### ISSUE TITLE
AMARETTO new package submission

### ISSUE THREAD

**Issue by ogevaert** [Bioconductor/Contributions#1001]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gevaertlab/AMARETTO

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ogevaert** [comment]
@jayendrashinde91

**Comment by ogevaert** [comment]
@mtmorgan Hi Martin, just a note, we have been able to resolve all warnings and errors. 
Let us know if we need to do anything else to have the package reviewed.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Consider a more extensive Description: field, like a paper abstract.

- The License: field says that the package is licensed under MIT but the LICENSE file is Apache. Please clarify.

vignettes

- please remove vignette 'build' products, i.e., the pdf file, from the vignettes directory; these are created when the package is installed.

- the vignette needs to contain evaluated R code chunks, rather than static code. Most code in the vignette should be evaluated, with the exception of package installation instructions.

- Use `TargetDirectory <- tempfile()` for temporary file locations.

- usually only a single .gitignore file (in the top-level directory) is required.

R: the following comments are about specific locations in your code, but the issues come in a number of places.

- Consider using [BiocFileCache][1] so that both your user and the build system only download large files once.

- e.g., amaretto_download.R:21 use `message()` rather than `cat()` when providing informative messages to users. Note that `message()` pastes its arguments together, so that `cat(paste0("foo ", bar))` becomes `message("foo ", bar)`.

- e.g., amaretto_download.R:42 this command is only executed if there are no prior errors, otherwise the user is surprised to find their directory changed 'behind their backs'. At the start of the function, ensure that the original directory is restored no matter what happens by using

    ```
    ori.dir <- getwd()
    on.exit(setwd(ori.dir)
    ```

- amaretto_download.R:59 I'm not an expert on TCGA, but am concerned that your efforts duplicate those available in other Bioconductor packages; maybe @LiNk-NY or @lwaldron can comment further.

- amaretto_download.R:99 `return(cat(...))` is confusing use

    ```
    cat(...)
    return()
    ```
    
- amaretto_download.R:104 use [httr][2] instead of `getURL()` and other approaches to internet access. For instance, `stop_for_status()` can be used to test for failed access, rather than trying to scrape (amaretto_download.R:143) output values. Likewise facilities for checking status, `write_disk()`, etc.

- amaretto_download.R:147 `stop(paste0(...))` can usually be written `stop(...)`. On the other hand amaretto_visualize.R:43 needs to include spaces `"... Module ", ModuleNr, " since..."`

- amaretto_functions.R:185 use `seq_len(AMARETTOresults$NrModules)` to avoid surprise when `AMARETTOresults$NrModules == 0`

- amaretto_functions.R:209 use 'pre-allocate and fill' or simply `lappy()` and friends rather than inefficient copy and append; see [robust and efficient code][3].

- amaretto_functions.R:217 use vectorized (one call to an R function) rather than iterative (one call per element) calculations, e.g., `colMeans()` rather than `apply(., 2, mean)`. See also functionality in the [matrixStats][] package

- amaretto_htmlreport.R:88 this and other code in this file is basically unreadable! break at 'logical' locations rather than at fixed width, e.g.,
    ```
    dt_regulators <- 
      datatable(
        rownames_to_column(as.data.frame(ModuleRegulators), "RegulatorIDs") %>% 
        dplyr::rename(Weights = "ModuleRegulators") %>% 
        mutate(
          RegulatorIDs = paste0(
            "<a href=\"https://www.genecards.org/cgi-bin/carddisp.pl?gene=", RegulatorIDs, "\">", 
            RegulatorIDs, 
            "</a>"
          )
        ), 
        class = "display", 
        extensions = "Buttons", 
        rownames = FALSE, 
        options = list(columnDefs = list(list(width = "200px", targets = "_all")), 
        pageLength = 10, 
        dom = "Bfrtip", 
        buttons = c("csv", "excel", "pdf")), 
        escape = "Weights"
     ) %>%  ...
    ```
  consider other approaches, too, e.g.,, defining `base_url = ...` outside the complicated experssion or using [whisker][4]. Many other examples of unusual rather than (mathematically) logical line breaks generally make your code very difficult to read.

- amaretto_preprocess.R: 674 Another (of many!) examples where a simple lapply would be both easier to read and more efficient.

man

- pay attention to line widths, especially in examples, where many environments present man pages formatted to a width of 80 characters.

- most man pages should have runnable code (not just loading a data set like AMARETTO_EvaluateTestSet.Rd!)

other

- please 'clean up' the master branch of the repository to include only files necessary for your package, e.g., removing AMARETTO-manual.pdf and files/.

[1]: https://bioconductor.org/packages/BiocFileCache
[2]: https://cran.r-project.org/package=httr
[3]: https://bioconductor.org/developers/how-to/efficient-code/
[4]: https://cran.r-project.org/package=whisker
[matrixStats]: https://cran.r-project.org/package=matrixStats

**Comment by jayendrashinde91** [comment]
@celineeveraert @monabiyan

**Comment by lwaldron** [comment]
The TCGA data access does seem extremely complicated, getting RNAseq2GeneNorm from curatedTCGAData and GISTIC with a long get_firehoseData() function copied from MethylMix. The following probably does what you need:

```
library(curatedTCGAData)
library(TCGAutils)
mae.orig <- curatedTCGAData("ACC", assays=c("GISTIC_AllByGene", "RNASeq2GeneNorm"), dry.run = FALSE)
# Separate normal tissues etc; this might be followed by removal of 
# unwanted sample types or selection of wanted sample types
mae <- splitAssays(mae.orig)
# Merge any remaining replicates
mae <- mergeReplicates(mae)
# Only if you want to align specimens / columns of each assay
mae <- intersectColumns(mae)
# Only if you want to align genes / rows of each assay
mae <- intersectRows(mae)
listofmatrices <- assays(mae) #can write to disk or do whatever you want then
```

A few other thoughts in addition to Martin's:

* amaretto_functions.R:31:  It seems unconventional and maybe dangerous to supersede the `assays` generic (which has methods for `MultiAssayExperiment` and `SummarizedExperiment`) with a data object

* amaretto_functions.R:34: Why serialize then save `curatedTCGAData` results? It duplicate the caching procedure that ExperimentHub is already doing automatically, except with extra steps and disk usage, and copying files from the ExperimentHub cache to another directory every time the function is run

* * amaretto_functions.R:251: Creates an output device within a function to create a pdf, so there's no user control over figure size, fonts, etc. Maybe this needs to be done because of many pages of output, but can you at least use `...` to pass arguments to pdf() to allow users to modify the output device? Question: does this create huge pdf files due to large cluster dendrograms and size of heatmap grid?

* amaretto_functions.R:271: It isn't necessary to include `paste0` inside `file.path()`, which already performs a paste0 on its arguments.

Vignette: Note that `>BiocManager::install("gevaertlab/AMARETTO")` installs from GitHub, not Bioconductor

**Comment by LiNk-NY** [comment]
I agree with Levi @lwaldron. 

A couple of additional notes: 
* I would avoid saving PDFs for the user (unless explicitly requested by the user).
* There are  functions that identify samples in assays such as `sampleTables` in `TCGAutils` in conjunction with `data("sampleTypes")` which would save you some code in `TCGA_GENERIC_GetSampleGroups`. You can also look into `TCGAsampleSelect`.

Best, 
Marcel

**Comment by nathaliepochet** [comment]
Thanks so much @lwaldron, @mtmorgan and @LiNk-NY for your suggestions! We'll be making improvements according to your suggestions!

Kind regards,
Nathalie & Olivier

**Comment by jayendrashinde91** [comment]
Thank you @lwaldron for this interesting suggestion. We have tested the packages curatedTCGAData and TCGAutils to download data. Indeed the firehose approach is a little complicated, but GISTIC data from curatedTCGAData does not match in the number of samples to the GISTIC data from Broad Firehose for few cancer types. This was the motivation to stick to get_firehoseData(). Could you kindly recommend a way to circumvent this issue in implementing download with curatedTCGAData()?

Best regards,
Jay & Olivier

**Comment by lwaldron** [comment]
Which GISTIC profiles are missing (or extra)? I'm surprised, and would like
to investigate...

Il lun 18 feb 2019, 8:31 PM Jayendra Shinde <notifications@github.com> ha
scritto:

**Comment by mtmorgan** [comment]
I'm not exactly sure where this issue stands? Is it ready for continue review?

**Comment by ogevaert** [comment]
We are working with Vincent to fix a number of other issues as well. So we will be ready and respond to your review in the next few days.

**Comment by jayendrashinde91** [comment]
Dear reviewers @mtmorgan @lwaldron @LiNk-NY 
Thank you for your suggestions.
We added most of your suggested edits and made critical changes with the coding style for the package to be compliant with the Bioconductor submission.
 
* DESCRIPTION
 
* [x]  Consider a more extensive Description: field, like a paper abstract.
* [x]  The License: field says that the package is licensed under MIT but the LICENSE file is Apache. Please clarify.
 
* vignette
 
* [x] please remove vignette 'build' products, i.e., the pdf file, from the vignettes directory; these are created when the package is installed.
* [x]  the vignette needs to contain evaluated R code chunks, rather than static code. Most code in the vignette should be evaluated, with the exception of package installation instructions.
* [x]  Use `TargetDirectory <- tempfile()` for temporary file locations.
 
* R
 
* [x]  Consider using [BiocFileCache](https://bioconductor.org/packages/BiocFileCache) so that both your user and the build system only download large files once.
* [x]  e.g., amaretto_download.R:21 use `message()` rather than `cat()` when providing informative messages to users. Note that `message()` pastes its arguments together, so that `cat(paste0("foo ", bar))` becomes `message("foo ", bar)`
* [x]  e.g., amaretto_download.R:42 this command is only executed if there are no prior errors, otherwise the user is surprised to find their directory changed 'behind their backs'. At the start of the function, ensure that the original directory is restored no matter what happens by using
 
* amaretto_download.R:59 I'm not an expert on TCGA, but am concerned that your efforts duplicate those available in other Bioconductor packages; maybe @LiNk-NY or @lwaldron can comment further.
 
We had some discrepancy in the downloads using curatedTCGA for certain cancer types.
The number of samples varied using  curatedTCGAData() and AMARETTO_Download()

* [x] amaretto_download.R:104 use [httr](https://cran.r-project.org/package=httr) instead of `getURL()`
* [x] amaretto_functions.R:185 use `seq_len(AMARETTOresults$NrModules)` to avoid surprise when `AMARETTOresults$NrModules == 0`
* [x] amaretto_functions.R:209 use 'pre-allocate and fill' or simply `lappy()` and friends.
* [x] amaretto_functions.R:217 use vectorized (one call to an R function) rather than iterative (one call per element) calculations, e.g., `colMeans()` rather than `apply(., 2, mean)`.
* [x] amaretto_htmlreport.R:88 this and other code in this file is basically unreadable!
* [x] amaretto_preprocess.R: 674 Another (of many!) examples where a simple lapply would be both easier to read and more efficient
 
* man
 
* [x] pay attention to line widths, especially in examples, where many environments present man pages formatted to a width of 80 characters.
* [x] most man pages should have runnable code (not just loading a data set like AMARETTO_EvaluateTestSet.Rd!)
 
* other
 
* [x] please 'clean up' the master branch of the repository to include only files necessary for your package, e.g., removing AMARETTO-manual.pdf and files/.
* [x] usually only a single .gitignore file (in the top-level directory) is required.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ogevaert.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AMARETTO")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AMARETTO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
