### ISSUE TITLE
BgeeCall package

### ISSUE THREAD

**Issue by jwollbrett** [Bioconductor/Contributions#1002]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BgeeDB/BgeeCall

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
Hi @jwollbrett ,

Before we do a package review it's important that your package build status is clean on the Single Package builder i.e no WARNINGS, NOTE, ERROR messages. 

Please fix them before we are able to continue with a review. 

Best,

Nitesh

**Comment by nturaga** [comment]
Hi @jwollbrett 

You have 2 weeks from today to get back to me regarding improving and getting your package to a reviewable state (i.e no BUILD , CHECK, INSTALL) errors on the build machine. 

We can close the issue if it takes longer, and reopen when you are able to actively develop. 

Best,

Nitesh

**Comment by jwollbrett** [comment]
Hello Nitesh,

I am currently on holiday and will be back the 11th of march. I will solve
this build/check problem before the middle of march.
Sorry.

Julien

Le ven. 22 févr. 2019 à 05:30, Nitesh Turaga <notifications@github.com> a
écrit :

**Comment by nturaga** [comment]
Hi @jwollbrett ,

That is fine. I'll close the issue and you can reopen it once you are back.

Have a good holiday.

Nitesh

**Comment by jwollbrett** [comment]
Hi @nturaga ,

I have an issue with my package.
The build passed for windows (weird as I work on mac..) but failed on mac and linux.
The error on mac looks like that : 

dyld: Library not loaded: @rpath/libz.1.dylib
  Referenced from: /private/var/folders/gh/37kcv9bj20v2qnpgxq14hh1c0000gq/T/RtmpdziLp3/Rbuild117e75db4ce63/BgeeCall/kallisto/kallisto
  Reason: image not found

I am not able to understand where the problem comes from as I definitly never saw this message on my computer. Could you please have a look and confirm that the problem does not come from your devel server?
Could you please also reopen the issue?

Thank you

**Comment by jwollbrett** [comment]
Hello @nturaga 

Do you know if the error described in the previous message could come from your dev server?
I have no build error with my computer(MacOs Sierra)

**Comment by lshep** [comment]
It looks like an issue with the installation of kallisto.   Is kallisto a system dependency?  Looking at previous build reports,  You try to install this on a users system if it is not found;  This should never be done.  Any system dependencies should be listed in the DESCRIPTION file with the `SystemRequirements` field and the code in the R package that tries to install a program should be removed.   Your package should assume the users have installed the system dependency correctly based on instructions.  You should include installation instructions for kallisto if necessary inthe README and include an installation section in the vignette.

**Comment by jwollbrett** [comment]
Hello @lshep 
Yes kallisto is installed in the user system. 
It is not a system dependency as the user do not need to install it before running the package.  The "installation" consists in downloading and decompressing an archive. It has no impact on the user environment. 
This step is done automatically. We only check that kallisto has already been installed by the package on the user system in order to not install it if it has already been installed (from a previous use of the R package).
My package use three S4 objects and the user can choose to use its own version of kallisto by changing a boolean attribute of one S4 object. We really want to keep this download of kallisto as part of my pipeline. I tested this step on different computers with windows and macOs. I have never seen a bug.
I will test with a linux virtual machine this week to be sure that there is no bug with linux OS.
Why did you say that it "should never be done"?
How can you generate the vignette and run the tests and the examples if you add a dependency?

**Comment by nturaga** [comment]
Hi @jwollbrett 

I don't think having Kallisto install automatically is a good idea for two reasons,

1. You should not install software which is not advertised/mentioned in the DESCRIPTION file. 

2. There could be problems with downloading from github, and building the software manually which you don't anticipate on the user's host OS. You may add a function if you wish in your package which does this, something like `install_kallisto()`, and the user can run it if they don't have it installed.

You should just have Kallisto in the SystemRequirements, and let the user install on their own. You may write a help section in the vignette which instructs how to install.

Couple of quick review points before I provide a more comprehensive review, (A full review is easier when you have no ERRORS or warnings on your build report) 

1. Add Kallisto to the system dependencies

2. Add more details to the Description section in the DESCRIPTION file. Think of it like a paper's abstract.

3. Your vignette doesn't run because of a missing file, see below

```
Downloading kallisto for osx...
trying URL 'https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_mac-v0.45.0.tar.gz'
Content type 'application/octet-stream' length 2537204 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

Kallisto has been succesfully installed.
dyld: Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rbuildd6f71c97108/BgeeCall/kallisto/kallisto
  Reason: image not found
Will run kallisto using this command line : /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rbuildd6f71c97108/BgeeCall/kallisto/kallisto quant -i /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rbuildd6f71c97108/BgeeCall/intergenic_0.1/6239/kallisto/transcriptome_WBcel235/transcriptome.idx -o /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rbuildd6f71c97108/BgeeCall/intergenic_0.1/6239/kallisto/transcriptome_WBcel235/annotation_WBcel235_84/SRX099901_subset -t 1 --single -l 180 -s 30 --bias  /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rinstd6f7501bc522/BgeeCall/extdata/SRX099901_subset/SRR350955_subset.fastq.gz
dyld: Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rbuildd6f71c97108/BgeeCall/kallisto/kallisto
  Reason: image not found
Warning in .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of
  type stop_codon. This information was ignored.
'select()' returned 1:1 mapping between keys and columns
Quitting from lines 113-114 (bgeecall-manual.Rmd)
Error: processing vignette 'bgeecall-manual.Rmd' failed with diagnostics:
can not generate presence/absence calls.
                Abundance file is missing : /private/var/folders/6d/6dsfg6190rs6qm2fvbyml920smsq5s/T/RtmpPUpj4p/Rbuildd6f71c97108/BgeeCall/intergenic_0.1/6239/kallisto/transcriptome_WBcel235/annotation_WBcel235_84/SRX099901_subset/abundance.tsv.
--- failed re-building ‘bgeecall-manual.Rmd’
```


Best,

Nitesh

**Comment by jwollbrett** [comment]
Hello @nturaga ,

I solved some problems with my package and I did some modifications regarding to your comments.
- I wrote a more precise description in the DESCRIPTION file
- I added kallisto as a SystemRequirement in the DESCRIPTION file

The build and check steps on both windows and mac do not create ERROR. I have only one warning because I do not have "@return" section in the documentation of some functions. It corresponds to functions that do not return anything. What should I do with this WARNING ? Should I add a "@return" section even if I do not return anything? Should I return 1 or TRUE when there is no return?

There is still one ERROR when building the package on mac. I can not reproduce it (I tested my package in 5 different mac), I can not solve it.
I already saw this error (dyld: Library not loaded: @rpath/libc++.1.dylib) on my computer a long time ago. Its origin was a R package that was not compatible with my version of R. I had to uninstall this package manually and install an up to date version in order to solve this error.
Could you please provide me the version of all dependancies loaded to your mac os development server when my package is built?

**Comment by jwollbrett** [comment]
Hello,

Today I will try to reproduce the error with a computer using El Capitan (10.11.6). 
Do you have any news or information about the possible origin of this error ? 
Is it possible to provide me a list of all version of the dependencies?

Please tell me how I should solve this warning message

> WARNING: Add non-empty \value sections to the following man
      pages: man/create_kallisto_index.Rd, man/download_kallisto.Rd,
      man/merge_transcriptome_and_intergenic.Rd, man/run_kallisto.Rd,
      man/run_tximport.Rd

Thank you

**Comment by jwollbrett** [comment]
Hello,
I built my package on El capitan without any error.
I am still not able to reproduce the error.

See below my sessionInfo
```
R Under development (unstable) (2019-03-18 r76245)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] C/fr_CH.UTF-8/fr_CH.UTF-8/C/fr_CH.UTF-8/fr_CH.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] rtracklayer_1.43.3   GenomicRanges_1.35.1 GenomeInfoDb_1.19.2 
[4] IRanges_2.17.4       S4Vectors_0.21.18    BiocGenerics_0.29.2 
[7] BgeeCall_0.99.10    

loaded via a namespace (and not attached):
 [1] Biobase_2.43.1                httr_1.4.0                   
 [3] tidyr_0.8.3                   bit64_0.9-7                  
 [5] AnnotationHub_2.15.8          topGO_2.35.0                 
 [7] shiny_1.2.0                   assertthat_0.2.1             
 [9] interactiveDisplayBase_1.21.0 BiocManager_1.30.4           
[11] blob_1.1.1                    GenomeInfoDbData_1.2.0       
[13] Rsamtools_1.99.4              yaml_2.2.0                   
[15] progress_1.2.0                pillar_1.3.1                 
[17] RSQLite_2.1.1                 lattice_0.20-38              
[19] glue_1.3.1                    digest_0.6.18                
[21] promises_1.0.1                XVector_0.23.2               
[23] htmltools_0.3.6               httpuv_1.5.0                 
[25] Matrix_1.2-17                 XML_3.98-1.19                
[27] pkgconfig_2.0.2               biomaRt_2.39.2               
[29] SparseM_1.77                  zlibbioc_1.29.0              
[31] purrr_0.3.2                   xtable_1.8-3                 
[33] GO.db_3.7.0                   later_0.8.0                  
[35] BiocParallel_1.17.18          tibble_2.1.1                 
[37] SummarizedExperiment_1.13.0   GenomicFeatures_1.35.9       
[39] magrittr_1.5                  crayon_1.3.4                 
[41] mime_0.6                      memoise_1.1.0                
[43] evaluate_0.13                 graph_1.61.0                 
[45] tools_3.6.0                   data.table_1.12.0            
[47] prettyunits_1.0.2             hms_0.4.2                    
[49] matrixStats_0.54.0            stringr_1.4.0                
[51] Rhdf5lib_1.5.4                DelayedArray_0.9.8           
[53] AnnotationDbi_1.45.1          Biostrings_2.51.5            
[55] compiler_3.6.0                rlang_0.3.2                  
[57] rhdf5_2.27.15                 grid_3.6.0                   
[59] RCurl_1.95-4.12               tximport_1.11.7              
[61] bitops_1.0-6                  DBI_1.0.0                    
[63] curl_3.3                      R6_2.4.0                     
[65] GenomicAlignments_1.19.1      knitr_1.22                   
[67] dplyr_0.8.0.1                 bit_1.1-14                   
[69] stringi_1.4.3                 Rcpp_1.0.1                   
[71] BgeeDB_2.9.0                  tidyselect_0.2.5             
[73] xfun_0.5
```

**Comment by mtmorgan** [comment]
Please follow the [advice][1] to have kallisto as a system dependency rather than to download it to the local system. A basic problem with your current approach is that it tries to install into the package installation directory, which will frequently be unwriteable (e.g., when centrally administered on a shared server). The build system illustrates a second problem -- user systems are different in many ways, and you as remote developer are in a poor position to troubleshoot.

Please also avoid evaluating [instructions to install your package][2] in the vignette.

[1]: https://github.com/Bioconductor/Contributions/issues/1002#issuecomment-473878176
[2]: https://github.com/BgeeDB/BgeeCall/blob/master/vignettes/bgeecall-manual.Rmd#L50

**Comment by jwollbrett** [comment]
Thank you for this answer.

As asked I removed the default download of kallisto (It is still possible for the user to ask the package to download kallisto but it is not the default option anymore).
I updated the documentation to describe available options to install kallisto.
I also added kallisto as a systemRequirements in the DESCRIPTION file.

I bumped the version of the package.
I now have errors to build my package as kallisto is not installed in your server.
If kallisto is not installed the package will not be able to create the vignette, run tests, and run examples.
How do you usually manage these system dependencies?

Best,

Julien

**Comment by mtmorgan** [comment]
@lshep I think we should install kallisto on the build servers!

Though actually @jwollbrett the purpose of the vignette is to illustrate your software, rather than kallisto, so a different option would be to capture relevant data from a kallisto run and use it to illustrate the vignette. The data could be represented in your package if small, or in [ExperimentHub][1] if large, or perhaps there is already an [experiment data][2] package or ExperimentHub resource that you could re-use.

[1]: https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html
[2]: https://bioconductor.org/packages/devel/BiocViews.html#___ExperimentData

**Comment by lshep** [comment]
I would be more in favor of the later point made -  If Kallisto isn't needed directly in the package use than providing the data with the package would be a better option.

**Comment by jwollbrett** [comment]
Hello,

BgeeCall is a workflow package. Running kallisto is one step of this workflow but there is other steps before (e.g merging user transcriptome and bgee intergenic regions) and after (e.g present/absent gene expression calls generation).

1. Of course I would be very happy if you can add kallisto to your build server.
2. It could be possible not to install kallisto to your server but it will have some negative impacts on my package :
- I will not be able to call the main function of my workflow in the quickstart section of my vignette or at least I will not be able to evaluate it.
- I will not be able anymore to test and/or provide runnable examples for some functions

If you choose the 2nd option could you please allow me to add more not runnable examples and more not evaluated chunks than usually ?
I understand that this issue is time consuming for everyone and I will adapt whatever solution you choose.

Best,

Julien

**Comment by mtmorgan** [comment]
Thanks for your flexibility. I think option 2 is better, and that the non-runnable examples / evaluated code chunks are a necessary consequence of this and acceptable from the project's perspective.

**Comment by jwollbrett** [comment]
Hello,

It looks like we are getting closer to a version ready to release 😃 
I finally managed to remove all dependencies to kallisto in my examples, vignette, and tests.
I do not have error anymore but I still have 1 Timeout (on celaya2), 1 Warning and 6 Notes.

- Do I need to change something for the TIMEOUT? 

- It looks like the WARNING is because I do not have "@return" section in the documentation of some functions. It corresponds to functions that do not return anything. What should I do with this WARNING ? Should I add a "@return" section even if I do not return anything? Should I return 1 or TRUE when there is no return? Sorry for this naïve question but I am not aware of such best practices in R.

- Is it mandatory to remove all NOTES? 

Thank you.

**Comment by mtmorgan** [comment]
A 15 minute timeout is very generous; yes you should work further, e.g., reducing the examples with double-digit execution times by illustrating (with subsets of data) the functionality rather than providing comprehensive examples.

for `@return` it would be reasonable to indicate that the function is invoked for its side effect. Note that even functions that we typically think of as being invoked for their side effect, like plotting, actually return objects that can be captured and further processed, or that are useful for further processing.

The goal isn't to get a NOTE / WARNING free build report but to get a robust package; I would not worry about the existing NOTEs, other than being aware of the overall size of the package.

I see you have chosen terms for the Workflows biocViews category, but workflows generally illustrate use of multiple packages to illustrate end-to-end analyses. The packages usually have vignette(s) and very little if any R code, since they are illustrating integrated package use. It seems though that your package introduces significant new functionality, and is really a standard software package. As such it should be tagged with terms for the [software hierarchy][1] exclusively.

[1]: https://bioconductor.org/packages/devel/BiocViews.html#___Software

**Comment by jwollbrett** [comment]
Hello,

First of all, thank you for your clear answer.

I added @return with a short description to all functions. 
I also optimized runtime of all my examples and tests.
The package is now building/checking without error/warning/timeout.

I still have 6 NOTES remaining.

The overall size of the package is 9Mb. The size of the extdata folder is 8.6Mb
I created a toy dataset (5Mb) allowing to run the main function of the package (and then run kallisto). As kallisto is not installed on your server this toy dataset is not used anymore but I
still describe how to use it in the quick start section of the vignette. In order to allow user to reproduce result present in the vignette I choose to keep it.
Is this overall size ok for you?

I will be available the full week and will be reactive to any suggestion of modification (I know you are busy with the new release)

**Comment by jwollbrett** [comment]
Hello @nturaga ,
The package looks ready for a review 😄 
Could you please confirm that the package can still be part of Bioconductor 3.9 (if I am able to quickly manage modification you could ask me to do) ?
Thank you

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

* There can be only one maintainer, [cre] can be used with one person only.

```
“Authors@R or Author/Maintainer:” fields: Use either Authors@R field or Author: and Maintainer: fields, not both. A maintainer designation (cre for Authors@R ) is required with an actively maintained email. This email will be used for contact regarding an issues that arise with your package in the future. We prefer the Authors@R format giving all the authors with appropriate roles. For persons with an ORCID identifier (See ORCiD for more information) provide the identifier via an element named “ORCID” in the comment argument of person(). Example: person("Lori", "Shepherd", email=Lori.Shepherd@roswellpark.org, role=c("cre", aut"), comment = c(ORCID = "0000-0002-5910-4010")).

Only one person should be listed in the Maintainer field to ensure a single point of contact. This person by default will have commit access to the git repository on git.bioconductor.org. Commit access can be given to other developers by request on the bioc-devel mailing list. Another option is to add collaborators to the github repository. This approach enables development by many but restricts push access to git.bioconductor.org.
```

http://bioconductor.org/developers/package-guidelines/


## NAMESPACE

* ok

## R

* AbundanceMetadata.R: ok

* BgeMetadata.R :

	* Use getters and setters instead of accessors (@) in your methods.

	http://bioconductor.org/developers/package-guidelines/ (`Avoid use
    of direct slot access with @ or slot(). Accessor methods should be
    created and utilized`)

	* remove commented code.
	
* Maybe come up with a better way than hardcoding these links? What if
  they change? I would suggest a "unit test" in your package where
  these links are checked for existence. That way you know from the
  build report when these links go invalid so you can change them
  either manually or write a function to change them in an automated
  fashion.

	        kallisto_windows_url = 
            "https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_windows-v0.45.0.zip",
        kallisto_linux_url = 
            "https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_linux-v0.45.0.tar.gz",
        kallisto_osx_url = 
            "https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_mac-v0.45.0.tar.gz",
			 
* In listIntergenicRelease.R: 

	* Some `cat` statments should be replaced by `message`
      statements. Unless you want "Downloading...." to go to stdout	  
	  
	  The traditional output functions are:
			print()
			cat()
			message()
			warning()
			stop()
			
	  The first two functions (print() and cat()) send their output to
      stdout or standard output. The last three functions (message(),
      warning(), and stop()) send their output to stderr or the
      standard error.

	  It's possible that users would want to write a script and pipe
      the output of your package, since it uses Kallisto, which might
      take time. If you think of it in that regard, you might want to
      take a minute to really think about which messages you want
      going to stdout and std err.
	  
	  eg:
		  
			R -f "script.R" 1> log.out 2> log.err

* You want to use the function `isS4` instead of
  `typeof(userMetadata[[1]]) == "S4")`. It's more robust.
  
*  Use `seq_along(fastq_files)` instead of
   `seq_len(length(fastq_files)))`. Note the difference between the
   two.
   
## NEWS

* Make sure it's parsable by `utils::news`

## vignettes

* There is no sessionInfo() call at the end of the vignette. Make sure
  you follow the vignette section as closely as possible.

	http://bioconductor.org/developers/how-to/buildingPackagesForBioc/#vignettes

	http://bioconductor.org/developers/package-guidelines/#vignettes

**Comment by nturaga** [comment]
> Hello @nturaga ,
> The package looks ready for a review 😄
> Could you please confirm that the package can still be part of Bioconductor 3.9 (if I am able to quickly manage modification you could ask me to do) ?
> Thank you

Just as additional information, your package is pretty good now, and with a few minor modifications which were suggested in the review you can make it to the next release.

**Comment by jwollbrett** [comment]
Hello @nturaga ,

Thank you for your review.
I saw that submission deadline is Wed 24th (tomorrow). 
I will try to fix everything before this evening.

**Comment by jwollbrett** [comment]
Hello @nturaga ,

I did some modifications taking into account the comments of your review.

> # Review
> ## DESCRIPTION
> * There can be only one maintainer, [cre] can be used with one person only.
> 
> ```
> “Authors@R or Author/Maintainer:” fields: Use either Authors@R field or Author: and Maintainer: fields, not both. A maintainer designation (cre for Authors@R ) is required with an actively maintained email. This email will be used for contact regarding an issues that arise with your package in the future. We prefer the Authors@R format giving all the authors with appropriate roles. For persons with an ORCID identifier (See ORCiD for more information) provide the identifier via an element named “ORCID” in the comment argument of person(). Example: person("Lori", "Shepherd", email=Lori.Shepherd@roswellpark.org, role=c("cre", aut"), comment = c(ORCID = "0000-0002-5910-4010")).
> 
> Only one person should be listed in the Maintainer field to ensure a single point of contact. This person by default will have commit access to the git repository on git.bioconductor.org. Commit access can be given to other developers by request on the bioc-devel mailing list. Another option is to add collaborators to the github repository. This approach enables development by many but restricts push access to git.bioconductor.org.
> ```
> http://bioconductor.org/developers/package-guidelines/
> 

Done

> ## NAMESPACE
> * ok
> 
> ## R
> * AbundanceMetadata.R: ok
> * BgeMetadata.R :
>   
>   * Use getters and setters instead of accessors (@) in your methods.
>   
>   http://bioconductor.org/developers/package-guidelines/ (`Avoid use of direct slot access with @ or slot(). Accessor methods should be created and utilized`)
>  

I created getters/setters for slots of BgeeMetadata and UserMetadata classes that can be used by user.
 
>   * remove commented code.

Thank you. I totally forgot to reactivate these 3 lines of code.
Done

> * Maybe come up with a better way than hardcoding these links? What if
>   they change? I would suggest a "unit test" in your package where
>   these links are checked for existence. That way you know from the
>   build report when these links go invalid so you can change them
>   either manually or write a function to change them in an automated
>   fashion.
>   ```
>         kallisto_windows_url = 
>         "https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_windows-v0.45.0.zip",
>     kallisto_linux_url = 
>         "https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_linux-v0.45.0.tar.gz",
>     kallisto_osx_url = 
>         "https://github.com/pachterlab/kallisto/releases/download/v0.45.0/kallisto_mac-v0.45.0.tar.gz",

The package already tested that kallisto can be downloaded. 
I added a new unit test testing that the URL return a 200 status.

>   ```
> * In listIntergenicRelease.R:
>   
>   * Some `cat` statments should be replaced by `message`
>     statements. Unless you want "Downloading...." to go to stdout
>     The traditional output functions are:
>     print()
>     cat()
>     message()
>     warning()
>     stop()
>     The first two functions (print() and cat()) send their output to
>     stdout or standard output. The last three functions (message(),
>     warning(), and stop()) send their output to stderr or the
>     standard error.
>     It's possible that users would want to write a script and pipe
>     the output of your package, since it uses Kallisto, which might
>     take time. If you think of it in that regard, you might want to
>     take a minute to really think about which messages you want
>     going to stdout and std err.
>     eg:
>     ```
>       R -f "script.R" 1> log.out 2> log.err
>     ```

I was not aware of the differences between `cat` and `message`. Thank you. 
I replaced `cat` statements by `message` statements.

> * You want to use the function `isS4` instead of
>   `typeof(userMetadata[[1]]) == "S4")`. It's more robust.

Done

> * Use `seq_along(fastq_files)` instead of
>   `seq_len(length(fastq_files)))`. Note the difference between the
>   two.

Done
> 
> ## NEWS
> * Make sure it's parsable by `utils::news`
> 
> ## vignettes
> * There is no sessionInfo() call at the end of the vignette. Make sure
>   you follow the vignette section as closely as possible.
>   http://bioconductor.org/developers/how-to/buildingPackagesForBioc/#vignettes
>   http://bioconductor.org/developers/package-guidelines/#vignettes

Done

**Comment by nturaga** [comment]
Hi @jwollbrett 

You are really close to getting your package accepted. Thank you for the helpful commit messages so I can easily review your package.

I need you to fix the WARNING messages though,

```
* WARNING: Use TRUE/FALSE instead of T/F
      Found in R/ directory functions:
        generate_presence_absence()
```

Best,

Nitesh

**Comment by jwollbrett** [comment]
Hello @nturaga ,

Sorry for this warning message. Everything build/check well now.
Hope the package can still be part of Bioconductor 3.9 😃

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jwollbrett.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BgeeCall")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BgeeCall

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
