### ISSUE TITLE
evaluomeR package

### ISSUE THREAD

**Issue by neobernad** [Bioconductor/Contributions#1005]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/neobernad/evaluomeR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It would seem particularly important for a package like this to interoperate with other Bioconductor packages by re-use of [standard classes][1] especially [SummarizedExperiment][2]. Alternatively if this is not particularly Bioconductor-centric then perhaps it belongs on CRAN?

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by neobernad** [comment]
Dear reviewer,

We think it would be a great addition to include SummarizedExperiment as another input format in our methods, could it be added as an upgrade in a later version? Also, I'm a bioinformatics PhD student and the co-authors work in the bioinformatics domain. Therefore we are highly interested in focusing the package usage in the bioinformatics field. Could it be still submitted to Bioconductor?

Thanks,
José Antonio

**Comment by LiNk-NY** [comment]
Hi José, @neobernad 

Thank you for your submission. 
We consider packages that are inter-operable with existing Bioconductor
data structures and provide relevant functionality. 
If you would like more time to provide an interface with `SummarizedExperiment`, 
we can close the issue and you can re-open it at a later date. 

Best regards,
Marcel

**Comment by neobernad** [comment]
Dear reviewers,

We have added a new functionality, `seToDataFrame`. This method allows the user to transform a `SummarizedExperiment` object with an assay into a valid dataframe for our package functions.

Best regards,
José Antonio

**Comment by LiNk-NY** [comment]
Hi José, @neobernad 

When we talk about interoperability, we mean that functions in your package **support** and **use**
existing Bioconductor functions. Providing a coercion function does not ensure that your functions work with `SummarizedExperiment` and return `SummarizedExperiment` where appropriate. 

Best regards,
Marcel

**Comment by neobernad** [comment]
Hello Marcel,

Thank you for the clarification. The current state of the package uses `SummarizedExperiment` as the standard input and output for all our functionality.

Kind regards,
José Antonio

**Comment by LiNk-NY** [comment]
Hi José Antonio, @neobernad 
Thank you for making those changes.
I will get to your package in the next few days as there
are other packages waiting for review. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi José Antonio, @neobernad 

Thank you for your submission. 
Please see the package review below. 
If you have any questions, please post them here.

Best regards,
Marcel 

---

# evaluomeR #1005

* Overall, the package looks like a script turned into software.
* There are errant variables set inside functions repeatedly and there
is little attention to formatting.

## DESCRIPTION

* Consider combining `Author` and `Maintainer` fields into `Authors@R`
* Add a `BugReports` field
* Add additional `biocViews` items to better discoverability

## NAMESPACE

* Looks good.

## vignettes

* It looks thorough and well done.
* Please respect the 80 column width so that it is easier to read and possibly
maintain.

## inst/extdata

* Remove data in `extdata`. The folder should be used to store raw files if you
have functions that require to read raw data as an example.
* See `loadSample` bullet point in R section below.

## R/

* Use a more descriptive name instead of `correlations`
* Avoid the use of semi-colons. You can use `utils::globalVariables` for such
variables
* Avoid saving graphics for the user. Let users save graphics using the format
of their choosing. Remove `png` function and `path` and `label` arguments.
* Use `match.arg` in `loadSample` and provide all possible options as arguments.
For example, use `loadSample <- function(descriptor = c("ont-metrics", ...))`.
* Why not use `RData` or `rda` data and use `data(...)` to load example
datasets?
* If possible, avoid using 'orphaned' packages because they are not maintained
and may include poorly written code (`fpc`).
* No need to create `getAssay`, this is done by the `assay` function
for `SummarizedExperiment` objects
* `makeSummarizedExperimentFromDataFrame` can possibly replace what `createSE`
does
* Again, `createSEList` can be taken care of by converting your list of matrices
with `SimpleList` and then passing them along to the `SummarizedExperiment`
constructor function. Avoid loops when functionality is already available to
work with lists.
* Avoid **setting** seeds inside a function
* Avoid modifying user's `par` settings, use `on.exit` to re-establish them
before your function
* You shouldn't have to use `get` and `assign` functions in normal code
* Create a local package environment with variables that you to access across
functions. This will avoid the use of `env` argument for most plotting functions
* There isn't much difference in terms of programming between 'stability' and
'quality' functions. Perhaps you can combine these functions into one and
add an arugment for either `quality` or `stability`?

Minor:
* No need to `paste` error message before the stop function in R/helpers:L#79

**Comment by neobernad** [comment]
Hello Marcel, @LiNk-NY 

We developed every change listed in the review, except for the following bullets (explaining their reason):
* If possible, avoid using 'orphaned' packages because they are not maintained
  and may include poorly written code (`fpc`)
  > We have a dependency with that package so far.
* No need to create `getAssay`, this is done by the `assay` function for `SummarizedExperiment` object
  > The methods `getAssay`, `createSE` and `createSEList` are required, they are just wrappers for some `SummarizedExperiment` functionality. These methods are defined in the private scope of the package, thus the end-user  will not see them nor need to use them.
* There isn't much difference in terms of programming between 'stability' and 'quality' functions. Perhaps you can combine these functions into one and  add an argument for either `quality` or `stability`?
  > These two functionalities might differ from each other considerably in the future. We would like to keep them separately so that a further package update will not change the naming convention.

We hope the changes performed satisfy the Bioconductor needs.

Best regards,
José Antonio

**Comment by LiNk-NY** [comment]
Hi José Antonio, @neobernad 

* After consulting with my colleagues @hpages @lshep, it seems that `fpc` unfortunately
can be retired from CRAN at any moment and having a dependency on this
package will cause yours to break. I would recommend that you find a
replacement to the functionality provided in `fpc` or adopt the maintainership
of the `fpc` package yourself if you extensively used it. 

For more information see here: https://cran.r-project.org/src/contrib/Orphaned/README

* `getAssay` can be replaced with `as.data.frame(assay(se))` internally.
It is better to specify a minimum and necessary amount of functions
needed so that maintainership is easier. Other functions like `createSE` 
can be handled by a single or couple of lines (based on functionality) such as:

```
SummarizedExperiment(
    assays = data.matrix(dat), 
    colData = DataFrame(metrics = colnames(dat))
)
```

* For something like `createSEList`, you can coerce the list of matrix assays to
a `SimpleList` and then use `SummarizedExperiment` such as: 
`SummarizedExperiment(assays = as(data, "SimpleList"))`. It's best to keep it simple.
If you do need to check the matrices, create a helper function that runs `data.matrix`
when the matrix is not `numeric` and this helper can then be used before conversion to
`SummarizedExperiment`. 

* Why do you need so many variables assigned to `NULL` shortly before you set values
to them? It doesn't quite make sense to me. 

Best, 
Marcel

**Comment by neobernad** [comment]
Hi Marcel, @LiNk-NY 

Thank you for the review and comments, we have successfully finished all the bullet points listed above except for one of them:
I am having some trouble trying to create a `SimpleList`. The output list of the method `qualityRange` provides dataframes with different `colnames()`, not only in their label but also in their length:
```
library(evaluomeR)
data("rnaMetrics")
dataList <- qualityRange(data=rnaMetrics, k.range=c(2,3))
colnames(as.data.frame(assay(dataFrame$k_2)))
# "Metric" "Cluster_1_SilScore" "Cluster_2_SilScore" "Avg_Silhouette_Width" "Cluster_1_Size"       
# "Cluster_2_Size"
colnames(as.data.frame(assay(dataFrame$k_3)))
#"Metric" "Cluster_1_SilScore" "Cluster_2_SilScore" "Cluster_3_SilScore" "Avg_Silhouette_Width" 
# "Cluster_1_Size" "Cluster_2_Size" "Cluster_3_Size"
```
If both items in the list, `k_2` and `k_3`, would have the same `colnames()`, the next command would work:
`se = SummarizedExperiment(assays = as(dataList , "SimpleList"))`

However that is not the case, I have checked the `SummarizedExperiment` documentation but the example assays seem to have the same `colnames()` values. Do you know if it is possible to create different column names for each assay in the same SimpleList?

Thanks for your time,
José Antonio

**Comment by neobernad** [comment]
Dear all,

We have uploaded the latest version. It solves all the bullet points listed on https://github.com/Bioconductor/Contributions/issues/1005#issuecomment-471624889 except for the issue commented on https://github.com/Bioconductor/Contributions/issues/1005#issuecomment-474148410.

Could we have an update about the commented issue?

Thanks,
José Antonio

**Comment by LiNk-NY** [comment]
Hi José Antonio, @neobernad 

Thanks for following up on that. Yes, `SummarizedExperiment` only allows
assays with the same set of samples. You can go ahead and put them in as a list
of `SummarizedExperiment` objects.
You may also want to try `MultiAssayExperiment::ExperimentList` although there
are not many methods for that class because it's meant to accommodate several
rectangular shaped classes.

Best regards,
Marcel

**Comment by neobernad** [comment]
Hi Marcel, @LiNk-NY 

Thanks for your comment, we have just uploaded the latest version, where we use the `MultiAssayExperiment::ExperimentList`, instead of just a list of `SummarizedExperiment` for the method `qualityRange`.

We hope the package meets the requirements for Bioconductor.

Best regards,
José Antonio

**Comment by LiNk-NY** [comment]
Hi José Antonio, @neobernad 

If you plan on using `MultiAssayExperiment` this change works well. 
Otherwise, you may want to **avoid** the additional dependencies. 

I will accept your package and you can make the changes after it has been
added to Bioconductor. 

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/neobernad.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("evaluomeR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/evaluomeR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
