### ISSUE TITLE
gpuMagic package

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/Contributions#1007]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jiefei-Wang/gpuMagic

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Jiefei-Wang** [comment]
Hello Daniel,

I have fixed the compilation errors. It looks like the package has successfully built. Since the builders do not have an OpenCL driver, an error message was thrown by my package indicating that there is no OpenCL device installed. 

Because this error is related to the builder system, could we install the OpenCL driver on each builder system? Or should we provide an option to suppress the build of vignettes and unit tests? 

Thanks,
Jiefei

**Comment by mtmorgan** [comment]
For complicated system requirements like these, installation instructions should be summarized in the SystemRequirements: field of the DESCRIPTION file, perhaps referencing an 'INSTALL' or 'README' file in the package git repository. The instructions should be specific, so that a naive user can follow them and get a working system going. An example might be https://github.com/Bioconductor/ensemblVEP

**Comment by dvantwisk** [comment]
Hey @Jiefei-Wang 

I just want to confirm that you are still working on getting your package to run without errors. I can imagine that getting OpenCL code to work across multiple systems is difficult.

**Comment by Jiefei-Wang** [comment]
Yes, I'm going to make a version bump and see if I can remove the building errors in the mac builder. Also, this version bump will include several important updates of my package. For the other platform, since they don't have appropriate drivers, there is no way to fix the error message.

**Comment by dvantwisk** [comment]
Here's a review of your package. I'm going to need a little more time to look more thoroughly over your C code and I suppose the additions that you are adding to your vignette. Overall, the package look very well written. I have three overall issues.

- You seem to be using the copy-and-append pattern very frequently. E.g. declaring `vec <- c()` and then add to it in a for-loop with `vec <- c(vec, more_vec)`. It would be much more efficient to declare the variable with `vapply()` or `sapply()`. I'm not sure if you are aware of this or that you choose to ignore this because the sections of code that they are run on only add negligible run-time.
- There seems to be a lot of chunks of code that are repeated (except for a few small details) especially within the parser files. You may consider creating functions for repeated code.
- There are some spelling and grammatical errors that should be corrected. Since the package looks very useful, I think making the documentation as clear as possible good to do.

[REQUIRED] tags must be changed or addressed. [CONSIDER] tags are change that are advisable but not required. Please message me back when you are done making changes or have further questions.

DESCRIPTION
- [ ] [REQUIRED] In `Title:` change to "... to compile R functions and ...".
- [ ] [REQUIRED] A few grammar issues in to polish up in `Description:`. Change
first line to "The package aims to help users write openCL code ...". Second
line "... a CPU or a GPU". Third line "... run their openCL code".

R/RCParserFunc.R
- [ ] [REQUIRED] L522-531: I've seen the use of copy-and-append patterns a few
times in your pacakge now and just want to make sure you are aware that this is
very iniffiecient in R. specifically at L530 where the end the loop by
continuously reallocating the `B_vec` to a larger vector. A better way to right
this code would be:
```
B_vec <- vapply(seq_len(vectorize_size), function(i) {
    B_multi_sub_vector = C_element_getCExp(
    varInfo, rightVar2, sub = c(paste0("gpu_k*gpu_vectorize_size+gpu_start+", i - 1), "gpu_j"),
    opt = list("gpu_j", c("gpu_k")), extCode = B_multi_sub_vector$extCode)
    B_multi_sub_vector$value
}, numeric(<what the length of B_multi_sub_vector$value))
```
If the length / type of `B_multi_sub_vector$value` isn't known, the less
efficient `sapply` can be used.
There are other parts of your package that are using this pattern as well that
should be changed.
Again, it may be the case the this operation is very short and negligable, but
I urge you to not use the copy-and-append pattern.

- [ ] [CONSIDER] L522-531, 677-685: It seems that you have repeated code here.
Aside from soem of the labels that you are applying, the code appears to be the
same. Please consider considleidating this to a single function.

R/RCParser_elementOP.R
- [ ] [CONSIDER] L118-131: Very little difference between functions, could
probably be reused.

R/gpuApply.R
- [ ] [REQUIRED] Assorted grammar fixes:
        - L5: "A GPU version of the sapply function"
        - L9: "This function compiles the R code and runs it on ..."
        - L13: misspelled "element"
        - L219: "There are a few options that are ..."
        - L251: "Compile the R function without executing it on the device"

R/gpuFunctions.R
- [ ] [REQUIRED] Assorted grammar fixes:
        - L89: "... index before using thsi function"
        - L185,224: "This function gets the computing precision when compiling the ..."
        
R/gpuMatrix.R
- [ ] [REQUIRED] Assorted grammar fixes:
        - L256: "It does not have any effect"

R/gpuResourcesManager.R
- [ ] [REQUIRED] L110-117: Another example of the copy-an-append pattern why not
just isolate each statment and declare each with `vapply()`/`sapply()`.

R/kernelManager.R
- [ ] [REQUIRED] Assorted grammar fixes:
        - L4: "... the device and executes it on the device."
        - L16: "... specifies the number of threads that will be ..."
        - L17: "... in openCL functions."
        - L39: misspelled "containing"
        - L49: "... the number of threads ..."

R/pkgFunc.R
- [ ] [REQUIRED] Assorted grammar fixes:
        - L394: Do some operation with copying memory

tests
- [ ] [CONSIDER] `test_resourcesManager.R` has no tests

vignettes
- [ ] [REQUIRED] Assorted grammar fixes:
    `Quick_start_guide.Rmd`
        - L26: "... ability to compile R code ..."
               "... language so parallelization using the CPU is also supported."
        - L29: "To get started, it is always a good idea ..."
        - L34: "The devices listed above show the current available devices, if you cannot see the dive, you should ..."
        - L39: "The package also has a GPU resource manager."
        - L46: "If you are using a Nvidia graphics card, if it good practice to ..."
               "... will reset the graphics card if the ..."
               "If you are usign another device such as an Intel graphics card ..."
        - L48: "Changing it to a larger number such as 20 seconds will make most programs work."
        - L51: "... with the **sapply** function."
        - L60: "...by using the **sapply** function."
        - L95: "... Keys to Success"
        - L96: "... that you may have when using the function <which function?>."
               "... the limitations of the openCl language."
        - L98: "Important notes"
        - L99: "All objects in openCL are either a scalar or a matrix, vectors are not supported."
        - L100: "I did not test them yet ..."
                "... may not work as you expect ..."
        - L101: "... for-loops or if-statements, it may ..."
        - L102: "... you do self assignments ..."
                "... will not work ...."
        - L103: "... poor design of the ..."
        - L106: "... without knowing its size ..."
        - L114: "... the value of the macro will be plugged into the function and is known by the compiler, for example,"
        - L129: "... you cannot change the value ..."        
        - L132: "... in your code ..."
        - L152: "... dynamically subset it to ..."
                "... available reference functions."
        - L155: "Since dynamic allocation ..."
                "... may wonder if returning an object with ..."
                "... in your code, the package ..."
                "... return a variable of undetermined length ..."
                "... enough space for your return variable ..."
        - L181: "In the future, ..."
        - L183: "Operations between ..."
        - L184: "..., and matrix to scalar operations. However, for matrix to matrix operations ..."
        - L186: "Error checking"
        - L187: "For performance reasons, the package only performs error checking ..."
                "... when an error occurs on GPU ..."
                "... with the **sapply** function to check for possible errors ..."
        - L190: "... you can create it without limitations."
                "... compact format and does not use memory."
                "... to creat a sequence variable in memory, ..."
        - L193: "... does not support calling user-defined R functions ..."
        - L284: "The package currently supports a limited number of functions ..."
        - L326: "Besides tradiational R functions, the pacakge also provides ..."
                "... is for saving memory usage ..."

    - `Customized-openCL-code.Rmd`
        - L35: "... feature a to relieve you ..."
               "... tons of great introductions on the ..."
        - L75: "... The availiable types are listed in the end ..."
               "... code also matches it."
               "... the '.kernel' function provides a set of macros ..."
               "... These macros will ..."
        - L105: "... code, so the function definition is ..."
                "Lowring the variable precision can make the code run faster."
        - L109: "... regarding the use of the `.kernel` function, ..."
                "the reader is referred ot the documentation of the `.kernal' function as the complementaiton" <what does this mean?>
        - L111: "... through the `.device` argument ..."
                "... please do so by calling the `setDevice` functin."
        - L114: "... multiple `.kernel` function calls with different device IDs to parallelize the hardware."

- [ ] [REQUIRED] There are many `eval=FALSE`s litered throught the vignettes.
Is there a reason why you are using them? We generally don't allow there use if
the code is meant to be runnable by the user.

- [ ] [REQUIRED] Probably a good idea to add a `sessionInfo()` section to the
end of the vignettes.

- [ ] [CONSIDER] I realize you are still working on the vignettes. I suggest
that you add a section to a vignette about installing the package as well as the
SystemRequirments that you list in `DESCRIPTION`. I think this installation
process may be non-trivial to the user.

**Comment by Jiefei-Wang** [comment]
Hello @dvantwisk, thanks for your super detailed suggestions. I will follow them step by step and correct the problems. I did aware of the potential performance issues for the appending function, I will try to clean them as many as I can. Removing the redundant functions may contain a lot of works and I may need to fix them after several version bumps. The grammar issues will be correct.

**Comment by dvantwisk** [comment]
The redundant code issue isn't very important, the issue comes down to tidying up your code a bit in the parser may make it easier to understand and fix later. Don't worry too much about it if it's way too much effort.

**Comment by Jiefei-Wang** [comment]
Hello @dvantwisk,

I have finished the revision of my package. Could you please review it again? Here are a few notes:

- The grammar issues have been fixed. 

- Some copy-and-append codes are unchanged since they either require iteration or need to ignore the `NULL` value. The others have been revised.

- The redundant code will be solved in a future release. It requires a lot of work to simplify them.

- The unfinished vignette has been removed from the package. Installation instruction is added as a separate vignette.

Thanks,
Jiefei

**Comment by dvantwisk** [comment]
The changes look good so far.

I understand that the redundant code may take a while to fix and that it is really only necessary to make the package's code look cleaner.

When it comes to the copy-and-append patterns, it seems that despite not being able to vectorize or use `vapply()`, you have been preallocating the vectors that you are declaring (i.e. `vec <- vector(length=x)`) and then creating them iteratively using `vec[i] <- val` in a for-loop. This is a better way of doing things than the copy-and-append pattern, so do it where you can. I suppose if you can guarantee the cases that you use the copy-and-append pattern iterates for only a small number of times (e.g. if the can guarantee an upper bound of 10 for iteration across a copy-and-append pattern), it isn't a big concern.

I've looked through you `src` directory again after looking into a bit more about `OpenCL`. Admittedly, I am not as familiar with openCL as you but from what I can see it looks consistent with the coding styles I've seen. So since the code looks correct and functions correctly, I don't have any changes to make there.

And thank you for fixing the grammar issues. I don't mean to be patronizing in anyway by recommending these fixes but am doing it because I think the package is very useful and needs documentation to make its usage as clear as possible.

All I have left is a few grammar fixes in the new vignette. Please address these and I should be able to accept the package: 

vignettes/Installation_guide.Rmd
- [REQUIRED] various grammar fixes:
    - L24: "Here are installation instructions from"
    - L33: "For windows users,"
           "... please follow the instructions below to install ..."
    - L57: "... please choose the developer one"
    - L60: "... 'OpenCL.dl'. It may be necessary to manually move this file to fix this issue."

**Comment by Jiefei-Wang** [comment]
Hello @dvantwisk , thanks for your suggestions, I really appreciate it. I have made the changes accordingly. The grammar problem has been fixed now.

**Comment by dvantwisk** [comment]
It looks like the linux and windows builder are unable to find their openCL libraries. I am assuming this is an issue on our system and will accept your package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jiefei-Wang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gpuMagic")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gpuMagic

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
