### ISSUE TITLE
MCbiclust

### ISSUE THREAD

**Issue by rbentham** [Bioconductor/Contributions#101]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/rbentham/MCbiclust

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by rbentham** [comment]
Any possible reason why there has been no response from the last commit?

**Comment by LiNk-NY** [comment]
Hi @rbentham, 
Thank you for submitting your package to Bioconductor!
Please find a brief package review below: 

---

#### Grammar
* There were several instances where the `which(logical_vector)` construction was used but shouldn't be needed. Switching between logical and integer subsetting does not do anything. 

* `sapply` vs `vapply` - you may want to use `vapply` for more robust code since the output of `sapply` depends on it's input. 

* Minor: `seq(length = number)` or `seq(length = length(vector))` could really `seq_len(number)`

* Please avoid creating sequences such as `1:number` and use `seq_len(number)` instead for more robust code. 

* There are some instances where you use `eval(parse(text))`. This is generally not good coding practice and the more you can avoid it, the better. 

#### Organization and Usability
* My impression was that you have too many R files when some related functions could be put into one R file and you could even have some man pages describing groups of related functions. 

* Your function descriptions could be more in-depth so that users understand their purpose and arguments.

* We also recommend adding unit tests to your package to minimize bugs and increase robustness of the code. 

Your package is passing all checks and looks ready to go once you've addressed some of these issues. 

Thank you!

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @rbentham, 
If you're making changes to the package. Bump the version to kick off another build in the SPB. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Robert, @rbentham
Please notify me when you're done making changes to the package so I can review and update. 
Thanks. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Robert, @rbentham 
Don't forget to respond to the review. 
Best,
Marcel

**Comment by rbentham** [comment]
Hi Marcel,
Apologies for the very long delay, I have been exceptionally busy this last few months and have not found time for the final changes. I am however currently working on them now and should have them finished soon.
Best,
Robert

**Comment by rbentham** [comment]
Hi Marcus, @LiNk-NY,

I have made all the changes I was planning on, but since the change to R 3.4, my vignettes have not been compiling on Mac or Windows (see build reports).  I have tried various things without success so far and I have not been able to reproduce the errors on my machine. I will try a few more things but if you have any ideas why this has started happening please let me know.

Best,
Robert

**Comment by rbentham** [comment]
Hi Marcus, @LiNk-NY,

I was having issues with Miktex so my vignette now produces a html document. Everything else though should now be working and ready for you to review.

Best,
Robert

**Comment by LiNk-NY** [comment]
Hi Robert, @rbentham 
Thank you for making those changes. I will review your changes in the next couple of days. 

Regards,

Marcel

**Comment by LiNk-NY** [comment]
Hi Robert, @rbentham 
Apologies for the late response. 
Please see the `NOTE` you're getting from `Check` & `BiocCheck`

```
CVPlot: no visible binding for global variable ‘Status’
CVPlot : H_d_plot_fun: no visible binding for global variable ‘Status’
Undefined global functions or variables:
  Status
```

Please provide vectors as the `aes` arguments so this is resolved: 
Example: `aes(x = mtcars[["mpg"]])`

Regards,
Marcel

**Comment by rbentham** [comment]
Hi Marcel @LiNk-NY ,

See above commit for fix of the issue you raised.

Best,
Robert

**Comment by LiNk-NY** [comment]
Hi Robert @rbentham, 
Thank you for making those changes. 

In future revisions, you may want to look at using the internal `aes_` instead (to avoid the use of the `get` function). `aes_` seems like the preferred option, according to the documentation. 
Also, I'm not sure why `Vignette_sort` is user visible. You might want to store the data in `R/sysdata.rda`. 

Your package has been accepted. Thank you for submitting to Bioconductor! 

Best regards,
Marcel
