### ISSUE TITLE
SpectralTAD

### ISSUE THREAD

**Issue by cresswellkg** [Bioconductor/Contributions#1012]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dozmorovlab/SpectralTAD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see initial review below: 

**GENERAL:**
- [ ] It would be great if you could provide a brief explanation on how your package differs from exisiting package methods in Bioconductor. [current HiC package](http://bioconductor.org/packages/release/BiocViews.html#___HiC).  

**Build Report:**
Clean up Notes.
- [ ] Global variables and suggested import in NAMESPACE
- [ ] Avoid 1:...; use seq_len() or seq_along()
- [ ] We strongly encourage the use of a NEWS file to keep track of changes from versions. This is also used to create an entry each Bioconductor release to highlight changes. 
- [ ] We strongly encourage adding unit tests to test the functionality and accuracy of your package. 


**DESCRIPTION:**
- [ ]  Remove `lazyData: True` we have rarely found this useful and in our experience can actually slow down the building of the package. 

**VIGENTTE**
- [ ] Obviously when it gets accepted please update the default installation instructions to be the BiocManager install. 
- [ ] Clarification - you mention that the output is a bed file. Is this saved to a file? In running the code and in section 2.3 Running SpectralTAD you have a comment #Printing the bed file  - but really this is just a tibble in bed format correct? This was deceiving to me as far as description. 
- [ ] We like to see input/output consistent with existing Bioconductor classes. The output  
```
  chr     start     end Level
  <chr>   <dbl>   <dbl> <dbl>
1 chr20   50000 1200000     1
2 chr20 1200000 2450000     1
3 chr20 2450000 3525000     1
4 chr20 3525000 4075000     1
5 chr20 4075000 4575000     1

```
Really should be converted to a `GRanges` object of the package `GenomicRanges` - dplyr like methods for GenomicRanges objects have also been implemented in `plyranges`

By the look of results as a list - My assumption is this would be a list of these types of tibble objects - so also appropriate may be GRangeList
```
> results
$Level_1
# A tibble: 62 x 4
   chr     start     end Level
   <chr>   <dbl>   <dbl> <dbl>
 1 chr20   50000 1200000     1
 2 chr20 1200000 2450000     1
 3 chr20 2450000 3525000     1
 4 chr20 3525000 4075000     1
 5 chr20 4075000 4575000     1
 6 chr20 4575000 5225000     1
 7 chr20 5225000 5450000     1
 8 chr20 5450000 6075000     1
 9 chr20 6075000 7275000     1
10 chr20 7275000 7850000     1
# … with 52 more rows
> class(results)
[1] "list"

```

If the data is in this format for a particular reason (ie. to work into an existing package pipeline) please specify.  There should at the very least be a conversion method to GenomicRanges as most Bioconductor users are familiar with this data object for chromosome location specific data. 



**data**
- [ ] Just a thought - it seems even with your data that the SpectralTAD function requires a matrix rather than a data.frame - perhaps this check could be performed by the function itself as a helper for the user. 


**man**
- [ ] rao_chr20_25_rep - could you please include the full reference for the source of the data. 


**R code**
- [ ] (optional) I might suggest keep the ordering of the arguments as similar as possible between SpectralTAD_Par and SpectralTAD, grouping the parallel specific arguments together - to me this would seem more intuitive if I was using the different functions in different situations. 

- [ ] as mentioned above maybe have the check for data.frame/matrix in the code so a user doesn't have to worry about the conversion. 


Please address the above issues and kick off a version bump for a new build report to be generated.  When ready please comment back here with what has been updated and requesting a re-review.  I look forward to working with you to get your package accepted to Bioconductor.

**Comment by cresswellkg** [comment]
The latest build contains fixes for all the above comments. I outline them below:

##### It would be great if you could provide a brief explanation on how your package differs from exisiting package methods in Bioconductor. [current HiC package](http://bioconductor.org/packages/release/BiocViews.html#___HiC).

Our method will be the only Topologically Associated Domain (TAD) caller on Bioconductor. Some other methods provide methods for analyzing TADs but ours is the only one that actually identifies TADs. 

##### Global variables and suggested import in NAMESPACE

I've added import(magrittr) to the NAMESPACE file

##### Avoid 1:...; use seq_len() or seq_along()

All instances have been replaced

##### We strongly encourage the use of a NEWS file to keep track of changes from versions. This is also used to create an entry each Bioconductor release to highlight changes.

A blank NEWS file has been added
  
##### We strongly encourage adding unit tests to test the functionality and accuracy of your package.

This has been added

##### Remove `lazyData: True` we have rarely found this useful and in our experience can actually slow down the building of the package.

This has been removed

##### Obviously when it gets accepted please update the default installation instructions to be the BiocManager install.

This will be updated

##### Clarification - you mention that the output is a bed file. Is this saved to a file? In running the code and in section 2.3 Running SpectralTAD you have a comment #Printing the bed file  - but really this is just a tibble in bed format correct? This was deceiving to me as far as description.

We've removed all references to bed files in both documentation and the vignette and replaced them with references to "data frames in BED format" or "GRanges in BED format" whenever applicable. 

##### We like to see input/output consistent with existing Bioconductor classes.

An option for output in GRangelist form has been added for both `SpectralTAD` and `SpectralTAD_Par`. We have left the default as a list of data frames due to the expectation that users will be running the algorithm and immediately writing to files. Data frames will require no conversion for this. 

##### Just a thought - it seems even with your data that the SpectralTAD function requires a matrix rather than a data.frame - perhaps this check could be performed by the function itself as a helper for the user.

This depends on the type of matrix that is input. We have added automatic checking and conversion for these types of input.

##### rao_chr20_25_rep - could you please include the full reference for the source of the data.

This has been added.

##### (optional) I might suggest keep the ordering of the arguments as similar as possible between SpectralTAD_Par and SpectralTAD, grouping the parallel specific arguments together - to me this would seem more intuitive if I was using the different functions in different situations.

The order has been changed accordingly.

##### as mentioned above maybe have the check for data.frame/matrix in the code so a user doesn't have to worry about the conversion.

This has been added as already mentioned and the vignette has been edited to reflect this.

**Comment by lshep** [comment]
This is very close to being accepted 

**General**
- [ ] Please investigate the recent timeout on the windows platform


**NAMESPACE/DESCRIPTION**
- [ ] With the addition of GRanges and RGRangesList please include GenomicRanges
in the Suggests of the DESCRIPTION and import in NAMESPACE. 

When the package (or functions) are imported in the NAMESPACE this should also
fix why GRanges cannot be found when currently trying to use the grange flag

```
> spec_table <- SpectralTAD(rao_chr20_25_rep, chr= 'chr20', grange=TRUE)
Converting to n x n matrix
Matrix dimensions: 2517x2517
Estimating resolution
Error in GRanges(x) : could not find function "GRanges"
```

**LICENSE**
- [ ] (Optional) For what its worth the MIT license is distributed with R so it is not necessary to include this file but it is okay if you choose too. 

With the change to the DESCRIPTION/NAMESPACE and fixing the windows TIMEOUT, I think it should be good to go.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cresswellkg.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpectralTAD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpectralTAD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
