### ISSUE TITLE
Melissa package submission

### ISSUE THREAD

**Issue by andreaskapou** [Bioconductor/Contributions#1013]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/andreaskapou/Melissa

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by andreaskapou** [comment]
Hi,

I have attempted to fix the WARNINGS found by build-bot. 
* Then I changed version (many time) so the built-bot to start building the package.
* Although I receive the message 'Received a valid push; starting a build', I do not get any response for whether the package was built successfully.

Could you please have a quick look, it might need to perform a manual build?

Thanks,
Andreas

**Comment by mtmorgan** [comment]
yes I think the 'single package builder' is having problems; it might not be fixed until Tuesday morning, sorry for the inconvenience.

**Comment by lshep** [comment]
I apologize for the inconvenience.   I have kicked off a manual build which should post shortly.  The single package builder should now be functioning normally and will produce build reports upon version bumps.

**Comment by andreaskapou** [comment]
Thank you both for your help :) Do you have an estimate on the time it takes to be accepted to Bioconductor? Since I am publishing a methods paper and it would be great to have the Bioconductor link as well.

Best wishes,
Andreas

**Comment by mtmorgan** [comment]
DESCRIPTION

- Remove Author: and Maintainer: when Authors@R used (these fields are generated when the package is built).

vignettes

- impressive!

- run_melissa.Rmd:63 I found the `melissa_encode_dt` object very difficult to work with, and wonder why it is not a data.frame / tibble / DataFrame with columns sample, cell, CpG_offset, methylation. This structure makes it immediately obvious how to explore basic data structure; using a tibble or DataFrame would provide a straight-forward display. Using DataFrame could allow use of Rle() (for efficient representation of sample and cell, as well as associate of `metadata()`, perhaps in a simple derived class `setClass("MelissaData", contains="DataFrame")`. It would be natural to use GenomicRanges (instead of or as a column in DataFrame) for annotating genomic regions. Generally looking at your code I could not help but feel that the nested data structures greatly increased code complexity and had significant performance consequences.

R -- comments are on specific locations in code but apply generally

- melissa_gibbs.R:97 this 'copy-and-append' pattern is inefficient, use 'pre-allcoate and fill'; see [1][]

- melissa_gibbs.R:115 consider BiocParallel for parallel evaluation across platforms and standard Bioconductor experience

- melissa_gibbs.R:168 I find this 'compact' representation difficult to read and urge a more standard representation, e.g.,

    ```
    for (i in seq_len(I)) {
        C[i, ] <- rmultinom(n = 1, size = 1, post_prob[i, ]) 
    }
    ```

- melissa_gibbs.R:212 this is another example of inefficient 'copy-and-append'.

- melissa_gibbs.R:195 these nested iterations are likely to be very inefficient; carefully examine code to write 'vectorized' (one call to R functions) rather than 'iterative' (K x N calls) algorithms.

- melissa_gibbs.R:242 I'm not 100% sure but suspect that this line copies the entire object `z` on each assignment! This would be very time-expensive.

- melissa_gibbs.R:400 it looks like this code duplicates the parallel version above; write one helper function and use it in mclapply / lapply rather than two anonymous function.

- melissa_gibbs.R:521 it is seldom necessary to mix parallel processing (mclapply / foreach) paradigms; stick with one (mclapply or actually BiocParallel::bplapply). Avoid nested parallelism (parallelize the outermost iteration).

- melissa_gibbs.R:548 use `message()` rather than `cat()` for reporting progress / other information messages.

- process_data.R:98 invoking `system("gzip"...)` is not portable

tests

- consider developing more extensive and meaningful tests!

[1]: https://bioconductor.org/developers/how-to/efficient-code/

**Comment by andreaskapou** [comment]
Thanks for the quick reply. I made most of the changes you requested, see below. 

DESCRIPTION

* Remove Author: and Maintainer: when Authors@R used (these fields are generated when the package is built).

**Done.**


Vignettes

* impressive!

* run_melissa.Rmd:63 I found the `melissa_encode_dt` object very difficult to work with, and wonder why it is not a data.frame / tibble / DataFrame with columns sample, cell, CpG_offset, methylation. This structure makes it immediately obvious how to explore basic data structure; using a tibble or DataFrame would provide a straight-forward display. Using DataFrame could allow use of Rle() (for efficient representation of sample and cell, as well as associate of `metadata()`, perhaps in a simple derived class `setClass("MelissaData", contains="DataFrame")`. It would be natural to use GenomicRanges (instead of or as a column in DataFrame) for annotating genomic regions. Generally looking at your code I could not help but feel that the nested data structures greatly increased code complexity and had significant performance consequences.

_I agree that the data structure might not seem perfect, however, an issue this way I could use a sparse representation, since in your proposal I would need to replicate the cell id and genomic region columns millions of times. In addition, many regions do not have data, which in my case i have an empty list, however in the data.frame setting probably this would be problematic, since it wouldn't be an entry. In addition, the package depends heavily on a previous package I have developed (BPRMeth) which uses the same data structure. However I see your point of complexity and will look in the future use a better suited data structure._

R -- comments are on specific locations in code but apply generally

* melissa_gibbs.R:97 this 'copy-and-append' pattern is inefficient, use 'pre-allcoate and fill'; see [1](https://bioconductor.org/developers/how-to/efficient-code/)

**Updated code**

* melissa_gibbs.R:115 consider BiocParallel for parallel evaluation across platforms and standard Bioconductor experience

**I felt that the sometimes `mclapply` was faster, and generally the two approaches are similar. That is why I prefer `mclapply`. Might read a bit more on BiocParallel package though, thanks for the suggestion.**

* melissa_gibbs.R:168 I find this 'compact' representation difficult to read and urge a more standard representation, e.g.,
  ```
  for (i in seq_len(I)) {
      C[i, ] <- rmultinom(n = 1, size = 1, post_prob[i, ]) 
  }
  ```

**Updated code in all functions**

* melissa_gibbs.R:212 this is another example of inefficient 'copy-and-append'.
* melissa_gibbs.R:195 these nested iterations are likely to be very inefficient; carefully examine code to write 'vectorized' (one call to R functions) rather than 'iterative' (K x N calls) algorithms.
* melissa_gibbs.R:242 I'm not 100% sure but suspect that this line copies the entire object `z` on each assignment! This would be very time-expensive.
* melissa_gibbs.R:400 it looks like this code duplicates the parallel version above; write one helper function and use it in mclapply / lapply rather than two anonymous function.

**I understand that the code in `melissa_gibbs` is not perfect, although this was mostly implemented and added in the package only for reproducibility purposes and will be DEPRECATED in future releases. This is because the algorithm is really slow, irrespective of the sloppiness of my implementation. In the documentation, I also urge users to use the faster algorithm `melissa` function.**

* melissa_gibbs.R:521 it is seldom necessary to mix parallel processing (mclapply / foreach) paradigms; stick with one (mclapply or actually BiocParallel::bplapply). Avoid nested parallelism (parallelize the outermost iteration).

**Removed the foreach code as requested**

* melissa_gibbs.R:548 use `message()` rather than `cat()` for reporting progress / other information messages.

**Updated code as requested**

* process_data.R:98 invoking `system("gzip"...)` is not portable

**Removed call to gzip as requested**

tests

* consider developing more extensive and meaningful tests!

**Added tests for filtering process and running Melissa as requested**

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/andreaskapou.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Melissa")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Melissa

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
