### ISSUE TITLE
Structstrings

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/Contributions#1015]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FelixErnst/Structstrings

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hi @FelixErnst,

I have just started the review and have only gotten as far as the documentation of the package. If you wanted to merge the changes that would be fine with me. 

Best,
Kayla

**Comment by FelixErnst** [comment]
hmm, on Linux it took a bit longer to build. I hope that is not a problem.

**Comment by Kayla-Morrell** [comment]
It's just a few seconds over 5 minutes so it shouldn't matter too much. I'll continue my review with these changes.

**Comment by FelixErnst** [comment]
Hi @Kayla-Morrell any news on the review? Thanks for any update.

**Comment by Kayla-Morrell** [comment]
Hi @FelixErnst,

Thank you for submitting to _Bioconductor_ and thank you for your patience with the review process. Please see the initial review of your package below.

# General Package Development #

- [ ] SUGGESTION: When running R CMD BiocCheck, consider adding these automatically suggested biocView: Alignment, SequenceMatching.

- [ ] SUGGESTION: Consider adding runnable examples to the man page 'Structstrings-internals.Rd' since exported objects are documented.

- [ ] SUGGESTION: For style reasons, consider shorter lines of > 80 characters. There are 13 lines that are longer than 80 characters (this includes comments and roxygen documentation). R CMD BiocCheck provides the first 6 lines:
	- R/Structstrings-conversion.R, line 15
	- R/Structstrings-conversion.R, line 254
	- R/Structstrings-DotBracket-io.R, line 28
	- R/Structstrings-DotBracketDataFrame.R, line 92
	- R/Structstrings-DotBracketDataFrame.R, line 106
	- R/Structstrings-DotBracketDataFrame.R, line 226

- [ ] SUGGESTION: For style reasons, consider multiple of 4 spaces (not tabs) for line indents. There are 671 lines that are not. R CMD BiocCheck provides the first 6 lines:
	- R/AllGenerics.R, line 7
	- R/AllGenerics.R, line 11
	- R/AllGenerics.R, line 16
	- R/AllGenerics.R, line 17
	- R/AllGenerics.R, line 21
	- R/AllGenerics.R, line 25

# vignette #

- [ ] REQUIRED: The first sentence of the 'Introduction' there seems to a grammatical error. I believe you meant for it to read '...used dot bracket...'.

- [ ] REQUIRED: There seems to be a missing reference for 'Biostrings'. The link in the second paragraph of the 'Introduction' links back to your vignette.

- [ ] REQUIRED: Create an 'Installation' section that shows the user how to download and load the package from _Bioconductor_. For example...

```{r} 
if(!requireNamespace("BiocManager", quietly = TRUE))
	install.packages("BiocManager")
BiocManager::install("Structstrings")
```

Then move the `library()` command up to this section and start section 2 with the text about `DotBracketString()`.

- [ ] REQUIRED: Finish your vignette with a `SessionInfo()` section.

# man pages #

*DotBracketString*

- [ ] REQUIRED: For the description, there seems to be an extra \\ when talking about what the alphabet consists of. 

*DotBracketStringSet-io*

- [ ] REQUIRED: For the description, the first paragraph talking about the '<>' conflict needs to end in a period not a comma.

- [ ] REQUIRED: The last sentence of the description needs to be reworded.

- [ ] CLARIFICATION: Take another look at the links you use to `Biostrings:XStringSet-io`. It is my understanding that in order for these links to work in the way you have them it should be `\code{\link[package:function]{name}}` but `XStringSet-io` is not a function so I don't think the link is rendering correctly. If I am wrong, please feel free to correct me.

*Structstrings-data*

- [ ] REQUIRED: Data man pages must include source information and structure information. 

*Structstrings*

- [ ] SUGGESTION: This is a good use of a package man page that contains an overview of the package. You may also think of adding links to the main functions.

# R code #

The General package development section have some suggestions for improvements that can be made to the R code.

- [ ] REQUIRED: Overall, avoid the use of direct sloct access with `@`, accessor methods should be created and utilized instead.

- [ ] REQUIRED: Shouldn't use unexported functions (via `:::`), this was used extensively with `setValidity2` from `S4Vectors`.

Comment back here with updates that have been made and when the package is ready for a re-review.

Best,
Kayla

**Comment by FelixErnst** [comment]
I worked through the review:

# General Package Development

I followed you advice, except for the indentation and some of the line with width > 80L incase they could not be shortened.

# vignette

all done

# man pages

all done. The `\code{\link[package:function]{name}}` works as intended, since the actual name of the man page must be used as `function`. An alias like `readDNAStringSet()` cannot be used (It could be used with `\link{}`, but I like the more explicit version).

# R code

### slot access: 
  - @structure: replaced by accessor calls

The other calls are purely done for optimization purposes.
  - @listData: used during construction of `DotBracketDataFrame` to avoid deconstructing and reconstructing the object.
  - @unlistData: I could do it via unlisting and relisting. However, this adds additional overhead, which is not necessary, since I just need small adjustments:

I hope the few calls are ok for you.

### unexported functions
- all calls removed except `XStringSet`, which is needed for the constructor of `DotBracketStringSet`

**Comment by FelixErnst** [comment]
@Kayla-Morrell the error is due changes in IRanges not propagating to the `SPB`. I bump the `Structstrings` version, when the new `IRanges` version has ended up on the SPB. However, the changes addressing are complete.

**Comment by FelixErnst** [comment]
@lshep For the last build a report did not get posted. Thanks for any help in advance.

**Comment by Kayla-Morrell** [comment]
Hello @FelixErnst,

Thank you for the work done on your package. I have looked over the changes made and have just a few more requirements/suggestions before accepting your package. See the secondary review below and comment back here when you are ready for me to look it over again.

# General Package Developement #

*R CMD check*

- [ ] REQUIRED: There is an error when running R CMD check. Below is the error:

```{r}
* checking examples ... ERROR
Running examples in ‘Structstrings-Ex.R’ failed
The error most likely occurred in:

> ### Name: Structstrings-internals
> ### Title: Structstrings internals
> ### Aliases: Structstrings-internals DOTBRACKET_CHAR_VALUES
> ###   DOTBRACKET_ALPHABET STRUCTURE_NEUTRAL_CHR STRUCTURE_OPEN_CHR
> ###   STRUCTURE_CLOSE_CHR [<-,DotBracketDataFrame-method
> ###   colnames<-,CompressedSplitDotBracketDataFrameList-method
> ### Keywords: datasets
>
> ### ** Examples
>
> DOTBRACKET_CHAR_VALUES
[1]  40  41  46  60  62  91  93 123 125
> DOTBRACKET_ALPHABET
[1] "(" ")" "." "<" ">" "[" "]" "{" "}"
> STRUCTURE_NEUTRAL_CHR
[1] "."
> STRUCTURE_OPEN_CHR
[1] "\\(" "<"   "\\[" "\\{"
> STRUCTURE_CLOSE_CHR
[1] "\\)" ">"   "\\]" "\\}"
>
> # the replace method for a DotBracketDataFrame had to be reimplemented
> # because of the requirement of columns for a DotBracketDataFrameList and
> # DotBracketDataFrame
> data("dbs", package = "Structstrings", envir = environment())
> dbdfl <- getBasePairing(dbs)
> # Elements are returned as DotBracketDataFrames
> dbdf <- dbdfl[[1]]
> dbdfl[[1]] <- dbdf
Error: C stack usage  7972064 is too close to the limit
Execution halted
```

# vignette #

- [ ] SUGGESTION: Thank you for adding session info to the end of the vignette. However, you can just use `SessionInfo()` at the end of the vignette as it comes from the `utils` package. This way you won't have to add `sessioninfo` as a suggested package in your DESCRIPTION file.

# man pages #

*DotBracketStringSet-io*

- [ ] REQUIRED: Line 50, I believe 'has' should be 'have'.

Best,
Kayla

**Comment by FelixErnst** [comment]
Hi @Kayla-Morrell,

Thanks you for the second review.

# General Package Developement
*R CMD check*
the error you mentioned is not reported in the last build report. If you installed `Structstrings` locally and this is an error from that installation, please make sure to install the latest `IRanges` version using `install_github("Bioconductor/IRanges")`. The error is resolved there (see build report from yesterday).

# vignette
done.

# man pages
Thanks for catching that. Much appreciated.

**Comment by FelixErnst** [comment]
@Kayla-Morrell Thank you for the review. Much appreciated!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Structstrings")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Structstrings

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
