### ISSUE TITLE
scRecover

### ISSUE THREAD

**Issue by miaozhun** [Bioconductor/Contributions#1021]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/miaozhun/scRecover

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
scImpute, which your package Imports:, is not a CRAN or Bioconductor package. Your dependencies must be from CRAN or Bioconductor.

**Comment by miaozhun** [comment]
Thank you! Martin @mtmorgan 
I have integrated scImpute in my package now. : )

**Comment by mtmorgan** [comment]
scImpute is still listed in the Imports field of your DESCRIPTION file. Also, is it really a good idea to re-implement an entire package inside this package? Wouldn't a better strategy be to make scImpute robust and available through standard (CRAN or Bioconductor) channels?

**Comment by miaozhun** [comment]
Sorry for the mistake, I have fixed it now.
Actually, I'm not one of the authors of "scImpute", so I think maybe I won't have the right to submit their package to Bioconductor or CRAN. Though my package invokes and cooperates with one of their function.
Anyway, I will contact the authors of scImpute and suggest them to submit their package to Bioconductor. And before scImpute become available through standard channels, I will include and use its function in my package carefully to ensure it works well.
Thank you for your suggestions! @mtmorgan

**Comment by miaozhun** [comment]
Hi, Qian @Liubuntu ,
Long time no see. How are you?
I have bumped the version number of my package while it not start building automatically. Would you please help me with it or tell me what shall I do? Thank you very much!

Best,
Zhun

**Comment by Liubuntu** [comment]
Hi @miaozhun , 

How are you! Glad to see that you are still working on developing Bioconductor packages.

Seems that the building machine didn't catch your version bump. Quick test you can do is to bump version again and see if it triggers new build. If not, I'll ask my colleague about the building machine status. Thanks!

Best,
Qian

**Comment by miaozhun** [comment]
Dear Qian @Liubuntu ,

Thank you! I bumped the version number again while the building machine still not start building. I guess maybe it is because I wrongly set the version number to 0.1.5 at the beginning, and when I corrected it later to 0.99.0, 0.99.1 and 0.99.2 now, it still not working somehow. Maybe we should ask your colleague who is in charge of the building machine to help to start it manually. Thanks a lot!

Best,
Zhun

**Comment by Liubuntu** [comment]
Hi @miaozhun , 

Did you successfully set up the webhook? 

**IMPORTANT**: Please read [the instructions][1] for setting
up a push hook on your repository, or further changes to your
repository will NOT trigger a new build.

[1]: https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

**Comment by miaozhun** [comment]
Oh! My fault, I've missed that instruction, Sorry about that!
Thanks a lot! @Liubuntu 

Best,
Zhun

**Comment by Liubuntu** [comment]
Looks good. You can expect an initial review within 2 weeks, but could be earlier.

**Comment by miaozhun** [comment]
Thanks a lot!

**Comment by Liubuntu** [comment]
Hi @miaozhun , 

Sorry for the delay in the package review. I was out for the past several days. Will be posting the initial review very soon. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @miaozhun , 

I am posting the partial initial review. Please seek to work on these issues and I'll continue review your man / R / vignette section. Thanks for the understanding. 

Best,
Qian

## DESCRIPTION

- Please remove “LazyData = true”. This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data.
- `Description` field looks a bit long. The description should be a relatively short but detailed overview of what the package functionality entails. It should be one or more complete sentences.
- `BugReports:` field: It is encouraged to include the relevant links to Github for reporting Issues.

## NAMESPACE
- Looks good.

## NEWS
- Add a NEWS file in the top folder. See [here](http://bioconductor.org/developers/package-guidelines/#news) for details.

## Unit tests
Unit tests are highly recommended. See [here](http://bioconductor.org/developers/package-guidelines/#unittest) for details.

## R/
- scRecover.R: `@param outputDir` we recommend to use a temporary directory as the default output dir, and print out the file path in the corresponding step so that users could access their output data.

## vignette
- load in all required libraries in the beginning of the vignette.

**Comment by Liubuntu** [comment]
HI @miaozhun , 

Sorry again for the delay. Here are the reviews for `R/` and `man/`. Mostly are just minor issues about coding style and efficient R code. Please seek to address all of them and let me know for any question. I'll read through the vignette and post back here very soon!

Cheers,
Qian

## R/
- scRecover.R:L141. We recommend to use a temporary directory as the default output dir, and print out the file path in the corresponding step so that users could access their output data.
- scRecover.R:L66. It's recommended to use `is(object, "class")` to check for S4 classes.
- L87. use `else{}` to avoid duplicate checking of `is.null(labels)`.
- L201:L210, L223. Vectorization. Since the length of `dropoutNum` is fixed, pre-assign a vector of NULL of that length, and sign values by for loop. e.g., ```dropoutNum <- rep(NULL, ncol(counts_used)); ... for (...), dropoutNum[i] <- ...```. Using ```xx <- c(xx, ...)``` will copy the values of `xx` each time in the loop which is very inefficient in R.
- Similar issue in L223, L272.
- L217. Use `else{}` because you already checked the `if(!UMI)`.
- L305:L324. Avoid double checking. Use `if(SAVER)` instead. Similar to `MAGIC` and other instances.

- Seems that the `counts` argument in `countsSampling.R` and `estDropoutNum.R` could also be `SingleCellExperiment` object (subsetted to genes), right? If yes, add appropriate code and documentation.

- estDropoutNum.R,L90:L98. if else statement could be more simplified, e.g.,
```
if (return %in% c("geneNumPredict", "transcriptNum")) {
        return(geneNumPredict)
} else {
        return(dropoutNum)
}
```

- imputation_model.R:L20. Avoid double checking in `if(labeled==TRUE)` and all similar instances in the scripts.
- normalization.R:L52. You can use `is(counts, "SingleCellExperiment")` here.
- scImpute-internal.R. Where was this internal function (`.Random.seed`) used in your package?
- scimpute.R:L24,L33. Avoid double checking inside the `if()` statement.


Notes in building reports & Else:
- Avoid sapply(); use vapply()
- Avoid 1:...; use `seq_len()` or `seq_along()`
- Avoid double checking for `if(... == TRUE)` statement.


## man/ 
- estDropoutNum.md: According to your code, `histCounts` argument could also be `transcriptNum`.

**Comment by miaozhun** [comment]
Dear Qian @Liubuntu ,

Thanks a lot for the review! I'll work on it according to your advices.
I really appreciate your effort to help me to improve the package. Thank you so much!

Best,
Zhun

**Comment by Liubuntu** [comment]
Hi @miaozhun , 

Please see following for the review of vignette (which completes the initial review). 

Generally you package was written really well! Fix these minor issues and we can proceed for acceptance. You package could also be greatly enhanced and be more robust by adding unit tests (highly recommended). 

Best,
Qian

## vignette
- load in all required libraries in the beginning of the vignette.
- L39: the citation for scRecover is empty?
- Installation section. Please include the following info:
```
1. Download the package from Bioconductor.
{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
 BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```

- The output message from 6.1.1 and 6.1.2 was printing too many lines. I see that you are using `\r` in print messages and it works great in R console, but printing all rows in vignette. A workaround could be adding an additional argument in `scRecover(verbose = TRUE)` by default to print this message in R console, but set `verbose=FLASE` in vignette.

- Just curious, for example in the section 9.3, when you evaluating the clustering performance, seems that you are using t-SNE for visualization, how did you evaluate the improvement by incorporating "scRecover" into the the other imputation tools? (Any mathematical statistics or just by visual?)

**Comment by miaozhun** [comment]
Dear Qian @Liubuntu ,

I'm glad to tell you that all the issues mentioned above are addressed. Thank you very much for the help!
Unit tests are added as recommended, thanks for the good suggestion!
Please see blow for other details. Thanks!

Best,
Zhun

# DESCRIPTION
* “LazyData = true” is removed.
* Description is simplified.
* BugReports field is added.

# NEWS
* A NEWS file is added under /inst.


# Unit tests
* Unit tests are added.

# R/
* scRecover.R: Default `@param outputDir` is changed to a temporary directory as the output dir, and the output file path is printed out in the ending.
* Actually the `counts` argument in countsSampling.R and estDropoutNum.R is only a vector of read counts of each gene in one cell. So I think SingleCellExperiment object is not very suitable for them because it will be complicated to make each cell a SingleCellExperiment object for the users.
* scImpute-internal.R is removed because it seems useless (I copied it from scImpute).
* All the other issues are fixed as adviced.

# man/
* `transcriptNum` is added to  `@param return`.

# vignette
* All required libraries are loaded in the beginning of the vignette.
* The citation for scRecover is temporarily empty because we're conducting more applications of scRecover and will write the manuscript for it in the near future. I'll add the citation for scRecover once our paper is available in bioRxiv.
* Installation section is modified as recommended.
* Argument `verbose` is added  to function `scRecover`, by default `verbose = TRUE` to print messages in R console, and set `verbose = FALSE` in vignette.
* To evaluate the imputation results in 9.2 and 9.3, I use ARI (Adjusted Rand Index) and Jaccard index to compare the clustering resultes to the ground truth of cell labels (the larger, the better). I also updated the figures in vignette, you could see ARI and Jaccard index above each sub-figures more clearly, thanks!


Thank you for all your efforts and helps to me!

Best,
Zhun

**Comment by Liubuntu** [comment]
HI @miaozhun , 

Thanks for making the quick fixes. Here are some additional minor issues for R scripts, make some quick updates and we are ready to go! 

Best,
Qian

## R/
- scRecover.R Please update the documentation for `@param outputDir` since you are now using temporary directory, not the current working directory.
- > Seems that the `counts` argument in `countsSampling.R` and `estDropoutNum.R` could also be `SingleCellExperiment` object (subsetted to genes), right? If yes, add appropriate code and documentation. 

Subsetting a `SingleCellExperiment` to each cell would be simply `sce[1, ]` and could retain all the metadata (e.g., `rowData/colData`) to that specific cell, which should actually be more convenient to my understanding. If there was no technical difficulty, to be consistent, I think you should incorporate that in these 2 scripts. 
- Correct the following scripts to avoid double checking. Use `if(labeled)` or `if(!labeled)`.  
```
qian@qian-ZBook:~/PackageReview/scRecover/R$ grep "== TRUE" *
scimpute.R:    if(labeled == TRUE & is.null(labels)){
qian@qian-ZBook:~/PackageReview/scRecover/R$ grep "== FALSE" *
imputation_model.R:          if (labeled == FALSE){ npc = max(npc, Kcluster) }
imputation_model.R:          if (labeled == FALSE){ npc = max(npc, Kcluster) }
imputation_model.R:  if(labeled == FALSE){
imputation_model.R:        if (labeled == FALSE){ npc = max(npc, Kcluster) }
imputation_model.R:        if (labeled == FALSE){ npc = max(npc, Kcluster) }
imputation_model.R:        if (labeled == FALSE){ npc = max(npc, Kcluster) }
imputation_model.R:        if (labeled == FALSE){ npc = max(npc, Kcluster) }
scimpute.R:    if(labeled == FALSE & is.null(Kcluster)){
```

## vignette
- Thanks for the explanation, and the addition of ARI and Jaccard to the figures looks great!

## unit tests
- Looks great!

**Comment by miaozhun** [comment]
Hi, Qian @Liubuntu ,

Thank you for the further explanation of the use of `SingleCellExperiment`.
* I modified function `estDropoutNum` and `countsSampling`, and now they could support `SingleCellExperiment` object. I also modified their documentation to explain that they could support `SingleCellExperiment` object.
* I also updated the documentation of `scRecover` for `@param outputDir`.
* And also the other codes according to you advices.

Thank you so much for your review!

Best,
Zhun

**Comment by Liubuntu** [comment]
Hi @miaozhun  

Thanks for those updates. Your package is now accepted. 

Cheers,
Qian

**Comment by miaozhun** [comment]
Dear Qian @Liubuntu ,

Thanks a lot for all your effort and patience to help me to improve the package!

Cheers!
Zhun

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/miaozhun.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scRecover")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scRecover

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
