### ISSUE TITLE
CHETAH

### ISSUE THREAD

**Issue by jdekanter** [Bioconductor/Contributions#1025]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jdekanter/CHETAH

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package so that all user-facing functions provide an interface (inputs and outputs) that interoperate with [SingleCellExepriment][1], the standard Bioconductor representation for this type of data.

[1]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by jdekanter** [comment]
Thank you for your quick response. 
I will work on the incorporation with SingleCellExperiment
and I will find out why the built failed, as I have tested it extensively myself.

**Comment by jdekanter** [comment]
I now build CHETAH on top of SingleCellExperiment en fixed the building problems!

**Comment by dvantwisk** [comment]
Great! I'll have a look at it shortly.

**Comment by dvantwisk** [comment]
Hello
Here is a review of your package. [REQUIRED] tags indicate changes that must be made or addressed. [CONSIDER] tags indicate changes that are not required but advisable. Code that I've written hasn't been tested so it may not work function correctly it can rather be considered as guidelines. Message me back if you have any questions.

GENERAL:
- [ ][REQUIRED] The size of the package is 13MB. We tend to want to see packages
that are no larger than 5MB upon submission. It seems that most of the package's
size comes from its history in `.git` (it is 9.6MB in size). Please use the BFG
Repo-Cleaner tools to reduce the size of your repository as much as possible.
https://rtyley.github.io/bfg-repo-cleaner/

DESCRPTION
- [ ][REQUIRED] State that you are using the GPL-3 license in the `LICENSE: `
field. That is `LICENSE: GPL-3 + file`.

R/Utils_CHETAH.R
- [ ][CONSIDER] L123: Use `match.arg()` where only certain `character(1)`
inputs are accepted. For example with the `cor_method` argument in the
`CHETAHclassier()` function, it can be expressed as
`cor_method = c("spearman", "kendall", "pearson", "cosine")` in the function
declaration. The first argument `"spearman"` is the default argument. The
user's selection can be obtained using `cor_method <- match.arg(cor_method)`.
Using `match.arg()` allows the user to more easily see the possible values to
`cor_method` if they print the function. Also, `match.arg()` has built in error
checking such that it will throw an error if any unspecified argument is given.
This can be done for other arguments and function throughout your package.
- [ ][REQUIRED] L169: Use `message()` in place of `cat()` for diagnostic
messages. This is better because messages made with `message()` can be silenced
with `suppressMessages()`.
- [ ][REQUIRED] L245-248: Vectorize instead of using for-loop. This is more
efficient:
```
i <- seq_len(nrow(coor))
coor[i, 2] <- coordinates[ ,1][coordinates[ ,2] == coor[i, 1]]
```
- [ ][REQUIRED] L1188-1191: Inefficient copy-and-append pattern. Replace with:
```
row <- seq_len(nrow(conf_df))
sub_score <- conf_df[row, sub_clas[row]]
```

tests
- [ ][CONSIDER] Add tests using the `testthat` package.

vignettes/CHETAH_introduction.Rmd
- [ ][REQUIRED] L98-105: Remove reference to obtaining the devel version of the
package from github using `devtools::install_github("jdekanter/CHETAH")`. Once
the package is accepted to Bioconductor, the `master` branch on the Bioconductor
github server will serve as devel and `RELEASE_X_X` will serve as the release.
Different version can be installed using `BiocManager::install()` along with
`BiocManager::install(version = "devel")` if the user wants to use the
development version.

**Comment by jdekanter** [comment]
Thank you for the elaborate review. I'm sorry for not answering, but I'm looking into it!

**Comment by jdekanter** [comment]
Hey! The error that is thrown, is that the vdiffr package is not available on the OS X machine, which I do not understand, as it is part of CRAN.

**Comment by jdekanter** [comment]
I changed all things mentioned in your review! Expect for one:

> [REQUIRED] L1188-1191: Inefficient copy-and-append pattern. Replace with:
> row <- seq_len(nrow(conf_df))
> sub_score <- conf_df[row, sub_clas[row]]

I did not incoporate this, because I those original lines:

> for (row in seq_len(nrow(conf_df))) {
>     sub_score <- c(sub_score, conf_df[row, sub_clas[row]])
> }

, I extract different values from a matrix; each time a combination of a row and a column name extracted from subclass. In the example that you provide, It would extract a large martrix instead of a vector of separately extracted values.

**Comment by dvantwisk** [comment]
The changes look good. I suppose I wasn't keeping up with which types of objects I was trying to subset. Again, I suppose my purpose with that code is to show different techniques to vectorize your code which will make it perform better.

Aside from that, there appears to be an error on the building. This error is likely ours since the mac builder frequently fails to assemble its binaries. We can likely overlook it.

I'll give you package one more look through and accept it if everything looks good.

**Comment by jdekanter** [comment]
The tips on vectorization were really useful. I guess I frequently loop over things that can be vectorized, also in other code, so that was a useful tip! 

The error in the code on the macs builder was the fact that the vdiffr package that I use for the tests on the plotting functions is apparently not available there, so that is indeed not something I can fix from here.

Thanks for your time on the package! I hope you can indeed accept it :)

**Comment by dvantwisk** [comment]
I've looked over your package and the changes look great! I'm going to move to accept it now.

**Comment by jdekanter** [comment]
Great! Thanks a lot

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jdekanter.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CHETAH")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CHETAH

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
