### ISSUE TITLE
bodymapRat: An experiment data package that contains a SummarizedExperiment object from the Yu et al. (2014) paper that performed the rat BodyMap across 11 organs and 4 developmental stages

### ISSUE THREAD

**Issue by stephaniehicks** [Bioconductor/Contributions#1026]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stephaniehicks/bodymapRat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by stephaniehicks** [comment]
AdditionalPackage: https://github.com/stephaniehicks/qsmooth

**Comment by lshep** [comment]
Sorry for the delay in the review -  I should have a review within this next week.

**Comment by stephaniehicks** [comment]
No problem, thanks for the status update!

**Comment by lshep** [comment]
Here is a review of the data package. I'm looking a qsmooth now and will have it either later today or tomorrow morning at the latest:
# bodymapRat

**General:**
- [ ] The package should probably be converted into an ExperimentHub package; removing the large data file from the package and storing it on S3. We are
encouraging all submission with large data to utilize the hubs to keep the
packages small and lightweight. Nothing would really change except adding
ExperimentHub to the biocViews and Imports,  creation of the metadata.csv file
so I could add it to the experimenthub data base, and uploading the data to
external site (I can give you credentials to upload to AWS S3 bucket hosted by
Bioconductor) and git removal from the package itself. 

https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

**Description**
- [ ] Please remove Maintainer.  The Maintainer specified with the "cre" in the
Authors@R is sufficient and it is not recommended to use both Authors@R and
Author/Maintainer fields. 

**README**
- [ ] Please update to also include Bioconductor installation instructions. 

**Vignette**
- [ ] Optional - It is more intuitive for a user to just do
vigentte("bodymatRat") rather than vigentte("bodymatRat-vignette"). I would
recommend renaming.

**inst/scripts**
Thank you for including this!! It is recommended but often forgotten.

**Comment by lshep** [comment]
In general both packages look really good and really well written.  Just a few clean up items here and there.  Please see the review of the qsmooth package:

# qsmooth

**General:**
- [ ] Was there a reason to create your own class for the result object rather
than doing an endomorphism and getting back a SummarizedExperiment as output
from the `qmooth` function since the dimensions seem the same? Although I
suppose you aren't actaully passing in a SummarizedExperiment but having the
user parse out the data from the SummarizedExperiment object ... 


**Description**
- [ ] Optional - recommend removing hard coded date as it can often be forgotten
about when updating 

**README**
- [ ] Please update to also include Bioconductor installation instructions. 

**Vignette**
- [ ] Optional - It is more intuitive for a user to just do
vigentte("qsmooth") rather than vigentte("qsmooth-vignette"). I would
recommend renaming.


**man**
- [ ] Optional - I like to recommend having a package overview page that gives a
brief overview of the package and points to the main functions. However since
the main function is the same as the package probably could be skipped. 

- [ ] qsmooth. The value isn't actually a matrix, it is an object of the class
  `qsmooth` that contains the matrix of normalized values as well as somthing
  else.  This should probably be clarified 

**R code**

- [ ] From running the code and examples, if you define your own qsmooth class
  maybe it would also benefit to creating a show method for the class. When
  printing the qsNorm example, it is the entire result values - think of how the
  value are truncated when you print a summarizedExpeiment object. Perhaps so
  you can see the slot names and maybe just the head of each of the results? 


- [ ] plots.R seems incomplete as far as implementation. None of your arguments
  are actually used when creating the plots or passed as additional
  arguments. If these are kept we would also encourage checking for proper
  format. 

- [ ] qsmooth.R optional but I would encourage additional argument checking such
  as if the object is of a particular class.


I look forward to working with you to get these package accepted.  Please update as necessary and make sure the webhook is initialzed.  When ready for a re-review please bump the version for a new report and comment here with a summary of the changes made.  Thank you!

**Comment by stephaniehicks** [comment]
Thanks @lshep! I have addressed the comments for the `bodymapRat` package and converted it to an ExperimentHub package. I'm also ready to upload the `.rda` file to AWS. I will wait for your guidance on next steps.

**Comment by lshep** [comment]
@stephaniehicks   Whats the best email to reach you to send you the S3 credentials?

**Comment by stephaniehicks** [comment]
shicks19@jhu.edu

**Comment by stephaniehicks** [comment]
@lshep I have uploaded the `.rda` file to AWS using the S3 credentials provided.

**Comment by lshep** [comment]
Great. I added the data into ExperimentHub so you will be able to test and debug your experiment package and software package.  Its only available in devel 3.9
```
> eh = ExperimentHub()
snapshotDate(): 2019-03-21

> query(eh, "bodymapRat")
ExperimentHub with 1 record
# snapshotDate(): 2019-03-21 
# names(): EH2257
# package(): bodymapRat
# $dataprovider: SRA
# $species: Rattus norvegicus
# $rdataclass: SummarizedExperiment
# $rdatadateadded: 2019-03-21
# $title: bodymapRat
# $description: Experimental dataset from the rat BodyMap project
# $taxonomyid: 10116
# $genome: Ensembl release 80
# $sourcetype: FASTQ
# $sourceurl: http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE53960
# $sourcesize: NA
# $tags: c("SequencingData", "RNASeqData", "ExpressionData",
#   "ExperimentData", "ExperimentHub") 
# retrieve record with 'object[["EH2257"]]' 
> 
> 
> query(eh, "bodymapRat")[[1]]
see ?bodymapRat and browseVignettes('bodymapRat') for documentation
downloading 1 resources
retrieving 1 resource
  |======================================================================| 100%

loading from cache 
    'EH2257 : 2257'
class: SummarizedExperiment 
dim: 32637 652 
metadata(0):
assays(1): counts
rownames(32637): ENSRNOG00000000001 ENSRNOG00000000007 ... ERCC-00170
  ERCC-00171
rowData names(0):
colnames(652): SRR1169893 SRR1169894 ... SRR1170551 SRR1170552
colData names(22): sraExperiment sraRun ... xtile ytile

```

**Comment by stephaniehicks** [comment]
I apologize for forced commits. I realized I still had the `data/bodymapRat.rda` file in the GitHub repo and needed to rerun http://bioconductor.org/developers/how-to/git/remove-large-data/. That should now be fixed. Next, I'm working on testing and debugging the package with ExperimentHub.

**Comment by lshep** [comment]
No problem at all!  Just let me know when the packages are ready for a re-review.  From first glance of them they seems in fairly good shape once we got the data worked out.  Cheers

**Comment by stephaniehicks** [comment]
@lshep -- Could you tell me how to update the snapshot date for `ExperimentHub()`? I am using bioc-devel and I read through the documentation (http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html), but it's not clear to me how to get `ExperimentHub()` point to the 2019-03-21 date instead of the 2019-01-25 date that I'm seeing. Thanks! 

```
> eh = ExperimentHub()
snapshotDate(): 2019-01-25
> sessionInfo()
R Under development (unstable) (2019-02-20 r76140)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.9 (Santiago)

Matrix products: default
BLAS: /jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-devel/R/devel/lib64/R/lib/libRblas.so
LAPACK: /jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-devel/R/devel/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices datasets  utils     methods  
[8] base     

other attached packages:
[1] ExperimentHub_1.9.1  AnnotationHub_2.15.8 BiocGenerics_0.29.2 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0                    AnnotationDbi_1.45.1         
 [3] magrittr_1.5                  IRanges_2.17.4               
 [5] bit_1.1-14                    xtable_1.8-3                 
 [7] R6_2.4.0                      blob_1.1.1                   
 [9] httr_1.4.0                    tools_3.6.0                  
[11] Biobase_2.43.1                DBI_1.0.0                    
[13] htmltools_0.3.6               yaml_2.2.0                   
[15] bit64_0.9-7                   digest_0.6.18                
[17] interactiveDisplayBase_1.21.0 shiny_1.2.0                  
[19] BiocManager_1.30.4            later_0.8.0                  
[21] S4Vectors_0.21.10             promises_1.0.1               
[23] curl_3.3                      mime_0.6                     
[25] memoise_1.1.0                 RSQLite_2.1.1                
[27] compiler_3.6.0                stats4_3.6.0                 
[29] httpuv_1.4.5.1                pkgconfig_2.0.2              
```

**Comment by lshep** [comment]
It should update automatically -  It is odd that it is not. I'll investigate this right away.

**Comment by lshep** [comment]
It seems like somehow the timestamp in the database got reverted.  I updated and everything should work accordingly now.  It should update automatically when you do a new eh = ExperimentHub( ) call ;   Please let me know if it does not.

**Comment by stephaniehicks** [comment]
Thanks! I see the same: 

```
> eh  = ExperimentHub()
snapshotDate(): 2019-03-27
```

**Comment by stephaniehicks** [comment]
@lshep the `bodymapRat` package is ready for re-review. I will start on updating the `qsmooth` package now. Will send message ready to re-review of that package.

**Comment by stephaniehicks** [comment]
I have implemented half of the requested changes from the Bioconductor review and will finish the second half this weekend. Here are the updates thus far:

Changes in version 0.99.2 (2019-03-29)
+ Removed hard-coded date in DESCRIPTION file
+ Included Bioconductor installation instructions in README.md file
+ Changed the name of the vignette so user can use `vigentte("qsmooth")`
+ man. Changed the description of the return to reflect the actual output

**Comment by stephaniehicks** [comment]
@lshep Thank you very much for the helpful feedback! I have now addressed all the points in your review of both the `bodymapRat` (https://github.com/Bioconductor/Contributions/issues/1026#issuecomment-472963444) and `qsmooth` (https://github.com/Bioconductor/Contributions/issues/1026#issuecomment-472977053) packages. Both are ready for re-review.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stephaniehicks.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bodymapRat")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bodymapRat

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stephaniehicks.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("qsmooth")`. The package 'landing page' will be created at

https://bioconductor.org/packages/qsmooth

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
