### ISSUE TITLE
PoTRA-Package

### ISSUE THREAD

**Issue by PoTRA-Package** [Bioconductor/Contributions#1029]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PoTRA-Package/PoTRA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by PoTRA-Package** [comment]
Hi - I am working with Dr. Valentin Dinu on the PoTRA submission.
He is the maintainer, and he is aware that I am making this submission on his behalf.
Please feel free to email him and CC my email for confirmation.

**Comment by mtmorgan** [comment]
Your package must include plain text files containing your R code in the R/ directory; it is not appropriate to include function definitions etc. in data/PoTRA.RData.

Additional initial comments:

DESCRIPTION

- please expand the DESCRIPTION to read more like a paper abstract, indicating the novelty, applicability, and merits fo your particular paproach.

- Please choose biocViews terms that are appropriate for your package; choose from the software hierarchy under http://bioconductor.org/packages/devel/BiocViews.html#___Software

- If a package provides functionality that a user will use, then include as Depends:, but if the package is needed only for use by your package use `Imports:`; packages in the `Depends:` field do not also need to be in the `Imports:` field.

NAMESPACE

- use `importFrom()` or `import(..., except=...)` to import selectively from individual packages, avoiding warnings such as

  ```
  Warning: replacing previous import 'graph::union' by 'igraph::union' when loading 'PoTRA'
  Warning: replacing previous import 'BiocGenerics::normalize' by 'igraph::normalize' when loading 'PoTRA'
  Warning: replacing previous import 'graph::degree' by 'igraph::degree' when loading 'PoTRA'
  Warning: replacing previous import 'BiocGenerics::path' by 'igraph::path' when loading 'PoTRA'
  Warning: replacing previous import 'graph::intersection' by 'igraph::intersection' when loading 'PoTRA'
  Warning: replacing previous import 'graph::edges' by 'igraph::edges' when loading 'PoTRA'
  ```
  
vignettes

- Do not write code 'by hand' in HTML; use fully evaluated code chunks. This ensures that the code actually works, rather than merely 'looks good'.

- Do not install packages in your vignette; use `Suggests:` in the DESCRIPTION file to ensure that the packages are available by the build system.

LICENSE

- file is not needed; LGPL text is included in base R.

Other

- The warning
  ```
  Undocumented data sets:
    '.Random.seed' 'PoTRA.corN'
  ```
  likely means that you have saved .Random.seed in one of your data sets; remove this variable.

- The warngin
  ```
  * checking for unstated dependencies in vignettes ... NOTE
    'library' or 'require' call not declared from: 'repmis'
  ```
  means that you must `Suggests: repmis` in your DESCRIPTION file

**Comment by PoTRA-Package** [comment]
Hi - I need help understanding the error and warnings, they seem to be on the Bioconductor side.
Perhaps these are bugs?

**Comment by mtmorgan** [comment]
ours, ignore
```
* checking for future file timestamps ...Warning in file(con, "r") :
  cannot open URL 'http://worldclockapi.com/api/json/utc/now': HTTP status was '403 Forbidden'
 WARNING
unable to verify current time
...
* Checking for deprecated package usage...
Warning in readLines(file, skipNul = TRUE) :
  URL 'https://bioconductor.org/packages/release/bioc/VIEWS': status was 'SSL connect error'
Error in readLines(file, skipNul = TRUE) : 
  cannot open the connection to 'https://bioconductor.org/packages/release/bioc/VIEWS'
Calls: <Anonymous> ... checkDeprecatedPackages -> getAllDeprecatedPkgs -> read.dcf -> readLines
Execution halted
```
yours
```
* checking R code for possible problems ... [8s/8s] NOTE
PoTRA.corN: warning in page.rank(graph.normal, direct = FALSE): partial
  argument match of 'direct' to 'directed'
PoTRA.corN: warning in page.rank(graph.case, direct = FALSE): partial
```
please address, where appropriate:
```
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        PoTRA-devel.R (line 18, column 15)
        PoTRA-devel.R (line 18, column 41)
        PoTRA-devel.R (line 49, column 23)
        PoTRA-devel.R (line 57, column 39)
        PoTRA-devel.R (line 57, column 90)
```

For this:
```
    * NOTE: Consider shorter lines; 89 lines (14%) are > 80 characters
      long.
    ...
```
very long lines with highly nested commands and no spaces are very difficult to read.

**Comment by GenomicsPrograms** [comment]
Dear Martin,

I attempted to replace the "1:" with seq_along and seq_len but these altered the output and thus caused the program to generate erroneous results. Thus I will have to keep PoTRA as is. 

The complexity of the PoTRA program would make it hard to rewrite in certain spots. Would it be ok to keep PoTRA as is? 

Thank you for understanding,
Margaret

**Comment by PoTRA-Package** [comment]
Dear Martin, 

GenomicsPrograms is my other github, I am now signed in as PoTRA-Package.
Here is my message again.

I attempted to replace the "1:" with seq_along and seq_len but these altered the output and thus caused the program to generate erroneous results. Thus I will have to keep PoTRA as is.

The complexity of the PoTRA program would make it hard to rewrite in certain spots. Would it be ok to keep PoTRA as is?

Thank you for understanding,
Margaret

**Comment by PoTRA-Package** [comment]
Dear Martin,

I attempted to replace the "1:" with seq_along and seq_len but these altered the output and thus caused the program to generate erroneous results. Thus I will have to keep PoTRA as is.

The complexity of the PoTRA program would make it hard to rewrite in certain spots. Would it be ok to keep PoTRA as is?

Thank you for understanding,
Margaret

**Comment by PoTRA-Package** [comment]
Dear Martin,

Just checking in to see if there is any feedback available regarding my previous message.

Thanks so much,
Margaret

**Comment by LiNk-NY** [comment]
Hi Margaret, @PoTRA-Package 

You should be able to use `seq_len(length(Pathway.database))` if `seq_along`
doesn't work for that object. 

The Biocondcutor package review process is designed to provide feedback for the
overall improvement of quality of packages that are accepted to Bioconductor.
Please ensure that your package meets the package guidelines https://www.bioconductor.org/developers/package-guidelines/ and that you
respond appropriately to feedback.
We do this because we value our users' experience and want to minimize
error-prone software.

Currently, the code in the package is highly nested and is hard to read and review.
Please start by providing formatted code and un-nested commands.

Best, 
Marcel

**Comment by PoTRA-Package** [comment]
Thank you for the quick response Marcel. I have made the suggested changes to the PoTRA code,
so that seq_along and seq_len are used, as well as improved readability.

**Comment by mtmorgan** [comment]
Is your package ready for final review? If so please increment the version one last time...

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PoTRA-Package.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PoTRA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PoTRA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
