### ISSUE TITLE
PAST

### ISSUE THREAD

**Issue by adamthrash** [Bioconductor/Contributions#1032]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/IGBB/PAST

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please provide a more meaningful vignette, e.g., describing steps necessary and format of each data input, illustrating key assumptions and unique aspects of analysis implemented in the package, and providing technical and biological interpretation of results.

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 
Please respond to Martin's comment.

Best, 
Marcel

**Comment by adamthrash** [comment]
> Please provide a more meaningful vignette, e.g., describing steps necessary and format of each data input, illustrating key assumptions and unique aspects of analysis implemented in the package, and providing technical and biological interpretation of results.

I'm working on adding information about the format of data inputs and providing information about interpretation, but I'm not sure what you mean by "describing steps necessary." The steps described by the vignette are the only steps necessary to run PAST. Could you clarify what you mean by that, @mtmorgan?

**Comment by mtmorgan** [comment]
For instance you have a file association.txt.xz but it is not clear where this file would have come from. I guess you mean PAST to be used as part of a larger pipeline, but 'from the outside' it is not at all clear what that pipeline is.

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 
Please provide an update on the status of the package. 
Otherwise, I'd be forced to close it. 
Best regards,
Marcel

**Comment by adamthrash** [comment]
Hi Marcel @LiNk-NY, I'm getting together documentation as requested by @mtmorgan for the vignette. I expect to be adding information this week.

**Comment by adamthrash** [comment]
@LiNk-NY @mtmorgan I've added more information to the vignette about the types of expected input.

**Comment by adamthrash** [comment]
@LiNk-NY how serious are the warnings in the build? In my experience working locally, I ran into an issue in which fixing the issue in R CMD CHECK caused issues in BiocCheck, and fixing the issue in BiocCheck caused issues in R CMD CHECK. Any suggestions?

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 
Please fix the warnings in the report. 
Specifically, there is a warning of a code-doc mismatch:

```
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'parse_temp':
parse_temp
  Code: function(chunk, r_squared_cutoff)
  Docs: function(data, r_squared_cutoff)
  Argument names in code not in docs:
    chunk
  Argument names in docs not in code:
    data
  Mismatches in argument names:
    Position: 1 Code: chunk Docs: data
```

as well as a R version warning which should be R `3.6.0`. 

Best, 
Marcel

**Comment by adamthrash** [comment]
@LiNk-NY I pushed a fix to these changes yesterday, but the bot doesn't seem to have registered the push.

**Comment by lshep** [comment]
We were having issues yesterday with the tracking system.  The issues should be remedied. Could you please try another version bump and let us know if you continue to have issues.

**Comment by adamthrash** [comment]
@LiNk-NY I've resolved most of the warnings, except for one about an import. This is the warning that I had trouble resolving in testing. Solving it for BiocCheck produced it in R CMD check, and solving it in R CMD check produces a warning in R BiocCheck. Any advice?

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 

It seems like you have two packages at hand. 
It would be best to separate the shiny and analysis components.
You may also submit your shiny package separately to Bioconductor.
This reduces the number of dependencies for those that are interested in using
just the analysis functions in your package. 

I will review your package today. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 

Thank you for your submission.
Please note that `PAST` does not make use of Bioconductor infrastructure. We strive to provide an inter-operable environment for our user base. 
Please see # 8 in our package guidelines: https://bioconductor.org/developers/package-guidelines/#description
If you have any questions, respond here.

Best,
Marcel

---

# PAST #1032

Currently, `PAST` would be a good CRAN package as it does not take
advantage of the Bioconductor infrastructure.

## DESCRIPTION

* Looks good, thanks for separating out the `shiny` dependencies.
* Please provide a more substantial `Description` field and
organize package dependencies so that there is one package per line
or respecting the 80 column width limit.
* There appears to be no Bioconductor dependencies

## NAMESPACE

* Function names can be more descriptive, i.e., `analyze_pathways` is too
vague
* `merge_data` can mean anything as well

## vignettes


* Keep text within the 80 column width limit for readability and tidiness
* It's a bit short. Please detail the methods in the vignette..

## R

* Provide more descriptive dataset names, 'genes' can represent anything
* `rugplots_data` should really be created and obtained from the examples
* The API makes no use of Bioconductor infrastructure such as `GPos`/`GRanges`
* Functions assume that there are naming conventions in such files which is
not always the case
* Avoid using `print`
* Use `stop` to exit the function with an error instead of `print`
* Use the more robust `seq_len` or `seq_along` to create a sequence rather than
`seq`
* Avoid nesting `ifelse` statements, create a `data.frame` of conditions and
resulting values instead (`R/parse_SNP.R`)
* Do not save plots or create folders for users without their explicit
authorization

**Comment by adamthrash** [comment]
@LiNk-NY in your comment:

> Do not save plots or create folders for users without their explicit authorization

Which function is saving plots? As far as I am aware, all test/examples save to `tempdir()`.

**Comment by adamthrash** [comment]
Which functions assume naming conventions? I pushed several changes after your comment that you would begin reviewing that resolve our error of assuming naming conventions in the input data, and instead ask the user to provide the type of TASSEL analysis they ran.

**Comment by LiNk-NY** [comment]
@adamthrash 
The example: 
```
plot_pathways(rugplots_data, "pvalue", "0.03", "decreasing", "results")
```
creates a `results` directory in the 'home' folder. This is not what we want in the builders
and on our user's computers.

**Comment by LiNk-NY** [comment]
> Which functions assume naming conventions? I pushed several changes after your comment that you would begin reviewing that resolve our error of assuming naming conventions in the input data, and instead ask the user to provide the type of TASSEL analysis they ran.

Functions such as `parse_LD` and others assume that the input files contain standard
column names (i.e., they use hard-coded column names). In the end, the hard-coded 
values could work out **if** the file structures _don't_ change but it is often the case that
they _do_. It is recommended to provide column names as part of the arguments in the
function (with default values) possibly as a vector.

**Comment by adamthrash** [comment]
Thank you for your feedback. I will begin working on incorporating these changes and adding the use of `GRanges` for reading annotation information. I am still interested in publishing on Bioconductor.

**Comment by adamthrash** [comment]
What does 

> `rugplots_data should really be created and obtained from the examples

mean?

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 

You can run examples using `example(plot_rugplots)`. 
Your example code can generate a simulated / toy dataset. It's better to keep them minimal. 
If you must, then include an `*.Rdata` file.

**Comment by adamthrash** [comment]
Why is our dependency on [qvalue ](http://bioconductor.org/packages/release/bioc/html/qvalue.html) not considered a dependency from Bioconductor?

**Comment by adamthrash** [comment]
Hi @LiNk-NY,

I've described my changes [here](https://github.com/IGBB/PAST/pull/30), and most of your suggestions have been resolved. There is a warning, but per an email from Bioc-Devel this morning, these warnings seem like they are a temporary issue with the build servers.

**Comment by LiNk-NY** [comment]
Hi Adam, @adamthrash 

Thank you for working on those changes. I hope this review process has been valuable. 
Your package has been accepted to Bioconductor. 

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adamthrash.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PAST")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PAST

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
