### ISSUE TITLE
nanotubes

### ISSUE THREAD

**Issue by MalteThodberg** [Bioconductor/Contributions#1033]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MalteThodberg/nanotubes

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by MalteThodberg** [comment]
This is a data package for a workflow - let me know when in should activate the workflow package itself.

**Comment by Liubuntu** [comment]
Hi @MalteThodberg , 

Thank you for submitting this data package. An initial review will be done and posted very soon. 

Best,
Qian

**Comment by MalteThodberg** [comment]
Dear Qian!

That sounds good. As mentioned above, this package is a data package for a workflow package. Let me know when I should add the workflow package to this issue.

**Comment by Liubuntu** [comment]
Hi @MalteThodberg , 

The package submission deadline for next release would be around April 5th (not officially announced yet). I'll try to finish the review of this data package before this date, so that you can submit the workflow package before the deadline. Otherwise, we can make it an exception if we miss it. 

Sorry for the delay though, we are experiencing a big flow of packages at this time before release. But I'll keep you posted for the updates. Thanks for understanding!

Best,
Qian

**Comment by MalteThodberg** [comment]
Dear Qian!

That sounds good. Once the data package and worflow has been added to bioconductor, it can be reviewed at f1000.

Im on vacation until March 31.

**Comment by Liubuntu** [comment]
Hi @MalteThodberg , 

Bioconductor now encourage package developers to submit their software (or workflow) package together with a data package. So you can submit your workflow package now (before 4/5/2019), and the build system could recognize both. 

Thanks,
Qian

**Comment by Liubuntu** [comment]
Hi @MalteThodberg , 

Please see following for the initial review of your data package. Modify and bump version to trigger the build. Thanks!

Best,
Qian

## DESCRIPTION

Looks good. But consider adding the following fields:

- "BugReports:" field: It is encouraged to include the relevant links
  to Github for reporting Issues.
- "URL:" field: This field directs users to source code repositories,
  additional help resources, etc; details are provided in “Writing R
  Extensions”, RShowDoc("R-exts").

I understand that you have these info in the vignette. But include
them in DESCRIPTION would print out in the Bioconductor package launch
page and easier to navigate users.

## man/
- nanotubes.Rd: L8. typo in "Ctrl (untread)". Should it be "untreated"?

## R/
- Good!

## README.md & README.Rmd

- These two files contains almost identical contents. Remove the
  "README.Rmd".

## vignette

- Looks good!

**Comment by MalteThodberg** [comment]
AdditionalPackage: https://github.com/MalteThodberg/CAGEWorkflow

**Comment by MalteThodberg** [comment]
Hello again @Liubuntu!

Thank you for the comments for the data package. I've have implemented all, except the README-files, both of which are used to generate a pretty opening page on GitHub.

I've also added the workflow itself, and it now passes checks on Mac and Linux. It fails on Windows since CAGEfightR uses the BigWig-functions from rtracklayer that are not supported on Windows - how can I specify that the workflow is not runnable on windows?

**Comment by ahmohamed** [comment]
Not an official answer. But `.BBSoptions` file with `UnsupportedPlatforms: win` should work. See https://github.com/Bioconductor/ensemblVEP/blob/master/.BBSoptions as an example.

**Comment by lshep** [comment]
Yes this would be the correct solution adding the .BBSoptions as described above

**Comment by MalteThodberg** [comment]
I have added the BBSoptions files as described by @ahmohamed and @lshep .

**Comment by Liubuntu** [comment]
Thanks @ahmohamed and @lshep for offering the help! 

Hi @MalteThodberg , 

Thanks for making the updates to the data package. I'm accepting it now and moving forward with the workflow package. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @MalteThodberg , 

Please see below for the review of the CAGEworkflow package. It is very well written and organized!

Cheers,
Qian

## DESCRIPTION

- “LazyData:” field: For packages that include data, we recommend not
  including `LazyData: TRUE`. This rarely proves to be a good
  thing. In our experience it only slows down the loading of packages
  with large data.
- Please add a `Depends: R (>= 3.6.0)` field. If your workflow package
  depends on the `nanotube` data package, also add it in this field.

## data_raw/cache.R
- If your workflow package depends on the `nanotube` data package, you
  may want to replace those local file path `~/BINF/CAGE_data/...`
  with something like the following, so that the users could reproduce
  the data by your script.
```
library(nanotube)
data(nanotubes)
bw_path <- system.file("extdata",
                       nanotubes$BigWigMinus[1],
                       package="nanotubes",
                       mustWork = TRUE)

```

## vignette/CAGEworkflow.Rmd
- L8: Typo in "This is workflow is...", should be "This workflow is ...".
- L264: Typo in "This leaves almost 10.000 enhancer candidates for
  analysis."? Was it supposed to be "10,000" instead of "10.000"?
- Maybe run a spell checker for the whole vignette.

**Comment by MalteThodberg** [comment]
Dear @Liubuntu ,

Thanks you for the detailed look. I've added all of your suggestions:

DESCRIPTION: Technically, neither R-3.6 or nanotubes are strictly needed in Depends, since the workflow package doesn't contain any data and packages used in vignettes are normally placed under Suggests. However, I have added them to Depends if this complies better with Bioconductor standards.

data_raw: This was an old forgotten folder from before I added the data package. I have simply removed the folder.

vignette: I have run a spell checker and fixed many smaller typos, including the ones you suggested.

**Comment by Liubuntu** [comment]
Hi @MalteThodberg , 

It's strongly recommended that new packages (software/workflow/hubs...) `Depends` on `R (>= 3.6.0)` unless developer strongly oppose with good reason. It's fine that you put the `nanotubes` in the `Imports` field though. I am accepting both of packages now! 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MalteThodberg.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("nanotubes")`. The package 'landing page' will be created at

https://bioconductor.org/packages/nanotubes

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MalteThodberg.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CAGEWorkflow")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CAGEWorkflow

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
