### ISSUE TITLE
batchelor

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1034]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/batchelor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Hey @LTLA 
I'm seeing that you still have some issues with build time. The check time I am seeing on both out osx and linux builders is about 6 minutes and could be overlooked if there is nothing else you can do to reduce the this time. I do need to see you get rid of the timeout on the windows system, however.

**Comment by LTLA** [comment]
Thanks @dvantwisk. I suspect that one of the functions is silently using `bpparam()` and that's causing the time-out on Windows due to the slowness of `SnowParam()`. I guess that's part of the reason why I was requesting to @mtmorgan that `bpparam()` default to `SerialParam()` on all systems, to avoid getting ambushed by slowdowns like this. Indeed, none of my functions are directly using `SnowParam()` or `bpparam()`; I suspect it's one of the _DelayedArray_-related functions implicitly doing so.

**Comment by LTLA** [comment]
Yep, pretty much as I thought. Now I have to go through and figure out which of these functions is the problem child...

**Comment by dvantwisk** [comment]
Alright. I assume very little is going to change so I am going to have a look through the package now.

**Comment by LTLA** [comment]
Whoops. Failures due to my _beachmat_ version 2 update; left hand forgot to talk to the right. Will fix tomorrow.

**Comment by LTLA** [comment]
Argh. It's just one thing after another today. The package builds fine on my 10yo Linux laptop (3min 4s) so I don't know what's happening here.

**Comment by dvantwisk** [comment]
Hi @LTLA 
I've looked over your package and am happy to say I don't have any changes of substance to add; you're as great as ever with writing packages.

It however, doesn't seem that your most recent changes have been built so maybe try another push to see if we can get it to run.

Once the package builds fine with the most recent changes I will accept it.

**Comment by LTLA** [comment]
Nudge.

**Comment by dvantwisk** [comment]
Sorry for the delay! I'll accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("batchelor")`. The package 'landing page' will be created at

https://bioconductor.org/packages/batchelor

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
