### ISSUE TITLE
Package submission: scds

### ISSUE THREAD

**Issue by kostkalab** [Bioconductor/Contributions#1037]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kostkalab/scds

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Your Description is mal-formed. You'll have to fix it to get a build report. 

https://github.com/kostkalab/scds/blob/master/DESCRIPTION

**Comment by kostkalab** [comment]
Hi, 

Have you started reviewing? The warnings are unrelated to code in the package. 

Thanks a lot,

Dennis

**Comment by lshep** [comment]
Yes.  I will have an official review before the end of the week.

**Comment by kostkalab** [comment]
Great thanks!

**Comment by lshep** [comment]
The package in general looks in good shape.  Please find my review below: 

**Build Report**
- [ ] Please clean up coding notes about Avoiding 1:... 

**README**
- [ ] Include Bioconductor installlation instructions

**LICENSE**
- [ ] (Optional) The MIT license is included with the R release so you do not
strictly need to include it  https://www.r-project.org/Licenses/

**Description**
- [ ] Please use Authors@R (preferred) or Author/Maintainer fields but not
both. 

**NEWS** 
- [ ] We strongly encourage a news file so that updates to the package can be
announced http://bioconductor.org/developers/package-guidelines/#news

**Tests**
- [ ] We strongly encourage the use of unit tests
http://bioconductor.org/developers/package-guidelines/#unittest

**MAN**
OK

**Vignette**
- [ ] Optional - It is much more intuitive to do vignette("scds") than it would
be to do vignette("vignette-intro").  I would recommend renaming the
vignette. Also with something generic like that, there is a chance the wrong
vignette will be accessed by a user... for instance when I blindly did the
vignette call without the package it actually gave me the one from scatter
instead of yours. 
```
> library(scds)
> vignette("vignette-intro")
starting httpd help server ... done
Warning message:
vignette 'vignette-intro' found more than once,
using the one found in '/home/lori/R/x86_64-pc-linux-gnu-library/3.6-BioC-3.9/scater/doc' 

```
- [ ] Include Bioconductor installation instructions
- [ ] Section 3.2, I feel like a brief indication of the difference between cxds
and bcds would be helpful. The link to the manuscript is good but not everyone
will follow it, so even just a few words to clarify the difference between the
two. And what exactly is gonig on with the cxds_bcds_hybrid -  The pipeline is
good but the clarification of what each step is really doing is somewhat
lacking. I would recommend just adding a few lines of more detail. 

**R code**
- [ ] I would put in a validation check on the sce object to make sure it is of
class SingleCellExperiment and that it has the needed assay matrix counts. 
- [ ] Update from using `cat` to using `message`. It is more appropriate for
printing status messages. 

Please update and perform a version bump to kick off a new build. When you are ready for a re-review please comment back here with what has been updated and I will look at the package again.  Cheers!

**Comment by kostkalab** [comment]
Thanks a lot for the comments, they've been helpful!
Addressed them in an incremented version and  the new package seems to build fine. 
It'd be great if you could take a second look. Here is what's changed in a bit more detail:

* Now consistently using seq_len

* Added NEWS file in ./inst/

* DESCRIPTION now only  uses Authors@R

* Added Bioc installation instructions to README.md

* Added Bioc installation instructions to vignette

* Renamed vignette to "scds"

* Expanded text in the doublet prediction section (3.2) of the vignette.

* Checked that first argument for cxds and bcds functions:
  needs to be a SingleCellExperiment with "counts" in the assasys slot

* Replaced cat with message

* Used usethis::use_mit_license() to generate license files

**Comment by lshep** [comment]
Looks good.  Thank you.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kostkalab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scds")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scds

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
