### ISSUE TITLE
(inactive) Transcriptome Annotation with Trans2Kegg

### ISSUE THREAD

**Issue by croesel** [Bioconductor/Contributions#1038]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/croesel/Trans2Kegg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please address the following and, when done, post a short comment summarizing your changes.

Package

- Please create, at least for the submission process, a 'master' branch containingly only files to be imported into the Bioconductor git repository, e.g., DESCRIPTION / NAMESPACE / NEWS / R / vignettes / man / inst / tests / .Rbuildignore / .gitignore.

DESCRIPTION

- `person(role=...)` can be a vector, so only one entry necessary per person
- please provide a paragraph-length Description: that more completely describes what your package does. For instance, it would be helpful to indicate when your package would be used, versus existing Bioconductor infrastructure and packages.

NEWS

- only include if you intend to update (recommended)

vignettes

- please also clean up this directory to contain only the .Rmd and .bib file (.html is generated when the package in installed). I believe that the csv files should not be here, either?

R (comments on specific lines; apply throughout)

- It seems like you're using files to accumulate temporary results; this seems unnecessary in general, unless results are very large
- row-wise operations on data.frames, and creating small temporary data frames, can be very expensive; often the row-wise operations can be re-implemented to act on columns (vectors), avoiding the need for small temporary data.frames.
- Only R files should be present in the R directory
- Consider adopting a more consistent identation style so that 'continuation' lines are always indented, e.g., write annotateAws.R:45 as

        blastResult <- blastSequencesAWS(query,
            database="swissprot",program="blastx",
            fmt="data.frame", expect=1e-5,instance=instance,
            dns=dns, threads=threads)
- annotateDE.R:43 this 'copy-and-append' pattern is inefficient; one solution is to create a list of results, possibly with NULL entries, and then use do.call,
    ```
    df <- lapply(resultsNames(ddsALL), function(...) {
        # return df or NULL
    })
    do.call(rbind, df)
    ```
    
- annotateDE.R:46 results should not be written to the file installation directory; provide an argument `output = tempfile()` for the user to specify a file; using `tempfile()` as default means that the examples and tests write to a temporary location that is guaranteed not to exist before use and is cleaned up when the R session exits.

- getKegg.R: I find the indentation of this file very difficult to read. For instance I would write

                            newOrtho <- tryCatch(data.frame(row.names=kegg,
                            "kegg"=kegg, "ko"=names(ortho),
                            "desc"=ortho[names(ortho)]),
                            error=function(e) print(ortho))

  so that items playing similar roles (e.g., arguments to `tryCatch()`)  are indented at the same level

                        newOrtho <- tryCatch(
                            data.frame(
                                row.names=kegg,
                                "kegg"=kegg, "ko"=names(ortho),
                                "desc"=ortho[names(ortho)]
                            ),
                            error=function(e) print(ortho)
                        )
                        
  Don't use `print()` to communicate information to users; perhaps the intention here is `message()`? My sense here is that you are trying to 'log' unusual outcomes, and it might make sense to use a package like futile.logger to do this in a more formal sense.

                        newOrtho <- tryCatch(
                            data.frame(
                                row.names=kegg,
                                "kegg"=kegg, "ko"=names(ortho),
                                "desc"=ortho[names(ortho)]
                            ),
                            error=function(e) {
                                flog.error(conditionMessage(e))
                                NULL
                            }
                        )

- getKegg.R:17-18 `accDone` seems unused in the function; `rowNum` is incremented but not otherwise used.
- getKegg.R:23 use `&&` when performing scalar (1-length) comparisons
- getKegg.R:24 here (and elsewhere) it seems you want to use `stringsAsFactors=FALSE`?
- getKegg.R: this makes extensive use of the 'copy-and-append' pattern, and is likely to be inefficient.
- getKegg.R:28 `keggGet()` is vectorized, so it would be better to get all entries at once `keggGet(newRow$kegg)`
- localBLAST.R:17 this loop seems unnecessary?
    ```
    transSeq <- refTrans[accessions]
    writeXStringSet(...
    ```

tests

- hmm, no meaningful unit tests; I suggest you remove this directory (or implement tests, using the testthat framework rather than RUnit).

scripts

- are the files here referenced in the package? if not, they should be removed from the git repository.

**Comment by mtmorgan** [comment]
Will you complete revisions in time for the forthcoming release, deadline [here][1]

[1]: http://bioconductor.org/developers/release-schedule/

**Comment by croesel** [comment]
Hi Martin,
I won't be able to make the deadline. Some of the required changes are in conflict with limits of the KEGG API (yes, it accepts vectorized but not more than 10, for example) so it's going to take me a while to resolve.
Chuck

**Comment by mtmorgan** [comment]
OK I'll mark this as 'inactive'; it can be re-opened when you're ready to continue.

**Comment by croesel** [comment]
Great, thank you for being flexible. I'll reopen as soon as I can get the work done.
Chuck
