### ISSUE TITLE
PhyloProfile

### ISSUE THREAD

**Issue by trvinh** [Bioconductor/Contributions#1039]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:  https://github.com/BIONF/PhyloProfile

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by trvinh** [comment]
@nturaga hi, I have just pushed a new commit to the master branch and also saw a new ping in the webhook response history. But here it shows nothing new. Is it normal?

**Comment by trvinh** [comment]
@nturaga I got it now. I've thought changing from "1.0.0" back to "0.99.0" is already a valid version number change. I'm sorry if I disturbed you!

**Comment by trvinh** [comment]
@nturaga sorry for disturbing you, but for this warning I cannot find a solution. 
WARNING: Use Authors@R (preferred) or Author/Maintainer fields not both.

I've already updated the DESCRIPTION file in order to remove the Maintainer field, but the warning still exists. Could you please help me on this issue? Many thanks!

**Comment by nturaga** [comment]
This is an issue on our end. Please make other changes if you need to
improve your package, once you are ready for a review leave a not saying
you are. I'll review your package.

Best,

Nitesh

**Comment by trvinh** [comment]
@nturaga Dear Nitesh, I think it is ready for review. 
Best,
Vinh

**Comment by nturaga** [comment]
Please issue another version bump, the warnings should have been resolved.

**Comment by trvinh** [comment]
@nturaga done! :)

**Comment by mtmorgan** [comment]
General

- It's not appropropriate to have your package depend heavily on data
  that is hosted on github; this data should be made available as an
  ExperimentData package or collection of ExperimentHub resources.
- Please pay particular attention to writing _vectorized_ code (no
  explicit iteration in _R_) that does NOT follow the
  'copy-and-append' pattern
  https://bioconductor.org/developers/how-to/efficient-code/ .

DESCRIPTION

- please provide a Description: that is more like an abstract,
  providing an overview of functionality and perhaps comparision with
  other similar packages
  
NEWS

- Make sure the NEWS file can be parsed by `utils::news()`

Other

- please remove extraneous (non-R package) files from this branch,
  e.g., the `www/` directory
  
vignettes

- good

R -- Comments are for specific functions but should be applied
throughout

- analyzeDistribution.R:16 the strategy here seems to be to rename
  columns to match expectations, but a better strategy would be to
  check that the inputs match expectation, e.g., using `stopifnot()`.
- analyzeDistribution.R: 30 it seems unnecessarily verbose to fully
  resolve functions in your own pacakge
- analyzeDistribution.R:48 `as.numeric(as.character())` seems like you
  are struggle with factor represenation of integer values, why not
  insist that the data is integer- (or numeric-) valued up-front, to
  avoid this dangerous coercion?
- clusterProfile.R:96 iterations (`for` loops, `*apply()`, etc) are
  expensive in R, be sure that these are necessary. Even if necessary,
  revise your code to 'hoist' common operations out of loops to
  minimize the time identical code is evaluated, e.g.,
  
  ```
  n <- seq_len(nrow(profiles))
  matrix[cbind(n, n)] <- 0
  for (i in seq_len(nrow(profiles))) { # rows
      p_i <- unlist(profiles[i,])
      for (j in seq_len(nrow(profiles))) { # columns
          if (i == j)
              break
          matrix[i, j] <- dcor(p_i, unlist(profiles[j,]))
      }
  }
  # Swich the value so that the profiles with a high correlation
  # are clustered together
  matrix <- 1 - matrix
  ```
- compareTaxaGroups.R:137 use `message()` to communicate progress to
  the user; usually no need to `message(paste(...))`, just
  `message(...)`.
- compareTaxaGroups.R:166 updating a data.frame is relatively
  expensive (copies the entire data frame); keep track of simple
  vectors and update the data.frame once.
- compareTaxaGroups.R: 181 'copy-and-append' (`rbind()`, here) is
  expensive, copying the data frame for each gene. Use
  'pre-allocate-and-fill' or `lapply()` / similar to better manage
  memory; see
  https://bioconductor.org/developers/how-to/efficient-code/ .
- compareTaxaGroups.R:235 returning different data types (character
  vector, versus data.frame) generally makes code more complicated
  than it needs to be -- return a zero-row data.frame, and write
  downstream functions so that they work with zero-row data.frames. 
- compareTaxaGroups.R:366 are `var1`, `var2` used in this function?
- getFastaSeq.R: 72 no need to re-invent a fasta parser (hmm, but I see you use Biostrings a few lines down?? why implement two different ways of doing the same thing?)
  ```
  > Biostrings::readAAStringSet(fastaURL)
    trying URL 'https://raw.githubusercontent.com/BIONF/phyloprofile-data/master/demo/fastaFile/concatenatedSeq.fa'
    Content type 'text/plain; charset=utf-8' length 1275183 bytes (1.2 MB)
    ==================================================
    downloaded 1.2 MB
    
      A AAStringSet instance of length 1931
           width seq                                            names
       [1]  1376 MDFGGVGRSDRPNRATTLTLLS...APKLGIVPGIAFVSVFVVLLI A.aegypti@7159@16034
       [2]  1016 MKLNITSAAGIICLLDEPIQEL...GPKNDDLKEPEAPEPFEYIED A.aegypti@7159@8
       [3]  4525 MSGFGTSTGSDLHFRALPYLDK...VLHMNMFRFLGVLMGIAVRTG A.aegypti@7159@5431
       [4]   609 MSRNRAAEETDKQTRIAIVSSD...TNSVKDTEQKRAGQYFFYEES A.aegypti@7159@9350
       [5]   342 MTLPSSARVYADVNSHKPREYW...FAVIVNGQMPPPSSSTKGSNQ A.aegypti@7159@11472
       ...   ... ...
    [1927]   307 MRNLLTDSFELGKRGQSSGNVD...IILLIIILIIILSLKPWSWGK Z.mays@4577@268479
    [1928]  1007 MAAVATVSSASGLLAMLQEPAP...GSSAMAVDDEPQPPQPFEYSS Z.mays@4577@228614
    [1929]   418 MWRATRRSPPFLRWLSSDAASS...VHVSCGFNHTGAIYECSEDFD Z.mays@4577@298043
    [1930]   604 MAERLTRIAIVSEDKCKPKKCR...KLESTKDREQKSAGSYYYLDD Z.mays@4577@306796
    [1931]   332 MSKARVYTDVNVLRPKEYWDYE...EAMTHPYFQQVRAAENSRTRA Z.mays@4577@271955
  ```
  also, please clarify the use of this data -- it is not appropriate
  to host 1/2 of your package in github, 1/2 in Bioconductor.
- getFastaSeq.R:125 `paste0()` outside the loop, to avoid unnecessary
  iteration & function calls.
- getFastaSeqs.R:141 another 'copy-and-append' example
- getFastaSeqs.R:367 `reverse,character-method` is implemented in
  IRanges (already an implicit dependence through Biostrings).
- getOmaBrowser.R:81 avoid at least some iteration and copy-and-append
  with (outside the loop)
  ```
  pos <- strsplit(domains$location, ":")
  start <- vapply(pos, '[[', character(1), 1)
  end <- vapply(pos, '[[', character(1), 2)
  feature <- ifelse(
      nchar(domains$name > 0),
      paste0(domains$source, "_", ...),
      paste0(domains$source, "_", domains$domainid)
  )
  feature <- gsub("#", "-", feature)
  data.frame(start, end, feature)
  ```
- getOmaBrowser.R:214 another example (other examples in this file!)
  ```
  feature <- sub("#.*", "", domainList)
  data.frame(
      seedID = domainID, # why not name function argument `seedID` ?
      orthoID,
      length,
      feature,
      start = NA_integer_,
      end = NA_integer_,
      stringsAsFactors = FALSE
  )
  ```
- parseDomainInput.R:42 does `read.csv()` ever return an object that
  is _not_a data.frame?
- parseDomainInput.R:124 will `paste0()` ever generate a warning that
  requires supression?
- parseMainInput.R:198
  ```
  cidx <- seq_len(ncol(finalDf) - 3)
  colnames(finalDf)[cidx + 3] <- paste0("value_", cidx)
  ```

man

- e.g., createPercentageDistributionData -- place yourself in the seat
  of the user. A description such as 'dataframe contains raw input
  data in long format' is not enough guidance. Likewise, the return 'A
  dataframe ready for analyzing the ... is also not precise
  enough. Please revise all man pages appropriately.
  
other

- Please either remove the CODE\_OF\_CONDUCT from your submission (it is
  fine of course to retain this in your github repository, perhaps
  temporarily during the review process on a separate branch), or
  clarify the wording so that it is clear that you are speaking for
  your own 'project', rather than Bioconductor. Bioconductor of course
  encourages conduct consistent with this code, but the
  CODE\_OF\_CONDUCT document here is not a part of the Bioconductor
  project (e.g., we would not delegate 'Enforcement' to
  tran@bio....`).
- I'm not clear on the role of the files in inst/PhyloProfile; are
  these all part of the package or are some of them (e.g. global.R,
  help.html, scripts/, data/, R/) utilities that are useful to you but
  not the end user of this package? Please clean up the master branch
  of your repository to include only files strictly relevant to your
  package.

**Comment by mtmorgan** [comment]
Please revise your package in response to the comments above, and post a brief summary here when ready for the next review.

**Comment by nturaga** [comment]
Hi @trvinh 

If your package is to make the next release, (the deadline is tomorrow) I suggest you start pushing changes now allow a clean build report and also post a response to the comments issued by @mtmorgan. 

If not, we are happy for you to continue development at a pace you are comfortable with, and it will go in the next devel cycle (which is perfectly fine). 

Another reminder, once a review is given, we give maintainers about 2 weeks to respond. Before we close the issue and it can be reopened once the maintainer has more time to proceed with active development of the package.

Best,

Nitesh

**Comment by trvinh** [comment]
Hi @nturaga 
I am still doing the revision according to comments of @mtmorgan but I am not sure if I can make it on time for the upcoming release. Whenever it is ready I will push the changes.
Best,
Vinh

**Comment by nturaga** [comment]
That sounds good. No need to rush the it.

Best,

Nitesh

**Comment by trvinh** [comment]
Hi @mtmorgan 

first of all thanks so much for your comments! I have made some minor changes according to your comments (details in https://github.com/BIONF/PhyloProfile/pull/99#issue-273019196). However I still need to work on improving the code efficiency (e.g. avoiding loop). I am new to R, therefore it takes me some time to understand how this concept works :-) And I will also revise the man pages as well. 

About your last comment, the files in `inst/PhyloProfile` are part of the package. It is the Shiny-based GUI version of the package.

According to your comment about hosting the data in both github and bioconductor: since Bioconductor requires a package size smaller than 5MB, I need to store the demo data somewhere else and they just need to be downloaded only when the user uses them. Those data are quite large (they are not used for testing the functions but for demonstrating biological use-cases). I will consider your suggestion to create an `ExperimentData package` to host them instead of using github.

Best regards,
Vinh

**Comment by nturaga** [comment]
Hi @trvinh 

Let me know once you are ready for another review. Highlighting the changes you've made according to mtmorgan's comments.

Best,

Nitesh

**Comment by trvinh** [comment]
Hi @nturaga ,
I am going to ask you one thing regarding to providing the data as an ExperimentData package (I have adapted the codes according to all comments of @mtmorgan, except that one). I am able to create a data package (not yet posted it into the bioconductor issues) and load the data into this PhyloProfile package. However, until the data package is available in bioconductor, some functions of PhyloProfile still depend on github (since the data package is hosting currently only in github).
So my question is, must I now submit the data package first, and after it has been accepted and can be installed from bioconductor, I can continue working on PhyloProfile package to remove the github dependency?
Many thanks for your declaration!
Best,
Vinh

**Comment by nturaga** [comment]
Hi @trvinh 

You should be able to follow this guide [here](https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html) for your question. 

But you must reach out to @lshep (Lori Shepherd) since it's important that your data is first accepted into the AWS S3 bucket. @lshep will guide you through this process.

Best,

Nitesh

**Comment by trvinh** [comment]
@nturaga Dear Nitesh, 
thanks for your instruction! I have the created the data package following the link you gave me and already mailed @lshep to ask about the access to AWS S3 (did not get the reply yet, I just wrote her last Friday).
I am preparing this package to be ready for using the data from the upcoming data package. 
I will get back to you whenever it is ready for the next review :-)
Best,
Vinh

**Comment by trvinh** [comment]
AdditionalPackage: https://github.com/BIONF/PhyloProfileData

**Comment by trvinh** [comment]
Dear @nturaga and @mtmorgan ,
thanks to @lshep I have moved the data from experiment data from github to AWS S3 and created an Experiment data package for them (https://github.com/BIONF/PhyloProfileData).
I have revised the PhyloProfile package according to Martin's [comments](https://github.com/Bioconductor/Contributions/issues/1039#issuecomment-485022427). I think it is ready for the next review now.
Best,
Vinh

**Comment by lshep** [comment]
Hang tight the ABNORMAL is on our end.  We will manually kick off a build for you when it is fixed.  You should have a report within the next 10 min

**Comment by lshep** [comment]
Everything should be back to normal,  we are manually kicking off a build of your data package first to have it build on all three builders, and then we will manually kick off a build of your software package.  Once those post feel free to do version bumps as normal.

**Comment by trvinh** [comment]
Dear @nturaga and @lshep ,
just want to drop a quick note, that the package is ready for the next round of review :)
Best,
Vinh

**Comment by nturaga** [comment]
Ok. I will review in the next few days

**Comment by trvinh** [comment]
Many thanks in advance @nturaga ! :-)

**Comment by trvinh** [comment]
@nturaga Hi Nitesh, I don't want to bother you but I just want to ask how is the status of the review :-P

**Comment by nturaga** [comment]
# PhyloProfile review

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* Ok

## NAMESPACE

* ok

## NEWS

* Make sure the NEWS file is parsable by utils::news()

## vignette

* ok

## man

ok

## R

* One major issue is your package introduces a lot of dependencies,
  which i'm not conviced you need.
  
  Packages like `stringr`, have been used in core functions, very
  sparsely, and can easily be replaced by base R functions, just as
  easily.
  
  The same applies to `plyr` as well. You can use 
  
  It appears that there no consistency in the data manipulation.
  
* Validating arguments, instead of use `stop`, and provide a useful
  error message. This is more valuable to the user than, just
  returning whenever something is not correct.

	    if (is.null(profiles)) return()
		
	use, 
	
		if(is.null(profiles)) 
			stop("'profiles' is NULL, provide the correct value")
			
  Make these changes everywhere. You seem to want to use "return" as
  the only way to exit from a function, this is not the case. 

* Remove commented out code.

* Try not to have multiline functions declared within other
  functions. They get harder to debug as time passes. eg:
  `generatePlot()` is a lot of code to be embedded in another function
  varDistTaxPlot(). Keep them seperate, do this all across your code
  base.
  
* This one NOTE is of value and makes sense to follow,

* Checking function lengths.

```
    * NOTE: Recommended function length <= 50 lines.
      There are 23 functions > 50 lines.
      The longest 5 functions are:
        heatmapPlotting() (R/createProfilePlot.R, line 174): 191 lines
        filterProfileData() (R/parsePhyloProfile.R, line 702): 168
      lines
        estimateGeneAge() (R/estimateGeneAge.R, line 37): 150 lines
        varDistTaxPlot() (R/compareTaxaGroups.R, line 329): 139 lines
        createArchiPlot() (R/createDomainPlot.R, line 37): 133 lines
```

**Comment by trvinh** [comment]
@nturaga Hi Nitesh, the 2-weeks deadline is almost over but I want to leave a short note here, so that you know that I am still working on the revision :-) I will let you know when everything is ready for the next review.
Best,
Vinh

**Comment by nturaga** [comment]
Perfect. Keep working. No issues.

**Comment by nturaga** [comment]
Hi @trvinh 

Just leaving a message hoping you are still working on the package. If it takes more time, it is really best to close the issue and reopen the issue. The builder still works and you can keep updating your version number for a "closed" issue as well.

This will help us better gauge the number of active packages we have to review as reviewers. If it takes longer please close the issue and reopen. 

Best,

Nitesh

**Comment by trvinh** [comment]
Hi @nturaga, 
The package is still alive and active :-) I am just on vacation right now. Next week I will push some changes to build a new version. I hope that it will be ok not to close this issue.
Best,
Vinh

**Comment by trvinh** [comment]
@nturaga 
Hi Nitesh,
I have revised the package based on your comments. I reduced the number of required packages stated in the DESCRIPTION file, as well as the length of several functions. However there are still 6 long functions which I cannot solve (it is not possible to split into multiple smaller functions). The NEWS file works with news() function in R terminal but not in RStudio, I read that it was RStudio‘s issue. 
I think it is ready for the next review. I am waiting for the new comments :-)
Best,
Vinh

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/trvinh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PhyloProfile")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PhyloProfile

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/trvinh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PhyloProfileData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PhyloProfileData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
