### ISSUE TITLE
celda

### ISSUE THREAD

**Issue by zhewa** [Bioconductor/Contributions#1041]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/campbio/celda

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

This is a re-submission of the package **celda**. The original submission is here: #910

**Comment by zhewa** [comment]
Hi @Kayla-Morrell 
I think our package celda is now passing the BiocCheck with minimal warning and notes and is ready for your review. The only warning in the latest build report is the use of `set.seed`:
``` 
* WARNING: Remove set.seed usage in R code
  Found in R/ directory functions:
    .setSeed()
```
As mentioned in our [previous submission](https://github.com/Bioconductor/Contributions/issues/910), this is a feature we would like to include in our package. We employed a strategy that "We could allow the user to set the ‘seed’ argument to NULL and then the calls to ‘set.seed()’ will be bypassed with ‘if’ statements." Please let us know if you have any suggestions.

Thank you,
Zhe

**Comment by Kayla-Morrell** [comment]
Hi @zhewa,

We require that `set.seed()` not be included inside functions. The user should set the seed outside the function if they choose to do so. Please make the necessary changes. 

Best,
Kayla

**Comment by zhewa** [comment]
Hi @Kayla-Morrell 

Sorry, I think I did not make myself clear. A major reason why we use `set.seed()` in our package is we want to maintain reproducibility. The more detailed explanation is here: https://github.com/Bioconductor/Contributions/issues/910#issuecomment-433493355. We would really appreciate it if you can read through it and take a look at the issue from our point of view. 

Also, in this comment https://github.com/Bioconductor/Contributions/issues/910#issuecomment-433964386, @dvantwisk already approved our solution to the use of `set.seed()` in our package.  Is this no longer an option anymore? If not, we might need to re-evaluate our options.

Thank you,
Zhe

**Comment by Kayla-Morrell** [comment]
Hi @zhewa,

I have read over the previous discussion and understand your concerns. However, after talking over this issue with @mtmorgan and my other colleagues, the `set.seed()` feature you have within your function is not acceptable. Please make the necessary changes.

Best,
Kayla

**Comment by zhewa** [comment]
Hi @Kayla-Morrell 

Thank you for taking the time to read over the previous discussion. We gave some more thoughts about the use of `set.seed()` and decided to remove them from our package. Please let us know if any more changes are needed.

Thank you

**Comment by Kayla-Morrell** [comment]
@zhewa - Thank you for the changes made. I do need to do a proper review of your package which is done once a clean build is produced, however you keep making changes/improvements. Please let me know when you have finished making changes so I may begin the review and get comments back to you.

Best,
Kayla

**Comment by zhewa** [comment]
Hi @Kayla-Morrell  
I have finished making the changes. Sorry about the constant changes. The last few changes are to fix the use of `sapply()` and `1:n`.

**Comment by Kayla-Morrell** [comment]
Hello @zhewa,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. Comment back here with updates that have been made and when the package is ready for a secondary review.

# General Package Development #

*R CMD check*

- [ ] Recommend fixing the missing or unexported object 'stats::mean' NOTE.

*R CMD BiocCheck*

- [ ] Recommend fixing the runnable examples to man pages that document exported objects 'availableModels.Rd', 'celda.Rd', 'semiPheatmap.Rd' NOTE.

- [ ] Recommend checking to make sure 'dontrun{}/donttest{}' sections are tested some where either in another example or in the vignettes. They are in 'featureModuleTable.Rd', 'plotDimReduceCluster.Rd', 'plotDimReduceFeature.Rd', 'plotDimReduceGrid.Rd', 'plotDimReduceModule.Rd' NOTE.

- [ ] Recommend fixing shorter lines NOTE. There are 63 lines that are > 80 characters long.

- [ ] Recommend fixing multiples of 4 spaces for line indents NOTE. There are 397 lines that are not.

# DESCRIPTION #

- [ ] REQUIRED: There are 13 packages listed as 'Imports:' that are not listed in your NAMESPACE file.

# NAMESPACE #

- [ ] REQUIRED: Exported functions should use camel case or underscoring and not include "." which indicates S3 dispatch.

- [ ] REQUIRED: Fix the import of 'gridExtra', you have both `import(gridExtra)` and `import(gridExtra, except = c(combine))`.

- [ ] REQUIRED: We encourage `importFrom()` over importing an entire package if there are only a few functions used from the package. If there are many functions being used then `import()` is okay.

# data #

- [ ] REQUIRED: Need documentation (creation and source information).

# vignette #

*celda-analysis*

- [ ] REQUIRED: There needs to be consistancy with the naming of the package. All documentation (expect for in the vignette) 'celda' is with a lower case 'c'. In the vignette you start calling the package 'Celda' with a capital 'C'. Please be consistant.

- [ ] SUGGESTION: Break the 'Introduction' section into 'Introduction' and 'Installation'. Line 19 should start the 'Installation' section.

- [ ] REQUIRED: Whether you split into an 'Installation' section or keep as is, you should show how the user can download the package from _Bioconductor_ and then load the library.

- [ ] SUGGESTION: Line 31, I would also add some text about how the user can go to the _Bioconductor_ support site to ask questions using the tag 'celda'.

- [ ] REQUIRED: Line 33-37, this chunk is not needed since it is already run at line 21-23.

- [ ] REQUIRED: Line 149, this does not render as a section heading. I think this is because you need a line between the plot code (ending at line 148) and the heading (line 149).

- [ ] REQUIRED: Line 151, end this section with a '.' not a ':'.

- [ ] REQRUIED: Line 181, this is also not showing as a heading. There needs to be an empty line between the end of the code chunk (line 180) and the heading (line 181).

- [ ] REQUIRED: Line 183, 'moduleHeatmap' needs to be formated correctly with \` \`.

- [ ] REQUIRED: Line 207, this is not showing as a heading. There needs to be an empty line between the end of the code chunk (line 206) and the heading (line 207).

- [ ] REQUIRED: Line 213-215, this chunk is not needed because the library is listed under 'Imports' for the package. Also, it is pointless to have if the user can't see it.

- [ ] REQUIRED: Line 239, this sentence should end with '.' not ':'.

- [ ] REQUIRED: Line 259, there should be a space in between 'K' and '(' as well as between 'L' and '('.

- [ ] REQUIRED: The vignette should end with a 'Session Info' section that includes `SessionInfo()`.

*DecontX-analysis*

- [ ] REQUIRED: There needs to be consistency with the naming of 'celda' (just like with the first vignette).

- [ ] SUGGESTION: Like the first vignette, break the 'Introduction' section into 'Introduction' and 'Installation'. Line 23 should start the 'Installation' section.

- [ ] REQUIRED: Like the first vignette, whether you splity inton an 'Installation' section or keep as is you should show how the user can download the package from _Bioconductor_ and then load the library.

- [ ] SUGGESTION: Like the first vignette, line 26 could also have some text about how the user can go to the _Bioconductor_ support site to ask questions using the tag 'celda'.

- [ ] REQUIRED: Line 46, I produce a different output when I run this code. My `table(simCounts$z)` results in 38, 31, 31 respectively. Should there be a `set.seed()` before running the code similar to how you had it in the first vignette?

- [ ] REQUIRED: The vignette should end with a 'Session Info()' section that includes `SessionInfo()`.

# man pages #

- [ ] REQUIRED: Since you have the packages listed as 'Imports' in your description file, you don't have to load them in examples.

# tests #

- [ ] REQUIRED: Nothing is being tested in 'test-recursiveSplit.R', either uncomment some of the code so it's actually tested or remove the file.

# R code #

- [ ] REQUIRED: Avoid the use of direct slot access with '@', accessor methods should be created and used instead.

- [ ] REQUIRED: Use various apply functions (we prefer vapply) instead of `for` loops.

Best,
Kayla

**Comment by zhewa** [comment]
Hi @Kayla-Morrell ,

Thank you so much for taking the time to review our package **celda**. Please see below for the updates to the package. I think our package is ready for a secondary review. Please let us know if any more changes are needed.

Thank you,
Zhe

# General Package Development #

*R CMD check*

- [x] Recommend fixing the missing or unexported object 'stats::mean' NOTE.
**We removed `stats::` in `elbow.R`**

*R CMD BiocCheck*

- [x] Recommend fixing the runnable examples to man pages that document exported objects 'availableModels.Rd', 'celda.Rd', 'semiPheatmap.Rd' NOTE.
**We moved the definition of 'availableModels' to `data.R`. We added examples to 'availableModels.Rd' and 'celda.Rd'. We removed the export of `semiPheatmap` function.**

- [x] Recommend checking to make sure 'dontrun{}/donttest{}' sections are tested some where either in another example or in the vignettes. They are in 'featureModuleTable.Rd', 'plotDimReduceCluster.Rd', 'plotDimReduceFeature.Rd', 'plotDimReduceGrid.Rd', 'plotDimReduceModule.Rd' NOTE.
**We removed `donttest{}`.**

- [x] Recommend fixing shorter lines NOTE. There are 63 lines that are > 80 characters long.
**These lines are within the file `RcppExports.R` which are automatically generated by `Rcpp` package.**

- [x] Recommend fixing multiples of 4 spaces for line indents NOTE. There are 397 lines that are not.
**Most of these lines are within documentation files which are automatically generated by `roxygen2`.**

# DESCRIPTION #

- [x] REQUIRED: There are 13 packages listed as 'Imports:' that are not listed in your NAMESPACE file.
**We have added them to NAMESPACE file.**

# NAMESPACE #

- [x] REQUIRED: Exported functions should use camel case or underscoring and not include "." which indicates S3 dispatch.
**We have renamed the function names.**

- [x] REQUIRED: Fix the import of 'gridExtra', you have both `import(gridExtra)` and `import(gridExtra, except = c(combine))`.
**We removed `import(gridExtra)`.**

- [x] REQUIRED: We encourage `importFrom()` over importing an entire package if there are only a few functions used from the package. If there are many functions being used then `import()` is okay.
**We changed how we import a few packages and used `importFrom()` if only a few functions are used from the imported package.**

# data #

- [x] REQUIRED: Need documentation (creation and source information).
**We have examples in the documentation of these objects showing how they are generated. Is there any other documentation we need to add?**

# vignette #

*celda-analysis*

- [x] REQUIRED: There needs to be consistancy with the naming of the package. All documentation (expect for in the vignette) 'celda' is with a lower case 'c'. In the vignette you start calling the package 'Celda' with a capital 'C'. Please be consistant.

- [x] SUGGESTION: Break the 'Introduction' section into 'Introduction' and 'Installation'. Line 19 should start the 'Installation' section.

- [x] REQUIRED: Whether you split into an 'Installation' section or keep as is, you should show how the user can download the package from _Bioconductor_ and then load the library.

- [x] SUGGESTION: Line 31, I would also add some text about how the user can go to the _Bioconductor_ support site to ask questions using the tag 'celda'.

- [x] REQUIRED: Line 33-37, this chunk is not needed since it is already run at line 21-23.

- [x] REQUIRED: Line 149, this does not render as a section heading. I think this is because you need a line between the plot code (ending at line 148) and the heading (line 149).

- [x] REQUIRED: Line 151, end this section with a '.' not a ':'.

- [x] REQRUIED: Line 181, this is also not showing as a heading. There needs to be an empty line between the end of the code chunk (line 180) and the heading (line 181).

- [x] REQUIRED: Line 183, 'moduleHeatmap' needs to be formated correctly with \` \`.

- [x] REQUIRED: Line 207, this is not showing as a heading. There needs to be an empty line between the end of the code chunk (line 206) and the heading (line 207).

- [x] REQUIRED: Line 213-215, this chunk is not needed because the library is listed under 'Imports' for the package. Also, it is pointless to have if the user can't see it.

- [x] REQUIRED: Line 239, this sentence should end with '.' not ':'.

- [x] REQUIRED: Line 259, there should be a space in between 'K' and '(' as well as between 'L' and '('.

- [x] REQUIRED: The vignette should end with a 'Session Info' section that includes `SessionInfo()`.

*DecontX-analysis*

- [x] REQUIRED: There needs to be consistency with the naming of 'celda' (just like with the first vignette).

- [x] SUGGESTION: Like the first vignette, break the 'Introduction' section into 'Introduction' and 'Installation'. Line 23 should start the 'Installation' section.

- [x] REQUIRED: Like the first vignette, whether you splity inton an 'Installation' section or keep as is you should show how the user can download the package from _Bioconductor_ and then load the library.

- [x] SUGGESTION: Like the first vignette, line 26 could also have some text about how the user can go to the _Bioconductor_ support site to ask questions using the tag 'celda'.

- [x] REQUIRED: Line 46, I produce a different output when I run this code. My `table(simCounts$z)` results in 38, 31, 31 respectively. Should there be a `set.seed()` before running the code similar to how you had it in the first vignette?

- [x] REQUIRED: The vignette should end with a 'Session Info()' section that includes `SessionInfo()`.

# man pages #

- [x] REQUIRED: Since you have the packages listed as 'Imports' in your description file, you don't have to load them in examples.
**We removed `library(SummarizedExperiment)` in the example codes of `differentialExpression`.**

# tests #

- [x] REQUIRED: Nothing is being tested in 'test-recursiveSplit.R', either uncomment some of the code so it's actually tested or remove the file.
**We removed 'test-recursiveSplit.R'.**

# R code #

- [x] REQUIRED: Avoid the use of direct slot access with '@', accessor methods should be created and used instead.
**We have replaced `@` with S4 getters for slot access.**

- [x] REQUIRED: Use various apply functions (we prefer vapply) instead of `for` loops.
**We use 18 `vapply`, 13 `lapply` and 10 `apply` functions within the `celda` package. 57 `for` loops are used. We are aware of the advantage of using `vapply`, `lapply` and `apply` functions over `for` loops. However, there are some cases where we think using `*apply` functions instead of `for` loop will not result in a huge improvements in efficiency but instead hinders the readability of the codes. Is it a hard limit that no `for` loops can be used for R packages on Bioconductor?**

**Comment by Kayla-Morrell** [comment]
Hello @zhewa,

Thank you for all the work done on this package. I have looked over the changes made and have just a couple additional notes before accepting your package. See the secondary review below and comment back here when you are ready for me to look it over again.

# General package development #

- [ ] REQUIRED: Thank you for adding/fixing the runnable examples in the man pages. There are no examples for the man pages 'celdaGridSearch', 'plotDimReduceCluster', 'plotDimReduceFeature', and 'plotDimReduceModule'. Since they are demonstrated in the vignette, it is acceptable to have the examples as 'dontrun{}/donttest{}'.

- [ ] REQUIRED: The man page 'plotDimReduceGrid' does not have any examples in it. This function is not demonstrated in the vignette, so there should be runnable examples in this man page.

# data #

I'm sorry, this was a note to myself to check to make sure there was documentation. I should have not included this in the review, what you have is just fine.

# R code #

We do not require that there be absolutely no for loops in code, we just want to be sure the code is as efficient, robust, and fast as possible. Our main concern when dealing with for loops is to be sure you vectorize instead of iterate. If iteration is necessary than we want to be sure you 'pre-allocate and fill' rather than copy-and-append. See our common advice here: https://bioconductor.org/developers/how-to/efficient-code/. If your code seems to follow this advice than you can leave your code as is.

Best,
Kayla

**Comment by zhewa** [comment]
Hi @Kayla-Morrell 

Thank you for the feedback on the second review. Please see below for changes made.


# General package development #

- [x] REQUIRED: Thank you for adding/fixing the runnable examples in the man pages. There are no examples for the man pages 'celdaGridSearch', 'plotDimReduceCluster', 'plotDimReduceFeature', and 'plotDimReduceModule'. Since they are demonstrated in the vignette, it is acceptable to have the examples as 'dontrun{}/donttest{}'.
**We added `donttest{}` examples to these functions.**

- [x] REQUIRED: The man page 'plotDimReduceGrid' does not have any examples in it. This function is not demonstrated in the vignette, so there should be runnable examples in this man page.
**We added a runnable example to 'plotDimReduceGrid'.**

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhewa.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("celda")`. The package 'landing page' will be created at

https://bioconductor.org/packages/celda

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
