### ISSUE TITLE
scGPS - Single Cell Global fate Potential of Subpopulations

### ISSUE THREAD

**Issue by quanaibn** [Bioconductor/Contributions#1042]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/IMB-Computational-Genomics-Lab/scGPS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 
Thank you for your submission. 
Please resolve the package errors in the report. 

Best regards,
Marcel

**Comment by quanaibn** [comment]
Hi Marcel Ramos,

Finally the package has passed all the build requirements. Could you please advise what do I need to do next? 

Thanks very much for your help and I look forward to your response. 

Best wishes,

Quan

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 
Thank you for your submission to Bioconductor. 
Please see the review below. 

Add comments in this thread if you have any questions. 

Best regards,
Marcel

---

# scGPS #1042

* Overall, the maintainer has put a lot of work into the package but there
is much room for improvement in terms of following standard coding practices
as outlined on the Bioconductor website. Please make use of those resources.

## DESCRIPTION

* Fix the formating to fit the 80 column width

## NAMESPACE

* Remove the export pattern from the NAMESPACE
* Use consistent function naming schemes either snake_case or camelCase, try
to avoid using both
* Functions like `NewscGPS` appear confusing based on the name alone
* Every function does not need to include a `_scGPS` suffix

## vignettes

* Please fix the installation instructions, they should only require
`devtools::install` and a `library(scGPS)` call. `devtools::document` should
only be used to update the documentation pages and `devtools::load_all()` is
not the right way to load the package
* It may be better to include figures in the `inst/resources` folder, for
example
* Keep R code and git code in separate chunks
* Do not include unevaluated code in the vignette. This code can become stale
quickly without constant evaluation
* Add a `sessionInfo` chunk to the vignette

## R

* Follow the guidelines on the Bioconductor website:
https://www.bioconductor.org/developers/package-guidelines/#rcode
* Avoid the copy and append method, i.e., `X <- vector(); X[i] <- y`:
https://www.bioconductor.org/developers/how-to/efficient-code/
* Use `message` instead of `print` within functions
* Pass inputs such as `scaling` to the `stats::prcomp` function rather than
using a condition `scaling == TRUE` (See minor point below)
* Remove any commented code `CIDR` or provide a working alternative
* Use `SummarizedExperiment` inputs where possible especially for expression
matrix arguments
* Where possible, reference by name values not index. For example,
`mtcars[["mpg"]]` is preferred over `mtcars[[1]]`
* Avoid printing too many messages, use a `verbose` argument in your functions
* What is the reasoning for `add_import` rather than using `NULL`?

Minor:
* Evaluate `if` conditions without redundancy `if (LDA_run)` is preferred over
`if (LDA_run == TRUE)` and `!is.matrix(x)` over `is.matrix(x) == FALSE`

## data

* Use a more descriptive names than `sample1`, `sample2`, and `GeneList` if
possible

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 

Any updates on the package status? 
Do you intend to work on the package? 

Thanks for letting us know. 

Best,
Marcel

**Comment by quanaibn** [comment]
Hi Marcel,
Yes, we will work on the package. It was a hectic few weeks for us to work
on grant applications. Do we have a chance to meet the Bioconductor release
deadline?
Many thanks!
Quam

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 

The deadline to get reviewed packages into the next release
was April 24 (as on the website):

## Wednesday April 24
* No API changes to Bioc 3.9.
* Deadline to add new packages to the BiocC 3.9 manifest.

You can still submit your package to the devel branch of Bioconductor. 

Best regards,
Marcel

**Comment by quanaibn** [comment]
Hi Marcel,
That's ok, we'll aim for the next release. We will start addressing your
comments from next week after submitting the grants.
Thanks very much!
Quan

**Comment by quanaibn** [comment]
Hi Marcel,

We are working on addressing all of your comments. We will have the revised version ready on Friday. Could you advise us how to address your comments below and still keep the compilation file under 5 minutes:

1) "Do not include unevaluated code in the vignette. This code can become stale
quickly without constant evaluation" -> Our full vignette will make the compilation time exceeds 5 minutes, so we commented out some codes to save the compilation time. Do you have advice about a better option?

Many thanks!

Quan

**Comment by quanaibn** [comment]
Hi Marcel,

We've attempted to address most of your comments. The new version has been updated.  

There are 4 items that we haven't completely addressed yet. Could you let us know if we need to address them further: 
- The vignette stuff we sent the message about already -> if we include all evaluations, the compiling time becomes more than 5 minutes
- Choosing which long messages to cut shorter -> we've tried. Most messages are useful for users to monitor the run. We can cut shorter if you think necessary.
- Use Summarized Experiment where possible -> we've tried
- inst/resources folder -> this folder is not generated by pkgdown

Hope to hear from you soon,

Best wishes,

Quan

**Comment by quanaibn** [comment]
Hi Marcel,

We are waiting for your responses to complete our submission. Could you please comment on the current version?

Many thanks,

Quan

**Comment by quanaibn** [comment]
Hi Marcel,

If you are busy and unable to comment. Could you please suggest another curator at Bioconductor? Thanks!

Quan

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 
Apologies for the delay. I was traveling last week. 
I will respond to your questions. 
Briefly, you can go over the 5 minute limit without problems. 
I will have another look at your package soon. 

Best, 
Marcel

**Comment by quanaibn** [comment]
Hi Marcel,

Thanks very much!

We're aiming to submit a manuscript based on the scGPS package by mid-July.
We can continue to work on it after we have received your feedback.

Best wishes,

Quan

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 

Please clean up the package. There are a lot of files that should not
be there even if you're using `pkgdown` (including `_pkgdown.yml`,
logo, `scGPS.md`, etc.). You should build your `pkgdown`
website independently of the GitHub repository. 

* Avoid using `1:x` sequence generation. It is not robust. Please see:
http://bioconductor.org/developers/package-guidelines/#rcode
* I think your users would appreciate an argument such as `verbose = FALSE`
at the main function level. 

Best, 
Marcel

**Comment by quanaibn** [comment]
Thanks Marcel,

We are revising the package to address your comments. We will try to submit
the revised package by the middle of next week.

Best regards,

Quan

**Comment by quanaibn** [comment]
Dear Marcel,

We have done with all revision of the package to address your comments. 

In addition, we also created a github html user's instruction file, in here: https://imb-computational-genomics-lab.github.io/scGPS/articles/vignette.html

I hope you could have time to finalise our package soon.  

Many thanks,

Quan

**Comment by LiNk-NY** [comment]
Hi Quan, @quanaibn 
Thank you for making those changes. 
It looks good! Your package has been accepted. 
Thank you for your contribution. 
Best,
Marcel

**Comment by quanaibn** [comment]
Hi Marcel,
Fantastic! Thanks very much for your very valuable comments and help and we hope to contribute more packages in the future.
Best wishes,
Quan

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/quanaibn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scGPS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scGPS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
