### ISSUE TITLE
TPP2D

### ISSUE THREAD

**Issue by nkurzaw** [Bioconductor/Contributions#1043]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nkurzaw/TPP2D

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi @nkurzaw , 

Thank you for submitting your package to Bioconductor. An initial review will be given hopefully within 2 weeks. 

Best,
Qian

**Comment by nkurzaw** [comment]
Great, thanks!

Best,
Nils

**Comment by Liubuntu** [comment]
HI @nkurzaw , 

Sorry for the delay of reviewing. I'm working on it right now will be get back to you very soon!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @nkurzaw , 

Please see below for the initial review. Generally your package was really well written. There are only some minor issues. Please try to fix all or most of them, and comment back with any questions or explanations. 

Cheers,
Qian

## DESCRIPTION
- `LazyData:` field: For packages that include data, we recommend not
  including LazyData: TRUE. This rarely proves to be a good thing. In
  our experience it only slows down the loading of packages with large
  data.
- `biocViews:` field: REQUIRED! Specify at least two [biocViews
  categories](https://bioconductor.org/packages/release/BiocViews.html). Multiple
  terms are encouraged but terms must come from the same package type
  (Software, AnnotationData, ExperimentData, Workflow).
- `BugReports:` field: It is encouraged to include the relevant links
  to Github for reporting Issues.
- `URL:` field: This field directs users to source code repositories,
  additional help resources, etc; details are provided in “Writing R
  Extensions”, RShowDoc("R-exts").

## NAMESPACE
- Looks good!

## NEWS
- Looks good!

## R/

- import_func.R:L170, L219, `if(length(xxx) > 0)` could be simplified
  as `if(length(xxx))`.
- remove commented code chunks in R scripts (could retain those for
  note purposes).

coding styles (SUGGESTION):
- be consistent and use ` <- ` for variable assignment. (there are
  mixture of `<-` and `=`).
- Prefix non-exported functions with a `.`. See
  [here](https://www.bioconductor.org/developers/how-to/coding-style/)
  for coding styles.

## man/

- SUGGESTION: put all data documentations into one `.Rd` file. This
  could be easily achieved by adding `@rdname data` above each `NULL`
  of the data. But note that by sharing one `.Rd` file (realized by
  adding `@rdname data` for each data documentation), some duplicate
  fields should be removed, e.g., only keep one `name` (value could be
  "data"), one `docType`, one `title` (value could be "Example
  datasets for TPP2D package"). For `description` and `format`, add
  the data name before each section, so after combination, users could
  still tell which paragraph corresponds to which dataset.
- Required: Add `@examples` for the data documentation.
```
@title Example datasets for TPP2D package
@name TPP2D datasets
@docType data
@rdname data
@description \code{simulated_cell_extract_df: } Simulated example dataset ...
@format \code{simulated_cell_extract_df: } data frame with columns ...
@examples
  data(simulated_cell_extract_df)
NULL

@rdname data
@description \code{raw_dat_list: } Simulated example dataset obtained by ...
@format \code{raw_dat_list: } list of data frames with ...
@examples
  data(raw_dat_list)
NULL

## repeat the 2nd chunk for other data documentations
```
- computeFdr.Rd:L19, typo for "obsevations" should be "observations".
- SUGGESTION: You can also combine the documentation for fdr related
  functions (findHits, computeFdr) into one `.Rd` file, using the same
  trick as I suggested above, so that it's more convenient for users
  with the help page.

## vignette
- Suggestion: Use the name of `TPP2D.Rmd` instead of
  `introduction.Rmd` so that it's more intuitive for users to use
  `browseVignette("TPP2D")`.
- For the section of "Installation" to show to users how to install
  the package as if it has been included in Bioconductor. Because new
  packages is going to be in Bioc devel, they are required to use
  `BiocManager` instead of `BiocInstaller` for downloading the
  package. NOTE that the
  `BiocManager::install(“githubUserName/pkgname”)` works as
  `devtools::install_github("../..")`. You should include something
  like this:
```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```

## unit tests

- By running `devtools::test()`, There were 72 warnings. Consider
  using `testthat::expect_warning()` if those are expected. Or check
  your tests if not.

**Comment by nkurzaw** [comment]
Hi @Liubuntu,

thanks a lot for the comments. 
I will try to address them as soon as possible.

Cheers,
Nils

**Comment by nkurzaw** [comment]
Hi @Liubuntu,
I tried to address all points you raised:

# Description 
* LazyData is now set to "false"
* it now contains the following biocViews: "Software, Proteomics, DataImport"
* URL and BugReports now link to my GitHub repository where I plan to handle issues, bug reports and news on the development version

# R/
* I simplified the code chunk that you have pointed out
* all instances of variable assignment with "=" I could find have been changed to "<–"
* internal functions are now pre-fixed with "."

# man
* I have added examples for all example datasets
* the typo you pointed out is now fixed 
* however when trying to generate the joint data documentation for the datasets and also for the fdr functions I ran into troubles when trying to generate the respective markdown files using roxygen so I have kept the old version for now

# vignette
* I have renamed the vignette to TPP2D.Rmd
* the installation instruction have been changed to your suggestion using BiocManager

# unit tests
* the test you mentioned does not generate any warnings anymore


Thanks a lot again for taking the time to look at my package and for considering it for Bioconductor!

Cheers,
Nils

**Comment by nkurzaw** [comment]
Hi @Liubuntu,

I just realised that I forgot to rename a set of internal functions to start with "." . I'm doing it right now and will let you know once I'm ready!

Sorry for that!

Cheers,
Nils

**Comment by nkurzaw** [comment]
Hi @Liubuntu,
ok, this has now been done!
Cheers,
Nils

**Comment by Liubuntu** [comment]
Hi @nkurzaw ,

Please see below for some additional comments: 

## R/
- data.R: Use the data name instead of `NULL` in the
body. Refer [here](http://r-pkgs.had.co.nz/data.html#documenting-data)
for more details.  Also, the example for data could be only
`data(dataName)`. E.g.,

```
@title ...
@format ...
@example data("simulated_cell_extract_df")
"simulated_cell_extract_df"   ## instead of NULL here.

**Comment by Liubuntu** [comment]
HI @nkurzaw , 

Just a friendly reminder that the deadline for including new packages into Bioc new release will be Wednesday, April, 24th. Please make updates based on the above review (which are really minor with clear instructions) and we'll proceed to acceptance. 

Best, 
Qian

**Comment by nkurzaw** [comment]
Dear @Liubuntu ,

sorry for the delay, I have know included your additional comments.
Thanks for the great feedback!

Cheers,
Nils

**Comment by Liubuntu** [comment]
Hi @nkurzaw , 

Thanks for the updates. One minor issue: 

## R/data.R
- use `@examples` instead of `@example`. Otherwise, the `.Rd` file
  doesn't catch this entry.

Best,
Qian

**Comment by nkurzaw** [comment]
Hi @Liubuntu ,

this is also now done.
Thanks again!

Best,
Nils

**Comment by Liubuntu** [comment]
Hi @nkurzaw , 

Your package is now accepted! 

Cheers,
Qian

**Comment by nkurzaw** [comment]
Hi @Liubuntu ,

That's great news :)
Thanks a lot for the constructive feedback!

Best,
Nils

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nkurzaw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TPP2D")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TPP2D

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
