### ISSUE TITLE
infercnv

### ISSUE THREAD

**Issue by GeorgescuC** [Bioconductor/Contributions#1045]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/broadinstitute/infercnv

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by GeorgescuC** [comment]
Hi @dvantwisk ,

The last version of our package only has `WARNING: check time exceeded 5 min` returned in the build report. This is due to the examples provided to run certain methods taking a bit more time to run (mainly when tested on the i386 architecture). Is this a critical issue?

Best.

**Comment by dvantwisk** [comment]
Here is the review of your package. [REQUIRED] tags must be addressed while [CONSIDER] tags are advisable but not necessary. Please message me back when you are finished making changes so I can have another look.

GENERAL
- [ ] [REQUIRED] Your repository as its stands is 473MB in size. We generally
want to see repos of smaller than 5MB. First off, the `.git` directory is 400MB
in size. You likely committed some large files that you later deleted. To clean
this, please use BFG repo-cleaner: https://rtyley.github.io/bfg-repo-cleaner/.
The rest of the size seems to come from the `examples` directory. Is this
directory necessary or can it be decreased in size in any way?

R/GENERAL
- [ ] [REQUIRED] Use `seq_len()` or `seq_along()` instead of `1:...`. This is
slightly faster. It also avoids the unexpected case where `1:0` evaluates to
`1 0` You seem to use these at some places put it is best to use it throughout.

R/inferCNV_constants.R
- [ ] [REQUIRED] L4: This seems invasive to the user since it is expected that a
package will either have the default activity on error or the user themselves
will decide whether to modify what to do on error. Please remove this.

R/inferCNV_HMM.R
- [ ] [REQUIRED] L163-173: Inefficient copy-and-append pattern used here to
declare `sds` and `means`. Creating an empty vector and adding onto it
one-by-one is actually creating a new vector and copying all the data to it
each time. It is better to use `vapply()` to declare vectors to avoid this
pattern. It is even better to vectorize the code such that it avoids the looping
altogether:
```
sds <- vapply(seq_len(100), function(ncells) {
    vals <- replicate(nrounds, sample(expr_vals, size=ncells, replace=TRUE))
    means <- Matrix::rowMeans(vals)
    sd(means)
}, numeric(1))
```

R/inferCNV_heatmap.R
- [ ] [REQUIRED] L795-801,806-811: Use `vapply()` to avoid copy-and-append
pattern.

R/inferCNV_ops.R
- [ ] [REQUIRED] L13: When it comes to saving output_files, is it necessary to
save the RDS file? Can an option be given to the user to save the file? Also,
does the output_dir need to be `.`? Could the default be `tempfile()`?
- [ ] [REQUIRED] L1270-1282: Replace copy-and-append pattern.

vigenttes
- [ ] [REQUIRED] L72-77: Once the package is accepted to Bioconductor, it will
be availiable using `BiocManager::install('infercnv')`. Please include this in
the vignette and remove this `install.packages()` and github installation
instructions.

**Comment by dvantwisk** [comment]
Hi @GeorgescuC 

Just a reminder that April 24th is our last day to accept packages for the bioc3.9 release. Please make changes soon so that they can be reviewed in time.

**Comment by GeorgescuC** [comment]
Hi @dvantwisk ,

All the point you asked us to address in your review should now be fixed, with the exception of reducing the total size of the repo with BFG, for which I have sent a support request to GitHub as it appears to be a known issue that PRs need to be deleted by GitHub admins for the error I receive when trying to push the cleaning. I will finish the process as soon as I hear back from them.

With regards to using tempfile() rather than "." as default output path, we have now removed the default value entirely and ask the user to provide a path as the processing can be quiet computationally heavy, and we do not want the user's compute to go to waste by losing the outputs in a temporary folder. If no path is provided, the run() command will return an error message right away letting the user know they need to specify it.
It is also for similar reasons that we save as RDS files the results of our processing at different steps by default. If the user encounters an error at a late step, or decides to run the analysis with some different options enabled, they can quickly resume from right before the error occurred, or the different option changed the outcome of the processing. If you would still like us to disable that with this context, we will make the change. (There is currently an option to not use those saved files if the user has reason to believe they are incorrect for some reason)

Last, for the WARNINGS/TIMEOUT occurring on the latest build, the examples and code ran did not change in a meaningful way from the build that did not timeout ( https://github.com/Bioconductor/Contributions/issues/1045#issuecomment-485205638 ), as the changes only addressed the use of seq_len() and seq_along(). There was also no timeout on the Windows build. Could the long examples run time be an issue with the build system?

Regards,
Christophe.

**Comment by dvantwisk** [comment]
Have you heard back from github regarding the size issue? The changes you made so far look good, but ~500MB is very large. I'd like to see this issue fixed before we accept your package.

**Comment by GeorgescuC** [comment]
Hi @dvantwisk , 

Github support just finished removing the PRs so I could finish cleaning our repo with BFG a couple minutes ago. The size is now 16.81 MiB, is that good?

**Comment by GeorgescuC** [comment]
Small update, the repo is actually down to 10.50MiB now after removing branches that had some of the duplicate files left.

**Comment by dvantwisk** [comment]
I'm getting ~11MB and 15MB for the size of the whole repository. This is much better than the original ~500MB. Since the changes you made look good and package acceptance deadline is today, I'm going to accept the package now. If you are able to reduce the size of the package further later on, please do so.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GeorgescuC.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("infercnv")`. The package 'landing page' will be created at

https://bioconductor.org/packages/infercnv

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
