### ISSUE TITLE
mbkmeans

### ISSUE THREAD

**Issue by drisso** [Bioconductor/Contributions#1047]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/drisso/mbkmeans

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by drisso** [comment]
Tagging co-authors @YuweiNi45 @epurdom @stephaniehicks

**Comment by epurdom** [comment]
Due to an incorrect file remaining on github (.Rproj file). Have fixed and pushed to master.

**Comment by drisso** [comment]
Hi @hpages 

thanks in advance for reviewing the package! As far as I can tell, this is the only warning in the build:
`WARNING: R CMD check exceeded 5 min requirement`

and it happens only on windows. Can we safely ignore this?

**Comment by hpages** [comment]
Hi @drisso ,

Thanks for your submission.

It's hard for me to understand how `R CMD build` and `R CMD check` would take more than 7 and 13 min respectively on tokay2 (Windows) when they take only 1 and 2.5 min on malbec2 (Linux). It could be that most of the time is spent in the compilation, I'm not sure. In my experience compilation of C++ code is significantly slower than compilation of C code, and to make the matter even worse, on Windows everything needs to be compiled twice (once for the 64-bit arch and once for the 32-bit arch). If that's the case there is not much you can do about it. Note that we'll get much more details (e.g. timing of `R CMD INSTALL` and for all examples) on the nightly build report once the package gets accepted, so stay tuned.

Anyway I took a first look at mbkmeans and found a few problems that would require your attention. See below for the details.

H.

## Compilation warnings and errors

1. Compilation of the package generates many warnings and even an error for me (I'm on Ubuntu Ubuntu 16.04.5 LTS):
```
hpages@spectre:~$ R CMD INSTALL mbkmeans
* installing to library ‘/home/hpages/R/R-3.6.r76263/library’
* installing *source* package ‘mbkmeans’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/home/hpages/R/R-3.6.r76263/include" -DNDEBUG  -I"/home/hpages/R/R-3.6.r76263/library/Rcpp/include" -I"/home/hpages/R/R-3.6.r76263/library/RcppArmadillo/include" -I"/home/hpages/R/R-3.6.r76263/library/Rhdf5lib/include" -I"/home/hpages/R/R-3.6.r76263/library/beachmat/include" -I"/home/hpages/R/R-3.6.r76263/library/ClusterR/include" -I/usr/local/include  -fpic  -g -O2  -Wall -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/home/hpages/R/R-3.6.r76263/include" -DNDEBUG  -I"/home/hpages/R/R-3.6.r76263/library/Rcpp/include" -I"/home/hpages/R/R-3.6.r76263/library/RcppArmadillo/include" -I"/home/hpages/R/R-3.6.r76263/library/Rhdf5lib/include" -I"/home/hpages/R/R-3.6.r76263/library/beachmat/include" -I"/home/hpages/R/R-3.6.r76263/library/ClusterR/include" -I/usr/local/include  -fpic  -g -O2  -Wall -c mini_batch.cpp -o mini_batch.o
In file included from mini_batch.cpp:3:0:
/home/hpages/R/R-3.6.r76263/library/ClusterR/include/ClusterRHeader.h: In member function ‘arma::mat clustR::ClustHeader::KMEANS_arma(arma::mat&, int, int, bool, std::__cxx11::string, Rcpp::Nullable<Rcpp::Matrix<14> >, int)’:
/home/hpages/R/R-3.6.r76263/library/ClusterR/include/ClusterRHeader.h:837:14: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
         bool status;
              ^
/home/hpages/R/R-3.6.r76263/library/ClusterR/include/ClusterRHeader.h: In member function ‘Rcpp::List clustR::ClustHeader::GMM_arma(arma::mat&, int, std::__cxx11::string, std::__cxx11::string, int, int, bool, double, int)’:
/home/hpages/R/R-3.6.r76263/library/ClusterR/include/ClusterRHeader.h:1433:14: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
         bool status;
              ^
In file included from /home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/LIN_output.h:8:0,
                 from /home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/numeric_matrix.h:5,
                 from mini_batch.cpp:13:
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h: In instantiation of ‘beachmat::external_writer_base<T, V>::external_writer_base(size_t, size_t, const string&, const string&) [with T = double; V = Rcpp::Vector<14, Rcpp::PreserveStorage>; size_t = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:199:58:   required from ‘beachmat::external_lin_writer<T, V>::external_lin_writer(size_t, size_t, const string&, const string&) [with T = double; V = Rcpp::Vector<14, Rcpp::PreserveStorage>; size_t = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/LIN_output.h:154:105:   required from ‘beachmat::external_lin_output<T, V>::external_lin_output(size_t, size_t, const string&, const string&) [with T = double; V = Rcpp::Vector<14, Rcpp::PreserveStorage>; size_t = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/numeric_matrix.h:131:110:   required from here
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:22:22: warning: ‘beachmat::external_writer_base<double, Rcpp::Vector<14, Rcpp::PreserveStorage> >::pkg’ will be initialized after [-Wreorder]
     std::string cls, pkg;
                      ^
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:21:18: warning:   ‘beachmat::external_ptr beachmat::external_writer_base<double, Rcpp::Vector<14, Rcpp::PreserveStorage> >::ex’ [-Wreorder]
     external_ptr ex; 
                  ^
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:29:5: warning:   when initialized here [-Wreorder]
     external_writer_base(size_t nr, size_t nc, const std::string& Pkg, const std::string& Class) :
     ^
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h: In instantiation of ‘beachmat::external_writer_base<T, V>::external_writer_base(size_t, size_t, const string&, const string&) [with T = int; V = Rcpp::Vector<13>; size_t = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:199:58:   required from ‘beachmat::external_lin_writer<T, V>::external_lin_writer(size_t, size_t, const string&, const string&) [with T = int; V = Rcpp::Vector<13>; size_t = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/LIN_output.h:154:105:   required from ‘beachmat::external_lin_output<T, V>::external_lin_output(size_t, size_t, const string&, const string&) [with T = int; V = Rcpp::Vector<13>; size_t = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/integer_matrix.h:94:126:   required from here
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:22:22: warning: ‘beachmat::external_writer_base<int, Rcpp::Vector<13> >::pkg’ will be initialized after [-Wreorder]
     std::string cls, pkg;
                      ^
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:21:18: warning:   ‘beachmat::external_ptr beachmat::external_writer_base<int, Rcpp::Vector<13> >::ex’ [-Wreorder]
     external_ptr ex; 
                  ^
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/external_writer.h:29:5: warning:   when initialized here [-Wreorder]
     external_writer_base(size_t nr, size_t nc, const std::string& Pkg, const std::string& Class) :
     ^
In file included from /home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/LIN_output.h:7:0,
                 from /home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/numeric_matrix.h:5,
                 from mini_batch.cpp:13:
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/Csparse_writer.h: In instantiation of ‘Rcpp::RObject beachmat::Csparse_writer<T, V>::yield() [with T = double; V = Rcpp::Vector<14, Rcpp::PreserveStorage>; Rcpp::RObject = Rcpp::RObject_Impl<Rcpp::PreserveStorage>]’:
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/LIN_methods.h:163:25:   required from ‘Rcpp::RObject beachmat::general_lin_output<T, V, WTR>::yield() [with T = double; V = Rcpp::Vector<14, Rcpp::PreserveStorage>; WTR = beachmat::Csparse_writer<double, Rcpp::Vector<14, Rcpp::PreserveStorage> >; Rcpp::RObject = Rcpp::RObject_Impl<Rcpp::PreserveStorage>]’
mini_batch.cpp:672:1:   required from here
/home/hpages/R/R-3.6.r76263/library/beachmat/include/beachmat/output/Csparse_writer.h:268:15: warning: unused variable ‘RTYPE’ [-Wunused-variable]
     const int RTYPE=V().sexp_type();
               ^
Error: 'pkgconfig' is not an exported object from 'namespace:beachmat'
Execution halted
g++ -std=gnu++11 -shared -L/home/hpages/R/R-3.6.r76263/lib -L/usr/local/lib -o mbkmeans.so RcppExports.o mini_batch.o -L/home/hpages/R/R-3.6.r76263/lib -lR
Error: 'pkgconfig' is not an exported object from 'namespace:beachmat'
Execution halted
installing to /home/hpages/R/R-3.6.r76263/library/00LOCK-mbkmeans/00new/mbkmeans/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mbkmeans)
```
Interestingly, the compilation error is not fatal (1st time I see something like this). Are these expected? Do they need some attention? Unfortunately `R CMD check` doesn't report these things (and our Single Package Builder doesn't show the ouput of `R CMD INSTALL`).

## Reliability/accuracy of central function mbkmeans()

2. `mbkmeans()` does not work as expected on a Matrix derivative (from the Matrix package):
    ```
    library(Matrix)
    library(mbkmeans)
    set.seed(123)
    m0 <- matrix(rnorm(100), ncol=10)
    m1 <- as(m0, "sparseMatrix")
    mbkmeans(m1, clusters=3)
    # Error in t.default(x) : argument is not a matrix
    ```
    Importing `t` from the Matrix package should address this.

3. `mbkmeans()` returns a different result when called on an HDF5Matrix instance compared to an ordinary matrix or DelayedMatrix instance:
    ```
    library(HDF5Array)
    library(mbkmeans)
    set.seed(123)
    m0 <- matrix(rnorm(100), ncol=10)   # ordinary matrix
    M2 <- as(m0, "HDF5Matrix")          # HDF5Matrix instance
    M3 <- rbind(M2[1:5, ], M2[6:10, ])  # DelayedMatrix instance

    set.seed(123)
    res0 <- mbkmeans(m0, clusters=3)

    set.seed(123)
    res2 <- mbkmeans(M2, clusters=3)
    identical(res0, res2)
    # [1] FALSE

    set.seed(123)
    res3 <- mbkmeans(M3, clusters=3)
    identical(res0, res3)
    # [1] TRUE
    ```

4. Make sure to add some tests that cover the 2 situations above.

## Vignette

5. References are not clickable in rendered HTML vignette. Also the reference section is not separated from the body of the text: it has no header (e.g. References or Bibliography) and thus seems to belong to last section, "4. Comparison with k-means".

6. Don't tell your readers to install a Bioconductor package from GitHub. The proper way to install a Bioconductor package is explained here: https://bioconductor.org/install/ Either provide that link, or show the following code in your vignette:
    ```
    if (!requireNamespace("BiocManager"))
        install.packages("BiocManager")
    BiocManager::install("mbkmeans")
    ```
    Or both. Note that the above code should not get evaluated when the vignette gets built (e.g. with `R CMD build`) which means that `eval=FALSE` should be used in the opening line of the code chunk.

## Man pages

7. In `?mbkmeans` (Description section): "... with the dimensionality reduction results as input in in the reducedDim() slot." ("in" repeated)

## Code

8. Do not put curly brackets (`{` .. `}`) around the call to `standardGeneric()` in your `setGeneric()` statements. Because of the presence of the curly brackets your generic function is considered a non-standard generic, which is unnecessary here:
    ```
    > mbkmeans
    nonstandardGenericFunction for "mbkmeans" defined from package "mbkmeans"
    
    function (x, ...) 
    {
        standardGeneric("mbkmeans")
    }
    <bytecode: 0xe50a6b8>
    <environment: 0xe5241b0>
    Methods may be defined for arguments: x
    Use  showMethods("mbkmeans")  for currently available ones.
    ```

9. Always use `&&` instead of `&` to combine conditions in an `if` statement.

**Comment by drisso** [comment]
Thanks @hpages! I really appreciate your comments! 

We will address them and report back here.

**Comment by drisso** [comment]
Hi @hpages,

thanks again for your comments.

We addressed points 2, 5, 6, 7, 8, and 9 as these were straightforward fixes.

As for point 3, the behavior that you observed was due to a bug recently introduced in beachmat that was fixed in beachmat version 1.99.6. It was indeed a good suggestion to add unit tests to cover that situation and I did.

Point 1. When we submitted the package a couple of weeks ago, the only two warnings that we observed at installation were the two related to the status variable being defined and not used: these only occurred on windows, and are related to functions that we import from the ClusterR package, so not sure how we can fix them other than creating a pull request for the ClusterR package (which I plan to do).

The other warnings (and the two errors) were not present when we submitted, but are indeed present now on all systems. I'm not sure what is going on and I'm confused as well as to why they are not fatal. 
Since they appeared after Aaron converted beachmat to a header only library, I suspect that that's the cause of these warnings. 

I'm tagging @LTLA in the hope that he can help us interpret those warnings, which look like they are coming from beachmat? If not, I'd appreciate any guidance on how to remove them.

Finally, in the latest build I now see that R CMD check times out on linux, but not on windows or Mac. I'm not sure what's going on there.

**Comment by LTLA** [comment]
The `pkgconfig` error is because use of _beachmat_ no longer requires linking to a shared library, as discussed in LTLA/beachmat#16. Thus _beachmat_ does not export `pkgconfig` anymore.

The `RTYPE` warning has been resolved.

The compilation time is naturally longer because the compiler needs to do more work to process a header-only library. However, this should not have been too different to _beachmat_ v1, because there's so much templating in the C++ code across both versions. I am surprised that it takes so long to compile, though, unless you are using 100% of _beachmat_'s functionality. 

I'll point out that _batchelor_ also timed out once on Linux during submission; but this disappeared upon bump, and it doesn't seem to be a problem with _scran_, etc. on the actual BioC build system.

**Comment by drisso** [comment]
Thanks @LTLA !
@hpages, I believe we addressed all the issues, let us know if there's something else left for us to do!

The time issues solved theirselves so...

**Comment by hpages** [comment]
Excellent! Every thing looks ok now. Thanks for this new contribution!

**Comment by LTLA** [comment]
Just a reminder about Bioconductor/HDF5Array#15; until we resolve this in one manner or another, this will affect _mbkmeans_' performance on HDF5 matrix inputs.

**Comment by hpages** [comment]
Yep, I have this on my radar, sorry. Right now I'm kind of buried in pre-release madness.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/drisso.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mbkmeans")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mbkmeans

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
