### ISSUE TITLE
submitting scBFA package

### ISSUE THREAD

**Issue by RuoxinLi** [Bioconductor/Contributions#1054]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/quon-titative-biology/scBFA
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by RuoxinLi** [comment]
Hi, It seems my package already passed the windows and linux system check, but for OS system, it outputs the error: dependency copula is not available for package scBFA. Can you help me install it on it? Thanks!

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 
When checking the package, I get an error: 

```
> scData = CreateSeuratObject(raw.data = GeneExpr,project = "sc",min.cells = 0)
Error in CreateSeuratObject(raw.data = GeneExpr, project = "sc", min.cells = 0) : 
  unused argument (raw.data = GeneExpr)
Execution halted
```

Please fix this issue, it seems like the argument should be `counts`.

Best,
Marcel

**Comment by RuoxinLi** [comment]
Hi Marcel,

Thank you for pointing out, I think this is due to seurat's recent update. I will adjust my code accordingly ASAP.

Best
Rita

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 
Any updates on the status? 
Thanks, 
Marcel

**Comment by RuoxinLi** [comment]
Hi Marcel,

Sorry was focusing on the reviews of BFA main paper recently.

Will address it this weekend

Thanks for the reminder

Best

Rita

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 
Any updates on the status of the package? 
Thank you.
-Marcel

**Comment by RuoxinLi** [comment]
Hi Marcel, I am very sorry. We are busy on addressing the reviewers comments right now, but I will make updates within this week!

Sorry for the delay.

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 
It has been quite a while. Please provide any updates that you may have. 
Thank you,
Marcel

**Comment by RuoxinLi** [comment]
Hi Marcel, @LiNk-NY sorry for the late update, can we start again on the review process, I updated the new version I had so far.

Thank you.

Rita

**Comment by RuoxinLi** [comment]
Hi Marcel, @LiNk-NY, again I apologize for the delay of updating and we were too busy to address the reviewer's comments within given deadlines, so I missed your last comments.  Can we start the review process again?

Thank you.

Rita

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 
Did you push a version bump of the package? 
Thanks,
Marcel

**Comment by RuoxinLi** [comment]
Hi Marcel, @LiNk-NY
The version I pushed is 0.99.914

Thanks

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 

Thank you for your submission. Please see the
review below. 
If you have any questions, post them here in the thread.

Best,
Marcel 

---

# scBFA #1054

## DESCRIPTION

* You may want to depend on either `SummarizedExperiment` or
`SingleCellExperiment` for the access functions like `mcols`, `colData`, etc.

## NAMESPACE

* Looks neat

## vignettes

* You don't need to use an `envir` argument for loading the `data`. This might
confuse users. Keep it in the `.GlobalEnv`.

Minor:
* Use the standard R code chunk for installation instructions and use
`eval=FALSE`

## R

* Avoid using semicolons (`;`)
* You can avoid repetitive code by using the `[[<-` instead of `$` to replace
values programatically (see `R/BFA.R`)
* Avoid using `print` and use `message` instead
* Document all methods available for input to the `scbfa` function as the
`method` argument and `diagnose` function (`disperType`), you may also want to
create a vector of methods available and use `match.arg` in the body of the
function to match the first one by default
* Use `is`  or `is.*` derivatives to check class membership instead of
`class(x) == "xx"`. You can also create a helper function to extract the
data matrix from these classes (and a check and error message for unsupported
classes)
* Data documentation looks good (`R/data.R`)
* Why not return a standard Bioconductor object from `scNoiseSim`?

Minor:
* No need to evaluate `TRUE` twice: `if (modelEnv$updateCellcoef == TRUE)`.
Simply use `if (modelEnv$updateCellcoef)`
* Consistently use `<-` as assignment operator (optional)
* Use `identical` for scalar matching of strings, e.g.,
`identical(diagnose_feature, "dispersion")`

**Comment by RuoxinLi** [comment]
Thanks Marcel!

**Comment by RuoxinLi** [comment]
Hi Marcel, @LiNk-NY,
I corrected the scBFA R package based on your comments, however there are two points:
1. You can avoid repetitive code by using the [[<- instead of $ to replace
values programatically (see R/BFA.R)
The modification for this comment I made is replace:
modelEnv$AA <- param$AA
   modelEnv$ZZ <- param$ZZ
   modelEnv$beta <- param$beta
   modelEnv$gamma <- param$gamma
   modelEnv$UU <- matrix(param$UU,ncol = 1)
   modelEnv$VV = matrix(param$VV,ncol = 1)
to:
  for(vNames in c("AA","ZZ","beta","gamma")){
        modelEnv[[vNames]] = param[[vNames]]
    }
    for(Intercept in c("UU","VV")){
        modelEnv[[Intercept]] = matrix(param[[Intercept]],ncol = 1) 
    }
But there are other places, like in the initialization, the evaluation for every variable is different, so I keep it unchanged, is it ok?

2. Document all methods available for input to the scbfa function as the
method argument and diagnose function (disperType), you may also want to
create a vector of methods available and use match.arg in the body of the
function to match the first one by default

Do you mean document the internal function like neg_loglikelihood() , gradient()?
Or you mean document the parameter of scbfa like scData, numFactors, etc? Can you give me a simple example?

Thank you!

Best!

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 

> 1. You can avoid repetitive code by using the [[<- instead of $ to replace
>    values programatically (see R/BFA.R)
>    The modification for this comment I made is replace:
>    modelEnv$AA <- param$AA
>    modelEnv$ZZ <- param$ZZ
>    modelEnv$beta <- param$beta
>    modelEnv$gamma <- param$gamma
>    modelEnv$UU <- matrix(param$UU,ncol = 1)
>    modelEnv$VV = matrix(param$VV,ncol = 1)
>    to:
>    for(vNames in c("AA","ZZ","beta","gamma")){
>    modelEnv[[vNames]] = param[[vNames]]
>    }
>    for(Intercept in c("UU","VV")){
>    modelEnv[[Intercept]] = matrix(param[[Intercept]],ncol = 1)
>    }
>    But there are other places, like in the initialization, the evaluation for every variable is different, so I keep it unchanged, is it ok?

That's okay, thanks for making the change. 

> 2. Document all methods available for input to the scbfa function as the
>    method argument and diagnose function (disperType), you may also want to
>    create a vector of methods available and use match.arg in the body of the
>    function to match the first one by default
> 
> Do you mean document the internal function like neg_loglikelihood() , gradient()?
> Or you mean document the parameter of scbfa like scData, numFactors, etc? Can you give me a simple example?

This means that the diagnose function should look like: 
```r
diagnose <- function(scData,
    sampleInfo = NULL, disperType = c("Fitted", "Map", "GeneEst"),
    diagnose_feature="dispersion")
{
match.arg(disperType, c("Fitted", "Map", "GeneEst"))
...
}
```
So that your users can see all the possible inputs. I would also add an error message to `disperType` not supported. The same would apply to the `scbfa` function. 
Consider also matching case between the main function and the package name, i.e., `scBFA::scBFA`. 

Best,
Marcel

**Comment by RuoxinLi** [comment]
Hi Marcel, @LiNk-NY, I finished the changes based on your previous comments.

Thanks 

Best

Rita

**Comment by LiNk-NY** [comment]
Hi Rita, @RuoxinLi 
Thank you for your contribution. Your package has been accepted. 

As you continue to maintain your package please include the minor detail below:

* Add the list of possible inputs in the function arguments as provided in the example above. 
The argument should look like this: `disperType = c("Fitted", "Map", "GeneEst")`. 

Best regards, 
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/RuoxinLi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scBFA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scBFA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
