### ISSUE TITLE
dcanr

### ISSUE THREAD

**Issue by bhuvad** [Bioconductor/Contributions#1055]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DavisLaboratory/dcanr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by bhuvad** [comment]
AdditionalPackage: https://github.com/DavisLaboratory/SingscoreAMLMutations

**Comment by bhuvad** [comment]
Hi @Liubuntu,

I have submitted two packages and both have built without error or warnings, yet for some reason, the WARNING tag is assigned to this issue along with the OK tag. Is this supposed to happen or is this a bug?

Cheers,
Dharmesh

**Comment by Liubuntu** [comment]
Hi @bioc-issue-bot , 

Thanks for submitting your 2 packages. I have just manually removed the "WARNINGS" tag, so no worries about it. I'll work on the review and get back to you shortly. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @bhuvad , 

Not sure what updates introduced the `ERROR` in building on all 3 platforms again. Please correct the vignette and have it fixed, before I proceed with the initial review. Thanks!

Best,
Qian

**Comment by bhuvad** [comment]
Hi @Liubuntu 

I have made the required changes and it builds correctly now. The warnings flag is still persisting as before :). I also had a small query regarding these packages; are these packages likely to make it to the next release? (I will ensure I am quick to respond to your feedback). It's just that we are planning to follow the workflow package up with an F1000 research paper and it would be nice to have the package with it. I totally understand if its not likely as I was pretty late in submitting them.

Cheers,
Dharmesh

**Comment by Liubuntu** [comment]
Hi @bhuvad , 

Since your package was submitted before the deadline of April 5th, so we'll make all efforts to have it accepted based on instant updates. Time would be very limited but achievable, while not guaranteed. 

In case if we missed the release, your package would still be available in the bioc devel, and has official searchable webpage on bioconductor. Not sure if I answered your question. 
 
Best,
Qian

**Comment by bhuvad** [comment]
Hi @Liubuntu,

Yes that does, thanks for the prompt response!

Another question (sorry for so many, these are my first packages), other authors of the workflow package are currently reviewing it and we may need to make changes to the text. Would such changes hinder your review process? We will not be making any changes to the code itself at any point. We are also working on a Chinese translation of the vignette which will simply be a translation of the text so I will be adding that towards the end of next week. Please let me know if these would interrupt your review and if so, what measures I should take to avoid it. 

Thanks, 
Hopefully my last question :)
Dharmesh

**Comment by Liubuntu** [comment]
HI @bhuvad, 

Minor changes to the context of the workflow would not hinder the review process. But remember to make version bump if there is a major change (hierarchy, structure, additional of major contents, etc.) and comment under this issue so we can take a further look of those changes. 

You can also modify anytime after acceptance which is encouraged as part of the maintenance of your bioc package. Remember to update your NEWS file also for major updates. Refer [here](http://bioconductor.org/developers/package-guidelines/#news) for more details. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @bhuvad , 

Please see following for the initial review. The package was well developed and there are some minor issue. Please try to address those as much and soon as possible so we can proceed with the next review and for final acceptance. 

Cheers,
Qian

## DESCRIPTION
- `LazyData:` field: For packages that include data, we recommend not
  including LazyData: TRUE. This rarely proves to be a good thing. In
  our experience it only slows down the loading of packages with large
  data.

## NAMESPACE
- looks good!

## NEWS
- The current format is not correct. Please refer  [here](http://bioconductor.org/developers/package-guidelines/#news)  for how to format your NEWS file. Or take this one as an [example](https://github.com/Bioconductor/DelayedArray/blob/master/NEWS)

## unit tests
- Look good!

## R/
- `evalution_functions.R`: for setting argment values, you can use
```{R}
dcEvaluate <- function(truth.type = c('association', 'influence', 'direct'),...)
{
    truth.type <- match.arg(truth.type)
}
```
So users could provide an abbreviated name, e.g., "influ" and
`match.arg` will still return the correct argument of
`influence`. Also it get the benefit to return the `association` as
default if user does not provide any value for `truth.type`.
- Same trick could be applied to `getTrueNetwork` function in
  `simulation_accessors.R`.
- Also applies to `plotSimNetwork` function in `simulation_plot.R`.
- You can also use the same trick for the function of
  `cor.pairs(cor.method=)` in `inference_methods.R` and those utility
  functions.
- `inference_methods_generic.R`: L87:89. Since you already have set
  the default value for `dc.method = 'zscore'` when `dc.method` value
  was missing (not provided) by user, there is no need to check and
  reassign.  Remove L87:89 the function will still work. So does the
  `dcScore` methods for other signatures.

**Suggested:** Bioconductor [coding style](https://www.bioconductor.org/developers/how-to/coding-style/)
- Prefix non-exported functions with a ‘.’.
## man/
- `dcNetwork.md`: This code chunk `igraph::plot.igraph(ig)` was set as
  not run. But seems it didn't take much time running and returns an
  igraph. Was there any other reason? Because generally we don't
  encourage developers to add the `dontrun` tag for examples.

## vignette
- dcanr_vignette.Rmd: "Installation" section: show to users how to
  install the package as if it has been included in
  Bioconductor. Because new packages is going to be in Bioc devel,
  they are required to use `BiocManager` instead of `BiocInstaller`
  for downloading the package. You should include something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```

**Comment by bhuvad** [comment]
## DESCRIPTION

* LazyData: field: For packages that include data, we recommend not including LazyData: TRUE. This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large
data.

> This has been changed to false now

## NEWS

* The current format is not correct. Please refer here for how to format your NEWS file. Or take this one as an example

> I have corrected the format now and `utils::news(package = 'dcanr')` prints out the news in the correct format

## R/

* So users could provide an abbreviated name, e.g., "influ" and `match.arg` will still return the correct argument of influence. Also it get the benefit to return the association as default if user does not provide any value for `truth.type`

> This has been changed for all recommended functions. I wasn't aware of this function, it makes the code much neater! Thanks for pointing it out.

* `inference_methods_generic.R`: L87:89. Since you already have set the default value for `dc.method = 'zscore'` when `dc.method` value was missing (not provided) by user, there is no need to check and reassign. Remove L87:89 the function will still work. So does the `dcScore` methods for other signatures.

> Upon removing these lines, my unit tests failed. I am not sure why this is the case. I have reproduced the error on both windows and mac. The exact error is: `test_inference_methods.R:92: error: Different matrix types`

## man/

* dcNetwork.md: This code chunk igraph::plot.igraph(ig) was set as not run. But seems it didn't take much time running and returns an igraph. Was there any other reason? Because generally we don't encourage developers to add the dontrun tag for examples.

> I don't remember a particular reason for this. I have removed the `dontrun` tag so the results are now plotted

## vignette

* dcanr_vignette.Rmd: "Installation" section: show to users how to install the package as if it has been included in Bioconductor. Because new packages is going to be in Bioc devel, they are required to use BiocManager instead of BiocInstaller for downloading the package. You should include something like this:

> Installation instructions have been modified in the vignette and in the github README file for the repository

**Comment by Liubuntu** [comment]
Hi @bhuvad , 

Thanks for those quick updates, and they all look fine for me. 

Only it's weird that bioc-issue-bot catches the valid commit but didn't generate a building report. The building and checking on my linux machine works perfect. So I will ask my colleague to kick a manual build so that I can see the building report. Once it clears on all platforms, I will accept the package. 

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @bhuvad 

Here is the review for the `SingscoreWorkflow`. The vignette is written well, only some minor issues and we are good to go. 

Cheers,
Qian

## DESCRIPTION
- `LazyData:` field: For packages that include data, we recommend not including LazyData: TRUE. This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data.
- `Depends:` is for packages that provide essential functionality for users of your package, It is unusual for more than three packages to be listed as ‘Depends:’. "R (>= 3.6.0)" is usually in `Depends` field, and in your case, the data package of `dcanr`.
- Please use "R (>= 3.6.0)" in the `Depends` field.
- `Imports:` is for packages that provide functions, methods, or classes that are used inside your package name space. Most packages should be listed here.
- `URL:` field: This field directs users to source code repositories, additional help resources, etc; You can put your github directory here.
- `BugReports:` field: It is encouraged to include the relevant links to Github for reporting Issues.

## NEWS.md
- Good!

## R/ 
- In the data documentation, please add a field of `@examples data(AMLPatientMutationsTCGA)`.

**Comment by Liubuntu** [comment]
Hi @bhuvad , 

Your package of `dcanr` is now accepted. 

Please be noted that the deadline for accepting new packages into Bioc release will be this Wednesday (April 24th). Please try to fix the issues in the workflow package `SingscoreWorkflow` as soon as possible so that we can get them both accepted. 

Best,
Qian

**Comment by bhuvad** [comment]
Hi @Liubuntu,

Thank you again for such prompt feedback. I have addressed all the feedback you provided. Glad to hear the good news about dcanr! Hope to hear the same for the workflow package soon :).

Cheers,
Dharmesh

## DESCRIPTION

* LazyData: field: For packages that include data, we recommend not including LazyData: TRUE. This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data.

> This has been set to false now

* Depends: is for packages that provide essential functionality for users of your package, It is unusual for more than three packages to be listed as ‘Depends:’. "R (>= 3.6.0)" is usually in Depends field, and in your case, the data package of dcanr.
* Please use "R (>= 3.6.0)" in the Depends field.
* Imports: is for packages that provide functions, methods, or classes that are used inside your package name space. Most packages should be listed here.

> All these matters have been addressed. The only item in the Depends field is now `R (>= 3.6.0)`. All other packages have been moved to the imports field. The data used in this workflow comes from this package itself therefore `dcanr` can also be moved to Imports. I originally assumed that these packages are dependencies as they are part of the vignette, however I now see they weren't. Thanks for pointing that out.

* URL: field: This field directs users to source code repositories, additional help resources, etc; You can put your github directory here.

> I have added the link to the github repo https://github.com/DavisLaboratory/SingscoreAMLMutations

* BugReports: field: It is encouraged to include the relevant links to Github for reporting Issues.

> I have added the issues link to the github repo https://github.com/DavisLaboratory/SingscoreAMLMutations/issues

## NEWS.md

* Good!

## R/

* In the data documentation, please add a field of @examples data(AMLPatientMutationsTCGA)

> I have added this example

**Comment by bhuvad** [comment]
Hi @Liubuntu,

I have made a commit to correct a warning I got though there is a problem with the build again. I have tested the build on my machine and it passes all checks. You might have to trigger a build again. 

Cheers, 
Dharmesh

**Comment by Liubuntu** [comment]
Hi @bhuvad , 

Thanks for the quick fix. Both packages are accepted now to Bioc 3.9 release. 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bhuvad.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dcanr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dcanr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bhuvad.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingscoreAMLMutations")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingscoreAMLMutations

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
