### ISSUE TITLE
curatedAdipoChIP: A Curated ChIP-Seq Dataset of MDI-induced Differentiated Adipocytes (3T3-L1)

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/Contributions#1059]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MahShaaban/curatedAdipoChIP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by MahShaaban** [comment]
Hi @lshep 
The build is failing because of an error in creating the vignette. The package contains an R object in `data/` which is tracked using **lfs**. The system also generates an error because of a git tracked `.gitattributes` file. Is lfs allowed on the build system?

**Comment by lshep** [comment]
We do not support lfs;  we encourage use of the Bioconductor Hubs (AnnotationHub/ExperimentHub) -  Please see [Creating ExperimentHub Package](https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html).   Yes please remove .gitattributes from being git tracked with a `git rm` .

**Comment by lshep** [comment]
**General**
- [ ] One of your package dependencoes bib2df has been removed from CRAN. Please
remove this package dependency or reach out to CRAN/package maintainer to
reinstate.  We do not accept dependencies that are not on CRAN or
Bioconductor. The SPB will not pick up on this change as it has already been
installed before the package was removed from CRAN but as soon as we update to a
newer version of R and flush the repo it will fail on all platforms. 

https://cran.r-project.org/web/packages/bib2df/index.html   



**Build report**
- [ ] Please fix this note:
```
* checking dependencies in R code ... NOTE
Packages in Depends field not imported from:
  ExperimentHub ExperimentHubData SummarizedExperiment
  These packages need to be imported from (in the NAMESPACE file)
```


- [ ] We strongly encourage the use of unit tests.  Unit tests can be a simple
  as checking to make sure the input/output data is of expected format and the
  like


**NAMESPACE**
- [ ] As mentioned in build report above.  Please import necessary packages that
are listed in the depends of the Description.  


**vignette**
- [ ] Optional but I recommend renaming to package name or at least
curatedchip.Rmd.  It is much more intuitive for a user searching for a vignette
to type `vignette('curatedAdipoChIP')  or  vignette('curatedchip')` rather than
vignette('curatedchop_vignette')

Thank you and I look forward to accepting your package.  Please address the above issues and when ready please comment here on the issue requesting a re-review.

**Comment by MahShaaban** [comment]
Thanks @lshep 
* I opened a new [issue](https://github.com/ropensci/bib2df/issues/28) on the packages github repo. If the maintainer didn't reply soon I will look for a replacement for `bib2df`.
* I imported the three packages, so this note should be fixed.
* I was adivised by the reviewer in a previous submission of a similar packages to not use tests, [here](https://github.com/Bioconductor/Contributions/issues/994#issuecomment-466138271). I am also worried about the tests having to download and load the the data object every time they run.
* I renamed the vignette file to `curatedAdipoChIP.Rmd`.

**Comment by lshep** [comment]
Ok.  Let's wait and see what bib2df comes back with but otherwise I'm ready to accept.

**Comment by lshep** [comment]
Side note because we can still give them time to respond, Just keep me mind that the acceptance deadline is the 24th - so if you need time to make changes and make sure it checks ok just leave yourself a few days -

**Comment by MahShaaban** [comment]
I removed the `bib2df` dependency as I haven't got any reply on the issue.
Please let me know if other changes are needed.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MahShaaban.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("curatedAdipoChIP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/curatedAdipoChIP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
