### ISSUE TITLE
GNET2

### ISSUE THREAD

**Issue by chrischen1** [Bioconductor/Contributions#1060]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/chrischen1/GNET2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package to interface with (accept as inputs and outputs, as appropriate) [standard Bioconductor data objects][1], especially [SummarizedExperiment][2]. Please post a comment here when you have addressed this initial issue.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/devel/SummarizedExperiment

**Comment by chrischen1** [comment]
Thank you! The package is now updated with the capability to accept the SummarizedExperiment Object as standard input. Another issue is that the current Github Repository has been changed to https://github.com/chrischen1/GNET2

**Comment by chrischen1** [comment]
> Please update your package to interface with (accept as inputs and outputs, as appropriate) [standard Bioconductor data objects](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/), especially [SummarizedExperiment](https://bioconductor.org/packages/devel/SummarizedExperiment). Please post a comment here when you have addressed this initial issue.

Thank you! The package is now updated with the capability to accept the SummarizedExperiment Object as standard input. Another issue is that the current Github Repository has been changed to https://github.com/chrischen1/GNET2

**Comment by mtmorgan** [comment]
@lshep can you help with the github repository name change?

**Comment by lshep** [comment]
Thank you for letting us know.  The github repository has changed in our database and as long as the webhook is initialized should trigger builds on version bumps.

**Comment by chrischen1** [comment]
Dear @mtmorgan , I think it is ready for review.
Best,
@chrischen1

**Comment by mtmorgan** [comment]
Please update in response to the following and post a short comment when ready for final review.

DESCRIPTION, vignettes/, man/

- ok

R (please apply principles of each comment to all of your code)

- `build_module.R:13` use drop=FALSE to avoid surprise coercion from matrix to vector.

- `build_module.R:14` avoid iteration (`for()`, `*apply()`) in favor of vectorization, for instance using `matrixStats::colSds()`
    ```
    mean = rep(colMeans(x_i), each = nrow(x_i))
    sd = rep(colSds(x_i), each = nrow(x_i))
    density_scores <- dnorm(x_i, mean, sd, log = TRUE)
    score_total <- score_total + sum(density_scores)
    ```
    
- `build_module.R:161` AND THROUGHOUT 'copy-and-append' strategies like this are very inefficient; try to use 'pre-allocate-and-fill' or similar; see [1][]

[1]: https://bioconductor.org/developers/how-to/efficient-code/

- `build_module.R:252` it is not usually necessary to use `message(paste("iteration", i))`; simply `message("iteration ", i)`
    
src

- gnet_rcpp.cpp:108 declare inputs visible to R as `const` to avoid accidental modification of R values.

misc

- please make sure NEWS files are parsed by `utils::news()`

**Comment by chrischen1** [comment]
Hi @mtmorgan ,

Thanks for the comments! I have made a few changes based on the review.

- All matrix slice operations are added with drop=FALSE if they are intended to keep the matrix format.
- Most of the for loops have been replaced with vectorization. Below is the performance improvement using the R code to build a module.
```
X = matrix(rnorm(15*500),15,500)
Y = matrix(rnorm(15*500),15,500)
system.time(build_moduleR_original(X, Y,max_depth=3,cor_cutoff=0.9,min_divide_size=3))
user  system elapsed 
211.435   0.000  211.434 
system.time(build_moduleR(X, Y,max_depth=3,cor_cutoff=0.9,min_divide_size=3))
user  system elapsed 
8.380   0.000   8.379 
```
A few loops still exist in the code as they could not be simply replaced with vectorization.

- All rbind() and cbind() are now replaced with the 'pre-allocate-and-fill' way.
- All other issues in the comments are fixed accordingly.

Please review this when have time, thanks!
Chris

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/chrischen1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GNET2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GNET2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
