### ISSUE TITLE
ViSEAGO

### ISSUE THREAD

**Issue by abrionne** [Bioconductor/Contributions#1061]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/abrionne/ViSEAGO

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
@nturaga  was away this week but here are a few comments to get you started:

**Build Report**

- [ ] Fix the build report for global variables and function definitions. 
- [ ] Do not try to install packages for a user in `annotate.R`. `stop()` and recommend the user installs themselves.

**README**

- [ ] Also include Bioconductor Instructions

**NEWS**

- [ ] Do not have an empty NEWS file. Either remove or add a relevant informative message. See formatting with `?news`

**LICENSE**

- [ ] Can be removed. The GPL-3 licenses is already distributed with R. 

**inst/extadata**

- [ ] Please provide a corresponding inst/script that describes how the data in inst/extadata was generated along with any source information. 


**man**

- [ ] I recommend having a package level man page ViSEAGO.Rd that gives an overview of the package and directs to the main functions of the package. 

**vignettes**

- [ ] Optional but I recommend renaming overview.Rmd to ViSEAGO.Rmd. It is much more intuitive for a user to type `vignette("ViSEAGO")` than vignette("overview")`. It is also not advisable to have something so generic as there could be potential naming conflict depending on other package dependencies loaded. When I tried to load your vignette, the wrong vignette appeared because GenomicDataCommons also has a vignette named overview that is first in the load path
```
> library(ViSEAGO)
> vignette("overview")
starting httpd help server ... done
Warning message:
vignette 'overview' found more than once,
using the one found in '/home/lori/R/x86_64-pc-linux-gnu-library/3.6PreRel/GenomicDataCommons/doc' 
```

- [ ] The vignette global option `eval=FALSE` should not be used. Vignettes should be evaluated and run interactively. Please update. Also the fig.path should not write to the home directory. Please update to use `tempdir/tempfile` to write output.  

- [ ] The vignette should operate from a `tempdir()/tempfile()` and not create/write to a users home directory to avoid potentially overwritting a users existing directories or files. Please update throughout. So in your call to `base::dir.create` this should not be to the home directory.

- [ ] `eval=FALSE` should be used sparingly. Please justify any use of eval=FALSE in the vignette code functions. I see some of your commits to improve build time where to add eval=FALSE, we would prefer the longer build time and code being fully executed/tested

@nturaga  can do a more thorough review of the underlying R code but please start working on these.

**Comment by abrionne** [comment]
Thanks you @Ishep for your comments.
I work on it and I commit changes before Friday.

**Comment by abrionne** [comment]
> **Build Report**
> * [x]  Fix the build report for global variables and function definitions.
NB: 
no visible binding for global variable comes from data.table syntax.
I modified  style syntaxe for prevent theses notes except for lines 204 and 212 in 
compute_SS_distances.
 *build report*: 
" compute_SS_distances,ANY-character: no visible binding for global
    variable ‘N’
  compute_SS_distances,ANY-character: no visible binding for global
    variable ‘IC’
  Undefined global functions or variables:
    IC N"
> * [x]  Do not try to install packages for a user in `annotate.R`. `stop()` and recommend the user installs themselves. 

> **README**
> * [x]  Also include Bioconductor Instructions

> **NEWS**
> * [x]  Do not have an empty NEWS file. Either remove or add a relevant informative message. See formatting with `?news`

> **LICENSE**
> * [x]  Can be removed. The GPL-3 licenses is already distributed with R.
> **inst/extadata**
> * [x]  Please provide a corresponding inst/script that describes how the data in inst/extadata was generated along with any source information.

> **man**
> * [x]  I recommend having a package level man page ViSEAGO.Rd that gives an overview of the package and directs to the main functions of the package.

> **vignettes**
> * [x]  Optional but I recommend renaming overview.Rmd to ViSEAGO.Rmd. It is much more intuitive for a user to type `vignette("ViSEAGO")` than vignette("overview")`. 
> * [x]  The vignette global option `eval=FALSE` should not be used. Vignettes should be evaluated and run interactively. Please update. Also the fig.path should not write to the home directory. Please update to use `tempdir/tempfile` to write output.
> * [x]  The vignette should operate from a `tempdir()/tempfile()` and not create/write to a users home directory to avoid potentially overwritting a users existing directories or files. Please update throughout. So in your call to `base::dir.create` this should not be to the home directory.
> * [x]  `eval=FALSE` should be used sparingly. Please justify any use of eval=FALSE in the vignette code functions. I see some of your commits to improve build time where to add eval=FALSE, we would prefer the longer build time and code being fully executed/tested

I have checked package  for mouse_bionconductor vignette:
* with eval=FALSE in knitr::opts_chunk$set(...)
 build report: Duration: 4m 34.3s and  installed size is  7.0Mb
* with eval=TRUE in knitr::opts_chunk$set(...) 
build report: Duration: 8m 17.2s and installed size is 11.7Mb

I kept eval=FALSE to prevent warnings build report

Thanks to you @lshep for the first code pass.
I wait now @nturaga report for the second pass.

@abrionne

**Comment by nturaga** [comment]
## Review

## R

* You seem to using the function for base R, in the following way,
  `base::paste`. This is not required. You can call the base R
  functions by their name, unless you are redefining the function
  `paste` in your code.

  Even this call to `base::` is not done uniformly. This is cluttering
  the codebase for no reason, making it extremely hard to read.

  Please remove, `base::` to all functions, like cat, paste, vapply
  and all the functions/methods defined in base R.

  Similarly with `methods`, this is distributed with base R. For a
  list of packages distributed by base R, try:

```
i <- installed.packages()

rownames(i[ i[,"Priority"] %in% c("base","recommended"), c("Package",
"Priority")])
```

Please check this,http://bioconductor.org/developers/how-to/coding-style/

```
Namespaces

Import all symbols used from packages other than “base”. Except for default
packages (base, graphics, stats, etc.) or when overly tedious, fully
enumerate imports.
Export all symbols useful to end users. Fully enumerate exports.
```

* Please format your code also accordingly after you have removed the
  calls to all the functions available to you with base R.

* To check the class type of an object, please use the function `is`.

is(object, "enrich_GO_terms")
as opposed to
class(object) %in% c("enrich_GO_terms") ...
Make this change everywhere this paradigm is used.
* When issuing end-user-messages please make sure you are using the
  appropriate ones, http://bioconductor.org/developers/how-to/coding-style/.

```
  End-User messages

message() communicates diagnostic messages (e.g., progress during lengthy
computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g.,
in a show method.
```

  eg:

  You have to use `message` here and not `cat`

    base::cat("GOcount is required for multiples comparisons")
* You seem to be using the function `rm` to remove some object. This
  is not needed, if you are "saving" memory. R does this
  automatically. Please remove all calls to `rm`.

  This is in the file GOterms_heatmap.R. The way it's written right
  now, makes it extremely difficult to follow the logic as a reviewer.

  I highly recommend you reformat your code by hand, using 4 space
  indent and removing all the calls to `<package>::`. If you are not
  getting access to that function, pleaes import in your NAMESPACE.

* There are unoptimized chunks of code which use `apply` and other
  loop like statements all over your code. In GOterms_heatmap.R,

mat<-base::apply(mat,base::c(1,2),function(x){
if(base::is.na(x)){
NA
}else{
if(x<2){0}else{1}
}
})

You could just write this as,
mat <- ifelse(mat < 2, 0, 1)
There is no need to use `apply` here. Pleae check the use of
    apply/loops all across your package. Some of the `vapply`'s are
    also not needed. Please vectorize your code.
http://bioconductor.org/developers/how-to/efficient-code/
Look at the "Vectorize" section.
* Instead of using `seq_len(length(x))` you can use `seq_along(x)`.

* You don't need to use `which` for subsetting. In overLapper.R

mycol1 <-base::which(base::colnames(setmatrix) %in% allcombl[[index]])
mycol2 <-base::which(!base::colnames(setmatrix) %in% allcombl[[index]])
cond1 <-base::rowSums(setmatrix[, base::rep(mycol1, 2)]) == 2 *
base::length(mycol1)
cond2 <-base::rowSums(setmatrix[, base::rep(mycol2, 2)]) == 0
vs
mycol <-colnames(setmatrix) %in% allcombl[[index]]
cond1 <-matrixStats::rowSums2(setmatrix[, rep(mycol, 2)]) == 2 *
length(mycol1))
cond2 <-matrixStats::rowSums2(setmatrix[, rep(!mycol, 2)]) == 0

  Simplify your code.

The package needs some improvement before it can be accepted. Please make
the changes given above, and report back point by point so I can go through
the code again.

Thank you,

Nitesh

**Comment by nturaga** [comment]
# Review

## R

* You seem to using the function for base R, in the following way,
  `base::paste`. This is not required. You can call the base R
   functions by their name, unless you are redefining the function
  `paste` in your code.

  Even this call to `base::` is not done uniformly. This is cluttering your codebase for no reason, making it extremely hard to read.

  Please remove, `base::` to all functions, like cat, paste, vapply and all the functions/methods defined in base R.

  Similarly with `methods`, this is distributed with base R. For a
  list of packages distributed by base R, try:

      i <- installed.packages()

      rownames(i[ i[,"Priority"] %in% c("base","recommended"), c("Package", "Priority")])


  Please check this,http://bioconductor.org/developers/how-to/coding-style/

"""

  Namespaces

  Import all symbols used from packages other than “base”. Except for default packages (base, graphics, stats, etc.) or when overly tedious, fully enumerate imports.

  Export all symbols useful to end users. Fully enumerate exports.

"""

* Please format your code also accordingly after you have removed the
  calls to all the functions available to you with base R.

* To check the class type of an object, please use the function `is`.

		is(object, "enrich_GO_terms")

	as opposed to

		class(object) %in% c("enrich_GO_terms") ...

	Make this change everywhere this paradigm is used.

* When issuing end-user-messages please make sure you are using the
  appropriate ones, http://bioconductor.org/developers/how-to/coding-style/.

```
  End-User messages

message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```
  eg:

  You have to use `message` here and not `cat`

    base::cat("GOcount is required for multiples comparisons")

* You seem to be using the function `rm` to remove some object. This
  is not needed, if you are "saving" memory. R does this
  automatically. Please remove all calls to `rm`.

  This is in the file GOterms_heatmap.R. The way it's written right
  now, makes it extremely difficult to follow the logic as a reviewer.

  I highly recommend you reformat your code by hand, using 4 space
  indent and removing all the calls to `<package>::`. If you are not
  getting access to that function, pleaes import in your NAMESPACE.

* There are unoptimized chunks of code which use `apply` and other
  loop like statements all over your code. In GOterms_heatmap.R,

		mat<-base::apply(mat,base::c(1,2),function(x){
			if(base::is.na(x)){
				NA
			}else{
				if(x<2){0}else{1}
			}
		})

	You could just write this as,

		mat <- ifelse(mat < 2, 0, 1)

	There is no need to use `apply` here. Pleae check the use of
         apply/loops all across your package. Some of the `vapply`'s are
         also not needed. Please vectorize your code.

	http://bioconductor.org/developers/how-to/efficient-code/

	Look at the "Vectorize" section.

* Instead of using `seq_len(length(x))` you can use `seq_along(x)`.

* You don't need to use `which` for subsetting. In overLapper.R

		mycol1 <-base::which(base::colnames(setmatrix) %in% allcombl[[index]])
		mycol2 <-base::which(!base::colnames(setmatrix) %in% allcombl[[index]])
		cond1 <-base::rowSums(setmatrix[, base::rep(mycol1, 2)]) == 2 * base::length(mycol1)
		cond2 <-base::rowSums(setmatrix[, base::rep(mycol2, 2)]) == 0

	vs

		mycol <-colnames(setmatrix) %in% allcombl[[index]]
		cond1 <-matrixStats::rowSums2(setmatrix[, rep(mycol, 2)]) == 2 * length(mycol1))
		cond2 <-matrixStats::rowSums2(setmatrix[, rep(!mycol, 2)]) == 0

  Simplify your code.


The package needs some improvement before it can be accepted. Please make
the changes given above, and report back point by point so I can go through
the code again.

Thank you,

Nitesh

**Comment by abrionne** [comment]
Hi Nitesh,

Thanks you for our package code evaluation.
I think I made all required changes.

Sincerely,

Aurélien,

> # Review
> ## R
> * You seem to using the function for base R, in the following way,
>   `base::paste`. This is not required. You can call the base R
>   functions by their name, unless you are redefining the function
>   `paste` in your code.
>   Even this call to `base::` is not done uniformly. This is cluttering your codebase for no reason, making it extremely hard to read.
>   * [x] Please remove, `base::` to all functions, like cat, paste, vapply and all the functions/methods defined in base R.
>   * [x] Similarly with `methods`, this is distributed with base R. For a
>   list of packages distributed by base R, try:
>   ```
>   i <- installed.packages()
>   
>   rownames(i[ i[,"Priority"] %in% c("base","recommended"), c("Package", "Priority")])
>   ```
>   Please check this,http://bioconductor.org/developers/how-to/coding-style/
> 
> """
> 
> Namespaces
> 
> * [x] Import all symbols used from packages other than “base”. Except for default packages (base, graphics, stats, etc.) or when overly tedious, fully enumerate imports.
> 
> * [x] Export all symbols useful to end users. Fully enumerate exports.
> 
> """
> 
> * * [x] Please format your code also accordingly after you have removed the
>   calls to all the functions available to you with base R.
> * * [x] To check the class type of an object, please use the function `is`.
>   ```
>     is(object, "enrich_GO_terms")
>   ```
>   as opposed to
>   ```
>     class(object) %in% c("enrich_GO_terms") ...
>   ```
>   Make this change everywhere this paradigm is used.
> * When issuing end-user-messages please make sure you are using the
>   appropriate ones, http://bioconductor.org/developers/how-to/coding-style/.
> 
> ```
>  * * [x] End-User messages
> 
> message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
> warning() communicates unusual situations handled by your code.
> stop() indicates an error condition.
> cat() or print() are used only when displaying an object to the user, e.g., in a show method.
> ```
> eg:
> 
> You have to use `message` here and not `cat`
> 
> ```
> base::cat("GOcount is required for multiples comparisons")
> ```
> * [x] You seem to be using the function `rm` to remove some object. This
>   is not needed, if you are "saving" memory. R does this
>   automatically. Please remove all calls to `rm`.
>   This is in the file GOterms_heatmap.R. The way it's written right
>   now, makes it extremely difficult to follow the logic as a reviewer.
>   * [x] I highly recommend you reformat your code by hand, using 4 space
>   indent and removing all the calls to `<package>::`. If you are not
>   getting access to that function, pleaes import in your NAMESPACE.
> * [x] There are unoptimized chunks of code which use `apply` and other
>   loop like statements all over your code. In GOterms_heatmap.R,
>   ```
>     mat<-base::apply(mat,base::c(1,2),function(x){
>     	if(base::is.na(x)){
>     		NA
>     	}else{
>     		if(x<2){0}else{1}
>     	}
>     })
>   ```
>   You could just write this as,
>   ```
>     mat <- ifelse(mat < 2, 0, 1)
>   ```
>   There is no need to use `apply` here. Pleae check the use of
>   apply/loops all across your package. Some of the `vapply`'s are
>   also not needed. Please vectorize your code.
>   http://bioconductor.org/developers/how-to/efficient-code/
>   Look at the "Vectorize" section.
> * * [x] Instead of using `seq_len(length(x))` you can use `seq_along(x)`.
> * * [x] You don't need to use `which` for subsetting. In overLapper.R
>   ```
>     mycol1 <-base::which(base::colnames(setmatrix) %in% allcombl[[index]])
>     mycol2 <-base::which(!base::colnames(setmatrix) %in% allcombl[[index]])
>     cond1 <-base::rowSums(setmatrix[, base::rep(mycol1, 2)]) == 2 * base::length(mycol1)
>     cond2 <-base::rowSums(setmatrix[, base::rep(mycol2, 2)]) == 0
>   ```
>   vs
>   ```
>     mycol <-colnames(setmatrix) %in% allcombl[[index]]
>     cond1 <-matrixStats::rowSums2(setmatrix[, rep(mycol, 2)]) == 2 * length(mycol1))
>     cond2 <-matrixStats::rowSums2(setmatrix[, rep(!mycol, 2)]) == 0
>   ```
>   Simplify your code.

**Comment by nturaga** [comment]
## Update

* I'd still like to see you remove your calls to `base::` in your
  functions. This doesn't add anything. But if you are getting errors,
  it means there are other `paste` methods which are overriding your
  `base::paste` method.

  Same with `base::match.arg` as well.

* Check the NOTE in your build report and fix some of these issues,

```
annotate,character-genomic_ressource: warning in getBM(attributes =
  c("ensembl_gene_id", "go_id", "go_linkage_type", "namespace_1003"),
  filters = unlist(go_filter[grep("with GO ID", ignore.case = TRUE,
  go_filter$description), "name", with = FALSE]), value = TRUE, mart =
  myspecies): partial argument match of 'value' to 'values'

compute_SS_distances,ANY-character: warning in select(GO.db, keys =
  onto$values, column = "TERM"): partial argument match of 'column' to
  'columns'

merge_enrich_terms,list : <anonymous>: warning in getBM(attributes =
  c("ensembl_gene_id", "external_gene_name"), value = TRUE, mart =
  myspecies): partial argument match of 'value' to 'values'
```

* Add a NEWS file

```
  * Checking package NEWS...
      * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
```

* You should just depend on `methods` package and add it to your DESCRIPTION file and see if you can get rid of those NOTEs. Your package looks fairly complete and can be accepted. But every build report will have those NOTE issues which you need to fix. 

Give it another build report and version bump with these changes.

Best,

Nitesh

**Comment by abrionne** [comment]
Thank you Nitesh for your comments,
I have added responses to your comments.

> ## Update
> * I'd still like to see you remove your calls to `base::` in your
>   functions. This doesn't add anything. But if you are getting errors,
>   it means there are other `paste` methods which are overriding your
>   `base::paste` method.
>   Same with `base::match.arg` as well.
> * Check the NOTE in your build report and fix some of these issues,
> 
forgotten "base::" have been removed.

> ```
> annotate,character-genomic_ressource: warning in getBM(attributes =
>   c("ensembl_gene_id", "go_id", "go_linkage_type", "namespace_1003"),
>   filters = unlist(go_filter[grep("with GO ID", ignore.case = TRUE,
>   go_filter$description), "name", with = FALSE]), value = TRUE, mart =
>   myspecies): partial argument match of 'value' to 'values'

this message come from "myspecies" internal object from ViSEAGO::annotate (mart object from biomaRt)
and only appears in the check report without error in ViSEAGO::annotate method execution.
This message seems come from the existence of several colomns named "ensembl_gene_id" in Ensembl (throught biomaRt) but without code error when executed.

columns(myspecies)[columns(myspecies)%in%"ensembl_gene_id"]
[1] "ensembl_gene_id" "ensembl_gene_id" "ensembl_gene_id" "ensembl_gene_id" "ensembl_gene_id"

> compute_SS_distances,ANY-character: warning in select(GO.db, keys =
>   onto$values, column = "TERM"): partial argument match of 'column' to
>   'columns'

the called column "TERM" is real, and I don't understand the origin of this check note.
columns(GO.db)
[1] "DEFINITION" "GOID"       "ONTOLOGY"   "TERM"   

> merge_enrich_terms,list : <anonymous>: warning in getBM(attributes =
>   c("ensembl_gene_id", "external_gene_name"), value = TRUE, mart =
>   myspecies): partial argument match of 'value' to 'values'

same than annotate (seems due to "ensembl_gene_id" column call)

> * Add a NEWS file
added

> ```
>   * Checking package NEWS...
>       * NOTE: Consider adding a NEWS file, so your package news will be
>       included in Bioconductor release announcements.

NEWS file added

> * You should just depend on `methods` package and add it to your DESCRIPTION file and see if you can get rid of those NOTEs. Your package looks fairly complete and can be accepted. But every build report will have those NOTE issues which you need to fix.

I added "methods" in DESCRIPTION and also in NAMESPACE for several functions in order to prevents this NOTES.
The last notes can't be removed (come from data.table columns calls)

I have also added a custom2GO method for local GO annotations (species not in EntrezGene, Ensembl, or Uniprot database)  in the last version bump.

Thank you Nitesh for your comments that improve this package

Aurélien,

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/abrionne.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ViSEAGO")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ViSEAGO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Monod79** [comment]
Hi! 

Thanks for the package. Although the package seems to address the redundancy problem from GO terms, the GOterms_heatmap visual output could be greatly improved. Is there a way to display the terms name on the heatmap? Also, how do we change the heatmap colors? 

Thanks !

**Comment by mtmorgan** [comment]
@Monod79 please post issues to the developer of this package on the package github repository https://github.com/abrionne/ViSEAGO

**Comment by Monod79** [comment]
The github repository is down...

**Comment by Monod79** [comment]
The github repository is down...

**Comment by mtmorgan** [comment]
Contact `maintainer("ViSEAGO")` or ask on the support site https://support.bioconductor.org with the tag ViSEAGO; this issue was used exclusively for initial package submission.

**Comment by abrionne** [comment]
Hi @Monod79 ,

For display GO names on GOterms_heatmap, simply set showGOlabels = TRUE (default parameter).
You cannot ,for the moment, modifiy heatmap colors. I will add this option in the next release.
For bug report go to https://forgemia.inra.fr/UMR-BOA/ViSEAGO/issues
Thanks,

**Comment by Monod79** [comment]
Hi Aurélien,

Thanks for the quick reply. The default display parameter requires to hover over each clustered terms, in an interactive manner, which is incompatible with results publications, but really great in a live presentation. I would rather like to publish the results in a figure where readers can read the names of the GO terms.

The package has great potential !!! It addresses the inconvenient redundancies of GO terms, and resumes perfectly how biologist would like to display and understand their omics data.

Thanks for the good work !

Jonathan

Jonathan Boulais, PhD

Analyste en bio-informatique & protéomique
Computational analyst in proteomics

Institut de recherches cliniques de Montreal (IRCM)
Montreal Clinical Research Institute
110 avenue des Pins Ouest
Montreal (Qc) H2W 1R7
Canada

Phone: 514 987-3245
Fax: 514 987-5624
[cid:AAECBC98-01EE-4DD5-ABEF-7A30D9A3C997@ircm.priv]

De : Aurélien BRIONNE <notifications@github.com>
Envoyé : Tuesday, November 12, 2019 2:26 AM
À : Bioconductor/Contributions <Contributions@noreply.github.com>
Cc : BOULAIS Jonathan <Jonathan.Boulais@ircm.qc.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Bioconductor/Contributions] ViSEAGO (#1061)


Hi @Monod79<https://github.com/Monod79> ,

For display GO names on GOterms_heatmap, simply set showGOlabels = TRUE (default parameter).
You cannot ,for the moment, modifiy heatmap colors. I will add this option in the next release.
For bug report go to https://forgemia.inra.fr/UMR-BOA/ViSEAGO/issues
Thanks,

**Comment by abrionne** [comment]
Dear @Monod79,

A new version of ViSEAGO (1.1.0) will be available in few hours on bioconducor, where you could modify heatmap colors on GOterms_heatmap.
