### ISSUE TITLE
MBQN package

### ISSUE THREAD

**Issue by arianeschad** [Bioconductor/Contributions#1064]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/arianeschad/MBQN

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Ariane, @arianeschad 
Thank you for your submission to Bioconductor. 
Please see your review below. 

Post any questions in the same thread here. 

Best regards,
Marcel

---

# MBQN #1064

* Please use a Bioconductor data structure that works with your matrix
representation. Bioconductor prefers packages that are interoperable so we
require that all packages re-use existing Bioconductor data classes where
possible.

## DESCRIPTION

* Looks good. Try to keep it within the 80 column width limit for readability.
* Provide a `BugReports` URL pointing to the GitHub issues page.

## NAMESPACE

* Try to be consistent with the use of `camelCase` and `snake_case`
* Note that it is not entirely necessary to prefix all your functions with
`mbqn` but acceptable
* What is the reason for using `filesstrings::file.move`? Why not use `rename`?

## vignettes

* Stay within the 80 column width for readability. Reviewers will appreciate it.
* Note that `preprocessCore` and `rpx` should be obtained from CRAN and
Bioconductor repositories rather than referencing the GitHub version.
* Why export an `mbqnExample` rather than providing an example in the `mbqn*`
functions? Why do you need an external file rather than something saved in
`extdata`
* Documentation should be reviewed using `help(package = "MBQN")`.
`??MBQN` uses fuzzy matching.

## R

* Use a more specific name for contained data
* Use temporary files to save data in `get_pxdfile` and other functions
instead of the working directory
* Use `message` instead of `print`
* Use `rename` instead of `file.move` and remove dependency
* `loadFile` is a generic name and it should be more specific
* You should use an appropriate Bioconductor class such as
`SummarizedExperiment` to store the return value of `loadFile`
* Consider using `BiocFileCache` for downloading and storing PRIDE data
* Use the more robust `seq_along` instead of `seq(1, x)`
* Do not save figures without the user's explicit consent. Avoid the `filename`
argument and just plot to the graphics device. Not all users want a `pdf` of
figures.
* `ifelse` calls in the `mbqnBoxplot` options can be replaced with
`x <- if(is.null(x)) value`, you can also create a helper function to avoid
repetitive code
* 'Demo' and 'example' functions are not needed when you have robust examples.
You should provide these demos in the example pages of the documentation
* You don't need to use double `::` in your own package `MBQN::get_kminmax`
* Remove `save_fig` and `show_fig` arguments, plotting functions will always
plot there should be no option to not plot. You may have to separate analysis,
and plotting functions in `mbqnPlotAll`
* Delete `set.seed` in `mbqnSimuData` and `mbqnSimuDistortion`. It has no
place inside functions even if it is a comment.


Minor:
* Use `file.exists` instead of `length(list.files(...))`
* Make a variable out of the `file.path` call and reuse it
* Use `all(is.na(r))` to check for NA values across the row instead of the
series of functions in `R/loadFile.R#63`
* Avoid using `$` symbols that use fuzzy matching and extract with `[[`
* Use `nrow` and `ncol` instead of `dim(x)[1]` and  `dim(x)[2]`
* Make `FUN` in `mbqn` a functional argument rather than matching the function
internally as is done by convention.

**Comment by LiNk-NY** [comment]
Hi Ariane, @arianeschad

Please provide some updates regarding the status of the package.
Do you intend to continue with the submission and
respond to the comments? 

Best regards,
Marcel

**Comment by arianeschad** [comment]
Dear Marcel, 
yes, we intend to continue. We are working on the comments.

**Comment by clemenskreutz** [comment]
Dear Marcel.

Let me try to respond point by point.
We want to quickly finish submission because we submitted a paper.

> Hi Ariane, @arianeschad
> Thank you for your submission to Bioconductor.
> Please see your review below.
> 
> Post any questions in the same thread here.
> 
> Best regards,
> Marcel
> # MBQN #1064
> 
>     * Please use a Bioconductor data structure that works with your matrix
>       representation. Bioconductor prefers packages that are interoperable so we
>       require that all packages re-use existing Bioconductor data classes where
>       possible.
> 
> 
> ## DESCRIPTION
> 
>     * Looks good. Try to keep it within the 80 column width limit for readability.
> 
>     * Provide a `BugReports` URL pointing to the GitHub issues page.
Done.
> 
> ## NAMESPACE
> 
>     * Try to be consistent with the use of `camelCase` and `snake_case`
Done.
> 
>     * Note that it is not entirely necessary to prefix all your functions with
>       `mbqn` but acceptable
> 
>     * What is the reason for using `filesstrings::file.move`? Why not use `rename`?
Dones.
> ## vignettes
> 
>     * Stay within the 80 column width for readability. Reviewers will appreciate it.
Done. 
>     * Note that `preprocessCore` and `rpx` should be obtained from CRAN and
>       Bioconductor repositories rather than referencing the GitHub version.
Done.
>     * Why export an `mbqnExample` rather than providing an example in the `mbqn*`
>       functions? Why do you need an external file rather than something saved in
>       `extdata`
mbqnExample illustrates our package by downloading and using real public data from the PRIDE database.
The individual functions contain additional example code.
Please accept our current solution.

>     * Documentation should be reviewed using `help(package = "MBQN")`.
>       `??MBQN` uses fuzzy matching.
> 
Done.
> ## R
> 
>     * Use a more specific name for contained data
This is not clear to me. I don't see data contained in the package. 
I guess this has been changed.
>
>     * Use temporary files to save data in `get_pxdfile` and other functions
>       instead of the working directory
> 
Done.
>     * Use `message` instead of `print`
Done.
> 
>     * Use `rename` instead of `file.move` and remove dependency
Done.
> 
>     * `loadFile` is a generic name and it should be more specific
Done
> 
>     * You should use an appropriate Bioconductor class such as
>       `SummarizedExperiment` to store the return value of `loadFile`
Hmm. I agree, but to some extend it is also a matter of taste.
I think for less experienced users, it is easier to use the package if we do not introduce specific bioconductor classes when we just operate on the data matrix. The major purpose of this function is loading data for illustration purpose. Users working with other packages will anyway have the data in special Bioconductor classes.
We’ll keep it in mind.
>
>     * Consider using `BiocFileCache` for downloading and storing PRIDE data
Yes, this is also a potential improvment we will consider in the future.
> 
>     * Use the more robust `seq_along` instead of `seq(1, x)`
Done.
> 
>     * Do not save figures without the user's explicit consent. Avoid the `filename`
>       argument and just plot to the graphics device. Not all users want a `pdf` of
>       figures.
In the current version, no figures are saved by default any more.
> 
>     * `ifelse` calls in the `mbqnBoxplot` options can be replaced with
>       `x <- if(is.null(x)) value`, you can also create a helper function to avoid
>       repetitive code
Done.
> 
>     * 'Demo' and 'example' functions are not needed when you have robust examples.
>       You should provide these demos in the example pages of the documentation
See above. We'll try to improve this in the future.
> 
>     * You don't need to use double `::` in your own package `MBQN::get_kminmax`
Done.
> 
>     * Remove `save_fig` and `show_fig` arguments, plotting functions will always
>       plot there should be no option to not plot. You may have to separate analysis,
>       and plotting functions in `mbqnPlotAll`
Done.
> 
>     * Delete `set.seed` in `mbqnSimuData` and `mbqnSimuDistortion`. It has no
>       place inside functions even if it is a comment.
Done.
> 
> Minor:
> 
>     * Use `file.exists` instead of `length(list.files(...))`
Done.
> 
>     * Make a variable out of the `file.path` call and reuse it
Done, where it occurs repeatedly.
> 
>     * Use `all(is.na(r))` to check for NA values across the row instead of the
>       series of functions in `R/loadFile.R#63`
Done.
> 
>     * Avoid using `$` symbols that use fuzzy matching and extract with `[[`
This occurs too frequently. I’m not the responsible programmer and afraid that I break the code.
> 
>     * Use `nrow` and `ncol` instead of `dim(x)[1]` and  `dim(x)[2]`
Done.
> 
>     * Make `FUN` in `mbqn` a functional argument rather than matching the function
>       internally as is done by convention.

**Comment by LiNk-NY** [comment]
Hi Clemens, @clemenskreutz 
CC: @arianeschad 

> mbqnExample illustrates our package by downloading and using real public data from the PRIDE database.
The individual functions contain additional example code. Please accept our current solution.

This material seems more apt for a workflow rather than a package. Also, when
including an example as a function, the code gets obfuscated and not clear for
the user which is actually counterproductive. I would recommend that you break
up the large example function into smaller visible examples and include those
as examples in the package rather than as a single function. Please limit package
example datasets to small manageable sizes rather than large real-world data.

> Hmm. I agree, but to some extend it is also a matter of taste.
I think for less experienced users, it is easier to use the package if we do not introduce specific bioconductor classes when we just operate on the data matrix. The major purpose of this function is loading data for illustration purpose. Users working with other packages will anyway have the data in special Bioconductor classes.
We’ll keep it in mind.

We strive to keep packages interoperable by providing representations in the
usual and appropriate data classes. This includes `SummarizedExperiment` for
expression and similar data. You can provide compatibility for both data
types.

> In the current version, no figures are saved by default any more.

`mbqnExample` still saves figures using a hard coded `save.fig` value set to
`TRUE`

AND

`mbqnExample` doesn't work after interrupt (`^C`):

```
> mbqnExample(3)
File does not exist - start downloading file. This can take a few minutes!
 Do you want to continue? [y/n]
y
Proceed with download...
Error in unzip(fnm, files = "proteinGroups.txt", exdir = filepath) :
  object 'filepath' not found
```

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
@clemenskreutz @arianeschad 
Additional commentary from the core team points out the `dontrun` statements in the example and the vignette which are not good for keeping functions tested. 
You can't expect the user to press a button and learn about the typical workflow. 
This has to be drawn out in detail in the examples and _evaluated_. 

Thanks,
Marcel

**Comment by clemenskreutz** [comment]
@LiNk-NY 
We now removed the example function `mbqnExample` and put the respective examples into the documentation. We also don't save pdfs any more.

 `mbqnLoadFile` now also returns a `SummarizedExperiment` object.

**Comment by clemenskreutz** [comment]
@LiNk-NY 
We now also implemented a stable and robust download functionality for data from PRIDE.

**Comment by LiNk-NY** [comment]
Guten Morgen! @clemenskreutz 
Thank you for making those changes. 
My apologies for the delay. 
I will have a look at your package shortly. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
You should really be using a `tempfile` to store download or even better `BiocFileCache`. 
In the immediate future, you can use a tempfile but ideally, `BiocFileCache` is the way to go. 

You could have an object to store package-wide options. This can be done using an `.onLoad` function that defines all the default values within the package environment (so to avoid code in `mbqnBoxplot`). You can see an example in https://github.com/Bioconductor/SOUNDBoard/blob/master/R/zzz.R

Best, 
Marcel

**Comment by LiNk-NY** [comment]
> Received a valid push; starting a build. Commits are:
> 
> [7d81d24](https://github.com/arianeschad/MBQN/commit/7d81d245350701414b5bb2d5d31a7cf19cc362c2) Download is now done with BiocFileCache package

Jaaa! Das ist super! @clemenskreutz

**Comment by LiNk-NY** [comment]
Hi @arianeschad @clemenskreutz ,

If you want these demos (`mbqnDemo.R`, etc.) to be helpful, please include
the code somewhere visible rather than obfuscated in a function body. I
suggest you include separate vignettes to demonstrate this code. 
On the user side of things, simply running the function will not teach the
user what's going on in the background. 

Otherwise, your package looks ready to go. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
@arianeschad @clemenskreutz 
Also, it would be best to remove `*figure*.png` files from the package folder.
If you need to use images for your `README.md`, you can create a separate
GitHub repository and link the "raw github content" to the `README.md` file
as a link.

**Comment by LiNk-NY** [comment]
It looks good ! 
Don't forget to add your figures to the read me :+1: 
You can use `<img src = ... >` to add them. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi @arianeschad 
You're getting an error here:
```
--- re-building MBQNpackage.Rmd using rmarkdown
Quitting from lines 85-89 (MBQNpackage.Rmd) 
Error: processing vignette 'MBQNpackage.Rmd' failed with diagnostics:
object 'mtx.qn' not found
--- failed re-building MBQNpackage.Rmd
```
Best,
Marcel

**Comment by ebrombacher** [comment]
Dear Marcel @LiNk-NY  and Lori @lshep,
Thanks so much for your help!  The problem Marcel mentioned on 9 August is corrected now. There seems to be a bug when trying to run the package on Windows. We are trying to fix it as well as soon as possible.
Best wishes,
Eva

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/arianeschad.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MBQN")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MBQN

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
