### ISSUE TITLE
sRACIPE

### ISSUE THREAD

**Issue by vivekkohar** [Bioconductor/Contributions#1066]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vivekkohar/sRACIPE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vivekkohar** [comment]
Hi @dvantwisk 
The package is ready for review whenever you have time.
Thanks!
Vivek

**Comment by dvantwisk** [comment]
Great! I'll have a look at it soon.

**Comment by dvantwisk** [comment]
Apologies for the wait. Here is a review of your package. [REQUIRED] tags are changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not necessary. Please message me back when you are finished making changes.


R/AllClasses.R
- [ ] [REQUIRED] L12-22: There needs to be more documentation for the `RacipeSE`
class. I'd like to know what slots it has, that it inherits from
`SummarizedExperiments` and what exactly this class is used for.

R/AllGenerics.R
- [ ] [REQUIRED] It looks like the generics you are naming have very common
names. The Bioconductor suite of packages includes many generics and problems
will arise if multiple generics are declared under the same name. For this
reason, I'd like to ask that your generics (especially `config`, `param`, `ic`
, and `plotData`) be made more specific for your package. You could simple do
this by adding "sRACIPE" to the names such that `param` will now be
`sRACIPEparam` (or something like this). Another option would be to utilize
an exisiting generic in the Bioconductor environment for certain methods. If
you don't plan on these methods to be utilized in other places and to only be
used once, another option my to simply let them be functions.

R/data.R
- [ ] [REQUIRED] Pleae add information about the dimensionality of the data
and also the origin of the data if applicable.

R/methods.R
- [ ] [REQUIRED] L497,511: Use `seq_along()` instead of `seq(length())`.

R/simulateGRC.R
- [ ] [REQUIRED] L10: What is the purpose of the `config` parameter? Please
be sure that the documentation decribes the purpose of each parameter.
- [ ] [REQUIRED] L319: Use `message()`, `warning()`, or `error()` instead
of print for diagnostic messages.
- [ ] [REQUIRED] L430: Use `seq_along()` here.

tests
- [ ][CONSIDER] Add tests to your package using the `testthat` package.

vignettes/scRACIPE.R
- [ ] [REQUIRED] L82-87: Is there a reason not to evaluate this code block? We
would like to see user facing code evaluated by the builder to ensure its
functionality. Exceptions can be made for code that opens html pages or other
interactive elements but that doesn't seem to be happening here.

**Comment by vivekkohar** [comment]
@dvantwisk Thank you for carefully reviewing the package and the thoughtful comments. We have now addressed the points raised in the review. Can you please review it again? 

> Apologies for the wait. Here is a review of your package. [REQUIRED] tags are changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not necessary. Please message me back when you are finished making changes.
> 
> R/AllClasses.R
> 
> * [ ]  [REQUIRED] L12-22: There needs to be more documentation for the `RacipeSE`
>   class. I'd like to know what slots it has, that it inherits from
>   `SummarizedExperiments` and what exactly this class is used for.
> 
Additional description added.
> R/AllGenerics.R
> 
> * [ ]  [REQUIRED] It looks like the generics you are naming have very common
>   names. The Bioconductor suite of packages includes many generics and problems
>   will arise if multiple generics are declared under the same name. For this
>   reason, I'd like to ask that your generics (especially `config`, `param`, `ic`
>   , and `plotData`) be made more specific for your package. You could simple do
>   this by adding "sRACIPE" to the names such that `param` will now be
>   `sRACIPEparam` (or something like this). Another option would be to utilize
>   an exisiting generic in the Bioconductor environment for certain methods. If
>   you don't plan on these methods to be utilized in other places and to only be
>   used once, another option my to simply let them be functions.
> 
Changed the generics names to start with sracipe.
> R/data.R
> 
> * [ ]  [REQUIRED] Pleae add information about the dimensionality of the data
>   and also the origin of the data if applicable.
> 
Additional information added.
> R/methods.R
> 
> * [ ]  [REQUIRED] L497,511: Use `seq_along()` instead of `seq(length())`.
> 
Done
> R/simulateGRC.R
> 
> * [ ]  [REQUIRED] L10: What is the purpose of the `config` parameter? Please
>   be sure that the documentation decribes the purpose of each parameter.
> * [ ]  [REQUIRED] L319: Use `message()`, `warning()`, or `error()` instead
>   of print for diagnostic messages.
> * [ ]  [REQUIRED] L430: Use `seq_along()` here.
> 
Done
> tests
> 
> * [ ]  [CONSIDER] Add tests to your package using the `testthat` package.
> 
Will add tests in the next release cycle.
> vignettes/scRACIPE.R
> 
> * [ ]  [REQUIRED] L82-87: Is there a reason not to evaluate this code block? We
>   would like to see user facing code evaluated by the builder to ensure its
>   functionality. Exceptions can be made for code that opens html pages or other
>   interactive elements but that doesn't seem to be happening here.
The package took more than 5 minutes for CMD CHECK resulting in warnings, so I disabled some evaluations in the vignette. Changed it again after tuning some parameters to reduce the build time.

Thanks!!

**Comment by dvantwisk** [comment]
The changes look great! I don't think I have anything else to add, so I will accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vivekkohar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sRACIPE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sRACIPE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
