### ISSUE TITLE
profileplyr

### ISSUE THREAD

**Issue by dougbarrows** [Bioconductor/Contributions#1069]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RockefellerUniversity/profileplyr

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ThomasCarroll** [comment]
Would it be possible to get some advice on why we are timing out? When running the same command as in the build report, the package gets through both check and BiocCheck in a combined 4 minutes and 45 seconds, yet we are consistently going over the 10 minute limit in the submission check. We have made substantial improvements to reduce the size and speed of the examples and the vignette leading to reductions in check time on our local machines, but the time in our submissions has actually gone up (compare v0.99.2 build to v0.99.5). We wanted to check before we begin to cut the examples/vignettes further, and any guidance would be greatly appreciated. Thank you.

**Comment by lshep** [comment]
Have you set up your system to use the latest R-devel along with the R check environment as mentioned in the [package guidelines](http://bioconductor.org/developers/package-guidelines/#checkingenv)

**Comment by ThomasCarroll** [comment]
hi, 
Thank you for reply. 
Yes, we have been using development and  R check environment as per guidelines. This gives us a check just now was  for around 4:20 minutes on our machines. 
Any suggestions would be super helpful?

**Comment by lshep** [comment]
It seems to have resolved itself somewhat -  the check times are still high and when I did a check locally on my Ubuntu machine I'm getting somewhere around 7 min as well -  Please try and reduce.

**Comment by ThomasCarroll** [comment]
We have worked to further reduce our check times and have now reduced our times substantially (at least locally following guidelines). I can not align the timings in this build with what we see locally so not sure what we can improve upon now. 
Would it be possible to take a look to see if there is something we can do? 
thank you for any help

**Comment by lshep** [comment]
Yes I will continue with a review of the package - I should be able to get to in within the next week.

**Comment by ThomasCarroll** [comment]
Thank you in advance for your review. We look forward to working to address any comments and incorporate as required.

**Comment by lshep** [comment]
**General**
It seems you have made changes to your package but when I just tried to clone and build locally it now ERROR's. 

```
Quitting from lines 612-643 (profileplyr_vignette.Rmd) 
Error: processing vignette 'profileplyr_vignette.Rmd' failed with diagnostics:
The length of the 'extra_anno_color' argument for the 'GRoverlap_names' column is not the same length as the number of discrete names in that column of the range metadata.
--- failed re-building ‘profileplyr_vignette.Rmd’
```

My guess if you did a version bump as indicated above this would reproduce this
ERROR. 


**Build report**
- [ ] Perform a version bump for a recent build report. Please sure it can build/check without ERROR/WARNING

**Description**
- [ ] Please remove `LazyData: true`, we have rarely found this useful and can actually slow down installation. 


**NEWS**
- [ ] Either populate the NEWS file in the correct format as described in `?news`  or remove but do not include empty.

**inst/extdata**
- [ ] If you have an `inst/extdata` please also include `inst/scripts` that has files describing how the data in inst/extdata was generated. These can be code, sudo code, or text files but should include source information and relevant preprocessing

**vignette**
- [ ] Optional, but I suggest renaming. In is much more intuitive for a user to type in R `vignette('profileplyr')` rather than `vignette('profileplyr_vignette')`
- [ ] won't evaluate the rest of the vignette until the package can build/install

**Comment by ThomasCarroll** [comment]
Thank you for your comments. We have worked to address the points raised and we address them below.  

>General
>It seems you have made changes to your package but when I just tried to clone and build locally it ?>now ERROR's.

We were working to reduce our build times by reducing our sets and this led to us failing to build vignette. We have changed the part of vignette which caused this so the number of colors specified match the smaller number of data points.

> Build report

> Perform a version bump for a recent build report. Please sure it can build/check without ERROR/WARNING

We have bumped the version and now pass Build and Check with "OK".  Our remaining warning comes from Build Bin.

> Description

>Please remove LazyData: true, we have rarely found this useful and can actually slow down >installation.
We have removed LazyData: true from Description.

> NEWS

>Either populate the NEWS file in the correct format as described in ?news or remove but do not  >include empty.

We have added information to NEWS file. 

>inst/extdata

 >If you have an inst/extdata please also include inst/scripts that has files describing how the data in >inst/extdata was generated. These can be code, sudo code, or text files but should include source >information and relevant preprocessing

We have added description file to scripts directory of how we have generated the data in extdata directory. This contains links to our workshop where we have code working from the fastq data in Encode.

>vignette
>Optional, but I suggest renaming. In is much more intuitive for a user to type in R >vignette('profileplyr') rather than vignette('profileplyr_vignette')
 >won't evaluate the rest of the vignette until the package can build/install

We agree and have updated the name of vignette to profileplyr.

Thank you again for taking the time to review and we ask for a re-review of the updated package.

**Comment by ThomasCarroll** [comment]
hi,

I have checked in a fix into development branch of soGGi package (1.15.2) last night to remove a warning from loading the soGGi package which i think was causing our Build Bin warning here in profileplyr.

e.g. tokay2 BUILD SRC output for profileplyr

>Warning: replacing previous import 'ggplot2::Position' by 'BiocGenerics::Position' when loading 'soGGi'

As i haven't made any changes to profileplyr (only changes made to soGGi), i haven't bumped version here to get another build but please let us know if we should.

thanks again

**Comment by lshep** [comment]
Thank you.  Here are some further comments. 

**Vignette**
- [ ] I see behind the scenes you export and then unlink.  Please instead write
to a tempdir/tempfile that would be cleaned upon closure of the R session. If
the function export_deepToolsMat does not allow for control of where the file is
written this should be updated. 


**R code**

- [ ] Try to eliminate redundant code whenever possible. Example: it seems like
  this code is called twice without any modifications to it or elements in it.
  Can it be relocated to only be evoked once.  line 63  (and then again 89)
```
    metadata(tempDou)$info <- metadata(x)$info
    
    metadata(tempDou)$info$group_boundaries <- c(which(!duplicated(mcols(tempDou)$dpGroup))-1,length(mcols(tempDou)))
    metadata(tempDou)$sampleData <- metadata(x)$sampleData
    metadata(tempDou)$rowGroupsInUse <- metadata(x)$rowGroupsInUse
    
    x <- new("profileplyr", tempDou,params=x@params,
             sampleParams=x@sampleParams,
             sampleData=x@sampleData)

```
It seems like it might be possible to move this call after the i/j subsetting to
envoke once? It is always best to try to have concise and simplified
code. Repeated code also means if there is a bug in one you have to remember to
fix it everywhere itstead of one location. 

- [ ] Again with export functions make sure a user can specifiy where they want
  to output to. 
- [ ] Your export function seems to default to overwriting, maybe you would want
  to give the user this option or at least warn if they were going to overwrite
  and existing file? 

- [ ] annotateRanges. Does there need to be a check if TxDb is NULL or not
  valid? It seems like in the assignment of orgAnn you are assumming TxDb is a
  character but when below is seems like it could be other formats? 

- [ ] Again try and eliminate redundent code by creating helper functions and
  then calling when appropriate. Ex.  587/822
  Even the code in separateDuplicates==TRUE is the same except for using
  `GRanges_names` vs `gene_list_names` it would be better to make a function
  that could pass this in as an argument and reuse the overlapping code. Similar
  for separateDuplicates == FALSE.  It will make the code short, more precise,
  easier to maintainer.  

- [ ] Remove commented out code 725/954.  An excellent example too of why code should not be duplicated. This now needs to be changed in two locations instead of one. If you find a bug in the code that has been reutilized, you have to change in all locations.  

Generally the package is in good shape but please try to eliminate all the redundant code. It is not good practice to have so many lines of duplicated code.  Please comment back here with what has been updated and when you are ready for another re-review.

**Comment by dougbarrows** [comment]
Thanks for your feedback. We have addressed your points below.

> Vignette
> 
>   I see behind the scenes you export and then unlink. Please instead write
> to a tempdir/tempfile that would be cleaned upon closure of the R session. If
> the function export_deepToolsMat does not allow for control of where the file is
> written this should be updated.
> R code

The files that were exported and unlinked are now written to a tempdir.


>  Try to eliminate redundant code whenever possible. Example: it seems like
> this code is called twice without any modifications to it or elements in it.
> Can it be relocated to only be evoked once. line 63 (and then again 89)
>     metadata(tempDou)$info <- metadata(x)$info
>     
>     metadata(tempDou)$info$group_boundaries <- c(which(!duplicated(mcols(tempDou)$dpGroup))-1,length(mcols(tempDou)))
>     metadata(tempDou)$sampleData <- metadata(x)$sampleData
>     metadata(tempDou)$rowGroupsInUse <- metadata(x)$rowGroupsInUse
>     
>     x <- new("profileplyr", tempDou,params=x@params,
>              sampleParams=x@sampleParams,
>              sampleData=x@sampleData)
> 
> 
> It seems like it might be possible to move this call after the i/j subsetting to
> envoke once? It is always best to try to have concise and simplified
> code. Repeated code also means if there is a bug in one you have to remember to
> fix it everywhere itstead of one location.

We have created a constructor function for the profileplyr object to eliminate redundant code. We have also eliminated parts of the object that were duplicated.

>   Again with export functions make sure a user can specifiy where they want
> to output to.

The user is able to specify the path to the directory that they would like to output to in the export_deepToolsMat using the 'con' argument.

>   Your export function seems to default to overwriting, maybe you would want
> to give the user this option or at least warn if they were going to overwrite
> and existing file?

The export function will now stop if it is about to overwrite an existing file, and will only do so if the newly added 'overwrite' argument is set to TRUE.

>   annotateRanges. Does there need to be a check if TxDb is NULL or not
> valid? It seems like in the assignment of orgAnn you are assumming TxDb is a
> character but when below is seems like it could be other formats?
> 

We have added a check at the beginning of the function requiring the user to make TxDb a valid entry if it is NULL.

>   Again try and eliminate redundent code by creating helper functions and
> then calling when appropriate. Ex. 587/822
> Even the code in separateDuplicates==TRUE is the same except for using
> GRanges_names vs gene_list_names it would be better to make a function
> that could pass this in as an argument and reuse the overlapping code. Similar
> for separateDuplicates == FALSE. It will make the code short, more precise,
> easier to maintainer.

Two helper functions (subset_GR_GL_common_top and inherit_group_function)were added to reduce the amount of redundant code in the subsetbyRangeOverlap and subsetbyGeneListOverlap functions.

>  Remove commented out code 725/954. An excellent example too of why code should not be duplicated. This now needs to be changed in two locations instead of one. If you find a bug in the code that has been reutilized, you have to change in all locations.

We have removed unnecessary commented code.


Thanks again for your input - these changes have improved the code and the package. We appreciate your time, and look forward to another review.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dougbarrows.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("profileplyr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/profileplyr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
