### ISSUE TITLE
NBAMSeq

### ISSUE THREAD

**Issue by reese3928** [Bioconductor/Contributions#1073]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reese3928/NBAMSeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by reese3928** [comment]
Hi @Kayla-Morrell ,

Thanks very much for your review. We have addressed all of your comments and the package is ready for re-review. Here is our point-by-point response to your comments.

## DESCRIPTION
**SUGGESTION: We strongly encourage the addition of 'BugReports:' field with a relevant link to a GitHub for reporting Issues.**
- We have included the URL field and BugReports field in the DESCRIPTION file.

## vignette
**CLARIFICATION: Line 150, is there a reason you set this as eval = FALSE?**
- We have changed this as `eval = TRUE`. Previously we set this as `eval = FALSE` to meet the R CMD build time limit requirement. But it turns out that this option does not have a very huge impact on R CMD build time, so we set this as `eval = TRUE`.

## man pages
**makeExample**
**REQUIRED: For 'Description' capitalize the first letter of the sentence.**
- Thanks for pointing out this typo, we have capitalized the first letter of the sentence.

**NBAMSeq-methods**

**SUGGESTION: When looking up this man page, it is not clear what each sentence is referring to in the 'Description'. Could you make this clearer? Same with the return values. Maybe adding something like "For getDesign()...", "For getsf()...", that way the user knowns which description and return value is associated with which method.**

- Thanks for your suggestion, we have included "For `getDesign()`...", "For `getsf()`..." in the 'Description', 'return' and 'examples' to make it more clear for the users.

**NBAMSeqDataSet-class**
**CLARIFICATION: The only slot that is documented is 'design', is this correct?**
- Yes, because in our class `design` is the only extra slot compared to `SummarizedExperiment`.

**SUGGESTION: You might consider adding in a reference for this man page since you talk about how it is inherited from 'SummarizedExperiment'.**
- Thanks for you suggestion. We have included the reference for this man page.

## R code
**REQUIRED: AllClasses.R, line 185 should not use direct slot access with '@' but use an accessor method instead.**
- We totally understand that direct slot access with '@' is not acceptable. However, this '@' happens when we are creating the accessor method. We used '@' when creating the accessor `getDesign`. `getDesign` itself is an accessor method. Just to clarify, do you mean we should use `slot` instead of '@' ?


We look forward to hearing from you.

Sincerely,
Xu Ren

**Comment by Kayla-Morrell** [comment]
Hello @reese3928,

Thank you for all the work done on this package. I have looked over the changes made and everything looks good. In regards to the last requirement in *AllClasses.R*, this was my mistake and no change needs to be made. 

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/reese3928.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NBAMSeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NBAMSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
