### ISSUE TITLE
CopyNumberPlots

### ISSUE THREAD

**Issue by bernatgel** [Bioconductor/Contributions#1076]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bernatgel/CopyNumberPlots

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by bernatgel** [comment]
Hi @Liubuntu 

I've been trying for a few hours to reduce the time taken by check on windows to remove the last Warning. I've even removed whole sections of the vignette to try to improve it. I've timed the process in my machine and it's 30seconds for vignette + examples (the part I can reduce) and 2minutes 50seconds for the rest, where I don't know how to act. Any idea on how to reduce the check time in windows? Do you think we can start the review process even with that warning still present?

Thanks

Bernat

**Comment by Liubuntu** [comment]
Hi @bernatgel , 

Generally we'll suggest to reduce the size of the data used in the example and vignette so that they are just big enough to show the functionalities. 

Yes, please try the above and see if warning would go away, and I can at the same time proceed with the reviewing. 

Best,
Qian

**Comment by bernatgel** [comment]
HI @Liubuntu 

We have reduced the size of some of the example files and it now passes on windows without warnings. However, a problem with the builders is causing warnings and timeouts in linux and mac.

I'll wait a day or two do a version bump to trigger a rebuild to see if the situation has improved.

Thanks

Bernat

**Comment by Liubuntu** [comment]
Hi @bernatgel , 

Please see below for the initial review. Mostly are minor issues. Please try to address all or most of them, and comment back with any questions. Note that the deadline for accepting new packages to release would be next Wednesday (April 24th, 2019). So please try to make updates soon so we can proceed with the acceptance. 

Cheers,
Qian 

## DESCRIPTION

- Consider adding these automatically suggested biocViews: Sequencing,
      DNASeq, ChIPSeq, MethylSeq as appropriate.

## NAMESPACE

- Looks good.

## NEWS
- Please add a `NEWS` file in the top directory, so your package news
      will be included in Bioconductor release announcements. You can
      leave it blank for the first version.

## unit tests
- Consider adding unit tests. We strongly encourage them. See
  [here](http://bioconductor.org/developers/how-to/unitTesting-guidelines/)
  for more details.

## R/
- remove `detectBAFClusters.R` since it has only commented code.
- remove `loadCopyNumberCalls.ASCAT.R` for the same reason as above.
- since most of your documentations are identical between those
  `loadCopyNumberCalls.*.R` functions, try use `@inheritParams` to
  avoid repeats. Check [here](http://r-pkgs.had.co.nz/man.html#dry2)
  for more details.
- Similar in `plotBAF` and `plotLRR`. And check other similar cases.
- Function names should avoid using '.'. See
  [here](https://www.bioconductor.org/developers/how-to/coding-style/)
  for more details.
 ```
  Function names

  Use camelCaps: initial lower case, then alternate case between words.
  Do not use ‘.’ (in the S3 class system, some(x) where x is class A will dispatch to some.A).
  Prefix non-exported functions with a ‘.’.
```
## man/
- SUGGESTION: as said above, use `@inheritParams` to avoid repeating.

## vignette

- After the Introduction, add a "Installation" section to show to
  users how to install the package as if it has been included in
  Bioconductor. Because new packages is going to be in Bioc devel,
  they are required to use `BiocManager` for downloading the
  package. You should include something like this:

```
1. Download the package from Bioconductor.
{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```
- SUGGESTION: Add more details about the authors, e.g., affiliation.

- L160: typo in `segmnet.value`? was it supposed to be `segment.value`?
- L287: typo in `specilized`.
- L319: typo in `fucntions`.
- L390: typo in `specifica`.
- L471: typo in `kpPlotCopyNumberCalls`. Should be just `PlotCopyNumberCalls`.
- L543: typo in `accumulatoion`.

**Comment by bernatgel** [comment]
Hi @Liubuntu 

Thanks for your review. We have applied most of the changes you requested or suggested. Here's a description of the changes:

- BiocViews: Added Sequencing and DNASeq. I don’t think the other would apply.
- NEWS: Added an empty NEWS file
- Unit tests: We plan adding them in the near future but we cannot make a good testing suite in time for the release
- Empty functions: Removed the commented out functions
- inheritParams: The documentation is actually not identical, since it includes the default value, which is different in some of the functions. We decided not to use any inheritParams in these functions to make it more manageable in the future
- inheritParams in plotLRR: plotLRR now inherits params from plotBAF
- functions with . in name: The name of these functions have been changed
- Vignette: An Installation section has been added to the vignette.
- Fixed all typos. Thanks for reporting them! :)

Do you think is there anything else needed?

Thanks

Bernat and Míriam

**Comment by Liubuntu** [comment]
Hi @bernatgel , 

The updates look good. Please correct the following and we are good to go: 

vignette/CopyNumberPlots.Rmd

- Please replace the `pkgName` and `githubUserName/pkgname` with your own package name and github info. 

Best,
Qian

**Comment by bernatgel** [comment]
Doh! Sorry about that!

Fixed! 

Thanks for the review :)

**Comment by Liubuntu** [comment]
Hi @bernatgel , 

Thanks for the quick fix. The package is accepted for the Bioc 3.9 release. 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bernatgel.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CopyNumberPlots")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CopyNumberPlots

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
