### ISSUE TITLE
DiscoRhythm

### ISSUE THREAD

**Issue by matthewcarlucci** [Bioconductor/Contributions#1078]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/matthewcarlucci/DiscoRhythm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Is there any interoperability with [standard Bioconductor data representations][1]? Please make sure that each of the functions you expose to the user are able to handle relevant data structures, especially (as appropriate) GenomicRanges and SummarizedExperiment. I see that your vignette includes several figures, but no actual code. Please revise your vignette so that it actually performs the calculations that your package provides. This is both an essential check that your package functions as advertised, and an essential guide to how your package is supposed to be used.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by matthewcarlucci** [comment]
Dear Reviewers,

Thank you @mtmorgan for the suggestion to add support for SummarizedExperiment objects in usage of the relevant functions. We have added this functionality such that other packages using SummarizedExperiments will be suitable for the DiscoRhythm functions. We have also provided accommodation functions to import tabular data as SummarizedExperiment for analysis in native R (i.e. migrating from shiny application to R), and export SE objects as tabular data for interactive usage in our shiny application. 

The originally submitted vignette contains runnable R code for all exported functions (section 5) with additional details on the methodology provided in section 4. In this version, we have updated the vignette to reflect the added support for SummarizedExperiment.

Regards,
Matt

**Comment by dvantwisk** [comment]
I've reviewed your package and it looks excellently written. I only have one suggestion for you to consider. Please message me back when you are finished making change and would like me to accept the package.

R/QC.R
- [ ] [CONSIDER] L120: Use `match.arg()` to declare `thresh_type`. In the
funtion declaration of `discoInterCorOutliers()`, `thresh_type` can be
declared with `thresh_type = c("SD", "value")`. The first option, `"SD"`
will be the default option. In the function the value of thresh_type that
the user chooses can be obtained with `thresh_type = match.arg(thresh_type)'.
Using `match.arg()` is generally better since it allows the possible values 
of `thresh_type` to be explicitly stated in the function declaration. Also
`match.arg()` will throw an error if the user selects an option not listed in
`thresh_type`'s declrartion in the function declaration. It seems that
`match.arg()` can be used in other parts of the package.

**Comment by matthewcarlucci** [comment]
The comment has been addressed and match.arg is utilized where relevant to neatly restrict argument values. We have also identified and fixed a few bugs. Thank you for the comment and for reviewing our package @dvantwisk.

Our understanding is that updates can be made up to April 26th for all packages for the 3.9 release. Is this true also for newly accepted packages? We are ready for the package to be accepted in either case.

**Comment by dvantwisk** [comment]
Yes, updates should be added by April 26th. Since you changes you made to the package look good, I am going to move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/matthewcarlucci.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DiscoRhythm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DiscoRhythm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
