### ISSUE TITLE
StructuralVariantAnnotation

### ISSUE THREAD

**Issue by d-cameron** [Bioconductor/Contributions#1079]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PapenfussLab/StructuralVariantAnnotation

Confirm the following by editing each check box to '[x]'

- [ X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X ] The 'devel' branch for new packages and features.
- [ X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by d-cameron** [comment]
Hmm. What's the best way to proceed when my package builds without error/warning when build against release dependencies, but is failing in devel due to dependencies? In this case, a test/example VCF parses in release, but I get a `invalid class "VCFHeader" object: 'info(VCFHeader)' must be a 3 column DataFrame with names Number, Type, Description` when I call `VariantAnnotation::readVcf()` in the vignette.

**Comment by hpages** [comment]
Hi @d-cameron ,

Thanks for this submission.

Please focus on BioC devel. There has been major changes to Rsamtools and VariantAnnotation between BioC 3.8 (release) and 3.9 (devel) that could explain these differences. Also let's ignore Windows for now: there is a known Windows-specific issue with the latest Rsamtools and VariantAnnotation in devel that is still under investigation.

Best,
H.

**Comment by lawremi** [comment]
The overlap functionality could greatly benefit from using features of the Hits objects, instead of reducing to data.frames and resorting to dplyr. For example, in `findBreakpointOverlaps()`, comments mention that `duplicated(hits)` takes too much memory. Is that just because hits is a data.frame? The `duplicated,Hits()` method is very efficient. I think `intersect(x_hits, partner_hits)` would be a better approach.

**Comment by d-cameron** [comment]
@lawremi that also had the advantage of the of the return type matching `findOverlaps()` which is a nicer design so I've refactored that code.

Attempting to do the obvious and concat the two hits objects fails with `S4Vectors::c()` fails with the error:
```
Error in validObject(ans) : 
  invalid class “SortedByQueryHits” object: 'queryHits(x)' must be sorted
```
Is this something I should raise an issue for? I would have expected either a zipper merger returning a SortedByQueryHits, or the return class to be demoted to `Hits` since the concatenated sequences are not in order.

Judging by performance in profvis, neither `intersect()` nor `duplicated()` have any optimisations for the sorted nature of the `SortedByQueryHits` returned by `findOverlaps()` (which is somewhat strange given that `duplicated()` requires the Hits to be queryHits sorted). `intersect()` so I just went with `intersect` as it's actually the operation that I'm attempting to perform.

**Comment by jackieduckie** [comment]
Hi @lawremi @hpages , we have made changes on examples, vignettes and test files to address the last timeout/warning issue. It now passes on windows but remains checktime > 10min on linux and osx.  The check time on my local mac machine is ~4min. We will try and improve the issue further, but meanwhile, could we proceed with the review with the timeout warning present?

Thanks,
Ruining

**Comment by hpages** [comment]
Hi @d-cameron ,

Glad to see that StructuralVariantAnnotation finally builds and passes check with no timeout or error on all platforms. I took a first look at the package and have some feedback. See below.

Best,
H.

### General

1. I'm surprised by your choice to use a _breakpoint GRanges_ (i.e. a GRanges object with a `partner` metadata column) to represent a set of structural variants with 2 breakends. The natural choice for representing _compound genome features_ in Bioconductor (a.k.a. _disjoint genome features_ in bedtools terminology) is to use a GRangesList object. For example, loading a BEDPE file in a GRangeList object can simply be done with:
    ```
    library(StructuralVariantAnnotation)
    bedpe.file <- system.file("extdata", "gridss.bedpe", package = "StructuralVariantAnnotation")
    pairs <- rtracklayer::import(bedpe.file)
    names(pairs) <- mcols(pairs)$name
    mcols(pairs)$name <- NULL
    mcols(first(pairs)) <- mcols(second(pairs)) <- mcols(pairs)
    grl <- zipup(pairs)
    grl
    # GRangesList object of length 2:
    # $gridss2o 
    # GRanges object with 2 ranges and 1 metadata column:
    #       seqnames    ranges strand |     score
    #          <Rle> <IRanges>  <Rle> | <numeric>
    #   [1]     chr1  18992158      + |        55
    #   [2]    chr12  84963533      - |        55
    # 
    # $gridss39o 
    # GRanges object with 2 ranges and 1 metadata column:
    #       seqnames  ranges strand |  score
    #   [1]    chr12   84350      - | 627.96
    #   [2]    chr12 4886681      + | 627.96
    #
    # -------
    # seqinfo: 2 sequences from an unspecified genome; no seqlengths
    ```
    It's easy to extract the 1st and 2nd genomic loci from this kind of object:
    ```
    unlist(heads(grl, n=1))
    # GRanges object with 2 ranges and 1 metadata column:
    #             seqnames    ranges strand |     score
    #                <Rle> <IRanges>  <Rle> | <numeric>
    #    gridss2o     chr1  18992158      + |        55
    #   gridss39o    chr12     84350      - |    627.96
    #   -------
    #  seqinfo: 2 sequences from an unspecified genome; no seqlengths
    
    unlist(tails(grl, n=1))
    # GRanges object with 2 ranges and 1 metadata column:
    #             seqnames    ranges strand |     score
    #                <Rle> <IRanges>  <Rle> | <numeric>
    #    gridss2o    chr12  84963533      - |        55
    #   gridss39o    chr12   4886681      + |    627.96
    #   -------
    #   seqinfo: 2 sequences from an unspecified genome; no seqlengths
    ```
    Generally speaking, it's easier to work with this kind of object than with a _breakpoint GRanges_. I would strongly suggest that you consider using this instead of _breakpoint GRanges_ objects for representing structural variants with 2 breakends.

2. I would have expected that calling `breakpointgr2bedpe()` on the _breakpoint GRanges_ returned by `bedpe2breakpointgr()` would work:
    ```
    breakpointgr2bedpe(bedpe2breakpointgr(bedpe.file))
    # Error in data.frame(chrom1 = GenomeInfoDb::seqnames(gr), start1 = start(gr) -  : 
    #   arguments imply differing number of rows: 4, 0
    ```

3. A common practice is to document opposite functions like `bedpe2breakpointgr()` and `breakpointgr2bedpe()` in the same man page. If for whatever reason you prefer to keep them in separate man pages, at least the 2 man pages should be cross-linked via a `\seealso` section in each page.


### Vignette

4. The code chunk in the Installation section shows how to _install_ the package, not how to _load_ it. However the text above the code chunk says:
    ```
    The StructuralVariationAnnotation package can be loaded from Bioconductor as follows:
    ```
    So it would need to be modified to say something like:
    ```
    The StructuralVariationAnnotation package can be installed from Bioconductor as follows:
    ```

5. Instead of:
    ```
    Details of `VCF` objects can be found by `browseVignettes("VariantAnnotation")`.
    ```
    please consider saying something like:
    ```
    More information about VCF objects can be found by consulting the vignettes in
    the VariantAnnotation package (with `browseVignettes("VariantAnnotation")`).
    ```

6. Maybe it would be worth pointing the reader to some fields of interests (e.g. `MATEID`, `SVTYPE`, etc...) after displaying the `vcf` object, and maybe to comment some of these fields.

7. Your `findBreakpointOverlaps()` and `countBreakpointOverlaps()` examples (in the "Exploring breakpoints" section) produce no overlaps so are not illustrative. Also please note that `findBreakpointOverlaps()` returns a Hits object, not a matrix.

8. Please remove the parentheses in `Alternatively, plotting package such as ggbio() provides...` (ggbio is a package, not a function).

9. This code:
    ```
    region.gr <- gr[2:3,] %>% dplyr::mutate(end=end+5) %>% dplyr::mutate(start=start+5)
    ```
    is unnecessarily complicated and hard to read. The same can be achieved with just:
    ```
    region.gr <- shift(gr[2:3,], 5)
    ```
    In addition to being more readable, the `shift()` solution is also more efficient (36x faster on my laptop):
    ```
    library(microbenchmark)
    gr0 <- gr[2:3]
    microbenchmark(gr0 %>% dplyr::mutate(end=end+5) %>% dplyr::mutate(start=start+5), shift(gr0, 5))
    # Unit: milliseconds
    #                                                                            expr
    #  gr0 %>% dplyr::mutate(end = end + 5) %>% dplyr::mutate(start = start +      5)
    #                                                                   shift(gr0, 5)
    #        min        lq      mean    median        uq       max neval
    #  60.207715 62.678722 64.550741 64.024463 64.970522 92.749330   100
    #   1.435635  1.739248  1.761021  1.750163  1.779301  1.963865   100
    ```

10. Similar problem with this code:
    ```
    gr.circos <- gr %>% mutate(to.gr=GRanges(seqnames(partner(gr)),ranges(partner(gr))))
    ```
    This is better done with:
    ```
    gr.circos <- gr
    mcols(gr.circos)$to.gr <- granges(partner(gr))
    ```
    Using `granges(partner(gr))` instead of `GRanges(seqnames(partner(gr)),ranges(partner(gr)))` also has the benefit to preserve the strand.

11. Spelling:
    - `from a number of popular caller` (caller**s**)
    - `We can then plot the breakpoints agains referece genomes` (agains**t**, refere**n**ce)

**Comment by d-cameron** [comment]
> 1. I'm surprised by your choice to use a _breakpoint GRanges_ (i.e. a GRanges object with a `partner` metadata column) to represent a set of structural variants with 2 breakends. The natural choice for representing _compound genome features_ in Bioconductor (a.k.a. _disjoint genome features_ in bedtools terminology) is to use a GRangesList object.

This is actually a core reason why I'm submitting this package: all four existing pair-of-genomic-coordinate data structures in BioConductor have two parallel first-in-pair and second-in-pair structures of the same type (GRanges or something convertible to this). When doing SV analysis, I found these formats quite painful to deal with as it results in a whole lot of code duplication as the vast majority of SV annotation that one actually uses is actually breakend-level annotations.

Fundamentally, there is no intrinsic 'first' and 'second' breakend for a breakpoint - both have equal weighting and the choice of which breakend gets allocated to the first is arbitrary. I believe that arbitrarily grouping break-ends into two different subsets is the incorrect abstraction. Two variants that disrupt TP53 with identical breakend position and orientation should not have to be treated differently just because the partner of one of the occurs 'before' TP53 and the other occurs 'after'.

The GRanges approach is the closest data structure match to SV record in VCF BND notation. I've advocated strongly for the BND format in the GAG4H file formats working group (of which I am a member) as I've found that the 'traditional' VCF symbolic allele `SVTYPE`s (`DEL`, `INS, `DUP`, ...) are only useful for extremely simple analysis and as soon as you start delving into more complicated analysis, you end up converting everything to breakend-focused BND-like notation.

The second reason I have chosen this format is that is more naturally support single breakend variants (as defined on Section 5.4.9 of the [VCF specifications](https://samtools.github.io/hts-specs/VCFv4.1.pdf)). The data structure chosen for this package allows both breakpoint variants and single breakend variants to be combined with minimal hacks - a `NA` partner is way easier to deal with than missing elements in a second-in-pair data structure.


Examples of use cases that are more naturally represented in a GRanges object that I have actually implemented in my variant projects include:

- Variants calls composed of both breakpoints and single breakends (e.g. as produced by [GRIDSS](https://github.com/PapenfussLab/gridss))
- Breakend-level annotations.
  - Gene overlap/annotation
  - Closest gene
  - variant allele fraction. A SV can be het at one breakend and hom at the other. Formats such as BEDPE require a pairing of var1, var2 (or some equivalent notation) to encode these paired breakend-level values.
  - Many many others. In the clinical cancer sequencing pipeline I've been involved in, our SV table has 17 breakend-level annotations, and only 7 break-point level annotations.
- Parsing SV in VCF BND notation
  - VCF BNDs are intrinsically breakend-level
- SV deduplication
  - downstream of this package, I have code that compares the sequence of SV which have the same/similar breakend on one side. SV callers will call multiple SVs when one side occurs in a repeat. Two variants A<->B and A<->C may actually be a single SV represented multiple times if B and C have (almost) the same sequence.
- Chaining of SV
  - Logic such as 'Find candidate SV paths if traversing from SV into chr1:400+' would duplicate code to check the firsts and the seconds.
- Identifying Transitive calls 
  - A complex compound SV involving A<->B<->C will have SV callers reporting A<->C if the B segment is short. The logic for identifying these is very similar to that of SV chaining.
- findOverlaps()
  - findBreakpointOverlaps() need to report not only which breakpoints match, but which of the constituent breakends are the matching ones. This is particularly important for foldback inversions where a breakpoint-level match (e.g. gridss2o matches gridss39o in your example) followed up a naive breakend overlap check can give the wrong answer (since both breakends can overlap).


> It's easy to extract the 1st and 2nd genomic loci from this kind of object:

In the three years since I first developed this package, the only time I've ever wanted to extract a set of first or second genomic loci has been when having to flatten for export to a format. All the actual work has been symmetrical in that every breakend is treated equally with no intrinsic separation.


>I would have expected that calling breakpointgr2bedpe() on the breakpoint GRanges returned by bedpe2breakpointgr() would work:

Compatibility with rtracklayer's notation sounds like it would be a good idea. I'll look into replacing these functions with data conversions to/from the GRangeList of pairs used by rtracklayer which means this package won't have to worry about BEDPE import/export. Interoperability with existing BioConductor notations is definitely a desirable feature.

> Your findBreakpointOverlaps() and countBreakpointOverlaps() examples (in the "Exploring breakpoints" section) produce no overlaps so are not illustrative.

I've replaced this with an simplified example of the comparison logic I used for my SV caller benchmarking paper.

> Also please note that findBreakpointOverlaps() returns a Hits object, not a matrix.

We made this change due to feedback from @lawremi but didn't update all our documentation. Sorry about that.


Thanks for the review. I'm hoping to complete the changes addressing all points within the next couple of days.

**Comment by hpages** [comment]
Hi @d-cameron ,

Thanks for the feedback. Before you discard my suggestion of using a GRangesList object, I want to make sure that there is no misunderstanding.

About this: "all four existing pair-of-genomic-coordinate data structures in BioConductor have two parallel first-in-pair and second-in-pair structures of the same type (GRanges or something convertible to this)."

I'm not proposing to use a GRangesList object with two parallel first-in-pair and second-in-pair GRanges. What I'm proposing is to use a GRangesList object **with one list element per breakpoint**. In other words it's not about forming 2 groups (1 with the first breakends and 1 with the second breakends), it's about forming 1 group per breakpoint. See the `grl` object from my initial feedback. It has 2 list elements, 1 for the gridss2o breakpoint, and 1 for the gridss39o breakpoint. Each list element is a small GRanges object containing the 2 breakends. So the breakends are not arbitrarily grouped into two different subsets. Furthermore, the number of breakends for each breakpoint is not enforced and could be anything. This means that you can combine both breakpoint variants and single breakend variants in the same object. You could imagine storing breakpoint variants with 3 or more breakends if such thing make sense.

About your concern that "the vast majority of SV annotation that one actually uses is breakend-level annotations": Please note that GRangesList objects support top-level annotations (`mcols(grl)`) as well as inner annotations (`mcols(grl, level="within")`). This allows one to annotate at the breakpoint and/or breakend level. For example the `grl` object from my initial feedback is annotated at the breakend level (`score` inner metadata column -- even though it could be that the score should be considered a breakpoint attribute rather than a breakend attribute so would be better stored at the breakpoint level). You don't have the ability to easily annotate at the 2 levels (breakpoint and breakend) with a flat `breakpoint GRanges` object.

Another major advantage of the GRangesList approach is that it makes the grouping more robust. With the flat `breakpoint GRanges` approach it's easy for a breakend to loose its partner e.g. when the user subsets the object or accidentally removes its names.

FWIW the GRangesList container was specifically designed for representing _compound genome features_ and was originally introduced to support the "exons grouped by gene" and "exons grouped by transcript" use cases (as returned by `GenomicFeatures::exonsBy(txdb, by="gene")` and `GenomicFeatures::exonsBy(txdb, by="tx")`, respectively). It has proven to be very convenient for this.

Hopefully this clarifies my proposal and addresses your concerns.

Best,
H.

**Comment by d-cameron** [comment]
>GRangesList container was specifically designed for representing compound genome features and was originally introduced to support the "exons grouped by gene"
> You could imagine storing breakpoint variants with 3 or more breakends if such thing make sense.

That actually does make quite a bit of sense as the current design does not handle breakpoints with multiple partners which are in the VCF specs (even if 0 tools use them)

The problem is that the GRangeList approach also wouldn't handle such events. If the list item has A, B, and C, there's no encoding which breakends correspond with which partners. Is it {AB, AC}, {AB, AC, BC}, or {AC, BC}? An data structure designed for exon lists doesn't quite work for this use case. There is a fundamental pairing of breakends within breakpoints and I've tried to take the middle ground of not splitting breakends into arbitrary first and second sets, but also keeping the pairing information (relatively) tightly coupled.

The other thing that is really annoying is that `findOverlaps()` ordinals are the list ordinals, not the row ordinals so you can't report which breakend corresponds with which breakend which breaks all the SV traversal use cases (or requires `findBreakpointOverlaps()` to report fundamentally different things than `findOverlaps()`).

> Another major advantage of the GRangesList approach is that it makes the grouping more robust.

The cost of GRanges notation does come with some brittleness inherit in the design. I've added in more aggressive checks and explicit error message so users know exactly why their breakpoint GRanges is breaking. Data inconsistences/unsupported notations are cleaned up/filtered on data loading but it's are not strongly at the time of data manipulation, merely when interacting with this package.

> With the flat breakpoint GRanges approach it's easy for a breakend to loose its partner e.g. when the user subsets the object

This is either a design flaw, or a feature depending on your use case. Filtering events to a subset of the genome is the typical operation where this occurs. Users will want to either retain or remove events that only have one breakend falling within the region of interest. For both GRanges and GRangesList designs, a simple filtering will result in the breakend that does not fall within the ROI to be remove but the other to be retained. The GRanges$partner approach causes subsequence breakpoint GRanges operations to throw a (now more friendly) error message. A GRangesList approach will silently convert the breakpoint into a single breakend which I think is definitely the wrong approach - we definitely should not change the type of event when filtering. In this situation I think a hard failure is better than a silent data corruption.

> accidentally removes its names

Names are absolutely essential to VCF BND notation so I suspect my experience with writing an SV caller than reports in BND notation has baised my design quite heavily towards a name-centric design.

>Before you discard my suggestion of using a GRangesList object
>You don't have the ability to easily annotate at the 2 levels (breakpoint and breakend) with a flat breakpoint GRanges object.

I agree that being able to annotate at both levels is indeed a significant feature.

My current plan of action is to try and get the (existing GRanges-centric) package to a state where (apart from your concerns with the core data structure), you're happy to pass review and accept the package by the deadline. I can see value in adding support for other notations in future releases and there's no reason why findBreakpointOverlaps() can't support `Pairs` and `GRangesList` notations in addition to the current one. In theory, mixed data structures could be supported and `findBreakpointOverlaps(grl, pairs)` would return the intuitive result and not an error.

Does that sound like a reasonable path forward to you?

**Comment by lawremi** [comment]
If this problem does require a new data structure, ideally it would be a formal class and serve as infrastructure for other packages operating on structural variants.

**Comment by d-cameron** [comment]
@lawremi I experimented with a formal class GRanges early on but decided against it since there were so many use cases where I just wanted it act exactly like a GRanges object (including all the GRanges manipulation methods that return a GRanges object) that I just went with using an actual GRanges object and adding optional pairing associations on top of it.

I valued playing nicely with existing ecosystem over the rough edges of building on top of GRanges. There's nothing stopping us creating a formal GRanges-like (derived?) class if this notational style gains traction. Apart from rtracklayer BEDPE loading, there's not really much of a precedent in the BioConductor ecosystem for handles arbitrary SVs. There's a some packages (e.g `instansv`, `chimeraviz`) that handle the trivially simple events (DEL/INS/DUP/INV) that can be represented as chr:start-stop, or do some visualisation, but unlike SVs/indels, I'm not aware of any packages that can do the analysis you'd want to be able to do for arbitrary SVs (e.g. gene disruption/fusion detection, breakpoint and event classification).

**Comment by d-cameron** [comment]
@hpages build now passing with your changes (hopefully) addressed.

**Comment by lawremi** [comment]
Extending GRanges a la VRanges (call it SVRanges?) might be a good idea.

**Comment by d-cameron** [comment]
@lawremi that would require adding hooks to everywhere that modifies a GRanges class so they also support the new class, correct? Wouldn't it be easier to modify GRanges itself to optionally track row pairings? Such as class would be useful in other context as well (e.g. `InteractionSet`).

**Comment by lawremi** [comment]
You can look at VRanges but basically it's not so bad, because GRanges is designed internally to be extensible. Many functions update the object without constructing a new GRanges instance.

**Comment by lawremi** [comment]
Actually maybe SVRanges should extend VRanges.

**Comment by d-cameron** [comment]
Unfortunately, many of `VRanges` columns are not appropriate/meaningful for arbitrary SVs.

**Comment by d-cameron** [comment]
>Actually maybe SVRanges should extend VRanges.

Unfortunately, most of the VRanges columns are not appropriate for arbitrary SVs so it's not a good fit. Even something as simple as equivalent of `refCount` and `altCount` are actually much more complicated for SVs (e.g. read pair support for smallish variants with either be wrong, or require a model to estimate the likelihood of a read pair coming from the ref or alt as the expected fragment size distributions overlap for small events).

> Many functions update the object without constructing a new GRanges instance.

Thinking it over, extending from `GRanges` (or `VRanges`) is problematic as it violates Liskov Substitution Principle - the proposed SVRanges class would either restrict the permitted operation (thus making operations that were valid on a `GRanges` not valid on the derived class), or if you allow the operations, be effectively the same as the `GRange` implementation that I've implemented (raising errors when the GRanges violates the breakpoint pairing constraints).

**Comment by hpages** [comment]
@d-cameron 

Yes that sounds like a reasonable path forward to me.

Some additional clarifications:

- As I said, GRangesList was specifically designed for representing compound genome features, not for "exon lists" in particular. The "exon lists" use case just happened to be the first use case supported by these objects.

- With the GRangesList approach, in the situation of a list element with A, B, and C, couldn't the encoding of which breakends correspond to which partners be achieved via a breakend-level metadata column?

- Yes `findOverlaps()` ordinals are the list ordinals and you want the row ordinals. But isn't it something that `findBreakpointOverlaps()` could handle e.g. by returning an annotated Hits object? You could make the valid point that maybe this feature belongs to the `findOverlaps()` method for GRangesList objects. I guess the reason we don't have it yet is that nobody asked for it so far. In the meantime, nothing prevents you from implementing it in `findBreakpointOverlaps()`.

- Finally a note about the Liskov Substitution Principle: Unfortunately real-world objects sometimes violate this principle. For example, `data.frame` inherits from `list` but you cannot change the length of one list element without breaking the object:
    ```
    df <- data.frame(aa=1:4, bb=letters[1:4])
    df[[1]] <- 1:3  # works on a list, but not on a data.frame
    # Error in `[[<-.data.frame`(`*tmp*`, 1, value = 1:3) : 
    #   replacement has 3 rows, data has 4
    ```
    We just have to live with that. There are many situations where it still makes sense to extend an existing class though, even if that means that the extended class supports a few less operations.

H.

**Comment by lawremi** [comment]
In many cases where the constraints would be broken by an exact endomorphism, one can just return the more general type. For example, `intersect,GRanges,GRanges()` always returns a GRanges instance, even if it receives a VRanges. 

Principles like the LSP are good guides, but the ultimate test is whether the software is more useful or not. VRanges has proven empirically useful.

**Comment by d-cameron** [comment]
>GRangesList was specifically designed for representing compound genome features
> With the GRangesList approach, in the situation of a list element with A, B, and C, couldn't the encoding of which breakends correspond to which partners be achieved via a breakend-level metadata column?

Which is essentially a `List` version for the `partner` implementation, which would have the same drawbacks that I have now. If we restrict ourselves to breakpoints and single breakend there's no problem and I don't currently have any plan to support A,B,C style variants as they're only used by a) multi-mapping aware callers that don't have widespread acceptance, or b) my variant caller 

GRangesList doesn't have this issue if it gets restricted to 


>Yes that sounds like a reasonable path forward to me.

We now have proposals for the package to also accept SVRanges, GRangeList, and Pairs objects. I'm not sure which (if any) need to be implemented now. Are there any blockers/required review changes that are preventing the acceptance of the package in its current form?


Thanks to both of you for the feedback and discussions.

**Comment by hpages** [comment]
@d-cameron If, as you said earlier, most of the VRanges columns are not appropriate for arbitrary SVs, extending it might not be suitable for your use case.

I don't think anybody suggested that the package should also accept Pairs objects.

I see that the last check by the automated single package builder was successful on all platforms. I'll take another look at the package later today and will let you know.

BTW you closed this issue. Was it intentional?

**Comment by d-cameron** [comment]
> BTW you closed this issue. Was it intentional?

It was not.

**Comment by hpages** [comment]
Hi @d-cameron 

Thanks for the changes.

There must have been a misunderstanding about item 2. I was only suggesting that `breakpointgr2bedpe(bedpe2breakpointgr(bedpe.file))` should work. This is a reasonable expectation for functions that have symmetric names, which suggests that they perform opposite operations. I was not suggesting that you get rid of `bedpe2breakpointgr()` and that you introduce the `breakpointgr2pairs()` / `pairs2breakpointgr()` combo. Exposing the intermediate Pairs representation has little value. Plus now you've lost the convenience of being able to go from `bedpe.file` to the _breakpoint GRanges object_ with a single function call.

A few more things:

12. Looks like you're using `tidyverse` in the vignette so the package needs to be added to the Suggests field. Note that you only need to load `tidyverse` once in the vignette. Furthermore AFAICS you only seem to be using the `ggplot2` and `dplyr` packages from the _tidyverse_. For the sake of minimizing package dependencies, it would be preferable to Suggest these 2 packages only instead of `tidyverse`. In the vignette it's better to load them right before you use them (i.e. right before generating the Precision-Recall and ROC curves).

13. Load the VariantAnnotation package before using it in the vignette, not after.

14. Use `library()` (or `require()`) consistently in the vignette, instead of a mix of both.

15. This code in the vignette:
    ```
    breakpointgr <- breakpointRanges(vcf)
    singleBreakendgr <- breakendRanges(vcf)
    gr <- c(breakpointgr, singleBreakendgr)
    ```
    concatenates `breakpointgr` with empty `singleBreakendgr` (both GRanges object). If that's intended, it deserves a comment. Ideally, an example where this concatenation is not a no-op would be more illustrative and would have more value. In particular it would show what happens to the `partner` metadata column and how the `breakpointgr` + `singleBreakendgr` blend is handled downstream.

16. "Once we know which calls match the truth set, it is relatively straight-forward to generate Precision-Recall and ROC curves for each caller."
    ```
    ggplot(as.data.frame(svgr) %>%
      dplyr::select(QUAL, caller, truth_matches) %>%
      dplyr::group_by(caller, QUAL) %>%
      dplyr::summarise(
        calls=n(),
        tp=sum(truth_matches > 0)) %>%
      dplyr::group_by(caller) %>%
      dplyr::arrange(dplyr::desc(QUAL)) %>%
      dplyr::mutate(
        cum_tp=cumsum(tp),
        cum_n=cumsum(calls),
        cum_fp=cum_n - cum_tp,
        Precision=cum_tp / cum_n,
        Recall=cum_tp/length(truth_svgr))) +
      aes(x=Recall, y=Precision, colour=caller) +
      geom_point() +
      geom_line() +
      labs(title="NA12878 chr22 CREST and HYDRA\nSudmunt 2015 truth set")
    ```
    That doesn't look straight-forward to me.

17. Please remove the parentheses in `ggplot2()` (`ggplot2` is a package, not a function).

H.

**Comment by d-cameron** [comment]
> There must have been a misunderstanding about item 2.
> Exposing the intermediate Pairs representation has little value. Plus now you've lost the convenience of being able to go from bedpe.file to the breakpoint GRanges object with a single function call.

Replacing the direct bedpe parsing with Pairs makes BEDPE parsing consistent with VCF parsing. Read/write of VCFs is performed entirely by `VariantAnnotation`, and with the Pairs functions, read/write of BEDPEs is performed entirely by `rtracklayer`. I feel that this is a cleaner design as the package is now consistent with how IO is handled and I'm no longer providing a parallel implementation of functionality already provided by `rtracklayer`.

**Comment by d-cameron** [comment]
> 12, 13, 14, 16, 17

Updated

> 15

I've added a real world (somatic COLO829) call set to the vignette and included a section on how to handle mixed single breakend/breakpoint GRanges. An added bonus is that the circos plots actually have interesting events in them now.

**Comment by d-cameron** [comment]
@hpages round two of feedback has been addressed

**Comment by hpages** [comment]
Thanks Daniel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/d-cameron.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("StructuralVariantAnnotation")`. The package 'landing page' will be created at

https://bioconductor.org/packages/StructuralVariantAnnotation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
