### ISSUE TITLE
CellMixS submission

### ISSUE THREAD

**Issue by almutlue** [Bioconductor/Contributions#1080]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/almutlue/CellMixS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see the comments below: 

**README**
- [ ] Add Bioconductor installation instructions

**NEWS**
- [ ] Please reformat. Headers should be changes in version 0.99.3, followed by the list of changes
```
Changes in Version 0.99.3

* Preparation for Bioconductor submission

```
If you install the package you should be able to do `news(package="CellMixS")`  and see the valid news file by version


**man**
- [ ] I recommend having a CellMixS package Rd package giving an overview and recommending main functions

**R code**
Generally really well written and seems to have detailed documentation,  I would recommend doing some input checking to make sure the arguments are the desired structures or certain criteria filled.
For example, for function ldfSce: 
If `sce_name` has to be in `sce_pre_list` then there should be a  `stopifnot(sce_name %in% names(sce_pre_list))` 
But should extended out to all .R file functions.
I see you start to do this for cms  but this should be done to any exported function that the user can call on their own. 

**vignette**
Seems clean and detailed.  Very nice. 

Please address the above issues. When ready perform a version bump and comment back here with what has been updated and requesting a re-review. I look forward to getting your package accepted to Bioconductor.

**Comment by almutlue** [comment]
Dear Lori, 
thanks a lot for your review and nice comments.  

I updated the package: 

- changed the install instructions in the **README**.  
- changed the format of the **NEWS** file by creating a NEWS.Rd in inst/.  
- added a **Man** page for the package (CellMixS-package.R).  
- added input checks to all exported functions in the **R code**.

I hope I adressed and implemented  your comments as they were intended. 
Let me know if there is anything else to change.

Thanks again for your input and time!

Best,
Almut

**Comment by almutlue** [comment]
Thank you so much!!!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/almutlue.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CellMixS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CellMixS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
