### ISSUE TITLE
metagene2

### ISSUE THREAD

**Issue by ericfournier2** [Bioconductor/Contributions#1081]
Hello,

Our group would like to submit the metagene2 package for inclusion in BioConductor release 3.9. metagene2 is a thorough rewrite of our previous BioCondcutor package, metagene. It includes large improvements to performance as well as a new, cleaner interface and numerous additional features:

- metagene2 now accepts discoutiguous regions, such as gene exons, allowing one to create metagenes for RNA-seq data.
- metagene2 can now accept metadata for genomic regions and input bam files, and can later use these metadata to improve its output plots
- Richer options for plotting, including grouping and facetting on arbitrary metadata columns. 
- A strand specific mode for RNA-seq data
- Options for extending reads
- Plotting individual regions

We hope you find the package to be of interest for inclusion in Bioconductor.

Cheers,
-Eric

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ArnaudDroitLab/metagene2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Do you intend to continue maintaining metagene? Perhaps it is appropriate to introduce this as 'metagene', version 2.0.0 instead?

**Comment by ericfournier2** [comment]
We intend to continue maintaining metagene with bug fixes for the foreseeable future. But we'd rather move on to metagene2 because 1) Some operations that were possible under metagene are not possible in metagene2 and 2) Even for routine operations, the interface changes in metagene2 might break working metagene code.

**Comment by ericfournier2** [comment]
Hi,

Is there some way to obtain additional information about which steps of CHECK are taking so much time on the Bioconductor build servers? Even after removing all but the most basic of unit tests, I'm still over 7 minutes (whereas CHECK runs in 3~4 minutes on my machine). I've run out of ideas on what I can do to improve CHECK time.

Thanks,
-Eric

**Comment by mtmorgan** [comment]
I think the majority of check time is actually spent loading your package, which is done many (I think 19) times during the check process. The length of time to load the package is determined in part by dependencies, so a suggestion would be to limit the number of dependencies to those that are essential for the functionality of your package. 

Unfortunately a very heavy dependency is GenomicFeatures, and this may well be essential for you. If so, then really I would not worry about the time limit being exceeded; I will review the package in its current state.

**Comment by ericfournier2** [comment]
Thanks for your insight. I've tried removing some dependencies and relying on 'require' for parts of the package which aren't core to its functionality, and I've managed to shave ~15% off the loading time (From ~7 to ~6 seconds). I might push that later when I've more thoroughly tested it.

**Comment by mtmorgan** [comment]
Is your package ready for review? If so please increment the version to trigger an automatic build.

**Comment by ericfournier2** [comment]
I'm sorry, I seem to have misunderstood. I thought you meant to review the package as it was, and so held off on pushing the changes while I worked on other things. Sorry for the hold-up.

I've gone ahead and pushed an update that removes some utility functionality and improves CHECK time. Go ahead and review whenever you have the time!

Thanks,
-Eric

**Comment by mtmorgan** [comment]
This package looks to be in good shape, with a few minor
comments. Please revise and when updated post a brief comment
summarizing changes you've made.

DESCRIPTION

- Use Author@R (preferred) or Author: and Maintainer: but not both. 
- The file LICENSE is not required for the Artistic-2.0 license; the
  text of the license is included with R.

vignettes

- good

R (comments are on specific lines of code but apply throughout)

- bam_handlerR:248 `stop(paste(...))` can usually be written `stop(...)`.
- FWIW I don't think there's value in R6 classes here; users are
  really aware of R's copy-on-change semantic and S3 / S4 generic +
  method constructs rather than reference-based `object$method()`
  formalisms.
- coverage_operations.R:28 use vectorized `lengths()` rather than an
  interation.
- coverage_operations.R:273 this is an example of inefficient
  'copy-and-append'; use `lapply()` or 'pre-allocate-and-fill' for
  better memory management; see [1][]
- demo.R:9 these expressions can be inverted, so that `system.file()`
  is called once with a vector of length 5, rather than 5 times.
- demo.R:47 names usually propagate through `lapply()`, etc., and it
  is cheaper to add names to a character vector than to a list of
  GRanges, so
  ```
  fls <- get_demo_region_filenames())
  names(fls) <- gsub(".bed", "", basename(fls))
  regions_grl <- lapply(fls, ...)
  GRangesList(regions_grl)
  ```
- gap_detection.R this code seems to be 'dead'; it's usually better to
  remove this (e.g., to a separate git branch) than to carry it
  around and confuse those looking at your code.

inst/unitTests

- nice!

man

- good!


[1]: https://bioconductor.org/developers/how-to/efficient-code/

**Comment by ericfournier2** [comment]
I've adressed most change requests:

- Fixed the DESCRIPTION Authors
- Removed the LICENSE file and fixed it in DESCRIPTION
- Changed stop(paste(...)) to stop(...)
- Vectorized the codes where length, system.file
- Removed gap_detection.R

I've also fixed quite  a few NOTES since my last push (global variable warnings, seq_len instead of 1:..., vapply instead of sapply).

I must admit that I've never liked ANY of R's object models, but R6 has always seemed the least objectionable to me. But regardless of personal preference, metagene2 is structured around an R6 class mostly for legacy reasons (that's how the first metagene was structured). We did put a lot of effort into extracting functionality into stand-alone functions, though those aren't exported at the moment (everything doing with aggregating coverages, calculating confidence intervals, etc.) In future releases, we'd like to make those functions more readily available.

I've also left the 'copy-and-append' code as is: it's been in production for a while and is relatively safe, while my attempt at refactoring it made the unit tests blow up in somewhere completely unexpected. I might look into it after release, but even though I completely agree copy-and-append is bad and inneficient, here it's in a code path that isn't critical to the overall runtime, and it's used with a plain list that shouldn't go over more than a few dozen elements, so it should hardly be a bottleneck.

**Comment by ericfournier2** [comment]
Yay! Thank you very much for your time and input in reviewing this package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ericfournier2.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metagene2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metagene2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
