### ISSUE TITLE
XCIR

### ISSUE THREAD

**Issue by SRenan** [Bioconductor/Contributions#1089]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SRenan/XCIR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by SRenan** [comment]
Looking at recent posts on bioc-devel, it looks like all versions I have submitted so far should have passed without ERROR/WARNING.

My first submission was affected by the issue in VariantAnnotation::readVcf on windows.
My latest sumission is now timing out on Linux despite decreasing data size for the examples and R CMD check consistently around 5minutes on 3 of my Linux machines. I see the BioC team is currently trying to resolve related issues.

Should I simply wait and submit a new push with bumped version once the issues are resolved?

**Comment by lshep** [comment]
The issue should be resolved.  You can push a new version bump now and it should be an accurate report.

**Comment by dvantwisk** [comment]
Great! I'll start reviewing your package now.

**Comment by dvantwisk** [comment]
Here is the review of your package. I think it is very well written and just have a few concerns. [REQUIRED] tags indicate changes that must be made or addressed. [CONSIDER] tags indicate changes that are advisable but not required. Please message me back when you are finished making changes.

GENERAL
- [ ] [REQUIRED] We tend to like to see repositories no larger than 5MB in size.
You repository is currently 10MB in size. Most of this size seems to come from
your `.git` file. It's likely files that you committed and later deleted are
taking up this space.  We recommend that you use the BFG-repo cleaner tool to
reduce the size of your repository.
- [ ] [CONSIDER] Try to be as specific as possible with your documentation.
For example in, `R/utils.R`'s `betaParam` function, it's not immediately clear
what type of input the parameters can take. Please look over your documentation
to make sure that a user can quickly learn what a function does, requires as
input, and returns.

R/betabin.R
- [ ] [CONSIDER] Use `match.arg()` to declare `optimizer`. In the function
definition of `betaBinomXI`, `optimizer` can be declared as
`optimizer=c('nlminb', 'optim')`. The first value, `'nlminb'`, is the default
value. The user's selection can be obtained with
`optimizer <- match.arg(optimizer)`. This way of doing things is better since
it allows the user to see the options when viewing the function. Also,
`match.arg()` will throw an error if an option not specified is given. There
are other places in this package that this can be used.

tests
- [ ] [CONSIDER] Add tests using the `testthat` package.

**Comment by SRenan** [comment]
@dvantwisk Thank you for reviewing this and the excellent points and suggestion. I was not aware of BFG-repo! It appears to have successfully reduced the size of the git folder to 2.5M.

I will go through the documentation one more time and submit a push for the other REQUIRED items. The only one I cannot promise to fix immediately is the implementation of tests with `testthat`. Adding tests is on the long TODO list along with moving to S4 classes for the bigger objects in the pipeline. In the meantime most exported functions are currently tested either through the example files or the vignette.

PS: The package built while I was typing this and it looks like it received an ERROR on one of the machines while trying to connect to ensembl.
```
Error in bmRequest(request = request, ssl.verifypeer = ssl.verifypeer,  : 
  Not Found (HTTP 404).
``` 
I believe this is an issue with accessing the URL, not related to my code, but please, let me know if that's a concern.

**Comment by SRenan** [comment]
@dvantwisk Please let me know if the package is acceptable with the fixes.


> GENERAL
> 
> * [X]  [REQUIRED] We tend to like to see repositories no larger than 5MB in size.
>   You repository is currently 10MB in size. Most of this size seems to come from
>   your `.git` file. It's likely files that you committed and later deleted are
>   taking up this space.  We recommend that you use the BFG-repo cleaner tool to
>   reduce the size of your repository.
> * [X]  [CONSIDER] Try to be as specific as possible with your documentation.
>   For example in, `R/utils.R`'s `betaParam` function, it's not immediately clear
>   what type of input the parameters can take. Please look over your documentation
>   to make sure that a user can quickly learn what a function does, requires as
>   input, and returns.
> 
> R/betabin.R
> 
> * [X]  [CONSIDER] Use `match.arg()` to declare `optimizer`. In the function
>   definition of `betaBinomXI`, `optimizer` can be declared as
>   `optimizer=c('nlminb', 'optim')`. The first value, `'nlminb'`, is the default
>   value. The user's selection can be obtained with
>   `optimizer <- match.arg(optimizer)`. This way of doing things is better since
>   it allows the user to see the options when viewing the function. Also,
>   `match.arg()` will throw an error if an option not specified is given. There
>   are other places in this package that this can be used.
> 
> tests
> 
> * [ ]  [CONSIDER] Add tests using the `testthat` package.

**Comment by SRenan** [comment]
@dvantwisk Could I get an update on the package changes, please? 
I am ready to submit the manuscript and letting readers know that the implementation of the method is available in BioC (at least devel) will surely increase the value of the work presented!

**Comment by dvantwisk** [comment]
The changes look good. I am going to move to accept the package now.

**Comment by SRenan** [comment]
Thank you very much!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SRenan.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("XCIR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/XCIR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
