### ISSUE TITLE
YARN: Robust Multi-Condition RNA-Seq Preprocessing and Normalization

### ISSUE THREAD

**Issue by jnpaulson** [Bioconductor/Contributions#109]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/QuackenbushLab/yarn

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by jnpaulson** [comment]
Hey @hpages, 

Hope all is well. Any recommendations on how to fix this on Windows?

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'GenomicFeatures'
Error: package or namespace load failed for 'yarn'
Execution halted

It looks like this package has a loading problem when not on .libPaths:
see the messages for details.
```

**Comment by hpages** [comment]
Hi Joseph,

I can't reproduce this problem. Maybe a spurious warning due to some unusual conditions that happened on the single package builder. Let's ignore this for now.

Thanks for your submission. There are some issues with the package. Hopefully they'll be easy to address:

(1) Using ExpressionSet for representing RNA-Seq data is a poor choice. Most Bioconductor packages that deal with RNA-Seq or other HTS data use the SummarizedExperiment container instead. But because you use ExpressionSet,  people using your package for normalization won't be able to use any of these   packages for the downstream part of the analysis. This lack of interoperability between your package and the Bioconductor ecosystem is unfortunate.

(2) Found in the vignette:

You can install yarn from github with:
```
    # install.packages("devtools")
    devtools::install_github("QuackenbushLab/yarn")
```
Once your package is accepted and part of Bioconductor, your users should *never* install it from github. They should always use `biocLite()` instead:
```
    source("http://bioconductor.org/biocLite.R")
    biocLite("yarn")
```
Using `biocLite()` is the standard way of installing a Bioconductor package. Unlike `devtools::install_github()`, it will take care of grabbing the version of yarn and its dependencies that are compatible with the user's version of Bioconductor.

(3) Please use `<-` instead of `=` for assignment.

Cheers,
H.

**Comment by jnpaulson** [comment]
Great points!

Thanks, I'll address those and make a new commit within the next two weeks.

Joe

**Comment by hpages** [comment]
Hi Joseph,

If you're done with your changes, please don't forget to bump the version of your package. Otherwise, the single package builder won't build it. Thanks!

H.

**Comment by jnpaulson** [comment]
Thanks @hpages! Went ahead and did an uptick. I still haven't switched over to _SummarizedExperiment_ objects because one of the bioc packages I rely on expects _ExpressionSets_ (quantro), but I can work around it if absolutely necessary / you still suggest it?

**Comment by jnpaulson** [comment]
@hpages

**Comment by hpages** [comment]
Hi Joseph,

1) The `matdensity()` function from the quantro package can take a matrix. In your code, you're actually calling it on a matrix, not on an ExpressionSet. Same thing for the `qsmooth()` function. 
3) You still use `=` instead of `<-` in the vignette and in some man pages (`plotHeatmap`, `plotCMDS`, `downloadGTEx`, etc...)
4) `extractMatrix` and `qsmooth` man page need examples.
5) The `annotateFromBiomart` example doesn't do anything.
6) `filterLowGenes` man page says:
```
     ...: Options for ‘cpm’
```
Which `cpm` function? Where is it defined? Please provide proper credit and add a \seealso section with something like this in it:
```
\link[edgeR]{cpm} function defined in the \package{edgeR} package
```
Hopefully you can make it in time for this release.

H.

**Comment by jnpaulson** [comment]
Thank you @hpages for the finds! Made all of the adjustments (except kept matdensity call).

Let me know if there is anything else, best.

**Comment by jnpaulson** [comment]
Apologies about the noisy commits. Here's the significant commit: https://github.com/QuackenbushLab/yarn/commit/9d186b3adbbe7e6c96a5a150ee96bf2be2a77ca0. The others were to fix error calls I made in a rush because the examples called non-exported functions (by design) without the `:::`

**Comment by hpages** [comment]
Hi Joseph,

I don't get it. If you don't want to export `extractMatrix` anymore that's fine. But then why would you bother having a man page for it and with examples that call `yarn:::extractMatrix`?

You misinterpreted my comment about your code calling `matdensity()` and `qsmooth()` on a matrix. Earlier you said

> I still haven't switched over to SummarizedExperiment objects because one of the bioc packages I rely on expects ExpressionSets (quantro and eventually qsmooth)

No they don't expect ExpressionSets. You can actually use them on a matrix and that's what your code was doing (before your latest changes). Your latest changes go in the wrong direction. The right direction would be for you to use SummarizedExperiment instead of ExpressionSets. You extract the matrix from a SummarizedExperiment object with `assay()`. So instead of calling `matdensity()` and `qsmooth()` on `exprs(ExpressionSet)`, you would call them on `assay(SummarizedExperiment)`. It's a very easy change. I hope you'll consider it. ExpressionSets are from the stone age really. Everybody these days is using SummarizedExperiment for new packages.

Unfortunately it's a little bit too late for making that change so the package is going to make it in the BioC 3.4 release as it is now.

We'll add it ASAP to our svn repo and builds. You'll receive an email from Martin with details about this.

Thanks for your submission,
H.

**Comment by jnpaulson** [comment]
@hpages -- ahh, okay! Thank you - will make those changes. 

Appreciate the help.
