### ISSUE TITLE
SCANVIS

### ISSUE THREAD

**Issue by agiusp** [Bioconductor/Contributions#1090]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nygenome/SCANVIS

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by agiusp** [comment]
I was wondering whether this submission had been received at all and whether it's being reviewed. Thanks

**Comment by mtmorgan** [comment]
We experienced some problems with our issue tracker at the time you submitted your package. I have tried to add your package to the review queue manually. Can you please increment the version number (to 0.99.1) to trigger an automatic build?

**Comment by mtmorgan** [comment]
I'd like to review your package; can you please address the error in the build report so that I can begin?

**Comment by agiusp** [comment]
I addressed the error and submitted a new version, please let me know if you have access issues. Thanks

**Comment by mtmorgan** [comment]
remember to increment the version number, 0.99.2, 0.99.3, 0.99.4... each time you want a new build.

**Comment by agiusp** [comment]
0.99.2 was uploaded yesterday ... previous version was 0.99.1. I just pushed a v0.99.3 to make sure the build is triggered. Please let me know if the build is still not getting triggered. Thanks so much.

**Comment by mtmorgan** [comment]
A build did not trigger; can you verify that your web hook is installed correctly [1][], perhaps also investigating, if it does seem to be firing, what the 'Response' is, as summarized in the 'Additional Actions' section.

[1]: https://github.com/Bioconductor/Contributions#additional-actions

**Comment by agiusp** [comment]
So my vignette and examples refer to a pulldown of annotation data from my github that's ~15MB in size. This is essential data for my software and inevitably gets included in the tarball by merely getting called up in the vignette. How can I avoid this? What's the best way to reference large data files for documented examples?

**Comment by mtmorgan** [comment]
One strategy is to create a much smaller dataset for illustrating your package. The other is to make the data available as an ExperimentHub resource. ExperimentHub will download and cache the file, so the cost of download is only paid once. See the [ExperimentHub][1] package for instructions on how to create an ExperimentHub package and resource.

[1]: https://bioconductor.org/packages/devel/ExperimentHub

**Comment by agiusp** [comment]
I need some guidance on the Warning that requires me to define Depends as R>=2.10 which is required on account of the compression of example data (per a previous iteration Warning). Does this mean merely inserting the dependency accordingly in the DESCRIPTION file? This is what I did in iteration 13 and 14, but it doesn't seem to have worked. The package really requires other softwares that are only available on R>=3.5, so not comfortable pushing it down to 2.10. And it would appear I need to do something more beyond merely defining dependency in DESCRIPTION. Thanks

**Comment by mtmorgan** [comment]
Specify R >= 3.6.0 or similar, ignore the warning about R >= 2.10, it seems to be mistaken or irrelevant.

**Comment by agiusp** [comment]
> Specify R >= 3.6.0 or similar, ignore the warning about R >= 2.10, it seems to be mistaken or irrelevant.

Did so in v15, Warning for dependency on 2.10 still issued in last Push and it appears to be the only warning. So what do I need to do next?

**Comment by mtmorgan** [comment]
next step: ignore the warning!

**Comment by agiusp** [comment]
Bot issued a version bump requirement. I pushed to v99.16, package was built and same warning lingers about R >=2.10 which I have ignored per instructions. What do I need to do next? Thanks

**Comment by mtmorgan** [comment]
I'll review the package asap. Once reviewed / accepted, it will be available at https://bioconductor.org/packages/SCANVIS. It will also be assigned a DOI (document object identifier) like those you see on package landing pages.

**Comment by mtmorgan** [comment]
#  6 June, 2019

I'm sorry for the delay in returning this review.

GENERAL

- Please address the build report NOTEs from R CMD check 

DESCRIPTION

- Please provide a descriptive title so that users have a sense of what your package does; the Description: field would be appropriate.

- Description: too brief; should read like a paper abstract highlighting new features and contrasting with alternatives

- There should only be one Depends: etc field

- Generally packages that are used only internally by your package should be listed in Imports:; only packages that the user would need to create inputs to or manipulate outputs of your function should be listed in the Depends: field.

LICENSE

- Academic / not-for-profit license is not appropriate for a Bioconductor package; please adopt a license that does not restrict use in this way.

vignettes

- looks really great

- add a code chunk reporting `sessionInfo()` at the end.

R

- Never write to the user file system (e.g., `getwd()`, `~/`, ...); expose any output file path to the user as a function argument with default tempfile()

- Use BiocFileCache to manage file downloads; e.g., http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource

- `SCANVIS.annotation.R:34` use accessors (e.g., `mcols(unlist(gencode))$gene_type`??) rather than direct slot access `@`

- `SCANVIS.annotation.R:95` avoid 'copy-and-append' pattern; instead, vectorize (best) or 'pre-allocate and fill', see http://bioconductor.org/developers/how-to/efficient-code/ . I think this pattern appears repeatedly in your code.

- `SCANVIS.annotation.R:98` use `stop()`, `warning()`, `message()` to signal error or informative messages to the user; use `cat()` or `print()` only to display an object in a `print()` or `show()` method.

- The function naming convention with '.' as part of the function name `SCANVIS.scan` should be avoided, as this format is used in S3 method dispatch.

man

- `SCANVIS.annotation.Rd:18` remove unused documentation sections.

**Comment by mtmorgan** [comment]
Is your package ready for final review?

**Comment by agiusp** [comment]
Yes please!

**Comment by mtmorgan** [comment]
looks like you made a commit just now, without a version bump; bump the version and I'll review...

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/agiusp.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SCANVIS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SCANVIS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
