### ISSUE TITLE
SynMut

### ISSUE THREAD

**Issue by Koohoko** [Bioconductor/Contributions#1093]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Koohoko/SynMut

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please mark the vignette chunk that illustrates how to install packages with `eval = FALSE` so that your package is not installed each time the vignette is built.

**Comment by Koohoko** [comment]
> Please mark the vignette chunk that illustrates how to install packages with `eval = FALSE` so that your package is not installed each time the vignette is built.

Thanks for your comments, I have revised it in the recent version.

**Comment by Koohoko** [comment]
@lshep Dear reviewer, I guess the SynMut package is now ready to be further examined, any of your comments would be much appreciated. Thanks.

**Comment by lshep** [comment]
Thank you for your submission.  Please see initial comments below:

**readme**
- [ ] Add bioconductor installation instructions too

**vignette**
- [ ] change name of vignette. Cannot have generic `vignette.Rmd` we recommend
the name of the package `SynMut.Rmd` as it is intuitive for users to do
`vignette('SynMut')` to find a package vignette.
- [ ] Include bioconductor installation instructions
- [ ] Why not extended out  a function to ease user call for random
synonymous mutants generation
```
get_cu(codon_random(rgd.seq)) - get_cu(rgd.seq)
get_cu(codon_random(rgd.seq, keep = TRUE)) - get_cu(rgd.seq)
get_cu(codon_random(rgd.seq, n = 0.5)) - get_cu(rgd.seq)
```
all have the same basic format, so something like
```
generate_mutants <- function(object, keep=c(TRUE, FALSE), n){
  keep <- match.arg(keep)
  get_cu(codon_random(rgd.seq, keep=keep, n=n)) - get_cu(rgd.seq)
}
```
This obviously needs some tweaking but hopefully demonstrates the idea... 

**R code**
- [ ] codon_random.R Try to avoid duplicated code. The series of line 81-109 is
  the same as 137-165. This should be made into its own function.  Duplicated
  code is never advisable. For example, if a bug in the code is found it is
  easier than to change in one location instead of two (or several)

- [ ] It seems like this could also be the case between codon_to.R and dinu_to.R
  regarding extract region section. Avoid duplicate code - make a single
  function that could be called in both places. 

- [ ] Extended this elimination of redundent/duplicated code throughout all R
  files. 

- [ ] try callNextMethod too for eliminating the duplicated code between
  input_seq setMethods in input_seq.R

When ready please do a version bump to trigger a new build and comment back here with a summary of changes and requesting a re-review.  I look forward to working with you on getting your package into Bioconductor. 
Cheers

**Comment by Koohoko** [comment]
@lshep Thank you so much for your comments.
The summary of changes for version 0.99.5 is as below:

> **readme**
> 
> * [x]  Add bioconductor installation instructions too

__Fixed as suggested.__

> 
> **vignette**
> 
> * [x]  change name of vignette. Cannot have generic `vignette.Rmd` we recommend
>   the name of the package `SynMut.Rmd` as it is intuitive for users to do
>   `vignette('SynMut')` to find a package vignette.
> * [x]  Include bioconductor installation instructions

__Fixed  as suggested.__

> * [x]  Why not extended out  a function to ease user call for random
>   synonymous mutants generation
> 
> ```
> get_cu(codon_random(rgd.seq)) - get_cu(rgd.seq)
> get_cu(codon_random(rgd.seq, keep = TRUE)) - get_cu(rgd.seq)
> get_cu(codon_random(rgd.seq, n = 0.5)) - get_cu(rgd.seq)
> ```
> all have the same basic format, so something like
> 
> ```
> generate_mutants <- function(object, keep=c(TRUE, FALSE), n){
>   keep <- match.arg(keep)
>   get_cu(codon_random(rgd.seq, keep=keep, n=n)) - get_cu(rgd.seq)
> }
> ```
> This obviously needs some tweaking but hopefully demonstrates the idea...
> 

__Sorry for my poor explanation for the commands in the vignette. In fact the__ 
__`codon_random` function is essentially the function for generating random mutants.__
__The `get_cu` functions was for validation of the results. I have added more detailed__
__comments in the vignette now to help explaining my intention.__

> **R code**
> 
> * [x]  codon_random.R Try to avoid duplicated code. The series of line 81-109 is
>   the same as 137-165. This should be made into its own function.  Duplicated
>   code is never advisable. For example, if a bug in the code is found it is
>   easier than to change in one location instead of two (or several)

__Fixed  as suggested.__
__Duplicated code in the following functions were converted to helper functions.__
  o __codon_random.R__
  o __codon_to.R__
  o __dinu_to.R__
  o __codon_mimic.R__

> * [x]  It seems like this could also be the case between codon_to.R and dinu_to.R
>   regarding extract region section. Avoid duplicate code - make a single
>   function that could be called in both places.

__Fixed  as suggested.__
__Added region_related.R to store the helper functions related to extracting or merging region.__

> * [x]  Extended this elimination of redundent/duplicated code throughout all R
>   files.

__Fixed  as suggested.__
__Eliminated 67 lines of duplicated code in dinu_to.R__

> * [x]  try callNextMethod too for eliminating the duplicated code between
>   input_seq setMethods in input_seq.R

__Fixed  as suggested.__
__Eliminated duplicated code in input_seq.R (did not use callNextMethod due to lack of class inheritance)__

**Comment by lshep** [comment]
Thank you.  I hope you can appreciate the value of not having duplicated code.  Please update the Bioconductor installation instructions in your readme and vignette to include `BiocManager::install("SynMut")`  for the actual installation of your package.

**Comment by lawremi** [comment]
I would recommend `import(methods)` and `import(BiocGenerics)`. And removing all of the `methods::` and `BiocGenerics::` stuff. Those should be considered basic APIs without need of qualification.

**Comment by Koohoko** [comment]
> I would recommend `import(methods)` and `import(BiocGenerics)`. And removing all of the `methods::` and `BiocGenerics::` stuff. Those should be considered basic APIs without need of qualification.
> 
> There are also needless `Biostrings::` and why is seqinr used here in addition to Biostrings? Should only need one.

Thank you @lawremi , I agree it would be a good practice importing these packages and I have revised this in the 0.99.8 version. 
Regarding to seqinr issue, in fact the input and output object, and the main body in this package is easily compatible with the Biostrings package, and it was our aim to make it compatible to the Bioconductor environment. However, we did make use of some existing functions in seqinr in the internal part of the package. They were mainly established functions for some specific demands, for example the `synsequence` function in seqinr generates a random synonymous coding sequence with fixed codon usage bias. We did not mean to but we was simply avoiding recreation of similar functions, so we used them.
Thank you again for your kind help.

**Comment by Koohoko** [comment]
> Thank you. I hope you can appreciate the value of not having duplicated code. Please update the Bioconductor installation instructions in your readme and vignette to include `BiocManager::install("SynMut")` for the actual installation of your package.

Thank you so much for your time @lshep . I revised it in the updated version.

**Comment by lawremi** [comment]
Ok, I would try to minimize the dependency on seqinr though. For example, `seqinr::translate()` and `seqinr::words()` have equivalents in Biostrings.

**Comment by lshep** [comment]
Could you please update as @lawremi  suggests.

**Comment by Koohoko** [comment]
> Ok, I would try to minimize the dependency on seqinr though. For example, `seqinr::translate()` and `seqinr::words()` have equivalents in Biostrings.

Thank you @lawremi, I updated most of the R files reducing the dependency on seqinr. I mainly changed  the `seqinr::translate()` and `seqinr::words()` to `Biostrings::translate()` or `Biostrings::mkAllStrings()` where interchangeable.
Thank you for your advice, I've learnt a lot.

**Comment by Koohoko** [comment]
> Could you please update as @lawremi suggests.

Hi @lshep , I updated most of the R files reducing the dependency on seqinr. I mainly changed the `seqinr::translate()` or `seqinr::words()` to `Biostrings::translate()` or `Biostrings::mkAllStrings()` where interchangeable. The few remaining seqinr functions were kept because they maintained the data structure and reduced complexity for specific analysis.
Thank you.

**Comment by lawremi** [comment]
Thanks for making those changes. I would suggest using `Biostrings::GENETIC_CODE` instead of `mkAllStrings()`.

**Comment by Koohoko** [comment]
> Thanks for making those changes. I would suggest using `Biostrings::GENETIC_CODE` instead of `mkAllStrings()`.

Thank you. I've used the `Biostrings::GENETIC_CODE` for the codon/amino acid related parts, and mkAllStrings()` was mainly for generating oligonucleotide with other lengths. :)

**Comment by Koohoko** [comment]
Thank you all for your kind help. :)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Koohoko.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SynMut")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SynMut

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
