### ISSUE TITLE
depmap: Cancer Dependency Map data package

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/Contributions#1096]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/UCLouvain-CBIO/depmap

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lgatto** [comment]
I have addressed some issues with the DESCRIPTION file. 

There remain two errors, one of which is a false positive. I am registered on the support site, but using my gmail address. 
The other error concerns manual pages without examples. The package has two executable vignettes that describe the data in good detail. Any examples in the manual pages would unnecessarily duplicate the code in the vignette.

**Comment by lgatto** [comment]
@nturaga - could you help me out with the apparent lack of pushes. The push webhook looks correct (this one, below, is a new one, that I just recreated now; the previous one displayed similar apparent successful deliveries)

![2019-04-23-112822_746x671_scrot](https://user-images.githubusercontent.com/384198/56570139-a77fbe00-65ba-11e9-9a53-d10cc840f3f9.png)

![2019-04-23-112723_755x871_scrot](https://user-images.githubusercontent.com/384198/56570091-946cee00-65ba-11e9-81fb-af857a0006a9.png)

![2019-04-23-112741_758x483_scrot](https://user-images.githubusercontent.com/384198/56570102-9931a200-65ba-11e9-932f-ad4bb1fa37d3.png)

I can't see any signs of pushes here, despite an [bumped version number](https://github.com/UCLouvain-CBIO/depmap/commit/8c090691a431e54d68afdf2047ff50245a4b0eb2).

**Comment by lshep** [comment]
Could you please try another version bump so I can try and trace it on our end ?  I'm having trouble finding the original because of the 5 day span (we've had a lot of activity with it being release deadline week)

**Comment by lgatto** [comment]
Done, and now I receive the following error:

![2019-04-23-215856_1168x778_scrot](https://user-images.githubusercontent.com/384198/56611902-46380900-6613-11e9-8a77-53f199189bcf.png)

So I must have done something wrong?

**Comment by lshep** [comment]
We are thinking it might be a capitalization issue.  As the repository seems technically to be `UCLouvain-CBIO/depmap`   while it is all lowercase in the repository link at the top of this page.  Could you please update the repository link and try another version bump.

**Comment by lgatto** [comment]
Yes, that was it indeed. Sorry for the trouble.

**Comment by lgatto** [comment]
Regarding the 2 errors:
```
* Checking man page documentation...
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      copyNumber.Rd, crispr.Rd, depmap_release.Rd, metadata.Rd,
  mutationCalls.Rd, rnai.Rd, RPPA.Rd, TPM.Rd
```
There's a detailed vignette that describes these data and how to load them. Repeating the same calls in the man pages feels a bit like a waste.


```
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .
```
I am [registered on the support site](https://support.bioconductor.org/u/5645/), but with a different email address.

**Comment by nturaga** [comment]
Hi @mtmorgan, Is there a way to avoid the error on the build report "R CMD Check" without an ERROR for the maintainer being listed on the support site? @lgatto seems to be registered by since it's a different email address, it's displaying the ERROR note. 

If there isn't to suppress this, is the best idea for @lgatto to use his registered gmail account in the package DESCRIPTION as well?

**Comment by mtmorgan** [comment]
I think the sensible thing to do is to ignore the error in the check.

**Comment by lgatto** [comment]
There was a message asking for a version bump, which I did. The errors as still the same ones as discussed above. Let me know if there's anything you need from me.

**Comment by nturaga** [comment]
# depmap Review

## R CMD build

ok

## R CMD check

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## NEWS

ok

## man

ok

## vignettes

ok

## R

ok

Good package @lgatto !

**Comment by lgatto** [comment]
Excellent, thanks @nturaga. And thank you to @tfkillian, the co-developer.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgatto.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("depmap")`. The package 'landing page' will be created at

https://bioconductor.org/packages/depmap

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
