### ISSUE TITLE
ENCODExplorerData

### ISSUE THREAD

**Issue by ericfournier2** [Bioconductor/Contributions#1097]
We would like to submit ENCODExplorerData for inclusion in Bioconductor release 3.9. This package is a subset of our current Bioconductor package, ENCODExplorer. The Data portion of ENCODExplorer (A data.table describing every file made available by the ENCODE project) has grown too big for inclusion as a software package (Nearly 80MB). Thus, we have split the data part into this new AnnotationHub package, and kept the software part in ENCODExplorer.

Thank you for your time,
-Eric Fournier

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ArnaudDroitLab/ENCODExplorerData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ericfournier2** [comment]
The package currently fails BiocCheck because less than 80% of our eported functions have runnable examples. However, we only export 5 functions, and two of those rely on downloading and parsing massive json file, an operation which takes up to 3 hours to run on a modern PC.

Is there a way to get a pass on that one, or should we start thinking very hard about new functions to export?

**Comment by lshep** [comment]
We can ignore the 80% ERROR for now. Please see some other notes below. 

**build report**
- [ ] Recommend cleaning up the global variable and function NOTES
- [ ] Recommend updating sapply to vapply as suggested
- [ ] Recommend seq_len or seq_along in place of 1:... as suggested
- [ ] Add a newline at the end of `/inst/scripts/make-metadata.R`

**readme**
- [ ] (optiona) we always suggest adding the Bioconductor installation
instruction to the readme 

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ENCODExplorerData")

```

**description**
- [ ] Please use Authors@R (preferred) or Author/Maintainer but not both
- [ ] Please remove `LazyData: true` . We actually have rarely found this
helpful and can actually slow down installation of data packages. 


**man**
- [ ] You might want to do a Seealso for your main package page to indicate main
functions or the software package
- [ ] Can you mark non exported functions with` @keywords internal`
- [ ] encode_df_lite.Rd I would run the download for the lite version of the
data.frame. It does not take long to download from AnnotationHub. Also if you
know exact match I would use subset instead of query
```
> myfiles <- subset(hub, title=="ENCODE File Metadata (Light, 2019-04-12 build)")
> myfiles
AnnotationHub with 1 record
# snapshotDate(): 2019-04-18 
# names(): AH69290
# $dataprovider: ENCODE Project
# $species: NA
# $rdataclass: data.table
# $rdatadateadded: 2019-04-18
# $title: ENCODE File Metadata (Light, 2019-04-12 build)
# $description: A data-frame containing a curated selection of metadata desc...
# $taxonomyid: NA
# $genome: NA
# $sourcetype: JSON
# $sourceurl: https://www.encodeproject.org/
# $sourcesize: NA
# $tags: c("ENCODE", "ENCODExplorerData") 
# retrieve record with 'object[["AH69290"]]' 

```

Please make sure the [webhook is initialized]( https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) to trigger a rebuild on version bump.  Please address the issues above and when ready to a version bump and comment back here with a summary of updates and requesting a re-review.  
Cheers and thank you for all your quick work on putting this package together.

**Comment by ericfournier2** [comment]
I've pushed a new build. Here are the points I've addressed, and a justification for the one I did not.

> 
> **build report**
> 
>     * [x]  Recommend cleaning up the global variable and function NOTES
> 
>     * [ ]  Recommend updating sapply to vapply as suggested
> 
>     * [x]  Recommend seq_len or seq_along in place of 1:... as suggested
> 
>     * [x]  Add a newline at the end of `/inst/scripts/make-metadata.R`
> 

I have cleaned up the global variables (which were really dynamic-bound variables with tidyr and data.table) and the uses of 1:.... However, I'd rather not touch the sapply calls right now, since they've been working production code for years now, and are mostly in a messy function written by someone else, and I can't telll if it might actually rely on the funky sapply behaviour. I might try to refactor that whole function after the 3.9 release, but right now I think the risk of breaking something outweighs the benefits of moving to vapply.

> **readme**
> 
>     * [x]  (optiona) we always suggest adding the Bioconductor installation
>       instruction to the readme
> 
> **description**
> 
>     * [x]  Please use Authors@R (preferred) or Author/Maintainer but not both
> 
>     * [x]  Please remove `LazyData: true` . We actually have rarely found this
>       helpful and can actually slow down installation of data packages.
> 
> 
> **man**
> 
>     * [x]  You might want to do a Seealso for your main package page to indicate main
>       functions or the software package
> 
>     * [x]  Can you mark non exported functions with` @keywords internal`
> 
>     * [x]  encode_df_lite.Rd I would run the download for the lite version of the
>       data.frame. It does not take long to download from AnnotationHub. Also if you
>       know exact match I would use subset instead of query
> 

Thank you for your time,
-Eric

**Comment by ericfournier2** [comment]
The remaining error is still the 80% \dontrun bit.

**Comment by lshep** [comment]
Looks good.  I'm okay with not having the 80% of examples run since most other functions are run and tested.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ericfournier2.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ENCODExplorerData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ENCODExplorerData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
