### ISSUE TITLE
MONSTER

### ISSUE THREAD

**Issue by dschlauch** [Bioconductor/Contributions#110]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/QuackenbushLab/MONSTER

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lshep** [comment]
Any package utilized should be listed in the DESCRIPTION file as a Depends, Imports, Suggests, or Enhances and if applicable imported (or specific functions importFrom)  in the NAMESPACE.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. 

Please address the following WARNING/NOTE issues from the buildreport: 
[MONSTER](http://bioconductor.org/spb_reports/MONSTER_buildreport_20160919154800.html)

**DESCRIPTION:** 
remove testthat from Imports and leave in Suggests. 
add Methods to Imports

**DESCRIPTION/NAMESPACE:** 
Please consider adding the imports and imports from suggested in the package build report to remove the "no visible global function definition" notes: 
Add:
```
  importFrom("methods", "new")
  importFrom("stats", "as.dendrogram", "as.dist", "coefficients", "cor",
             "cov", "dist", "hclust", "lm", "order.dendrogram", "pnorm",
             "princomp", "sd")
  import(pandaR)
  importFrom("tidyr", "spread")
  importFrom("reshape2", "melt")
```  

We would appreciate if you could also correct the package build report notes on "no visible binding for global variable". See `?globalVariables`

**MAN:**
add a documentation entry for yeast

fix checking Rd \usage sections ... WARNING   (see the build report)

**DATA:** 
For the uncompressed saves
Run
`R CMD build --resave-data MONSTER`
This will create a tarball that has the data files compressed as small as possible. Untar this file and copy the data files in it over the ones in your git working copy, then recommit those.

Once these are address we will further review your package for acceptance.  I look forward to reviewing your updates.

**Comment by lshep** [comment]
Thank you for your submission. Please address the following issues: 

**General:**
remove the png in the top level directory

generally we like packages to be under 4Mb after running R CMD build. Is there any way to reduce your package size, perhaps a smaller dataset? 

**Vignette:** 

We suggest using the BiocStyle::html_document as the output format and therefore add BiocStyle to suggest in the DESCRIPTION file.

Please change or also include installation instruction through Bioconductor
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("MONSTER")
```
When you describe setting up the design vector, you describe it as a 10/5/10 inclusion/exclusion but in the code it looks like 20/10/20 ? 

It seems like you make wrappers for ggplot (tranisitionPCAPlot), igraph (transitionNetworkPlot), dTFIPlot (plot) ,  why wouldn't you have such a wrapper for the heatmap? 

It seems like the input arguments for monster can be an exprSet/expressionSet for the motif/exprData (or at least they should be).  It would be nice to see examples in vignette and man pages and make this more clear. We really try to foster the interconnectivity and compatibility with standard Bioconductor objects.



**MAN PAGES:**
general:  
Change all keywords to meaningful keywords or exclude not \keyword{keyword}
If you have internal functions they should be marked as \keywork{internal}, possibly functions you haven't exported

bereFull.Rd/ldaBERE.Rd:
add example

checkDataType.Rd: 
either mark as internal or  export and add example

monster-package.Rd: 
remove references if not populated
add \seealso section linking to the man page for monster function
remove examples section or include an example don't just populate with comments

monster.Rd: 
Can expr be an ExpressionSet (it should) - make this more clear
Can motif be matrix, exprSet (it should), data.frame that you made reference to in other help pages? - make this more clear.
outputDir should be more clear that its a character vector for the path of file, not logical T/F
Add more details to the MONSTER algorithm, not everyone will look at vignette or where to find it, should be a brief summary here
Add a \seealso to link to a man page for your monster object 

ADD A PAGE FOR YOUR CLASS/OBJECT!  - currently have no idea what the 'monster obj' is.  There should be a page documenting its structure and what is stored.  

monsterNI.Rd: 
'alphaw' -  what documentation? 

plot.monster.Rd: 
'...'   what other plotting methods? what is the underlying plotting function

ssodm.Rd:
Shouldn't this also be able to take in your monsterObj? The code probably should be altered as such. 

transformation.matrix.Rd:
What are the acceptable values for 'method' 


**R/CODE:** 
general: 
Remove any "::", they shouldn't be needed if specified in NAMESPACE/DESCRIPTION
Use seq_len/seq_along rather than 1:n/1:length(x) where appropriate

Class: 
Can your output extend any existing Bioconductor structures? I would offer suggestions but with no man page describing the existing structure and what it consists of its challenging. 

analysis_functions.R: 
Be consistent with naming - functions that use monsterObj as input sometimes are labelled   function(x, ...)  while others are function(monsterObj, ... )

plottm 
This is not used anywhere, not exported, and not documented. Can it be removed? 

hcl.heatmap.plot 
Take out commented code/test code 

ssodm 
This should take in your monsterObj instead of or in addition to a matrix?

transformation.matrix
Have a check for valid 'method'
Take out commented out code


globalVariableHack.R: 
globalVariables should be defined where they are used, in general we don't like 'hacks'. This file shouldn't exist  


regpredict.R:
monsterNI: 
Check valid 'method' since stated in the help page only certain are valid. If 'cd', 'lda' or 'wcd' are used, they all are the same method? 

monster: 
Can motif really be NULL?  it doesn't appear so? have a check? 
Make sure input can also be standard Bioconductor objects like exprSet/expressionSet.  


Thank you for your submission. Please address the above issues with updates or justification. 
Lori

**Comment by lshep** [comment]
Did you intend to start a new build with updates? 
When you are done making updates, please respond to the issues listed above indicating how you addressed/fixed or any justification.

**Comment by dschlauch** [comment]
Hey Lori,
No, I didn't intend to rebuild.  Just got sidetracked.  Hopefully will be able to address all the issues today.  Thanks for your help!

**Comment by lshep** [comment]
No problem. Just wanted to make sure you weren't waiting on me to respond.  
Cheers,
Lori

**Comment by lshep** [comment]
Thank you for your updates.  Please see the following additional comments.  Once
you are finished addressing please respond back here with a summary of changes
or justifications/response to any issues. 

**vignette/R code:** 

- [ ] When you describe setting up the design vector, you describe it as a 10/5/10
inclusion/exclusion but in the code it looks like 20/10/20 ? Could you explain
or maybe I'm miss understanding how the design is constructed. 

- [ ] It seems like you make wrappers for ggplot (tranisitionPCAPlot), igraph
(transitionNetworkPlot), dTFIPlot (plot) , why wouldn't you have such a wrapper
for the heatmap.2 used in your vignette?

- [ ] We really try to foster the interconnectivity and compatibility with standard Bioconductor packages and infastructure. It seems like the input arguments for monster can be an exprSet/expressionSet
for the motif/exprData (or at least they should be). It would be nice to see examples in vignette and man pages and make this more clear.  Further more, are the gene expression matrix (exprData) and regularory gene data frame (motif) related? Could the input be better organized/adaptable to take in a SummarizedExperiment as this is a commonly used Bioconductor object to store gene expression data? 

**man:** 

monsterNI.Rd: 
- [ ] 'alphaw' - you say see documentation. what documentation?

transformation.matrix.Rd:
- [ ] What are the acceptable values for 'method'

I look forward to your response. Thank you.

**Comment by lshep** [comment]
Hello,  I just wanted to touch base to see if you were going to make anymore updates with a version bump?

**Comment by dschlauch** [comment]
Hi Lori,

Very sorry about the delay.  After I wasn't able to get it into the last
release I put it on the back burner for awhile.  I do expect to be making
more changes and to finish up before the next release.

Thanks,
Dan

**Comment by lshep** [comment]
No problem at all.  I saw the pushes and just wanted to double check you weren't waiting on me.

**Comment by lshep** [comment]
As we are getting closer to the spring release I just wanted to check in to see if you had any updates.  Normally it gets quite busy during the release time frame and wanted to make sure you could get your package in this time around.

**Comment by dschlauch** [comment]
Yes, I'll push some updates soon.  Is there a release schedule available?
Thanks, Dan

**Comment by lshep** [comment]
It should be out sometime this week but we are probably looking at 3-4 weeks before the cap for new packages to be included in the release.

**Comment by lshep** [comment]
http://bioconductor.org/developers/release-schedule/

**Comment by lshep** [comment]
Thank you for you submission to Bioconductor.  I am recommending to close this issue as there has been no movement on it in the last few months.  Please reopen the issue when you have more time to work on the package.
