### ISSUE TITLE
muscData

### ISSUE THREAD

**Issue by HelenaLC** [Bioconductor/Contributions#1100]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HelenaLC/muscData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by HelenaLC** [comment]
Dear Martin (or other potential assignees),
While I pass `R CMD build` and `check` without warnings, I receive a NOTE regarding the `Depends` field of the `DESCRIPTION`: 
```
Depends: includes the non-default packages:
  'dplyr', 'ExperimentHub', 'GEOquery', 'Matrix',
  'SingleCellExperiment', 'S4Vectors'
Adding so many packages to the search path is excessive and importing
selectively is preferable.
```

In this context, it is unclear to me whether I should
a) only list packages explicitly used by exported functions (accession functions) or in the vignette (e.g., `ExperimentHub`), or
b) list all packages used anywhere, including any `make-data.R` scripts (e.g., `dplyr` ect.). In this case, is it possible to resolve the above NOTE?

**Comment by mtmorgan** [comment]
Depends: should contain packages that the user must have to interoperate with the functions in your package; packages used in the vignette or scripts or examples or ... and not required by your package internally should be in Suggests:. Packages required internally should be in Imports:

If it turns out that you _do_ have more packages legitimately in Depends: than R CMD check likes, ignore what R CMD check likes.

**Comment by mtmorgan** [comment]
Remember to increment the version number of your package, to 0.99.1, 0.99.2, ... each time you'd like a new build.

**Comment by HelenaLC** [comment]
Okay. Before pushing further updates .. I remain confused regarding the following:
- In lshep's example package (https://github.com/Bioconductor/GSE62944) `DESeq2` is used in the vignette, but does not appear in the DESCRIPTION.
- From your reply above, I am still not certain how to deal with `make-data.R` related functions (as these scripts serve reproducibility, are not exported, and not evaluated during package build/installation). Should functions appearing in `make-data.R` scripts 
a) not appear in the DESCRIPTION, and accordingly be omitted from the NAMESPACE, or, 
b) should they be listed under **suggests:**?
Again, my confusion comes from the fact the lshep put `GEOquery` under **depends:** while the package is only used by `make-data.R`.

As I'm not using any additional packages, my current understanding is:
1. **depends:** `ExperimentHub`
2. **suggests:** `BiocStyle`, `knitr`, and `rmarkdown` for the vignette
3. **imports:** `rdpack` for references, `utils` for `read.csv`/`write.csv` in `zzz.R`/`make-metadata.R`.

**Comment by mtmorgan** [comment]
Yep, time for GSE62944 to be revised, DESeq2 belongs in Suggests:

I'd say that the user is only expecting to interact with your helper functions (not directly with ExperimentHub) and the object returned from ExperimentHub. The vignette on writing ExperimentHub packages also says that this package should go in Depends. So I'd put

    Depends: SingleCellExperiment, ExperimentHub

Your package internals need to use utils (as well as ExperimentHub, but it's availability is already guaranteed by Depends:), so

    Imports:  utils

Various supporting infrastructure, including the packages used in make-data.R, should appear in Suggests:

    Suggests: GEOquery, BiocStyle, knitr, rmarkdown, rdpack

I think ExperimentHub could go in either Depends: or Imports: because of its central role in the way the user will experience your package.

**Comment by HelenaLC** [comment]
That all makes sense & I agree with all of the above. However, R CMD complains about `SingleCellExperiment` in depends: as no functions are imported from it. As the motivation is for the user to be able to directly interact with the output objects, I'm of the opinion that this can be ignored. Thoughts?
```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘SingleCellExperiment’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

**Comment by mtmorgan** [comment]
Ignore the NOTE from R CMD check about SingleCellExperiment; it is about a scenario that is not relevant to the way your package will be used.

I'm not familiar with Rdpack or how it's being used, so you'll have to find the right incantation elsewhere, maybe in an Rdpack man page or vignette, or through trial and error. Note that it introduces several additional dependencies
```
> pkgs = available.packages(repos=BiocManager::repositories())
> tools::package_dependencies("Rdpack", pkgs, recursive=TRUE)
$Rdpack
 [1] "methods"   "tools"     "utils"     "grDevices" "bibtex"    "gbRd"
 [7] "stringr"   "glue"      "magrittr"  "stringi"   "stats"
```
that may make the cost of using it, in terms of maintainability, not worth the benefit it provides.

**Comment by mtmorgan** [comment]
R supports 32- and 64-bit windows. If your data is intrinsically large (1-2 Gb) then it is not meaningful to make it available on a 32-bit platform. You could add a pain text file `.BBSoptions` containing the single line
```
UnsupportedPlatform: win32
```
and place in this at the top level of your package.

**Comment by mtmorgan** [comment]
(a) oops, my mistake, should be plural `UnsupportedPlatforms: win32` and (b) I'm actually not sure whether this is supported by the builder we use during package acceptance; let's ignore the error for now; I'll review the package as-is.

**Comment by lshep** [comment]
The UnsupportedPlatforms specification is support on the SPB.

**Comment by LTLA** [comment]
I have just noticed that this package does an EHub upload of the Tal1 chimera data from the Pijuan-Sala et al. paper. @jonathangriffiths and I are preparing an EHub package for the entirety of the mouse embryo data from that paper, and this would include the Tal1 data as hosted on the CRUK FTP server.  

I don't know how we feel about data duplication on EHub... I would guess that it's probably something we should try to avoid if we can. From my selfish perspective, _compareSingleCell_ needs the raw, unfiltered counts from the paper as well, so even if I used _muscData_ to pull down this data for my workflow, I'd have to write another EHub package anyway to provide the raw data.

**Comment by HelenaLC** [comment]
Fully agree that data duplication on the EH should be avoided. I was of course unaware of this.. apologies for not catching this. I'm still quite new to EH, but I assume that @lshep will have to remove the data object from the EH while I remove the associate metadata/scripts.
...Just to note that - for what it's worth - from my selfish perspective, I also require the raw, unfiltered counts, which is why they are in `muscData` - untouched as proved by Cancer Research UK; only reformatted into a `SingleCellExperiment`.

**Comment by jonathangriffiths** [comment]
Thanks for this - I don't think you could have known about our package, though, so don't worry about that!

The unfiltered counts will be accessible from our package too.

**Comment by lshep** [comment]
@HelenaLC  I can take care of removing the data from EH.  Just so I am clear, I amonly removing the Sala19_2vs2 but leaving the Kang18_8vs8 correct?

**Comment by lshep** [comment]
The package is in excellent shape.  The only comment is to remove the commented out Author/Maintainer fields in the DESCRIPTION.  Authors@R is sufficient.   Please comment on the above. If we are removing 
Sala19_2vs2 but leaving the Kang18_8vs8  in ExperimentHub.  I can handle the removal of the data on S3 and the removal in the Hub but you will need to update the package accordingly as well.

**Comment by LTLA** [comment]
FYI we are almost ready to go at https://github.com/MarioniLab/MouseGastrulationData/.

**Comment by HelenaLC** [comment]
Yes, `Sala19_2vs2` should be removed and `Kang18_8vs8` should stay. I've made the according changes to the packages, and remove the commented-out lines in the DESCRIPTION.

**Comment by lshep** [comment]
I've removed the data from S3 and EH hub.  The rest of the package looks good.  Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HelenaLC.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("muscData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/muscData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
