### ISSUE TITLE
submission of package deltaCaptureC

### ISSUE THREAD

**Issue by michaeldshapiro** [Bioconductor/Contributions#1101]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/michaeldshapiro/deltaCaptureC

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by michaeldshapiro** [comment]
The ERRORs have now been rectified and the code has been modified to address suggestions.

**Comment by michaeldshapiro** [comment]
I am new to this process, so I am not sure what to expect once the errors have been corrected.  In particualr, I'm not sure what triggers a new check once the errors have been corrected and the code changes committed to git.  Please advise if I need to undertake any additional steps.

**Comment by lshep** [comment]
Please see the link for [adding a webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) that was also referenced above.   This will trigger a new build when there is a version bump in the DESCRIPTION file.  Once you have set up the webhook, bump your version, and see if the ERRORs remain on the corresponding build report.

**Comment by michaeldshapiro** [comment]
Thank you, lshep.  Just what the doctor ordered.

**Comment by michaeldshapiro** [comment]
The remaining warning, 'Evaluate more vignette chunks' seems rather generic.  Maybe this package is ready to move on to the next stage in its evaluation?

Cheers!

**Comment by LTLA** [comment]
Chipping in here; if you're dealing with genomic interaction data, you may want to supporting inputs of the `GenomicInteractions` class. One example might be to accept a `GenomicInteractions` object for the restriction fragment pairs annotated with counts. We have a whole stack of infrastructure based on this class for handling various types of chromosomal conformation data, see the revdeps [here](https://bioconductor.org/packages/release/bioc/html/GenomicInteractions.html) and [here](https://bioconductor.org/packages/release/bioc/html/InteractionSet.html).

**Comment by michaeldshapiro** [comment]
Thanks for alerting me to this.  I will look into into it.

**Comment by nturaga** [comment]
# Review deltaCaptureC

## R CMD build

ok

## R CMD check

ok

## DESCRIPTION

ok

## NAMESPACE 

ok

## R

* Import functions like DESeq2::estimateSizeFactorsForMatrix because
  you packge needs it. Use the @importFrom roxygen functionality.
  
* Same with SummarizedExperiment. You should put all these functions
  in the NAMESPACE, and make your code more readable. By removing
  calls to "SummarizedExperiment::" in everyplace you use that
  function, you will make your code more readable.
  
  Review:
  
  http://bioconductor.org/developers/how-to/coding-style/
  
  http://bioconductor.org/developers/package-guidelines/#namespace
  
  You have done this with other packages as well. please correct it.
  
* It seems like some loops can be avoided. Please keep in mind that
  division is vectorized in R. You can have column wise division. 

* For argument validation, use,

		if(condition)
			stop("<Explain why something has to be a value>")
			
	vs
	
	    stopifnot(length(unique(W)) == 1)
		
* In this loop, you will be calcualting the value of `ceiling(n-m)/2` each time

		for(i in seq_len(ceiling((n-m)/2)))
		
	vs
		
		val <- ceiling(n-m)/2
		for (i in seq_len(val)) {
			...
		}
  
  This is not efficient. Please correct similar ideas everywhere in
  your code base.
  
* Move the code for function `getRunsAndTotals` outside of
  `getRunTotals`. Make use of private functions, by not exporting them
  to your namespace.
  
  Define the function, `.getRunsAndTotals()` outside
  `getRunTotals`. Look up coding style and standards on the
  Bioconductor website for Developers.

**Comment by michaeldshapiro** [comment]
Dear Nitesh -

Thank you for your comments.  They seem very much to the point.  I've changed jobs since the initial submission and am juggling obligations, but I hope to respond to these soon.

Thanks,
Michael

**Comment by nturaga** [comment]
@michaeldshapiro 

Congrats on your new job. Just as a heads up. We usually allow a 14 day period for each issue to receive a response once a review is posted. But not to worry, if you do go beyond that, we can close the issue and you can just click "reopen" once you are ready for further development.

Best,

Nitesh

**Comment by michaeldshapiro** [comment]
Dear Nitesh -

Thank you for the heads-up on the deadline.  Makes a great excuse for putting everything else aside.

I'm glad to know about the @importFrom technology.  Makes for much happier code.  Is there a way to rationalize the placement of the imports?  I would have liked to place them all first in the file, but this leads to devtools::document() warnings.

I looked at my for loops, but did not have much success vectorizing these.  Most of these iterate either over individual assays in a SummarizedExperiment or over the columns of a matrix.  Sadly, although the call to width(intersect(...)) can be vectorized, intersect() does not report empty intersections which leads to omission of 0 widths, hence a vector of the wrong length.

Looking forward to your thoughts,
Michael

**Comment by nturaga** [comment]
Please fix the issues in the `R CMD build` and `R CMD check` before I can review your package again. 

The build report has been available since Jul 12.

http://bioconductor.org/spb_reports/deltaCaptureC_buildreport_20190712095651.html

**Comment by nturaga** [comment]
Hi @michaeldshapiro 

I took a look at your package and it's in shape for acceptance. 

The man page issues are highly fixable and I suggest you fix them before the package is accepted. The "fixable" warning messages are the only thing stopping me from accepting your package.

Best,

Nitesh

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/michaeldshapiro.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("deltaCaptureC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/deltaCaptureC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
