### ISSUE TITLE
RNAmodR

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/Contributions#1106]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FelixErnst/RNAmodR.Data

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by FelixErnst** [comment]
Additional packages using the ExperimentHub package will be added once the build succeeds.

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/RNAmodR

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/RNAmodR

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/RNAmodR.RiboMethSeq

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/RNAmodR.AlkAnilineSeq

**Comment by FelixErnst** [comment]
So as a summary regarding the errors and warnings:

- `RNAmodR`: warning because of check time, but it is hard to shorten this, since a lot of things have to be checked. So I would like to keep it as it is for now.
- `RNAmodR`: error is Windows specific and somehow bam files can not be opened, which are provided by the `RNAmodR.Data` package from the ExperimentHub backend. This works on Linux and MacOS
- `RNAmodR.RiboMethSeq` and `RNAmodR.AlkAnilineSeq` will not build on Windows because of the error mentioned directly above.
- `RNAmodR.RiboMethSeq` and `RNAmodR.AlkAnilineSeq`: both build on Linux, but not on MacOS, since Modstrings package cannot be loaded. This is weird since Modstrings is accepted in current devel and should be available.

So everything builds fine on Linux, but Windows and MacOS builds are broken. Any pointers on how to debug this are most welcome.

If you don't have the time right because of the Bioc 3.9 build, let me know.

**Comment by FelixErnst** [comment]
@lshep 

I submitted the `RNAmodR.Data` package and it build fine. However, it cannot be used on Windows, since the bam files are not loaded correctly (see `RNAmodR` build reports). On Linux and MacOS this works fine.

I tried to debug this a bit and noticed, that the devel build reports contain a warning (Windows only) for the `ExperimentHub` package. This didn't need to be updated regarding your changes made last week for the support of the `BamFile` resources, but I find the error I get here quite odd and the warning in the build is also quite odd (https://bioconductor.org/checkResults/3.9/bioc-LATEST/ExperimentHubData/tokay2-checksrc.html). Is the `ExperimentHub` package correctly installed on Windows?

Otherwise I am out of ideas regarding this error. Would you have time to look at this?

**Comment by lshep** [comment]
I'll look into the Windows issue.

**Comment by lshep** [comment]
It looks like symlinks (or the use of file.symlink) is not supported on windows.  I'll debug in AnnotationHub but given we are so close to release probably not until after the official 3.9 release.

**Comment by FelixErnst** [comment]
Thanks. I actually never tested on Windows directly, just in the docker container.

**Comment by lshep** [comment]
The Rsamtools change should propagate today.  I'm pushing up the fix to AnnotatinoHub today and it should propagate tomorrow.  When `AnnotationHub_2.17.3`  is available on the build report, your packages should be able to work on windows for ExperimentHub.   Cheer.

**Comment by FelixErnst** [comment]
Just a question regarding the version of SPB: The devel version of Rsamtools and AnnotationHub is only available Bioc 3.10, but the SPB uses Bioc 3.9 for now (at least 2 days ago). Can I expect the changes to be available on the SPB or do I have to wait for the SPB to be updated?

**Comment by lshep** [comment]
I plan to update the spb in the next week or so. We normally switch it over a week to two weeks after the release too make sure the current packages have time to build through the daily builder

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FelixErnst** [comment]
Hi @LiNk-NY 

since the packages build fine on Linux and the errors on MacOS and Windows are due to very recent changes in BioC and the AnnotationHub, would you consider starting the review process?

I am asking, because there is a paper coming up (in a few month), which would include using the packages, and would of course give me a bit of heads up, if there is something of a show stopper in the packages.

In any event, thanks for you answer.
Felix

**Comment by FelixErnst** [comment]
Hi @lshep. just wanted to ask, if there any news/updates on the SPB update. Thanks

**Comment by lshep** [comment]
Working on them this morning.  The Windows builder for devel was only activated last week so we gave it a week to stabilize.  It should be active later this morning.

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 
Sorry for the delay. I will get to your package today. 
Best regards,
Marcel

**Comment by FelixErnst** [comment]
@lshep I cannot access the build report. Any help/advice is most welcome.

**Comment by lshep** [comment]
Its odd because the resources are there and built fine on the other two platforms... a server 500 error is normally intermittent downtime -  I'll manually kick off a build to see if it persists but for now ignore (@LiNk-NY  ignore -  I ran manually on my linux and it builds/checks fine)

**Comment by FelixErnst** [comment]
and back to the Linux error again. hmm... I wait until you give me the green light for the SPB. Many thanks for looking into the issue.

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 

guten Abend!

Thank you for your contribution. 
Please see the review below. 
If you have any questions, post them here.

Best regards,
Marcel

---

# RNAmodR #1106

Overall, good work on the packages. There is a lot of code in the package that
implements checks for type or non-NULL. It would be good to have a device to
avoid such repeated checks. Perhaps using a particular data structure where
such `list` inputs are not used.

## DESCRIPTION

* Looks good.

## NAMESPACE

* A `settings` function seems a bit vague as to what it does. It would be
helpful for users to have a more descriptive name, if possible.
* Also, see `AnnotationHub` for a similar generic.

## vignettes

* It seems like the early part of the creation vignette goes more into the
developer rather than the user side of the package. You should indicate that
the vignette is for developers only.
* Please use examples that would be mainly used by the end user.
* Main vignette looks good and thorough.

## R/

* Signature arguments in `setGeneric` are not required as they match the formal
arguments unless you are using lazy evaluation.
* Did you contact the 'Gviz' maintainer about using
a non-hardcoded DNA alphabet?
* You shouldn't need to run `valid*` functions in the `show` method, this
should be done at class creation.
* Be more specific with error messages rather than 'Something went wrong.' If
it is an internal error, you can tag it with '<internal>'.
* Use default arguments such as `input = list()` instead of assigning after a
check for `missing()`.
* It may be useful to create a helper function to test `input[["x.measure"]]`
for non-zero, NA, and blanks instead of using a series of `if` and `else` calls,
especially when you run this check on several occasions.
* You may benefit from using a map to check arguments for `.norm_plot_args` and
others. This map will indicate (as separate columns) the error message, assert
function, and name in `input` to check for all those that exist.
* Avoid nesting `lapply`, where possible.
* There's a lot of code in the package and I wasn't able to review all of it.

Minor:
* Avoid name clashing objects with function names, e.g., `list <- ...`
* No need to wrap character/logical/numeric scalars with the `c()` function.
* Use `Map` to avoid `SIMPLIFY = FALSE` argument in `mapply`.
* No need to check `if(X == TRUE)`, simply do `if (X)`. The inverse also applies,
i.e., `if (!X)` is preferred over `if(X == FALSE)`

**Comment by FelixErnst** [comment]
Hi Marcel, @LiNk-NY 

Guten Morgen 😃 

thanks for the quick review.

## NAMESPACE ##
> A settings function seems a bit vague as to what it does. It would be
> helpful for users to have a more descriptive name, if possible.
> Also, see AnnotationHub for a similar generic.

I had a look at the generics from the AnnotationHub package, but none of those seem to be reusable for purpose of tracking settings for a detection strategy. Which generic did you have in mind?
To describe the purpose of the `settings` function more clearly, I added a separate man page.

## vignettes ##
> It seems like the early part of the creation vignette goes more into the
> developer rather than the user side of the package. You should indicate that
> the vignette is for developers only.
> Please use examples that would be mainly used by the end user.

I included clear statement for the intended audience at the beginning of the creation vignette. I hope I can leave the creation vignette in the package. The intention is just to have a comprehensive description of how to extend from the classes.

## R/ ##
> - Signature arguments in setGeneric are not required as they match the formal
> arguments unless you are using lazy evaluation.

I used this for me to keep track of, what I consider required non optional input. This should make it a bit easier down the line, if someone wants to reuse the functionality. Is that ok?

> - Did you contact the 'Gviz' maintainer about using
> a non-hardcoded DNA alphabet?

No, I did not. That is still on my agenda, but since the development and submission of the Modstrings package and the development of the RNAmodR package mostly overlapped, I felt it was not the time, yet, since there was nothing to show for. My intention, is to point out the existence of the classes and prepare a pull request for the Gviz repo. However, I need these classes and I don't know, what the response will be, so I implemented them for now.

> - You shouldn't need to run valid* functions in the show method, this
> should be done at class creation.

The `validAggregate` and `validModification` function do not check the validity of the object, but the validity of the contained data. Since changing a setting invalidates the aggregate data, these function check for this scenario. A warning is shown for `show` and `modifications`.

> - Be more specific with error messages rather than 'Something went wrong.' If it is an internal error, you can tag it with ''.

Done

> - Use default arguments such as input = list() instead of assigning after a
> check for missing().

Done. However, if a default value is not defined in the S4 Generic, a default value in method will not be set. Therefore the missing value has to be caught. I removed all instances, for which it was not necessary, but some remain (see `visualizeData`)

> - It may be useful to create a helper function to test input[["x.measure"]]
> for non-zero, NA, and blanks instead of using a series of if and else calls,
> especially when you run this check on several occasions.

I agree, but `input[["x.measure"]]` is only used in this on location. I simplified it a bit.

In general the input checks are run just once upon creation of an object.

> - You may benefit from using a map to check arguments for .norm_plot_args and
> others. This map will indicate (as separate columns) the error message, assert
> function, and name in input to check for all those that exist.

Could you clarify this point? I am not sure that I grasp the concept completely

> - Avoid nesting lapply, where possible.

I could only find one instance. Since the `path` function is not available for a `BamFileList`, I don't have an alternative option.

> - There's a lot of code in the package and I wasn't able to review all of it.

Yeah it is a bit big. Thats why split of the other strategies for RiboMethSeq and AlkAnilineSeq


> Minor:
> Avoid name clashing objects with function names, e.g., list <- …

Done for `list`, `c`, `names`, `seqnames`

> No need to wrap character/logical/numeric scalars with the c() function.

Done

> Use Map to avoid SIMPLIFY = FALSE argument in mapply.

Done

> No need to check if(X == TRUE), simply do if (X). The inverse also applies,
> i.e., if (!X) is preferred over if(X == FALSE)

Done

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 

Thanks for making the changes!
Please see the responses below.

Mit freundlichem Gruß,
Marcel

---

> A settings function seems a bit vague as to what it does. It would be
helpful for users to have a more descriptive name, if possible.
Also, see AnnotationHub for a similar generic.

>> I had a look at the generics from the AnnotationHub package, but none of
those seem to be reusable for purpose of tracking settings for a detection
strategy. Which generic did you have in mind?
To describe the purpose of the settings function more clearly, I added a
separate man page.

Sorry it's not a generic but a way of keeping track of options in the package.
Please see `.AH_hub_options` variable in the `R/AnnotationHubOption.R` file.

>> I included clear statement for the intended audience at the beginning of
the creation vignette. I hope I can leave the creation vignette in the
package. The intention is just to have a comprehensive description of how to
extend from the classes.

Yes, you can keep it in the package. It will be useful for developers.

> Signature arguments in setGeneric are not required as they match the formal
arguments unless you are using lazy evaluation.

>> I used this for me to keep track of, what I consider required non optional
input. This should make it a bit easier down the line, if someone wants to
reuse the functionality. Is that ok?

Yes, this should be okay but I'm not sure of the implications of this. Perhaps,
Martin (@mtmorgan) or Hervé (@hpages) has some insight on this.

> I agree, but input[["x.measure"]] is only used in this on location. I
simplified it a bit.
In general the input checks are run just once upon creation of an object.

Yes, but these input checks can be re-used when creating different objects.

> You may benefit from using a map to check arguments for .norm_plot_args and
others. This map will indicate (as separate columns) the error message, assert
function, and name in input to check for all those that exist.

>> Could you clarify this point? I am not sure that I grasp the concept completely

You can create a map with a row like:
`'AUC', 'is_a_bool', 'must be a single logical value'`
for all the types in your checks to reduce the amount of code needed to run
all the checks. You can then run a function for each of the rows. This is an
optional way to reduce the repetition in the code.

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY ,

Thanks for the clarification.

> > I agree, but input[["x.measure"]] is only used in this on location. I
> > simplified it a bit.
> > In general the input checks are run just once upon creation of an object.

> Yes, but these input checks can be re-used when creating different objects.

> > > You may benefit from using a map to check arguments for .norm_plot_args and
> > > others. This map will indicate (as separate columns) the error message, assert
> > > function, and name in input to check for all those that exist.

> > Could you clarify this point? I am not sure that I grasp the concept completely

> You can create a map with a row like:
> 'AUC', 'is_a_bool', 'must be a single logical value'
> for all the types in your checks to reduce the amount of code needed to run
> all the checks. You can then run a function for each of the rows. This is an
> optional way to reduce the repetition in the code.

I made some changes to the `settings` function and other input checks.

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY,

I updated a few things due to feedback I got. The warnings and errors are due to download issues on the SPB so I guess it is ready for the next review phase. Let me know what you think.

Best regards,
Felix

**Comment by FelixErnst** [comment]
Hi Marcel, @LiNk-NY 

sorry for the constant changes. I am done now.

@lshep it seems that the SPB has a bit of a bad day. Thanks for looking into.

Best regards
Felix

**Comment by FelixErnst** [comment]
Hi Lori and Marvel @lshep @LiNk-NY 

Should I trigger another build to remove the Abnormal status or should wait until the SPB is working correctly again? Thanks for any advice.

Felix

**Comment by lshep** [comment]
The SPB should be up and running as normal.  Please trigger another build with a version bump.

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 
I'll take another look at the package. Thanks for making those changes. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 
It's looking better! 
Thank you for your contribution. 
Best, 
Marcel

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY 

thanks for the review.

Best regards
Felix

@lshep: Thanks for all the support with the data package and help along the way.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RNAmodR.Data")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RNAmodR.Data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RNAmodR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RNAmodR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by FelixErnst** [comment]
@mtmorgan 

Thanks for adding the packages to the git repo. Will the other two packages `RNAmodR.RiboMethSeq` and `RNAmodR.AlkAnilineSeq` be added later once the other two packages have bin build correctly?

**Comment by mtmorgan** [comment]
These additional repositories have now been added.

**Comment by FelixErnst** [comment]
@mtmorgan @lshep 

Hi, I have a bit of a follow up question and I think I read the answer somewhere in the last year, but I can't seem to find it on the mailing list or the website, so here it goes again and I apologize for the redundancy in advance:

The experimental data packages are build nightly only on Linux, so that the nightly builds of packages dependent on a new data package, will report an error on Windows and macOS. Is that correct? If so, when will the data packages be build for Windows and macOS?

Maybe the answer to this question might make a good addition to https://bioconductor.org/developers/package-submission/#afteraccept
, if I wasn't just too blind to see it on the dev pages.

**Comment by lshep** [comment]
We currently only provide source packages for experimental data and only run them on linux and not on mac/windows.  This is something we are considering but haven't fully decided on doing yet.   I encourage you to post concerns or discussion about this on the community-bioc slack  bioc-build channel!   
https://join.slack.com/t/community-bioc/shared_invite/enQtNjYzMjc4ODk2ODA3LTM5ZDQ3ZjFmOWFkNjlkNjZmODM2YzI1YWQ5NGE2ZTYwMjM1YWUxM2E1NmM1MWFmZmU0Mjc3OWU4MTFjY2E0OTc

**Comment by FelixErnst** [comment]
Ok, does it just take one additional cycle before they become available on Windows and macOS?

I have seen a couple of packages, which depend on an experimental data package, but pass the nightly build without error on Windows and macOS.

**Comment by lshep** [comment]
Windows and mac should be downloading the source tars  of the experiment data as well.  It shouldn't take additional time as far as I am aware.   Remember for experiment data packages they aren't built nightly; 
they are built Sundays, Tuesdays, and Thursdays.

**Comment by FelixErnst** [comment]
Hmm, I was aware of the build schedule for the experimental data packages, but RNAmodR build fine on Linux yesterday and not on Windows and macOS. The error was package RNAmodR.Data not found, so I assumed, that it had something to do with the fact that the experimental packages are only build on Linux.

So maybe it was just a race condition. Lets wait for todays build.

Anyway, thanks again for taking the time clarifying the details.

**Comment by lshep** [comment]
I'll try to keep an eye on it too.  If it continues to fail just ping me again and I'll investigate more into it.
