### ISSUE TITLE
SAMEclustering

### ISSUE THREAD

**Issue by yycunc** [Bioconductor/Contributions#1110]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yycunc/SAMEclustering

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi @yycunc , 

Thank you for submitting your package to Bioconductor.

After a quick look at your DESCRIPTION file, you should `Depends: R (>= 3.6)` for the new bioc 3.10 devel. The `Title` seems to be a little redundant by saying `for Single Cell RNA seq data` in the end. 

I'll give an official review soon for the whole package. 

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @yycunc , 

Your package dependency `cidr` is not available as a CRAN / Bioconductor package. Bioconductor requires that all packages must be available via Bioconductor or CRAN because users and the automated build system have no way to install packages from other sources. See [here](http://bioconductor.org/developers/package-guidelines/#description) for more details. 

So you need to make sure: 
1. DESCRIPTION `Depends: R (>= 3.6)` instead of `R 3.5`. 
3. Find an alternative of `cidr` in your package, so that it could build successfully. 

Please let me know for any questions. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @yycunc , 

I wonder if you are working on fixing the above issues, because we usually expect responses (questions / updates / comments) to the official review in 2 weeks. Please let us know if you would need extended time to make the package work, and we will temporarily close the issue and reopen when you are ready. 

Thanks,
Qian

**Comment by yycunc** [comment]
Hi Qian,

Thanks for your reminding. Please temporarily close this issue, and I will let you know when I am ready to reopen it.

Thanks for your help!

Bests,

Yuchen

Yuchen Yang, Ph.D.
Postdoctoral Fellow, Department of Genetics
5100 Genetic Medicine Building
University of North Carolina at Chapel Hill
120 Mason Farm Road
Chapel Hill, NC, 27599
