### ISSUE TITLE
gwasrapidd

### ISSUE THREAD

**Issue by ramiromagno** [Bioconductor/Contributions#1124]
## Note

Please note that I am aware that  `BiocCheck::BiocCheck()` should give no errors and no warnings. I have one warning still:

```
"The following files are over 5MB in size: '.git/objects/pack/pack-fb9aec1c48d78e3166698db47359a703612078be.pack'"
```
I have followed the instructions here: https://bioconductor.org/developers/how-to/git/remove-large-data/ but to no avail.

## Submission form

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ramiromagno/gwasrapidd

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
For the duration of the review process, please update the 'master' branch to contain only files to be included in the R package.

Please provide 'accessors' rather than using direct slot access `@`, e.g., in the vignette.

The assigned reviewer will provide a more comprehensive review.

**Comment by ramiromagno** [comment]
Hi @mtmorgan:

Regarding the requirement: *providing 'accessors' rather than using direct slot access @*:

I am aware of the good practice of creating functions to access slots of S4 objects in general. Let me explain however why I think in my specific case it is more appropriate to use the slot access @ style rather than the setter/getter approach.

Here are the reasons:

-  All S4 objects in this package are created by the package and never by the user. These objects are the result of web requests to a REST API server.
- The different ways the user can change these objects is via exported functions from the package itself. There is not a use case where the user is expected to change the value of a slot, in the sense of a setter function.
- In this package, all S4 objects are really just mini-, in-memory, relational databases, effectively a list of tibbles, i.e., each slot is a tibble. The only way the user is expected to interact with those slots is to get data from it. So the @-style of accessing slots is perfectly suited here. Creating a getter for each slot would simply be redundant. Moreover, the principle of separating interface from implementation does not really apply here as the slot names are the perfect interface: each slot name stands for a table in the S4 object database. If I ever need to change the name of these tables, or deprecate them, then even if I had implemented getters, I would still have to change those getters anyway... My point is, implementation here and interface are one and the same thing.

**Comment by mtmorgan** [comment]
I appreciate that the data is 'read only' and that interface and implementation overlap. Nonetheless, please provide accessors, if only to discourage your users from thinking that all objects are as simple as yours.

**Comment by ramiromagno** [comment]
@dvantwisk:

Only the Windows builld is failing because of a timeout at this step:

```
** running examples for arch 'i386' ... ERROR
```

I don't know why. I can only speculate: maybe that environment does not provide internet connection and those examples hang waiting for a response...

**Comment by dvantwisk** [comment]
Sorry for the delay. It's not immediately clear what is causing the package to timeout of that architecture. First, you might consider trying a version bump to see if the issue repeats itself in a new build. Rarely, the builds fail for reasons other than the package.

Given windows does lack certain features it may be the case that either your package or packages that you are using may not be able to run on windows.

If the issue persists it is possible to tell the builder to ignore windows, however, this is not ideal since the package can't be guaranteed to work on this platform.

**Comment by ramiromagno** [comment]
@dvantwisk : the Win build is still timing out. I tried to install my package on a Windows machine and it seemed to work fine. So I am not sure why the building here is giving this timeout.

How should we proceed?

**Comment by dvantwisk** [comment]
It seems that the function `get_variants()` is eating up a lot of time on the windows builder. A good place to look to lower the runtime may be in the `get_variants.Rd` examples.

**Comment by lshep** [comment]
Hello,  actually hold off on investigating there... my fault, I was looking at something different... I will try to investigate the windows slow down but I probably won't be able to look at it until next week...

**Comment by lshep** [comment]
@dvantwisk  since the other two platform look ok you can review while I look into the windows issue.

**Comment by dvantwisk** [comment]
Okay, I'll begin reviewing the package.

**Comment by lshep** [comment]
From some testing it seems like it timeouts in windows because of the examples that open the web browsers.  In windows, the web browser will open but the code will not continue running until the window is closed, causing the process to hang.   The best solution is probably to put the examples that run code that produces these pop-ups/web browsers in `if (!interactive()){ }`    Cheers.

**Comment by ramiromagno** [comment]
Thanks @lshep! I am going to update the code.

**Comment by dvantwisk** [comment]
Here is a review of your package. I think the package looks very well written and I only have a few concerns. [REQUIRED] tags need to be addressed or the change need to be made. [CONSIDER] tags are changes that are advisable but not required. Please address these proposed changes and message me back when you are finished.

GENERAL
- [ ] [REQUIRED] Your package is 26MB in size. We tend to want to see our
repositories 5MB in size or less. Is there anywhere that you can reduce
the size of the package? If you deleted any large files and committed the
change, these files may still appear in your `.git` directory. You can
use the BFG-repo-cleaner https://rtyley.github.io/bfg-repo-cleaner/ to
remove deleted file from your `.git` history. 

R/GENERAL
- [ ] [REQUIRED] It seems that some of the generics and classes you are delcaring
and exporting have very common names. Problems can aarise if two generics with
the same name are declared in different packages and loaded at the same time.
For this reason, I need to ask that you make the names of your generics less
common or to use existing genrics from other pacakges. For example, you declare
a `union` generic but there is already a `union` generic present in the
`IRanges` package that has a similar declaration. You should be able to import
and use this generic for your own purposes. For Class names like `studies` I
would encourage you to use the name `GWASstudies` or something similar. Please
correct the following symbols:
    Classes:
    - associations
    - studies
    - traits
    - varients

    Generics:
    - union
    - intersect
    - setdiff
    - setequal
    - bind
    - n

R/browser.R
- [ ] [CONSIDER] L41: In the `open_in_gwas_catalog` function, consider using
`match.arg()` to declare `gwas_catalog_entity`. This would involve writing the
delcaration as `gwas_catalog_entity = c('study', 'varient', 'trait', etc..)`.
The default argument is the first element in the vector, `'study'`. The value
that the user selects can be obtained using
`gwas_catalog_entity = match.arg(gwas_catalog_entity)`. This method is
preferable because it allows the users to see possible values of
`gwas_catalog_entity` when they print the function. Also, an error will be
thrown if the user gives input outside of the allowed values. This can take the
place of the error check in lines L50-69. This can be done in multiple other
functions throughout the package.

R/sure.R
- [ ] [REQUIRED] It seems that the `sure()` function will only give a prompt during
an interactive session. However, I would imagine that there are cases where the
user would automatically want to answer "yes" instead of giving "yes" as input
during an interactive prompt and it doesn't seem that this functionality exists.
Can this functionality be added?

vignettes/gwasrapidd.Rmd
- [ ] [REQUIRED] There seems to be many uses of `eval=FALSE` here. Is there a reason
why these are being used? We would like all user-facing code to be run by the
build system, but recognize there are some cases that these can't be run in the
vignette (such as L107 where it would presumably open a web browser).

**Comment by ramiromagno** [comment]
Hi @dvantwisk:

Thank you for your review!

Before I start making changes to the code let me know your thoughts on these points:

1. My package size is big because of the mock files used for testing. I have reduced the number of files and the size per file used before submitting here to Bioconductor. Nevertheless, I believe they are leaving their footprint in the `.git` folder. As I said early in this issue, I have tried `bfg-repo-cleaner` but to no avail. So I am afraid that to really reduce the package size I would need to start a new git repository... I guess this implies discarding the git history so far, so I am a bit reluctant...
2. I am happy to change the S4 class names to something more specific, and I am aware of the `camelCaps`/`UpperCamelCase` convention. But would it be ok to use something like: `gwas_studies`, `gwas_associations`, `gwas_variants` and `gwas_traits`? (I have a preference for lowercase, underscore-separated words -- I promise I will be consistent).
3. With respect to the names of the generics, I will change them. But I must confess I picked them precisely this way because I thought their semantics would be obvious if the user was already acquainted with these functions in R base and dplyr.
4. The suggestion on using the `match.arg()` function seems like a really nice idiom. Will do!
5. Actually the `sure()` function already allows for non-interactive use but I realize now that this is not very clear from the documentation (`sure()` is not exported). I will make it more explicit that the user can set the parameter `default_answer` to `'yes'`/`'no'`, and that, then, `sure()` proceeds without interruption using `default_answer` as answer.
6. On your remark about the `eval=FALSE`, I will revise those code chunks. There might have been a reason at a certain point for doing that but I agree with you that it needs to change. Only the line that launches the browser will be left with `eval=FALSE`.

**Comment by dvantwisk** [comment]
1 ) The package size should be fine, I just want to be sure you know that we would like packages to take up a small amount of space. If there's nothing else that you can remove, I think the size is okay.

2) Yes, using the `gwas_*` syntax is okay.

3) Most R `base` functions are implemented as S4 generics in the `BiocGenerics` package. I encourage you to write methods for these and dispatch them on your classes. For example, the following are present in `BiocGenerics`:
```
> getMethod(c('setdiff'))
Method Definition (Class "derivedDefaultMethod"):

function (x, y, ...)
base::setdiff(x, y, ...)
<bytecode: 0x7fa7ff679ee0>
<environment: namespace:BiocGenerics>

Signatures:
        x
target  "ANY"
defined "ANY"
> getMethod(c('union')
+ )
Method Definition (Class "derivedDefaultMethod"):

function (x, y, ...)
base::union(x, y, ...)
<bytecode: 0x7fa7fd586790>
<environment: namespace:BiocGenerics>

Signatures:
        x
target  "ANY"
defined "ANY"
> getMethod(setdiff)
Method Definition (Class "derivedDefaultMethod"):

function (x, y, ...)
base::setdiff(x, y, ...)
<bytecode: 0x7fa7ff679ee0>
<environment: namespace:BiocGenerics>

Signatures:
        x
target  "ANY"
defined "ANY"
> getMethod(union)
Method Definition (Class "derivedDefaultMethod"):

function (x, y, ...)
base::union(x, y, ...)
<bytecode: 0x7fa7fd586790>
<environment: namespace:BiocGenerics>

Signatures:
        x
target  "ANY"
defined "ANY"
> getMethod(intersect)
Method Definition (Class "derivedDefaultMethod"):

function (x, y, ...)
base::intersect(x, y, ...)
<bytecode: 0x7fa7faa867d0>
<environment: namespace:BiocGenerics>

Signatures:
        x
target  "ANY"
defined "ANY
```
For `dplyr` methods, you are allowed to use delcare them as an s3 method. For example:
```
filter.gwas_study <- function(.data, ..., .preserve=FALSE)
{
 <your function>
}
```

6 ) It's likely that some of these `eval=FALSE`s were probably added to reduce the runtime on the windows machine that was timing out. Since it's no longer an issue, it doesn't seem that some of them are necessary.

**Comment by dvantwisk** [comment]
Hello,

Just touching base with you again. Have you or do you plan to make further changes to the package?

**Comment by ramiromagno** [comment]
Hi @dvantwisk:

I have not decided yet.

**Comment by dvantwisk** [comment]
Hi,
Just checking up on your progress with this issue. We generally like to see packages being actively worked on, or we close the issue within two weeks. Closed issues can be reopened when the package maintainer is ready to work on it again. Are you still actively working on correcting issues to this package?

**Comment by ramiromagno** [comment]
Hi @dvantwisk:

I think for the moment it is best to close this issue indeed.

Thank you for all the help though!
