### ISSUE TITLE
HCAMatrixBrowser

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#1129]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/HCAMatrixBrowser

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 
It seems like the API link to the HCA Matrix service is broken and causing the package to fail. 
It might be better to close the issue for now until this can get fixed through their new API
service. 
Best,
Marcel

**Comment by nturaga** [comment]
Got it.

**Comment by LiNk-NY** [comment]
@nturaga 

Update: I am using experimental / GitHub packages to make the HCAMatrixBrowser work. These include: 
[Bioconductor/AnVIL](https://github.com/Bioconductor/AnVIL)
[Bioconductor/AnVIL_rapiclient](https://github.com/Bioconductor/AnVIL_rapiclient)
[mtmorgan/HCAmtxzip](https://github.com/mtmorgan/HCAmtxzip)

Until we can get stable versions of these packages on Bioconductor, we can't add `HCAMatrixBrowser` to Bioconductor. 
Thanks.

CC: @mtmorgan

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 
It looks like the package is ready to review. Thanks!

**Comment by nturaga** [comment]
I'll review it soon @LiNk-NY

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 
Any updates on the review? 
Thanks :pray:

**Comment by nturaga** [comment]
Hi @mramos,

I'll try to do it today, but at the most by Monday evening. Sorry for the
delay.

Nitesh

**Comment by LiNk-NY** [comment]
Hi Nitesh, 

Any updates on the status? 
I think we also want this package in release? @mtmorgan 

Thanks!

**Comment by nturaga** [comment]
# Review HCAMatrixBrowser

## R CMD build

ok

## R CMD check

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## vignette

ok

## man

ok

## R

*  `for (ndot in 0:10) {`, 0 was deliberately included in this loop?
   Some documentation would be useful to follow parts of the code.
   
* Some of the functions `.is_scalar_character` can be used from the
  AnVIL package, `AnVIL:::.is_scalar_character()`instead of repeating
  code.
  
Overall a very well written package!

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 

Thank you for the review. 

I would use them if they were exported otherwise `R CMD check` will complain
about using `:::` triple colons.
We should think about creating a package with all of these utility
functions exported for everyone to use. 

Best,
Marcel

**Comment by nturaga** [comment]
Fair enough!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HCAMatrixBrowser")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HCAMatrixBrowser

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
