### ISSUE TITLE
NoRCE - Non-coding RNA sets Cis Enrichment Tool

### ISSUE THREAD

**Issue by guldenolgun** [Bioconductor/Contributions#1131]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/guldenolgun/NoRCE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I have not looked at your package closely, but probably many of the packages included in the Depends: field should be in Suggests: (i.e., used in examples or the vignette). @LiNk-NY will have a more complete review of your package.

**Comment by guldenolgun** [comment]
Hi @LiNk-NY ,

We are curiously waiting your response for our package. If you have any question please let us know.

Best.

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

Thank you for your submission. 
Currently, the package does not meet Bioconductor standards. 
Please see the review below and make considerable
improvements to the package for a second review. 

Best, 
Marcel

---

# NoRCE #1131

## DESCRIPTION

* Please move any packages that are relevant to the vignette from `Depends:`
to `Suggests:`.
* Include a `BugReports:` field
* Keep the format of the file tidy by keeping lines within 80 column widths

## NAMESPACE

* Are `readbed` and `readGMT` functions necessary? Some of these have been
written by other packages. See:
http://bioconductor.org/developers/how-to/commonMethodsAndClasses/
* You don't need to import from `TxDb.*` and `org.*.db` packages.

## vignettes

* Avoid using `eval=FALSE` in code chunks. This creates stale code quickly.
Pseudocode is not acceptable see line #256
* Keep the vignette formatted to 80 column width. It makes it easier to review
and edit
* Installation instructions should assume package is available via Bioconductor
* Move code comments outside of code chunks and into the Markdown prose
(especially long comments)
* Do not add `PNG` files when you can evaluate code and have a plot output

## R

* Create a table to map inputs to cells in the `data.frame` in the `annotate.R`
file. See Martin's example here:
https://stackoverflow.com/questions/39217432/r-improving-nested-ifelse-statements-multiple-patterns
* Avoid using `assign()`, the `go` object is being assigned to itself.
* Do not use `1:dim(x)[1]` sequence generation. Use the more robust
`seq_len(nrow(x))`
* Avoid providing 'dontrun' examples to your users. It will only create
frustration when such examples do not work because of a change in the code
base.
* Follow Bioconductor best practices and run `BiocCheck` on the package to see
recommendations with regards to `sapply`, `1:length(n)`, etc. Stay within the
80 column width recommendations. This makes for neater code.
* Consider renaming the `hg` argument to something more descriptive and less
specific such as 'genome'.
* Provide a vector of assembly options as an argument in `goEnrichment`and
related functions. This will let the user see what assemblies are available.
* See previous point and apply it to `pAdjust` methods in `goEnrichment`
* Create a function that will check whether the particular assembly is
available on the user's system otherwise return an error with a message saying
that the user should install the particular package needed for that assembly.
* I suggest you check out `cRegulome` package for the `miRCancer.db` and
see if that works for the purposes of `corrbased*` functions.
* Support either one or two `SummarizedExperiment` inputs in the `calculateCorr`
function
* Some functions do not provide type checks such as `geneGOEnricher`. They
should be checking that the inputs conform to a specific data type (e.g.,
"character" for Genes)
* Avoid interacting with the `.GlobalEnv` within the function scope.
* Create an package-specific environment for objects like "mart", "go", etc.
* Do not modify user-level options (see `R/getNearest.R#L1`)
* Avoid repetitive code in the `assembly` function
* There's a lot of unnecessary work here mapping genome symbols to `org.*`
package in `keggPathwayDB` where other packages have done this already (see
`EnrichmentBrowser`).
* Remove `.onLoad` message

## data

* Make use of `GO.db` package (thanks @lgeistlinger) and remove data from
`data/` folder or justify why the data you provided is different and
necessary. If the latter, consider providing an experiment data package
separately.

Minor:
* Use `nrow` or `ncol` for `dim()[1]` and `dim()[2]`, respectively.
* Use `file.path(x[1], x[2])` instead of
`paste0(x[1], "/", x[2], sep = "", collapse = "")`

**Comment by LiNk-NY** [comment]
Hi @guldenolgun 
Please provide an update / response to the review. 
Thank you. 
-Marcel

**Comment by guldenolgun** [comment]
@LiNk-NY , I would like to thank for your helpful feedback. I made major changes in the code. However, I would like to share my ideas some points that you raised.

In namespace, you suggested me check the common methods and classes for 'readbed' and 'readGMT' functions. rtracklayer package imports txt formatted bed file and lots of other package (not common methods) accept data frames as bed and read gmt file. Our 'readbed' function accepts both txt formatted bed file and data.frames that needs to be converted to the bed. None of the functions support both features. Also, there is no common method for reading gmt file. Thus, these functions are existed in the current version. 

In vignette, you mentioned "Pseudocode is not acceptable see line #256" . However, in this version, there is no pseudocode in this line. So, I could not fix this issue.

In R, you suggested me to check cRegulome package and see if it is suitable to use this package instead of using corrbased functions. However, functions of this package do not accept mRNA genes to get precalculated miRNA:mRNA correlation results for the given cancer. Also, none of the functions retrieve miRNAseq expression of the miRNA genes for the given cancer.  Moreover, before calling functions of this package, database connection should be performed in order to use functions. Thus, I kept the functions. 

Again in R, you suggested to avoid repetitive codes in assembly function. However, for each species, different org.* and different TxDb* data should be loaded and biomart object should be defined for the given species and the assembly. The only repetitive 2 line code is where data.frame UCSC data is converted to GRanges object and assigned to the global variable. Since I couldn't find a clear explanation for the scope of variables in if statement (since different programming languages have different variable scopes), I use same 2 line code for each statement to prevent the scoping error. 

You recommended me to use EnrichmentBrowser package for mapping the symbols. When I checked this package, related function returns Entrez IDs or GeneSetCollection object that gene symbols are contained. However, there is an issue that is raised in Bioconductor forum for GeneSetCollection that gene symbols in GeneSetCollection are not up-to-date and some of the gene names are not official HGNC symbol so that it has to be mapped with org.* databases (This problem is for the MSigDB but we cannot guarantee that the same problem cannot occur for the KEGG). This problem is very important for our package since only overlapped gene symbols are enriched and we only care the official HGNC symbols. To not miss the genes in the analysis, I kept the function as it is. 

https://support.bioconductor.org/p/110298/

Best Regards,

**Comment by LiNk-NY** [comment]
Hi @guldenolgun, 
I don't see how `readbed` would help users. There are functions already available that take a `data.frame` and produce a `GRanges` object (`GenomicRanges::makeGRangesFromDataFrame`) as well as functions that import `BED` files. 

Sorry, my line numbers were different at the time of the review.
I went back and looked at the line numbers with issues: `216`, `236`, `247` and all code chunks that include 'code' with the `eval=FALSE` flag. 
Update your code chunks to minimize the number of code chunks with `eval=FALSE`. 
Save your users the frustration when coming upon code that purportedly works only to find out
that it is stale. Please avoid that in your package.

Concerning `cRegulome` I was referring to the `miRCancer.db` database file in the package and was wondering if you could make use of it. 

The `assembly` function will not be accepted as it stands because it requires users to download all those packages. The code is pretty much the same for all except for some calls to the `useMart` function. This can be generated programmatically and without the need to install _all_ packages. 

I was referring to the specific implementation found in the `EnrichmentBrowser` which does all the mapping of  internally, see `.org2pkg` specifically. 

Best,
Marcel

**Comment by lawremi** [comment]
Agree about `readbed()`. Also see https://rdrr.io/bioc/GSEABase/man/getObjects.html for reading GMT files.

**Comment by LiNk-NY** [comment]
Devoid of further commentary. I will close the issue within the coming days. Thank you @guldenolgun

**Comment by guldenolgun** [comment]
@LiNk-NY , we are still working on your feedback. We completely changed the assembly function. However, we need couple of days.

**Comment by LiNk-NY** [comment]
Hi @guldenolgun, 
Please make sure your changes are in before Monday 10/21 COB
so that I can have a last look at them. The hard deadline is October 23<sup>rd</sup>. 
Thank you.
-Marcel

**Comment by LiNk-NY** [comment]
Hi @guldenolgun,

I had a look at your `DESCRIPTION` file and it seems that
you are putting `TxDb.*` packages in the `Depends` field. 
This would make your package incredibly inconvenient to
load given that you need several database packages loaded
before use. 
 * Remove those packages from the `Depends` field and move
them to the `Suggests`. Load them conditionally for functions
that need them by using:

```
if (!requireNamespace(<PKGNAMEHERE>, quietly = TRUE))
    stop("Install package A in order to use this function.")
```

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

Please refer to https://bioconductor.org/developers/how-to/buildingPackagesForBioc/
For more information about package `Imports` and `Depends` fields. 
You should only have a minimal number of packages that you `Depend` on. Packages
in the `Depends` field are packages for which you are extending the codebase or
creating derivative classes (such as for `SummarizedExperiment`). 
Otherwise, most packages should be in the `Imports` field in the `DESCRIPTION` file.

Also, please have a look at your `check` results. There are a number of issues / notes
to take care of. For example:

```
* checking installed package size ... NOTE
  installed size is 10.1Mb
  sub-directories of 1Mb or more:
    data   9.7Mb
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘dbplyr’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
package 'methods' is used but not declared
* checking R code for possible problems ... NOTE
createNetwork: warning in adjustcolor(c("gray50", "tomato", "gold",
  "yellowgreen", "dark orange", "red", "blue", "green"), alpha = 0.6):
  partial argument match of 'alpha' to 'alpha.f'
mirnaGOEnricher: warning in goEnrichment(gene = miNearGene, GOtype =
  pkg.env$GOtype, org_assembly = org_assembly, pCut = pkg.env$pCut,
  pAdjCut = pkg.env$pAdjCut, pAdjust = pkg.env$pAdjust, backG =
  backGenes, backGType = backGType, min = pkg.env$min, enrichTest =
  pkg.env$enrichTest): partial argument match of 'gene' to 'genes'
mirnaRegionGOEnricher: warning in goEnrichment(gene = miNearGene,
  GOtype = pkg.env$GOtype, org_assembly = org_assembly, pCut =
  pkg.env$pCut, pAdjCut = pkg.env$pAdjCut, pAdjust = pkg.env$pAdjust,
  backG = backG, backGType = backGType, min = pkg.env$min, enrichTest =
  pkg.env$enrichTest): partial argument match of 'gene' to 'genes'
KeggEnrichment: no visible global function definition for ‘new’
WikiEnrichment: no visible global function definition for ‘new’
annGO: no visible binding for global variable ‘td’
calculateCorr: no visible global function definition for ‘assay’
calculateCorr: no visible global function definition for ‘isEmpty’
commonGene: no visible global function definition for ‘queryHits’
commonGene: no visible global function definition for ‘subjectHits’
commonGene: no visible global function definition for ‘isEmpty’
corrbased: no visible binding for global variable ‘conn’
corrbasedMrna: no visible binding for global variable ‘mirna_base’
corrbasedMrna: no visible binding for global variable ‘feature’
drawDotPlot: no visible binding for global variable ‘Pvalue’
drawDotPlot: no visible binding for global variable ‘EnrichGeneNumber’
drawDotPlot: no visible binding for global variable ‘PAdjust’
geneGOEnricher: no visible binding for global variable ‘tad_hg19’
geneGOEnricher: no visible binding for global variable ‘tad_dmel’
geneGOEnricher: no visible binding for global variable ‘tad_hg38’
geneGOEnricher: no visible binding for global variable ‘tad_mm10’
geneGOEnricher: no visible global function definition for ‘new’
genePathwayEnricher: no visible binding for global variable ‘tad_hg19’
genePathwayEnricher: no visible global function definition for ‘new’
geneRegionGOEnricher: no visible binding for global variable ‘tad_hg19’
geneRegionGOEnricher: no visible binding for global variable ‘tad_dmel’
geneRegionGOEnricher: no visible binding for global variable ‘tad_hg38’
geneRegionGOEnricher: no visible binding for global variable ‘tad_mm10’
geneRegionGOEnricher: no visible binding for global variable ‘geneLoc’
geneRegionGOEnricher: no visible global function definition for ‘new’
geneRegionPathwayEnricher: no visible binding for global variable
  ‘tad_hg19’
geneRegionPathwayEnricher: no visible binding for global variable
  ‘geneLoc’
geneRegionPathwayEnricher: no visible global function definition for
  ‘new’
getNearToExon: no visible global function definition for
  ‘subsetByOverlaps’
getNearToIntron: no visible global function definition for
  ‘subsetByOverlaps’
getTADOverlap: no visible binding for global variable ‘tad_hg19’
getTADOverlap: no visible binding for global variable ‘tad_dmel’
getTADOverlap: no visible binding for global variable ‘tad_hg38’
getTADOverlap: no visible binding for global variable ‘tad_mm10’
getTADOverlap: no visible binding for global variable
  ‘subsetByOverlaps’
getTADOverlap: no visible global function definition for
  ‘subsetByOverlaps’
getUCSC: no visible global function definition for ‘subsetByOverlaps’
getUCSC: no visible global function definition for ‘unstrand’
getmiRNACount: no visible binding for global variable ‘study’
getmiRNACount: no visible binding for global variable ‘mirna_base’
goEnrichment: no visible global function definition for ‘new’
mirnaGOEnricher: no visible binding for global variable ‘tad_hg19’
mirnaGOEnricher: no visible binding for global variable ‘tad_dmel’
mirnaGOEnricher: no visible binding for global variable ‘tad_hg38’
mirnaGOEnricher: no visible binding for global variable ‘tad_mm10’
mirnaGOEnricher: no visible global function definition for
  ‘findOverlapPairs’
mirnaGOEnricher: no visible global function definition for ‘new’
mirnaPathwayEnricher: no visible binding for global variable ‘tad_hg19’
mirnaPathwayEnricher: no visible binding for global variable ‘tad_dmel’
mirnaPathwayEnricher: no visible binding for global variable ‘tad_hg38’
mirnaPathwayEnricher: no visible binding for global variable ‘tad_mm10’
mirnaPathwayEnricher: no visible global function definition for
  ‘findOverlapPairs’
mirnaPathwayEnricher: no visible global function definition for ‘new’
mirnaRegionGOEnricher: no visible binding for global variable
  ‘tad_hg19’
mirnaRegionGOEnricher: no visible binding for global variable
  ‘tad_dmel’
mirnaRegionGOEnricher: no visible binding for global variable
  ‘tad_hg38’
mirnaRegionGOEnricher: no visible binding for global variable
  ‘tad_mm10’
mirnaRegionGOEnricher: no visible global function definition for
  ‘findOverlapPairs’
mirnaRegionGOEnricher: no visible global function definition for ‘new’
mirnaRegionPathwayEnricher: no visible binding for global variable
  ‘tad_hg19’
mirnaRegionPathwayEnricher: no visible binding for global variable
  ‘tad_dmel’
mirnaRegionPathwayEnricher: no visible binding for global variable
  ‘tad_hg38’
mirnaRegionPathwayEnricher: no visible binding for global variable
  ‘tad_mm10’
mirnaRegionPathwayEnricher: no visible global function definition for
  ‘findOverlapPairs’
mirnaRegionPathwayEnricher: no visible global function definition for
  ‘new’
pathwayEnrichment: no visible global function definition for ‘new’
reactomeEnrichment: no visible global function definition for ‘new’
reactomePathwayDB: no visible binding for global variable
  ‘org.Sc.sgd.db’
topEnrichment : split_tibble: no visible binding for global variable
  ‘.’
Undefined global functions or variables:
  . EnrichGeneNumber PAdjust Pvalue assay conn feature findOverlapPairs
  geneLoc isEmpty mirna_base new org.Sc.sgd.db queryHits study
  subjectHits subsetByOverlaps tad_dmel tad_hg19 tad_hg38 tad_mm10 td
  unstrand
Consider adding
  importFrom("methods", "new")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
```

Make sure that your functions are not running `browseURL` during package
check. Use this function only when `identical(interactive(), TRUE)`. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

It looks like you already have import directives (`@importFrom` tags) for the packages in the
`Depends` field in the `DESCRIPTION` file. You're set up for selective importing. You just
need to move them to the `Imports` field. 

Thank you.
-Marcel

**Comment by lshep** [comment]
We are updating our new package submission builders to R 4.0 and Bioc 3.11 -  The ERROR of the missing dependency is on our end and we are investigating

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 
The installation size for the package is considerably higher than our 5 MB limit.
Is there a way to reduce the size of the data folder?
Otherwise consider creating an ExperimentHub package.
See: https://bioconductor.org/packages/devel/bioc/html/ExperimentHub.html

```
* checking installed package size ... NOTE
  installed size is 10.4Mb
  sub-directories of 1Mb or more:
    data   9.7Mb
```

**Comment by guldenolgun** [comment]
Hi @LiNk-NY ,
Bioconductor package guideline reports that software package should be <=5MB. However, to best of my knowledge, there is no space limitation for the experimental packages. 

For target analysis, some data files have to be present in the folder.

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 
As far as I can tell, you're submitting an software package and _not_ an 
experiment data package. 
You should only include enough data to be able to run examples for demo
purposes. These data can be a subset of the original data. 

If you need to include data that is not already part of another experiment
data package or that is in a format that is not found in other packages,
you should submit these data as an ExperimentHub package. 

Best, 
Marcel

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 
Any updates on the status of the package(s)? 
Thanks.

**Comment by guldenolgun** [comment]
Hi @LiNk-NY ,
I removed the additional data from the package. I will push the new version.

Thanks.

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

I really appreciate your efforts on sticking with the review process and
continually improving the package. 

You should really include `NoRCE-data` as a separate [`ExperimentHub`](https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html) package 
submission rather than downloading from `https://raw.githubusercontent.com/*`
**_if_** the data is really necessary. If the data is available from other sources, I would
recommend a direct download from the organization website and caching using
`BiocFileCache`.

If these data is available in Bioconductor `*.org` experiment data packages,
please make use of those packages instead by conditionally loading the
package (include them in the `Suggests:` field) and use `requireNamespace`. 

Best, 
Marcel

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 
Any updates on the status of the package? 
Thank you.

**Comment by guldenolgun** [comment]
AdditionalPackage: https://github.com/guldenolgun/miRTargetForSpecies

**Comment by guldenolgun** [comment]
AdditionalPackage: https://github.com/guldenolgun/miRTargetForSpecies

**Comment by guldenolgun** [comment]
Hi @LiNk-NY , 
I added a new ExperimentalHub package. Since it builds with errors, I modified it. How can I make it to rebuild the package? In the description file of this new package, I have already modified its version. 

Thanks.

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

You should be able to bump the version package and get the SPB to re-build the package. 

Best,
Marcel

**Comment by guldenolgun** [comment]
Hi @LiNk-NY , 
I am really sorry but I couldn't get your comment. What do you mean by bump the version package? The additional package version is 0.99.2 (since I made changes after build error). Should I change it to the actual package(NoRCE package) version (0.99.25)? As far as I understand, without acceptance of the additional package, I cannot use the additional package data in NoRCE through the ExperimentHub. 

Thank you.

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

Please bump the version in the additional package's `DESCRIPTION` file like this: 

```diff
Package: miRTargetForSpecies
Type: Package
Title: miRTargetsForSpecies : Collection of miRNA Target Prediction Data
   for Various Species
- Version: 0.99.2
+ Version: 0.99.3
```

and push the changes to your repository. 

Best,
Marcel

**Comment by guldenolgun** [comment]
Hi Marcel @LiNk-NY , 

It is really strange because I changed the Description file like this

- Version: 0.99.2
+ Version: 0.99.3

Then, I changed it as 
Version: 0.99.3

Then I thought, it requires a new version, I changed it as 
Version: 0.99.4

No, nothing is working. 

Thanks

**Comment by LiNk-NY** [comment]
@guldenolgun Did you create a webhook for the additional package? It may not be activated and therefore not buildling. 
Thanks,
Marcel

**Comment by guldenolgun** [comment]
Oh, I didn't add it. I think that's the problem. 

Thanks @LiNk-NY .

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 
For the next step, you will have to get in contact with Lori @lshep for access to our AWS bucket for data upload and indexing into our database. 
Her email is listed here: 
https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html#uploading-data-to-s3

Thanks,
Marcel

**Comment by guldenolgun** [comment]
Hi Marcel @LiNk-NY , 
Can Bioconductor system allow us to delete the additional package completely? If so, how can I delete my additional package from the system? After the deletion without an additional package, can my main package pass the all test and be labeled as OK? 

Thank you.

**Comment by LiNk-NY** [comment]
Hi Gulden, @guldenolgun 

Yes, we can include `NoRCE` in Bioconductor devel and leave the data package out. 
Does `NoRCE` have any code that depends or uses the data package? 
If not, I can go ahead and accept it and let Martin know to **exclude** the `AdditionalPackage: https://github.com/guldenolgun/miRTargetForSpecies`. 

Thanks,
Marcel

**Comment by LiNk-NY** [comment]
I had a quick look and it doesn't seem to be the case. I will accept the package and remind @mtmorgan that `miRTargetForSpecies` will **not** be included. Thank you for your contribution! 
:1st_place_medal: 
-Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/guldenolgun.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NoRCE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NoRCE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
