### ISSUE TITLE
SigsPack

### ISSUE THREAD

**Issue by fefschumann** [Bioconductor/Contributions#1136]
- Repository: https://github.com/bihealth/SigsPack

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Please fix all ERROR/Warnings before @dvantwisk begins a formal review -  Your package currently is missing the require [NAMESPACE file](http://bioconductor.org/developers/package-guidelines/#namespace).

**Comment by dvantwisk** [comment]
Hello,

Have you made progress with adding a `NAMESPACE` to your package like explained above? We want to see packages actively being worked on (within a two-week period) or else we need to close the issue. If an issue if closed, it can be re-opened at a later date when the maintainer is ready to make changes.

**Comment by fefschumann** [comment]
Hi,

we have added a NAMESPACE file and fixed all the errors that are coming up when we build the package on our machine, but it looks like the push wasn't recognized. Do we need to change the version number?

**Comment by dvantwisk** [comment]
Hi @fefschumann 

Here is the review of your package. I think the code is well written and I only have a few concerns with the vignette. Email me back once you have addressed the following issues:

vignettes/SigsPack.Rmd
- [ ] [REQUIRED] You use `eval=FALSE` multiple times in this vignette. We
generally want to see user facing code run by our builders. Is there a reason
why you are using this? There are situations where it is acceptable such as when
the code opens a ui.
- [ ] [REQUIRED] The line mentioning installing from github for the devel verion
can be removed. `BiocManager::install(version = "devel")` can be used to install
devel versions of Bioconductor packages.

**Comment by dvantwisk** [comment]
Hi,
I'm just checking in again since this issue hasn't been updated in a while. Are you making the changes that I prescribed above? We generally like to see packages be actively worked on within a two week period, of we close the issue. Closed issues can be reopened when the package maintainer is ready to continue work on the package. Are you still working on making changes to this package?

**Comment by fefschumann** [comment]
Dear @dvantwisk,

we have addressed the issues you mentioned in your review and pushed the new version.

**Comment by dvantwisk** [comment]
The changes look good! I'm going to move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fefschumann.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SigsPack")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SigsPack

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
