### ISSUE TITLE
MetaVolcanoR

### ISSUE THREAD

**Issue by csbl-usp** [Bioconductor/Contributions#1142]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/csbl-usp/MetaVolcanoR

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
- please include in the 'master' branch of your repository only the files necessary for your R package

vignette

- please update the installation instructions to reflect standard Bioconductor practice, as seen on package landing pages. 

- Please mark the installation instruction with `eval = FALSE` to avoid installing the package each time the vignette is processed.

R

- please carefully examine your code for opportunities to 'vectorize' -- replace many calls to the same R function with one call. As a simple example, calc_vi.R has

    ```
    diffexp[['vi']] <- apply(diffexp, 1, function(gene) {
        ((as.numeric(gene[rlcol]) - as.numeric(gene[llcol]))/3.92)^2
    })
    ```
    
  which can instead without the `apply()` loop as
  
    ```
    diffexp[['vi']] <-
        ((as.numeric(gene[rlcol]) - as.numeric(gene[llcol]))/3.92)^2
    ```

  This issue is pervasive in your code.
  
- combining_mv.R:44 it is highly likely that the overhead of multicore (parallel) evaluation here and elsewhere provides at best minimal performance improvements while making the code much more fragile -- reconsider use of `mclapply()` here and elsewhere, especially in the light of 'vectorized' code.

- combining_mv.R:166 check inputs as the first step of the function, rather than part way through.

**Comment by Bionett** [comment]
Dear Martin @mtmorgan,

Thanks for your review. I've addressed the points you raised.

- The master branch now contains the necessary files.

- The vignette installation section is now according to the standard Bioconductor practice.

- The use of mclapply and 'vectorization' was reconsidered over the whole package. Parallel mclapply was conserved in the rem_mv() function where it does make a running time difference.

- Input checks are now the first steps in all functions.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/csbl-usp.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MetaVolcanoR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaVolcanoR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
