### ISSUE TITLE
SharedObject

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/Contributions#1153]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jiefei-Wang/SharedObject

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
What about using arrow for this?

**Comment by Jiefei-Wang** [comment]
Hi @lawremi , I'm sorry I don't understand your question, could you please elaborate it? Thank you!

**Comment by mtmorgan** [comment]
https://arrow.apache.org/

**Comment by Jiefei-Wang** [comment]
@mtmorgan Thanks, I will take a look at it.

**Comment by hpages** [comment]
Hi Jiefei @Jiefei-Wang,

Is the package ready for review?

Thanks,
H.

**Comment by Jiefei-Wang** [comment]
Hi Hervé @hpages ,

Yes, I think Nitash @nturaga is reviewing it since you are in a vaca. He gave me some comments today so I made a commit. 

Best,
Jiefei

**Comment by hpages** [comment]
Thx Jiefei.

@nturaga Nitesh can you please post your comments here? Thanks!

**Comment by nturaga** [comment]
# SharedObject review

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

ok

## NAMESPACE

* Why are you exporting "private" functions which start with a
  ".". You can just rename them without the "." if the intention is to
  export them.

		export(.getDataInfo)
		export(.getProperty)
		export(.removeAllObject)
		export(.removeObject)
		export(.setProperty)
		
## NEWS

ok

## R

* Get rid of extra lines. pkgSetting.R L1-4. There are also plenty of
  formatting issues throughout your codebase. Extra lines, commented
  out code, 2 space vs 4 space indentation etc. Check
  http://bioconductor.org/developers/how-to/coding-style/. See also
  formatR package.

* don't actually need to `return` in R. It happens anyway.

* Why are you exporting "Internal functions" ? eg: `.removeAllObject`?

* In the function `invisible()`, i think it's standard practice to
  return an object within the function. eg: `f2 <- function(x)
  invisible(x)`.
  
  This function can be useful when it is desired to have functions
  return values which can be assigned, but which do not print when
  they are not assigned.
  
  In functions like, `removeObject_single`, I don't believe
  `invisible()` is needed.
  
  Can you exlain why you used it?

**Comment by Jiefei-Wang** [comment]
Hi Nitash,

Thanks for your comments. Here are some notes from the revision.

**1. Get rid of extra lines. pkgSetting.R L1-4. There are also plenty of formatting issues throughout your codebase. Extra lines, commented out code, 2 space vs 4 space indentation etc.** 

The formatting issues have been fixed.

**2. Don't actually need to return in R. It happens anyway.**

I've removed the unnecessary return. There are some left because they do not happen at the end of the function.

**3. Why are you exporting "private" functions which start with a "."( eg: .removeAllObject). You can just rename them without the "." if the intention is to export them.**  

They are designed for special cases. For example, if R crashed unexpectedly and the GC did not have a chance to release the memory, calling the function .removeObject() in a new R session can solve the memory leaking problem. These functions are not expected to be used in a normal case so that I add `.` to indicate they should be treated as internal-like functions.

I have renamed the function .getDataInfo and make it publicly viewable since it might be useful in normal case. The function .removeAllObject is removed from the package.


**4. the function invisible().**

For the function like removeObject_single(), I have deleted invisible() since they are only used internally. 

For exported functions, some of them do not have a return value, but they will return NULL or NA or something else, so I add an invisible() at the end of the function to suppress the unnecessary message.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment]
Hi @hpages and @nturaga 

I have finished updating the package. It is ready for review now.

Best,
Jiefei

**Comment by nturaga** [comment]
@hpages I'll leave this in your court now for the review of the `src` code.

**Comment by hpages** [comment]
Hi guys,

Turns out that the package uses C++, not C, so I'm not really in a position to provide much feedback on the C++ code 'cause I'm not a C++ guy, sorry! One thing I noticed though is that compilation with `-Wall` produces some warnings that maybe should not be ignored, I don't know. Examples of such warnings:
```
...
g++ -std=gnu++11 -I"/home/hpages/R/R-3.6.r76454/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I"/home/hpages/R/R-3.6.r76454/library/BH/include" -I"/home/hpages/R/R-3.6.r76454/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -Wall -c memoryManager.cpp -o memoryManager.o
In file included from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/smart_ptr/shared_ptr.hpp:28:0,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/shared_ptr.hpp:17,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/date_time/microsec_time_clock.hpp:18,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/detail/posix_time_types_wrk.hpp:31,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/sync/scoped_lock.hpp:35,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/allocators/detail/allocator_common.hpp:32,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/allocators/allocator.hpp:30,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/segment_manager.hpp:38,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/detail/managed_memory_impl.hpp:30,
                 from /home/hpages/R/R-3.6.r76454/library/BH/include/boost/interprocess/managed_shared_memory.hpp:25,
                 from memoryManager.cpp:14:
/home/hpages/R/R-3.6.r76454/library/BH/include/boost/smart_ptr/detail/shared_count.hpp:355:33: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
...
```
and
```
...
memoryManager.cpp:226:31:   required from here
/home/hpages/R/R-3.6.r76454/library/BH/include/boost/container/detail/tree.hpp:172:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
...
```
It could be that these warnings originate from the C++ code in the BH package in which case I'm not sure there's anything you can do about them (except maybe report them to the BH folks).

Note that you need to edit your `R_HOME/etc/Makeconf` file and add the `-Wall` flag to the appropriate variables if you want `R CMD INSTALL` to use this flag during compilation (FYI this is a setting that we use on the build system for the nightly builds).

One more thing about the C++ code (from the perspective of a C guy): I'm not sure I understand why you declare the data info fields as standalone variables in `tools.h`:
```
#define X(id,type, name) extern const ULLong dataInfo_##name;
DATAINFO_FIELDS
#undef X
```
and then initialize them in `tools.cpp`:
```
#define X(id,type, name) const ULLong dataInfo_##name=id;
DATAINFO_FIELDS
#undef X
```
since you don't seem to use these variables anywhere.

Other than that, from the naive perspective of a C-only guy, it's pretty clear that the C++ code was written by someone who knows his way around the complexity of this language. So congrats! Especially for managing to use the boost::interprocess component and make all this compile and work on all platforms. Quite impressive!
  
I was curious to try the package and while I was playing with it I found a few minor things that I thought would be worth reporting. So here you go...

### Other things

- Man page for `getSharedProperty()` says the function returns a `sharedMemory` object but I get a `sharedProperty` object.

- All the properties are displayed as floating point values:
    ```
    x=share(1:10)
    getSharedProperty(x)
    #       dataId    processId       typeId       length    totalSize  copyOnWrite 
    #   8.8189e+15   5.0590e+03   2.0000e+00   1.0000e+01   4.0000e+01   1.0000e+00 
    # sharedSubset   sharedCopy 
    #   1.0000e+00   0.0000e+00 
    # attr(,"class")
    # [1] "sharedProperty"
    ```
    which is not pretty, especially in the case of toggles `copyOnWrite`, `sharedSubset`, and `sharedCopy`, which are booleans in nature.

- I was hoping that using `as.list=TRUE` would produce a better display (i.e. a display that reflects the type of the properties) but it doesn't:
    ```
    getSharedProperty(x, as.list=TRUE)
    # [[1]]
    #       dataId    processId       typeId       length    totalSize  copyOnWrite 
    #   8.8189e+15   5.0590e+03   2.0000e+00   1.0000e+01   4.0000e+01   1.0000e+00 
    # sharedSubset   sharedCopy 
    #   1.0000e+00   0.0000e+00 
    # attr(,"class")
    # [1] "sharedProperty"
    ```
    I was expecting that using `as.list=TRUE` would give me something like this instead:
    ```
    as.list(getSharedProperty(x))
    # $dataId
    # [1] 8.8189e+15
    #
    # $processId
    # [1] 5059
    # 
    # $typeId
    # [1] 2
    #
    # $length
    # [1] 10
    #
    # $totalSize
    # [1] 40
    #
    # $copyOnWrite
    # [1] 1
    # 
    # $sharedSubset
    # [1] 1
    #
    # $sharedCopy
    # [1] 0
    ```
    Returning the properties in a list should probably be the default anyway. Even though all properties are still represented by numeric values, at least they no longer get automatically displayed in scientific notation (only the big numbers are). And because the object is a list, individual properties can conveniently be retrieved using `$` (e.g. `getSharedProperty(x)$length`), which doesn't work on the atomic vector currently returned by `getSharedProperty(x)`.

    Finally note that the `as.list` argument then would have very little value because it's reasonable to assume that anybody would know they can use `unlist()` on this list to get the properties in an atomic vector.

- Maybe display a more useful and less cryptic error message when calling getSharedProperty() on a non-shared object:
    ```
    y <- 1:4
    getSharedProperty(y)
    # Error: Expecting a single value: [extent=0].
    ```

- Have you considered naming the function `getSharedProperties` instead of `getSharedProperty`?

- Similarly it seems that using the plural form for `dataInfoPropName` and `dataInfoName` would make sense (IMO it slightly improves the code readability/clarity, especially since you use the plural form for other things like `sharedOptions` and `completeOptions`).

- Is this expected?
    ```
    library(SharedObject)
    for (i in 1:1200) {x <- share(1:10); rm(x)}
    # Error in C_createSharedMemory(x, dataInfo) : 
    #   Can't create a shared object, data ID 8432063514411008, has key:0 
    # Too many open files
    ```
    Also the memory never seems to be released (running `top` in another terminal reports that memory usage is growing). Then, when I quit R I get:
    ```
    q("no")
    # Error in gzfile(file, "rb") : cannot open the connection
    # In addition: Warning message:
    # In gzfile(file, "rb") :
    #   cannot open compressed file '/home/hpages/R/R-3.6.r76454/library/tools/Meta/nsInfo.rds', probable reason 'Too many open files'
    ```
    FWIW if I restart R and do the above again but this time with a call to `gc()` in the loop, I still get into  trouble (but note that this time the error message is slightly different):
    ```
    library(SharedObject)
    for (i in 1:1200) {x <- share(1:10); rm(x); gc()}
    # Error in C_createSharedMemory(x, dataInfo) : 
    #   Can't read shared object:Too many open files
    ```
    However this time the memory used by the shared objects seems to be released (it doesn't grow according to `top`).

- Typo in `calculateSharedMemerySize` ("Memery" instead of "Memory").

- "of" missing in "Is an Object a desired type?". Should be "Is an Object of a desired type?". Also no need to capitalize "Object", could just be "object".

- Always put spaces around the assignment e.g. do `x = share(1:10)` instead of `x=share(1:10)`. Note that the left arrow (`<-`) is actually preferred for assignment.

H.

**Comment by nturaga** [comment]
@Jiefei-Wang Your package needs a version bump to build again.

**Comment by Jiefei-Wang** [comment]
Thanks @nturaga . I have made the bump and push it to GitHub,

**Comment by Jiefei-Wang** [comment]
Hi @hpages , the package is ready for review. Most of your review comments have been solved. The only one left is the warnings during the compilation. The warnings are from the boost library and there is not too much we can do. Although there are warnings but it seems that the package is working as expected, the error you saw is irrelevant to the warnings. I can try to ask the boost team and hopefully they will have an answer for it.

**Comment by hpages** [comment]
Hey @Jiefei-Wang We're good to go. @nturaga already provided a formal review and it seems that you've addressed all our concerns. Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jiefei-Wang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SharedObject")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SharedObject

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
