### ISSUE TITLE
amplican

### ISSUE THREAD

**Issue by JokingHero** [Bioconductor/Contributions#116]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/valenlab/amplican

Confirm the following by editing each check box to '[x]'
- [ x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [ x ] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [ x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [ x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [ x ] The 'devel' branch for new packages and features.
- [ x ] The stable 'release' branch, made available every six
    months, for bug fixes.
- [ x ] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by JokingHero** [comment]
Hi,

moscato1 check is complaining:

** checking loading without being on the library search path ... WARNING
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'httr'
Error: package or namespace load failed for 'amplican'

I am rather puzzled as I do not state any dependency on package 'httr' nor I do not need this package  for anything I believe. Why is only windows having this problem not other systems? Should I add this package to dependencies?

Best,
Kornel

**Comment by AllenTiTaiWang** [comment]
I got the same warning message as yours,
don't know how to solve it, neither ..

**Comment by mtmorgan** [comment]
This seems to be a build system configuration issue that does not require a package author fix; @lshep might respond here with an update.

For this issue, httr is an indirect dependency via ggbio --> biovizBase --> ensembldb --> AnnotationHub

For https://github.com/Bioconductor/Contributions/issues/124,  httr is an indirect dependency  via methylumi --> minfi --> GEOquery

**Comment by mtmorgan** [comment]
Thanks for your contribution.

- Please spell check the DESCRIPTION, man, vignette, ... pages!

DESCRIPTION

- spell check

vignette

- please spell-check your vignette, e.g., 'posible' 'coffe', ...
- use a temporary location `tempfile()` or `tempdir()` in the vignette
  / examples, rather than writing to `getwd()`.
- avoid long lines of code, e.g., amplicanOverview.Rmd:97 by
  un-nesting function calls; don't use explicit path separators but
  rely on the function call to use the appropriate separator for the
  operating system in use.

        fl <- system.file("extdata", "results", "barcode_reads_filters.csv",
            package = "amplican")
        barcodeFilters <- read.csv(fl)

R

- Since a major novelty in this package is the implementation of the
  Gotoh alignment algorithm, consider exposing this as a stand-alone
  function. It would operate on input objects (from ShortRead and
  Biostrings?) rather than files, and would return objects that can be
  computed on (Biostrings::PairwiseAlignment?)
- use BiocParallel rather than doParallel / foreach for a more
  consistent interface across Bioconductor packages.
- use `file.path()` rather than `paste0()` to construct file paths.
- return meaningful values, perhaps using `invisible()`, from all
  functions. For instance, from `amplicanPipeline()` return
  `results_folder`
- avoid misuse of `ifelse()` for scalar tests (e.g.,
  amplicanAlign.R:128), use
  
      result <- if (test) {
          ## TRUE value
      } else {
          ## FALSE value
      }

  or similar (`ifelse()` is meant for use with vector arguments).
- avoid repeated calls to writeLine, e.g., amplicanAlign.R:180

        writeLines(
            c(paste("Config file:           ", "foo"), 
              paste("Processors used:       ", 2),
              paste("Skip Bad Nucleotides:  ", TRUE),
              ...),
            logFileConn)

- use `seq_len()` / `seq_along()` rather than `1:n` / `1:length(x)`
- choose an indentation scheme that does not result in highly
  indented, very short and illegible lines, as at amplicanAlign.R:222
- The output format from gRCPP contains familar concepts (e.g., an
  alignment CIGAR) but in an idiosyncratic format. Present this
  information in a standard representation.
- avoid direct slot access, e.g., helpers_alignment.R:181
  `ShortRead::sread(forwardsTable)` rather than `forwardsTable@sread`,
  `as(quality(reads), "matrix")` instead of `as(slot(reads,
  "quality"), "matrix")` at helpers_filters.R:16.
- is this line helpers_alignment.R:272 like
  `Biostrings::reverseComplement()`? Use Biostrings to reduce the
  number of package dependencies.

        seqinr::c2s(rev(seqinr::comp(seqinr::s2c(guideRNA))))

- 'Hoist' common expressions outside for loops, to vectorize (speed
  up) calculations, e.g., the 'reverse complement' (?) commands at
  helpers_alignment.R:289 on individual rows of a data.frame can be
  applied to the entire column outside the loop. Indeed, much of this
  and other loops seem that they can be effectively vectorized.
- minimize the number of times data is written to a file by returning
  vectors from calculations, and writing the vector. APPLY THESE
  CONSIDERATIONS TO ALL ITERATIONS
- `unpackFastq()` is not necessary for input to ShortRead, if that is
  how it is being used.
- use matrix-wise operations such as `matrixStats::rowMins()` rather
  than `apply()` at helpers_filters.R:16 and elsewhere
- helpers_filters.R:62 use `grepl("^[ATCG]+$", sread(reads))` or
  `stringr::str_detect(sread(reads), "^[ATCG]+$")` rather that
  `sapply()`. If the functionality of `grepl()` and `str_detect()` are
  approximately the same and relatively equivalent in terms of
  performance, then use `grepl()` to reduce the number of package
  dependencies. Can you provide an example of the error implied in the
  comment "possible c stack limits"?

src

- use spaces or tabs for indentation, not both.

man

- Please document the Gotoh algorithm, for instance, a literature
  citation
- Please clearly mark functions that are not exported, so the user
  knows that they are not to be called directly.

Please address the points above, and when your package is again passing the build and check process correctly include a brief summary of your response to each of these points.

**Comment by mtmorgan** [comment]
Do you plan to submit a revised package in time for the current release? The deadline is today.

**Comment by JokingHero** [comment]
Yes, I will try to fix what I can. I am afraid fixing Gotoh implementation so that it "It would operate on input objects (from ShortRead and Biostrings?) rather than files, and would return objects that can be computed on (Biostrings::PairwiseAlignment?)" and "The output format from gRCPP contains familar concepts (e.g., an alignment CIGAR) but in an idiosyncratic format. Present this information in a standard representation." will not be possible to do today. It would be my goal to fix this in next release. We could still expose gRCPP function to the user,  do you think we should do that? I have restricted from doing this before as I am also unhappy with inputs and outputs from the gRCPP function.

**Comment by mtmorgan** [comment]
I would rather see

- Since a major novelty in this package is the implementation of the
  Gotoh alignment algorithm, consider exposing this as a stand-alone
  function. It would operate on input objects (from ShortRead and
  Biostrings?) rather than files, and would return objects that can be
  computed on (Biostrings::PairwiseAlignment?)

addressed prior to accepting the package; if this can be done in the next several days then we can be more relaxed about the deadline for adding new packages to the Bioconductor release.

**Comment by JokingHero** [comment]
First of all thank you for all the feedback and comments. 

In this update I tried my best to fix following comments:

- [ x ] - Please spell check the DESCRIPTION, man, vignette, ... pages!

DESCRIPTION

- [ x ] spell check

vignette

- [ x ] please spell-check your vignette, e.g., 'posible' 'coffe', ...

- [ x ] use a temporary location tempfile() or tempdir() in the vignette / examples, rather than writing to getwd().

- [ x ] avoid long lines of code, e.g., amplicanOverview.Rmd:97 by un-nesting function calls; don't use explicit path separators but rely on the function call to use the appropriate separator for the operating system in use.

  fl <- system.file("extdata", "results", "barcode_reads_filters.csv",
      package = "amplican")
  barcodeFilters <- read.csv(fl)

R

- [ Not yet ready! ] Since a major novelty in this package is the implementation of the Gotoh alignment algorithm, consider exposing this as a stand-alone function. It would operate on input objects (from ShortRead and Biostrings?) rather than files, and would return objects that can be computed on (Biostrings::PairwiseAlignment?)

- [ x ] use BiocParallel rather than doParallel / foreach for a more consistent interface across Bioconductor packages.

- [ x ] use file.path() rather than paste0() to construct file paths.

- [ x ] return meaningful values, perhaps using invisible(), from all functions. For instance, from amplicanPipeline() return results_folder

- [ x (it was used with vector argument, removed elsewhere)] avoid misuse of ifelse() for scalar tests (e.g.,
amplicanAlign.R:128), use

result <- if (test) {
    ## TRUE value
} else {
    ## FALSE value
}
or similar (ifelse() is meant for use with vector arguments).

- [ x ] avoid repeated calls to writeLine, e.g., amplicanAlign.R:180

writeLines(
    c(paste("Config file:           ", "foo"), 
      paste("Processors used:       ", 2),
      paste("Skip Bad Nucleotides:  ", TRUE),
      ...),
    logFileConn)

- [ x ] use seq_len() / seq_along() rather than 1:n / 1:length(x)

- [ x (hopefully acceptable now)] choose an indentation scheme that does not result in highly indented, very short and illegible lines, as at amplicanAlign.R:222

- [ Not yet ready! ] The output format from gRCPP contains familar concepts (e.g., an alignment CIGAR) but in an idiosyncratic format. Present this information in a standard representation.

- [ x ] avoid direct slot access, e.g., helpers_alignment.R:181 ShortRead::sread(forwardsTable) rather than forwardsTable@sread

- [ Could not find import for quality accessor no matter what I tried, package would not pass checks] , as(quality(reads), "matrix") instead of as(slot(reads, "quality"), "matrix") at helpers_filters.R:16.

- [ x ] Biostrings::reverseComplement()? Use Biostrings to reduce the number of package dependencies.

- [ x ] 'Hoist' common expressions outside for loops, to vectorize (speed up) calculations, e.g., the 'reverse complement' (?) commands at helpers_alignment.R:289 on individual rows of a data.frame can be applied to the entire column outside the loop. Indeed, much of this  and other loops seem that they can be effectively vectorized.

- [ x ] minimize the number of times data is written to a file by returning vectors from calculations, and writing the vector. APPLY THESE CONSIDERATIONS TO ALL ITERATIONS

- [ x ] unpackFastq() is not necessary for input to ShortRead, if that is how it is being used.

- [ x ] use matrix-wise operations such as matrixStats::rowMins() rather than apply() at helpers_filters.R:16 and elsewhere

- [ x ] helpers_filters.R:62 use grepl("^[ATCG]+$", sread(reads)) or stringr::str_detect(sread(reads), "^[ATCG]+$") rather that sapply(). If the functionality of grepl() and str_detect() are approximately the same and relatively equivalent in terms of performance, then use grepl() to reduce the number of package dependencies. 

- [ Not yet ready! I need to run on large chunk of data overnight to try to replicate this error.] Can you provide an example of the error implied in the comment "possible c stack limits"?

src

- [ x ] use spaces or tabs for indentation, not both.

man

- [ x ] Please document the Gotoh algorithm, for instance, a literature citation

- [ x (Exported functions are marked with "@export" tag, only they will be visible for the user. Is there something specific I should do to mark not exported functions?)] Please clearly mark functions that are not exported, so the user knows that they are not to be called directly.

**Comment by JokingHero** [comment]
After some discussion with maintainer we decided that we are going to switch from using our gotoh function to the Biostrings::pairwiseAlignment in this package. Which aligner we use is not the main substance of our contribution. amplican is mean as pipeline for high-throughput amplicon sequencing specialized for CRISPR experiments. 

Also, we would like to wait with release for next Bioconductor schedule. We would like to test some more and gather more feedback from collaborators.

**Comment by mtmorgan** [comment]
OK, I will close this issue. Feel free to open a new issue when your updated package is ready.

**Comment by JokingHero** [comment]
Tried to open up new issue to submit amplican again, but bioc-issue-bot complains that I have already submitted this repository more than once and it exists in issue tracker. See #454. Can we open up this submission once more?

**Comment by mtmorgan** [comment]
Please perform a version bump.

**Comment by JokingHero** [comment]
I bumped the version to 0.9.100 as new start point, should it trigger the build automatically? Or should we check our web hooks? Or red error label "VERSION BUMP REQUIRED" prevents build?

**Comment by mtmorgan** [comment]
It should trigger a new build; when the build is successful the 'VERSION BUMP REQUIRED' tag will be removed. Can you check the web hook?

**Comment by mtmorgan** [comment]
There might be problems with having closed the issue; if the web hook is ok let me know and we'll work on it from this end.

**Comment by JokingHero** [comment]
I am sorry for so much delay, we had communication problems apparently. I confirmed that we do still have the web hook, could you work out some solution for our submission? Maybe it would be easier to close this issue, remove it from github completely and resubmit package (package changed so much that previous comments are no longer relevant I believe)? Or I could change the name to ampliCan - I made the name in lower case,so its easier to type, but the actual name on our logo is ampliCan.

**Comment by mtmorgan** [comment]
I suspect that your unit test fails because it uses the same directory on each architecture -- `results_folder <- ...` should be something like `results_folder <- tempfile(); dir.create(results_folder)`.

Also please confirm on next version bump (an increment of to z+1 for version x.y.z is sufficient) that the web hook runs, or at least what the return value is, under settings --> web hooks --> edit and then choose the hook(s) and look at 'Response'.

**Comment by JokingHero** [comment]
<img width="759" alt="screen shot 2017-08-29 at 1 29 46 pm" src="https://user-images.githubusercontent.com/7996188/29819614-af302dca-8cc1-11e7-81fe-9d07e1c80e6d.png">

Just made commit into 0.9.101 and web hook returns above.

**Comment by mtmorgan** [comment]
Great, thanks, I added the 'review in progress' label for the future, and triggered a manual rebuild.

**Comment by JokingHero** [comment]
Great! Thank you! 

During code review, if you have any suggestions to speed up getEventInfo function (helpers_general.R) it would be great as this is main bottleneck (not the alignment process in itself). The goal is to extract deletions, insertions and mismatches from PairwiseAlignmentsSingleSubject class into GRanges object with metadata columns. Main issue is that extracting deletions with natural Biostrings::deletion returns ranges not from the subject point of view. I get around this by shifting deletions for each insertion beforehand if any, but its slow. If there would be a way to vectorize this process (maybe C level Biostrings library?) I would be grateful for advice on how to achieve that. For this moment, current implementation works and is properly tested in test_alignment_helpers.R.

**Comment by mtmorgan** [comment]
Sorry to be slow in returning comments. Below are some minor general things. If you can provide an easy way for me to run an example with `getEventInfo()` then I'll be happy to work on it in the short term.

Seems like the one-year anniversary of my initial review!

DESCRIPTION / NAMESPACE

- good
- CONSIDER: large number of imports makes he package fragile; are they all strictly necessary?

vignette

- format long code lines so that they are easy to read (do not wrap) in the built vignette.

R

- use accessors instead of direct slot access, e.g., in validity method replace `object@experimentData` with `experimentData(object)`x
- AlignmentsExperimentSet-class.R:76 ensure that enough information is displayed to help the user rather than (as it appears) an overwhelming amount of data.
- `cat()`, `message()`, `warning()`, `stop()` do not usually require `paste()` inside them, `cat(paste("foo", "bar"))` --> `cat("foo", "bar")`
- amplicanAlign.R:79 it is better practice to leave BPPARAM unspecified, so the user has control through `BiocParallel::register()`. The conditional could be simplified as

    ```
    if (use_parallel)
        p = BiocParallel::bpparam()     # user choice
    else
        p = BiocParallel::SerialParam() # standard lapply
    configSplit <- split(cfgT, f = cfgT$Barcode)
    finalAES <- BiocParallel::bplapply(configSplit, FUN = makeAlignment,
                                       average_quality,
                                       min_quality,
                                       scoring_matrix,
                                       gap_opening,
                                       gap_extension,
                                       fastqfiles,
                                       primer_mismatch, BPPARAM=p)
    ````

- amplicanAlign.R:104 `do.call(c, x)` is usually more efficient than `Reduce(c, x)`

**Comment by JokingHero** [comment]
Thank you for feedback. [Here](https://gist.github.com/JokingHero/3df49515aeeaeb3dd2a0cff3714e2c8c) is gist with getEventsInfo, if you can suggest something to make it faster, me and future users will be grateful.

DESCRIPTION / NAMESPACE

- [ x ] good
- [ x ] CONSIDER: large number of imports makes he package fragile; are they all strictly necessary? Unfortunately yes, for some of them I only use one function, but this is very high level package and we will take responsibility to keep up with package fixes.

vignette

- [ ? ] format long code lines so that they are easy to read (do not wrap) in the built vignette. - If I understand correctly all variables shouldn't be chained eg. something(something2(something3(x))). Fixed that case. 

R

- [ x ] use accessors instead of direct slot access, e.g., in validity method replace object@experimentData with experimentData(object)

- [ ? ] AlignmentsExperimentSet-class.R:76 ensure that enough information is displayed to help the user rather than (as it appears) an overwhelming amount of data. - Currently show method prints information only for the first experiment. I changed readCounts to print wth the use of str(). From my experience it is easier to manipulate object, if I can look up first element of it, even if its a bit longer.

- [ x ] cat(), message(), warning(), stop() do not usually require paste() inside them, cat(paste("foo", "bar")) --> cat("foo", "bar")

- [ x ] amplicanAlign.R:79 it is better practice to leave BPPARAM unspecified, so the user has control through BiocParallel::register(). The conditional could be simplified as

if (use_parallel)
    p = BiocParallel::bpparam()     # user choice
else
    p = BiocParallel::SerialParam() # standard lapply
configSplit <- split(cfgT, f = cfgT$Barcode)
finalAES <- BiocParallel::bplapply(configSplit, FUN = makeAlignment,
                                   average_quality,
                                   min_quality,
                                   scoring_matrix,
                                   gap_opening,
                                   gap_extension,
                                   fastqfiles,
                                   primer_mismatch, BPPARAM=p)

- [ x ] amplicanAlign.R:104 do.call(c, x) is usually more efficient than Reduce(c, x) - This works as intended, do.call keeps it as list, while Reduce will merge all objects using c into AlignmentExperimentSet class.

**Comment by mtmorgan** [comment]
I looked quite a bit a getEventInfo, although I'm not actually familiar with the aligned string representations in Biostrings. I did not come up with meaning performance improvements. Some minor changes include:

- Use the constructor rather than construct-and-assign in `defGR()`, 

    ```
    GenomicRanges::GRanges(
        ranges = x,
        strand = strand_info,
        seqnames = ID,
        originally = as.character(originally),
        replacement = as.character(replacement),
        type = type,
        read_id = names(x),
        score = score
    )
    ```

- minimize operations within conditionals, e.g., 

    ```
    shift_to_subj <- function(x, ampl_shift, subject, strand_info) {
      if (strand_info == "+") {
        delta <- 1L
      } else {
        delta <- stringr::str_count(subject, "[ATCG]")
      }
      IRanges::shift(x, ampl_shift - delta)
    }
    ```
  and

    ```
    width <- nchar(align)
    if (strand_info == "+") {
      s_err <- width + ampl_shift - 1L >= ampl_len
      start <- width[!s_err] + ampl_shift
      end <- if (all(s_err)) integer() else ampl_len
    } else {
      s_err <- width + abs(ampl_shift - ampl_len) >= ampl_len
      start <- if (all(s_err)) integer() else 1L
      end <- ampl_shift - width[!s_err]
    }
    sizes <- IRanges::IRanges(start = start, end = end, names = which(!s_err))
    ```
    
- avoid nested iterations with vectorization, e.g.,

    ```
    ins_r <- rep(ins, each = lengths(del))
    del_s <- unlist(start(del))
    sft <- -1 * sum(width(ins_r)[del_s > start(ins_r)])
    del_sft <- relist(sft, del)
    del <- IRanges::shift(del, del_sft)
    ```

  this is actually a little slower than an intermediate solution that hoists the accessors out of the iteration:

    ```
    shift_del <- mendoapply(function(x, y, w) {
        vapply(
            x,
            function(x_i, y, w) sum(w[x_i > y]),
            integer(1),
            y, w
        )
    }, BiocGenerics::start(del), BiocGenerics::start(ins), BiocGenerics::width(ins))
    del <- IRanges::shift(del, -1 * shift_del)
    ```

You can either incorporate these changes or not; let me know via a comment and I will accept the package.

**Comment by JokingHero** [comment]
Thank you for your effort and that you care! Do you think implementing some parts in C++ (maybe mendoapply(function(x, y, w) part) would give any benefits?

**Comment by mtmorgan** [comment]
no; about 30% of the time is in `mismatchSummary()`, which is doing complicated queries on `events`; it would be tedious and error-prone to do that in C. I think you could get a speed-up by iterating on the `events` part

```
  width <- nchar(align)
  subj <- as.character(subject(align))
  pat <- Biostrings::pattern(align)
  del <- Biostrings::deletion(align)
  ins <- Biostrings::insertion(align)
  mm <- Biostrings::mismatchSummary(align)$subject
```
and collapsing the result of the iteration into Vectors and a partitioning, allowing for vectorization, but that would be a little (not impossible) tedious.

**Comment by mtmorgan** [comment]
I'll accept this package now; further performance improvements can be pursued once it's in Bioconductor.

**Comment by JokingHero** [comment]
Alright, Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (tithub.com/<username>.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]

1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/

[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/

https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
