### ISSUE TITLE
ENTC

### ISSUE THREAD

**Issue by zhangli1109** [Bioconductor/Contributions#1161]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhangli1109/ENTC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by zhangli1109** [comment]
I am sorry, I don't know where is the awaiting moderation

**Comment by mtmorgan** [comment]
In addition to comments to be provided by your reviewer, please update your package to interoperate with (accept as input) the [SingleCellExperiment][1] class.

[1]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by zhangli1109** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Dear professor,Now I modified the version, can you check it again?Thanks.On 6/26/2019 19:08，bioc-issue-bot<notifications@github.com> wrote：

Dear Package contributor,
This is the automated single package builder at bioconductor.org.
Your package has been built on Linux, Mac, and Windows.
On one or more platforms, the build results were: "ERROR".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.
Please see the build report for more details.

**Comment by Liubuntu** [comment]
Hi @zhangli1109 , 

Please fix this error in the building report: 
```
* Checking new package version number...
    * ERROR: New package version starting with 0.99.* (e.g., 0.99.0,
      0.99.1, ...); got 0.1.0.
```

There are multiple other issues with your package, including but not limited to: 

1. in DESCRIPTION, you should list `Imports` field, for the all the imported R packages. (refer to your NAMESPACE)
2. R/ENTC.R, this function should be interoperable with `SingleCellExperiment` class as input, since your package claims to work with scRNA-seq data. See @mtmorgan Martin's comment https://github.com/Bioconductor/Contributions/issues/1161#issuecomment-505828692
3. Also as rectangular count data (rows are features, cols are samples), we recommend using `SummarizedExperiment` data class in representing the datasets. See [here](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/). 

Minor: 
4.  We would strongly recommend adding unit tests. See [here](http://bioconductor.org/developers/package-guidelines/#unittest). This would usually go with the official review. 

You can check the whole webpage here for the [package development guidelines](https://bioconductor.org/developers/package-guidelines/). Refer [here](https://bioconductor.org/packages/release/BiocViews.html#___miRNA) for Bioc packages dealing with miRNA. 

Please let me know if you can make the changes. Or if you think this will take elongated time, also let us know, so that we can close this issue temporarily, and reopen it whenever you feel ready. Let me know for any questions.

Best,
Qian

**Comment by zhangli1109** [comment]
hi，Qian Liu
 I have fixed the package version error, but I don’t know how to use summarizedexperiments, which will take me a long time to study. I will use it as long as I have learned it


Best,
Li Zhang 




------------------ Original ------------------

**Comment by Liubuntu** [comment]
Hi Li @zhangli1109 , 

I would recommend reading the following materials for implementing `SummarizedExperiment` in representing your input data from micro RNA assay: 

http://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html

`SingleCellExperiment` extends the `SummarizedExperiment` and aims to represent scRNA-seq data sets. Check here: 
http://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/intro.html
http://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/devel.html

Basically your current input data includes read counts, gene annotation, sample annotation, which maps well into `SummarizedExperiment` or `SingleCellExperiment` in the slots of `@assay`, `@rowData` and `@colData`. Using these containers could have all related data (assay data + annotation data) into one R object, and it comes with many useful methods for free, such as `[` subsetting, etc. Once your tools is interoperable with these S4 classes, it interoperates with many other tools that were build upon these classes. 

Please look into updating your package based on the above comment. I'll keep this issue open for another 2~3 weeks, so that we can see if any changes could be implemented. Let me know for any questions concerning the above comments. 

Also for bioc packages, once you make any updates / changes, you need to bump version in `DESCRIPTION` file, e.g., from `0.99.1` into `0.99.2`, and so on, so that the building machine could catch the commits and trigger the auto building. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @zhangli1109 , 

I'm closing this issue now. Please let me know when you are ready and I can reopen it then, 

Best,
Qian

**Comment by zhangli1109** [comment]
Hi, Qian,
I have learned SummarizedExperiment, but I still don't know how to add it to my code and where to add it. Can you give me some examples ?
Best,
Li

**Comment by zhangli1109** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi, Qian,I have learned SummarizedExperiment, but I still don't know how to add it to my code and where to add it. Can you give me some examples ? I need your help.And are there any other questions besides this one? Please tell me. Thank you!Best,Li
            
        
    
    
        
            
        
    
    
     
    
 

    On 8/6/2019 04:02，Qian Liu<notifications@github.com> wrote： 


Closed #1161.

**Comment by zhangli1109** [comment]
Hi, @Liubuntu ,
I have fixed the errors in the package and changed the package version, but I found that the package is not built at bioconductor.org. I don't know what's the problem.
 Best,Li

**Comment by mtmorgan** [comment]
Closed issues are not built automatically. 

Because the package has been inactive for so long, I suggest that you open a new issue and start again. Note that you have changed your package name, to CAEN, and that the name of your repository must match the name of your package. So you should clone or rename your repository to match the name of your package, and then open a new issue.
