### ISSUE TITLE
gramm4R

### ISSUE THREAD

**Issue by chentianlu** [Bioconductor/Contributions#1167]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/chentianlu/gramm4R

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
The vignette in your package is incomplete.

Your package should be interoperable with existing Bioconductor data representations for similar data, for instance [SummarizedExperiment][1] for representing matrix-like data with annotations on the rows and / or columns.

[1]: https://bioconductor.org/packages/SummarizedExperiment

Please update your package and post a comment here when ready, so the review process may begin.

**Comment by chentianlu** [comment]
Dear Martin,
We have revised and updated the gramm4R package per your professional comment. Thank you for your kind help.

**Comment by chentianlu** [comment]
Dear, 
We have revised and updated the package according to your comment.
Thank you for your kind help.

Tianlu Chen



Tianlu Chen

 
From: Martin Morgan
Date: 2019-06-27 16:22
To: Bioconductor/Contributions
CC: Tianlu Chen; Mention
Subject: Re: [Bioconductor/Contributions] gramm4R (#1167)
The vignette in your package is incomplete.
Your package should be interoperable with existing Bioconductor data representations for similar data, for instance SummarizedExperiment for representing matrix-like data with annotations on the rows and / or columns.
Please update your package and post a comment here when ready, so the review process may begin.

**Comment by chentianlu** [comment]
Dear,
We have revised the package and fixed the problem. Thank you.

**Comment by chentianlu** [comment]
Dear,
We have fixed the problem. Thank you.

Tianlu Chen



Tianlu Chen

 
From: bioc-issue-bot
Date: 2019-07-01 14:09
To: Bioconductor/Contributions
CC: Tianlu Chen; Mention
Subject: Re: [Bioconductor/Contributions] gramm4R (#1167)
Dear Package contributor,
This is the automated single package builder at bioconductor.org.
Your package has been built on Linux, Mac, and Windows.
On one or more platforms, the build results were: "ABNORMAL".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.
Please see the build report for more details.

**Comment by dvantwisk** [comment]
Hi @chentianlu 

Glad to see you are making fixes. There are further errors in the package the need to be addressed. Feel free to ask for help if needed.

**Comment by chentianlu** [comment]
Hi @dvantwisk 
We have fixed the errors in the package. Thank you.

**Comment by dvantwisk** [comment]
The most current build report is still giving errors.
http://bioconductor.org/spb_reports/gramm4R_buildreport_20190701083223.html

**Comment by chentianlu** [comment]
Dear,
We have revised the package and fixed the problem, please check the package again. Thank you.

**Comment by dvantwisk** [comment]
Please perform a version bump so that your package will build on our system.

**Comment by chentianlu** [comment]
Thanks a lot, we have revised the version of our package, please check it again. @bioc-issue-bot

**Comment by dvantwisk** [comment]
Your package should build automatically once you perform a version bump, assuming the webhook to your package is set up correctly. Have you set it up?
https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by chentianlu** [comment]
Dear, we have set up the webhook of our package. Thanks for your kind help.

**Comment by chentianlu** [comment]
We have corrected the package. @mtmorgan

**Comment by lshep** [comment]
If you have updated changes and set up the webhook,  could you please do a version bump in the DESCRIPTION file to trigger a build.  Thank you.

**Comment by chentianlu** [comment]
The current version is 0.9.1. 
Shall we change it to 0.99.9 to triger a build or change it to 1.0.0 directly?
Thank you for your kind instruction.

Tianlu Chen


Tianlu Chen
Center for Translational Medicine
Shanghai Jiao Tong University Affiliated Six People's Hospital

 
From: lshep
Date: 2019-07-12 01:42
To: Bioconductor/Contributions
CC: Tianlu Chen; Mention
Subject: Re: [Bioconductor/Contributions] gramm4R (#1167)
If you have updated changes and set up the webhook, could you please do a version bump in the DESCRIPTION file to trigger a build. Thank you.

**Comment by chentianlu** [comment]
We have revised the version form 0.99.1 to 1.0.0 in the DESCRIPTION file and a build has been triggered. Thank you.
Tianlu Chen



Tianlu Chen
Center for Translational Medicine
Shanghai Jiao Tong University Affiliated Six People's Hospital

 
From: lshep
Date: 2019-07-12 01:42
To: Bioconductor/Contributions
CC: Tianlu Chen; Mention
Subject: Re: [Bioconductor/Contributions] gramm4R (#1167)
If you have updated changes and set up the webhook, could you please do a version bump in the DESCRIPTION file to trigger a build. Thank you.

**Comment by chentianlu** [comment]
We have changed the version from 1.0.0 to 0.99.3 and have subscribed the bioc-devel mailing list.

**Comment by chentianlu** [comment]
We have fixed the errors. Thank you.

**Comment by dvantwisk** [comment]
I've reviewed your package. It looks good though I have a few issues. [REQUIRED] tags must be addressed whereas [CONSIDER] tags are advisable but not necessary. Please message me back once you are done making changes.

R/GENERAL
- [ ] [CONSIDER] I've noticed a lot of for-loops used in your code. Some of
these-loops have depths of 3. I'd like to point out that R code performs
better when the code is vectorized as opposed to other languages where the
use of loops is more frequent. The only times to really use loops in R is when
either there are functions in the loop that don’t take vector arguments or in
the case of loops where each iteration is dependent on the results of previous
iterations. Your code seems rather complex and I can't recommend anything
specific with regards to how to vectorize your code. In fact it's not clear that
vectorization can be used over what you are doing in your for-loops. I ask that
you look through articles like
this https://www.noamross.net/blog/2014/4/16/vectorization-in-r--why.html to
understand when to vectorize your code and take a quick look over your code to
see whether or not it could be vectorized.

R/naiveGramm.R
- [ ] [REQUIRED] It seems that the code in Gramm.R:L126-257 is the same or very
similar to the code in this file. Please try to create functions that perform
this functionality instead of repeating code.

vignettes/gramm4R.Rmd
- [ ] [CONSIDER] Add a small section at the beginning detailing how to install
the package.

**Comment by dvantwisk** [comment]
Hi,
I'm just checking in again since this issue hasn't been updated in a while. Are you making the changes that I prescribed above? We generally like to see packages be actively worked on within a two week period, of we close the issue. Closed issues can be reopened when the package maintainer is ready to continue work on the package. Are you still working on making changes to this package?

**Comment by chentianlu** [comment]
Hi,
I have made the changes that you comment above, and sorry to be late.  I deselect the for-loops in preGramm.R , and made the code vectorized. In Gramm.R and naiveGramm.R,  the for-loops contain iterations that is dependent on the results of previous iterations, so I think it's can't be used. We correct the repeated code in Gramm.R:L126-257, and add small section at the beginning detailing how to install the package in vignettes/gramm4R.Rmd. 
Thanks for your advises.

**Comment by dvantwisk** [comment]
Sorry for the wait! The changes to your code look good. I'm going to move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/chentianlu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gramm4R")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gramm4R

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
