### ISSUE TITLE
idr2d

### ISSUE THREAD

**Issue by kkrismer** [Bioconductor/Contributions#1175]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kkrismer/idr2d

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# idr2d review

## R CMD build 

ok

## R CMD INSTALL 

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## R

* After using importFrom, the imported function is within the scope of
  the function you are writing. So you don't need to,
  `GenomicRanges::` before using `makeGRangesFromDataFrame`. Similar
  changes need to be made in all other places in the codebase.

* Make your code less error prone, by typing out the col names you
  risk making an error by repeating.

		rep1.df <- dplyr::select(rep1.df, chr, start, end,
                                 value, rep.value,
                                 rank, rep.rank,
                                 idx, rep.idx)
        rep2.df <- dplyr::select(rep2.df, chr, start, end,
                                 value, rep.value,
                                 rank, rep.rank,
                                 idx, rep.idx)
vs
   
		cols <- c('chr', 'start', 'end', 'value', 'rep.value',
		         'rank', 'rep.rank', 'idx', 'rep.idx')
		rep1.df <- select(rep1.df, cols)
		rep2.df <- select(rep2.df, cols)

	Similar changes can be made in other code chunks as well.
	
	
* This is not needed,

		# avoid CRAN warnings
		rep2.idx <- rep1.value <- rep2.value <- NULL
		chr <- start <- end <- NULL
		chr.a <- start.a <- end.a <- chr.b <- start.b <- end.b <- NULL
		value <- rep.value <- rank <- rep.rank <- idx <- rep.idx <- idr <- NULL
		
	If you think it is, please give a reason.


## Vignettes

* Does the package need two vignettes, one called idr1d and idr2d?

## General

I'm glad that you referenced the previous package `idr`.

**Comment by nturaga** [comment]
@kkrismer Please note that you have about 2 weeks from the review to reply (any reply) to suggest that you are actively working on the package. 

If not we can close the issue and reopen it at a later time. You lose nothing by doing this. It would be additional time for you.

**Comment by kkrismer** [comment]
Hi Nitesh,

thank you for your helpful feedback! I will address your comments and push changes next week.

Cheers,
Konstantin

**Comment by kkrismer** [comment]
Hi Nitesh,

I've pushed changes to the idr2d repository that address some issues you mentioned.
Other changes were necessary to adhere to the tidyverse style guide. I've also added a new function, estimate_idr2d_hic, which enables HiC analysis.

I'd like to address your comments individually:

**1. using namespaces when calling external functions**

I agree that this is not necessary, but I prefer to make function calls to other packages explicit by always specifying the package name. I follow Hadley Wickham's advice:
"[...] always refer to it explicitly with pkg::fun(). Unless there is a strong reason not to, it’s better to be explicit." (see http://r-pkgs.had.co.nz/namespace.html)

**2. type out column names**

Done.

**3. col <- NULL**

If I don't define the data frame columns like this, R CMD check throws a NOTE:
checking R code for possible problems ... NOTE
  estimate_idr: no visible binding for global variable 'col'
  Undefined global functions or variables:
    col

I follow Matt Dowle's recommendation, see https://stackoverflow.com/a/8096882 and also https://stackoverflow.com/q/9439256 for a broader discussion.

**4. Multiple vignettes**

I drastically reduced the file sizes of the vignettes by only showing the first 1000 observations in each.
I'd like to keep a vignette for each major use case of the package (one for ChIA-PET data and one for ChIP-seq data). If there are downsides to having multiple vignettes, I'm happy to condense them into a single vignette. This structure seemed the most logical to me.

Thanks again for your helpful feedback!

Cheers,
Konstantin

**Comment by nturaga** [comment]
Thanks for your response. Your package has been accepted.

**Comment by kkrismer** [comment]
Thanks @nturaga 
Is there anything left to do? I'm wondering because the bioc-issue-bot hasn't posted the usual "Your package has been accepted. [...]" message yet and idr2d also hasn't been added to the devel branch.

**Comment by nturaga** [comment]
This will happen when Martin processes the accepted packages. Please be
patient. Reviews/acceptance process involves multiple people on the
Bioconductor team.

Best,

Nitesh

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kkrismer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("idr2d")`. The package 'landing page' will be created at

https://bioconductor.org/packages/idr2d

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
