### ISSUE TITLE
Submission of "APAlyzer" package to Bioconductor

### ISSUE THREAD

**Issue by RJWANGbioinfo** [Bioconductor/Contributions#1180]
Dear Bioconductor developers,

I would like to submit my "APAlyzer" R package to Bioconductor.  The current package has been checked using 'R CMD build', 'R CMD check' and 'R CMD BiocCheck'. And please notice that the package supports both Linux and Mac, but doesn't support window.

- Repository: https://github.com/RJWANGbioinfo/APAlyzer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by RJWANGbioinfo** [comment]
Hi,

1) As I mentioned in the submission, this package does not support Windows due to the use of Rsubread.

2) I have attempted to fix the issues pointed by build-bot on Linux, Mac:
Changed version to 0.99.1
Use an extra extdata file for the example of 'REFCDS'.

**Comment by mtmorgan** [comment]
@Liubuntu will review your package, but I was wondering if you could be more precise about how your package uses Rsubread? The reason to push this is actually that more than 1/2 our users are on Windows, so you automatically lose 1/2 your audience by Depending or Importing Rsubread. Perhaps it makes sense to move Rsubread to 'Suggests:', and to make the functionality that uses it conditional on it's availability, either as a stand-alone script that demonstrates data preparation or as functions that start by trying to `requireNamespace('Rsubread')` and fails with a helpful message (install if not on Windows, sorry out-of-luck if on Windows) if it is not installed. Obviously if your package depends intimately on Rsubread (the vignette didn't look like that...) then this isn't an option.

**Comment by RJWANGbioinfo** [comment]
Hi @mtmorgan,

Thanks for your prompt reply. In the current version of the package, one of the core function PASEXP_IPA  relies on Rsubread. Other functions don't require Rsubread. Since this function is one of the most important ones in the package,  it's hard for us to bypass it in the current stage.

**Comment by mtmorgan** [comment]
Looks like you're using Rsubread to count reads over features in existing bam files, which can be done easily with GenomicAlignments::summarizeOverlaps(); the performance is not as good as Rsubread, but that might not matter for the size of data / types of queries you are making. It also looks like at least some of the arguments to this function should be GenomicRanges::GRanges(); using GRanges increases the ease with which users of other Bioconductor packages can use your package, and provides robust software for working with ranges, rather than ad hoc data frames.

**Comment by RJWANGbioinfo** [comment]
Hi @mtmorgan,
Thanks for your suggestion. We actually used summarizeOverlaps() in some of the other functions, e.g., REF3UTR. The reason we stick on Rsubread in this function, because we have some of the IPA region features that are highly overlapped in the genome. And the performance of summarizeOverlaps() is not ideal (we have tried that) for these regions, that's why we switch to featureCounts with allowMultiOverlap=TRUE. 
If there is any alternative library supporting Windows can handle a similar situation, we may modify the code and switch to it; otherwise we may have to keep featureCounts in our function for the current stage. Thx.

**Comment by Liubuntu** [comment]
Hi @RJWANGbioinfo , 

Thanks for submitting you package to Bioconductor. I'll be out for conference next week and a few days more. So the official review will most probably go out in 2-3 weeks. Thanks for understanding. 

Best,
Qian

**Comment by RJWANGbioinfo** [comment]
Hi @Liubuntu ,

Thanks for letting me know. No problem at all. :)

Thx.
Ruijia

**Comment by Liubuntu** [comment]
Hi @RJWANGbioinfo , 

Sorry for the delay. But here please find the official review. Please seek to address most of the points and comment back for any questions / comments / updates. 

Your package looks very solid, and inter-operates with the existing Bioconductor packages really nicely. Vignette and documentations are well written also. Most of the review issues are minor, more about the formats, and consistent Bioconductor coding styles. Let me know for any questions. 

Cheers,
Qian

## DESCRIPTION
- `Date:` field is not actually needed here.
- if you want to specify more information about each author, it's
  suggested to use the `Authors@R` instead of `Author`+`Maintainer`
  fields. E.g.,
  ```
  Authors@R: c(person("FirstName", "LastName", role = "aut"),
               person("Lori", "Shepherd", email="Lori.Shepherd@roswellpark.org", role=c("cre", "aut"),
                           comment = c(ORCID = "0000-0002-5910-4010")))
  ```
- `LazyData:` field: For packages that include data, we recommend not
  including `LazyData: TRUE`. This rarely proves to be a good
  thing. In our experience it only slows down the loading of packages
  with large data.

- `BugReports:` field: It is encouraged to include the relevant links
  to Github for reporting Issues.
- `URL`: Recommended to add `URL` field, to direct users to source
  code repositories, e.g., the GitHub repository.

## NAMESPACE
- Looks good!

## R/
- `APAlyzer.R`L24: `.getcount()` function. Seems that under 3 different
  conditions, the `counttbl` is calculated in a very similar
  way. Consider pre-define a value for the argument of `preprocess.reads`
  and call the `summarize3Overlaps` function only once to avoid
  duplicate code. e.g.,
 ```
preprocess.reads.function <- NULL
if (STRINFOR == "INVERT") preprocess.reads.function <- invertStrand
counttbl<- summarizeOverlaps(DB, BMAfile,
                               mode="IntersectionNotEmpty",
                               singleEnd=TRUE, ignore.strand=TRUE,
                                                   preprocess.reads=preprocess.reads.function)
```
- `APAlyzer.R`, `.divxdb()` function, L45: the `()` is not necessary
  inside `xp=x[(strand(x)==keystr),]`. L46: Not exactly sure about the
  conditions in your package, but seems that the `split` function
  directly assigns names for the returned list as the split levels,
  i.e., the `xp$gene_name` here, in that case, no need to pre-define
  the `names(xp)` before `split()` call. Similar case in L90.
- `APAlyzer.R`L65: `REF3UTR()` function. In the function
  documentation, the argument `refUTR` must conform a specific format
  with corresponding contents. It is recommended to check the value of
  the input, e.g., the `ncol()`, or more.
- `APAlyzer.R`L65: `PASEXP3UTR()` function, same as above, check the
  input format for robustness, e.g.,`stopifnot(is(UTRdb, "GRangesList"))`.

General:
- Suggested: In all R scripts (including R code chunks in vignette),
  please be consistent of using ` <- ` or ` = ` for value assignment
  in examples.

## man/
- REF3UTR: inconsistent function name in the `Value` section.
- IPA_analysis(nts): Consider adding the `?Rsubread::featureCounts`
  and `nthread` in the documentation for argument of `nts` for users
  to look for more detailed information and in vignette when you
  mention the multiple thread calculation.

## vignette

- Nice work on the PolyA_DB database. I'm not quite sure, but seems
  that the current version is v3 instead of `v1.0` as you stated in
  the "About APAlyzer" section?
- Installation: Suggest to add info about the development version of
  the software, that is available on
  github. `BiocManager::install('RJWANGbioinfo/APAlyzer')` could do the work.
- Evaluate the `library(APAlyzer)` at first mention in the
  "Intallation" section (as if it was already included in
  Bioconductor), and remove the other `library(APAlyzer)` in vignette.
- the visualization ggplot2 code are all successfully
  executable. consider having them evaluated instead of inserting
  pre-generated figures. Also for the last section "Gene expression
  analysis...".
- Minor: typo in L23 'APAlyzer.Rmd', the word `sequencing` were
  separated accidently. typo in L104, should be `reference` instead of
  `refence`.


General:
- It's recommended to use `eval=TRUE` for most of the code chunks in
  vignette. There are too many unevaluated code chunks in your
  vignette while they are perfectly executable. Given many of the
  packages are included in `DESCRIPTION` as `Suggests`, that won't
  affect the building and checking of your package. Evaluated code
  with outputs will also give users better idea of how your package works.

## unit test
- Unit tests are highly recommended. Refer [here](http://bioconductor.org/developers/package-guidelines/#unittest) for more details.

**Comment by Liubuntu** [comment]
To avoid building and checking on windows platform, add this file in your package repo: https://github.com/hubentu/Rcwl/blob/master/.BBSoptions

**Comment by RJWANGbioinfo** [comment]
Hi @Liubuntu,

Thanks for your review and feedback! We'll address all your comments one by one and submit the revised version as soon as we can.

Thx.

**Comment by RJWANGbioinfo** [comment]
Hi @Liubuntu 

We have revised our package and addressed all your comments one by one. The updated version has been updated in Github. Here's the detailed revision report:

**DESCRIPTION**

- We've removed the Data field.

- We've revised the format of Author field according to your suggestion.

- We've removed the LazyData field.

- We've added the corresponding links to the BugReports and URL field.

**R/**

- The `counttbl` has been simplified according to your comments.

- The unnecessary () has been removed,

- Format check has been added into `REF3UTR()`.

- Format check has been added into `PASEXP3UTR()`.

-  The "=" has been consistently used in all R scripts now.

**man/**

- Function name has been modified accordingly in the Value section of `REF3UTR`.

- `IPA_analysis`: Description of `Rsubread::featureCounts` and nthread has been added in both man and vignette for users to look for more detailed information.

**vignette**

- The version of PolyA_DB has been modified accordingly.

- Installation of the development version has been added.

- Evaluation of the `library(APAlyzer)` at first mention has been turned on, others have been removed.

- Evaluation of the visualization section and the last section have been turned on.

- The typo has been corrected.

- We have now used eval=TRUE for the vignette as much as we can according to your suggestion.

**unit test**

- We've now added the unit tests into the package.

**Others**

- .BBSoptions has been added to the package repo.

- Changed version to 0.99.2

Many thanks,
Ruijia

**Comment by Liubuntu** [comment]
Hi @RJWANGbioinfo , 

Thanks for the quick response. Your revised package looks very good for acceptance. Thanks for your contribution to Bioconductor. 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/RJWANGbioinfo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("APAlyzer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/APAlyzer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
