### ISSUE TITLE
SEtools

### ISSUE THREAD

**Issue by plger** [Bioconductor/Contributions#1181]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/plger/SEtools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
I apologize for the wait. Here is a review of your package. It looks well written and I only have a few concerns. [REQUIRED] changes must be made or addressed wheres [CONSIDER] tags are advisable but not necessary. Please message me back when you are finished making changes.

R/GENERAL
- [ ] [REQUIRED] Use `seq_len()` instead of `1:length()`. This is
slightly more efficient and prevents the unexpected case where `1:0` is
`1 0`.

R/mergeSEs.R
- [ ] [CONSIDER] L108-127: There seems to be a quintuple for-loop here and
I am worried that this would become very inefficient in some bases. If the
number of iterations here is not bounded, I would consider thinking
further into how this section of code can be vectorized to increase
efficiency. 

vignettes/SEtools.Rmd
- [ ] [CONSIDER] It may be helpful for users to add a small section about
installing the package through Bioconductor in case they are not familiar
with it.

**Comment by plger** [comment]
Thanks for the feedback!

Regarding the 2nd point, I'm not sure I get your precise concern: is it generally about the many steps that are iterating, or specifically about nested apply functions? On the former, I could reduce by always running the code for the worst-case scenario, but that would be slower for simpler cases. On the latter, there is at most 3 nested apply calls: line 108 for each assay, then in the worst case (when rows without variance create scaling errors) lines 120 (for each dataset) and 121 (each row)...

(fixing the other 2 points)

**Comment by plger** [comment]
* [x]  [REQUIRED] Use `seq_len()` instead of `1:length()`. 
* [x]  [CONSIDER] It may be helpful for users to add a small section about installing the package through Bioconductor

**Comment by plger** [comment]
I don't understand the BiocCheck error at "Checking for support site registration" (I now get the same locally, didn't before the last changes). 
I'm registered:
https://support.bioconductor.org/api/email/pierre-luc.germain%40hest.ethz.ch/

But it rather seems like BiocCheck either doesn't get/interpret correctly the api's output...

@dvantwisk any tip would be appreciated!

**Comment by lshep** [comment]
The support site is experience some connectivity issues. We are in the process of resolving.  This is on our end please ignore that BiocCheck ERROR for now.

**Comment by dvantwisk** [comment]
I apologize for the silence on my end, I think I lost track of this issue.

Regarding your question on clarification on "for-loop" issue, I usually get a little nervous when I see the a lot of nested loops in R due to inefficiency concerns. It's better practice to pass operations on to functions in the underlying C-code as quickly as possible for the best results. We tend to refer to this as vectorization. Here a pretty good introduction on exactly why this is a good thing to do https://www.noamross.net/archives/2014-04-16-vectorization-in-r-why/

Of course, not all code can be vectorized, and for-loops may be the only option. Your code did seem somewhat complicated and I can't see any obvious way to make it better. I suppose my purpose for that suggestions was to make sure that you were aware that that code chunk had this issue and to suggest that there may be a better way to do it. But if those nested for-loops run in an acceptable amount of time, then this is an issue that does not need to be addressed.

**Comment by plger** [comment]
Thanks for the clarification. In the present context the memory is pre-allocated and the higher-level iterations are bound to be low, so I'll leave that bit of code as is, but I'll keep this in mind.

**Comment by dvantwisk** [comment]
Thanks for the explanation. With that, I think the changes you've made look good and I am going to move to accept this package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/plger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SEtools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SEtools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
