### ISSUE TITLE
AlphaBeta

### ISSUE THREAD

**Issue by shahryary** [Bioconductor/Contributions#1183]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jlab-code/AlphaBeta

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before your package can be reviewed, you'll need to update your vignette (some of it is simply template; your vignette should walk the user through the analysis you provide, describing inputs, interpreting outputs, and demonstrating how the software integrates with other Bioconductor components.

You software depends on no other Bioconductor packages. Usually this means that you have not recognized that your data could be represented in [standard Bioconductor objects][1]. Please review your code and use appropriate Bioconductor data representations.

When you have updated your repository with these changes, please post a short comment here tagged with @mtmorgan.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by shahryary** [comment]
@mtmorgan 

Thank you for your message. We have updated the vignette file. 

Also, in response to your second note, we would like to point out that we are using the outputs from the Bioconductor Methimpute* package. These outputs are either text files or GRanges objects (see "Preparing Files in the vignette file below). 

* [Methimpute package](https://bioconductor.org/packages/release/bioc/html/methimpute.html)

**Comment by mtmorgan** [comment]
The package looks good with mostly minor changes suggested below.

DESCRIPTION

- good

vignettes

- good

R (file.R:line numbers are illustrations, update for all occurrences

- generally, the code looks highly repretitive (e.g., in the AB*.R files). Is it not possible to write shorter helper functions and re-use these?

- ABneutral.R:154 use `message()` rather than `cat()` for progress

- ABneutral.R:164 avoid 'copy-and-append' using `rbind()`, as this is very inefficient. Instead, pre-allocate the memory and fill results, or accumulate in a pre-allocated list and invoke a single `do.call("rbind", final)` or simply use `sapply()`.

- ABnull.R:36 use spaces (preferred) or tabs consistently

- Suggestion: Use BiocParallel for parallel evaulation, for consistency with other Bioconductor packages

- test.R: entirely commented out; remove.

man

- some man pages, e.g., `makePHYLO` are too sparse. Fully describe data inputs and outputs, e.g., the relationship between the argument `tall` as 'pedigree data' to the example value '330' is completely unclear. Likewise, fully describe the return value -- 'pedigree data', so I guess that means '330'??

**Comment by shahryary** [comment]
@mtmorgan 

Thank you very much for your feedback.
I applied your notes and pushed the new version into Github. 

> The package looks good with mostly minor changes suggested below.
> 
> DESCRIPTION
> 
> * good
> 
> vignettes
> 
> * good
> 
> R (file.R:line numbers are illustrations, update for all occurrences
> 
> * generally, the code looks highly repretitive (e.g., in the AB*.R files). Is it not possible to write shorter helper functions and re-use these?

We are using diffrent parameters in AB* files which is making it difficult to re-use it but there are some parts that we can re-use. I'm working on it for the next update.

> * ABneutral.R:154 use `message()` rather than `cat()` for progress

Done.

> * ABneutral.R:164 avoid 'copy-and-append' using `rbind()`, as this is very inefficient. Instead, pre-allocate the memory and fill results, or accumulate in a pre-allocated list and invoke a single `do.call("rbind", final)` or simply use `sapply()`.

Done.

> * ABnull.R:36 use spaces (preferred) or tabs consistently

Done.

> * Suggestion: Use BiocParallel for parallel evaulation, for consistency with other Bioconductor packages

Replaced with BiocParallel.

> * test.R: entirely commented out; remove.

Removed.

> man
> 
> * some man pages, e.g., `makePHYLO` are too sparse. Fully describe data inputs and outputs, e.g., the relationship between the argument `tall` as 'pedigree data' to the example value '330' is completely unclear. Likewise, fully describe the return value -- 'pedigree data', so I guess that means '330'??

Updated man pages.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shahryary.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AlphaBeta")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AlphaBeta

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
