### ISSUE TITLE
brendaDb

### ISSUE THREAD

**Issue by y1zhou** [Bioconductor/Contributions#1184]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/y1zhou/brendaDb

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by y1zhou** [comment]
Any updates on this? I created the issue right before GitHub when down yesterday, so I'm not sure if the bot is triggered correctly. Thanks!

**Comment by y1zhou** [comment]
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> On one or more platforms, the build results were: "ERROR".
> This may mean there is a problem with the package that you need to fix.
> Or it may mean that there is a problem with the build system itself.
> 
> Please see the [build report](http://bioconductor.org/spb_reports/brendaDb_buildreport_20190731140141.html) for more details.

The error seems to be with the build system? `/Library/Frameworks/R.framework/Resources/bin/Rcmd: line 62: exec: BiocCheckGitClone: not found`. The package itself built without problems on [Travis CI](https://travis-ci.org/y1zhou/brendaDb/builds/566100092).

**Comment by lshep** [comment]
You will have a report with the other platforms shortly.  we updated our version of R this afternoon on the mac builder and it seems to be missing the BiocCheck package.  We will remedy this shortly

**Comment by lshep** [comment]
Please ignore the mac error for now - this will be fixed on our end

**Comment by y1zhou** [comment]
Been looking at some of the other submitted packages, and now I'm wondering if the `brenda.query` object in my package could be replaced by the `SummarizedExperiment` class. Would love some input from the Bioconductor team!

**Comment by lshep** [comment]
Sorry for the delayed review. I will review over there weekend and post by Monday.

In general we strongly encourage using or extending existing bioconductor classes so they can integrate with other packages. If it's possible to incorporate i would suggest it.

**Comment by lshep** [comment]
Thank you for your submission please see the following additional comments: 

**README**

- [ ] Include Bioconductor installation instructions


**DESCRIPTION**

- [ ] biocViews maybe also DataImport? 

**inst/extdata**

- [ ] Could you please include a inst/scripts directory that describes (either in text, sudo code, or code. How the data files in inst/extdata were created.

**data/man for data**

- [ ] Could you please expand the man file for the acronymns.RData file. What is the source of the file? how was it generated? ect.


**General**

- [ ] Please see [BiocFileCache](http://bioconductor.org/packages/BiocFileCache/) for managing donwloaded resources.  This will download the file onto a users system and keep track for easy retrieval. I recommend DownloadBrenda and ReadBrenda are updated to use BiocFileCache. Also if the user forgets where they download, you would be able to rerieve for them, and if the website is down you dont have to worrry about it if there is already a copy saved somewhere. BiocFileCache has internal functions for checking to see if the remote file has been updated or not so you could check if redownload is necessary. 

- [ ] You could also possibly store the converted text file results of ReadBrenda in the cache so that it is quicker if it has already been done before. (considering I was going on 15 min waiting and cancelled out - Do you have any estimate on average how long this takes? - The user would generally do the full Db or is there a way to download a subset? ). This way the conversion may take a long time the first time but then skipped and just accessed as a file any subsequential time. 

- [ ] I mention this below too but please ensure all functions are either exported and documented or that internal functions are marked with internal. 

- [ ] For my own knowledge (and being unfamiliar with this data) could you just explain what goes on when an item is "TRANSFERRED_DELETED".  I'm not quite following if/why it is removed or excluded or what is exactly happening here (more just for my own curiosity)?  


**vignette**

- [ ] [Optional] Just from a personal point of view. I think its more intuitive for a user to do  `vignette("brendaDb")`  rather than `vignette("brendaDb-vignette")`  But this is just my own observation.  

- [ ] include Bioconductor installations instructions


**R/man**

**brendaDb.R**

- [ ] Perhaps on the package help page also reference the main functions or vignette for where to go to next for help using the package. 


**brendaEntry.R**

- [ ] InitBrendaEntry and InitBrendaDeprecatedEntry are an internal function and should be marked as such.

- [ ] I'm not quite sure I understand when and what object is passed into is.brenda.entry and is.brenda.dperecated.entry?  Please expand on the documentation if you are going to export these.

**parse-bibliography.R/parse-helper.R/...**

- [ ] Please mark all internal functions as such. Functions not executed by the
  user should be marked as internal.  Functions to be used by the user should be
  exported.  (See also ConfigBPCores, SelectOrganism...etc.... Please check that
  all functions are exported/documented or that the documentation includes
  internal for non-exported functions. 




In general I feel like the code is written well.  Please address the above issues and respond back here is comments/clarification as necessary.  When ready please perform a version bump and request a re-review.  

Cheers, 
Lori

**Comment by y1zhou** [comment]
Hi Lori,

Thank you so much for all your feedback on the package! All the issues should be addressed now, and here's the ones that need some more clarification.

> **DESCRIPTION**
> **inst/extdata**
> 
> * [x]  Could you please include a inst/scripts directory that describes (either in text, sudo code, or code. How the data files in inst/extdata were created.

I put a text file under `inst/scripts` that describes how the data file was generated. The file is used for testing and demonstration purposes so it's essentially handpicked chunks from the original file.

> **General**
> 
> * [x]  Please see [BiocFileCache](http://bioconductor.org/packages/BiocFileCache/) for managing donwloaded resources.  This will download the file onto a users system and keep track for easy retrieval. I recommend DownloadBrenda and ReadBrenda are updated to use BiocFileCache. Also if the user forgets where they download, you would be able to rerieve for them, and if the website is down you dont have to worrry about it if there is already a copy saved somewhere. BiocFileCache has internal functions for checking to see if the remote file has been updated or not so you could check if redownload is necessary.
> * [ ]  You could also possibly store the converted text file results of ReadBrenda in the cache so that it is quicker if it has already been done before. (considering I was going on 15 min waiting and cancelled out - Do you have any estimate on average how long this takes? - The user would generally do the full Db or is there a way to download a subset? ). This way the conversion may take a long time the first time but then skipped and just accessed as a file any subsequential time.

The file is now downloaded using `BiocFileCache`. Thanks a lot for bringing this package up! I didn't know it existed and it made the process so much easier. 
I improved the converting code a bit and it now takes ~12s on my machine to load the entire file. Could you please test it on your machine again? If it's still taking a really long time then I'll try re-writing the C++ code to provide an option for only reading part of the file.
Since the return of `ReadBrenda()` is just a `tibble`, if the users feel they are going to need it again later they can just save it to their desired locations using `data.table::fwrite()` or `save()`. I added a message here but I'll leave it for the users to decide :)

> * [x]  For my own knowledge (and being unfamiliar with this data) could you just explain what goes on when an item is "TRANSFERRED_DELETED".  I'm not quite following if/why it is removed or excluded or what is exactly happening here (more just for my own curiosity)?

TRANSFERRED_DELETED is when the classification of the enzyme was found to be incorrect, and there's an update to the EC number of the enzyme. Usually there would be some information pointing to the new / corrected EC entry.

Thanks again for your time in reviewing the package. Hope everything looks good now!

**Comment by lshep** [comment]
A few very minor comments that are entirely optional: 

**General**

- [x] Thanks for switching to BiocFileCache. I think it will help improve relablitiy

- [x] Thank you for the speed up changes - I too can now load in 12-15 seconds the full set. 


**Vignette**

**Query for Multiple Enzymes**

- [ ] I would advertise more that the brenda.entries object (res) can be subset by EC number.  I would assume if a user may enter multiple EC numbers that advertising this sort of subsetting would be useful which seems already implemented (But again I don't work with this data so maybe not?)

- [ ] Also personal preference I think its cleaner to show subsetting through the traditional bracket methods (but again totally optional)

```
res[["1.1.1.1"]][["interactions"]][["substrate.product"]]

```

- [ ] The above made me think if having a defined accessor method for at least the top level categories of the brenda.entries object may be useful? If you were looking at a single EC number like above for instance having an interactions function that would pull that out.  Again I don't work with this data so maybe its not necessary but having accessor methods for objects is always preferrable rather than users having to manually manipulate objects. It might not be necessary to have these for every level but perhaps ones that would be frequently accessed?  

```
interactions(res, "1.1.1.1")
organism(res, "1.1.1.1")
etc... 
```

Package looks in really good shape.  Please let me know if you plan on implementing any of the above suggestions.

**Comment by y1zhou** [comment]
Hi Lori,

> A few very minor comments that are entirely optional:
> 
> **General**
> 
> * [x]  Thanks for switching to BiocFileCache. I think it will help improve relablitiy
> * [x]  Thank you for the speed up changes - I too can now load in 12-15 seconds the full set.
> 
> **Vignette**
> 
> **Query for Multiple Enzymes**
> 
> * [x]  I would advertise more that the brenda.entries object (res) can be subset by EC number.  I would assume if a user may enter multiple EC numbers that advertising this sort of subsetting would be useful which seems already implemented (But again I don't work with this data so maybe not?)

Since `brenda.entries` objects are named lists, they can be directly subsetted by EC numbers (using `$` or `[[`).

> * [x]  Also personal preference I think its cleaner to show subsetting through the traditional bracket methods (but again totally optional)
> 
> ```
> res[["1.1.1.1"]][["interactions"]][["substrate.product"]]
> ```
> 
> * [x]  The above made me think if having a defined accessor method for at least the top level categories of the brenda.entries object may be useful? If you were looking at a single EC number like above for instance having an interactions function that would pull that out.  Again I don't work with this data so maybe its not necessary but having accessor methods for objects is always preferrable rather than users having to manually manipulate objects. It might not be necessary to have these for every level but perhaps ones that would be frequently accessed?
> 
> ```
> interactions(res, "1.1.1.1")
> organism(res, "1.1.1.1")
> etc... 
> ```
> 
> Package looks in really good shape. Please let me know if you plan on implementing any of the above suggestions.

I created a `ExtractField()` getter method for `brenda.entries` objects. It's not the neatest solution but it's at least better than having users manipulate the object directly. Thanks for the suggestion!

**Comment by y1zhou** [comment]
Hi @mtmorgan, thanks for accepting the package! Is there anything else I need to do on my end to proceed to the next step?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/y1zhou.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("brendaDb")`. The package 'landing page' will be created at

https://bioconductor.org/packages/brendaDb

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
