### ISSUE TITLE
IgGeneUsage

### ISSUE THREAD

**Issue by snaketron** [Bioconductor/Contributions#1187]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/snaketron/IgGeneUsage

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It sounds like the input data could be represented as a [SummarizedExperiment][1] and this representation should be supported for robustness and interoperability with other packages in the Bioconductor community.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by snaketron** [comment]
Yes, I considered implementing this, however, I found the SummarizedExperiment object much more complex than the commonly expected input of IgGeneUsage -> simple table with counts.

I will nevertheless implement the additional interface for the Bioconductor users.

Best

**Comment by snaketron** [comment]
Dear developers (@mtmorgan),

I am rethinking the idea of representing the input data of IgGeneUsage as SummarizedExperiment object, as this class is much more general (and thus complex) than the typical input of IgGeneUsage. I believe this would limit the usability of the package in the R-community.

To nevertheless help the Bioconductor community, I developed a short vignette explaining how to convert an existing SummarizedExperiment object into a proper input for IgGeneUsage.

Please let me know what you think about this. Otherwise, the package has passed all checks and I am looking forward to the next part of the review.

Best

**Comment by mtmorgan** [comment]
A better approach is to adapt your interface to accept SummarizedExperiment, perhaps in addition to your alternative representation; while SummarizedExperiment is unfamiliar to the general R user, it is very widely used in the Bioconductor community. By writing an interface, you relieve the user of having to follow, perhaps in an error-prone way, the instructions that you would otherwise lay out in your vignette.

**Comment by snaketron** [comment]
Thank you for the suggestion. I implemented the additional interface.

**Comment by mtmorgan** [comment]
This package looks good, with a few minor suggestions below.

DESCRIPTION

- please provide a more complete Description: of what your package does, e.g., like an abstract

- Including a copy of the GPL license is not required, since it is distributed with R

- It is unlikely that the user directly interacts with Rcpp; this should be in 'Imports:' rather than 'Depends:'.

vignettes

- it's not clear how ModelOverview.Rmd represents a standalond vignette?

- IgUsageCaseStudies.Rmd seems mostly to use base R commands and ggplot; revise so it is clear how your package contributes to understanding. In particular the key function seems to be `DGU()`, but the use of this function is in code chunks presented without description of inputs or interpretation of outputs.

R

- e.g., Usage.R:49 use `message()` rather than `cat()` to communicate progress to the user

- Util.R:176 this 'copy-and-append' pattern is very inefficient, use `sapply()` or pre-allocate and fill a list followed by a single `do.call("rbind", ...)` instead

man

- ok

tests

- good

**Comment by snaketron** [comment]
Thank you for your suggestions @mtmorgan .

> This package looks good, with a few minor suggestions below.
> 
> DESCRIPTION
> 
>     * please provide a more complete Description: of what your package does, e.g., like an abstract
- provided
> 
>     * Including a copy of the GPL license is not required, since it is distributed with R
- extra GPL license removed
> 
>     * It is unlikely that the user directly interacts with Rcpp; this should be in 'Imports:' rather than 'Depends:'.
- Rccp is necessary for runtime compilation of stan models
> 
> 
> vignettes
> 
>     * it's not clear how ModelOverview.Rmd represents a standalond vignette?
- removed vignette. Methods section describing the model was added in IgUsageCaseStudies.Rmd

>     * IgUsageCaseStudies.Rmd seems mostly to use base R commands and ggplot; revise so it is clear how your package contributes to understanding. In particular the key function seems to be `DGU()`, but the use of this function is in code chunks presented without description of inputs or interpretation of outputs.
- vignette restructured with more focus on inputs/outputs of DGU
- all input parameters are explained in more detail
> 
> 
> R
> 
>     * e.g., Usage.R:49 use `message()` rather than `cat()` to communicate progress to the user
- all cat -> message
>     * Util.R:176 this 'copy-and-append' pattern is very inefficient, use `sapply()` or pre-allocate and fill a list followed by a single `do.call("rbind", ...)` instead
- pre-allocated list followed by do.call("rbind", ...)
> 
> man
> 
>     * ok
> 
> 
> tests
> 
>     * good

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/snaketron.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("IgGeneUsage")`. The package 'landing page' will be created at

https://bioconductor.org/packages/IgGeneUsage

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
