### ISSUE TITLE
calm

### ISSUE THREAD

**Issue by k22liang** [Bioconductor/Contributions#1188]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/k22liang/calm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It seems like your package should re-use the [SummarizedExperiment][1] representation for gene & phenotype information, and the [GenomicRanges][2] package `GRanges` class for representing, e.g., genomic coordinates.

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/packages/GenomicRanges

**Comment by k22liang** [comment]
Change the version number from 0.9.0 to 0.99.0 to fix the error. Now it should be OK.

**Comment by k22liang** [comment]
> It seems like your package should re-use the [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment) representation for gene & phenotype information, and the [GenomicRanges](https://bioconductor.org/packages/GenomicRanges) package `GRanges` class for representing, e.g., genomic coordinates.


Thanks for the suggestion. My package directly works on the test statistics (e.g., t-statistics and its derived z-values) from a genetic experiment, in addition to covariate information, such as gene coding region length. My understanding is that SummarizedExperiment and ExpressionSet can be used to contain RNA-seq and microarray data, and after applying DESeq or limma, we can obtain the test statistics. In this sense, SummarizedExperiment can be used upstream before applying my package.

**Comment by nturaga** [comment]
> > It seems like your package should re-use the [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment) representation for gene & phenotype information, and the [GenomicRanges](https://bioconductor.org/packages/GenomicRanges) package `GRanges` class for representing, e.g., genomic coordinates.
> 
> Thanks for the suggestion. My package directly works on the test statistics (e.g., t-statistics and its derived z-values) from a genetic experiment, in addition to covariate information, such as gene coding region length. My understanding is that SummarizedExperiment and ExpressionSet can be used to contain RNA-seq and microarray data, and after applying DESeq or limma, we can obtain the test statistics. In this sense, SummarizedExperiment can be used upstream before applying my package.

@mtmorgan Is this response satisfactory? There isn't any reuse of existing methods for importing data, and reusing established classes for representing data.

**Comment by mtmorgan** [comment]
yes

**Comment by Kayla-Morrell** [comment]
Hello @k22liang,

Thank you for submitting to _Bioconductor_. Please see the initial review of your package below. The package was very nicely put together so there aren't many requirements needed to be met for acceptance. The suggestions are not necessary but are strongly encouraged. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to false. When this field is set to 
true it is our experience that the loading of a package with data gets slowed 
down.

- [ ] SUGGESTION: We strongly encourage including a 'BugReports:' field which 
should include a relevant GitHub link for reporting Issues. 

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file, this is very helpful when 
keeping track of changes to the code from version to version. However, the file
 you have is not formatted properly. Please look at the following link to see 
how the news files should be created so they are rendered properly, 
https://bioconductor.org/developers/package-guidelines/#news

## Vignette

- [ ] REQUIRED: After the "Introduction" section and before the "Conditional 
local FDR" section add an “Installation” section that shows the users how to 
download the package from Bioconductor. The code should look something like:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("calm")
```

## Man pages

*CLfdr*

- [ ] REQUIRED: The example code should demonstrate how to use `CLfdr()`.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@k22liang - Thank you for making the necessary changes and providing clarification about the unit tests. Everything looks good now and I'm happy to accept the package!

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/k22liang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("calm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/calm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
