### ISSUE TITLE
Spaniel

### ISSUE THREAD

**Issue by RachelQueen1** [Bioconductor/Contributions#1202]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RachelQueen1/Spaniel

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by RachelQueen1** [comment]
Hi, Just wondered if there is anything I need to do as I haven't had an update for a while? Thanks in advance

**Comment by nturaga** [comment]
Hi @RachelQueen1 ,

I will review your package and post a review in a few days time. 

Best,

Nitesh

**Comment by RachelQueen1** [comment]
Great, thank you :)

Rachel

**Comment by nturaga** [comment]
> Great, thank you :)
> 
> Rachel

Please take a look at the edits in my previous comment.

**Comment by RachelQueen1** [comment]
Thanks, I have added the web hook.

**Comment by nturaga** [comment]
Hi, 

I'm reviewing your package and I cannot get the vignette to run,

```
    sce <- scater::addQCPerCell(
        sce, 
    )
```

The package `scater` doesn't have the function `addQCPerCell`.

```
Error: processing vignette 'spaniel-vignette.Rmd' failed with diagnostics:
'addQCPerCell' is not an exported object from 'namespace:scater'
```

Could you let me know how to run the vignette? 

best,

Nitesh

**Comment by RachelQueen1** [comment]
Hi Nitesh, 

Thanks for starting the review process. I have now addressed the problem with the Description and removed the dead code.  addQCPerCell  is exported from the development version of Scater: https://bioconductor.org/packages/devel/bioc/html/scater.html. The function replaces calculateQCMetrics and I was getting a warning message to say that that function would soon be depreciated. Is it the right thing to do to use the development version of scater or should I stick with the current version in Bioconductor? 

Thanks in advance, 

Rachel

**Comment by lshep** [comment]
New packages and packages being submitted should use the development version of Bioconductor (and therefore the devel version of packages). So this is the right version to be developing against  https://bioconductor.org/packages/devel/bioc/html/scater.html  . Cheers.

**Comment by nturaga** [comment]
## Update

* Variable naming is not consistent. `MetaData` vs `whichCols`, use
  only one type of casing. Use either, "UpperCamelCase" or
  "lowerCamelCase"(recommended). Just make sure your variable names
  are consistent across.

* Add the Bioconductor way of installing the package in the vigneette
  `BiocManager::install('Spaniel')`.

* `readSeurat()` and `readSCE()` are not very descriptive of
  "creating" seurat or SCE objects. The function name should probably be `createSeurat` and `createSCE()`

* It would also help if you used markdown formatting features to
  annotate your vignette to make it more readable. Function calls can
  be `functionCall()`, and important points can be marked as
  **important**. This allows greater readability.

**Comment by RachelQueen1** [comment]
Hi @nturaga 

Thanks for looking at my code. I have made the suggested edits. 

Best wishes, 

Rachel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/RachelQueen1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Spaniel")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Spaniel

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
