### ISSUE TITLE
Qtlizer

### ISSUE THREAD

**Issue by matmu** [Bioconductor/Contributions#1203]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/matmu/Qtlizer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It seems that the return value should be a GenomicRanges::GRanges object, or perhaps VariantAnnotation:VRanges; please update your package to use existing Bioconductor infrastructure to increase code robustness and interoperability with other packages.

**Comment by matmu** [comment]
> Hello @matmu,
> 
> Before I can perform an initial review of the package there are a couple things that must be done.
> 
> 1. Please be sure you address @mtmorgan's comment:
> 
> > It seems that the return value should be a GenomicRanges::GRanges object, or perhaps VariantAnnotation:VRanges; please update your package to use existing Bioconductor infrastructure to increase code robustness and interoperability with other packages.
> 
> 1. Please perform the required version bump.
> 
> Once both of these are done then I will be able to provide you a proper review of the package.
> 
> Best,
> Kayla

Dear Kayla, we added the optional parameter `return_obj` which is "dataframe" by default but can be set to "grange" in order to return a **GenomicRanges::GRanges** object. Also, the version has been bumped.

**Comment by matmu** [comment]
> Hello @matmu,
> 
> Thank you for making those changes. Please see the initial review of the package below. The suggestion points are not mandatory but are strongly encourage. Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## DESCRIPTION
> * [ ]  SUGGESTION: Look at the 'Title:' field, the quotetation marks don't seem
>   correct (please justify if this was intended).
> * [ ]  REQUIRED: For the 'License:' field, you list a license that does not
>   require '+ LICENSE'. Therefore the LICENSE file should be removed from the top
>   level of the repository.
> * [ ]  REQUIRED: 'LazyData:' should be set to false. Having this field set to
>   true can slow down the loading of the package.
> * [ ]  SUGGESTION: We strongly encourage the use of the 'BugReports:' tag that
>   includes a relevant GitHub link for reporting issues. I know you have some links
>   provided when the package is loaded, but this link would be located on the
>   landing page on _Bioconductor_ for the package.
> 
> ## Vignette
> * [ ]  REQUIRED: Following the 'Introduction' section there should be an
>   'Installation' section that shows the user how to download the package from
>   _Bioconductor_. This section can also include loading the package. The code
>   should look something like this:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("Qtlizer")
> ```
> 
> * [ ]  SUGGESTION: For section 3 "Example function calls", you might mention what
>   type of data should be read into the funtion. Is it only names of SNPs or can
>   other data types be used? (I see later on in the example both a name of a SNP
>   and a gene name are used when passing a vector)
> * [ ]  REQUIRED: Line 47, look at the wording of the last sentence. I think it
>   should read "...can be set with `corr` and ranges between 0 and 1.". There seems
>   to be an extra 'between' before `corr`.
> * [ ]  REQUIRED: Line 60, in the last sentence you only list one allowed value
>   even though there is another one used in the example. Be sure to list both
>   allowed values.
> 
> ## Man pages
> * [ ]  SUGGESTION: Only functions that are exported need to have a man page. For
>   those functions you have documented already that aren't exported, you can add
>   the tage `@keywords internal` which will remove the function from the
>   documentation index.
> 
> ## Unit tests
> * [ ]  NOTE: Consider adding unit tests, we strongly encourage them.
> 
> ## R code
> * [ ]  REQUIRED: Avoid 1:..., use `seq_len()` or `seq_along()` instead. Found in
>   file 'get_qtls.R', line 186.
> * [ ]  SUGGESTION: Thank you for incorporating the GRanges object in your code.
>   Ideally we would have liked the default of 'return_obj' to be a GRanges object,
>   but what you implemented works as well.
> * [ ]  SUGGESTION: Look over our notes for querying web resources
>   (http://bioconductor.org/developers/how-to/web-query/). You may find helpful
>   information to be sure your package doesn't TIMEOUT when building each
>   day on our build systems.
> 
> Best,
> Kayla

Dear Kayla,

we followed all your suggestions & requirements except the unit tests and pushed a new version.

Looking forward to hear from you!

Best,
Matthias

**Comment by Kayla-Morrell** [comment]
@matmu - All the changes look good. I have just one more requirement and then I'll be happy to accept the package. 

## Vignette

- [ ] REQUIRED: Thank you for including the 'Installation' section. This section
of code can include `eval = FALSE` so that the warning messages aren't shown.

Best,
Kayla

**Comment by matmu** [comment]
> @matmu - All the changes look good. I have just one more requirement and then I'll be happy to accept the package.
> 
> ## Vignette
> * [ ]  REQUIRED: Thank you for including the 'Installation' section. This section
>   of code can include `eval = FALSE` so that the warning messages aren't shown.
> 
> Best,
> Kayla

Done!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/matmu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Qtlizer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Qtlizer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
