### ISSUE TITLE
SingleR

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1206]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/SingleR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment]
Ha, got the full set. The mac one is a bit weird. The windows one... I'll bet the parallelization tests are making it spit the dummy again.

**Comment by LTLA** [comment]
Tagging @lshep:

We (cc @friedue) were also hoping to upload some reference data to EHub that goes with this package. We have most things in place and can upload things fairly soon.

The only question is whether the BioC infrastructure is happy with a software package being the main "owner" of an ExperimentHub resource. BiocCheck, for example, was not happy with me putting down `ExperimentHub` as a biocViews for a software package.

**Comment by lshep** [comment]
This was discussed -  I  would say to remove the ExperimentHub biocView to avoid the check ERROR.  (Yes it will cause makeExperimentHubMetadata to fail but I can add this tag in momentarily on my local copy for it to be valid for when I add data into the database)

**Comment by LTLA** [comment]
@lshep Files are on EHub under `SingleR/`.

**Comment by mtmorgan** [comment]
is there a reason why this package doesn't have a more informative name, e.g., scAnnotate?

**Comment by LTLA** [comment]
Not beyond the fact that's the name with which it was published.

I don't disagree with your assessment of the name, but there's an established userbase for this package and changing the name would make it tricky to get them to switch to the BioC version.

**Comment by LTLA** [comment]
@lshep Did the uploaded data get put into EHub?

**Comment by lshep** [comment]
@LTLA   Sorry for the delay I was out on a 2 week holiday.  I'm looking it over and should have it uploaded later today.

**Comment by lshep** [comment]
Just wanted to check in @LTLA :  There are metadata files in SingleR for dice, dmap, and monaco_immune  but there was no data uploaded for them.  Should data be uploaded for these? 
I'm working on the other four now and will let you know when they are available or if I run into any issues.

**Comment by j-andrews7** [comment]
I am currently prepping those sets - they should be done by tomorrow or Friday at the latest.

**Comment by lshep** [comment]
Awesome.  The other 4 were added and now available; let me know if there are any issues. 
```
> query(eh, "SingleR")
ExperimentHub with 8 records
# snapshotDate(): 2019-09-04 
# $dataprovider: Benayoun Lab, Blueprint and ENCODE, Human Primary Cell Atla...
# $species: Homo sapiens, Mus musculus
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3088"]]' 

           title                             
  EH3088 | Blueprint/Encode RNA-seq logcounts
  EH3089 | Blueprint/Encode RNA-seq colData  
  EH3090 | Human Primary Cell Atlas logcounts
  EH3091 | Human Primary Cell Atlas colData  
  EH3092 | ImmGen logcounts                  
  EH3093 | ImmGen colData                    
  EH3094 | Mouse bulk RNA-seq logcounts      
  EH3095 | Mouse bulk RNA-seq colData        
```

**Comment by dvantwisk** [comment]
Hi @LTLA 
I apologize for the silence on my end and the wait. I always feel odd about accepting a package without adding any suggestions and try to agonize over finding things that I would change in the code or documentation, but this is a case where the package looks excellent as it is. I am going to move to accept it now.

**Comment by LTLA** [comment]
All right! Thanks Dan.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingleR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingleR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
