### ISSUE TITLE
microbiomeDASim

### ISSUE THREAD

**Issue by williazo** [Bioconductor/Contributions#1216]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/williazo/microbiomeDASim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hello @williazo,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The raw package directory should not contain unnecessary files, 
system files, or hidden files. These files may be present in your local 
directory but should not be commited to git. The 'BiocCheck-comments' and 
'cran-comments' files, also the 'doc/' directory, don't seem necessary but 
please clarify if I am mistaken.

- [ ] REQUIRED: Currently, the 'SIMULATION/' directory would not be distributed
 to users through your package. When we build packages we build off of specific
 things in the repo and this directory is not one of those things. If you want 
this to be apart of the _Bioconductor_ package I suggest you put it within an 
'inst/' directory. Even just placing the Jupyter notebook within an 
'inst/script/' directory would be better, since this is where we ask developers
 to house scripts for creating extdata in their packages. This will insure that
 it is included since we keep things in this 'inst/' directory when building 
packages from GitHub.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to false. This field being true can 
slow down the loading of the package.

## Vignettes

- [ ] SUGGESTION: The idea of the 'Introduction' section is to almost be an 
abstract to introduce the objective, models, unique functions, key points, etc 
that distinguish the package from other packages of similar type. The 
information you have currently is a good motive for using the package but I 
would add a bit more detail about the actual package. 

- [ ] REQUIRED: After the 'Introduction' section there should be an 
'Installation' section that shows users how to download and the package from 
_Bioconductor_. The code should look something like this:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("microbiomeDASim")
```

- [ ] REQUIRED: The last section of the vignette should be Session Info and 
should include `sessionInfo()`.

## man pages

- [ ] SUGGESTION: Only functions that are exported need to have a man page. For
 those functions you have documented already that aren't exported, you can add 
the tag `@keywords internal` which will remove the function from the 
documentation index.

## Unit tests

- [ ] CLARIFICATION: What is the purpose of the 'Rplots.pdf' file in the 
'test/testthat' directory?

Best,
Kayla

**Comment by williazo** [comment]
Hi @Kayla-Morrell,

Thank you for your review comments above, I have gone through and updated the package based on your feedback and have included details for each of your points below.

# General package Development 
- [x] REQUIRED: The raw package directory should not contain unnecessary files,
system files, or hidden files. These files may be present in your local
directory but should not be commited to git. The 'BiocCheck-comments' and
'cran-comments' files, also the 'doc/' directory, don't seem necessary but
please clarify if I am mistaken.

I have removed the build comments (BiocCheck and cran) and 'doc/' directory from the package directory (commit a6d455d).

- [x] REQUIRED: Currently, the 'SIMULATION/' directory would not be distributed
to users through your package. When we build packages we build off of specific
things in the repo and this directory is not one of those things. If you want
this to be apart of the Bioconductor package I suggest you put it within an
'inst/' directory. Even just placing the Jupyter notebook within an
'inst/script/' directory would be better, since this is where we ask developers
to house scripts for creating extdata in their packages. This will insure that
it is included since we keep things in this 'inst/' directory when building
packages from GitHub.

As suggested I moved the Jupyter notebook into an `inst/script/' directory to allow for it to be distributed. I think it provides a useful framework for a hands on introduction to using the package and some of the rationale (commit c2ad972).

# Description

- [x] REQUIRED: 'LazyData:' should be set to false. This field being true can
slow down the loading of the package.

I have changed this to false in the Description file (commit 83adb13).

# Vignettes

- [x] SUGGESTION: The idea of the 'Introduction' section is to almost be an
abstract to introduce the objective, models, unique functions, key points, etc
that distinguish the package from other packages of similar type. The
information you have currently is a good motive for using the package but I
would add a bit more detail about the actual package.

As suggested I re-wrote the Introduction section to highlight the objective of the simulation package and some of the key functions involved in simulating the longitudinal differential abundance. I moved the previous Introduction section into a new Motivation section after the  Installation section (commit 828cf40).

- [x] REQUIRED: After the 'Introduction' section there should be an
'Installation' section that shows users how to download and the package from
Bioconductor

The Installation section has been added (commit 828cf40).

- [x]  REQUIRED: The last section of the vignette should be Session Info and
should include `sessionInfo()`.

The Session Info section has been added (commit 828cf40).

# man pages

- [x] SUGGESTION: Only functions that are exported need to have a man page. For
those functions you have documented already that aren't exported, you can add
the tag @keywords internal which will remove the function from the
documentation index.

I have added @keywords internal for all of the helper function that aren't exported (commit 7f089b1).

# Unit tests

- [x] CLARIFICATION: What is the purpose of the 'Rplots.pdf' file in the
'test/testthat' directory?

I believe that this Rplots.pdf file was created by accident as my test scripts had examples where the plot graphics were turned on. I have removed this file manually and have also changed the test scripts so that the graphics are turned off for all examples (commit 0149350).

I look forward to hearing additional comments and/or suggestions.

Best,
Justin

**Comment by Kayla-Morrell** [comment]
Hi @williazo,

Thank you for making the changes and providing details for each point. Everything looks good and I'm happy to accept the package!

Best,
Kayla

**Comment by williazo** [comment]
Thanks @Kayla-Morrell! I will look out for further instructions and additional information in the coming days.

Best,
Justin

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/williazo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("microbiomeDASim")`. The package 'landing page' will be created at

https://bioconductor.org/packages/microbiomeDASim

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
