### ISSUE TITLE
BioTIP

### ISSUE THREAD

**Issue by xyang2uchicago** [Bioconductor/Contributions#1220]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xyang2uchicago/BioTIP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by xyang2uchicago** [comment]
Can we ignore these warnings? @mtmorgan @dvantwisk 
Warning in rgl.init(initValue, onlyNULL) :
  RGL: GLX extension missing on server
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning in rgl.init(initValue, onlyNULL) :
  RGL: GLX extension missing on server
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
** testing if installed package can be loaded from final location
Warning in rgl.init(initValue, onlyNULL) :
  RGL: GLX extension missing on server
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
** testing if installed package keeps a record of temporary installation path
* DONE (BioTIP)

**Comment by xyang2uchicago** [comment]
also not sure how to solve this error:
Error in .get_entry_index(name, stop_if_missing) : 
  Entry TSDistances not in registry.

**Comment by zhezhenwang** [comment]
Hi @mtmorgan @dvantwisk @ttriche Is there anything else we need to do to trigger a technical review?

**Comment by dvantwisk** [comment]
I've started reviewing your package. I should have it in to you soon.

**Comment by dvantwisk** [comment]
Apologies for the delay. Here is a review of your package. The code looks good but I have a few small issues to address. [REQUIRED] tags must have changes made or addressed. [CONSIDER] tags describe changes are advisable but not necessary. Please message me back when you are finished making changes.

R/BioTIP.R
- [ ] [CONSIDER] L1182: Use `match.arg()`. In the function delcaration for
`getIc()`, `output` can be written as `output=c('Ic', 'PCCG', 'PCCs')`.
The default value is the first value, `'Ic'`. In the function body,
the user's choice can be otained with `ouput <- match.arg(output)`. This way
is prefferable because it shows the possible values of `output` when the
function is displayed and it also throws an error if any value aside from the
listed values is given. This can be done in multiple places.
- [ ] [REQUIRED] Use `seq_len()` instead of `1:length()`. This is slightly
faster and catches the unexpected case where `1:0` is `1 0`. `seq_along()`
can also be used in certain cases.
- [ ] [REQUIRED] L535,1045: Use `message()` instead of `print()` for user-facing
messages. This is preferable becuase they can be toggled off with
`supressMessages()`.

DESCRIPTION.bak
- [ ] [REQUIRED] Remove the `DESCRIPTION.bak` file.

vignettes/BioTIP.Rmd.bak
- [ ] [REQUIRED] Remove the `BioTIP.Rmd.bak` file.

**Comment by xyang2uchicago** [comment]
@dvantwisk Hi I have finished updating.

**Comment by xyang2uchicago** [comment]
@dvantwisk Hi let me know if there's anything else we need to do, thanks!

**Comment by xyang2uchicago** [comment]
Hi @dvantwisk just want to let you know that we finished updating our package based on the following suggestions you provided:

[CONSIDER] L1182: Use match.arg(). In the function delcaration for
getIc(), output can be written as output=c('Ic', 'PCCG', 'PCCs').
The default value is the first value, 'Ic'. In the function body,
the user's choice can be otained with ouput <- match.arg(output). This way
is prefferable because it shows the possible values of output when the
function is displayed and it also throws an error if any value aside from the
listed values is given. This can be done in multiple places.
 [REQUIRED] Use seq_len() instead of 1:length(). This is slightly
faster and catches the unexpected case where 1:0 is 1 0. seq_along()
can also be used in certain cases.
 [REQUIRED] L535,1045: Use message() instead of print() for user-facing
messages. This is preferable becuase they can be toggled off with
supressMessages().
DESCRIPTION.bak

 [REQUIRED] Remove the DESCRIPTION.bak file.
vignettes/BioTIP.Rmd.bak

 [REQUIRED] Remove the BioTIP.Rmd.bak file.

**Comment by dvantwisk** [comment]
The changes look good! I am going to move to accept the package now.
