### ISSUE TITLE
peakPantheR

### ISSUE THREAD

**Issue by adwolfer** [Bioconductor/Contributions#1223]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/phenomecentre/peakPantheR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission please see some initial comments below: 

**README**

- [ ] Please include Bioconductor installation instructions
- [ ] Do you need both the .md and .Rmd seems like one should be deleted

**DESCRIPTION**

- [ ] We don't recommend `lazyData: true`; we have rarely found it useful and can actually slow installation

**inst**

- [ ] Generally extra data files are included in an `inst/extdata` directory. 
- [ ] Could you please also include a `inst/scripts` that describes how the data included in the data directory was created including any source/reference information 

**vignette**

**getting-started**

- [ ] How did you determine the information for the input_targetFeatTable? 
- [ ] Since you mention data import is accomplished through mzR, I'm curious at why mxR data structures are not able to be used as input? Why must you use raw files? 

**parallel-annotation**

- [ ] So is input_spectraMetadata strictly required? This file as made in the vignette does't seem useful or informative?
- [ ] It seems like if you took the time to make classes for everything else, there should be a defined class for the output of peakPantheR_parallelAnnotation with accessor method for retrieving the
  annotations rather than annotation_result$annotation. Especially if this is the object that is used in downstream analysis.  
- [ ] While its in eval=FALSE, I tried the code in 3.3 for saving output but get
  the following ERROR

```
> outputAnnotationDiagnostic(updated_annotation, saveFolder='/output_folder/', 
+                             savePlots=TRUE, sampleColour=col_sType, 
+                             verbose=TRUE, ncores=2)
Annotation parameters saved at /output_folder//annotationParameters_summary.csv
Error in file(file, ifelse(append, "a", "w"), encoding = fileEncoding) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w"), encoding = fileEncoding) :
  cannot open file '/output_folder//annotationParameters_summary.csv': No such file or directory

```
It seems like the saveFolder has to already exist - perhaps having a prompt that
if the directory doesn't exist to create it for the user would be a good option? 
- [ ] When I run outputAnnotatinoDiagnostic in 3.5.1 a device stays open?
- [ ] It looks like a file at some point also got created without asking? `Rplots.pdf`


**R file in top directory**

- [ ] What is dev_peakPanther.R ?  This file should not be git tracked.


**R/man**

- [X] Very detailed man pages. Thank you!

**extractSignalRawData.R**
- [ ] Should there be a message when no reads are found or would a user
intuively know why? #line 126
- [ ] line #166 I don't think you need a paste0 with stop, it should work the
same as message, so the paste0 is unnecessary
- [ ] For extractSignalRawData_checkInput, what happens if one of the values is
missing? There are only checks if it is not?
- [ ] If mz or rt are numeric do the numbers/lengths have to match up? You only
check if mz and rt are matrix/data.frame but not if one is not?
- [ ] In the message #line 194 you say that the row will be duplicated but there
is no code to do that. So to verify are you relying on R default behavior of
recycling? 
- [ ] So it seems like you do more checks in extactSinglaRawData_init that
address some of the above but why not move these to the
extractSignalRawData_checkInput function and have all the checks together.  It
seems like it would make more sense to have all the input parameter checks together. 

**findTargetFeatures.R**
- [ ] findTargetFeatures_findRTMax and findTargeFeatures_findRTMin should be
combined to be one function to minimize the repeat of code. Besides the naming
of the variable the only difference in the function is line 419 vs 460 where the
delta is either subtracted or added based on if you are looking for max or
min. Which could easily be a conditional based on an argument for if looking for
max or min. 

 
Please respond to the above issues and when ready perform the version bump to kick off a new build and tag me to re-review.  We look forward to working with you to get your package accepted into Bioconductor.

**Comment by adwolfer** [comment]
Hi @lshep

Thank you for the detailed review. We will address the points you highlighted and update the package accordingly
Best

**Comment by Gscorreia89** [comment]
Hi @lshep 

We have worked to address the issues highlighted, and have just submitted a new build. I am attaching below the details for each individual issue. Thank you for your feedback and suggestions, and we look forward to the next iteration.

> **README**
> 
> * [x]  Please include Bioconductor installation instructions
> * [x]  Do you need both the .md and .Rmd seems like one should be deleted

The `.Rmd` has been removed as it is redundant

> 
> **DESCRIPTION**
> 
> * [x]  We don't recommend `lazyData: true`; we have rarely found it useful and can actually slow installation
> 
> **inst**
> 
> * [x]  Generally extra data files are included in an `inst/extdata` directory.
> * [x]  Could you please also include a `inst/scripts` that describes how the data included in the data directory was created including any source/reference information
> 
> **vignette**
> 
> **getting-started**
> 
> * [x]  How did you determine the information for the input_targetFeatTable?

The regions of interest (ROI) to provide for targeted integration depend on the chemical coverage of a given LC-MS assay for a specific type of sample, and therefore should be defined by the user based on previous knowledge of the data. 

> * [x]  Since you mention data import is accomplished through mzR, I'm curious at why mxR data structures are not able to be used as input? Why must you use raw files

`mzR` is employed indirectly through `MSnbase` as parser to read raw MS data from multiple open and vendor mass spectrometry format.
MSnbase has objects to represent and optimize mzR calls to obtain the raw data. 
However, once the table or raw signal is extracted, peakPantheR uses its own pre-processing/peak detection and curve fitting algorithms to obtain annotated peaks, quality control metrics and summarized data for plots. 
When processing data, peakPantheR only passes the raw file path to workers which then load the data file required, reducing memory consumption and enabling concurrent data access.

> 
> **parallel-annotation**
> 
> * [x]  So is input_spectraMetadata strictly required? This file as made in the vignette does't seem useful or informative?

This file is optional to run peakPantheR, but can still be helpful to store experimental metadata pertaining to each sample. For example, the plotting interface enables the user to plot subsets of the data with different colours based on sample metadata, and this functionality is supported by the data.frame passed on input_spectraMetadata.

> * [X]  It seems like if you took the time to make classes for everything else, there should be a defined class for the output of peakPantheR_parallelAnnotation with accessor method for retrieving the
>   annotations rather than annotation_result$annotation. Especially if this is the object that is used in downstream analysis.

True, the `peakPantheRAnnotation` in `annotation_result$annotation` is the object used upstream and in downstream analysis, as a fully described object which contains all information and if it contains results or not.

In `peakPantheR_parallelAnnotation()` we wish to return this `peakPantheRAnnotation` (updated with results) and a list of failures. It seemed the 'best' way to return both is to use a list. If we returned a novel object, the user would still need to extract the `peakPantheRAnnotation` (and discard the failure list) to do the subsequent analysis.

The $failures list return is there to catch and log any potentially serious error that a parallel worker might experience while reading each file, in order to make debugging parallel workflows easier. Examples of errors recorded in $failures would be attempting to read corrupted raw data files or the OS running out of physical memory. This return list does not cover any failure to detect or integrate signals, or anything which is part of the peakPantheR integration workflow. These are recorded directly inside the returned $annotation. Files for which a failure occurred are removed from the $annotation object, hence why we kept a separate $failures in the return to report these.

> * [X]  While its in eval=FALSE, I tried the code in 3.3 for saving output but get
>   the following ERROR
> 
> ```
> > outputAnnotationDiagnostic(updated_annotation, saveFolder='/output_folder/', 
> +                             savePlots=TRUE, sampleColour=col_sType, 
> +                             verbose=TRUE, ncores=2)
> Annotation parameters saved at /output_folder//annotationParameters_summary.csv
> Error in file(file, ifelse(append, "a", "w"), encoding = fileEncoding) : 
>   cannot open the connection
> In addition: Warning message:
> In file(file, ifelse(append, "a", "w"), encoding = fileEncoding) :
>   cannot open file '/output_folder//annotationParameters_summary.csv': No such file or directory
> ```
> 
> It seems like the saveFolder has to already exist - perhaps having a prompt that
> if the directory doesn't exist to create it for the user would be a good option?
 
`saveFolder` is recursively created in `outputAnnotationParamsCSV()`. 
However as we couldn't expect a path common to all users, we put a placeholder path as example (i.e. `/output_folder/`). 
On some machines or R version the default behaviour is to use the hard drive root directory, or the R working directory.
It seems that in this example the path couldn't be resolved (possibly due to permission). 
To make it safe for all users, the vignette has been modified and a temporary folder is first created with `tempdir()`

> * [X]  When I run outputAnnotatinoDiagnostic in 3.5.1 a device stays open?

It could possibly be left from parallel calls to `outputAnnotationDiagnostic_saveSingleMultiPlot()` (and ggsave) across workers.
We added a dev.off() after ggsave() to be sure the devices are closed as expected.

> * [X]  It looks like a file at some point also got created without asking? `Rplots.pdf`

`Rplots.pdf` seems to be created in the working directory when R is run non-interactively (in this case as part of the unittests)
by ggplot2 to determine plots and subplots dimensions. This behaviour seems to come and go with updates of ggplot (https://github.com/tidyverse/ggplot2/issues/2787, https://stackoverflow.com/questions/17348359/how-to-stop-r-from-creating-empty-rplots-pdf-file-when-using-ggsave-and-rscript)
 
> **R file in top directory**
> 
> * [x]  What is dev_peakPanther.R ?  This file should not be git tracked.

The file has been removed

> **R/man**
> 
> * [x]  Very detailed man pages. Thank you!
> 
> **extractSignalRawData.R**
> 
> * [x]  Should there be a message when no reads are found or would a user
>   intuively know why? #line 126 

This situation is non-pathological (it cannot be the users fault) and occurs when no scans are found within a given ROI, which is expected 
to happen frequently (for example, when a compound is not present in a sample or below the instrument's limits of detection). 
Also, some MS instrument vendors implement denoising algorithms, which makes their raw datasets inherently more sparse.
Additionally the function is not exported the user will not be directly faced with an empty result data table.
This empty data table is expected by the functions calling `extractSignalRawData()` which will let the user know that no signal was found in the window of interest.

> * [x]  line #166 I don't think you need a paste0 with stop, it should work the

the paste0 was unnecessary

> * [x]  For extractSignalRawData_checkInput, what happens if one of the values is
>   missing? There are only checks if it is not?

If `rt` and `mz` are not provided, the full retention time/mass range are extracted. This is done in `extractSignalRawData_init()` by setting `rt` and `mz` to `c(-Inf, Inf)`

> * [x]  If mz or rt are numeric do the numbers/lengths have to match up? You only
>   check if mz and rt are matrix/data.frame but not if one is not? 

`extractSignalRawData()` can extract one or multiple windows (defined by rt/mz) in a raw file. The windows in rt or mz dimension can be either defined by a numeric(2) (e.g. `rt = c(3290., 3410.)`) or as a row in a matrix/data.frame (first column the start of the window, second column the end of the window)

In the end, the inputs to `extractSignalRawData()` can be as follow:
- For one window, rt/mz can be a numeric(2), or matrix/data.frame of 1 row or both
- For N windows of different rt/mz, input can be matrix/data.frame with the N rows (one per window)
- For N windows sharing the same rt for example, rt can be a numeric or matrix/data.frame of 1 row, and mz a matrix/data.frame of N rows. In that case the rt value will be repeated N times in `extractSignalRawData_init()`

To enable that, we only need to check that we get the 2 numeric values for one window, or that the number of rows match. All these different cases are tested in `test_extractSignalRawData.R`

> * [X]  In the message #line 194 you say that the row will be duplicated but there
>   is no code to do that. So to verify are you relying on R default behavior of
>   recycling?

The duplication takes place in `extractSignalRawData_init()` line #217 and #219

> * [X]  So it seems like you do more checks in extactSinglaRawData_init that
>   address some of the above but why not move these to the
>   extractSignalRawData_checkInput function and have all the checks together.  It
>   seems like it would make more sense to have all the input parameter checks together.

True, we did split checkInput and Init to respect the 50 lines max function length. 
For clarity we moved `extractSignalRawData_checkInput()` inside `extractSignalRawData_init()` so the check and modifications take place together.

> 
> **findTargetFeatures.R**
> 
> * [X]  findTargetFeatures_findRTMax and findTargeFeatures_findRTMin should be
>   combined to be one function to minimize the repeat of code. Besides the naming
>   of the variable the only difference in the function is line 419 vs 460 where the
>   delta is either subtracted or added based on if you are looking for max or
>   min. Which could easily be a conditional based on an argument for if looking for
>   max or min.

The functions were split to respect the 50 lines max function length, they have now been grouped.

**Comment by lshep** [comment]
Thanks for the clarifications.  Two more minor points:

**doc**

- [ ] The files in `doc` should be generated automatically from your vignettes.
  Please remove this directory

**Vignettes**

**parallel_annotation**

- [ ] `Rplots.pdf` is still saved in my working. While this should be corrected
in ggplot2, please have a clean up for if it is generated on a users
system.  


Thank you!  When ready please kick off another build/version bump and comment back here.

**Comment by adwolfer** [comment]
Hi @lshep

I am attaching below the details for the issues you highlighted. Thanks again for your feedback and suggestions


> **doc**
> 
> * [X]  The files in `doc` should be generated automatically from your vignettes.
>   Please remove this directory

The `doc` folder has been removed and the documentation moved to an independent github.io page
 
> **Vignettes**
> 
> **parallel_annotation**
> 
> * [X]  `Rplots.pdf` is still saved in my working. While this should be corrected
>   in ggplot2, please have a clean up for if it is generated on a users
>   system.

Each unittest that calls ggplot2 and could generate it, now removes `Rplots.pdf` from the working environment

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adwolfer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("peakPantheR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/peakPantheR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
