### ISSUE TITLE
RNAsense

### ISSUE THREAD

**Issue by marcusrosenblatt** [Bioconductor/Contributions#1227]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/marcusrosenblatt/RNAsense

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before the review process begins, please update your package to interoperate with standard Bioconductor data representations, e.g., [SummarizedExperiment][1]. Please also update your vignette so that it is a narrative document that describes the steps and functionality of your package, rather than simply a script embedded in a markdown document.

Please post a comment here with me tagged @mtmorgan to indicate that you are ready to begin the review process

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by marcusrosenblatt** [comment]
@mtmorgan Hi Martin, thanks for your comments. I restructured the code that it is now using the SummarizedExperiement class. The vignette was updated as well and contains much more information. Could you please have a look on the package again?

**Comment by marcusrosenblatt** [comment]
@Kayla-Morrell Did not figure out how to link to S4vector::DataFrame within the documentation. Do you have an idea for that?

**Comment by Kayla-Morrell** [comment]
@marcusrosenblatt  I think it is something along the lines of `\code{\link[packagename]{functioname}}` if it's a function from another package.

**Comment by marcusrosenblatt** [comment]
@Kayla-Morrell Thanks.  I thought I had tested this before. But now it works! Great!

**Comment by Kayla-Morrell** [comment]
Hello @marcusrosenblatt - We had some issues with our Windows builder last week which is why you didn't see it on your last build report. Before I could start the initial review of your package I kicked off a new build so that I could get a Windows build/make sure it ran correctly on Windows. It seems there is an error with the package when running on Windows. Please address this error and then I'll be able to start the review process.

Thank you,
Kayla

**Comment by marcusrosenblatt** [comment]
@Kayla-Morrell - The link code{\link[S4vectors]{DataFrame}} seems to give a warning on Windows machines but works fine for Linux and Mac. I have no idea how to fix this. I do not have access to a Windows machine. Can you help? Or what can we do now?

**Comment by Kayla-Morrell** [comment]
@marcusrosenblatt - Did a little digging and have found a possible solution [here](https://stackoverflow.com/questions/48430093/how-do-i-resolve-rd-warning-missing-file-link-when-building-packages-in-rstudi). It seems to be due to DataFrame being an alias in S4Vectors. The actual name of the file is DataFrame-class. So my (hopefully last) suggestion to fix this would be to change the code to `\link[S4Vectors:DataFrame-class]{S4Vecotrs::DataFrame()}`. My apologizes for misleading you before, I had forgotten about the possibility for aliases. Hopefully this change will work for you.

Best,
Kayla

**Comment by mtmorgan** [comment]
Actually the best fix is to not specify the package; `\link{DataFrame}`. It's then resolved (correctly or via a user prompt if there is some ambiguity amongst loaded packages) at run time.

**Comment by marcusrosenblatt** [comment]
I tried \link{DataFrame} in previous pushes, but this always resulted in an error.

**Comment by mtmorgan** [comment]
can you point to the build report showing the error?

**Comment by marcusrosenblatt** [comment]
@mtmorgan - it was the commit acadda9 (https://github.com/Bioconductor/Contributions/issues/1227#issuecomment-533163141)

The output in the build report was as follows:

* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'getFC.Rd':
  DataFrame

**Comment by marcusrosenblatt** [comment]
So it in fact was not an error, but a warning...

**Comment by mtmorgan** [comment]
Sorry, I guess I gave bad advice. It seems from looking a the code that `\link{DataFrame}` would only work if the package in which the documentation occurred were in the Depends: field of the DESCRIPTION file.

**Comment by marcusrosenblatt** [comment]
No worries. I mean I could add S4vectors to the Description file, if you would prefer that. I don't know what would be the most consistent.

**Comment by mtmorgan** [comment]
No, please don't add S4Vectors to the DESCRIPTION file.

**Comment by Kayla-Morrell** [comment]
Hello @marcusrosenblatt, 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to 'false', when 'true' it can slow 
down the loading of packages.

- [ ] SUGGESTION: We encourage including the 'BugReports:' field with a 
relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: Is there a reason why none of the functions in your package 
are being exported?

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package. If there happens to be many functions being used from a package 
then that is okay, but please limit this if possible.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in _Bioconductor_ release announcements.

## Data

- [ ] REQUIRED: The data in the vignette folder does not belong there. The data 
should be included in a 'data/' directory and made available in the R session 
through the use of `data()`. There needs to be documentation for this data as 
well.

## Vignette

- [ ] REQUIRED: There seems to be a hidden file in 'vignettes/' called '.Rmd'. 
This file should be removed.

- [ ] SUGGESTION: We strongly encourage table of contents.

- [ ] REQUIRED: In order for your headers to render correctly there needs to be 
a space between the '#'s and the header title. For example, for 'Introduction' 
it should be `###` `Introduction`. Then you will have a header title instead of 
'###Introduction'.

- [ ] REQUIRED: After the 'Introduction' section there should be an 
'Installation' section that demonstrates to the users how to download and load 
the package from _Bioconductor_. The code to download should look something 
like the following and include `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("RNAsense")
```

- [ ] REQUIRED: It is pointless to load in packages (line 16-21) since the user 
cannot see this code. Also, since these packages are listed under 'Import' in 
the DESCRIPTION file they will be loaded when the user installs your package.
You should show and evaluate `library(RNAsense)` after showing how to install the package 
(the requirement above).

- [ ] REQUIRED: In order for the code on line 43 to run properly, you need to 
include `library(SummarizedExperiment)`. Without this library being loaded R 
doesn't recognize `assays()`.

- [ ] SUGGESTION: For line 43, I would see if you could split this code onto 
multiple lines since it continues outside the code box when the vignette is 
rendered. The same goes for lines 49, 54, and 59. 

- [ ] REQUIRED: You should not be using internal functions (with the use of 
`:::`) in the vignette. If these are the functions the user is to be using they 
need to be exported, which was mentioned in the NAMESPACE requirement.

- [ ] SUGGESTION: I would consider changing the global setting you have for 
figure width and figure height. Those dimensions seem to work of the first 
`ggplot` but then when doing the heatmap from `plotSSGS` things look really 
crammed. You can set figure width and height in the options for the R code 
chunks. For example, you could set `{r plot, message = FALSE, eval = TRUE, 
fig.height = 10, fig.width = 15}` just for the `plotSSGS` code (I chose 
arbitrary numbers here, you should try yourself for the best dimensions).

- [ ] REQUIRED: Line 72, this text says that the information is output into a 
csv file, but all that I found in my working directory were a few txt files. 
This should be fixed. You might also include some information about the files 
that are created/saved like how many, their names, and the information within 
each one.

- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: Once all of these functions are exported, you will need to 
provide working examples to demonstrate the use of each of the functions. This 
is for a quick reference of use without having to look in the vignette.

- [ ] REQUIRED: When the data is put in the correct location there should also 
be a proper man page that documents the data used in the vignette.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See 
here, http://bioconductor.org/developers/how-to/unitTesting-guidelines/, for 
some help with unit tests.

## R code

- [ ] REQUIRED: The following lines of code should be added to the R code 
documentation (which in turn will add the importing to the NAMESPACE file):
                - importFrom("stats", "fisher.test", "pchisq", "time", "var")
                - importFrom("utils", "write.table")

- [ ] SUGGESTION: Consider clarifying how 36 object(s) are initialized. The 
following list shows the function with the objects listed in paratheses. 
        combineResults(resultSwitch, resultFC, name, FCdetect, nrcores)
        getFC(mydata, analyzeConditions, times)
        getSwitch(mydata, times, time, var, pchisq)
        outputGeneTables(resultCombined, times, analyzeConditions, timepoint,
        FCdown, FCup, write.table, experiment)
        plotSSGS(resultCombined, times, analyzeConditions, result, timepoint,
        FCdown, FCup, fisher.test, experiment, xaxis, time, cluster)

- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
RNAsense.R, lines 23, 26, and 107.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 125 
lines (25%) that are > 80 characters long.

- [ ] SUGGESTION: Since 'mydata' needs to be a SummarizedExperiment object for 
`getSwitch` and `getFC` I would add testing before going into the code to be 
sure the object that was passed in is in fact a SummarizedExperiment object. A 
simple `stopifnot()` test could work out for this.

- [ ] REQUIRED: For `outputGeneTable()` you state that it is in .csv format but 
your code creates only .txt. Either fix the code make csv files or change the 
documentation to txt not csv. Which ever you chose just be sure everything is 
uniform between code and documentation.

- [ ] SUGGESTION: For `outputGeneTable()` would it be possible for there to be 
an added argument to the function so the user could pick a location where they 
want the files written to? The default could be the working directory incase the 
user forgets to set the location, but I think it would be nice option for the 
user to decide where the files go.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
Hello @marcusrosenblatt - 

Just checking in to see if there are any updates on the initial review for this package? Please keep in mind that if you would like this package to be included in the upcoming 3.10 release the review process must be finished and the package accepted by October 23rd.

Best,
Kayla

**Comment by marcusrosenblatt** [comment]
Hello @Kayla-Morrell 
first of all, thanks for your review of the package. I did not manage to be in time for the current bioconductor release. But that's ok.
I incorporated all requirements and a lot of the suggestions and uploaded a new version of the package. One single warning is remaining which corresponds to what we had before. We decided to leave it like it is.
Looking forward to hearing from you!
Marcus

**Comment by marcusrosenblatt** [comment]
Hi @Kayla-Morrell 
thanks for your quick reply. I did the first two requirements and will upload them now. Regarding the MZsox data set. Up to now, this data is unpublished. We are planning to submit it soon. This is why I did not provide anything. What is the best to do in such cases?

**Comment by Kayla-Morrell** [comment]
@marcusrosenblatt - About the MZsox data, that's fine but just be sure to add the information when the data is published. I'm more than happy to accept the package now.

Thanks,
Kayla
