### ISSUE TITLE
BiocSet

### ISSUE THREAD

**Issue by Kayla-Morrell** [Bioconductor/Contributions#1229]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Kayla-Morrell/BiocSet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 
I'm getting this error when running `R CMD check` : 
```r
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  > 
  > test_check("BiocSet")
  ── 1. Failure: 'kegg_sets()' works (@test_mapping_set.R#58)  ───────────────────
  dim(es_element(es))[1] is not strictly more than c(3201L). Difference: 0
  
  ── 2. Failure: 'kegg_sets()' works (@test_mapping_set.R#61)  ───────────────────
  dim(es_elementset(es))[1] is not strictly more than c(5345L). Difference: -2
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 473 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 2 ]
  1. Failure: 'kegg_sets()' works (@test_mapping_set.R#58) 
  2. Failure: 'kegg_sets()' works (@test_mapping_set.R#61) 
  
  Error: testthat unit tests failed
  Execution halted

```
Could it be a database issue? 

Thanks

**Comment by Kayla-Morrell** [comment]
Hey @LiNk-NY,

I'm not sure if it's a database issue or not. I used to test for exact dimensions but these tests kept failing which is why I resorted to the strictly more than approach. Let me see if I can improve these tests so you don't get the error.

Thanks for catching this!

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 

Thank you for your submission! :)
Please see your review below. 
If you have any questions, feel free to post them here. 

Thanks!
-Marcel 

---

# BiocSet #1229

* Code is nicely written and neat.
* Generally, there is a mix between S4 and S3 methods and it's not immediately
clear why use one over the other.

## DESCRIPTION

* It looks good

## NAMESPACE

* It looks like functions, such as `*_from_elementset`, should
be coercion functions or be part of the constructor function?
* Should the verbs like `mutate`, `select`, etc. be methods?

## vignettes

* It wasn't clear what the difference between `union` and `union_single` is.
Could these be the same function with dispatch on either two or one `BiocSet`
objects? (Also applies to `intersect*`)
* Should the `file_cache` chunk be an internal / convenience function? It
seems too manual..
* When I try to run `union(es1, es2)` again after running the `airway` and
`go_sets` chunks, I get an error:

```
> union(es1, es2)
Error in as.vector(x) : no method for coercing this S4 class to a vector
```
It may be due to loading the other packages but when entering `union.BiocSet`
I also get an error.


## R

* Is the `GMTFile` class necessary? It may be simpler to use a GMT file path
string unless you have several methods for the GMTFile class.
* Provide a coercion method from `GeneSetCollection` or `getGmt` to `BiocSet`
(if not present already).
* How closely do you want the functions to match `dplyr`? If quite close,
`filter_element` would have to operate based on (potentially) three subclasses
and be called `filter`.
* `update_es_element` and friends seems a little circular, it may just be
better to use `es_element<-` from the get-go
* Do you want to export the replace methods? If so, consider using
`setReplaceMethod`
* Export the coercion method `setAs` as well.
* It feels like the `*_elementset` / `*_set` definitions should not get in the
way of the tidy verbs. `filter(...)` and other methods should just work without
the extra suffix.
* Perhaps you want to reorganize the class definition when doing `activate`?
This will allow you to use `filter_*` based on the first class in line.

Minor:
* Use `character()` as argument defaults to avoid checking for `missing` in
`BiocSet_from_elementset`

**Comment by Kayla-Morrell** [comment]
Hey @LiNk-NY - Thank you for the thorough review. Below are my responses to the points you made. Please let me know if there is anything additional that needs to be changed or clarified.

> ## NAMESPACE
> * It looks like functions, such as `*_from_elementset`, should
>   be coercion functions or be part of the constructor function?

We don't have control over the constructor functions. We could have done
`as_tibble.BiocSet` but we didn't want to support the other arguments.

> * Should the verbs like `mutate`, `select`, etc. be methods?

These are S3 methods to extend these generic functions to the BiocSet class.
What would your suggestion be otherwise?
> 
> ## vignettes
> * It wasn't clear what the difference between `union` and `union_single` is.
>   Could these be the same function with dispatch on either two or one `BiocSet`
>   objects? (Also applies to `intersect*`)

We had initially implemented what you suggested, the same function with
dispatch on either two or one `BiocSet` objects. But this proved to be quite
difficult when dealing with a single `BiocSet` object because `base::union` and
`dplyr::union` require 2 arguments. So we decided to create two seperate
functions as a work around.
> * Should the `file_cache` chunk be an internal / convenience function? It
>   seems too manual..

This section was just to demonstrate the use of `file_cache` if the user is
having difficulty downloading large data files. As far as it being too manual
this is more so on `BiocFileCache` because of how you must write the code to
utilize it.
> * When I try to run `union(es1, es2)` again after running the `airway` and
>   `go_sets` chunks, I get an error:
> 
> ```
> > union(es1, es2)
> Error in as.vector(x) : no method for coercing this S4 class to a vector
> ```
> 
> It may be due to loading the other packages but when entering `union.BiocSet`
> I also get an error.

I believe it has something to do with the `airway` package being loaded (seems
that the `BiocSet::union` is masked with the package load). Since we export the 
`dplyr` generic of `union`, you would have to do `dplyr::union()` which I had to 
change in my examples for union and intersect since the same thing happens 
when loading the package `org.Hs.eg.db` thanks to `BiocGenerics`. Could be a 
fix in a later version.
> 
> ## R
> * Is the `GMTFile` class necessary? It may be simpler to use a GMT file path
>   string unless you have several methods for the GMTFile class.

It's needed internally in our package.
> * Provide a coercion method from `GeneSetCollection` or `getGmt` to `BiocSet`
>   (if not present already).

Coercion method was created in the `import-class.R` file.
> * How closely do you want the functions to match `dplyr`? If quite close,
>   `filter_element` would have to operate based on (potentially) three subclasses
>   and be called `filter`.

We feel that this is fine as is. An example might help for explaining this. If
the user just wants to use `filter`, it will work:

```{r}
es <- BiocSet(set1 = letters, set2 = LETTERS)
es %>% filter(set = "set1")
```

but this will default to the `elementset` tibble. If the user wanted to filter
on the `set` tibble then they would have to use `es_activate`:

```{r}
es <- BiocSet(set1 = letters, set2 = LETTERS)
es %>% es_activate(set) %>% filter(set = "set1")
```

which we felt was quite a mouth full, so that is why we simplified to just
`filter_*`:

```{r}
es <- BiocSet(set1 = letters, set2 = LETTERS)
es %>% filter_set(set = "set")
```
> * `update_es_element` and friends seems a little circular, it may just be
>   better to use `es_element<-` from the get-go

This is to keep in line with the `dplyr` way versus the old way of doing things.
> * Do you want to export the replace methods? If so, consider using
>   `setReplaceMethod`

We don't want to export the replace methods, might end up being confusing to the
user.
> * Export the coercion method `setAs` as well.

This is now exported.
> * It feels like the `*_elementset` / `*_set` definitions should not get in the
>   way of the tidy verbs. `filter(...)` and other methods should just work without
>   the extra suffix.

I explained this point above with an example.
> * Perhaps you want to reorganize the class definition when doing `activate`?
>   This will allow you to use `filter_*` based on the first class in line.

Not sure what you mean by this exactly.
> 
> Minor:
> 
> * Use `character()` as argument defaults to avoid checking for `missing` in
>   `BiocSet_from_elementset`

We are going to leave this as is for now.

Thanks,
Kayla

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 
Thanks for responding to the points in the review and the elucidating example. 

>> * Perhaps you want to reorganize the class definition when doing activate?
This will allow you to use filter_* based on the first class in line.
>
> Not sure what you mean by this exactly.

It was related to my point above it. When you `activate`, you may be able to reorder the class string `class(x) <- c("B", "C", "A")` so that the the method for `filter.B` works on the object first rather than other methods. I would allow you to avoid doing `filter_set`. You may even be able to do an `on.exit` call to return the order to the original in `activate`. 
I was thinking in terms of multiple S3 classes and sub-classes. After looking more closely, I see
that you're changing an indicator slot that gives the active component. It would be interesting to explore the possibility of having three sub-classes for a main class and dispatching on those, perhaps in a future version. 

Your package has been accepted. Thanks. 

Best, 
Marcel

**Comment by Kayla-Morrell** [comment]
@LiNk-NY, thank you for clarifying and we will definitely keep that in mind for future versions. Thank you also for reviewing and accepting the package!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Kayla-Morrell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocSet")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocSet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
