### ISSUE TITLE
Submission package: PERFect

### ISSUE THREAD

**Issue by cxquy91** [Bioconductor/Contributions#1243]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cxquy91/PERFect

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by cxquy91** [comment]
Hi, 

I have fixed the issue from the build report and update the github repository. 

Thank you, 

Quy

**Comment by lshep** [comment]
Please set up the webhook as described [here](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) . Once that is set up perform a version bump in the DESCRIPTION and it will trigger a new build report.

**Comment by cxquy91** [comment]
Hi Ishep, I couldn't find the "Settings" menu on the landing page of https://github.com/katiasmirn/PERFect (eventhough we are both contributors to the package) so I forked it, updated the repository link to https://github.com/cxquy91/PERFect, added the webhook and bumped the version.

**Comment by cxquy91** [comment]
I just update to another version and it seems that the bot is building.

**Comment by cxquy91** [comment]
The most recent error came from the .Rproj file, so I think the bot is complaining about my Git/SVN url (it was https://github.com/katiasmirn/PERFect, but I just changed into https://github.com/cxquy91/PERFect). I just bump to another version. Let's see what the bot says.

**Comment by cxquy91** [comment]
The bot still doesn't like how I update my PERFect.Rproj. Please let me know how should I do this correctly. This is what I have done:

Follow instruction from https://git.wiki.kernel.org/index.php/GitSvnSwitch to change Git/Svn for my package, using the General Case guidelines. (doesn't seem to work). This is what I got that makes me think it doesn't work:

$ git svn fetch
Migrating from a git-svn v1 layout...
Data from a previous version of git-svn exists, but
        .git/svn
        (required for this version (2.23.0.windows.1) of git-svn) does not exist.
Done migrating from a git-svn v1 layout
[svn-remote "svn"] unknown

And this is my updated .git/config:

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/cxquy91/PERFect
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[gui]
	wmstate = normal
	geometry = 893x435+234+234 175 196

**Comment by lshep** [comment]
That ERROR i indicating that the .Rproj file should not be git tracker.  In order to remove the file you need to do the following  `git rm PERFect.Rproj`   You can keep this file for yourself but do not commit it to git (this can be done with a .gitignore file).   After you do the git rm,  do a version bump, git commit the changes and the ERROR should be corrected.

**Comment by cxquy91** [comment]
Should I be worry about this TIMEOUT? It looks like Linux system struggles to build it while other two are fine. Also, should I remove inst/doc folder?

**Comment by Kayla-Morrell** [comment]
This is most likely an issue on our end so I wouldn't worry about the TIMEOUT for now. Yes, please remove the inst/doc folder.

**Comment by cxquy91** [comment]
finally :D

**Comment by Kayla-Morrell** [comment]
Hello @cxquy91,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The build/ directory does not seem necessary and should be 
removed.

## DESCRIPTION

- [ ] REQUIRED: The 'Packaged:' tag is not needed and should be removed.

- [ ] REQUIRED: There are functions used in your code from 'parallel' and it is
 not listed in the 'Imports:' field. Please add it.

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file, this very helpful when 
tracking changes in the code from one version to the next. However, it does not
 look like your file is formatted correctly. Please see the following link 
on how to properly format your NEWS file: 
https://bioconductor.org/developers/package-guidelines/#news.

## Data

- [ ] CLARIFICATION: I see the use of the data files 'mock' and 'mock2' within 
the vignette and the man pages. Where are the other data files used?

## Vignettes

- [ ] REQUIRED: Lines 27-36, most of this code needs to be shown to the user 
and should be incorporated into the workflow code. The libraries should be 
loaded where needed and the user needs to know what to set the seed to in order
 to produce the same results as you did.

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how 
to download and install the package from _Bioconductor_. The code should look 
something like the following and include 'eval=FALSE':

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("PERFect")
```

- [ ] SUGGESTION: In the 'Introduction' section you might explain what a taxa is
 since the user maybe unfamiliar with this type of data.

- [ ] REQUIRED: Lines 290-300, something doesn't seem right in here. When I 
generate the vignette on my computer the math doesn't seem to line up properly 
and there are two trailing 'end's that don't seem to belong here. Just make sure
 all of the code is correct.

- [ ] REQUIRED: Line 416-428, the same goes for this chunk of code as well. When
 I generate the vignette the math doesn't line up properly and there is a 
trailing 'end' that doesn't seem to belong at the end of the paragraph. Double 
check that the code is correct.

- [ ] REQUIRED: Line 467-474, same as above with one trailing 'end'.

- [ ] REQUIRED: The last section of the vignette should be "Session Information"
 and should include `sessionInfo()`.

- [ ] SUGGESTION: You give a very thorough illustation and explanation of the 
method and a very little section about the actual use of the package. Keep in 
mind the purpose behind a vignette, to demonstrate how to accomplish non-trivial
 tasks embodying the core functionality of the package. My suggestion would be 
to shorten the explanation of the method a bit and include a little bit more of
 the functionality of the package. 

## man pages

*PERFect_perm*

- [ ] SUGGESTION: The last part of your example could be contained in within 
`\dontrun{}` so that the user won't have to uncomment out the code. The code 
will show regularly withing a don't run section and it will not be run when 
testing example code.

*PERFect_perm_reorder*

- [ ] SUGGESTION: The same suggestion can be applied to the end of the examples
 in this man page as well.

*knight*

- [ ] REQUIRED: This data file is incomplete.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] REQUIRED: Avoid sapply(); use vapply() instead. Found in files:
        - utility_functions.R, line 25
        - utility_functions.R, line 27

- [ ] REQUIRED: Please use various apply functions (eg. vapply() or lapply()) 
instead of for loops. For example, this seems like it might be possible when you
 are populating `pvals` in PERFect_perm.R.

- [ ] SUGGESTION: Consider shorter lines, 517 lines are > 80 characters long.

- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents, 889 lines are
 not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@cxquy91 Just wanted to check in since I saw this issue was closed. Is there a reason you closed the issue?

**Comment by cxquy91** [comment]
Oh no, I didn't notice that I close it. I was reviewing the your suggestions and I might accidentally his the close button. I am almost finished with the revision and will update package. Thank you for noticing that.

**Comment by Kayla-Morrell** [comment]
Hello @cxquy91,

Just checking in to see if there are any updates on the initial review for this package? Please keep in mind that if you would like this package to be included in the upcoming 3.10 release the review process must be finished and the package accepted by October 23rd. 

Best,
Kayla

**Comment by cxquy91** [comment]
Dear Kayla,

Thank you for the reminder. I was a little busy recently but I will try to push this package out in the next few days.

**Comment by Kayla-Morrell** [comment]
@cxquy91 - Is the package ready for re-review now or are you planning on making more changes?

**Comment by cxquy91** [comment]
Hi Kayla,

I will have another push by tonight it will be for review. Thank you,

**Comment by cxquy91** [comment]
General package development
•	  REQUIRED: The build/ directory does not seem necessary and should be
removed.
It is removed.
DESCRIPTION
•	  REQUIRED: The 'Packaged:' tag is not needed and should be removed.
 	It is removed.
•	  REQUIRED: There are functions used in your code from 'parallel' and it is
not listed in the 'Imports:' field. Please add it.
“parallel” is added.
NEWS
•	  REQUIRED: Thank you for including a NEWS file, this very helpful when
tracking changes in the code from one version to the next. However, it does not
look like your file is formatted correctly. Please see the following link
on how to properly format your NEWS file:
https://bioconductor.org/developers/package-guidelines/#news.
I have reformatted to the way it should be.
Data
•	  CLARIFICATION: I see the use of the data files 'mock' and 'mock2' within
the vignette and the man pages. Where are the other data files used?
Other data are used for other demonstrations, but those vignettes must be cleaned up and updated before added in. Therefore, I temporary removed them for now and added them in once their vignettes are completed.
Vignettes
•	  REQUIRED: Lines 27-36, most of this code needs to be shown to the user
and should be incorporated into the workflow code. The libraries should be
loaded where needed and the user needs to know what to set the seed to in order
to produce the same results as you did.
I have shown them in the vignette.
•	  REQUIRED: The 'Installation' section should demonstrate to the user how
to download and install the package from Bioconductor. The code should look
something like the following and include 'eval=FALSE':
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("PERFect")
This is also added. 
•	  SUGGESTION: In the 'Introduction' section you might explain what a taxa is
since the user maybe unfamiliar with this type of data.
I added a brief discussion about taxa and filtering.
•	  REQUIRED: Lines 290-300, something doesn't seem right in here. When I
generate the vignette on my computer the math doesn't seem to line up properly
and there are two trailing 'end's that don't seem to belong here. Just make sure
all of the code is correct.
This supposes to mimic the for loop, but I can see that it is confused so I removed them and reformat the loop.
•	  REQUIRED: Line 416-428, the same goes for this chunk of code as well. When
I generate the vignette the math doesn't line up properly and there is a
trailing 'end' that doesn't seem to belong at the end of the paragraph. Double
check that the code is correct.
Same as above.
•	  REQUIRED: Line 467-474, same as above with one trailing 'end'.
Same as above
•	  REQUIRED: The last section of the vignette should be "Session Information"
and should include sessionInfo().
SessionInfo() is added.

•	  SUGGESTION: You give a very thorough illustation and explanation of the
method and a very little section about the actual use of the package. Keep in
mind the purpose behind a vignette, to demonstrate how to accomplish non-trivial
tasks embodying the core functionality of the package. My suggestion would be
to shorten the explanation of the method a bit and include a little bit more of
the functionality of the package.
I have added extra examples for user to better manipulate both functions.
man pages
PERFect_perm
•	  SUGGESTION: The last part of your example could be contained in within
\dontrun{} so that the user won't have to uncomment out the code. The code
will show regularly withing a don't run section and it will not be run when
testing example code.
Thank you for this suggestion. It is very helpful and I have implemented it.
PERFect_perm_reorder
•	  SUGGESTION: The same suggestion can be applied to the end of the examples
in this man page as well.
Same as above.
knight
•	  REQUIRED: This data file is incomplete.
This is removed.
Unit tests
•	  SUGGESTION: Consider adding unit tests. We strongly encourage them.
I have different files that test my functions so this is not necessary. 
R code
•	  REQUIRED: Avoid sapply(); use vapply() instead. Found in files:
- utility_functions.R, line 25
- utility_functions.R, line 27
I have fixed them so we don’t have sapply() anymore.
•	  REQUIRED: Please use various apply functions (eg. vapply() or lapply())
instead of for loops. For example, this seems like it might be possible when you
are populating pvals in PERFect_perm.R.

This is where I spent most of the time tinkering. I have changed all the loops wherever applicable, but there are some instances I have to use loops. It is either because the index of the loop is coded as part of the function, such as the functions DiffFiltLoss_j, Perm_j_s in the utility_functions.R, or I am running a binary search, so I don’t want to execute my loops for all taxa in order to be more computationally efficient. Since apply functions would essentially execute for all taxa, it would not be applicable. 

•	  SUGGESTION: Consider shorter lines, 517 lines are > 80 characters long.
I hope it is not a big deal if I kept them unchanged. 
•	  SUGGESTION: Consider multiples of 4 spaces for line indents, 889 lines are
not.
I hope it is not a big deal if I kept them unchanged.

**Comment by Kayla-Morrell** [comment]
Hello @cxquy91 - Thank you for making the necessary changes and clarifying where needed. I have just one additional note before accepting the package. Please see this requirement below.

## Vignette

- [ ] REQUIRED: Thank you for including the session info like I asked, however the placement is a little off. You have it inserted between a plot and the explanation of the plot. Please move it to right before the References and be sure there is a 'Session Info' header to indicate it's own section.

Best,
Kayla

**Comment by cxquy91** [comment]
Hi Kayla,

Thank you for spotting that. I just quickly fixed the issue and push the updated package. 

Quy

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cxquy91.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PERFect")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PERFect

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
