### ISSUE TITLE
cliqueMS

### ISSUE THREAD

**Issue by osenan** [Bioconductor/Contributions#1244]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/osenan/cliqueMS

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please revise your package to respond to the following comments, posting a brief summary fo your changes when ready for final review.

DESCRIPTION

- good

NEWS.md

- is this file formatted so that it is parsed by `utils::news()`, e.g., as created by `usethis::use_news_md()`?

vignettes

- looks really good

R

- Please use S4 classes and methods for more robust data structures and interoperabilty with _Bioconductor_ infrastructure. This is not as big an ask as it might sound; define a class, constructor, accessors, and `show` method, as well as replacing S3 with S4 methods. Use the accessors throughout your own code, so that direct slot access is only present in the accessors.

```
.AnClique <- setClass(
    'AnClique",
    slots = c(
        peaklist = "data.frame",
        network = ...
    )

AnClique <-
    function(peaklist = data.frame(), ...)
{
    ...
    .AnClique(peaklist = peaklist, ...)
}

setGeneric("peaklist", function(x) standardGeneric("peaklist"))

setMethod("peaklist", "AnClique", function(x) slot(x, "peaklist"))

...

setMethod(
    "show", "AnClique",
    function(x)
{
    ...
})

...
```

- e.g., allClasses.R:160 Use `message()` rather than `cat()` to provide diagnostic information

- please use more standard formating (e.g., using formatR or the guidelines at http://bioconductor.org/developers/how-to/coding-style/). E.g., in buildNetwork.R:34 the use of `} else { ...` makes it very difficult to parse the limits of the `if` and `else` blocks

```
    if( sum(repeated.peaks) == 0 ) {
        nodes.delete = NULL
    } else {
        filtered.edges <- edges0.99[repeated.peaks,]
        if(sum(repeated.peaks) == 1) {
            ## only one peak filtered
            nodes.delete <- min(filtered.edges)
        } else {
            nodes.delete <- vapply(
                seq_len(nrow(filtered.edges)),
                function(x) { 
                    min(filtered.edges[x,])
                }, 
                numeric(1)
            )
        }
    }
```

- look carefully at your code for opportunities to vectorize (replace many R-level function calls with one function call. E.g., in the above code chunk the use of `vapply()`, which calls `min()` and `[` `nrow(filtered.edges)` times, can be replaced with `matrixStats::rowMins(nodes.deleted)`. 

- use `message()` rather than `cat()` to communicate diagnostic messages to the user, e.g., buildNetwork.R:290

- it is usually sufficient to use `warning(...)` rather than `warning(paste(...))`, e.g., findIsotopes.R:235

man 

- ok

**Comment by osenan** [comment]
Dear @mtmorgan,

Thank you very much for the comments. When all the corrections are made I will post a summary with the changes along with the new version.

Kind regards,
Oriol

**Comment by osenan** [comment]
Dear @mtmorgan  ,

Here is a summary of the changes

- DESCRIPTION: New webpage, added a collate field, added a package to Imports.

- NEWS: The file could not be parsed by `utils::news()`. I changed and now it is.

- R Code:

     - I changed the main class of the package `anClique` from S3 to a S4 class. This means:

      1. New class, methods and functions with slots, accessors and setters.
      2. Changes in all the other functions to adapt to the new S4 class.
      3. Changes in the documentation, with new entries for the accessors and the setters and the own class.
      4. Changes in the vignette.

     - I changed all `cat` for `message`, and I removed paste from the `warnings`.
 
     - I reviewed the coding style so space indenting, `if` and `else` enclosures are clearer, and the code looks cleaner in general.

     - I tried to vectorize the loops in the places were I was using to much basic function calls. Many of them remained unchanged because they are too complex to be synthesized in one line.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/osenan.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cliqueMS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cliqueMS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
@osenan unfortunately, when trying to add your package to the Bioconductor git repository the large *tgz files in the MacOS directory are flagged as too large. These need to be removed from the master branch of your repository before your package can be added to Bioconductor. To do this you might

0. Make a copy of your repository

1. Make a commit that removes the files

    git rm MacOS/*tgz
    git commit -am "remove large .tgz files"
    git push

2. Clean the repository following the instructions at https://rtyley.github.io/bfg-repo-cleaner/ using a maximum file size of 4.99M and push the results to github.

Please let me know when repository has been cleaned in this way. Once added to Bioconductor, your github repository can be managed in whatever way you like (though you will normally need to keep it in sync with the Bioconductor repository, and adding the large files back to the master branch would re-introduce problems).

**Comment by osenan** [comment]
Dear @mtmorgan ,
Those files *tgz files were necessary as the CRAN repository was not building the version for MacOS because the server did not have all the dependencies. Now they are not necessary anymore, I followed the instructions and commited the changes.

I also updated the DESCRIPTION and removed another doc file that only was needed for CRAN.

**Comment by mtmorgan** [comment]
thanks, but I think the files are still there?

**Comment by osenan** [comment]
Yes they were, I did not commit the local changes correctly. Now they are definitely not. Sorry for the inconvenience.
