### ISSUE TITLE
Update of DMRcatedata and DMRcate

### ISSUE THREAD

**Issue by timpeters82** [Bioconductor/Contributions#1247]
Hi Nitesh and Lori,
Further to the bioc-devel issue on 22/8, at Nitesh's suggestions I have made DMRcatedata into an ExperimentHub package - see link below. This is to accompany the new version of DMRcate, whose git has also been updated.

Repository: https://github.com/timpeters82/DMRcatedata

DMRcate_2.0.0 should pass R CMD check and R CMD BiocCheck, but I am unsure about DMRcatedata_2.0.0 because it needs to be incorporated into ExperimentHub first.

Many thanks,
Tim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

**Comment by lshep** [comment]
Yes @Kayla-Morrell   please ignore the current ERROR for version number and that it exists but otherwise proceed as normal for reviewing a package.  thanks

**Comment by lshep** [comment]
Again I wanted to check about uploading the data so I can put the files into the experimenthub - Please email me for credentials if you plan on using Bioconductor S3 buckets else if you have a public available serve that you will be hosting on that is okay too but we will have to adjust your metadata.csv in particular the RDataPath in order for me to get the data into the experiment hub.

**Comment by timpeters82** [comment]
Hi @lshep ,
Sorry, I missed your original question from 6 days ago. I've hosted the Rda file with the 9 objects here: https://github.com/timpeters82/DMRcatedata_Rda. Please feel free to adjust the metadata file as you see fit. 
Thanks,
Tim

**Comment by lshep** [comment]
We don't support data really being on github.  Putting the data on S3 would be much better.  I also was concerned as it appears you have several data objects saved under one rda -  It would be better if each object was saved to its own file.   If you prefer we can correspond through email (lori.shepherd@roswellpark.org)

**Comment by lshep** [comment]
Hello, 

A few minor comments and changes to make.  Also please let me know when you have uploaded the data to S3 as I will then add the data to the hub. 

**DESCRIPTION**

- [ ] If you want the version to be 2.0.0 please make the version 1.99.0 (The
  same with the package DMRcate - it should be 1.99.0 so that at release time it
  switches to 2.0.0 to indicate new version)
- [ ] Add biocViews term ExperimentHub

**Metadata file**

- [ ] The BiocVersion should be "3.10" as this is the version of bioconductor
  that the data will be available _through the hubs_
- [ ] Please remove empty columns Location_Prefix, Tags, Notes
- [ ] Please update the RDataPath. Since you are using the Bioconductor S3 these
  data files should be in a directory the same name as the package so for
  example `crosshyb.Rda` would actually be `DMRcatedata/crosshyb.Rda`. 

Thanks for making these changes!

**Comment by lshep** [comment]
The data has been added to the hub -  
```
> eh = ExperimentHub()
snapshotDate(): 2019-09-25
> query(eh, "DMRcate")
ExperimentHub with 9 records
# snapshotDate(): 2019-09-25 
# $dataprovider: Ensembl, Bioconductor, SickKids, Springer, Springer
# $species: Homo sapiens, Mus musculus
# $rdataclass: GRanges, GeneRegionTrack, character, data.frame
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3129"]]' 

           title          
  EH3129 | crosshyb       
  EH3130 | snpsall        
  EH3131 | XY.probes      
  EH3132 | hg19.generanges
  EH3133 | hg19.grt       
  EH3134 | hg38.generanges
  EH3135 | hg38.grt       
  EH3136 | mm10.generanges
  EH3137 | mm10.grt       
> temp = query(eh, "DMRcate")[[1]]
see ?DMRcatedata and browseVignettes('DMRcatedata') for documentation
downloading 0 resources
loading from cache
> head(temp)
[1] "cg00001510" "cg00002590" "cg00003969" "cg00004121" "cg00004192"
[6] "cg00004209"
```
Please test and make sure everything looks okay from your end.  You will have to be using Bioc devel 3.10 to be able to see the resources.  

Unless you have any other concerns - I think the package is good from my end -  
Don't forget to update DMRcate to use the hub resources now and to update the version of DMRcate software package 1.99.0  so that it will be bump to 2.0.0 at release time.

**Comment by timpeters82** [comment]
Thanks Lori! Much appreciated.
Cheers,
Tim

**Comment by timpeters82** [comment]
Hi Lori,
Ok, I have pushed versions 1.99.0 of DMRcate and DMRcatedata to origin/master and upstream/master.

Just checking if I've done the right thing to make this propagate to BiocCheck for 3.10 and you can see the pushes from your end?

Cheers,
Tim

**Comment by lshep** [comment]
Yes I see the changes. You should see 1.99.0  either on today or tomorrow's build report depending on when you push.  This data package will be added shortly;  You will receive additional instructions about it soon. Cheers

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/timpeters82.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DMRcatedata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DMRcatedata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
