### ISSUE TITLE
peco

### ISSUE THREAD

**Issue by jhsiao999** [Bioconductor/Contributions#1248]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jhsiao999/peco

Confirm the following by editing each check box to '[x]'

- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package to use the more modern [SummarizedExperiment][1] or, given the topic of your package, [SingleCellExperiment][2]

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by jhsiao999** [comment]
@mtmorgan Thank you for the feedbacks. We now use SingleCellExperiment to store our data. All examples have been updated accordingly. 

@bioc-issue-bot We've bumped the version to 0.99.3.

**Comment by LiNk-NY** [comment]
Hi ChiaoWen, @jhsiao999 
Thank you for your submission. 
Please see the package review below. 
If you have any questions, feel free to post them as comments below. 

Best,
Marcel 

---

# peco #1248

Overall, the package seems to use `list`s often as function outputs. It is
better to have 'endomorphic' operations that take a `SingleCellExperiment` as
input and return one with results whenever possible.

## DESCRIPTION

* The `Date` field is not really needed.
* Looks good

## NAMESPACE

* Avoid tagging functions with `generic`. The 'generic' property should be
reflected in the implementation

## vignettes

* Please respect the 80 column width limit, it makes it easier to maintain
and easier to review
* Avoid using `get` with `data`. Simply use `data(sce_sub)`
* Consider using a more informative dataset name
* Use `apply(x, 1L, ...)` instead of
`do.call(rbind, lapply(seq_len(nrow(x)), ...))`
* Avoid converting logical to numeric index. Often the logical index is enough:
`which(coldata$chip_id != "NA18511")` can be `coldata$chip_id != "NA18511"` and
you can add `!` in the front to get the opposite (instead of `==`)

Minor:
* Simplify code by using `1:5` instead of `c(1:5)`

## R

* Please use a standard 1 or 2 cores as default for functions that use
`doParallel`
* Prioritize vectorized operations and try to avoid nested `for`/`lapply` loops
* Avoid using `sapply` and use `vapply` instead
* Use 'character' indices (e.g., `x["coef"]` vs `x[2]`) for subsetting data
whenever possible to avoid mistakes when data changes

### data.R

* Use descriptive names

Minor:
* Consider using `seq_along` instead of `seq_len(length(...))`
* No need to double evaluate to `TRUE` in `if (plot.it == TRUE)`;
`if (plot.it)` should be enough

**Comment by LiNk-NY** [comment]
Hi ChiaoWen, @jhsiao999 
Please provide an item-by-item response to the review.
Otherwise, I'd be forced to close the issue due to inactivity. 
Thank you.
-Marcel

**Comment by jhsiao999** [comment]
@LiNk-NY Hi Marcel, sorry for the delayed response. I've been working on incorporate the package as a Bioconductor single-cell analysis workflow, so that the main input/output object would be `SingleCellExperiment`. I will send a response to the comments later today. 

Thanks for the reminder,

Joyce

**Comment by jhsiao999** [comment]
@LiNk-NY Thank you for the useful suggestions. Please see my reply below. These changes have been incorporated into version v0.99.5. 
https://github.com/jhsiao999/peco

> Hi ChiaoWen, @jhsiao999
> Thank you for your submission.
> Please see the package review below.
> If you have any questions, feel free to post them as comments below.
> 
> Best,
> Marcel
> 
> # peco #1248
> Overall, the package seems to use `list`s often as function outputs. It is
> better to have 'endomorphic' operations that take a `SingleCellExperiment` as
> input and return one with results whenever possible.
The main functions now output `SingleCellExperiment` object. These include `cycle_npreg_outsample` and `data_transform_quantile`.

> ## DESCRIPTION
> * The `Date` field is not really needed.
> * Looks good
> 
> ## NAMESPACE
> * Avoid tagging functions with `generic`. The 'generic' property should be
>   reflected in the implementation
I am not sure how to address this comment. In the current version of NAMESPACE, none of the function is tagged with `generic`. Please let me know if this is still an issue.

> ## vignettes
> * Please respect the 80 column width limit, it makes it easier to maintain
>   and easier to review
The code has been edited accordingly.

> * Avoid using `get` with `data`. Simply use `data(sce_sub)`
Data are now loaded use `data`

> * Consider using a more informative dataset name
Dataset names are changed to `model_5genes_predict.rda`, `model_5genes_train.rda`, `sce_top101genes.rda` and `training_human.rda`.

> * Use `apply(x, 1L, ...)` instead of `do.call(rbind, lapply(seq_len(nrow(x)), ...))`
Changes have been made accordingly.

> * Avoid converting logical to numeric index. Often the logical index is enough:
>   `which(coldata$chip_id != "NA18511")` can be `coldata$chip_id != "NA18511"` and
>   you can add `!` in the front to get the opposite (instead of `==`)
Changes have been made accordingly.

> Minor:
> * Simplify code by using `1:5` instead of `c(1:5)`
Changes have been made accordingly.
 
> ## R
> * Please use a standard 1 or 2 cores as default for functions that use `doParallel`
Changes have been made accordingly.

> * Prioritize vectorized operations and try to avoid nested `for`/`lapply` loops
Changes have been made accordingly.

> * Avoid using `sapply` and use `vapply` instead
Changes have been made accordingly.

> * Use 'character' indices (e.g., `x["coef"]` vs `x[2]`) for subsetting data whenever possible to avoid mistakes when data changes
Changes have been made accordingly.

> ### data.R
> * Use descriptive names
Changes have been made accordingly.

> Minor: 
> * Consider using `seq_along` instead of `seq_len(length(...))`
Changes have been made accordingly.

> * No need to double evaluate to `TRUE` in `if (plot.it == TRUE)`; `if (plot.it)` should be enough
Changes have been made accordingly.

**Comment by lshep** [comment]
We are working on updating the SPB builders on R 4.0 and Bioc 3.11  the dependency issues is on our end and we are investigating

**Comment by lshep** [comment]
The dependency issue on our end has been fixed.  These results reflect real ERRORs that should be corrected.  Cheers

**Comment by LiNk-NY** [comment]
Hi Joyce ChiaoWen, @jhsiao999 
Please follow up on the issues reported on the SPB. 
Thank you. -M

**Comment by jhsiao999** [comment]
Thanks @LiNk-NY! I'll look into this error and let you know if I have any questions. 

Joyce

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 
Any updates on the status of the changes? 
Thanks.

**Comment by jhsiao999** [comment]
Hi Marcel,

Apologies fo the delay. I am getting to them before the end of the year.
Thanks for you patience!

Joyce

**Comment by jhsiao999** [comment]
Hi Marcel @LiNk-NY , 

The errors have been fixed in peco 0.99.6. Please let me know if there are any more issues. Thanks!

Joyce

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 
Please bump the package's version for another build in the SPB. 
Thank you. 
Best,
Marcel

**Comment by jhsiao999** [comment]
Hi Marcel @LiNk-NY ,

I just bumped the version to 0.99.7, made a new build, and pushed the build to the GithHub repo. Thanks!

Joyce

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 
Thank you for bumping the version. Can you check if the web hook is still active? 
I don't see a build of your package. 
CC: @lshep 
Lori, Is the SPB operational? Thanks.

**Comment by Kayla-Morrell** [comment]
Hey Marcel @LiNk-NY, I just checked the SPB and everything is running correctly on it.

**Comment by jhsiao999** [comment]
Hi Marcel @LiNk-NY,

Do you see a build of the package now? I just checked the bioconductor webhook of the repo and it appears to be active (there is also a successful delivery).

P.S. What is the common practice of choosing webhook trigger event? Currently, I select "Just the Push Event". Thanks!

Joyce

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 

The build message should look like the [comment above](https://github.com/Bioconductor/Contributions/issues/1248#issuecomment-557611291).

You have the right trigger selected.
Try bumping the package `z` version (`x.y.z`) again.

@Kayla-Morrell Thanks for looking into it Kayla!

**Comment by jhsiao999** [comment]
Hi Marcel,

I bumped the version again. The push event seems to have triggered the above message. 

Joyce

> Hi Joyce, @jhsiao999
> 
> The build message should look like the [comment above](https://github.com/Bioconductor/Contributions/issues/1248#issuecomment-557611291).
> 
> You have the right trigger selected.
> Try bumping the package `z` version (`x.y.z`) again.
> 
> @Kayla-Morrell Thanks for looking into it Kayla!

**Comment by jhsiao999** [comment]
@LiNk-NY What do you suggest I should do to handle the following warning? Thanks!

Joyce

```
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.5 to 4.0.
```

**Comment by LiNk-NY** [comment]
@jhsiao999 
Because Bioconductor devel uses R-devel. It is recommended that you
change the R version dependency to `4.0.0`.

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 
I don't see your line-by-line response to the review. 
I will check the changes today. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 

I now noticed your line-by-line responses. In the future, please add more empty lines between original text and your responses for readability. (See below for an example)


> Avoid tagging functions with generic. The 'generic' property should be
reflected in the implementation

> > I am not sure how to address this comment. In the current version of NAMESPACE, none of the function is tagged with generic. Please let me know if this is still an issue.

Some functions such as `fit_trendfilter_generic` have the `generic` tag in the name.
This should just be a regular function called `fit_trendfilter` unless you're creating a
'generic' for which you have and own a class to apply the method to (in S4 the
implementation would involve `setGeneric` and `setMethod`).

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 
Any updates?

**Comment by jhsiao999** [comment]
Hi Marcel @LiNk-NY,

I didn't have time to look into this yet. I'll fix it this weekend. Thank you!

Joyce

**Comment by LiNk-NY** [comment]
Thank you Joyce! @jhsiao999

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999  
It's been a few weekends. Do you have updates to `peco`? 
Thanks!

**Comment by LiNk-NY** [comment]
Hi Joyce, @jhsiao999 

Thanks for making those changes. 
Do the packages need a version number dependency? 

https://github.com/jhsiao999/peco/blob/1e79324378a8e13b0fd26be8401ce7f6f8f418e9/DESCRIPTION#L26-L37

Usually, you add a version number if there is a feature that is only implemented in a particular version or above. Is that the case for all the packages listed in the `DESCRIPTION` file with the exception of `R`?

**Comment by jhsiao999** [comment]
Hi @LiNk-NY,

I cannot be sure of all the specific features that are implemented in a particular version of these pages. The version numbers are added in case of a possible feature that I am not aware of. I usually do this for my R packages to avoid possible versioning issues during software installation. This is probably more of a concern for newer packages such as `scater`, `SingleCellExperiment` and `SummarizedExperiment`. 

What do you think about keep the version numbers of the newer packages? Is this acceptable? 

Thanks,
Joyce

**Comment by jhsiao999** [comment]
Hi @LiNk-NY,

We have received requests about using our package for R3.6. The current version requires R>=4.0. Any suggestions on how to approach this? For example, could we create a new branch release compatible with R3.6? Would this trigger a new Bioc package built? Thanks!

Joyce

**Comment by jdblischak** [comment]
From the [Bioconductor package guidelines](https://www.bioconductor.org/developers/package-guidelines/):

> It is seldom necessary to specify R or specific versions as dependencies, since the Bioconductor release strategy and standard installation instructions guarantee these constraints. Repositories mirrored outside Bioconductor should include branches for each Bioconductor release, and may find it useful to fully specify versions to enforce constraints otherwise guaranteed by Bioconductor installation practices.

If we create the branch `RELEASE_3_11` in our GitHub repository, how can we have Bioconductor build that branch instead of `master`?

Alternatively, can we simply remove the hard dependency on a specific version of R? As the guidelines state, this is handled by Bioconductor anyways.

Also, looking at official Bioconductor GitHub repositories for guidance:

* [Rhtslib](https://github.com/Bioconductor/Rhtslib) does not include the field `Depends` in either the `master` or `RELEASE_3_10` branches

* [VariantAnnotation](https://github.com/Bioconductor/VariantAnnotation) depends on `R (>= 2.8.0)` in both the `master` and `RELEASE_3_10` branches (even though [Bioconductor 3.10](https://bioconductor.org/news/bioc_3_10_release/) requires `R >=3.6.1`)

**Comment by LiNk-NY** [comment]
@jhsiao999 The versioning of packages in the `Imports:` field is a bit overkill since Bioconductor releases ensure that packages work well with other packages in that particular release. You could leave the package versions in the field, it usually doesn't hurt **unless** you get a request to use the package with a different R version. It is recommended to use a version `pkg >= x.y.z` only when necessary features are implemented past a particular version number _that your package uses_. 

**On the other hand**, if you do leave the versions on there, users may encounter issues when using an older version of R and Bioconductor because they will not be able to download those packages with an older version of Bioconductor because the newer version (`pkg >= x.y.z`) resides in a newer version of Bioconductor. 

Given the request to use your package outside of the R version it was created for, my recommendation is to remove the R version tag from the `Depends: ` field. The package _may_ work with older versions of R but it is _less_ likely to do so with the added version tags in the `Imports: ` field. A package can't be guaranteed to work with older versions because of this. 

@jdblischak There is no need to create that branch yet. You will do so when the Bioconductor release is published. 
Also, some packages include serialized instances of data that require them to have an R version specification (that may be the case for `VariantAnnotation` though I'm not sure).

**Comment by jdblischak** [comment]
> Given the request to use your package outside of the R version it was created for, my recommendation is to remove the R version tag from the Depends: field.

@LiNk-NY We're stuck at the moment. If we remove `Depends` entirely, then we get the WARNING:

```
* checking data for ASCII and uncompressed saves ... WARNING
  Warning: package needs dependence on R (>= 2.10)
```

If we then add `Depends: R (>= 2.10)`, then we get the WARNING

```
Checking R Version dependency...
    * WARNING: Update R version dependency from 2.10 to 4.0.
```

Since Bioconductor itself will handle the minimal R version during the installation process, is it ok if we leave the R depends as `R (>= 2.10)`?

**Comment by LiNk-NY** [comment]
Hi John, @jdblischak 

I see that you have serialized data in the `data` folder. This requires that you have an R version specified.

Ideally, your early users should have `R (>= 4.0.0)` as the Bioconductor release will _soon_ require it.
Anyone with an older version of R could have a potentially troublesome installation of Bioconductor.

You could set the `Depends: ` field to `R (>= 3.6.0)` and make no guarantees and live with the warning. The version restrictions will soon be in place once the Bioconductor release is out anyway.
The devel branch (which becomes the release) of Bioconductor has been making use of `R (>= 4.0.0)` for a while now and using new features of R in the process.

**Comment by jdblischak** [comment]
> I see that you have serialized data in the data folder. This requires that you have an R version specified.

Ah, that makes sense. Thanks for that insight. I was a little confused why `R CMD check` was requiring a minimum version.

> Ideally, your early users should have R (>= 4.0.0) as the Bioconductor release will soon require it.
> Anyone with an older version of R could have a potentially troublesome installation of Bioconductor.

> You could set the Depends: field to R (>= 3.6.0) and make no guarantees and live with the warning. The version restrictions will soon be in place once the Bioconductor release is out anyway.

The warning doesn't bother me because the package works fine with both R 3.x and R 4.0. I just want to make sure that this warning doesn't prevent peco from being included in the upcoming Bioconductor 3.11 release. In other words, are you and the other Bioconductor maintainers ok with the warning?

As we've discussed above, BiocManager can enforce the minimum R version required for whichever Bioconductor release the user has installed. It's not necessary for every R package to require R > 4.0.

> The devel branch (which becomes the release) of Bioconductor has been making use of R (>= 4.0.0) for a while now and using new features of R in the process.

The peco package is compatible with R 4.0.0 and its new features, as shown by the Bioconductor build results.

**Comment by LiNk-NY** [comment]
Yes, the warning is OK. 

> It's not necessary for every R package to require R > 4.0.

Yes, it's mostly cosmetic until someone with R version 3.2.5 shows up and wants to use the package directly from GitHub :face_with_head_bandage:. That's why we have explicit installation instructions. 

The alternative is to create a branch in the repo for your `R (>= 3.5.0)` users (`BiocManager` was made only for R 3.5 and above). 

The package is almost ready to go. Thanks!

**Comment by jdblischak** [comment]
> Yes, it's mostly cosmetic until someone with R version 3.2.5 shows up and wants to use the package directly from GitHub 🤕. That's why we have explicit installation instructions.

Very true. We'll handle these types of installation issues on our GitHub Issues tracker.

> The alternative is to create a branch in the repo for your R (>= 3.5.0) users (BiocManager was made only for R 3.5 and above).

Thanks for the tip. We'll consider this option if it starts to become a big problem.

> The package is almost ready to go. Thanks!

Great! Please let us know any remaining issues that you would like to see addressed.

And thanks again for all of your guidance!

**Comment by LiNk-NY** [comment]
Thank you for your submission. Your package has been accepted!
:tada:

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jhsiao999.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("peco")`. The package 'landing page' will be created at

https://bioconductor.org/packages/peco

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
