### ISSUE TITLE
scPCA

### ISSUE THREAD

**Issue by PhilBoileau** [Bioconductor/Contributions#1249]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PhilBoileau/scPCA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by hpages** [comment]
Hi @PhilBoileau ,

I see that you've been actively working on scPCA and the package now passes `R CMD check` and `R CMD BiocCheck` without errors or warnings. Thanks for that. Please let me know if the package is now ready for review.

Regards,
H.

**Comment by PhilBoileau** [comment]
Hi @hpages,

The package is ready for you to review. We’re looking forward to your feedback.

Thank you,
Phil

**Comment by nhejazi** [comment]
Hi @hpages --- please let us know if we can help facilitate the review process. We hope to make the 3.11 release deadline if at all possible. Thanks in advance for your review of our package.

**Comment by hpages** [comment]
Hi @nhejazi 

Sorry for the slow response. I'm currently taking a look at the package. I'll send you some feedback today.

Thanks for your patience,
H.

**Comment by nhejazi** [comment]
Thanks, @hpages. Since the deadline for inclusion of the package in release 3.10 has been advertised as this Wednesday, please let us know if there are any changes we need to make for acceptance of the package. From last submission experience, I think this package covers all of the requirements, but we’re sure that a review from you, time permitting, would still improve its quality.

**Comment by hpages** [comment]
I've been distracted again, sorry. The package looks good. Thanks for your contribution!

H.

**Comment by nhejazi** [comment]
@hpages, many thanks for getting back to us in time for the 3.10 release and for accepting our `scPCA` package. We're looking forward to having this work in the Bioconductor ecosystem!

**Comment by PhilBoileau** [comment]
@hpages, seconding what @nhejazi has said. Thank you for accepting our package!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PhilBoileau.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scPCA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scPCA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
