### ISSUE TITLE
flowSpy

### ISSUE THREAD

**Issue by ytdai** [Bioconductor/Contributions#1251]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JhuangLab/flowSpy

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by ytdai** [comment]
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> On one or more platforms, the build results were: "ERROR".
> This may mean there is a problem with the package that you need to fix.
> Or it may mean that there is a problem with the build system itself.
> 
> Please see the [build report](http://bioconductor.org/spb_reports/flowSpy_buildreport_20190918112209.html) for more details.

Hi @bioc-issue-bot 

I have removed all flowSpy.Rproj, .DS_Store and .gitattributes in flowSpy project. 
Please help me to check the package again, many thanks.

best

Yuting Dai

**Comment by dvantwisk** [comment]
Here is the review of your package. The code looks very well written and most of my issues are related to the documentation. [REQUIRED] tags describe changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not necessary. Please message me back when you are finished making changes.

R/GENERAL
- [ ] [REQUIRED] In come places of the Roxygen documentation, only the
class of the parameter is given with no further description of what it is
meant to be. They should be expanded on for the user's sake. E.g
R/cluster.R:L297 `@param algorithm numeric.`.

R/buildTree.R
- [ ] [REQUIRED] There is no documention for what the `dim.type` and
`dim.use` parameters are meant to represent.
- [ ] [CONSIDER] `match.arg()` could be used to explicitly state
what values are expected for `dim.type` to be. At the moment, it seems
you expect the user to know what inputs are acceptable here without
stating them.

R/preprocessing.R
- [ ] [REQUIRED] L215-233: `message()` should be used instead of `cat()` here.
The reason being that `suppressMessages()` can be used to toggle whether the
user sees the message.

R/pseudotime.R
- [ ] [CONSIDER] L172: It looks like `dim.type` could be declared using
`match.arg()` here

R/trajectory.R
- [ ] [CONSIDER] L33: `mode` could use `match.arg()` to be declared.

**Comment by ytdai** [comment]
> Here is the review of your package. The code looks very well written and most of my issues are related to the documentation. [REQUIRED] tags describe changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not necessary. Please message me back when you are finished making changes.
> 
> R/GENERAL
> 
> * [ ]  [REQUIRED] In come places of the Roxygen documentation, only the
>   class of the parameter is given with no further description of what it is
>   meant to be. They should be expanded on for the user's sake. E.g
>   R/cluster.R:L297 `@param algorithm numeric.`.
> 
> R/buildTree.R
> 
> * [ ]  [REQUIRED] There is no documention for what the `dim.type` and
>   `dim.use` parameters are meant to represent.
> * [ ]  [CONSIDER] `match.arg()` could be used to explicitly state
>   what values are expected for `dim.type` to be. At the moment, it seems
>   you expect the user to know what inputs are acceptable here without
>   stating them.
> 
> R/preprocessing.R
> 
> * [ ]  [REQUIRED] L215-233: `message()` should be used instead of `cat()` here.
>   The reason being that `suppressMessages()` can be used to toggle whether the
>   user sees the message.
> 
> R/pseudotime.R
> 
> * [ ]  [CONSIDER] L172: It looks like `dim.type` could be declared using
>   `match.arg()` here
> 
> R/trajectory.R
> 
> * [ ]  [CONSIDER] L33: `mode` could use `match.arg()` to be declared.


Thank you for the comments and suggestions. I have fixed the issues that are related to the documentation. Please see the updated version 0.99.2 of flowSpy. 

Best,

Yuting Dai

**Comment by dvantwisk** [comment]
How's progress on this? I do need to mention that the release bioc3.10 deadline is October 22nd. Please finish making changes to your package by then.

**Comment by dvantwisk** [comment]
The changes look good! I'm going to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ytdai.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("flowSpy")`. The package 'landing page' will be created at

https://bioconductor.org/packages/flowSpy

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
