### ISSUE TITLE
selectKSigs

### ISSUE THREAD

**Issue by zhiiiyang** [Bioconductor/Contributions#1252]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/USCbiostats/selectKSigs

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by zhiiiyang** [comment]
Hi @lshep,

The package is ready for review. Looking forward to your feedback. Thank you!

Zhi

**Comment by mtmorgan** [comment]
DESCRIPTION

- ok

NAMESPACE

- ok

NEWS

- please make sure that this file is parsed by `utils::news()`.

vignette

- the vignette seems to end abruptly. Help the user to understand the results by interpreting them. Perhaps also suggest 'next steps'.

- include the output of `sessionInfo()` for reproducibility.

R

- generally it is very poor form to use direct slot access `slot()` or `@` and instad one shoudl use `accessors`; can you access the data in the objects you are using with function calls, rather than accessors?

src

- ok

man

- include examples for all exported functions

- Generally, the description of arguments and values is very terse; will a user trying to understand your package be given enough information?

**Comment by mtmorgan** [comment]
@zhiiiyang will you have a chance to update your package in response to the comments above?

**Comment by zhiiiyang** [comment]
> @zhiiiyang will you have a chance to update your package in response to the comments above?

I was sorry that I was swamped with preparing my defense in the past weeks. I just defended this Monday and will be addressing the problem in a few days. Thank you for your patience.

**Comment by zhiiiyang** [comment]
> @zhiiiyang will you have a chance to update your package in response to the comments above?

Hi Martin, I am almost done addressing all the comments except for the following one. 

`generally, it is very poor form to use direct slot access slot() or @ and instead one should use accessors; can you access the data in the objects you are using with function calls, rather than accessors?`

Can you provide an example of it? Are we talking about using `setGeneric` and `setMethod` for all the slots? Or I can use a function like this `person_name <- function(x) x@name`. Thank you!

**Comment by mtmorgan** [comment]
This
```
cv_PMSignature.R:      nP <- length(param@sampleList)*(k-1) +
```
uses direct slot access, whereas one would rather some accessor `sampleList(param)` if that is appropriate.

**Comment by zhiiiyang** [comment]
> This
> 
> ```
> cv_PMSignature.R:      nP <- length(param@sampleList)*(k-1) +
> ```
> 
> uses direct slot access via `@`, whereas one would rather some accessor `sampleList(param)` if that is appropriate.

Got it. Then I will use `setGeneric` and `setMethod` to define the `sampleList` accessor. This might not be the right place to ask this question. But since there are lots of slots that need to be assessed, i.e., approximately ~ 10 accessors, is there a convenient way to define a more generic accessor for different slots? Or I just to define each accessor using `setGeneric` and `setMethod` ten times? Thank you so much!

**Comment by mtmorgan** [comment]
You could write something programmatic (e.g., using `slotNames()` in a `for()` loop) but invariably this 'clever' approach comes back to haunt you...

**Comment by zhiiiyang** [comment]
Hi Martin, please see all the comments below. I've updated the package accordingly. Thank you for your help!

> DESCRIPTION
> 
> * ok
> 
> NAMESPACE
> 
> * ok
> 
> NEWS
> 
> * please make sure that this file is parsed by `utils::news()`. **fixed it**
> 
> vignette
> 
> * the vignette seems to end abruptly. Help the user to understand the results by interpreting them. Perhaps also suggest 'next steps'. **added a visualization to highlight the optimal number**
> * include the output of `sessionInfo()` for reproducibility. **added it**
> 
> R
> 
> * generally it is very poor form to use direct slot access `slot()` or `@` and instead one should use `accessors`; can you access the data in the objects you are using with function calls, rather than accessors? **Please refer to R/class_G.R and R/class_param.R**
> 
> src
> 
> * ok
> 
> man
> 
> * include examples for all exported functions **I didn't see any exported functions without examples. Could you point it out?**
> * Generally, the description of arguments and values is very terse; will a user trying to understand your package to be given enough information? **The paper is currently under review. Users will often come in with basic knowledge of the data and apply this method under a specific framework.**

**Comment by zhiiiyang** [comment]
@mtmorgan Hi, should I go ahead to fix the warnings which are about "Update R version dependency from 3.6 to 4.0." Should i go ahead and download the devel version of R (4.0)? Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhiiiyang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("selectKSigs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/selectKSigs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
