### ISSUE TITLE
scDblFinder

### ISSUE THREAD

**Issue by plger** [Bioconductor/Contributions#1254]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/plger/scDblFinder

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by Liubuntu** [comment]
An easy fix to your building report error: 

Add all packages from NAMESPACE into the `Imports` (or `Depends` if really necessary) field of DESCRIPTION file. 

```
* checking package dependencies ... ERROR
Namespace dependencies not required: 'S4Vectors', 'ggplot2', 'methods'
```

**Comment by Liubuntu** [comment]
Hi @plger , 

Please see below for the initial package review. Try to address all or most of the issues and comment back with any questions / comments / when ready for a second look. 

Best,
Qian

## DESCRIPTION
- `License` field: please specify the version. (e.g., GPL-3)
- `LazyData` field: For packages that include data, we recommend not
  including LazyData: TRUE. This rarely proves to be a good thing. In
  our experience it only slows down the loading of packages with large
  data.
- `BugReports:` field: It is encouraged to include the relevant links
  to Github Issues tracker.
- `URL:` field: This field directs users to source code repositories,
  additional help resources, etc; Usually it could be the github link.

## NAMESPACE
- It's recommended to only use `testthat` package in the test
  functions, which goes to the `Suggest` field under DESCRIPTION file,
  and no need to import in NAMESPACE.

## R/
General:
- It's suggested to have the unit tests separated from the R
  scripts. By calling `usethis::use_test("scDblFinder")` interactively
  in your R session, it generates a folder under the package repo
  called "tests/testthat/", you can put your test functions,
  eg. `test-funcName.R` to the path for anything you want to test
  about that function. By calling `usethis::use_test`, it also
  automatically add `testthat` as `Suggests` in DESCRIPTION file.

- scDblFinder.R:L72,L80, use something like `stopifnot(is(sce,
  "SingleCellExperiment"))` to replace the `expect_*` functions.

## man/
- `scDblFinder(dbr)`, the script shows 0.01, and help doc shows 0.1?

## vignette
- After the Introduction, please add a section for "Installation" to
show to users how to install the package as if it has been included in
Bioconductor. You should include something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```

## unit test
- See above `R/` section for details.

**Comment by plger** [comment]
Dear @Liubuntu 
thanks for the clear and helpful review!
I've addressed everything, but at the moment I just removed `testthat` (I'll have to read and play around to properly use the unit tests).
(Kudos for spotting the 0.1 in the docs  - thanks again!)

**Comment by Liubuntu** [comment]
Hi @plger , 

Your updates looks good. One more thing, please look at this following note message from building report, and address as suggested. 

```
Undefined global functions or variables:
  BPPARAM FPR TPR abline assayNames colData<- ecdf is legend lines
  method optimize pcauchy plot
Consider adding
  importFrom("graphics", "abline", "legend", "lines", "plot")
  importFrom("methods", "is")
  importFrom("stats", "ecdf", "optimize", "pcauchy")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
```

Cheers,
Qian

**Comment by plger** [comment]
Hi @Liubuntu ,

I've fixed these imports, but I'd have a question on this:

```
Undefined global functions or variables:
  FPR TPR assayNames colData<- method
```

The TPR/FPR/method is due to the way ggplot parses its arguments ('within' the data.frame), but regarding the undefined `assayNames` and `colData<-`: I thought that by importing the whole of `SingleCellExperiment`, all the methods of that package were also imported. Why does it still not know where to find them?

**Comment by Liubuntu** [comment]
Hi @plger , 

For the notes generated from ggplot variables we can ignore right now. 

For the other 2 methods, because they are not exported from `SingleCellExpeirment` package, but defined in `SummarizedExperiment`. So importing the namespace of `SingleCellExperiment` doesn't automatically load these methods. (Since you are only `Imports: `, not `Depends: ` on it. `SingleCellExperiment` depends on `SummarizedExperiment`. If your package depends on `SingleCellExperiment`, the loading of your package loads the `SingleCellExperiment`, which in turn loads `SummarizedExperiment` to have those methods available). We are not encourage package authors to have many packages in the `Depends: ` fields, so that you need to import these methods explicitly. 

```
 > SingleCellExperiment::`colData<-`
 Error: 'colData<-' is not an exported object from 'namespace:SingleCellExperiment'
 > 
!> SingleCellExperiment::assayNames
 Error: 'assayNames' is not an exported object from 'namespace:SingleCellExperiment'

 > methods(`colData<-`)
 [1] colData<-,SummarizedExperiment,DataFrame-method
 see '?methods' for accessing help and source code
 > 
!> methods(`assayNames`)
 [1] assayNames,SummarizedExperiment-method
 see '?methods' for accessing help and source code
```

You need to explicitly `@importFrom SummarizedExperiment colData<- assayNames` to load `SummarizedExperiment` and the 2 methods into your package's namespace. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @plger , 

Your package building report is already pretty clean. But before acceptance, it would be great if you can also look into the following NOTE message and fix them. Thanks!

Please make sure to make these updates ASAP since the deadline for accepting new packages would be this Wednesday, on Oct 23rd. Thanks!  [Release Schedule]( http://bioconductor.org/developers/release-schedule/)

```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        doubletThresholding.R (line 78, column 12)
        doubletThresholding.R (line 79, column 12)
        doubletThresholding.R (line 84, column 37)
        doubletThresholding.R (line 86, column 14)
        misc.R (line 50, column 26)
        misc.R (line 80, column 11)
        overcluster.R (line 81, column 22)
        overcluster.R (line 110, column 20)
        scDblFinder.R (line 149, column 19)
        scDblFinder.R (line 185, column 24)
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        doubletThresholding.R (line 77, column 10)
        scDblFinder.R (line 111, column 51)
        scDblFinder.R (line 119, column 16)
        scDblFinder.R (line 152, column 37)
```

Best,
Qian

**Comment by plger** [comment]
Dear @Liubuntu ,

- thanks for the explanation on the import/namespace, I've imported the additional functions now.
- I've also replace the sapply to vapply (although to be honest I find it a bit excessive for the likes of `sapply(x, length)`... )
- The remaining notes on `Avoid 1:...` refer to hardcoded cases (e.g. `1:1500`) where the alternative doesn't bring anything more.

**Comment by Liubuntu** [comment]
Hi @plger , 

Thanks for making the prompt changes. Both the `seq_len()`, `seq_along`, and the `vapply()` are encouraged for robustness, so that they could avoid issues from any unnecessary edge cases. 

Your package is now accepted, thank you for the contribution to Bioconductor. 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/plger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scDblFinder")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scDblFinder

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
