### ISSUE TITLE
scTGIF

### ISSUE THREAD

**Issue by kokitsuyuzaki** [Bioconductor/Contributions#1255]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rikenbit/scTGIF

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 
Thank you for your submission. 
I will be reviewing your package. 
My initial review shows that you have an undocumented object: 

```
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 1 object(s) are initialized. Maybe
      it is part of a data set loaded with data(), or perhaps part of
      an object referenced in with() or within().
    function (object)
      .twoDimGrid (aMat)
```

Please resolve this. I will be providing your full review in coming days. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 
Please see the review below. 
If you have any questions, please include them as additional comments below. 

Thank you. 

Best regards,
Marcel

---

# scTGIF #1255

## README.md

* Please use a vector of packages as input to `BiocManager::install`

## DESCRIPTION

* Please format the file to fit the 80 column width limit
* It is recommended that the `Imports` field contain one package per line for
readability
* `Date` field is not really needed

## NAMESPACE

* It looks good.
* Consider using `roxygen2` for documentation

## vignettes

* Introduction well established.
* Avoid using `eval=FALSE` in chunks. Provide a smaller example dataset if the
current one is too big.

## R

* It is recommended that you do not create methods for classes that are not
your own especially if there is only one method. Please use a plain function
for `settingTGIF`.
* Avoid `eval` / `parse` operations and use alternatives such as `[[`.
* Avoid putting objects in the `.GlobalEnv` from an internal function. Use the
conventional return object.
* Do not save files / reports for the user by default, make this argument
optional.
* Use temporary files by default and display HTML pages
* Consider using `Rcpp` for `text.aMat`

**Comment by kokitsuyuzaki** [comment]
Hi, @LiNk-NY

Thank you for your previous help during the review of scTensor.
Please check the revised version of scTGIF.
I tried to fully address your comments,
but there are some ambigous parts for me.

> .twoDimGrid

I added the temporal definition of `aMat` to remove the NOTE.

> README.md

I vectorized the package names in `BiocManager::install`.

> DESCRIPTION

I listed the package names in `Imports` field as one package per line.

> NAMESPACE

I may use roxygen2 in the next time.

> Vignettes

I have removed all `eval=FALSE` parts.

> R

- settingTGIF: Actually `SingleCellExperiment` class is not my own, but many single-cell tools are based on this class. Besides, this is not the only one method; I also implemented `calcTGIF` and `reportTGIF` for this class.

- eval/parse: I removed all the eval/parse parts such as

```
reducedDims(sce)[[reducedDimNames]]
assays(sce)[[assayNames]]
```

- .GlobalEnv: `assign(userobjects, sce, envir=.GlobalEnv)` is not for putting objects in the global environment, but updating the metadata slot in the `SingleCellExperiment` object (sce) the users defined in the global environment. So this part is necessary.

- Do not save files / report and use temporary files: I'm already using `tempdir()` by default. 

- display HTML pages: I changed the default value of `html.open` as TRUE.

- Rcpp: I'm still using `Rcpp::sourceCpp()` for compiling the text.aMat.


Regards,

Koki

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 
Thank you for your response. 
There is one additional item.

> `assign(userobjects, sce, envir=.GlobalEnv)` is not for putting objects in
the global environment, but updating the metadata slot in the
SingleCellExperiment object (sce) the users defined in the global environment.
So this part is necessary.

Why not provide an endomorphic operation that takes an `sce` as input and
returns `sce` with additional metadata? It is not recommended to change
objects in the user's `.GlobalEnv`.


Best,
Marcel

**Comment by kokitsuyuzaki** [comment]
Hi, @LiNk-NY

Ok, I modified the parts related to `.GlobalEnv`.

Koki

**Comment by kokitsuyuzaki** [comment]
Hi, @LiNk-NY

Ok, I modified the parts related to `.GlobalEnv`.

Koki

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 

Thank you for your updates. 
I will accept your package. 

I wanted to note an interesting use of the gerund for set in `settingTGIF`. Usually
the imperative form is used (`set*`) but this is not a matter of correctness but
rather one of style. 

For these methods `settingTGIF`, `calcTGIF`, `reportTGIF`, etc. should have
an argument such as `object` or `x` in the generic specification so that it can
be applicable to other classes and not just `sce` (which is the point of creating,
generics). 
This is something to consider in future releases. 

Thank you for your contribution. 
<sup> こうけんはありがとうございました！</sup>

Best regards,
Marcel

**Comment by kokitsuyuzaki** [comment]
Thanks @LiNk-NY !

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kokitsuyuzaki.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scTGIF")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scTGIF

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
