### ISSUE TITLE
flowSpecs

### ISSUE THREAD

**Issue by jtheorell** [Bioconductor/Contributions#1259]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jtheorell/flowSpecs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jtheorell** [comment]
Dear BioConductor team, 
Looking much forward to the coming interactions! I have tried to learn as much as possible from the last subsmission, so I hope this one will mean less work for You. 
Best regards
Jakob

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by Kayla-Morrell** [comment]
Hello @jtheorell - We had some issues with our Windows builder last week which is why you don't see Windows on your build report. I'm working on getting a build report that includes the Windows builder before I can start your initial review. Ignore the next few builds as I work out the issue and I'll let you know if there is anything you need to address.

Thanks,
Kayla

**Comment by Kayla-Morrell** [comment]
@jtheorell - Everything looks good now! I should have your initial review posted in the next couple days.

Best,
Kayla

**Comment by jtheorell** [comment]
Dear @Kayla-Morrell, 
Thank you very much! Looking forward to your input!
Best regards
Jakob

**Comment by Kayla-Morrell** [comment]
Hello @jtheorell,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The README.md file doesn't seem necessary unless you intend to 
put text in it.

## DESCRIPTION

- [ ] SUGGESTION: We encourage including the 'BugReports:' field with the 
relevant GitHub url for reporting Issues.

## NEWS

- [ ] REQUIRED: Thank you for including a news file, this helps keep track of 
changes to code from one version to the next. However, the file is not formated
 correctly. Please look at the following link to figure out how the NEWS file 
should be formatted: https://bioconductor.org/developers/package-guidelines/#news.

## Vignettes

- [ ] REQUIRED: After the 'Introduction' section there should be an 'Installation'
 section that shows the user how to download the pacakge from _Bioconductor_. 
The code should look something like this and should include `eval = FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("flowSpecs")
```

- [ ] SUGGESTION: Line 54, I would print just the head of the data so that it 
doesn't take up too much of the vignette space.

- [ ] SUGGESTION: Line 83, when rendering the vignette the line indent of this 
code looks a litte strange. I think there needs to be multiple of 4 spaces for 
this to indent correctly and it seems like you are at 23 spaces. If you use one
 more space this might help the look of the code.

- [ ] SUGGESTION: Line 122, this line also doesn't look great when I render the
 vignette. It looks like you are at 29 spaces. I would remove one space to make
 it 28 and this should help the look of the code.

- [ ] SUGGESTION: Line 247, same as the above two points. There are 37 spaces so
 if you removed one space to make 36 this should help the look of the code.

- [ ] REQUIRED: The last section of the vignette should be 'Session Information'
 and should include `sessionInfo()`.

## Man pages

- [ ] SUGGESTION: The only functions that need to be documented are those that 
are exported to the user. For those functions that aren't exported and you have
 included documentation for I would suggest adding `@keywords internal` so that
 it is removes the function from documentation index. 

*corrMatCreate*

- [ ] REQUIRED: Add runnable examples to this man page since it is exported to 
the user.

*flowSet2LongDf*

- [ ] REQUIRED: The package 'DepecheR' is unavailable to link to in this man 
page. I would add it to the 'Suggests:' of your package if you want the link to 
work. This way if the user really wants the link to work they can install the 
package but it's not necessary for your package to work.

## R code

- [ ] REQUIRED: Avoid the use of direct slot access with `@` or `slot()` but 
instead create and use an accessor method. This occurs in:
	- appendFFCols.R
	- flowSet2LongDf.R


Best,
Kayla

**Comment by jtheorell** [comment]
Dear @Kayla-Morrell, 
Thank you for all this very valuable input. I have addressed these issues, as specified below. In addition, I will correct my previous BioConductor package, DepecheR, as a number of these things did not appear in that review.

 ## General package development
 
 - [x] REQUIRED: The README.md file doesn't seem necessary unless you intend to
       put text in it.


 ## General package development
 
 - [x] REQUIRED: The README.md file doesn't seem necessary unless you intend to
       put text in it.
 
 
 ## DESCRIPTION
 
 - [x] SUGGESTION: We encourage including the 'BugReports:' field with the
       relevant GitHub url for reporting Issues.
 
 
 ## NEWS
 
 - [x] REQUIRED: Thank you for including a news file, this helps keep track of
       changes to code from one version to the next. However, the file is not formated
       correctly. Please look at the following link to figure out how the NEWS file
       should be formatted: https://bioconductor.org/developers/package-guidelines/#news.
 
 
 ## Vignettes
 
 - [x] REQUIRED: After the 'Introduction' section there should be an 'Installation'
       section that shows the user how to download the pacakge from _Bioconductor_.

 - [x] SUGGESTION: Line 54, I would print just the head of the data so that it
       doesn't take up too much of the vignette space.
 
 - [x] SUGGESTION: Line 83, when rendering the vignette the line indent of this
       code looks a little strange. I think there needs to be multiple of 4 spaces for
       this to indent correctly and it seems like you are at 23 spaces. If you use one
       more space this might help the look of the code.
 
 - [x] SUGGESTION: Line 122, this line also doesn't look great when I render the
       vignette. It looks like you are at 29 spaces. I would remove one space to make
       it 28 and this should help the look of the code.
 
 - [x] SUGGESTION: Line 247, same as the above two points. There are 37 spaces so
       if you removed one space to make 36 this should help the look of the code.

**Thank you. Have tried to style the code to look better in the vinjette now. Hopefully it does.** 

 - [x] REQUIRED: The last section of the vignette should be 'Session Information'
       and should include `sessionInfo()`.
 
 
 ## Man pages
 
 - [x] SUGGESTION: The only functions that need to be documented are those that
       are exported to the user. For those functions that aren't exported and you have
       included documentation for I would suggest adding `@keywords internal` so that
       it is removes the function from documentation index.
 
 
 _corrMatCreate_
 
 - [x] REQUIRED: Add runnable examples to this man page since it is exported to
       the user.
 
 
 _flowSet2LongDf_
 
 - [x] REQUIRED: The package 'DepecheR' is unavailable to link to in this man
       page. I would add it to the 'Suggests:' of your package if you want the link to
       work. This way if the user really wants the link to work they can install the
       package but it's not necessary for your package to work.
 
 
 ## R code
 
 - [x] REQUIRED: Avoid the use of direct slot access with `@` or `slot()` but
       instead create and use an accessor method. This occurs in:
       
       * appendFFCols.R
       * flowSet2LongDf.R

**One new accessory method created and in the other instance, an accessory method was already available. Thank you for clarifying this.**

**Comment by jtheorell** [comment]
Thanks a lot for a really smooth and fast process, @Kayla-Morrell!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jtheorell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("flowSpecs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/flowSpecs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
