### ISSUE TITLE
LinkHD-Bioconductor

### ISSUE THREAD

**Issue by lauzingaretti** [Bioconductor/Contributions#1262]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lauzingaretti/LinkHD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by lauzingaretti** [comment]
A new version of LinkHD library (1.0.1) is now available.

**Comment by lshep** [comment]
Please see the link about about [creating a webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook)   When version bumps are committed and pushed they should trigger a new build report.  Please set up a webhook and push a new version.

**Comment by lauzingaretti** [comment]
Done.

**Comment by lauzingaretti** [comment]
Dear Bioconductor's I'm not sure if it was a problem with the deliver because I don't receive an automatic response to rebuild my package.

**Comment by lshep** [comment]
Are you sure you set the webhook up properly?  Other issues are receiving posts so its not a system wide issue -  Make sure you version bump, commit and push too.

**Comment by lauzingaretti** [comment]
Can I close this issue and restart the process?

**Comment by lshep** [comment]
Please try again on this issue.  Double check the webhook.  Push a version bump up.  We would prefer to try and figure this out and not have to do that as it will involve us doing work on our database to allow you to reopen an issue.

**Comment by lauzingaretti** [comment]
Ok, maybe I am confusing with the webhook process. I should add a new
webhook or only to push using the first one?  I have my master branch and I
add a tag with 0.99.1 version. I fix a problem with the first version
because it was 1.0.0... thanks!

**Comment by lshep** [comment]
I just tested with a different issue and everything seems to work find.   
I would delete the webhook you set up and create a new one to make sure all the steps were followed correctly in [Adding a Webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook).  After that is done, please bump the version to `0.99.2` in the DESCRIPTION,  add and commit the change in git,  and push the changes to your github.  That should hopefully trigger a new build.   If it doesn't we will try and figure out a different solution.

**Comment by lauzingaretti** [comment]
thanks a lot @lshep. Maybe it was a problem with my old Webhook. Now it looks working!

**Comment by mtmorgan** [comment]
DESCRIPTION
 
 - ok
 
NAMESAPCE
 
 - ok
 
vignettes

- please format code chunks to more conventional form, e.g., via the `formatR` package. Please verify that the code is readable and complete, e.g., no lines that run off the edge of the page, in the vignette.

R (comments are on specific lines of code but apply throughout)

- Please feel free to increase readability of your code by being more liberal inthe use of lines and spaces, e.g., Auxiliares.R:11. 

    ```
    else {
        idx <- is.finite(unlist(Data)) & Data > 0
        exp(mean(log(Data[idx])))
    }
    ```

- Please condsider using formatR or similar to ensure that your code adopts more standard formatting, including use of white space to improve constency and readability.

- Auxiliares.R:90 since `X` is a matrix, all columns have the same type; use `typeof(X)` to test the type of X.

- Auxiliares.R:109 it's not clear why you check for a data.frame when from the calculation it is clear that you require all columns to be numeric, i.e., a matrix...

- Auxiliares.R:115 and throughout use vectorized calculations like `rowSums()` etc (including from the matrixStats package) for row and column summaries, rather than the `apply()` family.
- Auxiliares.R:125 is this just `df[is.na(df)] <- 0` ? but why replace NA values with 0?

- Auxiliares.R:139 why isn't this code indented consistently? It's very hard to read.

- Auxiliares.R:225: would it be better to use `readline()` here?

- CompromisePlot.R:46 for generics with many arguments usually only one or two are actually used for dispatch (method selection). Indicate this using the `signature=` argument.

- CompromisePlot.R:54 since this methdo is for 'DistStatis' objects, there is no need to test whehter `x` is of that class.

- CompromisePlot.R:58 please define and use 'accessor' functions e.g. `.compromise_coords <- function(x) x@Compromise.Coords` rather than direct slot access. The accessor functions, even or perhaps especially within your pacakge. The accessor functions define the interface to your data object, allowing you to change the data structure (e.g., for more efficient internal represenation) without having to re-write code that uses your data object.

- ComputeDistance.R:27 I think the code structure you are aiming for here is

    ```
    if (...) {
        ...
    } else if (..) {
        ...
    }
    ```
    
    or alternatively
    
    ```
    Distance <- switch(
        tolower(Distance),
        scalarproduct = ..., 
        euclidean = ..
        ...
    )
    ```

- LinkData.R Consdier wrapping your markdown annotations, e.g., as

    ```
    #' @description Integrating multiple Heterogeneous Datasets stored
    #'     into a list. This function makes Statis using Distances
    #'     options.  Statis is part of the PCA family and is based on
    #'     singular value decomposition (SVD) and the generalized singular
    #'     value decomposition (GSVD) of a matrix.  This methodology aims
    #'     to analyze several data sets of variables that were collected
    #'     on the same set of observations.  Originally, the comparisons
    #'     were drawn from the compute of the scalar product between the
    #'     different tables.  In our approach, the condition is relaxing
    #'     allowing the incorporation of different distances.
    #'@param Data should be a list of dataframes or ExpressionSet data
    #'     with the same length of the number of tables to be integrate.
    #'     In each dataframe, the Observations (common elements on Statis)
    #'     should be in rows and the variables should be in columns. Data
    #'     also might be a MultiAssayExperiment object from
    #'     MultiAssayExperiment package, a software for multi-omics
    #'     experiments integration in Bioconductor.
    ```
- LinkData.R:88 Use the accessor functions provided by MultiAssayExperiment, rather than direct slot access.

- LinkData.R:156 use `seq_along()` or `seq_len()` rather than `1:length(Data)`.

- LinkData.R:254 This `copy and append pattern (`pit = c(); for (i in ...) pit[i] = ...`) is inefficient and difficult to read; use `lapply()` or `vapply()` to manage memory `pit <- vapply(seq_len(nrow(RV)), fucntion(i) ..., numeric(1))`

- LinkData.R:350 instead of creating and then updating the `DistStatis` object, create the object once

    ```
    new("DistStatis", RV = RV, Inertia.RV = Inertia.RV, ...)
    ```
    
- VarSelection.R:138 use of `which()` is not necessary for subsetting; it makes the code more verbose than necessary.

- dAB.R: 67 it's not usually necessary to use `stop(paste0(...))`; `stop(...)` usually accomplishes the same thing.

man

- please pay attention to formatting of examples; as currently formatted they are difficult to read, spill outside the PDF version of the manuscript, and wrap around lines in a standard 80-column console view.

**Comment by lauzingaretti** [comment]
Hi Martin, I have followed your recommendations and now the repo is updated with a revised  version of LinkHD. Best regards

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lauzingaretti.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("LinkHD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/LinkHD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
