### ISSUE TITLE
OmnipathR

### ISSUE THREAD

**Issue by alberto-valdeolivas** [Bioconductor/Contributions#1263]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saezlab/OmnipathR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by alberto-valdeolivas** [comment]
Hello! 

I am getting a TIMEOUT when building the package in Windows. It seems to occur when running the tests contained in testthat. However, they run quite fast in the other systems. I have no easy access to a windows system so, I wonder if you can give some more information about the error or any clue about how to solve it, before writing to the bioc mailing list.   

Many thanks for your help.

Best regards,
Alberto.

**Comment by lshep** [comment]
We will try and investigate the slowness on windows.  I will review the package and have a review in the next few days.  Cheers

**Comment by lshep** [comment]
Thank you for submitting to Bioconductor.  Please see your initial review below:


**Build Report / NEWS**

- [ ] We really recommend a news file to keep track of changes in your package. These NEWS files are utilizes in our releases to compile a [release announcement](http://bioconductor.org/news/bioc_3_9_release/) of significant changes to packages. In R see `?news` for formatting. 

**Description**

- [ ] please remove `LazyData: tru` we have rarely found this useful and that it can actually slow installation. 

**LICENSE/LICENSE.md**

- [ ] Please remove one of these (probably the md version)

**NAMESPACE**

- [ ] Exported function generally don't start with a `.`. We would prefer not to use this notation.  Please see last section of R/man notes for further thoughts on this. 

**README**

- [ ] Include Bioconductor installation instructions

- [ ] Your package depends on igraph so you shouldn't need to do `library(igraph)`; it should load automatically with your package if you set your description and namespace correctly

**figures**

- [ ] Where are these figures used?

**vignettes**

- [ ] I don't think you should need to do `library` on packages that are in depends or imports of your package description/namespace.  Only packages in suggests should be `library` calls

- [ ] maybe do head(.get_interaction_databases()) to avoid multiple page output as vignette is proof of principle

- [ ] I notice you do a printPath_es in the vignette for one and printPath_vs for the other.  What is the difference between these print functions? It doesn't seem discussed in the vignette. 

- [ ] Perhaps make note that the other clustering algorithms and the clustering algorithm used are found in the igraph package directly. 

- [ ] section 3.1.2 when I run the code I get an error
```
> interactions <- import_PathwayExtra_Interactions(filter_databases=c("BioGRID","IntAct"),select_organism = 10090)
[1] "Downloaded 53923 interactions"
[1] "removed 44809 interactions during database filtering."
> interactions_Amfr <- filter(interactions, source_genesymbol == "Amfr" | target_genesymbol == "Amfr")
Error in filter(interactions, source_genesymbol == "Amfr" | target_genesymbol ==  : 
  object 'source_genesymbol' not found
In addition: Warning messages:
1: In data.matrix(data) : NAs introduced by coercion
2: In data.matrix(data) : NAs introduced by coercion
3: In data.matrix(data) : NAs introduced by coercion
4: In data.matrix(data) : NAs introduced by coercion
5: In data.matrix(data) : NAs introduced by coercion
6: In data.matrix(data) : NAs introduced by coercion

> interactions <- import_KinaseExtra_Interactions(filter_databases=c("PhosphoPoint","PhosphoSite"), select_organism = 10116)
[1] "Downloaded 4990 interactions"
[1] "removed 1428 interactions during database filtering."
> interactions_TargetDpysl2 <- filter(interactions,target_genesymbol == "Dpysl2")
Error in filter(interactions, target_genesymbol == "Dpysl2") : 
  object 'target_genesymbol' not found
In addition: Warning messages:
1: In data.matrix(data) : NAs introduced by coercion
2: In data.matrix(data) : NAs introduced by coercion
3: In data.matrix(data) : NAs introduced by coercion
4: In data.matrix(data) : NAs introduced by coercion
5: In data.matrix(data) : NAs introduced by coercion
6: In data.matrix(data) : NAs introduced by coercion

```
I believe you should do dplyr::filter for the code to work correctly. This should be applied throughout the vignette as it occurs in a few different places. 

- [ ] 3.5 maybe do a head of the `.get_intercell_categories()`

**R / man**

_dataframe2graph.R_

- [ ] These two functions are identical except for the first three lines.  I would suggest combined into one function (perhaps with an argument to determine which alternative code to run for the first 3 lines).  
- [ ] It seems like there should be some parameter checking that certain columns exist
that are necessary. 

*print_interactions.R*

- [ ]can message be used instead of print
- [ ] definately use message instead of cat
- [ ] use message instead of print for indicating empty path

*import_Omnipath.R*

- [ ] again it seems odd and not a popular format to use `.` in functions. I would change the listing of database functions to not include the `.` .  See additional comments below concerning these functions. 
- [ ] use message instead of print for status messages so the user can choose to suppress. 
- [ ] The following can be its own helper function that the other main functions call to check the input and avoid duplicating code

```
    if (select_organism %in% c(9606, 10116, 10090)){
        if (select_organism == 9606){
            url_ptms <- paste0(url_ptms_common,'&genesymbols=1') 
        } else {
            if (select_organism == 10116){
                url_ptms <- 
                    paste0(url_ptms_common,'&genesymbols=1&organisms=10116') 
            }
            if (select_organism == 10090){
                url_ptms <- 
                    paste0(url_ptms_common,'&genesymbols=1&organisms=10090') 
            }
        }     
    } else {
        stop("The selected organism is not correct")
    }

```
- [ ] Actually again import_Omnipath_Interactions and import_Omnipath_PTMS are essentially the same code except for the url (and what you name the object) and one additional filtering set.  The overlapping code should be in a single function -  if you want to still have an outward function distinct for PTMS and Interactions, that is fine but it should then call the new function that contains the similar code.  import_miRNAtarget_Interactions and import_AllInteractions are also the same as the above but with different url. 
- [ ]  The same with import_PathwayExtra_Interactions, import_KinaseExtra_Interactions, import_LigrecExtra_Interactions, import_TFregulons_Interactions.  It is the same code except for a url. Move to a common function. 
- [ ] The main point is to **eliminate duplicate code** where ever possible.  For that matter, the `.get` functions could also be combined to a single function with an argument for which url to grab since it does the same thing to the result 
```
get_databases = function(db=c("ptm", "complexes", "interactions")){
    
    db <- match.arg(db)
    url <- 
    	switch(db, 
               "ptm"='http://omnipathdb.org/ptms/?fields=sources',
               "complexes"='http://omnipathdb.org/complexes?&fields=sources',

        )
    res <- getURL(url, read.table, sep = '\t', header = TRUE,
        stringsAsFactors = FALSE)
    return(unique(unlist(strsplit(x = as.character(res$sources),split = ";"))))
}

```

I look forward to getting your package accepted to Bioconductor. Please perform the above revisions and comment back here with an update.  Please also bump the version number to kick off a new build and comment here that you are ready for a re-review. 

Cheers
Lori

**Comment by alberto-valdeolivas** [comment]
Hello Lori,

Many thanks for you review and your very useful comments. I performed the modifications you suggested, bumped a new version and I am therefore ready for a new review (I still get the same Warning for time in windows, whereas I have no issues in Unix or Mac ). 

You can find below some comments regarding the modifications you suggested:

**Build Report / NEWS**

- NEWS file included.

**Description**

- `LazyData: true` removed.

**LICENSE**

- LICENSE.md file removed.

**NAMESPACE**

- Modification of the name of the exported functions which started by a point.

**README**

- Github installation instructions replaced by the Bioconductor installation instructions.

- `library(igraph)` removed.

**Figures**

- First figure is included in the Vignette to illustrate the different types of data that can be retrieved using the package.

- Second figure is included in the README file for aesthetic reasons.

- I removed the third figure.

**Vignette**

- Removed the `library` calls of packages included in depends or Imports.

- I did `head` of some of the functions returning long outputs in the Vignette as suggested.

- I included `dplyr::` when calling to functions of this package to avoid potential mistakes between functions with the same name from different packages.

- `printPath_vs`  is used to print networks paths given a node sequence, whereas `printPath_es` is used to print networks paths given an edge sequence. The definition is explained in the manual but not in the vignette. I modified the vignette aiming at clarifying this point.

- I commented in the vignette about the clusters algorithms available in the `igraph` package and I included an hyperlink to `igraph` documentation for further information.

**R / man**

As a general comment, I would like to say that you are totally right about the code duplication. However, this package is available in Github since a while and some new features where recently added to the webservice we query. I didn’t want to change names of functions or include some mandatory parameters in functions that were previously available in order to avoid problems for former users. That’s why, in the following points, I tried to get a balance between reduction of duplicated code and modification of previously available functions.

- _dataframe2graph.R:_
	
1. I included a step to check the columns of the input data frame in these functions. 

2. I kept both different functions, but I created an internal function to reduce code duplication. 

- _print_interactions.R:_

1. I replaced `cat` and `print` by `message` when the path is empty.

2. I removed `print` when it was not required, otherwise I replaced it by `message`.

- _import_Omnipath.R:_

1. I removed the starting `.` from the functions (both internal and external)

2. I replaced `print` by `message` as suggested.

3. I created some internal new functions to avoid code duplication. However, I kept separated functions to import the different types of data. I agree that they could be combined in single functions for effeciency, but the `import_Omnipath_PTMS()` and `import_Omnipath_interactions()` functions were always separated in our Github package. I therefore proceed this way thinking on the former users/scripts using the package. 

4. Same than the previous point for the functions getting the different databases.

Best regards,
Alberto.

**Comment by lshep** [comment]
One last comment 

**R/man**
_import\Omnipath.R_
- [ ] remove `paste0` from message calls. not needed


Side note:  We really recommend single functions and avoiding duplication but if you are comfortable leaving them as is I  will make an exception in this case.  
Please keep this this practice in mind with future packages development,  as removing duplicate code where possible helps with debugging, management, and makes code more readable.  Others may insist on it.   


Cheers,

**Comment by alberto-valdeolivas** [comment]
Hello again,

Many thanks again for your comments. I performed the modifications you suggested and bumped a new version.

Yeah, I totally agree with your note and thanks for your understanding.

Cheers, 
Alberto.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alberto-valdeolivas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("OmnipathR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OmnipathR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
