### ISSUE TITLE
target

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/Contributions#1267]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MahShaaban/target

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
DESCRIPTION

- Good

NAMESPACE

-good

Other

- The LICENSE file is not required, as it is distributed with base R

vignette

- really nice, thank you!

R -- comments are on specific lines of code but apply generally

- functions.R:20 I'm not really understanding the purpose of defining `merge_ranges = IRanges::mergeByOverlaps`? It just introduces cognitive load to someone trying to understand your package. I also don't understand why `merge_ranges` is tagged `@export` but documented as 'For internal use only'? (If it is for internal use, and were not exported, I wouldn't be so concerned about the re-definiition).

- functions.R:194 perhaps `vapply()` rather than `unlist(lapply())`?

- it's refereshing to see your clear and well-organized code!

man 

- good

inst/target-app/app.R

- generally this looks very clean. app.R:542 I think relative complicated (computationally) commands like this would be better represented as functions in the package, so that they can be tested / etc independently of the app. They would not necessarily be exported from the package.

- hmm, tutorial/tutorial.md seems a little thin!


tests

- good! thanks.

**Comment by MahShaaban** [comment]
Thanks, @mtmorgan 
* I am aware that the LICENSE file is not required, but I added it so that GitHub recognizes the license type.
* I define `merge_ranges` as it is for two reasons. First, to have a function that corresponds to each step of the algorithm. Second, to have control over the input arguments so that they look similar to those of the other functions.
* Maybe I misused the phrase "for internal use only". What I really meant is that these functions are not called directly by the users to perform the target analysis. I might change this in the docs to be clearer.
* I will change `unlist(apply())` to `vapply()` as suggested.
* I am working on tutorial and will add it to the next push.
* I am working on a version of the app using shiny modules. It needs more time though, so hopefully in a future release.

**Comment by mtmorgan** [comment]
As you say, `merge_ranges()` is not meant to be called by the user. Yet since it is `@export`ed it is visible to the user. Now the user has to decide whether they are going to use `mergeByOverlaps()` or `merge_ranges()` when they want to do an operation like `mergeByOverlaps()`, whether you intended to impose this confusion on the user or not.  Is there a reason not to remove the `@export` tag?

**Comment by mtmorgan** [comment]
Please do as you feel best.

**Comment by MahShaaban** [comment]
I am actually not sure what the next step should be.

**Comment by mtmorgan** [comment]
have you made the changes in the original review, in as much as you are going to make them?

**Comment by MahShaaban** [comment]
Yes. The changes in MahShaaban/target@0b63c9d796da9d474ebf3bb87bb2ff4a2508a2dd are in response to the original review.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MahShaaban.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("target")`. The package 'landing page' will be created at

https://bioconductor.org/packages/target

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
