### ISSUE TITLE
pmp

### ISSUE THREAD

**Issue by andzajan** [Bioconductor/Contributions#1268]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/computational-metabolomics/pmp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by andzajan** [comment]
Note that the pmp packages is a dependency for the structToolbox (#1266).

**Comment by mtmorgan** [comment]
# 26 November, 2019

I'm very sorry that your package did not get added to the review queue.

Please update this package in response to the following comments and to the automatic package build reports. When this package is acceptable, we will add your second contribution as an 'AdditionalPackage', as outlined in https://github.com/Bioconductor/Contributions#submitting-related-packages

DESCRIPTON

- please provide a more informative Title and Description, so that users will be able to distinguish your package from the others on Bioconductor

vignette

- Please provide a vignette outlining how your package is used. This should not be a recapitulation of 'help' pages, but rather walk the user through the data input and analysis steps and scientific insights your package enables. In particular connect your contribution to other opportunities within the Bioconductor ecosystem, illustrating how the inputs and outputs to your package are relevant to other steps in a typical work flow.

R / man (specific comments should be considered generally in your code)

- The 'features in rows / samples in columns' peak matrix validated by `check_peak_matrix()` seems like a [SummarizedExperiment][]. Ensure that your functions (all, e.g., `filter_peaks_by_blank()` work with such standard Bioconductor objects, e.g., by writing an S4 generic with methods for SummarizedExperiment and for a matrix.

- Write functions as _endomorphisms_ that return the same object as the input. For instance `filter_peaks_by_blank()` should return a SummarizedExperiment, perhaps updating the `metadata()` to include flags, or if one wishes to be more ambitious creating a derived class that contains slots to contain flags.

- In the roxygen tags, provide more comprehensive description of input parameters and return values. For instance, indicate the class (numeric()) of `peak_data`.

- Provide better documentation of the `testData` object, for instance describing the steps a user would take to go from the `@source` link to the object in your package. The object is incredibly complicated (36 components) and a decent documentation would describe each element. Perhaps you would rather limit the data to that which is essential for use in your package?

- glog_transformation.R:34 here and elsewhere use more efficient versions than `apply()` on a matrix, e.g., `rowMeans()` or functions from the matrixStats package.

- mv_imputation.R:74 this is an iteration (calling the function as many times as there are rows in the data frame) that should be replaced with a vectorized call (calling functions once on the entire object), e.g.,
```
if (rowSums(is.na(df)) == nrow(df)) {...}
```

[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by andzajan** [comment]
Thank you for your comments, they are very helpful. We are willing to follow your suggestions but as some of it requires quite significant changes it will take a bit of time, so please bear with us.

In the mean time we will make the more minor changes required to get the
build checks to pass so that we can get feedback on structToolbox as well.

**Comment by andzajan** [comment]
# 21 January, 2020
 
>I'm very sorry that your package did not get added to the review queue.
 
 >Please update this package in response to the following comments and to the automatic package build reports. When this package is acceptable, we will add your second contribution as an 'AdditionalPackage', as outlined in https://github.com/Bioconductor/Contributions#submitting-related-packages

Dear Martin, thank you for comprehensive and helpful review. Please see our response below where we did try to address all comments and suggestions.

## DESCRIPTION
 
> * [x] please provide a more informative Title and Description, so that users will be able to distinguish your package from the others on Bioconductor

DESCRIPTION file has been updated.

 ## Vignette
 
> * [x] Please provide a vignette outlining how your package is used. This should not be a recapitulation of 'help' pages, but rather walk the user through the data input and analysis steps and scientific insights your package enables. In particular connect your contribution to other opportunities within the Bioconductor ecosystem, illustrating how the inputs and outputs to your package are relevant to other steps in a typical work flow.

Three vignette documents have been added:
[Peak Matrix Processing for metabolomics data sets](https://github.com/computational-metabolomics/pmp/blob/master/vignettes/peak-matrix-processing.Rmd);
[Signal and batch correction for mass spectrometry](https://github.com/computational-metabolomics/pmp/blob/master/vignettes/signal-batch-correction.Rmd);
[Signal and batch correction, data assesment and correction](https://github.com/computational-metabolomics/pmp/blob/master/vignettes/sbc-data-evaluation-and-algorithm.Rmd).

## R / man (specific comments should be considered generally in your code)

> * [x] The 'features in rows / samples in columns' peak matrix validated by `check_peak_matrix()` seems like a [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment). Ensure that your functions (all, e.g., `filter_peaks_by_blank()` work with such standard Bioconductor objects, e.g., by writing an S4 generic with methods for SummarizedExperiment and for a matrix.

All exported functions of `pmp` package are using `SummarizedExperiment` object as the main data structure. Instead of writing S4 generics we opted to provide several utility functions to handle checks on input/output structures.
- Function [check_peak_matrix](https://github.com/computational-metabolomics/pmp/blob/master/R/checkPeakMatrix.R#L27-L56) is used to: 
  -  check if all values are `numeric()` ;
  - if input data need to be transposed, so that samples are in columns and features in rows;
  - if class labels are provided checks if the length is the same as in data matrix.
 - Function [check_input_data](https://github.com/computational-metabolomics/pmp/blob/master/R/checkPeakMatrix.R#L70-L89) is used to check what R data structure input object is, and converts it to `SummarizedExperiment` if needed.
 - Function [return_original_data_structure](https://github.com/computational-metabolomics/pmp/blob/master/R/checkPeakMatrix.R#L105-L127) is used that all function act as _endomorphisms_, as recommenced to be implemented in the section below.

> * [x] Write functions as _endomorphisms_ that return the same object as the input. For instance `filter_peaks_by_blank()` should return a SummarizedExperiment, perhaps updating the `metadata()` to include flags, or if one wishes to be more ambitious creating a derived class that contains slots to contain flags.

As described above we have implemented several functions to handle input/output data structures. `metaData()`, `colData()` and `rowData()` functionality of  `S4Vecotrs` and `SummarizedExperiment` are used to handle processing flags.
Function [return_function_args](https://github.com/computational-metabolomics/pmp/blob/master/R/utils.R#L5-L14) is used to extract argument values of each function call to be be appended to `metaData()` slot of output data object as `processing_history`.

> * [x] In the roxygen tags, provide more comprehensive description of input parameters and return values. For instance, indicate the class (numeric()) of `peak_data`.

All documentation entries have been updated. 

> * [x] Provide better documentation of the `testData` object, for instance describing the steps a user would take to go from the `@source` link to the object in your package. The object is incredibly complicated (36 components) and a decent documentation would describe each element. Perhaps you would rather limit the data to that which is essential for use in your package?

Object `testData` is only used for function unit tests with testthat, it has been moved to internal `sysdata.Rda` file and is not exported anymore. We have added full data set of the same data `MTBLS79`. Steps used to create corresponding `SummarizedExperiment` object are provided in help page of [MTBLS79](https://github.com/computational-metabolomics/pmp/blob/master/R/data.R#L29-L59) object. 

>* [x] glog_transformation.R:34 here and elsewhere use more efficient versions than `apply()` on a matrix, e.g., `rowMeans()` or functions from the matrixStats package.

Where possible all `apply` calls are replaced with faster alternatives. 
Relevant Github commits: 
* [19524f71](https://github.com/computational-metabolomics/pmp/commit/19524f71dbfe6c9ffe3d229dca3e46a51e19c60a);
 * [2736e5571](https://github.com/computational-metabolomics/pmp/commit/2736e557130c9aefe5ab25e3b228c321ecb06a82) ;
 * [483b3c27](https://github.com/computational-metabolomics/pmp/commit/483b3c27a68d3389a1e25c7b45f0fcf1c15b3b92);
* [04501eaa](https://github.com/computational-metabolomics/pmp/commit/04501eaa101c086261a0bb2fcb878b3fa07c1ec1).

> * [x] mv_imputation.R:74 this is an iteration (calling the function as many
 times as there are rows in the data frame) that should be replaced with a vectorized call (calling functions once on the entire object), e.g.,
>`if (rowSums(is.na(df)) == nrow(df)) {...}`

Fixed in [9b28636](https://github.com/computational-metabolomics/pmp/commit/9b28636b902d902d9063c5ce1955c25bf30cec89)

We have moved all functions from previously submitted [sbcms](https://github.com/Bioconductor/Contributions/issues/1269) package to the function base of `pmp`.  In our opinion QCRSC algorithm for signal batch effect correction for mass 
   spectrometry data sets fits very well with general scope of `pmp` package. 
 `QCRSC` and related functions are utilising "SummarizedExperiment" object and other `pmp` functions as demonstrated in corresponding vignettes:
[Signal and batch correction for mass spectrometry](https://github.com/computational-metabolomics/pmp/blob/master/vignettes/signal-batch-correction.Rmd);
[Signal and batch correction, data assesment and correction](https://github.com/computational-metabolomics/pmp/blob/master/vignettes/sbc-data-evaluation-and-algorithm.Rmd).

**Comment by andzajan** [comment]
Dear @mtmorgan , I did fix Warnings on Windows build from yesterday commit. And it looks that today's build "ERROR" originates from your build system and is not related to the package itself. Do I need to take any further action?

```
* Checking for bioc-devel mailing list subscription...
    Maintainer is subscribed to bioc-devel.
* Checking for support site registration...
Error in if (suppressMessages(content(response))) { : 
  argument is not interpretable as logical
Calls: <Anonymous> -> BiocCheck -> checkForSupportSiteRegistration
Execution halted
```

**Comment by mtmorgan** [comment]
thanks for the changes; no need to address today's problem. I'll take a detailed look at your  revisions later today.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/andzajan.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pmp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pmp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
