### ISSUE TITLE
biscuiteerData

### ISSUE THREAD

**Issue by jamorrison** [Bioconductor/Contributions#1270]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/trichelab/biscuiteerData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jamorrison** [comment]
AdditionalPackage: https://github.com/trichelab/biscuiteer

**Comment by jamorrison** [comment]
Mentioning @ttriche to look at package.

**Comment by jamorrison** [comment]
Hi @nturaga biscuiteerData and biscuiteer are ready to be reviewed. Let me know what elements I need to change. Thank you.

**Comment by lshep** [comment]
Sorry for the delay -  I will be taking over the review for now -  I am currently looking at the packages and will post feedback within the next few hours

**Comment by lshep** [comment]
Thank you for your submission please see initial comments below: 

# Data package 

**README**

- [ ] We would recommend still showing Bioconductor installation instructions

**NEWS**

- [ ] Please see `?news` for formatting. Namely the section headers should be
  `changes in version x.y.z` and not include the package name. 

**DESCRIPTION**

- [ ] We recommend removing `lazyData: true`. We have rarely found this useful
  and actually have found it can slow installation of packages. 

**R/man**

_data.R_

- [ ] Could you include source information in the man files. Along with some
  indication of the format of the data. (ie. return type is a GRange object,
  etc)




# Software package

**Build report**

- [ ] Please fix global variable and function NOTES
- [ ] Please fix coding practice NOTES


**README**

- [ ] We would recommend still showing Bioconductor installation instructions

**NEWS**

- [ ] Please see `?news` for formatting. Namely the section headers should be
  `changes in version x.y.z` and not include the package name. 

**LICENSE**

- [ ] This file isn't needed since GPL-3 listed in description is distributed
  with base R. This should also fix the NOTE in the build report. 

**test**

- [ ] Remove these and replace with real tests. "tricking" the system with
  placeholders is not acceptable. 

**inst**

- [ ] Include an inst/script directory that describes the source information and
  any preprocessing for the data in inst/extdata

**Clarification**

- [ ] You still include a lot of data with the package in data and
  inst/extdata. Is all this necessary since you uploaded data in the hub? 


**Vignette**

- [ ] I would suggest shorting to just biscuiteer rather than
  biscuiteer_vignette as it is much more intuitive for a user to type
  `vignette("biscuiteer")`


-[ ] section 2.3 while it is quick, it seems like wasted effort to recreate the
 object you just did in the previous section. perhaps only create the new second
 object to show combining. 

- [ ] the results of getLogitFracMeth should be a GRanges object as it expresses
  genomic positioning information. Also the idea that functions should be as
  endomorphic as possible is a standard best practice. 

- [ ] Where appropriate (meth, coefs, etc) the objects that make up the result
  list of WGBSage should be converted to GRanges. 

- [ ] While you use a `show` the ERROR when the results from trying to view the
  results of bisc.CpGindex should be corrected if possible as I feel most (esp. naive) users
  will try to investigate the object by the following:

```
> bisc.CpGindex
CpGindex with 1 row and 3 columns
    hyper.MCF7_Cunha   hypo.MCF7_Cunha ratio.MCF7_Cunha
           <numeric>         <numeric>        <numeric>
1 0.0690734126984127 0.199261516805161 0.34664702851757
  -------
This object is just a DataFrame that has an idea of where it came from:
Error in as.vector(x, mode = "character") : 
  no method for coercing this S4 class to a vector

```


**R / man**

_WGVSage.R_

- [ ] As mentioned above objects in results that can be expressed as a GRanges
  object should. 
- [ ] Do /should the other parameters be checked for correct input? ie. 
  `stopifnot(is.logical(useENSR))`  etc ? 

_atRegions.R_

- [ ] Output should be converted to GRanges

_binCoverage.R_

- [ ] We really don't like seeing FIXME in code. These seem more like
  TODOs. (and very good TODOs)
- [ ] Should there be parameter checking on which, QDNAseq, or readLen? 

_biscuitMetadata.R_
- [ ] dont call a function two different names. Choose one and export it. you
can reference different alias in the man file without explicitly exporting
functions of different names. 

_byExtremality.R_

- [ ] convert output to GRanges or GRangeList
- [ ] remove paste0 in stop call. unnecessary


_checkBiscuitBED.R_

- [ ] Might want to expand man page with details on what backing up with hdf5 or
  what a sparse matrix is. Or at least include links for more info. 
- [ ] no need to create variable err_message if it is returned right away in a
  `stop`. Just place right in stop call.
- [ ] remove paste0 from message and stop calls. 
- [ ] despite having an argument for `how` you compute the values of `colSpecs`
  for readr and `colClassses` for data.table.  Shouldn't only the specified
  `how` be done and stored. Otherwise whats the point of asking? 


_data.R_

- [ ] Expand on the documentation including source and format information. 


_extremality.R_

- [ ] We never really like to see FIXME in code.  This bug should be fixed
  before releasing. 

_fexpit.R_

- [ ] Will this really be useful to a user and need to be exported?
- [ ] Why can't this be written in one line and returned?


_filterLoci.R_

- [ ] Include argument parameter checking

_fixNA.R_

- [ ] sparse seems like a mis-leading entry. TRUE/FALSE both return a matrix
  object just a matter of what kind. 

_flogit.R_

- [ ] Is this really useful to the user to export?

_getLogitFracMeth.R_

- [ ] the results of getLogitFracMeth should be a GRanges object as it expresses
  genomic positioning information. Also the idea that functions should be as
  endomorphic as possible is a standard best practice. 
- [ ] not recommended to have two functions doing the same thing. You can alias different names in the man file but dont export both. 



_loadHDF5.R_

- [ ] Why is this needed and not just directed to the HDF5Array function when
  necessary?

_read.biscuit.R_

- [ ] Seems odd that this is the only function that has a `.` in the name. A dot
  typically indicates S3 dispathch which this really isn't. Would recommend
  removing and using camelcase instead. 
- [ ] don't create extra variable err_message if it is returned in the next
  line. Put the message directly into `stop` call. 
- [ ] not recommended to have two functions doing the same thing. choose read or
  load but don't export both. You can alias different names in the man file but
  dont export both. 

_saveHDF5.R_

- [ ] Why is this needed and not just directed to the HDF5Array function when
  necessary?


Please revise the packages according to above.  When ready please comment here summarizing the changes.  Please also remember to do a version bump to trigger a new build report and ping me in a message indicating you are ready for another review. 

Cheers!

**Comment by jamorrison** [comment]
Hi @lshep I wanted to let you know that I started making changes based on the corrections you requested. I will have those done early next week and answer any clarifications at that point.

**Comment by jamorrison** [comment]
Hi @lshep I have addressed the comments you made in your review. Please see below for responses.

# Data package
**README**

* [x]  We would recommend still showing Bioconductor installation instructions - _added_

**NEWS**

* [x]  Please see `?news` for formatting. Namely the section headers should be
  `changes in version x.y.z` and not include the package name. - _reformatted_

**DESCRIPTION**

* [x]  We recommend removing `lazyData: true`. We have rarely found this useful
  and actually have found it can slow installation of packages. - _removed, will keep this in mind for
  future package submissions_

**R/man**

_data.R_

* [x]  Could you include source information in the man files. Along with some
  indication of the format of the data. (ie. return type is a GRange object,
  etc) - _source information/return type added_

# Software package
**Build report**

* [x]  Please fix global variable and function NOTES - _fixed_
* [x]  Please fix coding practice NOTES - _fixed_

**README**

* [x]  We would recommend still showing Bioconductor installation instructions - _added_

**NEWS**

* [x]  Please see `?news` for formatting. Namely the section headers should be
  `changes in version x.y.z` and not include the package name. - _reformatted_

**LICENSE**

* [x]  This file isn't needed since GPL-3 listed in description is distributed
  with base R. This should also fix the NOTE in the build report. - _removed_

**test**

* [x]  Remove these and replace with real tests. "tricking" the system with
  placeholders is not acceptable. - _my apologies, I have added one test for the time being and will
  add more as the package matures_

**inst**

* [x]  Include an inst/script directory that describes the source information and
  any preprocessing for the data in inst/extdata - _directory and scripts added to describe extdata, a
  script was also added to show how some of the files in the data directory were created (to go with
  the comments on data.R)_

**Clarification**

* [x]  You still include a lot of data with the package in data and
  inst/extdata. Is all this necessary since you uploaded data in the hub? - _Some of the final
  functionality of biscuiteer is still being worked out, so we are unsure which datasets will be
  needed. Once this decision has been made, we will either remove the data entirely, or move it to
  the hub._

**Vignette**

* [x]  I would suggest shorting to just biscuiteer rather than
  biscuiteer_vignette as it is much more intuitive for a user to type
  `vignette("biscuiteer")` - _vignette name changed to biscuiteer.Rmd_

* [x] section 2.3 while it is quick, it seems like wasted effort to recreate the object you just did in
  the previous section. perhaps only create the new second object to show combining. - _removed
  repeat creation of first object_

* [x]  the results of getLogitFracMeth should be a GRanges object as it expresses
  genomic positioning information. Also the idea that functions should be as
  endomorphic as possible is a standard best practice. - _getLogitFracMeth returns a GRanges now_
* [x]  Where appropriate (meth, coefs, etc) the objects that make up the result
  list of WGBSage should be converted to GRanges. - _Combined meth and coefs into one GRanges
  object that is included in the output list_
* [x]  While you use a `show` the ERROR when the results from trying to view the
  results of bisc.CpGindex should be corrected if possible as I feel most (esp. naive) users
  will try to investigate the object by the following: - _fixed_

```
> bisc.CpGindex
CpGindex with 1 row and 3 columns
    hyper.MCF7_Cunha   hypo.MCF7_Cunha ratio.MCF7_Cunha
           <numeric>         <numeric>        <numeric>
1 0.0690734126984127 0.199261516805161 0.34664702851757
  -------
This object is just a DataFrame that has an idea of where it came from:
Error in as.vector(x, mode = "character") : 
  no method for coercing this S4 class to a vector
```

**R / man**

_WGBSage.R_

* [x]  As mentioned above objects in results that can be expressed as a GRanges
  object should. - _see above_
* [x]  Do /should the other parameters be checked for correct input? ie.
  `stopifnot(is.logical(useENSR))`  etc ? - _added parameter checks_

_atRegions.R_

* [x]  Output should be converted to GRanges - _output converted_

_binCoverage.R_

* [x]  We really don't like seeing FIXME in code. These seem more like
  TODOs. (and very good TODOs) - _changed to TODOs_
* [x]  Should there be parameter checking on which, QDNAseq, or readLen? - _added parameter
  checks_

_biscuitMetadata.R_

* [x]  dont call a function two different names. Choose one and export it. you
  can reference different alias in the man file without explicitly exporting
  functions of different names. - _biscuitMetadata is the only exported function now_

_byExtremality.R_

* [x]  convert output to GRanges or GRangeList - _converted_
* [x]  remove paste0 in stop call. unnecessary - _removed_

_checkBiscuitBED.R_

* [x]  Might want to expand man page with details on what backing up with hdf5 or
  what a sparse matrix is. Or at least include links for more info. - _extra description added_
* [x]  no need to create variable err_message if it is returned right away in a
  `stop`. Just place right in stop call. - _moved string into stop call_
* [x]  remove paste0 from message and stop calls. - _done_
* [x]  despite having an argument for `how` you compute the values of `colSpecs`
  for readr and `colClassses` for data.table.  Shouldn't only the specified
  `how` be done and stored. Otherwise whats the point of asking? - _now uses `how` to choose
  which values to create_

_data.R_

* [x]  Expand on the documentation including source and format information. - _added source and
  return information_

_extremality.R_

* [x]  We never really like to see FIXME in code.  This bug should be fixed
  before releasing. - _since the DelayedArray functionality is currently experimental, I added an
  error message to cover the instance mentioned in the FIXME. When DelayedArray/HDF5-backing 
  is fully implemented, this will be dealt with properly_

_fexpit.R_

* [x]  Will this really be useful to a user and need to be exported? - _not exported anymore_
* [x]  Why can't this be written in one line and returned? - _While it could be written in one line, it
  is easier to read and maintain when split over multiple lines._

_filterLoci.R_

* [x]  Include argument parameter checking - _included_

_fixNA.R_

* [x]  sparse seems like a mis-leading entry. TRUE/FALSE both return a matrix
  object just a matter of what kind. - _parameter name changed to sparseMatrix_

_flogit.R_

* [x]  Is this really useful to the user to export? - _not exported anymore_

_getLogitFracMeth.R_

* [x]  the results of getLogitFracMeth should be a GRanges object as it expresses
  genomic positioning information. Also the idea that functions should be as
  endomorphic as possible is a standard best practice. - _see above_
* [x]  not recommended to have two functions doing the same thing. You can alias different names
  in the man file but don't export both. - _only getLogitFracMeth is exported now_

_loadHDF5.R_

* [x]  Why is this needed and not just directed to the HDF5Array function when
  necessary? - _removed_

_read.biscuit.R_

* [x]  Seems odd that this is the only function that has a `.` in the name. A dot
  typically indicates S3 dispathch which this really isn't. Would recommend
  removing and using camelcase instead. - _changed to readBiscuit_
* [x]  don't create extra variable err_message if it is returned in the next
  line. Put the message directly into `stop` call. - _moved_
* [x]  not recommended to have two functions doing the same thing. choose read or
  load but don't export both. You can alias different names in the man file but
  dont export both. - _only readBiscuit is exported now_

_saveHDF5.R_

* [x]  Why is this needed and not just directed to the HDF5Array function when
  necessary? - _removed_

Let me know if you have further requests for changes to be made.

**Comment by lshep** [comment]
Thank you. I have no further comments at this time.  I look forward to seeing the future developments of this package as well. 
Cheers,

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jamorrison.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biscuiteerData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biscuiteerData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jamorrison.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biscuiteer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biscuiteer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
