### ISSUE TITLE
SAIGEgds

### ISSUE THREAD

**Issue by zhengxwen** [Bioconductor/Contributions#1275]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhengxwen/SAIGEgds

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment]
Hi Xiuwen @zhengxwen ,

Thanks for this new contribution. It's in great shape and will be a valuable addition to Bioconductor. A few minor points:

- When using `system.file()`, don't place hardcoded `/` in the path as this is not cross-platform compatible. For example, instead of
    ```
    system.file("extdata/grm1k_10k_snp.gds", package="SAIGEgds")
    ```
    please use
    ```
    system.file("extdata", "grm1k_10k_snp.gds", package="SAIGEgds")
    ```

- You mention "the SAIGE paper" in some of your man pages but it is not immediately obvious that the reference you provide in the `\references` section of the man page is actually the reference to this paper. I'm actually not even sure that it is (and I shouldn't have to look up the reference in order to try to find out).

- `pkg_vignette` is not a good name for a vignette because it makes it a little bit harder than necessary to find it. Here is why:

    Typically users will try `vignette("SAIGEgds")` with the hope that it works. If it fails, some users might not necessarily know what to do, or they might even conclude that the package has no vignette. More savvy users (or people that take the time to consult `?vignette`) will know that they can get the list of vignettes with `vignette(package="SAIGEgds")` so they will eventually find out that they can open the vignette with `vignette("pkg_vignette")`.
    On the other hand if you name your vignette like your package (`SAIGEgds`), everybody will be happier.

- Installing Bioconductor packages directly from GitHub can easily lead to dependencies problems and/or version mismatches, so is generally not a good idea. Besides, almost nobody should ever need to do that. So we should not encourage it. Please either remove the instructions of how to install the development version of the package from GitHub from the vignette, or make it clear that this is for developers/testers only. Also please note that, like the `install_github()` approach, the standard approach (i.e. `BiocManager::install()`) also requires that you build from source if you are on Linux.

Regards,
H.

**Comment by zhengxw-ab** [comment]
Changes in v0.99.2:
* `system.file()`: remove `/`
* add `[Zhou et al. 2018]` (following the SAIGE paper)
* rename `vignettes/pkg_vignette.Rmd` to `vignettes/SAIGEgds.Rmd`
* remove `Installing Bioconductor packages from GitHub`

Best wishes,

Xiuwen

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhengxwen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SAIGEgds")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SAIGEgds

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
