### ISSUE TITLE
methrix

### ISSUE THREAD

**Issue by PoisonAlien** [Bioconductor/Contributions#1276]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CompEpigen/methrix

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by tkik** [comment]
Dear @lshep,
It seems that the error we are getting is caused by our package being dependent on the data.table version 1.12.4, which was released only on 3. October and is not yet in BioC's build systems. Can we do anything to address the error, or should we just wait?

**Comment by lshep** [comment]
I believe it should have 1.12.4 now installed.  I'm kicking off a manual build and hopefully it should pick it up.

**Comment by tkik** [comment]
Dear @lshep,

The recent build report only shows an error here:
** running examples for arch 'i386' ... ERROR
I am not sure why I am getting this error, because this part ran without a problem before and I didn't change anything here. Could you please take a look? 
Thank you!

**Comment by tkik** [comment]
Dear @lshep, 
Could you please take a look? It seems to me that the error is not related to our package: 
* Checking for bioc-devel mailing list subscription...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [stat.ethz.ch] SSLRead() return error -9806
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous>

Should I do a version bump to start a new build?
Thank you! 

Best, 
Reka

**Comment by lshep** [comment]
This is an ERROR on our end.  No need to kick off a new build.   I will take a look at the package and post a review shortly.   In the meantime please try to clean up all the NOTES in the build report - esp the global variable/functions and the coding practice NOTES.

**Comment by tkik** [comment]
Thanks! I cleaned the notes as much as possible. I will wait for your review and commit the changes together.

**Comment by lshep** [comment]
Please see the following review: 


**build report**
- [ ] Please fix global variable/function
- [ ] Rd line lengths
- [ ] Coding practices
- [ ] We really recommend having some basic unit tests. 
- [ ] What is the reasoning behind not having runnable examples in exported
functions?
- [ ] Are the dontruns run some other place (vignette or test?) all function
unless strong reasoning should be run at least once. If they are run elsewhere
than this is okay (ish). Looking at the vignette these are all `eval=FALSE` I
would prefer to see the vignette `eval=TRUE` and have the vignette run in its
entireity - then leaving these to dontrun are okay because of time constraint. 


**README**
- [ ] Because I noticed your badges.  We recommend packages only get submitted
  to CRAN or Bioconductor and not both but you have the badges for both. What is
  your intention here? 
  We have talked with CRAN about this and our reasoning is often maintainers
  than will update one but not the other; causing multiple 'current' versions to
  be out to the universe. 
- [ ] You list functions multiple times in Methrix operations


**LICENSE/LICENSE.md**
- [ ] Remove LICENSE.md file. This is already included with the base R
distribution. Keep LICENSE file. 


**DESCRIPTION**
- [ ] In our experience we don't recommend including `LazyData: true` as it can
slow installation of the package. 


**inst/**
- [ ] Please include an `inst/script` diectory that describes where or how the
data in `inst/extdata` was curated/generated. This should include basic source
information. 
- [ ] It seems like `summarize_metrix.Rmd` should either be moved to another
vignette or included as `inst/doc` 

 
**vignette**
- [X] I like the overview graph. Thank you for including it!
- [ ] A LOT of `eval=FALSE` this is not recommended. Run the vignette
interactively. All functions should be run once somewhere unless a very good
argument otherwise. I recommend running these beginning sections with
`eval=TRUE`
- [ ] Remove SNPs. We would recommend using `BiocManager::install` rather than
`install.packages` esp since these are Bioconductor packages the repos might not
be set correctly relying on CRAN.
- [ ] When I try to run the remove snps code I get an ERROR
```
> meth_snps_filtered = methrix::remove_snps(m = meth)
Used SNP database: MafDb.1Kgenomes.phase3.hs37d5. 
Error in .scores_snrs(x, ranges, pop, summaryFun, quantized, scores.only,  : 
  Sequence names M in 'ranges' not present in reference genome hs37d5.

```
- [ ] Is this filtering snps an optional step?  
- [ ] I suggeset reformting this section slightly. Show that you can install the
needed packages through Bioconductor with the code to install in `eval=FALSE`
but then have the code section that actually runs the function call with the
assumption that the packages are available 
```
library(GenomicScores)
library(MafDb.1Kgenomes.phase3.hs37d5)
meth_snps_filtered = methrix::remove_snps(m = meth)
```
- [ ] Remove the manually added 'output'
- [ ] in section remove uncovered loci.  why is this in an `eval=FALSE`? Run
interactively and remove the manually added 'output'

- [ ] `meth_mat_with_loci = methrix::get_matrix(m = methrix_data, type = "M",
  add_loci = TRUE)` The results of this really are a GRanges object.  Do you
  have a wrapper or show the code to conver into a standard GRanges object. 
- [ ] Subset by genomic regions. Show subsetting by GRanges object. hint:
  `GRanges("chr21:27867971-27868103")`

- [ ] in section 'converting methrix to BSeq' . Again we prefer to see
  `BiocManager::install` rather than `install.package` instructions. This code
  should be in an `eval=FALSE` and then show the code to run
```
library(bsseq)
bs_seq = methrix::methrix2bsseq(m = methrix_data)

```


**R / man**

**General and should be applied to all files**
- [ ] Remove commentted out code chunks. True comments in code are fine but
remove legacy code
- [ ] Use `<-` rather than `=` except for argument assignment. 
- [ ] use `message` instead of `cat` so they can be suppressed if the user wants


_accessory\_funcs.R_
- [ ] has parameter checking been done previous to this point in the code?
- [ ] Remove older implementation (the beauty of git tracking is you can always
find and revert the commit removing this code)

_check\_bins.R_
- [ ] These functions do the same thing. combined into one function that checks
bedtools/bedGraphToBigWig/bedClip based on a second argument. 
something along the lines:
```
check_bins <- function(path=NULL, value=c("bedtools", "bedGraphToBigWig",
"bedClip")){

names = match.arg(value)
if(is.null(path)){
    check = as.character(Sys.which(names = names))[1]
  }else{
    check = paste0(path, "/", names")
    if(!file.exists(check)){
      stop("Could not locate ", names, " at " , check ,"\nDownload: <http://hgdownload.cse.ucsc.edu/admin/exe/>")
    }
  }

  if(check != ""){
    return(check)
  }else{
    stop("Could not locate ", names, " at " , check ,"\nDownload: <http://hgdownload.cse.ucsc.edu/admin/exe/>")
  }
}


```

_extract\_CpGs.R_
- [ ] Remove unneeded paste0 in message call. 
- [ ] `if(nrow(gnoms_installed[pkgname %in% ref_genome]) == 0){`  seems like it
won't work as pkgname is not defined anywhere? 
- [ ] While I appreciate the humor, I would not recommend the `bored = TRUE` to
tell a joke from the Chuck Norris Database.  For a number of reasons, starting
with it adds a layer of complexity and an additional packages dependency that
would otherwise be unneeded.  Being a publicallly open space, the fact they can
be explicit is also discouraged.  
- [ ] cpgs in the list should remain a GRanges object not flattened to a
table. Any place this is used should utilize GRanges.  
- [ ] message instead of cat

_matrix-plot.R_
- [ ] Have more argument checking. For example - There is no check on the ranges
if it is not null if it is a GRanges object or if it has the required
columns. Unless this is handled by subset\_matrix?  But this sort of thinking
that the data provided is the right class/structure to all (or many of the
important arguments) should be checked. 
- [ ] Duplicate code should be pulled into its own helper function. Lines 16-59
in the violin plot are the same as 93-132 of the density plot 
- [ ] FWIW - it seems like this file should be methrix\_plot to be consistent
with all the other files instead of a dash. 



_methrix\_operations.R_

- [ ] check if argument/parameter checking is necessary for any user input. 


_mm9\_bsmap.R_
- [ ] It appears this was removed so please also remove the documentation file.


_read\_bedgraphs.R_
- [ ] Remove TODO.  Make sure this works or fix it! 
- [ ] so it is okay to leave chr_idx, start_idx, etc... NULL as there is no
default set


Thank you for the submission.  Please work on the above changes.  When ready please version bump to kick off a new build and comment back here that you are ready for a re-review and a summary of the changes.

**Comment by tkik** [comment]
Dear @lshep, 
Thank you for the review and your detailed explanations. I modified our package according to your recommendations. I hope we can still make it to the autumn release. See the detailed answer below:

> Please see the following review:
> 
> **build report**
> 
> * [x]  Please fix global variable/function
> * [x]  Rd line lengths
> * [x]  Coding practices – **Significantly reduced the too long lines and wrong intends. The remaining long rows doesn’t “look good”, when split.**
> * [ ]  We really recommend having some basic unit tests. **.- In progress, I will commit them ASAP**
> * [x]  What is the reasoning behind not having runnable examples in exported
>   functions? **– As you say later, basic time constraint. We use a small dataset as an example, but since some of the functions (read_bedgraph) works with the whole genome, irrespective of the example size, it takes relatively long. Therefore, according to your suggestion, I let them run in the vignette, where I set all of them to eval=TRUE.** 
> * [x]  Are the dontruns run some other place (vignette or test?) all function
>   unless strong reasoning should be run at least once. If they are run elsewhere
>   than this is okay (ish). Looking at the vignette these are all `eval=FALSE` I
>   would prefer to see the vignette `eval=TRUE` and have the vignette run in its
>   entireity - then leaving these to dontrun are okay because of time constraint.
**> See the previous answer.** 
> **README**
> 
> * [x]  Because I noticed your badges.  We recommend packages only get submitted
>   to CRAN or Bioconductor and not both but you have the badges for both. What is
>   your intention here? **– I deleted the CRAN badge.** 
>   We have talked with CRAN about this and our reasoning is often maintainers
>   than will update one but not the other; causing multiple 'current' versions to
>   be out to the universe.
> * [x]  You list functions multiple times in Methrix operations
> 
> **LICENSE/LICENSE.md**
> 
> * [x]  Remove LICENSE.md file. This is already included with the base R
>   distribution. Keep LICENSE file.
> 
> **DESCRIPTION**
> 
> * [x]  In our experience we don't recommend including `LazyData: true` as it can
>   slow installation of the package.
> 
> **inst/**
> 
> * [x]  Please include an `inst/script` diectory that describes where or how the
>   data in `inst/extdata` was curated/generated. This should include basic source
>   information. **I added the `data.generation.R` to the script folder. It seems that the underlying data changed since the first generation, therefore the `methrix_data` changed slightly.** 
> * [x]  It seems like `summarize_metrix.Rmd` should either be moved to another
>   vignette or included as `inst/doc` – The `summarize_methrix.Rmd` function is needed to generate a report. I moved it to `inst/report`.
> 
> **vignette**
> 
> * [x]  I like the overview graph. Thank you for including it!
> * [x]  A LOT of `eval=FALSE` this is not recommended. Run the vignette
>   interactively. All functions should be run once somewhere unless a very good
>   argument otherwise. I recommend running these beginning sections with
>   `eval=TRUE` **See above.**
> * [x]  Remove SNPs. We would recommend using `BiocManager::install` rather than
>   `install.packages` esp since these are Bioconductor packages the repos might not
>   be set correctly relying on CRAN.
> * [x]  When I try to run the remove snps code I get an ERROR
> 
> ```
> > meth_snps_filtered = methrix::remove_snps(m = meth)
> Used SNP database: MafDb.1Kgenomes.phase3.hs37d5. 
> Error in .scores_snrs(x, ranges, pop, summaryFun, quantized, scores.only,  : 
>   Sequence names M in 'ranges' not present in reference genome hs37d5.
> ```
> **– fixed, the functions were in the wrong order.** 
> * [x]  Is this filtering snps an optional step? **– Yes, it is. It depends on the genome that is used, it is usually done only on human data.** 
> * [x]  I suggeset reformting this section slightly. Show that you can install the
>   needed packages through Bioconductor with the code to install in `eval=FALSE`
>   but then have the code section that actually runs the function call with the
>   assumption that the packages are available
> 
> ```
> library(GenomicScores)
> library(MafDb.1Kgenomes.phase3.hs37d5)
> meth_snps_filtered = methrix::remove_snps(m = meth)
> ```
> 
> * [x]  Remove the manually added 'output'
> * [x]  in section remove uncovered loci.  why is this in an `eval=FALSE`? Run
>   interactively and remove the manually added 'output'
> * [x]  `meth_mat_with_loci = methrix::get_matrix(m = methrix_data, type = "M", add_loci = TRUE)` The results of this really are a GRanges object.  Do you
>   have a wrapper or show the code to conver into a standard GRanges object. **– I added the option in_granges to the `get_matrix` function to get a Granges output.** 
> * [x]  Subset by genomic regions. Show subsetting by GRanges object. hint:
>   `GRanges("chr21:27867971-27868103")`
> * [x]  in section 'converting methrix to BSeq' . Again we prefer to see
>   `BiocManager::install` rather than `install.package` instructions. This code
>   should be in an `eval=FALSE` and then show the code to run
> 
> ```
> library(bsseq)
> bs_seq = methrix::methrix2bsseq(m = methrix_data)
> ```
> 
> **R / man**
> 
> **General and should be applied to all files**
> 
> * [x]  Remove commentted out code chunks. True comments in code are fine but
>   remove legacy code
> * [x]  Use `<-` rather than `=` except for argument assignment.
> * [x]  use `message` instead of `cat` so they can be suppressed if the user wants
> 
> _accessory_funcs.R_
> 
> * [x]  has parameter checking been done previous to this point in the code? - **Yes, these are only internal functions, the parameter checking is in other functions.** 
> * [x]  Remove older implementation (the beauty of git tracking is you can always
>   find and revert the commit removing this code)
> 
> _check_bins.R_
> 
> * [x]  These functions do the same thing. combined into one function that checks
>   bedtools/bedGraphToBigWig/bedClip based on a second argument.
>   something along the lines:
> 
> ```
> check_bins <- function(path=NULL, value=c("bedtools", "bedGraphToBigWig",
> "bedClip")){
> 
> names = match.arg(value)
> if(is.null(path)){
>     check = as.character(Sys.which(names = names))[1]
>   }else{
>     check = paste0(path, "/", names")
>     if(!file.exists(check)){
>       stop("Could not locate ", names, " at " , check ,"\nDownload: <http://hgdownload.cse.ucsc.edu/admin/exe/>")
>     }
>   }
> 
>   if(check != ""){
>     return(check)
>   }else{
>     stop("Could not locate ", names, " at " , check ,"\nDownload: <http://hgdownload.cse.ucsc.edu/admin/exe/>")
>   }
> }
> ```
> 
> _extract_CpGs.R_
> 
> * [x]  Remove unneeded paste0 in message call.
> * [x]  `if(nrow(gnoms_installed[pkgname %in% ref_genome]) == 0){`  seems like it
>   won't work as pkgname is not defined anywhere?
> * [x]  While I appreciate the humor, I would not recommend the `bored = TRUE` to
>   tell a joke from the Chuck Norris Database.  For a number of reasons, starting
>   with it adds a layer of complexity and an additional packages dependency that
>   would otherwise be unneeded.  Being a publicallly open space, the fact they can
>   be explicit is also discouraged.
> * [ ]  cpgs in the list should remain a GRanges object not flattened to a
>   table. Any place this is used should utilize GRanges. **– Here extracting cpgs is just a step in reading in the bedgraph files. It the read_bedgraph function we use the cpgs as a data.table, therefore it seems easier, if the outcome of this is a data.table. I would rather not change it, as long as it is absolutely necessary.** 
> * [x]  message instead of cat
> 
> _matrix-plot.R_
> 
> * [x]  Have more argument checking. For example - There is no check on the ranges
>   if it is not null if it is a GRanges object or if it has the required
>   columns. Unless this is handled by subset_matrix?  But this sort of thinking
>   that the data provided is the right class/structure to all (or many of the
>   important arguments) should be checked.  **– Yes, some of it is taken care by the `subset_matrix` function, but I also added additional argument checking.** 
> * [x]  Duplicate code should be pulled into its own helper function. Lines 16-59
>   in the violin plot are the same as 93-132 of the density plot **– extracted into a separate function**
> * [x]  FWIW - it seems like this file should be methrix_plot to be consistent
>   with all the other files instead of a dash.
> 
> _methrix_operations.R_
> 
> * [x]  check if argument/parameter checking is necessary for any user input. – Added additional argument checking
> 
> _mm9_bsmap.R_
> 
> * [x]  It appears this was removed so please also remove the documentation file.
> 
> _read_bedgraphs.R_
> 
> * [x]  Remove TODO.  Make sure this works or fix it!
> * [x]  so it is okay to leave chr_idx, start_idx, etc... NULL as there is no
>   default set **- yes, it is ok.** 
> 
 
I will commit unit tests very soon. Please let me know if you have any more concerns. Thank you for your help!

**Comment by lshep** [comment]
Thank you.  Last few clean up items before acceptance: 

**vignette**

- [ ] The only other code chunk that really should have a eval=FALSE is the one that
  tries to install the packages. So these lines at the top should be in an eval=FALSE.  It seems like all other instances in the vignette are correct. 

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if(!requireNamespace("BSgenome.Hsapiens.UCSC.hg19")) {
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
}

```


**R / man**

_check\_bins.R_
- [ ] Remove check\_bins.R file as it is no longer needed. Did this combined
  function move into a different file it seems? 


Please make these last to changes and do a version bump to the DESCRIPTION and I see no other reason not to accept the package.  Thank you for making the previous set of changes and improvements.  
Cheers,

**Comment by tkik** [comment]
Thank you! 
[x] I removed the ´check_bins.R´ file, because I realized we used it in a previous version of ´write_bedgraph()´
[x] I modified the vignette as well. 
[x]  added some unit tests and some minor bug fixes. 
[x] cleaned up the old version of example bedgraphs. 

I hope it is ready for acceptance :)
Cheers,

**Comment by tkik** [comment]
Dear @lshep,

I think the build had errors that might come from your end. Apparently some packages are missing. Could you take a look? Thanks!

**Comment by lshep** [comment]
yes im looking into it
