### ISSUE TITLE
MSstatsSampleSize

### ISSUE THREAD

**Issue by huang704** [Bioconductor/Contributions#1277]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsSampleSize

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
9 October, 2019
 
DESCRIPTION

- too bad the package does not re-use data structures, even data structures from the same lab group; the software is more fragile and more difficult for interoperability because of that.

vignette

- please verify that the code chunks in the vignette output does not spill over the page margins.

- MSstatsSampleSize.Rmd:275 model good programming practice by using `seq_along()` / `seq_len()` rather than `1:length...`.

- good

R -- comments are on specific lines of code but apply throughout

- Methods.R:18 use `seq_len()` / `seq_along()` rather than `1:...`

- Methods.R:19 avoid 'copy-and-append', e.g., y using `unlist(lapply())`; see http://bioconductor.org/developers/how-to/efficient-code/

- designSampleSizeClassification.R:169 `message(paste0(...))` can usually be replaced by `message(...)`.

- designSampleSizeClassification.R:172 using `foreach` means that Bioconductor users must learn that package as well; consider using `BiocParallel` for better interoperability.

- there seems to be cut & paste code, one example being simulateDataset.R:131. Consider creating helper functions and using these, so that your code is easier to maintain and more consistent.

- simulateDataset.R:182 `stop("ERROR: ...")` seems redundant, since `stop("...")` already prints `Error: ...`").

- simulateDataset.R:255 Is `stop(message(paste0(...)))` intentional, or is `stop(...)` sufficient?

man 

- ok

Other

- Can the NEWS file be parsed by `utils::news()`?

- nice to see the start on unit tests.

**Comment by huang704** [comment]
Thanks for all the comments. The package has been revised according to those comments.

> DESCRIPTION
> * too bad the package does not re-use data structures, even data structures from the same lab group; the software is more fragile and more difficult for interoperability because of that.

Response: We tried to reuse same data structures as other packages from our lab. It is hard to completely re-use the data structures since the input data to these packages are different. But we indeed made one required input of MSstatsSampleSize (annotation data) have same structure and column names as the other packages from our lab.

> vignette
> * please verify that the code chunks in the vignette output does not spill over the page margins.
Response: The vignette has been revised to fit the page width. 

> * MSstatsSampleSize.Rmd:275 model good programming practice by using `seq_along()` / `seq_len()` rather than `1:length...`.
> * Methods.R:18 use `seq_len()` / `seq_along()` rather than `1:...`
Response: All the for-loop with 1:length() have been replaced with seq_along() or seq_len().

> * Methods.R:19 avoid 'copy-and-append', e.g., y using `unlist(lapply())`; see http://bioconductor.org/developers/how-to/efficient-code/
> * designSampleSizeClassification.R:169 `message(paste0(...))` can usually be replaced by `message(...)`.
> * designSampleSizeClassification.R:172 using `foreach` means that Bioconductor users must learn that package as well; consider using `BiocParallel` for better interoperability.
> * there seems to be cut & paste code, one example being simulateDataset.R:131. Consider creating helper functions and using these, so that your code is easier to maintain and more consistent.
> * simulateDataset.R:182 `stop("ERROR: ...")` seems redundant, since `stop("...")` already prints `Error: ...`").
> * simulateDataset.R:255 Is `stop(message(paste0(...)))` intentional, or is `stop(...)` sufficient?
Response: We have used `BiocParallel` instead of `foreach` and `doParallel` for parallel computation. The codes have been revised based on other comments, such as message() or stop(). 

> * Can the NEWS file be parsed by `utils::news()`?
Response: We have made the NEWS file through .Rd file.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/huang704.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsSampleSize")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsSampleSize

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
