### ISSUE TITLE
MACSQuantifyR

### ISSUE THREAD

**Issue by raph06** [Bioconductor/Contributions#1282]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Peyronlab/MACSQuantifyR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
As preliminary comments I'll mention that you MUST provide 'accessor' functions, not relying on `slot()` / `slot()<-`, `@`, `@<-`.

Your package depends or imports no Bioconductor packages. It seems appropriate to identify relevant [standard data representations][1] to serve as inputs / outputs for your package, to make it both more robust and more interoperable.

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by lshep** [comment]
Out of curiosity how did you push your changes and Do you have any other webhooks activated or only the one to Bioconductor?

**Comment by raph06** [comment]
There was indeed a duplicate global hook in our institution. Thanks for the help, hopefully, it should be settled.

**Comment by dvantwisk** [comment]
Here is the review of your package. [REQUIRED] tags describe changes that must be made or addressed. [CONSIDER] tags describe changes that are advisable but optional. Please message me back when you are finished addressing these issues.

R/GENERAL
- [ ] [CONSIDER] Use `seq_len()` or `seq_along()` instead of `seq(1, ...)`.
This is slightly more optimized.

R/function_toolbox.R
- [ ] [REQUIRED] L63-66,74-84: Inefficient copy-and-append pattern used here.
Iteratively adding to an empty vector requires multiple operations to lengthen
the vector and copy over elements to that lengthened vector. Instead, simply
use `vapply` if equal length vectors are returned or `lapply` followed by
`unlist()` to create the vector. Another option may be to declare a vector
of a needed length to avoid the time-consuming lengthening step.
`v <- vector(length=10)`.

R/new_class_MQ.R
- [ ] [REQUIRED] L126: Files should be saved to `tempdir()` by default as the
user may not want the files to clog up their current directory. Make it clear to
the user that they need to specify a save path to receive the output files.

R/on_plate_selection.R
- [ ] [REQUIRED] L39,40: Why are you sourcing two files in your R directory? It
would be better to create internal functions in these files and call them in 
this file as opposed to going through the extra mechanisms of loading a file
using `source()`.
- [ ] [REQUIRED] L263, 267: Why does the message say "saved to ./outputMQ"?
Isn't the output location variable such that you should call `param.output`
here?

R/pipeline.R
- [ ] [REQUIRED] L39-41: Same issues with the use of `source()`.

vignettes/MACSQuantifyR_combo.R
- [ ] [REQUIRED] There are multiple uses of `eval=FALSE` here. We generally like
to see user facing code run on the build machine. Exceptions can be made in some
cases like where the code opens up a GUI. Does all this code interact with a
GUI?

vignettes/MACSQuantifyR_pipeline.Rmd
- [ ] [REQUIRED] Same question about `eval=FALSE` usage.

**Comment by dvantwisk** [comment]
How's progress on this? I do need to mention that the release bioc3.10 deadline is October 22nd. Please finish making changes to your package by then.

**Comment by raph06** [comment]
I have address the issues. Updating them by tonight

**Comment by raph06** [comment]
R/GENERAL

- [x] CONSIDER Use seq_len() or seq_along() instead of seq(1, ...).
    I changed seq to seq_len for most cases. 

    I feel a little bit confused for the remaining seq() functions regarding the 
    trade of beetween optimisation and efficiency/readability: 

    which of those should I favour
    - `seq(3,7) vs seq_len(7)[3:7]`
    - `seq(8,1) vs rev(seq_len(8))`
    - `seq(1, n, 2)` vs some other subsetting 

R/function_toolbox.R

- [x] REQUIRED L63-66,74-84: Inefficient copy-and-append pattern used here.
    replaced for loops with lapply&unlist

R/new_class_MQ.R

- [x] REQUIRED L126: Files should be saved to tempdir() by default as the
user may not want the files to clog up their current directory. Make it clear to
the user that they need to specify a save path to receive the output files.

R/on_plate_selection.R

- [x] REQUIRED L39,40: Why are you sourcing two files in your R directory?

Removed source ()

- [x] L263, 267: Why does the message say "saved to ./outputMQ"?

Corrected message output regarding path 
 
- [x] There are multiple uses of eval=FALSE here. We generally like
to see user facing code run on the build machine.

In MACSQuantifyR_combos.Rmd I removed severals. 
The one remaining concerns 
- the GUI (on_plate_selection) 

In MACSQuantifyR_pipeline.Rmd there is a single EVAL=F tag for the GUI requiring function on_plate_selection()

Building/ checking/ uploading...

Best 

Raphaël

**Comment by dvantwisk** [comment]
Hi Raphael,

It looks like some of the changes weren't made.

- [ ] The files still save to a directory that is not `tempdir()` by default.
- [ ] The files still use the `source()` function.
- [ ] The fixed file output message are still there.
- [ ] The `eval=FALSE`s are still there.

Are there uncomitted changes on your end that you forgot to push?

**Comment by raph06** [comment]
> Hi Raphael,
> 
> It looks like some of the changes aren't present in the master branch of your github repo.
> 
> * [ ]  The files still save to a directory that is not `tempdir()` by default.
> * [ ]  The files still use the `source()` function.
> * [ ]  The fixed file output message are still there.
> * [ ]  The `eval=FALSE`s are still there.
> 
> Are there changes on your end that you forgot to push?

Yes, I was out of office. Sent the message before pushing. I just finished with the source() issue, I  just pushed everything a few moments ago.

**Comment by dvantwisk** [comment]
Things look good now. I'm going to accept the package.
