### ISSUE TITLE
HCAExplorer

### ISSUE THREAD

**Issue by dvantwisk** [Bioconductor/Contributions#1283]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/HCAExplorer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment]
@dvantwisk @mtmorgan Please address the ERROR. I suspect you guys want HCAExplorer to be included in BioC 3.10 right? Thanks!

**Comment by dvantwisk** [comment]
I'm closing this issue for a little while since there a few issues that need to be worked through before a more thorough review.

**Comment by hpages** [comment]
ok thanks!

**Comment by hpages** [comment]
Some feedback (after a quick and shallow review):

1. Why rely so much on tidyverse stuff like dplyr, tibble, or tidygraph? Hey, we are Bioconductor, not RStudio!

2. Just kidding (well, half-kidding to be honest). Anyway, we, the Bioconductor people, usually don't really care if we define a function (ordinary or generic) with a name that is already used in the tidyverse (like they don't care either if they define a function with a name that is already used in Bioconductor), because these are 2 separate worlds. However, if your package relies on tidyverse stuff then you should be careful about not doing that. For example it's not a good idea that you mask `vctrs::fields()` and `tidygraph::activate()` with your own functions.

3. We usually use `x` or `object` for the first arg of a generic function that we define for the sole purpose of implementing an accessor method. Not something like `hca` which reminds the type of objects that our accessor support at the moment. That's because the only reason for using a generic and not a regular function is to be able to re-use that same generic in the future for accessing other types of objects. So it makes sense to name the first argument in a way that is not biased towards a particular type of object. (For some reason, you're using `hca` for all your generics except for `results()`.)

4. `results()` returns an **invisible** tibble. If that's intended, it should be clarified in the man page.

5. Man pages are very minimalistic and their examples too.

6. Cross-linking of man pages (e.g. via `\seealso` sections) is always a good idea as it helps navigate the documentation. For example in the man page for the `values(x, fields)` getter (``?`values,HCAExplorer-method` ``) a short mention of the `fields()` accessor (with a link to its man page) for getting the list of valid `fields` values would be nice. At a minimum the example could show the use of `fields()` just before doing `hca %>% values('organ')`. Right now, the `'organ'` value comes out of the blue.

7. The systematic use of `%>%`, even when it's not justified like in
    ```
    hca <- HCAExplorer()
    hca %>% fields
    ```
    might be confusing (and annoying) to some people (like it is to me).

8. Why the mix of camel caps (`donorCount`) and snake case (`current_filter`) for the slot names of the HCAExplorer class? Absolutely not an issue in any way since slots are internal business. Just curious.

9. Typo: "avaiable" instead of "available" in vignettes/HCAExplorer.Rmd and R/filter-utilities.R

Thanks!

**Comment by dvantwisk** [comment]
Fixing these now

**Comment by dvantwisk** [comment]
Hi Herve,

- I suppose it all comes down to one's own tastes 😛 
- I've made `activate` use the s3 method from `tidygraph` now. I haven't done this for `fields` and just made it a function. The reason for this is that `fields` doesn't appear to be an s3 generic exposed to the user.
- I've renamed all instances of `hca` in the generics and methods to `x`.
- I must have deleted the last line of that function. `results()` now returns a unattenuated tibble of results.
- I've done what I can to update the documentation to be a but more robust. I do admit there is still some room for improvements.
- I've done some cross linking with `@seealso` where applicable and did what I could to better explain the examples. Again, this may be a place for further improvement.
- I admit, it is a mess. I've limiting the use of piping to tidyverse methods only.
- I've modified the names in my slots to only use camal case.
- typo fixed.

I've also added a method for subsetting, `[`, replacing what `select()` was doing. `select()` now modifies what columns are show in the output of an HCAExplorer object.

**Comment by hpages** [comment]
Thanks for the improvements.

A few more things:

> The reason for this is that `fields` doesn't appear to be an s3 generic exposed to the user.

I think you should still be able to turn it into an S4 generic. You actually don't even need to _explicitly_ do that. Defining a method will implicitly do that for you. So just:
```
setMethod("fields", "integer", function(x) x@terms)
```
but you need to import `fields` from vctrs first.

Don't use this kind of markup:
```
\seealso{
[HCAExplorer()] [fields()]
}
```
Use links instead:
```
\seealso{
  The \code{\link{HCAExplorer}} constructor function.

  The \code{\link[HCAExplorer]{fields}} getter.
}
```
This should produce valid links when you navigate the doc in a browser (`help.start()`).

"avaiable" typo still here. New typo: "firelds" in 2 places in `R/filter-utilities.R`

Address at your earlier convenience.

Thanks,
H.

**Comment by hpages** [comment]
Also of course don't forget to address the current `CHECK` error.

**Comment by dvantwisk** [comment]
Yes, it should run with this next build.

**Comment by dvantwisk** [comment]
- I didn't know you could create an s4 generic in that manner. `fields` is now a method utilizing that.
- I've rewritten the documentation to make better use of `@seealso`.
- typos fixed.

**Comment by hpages** [comment]
Excellent. Thanks!

> I didn't know you could create an s4 generic in that manner.

It's a powerful feature and we use it a lot in BiocGenerics (where we _turn_ existing functions defined in base R into S4 generics).

H.

**Comment by dvantwisk** [comment]
Is the package ready to be accepted now?

**Comment by hpages** [comment]
I already accepted it (about 3 hours ago).

**Comment by dvantwisk** [comment]
Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dvantwisk.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HCAExplorer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HCAExplorer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
