### ISSUE TITLE
(inactive) RTIGER: A Robust HMM-based Model for genotyping-by-sequencing and Recombination Breakpoints Identification.

### ISSUE THREAD

**Issue by rfael0cm** [Bioconductor/Contributions#1285]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rfael0cm/RTIGER

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
please remember to increment your package version (to 0.99.1) to trigger a build.

**Comment by mtmorgan** [comment]
# 27 November, 2019

DESCRIPTION

- good

vignette

- good

## R / man

Coments are on specific lines, but please review all code for similar changes

AllClasses.R

- the slot desriptions aren't clear enough -- 'list of filtered data' does not provide a robust description of the content.

- Documentaitno sometimes mentions `RTIGER`, sometimes `RTiger` etc., choose one and be consistent.

- use `message()` to communicate, rather than `print()` or `cat()` (only exception: `show()` methods). Usually no need to `message(paste(...))`, just `message(...)`. Similarly for `stop()` and `warning()`. Always provide a `verbose=` argument to allow the user to control amount of output.

- avoid `1:...`, e.g., `1:nrow(myCol)`, which fails surprisinglyn `nrow(myCol) == 0`. Use `seq_len()` or `seq_along()` instead.

- avoid `sapply(X, ...)` because it returns unexpeted results when `length(X) == 0` (a `list()`, rather than e.g., `character(length(X))`). Use `vapply()` (if the type of result from each call to `FUN` is known and consistent) or `lapply()`. `unlist(sapply())` is particularly confusing, since the `sapply()` implies that the result type will be homogenous and automatically simplified, whereas the `unlist()` implies that one is not expecting a homogenous result.

- `if ( a & b )` use `&&` to clarify that this is scalar, rather than vectorized, comparison.

- Consider adjusting use of quotations to avoid need to escape, e.g., `"'foo' is"` rather than `"\"foo\" is"`

CO-analysis.R

- implement and use accessors for all slots, e.g., `viterbi(object)` rather than `object@Viterbi`; the accessor does not have to be exported if not useful to the user.

- in the line below it seems unusual to anticipate an error (use of `try()`) but to expect that the try-error will be handled sensibly in subsequent code.

```
      sampGR = try(Vit2GrangesGen(newsamp, "Viterbi"), silent = TRUE)
      COs = length(sampGR)-1
```

- watch for and exploit opportunities for vectorization (one R-level function call) rather than iteration (as many R-level function calls as there are elements in a vector). E.g., replace
```
        dco = unlist(sapply(hetpos, function(i){
          if(vit$Viterbi[i-1] == vit$Viterbi[i + 1]) return(i)
        }) # end sapply dco
```
with
```
dco <- ifelse(vit$Viterbi[hetpos - 1] == vit$Viterbi[hetpos + 1], i, NA)
dco <- dco[!is.na(dco)]
```

- avoid use of `.` -separated function names, e.g., `width.DoubleCO()` as these are confused with S3 `width` generic `DoubleCO()` method.


- adopt more traditional spacing, e.g., with
```
      if( all((length(hetpos) == 1) & (hetpos == 0 | hetpos == 1))) return(dco = 0 )
```
the length of the line and 'hidden' conditional makes it hard to read. Instead
```
      if ( all((length(hetpos) == 1) & (hetpos == 0 | hetpos == 1))) 
          return(dco = 0 )
```

Conf_Interval.R

- I notice that in the third file that I've looked at, I've come across three different file naming schemes. Adopt one throughout.

- consider using `stopifnot()` to facilitate extensive argument validation, rather than more verbose (though more customizable) validation checks, e.g.,
````
stopifnot(
    is(rtigerobj, "RTIGER"),
    is(rviterbiobj, "RViterbi")
)
```

- consider an indentation style that allows more consitent indentation and ultimately more informative characters per 80-column line, e.g.,
```
            myscore = intervalTransition(
                a = newx,
                b = newy,
                sj = sj,
                sk = sk,
                alphas = myres$alphas,
                betas = myres$betas,
                normfactors = myres$normfactors, # scaling factors for the alphas
                transitions = transMat, # a_jk transition probs for moving from j to k
                psis = myres$psis # Emission Probabilities
            )
```

- avoid 'copy and append' like
```
              score.mat = rbind(score.mat, c(i, newx, newy, myscore ))
```
which has very poor performance when `score.mat` gets even moderately large. Use `pre-allocate and fill` or other strategies, e.g., http://bioconductor.org/developers/how-to/efficient-code/

- define helper functions to avoid (apparently?) repetative code chunks like
```
            while(myscore < conf & diff(c(newx, newy)) < nmax.width){
              i = i + 1
              cat(i, "\n")
              newy = newy + 1
              myscore = intervalTransition(a = newx,
                                           b = newy,
                                           sj = sj,
                                           sk = sk,
                                           alphas = myres$alphas,
                                           betas = myres$betas,
                                           normfactors = myres$normfactors, # scaling factors for the alphas
                                           transitions = transMat, # a_jk transition probs for moving from j to k
                                           psis = myres$psis # Emission Probabilities
              )
              
              score.mat = rbind(score.mat, c(i, newx, newy, myscore ))
            } # while
```

Data_generation.R

- Remove 'dead' (commented) code; pervious versions are always available in the version control system.

EMFit.R

- updating complex objects usually triggers copy of the _entire_ object and is very expensive when performed in loops, e.g., 
```
        zeta[[part]][,,r_state,s_state] = hilf1 * a[r_state,s_state] * hilf2 * hilf3
```
instead remove the invariant part outside the loop
```
zeta_part <- zeta[[part]]
...
    zeta_part[,, r_state, s_state] <- 
...
zeta[[part]] <- zeta_part
```

- the inner loop in the following, at least, is vectorizable
```
  for (part in initial_parts){
    for (v_state in vstates){
      for (m_state in mstates){
        hilf[part,,v_state,m_state] =
          hilf[part,,v_state,m_state] / normfactor[part,,m_state] * params$pim[m_state]
      }
    }
  }
```
as
```
hlif[part, , v_state, m_states] <- 
    hilf[part, , v_state, m_states] / normfactor[part,, m_states] * params$pim[m_state]
```

- avoid duplicate function definitions, e.g., `hidden_to_emission()` in EMFit.R and Data_generation.R


RTIGER-Package.R

- The descriptions fof data files are insufficient. Describe the source, how it was accessed, transformations performed, and representation in the package.

RViterbi.R

- It's confusing to have a file `AllClasses.R` and then to find a class definition in another file.

export.csv.R

- hmm
```
    res = sapply(viterbis, function(x){
      
    } )
```

sideFunctionsLoad.R

- niether `cat()` nor `paste()` seem likely to be important.
```
    stop(cat(paste("Second column in file ", samp, " is not an integer.\nGenomic positions must be integers!" )))
```

## data, inst/extdata

- is the large sie of fittedExample.rda and the *txt files necessary? consider developing a realistic but smaller example to facilitate user interaction.

**Comment by mtmorgan** [comment]
remember to increment the package version and provide a short summary of changes made in response to reviewer comments when you are ready for the next step of the review.

**Comment by mtmorgan** [comment]
are you working on this package? It looks like there's a version bump required and a summary of revisions in response to the review are required.

**Comment by rfael0cm** [comment]
Hi Martin,
yes! sorry I took my first holidays in a long time and I will put my hands
on it once I am back!
sorry,
Rafael
