### ISSUE TITLE
scMAGeCK

### ISSUE THREAD

**Issue by weililab** [Bioconductor/Contributions#1296]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/weililab/scMAGeCK

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
As a preliminary comment, please make sure that your package interoperates with existing Bioconductor single-cell experiment infrastructure, e.g., [SingleCellExperiment][1]

[1]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by weililab** [comment]
I have subscribed to the bioc-devel mailing list and the error should be resolved. For the warnings, I removed the inst/doc directory and the warnings should miss now.  Please check my package one more time. Thanks

**Comment by mtmorgan** [comment]
your package will need to be updated to use Makevars rather than Makefile, as outlined in 'Writing R Extensions', `RShowDoc('R-exts')`. There is no need to implement a random number generator; use R's for interoperability and compatibility.

**Comment by mtmorgan** [comment]
# 27 November, 2019

General

- please interoperate with the standard Bioconductor SingleCellExperiment class

- What's the relationship with the software package in 'RRA.zip'?

DESCRIPTION

- ok

vignettes

- please add sections illustrating input and informative interpretation of the results produced by `scmageck_LR()`

## R

- please review specific comments and to all code

frame2indmatrix.R

- use `message()` rather than `print()` / `cat()` to communicate progress

- consider using a code formatter, e.g., formatR, to make your code more readable

- vectorize -- one function call rather than n, e.g.,
```
  for(si in 1:nrow(bc_d)){
    t_r=bc_d[si,'cell']
    t_c=bc_d[si,'gene']
    if((t_r%in%rnm) & (t_c%in% cnm)){
      ind_matrix[t_r,t_c]=TRUE
    }
  }
```
is (a matrix can be subset by another matrix with row and column indexes as columns)
```
row <- bc_d[, 'cell']
col <- bc_d[, 'gene']
test <- (row %in% rnm) & (col %in% cnm)
idx <- cbind(row[test], col[test])
ind_matrix[idx]  <- TRUE
```

get\_rank\_tables.R

- use `seq_along(X)` or `seq_length()` rather than `1:length(X)` to avoid surprises when `length(X) == 0`.

- it is somehow very disheartening to see so many `system()` commands here, for instance `system(paste("rm", ngguidefile))` is accomplished as easily with `unlink(ngguidefile)`.

prepare\_matrix\_for\_pair\_reg.R

- 'copy and append' patterns like
```
        pair_genes[[zi_c_id]]=append(pair_genes[[zi_c_id]],gls_cell_name)
```
are very inefficient, even for only moderate sized objects; for altnernatives see http://bioconductor.org/developers/how-to/efficient-code/

scMAGeCK_lr.R

- use helper functions to avoid (apparent?) code duplication like
```
  if(nmatch==0){
    print('Cell names in expression matrix and barcode file do not match. Try to remove possible trailing "-1"s...')
    if(length(grep('-\\d$',bc_dox[,1]))>0){
      bc_dox[,1]= sub('-\\d$','',bc_dox[,1])
    }
    nmatch=sum(bc_dox[,1]%in%colnames(x=targetobj))
    if(nmatch==0){
      stop('No cell names match in expression matrix and barcode file.')
    }
  }
```

## man

- please make sure usage and example lines are <80 characters, as these do not display well in many situations

**Comment by mtmorgan** [comment]
remember to increment the version of your package to trigger another automatic build. Remember to provide a brief summary of your changes when your package is ready for the next stage of the review.

**Comment by weililab** [comment]
Hi mtmorgan,

I have modified the code. 

For the general questions: 

First, we don't process single-cell data directly and the input for our package is a Seurat object. So, I think we don't need SingleCellExperiment class.

Second, the scmageck_rra function in this package is based on our previous MAGeCK work (which is in C++ format) and RRA is a function of MAGeCK.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/weililab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scMAGeCK")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scMAGeCK

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
