### ISSUE TITLE
packFinder

### ISSUE THREAD

**Issue by jackgisby** [Bioconductor/Contributions#1298]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jackgisby/packFinder

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jackgisby** [comment]
Hi @nturaga 

Just to pre-empt the note in my package and the chunks that use eval=FALSE in my vignette: 

While R/bioconductor was appropriate for the main elements of this package (searching for transposable elements by pattern matching (Biostrings) and representing the ranges of predicted elements (GenomicRanges) I wasn't able to find a package in R that implemented VSEARCH style clustering. 

This clustering/alignment step is optional and is the last step in the analysis, but requires installation and use of the vsearch command line tool (I've included instructions in the vignette for downloading/using vsearch if users wish to). Therefore I haven't included run-able examples and chunks in the examples and vignette, respectively. This can be installed on MacOS, Linux or Windows systems. 

I reckoned this was the best method for implementing (optional) vsearch clustering functionality with the package - although I'm open to improvements or changes if this isn't acceptable for bioconductor submission.

Additionally, I initially tested the package on R 4.0.0 thinking the next bioconductor release had already occured - I may need to update my description to >=4.0.0 for the next cycle?

**Comment by nturaga** [comment]
Hi @jackgisby 

Just an add to to my subsequent review. Your package downloads 1.1 GB from git when i try to clone it. 

Your .git repo is bloated possibly because of data files you pushed into the repo at some point and deleted them later on. You can trim this by using https://stackoverflow.com/questions/2116778/reduce-git-repository-size. Or something like https://rtyley.github.io/bfg-repo-cleaner/.

This is not optimal as size for a bioconductor repo.

**Comment by jackgisby** [comment]
Hi @nturaga 

Thanks for pointing that out, I've done as you suggested and the repo is now significantly smaller.

**Comment by nturaga** [comment]
Great, thanks a lot. I'll send in your review in the week.

**Comment by nturaga** [comment]
# packFinder review

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## vignette

* Good vignette. Although there are a few `eval=FALSE` code blocks. Do
  you intend to not run them? If so, why?

## R

* This seems like a block of code, which I will not be able to
  understand 1 year from now if I had written it. I'm not sure why you
  are checking for "read" permission twice in this block. Some
  documentation would go a long way for both yourself, and the
  reviewer :D
  
```
      if (!is.null(file)) {
        if (!(file.access(file, 4) == 0) |
            !(file.access(file, 4) == 0) |
            !(file.access(file, 2) == 0)) {
            stop("file does not exist, or R does not 
                have read/write permissions")
        }
```

* identifyTirMatches.R , You can use the methods `start` instead of
  `matches@ranges@start`. Try to avoid using solt accessors like `@`
  unless you absolutely need to. There are other similar instances
  where you do this, but it's possible to find functions in the
  BioStrings package which help you with this.
  
* In packAlign.R, Use `file.path` instead of this, it's more
  robust. you seem to have used it in other places.

		packMatchesFile <- paste0(saveFolder, "/packMatches.fasta")

* In packClust.R, add a `message` to this location saying you are
  saving in the current folder,
  
		if (is.null(saveFolder)) {
			message("Saving in the current folder: ", getwd())
			saveFolder <- getwd()
		}

## man

* Good.

## tests

* good

**Comment by jackgisby** [comment]
Hi @nturaga 

Thanks for your review, I've provided an answer to each of your points below although I'm very happy to make further improvements if necessary. 

- **Non-evaluated chunks:** I've removed one of the eval=false blocks and made it run-able. The first remaining block is for the installation of the package from bioconductor. The other two use the VSEARCH command line tool (via system2()) for clustering and alignment functions. While these aren't essential to the annotation pipeline of the package, we found them to be useful for identifying groups of transposons; I could not find an equivalent tool in R that clustered sequences with the same performance and accuracy - others were not able to separate transposons into the groups of our validation set. Therefore, if users wish to use the clustering functions, they need to make sure to have installed this command line tool (instructions available in the vignette/documentation). The vignette chunks and examples for these functions were disabled so the automated tests would run, however if the CL application is installed they will run and I have unit tests for these that I run separately to the other checks. 
- **Unclear code/double file check:** I think this must have been a typo that I copied a few times, I've fixed this bit of code; I've also generally re-organised some of the functions and added some comments that will hopefully make parts more clear. 
- **Slot accessors:** Switched out slot accessors, in all functions, for accessor methods. 
- **File paths:** There were a few places where I had some odd file path paste0 statements that didn't make sense, I've switched these out to be more consistent using file.path.
- **Wd save message:** Have added the message you recommended for this, and similar, functions. 

I've implemented the CL tool in the way I thought seemed optimal - it's an optional final step that is not necessary for the main annotation workflow; therefore, I felt it was best to allow users to install it when/if needed. However, I realise this may not be standard for bioconductor packages? If necessary, I'm happy to change how this part of the package works.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jackgisby.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("packFinder")`. The package 'landing page' will be created at

https://bioconductor.org/packages/packFinder

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
