### ISSUE TITLE
ChIP-seq signal quantifier pipeline (CSSQ)

### ISSUE THREAD

**Issue by ashwathkumar** [Bioconductor/Contributions#1303]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ashwathkumar/CSSQ

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ashwathkumar** [comment]
Hi @dvantwisk , I cannot seem to recreate the R CMD build error on my PC as it builds and checks without issue. I am not able to check it on the Bioconductor devel version because of a Rtools issue I face in using devtools with the r-devel on Rstudio. Any pointers on how to deal with this? Thanks !

**Comment by ashwathkumar** [comment]
@dvantwisk Hi Daniel ! It seems the package has passed the initial automated tests. I would very much like your feedback on the package so i can make the recommended changes and get this rolling. Thanks a lot for your time !

**Comment by dvantwisk** [comment]
Got it. I should have a review for you sometime early next week.

**Comment by ashwathkumar** [comment]
Great ! Thanks a lot for taking time to review the package. Looking forward to your feedback.

**Comment by dvantwisk** [comment]
I apologize for the wait!

Here is a review of your package. [REQUIRED] tags are changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not required. Message me back when you are done making changes.

R/GENERAL:
- [ ] [REQUIRED] Your documentation should say when a parameter uses a default
values if the user does not give input. Many parameters that are documented
throughout you package do not include documentation regarding default values.
- [ ] [CONSIDER] I've noticed that you end each line with `;`. This is common
in more strongly-typed languages like C but R doesn't require it and most
R-programmers generally don't do this. Mind you, it's not incorrect to use `;`,
it's just not commonly done as it's another unnecessary key stroke.

R/dbAnalyze.R
- [ ] [REQUIRED] Does the `comparison` parameter work when it is assigned its
default value of `c()`? Does the result have any value to the user? Perhaps it's
better to make `comparison` required and `stop()` if the user doesn't include
it.

R/getBgSubVal.R
- [ ] [CONSIDER] Use `match.arg()` to declare `countMode`. There appears to be
only four values that `countMode` can take. In the function declaration, you can
write
`countMode = c('Union', 'IntersectionNotEmpty', 'IntersectionStrict', 'user supplied function')`
The first value is the default value of countMode, in this case it is `Union`.
To obtain the user's input, you can write `countMode <- match.arg(countMode)` in
the body of the function. Doing this makes it easier for the user to understand
what values `countMode` can have. It also throws an error if the user gives
anything other than the listed values. This can be done elsewhere in this
package.

R/getRegionCounts.R
- [ ] [REQUIRED] L47: Use `message()` instead of `print()` to display diagnostic
messages to the user. `message()` is preferable because they can be toggled off
with `suppressMessages()`.

R/loadCountData.R
- [ ] [CONSIDER] L34: The `rtracklayer` package has a method called
`import.bed()` that is meant to import bed files. This is better to use than
`read.table()`.

R/plotDist.R
- [ ] [REQUIRED] It is preferable to return the plots that are generated to 
users using `plotDist()` instead of automatically placing them in a pdf. This
allows the user control on how they want to display these plots. Perhaps this
function should be user facing to allow users the ability to create their own
plots?

R/preprocess.R
- [ ] [REQUIRED] It's somewhat confusing to may the default value of
`inputCountData` to `'None'`. This is only used to check whether the user has
given a value to this parameter in L51-53. Instead, give no default value to 
`inputCountData` and check is the user has given input with the lines:
```
if (missing(inputCountData)
    countData <- getRegionCounts(inputRegions,sampleInfo,sampleDir=sampleDir,...)
```

tests
- [ ] [CONSIDER] Add tests using the `testthat` package.

**Comment by ashwathkumar** [comment]
Thanks for the feedback ! I will work on these and make a new commit soon !

**Comment by ashwathkumar** [comment]
Hi @dvantwisk,

I have made all the REQUIRED changes you mentioned and some of the CONSIDER one as well. I updated the package and the new build by the bot gave me the following error 

"Error: package DelayedArray required by SummarizedExperiment could not be found" in OSX systems. Is this error from my side or the computer the bot ran it on? I am unsure how to go about fixing this. Any help will be appreciated. 

Thanks !

**Comment by lshep** [comment]
I'm going to try and kick off a manual build of your package -  DelayedArray should be available for that platform and it is odd that it is not being found.

**Comment by ashwathkumar** [comment]
> I'm going to try and kick off a manual build of your package - DelayedArray should be available for that platform and it is odd that it is not being found.

Thanks a lot ! It seems there was no error in the manual build. It is odd why it wasn't able to find the package in the earlier build.

**Comment by dvantwisk** [comment]
Great! I'll have a look at your changes and get back to you soon!

**Comment by dvantwisk** [comment]
Sorry for the wait! I think the changes you made look good. I'm going to move to accept that package now.

**Comment by ashwathkumar** [comment]
> Sorry for the wait! I think the changes you made look good. I'm going to move to accept that package now.

Thanks a lot @dvantwisk  for taking the time to give me feedback and reviewing the package !

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ashwathkumar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CSSQ")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CSSQ

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
