### ISSUE TITLE
snapcount package submission

### ISSUE THREAD

**Issue by ch4rr0** [Bioconductor/Contributions#1304]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/langmead-lab/snapcount

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ch4rr0** [comment]
@hpages -- The project now compiles without warning or error and would love to continue the review process.

**Comment by hpages** [comment]
Hi @ch4rr0 ,

Happy New Year and sorry for the delay.

Looks like the snapcount package is using reference classes. Any reason for that? Bioconductor strongly recommends the use of traditional S4 classes, unless you have a good reason for using something else.

In any case, Bioconductor users are not necessarily familiar with the `sb$query_jx()` syntax and should not be required to learn it in order to use your package. Please make sure that your objects support the standard `query_jx(sb)` syntax, even if they are reference objects (reference objects also support it), and stick to this syntax in all your examples and vignette.

Thanks!
H.

**Comment by ch4rr0** [comment]
I am working on this.

**Comment by hpages** [comment]
Any progress on this? Thanks

**Comment by ch4rr0** [comment]
Still working on the changes. Some additional suggestion were brought during an internal review, so working on addressing those as well.

**Comment by ch4rr0** [comment]
I will be resubmitting the package tomorrow. Apologies for the delay.

**Comment by hpages** [comment]
No problem. Thanks for the update.

**Comment by ch4rr0** [comment]
FYI -- I need to fix some test-breaking changes, so will be delayed by a day.

**Comment by ch4rr0** [comment]
@hpages -- package is ready for review now.

**Comment by ch4rr0** [comment]
@hpages -- do you think we will be ready for the next bioconductor release?

**Comment by ch4rr0** [comment]
any updates?

**Comment by hpages** [comment]
Hi @ch4rr0 ,

Sorry again for the delay.

My major concern remains: the package is still using reference classes. Sorry to ask again but are there any reasons for that? See my comment from Jan 9 above in this issue, and also, if the use of reference classes is really necessary, my recommendation to avoid exposing the end user to things like `sb$compilation("gtex")$regions("CD99")$query_jx()`.

Other minor things:

1. Please address the `R CMD check` NOTEs about the `LICENSE` file.

2. Using URLs like
    https://bioconductor.org/packages/release/bioc/vignettes/recount/inst/doc/recount-quickstart.html
    https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html
    is fragile because these URLs are not guaranteed to work in the future. It's much better to use the "canonical URL" for a Bioconductor package (sometimes called the _Package Short Url_). The canonical URL is of the form: `https://bioconductor.org/packages/pkgname`. The Bioconductor project is committed to keep these URLs valid for as long as the project will live.

3. In `?Compilation`:
    > If the package cannot connect to the internet the variants will default to:

    but there is nothing after "to:"

4. Too many typos e.g. SnaptonQueryBuilder ("r" missing), RangeSummarizedExperiment ("d" missing), etc... Please re-read carefully your man pages and the vignette.

Thanks,
H.

**Comment by ch4rr0** [comment]
The reference class makes it easy to implement the Builder pattern used in SnaptronQueryBuilder class. We kept it documented, but also provided wrapper functions for users not familiar with R6. I made an attempt to replace all examples outside of the SnaptonQueryBuilder with wrapper functions.

**Comment by ch4rr0** [comment]
I am working on fixing the remaining issues.

**Comment by ch4rr0** [comment]
FYI -- we are almost done with the changes.

**Comment by ch4rr0** [comment]
There seems to be an issue with the build bot.

**Comment by hpages** [comment]
We're currently looking into this. Thanks!

**Comment by hpages** [comment]
Thanks for all the improvements to the package. It's in a much better shape. I like that the user can now operate on the SnaptronQueryBuilder objects using the classic R syntax. Note that you still have a few occurrences of "SnaptonQueryBuilder" (the "r" is missing) but that is not a showstopper (you can fix them now or after the package is added to our git server at git.bioconductor.org).

I'm accepting the package.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ch4rr0.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("snapcount")`. The package 'landing page' will be created at

https://bioconductor.org/packages/snapcount

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
