### ISSUE TITLE
clustifyr

### ISSUE THREAD

**Issue by raysinensis** [Bioconductor/Contributions#1308]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rnabioco/clustifyr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
nturaga will provide a more extensive review but your package *must* interoperate with the [SingleCellExperiment][] class, as this is the primary Bioconductor data representation. 'Interoperate' means that your functions that accept a matrix of features x cells as input should in addition (e.g., by constructing a generic and method,SingleCellExperiment as well as method,matrix) support SingleCellExperiment. It seems like often the return value, regardless of input, will also be a SingleCellExperiment

[SingleCellExperiment]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by nturaga** [comment]
# clustifyr review

## General

Please go over the
http://bioconductor.org/developers/package-guidelines/ .There are many
locations in the package which don't follow the standards set in the
guidelines.

The BiocCheck package flags certain coding standards i'm particular about,

```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        compare_genelist.R (line 225, column 13)
        compare_genelist.R (line 262, column 17)
        compute_similarity.R (line 177, column 3)
        run_fgsea.R (line 63, column 23)
        run_fgsea.R (line 73, column 25)
        utils.R (line 138, column 12)
        utils.R (line 228, column 17)
        utils.R (line 587, column 5)
        utils.R (line 594, column 5)
        utils.R (line 601, column 5)
        utils.R (line 654, column 10)
        utils.R (line 1417, column 12)
        utils.R (line 1537, column 13)
        utils.R (line 1574, column 5)
        utils.R (line 1581, column 5)
        utils.R (line 1618, column 19)
        utils.R (line 1765, column 9)
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        compare_genelist.R (line 103, column 44)
        compare_genelist.R (line 121, column 51)
        compare_genelist.R (line 285, column 25)
        compute_similarity.R (line 131, column 13)
        utils.R (line 203, column 15)
        utils.R (line 373, column 40)
        utils.R (line 375, column 61)
        utils.R (line 458, column 13)
        utils.R (line 539, column 50)
        utils.R (line 1313, column 24)
        utils.R (line 1323, column 30)
        utils.R (line 1325, column 27)
        utils.R (line 1373, column 13)
```

* Your package is 117MB because of the `.pack` files stored by
  git. You can use https://rtyley.github.io/bfg-repo-cleaner/ to make your package fit the 5MB limit for a software package in Bioconductor.

```
[2] "The following files are over 5MB in size: '.git/objects/pack/pack-b29fb310db06ba1e579e3cf0893520e9864f277c.pack'"
```

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* The `Description` section should be like the abstract of a
  paper. The current version needs to be more elaborate.

## NAMESPACE

ok

## NEWS.md

* There is a location for the NEWS file, and it should be parsable by
  `utils::news(). Please follow the guidelines here,
  http://bioconductor.org/developers/package-guidelines/#news
  
## vignette

* Use `BiocStyle` for the
  vignette. http://bioconductor.org/developers/package-guidelines/#vignettes
  
  http://bioconductor.org/packages/devel/bioc/html/BiocStyle.html
  
## R - initial review 

* Use 4-space formatting in the code, it makes it more readable for
  the reviewer.


Once you are done fixing the issues, please issue a version bump.

**Comment by kriemo** [comment]
Hi,
  Thank you for the initial review.  I have a question about the package size requirement. We have run `bfg-repo-cleaner` to remove all old large files, and now there are no files larger than 5MB. The .git directory however is still somewhat large (29MB), but the build source tarball is less than 5MB. Is it required for the directory (.git + all other files) to be less than 5Mb or just the source tarball? 

Thanks!

**Comment by nturaga** [comment]
> Please disregard comment below, we were able to get the repo size down less than 5Mb.
> 
> Hi,
> Thank you for the initial review. I have a question about the package size requirement. We have run `bfg-repo-cleaner` to remove all old large files, and now there are no files larger than 5MB. The .git directory however is still somewhat large (29MB), but the build source tarball is less than 5MB. Is it required for the directory (.git + all other files) to be less than 5Mb or just the source tarball?
> 
> Thanks!

The source tarball should be even smaller, the package should be smaller than 5MB when installed.

**Comment by nturaga** [comment]
# Update

## DESCSRIPTION

ok

## NAMESPACE

ok

## NEWS

ok

## vignette

* Doesn't run to completion

```
> # For further convenience, a shortcut function for generating reference matrix from `SingleCellExperiment` or `seurat` object is used.
> new_ref_matrix_sce <- object_ref(
+   input = sce_small,               # SCE object
+   cluster_col = "cell_type1"       # name of column in colData containing cell identities
+ )
Error in is(input, "seurat") : object 'sce_small' not found
```

## R

* You don't need to use `paste0` when using the message function. You
  can just say `message("xyz ", value)`. paste0 is an additional
  function which is not needed unless there is an intention of
  recycling the vector `threshold`.

        message(paste0("using threshold of ", threshold))

* Don't use slot accessors `s_object@data`. Please write an accessor
  method `get_object_data <- function(object) object@data`, and use
  the get_object_data function.

  Do this everywhere.

* Good use of MatrixStats.

**Comment by nturaga** [comment]
Hi @kriemo 

Any updates on the package development? We usually give authors about 2 weeks before they make changes or at least make a push or some sort. 

So, consider this the two week heads up since I forgot to tell you about it. In about 2 weeks, if there are no updates, then we can close the issue and reopen it whenever you have time to work on your package again.

Best,

Nitesh

**Comment by kriemo** [comment]
Hi Nitesh,
  We have made updates to `clustifyr` and have been able to fix the issues that you highlighted in the `R` section ( see italicized responses below). However we have been unable to replicate the vignette building error (see more detail below). 

# R   

- You don't need to use paste0 when using the message function. You
can just say message("xyz ", value). paste0 is an additional
function which is not needed unless there is an intention of
recycling the vector threshold.

  message(paste0("using threshold of ", threshold))

*We have removed paste0 from any message function calls (https://github.com/rnabioco/clustifyr/commit/547bc5bd6f4615c2debee803a4801f95bc71e84a)*

- Don't use slot accessors s_object@data. Please write an accessor
method get_object_data <- function(object) object@data, and use
the get_object_data function.

*We have added an [`object_data()`](https://github.com/rnabioco/clustifyr/blob/b949e08168ade72b935312fa0b0f7c5520999d01/R/seurat_wrapper.R#L5) accessor method and used this method inplace of directly calling the relavant slots.* 

# vignette 

Doesn't run to completion 
```r
> # For further convenience, a shortcut function for generating reference matrix from `SingleCellExperiment` or `seurat` object is used.
> new_ref_matrix_sce <- object_ref(
+   input = sce_small,               # SCE object
+   cluster_col = "cell_type1"       # name of column in colData containing cell identities
+ )
Error in is(input, "seurat") : object 'sce_small' not found
```

*We have been unable to replicate this error locally (MacOS) or on Travis (Linux, see build report (https://travis-ci.org/rnabioco/clustifyr/builds/643986804). We are not sure what is causing this issue and any suggestions would be appreciated.*  

Thanks!
Kent

**Comment by nturaga** [comment]
Hi Your package has been accepted. Please bump the version once as the single package builder says it is required.

**Comment by kriemo** [comment]
Great thanks. I bumped the version on master to `0.99.7` but the single package builder hasn't recognize the commit.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/raysinensis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("clustifyr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/clustifyr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
