### ISSUE TITLE
curatedAdipoArray: A Curated Microarrays Dataset of MDI-induced Differentiated Adipocytes (3T3-L1) Under Genetic and Pharmacological Perturbations

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/Contributions#1311]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MahShaaban/curatedAdipoArray

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by MahShaaban** [comment]
For some reason the latest push didn't trigger a new build. 
I changed the R dependency to `R (>= 4.0)` and the package version to `0.99.1`.

**Comment by mtmorgan** [comment]
usually this means that the web hook has not been configured correctly. https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by MahShaaban** [comment]
Thanks @mtmorgan I added a new webhook and it works now.

**Comment by LiNk-NY** [comment]
Hi Mahmoud, @MahShaaban 

Thank you for your submission. Please see the review below.

Best regards,
Marcel 

---

# curatedAdipoArray # 1311

## DESCRIPTION

* `Year` field is not necessary
* Update your `License` field if you are going to include a file.
* It looks good overall.

## NAMESPACE

* None

## vignettes

* Avoid using `ExpressionSet` and use `SummarizedExperiment`
* We recommend storing the data as `data.frame`s and building a
`SummarizedExperiment` from the downloaded data.
* Please mention the other `curated*` packages that you maintain.

**Comment by MahShaaban** [comment]
Thanks @LiNk-NY 

I updated the DESCRIPTION file to remove the Year field and add file to License.
Adding the file `LICENSE.md` to License field produces a warning. I am not sure how to avoid that!

I thought that `ExpressionSet` is the preferred format for arrays data. If not, I will replace it with `SummarizedExperiment`. I also thought, since I am planning on using `ExperimentHub` to store the cleaned data, it should be in user ready format. This would reduce the time needed to build the objects when the package is installed.

I maintain two other packages: https://github.com/MahShaaban/curatedAdipoRNA and https://github.com/MahShaaban/curatedAdipoChIP

**Comment by LiNk-NY** [comment]
Can you add a plain text `LICENSE` file? 

`ExpressionSet` was superseded by `SummarizedExperiment` for analyzing microarray and other data.
You **could** store the data as `SummarizedExperiment`. It becomes problematic when there are significant changes to the `SummarizedExperiment` class and that is why I suggested using a more
stable data format such as `matrix` or `data.frame`. 

Please list those packages in the vignette so that your users can check out your other work.

**Comment by MahShaaban** [comment]
@LiNk-NY 
* I replaced `LICENSE.md` with `LICENSE`
* I added links to the related packages to the vignette.
* I replaced `ExpressionSet`s with `SummarizedExperiment`s and updated the scripts and the docs accordingly.

**Comment by LiNk-NY** [comment]
Hi @MahShaaban 
Thank you for making those changes. I have accepted your experiment data package. 
Best,
Marcel

**Comment by MahShaaban** [comment]
Thanks @LiNk-NY How about uploading the data to the experimental hub?

**Comment by LiNk-NY** [comment]
Hi Mahmoud, @MahShaaban 
Have you been given access to upload the data? 
If not, we will get back to you shortly. Thanks.

**Comment by lshep** [comment]
Please email me at lori.shepherd@roswellpark.org  and I can give you credentials to upload your data to S3 so they can be added to the hubs

**Comment by Kayla-Morrell** [comment]
@MahShaaban We were working on adding the data into ExperimentHub but when we run the `makeExperimentHubMetadata` command there was an issue with the SourceType. Will one of the current entries suffice or if not why is it different?

```
> meta <- makeExperimentHubMetadata("curatedAdipoArray", "metadata.csv")
Loading valid species information.
Tags are specified by biocViews entry in the DESCRIPTION file.
Ignoring Tags in the metadata file.
Error in .checkThatSourceTypeSoundsReasonable(object@SourceType) :
  'SourceType' should be one of: BAI, BAM, BED, BigWig, BioPax, BioPaxLevel2, BioPaxLevel3, BLOB, CEL, Chain, CSV, ensembl, FASTA, FASTQ, FCS, GFF, GRASP, GTF, HDF5, IDAT, Inparanoid, JSON, MTX, MySQL, mzid, mzML, mzTab, mzXML, NCBI/blast2GO, NCBI/ensembl, NCBI/UniProt, RDA, RData, Simulated, tab, tar.gz, TSV, TwoBit, TXT, UCSC track, VCF, XLS/XLSX, Zip.
 Found type: GSEmatrix
```

**Comment by MahShaaban** [comment]
@Kayla-Morrell 
I am not sure which of the above would be the correct source type of the data. Each of the entries is a microarrays probe intensities expression matrix downloaded from GEO. Which SourceType should I use?

**Comment by lshep** [comment]
Thank you for the explanation. I can add a new source type on Monday for gsematrix. We will let you know when the data is ready in the hub. 
Cheers

**Comment by Kayla-Morrell** [comment]
@MahShaaban - Based on standards we updated the SourceType to be 'GSEMatrix' so be sure to make this change in your metadata file (note the capital M instead of lowercase m). The data is now available in the devel version of ExperimentHub:

```
> library(ExperimentHub)
> eh = ExperimentHub()

snapshotDate(): 2020-02-11

> query(eh, "curatedAdipoArray")
ExperimentHub with 45 records
# snapshotDate(): 2020-02-11
# $dataprovider: GEO
# $species: Mus musculus
# $rdataclass: SummarizedExperiment
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype
# retrieve records with, e.g., 'object[["EH3245"]]'

           title
  EH3245 | A Clean Expression Matrix of the GEOGSE102403 Dataset.
  EH3246 | A Clean Expression Matrix of the GEOGSE122054 Dataset.
  EH3247 | A Clean Expression Matrix of the GEOGSE12929 Dataset.
  EH3248 | A Clean Expression Matrix of the GEOGSE14004 Dataset.
  EH3249 | A Clean Expression Matrix of the GEOGSE1458 Dataset.
  ...      ...
  EH3285 | A Clean Expression Matrix of the GEOGSE97241 Dataset.
  EH3286 | A Curated Microarrays Dataset  of MDI-induced Differentiated Adi...
  EH3287 | A Curated Microarrays Dataset (processed) of MDI-induced Differe...
  EH3288 | A Curated Microarrays Dataset  of MDI-induced Differentiated Adi...
  EH3289 | A Curated Microarrays Dataset (processed) of MDI-induced Differe...
> temp = query(eh, "curatedAdipoArray")[[1]]

> head(temp)
class: RangedSummarizedExperiment
dim: 6 9
metadata(3): experimentData annotation protocolData
assays(1): exprs
rownames(6): 0610005C13Rik 0610009B22Rik ... 0610010F05Rik
  0610010K14Rik
rowData names(0):
colnames(9): GSM2736085 GSM2736086 ... GSM2736092 GSM2736093
colData names(18): series_id sample_id ... symbol_missing
  perturbation_type
```

You can now update your package and code to use ExperimentHub.

Best,
Kayla

**Comment by MahShaaban** [comment]
I updated the metadata file and the vignette to use the data from the ExperimentHub.

**Comment by LiNk-NY** [comment]
Hi Mahmoud, @MahShaaban 
Thanks for making the changes. Your package looks ready to go! 
Best,
Marcel

**Comment by MahShaaban** [comment]
Thank you all for your help.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MahShaaban.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("curatedAdipoArray")`. The package 'landing page' will be created at

https://bioconductor.org/packages/curatedAdipoArray

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
