### ISSUE TITLE
rSWeeP: Representations large biological sequences datasets in compact vectors on an R platform.

### ISSUE THREAD

**Issue by DanrleyRF** [Bioconductor/Contributions#1323]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DanrleyRF/rSWeeP

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
please make sure that your package interoperates with standard Bioconductor data representations, especially DNAStringSet from the [Biostrings][1] package.

[1]: https://bioconductor.org/packages/Biostrings

**Comment by DanrleyRF** [comment]
@mtmorgan thank you for the attention. I believe that the package is package interoperational with standard Bioconductor data representations, as suggested

**Comment by mtmorgan** [comment]
15 January, 2020

Sorry for my delay. I don't see any interoperability with standard Bioconductor data structures. Please update, including in response to the following comments. When you've completed the updates please post a short comment summarizing your changes.

DESCRIPTION

- If the package primarily relies on seqinr, rather than Biostrings (e.g., the package imports seqinr, but does not depend, import, or suggest Biostrings, then really it belongs on CRAN; Biostrings is the standard pacakges for representing sequence data in Bioconductor, providing Bioconductor users with robust and interoperable concepts.

- can you provide a more descriptive Title: and more extensive Description: so that someone encountering these can tell precisely what functionality the package provides.

R

- The following specific comments should be applied to all code.

- Make sure the exposed functions of your package interoperate with standard Bioconductor objects. For instance `SWeeP` is written to accept a file name but should also accept a DNAString and / or DNAStringSet (maybe your method is really working on amino acid sequences? this needs to be clarified; the Biostrings representations are AAString / AAStringSet and readAAStringSet()). The natural way to do this is to use an S4 Generic and S4 methods, with the methods implementing a 'facade' pattern that do a little work and pass a consistent argument to a helper function that does the real lifting, along the lines of

    ```
    setGeneric(
        "SWeeP", 
        function(file, orthoBase) standardGeneric("SWeeP"),
        signature = "file"
    )
    
    setMethod("SWeeP", "character", function(file, orthoBase) {
        dna = readDNAStringSet(file)
        SWeeP(dna, orthoBase)
    })
    
    setMethod("SWeeP", "DNAStringSet", function(file, orthoBase) {
        ...
    })
    ```

- For robust code, start each user-facing function by validating user input. Thus check that `orthoBase` is a matrix (or can be coerced to a matrix, if that is appropriate) with, e.g.,
  ```
  stopifnot(is(orthoBase, "matrix"))
  ```
  Doing this at the start of the function so that the user finds out quickly and informatiely that they have used the wrong arugment; this also simplifies code further down, for instance there are three occurrence of `as.matrix(orthoBase)` in `SWeeP()`, but this operation only needs to be performed once.

- Carefuly consider the selection of package dependencies to re-use standard Bioconductor functionality. For isntance use Biostrings::readDNAStringSet for fasta input.

- use `message(...)` rather than `print(paste(...))` to communciate with users. If there is an error (e.g. `print("The amino acid sequences are too short ")` use `stop()` making sure that the error tells the user what you have been checking, e.g., `stop("'file' should reprsent a DNA sequence of more than 2001 nucleotides")`. Actually, the message is printed when `is.list(xfas)` fails, and it is not clear why that condition would corresond to an amino acid sequence that is too short.

- SWeeP.R:42 revise
    ```
    for (i in c(1:(round(length(xfas)/block)))){
    ```
  to 
    ```
    for (i in seq_len(length(xfas) / block))
    ```
  Note that the use of `seq_len()` avoids the use of `1:n`, which is problematic when `n == 0`. Please also note that there is no need for `c()`, and that using additional spacing around operators such as `/` increases readability. Please review and revise all of your code for these types of issuse

- Please review the coding style guidelines (https://bioconductor.org/developers/how-to/coding-style/) and in particular consider using `formatR` or similar package for standardizing your code formating. Standard formatting makes it easier for others to read your code and hence contribute to your software.

- Please carefully review your code to remove operations taht have no effect. For  example the use of `c()` above, the first line of

    ```
    projected <- list();
    projected <- (matrizid%*%as.matrix(orthBase))
    ```
  is
    ```
    projected <- matrizid %*% orthBase
    ```
  The call to `Sys.time()` in the next line is also redundant.

- consider adopting consistent, rather than 'cute', function and variable naming conventions, usually following a lowerCamelCase convention, e.g., `sweep()`, `orthobase()`.

- `aa2int()` this code can be easily 'vectorized' (one R function call, rather than `length(xfas)` calls) with something like
  ```
  map <- c(A = 1L, a = 1L, R = 2L, r =2L, ...)
  xfas <- unnamed(map[xfas])
  ```
- consider adopting a more informative name for the data set `datastring`. Use standard R terminology to describe the object, e.g. 'A string vector with six strings' might be 'A `character()` vector of length 6.'

- `fas2mat`: use Biostrings functionality

vignette

- Instead of reading the R object `datastring` and writing it as a fasta file, include the fasta file directly in `inst/extdata/exdna.fas` and reference it in the ignette as
  ```
  path <- system.file(package = "rSWeeP", "extdata", "exdna.fas")
  ```
  
- please clarify the scale of the problem you are tackling. What size and number of sequences are you expecting your algorithm to work on? Can you generate a 'large' example that shows that it works at the scale you anticipate?

misc

- please remove non-R package source files from your git repository, e.g., the `doc/` and `Meta/` directories.

**Comment by DanrleyRF** [comment]
21 January 2020

Thank you for your comment @mtmorgan , your recommendations have been very useful in developing our package and improving our knowledge on the Bioconductor platform 

DESCRIPTION
The package no longer relies on seqinr, now operates only with Biostrings functions and variables
The  Title and the Description have been updated to be more precise in describing the package.

R
Despcritional comments have been added to all codes.
The sWeeP functions now accept  AAStringset as well file names as a valid entry 
The sWeeP function now uses an S4 Generic and S4 methods
The user input variable baseMatrix has now a  validating step on the code
The sWeeP function now uses Biostrings::readAAStringSet for FASTA input.
All functions now only use message(...) to communicate with users. 
All 1:length(...) instances have been replaced with seq_len
On all codes, the function tidy_source() from the formatR package has been used to standardizing code formating. 
All operations that do not affect have to the package working been removed.
Some functions and variables naming has been changed aiming to follow the lowerCamelCase convention (the sWeeP function still as it's, due it is the method initials)
aa2int() has been replaced by a vector inside  the aa2num2() 
The data set datastring has been removed. 
fas2mat receives now an AAStringSet as entry

vignette
Instead of reading the R object datastring and writing it as a FASTA file, a FASTA file has been included directly in inst/extdata/ 
A bigger FASTA has been used in the "Quick Start" section,  but still not 'larger'  as the program can handle in max, due to the long time that would take to generate the example  if the maximum where used

misc
All non-R package source files have been removed from the git repository

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DanrleyRF.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rSWeeP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rSWeeP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
