### ISSUE TITLE
TreeAndLeaf

### ISSUE THREAD

**Issue by sysbiolab** [Bioconductor/Contributions#1324]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sysbiolab/TreeAndLeaf

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sysbiolab** [comment]
Hi,

The changes I've made are:

1. Updated R version dependency from 3.6 to 4.0 on the `DESCRIPTION` file (commit Warning fix);
2. Incremented the package version from 0.99.0 to 0.99.1 (commit Version bump).

Thank you

**Comment by nturaga** [comment]
I'll review your package within a couple of days.

Thanks

**Comment by nturaga** [comment]
# TreeAndLeaf review

## DESCRIPTION

- The title can just be 

		Title: An alternative to dendrogram visualization and insertion of multiple layers of information

  instead of 

		Title: TreeAndLeaf: An alternative to dendrogram visualization
		and insertion of multiple layers of information

## NAMESPACE

ok

## R CMD build

ok

## R CMD check

ok

## build report issues

Some "NOTE"s, but no major issues.

## R

* In `allChecks.R`, it makes more sense to use `stop(".....` as
  opposed to using a "NOTE:" in the message.
  
  What you have now, displays `Error: NOTE: ....`. Please fix this.
  
* Instead of `==` to check if two strings are equal please use
  `identical`.https://stat.ethz.ch/R-manual/R-devel/library/base/html/identical.html
  
* Some of your control statements are poorly formed, example in the
  function `hclust2igraph()`. eg, the `if..else` statements end with
  an else usually. Your code works, but seems like you are missing an
  `else()`. Take a look at this very helpful, https://rstd.io/code-smells.

## man

ok

## vignette

ok

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sysbiolab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TreeAndLeaf")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TreeAndLeaf

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
