### ISSUE TITLE
CeTF

### ISSUE THREAD

**Issue by cbiagii** [Bioconductor/Contributions#1329]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbiagii/CeTF

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by cbiagii** [comment]
Dear reviewer, @LiNk-NY, is it possible for me to change the role of the authors without compromising their package revision?

**Comment by cbiagii** [comment]
@LiNk-NY  Hi Marcel!! It seems the package has passed the initial automated tests. I would very much like your feedback on the package so I can make the recommended changes and get this rolling. Thanks a lot for your time !

**Comment by LiNk-NY** [comment]
Hi Carlos, 
I have a couple of packages ahead of you in the queue. 
I will get to your package as soon as possible. 
Thank you.

**Comment by cbiagii** [comment]
Dear Marcel, don't worry! Thanks for the answer.

**Comment by LiNk-NY** [comment]
Hi Carlos, @cbiagii 

Thank you for your submission. 
Please see the review below. If you have any questions, feel free to post them
in the comments below.

Best,
Marcel

---

# pcitRif #1329

* Consider renaming the package to something that is easier to remember.
Packages with a lot of acronyms are not usually.

## DESCRIPTION

* It looks good. 
* The `Authors@R` section is overflowing. Please maintain it within 80 column
width.

## NAMESPACE

* `*input`, `*input1`, and `*input2` and related methods point out a potential
area of improvement for the package
* `*Data` functions may not be necessary (see below)

## vignettes

* Please keep the text within the 80 column width margin. It makes the source
document easier to maintain and to review.
* You do not need to explicitly install the dependencies for the package,
a simple installation of the package will automatically get them for the user.
Use `BiocManager::install("cbiagii/pcitRif")`

## R

* Avoid using `cat` inside a function unless it is the show method. Use
`message` instead
* `countsToTPM` can have a funcitonal argument that guides the conversion with
the default being the original computation.
* Arguments with default values will not be missing (e.g., `anno = NULL`) so
the test is not relevant, use `is.null`.
* Avoid using index positions to subset and rather opt for names when
subsetting. For example, use `df[, "sample1"]` instead of `df[, 1]`.
* Combine R files that are related to each other for example, some plotting
functions can be in the same file.
* Avoid using nested `ifelse`. Use a table of data to reassign values, see
Martin Morgan's response in this stackoverflow link:
https://stackoverflow.com/questions/39217432/r-improving-nested-ifelse-statements-multiple-patterns
* Consider providing a more robust prototype for the `pcitrif` class. A list
of lists does not have much structure.
* It seems like creating accessors for specific inputs is not the right way to
go. Please create one general function that will access different parts of the
object based on an argument (similar to `SummarizedExperiment::assay`) for
`PCITinput*` and related functions. This can also apply to the data accessor
functions raw/tmp/norm `*Data`.
* Usually, class names and package names match in case and class names have
their first letters capitalized.
* Avoid using `@` accessor and create dedicated accessor functions for your
class
* Please provide a more thorough description of the `tolerance` arguments `a`,
`b`, `c`.

**Comment by cbiagii** [comment]
Dear Marcel, @LiNk-NY  , 
Thank you so much for your review on my package.
I'm sure when I implement these recommended changes the package will look much better.
I will start working on the modifications now, as soon as I have everything ready I will reply your comment with the revisions topic by topic.

**Comment by cbiagii** [comment]
@mtmorgan , I changed the package name and consequently the repository.
I already made the necessary modifications and now I'm waiting to bump the package version in the new repository to trigger a new build.
Thanks!

**Comment by cbiagii** [comment]
Dear @LiNk-NY , 
Thank you very much for the review. I have made the solicited changes to ceTF package.
If there is something else to fix, please let me know.
Thanks!!


> # pcitRif #1329
> * Consider renaming the package to something that is easier to remember.
>   Packages with a lot of acronyms are not usually.

- **The package has been renamed to **ceTF**. I changed the repository name and added a new Webhook on the new repository. Now I'm waiting for the approval to bump and trigger the new version to start a build.**

> ## DESCRIPTION
> * It looks good.
> * The `Authors@R` section is overflowing. Please maintain it within 80 column
>   width.

- **Done!!**

> ## NAMESPACE
> * `*input`, `*input1`, and `*input2` and related methods point out a potential
>   area of improvement for the package
> * `*Data` functions may not be necessary (see below)

- **Done!! (Further details below)**

> ## vignettes
> * Please keep the text within the 80 column width margin. It makes the source
>   document easier to maintain and to review.
> * You do not need to explicitly install the dependencies for the package,
>   a simple installation of the package will automatically get them for the user.
>   Use `BiocManager::install("cbiagii/pcitRif")`

- **Done!!**

> ## R
> * Avoid using `cat` inside a function unless it is the show method. Use
>   `message` instead

- **Done!!**

> * `countsToTPM` can have a funcitonal argument that guides the conversion with
>   the default being the original computation.

- **Done!!**
**The _countsToTPM_ function has been deleted and the line code to perform it was incorporated in the _runAnalysis_ function.**

> * Arguments with default values will not be missing (e.g., `anno = NULL`) so
>   the test is not relevant, use `is.null`.

- **Done!!**

> * Avoid using index positions to subset and rather opt for names when
>   subsetting. For example, use `df[, "sample1"]` instead of `df[, 1]`.

- **Done!!**

> * Combine R files that are related to each other for example, some plotting
>   functions can be in the same file.

- **The functions _densitySig_ and _densityPlot_ has been deleted and combined in one function called _densityPlot_**;
**The _singleNetworkPlot_ function has been renamed by _netConditionsPlot_**;
**The old functios _netGOplot_ and _networkPlot_ has been deleted and combined in one function called _netGOTFPlot_**;
**The old functios _SmearPlotDE_ and _SmearPlotTF_ has been deleted and combined in one function called _SmearPlot_**.

> * Avoid using nested `ifelse`. Use a table of data to reassign values, see
>   Martin Morgan's response in this stackoverflow link:
>   https://stackoverflow.com/questions/39217432/r-improving-nested-ifelse-statements-multiple-patterns

- **Done!!**

> * Consider providing a more robust prototype for the `pcitrif` class. A list
>   of lists does not have much structure.

- **I reviewed all class structure and created the _CeTF_ class. This new class is based on SummarizedExperiment class containing 5 assays slots: _Data_, _DE_, _Input_, _Output_ and _Network_. For Data slot, i.e., has raw, tpm and norm data. Input slot has all the inputs for PCIT and RIF. And so on.**

> * It seems like creating accessors for specific inputs is not the right way to
>   go. Please create one general function that will access different parts of the
>   object based on an argument (similar to `SummarizedExperiment::assay`) for
>   `PCITinput*` and related functions. This can also apply to the data accessor
>   functions raw/tmp/norm `*Data`.

- **Only 5 accessors were created: _getData_, _getDE_, _InputData_, _OutputData_ and _NetworkData_. There is an argument for each accessor that allows the user to choose raw/tpm/norm, i.e. _getData(CeTFobject, "raw")_, and so on.**

> * Usually, class names and package names match in case and class names have
>   their first letters capitalized.

- **Done!!**

> * Avoid using `@` accessor and create dedicated accessor functions for your
>   class

- **Done!!**

> * Please provide a more thorough description of the `tolerance` arguments `a`,
>   `b`, `c`.

- **Done!!**

**Comment by LiNk-NY** [comment]
Hi Carlos, @cbiagii 
You may also want to match the package case with the class case, i.e., `CeTF`. 
This is convention for many packages such as `SummarizedExperiment`, `SingleCellExperiment`, `LoomExperiment`, etc.

**Comment by cbiagii** [comment]
Dear Marcel, @LiNk-NY 
I just updated the name of package to CeTF, as suggested. I updated too the repository name and added a new webhook to the repository.
I need the confirmation of @mtmorgan to trigger a new version to make the automated build.
Thanks!

**Comment by Kayla-Morrell** [comment]
Hey @cbiagii (cc @mtmorgan, @lshep, and @LiNk-NY), 

I have changed the name of the package in our database so you should be good to kick off another build. 

Best,
Kayla

**Comment by cbiagii** [comment]
Thank you so much, @Kayla-Morrell!!
Have a nice week. 
Best!!

**Comment by cbiagii** [comment]
Dear Marcel, @LiNk-NY, 
It's all OK with the automated build!!

**Comment by cbiagii** [comment]
Dear Marcel, @LiNk-NY ,
I fixed a minor errors, and now it's all OK with the automated build!!
Thanks.

**Comment by LiNk-NY** [comment]
Hi Carlos, @cbiagii 
Thanks for making those changes. 
Your package has been accepted. 
Thank you for your contribution!

Best,
Marcel

**Comment by cbiagii** [comment]
@LiNk-NY, Thank you for accepting the package. I am so glad to have worked with you these days and I am at your disposal for anything. Thanks very much,

Carlos Biagi Jr

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cbiagii.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CeTF")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CeTF

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
