### ISSUE TITLE
tidybulk: Friendly tidy wrappers for streamlined bulk transcriptional analysis

### ISSUE THREAD

**Issue by stemangiola** [Bioconductor/Contributions#1330]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stemangiola/tidybulk

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by stemangiola** [comment]
Hello,

I don't understand this.

WARNING: Update R version dependency from 3.6.0 to 4.0.

**Comment by dvantwisk** [comment]
BiocCheck is asking you to update to 4.0 because once your package is accepted, it will be included in bioc3.11 that will require R 4.0. We sometimes make exceptions for a developer to allow older versions of R if they have a reason for it, but in most cases we recommend that you update your depends line with R to `R (>== 4.0)`

**Comment by stemangiola** [comment]
Hello, That is unfortunate, because I wanted to keep available the original GitHub repo as well as Bioconductor. Putting such requirement is to strict, even for me as user. Could we proceed at the moment with 3.6 and upgrade around publication time (Apr)? Best wishes.Stefano  Stefano Mangiola | Postdoctoral fellowPapenfuss LaboratoryThe Walter Eliza Hall Institute of Medical Research+61 (0)466452544 From: Daniel Van TwiskSent: Wednesday, 8 January 2020 5:00 AMTo: Bioconductor/ContributionsCc: stemangiola; MentionSubject: Re: [Bioconductor/Contributions] ttBulk: Friendly tidy wrappers for streamlined bulk transcriptional analysis (#1330) BiocCheck is asking you to update to 4.0 because once your package is accepted, it will be included in bioc3.11 that will require R 4.0. We sometimes make exceptions for a developer to allow older versions of R if they have a reason for it, but in most cases we recommend that you update your depends line with R to R (>== 4.0)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dvantwisk** [comment]
Unfortunately, our webhook considers `master` as the development branch and therefore asks that you use the most recent version of R there. As your package ages through multiple releases, the Bioconductor git server will generate `RELEASE_X_X` branches that can be used with older versions of R. If you want to, you could direct R 3.6 users to a branch that you create on your github page that uses the older R versions.

**Comment by dvantwisk** [comment]
And thank you for bumping the R version, I will begin looking over your package soon.

**Comment by stemangiola** [comment]
> 
> 
> Unfortunately, our webhook considers `master` the development branch and therefore asks that you use the most recent version of R there. As your package ages through multiple releases, the Bioconductor git server will generate `RELEASE_X_X` branches that can be used with older versions of R. If you want to, you could direct R 3.6 users to a branch that you create on your github page that uses the older R versions.

Thanks. I hope the Bioconductor requirements for R is forced just for this major version change, not the minor one (i.e., I will be able to keep >= 4.0)

**Comment by dvantwisk** [comment]
Hello,

I've reviewed your package. It looks very well written and I have only a few issues. The biggest one involves the use of s3 dispatch. [REQUIRED] tags indicate changes that must be made or addressed. [CONSIDER] tags describe changes that are not required but are advisable. Please message me once you are finished making changes so I can have a second look at it.


R/data.R
- [ ] [REQUIRED] Please give better descriptions of your data available example
datasets. e.g. What is the source of the data? What is the structure?

R/methods.R
- [ ] [REQUIRED] It seems that you are using the S3 dispatch system to define
the functionality of your methods. Bioconductor requires that it's software uses
the S4 dispatch system. I ask that you create generics with `setGeneric()` that
you can then dispatch on using `setMethod()`. The S4 dispatch system is
described online:
https://www.bioconductor.org/help/course-materials/2017/Zurich/S4-classes-and-methods.html
https://www.bioconductor.org/help/course-materials/2010/AdvancedR/S4InBioconductor.pdf

**Comment by stemangiola** [comment]
Hello,

I am investigating S4 conversion, and there is a reason I am almost walled of that class. My package has the goal to integrate RNA sequencing analysis workflow with tidyverse in a natural way. I do it through tbl_df.

It is clearly stated that 

![image](https://user-images.githubusercontent.com/7232890/72584445-2b928680-393e-11ea-9406-e9db626a4b81.png)

Indeed my S3 object is just a tbl_df with an attribute memorizing column names, when I apply tidyverse verb, I just put it back with one line on the backend. All the rest comes for free.

Unless there is a way to automatically apply all methods working for tbl_df (e.g., head) to my object automatically.

head(tt_object) does not produce a tibble for example

**Comment by stemangiola** [comment]
up

**Comment by dvantwisk** [comment]
You should be able to utilize s3 objects within s4 by using the `setOldClass()` method. In your case, just put `setOldClass(tbl_df)` on the top of the file and this should allow you to inherit and set s4 methods to `tbl_df`.

**Comment by stemangiola** [comment]
I have limited experience in S4 but let's have a look to these two examples

```r
setClass("test", contains = "tbl_df", representation(tb = "tbl_df"))
my <- new("test", tb = tibble(a = 1))
my@tb %>%	mutate(b = 3)
```
```
# A tibble: 1 x 2
      a     b
  <dbl> <dbl>
1     1     3
```
It works in the sense that produces a tibble, however fails mainly because:

- the user has to use `@` therefore the goal of seamless integration of transcriptpmics tools with tidyverse fails. 

____________________________________________

A second example is 

```
setClass("test2", contains = "tbl_df")
my <- new("test2",  tibble(a = 1))
my %>%	mutate(b = 3)
```

```
  a b
1 1 3
```

It does not return a tibble for some reason.

I am not sure whether I am missing something

**Comment by stemangiola** [comment]
Furthermore, here is another undesired behavior

```r
my <- new("test2",  tibble(a = rnorm(100), b = 1))
my %>% nest(data = -b)
```
```r
Error: `x` must be a vector, not a `test2` object
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by stemangiola** [comment]
Hello,

could you please advise further? I need to understand if I have to considering withdraw from Bioconductor. So far I don't have enough experience to see a clean solution with forced S4 objects.

As tidyverse enters more and more the programming standards, have you had similar problems before?

**Comment by stemangiola** [comment]
I am not sure if you get notified of my comments without a version bump, so I did, although nothing has changed.

I hope I can receive an advice on the matter above.

Thanks a lot.

**Comment by stemangiola** [comment]
Hello,

a brief update:

- all ttBulk functions are not S4 methods
- the SumarizedExperiment object is not fully integrated in the framework as shown by the vignette.

**Comment by dvantwisk** [comment]
Hi, I apologize for the silence on my end. After discussing the tidyverse s4 issues with the rest of my group, we've concluded that it's fine for you to use the s3 system since it's difficult to get around the issues you've been having otherwise.

Integrating `SummarizedExperiment` in your package is highly recommended because it's usage is ubiquitous in Bioconductor, however, it is not required. Integrate it as best you can.

Message me back once you are finished making changes.

**Comment by stemangiola** [comment]
What I wrote is really weird. That must have been my subconscious. I meant

- all ttBulk functions are NOW S4 methods
- the SumarizedExperiment object is NOW fully integrated (and tested) in the framework as shown by the vignette.

I will push the latest changes updates or tomorrow and up the version.

P.S. the package is now called **tidyBulk**

**Comment by stemangiola** [comment]
Hello,

I have versioned UP but since the package changed name (sorry! :) ) Bioconductor must have lost the link.

The package is here

https://github.com/stemangiola/tidybulk

How can I fix the issue?

Thanks a lot.

**Comment by lshep** [comment]
There are steps to take to make the Bioconductor database recognize the package for automatic builds again; in the future please make sure to notify us so we can make updates.  Please change the repository link in the [first comment](https://github.com/Bioconductor/Contributions/issues/1330#issue-545567633) to be the new repo.  I have updated the database on our end.  As long as the webhook is still activated you should receive build reports on version bumps. Please do a version bump to test this and let us know if there are any issues.  I would also recommend changing the title of the issue to match your new name.

**Comment by stemangiola** [comment]
Hello @lshep  I cannot understand why now Windows gives me error

http://bioconductor.org/spb_reports/tidybulk_buildreport_20200302061240.html#tokay2_check_anchor

On my local windows machine complete the tests no problem.

Could you please advise? Thanks a lot.

**Comment by lshep** [comment]
I will look into it but in the meantime @dvantwisk  can review the results from the linux build.

**Comment by dvantwisk** [comment]
I apologize for the wait. I've reviewed your package and found that it is excellently written. I really don't have much to add. My only question is as follows:

vignettes/introduction.Rmd
- [ ] [REQUIRED] There is a use of `eval=FALSE` here. We generally want to see
using facing code run on the build system to ensure it is functioning properly.
Is there a reason to use `eval=FALSE` in this location?

**Comment by stemangiola** [comment]
Hello Daniel,

thanks for the compliment. 

The only eval=FALSE is

```{r eval=FALSE}
counts = bam_sam_to_featureCounts_tibble(
	file_names,
	genome = "hg38",
	isPairedEnd = TRUE,
	requireBothEndsMapped = TRUE,
	checkFragLength = FALSE,
	useMetaFeatures = TRUE
)
```
And is simply because involves read mapping from BAM files which is slow and file-size heavy. In the future I will try to prepare a dummy BAM file, but as you can imagine my packages involves more than 15 wrappers and this improvements will be done in a progressive way, if you guys allow.

Would be great if you could make this only exception, that I will aim to solve in the future release.

Please let me know for the new Windows error mystery.

**Comment by dvantwisk** [comment]
I apologize for the wait. Out team is in release territory and our volume of reviews has been increasing and I admit I somewhat left yours by the wayside because it didn't have many significant issues. It seems that the windows error was fixed on our build system. With regards to that `eval=FALSE`, the usage is acceptable, I just needed some justification for it since it's usage isn't ideal.

I've had one last review of your package and the recent changes look fine. I am going to move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stemangiola.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tidybulk")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tidybulk

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by stemangiola** [comment]
It is not clear how to update this repository

**Comment by mtmorgan** [comment]
This was answered on slack; in general ask questions there or on the [bioc-devel](https://stat.ethz.ch/pipermail/bioc-devel/) mailing list.
