### ISSUE TITLE
tscR

### ISSUE THREAD

**Issue by fpsanz** [Bioconductor/Contributions#1333]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fpsanz/tscR

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
As preliminary comment

- please do not depend on the 'tidyverse' package, but rather the specific packages you require.

- please make sure that all of your 'user-facing' functions that expect or return gene expression values allow the use of [SummarizedExperiment][] for robust and interoperable code. Please update your vignette to use SummarizedExperiment rather than matrix / data frame of expression values and corresponding design matrix

[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by fpsanz** [comment]
Dear reviewer

Thank you for your suggestions

In this commit (0.99.1) we have fixed bugs in BioCheckGitClone, removed the dependency on tidyverse and added new functionality to make the package compatible with summarizedExperiment container.

regards

**Comment by lshep** [comment]
Thank you for your submission. Please see comments below: 

**Build Report:**

- [ ] Could you please look into the NOTE from the tokay2? I don't have much
background in this so if you run into issues maybe it would be worth posting on
the bioc-devel@r-project on how often these are real vs false positives? 
```
* checking compiled code ... NOTE
Note: information on .o files for i386 is not available
Note: information on .o files for x64 is not available
File 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1333/810cf08/tscR.buildbin-libdir/tscR/libs/i386/tscR.dll':
  Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
File 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1333/810cf08/tscR.buildbin-libdir/tscR/libs/x64/tscR.dll':
  Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
File 'tscR/libs/i386/tscR.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
File 'tscR/libs/x64/tscR.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.
It is good practice to register native routines and to disable symbol
search.

```

- [ ] We strongly recommend unit tests.  While most are initially hestitant,
  many find that it helps with debugging and sometimes even development. 



**NEW**

- [ ] Don't add an empty news file. Either have valid entires or remove. We
  collect all package news files to put together the [release announcement](http://bioconductor.org/news/bioc_3_10_release/) at
  every bioconductor release.  we strongly encourage you to utilize it to notify
  users of any changes or bug corrections but is optional. See `?news` in R for
  formatting or
  [news](http://bioconductor.org/developers/package-guidelines/#news)


**DESCRIPTION**

- [ ] Please remove `lazyData: true` we have rarely found it useful and actually
  can slow down package installation. 


**vignette**

- [x] Nice background section and I appreciate the comparisons to other
  Bioconductor packages. 

- [ ] Please include Bioconductor installation instructions as default. You can
  include the github installation as 'development' version

- [ ] When I try to run your vignette manually with only the code shown, I get an ERROR 
```
> data(tscR)
> time <- c(1,2,3)
> sDist <- slopeDist(df, time)
Error in if (dim(x)[1] > 1000) { : argument is of length zero
```
I believe this is because whereever you defined the `df` it is actually not
shown in the vignette (perhaps you did echo=FALSE for that code chunk?) 


When ready for a re-review please don't forget to kick off a new build with a version bump and to comment back here with a summary of updates.

**Comment by fpsanz** [comment]
Hi @Ishep,
thank you so much for your comments. We think we've solved all the problems:

## Build report

* Could you please look into the NOTE from the tokay2? I don't have much
background in this so if you run into issues maybe it would be worth posting on
the bioc-devel@r-project on how often these are real vs false positives?

We think are false positives. We have tested in Windows 10 and Windows Home and we have not obtained that note. We also think it could be due to the windows server version. We attach our log:

```
...
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... OK
** running examples for arch 'x64' ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
  'tscR.Rmd' using 'UTF-8'... OK
...
```
* We strongly recommend unit tests. While most are initially hestitant,
many find that it helps with debugging and sometimes even development.

We've added unit test for functions

## NEWS

* We've added a little comment inside NEWS file

## DESCRIPTION

* We've removed `lazyData: true`

## Vignette

* We've included Bioconductor installation instruccions and github installation instruction.

* there was effectively an `echo=FALSE`. The code in the vignette code should work fine.


kind regards

Fernando

**Comment by fpsanz** [comment]
Hi @Ishep,

in this new version we have registered native routines and now the message "Found no calls to: R_registerRoutines, R_useDynamicSymbols" no longer appears in Bioconductor build report

kind regards

**Comment by lshep** [comment]
Sorry for the delay.  I'm working on the review and will have one for you in the next day.

**Comment by lshep** [comment]
Thank you for the current updates.  Please see some follow up comments below: 

**Vignette**

- [ ] newline for imputeSenators
```
> senators <- imputeSenators( bigDF, k = 100 )
Setting k to 30 . 10% of total data> 
```



**R code**

_combineCluster.R_

- [ ] You check the include for X twice instead of x and y.


_data.R_

- [ ] Please provide more detail on how this object was created. How was it
  simulated? 


 _frechetDist.R_

- [ ] If frechetDistC is better than why have this function at all? 
- [ ] Don't do two separate warning calls. It can be combined into one
```
>   warning("This function is slower than frechetDistC.\nYou should use C version")
```
- [ ] Does there need to be a tryCatch around changing x to a matrix? You make the assumption the user gave valid input that could be converted?
```
 if (!is.matrix(x)) {
    x <- as.matrix(x)
  }

```


_frechetDistC.R_

- [ ] Same comment above about checking that x is valid or tryCatch when
  converting to matrix

- [ ] Should there be other parameter checking to make sure time is a valid
  formatc? 

- [ ] If x was already changes to a matrix, wouldn't `t()` already be a matrix
  form and therefore not needed here?
```
 Df <- as.vector(as.matrix(t(x)))
# so couldn't it just be?
 Df <- as.vector(t(x))

``` 

_getCluster.R_

- [ ] Have a parameter check for k too. That a valid argument is given

_imputeSenators.R_

- [ ] Change the cat to a message()

Please make the above changes or respond to the question above.  When you are ready please do a version bump for a new build and comment here with what has been updated. 

Thank you and we look forward to getting your package submitted to Bioconductor.

**Comment by fpsanz** [comment]
Hello @lshep,

thank you for your comments. I'm going to answer point by point to your suggestions.

> Thank you for the current updates. Please see some follow up comments below:
> 
**Vignette**
> 
* [x ]  newline for imputeSenators
Fixed.
> 
> ```
> > senators <- imputeSenators( bigDF, k = 100 )
> Setting k to 30 . 10% of total data> 
> ```
>
> **R code**
> 
> _combineCluster.R_
> 
* [x ]  You check the include for X twice instead of x and y.
 Fixed.

> _data.R_
> 
* [x ]  Please provide more detail on how this object was created. How was it
>       simulated?
This object has been created specifically to be able to illustrate the operation of the package with the different distance metrics. Thus, from 3-4 hand-created trajectories (ascending, descending and quasi-horizontal) we have generated 300 trajectories with random variations from the original ones. The code used was similar to the one attached here:

```
df <- data.frame(T1 = c(4,3.9,4.1,4), T2=c(5.5, 4.3, 3.7, 2.5), T3 = c(7, 3.9,4.1, 1))
df1 <- matrix(NA, nrow=100, ncol=3)
df2 <- matrix(NA, nrow=100, ncol=3)
df3 <- matrix(NA, nrow=100, ncol=3)
df4 <- matrix(NA, nrow=100, ncol=3)
for(i in seq(1,75)){
  df1[i,] <- jitter(as.numeric(df[1,]), factor = 2.5)
  df2[i,] <- jitter(as.numeric(df[2,]), factor = 7.5)
  df3[i,] <- jitter(as.numeric(df[3,]), factor = 7.5)
  df4[i,] <- jitter(as.numeric(df[4,]), factor = 2.5)
}
df <- as.data.frame(rbind(df1,df2,df3, df4))
names(df) <- c("T1","T2","T3")
```
    

> 
_frechetDist.R_
> 
* [x ]  If frechetDistC is better than why have this function at all?

Certainly it would not be necessary as frechetdistC is faster. But since our functions are matrix-adapted versions of the functions published in the kmlShape package (distFrechet and distFrechetR) we've wanted to keep both versions. If this is a trouble it could be removed

* [x ]  Don't do two separate warning calls. It can be combined into one
Fixed.
> 
> ```
> >   warning("This function is slower than frechetDistC.\nYou should use C version")
> ```
> 
* [x ]  Does there need to be a tryCatch around changing x to a matrix? You make the assumption the user gave valid input that could be converted?
Added tryCath that controls the correct conversion and also a control that the dimensions of the converted matrix are correct
> 
> ```
>  if (!is.matrix(x)) {
>     x <- as.matrix(x)
>   }
> ```
> 
> _frechetDistC.R_
> 
 * [x ]  Same comment above about checking that x is valid or tryCatch when
   converting to matrix
Fixed.
> 
* [x ]  Should there be other parameter checking to make sure time is a valid
      formatc?
Added and fixed.
> 
* [x ]  If x was already changes to a matrix, wouldn't `t()` already be a matrix
    form and therefore not needed here?
Fixed.
> 
> ```
>  Df <- as.vector(as.matrix(t(x)))
> # so couldn't it just be?
>  Df <- as.vector(t(x))
> ```
> 
 _getCluster.R_
> 
 * [x ]  Have a parameter check for k too. That a valid argument is given
This parameter is already controled by pam function whose is called from getCluster
> 
 _imputeSenators.R_
> 
* [x ]  Change the cat to a message()
Fixed.
> 
> Please make the above changes or respond to the question above. When you are ready please do a version bump for a new build and comment here with what has been updated.
> 
> Thank you and we look forward to getting your package submitted to Bioconductor.

**Comment by lshep** [comment]
Could you add the explanation that you gave here of how the data was calculated in the man file for data.R.   otherwise the rest of the changes look good.

**Comment by fpsanz** [comment]
> Could you add the explanation that you gave here of how the data was calculated in the man file for data.R. otherwise the rest of the changes look good.

hi @lshep,

We've updated data.R including documentation explains how this dataset was created

regards.

Fernando

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fpsanz.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tscR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tscR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
