### ISSUE TITLE
MEAT

### ISSUE THREAD

**Issue by sarah-voisin** [Bioconductor/Contributions#1336]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sarah-voisin/MEAT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It seems like the first step in the vignette should be to assemble the data into a standard Bioconductor object -- not sure if this is SummarizedExperiment or something from the minfi package -- and *then* perform cleaning to avoid having to explicitly coordinate phenotype / genetic data.

**Comment by sarah-voisin** [comment]
Hi,

I have made the following changes:
1) Modified the data_cleaning.R file to pass the testthat
2) added ".Rproj" in the gitignore file
However, I do not understand the following WARNING:
**WARNING: Update R version dependency from 3.6 to 4.0**

Can you help me solve it?

Further to Martin's comment, is it necessary for me to create a standard Bioconductor object instead of relying on a matrix with a separate phenotype file?

Thank you

**Comment by dvantwisk** [comment]
R 4.0 is the current development versio of R. Since the next release of Bioconductor, bioc3.11, will use R version 4.0, we ask that your package also requires this version. That means to change the line `Depends: R (>= 3.6)` in the `DESCRIPTION` file to `Depends: R (>= 4.0)`.

The `SummarizedExperiment` class is used to store assays. It seems that you are able to use this class in place of one of your matrices. It is a very widely utilized class in Bioconductor and it would make your package a lot easier to use if it would work well with `SummarizedExperiment`.

**Comment by sarah-voisin** [comment]
Hi,

Thank you for your help. I have made the change to the DESCRIPTION file.

I would not mind using a SummarizedExperiment for my package, although it is not essential for what my package is doing. I just have a little size issue. If I put the example dataset into a SummarizedExperiment object instead of a simple matrix, its size becomes too large to be included in the package (i.e. from ~4Mb to ~8Mb). I have already reduced my example dataset to only two samples, and trimmed the values to 3 digits after the 0 to limit the size of the file, but I can't further limit the size. Therefore, may I proceed without using a SummarizedExperiment object?

Last question: when I increment the package version, which part should I increment? I have these options:
1: major --> 1.0.0
2: minor --> 0.100.0
3: patch --> 0.99.1
4:   dev --> 0.99.0.9000

Thank you

**Comment by dvantwisk** [comment]
It's advisable that you use `SummarizedExperiment` due to its ubiquity in Bioconductor. I'm not sure how you are going about saving the file, as an .rda? I think the ideal thing to do would be to save the example file as a plain file, then to convert to a `SummarizedExperiment` for usage in the vignette. Is this doable?

You should increment it in the third manner (e.g. patch -> 0.99.1)

**Comment by sarah-voisin** [comment]
I have made the required changes and used a SummarizedExperiment object in the package. Let me know if it works now.

**Comment by sarah-voisin** [comment]
I have:
1. added ".Rproj" in the gitignore file
2. changed class() to is() in the functions
3. However, I do not understand the following WARNING:
Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/RtmpCMKief/R.INSTALL19807ff431e2/MEAT/man/BMIQcalibration.Rd:10: file link 'SummarizedExperiment' in package 'SummarizedExperiment' does not exist and so has been treated as a topic

Thank you

**Comment by sarah-voisin** [comment]
I have typed this in the terminal to avoid git-tracking the Rproj file:
git rm --cached MEAT.Rproj
But I don't know what to do next.

**Comment by lshep** [comment]
if you do a `git status` it should show that it is staged to be removed -  You need to do a `git commit` and push up the change (don't forget the version bump)

**Comment by sarah-voisin** [comment]
I have been trying to address the main issue of "ERROR: System Files found that should not be git tracked: MEAT.Rproj" but I don't know what else to try. Can you help me?

**Comment by lshep** [comment]
Did you try the following: 
```
git rm MEAT.Rproj
# bump version in DESCRIPTION
# I also recommend adding MEAT.Rproj in the .gitignore file
git  commit -a
git push 
```

**Comment by sarah-voisin** [comment]
I do not understand where this error message is coming from:
Running the tests in tests/testthat.R failed.
Complete output:
  > library(testthat)
  > library(MEAT)
  Error: package or namespace load failed for 'MEAT' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
   there is no package called 'rtracklayer'

MEAT does not use 'rtracklayer' at all, and I don't understand why the error is in the testthat.R file.

**Comment by lshep** [comment]
I'm going to kick off a manual build for your package - one of your dependencies may use rtracklayer and therefore indirectly mean your package does -  in any case the builders have rtracklayer installed so its odd that it wasn't found

**Comment by dvantwisk** [comment]
Hello,

I apologize for the silence from me. It looks like Lori helped resolve your issue and the only remaining issues are a minor documentation issue and it also looks like you need to include `wateRmelom` imports in your namespace. I am going to begin reviewing your package now since these issue are minor.

**Comment by sarah-voisin** [comment]
Hi, may I have an update on your feedback?

**Comment by lshep** [comment]
Please see this post on this warning and how to fix it
https://stat.ethz.ch/pipermail/bioc-devel/2019-April/014999.html

**Comment by dvantwisk** [comment]
I've reviewed your package. I think the package looks very well written. Aside from a minor knit-picks that aren't worth mentioning, I really don't have anything to add. I am going to move to accept your package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sarah-voisin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MEAT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MEAT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
