### ISSUE TITLE
(inactive) DeMixT version changing

### ISSUE THREAD

**Issue by pengyang0411** [Bioconductor/Contributions#1343]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yourusername/yourpackagename

Confirm the following by editing each check box to '[x]'

- [ ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ ] The 'devel' branch for new packages and features.
- [ ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by pengyang0411** [comment]
Hello Bioconductor Team,

I am a new maintainer of DeMixT package.

We aimed to release a new updated DeMixT package from version 1.3.1 to 1.5.0 in devel branch.
However, I got the following error message when I try to push the package public:
Error: Illegal version bump from '1.3.1' to '1.5.0'.

I am very confused about this issue, since I noticed that we need use odd number for y(x.y.z) in devel. How can I address this issue?

Thanks,
Peng

**Comment by mtmorgan** [comment]
usually new commits increment z within a release cycle, so the next version would be 1.3.2, 1.3.3, 1.3.4. At the next release this roles over to 1.4.0 for users (Bioconductor release 3.11) and 1.5.0 for to start the next devel cycle. See [here][].

Please though ask questions on the [bioc-devel][] mailing list.

[here]: https://bioconductor.org/developers/how-to/version-numbering/
[bioc-devel]: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by mtmorgan** [comment]
Remember that only bug fixes are introduced into the 'release' branch. So your major changes are added to the 'devel' branch. The devel branch will become the next release, some time in April. So if you make changes now, with version 1.3.2, etc, then in April this will become release 1.4.0 for the user; you cannot make version 1.4.0 available to the user before then.

This is so that the user has a stable environment to work in, and you as a developer can address any unexpected problems as they arise in the devel branch, before the next release.

Usually a 'major' change is marked by transition from version 1.x.y in the current release to 2.0.0 in the next release. This is accomplished by incrementing the version number to 1.99.0, 1.99.1, 1.99.2, ... etc in the current devel branch. After the next release the devel branch will be 2.1.0 and the release will be 2.0.0.

If you'd like to do this, then you need to communicate on the bioc-devel mailing list.

**Comment by pengyang0411** [comment]
Hi Martin,

Thank you very much for detailed explanation. I just pushed updated package
into remote/upstream/master and I double checked all the files has been
updated; however, there is no changes on the DeMixT website in biocondoctor,
https://bioconductor.org/packages/devel/bioc/html/DeMixT.html

Can you help me update it or is there anything I can do?

Thanks,
Peng
