### ISSUE TITLE
reconsi

### ISSUE THREAD

**Issue by sthawinke** [Bioconductor/Contributions#1345]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CenterForStatistics-UGent/reconsi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
DESCRIPTION

- It might help, in the Description: field, to indicate the domain (metagenomics?) where this package might be helpful.

vignettes

- good!

- please use `BiocManager::install("reconsi")`; seems best practice remove potential ambiguity of the `install()` function being invoked for this crucial operation.

R

- F_calcWeights.R please more carefully document arguments, for instance `logDensPerm` tells us what the rows are but not the columns.
- consider using formatR or similar to standardize your code formatting, for instance some lines in `F_getGO.R` are indented and others are not, and generally somethign that is compactly written as
  ```
  if(length(z0Quant)==1) {z0Quant = sort(c(z0Quant, 1-z0Quant))}
    statObs = statObs[!is.na(statObs)] #ignore NA values
  ```
  is more readable as
  ```
  if (length(z0Quant) == 1) {
      z0Quant = sort(c(z0Quant, 1 - z0Quant))
  }
  statObs = statObs[!is.na(statObs)]#ignore NA values
  ```
  
- pay attention to formatting of warning / errro messages, for instace
  ```
  warning("Consensus null estimation did not converge,
      please investigate cause! \n")}
  ```
  produces output
  ```
  Warning message:
  Consensus null estimation did not converge,
                please investigate cause!
  ```
  where the indentation is nonsensical.
- F_getTestStats.R it is usually best practice to start each user-facing function with assertions that test validity of incoming arguments. In this way your code can focus on robustly implementing the algorithm, and fail early on incorrect input, rather than mingling assertions with algorithm. E.g., start `getTestStats()` with checks such as
  ```
  stopifnot(
      is.matrix(Y), identical(mode(Y), "numeric"), length(dim(Y)) == 2,
      ## checks on other arguments
  )
  ```
- standardize function naming convention (preferably to lowerCamelCase) including for internal functions (where a preceding `.` might indicate that it is not exported, e.g., `.ptEdit()`, `.qtEdit()` in F_pt.edit.R
- `stop(paste(...))` (also `warning()`, `message()`) can usually be replaced by `stop(...)` (`stop()` calls `paste(...)` internally).
- `rowMultiply()` might instead be implemented as `t(t(matrix) * vector)`

tests

- it is usually best practice to write self-contained tests; perhaps not important for the current set of tests, but
  ```
  n = 50; p = 100
  mat = matrix(rnorm(n*p), n,p)
  vec = rnorm(p)
  
  test_that("Rowmultiply works", {
      expect_equal(rowMultiply(mat, vec), t(t(mat)*vec))
  })
  ```
  might be revised so the matrix is formed inside the test
  ```
  test_that("rowMultiply works", {
      n = 50; p = 100
      mat = matrix(rnorm(n*p), n,p)
      vec = rnorm(p)
      expect_equal(rowMultiply(mat, vec), t(t(mat)*vec))
  })
  ```

**Comment by sthawinke** [comment]
Thanks for your careful review and suggestions. We made following changes to the package:

DESCRIPTION

The description has been extended by:

"This dependence is common in genomics applications, e.g. when combining flow cytometry measurements with microbiome sequence counts."

VIGNETTE

BiocManager::install("reconsi") is used now

R

 - F_calcWeights

Argument description _logDensPerm_ has been extended to

"(...), and p columns for the p observed test statistics." has been added.

The description of _fdr_ has been modified to

"A vector of local false discovery rates for the observed tests statistics of length p."

- Formatting

The if-else clauses have been extended where necessary, and the indentation has been cleaned up.

- Messages

The indentation in the message formatting has been adapted.

- Early checks

The checks on the statistical tests have been moved to the user interface F_reconsi.R, and some basic checks have been added at the very beginning.

- Naming convention

The lowerCamelCase convention has been adopted all over the package.

- Stop-paste

The paste statements have been omitted.

- rowMultiply

t(t(matrix) * vector) is indeed possible, but our implementation is faster. We added this clarification to the details.

TESTS

Most tests have been made self-contained, except for the test-reconsi.R script, where the same matrix is used again and is also modified for the later checks.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sthawinke.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("reconsi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/reconsi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
