### ISSUE TITLE
GCSConnection

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/Contributions#1347]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jiefei-Wang/GCSConnection

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@nturaga I'll take over this review (when the next package comes in...)

**Comment by mtmorgan** [comment]
Thanks for this interesting package!

General

- Introduce functions to copy (`gcs_cp(from, to)`, via `httr::write_disk()`?) files to and from buckets without realizing them in memory?

- Introduce function to list bucket / path content `gcs_dir()`, including support for recurssive and 'long' (e.g., bucket size) listings?

DESCRIPTION

- Expand the Description: a little, e.g.,
  ```
    Description: Create R 'connection' objects to google cloud storage
        buckets using the Google REST interface.  Both read and write
        connections are supported.
  ```

- systemDependencies: I don't think these are relevant anymore?

vignettes

- Provide some information about authentication

R

- perhaps names functions `gcs_set_read_buff()`, `gcs_set_write_buff()`. Also return the old value `invisible(old_size)`.

- I think the file XMLRequest.R does not contain XML requests? It's confusing.

- In describing `@param`, use standard R terms, e.g., `@param description character string ...` -- R doesn't have a 'character string', but rather `@param description character(1) ...`

- zzz.R: `pkg_namespace <- getNamespace(pkgname)`

src

- I was surprised to see altrep in the C++ code, can you explain why it is necessary?

- utils.cpp: do the `Rf_lang*()` return values need to be PROTECTed? They could be garbage-collected in `R_forceAndCall()`?

**Comment by Jiefei-Wang** [comment]
Thanks for your suggestions, @mtmorgan .  I have updated the package according to your comments:

1. Introduce functions to copy (gcs_cp(from, to), via httr::write_disk()?) files to and from buckets without realizing them in memory?
Done, the function name is `gcs_cp`.

2. Introduce function to list bucket / path content gcs_dir(), including support for recurssive and 'long' (e.g., bucket size) listings?
This is a very good suggestion. I have implemented it and users can browse and manage files using the function. It can be used to create connections.


3. Expand the Description: a little, e.g.,

  Description: Create R 'connection' objects to google cloud storage
      buckets using the Google REST interface.  Both read and write
      connections are supported.
Done

4. systemDependencies: I don't think these are relevant anymore?
Yes, it has been removed.

5. Provide some information about authentication
A few sections have been added into the vignette

6. perhaps names functions gcs_set_read_buff(), gcs_set_write_buff(). Also return the old value invisible(old_size).
Done

7. I think the file XMLRequest.R does not contain XML requests? It's confusing.
I have renamed it to RESTRequest.

8. In describing @param, use standard R terms, e.g., @param description character string ... -- R doesn't have a 'character string', but rather @param description character(1) ...
Done

9. zzz.R: pkg_namespace <- getNamespace(pkgname)
Done

10. I was surprised to see altrep in the C++ code, can you explain why it is necessary?
Since downloading data requires calling R functions from C++, and the data needs to be copied from R object to a cache memory, using ALTREP can save the cost of memory copy and the creation of an R vector. Though the effect should be minor.

11. utils.cpp: do the Rf_lang*() return values need to be PROTECTed? They could be garbage-collected in R_forceAndCall()?
Thanks for pointing it out, the variable has been protected now.

**Comment by mtmorgan** [comment]
Sorry to be slow. 

- please make sure that `gcs_dir()` and `gcs_cp()` support path or from / to arguments that are full URIs, e.g., `gcs_dir("gs://genomics-public-data/")`

- for `gcs_dir()`, use `depth = ` rather than `deep = ` as argument. I don't understand the role of `delimiter=`; I understand that the buckets are arbitrary identifiers, but the use of `/` must be a 'standard' way to convey the illusion of hierarchy?

- I noticed this bug

```
> gcs_dir("genomics-public-data/", recursive=TRUE)
Error in new("FolderClass", full_path = c("genomics-public-data", "clinvar" :
  attempt to use zero-length variable name
```

- `names(x <- gcs_dir(path = "genomics-public-data/"))` should not combine 'user-facing' and internal (e.g., `#file_names#`, `#file_sizes#`) information; create separate (non-exported?) accessors e.g., `file_size()`.

- although tab-completion is 'cute', it doesn't seem very functional, e.g.,  
~~~
x$`references/`$`b37/`
~~~
a nicer alternative would tab complete and resolve `x$references` and `x$references$b37`; it seems like `x[["references"]]` and `x[['references/b37"]]` should also work.

- `gcs_connection()` ignores `bucket =` when `file =` include a bucket; it should instead fail.

- provide unit tests for `gcs_cp()`.

- The 'httr' (and probably google* packages) depend on xml2, whereas you introduce the XML package with similar functionality. Please use the xml2 package. The xml2 package will likely be listed in Imports:, and does not need to be in Suggests:

**Comment by Jiefei-Wang** [comment]
Hello @mtmorgan ,

Thanks for your comments, the package is ready for a second review, here are some key changes I made:

1. `gcs_cp` and `gcs_dir` supports both URI and path now.

2. `gcs_cp` supports upload/download folders to/from the cloud

3. for `gcs_dir`, the return object `x` can go to the parent folder using `x[[".."]]`, this is also supported by the dollar operator. You can even use it to switch between buckets. Directly navigate through multiple folders is available now(E.g. `x[["../folder1/folder2/"]]`)

4. The tab-completion would show folder names without `/`

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jiefei-Wang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GCSConnection")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GCSConnection

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
