### ISSUE TITLE
PeacoQC

### ISSUE THREAD

**Issue by AnneliesEmmaneel** [Bioconductor/Contributions#1348]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saeyslab/PeacoQC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
Note: [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput cytometry data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# PeacoQC review

## R CMD build

* ok

## R CMD check

* ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## man

* ok

## vignette

* Consider using BiocStyle for the vignette. It adds formatting in a Bioconductor
  standardized way to you vignette.
  https://bioconductor.org/packages/release/bioc/html/BiocStyle.html

* There are other ways to show commented out code, more stardard with how 
  markdown is written. Please use `eval=FALSE` if needed to show commented out
  code.
  
* The vigentte produces artifacts in the users directory. There should be clear 
  warnings to show that this is happening. Usually vignettes when evaluated just
  produce an HTML file but do not save the plots and results.
  
  Consider this, as a new user, there is a higher chance that the vignette is being
  read before the function man page. 
  
## R

* You don't need `which()` in this line of code,

```
if (length(which(selection == FALSE))/length(selection) > 0.1) 
```

* You don't need `paste0()` in your `warning()` functions unless you are recycling vectors,

```
warning(paste0("More then ",
    round(length(which(selection == FALSE))/length(selection) * 100, 2),
    "% is considered as a margin event in file ",
    basename(ff@description$FILENAME), ". This should be verified."))
```

* Do not accecss slots in a class with `@` like in `ff@description`. 
  Please write accessor functions. Pleaes read,  http://bioconductor.org/developers/how-to/efficient-code/.

  There are multiple places in your code base where this is done.

* It seems like you need the `matrixStats::colMedian()` function here. 
  You can avoid writing a loop here and just use the highly optimized 
  package in matrixStats.

```
  channel_medians <- vapply(breaks,
            function(x){stats::median(ff@exprs[x,channel])},
            FUN.VALUE = numeric(1))
```

* I highly recommend you consider breaking up the function `PeacoQCSignalStability()`.
  Try to write smaller functions, and stitch them together in the final function
  `PeacoQCSignalStability()`. The way it is written right now, makes it very prone
  to errors.
  
  I want to stress on this on other functions as well. It is extremely hard for the 
  reviewer to follow a 200-300 line function. Break them up. This is important as 
  good coding practice. It helps you write functions where blocks of code are being repeated.
  Please go through the entire codebase once and make these changes.
  
 * Instead of `if(display_peaks == TRUE)` you can just write `if(display_peaks)`.
 
 * Tailor your end user messages to fit this pattern, http://bioconductor.org/developers/how-to/coding-style/
 
 ```
 End-User messages

message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```

* Please go through your code base and fix the issues i've mentioned. Note that i've
  mentioned issues on specific lines of code, but these issues happen repeatedly in your
  codebase. Fix all of them. I highly encourage you go through the following documents 
  on the Bioconductor website and follow them as rigidly as possible,
  
  http://bioconductor.org/developers/how-to/coding-style/
  
  http://bioconductor.org/developers/how-to/efficient-code/
  
* Consider writing unit tests as well.

**Comment by nturaga** [comment]
Hi, 

We usually give maintainers 14 days to respond to comments to know that they are actively working on the package.

Please take this as your 14 day notice to respond.

**Comment by AnneliesEmmaneel** [comment]
Hi,

I'm sorry that I did not respond yet. I am currently working on the package but it is taking a bit more time than I thought. 

Kind regards.

**Comment by lshep** [comment]
Is this ready for review? If so please comment with a summary of what was addressed

**Comment by AnneliesEmmaneel** [comment]
No not yet, there are still some issues that I have to address.

**Comment by nturaga** [comment]
Please note that if your package is ready for review you need to let me know.

**Comment by AnneliesEmmaneel** [comment]
Dear,
I am currently trying to splitting up my code into multiple functions to make it a bit more readable.
But while doing this, I am coming across some errors or ways where I can still improve my code.

It is a bit of a slow job but I am certainly working on it :). 

For now, I tried to address most of the comments but I should still check for them all when my code is sort of finalized.
When it is ready, I will try to respond here with what kind of changes I did and how I tried to improve my package but for now there is still some work to do.

My apologies that it is taking so long but this is the first time I created a package and I still have a lot to learn.

Thank you for your patience!

Kind regards,
Annelies Emmaneel

**Comment by nturaga** [comment]
Hi, please let me know when you are ready for another review.

**Comment by AnneliesEmmaneel** [comment]
Hi, 
I think the package is ready for another review. I made following changes according to your remarks:

> ## vignette
> * Consider using BiocStyle for the vignette. It adds formatting in a Bioconductor
>   standardized way to you vignette.

The BiocStyle is now used for the vignette.

> * There are other ways to show commented out code, more stardard with how
>   markdown is written. Please use `eval=FALSE` if needed to show commented out
>   code.

I made more blocks and used the eval = FALSE for the blocks that are not run.

> * The vignette produces artifacts in the users directory. There should be clear
>   warnings to show that this is happening. Usually vignettes when evaluated just
>   produce an HTML file but do not save the plots and results.
>   Consider this, as a new user, there is a higher chance that the vignette is being
>   read before the function man page.

Since the usage of the package requires to make a new folder, I added some warnings in the vignette. The package will be used in a cleaning process and the figures made are too large to display directly. Please let me know if the warnings are not clear enough.

> 
> ## R
> * You don't need `which()` in this line of code,
> 
> ```
> if (length(which(selection == FALSE))/length(selection) > 0.1) 
> ```
> 

I tried to rerun this code without the which but this ended up with my two lengths being the same. I need the shorter version of the (which(selection) == F) to be able to calculate the percentages.

> * You don't need `paste0()` in your `warning()` functions unless you are recycling vectors,
> 
> ```
> warning(paste0("More then ",
>     round(length(which(selection == FALSE))/length(selection) * 100, 2),
>     "% is considered as a margin event in file ",
>     basename(ff@description$FILENAME), ". This should be verified."))
> ```
> 

I removed all the paste0 arguments in my warning statements.

> * Do not accecss slots in a class with `@` like in `ff@description`.
>   Please write accessor functions. Pleaes read,  http://bioconductor.org/developers/how-to/efficient-code/.
>   There are multiple places in your code base where this is done.

I changed all the `@`s by their flowCore:: functions.

> * It seems like you need the `matrixStats::colMedian()` function here.
>   You can avoid writing a loop here and just use the highly optimized
>   package in matrixStats.
> 
> ```
>   channel_medians <- vapply(breaks,
>             function(x){stats::median(ff@exprs[x,channel])},
>             FUN.VALUE = numeric(1))
> ```
> 

I tried using this function but I always ended up using a loop since the breaks variable contains a list of overlapping lists for which the medians have to be calculated. If you have a more efficient way to solve this, please let me know.

> * I highly recommend you consider breaking up the function `PeacoQCSignalStability()`.
>   Try to write smaller functions, and stitch them together in the final function
>   `PeacoQCSignalStability()`. The way it is written right now, makes it very prone
>   to errors.
>   I want to stress on this on other functions as well. It is extremely hard for the
>   reviewer to follow a 200-300 line function. Break them up. This is important as
>   good coding practice. It helps you write functions where blocks of code are being repeated.
>   Please go through the entire codebase once and make these changes.

I tried to split up the bigger functions (PeacoQC (previously PeacoQCSignalStability) and PlotPeacoQC). 

> * Instead of `if(display_peaks == TRUE)` you can just write `if(display_peaks)`.

I changed all the occurrences where this happened except on one spot where for some strange reason my function stopped working if I used this type of coding (In the IsolationTreeSD function).

> * Tailor your end user messages to fit this pattern, http://bioconductor.org/developers/how-to/coding-style/
> 
> ```
> End-User messages
> 
> message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
> warning() communicates unusual situations handled by your code.
> stop() indicates an error condition.
> cat() or print() are used only when displaying an object to the user, e.g., in a show method.
> ```
> 

I tried to adapt everything according to these guidelines.

> * Please go through your code base and fix the issues i've mentioned. Note that i've
>   mentioned issues on specific lines of code, but these issues happen repeatedly in your
>   codebase. Fix all of them. I highly encourage you go through the following documents
>   on the Bioconductor website and follow them as rigidly as possible,
>   http://bioconductor.org/developers/how-to/coding-style/
>   http://bioconductor.org/developers/how-to/efficient-code/

I tried to adapt as much as possible according to these rules but I did not change my variable and function names yet. This was a whole lot of work and I don't really see the added advantage here. I can change the function names but the variable names will take a really long time. 

> * Consider writing unit tests as well.

I am trying to write these but I find them very hard. They are not included yet in the package but I am working on them.

I hope these changes are all ok.

Kind regards,
Annelies Emmaneel

**Comment by nturaga** [comment]
Hi,

I've taken a look at your package again it looks sufficient. I'll accept the package once a new build is done and i've taken a look at it.

Please bump the version again once, I want to see if the warning you are seeing on the build report persists. 

Best,

Nitesh

**Comment by AnneliesEmmaneel** [comment]
Dear,

I thought I fixed the issue but I figured out that the warning can be traced back to the latest flowCore or flowWorkspace package.
My colleague had the same warnings with the latest updates but I did not until I updated these packages.

With kind regards,
Annelies Emmaneel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/AnneliesEmmaneel.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PeacoQC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PeacoQC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
