### ISSUE TITLE
DAMEfinder

### ISSUE THREAD

**Issue by sorjuela** [Bioconductor/Contributions#1349]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/markrobinsonuzh/DAMEfinder

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sorjuela** [comment]
Hi @Kayla-Morrell , I get some notes in the build report I don't really know how to fix:
1. ```
NOTE: Consider clarifying how 10 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    function (object)
      calc_logodds (MM)
      calc_logodds (UU)
      calc_logodds (MU)
      calc_logodds (UM)
      read_tuples  (MM)
      read_tuples  (UU)
      read_tuples  (UM)
      read_tuples  (MU)
      read_tuples  (pos2)
      read_tuples  (pos1)
```

How can I clarify this? they are columns read-in from the `methtuple` output (a tsv.gz file).

**Comment by Kayla-Morrell** [comment]
@sorjuela - In calc_logodds, I would try adding `MM <- NULL`, `UU <- NULL`, etc. (or just `MM <- UU <- MU <- UM <- NULL` for simplicity) before using them. That should also clear up the later use of the objects in read_tuples. Then I would try adding `pos2 <- NULL` and `pos1 <- NULL` (or just `pos2 <- pos1 <- NULL`) in read_tuples and that should clear those up. Hopefully this works for you.

Best,
Kayla

**Comment by sorjuela** [comment]
Hi @Kayla-Morrell I managed to reduce to 2 NOTEs, is it ok if I leave long functions? :)

**Comment by Kayla-Morrell** [comment]
@sorjuela - good work! The 2 NOTEs are fine to leave, just minor suggestions from us. I will post my initial review of the package here in the next few days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@sorjuela - Thank you for submitting to _Bioconductor_. The package looks pretty good and I have just a few notes to make. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The `doc/` directory is not needed and should be removed.

## DESCRIPTION

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field that has 
the relevant link to Github for reporting Issues.

## Data

- [ ] SUGGESTION: I would move the files in `data-raw/` to the `inst/script/` 
directory 

## Vignettes

- [ ] REQUIRED: There shouldn't be any unnessary files in this directory unless 
they are used in the vignette. It looks like the png files are being used in the 
README file. Therefore, those files belong in an `inst/figures/` directory.

- [ ] SUGGESTION: I would seperate the 'Session Info' and 'References' sections 
into two seperate sections. 

## Man pages

- [ ] SUGGESTION: For any function that is documented but isn't exported you
should add the tag `@keywords internal` so that they are removed from the
documenation index.

## R code

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 194 lines that are not.

- [ ] REQUIRED: The file 'input_split_bams.R.inprogress' should be completed. 
This function is being exported, there is not examples being run, and there 
should not be 'inprogress' included in the name of the file.

Best,
Kayla

**Comment by sorjuela** [comment]
Hi @Kayla-Morrell  thank you for the review. I implemented all your comments, except the suggestion on the line indents.

**Comment by Kayla-Morrell** [comment]
@sorjuela - Perfect, thank you for making those changes. Everything looks good now and I'm happy to accept the package. Thank you again for your contribution.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sorjuela.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DAMEfinder")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DAMEfinder

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
