### ISSUE TITLE
fluentGenomics

### ISSUE THREAD

**Issue by sa-lee** [Bioconductor/Contributions#1350]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sa-lee/fluentGenomics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sa-lee** [comment]
cc @mikelove

**Comment by LiNk-NY** [comment]
Hi Stuart, @sa-lee 

Thank you for your submission. 
Please see the review below. 
Feel free to comment if you have any questions.

Best,
Marcel

---

# fluentGenomics #1350

## DESCRIPTION

* Looks good.

## NAMESPACE

* Looks okay although *cache* functions seem to be helpers rather than
main functions.

## vignettes/

* Formatting looks great! R code could be formatted with 4 spaces but this
is a minor detail.
* The `*.bib` and `workflow.png` files should be in the main `vignettes` folder.
Is there a reason for putting them in `/inst/vignettes`?
* 'stable version' should read 'development version' after acceptance and
until Bioconductor release.

## data/

* It would be good if the "peaks" data had a slightly more descriptive name

## docs/

* Please remove built documentation from the source package (`docs` folder).
This is generated when the package is built.

## Other

* 'pkgdown' files (e.g., `_render.R`, and `_pkgdown.yml`) should go in another
branch as they are related to the website build and not the Bioconductor
software.
* `WORDLIST` file should also be in that branch.
* Consolidate `LICENSE` files, if possible.

**Comment by sa-lee** [comment]
Hi Marcel @LiNk-NY , 

> Hi Stuart, @sa-lee
> 
> Thank you for your submission.
> Please see the review below.
> Feel free to comment if you have any questions.
> 
> Best,
> Marcel
> 
> # fluentGenomics #1350
> ## DESCRIPTION
> * Looks good.
> 
> ## NAMESPACE
> * Looks okay although _cache_ functions seem to be helpers rather than
>   main functions.
> 

I've removed this now.

> ## vignettes/
> * Formatting looks great! R code could be formatted with 4 spaces but this
>   is a minor detail.
> * The `*.bib` and `workflow.png` files should be in the main `vignettes` folder.
>   Is there a reason for putting them in `/inst/vignettes`?
> * 'stable version' should read 'development version' after acceptance and
>   until Bioconductor release.

I've made these changes. I think I originally had this in `/inst/vignettes/` cause that's what we did for the workshop.

> 
> ## data/
> * It would be good if the "peaks" data had a slightly more descriptive name
> 

I think in the context of the vignette this makes sense. 

> ## docs/
> * Please remove built documentation from the source package (`docs` folder).
>   This is generated when the package is built.
> 
> ## Other
> * 'pkgdown' files (e.g., `_render.R`, and `_pkgdown.yml`) should go in another
>   branch as they are related to the website build and not the Bioconductor
>   software.
> * `WORDLIST` file should also be in that branch.
> * Consolidate `LICENSE` files, if possible.

Done I've moved everything into a separate branch. 

Please let me know if there's anything else.

**Comment by sa-lee** [comment]
hi @LiNk-NY Marcel, 
I think I've made all the changes you suggested. Please let me know if there's anything else. 

Thanks,
Stuart

**Comment by LiNk-NY** [comment]
Hi Stuart, @sa-lee 
I'll have another look at it today. 
Thanks.

**Comment by LiNk-NY** [comment]
Hi Stuart, @sa-lee 
Thanks for making those changes.
You probably don't need the `Makefile` in there either. 
I will accept your package.
Best,
Marcel

**Comment by mikelove** [comment]
Woohoo 🎉

**Comment by sa-lee** [comment]
Thanks @LiNk-NY!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sa-lee.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("fluentGenomics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/fluentGenomics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mikelove** [comment]
Woohoo 🎉
