### ISSUE TITLE
GeneTonic

### ISSUE THREAD

**Issue by federicomarini** [Bioconductor/Contributions#1357]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/federicomarini/GeneTonic

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by federicomarini** [comment]
Hi @mtmorgan, thank you for taking over the reviewing process.

I am noticing that (apart the RStudio project file) all other main errors and warnings are due to the package size. 
Only way to address that would be to chop off from the vignette some of the content - or is some trick there that I am not aware of to shrink down its final size?
Thanks!

**Comment by mtmorgan** [comment]
The size of the package is from the vignette, and vignettes are good, so I'd suggest that we ignore the size error for the review. Can you let me know via a comment with @mtmorgan when your package is ready for review, other than the vignette size issue?

Your package has a huge number (>125) of dependencies and this will make it very fragile and difficult to maintain (for both you and your users!). I suggest that you reduce these dependencies by identifying the functionality each provides and assessing whether that functionality is 'essential', 'necessary', 'useful', or 'lux', and then keep only those packages providing 'essential' functionality. After all, Gin & Tonic is a simple drink...

**Comment by federicomarini** [comment]
I did already address a couple of NOTEs from BiocCheck - see latest commits.
There's one warning in the help indices I can not reproduce (probably because I am using markdown+roxygen?).

Feature-wise: I'd say it is indeed complete and ready for review @mtmorgan 

Regarding the dependencies: I do know there are some of them on my back as a responsability in terms of maintenance. Explicitly I do not have so many, but of course each dependency might have some internal burden that I end up carrying along.
I can investigate in parallel whether I can drop some - in favor probably of unoptimized versions? Or as you say, dropping some luxury-like features. Point taken for the drink, the quality of the ingredients is paramount 😉

**Comment by federicomarini** [comment]
As a note to self - maybe useful for others: I recall Jim Hester gave recently a presentation on the pros and cons of dependencies. Happy to follow up on the tool he assembled, once I'll run it on my package.

**Comment by federicomarini** [comment]
Following up on my thought:

Ingredients: `itdepends`  (remotes::install_github("jimhester/itdepends")) + base R commands

```
library("magrittr") 
mydeps <- itdepends::dep_usage_pkg("GeneTonic") %>% dplyr::count(pkg,sort=TRUE) 
db <- available.packages(repos=BiocManager::repositories())
depsnr <- tools::package_dependencies(mydeps$pkg, db,recursive = TRUE )
depsnr
# total of dependencies
length(unique(unlist(depsnr)))
# which ones contribute with most dependencies
sort(sapply(depsnr, length))
```

In my case, `union(depsnr$plotly, depsnr$DESeq2)` gives me 108 (of the 128). 
I wish I could say I could cut down more, but it was an informative exercise!

**Comment by mtmorgan** [comment]
DESCRIPTION

- OK

vignette

- please minimize the number and amount of code in `eval = FALSE` code chunks, e.g., consider arranging for only `DEseq()` at line 140 to be not evaluated. This minimizes opportunity for bit rot.

R -- comments on specific lines of code may be more generally relevant

- GeneTonic-extras.R: without looking to carefully, I wonder if a more templated approach (e.g., via the whiskers package) would provide a cleanser separation between 'code' (things you have to compute) and 'data' (the html in which you insert the result of the code)?

- GeneTonic.R:81 best practice is to reset options to original values, e.g.,
  ```
  oopt <- options(spinner.type = 6, spinner.color = .biocgreen)
  on.exit(options(oopt))
  ```

- ggs_graph.R:112 `seq_len(length(...))` is often just `seq_along(...)`.

- happy_hour.R:160 a better choice for `output_dir` default is usually `tempdir()` or `tempfile()`, to avoid accidental over-write of user files.

- happy_hour.R:189 `stop(paste0(...))` is often just `stop(...)`.

man

- Generally good.

other

- nice to see the unit tests!

- is `www/genetonic_hex_concept.png` still relevant?

**Comment by federicomarini** [comment]
Hi Martin, thanks for the timely and detailed review!

I'll be working on these aspects and get back soon by tagging you once I addressed them.

Quick question, just so that I know we are on the same page. Is this - https://github.com/edwindj/whisker - the package you were referring to regard the templating? I was considering also to give a try to Jim's `glue`. 
Either way: I'll make sure to explore these possibilities!

**Comment by mtmorgan** [comment]
yes I was thinking of the whisker package you mention.

**Comment by federicomarini** [comment]
Ok, good. As I said, I'll give them all a run to see if conceptually the code and assembled output become somewhat clearer (and thus somewhat easier to expand/edit/maintain).

**Comment by federicomarini** [comment]
Hi @mtmorgan , I am now done in addressing all the points above.
Please see below the reply to each.

> Please review the comments below, update your package, and provide a short comment outlining your changes.
> 
> DESCRIPTION
> 
> * OK

No change needed

> 
> vignette
> 
> * please minimize the number and amount of code in `eval = FALSE` code chunks, e.g., consider arranging for only `DEseq()` at line 140 to be not evaluated. This minimizes opportunity for bit rot.

Addressed in commit 69680971

> 
> R -- comments on specific lines of code may be more generally relevant
> 
> * GeneTonic-extras.R: without looking to carefully, I wonder if a more templated approach (e.g., via the whiskers package) would provide a cleanser separation between 'code' (things you have to compute) and 'data' (the html in which you insert the result of the code)?

I did rewrite both functions in a clearer way, following your advice - computing first, assembling later.
See 750c764b and e07ec047 for the related commits.

What I did was also to switch to constructing the content via `shiny::tags` - that also helped a lot IMHO. Plus, I caught an unused `</b>` tag.

This allowed me to have a clearer compartimentalization, which hopefully will help out once I update/fix the function.

Arguments against `whisker` or `glue`: after restructuring, I had the impression clarity was "improved enough". In the end, I am saving an extra dependency :)
If the package had a massive component of such HTML generating functions, then one of these approaches would probably not be so overkill. `glue` did seem at times clearer, other not (because I am not generating "just" pure text).

> * GeneTonic.R:81 best practice is to reset options to original values, e.g.,
>   ```
>   oopt <- options(spinner.type = 6, spinner.color = .biocgreen)
>   on.exit(options(oopt))
>   ```

Nice catch, thanks. Addressed in 5147996

> * ggs_graph.R:112 `seq_len(length(...))` is often just `seq_along(...)`.

Indeed :) I replaced the call in that, as well as in two other similar spots - see eade582

> * happy_hour.R:160 a better choice for `output_dir` default is usually `tempdir()` or `tempfile()`, to avoid accidental over-write of user files.

Changed in a8fc878

> * happy_hour.R:189 `stop(paste0(...))` is often just `stop(...)`.

Done, replaced call in f7c1ecc

> 
> man
> 
> * Generally good.

No change needed. 
I fixed the manual for `get_aggr_scores` where one argument was defined, documented, yet unused - commit e3c27ffa69da723cc27f8a65958d7caff5e7cf34

> 
> other
> 
> * nice to see the unit tests!

Thanks!
I also edited slightly the tests for respecting the returned warning

> * is `www/genetonic_hex_concept.png` still relevant?

Nope, it was still there for historical (and affective) reasons, but can be effectively archived. 
Addressed in dc8f75f

<hr>

The size of the tarball seems also to have been reduced, although I am not sure it will pass the BiocCheck in this go. 

Happy to hear back from you in the next round if further changes are required!

**Comment by mtmorgan** [comment]
Thanks, these look great. Can you fix
```
Found the following significant warnings:
  Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/Rtmp6jlZSH/R.INSTALL1a1c53be681c/GeneTonic/man/enrichment_map.Rd:55: file link 'visIgraph' in package 'visNetwork' does not exist and so has been treated as a topic
  Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/Rtmp6jlZSH/R.INSTALL1a1c53be681c/GeneTonic/man/ggs_graph.Rd:47: file link 'visIgraph' in package 'visNetwork' does not exist and so has been treated as a topic
  Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/Rtmp6jlZSH/R.INSTALL1a1c53be681c/GeneTonic/man/map2color.Rd:14: file link 'brewer.pal' in package 'RColorBrewer' does not exist and so has been treated as a topic
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1357/54f7edc/GeneTonic.Rcheck/00install.out' for details.
```
which generally arise when trying too hard to resolve symbols -- I think 
```
GeneTonic-extras.R:#' palette, e.g. obtained via [RColorBrewer::brewer.pal()]
```
gets translated as 'look for a help page with name brewer.pal in package RColorBrewer', but actually the help page name is actually (from the top-left corner of the man page)
```
RColorBrewer           package:RColorBrewer            R Documentation
```
So you either need to figure out the roxygen syntax to link to that help page _name_, or simply let R find all man pages with alias `brewer.pal` and, if there are conflicts (seems unlikely!) let the user resolve them.

**Comment by mtmorgan** [comment]
Also, FWIW, `grDevices::palette.pals()` provides similar pallets from a base package, reducing an external dependency.

**Comment by federicomarini** [comment]
On it!

**Comment by federicomarini** [comment]
re: palettes, I was even tempted to use the newly developed `colorspace`. 
But probably I am using RColorBrewer since too long to depart from it 😬

**Comment by federicomarini** [comment]
I gave a shot with the link to the topics.
This seems to be supported in the roxygen+md combo.

Might have to bump this a couple of times more if this does not work - somehow, on none of my dev machines the warning does not show up when checking. Apologies for the potential inconveniences.

**Comment by mtmorgan** [comment]
yeah it's triggered on Windows only...

**Comment by federicomarini** [comment]
Oh I see, this explains it partially 😁 

Let's see if I get lucky with the first round.

**Comment by federicomarini** [comment]
Ok, I did force now the usage of classical documentation tags (link + code combination), and see what happens.

**Comment by federicomarini** [comment]
Warning is gone - sometimes a touch of vintage is indeed the solution 🎉 
I think btw the good old `\code{\link{...}}` should also be quite robust to the cases you mentioned!

**Comment by federicomarini** [comment]
Ok, I restored back the full coverage 
@mtmorgan ready for the next round

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/federicomarini.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GeneTonic")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeneTonic

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
I'm just re-opening this to re-process it for addition to the Bioconductor build system. Sorry for the inconvenience.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/federicomarini.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GeneTonic")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeneTonic

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
