### ISSUE TITLE
scTHI.data

### ISSUE THREAD

**Issue by miccec** [Bioconductor/Contributions#1362]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/miccec/scTHI.data

Confirm the following by editing each check box to '[x]'

- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I think this is a companion to your other package. Please review the instructions for [submitting related packages][1] -- which package can be built without depending on the other package (no circular dependencies allowed)? This should be the primary issue, and once the package without other dependencies builds successfully, add a comment with the 'AdditionalPackage: ' syntax. Close the issue that is associated with the package that depends on the primary package.

[1]: https://github.com/Bioconductor/Contributions#submitting-related-packages

**Comment by miccec** [comment]
Thanks @mtmorgan ,
yes, this is a companion submission. I have closed the issue related to the submission of the software package. I will submit it as  AdditionalPackage here.

**Comment by miccec** [comment]
AdditionalPackage: https://github.com/miccec/scTHI

**Comment by miccec** [comment]
Issue  #1361 was closed due to a companion submission.  The correct post is in this issue.

**Comment by miccec** [comment]
AdditionalPackage: https://github.com/miccec/scTHI

**Comment by miccec** [comment]
Dear @Kayla-Morrell thanks for serving on the team of  Bioconductor Core Members. I want to add the package https://github.com/miccec/scTHI as companion submission. The system gives the above reply referring to the closed issue  #1361.

**Comment by Kayla-Morrell** [comment]
@miccec - We have updated the database on our end and kicked off a manual build, so there should be a build report shortly for scTHI. Be sure that the web hook is set up for this additional package and when you bump the version a build report should be triggered. If there are any additional issues feel free to tag me.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@miccec - Looking at the build report from scTHI, dependency packages can only be from Bioconductor or CRAN. Since we don't allow for GitHub packages yaGST needs to be added to CRAN or Bioconductor OR you need to utilize a different package. Also the doMC package is not available on Windows. If you want to use this package Window users will not be allowed to use your package, we suggest looking into BiocParallel which is available for all platforms. Please make these changes for the package to build properly.

**Comment by miccec** [comment]
Dear @Kayla-Morrell it looks like that both packages compile with no issues. Let me know if there are additional enhances you can suggest.
Thanks!
Michele

**Comment by Kayla-Morrell** [comment]
@miccec - I am currently working on the review for both packages and should have comments posted here within a couple days. 

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
Hello @miccec - Thank you for submitting to _Bioconductor_. Please see the initial review of both packages below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

# scTHI.data
## DESCRIPTION

- [ ] REQUIRED: The 'Title:' field needs to be filled in with something that is 
brief but descriptive.

- [ ] REQUIRED: The 'LazyData:' field should be set to 'false'. We find that 
when this field is set to true it can slow down the loading of the package, 
especially if it includes data.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
      RNASeqData, miRNAData, ExpressionData, NCI

- [ ] SUGGESTION: We suggest including the 'BugReports:' field with a relevant 
link to the GitHub for reporting Issues.

## NEWS

- [ ] REQUIRED: Correct format for the news file, just change the date to be the 
actual date it was submitted.

## README.md

- [ ] SUGGESTION: Unless you plan on adding information to the README file I 
would delete it for now.

## Man pages

- [ ] SUGGESTION: We highly suggest including a man page for the package. This 
should be an overview of the package.

# scTHI
## DESCRIPTION

- [ ] REQUIRED: In the 'Description:' field you mention using functions from the 
'yaGST' package. We do not allow our packages to use/depend on packages that are 
not CRAN or Bioconductor packages. Please remove this and any functions used from 
that package. 

- [ ] REQUIRED: 'LazyData:' should be set to 'false'.

- [ ] REQUIRED: The additional package, 'scTHI.data' should be listed under 
'Depends:'.

- [ ] SUGGESTION: We highly suggest using the 'BugReports:' tag that includes 
a relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: The exported functions should use camel case or underscoring, 
and should not include '.' as this indicates S3 dispatch.

- [ ] REQUIRED: There shouldn't be two instances of `importFrom()` for the 
'BiocParallel' package. This should be declared in one line like the others. 
But I can't seem to find where you actually declare the `importFrom` in your 
code. Are you editing this file by hand? Because, like it says in the comment, 
this file should be created through the roxygen2 tags and shouldn't be editted 
by hand.

## Data

- [ ] REQUIRED: Why do you still have data in this package if you have the 
accompanying data package? The data that is in an experiment data package can 
be used in examples and vignettes.

## Vignettes

- [ ] REQUIRED: Line 18, it is not necessary to include this. This function is 
used when including an additional .css file.

- [ ] REQUIRED: Line 21, there should be a space between '#' and 'Introduction' 
so it will render as a proper header.

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how to 
download and load the package from Bioconductor. The code should look something 
like this:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("scTHI")
```

- [ ] REQUIRED: Line 38, it is not necessary to call `library(scTHI)` here since 
you do it later in line 63 (and that one is actually evaluated).

- [ ] REQUIRED: Line 42, there should be a space between '##' and 'Analysis' so 
it will render as a proper header.

- [ ] REQUIRED: Line 48-50, the link does not render properly when it is split 
up on multiple lines. Please change this. My suggestion would be to use markdown 
links with the link name in square brackets '[ ]' and the url in parantheses '()'. 
It would look something like \[Broad Institute Single-Cell Portal\](https://portals.broadinstitute.org/single_cell/study/single-cell-analysis-in-pediatric-midline-gliomas-withhistone-h3k27m-mutation).

- [ ] SUGGESTION: Line 103-117, I would suggest removing 'message=FALSE'. If a 
user is reading through the vignette without evaluating the code on their own, 
its not clear what the output from this function is. It wasn't until I evaluated 
the code on my own and saw the final message 'Interaction pairs detected:' did 
I understand what the output was.

- [ ] REQUIRED: The source [2] isn't cited anywhere in the vignette. I see [1] 
in line 50 and [3] in line 152, but no [2]. Either add in the citation or remove 
the reference.

- [ ] REQUIRED: Line 163-167, when I run this code locally on my own machine, 
the plot that is produced is almost a mirror image of what your plot looks like.
(I've attached my plot for refrence).

<img width="1072" alt="scTHI plotCluster" src="https://user-images.githubusercontent.com/32339524/74849449-b46a5c80-5306-11ea-9334-caf642048f87.png">

- [ ] REQUIRED: Line 177-183, these plots look different for me as well.
(Attached is my plot).

<img width="1174" alt="scTHI plotPairs" src="https://user-images.githubusercontent.com/32339524/74849472-bc2a0100-5306-11ea-820d-d6effe2377aa.png">

- [ ] REQUIRED: Line 237, the plot I produce looks different from what is shown 
in the vignette.
(Attached is my plot).

<img width="1069" alt="TME plot" src="https://user-images.githubusercontent.com/32339524/74849486-c21fe200-5306-11ea-8312-ad4372da0ac8.png">

- [ ] REQUIRED: There should be a final section (probably before the references) 
titled 'Session Info' and should include `sessionInfo()`. 

## Man pages

- [ ] SUGGESTION: We strongly encourage having a package man page with an 
overview of the package and links to the main functions.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See 
the following for help,
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: We do allow for internal data, which you utilize in your package. 
However, it would be helpful to have some documentation and/or source 
information about this data to be sure it is correct. Please create an 
`inst/script/` directory that would contain documentation about this data. It 
can be executible code, sudo code, or a text file, but it should include source 
urls and any important information regarding filtering or processing.

- [ ] REQUIRED: Overall the code is very difficult to read/follow. You should 
avoid excessively long functions. Functions should be small and have only one 
job to do. It's best if this job is done in as few lines of code as possible.
If the functions wrap one for more than a screen then you should probably take 
a moment to split it up into smaller helper functions. Smaller functions are 
easier to read, debug, and reuse. For example, lines 64-89 are to check all 
interaction genes in expMat. This could be it's own function outside of the 
scTHI.score function, then all you would have to do is call that function to 
check the interaction.

- [ ] REQUIRED: Even if the code isn't split up I think there is room for some 
helper functions (like my example above). There seems to be large chunks of 
repeated code that could be good candidates for helper functions as well.

- [ ] SUGGESTION: Another tip for readability of the code would to split the 
code into other R files. There could be one file for each of the main functions. 
This will simplify the scTHI.R file. 

- [ ] REQUIRED: The roxygen documentation should go before the function, not 
in it. For example, line 16-62 should go before line 1.

- [ ] REQUIRED: Function names should be camel case or utilize the underscore 
'_' and not have a dot '.' with indicates S3 dispatch.

- [ ] REQUIRED: Use various apply functions instead of for loops, unless 
absolutely necessary.

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` instead. Found in files:
        - scTHI.R (lines 1190, 1200, 1227, 1232)

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead. Found 
in files:
        - scTHI.R (lines 112, 137, 181, 206, 370, 440, 539, 609, 619, 700, 707,
        866, 872, 994, 1023, 1062, 1086, and 1177)

- [ ] SUGGESTION: For formatting reasons consider shorter lines. There are 6 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 88 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@miccec - Are the packages ready for re-review?

**Comment by miccec** [comment]
Hi @Kayla-Morrell  yes, please. Many thanks for your help. We submitted the new version last week addressing all your suggestions.

**Comment by Kayla-Morrell** [comment]
@miccec - Thank you for making the required changes. There are a few more requirements before I can accept the package. Please see the notes below and comment here when you are ready for me to review the changes.

# scTHI.data

- [ ] REQUIRED: The two requirements for the DESCRIPTION file were not made. The
'Title:' field needs to be edited and 'LazyData:' needs to be set to 'false'.

# scTHI

- [ ] REQUIRED: In the DESCRIPTION file, the title is malformed. It should not
end in a period.

- [ ] REQUIRED: In the DESCRIPTION file, scTHI.data can be moved from Depends to
Suggests. Since the data package is only used in the vignettes, it should be
listed as a suggests, that was my mistake.

- [ ] REQUIRED: For the examples, the `data(scExample)` isn't found.

Best,
Kayla

**Comment by miccec** [comment]
Dear @Kayla-Morrell ,
many thanks for your help and for looking at our package so carefully!

Before moving forward with the revision, I have some questions. Are you sure that you checked version 0.99.6? Il looks like that some of the required changes have been already made.
For example:
- REQUIRED: The two requirements for the DESCRIPTION file were not made. The
'Title:' field needs to be edited and 'LazyData:' needs to be set to 'false'.

we edited the DESCRIPTION file and the  'LazyData:' is already set to false
https://github.com/miccec/scTHI/blob/master/DESCRIPTION

-  REQUIRED: In the DESCRIPTION file, scTHI.data can be moved from Depends to
Suggests. Since the data package is only used in the vignettes, it should be
listed as a suggests, that was my mistake.

scTHI.data is needed for the examples in the documentation, do we need to put suggested also in this case?

-- REQUIRED: For the examples, the data(scExample) isn't found

according to your previous suggestion to move all the data in scTHI.data we moved the scExample object in the scTHI.data package. I suspect that you did not use the latest version of scTHI (0.99.8 )
could you please check.

I really appreciate your help and your time. I would be grateful if you can check the above question so we can quickly move forward.
Regards
Michele

**Comment by Kayla-Morrell** [comment]
@miccec - Please see my responses to your questions below.

> Before moving forward with the revision, I have some questions. Are you sure that you checked version 0.99.6? Il looks like that some of the required changes have been already made.

I checked `scTHI` version 0.99.6 and `scTHI.data` version 0.99.8.

> * REQUIRED: The two requirements for the DESCRIPTION file were not made. The
>   'Title:' field needs to be edited and 'LazyData:' needs to be set to 'false'.
> 
> we edited the DESCRIPTION file and the 'LazyData:' is already set to false
> https://github.com/miccec/scTHI/blob/master/DESCRIPTION

Yes but this requirement was for `scTHI.data`, the title remains unchanged and 'LazyData:' is still false.

> * REQUIRED: In the DESCRIPTION file, scTHI.data can be moved from Depends to
>   Suggests. Since the data package is only used in the vignettes, it should be
>   listed as a suggests, that was my mistake.
> 
> scTHI.data is needed for the examples in the documentation, do we need to put suggested also in this case?

Yes, packages used in vignettes, examples, and in conditional code should be listed in 'Suggests:'.

> -- REQUIRED: For the examples, the data(scExample) isn't found
> 
> according to your previous suggestion to move all the data in scTHI.data we moved the scExample object in the scTHI.data package. I suspect that you did not use the latest version of scTHI (0.99.8 )
> could you please check.

I as stated above, I am using `scTHI.data` version 0.99.8. If the data is in the data package then you need to load the package before using the data. So the example code should look something like:

```
library(scTHI.data)
data(scExample)
```

I hope this answers your questions.

Best,
Kayla

**Comment by miccec** [comment]
Thanks @Kayla-Morrell 
now I see. I will update the package according to your suggestion.
All the best and stay safe!

**Comment by miccec** [comment]
Dear @Kayla-Morrell 
just submitted the new version according to your suggestion. Looking forward to receiving your feedback.
Many thanks
All the best
Michele

**Comment by Kayla-Morrell** [comment]
@miccec - Thank you for make the changes. Everything looks good now and I'm more than happy to accept the packages.
Best,
Kayla

**Comment by miccec** [comment]
@Kayla-Morrell 
thanks a lot, Kayla! You did a great job. Very helpful.
Best,
Michele

**Comment by miccec** [comment]
@Kayla-Morrell ,
sorry to disturb you again. What's the follow-up for the release of the package? I have not received any notification.
Best regards
Michele

**Comment by Kayla-Morrell** [comment]
@miccec - There will be some additional instructions to follow once your package gets added to our Bioconductor git repository. But for the time being there is some information [here](https://bioconductor.org/developers/package-submission/#afteraccept) that will broadly explain what to expect next.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/miccec.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scTHI.data")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scTHI.data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/miccec.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scTHI")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scTHI

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
