### ISSUE TITLE
HIPPO

### ISSUE THREAD

**Issue by tk382** [Bioconductor/Contributions#1364]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tk382/HIPPO

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@LiNk-NY will review your package, but please update the Description: field to more clearly identify the unique contributions you are making. Please also consider using an existing [ExperimentData](http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData) resource for your vignette, e.g., http://bioconductor.org/packages/release/data/experiment/html/TENxPBMCData.html

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Thank you for your submission to Bioconductor. 
Please see the package's review below. 
If you have any questions, post them on this thread. 
Best regards,
Marcel

---

# HIPPO #1364

## DESCRIPTION

* It looks good. Please add a `BugReports` link that refers to the GitHub
issues page.
* Minor: Use fully qualified version numbers `R (>= 4.0.0)`.
* Consider using `Authors@R` field instead of `Author` and `Maintainer`

## NAMESPACE

* Avoid using general names such as `dimension_reduction`,
`compute_test_statistic`, etc.
* Consider re-exporting the pipe operator if you want to provide that
functionality for your users

## vignettes/

* Use a more descriptive title for the vignette
* Include an 'Installation' section in the vignette
* Avoid downloading data from the web (line #25). If the data is needed for an
example, your first option should be to generate an example /mock dataset from
code and the second would be to add a _small and condensed_ dataset to the
`data/` folder to show usage
* Please format the vignette code so that it doesn't go over the 80 column
width limits
* Consider providing a helper function / functionality to be able to read data
from `sce@assays\$data\counts`
* Include a `sessionInfo` section
* Provide an extractor function for hippo results instead of having the user
enter `sce@int_metadata$hippo$diffexp$result_table`

## R/

* Re-use functions where possible. For example, use `nb_prob_zero` inside
`zinb_prob_zeo`.
* Allow the use of a `SingleCellExperiment` where a matrix object of count
data is the main input (e.g., `preprocess_heterogeneous`)
* Use `assay` instead of `assays@data$counts`
* Condense conditionals to just use "`setdiff`" of the code. For example,
when `show_outliers` is `TRUE`, it should only add
`ggplot2::geom_point(data = subset, ...)` to `g`.
* Avoid using semicolons in the code (`;`)
* Avoid using `print` and use `message` instead, provide a `verbose` option for
users to opt-out of the messages
* Consider extending `SingleCellExperiment` or providing a method to access
`int_metadata` in an organized way.
* Condense code by reducing repeated code in `dimension_reduction`. Use a
`switch` to assign the appropriate function either (`umap` and `Rtsne`).
* Rename functions that have 'generic' names such as `diffexp`,
`compute_test_statistic`, etc.

Minor:
* Use `<-` for assignment instead of `=`
* Avoid using `1:n` sequence generation and use the more robust
`seq_len(n)` or `seq_along(x)`
* Use  `rownames(df) <- NULL` to remove row names
* `if (length(x) > 0)` is equivalent to `if (length(x))`

## /

* Remove non-package related folder such as `analysis`, `readme`, `docs`,
`README_file`, `ensg_hgnc*.txt`, etc.
* Move any datasets that you _absolutely_ need into a `data` directory,
refer to data comments above

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Any updates on the status of the review? 
Otherwise, I'd be forced to close the issue. Thank you. 
Marcel

**Comment by tk382** [comment]
Hi Marcel,

The package development has been going through a bit of delay. I just accidentally pushed it with a new version, but it is not ready for a submission yet. Please ignore. I will push again once it reflects all your comments. Thank you!

Best,
Tae


On Feb 28, 2020, at 12:33 PM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Tae, @tk382<https://github.com/tk382>
Any updates on the status of the review?
Otherwise, I'd be forced to close the issue. Thank you.
Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
It's been more than a month since the review. 
If there is no follow-up, I'd be forced to close the issue. 
Thank you. 
-Marcel

**Comment by tk382** [comment]
Hi Marcel,

There has been a delay in the development of package, so it will take a while. You can close the issue, and I’ll work on the comments on my own, and resubmit. Thank you.

Best,
Tae


On Mar 20, 2020, at 1:41 PM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>
It's been more than a month since the review.
If there is no follow-up, I'd be forced to close the issue.
Thank you.
-Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
I will close the issue and the package submission will be marked as inactive. 
Feel free to re-open it when the team is ready. Thank you!
Best,
Marcel

**Comment by tk382** [comment]
Hi Marcel,

I made a valid push, and I would like to re-open the issue for another round of evaluation. I couldn’t find a way to do that in the issue. I now have two issues #1364 and #1437, and I’m confused now where to go! Could you help please?

Tae


On Mar 26, 2020, at 1:19 PM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>
I will close the issue and the package submission will be marked as inactive.
Feel free to re-open it when the team is ready. Thank you!
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 

You have to address the points made in the review. 

I am contacting Lori and Kayla here to see what can be
done about the new issue that you opened. 
@lshep cc @Kayla-Morrell 

Best,
Marcel

**Comment by tk382** [comment]
Hi Marcel,

I see. I addressed most issues mentioned in the last review in the last push.

There are some parts that I wanted to discuss further. For example, I’d like to keep docs folder so that I can keep my workflowr page. (https://tk382.github.io/HIPPO/example.html). And I was wondering if changing “=“ to “<-“ is absolutely required.

Thank you for your help, and please let me know what I can do next.

Best,
Tae

On Mar 26, 2020, at 6:37 PM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>

You have to address the points made in the review.

I am contacting Lori and Kayla here to see what can be
done about the new issue that you opened.
@lshep<https://github.com/lshep> cc @Kayla-Morrell<https://github.com/Kayla-Morrell>

Best,
Marcel

**Comment by lshep** [comment]
With the issue reopened and the tag "review in progress"  you should be able to proceed as normal using This issue #1364.   Please do version bumps and check this issue for the regenerated build report. I don't think the other issue that was opened/closed should have any affect.  Cheers

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
You can create the website locally and deploy it on another branch. 
The `docs` folder should not be part of the package. 
You should also clean up other files from the repository including:
* analysis
* README_files
* readme
* ./*.txt
* ./*.rds
These are all artifacts that are not part of the essential package you are submitting. 

Best,
Marcel

**Comment by tk382** [comment]
Got it! Those files are all now removed from the package. Thank you.

Best,
Tae


On Mar 27, 2020, at 8:03 AM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>
You can create the website locally and deploy it on another branch.
The docs folder should not be part of the package.
You should also clean up other files from the repository including:

  *   analysis
  *   README_files
  *   readme
  *   ./*.txt
  *   ./*.rds
These are all artifacts that are not part of the essential package you are submitting.

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Please bump the package version for another build. 
-Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Please address the issues in the build report and sign up for the mailing list. Thank you.

**Comment by tk382** [comment]
I did sign up for the mailing list multiple times, as a response to the build error, but the build report keeps repeating the same error. But I sent another request to be subscribed anyway. Thank you.

Best,
Tae




On Mar 30, 2020, at 3:28 PM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>
Please address the issues in the build report and sign up for the mailing list. Thank you.

**Comment by lshep** [comment]
Have you been able to confirm the mailing list?  Have you checked your spam folder; many confirmations get accidently sent to spam?

**Comment by tk382** [comment]
Hello,

I confirmed the mailing list subscription. Should I push again using a version bump?

Tae


On Mar 31, 2020, at 7:55 AM, lshep <notifications@github.com<mailto:notifications@github.com>> wrote:



Have you been able to confirm the mailing list? Have you checked your spam folder; many confirmations get accidently sent to spam?

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Yes, please push a version bump. Thanks.

**Comment by tk382** [comment]
Hello,

I addressed all the warnings and errors, but I don’t know how to resolve the following. I can build the package using that command, but given that the package is checked as the entire github repository, I’m not sure how to reflect the change.


Thanks,

Tae

————————————

* checking data for ASCII and uncompressed saves ... WARNING

  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                  old_size new_size compress
  ensg_hgnc.RData    445Kb    201Kb       xz
  toydata.RData      415Kb    249Kb       xz



On Mar 31, 2020, at 12:34 PM, bioc-issue-bot <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Package contributor,

This is the automated single package builder at bioconductor.org<http://bioconductor.org>.

Your package has been built on Linux, Mac, and Windows.

On one or more platforms, the build results were: "WARNINGS".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.

Please see the build report<http://bioconductor.org/spb_reports/HIPPO_buildreport_20200331133345.html> for more details.

**Comment by lshep** [comment]
Running that command will  create a tarball that has the data files compressed as small as possible. Untar this file and copy the data files in it over the ones in your git working copy, then recommit those, with a version bump.

**Comment by tk382** [comment]
Thank you. I’m struggling with another warning:

directory HIPPO/build is empty

When I build a package, there is no such folder. How can I address this?

Best,
Tae


On Mar 31, 2020, at 3:00 PM, bioc-issue-bot <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Package contributor,

This is the automated single package builder at bioconductor.org<http://bioconductor.org>.

Your package has been built on Linux, Mac, and Windows.

On one or more platforms, the build results were: "WARNINGS".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.

Please see the build report<http://bioconductor.org/spb_reports/HIPPO_buildreport_20200331155945.html> for more details.

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
I would first start with removing all the files and folders that are not pertinent to the package. This includes cache folders like `README_files`, `*.rds`, and `*.pdf`.
Please also rename `R/__imports.R` as this is not a valid name. 
After this, we can isolate the `build` folder issue. Thanks.
-Marcel

**Comment by tk382** [comment]
Hi Marcel,

I am still getting the errors


WARNING: directory 'HIPPO/build' is empty

WARNING: Unless package includes compressed data, remove R
      version dependency.

and I’m not sure how to address either. Could you please help? Thank you.

Best,
Tae



On Apr 1, 2020, at 3:20 PM, bioc-issue-bot <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Package contributor,

This is the automated single package builder at bioconductor.org<http://bioconductor.org>.

Your package has been built on Linux, Mac, and Windows.

On one or more platforms, the build results were: "WARNINGS".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.

Please see the build report<http://bioconductor.org/spb_reports/HIPPO_buildreport_20200401161955.html> for more details.

**Comment by tk382** [comment]
Hi Marcel,

I also have a question about why biocCheck recommends R version dependency of (>=4.0.0). Is this correct? It’s preventing people from trying the software, and I was wondering if there’s a way to get around it. Thank you.

Tae

On Apr 1, 2020, at 3:33 PM, Tae Kim <tk382@uchicago.edu<mailto:tk382@uchicago.edu>> wrote:

Hi Marcel,

I am still getting the errors


WARNING: directory 'HIPPO/build' is empty

WARNING: Unless package includes compressed data, remove R
      version dependency.

and I’m not sure how to address either. Could you please help? Thank you.

Best,
Tae



On Apr 1, 2020, at 3:20 PM, bioc-issue-bot <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Package contributor,

This is the automated single package builder at bioconductor.org<http://bioconductor.org/>.

Your package has been built on Linux, Mac, and Windows.

On one or more platforms, the build results were: "WARNINGS".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.

Please see the build report<http://bioconductor.org/spb_reports/HIPPO_buildreport_20200401161955.html> for more details.

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 

Apologies for the late response. 

There seems to be some confusion concerning the decision to include an R version or not. 
I think it is best to leave the R version restriction out of the DESCRIPTION file since Bioconductor has checks for ensuring the proper R version (via `BiocManager` and `BiocVersion`). 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Thanks for making changes. 

* Please fix the warnings:
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'zero_proportion_plot'
  'pointsize' 'pointalpha' 'textsize'
```
* **Remove** `README_files` folder. You can have a `README.Rmd` file and a `README.md` but _no_ intermediate files. 

* Because you have `RData` files in the data folder, I would recommend that you use an `R (>= 4.0.0)` in the `Depends: ` field of the `DESCRIPTION` file. 

Best,
Marcel

**Comment by tk382** [comment]
Hi Marcel,


  *   Please fix the warnings:

* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'zero_proportion_plot'
  'pointsize' 'pointalpha' ‘textsize'


I will fix this.


  *   Remove README_files folder. You can have a README.Rmd file and a README.md but no intermediate files.

  *

I have tried this, but that will prevent figures from showing in the github readme file in the repository page. How do I go around this issue?


  *   Because you have RData files in the data folder, I would recommend that you use an R (>= 4.0.0) in the Depends: field of the DESCRIPTION file.

This prevents me from allowing users to try the software now. Is this absolutely necessary? Can I change the R version dependency after R 4.0.0 is formally released?

Thank you.

Tae





On Apr 10, 2020, at 9:33 AM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>
Thanks for making changes.

  *

  *

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 
Thanks for getting back to me. 

1) 
If you'd like to load images in the `README.md` file, you can load them from an external repository such as `https://github.com/tk382/figures` and then you can link to them using HTML like this:

```html
<a href="https://github.com/tk382/HIPPO"><img src="https://raw.githubusercontent.com/tk382/figures/master/pngs/diagnostic-1.png"/></a>
```

2)
Ideally, your early users should have `R 4.0.0` as the Bioconductor release will soon require it. 
In the meantime, you can leave it as is.

**Comment by tk382** [comment]
Thank you for your help! I reflected all the comments and made another version bump.

Tae



On Apr 10, 2020, at 9:56 AM, Marcel Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Tae, @tk382<https://github.com/tk382>
Thanks for getting back to me.

  1.

If you'd like to load images in the README.md file, you can load them from an external repository such as https://github.com/tk382/figures and then you can link to them using HTML like this:

<a href="https://github.com/tk382/HIPPO"><img src="https://raw.githubusercontent.com/tk382/figures/master/pngs/diagnostic-1.png"/></a>

  1.

Ideally, your early users should have R 4.0.0 as the Bioconductor release will soon require it.
In the meantime, you can leave it as is.

**Comment by LiNk-NY** [comment]
Hi Tae, @tk382 

Please read the instructions carefully. 
Create a **separate** repository for figures and link to them in the `README.md` file as above.
Another possibility is to create a separate branch in the original repository and keep the images
on that branch. You can then use a permanent link to those images in the `README.md`. 
We want the master branch to contain just the source package and not any build products / artifacts. 
Thank you. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Thank you for making those changes Tae @tk382 
You can follow up on the `NOTES: ` in the build report as you continue to improve your package. 
Thank you for your contribution. 
Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tk382.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HIPPO")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HIPPO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
