### ISSUE TITLE
SynExtend

### ISSUE THREAD

**Issue by npcooley** [Bioconductor/Contributions#1369]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/npcooley/SynExtend

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
please provide a more extensive Description:, like a paper abstract describing the unique contributions your package is making.

Please mark the first code chunk of your vignette with `{r, eval = FALSE}` so that building the vignette does not trigger installing the package.

In the vignette, please use `rtracklayer::import()` to import the gff file into a standard R data representation; make sure that this representation can be used as inputs to your functions.

The assigned reviewer will provide additional comments after you have made these (and any other issues identified by the automatic checks) changes.

**Comment by lshep** [comment]
**Build Report**

- [ ] We highly suggest having unit tests

- [ ] We highly suggest adding a NEWS file. The NEWS file is what we use to generate the release announcements to recognize changes and updates to code. [example release announcement](http://bioconductor.org/news/bioc_3_10_release/)

**README**

- [ ] Add Bioconductor installation instructions as well. 

**DESCRIPTION**

- [ ] Remove Date field. Should be generated automatically and not needed to put directly in the DESCRIPTION

- [ ] Please remove `LazyData: true` we have found this rarely proves useful and can actually slow down the installation of a package

**NAMESPACE**

- [X] Okay

**INST**

- [ ] Include an inst/scripts directory that has information on how the data in inst/extdata was generated.  It should be an R script, sudo-code, or text information the source and any relavalent processing

**Data**
- [X] Okay

**Vignette**

- [ ] As @mtmorgan previously stated: please use `rtracklayer::import()` to import the gff file into a standard R data representation; make sure that this representation can be used as inputs to your functions. GenomicRanges GRanges object is the common class structure in Bioconductor to represent genomic positions. 


**man pages**

_data man pages_

- [ ] man files for data seem incomplete.   `TBA`

_NucleotideOverlap_

- [ ] I would make it more explicit that the Synteny object is from DECIPHER.
- [ ] GeneCalls should be GRange or GRangeList from GenomicRanges.
- [ ] List the options for OutputFormat. I don't know what else besides "Normal" can be used
- [ ] inluced references and note or remove
- [ ] based on the code it seems like GeneCalls also needs more information like
  that it should be named 

_PairSummaries_
- [ ] How would one create the DBPATH or get the DBPATH? This is unclear to me? Where does this come from? Is it common output when creating the DECIPER object?
- [ ] remove TBA sections
- [ ] What are the options for Correction?
- [ ] Elobrate if possible for all descriptions

_gffToDataFrame_
- [ ] Remove this entirely and use already implemented Bioconductor function `rtracklayer::import`


**R code**
In general the code need clean up and compression. 

_PairSummaries_
- [ ] GeneCalls should be GRange or GRangeList
- [ ] Do all checking for valid arguments at the start of the function. Include additional checks for model, correction, etc. 
- [ ] can some of the conditional code be together. Example: All if(PID) in the same location instead of multiple separate conditionals. condense where possible 
- [ ] Instead of multiple
```
  TotalCoverage <- vector("list",
                          length = Total)
  MinCoverage <- vector("list",
                        length = Total)
  MaxCoverage <- vector("list",
                        length = Total)
```
It would be more readable to do 
```
TotalCoverage <- MinCoverage <- MaxCoverage <- vector("list", length = Total)
```
It looks like you did this for some but not all. 

- [ ] Minimize function calls.  It would be cleaner to assign arguments in conditional and have a single call to the functions. This is an example but should be applied throughout
```
    if (!(GeneCalls[[m1]][SyntenyLinks[[m1, m2]][i, "QueryGene"], "Coding"]) |
              !(GeneCalls[[m2]][SyntenyLinks[[m1, m2]][i, "SubjectGene"], "Coding"]) |
              IgnoreDefaultStringSet) {
            # align as nucleotides
            IDType[[Count]][i] <- "DNA"
            Scores[[Count]][[i]] <- 1 - DistanceMatrix(myXStringSet = AlignSeqs(myXStringSet = Scores[[Count]][[i]],
                                                                                verbose = FALSE),
                                                       penalizeGapLetterMatches = GapPenalty,
                                                       includeTerminalGaps = TerminalPenalty,
                                                       correction = Correction,
                                                       type = "matrix",
                                                       verbose = FALSE)[1, 2]
          } else {
            # align as AAs
            IDType[[Count]][i] <- "AA"
            Scores[[Count]][[i]] <- 1 - DistanceMatrix(myXStringSet = AlignTranslation(myXStringSet = Scores[[Count]][[i]],
                                                                                       sense = "+",
                                                                                       direction = "5' to 3'",
                                                                                       type = "DNAStringSet",
                                                                                       readingFrame = 1L,
                                                                                       verbose = FALSE),
                                                       penalizeGapLetterMatches = GapPenalty,
                                                       includeTerminalGaps = TerminalPenalty,
                                                       correction = Correction,
                                                       type = "matrix",
                                                       verbose = FALSE)[1, 2]


```
Would become.  
```
    if (!(GeneCalls[[m1]][SyntenyLinks[[m1, m2]][i, "QueryGene"], "Coding"]) |
              !(GeneCalls[[m2]][SyntenyLinks[[m1, m2]][i, "SubjectGene"], "Coding"]) |
              IgnoreDefaultStringSet) {
	myXStringSet = AlignSeqs(myXStringSet = Scores[[Count]][[i]], verbose =	FALSE)
	type = "DNA"
   }else{
        myXStringSet = AlignTranslation(myXStringSet = Scores[[Count]][[i]], sense = "+",
		       direction = "5' to 3'",type = "DNAStringSet", readingFrame = 1L, verbose = FALSE)
        type = "AA
  }
  IDType[[Count]][i] <- type
  Scores[[Count]][[i]] <- 1 - DistanceMatrix(myXStringSet = myXStringSet, 
                                             penalizeGapLetterMatches = GapPenalty,
                                             includeTerminalGaps = TerminalPenalty,
                                             correction = Correction,
                                             type = "matrix",
                                             verbose = FALSE)[1, 2]

```
This eliminates redundant code and condense the code to make it easier to read. Please apply throughout this script and NucleotideOverlap.R 
Another example 
```
  if (PIDs) {
    DF <- data.frame("TotalCoverage" = unlist(TotalCoverage),
                     "MaxCoverage" = unlist(MaxCoverage),
                     "MinCoverage" = unlist(MinCoverage),
                     "NormDeltaStart" = unlist(NormDeltaStart),
                     "NormDeltaStop" = unlist(NormDeltaStop),
                     "NormGeneDiff" = unlist(NormGeneDiff),
                     "ExactMatch" = unlist(ExactMatch),
                     # "LeftDeviation" = unlist(AbsStartDelta),
                     # "RightDeviation" = unlist(AbsStopDelta),
                     # "SubjectLeft" = unlist(ExactLeftS),
                     # "SubjectRight" = unlist(ExactRightS),
                     # "QueryLeft" = unlist(ExactLeftQ),
                     # "QueryRight" = unlist(ExactRightQ),
                     "PID" = unlist(Scores),
                     "PIDType" = unlist(IDType),
                     stringsAsFactors = FALSE)
    rownames(DF) <- unlist(LabelNames)
  } else {
    DF <- data.frame("TotalCoverage" = unlist(TotalCoverage),
                     "MaxCoverage" = unlist(MaxCoverage),
                     "MinCoverage" = unlist(MinCoverage),
                     "NormDeltaStart" = unlist(NormDeltaStart),
                     "NormDeltaStop" = unlist(NormDeltaStop),
                     "NormGeneDiff" = unlist(NormGeneDiff),
                     "ExactMatch" = unlist(ExactMatch),
                     # "LeftDeviation" = unlist(AbsStartDelta),
                     # "RightDeviation" = unlist(AbsStopDelta),
                     # "SubjectLeft" = unlist(ExactLeftS),
                     # "SubjectRight" = unlist(ExactRightS),
                     # "QueryLeft" = unlist(ExactLeftQ),
                     # "QueryRight" = unlist(ExactRightQ),
                     stringsAsFactors = FALSE)
    rownames(DF) <- unlist(LabelNames)
  }
```
You could construct the overlapping DF first and then apply the additional columns in the conditional only. 
And again with choosing the model. The conditional should be the model difference
and then only a single call 
```
# shortened for example
if (Model == "Global") {
      data("GlobalSelect",
           envir = environment(),
           package = "SynExtend")
      modelData = GlobalSelect
else if (Model == "Local") {
      data("LocalSelect",
           envir = environment(),
           package = "SynExtend")
       modelData = LocalSelect
}

KeepSet <- predict(object = modelData, DF, type = response")
DF <- cbind(DF,"ModelSelect" = KeepSet >= 0.5)
```

- [ ] Remove commented out code


_NucleotideOverlap_

- [ ] OutputFormat doesn't change between options? Also have a check for valid
  value of OutFormat at the start of the function.

```
> Links <- NucleotideOverlap(SyntenyObject = Syn,
+                            GeneCalls = GeneCalls,
+                            LimitIndex = FALSE,
+                            Verbose = FALSE)
> Links
                   1                  2          3
1                            1683 Pairs 1760 Pairs
2 609223 Nucleotides                    1781 Pairs
3 802650 Nucleotides 623239 Nucleotides           
> Links <- NucleotideOverlap(SyntenyObject = Syn,GeneCalls=GeneCalls, LimitIndex=FALSE, Verbose=FALSE, OutputFormat="Comprehensive")
> Links
                   1                  2          3
1         1794 Genes         1683 Pairs 1760 Pairs
2 609223 Nucleotides         2264 Genes 1781 Pairs
3 802650 Nucleotides 623239 Nucleotides 2216 Genes
> Links <- NucleotideOverlap(SyntenyObject = Syn,GeneCalls=GeneCalls, LimitIndex=FALSE, Verbose=FALSE, OutputFormat="Sparse")
> Links
                   1                  2          3
1                            1683 Pairs 1760 Pairs
2 609223 Nucleotides                    1781 Pairs
3 802650 Nucleotides 623239 Nucleotides           

```
- [ ] Check valid argument values at the start of function.  
- [ ] GeneCalls should be GRange or GRangeList
- [ ] Apply comments to avoid redundant code and to condense where possible to this script as well.

_gffToDataFrame_
- [ ] Remove this entirely and use already implemented Bioconductor function `rtracklayer::import`


Please apply the above corrections and clean up.  When ready make sure there is a new build with a valid version bump and comment back here with a summary of the updates.  

Thank you for your submission to Bioconductor
~ Lori

**Comment by npcooley** [comment]
Hi Lori,

Thanks for all the reviewing! I'll get started on your comments as I have time.

I would be happy to make NucleotideOverlap flexible in that it could take in a Genomic Ranges object, but just the wholesale import of the GFF is actually not useful to us. The text parsing that the gffToDateFrame performs is just sort of speculative, but all the parent/id matching and condensing would still have to be performed on the Genomic Ranges object anyway. It made more sense for us to parse it straight from the original file.

I.e. a naive user would be just fine pulling the gene bounds from a gff generated by Prodigal or Prokka using a `rtracklayer::import` because those programs don't think about genes with complex bounds, but if I pull a generic refseq or genbank gff, it will need additional condensing to drop redundant bound sets (such as were the same bound is marked for "gene", "mrna", "exon", and "cds"), and to correctly think about the coding space for cases where multiple exons exist.

Keeping a condensed format is useful for me internally because it allows me to correctly reconcile CDS and gene bounds in a single place, and keep track of indices in the source FASTA file. It seems useful for a naive user as well because the data format is just simpler.

Once again I'm happy to make it flexible, and if GRanges objects can support ragged ranges for gene positions I can convert my output to that, but those are changes I would prefer to implement in a later release if possible.

Cheers,
Nick

**Comment by lshep** [comment]
In Bioconductor the recommended and almost always required structure for data
involving genomic position information is GenomicRanges in either a GRanges or
GRangesList object.  Users that have been using Bioconductor pipelines and
workflows will expect this and at minimum expect the function to be able to
handle this type of object.  There is also some consideration of how your parser
handles the range and range intervals.  Bioconductor standards for ranges are
1-based, closed intervals and this would have to be implemented so there is no discrepancy from standard usage throughout Bioconductor; this is the reasoning for using the rtracklayer::import function as it takes all of this into consideration when
doing the parsing; it is a fast and developed function that would guarantee correctness.  It seems like your other manipulations (parent/id matching,
etc) and additions of information can be performed on the imported GenomicRanges
object and this would be preferred. The GenomicRanges package has been highly
developed over the years, as a very mature package, and has many useful
functionalities that could prove useful in development. Please update the
package in the current version before acceptance; in our experience promises of
updating in future implementations never come to fruition.

**Comment by lshep** [comment]
Is the package ready for a re-review?  If so please summarize changes that have been made here.

**Comment by lshep** [comment]
Please remember all packages must be reviewed and accepted by april 22 to be included in the 3.11 release else they will be in devel until the released in fall 3.12

**Comment by npcooley** [comment]
Ohp, I missed your earlier notification, sorry! Yes, the package is ready for review.

- Attempted to address all comments on documentation and vignette.
- Addressed changes to code, including simplifications and removal of commented out lines
- Added GRange objects as an option for inputs to functions.
- gffToDataFrame remains in the package because it is not simply just importing the gff files, it is perfroming parsing functions that are essential. That parsing either has to occur upfront, or interior to later functions, and my preference is for it to happen up front.

**Comment by npcooley** [comment]
Hi,

I know this is cuttiing it close to the deadline, but is it possible to get
a review back for this package today?

Cheers,
Nick

**Comment by lshep** [comment]
A few more minor comments that should be doable: 

**NEWS**

- [ ] not formatted properly.  See `?news` in R and/or [Bioc news linke](http://bioconductor.org/developers/package-guidelines/#news)

**README**

- [ ] Don't include version in `BiocManager::install()` This will change will   given Bioconductor releases and BiocManager should pick up the necessary (and correct) version automatically

**Vignette**
okay

**Other**

- [x] we still would recommend using the rtracklayer::import but your ranges are
  imported with Bioconductor standards so we will let this go. In the future if
  you develop more packages reuse existing imports and class structures wherever
  possible. 

**man**

_NucleotideOverlap_

- [ ] Again I would put in the man page that the object of class 'Synteny' is   from DECIPHER. 

_PairSummaries_

- [ ] Since it seems like correction can only be none or jukes-cantor it probably should be explicitly stated so a user doesnt have to then go to the DistanceMatrix help page to find what it can be.

_Other_

- [ ] Since you reference them as output formats and input formats, you should   have a help page describing the strucutre of the LinkedPairs object. What does it contain?  And then link this help page in the other pages that take as input or output. 

**R code**

- [ ] Remove paste from messsage/warning/error code. It pastes automatically. 

Cheers,

**Comment by npcooley** [comment]
Hi,

I've attempted to address all issues, please let me know if further changes are required.

Cheers,
Nick

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/npcooley.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SynExtend")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SynExtend

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
