### ISSUE TITLE
TADBD

### ISSUE THREAD

**Issue by bioinfo-lab** [Bioconductor/Contributions#1372]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bioinfo-lab/TADBD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please provide a Description: more like a paper abstract, e.g., like the abstract presented in your vignette. Please do not use undefined acronyms ('TAD') in the Title: or Description.

Please revise your code to interoperate with [standard Bioconductor classes][1], e.g., `SummarizedExperiment`, `DataFrame`. Please review relevant Bioconductor packages (e.g., [diffHic][2], [InteractionSet][3]) to identify common data representations for interfacing with your user, so that the user can easily use your package.

Please do not execute `rm()` in your code, it should not be necessary.

Your reviewer will provide additional comments after the above issues and others identified by the automatic builder are addressed.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/diffHic
[3]: https://bioconductor.org/packages/InteractionSet

**Comment by nturaga** [comment]
Hi @bioinfo-lab 

Please make the necessary changes prescribed by mtmorgan, before I further go in for a full review of your package. 

Also note that, try and bump the version of your package to rebuild and get a new build report. 

We usually give authors about 2 weeks to respond to the comments made by us, and produce some changes in their package. I'll check back in 2 weeks time.

**Comment by nturaga** [comment]
# Review

## R CMD build

* ok 

## R CMD INSTALL

* ok

## General

* The comments given by @mtmorgan were not implemented and taken into
  consideration. Please do so! It's imperative that your package works
  in a way to interoperate with standard bioconductor classes.

## DESCRIPTION

* The description of the package should be like a paper abstract.

## NAMESPACE

* Please consider using roxygen `@export`, read 

	http://bioconductor.org/developers/package-guidelines/#namespace

## NEWS

* Make sure the news file can be parsed, 

		utils::news(package="<name of your package>")

## R

* Why is there a .zip file in your package? Is this needed? This can
  pose as a major problem for users.

* The first file `DataLoad.R` involves too much hard coding of chr and
  values. Please interoperate with other bioconductor packages and
  avoid this.

* Please follow the coding style we prescribe
  http://bioconductor.org/developers/how-to/coding-style/
  
  As it stands, the coding style you use right now makes it very time
  consuming for me to read the code and have an understanding of it.
  
* Please also follow the the robust and efficient coding practices,
  (this one is particularly important)

	http://bioconductor.org/developers/how-to/efficient-code/

* Do not use `1:length()` use `seq_length()` instead.

* Your package's build report has 

		ERROR count: 2
		WARNING count: 4
		NOTE count: 9

  Without fixing most of these, we cannot move forward with the
  package code review.

* There are many matrix operations which can be optimized in
  TADBD.R. You use too many nested forloops. There are ways to
  optimize this in R. Please follow the resources on numerical
  computation in R to optimize your code.

## vignette

* Please use 'BiocStyle' package for the vignette.

* I'll take a second look at your vignette once your package is
  imporoved. 

## man

* ok

**Comment by nturaga** [comment]
As an additional note, it has been over 20 days since your last response. We usually give authors 14 days to improve on packages and respond. 

Please note that since it's a time of distress around the world, we can close this issue and reopen it once you are able to work on your package again. If you are not able to work on it in 14 days, just let me know. There will not be a problem in reopening the issue.
