### ISSUE TITLE
scDataviz: single cell dataviz and downstream analyses

### ISSUE THREAD

**Issue by kevinblighe** [Bioconductor/Contributions#1374]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kevinblighe/scDataviz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
Thank you for your submission. Please see the review below.
Overall, the package is in good shape. 

Best regards,
Marcel
---
# scDataviz #1374

## DESCRIPTION

* It looks good.
* Please add a `BugReports` field pointing to the issues page on GitHub.

## NAMESPACE

* Use roxygen to generate `NAMESPACE`
* Looks good.

## vignettes

* Keep to the 80 column width limit in the vignette
* It would be good to include a small subset of the dataset in the package so
to avoid download from the vignette and GitHub (`SeuratToSCEb`)

## R

* Provide a `verbose` argument for users who would like to suppress messages
from functions.
* Create a package-wide theme for `ggplot2` instead of copying and pasting the
same code into different functions
* Avoid `0:x` sequence generation, use the more robust `seq_len` or `seq_along`
* Try to isolate differences in conditions, for example, `drawConnectors` as T/F and
`celllab` NULL or not, into a simple assignment
`colConnectors <- if (!drawConnectors) NULL`. This reduces the amount of code
needed.
* Some functions look similar enough, for example `metadataPlot` and
`contourPlot`, to be abstracted (if possible) so to get both with one function
* The sheer number of arguments in some functions may impact usability among
novice users. If possible, keep arguments to a minimum.
* Formatting looks good.

Minor:
* These are equivalent: `length(x) > 0` and `length(x)` within an `if`.
* Avoid redundant `if (gridlines.major == TRUE)`. `if` is already checking for
`TRUE`

## / (src folder)

* Remove folders and files that do not belong such as `README_files` and
`library.bib` or at least add them to the `.Rbuildignore`. Ideally these
should only exist in your local GitHub repository.

**Comment by kevinblighe** [comment]
Hey @LiNk-NY - thanks! I have been busy but will address all of these in the next week or two. It may not likely make the next Bioc submission.

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
Any updates on the status of the response to the review? 
Thanks. 
-Marcel

**Comment by kevinblighe** [comment]
Hi @LiNk-NY, sorryr, the virus has thrown everything into chaos. I am planning to get back to this, but doubtfull that it will make the next Bioc release. I appreciate your efforts and will follow-up

**Comment by kevinblighe** [comment]
Hi Marcel, I was curious about this point:

> It would be good to include a small subset of the dataset in the package so
> to avoid download from the vignette and GitHub (SeuratToSCEb)

The data that I use for the vignette is relatively large, and is pulled from this repo: https://github.com/kevinblighe/scDataviz_data

What is the best way for dealing with this? Should I create a separate data package altogether?

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 

If you would like to publish this data, it should be as it's own ExperimentHub / experiment data package given the size.
Otherwise, if you are using the data for the vignette and/or examples, create a small manageable subset of the data within the submitted package to _demonstrate_ functionality.
Pulling data from a GitHub repo is generally discouraged.
Best,
Marcel

**Comment by kevinblighe** [comment]
Hey Marcel @LiNk-NY - thanks! I checked the options here (https://www.bioconductor.org/developers/package-guidelines/) and it seems that using _inst/extdata/_ would be easiest option in order to show the functionality of the package in a vignette. I presume that the overall file size of the tarball of 5MB still applies, in this case?

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
That's right! 
-Marcel

**Comment by kevinblighe** [comment]
Hey @LiNk-NY Marcel, that push was just to figure out how to utilise data via _inst/extdada_. It seems to have built the vignette okay. I will start to address the other issues next.

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
The size of the tarball exceeds 5 MB. Please update the package. 
Thank you. 
-Marcel

**Comment by LiNk-NY** [comment]
Changes have to be made before April 22nd (in time for me to have a second look). Thanks! 
https://www.bioconductor.org/developers/release-schedule/

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
Please provide any updates. Unfortunately, tomorrow is the deadline to add new packages and it does not appear that `scDataviz` will be part of the Bioconductor release. We can still add the package to the development branch after the changes are made. 
Thank you. 
Regards,
Marcel

**Comment by kevinblighe** [comment]
Hey @LiNk-NY, yep, no chance of it making the next Bioc release, but not to worry. I am still getting through other workloads, but will address this package wen time becomes free. Thanks for following up!

**Comment by kevinblighe** [comment]
Hey Marcel, I have addressed a few of the issues (but not all). My main goal right now is to find the balance between the number of cells used in the vignette to the tarball size. My local tarball is 3.9MB, but it always seems higher when going through the Bioc system. I will await the current Bioc build to finish to see how it comes out.

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 

I've built the package and it's 4.5 Mb for me although it's quite different for the builders.
I wouldn't worry about it for now. 

Please resolve this note from `BiocCheck`: 

```
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 7 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    function (object)
      clusKNN (metadata)
      clusKNN (metadata<-)
      importData (rowVars)
      importData (metadata<-)
      markerExpressionPerCluster (metadata)
      plotSignatures (metadata)
      processFCS (metadata<-)
```

-Marcel

**Comment by kevinblighe** [comment]
Thanks - I think that I am mostly there. I will prepare a response to your original points, probably later tonight.

**Comment by kevinblighe** [comment]
Okay, hopefully that will now build okay.  Here is a point-by-point response (unfortunately, not 100% finished yet):

**DESCRIPTION**

> Please add a BugReports field pointing to the issues page on GitHub.

BugReports has been added

----------------

**NAMESPACE**

> Use roxygen to generate NAMESPACE

I have not trained too much in Roxygen. As I understand, this essentially means that the Rd and R file for a particular function are amalgamated? do we still therefore use the Rd file in _man/_?

----------------

**vignettes**

> Keep to the 80 column width limit in the vignette

I have done this where possible.

> It would be good to include a small subset of the dataset in the package so
> to avoid download from the vignette and GitHub (SeuratToSCEb)

In the Bioconductor Vignette, I have removed this part; well, I am still mentioning how one can use Seurat output within scDataviz, but that's all. I will maintain a separate GitHub vignette where I do these steps.

----------------

**R**

> Provide a verbose argument for users who would like to suppress messages
> from functions.

Added.

> Create a package-wide theme for ggplot2 instead of copying and pasting the
> same code into different functions

I have done this by adding a new internal function, _basetheme.R_


> Avoid 0:x sequence generation, use the more robust seq_len or seq_along

I have modified all cases of this. In some, I have used `seq()` - I presume that this is okay.


> Try to isolate differences in conditions, for example, drawConnectors as T/F and
> celllab NULL or not, into a simple assignment
> colConnectors <- if (!drawConnectors) NULL. This reduces the amount of code
> needed.

I have changed all instances of this where I am using `TRUE` or `FALSE`. For detecting NULL, I am still using `is.null()` - is this okay?

> Some functions look similar enough, for example metadataPlot and
> contourPlot, to be abstracted (if possible) so to get both with one function

You're right, and I will have to take a closer look at this. If I may leave this until the other issues have been addressed.


> The sheer number of arguments in some functions may impact usability among
> novice users. If possible, keep arguments to a minimum.

Yeh, there are many parameters. I like to have plots highly configurable for advanced users; for beginners, the benefit is that most functions can be run with just one or a few parameters. This logic has worked well so far in 2 of my other packages, _EnhancedVolcano_ and _PCAtools_; however, if you feel that they need to be reduced, then I can do that.

----------------
----------------

**Minor:**
> These are equivalent: length(x) > 0 and length(x) within an if.
> Avoid redundant if (gridlines.major == TRUE). if is already checking for
> TRUE

Yep, changed all instances of these

----------------

**/ (src folder)**

> Remove folders and files that do not belong such as README_files and
> library.bib or at least add them to the .Rbuildignore. Ideally these
> should only exist in your local GitHub repository.

Done this too.

----------------


Regarding the other issues about object initialisation, I am not sure how to address that. There is actually a clash in those functions whereby metadata is both a command line parameter and also a function name from Aaron's _SingleCellExperiment_ package. I presume that the only solution is to modify the variable name for these functions, to, e.g., 'meta'?

Thanks Marcel!

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
Apologies for the delay in responding. 
Thank you for making those changes. I've had a look at them and they look great. 

To respond to your questions: 

> Use roxygen to generate NAMESPACE
>> I have not trained too much in Roxygen. As I understand, this essentially means that the Rd and R file for a particular function are amalgamated? do we still therefore use the Rd file in man/?

You don't have to worry about using import directives from `roxygen2`. As long as the NAMESPACE is complete, there is no issue. In order to resolve the "object initialization" issue, provide the appropriate imports in the NAMESPACE so that `metadata`, `metadata<-`, and `rowVars` are available. 

> It would be good to include a small subset of the dataset in the package so
to avoid download from the vignette and GitHub (SeuratToSCEb)
>> In the Bioconductor Vignette, I have removed this part; well, I am still mentioning how one can use Seurat output within scDataviz, but that's all. I will maintain a separate GitHub vignette where I do these steps.

You can certainly do this but it would be good to not have to maintain separate vignettes and have a small example dataset (or even use an existing one from `ExperimentHub`) to run the examples in the vignette. 

>> I have changed all instances of this where I am using TRUE or FALSE. For detecting NULL, I am still using is.null() - is this okay?

Yes, using `is.null` is recommended for those cases. 

Best regards,
Marcel

**Comment by kevinblighe** [comment]
Thanks - I will get back to this when I next have a window of time!

**Comment by kevinblighe** [comment]
Hi @LiNk-NY , hopefully this should do it! I have done the following:

- now using Roxygen
- modified functionality in plotSignatures.R and markerEnrichment.R

May still be issue with tar.gz overall size.

If / when accepted and on the Bioc devel branch, I'll add more text to vignette and code Man pages.

**Comment by kevinblighe** [comment]
hmm, I reduced the extdata by 2500 cells to 7500 but the tarball seems to be almost the same size (?)

**Comment by lshep** [comment]
Maybe try http://bioconductor.org/developers/how-to/git/remove-large-data/

**Comment by kevinblighe** [comment]
Unfortunately, I am not sure what to do at this point. The tarball is only 2.5MB on my local computer (Ubuntu 16.04). The extdata is already reduced from > 1 million cells to just 5000 cells, meaning that the vignette suffers, too. This is why I am maintaining a separate vignette on the GitHub page. Any thoughts?

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
The vignette should demonstrate the functionality available in the
package and not represent a real-world analysis. It would be better to
keep everything in one place to reduce the burden of maintaining the
package and changes to the code. 
Don't worry if you go a bit over the 5 Mb limit.

**Comment by kevinblighe** [comment]
Okay, that should hopefully resolve it! I noticed that there were many 'junk' cells and markers in the extData, so, they have been cleaned. Also, I have done further testing on other datasets to improve processFCS.R's functionality.

**Comment by kevinblighe** [comment]
Strange error.. I will try to figure out what's happening.

**Comment by kevinblighe** [comment]
I spoke to Aaron and it seems to be an issue with SingleCellExperiment. Aaron says to try "_master 1.11.6_"? Is that possible on Bioc's side or something that I should debug locally?

**Comment by lshep** [comment]
If its pushed to Bioconductor the single package builder will automatically pick up the newest version.  You would want to trigger a new build after its pushed and propagated

**Comment by lshep** [comment]
When this shows 1.11.6  you can try a new build: http://bioconductor.org/checkResults/devel/bioc-LATEST/SingleCellExperiment/   

In the meantime I suggest testing locally

**Comment by lshep** [comment]
FWIW -- The maintainers of SingleCellExperiment have not pushed 1.11.6 to the git.bioconductor.org repo.  You may want to remind them as we will not pull any remotes or github versions of packages.

**Comment by kevinblighe** [comment]
Ah, I still have to wait until it is updated to 1.11.6 here: http://bioconductor.org/checkResults/devel/bioc-LATEST/SingleCellExperiment/
I can confirm that it works with 1.11.6 on my local machine, though.

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
It looks like there's a timeout on Linux. Any updates on this? 
You could try a version bump first to see if it was an issue on the server side.
Best,
Marcel

**Comment by kevinblighe** [comment]
Done now - this is certainly a bulky package. I don't know why the tarball is huge again - I've not changed the extdata.

**Comment by kevinblighe** [comment]
Sorry for delay @LiNk-NY. Is the tarball still too large? I can possibly try to reduce it further by removing figures from the vignette.

**Comment by LiNk-NY** [comment]
Hi Kevin, @kevinblighe 
The size of the tarball is okay.
It looks like you've resolved all the issues.
Thanks for your contribution!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinblighe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scDataviz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scDataviz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by kevinblighe** [comment]
Thanks so much to all - @LiNk-NY @lshep @mtmorgan !!
