### ISSUE TITLE
RNAAgeCalc

### ISSUE THREAD

**Issue by reese3928** [Bioconductor/Contributions#1375]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reese3928/RNAAgeCalc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It seems like the user-facing functions should accept [SummarizedExperiment][1] and other [standard Bioconductor classes][2] to enhance interoperability and robust software.

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by reese3928** [comment]
Hi Daniel @dvantwisk ,

As suggested by Dr. Morgan, we have updated our package such that it supports SummarizedExperiment as user input. The unit tests and vignette regarding SummarizedExperiment input were also updated. The package build results are "OK" and it is ready for review. Please let us know if there is any issue. Looking forward to you review. Thanks.

Sincerely,
Xu Ren

**Comment by dvantwisk** [comment]
Great! I will review your package soon!

**Comment by dvantwisk** [comment]
I apologize for the wait. Here is a review of your package. [REQUIRED] tags are changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not necessary. Please message me back when you are finished making changes.

R/count2FPKM.R
- [ ] [REQUIRED] In the `DESeq2` package there is a function called `fpkm()`
that converts raw counts to fpkm. Since it's best to reuse existing
functionality, is there a reason not use `fpkm()` here and to create a new
function? If not, it would be better to use `fpkm()`.

R/exampledata.R
- [ ] [REQUIRED] Please be more explicit about the source and shape of the data
in the documentation.

R/predict_age.R
- [ ] [CONSIDER] Using `match.arg()`. In the function `predict_age()`, the
argument `exprtype` can be written as `epxrtype=c("FPKM","counts")`. The 
default value is "FPKM". This makes it explicit to the user which arguments are
accepted here. The user's selected value can be obtained with
`exprtype <- match.arg(exprtype)`. An error will be thrown if any unacceptable
values are given. This can be done in other arguments throughout the package.

R/sysdata.rda
- [ ] [REQUIRED] Is `system.rda` needed? If not, please remove it.

**Comment by reese3928** [comment]
Hi Daniel @dvantwisk ,

Thanks very much for your review. We have addressed all of your comments and the package is ready for second round review. Here is our point-by-point response to your comments.

> R/count2FPKM.R
> 
> * [X]  [REQUIRED] In the `DESeq2` package there is a function called `fpkm()`
>   that converts raw counts to fpkm. Since it's best to reuse existing
>   functionality, is there a reason not use `fpkm()` here and to create a new
>   function? If not, it would be better to use `fpkm()`.

We understand that reusing existing functionality is preferable than writing own functions. To reuse existing function when calculating fpkm, we are now using `getRPKM()` function from the [recount](https://bioconductor.org/packages/release/bioc/html/recount.html) package. The reason that we use `getRPKM()` from recount rather than `fpkm()` from DESeq2 is because our internal gene length database was also retrieved from recount. Thus using the functionality from recount is more consistent than using the functionality in DESeq2.

In addition, it is difficult to completely remove our function `count2FPKM()` because the function supports the calculation of fpkm for different gene id types ("SYMBOL", "ENSEMBL", "ENTREZID", "REFSEQ") and there are some preprocess that needs to be done before calling `getRPKM()` function. So we kept this function in the package for now.

> R/exampledata.R
> 
> * [X]  [REQUIRED] Please be more explicit about the source and shape of the data
>   in the documentation.

The shape, data source, reference, and how we process the example data is now included in the 
documentation files fpkm.Rd and rawcount.Rd.

> R/predict_age.R
> 
> * [X]  [CONSIDER] Using `match.arg()`. In the function `predict_age()`, the
>   argument `exprtype` can be written as `epxrtype=c("FPKM","counts")`. The
>   default value is "FPKM". This makes it explicit to the user which arguments are
>   accepted here. The user's selected value can be obtained with
>   `exprtype <- match.arg(exprtype)`. An error will be thrown if any unacceptable
>   values are given. This can be done in other arguments throughout the package.

Thank you for the suggestion. We are now using `exprtype = c("FPKM", "counts")` and then `exprtype <- match.arg(exprtype)` for this type of arguments throughout our package.

> 
> R/sysdata.rda
> 
> * [X]  [REQUIRED] Is `system.rda` needed? If not, please remove it.

The `system.rda` is essential for our package. It contains our research results discussed in our [manuscript](https://www.biorxiv.org/content/10.1101/2020.02.14.950188v1). The `system.rda` contains the gene signatures required to make the RNAAge calculation. This internal data is used in our `predict_age()` function line 249 and 251. The R script to generate this internal data was saved in: data-raw/internalData.R.

**Comment by dvantwisk** [comment]
I've reviewed the changes you made and they look fine. I am also satisfied with the explanations you provided. I am going to move to accept your package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/reese3928.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RNAAgeCalc")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RNAAgeCalc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
