### ISSUE TITLE
TAPseq

### ISSUE THREAD

**Issue by argschwind** [Bioconductor/Contributions#1382]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/argschwind/TAPseq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by argschwind** [comment]
Hi @mtmorgan,

Thank you for helping to review our package. I looked at the build reports and it looks like TAPseq didn't find the required tools when building the vignettes.

These programs are listed under SystemRequirements in DESCRIPTION. Are Primer3 (>= 2.5.0) and BLAST+ (>=2.6.0) installed and in PATH on the systems the package was build?

Thanks, Andreas

**Comment by mtmorgan** [comment]
Generally, the build systems will not be modified to support these dependencies, and a package that has such dependencies is generally not going to be usable across platforms (because the dependencies are not available to, e.g., Mac or Windows users). This compromises the utility of the package to the Bioconductor community, and complicates end-user and developer support.

My recommendation is to remove the dependencies from your package, e.g., by finding R-based alternatives. A less satisfactory solution is to modify your examples / tests /vignette not to use the functionality provided by this software, but then perhaps your code is not really tested in a way that builds confidence in the correctness of the code for the end user. The third alternative is to recognize that these third party tools are essential to your package, and that as a consequence the package is not portable across platforms and cannot be tested effectively, and so not appropriate for Bioconductor.

**Comment by argschwind** [comment]
I understand that not having the dependencies on the build systems means that my code won't be tested systematically. But I would consider [BLAST](https://www.ncbi.nlm.nih.gov/books/NBK279690) and [Primer3](https://github.com/primer3-org/primer3) long-standing and reliable bioinformatics tools, which are available for all three platforms. I built and tested the package on Linux (CentOS Linux 7), Mac (10.15.3) and Windows 10 (v. 1803). But I understand that this is anecdotal.

One of my reasons to submit it to Bioconductor was that there is another primer design package (http://bioconductor.org/packages/release/bioc/html/openPrimeR.html) available for a different task, which also utilizes 3rd party software. To me it looks like they do not test or run examples that depend on these tools.

If that would be an option for my package, I could create a new version that does not run examples requiring these tools. I would adapt unit tests so that the functions interacting with the tools are still tested, but do not rely on them creating output.

**Comment by mtmorgan** [comment]
yes what you describe would be an appropriate solution.

**Comment by mtmorgan** [comment]
Is your package ready for review?

**Comment by argschwind** [comment]
R CMD check on tokay2 still raises weird warnings regarding links to functions in the man pages that I have to figure out. Example:
"file link 'GRanges' in package 'GenomicRanges' does not exist and so has been treated as a topic"

Else it should be ready for review. The warning about the missing software when loading the package is intentional.

**Comment by mtmorgan** [comment]
I have only a few cursory comments; please revise and respond with a short comment when ready for final review.

DESCRIPION, NAMESPACE, vignettes

- good

R

- code seems to be well-organized and clearly written

- TsIO_classes.R:148 A more typical paradigm for a validity method reports all invalid components at once, along the lines of

    ```
    txt <- character()
    if (length(seqname) > 1)
        txt <- c(txt, "multiple seqnames in target_annot")
    if (length(strand) > 1)
        txt <- c(txt, "conflicting strand information in target_annot")
    ...
    if (length(txt)) txt else TRUE
    ```

- TsIO_classes.R:237 avoid use of internal functions; I think

    ```
    setClass("TsIOList", contains = "SimpleList", prototype = "TsIO")
    TsIOList <- function(...) {
        objects <- list(...)
        new("TsIOList, objects, elementType = "TsIO")
    }
    ```
    
- Will there be many `TsIO` elements in a typical `TsIOList`? If so it would be worth-while to revise `TsIO` so that it can have 'length' 0, 1, ..., using the 'trick' of `GRangesList` etc where a single object (GRanges) is partitioned into groups by a second partitioning object -- this creates a total of three object (GRangesList, GRanges, partitioning) rathern tan n + 1 objects, and will be economical in space and time. Using `mendoapply()`, for instance, is much less efficient on large objects for transformations that can be performed by operations such as `gr <- unlist(grl); ...; relist(gr, grl)`.

- TsIO_classes.R:398 replacement methods are usually written

    ```
    setReplaceMethod("sequence_id", "TsIO", function(x, value) {
        ...
    })
    ```

man

- well documented

**Comment by argschwind** [comment]
I implemented the suggested changes, except for the partitioning trick for the `TsIO` class.

A typical `TsIOList` should contain 100-250 elements and rarely exceed 500. `TsIOLists` typically contains one element per target gene and the number of target genes is subject to limitations of multiplex PCR.

I had a look at the `GenomicRanges` and `IRanges` packages, but could not find the code that does the partitioning. If you think that this should be done for `TsIO` objects, it would be helpful if you pointed me to some example code of how this is done.

**Comment by mtmorgan** [comment]
I guess the simple case is easily understood, rather than representing a list of 4 numeric elements as `list(1, 2, numeric(), c(3, 4, 5))` you could represent this as a single numeric vector `c(1, 2, 3, 4)` and a partitioning that told R where to break the vector into 'virtual' groups, e.g., `c(1, 2, 2, 5)` to end the first group after element 1, the second and third groups after element 2 (i.e., no elements in the third group, and the fourth group after element 5. The machinery could be
```
.My = setClass("My", contains = "CompressedList", prototype = prototype(elementType = "numeric"))
my = .My(unlistData = c(1, 2, 3, 4, 5), partitioning = PartitioningByEnd(c(1, 2, 2, 5)))
```
You get
```
> my
My of length 4
> lengths(my)
[1] 1 1 0 3
> my[[1]]
[1] 1
> my[[2]]
[1] 2
> my[[3]]
numeric(0)
> my[[4]]
[1] 3 4 5
```
but there's only one data vector `my@unlistData` plus the instructions for partitioning `my@partitioning`. This will be space and time efficient when there are a lot of elements. Some operations, e.g.,`unlist()` and `relist()` are very inexpensive, so something like `mendoapply(my, sqrt)` can be very efficiently implemented as `relist(sqrt(unlist(my)), my)`. 

I guess your TsIO data structure is quite complicated, so probably would require quite a bit of re-factoring to fit this paradigm (any vector-like object, e.g., a GRanges, can be partitioned in the way outlined above, but I guess you would have perhaps two or three vector-like objects in your class...). If this aspect of performance isn't a problem, then I wouldn't pursue it.

Incidentally I noticed when I walked through the TsIO-class man page and printed the first object created
```
> obj <- TsIO(sequence_id = tx_id, target_sequence = tx_seq, beads_oligo = beads_oligo,
+             reverse_primer = reverse_primer, product_size_range = c(350, 500))
> obj
TsIO instance
  1004 bp sequence template
  Sequence ID: AKIP1
  Beads oligo: CTACACGACGCTCTTCCGATCTNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
  Right primer: CTACACGACGCTCTTCCGATCT
  Specified product size range: 350-500 basepairs> 
```
I found myself in the middle of a line -- there should be a carriage return as the final output, so the prompt is on a new line.

**Comment by argschwind** [comment]
Thanks for the explanation! I don't believe that operations on `TsIOList` objects will be performance limiting. But if it turns out that users create huge `TsIOList` objects I guess I could always implement the proposed solution, which should only require internal changes to the package.

I improved the show method and added a newline at the end to ensure that the prompt is not in the middle of a line. Looks like RStudio automatically added a new line to the output...

**Comment by argschwind** [comment]
I think the package is ready for final review.

**Comment by argschwind** [comment]
Thank you very much @mtmorgan that you took the time to review this package and all the helpful input.

**Comment by mtmorgan** [comment]
@argschwind the file examples/close2017_upstream_seqs.fa is greater than the largest file size we allow in git (it's 6.1 mb, the maximum size is 5mb). Can you either (1) create a smaller file or (2) use an existing file from [AnnotationHub](https://bioconductor.org/packages/AnnotationHub) or (3) create an [ExperimentHub](http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html) data package for your data resources?

Let me know what your plan is and if I can be of any help.

**Comment by denniscwylie** [comment]
@mtmorgan I think you're referring to a file in my submitted package (sarks) not this one (TAPseq). The file in question (the whole examples directory, actually) is omitted from the R package itself in .Rbuildignore, but if it still causes a problem in the git repo anyway I could potentially remove it if necessary---just let me know!

Thanks,
Dennis

**Comment by mtmorgan** [comment]
yes it is in sarks, thanks for the clarification. Yes, it needs to be made smaller or removed from the git version that is added to Bioconductor.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/argschwind.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TAPseq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TAPseq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
