### ISSUE TITLE
gpaExample

### ISSUE THREAD

**Issue by carter-allen** [Bioconductor/Contributions#1384]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/carter-allen/gpaExample

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by carter-allen** [comment]
Updated carter-allen/gpaExample and added SSH keys

**Comment by carter-allen** [comment]
AdditionalPackage: https://github.com/carter-allen/GPA

**Comment by carter-allen** [comment]
@Kayla-Morrell hello, could I please have the GPA repository linked to this issue? Thanks.

**Comment by Kayla-Morrell** [comment]
@carter-allen - We had to delete the previous issues from our database. Try the "Additional Package:..." comment again.

**Comment by carter-allen** [comment]
AdditionalPackage: https://github.com/carter-allen/GPA

**Comment by carter-allen** [comment]
@Kayla-Morrell Hello, I was wondering if you might have any insight regarding the 'texi2pdf' error I am getting on the Windows builds. I am unable to replicate the issue on my machines. Is Sweave supported by Bioconductor still?

**Comment by Kayla-Morrell** [comment]
@carter-allen - This error seems to be something that needs to be fixed on our Windows builder. If the packages are ready (besides this error) I can go ahead and start my initial review.

**Comment by carter-allen** [comment]
@Kayla-Morrell Ok great, it seems like that is the only issue left so they should be good to go for review now. Thanks!

**Comment by Kayla-Morrell** [comment]
Hello @carter-allen,
Thank you for submitting to _Bioconductor_. Please see the initial review of both packages below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the packages are ready for a re-review.

# gpaExample 

## DESCRIPTION

- [ ] REQUIRED: 'LazyLoad' isn't needed. We instead like to have the field
'LazyData' and it should be set to false. It is our experience that when this
field is true the loading of the package is slowed down.

# GPA 

## General package development

- [ ] REQUIRED: The top 'build/' directory is not needed and should be 
removed.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the automatically suggested biocViews 
'GeneExpression' and 'DifferentialExpression'.

- [ ] REQUIRED: The 'LazyData:' field should be added and set to false.

- [ ] REQUIRED: When trying to access the url provided in 'URL', it said I don't 
have permission to access. This url should be something accessable to users. You 
might just consider having it be the url to the GitHub repo.

- [ ] REQUIRED: The 'git_url:' is not a necessary field. Instead I would suggest 
a 'BugReports:' field with the link to the GitHub Issues. 

- [ ] SUGGESTION: Since GNU make is a system requirement for your package, you 
might consider adding a section in the README about needing to download this 
requirement.

## NAMESPACE

- [ ] SUGGESTION: Generally importFrom() is encouraged over importing an entire 
package, especially if you are only utilizing a few functions from the package. 
Simplify the import() if possible.

## NEWS

- [ ] REQUIRED: The information in the NEWS file doens't seem accurate since 
the package is currenly at version 0.99.2. Please edit this file.

## Vignettes

- [ ] REQUIRED: There should be an 'Installation' type section that shows users 
how to download the package from Bioconductor (and not github). The code should 
look something like the following and should be `eval = FALSE`,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GPA")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and 
include `sessionInfo()`.

## Man pages

*GPA-class*

- [ ] REQUIRED: The version number for the package is not correct and should be 
changed.

*shinyGPA*

- [ ] REQUIRED: This function needs to be tested some how, whether that be 
through running the examples in the man page or through demonstrating it in the 
vignette.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along(). Found in the 
following files:
	- assoc.R, lines 38, 41, and 66
	- aTest.R, lines 33, 52, 58, 65, 72, 86, 120, 136, and 152
	- base_covGPA.R, lines 56, 75, 106, 113, 122, 133, 149, 150, 171, 172, 
	176, 183, 184, 187, 194, 204, 224, 239, and 259
	- fitAll.R, lines 10, 11, 74, and 88
	- GPA.R, lines 152, 207, 208, 209, 210, 211, 216, and 219
	- methods_GPA.R, lines 19, 48, 92, 106, 126, 225, 242, 252, 268, 281, 
	and 318
	- pTest.R, lines 27 and 37
	- shinyGPA.R, lines 7, 10, 186, 287, 363, and 407

- [ ] REQUIRED: Use the various apply functions instead of for loops, if 
possible.

- [ ] REQUIRED: Avoid the use of direct slot access with `@`. Accessor methods 
should be created and utilized instead.

- [ ] SUGGESTION: Consider shorter lines; 205 lines are > 80 characters long.

- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents, 380 lines are
not.

Best,
Kayla

**Comment by carter-allen** [comment]
Hi Kayla @Kayla-Morrell , Thank you for taking the time to review the gpaExample and GPA packages. We considered each comment carefully. Below is a list of responses to your comments and description of the changes we made to address them.
 
**gpaExample**
 
DESCRIPTION
- The ‘LazyLoad’ field was replaced with ‘LazyData’ and set to false.
 
**GPA**
 
General
- The ‘build/’ directory was removed.
 
DESCRIPTION
- The suggested biocViews ‘GeneExpression’ and ‘DifferentialExpression’ were added.
- ‘LazyData’ was added and set to false.
- The ‘URL’ field was updated with the proper web link.
- The ‘git_url’ field was changed to link to the github issues page.
- A comment and web link were added to the README instructing users on how to obtain GNU make.
 
NAMESPACE
- We used importFrom() for packages that only contribute a few needed functions but used import() for packages that contributed several needed functions.
 
NEWS
- The NEWS file was updated to reflect the latest version (0.99.8 at this time).
 
Vignette
- The suggested installation code was added to the beginning of the vignette.
- A table of contents was added to the vignette.
- sessionInfo() was added to the end of the vignette.
 
Man pages
- The version number in GPA-class was updated.
- We added a runnable example to the shinyGPA.Rd man file. However the final line shinyGPA(out) is at the moment commented out because it caused the R CMD check to hang on the open shiny app session. This code does work however, as when the example is run in a normal R session no errors are produced. We hope this is OK. If there is a better solution to address this, please let us know and we will address it as requested.

Unit tests
- We are considering adding unit tests in a future version of GPA.
 
R code
- All uses of 1:n were replaced with seq_len(n).
- The author of the package developed GPA with knowledge of the efficiency advantages of vectorized calculations in mind and used apply family functions when appropriate. However, we feel there are cases when using apply functions is unnatural or unhelpful, such as when performing many sequential calculations at each iteration or when simply printing data to the user. We considered each for loop carefully with this in mind.
- Each slot access with @ was replaced with the appropriate get_*() accessor function. These accessor functions were added to the methods_GPA.R and AllGenerics.R files.
- We went through each line of code and made many lines shorter when possible. However, in some cases lines had to be over 80 characters to accommodate longer messages printed to the user.
- We considered the use of 4 spaces for tabs and will consider incorporating this change in a future version of GPA.
 
Thank you again for the helpful critiques of GPA. We feel these changes significantly improved the package. If there is anything else we can do to make the package suitable for Bioconductor, please let us know.
 
Carter Allen
cc: @dongjunchung

**Comment by Kayla-Morrell** [comment]
@carter-allen - Thank you for making the necessary changes. I have looked everything over and just have two minor requirements before I can accept the packages. Please see the points below and let me know when you are ready for me to review them agin.

# gpaExample

- [ ] REQUIRED: You mentioned that you made the change for 'LazyData:' in the 
DESCRIPTION file, but I don't see the change.

# GPA

- [ ] REQUIRED: Thank you for updating the information in the NEWS file.
Unfortunately it isn't formated properly. Please see the following link on how
the file should be formated,
https://bioconductor.org/developers/package-guidelines/#news.

Best,
Kayla

**Comment by carter-allen** [comment]
Hi Kayla @Kayla-Morrell , thanks for catching those! I believe they should be fixed now. Please let me know if there is anything else we can do. 

Carter

**Comment by Kayla-Morrell** [comment]
@carter-allen - Everything looks good now and I'm more than happy to accept the packages.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carter-allen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gpaExample")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gpaExample

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carter-allen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GPA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GPA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
