### ISSUE TITLE
EpiTxDb

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/Contributions#1387]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FelixErnst/EpiTxDb

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/EpiTxDb.Sc.sacCer3

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/EpiTxDb.Hs.hg38

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/EpiTxDb.Mm.mm10

**Comment by FelixErnst** [comment]
I have to upload the `AnnotationHub` resources. I will let you know, when the vignettes are set up correctly

**Comment by FelixErnst** [comment]
I overread the boldly written note, that I have to wait with the additional packages. sry for that :flushed:  :cold_sweat: :no_mouth:

**Comment by FelixErnst** [comment]
@hpages Hi Herve,

I added the `rescale` function we discussed last year  (https://github.com/Bioconductor/IRanges/issues/16) to this package. In addition, have a look at the coercion of `Ranges`/`RangesList` to `integer`/`IntegerList`. Maybe that is also something for the `IRanges` package.

Felix

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/EpiTxDb.Hs.hg38

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/EpiTxDb.Sc.sacCer3

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/FelixErnst/EpiTxDb.Mm.mm10

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY

the packages are ready for review. The warnings are from a invalid biocViews value.

@lshep: Would it be possible to add `Epitranscriptomics` to the list of valid biocViews?

Best regards
Felix

**Comment by lshep** [comment]
There is already a `Transcriptomics` and `Epigenetics` biocviews; would these not suffice for the EpiTxDb package?  For the three annotationhub data packages, they would have annotation data views ( http://bioconductor.org/packages/devel/BiocViews.html#___AnnotationData)  instead of Software views I'm wondering if there is an appropriate term placement.

**Comment by FelixErnst** [comment]
`Epitranscriptomics` is distinct from the terms `Transcriptomics` and `Epigenetics`. It is what `Epigenetics` is for `Genetics`, but just for `Transcriptomics`. It is fairly established and I expect, that it might become more important in the future. Therefore, a new biocViews term would be justified from my point of view.

If one whould follow the other type of biocViews for annotation data `EpiTxDb` in the group `PackageType` might be necessary. I wouldn't add that for now, since I don't know, how the data resources will develop in the future and if the `Epitranscriptomics` will be important for multiple organisms.

**Comment by lshep** [comment]
I'll look at adding the Epitranscriptomics biocViews into the Software schema then.  Thanks for the clarification.

**Comment by FelixErnst** [comment]
> I'll look at adding the Epitranscriptomics biocViews into the Software schema then. Thanks for the clarification.

Hi Lori @lshep, do you have an ETA for the biocViews update? As this is non critical (at least I hope Marcel @LiNk-NY sees it that way :innocent:  ), there is no rush. It just would me some idea for planning the corrections to the package.

**Comment by lshep** [comment]
I pushed the update today actually.  It should propagate tonight and be available by the weekend.

**Comment by FelixErnst** [comment]
@LiNk-NY everthing is ready for review. Please disregard the `WARNINGS`, since the label is somewhat stuck probably due to the number of packages in this issue. All packages have cleared the build without `ERROR` or `WARNINGS`.

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 
Apologies for the delay. It took me some time to go over the number of files in the packages. 
On the other hand, the review is pretty short due to the organization of the packages.

Please see below. 
Thank you for your submission. 
Best,
Marcel

---

# EpiTxDb #1387

## DESCRIPTION

* Looks good.

## NAMESPACE

* Looks good.
* Perhaps you may want to go over some imports and see which ones you can do
without (e.g., `assertive`)

## vignettes

* Looks good and straightforward.

Minor:
* You can use multi-chunk options to include the `library` calls only in _one_
chunk. For example, you can set
`results="hide",include=TRUE,message=FALSE,warning=FALSE`
to show the chunk but not the results or messages etc.

## R

* Good work. Keep in mind that some pain points would be that unexported
helpers from `GenomicFeatures` can change at any time and you will have to
support any changes to them.
* Overall, the functions look modular and there are plenty of helper
function to support the modulartiy of the package.
* You could write SQL calls that are not string dependent but this is a minor
point and may not be worth the dependencies overhead (see `dbplyr`).

**Comment by FelixErnst** [comment]
Hi Marcel, @LiNk-NY 

thanks for the review and the comments.

I removed the non eval chunk from the vignette. I didn't know that chunk option setup since I never had a close look at how startup messages relate to normal messages. Thanks for the hint.

Regarding the use of `dbplyr`: I didn't want to add a layer on the `AnnotationDbi` interface and follow more closely what was done for the `TxDb` class.

I will push the changes next week.

Felix

**Comment by FelixErnst** [comment]
Hi Marcel, @LiNk-NY 

thank you for the review and the suggestions.

I removed the single call to assertive and combined the first two chunks in the vignette. Thanks again for the hint with the chunk settings.

Regarding the use of `dbplyr`: I looked into it, but opted to take the challange to implement the two version of SQL generators. It was a helpful exercise to take suggestions from the `TxDb` class and rework and optimize space requirements, table relations and SQL statement generator to achieve the functionality for this use case. Certainly lifted some cobwebs from my SQL skills.

I will push the changes shortly.

Felix

**Comment by FelixErnst** [comment]
Hi Marcel, @LiNk-NY

any news on the changes?

Cheers
Felix

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 
I've reviewed your changes and comments. 
Thank you for your quick response. I will accept the package. 
Don't forget to include an `Installation` section in the vignette. 
Best,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EpiTxDb")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EpiTxDb

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EpiTxDb.Hs.hg38")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EpiTxDb.Hs.hg38

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by FelixErnst** [comment]
@mtmorgan Thanks for adding the packages to Bioconductor's git repo. Could you also add `EpiTxDb.Sc.sacCer3` and `EpiTxDb.Mm.mm10`? Thank you

**Comment by lshep** [comment]
@mtmorgan   not sure where EpiTxDb.Hs.hg38  got added but these three packages are annotation packages  so @Kayla-Morrell will probably have to do some magic.

**Comment by mtmorgan** [comment]
Re-opening for additional processing

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EpiTxDb.Sc.sacCer3")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EpiTxDb.Sc.sacCer3

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EpiTxDb.Mm.mm10")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EpiTxDb.Mm.mm10

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
