### ISSUE TITLE
rrvgo

### ISSUE THREAD

**Issue by ssayols** [Bioconductor/Contributions#1391]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ssayols/rrvgo

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission.  I have just a few minor comments before acceptance. 

**build report**

- [X] Okay
- [ ] Although we highly suggest adding unit tests

**readme**

- [ ] Optional: but we suggest adding installation instructions in the readme

**description**

- [ ] remove date. it often is forgotten to update and time stamps should be generated automatically through other processes. 

**namespace**

- [X] okay

**news**

- [X] Okay

**inst**

- [ ] please include an inst/scripts/ that describes what and how the data in inst/extdata was generated including source information. 

**vignette**

- [ ] close paraenthesis `(see GOStats or GSEA`
- [ ] In running the code for treemap I got the following. Can it be cleaned up?
```
treemapPlot(reducedTerms)
Warning message:
In if (class(try(col2rgb(palette), silent = TRUE)) == "try-error") stop("color palette is not correct") :
  the condition has length > 1 and only the first element will be used
```
- [ ] should packages or a suite of packages be in suggest? 
```
> rrvgo::shiny_rrvgo()
Loading required package: shiny
Error in library(shinydashboard) : 
  there is no package called 'shinydashboard'
Error in library(heatmaply) : there is no package called 'heatmaply'
```

- [ ] I don't know if there is an option in shiny but when I finally ran the above and got the shiny app to open it opened in a browser that didn't indicate part of the app was cut off (no horizontal bar) or window size big enough so it was confusing to me at first at what I was suppose to do. I'm not sure if there is a way to make it more clear that there was more. If you like I can email you my screenshot.


**R / man pages**

data.R 

- [ ] This seems like the information I was looking for in an inst/scripts directory. Since this function isn't exported I would suggest moving in to inst/scripts. 

calculateSimMatrix man page
- [ ] Provide a link to the description of method available. where to find the description of these in the other package 

Thank you for the submission.  Please address these minor points and comment back here when ready.  Cheers

**Comment by ssayols** [comment]
Dear @Ishep,
thank you for the comments. We'll address them and get back to you.
Regarding the shiny app being cut off, I'd appreciate if you could share a screenshot. We may have missed how it looks like in some screen sizes.
Cheers

**Comment by ssayols** [comment]
Dear @lshep ,
the previous pushes address all your comments except 1) the issue with the sinyapp being cut off, and 2) the warning in `treemapPlot()`.

Regarding the latter, after researching a bit because I couldn't reproduce the issue in latest stable R 3.6.3, I realized the issue is due to a new feature in R 4.0.0 (which you're probably using to test the package). R 4.0.0 fixes [`matrix()` inherits also from "array"](https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html), and  `class(matrix())` will return `[1] "matrix" "array"` instead of just `[1] "matrix"`.

This produces the former warning, which is difficult to fix from my side since it's in imported code from the `treemap` package. From my side I see 3 solutions here:

* wrap the `treemap::treemap()` call within `suppressWarnings()`
* leave it as it is and open an issue with the `treemap` package maintainers
* both, and remove the `suppressWarnings()` once the issue is solved in `treemap`.

Which option would you favor?

Cheers, Sergi

**Comment by ssayols** [comment]
> Dear @lshep ,
> the previous pushes address all your comments except 1) the issue with the sinyapp being cut off, and 2) the warning in `treemapPlot()`.
> 
> Regarding the latter, after researching a bit because I couldn't reproduce the issue in latest stable R 3.6.3, I realized the issue is due to a new feature in R 4.0.0 (which you're probably using to test the package). R 4.0.0 fixes [`matrix()` inherits also from "array"](https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html), and `class(matrix())` will return `[1] "matrix" "array"` instead of just `[1] "matrix"`.
> 
> This produces the former warning, which is difficult to fix from my side since it's in imported code from the `treemap` package. From my side I see 3 solutions here:
> 
> * wrap the `treemap::treemap()` call within `suppressWarnings()`
> * leave it as it is and open an issue with the `treemap` package maintainers
> * both, and remove the `suppressWarnings()` once the issue is solved in `treemap`.
> 
> Which option would you favor?
> 
> Cheers, Sergi

Dear @lshep,
so, I filled a [pull request to the treemap package](https://github.com/mtennekes/treemap/pull/49), and as soon as it gets incorporated the warning will disappear.
Is it worth wrapping the `treemap()` call in `rrvgo` with a `suppressWarnings()` until the `treemap` package incorporates the patch?

cheers, Sergi

**Comment by lshep** [comment]
It the warning isn't stemming from your package I think the report of the warning is good.  It would be up to you if you would like to wrap it in the `suppressWarnings()` - if it is worth reporting until the patch then it is fine as is.   I'll send you a screenshot to the maintainer email but I don't see this issue being a show stopper.  I'll accept the package but encourage you to look into the shiny width issue.  Cheers

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ssayols.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rrvgo")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rrvgo

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
