### ISSUE TITLE
regutools

### ISSUE THREAD

**Issue by josschavezf** [Bioconductor/Contributions#1393]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ComunidadBioInfo/regutools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by josschavezf** [comment]
regutools has three maintainers:
-@josschavezf
-@jemilianosf
-@carbarjon

This package is part of the community CDSB http://comunidadbioinfo.github.io/

**Comment by jemilianosf** [comment]
I acknowledge that I am a maintainer of regutools.

**Comment by CarBarJon** [comment]
I acknowledge that I am a maintainer of regutools.

**Comment by nturaga** [comment]
Hi. 

Please note that Bioconductor allows only one maintainer on the package.

```
Only one person should be listed in the Maintainer field to ensure a single point of contact. This person by default will have commit access to the git repository on git.bioconductor.org. Commit access can be given to other developers by request on the bioc-devel mailing list. Another option is to add collaborators to the github repository. This approach enables development by many but restricts push access to git.bioconductor.org.
```

http://bioconductor.org/developers/package-guidelines/#description

You can have multiple authors as collaborators though. 

Please make the change needed in the DESCRIPTION file.

**Comment by nturaga** [comment]
# Review

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## NEWS

* Make sure you can parse your NEWS file with `utils::news`

	http://bioconductor.org/developers/package-guidelines/#news

## Tests

* ok

## R

* Nicely done! Well written code. 

* Try line wrapping certain functions to avoid the 80 chars per line
  NOTE on the build machine.

## vignette

* Good!

## man

* Why is there a `figures` subdirectory in the `man/` directory?

**Comment by lcolladotor** [comment]
Hi,

Regarding `man/figures` that's because `pkgdown` and `usethis::use_logo()` default to that location for saving the `man/figures/logo.png` file https://usethis.r-lib.org/reference/use_logo.html. I suggested to Carmina, Joselyn and Emiliano that they make a package sticker/logo. 

Best,
Leo

**Comment by lcolladotor** [comment]
@CarBarJon @jemilianosf @josschavezf 

Regarding the note by Nitesh about `news.md` https://github.com/ComunidadBioInfo/regutools/blob/master/NEWS.md I think that if you make it look like https://github.com/leekgroup/recount/blob/master/NEWS.md then it would be ok.

As for the line-wrapping, I think that we've used RStudio's reindent lines utilities. But well, it doesn't guarantee the 80 chars per line. I think that there are only a few lines left to fix manually if you can do that.

<img width="493" alt="Screen Shot 2020-04-02 at 12 42 37 PM" src="https://user-images.githubusercontent.com/2288213/78275309-718fcd00-74df-11ea-93f4-c5d6fc816588.png">


Best,
Leo

**Comment by nturaga** [comment]
Hi, 

I'm satisfied with the changes made. If you do a version bump and the build report is clean, I can accept the package.

**Comment by mtmorgan** [comment]
Using the 'AnnotationData' biocViews term means that this would be classified as an 'annotation' package, but it's clearly a software package that allows access to a particular type of annotation data. 

Please update the biocViews terms to be strictly from the '[Software][]' hierarchy.

[Software]: https://bioconductor.org/packages/release/BiocViews.html#___Software

**Comment by josschavezf** [comment]
Hi @nturaga,

During the last 2 bumps, we are getting this warning 'WARNING: R CMD check exceeded 10 min requirement.' but I am not sure how to solve it. Could you please help us to understand the error or have any suggestions?

**Comment by nturaga** [comment]
Can you try a version bump to see if it happens again?

**Comment by josschavezf** [comment]
Hi @nturaga,

I bumped version but now a different error has appeared:

* Checking package NEWS...
Error in file.path(srcdir, pkg, c("inst", "inst", "inst", ".", "."), c("NEWS.Rd",  : 
  object 'srcdir' not found

But I have not moved any file, news file is located at ./NEWS.md as before.

**Comment by lshep** [comment]
The NEWS file ERROR is on our end.  Very sorry for the confusion.  I have a fix on the linux builder and windows should be cleared up by this afternooon.  I'll kick off a manual build now so you should at least have an accurate linux build.

**Comment by nturaga** [comment]
@josschavezf 

Some pointers about the time the package takes to complete the R CMD check,

*  It takes a significantly long time to load the package with a `library(regutools)` call. And when it does load, 124 packages are loaded. (124 is a big number for one package)

```
> system.time(library(regutools))
   user  system elapsed
 10.808   0.527  11.411
```

* This big file `'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'` keeps getting downloaded multiple times during the R CMD check. It's 37MB (approx), but use BiocFileCache or something to cache the downloaded file the first time it happens. Because it is downloaded for the vignette and the test cases too.

It also gives out this warning,

```
Warning message:
call dbDisconnect() when finished working with a connection
```

* It might help to profile your code with `Rprof` to see which functions are taking the longest.

**Comment by mtmorgan** [comment]
Ideally regulondb_v10.6.2_DM_sqlite3 should be placed in [ExperimentHub](https://bioconductor.org/packages/devel/ExperimentHub), which will manage file cache for you. This would not be feasible if the file requires frequent update, but even then the record to the metadata for the file could be placed in ExperimentHub, with the resource hosted in a location that could be conveniently updated.

**Comment by lcolladotor** [comment]
Hi,

I didn't think about the download part being the problem, but it makes total sense.

`regutools` is designed to have the SQL data at `AnnotationHub`, it's just that https://github.com/ComunidadBioInfo/regutools/blob/master/R/connect_database.R has a fall-back mechanism that downloads the data from Dropbox if the data is not available from `AnnnotationHub` (if you think that `ExperimentHub` is better, we'll make that small switch). It seems to me that at this point then it would be best to get the data uploaded at `AnnotationHub` so the code will work with a cache. 

I could also add `BiocFileCache` as a dependency and use it for the fall-back mechanism in `connect_database()` (aka, the files from Dropbox). I guess that after all, `BiocFileCache` is already an indirect dependency by depending on `AnnotationHub` (importing in strict terms).

This is something I helped them with since I had done something similar for `GenomicState` in 2019 (and now I'm doing the same for `spatialLIBD`).

Best,
Leo

**Comment by lcolladotor** [comment]
Hi again,

In https://github.com/ComunidadBioInfo/regutools/commit/c50700a1d8b461eedae6659342a13665127cf8a7 I now use `BiocFileCache` to cache the data when it's not available from `AnnotationHub`. I still think that it would be great to add the data to `AnnotationHub`. I believe that `regutools` has everything already setup for that, we'd just need the AWS info to do so from Lori I think @lshep.

We'll see in a few minutes what the SPB and the GHA reports say.

I'll explain these changes to the `regutools` team on our meeting this Thursday.

Best,
Leo

**Comment by lcolladotor** [comment]
Looks like the SPB caught some packages being updated 2/3 times it ran today (as in http://bioconductor.org/spb_reports/regutools_buildreport_20200421190543.html and http://bioconductor.org/spb_reports/regutools_buildreport_20200421195343.html) but it did work at http://bioconductor.org/spb_reports/regutools_buildreport_20200421192618.html. I'll submit a bump version later tonight just to double check things.

Best,
Leo

**Comment by lcolladotor** [comment]
Ok, nothing really changed in https://github.com/ComunidadBioInfo/regutools/commit/6551e7521cdb6e8e2906190cdb39d1671096cb66 except a bump in version number, so it really was some transient issue on the SPB. Anyway, it's all green now =)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/josschavezf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("regutools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/regutools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
