### ISSUE TITLE
Dune

### ISSUE THREAD

**Issue by HectorRDB** [Bioconductor/Contributions#1400]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HectorRDB/Dune

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I realize that this package provides functionality relevant to bioinformatics, but since it doesn't use or interoperate with other Bioconductor packages maybe it is better suited to CRAN?

**Comment by HectorRDB** [comment]
Hi @mtmorgan, 
Thanks for the quick reply. This was one of my concerns while developing the package but the clustering algorithms in Bioconductor (even when restricting to single-cell RNA Seq) do not output consistent results. For example, `sc3` or `scran` modifies the `colData` slot of a `SingleCellExperiment` object, while `monocle` changes the `pData` of the `cellDataSet` object and `mbkmeans` returns a list containing a `cluster` object. I opted for a generic input so that it would be a more flexible function.
Do you have any suggestions? My sole idea was to add a `SingleCellExperiment` method that would requires the user to specify which columns of `colData` should be selected but even this would lower compatibility.

**Comment by HectorRDB** [comment]
HI @mtmorgan,
I have changed the main function of the package. It is now an S4 method with 3 possible inputs: `matrix`, `data.frame` and `SummarizedExperiment`.

**Comment by HectorRDB** [comment]
Hi,
The package passed without errors and warnings. 
To remove the __TIMEOUT__ label, I had to add a `parallel` argument to the main function so that the function only used `BiocParallel` when needed. This removed the __TIMEOUT__ on windows but it is not very elegant. Do you have any recommandation on how to do this?

**Comment by HectorRDB** [comment]
Hi @dvantwisk 
I was just wondering what the next steps were for the package. It builds without warnings or errors. I fully understand that those are complex times and that you may have other priorities right now but I just wanted to make sure it was not something on my end.
Best,

**Comment by dvantwisk** [comment]
I apologize for the delay on my end. We are approaching our package deadline and things start to get hectic this time of the year. I've reviewed your package and it looks very well written. I only have a few small issues that need to be addressed. Please message me back when you are finished making changes.

R/data.R
- [ ] [REQUIRED] Provide the source of the data in the documentation
for user facing data.

vignettes/Dune.Rmd
- [ ] [REQUIRED] L17-22: Since your package will be accepted to
Bioconductor, it should be installed via `BiocManager::install()` instead of
`devtools::git_install()`.
```
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
BiocManager::install("Dune")
```

**Comment by HectorRDB** [comment]
Hi @dvantwisk 
Thank you very much for taking the time. I have now addressed the two issues.
Let me know if anything else needs to be done.
Best,

**Comment by dvantwisk** [comment]
I've reviewed your changes and they look fine. I am going to move to accepe the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HectorRDB.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Dune")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Dune

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
