### ISSUE TITLE
RegEnrich

### ISSUE THREAD

**Issue by WTaoUMC** [Bioconductor/Contributions#1410]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/WTaoUMC/RegEnrich

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I see that you have opened four issues for the same package. Can you clarify what your intention is? If you have a preferred github account we should just use the issue associated with that...

**Comment by WTaoUMC** [comment]
Dear Martin,


Sorry for confusion. I closed my first submission by accident. Then I tried to resubmit my package, but it failed. So I registered a new account to submit and finally succeded.


The last submission (WTaoUMC/RegEnrich) is the right one.


Sorry again for bringing any inconvenience.


Best,

Weiyang

________________________________

**Comment by lshep** [comment]
Please fix the ERRORS in the build report.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Before I go into a indepth review of your code I have some major concerns based on running through your vignette.  Please see the minimal review and comments: 


**Build Report**
- [ ] Check use of dontrun/donttest.  All dontrun should be donttest, as donttest requires valid R code.  All exported functions need to be run once either in man pages or vignette. 


**DESCRIPTION**

- [ ] Please remove `lazyData: true` we have rarely found useful and can actually slow package installation

**NEWS**

- [ ] Not formatted correctly. Please see `?news`

**vignette**

- [ ] We prefer vignettes to use BiocStyle for formatting.

- [ ] Looking at the argumnets to RegenrishSet object in the section 2.2, I
  wonder why you are not extending SummarizedExperiment. Your class should
  minimally extend this object and your class constructor should optionally
  take in a SummarizedExperiment object  since it consists of an expression
  matrix, sample info, and genomic region information and is the basic
  Bioconductor class used for such data. 
  Same with DEASet object. Why are you not extending the highly used and
  developed classes? This also seems like it should extend a
  summarizedExpeirment
  Same with TopNetwork object. There are classes like GeneSet and
  GeneSetCollection and BiocSet? 
  Since you use a bunch of different data.frames you might also look at
  MultiAssayExperiment.  
  
- [ ] In your case study for example you grab a classic eset object (which is
  the predecessor to SummarizedExperiment), again instead of deconstructing the eset,
  it would be better for your function to take in an eset and
  SummarizedExperiment and parse it accordingly into your object or extend it out.  Reorganizing
  your class to extend the Biconductor classes will have some benefits like
  1. be more intuitive to already established Biconductor users that are already
  familiar with the standard Bioconductor class. 2. you get all the functions
  that are already defined for the extended class out of the box. 

- [ ] You seem to using functions from a bunch of different packages? What functions/algorihms/improvements are uniquely new besides have new classes simply for organization? 

Thank you.

**Comment by lshep** [comment]
Could you please respond to the above initial review?

**Comment by WTaoUMC** [comment]
Thank you for your comments and sorry for late response, we have been managing to implement RegEnrich with the Bioconductor standard classes as you suggested. 

We found the classes like SummarizedExperiment and GeneSet might be doable, but MultiAssayExperiment wouldn't be feasible as RegEnrich currently works on data in one experiment.

We do implement the RegEnrich using multiple packages, as RegEnrich is a pipeline (differential analysis, network inference, enrichment, and ranking), by which we analysed our transcriptomic data and found a network of gene regulators (we also experimentally validated) important in regulating dendritic cell phenotypes by a chemokine (CXCL4). So we would like to make it publicly available and standardise and be managed by Bioconductor. Although RegEnrich is uses multiple packages, we have also improved the speed of network inference of the random forest method, with a controllability of accurate model selection. 

We will manage to address the problems you listed above and will reply it one-by-one soon. 

Thank you.

**Comment by lshep** [comment]
Please remember the package must be re-reviewed and accepted by April 22 to be included in the 3.11 release. Else it will remain in devel until the Fall release of bioc 3.12

**Comment by WTaoUMC** [comment]
Dear Lori,
 
Thank you for your comments and your suggestions. We have committed changes to RegEnrich (Version 0.99.14) on GitHub according to your suggesions. We do believe you suggestions have improved RegEnrich quite a lot in terms of readability, layout and standardization.
 
Here are our reply to your comments point by point:
·          Check use of dontrun/donttest. All dontrun should be donttest, as donttest requires valid R code. All exported functions need to be run once either in man pages or vignette.

Response: We have replace all “dontrun” tags by “donttest” in all examples.

·          Please remove lazyData: true we have rarely found useful and can actually slow package installation

Response: We have removed lazyData: true  from DESCRIPTION file.

·          Not formatted correctly. Please see ?news

Response: We have replaced NEWS file by NEWS.md file, which is formatted as required.

·          We prefer vignettes to use BiocStyle for formatting.

Response: We have updated the vignettes (RegEnrich.Rmd file) by using BiocStyle for formatting.

·          Looking at the argumnets to RegenrishSet object in the section 2.2, I
wonder why you are not extending SummarizedExperiment. Your class should
minimally extend this object and your class constructor should optionally
take in a SummarizedExperiment object since it consists of an expression
matrix, sample info, and genomic region information and is the basic
Bioconductor class used for such data.
Same with DEASet object. Why are you not extending the highly used and
developed classes? This also seems like it should extend a
summarizedExpeirment
Same with TopNetwork object. There are classes like GeneSet and
GeneSetCollection and BiocSet?
Since you use a bunch of different data.frames you might also look at
MultiAssayExperiment.

Response: Thanks, the RegenrichSet class is now implemented by inheriting DeaSet class, which inherits SummarizedExperiment class. So the accessor functions of SummarizedExperiment class can be applied to RegenrichSet and DeaSet classes. With respect to TopNetwork class, we decide to inherit the BiocSet class as this format is more applicable than GeneSet and GeneSetCollection to our case. The MultiAssayExperiment class does not fit our goal, so we don’t consider it.

·          In your case study for example you grab a classic eset object (which is
the predecessor to SummarizedExperiment), again instead of deconstructing the eset,
it would be better for your function to take in an eset and
SummarizedExperiment and parse it accordingly into your object or extend it out. Reorganizing
your class to extend the Biconductor classes will have some benefits like
                 i.        be more intuitive to already established Biconductor users that are already
familiar with the standard Bioconductor class. 2. you get all the functions
that are already defined for the extended class out of the box.

Response: Now the RegenrichSet class is reorganized according to your suggesion, see previous response.

·         You seem to using functions from a bunch of different packages? What functions/algorihms/improvements are uniquely new besides have new classes simply for organization?

Response: RegEnrich is a pipeline package to perform regulator enrichment analysis, which consists of four major steps: differential analysis, network inference, enrichment analysis, and regulator ranking. In each step we provide users with options to use the succesful methods, for example DESeq2 for differential expression analysis, random forest for network inference (inspired by GENIE3 package), and Fisher’s exact test for enrichment analysis. Although these packages are already available, the RegEnrich is the first package to combine these (by ranking the regulatory genes) to identify the key gene regulators. Besides, RegEnrich improves GENIE3 by supporting parallel computing and pre-defining features and controllability of accurate model selection. More importantly, using RegEnrich pipeline we analysed transcriptomic data in our previous study and found a network of gene regulators, which is also experimentally validated, important to regulating dendritic cell phenotypes upon a chemokine (CXCL4) stimulation. So we would like to make it publicly available and be managed by Bioconductor.
 
Best wishes,
Weiyang Tao

**Comment by lshep** [comment]
Thank you.  The package is looking much better.  

May I ask why a user cannot input a SummarizedExperiment into the functions as well?

**Comment by WTaoUMC** [comment]
Thank you. 

One of the major reasons is that we cannot make sure the column names of sample information in the SummarizedExperiment or ExperimentSet object do not contain any characters like "-", ",", ":" etc. These characters are illegal in each term of the formula object (the terms of formula indicate the columns of sample information), which is defined by 'design' and 'reduced' parameters. So users still need to manually change the column names of sample information even though such an "object converting" function has been provided. 

In addition, the row (gene) names of SummarizedExperiment or ExperimentSet object are also not ensured to be of the same type as the regulators (for example Ensembl ID). 

You may notice that in the vignette, the data preprocessing are majorly for sample information and gene names. If a SummarizedExperiment object with a clean sample information (no invalid characters) and valid gene names is provided, then with the current "RegenrichSet" function, only 'expr', 'colData', and 'rowData' parameters need to be extracted.

Since the users still need to check these information, it is similar in terms of amount of work, but safer, to extract the expression matrix and sample information followed by RegenrichSet creator function.

Is it mandatory to include such a function?

If you highly recommend it, we can change the current RegenrichSet function to an S4 generic and include 4 different S4 methods (for matrix, data.frame, SummarizedExperiment, and ExperimentSet) to create RegenrichSet object.

Best,
Weiyang

**Comment by lshep** [comment]
It is recommended but not mandatory.  Realizing that it is a lot of extra work for possibly minimal gain we can ignore this for now.  Thank you for the justification though it helps.
I will continue with the review and post any additional comments in the next few days

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/WTaoUMC.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RegEnrich")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RegEnrich

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
