### ISSUE TITLE
scHOT

### ISSUE THREAD

**Issue by shazanfar** [Bioconductor/Contributions#1412]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shazanfar/scHOT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
DESCRIPTION

- Please provide a more abstract-like Description of the functionality provided by this package.

vignettes

- good!

R -- representative comments; please review all code for similar issues

- `if (!"DataFrame" %in% methods::is(cellData)) {` is usually writen `!is(cellData, "DataFrmae")`.

- it's usually better, even for use stictly within the package, to define 'accessors' for slot access, e.g., 
  ```
  `positionType<-` = function(x, value) {
      x@positionType <- value
      x
   }
   ```
  but actually it seems like you want a constructor along the lines of 
  
  ```
  .scHOT <- setClass("scHOT", ...)
  ```
  and then create the complete object in one go
  ```
  sce <- SingleCellExperiment(<args>)
  .scHOT(sce, ..., positionType = ..., positionColData = ..., ...)
  ```
  
- e.g., build.R:230 avoid iteration (`n` calls to R functions) in favor of vectorization (1 call to an R function), e.g.,
  ```
  for (j in seq_len(n)) {
      W[i, j] <- 1/(1 + abs(i - j))
  }
  ```
  with `n` calls to `abs()` is
  ```
  j <- seq_len(n)
  W[i, j] <- 1 / (1 + abs(i - j))
  ```
  with 1 call to `abs()`.
  
- build.R:291 `message(paste(...))` is usually just `message(...)`.

man

- good.

**Comment by lshep** [comment]
The NEWS file ERROR is on our end.  We have a fix implemented in linux and there will be a fix on windows by later this afternoon.  I will kick off a manual build so there is at least an accurate linux build.  it should post shortly.

**Comment by shazanfar** [comment]
Thanks for clarifying Lori! I'll hold off on bumping version until later on then.

Re the other error, below, am I right in understanding that this is resolved by not including the `@export` flag for `.scHOT()`?

```
* Checking if other packages can import this one...
    * ERROR: Packages providing 1 object(s) used in this package should
      be imported in the NAMESPACE file, otherwise packages importing
      this package may fail.
    
      package::object in function()
        methods::new in .scHOT()
```

Thanks!

Cheers,
Shila

**Comment by shazanfar** [comment]
Hi Martin @mtmorgan,

Thanks for your constructive feedback on the package! I've endeavoured to make all improvements you've mentioned, in all relevant contexts and not just the representative examples. Please let me know if there are any remaining or further issues I should address.

Summary of changes:

- replaced instances of `if (!"DataFrame" %in% methods::is(cellData)) {` with `!is(cellData, "DataFrame")` and similar

- defined slot accessor functions and used them throughout the package

- replaced separate building of scHOT object and populating with slots in favour of a single complete constructor

- replaced multiple iterative calls to R functions in favour of vectorisation

- removed `paste0(...)` from within `message(...)`, `warning(...)` and `stop(...)`

Thanks again!

Cheers,
Shila

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shazanfar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scHOT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scHOT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
