### ISSUE TITLE
BrainSABER

### ISSUE THREAD

**Issue by bicbioeng1** [Bioconductor/Contributions#1413]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bicbioeng/BrainSABER

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# Review

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* The description of the package should be like a paper abstract.

## NAMESPACE

* ok

## NEWS

* Make sure news can be parsed by utils::news()

## R

* For logical operators, `if(mini == TRUE){` can be replaced by
  `if(mini)`. R knows that you are checking ig it is true.
  
* Consider validity checks for your function arguments, i.e 

	```
	if(!is.logical(mini))
		stop("argument should be logical')
	```

  You should do this across the board, for all functions and
  arguments, not just a few. You do a pretty good job of it for the
  most part.

## test cases

* Please consider adding unit tests. `testthat` provides a good
  option.


## vignette

* consider using BiocStyle https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html

* I'm experiencing an error while building the vignette, please take a
  look, although the build system is not seeing this issue. But i'd
  like to get to the bottom of it and understand why this issue is
  happening.

```
   Quitting from lines 194-217 (Installing_and_Using_BrainSABER.Rmd) 
   Error: processing vignette 'Installing_and_Using_BrainSABER.Rmd' failed with diagnostics:
   subscript out of bounds
   --- failed re-building ‘Installing_and_Using_BrainSABER.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘Installing_and_Using_BrainSABER.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 194-217 (Installing_and_Using_BrainSABER.Rmd) 
E> Error: processing vignette 'Installing_and_Using_BrainSABER.Rmd' failed with diagnostics:
E> subscript out of bounds
E> --- failed re-building ‘Installing_and_Using_BrainSABER.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘Installing_and_Using_BrainSABER.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted
```

## man

* ok

**Comment by bicbioeng1** [comment]
Dear Nitesh,

Thank you for taking the time to look at our package, we appreciate the
feedback! I'm not sure why there's an issue with the vignette, I'll look
into it. Perhaps it has to do with updates to some packages in the last 3
weeks after we submitted it? Will get back to you soon!

Best,
Evgeni

**Comment by bicbioeng1** [comment]
Apologies for the delay. Here's a list of updates to BrainSABER and the
comments they correspond to:

   - The description of the package should be like a paper abstract

*Changed the description to be more detailed, like a brief abstract.*

   - *Make sure news can be parsed by utils::news() *

*Checked formatting for NEWS file and didn't find any errors. Not sure why
it's not being parsed...*

   - For logical operators, if(mini == TRUE){ can be replaced by if(mini).
   R knows that you are checking ig it is true.
   - Consider validity checks for your function arguments, i.e
   - if(!is.logical(mini))
   - stop("argument should be logical')
   - You should do this across the board, for all functions and arguments,
   not just a few. You do a pretty good job of it for the most part.

*Added appropriate validity-checking for function arguments.*

   - *consider using
   BiocStyle https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html
   <https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html> *

*We've already integrated BiocStyle into our vignette and DESCRIPTION
according to the BiocStyle vignette, so I'm not sure what's missing
there...*

   -


*I'm experiencing an error while building the vignette, please take a look,
   although the build system is not seeing this issue. But i'd like to get to
   the bottom of it and understand why this issue is happening. *

*Could not replicate this error in my Windows 10, x64 system under the
developmental versions of R and Bioconductor. Do you have any info under
what conditions the vignette was built?*

Thanks again!

**Comment by lshep** [comment]
Please fix the ERROR in the report before a re-review will occur

**Comment by mtmorgan** [comment]
Instead of downloading a file each time (e.g., https://github.com/bicbioeng/BrainSABER/blob/7c3ea651d82c5b28aae282879aea1a6bd1e98a00/R/buildAIBSARNA.R#L60), use [BiocFileCache][] to download once or when the file is updated.

[BiocFileCache]: http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource

**Comment by bicbioeng1** [comment]
Thank you for the suggestion! That will definitely help speed up the
workflow.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bicbioeng1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BrainSABER")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BrainSABER

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
