### ISSUE TITLE
eisaR

### ISSUE THREAD

**Issue by mbstadler** [Bioconductor/Contributions#1417]
- Repository: https://github.com/fmicompbio/eisaR

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

Remark: This is currently the case, except for an issue where the checker fails
to correctly interpret non-standard code evaluation, as in
`BiocGenerics::subset(x, type = "exon")`, where the checks fail due to
a "missing" variable type.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

**Thank you!**

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Michael, @mbstadler 

Thank you for your submission to Bioconductor.
I have taken a look at your package. 
It was a pretty straightforward review as most items are
in order and well done.

Please see the short review below.

Best regards,
Marcel

---

# eisaR #1417

## DESCRIPTION

* It looks good.
* Add a `BugReports` field for filing issues

## NAMESPACE

* It looks good. Not too extensive :+1:

## vignettes

* It is customary to provide an installation section in one of the vignettes.
* Formatting looks good and is easy-to-read (Auth: MS).
* For readability, it is recommended to limit text with to 80 columns (Auth: CS)
* Content looks short and easy-to-read (Auth: CS)
* Remove the `eisaR.R` file from the vignettes folder

## R

* It looks properly formatted.
* Good to go.

## /

* OK

**Comment by mbstadler** [comment]
Hi Marcel, @LiNk-NY 

Thank you for the review and the feedback.

We have implemented your suggestions, specifically:
- added URL and BugReports fields in `DESCRIPTION`
- install section in `eisaR` vignette
- shorter lines in `rna-velocity` vignette
- remvoved `eisaR.R` from vignette folder
- bumped version to trigger a new built

Best regards,
Michael and Charlotte

**Comment by LiNk-NY** [comment]
Hi Michael and Charlotte, @mbstadler and @csoneson

Thank you for making those changes. Your package has been accepted. 
Note. Remove the `version="devel"` option in the installation section for
when the package is released. 

Best,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mbstadler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("eisaR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/eisaR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
