### ISSUE TITLE
MoonlightR

### ISSUE THREAD

**Issue by torongs82** [Bioconductor/Contributions#142]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ibsquare/MoonlightR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,
I'd like to start this review but want Single Package Builder results for the most current commit. In your last commit you didn't bump the version ... did you  mean to?
Valerie

**Comment by vobencha** [comment]
Hi,

I"ve done a first review of MoonlightR. Please see comments and suggestions below.

(1) Description in DESCRIPTION

This statement is not free-standing:

Description: We developed an R/Bioconductor package called Moonlight to address these challenges and offer solutions by using a guided workflow
             to allow users to perform functional enrichment analysis (FEA) and upstream regulator analysis (URA).

What are the challenges? It makes sense if you read the Title first but probably a good idea to include what challenges you're addressing in 'Description'.

(2) RISmed

RISmed is mentioned in NAMESPACE but not in DESCRIPTION. Do you need it?

importFrom(RISmed,EUtilsGet)
importFrom(RISmed,EUtilsSummary)

(3) vignette

i) installation section

Please remove the commented out lines and just suggest using biocLite().

#library(devtools)
#install_github("torongs82/Moonlight/tree/master/MoonlightR")
source("https://bioconductor.org/biocLite.R")
biocLite("MoonlightR")

ii) You only need to load the package once (library(MoonlightR) - this is usually at the top of the vignette in the setup section.

iii) eval=FALSE

There are many unevaluated vignette chunks. A few would be ok but this almost half. The Single Package Builder output reports 41% unevaluated:

* This is a software package, checking vignette directories...
      # of chunks: 34, # of eval=FALSE: 14 (41%)

Please either evaluate more chunks ,or it time is an issue, consolidate calls (e.g, one call to each function vs multiple calls etc.).

~/proj/git/software/test/MoonlightR/vignettes >grep FALSE *
Moonlight.Rmd:```{r setup, include=FALSE}
Moonlight.Rmd:knitr::opts_chunk$set(cache=FALSE)
Moonlight.Rmd:```{r, echo = FALSE,hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, eval = TRUE, echo = TRUE, results='hide', warning = FALSE, message = FALSE}
Moonlight.Rmd:```{r, eval = TRUE, echo = TRUE, results='hide', warning = FALSE, message = FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, eval = FALSE, echo = TRUE, hide=TRUE, results='hide', warning = FALSE, message = FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, eval = FALSE, echo = TRUE, results='hide'}
Moonlight.Rmd:```{r, eval = TRUE, echo = TRUE, message=FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, eval = TRUE, echo = TRUE, results='hide', warning = FALSE, message = FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r,eval=FALSE,echo=TRUE,message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, eval = FALSE, echo = TRUE, results='hide', warning = FALSE, message = FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r,eval=FALSE,echo=TRUE,message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, eval = FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r,eval=FALSE,echo=TRUE,message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r,eval=FALSE,echo=TRUE,message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, fig.width=6, fig.height=4, echo = FALSE, fig.align="center",hide=TRUE, message=FALSE,warning=FALSE}
Moonlight.Rmd:```{r, eval = FALSE, echo = FALSE}
Moonlight.Rmd:```{r, eval = TRUE, echo = FALSE}

(4) Problems in R CMD  check

Please fix these:

* checking R code for possible problems ... NOTE
DPA: no visible binding for global variable 'G1'
DPA: no visible binding for global variable 'G0'
FEA: no visible binding for global variable 'DiseaseList'
FEA: no visible global function definition for 'txtProgressBar'
FEA: no visible global function definition for 'setTxtProgressBar'
PRA: no visible binding for global variable 'tabGrowBlock'
PRA: no visible binding for global variable 'knownDriverGenes'
Roma: no visible global function definition for 'write.table'
Roma: no visible global function definition for 'read.table'
URA: no visible binding for global variable 'DiseaseList'
URA: no visible global function definition for 'txtProgressBar'
get.data.GEO: no visible binding for global variable 'GEO_TCGAtab'
get.data.TCGA: no visible global function definition for 'as.roman'
get.data.TCGA: no visible binding for global variable 'data'
get.data.TCGA: possible error in TCGAanalyze_Preprocessing(object =
  RSEobject, cor.cut = cor.cut, datatype = "raw_count"): unused
  argument (datatype = "raw_count")
get.data.TCGA: no visible binding for global variable 'geneInfo'
plotNetworkHive: no visible global function definition for 'adj2HPD'
plotNetworkHive: no visible global function definition for 'gpar'
Undefined global functions or variables:
  DiseaseList G0 G1 GEO_TCGAtab adj2HPD as.roman data geneInfo gpar
  knownDriverGenes read.table setTxtProgressBar tabGrowBlock
  txtProgressBar write.table
Consider adding
  importFrom("utils", "as.roman", "data", "read.table",
             "setTxtProgressBar", "txtProgressBar", "write.table")
to your NAMESPACE file.

* Checking if other packages can import this one...
    * ERROR: Packages (HiveR) which provide adj2HPD (used in NA) should
      be imported in the NAMESPACE file, otherwise packages that import
      MoonlightR could fail.

* Checking to see if we understand object initialization....
    * NOTE: Clarifying how objects 'G1, G0, DiseaseList,
      txtProgressBar, setTxtProgressBar, GEO_TCGAtab, as.roman, data,
      geneInfo, gpar, tabGrowBlock, knownDriverGenes, write.table,
      read.table, DiseaseList, txtProgressBar' (used in DPA, FEA,
      get.data.GEO, get.data.TCGA, plotNetworkHive, PRA, Roma, URA, NA,
      NA, NA, NA, NA, NA, NA, NA) were initialized. Maybe they are part
      of a data set loaded with data(), or perhaps part of an object
      referenced in with() or within().

* Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages:
      PEA.Rd

* Checking exported objects have runnable examples...
    * NOTE: Adding runnable examples to the following man pages which
      document exported objects:
      PEA.Rd

(5) get.data.TCGA man page

The example uses a DPA() function instead of get.data.TCGA() ... ?

(6) get.data.GEO man page

Example uses DPA() instead of get.data.GE0(). Why? Please modify all man pages to use the function they document.

(7) function names

The dot '.' is used is S3 method dispatch so if you're functions aren't S3 methods it can be confusing to new users. Please rename the functions to use camelCase or underscores.

Let me know if you have questions.

Valerie

**Comment by torongs82** [comment]
Dear Valerie,

thank you for your review. We are having small troubles to understand the timeline outlined here https://www.bioconductor.org/developers/release-schedule/ 
Could you let us know until we need to address the issues you raised in order to be accepted for the October release of Bioconductor? Thanks for your help!! 

Best,
Antonio

**Comment by vobencha** [comment]
We need to have the review finished by next Wednesday (Oct 12) to get it in the next release.
Valerie

**Comment by vobencha** [comment]
@torongs82 are you planning to submit a new version today? It's ok if you don't; if we don't make tomorrow's deadline the package will be available in devel only until the spring release at which time it becomes available in both release and devel.

**Comment by torongs82** [comment]
Dear Valerie @vobencha ,

thank you for your reviews and suggestions. 
We worked trying to address your seven points emerged. In particular we kept only those section at eval=FALSE that require data download.

I hope that MoonlightR will be in the next release, if you need further fixing or have any feedbacks I am here.

Thank you.

Best,
Antonio

**Comment by vobencha** [comment]
@torongs82 it looks like we have an error in the vignette ...

**Comment by torongs82** [comment]
@vobencha thank you I saw the error in the vignette.
We committed a fix, but now we have a small issues with examples related only with Windows machine maybe related on file writing permissions, we are ironing out a solution.
If you have any ideas or suggestions...
Best,
Antonio.

**Comment by vobencha** [comment]
@torongs82 I've seen that error in relation to doParallel not closing out a cluster. You could try using stopImplicitCluster() in the vignette or man pages.

**Comment by torongs82** [comment]
Dear @vobencha we followed your suggestion and added some fixes related on file output writing.
Now the package built without errors or warnings.
If you need anything else you can write me.
PS. @colsen thank you a lot for your great contribution.

**Comment by vobencha** [comment]
Yes, we are good to go - the package is approved. You'll receive an email from Martin in the next week with svn credentials and next steps.

Thanks for contributing your work to Bioconductor.
Valerie

**Comment by torongs82** [comment]
Thank you @vobencha accepting our package. 

Waiting for next steps.
Best,
Antonio.
