### ISSUE TITLE
SCATE

### ISSUE THREAD

**Issue by Winnie09** [Bioconductor/Contributions#1420]
- Repository: https://github.com/Winnie09/SCATE.git

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Winnie09** [comment]
Thank you so much @bioc-issue-bot! I am so sorry that the vignette generation runs for too long! I have addressed the "timeout" issue now. Please proceed. Thank you!

**Comment by lshep** [comment]
Please see the following for setting up a webhook https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

You should bump the version in the DESCRIPTION to trigger a new build.

**Comment by Winnie09** [comment]
Thank you! I have set the webhook. And the version is now set to be 0.2.2.
Would this be OK?

**Comment by Winnie09** [comment]
Updated. Please proceed. Thank you!

**Comment by Winnie09** [comment]
Hi, I am a bit confused why 1h ago you sent message saying the package built without errors or warnings on all platforms, and then 30min ago you sent another message saying there are Errors...I noticed this ERROR from the report, and I think maybe it is because the windows parallel issue?May I know more information about your Windows machine, for example, how many cores do you have in windows machine?  Please advise. Thank you!
** running examples for arch 'i386' ... ERROR
TIMEOUT: R CMD check exceeded 25 mins

**Comment by Winnie09** [comment]
Hi, could you proceed with the review please? Thank you!

**Comment by Winnie09** [comment]
Hi, could you proceed with the review please? Thank you!

**Comment by mtmorgan** [comment]
@dvantwisk is your reviewer. There's a build in response to every push with version bump, so I guess you made two commits yesterday? You should assume minimal parallelism, max 2 cores, for the builders, because this is a shared resource.

**Comment by Winnie09** [comment]
Thank you, @mtmorgan, @dvantwisk ! I have three questions:
1. Should I put files 'SCATE.Rnw', 'SCATE.pdf' in the folder 'inst/doc' or not?
I have been doing or not doing it back and forth but in either way, there will be a warning in an evaluation.
2. Since the algorithm requires whole-genome data, and the size is larger than the size limit (5M), I cannot put it inside the package but instead have to download the data when calling the function. I think that is the reason why TIMEOUT in the build. Since this data is by nature necessary for running the algorithm, I need it either inside the package or downloaded from URL. Would there be a way to avoid both size limit and TIME OUT problem?
3. It seems that I don't get the same build message when I call "R CMD CHECK" on my local machine. It takes multiple versions to know from the @bioc-issue-bot  report and modify the codes. How many versions can I bump at maximum and what happens after the maximum has been achieved?

**Comment by mtmorgan** [comment]
Just to keep the ball rolling...

1. no, you should not put anything in inst/doc. And in vignettes you should have only source -- the Rnw, not the pdf. The pdf is generated by the first command in the build and check process

```
R CMD build SCATE
```

3. be sure to use the current version of R-devel and Bioc-devel (`BiocManager::install(version="devel")`); if there are still problems see https://github.com/Bioconductor/Contributions#r-cmd-check-environment . 

2. The solution with large data is either (a) use a (much) smaller data set for illustrating and testing your package, or create a separate 'ExperimentHub' data resource and package to make your data available, as described in http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html (generally, https://bioconductor.org/packages/ExpermentHub)

**Comment by Winnie09** [comment]
Thank you @mtmorgan ! If I remove the files in inst/doc, I always get this warning while running R CMD CHECK:

* checking files in ‘vignettes’ ... WARNING
 Files in the 'vignettes' directory but no files in 'inst/doc':
 ‘SCATE.Rnw’

However, if I put the files back, I receive this warning while running R CMD BUILD:

* creating vignettes ... OK
Warning: 'inst/doc' files
    'SCATE.Rnw', 'SCATE.pdf'
  ignored as vignettes have been rebuilt.

This is so confusing to me.... Please advise. Thank you!

**Comment by mtmorgan** [comment]
```
checking files in ‘vignettes’ ... WARNING
Files in the 'vignettes' directory but no files in 'inst/doc':
‘SCATE.Rnw’
```
means the vignette is not being processed when the package is built -- remember to remove vignettes/SCATE.pdf and check the built package.
```
R CMD build SCATE
R CMD check SCATE_x.y.z.tar.gz
```
or similar.

**Comment by dvantwisk** [comment]
I apologize for the silence on my end. I've reviewed your package and can comment about the remaining issues you have on the builder.

You are receiving a TIMEOUT on check on the windows builder and an ERROR on check on the linux builder. These both occur in the documentation example for `SCATE.R`.
For the TIMEOUT on windows, the example is taking an excessive amount of time to run (since it will not run on multiple cores in this platform). You should consider making a very abbreviated example that, may not provide useful results, should run quickly.
The ERROR on the linux builder is occurring is because this builder can only support no more than 2 cores being requested, while the example specifies 8. You shouldn't include system specific code like this in an example because you can't be sure what the capabilities of the user's system is.

As for the review, [REQUIRED] tags involve making the change or giving an explanation on why the change cannot be made. [CONSIDER] tags describe changes that are advisable but not necessary. Please message me back when you have questions or are done making changes.

R/GENERAL
- [ ] [REQUIRED] Some functions require a `datapath` argument. The
documentation states that the user needs to download the data package
from http://jilab.biostat.jhsph.edu/projects/scate/hg19.zip. This is
problamatic since we cannot ensure that the user will be able to access that
link in the future. I ask that you please submit the data that you want the user
to download as an Experiment Data Package. The following page should help
you make one https://www.bioconductor.org/developers/package-guidelines/#data
- [ ] [REQUIRED] In addition, the repo is 318MB large, much of it due to data
in the `inst/extdata` directory. This data should be included in your
Experiment Data Package. Also, I ask that you remove these large files from
your version control history. We like to see repositories smaller than 5MB
in size. You can use this tool to remove these large files from version control
when you are able https://rtyley.github.io/bfg-repo-cleaner/

R/SCATE.R
- [ ] [CONSIDER] Use `match.arg()`. For example, at L27 where the argument
`type` is given, the argument can be written as `type=c('reads', 'peaks')`
since it has two possible character values. The default value is the first
item in the vector, `'reads'`. In the function, the value the user gave
can be obtained with `type <- match.arg(type)`. Doing things this way is
better because it explicitly states what values an argument can have in the
function declaration. Also, it will throw an error if the user provides an 
argument that is not specified. This can be done in multiple arguments
throughout the package.

- [ ] [REQUIRED] Use `message()` instead of `print()` when displaying
diagnostic messages to the user. This is desirable since the message can
be toggled off with `suppressMessages()`.

- [ ] [REQUIRED] Use `seq_len()` or `seq_along()` instead of `1:...`. This
is slightly more efficient and avoids the unexpected case where `1:0` is
`1 0`.

R/cellcluster.R
- [ ] [REQUIRED] L19: Do not use `set.seed()` within your package. If you
wish to have the user generate the same result as you for the vignette,
specify what seed to use at that section of the vignette.

R/extractfeature.R
- [ ] [REQUIRED] The documentation states a matrix will be returned by
`extractfeautre()`. If the `folder` argument is not NULL, it will save
the file and nothing will be returned. Please change it so that the table
the documentation says will be returned is returned in any case.

R/peakcall.R
- [ ] [REQUIRED] Same problem with `set.seed()` as before.

tests
- [ ] [CONSIDER] Add tests with the `testthat` package.

vignettes/SCATE.Rmd
- [ ] [REQUIRED] Your vignette contains some `eval=FALSE` tags. We want to 
see code exposed to the user run on our builder to verify that it functions
correctly. In some cases, `eval=FALSE`s can be acceptable, for example, if
the code opens an interactive prompt or the vignette deals with computations
that are too long (In this case we do ask that results of the calculations
are available to the user in between code sections). Can you explain the
reason for `eval=FALSE`s here?

**Comment by dvantwisk** [comment]
Hello,

I just want to check in with the progress of your package submission. I need to remind you that the deadline for your package to be included in the next Bioconductor release is April 21st.

**Comment by dvantwisk** [comment]
Hello,

I just want to check in with the progress of your package submission. I need to send you another reminder that the deadline for your package to be included in the next Bioconductor release is April 21st. The package will need to be accepted by then to be included in the next release. Please message me back if you have any issues making the changes I specified.

**Comment by dvantwisk** [comment]
I do need to remind you that the final day to accept packages for the upcoming Bioconductor release is April 22nd. Please message me if you have any other questions.

**Comment by Winnie09** [comment]
Sorry, something unexpected came up so I did not access emails or work on
this package for a couple of days. Is it possible to extend the deadline?

**Comment by lshep** [comment]
We can not guarantee after the 22nd inclusion in 3.11.  If the package does not make the deadline for the 3.11 release it can still be accepted into Bioconductor and be released under 3.12 in the fall.  It will still build and be findable on Bioconductor regardless.  Please work on your updates as soon as possible.

**Comment by lshep** [comment]
We are closing your issue since it has been inactive with no updates since March.  When you are ready to actively work through the submission project please request the issue be reopened.

**Comment by Winnie09** [comment]
Hi @mtmorgan @dvantwisk @lshep . I would like to submit an `ExperimentHub` data package of inst/extdata data as a companion of the SCATE package, as @mtmorgan suggested.  I checked the `ExperimentHub` website and the website tells that I need to notify the `Bioconductor` team first.  Am I correct notifying you about this?

**Comment by lshep** [comment]
Yes thank you for notification.   Could you please email me at lori.shepherd@roswellpark.org so I can give you credentials to upload your data to S3?  I will also need a link to your package (even if its not entirely complete) with the completed metadata.csv file.    As far as ExperimentHub vs AnnotationHub,  @mtmorgan  or @dvantwisk  do you have any strong opinion?

**Comment by Winnie09** [comment]
AdditionalPackage: https://github.com/Winnie09/SCATEData

**Comment by Winnie09** [comment]
Hi @mtmorgan @dvantwisk, the package companion "SCATEData" (ExperimentHub package, as the data package for "SCATE") has been labeled as "OK". I am now working on submitting "SCATE" package. Should I see the commits reports here?  Also, I have changed the github repository (as mentioned at the top first message in this issue) as https://github.com/Winnie09/SCATE.git. Is it OK? Thank you!

**Comment by Winnie09** [comment]
Hi @mtmorgan @dvantwisk @lshep , the package companion "SCATEData" (ExperimentHub package, as the data package for "SCATE") has been labeled as "OK". I am now working on submitting "SCATE" package. Should I see the commits reports here? Also, I have changed the github repository (as mentioned at the top first message in this issue) as https://github.com/Winnie09/SCATE.git. Is it OK? Thank you!

**Comment by lshep** [comment]
In response to your email,  I needed to update the database of issues on our end for the new link.  It has been updated.  Please make sure your webhook is activated on SCATE and try another version bump.

**Comment by Winnie09** [comment]
Dear Reviewers @dvantwisk @mtmorgan,

According to bioc-issue-bot's report, this package has passed all format check. May I know whether there is anything else I should do to help proceed with the review process? We really hope the package could be reviewed soon. Thank you!

Best,
Wenpin

**Comment by mtmorgan** [comment]
I'll take over review of this package and provide comments shortly.

**Comment by Winnie09** [comment]
Thank you so much @mtmorgan ! I am wondering whether you have any further comments on the package? I am happy to revise accordingly so that we could proceed soon. Thank you!

**Comment by mtmorgan** [comment]
# 30 July, 2020


1. Please briefly summarize how you have responded to each of the points in the review in https://github.com/Bioconductor/Contributions/issues/1420#issuecomment-604537158

1. The NOTE

    ```
    Undefined global functions or variables:
      GRanges GRangesList IRanges blacklist countOverlaps end<- nearest
      reduce seqlevels start<-
    ```
    
    indicates that your NAMESPACE is missing imports. For instance in SCATE.R you have
    
    ```
                      satac <- unlist(GRangesList(satac))
    ```
    
    and so should have a tag
    
    ```
    #' @importFrom GenomicRanges GRanges GRangesList
    ```
    
    etc.
    
1. This NOTE

    ```
    * checking Rd line widths ... NOTE
    Rd file 'SCATE.Rd':
      \examples lines wider than 100 characters:
         SCATE(GRanges(seqnames="chr1",IRanges(start=seq_len(100)+1e6,end=seq_len(100)+1e8)),clunum=156,type='reads',genome="mm10") # Reads as i ...
    ```

   also needs to be addressed, because help pages will render poorly. Do so by revising the example to use spaces and line breaks so that the text spans about 80 columns, e.g.,
  
    ```
    #' # Reads as input, setting CRE cluster number as 156 to increase
    #' # speed. Users need to set it to be NULL in real applications.
    #' ir <- IRanges(start=seq_len(100)+1e6, end=seq_len(100)+1e8)
    #' gr <- GRanges(seqnames="chr1", ir)
    #' SCATE(gr, clunum=156, type='reads', genome="mm10")
    ```
    
   Generally, the long lines and nested calls make your code difficult to read, and ti would be very helpful to revise it along the lines of the example, above.

1. These notes

    ```
    * Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        cellcluster.R (line 36, column 24)
        makedatabase.R (line 68, column 31)
        makedatabase.R (line 103, column 31)
        peakcall.R (line 31, column 16)
        peakcall.R (line 33, column 14)
        satacprocess.R (line 18, column 22)
        satacprocess.R (line 18, column 29)
        satacprocess.R (line 22, column 22)
        SCATE.R (line 73, column 28)
        SCATE.R (line 162, column 29)
        SCATE.R (line 168, column 30)
        SCATE.R (line 253, column 20)
        SCATEpipeline.R (line 24, column 13)
        SCATEpipeline.R (line 24, column 20)
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        SCATEpipeline.R (line 27, column 39)
    ```
    
   also need to be addressed. For instance, for this
  
    ```
        SCATEpipeline.R (line 24, column 13)
        SCATEpipeline.R (line 24, column 20)
    ```
    
   the line is
  
    ```
    satac <- sapply(sapply(bamfile,readGAlignmentPairs),GRanges)
    ```

   `sapply()` 'simplifies' a list of matrices /data.frames to a single matrix, but your function returns a list of GRanges, so they will never be 'simplified'. I would write
  
    ```
    satac <- lapply(bamfile, function(fl) GRanges(readGAlignmentPairs(fl)))
    ```

**Comment by Winnie09** [comment]
**Hi @mtmorgan ,**

**We have revised our manuscript according to the comments from you and previous reviewers. Could you please take a look to see if the current package meets the release requirement? Thank you.**

**1. We have tried our best to fix the points in review #1420**

R/GENERAL

[REQUIRED] Some functions require a datapath argument. The
documentation states that the user needs to download the data package
from http://jilab.biostat.jhsph.edu/projects/scate/hg19.zip. This is
problamatic since we cannot ensure that the user will be able to access that
link in the future. I ask that you please submit the data that you want the user
to download as an Experiment Data Package. The following page should help
you make one https://www.bioconductor.org/developers/package-guidelines/#data
 
  **We have created a separate Experiment Data Package SCATEData that has been recently submitted to Bioconductor. SCATE functions no longer download the data package from a fixed URL anymore.**
 
  [REQUIRED] In addition, the repo is 318MB large, much of it due to data
in the inst/extdata directory. This data should be included in your
Experiment Data Package. Also, I ask that you remove these large files from
your version control history. We like to see repositories smaller than 5MB
in size. You can use this tool to remove these large files from version control
when you are able https://rtyley.github.io/bfg-repo-cleaner/
  R/SCATE.R

**We have created a separate Experiment Data Package SCATEData that has been recently submitted to Bioconductor. We have removed these large files from the SCATE package.**

[REQUIRED] Use message() instead of print() when displaying
diagnostic messages to the user. This is desirable since the message can
be toggled off with suppressMessages().

**We have changed all print() to message()**

[REQUIRED] Use seq_len() or seq_along() instead of 1:.... This
is slightly more efficient and avoids the unexpected case where 1:0 is
1 0.

**We have changed all 1:.... to seq_len()**

R/cellcluster.R

[REQUIRED] L19: Do not use set.seed() within your package. If you
wish to have the user generate the same result as you for the vignette,
specify what seed to use at that section of the vignette.
R/extractfeature.R

**We have removed all set.seed() in the package.**

[REQUIRED] The documentation states a matrix will be returned by
extractfeautre(). If the folder argument is not NULL, it will save
the file and nothing will be returned. Please change it so that the table
the documentation says will be returned is returned in any case.
R/peakcall.R

**We have changed the description of the output.**

[REQUIRED] Same problem with set.seed() as before.

**We have removed the set.seed().**

[REQUIRED] Your vignette contains some eval=FALSE tags. We want to
see code exposed to the user run on our builder to verify that it functions
correctly. In some cases, eval=FALSEs can be acceptable, for example, if
the code opens an interactive prompt or the vignette deals with computations
that are too long (In this case we do ask that results of the calculations are available to the user in between code sections). Can you explain the reason for eval=FALSEs here?
 
  **We have removed most of the 'eval=FALSE' now. The remaining functions are related to building a new database and takes too long to run.**
 
**2. We have added GenomicRanges package as an additional import package. 'GRanges GRangesList IRanges' is no longer undefined global functions. There is no undefined global functions any more from packages other than R's basic packages.

3. We have fixed all lines that are too long.

4. We have fixed all sapply() that may potentially cause a problem. We didn't change the remaining sapply(), since changing them requires enormous amount of time to check the results. There is potential risk that changing these functions will prevent the users to reproduce results in our paper. We have doublechecked that these sapply() will not cause problem in running the functions.**

**Comment by mtmorgan** [comment]
Thanks I will accept the package later today. 

With respect to `sapply()`, I see

```
SCATE/R master$ grep sapply *
SCATE.R:                  tabclu <- sapply(spclu,length)
SCATE.R:                  loglike <- sapply(allclunum,function(clunum) {
SCATE.R:            res <- sapply(target,function(i) {
SCATEpipeline.R:   satac <- sapply(sapply(bamfile,readGAlignmentPairs,simplify=FALSE),GRanges,simplify=FALSE)
cellcluster.R:   clusteraggregate <- sapply(names(satac),function(sid) {
makedatabase.R:                  backnorm <- sapply(id,function(j) mean(norm[pos[j,1]:pos[j,2],i]))
makedatabase.R:                  backnorm <- sapply(id,function(j) mean(norm[pos[j,1]:pos[j,2],i]))
peakcall.R:      backv <- sapply(seq(0,100000),function(i) mean(sampfeature[(1+i*(2*flank+1)):((i+1)*(2*flank+1))]))
peakcall.R:      fdr <- sapply(xseq,function(cut) {
satacprocess.R:            satac <- sapply(sapply(input,readGAlignmentPairs,simplify=FALSE),GRanges,simplify=FALSE)
satacprocess.R:      satac <- satac[sapply(satac,length) >= libsizefilter]
```

The code `sapply(spclu,length)` and `sapply(satac,length)` can be replaced with `lengths(spclu)` and `lengths(satac)` for much more efficient processing and more compact representation. 

As mentioned previously the `sapply()` in lines `sapply(sapply(bamfile,readGAlignmentPairs,simplify=FALSE),GRanges,simplify=FALSE)` really just add confusion -- no simplification is possible and the code should just use `lapply()`.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Winnie09.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SCATE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SCATE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Winnie09.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SCATEData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SCATEData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Winnie09** [comment]
Thank you so much @mtmorgan !
