### ISSUE TITLE
BiocDockerManager

### ISSUE THREAD

**Issue by nturaga** [Bioconductor/Contributions#1424]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nturaga/BiocDockerManager

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
yeah, we'll have to adjust the reviewer assignment...

**Comment by nturaga** [comment]
Yes, just as expected the examples which need `docker` need to be wrapped in `\{donttest}`. But, if I do wrap them BiocCheck throws an error saying 56% of the examples in the man pages aren't runnable.

**Comment by nturaga** [comment]
I've pushed updates with the `\donttest{<code>}` tags. But these examples fail because `docker` isn't installed on the build machine.

Version 0.99.2 will also get an ERROR tag though since less than 80% of the examples are runnable.

**Comment by Kayla-Morrell** [comment]
@nturaga - I've finished the review of your package and below are my notes. I don't have any required changes, just a couple suggestions. Comment here whether you decide to make the follow changes or not so I know whether to re-review or accept the package.

## DESCRIPTION

- [ ] SUGGESTION: 'LazyData:' should be set to false.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with the
relevant links to GitHub for reporting Issues.

## Vignette

Well written, very clear, and good examples.

## R code

Well written and well organized.

Thanks!
Kayla

**Comment by nturaga** [comment]
Done @Kayla-Morrell . Thanks for the review.

> @nturaga - I've finished the review of your package and below are my notes. I don't have any required changes, just a couple suggestions. Comment here whether you decide to make the follow changes or not so I know whether to re-review or accept the package.
> 
> ## DESCRIPTION
> * [x]  SUGGESTION: 'LazyData:' should be set to false.
> * [x]  SUGGESTION: It is encouraged to include the 'BugReports:' field with the
>   relevant links to GitHub for reporting Issues.
> 
> ## Vignette
> Well written, very clear, and good examples.
> 
> ## R code
> Well written and well organized.
> 
> Thanks!
> Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nturaga.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocDockerManager")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocDockerManager

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by nturaga** [comment]
Woohoo!
