### ISSUE TITLE
iSEEu

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/Contributions#1425]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/iSEE/iSEEu

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
The problem with these types of "extras" packages is that they end up having tons of dependencies. While they protect the core package from dependency bloat, they just sacrificially shift the bloat to themselves. Having them as Suggests doesn't really help, because Suggests requires the user to understand the implementation detail of which suggested package is required for each feature, and to manually install each, or they just install all of them. Why not create a universe of packages instead of a universe package?

**Comment by kevinrue** [comment]
Fair point! 

I can see how future (panels that this package is intended for) might in fact increase this package complexity (as we have done ourselves to protect the complexity of the `iSEE` core package).
More precisely, each panel is likely to come with its own set of internal functions to deal with the various interactions between user inputs. That could warrant a separate package for each panel (or at least closely related sets of panels).

We'll discuss that internally. I'm sure @LTLA will share his opinion shortly :)

**Comment by federicomarini** [comment]
I'm going to tag myself here @federicomarini to follow up the conversation

**Comment by LTLA** [comment]
This is known and is simply a matter of gaining critical mass for any particular "topic" of visualization. Currently we only have 5 new panels, so it's difficult to justify splitting them up into further packages with, e.g., 1-2 panels per package. As we get more contributions, we will hopefully be in a better position to identify compartments within **iSEEu** and split off functionality into new packages. This is similar to how **scran** begot **batchelor** (and to some extent, **iSEE** itself); **scater** begot **SingleCellExperiment** and **DropletUtils**, and so on.

**Comment by lawremi** [comment]
The complexity of multiple modules still exists. The single package approach just pushes that complexity from the developers to the user. The other cases you cite are different in that the modules emerged over time. Here, you already have separate panels, each with specific dependencies. I'll defer to the core group though, since they'll also have to manage those packages.

**Comment by mtmorgan** [comment]
I started the review process, but Michael's advice shouldn't be taken lightly.

**Comment by kevinrue** [comment]
There was a versioning mistake in the first submission.
I've just tried to downgrade to version 0.99.0 but it didn't trigger anything.
What version should we set now to trigger a build?
Thanks!

**Comment by nturaga** [comment]
Try another push with version 0.99.1

**Comment by LTLA** [comment]
> The complexity of multiple modules still exists. The single package approach just pushes that complexity from the developers to the user. The other cases you cite are different in that the modules emerged over time. Here, you already have separate panels, each with specific dependencies. I'll defer to the core group though, since they'll also have to manage those packages.

Putting aside the philosophical considerations, the only panel with its own set of extra dependencies is the `GeneSetTable`. Everything else has dependencies nested within those of **iSEE**.

I'm not going to make another package just to hold a `GeneSetTable` panel. Well, I might if people were clamoring for it but that would be a nice problem to have.

As elegant as modularity might be, it does not seem worth the fuss of creating 2-3 more packages. I would need to think about appropriate package names, and this would take some effort.

**Comment by kevinrue** [comment]
All going well, the view is ultimately to have an "iSEEverse" of packages, each grouping closely related panels, so that end-users can plug-and-play into an app instance. This version of `iSEEu` is essentially a one-stop-shop for proof of concept that showcases how the wider community can develop different kinds new panels and modes as separate packages.

For instance, the `ReducedDimensionHexPlot` panel is likely to spin out into a separate package during the next release, as its functionality diversifies into a feature set comparable to [`schex`](https://github.com/SaskiaFreytag/schex). At which point, users would have the choice to install the small package dedicated to `ReducedDimensionHexPlot` if they're interested in that single panel, or they could use  `iSEEu` as a wrapper to install and load all available panels a-la-tidyverse.

Naming packages will indeed be the main challenge, at that point, but again that all depends on how popular it all gets. We dream big 😄

**Comment by lawremi** [comment]
Ok, the idea of a demonstration-oriented meta-package that pulls down all of the modules makes sense to me, as long as more granular options become available.

**Comment by csoneson** [comment]
The current ERROR on the Windows builder is due to a failure to access ExperimentHub to download the data for one of the examples, which seems to happen occasionally.

**Comment by kevinrue** [comment]
Any reason why the latest  version bump started a build, but didn't post a report? Should we bump the version again?

**Comment by nturaga** [comment]
Try the version bump.

**Comment by kevinrue** [comment]
👋 @nturaga - I imagine how busy you must be these days. We just wanted to gently enquire about the review status here given that the deadline is approaching. Thanks!

**Comment by nturaga** [comment]
Tomorrow, sorry.

**Comment by nturaga** [comment]
# Review

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## NEWS

* ok

## R

* There should be consistency in the variable naming. You have well
  written code but try not to mix naming `a_b` with `a.b`. Please
  consider changing, although it's not a requirement.
  
* Consistent Indentation wouldn't hurt either.
  
* Use `nzchar` instead of `(x[["Selected"]]!="")` and
  `length(msg)`. Example:


		> nzchar("")
		[1] FALSE
		> nzchar("adfaf")
		[1] TRUE

* Well written code!

## vignette

ok

## man

ok

**Comment by kevinrue** [comment]
Hi @nturaga 

Thanks a lot for your review!

Please see `0.99.8` for our updates following your review.

In particular:

- Indentation was fixed (4 space indent).
- Use `nzchar(x)` instead of `x!=""`.
  + However `length(msg)` is intentionally designed to check the number of values in the character vector `msg`
- Variable naming: we have documented our naming style in the [vignette](https://github.com/iSEE/iSEEu/blob/master/vignettes/universe.Rmd#L263).
  Note that while the package uses various naming styles, there are not randomly mixed. Some of the styles are used for end user-facing objects, others for developers of new `iSEEu` panels, and finally others for internal package use.

I hope this is enough to get us in the BiocC 3.11 manifest before Wednesday?
![image](https://user-images.githubusercontent.com/5769108/79752797-c0759900-830c-11ea-9f06-0f4471454baf.png)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinrue.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("iSEEu")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iSEEu

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
