### ISSUE TITLE
coseq

### ISSUE THREAD

**Issue by andreamrau** [Bioconductor/Contributions#143]
- Repository: https://github.com/andreamrau/coseq

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5](optionally [via GitHub][6]).

**Comment by LiNk-NY** [comment]
Hi @andreamrau!
I am aware of your package. I will review it shortly. Sorry for the delay in getting back to you. There have been many package submissions close to the deadline. 

Thank you for your patience. 

Regards,
Marcel

**Comment by andreamrau** [comment]
Hi Marcel, 
Of course no problem! I'm looking forward to your feedback once you have time to review the package.
Thanks for the update!
Best, Andrea

**Comment by LiNk-NY** [comment]
Hi Andrea @andreamrau, 
Thank you for submitting to Bioconductor! 
I have briefly looked at your package and composed a short review. Please see below. 

---

### coseq


#### Grammar 
* Avoid using 1:number for creating a sequence, use the more robust method of seq_len(number)
* Don’t overwrite / assign object names that are already function (i.e., I <- which(label == k)
* Use descriptive argument name (rather than x use coseq)
* Use S4Methods rather than S3
* Use is(object, “class”) to test for class. 
* Some functions look like they’re meant to dispatch using S4 methods
* Nested lists may necessitate an S4 structure to avoid using chain $ calls
* Avoid using periods or under_scores in function names
* `if(is.null(arg.user$Kmin.init)) arg.user$Kmin.init <- “small-em”` -- Seems like you should have a named list where you can input values based on is.null results. 
* No need to use `;` semi-colons
* Minor: use `which.max`, paste0 exists, if (length(conds)) vs if (length(conds) > 0)
* Avoid the use of `@` in extractor functions -- create accessor functions/methods
* Don’t need logic like if (transpose == TRUE) or if (is.numeric(K) == TRUE)
* Why so many options for plotting? If you do need all of those consider the data structure and how it is supposed to facilitate your plots. 
  * Don’t use functions as variables (i.e., “c” in {for c in sequence})

#### Vignette
* Could you provide a compilable vignette for the package? It would be better for users to be able to follow and run the functions that you provide in the package interactively. 

#### Structure
* It would be better to use available S4 structures for your class (i.e., using DataFrame instead of data.frame) 
* You can combine related functions into one file. 
* I can't imagine that there are no Bioconductor classes/structures available for your use. We would prefer that you re-use any existing functionality. 

Thank you for your time!

Regards,
Marcel

**Comment by andreamrau** [comment]
Hi Marcel,
Many thanks for this detailed review. It will obviously be too tight of a time crunch to address all of these points today for release in the next Bioconductor, so I will get to work on them in the next week or two (for the subsequent release in a few months).  I will let you know once I have looked into all of these points -- thanks again for the comments.
Best,
Andrea

**Comment by andreamrau** [comment]
Hi Marcel @LiNk-NY ,
Thanks for your patience. I've made some fairly significant changes to the code to address your comments, below you can find a point-by-point response to each of your suggestions. Let me know when you have a chance to look things over again!
Thanks, Andrea

---

### Grammar

1. Avoid using 1:number for creating a sequence, use the more robust method of seq_len(number)
-- Done.

2. Don’t overwrite / assign object names that are already function (i.e., I <- which(label == k)
-- Done.

3. Use descriptive argument name (rather than x use coseq)
-- Done.

4. Use S4Methods rather than S3
-- Done.

5. Use is(object, “class”) to test for class.
-- Done.

6. Some functions look like they’re meant to dispatch using S4 methods
-- S4 methods are now used for all primary (user-interface) functions and accessors.

7. Nested lists may necessitate an S4 structure to avoid using chain $ calls
-- Thanks for this nice suggestion. An S4 class extending the RangedSummarizedExperiment class was created, called coseqResults, to store results and avoid chained $ calls.
 
8. Avoid using periods or under_scores in function names
-- Done.

9. if(is.null(arg.user$Kmin.init)) arg.user$Kmin.init <- “small-em” -- Seems like you should have a named list where you can input values 
based on is.null results.
-- Done.

10. No need to use ; semi-colons
-- All semi-colons have been deleted.

11. Minor: use which.max, paste0 exists, if (length(conds)) vs if (length(conds) > 0)
-- All instances of paste(..., sep="") have been replaced by paste0, which.max and which.min have been used where appropriate, and if conditions similar to e.g., if(length(conds) > 0) have been replaced by if(length(conds))

12. Avoid the use of @ in extractor functions -- create accessor functions/methods
-- Done (see the newly added generic functions in AllGenerics.R)

13. Don’t need logic like if (transpose == TRUE) or if (is.numeric(K) == TRUE)
-- Fixed throughout.

14. Why so many options for plotting? If you do need all of those consider the data structure and how it is supposed to facilitate your plots.
-- The plot function has been significantly simplified.

15. Don’t use functions as variables (i.e., “c” in {for c in sequence})
-- Fixed throughout.

### Vignette

1. Could you provide a compilable vignette for the package? It would be better for users to be able to follow and run the functions that you provide in the package interactively.
-- Done.

### Structure

1. It would be better to use available S4 structures for your class (i.e., using DataFrame instead of data.frame)
-- As noted above, an S4 class extending the RangedSummarizedExperiment class was created, called coseqResults, to store co-expression results. 

2. You can combine related functions into one file.
-- Done. In particular, the newly defined class extension coseqResults is defined in AAA-classes.R, generics are in AAA-generics.R, and S4 method definitions are in methods.R. 

3. I can't imagine that there are no Bioconductor classes/structures available for your use. We would prefer that you re-use any existing functionality.
-- As noted above, we now re-use existing functionality by extending the RangedSummarizedExperiment class.

**Comment by LiNk-NY** [comment]
Hi Andrea, @andreamrau 
Thank you for making those changes. I will have a quick look at your package shortly. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Andrea, @andreamrau 
Thank you for making those changes. Your package is looking good. 

Is there a reason why you need to include a static vignette in your  package. Why not make it a runnable vignette as the one you provided? You one you included is great!

Minor comments about your changes:

* Consider adding unit tests
* Removing trailing whitespace 

Regards,
Marcel

**Comment by andreamrau** [comment]
Hi Marcel, @LiNk-NY 

Thanks for the latest comments! I've add the appropriate version of R to the depends field, removed the static vignette from the package (you're right, all of the information was in the runnable vignette, so it was totally redundant), and started adding unit tests (I will continue to add to them as I continue development on the package). By trailing whitespace, you mean extra lines at the end of each R file, right? If so, I've deleted them.

Thanks for your careful review, and let me know if there's anything else you would recommend or suggest.

Best, Andrea

**Comment by LiNk-NY** [comment]
Hi Andrea, @andreamrau
I mean the white spaces at the end of every line.
This is a minor point but they can be easily removed.

If you are using RStudio, you can set this setting under: 
`Tools` > 
`Global Options...` > 
`Code` > 
`Saving` tab > 
`Strip trailing horizontal whitespace when saving`

Regards,
Marcel

**Comment by andreamrau** [comment]
Hi Marcel, @LiNk-NY 

Ok, thanks for the explanation. I just followed your instructions for stripping the trailing whitespace in RStudio. The R version >= 3.4.0 is in the `Depends` field. Thanks very much for your comments, this has been a very positive review experience!

Best, Andrea

**Comment by LiNk-NY** [comment]
Thank you for submitting to Bioconductor Andrea! @andreamrau 

Regards,
Marcel
