### ISSUE TITLE
glmGamPoi

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/Contributions#1431]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/const-ae/glmGamPoi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thanks for your submission. Please see initial review comments: 

**DESCIRPTION**

- [ ] Remove lazyData: true we have rarely found this useful and in our
  experience can slow installation

**NAMESPACE**

- [ ] Is there a reason you choose S3 implementation rather than S4? We
  generally prefer S4 implementation and would highly suggest transitioning the
  code from S3 to S4. 

**NEWS**

- [ ] Please see suggested formatting. We don't recommend having the package
  name as the title as it is duplicated information ?news we recommend `changes
  in version`. 

**inst**

- [ ] What are these and where are they used? 

**vignette**

- [ ] Change the name. We highly recommend the name of the package as it is
  intuitive for a user to do `vigentte("glmGamPoi")` . Regardless it should be
  less generic. Something like Quickstart could be a vignette in multiple
  packages and depending on how they loaded the packages into their R session
  cause your vignette to not actually display. 

- [ ] Your vignette is minimal while your README is more extensive.  You can
  keep this quickstart basic vignette but you will need a more comprehensive
  vignette as well. 

- [ ] Include Bioconductor installation instructions in all vignettes

- [ ] In your vignette you do `c(fit)` yet `c()` is a standard concatenation
  function. Change the name of this function to accurate display what it is
  doing. 

- [ ] You should show the real dataset in the vignette as well as the
  README. README code is not run or tested and using simulated data doesn't
  always catch errors in the code like the code found in
  examples/vignette/tests.  How long does it take your function to run? Is there
  not a smaller real dataset that can be used? The README code while it took a
  bit of time did not seem like it would be unreasonable to run in the vignette
  and still be under the expected time constraint? You could always load the
  full dataset and truncate it to a smaller set like you did for the
  benchmarking in the README  


**README**

- [ ] Include Bicoonductor installation instructions too




**R code / man pages**

_General Notes_

- [ ] As noted above we would highly recommend using S4 instead of S3. You will
  need to make a strong case for not transitioning to S4 classes. 

_glmGamPoi-package_

- [ ] (Optional) might be nice to have the glmGamPoi.Rd man page that gives a
  summary of the package and list the main functions. 

_glm\_gp_

- [ ] Do any of the other arguments need parameter checking to make sure the
  user enters valid input? 

_print\_model_

- [ ] have one paste0 call instead of multiple in format.glmGamPoi

When ready please remember to do a version bump to kick off a new build and comment back here that you are ready for a re-review with a summary of changes. 

Cheers!

**Comment by const-ae** [comment]
Hi Lori,

thank you very much for your review. I hope my comments clarify some of the decision I took. But feel free to correct me if I misunderstood something :)

>  Is there a reason you choose S3 implementation rather than S4? We
generally prefer S4 implementation and would highly suggest transitioning the
code from S3 to S4.

I wanted to keep the overhead (in terms of cognitive load and additional getter methods) for the package as low as possible. And in the spirit of "Everything should be made as simple as possible, but not simpler", I felt that S3 achieves exactly that.

> inst
 What are these and where are they used?

The inst folder contains the C++ header files that  I want to make available for other packages, so they don't have to repeat the same implementation. For example the `fisher_scoring_qr_step()` function can be useful in and of itself. I followed the example of Aaron Lun's [beachmat](https://github.com/LTLA/beachmat/tree/master/inst/include/beachmat).

> In your vignette you do c(fit) yet c() is a standard concatenation function

I use `c()` for its secondary function of stripping an object of all attributes, excepts names.

>  Do any of the other arguments need parameter checking to make sure the
user enters valid input?

As far as I can tell, no. Note that a lot of parameters are validated in `glm_gp_impl()`.

------------
I fixed the following issues:

* Remove lazyData
* NEWS
* vignette. I use the same code now in the README and the glmGamPoi-vignette. Thus, the vignette is now more extensive and uses real world data. I also included the Bioconductor installation instructions
* one `paste0()` in print_model

**Comment by mtmorgan** [comment]
For the `c()` argument, why not just use `attributes(x) = NULL` which is explicit in what it is doing?

**Comment by lshep** [comment]
Please see @mtmorgan  comment above.  I still would insist on renaming the exported function `c()` to something else or enhancing the functionality to be able to concat two of your objects.  Basic R programming teaches that function as a listing and concatenation function, not strictly for formatting.

**Comment by const-ae** [comment]
Hi Lori, thank you so much for your comments, the last week was quite busy, so I didn't manage to take care of the issues, but I will look into the comments and adapt the code in the next two days.

**Comment by lshep** [comment]
The NEWS file ERROR is on our end. We have a fix implemented in linux and there will be a fix on windows by later this afternoon. I will kick off a manual build so there is at least an accurate linux build. it should post shortly.

**Comment by lshep** [comment]
NEWS file ERROR on our end is fixed.  Let me know when you are ready for a re-review

**Comment by const-ae** [comment]
Thank you for the quick fix.

Compared with the original review, I have now fixed the following issues:

* Removed LazyDate from DESCRIPTION
* Fixed NEWS file
* Renamed vignette to `glmGamPoi.Rmd`
* Extended the content of the vignette which is now identical to the README
* Use the BioConductor installation instructions
* Removed the confusing `c(fit)` pattern with `as.list(fit)` which expresses much better what I want to do
* Use the TENxPBMCData in the vignette
* Fixed the repeated `paste0()` calls in `print_model.R`

About the two question you raised:

> inst
What are these and where are they used?

The inst folder contains the C++ header files that I want to make available for other packages, so they don't have to repeat the same implementation. For example the fisher_scoring_qr_step() function can be useful in and of itself. I followed the example of Aaron Lun's beachmat.

> Do any of the other arguments need parameter checking to make sure the
user enters valid input?

As far as I can tell, no. Note that a lot of parameters are validated in glm_gp_impl().

**Comment by lshep** [comment]
Thanks.  changes look good.  thank you.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/const-ae.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("glmGamPoi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/glmGamPoi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
