### ISSUE TITLE
MsCoreUtils

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/Contributions#1432]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RforMassSpectrometry/MsCoreUtils

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lgatto** [comment]
Hello - `MsCoreUtils` is the first submission from the [R for Mass Spectrometry](https://www.rformassspectrometry.org/) effort, lead by @lgatto, @sgidd and @jorainer. The package implements low-level functionality that is used in other packages (such as [`Spectra`](https://github.com/rformassspectrometry/Spectra/), [`Features`](https://github.com/rformassspectrometry/Features/) that will be submitted in due time, and will be used by [`MSnbase`](http://bioconductor.org/packages/release/bioc/html/MSnbase.html) and [`MALDIQuant`](https://cran.r-project.org/web/packages/MALDIquant/index.html) once available in Bioconductor). Given that the package is meant to be used by package developers and the functionality made accessible through high-level infrastructure (like [preprocessCore](http://bioconductor.org/packages/release/bioc/html/preprocessCore.html)), the package doesn't include a vignette.

**Comment by lgatto** [comment]
I would like to make a case for these errors to be false positives:
```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .
```
The maintainer email address redirects to the emails of the packages authors, who are all already Bioconductor package maintainers and fulfill the above requirements.

```
 Checking whether vignette is built with 'R CMD build'...
    * ERROR: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.
```
As [mentioned above](https://github.com/Bioconductor/Contributions/issues/1432#issuecomment-602804589), we believe a vignette isn't really necessary here - there isn't much more to say than is in the man pages.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Please provide a more comprehensive Description: of the 'low-level functions' this package provides.

vignette

- I believe a brief vignette would still be in order, e.g., describing design principles and steps one anticipated developers will take to implement end-user functionality.

R

- the code seems well-organized, cleanly implemented, and well-documented.

other

- nice to see the extensive unit tests!

**Comment by lgatto** [comment]
Version [0.99.2](https://github.com/RforMassSpectrometry/MsCoreUtils) is now online - it contains an extended Description and a vignette. Not sure why it hasn't triggered a new build here - may be because it was submitted as a PR?

**Comment by mtmorgan** [comment]
Yes, version bumps currently need to be done on the master branch; we recently became aware of this and will address it, but for now is it possible to do a version bump on master?

**Comment by lgatto** [comment]
Done
![2020-04-05-172800_1046x287_scrot](https://user-images.githubusercontent.com/384198/78502751-e3c41400-7762-11ea-999a-3a776f736659.png)

**Comment by mtmorgan** [comment]
Hmm @lshep or @Kayla-Morrell may be able to get us back on track...

**Comment by lgatto** [comment]
Anything I need to do here?

**Comment by lgatto** [comment]
Hello. I just was the announcement that 

> the last day for any NEW package to be accepted and released under Bioc 3.11 is this Wed. April 22th.

Do let me know if I need to do anything to get this issue back on track.  Thank you.

**Comment by mtmorgan** [comment]
Sorry for the delay. I ran the build and check locally and reviewed your revision.

**Comment by lgatto** [comment]
Thank you very much!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgatto.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsCoreUtils")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsCoreUtils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
