### ISSUE TITLE
sangeranalyseR

### ISSUE THREAD

**Issue by HowardChao** [Bioconductor/Contributions#1433]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/roblanf/sangeranalyseR

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by HowardChao** [comment]
Hi @nturaga! 
sangeranalyseR uses Read the Docs for documentation. Thus, `docs/` directory is included so that documentation will be rebuilt for each new commit. 

The only problem that I have is package source tarball exceeds Bioconductor size issue because I include the `docs/` directory. Is it fine in my case?

And this is the sangeranalyseR documentation link: https://sangeranalyser.readthedocs.io/en/latest/

Thank you for your help!

**Comment by HowardChao** [comment]
Hi @nturaga! 
Have you had time to look into this? I have a question about package size limitation. Thank you! 👍

**Comment by lshep** [comment]
The NEWS file ERROR is on our end.  We will have a fix for the windows machine tomorrow and the linux should be remedied.

**Comment by lshep** [comment]
The NEWS file ERROR is on our end. We have a fix implemented in linux and there will be a fix on windows by later this afternoon. I will kick off a manual build so there is at least an accurate linux build. it should post shortly.

**Comment by nturaga** [comment]
# Review

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* The description of the package should be like a paper abstract.

* You can have only one maintainer. Please review package guidelines.

* Your package 'Depends' on packages like kableExtra, are these needed
  for the vignette? Have you thought about which packages should go in
  the 'Suggests' section?

## NAMESPACE

* If you are using certain packages for a "single" function, consider
  not using the package and using a base package instead. 
  
  It is valuable to have a package which has fewer dependencies. The
  more packages you depend on the higher you have a chance of issues
  in your build report.
  
## NEWS

* ok

## General

* There is an "Rplots.pdf" in your directory? What is the utility for
  this?

* Your package is erroring out because it doesn't meet the < 5MB
  limit. This needs to be fixed. Please look at your `inst`, `docs`
  folders.

## R

* It will help to follow the coding style we maintain,
  http://bioconductor.org/developers/how-to/coding-style/.
  
* No `sapply`. Please pay attention to the NOTE's you get on the build
  report. http://bioconductor.org/developers/how-to/efficient-code/
  
* Avoid 1:...; use seq_len() or seq_along().

* Avoid '<<-'

* Update R version dependency from 3.6.0 to 4.0.

## vignette

* ok

## man

* ok

## General

Please fix the build report before we proceed to a second review.

**Comment by HowardChao** [comment]
Hi @nturaga!
sangeranalyseR uses *Read the Docs* for documentation. Thus, `docs/` directory is included so that documentation will be rebuilt for each new commit.

The only problem that I have is package source tarball exceeds Bioconductor size issue because I include the `docs/` directory. Is it fine in my case?

And this is the sangeranalyseR documentation link: https://sangeranalyser.readthedocs.io/en/latest/

Thank you for your help!

**Comment by nturaga** [comment]
@HowardChao 

You need to fix your build report too. Please work on that, while I take a look at what needs to be done regarding your documentation. 

But we don't allow bioconductor packages above a 5MB limit. You may have to open an auxiliary github repository to host just the documentation.

**Comment by HowardChao** [comment]
Hi @nturaga  

## DESCRIPTION

* The description of the package should be like a paper abstract.
    - Fixed.

* You can have only one maintainer. Please review package guidelines.
    - Fixed.

## NAMESPACE

* Your package 'Depends' on packages like kableExtra, are these needed
for the vignette? Have you thought about which packages should go in
the 'Suggests' section?  If you are using certain packages for a "single" function, consider
not using the package and using a base package instead.
    - `kableExtra` is used in R scripts. This R package contains a lot of features of Sanger sequencing data analysis and R shiny apps. Therefore, it depends on more R packages. We have carefully checked all packages listed in 'Depend' are necessary.

* There is an "Rplots.pdf" in your directory? What is the utility for this?
    - This file is deleted.

* Your package is erroring out because it doesn't meet the < 5MB
limit. This needs to be fixed. Please look at your inst, docs
folders.
    - I have moved the documentation to an auxiliary Github repository; however, we prefer to put the documentation and the R package in the same repository. I am not sure about the branch method that you mentioned. Could you explain more about how I should do? 
(If I move the documentation back to the `master` branch after the package is accepted, would it cause any problems in future maintenance? Thank you!)

## R

* No sapply. Please pay attention to the NOTE's you get on the build
report. http://bioconductor.org/developers/how-to/efficient-code/
    - Fixed

* Avoid 1:...; use seq_len() or seq_along().
    - Fixed

* Avoid '<<-'
    - There are two shiny apps inside this R package. '<<-' is used to access the global variables in Shiny apps, and it is only used in Shiny app code.

* Update R version dependency from 3.6.0 to 4.0.
    - Fixed.

**Comment by HowardChao** [comment]
Hi @nturaga ~ I have already fixed the R package. Thank you for your help.

**Comment by nturaga** [comment]
You can move the docs back once the package gets into the system.

**Comment by HowardChao** [comment]
Hi @nturaga. When will sangeranalyseR gets into Bioconductor server? We are going to submit the manuscript and would like to include the sangeranalyseR Bioconductor link to our ms. Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HowardChao.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sangeranalyseR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sangeranalyseR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
