### ISSUE TITLE
HighlyReplicatedRNASeq

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/Contributions#1436]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/const-ae/HighlyReplicatedRNASeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Constantin, @const-ae 

Thank you for your submission to Bioconductor. 
I have reviewed your package. 
Please see the short review below. If you have any questions,
feel free to comment on the issue.

Best regards,
Marcel

---

# HighlyReplicatedRNASeq #1436

The title of the package is a bit vague and it may be more helpful to be
specific.

## DESCRIPTION

* A more detailed description would be helpful for potential users of the
data.
* Include the source of the data in the `Description:` field

## NAMESPACE

* Nice and short

## vignettes

* It looks good / illustrative.
* It may be better to provide the data in a standard format such as `matrix`
and then provide a function in the package that takes the matrix and serves
a `SummarizedExperiment`. This avoids issues with serialized objects in
'long-term' storage.

## R

* You could put all the files in one `R` file.
* Why not include a helper function to 'attach' the metadata to an existing
`SummarizedExperiment` object?
* Is the resource number supposed to be the same for both functions?

## /

* Keep one LICENSE file in the repository. The `LICENSE` file is not
necessary because it is known that you are the author of the package.

## README

* Update the installation instructions to use `BiocManager::install`

**Comment by const-ae** [comment]
Hi Marcel, 

thank you for your review.

You suggest that it might be helpful to store the raw count matrix, but in the first section of the [Creating An ExperimentHub Package](https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html) ExperimentHub vignette it is recommended to store processed data structures:

> The resources are generally not files of raw data (as can be the case in AnnotationHub) but instead are R / Bioconductor objects such as GRanges, SummarizedExperiment, data.frame etc

That is why I am confused right now, what is the current recommended best practice?

------------
Other comments:

> The title of the package is a bit vague and it may be more helpful to be
specific.

Yes, you are right. I however plan to extend the package with more datasets that fit that description. Thus, I think the name is appropriate.

> Is the resource number supposed to be the same for both functions?

Yes, the difference is that the `[` function returns the metadata, where as the `[[` function downloads and returns the full dataset.

> Why not include a helper function to 'attach' the metadata to an existing
SummarizedExperiment object?

My approach is to keep this package minimal, so my question would be the other way around: why include a helper function? Especially, if is is a simple one-liner is the user wants to do this
`metadata(se)$source_info <- Schurch16_metadata()`.

> Include the source of the data in the Description: field

Fixed.

> The LICENSE file is not necessary 

Fixed.

> Update the installation instructions to use BiocManager::install

Fixed.

**Comment by const-ae** [comment]
> > The LICENSE file is not necessary

> Fixed.

Reverted the fix to get rid of warning.

**Comment by LiNk-NY** [comment]
Hi Constantin, @const-ae 

> You suggest that it might be helpful to store the raw count matrix, but in the first section of the [Creating An ExperimentHub Package](https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html) ExperimentHub vignette it is recommended to store processed data structures:
> 
> > The resources are generally not files of raw data (as can be the case in AnnotationHub) but instead are R / Bioconductor objects such as GRanges, SummarizedExperiment, data.frame etc
> 
> That is why I am confused right now, what is the current recommended best practice?
> 

That is a valid point and perhaps we should change the language in the vignette. From experience, it would be better to upload components of the data object and assemble them on-the-fly. This means storing `colData` as `data.frame` count data as `matrix` and metadata as a `list`. This will protect you from having to update serialized instances of `SummarizedExperiment` when internals change.


> > Why not include a helper function to 'attach' the metadata to an existing
> > SummarizedExperiment object?
> 
> My approach is to keep this package minimal, so my question would be the other way around: why include a helper function? Especially, if is is a simple one-liner is the user wants to do this
> `metadata(se)$source_info <- Schurch16_metadata()`.
> 

Ideally, the 'helper' function would not be necessary if you provide one single instance of a `SummarizedExperiment`. With one function, the user obtains an integrated representation (`SummarizedExperiment` with `metadata`) instead of two functions that give the user the pieces that have to be assembled. This is not much of an issue with two pieces but it becomes more of an issue when you have many pieces. 

> > Reverted the fix to get rid of warning.
I think this happened because you had to update the `DESCRIPTION` file and remove the `+ file LICENSE` from the `License: ` field

Best,
Marcel

**Comment by const-ae** [comment]
> That is a valid point and perhaps we should change the language in the vignette. From experience, it would be better to upload components of the data object and assemble them on-the-fly. This means storing colData as data.frame count data as matrix and metadata as a list. This will protect you from having to update serialized instances of SummarizedExperiment when internals change.

Sure, I am okay with that. Should I then ask Lori to delete the old metadata and for access to the S3 storage?

**Comment by lshep** [comment]
The same S3 credentials should still be active for you to upload.  Just let me know if the old data should be deleted and when the metadata.csv file is updated for the new data to be uploaded.

**Comment by const-ae** [comment]
Hi Marcel,

I have mailed with Lori and changed the structure of the data stored in ExperimentHub as you suggested.

----------
> I think this happened because you had to update the DESCRIPTION file and remove the + file LICENSE from the License: field

I did as you suggested and removed the LICENSE file and the reference. Now I get the following 
NOTE from R CMD check, but I guess that is fine then:

```
* checking DESCRIPTION meta-information ... NOTE
License components which are templates and need '+ file LICENSE':
  MIT
```

**Comment by LiNk-NY** [comment]
Hi Constantin, @const-ae 
Thanks for making those changes. I am taking a look.
-Marcel

**Comment by LiNk-NY** [comment]
It looks like although `MIT` is a "standard" license type, R-core treats it as a template. See https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing. Therefore, you have to add a `LICENSE` file and keep `License: MIT + file LICENSE` in the `DESCRIPTION`. The `LICENSE` file should read:
```
YEAR: 2020
COPYRIGHT HOLDER: Constantin Ahlmann-Eltze 
```
Apologies for the back and forth. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Constantin, @const-ae 

Thank you for making those changes. The package is ready to go. 

Cheers,
Marcel

**Comment by const-ae** [comment]
Thank you Marcel for your review. I am very happy to see this accepted :)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/const-ae.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HighlyReplicatedRNASeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HighlyReplicatedRNASeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
