### ISSUE TITLE
cytomapper

### ISSUE THREAD

**Issue by nilseling** [Bioconductor/Contributions#1441]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BodenmillerGroup/cytomapper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please make sure to remove .Rhistory files from your git repository.

**Comment by nilseling** [comment]
Hi @lshep,

I can't quite figure out where the last warning on the Windows server is coming from. When searching for help online, most posts recommend re-installing the package dependencies. 
Would you know anything about this warning and could you point me in the right direction to fix this?
Thanks for your input!
Best,

Nils

**Comment by lshep** [comment]
I would ignore this Warning for now.  Bioconductor packages will be reinstalled on there own.  In makes me think there might be conflicting plot methods (maybe not necessarily from your package could also be from dependencies)  --

**Comment by nilseling** [comment]
Yeah, I thought the same and removed the exported plot method from my package. But that didn't seem to fix the problem.

**Comment by lshep** [comment]
so ignore for now.

**Comment by lshep** [comment]
Thank you for your submission.   Please see initial review below: 

**README**

- [ ] Include Bioconductor installation instructions

**Description**

- [ ] Please remove date field. This should be generated automatically so it doesn't get out-dated

**inst/extadata**

- [ ] Please include an inst/scripts directory that has a file describing the ata in inst/extdata. Ideally code but could be sudo code or text description but should include relevant source/reference information and any sort of processing or subsetting


**vigenttes**

_I'm coming from a naive user perspecetive since I don't readily work with this
type of data_

- [ ] Just for my own clarity. The image files, they come directly from some instrumentation? 

- [ ] I guess I'm still slightly confused at the jump from 4.1 to 4.2.  If I assume the .tiff files come directly from instrumentation, but you already have the SingleCellExperiment object created? Does this come from the same instrumentation or is this a different step?  There is no indication of  how the SCE object was created so I'm not exactly getting the connection. Maybe someone in this field and working with this data would already understand this? 

- [ ] So is the object `data(pancreasMasks)`  created from 
```
path.to.images <- system.file("extdata", package = "cytomapper")
all_masks <- loadImages(path.to.images, pattern = "_mask.tiff")
all_masks
```

**R code / man pages**

Everything looks well written. 

Please respond to the few comments above and the few minor adjustments.  When ready please do a version bump and respond back here with a summary of changes and any responses to the inquires above.  

Cheers.  Looking forward to getting this into Bioconductor.

**Comment by nilseling** [comment]
Hi @lshep,

thanks a lot for your comments! 
We have now worked on the package/docs and submitted the reviews.
In detail, we have addressed the individual points as described below:

> Thank you for your submission. Please see initial review below:
> 
> **README**
> 
> * [ ]  Include Bioconductor installation instructions

We have added this to the README.

> 
> **Description**
> 
> * [ ]  Please remove date field. This should be generated automatically so it doesn't get out-dated
> 
> **inst/extadata**
> 
> * [ ]  Please include an inst/scripts directory that has a file describing the ata in inst/extdata. Ideally code but could be sudo code or text description but should include relevant source/reference information and any sort of processing or subsetting

We have now added .Rmd files to inst/scripts that download the data and fully process them to form the toy dataset. Furthermore, we have also added a README.md to inst/scripts that give further instructions on the data used. This data is published and we reference the correct publication and external processing scripts that are needed to process raw data into files that can be used with `cytomapper`.

> 
> **vigenttes**
> 
> _I'm coming from a naive user perspecetive since I don't readily work with this type of data_
> 
> * [ ]  Just for my own clarity. The image files, they come directly from some instrumentation?

The toy dataset used in the package comes from the Fluidigm Hyperion system. Unfortunately, the system does not return files that can be directly read into R. In the vignette, we link to standard pre-processing scripts that return the data in a format that can directly be used with `cytomapper`. We have now added further explanations to the "The provided toy dataset" section to indicate how raw data is commonly pre-processed.

> * [ ]  I guess I'm still slightly confused at the jump from 4.1 to 4.2.  If I assume the .tiff files come directly from instrumentation, but you already have the SingleCellExperiment object created? Does this come from the same instrumentation or is this a different step?  There is no indication of  how the SCE object was created so I'm not exactly getting the connection. Maybe someone in this field and working with this data would already understand this?

As mentioned above, pre-processing is unfortunately needed to generate data formats that can be directly used with `cytomapper`. However, the package reads in the standard output of the pre-processing pipeline. As you can see from the inst/scripts/1_LoadPancreasData.Rmd file, it is a bit tricky to read all files into a `SingleCellExperiment` object. Nevertheless, generating the `SingleCellExperiment` object from the pre-processed data is feasible when following the OSCA workflow (as mentioned in the vignette). My plan for the fall Bioconductor release is to write an extensive workflow how to process and analysis this sort of data using Bioconductor.  

> * [ ]  So is the object `data(pancreasMasks)`  created from
> 
> ```
> path.to.images <- system.file("extdata", package = "cytomapper")
> all_masks <- loadImages(path.to.images, pattern = "_mask.tiff")
> all_masks
> ```

In general, yes. The only step missing here is to scale the masks due to a scaling issue when pre-processing data using CellProfiler:

```
all_masks <- scaleImages(all_masks, value = (2 ^ 16) - 1)
```

This last step will scale the pixel-values in the masks to match the actual object IDs generated during segmentation.

> 
> **R code / man pages**
> 
> Everything looks well written.
> 
> Please respond to the few comments above and the few minor adjustments. When ready please do a version bump and respond back here with a summary of changes and any responses to the inquires above.
> 
> Cheers. Looking forward to getting this into Bioconductor.

Thanks again for the comments! It helped us to organise the processing of the toy data, which we will also use for an associated publication.
And please let me know if we should add other things or how to proceed.
Best,

Nils

**Comment by lshep** [comment]
Thank you.  Everything else looks good to me and the added inst/scripts and sections to the vignette make the connections more clear.  Welcome to bioconductor.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nilseling.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cytomapper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cytomapper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
