### ISSUE TITLE
spqnData

### ISSUE THREAD

**Issue by yiwang12** [Bioconductor/Contributions#1443]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hansenlab/spqnData

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by yiwang12** [comment]
AdditionalPackage: https://github.com/hansenlab/spqn

**Comment by yiwang12** [comment]
AdditionalPackage: https://github.com/hansenlab/spqn

**Comment by yiwang12** [comment]
AdditionalPackage: https://github.com/hansenlab/spqn

**Comment by mtmorgan** [comment]
We will need to clear the previous issue from our database; @lshep will fix this and trigger a build.

**Comment by yiwang12** [comment]
Thanks. That would be great.

**Comment by lshep** [comment]
I have updated the database and I have kicked off a manual build of spqn (it should post shortly).  Please make sure your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is set up on both package repositories so both will build on a version bump in the description.  Let me know if you have any problems receiving automated build reports.  Cheers

**Comment by mtmorgan** [comment]
Please review and update your package in response to the comments below. When ready, post a short comment indicating changes made.

## spqnData

DESCRIPTION

- Please provide a more descriptive Description: field

man

- Please include an `\example{}` on the man page, so the package at least loads the data as part of the build and check process.

## spqn

DESCRIPTION

- good

NAMESPACE

- since the 'man' pages are generated by roxygen2, I am surprised that the NAMESPACE seems to be generated by hand?

vignettes

- good

R (code should be reviewed for other occurrences of these specific comments)

- functions_evaluation.R:13 generally one wants to avoid 'copy and append', and instead let R build the vector (e.g., `vapply()`) or to pre-allocate `grp_mean = numeric(10); ... grp_mean[i] = ...`.

- please consider alternatives to globals.R, e.g., using quoted strings instead of non-standard evalaution in 'tidy' expressions, to avoid masking true errors.

- spqn.R:10 replace iteration (`n` calls to R functions) with vectorization (1 call), e.g.,

    ```
    idx <- seq_len(ngrp)
    grp_loc[idx] = grp_loc0[idx]
    ```
    
- spqn.R:38 highly nested logic is difficult to parse; break these into separate lines (omitting repeated code and relaxing spacing for increased legibility)

    ```
    tail <- tail(grp_loc_inner[[i-1]], 1)
    grp_loc_inner[[i]] <- (tail + 1):(tail + width_tmp)
    ```

- spqn.R:101 `remove()` is seldom needed in code; the referenced objects are available for automatic 'garbage collection' as soon as the function exits.

man

- the man pages seem to be generated by roxygen2, but there are no roxygen2 commands in the R files. This seems to undermine a major advantage of roxygen2, which is documentation at the location where the function is defined.

other

- it would be valuable to develop more extensive unit tests.

**Comment by yiwang12** [comment]
Hi Martin @mtmorga, we have completed the revision of the packages, and it is ready for second review now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yiwang12.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spqnData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spqnData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yiwang12.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spqn")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spqn

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
