### ISSUE TITLE
CoreGx Package Submission

### ISSUE THREAD

**Issue by ChristopherEeles** [Bioconductor/Contributions#1445]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/CoreGx

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ChristopherEeles** [comment]
Hi @nturaga,

I am not receiving build reports for my recent commits. Also bioc-issue-bot is opening two issues per commit.

Could be a problem with bioc-issue-bot?

Please advise.

**Comment by nturaga** [comment]
Are you bumping the version number each time?

**Comment by ChristopherEeles** [comment]
@nturaga 
> Are you bumping the version number each time?

Yes. I even did an arbitray bump to retrigger the build on your servers. I get the 'valid push; starting build' comment and email, but no build report is ever posted.

**Comment by nturaga** [comment]
Try to reenable your hook

**Comment by ChristopherEeles** [comment]
@nturaga,

I deleted and reset the webhook, after which I immediately got a build report posted here. 

However, on pushing another update same issue is occurring:
- I get two emails regarding 'valid push; starting build' for a single commit id
- I wait but no build report is posted (it's been 40 minutes now)

I also tried deleting the webhook again, but this time it did not result in a build report being returned.

Build:
- Warning on imalbec2 is just for R dependencies. I do have compressed data in the package so the dependency is necessary. Otherwise no errors/warnings
- Error on tokay2 looks like an issue with installing a dependency on the server; I can successfully build the package on my local Windows 10 laptop and thus cannot recplicate the error.

**Comment by ChristopherEeles** [comment]
@nturaga,

Build:
- Warning on malbec2 is just for R dependency. I do have compressed data in the package so the dependency is necessary. Otherwise no errors/warnings.
- Error on tokay2 looks like an issue with installing a dependency (graphics-de) on the server; I can successfully build the package on my local Windows 10 laptop and thus cannot replicate the error.

Please advise.

**Comment by ChristopherEeles** [comment]
AdditionalPackage: https://github.com/bhklab/RadioGx

**Comment by ChristopherEeles** [comment]
@nturaga,

RadioGx:
- The only warning is for R >= 4.0 dependency, which is required to load compressed data in the package.

**Comment by ChristopherEeles** [comment]
@nturaga 

CoreGx & RadioGx passing on both platform:
- A single warning is raised due to R >= 4.0 dependency; there is compressed data in both packages so the dependency is needed

I will be submitting one more additional package tomorrow which also depends on CoreGx.

**Comment by ChristopherEeles** [comment]
Just cleaning up ToxicoGx package to pass BiocCheck; will add as an additional package tomorrow.

**Comment by ChristopherEeles** [comment]
AdditionalPackage: https://github.com/bhklab/ToxicoGx

**Comment by ChristopherEeles** [comment]
@nturaga 

CoreGx [main], RadioGx [additional], ToxicoGx [additional] now pass checks on tokay2 and malbec2:
- Only warning can be ignored due to inclusion of compressed data in all packages:
  "* Checking R Version dependency...
    * WARNING: Unless package includes compressed data, remove R
      version dependency."

Please update tags to OK or advise on next steps to continue the submission process.

**Comment by ChristopherEeles** [comment]
> 
> 
> @nturaga
> 
> CoreGx [main], RadioGx [additional], ToxicoGx [additional] now pass checks on tokay2 and malbec2:
> 
>     * Only warning can be ignored due to inclusion of compressed data in all packages:
>       "* Checking R Version dependency...
>       
>       * WARNING: Unless package includes compressed data, remove R
>         version dependency."
> 
> 
> Please update tags to OK or advise on next steps to continue the submission process.

@nturaga 

Still no reply? Please advise what you need from me to proceed with this submission.

**Comment by nturaga** [comment]
I will review your package soon.

**Comment by p-smirnov** [comment]
@nturaga do you have a timeline for review? The acceptance of CoreGx into devel is required for updates which we want to make to existing Bioconductor Package `PharmacoGx`. We are concerned about having enough time to push the changes to PharmacoGx to devel and make sure it builds without errors for next release.

**Comment by p-smirnov** [comment]
Build on Tokay2 is failing due to inability to find `igraph` today. Weird as it is listed as already installed on Tokay 2 as of [yesterday's build reports](http://bioconductor.org/checkResults/3.11/bioc-LATEST/tokay2-R-instpkgs.html)

**Comment by ChristopherEeles** [comment]
^ CoreGx passing checks with no errors or warnings

**Comment by ChristopherEeles** [comment]
^ RadioGx passing checks with no errors or warnings

**Comment by ChristopherEeles** [comment]
^ ToxicoGx passing checks with no errors or warnings

NOTE: Warning tag added with no warnings in build report?

**Comment by ChristopherEeles** [comment]
^ ToxicoGx passing checks with no errors or warnings.

NOTE: Still a warning tag despite no warnings in build report?

**Comment by nturaga** [comment]
# Review CoreGX

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## NEWS

* If you intend the NEWS file to be part of package make sure it's
  parseable by utils::news().

## R

* In the `CoreSet` function, you can use the accessor methods you
  wrote, or write more if needed instead of direct slot access with `@`.
  
  http://bioconductor.org/developers/how-to/efficient-code/
  
  Do this everywhere there is slot access used directly, even in the
  private functions.

* In `connectivityScore`, what is the point of allowing for the method
  `gsea`? It is not used anyway.
  
* Instead of `mclapply` in `parallel` use BiocParallel's parallel
  functionality. 
  
* Please consider fixing the code which has comments like below, (or
  should either be removed, as they don't inspire confidence in
  reviewer). Consider removing all commented out code if you deem it
  not necessary.

```
## NOTE:: THIS FORMULA CAN SUFFER CATASTROPHIC CANCELATION AND SHOULD BE FIXED!
```

* A word about the coding style, from a reviewers stand point, it's
  impossible to make sense of code formated like this. Please consider
  fixing the formatting.

```
.mcc <- 
  function(ct, nbcat=nrow(ct)) {
    if(nrow(ct) != ncol(ct)) { stop("the confusion table should be square!") }
    if(!(sum(ct)==sum(diag(ct))) &&  (length(which(apply(ct, 1, sum) == 0)) == (nbcat-1) & ((length(which(apply(ct, 2, sum) == 0)) != (nbcat-1)) | (length(which(apply(ct, 2, sum) == 0)) == (nbcat-1)))) || (length(which(apply(ct, 2, sum) == 0)) == (nbcat-1) & ((length(which(apply(ct, 1, sum) == 0)) != (nbcat-1)) | (length(which(apply(ct, 1, sum) == 0)) == (nbcat-1)) & sum(diag(ct)) == 0))) { ct <- ct + matrix(1, ncol=nbcat, nrow=nbcat) } ### add element to categories if nbcat-1 predictive categories do not contain elements. Not in case where all are correct!
```

http://bioconductor.org/developers/how-to/coding-style/

* I'm not sure why you are using `testthat::expect_true()` in utility
  functions. Use the package `assertthat` instead. Or write test cases
  with testthat.
  
  Any reason why your tests are in the utilities.R?

## vignette

* Consider using BiocStyle

## man

ok

# Review RadioGx

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## NEWS

* Same comments as for CoreGx.

## R

* If the comments passed on CoreGx apply to this package, please fix
  them as well.

* End user messages should be used in this way, please use `message()`
  instead of `print()` where you need to. And follow the guidelines
  below.

```
message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.

warning() communicates unusual situations handled by your code.

stop() indicates an error condition.

cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```

* Remove commented out code.

* REQUIREMENT: Coding style should be fixed. This is important for 2
  reasons,

	1. We are expected to read your code as closely as possible. It
       would be a lot easier and faster if the code was formatted in a
       readable way. (ie indentation, line wrapping, tabs vs spaces,
       commented out code play a huge part in readability when you are
       submitting a large code base [3 packages]).
	   
	2. When you have to fix bugs 2-3 releases down the line, you'll
       have to read your code again. The coding style should not be
       taken lightly and you should follow the best practices we
       provide.

* Accessor methods need to be written. No direct slot access.

* Use the package "matrixStats" to calculate `rowMeans`, `rowMedians`
  etc. These are highly optimized functions and run faster than
  `apply` functions.

* Again not sure why test cases are written in `utilities.R`.

## vignette

* Vignette doesn't explain each of the exported functions and how to
  use them. I did see the comment below stating that more details in
  the coming months.

## man

* ok

**Comment by nturaga** [comment]
Checkout the https://github.com/r-lib/styler or `formatR` package.

**Comment by ChristopherEeles** [comment]
@nturaga 

^ CoreGx rebuild with no errors or warnings

NEWS: I was able to parse the news file after installing the package using utils::news(); please let me know if this is not what you meant

R:
- CoreSet: updated constructor to use new accessor functions instead of @; also corrected in other parts of the package
- Connectivity Score: removed the "gsea' argument and added an error to notify users of the parameter change
- mclapply: Swapped in bplapply as per request
- CATASTROPHIC FAILURE: removed this comment and the commented out code
- .mcc: Rewrote the function to be cleaner; generally plan to improve coding style over the coming months
- Removed testthat usage from utitlites

vignette:
- Switched to BiocStyle

**Comment by ChristopherEeles** [comment]
@nturaga 

NEWS: I updated the news file to display without warnings, but for some reason, it didn't make it through my merge; I will update it to the working version on the next push

R:
-  RadioSet: I updated the constructor to be in line with CoreGx and reviewer comments
- Accessors: I wrote a number of new accessor methods to ensure we aren't using @ to get data from our slots 
  - the generics for these are currently defined in RadioGx, but will be moved to CoreGx for the next push (after next round of feedback)
  - In utilities.R there are some accesses using @ due to the fact that we are comparing an older version of the RadioSet class with the new one; we have already removed accessor methods for the old version
    - The purpose of the .validateRsetMolecu... function is to ensure that no information was lost from our curated objects as we transition from ExpressionSets to SummarizedExperiemnts; this function will be removed in future releases.
- mclapply: Swapped in bplapply as per request
- Commented out code: I believe I have removed all commented out code and hope it improves readability
- Coding style: I realize that some of our functions are hard to read, we are in the process of refactoring all four packages (CoreGx, PharmacoGx, RadioGx, ToxicoGx) and plan to get the codebase in shape within a month or two. Until then please let me know if there are any style issues I should address immediately 
- formatR: I ran it over our codebase for RadioGx but it broke some stuff and in general seemed to decrease readability. As we refactor our code we plan to ensure all variables and functions have descriptive names; we also intend to factor our large functions into manageable units but it will take some time
- Removed testthat usage from utitlites
- matrixStats: I changed the apply statements to use rowMeans/Medians and colMeans/Medians as per request; there are also some sapply's I could change because the return type is not clear - this will be addressed the upcoming refactor

vignette:
- Switched to BiocStyle
- In terms of updating the vignette we agree that a detailed vignette is needed and will attempt to put this together in the next month

**Comment by ChristopherEeles** [comment]
@nturaga 

Our current Bioconductor package PharmacoGx has significant updates that depend on CoreGx. Since we removed it from CRAN for this submission, we are unable to update the package until CoreGx is available on Bioconductor. 

Given it is the last day for package acceptance is there any chance to expedite acceptance of CoreGx? We put a lot of effort into the PharmacoGx changes and would very much like them to be available in this release.

If it means resubmitting RadioGx and ToxicoGx separately that is acceptable.

Thanks either way.

**Comment by nturaga** [comment]
> @nturaga
> 
> Our current Bioconductor package PharmacoGx has significant updates that depend on CoreGx. Since we removed it from CRAN for this submission, we are unable to update the package until CoreGx is available on Bioconductor.
> 
> Given it is the last day for package acceptance is there any chance to expedite acceptance of CoreGx? We put a lot of effort into the PharmacoGx changes and would very much like them to be available in this release.
> 
> If it means resubmitting RadioGx and ToxicoGx separately that is acceptable.
> 
> Thanks either way.

Hi, Let's do that. Let's get the review of CoreGx in and keep ToxicoGx and RadioGx seperate. That way, you can meet your urgency for the PharmacoGx package. 

I'll only review CoreGx now.

**Comment by ChristopherEeles** [comment]
> Hi, Let's do that. Let's get the review of CoreGx in and keep ToxicoGx and RadioGx seperate. That way, you can meet your urgency for the PharmacoGx package.
> 
> I'll only review CoreGx now.

I really appreciate it. Should we resubmit ToxicoGx/RadioGx as separate issues or will we just continue here later?

**Comment by nturaga** [comment]
> > Hi, Let's do that. Let's get the review of CoreGx in and keep ToxicoGx and RadioGx seperate. That way, you can meet your urgency for the PharmacoGx package.
> > I'll only review CoreGx now.
> 
> I really appreciate it. Should we resubmit ToxicoGx/RadioGx as separate issues or will we just continue here later?

Just delete the comments which add ToxicoGx and RadioGx as additional packages. And submit them as seperate issues. 

I'll review CoreGx and try to get it to you as soon as possible.

**Comment by nturaga** [comment]
Hi @ChristopherEeles ,

I'm ok accepting the package for now since there is a time crunch. I have to point out a few things and insist you do them. 

1. Improve the vignette. The fact that you are just pointing people to 3 other packages, doesn't really help them. Especially if they are all them are related. Try to improve it just enough so that they have a sense of how CoreGx helps the other 3 packages.

2. Write test cases, because this package lays a foundation for your other packages. Failure here could trickle down into other packages. 

I will accept this package now, but please make these improvements ASAP.

**Comment by ChristopherEeles** [comment]
> Hi @ChristopherEeles ,
> 
> I'm ok accepting the package for now since there is a time crunch. I have to point out a few things and insist you do them.
> 
>     1. Improve the vignette. The fact that you are just pointing people to 3 other packages, doesn't really help them. Especially if they are all them are related. Try to improve it just enough so that they have a sense of how CoreGx helps the other 3 packages.
> 
>     2. Write test cases, because this package lays a foundation for your other packages. Failure here could trickle down into other packages.
> 
> 
> Please make these improvements ASAP.

Thanks, Nitesh! I will improve the vignette by the end of next week. As for unit tests, we already have a bunch written that we can migrate from PharmacoGx. Our goal will be to hit 90% coverage for all three packages before the next Bioconductor release.

How long until CoreGx will be available as a dependency? Will it be today or tomorrow?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ChristopherEeles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CoreGx")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CoreGx

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
