### ISSUE TITLE
MatrixGenerics

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/Contributions#1448]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/MatrixGenerics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by PeteHaitch** [comment]
We've discussed this package a bit over the years and it's thanks to @const-ae we've got something concrete to submit :tada: 

I think the aim will be for [**DelayedMatrixStats**](https://github.com/PeteHaitch/DelayedMatrixStats) to depend on **MatrixGenerics** in the next release (I've got a branch ready to go; https://github.com/PeteHaitch/DelayedMatrixStats/tree/MatrixGenerics).
Ultimately, I think it may be best to deprecate **DelayedMatrixStats** by incorporating it directly into **DelayedArray** (and perhaps **HDF5Array** if there are *HDF5Matrix*-specific methods).
@const-ae is also working on [**sparseMatrixStats**](https://github.com/const-ae/sparseMatrixStats) but I'm not sure I've left him enough time to have that prepared for the next release ...

Pinging @hpages who will likely want to run an eye over it, and @HenrikBengtsson since this builds on **matrixStats**.

**Comment by PeteHaitch** [comment]
In the `DESCRIPTION` we have:
```
biocViews: Infrastructure, Software
```
Because it's an 'infrastructure' package I think this should mean that a vignette is not required.
Indeed, in the [build report](http://bioconductor.org/spb_reports/MatrixGenerics_buildreport_20200401082142.html) we see:

```
* Checking vignette directory...
    This is a software package
  Infrastructure package, vignette not required.
```
But then we immediately get an `ERROR`:

```
* Checking whether vignette is built with 'R CMD build'...
    * ERROR: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.
```
And so the build fails.

Should we only have 
```
biocViews: Infrastructure
```
in the `DESCRIPTION`?

**Comment by lshep** [comment]
Probably needs an adjustment in BiocCheck -- can you open an issue there for me to look into it?  @dvantwisk  ignore the vignette ERROR for now.

**Comment by dvantwisk** [comment]
I'll have a review of this package done soon.

**Comment by PeteHaitch** [comment]
👋@dvantwisk - I totally understand that you're all busy right now, just wanted to make a gentle inquiry about the review status here given that the deadline is approaching. Thanks!
The current build error is due to a false-positive in BiocCheck, I believe.

**Comment by dvantwisk** [comment]
Hi,

I apologize or the delay. I've reviewed your package and I am happy to say that I don't have anything significant to add to it. It is very well written as is and I will accept it as is.

**Comment by PeteHaitch** [comment]
No worries at all, @dvantwisk, I appreciate how busy you must be.
Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PeteHaitch.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MatrixGenerics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MatrixGenerics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
