### ISSUE TITLE
OpenStats

### ISSUE THREAD

**Issue by Hamedhm** [Bioconductor/Contributions#1451]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mpi2/OpenStats

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
clarify, in the DESCRIPTION file Description: field, what is meant by 'phenotypic data'.

**Comment by Hamedhm** [comment]
Thanks @mtmorgan. It should be improved now. Thanks.

**Comment by Hamedhm** [comment]
@lshep do I need to take any step for the package to be recompiled by bioconductor?

**Comment by lshep** [comment]
It should be recompiled automatically upon rebuild

**Comment by Hamedhm** [comment]
@lshep thanks

**Comment by Hamedhm** [comment]
@lshep I keep getting the following error 
!   The file name record could not be found in the database.

please can you advise?

**Comment by lshep** [comment]
Can you give me a little background  -- what database are you accessing? How are you accessing it?

**Comment by Hamedhm** [comment]
sorry @lshep for not being clear. The error is on the following page:
http://bioconductor.org/spb_reports/OpenStats_buildreport_20200401105035.html

===============================

 R CMD BUILD

===============================

* checking for file 'OpenStats/DESCRIPTION' ... OK
* preparing 'OpenStats':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'OpenStats.Rmd' using rmarkdown
! ERROR: The file name database is damaged.
! ERROR: Info: fileName="5f122386631f6ced396477a29d0f0cd8-le64.cache-7"
! ERROR: Source: Libraries\MiKTeX\Core\Fndb\FileNameDatabase.cpp
! ERROR: Line: 356

! ERROR: Info: fileName="5f122386631f6ced396477a29d0f0cd8-le64.cache-7"
! ERROR: Source: Libraries\MiKTeX\Core\Fndb\FileNameDatabase.cpp
! ERROR: Line: 356

! ERROR: Source: Libraries\MiKTeX\Core\Fndb\FileNameDatabase.cpp
! ERROR: Line: 356

! ERROR: Line: 356

! Sorry, but C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\pdflatex.exe did not succeed for the following reason:

!   The file name record could not be found in the database.

! Remedy:

!   Delete the file name database files. Then run 'initexmf -u' to recreate the FNDB.

! For more information, visit: https://miktex.org/kb/fix-fndb-damaged

Error: processing vignette 'OpenStats.Rmd' failed with diagnostics:
LaTeX failed to compile C:/Users/pkgbuild/AppData/Local/Temp/RtmpeiqFSy/Rbuild24fc49ba79f2/OpenStats/vignettes/OpenStats.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See OpenStats.log for more info.
--- failed re-building 'OpenStats.Rmd'

SUMMARY: processing the following file failed:
  'OpenStats.Rmd'

Error: Vignette re-building failed.
Execution halted

**Comment by lshep** [comment]
Yes I get that -- Do you know how the file it references is created or accessed?

**Comment by Hamedhm** [comment]
No, I have included a normal rmd file in the package that compiles on my PC without any error.  I think this error is internal to MikTex

**Comment by lshep** [comment]
ok.  I'll look into it later this afternoon.

**Comment by Hamedhm** [comment]
@lshep Thanks a lot

**Comment by Hamedhm** [comment]
@lshep  Good morning. Please can you kindly let me know when the reviewing step start?

**Comment by lshep** [comment]
I am in the process of reviewing your package this morning and should have more comments shortly. Cheers

**Comment by Hamedhm** [comment]
@lshep  Thank you very much.

**Comment by lshep** [comment]
Thank you for your submission.  Please see the following initial comments: 

**Major concern**

- [ ] Biggest concern after vignette: You don't incorporate any standard Bioconductor structures for data analysis. The ability for functions to interact with other Bioconductor objects highly utilized in the Bioconductor community is generally a requirement. It seems like your functions should minimally be able to take in a SummarizedExperiment object. 
  Update after man pages: seems you can use PhenList from PhenStat but you don't display that anywhere. It is still recommended to have a way to interact with the hightly used SummarizedExperiemnt object. 

- [ ] S4 classes are recommended over S3. S4 classes have more defined structures and can be extended. This is where it would have been better to extended the PhenList class rather than define   new highly overlapped and highly similar structure. 

- [ ] How is this different than PhenStat?  Is this meant to be an extension or a replacement? I see you are the maintainer of the other package, the descriptions are the same.  What makes this unique? 


**Build Report**

- [ ] Fix coding practices
    + use of sapply vs vapply
    + avoid use of 1...

- [ ] Use of <<- in nmain.R needs to be justified as it is not encouraged and  generally not good practice to do. I'm not sure where this is utilized and quite honestly its very hard to try and understand your code in its current format and complexity.  Please explain the use. 

- [ ] We strongly recommend unit tests. Many developers not only use them to test correct package functionality but can find it useful for development as well. 

**Description**

- [ ] @mtmorgan already made the comment:  DESCRIPTION file Description: field, what is meant by 'phenotypic data'. Expand the Description to be more informative. 

- [ ] Please remove `Repository: CRAN` field. not needed 

- [ ] We also recommend removing `LazyData: true` we have rarely found this useful and have found it can actually slow installation. 

- [ ] Please remove manual Date field in the description. This is captured in other places and often gets out-dated


**Namespace**

- [ ] remove commented out imports


**inst**

- [ ] Include an inst/scripts directory that has a file describing the ata in inst/extdata.  Ideally code but could be sudo code or text description but should include relevant source/reference information and any sort of processing or subsetting. 

- [ ] NEWS file is not formated correctly.  Please review `?news`.  In R you should be able to run the following and have it display correctly `tools:::.news_reader_default("NEWS")`

**vignette**

- [ ] Only one vignette format.  Please remove  OpenStats.Rnw\_ and keep OpenStats.Rmd

- [ ] Don't keep repeating your calls and recreating your list object.  You run it in section 0.2 twice, then again in 0.2.1.  Create the object and use it throughout the vignette.  You don't need to keep calling `library(OpenStats)` either. Once a variable is defined once you don't have to keep redefining unless the arguments to the function changed.

- [ ] I suggest having a print method for your object.  It can do the same thing as summary or print even just that its an object of your class but it is very intuitive for a user to type the name of an object created which currently prints all the data in a not so nice format. 

- [ ] Fix spacing in code.  I currently cannot cut and paste because of the spaces in 0.2.1.  

- [ ] I'm not sure how you are plotting or defining plotting regions but if I run your plot call in 0.2.1,  the scatter plot is never shown because there is only one plot window. I only see the histogram like plot. 

- [ ] Why does the function only run correctly if you load the library nlme explicitly? If the library isn't loaded and you run your function

```
> MM_result
$messages
[1] "This process fully terminated. No success in recovering the initial model."

```
It seems like a `require` in the code to make sure the package is installed would be necessary then. 

- [ ] Again have a print and summary method for the resulting object from running OpenStatsAnalysis.  There should be both summary and print methods (even if they do the same thing) 

- [ ] reiterating if you already have the code defined in a previous section (like defining fileCon) dont keep repeating the code to execute in the vignette. Once is enough. 

- [ ] After you run Spliteffect, the resulting object is a list. You took the time to create the classes for the other results but not this one?  The summary of this object seems less than helpful given the explanation of what is does. Generally functions like this benefit from being endomorphic (object
  you put in is object you get out)

- [ ] Fix spaces in code in 0.4.4 . Again can't copy and paste because of spaces. 

- [ ] You describe briefly what the object holds.  Is there useful access methods for what would be of frequent interest for additional analysis or additional functions for discovery what is in your objects? 

- [ ] In 0.6 again remove extra spaces so can copy and paste code. 

- [ ] Minimally your functions should be able to take a SummarizedExperiment object as input as well as a generic matrix of data,  as that is the standard Bioconductor structure for genotypic data with accompanied phenotype data.   

**General comment**

- [ ] Your Rd and R files are incredibly hard to read because of the spacing inconsistency. Please consider using formatR or doing some format clean up on your files. 

**man pages**

- [ ] No need to put library in the examples of the man pages. The package would already be loaded to view the man page. 

_OpenStatsAnalysis_

- [ ] Apparently incomplete. As you have a comment to include alias

- [ ] Check spacing. If you do `?OpenStatsAnalysis` the spacing you have put in isn't really consistent. Remove spacing especially in usage section.

- [ ] Is the default method if unspecified MM or does the user have to specify?


_OpenStatsBuilder_

- [ ]  Why don't you run the code in the example? the example should be run. At
  the very least, donttest instead of dontrun should be used as donttest
  requires valid R code. But the code should be executed or justified the reason
  for not running.  Perhpas only put the plotting call in donttest. 

 _OpenStatsComplementarySplit_

- [ ] Typo in values section. `Life of` should be `List of` 
- [ ] How do you get meaningful data from this results object? 


_plot.OpenStats_

- [ ] Describe what plots are created.

_summary.OpenStats_

- [ ] Describe the summary statistics displayed


**R code**

- [ ] Consider reformatting code spacing so its readable and consistent. Honestly I can't really review it in its current state because of formatting and amount.  I would be lenient, just fixing the coding issues identified in the build report and allowing for the use of a standard Bioconductor SummarizedExperiment Object.  If you plan on developing outward (like it appears you are doing from PhenStat), I would highly suggest looking into S4 classes as well but understand that that may be too big of an undertaking at the current time.  


Please address the above issues. When ready ensure to do a version bump to kick off a new build. When ready for re-review please post back here along with a summary of updates and any comments to questions posed above. 

Cheers.  Look forward to getting your package into Bioconductor.

**Comment by Hamedhm** [comment]
@lshep  Thank you very much for reviewing OpenStats package. Please see below the comments and the corresponding changes/comments to the R package. Please feel free to share me your further concerns.

Major concern
 
*  [x]  Biggest concern after vignette: You don't incorporate any standard Bioconductor structures for data analysis. The ability for functions to interact with other Bioconductor objects highly utilized in the Bioconductor community is generally a requirement. It seems like your functions should minimally be able to take in a SummarizedExperiment object.
 Update after man pages: seems you can use PhenList from PhenStat but you don't display that anywhere. It is still recommended to have a way to interact with the highly used SummarizedExperiemnt object.
     - Some notes added to the man page of OpenStatsList and OpenStatsAnalysis, (OpenStatsList.Rd)"OpenStats allows a `data.frame` for the input data. This data.frame can be formed from CSV, TSV, TXT etc. files and is organised with rows and columns for samples and features respectively.  This allows a wide range of integration with other Bioconductor/CRAN packages, for instance, the output of Bioconductor `SummarizedExperiment` package can be transformed and fed into OpenStats (note that SummarizedExperiment allows sample in columns and feature in rows that requires at least a transpose operation). Additionally, Bioconductor `PhenStat` function `PhenList` produces very similar results to `OpenStatsList` that allows direct processing of the `PhenList` object by downstream OpenStats operational functions.". (OpenStatsAnalysis.Rd - arguments/OpenStatsListObject) "mandatory argument. An instance of the 'OpenStatsList' or 'PhenList' (former from the Bioconductor `PhenStat` package)." 


 * [x] S4 classes are recommended over S3. S4 classes have more defined structures and can be extended. This is where it would have been better to extend the PhenList class rather than define a new highly overlapped and highly similar structure.
    - We are planning to retire PhenStat soon. As a result, we realised that it may be safer to redefine/extend the object in the new software. We will improve and transform from S3 objects in future releases.

 * [x] How is this different than PhenStat? Is this meant to be an extension or a replacement? I see you are the maintainer of the other package, the descriptions are the same. What makes this unique?
     - OpenStats is the replacement for PhenStat. It allows custom modelling (where the name OpenStats come from) of the data in a much faster fashion than PhenStat (manuscript in progress). Moreover, we addressed some major concerns with PhenStat that over time we realised that are important for the scientific community. Moreover, PhenStat is specifically designed for the Internation Mouse Phenotyping Consortium (IMPC) whereas OpenStats designed for the broader community. 

Build Report

*  [x] Fix coding practices
* use of sapply vs vapply
    - Did as much as possible (more than 50% replaced)
* avoid use of 1...
    - applied as much as possible. Only one remained that is a special case 
 * [x] Use of <<- in nmain.R needs to be justified as it is not encouraged and generally not good practice to do. I'm not sure where this is utilized and quite honestly it is very hard to try and understand your code in its current format and complexity. Please explain the use.
     - Removed

 * [x] We strongly recommend unit tests. Many developers not only use them to test correct package functionality but can find it useful for development as well.
    - UnitTests added.

Description

 * [x] @mtmorgan already made the comment: DESCRIPTION file Description: field, what is meant by 'phenotypic data'. Expand the Description to be more informative.
     - Reworded to: "Description: Package contains several methods for statistical analysis of genotype to phenotype association the high-throughput screening pipelines."

*  [x] Please remove Repository: CRAN field. not needed
     - done

 * [x] We also recommend removing LazyData: true we have rarely found this useful and have found it can actually slow installation.
     - done

 * [x] Please remove manual Date field in the description. This is captured in other places and often gets out-dated
      - done

Namespace

*  [x] remove commented out imports
    - done

inst

* [x] Include an inst/scripts directory that has a file describing the data in inst/extdata. Ideally, code but could be sudo code or text description but should include relevant source/reference information and any sort of processing or submitting.
    - a Readme.Rd with the description of the IMPC data access added

* [x] NEWS file is not formatted correctly. Please review ?news. In R you should be able to run the following and have it display correctly tools:::.news_reader_default("NEWS")
    - fixed

vignette

* [x] Only one vignette format. Please remove OpenStats.Rnw_ and keep OpenStats.Rmd
    - OpenStats.Rnw_ removed

* [ ] Don't keep repeating your calls and recreating your list object. You run it in section 0.2 twice, then again in 0.2.1. Create the object and use it throughout the vignette. You don't need to keep calling library(OpenStats) either. Once a variable is defined once you don't have to keep redefining unless the arguments to the function changed.
    - Thanks for the comment. The justification behind the inclusion of the whole call is to facilitate running the code without being confused about the source of the object (and jumping around the document).

* [x] I suggest having a print method for your object. It can do the same thing as summary or print even just that its an object of your class but it is very intuitive for a user to type the name of an object created which currently prints all the data in a not so nice format.
    - print function similar to the summary for all objects added+documentation

* [ ] Fix spacing in code. I currently cannot cut and paste because of the spaces in 0.2.1.
    - Thanks for the comment, I tried formatR but still cannot copy from the pdf file. Even I cannot copy a simple multiline code such as print(1:10); plot(1:10) from the pdf file. Not sure what can I do for this. Any suggestion welcome.

* [x] I'm not sure how you are plotting or defining plotting regions but if I run your plot call in 0.2.1, the scatter plot is never shown because there is only one plot window. I only see the histogram like plots.
    - Fixed in the vignette and in plot.OpenStatsList manual page (see the example/details)

 * [x] Why does the function only run correctly if you load the library nlme explicitly? If the library isn't loaded and you run your function
     - Fixed. Depends: nlme added to the DESCRIPTION

> MM_result
$messages
[1] "This process fully terminated. No success in recovering the initial model."

It seems like a requirement in the code to make sure the package is installed would be necessary then.

* [x] Again have a print and summary method for the resulting object from running OpenStatsAnalysis. There should be both summary and print methods (even if they do the same thing)
     - addressed 

* [x] reiterating if you already have the code defined in a previous section (like defining fileCon) don't keep repeating the code to execute in the vignette. Once is enough.
     - see above for justification

* [x] After you run Spliteffect, the resulting object is a list. You took the time to create the classes for the other results but not this one? The summary of this object seems less than helpful given the explanation of what is does. Generally functions like this benefit from being endomorphic (object
you put in is object you get out)
    - Summary, print & plot functions defined for the new object called "OpenStatsComplementarySplit"
* [x] Fix spaces in code in 0.4.4 . Again can't copy and paste because of spaces.
    - commented above

 * [x] You describe briefly what the object holds. Is there useful access methods for what would be of frequent interest for additional analysis or additional functions for discovery what is in your objects?
    - a detailed summary can be extracted from the output of OpenStatsReport. Note added to the OpenStatsAnalysis.Rd, "OpenStatsReport function can be used to extract the key elements of the analysis from the OpenStatsMM/FE/RR objects. The output from OpenStatsReport has schemed that makes it easy to be populated to the downstream processes such as storing and accessing results from a database."

* [x] In 0.6 again remove extra spaces so can copy and paste code.
    -  see comments above

* [x] Minimally your functions should be able to take a SummarizedExperiment object as input as well as a generic matrix of data, as that is the standard Bioconductor structure for genotypic data with accompanied phenotype data.
     - explanation added to the OpenStatsList function and other places.

General comment

 * [x] Your Rd and R files are incredibly hard to read because of the spacing inconsistency. Please consider using formatR or doing some format clean up on your files.
man pages
    - Thanks for the comment. I have fixed the spacing issue with the Rd files however not sure about the R files. I normally use Rstudio indentation formater but sometimes align the commas. I could do it for the review but for the maintenance of the package, I tend to keep the current format as it makes debugging much easier for me.

 * [x] No need to put library in the examples of the man pages. The package would already be loaded to view the man page.
    - library removed

* [x] Apparently incomplete. As you have a comment to include alias
     - fixed

* [x] Check spacing. If you do?OpenStatsAnalysis the spacing you have put in isn't really consistent. Remove spacing especially in usage section.
    - improved

* [x] Is the default method if unspecified MM or does the user have to specify?
     - added notes to the OpenStatsAnalysis man page. "Must be specified by the user. A character string ("MM", "FE" or "RR") defining the method to use for model building."

OpenStatsBuilder
- HAMED: note that this function is an internal function and not exposed to the end-user. I may remove it depends in future.

* [x] Why don't you run the code in the example? the example should be run. At
the very least, donttest instead of dontrun should be used as donttest
requires valid R code. But the code should be executed or justified the reason
for not running. Perhpas only put the plotting call in donttest.
    - The code changed to donttest
OpenStatsComplementarySplit

*  [x] Typo in values section. Life of should be List of
     - Corrected, thanks.
 * [x] How do you get meaningful data from this results object?
     - Example of summary/print & plot for the output object is added + some notes in the \value section

plot.OpenStats

*  [x] Describe what plots are created.
     - Notes added to the man page

summary.OpenStats

 * [x] Describe the summary statistics displayed
R code
    - notes added to all summary functions

 * [x] Consider reformatting code spacing so its readable and consistent. Honestly I can't really review it in its current state because of formatting and amount. I would be lenient, just fixing the coding issues identified in the build report and allowing for the use of a standard Bioconductor SummarizedExperiment Object. If you plan on developing outward (like it appears you are doing from PhenStat), I would highly suggest looking into S4 classes as well but understand that that may be too big of an undertaking at the current time.
    - Thanks for the comments. Sure I will gradually convert the S3 objects to S4 in future releases. See above for the spacing issue.

**Comment by lshep** [comment]
**General**

- [ ] So once this is accepted can we start the deprecation process for PhenStat (it would be deprecated in 3.12 to be removed in 3.13)

- [x] Please strongly consider a revamp of this package using S4 but for now okay. 


**Rd**

- [x] More of a keep in mind for yourself, if the goal is to retire PhenStat then you will need to update the sections that took short cuts to descriptions like "similar to `PhenList` object with an extra col"


**R code**

- [ ] someone recently mentioned using the package styler  https://github.com/r-lib/styler  that it might be easier to use.

**Comment by Hamedhm** [comment]
Thanks very much for reviewing @lshep 

> * [x]  So once this is accepted can we start the deprecation process for PhenStat (it would be deprecated in 3.12 to be removed in 3.13)
-    Not exactly right now as PhenStat is a high cited package in the literature and we should well advertise OpenStats before removing the package. I will be in touch, thanks a lot.
> * [x]  Please strongly consider a revamp of this package using S4 but for now okay.
-   Sure thanks.
> **Rd**
> 
> * [x]  More of a keep in mind for yourself, if the goal is to retire PhenStat then you will need to update the sections that took short cuts to descriptions like "similar to `PhenList` object with an extra col"
-   Very good point. Thanks for mentioning.
> **R code**
> 
> * [x]  someone recently mentioned using the package styler  https://github.com/r-lib/styler  that it might be easier to use.
-   What a great package. Thanks for mentioning. I have applied styler to all R codes, Rds and vignette/manual. It is a fantastic tool. Thanks

Thank you very much again for taking time reviewing OpenStats and great comments.

**Comment by Hamedhm** [comment]
@lshep  Thanks very much.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Hamedhm.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("OpenStats")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OpenStats

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
