### ISSUE TITLE
timeOmics

### ISSUE THREAD

**Issue by abodein** [Bioconductor/Contributions#1453]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/abodein/timeOmics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Looks like the DESCRIPTION file is incomplete. Please review ALL BIOCONDUCTOR PACKAGE REQUIREMENTS. Post a comment here tagging @mtmorgan when your package is ready for assignment to a reviewer..

**Comment by abodein** [comment]
My apologies @mtmorgan for the missing fields in the DESCRIPTION file.

**Comment by mtmorgan** [comment]
Continuation lines in the DESCRIPTION file need to be indented
```
Description: This is an amazing
    package doing amazing things
```
But please check your package locally
```
R CMD build TADCompare
R CMD check TADCompare_<x.y.z>.tar.gz
````
or similar before pushing commits.

**Comment by abodein** [comment]
Thank you @mtmorgan. It's fixed.

**Comment by mtmorgan** [comment]
I suggest removing the dependeincy and sticking with warning about R >= 3.5.0, since Bioconductor will not distribute your package on that platform.

**Comment by abodein** [comment]
Hi @mtmorgan , as you suggested, I have removed the `Depends: R (>= 4.0)` .
I still have WARNINGS about R dependency because of the compressed data `usethis::use_data()`.
I tried different compression method:

* `gzip` give me warnings in the **check**
```
checking data for ASCII and uncompressed saves ... WARNING

  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                        old_size new_size compress
  timeOmics.simdata.rda    679Kb     90Kb       xz
```
* `bzip2` or `xz` give me the same warning as before:
```
* checking data for ASCII and uncompressed saves ... WARNING
  Warning: package needs dependence on R (>= 2.10)
```
Could you please tell me how to use external data properly in Bioconductor?

Also, some new package contributions do have an R dependency. I'm a bit confused here.

Thanks for your answer.

**Comment by mtmorgan** [comment]
don't worry about it, ignore the warning.

**Comment by abodein** [comment]
OK thanks, what should I do next?

**Comment by mtmorgan** [comment]
Please revise your package in response to the issues below. When done, post a brief comment summarizing your response to each issue.

DESCRIPTION

- Please justify why you have chosen not to integrate your package with common Bioconductor data structures for representing genomic ranges, 'summarized' experiments, and perhaps 'MultiAssayExperiment'; see [common methods and classes][1]

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

vignette

- good!

R (please review all code for issues highlighted in the comments below)

- getCluster.R:63 it is a red flag to suppress messages and warnings, suggesting that you are relying on the warnings being uninformative to the user, and perhaps also that you have not sufficiently validated user data before invoking these functions.

- getCluster.R:47 it's usually better (avoiding duplication of objects) to construct an object once (include `dimnames=` in the call to `matrix()`) rather than to construct objects through sequential commands.

- getNcomp.R:83 rather than an extended `if () {} else if () {} ...` with long code blocks, it is usually better to write functions that handle each clause. Since the functions all perform the same operation, implement a generic and methods that dispatch on the class of `object`. The end result is more modular and extensible code, and a straight-forward implementation in the top-level function `silhouette.res = .getNcompImpl(object, ...)`.

- lmms.filter.lines.R:88 I'm not familiar with this object, but it is unfortuante if there are not 'accessor' functions rather than direct slot access (via `slot()`) for manipulating this object; if there _are_ accessor functions, then use those and avoid direct slot access.

- lmms.filter.lines.R:109 follow the convention of pipes split with one operation per line; this more clearly indicates the logical steps invovled, helps the reader focus on the operation being performed by each command, and avoids excessively long lines.

    ```
    result <-
        result %>%
        dplyr::left_join(...) %>%
        dplyr::mutate(...) ...
    ```

- utils.R: it is confusing to name functions with `.`-delimited names like `sd.new()`, especially when using S3 methods elsewhere in the package. Adopt a different convention `sdNew()`, `sd_new()` for plain-old functions.

man

- good

tests

- nice to see unit tests

**Comment by abodein** [comment]
Hi @mtmorgan,
Thanks for the review. I am currently responding to your observations, but I have a question about the first one.

*getCluster.R:63 it is a red flag to suppress messages and warnings, suggesting that you are relying on the warnings being uninformative to the user, and perhaps also that you have not sufficiently validated user data before invoking these functions.*


In this function, I generate random data to have different "mixOmics" objects for demo purposes.
Depending on the generated data, it's possible that the algorithm doesn't converge and thus produces a warning.
In the demo context, I would ignore this warning, that's why I used the `suppressWarning()`.
I could hard-code the object to remove the suppressWarning.

Should I ignore the comment or include another compressed data ?
What do you suggest ?

Thanks for your answer.

**Comment by mtmorgan** [comment]
I would move the message suppression from the the implementation of the function to the demo, with a user-visible comment on why the code chunk is wrapped in `suppressMessages()` etc.

**Comment by abodein** [comment]
Hi @mtmorgan,
Thank you for your review. In the last commit I have made the following changes.

### DESCRIPTION
* *Please justify why you have chosen not to integrate your package with common Bioconductor data structures for representing genomic ranges, 'summarized' experiments, and perhaps 'MultiAssayExperiment'*

This package is an extension of `mixOmics`, a Bioconductor package. Thus, I use the same type of object (data.frame, ...). It would be confusing for the users to use different object with similar methods.

### R
* *getCluster.R:63 it is a red flag to suppress messages and warnings, suggesting that you are relying on the warnings being uninformative to the user, and perhaps also that you have not sufficiently validated user data before invoking these functions.*

I removed `suppressWarnings()` from the function and instead I wrap it `demo <- suppressWarnings(get_demo_cluster())` and as suggested I add a note in the man to warn the user it can be produce warning but it is not important for the demo.

* *getCluster.R:47 it's usually better (avoiding duplication of objects) to construct an object once (include `dimnames=` in the call to `matrix()`) rather than to construct objects through sequential commands.*

I changed to use `matrix(..., dimnames=...)`.

* *`getNcomp.R:83` rather than an extended `if () {} else if () {} ...` with long code blocks, it is usually better to write functions that handle each clause. Since the functions all perform the same operation, implement a generic and methods that dispatch on the class of `object`. The end result is more modular and extensible code, and a straight-forward implementation in the top-level function `silhouette.res = .getNcompImpl(object, ...)`.*

As suggested, I changed the implementation to use generic instead.

* *lmms.filter.lines.R:88 I'm not familiar with this object, but it is unfortuante if there are not 'accessor' functions rather than direct slot access (via `slot()`) for manipulating this object; if there are accessor functions, then use those and avoid direct slot access.*

I double-checked, but the package doesn't seem to implement accessors yet.

* *lmms.filter.lines.R:109 follow the convention of pipes split with one operation per line; this more clearly indicates the logical steps invovled, helps the reader focus on the operation being performed by each command, and avoids excessively long lines.*

I changed the entire code to respect now the convention of pipes.

* utils.R: it is confusing to name functions with .-delimited names like `sd.new()`, especially when using S3 methods elsewhere in the package. Adopt a different convention `sdNew()`, `sd_new()` for plain-old functions.

I removed the dots in the name of each function in utils.R.

Thank you for your feedback

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/abodein.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("timeOmics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/timeOmics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
