### ISSUE TITLE
pipeComp

### ISSUE THREAD

**Issue by plger** [Bioconductor/Contributions#1457]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/plger/pipeComp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by plger** [comment]
Hi @nturaga 

thanks for taking up the review, and sorry for the several builds and errors. The last warning was about the R version dependency (I though I needed it due to the RData files), which I removed but somehow the new build appears to be still pending after 4 days... should I just wait or make a fake version bump push?

Some explanation for the other build/check notes:

- "clarifying how object(s) are initialized": the usual thing with ggplot `aes` variables;
- "Avoid 1:..." : these are all instances with hardcoded integers (e.g. `1:3`)
- The 2 `:::` are needed because some package functions using internals are exported to an object (`PipelineDefinition`) before being called.
- "Avoid sapply(); use vapply()" : guilty... shouldn't cause any issue; I'll try my best but unfortunately I doubt I manage to change all that and do proper testing again until the end of the review period.

In addition, you'll notice that the package is weird in that it contains R code in the `inst`; this is because we want to include the wrappers we used for all the methods, but if we were to include them as normal code we'd have to include all dependencies as well, which would be huge (and they're already not small). If you have a better suggestions about this, I'm totally open!

**Comment by plger** [comment]
Hi @nturaga 
As far as I'm concerned the pushed version is final, and documentation complete...
The windows-specific warnings I really can't fathom (they are related to basilisk, which I don't use, and appear to be encountered by other people), so I'm going to ignore them...
Pierre-Luc

**Comment by nturaga** [comment]
I'll take a look at your package in the next day.

**Comment by nturaga** [comment]
Hi @plger 

There are certain coding standards we are really particular about,

1. The sapply --> vapply. You need to use vapply as much as possible. `sapply` has a lot of unexpected consequences. 

2. Add a NEWS file. 

3. Don't worry about the windows issue for now, try to get it working on the Linux machine with as few NOTE(s) as possible.

I'll post a detailed review of your code in the next day.

**Comment by plger** [comment]
All sapply were changed to vapply, and I've added a news file...

**Comment by plger** [comment]
Hi @nturaga ,
it was quite a disappointment not to be included in the release, I'm not sure why...
I had addressed the things you pointed out, let me know what else needs to be done.
Pierre-Luc

**Comment by nturaga** [comment]
Hi,

I apologize for not being able to re-review your package before the release. But, please keep in mind that we are reviewing multiple packages and have other responsibilities as well. There is only so much time we can can allocate to reviewing packages.

I'll get to your package in the next week or so.

Best,

Nitesh

**Comment by plger** [comment]
@nturaga I can imagine the amount of work it is, and despite the disappointment I'm grateful for the commitment ;)
Now I guess there's no rush on this...
Pierre-Luc

**Comment by nturaga** [comment]
# pipeComp review

## DESCRIPTION

* ok

## NAMESPACE

* ok

## General

* It is in your best interest to address as many of the NOTE(s) as
  possible in the build report. Please bump the version so you can
  address as many of the NOTE(s) as possible.

* Check your coding style as well, (4 spaces instead of 2 for
  indentation). These are checks in the build report which the package
  builder is looking for.

* Test cases are highly encouraged. 

## R

* Do not use direct slot access in your classes. Write accessor
  methods instead of using `@` directly. Do this everywhere in your
  code base.

  Please review, http://bioconductor.org/developers/how-to/efficient-code/

```
   Accessors (simple functions that return components of your object)
   rather than direct slot access (using @) help to isolate the
   implementation of your class from its interface. Generally @ should
   only be used in an accessor, all other code should use the
   accessor. The accessor does not need to be exported from the class if
   the user has no need or business accessing parts of your data
   object. Plain-old-functions (rather than generic + method) are often
   sufficient for accessors; it’s often useful to employ (consistently) a
   lightweight name mangling scheme (e.g., starting the accessor method
   name with a 2 or 3 letter acronym for your package) to avoid name
   collisions between similarly named functions in other packages.
 ```

* You use some functions which essentially do the same thing, `rbind`
  and `bind_rows`. You are introducing additional dependencies which
  are not needed.

**Comment by lshep** [comment]
Please do a version bump to ensure the build report is from the latest version of the package.

**Comment by plger** [comment]
Hi @nturaga ,

all `@` were replaced by accessors except in the getter/setters themselves and the object construction/validation functions (all in `PipelineDefinition.R`).

I got rid of some notes, and tabs were was standardized to 2 spaces. In case of wrapped lines, however, indentation was not set to multiples of 2 in order to maintain alignment across lines.

Regarding this point:

> You use some functions which essentially do the same thing, `rbind` and `bind_rows`. You are introducing additional dependencies which are not needed.

I disagree that they do the same thing: beside the difference in performance, I generally use `bind_rows` with the `.id` argument. I can write my own `bind_rows` that does the equivalent, it just seems redundant (given that `dplyr` isn't an obscure package that nobody has), but if you think this is preferable I can do so, let me know what you think. In the meantime, though, I've managed to get rid of the `data.table` dependency at virtually no cost in performance.

**Comment by plger** [comment]
Same windows-specific timeout, that's odd:
```
* checking PDF version of manual ... ERROR
TIMEOUT: R CMD check exceeded 25 mins
```
I've seen some others discussing a windows-specific timeouts in the slack, don't know if it's the same issue...

**Comment by nturaga** [comment]
Hi @plger ,

Please issue a version bump. I will accept your package if it passes everything with an OK.

Best,

Nitesh

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/plger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pipeComp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pipeComp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by plger** [comment]
@nturaga @mtmorgan 
There's something odd about how this package was added to Bioc:

The link
https://bioconductor.org/packages/pipeComp
does not work, nor does this one:
https://bioconductor.org/packages/devel/bioc/html/pipeComp.html
However when you search the name of the package, you can find all the vignettes:
https://bioconductor.org/help/search/index.html?q=pipeComp/
e.g.
https://bioconductor.org/packages/devel/bioc/vignettes/pipeComp/inst/doc/pipeComp.html

Is this normal?

**Comment by lshep** [comment]
The package was built and processed and can be found on the build report http://bioconductor.org/checkResults/3.12/bioc-LATEST/ .  We had some internal issues with our website this week that prevent it from updating.  We are working on a fix that should be implemented by the end of the day today.  Once this is fixed, your package landing page should be visible.

**Comment by plger** [comment]
Ok, thanks a lot for the info!
