### ISSUE TITLE
distinct

### ISSUE THREAD

**Issue by SimoneTiberi** [Bioconductor/Contributions#1458]
- Repository: https://github.com/SimoneTiberi/distinct

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by SimoneTiberi** [comment]
Hi,
we're still working on the package (e.g., README, vignette and examples are missing).
Within the next few days we'll complete it, and I'll post an update here.

Simone

**Comment by SimoneTiberi** [comment]
Ok, package ready to be reviewed.
Thanks.

**Comment by mtmorgan** [comment]
@lshep I think the contributor changed the name of the repository from 'discerner' to 'distinct', and this is messing up our database?

**Comment by SimoneTiberi** [comment]
Yes exactly (I wrote it above).
I can re-submit a new issue with the new name if this simplifies things for you.

**Comment by lshep** [comment]
Opening a new issue is not necessary.  I changed the name in our database.  I have manually kicked off a build that you should receive shortly.  Please remember to set up your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)  on the repository so that it will get new build reports generated automatically on version bump.

**Comment by SimoneTiberi** [comment]
Ok, Thanks!
Yeah I already set up the webhook.

**Comment by SimoneTiberi** [comment]
Dear Martin @mtmorgan ,
a quick note to say that the package is ready to be reviewed.

Have a good day,
Simone

**Comment by mtmorgan** [comment]
Please update your package in response to the following comments. When complete, please post a brief comment summarizing the changes made.

DESCRIPTION

- Please provide a more extensive Description of what your package does, to provide potential users with insight into when they might choose it over other available implementations.

vignettes

- consider expanding the vignette to provide the user with more guidance on what the 'example data' should contain, and how to interpret the output of your calculations and visualizations.

R

- distinct_test.R:60 for each function exported to the user, start the function by validating input, using `stopifnot()` for simple tests, e.g.,

  ```
  stopifnot(
      is.character(name_assays_expression), length(name_assays_expression) == 1L,
      is.character(name_cluster), length(name_cluster) == 1L,
      ...
  )
  ```

src

- I was surprised to see `symbols.rds` in this directory?

- Much of your C++ code seems like standard vector manipulations that are handled efficiently (when implemented using vectorized operations, not iterations) at the R level, and I wonder why you chose to implement these in C++?

**Comment by SimoneTiberi** [comment]
Dear Martin @mtmorgan ,
Thanks for your feedback and for taking the time to look at our package.

We re-submitted our package (`distinct`, version  0.99.4) after implementing your corrections; in particular:
- we extended the description of the package in DESCRIPTION;
- we greatly edited and extended the vignettes;
- we added `stopifnot()` checks;
- we removed `symbols.rds` from src directory.

Concerning C++ code: we obtained a massive speed-up when translating our R (vectorized) code in C++; I don't remember the exact number, but we obtained at least a 10-20 time speed-up.

Let us know if you have further comments.

Best regards,
Simone

**Comment by SimoneTiberi** [comment]
Dear Martin @mtmorgan ,
Thanks for your feedback and for taking the time to look at our package.

We re-submitted our package (distinct, version 0.99.5) after implementing your corrections; in particular:

we extended the description of the package in DESCRIPTION;
we greatly edited and extended the vignettes;
we added stopifnot() checks;
we removed symbols.rds from src directory.
Concerning C++ code: we obtained a massive speed-up when translating our R (vectorized) code in C++; I don't remember the exact number, but we obtained at least a 10-20 time speed-up.

Let us know if you have further comments.

Best regards,
Simone

**Comment by SimoneTiberi** [comment]
Dear Martin @mtmorgan ,
Thanks for your feedback and for taking the time to look at our package.

We re-submitted our package (distinct, version 0.99.6) after implementing your corrections; in particular:

we extended the description of the package in DESCRIPTION;
we greatly edited and extended the vignettes;
we added stopifnot() checks;
we removed symbols.rds from src directory.
Concerning C++ code: we obtained a massive speed-up when translating our R (vectorized) code in C++; I don't remember the exact number, but we obtained at least a 10-20 time speed-up.

Let us know if you have further comments.

Best regards,
Simone

**Comment by SimoneTiberi** [comment]
Dear Martin @mtmorgan ,
Thanks for your feedback and for taking the time to look at our package.

We re-submitted our package (`distinct`, version 0.99.6) after implementing your corrections; in particular:

we extended the description of the package in DESCRIPTION;
we greatly edited and extended the vignettes;
we added stopifnot() checks;
we removed symbols.rds from src directory.
Concerning C++ code: we obtained a massive speed-up when translating our R (vectorized) code in C++; I don't remember the exact number, but we obtained at least a 10-20 time speed-up.

Let us know if you have further comments.

Best regards,
Simone

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SimoneTiberi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("distinct")`. The package 'landing page' will be created at

https://bioconductor.org/packages/distinct

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
