### ISSUE TITLE
MOMA

### ISSUE THREAD

**Issue by sunnyjones5** [Bioconductor/Contributions#1462]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/califano-lab/MOMA

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sunnyjones5** [comment]
Hi Reviewers,

This is just the data package for the vignette of the package 'MOMA' that I am also submitting. As per the directions on the contributions page I am not adding it until I receive the "review in progress" notification, but I just wanted to clarify.

Thanks,
Sunny

**Comment by sunnyjones5** [comment]
Hi the only error I still have left is that the package is too large (5.9 MB) but it's only a data package and I've tried to compress it as much as possible. Please let me know how to proceed.

**Comment by sunnyjones5** [comment]
This is official package I'm submitting

AdditionalPackage: https://github.com/califano-lab/MOMA

**Comment by LiNk-NY** [comment]
Hi Sunny Jones, @sunnyjones5 

Thank you for your submission. 
I have taken a look at your package. 
Please see the review below. 
If you have any questions, feel free to post them here. 

Best regards,
Marcel

---

# MOMA #1462

Thank you for your submission.

A few questions:

Is the `moma.gbmexample` package necessary?
Does it contain previously unpublished data?

If the data is just for the examples in the vignette, perhaps you can take a
subset of it so that you can provide a small representation in the `MOMA`
vignette without the introduction of a second package.

Other than the dependency on `ComplexHeatmap`, the author does not make use
of existing Bioconductor infrastructure.

## DESCRIPTION

* It looks good.
* Consider adding a `BugReports:` field in the `DESCRIPTION` file pointing to
the GitHub repository.
* Are the versions specified in the `Imports:` field really required? It may
be a little too restrictive.
* Only include `LazyData: true` if you have small manageable datasets.
* Respect the 80 character width limit (`biocViews:` & `Authors@R` fields).

## NAMESPACE

* Use a consistent naming convention. Either `snake_case` or `camelCase`.

## vignettes/

* Include an installation section that uses `BiocManager::install`
* The vignette is meant to show the functionality of the package and not really
a 'real-world' example although it could but usually real-world data is too
large for a package.
* The `gbm.example` is an unstructured list. Consider using something like a
`SummarizedExperiment` as input.
* Constructor functions are usually plain functions that filter the inputs and
ultimately call `new` to create a `MOMA` class object.
* The constructor should be the same name as the class (for example, "Moma").
* Usually, class names are capitalized (i.e., "Moma") though not required.
* With a proper structure, you can avoid operations like
`sapply(..., '[[', "reliability")` at the user level.
* Include a `sessionInfo()` section.

## R/

* Remove any mention of `set.seed` from within a function (even if it is a
comment)
* Do not use `print`
* Use `stop` to return an error
* Are many of the functions internal? I don't think I saw that they were
exported (e.g, in `diggit.r`) and they don't have an `@export` tag on them.
* Unexported helpers / utility functions should have a `@internal` tag.
* Avoid the use of `sapply` where possible
* Consider using `MultiAssayExperiment` for combining samples from different
assays (e.g., in `genomic.saturation.r`) and coordinating them.
* It's interesting that the class has `output.folder` slot. Could you make a
method that allows you to save whatever you need from the object?

**Comment by sunnyjones5** [comment]
Hi Marcel,

Thank you for your comments and review! I am currently communicating with the other builder of the package about the best way to move forwards with regards to your concerns about using the extra package for example data and best way to either restructure or shrink the size. But I did want to respond to confirm that I had seen your comments and that I am working on making the other improvements as per your concerns.

Also, more broadly to your question about it not directly interfacing with other Bioconductor infrastructure, while it doesn't directly use other data structures commonly used in Bioconductor we think the package would still be useful to other users in the community as the analysis is built on biology data frequently used by the Bioconductor community and in other packages (the original analysis coming out in a forthcoming paper used TCGA data but other multi-omic data could be used as well). Do you think it's still appropriate to to include this package in Bioconductor, or would other changes need to be made to make it a better fit? 

Best,
Sunny

**Comment by LiNk-NY** [comment]
Hi Sunny, @sunnyjones5

Is there infrastructure that you can use from `viper` to link to your package?
It seems like `viper` matrices are required for your package though the dependency is
not explicitly listed in the `DESCRIPTION` file.
Also, consider using `MultiAssayExperiment` for multi-omic data type handling and management.

<sup> (Disclaimer: I am the maintainer of `MultiAssayExperiment`) </sup>

Thanks Lori @lshep for identifying a potential dependency for the package.

Best,
Marcel

**Comment by sunnyjones5** [comment]
Hi Marcel,

While output from `viper` is required for the analysis those results can be generated separately and via a few different ways which is why I didn't make it a direct dependency, but I can either make it a dependency or suggested package to make their relationship more clear. The main output used is just the sample vs protein matrix so there isn't much more object infrastructure overlap that I could see being made. 

I will look more into the `MultiAssayExperiment` infrastructure in order to better understand how to make `MOMA` more compatible. 

Thanks,
Sunny

**Comment by sunnyjones5** [comment]
Hi Marcel,

Just an update that I've gone through and made most of the fixes to the package that you mentioned in the Description/Namespace/Vignette/R section. A few remarks about the things I am still working on and your other questions:

1. Size of the example dataset: currently creating a workable subset now and will remove the other package from submission. I will also improve the structure of the object.
2. Internal functions: yes most of the functions are internal and the main ones are run as methods in the Moma object. I've gone through and added the `internal` tag throughout to make it more clear
3. Constructor function: I'm not sure I understand your description of it as a "plain function that just filters input." Currently that's the main task of the function in that it checks that all the different inputs to the Moma object are in the correct format. I added some more comments/warnings in the code to make it more clear that that is what it was doing. Could you elaborate on this a bit more?
4. MultiAssayExperiment: I am looking more into this to see if I can adapt the code to interface with this data object style
5. Save method: I will implement a method in the Moma object that allows you to more flexibly save any of the outputs.

Thanks,
Sunny

**Comment by LiNk-NY** [comment]
Hi Sunny, @sunnyjones5 

I've updated the link to the repository in the initial comment and renamed the name of the issue. 
Thanks for working on a workable subset of data. 

3. Example constructor functions can be seen here: 

https://github.com/Bioconductor/SummarizedExperiment/blob/81d41a110c1115df6ad5b144c40e6d171ab13c2f/R/SummarizedExperiment-class.R#L80-L105

https://github.com/Bioconductor/RaggedExperiment/blob/a3d17eae741f8c27adc601c46dce8b2aab4e987c/R/RaggedExperiment-class.R#L115-L154

They take the input and then filter / coerce / pre-process etc. before creating the target class. 

5. It doesn't have to be a `save` method. It can be called something else but essentially it takes the data in your class and puts it into a file.

**Comment by sunnyjones5** [comment]
Hi Marcel @LiNk-NY ,

I've made all the changes that you recommended.  In particular:

1. I made the example dataset a `MultiAssayExperiment` object and made the constructor function compatible with both `MultiAssayExperiment` objects as well as named lists. 
2. I cleaned up the constructor function to be more streamlined. I moved some of the check functions to their own separate functions to make the constructor itself shorter. I still kept many of the error/warning messages so it would be clear to people what happened if they did enter something incorrectly.
3. I made a `saveData()` method in the `Moma` object where you can pass in any of the names of the results fields and save them as text files. 

Let me know if you think I should do anything else to make the package ready for publication!

(Note: On this [http://bioconductor.org/spb_reports/MOMA_buildreport_20200415142625.html](build report) I had a series of weird errors on the tokay2 build that had to do with base packages not loading. I wasn't sure how to fix that and so I just resubmitted the package again a few minutes later and the [http://bioconductor.org/spb_reports/MOMA_buildreport_20200415145255.html](build report) didn't have any errors cause it looks like it didn't run on tokay2. I'm guessing that's because of something on Bioconductor's end but I figured I would clarify what happened).

Thanks
Sunny

**Comment by LiNk-NY** [comment]
Hi Sunny, @sunnyjones5 
Thank you for making those changes. The package is looking better!

* I see that you reduced the strict version dependencies on packages. Good!
* Do you need to import `BiocManager`? If so, for what reason?
* Please find an alternative to `sink`. Perhaps `writeLines` can do the trick?
If the data has no structure, consider tidying it.
* Replace the user's options after changing them with `on.exit`
* For the convenience of your users, provide arguments to the `MomaConstructor`
that indicate the assay name for the datasets that you are interested in.
For example:
```r
MomaConstructor(..., viperAssay = "viper") {
    ...
    Moma$new(viper = x[[viperAssay]], ...)
}
```
this also allows you to have your own defaults.
* Remove redundant `Error: ` text from error messages. The `Error` keyword is already
included when calling `stop`.

Minor:
* Constructor functions are eponymous by convention although you can leave it
as-is (`MomaConstructor`) in the package.

Thank you!

**Comment by sunnyjones5** [comment]
Hi Marcel @LiNk-NY ,

Thanks for getting back to me! Regarding your remaining concerns:
1. I thought I needed to import `BiocManager` to facilitate installation of it as a Bioconductor package and to have the `install` section in the vignette. Without having it imported I get a note/error about using it in the vignette so I'm not sure I can take it out or how to properly do so?  
2. I took out the remaining redundant `error` and `warning` text from messages.
3. I changed the `MomaConstructor` inputs to allow that naming flexibility. 
4. Unfortunately for certain/most results data structures the lists are too nested for them to be written by `writeLines` or to be easily tidied. From my searching on this `sink` was the best option. Is there a reason I shouldn't use it? I could add in a note/warning that alerts people that it's the function that's going to be used? Alternatively I could have them save as `RData` files or some other format that maintains their list structure? Another option would be to go back to not having the `saveData` function and allow users to use the data as they see fit as the main outputs are the plots generated by the `makeSaturationPlots` function? I can send over pictures/or longer descriptions of the results data if that would help explain why attempting to tidy them would be pretty difficult. 
5. Is the `on.exit` thing you mentioned related to the print options I currently change in the `saveData()` method? 

Thanks,
Sunny

**Comment by LiNk-NY** [comment]
Hi Sunny,

> 1. I thought I needed to import `BiocManager` to facilitate installation of it as a Bioconductor package and to have the `install` section in the vignette. Without having it imported I get a note/error about using it in the vignette so I'm not sure I can take it out or how to properly do so?

You should not run code to install packages in the vignette. Please add an `eval = FALSE` to the chunk options. 

> 4. Unfortunately for certain/most results data structures the lists are too nested for them to be written by `writeLines` or to be easily tidied. From my searching on this `sink` was the best option. Is there a reason I shouldn't use it? I could add in a note/warning that alerts people that it's the function that's going to be used? Alternatively I could have them save as `RData` files or some other format that maintains their list structure? Another option would be to go back to not having the `saveData` function and allow users to use the data as they see fit as the main outputs are the plots generated by the `makeSaturationPlots` function? I can send over pictures/or longer descriptions of the results data if that would help explain why attempting to tidy them would be pretty difficult.

Not being able to easily tidy the data usually points to underlying data design issues. If possible, it may be better to add arguments for `getData` that target specific pieces of the data structure. 

> 5. Is the `on.exit` thing you mentioned related to the print options I currently change in the `saveData()` method?

Yes, the function shouldn't be changing the users' options. 

Best,
Marcel

**Comment by sunnyjones5** [comment]
Hi Marcel @LiNk-NY ,

As per your last comments I did the following:
1. Removed the `BiocManager` dependency and changed the `eval` to false in that part of the vignette.
2. I re-evaluated the "tidy-ablity" of the results data and was able to convert most of the results data (7/9) to tables. I've changed the options for saving these to `write.table` in the `saveData` method. For the remaining 2, the results are lists that containing results of varying lengths/variables at multiple depths (see attached pictures) so I have just those 2 saving as `rda`'s. 

Let me know if that's okay! Is there anything else I need to address before the deadline on the 22nd?

Thanks,
Sunny

![image](https://user-images.githubusercontent.com/33134524/79804539-39d3b280-8332-11ea-9856-a00c7a1a8b78.png)
(Clustering results run by testing PAM clustering with 2-15 centers. each result contains multiple pieces of information of varying sizes.)


![image](https://user-images.githubusercontent.com/33134524/79804597-5c65cb80-8332-11ea-9740-10fdcc8f7270.png)
(The genomic saturation information calculates the number/type of genomic events associated with each sample and with 1:100 regulators, saving the cumulative result with each addition regulator considered. Having them in a list like this is critical for internal downstream calculations. Honestly these are really intermediate results anyway as the summary of them is captured in the main plots made by `makeSaturationPlots`.)

**Comment by LiNk-NY** [comment]
Hi Sunny, @sunnyjones5 

Thank you for making those changes. They look great! 

* The NEWS file should anticipate the release version `1.0.0`. 
* The name of the NEWS file should be `NEWS.md` otherwise it
won't get picked up by `BiocCheck`. It currently is `NEWS.Md`.

Best,
Marcel

**Comment by sunnyjones5** [comment]
Hi Marcel @LiNk-NY ,

This is great to hear!! 
I changed and pushed the version with the new `NEWS.md` file. 
Let me know what I need to do next to move it through to the next phase of submissions.

Thanks,
Sunny

**Comment by sunnyjones5** [comment]
Hi Marcel @LiNk-NY and Lori @lshep ,

I just wanted to check to see if this package was confirmed to be in the next roll out of Bioconductor since this is the last day and it's still tagged as `review in progress`? Or if there is anything else I need to do?

Thanks,
Sunny

**Comment by LiNk-NY** [comment]
Hi Sunny, @sunnyjones5 

Thank you for sticking to it and making continual changes to your contribution.
MOMA has been accepted. :tada: 

Best regards,
Marcel

**Comment by sunnyjones5** [comment]
Amazing!! Thanks for your help!
Best,
Sunny

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sunnyjones5.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MOMA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MOMA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
