### ISSUE TITLE
TBSignatureProfiler

### ISSUE THREAD

**Issue by Aubreyodom** [Bioconductor/Contributions#1463]
- Repository: https://github.com/compbiomed/TBSignatureProfiler

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Hello,

I just want to check in with the progress of your package submission. I need to remind you that the deadline for your package to be included in the next Bioconductor release is April 21st.

**Comment by Aubreyodom** [comment]
Hi Daniel,
Is there any way to re-run the build on the bioconductor servers? I believe I've addressed the warnings and errors (and notes for R CMD Check) but I would need to check the output to be sure. The errors weren't showing up in my Travis build, which is why I am only just now addressing them. I am also creating a website to host our current vignette (which is quite large) and replace it with a more bare-bones vignette. I also expect that I will need to address additional reviewer comments from you at some point, correct? I anticipate that I will have adequate time to finish all of this before the deadline.

**Comment by PeteHaitch** [comment]
To trigger a new build, include a version bump in your commit, e.g., from Version: `0.99.0` to Version: `0.99.1`. Pre-release versions utilize the `0.99.z` format.  (see https://bioconductor.org/developers/package-submission/)

**Comment by lshep** [comment]
To trigger a new build you will need to first set up the [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) and then do a version bump in the description as suggested by @PeteHaitch .  Please do this so @dvantwisk can start a review

**Comment by Aubreyodom** [comment]
Thanks for the clarification. It should be connected now.

**Comment by Aubreyodom** [comment]
Hi - Sorry, the test-profile.R file is the only problem left with the build. The error log is too vague to  easily determine the cause of the problem, and I do not receive errors for these tests when I run R CMD check on my local machine. I have notified the maintainer who should get back to me shortly. Thank you for your patience as I work through this issue.

**Comment by dvantwisk** [comment]
Hi,

I've reviewed your package. Please address the following issues and message me back when you are finished making changes.

R/bootstrap.R
- [ ] [REQUIRED] Multiple uses of copy-and-append pattern to assign variables.
The pattern `pvals <- c(pvals, ...)` within a loop is very inefficient as it
first creates a new vector of length length(pvals)+1 and then moves all elements
to that new fector. A better way to do this would be to preallocate the vector
with `pvals <- c("numeric", length=<loop_length>)` and then to iterate using
`pvals[i] <- val`.

R/evaluate.R
- [ ] [REQUIRED] L40-53,86: Preallocate these empty vectors before the loop.

R/profile.R
- [ ] [REQUIRED] L218,238: What is the purpose of using `setwd()`? Will the
program automatically return to the user's initial directory? Can the
functionality of the code be done without changing directories like this?

vignettes/tbspVignette.Rmd
- [ ] [REQUIRED] L35: Do not use `git_install()` to install the package once
it is accepted into Bioconductor. Use `BiocManager::install()` instead.
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install('TBSignatureProfiler')
```
- [ ] [REQUIRED] L44-48: Since your package imports SummarizedExperiment,
the user should have it loaded when installing your package. If
SummarizedExperiment and all its symbols are directly being used in
conjunction with the package, you may consider placing it in `Depends:`
instead of `Imports:` in your package description.
- [ ] [REQUIRED] L125: We tend to want to see user facing examples run on
our builder to validate that they are working. Is there a specific reason
why not to run this code?

**Comment by Aubreyodom** [comment]
Daniel (@dvantwisk),
Thank you for your comments. We have reviewed them and corrected the associated code, and included our responses below.

> R/bootstrap.R
> 
> * [ ]  [REQUIRED] Multiple uses of copy-and-append pattern to assign variables.
>   The pattern `pvals <- c(pvals, ...)` within a loop is very inefficient as it
>   first creates a new vector of length length(pvals)+1 and then moves all elements
>   to that new fector. A better way to do this would be to preallocate the vector
>   with `pvals <- c("numeric", length=<loop_length>)` and then to iterate using
>   `pvals[i] <- val`.
* All three vectors of this nature are now initialized before the for-loop in the bootstrapAUC() function.
>
> R/evaluate.R
> 
> * [ ]  [REQUIRED] L40-53,86: Preallocate these empty vectors before the loop.
> 
* All empty vectors in LOOAUC_simple_multiple_noplot_one_df() and Bootstrap_LOOCV_LR_AUC() are now preallocated before the loops. 
> R/profile.R
> 
> * [ ]  [REQUIRED] L218,238: What is the purpose of using `setwd()`? Will the
>   program automatically return to the user's initial directory? Can the
>   functionality of the code be done without changing directories like this?
> 
* When using the runTBsigProfiler() function with the ASSIGN method, we use setwd() because the package ASSIGN that is called also uses setwd() in their code. Unfortunately, we cannot change the function in its current form without modifying the code for ASSIGN (or removing ASSIGN compatability altogether, which is not desirable). Note that the code does return the user to the original directory here on [line 239](https://github.com/compbiomed/TBSignatureProfiler/blob/master/R/profile.R#L239), but we have also added the line `on.exit(setwd(predir))` to [line 212](https://github.com/compbiomed/TBSignatureProfiler/blob/master/R/profile.R#L212). This will make sure the user is returned to the original directory even if the function errors.

* If this is unacceptable, as ASSIGN was written by other members of the same lab that developed the TBSignatureProfiler, we could potentially work on updating the ASSIGN code to remove the setwd(), and subsequently remove setwd() from this package as well. However, we have done our best to add the necessary code to ensure that the program does at least automatically return to the user's initial directory.

> vignettes/tbspVignette.Rmd
> 
> * [ ]  [REQUIRED] L35: Do not use `git_install()` to install the package once
>   it is accepted into Bioconductor. Use `BiocManager::install()` instead.
> 
> ```
> if (!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install('TBSignatureProfiler')
> ```
* Once the package is accepted, we will change this on the vignette, the package website, and the github README file.
>
> * [ ]  [REQUIRED] L44-48: Since your package imports SummarizedExperiment,
>   the user should have it loaded when installing your package. If
>   SummarizedExperiment and all its symbols are directly being used in
>   conjunction with the package, you may consider placing it in `Depends:`
>   instead of `Imports:` in your package description.
>
* It is true that as SummarizedExperiment is installed as part of the TBSP package, it is not necessary for the user to download & install it separately. However, because certain functions from SummarizedExperiment are required to construct the vignette, we have retained the loading of the library in the subsequent code block. Per the package development guidelines outlined in Wickham (2015) we will leave the package in `Imports` for now.
>
> * [ ]  [REQUIRED] L125: We tend to want to see user facing examples run on
>   our builder to validate that they are working. Is there a specific reason
>   why not to run this code?
* The duplicated code block was originally included as an attempted workaround to suppress the output of the progress bar automatically outputted from the runTBsigProfiler() function. However, by wrapping the function call with capture.output(), we are now able to do this without the need for another code block. Thus we have removed the non-evaluated code block so that all code blocks can be run and tested.

Please let us know if you have any other suggestions to ready this package for publication.
Best,
Aubrey Odom

**Comment by dvantwisk** [comment]
The changes so far look good.

- With regards to the SummarizedExperiment load in the vignette, do you expect the user to almost always need to use SummarizedExperiment to use your package? If so, then you should put it in `Depends: `. If not and it is only useful to load to show some examples, then what you have is fine.

- I don't think it is acceptable to use `setwd()`. I think expecting the user to leave their current workspace to perform some kind of analysis is to much to risk since `on.exit()` may not capture all possible exit situations. Can you elaborate why `ASSIGN::assign.wrapper()` needs to be in a different directory to function. Can you not specify an input directory (it looks like you can specify and output directory), if not, it appears to be a problem with the `ASSIGN` package to .
L215-216: You can user `tempdir()` to create a temporary directory instead of using `tempfile()` and then creating a directory from it.

- You will need to change the `install_github()` line in the vignette before I accept the package, as it will be beyond my control to require you to change it after the fact.

**Comment by Aubreyodom** [comment]
Hi Daniel,
Thanks for getting back to us.  See our responses below.

> * With regards to the SummarizedExperiment load in the vignette, do you expect the user to almost always need to use SummarizedExperiment to use your package? If so, then you should put it in `Depends: `. If not and it is only useful to load to show some examples, then what you have is fine.
* No, for most functions the user is able to use data.frame and/or matrix objects as an alternative input to SummarizedExperiment objects. The example data that we have provided with the package are SummarizedExperiment objects, however, so it is necessary to run the vignette, but not absolutely to use the bulk of the package.

> * I don't think it is acceptable to use `setwd()`. I think expecting the user to leave their current workspace to perform some kind of analysis is to much to risk since `on.exit()` may not capture all possible exit situations. Can you elaborate why `ASSIGN::assign.wrapper()` needs to be in a different directory to function. Can you not specify an input directory (it looks like you can specify and output directory), if not, it appears to be a problem with the `ASSIGN` package to .
>   L215-216: You can user `tempdir()` to create a temporary directory instead of using `tempfile()` and then creating a directory from it.
* We agree that the user should not have to leave their current workspace, and so we will be making the appropriate changes to the ASSIGN package and the runTBsigProfiler() function tomorrow. We will update you here when this is completed.

> * You will need to change the `install_github()` line in the vignette before I accept the package, as it will be beyond my control to require you to change it after the fact.
* This is now corrected in the vignette and README files.

Best,
Aubrey

**Comment by dvantwisk** [comment]
Alright, just message me back when the changes are made.

I do need to remind you that the final day to accept packages for the upcoming Bioconductor release is April 22nd. Please message me if you have any other questions.

**Comment by Aubreyodom** [comment]
Thanks, Daniel. We have made the appropriate changes; we are now waiting for the devel version of ASSIGN to propagate so that our build can run without errors.

Also, to respond to your earlier comment: tempdir() provides a per-session temporary directory; since we need one unique to each run, we use tempfile() to create a directory that we can remove when we don’t need it anymore.

**Comment by Aubreyodom** [comment]
@dvantwisk,
The package should now be ready to go.

**Comment by dvantwisk** [comment]
One last change.
In the vignette you have
```
BiocManager::install("compbiomed/TBSignatureProfiler")
```
For Bioconductor, we do not use the user's github id:
```
BiocManager::install("TBSignatureProfiler")
```

**Comment by Aubreyodom** [comment]
@dvantwisk Done.

**Comment by dvantwisk** [comment]
Great!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Aubreyodom.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TBSignatureProfiler")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TBSignatureProfiler

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
