### ISSUE TITLE
dorothea

### ISSUE THREAD

**Issue by christianholland** [Bioconductor/Contributions#1466]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saezlab/dorothea

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It seems from a quick look at the vignette that this package should interact (accept as inputs / return as outputs) with [SingleCellExperiment][1] and other [common Bioconductor classes and methods][2]

[1]: https://bioconductor.org/packages/SingleCellExperiment
[2]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by christianholland** [comment]
Hi @mtmorgan,

thanks for your feedback. In the current state this package can interact with the classes "ExpressionSet" and "Seurat". Based on your suggestion I am adding also the ability to interact with "SingleCellExperiment" class in the development branch. Hope to push it to the master branch today

**Comment by christianholland** [comment]
Hi @mtmorgan,

please note that I have removed in my latest commit a link the to the Bioconductor class `Biobase::ExpressionSet`. The link raises **only** on windows machines the following warning: 

`dorothea/man/run_viper.Rd:13: file link 'ExpressionSet' in package 'Biobase' does not exist and so has been treated as a topic.`

With respect to this [issue](https://github.com/r-lib/roxygen2/issues/707) there is currently no solution for this warning. Hence, I removed the link to avoid this warning.

**Comment by mtmorgan** [comment]
I believe the problem with the link can be understood from https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Cross_002dreferences where the `[]` is a link to the help page **file name**. You had `\link[Biobase:ExpressionSet]{ExpressionSet}` but the page name is 'class.ExpressionSet'. You could have `\link[Biobase:class.ExpressionSet]{ExpressionSet}`, but this seems like getting too much into the internals of the package, and I think the solution should be to allow R to resolve the reference itself, dynamically at run-time `\link{ExpressionSet}`.

I have no other comments on your package, and will mark it as accepted. You can update the link as above after the package has been added to the Bioconductor git repository.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/christianholland.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dorothea")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dorothea

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
