### ISSUE TITLE
GWENA

### ISSUE THREAD

**Issue by Kumquatum** [Bioconductor/Contributions#1468]
Hello,

I would like to submit the GWENA package for inclusion in BioConductor release 3.11. It is a package containing a pipeline for gene co-expression analysis with biological and topological tools for further analysis included.

I hope you will find the package interesting enough to be included into Bioconductor.

Regards,
Gwenaëlle

_____

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Kumquatum/GWENA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package must be adapted to work with [SummarizedExperiment][1] and other [standard Bioconductor data representations][2], for instance as inputs and outputs to your functions and as example data sets in your vignette.

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by lshep** [comment]
Please fix the ERRORs in the report before @nturaga  does a formal review.  And make sure to take into account the comment from @mtmorgan above.

**Comment by Kumquatum** [comment]
ERRORs in report were all corrected except for this one I couldn't reproduce :
```
Error: connections left open:
	<-TOKAY2:11632 (sockconn)
	<-TOKAY2:11632 (sockconn)
Execution halted
```
Could you give me more information on the test performed which returned this error ?

Also, I don't know if you're aware of this behavior (if so, sorry for the inconvenience) : when creating a branch to properly patch code, then incrementing the version in DESCRIPTION, and finally merging the branch, the @bioc-issue-bot doesn't seems to trigger new build. But if I look to the webhook, it is sent.

**Comment by Kumquatum** [comment]
Dear @mtmorgan 
I made all the asked modifications. But it seems I can't reproduce the last two errors : 
* The connection left open
* The test-net_and_modules.R fail with `'length(x) = 7 > 1' in coercion to 'logical(1)`

Is there a way to have more information on them ?

Here is my session info if this can help :
```
> version
               _                                        
platform       x86_64-pc-linux-gnu                      
arch           x86_64                                   
os             linux-gnu                                
system         x86_64, linux-gnu                        
status         alpha                                    
major          4                                        
minor          0.0                                      
year           2020                                     
month          03                                       
day            26                                       
svn rev        78078                                    
language       R                                        
version.string R version 4.0.0 alpha (2020-03-26 r78078)
nickname
```

**Comment by Kumquatum** [comment]
Dear @mtmorgan, @lshep and @nturaga 

I managed to find out where the connection left open ERROR (specific to Windows) came from. It is due to the use of WGCNA parallelization system which doesn't seems to work well on Windows. I "fixed" it by making the vignette and the examples use only one thread. However I don't feel comfortable doing this because a single OS doesn't handle parallelization properly. I would prefer to undo this changes but I would like your opinion on this if I may.

I also discovered that the remaining Windows-specific WARNINGS are caused by the use of documentation links such as `\link[base]{Long vectors}` or `\code{\link[WGCNA]{pickSoftThreshold.fromSimilarity}`. Both don't have specific Rd file because of aliases (see detail below) and roxygen seems to have trouble with this on Windows. There has been [an issue on roxygen repo](https://github.com/r-lib/roxygen2/issues/707) about this subject.
This seems to be common so I assume you have encountered this case with other Bioconductor packages before. Is there a workaround or should I just ignore them ?

___________________

Detail about aliases :
* [WGCNA](https://github.com/cran/WGCNA/blob/678c9da2b71c5b4a43cb55005224c243f411abc8/man/pickSoftThreshold.Rd#L3)
* [Long Vectors](https://svn.r-project.org/R/tags/R-3-6-3/src/library/base/man/LongVectors.Rd)

**Comment by Kumquatum** [comment]
Thanks to your advices @mtmorgan I managed to remove the last warnings and make the code specific for each OS.
Anything else I need to do ?

**Comment by lshep** [comment]
Please do a version bump to trigger a new build report.  If it is ERROR free @nturaga  will continue with the review process.

**Comment by nturaga** [comment]
Hi @Kumquatum 

Please take a look at the NOTE issues on your build report. There are 8 of them in your build report. 

A few things are easy to solve,

1. NEWS file.

2. Avoid sapply(); use vapply()

3.  Avoid 1:...; use seq_len() or seq_along()

Try and fix as many of them as possible.

**Comment by nturaga** [comment]
# GWENA review

## DESCRIPTION

ok

## NAMESPACE

ok

## vignette

* Use BiocStyle for the vignette, but good job otherwise.

## R

* Multiple NOTES in the build report which **need** to be addressed
  before the package can be accepted.
  
* Coding style needs to be fixed to improve readibility
  http://bioconductor.org/developers/how-to/coding-style/. This needs
  to be fixed as well.
  
* Remove commented out code.

* Good use of matrixStats

* Some helper functions like `%sub_in%` add confusion while reading
  code. It's not necessary to remove them, but they seem to be easy
  enough operations to repeat. I'll leave it to your judgement.
  
* Take some time to think about the exessive use of the `%>%` operator
  outside of the rectagular data manipulations through dplyr. This may
  seem to add to readability while writing the code, but makes it
  extremely hard to debug later on.
  
## tests

ok

**Comment by nturaga** [comment]
Hi, 

We usually give authors about 2 weeks to reply after the review. Please consider this a 2 week notice to reply. We can always close the issue and reopen when you are able to work on your package. I understand these are tough times for the world. The review will continue from where we left off when we reopen the issue after closing, nothing is lost.

I will wait for your response by June 15th. 

Best regards,

**Comment by nturaga** [comment]
Make sure there are no ERROR messages in the build report. I'll review your package again with the changes you made if there is/are no ERROR(s) on the build report.

**Comment by Kumquatum** [comment]
Dear @nturaga,

Thank you. I addressed as much of your remarks as possible.
I prefer to keep the original functions like `%sub_in%` as they are since I copied them from the `NetRep` package. But if you insist I'll include them.
Regarding the use of the `%>%` operator, as much as I understand your concern, I think its use actually helps the readability of the code. Declaring a lot of single-use and short-living variable is confusing and requires more memory space. 


However the package doesn't seem to pass the build on your server now. The function implied in the build report is `plot_expression_profiles`. I haven't changed the way it works since the last successful build on your servers. Still, I've been investigating :
* The only changes are a shortening of the lines to less than 80 char.
* You can see that with [GitHub's blame windows](https://github.com/Kumquatum/GWENA/blame/master/R/net_and_modules.R#L579) or by doing `git diff 516a2a6 b2f3c6f R/net_and_modules.R`
* Since build/check/BiocCheck seems to pass on my station (Ubuntu 18.04) and my Windows VM, I've tried the R-hub tool. Here are the successful reports on each OS :
  * [Windows](https://builder.r-hub.io/status/GWENA_0.99.100.tar.gz-7cd640cb669ab24c91d90e7778bbf59f)
  * [Linux](https://builder.r-hub.io/status/GWENA_0.99.100.tar.gz-a03907381543341783b01f00a4f9e1e5)
  * [macOS](https://builder.r-hub.io/status/GWENA_0.99.100.tar.gz-5c24f334925446763dc7c2dfb8bc69cf)
  
I can't reproduce the `Can't convert <character> to <double>`, do you have any idea how I could do it or correct it ?

**Comment by nturaga** [comment]
Hi @Kumquatum 

Even though your build report doesn't display any warning or error messages, you can notice some issues with it.

```
Error in !is_windows : invalid argument type
Error in !is_windows : invalid argument type
```

Another one is,

```
  * NOTE: Consider clarifying how 47 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    function (object)
      build_graph_from_sq_mat (gene_from)
      build_graph_from_sq_mat (.)
      build_graph_from_sq_mat (gene_to)
      build_net (is)
      compare_conditions  (is)
      compare_conditions  (setNames)
      compare_conditions  (setNames)
      compare_conditions (.)
      detect_modules (is)
      detect_modules (as.dist)
      detect_modules (setNames)
      detect_modules (.)
      filter_low_var (is)
      filter_RNA_seq (is)
      get_fit.cor (SFT.R.sq)
      get_fit.cor (Power)
      get_fit.expr (is)
      get_hub_degree  (.)
      get_hub_high_co  (.)
      get_hub_kleinberg  (.)
      plot_comparison_stats (module)
      plot_comparison_stats (statistics)
      plot_comparison_stats (pvalue)
      plot_enrichment (query)
      plot_expression_profiles (is)
      plot_expression_profiles (stack)
      plot_expression_profiles (setNames)
      plot_expression_profiles (module)
      plot_expression_profiles (.)
      plot_expression_profiles  (prcomp)
      plot_expression_profiles  (.)
      plot_expression_profiles (gene)
      plot_expression_profiles (gene_gene)
      plot_expression_profiles (expression_gene)
      plot_expression_profiles (expression_eigengene)
      plot_expression_profiles (cor_sign)
      plot_module (.)
      plot_module (lsf.str)
      plot_module (vertex.size)
      plot_module (edge.width)
      plot_module (legend)
      plot_module (symbols)
      plot_modules_merge (stack)
      plot_modules_merge (before)
      plot_modules_phenotype (eigengene)
      plot_modules_phenotype (pval)
      plot_modules_phenotype (phenotype)
```

* Your DESCRIPTION file needs to contain a `Description` that is more like the abstract of a paper. 

* Use `donttest{}` instead of `dontrun{}` for your examples if you insist on using it. At least it'll check for the validity of the R code.

These are easy fixes. I'm satisfied with the way your package has developed. If you are eager to get rid fo the NOTE for the coding style, take a look at http://bioconductor.org/developers/how-to/coding-style/. 

I'll accept your package as soon as your next build report looks cleaner.

**Comment by Kumquatum** [comment]
Hello @nturaga 

All four corrections asked were implemented. 
I tried the `\donttest` inclusion but it finally seems that it's not needed anymore (it was used in first place to avoid time out on the build). So good news.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Kumquatum.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GWENA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GWENA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
