### ISSUE TITLE
randRotation

### ISSUE THREAD

**Issue by phettegger** [Bioconductor/Contributions#1469]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/phettegger/randRotation

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package should be adapted to work with [SummarizedExperiment][1] and other [standard Bioconductor data representations][2], for instance as inputs and outputs to your functions and as example data sets in your vignette.

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by Kayla-Morrell** [comment]
Hello @phettegger,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Keep in mind that the deadline for accepting new packages into the Bioconductor 3.11 release is 4/22.

## General package development

- [ ] REQUIRED: All of the warnings from the Rd files need to be cleaned up in 
BiocCheck. I don't think you have the proper set up for the Rdpack package 
(as seen from this source: https://cran.r-project.org/web/packages/Rdpack/vignettes/Inserting_bibtex_references.pdf). 
Please be sure you are correctly setting up the Rdpack usage.

- [ ] REQUIRED: Is there a reason to have both REFERENCES.bib and library.bib in 
the 'inst/' directory. Is there a difference between the files?

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to false. It's our experience that 
when this field is set to true it can slow down the loading of the package.

- [ ] SUGGETSION: It is encouraged to include the 'BugReports:' field with the 
relevant link to Github for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring and 
not include '.' indicate S3 dispatch.

- [ ] REQUIRED: Internal functions should not be exported.

## Vignettes

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to 
the user how to install the package from Bioconductor. The code should look 
something like the following:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("randRotation")
```

- [ ] REQUIRED: In section 7 - Correlation matrices with non-block design there 
are a lot of arrows that are produced in the rendered vignette. I believe this 
is due to the commented out code and text. Please clean these up. Also, is there 
a reason there is so much commented out lines? Is this information for future 
versions? Why not include it now?

## Man pages

- [ ] SUGGESTION: For any of the internal functions that you have documented, 
you can add the `@keywords internal` tag to the roxygen documentation. This will 
remove the function from the documentation index.

- [ ] REQUIRED: Add runnable examples to the following man pages which document 
exported object:
        - fdr.p.Rd
        - p.fdr.Rd

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 
236 lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 377 lines (11%) are not.

Best,
Kayla

**Comment by phettegger** [comment]
Dear @Kayla-Morrell,

thanks a lot for the initial review of the package. I tried to adress all issues:

> 
> 
> Hello @phettegger,
> 
> Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Keep in mind that the deadline for accepting new packages into the Bioconductor 3.11 release is 4/22.
> ## General package development
> 
>     * [ ]  REQUIRED: All of the warnings from the Rd files need to be cleaned up in
>       BiocCheck. I don't think you have the proper set up for the Rdpack package
>       (as seen from this source: https://cran.r-project.org/web/packages/Rdpack/vignettes/Inserting_bibtex_references.pdf).

I added the lines to DESCRIPTION as described and I tried various other approaches to remove the warnings. However, according to section 4.2 in [https://cran.r-project.org/web/packages/Rdpack/vignettes/Inserting_bibtex_references.pdf](url) 
--> _these warnings are harmless - the help pages are built properly_.
If you have any further suggestion on how to remove the warnings, please let me know.

>       Please be sure you are correctly setting up the Rdpack usage.
> 
>     * [X]  REQUIRED: Is there a reason to have both REFERENCES.bib and library.bib in
>       the 'inst/' directory. Is there a difference between the files?

i removed that, it was automatically generated by mendeley

> 
> ## DESCRIPTION
> 
>     * [X]  REQUIRED: 'LazyData:' should be set to false. It's our experience that
>       when this field is set to true it can slow down the loading of the package.
> 
>     * [X]  SUGGETSION: It is encouraged to include the 'BugReports:' field with the
>       relevant link to Github for reporting Issues.
> 


> ## NAMESPACE
> 
>     * [X]  REQUIRED: Exported functions should use camel case or underscoring and
>       not include '.' indicate S3 dispatch.
> 
>     * [X]  REQUIRED: Internal functions should not be exported.

I adapted the functions and exports

> 
> ## Vignettes
> 
>     * [X]  REQUIRED: There should be an 'Installation' section that demonstrates to
>       the user how to install the package from Bioconductor. The code should look
>       something like the following:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("randRotation")
> ```

I added the installation section


>     * [X]  REQUIRED: In section 7 - Correlation matrices with non-block design there
>       are a lot of arrows that are produced in the rendered vignette. I believe this
>       is due to the commented out code and text. Please clean these up. Also, is there
>       a reason there is so much commented out lines? Is this information for future
>       versions? Why not include it now?
> 

These commented out code text were some ideas that I basically implemented in the other sections. I removed them


> ## Man pages
> 
>     * [X]  SUGGESTION: For any of the internal functions that you have documented,
>       you can add the `@keywords internal` tag to the roxygen documentation. This will
>       remove the function from the documentation index.
> 
>     * [X]  REQUIRED: Add runnable examples to the following man pages which document
>       exported object:
>       - fdr.p.Rd
>       - p.fdr.Rd

fdr.p is actually an internal function, so I changed that.

> 
> ## R code
> 
>     * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are
>       236 lines that are > 80 characters long.
> 
>     * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>       line indents. There are 377 lines that are not.

I will adapt that as soon as possible. Also, thank you very much @mtmorgan for your comments on the SummarizedExperiment. I will also adapt that as soon as possible.

> 
> Best,
> Kayla


Thank you again for your efforts and Best Regards,
Peter

**Comment by Kayla-Morrell** [comment]
@phettegger - Thank for making the necessary changes. Everything looks good now and I'm more than happy to accept the package. 

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/phettegger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("randRotation")`. The package 'landing page' will be created at

https://bioconductor.org/packages/randRotation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
