### ISSUE TITLE
getDEE2

### ISSUE THREAD

**Issue by markziemann** [Bioconductor/Contributions#1473]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/markziemann/getDEE2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
The vignette provides installation instructions for a package called 'mitch' (!!!)

It seems like your package should try harder to interoperate with Bioconductor by returning [standard data representations][1] like SummarizedExperiment. Minimally, the vignette should include an example of SummarizedExperiment construction from the downloads.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by markziemann** [comment]
> The vignette provides installation instructions for a package called 'mitch' (!!!)
> 
> It seems like your package should try harder to interoperate with Bioconductor by returning [standard data representations](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/) like SummarizedExperiment. Minimally, the vignette should include an example of SummarizedExperiment construction from the downloads.

Thanks for this. I will look into SummarizedExperiment.

**Comment by lshep** [comment]
The NEWS file ERROR was on our end.  We have a fix implemented for the linux builder and the windows one should clear up tomorrow afternoon.  Sorry for the confusion.

**Comment by markziemann** [comment]
> The NEWS file ERROR was on our end. We have a fix implemented for the linux builder and the windows one should clear up tomorrow afternoon. Sorry for the confusion.

Thanks for the clarification, I thought I was going crazy :)

**Comment by lshep** [comment]
yea sorry about that.  Hopefully fully fixed by this afternoon.

**Comment by markziemann** [comment]
Hello @mtmorgan , I have written a new function calles `se()` to construct a SummarizedExperiment object from DEE2 data and included this in the vignette as shown below:

## SummarizedExperiment construction
A SummarizedExperiment object can be created from DEE2 data using the se function. The ‘counts’ parameter controls the type of counts to use:

* GeneCounts STAR gene level counts

* TxCounts Kallisto transcript level counts

* Tx2Gene transcript counts agggregated to the gene level.

```
y<-se(x,counts="GeneCounts")
y
## class: SummarizedExperiment 
## dim: 46739 2 
## metadata(0):
## assays(1): counts
## rownames(46739): WBGene00197333 WBGene00198386 ... WBGene00010967
##   WBGene00014473
## rowData names(0):
## colnames(2): SRR1176644 SRR1176645
## colData names(82): QC_summary SRX_accession ... DatasetCorrel
##   QC_SUMMARY
```
Do let me know if this is sufficient, and whether the name is okay. Thanks.

**Comment by mtmorgan** [comment]
A better solution would have `getDEE2()` return a SummarizedExperiment, and for the downstream functionality you implement accept SummarizedExperiment. This makes your package useful to anyone with a SummarizedExperiment, and conversely allows your users to learn only one set of tricks -- working with SummarizedExperiment -- and benefit from a much broader part of the Bioconductor ecosystem.

**Comment by markziemann** [comment]
@mtmorgan Thanks for the suggestion. The main function `getDEE2()` now returns a SummarizedExperiment.

**Comment by Kayla-Morrell** [comment]
@markziemann - Is this package ready for review or do you plan to make more changes to it?

**Comment by markziemann** [comment]
@Kayla-Morrell There is 1 more [issue](https://github.com/markziemann/getDEE2/issues/3) to fix on my end then it will be ready for you. No more than a week. Thanks

**Comment by Kayla-Morrell** [comment]
@markziemann - Perfect, I just wanted to be sure you weren't waiting on me. Just let me know when it's ready for review. Thanks!

**Comment by markziemann** [comment]
Hello @Kayla-Morrell I have fixed up the remaining issues on my side and now the package is ready for review. Thanks for your time.

**Comment by Kayla-Morrell** [comment]
@markziemann - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: It is encouraged to include the 'BugReport:' field with a 
relevant link to GitHub for reporting Issues.

## Vignette

- [ ] REQUIRED: Data does not belong in this directory. There should only be the 
vignette file and any necessary static images. Please read our information about 
data, here: https://bioconductor.org/developers/package-guidelines/#data, to 
determine the best location for the data here.

## Man pages

*loadFullMeta*

- [ ] REQUIRED: The example code in this man page shows code for `loadQcMx` not 
`loadFullMeta`.

*loadSummaryMeta*

- [ ] REQUIRED: The same for this man page, the example code shows `loadQcMx`.`:w

## R code

- [ ] SUGGESTION: There are a couple functions that don't seem to follow the 
naming pattern of other functions (as well as the package name itself). Is there 
a reason that `getDee2Metadata` and `queryDee2` don't follow the DEE2 schema? 
Users would have to remember that those two functions have Dee2 instead. Might 
not be a huge issue, especially with tab completion, but just something I 
noticed.

- [ ] REQUIRED: Since you do query to a web resource, be sure you look over our 
information about querying web resources, here: http://bioconductor.org/developers/how-to/web-query/.
It is important to think about to prevent future ERRORs or TIMEOUTs with our 
builders. 

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` instead. Found in the following 
file:
        - getDEE2.R, lines 432, 436, and 437

Best,
Kayla

**Comment by markziemann** [comment]
@Kayla-Morrell  Many thanks for this!! I will need a bit of time to address these. I will let you know when it's ready.

**Comment by markziemann** [comment]
Dear @Kayla-Morrell  I believe I've addressed all the points you've raised. Do et me know whether this is satisfactory. Thank you.

> DESCRIPTION
>  SUGGESTION: It is encouraged to include the 'BugReport:' field with a
> relevant link to GitHub for reporting Issues.
This has been added to the description.

> Vignette
>  REQUIRED: Data does not belong in this directory. There should only be the
> vignette file and any necessary static images. Please read our information about
> data, here: https://bioconductor.org/developers/package-guidelines/#data, to
> determine the best location for the data here.
This data file has been removed.

> Man pages
> loadFullMeta
>  REQUIRED: The example code in this man page shows code for loadQcMx not
> loadFullMeta.
> loadSummaryMeta
 REQUIRED: The same for this man page, the example code shows loadQcMx.`:w
R code
This has been fixed for both functions.

>  SUGGESTION: There are a couple functions that don't seem to follow the
> naming pattern of other functions (as well as the package name itself). Is there
> a reason that getDee2Metadata and queryDee2 don't follow the DEE2 schema?
> Users would have to remember that those two functions have Dee2 instead. Might
> not be a huge issue, especially with tab completion, but just something I
> noticed.
Thanks for this suggestion. I agree and have changed the names of these functions.

>  REQUIRED: Since you do query to a web resource, be sure you look over our
> information about querying web resources, here: http://bioconductor.org/developers/how-to/web-query/.
> It is important to think about to prevent future ERRORs or TIMEOUTs with our
> builders.
I agree this is important. I have included the getURL function as a way to manage graceful download errors. Lines 27-42, 75-76, 398-399, 452-453, 555-556, 

> REQUIRED: Avoid sapply(); use vapply() instead. Found in the following
> file:
> - getDEE2.R, lines 432, 436, and 437
This has been resolved

**Comment by Kayla-Morrell** [comment]
@markziemann - Thank you for making the necessary changes. I have reviewed them all and have no additional changes that need to be made. With that, I am more than happy to accept the package.

Best,
Kayla

**Comment by markziemann** [comment]
Great to hear. 
Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/markziemann.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("getDEE2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/getDEE2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
