### ISSUE TITLE
rfaRm

### ISSUE THREAD

**Issue by LaraSellesVidal** [Bioconductor/Contributions#1478]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LaraSellesVidal/rfaRm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LaraSellesVidal** [comment]
Dear BioConductor team,

I have recently pushed some updates to the GitHub repository of this package correcting some mistakes I identified. However, they don't seem to be triggering builds of the package, even though I have included in each update a version bump. I have confirmed that the webhook is setup. Any advice on what could be possibly missing?

Thanks a lot in advance!

**Comment by mtmorgan** [comment]
@LaraSellesVidal the issue needed to be moderated (added to the review queue) before automatically building. If your web-hook is set up correctly, new version bumps should now trigger builds.

**Comment by LaraSellesVidal** [comment]
Hi @mtmorgan  ,

Thanks a lot for looking into this!

Best wishes,

Lara

**Comment by LaraSellesVidal** [comment]
Hi @mtmorgan @dvantwisk ,

We have now passed BiocCheck without errors or warnings. We have only three remaining notes:

- One of them is about the use of a \dontrun section in one of the manual pages. We included this on purpose to show an example of an error case.
- The other two notes relate to the presence of some lines longer than 80 characters or with indentations not multiple of 4 spaces. We have removed as many as possible of these after seeing the note in the first build report. We believe changing the remaining lines leading to these two notes might make the readability of the code a bit worse

Can we ignore these notes for now, or should we anyway perform the changes required to get a build report free of any notes?

Also, we have observed the single package builder is not currently building on macOS, just on tokay2 (Windows) and malbec2 (ubuntu). Just to confirm, this is the expected behaviour at the moment, right? 

Thanks a lot in advance!

Best wishes,

Lara

**Comment by dvantwisk** [comment]
Hi,

I've reviewed your package and I'm happy to say I don't have anything to add. The package is excellently written as is. I am going to move to accept your package now so it makes it into the next release.

**Comment by LaraSellesVidal** [comment]
Hi @dvantwisk ,

Thanks a lot ! :) 

Best wishes,

Lara

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LaraSellesVidal.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rfaRm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rfaRm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
