### ISSUE TITLE
PathoStat New package submission

### ISSUE THREAD

**Issue by mani2012** [Bioconductor/Contributions#148]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mani2012/PathoStat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
DESCRIPTION

- Looks good!

vignettes

- Once in Bioconductor, `biocLite('PathoStats')` installs
  dependencies, so these do not need to be enumerated at
  PathoStatIntro.Rmd:41
- consider naming chunks `{r setup, options...}` to help debug when
  errors occur.
- Provide a more comprehensive vignette that describes in greater
  detail the inputs and outputs of the main package functions, so that
  someone reading the vignette gains a comprehensive understanding of
  what the package does, how the package can be used for analysis of
  their own data, and how the package works with other _Bioconductor_
  packages.

R

- The following comments are about specific lines of code, but there
  are many examples of similar issues throughout.
- no need to `require(phyloseq)` in allClasses.R or other packages
  (e.g., `library(gtools)` in confRegion.R), provided the NAMESPACE
  file is formulated properly.
- avoid 1:n (e.g., cnofRegion.R:6) in favor of `seq_len()` or
  `seq_along()` (avoids issues when n == 0).
- vectorize, rather than iterate, e.g., (there are important issues
  like this throughout the code)

        for (i in 1:3)  {
            if (x[i] <= 0)  {
                x[i] = delta
            }
        }

  is `x[x[i] < 0] = delta`
- simplify

        check <- FALSE
        if (chi < chisqval) {
            check <- TRUE
        }
        return (check)
        
  as simply returning `chi < chisqval`
- if a loop involves a part that can be vectorized and a part that
  cannot, separate these. Use the 'apply' family rather than iteration
  where possible; it simplifies memory management. For instance,
  confRegion.R:95
  
        for (i in 1:n) {
          me <- confinterval(A[,i], size)
          p1up <- p1up + A[,i][1]+me[1]
          p1low <- p1low + A[,i][1]-me[1]
          p2up <- p2up + A[,i][2]+me[2]
          p2low <- p2low + A[,i][2]-me[2]
        }

  might be (untested!)
  
        me <- apply(A, 2, confinterval, size)
        p1up <- sum(A[1,] + me[,1])
        ...
- coreOTUModule.R:32 avoid highly nested evaluations that make code
  difficult to parse and debug, e.g.,
  
        coremat <- data.frame(do.call(rbind, lapply(prev, function(p){
          sapply(det, function(d) sum(rowSums(otu_table(pstat) >= d) >= p))
        })))
        
  It looks like in this code chunk `otu_table(pstat)` is being called
  repeatedly; this expression should be 'hoisted' from the body
  
        otu_pstat = otu_table(pstat)

  it then seems that `rowSums(otu_pstat >= d)` is calculated for each
  `p`, so again hoist outside the inner loop
  
        otu_d <- sapply(det, function(d) rowSums(otu_pstat >= d))

  the `lapply()` seems like it'll always return a single scalar, so
  
        det <- sapply(prev, function(p) sum(otu_d > p))

  and the original chunk of code is
  
        otu_pstat = otu_table(pstat)
        otu_d <- sapply(det, function(d) rowSums(otu_pstat >= d))
        det <- sapply(prev, function(p) sum(otu_d > p))
        data.frame(det=det, prev=prev)

  this is both easier to understand and faster. In particular the
  original formulation scaled as the product of the length of det and
  prev, whereas the updated formulation scales as the sum of these
  lengths.
  
  A further improvement would use `vapply()` rather than `sapply()`.
  
  Please review all of your code for similar issues.
- consider indenting code at coreOTUModule.R:55 to improve readability
- utils.R:46 this 'copy-and-append' strategy (also line 56, for
  instance) has very poor memory cahracteristics; use `lapply()` (and
  `unlist()`?) to avoid the need to explicity grow memory.

man

- Aim for all man pages to have runnable examples, e.g.,
  coreOTUModule.Rd, coreOTUModuleUI.Rd
- clearly mark documented functions that are not exported,
  e.g,. findTaxonLevelData, as 'INTERNAL'.

**Comment by mani2012** [comment]
Hi Martin,
Thank you so much for your review and comments, which were very helpful. We have updated our PathoStat package based on your review and suggestions. 

We have followed all your suggestions for updating the R code, and we have addressed all those issues. The only NOTE on 'Adding runnable examples for coreOTUModule.Rd', we would like to mention that we have added example codes for how this coreOTUmodule can be included in another shiny app, but this function is not to be called directly by the user of our PathoStat package (we have used the dontrun directive for this purpose) ; it will only be useful for calling this function from another shiny app with the shiny server input.

For the vignette, we are working on creating another more comprehensive vignette. We shall shortly add the detailed vignette to the package. Could you please review our PathoStat package again to make sure that there are no other issues?

Thanks,
Mani

**Comment by mtmorgan** [comment]
Thank you for your changes so far. I think the only remaining issue is the vignette.

**Comment by mani2012** [comment]
Hi Martin,

Thanks again for your review. We have now added a detailed PathoStat User Manual and PathoStat Advanced Usage vignettes to our package.

We look forward to having our package added to the BioConductor release.

Thanks,
Mani

**Comment by mtmorgan** [comment]
Thanks for your work on this package, it looks great, and I am happy to accept it to Bioconductor. It will be added to the Bioconductor svn repository and nightly builds. You will receive additional information in the next several days.
