### ISSUE TITLE
uncoverappLib

### ISSUE THREAD

**Issue by Manuelaio** [Bioconductor/Contributions#1482]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Manuelaio/uncoverappLib

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Manuelaio** [comment]
I have removed .DS_Store files and change my version in description file, however it seems that .DS_Files don't' be just removed and I receive the same error

**Comment by lshep** [comment]
you will need to `git rm <file>`  and `git commit` the removed files

**Comment by mtmorgan** [comment]
As indicated on the build report there are still .DS_Store files in your repository, e.g., in the inst/extdata directory.

**Comment by Manuelaio** [comment]
Yes, I did, but I had "version bump required"  message in  response, later I updated the version in Description  file and I pushed. Now  I haven't in my repository this files, I need to go back in my history and recover the commit or,  is there an other way, please? Thank you

**Comment by mtmorgan** [comment]
I'm not sure that I understand. When I look in your repository on github at

https://github.com/Manuelaio/uncoverappLib/tree/master/inst/extdata

I see a .DS_store file. So `git rm inst/extdata/.DS_store` (There are other instances to be removed), version bump, commit, and push. No need to go back into history.

**Comment by Manuelaio** [comment]
Thank you for help, you are right! They escaped  me

**Comment by lshep** [comment]
Thank you for your submission.  Please see the initial review below. 

**Build Report**

- [ ] We strongly recommend unit tests. Most maintainers find them useful for checking functionality as well as development. 

**README**

- [ ] Update to say samtools >= 1.9
- [ ] Update to say R >= 3.5.1 
- [ ] Include Bioconductor installation instructions
- [ ] Do a spell check. There are typos like 'prevusly'


**General**

- [ ] How do I run anything? There is a lot of preprocessing work to be done.  You should provide example preprocessed files in the correct form ready to be used by the user to display functionality of your application.  If you have the bam and tbi file why not run the processing and provide the input file that can be directly used?  -- Running the vignette and searching your github it seems you do (POLG.example.bed.gz) but do not make good mention of using this file as an example.  I would recommend showing how you created this example file (all commands / extra files modified / etc) and make mention its there for use to demo the application.  
- [ ] Can a user provide their own versions of `sorted.bed.gz` and `sorted.bed.gz.tbi`? We generally prefer annotation files needed for Bioconductor packages to be uploaded to the Bioconductor AnnotationHub. 

**LICENSE**

- [ ] Do you really need the LICENSE in both formats?  You could remove the LICENSE.md file since the MIT license is included with the distribution of R. 


**NEWS**

- [ ] Don't have empty news sections.  Remove 0.99.0 if it has no subsections or items. 

**inst**

- [ ] Include an inst script describing what is provided in inst/extdata and any relevant source information. 

**vignette**

- [ ] Change the name of the vignette.  Vignette is too generic and could name conflict if there are other packages the user has loaded that choose not to name their vignette.  I recommend the name of the package uncoverappLib.Rmd. 
- [ ] It seems like you can run `run.uncoverapp()`  without specifying file.name and tbi so why is defining these before running the app important?  If those files are required than the app shouldn't launch if they aren't available.
- [ ] Can a user provide their own versions of `sorted.bed.gz` and `sorted.bed.gz.tbi`?  How are these important? Why should they be specified when it seems like the app doesn't need them to run. 
- [ ] Again spell check there are typos. example 'obteined'
- [ ] In Section 2 Installation and example. You mention an example file is a BED file containing genomic positions of POLG gene. Describe how this was generated.  You don't indicate that its location is anywhere for use? 
- [ ] Section 3: How do you know what samples are available? 
- [ ] With your example POLG.example.bed.gz , then in the next section you mention the HGNC official gene name -- maybe provide example gene name that can be used. This whole section, provide example of input to the sidebar that the user can run with the POLG.example.bed.gz. Values that would populate the other tabs in the app.
- [ ] You don't make mention of the output that appears in the terminal console. I assume it mimics the tables appearing in the shiny app. 

** R / Man Pages**

- [ ] Don't make the package documentation internal. We recommend having a
  package help page available to the users. 

Please address or comment on the above issues.  When ready please do a version bump to trigger a new build and summarize the changes. Thank you.

**Comment by Manuelaio** [comment]
Dear 
thank you for your revision and your consideration. I have made some change in order to include in shiny app the file preparation with `RSamtools` and in order to reduce the preprocessing phase. Could I upload this new version? 
Regarding `sorted.bed.gz` and `sorted.bed.gz.tbi,` those are annotation files from dbNSPF, required for annotate low-coverage positions at base-pair levels with Clinvar, omim, CADD and other mutation scores. This bed file is very large (1.3Gb) and I can't include it in the package otherwise I have warning during testing phase, could you suggest an efficient way to do it? I will work on issues in next days 

Thank you

**Comment by lshep** [comment]
Yes please merge your new version and do a version bump so there is a new build report. If the annotations can be useful for the larger Bioconductor community which is appears it could be I would recommend putting them in Bioconductor's AnnotationHub. There is information here for creating an annotationhub package. https://bioconductor.org/packages/release/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html

**Comment by lshep** [comment]
Could you please commit the new version and do a version bump so we have the most recent version of the package to build with an accurate build report.

**Comment by Manuelaio** [comment]
Dear thank you for your reminding, we have accumulated some delay for workplace restrictions caused by coronavirus emergency. I hope that it is ok if I will commit the new version and build report on Monday. Sorry !

**Comment by Manuelaio** [comment]
Dear 
thanks for your review and helpful suggestions.
I was worked on package focusing on your suggestions. Below, the answers point-by-point at your queries. 

Build Report

 We strongly recommend unit tests. Most maintainers find them useful for checking functionality as well as development. _--Done: a unit tests was added (in ### inst folder)_ 

README

 Update to say samtools >= 1.9 _-- Done: samtools was removed and RSamtools library was added_.  
 Update to say R >= 3.5.1 -- _Done: R version was modified and java control script was added._
 
Include Bioconductor installation instructions _--Done: Bioconductor installation was included._
 Do a spell check. There are typos like 'prevusly'. _--Done_ 

General

 How do I run anything? There is a lot of preprocessing work to be done. _--Done: I have simplified integrating preprocessing work on app: you can directly load input files (gene(s) list and bam list) on the application using R language._ 
You should provide example preprocessed files in the correct form ready to be used by the user to display functionality of your application. _--Done: I have added two required input file: a txt file with gene name and a bam file_ 
If you have the bam and tbi file why not run the processing and provide the input file that can be directly used? -- Running the vignette and searching your github it seems you do (POLG.example.bed.gz) but do not make good mention of using this file as an example. I would recommend showing how you created this example file (all commands / extra files modified / etc) and make mention its there for use to demo the application. _--Done:  my example should be run launching app. Users are able to build my example starting from two input file stored in extdata_ 

Can a user provide their own versions of sorted.bed.gz and sorted.bed.gz.tbi? We generally prefer annotation files needed for Bioconductor packages to be uploaded to the Bioconductor AnnotationHub. _--No, users can't provide their own versions of sorted.bed.gz and sorted.bed.gz.tbi they must use our version._  
_We stored  dbNSFP annotation file and tbi on zenodo because the size is 1.3 Gb._

LICENSE

 Do you really need the LICENSE in both formats? You could remove the LICENSE.md file since the MIT license is included with the distribution of R. _--Done: LICENSE.md is removed._ 

NEWS

 Don't have empty news sections. Remove 0.99.0 if it has no subsections or items. _--Done: 0.99.0 was removed from NEWS file._ 

inst

 Include an inst script describing what is provided in inst/extdata and any relevant source information. _--Done: A script folder containing txt files summarizing relevant info was added._ 

vignette

 Change the name of the vignette. Vignette is too generic and could name conflict if there are other packages the user has loaded that choose not to name their vignette. I recommend the name of the package uncoverappLib.Rmd. _--Done, the vignette name was changed in uncoverappLib.Rmd._

 It seems like you can run run.uncoverapp() without specifying file.name and tbi so why is defining these before running the app important? If those files are required than the app shouldn't launch if they aren't available. _-- Yes, app can work without annotation files just for plot function and binomial distribution function (basic mode). Specifying file.name and tbi are mandatory to use annotate functions._ 


 Can a user provide their own versions of sorted.bed.gz and sorted.bed.gz.tbi? How are these important? Why should they be specified when it seems like the app doesn't need them to run.
_-- No, the users can't use their own versions. The underlying script recalls sorted.bed.gz and sorted.bed.gz.tbi to annotate bed file._ 

 Again spell check there are typos. example 'obteined'

 In Section 2 Installation and example. You mention an example file is a BED file containing genomic positions of POLG gene. Describe how this was generated. You don't indicate that its location is anywhere for use? --Done: now a BED file with POLG gene could be generated directly on the "preprocessing" page from BAM file stored in extdata.  


 Section 3: How do you know what samples are available? _-- Done: explanation about samples number was added_ 
 With your example POLG.example.bed.gz , then in the next section you mention the HGNC official gene name -- maybe provide example gene name that can be used. _-- Done: an example of file was added_ 

This whole section, provide example of input to the sidebar that the user can run with the POLG.example.bed.gz. Values that would populate the other tabs in the app.
 You don't make mention of the output that appears in the terminal console. I assume it mimics the tables appearing in the shiny app. _--Done: required inputs are specified and related outputs are shown in vignette._ 

** R / Man Pages**

Don't make the package documentation internal. We recommend having a
package help page available to the users. -- I tried to create a help folder also in repository but I have a warning 

MY NOTE
In shiny app I use some function of `dplyr `package, but I have a boring warning because I use also `select `function from OrganismDbi library. To resolve this issue I put dplyr library in suggest packages and I recall function with `"dplyr::" `definition. 

I'm available for any clarification.

Manuela

**Comment by lshep** [comment]
Thank you for your updates.  Some additional comments based on running through the vignette again:

- [ ] I would suggest creating a helper function in R to download the files from Zenbo for
  the user and storing them with BiocFileCache.  The helper function should
  download if the files have not been cached yet or return the paths to the
  files to be used in the application. 

- [ ] Please use `message` instead of `print` 

- [ ] The links to the mygene.txt file and BAM file should not point to github.
  use the generic code to point to extdata files on a users system asssuming
  they have already installed your package. For example:

```
system.file("extdata", "mygene.txt", package="uncoverappLib")
```

- [ ] Check over your vignette carefully! you currently don't execute any code
  so it will be very easy to have typos.  For instances in section 3 you say
  `and launch run.converappLib() command.`  But that command doesn't exist
  because your function is `run.uncoverapp()`

- [ ] Why not submit the accompanied unCOVERApp to Bioconductor as well so
  Bioconductor users have full access to all parts of the shiny app through
  Bioconductor packages?  

- [ ] It seems at the very least the script that is
  referenced should also be in the current package and a helper function to run
  and create the necessary file for input.  Thereby giving Bioconductor users
  the option to have a fully functioning app within your package itself.  

Cheers, 
L

**Comment by Manuelaio** [comment]
Dear lsheep, 
I have just finishing to review my code given your suggestions. I would like to thank you for bringing me to know **BiocFileCache** library, it is exactly what I was looking for obtain an absolute paths of downloaded files. Before loading reviewed version, I would like to know if is possible remove the hash linked to downloaded file from absolute path. 
For example the output of download function are: 

`"/Users/myname/Library/Caches/uncoverappLib/72d25212f59_sorted.bed.gz"
"/Users/myname/Library/Caches/uncoverappLib/72d25ab8f1a_sorted.bed.gz.tbi" ` 

I would remove 72d25212f59_ and 2d25ab8f1a_. In my package, the downloaded files must have the same name because **tbi** is the index file of **bed**.  I have read the vignette but I don't found this option, do you any suggestion please? 
Many thanks, best wishes 
manuela

**Comment by lshep** [comment]
No there is no option to remove the additional identifiers since this allows for multiple versions of the same file / filename to be cached.  The work around/trick I think some have done in the past is to use the FilePath option to save the files and then use links to rename.  I'll try to look up the exact code / package that was doing this for reference.

**Comment by lshep** [comment]
I'll discuss with the implementation team about giving an option to remove unique identifiers but there is no guarantee that this will be implemented.   If you need the raw bam and bai files instead of having the hubs load the bam file already with Rsamtools::BamFile (DispathClass = BamFile) ,  I suggest looking at the implementation in the chipseqDBData package. They have an internal function called `.linker`  and had the DispatchClass as FilePath.

**Comment by Manuelaio** [comment]
@lshep thank you so much, I think that I just work something out; I'll load a new version soon for you to review. Cheers

**Comment by Manuelaio** [comment]
Hi, I have pushed a new version but in Windows server I have this error 

`Warning: download failed
  web resource path: 'https://zenodo.org/record/3747448/files/sorted.bed.gz'
  local file path: 'C:\Users\pkgbuild\AppData\Local\uncoverappLib\uncoverappLib\Cache/174c6d1110b6_sorted.bed.gz'
  reason: Service Unavailable (HTTP 503).`

Do you think it could be caused by zenodo server, busy after 2 previous test, or is a bug in my code? Thank you

**Comment by lshep** [comment]
We were running updates to R yesterday. It might have disrupted it.  I'll manually kick off a new build to see if it fixes it.  Since this is an outside server we cant offer much advice which is why we encourage the use of the ExperimentHub/Bioconductor S3 buckets for storing data.

**Comment by Manuelaio** [comment]
@lshep thank you, I run on my macOS

`devtools::check_win_(pkg = ".")`

and I riceve the report after 25 minutes without errors or timeout, I riceve only some notes. 
Do I need to add `longtests`? thanks

**Comment by Manuelaio** [comment]
Dear Lori, 
Thank you very much for the previous review,  I had to work at it but I hope that I have implemented all your suggestions,  as follow: 

I would suggest creating a helper function in R to download the files from Zenbo for
the user and storing them with `BiocFileCache`. The helper function should
download if the files have not been cached yet or return the paths to the
files to be used in the application. -->  _Done, I have created a function given BiocFileCache vignette suggestion. The function `getAnnotationFiles(verbose=TRUE)` downloads and rename. The function returns a path of downloaded and renamed file.  I used_ `uncoverappLib::getAnnotationFiles()`  _in shiny-code in order to automatically load this file in the app, therefore it is not necessary set R environment before load the application each time (last version file.name= “/path/”, tbi= “/path/”). Users just  need to use download and rename  function only once._  

The links to the mygene.txt file and BAM file should not point to github.
use the generic code to point to extdata files on a users system asssuming
they have already installed your package. --> _Done, I added_ 
`system.file("extdata", "mygene.txt", package="uncoverappLib") ` _instead github link._

Why not submit the accompanied unCOVERApp to Bioconductor as well so
Bioconductor users have full access to all parts of the shiny app through
Bioconductor packages? -->  __If we have correctly understood, uncoverappLib contains entirely the software unCOVERApp, in_ `shiny-dir` _folder. I basically kept them separately  because I ready sent a paper with  unCOVERApp.__ 

It seems at the very least the script that is
referenced should also be in the current package and a helper function to run
and create the necessary file for input. Thereby giving Bioconductor users
the option to have a fully functioning app within your package itself. -->  _Done, I have added an addition function to prepare input file (buildInput) instead a R script . 
This function could be helpful  to prepare input file if many genes (i.e. >50) are be analyzed as reported in vignette in which I strongly hope to remove all typing errors._

Thank you 
Kind Regards

**Comment by lshep** [comment]
From running the vignette again, I have the following comments/concerns/questions: 

- [ ] Why is all your R code in eval=FALSE code blocks? You should be able to evaluate the code chunks. 
  Updated: from running the code chunk I am guess it was time to take todownload the files? 
  Is there a way to make a smaller example bam and bai file that would suffice to demonstrate your package for the vignette 
  but then advertise the full file for actual runs?  

- [ ] Maybe have a message in the getAnnotatinoFiles function that this will take a long time to run the first time and subsequent runs will be faster?

- [ ] Any output directory in the vignette should reference `tempdir()` for a user running it not `/Your directory/`

**Comment by Manuelaio** [comment]
Dear Lori,
Thank you for your review, following my answers 

- Why is all your R code in eval=FALSE code blocks? You should be able to evaluate the code chunks. --> 
_Done, except for:_ 
```
install.packages("BiocManager")
BiocManager::install("uncoverappLib")
```
- Updated: from running the code chunk I am guess it was time to take to download the files?
You should make a smaller example bam and bai file that would suffice to demonstrate your package for the vignette
but then advertise the full file for actual runs. _--> _Done, I have added a short annotation file only for vignette, in particular I have added a_ `vignette=TRUE` _option in oder to quickly test the package._ 

-  Maybe have a message in the getAnnotatinoFiles function that this will take a long time to run the first time and subsequent runs will be faster? -->  _Yes,  I put sever messages during download phase. _ 

- Any output directory in the vignette should reference tempdir() for a user running it not /Your directory/ --> _Done, I replaced_ `/Your directory/` _to_ `tempdir()` _in vignette._ 

If I correctly understand , the new submission regards the new packages, anyway please let me know if I'm wrong . 
Thank you!
Kind Regards

**Comment by lshep** [comment]
Sorry for the delay in the re-review I was away on vacation.  I will have a look at the package shortly.

**Comment by lshep** [comment]
Thank you for making the improvements.  Cheers

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Manuelaio.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("uncoverappLib")`. The package 'landing page' will be created at

https://bioconductor.org/packages/uncoverappLib

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
