### ISSUE TITLE
Including multiGSEA in Bioconductor

### ISSUE THREAD

**Issue by boll3** [Bioconductor/Contributions#1483]
- Repository: https://github.com/yigbt/multiGSEA

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by boll3** [comment]
Apparently the build system on Windows was not able to clone the git repo.
It worked smoothly on linux and the last time on windows. I didn't change anything that might cause this issue. 

Any help is much appreciated.

**Comment by mtmorgan** [comment]
best guess is that this is a transient github failure; can you try a version bump again?

**Comment by boll3** [comment]
Hi @mtmorgan,

we have now passed the build process without errors or warnings. We have only a few remaining notes regarding some coding style issues.

1) We added runnable examples for each function. To present some more function calls in those examples, we also add \donttest sections. We explicitly used the \donttest section, since these would significantly increase the building time of the package.

2) Line lengths longer than 80 characters and line indent with multiples of four.
We tried to keep lines within 80 chars as often as possible, but especially in combination with multiple line indents this was not always to be accomplished.
And for readability we would like to keep the remaining line the way they are.

Can we ignore these notes for now, or should we take care of all notes to accomplish a completely clean build report?

Thanks a lot for your help!

Cheers,

boll3

**Comment by mtmorgan** [comment]
DESCRIPTION

- Please spell check the Description: field, vignette, and man paages

vignettes

- please reconsider the merit of including conda installation instructions; using conda causes frequent confusion on the support site.

- please update teh Bioconductor installation instructions 'as if' the package were available on Bioconductor

- Please do not include the command-line installation instructions, since a major source of problem with Bioconductor packages is mixing packages from different Bioconductor releases.

- is it necessar to load several packages manually? Are these not loaded as part of your package Depends: and Imports: directives?

- since your package already depends on common 'tidyverse' packages, maybe the `data()` objects should be `tibble` for better and more modern display

- multiGSEA.rmd:317 please avoid long lines, even in `echo=FALSE`

    ```
    kable( 
        df %>% 
        dplyr::arrange( combined_padj) %>% 
        dplyr::select(c( 
            transcriptome_padj, proteome_padj, metabolome_padj, combined_padj
        )) %>% 
        dplyr::slice( 1:15), caption = caption
    )
    ```

R (comments on specific lines should be applied throughout the code base)

- functions.r:240 perhaps better than a long `if ()` statement is along the lines of

    ```
    map <- c(hsapiens = "org.Hs.eg.db", rnorvegicus = "org.Rn.eg.db", ...)
    stopifnot(organism %in% names(map))
    pkg <- map[[organism]]
    ```
    
- functions.R:276 avoid parsing and evaluating text

    ```
    get(pkg, envir = getNamespace(pkg))
    ```

- functions.R:335 these are scalar logical operations, use `&&`

- functions.R:335 reduce code duplication

    ```
    if (returntype %in% c("DTXCID", "DTXSID", "HMDB") && length(map) > 0)
        map <- paset0(returntype, map)
    ```

- functions.R:416 does `str_detect()` provide meaningful improvement over base R string functions? if not avoid this package dependency.

- functions.R:451 avoid long lines with nested logic, which are hard to read

    ```
    dbs0 <- pDBs %>% 
        filter( .data$species == organism ) %>% 
        pull( .data$database) )
    dbs <- as.vector( dbs0 )
    ```

- functions.R:858 use `file.path()` rather than `paste0()` when constructing file paths

- functions.R:916 this line is evaluated when the package is built (on the build machine), but presumably requires evaluation on the user machine (in a `.onLoad()` function); it seems unlikely that this is needed now...

- consider refactoring `functions.R` into separate files containing logically related functions, so that it is easier to navigate the source code. Follow the 'one source file / one man page' model, where functions in a single file are documented on the same man page.

- consider using the `styler` package to format your code into a more standard foramt, 

    ```
    style_pkg(".", transformers=tidyverse_style(indent = 4))
    ```
data

- 'metabolitesMapping' is a large file; does it make sense to make this an [ExperimentHub][] resource and [package][], both for better distribution and for re-use across packages?

[ExperimentHub]: https://bioconductor.org/packages/devel/bioc/html/ExperimentHub.html
[package]: https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

tests

- thanks for including unit tests

**Comment by mtmorgan** [comment]
please let me know when you plan to have a revision available.

**Comment by boll3** [comment]
First of all, thanks for your comments!
I'm done including all the suggestions you made.
I also excluded the 'metabolitesMapping` table from this package and designed a stand-alone AnnotationHub package. As soon as this one is available, and I can use the data in the multiGSEA package, I will push the revison into the repo.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/boll3.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("multiGSEA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/multiGSEA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
