### ISSUE TITLE
cBioPortalData

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#1488]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/cBioPortalData
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
The review of this package needs to wait until the AnVIL package has been accepted & built on the build servers... :(

**Comment by LiNk-NY** [comment]
Shouldn't it be available on the SPB after submission?

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 

`cBioPortalData` was released previously on GitHub https://github.com/waldronlab/cBioPortalData/releases/tag/v1.0 to the cBioPortal collaborators. 

Can we make an exception to release a `2.0.0` version of the package? 

Thank you!
Marcel

**Comment by Kayla-Morrell** [comment]
Hi @LiNk-NY, that should be fine. Thanks for checking!

**Comment by LiNk-NY** [comment]
Thanks Kayla! @Kayla-Morrell 
It's ready when you are. I would like the package to be added to the release branch :speak_no_evil: 
Best,
Marcel

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: I'm a bit confused if this is meant to be a Software package 
or an Experiment Data package. You have used Experiment Data biocViews, but 
normally an Experiment Data package accompany a Software package, doesn't 
contain R code, have thorough vignettes, or export objects/classes. 

- [ ] REQUIREMENT: y of x.y.z version should be even in release. But I think 
we have discussed this.

## Vignettes

These were never run through BiocCheck because of the experiment 
data biocViews used.

- [ ] REQUIRED: There should be 'Introduction' and 'Installation' sections in 
the vignettes. The 'Installation' sections should demonstrate to the users 
how to download/install the package from Bioconductor (not GitHub).

*cBioPortalData*

- [ ] REQUIRED: This vignette should have a session info section to it.

## Man pages

- [ ] REQUIRED: There could be a bit more information in the man page of
the class. Man pages describing new classes must be very detailed on the 
structure and what type of information is stored.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] REQUIRED: Unexported object imported by a ':::' call: 
'rappdirs:::get_os'.

- [ ] REQUIRED: Avoid sapply(); use vapply() instead. Found in file:
        - cBioDataPack.R, line 183 and 186

- [ ] REQUIRED: Avoid '<<-' if possible, found in 2 files:
        - cBiocPortal.R, line 208
        - cBioPortalData.R, line 75

- [ ] SUGGETION: Consider shorter lines, 6 lines are > 80 characters long.

- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents, 90 lines 
are not.

Best,
Kayla

**Comment by LiNk-NY** [comment]
Thank you Kayla @Kayla-Morrell for the review.
Please see my responses below:

> ## DESCRIPTION
> * [ ]  REQUIRED: I'm a bit confused if this is meant to be a Software package
>   or an Experiment Data package. You have used Experiment Data biocViews, but
>   normally an Experiment Data package accompany a Software package, doesn't
>   contain R code, have thorough vignettes, or export objects/classes.

The package is a hybrid of the two. It's an Experiment Data package because it serves data from the web and I think it should be labeled as such for users looking to download cBioPortal data. It is also a software package given that it is the software interface to the API. I am not sure how to best categorize the package so that it takes advantage of both modalities. 

> * [ ]  REQUIREMENT: y of x.y.z version should be even in release. But I think
>   we have discussed this.

I think the version bump will be made by Bioc members "releasing"
the package though I am not sure.

> ## Vignettes
> These were never run through BiocCheck because of the experiment
> data biocViews used.

Is there a way to override this? I thought all vignettes were run. 

> * [x]  REQUIRED: There should be 'Introduction' and 'Installation' sections in
>   the vignettes. The 'Installation' sections should demonstrate to the users
>   how to download/install the package from Bioconductor (not GitHub).
> 
> _cBioPortalData_
> 
> * [x]  REQUIRED: This vignette should have a session info section to it.
> 
> ## Man pages
> * [x]  REQUIRED: There could be a bit more information in the man page of
>   the class. Man pages describing new classes must be very detailed on the
>   structure and what type of information is stored.
> 
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them.

I can add these in the near future. I'd like to at least have some sense of versioning
for the API specification (as Martin mentioned in today's meeting with `AnVIL`).

> ## R code
> * [ ]  REQUIRED: Unexported object imported by a ':::' call:
>   'rappdirs:::get_os'.

I understand the consequences of using an unexported triple colon function and
I am willing to adjust the code if that were to ever change. 

> * [x]  REQUIRED: Avoid sapply(); use vapply() instead. Found in file:
>   - cBioDataPack.R, line 183 and 186

Old code was removed.

> * [ ]  REQUIRED: Avoid '<<-' if possible, found in 2 files:
>   - cBiocPortal.R, line 208
>   - cBioPortalData.R, line 75

I don't usually use double arrow assignment but in order to avoid multiple
API calls, I create side effect objects from one single call to the API. I could
use `assign` and modify the object in the parent environment. 

> * [x]  SUGGESTION: Consider shorter lines, 6 lines are > 80 characters long.
> * [ ]  SUGGESTION: Consider multiples of 4 spaces for line indents, 90 lines
>   are not.

These are a work in progress. Thank you.
-Marcel

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 

Regarding
* [ ] SUGGESTION: Consider multiples of 4 spaces for line indents, 90 lines
are not.

, it seems like most of the lines for this are due to `roxygen2`. I've tried looking for an
option to make documentation indentation 4 spaces instead of two but I am
not sure this is possible. I added a comment here: https://github.com/r-lib/roxygen2/issues/332
This is a closed issue and may not get any attention if there is not enough demand.

**Comment by LiNk-NY** [comment]
Also, @Kayla-Morrell I know you're very busy but I would like this package to be
accepted as soon as possible. It is part of a manuscript submission and I would like it
to be in the release branch of Bioconductor before sending our response to the
reviewers. Thank you so much!

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - I should be able take another look at everything in a couple hours. Thanks for your patience!

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - Thanks for making the necessary changes. I've looked everything over and it looks good to go. I'd be more than happy to accept the package. Thanks again for your contribution!

**Comment by LiNk-NY** [comment]
Thank you Kayla! @Kayla-Morrell :pray: 

Can the package be added to the release manifest? @mtmorgan

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cBioPortalData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cBioPortalData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
