### ISSUE TITLE
RadioGx resubmission

### ISSUE THREAD

**Issue by ChristopherEeles** [Bioconductor/Contributions#1490]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/RadioGx

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# RadioGX review 

## R CMD build

ok

## R CMD INSTALL 

ok

## DESCRIPTION

ok

## NAMESPACE 

ok

## vignette

* Ok. 

  It seems there will be more details added to the vignette to
  make it more complete.
  
## R

* Replace 

		##FIXME:: Why write as character and convert to numeric?
		D <- as.numeric(c("0","1","2","3","4","5","6","8","10"))

  with

		D <- c(0:6,8,10)

  You can check with `class(D)` and it'll show you it's `numeric`.


* As I mentioned in the review for `PharmacoGx` as well, there is a
  real formatting inconsistency in your codebase. This makes it very
  hard for a reviewer to follow. Specifically, consider the 2 space
  indent vs 4
  space. http://bioconductor.org/developers/how-to/coding-style/
  
  There are multiple NOTES in your build report (NOTE count: 8 ). The
  build report acts as a way for you to correct the NOTES before the
  reviewer takes a look. I will point out some of them below. I'm
  particular about the sapply() issue, please rectify that. The other
  ones, i'm less particular about, but consider fixing those as well.
  
  1. Do not use 'sapply()'
 
``` 
		* NOTE: Avoid sapply(); use vapply()
			Found in files:
			  computeSensitivity.R (line 94, column 12)
			  computeSensitivity.R (line 95, column 11)
			  doseResponseCurve.R (line 287, column 18)
			  geneDrugSensitivity.R (line 36, column 27)
			  plotCurve.R (line 96, column 13)
			  radSensitivitySig.R (line 195, column 24)
			  radSensitivitySig.R (line 214, column 17)
			  radSensitivitySig.R (line 220, column 14)
			  rankGeneDrugSensitivity.R (line 104, column 24)
			  rankGeneDrugSensitivity.R (line 107, column 25)
			  rankGeneDrugSensitivity.R (line 121, column 26)
```


   2. There are also no test cases for such an extensive codebase in
      this package. `testthat` makes it very easy to write test cases.
	  
	  Please consider writing some test cases.
	  
   3. As I mentioned about the formatting, the build report throws the
      same as a NOTE,
	  

```
		* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
		and vignette source...
		  * NOTE: Consider shorter lines; 345 lines (6%) are > 80 characters
			long.
		  First 6 lines:
			R/computeAUC.R:82     CoreGx::.sanitizeInput(pars = pars, # Added this ...
			R/computeAUC.R:107       return(pars[[1]] / 2 * (lower ^ 2 - upper ^ 2)...
			R/computeAUC.R:113           return((exp(-pars[[1]] * lower) - exp(-par...
			R/computeSensitivity.R:1 ## This function computes pars/AUC/SF2/D10 for...
			R/computeSensitivity.R:28     pars <- lapply(names(AUC), function(exp, ...
			R/computeSensitivity.R:29       if(length(grep("///", raw.sensitivity[e...
		  * NOTE: Consider 4 spaces instead of tabs; 32 lines (1%) contain
			tabs.
		  First 6 lines:
			R/RadioSetClass.R:1269   	exps <- adArgs[["exps"]]
			R/RadioSetClass.R:1270   	if(is(exps,"data.frame")){
			R/RadioSetClass.R:1271   		exps2 <- exps[[name(object)]]
			R/RadioSetClass.R:1272   		names(exps2) <- rownames(exps)
			R/RadioSetClass.R:1273   		exps <- exps2
			R/RadioSetClass.R:1274   	} else{
		  * NOTE: Consider multiples of 4 spaces for line indents, 1399
			lines(23%) are not.
		  First 6 lines:
			R/computeAUC.R:38                        SF_as_log = FALSE,
			R/computeAUC.R:39                        area.type = c("Fitted", "Actua...
			R/computeAUC.R:40                        verbose = TRUE)
			R/computeAUC.R:41   {
			R/computeAUC.R:42   area.type <- match.arg(area.type)
			R/computeAUC.R:44   if (!missing(SF)) {
		  See http://bioconductor.org/developers/how-to/coding-style/
		  See FormatR package:
			https://cran.r-project.org/web/packages/formatR/index.html

```

   Based on your previous response, (during the CoreGx package
    review, and I asked to uniformly fix them across all the
    packages). It seems like some of these issues which I raised in my
    last review still persist. You spoke of an upcoming
    "refractor". Any idea when this is going to happen? Please keep in
    mind, when you have such a massive code refractor to improve the
    codebase , why not do it before the review and make it easier for
    the reviewer as well?

		Coding style: I realize that some of our functions are hard to
		read, we are in the process of refactoring all four packages
		(CoreGx, PharmacoGx, RadioGx, ToxicoGx) and plan to get the
		codebase in shape within a month or two. Until then please let me
		know if there are any style issues I should address immediately


* There are still some slots in your object being accessed with the
  '@' function. eg: `object@curation`

* I highly recommend you break up the file RadioSetClass.R, the file
  has over 1700 lines of code which are complex. Break it up into
  multiple files if needed, the functions can be made easier too by
  writing a few helper functions. This will also help you be able to
  debug in case something goes wrong in your code, since there are no
  test cases.


## General

Since you are aiming to get this in for the conference, please make as many updates as you can and leave a reply on each point detailing what is possible and what isn't at the moment. That way we can move forward to package acceptance in a faster way.

**Comment by ChristopherEeles** [comment]
1. **Vignette** 
- Expanded current vignette to include computation of common radiation dose-response metrics from a RadioSet and a fitted linear-quadratic model. 
- Next steps for the vignette is to add section on detecting molecular signatures of radiation response, this will be written over the next month as we prepare for our workshop at Bioc 2020.

2. **Replace**
- Line now reads: D <- seq(0, 10 ,1) and comments removed

3. **Formatting inconsistency**
- I agree that the formatting consistency is an issue; the codebase was developed by a number of summer and graduate students over several years. I working on cleaning it up but am currently the only full-time R developer in our lab so it will take some time.
- Noted the 4 space issue; I tried to fix with quick regex but it didn't work; this will be my first formatting priority for all Gx packages.

4. **Notes**
- I believe I have removed all sapply statements
- Shorter lines and shorter functions are an item on the list for the refactor, but the first steps are going to be minimizing redundancy between all Gx packages
  - I expect we will end up throwing away a lot of code, so I feel I should address formatting after we finish rewriting longer functions

5. **Tests**
- I also agree tests are important, I think it makes the most sense to start with CoreGx since those functions are inherited by all Gx packages
- Unless you think it is essential I would prefer to address the unit testing issue in the future (once we have finished minimizing redundancy between packages and rewriting function

6. **Refactor**
- RadioGx and ToxicoGx were already on CRAN, we had hoped to get them into Bioconductor quickly then start the refactor with CoreGx -> PharmacoGx -> RadioGx -> ToxicoGx
-  Still planning  a major refactor, but I am the only full-time developer working on this and I have to balance my effort between several projects so it will take some time
- Petr Smirnov has already started refactoring functions in PharmacoGx, which will be propagated back into CoreGx as we continue to clean up the code-base

6. **@ Access**
- I have removed all @ slot access outside of accessor methods

7. **RadioSet**
- I broke up the class from its accessor methods, it should be easier to deal with now
- I will do the same in other Gx packages as well

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ChristopherEeles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RadioGx")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RadioGx

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
