### ISSUE TITLE
wpm

### ISSUE THREAD

**Issue by HelBor** [Bioconductor/Contributions#1494]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HelBor/wpm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It would be great to see, e.g., in the vignette, greater integration with Bioconductor packages, either before or after the use of your app.

I think your code should be refactored so that most of the analytic code is in the R/ directory of your package, and your shiny app calls that code `wpm::foo()`. This exposes your code to standard R package build and check benefits, and also exposes your code to examples and tests -- currently, there is no automated way to validate that your code performs correct calculations.

Your reviewer will provide additional comments, but I strongly encourage you to make these changes proactively.

**Comment by HelBor** [comment]
@mtmorgan 
> It would be great to see, e.g., in the vignette, greater integration with Bioconductor packages, either before or after the use of your app.

I'm not sure I understand your suggestion, should I put a sentence suggesting to use this or this BioConductor packages before/after using wpm?

> I think your code should be refactored so that most of the analytic code is in the R/ directory of your package, and your shiny app calls that code `wpm::foo()`. This exposes your code to standard R package build and check benefits, and also exposes your code to examples and tests -- currently, there is no automated way to validate that your code performs correct calculations.

I tried with a structure where all .R scripts where in the ./R folder (and not the actual ./inst/wpmApp folder) but I didn't make it work properly...

**Comment by mtmorgan** [comment]
@HelBor not just suggesting, but actually doing -- I have no idea about what your package actually does, but maybe preparing data via other packages is appropriate (and modifying your app so that the user can say the equivalent of `runApp(<my Biocoonductor object>)` rather than having things file based). Likewise illustrating how the output of your package could used in visualization / etc, without having to go through a ton of steps. Basically I'm looking for evidence that your package interoperates with the Bioconductor ecosystem, rather than is just a package that does something that is related to topics that Bioconductor has packages available for. [Common classes and methods][1] might be a starting point.

It makes me nervous that you are not able to restructure your package as I suggested; it suggests that the code is not organized in a robust manner. I think you should try further, maybe asking for (specific) advice on the [bioc-devel][2] mailing list or [community slack][3]

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[3]: https://bioc-community.herokuapp.com/

**Comment by dvantwisk** [comment]
Hello,

I'm checking into to see if you've made any progress with this. I've reviewed what you currently have and the code looks well written, but the issue with interoperability with Bioconductor that Martin Morgan brought up should still be addressed. Do you need help on how to address this issue? If so, please message us back.

We usually want to see package submissions being actively worked on, that is, have updates made to the package within a two week period. We usually close issues if they have not seen activity for two weeks. Closed issues can be opened again when the submitter is ready to actively work on making changes to the package. This is just a notice that we may temporarily close this issue if we don't see activity soon.

**Comment by HelBor** [comment]
Hello,
I am in the process of finalizing the restructuring of the code to respond to suggestion n°1 of Martin Morgan and I counted push today at the end of the day.
Regarding interoperability with Bioconductor, I am still working on it, for the moment I don't think I need any particular help.
I am sorry for this inactivity on this issue, I will correct that.

**Comment by dvantwisk** [comment]
Looks like you are making progress on this. Message us back when you are finished making changes so we can review the package again.

**Comment by HelBor** [comment]
Dear Bioconductor Reviewers,
I have finished making all the requested changes to the package. The Bioc-issue-bot having put the label "OK", I suppose you can now check my package.
I remain at your entire disposal for any questions.

**Comment by dvantwisk** [comment]
I've reviewed your package. It looks very well written and I really don't have anything more of substance to add. Thank you for making the original changes. I am going to move to accept your package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HelBor.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("wpm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/wpm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
