### ISSUE TITLE
CytoTree

### ISSUE THREAD

**Issue by ytdai** [Bioconductor/Contributions#1501]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JhuangLab/CytoTree

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Yuting, @ytdai 
Thank you for your submission. I will review your package today. 
Best,
Marcel

**Comment by ytdai** [comment]
> Hi Yuting, @ytdai
> Thank you for your submission. I will review your package today.
> Best,
> Marcel

Dear Marcel:

Thank you. The CytoTree package is the updated version of the flowSpy package in Bioconductor (https://bioconductor.org/packages/flowSpy/). For some reason, we had to change the package name of flowSpy to CytoTree. Most functions and workflow in CytoTree are the same as flowSpy. After discussed with the Bioc team, I submitted CytoTree as a new package to GitHub for traditional review. The update of flowSpy will continue until the end of 3.11. And for the 3.12 devel, flowSpy will be deprecated.  

Thank you for reviewing my package.

Best,

Yuting Dai

**Comment by LiNk-NY** [comment]
Hi Yuting, @ytdai 

Thank you for your submission. 
Please see the review below.

If you have any questions, feel free to post them here. 

Best,
Marcel

---

# CytoTree #1501

* Example code in examples, vignettes, unit tests, are meant to guarantee that
a package is working for the users. The absence of this code in your package
does not look favorable for users who would like to replicate a workflow.
Please include working examples and a substantial vignette for users who
do not want to access your online resources or who have limited internet
connectivity on their servers.

## DESCRIPTION

* Looks good
* Remove empty fields from the file

## vignettes

* Is there a reason why you link to the website instead of providing
a vignette that is built nightly with other packages?
* Do you have continuous integration set up on tutorial documents?
* My concern is that content like this will become stale because it is not
regularly updated and checked as it would if it were a vignette in the
package.
* An alternative to consider is to have the vignettes from the linked
website built from the package and served to `github.io` using something like
the `pkgdown` package

## R

* It is redundant to use 'ERROR', 'WARNING', etc. tags with the appropriate
functions. `stop` already returns an explicit error message.
* Why not use the `%in%` generic in `BiocGenerics`?
* Avoid using `if (FALSE)` in the examples. This creates stale code, provide
code that users can run if they need to test a function. If you data is large
provide a small example dataset for testing and use within the examples.
* Avoid using `1:ncol(x)` sequence generation use `seq_along(x)` or
`seq_len(ncol(x))`
* Rename R files so that they match with the function (e.g., `subsetCYT()` in
`subsetFSPY.R`)

**Comment by ytdai** [comment]
Hi Marcel

Thank you very much for reviewing the package.

According to your comments, I have changed the code of the package. The newest version of CytoTree is 0.99.4. The response and modification was attached below.

As for the ERROR message on the build bin of CytoTree on macOS, I didn't meet this error when I was running `R CMD install` on my MacBook. Could you please help me to fix it?

The link is http://bioconductor.org/spb_reports/CytoTree_buildreport_20200604141703.html

Thank you very much.

Best,

Yuting Dai
2020-06-05


## DESCRIPTION
- Looks good
- Remove empty fields from the file

[A] The empty fields were removed.

## vignettes
- Is there a reason why you link to the website instead of providing a vignette that is built nightly with other packages?
- Do you have continuous integration set up on tutorial documents?
- My concern is that content like this will become stale because it is not regularly updated and checked as it would if it were a vignette in the package.
- An alternative to consider is to have the vignettes from the linked website built from the package and served to github.io using something like the pkgdown package

[A] For the first question, if the detailed tutorial was included in the package, the size of the package will be so large. So I chose to put the tutorial on the website. 

For the second question, I have continuous integration set up for the tutorials. The update of the tutorials was controlled by another GitHub project (https://github.com/JhuangLab/CytoTree-dataset). I used Rmarkdown to control the entire workflow to generate tutorials of this package. Once the package is modified, I will also update the tutorials on the website.

And for the third and fourth questions, I can ensure to keep synchronous updates for both the package and tutorial.


## R
- It is redundant to use 'ERROR', 'WARNING', etc. tags with the appropriate functions. stop already returns an explicit error message.
- Why not use the %in% generic in BiocGenerics?
- Avoid using if (FALSE) in the examples. This creates stale code, provide code that users can run if they need to test a function. If your data is large provide a small example dataset for testing and use within the examples.
- Avoid using 1:ncol(x) sequence generation use seq_along(x) or
seq_len(ncol(x))
- Rename R files so that they match with the function (e.g., subsetCYT() in subsetFSPY.R

[A] Yes, I agree it is redundant to use 'ERROR', 'WARNING' and 'INFO'. These habits come from the writing style of Perl packages. In fact, these massage tags do not affect the function. With the message tags, I think the output information are more eye-catching. So I decided to keep it.

For the second question, I have deleted the `%in%` generic in BiocGenerics. %in% generic was not used in this package.

For the third question, the workflow of this package was in series. For example, if users want to run function E, they must run functions A, B, C, D step by step in advance. So it is hard to provide a small example of a dataset for testing. I have added an example file in extdata, and all `if (FALSE)` were removed.

For the fourth question, all 1:ncol(x) were changed to seq_along(x) or seq_len(x).

For the fifth question, the name was changed.

**Comment by ytdai** [comment]
Hi Marcel, @LiNk-NY 

Thank you very much for reviewing the package.

According to your comments, I have changed the code of the package. The newest version of CytoTree is 0.99.4. The response and modifications were attached below.

As for the ERROR message on the build bin of CytoTree on macOS, I didn't meet this error when I was running `R CMD install` on my MacBook. Could you please help me to fix it?

The link is http://bioconductor.org/spb_reports/CytoTree_buildreport_20200604141703.html

Thank you very much.

Best,

Yuting Dai
2020-06-05


## DESCRIPTION
- Looks good
- Remove empty fields from the file

[A] The empty fields were removed.

## vignettes
- Is there a reason why you link to the website instead of providing a vignette that is built nightly with other packages?
- Do you have continuous integration set up on tutorial documents?
- My concern is that content like this will become stale because it is not regularly updated and checked as it would if it were a vignette in the package.
- An alternative to consider is to have the vignettes from the linked website built from the package and served to github.io using something like the pkgdown package

[A] For the first question, if the detailed tutorial was included in the package, the size of the package will be so large. So I chose to put the tutorial on the website. 

For the second question, I have continuous integration set up for the tutorials. The update of the tutorials was controlled by another GitHub project (https://github.com/JhuangLab/CytoTree-dataset). I used Rmarkdown to control the entire workflow to generate tutorials of this package. Once the package is modified, I will also update the tutorials on the website.

And for the third and fourth questions, I can ensure to keep synchronous updates for both the package and tutorial.


## R
- It is redundant to use 'ERROR', 'WARNING', etc. tags with the appropriate functions. stop already returns an explicit error message.
- Why not use the %in% generic in BiocGenerics?
- Avoid using if (FALSE) in the examples. This creates stale code, provide code that users can run if they need to test a function. If your data is large provide a small example dataset for testing and use within the examples.
- Avoid using 1:ncol(x) sequence generation use seq_along(x) or
seq_len(ncol(x))
- Rename R files so that they match with the function (e.g., subsetCYT() in subsetFSPY.R

[A] Yes, I agree it is redundant to use 'ERROR', 'WARNING' and 'INFO'. These habits come from the writing style of Perl packages. In fact, these massage tags do not affect the function. With the message tags, I think the output information are more eye-catching. So I decided to keep it.

For the second question, I have deleted the `%in%` generic in BiocGenerics. %in% generic was not used in this package.

For the third question, the workflow of this package was in series. For example, if users want to run function E, they must run functions A, B, C, D step by step in advance. So it is hard to provide a small example of a dataset for testing. I have added an example file in extdata, and all `if (FALSE)` were removed.

For the fourth question, all 1:ncol(x) were changed to seq_along(x) or seq_len(x).

For the fifth question, the name was changed.

**Comment by ytdai** [comment]
Hi Marcel, @LiNk-NY 

Last week, I have modified the code of CytoTree and submitted the novel version of CytoTree package to Bioconductor/Contributions. The answers to your comments were also added to the link https://github.com/Bioconductor/Contributions/issues/1501. Could you have time to take a look?

As for the ERROR message on the build bin of CytoTree on macOS, I didn't meet this error when I was running R CMD install on my MacBook. Could you please help me to fix it?

Thank you very much.

Yuting Dai
2020-06-11

**Comment by ytdai** [comment]
Hi Marcel,


Last week, I have modified the code of CytoTree and submitted the novel version of CytoTree package to Bioconductor/Contributions. The answers to your comments were also added to the link&nbsp;https://github.com/Bioconductor/Contributions/issues/1501.&nbsp;Could you have time to take a look?


As for the ERROR message on the build bin of CytoTree on macOS, I didn't meet this error when I was running R CMD install on my MacBook. Could you please help me to fix it?


Thank you very much.


Yuting Dai
2020-06-11












------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marcel Ramos"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 晚上10:02
收件人:&nbsp;"Bioconductor/Contributions"<Contributions@noreply.github.com&gt;;
抄送:&nbsp;"代雨婷"<809449456@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Bioconductor/Contributions] CytoTree (#1501)





 
Hi Yuting, @ytdai
 
Thank you for your submission.
 Please see the review below.
 
If you have any questions, feel free to post them here.
 
Best,
 Marcel
 
 
CytoTree #1501
  
Example code in examples, vignettes, unit tests, are meant to guarantee that
 a package is working for the users. The absence of this code in your package
 does not look favorable for users who would like to replicate a workflow.
 Please include working examples and a substantial vignette for users who
 do not want to access your online resources or who have limited internet
 connectivity on their servers.
  
DESCRIPTION
  
Looks good
 
Remove empty fields from the file
  
vignettes
  
Is there a reason why you link to the website instead of providing
 a vignette that is built nightly with other packages?
 
Do you have continuous integration set up on tutorial documents?
 
My concern is that content like this will become stale because it is not
 regularly updated and checked as it would if it were a vignette in the
 package.
 
An alternative to consider is to have the vignettes from the linked
 website built from the package and served to github.io using something like
 the pkgdown package
  
R
  
It is redundant to use 'ERROR', 'WARNING', etc. tags with the appropriate
 functions. stop already returns an explicit error message.
 
Why not use the %in% generic in BiocGenerics?
 
Avoid using if (FALSE) in the examples. This creates stale code, provide
 code that users can run if they need to test a function. If you data is large
 provide a small example dataset for testing and use within the examples.
 
Avoid using 1:ncol(x) sequence generation use seq_along(x) or
 seq_len(ncol(x))
 
Rename R files so that they match with the function (e.g., subsetCYT() in
 subsetFSPY.R)

**Comment by LiNk-NY** [comment]
Hi Yuting, @ytdai 
Sorry for the delay in getting back to you. 
I will have take a look at your package today.
Thank you for your patience.

**Comment by LiNk-NY** [comment]
Can you try bumping the version to re-build the package? Thanks

**Comment by ytdai** [comment]
> Can you try bumping the version to re-build the package? Thanks

Okay, I am re-building this package now.

**Comment by LiNk-NY** [comment]
Hi Yuting, @ytdai 

I had a look at your response. 
We would prefer that you use a vignette that has a smaller example dataset that fits
inside the package, rather than having a large example hosted elsewhere. You are
free to host these vignettes **independent** of the package but in this instance,
those websites are replacing the functionality of the vignettes that we require. 

We recommend that you use a "toy" example dataset to demonstrate the functionality
of the package. If you would like to publish a more drawn out example, you are
welcome to submit a `workflow` package. We don't really accept vignettes that link
to other websites. Thank you. 

> For the third question, the workflow of this package was in series. For example, if users want to run function E, they must run functions A, B, C, D step by step in advance. So it is hard to provide a small example of a dataset for testing. I have added an example file in extdata, and all if (FALSE) were removed.

If your functionality is to show function E, why not take the results of step D and add a small
dataset of `D` in the package? 

* RE: `stop`

Consider this example for removing redundant keywords from similar functions. 
There is no added value to repeating the "ERROR"/"WARNING" word etc.
```r
stop("ERROR: The function is not working")
# Error: ERROR: The function is not working
```

Thank you. 
-Marcel

**Comment by ytdai** [comment]
Hi Marcel, @LiNk-NY 

Thank you very much.

For the vignettes, I have added a vignette included in the package and remove the link of the vignette on the website.

For the examples, I have added a small example data. So all the examples included in the function are runnable.

And for the redundant keywords, they were all removed.

I hope to get your reply soon, thank you.

Best,

Yuting Dai
2020-06-19

**Comment by LiNk-NY** [comment]
Hi Yuting, @ytdai 
Thanks for making those changes!
Your package has been accepted. 
Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ytdai.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CytoTree")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CytoTree

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
