### ISSUE TITLE
UMI4Cats package submission

### ISSUE THREAD

**Issue by mireia-bioinfo** [Bioconductor/Contributions#1504]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Pasquali-lab/UMI4Cats

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission.  Please see some comments below: 

**build report**

- [ ] strongly recommend unit test to check for correct functionality of the
  package. 

**gitignore**

- [ ] Please also git ignore any extra directories or files for other
  applications.  Like the `dev` directory,  `_pkgdown.yml` file,  `pkgdown`
  directory

- [ ] Make sure doing git clone does not include any of those files/directories

**README**

- [ ] Are both the Rmd and md files necessary? 

- [ ] Make sure to update to pull from the Bioconductor repository for the
  official/stable version than your github (for development) It can include both
  if you like. 


**DESCRIPTION**

- [ ] Please remove `LazyData: true` we have rarely found this useful and can
  slow installation. 

**NAMESPACE**

- [ ] Since your classes extend SummarizedExperiment, I highly recommend
  importing the full package rather than importFrom. The full range of
  functinoality provided by SummarizedExperiments should be automatically
  available to your objects but not without importing the package. 

**inst**

- [ ] Please have an `inst\scripts` that describes what is in and how you
  created any data in `inst/extdata` This should include any source information,
  filtering, etc.  It doesn't have to be strictly code, it can be text or
  sudo-code

- [ ] Citation file should be able to be read independent of package
  installation. The current CITATION will not display properly on Biocoductor. 
  Again `readCitationFile(<pathtofile>)` should run without error wihtout the
  package being loaded. 

**vignette**

- [ ] I suggest renaming the vignette from `umi4cats-usage` to `UMI4Cats` or
  `umi4cats` as it is much more intuitive for a user to just call the package
  name to get the vignette (ie.  `vignette('UMI4Cats')`


- [ ] Why not run with the sample data you provide with
  `downloadUMI4CexampleData()` I haven't looked at the R code yet for this
  function but by default it should use a temp directory not the users working
  directory to download data.  I'm wondering if you implemented any caching
  mechanism so users would not have to download multiple times?  I would suggest
  looking at BiocFileCache.

- [ ] All defined output directorys should write to a tempdir for demo
  purposes (i.e any use of `out_path` in the vignette)


**R/man**

- [ ] downloadUMI4CexampleData should cache the tar files to save time
  downloading in the future.

When ready please leave a comment here responding to the above items and requesting a re-review.  

Cheers,

**Comment by lshep** [comment]
Has there been any progress in updating the package?

**Comment by mireia-bioinfo** [comment]
Yes, I'm so sorry! We're working on it, but we are currently dealing with a lot of stuff, including moving the lab from one city to another, and all work and projects are delayed. We should have everything updated during the next few weeks. I'm so sorry for the delay!

**Comment by lshep** [comment]
No problem.  Thank you for the update.  Let me know if anything is unclear when you are working through it.

**Comment by mireia-bioinfo** [comment]
Hi, sorry for the delay! I did some push addressing the comments above, together with a version bump but seems that the @bioc-issue-bot is not recognizing them... From my side, the webhook is set and still active, so I'm not sure what went wrong... 

I'm waiting to see if the checks are passed to upload a point-by-point response to the comments listed above in order to continue with the submission.

**Comment by lshep** [comment]
I kicked off a manual build to help you move forward that should post shortly.  I would suggest maybe deleting and trying re-establish the webhook. I can look at this more next week after the Bioconductor conference.

**Comment by lshep** [comment]
Sorry for the delay; I was away on vacation. I'll have a look at the packages shortly and post a re-review

**Comment by lshep** [comment]
The package looks much better. 

Minor comment for something to think about.  There are some places you require sequence information.  You might consider upgrading from a character vector to the Biostrings  DNAString or RNAString etc.  since it will have some built in checks for valid sequences.  This is only a minor suggestion and does not prevent the package from being accepted but may make the arguments stronger and more consistent. 

Cheers

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mireia-bioinfo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("UMI4Cats")`. The package 'landing page' will be created at

https://bioconductor.org/packages/UMI4Cats

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
