### ISSUE TITLE
Omixer

### ISSUE THREAD

**Issue by ljsinke** [Bioconductor/Contributions#1507]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/molepi/Omixer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
  _However, since my package relies on setting multiple seeds to create 
  different but randomized sample layouts, there is 1 (unavoidable) WARNING
  on R CMD BiocCheck. I would very much appreciate discussion of this._

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
There should be no ERROR messages before the package review.

**Comment by ljsinke** [comment]
Updated image paths in the vignette. These were causing an error on vignette rebuilding in Linux. Hopefully it will build without ERROR messages on Linux too now.

**Comment by nturaga** [comment]
# Omixer review

## DESCRIPTION

* Description needs to be like a package abstract

* Use Authors@R instead of Author / Maintainer

## NAMESPACE

* ok

## R

* Let the user set the seed as needed.

        * WARNING: Remove set.seed usage in R code
            Found in R/ directory functions:
            omixerRand()
            omixerSpecific()

**Comment by ljsinke** [comment]
Thank you for the review, nturaga. I will make the changes to the Description as you suggest.

However, in regards to setting the seed, due to the nature of the package, I cannot remove it. This package uses a large number of different seeds (default 1000) to create 1000 different random layouts of samples. As far as I know there is no other way for me to create a **specific number of different random layouts** without iteratively changing the seed within the function.

Therefore, for this functionality, unless there is a method I cannot think of, I cannot remove set.seed() from the code. 

In the second function, omixerSpecific(), the seed is one of the options in the function and is well documented stating that this required option will set the seed for the user.

I hope that I have explained clearly and that we can come up with a solution, such as extremely clear documentation to the user and/or warnings printed in the function to ensure that the user is aware of the set.seed() but that I can also provide functionality to optimize using the specified number of random layouts. 

I look forward to hearing your suggestions and feedback.

**Comment by nturaga** [comment]
Regarding the `set.seed()` functionality, I'll suggest a couple of things. But I'm clearly missing some key information, so please help me understand this better.

1. In OmixerRand.R

Take out the `dfRandList` function into its own function so that we can be more objective about it. 

To understand it a little better, why do you need to set 1000 different seeds to create essentially 1000 random samples? 

```
    ## Create list of randomized sample layouts using permSet
    dfRandList <- lapply(seq_len(iterNum), function(x) {
        set.seed(x*999)
        dfShuffle <- df %>% group_by(permVar) %>% 
            slice(sample(seq_len(n()))) %>% ungroup()
        dfRandList <- lapply(seq_len(length(permSet[[x]])), function(y){
            dfRand <- dfShuffle %>% filter(permVar == permSet[[x]][y])
            return(dfRand)
        })
        dfRand <- bind_rows(dfRandList)
        dfRand <- dfRand %>% mutate(seed=x*999)
        return(dfRand)
    })
```

2. In OmixerSpecific.R, why do you need to set the seed twice?? 

```
    df$seed <- seed

    ## Use seed to generate permSet of the specified layout
    set.seed(seed)
    permSet <- sample(unique(df$permVar))

    ## Create randomized sample layout using permSet
    set.seed(seed)
```

You already let the user pass in `seed` as an argument to the function. Essentially at this point, you can just pass a message to the user before the function starts, `message("please use the set.seed() function before running, ignore if you already have")`.

**Comment by ljsinke** [comment]
Thank you for these suggestions and comments, Nitesh. 

The reason for setting the seed in `RandList` was to ensure that the 1000 layouts were different to each other. I suppose on second thought, this is perhaps unnecessary as two seeds are unlikely to be the same. Would you agree? If so, then I can remove `set.seed` from `dfRandList` and instead save the value of `.Random.seed` for each layout and return the optimal one to the user.

Let me know if you think this is a better solution and I will implement it.

Also, in `omixerSpecific` your solution seems great. If I clearly document that the user should `set.seed` before running the function, and print a message as well, then I think this will solve it for this function.

Thank you again for your help.

**Comment by ljsinke** [comment]
Just an update after thinking about this overnight. 

Since I perform multiple random processes to get each randomized list (randomizing the internal order of blocks and then randomizing the list), I'm not sure if I can simply save the first value of `.Random.seed` to allow the user reproduce this process. Each randomized list would be characterized by 2 random seeds if no seed is set.

Therefore, I'm very unsure how to provide a function that can reproduce the randomized layout quickly for the user after they have used `set.seed`, without using `set.seed` in the randomization function. It seems I could remove `set.seed` from one of the functions, but not both.

I will keep trying to think of a solution that works without setting the seed internally.

**Comment by ljsinke** [comment]
Another update:

I have found a solution to store the appropriate `.Random.seed` and am implementing this, along with other discussed changes, now.

I hope to push this update before the end of the week.

Thank you for all your help!

**Comment by ljsinke** [comment]
The changes have worked and there is no more `set.seed` in the code of Omixer.

The vignette also details how to use the saved `.Random.seed` to regenerate a layout using `omixerSpecific`.

I have also updated the Description file. Hopefully it is more descriptive now and the author is listed correctly.

Please do let me know what any next steps I should take. Thank you for all your help.

**Comment by nturaga** [comment]
Can you issue a version bump? I'd like to see the latest build report.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ljsinke.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Omixer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Omixer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
