### ISSUE TITLE
Rtpca

### ISSUE THREAD

**Issue by nkurzaw** [Bioconductor/Contributions#1508]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nkurzaw/Rtpca

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hello @nkurzaw,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: Depends are for packages that provide essential functionality 
for users of your package. It is unusual for more than three packages to be 
listed here. Please move some of these packages to imports.

- [ ] SUGGESTION: It is encouraged to include a 'BugReports:' field with the 
relevant link to GitHub for reporting Issues.

## Vignette

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how 
to install the package from Bioconductor, not GitHub.

- [ ] SUGGESTION: I would consider moving the subsections (2.1-2.3) under 
'Introduction' into their own section since they aren't introductions but the 
actual demonstration of the functionality of the package.

- [ ] SUGGESTION: I'm assuming the data 'hdacTR_smallExample' is coming from 
TPP? You might mention this.

- [ ] SUGGESTION: It isn't clear (at least not to me) in the vignette when you 
move from TPP functionality into the functionality of Rtpca. I see under 2.1 
where you mention importing using TPP, but then you don't mention if the other 
functions used are from there or Rtpca. Just a bit of clarification in the text 
might be helpful. 

- [ ] REQUIRED: What is the purpose of the .csl file? There should only be one
reference file included here.

## Man pages

- [ ] REQUIRED: The only files that should be in this directory are the .Rd man 
pages. I would suggest moving the 'figures' directory to an 'inst/figure/' 
directory

- [ ] REQUIRED: The class man page doesn't seem complete, the value information 
just ends at 3). 

## R code

- [ ] REQUIRED: Avoid the use of direct slot access with `@` or `slot()`. An 
accessor method should be created and utilized instead.

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 26 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line 
indents. There are 168 lines that are not

Best,
Kayla

**Comment by nkurzaw** [comment]
Hello @Kayla-Morrell, 
thanks a lot for reviewing our package and for getting back to us so fast.
I will try to address all the points you raised as soon as possible!

Concerning the .csl file in the vignette folder, it is a citation style that I prefer over the standard `rmarkdown` one, I have that included also for another *Bioconductor* package of mine (`TPP2D`) and it does not cause any troubles there. But if you think I should still remove it, I am happy to that.

Thanks again!
Best,
Nils

**Comment by Kayla-Morrell** [comment]
Hello @nkurzaw - Just checking in to see if the package is ready for re-review? If it is, please comment back addressing the points I raised. If not, just let me know when it's ready.
Best,
Kayla

**Comment by nkurzaw** [comment]
Hello @Kayla-Morrell,
I'm sorry, I'm not quite there yet. I'm still missing some accessory functions.
I'll try to finalise all required changes and comment back on the points tomorrow!

Best,
Nils

**Comment by nkurzaw** [comment]
Hi @Kayla-Morrell ,

I have now addressed all 'REQUIRED' change requests and most 'SUGGESTIONS'. 
Thanks a lot again for reviewing our package, you had great comments that definitely improved the package!
Please see below the detailed response to all comments:

# DESCRIPTION

- [x]  REQUIRED: Depends are for packages that provide essential functionality
for users of your package. It is unusual for more than three packages to be
listed here. Please move some of these packages to imports.

- I have now reduced the Depends to: "R (>= 4.0.0), stats, dplyr, tidyr". All of the three packages are required for core functionalities of the package.

- [x] SUGGESTION: It is encouraged to include a 'BugReports:' field with the
relevant link to GitHub for reporting Issues.

- the following 'BugReports' field has been added to the DESCRIPTION file: "BugReports: https://support.bioconductor.org/"

# Vignette

- [x] REQUIRED: The 'Installation' section should demonstrate to the user how
to install the package from Bioconductor, not GitHub.

- This has been changed accordingly. It now states:

"
Installation from *Bioconductor*
```{r, eval = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Rtpca")
```
"
- [x]  SUGGESTION: I would consider moving the subsections (2.1-2.3) under
'Introduction' into their own section since they aren't introductions but the
actual demonstration of the functionality of the package.

- The vignette has now been restructured: a new heading after "Installation" and "Introduction" called "The Rtpca package workflow" has beed added.

- [x] SUGGESTION: I'm assuming the data 'hdacTR_smallExample' is coming from
TPP? You might mention this.

- You're right, this is now explained more clearly

- [x]  SUGGESTION: It isn't clear (at least not to me) in the vignette when you
move from TPP functionality into the functionality of Rtpca. I see under 2.1
where you mention importing using TPP, but then you don't mention if the other
functions used are from there or Rtpca. Just a bit of clarification in the text
might be helpful.

- Thanks, this is really a good point. This is now made more obvious by adding a subsection  "Import Thermal proteome profiling data using the TPP package" and then another "Performing thermal co-aggregation analysis with Rtpca" 

- [x]  REQUIRED: What is the purpose of the .csl file? There should only be one
reference file included here.

- This has been discussed already above

# Man pages

- [x] REQUIRED: The only files that should be in this directory are the .Rd man
pages. I would suggest moving the 'figures' directory to an 'inst/figure/'
directory

- I changed this according to your suggestion

- [x]  REQUIRED: The class man page doesn't seem complete, the value information
just ends at 3).

- Good spot! This has now been completed

# R code

- [x]  REQUIRED: Avoid the use of direct slot access with @ or slot(). An
accessor method should be created and utilized instead.

- I have now added accessor methods and replaced all usages of @ or slot

- [x]  SUGGESTION: For formating reasons, consider shorter lines. There are 26
lines that are > 80 characters long.

- I have shortened all lines for which I was able to do so. The two remaining ones with > 80 characters are hyperlinks that cannot be broken.

- [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
indents. There are 168 lines that are not

- I have not completely addressed this point. I am using RStudio and it does not in all cases adhere to this style, if you feel strongly about this point, I'm happy to address it, but I don't think it adds much to the readability of the code.

Thank you very much for your time and effort sent again!

Best,
Nils

**Comment by Kayla-Morrell** [comment]
@nkurzaw - Thank you for making the necessary changes! Everything looks good now and I'd be more than happy to accept the package.

Best,
Kayla

**Comment by nkurzaw** [comment]
Awesome :) Thanks a lot @Kayla-Morrell!

Best,
Nils

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nkurzaw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rtpca")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rtpca

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
