### ISSUE TITLE
scCB2

### ISSUE THREAD

**Issue by zijianni** [Bioconductor/Contributions#1509]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zijianni/scCB2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Zijian, @zijianni 

Thank you for your submission. 
Please see the review below.
If you have any questions, post them here.

Best,
Marcel

---

# scCB2 #1509

## DESCRIPTION

* Looks good.
* (optional) Reformat the `Description: ` field so that it doesn't run out of
the screen
* Is there a reason for importing `BiocStyle`?
* BiocStyle should be used for the vignette and should remain in the
`Suggests:` field

## NAMESPACE

* It looks good.
* See note above regarding `BiocStyle`

## vignettes

* Remove code chunk that shows how to install via GitHub
* Try to keep your lines within the 80-width columns limit
* Pretty straightforward

## R

* Default values for `Ncores` arguments should be 1 or 2 and not more. These
values should be set by the user and should not be greedy (see `CB2FindCell`).
* Where possible, provide a unified representaiton as output rather than lists
or use a central class throughout the package (e.g., `SummarizedExperiment`,
`SingleCellExperiment`)
* It looks like `BiocStyle` does nothing in the `R/QuickCB2.R` file.
* Avoid using `dontrun` in the examples for `QuickCB2`. It shouldn't hurt
to run the operations more than once. If the dataset / examples are small
enough, it should not take very long.

**Comment by zijianni** [comment]
Hi Marcel, @LiNk-NY 

Thank you so much for reviewing our package! I will provide a point-by-point response soon with modified codes. 

For the `BiocStyle`, you are right that it was only used for building vignettes. However I encountered some problem when building my packages saying something like "Couldn't find package `BiocStyle` when building vignettes", and I had to fix that by moving `BiocStyle` from `Suggests:` to `Imports:`. Anyway, I will play a little bit more with it and update the code.

Best,
Zijian

**Comment by zijianni** [comment]
Hi Marcel,

Thanks again for reviewing our package! Please see below for our response and check our updated codes again.

Best,
Zijian


> # scCB2 #1509
> ## DESCRIPTION
> * Looks good.
> * (optional) Reformat the `Description: ` field so that it doesn't run out of
>   the screen
Fixed a little bit… maybe looks better now.
> * Is there a reason for importing `BiocStyle`?
Moved `BiocStyle` from `imports` to `suggests`.
> * BiocStyle should be used for the vignette and should remain in the
>   `Suggests:` field
See above.
> 
> ## NAMESPACE
> * It looks good.
> * See note above regarding `BiocStyle`
> 
> ## vignettes
> * Remove code chunk that shows how to install via GitHub
Done.
> * Try to keep your lines within the 80-width columns limit
Done, except for some url link. Please double check and let me know if not.
> * Pretty straightforward
> 
> ## R
> * Default values for `Ncores` arguments should be 1 or 2 and not more. These
>   values should be set by the user and should not be greedy (see `CB2FindCell`).
Changed default values of `Ncores` to be 2.
> * Where possible, provide a unified representaiton as output rather than lists
>   or use a central class throughout the package (e.g., `SummarizedExperiment`,
>   `SingleCellExperiment`)
Changed output of `CB2FindCell` to be an object of class `SummarizedExperiment`.
> * It looks like `BiocStyle` does nothing in the `R/QuickCB2.R` file.
Removed `BiocStyle` from `R/QuickCB2.R`.
> * Avoid using `dontrun` in the examples for `QuickCB2`. It shouldn't hurt
>   to run the operations more than once. If the dataset / examples are small
>   enough, it should not take very long.
Added runnable example in `QuickCB2`.

**Comment by zijianni** [comment]
By the way, I'm wondering if it's OK to change R dependence from >= 4.0 to like >= 3.6 so that the package can be installed in older R versions? I did so but there were warnings when performing BiocCheck.

**Comment by LiNk-NY** [comment]
Hi ZiJian, @zijianni 
Thank you for making those changes. 

Can you remove the file download from the vignette? 
```r
download.file("http://cf.10xgenomics.com/samples/cell-exp/2.1.0/neurons_900/neurons_900_raw_gene_bc_matrices.tar.gz",
    destfile = file.path(data.dir,"neurons_900_raw_gene_bc_matrices.tar.gz"))
```

Your vignette should include a small subset of the 10x file for demonstration
purposes. We don't want a large file to be downloaded every time
the vignette is run. You can save the small subset of data in the 
`inst/extdata` folder. Remember, the vignette is meant to demonstrate
the functionality of your software and not really provide a real-world example
with large data. You could do that, if you are so inclined, in a workflow 
package. 

> By the way, I'm wondering if it's OK to change R dependence from >= 4.0 to like >= 3.6 so that the package can be installed in older R versions? I did so but there were warnings when performing BiocCheck.

The package will go into Bioconductor development branch. Users of Bioc devel will
be required to use R version 4.0 and your package was developed in that version so you
can make some guarantees that it will work with R 4.0. 

If you'd like, you can remove the R version dependency line in the `DESCRIPTION` file
and allow users who haven't updated their R version to obtain the package through 
GitHub.  Although you can't guarantee that it will work with their installations...

Best,
Marcel

**Comment by zijianni** [comment]
Hi Marcel, @LiNk-NY 

Thanks for your suggestions! I will remove the direct download from vignettes. Instead I'm planning to simulate some small raw data using the built-in `data/mbrainSub.rda` rather than adding raw data to `inst/extdata`. You know how large a single-cell data could be...  Does that sound good to you?

> If you'd like, you can remove the R version dependency line in the `DESCRIPTION` file
> and allow users who haven't updated their R version to obtain the package through
> GitHub. Although you can't guarantee that it will work with their installations...

Do you mean keep the  R dependence >= 4.0 for Bioconductor version and delete it for my personal GitHub version once the package got accepted and added to Bioconductor? Or maybe installation through `BiocManager` must be based on R-4.0 whatever R dependence is specified, but through Bioconductor GitHub repo can be on older R version?

And if I'm really gonna do that, should I just remove the `(>=4.0)` or the whole `Depends: R (>= 4.0)` ?

Best,
Zijian

**Comment by LiNk-NY** [comment]
Hi ZiJian, @zijianni 

That's perfect! Simulating data is even better.

> Do you mean keep the R dependence >= 4.0 for Bioconductor version and delete it for my personal GitHub version once the package got accepted and added to Bioconductor? Or maybe installation through BiocManager must be based on R-4.0 whatever R dependence is specified, but through Bioconductor GitHub repo can be on older R version?

I mean you can remove the `Depends:` field from the `DESCRIPTION` file (see below).
```
Depends: 
    R (>= 4.0)
```
Bioconductor has strict checks in place that will ensure that the user has R version 4.0 or greater
when using Bioconductor devel (after your package is accepted). On the other hand, users who install
your package from GitHub will be able to do so even with an old Bioconductor version but at their
own risk because you developed your package using Bioc-devel.

Best,
Marcel

**Comment by zijianni** [comment]
Hi Marcel, @LiNk-NY 

I've now updated vignettes by replacing direct download of raw data with simulating data. I also updated vignette title to match the citation. 

I tried to remove the whole part of
```
Depends: 
    R (>= 4.0)
```
but another warning poped out

```
checking data for ASCII and uncompressed saves ... 
WARNING Warning: package needs dependence on R (>= 2.10)
```

So I changed the dependency to 3.6, and BiocCheck gives warning (as expected). Should I try to fix it or just leave as is? Thanks!

Best,
Zijian

**Comment by LiNk-NY** [comment]
Hi ZiJian, @zijianni 

I forgot that you have compressed data in the package. Let's go with the second option.
That is to add R version >= 4.0.0 (that's what it will be once it's in Bioconductor anyway) and
create a GitHub branch that has a lower version for users who are lagging behind in R versions. 
I would encourage those users to update their R version to 4.0 for them to use your package.
That ensures that your package is working nicely with the other packages in the
R/Bioconductor ecosystem. 

Best,
Marcel

**Comment by zijianni** [comment]
Sounds good... fixed it now. Please check again, thanks! @LiNk-NY

**Comment by zijianni** [comment]
Hello @LiNk-NY , any updates on the review process?

**Comment by LiNk-NY** [comment]
Hi Zijianni, @zijianni 
Apologies for the delay. I will review your changes in the next couple of days. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi ZiJian, @zijianni 

I had a look at the changes and they look great! 
Your package is ready for acceptance. 
Thank you for your contribution to Bioconductor.

Best regards,
Marcel

**Comment by zijianni** [comment]
Thanks a lot! @LiNk-NY

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zijianni.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scCB2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scCB2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
