### ISSUE TITLE
periodicDNA

### ISSUE THREAD

**Issue by js2264** [Bioconductor/Contributions#1511]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/js2264/periodicDNA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by js2264** [comment]
Hi @hpages,
Thanks for reviewing this package! This is my first Bioconductor submission so hopefully I am not doing everything wrong. 
I solved the `ERRORS` I had when the package was built/checked by the Bioconductor package builder. From the latest report, I still have one `WARNING`: 

```
"WARNING: Update R version dependency from 3.5 to 4.0."
```

I understand that ideally, new packages are written for the most recent version of R/Bioconductor. However, I have developed this package from a server using R 3.5, and it would be rather cumbersome to have to install a new version of R for this (I cannot devtools::check() the package if R dependency is >= 4.0.0). Moreover, I feel like a lot of users may not have updated their R version to 4.0.0, a major change.  
In such context, is changing this dependency a required step for Bioconductor submission? 

Thanks!

**Comment by js2264** [comment]
Regarding the notes I got from the report: 

1. `Recommended function length <= 50 lines`: I have quite a lot of plotting functions that are long and cannot really be shortened... I did try to maximize the use of functions whenever possible and to avoid repeats. 
2. `Consider shorter lines; 2 lines (0%) are > 80 characters`: these are 2 https links in a .Rmd vignette, that are longer that 80 chars, but are not meant to be displayed anyway, as they are https links. 
3. `Consider multiples of 4 spaces for line indents, 132 lines(3%) are not`: not sure how to fix this... I generate my documentation using `devtools::document()` (`devtools` version 2.0.1, `R 3.5.2` in `Ubuntu 18.04.2`), and somehow it uses 2-space tabs. Let me know if my full `sessionInfo()` could help here.

Would these 3 notes need to be addressed? 

Thanks!

**Comment by js2264** [comment]
Hi @hpages, 

Just to check, did you have a chance to read my previous message? The current warning is due to the version of R I specified in my dependencies. Let me know if you think it is ok or if I absolutely have to put R 4.0. 
Is the review process on going? I have a few minor commits to bump to Bioconductor build, but it is largely unchanged from 0.99.8.

Many thanks, 
J

> Hi @hpages,
> Thanks for reviewing this package! This is my first Bioconductor submission so hopefully I am not doing everything wrong.
> I solved the `ERRORS` I had when the package was built/checked by the Bioconductor package builder. From the latest report, I still have one `WARNING`:
> 
> ```
> "WARNING: Update R version dependency from 3.5 to 4.0."
> ```
> 
> I understand that ideally, new packages are written for the most recent version of R/Bioconductor. However, I have developed this package from a server using R 3.5, and it would be rather cumbersome to have to install a new version of R for this (I cannot devtools::check() the package if R dependency is >= 4.0.0). Moreover, I feel like a lot of users may not have updated their R version to 4.0.0, a major change.
> In such context, is changing this dependency a required step for Bioconductor submission?
> 
> Thanks!

**Comment by js2264** [comment]
HI @hpages,
Sorry if I seem to be insisting too much, I am not completely sure of how the whole process of submission works. 
Should I bump the version (and the associated changes I have been working on recently) for the package to be reviewed? The commits waiting for a version bump are minor, but I could bump them now, in case you are waiting for them to review the whole package. 
Many thanks, 
Jacques

**Comment by lshep** [comment]
Please bump the version so we have  a complete version.  We normally give reviewers approximately 2 weeks to get back reviews.   @hpages will review your package shortly.

**Comment by js2264** [comment]
I have now pushed the last commits and fixed the errors and warnings. The remaining warning is still about the R version specified in my dependencies
> The current warning is due to the version of R I specified in my dependencies. Let me know if you think it is ok or if I absolutely have to put R 4.0.

Thx

**Comment by js2264** [comment]
Dear @lshep and @hpages,
Sorry to be annoying with this, as I am sure everybody is working on tight schedules. I'd like to submit a manuscript presenting periodicDNA for publication as soon as possible. Is it possible to get an idea of the timeline for the coming review of my package? 
Thank you very much,
Jacques

**Comment by js2264** [comment]
Dear @lshep and @hpages, 
Sorry again to bother you, but tomorrow will be 5 full weeks since I have submitted my package for review, and I have had no feedback until today. I would really like to submit a manuscript as soon as possible, but I would need the package to be available to publish it. 
The package submission information on Bioconductor states: 

> The entire review process typically takes between 2 and 5 weeks.

Could I please be informed whether there are any extraordinary circumstances that are delaying the review process? 

Many thanks and sorry again for being so inquisitorial/pushy. 
Best,
Jacques

**Comment by hpages** [comment]
Hi @js2264,

Thanks for your patience. You don't need (and should not) have a man page for every internal helper that you define (e.g. `na.remove`). That will just clutter the reference manual with dozens of functions that the end user doesn't care about and doesn't have access to and so will be quite confusing. Please remove them. To give an idea, the package exports 18 symbols so typically would not have more than 18 man pages (a few extra man pages for concepts and for the package level man page are ok).

Thanks!

**Comment by hpages** [comment]
Also no need to reinvent the wheel with `char2BSgenome()` when `BSgenome::getBSgenome()` does exactly that (and more). Thanks!

**Comment by hpages** [comment]
With respect to the current warning. Please keep in mind that the package is currently being tested with R 4.0 and that this is what you should also be using to develop and test it. The reason for this is that you're submitting a package for inclusion in BioC devel and BioC devel is targeting R 4.0 and R 4.0 only. So whether you update the R version dependency from 3.5 to 4.0 or not, once your package makes it in Bioconductor it will only be available to users that are running R >= 4.0.

Best

**Comment by js2264** [comment]
Hi @hpages, 
Thanks for your feedbacks, it is very useful. 

[x] I removed the documentation for all internal functions.

[x] I didn't know about `BSgenome::getBSgenome()`. I removed `char2BSgenome()` and replaced it entirely by `BSgenome::getBSgenome()`. Thanks for the info!

[x] Based on your comment, I thought moving it the package requirement to R >= 4.0 would be the easiest. 

**Note:** The last remaining warning is about the check which takes more than 10 min (only for the Linux build, apparently). I am note sure why it's only for 1 build but not the other. Should I deal with this?

Let me know if there is anything else you would want me to change!
Best

**Comment by js2264** [comment]
I have now managed to make the examples/tests run faster, so the check time is under 10 minutes total. 
Let me know what the next steps should be. 
Thanks!

**Comment by js2264** [comment]
Hi @hpages,
Any info on when the review will be done?
Best, J

**Comment by js2264** [comment]
Dear @hpages,
Sorry to bother you again. Any info on when the full review would be available? Or are your last comments the only ones you had?
Best, J

**Comment by js2264** [comment]
Dear @hpages,
Sorry to insist, but is there anything else to do for the review? I would like to submit a manuscript presenting the package and I need it to be available. It has been more than 10 weeks since the beginning of the submission process. Perhaps the review should be transferred to someone with more time available?
Best, J

**Comment by hpages** [comment]
Hi @js2264 ,
Thanks for the changes to periodicDNA. I'm taking a deeper look at the package now and will get back to you in the next 24h or so. Thanks for your patience.
H.

**Comment by hpages** [comment]
Hi @js2264 ,

An important effort is needed to improve the documentation. See below.

Best,
H.

1. Are utility functions like `checkPeriodFromFourier` or `withSeq` useful/meaningful to the end user? I can't figure out what users of the periodicDNA package would need these functions for. Furthermore, in the case of `checkPeriodFromFourier` I don't really understand what the function does and have no idea how I would use it in the context of a periodicDNA analysis. If a function is an internal utility (i.e. not intended to be used by the end user), please do not export or document it (see my earlier comment about that). Otherwise please improve its man page, including the examples provided in its man page.

2. Assuming `sampleGRanges` is a function intended for the end user (see above point if it's not), then its man page needs improvements. The current description of what the function does exactly is mimimalist and seems inaccurate. In particular it says that the returned GRanges has "the same chromosome, width and strand distributions than the original" but that doesn't seem to be the case:
    ```
    gr <- GRanges(LETTERS[1:5], IRanges(1:5, width=10), strand=c("+", "+", "-", "-", "*"))
    set.seed(333)
    sampleGRanges(gr)
    # GRanges object with 5 ranges and 0 metadata columns:
    #       seqnames    ranges strand
    #          <Rle> <IRanges>  <Rle>
    #   [1]        B      1-10      +
    #   [2]        C      7-10      -
    #   [3]        D       6-8      -
    #   [4]        D        11      -
    #   [5]        E       4-9      *
    #   -------
    #   seqinfo: 5 sequences from an unspecified genome
    ```
    Also why set these artificial seqlengths on the returned GRanges?
    ```
    seqlengths(gr2)
    #  A  B  C  D  E 
    # 10 11 12 13 14 
    ```
    That would not make much sense in general and would likely cause problems downstream (e.g. a `findOverlaps()` operation would fail because of incompatible seqlengths between query and subject).

3. The vignette starts with "Dinucleotide periodicity over a set of Genomic Ranges". Unfortunately this somehow suggests that periodicDNA only handles dinucleotides which I believe is not the case. How about giving a general introduction to the periodicDNA packages first, and then delve into the particular case of dinucleotide periodicity?

4. Why explaining how periodicDNA works in a separate vignette? This information is very relevant to anybody seriously interested in using the package so a much better place for it is in the main vignette. This is also an opportunity to introduce terms like _distogram_, to define them precisely, and to use them later thru the rest of the documentation.

5. I could be misunderstanding how periodicDNA works but it seems to me that the message displayed by `getPeriodicity()` -- "Applying Fast Fourier Transform to the vector of distances" -- is incorrect. My understanding is that it applies the FFT to the normalised distogram, which is not the same as the vector of distances.

6. It's very hard to find the documentation for the extra arguments accepted by `getPeriodicity()`. The man page for the function (typically accessed with `?getPeriodicity`) doesn't say anything about these arguments but uses them (e.g. `range_spectrum`) in its examples. After a while I realized that these arguments are documented in separate man pages (in `?getPeriodicity.DNAStringSet` and in `?getPeriodicity.GRanges`). However most users will struggle to find these man pages, at best, or won't be able to find them. This problem is usually avoided by documenting the S3 generic and all its method in the same man page. Another benefit of doing this is that it avoids repeating the same information across all the man pages (e.g. the long Value section) which will make long term maintenance significantly easier.

7. The other S3 generics (`getFPI`, `plotAggregateCoverage`, etc..) have the same documentation problem.

8. Why isn't `motif` an argument of the `getPeriodicity()` generic itself since all the methods actually need a motif in order to work? It is generally considered better design to put arguments that are common to all methods in the generic.

9. The `motif` argument in `?getPeriodicity.DNAStringSet` is described as "a dinucleotide of interest" and the 6th item in the list returned by the function is described as "The motif object is the dinucleotide being analysed". Unfortunately this again suggests that the function can only handle dinucleotides.

10. `getPeriodicity` returns a list of 7 components but the man page for `getPeriodicity` only documents 6.

11. Generally speaking functions are expected to catch edge cases (or misuse on the part of the user) in a graceful manner, and to display useful error messages. For example it's not immediately clear what's going on here:
    ```
    motif <- "AAA"
    seqs <- rep(DNAStringSet("AATCTAATCTAATCTAATCTAATCTAATCTAA"), 20)
    periodicity_result <- getPeriodicity(seqs, motif)
    # - Mapping k-mers.
    # range_spectrum (1:200) is wider than the maximum distance between pairs of k-mers (-Inf). Try shortening range_spectrum to a smaller range.
    # Error in getPeriodicity.DNAStringSet(seqs, motif) : 
    # In addition: Warning messages:
    # 1: In max(dists) : no non-missing arguments to max; returning -Inf
    # 2: In max(dists) : no non-missing arguments to max; returning -Inf
    # 3: In max(dists) : no non-missing arguments to max; returning -Inf
    ```
    So please implement some basic checking of the user input and make sure to print informative error messages.

12. Keep the code chunks in the vignette as simple and easy to understand as possible, possibly sticking to traditional R syntax. For example, this is mostly a matter of taste but I don't find something like
    ```
    periodicity_result$periodicityMetrics %>% '['(.$Period == 10, )
    ```
    to be particularly easy to read/understand. The more traditional R syntax is IMO much clearer:
    ```
    subset(periodicity_result$periodicityMetrics, Period == 10)
    ```

**Comment by js2264** [comment]
Hi @hpages,
Thanks for your review. I will start working on it asap. 
Best, J

**Comment by js2264** [comment]
Hi @hpages, 

I have tried to address all your comments. Briefly:

1. I have deleted some functions and removed others from the NAMESPACE, per your instructions. 
2. I removed sampleGRanges function entirely.
3. I completed the vignette and replaced "dinucleotide" by "k-mer" when necessary.
4. I have fused the 2 vignettes together. 
5. I have corrected the statement.
6. I have simplified the documentation per your suggestions. 
7. I have simplified the documentation per your suggestions. 
8. I have moved `motif` to the generic function directly. Thanks for the tip!
9. Replaced "dinucleotide" by "k-mer" when necessary.
10. I have completed and clarified `getPeriodicity()` manual.
11. I have added clear errors messages wherever I could think of a edge case / potential misuse.
12. Hopefully the vignette is now clear enough. 

Let me know if there are further changes you'd want me to work on,
Thanks!

**Comment by hpages** [comment]
Hi @js2264 ,

All the changes look good. Package is ready to go. Thanks for your contribution to the project.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("periodicDNA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/periodicDNA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
