### ISSUE TITLE
transomics2cytoscape

### ISSUE THREAD

**Issue by kozo2** [Bioconductor/Contributions#1513]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ecell/transomics2cytoscape

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kozo2** [comment]
@mtmorgan Hi Martin. This package needs to install Cytoscape in the build environment. Is it possible for me to do that?

**Comment by mtmorgan** [comment]
Hi @kozo2 

In principle, we could manually install Cytoscape if it were added to the SystemRequirements: field of the DESCRIPTION file, and if there were a file INSTALL that provided detailed instructions on how to install it on each of our platforms (Linux, Mac, Windows). The 'Headless' version is appropriate for the builders.

But how do other packages like RCy3 that seem like they would have Cytoscape dependencies manage? Also, just reaching out to @paul-shannon in case he remembers past experiences...

**Comment by paul-shannon** [comment]
@kozo2 and @mtmorgan,

Dan Tenebaum managed what I think he called "a cytoscape farm" for several years to support RCytoscape then RCy3 testing.  I vaguely recall that as the overall bioc build system evolved, the burden of the farm rose, and we all agreed to give it up.  @dtenenba will remember the details.

**Comment by kozo2** [comment]
Thanks @mtmorgan 
I added the [SystemRequirements: field](https://github.com/ecell/transomics2cytoscape/blob/master/DESCRIPTION#L19)
And I added [a file INSTALL that provided detailed instructions on how to install it on each of our platforms (Linux, Mac, Windows)](https://github.com/ecell/transomics2cytoscape/blob/master/INSTALL).

@mtmorgan @paul-shannon 
As far as I know, the `Headless` version is no longer in development.
We need at least two terminals to use Cytoscape as a REST server. (RCy3 is a client package for the REST server.)
One is for the Cytoscape process and the other for the R process.
One terminal has to run Cytoscape process and keep the process. (This cannot be done in the background.)

**Comment by mtmorgan** [comment]
I'm concerned that this will be a very fragile situation. It sounds similar to what Dan had, and it required regular maintenance as well as familiarity with the details of Cytoscape across platforms; it also ran into connectivity and other problems associated with long-running processes on multi-tenant systems.

In the end and for this particular case I think it is better to provide a vignette with code chunks that are built on your system but not the build system
```{r}
knitr::opts_chunk$set(eval = identical(Sys.getenv("KOZOS_SYSTEM"), "TRUE"))
```
I think it would be very valuable to explore the use of `testthat::with_mock()` to write unit tests that do not rely on the server, but allow assessment of the correctness of your code.

**Comment by paul-shannon** [comment]
Fragile - I agree.

One other possibility (maybe practical, maybe not) is for the Cytoscape Consortium to run a Cytoscape instance with the CyREST interface at a known host:port - just for bioc build testing.  RCy3 is the client, talking to this remote, always available server, which I imagine would be running headless but otherwise fully functional, and completely separate from Bioconductor.

 n- Paul

**Comment by kozo2** [comment]
@mtmorgan
I provided a code chunk not to be built on the Bioconductor system.
https://github.com/ecell/transomics2cytoscape/blob/master/vignettes/transomics2cytoscape.Rmd#L14-L18

I didn't see why `testthat::with_mock()` could be used for writing unit tests that do not rely on the CyREST server.
Anyway I added some unit tests to https://github.com/ecell/transomics2cytoscape/tree/master/tests/testthat
(But these unit tests rely on the CyREST server.)

**Comment by kozo2** [comment]
@paul-shannon I'll send your message to Cytoscape team (when I get a chance). But It might be difficult to realize. (One of the reasons is that CyREST does not support remote file IO.)

**Comment by kozo2** [comment]
@mtmorgan

These errors cannot be resolved because Cytoscape is required to run the man Rd files in this package.
What should I do?

```
* Checking man page documentation...
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      create3Dcyjs.Rd
    * NOTE: Usage of dontrun{} / donttest{} found in man page examples.
      100% of man pages use one of these cases.
      Found in the following files:
        create3Dcyjs.Rd
```

**Comment by mtmorgan** [comment]
ignore the error; I'll review the package

**Comment by kozo2** [comment]
@mtmorgan 
I'm sorry. I have changed the specifications of the package since you replied me.
Would it be possible for you to review the package again?

**Comment by mtmorgan** [comment]
If the package is stable and you perform a version bump, I will review it.

**Comment by kozo2** [comment]
@mtmorgan I stopped updating. Now the package is stable (and I performed a version bump).
I would like to ask you to review it.

**Comment by mtmorgan** [comment]
3 August, 2020

Please address these very brief notes and include a comment indicating your response.

DESCRIPTION, NAMESPACE

- good

vignettes

- please update installation instructions to indicate `BiocManager::install("transomics2cytoscape")`.

- please do not write to the current working director `"."` at line 123; use `tempdir()` or `dir.create(tempfile())` instead (also in the man page).

R

- transomics2cytoscape.R: 77 `message(paste(...))` is usually not necessary, since `message()` calls `paste0()` internally. Just `message("... ", "...")`

tests

- the unit tests are commented out; it is better to remove 'dead' code.

**Comment by kozo2** [comment]
@mtmorgan Thank you for your review.

I updated the code as much as I can.
https://github.com/ecell/transomics2cytoscape/compare/comment-3Aug?expand=1
If it's OK with this update, I would like to merge `comment-3Aug` to `master`.

> please update installation instructions to indicate `BiocManager::install("transomics2cytoscape")`.

I replaced `devtools::install_github` to `BiocManager::install`

> please do not write to the current working director "." at line 123; use tempdir() or dir.create(tempfile()) instead (also in the man page).

I couldn't find a way to reflect this advise.

I think the `sif` path created by `tempdir` is not fixed.
On the other hand, in the `networkLayers.tsv` (an argument of `create3Dnetwork` function), it is necessary to write the path of the `sif`.
(In the example data case, it is `galFiltered.sif` in the current directory).

```
layer1	rno04910	600
layer2	galFiltered.sif	400
layer3	rno00010	200
layer4	rno00010	1
```

I think we have no way to know the path created by tempdir before writing this tsv.
If we can use the current directory, we don't need to write the full path.

What are your thoughts on that?

> transomics2cytoscape.R: 77 `message(paste(...))` is usually not necessary, since `message()` calls `paste0()` internally. Just `message("... ", "...")`

I removed all `paste()` in `message()`.

> the unit tests are commented out; it is better to remove 'dead' code.

I moved the test code from `tests` to `inst/unitTests` (and removed the comment marks in them).
I imitated the way of RCy3 https://github.com/cytoscape/RCy3/blob/master/inst/unitTests/test_RCy3.R

**Comment by mtmorgan** [comment]
`tempfile()` exists for the duration of the R session, and would be an appropriate value for a vignette or example; of course the user could write `"."` or any other path? Something like
```
diff --git a/R/transomics2cytoscape.R b/R/transomics2cytoscape.R
index 22e1eea..ceb719a 100644
--- a/R/transomics2cytoscape.R
+++ b/R/transomics2cytoscape.R
@@ -12,23 +12,28 @@
 ##' representing transomic interaction edges between the network layers.
 ##' @param stylexml A XML file path for Cytoscape style file to be applied to
 ##' the 3D network.
+##' @param workdir Path to the directory used to create output.
 ##' @return A SUID of the 3D network. 
 ##' @author Kozo Nishida
 ##' @import dplyr
 ##' @export
 ##' @examples \donttest{
+##' workdir <- tempfile(); dir.create(workdir)
 ##' sif <- system.file("extdata","galFiltered.sif",package="RCy3")
-##' file.copy(sif, ".")
+##' file.copy(sif, workdir)
 ##' networkLayers <- system.file("extdata", "networkLayers.tsv",
 ##'     package = "transomics2cytoscape")
 ##' transomicEdges <- system.file("extdata", "transomicEdges.tsv",
 ##'     package = "transomics2cytoscape")
 ##' stylexml <- system.file("extdata", "transomics.xml",
 ##'     package = "transomics2cytoscape")
-##' create3Dnetwork(networkLayers, transomicEdges, stylexml)
+##' create3Dnetwork(networkLayers, transomicEdges, stylexml, workdir)
 ##' }
 
-create3Dnetwork <- function(networkLayers, transomicEdges, stylexml) {
+create3Dnetwork <- function(networkLayers, transomicEdges, stylexml, workdir) {
+    owd <- setwd(workdir)
+    on.exit(setwd(owd))
+
     tryCatch({
         RCy3::cytoscapePing()
     }, error = function(e) {
```

**Comment by kozo2** [comment]
@mtmorgan Thank you for your advice.

I replaced `"."` to `tempdir()` with your idea.

https://github.com/ecell/transomics2cytoscape/compare/comment-3Aug?expand=1
If it's OK with this update, I would like to merge `comment-3Aug` to `master`.

**Comment by mtmorgan** [comment]
sounds good!

**Comment by kozo2** [comment]
Sorry, I forgot to update README.
Please forgive me for updating twice.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kozo2.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("transomics2cytoscape")`. The package 'landing page' will be created at

https://bioconductor.org/packages/transomics2cytoscape

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by kozo2** [comment]
@mtmorgan Thank you for your reviews.
I confirmed that the contents of https://bioconductor.org/packages/transomics2cytoscape worked without problems.
I will read the following how-tos and continue the development.

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

If I have any questions, I will contact the mailing list.
Thanks again.
