### ISSUE TITLE
SplicingFactory

### ISSUE THREAD

**Issue by peterszikora** [Bioconductor/Contributions#1517]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SU-CompBio/SplicingFactory

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

**Comment by mtmorgan** [comment]
Please update your package to use SummarizedExperiment rather than ExpressionSet.

**Comment by LiNk-NY** [comment]
Hi @peterszikora ,
Any updates on using `SummarizedExperiment`? 
Thanks.

**Comment by peterszikora** [comment]
Hi, thank you for the comment, working on it.

**Comment by esebesty** [comment]
Hi @mtmorgan and @LiNk-NY 

We were discussing the right way to use `SummarizedExperiment` and were curious about your opinion. Right now, the package deals with data where we have a **single table** with samples as columns and transcripts as rows. However, `SummarizedExperiment` might contain more than one assay with a matrix-like representation of read counts, etc. We don't want to simply pick the first assay for further analysis, so we were wondering what to do.

- Just pick the first assay, or an assay with a specific name.
- Implement some parameter for the `calculate_diversity` function, to specify the assay to be analyzed.
- Loop over the entire `SummarizedExperiment` object, process all tables, and return a list of data frames. This would mean additional complications in downstream analysis too.

Initially we decided to use `ExpressionSet` as similar tools, doing differential expression, like `limma` also use `ExpressionSet`. `voom` and `lmFit` of `limma` both expect a matrix-like data object.

**Comment by LiNk-NY** [comment]
Hi Endre, @esebesty 

I think the best option would be to include an argument ('parameter') in the `calculate_diversity` 
function with default of `1` for the first assay in the `SummarizedExperiment`. The user will also
have the option to change the argument to their liking. 

Using these tools (`limma` etc.) should be separate from the functionality and data representation
you provide. Ideally, these tools would accept a `SummarizedExperiment` as input. The
responsibility then falls on the analyst to provide the correct input for these tools. They would have
to use `assay(SE)` to get the matrix data.

I hope this answers your questions. 
Best,
Marcel

**Comment by peterszikora** [comment]
@mtmorgan and @LiNk-NY

Thank you again for your comments, we updated the package with SummarizedExperiment, waiting for your detailed review.

**Comment by LiNk-NY** [comment]
Hi @peterszikora 

Thank you for your submission. 
Please see the review below. 
If you have any questions, continue the thread here. 

Best,
Marcel

---

# SplicingFactory #1517

## DESCRIPTION

* Looks good

## NAMESPACE

* Looks straightforward

## vignettes/

* Looks good

## R

* Use `is.matrix` and `is(x, "SummarizedExperiment")` type of methods
for obtaining the class of the input object.
* Use a `verbose` argument for all the `message`s in `calculate_diversity`
and other functions
* User-facing functions should allow a `SummarizedExperiment` input
(`calculate_method`, `calculate_diversity`, etc.) and ideally return a
`SummarizedExperiment`
* Allow for alternative correction methods in `wilcoxon`. Is `BH` the only
correction method? It seems to be hard-coded.
* Should `calculate_*entropy` and related functions be exported and work on
a `SummarizedExperiment` object?
* Both`calculcate_entropy` and `calculate_laplace_entropy` look about the same,
perhaps make them into one function with a type argument so that you're
re-using code?

## data

* Rename the dataset `example_dataset` into something more descriptive
* If possible, re-use data from an existing TCGA data resource (or even
`GenomicDataCommons`)

**Comment by esebesty** [comment]
@LiNk-NY Hi Marcel, thanks for the suggestions, working on them.

**Comment by LiNk-NY** [comment]
Hi @peterszikora ,
Thanks for making those changes. Can you respond to the review line by line? 
Best,
Marcel

**Comment by esebesty** [comment]
Hi @LiNk-NY we are not done yet, as soon as all changes suggested in the review are implemented and/or discussed, we will respond line-by-line.

**Comment by esebesty** [comment]
> ## R
> 
>     * Use `is.matrix` and `is(x, "SummarizedExperiment")` type of methods
>       for obtaining the class of the input object.

Done.

> 
>     * Use a `verbose` argument for all the `message`s in `calculate_diversity`
>       and other functions

Done.

> 
>     * User-facing functions should allow a `SummarizedExperiment` input
>       (`calculate_method`, `calculate_diversity`, etc.) and ideally return a
>       `SummarizedExperiment`

`calculate_diversity` allows a `SummarizedExperiment` input. At the moment we would prefer to leave its output and the input format of other functions as they are. We are discussing what and how to change exactly, and [keeping the issue open](https://github.com/SU-CompBio/SplicingFactory/issues/5). However, if you prefer, we can adapt the code before Bioconductor submission.

> 
>     * Allow for alternative correction methods in `wilcoxon`. Is `BH` the only
>       correction method? It seems to be hard-coded.

Done, all methods that are available in `p.adjust` are available now.

> 
>     * Should `calculate_*entropy` and related functions be exported and work on
>       a `SummarizedExperiment` object?

Exported now. They work on a vector, that contains expression values of a single gene, so we would prefer not to adapt it to a  more complex `SummarizedExperiment` object.

> 
>     * Both`calculcate_entropy` and `calculate_laplace_entropy` look about the same,
>       perhaps make them into one function with a type argument so that you're
>       re-using code?

Done.

> 
> 
> ## data
> 
>     * Rename the dataset `example_dataset` into something more descriptive

Done.

> 
>     * If possible, re-use data from an existing TCGA data resource (or even
>       `GenomicDataCommons`)

We are using TCGA data from the legacy database, where RSEM based transcript level expression values are available. Let me know if you need a more detailed description of the data or a more recent dataset as example.

Additionally, we would like to change the maintainer to @esebesty The `DESCRIPTION` file is already updated to reflect this.

**Comment by LiNk-NY** [comment]
Hi Endre, @esebesty 

I've added a comment to the issue that you linked above.


>We are using TCGA data from the legacy database, where RSEM based transcript level expression values are available. Let me know if you need a more detailed description of the data or a more recent dataset as example.

Both `curatedTCGAData` (which I maintian) and `GenomicDataCommons` offer RSEM-based TCGA data although GDC has legacy data available. There are many resources for TCGA data and I think it would be better to use those instead of providing a potentially duplicate dataset. 

-MR

**Comment by esebesty** [comment]
Thanks for the hint, I didn't know about these packages! They are definitely more straightforward to use and we will replace the legacy data.

**Comment by LiNk-NY** [comment]
@esebesty I should also mention `RTCGAToolbox` and `TCGAbiolinks`. 
My guess is that these data are used in examples / vignettes so I would include the package that you end up using in the `Suggests` field only.

**Comment by LiNk-NY** [comment]
Hi Endre @esebesty 
Any updates on the status? 
Thanks.
Marcel

**Comment by esebesty** [comment]
We are a bit slow, sorry, but finishing soon! Thanks.

**Comment by LiNk-NY** [comment]
Please reopen when ready. Thank you.

**Comment by esebesty** [comment]
Please reopen the issue, we are (hopefully) done with all necessary changes.

**Comment by LiNk-NY** [comment]
Hi Endre, @esebesty 
Thank you for making those changes. I had a look at the package and it looks good. 
I'm accepting it. 
Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/peterszikora.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SplicingFactory")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SplicingFactory

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
