### ISSUE TITLE
epivizGviz

### ISSUE THREAD

**Issue by hcorrada** [Bioconductor/Contributions#152]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HCBravoLab/epivizGviz
Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
This has surely crossed your mind already, but why not use polymorphism for the different epiviz plot types? There is a way to convert a Gviz plot to an epiviz workspace. What about adding a Gviz plot to an existing workspace? Broader question: does Bioconductor need a "universal" track representation. Is that Gviz? It would be nice for the user to be able to construct a track using the same API, whether the track is rendered statically or interactively in epiviz. I realize each framework will have its own specific features, so there would need to be an extension mechanism, or an escape hatch to call down to the backend API.

**Comment by hpages** [comment]
Hi Hector,

I'm running into some serious usability issues with the package. See below. Thanks!

H.

(1) Many problems with the code in the first big chunk of code (i.e. the chunk that starts with a call to `startStandalone`):
 
1.a) It will fail for the user who tries to copy/paste the code in his/her session:
```
> app <- startStandalone(Homo.sapiens, keep_seqlevels=paste0("chr", c(10,11,20)), chr="chr11", try_ports=TRUE)
Error in startStandalone(Homo.sapiens, keep_seqlevels = paste0("chr",  : 
  object 'Homo.sapiens' not found
```

1.b) If after I get this error I try to run the next line of code anyway, I get a segfault on my laptop (64-bit Ubuntu):
```
> cgi_track <- app$plot(cgi_gr, datasource_name="CpG Islands")

 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: .Call("httpuv_sendWSMessage", PACKAGE = "httpuv", conn, binary,     message)
 2: sendWSMessage(.handle, FALSE, as.character(message))
 3: .self$.websocket$send(request)
 4: .self$.pop_request()
 5: .self$.server$send_request(request_data, .callback)
 6: .self$data_mgr$add_measurements(data_object, send_request = send_request,     ...)
 7: app$plot(cgi_gr, datasource_name = "CpG Islands")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```
I realize that, when I do this, I'm using the wrong `app` i.e. I'm using the one loaded earlier with `data(app, gviz_plot)` instead of the one that should have been returned by the call to `startStandalone()`. But still, `app$plot()` should handle the situation more gracefully.

1.c) If I restart R and try to run the code in this chunk again, but this time I do `library(Homo.sapiens)` before calling `startStandalone()`, then I see the following:
```
> app <- startStandalone(Homo.sapiens, keep_seqlevels=paste0("chr", c(10,11,20)), chr="chr11", try_ports=TRUE)
cloning epiviz JS app from repository...
cloning into '/home/hpages/R/R-3.3.r70604/library/epivizrStandalone/www'...
Receiving objects:   1% (56/5517),   16 kb
Receiving objects:  11% (607/5517),  649 kb
Receiving objects:  21% (1159/5517), 5364 kb
Receiving objects:  31% (1711/5517), 7141 kb
Receiving objects:  41% (2262/5517), 7958 kb
Receiving objects:  51% (2814/5517), 28170 kb
Receiving objects:  61% (3366/5517), 28450 kb
Receiving objects:  71% (3918/5517), 28714 kb
Receiving objects:  81% (4469/5517), 28858 kb
Receiving objects:  91% (5021/5517), 29042 kb
Receiving objects: 100% (5517/5517), 29663 kb, done.
done
Seqinfos added to application
creating gene annotation (it may take a bit)
'select()' returned 1:1 mapping between keys and columns
Measurement  hg19  added to application and connected
Chart  epivizChart_1  added to browser and connected to id  track-genes-BP4Iv 
```

Mmmh... that doesn't look good. The installation folder of a package should always be treated as a read-only place. I'm also very surprised to see that `startStandalone()` needs to clone a git repo. That doesn't seem like a good idea to me. Why would it need to do that? I can only see trouble in the long run by doing something like that. There must be a better way.

1.d) The code in the chunk is not evaluated (i.e. eval=FALSE).

(2) Running the next code chunk, which is also not evaluated:
```
app$print_workspace(file_name="workspace", file_type="pdf")
```
produced a PDF with "blank" tracks for me.

I didn't go further. I thought it was already a lot.

Also 2 minor cosmetic issues with the vignette so far:

(3) Problem with section numbering in the vignettte: sections are numbered from 0.1 to 0.8.

(4) The vignette refers to a epivizGvizConverter package in several places where it probably should refer to epivizGviz.

**Comment by hcorrada** [comment]
Thanks Mike and Herve. I think this package could use some redesign based on @lawremi comments. I'll close this issue now and resubmit after doing that and fixing vignette issues. 

@hpages the reason we don't evaluate chunk is that we're still figuring out a good way of embedding epiviz apps within rmarkdown documents. 

@hpages the github pull is done by the `epivizrStandalone` package actually, which pulls updated JavaScript repo for the UI (which we treat as an external dependency rather than as a part of the R package) if there are any updates to the JS code. The package allows users to set a different path for that code.
