### ISSUE TITLE
RIPAT

### ISSUE THREAD

**Issue by bioinfo16** [Bioconductor/Contributions#1523]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bioinfo16/RIPAT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before being reviewed, your package must have an R-markdown or Sweave-style vignette with evaluated code chunks. Please let me know with a comment here when you have updated your package to include a vignette.

**Comment by bioinfo16** [comment]
Hello @mtmorgan ,
I updated the vignette directory of RIPAT.
Please check it and let me know if there is any problem.

**Comment by mtmorgan** [comment]
The vignette must be written so that most chunks are actually evaluated when the package is built. The package must build and check within the time limits specified in the package guidelines.

**Comment by bioinfo16** [comment]
@mtmorgan,
I modified RIPAT vignette folder, bioccheck error and warnings.
Please check again.

**Comment by bioinfo16** [comment]
Hello @dvantwisk,
I modified my package. Please check again.

**Comment by mtmorgan** [comment]
remember to increment the version number to 0.99.1. This will trigger an automatic build.

**Comment by bioinfo16** [comment]
@mtmorgan,
I rewrited version.

**Comment by mtmorgan** [comment]
Have you [added a web hook][1] ? If not, please do so and increment the version again.

[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by bioinfo16** [comment]
@mtmorgan,
I added it before with version increment.

**Comment by mtmorgan** [comment]
It looks like when you did the version bump, you removed the DESCRIPTION file, then added it back in with a new version. Instead, what you should do is edit the DESCRIPTION file and then commit the changes. Can you try again taking that approach?

**Comment by bioinfo16** [comment]
@mtmorgan ,
I did it. Thanks :)

**Comment by bioinfo16** [comment]
Hello @mtmorgan,
By build report, my package have a problem with register bioc-devel mailing list.
I have been already register my email before opening this issue.
Could you check about it?

**Comment by bioinfo16** [comment]
@mtmorgan,
Same error is occured in the latest build report.
I don't know what happened.

**Comment by mtmorgan** [comment]
I do not see mjbaek16 at korea.ac.kr on the bioc-devel mailing list. Usually when you register it sends a confirmation email. Sometimes the email goes to your spam mail box. Try registering again

**Comment by bioinfo16** [comment]
@mtmorgan,
Thank you. I registered again.

**Comment by dvantwisk** [comment]
Hi,

I've reviewed your package. [REQUIRED] tags show issues that must be changes or addressed. [CONSIDER] tags show changes that are not required but are advisable. Please message me back when you are done making changes.

R/annoByCpG.R
- [ ] [CONSIDER] L36: Consider using `match.arg()` to declare the `mapTool`
argument. In the function delcartion for `annoByCpG()`, it can be written as
`mapTool = c("blast", "blat")`. `blast` will still be the default argument. The
user's choice can be selected with `mapTool <- match.arg(mapTool)` in the
function body. This method is preferred because it shows all possible values
`mapTool` can have in the function declaration. Also, `match.arg()` will throw an
error if a value outside the allowed values is given. `match.arg()` can be used
in many other places throughout this package.

- [ ] [CONSIDER] L41,44: The empty `else {}` condition is not needed. The
`if` statement can function by itself.

- [ ] [REQUIRED] L40,46: Use `error()` to display an error instead of using
`cat()`. Use `warning()` to show warning messages. Please make this change
throughout the package.

- [ ] [REQUIRED] L48,50,54: Use `message()` instead of `cat()` or `print()` to
display diagnostic messages to the user. This is preferred since these messages
can be silenced with `suppressMessages()`. Please make this change throughout the
package.

- [ ] [REQUIRED] The package seems to be continuously creating png files with
`grDevices`. It would be far better for the function to return the plot object
and allow the user to display the graphs as they see fit. Please allow the
functions to return either the plot or a list of plots for the user to
manipulate themselves. Please make this change throughout the other functions in
this package.

R/annoByRepeat.R
- [ ] [REQUIRED] L51: It looks like you are accessing a web resource here. Is
this resource maintained by your group? Will this resource be consistently
available? You might consider creating an Experimental Data package to store
this data, so that it will be guaranteed to be available for the user.

R/makeDocument.R
- [ ] [REQUIRED] Instead of make an excel file, this function should just create
a `data.frame` and then allow them the option of exporting the data to an excel
file themselves.

- [ ] [REQUIRED]L131: Instead of `1:...` use `seq_len()` or `seq_along()`. These
functions are slightly faster and prevent the unexpected case where `1:0` is
`1 0`. Please make this change through the package.

test
- [ ] [CONSIDER] I'm not certain what kind of testing environment you are using
inside your test directory. Normally, either the `testthat` or `Runit` testing
framework is used to create tests so that these tests are run in the `check`
stage of the build process. I would recommend using either testing framework for
your tests.

vignettes/RIPAT_Manual_v0.99.8.Rmd
- [ ] [REQUIRED] L47-61: The sitnallation for the apckage will be done through
the `BiocManager` package once your package is accepted. Please replace both the
`github_install()` and `R CMD INSTALL` code with:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("RIPAT")
```

**Comment by bioinfo16** [comment]
@dvantwisk 
I made a mistake (closing issue..). Thank you for your mention.
I will contact you after modification.

**Comment by bioinfo16** [comment]
@dvantwisk 
I want to ask you something about websource.
I made the github repository for providing resource of RIPAT.
Of course, It will be maintained stably.
Should I made new experimental data package for RIPAT in this case?

**Comment by mtmorgan** [comment]
Resources that your package needs cannot be hosted on GitHub. If it is a data resource, then it is appropriate to make an ExperimentHub package & resource.

**Comment by mtmorgan** [comment]
Can you provide me with an update on this package? Are you working to address the size and other issues?

**Comment by bioinfo16** [comment]
@mtmorgan 
Hello.
I am working to correct error message on the build report.
I need more time to modify my package. It will be maybe 2days.
Plus, package oversizing is occured by example data on RIPAT. I am also making new example data.

**Comment by bioinfo16** [comment]
@mtmorgan 
I am fixing it. When I finish it, I'll post comment on here.

**Comment by bioinfo16** [comment]
@mtmorgan 
I am so sorry for my delayed modification work.
That work is finished. Please review it again and let me know if I have to check somethings.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bioinfo16.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RIPAT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RIPAT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
