### ISSUE TITLE
POMA

### ISSUE THREAD

**Issue by pcastellanoescuder** [Bioconductor/Contributions#1524]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pcastellanoescuder/POMA

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by pcastellanoescuder** [comment]
@dvantwisk The build label for the package is OK but seems that Linux, Mac, and Windows platforms are still "skipped, UNSUPPORTED"...

Could you provide me some help on that?

Thanks!

**Comment by mtmorgan** [comment]
I believe (@lshep can confirm) that it's reacting to the presence of the Dockerfile at the base of the package repository; it is better to keep the submission git branch clean -- exactly an R package, no more or less.

**Comment by pcastellanoescuder** [comment]
Thanks @mtmorgan !! Seems that Dockerfile was the problem...

**Comment by pcastellanoescuder** [comment]
@mtmorgan I'm not sure how to deal with "ABNORMAL" label... Seems that BiocCheck is OK but I don't know how to fix this status...

Could you provide me some feedback about?

Thanks a lot:)

**Comment by lshep** [comment]
The abnormal is on our end.  we  temporarily had the tracker offline.  I will manually rerun the issues and it should clear up.

**Comment by pcastellanoescuder** [comment]
Great! Thanks @lshep :)

**Comment by pcastellanoescuder** [comment]
@lshep I think that this is the "last" bug but I have no idea on how to fix it... My package master branch doesn't have inst/doc directory...

Could you provide me some help?

Thanks:)

**Comment by lshep** [comment]
Ignore for now.  We normally try to have reviews within two weeks of a clean build.  I will try to have some feedback for you as soon as possible. Cheers.

**Comment by pcastellanoescuder** [comment]
Great! Anyway, I'll try to fix it.

Thanks @lshep :)

**Comment by dvantwisk** [comment]
I apologize for the wait. I will have a review for you soon.

**Comment by pcastellanoescuder** [comment]
Thanks a lot @dvantwisk

**Comment by pcastellanoescuder** [comment]
Dear @dvantwisk, just to remind you. Do you have any news about POMA?

Thank you:)

**Comment by dvantwisk** [comment]
I apologize for the wait. Here is the review. The package looks very well written and I only have a few issues. [REQUIRED] tags detail changes that must be made or addressed. [CONSIDER] tags detail changes that are advisable but not necessary. Message us back when you are done making changes.

GENERAL
- [ ] [REQUIRED] Your package repo is 62MB large. We generally want to see
repos no larger than 5MB. It seems that your `.git` directory is 62MB in size
where as the rest of your repo's size if negligible. This indicates that you
may have committed some large files to this repo and later deleted them. I ask
that you use the bfg-repo cleaner tool to try to reduce as much of the size as
possible. https://rtyley.github.io/bfg-repo-cleaner/

vignettes/POMA-demo.Rmd
- [ ] [REQUIRED] Remove section about installing from github. The current devel
version will be the master branch of your package once it is accepted. 

R/POMA_EDA_report.R
- [ ] [REQUIRED] This file appears to be a vignette. Should it be included as
a vignette?

R/PomaClust.R
- [ ] [REQUIRED] L39: I think this should be `is(data[1], "MSnSet")`

R/PomaBoxplots.R
- [ ] [CONSIDER] L39: Use `match.arg()`. The `group` argument can be expressed
as `group = c("samples", "features")`. The default argument is the first
argument. The user's selection can be obtained in the body of the function
with `group <- match.arg(group)`. Using `match.arg()` is preferred because it
explicitly states the possible values of `group`. It will also throw an error
if any other argument to `group` is given. This can be applied to other
functions in this package.

vignettes
- [ ] [REQUIRED] Remove the documentation about using `github_install()`. Once
the package is accepted to Bioconductor, the devel branch will be the `master`
branch and it can be accessed by users who are using a devel version of
Bioconductor. https://www.bioconductor.org/developers/how-to/useDevel/

**Comment by pcastellanoescuder** [comment]
Dear @dvantwisk , thank you for your comments.

I answer below:

GENERAL
 
* [x]  [REQUIRED] Your package repo is 62MB large. We generally want to see
repos no larger than 5MB. It seems that your `.git` directory is 62MB in size
where as the rest of your repo's size if negligible. This indicates that you
may have committed some large files to this repo and later deleted them. I ask
that you use the bfg-repo cleaner tool to try to reduce as much of the size as
possible. https://rtyley.github.io/bfg-repo-cleaner/

_Done! The problem was the resolution (dpi) in vignette plots._ 

R/POMA_EDA_report.R
 
* [x]  [REQUIRED] This file appears to be a vignette. Should it be included as
a vignette?
 
_This is the output of a function (PomaEDA) that produces a PDF report. However, it's great to include this as a vignette. Now, it has been included and the POMA package offers 3 different vignettes._

R/PomaClust.R

* [x]  [REQUIRED] L39: I think this should be `is(data[1], "MSnSet")`
 
_Completely right! It has been changed in all functions._

R/PomaBoxplots.R

* [ ]  [CONSIDER] L39: Use `match.arg()`. The `group` argument can be expressed
as `group = c("samples", "features")`. The default argument is the first
argument. The user's selection can be obtained in the body of the function
with `group <- match.arg(group)`. Using `match.arg()` is preferred because it
explicitly states the possible values of `group`. It will also throw an error
if any other argument to `group` is given. This can be applied to other
functions in this package.

_This would be a great point but we think that it's better to keep the exact word to avoid confusions between users. Of course, we can discuss it for sure!_

vignettes

* [x]  [REQUIRED] Remove the documentation about using `github_install()`. Once
the package is accepted to Bioconductor, the devel branch will be the `master`
branch and it can be accessed by users who are using a devel version of
Bioconductor. https://www.bioconductor.org/developers/how-to/useDevel/

_Done!_

I look forward for your news!

Best,
Pol

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pcastellanoescuder.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("POMA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/POMA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
