### ISSUE TITLE
(inactive) monaR

### ISSUE THREAD

**Issue by gjgetzinger** [Bioconductor/Contributions#1528]
- Repository: https://github.com/gjgetzinger/monaR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

**Comment by mtmorgan** [comment]
Please update your package in response to the comments below. When revisions are complete please provide a brief comment summarizing the changes.

DESCRIPTION

- good

vignette

- The vignette showed some aspects of use, but as a naive user I was
  left wondering what to do next. For instance

    ```
    > mona_query(query = 'MCLR', from = 'text')
    MoNA query by structure/molecule identifier:
    query : MCLR 
    from : text 
    Results:
    Rows: 42
    Columns: 13
    $ compound    <list> [<data.frame[1 x 7]>, <data.frame[1 x 7]>, <data.frame[1…
    $ id          <chr> "EQ299207", "EQ299256", "EQ299206", "EQ299252", "EQ299202…
    $ dateCreated <dbl> 1.584040e+12, 1.584040e+12, 1.584040e+12, 1.584040e+12, 1…
    $ lastUpdated <dbl> 1.588836e+12, 1.588836e+12, 1.588836e+12, 1.588836e+12, 1…
    $ lastCurated <dbl> 1.588836e+12, 1.588836e+12, 1.588836e+12, 1.588836e+12, 1…
    $ metaData    <list> [<data.frame[30 x 6]>, <data.frame[30 x 6]>, <data.frame…
    $ annotations <list> [<data.frame[51 x 5]>, <data.frame[18 x 5]>, <data.frame…
    $ score       <df[,2]> <data.frame[26 x 2]>
    $ spectrum    <chr> "69.0335:0.979463 70.0651:58.792322 71.0492:1.422030 72.0…
    $ splash      <df[,5]> <data.frame[26 x 5]>
    $ submitter   <df[,5]> <data.frame[26 x 5]>
    $ tags        <list> [<data.frame[2 x 2]>, <data.frame[2 x 2]>, <data.frame[2…
    $ library     <df[,4]> <data.frame[26 x 4]>
    ```
    
  which obviously contains alot of information, but how am I going to
  access this, for instance it looks like there's a tibble inside
  somewhere, but how do I retreive it? `as_tibble()`? Also the
  list-of-data-frame columns seems to suggest a not-very-'tidy' data
  structure that the user will have to work hard to make tidy; can you
  outline how one might 'drill down' into this data, and in the
  process make sure that the data at each step has been made tidy for the user?
  
R

- `globalVariables()` usually indicates use of non-standard evaluation
  in the tidyverse, and best practices mean that these should be
  avoided. For instance I believe `select(foo)` should be written
  `select("foo")`, and `filter(bar == 1)` should be written
  `filter(.data$bar == 1)` where `.data` is imported from the `rlang`
  package.

- It is probably better to refactor the code around GET / POST so that
  there is afile 'httr-utilities.R' or something, where something like
  `POST_mona()` would implement transformation to JSON, the actual
  `httr::POST`, `stop_for_status()`, etc.
  
man

- In some ways I think the examples are _too_ extensive, e.g., for
  `mona_getMeta()` all examples are really 'the same'. I'm partly
  concerned about the network access implied by these in a nightly
  build, with each network access representing an opportunity for
  failure unrelated to the functionality of your package.

**Comment by gjgetzinger** [comment]
@mtmorgan Thanks for your comments. 

For your comment on the vignette, the package includes a number of helper functions that extract various aspects of the query results (e.g., `mona_getMeta` and `mona_getChem`). These helper functions are detailed in the vignette. The list-of-dataframe columns are very non-tidy, hence why I created the `mona_getMeta` and `mona_getChem` generics. My goal was to provide functions for accessing the most common aspects of the query results, but not limit the variables returned from `mona_query`, since I can not anticipate all possible use cases and the results returned by the API may change in the future. Does that make sense? If this is not an acceptable solution, I will incorporate the `mona_getMeta` and `mona_getChem` methods into `mona_query` and return only the tidied subset of API results to the user. 

Thanks for your suggestions on `globalVariables` and for moving the GET/POST functions into a separate set of functions.

**Comment by mtmorgan** [comment]
Maybe it is better for the object returned by `mona_query()` to display a summary of its content and indication of next steps, 
```
MoNA query by structure/molecule identifier:
query : atrazine 
from : name 
Results:
Rows: 181
Columns (13): compound, id, ...
see mona_getMeta(), mona_...
```
If it is still important to display the content in detail, I'm not really sure why the display is as a list-of-columns, instead of something like
```
MoNA query by structure/molecule identifier:
query : atrazine 
from : name 
Results:
Rows: 181
Columns (13): compound, id, ...
see mona_getMeta(), mona_...

# A tibble: 181 x 13
   compound id    dateCreated lastUpdated lastCurated metaData score$impacts
   <list>   <chr>       <dbl>       <dbl>       <dbl> <list>   <list>       
 1 <df[,7]… VF-N…     1.54e12     1.56e12     1.56e12 <df[,6]… <df[,2] [11 …
 2 <df[,7]… VF-N…     1.54e12     1.58e12     1.58e12 <df[,6]… <df[,2] [11 …
 3 <df[,7]… EA02…     1.49e12     1.59e12     1.59e12 <df[,6]… <df[,2] [12 …
 4 <df[,7]… MSJ0…     1.49e12     1.59e12     1.59e12 <df[,6]… <df[,2] [8 ×…
 5 <df[,7]… SM84…     1.49e12     1.59e12     1.59e12 <df[,6]… <df[,2] [12 …
 6 <df[,7]… JP01…     1.49e12     1.59e12     1.59e12 <df[,5]… <df[,2] [7 ×…
 7 <df[,7]… UA00…     1.49e12     1.59e12     1.59e12 <df[,6]… <df[,2] [12 …
 8 <df[,7]… VF-N…     1.54e12     1.56e12     1.56e12 <df[,6]… <df[,2] [11 …
 9 <df[,7]… EA02…     1.49e12     1.59e12     1.59e12 <df[,6]… <df[,2] [13 …
10 <df[,7]… VF-N…     1.54e12     1.56e12     1.56e12 <df[,6]… <df[,2] [11 …
# … with 171 more rows, and 19 more variables: $score <dbl>, spectrum <chr>,
#   splash$block1 <chr>, $block2 <chr>, $block3 <chr>, $block4 <chr>,
#   $splash <chr>, submitter$id <chr>, $emailAddress <chr>, $firstName <chr>,
#   $lastName <chr>, $institution <chr>, tags <list>, library$library <chr>,
#   $description <chr>, $link <chr>, $tag$ruleBased <lgl>, $$text <chr>,
#   annotations <list>

```

For e.g., 
```
> meta <- mona_getMeta(id_query_rst, var = 'category', value = 'mass spectrometry')
> meta
Rows: 173
Columns: 11
Groups: id [173]
$ id                   <chr> "AU202201", "AU202302", "AU202303", "AU202304", …
$ `collision energy`   <chr> "10 eV", "20 eV", "30 eV", "40 eV", "10 eV", "10…
$ `fragmentation mode` <chr> "CID", "CID", "CID", "CID", "CID", "CID", "CID",…
$ ionization           <chr> "ESI", "ESI", "ESI", "ESI", "ESI", "ESI", "ESI",…
$ `ionization energy`  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `ionization mode`    <chr> "positive", "positive", "positive", "positive", …
$ `mass accuracy_ppm`  <dbl> 0.008163109, 0.211471127, 0.211471127, 0.2114711…
$ `mass error_Da`      <dbl> 1.1920e-06, -3.5972e-05, -3.5972e-05, -3.5972e-0…
$ `ms level`           <chr> "MS2", "MS2", "MS2", "MS2", "MS2", "MS2", "MS2",…
$ `precursor type`     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ resolution           <dbl> 35000, 35000, 35000, 35000, 35000, 35000, 35000,…
```
I'm still not presented with a tibble-like object, or shown in the vignette that I can use this as a tibble. Naively I tried
```
as_tibble(meta)
```
and it 'worked' but is that correct? For instance I see
```
> class(meta)
[1] "mona_meta"  "grouped_df" "tbl_df"     "tbl"        "data.frame"
> class(tibble::as_tibble(meta))
[1] "tbl_df"     "tbl"        "data.frame"
```
so is it important that I've lost the 'grouped_df' part of the class definition?

I guess I'm coming at this as a naive user of the software, and my comment is that the vignette did not help me enough in understanding how to use it. I will leave it to you to identify specific ways of improving the documentation.

**Comment by mtmorgan** [comment]
will you be updating your package further?

**Comment by gjgetzinger** [comment]
> will you be updating your package further?

Yes, I plan to make updates, but haven't had time to implement them.
