### ISSUE TITLE
ILoReg R package

### ISSUE THREAD

**Issue by j0ntt** [Bioconductor/Contributions#1536]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/elolab/ILoReg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hello @j0ntt - There are ERRORs on the build report. Please address them so the review process can proceed.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
Hello @j0ntt  - 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: The 'GPL-3' license is a standard license so the LICENSE file 
isn't needed.

- [ ] SUGGESTION: Conside adding these automatically suggested biocViews:
        - ATACSeq, KEGG

- [ ] REQUIRED: The 'BugReports:' field should direct users to the 'Issues' on 
'GitHub', not just the 'GitHub' (this is reserved for the 'URL' field, like 
you have).

## CITATION

- [ ] REQUIRED: I wasn't able to successfully run `readCitationFile("inst/CITATION")`
on your CITATION file. See the following for details about CITATION files,
https://bioconductor.org/developers/package-guidelines/#citation.

## Vignettes

- [ ] REQUIRED: The 'ILoReg_files/figure-html' directory should be removed. 
These figures are created from the code within the vignette. The only image(s) 
that should be present are any necessary static images (like figure.png).

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how 
to download the package from Bioconductor. The code should look like the 
following,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ILoReg")
```

- [ ] REQUIRED: You cannot write the home directory of the user. You should 
create a temp file if you need the data for the rest of the vignette. This 
effects the `saveRDS` commands at lines 92 and 287.

- [ ] REQUIRED: Is there a reason to write the plots to a pdf? The images are 
created within the vignette.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 79 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 917 lines that are not.

Best,
Kayla

**Comment by j0ntt** [comment]
Hi @Kayla-Morrell 

All the required changes have been made. Additionally, I removed the redundant license file as suggested.

# DESCRIPTION
REQUIRED: The 'BugReports:' field should direct users to the 'Issues' on 'GitHub', not just the 'GitHub' (this is reserved for the 'URL' field, like you have).
**Response: This has been fixed in the new version.**

# CITATION

REQUIRED: I wasn't able to successfully run readCitationFile("inst/CITATION") on your CITATION file. See the following for details about CITATION files, https://bioconductor.org/developers/package-guidelines/#citation.
**Response: This has been fixed in the new version.**

# VIGNETTE
REQUIRED: The 'ILoReg_files/figure-html' directory should be removed.
These figures are created from the code within the vignette. The only image(s)
that should be present are any necessary static images (like figure.png).
**Response: This has been fixed in the new version.**

REQUIRED: The 'Installation' section should demonstrate to the user how
to download the package from Bioconductor. The code should look like the
following...
**Response: This has been fixed in the new version.**

REQUIRED: Is there a reason to write the plots to a pdf? The images are
created within the vignette.
**Response: I assume you mean png, because I can't find anywhere a command that specifies the plots to be pdf. I removed the `dev = 'png'` argument from the vignette's code.**

REQUIRED: You cannot write the home directory of the user. You should create a temp file if you need the data for the rest of the vignette. This effects the saveRDS commands at lines 92 and 287.
**Response: The save parts have been removed from the vignette's code."**

**Comment by Kayla-Morrell** [comment]
Hello @j0ntt - Thank you for making the necessary changes. I have reviewed them all and everything looks good. I'd be more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/j0ntt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ILoReg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ILoReg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
