### ISSUE TITLE
clustifyrdatahub

### ISSUE THREAD

**Issue by raysinensis** [Bioconductor/Contributions#1545]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rnabioco/clustifyrdatahub

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Rui, @raysinensis 
Do you intend to submit the `clustifyr` package as well? Thanks

**Comment by raysinensis** [comment]
Hi @LiNk-NY,
`clustifyr` had previously been submitted, and is already on Bioconductor.
Thanks.

**Comment by LiNk-NY** [comment]
@raysinensis 
Oh sorry, I did not see that.
Can you update the link in the `Description` field in the `DESCRIPTION` to point to the Bioconductor landing page? 
https://bioconductor.org/packages/clustifyr
I will review your package today. 
Best,
Marcel

**Comment by raysinensis** [comment]
Description has been updated, thanks!

**Comment by LiNk-NY** [comment]
Hi Rui, @raysinensis 
Thank you for your submission. 
Please see the review below. 

If you have any questions, feel free to post them below. 

Best,
Marcel

----


# clustifyrdatahub #1545

## DESCRIPTION

* Consider including ORCID IDs in `Authors@R`
* Remove extra packages in the `Suggests` field (`tibble`, `dplyr`, etc.). You
should only include packages that you use in the vignettes or examples.

## NAMESPACE

* Looks good

## vignettes

* Consider removing some columns that are not so relevant in the table output
when printing the metadata table (first chunk)
* Move installation section to the top.
* Remove mentions of GitHub.

Minor:
* Use `TRUE` and `FALSE` instead of T and F.

## R

* Looks good

## man

* Looks good

## /README.*

Same comments with vignettes:

* Move installation section to the top.
* Remove mentions to GitHub.

**Comment by raysinensis** [comment]
Hi @LiNk-NY 
Thanks for the suggested changes. They have all been revised as suggested.

**Comment by raysinensis** [comment]
@LiNk-NY 
Hi, all suggested changes have been made, however bumping version doesn't seem to trigger a rebuild in the system anymore?
Please let me know if anything else needs to be done.
Thanks!

**Comment by LiNk-NY** [comment]
Hi Rui, @raysinensis 
Did you push a version bump to `git@git.bioconductor.org:packages/clustifyrdatahub`?
Please respond line by line to the review. 
Best,
Marcel

**Comment by raysinensis** [comment]
Hi Marcel,
All requested changes have been made. See below for details. 
I have also now triggered a build.

# clustifyrdatahub #1545
## DESCRIPTION
* Consider including ORCID IDs in `Authors@R`
**added**
* Remove extra packages in the `Suggests` field (`tibble`, `dplyr`, etc.). You
should only include packages that you use in the vignettes or examples.
**removed all used packages in examples**
## NAMESPACE
* Looks good

## vignettes
* Consider removing some columns that are not so relevant in the table output
when printing the metadata table (first chunk)
**removed**
* Move installation section to the top.
**Installation now at the top**
* Remove mentions of GitHub.
**removed**
 
Minor:

* Use `TRUE` and `FALSE` instead of T and F.
**Cases have been fixed**
## R
* Looks good
 
## man
* Looks good
 
## /README.*
Same comments with vignettes:
**made same edits as vignette**
* Consider removing some columns that are not so relevant in the table output
   when printing the metadata table (first chunk)
**removed**
* Move installation section to the top.
**moved**
* Remove mentions to GitHub.
**removed**

**Comment by LiNk-NY** [comment]
Thank you for your quick follow up!
Please use `BiocManager::install` in the installation instructions instead of GitHub. 
Everything else looks good. I will accept once you make that change. 
-MR

**Comment by raysinensis** [comment]
Hi @LiNk-NY 
Changes have been made for installation to both readme and vignette.
Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/raysinensis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("clustifyrdatahub")`. The package 'landing page' will be created at

https://bioconductor.org/packages/clustifyrdatahub

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
