### ISSUE TITLE
SeqGate

### ISSUE THREAD

**Issue by srialle** [Bioconductor/Contributions#1548]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/srialle/SeqGate

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package must be updated interoperate with [standard Bioconductor data representations][2], especially [SummarizedExperiment][1], by accepting these objects as inputs and returning as outputs (when appropriate).

[1]: https://bioconductor.org/packages/SummarizedExperimient
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by LiNk-NY** [comment]
Hi @srialle 
Sorry for the delay in getting your package reviewed. 
I will have a look at it in the next couple of days. 
In the meantime, please bump the version and push to the `git@git.bioconductor.org` location above.
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Stéphanie @srialle 

I had a look the package since it was quite compact.
Please see the review below. 
Remember to respond line by line to the comments. 
If you have any questions, include them in the comments section below. 

Best regards,
Marcel

---

# SeqGate #1548

## DESCRIPTION

* Looks good and light weight in terms of dependencies.
* Please add a `BugReports:` field to the `DESCRIPTION` file.

## NAMESPACE

* Looks good

## vignettes

* Please include an `Installation` section in the vignette that uses
`BiocManager::install`.
* Add a more descriptive name to example dataset
* I think it would be helpful to allow a `SummarizedExperiment` input with
`colData` annotations that indicate biological conditions in `applySeqGate`.
* The return value could then be a `SummarizedExperiment` with
`rowData` that indicate kept or filtered rows, `onFilter`, and `threshold`
values.

## R

* There seems to be a typo in the `ckeckForReplicates` function name.
* Use `data.matrix` on a `data.frame` avoid the `while` loop and the
cyclomatic complexity
* The `checkReadCounts` can be avoided by using a `SummarizedExperiment`
which already implements such checks.
* Avoid using `cat` for warnings / error messages (use `message`, `warning`, or
`stop`)
* Don't use keywords in the error / warning messages (e.g., `ERROR`, `WARNING`)
these are output by the `stop` and `warning` functions. For example, run this
in your console `stop("ERROR")`.

## tests

* Tests look good
* If possible, avoid using an external dataset and use generated data
to test your functions
* Avoid using `rm(list=list())`

**Comment by srialle** [comment]
Hi Marcel @LiNk-NY,
Thank you for your review. No problem for the delay, I was myself away from office until last Monday. I'll respond your comments and push to git@git.bioconductor.org as soon as I have time.
Best regards,
Stéphanie

**Comment by LiNk-NY** [comment]
Hi Stéphanie, @srialle 
Please provide any updates. 
Thank you.
-Marcel

**Comment by srialle** [comment]
Hi Marcel, @LiNk-NY 
I have pushed a new version that fixes some of the remarks you made in the review. I am currently working to deal with SummarizedExperiment objects and I'll push a new version soon.
Best regards,
Stéphanie

**Comment by LiNk-NY** [comment]
Thank you Stéphanie @srialle for making those changes. They're looking good.
Can you respond to the review line-by-line? Thank you. 

Best regards,
Marcel

**Comment by srialle** [comment]
Dear Marcel @LiNk-NY ,
I'm sorry I forgot to make the R CMD ckeck before pushing. I did not yet updated the vignette after the addition of SummarizedExperiment support. I will do it by the end of the week, and response line by line to the review.
Best regards,
Stéphanie

**Comment by LiNk-NY** [comment]
Thanks for providing an update Stéphanie! :)

**Comment by srialle** [comment]
Dear Marcel @LiNk-NY ,

This time the package should pass the different checks. 4 "NOTES" remains in the "R CMD BiocCheck" output :
*  NOTE: Consider adding these automatically suggested biocViews:
      Coverage
=> This does not seem relevant for my package
* NOTE: Consider shorter lines; 1 lines (0%) are > 80 characters
      long.
    => This line is the affiliation line in the vignette, but I can't change it.
* NOTE: Consider multiples of 4 spaces for line indents, 11
      lines(2%) are not.
    => the mentionned lines corresponds to line return for function which needs many arguments. I think it is better if I leave them like this.
* NOTE: Cannot determine whether maintainer is subscribed to the
      bioc-devel mailing list
    => I guess you might be able to verify my subscription.
      
I have changed th input of my main function to be a SummarizedExperiment.
Please find below my responses to your review.

Best regards,
Stéphanie

----------------------------------------------------------------------
SeqGate #1548
**DESCRIPTION**

* Looks good and light weight in terms of dependencies.

   => added dependency tu SummarizedExperiment and GenomicRanges

* Please add a BugReports: field to the DESCRIPTION file.
   => Done

**NAMESPACE**

 * Looks good
=> Hope it's still the case ^

**vignettes**
 
* Please include an Installation section in the vignette that uses BiocManager::install.
=> Done
* Add a more descriptive name to example dataset
=> dataTest renamed data_MiTF_1000genes
* I think it would be helpful to allow a SummarizedExperiment input with
   colData annotations that indicate biological conditions in applySeqGate.
=> Done
* The return value could then be a SummarizedExperiment with
 rowData that indicate kept or filtered rows, onFilter, and threshold
 values.
=> now the output value is the input SummarizedExperiment with a new column in rowData named onFilter (boolean) and a new value in metadata for threshold.

**R**

* There seems to be a typo in the ckeckForReplicates function name.
  => fixed
* Use data.matrix on a data.frame avoid the while loop and the cyclomatic complexity
  => I'm sorry, this is not clear to me. Can you be more specific on what I have to change please?
* The checkReadCounts can be avoided by using a SummarizedExperiment
     which already implements such checks.
   => I have modified it but not suppressed it as some of the checks are not automatically made at the creation of a SummarizedExperiment object.

* Avoid using cat for warnings / error messages (use message, warning, or
     stop)
     => Done
* Don't use keywords in the error / warning messages (e.g., ERROR, WARNING)
     these are output by the stop and warning functions. For example, run this
     in your console stop("ERROR").
     => Done

**tests**

* Tests look good
*  If possible, avoid using an external dataset and use generated data
    to test your functions
=> Done
* Avoid using rm(list=list())
=> Removed

**Comment by LiNk-NY** [comment]
Hi Stéphanie, @srialle 

> Use data.matrix on a data.frame avoid the while loop and the cyclomatic complexity
=> I'm sorry, this is not clear to me. Can you be more specific on what I have to change please?

The `checkReadCounts` function should use `data.matrix` instead of the `if (!is.matrix(counts))` section of code.

I will have a quick second look at your code. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Stéphanie, @srialle 

The changes look great! 
Thanks for updating the package and thank you for your contribution to Bioconductor. 
:tada: 

-Marcel

**Comment by srialle** [comment]
Hi Marcel @LiNk-NY ,
Thanks for your messages and for having accepted my package!
Do I have anything else to do?
Thanks again,
Stéphanie

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/srialle.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SeqGate")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SeqGate

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
