### ISSUE TITLE
flowPloidyData package for consideration for Bioconductor

### ISSUE THREAD

**Issue by plantarum** [Bioconductor/Contributions#155]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/plantarum/flowPloidyData

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by plantarum** [comment]
AdditionalPackage: https://github.com/plantarum/flowPloidy

**Comment by plantarum** [comment]
I'm not sure how to fix this. The only error I see is:

```
* Checking for bioc-devel mailing list subscription...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL connect error
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
Execution halted
```
This suggests there's a connection error on your build server?

I am registered on the bioc-devel mailing list, and see that I have received emails from the list to the email address listed in the DESCRIPTION file as recently as 13 hours ago. Also, running BiocCheck locally passes, so I don't know what else I can do at this end?

**Comment by mtmorgan** [comment]
Thanks for your contribution. Please address the following. When done,
please post a short comment outlining the steps taken for each.

DESCRIPTION

- Good!
- Any additional biocViews terms?

NAMESPACE

- Good!

vignettes

- please update the installation instructions to how they will be once
  the package is accepted -- biocLite('flowPoidy')
- Never use direct slot access as the 'public' interface to your
  classes. Instead, reuse existing or provide new 'accessors'. The
  accessors may be simple functions that provide direct slot access,
  or functions that access several slots to return information to the
  user in a way that is useful to them, rather than useful to you as a
  developer.

R

- See above about providing accessors. Use these internally, so that
  the accessors are the only place where direct slot access
  occurs. This design principle separates 'interface' from
  'implementation', allowing the former to be conveniently constant
  while freeing the latter to take different form as the package
  matures.
- Remember that R works well on vectors, and that calculations that
  use iteration are to be prefered. A specific example is models.R:293
  
        for(j in channels){
            res <- res + j^(1/3) * intensity[j] * 2 /
                (pi * j * sqrt(xx/j * (1 - xx/j)))
        }

  which can be replaced by something like
  
        denominator <- (pi * channels * sqrt(xx/channels * (1 - xx / channels)))
        res <- res + 
            cumsum(channnels ^(1/3) * intensity[channels] * 2 / denominator)

  There seem to be other places in the code where similar
  opportunities exist; please carefully review the entire package for
  use of vectorization.
- `eval()` is rarely needed; can it's use at flowAnalysis.R:47 be
  re-cast as a simple function call?

man

- The documentation is fine, if a bit sparse, particularly in the
  description of what functions do.

NEWS

- format so that `news()` works on the installed package, and of
  course have reasonable content.
  
        Changes in version 1.0.0
        ------------------------
        
        NEW FEATURES
        
            o Key feature 1

            o Key feature 2
        
  with additional headings as the package develops of 'BUG FIXES' and
  'USER-VISIBLE CHANGES'

flowPloidyData

- This package looks fine.

**Comment by plantarum** [comment]
# DESCRIPTION
- Added Regression, Visualization biocViews

# Vignette
- Updated installation instructions to Bioconductor
- added accessors and updated vignette. The original vignette directly accessed slots to mimic behaviours that are handled by interactive functions in normal use. This is now done with unexported functions instead.

# R
- added accessor functions for all slots that need to be queried from package code, and replacement functions for slots that need to be updated. These aren't exported, as the package already provides access to these values for users via other functions (which now use the accessors internally). 
- replaced the inner loops in several functions in models.R with vectorized equivalents. Still some remaining loops where vectorizing is not possible, as the value for one element in a vector depends on the values at several other elements.
- removed the call to `eval` in flowAnalyze.R, replaced with a normal call to `nlsLM`.

**Comment by plantarum** [comment]
The warning indicates that BiocCheck wants me to include more executable chunks in my vignette. I have a lot of chunks with `eval = FALSE` because they are demonstrating interactive functions, which cannot be evaluated in a vignette. In this situation I would prefer to leave the chunks in as-is.

**Comment by mtmorgan** [comment]
Thanks for your changes. I will accept the package to Bioconductor. It will be added to our svn and nightly build system; additional information will be sent in several days.

**Comment by plantarum** [comment]
Wonderful, thanks for your help!
