### ISSUE TITLE
ggtreeExtra

### ISSUE THREAD

**Issue by xiangpin** [Bioconductor/Contributions#1550]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/ggtreeExtra

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
3 August, 2020
 
Please revise your package in response to the following notes. When done, please post a comment indicating how you have responded to each.

DESCRIPTION
 
 - good
 
vignettes

- please mark the code chunk with package installation instructions with `eval = FALSE`.

- This is a stylistic comment so please ignore if you wish. I find code difficult to read when the indentation is aligned to a `(`, because the leading space can be large and inconsistent. I would write the code at ggtreeExtra.Rmd:219 as (I think this follows the tidyverse style guide, except with 4-space indentation, https://style.tidyverse.org/pipes.html#long-lines-2)

    ```{r}
    p2 <- 
        p1 + 
        geom_fruit_list(
            geom_fruit(
                data = df,
                geom = geom_bar,
                mapping = aes(y=id, x=value, fill=group2),
                orientation = "y",
                stat = "identity"
            ),
            scale_fill_manual(values=c("blue", "red")), # To map group2
            new_scale_fill(), # To initialize fill scale.
            geom_fruit(
                data = dt,
                geom = geom_star,
                mapping = aes(y=id, x=value, fill=group),
                size = 2.5,
                color = NA,
                starstroke = 0
            )
        ) + 
        new_scale_fill()
    ```
    
R

- the style comment above applies to the R code and examples.

- Lines like (method-ggplot-add.R:16

    ```{r}
    if (layout=="inward_circular" || flagreverse){orientation <- -1}else{orientation <- 1}
    ```
    
  are excessively compact and difficult to read. I would write as
  
    ```{r}
    if (layout == "inward_circular" || flagreverse) {
        orientation <- -1
    } else {
        orientation <- 1
    }
    ```

- At method-ggplot-add.R:25 I would again aim for more consistent spacing, and with breaks at mathematically logical locations (e.g., after an operator rather than mid-way through function arguments).

    ```{r}
    dat[[paste0("new_",xid)]] <-
        orientation *
        normxy(refnum=plot$data$x, targetnum=dat[[xid]], ratio=object$pwidth)
    ```
    
- Use of `getFromNamespace()` seems to be asking for future trouble, since these are not part of the ggplot2 API. Are there no alternatives?

**Comment by xiangpin** [comment]
Thanks for your review. I have revised `ggtreeExtra` following your suggestions.

vignettes

+ The code chunk of installation instructions has been masked using `eval=FALSE`.
+ Yes, the style comment your suggested is easier to read, I have revised it.

R

+ I have revised related R function and examples using the style comment your suggested.
+ Because the funtions of `getFromNamespace` are needed by the object of `Position` of `ggplot2`, The `Position` of `ggtreeExtra` is a `extension` of `Postion` of `ggplot2`, So they also are needed by `ggtreeExtra`.

**Comment by mtmorgan** [comment]
I see that you have changed the formatting of the *specific* chunk of code I indicated, but the rest of the code remains unchanged?

**Comment by xiangpin** [comment]
I have changed the formatting of the code chunk that I think it is difficult to read.

**Comment by xiangpin** [comment]
ok, Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xiangpin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggtreeExtra")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggtreeExtra

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by xiangpin** [comment]
Hello, everyone
 I was pushing a patch version to `Bioconductor`, but some issues (the following) were generated. To solve the problem, what do I need to do?

```
Counting objects: 15, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 1.52 KiB | 519.00 KiB/s, done.
Total 15 (delta 12), reused 0 (delta 0)
remote: Error: Please bump the version again and push.
remote:
remote: The build did not start as expected. If the issue persists,
remote: please reach out at bioc-devel@r-project.org or post on the
remote: Github issue where your package is being reviewed.
remote:
remote: 500 Server Error: Internal Server Error for url: https://issues.bioconductor.org/start_build
remote:
To git.bioconductor.org:packages/ggtreeExtra.git
   7145622..6c32095  master -> master
```

**Comment by lshep** [comment]
This has been reported in multiple threads.  We are investigating the issue.

**Comment by lshep** [comment]
Please try again; the issue should be resolved. If you didn't do so already don't forget to pull from git.bioconductor.org to get the version bump changes from the release and resolve any merge conflicts in the DESCRIPTION.

**Comment by xiangpin** [comment]
Ok, thank you.
