### ISSUE TITLE
New package: preciseTAD

### ISSUE THREAD

**Issue by stilianoudakis** [Bioconductor/Contributions#1553]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dozmorovlab/preciseTAD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by stilianoudakis** [comment]
I have address the errors but when I go to push upstream to generate a new build I receive this message:

$ git push -u upstream master
The authenticity of host 'git.bioconductor.org (34.192.48.227)' can't be established.
ECDSA key fingerprint is SHA256:nXILc5fVCnDfOID8HgPi+mSufGtr2JMYgnRa1JAQj/Q.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'git.bioconductor.org,34.192.48.227' (ECDSA) to the list of known hosts.
Connection closed by 34.192.48.227 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can anyone provide me with a potential solution?

**Comment by stilianoudakis** [comment]
I am unable to push to bioconductor
git@git.bioconductor.org:packages/preciseTAD
to generate a new build. I receive the following message:

$ git push -u upstream master
The authenticity of host 'git.bioconductor.org (34.192.48.227)' can't be
established.
ECDSA key fingerprint is SHA256:nXILc5fVCnDfOID8HgPi+mSufGtr2JMYgnRa1JAQj/Q.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'git.bioconductor.org,34.192.48.227' (ECDSA) to
the list of known hosts.
Connection closed by 34.192.48.227 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have already gone through the steps for generating an ssh key. Could
someone provide some details for a potential solution?

**Comment by nturaga** [comment]
# preciseTAD review

## build 

ok

## install 

ok

## DESCRIPTION

* Description section needs to be like a paper abstract. Please elaborate.

## NAMESPACE

* ok

## Vignettes

* ok

## R 

* I'm very particular about robustness of the code, whihc are
  highlighted in the build report very clearly. Please fix these.

```
   * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        bedToGRangesList.R (line 31, column 15)
        createTADdata.R (line 185, column 19)
        createTADdata.R (line 203, column 27)
        createTADdata.R (line 207, column 27)
        createTADdata.R (line 211, column 27)
        createTADdata.R (line 216, column 27)
        createTADdata.R (line 221, column 27)
        createTADdata.R (line 292, column 19)
        createTADdata.R (line 310, column 27)
        createTADdata.R (line 314, column 27)
        createTADdata.R (line 318, column 27)
        createTADdata.R (line 323, column 27)
        createTADdata.R (line 328, column 27)
        createTADdata.R (line 401, column 19)
        createTADdata.R (line 419, column 27)
        createTADdata.R (line 423, column 27)
        createTADdata.R (line 427, column 27)
        createTADdata.R (line 432, column 27)
        createTADdata.R (line 437, column 27)
        createTADdata.R (line 501, column 19)
        createTADdata.R (line 519, column 27)
        createTADdata.R (line 523, column 27)
        createTADdata.R (line 527, column 27)
        createTADdata.R (line 532, column 27)
        createTADdata.R (line 537, column 27)
        extractBoundaries.R (line 31, column 34)
        preciseTAD.R (line 270, column 14)
        preciseTAD.R (line 272, column 18)
        preciseTAD.R (line 295, column 38)
        preciseTAD.R (line 314, column 22)
        preciseTAD.R (line 426, column 19)
        preciseTAD.R (line 432, column 27)
        preciseTAD.R (line 459, column 19)
        preciseTAD.R (line 461, column 23)
        preciseTAD.R (line 462, column 23)
        TADrandomForest.R (line 168, column 14)
```

* Use `<-` instead of `=` within the code. It's more "R" like. Be consistent.

* Try to break up the function like `createTADdata` into multiple
  functions with some helper functions. This will make it easier to
  debug. Maybe it doesn't need to be 50 lines or less, but make sure
  your function is easy to follow by reviewers.

```
    * NOTE: Recommended function length <= 50 lines.
      There are 4 functions > 50 lines.
      The longest 5 functions are:
        createTADdata() (R/createTADdata.R, line 63): 504 lines
        preciseTAD() (R/preciseTAD.R, line 135): 355 lines
        TADrandomForest() (R/TADrandomForest.R, line 83): 200 lines
        TADrfe() (R/TADrfe.R, line 64): 69 lines
        juicer_func() (R/preciseTAD.R, line 419): 37 lines
```

* Remove the "nested" functions and put them outside the main
  functions. There is no real value add t the nested functions.

**Comment by nturaga** [comment]
Hi @stilianoudakis 

It doesn't seem like you made some of the requested changes in the review for the package. If you want your package to accepted in the next release cycle please try to make the fixes in the next week.

http://bioconductor.org/developers/release-schedule/

**Comment by stilianoudakis** [comment]
Hi Nitesh,

Thank you for your message. I am a little confused because I thought I
addressed the requested changes that were proposed in a previous email. I
have listed the things that I addressed in red:

* NOTE: Avoid 1:...; use seq_len() or seq_along()

* Use <- instead of = within the code. It's more "R" like. Be consistent.

* Remove the "nested" functions and put them outside the main

The only point I have not changed yet was the following:

* Try to break up the function like createTADdata into multiple
functions with some helper functions.

I would prefer to keep the function as is for ease of use. But I
understand if it needs to be broken up and I will try to make the
changes if necessary.

Could you please let me know if there are additional changes that you
had in mind? Thank you for taking the time to review my package!


Best,


Spiro Stilianoudakis

PhD Candidate | Department of Biostatistics

Virginia Commonwealth University

**Comment by stilianoudakis** [comment]
Hi Nitesh,

Thank you for your message. I am a little confused because I thought I
addressed the requested changes that were proposed in a previous email. I
have listed the things that I addressed in red:

* NOTE: Avoid 1:...; use seq_len() or seq_along()

* Use <- instead of = within the code. It's more "R" like. Be consistent.

* Remove the "nested" functions and put them outside the main

The only point I have not changed yet was the following:

* Try to break up the function like createTADdata into multiple
functions with some helper functions.

I would prefer to keep the function as is for ease of use. But I
understand if it needs to be broken up and I will try to make the
changes if necessary.

Could you please let me know if there are additional changes that you
had in mind? Thank you for taking the time to review my package!


Best,


Spiro Stilianoudakis

PhD Candidate | Department of Biostatistics

Virginia Commonwealth University

**Comment by nturaga** [comment]
Your package is fine. I was talking about the lack of modularization in `createTADdata.R`.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stilianoudakis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("preciseTAD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/preciseTAD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by stilianoudakis** [comment]
Hi,

I have made a minor edit in one of the helper functions in my package.
Thus, I have changed the version in the DESCRIPTION from 1.1.0 to 1.1.1.
However, it does not seem to have triggered a new build when I pushed to
the upstream remote. Would you happen to know why that is or what I am
doing wrong? Thank you in advance for any help!

Best,

Spiro

**Comment by mtmorgan** [comment]
Once your package has been accepted to Bioconductor, the builds occur nightly, as summarized at http://bioconductor.org/checkResults/devel/bioc-LATEST/preciseTAD/. From that page, you can see that the last build started at 
```
Snapshot Date: 2020-11-23 14:41:10 -0500 (Mon, 23 Nov 2020)
```
and the build report was published on
```
This page was generated on 2020-11-24 12:01:41 -0500 (Tue, 24 Nov 2020).
```
but from your git log the version bump was
```
commit 8ca9dd519adabc6fb03037b647113838212c81bf (HEAD -> master, origin/master, origin/HEAD)
Author: stilianoudakis <stilianoudasc@mymail.vcu.edu>
Date:   Tue Nov 24 15:23:44 2020 -0500

    version bump
```
so the nightly build started before your version bump. It should be captured in tonight's build, with the times approximately the same as those indicated here but shifted by a day.
