### ISSUE TITLE
FieldEffectCrc

### ISSUE THREAD

**Issue by dampierch** [Bioconductor/Contributions#1554]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BarcUVa-Seq/FieldEffectCrc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hello @dampierch - 

The package looks great, I have just a couple minor points about the vignette. The suggestion doesn't need to be changed but the required one should be. Comment back here when you are ready for me to re-review.

## Vignette

- [ ] SUGGESTION: For the 'Installation' section the code could be simplified
to something like, with `eval = FALSE`:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(c("SummarizedExperiement", "ExperimentHub", "FieldEffectCrc")
```

I've added "FieldEffectCrc" to this list because technically this section should
be demonstrating to the user how to install and load the package from
Bioconductor.

- [ ] REQUIRED: The first code chunk under "Filter Genes" is missing the R code
distinction. Be sure to add {r} to the code chunk (line 213).

Best, 
Kayla

**Comment by dampierch** [comment]
Hi @Kayla-Morrell -

Thank you for reviewing my package and for your help! I updated the vignette to address your suggestion and requirement. The revised package passed `R CMD build`, `R CMD check`, and `R CMD BiocCheck` on my machine, so I changed the version number to 0.99.__1__ and pushed to GitHub.

- [x] SUGGESTION: For the 'Installation' section the code could be simplified
to something like, with `eval = FALSE`

- [x] REQUIRED: The first code chunk under "Filter Genes" is missing the R code
distinction. Be sure to add {r} to the code chunk (line 213).

Please let me know if I misunderstood anything.

Thank you
Chris

**Comment by Kayla-Morrell** [comment]
Hello @dampierch - Things look great now, thanks for making those changes! I'd be more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dampierch.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("FieldEffectCrc")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FieldEffectCrc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
