### ISSUE TITLE
QFeatures

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/Contributions#1556]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rformassspectrometry/QFeatures

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lgatto** [comment]
- The maintainer has an account on the Bioconductor support site, but under his gmail address.
- I confirm that the maintainer is subscribed to the bioc-devel mailing list.

**Comment by lgatto** [comment]
I have looked at the errors

1. As noted above `ERROR: Maintainer must register at the support site` is a false positive. I am registered on the support site but using my google account.
2. I installed R 4.0 and Bioconductor version 3.12 on Windows and was unable to reproduce the error on `tokay1`.  Any further help would be appreciated here.

**Comment by Kayla-Morrell** [comment]
Hello @lgatto - Thank you for your patience, I will work on getting an initial review of the package posted within the next couple of days.

**Comment by Kayla-Morrell** [comment]
Hello @lgatto -

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

*R CMD BiocCheck*

- [ ] ERROR: Package Source tarball exceeds Bioconductor size requirement, 
package size is 5.2MB and our size requirement is 5.0MB. 
HOWEVER, this isn't showing up on the build report for the SPB so there might 
not need to be any changes, just something to keep an eye on. I got this after 
building and checking locally.

- [ ] ERROR: Maintainer must register at the support site. *But I believe you 
mentioned above that you are registered but with a different email address?*

## DESCRIPTION

- [ ] SUGGESTION: A WARNING is being thrown in BiocCheck because 'Description:' is 
too concise. This will be removed if there are more than 20 words. But then a 
NOTE will be produced because there are less than 3 sentences. Up to you if you 
want to fix this.

## Man pages

- [ ] REQUIRED: Add non-empty \value sections to the following man pages:
        - man/QFeatures-class.Rd
        - man/QFeatures-filtering.Rd
        - man/QFeatures-processing.Rd

- [ ] SUGGESTION: Consider adding runnable examples to the following man pages 
with document exported objects. Since this is a shiny app function it might be 
useful to include it in a `\donttest{}` chunk to insure valid R code is being 
used.
        - display.Rd

## R code

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` instead where possible. Found 
in files:
        - AssayLinks, lines 125, 177, 181, 333, and 338
        - QFeatures-class, line 265
        - QFeatures-functions, lines 6, 9, 25, 30, and 40
        - QFeatures-join, line 53
        - QFeatures-missing-data, lines 50 and 51
        - reduce, lines 4 and 126
        - subsetBy-methods, lines 35, 50, and 106

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 110 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 444 lines that are not.

Best,
Kayla

**Comment by lgatto** [comment]
## General package development

*R CMD BiocCheck*

- [X] ERROR: Package Source tarball exceeds Bioconductor size requirement,
package size is 5.2MB and our size requirement is 5.0MB.
HOWEVER, this isn't showing up on the build report for the SPB so there might
not need to be any changes, just something to keep an eye on. I got this after
building and checking locally.

The size was due to a rda data file that I substantially trimmed down.

- [X] ERROR: Maintainer must register at the support site. *But I believe you
mentioned above that you are registered but with a different email address?*

Yes, I confirm.

## DESCRIPTION

- [X] SUGGESTION: A WARNING is being thrown in BiocCheck because 'Description:' is
too concise. This will be removed if there are more than 20 words. But then a
NOTE will be produced because there are less than 3 sentences. Up to you if you
want to fix this.

I have updated the description.

## Man pages

- [X] REQUIRED: Add non-empty \value sections to the following man pages:
    - man/QFeatures-class.Rd
    - man/QFeatures-filtering.Rd
    - man/QFeatures-processing.Rd

Done.

- [X] SUGGESTION: Consider adding runnable examples to the following man pages
with document exported objects. Since this is a shiny app function it might be
useful to include it in a `\donttest{}` chunk to insure valid R code is being
used.

   - display.Rd

Done.

## R code

- [X] REQUIRED: Avoid `sapply()`; use `vapply()` instead where possible. Found
in files:

     - AssayLinks, lines 125, 177, 181, 333, and 338
     - QFeatures-class, line 265
     - QFeatures-functions, lines 6, 9, 25, 30, and 40
     - QFeatures-join, line 53
     - QFeatures-missing-data, lines 50 and 51
     - reduce, lines 4 and 126
     - subsetBy-methods, lines 35, 50, and 106

I have replaced all instances except:

     - AssayLinks::177: is never simplified, always a list of S4 objects. I use `sapply()` rather than `lapply()` to get a named list.
     - reduce::126: I can't predict the value of the output here.

- [X] SUGGESTION: For formatting reasons, consider shorter lines. There are 110
lines that are > 80 characters long.

I have shortened a few of them, but many are fine, such as calls to `stop()`, or `@aliases` 
lines in documentation.

- [X] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 444 lines that are not.

The indentation is handled by my editor and I prefer to keep it as is.

I'll push version 0.99.1 now.

**Comment by lgatto** [comment]
The residual error reported is because the maintainer email address isn't recognised on the support site, but I am registered with another one.

**Comment by Kayla-Morrell** [comment]
@lgatto - Thank you for making the necessary changes. I have reviewed them all and they look good. I am more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgatto.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("QFeatures")`. The package 'landing page' will be created at

https://bioconductor.org/packages/QFeatures

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lgatto** [comment]
Thank you for your review Kayla :-)
