### ISSUE TITLE
Nebulosa

### ISSUE THREAD

**Issue by joseah** [Bioconductor/Contributions#1567]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/powellgenomicslab/Nebulosa

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
3 August, 2020

DESCRIPTION, NAMESPACE

- good

vignettes

- introduction.Rmd:42 use BiocFileCache (and add as a Suggests: dependency) to avoid downloading this file each time this file is needed

    ```{r}
    url <- "https://s3-us-west-2.amazonaws.com/10x.files/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz"
    pbmc3k <- BiocFileCache::bfcrpath(rnames = url)
    ```
    
- It's frustrating that your vignette illustrates a Seurat workflow. Since you are contributing Bioconductor, why not illustrate the steps with Bioconductor packages? For instace the data is available as a SummarizedExperiment with

    ```{r}
    pbmc <- TENxPBMCData::TENxPBMCData("pbmc3k")
    ```
    
  Is there functionality not available or illustrated in https://osca.bioconductor.org ?
  
R (specific comments apply to code in general)

- generally clearly written

- helpers.R:11 `stop(paste0(...))` is equivalent to `stop(...)`, except when using the `collapse=` argument.

- coding style is not consistent, for instance indenting a fixed number of spaces (good) compared to aligning at `(` (bad) as in the following two logical lines of code from helpers.R:48

    ```{r}
    res <- apply(
        vars, 2, calculate_density,
        cell_embeddings, method, adjust
    )
    p <- mapply(plot_density_, as.list(as.data.frame(res)), colnames(res),
                MoreArgs = list(cell_embeddings, dim_names, shape, size,
                                "Density",
                                pal = pal
               ), SIMPLIFY = FALSE
    )
    ```
            
- methods.R:157 direct slot access of Bioconductor S4 objects is strongly discouraged, as it breaks the interface / implementation boundary that is one of the major strengths of object-oriented systems. Thus

    ```{r}
    assayNames(object)  # not names(object@assays)
    assay(object, "logcounts") # not object@assays@data[[slot]]
    ```

  Many operations are illustrated in the SummarizedExperiment vignette (e.g., section 4, "Common operations on `SummarizedExperiment`"
  
man

- ok

**Comment by joseah** [comment]
Dear Martin, 

Thank you for your very helpful feedback.
I've addressed your observations in the newest version:

> introduction.Rmd:42 use BiocFileCache (and add as a Suggests: dependency) to avoid downloading this file each time this file is needed

I've implemented BiocFileCache in the vignettes and added the package in the DESCRIPTION file as indicated.

> It's frustrating that your vignette illustrates a Seurat workflow. Since you are contributing Bioconductor, why not illustrate the steps with Bioconductor packages? For instace the data is available as a SummarizedExperiment with

I completely agree with this point. I've now included a main vignette using the Bioconductor framework suggested in **OSCA** (using `scran`, `scater`, and `DropletUtils`). Also, I've added pertinent links to the OSCA ebook so people can explore more in each step along with the vignette. The original vignette based on Seurat is now a second resource available within the package. Both vignettes are independent of each other to allow users consulting the most suitable documentation for them. In this regard, I've avoided using the `TENxPBMCData`and downloading the data instead via `BiocFileCache` (as you suggested) for three main reasons: 1. Count data in `TENxPBMCData` is stored as a `DelayedMatrix` object. This breaks the interface between `Bioconductor` and `Seurat` objects via `Seurat::as.Seurat()`, since `DelayedMatrix`objects are not defined as a possible storage option within Seurat. This avoids a clean use of `TENxPBMCData` in the Seurat vignette. 2. I believe showing the whole process from importing the data to visualizing with Nebulosa adds more value to the vignette, as users who may start understanding how to import their own data can start doing it using various options from Bioconductor packages (in this case with `DropletUtils`). Additionally, `DropletUtils` imports the count data as a `dgCMatrix` object, which is compatible with Seurat too. 3. Using `dgCMatrix` instead of `DelayedMatrix` objects results in a faster computation for this particular demo, resulting in faster creation of the vignettes.

> helpers.R:11 stop(paste0(...)) is equivalent to stop(...), except when using the collapse= argument.

This is now fixed in the current version

> coding style is not consistent, for instance indenting a fixed number of spaces (good) compared to aligning at ( (bad) as in the following two logical lines of code from helpers.R:48

Thanks for this comment, `biocstyle` introduced this style mismatch in those specific lines. This has now been fixed.

> methods.R:157 direct slot access of Bioconductor S4 objects is strongly discouraged, as it breaks the interface / implementation boundary that is one of the major strengths of object-oriented systems

I really appreciate the feedback on this important observation. All data subsetting steps have been now fixed using the respective methods for each S4 object.

Builds in all OSs have now been generated. Let me know if you have any other comments.
I'd like to thank you again for your feedback and time.

Best,
Jose Alquicira Hernandez

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/joseah.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Nebulosa")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Nebulosa

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
