### ISSUE TITLE
nearBynding

### ISSUE THREAD

**Issue by vbusa1** [Bioconductor/Contributions#1569]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vbusa1/nearBynding

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package must have version 0.99.0 to begin the review process; please update and post a comment here when ready. Please review package and submission guidelines to ensure other requirements are met.

**Comment by vbusa1** [comment]
@mtmorgan version changed, thank you

**Comment by vbusa1** [comment]
Hi Nitesh,

Thank you for taking the time to help me improve my code. I am new to Bioconductor so I hope it's not too frustrating for you. The main problem I am having with building my package is that it requires the local system to have three softwares (CapR, StereoGene, and bedtools) in the path. Although I am editing my examples to 'dontrun' now so that the package can build, I would appreciate any recommendations for how to best provide examples for the user with this consideration. @nturaga 

Thanks, Veronica

**Comment by vbusa1** [comment]
This seems to be an issue on Bioconductor's end, since none of my code is changed and these packages should be available on the servers-- going to re-push to try again

**Comment by nturaga** [comment]
Hi,

Just to be clear on expectations from the reviewer http://bioconductor.org/developers/package-submission/#whattoexpect 

```
Once your package **builds and checks without errors or (avoidable) warnings**, a Bioconductor team member will provide a technical review of your package. Other Bioconductor developers and users with domain expertise are encouraged to provide additional community commentary. Reviewers will add comments to the issue you created.
```

Go through the http://bioconductor.org/developers/package-guidelines/ Guidelines because there are MANY areas your package doesn't meet the standards. 

Go through your build report, http://bioconductor.org/spb_reports/nearBynding_buildreport_20200805164015.html and make sure you solve the issues there.

If you want specific recommendations on how to do something within your package, point me to a line of code or a code chunk within your package (https://docs.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet).

**Comment by vbusa1** [comment]
Hi @nturaga,
The errors on the build report were on Bioconductor's end; I bumped the version and everything resolved itself. Can you please provide some guidance on unfulfilled guidelines? In the last ~week I modified every line to be <=80 characters, modified the tabs to 4 spaces, changed T/F to TRUE/FALSE, and ensured all the = were instead <-. It's not an unwillingness to adhere to guidelines but rather I am not noticing what guidelines I'm missing.

Sincerely thank you for reviewing for me,
Veronica

**Comment by nturaga** [comment]
Hi, 

I understand. I'll do a detailed review of your package this week and get back to you. The build system seems to have given the issue the "OK" tag. 

Best,

Nitesh

**Comment by vbusa1** [comment]
Hi Nitesh,

Thank you for your suggestions. They drove me to learn a few new skills and definitely improved my overall package.

NAMESPACE: All of my man pages and NAMESPACE were manually created. I learned how to use Roxygen so now they have been generated automatically (much easier for future use).

NEWS: The NEWS file is re-formatted

man: I kept one \dontrun example in CleanBAMtoBG since the file referenced is not available to the user through the package; all other examples are runnable, contingent on the user having the requisite software installed, even if they are marked \donttest.

R: I created utility functions (utilities.R file) to run bedtools, CapR, and StereGene and to check whether those software were available. I also created catches to stop the functions if the software is not available. I found the lapply functions you mentioned that could be avoided and have coded those lines more efficiently.

vignette: The vignette now tests whether the software is available and runs chunks that require that software if it is.

Please let me know if I need to make any further edits @nturaga.

Thanks,
Veronica

**Comment by vbusa1** [comment]
Hi Nitesh,

I'm following up to see whether you can provide an anticipated timeline for the review process? My PI and I have been working on a manuscript and he wants an estimate from me for when we might be able to submit. It's not a rush, just so we can plan. @nturaga 

Thank you,
Veronica

**Comment by nturaga** [comment]
> Hi Nitesh,
> 
> I'm following up to see whether you can provide an anticipated timeline for the review process? My PI and I have been working on a manuscript and he wants an estimate from me for when we might be able to submit. It's not a rush, just so we can plan. @nturaga
> 
> Thank you,
> Veronica

Thanks for your contribution. Your package looks good to be accepted.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vbusa1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("nearBynding")`. The package 'landing page' will be created at

https://bioconductor.org/packages/nearBynding

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
