### ISSUE TITLE
HMMRATAC

### ISSUE THREAD

**Issue by dvantwisk** [Bioconductor/Contributions#1570]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/HMMRATAC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
AdditionalPackage: https://github.com/Bioconductor/HMMRATACData

**Comment by mtmorgan** [comment]
The version number of HMMRATACData should be 0.99.0. I'll update it.

**Comment by mtmorgan** [comment]
The package contains a file larger than 5MB, and these cannot be added to our git; should the be an ExperimentHub package?
```
  /data/65283_treat_rep1.chr22.20to30MB.bam
```

**Comment by nturaga** [comment]
# HMMRATAC and HMMRATACData

## Build

* ok

## INSTALL 

* ok

## DESCRIPTION

* Use `Authors@R` instead of Author and Maintainer field.

* Malformed Description field: should contain one or more complete
  sentences.

## NAMESPACE 

ok

## R

* WARNING: Update R version dependency from 3.5.0 to 4.0.

* ok, seems like a wrapper function around a java based tool. Looks good. 

* jar file for HMMRATAC is in inst/ folder. This is ok.

## man

The HMMRATACData package seems to need more work to populate the man
pages and vignette.

```
* checking for missing documentation entries ... WARNING
Undocumented data sets:
  HMMRATACData
```

## tests

* There are no tests.

## vignette 

* All the code chunks are set to eval = FALSE. The vignette is non-functional.

# HMMRATACdata

Important details are missing, there is no vignette, R script or man
pages. Please check

https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

**Comment by nturaga** [comment]
Hi @dvantwisk ,

Since the package has been idle without any updates for about 30 days. I'm temporarily closing it. If you are able to get it into the next release, we can always reopen the package when you have time to address the issues in the review.

They are fairly minor, so take a look at them if you get a chance.

Hope things are going well.

Nitesh
