### ISSUE TITLE
HPAStainR

### ISSUE THREAD

**Issue by tnieuwe** [Bioconductor/Contributions#1571]
Update the following URL to point to the GitHub repository of
the package you wish to submit to *Bioconductor*

- Repository: https://github.com/tnieuwe/HPAStainR

Confirm the following by editing each check box to '[x]'

- [x]  I understand that by submitting my package to *Bioconductor*,
the package source and all review commentary are visible to the
general public.

- [x] I have read the *Bioconductor* [Package Submission](https://bioconductor.org/developers/package-submission/)
instructions. My package is consistent with the *Bioconductor*
[Package Guidelines](https://bioconductor.org/developers/package-guidelines/).

- [x] I understand that a minimum requirement for package acceptance
is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS.
Passing these checks does not result in automatic acceptance. The
package will then undergo a formal review and recommendations for
acceptance regarding other *Bioconductor* standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
includes monitoring the [support site](https://support.bioconductor.org/) for issues that users may
have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
of developments in the *Bioconductor* community, responding promptly
to requests for updates from the Core team in response to changes in
*R* or underlying software.

I am familiar with the essential aspects of *Bioconductor* software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
months, for bug fixes.
- [x] *Bioconductor* version control using [Git](http://bioconductor.org/developers/how-to/git/)
(optionally [via GitHub](http://bioconductor.org/developers/how-to/git/sync-existing-repositories/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by Kayla-Morrell** [comment]
Hello @tnieuwe,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: The 'Depends:' field is intended for packages that provide 
essential functionality for users of your package. It is unusual for more than 
three packages to be listed as 'Depends'. I would argue that 'shiny' could be 
moved to 'Imports:' since it isn't need for the main function(s) of this package.
I would also consider moving 'itbble' to 'Imports:' since it seems you only 
utilize it for `as_tibble()`, but that's just my suggestion. 

## NEWS

- [ ] REQUIRED: The version number doesn't seem correct in the NEWS file. 

## Vignettes

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to 
the users how to install the package from Bioconductor. The code should look 
something like the following and should include `eval = FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("HPAStainR")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: Line 38 - the text after the download_data code - you mention 
that you selected save, but it seems that you set `save_file` to `FALSE`. So is 
this statement still true?

- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and 
should include `SessionInfo()`.

## R code

- [ ] REQUIRED: For `HPA_data_downloader()` since you are querying a web 
resource for data you might consider looking at our documentation here:
http://bioconductor.org/developers/how-to/web-query/. There should be some 
thought about what happens if the website isn't accessible for some reason. A 
simple function that attempts X number of times and then fails if unreachable 
can help. Please implement this in some way.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 
57 lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 543 lines that are not.

Best,
Kayla

**Comment by tnieuwe** [comment]
Hello @Kayla-Morrell ,

Thank you for taking the time to review my package. I have done my best to address all issues below.

# DESCRIPTION

- [x] REQUIRED: The 'Depends:' field is intended for packages that provide
essential functionality for users of your package. It is unusual for more than
three packages to be listed as 'Depends'. I would argue that 'shiny' could be
moved to 'Imports:' since it isn't need for the main function(s) of this package.
I would also consider moving 'itbble' to 'Imports:' since it seems you only
utilize it for as_tibble(), but that's just my suggestion.

Based on your input shiny has been moved to imports as well as `tibble`, leaving only dplyr and tidyr as depends.

# News

- [x]  REQUIRED: The version number doesn't seem correct in the NEWS file.

I updated the news file to the current version, `0.99.0`

# Vignettes

- [x]  REQUIRED: There should be an 'Installation' section that demonstrates to
the users how to install the package from Bioconductor. The code should look
something like the following and should include eval = FALSE:

I have updated the vignette to include an installation section based on the code you gave.

- [x] SUGGESTION: We strongly encourage the use of table of contents.

I have generated a table of contents for the vignette with a `toc_depth` of 1.

- [x] REQUIRED: Line 38 - the text after the download_data code - you mention
that you selected save, but it seems that you set save_file to FALSE. So is
this statement still true?

In this case, I decided to edit the text itself rather than the code. The vignette is unable to correctly run with `save_file = TRUE` due to the download occurring in the vignette directory. As a result, I added clarifying text to explain that, the code is `save_file = FALSE`, but if set to `TRUE` the files would be downloaded in the current working directory. 

- [x] REQUIRED: The last section of the vignette should be 'Session Info' and
should include SessionInfo().

I have included a sessionInfo() section at the end of the markdown. 

# R code
- [x] REQUIRED: For HPA_data_downloader() since you are querying a web
resource for data you might consider looking at our documentation here:
http://bioconductor.org/developers/how-to/web-query/. There should be some
thought about what happens if the website isn't accessible for some reason. A
simple function that attempts X number of times and then fails if unreachable
can help. Please implement this in some way.

I have adapted HPA_data_downloader to include the function getURL from the suggested webpage.

- [x] SUGGESTION: For formatting reasons, consider shorter lines. There are
57 lines that are > 80 characters long.

The number of lines with greater than > 80 characters has been reduced to 12, and these remaining lines of code cannot be further reduced without changing the code itself.

- [x] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
line indents. There are 543 lines that are not.

The number of lines with line indents not of a multiple of 4 spaces has been reduced to 275. I attempted to use `formatR` to deal with both the indentation issue and the line width issue, but they generated problems for one another were fixing the line length (as done by `formatR`) ruined the indentation. If possible, I would like to fix this issue, but I am unaware of how to properly without using `BiocCheck` and attempting to by hand fix indentation issues 6 lines at a time.

**Comment by Kayla-Morrell** [comment]
Thank you @tnieuwe for making those changes. You will need to bump the version in the DESCRIPTION file in order for a build report to be produced.

**Comment by tnieuwe** [comment]
I just want to check if you wanted me to ping you @Kayla-Morrell after I bumped the version. If so, sorry I did not do it earlier, if not, sorry for bothering you by pinging you.

**Comment by Kayla-Morrell** [comment]
@tnieuwe - That's fine, I did see the version bump and the clean build. I'll be able to review the changes in the next day or so. 

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@tnieuwe - Thank you for making the changes mentioned above. I have looked over them and everything looks good. I am more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tnieuwe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HPAStainR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HPAStainR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
