### ISSUE TITLE
metabolomicsWorkbenchR: An R package for interfacing with the Metabolomics Workbench API

### ISSUE THREAD

**Issue by grlloyd** [Bioconductor/Contributions#1577]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/computational-metabolomics/metabolomicsWorkbenchR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
I apologize for the delay in review; I was away on vacation. I should have a review of your package in the next few days.

**Comment by lshep** [comment]
Thank you for your submission.  I few minor comments and clarifications: 

**Build Report**

- [ ] Please clean up the NOTES about DESCRIPTION and coding practices.  

**General**

- [ ] Please .gitignore the `appveyor.yml` and `codecov.yml` so these are not  included in a clone of the repository

**README**

- [ ] Please add Bioconductor installation instructions

**DESCRIPTION**

- [ ] Please remove `lazyData: true`. We have rarely found this useful and can actually slow the installation of a package.


**R / man pages**

- [ ] Perhaps provide a seealso in the package man page to direct to another help page with runnable code or where to get started?

- [ ] What data is provided in `sysdata.rda` that your functions use and should not be exposed to the user? Why is this needed?

Please respond back with updates and when you are ready for a re-review.  
Thank you 
Lori

**Comment by grlloyd** [comment]
Thank you for your feedback. I have responded to each comment below.

> Please clean up the NOTES about DESCRIPTION and coding practices.

I have...

- cleaned up the description
- replaced all uses of 1: with seq_len and seq_along
- split lines over 80 characters into multiple lines
- tried to fix incorrect indents. 

A small number of long lines and indent notes remain due to documentation generated by roxygen.

> Please .gitignore the appveyor.yml and codecov.yml so these are not included in a clone of the repository

Done

> Please add Bioconductor installation instructions

Done

> Please remove lazyData: true. We have rarely found this useful and can actually slow the installation of a package.

Done

> Perhaps provide a seealso in the package man page to direct to another help page with runnable code or where to get started?

I have added seealso links to the `do_query` function, the vignette, and to the API documentation.

> What data is provided in sysdata.rda that your functions use and should not be exposed to the user? Why is this needed?

This file contains my mock responses from the API for testing purposes. It means that if during build the API is unavailable for some reason then the package tests will still work. They are of no use to the user as they will want to use genuine API responses.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/grlloyd.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metabolomicsWorkbenchR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metabolomicsWorkbenchR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
