### ISSUE TITLE
BP4RNAseq

### ISSUE THREAD

**Issue by sunshanwen** [Bioconductor/Contributions#1581]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sunshanwen/BP4RNAseq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please review Bioconductor contribution instructions. Your repository contains files larger than 5Mb
```
  /inst/extdata/test_read_2.fastq
  /inst/extdata/Trimmed_test_read_2.fastq
```
You will need to further reduce the size of these files, and perhaps also 'clean' the repository to remove large file artifacts.
See https://bioconductor.org/developers/how-to/git/remove-large-data/

**Comment by sunshanwen** [comment]
Dear Bioconductor,

thank  you very much for your comment. We have reduced sizes of
/inst/extdata/test_read_2.fastq and /inst/extdata/Trimmed_test_read_2.fastq.
Both files are now smaller than 5Mb.


Best regards,

Shanwen Sun

**Comment by nturaga** [comment]
# BP4RNAseq review

## DESCRIPTION

ok 

## NAMESPACE

ok

## R

- Use `system2` throughout as it is more robust. Don't use `system`. 

		system2 is a more portable and flexible interface than system. It
		allows redirection of output without needing to invoke a shell on
		Windows, a portable way to set environment variables for the execution
		of command, and finer control over the redirection of stdout and
		stderr. Conversely, system (and shell on Windows) allows the
		invocation of arbitrary command lines.

- Make your functions modular, especially in adapter_trim.R. You'll
  find it easier to debug in the future.
  
- Why is `conda` needed as a system requirement for this package? Does
  the vignette evaluate without all these system requiements
  installed?
  
- There are no unit tests in this package. I highly encourage them
  because so much of the functionality depends on other system
  requirements.
  
- remove commented out code.

- You have hardcoded the urls for the datasets like the one given
  below. It now becomes your responsibility to keep track of these
  urls to make sure they don't fail.

		https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/dataset\

- The `install_depends.sh` function seems like it's installing a bunch
  of system requirements. This should probably be in the inst/extdata
  folder because otherwise it doesn't go with the package.
  
## Vignette

- Good vignette! 

## General build report issues

- Fix the following NOTEs (they seem easy to fix, indentation and line
  wrap in examples)

1.

```
NOTE: Consider multiples of 4 spaces for line indents, 1029
      lines(36%) are not.
```

2. 

```
* checking Rd line widths ... NOTE
Rd file 'align_based_quan.Rd':
  \examples lines wider than 100 characters:
     align_based_quan(pair = "paired", taxa = "Homo sapiens", genome = test_Homo_sapiens.fna, annotation = test_Homo_sapiens.gff, novel_tran ... [TRUNCATED]

Rd file 'align_free_quan.Rd':
  \examples lines wider than 100 characters:
     align_free_quan(pair = "paired", "test_Homo_sapiens.fna", "test_transcript_Homo_sapiens.fna","test_Homo_sapiens.gff")

Rd file 'average.Rd':
  \examples lines wider than 100 characters:
     align_based_gene <- system.file("extdata", "test_gene_alignment_based_quantification.csv", package = "BP4RNAseq")
     align_free_gene <- system.file("extdata", "test_gene_alignment_free_quantification.csv", package = "BP4RNAseq")
     align_based_transcript <- system.file("extdata", "test_transcript_alignment_based_quantification.csv", package = "BP4RNAseq")
     align_free_transcript <- system.file("extdata", "test_transcript_alignment_free_quantification.csv", package = "BP4RNAseq")

Rd file 'down2quan.Rd':
  \examples lines wider than 100 characters:
     down2quan(accession = "SRR11427582", dir = getwd(), 
```

**Comment by sunshanwen** [comment]
Dear Bioconductor/Contributions,

thanks a lot for your comments. We have modified our codes to meet
your requirements as much as possible. Please see our responses to your
specific comments below.

   - Use system2 throughout as it is more robust. Don't use system.* Done.*
   -

*Make your functions modular, especially in adapter_trim.R. You'll find it
   easier to debug in the future.  We have modified the adapter_trim.R and
   devided the whole adapter_trim.R into adapter_trim() and check_dep()
   functions.         *
   - Why is conda needed as a system requirement for this package? Does
   the vignette evaluate without all these system requiements
   installed?  *This is a mistake and conda is removed from the system
   requirement. *
   -

*There are no unit tests in this package. I highly encourage them because
   so much of the functionality depends on other system requirements. We added
   the unit tests for some functions. *
   -
*remove commented out code. Done.   *
   -

*You have hardcoded the urls for the datasets like the one given below. It
   now becomes your responsibility to keep track of these urls to make sure
   they don't fail. Yes, we will make sure that the urls work. *
   -

*The install_depends.sh function seems like it's installing a bunch of
   system requirements. This should probably be in the inst/extdata folder
   because otherwise it doesn't go with the package.  **install_depends.sh
   is not part of the package. Using the command **wget
   https://raw.githubusercontent.com
   <http://raw.githubusercontent.com>/sunshanwen/BP4RNAseq/master/install_depends.sh,
**which
   is illustrated in the package vignette, can always help users to download
   it. Therefore, we decided not to put** install_depends.sh into
   the inst/extdata folder. *
   - Fix the following NOTEs (they seem easy to fix, indentation and line
   wrap in examples).* Done. *

We hope these improvements may meet the Bioconductor's standards.


Best Wishes,

Shanwen Sun

**Comment by nturaga** [comment]
Thanks for addressing the concerns. The package looks good now. 

Consider adding unit tests to check the URLs to see if they pass. This way when the nightly build happens if the URLs fail, you can know instantly and fix them. 

Also, another thing to consider as an improvement is more examples in the exported functions with `/donttest` tag. This will guide users better when they ask what a function does using `?BP4RNAseq::adapter_trim`. Right now, there is a single example to most function.s

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sunshanwen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BP4RNAseq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BP4RNAseq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
