### ISSUE TITLE
Informeasure

### ISSUE THREAD

**Issue by chupan1218** [Bioconductor/Contributions#1584]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/chupan1218/Informeasure

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
This package seems to provide general statistical functionality with reference to the Bioconductor ecosystem. It seems like it is more appropriate for CRAN.

If you do wish to continue with a Bioconductor submission, please use the correct version number (0.99.0) and closely follow other Bioconductor package submission guidelines.

**Comment by chupan1218** [comment]
Hi @mtmorgan,
Thank you for your comments. I do wish to submit Informeasure to Bioconductor. I have modified the  DESCRIPTION file. Hope the updated version can meet the basic requirements of biocondutor. Please check it, thanks.

**Comment by nturaga** [comment]
# Informeasure review

## General

- The package doesn't depend on any Bioconductor package or
  class. 
  
- The package doesn't interoperate with any other existing
  Bioconductor package as well. This is essential.
  
- Like @mtmorgan suggested, have you considered submitting to CRAN?

## DESCRIPTION

ok

## NAMESPACE

ok

## man

ok

## R 

- Please fix the issue reported in the build report where you use
  `1:len` instead of `seq_len`.

```
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        discretization.plugin.R (line 199, column 18)
        information.plugin.R (line 285, column 45)
        information.plugin.R (line 302, column 45)
        information.plugin.R (line 311, column 43)
        information.plugin.R (line 318, column 27)
        information.plugin.R (line 318, column 49)
```

- Use `<-` for assignment rather than `=`. It's the "R" thing to do.

- Use the package matrixStats to calculate rowSums and colSums. It's
  optimized. Do not use `apply` functions for this.

- Fix indentation.

## vignette

- no evidence of interoperability with other Bioconductor packages.

**Comment by chupan1218** [comment]
Hi @nturaga thanks for your comments!
I admit that the current version doesn't interoperate with the existing Bioconductor pacakge, even though I have been thinking about it for a few days, I haven't found a good way.
But I am still interested in submitting Informeasure to Bioconductor, as I have already written a biological paper to sell it. Hope you can consider accepting it, thank you!

I've made changes in R section showed below and bumped the version to 0.99.6:

R

1:length statements replaced with seq_len() 

Used "<-" for assignment rather than "="

It seems that R package matrixStats only applies to matrix, in the case of matrix, the rowSums2 and colSums2 functions from matrixStats are called in current version. While in the case of three-dimensional array, the rowSums and rowSums are suitable for this type of data. As your suggested, the apply functions are replaced by rowSums or rowSums for row/column accumulation purposes.

Fixed some non-standard indentation

**Comment by nturaga** [comment]
Hi @chupan1218 , 

After some internal discussion, unless you can allow some cross-functionality to users who want to interoperate with `SummarizedExperiement`. I do not think this package can go into Bioconductor; without this, CRAN would be a more suitable home for this package. 

@mtmorgan will be in touch with you about this.

Best,

**Comment by mtmorgan** [comment]
@chupan1218 I really think your package will benefit from making it interoperable with SummarizedExperiment. To start working on this, I looked at your vignette and the first few evaluated code lines

```
load(system.file("extdata/tcga.brca.testdata.Rdata", package="Informeasure"))
```
I would make several changes. Most relevant, I would make this data a 'SummarizedExperiment' rather than a data.frame
```
library(SummarizedExperiment)
mRNAexpression <- as.matrix(mRNAexpression)
se = SummarizedExperiment(assay = list(mRNAexpression = mRNAexpression))
```
Already there are hidden benefits -- displaying `se` doesn't just print a lot of numbers to the screen! The next lines of the vignette might be
```
assays(se)[["log2"]] <- log2(assays(se)[["mRNAexpression"]])
```
and we again see a benefit -- there is no opportunity for the row or column names of the original and log2-transformed data to be confused. Subsetting is also straight-forward
```
se["MYC",]
```
etc.

Thus the initial recommendation is that mRNAexpression is actually stored as a SummarizedExperiment, rather than data.frame.

In some ways I think that this level of interoperability -- use of SE in the vignette -- is 'enough', functions like `discretize3D()` really do operate on matrices, etc., and it doesn't make much sense to accept a SummarizedExperiment but at the same time require that the user specify the name of assay to be used.

I'm really just exploring your package; it might also be very worth-while to look at [MultiAssayExperiment][1] as a way to store all three assays in a single representation -- this would make it very easy to, e.g., subset samples across assays.

[1]: https://bioconductor.org/packages/MultiAssayExperiment

**Comment by chupan1218** [comment]
Hi @mtmorgan, 
Sorry for late reply. Thank you for your useful suggestions. I have made it interoperable with SummarizedExperiment in the vignettes. Please check it, thank you!
Best,
chu

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/chupan1218.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Informeasure")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Informeasure

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
