### ISSUE TITLE
SCFA

### ISSUE THREAD

**Issue by duct317** [Bioconductor/Contributions#1591]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/duct317/SCFA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# SCFA review

## DESCRIPTION

- Description needs to be like a paper abstract.Please elaborate the description field.

## NAMESPACE

- ok

## Vignettes

- Elaborate the vignette section a little more.

## man

- Elaborate demand pages for each function in a more detailed
  manner. The current amount of information is not enough.
  
## R

- Please check the guidelines for coding style on the Bioconductor website.

- Use the R style assignment operator "<-" instead of "=".

- Please use the `BiocParallel` package instead of `parallel`. You can
  use the `BiocParallel::bplapply()` instead of using `foreach`. 
  
  
- Why are you using the pipe operation only in two lines of code,
  `%>%`?? What is the purpose of exporting the function when it
  doesn't add any value to the packages?
  
```
  vae %>% compile(optimizer = tf$contrib$opt$AdamWOptimizer(wdecay, 0.001), loss = "mse")
```

- There seems to be a lot of repeated code in the file `SCFA.R`. Avoid
  repetition usgin functions which will make the code clearer and
  easier to debug in the future. Please modularize is your code.

- Use `vapply` and not `sapply`.

- Fix NOTE, WARNING and any ERRORs in your build report.

**Comment by nturaga** [comment]
Hi @duct317 ,

We usually give the package authors/maintainers about 14 days to have responded to the comments we issue on the review (or at least keep us informed that they are looking at it, and it's not totally inactive, basically some correspondence).

Please make sure you try to address these in time, If not we can always close the issue and take a look at it again. There is no problem to reopen the issue when you have more time to address the concerns.

Please check the release schedule we are very close to it. http://bioconductor.org/developers/release-schedule/

**Comment by duct317** [comment]
Hi @nturaga ,

Sorry for the late reply. We are addressing the issues in your review. We will push the new version this week. Thank you very much.

**Comment by duct317** [comment]
Hi @nturaga ,

I uploaded the new version of the software. I tried to address your comments as much as possible. Please let me know if there is any problems with the new version.

**Comment by nturaga** [comment]
Hi, 

1. http://bioconductor.org/developers/how-to/coding-style/ You need to better format your code to make it easy for the reviewer. 

2. The man pages for your functions have "no" details unless someone has already read the vignette or is familiar with your work. Add '@description' section to your roxygen templates, and document your package. I do think your vignette needs to be expanded as well. 

These are comments which were not addressed from my last review.

**Comment by nturaga** [comment]
Since these changes are fairly minor, I'll accept your package. Consider still addressing them.

**Comment by duct317** [comment]
Hi @nturaga 
Thank you for the information. I am currently addressing your last comments. I will add those changes to the next version of the package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/duct317.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SCFA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SCFA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
