### ISSUE TITLE
AlpsNMR

### ISSUE THREAD

**Issue by Hgracia** [Bioconductor/Contributions#1598]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sipss/AlpsNMR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
New packages submitted to Bioconductor should have version format 'x.y.z' and with 'y' equal to 99 on initial submission; an appropriate version for your package would be '2.99.0', with changes during the review process accompanied by version bumps '2.99.1', '2.99.2', ... Please update and post a comment here when ready.

**Comment by Hgracia** [comment]
Package version updated

**Comment by Hgracia** [comment]
@mtmorgan or any other contributor. I didn't realiced that version for new packages in bioconductor have to be 0.99.X and now if i try to change git gives me the following error when i try to make push to upstream master
Error: Illegal version bump from '2.99.1' to '0.99.2'.

How can i solve this? Should i close this submission process and begin a new one?

Thanks

**Comment by mtmorgan** [comment]
Ignore the error about 2.99.z version numbers, and continue with 2.99.1, 2.99.2, 2.99.3, etc. If your package has already been made publicly available with version 2.5.90002 (it has!) then it would be a very bad idea to revert to a smaller version number.

**Comment by Hgracia** [comment]
Thanks for the clarification about the version number, @mtmorgan.

Now the only error is related to that and i see that the thread don't was labeled automaticaly as error.

Should i address the warning to continue?

Thanks

**Comment by mtmorgan** [comment]
I think your package is now ready for review and Lori will do so over the next two weeks. The NOTE about use of vapply() is worth paying attention to.

**Comment by lshep** [comment]
Thank you for your submission here are some initial comments from review: 

**General**

- [ ] We prefer and generally insist on programming in S4 classes   over S3 classes.  Can you explain your choice for using strictly S3classes?   (and for future packages please use S4) 

**Build Report**

- [ ] Please correcting the coding notes about using vapply instead of sapply

**README**

- [ ] Include Bioconductor installation instructions. 


**NAMESPACE**

- [ ] It seems like there are many commonly named functions being  re-exported. This doesn't seem quite right?  (like %>%, cluster, filter,  etc). If you import it from another package, you should list those packages in depends, import, suggest and import appropriately in the NAMESPACE but do not re-export those functions. See more in R/code section

- [ ] This is a very very long list of exports. Are all of these needed exposed to the user? 


**LICENSE.md**

- [ ] The MIT license is distributed with R. You do not need to include it. 

**DESCRIPTION**

- [ ] Please remove `LazyData: TRUE`. This has rarely proved useful and can actually slow installation

**inst**

- [ ] Please include a inst/script directoy that provides a file describing how the data in `inst/extdata` was created along with source information. 


**data/man**

- [ ] The man pages for ALL data files need to be expanded to include source/reference information and what the strucutre of the objects are. Many of your references are not resolving for me. (As example url `hmdb.ca` is not a valid url). 
  

**vignettes**

- [ ] We prefer parallelization to be accomplished through BiocParallel. Bioconductor's parallelization package. Is there a reason you did not utilize this package for interoperability?

- [ ] Please remove the excessive `print` statements 
```
> print(MeOH_plasma_extraction_dir)
[1] "/home/shepherd/R-Libraries/4.0-Bioc3.12/AlpsNMR/dataset-demo"

# print not needed
> MeOH_plasma_extraction_dir
[1] "/home/shepherd/R-Libraries/4.0-Bioc3.12/AlpsNMR/dataset-demo"
```
The same goes for most objects

```
print(exp_subj_id)
#
exp_subj_id
```

- [ ] If I run the code that you have for `plot_interactive`, it creates a
  subdirectory that I assume is needed `lib`. I would be careful about calling
  this lib and writing to a users directory without asking the user to avoid
  polluting or overwriting existing directories/files. I would at least warning
  or ask before writing.  Also when the command is run the following warnings
  occur that should be cleaned up if possible or explain why not possible

```
> plot_interactive(plt, "plot_region.html")
[1] "plot_region.html"
Warning messages:
1: `group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: 'scattergl' objects don't have these attributes: 'hoveron'
Valid attributes include:
'type', 'visible', 'showlegend', 'legendgroup', 'name', 'uid', 'ids', 'customdata', 'meta', 'selectedpoints', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'uirevision', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'hovertext', 'textposition', 'textfont', 'mode', 'line', 'marker', 'connectgaps', 'fill', 'fillcolor', 'selected', 'unselected', 'opacity', 'hovertemplate', 'texttemplate', 'error_x', 'error_y', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'metasrc', 'hoverinfosrc', 'xsrc', 'ysrc', 'textsrc', 'hovertextsrc', 'textpositionsrc', 'hovertemplatesrc', 'texttemplatesrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'
 
3: 'scattergl' objects don't have these attributes: 'hoveron'
Valid attributes include:
'type', 'visible', 'showlegend', 'legendgroup', 'name', 'uid', 'ids', 'customdata', 'meta', 'selectedpoints', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'uirevision', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'hovertext', 'textposition', 'textfont', 'mode', 'line', 'marker', 'connectgaps', 'fill', 'fillcolor', 'selected', 'unselected', 'opacity', 'hovertemplate', 'texttemplate', 'error_x', 'error_y', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'metasrc', 'hoverinfosrc', 'xsrc', 'ysrc', 'textsrc', 'hovertextsrc', 'textpositionsrc', 'hovertemplatesrc', 'texttemplatesrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'
```

- [ ] In section for Normalization.  You can not print the diagnostic values
  without the plot displaying? It would be nice to be able to do `diagnostic`
  like many would type, and not have a plot but just see the
  diagnostic$norm_factor

- [ ] Please add `sessionInfo()` to the end of the vignette. 




**R/man**

- [ ] We would recommend moving dplyr to Depend, since the full set of dplyr
  functionality is needed by the end user. You'll get all the dependencies
  whether dplyr is in depends or imports, the difference being the symbols being
  exposed to the end user. The same could be said for future. 

- [ ] Please clean up scripts to not include commented out code that is not
  going to be included or exported. 

- [ ] The code should be cleaned up and organized.  In general repeating large
  code chunks is not advisable. (This would be an excellent use case of using S4
  classes too, to have a generic and then different extensions for specific
  cases.  Example:
  `to_rDolphin_blood.R` -- all the `files_to_rDolphin_X` functions have
  essentially the same code except for the data objected loaded in the
  environment to create the final object. At the very least you should have one
  function like `files_to_rDolphin` and then have an argument that determines
  which object to load.

- [ ] We typically do not allow data to be hosted on random sites like
  dropbox. The data should be on a dedicated server to ensure
  logevity. Bioconductor offers the ExperimentHub to host large data.  


Please address the above issues or questions.  When ready please kick off a new build and comment here responding or commenting to the above concerns.  
Thank you!

**Comment by lshep** [comment]
This is a reminder the next Bioconductor release is October 28th.  All packages must be accepted by October 21st to be included in that release else it will remain in Bioconductor devel until the next release (normally April).

**Comment by Hgracia** [comment]
Thanks for the reminder.
I am not sure if i am going to have time to accomplish all the issues before that deadline. I think that can be good if i make you an update of the things that i already solved and which ones remains unsolved.

General

- [ ]  We prefer and generally insist on programming in S4 classes over S3 classes. Can you explain your choice for using strictly S3classes? (and for future packages please use S4)

Based on this https://adv-r.hadley.nz/oo-tradeoffs.html,  at the beginning of the project it was decided to use S3 instead of S4 because for prototyping it is easier to use S3 than S4. Refactoring everything would be a lot of work, as an alternative maybe we could create a function to export the main package objects (nmr_dataset_1D, nmr_dataset_peak_table) to SummarizedExperiment type objects. Would this work?

SummarizedExperiment.
https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html


NAMESPACE

- [ ]  It seems like there are many commonly named functions being re-exported. This doesn't seem quite right? (like %>%, cluster, filter, etc). If you import it from another package, you should list those packages in depends, import, suggest and import appropriately in the NAMESPACE but do not re-export those functions. See more in R/code section.

I have to work on this.

- [ ]  This is a very very long list of exports. Are all of these needed exposed to the user?

Seems that yes.


vignettes

- [ ]  We prefer parallelization to be accomplished through BiocParallel. Bioconductor's parallelization package. Is there a reason you did not utilize this package for interoperability?

It is not a particular reason, we used future and doParallel before we decide to submit to bioconductor. I think that i can replace doParallel for BiocParallel, but replace future will be more difficult. Would this work?


- [ ]  In section for Normalization. You can not print the diagnostic values
without the plot displaying? It would be nice to be able to do diagnostic
like many would type, and not have a plot but just see the
diagnostic$norm_factor

Probably yes, this is one of the remain issues.

Also the next issues still pending to solve. 

R/man

- [ ]  We would recommend moving dplyr to Depend, since the full set of dplyr
functionality is needed by the end user. You'll get all the dependencies
whether dplyr is in depends or imports, the difference being the symbols being
exposed to the end user. The same could be said for future.

- [ ]  The code should be cleaned up and organized. In general repeating large
code chunks is not advisable. (This would be an excellent use case of using S4
classes too, to have a generic and then different extensions for specific
cases. Example:
to_rDolphin_blood.R -- all the files_to_rDolphin_X functions have
essentially the same code except for the data objected loaded in the
environment to create the final object. At the very least you should have one
function like files_to_rDolphin and then have an argument that determines
which object to load.

- [ ]  We typically do not allow data to be hosted on random sites like
dropbox. The data should be on a dedicated server to ensure
logevity. Bioconductor offers the ExperimentHub to host large data.


If the mentioned issues about S3 classes and parallelization can be solved in the way explained, it is possible that I had time to solve everything before the 21st, otherwise we will wait for the next release.
Thank you.

**Comment by lshep** [comment]
Thank you for your updates thus far.  Please continue to implement the initial review.  For your follow up questions: 

- [ ] No need to refactor everything but please keep in mind for future submission to Bioconductor that we generally prefer s4 and reusing or interacting with existing Bioconductor classes. Implementing a function to export the main package objects (nmr_dataset_1D, nmr_dataset_peak_table) to SummarizedExperiment type objects would be highly recommended

- [ ] Yes your solution for parallelization would work and be acceptable. We ask because certain packages for parallelization can hinder or not support certain operating systems and we make a strong effort at Bioconductor to make all packages work on all OS systems.

**Comment by Hgracia** [comment]
Thanks for your clarification, Ishep

I think that solved all the initial review issues, less follow ones.

Create a function to export the main package objects (nmr_dataset_1D, nmr_dataset_peak_table) to SummarizedExperiment type objects.

Replace parallel for BiocParallel

Move data to ExperimentHub. To do this, is needed to create annother package follow the instructions in the next url, rigth?
http://bioconductor.riken.jp/packages/3.7/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html

**Comment by lshep** [comment]
Yes that is the correct link for instructions.  I would use the most recent copy of the vignette found [here](http://bioconductor.riken.jp/packages/3.12/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html)

**Comment by Hgracia** [comment]
Error: object metadata is not exported by 'namespace:SummarizedExperiment'
Execution halted

**Comment by Hgracia** [comment]
Hi,
I think that all the only issue that remains is move data to ExperimentHub. 

I don't think that i will be able to do it for tomorrow with everything properly checked. If this issue is mainly for ensure longevity, will it work if we compromise to move the data to ExperimentHub in the proper weeks or months?

Thanks and sorry for updating the package with so little time to the deadline, the import and export to SummarizedExperiment was more difficult that i expected.

**Comment by lshep** [comment]
So our recommendation,  since this function is only referenced in the static pdf vignette (which Bioconductor doesn't encourage to begin with because static vignettes have a tendency to get stale).  We would recommend removing the static vignette and accompanied function.  Then you can add the function and pdf vignette back in when you make the accompanied ExperimentHub data package in the upcoming weeks/months.  (even though the deadline is past we could still add your package up to tomorrow evening to the 3.12 release) 

Else we would wait for the ExperimentHub package to be created and submitted on this issue. And it can be accepted for the 3.13 devel cycle (note: devel packages are still listed, searchable, and accessible in Bioc devel) for official release in spring 2021.

**Comment by Hgracia** [comment]
Thanks for your recommendation @Ishep , i removed the static vignette and accompanied function as you said.

I hope everything is ok now
Regards

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Hgracia.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AlpsNMR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AlpsNMR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
