### ISSUE TITLE
fCCAC

### ISSUE THREAD

**Issue by pmb59** [Bioconductor/Contributions#160]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pmb59/fCCAC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Thanks for your contribution.

DESCRIPTION

- ok

NAMESPACE

- ok

vignettes

- ok, but brief. Is this really all there is to say about this package
  and it's role in the Bioconductor ecosystem?
  
R

- use `seq_along()` or `seq_len()` rather than 1:n and similar in
  `for` loops.
- scrutinize all code for opportunities to 'vectorize' rather than
  iterate, for instance fccac.R:69 `grep()` acts on a character vector
  `x` not just scalar; consider also using `grepl()` if a logical is
  the desired output.
- avoid 'copy-and-append' where a zero-length vector is allocated and
  then appended, as in fccac.R:66. Instead pre-allocate a vector of
  desired length and update individual elements, or better use
  `lapply()` to manage memory. In this particular case, I believe
  
        if(length(tf)==1){
            tf_co<-c()
            for (j in 1:ncol(co)){
                if ( length( grep(pattern=tf, x=co[,j]) ) >0  ) 
                  tf_co <- c(tf_co, j)
            }
            co <- co[,tf_co]
        }
        
  is just (untested!)
  
       idx <- unique(col(co)[grepl(tf, co)])
       co <- co[, idx] 
       
  There are many other examples of copy-and-append that need to be
  cleaned up.
- Please indent your code in a standard way, e.g., the `if` statement
  at fccac.R:162 is not indented and makes the code difficult to
  parse. The [formatR][1] package might be useful.
  
[1]: https://cran.r-project.org/package=formatR

**Comment by pmb59** [comment]
Dear Martin,
Thank you for the comments. 

- I have added some lines in the Introduction section of the vignette showing how fCCAC is linked to other packages in the Bioconductor ecosystem.

- I have modified the code as suggested. Hope it is fine now.

**Comment by mtmorgan** [comment]
Thank you for your updates; I will mark it as accepted, it will be added to the nightly svn builds and devel branch of Bioconductor. Additional information will be sent in the next several days; your package did not make it in time for Tuesday's release, but will be added to the next devel branch.

**Comment by mtmorgan** [comment]
Actually, there is still time, the  package will be added to the Tuesday release.
