### ISSUE TITLE
idpr

### ISSUE THREAD

**Issue by wmm27** [Bioconductor/Contributions#1600]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wmm27/idpr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
DESCRIPTION

- Since this is a Bioconductor package, it seems like Biostrings is a better, more interoperable, choice than seqinr for biological string processing?

NEWS.md

- is this file up-to-date? If not, and this is not part of your programming discipline, it is better to have no NEWS.

vignettes

- good to see several vignettes

- Indicate, e.g., idpr-vignette.Rmd:123, that the package should be installed with `BiocManager::install("idpr")` or from Github with `BiocManager::install("wmm27/idpr")`.

- It should not be necessary to use `:::` for users to access objects (TP53Sequences) in the package. Make sure symbols mean for users are exported from the package NAMESPACE.

R

- Generally, I think it is better practice to cleanly separate computation and plotting (e.g., via separate functions) rather than conditionally evaluating plotting code. Whether you adopt this suggest is at your discretion.

- Perhaps the data are generally 'small', but the pattern in chargeHydropathyPlot() where an empty data.frame is created and then individual elements updated is usually very expensive -- the entire data.frame is updated each time an element is updated. It is better to, e.g., create a list of results, one element for each row, and then something like `do.call(rbind, rows)`.

- In idprofile.R it should not be necessary to prefix idpr functions with `idpr::`. Also consider adopting and indentation style that allows for more consitent formatting, e.g., indenting by four spaces rather than under an opening parenthesis. The consistent formatting is easier to read.

    ```
    rhPlot <- chargeHydropathyPlot(
        sequence = sequence,
        pH = pH,
        pKaSet = pKaSet,
        proteinName = proteinName
    )
    ```

man

- good

Please update your package in response to the comments above, as well as the issues generated by the build system, and post a brief comment here when it is ready for subsequent review.

**Comment by wmm27** [comment]
Hello,
Thank you for taking the time to look over the package and provide insight. This is the first package submission I have been a part of, so I apologize if I am unfamiliar with this process. 

I have addressed the following issues, per your recommendation: 

- Removal of the NEWS.md file.
- Added installation instructions to all vignettes. 
- Switched to lists instead of an updating data frame for chargeHydropathyPlot()
- Removed unnecessary `idpr::` for functions within idprofile and fixed its indentation alignments. 
- Resolved the errors and warnings from the Bioconductor build system.

I may need additional details on the following issues, if possible:

- We chose to use seqinr because we wanted to support sequences as character strings, vectors of characters, and as .fasta files. seqinr was the most efficient way to allow input as several formats, though this can be changed if necessary. 

- The `idpr:::TP53Sequences` is needed because the sequences are stored as internal data. Removing the triple colon causes the following error – 
`TP53Sequences
Error: object 'TP53Sequences' not found.`
This error occurs because TP53Sequences do not appear in the Namespace as they are not exported. We chose to make the sequences internal because they are not required for the functionality of the package - they are only used as example sequences in vignettes. Therefore, the documentation of these sequences was not truly needed so we kept it as internal. 

- In terms of separating computation and plotting, this is good advice. In the future I will implement this, however, changing this would take a large overhaul of code for this package which we do not wish to do.

Once again, thank you very much for your time and your comments, it is greatly appreciated.

**Comment by mtmorgan** [comment]
Thanks for your updates.

Since `TP53Sequences` is used in the vignette, it is part of the public API of the package and should be exported / documented.

Biostrings supports each representation of sequence data, and is generally more efficient than seqinr. But the important point is to be interoperable with other Bioconductor packages. I strongly encourage you to switch to using Biostrings.

**Comment by wmm27** [comment]
Thanks for your comments. The TP53 sequences have been added to the NAMESPACE and documented. Additionally, the seqinr::read.fasta() function has been replaced with Bioconductor::readAAStringSet.
I believe I have addressed all of the suggestions. Thank you again for your help

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wmm27.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("idpr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/idpr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
