### ISSUE TITLE
proActiv

### ISSUE THREAD

**Issue by jleechung** [Bioconductor/Contributions#1602]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GoekeLab/proActiv

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jleechung** [comment]
Hi @nturaga! I looked at the build report and the errors on the Linux and macOS systems seem to be related to the Gviz package and its dependencies (biovizBase, rtracklayer). Gviz is listed in the imports so I would think that its dependencies would be installed too? Do you know why this might be the case and how I can fix it?

**Comment by lshep** [comment]
This does seem odd. I will kick off a manual build of your package to see if the issue has resolved; It might have caught the package when it was trying to reinstall on the builders.

**Comment by nturaga** [comment]
# proActiv review

## DESCRIPTION

- elaborate `Description`, it should be like a paper abstract.

## NAMESPACE

- ok

## R

- `cat()` or `print()` are used only when displaying an object to the
  user, e.g., in a show method. `message()` communicates diagnostic
  messages (e.g., progress during lengthy computations) during code
  evaluation. 
  
  This is done in multiple points of your code, please change.
  
- What is the purpose of reexports.R ? Why can't these functions be
  used directly when being called where they are used?
  
- This is a well written package in general! Good work.

## vignette

- There are quite a few eval=FALSE code chunks in the vignette. Is
  there any way to make the vignette fully evaluated, or come as close
  to it as possible?
  
## man

- ok

Good package over all!

**Comment by jleechung** [comment]
Hi, @nturaga thanks for the comments!
I've made changes summarized below and bumped the version to 0.99.2:

**DESCRIPTION**
- Elaborated upon

**R**
- print() statements replaced with message()
- reexports.R exports functions from other packages that users might find useful for processing input or downstream analysis. For example, since proActiv returns a SummarizedExperiment object, users can simply load proActiv and have access to accessors such as assays, rowData, and colData from the SummarizedExperiment package, without explicitly loading 
SummarizedExperiment into namespace. I think this is examplified in the vignette, where we need only call library(proActiv), without, say, library(SummarizedExperiment), library(AnnotationDbi)... (this practice was inspired from [dplyr](https://github.com/tidyverse/dplyr/blob/master/R/reexport-tibble.r)) Does this make sense?

**vignette**
- Out of the four chunks with eval=FALSE, three of the chunks are functions already run but demonstrated with different types of inputs, or already demonstrated in other sections (e.g. quickstart). Hope this is fine!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jleechung.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("proActiv")`. The package 'landing page' will be created at

https://bioconductor.org/packages/proActiv

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
