### ISSUE TITLE
msImpute

### ISSUE THREAD

**Issue by soroorh** [Bioconductor/Contributions#1606]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DavisLaboratory/msImpute

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hello @soroorh,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. The 
LICENSE file should be removed since you are using a standard library.

- [ ] REQUIRED: There should be 'SystemRequirements:' defined if users of the 
package need python to run certain functions.

## NAMESPACE

- [ ] REQUIRED: Internal functions should not be exported.

## NEWS

- [ ] REQUIRED: The versioning is incorrect in your NEWS file.

## Data

- [ ] REQUIRED: The raw data should not be accessed from github. We would rather 
have the data be part of the package or as a seperate data package. When the 
data is hosted on github, there is no gaurantee that the data will always be 
accessible to users, that it won't move, etc.

## Vignette

- [ ] REQUIRED: Only the vignette files (.Rnw or .Rmd) and any necessary static 
images should be in this directory. Please remove the .pdf file.

- [ ] REQUIRED: Is there a difference between 'msImpute-vignette.Rmd' and 
'usersguide.Rnw'? If there are multiple vignette files, each should demonstrate 
a unique function of the package.

- [ ] REQUIRED: The processing of the raw data should be included in an 
'inst/scripts/' directory and not in the vignette. The data used in the vignette 
should be the data provided in the package (pxd01477, pxd007959, and pxd010943). 

- [ ] REQUIRED: The vignette must include executable code. Static vignettes are 
not acceptable. Reduce the amount of `eval=FALSE` in the vignette since these 
undermine the benefit of vignettes.

## Man pages

- [ ] REQUIRED: Only exported functions should be documented. For documentation 
of internal functions you can add `@keywords internal` which will remove the 
function from the documentation index. 

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See i
the following for more details:
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Clarify how 1 object is initialized.
        - function (object)
        gromov_wasserstein (gw)

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()`. Found in files:
        - computeStructuralMetrics.R, line 114

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()`. Found in files:
        - computeStructuralMetrics.R, lines 155 and 156
        - KNC.R, line 38
        - KNN.R, line 30
        - selectFeatures.R, lines 80 and 90

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 302 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 246 lines that are not.

Best,
Kayla

**Comment by soroorh** [comment]
Hello @Kayla-Morrell ,

Thank you for your instructions. Please see below.
 
> ## DESCRIPTION
> * [x]  REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. The
>   LICENSE file should be removed since you are using a standard library.
> * [x]  REQUIRED: There should be 'SystemRequirements:' defined if users of the
>   package need python to run certain functions.
> 
> ## NAMESPACE
> * [x]  REQUIRED: Internal functions should not be exported.
> 
> ## NEWS
> * [x]  REQUIRED: The versioning is incorrect in your NEWS file.
> 
> ## Data
> * [x]  REQUIRED: The raw data should not be accessed from github. We would rather
>   have the data be part of the package or as a seperate data package. When the
>   data is hosted on github, there is no gaurantee that the data will always be
>   accessible to users, that it won't move, etc.


The vignette now mentions the name of the public repository where the raw data can be downloaded. This should address your concerns around accessibility of the data. The link to these public repositories are also documented in the data man pages.


> ## Vignette

> * [x]  REQUIRED: Is there a difference between 'msImpute-vignette.Rmd' and
>   'usersguide.Rnw'? If there are multiple vignette files, each should demonstrate
>   a unique function of the package.

Yes, there is. The intention is to accompany the package with a users guide, similar to  the`limma` package which comes with a static, pre-compiled pdf document that is also very comprehensive. The package vignette 'msImpute-vignette.Rmd'
covers most of the functions, and demonstrates that the functions run successfully. The users guide is intended to be more comprehensive and detailed and covers all functions implemented in the package. The idea is to help users with using the tools implemented in the package, and assist them in interpreting the results returned by the functions . We are treating the pdf file as a static image, if you wish. The Rnw file just embeds the pdf into the second vignette file. So, there is one dynamic vignette (.Rmd) and one static users guide which is created when the Rnw file is compiled.


> * [x]  REQUIRED: Only the vignette files (.Rnw or .Rmd) and any necessary static
>   images should be in this directory. Please remove the .pdf file.


I explained the intention of having the pdf file above. This is just a solution to make a users guide available that can be accessed from the landing page, as limma does.


> * [x]  REQUIRED: The processing of the raw data should be included in an
>   'inst/scripts/' directory and not in the vignette. The data used in the vignette
>   should be the data provided in the package (pxd01477, pxd007959, and pxd010943).

The corresponding codes are now removed from the vignette. The users are advised to consult the
users guide for 


> * [x]  REQUIRED: The vignette must include executable code. Static vignettes are
>   not acceptable. Reduce the amount of `eval=FALSE` in the vignette since these
>   undermine the benefit of vignettes.
> 
> ## Man pages
> * [x]  REQUIRED: Only exported functions should be documented. For documentation
>   of internal functions you can add `@keywords internal` which will remove the
>   function from the documentation index.
> 
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them. See i
>   the following for more details:
>   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
> 
> ## R code
> * [x]  REQUIRED: Clarify how 1 object is initialized.
>   - function (object)
>   gromov_wasserstein (gw)
> * [x]  REQUIRED: Avoid `sapply()`; use `vapply()`. Found in files:
>   - computeStructuralMetrics.R, line 114
> * [x]  REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()`. Found in files:
>   - computeStructuralMetrics.R, lines 155 and 156
>   - KNC.R, line 38
>   - KNN.R, line 30
>   - selectFeatures.R, lines 80 and 90
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 302
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 246 lines that are not.
> 
> Best,
> Kayla

**Comment by soroorh** [comment]
Dear @Kayla-Morrell ,

I believe the package should be ready for a re-review.
Many thanks,
Soroor

**Comment by Kayla-Morrell** [comment]
Hello @soroorh - Thank you for making the necessary changes above. However, I don't feel that you addressed the point about the data being available for download from GitHub. As stated in our data guidelines [here](https://bioconductor.org/developers/package-guidelines/#data), the raw data needs to be included in the package itself or should be a separate data package if the files are too large. Please address this issue.

Best,
Kayla

**Comment by soroorh** [comment]
Dear @Kayla-Morrell,

The data that the user would need to run the vignette is all included in the package and can be accesses via data() for the purpose of **demonstration**. I have seen packages where they've made only part of the data available (top few records). This is not the case about msImpute, as we have provided a full representative data.  Would be please revise your decision?
Best,
Soroor

**Comment by soroorh** [comment]
also, @Kayla-Morrell , please note that the data guidelines have been followed:
```
If existing data is not available or applicable, or a new smaller dataset is needed for examples in the package, data can be included either as a separate data package (for larger amounts of data) or within the package (for smaller datasets).
```

This is indeed the case - we just needed a new smaller dataset for package examples and the vignette, which are included in the package. Does this help?

Many thanks,
Soroor

**Comment by soroorh** [comment]
Dear @Kayla-Morrell ,
Can you please point me to the section of the data guidelines that you are referring to, please? the guidelines under *Raw Data and the inst/extdata/ Directory* states that it is *desirable*

> It is often desirable to show a workflow which involves parsing or loading of raw files

My understanding is that there are 4 principal practices for including data (corresponding to the 4 headings under *Including Data*, and data in `data/` is one of them. My apologies, I am confused!

Many thanks,
Soroor

**Comment by soroorh** [comment]
@Kayla-Morrell - can you please help me with clarifying your expectation re: raw data? thanks heaps!

**Comment by mtmorgan** [comment]
@soroorh please take a deep breath; Kayla, like each of us, has many obligations to fulfill, and yours is only one.

From my reading of your issue, it seems like the data() is consistent with our policies.

I personally would discourage your inclusion of the static vignette -- although limma does an excellent job of this, our experience is that static vignettes quickly become 'pictures of code' that fail because the code in the vignette no longer functions as illustrated. Of course you intend to maintain your code, but our experience has really been that best intentions are often not realized. I would encourage you to remove the static vignette from your package; perhaps reference it from your dynamic vignette. I think this would help to address Kayla's concerns, because you make reference, in both vignettes, to data in your github repository, and such data is not appropriate for use in a Bioconductor package.

**Comment by soroorh** [comment]
Thank you @mtmorgan . This is all I needed to understand to address her concerns. I definitely appreciate how busy all reviewer's are, and appreciate their time and assistance.  I tend to receive comments every 14 days for this issue, and was worried I have to wait another 14 days for this clarification. I shall address your concerns now. many thanks

**Comment by soroorh** [comment]
With the BiocStyle recent issues resolved, I am ready for the next steps. The static vignette is removed. I even attempted to enable the 2 chunks with python calls to show that they work. It builds with no issues on macOS. On windows and linux i had python installation issues, which I am really keen to know how it can be resolved. Many thanks!

**Comment by Kayla-Morrell** [comment]
@soroorh - Thank you for making the necessary changes. I would say that as long as the functions being used in the python code are run / tested some where, which that seems to be the case in their man page examples, I would say it is fine to leave these sections as `eval = FALSE`. I will go ahead and accept the package. Thank you for your time and patience with the review process.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/soroorh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("msImpute")`. The package 'landing page' will be created at

https://bioconductor.org/packages/msImpute

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by soroorh** [comment]
Thank you for your helps, Kayla and Martin.
Best,
Soroor
