### ISSUE TITLE
(inactive) CTDPathSim

### ISSUE THREAD

**Issue by mmor0728** [Bioconductor/Contributions#1608]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bozdaglab/CTDPathSim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
All package dependencies but be active on CRAN or Bioconductor.  Please either remove the dependency or request the package be added to CRAN or Bioconductor.

**Comment by lshep** [comment]
Can you please investigate the linux connection error?

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Please see the initial review comments below: 

**General/Bigger Issues**

- [ ] There seems to be a lack of Bioconductor interoperability of class/objects. At minimum the package should make use of the
  SummarizedExperiment object. The function arguments that take for example the Example.Methylation.450K object should be able to also take SummarizedExperiment. This is only one example but should be extended throughout. Second example but do throughout  RnaSeq_fpkm_hgnc_data, anywhere this is used should take a SummarizedExperiment object, and it is preferred to
  show examples utilizing expression data as SummarizedExperiment objects. Please refer to [common classes and
  methods](http://bioconductor.org/developers/how-to/commonMethodsAndClasses/) 
  Your package needs to interact with Bioconductor common classes.

- [ ] You never actually run any of your functions. This is not allowed in Bioconductor. All the functions are commented out in the vignette and in the man pages. All functions need to be run at least once interactively. We prefer the vignette over man pages. Functions are required to run somewhere in the package to prove they can operate correctly. This is also why we strongly encourage unit tests. 

- [ ] You describe what all these data files/data objects are and there are a lot of example data. It is unclear to me whether these are all automatically generated by some instrumentation or if the user is responsible for creating/generating all the proper data files/objects.

**DESCRIPTION**

- [ ] Please remove `lazyData: true`. This rarely proves useful and can greatly slow installation of the package. 

- [ ] I think the license should explicitly state `Creative Commons Attribution-NonCommercial 4.0 International Public License` rather than file LICENSE. 

**LICENSE**

- [ ] The `Creative Commons Attribution-NonCommercial 4.0 International Public License` is distributed with R and doesn't have to be explicityly included. You could reference it directly in the DESCRIPTION file and remove this file completely (optional - you may leave if you wish)

**inst/extdata**

- [ ] extdata is on the larger size. Is all this example data necessary? We generally recommend have larger example data stored in experimenthub so that the package remains lightweight and that others may take advantage of the data. It doesn't seem like all this data is used in the examples or vignettes either; what is not necessary should not be included. 

- [ ] At the very lease we will require a inst/script that describes how each of the data provided in inst/extdata was created. The description can be code, sudo-code, or text but must include source/reference information.

**NEWS**

- [ ] Formated incorrectly. Please see `?news`

**Vignette**

- [ ] We recommend BiocStyle for vignettes

- [ ] Not rendering correctly. The table of contents does not render as links and the headers/sections are not properly sizing/sectioning so it makes it extremely difficult to read. 

- [ ] Remove extra print statements. Example the following is the same with/without the print statement. Remove print. One example below but change through out 
```
> print(Example.Methylation.450K[1:3,1:2])
           TCGA-OU-A5PI-01A-12D-A29J-05 TCGA-OR-A5K8-01A-11D-A29J-05
cg00000029                    0.2497372                    0.4643335
cg00000165                    0.3474640                    0.1158493
cg00000236                    0.9174302                    0.8816447
> Example.Methylation.450K[1:3,1:2]
           TCGA-OU-A5PI-01A-12D-A29J-05 TCGA-OR-A5K8-01A-11D-A29J-05
cg00000029                    0.2497372                    0.4643335
cg00000165                    0.3474640                    0.1158493
cg00000236                    0.9174302                    0.8816447
```

- [ ] When running your vignette data cn section I get the following that should be investigated

```
  > cn<-xlsx::read.xlsx2(file = system.file("extdata", "ref_names.xlsx", package = "CTDPathSim"),header=TRUE,sheetIndex = 1)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.SAXHelper (file:/home/shepherd/R-Libraries/4.0-Bioc3.12/xlsxjars/java/poi-ooxml-3.10.1-20140818.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.SAXHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```


**R code**

- [ ] Remove any commented out code that is not being run
 
- [ ] Do not repeat large sections of code. This should be applied throughout but for example the code in  ProbeTogene27Fun and ProbeTogene450Fun are very much the same with minor differences.  This should be one function with an argument for 27 or 450, and then inside the code have conditionals for the specialized sections.  Again this should be applied throughout, another
  example is GetSampleDM and GetSampleDE. 

- [ ] Do not write or create directories without the users knowledge. Anywhere that writes/creates directories or files should have a function argument for the user to specify where they want the data to be written. The default should use a `tempdir()` or `tempfile()`.

- [ ] Use `message()` instead of `print()` throughout all code

Please address all the above concerns and issues.  When ready please do a version bump to trigger a new build/check of the package and comment back here responding to the points above and that you are ready for a re-review. 
Thank you for your submission.

**Comment by lshep** [comment]
This is a reminder the next Bioconductor release is October 28th. All packages must be accepted by October 21st to be included in that release else it will remain in Bioconductor devel until the next release (normally April).

**Comment by mmor0728** [comment]
Hi @lshep is there a way to reactivate the issue?

**Comment by lshep** [comment]
Yes.  I had not heard from you in over a month and you have not pushed any updates.  We generally expect maintainers to be active in the review process.

**Comment by mmor0728** [comment]
@lshep I am sorry for not communicating better. I have been working on the comments and will update the package soon.

**Comment by lshep** [comment]
No problem. Glad you will continue work on getting the package into Bioconductor.  Cheers!

**Comment by mmor0728** [comment]
@lshep for the interoperability with bioconductor classes, you mention that we should be interoperable with the summarizedExperament object, are there any others that we need specifically?

**Comment by lshep** [comment]
I'd have a look at the [common methods and classes page](http://bioconductor.org/developers/how-to/commonMethodsAndClasses/)   without really looking into your package again, generally rectangular data should be SummarizedExperiments so that seemed the biggest and most obvious, others if you have any genomic position information GenomicRanges,  etc.. The main ones are described on that page.  Cheers

**Comment by mmor0728** [comment]
@Ishep I want to let you know I am still working and should have an update soon.

**Comment by lshep** [comment]
Good to hear!  Thank you.

**Comment by mmor0728** [comment]
@ishep Hi, sorry for the delay. I am still working, will have an update soon and wanted to make sure I am communicating appropriately.

**Comment by lshep** [comment]
Okay. Thank you for the updates.

**Comment by lshep** [comment]
We are closing this issue for now.  When you are ready to continue the process, tag me in a message here to reopen and resume the review.  Cheers,

**Comment by mmor0728** [comment]
Hi @ishep I would be highly obliged if you could provide some guidance for my future projects. In a pipeline package, what is the best way to indicate the reliance of a function on running the functions before it in the pipeline in the man pages?

**Comment by lshep** [comment]
Could you please ask these type questions on the bioc-devel@r-project.org mailing list?  Others that have encountered this could also respond and then the answer is documented for others in the community to reference.  Thank you
