### ISSUE TITLE
SingleRBookWrapper

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1609]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/SingleRBookWrapper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment]
I would also like to know whether we could get some special `CNAME`s with the bioconductor.org domain for the GH Pages deployment, e.g., `singleR.bioconductor.org`. That would make it look nice and official.

**Comment by LTLA** [comment]
I would estimate that this takes about an hour to build on my laptop, hence the timeout.

**Comment by mtmorgan** [comment]
As we work through this new format, can you add a tag to the DESCRIPTION file

```
BiocType: Book
```

@lshep is it feasible to extend the SPB build times for Book (and Workflow) BiocType: to ??? 2 hours? Not sure if the workflows have guidance on this already...

**Comment by lshep** [comment]
@mtmorgan  Yes. The workflows already get an extended time. I'll have to look up what it exactly is.  I'll work on implementing

**Comment by LTLA** [comment]
Looks like the errors aren't my fault here.

I wonder whether we could rename this package to just **SingleRBook**, which would make it easier to find with the new links (similar to how OSCA's link is just http://bioconductor.org/books/devel/OSCA/).

**Comment by mtmorgan** [comment]
#  3 October, 2020

Sorry for my very slow response

- @lshep / @nturaga can we rename this package to SingleRBook in the issue tracker / git.bioconductor.org ?

Of course this is an impressive achievement, congratulations!

Do you think the model for book publication is suffuciently mature that it could be included as a template in [biocthis][] (recently submitted to Bioconductor)? 

Likewise, is there a page to be written for http://bioconductor.org/developers/ and as a pull request on https://github.com/Bioconductor/bioconductor.org, maybe in collaboration with @hpages, on book publishing in Bioconductor?

[biocthis]: https://github.com/lcolladotor/biocthis

DESCRIPTION

- The convention is to list packages used only in vignettes, etc., in the `Suggests:` field

- Is software license appropriate for this type of material, or would one rather go for a creative commons (documentation) license? (I don't know the answer to this)

- `Description:` I think this should really describe the book, rather than the purpose of the package -- an abstract / introduction paragraph.

- During the build process there is a warning

    ```
    * checking for empty or unneeded directories
      NB: this package now depends on R (>= 3.5.0)
      WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SingleRBookWrapper/vignettes/book/SingleR-book.rds'
    ```

  avoid this by adding (as appropriate for this version of Bioconductor) `Depends: R (>= 4.0)`

vignettes

- I suggest updating the Makefile so that it copies or moves the build products to `inst/doc` (or perhaps `inst/doc/book`) so the machinery for browsing vignettes 'just works' and it is easier to adopt existing infrastructure (e.g., the build system @hpages) to displaying the package and it's product.

- does the product of the Comments.Rmd file end up somewhere in the built 'package'? if so, it should probably be written in a moderately more formal way, including pointing to the location of the book on the Bioconductor web site, assuming that the package is accepted.

- Makefile: use quotes `"${R_HOME}/bin/R" -e ...` to protect against spaces in `${R_HOME}`?

- Makefile: a small point but since this forms a model for other books, why past tense target `compiled` rather than, e.g., `compile`?

vignettes/book

- Surprised to see a second DESCRIPTION / README.md file here

- `_bookdown.yml`: not sure what the role of `repo:` is, and whether `LTLA/SingleR-book` is appropriate?

- `_output.yml`: not really familiar with things, but does it make sesne to enable `sharing:` via github, twitter, ...?

- It seems like the published work itself, at a page that I presume will be like https://ltla.github.io/SingleRBook/, should start with the information that one would expect at the front of a book -- title, authors, publication date, copywrite (different from license) -- as well as information relevant to this type of resource, e.g., source version, compilation date, R / Bioconductor versions, cannonical (https://git.bioconductor.org/packages/...) as well as other URLs, etc. It would also be helpful to have a formatted citation, doi (once available), etc

**Comment by LTLA** [comment]
> Do you think the model for book publication is suffuciently mature that it could be included as a template in [biocthis](https://github.com/lcolladotor/biocthis) (recently submitted to Bioconductor)?
>
> Likewise, is there a page to be written for http://bioconductor.org/developers/ and as a pull request on https://github.com/Bioconductor/bioconductor.org, maybe in collaboration with @hpages, on book publishing in Bioconductor?

Possibly, though I don't know how much demand there is for this.

The [Trojan Action](https://github.com/LTLA/TrojanBookBuilder) contains all instructions necessary to create a book package from a directory with Rmarkdown files and a `DESCRIPTION`, so one could imagine generalizing this. 

> DESCRIPTION
> 
> * The convention is to list packages used only in vignettes, etc., in the `Suggests:` field

Done.

> * Is software license appropriate for this type of material, or would one rather go for a creative commons (documentation) license? (I don't know the answer to this)

I replaced it with CC BY.

> * `Description:` I think this should really describe the book, rather than the purpose of the package -- an abstract / introduction paragraph.

Done.

> * During the build process there is a warning
>   ```
>   * checking for empty or unneeded directories
>     NB: this package now depends on R (>= 3.5.0)
>     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SingleRBookWrapper/vignettes/book/SingleR-book.rds'
>   ```
>   
>   
>   avoid this by adding (as appropriate for this version of Bioconductor) `Depends: R (>= 4.0)`

This should hopefully be fixed by purging the `book/` directory of unnecessary files after the build. 

> vignettes
> 
> * I suggest updating the Makefile so that it copies or moves the build products to `inst/doc` (or perhaps `inst/doc/book`) so the machinery for browsing vignettes 'just works' and it is easier to adopt existing infrastructure (e.g., the build system @hpages) to displaying the package and it's product.

Done. In principle, the build system could scrap from `inst/docs` rather than wherever it's looking now (`vignettes/book/docs`?). However, `inst/docs` will also include the compiled stub vignette (see below); so this approach is not entirely clean, though the stub is never referenced from the book HTMLs so it should be fairly harmless.

> * does the product of the Comments.Rmd file end up somewhere in the built 'package'? if so, it should probably be written in a moderately more formal way, including pointing to the location of the book on the Bioconductor web site, assuming that the package is accepted.

Yes. (This is the stub vignette I was referring to.) This file only exists to indicate that `R CMD build` should try to build the vignette contents. If I remove this file, I cannot get the Makefile to run. 

In any case, I stripped it right down. I don't anticipate anyone reading this.

> * Makefile: use quotes `"${R_HOME}/bin/R" -e ...` to protect against spaces in `${R_HOME}`?

Done.

> * Makefile: a small point but since this forms a model for other books, why past tense target `compiled` rather than, e.g., `compile`?

I had been thinking that `compiled` was the dummy target rather than the action.

> vignettes/book
> 
> * Surprised to see a second DESCRIPTION / README.md file here

Removed.

> * `_bookdown.yml`: not sure what the role of `repo:` is, and whether `LTLA/SingleR-book` is appropriate?

Removed. This was inherited from the OSCA repo.

> * `_output.yml`: not really familiar with things, but does it make sesne to enable `sharing:` via github, twitter, ...?

Done, though I don't know what effect those settings have.

> * It seems like the published work itself, at a page that I presume will be like https://ltla.github.io/SingleRBook/, should start with the information that one would expect at the front of a book -- title, authors, publication date, copywrite (different from license) -- as well as information relevant to this type of resource, e.g., source version, compilation date, R / Bioconductor versions, cannonical (https://git.bioconductor.org/packages/...) as well as other URLs, etc. It would also be helpful to have a formatted citation, doi (once available), etc

Waiting on **rebook** to build, but once it does, it will look like:

![Screenshot from 2020-10-04 12-12-12](https://user-images.githubusercontent.com/8166669/95024913-dc5ec400-063a-11eb-86ef-a4e1ec03a263.png)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingleRBookWrapper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingleRBookWrapper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by LTLA** [comment]
Are we going to change the name? Ping me and I'll update the `DESCRIPTION`.

**Comment by nturaga** [comment]
> # 3 October, 2020
> Sorry for my very slow response
> 
> * @lshep / @nturaga can we rename this package to SingleRBook in the issue tracker / git.bioconductor.org ? (NB: the package has been accepted, so it does not need to be renamed in the SPB).
> 
> Of course this is an impressive achievement, congratulations!
> 
> Do you think the model for book publication is suffuciently mature that it could be included as a template in [biocthis](https://github.com/lcolladotor/biocthis) (recently submitted to Bioconductor)?
> 
> Likewise, is there a page to be written for http://bioconductor.org/developers/ and as a pull request on https://github.com/Bioconductor/bioconductor.org, maybe in collaboration with @hpages, on book publishing in Bioconductor?
> 
> DESCRIPTION
> 
> * The convention is to list packages used only in vignettes, etc., in the `Suggests:` field
> * Is software license appropriate for this type of material, or would one rather go for a creative commons (documentation) license? (I don't know the answer to this)
> * `Description:` I think this should really describe the book, rather than the purpose of the package -- an abstract / introduction paragraph.
> * During the build process there is a warning
>   ```
>   * checking for empty or unneeded directories
>     NB: this package now depends on R (>= 3.5.0)
>     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SingleRBookWrapper/vignettes/book/SingleR-book.rds'
>   ```
>   
>   
>   avoid this by adding (as appropriate for this version of Bioconductor) `Depends: R (>= 4.0)`
> 
> vignettes
> 
> * I suggest updating the Makefile so that it copies or moves the build products to `inst/doc` (or perhaps `inst/doc/book`) so the machinery for browsing vignettes 'just works' and it is easier to adopt existing infrastructure (e.g., the build system @hpages) to displaying the package and it's product.
> * does the product of the Comments.Rmd file end up somewhere in the built 'package'? if so, it should probably be written in a moderately more formal way, including pointing to the location of the book on the Bioconductor web site, assuming that the package is accepted.
> * Makefile: use quotes `"${R_HOME}/bin/R" -e ...` to protect against spaces in `${R_HOME}`?
> * Makefile: a small point but since this forms a model for other books, why past tense target `compiled` rather than, e.g., `compile`?
> 
> vignettes/book
> 
> * Surprised to see a second DESCRIPTION / README.md file here
> * `_bookdown.yml`: not sure what the role of `repo:` is, and whether `LTLA/SingleR-book` is appropriate?
> * `_output.yml`: not really familiar with things, but does it make sesne to enable `sharing:` via github, twitter, ...?
> * It seems like the published work itself, at a page that I presume will be like https://ltla.github.io/SingleRBook/, should start with the information that one would expect at the front of a book -- title, authors, publication date, copywrite (different from license) -- as well as information relevant to this type of resource, e.g., source version, compilation date, R / Bioconductor versions, cannonical (https://git.bioconductor.org/packages/...) as well as other URLs, etc. It would also be helpful to have a formatted citation, doi (once available), etc

Hi @mtmorgan, I'll change the name today.

**Comment by nturaga** [comment]
@LTLA @mtmorgan , why isn't there a SingleRBook github repo. The only thing I can find is SingleRBook-base.

**Comment by mtmorgan** [comment]
@nturaga not sure that it matters now that the package is accepted? git.bioconductor.org has packages/SingleRBookWrapper and it needs to be renamed packages/SingleRBook

**Comment by nturaga** [comment]
Hi @mtmorgan and @LTLA,

This is now done. The package is renamed to SingleRBook and should be
available from that name.

The manifest file is also changed.
