### ISSUE TITLE
MOGAMUN

### ISSUE THREAD

**Issue by elvanov** [Bioconductor/Contributions#1610]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/elvanov/MOGAMUN

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
The COPYING file should be called LICENSE

```
“License:” field: should preferably refer to a standard license (see wikipedia) using one of R’s standard
specifications. Be specific about any version that applies (e.g., GPL-2). Core Bioconductor packages are typically
 licensed under Artistic-2.0. To specify a non-standard license, include a file named LICENSE in your package
 (containing the full terms of your license) and use the string “file LICENSE” (without the double quotes) in this
 “License:” field. The package should contain only code that can be redistributed according to the package
 license. Be aware of the licensing agreements for packages you are depending on in your package. Not all
 packages are open source even if they are publicly available
```

**Comment by nturaga** [comment]
Use `BiocParallel` package instead of the `doParallel` functionality to parallelize.

**Comment by sneumann** [comment]
Hi @nturaga and bioc-issue-bot ;-) 
The MOGAMUN Build on Windows i386 errors because of `igraph_glpk_support.h:36:10: fatal error: glpk.h: No such file or directory` when installing the dependency `igraph_1.2.6.tar.gz`. 
What to do now ? Do we just wait for the tokay1 installation to be fixed ? 
Yours, Elva & Steffen

**Comment by nturaga** [comment]
Issue a new build by doing a version bump. I'll review your package in the next 3 days.

**Comment by nturaga** [comment]
# MOGAMUN review

## DESCRIPTION 

- ok

- Why do you import "devtools"?  You do not need to or can
  'install_github' once the package is accepted to Biconductor.
  
- Please be mindful of what packages are in the imports field .

## NAMESPACE

- Needs to be fixed with above point.

## R

- This is not needed, when the code tries to run it'll automatically
  fail.

```
    pkgname <- c("BiocParallel", "igraph", "stringr")
    
    for (p in pkgname) {
        require(p, quietly = TRUE, character.only = TRUE) || 
            stop("Package '", p, "' not found")
    }
```
  
- 'read.csv()' reads data into a data.frame by default. Not sure why
  you have to cast it to a data.frame again. Same with read.table().

```
          GenesWithNS <- 
            data.frame(read.csv(NodesScoresPath, stringsAsFactors = FALSE))
```

- `BiocParallel::bplapply()` takes an argument called BPPARAM where
  you can specify the method of your parallel compute task.
  
- Some of your `apply()` functions can be vectorized. Pay close
  attention to why you need a loop where you need a loop.
  
- Can you explain what this comment means? Are you "using" or just
  taking the code from a different package? Why not just import the
  package?

```
########## -------- FUNCTION FROM R PACKAGE nsga2R -------- ###################
```

## vignette

ok 

## man

ok

**Comment by elvanov** [comment]
Hello @nturaga! 

Thank you very much for reviewing MOGAMUN! I  just committed the corresponding changes. 

I just have a question regarding the BPPARAM argument of BiocParallel::bplapply(). I tried to use it, but it threw an error when I tried to use a function defined inside the function being parallelized, so I ended up removing the argument because it is marked as optional. Is it needed in my case?

Thank you for your comments!

Best,
Elva

**Comment by nturaga** [comment]
The default is `MulticoreParam()` . When you don't assign a BPPARAM you
don't ask for the number of workers your job needs etc.

```
 > p <- bpparam()
!> p
 class: MulticoreParam
   bpisup: FALSE; bpnworkers: 6; bptasks: 0; bpjobname: BPJOB
   bplog: FALSE; bpthreshold: INFO; bpstopOnError: TRUE
   bpRNGseed: ; bptimeout: 2592000; bpprogressbar: FALSE
   bpexportglobals: TRUE
   bplogdir: NA
   bpresultdir: NA
   cluster type: FORK
```

Check the BiocParallel vignette or just try `?BiocParallel::bplapply`

**Comment by elvanov** [comment]
Thank you very much, @nturaga! I just added the use of BPPARAM to my bplapply.

**Comment by nturaga** [comment]
Consider adding a README.md file to your github repo.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/elvanov.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MOGAMUN")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MOGAMUN

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
