### ISSUE TITLE
MethReg: Assessing the regulatory potential of DNA methylation regions or sites on gene transcription

### ISSUE THREAD

**Issue by tiagochst** [Bioconductor/Contributions#1613]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/TransBioInfoLab/MethReg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by tiagochst** [comment]
I fixed the version from 0.1.0 to 0.99.0.

**Comment by mtmorgan** [comment]
The package needs to be available on the 'master' branch. Please ensure that BiocCheck::BiocCheck() passes without error or warning. Please post a comment here when your package satisfies these basic requirements.

**Comment by tiagochst** [comment]
Hi Martin,

I fixed it.

<img width="398" alt="Screen Shot 2020-09-01 at 1 34 40 PM" src="https://user-images.githubusercontent.com/145529/91886844-e9614f80-ec57-11ea-8536-9426310fd9dd.png">

Here is the BiocCheck::BiocCheck().

<img width="937" alt="Screen Shot 2020-09-01 at 1 32 50 PM" src="https://user-images.githubusercontent.com/145529/91886736-c898fa00-ec57-11ea-9e6f-36a3ff2c1176.png">

<img width="1094" alt="Screen Shot 2020-09-01 at 1 32 18 PM" src="https://user-images.githubusercontent.com/145529/91886757-ccc51780-ec57-11ea-90fc-ca36157f670b.png">

**Comment by tiagochst** [comment]
@mtmorgan Please, do I need to do something else ?

**Comment by LiNk-NY** [comment]
Hi Tiago, @tiagochst 

Thank you for your submission to Bioconductor.
Please see the review below.

Best,
Marcel

---

# MethReg #1613

## DESCRIPTION

* Add more details to the `Description:` field.
* Add a `BugReports:` link for issue reporting.

## NAMESPACE

* If possible, shorten function names.
* You may want to import the entirety of `GenomicRanges` e.g.,
`import(GenomicRanges)` rather than using `importFrom`.

## vignettes

* Remove the `GitHub` installation instructions.
* Show how to use `BiocManager` to install the package.
* Remove the repeated `library(MethReg)` call in the vignette.
* Avoid awkward constructions such as `get(data(...))` in a user-facing
vignette. `data` should return the data instead of a character. Perhaps
use `usethis::use_data`.
* Observe the 80 character width limit. It makes text easier to read
and even maintain.
* You don't need to remove the data object from memory with `gc()`.
* Remove any code for `coMethDMR` as it is not in Bioconductor or CRAN.

## R

* It is possible for the user to save a file themselves without the need of the
`file.out` argument in your function. It may be more simple to remove the
argument and include an example in the documentation that shows the user how
to write the data to disk.
* Avoid using `dontrun{}` in examples. This creates stale code whenever there
is an API change.
* If the `dontrun` examples are too computationally intense, I would suggest
using a smaller example dataset.
* The `min.confidence` argument does not match the documentation in
`R/create_triplet_regulon_based.R`
* Use caching such as `BiocFileCache` to avoid re-download of `human_tfs`
resources.
* Update documentation for `dnam` and others to include `SummarizedExperiment`
as an option.
* Avoid downloading files from an Amazon bucket. It is recommended that you
obtain it from the official source or from ExperimentHub so that other
users/developers can make use of the data (`cRegulome.db.gz` in
`R/get_tf_targets_cistrome.R`).
* I think the documented data in `R/MethReg.R` should be named rather than
`NULL`. See `usethis::use_data`.

Minor:

* Reduce repetitive code by combining logical tests, for example,
`if (missing(exp) || is.null(exp))` in `R/cor_region_dnam_target_gene.R`.
* Allow users to turn off the verbosity from `message` function calls in
functions like `get_promoter_avg`.

## tests

* Remove or update any commented code.
* Looks good.

## README.Rmd

* Update installation instructions to use `BiocManager` instead of GitHub.

**Comment by tiagochst** [comment]
@LiNk-NY I made the updates requested.

I decided to remove `get_tf_targets_cistrome.R` since I was using it mainly for analysis in the article and it is not a requirement for the package. I had the function unexported, but I think removing makes more sense.

Those dontrun examples were taking some time to run due to the access of DNA methylation metadata information from the sesame package and there was a 20 min computation time limit from Bioconductor. I reviewed some of the examples and removed some dontrun examples.

For the function names here are some changes:

- `filter_genes_by_quantile_mean_fold_change -> filter_exp_by_quant_mean_FC`
- `filter_regions_by_quantile_difference -> filter_dnam_by_quant_diff`
- `make_se_from_dnam_probes ->make_dnam_se`
- `make_se_from_gene_matrix  -> make_exp_se`

The other requirements were fixed.

**Comment by LiNk-NY** [comment]
Hi Tiago, @tiagochst 

Thanks for making those changes. 
Can you please respond to the review line by line? 

Best,
Marcel

**Comment by tiagochst** [comment]
Thanks for the extensive review. Below are the answers to each point.

DESCRIPTION
----
> - Add more details to the Description: field.

 The description was modified from:

MethReg evaluates, annotated, and prioritizes DNA methylation regions (or sites) with high regulatory potential, which work synergistically with transcription factors to regulate target gene expressions, without any additional ChIP-seq data.

To:

Epigenome-wide association studies (EWAS) detects a large number of DNA methylation differences, often hundreds of differentially methylated regions and thousands of CpGs, that are significantly associated with a disease, many are located in non-coding regions.   Therefore, there is a critical need to better understand the functional impact of  these CpG methylations and to further prioritize the significant changes.  MethReg is an R package for integrative modeling of DNA methylation, target gene expression and transcription factor binding sites data,  to systematically identify and rank functional CpG methylations.  MethReg evaluates, prioritizes and annotates CpG sites with high regulatory potential using matched methylation and gene expression data, along with external TF-target interaction databases based on manually curation,  ChIP-seq experiments or gene regulatory network analysis.

https://github.com/TransBioInfoLab/MethReg/commit/49ac86d14caecb28041ea0e9b8fd68b6c454bd17#diff-35ba4a2677442e210c23a00a5601aba3

> -	Add a BugReports: link for issue reporting.

BugReports was added: https://github.com/TransBioInfoLab/MethReg/issues/

NAMESPACE
----
> If possible, shorten function names.

For the function names here are some changes:

- `filter_genes_by_quantile_mean_fold_change` -> `filter_exp_by_quant_mean_FC`
- `filter_regions_by_quantile_difference` -> `filter_dnam_by_quant_diff`
- `make_se_from_dnam_probes` ->`make_dnam_se`
- `make_se_from_gene_matrix` -> `make_exp_se`

> You may want to import the entirety of GenomicRanges e.g.,
import(GenomicRanges) rather than using importFrom.

I imported GenomicRanges, but there was a warning of masked functions because I was importing dplyr.
So I importedFrom dplyr instead of importing all its functions. 
However, importedFrom GenomicRanges was a easier solution, since 
dplyr functions were extensively used in the package.

vignettes
----

> Remove the GitHub installation instructions.

Removed.

> Show how to use BiocManager to install the package.

`MethReg` is a Bioconductor package and can be installed through `BiocManager::install()`.

```{r, eval = FALSE}
if (!"BiocManager" %in% rownames(installed.packages()))
     install.packages("BiocManager")
BiocManager::install("MethReg", dependencies = TRUE)
```

> Remove the repeated library(MethReg) call in the vignette.

Removed.

> Avoid awkward constructions such as get(data(...)) in a user-facing
vignette. data should return the data instead of a character. Perhaps
use usethis::use_data.

I normally use get(data(...)) when I need the object with another name instead of the 
default. But in this case it was not necessary. 

`object <- get(data(...))` was changed to `data(...)` only.

> Observe the 80 character width limit. It makes text easier to read
and even maintain.

I reduced as much as a could the width of the lines.

> You don't need to remove the data object from memory with gc().

Removed.

> Remove any code for coMethDMR as it is not in Bioconductor or CRAN.
R

All the coMethDMR code was removed.

> It is possible for the user to save a file themselves without the need of the
file.out argument in your function. It may be more simple to remove the
argument and include an example in the documentation that shows the user how
to write the data to disk.

This option was removed https://github.com/TransBioInfoLab/MethReg/blob/master/R/cor_region_dnam_target_gene.R#L51-L58

> Avoid using dontrun{} in examples. This creates stale code whenever there
is an API change. If the dontrun examples are too computationally intense, I would suggest
using a smaller example dataset.

Don't run examples were removed for the majority of the functions.

> The min.confidence argument does not match the documentation in
R/create_triplet_regulon_based.R

Thanks for catching this problem. Now the documentations have the same argument description:
https://github.com/TransBioInfoLab/MethReg/blob/master/R/create_triplet_regulon_based.R#L12-L15
https://github.com/TransBioInfoLab/MethReg/blob/master/R/regulons.R#L32-L34

> Use caching such as BiocFileCache to avoid re-download of human_tfs
resources.

BiocFileCache was used for caching: https://github.com/TransBioInfoLab/MethReg/blob/master/R/get_human_tfs.R#L26-L44

> Update documentation for dnam and others to include SummarizedExperiment
as an option.

Thanks for noticing this problem. I added SummarizedExperiment as an option of input for 
the DNA methylation and gene expression input.

> Avoid downloading files from an Amazon bucket. It is recommended that you
obtain it from the official source or from ExperimentHub so that other
users/developers can make use of the data (cRegulome.db.gz in
R/get_tf_targets_cistrome.R).

This function was removed. https://github.com/TransBioInfoLab/MethReg/commit/a21dc6e5693dc7732de1d98f8c620afd8f1882a2

> I think the documented data in R/MethReg.R should be named rather than
NULL. See usethis::use_data.

All datasets were named rathen than NULL.
https://github.com/TransBioInfoLab/MethReg/blob/master/R/MethReg.R

> Minor:
> Reduce repetitive code by combining logical tests, for example,
> if (missing(exp) || is.null(exp)) in R/cor_region_dnam_target_gene.R.

Thanks for the suggestion. I changed it in some of the functions.

> Allow users to turn off the verbosity from message function calls in
>  functions like get_promoter_avg.

I added the verbose argument to the following functions:
`cor_tf_target_gene`, `get_promoter_avg`,`interaction_model`, `make_dnam_se`, `make_exp_se`

This will silence the messages output from the function.

tests
----

> - Remove or update any commented code.

Commented code was removed

> - Looks good.

Thanks!

README.Rmd
----

> Update installation instructions to use BiocManager instead of GitHub.

The installation instructions were updated to:

> You can install the MethReg from Bioconductor with:
> BiocManager::install("MethReg")

**Comment by LiNk-NY** [comment]
Thanks for the detailed response. I've had a look at the changes and they look good!
Thank you for contributing to Bioconductor. 
Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tiagochst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MethReg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MethReg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
