### ISSUE TITLE
GSgalgoR:  Identification and Study of Prognostic Gene Expression Signatures in Cancer

### ISSUE THREAD

**Issue by harpomaxx** [Bioconductor/Contributions#1616]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/harpomaxx/GSgalgoR/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by harpomaxx** [comment]
Hello
After bumping a push to trigger a new build, the bioc-issue-bot reported an unknown ERROR in merida1 host running macOS.
Error: package or namespace load failed for BiocCheck in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called biocViews
Execution halted
Windows and Linux platform did not report the error. 
Since we don't have access to macOS, we are not sure how to proceed. Could you please point to some information
on how to deal with the ERROR? 
Bests,

Carlos A. Catania (AKA Harpo)

**Comment by mtmorgan** [comment]
Sorry for my slow review.

DESCRIPTION / NAMESPACE / NEWS

- Is the NEWS file parsed correctly by `utils::news()`?

vignettes

- extensive vignettes, good!

- please update the installation instructions to use
  `BiocManager::install()` as on package landing pages; you may also
  include github installation instructions if desired.

- consider using `message = FALSE` in code chunks (e.g., with
  `library()` calls) where the output is unlikely to be informative.

- Consder saving data under inst/data using `saveRDS()` so that one
  can simply, e.g., `test <- readRDS(...)`

- Is there a reason why functions defined in the vignette, e.g.,
  `DropDuplicates()`, are not instead defined in the package, so that
  the user does not need to copy and paste them from the vignette?

- It looks like you are using `Biobase::ExpressionSet` to represent
  the data, but most modern packages use `SummarizedExperiment`

R (comments apply generally, not just to the specific lines mentioned)

- callback-functions.R:94 consider providing `userdir = tempdir()` as
  the argument to this function, so that the argument default is
  self-explanatory to the user.

- callback-functions.R:108 use `file.path()` for file path
  construction; e.g., this avoids the need to paste `"/"`on to
  `tempdir()`.

- cluster-classifier.R:37 if the size of `R` is large, consider using
  `matrixStats::rowMaxs()` instead of `apply()`.

- cluster-classifier.R:163 'hoist' common subexpressions outside
  loops. For instance, evalaute `unlist(class)` once rather than c
  times.

- convert-functions.R:61 _always_ use accessor functions rather than
  direct slot access. If not intended for end-users, define the
  accessors using a convention to indicate that they are not exported,
  e.g., `.Solutions <- function(x) x@Solutions`.

- convert-functions.R:59 Avoid 'copy and append' patterns of list
  creation, where a zero-length list is extended in a `for`
  loop. Instead pre-allocate the result `OUTPUT = vector("list",
  nrow(.Solutions(output)))` or better leave list allocation to _R_
  using `OUTPUT <- lapply(.Solutions(output), function(x) ...)`. Note
  also that this pattern reduces the number of calls to `@` (once,
  instead of nrow(.Solutions(output))) and hence is more efficient.

- distance-functions.R:87 adopt standard indenting

- distance-functions.R:104 generally, `message(paste("foo", x, "bar"))` is
  redundant; use `message("foo ", x, " bar")`

- galgo.R:84 this version of 'copy and append' (`x <- c(x, x1)`) in
  particular is very inefficient.

- galgo.R:663 use `on.exit(parallel::stopCluster(cluster))` to ensure
  that the cluster is stopped even if an error occurs before the end
  of the function.

man

- good

**Comment by mtmorgan** [comment]
Please drop a brief comment here indicating that you are working on a revision. @harpomaxx

**Comment by harpomaxx** [comment]
Sorry. Sure. We are working on a revision of the package. We have already fixed most of the fundamental issues. We expect submitting the revised version  anytime soon.

**Comment by harpomaxx** [comment]
>Thanks for the deep revision of our package. We have tried to follow  all your recommendations  and suggestions



Is the NEWS file parsed correctly by `utils::news()`?

**A:** *We have verified using utils:news() and the file was parsed correctly*

### vignettes

* please update the installation instructions to use `BiocManager::install()` as on 
package landing pages; you may also include github installation instructions if desired.

**A:** *We added the information for installing the package using `BiocManager` and 
included as an alternative the  installation via `devtools`*

* consider using` message = FALSE `in code chunks (e.g., with library() calls) where 
the output is unlikely to be informative.

**A:** _We included `message = FALSE`  when loading libraries in the vignettes. 
We didn’t find any other cases in both vignettes. Unless you recommend the removal of `galgo()` output.?_

* Consider saving data under inst/data using `saveRDS()` so that one
can simply, e.g., `test <- readRDS(...)`

**A:** _We considered using readRDS as an option. However, the large size of 
the saved object was outside the accepted size for bioc packages. Reducing the 
object size was not possible for a useful example in the vignettes_

* Is there a reason why functions defined in the vignette, e.g.,
`DropDuplicates()`, are not instead defined in the package, so that
the user does not need to copy and paste them from the vignette?

**A:** _The DropDuplicates() and expandProbesets() functions were 
intended specifically to the datasets included in the examples. Particularly 
to adapt the TRANSBIG and UPP datasets to perform PAM50 classification
 in the case study. In this regard, the datasets are from packages from
 others and the functions are not general and are not needed for galgo to work._

* It looks like you are using `Biobase::ExpressionSet `to represent
the data, but most modern packages use `SummarizedExperiment`

**A:** _For the Vignettes we used two datasets included in the 
Bioconductor packages `breastCancerUPP` and `breastCancerTRANSBIG`. These packages are
 from other researchers and use the `Biobase::ExpressionSet `structure. Galgo does 
not require this structure and both `ExpressionSet` and 
`SummarizedExperiment` data can be adapted to be used in our package._
 
### R (comments apply generally, not just to the specific lines mentioned)

* `callback-functions.R:94` consider providing `userdir = tempdir()` as
the argument to this function, so that the argument default is
self-explanatory to the user.

**A:** _all functions now have` tempdir()` as default value for `usedir`. 
Also the body of the function was modified accordingly._ 

* `callback-functions.R:108` use` file.path()` for file path
construction; e.g., this avoids the need to paste "/" on to
`tempdir()`.

**A:**  _Thanks for the suggestion. The `file.path()` function was used 
and pasting “/” was not required anymore_ 

* `cluster-classifier.R:37` if the size of R is large, consider using
`matrixStats::rowMaxs() `instead of` apply()`.

**A:**  _Interesting suggestion. We were not aware of this function, 
nevertheless, we did a benchmark of both options within the range of 
reasonable sizes of datasets expected and the differences in 
performance are negligible. Also, the function mentioned returns the 
max value of the row, while we need the position of the max value of the 
row, which is also an inconvenience for using the suggested function._ 

* `cluster-classifier.R:163` 'hoist' common subexpressions outside
loops. For instance, evaluate` unlist(class) `once rather than c
times.

**A:** _We did our best for finding and removing all the subexpressions outside loops._ 

* `convert-functions.R:61 `always use accessor functions rather than
direct slot access. If not intended for end-users, define the
accessors using a convention to indicate that they are not exported,
e.g., .`Solutions <- function(x) x@Solutions.`

**A:**  _We wanted the end-users to have access to `galgo.Obj` slots.  
Therefore, we implemented generics methods for both slots `ParetoFront` and `Solutions`._

* `convert-functions.R:59 `Avoid 'copy and append' patterns of list
creation, where a zero-length list is extended in a for
loop. Instead pre-allocate the result` OUTPUT = vector("list", nrow(.Solutions(output)))` or better leave list allocation to R
using `OUTPUT <- lapply(.Solutions(output), function(x) ...)`. Note
also that this pattern reduces the number of calls to @ (once,
instead of `nrow(.Solutions(output)))` and hence is more efficient.

**A:** _We have pre-allocated all lists in convert-functions.R  and 
as well as in other source files such as `cluster-classifier.R `and `results-functions.R`_

* `distance-functions.R:87` adopt standard indenting

**A:** _We have fixed all the lines with incorrect indentation._

* `distance-functions.R:104 ` generally, `message(paste("foo", x, "bar")) `is
redundant; use `message("foo ", x, " bar")`

**A:** _Thanks for the suggestion. We weren’t aware of the behavior of` message().`  
The invocation to `paste() `was removed in all calls to `message()`_

* `galgo.R:84` this version of 'copy and append'` (x <- c(x, x1))` in
particular is very inefficient.

**A:** _We have fixed the antipattern for adding elements to a vector pre allocating 
the memory.  The modification was made not only in the section you mentioned above 
but also in other sections of the packages._

* `galgo.R:663` use _on.exit(parallel::stopCluster(cluster))_ to ensure
that the cluster is stopped even if an error occurs before the end
of the function.

**A:** _We added the use of `on.exit() `to ensure the cluster stopped. 
However, it seems that the return value of `galgo()` is lost and as a consequence, 
all tests fail. We were able to solve the problem by using return at the end
 of` galgo() `instead of using the returning value of the last expression._

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/harpomaxx.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GSgalgoR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GSgalgoR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
