### ISSUE TITLE
pageRank

### ISSUE THREAD

**Issue by hd2326** [Bioconductor/Contributions#1619]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hd2326/pageRank

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hd2326** [comment]
Dear @Kayla-Morrell 

Please let me know if there's anything else I need to do in terms of my package.

Best,
Ding

**Comment by Kayla-Morrell** [comment]
@hd2326 - I will have an initial review of the package posted within the next few days. Thank you for your patience.

Best,
Kayla

**Comment by hd2326** [comment]
@Kayla-Morrell Thanks for the response Kayla! Please take your time!

**Comment by Kayla-Morrell** [comment]
@hd2326 - 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## NEWS 

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be 
included in the Bioconductor release announcements.

## Vignette

- [ ] REQUIRED: The Citation subsection is empty. Since you have References as 
the last section of the vignette I would consider removing the Citation
subsection.

- [ ] SUGGESTION: There are many `library()` calls in the vignette. Once a 
library is loaded you don't have to keep loading it in each code chunk. I would 
suggest removing the repetitive calls.

- [ ] SUGGESTION: Under section 3.1 Generating GRNs from Multi-Omics Profiles, 
I would consider printing just the head of `aracne_network(regulon[1:10])` so 
that way there isn't 80 pages of output from this codei (line 185).

- [ ] REQUIRED: Use accessor functions, don't access S4 class slots via `@`. 
Found at line 213 and 246.

- [ ] REQUIRED: There should be a final 'Session Information' section that 
includes `sesssionInfo()`.

## Man pages

- [ ] REQUIRED: Use accessor functions, don't access S4 class slots via `@`. 
Found in the examples in man/accessibility_network.Rd and 
man/conformation_network.Rd.

- [ ] SUGGESTION: Only exported functions and classes need to be documented/have 
man pages. You might consider adding `@keywords internal` to the roxygen 
documentation for the functions that aren't getting exported. This will remove 
the function from the documentation index.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests, we strongly encourage them. See 
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 150 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 174 lines that are not.

Best,
Kayla

**Comment by hd2326** [comment]
Dear @Kayla-Morrell 

Thank you very much for your help in the review process!

I revised the package according to your comments, and the revision passed the build check.

However, with all respect, I didn't use the unit tests in the package. The reason is the results of demos are usually big data.frames or vectors,  rather the single number as the divideBy function in the unit tests guidelines, thus might not be that suitable for, e.g. expect_equal function in unit tests.

Please let me know if there's anything else I need to do in terms of my package.

Best,
Ding

**Comment by Kayla-Morrell** [comment]
Hello @hd2326 - 

Thank you for making the necessary changes. I have just one thing that needs to be changed and then I'll be able to accept the package.

## NEWS

- [ ] REQUIRED: Thank you for adding the NEWS file, however it isn't formatted properly. Take a look at our documentation [here](https://bioconductor.org/developers/package-guidelines/#news) for help with NEWS files.

Best,
Kayla

**Comment by hd2326** [comment]
Dear @Kayla-Morrell 

I fixed the NEWS file as per required by you. Thank you very much for your help on the package!

Just want to know the package would be officially available on Bioconductor on the next release (Oct 5), right? Planning to submit a paper, which includes the package, so just want to confirm with you.

Best,
Ding

**Comment by Kayla-Morrell** [comment]
@hd2326 - The NEWS file looks good, thanks for making that change. I'm more than happy to accept the package now. Our deadline for new packages to be accepted in time for the release is Oct 21, but it should officially be available within the next few days.

Best,
Kayla

**Comment by hd2326** [comment]
@Kayla-Morrell Thank you very much Kayla! I really appreciate your help on the review process!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hd2326.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pageRank")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pageRank

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
