### ISSUE TITLE
CellaRepertorium: data structures and statistical analysis for SC immune repertoires

### ISSUE THREAD

**Issue by amcdavid** [Bioconductor/Contributions#1622]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/amcdavid/CellaRepertorium

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by amcdavid** [comment]
Well that seemed to clean things up, aside from a mysterious error in the [Mac binary build](http://bioconductor.org/spb_reports/CellaRepertorium_buildreport_20200908175926.html#merida1_buildbin_anchor)

> >>>>>>> 
> >>>>>>> FIXING LINKS FOR libdir/CellaRepertorium/libs//CellaRepertorium.so
> >>>>>>> 
> 
> install_name_tool -change "/usr/local/lib/libgcc_s.1.dylib" "/Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libgcc_s.1.dylib" "libdir/CellaRepertorium/libs//CellaRepertorium.so"
> ERROR: R installation problem: File /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libgfortran.3.dylib not found!

I don't have any fortran code.  I can build and install fine on my Mojave Mac, so I'm at a loss about how to reproduce or debug this issue.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see initial review below: 

**build report**

- [ ] Please consider fixing the NOTE about objects/function binding

- [ ] Please justify not having runnable examples in the man pages identified in the build report

- [ ] We highly recommend having a NEWS file to keep track of updates/changes.  It will be included in future release announcements of Bioconductor.  An example release announcement can be found [here](http://bioconductor.org/news/bioc_3_11_release/). See `?news` or  [news](http://bioconductor.org/developers/package-guidelines/#news)
  

**branch**

- [ ] We like only necessary files in the Bioconductor versions of packages.  Could you seperate out the pkgdown files, docs directory,   extra README to a different branch rather than the master branch. same for inst/examples this doesn't seem necessary for package function
  

**README**

- [ ] Should only be one
- [ ] Add Bioconductor installation instructions

**DESCRIPTION**

- [ ] Please remove `LazyData: true`. We have rarely found this useful and can actually slow installation of packages.

**inst**

- [ ] What and how is the WORDLIST in inst utilized within the package?

- [ ] Have an `inst/script` that describes how the data in `inst/extdata` was created. It can be code, sudo-code, or text but should include reference/source information.

**docs**

- [ ] Seems necessary for pkgdown. pkgdown necessary files should be a separate branch than the master branch and not included in the git branch that Bioconductor clones. 

**data-raw**

- [ ] Package data should be in data or inst/extdata.  What is this and how is it utilized?  I think this belongs in an inst/script directory instead?

**data / man **

- [ ] Can you expand on the description and source information for ccdb_ex

**vignette**

- [ ] I recommend having at least one vignette that gives an overview of the package or the other vignettes.  It is more intuitive for a naive user to do `vignette("CellaRepertorium")` to look for help or guidance. 

- [ ] Include `sessionInfo()` at the end of each vignette. 

_cdr3\_clustering_

- [ ] It might be helpful to explain why you are filtering, mutating, etc the  data in each step. 

- [ ] Remove internal comments

```
# This maybe should be a turned into a function 
# Other plots should be considered:
```

For what its worth, anything that can be turned into a function to make the end users experience easier/quicker is recommended.

- [ ] Proceed with making the functions for the complex plots. 


_mouse\_tcell\_qc_

- [ ] For setting up all_anno, do all the col_types have to be specified? This  seems like a lot of set up arguments.

- [ ] Fix this
```
#> Warning: `cols` is now required when using unnest().
#> Please use `cols = c(anno)`
```

- [ ] If this is meant as an exploratory or come back to maybe remove from  vignette
```
  Is there a way to evaluate a sensitivity/specificity in distinguishing cells from debris, or T cells from other cell types?
```

- [ ] Section 6 should not be visible to users. This seems like internal come  back to questions/considerations. 

_reperoire\_and\_expression_

- [ ] Will the barcodes be in the same location each time?  Shouldn't there be  an accessor method to retrieve useful data like this rather than the cumbersome manual subsetting. 

- [ ] This warning generated seems fixable?
```
#> Warning: `cols` is now required when using unnest().
#> Please use `cols = c(extrabc)`
```

- [ ] Why do you need the "extra" barcodes generated?

- [ ] Seems like all the plots are empty? Please correct. This occurs when running interactive as well. 


Please address the above issues/concerns.  When ready be sure to bump the version to trigger a new build and comment back here on the updates.   Cheers

**Comment by amcdavid** [comment]
Hi Lori,

Thanks for the detailed review.  I have responded line-by-line (or just made the change if self-explanatory) below.  Note that I have not yet tackled the vignette improvements or the comments about the Check NOTES/examples but agree with your comments -- I just didn't want to lose my progress so far if my browser crashes!  I will edit this inline as I make the remaining changes and @ you when done.

> Thank you for your submission to Bioconductor. Please see initial review below:
> 
> **build report**
> 
> * [ ]  Please consider fixing the NOTE about objects/function binding
> * [ ]  Please justify not having runnable examples in the man pages identified in the build report
> * [x]  We highly recommend having a NEWS file to keep track of updates/changes.  It will be included in future release announcements of Bioconductor.  An example release announcement can be found [here](http://bioconductor.org/news/bioc_3_11_release/). See `?news` or  [news](http://bioconductor.org/developers/package-guidelines/#news)
> 
> **branch**
> 
> * [ x]  We like only necessary files in the Bioconductor versions of packages.  Could you seperate out the pkgdown files, docs directory,   extra README to a different branch rather than the master branch. same for inst/examples this doesn't seem necessary for package function
RE: `inst/examples` factors out repeated code for an example used across multiple manual pages. The code in that directory is pulled in via the roxygen2 @example tag.  I added a comment to it to make it clear to others its function, but I guess it could live under man/ and/or be added to .Rbuildignore if that's a problem to have it built in the package tarball.

> 
> **README**
> 
> * [ x]  Should only be one
> * [ x]  Add Bioconductor installation instructions
> 
> **DESCRIPTION**
> 
> * [x ]  Please remove `LazyData: true`. We have rarely found this useful and can actually slow installation of packages
> 
> **inst**
> 
> * [ x]  What and how is the WORDLIST in inst utilized within the package?
This is used for spell checking with `devtools::spell_check()`, would argue it's part of the build-chain of the package, have added it to .Rbuildignore though.
> * [ x]  Have an `inst/script` that describes how the data in `inst/extdata` was created. It can be code, sudo-code, or text but should include reference/source information.
This info was in `data-raw`, have moved to `inst/script` and removed `data-raw` 

> 
> **docs**
> 
> * [x]  Seems necessary for pkgdown. pkgdown necessary files should be a separate branch than the master branch and not included in the git branch that Bioconductor clones.
> 
> **data-raw**
> 
> * [x]  Package data should be in data or inst/extdata.  What is this and how is it utilized?  I think this belongs in an inst/script directory instead?

Ok, moved.  FWIW, this is Hadley Wickham's convention and there's some nice tooling that supports it in devtools.
> 
> **data / man **
> 
> * [x]  Can you expand on the description and source information for ccdb_ex
This is just a pre-constructed form of `contigs_qc` as described in the format.  Have added a crossref to `data(contigs_qc)`

> 
> **vignette**
> 
> * [ ]  I recommend having at least one vignette that gives an overview of the package or the other vignettes.  It is more intuitive for a naive user to do `vignette("CellaRepertorium")` to look for help or guidance.
> * [ ]  Include `sessionInfo()` at the end of each vignette.
> 
> _cdr3_clustering_
> 
> * [ ]  It might be helpful to explain why you are filtering, mutating, etc the  data in each step.
> * [ ]  Remove internal comments
> 
> ```
> # This maybe should be a turned into a function 
> # Other plots should be considered:
> ```
> 
> For what its worth, anything that can be turned into a function to make the end users experience easier/quicker is recommended.
> 
> * [ ]  Proceed with making the functions for the complex plots.
> 
> _mouse_tcell_qc_
> 
> * [ ]  For setting up all_anno, do all the col_types have to be specified? This  seems like a lot of set up arguments.
> * [ ]  Fix this
> 
> ```
> #> Warning: `cols` is now required when using unnest().
> #> Please use `cols = c(anno)`
> ```
> 
> * [ ]  If this is meant as an exploratory or come back to maybe remove from  vignette
> 
> ```
>   Is there a way to evaluate a sensitivity/specificity in distinguishing cells from debris, or T cells from other cell types?
> ```
> 
> * [ ]  Section 6 should not be visible to users. This seems like internal come  back to questions/considerations.
> 
> _reperoire_and_expression_
> 
> * [ ]  Will the barcodes be in the same location each time?  Shouldn't there be  an accessor method to retrieve useful data like this rather than the cumbersome manual subsetting.
> * [ ]  This warning generated seems fixable?
> 
> ```
> #> Warning: `cols` is now required when using unnest().
> #> Please use `cols = c(extrabc)`
> ```
> 
> * [ ]  Why do you need the "extra" barcodes generated?
> * [ ]  Seems like all the plots are empty? Please correct. This occurs when running interactive as well.
> 
> Please address the above issues/concerns. When ready be sure to bump the version to trigger a new build and comment back here on the updates. Cheers

**Comment by lshep** [comment]
Thank you for your progress so far and the progress update for changes.  When the vignette is ready please message and I'll begin a re-review.  Cheers!

**Comment by lshep** [comment]
This is a reminder the next Bioconductor release is October 28th. All packages must be accepted by October 21st to be included in that release else it will remain in Bioconductor devel until the next release (normally April).

**Comment by lshep** [comment]
Do you think the vignette changes will be ready for review before the deadline for this release?

**Comment by amcdavid** [comment]
Yes, they are mostly complete...hopefully have everything committed later this evening

**Comment by amcdavid** [comment]
@lshep just a note that I have addressed (or at least mitigated ;) ) the comments you made.

**Comment by lshep** [comment]
In repertoire_and_expression  vignette the plots are still showing up empty for me.  I think it has to do with transparency given the warnings 
```
#> transparency is not supported on this device: reported only once per page
```
transparency is only available on particular OS.  I think if you add `point_alpha = 1`  it will remedy the issue

**Comment by amcdavid** [comment]
Ok, I disabled alpha.  I guess the ideal fix would be to change the graphics device or output to something that supports transparency on all platforms.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/amcdavid.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CellaRepertorium")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CellaRepertorium

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
