### ISSUE TITLE
scp: Utility functions for manipulating, processing, and analyzing mass spectrometry-based single-cell proteomics data

### ISSUE THREAD

**Issue by cvanderaa** [Bioconductor/Contributions#1628]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/UCLouvain-CBIO/scp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      monts, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by cvanderaa** [comment]
Tagging @lgatto

**Comment by cvanderaa** [comment]
The changes introduced by the push are: 

- Maintainer subscribed to bioc-devel mailing list
- Removed `infIsNA`, the implementation was moved to the `QFeatures` packages

**Comment by LTLA** [comment]
Wow, we have single-cell proteomics? I didn't even know that was a thing. 

Guess I'm getting old. Back in my day, we just did MALDI-TOF/TOF.

**Comment by cvanderaa** [comment]
@nturaga any news ?

**Comment by lshep** [comment]
I'll have a review for you by tomorrow.

**Comment by lshep** [comment]
Thank you for your submission. We apologize for the delay in review.  Please see minor comments below: 


# README

- [ ] Please include the official repo location for stable download and github
  for development

# Description

- [ ] we recommend `LazyData: true` be removed from the DESCRIPTION file.  We
  have rarely found it useful and that it can  actually slow the installation
  process.

# Data / man

- [ ] scp1 can you include source information for the data files in the man
  pages for the data objects. I realize it is also in the vignette but would be
  good to include in the man page as well.

# Vignette

- [ ] PCA plot doesn't appear? See warning and transparency message?


Please address the above issues.  When ready please do a version bump and leave a comment here that you are ready for a re-review. 
Cheers

**Comment by lgatto** [comment]
Thank you very much for the prompt review, Lori.

**Comment by cvanderaa** [comment]
Hi @lshep 
Thanks a lot for your rapidity! I have been struggling with replicating the PCA plot issue, but thanks to @lgatto we could solve the issue. Here is an update of your review.

README
---
- [x] Please include the official repo location for stable download and github
for development

Description
---
- [x] we recommend LazyData: true be removed from the DESCRIPTION file. We
have rarely found it useful and that it can actually slow the installation
process.

Data / man
---
- [x] scp1 can you include source information for the data files in the man
pages for the data objects. I realize it is also in the vignette but would be
good to include in the man page as well.

*I added extra information about data collection in the `Details` section for the 3 datasets: `scp1`, `mqScpData` and `sampleAnnotation`*

Vignette
---
- [x] PCA plot doesn't appear? See warning and transparency message?

*I removed the transparency*

I bumped the version of `scp` to `0.99.3`. Thank you for your time!

**Comment by lshep** [comment]
It does not appear you pushed these changes to bioconductor.  Please update the repository as described [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/)

**Comment by lshep** [comment]
I went ahead and looked at the changes on your gitub.  Please update the stable instructions in the README to Bioconductor repository 
`BiocManager::install('scp')`  not the github repository. 

Everything else looks good.  Please push the git.bioconductor.org repository to kick off the new build with this change.  As long as the build report still looks good I will accept the package.

**Comment by lgatto** [comment]
Sorry about the installation instructions, this slid through the cracks. Fixed now, and I'm pushing to Bioc's git server.

**Comment by lgatto** [comment]
Would it be possible to give me write access to `git@git.bioconductor.org:packages/scp.git` - thanks.

**Comment by lshep** [comment]
@nturaga can you assist with this?

**Comment by nturaga** [comment]
@lgatto you should have access now.

**Comment by lgatto** [comment]
Thank you @nturaga

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cvanderaa.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
