### ISSUE TITLE
sparseDOSSA

### ISSUE THREAD

**Issue by boyuren158** [Bioconductor/Contributions#163]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/biobakery/sparseDOSSA

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by boyuren158** [comment]
Dear all,

I am not sure how I should address the R check error specific to Windows. In the latest report I got the message for checking tests as following:

> sparseDOSSA RUnit Tests - 1 test function, 1 error, 0 failures
>   ERROR in D:/packagebuilder/workers/jobs/163/cb4e0f6/sparseDOSSA.buildbin-libdir/sparseDOSSA/unitTests/test_sparseDOSSA.R: Error while sourcing  D:/packagebuilder/workers/jobs/163/cb4e0f6/sparseDOSSA.buildbin-libdir/sparseDOSSA/unitTests/test_sparseDOSSA.R : Error in file(file, "rt") : cannot open the connection

And this happens for both i386 and x64 version of R.

In my own PC, I cannot replicate this error and the R check runs without errors or warnings.

Best regards,
Boyu

**Comment by mtmorgan** [comment]
Try placing data files in inst/xxx/yyy" and referring to files paths as though the package were installed,`system.file(package="sparseDOSSA", "xxx", "yyy")` rather than using setwd() etc.

**Comment by boyuren158** [comment]
@mtmorgan Thanks Martin! That solves the Windows R check issue.

Best,
Boyu

**Comment by mtmorgan** [comment]
Thank you for your package.

I guess this was written as a stand-alone script and has been
re-purposed as a package. Many of the script paradigms remain, but
should be removed; I have tried to indicate some of these in the
comments below, especially in the 'R' section. 

DESCRIPTION

- Please spellcheck your DESCRIPTION and all man pages, e.g,. provdie -> provide
- Please provide additional detail in the Description: field, more
  like a paper abstract describing the method used and the unique
  features of the package compared to other alternatives. Do not
  hesitate to wrap the Description: field to <80 characters, indent
  continuation lines by 4 spaces.

NAMESPACE

- please address the NOTE in the build report, 

        Consider adding
            importFrom("stats", "binomial", "coef", "glm", "lm", "rbinom", "rnorm",
                "runif", "sd")
            importFrom("utils", "read.table", "write.table")
        to your NAMESPACE file.

vignette

- If authors include installation instructions, we encourage them to
  use the standard `biocLite()` approach rather than suggesting
  alternatives that result in installations that are not consistent
  with Bioconductor versioning and package availability.
- It would be very helpful to indicate how the output of sparseDOSSA
  can be used in further Bioconductor analysis.
  
R

- The #! at the top of `synthetic_datasets_script_bug_bug.R` is not
  appropriate
- Consider using a named character vector and
  `c_str$BugBugAssociation` rather than scalar variables.

        c_str <- c(
            BugBugAssociations = "BugToBugAssociations",
            CorrDomainBugs = "Number of bugs each correlated bug is correlated with:",
            ...)

- `c_str` (and other?)  constants are replicated across files, please
  consolidate these so each symbol is defined once.
- synthetic_datasets_script_bug_bug.R:167 The `print()` statement
  after `return()` is never evaluated; other examples?
- The R/*.R files contain a license (CCA-3.0) different from the
  package license; please harmonize these.
- Explicit calls to library() or require() (e.g.,
  synthetic_datasets_script_options.R:15,
  synthetic_datasets_script.R:16) are not required (and should not be
  used) inside a package.
- synthetic_datasets_script.R It is not appropriate to 'source' files
  into R. Instead, the functions defined in other R files will be
  available to invoke from within the package directly.
- code at the top level of a package, e.g.,
  synthetic_datasets_script.R:511, is evaluated at package
  installation time; it is not serving any useful purpose here.
- functions and R packages are more useful when they return objects to
  R users for subsequent computation. Minimally, return a character
  vector of file names, but if the data is at all reasonable in size
  return (a list or ideally existing domain-specific class) of data
  objects that can be integrated into other work flows.
- use `message()` rather than `print()` to communicate progress or
  other information to users.
- use `seq_len()` or `seq_along()` rather than `1:nrow()` or
  `1:length()` for code that is robust to zero-length sequences.
- carefully scruitinize code for opportunities to replace _iteration_
  (for loops, lapply(), etc) with _vectorization_. For instance, is
  synthetic_datasets_script_bug_bug.R:192 just
  
        log_corr_mat[range_features, domain_features[range_features]] <- 
            log_corr_values[ranges_features]
        ...
- The `copy-and-append` paradigm `l = list(); l[[length(l) + 1]] = 1`
  (eg., for `list_of_bugs` is very inefficient; use
  `pre-allocate-and-fill` `l = vector('list', n); l[[i]] = ...` or
  lapply instead. If only the maximum size is known, pre-allocate,
  fill, and set length `length(l) = ...` when done.
        
man

- Please clearly mark non-exported functions as 'internal', e.g., in
  the description section.

**Comment by boyuren158** [comment]
@mtmorgan Thank you for the feedback. I'll start work on fix these problems.

Best,
Boyu

**Comment by mtmorgan** [comment]
If you'd like me to finish the review, please bump the version to 0.99.1

**Comment by mtmorgan** [comment]
I'd like to either finish the review process or close this issue without accepting the package; please let me know your intentions as soon as possible.

**Comment by boyuren158** [comment]
Hi Martin,

I am actually working on this now. I’d like to push the whole updates later today or early tomorrow. Sorry for keeping you waiting for so long and please let me know if this time frame works for the submission process.

Thank you so much!

Best,
Boyu

**Comment by mtmorgan** [comment]
yep, that's great thank you. Martin

**Comment by boyuren158** [comment]
Hi Martin,

I have encountered a check error specific to Mac platform. I cannot reproduce this error on my own Mac. The error message is here:

> * checking PDF version of manual without hyperrefs or index ... ERROR
> Re-running with no redirection of stdout/stderr.
> Hmm ... looks like a package
> Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
>   pdflatex is not available
> Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
>   pdflatex is not available
> Error in running tools::texi2pdf()
> You may want to clean up by 'rm -rf /tmp/RtmpaaI693/Rd2pdf98827585c636'

I am wondering how I should proceed to find the potential problem in the Rd file. Thank you so much in advance.

Best,
Boyu

**Comment by mtmorgan** [comment]
This looks more like a build system error than a problem with your file. I advise you to ignore it.

**Comment by boyuren158** [comment]
Thanks Martin. I have followed your comments and made changes to the documentation as well as the R code. Please let me know if those changes look fine and if there is anything I still need to improve. I really appreciate your help!

Specifically, here is the list of things I have changed:

**DESCRIPTION**

* Spellchecked all the documentation pages
* Add one paragraph in Description to describe the model and the strength of the package

**NAMESPACE**
* Added the "stat" and "utils" to the NAMESPACE file

**vignette**
* Remove the installation instructions.
* Adding one paragraph to the introduction section to illustrate possible application of sparseDOSSA in Bioconductor analysis

**R**
* Removed the shebang section in all R files. Removed the CCA license as well.
* Created four lists c_str, c_d, c_f, c_i to collect constants. Removed the duplicated constant definitions.
* Fixed the print() after return() bug in all files and replaced print() with message().
* Removed the library()/require()/source() in all R files. Removed the command-line interface from the main sparseDOSSA function as well as the top level code.
* The main function now returns the names of the three files sparseDOSSA generated. 
* Replaced 1:length() etc with seq_len() and seq_along() in all R files.
* Vectorization for loops as much as possible.
* Removed the copy-and-append paradigm for vectors and lists. Now uses pre-allocation with truncation after all items are added. Include an index variable to trace for the number of items.

**man**
* Adding keyword internal for all internal functions. No Rd files are generated now for those functions.

**Comment by mtmorgan** [comment]
These revisions look good and I am marking this package as accepted; you'll receive additional information in the next several days. Thanks for your contribution!

**Comment by boyuren158** [comment]
Thank you for your help Morgan. I’ll keep an eye on the additional information.
