### ISSUE TITLE
metabCombiner

### ISSUE THREAD

**Issue by hhabra** [Bioconductor/Contributions#1633]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hhabra/metabCombiner

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [?] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
Hi @hhabra 

You'll need to fix the errors on the build report before your package can be reviewed. This is essential, also take a look at the notes and the warnings which are produced on the build report.

Issue a version bump and a new build report will be produced. Once the build report is clean I will review your package.

**Comment by hhabra** [comment]
Hi nturaga, it looks like there is one error that is rather trivial to fix (somehow it wasn't caught in my checks). I did have a couple of questions that I haven't been able to get a satisfactory answer to:

1) If I bump the minimal R version to 4.0 (per the warning), does this really mean that this package cannot be used for lower versions? Do I even need to specify a minimum R version? (I think I read somewhere that I don't, but nearly every example package I've seen contains a minimum R in DESCRIPTION)

2) I searched for some way to resolve the NOTE, "Consider clarifying how 5 object(s) are initialized", but could find nothing. Shall I ignore this NOTE?

I have other questions, but I'll start with these and I'd appreciate any help with this.

**Comment by nturaga** [comment]
1. Please review http://bioconductor.org/developers/how-to/useDevel/.

The general package guidelines will help as well,
http://bioconductor.org/developers/package-guidelines/#version

2. Ignore the NOTE for now, try to fix the bigger issues.

**Comment by nturaga** [comment]
# Review

## R CMD build

ok

## R CMD INSTALL

ok

## General

This one is easy to fix in the build report. To produce another build report, just bump the version and push. 

```
    * NOTE: Use donttest{} instead of dontrun{}.
      Found in the following files:
        fit_gam.Rd
        write2file.Rd
```

## DESCRIPTION

ok

## NAMESPACE

ok

## man

ok. The exported functions have good documentation. 

## vignette

ok

## R

- Use `<-` instead `=` for assignment. This is the "R" way of doing things.

- For validity checks, you might want to use `stop()` instead of `warning()`. Especially in this function `filterRT`. 

```
    if(!is.numeric(rtmin) | rtmin > rtmax | rtmin < 0 |
        rtmin > max(rts) | rtmin < min(rts))
    {
        warning("value supplied for 'rtmin' argument is invalid; ",
                "setting 'rtmin' to minimum observed retention time.")
        rtmin = min(rts)
    }

    if(!is.numeric(rtmax) | rtmin > rtmax | rtmax < 0 | rtmax > max(rts))
    {
        warning("value supplied for 'rtmax' argument is invalid; ",
                "setting 'rtmax' to maximum observed retention time.")
        rtmax = max(rts)
    }
```

- Use `matrixStats` for finding out row and col means, medians, max min...etc. The `matrixStats` package is highly optimized. 

- Do not use `@` (slot access) directly. Write accessor functions and use those. This is done in multiple places. Please fix this.

review: http://bioconductor.org/developers/how-to/efficient-code/ 

```
Accessors (simple functions that return components of your object) rather than direct slot access (using @) help to isolate the implementation of your class from its interface. Generally @ should only be used in an accessor, all other code should use the accessor. The accessor does not need to be exported from the class if the user has no need or business accessing parts of your data object. Plain-old-functions (rather than generic + method) are often sufficient for accessors; it’s often useful to employ (consistently) a lightweight name mangling scheme (e.g., starting the accessor method name with a 2 or 3 letter acronym for your package) to avoid name collisions between similarly named functions in other packages.
```

- if you import the functions you need in your package, you don't need to call them by referring to the package each time ie. `dplyr::group_by()` etc (unless there is a conflict).

- what is `return(invisible())` trying to do??

**Comment by hhabra** [comment]
Hi @nturaga,

I have updated metabCombiner to incorporate your suggestions to the best of my ability. Some changes are:

- Assignments within R functions should now all be using <-

- I changed some validity checks to stop (such as filterRT), though some I kept as warnings

-matrixStats functions have been added where relevant, particularly the adjustData function

- I have written an "update_mc" and "update_md" method for metabCombiner and metabData objects, respectively, which I think addresses this concern

-I opted to keep package names in my calls as it personally helps me read and remember where other package functions come from

-I removed return(invisible) calls (2 of them); I might have seen this used in other packages I used as templates, but ultimately they have no use

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hhabra.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metabCombiner")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metabCombiner

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
