### ISSUE TITLE
tomoda

### ISSUE THREAD

**Issue by liuwd15** [Bioconductor/Contributions#1635]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/liuwd15/tomoda

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Wendao Liu, @liuwd15 

Thank you for your submission to Bioconductor. 
Please see the review below. Feel free to post
any questions or comments below. 

Best regards,
Marcel

--- 

# tomoda #1635

## DESCRIPTION

* Briefly describe the tomo-seq technology and possibly even provide a
reference.

## NAMESPACE

* (optional) An unwritten convention is to use capital case function names for
constructor functions for classes (e.g., `SummarizedExperiment()`). Otherwise,
use lower case for 'plain' functions.
* The names of some functions are quite general and can cause confusion for
your users (e.g., `base::scale` vs `Scale` and `stats::kmeans` vs `KMeans`).
Please add a more descriptive name to your functions or consider renaming them.
* The number of exports looks reasonable though I'd be careful with function
names that differ only by case.

## vignettes

* Consider limiting your lines to the 80 column width in the vignette. It makes
it easier for the reviewer to read and potentially for the maintainer to
update.
* Use `r BiocStyle::Biocpkg('tomoda')` when accepted.
* Why not use a `SummarizedExperiment` to represent the example dataset
(`zh.data`)
* Should `Normalize` and `Scale` operations be part of your `CreateTomo`
function?
* Use color-blind friendly default colors for the heatmaps.
* Remove the `.gitignore` file in the vignettes folder (`.R` and `.html` files
do not belong in the directory).

## R

* `CreateTomo` should support both `matrix` and `SummarizedExperiment` inputs.
* You can also have a normalize / scale argument in the `CreateTomo` function.
* Consider renaming `CreateTomo` to something like `checkTomo` as 'Tomo' is not
really a class or subclass of `SummarizedExperiment`.
* Add more details in the documentation to what operations are performed on
the data as part of the `CreateTomo` function.
* Given that `SummarizedExperiment` is the main data representation. The
`GetMatrix` function is repeated code for `assay(se, i = "counts")` and should
be removed. The documentation should inform users to use the `assay` function
to extract a matrix.
* Avoid using `cat` and use `message` instead to notify the user.
* `HClust` and `KMeans` seem to be thin wrappers for `hclust` and `kmeans` and
consider including the convenience functions inside the main `CreateTomo`,
if at all.
* Avoid hardcoding the assay name in `FindPeakGene` (`assays(object)$scaled`).
Allow the user to input the scaled assay name (`scaled`) using an argument.
This applies to other functions that use `assays(object)$scaled` etc.
* Use `assay` rather than `assays` when extracting one
* Use the allocate and fill strategy in `FindPeakGene` `for` loop when
`nperm > 0`.

## README.md

* Update the `BiocManger::install` code chunk

**Comment by liuwd15** [comment]
Hi Marcel @LiNk-NY, 
Thanks for your comments. I have updated the package and here are my responses to your comments. I followed most of your comments but left a few unchanged. The reasons are explained below.

### DESCRIPTION

- Description and reference are added.

### NAMESPACE

- Functions are renamed such that they follow the convention (starts with lower cases) and differ from other functions.

### vignettes

- The vignette is now 80 column-wide.

- Now `r BiocStyle::Biocpkg('tomoda')` is used.

- In my opinion, most users will start with a read count `matrix` rather than a `SummarizedExperiment object`. The example matrix is useful as I show how to create the SummarizedExperiment object from a read count matrix. If the dataset is saved as a SummarizedExperiment object, users may not understand how to prepare their data. Therefore I believe saving the example dataset as matrix is reasonable.

- Normalization and scaling are now added into `createTomo`.

- Color-blind friendly default colors from `RColorBrewer` are used for heatmaps now.

- `.gitignore` in this directory is removed.

### R

- `createTomo` now supports matrix and SummarizedExperiment inputs by using S4 generics and methods.

- Normalization and scaling are now added into `createTomo`.

- Although there is no class named Tomo, I believe that `createTomo` shows the meanings of "creating an object representing tomo-seq data" better than `checkTomo`, so I leave this name unchanged.

- More details in documentation are added.

- `GetMatrix` is replaced with `assay`. Accessing matrices using `assay` is demonstrated in the vignette.

- `cat` and `print` is replaced with `message`.

- `hierarchClust` (old name `HClust`) returns a `hclust` object so it cannot be added into `createTomo`. Besides, I plan to add more clustering algorithms in future versions, so I do not think adding clustering functions in `createTomo` is a good idea.

- Functions using data of certain assays now have the augument `matrix`, which tells the functions which assay to work on. Default values are provided so that users do not always need to specify it. 

- `assays` are replaced with `assay`.

- Allocate and fill strategy is used in `FindPeakGene`.

### README.md
There is `BiocManager::install("tomoda")` in Installation.

**Comment by LiNk-NY** [comment]
Hi Wendao Liu, @liuwd15 

Thank you for making those changes. They look great!
I would consider renaming the `createTomo.matrix` function into something that resembles an S3 method _less_. Perhaps `tomoMatrix`?
I will accept your package. Thank you for your contribution. 

Best regards,
Marcel

**Comment by liuwd15** [comment]
Hi Marcel @LiNk-NY,
Thanks for reviewing and accepting this package.
`createTomo.matrix` and `createTomo.SummarizedExperiment` are renamed into `tomoMatrix` and `tomoSummarizedExperiment` now.

Best,
Wendao

**Comment by LiNk-NY** [comment]
Great!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/liuwd15.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tomoda")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tomoda

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
