### ISSUE TITLE
spatialHeatmap

### ISSUE THREAD

**Issue by jianhaizhang** [Bioconductor/Contributions#1639]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhaizhang/spatialHeatmap

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jianhaizhang** [comment]
Hello lshep,

The error in Linux (Ubuntu 18.04.4 LTS)/x86_64 is caused by the lack of "libavfilter-dev" dependency on the Linux system, since the "av" package builds on it. Can you install "libavfilter-dev"?

Regards,
Jianhai

**Comment by lshep** [comment]
I will check on installing libavfilter-dev on the linux builder.  In the meantime, please fix the ERROR, WARNING, and NOTES in the build report.

**Comment by lshep** [comment]
libavfilter-dev has been installed on the linux server.  Cheers

**Comment by jianhaizhang** [comment]
> libavfilter-dev has been installed on the linux server. Cheers

Hi lshep, 

Thanks a  lot!

Regards,
Jianhai

**Comment by jianhaizhang** [comment]
Hi @lshep,

I got the same issue with this post: https://support.bioconductor.org/p/122219/. Basically, I subscribed to the mailing list and received the confirmation email. But an error is raised because I am not detected in the list. Is there a time period for the 
 list to update? I subscribed less than 24h ago.

Regards,
Jianhai

**Comment by lshep** [comment]
I'll investigate the mailing list issue.  I'll try and have an initial review for you over the next week. Cheers and I look forward to getting your package into Bioconductor.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Overall this package seems well written and well documented.  I have a few minor points below: 

# General

- [ ] Remove 'Read-and-delete-me' .  Files that are not part of a traditional package structure should be removed and placed in a `.gitgnore`

# Description

- [ ] Recommended removing static information that can get stale and easily forgotten to update like Date.

# inst

- [ ] Remove blank CITATION file


# vignettes

- [ ] Need a more informative vignette title rather than vignette.Rmd.  It is too generic and can cause confusion. If more than one package is loaded, there  could also be naming conflicts. For example when I initially tried to load the
  vignette
```
starting httpd help server ... done
Warning message:
vignette 'vignette' found more than once,
using the one found in '/home/shepherd/R-Libraries/4.0-Bioc3.12/mixOmics/doc' 
```
We recommend using the name of the package. spatialHeatmap.Rmd


- [ ] If this is used somewhere in your code please fix, else I understand it can be generated by a dependency out of your control

```
Warning message:
`group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help

```

- [ ] I know the few places you show the `dir.create(~/test/)` are in `eval=FALSE`  but for naive, blindly copying users it would be best to use a `tempdir()` or  at the very least test if the directroy exists (which you do at some point) but if it does exist verify use as an output diretory before writing to it. 


# R / man

- [ ] For good measure should filter_data complete the else and stop if it is  not a data frame or summarizedexperiment.  I think this occurs a few times in other functions as well.  The outward exported functions should complete the  check for arguments in proper format and stop if not.

- [ ] Should there be other parameter checks for valid entries for exported  functions.

- [ ] We generally don't encourage repeating code.  Something like the following  that checks the data format as matrix

```
  if (is(data, 'data.frame')|is(data, 'matrix')|is(data, 'DFrame')) {

    data <- as.data.frame(data); rna <- rownames(data); cna <- make.names(colnames(data))
    if (!identical(cna, colnames(data))) cat('Syntactically valid column names are made! \n')
    na <- vapply(seq_len(ncol(data)), function(i) { tryCatch({ as.numeric(data[, i]) }, warning=function(w) { return(rep(NA, nrow(data)))
    }, error=function(e) { stop("Please make sure input data are numeric!") }) }, FUN.VALUE=numeric(nrow(data)) )
    na <- as.data.frame(na); rownames(na) <- rna
    idx <- colSums(apply(na, 2, is.na))!=0
    row.meta <- data[idx]; expr <- na[!idx]; colnames(expr) <- cna[!idx]

  }
```
Probably should be its own function to reference

```
if (is(data, 'data.frame')|is(data, 'matrix')|is(data, 'DFrame')) {
   convert_data(...)
}
```

Please address the above issues. When ready be sure to do a version bump to trigger a new build report and comment back here addressing the above concerns and requesting a re-review.  Cheers.

**Comment by jianhaizhang** [comment]
Hi @lshep ,

Thanks for your comments. The package was updated based on your feedback. Additional input entry checks were applied on update_feature, and return_feature.

I increased the version number, and the push was valid, but there are no build/check results. Do you know why?

Regards,
Jianhai

**Comment by lshep** [comment]
It looks like the building paused for some reason.  I will kick off a manual build shortly and provide a re-review over the next week or so.  Sorry for the inconvenience

**Comment by lshep** [comment]
Thank you for your updates. The package looks good.

**Comment by jianhaizhang** [comment]
Thank you for the review and the acceptance of the package!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jianhaizhang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spatialHeatmap")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spatialHeatmap

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by jianhaizhang** [comment]
Hi @lshep ,

I am receiving a minor error on the nightly build of Windows over the past days: https://bioconductor.org/checkResults/3.12/bioc-LATEST/spatialHeatmap/tokay1-buildsrc.html, though the last commit (999fd84009f5da69db273e5a53431d9d328ee342) during the review process passed all build/check without errors/warnings.

Now the hardship is the error could not be reproduced on both "Windows Server 2019" and "Windows Server 2012 R2", which were downloaded at https://www.microsoft.com/en-US/evalcenter/evaluate-windows-server-2019?filetype=ISO

Do you have any suggestions? Thank you!

Regards,
Jianhai

**Comment by lshep** [comment]
I currently do not have any suggestions at this time.  I see you started a slack conversation.  I would continue conversation there or switch to bioc-devel to ask build/developer questions.  Herve or I could possibly look further into this on the builders but it may take a few days as we are prepping for the release.
