### ISSUE TITLE
ttgsea

### ISSUE THREAD

**Issue by dongminjung** [Bioconductor/Contributions#1652]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dongminjung/ttgsea

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# Review

## General

- We like to see interopability with standard Bioconductor classes
  http://bioconductor.org/developers/how-to/commonMethodsAndClasses/.
  It seems like this package should make compatible with potentially
  BiocSet, GSEABase and SummarizedExperiment.

- Please investigate TIMEOUT and ERROR.

- Please address the coding style 

- We strongly recommend adding useful, meaningful, unit tests

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION 

- Description field needs to be more elaborate like the abstract of a
  paper.
  
- Add tensorflow as a SystemRequirement, as Keras uses tensorflow.

## README

- We suggest removing static data like Date that may forget to be
  updated

- Please include Bioconductor installation instructions in README

## NAMESPACE 

- Remove `exportPattern("^[^\\.]")`.  Export functions
  explicityly. Use roxygen.

## man

- ok, please elaborate on the man pages too.

## vignette

- ok, please format the vignette to be more in order.

## R 

- Don't use `sapply` use `vapply()`

- Use the correct type of messages, you mean to use `message()`
  instead of `cat()` most of the time. Here is a guide,

```
message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```

- Some of your `apply()` functions are not needed. Most basic
  functions in R are vectorized, especially comparison operations. Pay
  close attention to which ones are needed and which ones are not.

- The `plot_model()` function as written right now is unreadable to
  review. Please fix it based on the Bioconductor coding style.
  
  http://bioconductor.org/developers/how-to/coding-style/

**Comment by dongminjung** [comment]
Hi @nturaga thanks for your comments!
I've modified my code to meet your requirements as much as possible.
I've made changes summarized below and bumped the version to 0.99.3:



**General**

We like to see interopability with standard Bioconductor classes
http://bioconductor.org/developers/how-to/commonMethodsAndClasses/.
It seems like this package should make compatible with potentially
BiocSet, GSEABase and SummarizedExperiment.

- For GSEA, `fgsea` is used, so list of gene set is still necessary. Code for conversion from a gene set defined by BiocSet or GSEABase to a list was commented in vignette.

Please investigate TIMEOUT and ERROR.

- malbec1 only gives OK. merida1 gives TIMEOUT. There seems to be a problem for running TensorFlow or Keras. tokay1 gives ERROR with "Installation of Python not found" message.

Please address the coding style

- I revised my code to follow the Bioconductor coding style as much as possible.

We strongly recommend adding useful, meaningful, unit tests

- I added unit tests.



**DESCRIPTION**

Description field needs to be more elaborate like the abstract of a
paper.

- Done

Add tensorflow as a SystemRequirement, as Keras uses tensorflow.

- Done



**README**

We suggest removing static data like Date that may forget to be
updated

- Done

Please include Bioconductor installation instructions in README

- Done
- Also, I added tutorial



**NAMESPACE**

Remove exportPattern("^[^\\.]"). Export functions
explicityly. Use roxygen.

- Done



**man**

ok, please elaborate on the man pages too.

- I elaborated on the man pages as much as possible.



**vignette**

ok, please format the vignette to be more in order.

- I added a subheading for every paragraph.



**R**

Don't use sapply use vapply()

- Neither sapply() nor vapply() was used. Some of them were replaced by unlist(lapply()).

Use the correct type of messages, you mean to use message()
instead of cat() most of the time. Here is a guide,

- cat() was replaced by message().

Some of your apply() functions are not needed. Most basic
functions in R are vectorized, especially comparison operations. Pay
close attention to which ones are needed and which ones are not.

- Some apply functions are replaced by other functions.
For example,
from `inbound <- inbound[!sapply(inbound, is.null)]` to
`inbound <- Filter(Negate(is.null), inbound)`,
from `n <- apply(x_test, 1, function(x) length(x[x != 0]))` to
`n <- rowSums(x_test != 0)`,
from `temp <- lapply(apply(simulation_matrix, 1, list), function(z) z[[1]][seq_len(x)])` to
`temp <- lapply(seq_len(nrow(simulation_matrix)), function(z) simulation_matrix[z,])`

The plot_model() function as written right now is unreadable to
review. Please fix it based on the Bioconductor coding style.

- I modified my code to follow the Bioconductor coding style as much as possible.


Please let me know if I need to make any further changes.

Thanks,
Dongmin

**Comment by nturaga** [comment]
Can you issue another build report please? I'd like to see if the TIME OUT status shows up again. 

Also, for the error in the windows machine "check", it fails a unit test because a system requirement is missing. Look up https://rdrr.io/cran/remotes/src/tests/testthat/test-system_requirements.R where you can specifically test something if a requirement is present. 

Another resource is, https://github.com/Bioconductor/BiocDockerManager/blob/master/tests/testthat/test-docker_api.R#L1-L25

It checks to see if a system requirement is present and then tests it.

**Comment by dongminjung** [comment]
Hi @nturaga
I updated the file for a unit test. Thanks.

**Comment by lshep** [comment]
A reminder to please investigate the TIMEOUT occurring on the mac platform.

**Comment by dongminjung** [comment]
Hi @lshep
I found that `fit_generator` gives TIMEOUT because of an issue for R keras `fit_generator` with a custom data generator. Currently, I use `fit` instead of `fit_generator` and it works well for training. In linux, there were no errors but it gives an error for a plot of a model. I think different versions of keras and tensorflow are installed on linux.

**Comment by lshep** [comment]
Two more minor comments now that the package builds/checks cleanly before acceptance:

**README**

- [ ] Please include Bioconductor installation instructions

**NEWS**

- [ ] The NEWS file cannot be empty.  Most opt for an initial entry of
  submissiong to Bioconductor

```
Changes in version 1.0.0
------------------------

  - submission to Bioconductor 

```

Thank you!

**Comment by dongminjung** [comment]
README and NEWS files were updated. Thank you.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dongminjung.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ttgsea")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ttgsea

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
