### ISSUE TITLE
Herper

### ISSUE THREAD

**Issue by matthew-paul-2006** [Bioconductor/Contributions#1654]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RockefellerUniversity/Herper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@matthew-paul-2006 you will not have access to the git.bioconductor.org package until tomorrow morning -- because you submitted the package but tc.informatics@gmail.com is listed as the maintainer, the app that manages ssh keys tries to associate your ssh keys with the tc.informatics@gmail.com user. This needs to be fixed manually. I'll post here when this is sorted out.

**Comment by LTLA** [comment]
You might consider using the conda installation managed by [**basilisk**](https://www.bioconductor.org/packages/devel/bioc/html/basilisk.html), where we have already fought through the difficulties of on-demand installation of conda and its environments on the Bioconductor build system.

**basilisk** also provides some (as-yet-unexported) utilities for conda environment activation and inactivation, which deal better with multi-line environment variables than `printenv`.

**Comment by ThomasCarroll** [comment]
Thanks, we will take a look at basilisk. 

For the install we wanted to capture the output as JSON which didn't look possible using the Reticulate conda_install. 
I think...think.. the error we got from the examples was due to us not using the temp directory where we had installed Conda but the default directory. Our mistake.
This should be fixed in our Github repo but we can't push to Bioconductor Git yet until ssh keys issue above is solved.

Thats a good point about the multiline environment variable. It hasn't caused any issues yet but I didn't think about it and I'll update that. 
I had missed this unexported .activate_condaenv functionality. I see basilisk uses printenv in release but in devel branch now uses a different approach. This looks neat and I'll take a proper review now to see if it would fit our required functionality. 

Thanks again for your comments

**Comment by matthew-paul-2006** [comment]
Hi @mtmorgan,

I was just wondering if you had a chance to look at my ssh, as we have updates to push. I just checked my BiocCredentials page and there's no ssh listed and when I tried to add mine manually it said someone else had that ssh. 

Cheers,
Matt

**Comment by mtmorgan** [comment]
I think you should be good to go @matthew-paul-2006

**Comment by matthew-paul-2006** [comment]
@mtmorgan just checking in. It looks like everything built well which is a relief. We're on to the review step now, is that correct?

Cheers,
Matt

**Comment by mtmorgan** [comment]
DESCRIPTION

- In your Description:, please summarize the major use cases you are supporting, and the merits of your approach relative to basilisk (@LTLA).

vignettes

- generally well done!

- update the installation instructions to reflect the package as accepted, with `BiocManager::install("Herper")`; if you'd also like to mention a pre-release version, the format is `BiocManager::install("RockefellerUniversity/Herper")`

- Herper.Rmd:159 I'm a little confused whether conda environment `seqCNA` is a (bio)conda environment for the R package, or...? If it's an R package, I'm concerned about the implicit mixing of conda- versus 'standard' R package installations; this has caused considerable problems in the past, with the recommendation being to choose one poisson or the other.

R (comments are on specifc lines, but apply generally)

- conda_search.R:77 generally, `message()` is sufficient, without `message(paste(...))`.

- conda_search.R:77 this seems like a `warning()` or even `stop()` rather than `message()`?

- conda_search.R:147 for readability of code, it is better to adopt less nesting

    ```
    test <- suppressWarnings({
        v1 <- compareVersion_vapply(versions_no_letters, package_version) == -1
        v2 <- compareVersion_vapply(versions_no_letters, package_version) == 0
        (sum(v1, na.rm = TRUE) + v2(na.rm = TRUE)) > 0
    })
    if (test) {
        ...
    }
    ```
    
   It seems like a light revision of `v1` / `v2` would allow re-use without replication.
   
- functions.R:172 this seems to repeat a pattern seen in, e.g., conda_search.R:41 -- define a single function and re-use

- functions.R:294 if this code is 'dead', then it is better to remove it (it's always available in git...)

- functions.R:384 consider using `strwrap()` to match user console width, rather than arbitrary line breaks.

- Generally, the extensive use of `suppressWarnings()` makes me nervous -- if there are known issues, these should be anticipated in the code, rather than masked by `suppressWarnings()`.

- functions.R:523 generally, use `on.exit(unlink(tmpname))` immediately after ` is created (line 507) so that the file is unlinked even in the face of error in the intervening code.

- list_CondaPkgs.R:49 `message(message())`?

- list_CondaPkgs.R:59 the return value of `print()` is not a useful value to return from a function. Better to print and then return (perhaps invisbly) something the user could compute on

    ```
    value <- result[, c("name", "version", "channel", "platform")]
    print(value)
    invisble(value)
    ```

- with_conda.R:24 `file.path()` is vectorized, so probably only a single call is necessary.

tests

- it would be great to see more extensive tests using the 'mock' approach -- rather than performing, e.g., a conda installation, the mock returns a known value for the test, e.g., for a `system2()` command, without actually running the command. See e.g., `testthat::with_mock()`.

NEWS

- it does not look like this file is maintained; maintain or remove.

**Comment by LTLA** [comment]
From a quick inspection of the package, I think the use case is quite complementary to how **basilisk** operates. **Herper** will catch all the packages that are not engineered with portability in mind, at the cost of requiring some extra `with_conda` syntax. **basilisk**-powered packages do not need that syntax but instead require an up-front investment by the package authors to declare the desired Python environment. (Plus some protection for multi-environment sessions.) IMO a hypothetical future BioC package that relies on Python (e.g., MOFA2) should use **basilisk** to provide a seamless user experimence, but there is still a need to "rescue" the many older packages (especially in CRAN) that do not do so, and that's where I can see **Herper** coming in.

Regardless, would be a good idea to at least use the same Conda installation. **basilisk** has done a lot of the legwork in establishing cache locations for the base installation and the package-specific environments, ensuring safety with respect to parallel writes, etc. These things also take a lot of space and it doesn't make sense to have two of them floating around.

**Comment by matthew-paul-2006** [comment]
Hi @mtmorgan ,

Thanks for the feedback. It has been very useful. We've gone through and tried to address your comments. I've included the details below. 

Cheers,
Matt

## DESCRIPTION

* We have updated our description to clarify our use cases and give a reference to when they should be using Basilisk instead. We also added these clarifications to our vignette, and added a link to basilisk. 

## VIGNETTES

* We have updated the installation instructions
* We clarified the vignette example of seqCNA [Herper.Rmd:159], which needs samtools to run. 
 
## R

* We cut out the use of message(paste(...)) throughout [conda_search.R:77]
* We updated conda_search to give the suggested warning and to reduce some of the nesting [conda_search.R:77 and 147] 
 this seems like a warning() or even stop() rather than message()?
* We added a function to define channels [functions.R:172]
* We removed dead code [functions.R:294]
* We used strwrap() to standardize outputs [functions.R:384]
* We severely cut down the use of suppressWarnings()
* We added on.exit commands to clear tmp files [functions.R:523]
* We simplified the messaging outputs from list_CondaPkgs()

## TESTS

* We have started work to include extra testing, and we are looking about how to best use mocks to be able fully test our functionality, though we have not integrated mocks as of yet. This will be an area of active development for us.  

## NEWS

* We updated the NEWS file to reflect the submission

**Comment by matthew-paul-2006** [comment]
Hi @LTLA,

Thanks for your thoughtful comments. I'm very happy that you see Herper as a complimentary tool. 

We very much see Herper as a collection of tools that allows on-the-fly management of the conda system. We were really aiming for something that will allow you to interact with conda easily, to grab and manage tools interactively and then use in our analysis while staying integrated with Rmarkdown. Be that tools that we need to run R packages or tools that don't have existing R integration. 
Our system requirements functionality is exactly as you said. It will allow us to mop up the older packages that are missing Basilisk. We really appreciate your approach in encouraging users and developers to have a coherent and consistent methodology to implementing conda within packages. We have tried to indicate that in our documentation by pointing people towards Basilisk. 
With regards to the installation we have tried to keep it pretty lightweight, with Herper only installing what is strictly required. But with the user control that that Herper provides anyone can specify which conda builds and environments they want to use, so it would be easy for someone to streamline their conda setup by selecting the Basilisk conda or environments while using Herper.  

Thanks for the input,
Matt

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/matthew-paul-2006.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Herper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Herper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
