### ISSUE TITLE
ADImpute

### ISSUE THREAD

**Issue by anacarolinaleote** [Bioconductor/Contributions#1655]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/anacarolinaleote/ADImpute

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by anacarolinaleote** [comment]
I am afraid I lost my passphrase, so I had to generate a new SSH key in order to push the fixes I implemented. This push was successful, both to my repository and to bioconductor. However, I think this was not recognized here (I can't change the SSH key during the revision process?). How should I proceed?

**Comment by anacarolinaleote** [comment]
Hi @nturaga, I'm wondering if everything is ok from my side for the revision process to carry on.
Thanks, Carolina

**Comment by nturaga** [comment]
Hi,

Everything is ok. Please fix any notes you find in the build report before I issue a review for your package.

Best,

Nitesh

**Comment by nturaga** [comment]
# Review

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

- Description field should match that of an abstract of a paper.

## NAMESPACE

ok

## man

- Good

## vignette

- vignette needs to be elaborated.

- Consider using `BiocStyle`.

## R

- Use SingleCellExperiment to enable interoperability to other
  Bioconductor single cell packages.

- Use `BiocParallel` instead of `parallel` and
  `doParallel`. https://bioconductor.org/packages/release/bioc/html/BiocParallel.html
  
- Don't set a default number of cores `ncores=4`. Instead use
  `BiocParallel::bpworkers()` which works similar to
  parallel::detectCores().
  
- Use `message()` instead of `cat()` to show messages to the
  user. `cat()` is usually reserved to show objects. Check
  http://bioconductor.org/developers/how-to/coding-style/ "End User
  Messages"
  
- Use `<-` instead of `=` for assignment. This is the R way.

- Remove commented out code.

- The coding style is uneven as compared to the rest of your codebase
  in scimpute_009.R. Please fix.

**Comment by anacarolinaleote** [comment]
Hi @nturaga,

Thank you for your comments, I will start addressing them.
Regarding your final point "The coding style is uneven as compared to the rest of your codebase
in scimpute_009.R": this is because the functions in this file were adopted from a different R package, scImpute, which is not bioconductor-ready. I adapted their code slightly, for integration with my package, but avoided major changes in order to avoid potentially breaking the functionality.
As I made sure the code is functional, would it be ok to just fix style issues as the use of `<-` instead of `=`? Or is it necessary for the package to be accepted that I re-organize the code and break existing functions into smaller ones to make it more modular?

Best,
Carolina

**Comment by nturaga** [comment]
Yes, styling changes on that are fine.

**Comment by anacarolinaleote** [comment]
Dear @nturaga,

Thank you for your suggestions.
Please find bellow a summary of the implemented changes in the new push:

> ## DESCRIPTION
> 
>     * Description field should match that of an abstract of a paper.

- [x] Expanded Description field.

> ## vignette
> 
>     * vignette needs to be elaborated.
> 
>     * Consider using `BiocStyle`.

- [x] Introduction added to vignette; expanded code explanations; removed messages generated by R chunks for cleanliness; added entry on `SingleCellExperiment` as input; used `BiocStyle`

> ## R
> 
>     * Use SingleCellExperiment to enable interoperability to other
>       Bioconductor single cell packages.

- [x] Added an additional argument for a `SingleCellExperiment` to exported functions: user can opt between matrix or `SingleCellExperiment`. 

>     * Use `BiocParallel` instead of `parallel` and
>       `doParallel`. https://bioconductor.org/packages/release/bioc/html/BiocParallel.html

- [x] Replaced `parallel` and `doParallel` with `BiocParallel`; added argument `BPPARAM` for the user to control the generated cluster (SOCK by default).

>     * Don't set a default number of cores `ncores=4`. Instead use
>       `BiocParallel::bpworkers()` which works similar to
>       parallel::detectCores().

- [x] Default number of cores is set to `bpworkers(BPPARAM)` - see point above

>     * Use `message()` instead of `cat()` to show messages to the
>       user. `cat()` is usually reserved to show objects. Check
>       http://bioconductor.org/developers/how-to/coding-style/ "End User
>       Messages"

- [x] `cat()` and `print()` replaced with `message()` 

>     * Use `<-` instead of `=` for assignment. This is the R way.

- [x] Implemented. 

>     * Remove commented out code.

- [x] Removed.

>     * The coding style is uneven as compared to the rest of your codebase
>       in scimpute_009.R. Please fix.

- [x] Styling changes implemented.

**Comment by nturaga** [comment]
Great work!

**Comment by anacarolinaleote** [comment]
Great, thank you for your contribution!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anacarolinaleote.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ADImpute")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ADImpute

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
