### ISSUE TITLE
AnVILBilling package

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#1659]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/AnVILBilling

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It looks like @vjcitn is submitting the package, but is not the maintainer (`"cre"` in the Authors@R field). Can you please make this information consistent, so the person submitting the package is also the maintainer? Post a comment here when these are aligned.

**Comment by vjcitn** [comment]
I have made this change in 0.99.1

**Comment by Kayla-Morrell** [comment]
Hello @vjcitn - 

Please see the initial review of the package below. The required changes must 
be made while the suggested changes do not have to be (though we strongly 
encourage them). Comment back here with updates that have been made and when 
the package is ready for a re-review.

Keep in mind that the deadline to accept new packages into the Bioconductor 3.12
release is 10/21. Any packages accepted after this date will be included in the
next release.


## General package development

- [ ] REQUIRED: The 'oREADME.md' file seems unneeded and if so it should be 
removed.

## DESCRIPTION

- [ ] SUGGESTION: The 'Title:' field should be bried but descriptive. You might 
consider changing this.

- [ ] SUGGESTION: The 'Description:' field is made up by less than 3 sentences. 
Please consider expanding this field and structure it as a full paragraph.

- [ ] SUGGESTION: 'LazyData:' should be set to false. Since there is very little 
data in this package this isn't a requirement.

- [ ] SUGGESTION: We encourage including the 'BugReports:' field with the 
relevant link to Github for reporting Issues.

## Vignette

- [ ] REQUIRED: There should be an 'Installation:' section that demonstrates to 
the user how to install the package from Bioconductor. The code could look like 
the following:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("AnVILBilling")
```

- [ ] REQUIRED: Avoid the use of direct slot access with `@` in code chunks. 
Accessor methods should be created and used instead.

- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: Avoid the use of direct slot access with `@` in examples code. 
Accessor methods should be created and used instead.

- [ ] SUGGESTION: The `@keywords internal` tag can be added to the documentation 
for any non-exported functions. This will remove the function from the 
documentation index.

## R code

- [ ] SUGGESTION: There are undefined global functions or variables. Consider 
adding `importFrom("utils", "sessionInfo")`.
        cost
        res
        sessionInfo
        usage_end_time
        usage_start_time

- [ ] REQUIRED: Avoid the use of `sapply()` (if possible), use `vapply()`.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 22 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. 
There are 6 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 212 lines that are not.

Best,
Kayla

**Comment by vjcitn** [comment]
all requirements met except sapply.  will work on it

**Comment by Kayla-Morrell** [comment]
@vjcitn - Great, everything looks good and I'm more than happy to accept the package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AnVILBilling")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AnVILBilling

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
