### ISSUE TITLE
systemPipeShiny

### ISSUE THREAD

**Issue by lz100** [Bioconductor/Contributions#1660]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/systemPipeR/systemPipeShiny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It looks like @lz100 is submitting this package, but is not the maintainer (`"cre"` in the Authors@R field); please make sure that the person submitting the package is the same as the person listed as the maintainer. Post a comment here when this has been corrected.

**Comment by lz100** [comment]
@mtmorgan Hi, I have changed the maintainer to me.

**Comment by lz100** [comment]
@mtmorgan Hi Martin, I just subscribed to the list when I change the maintainer and it cannot find me. Maybe could you update the list?

**Comment by mtmorgan** [comment]
Usually the list sends a confirmation email ; did you receive it? It often ends in spam mailboxes...

**Comment by lz100** [comment]
yes, I confirmed it and am able to login to the list. I triggered another build and see if it can find me.

**Comment by lz100** [comment]
@mtmorgan Hi Martin, I have fixed all the issues so far.

**Comment by mtmorgan** [comment]
My main concern is that the large code base is untested by examples, vignettes, or unit tests. I think meaningful effort should be expended to ensure that each function performs the operations they are implemented to do. The fact that this is a siny app does not make this impossible -- the goal is to evaluate the classes and functions, which at the end of the day accept and return standard R objects, rather than to ensure that the shiny app itself functions.

DESCRIPTION

- The large number of Imports: makes me very nervous -- you are depending on a large ecosystem of packages; changes in any package could break yours. I encourage you to evaluate the features you provide, and perhaps reduce the scope of the package or the dependencies required to accmplish your goals, with the aim being to reduce the long term maintenance cost of your package

NEWS

- if this file will not be manitanied, then it is better to remove it.

vignettes

- the use of `suppressPackageStartupMessages()` is redundant in code chunks with `message = FALSE`.

- the vignette seems quite extensive; few code chunks are evaluated, but I guess this is because of the shiny-based nature of the app.

tests

- not sure why inst/unitTests is present?

**Comment by lz100** [comment]
Thank you, Martin @mtmorgan , for reviewing the package. We have made some changes to address your comments:

> My main concern is that the large code base is untested ...

1. We added about 150 unit tests to make sure all the functions are covered. As you mentioned, some of the examples for functions are Shiny based so we added `if(interactive()){...}` to not run these shiny apps in checks. This time, the unit tests cover all of this kind of functions and our unit tests cover more than this.

2. We found a great function `testServer` from Shiny itself. This function mimic running a Shiny server without actually running a real app. You can see in a lot of our tests, we use this function to make sure the server function can be created and **can be called as an R object** inside the fake server so we can use other code to test objects inside the *reactive* functions are as expected. 
  - *test-01sps_core.R* This file tests if the app folder can be created, files are there, both core UI and server can be called as R objects and check if core classes function as expected. 
  - *test-02interactive_funcs.R* tests all functions that are shiny HTML widgets (can only be run in shiny app). For UI functions, we render the UI and check the `md5` to see if the UI is as exact as expected. For server functions, we use `testServer` to check reactivity. 
  - *test-03isps_tabs.R* tests individual shiny modules (like different pages of a big website) can be called and rendered correctly. 

3. The test coverage is close to 50% not including code examed by running examples. So we did not add unit tests for functions that can be well examed by running examples. If the examples running is included, we expect the coverage can reach 80-90%. 

> The large number of Imports ...

We reduced a few of them. It looks a lot because we also included some R core packages like `methods`, `utils`, `stats`.  Excluding them, we have about 30 other imports. I checked other shiny-based repo and find our number is about the average. I guess this is hard for all Shiny-based packages, there is some backend data process and frontend UIs as well. We need some extra imports to handle the frontend comparing to other standard R packages.  If you check the `sessionInfo()`, we only have about 80 nested imports in namespace. I guess this is not a crazy number in the Bioconductor community. 

To further reduce the uncertainty from other packages, we added one more unit test file:
  - *test-04imports.R* tests the most important imported functions to see if they work as we expected.  If changes are made in other packages, these tests will immediately inform us our usage may not be valid. So we don't need to go to the long code to dig for the location. 

> NEWS

removed 

> the use of suppressPackageStartupMessages() is redundant ...

removed 

> not sure why inst/unitTests is present?

removed

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lz100.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("systemPipeShiny")`. The package 'landing page' will be created at

https://bioconductor.org/packages/systemPipeShiny

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lz100** [comment]
Thank you for reviewing the package.
