### ISSUE TITLE
ExperimentSubset

### ISSUE THREAD

**Issue by irzamsarfraz** [Bioconductor/Contributions#1673]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/campbio/ExperimentSubset

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It looks like the person submitting this package is not listed as the maintainer (`"cre"` in the Authors@R field). Please update this so that the maintainer and submitter are the same, and post a comment here.

**Comment by irzamsarfraz** [comment]
I have updated the author information in the DESCRIPTION file.

**Comment by lawremi** [comment]
Presumably a similar efficiency could be achieved with DelayedArray and DelayedDataFrame. Tracking the subset information at the SE level may be useful from the provenance perspective.

If the ExperimentSubset class inherited from SummarizedExperiment, it would be a drop-in replacement and thus a very useful tool. While SummarizedExperiment does carry slots, they could simply be ignored. The overall decorator approach is sound.

The vignette currently just describes the individual methods. It would be more useful if it described an practical workflow.

**Comment by joshua-d-campbell** [comment]
Hi @lawremi, thanks for your feedback. The provenance and streamlined framework for storing/accessing subsets is definitely the primary objective of the package. For single cell RNA-seq analysis, a lot of subsets of the original data are taken at different times (e.g. filtering out empty droplets, filtering out poor quality cells, limiting to highly variable genes, clustering with a subpopulation of cells). Right now in the singleCellTK package, we are keeping these in different objects in a list, which is cumbersome. We will add a practical example to the vignette shortly to illustrate a workflow.

Interestingly, the first version of the package we made did have the ExperimentSubset class inheriting from SummarizedExperiment. But then we had to have a second class called SingleCellExperimentSubset which inherited from SingleCellExperiment. We changed the framework to make one class that would generally work with any Experiment class by having a "root" slot storing the original data. We are happy to change it back if there is a preference for the first approach though. The ability to use it as a drop-in replacement is certainly a benefit. 

We were also a little bit worried about unforeseen consequences with replacing several of the standard generics from S4vectors (e.g. rownames) so they could take in additional parameters . Just let us know if there are any issues with that.

**Comment by lawremi** [comment]
I appreciate the complications brought about by inheritance, which need to be weighed against the convenience of having an interoperable object. By continuing to rely on the decorator pattern, i.e., having an internal SE as the delegate, one could define methods on e.g. SingleCellExperiment-specific generics which would just force the subset and delegate to the result (failing if the delegate is not of the correct type). 

There are ongoing discussions between R core and the tidyverse around a new OOP framework for R, which could support implicit conversions to facilitate decoration.

**Comment by irzamsarfraz** [comment]
Hi all,

We have fixed all build issues and updated the vignette in detail that now illustrates practical workflows with real datasets and outlines the structure of our package.

**Comment by mtmorgan** [comment]
DESCRIPTION

- good

vignettes

- quite a nice vignette!

- ExperimentSubset.Rmd:91 An important aspect of object-oriented approaches is to separate the implementation (slots) from the interface; the heading here undermines this, at least in a user-oriented (section) of a vignette. Perhaps this is better discussed in a section about `## Implementation details`?

R (comments are on specfic lines, but apply generally)

- line 70: use accessors, even internally; these do not need to be exported, e.g., `.root <- function(x) x@root`.

- line 71 this looks like a `stop()` rather than return value. Also, a best practice is for a function to reutrn a consistent value; here you sometimes return character(1) and sometimes logical(1), which only makes work for the user.

- line 115: no need to prefix `ExperimentSubset::` here, or `methods::` later.

- line 133: start the parameter description with a statement of expected object type, e.g., `character(1) Specify...`.

- line 157: likely you only intend (there is only one method) to dispatch on the first argument of the generic; use the `signature = ` argument of `setGeneric()` to limit dispatch (and simplify method specification) to the first argument. Methods should still validate (e.g., via `stopifnot()`) the remaining arguments.

- line 196: avoid nested statements, especially in tests, e.g., write as

    ```
    test <- 
        parentAssay %in% SummarizedExperiment::assayNames(object@root) ||
        parentAssay %in% subsetAssayNames(object)
    if (test) ...
    ```
    
- line 334: `stop(paste(...))` can usually be replace with `stop(...)` (which calls `paste(...)` internally).

- line 1664: a cleaner presentation is to write a single `cat()`: 

    ```
    cat(
        "class: ExperimentSubset\n",
        "root ",
        ...
    ```

- line 1703: the formatting of this method is different from others, requiring much more indentation and less space per line; revise as

    ```
    setReplaceMethod(
        f = "assay",
        signature = ...
    ```

- line 1755 avoid use of `F` in favor of `FALSE`, since `F` can be redefined but `FALSE` cannot.

tests

- I'm not sure I understand what `tests/test-ExperimentSubset.R` is doing here, rather than within `tests/testthat/`?

- there is value in writing smaller `test_that()` clauses, since failures are reported at this level and one then has to step through the test to identify the problem.

**Comment by irzamsarfraz** [comment]
@mtmorgan 

**Hi,** 

**We have made almost all of the suggested changes. Please see our responses against each comment for further clarification.**

**Thank you!**

> ExperimentSubset.Rmd:91 An important aspect of object-oriented approaches is to separate the implementation (slots) from the interface; the heading here undermines this, at least in a user-oriented (section) of a vignette. Perhaps this is better discussed in a section about ## Implementation details?

**Done! We have added an Implementation Details section at the end of the vignette, so regular users don't really have to bother with these details.**

> line 70: use accessors, even internally; these do not need to be exported, e.g., .root <- function(x) x@root.

**Done!**

> line 71 this looks like a stop() rather than return value. Also, a best practice is for a function to reutrn a consistent value; here you sometimes return character(1) and sometimes logical(1), which only makes work for the user.

**Done!**

> line 115: no need to prefix ExperimentSubset:: here, or methods:: later.

**Done!**

> line 133: start the parameter description with a statement of expected object type, e.g., character(1) Specify....

**Done! Modified throughout the package!**

> line 157: likely you only intend (there is only one method) to dispatch on the first argument of the generic; use the signature = argument of setGeneric() to limit dispatch (and simplify method specification) to the first argument. Methods should still validate (e.g., via stopifnot()) the remaining arguments.

**Unfortunately, this is something we haven't been able to modify yet as the suggestion is a little unclear to us. Could this be explained in a little more depth and we would definitely update the package asap!**

> line 196: avoid nested statements, especially in tests, e.g., write as
> 
> test <- 
>     parentAssay %in% SummarizedExperiment::assayNames(object@root) ||
>     parentAssay %in% subsetAssayNames(object)
> if (test) ...

**Done!**

> line 334: stop(paste(...)) can usually be replace with stop(...) (which calls paste(...) internally).

**Done!**

> line 1664: a cleaner presentation is to write a single cat():
> 
> cat(
>     "class: ExperimentSubset\n",
>     "root ",
>     ...

**We have removed as many cat() calls as possible, but because we need to call the show() method internally, it wasn't really working as intended and the output got cluttered. As a result, we had to use at least 3 of the cat() calls (alongwith use of paste() and paste0() as we needed different separators at times).**

> line 1703: the formatting of this method is different from others, requiring much more indentation and less space per line; revise as
> 
> setReplaceMethod(
>     f = "assay",
>     signature = ...

**Done!**

> line 1755 avoid use of F in favor of FALSE, since F can be redefined but FALSE cannot.

**Done!**

> tests
> 
> I'm not sure I understand what tests/test-ExperimentSubset.R is doing here, rather than within tests/testthat/?
> 

**Done! Fixed.**

> there is value in writing smaller test_that() clauses, since failures are reported at this level and one then has to step through the test to identify the problem.

**Done! Added smaller test_that() units relevant to a particular functionality or a group of functions.**

**Comment by mtmorgan** [comment]
For the generic, if one writes

```
setGeneric("foo", function(x, y) standardGeneric("foo"))
```
then the generic will dispatch on values of x and y. But often 'y' is not meant for dispatch, e.g.,

```
setGeneric("bar", function(x, verbose=TRUE) standardGeneric("bar"))
```
From the perspective of the person writing this generic, `verbose` will always be logical, or else an error. So one writes
```
setGeneric(
    "bar",
    function(x, verbose = TRUE) {},
    signature = "x"
)
```
and methods are 
```
setMethod(
    "foo",
    "A",
    function(x, verbose = TRUE) {
        stopifnot(is.logical(verbose))
        ....
    }
)
```
Here the number of methods necessary is equal to the number of classes `x` that are allowed, rather than the combinatorial explosion implied by methods on each argument.

**Comment by irzamsarfraz** [comment]
Hi @mtmorgan 

This definitely makes sense now. We have updated the package and pushed the changes.

Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/irzamsarfraz.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ExperimentSubset")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ExperimentSubset

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
