### ISSUE TITLE
biocthis

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/Contributions#1674]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lcolladotor/biocthis

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data. **Note**: it enables creating more packages.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# Review

## General

I specially enjoyed reading the developer notes for biocthis!

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## NEWS

ok

## actions

- What is the purpose of having the `actions` directory?

## man

ok

## vignette

- Very nicely done! 

## R

- code is clearly written. Good job!

**Comment by lcolladotor** [comment]
Thanks for the review Nitesh!

I had the `actions` directory to match what others had done (I think that it was a suggestion by Jim Hester) and it was the original home of the GHA template, but with Marcel Ramos' @LiNk-NY PR, we have deprecated that directory. Currently, it's used by the instructions at https://github.com/r-lib/actions/tree/master/examples#bioconductor-friendly-workflow, particularly

```R
## You can also use this GHA workflow without installing biocthis
usethis::use_github_action(
    "check-bioc",
    "https://bit.ly/biocthis_gha",
    "check-bioc.yml"
)
```

though https://github.com/lcolladotor/biocthis/blob/master/actions/check-bioc.yml refers to https://github.com/lcolladotor/biocthis/pull/11 and provides instructions for using the new setup.

I could delete the `actions` directory after sending a PR to `r-lib/actions` for updating the docs. It might be best to hold off to do this as a single PR once `biocthis` is part of BioC, to link to the BioC landing page (if this submission is approved).

Best,
Leo

**Comment by nturaga** [comment]
That sounds fair. 

Great work @lcolladotor and @LiNk-NY

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lcolladotor.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biocthis")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biocthis

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
