### ISSUE TITLE
MSstatsTMTPTM

### ISSUE THREAD

**Issue by devonjkohler** [Bioconductor/Contributions#1677]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsTMTPTM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Devon, @devonjkohler 
Thank you for your submission to Bioconductor.
Please find the review below. 
If you have any questions, feel free to post them in the comments.
Best,
Marcel

---

# MSstatsTMTPTM #1677

* If possible, consider renaming the package into something that is easier
to remember. I had two typos already trying to clone the package.

## DESCRIPTION

* Looks good.
* Add more to the `Description` field explaining at what point in the workflow
can this package be used etc.
* Add a `BugReports` field pointing to the issues page for your GitHub
repository

## NAMESPACE

* If possible, avoid long function names (nchar > 10?) and shorten function
names.
* Re-export the pipe `%>%` if you'd like your users to also make use of it.

## vignettes

* Add an installation section using `BiocManager`
* It's easier to review a vignette (and possibly maintain) when the text does
not pass the 80 character width limit (I have multiple R scripts open on one
screen)
* Clafiry where the data are coming from (`raw.ptm` and `raw.protein`) in the
vignette.
* Remove possibly stale code that is commented out.
* Include a `sessionInfo` section.

## R

* Add a more descriptive name to the "example.comparisons", "test.pairwise",
and "test.example.comparisons" datasets.
* Avoid saving files for the user (`address` in `dataProcessPlotsTMTPTM`).
Either use a temporary directory or do not save files without the users
explicit direction (`address = FALSE`).
* Remove any code that is not run (in `dataProcessPlotsTMTPTM` examples)
* Why not use `match.arg` for checking the `type` input argument instead of
`setdiff`?
* Perhaps coerce to `factor` first and then use the `levels`? (e.g.,
`x <- as.factor(x)` then `levels(x)` in `dataProcessPlotsTMTPTM.R`)
* Some of the code can be combined (e.g., Lines#512-540 in
`R/dataProcessPlotsTMTPTM.R`)
* Where possible create helper function to reduce repetitiveness in the code
(e.g., `x$Run <- factor(x$Run)` in `R/dataProcessPlotsTMTPTM.R`)
* If possible, modularize functions and avoid monolithic functions that
contain 1000+ lines.


Minor:
* Use `<-` arrow assignment instead of `=` the equals sign.
* `stop(paste0(...))` can be reduced to `stop(...)`

**Comment by devonjkohler** [comment]
Hi Marcel, @LiNk-NY 

Thank you for taking the time to review my package.
I have tried to address all the points in your review and have pushed the update. 
A few I was unable to address at this time and I have outlined those below.

## MSstatsTMTPTM

In terms of the package and function names, because it is part of the MSstats system of packages I cannot rename them to something shorter at this time. Going forward I will try to think of a new naming system so that the package and function names can be shortened.

### Namespace

I did not Re-export the pipe %>% because users are not required to use it. It's used in the vignette simply as my preference for data manipulation.

### R

In terms of the helper functions and length of the package, this is going to addressed in the next release. In order to reduce the function length the code needs to be refactored considerably. This is planned as the next immediate step in the package.

**Comment by LiNk-NY** [comment]
Hi Devon, @devonjkohler 

Can you respond to the review line by line? Thank you!
I will have a look tomorrow morning. 

Best,
Marcel

**Comment by devonjkohler** [comment]
Hi Marcel, @LiNk-NY 

Definitely! Here is the line by line response.

Thanks,
Devon

# MSstatsTMTPTM #1677
* If possible, consider renaming the package into something that is easier
to remember. I had two typos already trying to clone the package. - Since this is part of the MSstats system of packages I cannot rename it to something shorter at this time. This naming system is getting long so going forward we will try to think of a new naming system so that the package and function names can be shortened.

## DESCRIPTION
* Looks good.
* Add more to the `Description` field explaining at what point in the workflow
can this package be used etc. - Done
* Add a `BugReports` field pointing to the issues page for your GitHub
repository - Done

## NAMESPACE
* If possible, avoid long function names (nchar > 10?) and shorten function
  names. - Same thing as with the package name. These are based off function
 names from MSstatsTMT and cant be renamed at this time.
* Re-export the pipe `%>%` if you'd like your users to also make use of it. - 
Users should not be required to use this when using the package so I did not re-export

## vignettes
* Add an installation section using `BiocManager` - Done
* It's easier to review a vignette (and possibly maintain) when the text does
not pass the 80 character width limit (I have multiple R scripts open on one
screen) - Done, tried to do this across all functions/files
* Clarify where the data are coming from (`raw.ptm` and `raw.protein`) in the
vignette. - Done
* Remove possibly stale code that is commented out. - Removed stale code, 
there are a few small instances of commented out code that are examples
I wanted to keep.
* Include a `sessionInfo` section. - Done
 
## R
* Add a more descriptive name to the "example.comparisons", "test.pairwise",
 and "test.example.comparisons" datasets. - Changed names to try and be more descriptive
* Avoid saving files for the user (`address` in `dataProcessPlotsTMTPTM`).
  Either use a temporary directory or do not save files without the users
  explicit direction (`address = FALSE`). - Done, swapped to local plot
* Remove any code that is not run (in `dataProcessPlotsTMTPTM` examples) - Done
* Why not use `match.arg` for checking the `type` input argument instead of
 `setdiff`? - I have left this alone for now, I see the advantage of match.arg and
  will look at changing it in a future release
* Perhaps coerce to `factor` first and then use the `levels`? (e.g.,
 `x <- as.factor(x)` then `levels(x)` in `dataProcessPlotsTMTPTM.R`) - Tried to do this
 where possible.
* Some of the code can be combined (e.g., Lines#512-540 in
 `R/dataProcessPlotsTMTPTM.R`) - Done
* Where possible create helper function to reduce repetitiveness in the code
  (e.g., `x$Run <- factor(x$Run)` in `R/dataProcessPlotsTMTPTM.R`) - Tried to do this
  where possible without full code refactoring.. See next line.
* If possible, modularize functions and avoid monolithic functions that
  contain 1000+ lines. - this is going to addressed in the next release. 
  In order to reduce the function length the code needs to be refactored
  considerably. This is planned as the next immediate step in the package.
  This will include both creating helper functions and modulating the large
  block into smaller functions.

Minor:

* Use `<-` arrow assignment instead of `=` the equals sign. - Done
* `stop(paste0(...))` can be reduced to `stop(...)` - Done

**Comment by LiNk-NY** [comment]
Hi Devon, @devonjkohler 
Thanks for making those changes, they look good!

* Can you remove `BiocManager` from the `Suggests` field? The `BiocManager` code in the vignette is for show (where `eval=FALSE`); therefore, import is not needed. 

After this minor change. We will be ready to accept the package. Thank you. 

Best regards,
Marcel

**Comment by devonjkohler** [comment]
Hi Marcel, @LiNk-NY 

That's awesome! I just pushed through the update to remove BiocManager from the suggestions.

Devon

**Comment by devonjkohler** [comment]
Hey Marcel, @LiNk-NY 

I was wondering if you had a chance to take a final look at the package? Does everything seem in order for it to be accepted? 

Thanks!
Devon

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/devonjkohler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsTMTPTM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsTMTPTM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
