### ISSUE TITLE
customCMPdb

### ISSUE THREAD

**Issue by yduan004** [Bioconductor/Contributions#1680]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yduan004/customCMPdb

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Please see the initial review below: 


# general

- [ ] Was this package meant to import data into the hubs? It looks like you have the inst/scripts and inst/extadata/metadata.csv file but nothing has been added to the hubs? It looks like maybe this information moved to a different package compoundCollectionData? 

- [ ] It looks like you have an accompanied package that the data was moved into compoundCollectionData. This package should be officially submitted to Bioconductor for review as stated when the package data was originally submitted to the hubs in the email on 3/31/2020. Since this appears to be the accompanied data pacakge for this software package I would suggest submitting under this issue as a [related package](https://github.com/Bioconductor/Contributions#submitting-related-packages). The package compoundcollectiondata must have a formal review and be submitted to bioconductor or the data will be removed from the hub. 
  

# vignette

- [ ] remove `customCMPdb.html`. Vignettes should be interactively built.


# R

_drugage\_annot.R_

processDrugage:

- [ ] We generally discourage random downloads. This should either be stored in the hubs or minimally the file should be cached so that if it is ever not available for download users may used a cached version.

- [ ] You hard coded downloads directory to unzip. The user should control where the file is downloaded to.

- [ ] Hard coded paths seem to suggest this function would be broken for other users
  `chembldb <-
  "/bigdata/girkelab/shared/lcshared/chemoinformatics/compoundDBs/chembl_24/chembl_24_sqlite/chembl_24.db"`


downloadUniChem:

- [ ] Same comments as above. Minimally files should be cached and the user should be allowed to specify a write directory.


_manageCMAP.R_

- [ ] Same as above getDmap should not download and save information to a users  home directory without asking users permission or allowing user to specify  output directory. And download files should be minimally cached. 

- [ ] change print to message


Please submit the accompanied package as soon as possible and implement the changes recommended above. When ready please perform a version bump to trigger a new build and comment here on what has been updated and that you are ready for a re-review.  Cheers

**Comment by yduan004** [comment]
Hi Lori,

Thanks for reviewing my package. The situation is that I previously planned to write two packages, one software and one data package, where the data package used to store the compound annotation and structure databases, and the software package used as query and customization interface. The data package is named as `compoundCollectionData` and the data has been uploaded to `AnnotationHub` on 3/31/2020. The software package is named as `customCompoundDB`. But with the consideration that the data is of small size and overall this is a small utility package, it is unnecessary to have two packages. So I decided to merge the two packages into one package to simplify maintainability. So `customCMPdb`  is a combination of the both the data and software packages, it contains the descriptions of the data that are already submitted to AnnotationHub. 

So my specific question is whether it will be possible to rename the accompanied `compoundCollectionData` package as `customCMPdb`? This way, the package submitted to AnnotationHub will be `customCMPdb`, and is being reviewed. I hope this solution can be accepted. If it is accepted, I will editing the `metadata` in the `customCMPdb` package accordingly. I will respond to your R comments later. Looking forward to your response.

Best,
Yuzhu

**Comment by yduan004** [comment]
Hi Lori, @lshep 

Thanks for reviewing my package. Here are my further responses to your comments.

# general

- [x] Was this package meant to import data into the hubs? It looks like you have the inst/scripts and inst/extadata/metadata.csv file but nothing has been added to the hubs? It looks like maybe this information moved to a different package compoundCollectionData?

- [x] It looks like you have an accompanied package that the data was moved into compoundCollectionData. This package should be officially submitted to Bioconductor for review as stated when the package data was originally submitted to the hubs in the email on 3/31/2020. Since this appears to be the accompanied data package for this software package I would suggest submitting under this issue as a related package. The package compoundcollectiondata must have a formal review and be submitted to bioconductor or the data will be removed from the hub.

YD response: I have responded to this issue in my last post, please take a look at it. I hope the suggestion/request of renaming the `compoundCollectionData` package as `customCMPdb` could be accepted. In addition, in the `metadata.csv` file, I have changed all `compoundCollectionData` to `customCMPdb`. I have also made changes all over the package. Now the `customCMPdb` is the only one package that is a combination of both data and software packages. The datasets have been uploaded to `AnnotationHub` previously.  

# vignette

- [x] remove customCMPdb.html. Vignettes should be interactively built.

The html file of the vignette has been removed.

# R

_drugage_annot.R_

processDrugage:

- [x] We generally discourage random downloads. This should either be stored in the hubs or minimally the file should be cached so that if it is ever not available for download users may used a cached version.

Thanks for this very helpful comment! I have addressed this issue by using utilities in the `BiocFileCache` package to download online resources to user’s cache directory by using `bfc <- BiocFileCache(cache=rappdirs::user_cache_dir(appname="customCMPdb"), ask=TRUE)` code.

- [x] You hard coded downloads directory to unzip. The user should control where the file is downloaded to.

Now, all the downloads are stored in user’s cache directory. The ‘tar.gz’ files are also extracted under the cache directory for future uses, it is only done once. 
 
- [x] Hard coded paths seem to suggest this function would be broken for other users
`chembldb <- "/bigdata/girkelab/shared/lcshared/chemoinformatics/compoundDBs/chembl_24/chembl_24_sqlite/chembl_24.db"`

Sorry, it was an oversight on my part to include this hard coded path in my package. Thanks for pointing this out! Now, this hard coded path has been deleted. Instead the corresponding data are downloaded from the corresponding ftp site of ChEMBL and stored under cache.

downloadUniChem:

- [x] Same comments as above. Minimally files should be cached and the user should be allowed to specify a write directory.

This function has been deleted. Now the downloaded files are all cached, and the path of the output files are specified by users. 

_manageCMAP.R_

- [x] Same as above getDmap should not download and save information to a users home directory without asking users permission or allowing user to specify output directory. And download files should be minimally cached.

The `getDmap` function has been deleted, and the DMap dataset is now included in the `extdata` directory of the `customCMPdb` package. 
 
- [x] change print to message

The print has been deleted since it is not necessary. Now, the `message` function is used all over the R scripts for places where outputting a message to users. Thanks for pointing out.

The package is ready for your re-review. Thanks again for your time!

Best,
Yuzhu

**Comment by lshep** [comment]
In the future,  We generally still recommend separating experiment or annotation packages no matter how light weight to have a clear distinction between data and software. Also in general, if hub data does not have an associated package it would be removed (this happen to just slip through the cracks for the CompoundCollectData to still be available).   But if you wish to proceed with one package, I can take care of the renaming.  For What Its Worth,  this isn't a simple task and will involve extra time on my end not only to rename directories on S3 but also to manually manipulate entries in our database for each of your files.  When I'm finished with the renaming,  I'll do a re-review of the updated package.

**Comment by lshep** [comment]
The data in the hub has been updated to be associated with this package 
```
> ah = AnnotationHub()
snapshotDate(): 2020-10-14
> query(ah, "customCMPdb")
AnnotationHub with 5 records
# snapshotDate(): 2020-10-14
# $dataprovider: Broad Institute, DrugBank, DrugAge, DrugBank, Broad Institu...
# $species: Homo sapiens
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH79563"]]' 

            title         
  AH79563 | annot_0.1     
  AH79564 | drugage_build2
  AH79565 | drugbank_5.1.5
  AH79566 | cmap02        
  AH79567 | lincs_pilot1  
```
Please make sure everything still works as expect.  Then please do another version bump so we can ensure the resources are still accessible in the package on the builders as well.

**Comment by yduan004** [comment]
Hi Lori,

Thank you very much for renaming things. I am sorry for making additional work on your end... I will make a version bump right away to ensure everything still works. Thanks again for your help!

Best,
Yuzhu

**Comment by yduan004** [comment]
Hi Lori @lshep, the check status is OK, please re-review the package. Many thanks!

**Comment by yduan004** [comment]
Hi Lori, thanks for reviewing and accepting the package!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yduan004.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("customCMPdb")`. The package 'landing page' will be created at

https://bioconductor.org/packages/customCMPdb

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
