### ISSUE TITLE
CNVgears

### ISSUE THREAD

**Issue by SinomeM** [Bioconductor/Contributions#1685]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SinomeM/CNVgears

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by SinomeM** [comment]
Hi @mtmorgan, 
I apologize for the long series of failed check. I had experienced a series of technical problems on my machine and this made R CMD check fail for reasons not related to the package.
Let me know if I'm still missing something 
Simone

**Comment by mtmorgan** [comment]
I'm sorry for the delay in my review.

General

- it is not really clear why `data.table` is used or needed for user-facing data. `data.table` has 'reference' semantics and an API that is not familiar to many R users. The data that the user needs to work with outside the package does not seem to be that large that the impressive performance of data.table is required? Of course 'inside' the package it is fine to pursue whatever data representation is most efficient.

- Is there a reason not to use the GenomicRanges infrastructure? This would greatly facilitate interoperability and robust code re-use. For example, it looks like you have adopted a '0-based, half-open' coordinate system, where Bioconductor uses '1-based, closed' coordinates. I see your vignette using cn.mops and XRanges; the different structures and coordinate systems between your package and cn.mops only confuses the user.

DESCRIPTION

- Can you please provide a little more detail in the Description: field, so that soemone reading this will know what the package does?

vignettes

- Please update installation instructions to reflect best practices for an accepted Bioconductor package, using `BiocManager::install("CNVgears")`.

- consider re-naming the vignette file more informatively. 

- there is no 'top level' heading `# Initial note` so the table of contents has, .e., `0.1 Initial Note` rather than, e.g., `1.0 Initial note`.

R (comments on specific lines; some may require update throughout code).

- CNVRs_creation.R:271 use `message()` (prints to stderr) rather than `cat()` (prints to stdout) for 'verbose' output during fucntion evaluation


- CNVRs_inheritance.R:145 The code is too complicated to follow in detail, but the use of row-wise `for` loops make me very concerned that your code uses 'iteration' (call an R function `n` times, once for each element) when it could instead use `vectorization` (call an R function once). A trivial example is `x = 1:10; sapply(x, log)` (iteration, `log()` called 10 times) versus `log(x)` (vectorization, `log()` called once). A little more extensive example, from `chr_st_end_centr_arms.R`:20, revise the `for` loop as

    ```
    idx <-
        startsWith(head(bands$V4, -1), "p") & 
        startsWith(tail(bands$V4, -1), "q")
    df <- data.frame(chr = bands$V1[idx], centromere = bands$V3[idx])
    ```
    
  The 'copy-and-append' style of iteration 
  
    ```
    hg38_chr_arms <- data.table()
    for (i in 1:nrow(hg38_start_end_centromeres)) {
        hg38_chr_arms <- rbind(
            hg38_chr_arms,
            data.table(
                "chr" = hg38_start_end_centromeres$chr[i],
                "arm_ID" = paste0(hg38_start_end_centromeres$chr[i], c("p", "q")),
                "start" = c(0, hg38_start_end_centromeres$centromere[i] + 1),
                "end" = c(
                    hg38_start_end_centromeres$centromere[i],
                    hg38_start_end_centromeres$end[i])
            )
        )
    }
    ```
    
  is also often very inefficient (maybe data.table handles this better...) and is not necessary.

- CNVRs_inheritance.R:266 usually no need to call `warning(paste0(...))`; just use `warning(...)`.

- chr_st_end_centr_arms.R:50 perhaps use BiocFileCache::bfcrpath() (see the vignette for caching internet resources) to improve the experience / reduce depedence on reliable internet.

- chr_st_end_centr_arms.R:44 I was surprised to see `usethis::use_data()`, which is normally used during package development -- it will not be doing the right thing if this code is encoutered by the user.

    ```
    > setwd("/tmp")
    > usethis::use_data(1:10)
    Error: Path '/private/tmp/' does not appear to be inside a project or package.
    ```

- telom_centrom.R:33 a useful approach to errors / warnings is to stick fairly closely to the reason for the error / warning, e.g., `warning('telome' and 'centrom' are both FALSE; the function won't do anything")`. Of course spell-checking is always helpful ;)

man

- many of the help pages for data resources are too brief to be informative. E.g., `?penn_22`.

**Comment by SinomeM** [comment]
Hi, thank you for the review! I'll check the code as soon as possible to integrate your correction.

Meanwhile, regarding the general comments, the two issues are closely related and I'll try to answer to both together.    
I originally choose to use `data.table` because, even though is true that the resulting objects of the main functions are not that large 1. they may be (e.g. using Whole Genome Sequencing and markers of 1kb the total number of markers is ~3 millions), 2. in any case several functions in the package performs lot of inter-table comparisons and I found these kind of processes significantly faster using `data.table` if compared to other approaches such as tidyverse packages or GenomicRanges, 3. I personally am quite used to `data.table` and 4. I wanted to use `data.table` internal parallelization rather than deal with it myself (this was probably the main reason for the choice when I started developing the package). I agree that the majority of R user could find `data.table` syntax complex, I could change the vignettes examples if this is what you where referring to.    
When we decided to make the package public I started the process of integration with the Bioconductor packages and data structures however I still feel that the major objects need to be `data.table` for the reasons explained above. The final results can be converted into GenomicRanges via a provide function (`CNVresults_to_GRanges()`).    
Regarding the different coordinate system, I need to check. 

Let me know if my reasoning is clear enough, I am a relatively new bioinformatician so I always have a lot to learn!


PS, regarding the actual code, I noticed that most of the comment are on a function that I erroneously exported (`chr_st_end_centr_arms`). Not to say that, e.g., your comment of the unoptimized for loop is wrong, just to say that that for loop (again as an example) is meant to be run by me (not the user) and only if needed, to generate/update some of the package data.

**Comment by SinomeM** [comment]
In regard to the use of row-wise for loops,
I know very well that this kind of iterations in particular and, for loops in general, should be avoided in R and I tried to do so whenever possible. However, to our knowledge, given the purpose of some package functions a number of them are inevitable. This is the second main reason why I strongly rely on data.table and its internal paralellization.   
As an example the loop you pointed out (CNVRs_inheritance.R:145) performs an extensive series of "nested" comparison where the results of the first one in needed by the others etc, and I honestly can't think of a way of performing them without using these kind of loops. Several of the main functions needs to perform this kind of comparisons.

**Comment by SinomeM** [comment]
Hi I integrated all the corrections not related to `data.table`, I'm having now an error which I'm not sure is on "my side":
```
* creating vignettes ... ERROR
--- re-building CNVgears.Rmd using rmarkdown
Quitting from lines 477-488 (CNVgears.Rmd) 
Error: processing vignette 'CNVgears.Rmd' failed with diagnostics:
error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
--- failed re-building CNVgears.Rmd

SUMMARY: processing the following file failed:
  CNVgears.Rmd
```

**Comment by mtmorgan** [comment]
yes, this is a problem elsewhere. I'll provide final comments later today.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SinomeM.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CNVgears")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CNVgears

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
