### ISSUE TITLE
SpatialDecon

### ISSUE THREAD

**Issue by patrickjdanaher** [Bioconductor/Contributions#1690]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nanostring-Biostats/SpatialDecon

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by patrickjdanaher** [comment]
To the Bioconductor review team,
Please see below for a list of the BiocCheck NOTES I’m seeing along with explanations for them:
Thanks,
Patrick

[1] "Potential intermediate files found:"   
>	This is just our html vignette. Deleting that file removes this note, but I’m reluctant to delete it until I get confirmation from you that it will be recreated by the Bioconductor built process.
                                                                                                                                           
[2] "Recommended function length <= 50 lines."            
> I have a handful of functions that exceed 50 lines, but the more I think about it, the more it seems that breaking them up into smaller functions would make the code harder to read, not easier. I look to you to tell me whether this guideline is hard or flexible, or if you disagree that these functions wouldn’t make more sense broken up. 

                                                                                                                             
[3] "Consider shorter lines; 26 lines (1%) are > 80 characters long."  
> These are all in .Rd files created by Roxygen; the .R files containing the Roxygen documentation are all <80 characters. Is this acceptable? 
                                                                                                                
[4] "Consider multiples of 4 spaces for line indents, 662 lines(21%) are not."                             
> As far as I can tell these are all instances of when I’ve used indentation to line up function arguments to make them more legible. I think my usage is consistent with Bioconductor style, though please correct me if I’m wrong. 

                                                                            
[5] "Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin\ncredentials).  Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel"
> I think I’m subscribed now. 


In addition, devtools::check() gives me the following:
WARNING
‘qpdf' is needed for checks on size reduction of PDFs
>	Since this is specific to my machine, I assume it’s not pertinent to packages being assembles by Bioconductor?


NOTE
 unable to verify current time
>	This also seems specific to my machine and not pertinent to the package once it’s getting built by Bioconductor.

**Comment by Kayla-Morrell** [comment]
Hello @patrickjdanaher, 

The NOTES are not of major concern, most of these will be addressed in my review. However, the NOTES you mentioned from BiocCheck are minor and will not dictate the acceptance of the package. In order for me to review the package I will need a clean build report and there seem to be ERRORs that need to be addressed (see the [build report](http://bioconductor.org/spb_reports/SpatialDecon_buildreport_20201002154033.html) for ERRORs). Please fix these ERRORs and once a clean build report is produced I can continue with the review process.

Keep in mind that the deadline to accept new packages into the Bioconductor 3.12 release is 10/21. Any packages accepted after this date will be included in the next release.

Best,
Kayla

**Comment by patrickjdanaher** [comment]
Hi @Kayla-Morrell ,

Thanks. I'll look forward to the review. 

Best,
Patrick

**Comment by Kayla-Morrell** [comment]
Hello @patrickjdanaher - 

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

Keep in mind that the deadline to accept new packages into the Bioconductor 3.12
release is 10/21. Any packages accepted after this date will be included in the
next release.

## DESCRIPTION

- [ ] SUGGESTION: Since you are using a standard license the LICENSE file isn't 
really necessary.

- [ ] REQUIRED: 'LazyData:' should be set to 'FALSE'. It's our expreience that 
having this field be set to true can slow down the loading of the package, 
especially if they include data.

- [ ] REQUIRED: There are packages/functions used in your code that aren't 
documented in the DESCRIPTION file. For example, you use `colors()` from 
`grDevices`. These packages need to be listed under 'Imports:' in the 
DESCRIPTION file.

- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with a 
relevant link to Github for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: Consider adding '@importFrom()' to your documentation to import 
the functions used by the packages listed under 'Imports:' in the DESCRIPTION 
file.


## Vignette

- [ ] REQUIRED: There should be an installation section that demonstrates to the 
user how to install the package from Bioconductor. The code should look like the 
follow and include `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("SpatialDecon")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: The final section should be 'Session Info' and should include 
`sessionInfo()`.

## Man pages

- [ ] REQUIRED: The documentation for 'mini_geomx_dataset' seems almost exact to 
'cellcols'. Are they the same? If not, please edit accordingly.

- [ ] SUGGESTION: For any man page that documents a non-exported function I 
suggest adding the `@keywords internal` tag. This will remove the function 
from the documentation index.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 55 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 257 lines that are not.

Best,
Kayla

**Comment by patrickjdanaher** [comment]
Hi Kayla,

Do you think we could leave LazyData = true? Changing it to false is causing a lot of problems, and the package loads very quickly as-is (the data it loads is relatively small). 

Thanks,
Patrick

**Comment by Kayla-Morrell** [comment]
Hello @patrickjdanaher - yes, you can leave LazyData = true. Thank you for checking.

**Comment by Kayla-Morrell** [comment]
@patrickjdanaher  - I see the clean build report, is this package ready for re-review?

**Comment by patrickjdanaher** [comment]
Hi @Kayla-Morrell ,
Yep, it's ready for review. I addressed all the required and many of the suggested comments. 
Thanks,
Patrick

**Comment by Kayla-Morrell** [comment]
@patrickjdanaher - Great! Thank you for making the necessary changes. I've reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by patrickjdanaher** [comment]
Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/patrickjdanaher.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpatialDecon")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpatialDecon

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
