### ISSUE TITLE
recount3

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/Contributions#1691]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LieberInstitute/recount3

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Leonardo, @lcolladotor 

Thank you for your submission to Bioconductor.
Please see the review below. 
If you have any questions, feel free to post them as comments below.

Best regards,
Marcel

---

# recount3 #1691

* Overall looks pretty good.
* This package is a software package that imports data resources from
a JHU url.

## DESCRIPTION

* Looks good.
* Replace the DOI url with a real one in the `Description` file.
* Consider `BiocIO` instead of `rtracklayer` for importing files.

## NAMESPACE

* It looks good.
* Consider shortening some function names, if possible (e.g.,
`file_locate_url_annotation` and `project_home_available`).
* I don't think you need explicit imports for `SummarizedExperiment` functions
(`Depends` field) but I guess it doesn't hurt.

## vignettes

* I like that you've included a quick start guide.
* Can't the `.bib` file be provided as a `inst/references.bib` file? It's good
that you generate the `.bib` file with R code but you can also have a static
document because it doesn't change often. Also, you won't need to 'clean it up'
afterwards
* It's easier to review vignettes (and possibly maintain) that conform to the
80 character width limit.
* Consider including non-interactive code in another chunk with `eval=FALSE`.
* Consider providing some user-friendly layer for typical `BiocFileCache`
operations.

## R

* Internal functions are not usually `@export`ed and are only available in the
package environment (`annotation_ext`, `annotation_options`, etc).
* `rtracklayer::import` will be moved to `BiocIO` AFAIU
* Provide a `verbose = FALSE` option for the user in functions like
`R/create_rse_manual.R`.
* Consider using a helper function for the `stopifnot` messages in
`R/create_rse_manual.R`.
* If possible, create an abstraction layer for the `bfc` argument that allows
a user to set their own cache location via path rather than using a BFC object.
* Package specific cache locations can be set using
`tools::R_user_dir("recount3", "cache")` (optional).
* `file_list` should have a sensible default for the `url` argument and
avoid checking the users files to ensure 'purity'. The user should use
`list.files` directly.
* `file_list` should also access a file that lists all the data available
rather than 'scraping' the website to see what's available. This file would
have to be generated on the server end rather than the client end.
* When downloading data to local computer, the package should manage the
user's downloaded data using `BiocFileCache` so that they shouldn't have to
enter a 'file path' for the `url` argument. A convenience function would
tell them what data is already downloaded.
* I'm not sure how `match.arg` works with non-vector choices in
'match.arg(project_home)'
* Is the `fread` dependency needed? Perhaps, it can be a suggests?
(`R/read_counts.R`)

Minor:
* Perhaps a `Reduce(merge(...))` can replace the merging of `metadata` in
`R/read_metadata.R`. If metadata files are consistent then maybe use
`do.call(rbind(...))`.

## / pkg directory

* There's a `dev` folder there. Perhaps move it to `inst/scripts/*` or put it
somewhere else?

## tests

* Add more tests :)

## man

* I am not sure if image files should go in the `man` folder. Are they used
for the vignettes?

**Comment by lcolladotor** [comment]
Thanks Marcel for the detailed review!! 

I'll work on addressing your points next week. I have some clarifying questions and comments.

* I wasn't aware of the existence of `BiocIO`. Should we switch to it now or after `rtracklayer::import()` is moved there?
* We are depending on `SummarizedExperiment` because that was requested when we submitted `recount` a few years ago. The idea was to make it easier for users to use all the `SummarizedExperiment` functions on the RSE objects `recount3` (and `recount`) provides. I've gotten used to this as a user myself, so I think that it's a good idea to keep it under `depends`.
* Regarding the abstraction layer for `bfc`, are you talking about that being passed to `BiocFileCache::BiocFileCache(cache)`? So the user provides the path, but not the `BiocFileCache::BiocFileCache()` object? Maybe something like this:

```R
#' @param recount3_cache A `character(1)` specifying the recount3 cache file location.
foo <- function(recount3_cache) {
     bfc <- BiocFileCache::BiocFileCache(cache = recount3_cache)
}
```

* The `dev` folder is ignored by `.Rbuildignore`. It details code that was used for making the package and code that I frequently re-run myself when updating it.
* The image in the `man` folder is used for the `pkgdown` website. It's the location they recommend for the logo image.
* For the tests, we discussed in our weekly meeting what to do, and we'll add some test files to the package. They might have to be non-realistic files though, to keep the R package size under 5 mb.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi Marcel,

Thanks for the extra info!

I took a look at https://github.com/seandavi/BiocPkgTools/blob/master/R/cache.R and will adapt it for `recount3` then. I need to learn a bit what `rappdirs` does, but that should hopefully be easy given the working example in `BiocPkgTools`.


I'm still having issues understanding `BiocIO`. Like, can it be used for importing a BED file? Maybe what I need to do is use `rtracklayer::import.bed()` instead of using `rtracklayer::import()` at https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L182.


Best,
Leo

**Comment by LiNk-NY** [comment]
Hi Leo, @lcolladotor 

Sorry the code is a bit dated. I would use `tools::R_user_dir("recount3", "cache")` instead. 

My understanding of the package is that it allows you to create methods for the `import` generic. If `rtracklayer` is already providing that file-specific method, it would be better to use that. @Kayla-Morrell can provide more information about how to best support this function dependency. 

There are some changes slated for `rtracklayer` that I do not know the specifics about (cc: @lawremi). 

Best, 
Marcel

**Comment by lcolladotor** [comment]
Hi @LiNk-NY!

I made changes to respond to your review which pass R CMD check / R CMD BiocCheck ^^. The one thing that I still need to work on is adding tests. But well, I wanted to make sure we could proceed with the rest of the review given the upcoming deadline (next Wednesday) for new BioC package submissions.

Let me know what you think. And thanks again for the info on the cache! I made a few small new functions which I think are along what you had in mind.

Best,
Leo

## DESCRIPTION

> Replace the DOI url with a real one in the Description file.

We will once we have an actual preprint (maybe a couple more months more).

> Consider BiocIO instead of rtracklayer for importing files.

Looks like all we needed was to use `rtraklayer::import.bed()`. We will switch to `BiocIO` if the rtracklayer functionality moves there in the future.

## NAMESPACE

> Consider shortening some function names, if possible (e.g.,
file_locate_url_annotation and project_home_available).

We shortened the names of these functions:

* `project_home_available()` is now `project_homes()`
* `file_locate_url()` is now `locate_url()`
* `file_locate_url_annotation()` is now `locate_url_ann()`

>I don't think you need explicit imports for SummarizedExperiment functions
(Depends field) but I guess it doesn't hurt.

Looks we it doesn't hurt as discussed above.

## vignettes

> Can't the .bib file be provided as a inst/references.bib file? It's good
that you generate the .bib file with R code but you can also have a static
document because it doesn't change often. Also, you won't need to 'clean it up'
afterwards

I haven't changed this. It could be made static, but well, I've seen with other packages that by using dynamic code we can make sure that we are pointing people to the latest citation people want to use for their packages without us having to keep a very close eye on this. Hence why I like our current setup.

> It's easier to review vignettes (and possibly maintain) that conform to the
80 character width limit.

I haven't changed this. Hm... with "prose" I like how a single line per paragraph makes it easier to see the differences on GitHub's diff. Otherwise a lot of differences can be due to making a line longer or shorter based on an upstream edit. I use a word wrap setting on text editor and hopefully the vignette at http://research.libd.org/recount3/articles/recount3-quickstart.html can help a bit if needed. Though well, I guess that with some other text editors that don't have word wrapping, the long lines would be very problematic.

> Consider including non-interactive code in another chunk with eval=FALSE.

Done =)

> Consider providing some user-friendly layer for typical BiocFileCache
operations.

I added 3 functions related to the caching of the files and some of your other points:

* `recount3_cache()` which takes a `dir` parameter to set the location of the cache. It defaults to your suggestion `tools::R_user_dir("recount3", "cache")` (which was new to me) that I liked quite a bit! Thanks ^^
* `recount3_cache_list()` for listing the recount3 files in the cache
* `recount3_cache_rm()` for deleting the recount3 cached files

## R

> Internal functions are not usually @exported and are only available in the
package environment (annotation_ext, annotation_options, etc).

I haven't changed this. I'm not sure if others will want to check these functions, and since I already documented them, I think that it doesn't hurt to export them.

> rtracklayer::import will be moved to BiocIO AFAIU

Discussed previously.

> Provide a verbose = FALSE option for the user in functions like
R/create_rse_manual.R.

Done =) And it's set by an option, so the user could configure this globally on the ~/.Rprofile if they wanted to. I do think that the messages can be informative, so the default is set to TRUE. They are particularly informative when working with exons or larger files, such that the user can know that something is happening.

> Consider using a helper function for the stopifnot messages in
R/create_rse_manual.R.

We have several `stopifnot()` parts in the function, so it felt like too much extra work to add several helper functions: one per `stopifnot()` case. If they were all sequential and next to each other, I would do make the single helper function.

> If possible, create an abstraction layer for the bfc argument that allows
a user to set their own cache location via path rather than using a BFC object.
Package specific cache locations can be set using
tools::R_user_dir("recount3", "cache") (optional).

Done =)

> file_list should have a sensible default for the url argument and
avoid checking the users files to ensure 'purity'. The user should use
list.files directly.
file_list should also access a file that lists all the data available
rather than 'scraping' the website to see what's available. This file would
have to be generated on the server end rather than the client end.

I removed `file_list()`. It was useful with the test site we had, but it's no longer useful with the data hosted at IDIES. I do agree that it will be useful to have a file that lists all the files at IDIES and that's something that my collaborator (Chris Wilks) is going to generate at some future point.

> When downloading data to local computer, the package should manage the
user's downloaded data using BiocFileCache so that they shouldn't have to
enter a 'file path' for the url argument. A convenience function would
tell them what data is already downloaded.

I added the convenience function you suggested =)

> I'm not sure how match.arg works with non-vector choices in
'match.arg(project_home)'

It is a vector choice because `project_home = project_homes()` in the function definition, and `project_homes()` returns a character vector. So it behaves like you would expect it to.

> Is the fread dependency needed? Perhaps, it can be a suggests?
(R/read_counts.R)

I know... yet we found in several tests that it was much faster at reading the data than other functions, and since this is run for the main `create_rse()` function every time (except for exon-exon junctions which is a rarer use case), it feels best to leave it as a dependency.

Minor:

> Perhaps a Reduce(merge(...)) can replace the merging of metadata in
R/read_metadata.R. If metadata files are consistent then maybe use
do.call(rbind(...)).

Nice! Thanks for the tip =) The metadata is not necessarily consistent, hence the `merge()` calls.

## pkg directory

> There's a dev folder there. Perhaps move it to inst/scripts/* or put it
somewhere else?

Resolved in our prior discussion.

## tests

> Add more tests :)

A big TODO!! 

## man

> I am not sure if image files should go in the man folder. Are they used
for the vignettes?

Also resolved.

**Comment by lcolladotor** [comment]
Hi Marcel @LiNk-NY,

I've now added several tests bringing the test coverage up to 87% ^^.

Best,
Leo

**Comment by LiNk-NY** [comment]
Hi Leo, @lcolladotor 
Thanks for following up and making those changes!
I had a quick look and they look great! 
Your package has been accepted. 
Best,
Marcel

**Comment by lcolladotor** [comment]
Awesome, thanks again Marcel for the great review! ^^

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lcolladotor.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("recount3")`. The package 'landing page' will be created at

https://bioconductor.org/packages/recount3

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
