### ISSUE TITLE
megadepth

### ISSUE THREAD

**Issue by dzhang32** [Bioconductor/Contributions#1696]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LieberInstitute/megadepth

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dzhang32** [comment]
Hi Bioconductor, 

Just want to add, could you please give @lcolladotor commit permissions as well to megadepth? 

Thanks!

**Comment by dzhang32** [comment]
AdditionalPackage: https://github.com/dzhang32/dasper

We understand that we should make this comment later in the submission process [1], but wanted to let you know that this is submission involves two packages given the Bioconductor deadline (today) for new packages. 
[1] https://github.com/Bioconductor/Contributions#submitting-related-packages

**Comment by lcolladotor** [comment]
Hi BioC,

Just as a heads up, `megadepth` imports the new package `cmdfun` that was announced recently at https://twitter.com/NystromSpencer/status/1308460885900513280?s=20. I met Spencer @snystrom during BioC2020 and from personal communication with him, we know that CRAN is reviewing his package as of right now. 

Currently `cmdfun` is thus only available from GitHub at https://snystrom.github.io/cmdfun/ but will be on CRAN shortly. If it doesn't happen soon, we'll edit `megadepth` accordingly. If it helps, you can see our `biocthis` GitHub actions test results at that use `snystrom/cmdfun` from GitHub

* https://github.com/LieberInstitute/megadepth/actions
* https://github.com/dzhang32/dasper/actions

Best,
Leo

**Comment by mtmorgan** [comment]
it confuses our build system to introduce dasper before the underlying package has been added; this is why we provide guidance against this practice. I have remove the comment that adds the package

**Comment by lcolladotor** [comment]
Sorry about the comment issue Martin!

To get `megadepth` working on the SBP, I temporarily added the `cmdfun` code with permission from @snystrom. I don't have permissions to push to the update though to `git.bioconductor.org`, so I've asked David to do it in the meantime.

Thanks again and have a good weekend!

Best,
Leo

```
$ git remote -v
origin	git@github.com:LieberInstitute/megadepth.git (fetch)
origin	git@github.com:LieberInstitute/megadepth.git (push)
upstream	git@git.bioconductor.org:packages/megadepth.git (fetch)
upstream	git@git.bioconductor.org:packages/megadepth.git (push)
$ git push upstream
FATAL: W any packages/megadepth l.collado-torres DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dzhang32** [comment]
AdditionalPackage: https://github.com/dzhang32/dasper

**Comment by snystrom** [comment]
Just commenting to confirm Leo's got my permission to incorporate the **cmdfun** source. 👍

**Comment by lshep** [comment]
Please also fix dasper to Build/check without error/timeout.

**Comment by dzhang32** [comment]
Hi @lshep, 

I'm currently on leave at until Thursday but will try and sort out the build/check errors for dasper as soon as I'm back. 

Thanks, 

David

**Comment by lcolladotor** [comment]
Hi @nturaga,

Can you give me (svn username `l.collado-torres`) write permissions to update `megadepth`? Thanks! I made a few changes to it that I wanted to check on the SBP.

Best,
Leo

**Comment by nturaga** [comment]
> Hi @nturaga,
> 
> Can you give me (svn username `l.collado-torres`) write permissions to update `megadepth`? Thanks! I made a few changes to it that I wanted to check on the SBP.
> 
> Best,
> Leo

Done!  You can try now.

**Comment by lcolladotor** [comment]
Thanks Nitesh! I just tested it and the push went through =) Thanks again!

**Comment by nturaga** [comment]
No problem at all.

**Comment by nturaga** [comment]
# Review megadepth

## DESCRIPTION 

ok

## NAMESPACE 

ok

## man

ok

## vignette

ok

## R 

- ok!

- Only reservation I have is, I cannot check the install_megadepth() function myself. But it seems to look good. I think it passes on all the different platforms on the SPB.

- Code looks good to me.

# Review dasper

## DESCRIPTION 

ok

## NAMESPACE

ok

## R

- Package uses basilisk well.

- Some small issues,

```
 NOTE: Usage of dontrun{} / donttest{} found in man page examples.
      57% of man pages use one of these cases.
      Found in the following files:
        coverage_process.Rd
        junction_process.Rd
        outlier_process.Rd
        plot_sashimi.Rd
```

**Comment by lcolladotor** [comment]
Hi Nitesh,

Regarding `megadepth`'s `install_megadepth()` can you let me know a bit more about how you cannot check the function?

In case it helps, I'll explain a bit more about it. We used the same type of framework that is used to install Hugo in `blogdown` at https://github.com/rstudio/blogdown/blob/master/R/install.R. That is, `install_megadepth()` finds the latest release of `Megadepth` ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L51-L54) and [here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L87-L94)) from https://github.com/ChristopherWilks/megadepth/releases where Christopher Wilks @ChristopherWilks provides 3 binaries we use: one for macOS, one for Windows and one for Linux ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L61-L67)). `install_megadepth()` then downloads the binary file to a temporary location ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L69-L78)), then it sets the exectable permissions on macOS and Linux ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L80-L82)), and finally it copies the executable to it's home ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L84) and [here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L97-L114)) that depends on the operating system ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L116-L133)). So for you, which I think you are a Linux user, it would be `~/bin` by default unless you control it with the option `megadepth.dir` ([here](https://github.com/LieberInstitute/megadepth/blob/master/R/install.R#L118)).

Best,
Leo

**Comment by dzhang32** [comment]
Hi Nitesh, 

Thanks for your feedback on `dasper`. The reason I've chopped out certain sections of the Roxygen examples using `donttest{}` is to save time for the R CMD Check to be under the required 10mins. I will try to reduce the testing run-time in order to have more time for the examples.

Best, 

David

**Comment by dzhang32** [comment]
Hi Nitesh, 

Just to add, I'll aim to reduce the percentage of examples that are not tested tonight. There's a chance that some examples will take more time, but I'll be sure to work on these as part of the BioC 3.13 release. 

Thanks again, 

David

**Comment by dzhang32** [comment]
Hi Nitesh, 

I have reduced the % of man pages in `dasper` with `dont_test{}` from 57% to 14%. I've kept `dont_test{}` in use for the function `outlier_process` to reduce the run time of R CMD Check. To tease out more time from the tests/examples will take longer. Would this be okay for the BioC 3.12 release? I will continue to work on `outlier_process()` for the BioC 3.13 in future. 

Thanks, 

David

**Comment by dzhang32** [comment]
Sorry, reopening this. Accidentally clicked close and comment.

**Comment by dzhang32** [comment]
Hi Nitesh, 

Just wanted to mention, the last remaining `warning` on the `dasper` build report is regarding the `configure` file not having executable permissions. This `configure` file is generated following `basilisk` set-up instructions (http://www.bioconductor.org/packages/release/bioc/vignettes/basilisk/inst/doc/motivation.html#creating-environments) and when checking, does look to have read + executable permissions: 

```
ls -lh con*
-rwxr-xr-x  1 DZ_laptop  staff   120B 16 Oct 17:07 configure
-rwxr-xr-x  1 DZ_laptop  staff   137B 16 Oct 17:07 configure.win
```

I am not sure why this Windows-specific `warning` would occur and was wondering whether this a known issue or if you have any suggestions as to how to solve this? 

Best, 

David

**Comment by nturaga** [comment]
Can you please issue a new build report ASAP? We can try and get it in this release. But I'll have to review the changes.

Nitesh

**Comment by dzhang32** [comment]
Hi Nitesh, 

Thanks for confirming on the Windows warning. 

Sure, I've just updated the `dasper` version number to trigger a new build. I hope we can get it in this 3.12 release, thanks again! 

Best, 

David

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dzhang32.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("megadepth")`. The package 'landing page' will be created at

https://bioconductor.org/packages/megadepth

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dzhang32.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dasper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dasper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
