### ISSUE TITLE
musicatk

### ISSUE THREAD

**Issue by achevali** [Bioconductor/Contributions#1701]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/campbio/musicatk

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment]
Hello @achevali - 

In order for me to proceed with my review of the package, all ERRORs must be cleaned from the build report. A major issue seems to with a dependency, BAGEL is not a Bioconductor or CRAN package and therefore is not available. Please address the ERRORs and once a clean build is produced I can review the package.

Keep in mind that the deadline to accept new packages into the Bioconductor 3.12 release is 10/21. Any packages accepted after this date will be included in the next release.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
Hello @achevali -

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

Keep in mind that the deadline to accept new packages into the Bioconductor 3.12
release is 10/21. Any packages accepted after this date will be included in the
next release.

## DESCRIPTION

- [ ] REQUIRED: The Description field in the DESCRIPTION is made up by less 
than 3 sentences. Please expand this field and structure it as a full paragraph.

- [ ] SUGGESTION: Since you are using a standard license, I don't think you need 
to include 'file LICENSE' in the DESCRIPTION file or the LICENSE file in your 
package. I think you can just put 'LGPL-3' in the 'License:' field.

- [ ] REQUIRED: 'LazyData:' should be set to 'FALSE'. It is our experience that 
having this field set to 'TRUE' can slow down the loading of packages, 
especially if they contain data.

- [ ] REQUIRED: Under 'Depends:' there is a trailing ',' after NMF that should 
be removed.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        VariantAnnotation

- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with 
the relevant link to Github for reporting Issues.

## Data

- [ ] REQUIRED: The data in this package needs some attention. Please read our 
documentation [here](https://bioconductor.org/developers/package-guidelines/#data) 
about including data in the package. The 'data/' directory and the accompaning 
documentation is correct, but we do not allow the use of 'data-raw/' or 
'inst/testdata/'. These directories and their content will need to be 
re-organized based on our guidelinesi, most likely into an 'inst/extdata' 
directory. There should be accompanying documentation for these data files as 
well. 

## Vignettes

- [ ] REQUIRED: Line 81, the inline code is not formatted properly here. There 
should be \` \` around available.genomes() and select_genome(). The 
\`\`\`  \`\`\` is for code chunks.

- [ ] REQUIRED: Line 138, the same thing as above. It should be \`proprotional = 
TRUE \`  not \`\`\`proprotional = TRUE \`\`\`.

## Man pages

- [ ] REQUIRED: Use accessors; don't access S4 class slots via `@` in
examples / vignettes. Found `@` in man/add_variant_type.Rd.

- [ ] REQUIRED: Add runnable examples to the following man pages which document 
exported objects:
        add_flank_to_variants.Rd
        extract_count_tables.Rd

- [ ] SUGGESTION: For any of the non-exported functions that are documented 
(like table_96) I would suggest adding the `@keywords internal` tag to the 
documentation. This will remove the function from the documentation index.

## R code

- [ ] REQUIRED: We do not allow for seed usage in R code.

- [ ] REQUIRED: Avoid the use of direct slot access with `@` or `slot()`. 
Accessor methods should be created and utilized instead.

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` instead. Found in files:
        discovery_prediction.R, line 165 and 488

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()`. Found in files:
        discovery_prediction.R, line 456
        load_data.R, line 448
        plotting.R, lines 209 and 397
        standard_tables.R, lines 297, 452, 457, 535, 554, 580, and 586

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 100 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 2039 lines that are not.

Best,
Kayla

**Comment by achevali** [comment]
@Kayla-Morrell Thank you Kayla! Quick question about no seed in R code. I'm using a separate system with withr::with_seed() instead of set.seed(). It doesn't affect the user seed, only for the function being run itself. Should I remove this and let users do it themselves or could I set it to not be used by default? Thank you again!

**Comment by Kayla-Morrell** [comment]
@achevali  - We prefer for it to be removed and let users do it themselves. Thanks for clarifying!

**Comment by achevali** [comment]
I updated with a push that should address all the comments except for the last two suggestions. Just an fyi: nmf and lda have their own seed parameters, so a few of our functions retain pass-throughs to their function calls, but we don't do any seed-setting in the package (other than examples for users).

**Comment by achevali** [comment]
@Kayla-Morrell The latest build passed and I believe I've addressed all the required changes and most of the suggested ones. I would appreciate another review.

**Comment by Kayla-Morrell** [comment]
@achevali - Thank you for making the necessary changes. I still have one note that didn't seem to get addressed.

## R code

- [ ] REQUIRED: There still seems to be quite a bit of `@` use to directly access slots. You should create accessor methods and use them instead. This applies not only to the example code but the actual R code as well (or at least for any function that will be exported to the user).

**Comment by achevali** [comment]
Thank you! I'll go through and make that change.

**Comment by achevali** [comment]
@Kayla-Morrell Is it recommended to use S4 generic methods? (e.g.)
`setGeneric("variants", function(x) standardGeneric("variants"))
setGeneric("variants<-", function(x, value) standardGeneric("variants<-"))

setMethod("variants", "musica", function(x) x@variants)
setMethod("variants<-", "musica", function(x, value) {
  x@variants <- value
  x
})`

or standard functions:
`get_variants <- function(musica) {return(musica@variants)}`
`set_variants <- function(musica, variants) {musica@variants <- variants; return(musica)}`

**Comment by Kayla-Morrell** [comment]
@achevali  - It's recommended to use the S4 generic methods, thank you for clarifying.

**Comment by achevali** [comment]
@Kayla-Morrell I'm submitted a push that I believe addresses the use of @ accession in exported methods, but I'm not getting the notification of a valid push this time. Please let me know if there's anything I'm missing. I want to ensure everything is functional by end of day Wednesday. Thank you!

**Comment by achevali** [comment]
@Kayla-Morrell I'm submitted a push that addresses the use of @ accession in exported methods. I see there's a warning: 
```
* checking whether package 'musicatk' can be installed ... WARNING
Found the following significant warnings:
  Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/RtmpsbTWpO/R.INSTALL1af479dc6803/musicatk/man/pipe.Rd:13: file link '%>%' in package 'magrittr' does not exist and so has been treated as a topic
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1701/251a0f9022ca82fdcd279db1a8f6e591258da78a/musicatk.Rcheck/00install.out' for details
```
I didn't get this warning on previous builds, I'm hoping you can advise. Thank you!

**Comment by achevali** [comment]
I've attempted to address it and done a some research. I believe it's an issue with Magrittr and Windows.

**Comment by Kayla-Morrell** [comment]
@achevali - I believe the warning can be ignored for now. I've looked over the changes and they look good. I'm more than happy to accept the package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/achevali.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("musicatk")`. The package 'landing page' will be created at

https://bioconductor.org/packages/musicatk

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by achevali** [comment]
@mtmorgan Hi Martin. I don't see musicatk yet on the latest 3.12 devel, is this build still in progress? Thank you!
