### ISSUE TITLE
cfDNAPro

### ISSUE THREAD

**Issue by hw538** [Bioconductor/Contributions#1706]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hw538/cfDNAPro

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
The deadline for adding packages to the Bioc 3.12 manifest for the October 28 release is tomorrow. It would be great to see these minor improvements made and the package be included.

**Comment by hw538** [comment]
Hello Ishep,
thanks a lot for your suggestions and the kind reminder about the deadline. 
I have resolved these minor issue. Looking forward to your response and also wish my package could be released in this release. 

 # DESCRIPTION
 * [x ]  we recommend LazyData: true be remove from the DESCRIPTION file. We have rarely found it useful and that it can actually slow the installation process.
 * [x ]  We warn against static data like date that can easily be forgotten about
   and not updated when making changes to the package.
 **my Response: removed these two parts from DESCRIPTION.**
 # Tests
 * [x ]  We strongly recommend unit tests
 **my Response: Added unit tests.**

 # inst
 * [x]  For the description of data creation, can you include the source information for ` urine samples as input.` and `blood samples as input.`.
 **My Response: I updated the example dataset, and added the source information, ie. the link the paper publishing these data.**

 # vignette
 * [x]  I recommend having at least one vignette that gives an overview of the package or the other vignettes. It is more intuitive for a naive user to do vignette("cfDNAPro") to look for help or guidance.

**My Response:  Thank you for the suggestion, I directly added an overview of the package functions in the vignette, and then changed the vignette name to "cfDNAPro", which is more straightforward for naive users.**

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hw538.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cfDNAPro")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cfDNAPro

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by hw538** [comment]
Hi Bioconductor maintainer, my cfDNAPro packaged has been removed from bioconductor due to some reason, Now I am ready to RE-submit it, how should I do re-submission?

(ps. I tried to submit it again, but the bot directly closed the new issue claiming that 'cfDNAPro' has been submitted before)

#2121

**Comment by lshep** [comment]
ok.  The database has been updated.  Please try opening a new issue. It should not automatically close it

**Comment by hw538** [comment]
> ok. The database has been updated. Please try opening a new issue. It should not automatically close it

thanks, already re-submitted just now.
