### ISSUE TITLE
Package submission RnaSeqSampleSize

### ISSUE THREAD

**Issue by slzhao** [Bioconductor/Contributions#1708]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/slzhao/RnaSeqSampleSize

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
A reviewer has been assigned to your package. Learn [what to expect][2]
during the review process.

**IMPORTANT**: Please read [this documentation][1] for setting
up remotes to push to git.bioconductor.org. It is required to push a
version bump to git.bioconductor.org to trigger a new build.

Bioconductor utilized your github ssh-keys for git.bioconductor.org
access. To manage keys and future access you may want to active your
[Bioconductor Git Credentials Account][3]

[1]: https://bioconductor.org/developers/how-to/git/new-package-workflow/
[2]: https://github.com/Bioconductor/Contributions#what-to-expect
[3]: https://git.bioconductor.org/BiocCredentials

**Comment by lshep** [comment]
Thank you for your re-submission.  Please see the following comments that should be addressed.  

# General

- [ ] Fix ERROR/WARNING/NOTE of build report

- [ ] `git rm` the system files picked up on build report

- [ ] Bioconductor strongly emphasizes interoperability. Considering some
  functions take in a data matrix of rna count values, these functions should also be able
  to take in a SummarizedExpeirment object; the standard Bioconductor object for
  count matrices


# README

- [ ] Include Bioconductor installation instructions


# DESCRIPTION

- [ ] Update Author/Maintainer to use Author@R

- [ ] We recommend not using `LazyData: true` this has rarely proved useful and
  can actually slow installation

# Unit tests

- [ ] We highly recommend adding unit tests


# Vignette

- [ ] `git rm` pdf version of vignette. Vignettes should be compiled
  interactively in the build process




# R / man

_General_

- [ ] Fix the NOTES in the build report concerning coding style for removal of sapply and 1:...

- [ ] set.seed should never be manually set inside a function. The function
  set.seed itself really should never be called within a function but rather
  directly before calling the function of interest.  Please remove from intenral
  code.

- [ ]  Remove placeholder TODO: add comments

- [ ] switch all dontrun to donttest. I'm curious as to why these are necessary
  in the first place. Whenever possible functions, especially exported
  functions, should be run. The function does not take very long to run as
  written so it should be executed.

- [ ] Removed commented out code in all functions


_zzz.R_

- [ ] you can git rm this file indicating deprecation

_uniroot.R_


- [ ] Use message instead of print


_sampleSize.R_

- [ ] sample_size function: Why is lambda0AppCut hard coded at 2000?

- [ ] sample_size_distribution: Similar why is start.point, end.point,
  step.power hard coded to those specific values?

_optimize.R_

- [ ] remove dontrun.

_model.R_

- [ ] Use message instead of cat/print

_estPower.R_

- [ ] Remove TODO code from inline


When the issues have been addressed, don't forget to version bump the z of version x.y.z  and push to Bioconductor as described [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/).  Please also comment with what has been addressed  or answers to the questions above when requesting the re-review.

**Comment by slzhao** [comment]
Thanks so much for your suggestion and comments. I’ve fixed all error and
warning, and most of notes. I have some questions:

1.     I have pushed the package to github but have some troubles in git
push the package to Bioconductor. The error message is “FATAL: W any
packages/RnaSeqSampleSize s.zhao DENIED by fallthru”. I did some google
search but didn’t find a solution. May I know if there is any way to fix
this?

2.     My another data package, RnaSeqSampleSizeData (which is used by this
package) was indicated to be removed in next version. Is there any way I
can make it back?



Answers for each question listed below with highlights.



*General*

·  Fix ERROR/WARNING/NOTE of build report (Fix all ERROR/WARNING and most
of NOTE)

·  git rm the system files picked up on build report (Done)

·  Bioconductor strongly emphasizes interoperability. Considering some
functions take in a data matrix of rna count values, these functions should
also be able to take in a SummarizedExpeirment object; the standard
Bioconductor object for count matrices (This package doesn’t have much
interface with Rna-Seq raw count data. The only related function is
est_count_dispersion and it is highly related to edgeR and used similar
codes. I am working on next version of this package which will use more
Rna-Seq count tables and I will include support for SummarizedExpeirment.)

*README*

·  Include Bioconductor installation instructions (Done)

*DESCRIPTION*

·  Update Author/Maintainer to use Author@R (Done)

·  We recommend not using LazyData: true this has rarely proved useful and
can actually slow installation (Done)

*Unit tests*

·  We highly recommend adding unit tests (Done)

*Vignette*

·  git rm pdf version of vignette. Vignettes should be compiled
interactively in the build process (Done)

*R / man*

*General*

·  Fix the NOTES in the build report concerning coding style for removal of
sapply and 1:... (May I know if this is required or a suggestion? There are
too many functions with sapply and 1… I am afraid that I may change any of
them mistakenly and make the package not working correctly. I’d rather keep
them as is at this time and change gradually as I am working on next
version of this package)

·  set.seed should never be manually set inside a function. The function
set.seed itself really should never be called within a function but rather
directly before calling the function of interest. Please remove from
intenral
code. (Done)

·  Remove placeholder TODO: add comments (Done)

·  switch all dontrun to donttest. I'm curious as to why these are necessary
in the first place. Whenever possible functions, especially exported
functions, should be run. The function does not take very long to run as
written so it should be executed. (Done)

·  Removed commented out code in all functions. (Done)

*zzz.R*

·  you can git rm this file indicating deprecation (Done)

*uniroot.R*

·  Use message instead of print (Done)

*sampleSize.R*

·  sample_size function: Why is lambda0AppCut hard coded at 2000? This is a
cutoff value by experience to decide use which method for for power
caculation. The est_power_model method is not very accurate but faster when
lambda0 is very large. This won’t change result.

·  sample_size_distribution: Similar why is start.point, end.point,
step.power hard coded to those specific values? This is a sample size
estimation. So start from 1, and end at estimated max value. step.power is
an value by experience (to make it faster) as most sample size estimation
is from 0~200. This won’t change result.

*optimize.R*

·  remove dontrun. (Done)

*model.R*

·  Use message instead of cat/print  Done on “cat”. But I need to “print” a
model result. I don’t think message can do so.

*estPower.R*

·  Remove TODO code from inline (Done)

When the issues have been addressed, don't forget to version bump the z of
version x.y.z and push to Bioconductor as described here
<https://bioconductor.org/developers/how-to/git/new-package-workflow/>.
Please also comment with what has been addressed or answers to the
questions above when requesting the re-review.

**Comment by lshep** [comment]
Thank you. 

1. For not being able to push Bioconductor utilized your github ssh-keys for git.bioconductor.org access. To manage keys and future access you may want to active your [Bioconductor Git Credentials Account](https://git.bioconductor.org/BiocCredentials/login/?next=/BiocCredentials/)

2. I actually already undeprecated knowing this will be moved through yesterday.  The message should be removed on the next experiment data package build. 

We will need to figure out your push access and ability to trigger a new build.  Once that happens I'll review the report one last time and make sure everything is in order.

**Comment by lshep** [comment]
@nturaga /  @mtmorgan   can someone check on the credentials and access for this?

**Comment by mtmorgan** [comment]
I believe the ssh key we know about is correct; can @slzhao use a command like
```
ssh -T -v git@git.bioconductor.org|head
```
For me part of the output contains
```
debug1: Offering public key: RSA SHA256:0RpZuME6fbuZi2a0h7Xb5Zcn4+oMYoCgLYjJuWriNA0 /XXXX/.ssh/id_rsa
debug1: Server accepts key: pkalg rsa-sha2-512 blen 149
debug1: Authentication succeeded (publickey).
```
where I learn that ssh is trying (and succeeding) to use the key in my home directory at `~/.ssh/id_rsa`. If the wrong key is being used, I think FAQ#15 here https://bioconductor.org/developers/how-to/git/faq/ will help.

**Comment by slzhao** [comment]
Thank you! I only have one ssh key so I don't think it is a wrong key issue.
More information listed below:

*git config --list|grep upstream*
remote.upstream.url=git@git.bioconductor.org:packages/RnaSeqSampleSize.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*

*git pull upstream master*
From git.bioconductor.org:packages/RnaSeqSampleSize
 * branch            master     -> FETCH_HEAD
Already up to date.

*ssh -T -v git@git.bioconductor.org <git@git.bioconductor.org>|head*
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\shili/.ssh/config
debug1: Connecting to git.bioconductor.org [34.192.48.227] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\shili/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_ed25519-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_xmss type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\shili/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2
Ubuntu-4ubuntu2.10
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.10 pat OpenSSH* compat
0x04000000
debug1: Authenticating to git.bioconductor.org:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC:
<implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC:
<implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256
SHA256:nXILc5fVCnDfOID8HgPi+mSufGtr2JMYgnRa1JAQj/Q
debug1: Host 'git.bioconductor.org' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\shili/.ssh/known_hosts:10
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or
directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA
SHA256:IRzHUdi7eKAJPKA2u5OHE6QkXBAzNd3R5xtuz0aDF+w
C:\\Users\\shili/.ssh/id_rsa
debug1: Server accepts key: pkalg rsa-sha2-512 blen 533
debug1: Authentication succeeded (publickey).
Authenticated to git.bioconductor.org ([34.192.48.227]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com
want_reply 0
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
hello s.zhao, this is git@ip-172-30-0-33 running gitolite3
v3.6.6-6-g7c8f0ab on git 2.28.0

 R      admin/..*
 R      packages/..*
 R      admin/BiocManager
 R      admin/bioconductor.org
 R      admin/hook_maintainer
 R      admin/manifest
 R      packages/ABAData
 R      packages/ABAEnrichment
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3408, received 65648 bytes, in 1.5 seconds
Bytes per second: sent 2238.2, received 43113.7
debug1: Exit status 0

**Comment by mtmorgan** [comment]
aargh I think it was 'our' (i.e., my) problem; please try again.

**Comment by slzhao** [comment]
This works now. I've pushed the updates to BIioconductor server.
Thank you very much!

Best,
Shilin

**Comment by nturaga** [comment]
Did that work?

**Comment by slzhao** [comment]
Yes. Works now! Thank you!

Best,
Shilin

**Comment by slzhao** [comment]
More updates:
If using *ssh -T -v *git@git.bioconductor.org to show all packages in the
server, I can find:

R W    packages/KEGGprofile
R        packages/RnaSeqSampleSize
R W    packages/RnaSeqSampleSizeData

I can write the other two packages that I am working with but not
RnaSeqSampleSize. So I believe this is a server setting issue which needs
to give me the write permission on RnaSeqSampleSize.
Thanks!

Best,
Shilin

**Comment by mtmorgan** [comment]
But you said that this 'works'? I'm confused. Is this that you are able to write to 'master' (devel), but not RELEASE_3_11?

**Comment by lshep** [comment]
It seems like you were able to write, as indicated by the triggered build command and message that you had successfully pushed.

**Comment by slzhao** [comment]
I mean I have succeeded pushing the changes to BioC server. Everything is
good now. Sorry for the confusion.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/slzhao.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RnaSeqSampleSize")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RnaSeqSampleSize

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
