### ISSUE TITLE
ReactomeContentService4R

### ISSUE THREAD

**Issue by chilampoon** [Bioconductor/Contributions#1709]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reactome/ReactomeContentService4R

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by chilampoon** [comment]
The error from the Windows builder is raised by this issue https://github.com/ropensci/magick/issues/283
I may put the example under `\dontrun` till the next release of magick.

**Comment by chilampoon** [comment]
Hi @mtmorgan, may I ask what changes should I make to complete the submission? It's over one month since I opened this issue... Thanks.

**Comment by mtmorgan** [comment]
Sorry, I'll try to complete the review in the next few days.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Probably no need to start the title with 'R', since that's the language we're working in!

- Use `License: Apache License 2.0`

vignettes

- Looks good, thanks!

R (specific comments are meant to apply generally)

- a good practice is to start every exported function with argument validity checks, for instance using simple `stopifnot()` clauses.

- exporters.R:42 use `message()` (prints to stderr) rather than `cat()` (prints to stdout) for informational messages. Usually, `cat(paste(...))` can be replaced by `message(...)` (no need to `paste0()` arguments; this is done within `message()` / `warning()` / `stop()`)

- getContent.R:193 adopt a more line-oriented formatting convention for increased readability, e.g.,

    ```
    if (participants[participants$peDbId == list, ]$type == 0) 
        participants[participants$peDbId == list, ]$type <- component
    ```

- getContent.R:204 think carefully about vectorization versus iteration, e.g., the test can be hoisted outside the loop. Also, for both legibility and efficiency avoid re-computing the same index repeatedly

    ```
    id0 <- id %in% participants$peDbId
    for (i in id0) {
        idx <- participants$peDbId == i
        tmp.type <- participants[idx, ]$type
        ...
    ```

- getContent.R:254 I'm not sure that `file.path()` is the correct solution for constructing URLs, e.g., on Windows I think this produces paths separated by `\\`.

- utils.R:5 using `.onAttach()` means that the option is only set when the package is attached to the search path, e.g., library(...). If a package were to _import_ your package, then the option would not be set. Use `.onLoad()` for this part of the set-up.

- utils.R:26 no need to use `paste0()` here or subsequently.

NEWS.md / tests

- Doesn't look like you're not keeping up-to-date with these files / directories; delete if it is only a show of good intention.

**Comment by chilampoon** [comment]
@mtmorgan Thanks!

Some concerns:

> * Use `License: Apache License 2.0`

If using `License: Apache License 2.0`, `R CMD CHECK` will have a note, that's why I kept `file LICENSE`...
```
note: 
   File
     LICENSE
   is not mentioned in the DESCRIPTION file.
```

> * a good practice is to start every exported function with argument validity checks, for instance using simple `stopifnot()` clauses.

Actually most exported functions have the argument checks, some of them seem not because helper functions can help send more informative errors than those from `stopifnot()`, for instance:
```
getEventsHierarchy(main.species = 'dog')
#> Error: dog not listed in Reactome

query(id=12345)
#> Warning: HTTP 404 - Id: 12345 has not been found in the System
#> NULL
```

> * getContent.R:254 I'm not sure that `file.path()` is the correct solution for constructing URLs, e.g., on Windows I think this produces paths separated by `\\`.
I think it's OK. 
From `?file.path`: `The components are by default separated by / (not \) on Windows.`

> * utils.R:5 using `.onAttach()` means that the option is only set when the package is attached to the search path, e.g., library(...). If a package were to _import_ your package, then the option would not be set. Use `.onLoad()` for this part of the set-up.

I used `.onAttach()` because there would be a note in `R CMD CHECK` if using `.onLoad()`:
```
  File ‘ReactomeContentService4R/R/utils.R’:
    .onLoad calls:
      packageStartupMessage("Connecting...", appendLF = FALSE)
      packageStartupMessage("welcome to Reactome v", version, "!")
  
  See section ‘Good practice’ in '?.onAttach'.
```
If I use `.onAttach()` and `message()` instead of `packageStartupMessage()`, also a note...
```
  File ‘ReactomeContentService4R/R/utils.R’:
     .onLoad calls:
       message("Connecting...", appendLF = FALSE)
       message("welcome to Reactome v", version, "!")
   
   Package startup functions should use ‘packageStartupMessage’ to
     generate messages.
   See section ‘Good practice’ in '?.onAttach'.
```

> NEWS.md / tests
> 
> * Doesn't look like you're not keeping up-to-date with these files / directories; delete if it is only a show of good intention.

I deleted tests, but I want to keep the NEWS

Others are done.

**Comment by chilampoon** [comment]
@mtmorgan could you help update the `magick` package version in machv2? Thanks!

**Comment by mtmorgan** [comment]
Use

```
License: Apache 2.0 | file LICENSE
```

Separate `.onLoad()` to satisfy to set the option. Use `.onAttach()` and `packageStartupMessage()` to display a package startup message (but do you need to display a startup message? the user knows what they just did...).

We use mac binaries provided by the CRAN team; if there isn't a recent version, then we don't install it specially. Usually the strategy is, unfortunately, to wait until an updated binary is available from CRAN.

**Comment by chilampoon** [comment]
> Use
> 
> ```
> License: Apache 2.0 | file LICENSE
> ```

OK, I tried all possible combinations and finally found that the correct one is `Apache License (>= 2.0) | file LICENSE`, the others are neither standardizable nor permitted...

> Separate `.onLoad()` to satisfy to set the option. Use `.onAttach()` and `packageStartupMessage()` to display a package startup message (but do you need to display a startup message? the user knows what they just did...).

Yes... sending that startup message can 1) check the connection to the server; 2) tell the database version

> We use mac binaries provided by the CRAN team; if there isn't a recent version, then we don't install it specially. Usually the strategy is, unfortunately, to wait until an updated binary is available from CRAN.

Gotcha

**Comment by chilampoon** [comment]
> Use
> 
> ```
> License: Apache 2.0 | file LICENSE
> ```
> 
> Separate `.onLoad()` to satisfy to set the option. Use `.onAttach()` and `packageStartupMessage()` to display a package startup message (but do you need to display a startup message? the user knows what they just did...).
> 
> We use mac binaries provided by the CRAN team; if there isn't a recent version, then we don't install it specially. Usually the strategy is, unfortunately, to wait until an updated binary is available from CRAN.

Hi @mtmorgan, when will the binary be updated? isn't the `magick` package version on CRAN 2.5.2 (https://cran.r-project.org/web/packages/magick/index.html) > the requirement (2.5.1)? 
And any more necessary changes for this package? Thank you.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/chilampoon.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ReactomeContentService4R")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ReactomeContentService4R

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
