### ISSUE TITLE
preciseTADhub

### ISSUE THREAD

**Issue by stilianoudakis** [Bioconductor/Contributions#1725]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dozmorovlab/preciseTADhub

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
@LiNk-NY and @stilianoudakis   The data has been added to the hubs in devel 3.13.  The single package builder has not updated to run on 3.13 yet as we normally wait a week to make sure any issues around the release don't stem from the addition of the single package builder and are isolated to purely the builders release update.   Until  the SPB switches to use 3.13,  you will have to build/check manually as the builders will not find the data in the hubs since it is limited to data for 3.12.   We hope to have them switched later next week but wanted to give the heads up to expect the ERROR.   Sorry for the temporary inconvenience.  Cheers

**Comment by LiNk-NY** [comment]
Hi Spiro, @stilianoudakis 

Thank you for your submission. Please see the short review below. 

Best,
Marcel 

---

# preciseTADhub #1725

## DESCRIPTION

* Provide more details in the `Description` field for users. This helps them
identify the purpose of the package.
* It looks like `preciseTAD` should be in the `Suggests:` field
* Why suggest `BiocCheck` and `BiocManager`?
* Include a `BugReports` link and a `URL` pointing to the GitHub page for
users.

## vignette

* What is the purpose of using a width of 400?
* Include an `Installation` section in the vignette (usually at the top).
* It would be good to have a small wrapper function to avoid the 'manual'
calls to `ExperimentHub`. This makes it easier for the users.
* Include some details about what is contained in the
`CHR1_GM12878_5kb_Arrowhead` object

**Comment by LiNk-NY** [comment]
Hi Spiro, @stilianoudakis 
Please respond to the review line by line. Thank you.

**Comment by stilianoudakis** [comment]
Hi Marcel,

I have addressed each of the comments below from your previous review:

DESCRIPTION


   - Provide more details in the Description field for users. This helps
   them
   identify the purpose of the package. (added)
   - It looks like preciseTAD should be in the Suggests: field (added)
   - Why suggest BiocCheck and BiocManager? (removed)
   - Include a BugReports link and a URL pointing to the GitHub page for
   users. (added)

VIGNETTE


   - What is the purpose of using a width of 400? (it was not necessary,
   removed)
   - Include an Installation section in the vignette (usually at the
top). (added
   this and more)
   - It would be good to have a small wrapper function to avoid the 'manual'
   calls to ExperimentHub. This makes it easier for the users. (added in
   vignette)
   - Include some details about what is contained in the
   CHR1_GM12878_5kb_Arrowhead object (added in vignette, but also included
   in make-data.R file in /inst/scripts)

 There was a minor error in the last commit I made that caused an error in
the build report. I have since corrected and will push for a new build.

Please let me know if there is anything else that you would like me to
address. Thank you for taking the time to review my package!

Best,

Spiro Stilianoudakis
PhD Candidate | Department of Biostatistics
Virginia Commonwealth University

**Comment by LiNk-NY** [comment]
Spiros, @stilianoudakis 

It would be good to resolve the warnings.

```
* Checking that biocViews come from the same category...
    * WARNING: Use biocViews from one category only (one of Software,
      ExperimentData, AnnotationData, Workflow)
See http://bioconductor.org/developers/how-to/biocViews/
```

The `biocViews` field in the `DESCRIPTION` should say that this is an 
`ExperimentData` package. 

The section in the vignette increasingly points out the need for a wrapper function
in order to increase usability for the user. Imagine a function call like this that a
user can obtain resources with:

```r
> preciselTAD(chr = 1, cell_line = "GM12878", resolution = "*", caller = "*", dry.run = TRUE)
```
_Note_. `*` denotes a wildcard.

|FileName                        | EHID          |
|---------------------------------|---------------|
| CHR1_GM12878_5kb_Arrowhead.rds  |     EH3815    |
| CHR1_GM12878_10kb_Peakachu.rds  |     EH3816    |

IMO, this makes resource discoverability much easier for the user. 

I see that you added a function in the vignette but why not add it to
the package R directory? The `readEH` function is quite similar to
my suggestion above. When `dry.run = FALSE`, provide the resource to the user.

Best,
Marcel

**Comment by lshep** [comment]
Since this is a hub package please also make sure the biocViews includes ExperimentHub.

**Comment by stilianoudakis** [comment]
Hi all,

Thank you for taking the time to review my package!

Just to clarify, previously what I had in the BiocViews was the following:

ExperimentData, ExperimentHub, HiC, Sequencing,  Classification,
FunctionalGenomics

However, I was still getting the warning so I tried taking ExperimentHub
out. But it appears the warning persists. Would you happen to know why that
is? Would simply reverting back to what I had be okay?

Secondly, I am getting conflicting error messages regarding bioc-devel
mailing list subscription. I have had a package recently accepted onto
Bioconductor with the same authors and maintainer, and there was never an
error. Is this something that can be ignored for now? If not, would you
happen to know how it can be fixed, because I am certain that we are both
subscribed.

I will work on the other suggestion, but what to float this by in the
meantime. Thanks again!

Best,

Spiro

**Comment by LiNk-NY** [comment]
Hi Spiro, @stilianoudakis 

1. You can follow a path from the tree of terms here: 
http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData

2. If you've used the same email, I wouldn't worry too much about the error.

**Comment by LiNk-NY** [comment]
Hi Spiro, @stilianoudakis 
Thanks for making the change!
Please remove the `dontrun` tag so that you avoid getting the error in the report. 
The package looks ready to go. 
Thanks!

**Comment by LiNk-NY** [comment]
Hi Spiro, @stilianoudakis 
Sorry for the delay in getting back to you. 
I had a quick look at the changes and they look great.
Thanks!
Your package has been accepted. 
Best regards,
Marcel

**Comment by stilianoudakis** [comment]
Hi Marcel,

That's great news! Thanks again for taking the time to review my package!

Best,

Spiro

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stilianoudakis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("preciseTADhub")`. The package 'landing page' will be created at

https://bioconductor.org/packages/preciseTADhub

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
