### ISSUE TITLE
CAEN

### ISSUE THREAD

**Issue by zhangli1109** [Bioconductor/Contributions#1730]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhangli1109/CAEN

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
This was previously submitted as https://github.com/Bioconductor/Contributions/issues/1161, but should be reviewed as a 'new' package because of the long duration between submission and initial revision.

**Comment by zhangli1109** [comment]
Hello @bioc-issue-bot ,
I got a problem, I forget the passwords of the email of maintainer and the Bioconductor Git Credentials account, so I want to change the email address of the Author of this package. However, I cannot push to git.bioconductor.org because I cannot access to Bioconductor Git Credentials account. I don't known how to solve this problem?
Thanks,
zhangli1109

**Comment by zhangli1109** [comment]
hello @mtmorgan,
I got a problem and need your help. I forget the passwords of the email of maintainer and the Bioconductor Git Credentials account, so I want to change the email address of the Author of this package. However, I cannot push to git.bioconductor.org because I cannot access to Bioconductor Git Credentials account. I don't known how to solve this problem?
I tried to close the #1730, and submitted a new issue (#1744) with new email address, but it cannot open a new issue with the same package name. 

Thanks,
zhangli1109

**Comment by lshep** [comment]
@nturaga  can you assist with this?

**Comment by nturaga** [comment]
The email address listed is "2160090406@email.szu.edu.cn". Is this what you would like to continue with??

**Comment by zhangli1109** [comment]
Hi, @nturaga, 
Yes, I would like to continue with email address "2160090406@email.szu.edu.cn".  
Thanks for your help!
Best, Li.

**Comment by nturaga** [comment]
It's surprising that you don't have an account in BiocCredentials. I'll create one for you. You'll have to activate it. Your username is "zhangli1109" and email is the one given. 

Add your SSH keys and then you'll be set.

**Comment by lshep** [comment]
@zhangli1109   -- were you able to activate your git credentials account and able to push to the git.bioconductor.org repository now?

**Comment by zhangli1109** [comment]
Hello @lshep ,
I spent some time to learn how to push to
git@git.bioconductor.org:packages/CAEN to trigger a new build. I think it works well now. Thanks for all of your help!
Best, Li.

**Comment by lshep** [comment]
I'm sorry for the delay.  I am working on your review now and should have it posted later today or tomorrow at the latest.  Sorry for the inconvenience.

**Comment by lshep** [comment]
**Build Report**

- [ ] (Optional) Unit tests. We highly recommend them. While they seem tedious, most maintainers find them useful for debugging and testing

**vignette**

- [ ] Please include a section sessionInfo that runs `sessionInfo()` at the end of your vignette

- [ ] It would be good to show an example with a SummarizedExperiment or SingleCellExperiment Bioconductor object.


**R code**

_General_

- [ ] Your functions should be able to take in a SummarizedExperiment and/or SingleCellExperiment Bioconductor object for interoperability. Please update all functions accordingly


Please update your package accordingly. When ready please do a version bump and push to git.bioconductor.org to trigger a new build.  Then comment back here with a summary of updates addressing the above issues. 

Cheers

**Comment by zhangli1109** [comment]
Hi, @lshep ,
I have updated my package and triggered a new build. In this new version, I have update the following contents，
1. vignette
 Include a section sessionInfo that runs sessionInfo() at the end of the vignette;
Show an example with a SummarizedExperiment Bioconductor object.
2. R code
All functions could be able to take in a SummarizedExperiment  Bioconductor object.
Best, Li

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhangli1109.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CAEN")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CAEN

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
