### ISSUE TITLE
Submit package "mina"

### ISSUE THREAD

**Issue by Guan06** [Bioconductor/Contributions#1733]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Guan06/mina

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Guan06** [comment]
Hi,
I read the build report and the error was caused on Windows, the dependence "doMC" package was not installed successfully on the machine. Maybe the tester could try to install the missing package and build again?

Thanks a lot!

Best,
Rui

**Comment by Guan06** [comment]
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> On one or more platforms, the build results were: "skipped, ERROR".
> This may mean there is a problem with the package that you need to fix.
> Or it may mean that there is a problem with the build system itself.
> 
> Please see the [build report](http://bioconductor.org/spb_reports/mina_buildreport_20201027190434.html) for more details. This link will be active
> for 21 days.
> 
> ** Remember: **if you submitted your package after July 7th, 2020,
> when making changes to your repository push to
> `git@git.bioconductor.org:packages/mina` to trigger a new build.
> A quick tutorial for setting up remotes and pushing to upstream can be found [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/).

Hi,
I read the build report and the error was caused on Windows, the dependence "doMC" package was not installed successfully on the machine. Maybe the tester could try to install the missing package and build again?

Thanks a lot!

Best,
Rui

**Comment by mtmorgan** [comment]
doMC is not available on Windows https://cran.r-project.org/web/packages/doMC/index.html so you must modify your code to (a) move doMC to the Suggests: field of the description file, and use notation such as `doMC::...` when referencing functions from the package. Alternatively, consider implementing your package in a way that the user chooses the appropriate parallel 'back end', or using  a package such as BiocParallel that is available on all platforms.

**Comment by Guan06** [comment]
> doMC is not available on Windows https://cran.r-project.org/web/packages/doMC/index.html so you must modify your code to (a) move doMC to the Suggests: field of the description file, and use notation such as `doMC::...` when referencing functions from the package. Alternatively, (b) consider implementing your package in a way that the user chooses the appropriate parallel 'back end', or using a package such as BiocParallel that is available on all platforms.

I see... Thanks a lot for the clarification! I will try to address this then.

**Comment by Guan06** [comment]
> doMC is not available on Windows https://cran.r-project.org/web/packages/doMC/index.html so you must modify your code to (a) move doMC to the Suggests: field of the description file, and use notation such as `doMC::...` when referencing functions from the package. Alternatively, (b) consider implementing your package in a way that the user chooses the appropriate parallel 'back end', or using a package such as BiocParallel that is available on all platforms.

Hi Martin,

I just updated the package according to your suggestion (a), but still got the error for "R CMD CHECK" on windows, in the report it says "Package suggested but not available: 'doMC'". Is it possible to set " _R_CHECK_FORCE_SUGGESTS_" as "FALSE" during check()? Otherwise I guess I will need to follow the strategy (b).

Thanks a lot for your kindly help!

Best,
Rui

**Comment by mtmorgan** [comment]
I guess (a) was bad advice, sorry about that. It is not possible to set `_R_CHECK_FORCE_SUGGESTS_`. `doMC` could be placed in the `Enhances: ` field, or option (b).

**Comment by Guan06** [comment]
> I guess (a) was bad advice, sorry about that. It is not possible to set `_R_CHECK_FORCE_SUGGESTS_`. `doMC` could be placed in the `Enhances: ` field, or option (b).

No worries at all, thanks very much for your help! I placed `doMC` in the `Enhances:` this time, but for sure will use `BiocParallel` in the future. 

Thanks again and best,
Rui

**Comment by mtmorgan** [comment]
DESCRIPTION

- good!

vignettes

- looks good!

R (comments on specific lines apply generally)

- adj.R:39 it is always better to provide accessors to get and set slots, so that your code is more readable and that you maintain the abstraction of interface and implementation that is a major benefit of object-oriented programming. The accessors do not need to be exported if you do not wish users to use them. Thus

    ```
    .norm <- function(x)
        x@norm
    ...
        out <- rcorr(t(.norm(x)), type = method)
    ```

- adj.R:89 validate user-supplied arguments, e.g,.

    ```
    stopifnot(
        method %in% c(...),
        is.logical(sig),
        ...
    )
    ```
    
- adj.R:183 this looks like it could be vectorized, perhaps with the help of the matrixStats package, as `rowVars(log(x / y))` ? A number of other uses of iteration (`for`, `lapply()`, and parallel variants) seem like they might benefit from similar vectorized computations.

- adj.R:202 Is parallel evaluation necessary here? it seems like this could be written in a vectorized manner?

- adj.R:206 wow, this line looks very unusual! it should never be necessary to make this type of call.

- all_generics.R:44 it looks like this method will only be written to dispatch on the first or second argument; use `signature=...` to simplify dispatch only to the arguments that you expect to have different types and require method dispatch.

- com_dis.R:196 instead of defining a complicated anonymous function at a highly nested level, consider defining a helper function at top level, and using `lapply(samples, .helper_fun)`.

- net_dis.R:312 this 'copy and append' pattern is very ineffieicne if `len` is large; use a 'pre-allocate and fill' pattern, or simply `lapply()`. See http://bioconductor.org/developers/how-to/efficient-code/.

**Comment by Guan06** [comment]
> DESCRIPTION
> 
> * good!
> 
> vignettes
> 
> * looks good!
> 
> R (comments on specific lines apply generally)
> 
> * adj.R:39 it is always better to provide accessors to get and set slots, so that your code is more readable and that you maintain the abstraction of interface and implementation that is a major benefit of object-oriented programming. The accessors do not need to be exported if you do not wish users to use them. Thus
>   ```
>   .norm <- function(x)
>       x@norm
>   ...
>       out <- rcorr(t(.norm(x)), type = method)
>   ```
> * adj.R:89 validate user-supplied arguments, e.g,.
>   ```
>   stopifnot(
>       method %in% c(...),
>       is.logical(sig),
>       ...
>   )
>   ```
> * adj.R:183 this looks like it could be vectorized, perhaps with the help of the matrixStats package, as `rowVars(log(x / y))` ? A number of other uses of iteration (`for`, `lapply()`, and parallel variants) seem like they might benefit from similar vectorized computations.
> * adj.R:202 Is parallel evaluation necessary here? it seems like this could be written in a vectorized manner?
> * adj.R:206 wow, this line looks very unusual! it should never be necessary to make this type of call.
> * all_generics.R:44 it looks like this method will only be written to dispatch on the first or second argument; use `signature=...` to simplify dispatch only to the arguments that you expect to have different types and require method dispatch.
> * com_dis.R:196 instead of defining a complicated anonymous function at a highly nested level, consider defining a helper function at top level, and using `lapply(samples, .helper_fun)`.
> * net_dis.R:312 this 'copy and append' pattern is very ineffieicne if `len` is large; use a 'pre-allocate and fill' pattern, or simply `lapply()`. See http://bioconductor.org/developers/how-to/efficient-code/.

Thanks a lot for all of the comments and suggestions, they are super helpful!

adj.R:39  
I added getter and setter accessors for all the slots and exported the ones that could be interesting for the user to check.

adj.R:89
Added the validation for all user-supplied arguments.

adj.R:183
Here is for each row of `dat_1`, calculate the variance of this row divide each row of `dat_2`, not sure how to vectorize it... a bit tricky since it is not either element-wise nor matrix-wise.

adj.R:202
I think it is might be a good idea to keep the parallel here considering the running time, but you are right that in general I didn't manage to take advantage of vectorization enough to make the codes more efficient...

adj.R:206
Removed, sorry this is completely unnecessary, I added it since in my institute computer cluster, some temporary files were written under this folder when there are errors occurred. 

all_generics.R
Changed detailed arguments to ... to simplify the dispatch.

com_dis.R:196 
I have also considered this option,  the problem here is these functions used a lot of other local parameters, and I didn't manage to pass the function defined at the top level to each parallel core correctly... any suggestion here? highly appreciated! Maybe it is a good idea to rewrite it completely with BiocParallel instead of doMC later...

net_dis.R:312 
Here the group is the condition of compared networks, usually it is not very big (< 20). I tried the `lapply` for this function and the time-consuming part is how to take care of the reformat of output. So I think here it is easier to keep it as for loop. 
I tried to change the `for` loop in another big function `bs_pm()` in `bs_pm.R`, my problem was in each loop, a lot of variables defined outside the loop was used, and with `lapply()`, I would need to pass them as parameters. For example, the `for` loop from line 163 to line 180, variables including  `num_m`, `num_n`, `s_size`, `this_mat_m`, `this_mat_n`, MLST and NLST needed to be taken care. In this case, you think it is still better to use `lapply` or? especially there are `for` loops inside `for` loops like this... 

Thanks a lot for your time and all the comments again!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Guan06.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mina")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mina

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
