### ISSUE TITLE
RLassoCox

### ISSUE THREAD

**Issue by weiliu123** [Bioconductor/Contributions#1738]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/weiliu123/RLassoCox

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by weiliu123** [comment]
I think the error stems from that I added Depends: R (>= 4.1) in the DESCRIPTION file as suggested by BiocCheck. However, if I change to R>3.6, BiocCheck will return a warning "Update R version dependency from 3.6.0 to 4.1." How can I fix this problem?

**Comment by Kayla-Morrell** [comment]
@weiliu123 - The R version dependency issue is due to the fact that the SPB builders haven't yet been updated for the current Bioc and R devel versions. We hope to have this update done by next week. In the mean time, switch the R version to R>3.6 so only a warning is produced and fix all other issues, this will not hold up the review process in any way. We will let you know when you can switch the dependency back to R >= 4.1.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@weiliu123 - Thank you for submitting to _Bioconductor_. Overall this was a very 
well written package. Please see the initial review of the package below. The 
required changes must be made while the suggested changes do not have to be 
(though we strongly encourage them). Comment back here with updates that 
have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The 'inst/doc' directory is not needed and should be removed.

## DESCRIPTION

- [ ] REQUIRED: The R version dependency can now be changed from 3.6.0 to 4.1.

- [ ] REQUIRED: A new check on licenses has been implemented and we don't allow
  liceses to restrict use. It should be an explict version, i.e. GPL-2.

- [ ] REQUIRED: Look over the 'Depends:' field, usually only packages that
  provide essential functionality are listed here. It's unusual to have more
than three packages listed here. Some should be moved to an 'Imports:' field
which is intended for packages that provide functions, methods, or classes for
the package.

- [ ] REQUIRED: The 'BugReports:' link should be to the Issues section of the
  github.

## Data

- [ ] REQUIRED: dgMMirGraph.rda needs to be compressed. See the warning on R CMD
  check.

## Vignette

- [ ] REQUIRED: Under the Installation section, instead of commenting out the
  code you can have this section run as eval = FALSE.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/ for further
help with unit tests.

Best,
Kayla

**Comment by weiliu123** [comment]
@Kayla-Morrell 
Thank you very much for carefully reviewing our package. We have made the following updates：

- We have removed the 'inst/doc' directory.
- The R version dependency was changed from 3.6.0 to 4.1.
- The license was changed to Artistic-2.0.
- Four packages (Matrix, igraph, survival, stats ) were moved to the Imports section.
- The 'BugReports:' link was changed to https://github.com/weiliu123/RLassoCox/issues.
- dgMMirGraph.rda has been compressed.
- We have used "eval = FALSE" under the installation section.

Best,
Wei

**Comment by Kayla-Morrell** [comment]
@weiliu123 - Thank you for making the necessary changes. Everything looks good now and I'm more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/weiliu123.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RLassoCox")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RLassoCox

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
