### ISSUE TITLE
bnem

### ISSUE THREAD

**Issue by MartinFXP** [Bioconductor/Contributions#1740]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MartinFXP/bnem

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi Martin, @MartinFXP 

Thank you for your submission to Bioconductor. 
Please see the review below. Respond to the review line by line. 
Thank you.

Best,
Marcel

---

# bnem #1740

## DESCRIPTION

* Looks good.
* Please format the `Description` field so that it does not run across the
screen.
* Include `BugReports` and `URL` fields for the package.

## NAMESPACE

* AFAICT, should `bnembs` and `bnemBs` have the same case? The first is the
class and the second is the constructor function.
* Avoid importing `exprs` from Biobase, the `ExpressionSet` structure is
retired.

## vignette

* Does the function that creates the DAG need to be displayed? Do you expect
users to write their own function similarly (lines 86 - 105)? Should it be
a helper function?
* Avoid using `print` anywhere in the code (vignette or otherwise).
* There is some code to calculate sensitivity and specificity in the vignette
that can be re-used in the form of a helper function. You may want to create
it within the vignette only.

## R

* Consider using `colSums` and `rowSums` instead of `apply(x, 2 / 1, sum)`.
* `exprs` alludes to deprecated functionality. If this is not internal,
use a keyword that is more descriptive in `R/bnem_low.R`.
* Avoid writing files to the disk for the user (e.g., in `addEdge`). Write
to the temporary directory using `tempdir()`.
* If possible, avoid nested for loops (in `adj2dnf`).
* Although entertaining, perhaps it is better to remove error messages such as
"I'm sorry, Dave. I'm afraid I can't do that." in `checkMethod`.
* Avoid using the `@` accessor see the package guidelines:
https://bioconductor.org/developers/package-guidelines/#rcode
* Using `print` is not recommended in package code unless in a `show` method.
Use `message` instead.
* (optional) Consistently use the assignment operator `<-` and avoid `=` for
assignment.
* Workflows related to a publication are best published in a separate
repository or package (`processDataBCR`).
* It would be more consistent to have a constructor that uses the same name
as the class (`bnemBs` -> `bnembs`)
* Avoid copying and pasting code (e.g., use `glob2rx` in `gene2prot`).

Minor:
* `dim(x)[2]` corresponds to `ncol`
* Avoid redundance by removing `paste` from inside `stop`, `message`, etc.
* In some instances you don't need to convert logical to numeric index (e.g.,
`which(Epos < -beta)` can simply be `Epos < -beta` based on `Epos[wrongPos]`)
unless there is `NA`.
* Avoid using `flush.console()`

## tests

* It's recommended to add more unit tests

## other

* Perhaps add `bnem_app.R` to `inst/scripts`.

**Comment by MartinFXP** [comment]
Hi Marcel,

thank you for the review and suggestions to improve the package.

Let me know what you think about the changes.

Best,
Martin

> Hi Martin, @MartinFXP
> 
> Thank you for your submission to Bioconductor.
> Please see the review below. Respond to the review line by line.
> Thank you.
> 
> Best,
> Marcel
> 
> # bnem #1740
> ## DESCRIPTION
> * Looks good.
> * Please format the `Description` field so that it does not run across the
>   screen.

Done.

> * Include `BugReports` and `URL` fields for the package.

Done.

> 
> ## NAMESPACE
> * AFAICT, should `bnembs` and `bnemBs` have the same case? The first is the
>   class and the second is the constructor function.

I agree that it makes more sense to change bnembs to bnemBs. Done.

> * Avoid importing `exprs` from Biobase, the `ExpressionSet` structure is
>   retired.

I am at the moment not sure how to resolve this. I'm trying to find out
how to do the rma processing of the microarray data without getting a
deprecated structure.

> 
> ## vignette
> * Does the function that creates the DAG need to be displayed? Do you expect
>   users to write their own function similarly (lines 86 - 105)? Should it be
>   a helper function?

I added a function which adds the gaussian noise. Is that what you meant?

> * Avoid using `print` anywhere in the code (vignette or otherwise).

Fixed, except when I need to plot lattice objects. I hope that is ok.

> * There is some code to calculate sensitivity and specificity in the vignette
>   that can be re-used in the form of a helper function. You may want to create
>   it within the vignette only.

Done.

> 
> ## R
> * Consider using `colSums` and `rowSums` instead of `apply(x, 2 / 1, sum)`.

Done.

> * `exprs` alludes to deprecated functionality. If this is not internal,
>   use a keyword that is more descriptive in `R/bnem_low.R`.

I use exprs for a gene expression matrix that is an optional input 
argument of main function 'bnem'. Do you mean that I should 
change that to something else? Like 'expression'. Done.

> * Avoid writing files to the disk for the user (e.g., in `addEdge`). Write
>   to the temporary directory using `tempdir()`.

I used 'tempfile()', which seems more reasonable to me now. Done.

> * If possible, avoid nested for loops (in `adj2dnf`).

Done.

> * Although entertaining, perhaps it is better to remove error messages such as
>   "I'm sorry, Dave. I'm afraid I can't do that." in `checkMethod`.

Done.

> * Avoid using the `@` accessor see the package guidelines:
>   https://bioconductor.org/developers/package-guidelines/#rcode

Done, except:

CellNOptR only has a set method for the signal slot of the CNOlist class and that does not seem to be working.

For the renderInfo slot of a graphNEL object in the low level function 'getHierarchy'. The 'renderInfo' and 'nodeRenderInfo' accessor functions do not exists or seem to work, respectively.

> * Using `print` is not recommended in package code unless in a `show` method.
>   Use `message` instead.

Done.

> * (optional) Consistently use the assignment operator `<-` and avoid `=` for
>   assignment.

Done.

> * Workflows related to a publication are best published in a separate
>   repository or package (`processDataBCR`).

How would I go about that? It seems a bit of an overkill to add a package 
consisting only of this function. I'd rather keep it in here, if that's ok.

> * It would be more consistent to have a constructor that uses the same name
>   as the class (`bnemBs` -> `bnembs`)

Done.

> * Avoid copying and pasting code (e.g., use `glob2rx` in `gene2prot`).

Done.

> 
> Minor:
> 
> * `dim(x)[2]` corresponds to `ncol`

Done.

> * Avoid redundance by removing `paste` from inside `stop`, `message`, etc.

Done.

> * In some instances you don't need to convert logical to numeric index (e.g.,
>   `which(Epos < -beta)` can simply be `Epos < -beta` based on `Epos[wrongPos]`)
>   unless there is `NA`.

Done.

> * Avoid using `flush.console()`

Done.

> 
> ## tests
> * It's recommended to add more unit tests

Added two more tests.

> 
> ## other
> * Perhaps add `bnem_app.R` to `inst/scripts`.

Done.

**Comment by LiNk-NY** [comment]
Hi Martin, @MartinFXP 
Thank you for following up on that. A few comments: 

> Avoid importing exprs from Biobase, the ExpressionSet structure is
retired.

>> I am at the moment not sure how to resolve this. I'm trying to find out
how to do the rma processing of the microarray data without getting a
deprecated structure.

If the software you're using returns an `ExpressionSet` and it is crucial
for the functionality of your package, it seems like there is no way around
using the deprecated structure. 

After running build and check, I got an error from the examples. See the
details:

<details> <summary>
**ERROR** from R CMD check
</summary>
```r
* checking examples ... ERROR
Running examples in 'bnem-Ex.R' failed
The error most likely occurred in:

> ### Name: findResiduals
> ### Title: Compute residuals
> ### Aliases: findResiduals
> 
> ### ** Examples
> 
> sifMatrix <- rbind(c("A", 1, "B"), c("A", 1, "C"), c("B", 1, "D"),
+ c("C", 1, "D"))
> temp.file <- tempfile(pattern="interaction",fileext=".sif")
> write.table(sifMatrix, file = temp.file, sep = "\t",
+ row.names = FALSE, col.names = FALSE,
+ quote = FALSE)
> PKN <- CellNOptR::readSIF(temp.file)
> CNOlist <- dummyCNOlist("A", c("B","C","D"), maxStim = 1, maxInhibit = 2,
+ signal = c("A", "B","C","D"))
> model <- CellNOptR::preprocessing(CNOlist, PKN, maxInputsPerGate = 100)
[1] "The following species are measured: A, B, C, D"
[1] "The following species are stimulated: A"
[1] "The following species are inhibited: B, C, D"
[1] "The following species are not observable and/or not controllable: "
> expression <- matrix(rnorm(nrow(slot(CNOlist, "cues"))*10), 10,
+ nrow(slot(CNOlist, "cues")))
> fc <- computeFc(CNOlist, expression)
> initBstring <- rep(0, length(model$reacID))
> res <- bnem(search = "greedy", CNOlist = CNOlist, fc = fc, model = model,
+ parallel = NULL, initBstring = initBstring, draw = FALSE, verbose = FALSE,
+ maxSteps = Inf)
> rownames(fc) <- seq_len(nrow(fc))
> ## val <- validateGraph(CNOlist = CNOlist, fc = fc, model = model,
> ## bString = res$bString, Egenes = 10, Sgene = 4)
> residuals <- findResiduals(res$bString, CNOlist, model, fc = fc)
1.A: 1
Activated: 1
Inhibited: 0
Summary Score:
-0.38575837490523-0.38575837490523-0.38575837490523-0.38575837490523-0.38575837490523-0.38575837490523
2.B: 0
Activated: 0
Inhibited: 0
Summary Score:
NANANANaNNANA
3.C: 5
Activated: 4
Inhibited: 1
Summary Score:
-0.578637562357845-0.540061724867322-0.501485887376799-0.48605555238059-0.501485887376799-0.308606699924184
4.D: 4
Activated: 2
Inhibited: 2
Summary Score:
-0.88249750329277-0.78067086829745-0.644902021637024-0.602474257055641-0.466705410395215-0.237595481655746
Unique genes used: 10 (100 
                        %)
Duplicated genes: 0
Overall fit:
-0.88249750329277-0.56974701842881-0.52077380612206-0.522593316503074-0.414690253023122-0.237595481655746
calculating residuals for 4 S-genes based on 10 E-genes.

 1%
 3%
 5%
 7%
 9%
 11%
 13%Warning in cor(sgene, t(data.tmp), method = method) :
  the standard deviation is zero

 15%
 17%
 19%
 21%
 23%
 25%
 51%
 53%
 55%
 57%
 59%
 61%
 63%
 65%
 67%
 69%
 71%
 73%
 75%
 76%
 78%
 80%
 82%
 84%
 86%
 88%
 90%
 92%
 94%
 96%
 98%
 100%Error in fun(key = base::quote(list(space = FALSE, at = c(-0.034196039270363,  : 
  object 'key.gf' not found
Calls: findResiduals ... print.trellis -> printFunction -> evaluate.legend -> do.call -> fun
Execution halted
```
</details>

> Does the function that creates the DAG need to be displayed? Do you expect
users to write their own function similarly (lines 86 - 105)? Should it be
a helper function?
>> I added a function which adds the gaussian noise. Is that what you meant?

I meant the code in the first chunk in the DAG section. Could that be simplified for the
user? You've reduced the amount of code in the chunk so it looks more new-user-friendly. 

>> I use exprs for a gene expression matrix that is an optional input
argument of main function 'bnem'. Do you mean that I should
change that to something else? Like 'expression'. Done.

Yes, thank you. 

>> How would I go about that? It seems a bit of an overkill to add a package
consisting only of this function. I'd rather keep it in here, if that's ok.

A workflow like this is a bit hidden given that it is inside a package and it might
be more prominent in its own repository (perhaps even with a pkgdown page).
It would convey the same information but those looking for the workflow would
have an easier time finding it IMO. 

Best,
Marcel

**Comment by MartinFXP** [comment]
Hi Marcel,

Thanks for the suggestions.

> Hi Martin, @MartinFXP
> Thank you for following up on that. A few comments:
> 
> > Avoid importing exprs from Biobase, the ExpressionSet structure is
> > retired.
> 
> > > I am at the moment not sure how to resolve this. I'm trying to find out
> > > how to do the rma processing of the microarray data without getting a
> > > deprecated structure.
> 
> If the software you're using returns an `ExpressionSet` and it is crucial
> for the functionality of your package, it seems like there is no way around
> using the deprecated structure.
> 

The package can function without it, but the data object was created with this
function. Hence, I think it makes sense to include it.

> After running build and check, I got an error from the examples. See the
> details:

This error was the result of an unfortunate bugfix for the package 'epiNEM', but 
that is now fixed.

> 
> > Does the function that creates the DAG need to be displayed? Do you expect
> > users to write their own function similarly (lines 86 - 105)? Should it be
> > a helper function?
> > > I added a function which adds the gaussian noise. Is that what you meant?
> 
> I meant the code in the first chunk in the DAG section. Could that be simplified for the
> user? You've reduced the amount of code in the chunk so it looks more new-user-friendly.
> 
> > > I use exprs for a gene expression matrix that is an optional input
> > > argument of main function 'bnem'. Do you mean that I should
> > > change that to something else? Like 'expression'. Done.
> 
> Yes, thank you.
> 
> > > How would I go about that? It seems a bit of an overkill to add a package
> > > consisting only of this function. I'd rather keep it in here, if that's ok.
> 
> A workflow like this is a bit hidden given that it is inside a package and it might
> be more prominent in its own repository (perhaps even with a pkgdown page).
> It would convey the same information but those looking for the workflow would
> have an easier time finding it IMO.
> 

We analysed the data in the original publication of the method. The publication 
points to the github repository. I added a paragraph to the readme to put more 
emphasis on the data

> Best,
> Marcel

Best,
Martin

**Comment by LiNk-NY** [comment]
Hi Martin, @MartinFXP 
Thanks for making those changes. They look good. 
We have accepted your package. Thank you for your contribution. 
Best regards,
Marcel

**Comment by MartinFXP** [comment]
Hi Marcel,

Thanks again for the review and final decision. Happy to contribute.

Best,
Martin

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MartinFXP.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bnem")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bnem

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
