### ISSUE TITLE
RiboDiPA: Differential Pattern Analysis for Ribo-seq data

### ISSUE THREAD

**Issue by jipingw** [Bioconductor/Contributions#1741]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jipingw/RiboDiPA

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by jipingw** [comment]
Hi, I pushed a new version to github yesterday, but I haven't see the report yet? Is it on the way or something went wrong? thanks.

**Comment by jipingw** [comment]
@hpages HI, I am just wondering whether there is any update on the review of this package. Or is there anything i should do to make it move? thanks for help.

**Comment by hpages** [comment]
Hi @jipingw,

We'll review soon. Thanks for your patience.

H.

**Comment by hpages** [comment]
Hi @jipingw ,

Thanks for submitting RiboDiPA. The package looks good and is almost ready for inclusion in Bioconductor. Only a few cosmetic issues:

1. You have a typo in "differntial". Should be "differential" ("e" is missing). This is in the Description field of the `DESCRIPTION` file.

2. Please remove the `build/` folder and the `src/symbols.rds` file. These don't belong to the package source tree.

3. Also remove the last line in the `DESCRIPTION` file:
    ```
    Packaged: 2020-09-12 20:40:56 UTC; keren
    ```

4. Bioconductor naming style is to use _camelCaps_ for functions e.g. `dataBinning` instead of `DataBinning`, `diffPatternTest` instead of `DPtest`, etc... Please consider adopting this style. In any case, only one style should be used so having one function named `psitecal` and another one named `PsiteMapping` should be avoided.

5. Serialized datasets should preferably go in the `data/` folder. Using `inst/extdata/` is typically for data that is not in a serialized form e.g. for things like GTF, FASTA, or BAM files. The advantage of having the serialized datasets in `data/` instead of `inst/extdata/` is that they can be discovered and loaded with standard mechanisms like `data(package="RiboDiPA")` and `data(sample)`. Also please use a more descriptive name for the dataset, or at least a name that is more unique (`sample` is too generic).

6. The "Vignette of the RiboDiPA pipeline" section of the vignette should just be called "The RiboDiPA pipeline".

7. Please use proper indentation of your code. Also put a space after the commas (`,`). This will make your code a lot easier to read. For example, do:
    ```
    plot_track(data=data.psite, genes.list=c("YDR050C","YDR064W"), 
               replicates=NULL, exons=FALSE)
    ```
    instead of:
    ```
    plot_track(data=data.psite,genes.list=c("YDR050C","YDR064W"), 
    replicates=NULL,exons=FALSE)
    ```

8. Also make sure that your lines of code are properly wrapped. For example the code in the Examples section of `DPtest.exon's` man page looks like this when I open the man page with `?DPtest.exon`:
    ```
    classlabel <- data.frame(condition = c("mutant","mutant","wildtype",
    "wildtype"),
        comparison=c(2,2,1,1))
    ```
    This is hard to read. With proper wrapping and indenting, it will look like this:
    ```
    classlabel <- data.frame(
        condition = c("mutant","mutant","wildtype","wildtype"),
        comparison = c(2,2,1,1)
    )
    ```
    This looks a little bit nicer and is a little bit easier to read. Sometimes assigning additional variables helps make the code even easier to format thus easier to read:
    ```
    condition  <- c("mutant", "mutant", "wildtype", "wildtype")
    comparison <- c(2, 2, 1, 1)
    classlabel <- data.frame(condition, comparison)
    ```

9. You seem to be using TeX/LaTeX markup in your man pages (e.g. in the `\details` section of `DataBinning`'s man page). Note that this is not supported and doesn't render properly. For example, open `DataBinning`'s man page with `?DataBinning` and take a look at the formula in the Details section to see what I mean.

Thanks,
H.

**Comment by hpages** [comment]
Hi @jipingw -- do you intend to followup on this submission? Thanks.  H.

**Comment by jipingw** [comment]
Yes. Sorry for the delay. We are still on the revision of the codes. Thanks so much for the reminder.

**Comment by jipingw** [comment]
@hpages  Hi, there is an error from RiboDiPA.Rmd in lines 191-194. But I cannot figure what the error could be as the RiboDiPA.Rmd compile without problem locally. Could you give me some hints on this? I am using mac. Thanks.

**Comment by jipingw** [comment]
@hpages Hi, could you give me some help on the most recent report? on Windows system, it keeps complaining about an error in index the bam file, which was not encountered in the other two platforms? I don't have any clue about this error. Thanks!

**Comment by jipingw** [comment]
@ttriche @mtmorgan 

The RiboDiPA currently has two issues:
 
1. warning: R > 4.1 is suggested instead of 4.0. But 4.1 is not available for download yet. Some users requested to set R>4.0. So I still set it as R>4.0.
2. there was an error in Windows platform, which we don’t understand. Could anyone provide some hints or help on this issue?

**Comment by mtmorgan** [comment]
The files should be downloaded with `mode = "wb"` but a better strategy is to use BiocFIleCache as outlined in the vignette http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource.

**Comment by jipingw** [comment]
@mtmorgan @hpages @ttriche  Could please help? I have no clue why windows platform always generate some error. thanks.

**Comment by kerenli** [comment]
Here is the section caused error in x64 but works well in i386:

```
Running examples in 'RiboDiPA-Ex.R' failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: psiteCal
> ### Title: P-site position of reads
> ### Aliases: psiteCal
> 
> ### ** Examples
> 
> ex.cigar <- c("21M74731N7M", "2S11M57302N12M3S", "28M", "27M1S")
> ex.start <- c(177640, 249163, 249286, 249290)
> ex.psitemap <- c(9, 18, 9, 9)
> psiteCal(ex.cigar, ex.start, ex.psitemap)
```
where function `psiteCal()` is defined by

```
#include <Rcpp.h>
#include <iostream>
#include <vector>
#include <cstring>
#include <stdio.h>

using namespace Rcpp;

// [[Rcpp::export]]
NumericVector psiteCal(CharacterVector cigar, IntegerVector start, IntegerVector psitemap){

  int n=start.size();
  NumericVector center(n);

  /* prase cigar durations */

  for (int i=0; i < n; i++){

    char temp[strlen(cigar[i])];
    strcpy(temp,cigar[i]);
    /*Rcout << temp<<std::endl;*/
    char * pch;
    pch= strtok(temp,"MIDNSHP=X");
    int j=0;
    NumericVector duration(10);
    while (pch != NULL)
    {
      duration[j]=std::atoi(pch);
      /*Rcout << pch<<std::endl;*/
      pch = strtok (NULL, "MIDNSHP=X");
      j=j+1;
    }
    duration=duration[Rcpp::Range(0,j-1)];
    /*Rcout <<duration<<std::endl;  */
    center[i]= duration[0];
    /*Rcout<<"center:" <<center[i]<<std::endl;*/

    /* prase letters*/
    strcpy(temp,cigar[i]);
    /*Rcout << temp<<std::endl;*/
    pch = strtok(temp, "0123456789");

    j=0;
    CharacterVector letter(10);

    while (pch != NULL)
    {
      letter[j]=pch;
      /*Rcout << pch<<std::endl;*/
      pch = strtok(NULL, "0123456789");
      j=j+1;
    }
    letter=letter[Rcpp::Range(0,j-1)];

    /*Rcout <<letter<<std::endl;  */

    /*calculate read center*/
    int readlength=0;
    for (j=0;j<letter.size();j++){
      if(letter[j]=="M"||letter[j]=="I"||letter[j]=="S"||letter[j]=="="||letter[j]=="X"){
        readlength=readlength+duration[j];
      }
    }

    /*Rcout<<"read length "<<readlength<<std::endl;*/
    int fragmentlength=0;
    int position=start[i];


    if(duration.size()==1)
      center(i)=start[i]+psitemap[i];
    else{
      j=0;
      while(j<duration.size()){
        if(letter[j]=="M"||letter[j]=="X"||letter[j]=="="){
          fragmentlength=fragmentlength+duration[j];
          position=position+duration[j];
          if(fragmentlength>psitemap[i]){
            center[i]=position-(fragmentlength-psitemap[i]);
            j=duration.size();}
        }else if(letter[j]=="I")
          fragmentlength=fragmentlength+duration[j];
        else if(letter[j]=="S"){
          fragmentlength=fragmentlength+duration[j];
          if (j>0)
            position=position+duration[j];
        }else if(letter[j]=="N"||letter[j]=="D"){
          position=position+duration[j];
        }
        j=j+1;
      }
    }
    /*Rcout<<"fragmentlength "<<fragmentlength<<std::endl;*/
  }
  /*Rcout<<"center"<<center<<std::endl;*/
  return center;
}

```

Is there any library not work in x64?

Thank you.

**Comment by mtmorgan** [comment]
Isn't this
```
    char temp[strlen(cigar[i])];
    strcpy(temp,cigar[i]);
```
memory corruption, because `strlen("foo")` returns three, but `strcpy(temp, "foo")` writes four characters (including the `\0`). 

Have you used valgrind or similar to look for these problems?

**Comment by jipingw** [comment]
@mtmorgan @hpages thanks for hints. Thanks for help. The problem was indeed in the following two lines of codes:
   
    char temp[strlen(cigar[i])];
    strcpy(temp,cigar[i]);

I changed the first line to 

   char temp[strlen(cigar[I])+1];

which fixed the errors.

**Comment by hpages** [comment]
Hi @jipingw ,

Are you done addressing the issues I reported on Nov 18, 2020?

Thanks,
H.

**Comment by jipingw** [comment]
Yes, it’s all done. all the issues you pointed out have been taken care of. Thanks.

**Comment by jipingw** [comment]
Yes, we didn't addressed all issues. The uploaded version is the most updated version.

**Comment by kerenli** [comment]
What did you mean this? "we didn't addressed all issues"

**Comment by jipingw** [comment]
sorry, my typo, We addressed all issues.

**Comment by hpages** [comment]
All is good now. Thanks for all the improvements to the package.  H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jipingw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RiboDiPA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RiboDiPA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
