### ISSUE TITLE
censcyt

### ISSUE THREAD

**Issue by retogerber** [Bioconductor/Contributions#1747]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/retogerber/censcyt

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by retogerber** [comment]
Hi @hpages 

Thanks for taking the time to review this package. Just a short question: Until when can I expect a feedback? Just asking because I haven't yet gotten any and was wondering if I missed something in the submission process.

Best regards

**Comment by hpages** [comment]
Hi @retogerber ,

Sorry for the delay. **censcyt** looks good and is ready for acceptance. Only one minor thing: Is the masking of the `createFormula()` function from the **diffcyt** package intended? If yes, then this should be mentioned in the man page with a reference to the original `createFormula()`. If not, then please rename the function.

Also maybe you could make it easier for the user to compare **censcyt** with **diffcyt** by moving the latter from `Imports` to `Depends`. This way it will be automatically placed on the search path when the user loads the former, and it will be placed after the former, which is probably what the user would want. This would avoid the current inconvenience that the user explicitly needs to load **diffcyt**, and also avoid the uncertainty of where **diffcyt** ends up on the search path, sometimes before **censcyt**, sometimes after, depending on whether the package is loaded after or before **censcyt**. Having **diffcyt** in `Depends` would make its position on the search list the same for everybody and predictable, and therefore make the potential name conflicts easier to deal with.

Thanks,
H.

**Comment by retogerber** [comment]
Hi @hpages 

Thanks for the feedback. Yes the masking of `createFormula()` is intended since it expands the functionality but is backwards compatible (within **diffcyt**). Moving **diffcyt** to `Depends` indeed solves the issue with inconsistency when loading in different orders. 
Updated this and pushed to bioconductor.

Thanks again.
Best

**Comment by hpages** [comment]
Thanks. Package is good to go. Note that it would be great if you could provide a link or reference to `diffcyt::createFormula()` in your man page for `createFormula()`. Please consider adding this when you get a chance.

Cheers,
H.

**Comment by retogerber** [comment]
Thanks @hpages!
Will add the suggested link to `diffcyt::createFormula()`.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/retogerber.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("censcyt")`. The package 'landing page' will be created at

https://bioconductor.org/packages/censcyt

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
