### ISSUE TITLE
nempi

### ISSUE THREAD

**Issue by MartinFXP** [Bioconductor/Contributions#1749]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbg-ethz/nempi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Hi @MartinFXP,

Thanks for this new submission. 3 minor things before we can add the package to Bioconductor:

1. The `plotConvergence()` function in **nempi** masks the function of the same name in the **mnem** package. This should be avoided by making the function an S3 generic with methods for mnem and nempi objects. Note that this is exactly why R has generic functions. Also because **nempi** depends on **mnem** (via the `Imports` field) the generic needs to be defined in the latter, and exported. Since you control the 2 packages, this should be straightforward.

2. The title and author(s) of the vignette are missing in its HTML version (created by R CMD build).

3. Because of Bioconductor 6-month release cycles and because Bioconductor has a notion of release and devel, Bioconductor users should always use `BiocManager::install()` to install packages. This will spare them a lot of headaches with version mismatches. So please do not encourage your users to install your package from GitHub in the vignette.

Thanks,
H.

**Comment by MartinFXP** [comment]
Hi @hpages 

Thank you for the time to review my package. I believe I addressed all points below.

> Hi @MartinFXP,
> 
> Thanks for this new submission. 3 minor things before we can add the package to Bioconductor:
> 
> 1. The `plotConvergence()` function in **nempi** masks the function of the same name in the **mnem** package. This should be avoided by making the function an S3 generic with methods for mnem and nempi objects. Note that this is exactly why R has generic functions. Also because **nempi** depends on **mnem** (via the `Imports` field) the generic needs to be defined in the latter, and exported. Since you control the 2 packages, this should be straightforward.

This should be fixed.

> 2. The title and author(s) of the vignette are missing in its HTML version (created by R CMD build).

Fixed.

> 3. Because of Bioconductor 6-month release cycles and because Bioconductor has a notion of release and devel, Bioconductor users should always use `BiocManager::install()` to install packages. This will spare them a lot of headaches with version mismatches. So please do not encourage your users to install your package from GitHub in the vignette.

Removed.

> 
> Thanks,
> H.

Thanks again and please let me know what you think.

Best,
Martin

**Comment by hpages** [comment]
Thanks for the quick fixes.  Best,  H.

**Comment by MartinFXP** [comment]
Thanks for the quick review and acceptance.

Best,
Martin

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MartinFXP.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("nempi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/nempi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
