### ISSUE TITLE
MWASTools

### ISSUE THREAD

**Issue by AndreaRMICL** [Bioconductor/Contributions#175]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/AndreaRMICL/MWASTools

Confirm the following by editing each check box to '[x]'
- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [X] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
    months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lawremi** [comment]
Needs to be based on SummarizedExperiment. The assay matrix and clinical variables would fit nicely in one.

**Comment by AndreaRMICL** [comment]
Hi @lawremi, 

Thanks for your message. Do you mean creating  SummarizedExperiment object using the datasets metabolic_data and clinical_data that I use for the vignette and for the examples of the help files ?

Thanks, 

Andrea

**Comment by lawremi** [comment]
Sure, but the main thing is that the package itself (the API, even the implementaton) is based on it.  It should expect a SummarizedExperiment as input, for example.

**Comment by AndreaRMICL** [comment]
I think we could only use SummarizedExperiment in the function MWAS_stats () as it is the only function of the package where the metabolic data and the clinical data are used together. However, wouldn´t it be easier for the users to input the metabolic and clinical data as separate variables ?

**Comment by lawremi** [comment]
I would think users would appreciate a SummarizedExperiment interface, even for functions that do not require all of the information, because they will already be using such an object in their workflow. It should also simplify your implementation, since it can now make assumptions about the consistency of the data components.

**Comment by AndreaRMICL** [comment]
Thanks @lawremi I will start looking at it in detail soon.

**Comment by AndreaRMICL** [comment]
Hi @lawremi, 

Thanks very much for your advice. Actually it is really useful to use the SummarizedExperiment interface. I'm now modifying the functions so that the package is all based on a SummarizedExperiment. I'll push the updated version of the package hopefully tomorrow. 

Andrea

**Comment by lshep** [comment]
Thank you for transitioning to the SummarizedExperiment object. This will greatly improve its compatibility with existing Bioconductor packages.  Please see the additional comments below. Once you are done updating, please respond back here with a summary of what was changed or any
justification or responses to the issues. 

**Vignette/R code:** 

- [ ] Please add installation instructions from Bioconductor. 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("MWASTools")
```

- [ ] There is a missing reference in section 3.2

- [ ] You shouldn't need to load SummarizedExperiment since it is listed in the
DESCRIPTION and NAMESPACE. 

- [ ] Will the metabolic data be a frequently accessed slot. if so should there be a
accessor method for the metabolic data so instead of
t(assays(metabo_SE)$metabolic_data)  it could just be something like
metabolicData(metabo_SE)?

- [ ] what is the reasoning behind having static png images and using eval=FALSE for
the code that would generate these images? we generally like graphs/plots
generated interactively. 

- [ ] You define some "needed variables" like metabo_matrix, ppm, ref_spectrum and
then use in the functions like QC_CV, QC_CV_specNMR, MWSA_skylineNMR. Would
the desired data change in these variables or can these actually be calculated
from within the function to save users steps? The same with STOCSY_NMR, why
couldn't your main  metabo_SE object be used as input instead of having to
calculate metabo_matrix and ppm?

**man:**

the same as vignette, you shouldn't need to separately load the
SummarizedExperiment library as you import it as part of your package.   


Thank you for your submission. I look forward to your responses.

**Comment by AndreaRMICL** [comment]
Hi @lshep, 

Thanks very much for your feedback and for helping us to improve our package. I've just pushed an updated version, but by mistake I wrote version 0.99.3, instead of 0.99.2, I'm not sure if this is a problem. 

See some comments below: 

1) Vignette/R code: 

-We've added installation instructions from Bioconductor. 
-We've added the missing reference in 3.2 (now 4.2). 
-We've modified the code so that "metabo_SE" is the input argument for "STOCSY_NMR()", "QC_CV_specNMR()" and "MWAS_skylineNMR()". Now the variables "metabo_matrix" and "ppm" are generated internally from the "metabo_SE" variable. That was a very good suggestion, I like it much better like this (thanks!).
-We decided to include static images in the vignette because we think the size of the static images looks much nicer than if the images are generated interactively. I just wonder if there is a good way to customize the dimensions of the images interactively ? We tried with "dev.new()" but it did not really work.

2) man:

-In the example for : "MWAS_SummarizedExperiment()", I extracted the individual elements of metabo_SE, to illustrate the functionality of the function. To do so, I need to use the function "assays()" from the SummarizedExperiment package, and this is why I need to do library(SummarizedExperiment). 

Thanks very much, 

Best wishes, 

Andrea

**Comment by lshep** [comment]
It is looking very close to acceptance.  The limiting factor right now is the package size. We generally only accept packages that are >4Mb.  

There are two options:
1. reduces the size of the data objects being utilized
2.  If you get rid of the static .png in the vignette that should put you under as well.  I know you mentioned the images looked nicer when static rather than generating interactively. Have you tried specifying the plotting region width and length in the .Rmd code chunk?  When you specify a code chunk for plotting you can use the arguments fig.height and fig.width to change the defaults. 

Lori

**Comment by AndreaRMICL** [comment]
Hi @lshep, 

Thanks very much for your reply. I don't understand why when saving the data as a SummarizedExperiment object, the size of the package increased.... But anyway, I am going to try to reduce a bit the resolution of the NMR spectra of the example dataset, and see if this helps. 

Best wishes, 

Andrea

**Comment by AndreaRMICL** [comment]
Hi @lshep, 

I've now reduced the size of the data objects, so I think that now the package meets the size requirements. Let me know if there are further changes to be made. 

Best wishes, 

Andrea

**Comment by AndreaRMICL** [comment]
Hi @lshep, 

I have also included your suggestion about changing the dimensions of the figure in the .Rmd code chunck, so now the figures are created interactively. Thanks for the suggestion!

Andrea

**Comment by lshep** [comment]
Thank you. Everything else looked good. I will mark your package as accepted and you should receive svn instructions via email soon.  Please keep the issue open; we will close it when we send you credentials.

**Comment by AndreaRMICL** [comment]
Thanks very much for all your help!

**Comment by AndreaRMICL** [comment]
Hi @lshep, 
I was wondering if my package will be included in Bioconductor this week, or later on. I'm about to submit a paper where I have use the package, so it would be great if I could cite it from Bioconductor.

Thanks very much, 
Andrea

**Comment by lshep** [comment]
Hi @AndreaRMICL I'll double check on your svn credentials with @mtmorgan .  As soon as you are sent the credentials you will be able to include your package in the devel version of Bioconductor.

**Comment by AndreaRMICL** [comment]
Thanks very much @lshep

**Comment by AndreaRMICL** [comment]
Hi @lshep, 

Sorry to bother you again with this. I was just wondering if you have any news about the status of my package.

Thanks very much in advance, 

Best wishes, 

Andrea
