### ISSUE TITLE
VarCon (guithub now with ssh key)

### ISSUE THREAD

**Issue by caggtaagtat** [Bioconductor/Contributions#1754]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/caggtaagtat/VarCon

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

**Comment by caggtaagtat** [comment]
Hi,
when I try to push to bioconductor, I get the error: "error: src refspec master does not match any" and "error: failed to push some refs to 'git@git.bioconductor.org:packages/VarCon.git'"
It tried the command: "git push upstream" and "git push upstream master" and my paths are:

> git remote -v
origin  https://github.com/caggtaagtat/VarCon (fetch)
origin  https://github.com/caggtaagtat/VarCon (push)
upstream        git@git.bioconductor.org:packages/VarCon.git (fetch)
upstream        git@git.bioconductor.org:packages/VarCon.git (push)

All changes are commited and on guithub. I changed the version number in the DESCRIPTION file. Could this be related to something with the SSH key?

**Comment by caggtaagtat** [comment]
I reinitialized my git directory and now am able to push to guithub from console, but not to bioconductor:
>git push upstream master
"git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by mtmorgan** [comment]
Does FAQ #1 at http://bioconductor.org/developers/how-to/git/faq/ provide any suggestions? It looks like the key you've uploaded to github at https://github.com/caggtaagtat.keys matches the key known to Bioconductor

**Comment by caggtaagtat** [comment]
I'm sorry, but I don't seem to be able to create an account there. it says: "johannes.ptok@posteo.de is not associated with a maintainer of a Bioconductor package.". Should I have an account there, although I am not an active maintainer already?

**Comment by lshep** [comment]
Your account doesn't seem to be activate yet.  Have you tried this link: https://git.bioconductor.org/BiocCredentials/account_activation/

**Comment by caggtaagtat** [comment]
I tried activating it, but it says "johannes.ptok@posteo.de is not associated with a maintainer of a Bioconductor package.". Is there an alternative way to activate it?

**Comment by nturaga** [comment]
Hi @caggtaagtat 

This is strange. Have you checked your spam? Please try to activate it again and if it doesn't work we'll take another look at it. 

Best,

Nitesh

**Comment by caggtaagtat** [comment]
Thank you all for the advice. Activating my account worked now and I was able to add my SSH key to my account.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Please provide a more informative Title:, like for a paper.
- Standardize by using License: GPL-3.
- Not sure why both seqinr and Biostrings are needed? Since this is a Bioconductor package, use Biostrings?

vignettes

- VarCon.Rmd:17 it seems dangerous to ignoring all errors and warnings always.

- VarCon.Rmd:161 it would be helpful to break this dense code chunk up into sentences that describe what is going to be done, and then one or two lines of R code that does what is said to be done, followed by a few lines describing what the output should be / why it is interesting before continuing to the next couple of lines.

R (comments are on specific lines, but apply generally)

- calculateHZEIperNT.R:5 why not use Biostrings::DNAStringSet() to validate (and for subsequent manipualtion)?

- calculateMaxEntScanScore.R:9 `stop(paste0(...))` is generally redundant, since `stop()` applies `paste0(...)` internally

- calculateMaxEntScanScore.R:32 use the following paradigm to set / restore the directory robustly, even if an error occurs

    ```
    owd <- setwd(...)
    on.exit(setwd(owd))
    ```
    
- calculateMaxEntScanScore.R39 use `message()` (output to stderr) rather than `cat()` for informational messages

- calculateMaxEntScanScore.R:48 calling this perl code seems unjustified and dangerous. For instance it seems that inst/extdata/score3.pl has

    ```
    my $dir = "/bionet/geneyeo_essentials/MaxEntropy/webserver/splicemodels/";
    ```
    
  and so assumes specific directory structure. It's remarkable that this does not cause problems when the pacakge is built and checked; are there examples or tests that exercise this functionality? Or perhaps the perl code is not used at all and should be removed? Is the perl code that is used necessary, or does it translate easily into R?

- getSeqInfoFromVariation.R:9 increase readability by avoiding such nested calls, e.g.,

    ```
    if(transcriptID %in% gene2transcript$gene_name){
        idx <- match(transcriptID, gene2transcript$gene_name)
        transcriptID <- gene2transcript$transcriptID[idx]
    }
    ```
    
inst/

- app.R:29 it seems like operations like this, on the data and unrelated to UI rendering / response, should be in the package, perhaps as non-exported helper functions, so that the code is subject to the checks that `R CMD check` provides.

- app.R:62 the nested `paste(paste(...))` doesn't look necessary; again, this code should be in the R/ directory

**Comment by caggtaagtat** [comment]
Thank you very much for the detailed review. I hope my corrections are sufficient.
Four points of your review require some comments from my site:

1) **calculateHZEIperNT.R:5 why not use Biostrings::DNAStringSet() to validate (and for subsequent manipualtion)?**
This would allow e.g. characters like "-" which in my case should lead to an error.

2) **calculateMaxEntScanScore.R39 use message() (output to stderr) rather than cat() for informational messages**
The command in this line creates and manipulates a text file in the directory inst/extdata, since a text file is required as an input for the integrated perl script.

3) **calculateMaxEntScanScore.R:48 calling this perl code seems unjustified and dangerous. For instance it seems that inst/extdata/score3.pl has**
I deleted the respective code segments, since it was not used

4) **app.R:29 it seems like operations like this, on the data and unrelated to UI rendering / response, should be in the package**
There still was something wrong in the reactive data upload, so I updated the code accordingly. Now the data is uploaded using the path-input from the GUI.

**Comment by mtmorgan** [comment]
Generally, you should not be creating files in the installed library (e.g., the inst/extdata directory) because the package might be installed by a user (e.g., system administrator) different from the user. For examples, use `tempdir()`, `fl <- tempfile(); dir.create(fl)` or similar. Enable users to specify their own directory with an argument, defaulting to one of the temporary locations just indicated.

**Comment by caggtaagtat** [comment]
Thanks, I changed the code accordingly.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/caggtaagtat.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VarCon")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VarCon

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
