### ISSUE TITLE
csawBook

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1758]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/csawBook

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LTLA** [comment]
All content here was migrated from **csawUsersGuide**, which I hope this will replace. I also plan to migrate the content in **chipseqDB** into this book, thus enabling consolidation of all csaw-related documentation into a single location.

**Comment by hpages** [comment]
I wonder why the SPB didn't kick in. Anyways, this can go directly to the main builds.

Looks good. Please suggest **rebook** and add `BiocType: Book` to the DESCRIPTION.

Thanks

**Comment by hpages** [comment]
I just got this after trying to build the book locally on my laptop (got the error after 2h26m):
```
...
...
Loading required package: limma

Attaching package: 'limma'

The following object is masked from 'package:BiocGenerics':

    plotMA

Quitting from lines 117-122 (index.Rmd) 
Error in fitFDistRobustly(var, df1 = df, covariate = covariate, winsor.tail.p = winsor.tail.p) : 
  statmod package required but is not installed
Calls: local ... glmQLFit -> glmQLFit.default -> squeezeVar -> fitFDistRobustly

Execution halted
```
So it looks like **statmod** also needs to go to Depends or Suggests (using Depends indeed seems to make more sense for books). Thx

**Comment by LTLA** [comment]
I think this needs to go into the "under review" category or something to trigger creation of the repo on the BioC git server.

**Comment by hpages** [comment]
ok let's see what happens

**Comment by LTLA** [comment]
Hmm. Do you see a `csawBook` repository on your side?

**Comment by hpages** [comment]
Gosh, that thing took 7h to build on my laptop!

```
hpages@spectre:~$ time bdevbuild csawBook
* checking for file ‘csawBook/DESCRIPTION’ ... OK
* preparing ‘csawBook’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* creating default NAMESPACE file
* building ‘csawBook_0.99.0.tar.gz’


real	418m49.024s
user	49m15.256s
sys	9m42.879s
```

> Hmm. Do you see a csawBook repository on your side?

Nope:
```
hpages@spectre:~/sandbox$ git clone https://git.bioconductor.org/packages/csawBook
Cloning into 'csawBook'...
fatal: remote error: FATAL: R any packages/csawBook nobody DENIED by fallthru
(or you mis-spelled the reponame)
```
Lori @lshep, Martin @mtmorgan, or Nitesh @nturaga, any idea?

Thx

**Comment by lshep** [comment]
@hpages  --- it was awaiting moderation for @mtmorgan to do an initial look and add to git through the api and interface -- please don't manually change --  we will add to git and let you know when it can proceed

**Comment by hpages** [comment]
> Might depend on how much EHub data it needs to pull down.

I hope that's it. We have crappy internet here in Seattle, the home town of Amazon, which is ironical. 20 years ago we had fast and high quality internet in Europe for a 3rd of the price we're paying here.

**Comment by hpages** [comment]
Indeed. 2nd time is much better:
```
hpages@spectre:~$ time bdevbuild csawBook
* checking for file ‘csawBook/DESCRIPTION’ ... OK
* preparing ‘csawBook’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* creating default NAMESPACE file
* building ‘csawBook_0.99.0.tar.gz’


real	48m58.256s
user	45m39.890s
sys	1m19.977s
```
No need to replace my laptop yet.

**Comment by hpages** [comment]
Not sure what the SPB is up to but there's no need to wait.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("csawBook")`. The package 'landing page' will be created at

https://bioconductor.org/packages/csawBook

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
