### ISSUE TITLE
RJMCMCNucleosomes

### ISSUE THREAD

**Issue by adeschen** [Bioconductor/Contributions#176]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/ArnaudDroitLab/RJMCMCNucleosomes

Confirm the following by editing each check box to '[x]'
- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x ] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by adeschen** [comment]
Hi,

The only remaining warning is:
* Checking version number validity...
    * WARNING: y of x.y.z version should be even in release

Is there a way to solve it ?

Thanks,
Astrid Deschênes

**Comment by mtmorgan** [comment]
Please ignore this warning, I will review your package.

**Comment by mtmorgan** [comment]
The package looks like it's in good shape. Below are comments that I
hope help; they are from parsing the code quickly so (a) please
forgive any misinterpretations and (b) review the entire code base to
apply valid improvements to all relevant areas.

DESCRIPTION / NAMESPACE / NEWS

- It's sufficient to include Authors@R, without the Author: or
  Maintainer: fields; these are generated when the package is built
  (`R CMD build RJMCMCNucleosomes`).

- Please either populate the NEWS file in a format that can be parsed
  by `news()` (see, e.g., the [NEWS file in GenomicRanges][] or remove
  this file.
  
vignettes

- great!

R

- It seems like the major functions should inter-operate with the
  GenomicRanges package and in particular GRanges() class. The first
  two arguments of `rjmcm()` should be (minimally, support) GRanges
  instances. The return value should be a GRanges, perhaps with
  additional information in the `metadata()`.
  
- This leads to use of S4 classes that extend GRanges, rather than _ad
  hoc_ S3 classes like rjmcmNucleosomes. The classes do not have to be
  complicated, e.g.,
  
        setClass("RJMCMNucleosomes", contains="GRanges")
        
  with minimal additional methods, e.g., perhaps `show()`.
  
- `segmentation()`. The 'dataIP' argument is described 'reads that
  need to be segmented'. Reads are represented most readily as
  `GAlignments()` or `GAlignmentPairs()`, from the
  [GenomicAlignments][] package; should these be supported as input?
  
- `segmentation()`. The example might more easiy coerce to GRanges
  with
  
        as(syntheticNucleosomeReads$dataIP, "GRanges")

- `segmentation()` returns a simple list, but would be more convenient
  as a `GRangesList()`, the equivalent of
  `GRangesList(segmentation(...))`
        
- `segmentation()` seems to assume that
  `length(unique(seqnames(dataIP))) == 1L`?

- `segmentation()` it seems like you're splitting based on overlap, so
  a much more efficient implementation is

        starts = seq(posMin, posMax, by = (maxLength - (zeta + delta)))
        subject = GRanges(seqlevels(dataIP), IRanges(starts, width=maxLength)
        hits = findOverlaps(dataIP, subject)
        splitAsList(dataIP[queryHits(hits)], subjectHits(hits))
        
- `rjmcmCHR()` I suggest you use [BiocParallel][]`::bplappy()` rather
  than `mclapply()`, so that Windows users also get parallel
  evaluation.
        
        a <- bplapply(1:nbSeg, FUN = runCHR, seg, niter = nbrIterations,
            kmax = kMax, lambda = lambda, ecartmin = minInterval,
            ecartmax = maxInterval, minReads = minReads,
            adaptNbrIterations = adaptIterationsToReads,
            vSeed = vSeed, saveAsRDS = saveAsRDS)

- `mergeAllRDSFiles()` the pattern used here is 'copy-and-append',
  which scales quadratically with the size of data (all existing data
  is copied each time a new data element is added). If the data is
  large, consider a better strategy, e.g., 'pre-allocate-and-fill',
  e.g.,
  
        mu <- setNames(vector("list", length(arrayOfFiles)), arrayOfFiles)
        for (fileName in arrayOfFiles)
            ...
            mu[[fileName]] <- data$mu
            ...
        mu <- unlist(mu, use.names=FALSE)

- `postMerge()`: avoid `1:nbOverlap` in `for` loops, which has
  surprising results when `nbOverlap == 0`; use `seq_len(nbOverlap)`
  instead. It seems like (parts of?) this iteration could be avoided
  by vectorization?
  
- minor typos in documentation, e.g. RJMCMCNucleosomes.R:48 "froward"

src

- consistent use of spaces (rather than mixing tabs and spaces, e.g.,
  in rjmcmcNucleo.cpp) and formatting would help readability.

[GenomicAlignments]: https://bioconductor.org/packages/GenomicAlignments
[BiocParallel]: https://bioconductor.org/packages/BiocParallel
[NEWS file in GenomicRanges]: http://bioconductor.org/packages/devel/bioc/news/GenomicRanges/NEWS

**Comment by adeschen** [comment]
Hi,

The package is having a WARNING that used to be a NOTE:

* checking compiled code ... WARNING
File RJMCMCNucleosomes/libs/RJMCMCNucleosomes.so:
  Found abort, possibly from abort (C)
    Object: rjmcmcNucleo.o

We have reviewed the code and we have not direct abort() call. We are currently out of idea on how to solve this warning. Can you help.

Thanks,

Astrid

**Comment by mtmorgan** [comment]
Thank you for your updates. I've reviewed the package and while I have minor residual concerns in light of the time passed I am happy to accept it to Bioconductor. It will be added to our svn respository and nightly builds, with additional information in the next several days. Apologies for the delay in processing this package.
