### ISSUE TITLE
PoDCall

### ISSUE THREAD

**Issue by HansPetterBrodal** [Bioconductor/Contributions#1762]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HansPetterBrodal/PoDCall

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by HansPetterBrodal** [comment]
Hi,

At this point I am not sure if it is expected that I try to make further efforts to get clear of the warning from the latest build report? 

On my own system the package checks in under 8 mintes, and I am not sure what I can do to further decrease the check time. We rely on a function that does bootstrapping (mclustBootstrapLRT from mclust) and this is probably the single most time consuming part of our package. We don't want to sacrifice robustness and reproduciibility of the results for a lower check time.

Best regards,
Hans Petter Brodal

**Comment by lshep** [comment]
Thank you for your explanation.  I will review the package within the next week or so to provide any additional feedback.  Cheers

**Comment by lshep** [comment]
I apologize for the delayed review. Please see comments below: 

**README**

- [ ] Please include Bioconductor installation instructions
- [ ] Are both README.md and README.Rmd formats necessary? Seems like one could get out of date

**DESCRIPTION**

- [ ] We have rarely found including `LazyData: true` useful and found in can slow installation of the package. Unless necessary please remove.

**data-raw**

- [ ] data-raw is not distributed with the package. For this reason we encourage data to be in inst/scripts or inst/extdata.

**vignette**

- [ ] Please include Bioconductor installation instructions


**R code**

- [ ] In would be nice if the code could also work with SingleCellExperiment or SummerizedExperiment objects to interact more with existing Bioconductor structures.  Could some wrappers be introduced to make it compatible?

_importAmplitudeData.R_

- [ ] I recommend using `file.path` to construct the full file paths rather than a manual paste. This could potentially lead to mismatches on different OS where file.path uses the platform seperator for a users os automatically.


_podcallDdpcr.R_

- [ ] I would have an argument for output directory, allowing the users to  choose where to write the output and what to call the directory when that option is triggered.

-podcallThresholds.R_

- [ ] You shouldnt need paste inside a message. It does it automatically.

```
> vl = "something 4"
> message("Printing message ", vl)
Printing message something 4
```

Please address the above comments. When ready make sure to do a version bump and push to git.bioconductor.org to trigger a new build. Then comment back here with a summary of what has changed or discussion points and request a re-review.  

Cheers, I look forward to getting your package on Bioconductor

**Comment by HansPetterBrodal** [comment]
No worries!

Thank you for your feedback! I'll address the comments, bump the version and get back to you.

**Comment by HansPetterBrodal** [comment]
Hi again!

I have made some changes as suggested in your feedback, but have not bumped the version yet, as I would like to know what you think about our thoughts for the SingleCellExperiment and SummarizedExperiment before I proceed.

> I apologize for the delayed review. Please see comments below:
> 
> **README**
> 
> *  Please include Bioconductor installation instructions

Added instructions

> * [ ]  Are both README.md and README.Rmd formats necessary? Seems like one could get out of date.

README.md is not edited directly, but generated from README.Rmd by roxygen2 and updated every time i build the package on my own system. README.md is as you know used to generate the html summary in the GitHub repository, so I would like to keep it for that reason. And I want to keep git-tracking README.Rmd for version control purposes, since this is the file I edit.
> 
> **DESCRIPTION**
> 
> *  We have rarely found including `LazyData: true` useful and found in can slow installation of the package. Unless necessary please remove.

Removed `LazyData: true` and made changes in code to load data where necessary.
> 
> **data-raw**
> 
> *  data-raw is not distributed with the package. For this reason we encourage data to be in inst/scripts or inst/extdata.

Script to generate data moved to inst/scripts.
> 
> **vignette**
> 
> *  Please include Bioconductor installation instructions

Added instructions
> 
> **R code**
> 
> * [ ]  In would be nice if the code could also work with SingleCellExperiment or SummerizedExperiment objects to interact more with existing Bioconductor structures.  Could some wrappers be introduced to make it compatible?

Those object classes are not something I or the the other author is familiar with. For inspiration and examples I had a look at the two other software packages in Bioconductor for ddPCR data, but none of them mentioned any use of the suggested classes. I have yet to find any useful examples elsewhere either. 

At this point I am not sure how they could be used for ddPCR data. A possible complicating factor in ddPCR data is that due to differing number of data points for each sample in the same experiment, data cannot be stores as a single matrix. 
PoDCall is developed and used as a stand-alone tool for working on amplitude data exported from Quantasoft (Bio-Rad's proprietary software). 

Perhaps compatibility could be something we add at a later stage if there is a demand for it?  
> 
> _importAmplitudeData.R_
> 
> * I recommend using `file.path` to construct the full file paths rather than a manual paste. This could potentially lead to mismatches on different OS where file.path uses the platform seperator for a users os automatically.

Changed to using `file.path` where appropriate.
> 
> _podcallDdpcr.R_
> 
> *  I would have an argument for output directory, allowing the users to  choose where to write the output and what to call the directory when that option is triggered.

Added output directory as optional argument.
> 
> -podcallThresholds.R_
> 
> *  You shouldnt need paste inside a message. It does it automatically.
> 
> ```
> > vl = "something 4"
> > message("Printing message ", vl)
> Printing message something 4
> ```
> 
> Please address the above comments. When ready make sure to do a version bump and push to git.bioconductor.org to trigger a new build. Then comment back here with a summary of what has changed or discussion points and request a re-review.
> 
> Cheers, I look forward to getting your package on Bioconductor

Best regards,
Hans Petter Brodal

**Comment by lshep** [comment]
If its not appropriate than it does not have to be implemented. We like to see interoperability with other Bioconductor packages whenever possible so if there is a way to connect with other pcr or ddpcr Bioconductor packages that would be fantastic but if it is not possible than it can be skipped.

**Comment by HansPetterBrodal** [comment]
I agree, interoperability with other related Bioconductor packages would certainly be an advantage for our package. But at this point I don't see how it would be implemented. We'll skip it for now but will keep it in mind for future updates!

I will proceed to push the latest changes and bump the version to trigger a new build.

**Comment by HansPetterBrodal** [comment]
I need to install the devel version of R and push again...

**Comment by HansPetterBrodal** [comment]
Hopefully, the package is now ready for a re-review. 

Summary of changes (also see previous answer):
- Added Bioconductor installation instructions to README and vignette.
- Removed `LazyData: true` from DESCRIPTION.
- Moved script to generate ´thrTable´ to inst/script.
- Using ´file.path´ instead of ´paste´ to ensure correct file paths.
- Added optional argument for output directory in ´podcallDdpcr´.  
- Removed use of ´paste´ inside ´message´.

Best regards,
Hans Petter Brodal

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HansPetterBrodal.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PoDCall")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PoDCall

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
