### ISSUE TITLE
imcdatasets

### ISSUE THREAD

**Issue by ndamond** [Bioconductor/Contributions#1765]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BodenmillerGroup/imcdatasets

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by ndamond** [comment]
Hi @nturaga and @lshep ,

The build fails on Windows only. It looks like the SPB is failing to load the `masks` dataset from cache (for `i386`) and to download the `images` dataset (for `x64`). Is it possible that there is not enough memory on the builder? The size in memory should be 200 Mb for `masks` and 7.4 Gb for `images`.

Do you have any suggestion on how to fix this ?

Thanks,
Nicolas

**Comment by nturaga** [comment]
@lshep I'll take over if that's ok.

**Comment by lshep** [comment]
fantastic!

**Comment by nilseling** [comment]
Hi @nturaga,

first, thank you and @lshep for dealing with this submission. We'd slowly like to make the `imcdatasets` package available on Bioconductor and wanted to check if you already had time to take a look at it. 
Thanks and best regards!

**Comment by nturaga** [comment]
I'll post your review today. Thanks

**Comment by nturaga** [comment]
# Review

Happy new year! 

## LICENSE

* Please use a specific number to the GPL license. The (>=3) isn't
  recognized. Just use GPL 3 if that is the case.

## DESCRIPTION

ok

## NAMESPACE

ok

## NEWS

ok. It is compatible with utils::news()

## R

ok.

## inst

- extdata seems to contain csv files.

## man

ok

## tests

ok

## vignettes

Good

**Comment by ndamond** [comment]
Hi @nturaga,

Thank you for your review and happy new year!

**LICENSE**
Changed as suggested.

**inst**
Is there a problem with the csv files in extdata?
We have one `metadata.csv` file, as instructed here: https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html#building-the-data-experiment-package and one `alldatasets.csv` file that lists the datasets contained in the package.

Best,
Nicolas

**Comment by nilseling** [comment]
Hi @nturaga,

currently `imcdatasets` doesn't build on macOS since the `svglite` mac binary is not yet available for R4.1
This causes a build issue for `cytomapper` that `imcdatasets` depends on: https://bioconductor.org/checkResults/devel/bioc-LATEST/cytomapper/machv2-install.html  
We currently don't know how long it takes for the new binary to become available for macOS and R4.1.
However, `svglite` is maintained by the RStudio guys and we assume support won't be dropped.
So would it be alright for now to ignore this issue?
Cheers,

Nils

**Comment by ndamond** [comment]
Hi @nturaga,

The `svglite` issue and the license name are now fixed.

The last remaining point is the .csv files in `inst/extadata`:
We have one `metadata.csv` file, as instructed here: https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html#building-the-data-experiment-package and one `alldatasets.csv` file that lists the datasets contained in the package.
Could you please tell us if that's ok ?

Thanks,
Nicolas

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ndamond.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("imcdatasets")`. The package 'landing page' will be created at

https://bioconductor.org/packages/imcdatasets

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
