### ISSUE TITLE
Summix

### ISSUE THREAD

**Issue by GregoryMatesi** [Bioconductor/Contributions#1772]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hendriau/Summix

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
Please REVIEW THE BIOCONDUCTOR PACKAGE AND SUBMISSION GUIDELINES . Your package does not have a `biocViews:` in the DESCRIPTION file. Please update and post a comment here when you are ready to start the review process.

**Comment by GregoryMatesi** [comment]
I have added the `biocViews:` field to the DESCRIPTION and am ready to start the review process.

**Comment by Kayla-Morrell** [comment]
@GregoryMatesi - In order for me to start the formal review process you must correct all ERRORs and WARNINGs produced in the build report.

**Comment by GregoryMatesi** [comment]
Hi Kayla, we have corrected all ERRORs and WARNINGS from the build report and are ready to proceed with the review process.

Thanks,
Greg

**Comment by Kayla-Morrell** [comment]
Please be sure you push a version bump so that a proper build report can be produced, as instructed [here](https://github.com/Bioconductor/Contributions/issues/1772#issuecomment-734934185)

**Comment by GregoryMatesi** [comment]
Hi Kayla, we have pushed a version bump. I believe we are ready for a new build report. Thank you.

**Comment by GregoryMatesi** [comment]
Hi Kayla,
Thank you for your help thus far. I believe I have fixed all of my errors/warnings except for one pertaining to data compression during the R CMD **build** step:

`* checking data for ASCII and uncompressed saves ... WARNING
  
  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                   old_size new_size compress
  ancestryData.rda    518Kb    407Kb       xz`
  
 Is this something that we need to ignore or do I need to fix this somehow?

**Comment by lshep** [comment]
Please fix. There are two ways to fix:   
you would do what is suggested running `R CMD build --resave-data` on your repository 
untar the tarball created in a temporary location and replace the original `.rda` file with the version of the compressed `.rda` 
 OR 
load your .rda file back into R  and re-save using the save option `compres='xz'` and replace the original .rda file. 
commit the new object using `git commit`  and git push as normal

**Comment by GregoryMatesi** [comment]
Thank you Kayla!

**Comment by Kayla-Morrell** [comment]
@GregoryMatesi, 

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The `doc/` directory isn't something we usually allow for. Is
  there a specific function for these files?

## DESCRIPTION

- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with a relevant link to Github for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: There are undefined global functions or variables in the R code
  for 'is'. Add `importFrom("methods", "is")` to the documentation and NAMESPACE
file. Also be sure that in the DESCRIPTION file you include 'methods' in the
Imports field.

## NEWS

- [ ] REQUIRED: It is good practice to include a NEWS file, but it should be
  populated with some information. For example, you could include:

Changes in version 0.99.0 (2018-05-15)
+ Submitted to Bioconductor

## Data

- [ ] REQUIRED: In the documentation for ancestryData, you should also include
  some reference/source information from where the data came from if possible.

## Vignette

- [ ] REQUIRED: Line 52, please include reference information if it's available.

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install and download the package from Bioconductor. The code
should look something like the following and should include `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Summix")
```

- [ ] REQUIRED: Non-trival executable code is a must, static vignettes are not acceptable.

- [ ] REQUIRED: The last section of the vignette should be 'Session Information'
  and should include `sessionInfo()`.

## R code

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along().
        Found in files:
        summix.R, lines 105, 118, 123, 134, 144, and 181

- [ ] REQUIRED: Use various apply functions instead of for loops where possible.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 90 
lines are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 195 lines that are not.

Best,
Kayla

**Comment by GregoryMatesi** [comment]
Thank you Kayla. I'll work through this and get back to you.

Kind regards,
Greg

**Comment by GregoryMatesi** [comment]
Hi @Kayla-Morrell, would you be able to provide some more information on why our vignette is considered "static" or "trivial" please? Do we need to simply provide more information on what each line of our code is doing similar to the [AnnotationHub vignette](https://github.com/Bioconductor/AnnotationHub/blob/master/vignettes/AnnotationHub.Rmd)?
Thanks

**Comment by Kayla-Morrell** [comment]
@GregoryMatesi - Sure, I simply mean that all code chunks should be evaluated. There are a couple code chunks  that include `eval = FALSE`. We usually don't allow for these since this code is never evaluated (minus the use in the installation section), therefore the code within could not work properly or be broken. If you are looking to just show usage of the function, not actually a line of code that the user is expected to run, I would suggest using in line code notation (single `) or just making the text italicized. I hope this clears things up for you.

Best,
Kayla

**Comment by GregoryMatesi** [comment]
Thank you.

**Comment by GregoryMatesi** [comment]
Hi Kayle,
We are having a problem pushing to our git@git.bioconductor.org:packages upstream. My author, @hendriau is able to log into the biocredentials app and it looks like she should have permissions for the Summix package. Do you have any advice on how to proceed?
![image](https://user-images.githubusercontent.com/44989448/107666472-ca75d900-6c4b-11eb-9a69-27fe7f4f6de1.png)

**Comment by GregoryMatesi** [comment]
Just wanted to provide the error as text as well. Thanks

`Audreys-MacBook-Pro-2:Summix audreyhendricks$ git push upstream main
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (12/12), 2.37 KiB | 808.00 KiB/s, done.
Total 12 (delta 5), reused 0 (delta 0)
remote: FATAL: W refs/heads/main packages/Summix GregoryMatesi DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/Summix.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/Summix.git'`

**Comment by GregoryMatesi** [comment]
OK. Sorry for flooding you with messages but I believe we got it working. We also went through all of your fixes and are hopefully ready for another review.

Thank you,
Greg

**Comment by Kayla-Morrell** [comment]
@GregoryMatesi - Thank you for making the necessary changes. I have just one formatting note and then the package should be ready for acceptance.

## NEWS

- [ ] REQUIRED: Thank you for updating the information, however it is not formatted properly. The text in the file should look like the following (with the symbols included):

Changes in version 0.99.7 (2021-02-11)
\+ Fixed multiple issues in review for development
\+ No longer using for loops in function code

Once this is fixed and looks proper I'll accept the package.

Best,
Kayla

**Comment by GregoryMatesi** [comment]
Great to hear! The NEWS file should be fixed now.

Greg

**Comment by Kayla-Morrell** [comment]
@GregoryMatesi - Looks good, I'm more than happy to accept the package.

Best,
Kayla

**Comment by GregoryMatesi** [comment]
Thank you for all your help and hard work Kayla.

Kind regards,
Greg

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GregoryMatesi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Summix")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Summix

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
