### ISSUE TITLE
methylclockData

### ISSUE THREAD

**Issue by dpelegri** [Bioconductor/Contributions#1780]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isglobal-brge/methylclockData

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi @dpelegri ,

Do you intend to also submit `methylclock` to Bioconductor? 
It seems like you advertise it as such without going through the review process first.
https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/btaa825/5909987

**Comment by dpelegri** [comment]
Hi Marcel,

Yes, we want to send the methylclock package to Bioconductor.

Sorry, it's true that we  advertise it as such without going through the review process, the package initially depended on meffil library  (https://github.com/perishky/meffil) that is neither in r-cran nor in bioconductor and we had problems to meet the bioconductor requirements, we needed to publish the paper and we did not solve it in time.

Dolors

**Comment by LiNk-NY** [comment]
Hi Dolors, @dpelegri 

Having a publication like that is quite misleading. It's unfortunate that the reviewers did not catch that. 
Any Bioconductor user wanting to use your package would do `BiocManager::install("methylclock")`
and of course it would not work. 

Please see the `methylclockData` review below.  

We are looking forward to the submission of `methylclock`. 

Best,
Marcel

---

# methylclockData #1780

## DESCRIPTION

* Include a `BugReports` field.
* Update the `biocViews` field so that it matches the tree in
https://www.bioconductor.org/packages/release/BiocViews.html
* Spell out the acronym before using it in the `Description` field
* Because you don't have any code in the package, avoid using the `Depends`
field for your dependencies. Use the `Imports` field.
* Add `utils` and `ExperimentHub` to your `Imports`

## NAMESPACE

* Looks good

## vignette

* Show how the user is supposed to download the data from `ExperimentHub`

(*Enhancement*)
* Ideally, you'd have a function where the user can see a table of the
data resources available along with the text data that you provide in the
"Cell counts" section.
* This table would show the user what kind of cells are available in each
dataset.
* Your main function could then provide users with the data they've selected.

## R/zzz.R

* Avoid `library` calls in package code and use `utils::read.csv` etc.

**Comment by LiNk-NY** [comment]
Issue closed due to inactivity

**Comment by dpelegri** [comment]
Hello, 

I apologise for not solve the different points before
It is possible to reopen the thread or I have to start the process again?

Sorry,

Dolors Pelegrí

**Comment by dpelegri** [comment]
It is possible to continue with the review process?.  
I have applied the proposed changes.

Thanks

Dolors

**Comment by LiNk-NY** [comment]
Hi Dolors, @dpelegri 
Sorry for the late response. I will re-open the issue and have a look at the changes. 
Thank you!

**Comment by LiNk-NY** [comment]
Hi Dolors, @dpelegri 
In order for the review to continue, you should respond to the review line by line. 
Thank you!
-Marcel

**Comment by dpelegri** [comment]
Hi Marcel @LiNk-NY,

Thanks for your time and review on the methylclockData package! Following are my point-to-point
reply:

**DESCRIPTION**

Include a BugReports field. 
--> Added

Update the biocViews field so that it matches the tree in
https://www.bioconductor.org/packages/release/BiocViews.html
--> Modified with : ExperimentData, SpecimenSource, Tissue, OrganismData, Homo_sapiens_Data

Spell out the acronym before using it in the Description field
--> Added the spell out  : Extrinsic epigenetic age acceleration (EEAA) 

Because you don't have any code in the package, avoid using the Depends
field for your dependencies. Use the Imports field.
Add utils and ExperimentHub to your Imports
--> Added and removed Depends field from Description


**NAMESPACE**

Looks good

**vignette**

Show how the user is supposed to download the data from ExperimentHub
--> Added in vignette

(Enhancement)

Ideally, you'd have a function where the user can see a table of the
data resources available along with the text data that you provide in the
"Cell counts" section.
This table would show the user what kind of cells are available in each
dataset.
Your main function could then provide users with the data they've selected.


**R/zzz.R**

Avoid library calls in package code and use utils::read.csv etc.
--> Removed

**Comment by LiNk-NY** [comment]
Hi Dolors, @dpelegri 
Thanks for making those changes. I will accept the package. Please address these two minor `NOTES`
either before inclusion to Bioconductor or right after. 

```
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
### This can be resolved by adding a period at the end of the `Description` field text.
* checking Rd files ... NOTE
prepare_Rd: references.Rd:40-42: Dropping empty section \details
prepare_Rd: references.Rd:43-45: Dropping empty section \source
prepare_Rd: references.Rd:46-48: Dropping empty section \references
### These should be removed if empty
```

I would also encourage you to check out the results of `BiocCheck::BiocCheck()` to address
Bioconductor-specific concerns such as including a `NEWS` file and expanding the `Description`
field in the `DESCRIPTION` file. 

Thank you for your contribution. 
Best regards,
Marcel

**Comment by dpelegri** [comment]
Hi @LiNk-NY,

Thanks a lot for your help.

Dolors

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dpelegri.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("methylclockData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methylclockData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
