### ISSUE TITLE
scTypeR

### ISSUE THREAD

**Issue by jgriss** [Bioconductor/Contributions#1798]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/grisslab/scTypeR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by jgriss** [comment]
Hi @mtmorgan,

We've now renamed the package as discussed in #1784 

Thanks a lot!

Johannes

**Comment by jgriss** [comment]
Hi @mtmorgan 

We committed some code changes to fix the timeout issue to `git@git.bioconductor.org:packages/scTypeR` but it apparently didn't trigger a new build. Anything we can do to start this again?

Thanks a lot!

Johannes

**Comment by mtmorgan** [comment]
Hi Johannes -- I can see the commit, but not a version bump (to 0.99.1), which is required to trigger a build...

**Comment by jgriss** [comment]
Hi!

Thanks a lot for the quick reply! We made the change but forgot to add 
it to the commit...

Sorry about that!

Kind regards,
Johannes

**Comment by mtmorgan** [comment]
17 December, 2020

DESCRIPTION 

- Good!

NEWS

- hmm, if this is not maintained, then better not to include the file

vignettes

- please add `eval = FALSE` to the code chunks involving package installation.

R

- the code looks good; I offer mostly stylistic suggestions here to increase readability; comments on specific lines should be applied to all code.

- class.R: 217 `cat(paste0(...))` (also `message()`, `stop()`) can usually (expect when needing to `collapse =`) be written as `cat(...)`, since `paste0()` is called internally

- class.R: 218 use accessors `cell_type(ojbect)` rather than `@`, even in internal code

- class.R: 250 consider simplifying single-method generics to plain-old-functions, e.g.,

    ```
    cell_type <- function(classifier)
        classifier@cell_type
    ```
    
- classifier.R:113 consider an indentation style that allows for more readability (consitent 4-space indentation) and more characters per line (still less than 80)

    ```
    parent_process <- process_parent_clf(
        train_obj, seurat_parent_tag_slot, parent_cell, parent_clf, 
        path_to_models, zscore, seurat_assay, seurat_slot
    )
     ```

- classifier.R:177 very long, nested expressions are dificulat to read (I'm not sure the following is any better, or whether further improvements are possible...)

    ```
    test <- 
        (
            !is.null(parent_process$parent.clf) &&
            tolower(parent_process$parent.clf@cell_type) == 
                tolower(parent_process$parent_cell)
        ) || (
            tolower(parent_process$parent_cell) %in% 
                tolower(names(parent_process$model_list))
        )
    if (test) {
    ```

- support.R: 405 a less compressed style will be more readable

    ```
    x <- SummarizedExperiment::colData(obj)[, tag_slot], 
      tag = unlist(lapply(X, function(x) {
        if (x %in% pos.val || tolower(x) %in% tolower(cell_type)) {
          "yes"
        } else { 
          "no"
        }
    ))
    ```

  ... but this seems like it is just a vector comparison?
  

    ```
    x <- SummarizedExperiment::colData(obj)[, tag_slot], 
    test <- (x %in% pos.val) | (tolower(x) %in% tolower(cell_type))
    ifelse(test, "yes", "no")
    ```

- support.R:459 use `message()` (directed to 'stderr') when reporting progress / providing diagnostics / etc.

man

- consider grouping non-exported functions (e.g., `checkCellTypeValidity()` onto a common help page (e.g., using the `@rdname` roxygen2 tag) marked with keyword `"internal"` to simplify the user's navigation of the help pages.

tests

- good!

**Comment by jgriss** [comment]
Hi @mtmorgan 

Thank you very much for the detailed review! We tried to address all your points in the latest push.

While adapting the package, we realised that there is a name collision with an existing package: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03700-5

Therefore, we now changed the package name again to scClassifR.

Should we create a new issue again in order to avoid the error during the build test?

Kind regards,
Johannes

**Comment by mtmorgan** [comment]
@lshep can you guide us on the name change for this package? can we just rename it in git.bioconductor.org?

**Comment by lshep** [comment]
@mtmorgan  yes change the name on git.bioconductor.org  and I assume there will need to be updates in the package.conf for push access.  
I will take care of updating on the SPB database now.

**Comment by nturaga** [comment]
Hi @mtmorgan and @lshep Just following up on this a little more, I've made the changes needed on packages.conf and git.bioconductor. 

Now I think, it's also up to the author to change his package name on github from scTypeR to scClassifR. 

Best,

Nitesh

**Comment by jgriss** [comment]
@nturaga Thanks a lot for the help and the changes!

We've already renamed our GitHub repo accordingly: https://github.com/grisslab/scClassifR

Can you let me know when you changed the bioconductor github repo so we can adapt our settings?

Again, thanks a lot to everyone for the great support!

Best,
Johannes

**Comment by lshep** [comment]
I believe the change is already made.  Can you update the remotes to be sure to point to the correctly renamed git.bioconductor repository ( https://bioconductor.org/developers/how-to/git/new-package-workflow/  ).  If you try to push a version bump in the description it should now trigger an automatic build.

**Comment by jgriss** [comment]
@lshep Great! Thanks a lot!

**Comment by jgriss** [comment]
Hi @mtmorgan 

I believe that the `Error` label is no longer correct. The build process seems to be fine. The `Warning` we got was only on the windows system and seems to be related to the known doc issue.

Is there anything else we need to do?

Thanks a lot!

Johannes

**Comment by jgriss** [comment]
@mtmorgan Thanks a lot for the fast review!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jgriss.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scClassifR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scClassifR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by jgriss** [comment]
Hi @mtmorgan,

Looking at the latest build report I realised that there is already a package called `scClassify` with a comparable functionality (also classifying cells in scRNA-seq dataset).

I'm sorry we missed that!

May I ask you to remove our package from the Bioconductor again until we found a more suitable name?

Thanks a lot!

Johannes

**Comment by mtmorgan** [comment]
Because of the internal mechanisms we use, *your* scClassify package was not ever added to the public manifest. If you'd like to rename your package, please let me know the details...
