### ISSUE TITLE
RoDiCE

### ISSUE THREAD

**Issue by ymatts** [Bioconductor/Contributions#1800]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ymatts/RoDiCE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by nturaga** [comment]
Hi @ymatts 

Happy new year. 

- [ ] You have to issue a new version bump so we can take a look at the build report.  It seems the 'git clone' failed in the most recent one. 

# Review RoDICE

## DESCRIPTION

- Expand the Description section to resemble the abstract of a paper.

- Use Authors@R instead of Author and Maintainer fields. Please check
  http://bioconductor.org/developers/package-guidelines/#description

* Update R version dependency from 3.6.0 to 4.1.

## NAMESPACE

- ok

## R

- Avoid sapply(); use vapply()
  coptest_p.R (line 105, column 11)
  coptest_p.R (line 106, column 11)

- Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        coexvis.R (line 91, column 36)
        coexvis.R (line 96, column 14)
        coptest_p.R (line 55, column 12)
        netvis.R (line 132, column 14)
        netvis.R (line 153, column 14)
        parse_corum.R (line 25, column 24)
        parse_corum.R (line 27, column 24)-

- In your code try to use the R way of assignment, i.e `<-` instead of
  the `=`.

- Avoid functions declared within functions. It becomes harder to
  debug. It also doesn't add any value, just declare them outside as
  helper functions.

- remove commented out code.

- Check the document
  http://bioconductor.org/developers/how-to/coding-style/. End user
  messages especially, use `print()` only to display an object,
  otherwise use the function `message()`.

- As a general improvement, closely follow the coding style points in
  the document above.


Once I get a build report and see the an ERROR free build report we can proceed to the second review.

**Comment by nturaga** [comment]
Hi 

I'm closing this issue since it seems I've not gotten a reply from you about fixing the issues presented in the review. Please open again when you are ready to fix the issues. 

There is no problem in closing and reopening the issue when you are ready again. If you have any trouble with it, let me know.

Best,

Nitesh
