### ISSUE TITLE
MACSr: R wrapper of MACS3

### ISSUE THREAD

**Issue by hubentu** [Bioconductor/Contributions#1806]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hubentu/MACSr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
Your package requires 'biocViews' terms from the Software hierarchy at http://bioconductor.org/packages/devel/BiocViews.html#___Software ; see item 10 of http://bioconductor.org/developers/package-guidelines/#description

**Comment by hubentu** [comment]
@mtmorgan Updated 'biocViews' terms, Thanks!

**Comment by mtmorgan** [comment]
Have you considered using [basilisk](https://bioconductor.org/packages/devel/basilisk) to manage python dependencies? It will provide a robust, cross-platform user environment, and will allow R packages using conflicting versions of python packages to be loaded at the same time.

**Comment by hubentu** [comment]
Hi @mtmorgan , the `basilisk` package looks promising. I will try to rewrite the package. There are some troubles when trying this package because our package used some additional python helper functions as input.

**Comment by mtmorgan** [comment]
Great, the maintainer of the basilisk package is very knowledgable and I am sure willing to help with details if you run into problems.

**Comment by qhu75** [comment]
Hi @mtmorgan @hpages The package uses `basilisk` to manage the python library and ready for review now. Thanks!

**Comment by hubentu** [comment]
Hi @mtmorgan @hpages The package uses basilisk to manage the python library and ready for review now. Thanks!

**Comment by mtmorgan** [comment]
to trigger an automatic build, remember to push the most recent version to git.bioconductor.org

**Comment by hpages** [comment]
Hi @hubentu ,

Thanks for submitting MACSr. Please note that the last build by the SPB (Single Package Builder) reported some problems (`"skipped, UNSUPPORTED"`, see above). Unfortunately, we can't see the details because the link to the report has expired. Please bump the package version in order to trigger a new build. We need a clean build before we proceed with the review.

Also note that on my system (Ubuntu 20.10) `R CMD BiocCheck` produces 13 notes, which is a lot. Please address as many as you can.

Thanks,
H.

**Comment by hubentu** [comment]
Hi @hpages , we added `.BBSoptions` to skip `Windows` which caused the "UNSUPPORTED" problem. Our software doesn't support the Windows system. The overtime `WARNINGS` was caused by multiple time-consuming test examples, which is necessary to make sure the results are consistent with the original MACS tool.

Thanks,
Qiang

**Comment by hpages** [comment]
I see. Thanks for the explanation. I'll review ASAP.

H.

**Comment by hpages** [comment]
Hi,

Sorry for the delay.

Some examples are failing because they rely on the **MACSdata** package that is not available:
```
> library(MACSr)
> example(bdgbroadcall)

bdgbrd> eh <- ExperimentHub::ExperimentHub()
snapshotDate(): 2021-01-28

bdgbrd> CHIP <- eh[["EH4558"]]
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable)
  (2020-11-18 r79449)
Installing package(s) 'MACSdata'
loading from cache

bdgbrd> CTRL <- eh[["EH4563"]]
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable)
  (2020-11-18 r79449)
Installing package(s) 'MACSdata'
loading from cache

bdgbrd> p1 <- pileup(CHIP, outdir = tempdir(),
bdgbrd+ outputfile = "pileup_ChIP_bed.bdg", format = "BED")
sh: 1: .: Can't open ~/.cache/basilisk/1.3.6/0/etc/profile.d/conda.sh
Error in system(paste(act.cmd, collapse = " "), intern = TRUE) : 
  error in running command
In addition: Warning messages:
1: package ‘MACSdata’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: package ‘MACSdata’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```
You need to:
1. Submit **MACSdata** as an additional package (it needs to be submitted it in this issue).
2. Add **MACSdata** to the `Suggests:` field of **MACSr**.
3. Bump **MACSr** version.

Also please consider using proper formatting/indentation for your code. For example something like this:
```
     eh <- ExperimentHub::ExperimentHub()
     CHIP <- eh[["EH4558"]]
     CTRL <- eh[["EH4563"]]
     p1 <- pileup(CHIP, outdir = tempdir(),
     outputfile = "pileup_ChIP_bed.bdg", format = "BED")
     p2 <- pileup(CTRL, outdir = tempdir(),
     outputfile = "pileup_CTRL_bed.bdg", format = "BED")
     c1 <- bdgcmp(p1$outputs, p2$outputs, outdir = tempdir(),
     oprefix = "bdgcmp", pseudocount = 1, method = "FE")
     bdgbroadcall(c1$outputs, cutoffpeak = 2, cutofflink = 1.5,
     outdir = tempdir(), outputfile = "bdgbroadcall")
```
is very hard to read.

Thanks!
H.

**Comment by hubentu** [comment]
Thanks, Lori @lshep ! Should I push the data package to git.bioconductor.org? so the `MACSr` can be built in the Bioc server. It seems I don't have the permission now.

Hi @hpages , here is the additional data package:
`AdditionalPackage: https://github.com/hubentu/MACSdata`

Thanks,
Qiang

**Comment by lshep** [comment]
Unfortunately, I can't correct it ... could you post the AdditionalPackages without being in code quotes.

**Comment by lshep** [comment]
I don't I'm able to correct it for you but could you make a comment with AdditionalPackages without being in code quotes.  I'll look at correcting this for future submissions but it will take some time.

**Comment by lshep** [comment]
@hubentu  sorry for the confusion.  See my comment above.  Once the system recognizes the github link, the code on our backend will make the git.bioconductor.org repository and kick off an initial build. Then the software will be able to find it.

**Comment by hubentu** [comment]
AdditionalPackage: https://github.com/hubentu/MACSdata

**Comment by hubentu** [comment]
Hi @lshep , sorry for not reading the document clearly... Thanks!

**Comment by lshep** [comment]
Yep.  The additional package still has to be approved in the backend to have the build kicked off and add to git (@mtmorgan) .  Then the software will be able to find it.  Cheers

**Comment by hpages** [comment]
Thanks @hubentu for submitting additional package MACSdata.

Both packages satisfy our guidelines and can be added to Bioconductor.

Best,
H.

**Comment by hubentu** [comment]
@hpages Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hubentu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MACSr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MACSr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hubentu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MACSdata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MACSdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
