### ISSUE TITLE
SCArray

### ISSUE THREAD

**Issue by zhengxwen** [Bioconductor/Contributions#1809]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhengxwen/SCArray

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5] (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LTLA** [comment]
Some comments in passing:

- Seems like you'll want to implement `extract_sparse_array()` as well, if you want to take advantage of sparsity.
- We already have a `GDSArray` class; perhaps there is some potential for consolidation, to avoid duplication of effort.

**Comment by mtmorgan** [comment]
@zhengxwen will you implement the sparsity method mentioned in https://github.com/Bioconductor/Contributions/issues/1809#issuecomment-744166371 ?

**Comment by LTLA** [comment]
What I want to know is: what value does **SCArray** provide over **GDSArray**? It seems like the `DelayedArray`-related work in this package could be consolidated into **GDSArray** so that all applications using GDS files can benefit, even those that aren't single-cell-related. Then **SCArray** could provide single-cell-specific functionality on top of the more general **GDSArray**.

**Comment by zhengxwen** [comment]
1) I will implement the sparsity method `extract_sparse_array()`, and submit a new one.

2) The current GDSArray heavily relies on the SNPRelate and SeqArray packages (the two package I wrote) (e.g., see the function `.get_gds_dimnames` in the GDSArray.
It **exclusively** supports the GWAS SNP and Sequencing variant GDS files, however GDS is more general for a data container.
I have contacted with Qian earlier this year about the generalization of GDSArray (but no improvement so far).

The current SCArray only contains a lightweight wrapper of DelayedArray, and uses the latest feature of the gdsfmt package (i.e., sparse matrix read/write). SCArray defines the data variables and structure needed for SingleCellExperiment. In addition, GDSArray still needs to be improved according to its efficiency.

**Comment by zhengxwen** [comment]
A new submission SCArray_0.99.1 (commit id 6d5db6129df7aa392048f9425397ed00c0432dac):
1. add `extract_sparse_array()`
2. fix warnings

**Comment by mtmorgan** [comment]
This seems like a very useful integration of the GDS and DelayedArray frameworks. I have a few minor comments.

DESCRIPTION, etc

- Review the Suggests: field; are these packages all used in the vignettes / examples?

vignettes

- SCArray.Rmd:41 please add `{R, eval = FALSE}` to the installation code chunk.

- please provide text to introduce and interpret the output of each code chunk.

R (comments on specific lines may require changes throughout)

- AllClasses.R:58 consider developing simple (internal, if appropriate) accessors to always avoid slot access, including in package code

    ```
    .filename <- function(x) x@filename
    ...
        "File: ", .filename(x), "\n",
    ```

- AllClasses.R:68 for robust code, validate all user inputs, e.g.,

    ```
    stopifnot(is.???(index), !anyNA(index))
    ```
- scarray_main.r:44 `.cfunction` and `.cfunction2` are not used, delete?
        
- scarray_main.R:112 the use of `stop(sprintf(...` seems unnecessary; 

    ```
    stop(
        "FileVersion '", as.character(version)))
        "' (should be v1.0), consider updating SCArray"
    )
    ```

**Comment by zhengxwen** [comment]
* `Review the Suggests: field`: update the package list
* `SCArray.Rmd:41 please add {R, eval = FALSE}`: fixed
* `please provide text to introduce and interpret the output of each code chunk`: added more description
* `R (comments on specific lines may require changes throughout)`: add more comments
* `AllClasses.R:58 consider developing simple (internal, if appropriate) accessors to always avoid slot access`: add `.filename()` and others
* `AllClasses.R:68 for robust code, validate all user inputs`: add `stopifnot(is.list(index), !anyNA(index))`
* `scarray_main.r:44 .cfunction and .cfunction2 are not used`: removed
* `scarray_main.R:112 the use of stop(sprintf(... seems unnecessary`: removed

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhengxwen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SCArray")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SCArray

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Liubuntu** [comment]
> 1. I will implement the sparsity method `extract_sparse_array()`, and submit a new one.
> 2. The current GDSArray heavily relies on the SNPRelate and SeqArray packages (the two package I wrote) (e.g., see the function `.get_gds_dimnames` in the GDSArray.
>    It **exclusively** supports the GWAS SNP and Sequencing variant GDS files, however GDS is more general for a data container.
>    I have contacted with Qian earlier this year about the generalization of GDSArray (but no improvement so far).
> 
> The current SCArray only contains a lightweight wrapper of DelayedArray, and uses the latest feature of the gdsfmt package (i.e., sparse matrix read/write). SCArray defines the data variables and structure needed for SingleCellExperiment. In addition, GDSArray still needs to be improved according to its efficiency.

Hi @zhengxwen Good work! I am actually up now for updating the GDSArray to accommodate more general form of gds files. Please feel free to make PR as to the efficiency and other factors. I am happy to add you to the package authors (or possibly maintainer later to accommodate with any gdsfmt updates).
