### ISSUE TITLE
LRcellTypeMarkers

### ISSUE THREAD

**Issue by marvinquiet** [Bioconductor/Contributions#1818]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/marvinquiet/LRcellTypeMarkers

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by marvinquiet** [comment]
AdditionalPackage: https://github.com/marvinquiet/LRcell

**Comment by marvinquiet** [comment]
Dear Reviewer,

I found from the build report that the error message was 
```
> res <- LRcell(example_gene_pvals, species="mouse", region="FC", method="LR")
using temporary cache C:\Users\pkgbuild\AppData\Local\Temp\RtmpYv65Zc/BiocFileCache
snapshotDate(): 2020-12-14
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable)
  (2020-11-05 r79401)
Installing package(s) 'LRcellTypeMarkers'
package 'LRcellTypeMarkers' is not available for this version of R
...
...
Error: failed to load resource
  name: EH4548
  title: Mouse Frontal Cortex Marker Genes
  reason: 1 resources failed to download
```

In the LRcellTypeMarkers pkg, I wrote R version >=4.1 as I understand as the "R-devel" version and it seems to be successfully built on Linux. Thus, I might not understand which version should be the correct one for package submission, is R >=3.6 okay? (Because originally I wrote R >=3.6 and check or BiocCheck indicates me to change it to R>=4.1)

**Comment by marvinquiet** [comment]
> Dear Reviewer,
> 
> I found from the build report that the error message was
> 
> ```
> > res <- LRcell(example_gene_pvals, species="mouse", region="FC", method="LR")
> using temporary cache C:\Users\pkgbuild\AppData\Local\Temp\RtmpYv65Zc/BiocFileCache
> snapshotDate(): 2020-12-14
> Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable)
>   (2020-11-05 r79401)
> Installing package(s) 'LRcellTypeMarkers'
> package 'LRcellTypeMarkers' is not available for this version of R
> ...
> ...
> Error: failed to load resource
>   name: EH4548
>   title: Mouse Frontal Cortex Marker Genes
>   reason: 1 resources failed to download
> ```
> 
> In the LRcellTypeMarkers pkg, I wrote R version >=4.1 as I understand as the "R-devel" version and it seems to be successfully built on Linux. Thus, I might not understand which version should be the correct one for package submission, is R >=3.6 okay? (Because originally I wrote R >=3.6 and check or BiocCheck indicates me to change it to R>=4.1)
> 
> Thank you in advance!
> 
> Sincerely,

I just changed my dependency to R>=3.6 and pushed my code again.

**Comment by marvinquiet** [comment]
Dear Reviewer @hpages,

I get the warnings to update R package to 4.1, but it seems that the previous report said that `package 'LRcellTypeMarkers' is not available for this version of R`. I am not sure what happened and what is my correct next step. I may need your assistance on this. Any suggestions are appreciated!

Sincerely,

**Comment by lshep** [comment]
Please update to R 4.1, this is the devel version of R and what the packages are currently being built under for Bioc devel 3.13.  I'll investigate today why the resources do not seem available as they should be -- I'll comment back when I have further information.

**Comment by lshep** [comment]
I might try kicking off a manual build or two in testing -- do not be alarmed if you see builds triggered/reports posting.

**Comment by marvinquiet** [comment]
Dear Reviewer @lshep,

Got you! I will update it back now.

Sincerely,

**Comment by marvinquiet** [comment]
Dear Reviewer @lshep ,

I have changed the dependency back to R>=4.1 and now it has the vignettes build error. I think it is still caused by that some resources in LRcellTypeMarkers could not be found.

```
Error: processing vignette 'LRcellTypeMarkers-vignette.Rmd' failed with diagnostics:
failed to load resource
  name: EH4548
  title: Mouse Frontal Cortex Marker Genes
  reason: 1 resources failed to download
--- failed re-building LRcellTypeMarkers-vignette.Rmd
```

I checked it again on my own computer (macOS Catalina 10.15.7) with R devel version but could not repeat this error. I am not sure what possible moves are. I might just wait until further notice. Thank you for the hard work!!

Sincerely,

**Comment by lshep** [comment]
I just went on mac and tried to download a few different ways with no issues. I'm going to try and kick off a manual build of the package that will hopefully resolve the mac error.  if it continues I'll look back into it.

**Comment by marvinquiet** [comment]
Hi @lshep,

Thank you so much for your help! Should I just wait for further notice or what else can I do to help release my package?

Sincerely,
Wenjing

**Comment by lshep** [comment]
@hpages  will still do a review of both LRcellTypeMarkers and LRcell for any additional comments.  

The ERROR remains because there was an ERROR also for LRcell software package.  Now that the experimentdata package built , I will kick off a new build of that as well so @hpages  will have the latest report on both to look at.  Expect that to appear shortly. 

Cheers,

**Comment by marvinquiet** [comment]
Hi @lshep,

Got you! Thank you for helping manually build and test my packages!

Sincerely,
Wenjing

**Comment by hpages** [comment]
Hi @marvinquiet ,

Thanks for submitting the Marker Genes datasets to ExperimentHub.

Note that these datasets are conceptually matrices. Have you considered representing them as such instead of data.frames? The advantage of using matrices instead of data.frames is that one can directly use matrix summarization methods (e.g. methods from the **matrixStats** package) on a matrix. OTOH with a data.frame, the number of statistical methods that are available is very limited so one almost always needs to turn it first into a matrix before they can start doing any serious work with it:
```
library(ExperimentHub)
eh <- ExperimentHub()
mouse_FC <- eh[['EH4548']]

library(matrixStats)

colMaxs(mouse_FC, na.rm=TRUE)
# Error in colMaxs(mouse_FC, na.rm = TRUE) : 
#   Argument 'x' must be a matrix or a vector.

head(colMaxs(as.matrix(mouse_FC), na.rm=TRUE))
# [1] 57.72439 68.45864 36.61473 45.20171 72.88490 61.07701
```

Also the vignette doesn't say much about what can be done with these datasets. Please provide more examples.

Thanks,
H.

**Comment by marvinquiet** [comment]
Hi @hpages,

Thank you for your suggestions, I can change them to matrices! Should I just do the changes on the dataset and then uploaded them to the S3 and notify experiment hub members? Do I need to request another authentication key because I think my previous one should expire by now?

I may need to explain my current situation a bit.

These datasets are bundled with LRcell to work. In the LRcell package, I want users to specify some information and then I will grab this data frame (or matrices) and use `get_markergenes()` function to generate marker genes https://github.com/marvinquiet/LRcell/blob/2f9d5802213d65b35ad548a17e9df73acc785203/R/LRcell.R#L122. I listed that information in the LRcell vignette [here](https://github.com/marvinquiet/LRcell/blob/2f9d5802213d65b35ad548a17e9df73acc785203/vignettes/LRcell-vignette.Rmd#L131). Another reason that I did not list in LRcellTypeMarkers vignette because I think these two are very closely related and cross-reference will be triggered if I show an example in LRcellTypeMarkers using LRcell.

Does this sound reasonable?

Sincerely,
Wenjing

**Comment by lshep** [comment]
While you are waiting on @hpages  response,  If you change the dataset and save with files of the same name, yes you could just reupload and I could replace the files on S3 and the new versions of these files would then be linked in the ExperimentHub.  I'll find your email and resend credentials to you.

**Comment by marvinquiet** [comment]
Hi @hpages,

With the help of @lshep, I have re-uploaded my data in matrix form. 

Regarding my previous reply, may I know what is the best way for providing examples on using my data without cross-reference? I look forward to your reply!

Sincerely,
Wenjing

**Comment by marvinquiet** [comment]
Hi @hpages,

This is Wenjing again. I was wondering if any further suggestions on my package? The reason I am asking is that I am planning to submit a manuscript in which I want to address that my software is an R Bioconductor package. 

Sincerely,
Wenjing

**Comment by hpages** [comment]
Hi @marvinquiet ,

Thanks for re-uploading your data in matrix form. Please bump **LRcel**l and **LRcellTypeMarkers** versions in order to trigger new builds for the 2 packages. Note that **LRcell**'s unit tests are failing at the moment:
```
> test_check("LRcell")
Generate enrichment score for each gene..
  |======================================================================| 100%
total gene number: 3 
══ Failed tests ════════════════════════════════════════════════════════════════════════════════════════════════════════
── Failure (test-LRcell.R:6:5): LRcell works on provided example dataset (Alzheimer's disease) ───────────────────────────
res$FC[which.min(res$FC$p.value), ]$cell_type not equal to "Microglia".
1/1 mismatches
x[1]: ""
y[1]: "Microglia"

[ FAIL 1 | WARN 1 | SKIP 0 | PASS 2 ]
Error: Test failures
```
See my `sessionInfo()` below.

The **LRcell**'s vignette uses datasets that are tied to the **LRcellTypeMarkers** package so the vignette should say a word about the latter and you should put an explicit `library(LRcellTypeMarkers)` statement early on. This is not technically required but it has the merit to make your reader well aware of the existence of the **LRcellTypeMarkers** package and the need to have it installed. Also **LRcellTypeMarkers** would need to be added to **LRcell**'s `Suggest` field.

About the concern you expressed earlier: "cross-reference will be triggered if I show an example in **LRcellTypeMarkers** using **LRcell**". I'm not sure what the concern is. I don't see any issue with using **LRcell** in **LRcellTypeMarkers**'s vignette. Of course you'll need to add **LRcell** to **LRcellTypeMarkers**'s `Suggest` field if you do so. AFAIK packages can mutually suggest each others, it should not be a problem.

Thanks,
H.

**sessionInfo():**
```
R Under development (unstable) (2021-02-05 r79941)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.1.r79941/lib/libRblas.so
LAPACK: /home/hpages/R/R-4.1.r79941/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] LRcellTypeMarkers_0.99.2 LRcell_0.99.3            ExperimentHub_1.17.1    
[4] AnnotationHub_2.23.2     BiocFileCache_1.15.1     dbplyr_2.1.0            
[7] BiocGenerics_0.37.1      testthat_3.0.2          

loaded via a namespace (and not attached):
 [1] ggrepel_0.9.1                 Rcpp_1.0.6                   
 [3] png_0.1-7                     ps_1.5.0                     
 [5] Biostrings_2.59.2             assertthat_0.2.1             
 [7] rprojroot_2.0.2               digest_0.6.27                
 [9] mime_0.10                     R6_2.5.0                     
[11] stats4_4.1.0                  RSQLite_2.2.3                
[13] httr_1.4.2                    ggplot2_3.3.3                
[15] pillar_1.4.7                  zlibbioc_1.37.0              
[17] rlang_0.4.10                  curl_4.3                     
[19] rstudioapi_0.13               blob_1.2.1                   
[21] S4Vectors_0.29.7              desc_1.2.0                   
[23] BiocParallel_1.25.4           bit_4.0.4                    
[25] munsell_0.5.0                 shiny_1.6.0                  
[27] compiler_4.1.0                httpuv_1.5.5                 
[29] pkgconfig_2.0.3               htmltools_0.5.1.1            
[31] tidyselect_1.1.0              KEGGREST_1.31.1              
[33] tibble_3.0.6                  interactiveDisplayBase_1.29.0
[35] IRanges_2.25.6                withr_2.4.1                  
[37] crayon_1.4.1                  dplyr_1.0.4                  
[39] later_1.1.0.1                 rappdirs_0.3.3               
[41] grid_4.1.0                    xtable_1.8-4                 
[43] gtable_0.3.0                  lifecycle_1.0.0              
[45] DBI_1.1.1                     magrittr_2.0.1               
[47] scales_1.1.1                  cli_2.3.0                    
[49] cachem_1.0.4                  XVector_0.31.1               
[51] promises_1.2.0.1              ellipsis_0.3.1               
[53] filelock_1.0.2                generics_0.1.0               
[55] vctrs_0.3.6                   tools_4.1.0                  
[57] bit64_4.0.5                   Biobase_2.51.0               
[59] glue_1.4.2                    purrr_0.3.4                  
[61] BiocVersion_3.13.1            fastmap_1.1.0                
[63] yaml_2.2.1                    AnnotationDbi_1.53.1         
[65] colorspace_2.0-0              BiocManager_1.30.10.10       
[67] memoise_2.0.0                
```

**Comment by marvinquiet** [comment]
Hi @hpages,

Thank you for your previous suggestions.

I have updated my packages accordingly. Right now, I am waiting for uploading the new dataset to my LRcellTypeMarkers ExperimentHub package and after that, I will update my LRcell/LRcellTypeMarkers package again on vignettes.

I would like to know what is my next step to further revise my package. Thank you in advance!

Sincerely,
Wenjing

**Comment by hpages** [comment]
> Right now, I am waiting for uploading the new dataset to my LRcellTypeMarkers ExperimentHub package and after that, I will update my LRcell/LRcellTypeMarkers package again on vignettes.

No need to wait. Please proceed. Thanks!

**Comment by lshep** [comment]
@marvinquiet  were you waiting on something from us for ExperimentHub?  We changed the files to the matrix format when requested on 01-29-21.

**Comment by marvinquiet** [comment]
Hi @lshep, yes, I sent emails to hubs@bioconductor.org but did not get any responses. I might paste it here:

> Previously I have submitted two packages, LRcell the software package and LRcellTypeMarkers the ExperimentHub package. I would like to upload one more cell-type marker genes information into LRcellTypeMarkers package. 

> I have updated my metadata and bumped the version of my LRcellTypeMarkers package. May I have the AWS access key and ID again to upload my new dataset? Thank you in advance!

Please let me know what I should do for uploading one more dataset.

Sincerely,
Wenjing

**Comment by hpages** [comment]
OK, the packages are almost ready. One last thing:

The vignette contains:

> The package can be installed by using devtools.
> ```
> install.packages("devtools")
>
> library(devtools)
> devtools::install_github("marvinquiet/LRcell")
> ```
> Or you can download the code from the Github repo, build and install package yourself as follows:
> ```
> git clone https://github.com/marvinquiet/LRcell.git
> R CMD BUILD --no-build-vignettes LRcell  
> R CMD INSTALL LRcell_xxx.tar.gz
> ```

HOWEVER, this is not how a Bioconductor package should be installed. Because of Bioconductor 6-month release cycles and because Bioconductor has a notion of release and devel, Bioconductor users should always use `BiocManager::install()` to install packages. This will spare them a lot of headaches with version mismatches. Please instruct your users to install the package with `BiocManager::install()` and do not encourage them to install from GitHub. See details instructions of how to properly install Bioconductor packages [here](https://bioconductor.org/install/).

Thanks,
H.

**Comment by marvinquiet** [comment]
Hi @hpages,

Thank you for your suggestions! I will modify accordingly and let you know when I finished.

Sincerely,
Wenjing

**Comment by hpages** [comment]
Hi @marvinquiet , are you finished? H.

**Comment by marvinquiet** [comment]
Hi @hpages,

Thanks for checking in! 

Sorry, I forgot to let you know my progress. Yes, I think I have updated the vignette according to your suggestion and the package is ready to go.

Sincerely,
Wenjing

**Comment by hpages** [comment]
Thank you. You have a typo ("BiocManger" instead of "BiocManager") in the vignette and `README.md`. Please address and the packages will be good to go.

Thanks,
H.

**Comment by marvinquiet** [comment]
Thanks for letting me know. Just fixed it!

Sincerely,
Wenjing

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/marvinquiet.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("LRcellTypeMarkers")`. The package 'landing page' will be created at

https://bioconductor.org/packages/LRcellTypeMarkers

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/marvinquiet.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("LRcell")`. The package 'landing page' will be created at

https://bioconductor.org/packages/LRcell

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
