### ISSUE TITLE
ramr

### ISSUE THREAD

**Issue by oleksii-nikolaienko** [Bioconductor/Contributions#1822]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BBCG/ramr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by oleksii-nikolaienko** [comment]
Hi lshep,
I will probably ask the same question that many other people ask, but I couldn't find an explanation on Bioconductor's R version requirement. Warning in my build log suggests to increase it to R version 4.1, but it makes no sense, as the actual requirement for my package is 3.5.0, while the latest devel version is 4.0.3. I actually want people to use my package, reviewers of my paper to check it on their machines. If I put 4.1 no one would be able to install it.
What should I do with this warning?

**Comment by lshep** [comment]
The current released version of R is 4.0.3 (not devel) which technically is linked with our Bioc 3.12 packages. We say R 4.1 because that is the current devel version of R which is what our devel Bioc 3.13 is currently building off of.  We coordinate our Spring release with the R release so they stay in sync.  We have no way on our builders to guarantee that a package would work on a previous version of R (and therefore also potentially previous versions of packages which are sometime very closely tied to an R release).  R had significant changes from the jump of 3.6 to 4.0.  We would recommend minimally making the requirement 4.0.3  and I could ignore the warning.

**Comment by oleksii-nikolaienko** [comment]
Ok, thank you for the clarification. I'll change the requirement to 4.0.3 and resubmit on weekend

**Comment by oleksii-nikolaienko** [comment]
Hi @lshep,
the only warning is on R version. Hope the rest is OK in order to be included

**Comment by lshep** [comment]
Sorry for the delay. I was away for the holiday.  I should have a review for you within the next few days.

**Comment by lshep** [comment]
Good use of Bioconductor GRanges class.   Please see the following minor comments: 

**Build report**

- [ ] Please use donttest instead of dontrun. donttest requires valid R code while dontrun does not. 

- [ ] Another option instead of donttest/dontrun in man pages for options like graphing is using `if(interactive())` 

**DESCRIPTION**

- [ ] Please remove `LazyData: true`. We have rarely found it useful and can actually slow installation of packages. 

**Vignette:**

- [ ] R 4.1 has made changes to the default options for timeout for downloading files to 60 seconds. You might want to add a note before downloading and unpacking raw IDAT files that if users experience timeouts to adjust the `options(timeout=)`

- [ ] I'm not sure if you are using these internally or if they are coming from a dependent package.  If they are in a dependent package you can ignore, however if this in your code you should not use deprecated functions

```
  Warning messages:
1: `distinct_()` is deprecated as of dplyr 0.7.0.
Please use `distinct()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

**R code:**

getAMR.R

- [ ] Please remove any non active commented out code and TODO comments


Please address the above issues. When ready perform a version bump for the new build report to generate and comment back here with an update.  
Cheers!

**Comment by oleksii-nikolaienko** [comment]
Thanks for the review, @lshep. New version builds with the only warning on R version.
Here are the comments:

> **Build report**
> * [ ]  Please use donttest instead of dontrun. donttest requires valid R code while dontrun does not.

have changed to donttest

> **DESCRIPTION**
> * [ ]  Please remove `LazyData: true`. We have rarely found it useful and can actually slow installation of packages.

removed LazyData

> **Vignette:**
> * [ ]  R 4.1 has made changes to the default options for timeout for downloading files to 60 seconds. You might want to add a note before downloading and unpacking raw IDAT files that if users experience timeouts to adjust the `options(timeout=)`

added note on the potential timeout issue

> * [ ]  I'm not sure if you are using these internally or if they are coming from a dependent package.  If they are in a dependent package you can ignore, however if this in your code you should not use deprecated functions

those are some internal dplyr warnings

> **R code:**
> getAMR.R
> * [ ]  Please remove any non active commented out code and TODO comments

have removed them

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/oleksii-nikolaienko.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ramr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ramr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
