### ISSUE TITLE
TraRe

### ISSUE THREAD

**Issue by ubioinformat** [Bioconductor/Contributions#1823]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ubioinformat/TraRe

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by ubioinformat** [comment]
Hello, i have notice that the resultant warning comes from R dependency. BiocCheck warning ask to change R 4.0 dependency to 4.1. I have not be given that warning when running bioccheck on my own. Also, the 4.1 version is not available yet, as far as I know.   Do I have to change this dependency on the description file?? Thanks in advance.

**Comment by mtmorgan** [comment]
'4.1' is the 'devel' version of R, and is available. It is also the version used by our build systems and in the current 'devel' version of Bioconductor. It will also be the version used by users at the next release, when your accepted package moves from the devel branch to the release branch. So it makes sense to develop and test your package using R-devel.

R-devel is available, e.g., at https://cran.r-project.org/bin/windows/base/rdevel.html but for other platforms as well...

**Comment by ubioinformat** [comment]
Thank u very much mtmorgan, i will then keep working with R-dev.

**Comment by mtmorgan** [comment]
GENERAL

- Note that comments may mention a single line, but all examples of the problem in the package need to be addressed.

- Since the data are expression data, your functions should accept objects of class `SummarizedExperiment`.

- The vignette (e.g., line 129) uses experiment data from github, but these should instead be made available through ExperimentHub. Since this data is gene expression data, it should be made available as a `SummarizedExperiment`. Note that the information 'encoded' in the column names, e.g., about sample type, should be represented as `colData()`. 

  It can be useful to show, or point users to existing documentation, on how to create a `SummarizedExperiment` from a 'flat' table. It also makes sense to store the components of the `SummarizedExperiment` (expression **matrix**, column data, ...) in plain text (csv) files in ExperimentHub, and to assemble these into a `SummarizedExperiment` when they are retrieved.

DESCRIPTION

- good

NEWS

- is this file in a format parsed correctly by `utils::news()`?

vignettes

- TraRe.Rmd:125 large chunks of unevaluated code are not good practice -- the code quickly becomes out-of-date because of changes made in the package that the author 'forgets' to update in the vignette. If execuation time is a concern, use smaller examples.

R

- nice to see the validation of input arguments at the start of each function!

- please consider more standard formatting, e.g., as produced by the formatR package or as outlined at https://bioconductor.org/developers/how-to/coding-style/. Especially avoid long lines, and include spacing around, e.g., assignment and punctuation

- cliques_generatecliques.R:61 use `message()` to provide feedback to the user during function evaluation

- cliques_generatecliques.R:112 it is usually better to structure the code, to separate plotting and computation into two separate functions, even if the functions are internal to the package.

- excel_generation.R:79 `for` loops are seldom necessary when operating on vectors in R; use vectorization instead

    ```
    NR[list_final %in% list_edges_NR] <- 1
    R[list_final %in% list_edges_R] <- 1
    ```

- excel_generation.R:100 this is another example where vectorization is faster and more legible. Please carefully review all code for such changes; some may greatly influence performance.

    ```
    normalized_sum <- round(drivers_xor_sum / lengths(drivers_xor))
    ```

- linker_runlinker.R:113 use `message()` rather than `print()`; usually it is not necessary to use `message(paste(...))` since `message()` calls `paste0()` internally.

- linker_runlinker.R:103 it is usually very inefficient to 'copy and append'; instead use 'pre-allocate and fill' or (often even better) R's `lapply()` and friends to avoid needing to explicity manage memory. See http://bioconductor.org/developers/how-to/efficient-code/

- linker_runlinkernet.R:123 consider using BiocParallel and `bplapply()` rather than foreach for parallel evalation. Implement the body of the `foreach())` loop as a helper function to increase modularity and perhaps enable testing and re-use.

- linker_runlinkernet.R:165 consider `matrixStats::` functions for matrix operations, rather than `apply()`.

- rewiring_runrewiring.R:10 packages should never create output in a default location other than `tempdir()`; examples should use `tempdir()` (or `tempfile()`, including with `fl <- tempfile(); dir.create(fl)`).

man

- good

other

- nice to see the unit tests!

**Comment by ubioinformat** [comment]
Thank you very much @mtmorgan, I'm working on the comments to improve TraRe.  About BiocParallel, is there a way to have parallelization on windows? From what I have read it seems the MultiCoreParam is only available for mac and linux and the remaining parallelization options are for clustering (SnowParam, BatchtoolsParam and DoparParam), which do not seem very useful for this case.

**Comment by mtmorgan** [comment]
When you say, e.g., at https://github.com/ubioinformat/TraRe/blob/master/R/linker_runlinkernet.R#L135 `makeCluster()`, you are essentially doing the same as `SnowParam()`. You would revise the subsequent code to be more functional, rather than iterative, along the lines of
```
FUN <- function(idx, lognorm_est_counts, alpha) {
    y <- lognorm_est_counts[idx, ]
    fit <- glmnet::cv.glmnet(t(X), y, alpha = alpha)
    b_o <- stats::coef(fit, s = fit$lambda.1se)
    b_o[2:length(b_o)] # removing the intercept.
}
driverMat <- bplapply(target_filtered_idx, FUN, lognorm_est_counts, alpha)
```
This would have the side effect of 'automatic' selection of parallel back-end, so that on Linux / MacOS it would use forks and minimum data copy, whereas on windows it would have properties that are the same was what you are doing now.

**Comment by mtmorgan** [comment]
Will  your updates be available soon?

**Comment by ubioinformat** [comment]
Dear @mtmorgan:
Sorry for the delay. I'm now pushing into both the main branch of the TraRe and the bioconductor repository.

About each improvement you mentioned:

GENERAL


1) I have included the SummarizedExperiment object as a way of calling the main functions.

2) About the vignette, I have included the SummarizedExperiment and modify the datasets to fit them into the own package.

3) In the vignette there is a explanation on how to generate this SummarizedExperiments

NEWS

1) I have parsed the news and I think they were the right format.

vignettes

1) Now the chunks are evaluated.

R


1) Format functions have been used.

2) I have substituted prints and shows by message.

3) The structure of generate_cliques have been changed

4) I have paid attention for performance issues and I have improved all I've found. (Vectorization and lapply and sapply where I could)

5) Parallelization foreach has been substituted by bplapply().

6) outputs from examples are now in tempdir() by default.

Others

We have removed xlsx library and now those files are htmls.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ubioinformat.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TraRe")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TraRe

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by ubioinformat** [comment]
Hi there:

This package was deprecated (link [here](https://bioconductor.org/packages/3.16/bioc/html/TraRe.html)) because one of its dependencies (vbsr) was deleted from CRAN, and we did not fix that in time.  I've tried to create a new submission process, but a single issue is allowed with the same repository name. How should I proceed in order to have TraRe again as a Bioconductor package? 

The main branch of this package has already no error nor warnings, however when I push it to the upstream server "git@git.bioconductor.org:packages/TraRe.git" I get " DENIED by fallthru" error. 

I would greatly appreciate some help on this matter. Thank you so much in advance.

**Comment by lshep** [comment]
Per Bioconductor policy, if a package has been official removed from a release the package needs to be re-reviewed.  I have removed the package from seeing this issue. Please submit as a new issue as it should allow submission now.  Please let me know if you have any further issues submitting and I apologize for the delayed response.
