### ISSUE TITLE
planet

### ISSUE THREAD

**Issue by wvictor14** [Bioconductor/Contributions#1826]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wvictor14/planet

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by wvictor14** [comment]
Hi, I keep receiving this error when trying to fetch/push to git@git.bioconductor.org:packages/planet

**Comment by wvictor14** [comment]
Hi, I got it working by manually adding my ssh-keys directly into the biocredentials app. I will push a build in a couple minutes that addresses the warning.

**Comment by wvictor14** [comment]
@Kayla-Morrell the following warning is from the build report, I am not sure how to investigate the warning since I cannot reproduce on my local machine:

> * checking whether package 'planet' can be installed ... WARN WARNING
> Found the following significant warnings:
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1826/planet_20201221074502/planet.buildbin-libdir/00LOCK-planet/00new/planet/help/%>%.html': Invalid argument
> See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1826/planet_20201221074502/planet.Rcheck/00install.out' for details.

Could you advise how I should proceed? 

It also says there is a log that I might be able to get more information, but I'm not sure how to access:

>See
  'C:/Users/pkgbuild/packagebuilder/workers/jobs/1826/planet_20201221074502/planet.Rcheck/00check.log'

**Comment by Kayla-Morrell** [comment]
@wvictor14 - We've been experiencing some issues with our windows builder. I'd be happy to review the package in the mean time and if the warning persists we can investigate further on our end.

**Comment by wvictor14** [comment]
Sounds good! Thanks @Kayla-Morrell , I'll wait for your review.

**Comment by Kayla-Morrell** [comment]
@wvictor14  - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQUIRED: Licence 'GPL (>= 2)' is unknown. Licenses cannot restrict use. I
  believe just 'GPL-2' should suffice. Also, the LICENSE file is not needed in
the top directory since this is a standard license.

- [ ] REQUIRED: 'LazyData' should be set to false. It is our experience that
  when this field is set to true it can slow down the loading of a package,
especially if it contains data.

## Data

- [ ] REQUIRED: The 'data-raw' content should be moved to an 'inst/script/'
  directory to be sure that they are included with the package.

- [ ] REQUIRED: In the ethnicityCpGs.R file, the data/object should not be
  local. You should be demonstrating to the user how they can download/obtain
the raw data and turn it into the right data object. I would suggest including
any raw data in an 'inst/extdata/' directory.

## Vignette

- [ ] REQUIRED: Only vignette files (.Rnw or .Rmd) and any necessary static
  images should be in the vignette directory. All other files should be removed
(for example, the .orig files should be removed).

- [ ] REQUIRED: Each vignette should have an installation section that explains
  to the user how to download/install the package from Bioconductor. The code
should look something like the following and should inclue `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("planet")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents. 

- [ ] REQUIRED: Each vignette should end we a session information section and
  include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: The 'figures/' directory does not belong here. I would suggest
  moving it to and 'inst/figures/' directory.

## R code

- [ ] REQUIRED: Normally we don't allow for sysdata.rda in packages. I was not
  able to locate where this file was used. Please remove if not needed.

Best,
Kayla

**Comment by wvictor14** [comment]
> @wvictor14 - Thank you for submitting to _Bioconductor_. Please see the initial review of
> the package below. The required changes must be made while the suggested
> changes do not have to be (though we strongly encourage them). Comment back
> here with updates that have been made and when the package is ready for a
> re-review.
> 
> ## DESCRIPTION
> * [x]  REQUIRED: Licence 'GPL (>= 2)' is unknown. Licenses cannot restrict use. I
>   believe just 'GPL-2' should suffice. Also, the LICENSE file is not needed in
>   the top directory since this is a standard license.

I changed the license to "GPL-2"

> * [x]  REQUIRED: 'LazyData' should be set to false. It is our experience that
>   when this field is set to true it can slow down the loading of a package,
>   especially if it contains data.

I set LazyData to false. I tried my best to modify code accordingly, but I receive these notes in R cmd check:

```
 predictAge: no visible global function definition for 'data'
  predictAge: no visible binding for global variable 'ageCpGs'
  predictEthnicity: no visible global function definition for 'data'
  predictEthnicity: no visible binding for global variable
    'ethnicityCpGs'
  Undefined global functions or variables:
    ageCpGs data ethnicityCpGs
  Consider adding
    importFrom("utils", "data")
  to your NAMESPACE file.
```
What I did after setting lazydata to false:
- in my functions that rely on data that is exported (useful for users), I run a `data(...)` command at the beginning of the function. Otherwise the functions throw errors saying that the objects cannot be found / are not exported objects. 

I'm not sure if this was appropriate or the best approach. Please let me know if there is a better way, or a way to address the notes. Thanks

> ## Data
> * [x ]  REQUIRED: The 'data-raw' content should be moved to an 'inst/script/'
>   directory to be sure that they are included with the package.

Done

> * [ ]  REQUIRED: In the ethnicityCpGs.R file, the data/object should not be
>   local. You should be demonstrating to the user how they can download/obtain
>   the raw data and turn it into the right data object. I would suggest including
>   any raw data in an 'inst/extdata/' directory.

I cannot include raw data that is used in this file. It is extremely massive (>100mb). I included this script because it simply documents how I obtained the necessary data used in the function `predictEthnicity`. 

> ## Vignette
> * [x]  REQUIRED: Only vignette files (.Rnw or .Rmd) and any necessary static
>   images should be in the vignette directory. All other files should be removed
>   (for example, the .orig files should be removed).

Done.

> * [x]  REQUIRED: Each vignette should have an installation section that explains
>   to the user how to download/install the package from Bioconductor. The code
>   should look something like the following and should inclue `eval = FALSE`.
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("planet")
> ```
> * [x]  SUGGESTION: We strongly encourage the use of table of contents.
> * [x]  REQUIRED: Each vignette should end we a session information section and
>   include `sessionInfo()`.

Done

> ## Man pages
> * [x]  REQUIRED: The 'figures/' directory does not belong here. I would suggest
>   moving it to and 'inst/figures/' directory.

Done

> ## R code
> * [ ]  REQUIRED: Normally we don't allow for sysdata.rda in packages. I was not
>   able to locate where this file was used. Please remove if not needed.

The sysdata.rda object contains internal data that is used in the function `predictEthnicity`.

**Comment by wvictor14** [comment]
@Kayla-Morrell  Ready for re-review. Please see my previous comment where I respond to each of your points in-line. Let me know how to proceed. 

I'm not sure what the Warning is from the build report means.

Thanks!

**Comment by wvictor14** [comment]
@Kayla-Morrell I need to change the R version to >= 4.0 instead of >= 4.1, because otherwise my users cannot download the latest version of planet (or at least, it would be inconvenient for them to use). This produces a warning from BiocCheck, but I see that other package submissions have been flexible in the R version dependency. Is it OK if I use R (>= 4.0) from this point on?

**Comment by Kayla-Morrell** [comment]
@wvictor14 - Thank you for making the necessary changes. We can allow you to keep the R version at 4.0. Everything else looks good and I'm more than happy to accept the package.

Best,
Kayla

**Comment by wvictor14** [comment]
Thank you @Kayla-Morrell !

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wvictor14.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("planet")`. The package 'landing page' will be created at

https://bioconductor.org/packages/planet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
