### ISSUE TITLE
InteractiveComplexHeatmap

### ISSUE THREAD

**Issue by jokergoo** [Bioconductor/Contributions#1827]
- Repository: https://github.com/jokergoo/InteractiveComplexHeatmap

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi ZuGuang, @jokergoo

Thank you for your submission to Bioconductor. Sorry for the delay in getting back to you over the break. 
Please see the review below. Remember to respond to the review line by line. 

Best regards,
Marcel

---

# InteractiveComplexHeatmap #1827

## DESCRIPTION

* Add a `BugReports` field
* (optional) Add your ORCID ID to the `Authors@R` field

## NAMESPACE

* Looks good.
* Consider using all 'camelCase' or all 'snake_case' for your function names
instead of a mix of both.

## vignettes

* Provide an `Installation` section in one of the vignettes to show users how
to install the package from Bioconductor.
* If possible, avoid static code chunks (as in `implementation.Rmd` and
`shiny_dev.Rmd`) and use actual data

## R

* We encourage all developers to remove the noisy messages when loading a
package. Consider removing the `.onAttach` messages. A user wishing to report a
bug or see the package version would use `bug.report()` or even
`packageVersion()` for just the package version.
* There is some value in having sensible defaults. For example, use the
defaults that you have defined in the function body in the function's
arguments (e.g., `title = "ComplexHeatmap Shiny App"` in `ht_shiny`). This
way, you don't have to worry about whether the argument is `NULL` or not since
you have a working default. It reduces the overall cyclomatic complexity.
* Because you have interactive demonstrations, consider using the `demo`
subdirectory instead of the `ht_shiny_example` function. It seems like you
already have a script that is ready-to-run. For more details, see here:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-subdirectories
* Avoid any `library` calls in package code. Your examples can have `library`
calls as long as those packages are added to the `Suggests` field.

## / base pkg directory

* Remove `build_pkg_site.R` or put it in `inst/scripts`.
* `docs` should also be removed

## README.md

* Add a Bioconductor installation section after acceptance.
* Consider using an `Rmd` file and rendering to `md` so that code chunks are
evaluated.

**Comment by jokergoo** [comment]
Hi Marcel @LiNk-NY,

Thanks for your time and review on the **InteractiveComplexHeatmap** package! Following are my point-to-point
reply:


## DESCRIPTION
> * Add a `BugReports` field
> * (optional) Add your ORCID ID to the `Authors@R` field

Both are added.

## NAMESPACE
> * Looks good.
> * Consider using all 'camelCase' or all 'snake_case' for your function names
>   instead of a mix of both.

All function names now are written in camelCase style.


## vignettes
> * Provide an `Installation` section in one of the vignettes to show users how
>   to install the package from Bioconductor.

Added.

> * If possible, avoid static code chunks (as in `implementation.Rmd` and
>   `shiny_dev.Rmd`) and use actual data

In `implementation.Rmd`, some static code chunks demonstrate the output from
interactive manipulations on the interactive graphics device, e.g. clicks on the graphics device,
so they cannot be generated on the fly.

Similarlly, the static code chunks in `shiny_dev.Rmd` are only used to
demonstrate the format of the objects. They cannot be obtained in the
Rmarkdown generation and the exact values are not important there.

## R
> * We encourage all developers to remove the noisy messages when loading a
>   package. Consider removing the `.onAttach` messages. A user wishing to report a
>   bug or see the package version would use `bug.report()` or even
>   `packageVersion()` for just the package version.

It is removed.

> * There is some value in having sensible defaults. For example, use the
>   defaults that you have defined in the function body in the function's
>   arguments (e.g., `title = "ComplexHeatmap Shiny App"` in `ht_shiny`). This
>   way, you don't have to worry about whether the argument is `NULL` or not since
>   you have a working default. It reduces the overall cyclomatic complexity.

Yes, they are moved to function arguments.

> * Because you have interactive demonstrations, consider using the `demo`
>   subdirectory instead of the `ht_shiny_example` function. It seems like you
>   already have a script that is ready-to-run. For more details, see here:
>   https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-subdirectories

The reason is, the example code will be post-processed so that the source code of the example is
also shown in the Shiny app. For example, for the following example:

```r
library(InteractiveComplexHeatmap)
library(ComplexHeatmap)
ht = Heatmap(matrix(rnorm(100), 10))
htShiny(ht)
```

to put in `demo/` and to also print the source code of this example in the shiny app, it needs to be adapted to:

```r
library(InteractiveComplexHeatmap)
library(ComplexHeatmap)
ht = Heatmap(matrix(rnorm(100), 10))
htShiny(ht, html = "
<h3>Description</h3>
<pre>blablabla</p>
<h3>source code</h3>
<pre>
library(InteractiveComplexHeatmap)
library(ComplexHeatmap)
ht = Heatmap(matrix(rnorm(100), 10))
htShiny(ht)
</pre>
")
```

As you see, the example code is repeated twice, which is very bad for examples with huge block of code,
while in `htShinyExample()`, the value for `html` can be automatically processed.

> * Avoid any `library` calls in package code. Your examples can have `library`
>   calls as long as those packages are added to the `Suggests` field.

All packages used in examples are now put in `Suggests` field.


## / base pkg directory
> * Remove `build_pkg_site.R` or put it in `inst/scripts`.
> * `docs` should also be removed

`build_pkg_site.R` and `docs` are used for building the package website and
they are only available in the Github repo. They are actually excluded in `.Rbuildignore`.

https://github.com/jokergoo/InteractiveComplexHeatmap/blob/e990c8147d6a8bec3c6190b7d809afb4dad3609c/.Rbuildignore#L12-L14

## README.md
> * Add a Bioconductor installation section after acceptance.

Added.

> * Consider using an `Rmd` file and rendering to `md` so that code chunks are
>   evaluated.

There is no executable code chunk in `README.md`, so I think it is fine to only use the `.md` file.

**Comment by LiNk-NY** [comment]
Hi ZuGuang, @jokergoo

Thank you for making those changes and addressing the points. 
I would still argue that the `docs` folder and the `build_pkg_site.R` file can be moved to more suitable locations. 
Usually, the `docs` folder is a product (of `pkgdown::build_site()`) and its contents are put on a `gh-pages` branch
on GitHub for hosting.
We would like to only host the source of the package rather than all its by-products. 

Consider using GitHub Actions via `biocthis::use_bioc_github_action()` for possibly easier setup. 

Best,
Marcel

**Comment by jokergoo** [comment]
Hi Marcel,

Yes, you are right! I haven't considered that. I have moved `docs/` and `build_pkg_site.R` to `gh-pages` branch. Now it is clean.

Best,
Zuguang

**Comment by LiNk-NY** [comment]
Hi Zuguang, @jokergoo 
Thanks for making those changes! :pray: 
I have accepted your package. Thank you for your contribution. 
Best regards,
Marcel

**Comment by jokergoo** [comment]
Thank you @LiNk-NY Marcel too for your time and valuable suggestions!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jokergoo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("InteractiveComplexHeatmap")`. The package 'landing page' will be created at

https://bioconductor.org/packages/InteractiveComplexHeatmap

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
