### ISSUE TITLE
conclus

### ISSUE THREAD

**Issue by ilyessr** [Bioconductor/Contributions#1830]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ilyessr/conclus

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
Please update your package to not TIMEOUT before the review process can continue.

**Comment by lshep** [comment]
Please fix the TIMEOUT ERROR before the review process will continue.

**Comment by lshep** [comment]
Perhaps using a smaller dataset or a subset of data would help with the TIMEOUT

**Comment by lshep** [comment]
Again I haven't looked indepth at your package yet -- but if its an issue with comprehensive testing you can also look at [long tests](http://bioconductor.org/developers/how-to/long-tests/)

**Comment by ilyessr** [comment]
> Again I haven't looked indepth at your package yet -- but if its an issue with comprehensive testing you can also look at [long tests](http://bioconductor.org/developers/how-to/long-tests/)

Hi @lshep 

I think I have reduced the test and example data well. Now the errors come from a connection problem with the biomart package and also with GEO database. We choose to use Biomart package instead local database to reduce the size of the package. But there may be connection problems. Is it possible to use a local database even if the package exceeds the limit allowed by bioconductor?

**Comment by lshep** [comment]
@ilyessr  The option for using larger file sized data is to create an accompanied ExperimentHub data package.  See [documentation](https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAHubPackage.html)

**Comment by ilyessr** [comment]
Dear @Ishep,

I managed to make the tests and the examples faster to no longer have the TIMEOUT.

There are still some warnings for which I would like to know if they were acceptable or not :

1) The Rd warning on Windows concerning the setters but apparently it's a bug with the package builder.

2) The warning about evaluating more vignette chunks. We had to reduce the number of chunks evaluated in order to build the package on time, as we use a real dataset to concretely illustrate the use of our package in a real case.

3) The use of set.seed() : We use t-sne which has a part of randomness. set.seed() is essential to our package to have reproducible results. It is set to 42 by default, but the user can change its value using a parameter described in the function  "generateTSNECoordinates" man page

**Comment by ilyessr** [comment]
Dear @lshep ,

I managed to make the tests and the examples faster to no longer have the TIMEOUT.

There are still some warnings for which I would like to know if they were acceptable or not :

1) The Rd warning on Windows concerning the setters but apparently it's a bug with the package builder.

2) The warning about evaluating more vignette chunks. We had to reduce the number of chunks evaluated in order to build the package on time, as we use a real dataset to concretely illustrate the use of our package in a real case.

3) The use of set.seed() : We use t-sne which has a part of randomness. set.seed() is essential to our package to have reproducible results. It is set to 42 by default, but the user can change its value using a parameter described in the function  "generateTSNECoordinates" man page

**Comment by lshep** [comment]
1. Yes you can ignore these Rd Windows warnings
2. Reducing the number of code chunks evaluated is not a good solution for avoiding a TIMEOUT.  Real dataset usage can prove beneficial but perhaps a reduced size dataset would be acceptable; often using mock datasets provide enough detail to illustrate the features of the package while reducing the load for build/check. Minimally, all the functions should be run once either in vignette (preferred), man or tests; if this is not the case than an exception will not be made.
3. it is generally never a good idea to specify the seed in function code, however since you have clearly defined the argument and made its use known to the user we will make an exception in this case.  Please try to avoid encoding set.seed within package code in the future.

**Comment by ilyessr** [comment]
For information, all functions that are in chunks with eval = F are runned in both tests and man. 
So now the next step is to wait for your review, right?

**Comment by lshep** [comment]
Yes I'll have a review shortly

**Comment by lshep** [comment]
Please see initial review below: 


**DESCRIPTION**

- [ ] Please remove `LazyData: true`. We have rarely found it useful and can actually slow down installation.

**NEWS**

- [ ] Formatted incorrectly. See `news?` and [Bioc news](http://bioconductor.org/developers/package-guidelines/#news)

**inst**

- [ ] You will also need an inst/script directory that contains files explaining how the files in inst/extdata were generated. This should include source information and any processing. In can be code, sudo-code, or text.


**vignette**

- [ ] Please use a `tempdir()` when referencing output directories in vignette.

- [ ] The reason we generally insist on having vignette chunks eval=TRUE is to catch ERRORs and mistakes especially if files are not accessed anywhere else.

```
> countmatrixPath
[1] "/home/shepherd/R-Libraries/4.1-Bioc3.13/conclus/extdata/test_countMatrix.tsv"
> countMatrix <- loadDataOrMatrix(file=countmatrixPath, type="countMatrix")
Error in .checkLoadedDataParams(file, columnID, header, sep, dec, type) : 
  'file' parameter should be a path of existing file.
```

**R code / man pages**

- [ ] Anytime data is downloaded from the internet a caching approach should be taken. This not only would decrease time run on subsequent calls but also can act as a backup for if a resource becomes unavailable; as long as it was
  previously downloaded, there is something that can be utilized.  Please add a caching mechanism for functions like .retrieveMatrix.  See BiocFileCache for Bioconductor endorsed caching package.
  

Please address the above issues.  When ready do a version bump to kick off a new build and comment back here with a summary of updates and requesting a re-review. 

Cheers

**Comment by ilyessr** [comment]
Dear @lshep, 

The package is ready for a re-review, here the summary of updates :

DESCRIPTION

[x] Removed LazyData: true

NEWS

[x] Formatted NEWS

inst

[x] Created a inst/script directory that contains scripts to generate all files in inst/extdata. 
[x] New data in inst/extdata. 

vignette

[x] Used a tempdir() when referencing output directories in vignette.

[x] Removed old wrong path from the vignette

test
[x] Used a tempdir() for unit tests.

R code / man pages

[x] Added a caching mechanism for functions  .retrieveMatrix, .retrieveColMetaDataFromURL and .retrieveColMetaDataFromSeries

[x] Created conclusCacheClear() to delete this cache

**Comment by lshep** [comment]
Thank you for the changes.  Everything looks good.  One note just to be aware of: 

Nothing you really need to do on your end, it would be on a users system but so
you are aware if you get questions, not all systems support transparency that
ggplot offers.  So when I try to display I don't see anything but the
grid. Again if will be user dependent and there are ways to adapt on a system
but it case you get questions about it.  
```
> p[[1]]
Warning message:
In grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size) :
  semi-transparency is not supported on this device: reported only once per page
```

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ilyessr.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("conclus")`. The package 'landing page' will be created at

https://bioconductor.org/packages/conclus

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by ilyessr** [comment]
Thank you for your review
