### ISSUE TITLE
ExpHunterSuite

### ISSUE THREAD

**Issue by jimrperkins** [Bioconductor/Contributions#1835]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/seoanezonjic/ExpHunterSuite

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by nturaga** [comment]
# ExpHunterSuite review

## General

- Please fix NOTEs related to coding practice in your
package. Especially the ones for using `vapply` and `seq_len()`. I'm
particualr about these practices.

- It's a good idea to keep your build report as clean as possible.

- I will do a second review of the package once you fix the issues highlighted below. Some issues occur in more than one place. Please fix all occurrences. 

## DESCRIPTION

ok

## NAMESPACE

ok

## NEWS

- It's always good to add a NEWS file, it'll be included in the
  release documentation of every Bioconductor release.
  
## R

- **IMP** Indent your code according to coding style,
  http://bioconductor.org/developers/how-to/coding-style/. This is
  very important for code readability. 80 chars per line. 
  
- Please fix the `1:len` issue for your loops.

- ‘Pre-allocate and fill’ if iterations are
  necessary. http://bioconductor.org/developers/how-to/efficient-code/
  
  You seem to be making a lot of empty lists and vectors in
  `perform_expression_analysis()` and filling them. This is bad coding
  practice. Especially when you know the size of your lists / vectors.

- Instead of nesting multiple "if" statements, use logical operators
  like `&` between conditions. This is done in `check_results()`.
  
- Follow good documentation rules, follow the devtools documentation
  principles. Remove commented out code where it's not needed.
  
  eg:`translate_id()`. 
  
- In functions like `scaled_data_matrix` you can easily avoid the
  `apply` function. Vectorize your code when you
  can. http://bioconductor.org/developers/how-to/efficient-code/

## man

- Some functions have very limited man pages and need to be more
  detailed.
  
- No runnable examples in man pages.

**Comment by jimrperkins** [comment]
> # ExpHunterSuite review
> ## General
> * Please fix NOTEs related to coding practice in your
>   package. Especially the ones for using `vapply` and `seq_len()`. I'm
>   particualr about these practices.

All notes fixed with the exception of i) the use of <<- which we used in some situations in which the side effect of the function was more important than the return value, ii) Some functions are > 50 lines - this is unavoidable given the way the program is structured such that it can be run from the command line. iii) Unit tests - most of the functions are highly complex and it is not trivial to design unit tests to cover the multiple possible ways of running the package. In any case, the package is largely concerned with calling existing Bioc packages/functions which should themselves have their own testing implemented. iv) Multiples of 4 spaces for line indents - this is not always met in order to align functions on different lines in a clearer manner. i.e. in line with parentheses.

> * It's a good idea to keep your build report as clean as possible.

This is now MUCH cleaner. There are still a number of notes related to the code in the Rmd files - this appears to be unavoidable, as this is called using render from a different file - as such it appears as though some variables are not declared in the Rmd files (i.e. in tests for running chunks).

> * I will do a second review of the package once you fix the issues highlighted below. Some issues occur in more than one place. Please fix all occurrences.
> 
> ## DESCRIPTION
> ok
> 
> ## NAMESPACE
> ok
> 
> ## NEWS
> * It's always good to add a NEWS file, it'll be included in the
>   release documentation of every Bioconductor release.

Added

> 
> ## R
> * **IMP** Indent your code according to coding style,
>   http://bioconductor.org/developers/how-to/coding-style/. This is
>   very important for code readability. 80 chars per line.

This has been done, with the exception of that in some cases non-multiples of 4 spaces have been used to make things line up properly when functions are broken over several lines.

> * Please fix the `1:len` issue for your loops.

Fixed

> * ‘Pre-allocate and fill’ if iterations are
>   necessary. http://bioconductor.org/developers/how-to/efficient-code/
>   You seem to be making a lot of empty lists and vectors in
>   `perform_expression_analysis()` and filling them. This is bad coding
>   practice. Especially when you know the size of your lists / vectors.

In this function we concatenate the results of other functions into vectors/lists because, later on, these results will be used to generate plots/reports by applying the same operations to each list member. We had two possible options here:1.	Create a list with all possible containers and fill which will be executed and stay empty which will not be executed. After this, check one by one if each method had been executed and apply operations over those that are not empty only.2.	Create an empty list and use it as a linked list where each execution is performed and, after, apply operations over the full list (because list only contains executed results).We decided to code the second strategy in order to avoid empty containers. For this second strategy, we do know the maximum potential size (which corresponds to the maximum available modules in our code) but, if we create those lists with fixed size, we will be implementing the strategy 1 with potential empty spaces.,This will also break our ability to include new modules easily.

> * Instead of nesting multiple "if" statements, use logical operators
>   like `&` between conditions. This is done in `check_results()`.

We have rewritten this function and reduced some nested "ifs", but there are some others which cannot be simplified using logical operators. For example, we have the following code:if(is.data.frame(df)){  if(nrow(df) <= 0){    return(FALSE)  }}In this case, we must perform it independently because norw only works for matrix and dataframes but df can be a list, in case of execute nrow(<listObject>) it will return a logical(0) which is not treated as a TRUE/FALSE element.Same problem occurs at:if("pvalueCutoff" %in% slotNames(df)){    if(nrow(df@result[which(df@result$p.adjust <= df@pvalueCutoff),]) < 1){      return(FALSE)    }  }else if(length(get_categories(df)) < 1){    return(FALSE)  }In this case we are checking and external object which can have two formats, one containing pvalue threshold used into slot pvalueCutoff or storing it into a parental slot called params. For that reason, we must first check the slots architecture in order to correctly access the slot value.

> * Follow good documentation rules, follow the devtools documentation
>   principles. Remove commented out code where it's not needed.
>   eg:`translate_id()`.

We have followed the devtools documentation as much as possible and commented out all unnecessary code 

> * In functions like `scaled_data_matrix` you can easily avoid the
>   `apply` function. Vectorize your code when you
>   can. http://bioconductor.org/developers/how-to/efficient-code/

We have changed this function so it does not use apply - the functions are performed on the whole matrix instead using rowSums style functions.

> 
> ## man
> * Some functions have very limited man pages and need to be more
>   detailed.

We have improved documentation.

> * No runnable examples in man pages.

All man pages should now have runnable examples.

**Comment by nturaga** [comment]
Hi @jimrperkins i'm happy with the changes you made. 

Although looking at the build report, it seems like there are issues with the variables which cannot be found in scope. Please fix these although they might be minor. I'm happy to accept your package after.

**Comment by jimrperkins** [comment]
Hi @nturaga - great, thank you for your dedication and comments which have improved the package greatly.

The issues re: the variables  out of scope in the build report - I assume you mean in the bioccheck report, not CMD build? Things like `Error in eval(x, envir = envir) : object 'executed' not found` ?

These are due to the Rmd templates in the inst/templates folder, not code within the R folder - these Rmd templates are called via the `rmarkdown::render` function, which passes the variables. As such, the variables appear to not have been initialised, but in reality this doesn't cause an issue when running the package.

I can't think of any way of solving this problem, short of deleting the templates which obviously I don't want to do as the output reports are an integral part of the package functionality.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jimrperkins.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ExpHunterSuite")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ExpHunterSuite

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
