### ISSUE TITLE
IRISFGM

### ISSUE THREAD

**Issue by BMEngineeR** [Bioconductor/Contributions#1837]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BMEngineeR/IRISFGM

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by BMEngineeR** [comment]
@Kayla-Morrell Hi Kayla, thank you in advance for your help with checking the package submission. Regarding the most recent error from the bioc-issue-bot report (.Rproj file), I pushed changes to address these yesterday, but it has not automatically checked it again. Is there something we need to do to have the bioc-bot re-check? The package should be ready to review now that the issue is fixed. Thank you!

**Comment by Kayla-Morrell** [comment]
@BMEngineeR - Be sure that you are also pushing a version bump with changes, this is what will trigger the new build.

**Comment by Kayla-Morrell** [comment]
@BMEngineeR - I saw that you made a push yesterday but no build report was posted. I went ahead and kicked off a manual build so you got a build report. The latest build report is a reflection of the latest changes you pushed.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@BMEngineeR -

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQURIED: License 'GPL (>= 2)' is unknown; licenses cannot restrict use.
  I believe 'GPL-2' would be sufficient here. 

- [ ] SUGGESTION: I would move 'knitr' from the Imports field to a Suggests
  field since this package is used to create vignettes. Unless you actually
utilize functionality from the package within your code. The Imports is
reserved for packages that provide functions, methods, or classes to your
package while Suggests are for packages that are used in vignettes, examples,
and conditional code.

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field
  which includes the relevant link to Github for reporting Issues. 

## NAMESPACE

- [ ] SUGGESTION: Generally 'importFrom()' is encouraged over importing an
  entire package.

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file, however the file is not
  formated properly so it won't render properly. See our documentation here:
https://bioconductor.org/developers/package-guidelines/#news. After you install
your package you can check to see if the file is formated properly by running
the following in R, `utils::news(package="IRISFGM")`.

## Vignette

- [ ] REQUIRED: Only the vignette file (.Rnw or .Rmd) should be present in this
  directory. Please remove the other files.

- [ ] SUGGESTION: I would do a quick read through of the vignette. There are some
  spelling errors that should be addressed, for example in the heading
'Introduction to IRIS-FGM' Introduction is misspelled and in the heading 'Object
structure' Object is misspelled.

- [ ] REQUIRED: For the section where you talk about pre-installed packages,
  this code should not be individual inline code but they should all be in a
single code chunk. You should show installing packages (minus BiocManager) using
BiocManager, not install.packages (BiocManager will work for non-Bioconductor
packages as well). You should not be using github to install seurat, this should
also be done through BiocManager.

- [ ] REQUIRED: When showing how to install the IRISFGM package this should be
  demonstrated using Bioconductor. The code should look something like the
following and should include `eval=FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("IRISFGM")
```

- [ ] REQUIRED: All code should be included in code chunks, for example the code
  you use to demonstrate reading from .h5 file and 10X folder. Instead of inline
code this should be a code chunk like you do for setting the directory/importing
the library and reading the .csv or .txt file.

- [ ] REQUIRED: All code chunks need to be evaluated to demonstrate that the
  code works without errors. Please be sure code chunks do not include
`eval=FALSE`.

- [ ] REQUIRED: Use accessors; we do not allow for S4 class slots to be accessed
  via '@' in examples or vignettes (line 239).

## Man pages

- [ ] SUGGESTION: For any function that isn't being exported I would suggest
  adding the `@keywords internal` tag to the documentation. This will remove the
function from the package index. This should definitely be done for any function
that is internal (meaning it starts with a '.') because these functions should
be shown in documentation, they aren't intended to be exposed to the user.

- [ ] REQUIRED: Add runnable examples to the following man pages which document exported objects:
        - FindClassBasedOnMC.Rd
        - ReadFrom10X_folder.Rd
        - ReadFrom10X_h5.Rd
        - RunBicluster.Rd
        - RunDiscretization.Rd

- [ ] REQUIRED: We require all exported objects to have runnable examples, is
  there a reason why this one is not run? If it is absolutely necessary we
prefer donttest{} instead of dontrun{}.
        - RunPathway.Rd

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Avoid sapply(); use vapply() if possible.

- [ ] REQUIRED: Various apply functions should be instead of for loops if
  possible.

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along() if possible.

- [ ] REQUIRED: Avoid the use of direct slot access with '@' or 'slot()'. An
  accessor method should be created and utilized, especially in functions that
are being exported.

- [ ] REQUIRED: Is there a reason why you are not exporting the classes defined
  in your package? If they are to be exported you will need to provide better
documentation and information for the slots.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 441
  lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 305 lines that are not.

## C/Fortran code

- [ ] REQUIRED: File ‘IRISFGM/libs/IRISFGM.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
    Object: ‘struct.o’
  Found ‘___stdoutp’, possibly from ‘stdout’ (C)
    Object: ‘struct.o’
  Found ‘_printf’, possibly from ‘printf’ (C)
    Objects: ‘main.o’, ‘make_graph.o’, ‘read_array.o’, ‘struct.o’
  Found ‘_putchar’, possibly from ‘putchar’ (C)
    Objects: ‘cluster.o’, ‘read_array.o’, ‘struct.o’
  Found ‘_puts’, possibly from ‘printf’ (C), ‘puts’ (C)
    Objects: ‘get_options.o’, ‘read_array.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@BMEngineeR - I was wondering if there has been any progress on the points made in my review. We typically like to see changes within a 2-3 week time frame to be sure the package is actively being worked on and it has been just over 3 weeks since I posted my review.

**Comment by BMEngineeR** [comment]
@Kayla-Morrell Sorry for the concern, I thought the package should be uploaded this Monday.  I just reupdate GitHub and re-push to the new version for checking.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BMEngineeR.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("IRISFGM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/IRISFGM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
