### ISSUE TITLE
Travel

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/Contributions#1838]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jiefei-Wang/Travel

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi JeiFei, @Jiefei-Wang 

Thanks for your submission. Please see the review below. 
Remember to respond to the review line-by-line. 
Thank you.

Best regards,
Marcel

---
# Travel #1838

* It's not clear from the `DESCRIPTION` how the package works with the
Bioconductor ecosystem. Perhaps add info addressing this point in the
`Description` field? The package seems to have broader applications than just
Bioconductor.

## DESCRIPTION

* Add `URL` and `BugReports` fields

## NAMESPACE

* Looks good

## vignettes

* We recommend sticking to the 80 column-width limit for all vignettes and
package code
* The package introduction looks good.
* It may be a challenge to install the package properly on the builders. That
said, runnable examples would keep the package continually tested.

## R

* Reconsider exporting functions that are not mean to be used manually (e.g.,
`deploy_filesystem`) or provide the documenation with `@keyword internal`.

Minor:
* I think you mean to say `drive path` rather than `driver path` in
`R/filesystem.R`

**Comment by Jiefei-Wang** [comment]
Thanks for your comments! I have made changes according to your suggestions.
Responses are highlighted below @LiNk-NY

1. It's not clear from the DESCRIPTION how the package works with the
Bioconductor ecosystem. Perhaps add info addressing this point in the
Description field? The package seems to have broader applications than just
Bioconductor.
  **I have added one paragraph to discuss the potential use of the package 
in DESCRIPTION**

2. Add URL and BugReports fields
  **URL and BugReports are in DESCRIPTION now**

3. We recommend sticking to the 80 column-width limit for all vignettes and
package code
  **The vignette has been formatted**

4. It may be a challenge to install the package properly on the builders. That
said, runnable examples would keep the package continually tested.
  **The Linux builder should work now, I get one warning from the linux builder
but it looks like a false positive.**

5. Reconsider exporting functions that are not mean to be used manually (e.g.,
deploy_filesystem) or provide the documenation with @keyword internal.
  **They are internal functions now.**

6. I think you mean to say drive path rather than driver path in
R/filesystem.R
  **Thanks for the catch, I have changed it.**

Best,
Jiefei

**Comment by LiNk-NY** [comment]
Hi JieFei, @Jiefei-Wang 

Thanks for making those changes! They look good. 
Can you speak to the errors on the builders (Mac & Windows)? 

Thanks. 
-Marcel

**Comment by Jiefei-Wang** [comment]
That's because of the missing dependence on Win and Mac builders. 
I've talked with Herve about the dependence and he installed fuse on 
the Linux builder for me. He said he will install the dependence on 
the other builders later. I'll follow up this issue with Herve.

Best,
Jiefei

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 
Any updates on installing the dependencies for the Travel package? 
Other than this, the package looks pretty good to go to me. 

Thanks!
-Marcel

**Comment by lshep** [comment]
@hpages any update on this?

**Comment by LiNk-NY** [comment]
Hi JeiFei, @Jiefei-Wang 

Can you bump the version of the package? We should make sure it works on Linux.
After that, we can accept. 

Best,
Marcel

**Comment by hpages** [comment]
I installed fuse and libfuse-dev on malbec2 on January 7 per Jiefei's request and successfully `R CMD build & check`'ed **Travel** on this machine that day. I kind of assumed that we were good for now as far as package review is concerned. Sorry if I was not clear.

**Comment by Jiefei-Wang** [comment]
Hi @LiNk-NY , it looks like the warning is a false positive on the Linux builder. The unevaluated chunks are written in C language so they are not runnable.

Best,
Jiefei

**Comment by LiNk-NY** [comment]
Sounds good. Thanks Jeifei.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jiefei-Wang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Travel")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Travel

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
