### ISSUE TITLE
SANTA

### ISSUE THREAD

**Issue by alexjcornish** [Bioconductor/Contributions#1841]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/alexjcornish/SANTA

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by alexjcornish** [comment]
The SANTA packages was previously available in Bioconductor, but was deprecated in release 3.11, and removed in release 3.12. This was due to me failing to fix errors with the package (I had an old e-mail address listed in the DESCRIPTION file, so missed any e-mails concerning this). 

I have fixed all errors and have tried to ensure that SANTA now adheres to all current Bioconductor guidance. 

Sorry about this. I've updated my e-mail address in the DESCRIPTION file, and if SANTA is re-accepted will do a better job actively maintaining the package. 

Thanks, Alex

**Comment by mtmorgan** [comment]
@alexjcornish instead of creating a new repository with the updates, can you clone the original, commit the changes, and post the updated repository here (e.g., by replacing your current SANTA repository on github)? Something like

```
git clone https://git.bioconductor.org/packages/SANTA
cd SANTA
## make changes and git commit
...
## remove old remote and add to newly created github repo
git remote remove origin
git remote add origin git@github.com:alexjcornish/SANTA
git push
```

This will mean that the commit history of your package will be preserved.

**Comment by alexjcornish** [comment]
@mtmorgan, thanks for this, I have cloned the original package and updated as requested.

**Comment by mtmorgan** [comment]
Please ignore the error about package version needing to be `x.99.z`, but subscribe to the bioc-devel mailing list with the email used in your DESCRIPTION file. Bump the version to 1.27.1 to trigger a build. I'll provide a review after that...

**Comment by mtmorgan** [comment]
11 February, 2021

DESCRIPTION, NAMESPACE

- OK

vignettes

- I'm concerned about the number of code chunks that have commented-out code; the problem with this approach is that the vignette quickly becomes 'pictures of code' that does not actually work, frustrating the user.

R (comments on specific lines apply generally...)

- Generally looks good!

- BinGraph.R:34 long lines of nested logic are difficult to read; revise as

    ```
    if (length(breaks.unique) > nsteps + 1) {
        values <- breaks.unique[is.finite(breaks.unique) & breaks.unique != 0]
        samples <- sample(values, nsteps - 2)
        breaks <- sort(c(-Inf, 0, Inf, samples))
    }
    ```
    
- CheckAttributes.R:33 `suppressWarnings()` in code can mask real problems with user data; instead protect against known warnings (eg., removing NAs?) for easier to understand and more robust code.

- Compactness.R:23 avoid iteration (`n` function calls) in favor of vectorization (1 function call); update complicated data structures once rather than `n` times (also, e.g., Knet.R:62-67)

    ```
    res_attr <- rep(list(NA), length(element.names))
    names(res_attr) <- element.names
    res[[attr]] <- res_attr
    ```
    
  Avoid repeated calculation of the same value
  
    ```
    res_attr <- rep(list(NA), length(element.names))
    names(res_attr) <- element.names
    res <- rep(res_attr, length(vertex.attr))
    names(res) <- vertex.attr
    ```

**Comment by alexjcornish** [comment]
Dear Martin, thanks very much for the review and comments. I have updated SANTA as suggested: 

**I'm concerned about the number of code chunks that have commented-out code; the problem with this approach is that the vignette quickly becomes 'pictures of code' that does not actually work, frustrating the user.**

- I have removed or uncommented all commented-out code in the vignette. 

**BinGraph.R:34 long lines of nested logic are difficult to read; revise as
if (length(breaks.unique) > nsteps + 1) {
    values <- breaks.unique[is.finite(breaks.unique) & breaks.unique != 0]
    samples <- sample(values, nsteps - 2)
    breaks <- sort(c(-Inf, 0, Inf, samples))
}**

- Changed as suggested.

**CheckAttributes.R:33 suppressWarnings() in code can mask real problems with user data; instead protect against known warnings (eg., removing NAs?) for easier to understand and more robust code.**

-  Removed suppressWarnings(), as not required. 

**Compactness.R:23 avoid iteration (n function calls) in favor of vectorization (1 function call); update complicated data structures once rather than n times (also, e.g., Knet.R:62-67)

res_attr <- rep(list(NA), length(element.names))
names(res_attr) <- element.names
res[[attr]] <- res_attr
Avoid repeated calculation of the same value

res_attr <- rep(list(NA), length(element.names))
names(res_attr) <- element.names
res <- rep(res_attr, length(vertex.attr))
names(res) <- vertex.attr**

- I have updated Compactness.R as suggested. Knet.R:62-67 cannot be run within a rep() call, as Shuffle(vertex.weights, ignore=vertex.weights.is.na) needs to be run each time.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alexjcornish.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SANTA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SANTA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
