### ISSUE TITLE
CelliD

### ISSUE THREAD

**Issue by Cortalak** [Bioconductor/Contributions#1845]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RausellLab/CelliD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Cortalak** [comment]
Hello @nturaga,

I had my paper recently accepted for publication in a high impact peer-reviewed journal and we would like to include if possible the Bioconductor URL in the abstract rather than the github one.

I was wondering if I had done all the required steps until the personalized review .
If it is the case, it would help me a lot if I can go through the rest of the procedure as soon as possible.
Sorry for this sudden request, and if not possible I will just put the github link on the publication.

Thank you very much.

Best regards

Akira

**Comment by nturaga** [comment]
Hi,

During your package review, I realized I could not build your package on my machine locally. 

Please help me get past this error as it is not informative at all. Likely, other users will face the same issue. 

```
Quitting from lines 55-60 (BioconductorVignette.Rmd)
Error: processing vignette 'BioconductorVignette.Rmd' failed with diagnostics:
cannot open the connection to 'https://storage.googleapis.com/cellid-cbl/BaronMatrix.rds'
--- failed re-building ‘BioconductorVignette.Rmd’

SUMMARY: processing the following file failed:
  ‘BioconductorVignette.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by Cortalak** [comment]
Hello,

Sorry, It seems that the  billing for our google cloud bucket has expired since the last bioconductor build and the rds object cannot be accessed.
I will try to contact the admin to resolve the problem asap and will let you know when it is done.

Thank you for the feedback.

**Comment by nturaga** [comment]
You can submit such a data set as an ExperimentHub and use it from there.

https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html
package

You don't have to store it on Google cloud and have the link expire.
ExperimentHub will give you a constant link that does not expire.

Best,

Nitesh

**Comment by Cortalak** [comment]
Hello,

We have updated payment for google cloud and the package should now build normally without any new commit. 
We also cosidered ExperimentHub but we might make a few changes on the vignette to use in house data in the future.
We would like to wait for that moment to create a ExperimentHub package and keep the flexibility of our own bucket for now as the paper will be published in 2 - 3 weeks and new issue may arise from new users.

Best regards

Akira

**Comment by Cortalak** [comment]
Hello,

I was just wondering if the package could now be built on your local machine. Did I do everything needed so that the review process can advance?

Thanks

Akira

**Comment by nturaga** [comment]
I'll take a look at it today.

**Comment by Cortalak** [comment]
Hello,

I wanted to know if there is there is any advancement on the review process.
we are now editing the proofs of the manuscript in Nature Biotechnology and would like to include if possible in the paper the bioconductor URL rather than the Github repository.

Thanks 

Akira

**Comment by nturaga** [comment]
Hi, Sorry for the delay. I'll be posting a review today.

**Comment by nturaga** [comment]
## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION 

ok

## NAMESPACE

- It seems most functions are exported. Are you sure you need all these functions to be available to the user? If you believe all the functions that are exported are needed, ignore this. 

## R

- RcppExports.R - ok 

- When you use `stop()` it's smart to use a message within the `stop('I'm stopping here because....'), give users some idea of why it stopped since all they see is `Error:`. https://github.com/RausellLab/CelliD/blob/master/R/check.R#L62.

## man

- The documentation for the functions is not extensive, you can consider improving this.

## vignettes
-  good

## General

- Please replace the google buckets with an annotation hub or data experiment package. It is more stable that way.

**Comment by Cortalak** [comment]
Hello,

Thank you a lot for the review for the data experiment package do I add the package inquiry here or do I open another issue?
I saw that the package with the dependency must be posted first." _Start by submitting the package that can be installed without a dependency on any of the other packages you are submitting (this is usually the experiment data package)._ "

**Comment by nturaga** [comment]
Hi, 

Have you made the changes to the code in the review? I'm happy to accept your package but you'll have to submit at data experiment package later on probably. I'm ok to allow this since you have a time crunch.

**Comment by Cortalak** [comment]
Hello,

Thank you very much for this exception, We're almost done with the rest of the changes, we will get back to you as soon as it is done.

Akira

**Comment by Cortalak** [comment]
> ## R CMD build
> ok
> 
> ## R CMD INSTALL
> ok
> 
> ## DESCRIPTION
> ok
> 
> ## NAMESPACE
> * It seems most functions are exported. Are you sure you need all these functions to be available to the user? If you believe all the functions that are exported are needed, ignore this.
> **All functions that are exported must indeed be made available to the user.**
> 
> ## R
> * When you use `stop()` it's smart to use a message within the `stop('I'm stopping here because....'), give users some idea of why it stopped since all they see is `Error:`. https://github.com/RausellLab/CelliD/blob/master/R/check.R#L62.
> ** Added informative message for stops**
> 
> ## man
> * The documentation for the functions is not extensive, you can consider improving this.
> **Added more extensive description for each functions especially for core functions such as RunMCA**
>
> ## vignettes
> * good
> **replaced the old github installation process with the one with Biocmanager**

**Comment by Cortalak** [comment]
Hello,

I made the changes to assess the different point of the review. 

However right now I fail at the build level when I push my changes.

This is due to one of the core dependencies "Seurat" not installing properly due to their corrupted version 4.0.0. 
https://github.com/satijalab/seurat/issues/4226
They have just freshly pushed a new version on CRAN which is 4.0.1 and I forced in my DESCRIPTION file the version 4.0.1. However it seems that Bioconductor build check doesn't recognize the newly created version and only finds the 4.0.0.

Shall I just wait a little bit more and retry to push?

Thank you very much for your help

Akira

**Comment by Cortalak** [comment]
Hello,

The package was finally able to build without error and now the code adresses the issues in the review apart from the experimenthub package.

It should now be ready.

Akira

**Comment by nturaga** [comment]
Hi,

You have a new issue you have to fix now,

```
 Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        hyper.R (line 47, column 30)
        hyper.R (line 56, column 14)
        hyper.R (line 57, column 14)
        hyper.R (line 97, column 30)
        hyper.R (line 106, column 14)
        hyper.R (line 107, column 14)
```

**Comment by Cortalak** [comment]
> Hi,
> 
> You have a new issue you have to fix now,
> 
> ```
>  Checking coding practice...
>     * NOTE: Avoid sapply(); use vapply()
>       Found in files:
>         hyper.R (line 47, column 30)
>         hyper.R (line 56, column 14)
>         hyper.R (line 57, column 14)
>         hyper.R (line 97, column 30)
>         hyper.R (line 106, column 14)
>         hyper.R (line 107, column 14)
> ```

The sapply have been changed to vapply in the last commit.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Cortalak.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CelliD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CelliD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
