### ISSUE TITLE
ModCon

### ISSUE THREAD

**Issue by caggtaagtat** [Bioconductor/Contributions#1850]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/caggtaagtat/ModCon

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Hi @caggtaagtat,

ModCon is almost ready for inclusion to Bioconductor. A few minor problems that need your attention:

1. Your DESCRIPTION file contains:
    ```
    selectBestAndMean: Installation of any version of Perl is needed (e.g. strawberry perl).
    ```
    Please use the standard way to report system requirements (see the "Writing R Extensions" manual for more information).

2. The `inst/extdata` folder is for data so files like `app.R`, `score3.pl`, `score5.pl`, `splicemodels/hashseq.m` should probably go somewhere else. Please refer to the "Writing R Extensions" manual for how to organize the files in your package source tree.

3. Is file `splicemodels/hashseq.m~` intentionally included in the package?

Thanks,
H.

**Comment by caggtaagtat** [comment]
Hi hpages,

thank you for the review.

1) I changed it to: 
SystemRequirements: Perl

2) The perl scripts use data in the same folder and I'm not fluent enough in Pyhton to seperate them without disrupting the programm. But I created a new directory for app.R and changed the associated R function, which executes it.

3) I deleted the redundant file 

Kind regards,
Johannes

**Comment by caggtaagtat** [comment]
Hi hpages,

thank you for the review. Here, I repeat my text from above, in case it was hidden between the automatic messages.

1) I changed it to:
    SystemRequirements: Perl

2)  The perl scripts use data in the same folder and I'm not fluent enough in Pyhton to seperate them without disrupting the programm. But I created a new directory for app.R and changed the associated R function, which executes it.

3) I deleted the redundant file

Kind regards,
Johannes

**Comment by hpages** [comment]
Thanks for the changes.

One last thing: please give a proper title to the package. The title should be a short 1-liner (with no period at the end) rather than a repetition of the package name.  See the [current index of Bioconductor software packages](https://bioconductor.org/packages/release/BiocViews.html#___Software) for plenty of examples.

Best,
H.

**Comment by caggtaagtat** [comment]
Hi hpages,

I changed the package title in the DESCRIPTION file from "ModCon" to "Modifying splice site usage by changing the mRNP code, while maintaining the genetic code"

Thank you,
Johannes

**Comment by hpages** [comment]
Thanks!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/caggtaagtat.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ModCon")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ModCon

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
