### ISSUE TITLE
satuRn

### ISSUE THREAD

**Issue by jgilis** [Bioconductor/Contributions#1864]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/statOmics/satuRn

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Kayla-Morrell** [comment]
@jgilis - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review. Overall, this is a really well put together package. Very well organized, 
written, and documented. I have just a few points below.

## General package development

- [ ] REQUIRED: There are some files that either need to be removed or moved to
  another location. In the 'man/' directory, the 'figures/' directory should be
in the 'inst/' directory. What is the purpose of the 'dev/' directory? This is
usually not something we allow in our packages. If it's not necessary it should
be removed.

## Vignette

- [ ] REQUIRED: The installation section should demonstrate to the user how to
  install from Bioconductor and not from GitHub. The code should look something
like the following and should include `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("satuRn")
```

- [ ] REQUIRED: All sections of code should be exectutable, is there reason for
  having the sections at lines 171 and 204 as `eval = FALSE`?

## R code

- [ ] REQUIRED: Unexported object imported by a ':::' call: 'locfdr::locmle'.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 99 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reaosns, consider multiples of 4 spaces for 
line indents. There are 22 lines that are not.

Best,
Kayla

**Comment by jgilis** [comment]
Dear Kayla,

Thank you very much for your kind words in the previous review. This is the first time I submit to Bioconductor and even the first time I published an R package for external use. The fact that the package was immediately quite close to the desired output really is a testament to the authors of the `BiocCheck` package and the extensive documentation for the submission procedure as provided by Bioconductor.

That said, I recently made a new push to accommodate your remarks. All *requirements* should now be met. I also worked on meeting your *suggestions*, reducing the number of long lines and troublesome indents. However, some troublesome indents remain (also upon running `styler`), in particular in the *man* pages created by `roxygen2`.

Looking forward to completing the submission procedure,


Kind regards,

Jeroen

**Comment by Kayla-Morrell** [comment]
@jgilis - Thank you for making the required changes and attempting to clear up the suggestions as well. I have looked over the changes and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jgilis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("satuRn")`. The package 'landing page' will be created at

https://bioconductor.org/packages/satuRn

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
