### ISSUE TITLE
Meaningful Immunogenetic Data at Scale

### ISSUE THREAD

**Issue by mcjmigdal** [Bioconductor/Contributions#1878]
- Repository: https://github.com/Genentech/midasHLA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mcjmigdal** [comment]
Dear @vjcitn, as you can see the package is still getting some warnings - there are two of them. I would like to ask for your advice on how to best tackle those problems:

`* WARNING: Update R version dependency from 4.0.0 to 4.1.`
The reason for keeping the older R version is that the package is currently in use already by some users, making requiring developmental R version impractical for them. I would appreciate if you could advise on how I could handle this.

</br>

```
* WARNING: Add non-empty \value sections to the following man
      pages: man/MiDAS-class.Rd
```
I might be missing something, however as the class definition is actually not a function I don't see a strong reason for it to include the \value section. On the same time current documentation does includes description of the class itself and it feels more natural to me to omit \value section. Please let me know how critical it is to include the \value section in this case.

Cheers Maciek

**Comment by vjcitn** [comment]
The package code you are developing here will be released in Bioconductor 3.13, which will use R 4.1 exclusively.  If you want to support R 4.0 create a branch in your github repo and direct users there.  If users are already working from github, for now they can continue with that, and the 4.1 spec can be in the DESCRIPTION in the bioconductor git repo without affecting them.  But the **git repo for the devel branch must specify 4.1**

As for the second concern it might be a false positive, but I'd put in a simple @return directive with 'instance of class ...' and get rid of the warning.  File an issue at BiocCheck if you want to pursue this.  Do you have a constructor with the name of the class?  That would be the place to scotch this.

**Comment by mcjmigdal** [comment]
> Do you have a constructor with the name of the class? 

The class is named `MiDAS`, there is no constructor function called `MiDAS` we only provide user level function `prepareMiDAS` that does returns `MiDAS` object.

**Comment by vjcitn** [comment]
Sorry for delay.  Please deal with BiocCheck comment "Consider adding these automatically suggested biocViews: CellBiology" and then I will accept.

**Comment by mcjmigdal** [comment]
@vjcitn Hi thanks for the review! I've added CellBiology tag, however there seems to be now some problem with build on macOS I believe the cause must be more global as I haven't changed anything except that tag. What should I do now? Here is the error message. 

```
===============================

 R CMD BUILD

===============================

* checking for file midasHLA/DESCRIPTION ... OK
* preparing midasHLA:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
ERROR: dependency kableExtra is not available for package midasHLA
* removing /private/var/folders/xd/gpmk_x0977q95yv9tx6z_pqm0000gv/T/RtmpPismJB/Rinst4d527695e618/midasHLA
      -----------------------------------
ERROR: package installation failed
```

**Comment by mcjmigdal** [comment]
@vjcitn Hi thanks for the review! I've added CellBiology tag, however there seems to be now some problem with build on macOS I believe the cause must be more global as I haven't changed anything except that tag. What should I do now? Here is the error message. 

```
===============================

 R CMD BUILD

===============================

* checking for file midasHLA/DESCRIPTION ... OK
* preparing midasHLA:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
ERROR: dependency kableExtra is not available for package midasHLA
* removing /private/var/folders/xd/gpmk_x0977q95yv9tx6z_pqm0000gv/T/RtmpPismJB/Rinst4d527695e618/midasHLA
      -----------------------------------
ERROR: package installation failed
```

**Comment by vjcitn** [comment]
That will resolve naturally.  I will accept.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mcjmigdal.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("midasHLA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/midasHLA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
