### ISSUE TITLE
interacCircos

### ISSUE THREAD

**Issue by mrcuizhe** [Bioconductor/Contributions#1885]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mrcuizhe/interacCircos

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
There are no `BiocViews:` in your DESCRIPTION file; have you checked your package with `BiocCheck::BiocCheck()`?

**Comment by mrcuizhe** [comment]
Hello,

May I ask why the BioCheck() said that "Package must be removed from CRAN.”? Is that mean I should make a choice between CRAN or Bioconductor?

Thanks
Zhe

**Comment by mtmorgan** [comment]
Yes, your package can be hosted on **either** CRAN or Bioconductor, not both.

**Comment by mrcuizhe** [comment]
Hello, a new version with BiocViews is available in DESCRIPTION file now. Please check that.

**Comment by mtmorgan** [comment]
How do you plan to address the fact that your package is already on CRAN?

**Comment by mrcuizhe** [comment]
No worry, the CRAN man told me that I can send a mail to them when this package is available on BioC and then they will indicate on the CRAN package web page that the package was moved to BioC.

**Comment by mrcuizhe** [comment]
> How do you plan to address the fact that your package is already on CRAN?

No worry, the CRAN man told me that I can send a mail to them when this package is available on BioC and then they will indicate on the CRAN package web page that the package was moved to BioC.

**Comment by mrcuizhe** [comment]
> How do you plan to address the fact that your package is already on CRAN?

Hello, the package now only contains one error about CRAN, as "the CRAN man told me that I can send a mail to them when this package is available on BioC and then they will indicate on the CRAN package web page that the package was moved to BioC."
What should I do next?

**Comment by mrcuizhe** [comment]
@mtmorgan May I ask what should I do next? Thanks!

**Comment by mrcuizhe** [comment]
> Your package has been assigned to a reviewer; @hpages will review your package, usually within 2 weeks.

@mtmorgan Thanks!

**Comment by hpages** [comment]
Hi @mrcuizhe ,

Please remove the `doc/` folder. This has no place in the _source tree_ of your package. `R CMD build` will automatically add an `inst/doc` folder to the _package source tarball_ and populate it with `interacCircos.html`, `interacCircos.Rmd`, and `interacCircos.R`.

Thanks,
H.

**Comment by mrcuizhe** [comment]
Hello @hpages ,

The doc/ folder has been removed.

Thanks
Zhe

**Comment by hpages** [comment]
Thanks for removing the `doc/` folder.

Note that the vignette would need to be a _real vignette_ (i.e. a vignette with code chunks that are evaluated by `R CMD check`) and not just a list of pointers to static documents on github.io.

The reason static/precompiled vignettes must be avoided is that there's no way to know when the code in them breaks. And the code in them will break at some point.

OTOH when the code in a _real vignette_ breaks, we will immediately know that, thanks to our daily checks. This is why providing a _real vignette_ is a key feature of Bioconductor.

Thanks,
H.

**Comment by mrcuizhe** [comment]
Hello @hpages 

A new version with a real vignette is available now, could you please check that ?

Thanks
Zhe

**Comment by mrcuizhe** [comment]
Hello @hpages 

Could you please check our newest bump of interacCircos?

Thanks
Zhe

**Comment by hpages** [comment]
Hi,

You're using `eval=FALSE` for all the code chunks in your vignette so how is that a _real_ vignette? Please refer to my earlier explanation of what Bioconductor expectations are for vignettes. The key part is that the code chunks must be _evaluated_ by `R CMD build` (or `R CMD check`).

Also this is a package for generating plots and the vignette doesn't contain any plots?

Please use the left arrow (`<-`) instead of `=` for assignments. Also put a space before and after the `<-`. So:

    snpData <- snpExample

instead of:

    snpData=snpExample

Finally please address the `R CMD check` warning that you get on all platforms.

Thanks,
H.

**Comment by hpages** [comment]
I also realize now that the version of interacCircos that is on CRAN is at version 1.0.0. Versions should never go down so please bump the version of this submission to 1.1.0. When we release BioC 3.13, the version of the package will automatically get bumped to 1.2.0 (this is part of our release process). Thanks!

**Comment by mrcuizhe** [comment]
Hi @hpages,

May I ask how can I bump a version from 0.99.4 to 1.1.0?

When I push my new version to remote, it showed "Error: Illegal version bump from '0.99.4' to '1.1.0'." 

Thanks
Zhe

**Comment by lshep** [comment]
@nturaga can you assist with this,  we want to make a version exception in this case as the package is moving from CRAN to Bioconductor.  See https://github.com/Bioconductor/Contributions/issues/1885#issuecomment-816588031

**Comment by nturaga** [comment]
Hi @mrcuizhe @lshep 

Please make the push now. And let me know as soon as the version has been bumped. I'll revert the hook to act properly again on your package.

**Comment by mrcuizhe** [comment]
Hi @nturaga 

Version 1.1.1 has been pushed to remote, please check that

Thanks
Zhe

**Comment by hpages** [comment]
Thanks for the changes. Are you going to add plots to the vignette? I don't see any plot in the HTML vignette.

Also code like this is very hard to read:
```
Circos(moduleList=CircosSnp('SNP01', minRadius =150,
maxRadius = 190, data = snpExample,SNPFillColor= "#9ACD32",
circleSize= 2, SNPAxisColor= "#B8B8B8", SNPAxisWidth= 0.5,
animationDisplay=TRUE,animationTime= 2000, animationDelay= 0,
animationType= "linear") +
CircosBackground('BG01',minRadius = 145,maxRadius = 200))
```
Indentation should be used for expressions that span multiple lines (the 2nd line and any additional line should be indented with respect to the 1st line). Code clarity/readability is important.

Thanks,
H.

**Comment by mrcuizhe** [comment]
Hi @hpages 

Thank you for the suggestion and we have corrected that.

New version is bumped, please check that!

Best
Zhe

**Comment by hpages** [comment]
Please remove the `interacCircos.html` file. The HTML version of the vignette has no place in the package source tree.

Also I see that you've added the `jquery2.js` file to the package but it's not clear to me that you are using it. Do you really need this file?

Please be careful to not add unnecessary files to your package source tree.

Thanks!

**Comment by hpages** [comment]
All good.

Please remove the package from CRAN as soon as possible. Thanks!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mrcuizhe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("interacCircos")`. The package 'landing page' will be created at

https://bioconductor.org/packages/interacCircos

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
