### ISSUE TITLE
OSCA.multisample

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1888]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/OSCA-source/OSCA.multisample

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LTLA** [comment]
Another week, another book. This takes two of the chunkiest chapters in **OSCA.advanced** and breaks it up into 5 separate chapters for easier comprehension. It also migrates some content from **OSCA.workflows**.

**Comment by LTLA** [comment]
The books are now dependent on each other; I assume that the SPB doesn't know how to install **OSCA.workflows**.

**Comment by lshep** [comment]
Are these already accepted?

**Comment by lshep** [comment]
@mtmorgan  / @hpages  I thought we changed the BiocManager::install to recognize books so if they are already accepted than I'm surprised it couldn't find it.  If they are not accepted or reviewed, than no the SPB would not be able to find it; thats why we ask contributors to submit related packages under the same issue for review as we have a mechanism for them to be temporarily installed in an issue specific path.

**Comment by LTLA** [comment]
Accepted and building (https://bioconductor.org/checkResults/devel/books-LATEST/OSCA.workflows/rex3-buildsrc.html). Well, it built at some point this release; for the purposes of this discussion, you can ignore the build errors, because OSCA.workflows should been available at some point.

**Comment by mtmorgan** [comment]
BiocManager recognizes books, but only in 1.30.11, which was just submitted to CRAN; it could be cloned from https://github.com/Bioconductor/BiocManager for the impatient. I'd be tempted to wait for the CRAN release.

**Comment by LTLA** [comment]
Okay, thanks. Heads-up that it'll probably continue to fail until Friday at the earliest when we have a chance to rebuild **OSCA.workflows**. I recently refactored how content is shared across books and I've been getting tripped up by race conditions. Would be nice to get more frequent builds on the BioC-devel machines.

**Comment by LTLA** [comment]
Can we just get this in so @hpages and I can try it out on the book builder?

**Comment by mtmorgan** [comment]
It doesn't build on the SPB so won't build on the build system?

**Comment by LTLA** [comment]
I don't think any of the previous books I submitted have ever built on the SPB. In fact, we didn't even try. For example, the SPB errors relate to not finding another book package that the current book depends on, so I don't know what to do about that.

**Comment by mtmorgan** [comment]
@hpages can you process this package? thx

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("OSCA.multisample")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OSCA.multisample

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
