### ISSUE TITLE
ASpli

### ISSUE THREAD

**Issue by estepi** [Bioconductor/Contributions#19]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/estepi/ASpli

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by estepi** [comment]
Hi all! My package was built OK on Linux and Mac but not in Windows. I'm trying to detangle the problem. I've already built in a Windows machine with the same command you used. I would appreciate any help.

**Comment by estepi** [comment]
Hi all! Is there any news about my last push? thanks in advance

**Comment by estepi** [comment]
Hi all! Could anybody help me in which step I should focus in order to avoid warnings? I didn't found any warning in the report. Thanks in advance!

**Comment by dtenenba** [comment]
If BIocCheck finds items that it is RECOMMENDED that you fix, the output of the build will be WARNINGS. So search the build report for WARNINGS and that will tell you what to fix.

**Comment by estepi** [comment]
Thanks! I will try to fix ASAP. I was only considering R CMD CHECK warnings

**Comment by estepi** [comment]
Hi all! 
Can anyone help me in which step should I follow now, that the package has been successfully built without errors and warnings? I was wondering if It is possible to mention in a manuscript under revision that the package will be available in next release of Bioconductor? Thanks in advance!

**Comment by hpages** [comment]
Hola Estefania,

Glad to see that you're submitting the ASplit package for inclusion to Bioconductor! The package looks great.

I only have a few minor comments, mostly about cosmetic. Most of them are aimed at making the package a little bit more user-friendly:

1) A few missing imports: parallel, S4Vectors, AnnotationDbi, and DESeq2 Except for parallel, these packages need to go in both, the Imports field of your description file and your NAMESPACE file. parallel should go in the Imports field but only the mclapply symbol should actually be imported (by adding importFrom(parallel, mclapply) to the NAMESPACE file).

2) Please add a "show" method for ASpli-counts objects so they are printed on screen in a more compact and more user-friendly form. Also maybe consider adding "show" methods for the other objects defined in the package (ASpli-features, ASpli-AS, and ASpli-DU objects).

3) Found in the vignette:

    ASpli can be installed locally from the command line:

    R CMD INSTALL ASpli_0.99.0.tar.gz

Note that this installation method is strongly discouraged for Bioconductor packages. Using biocLite() is the only method that you should advertize in your vignette.

Also I would suggest that you place the following sentence:

    ASpli pacakge requires previous installation of several bioconductor
    packages: edgeR, DEXSeq, GenomicFeatures, GenomicRanges, GenomicAlignments
    and Gviz.

right below the biocLite() method. Also I suggest that you reformulate to say something like:

    biocLite() will take care of installing all the packages that ASpli depends
    on e.g. edgeR, DEXSeq, GenomicFeatures, GenomicRanges, GenomicAlignments,
    Gviz, and more...

Right now, because of its location at the beginning of the "Getting started" section, it's not clear what people should do about this list of dependencies. They might think they need to install all these packages by hand.

4) Try to keep your code as simple as possible. Sometimes the code seems unnecessarily complicated. For example, in the man page for loadBAM():

     targets <- data.frame(
         row.names=names(RNAseqData.HNRNPC.bam.chr14_BAMFILES),
         bam=matrix(unlist(RNAseqData.HNRNPC.bam.chr14_BAMFILES), ncol=1, byrow=TRUE), 
         condition=c(rep("CT",4),rep("KD",4)))

This code contains a few unnecessary steps that distract and confuse the user. The above is simply achieved with:

     targets <- data.frame(bam=RNAseqData.HNRNPC.bam.chr14_BAMFILES,
                           condition=c(rep("CT",4),rep("KD",4)))

Another example is this code in the vignette:

     targets_2 <- data.frame(bam=c("Ct_time1_rep1.bam", "Ct_time1_rep2.bam",
                                   "Ct_time2_rep1.bam", "Ct_time2_rep2.bam",
                                   "Mut_time1_rep1.bam","Mut_time1_rep2.bam",
                                   "Mut_time2_rep1.bam","Mut_time2_rep2.bam"),
                             condition=paste(bkg, time, sep="."),
                             row.names=c("Ct_time1_rep1", "Ct_time1_rep2",
                                         "Ct_time2_rep1", "Ct_time2_rep2",
                                         "Mut_time1_rep1","Mut_time1_rep2",
                                         "Mut_time2_rep1","Mut_time2_rep2" ))

A version a little bit shorter and easier to read:

     bam <- c("Ct_time1_rep1.bam",  "Ct_time1_rep2.bam",
              "Ct_time2_rep1.bam",  "Ct_time2_rep2.bam",
              "Mut_time1_rep1.bam", "Mut_time1_rep2.bam",
              "Mut_time2_rep1.bam", "Mut_time2_rep2.bam")
     targets_2 <- data.frame(bam=bam,
                             condition=paste(bkg, time, sep="."),
                             row.names=sub("\\.bam$", "", bam))

Inferring the row names from the BAM files programmatically is less error prone than explicitely spelling them out.

You might want to revisit other calls to data.frame() and try to simplify them. This will improve the overall readability of your examples.

5) No curly brackets arount standardGeneric() e.g.

    setGeneric (
      name= "rds",
      def=function(counts, targets) standardGeneric("rds"))

instead of

    setGeneric (
      name= "rds",
      def=function(counts, targets) {standardGeneric("rds")})

6) Coding style:

6-a) Using the dash (-) in class names is strongly discouraged. It breaks a few things like trying to access the man page of the class with class?ASpli-DU or trying to define S3 methods for ASpli-DU objects. You can replace the dash with an underscore (_) or a dot (.) if you want. Note however that the preferred naming style in Bioconductor is CamelCase (e.g. ASpliFeatures, ASpliCounts, ASpliAS, ASpliDU).

6-b) Use <- instead of = for assignments.

6-c) Put a space around <- (i.e. before and after). This will greatly improve the readability of your code.

Don't hesitate to ask on the bioc-devel mailing list if you have questions or
concerns about this.

Thanks,
Hervé

**Comment by estepi** [comment]
Hi Herve! 
Thank you very much for your comments! I'm working to fix them.
Should I push changes and change version number as before?  I will try to do it as soon as possible :)

**Comment by hpages** [comment]
Hi Estefania,
Yes, please push your changes and change version number as usual. Thanks!
H.

**Comment by estepi** [comment]
Hi all, could anybody help me with this error on Mac OS:

Loading required package: XVector
Error: package BiocGenerics 0.19.1 is loaded, but >= 0.19.2 is required by XVector
In addition: Warning message:
version 0.19.2 of BiocGenerics masked by 0.19.1 in /Users/pkgbuild/Library/R/3.3/library 
Execution halted

Thanks in advance,

**Comment by hpages** [comment]
Hi Stefi,

Sorry for the delay.  Thanks for the changes you made to ASpli. Please ignore the single package builder warning on morelia (Mac).

There are a few leftovers from my previous feedback.

1) One missing import:

    importFrom(parallel, mclapply)

2) Thanks for adding a "show" method for ASpliCounts object. Note that the method needs to print an "\n" at the end of the last output line so that the following prompt (>) gets displayed at the beginning of the next line:

    > counts
    Object of class ASpliCounts 
    Gene counts: 782 genes analysed. Access using countsg(object) 
    Gene RD: 782 genes analysed. Access using rdsg(object) 
    Bin counts: 13091 bins analysed. Access using countsb(object) 
    Bin RD: 13091 bins analysed. Access using rdsb(object) 
    Junction counts: 7880 junctions analysed. Access using countsj(object)> 

3) Please remove this from the vignette:

    ASpli can be installed locally from the command line:

    R CMD INSTALL ASpli_0.99.0.tar.gz

  As I tried to explain earlier, we strongly discourage this installation method. That's how people mix-up release and devel packages and break their installation. It happens all the time :-/
Also please remove the sentence "ASpli pacakge requires previous installation of ...". It is not accurate (there are a lot more dependencies) and not helpful (people might get confused and think they need to install these dependencies separately). It's better to give the standard way of installing the package first (i.e. with biocLite()). After which you can say a word about dependencies. See my previous feedback for the details.

4) See my previous feedback for how to simplify (and making less error prone) the code you use in the vignette for creating 'targets_2'.

Thanks,
H.

**Comment by hpages** [comment]
Hi Stefi,

I think I got confused and was looking at an old PDF of the vignette. I just looked at the vignette again (and this time I made sure I was looking at the current vignette) and it looks fine. So please ignore items 3) and 4) in my previous post. Sorry for the confusion.

Thanks,
H.

**Comment by estepi** [comment]
Hi Herve! Never mind! Im sorry I am a little anxious. You know this is my first package so, I'm making many common mistakes. I should replace pdf file under DOC directory. Sorry for this.
I'm worry because we are finished a paper where we have been using ASpli and I should cite if everything is OK.
I was worry also for the "check" problem because I thouth you need to see and OK in the package in order to continue with manual revision. 

let me know what I shoul do now.

Many many thanks in advance

Cheers, 
Estefi

**Comment by estepi** [comment]
Hi all, 
I would like to know if I should do something else with the package.  It is my package on devel list now?
Thank you very much in advance,
Estefi

**Comment by hpages** [comment]
Hi Stefi,
Everything looks fine now so I'm marking the package as accepted. Congratulations!
We'll add the package to our Subversion repository and to our builds in the next few days. You will soon receive your svn credentials and other important information about package maintenance and our daily builds.
Best,
H.

**Comment by estepi** [comment]
Hi Herve! Thank you very much! I am excited !!!! :) please, let me know if I have to do something else. I would like to make ASpli freely available via Bioconductor as soon as possible because we would like to include it in some recent articles and also send a manuscript describing the package. 
cheers, 
Estefi
