### ISSUE TITLE
Rbec

### ISSUE THREAD

**Issue by PengfanZhang** [Bioconductor/Contributions#1907]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PengfanZhang/Rbec

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
Your DESCRIPTION file does not contain a 'biocViews' field; please review the submission and package guidelines, and ensure that your package satisfies `BiocCheck::BiocCheck()`.

**Comment by mtmorgan** [comment]
You added two 'top level' biocViews terms -- 'Software' and 'Workflow'. Keep only 'Software', and choose other biocViews from **under** the 'Software' item at http://bioconductor.org/packages/release/BiocViews.html#___Software, see for instance the biocViews terms used by dada2: https://github.com/benjjneb/dada2/blob/45279a29e542a06561562d064c1241282a584e18/DESCRIPTION#L40

**Comment by PengfanZhang** [comment]
Dear mtmorgan,

I have messed up with the git repo. Currently the bioconductor Rbec repo and  the github Rbec repo have two different .git.  I will try to start a new issue with the new .git. Could you help me delete this issue? 

Otherwise, are there any solutions to get rid of the unrelated repos?

Thanks in advance,
Pengfan

**Comment by mtmorgan** [comment]
@nturaga can you help Pengfang?

**Comment by nturaga** [comment]
Hi @PengfanZhang , what do you mean two different `.git` directories?? This is highly unusual btw.

**Comment by PengfanZhang** [comment]
> Hi @PengfanZhang , what do you mean two different `.git` directories?? This is highly unusual btw.

Hi @nturaga , actually I updated my github repo from a local repo that is different to the previous one I used to push the data to github. Then when I tried to connect the updated github repo with bioconductor, an error message saying 'unrelated histories'. But I have fixed this problem by implementing all the conflicts. Thanks anyway!

**Comment by nturaga** [comment]
ok, so based on your message I'm guessing you don't need help now.

**Comment by lshep** [comment]
Thank you for your package submission. Please see initial review below: 

**DESCRIPTION**

- [ ] We recommend removing the manually created date field.  This can often get stale and not updated regularly.

**README**

- [ ] In BiocManager it is not advised to place strict versions in the install so that the packages are using recent versions of all packages.  Please remove  `version="3.11"`.  The package should work with the current version of dada2. 

- [ ] Please include Bioconductor installations instructions instead of installing Rbec by downloading source. Also this manual inclusion of source tar.gz will get stale and inaccurate every Bioconductor release and is not recommended advertising. As it is already since you are submitting version 0.99.3 instead of 0.1.0

- [ ] Running your example code does not work

```
> library(Rbec)
> fq <- system.file("extdata", "test_raw_merged_reads.fastq", package="Rbec")
> ref <- system.file("extdata", "test_ref.fasta", package="Rbec")
> Rbec(fq, ref, "./", 1, 500, 33)
Error: '' does not exist in current working directory ('/home/shepherd/PkgReviews/Rbec')
```

**inst**

- [ ] Please also include an `inst/scripts` directory that describes how the data in `inst/extdata` was created. It can be code, sudo-code, or text but should include any source/version information and any preprocessing of files before including in the directory for release to users.
  

**vignette**

- [ ] You need to have a working vignette with runnable code chunks. The vignette should demonstrate how to use the package.  Perhaps moving the example running of the code from the README to the vignette. Vignettes cannot be static and must show package functionality with executed code. 

**R/man**

- [x] I won't do an in-depth review of code until there is a working vignette. 

Please address the above issues.  When ready please do a version bump and push to the git repo to trigger a new build report.  When ready for a re-review please comment back here.

**Comment by PengfanZhang** [comment]
> Thank you for your package submission. Please see initial review below:
> 
> **DESCRIPTION**
> 
> * [ ]  We recommend removing the manually created date field.  This can often get stale and not updated regularly.
> 
> **README**
> 
> * [ ]  In BiocManager it is not advised to place strict versions in the install so that the packages are using recent versions of all packages.  Please remove  `version="3.11"`.  The package should work with the current version of dada2.
> * [ ]  Please include Bioconductor installations instructions instead of installing Rbec by downloading source. Also this manual inclusion of source tar.gz will get stale and inaccurate every Bioconductor release and is not recommended advertising. As it is already since you are submitting version 0.99.3 instead of 0.1.0
> * [ ]  Running your example code does not work
> 
> ```
> > library(Rbec)
> > fq <- system.file("extdata", "test_raw_merged_reads.fastq", package="Rbec")
> > ref <- system.file("extdata", "test_ref.fasta", package="Rbec")
> > Rbec(fq, ref, "./", 1, 500, 33)
> Error: '' does not exist in current working directory ('/home/shepherd/PkgReviews/Rbec')
> ```
> 
> **inst**
> 
> * [ ]  Please also include an `inst/scripts` directory that describes how the data in `inst/extdata` was created. It can be code, sudo-code, or text but should include any source/version information and any preprocessing of files before including in the directory for release to users.
> 
> **vignette**
> 
> * [ ]  You need to have a working vignette with runnable code chunks. The vignette should demonstrate how to use the package.  Perhaps moving the example running of the code from the README to the vignette. Vignettes cannot be static and must show package functionality with executed code.
> 
> **R/man**
> 
> * [x]  I won't do an in-depth review of code until there is a working vignette.
> 
> Please address the above issues. When ready please do a version bump and push to the git repo to trigger a new build report. When ready for a re-review please comment back here.

@lshep Dear Ishep,

Great thanks for your review and feedbacks. I have implemented all the changes accordingly and pushed it to git repo. Please restart the review.

Best,
Pengfan

**Comment by PengfanZhang** [comment]
> Thank you for your package submission. Please see initial review below:
> 
> **DESCRIPTION**
> 
> * [ ]  We recommend removing the manually created date field.  This can often get stale and not updated regularly.
> 
> **README**
> 
> * [ ]  In BiocManager it is not advised to place strict versions in the install so that the packages are using recent versions of all packages.  Please remove  `version="3.11"`.  The package should work with the current version of dada2.
> * [ ]  Please include Bioconductor installations instructions instead of installing Rbec by downloading source. Also this manual inclusion of source tar.gz will get stale and inaccurate every Bioconductor release and is not recommended advertising. As it is already since you are submitting version 0.99.3 instead of 0.1.0
> * [ ]  Running your example code does not work
> 
> ```
> > library(Rbec)
> > fq <- system.file("extdata", "test_raw_merged_reads.fastq", package="Rbec")
> > ref <- system.file("extdata", "test_ref.fasta", package="Rbec")
> > Rbec(fq, ref, "./", 1, 500, 33)
> Error: '' does not exist in current working directory ('/home/shepherd/PkgReviews/Rbec')
> ```
> 
> **inst**
> 
> * [ ]  Please also include an `inst/scripts` directory that describes how the data in `inst/extdata` was created. It can be code, sudo-code, or text but should include any source/version information and any preprocessing of files before including in the directory for release to users.
> 
> **vignette**
> 
> * [ ]  You need to have a working vignette with runnable code chunks. The vignette should demonstrate how to use the package.  Perhaps moving the example running of the code from the README to the vignette. Vignettes cannot be static and must show package functionality with executed code.
> 
> **R/man**
> 
> * [x]  I won't do an in-depth review of code until there is a working vignette.
> 
> Please address the above issues. When ready please do a version bump and push to the git repo to trigger a new build report. When ready for a re-review please comment back here.

**Comment by PengfanZhang** [comment]
Hi @lshep , I have implemented all the changes and pushed the new version to the git repo. Please help me re-start the review process. Thanks in advance.

**Comment by lshep** [comment]
Thank you.  I will re-review your package in the next week or so.  Cheers

**Comment by lshep** [comment]
Please see the following comments:  

**README**

- [ ] Please don't show examples using a users home directory. We recommend showing the usage/example using a tempdir() instead of defaulting to "." . It  seems like Rbec can take outdir as an argument.


**vignette**

- [ ] Please don't show examples using a users home directory. We recommend showing the usage/example using a tempdir() instead of defaulting to "." . It seems like Rbec can take outdir as an argument.

- [ ] Based on the vignette and the description. I'm unclear how to run
```
Contam_detect(log_file, outdir)
```

If you are controlling the example used, therefore the sample names,  and the output directory it seems like you should be able to execute this command with your example data?

**R / man**

- [ ] You shouldn't `@export` internal functions and those not listed in the NAMESPACE. and remove empty sections like blank `@examples`. They can be marked with `@internal` to have internal documentation and not export.  If the intention is to export this function that please show examples and export in the NAMESPACE.

- [ ] print should be replaced with message 

Please make the above changes and then trigger a new build by bumping the version in the DESCRIPTION and pushing to git.bioconductor.org
Comment back here when you are ready for another review. 

Cheers,

**Comment by PengfanZhang** [comment]
Hi @lshep , Thanks for the comments, I have uploaded a new version to bioconductor. But during the automatic check, an error message shows up that 'error: DLL 'RcppParallel' not found: maybe not installed for this architecture?' when trying to install on windows server. I have no idea what's going wrong as I only removed '@export' and blank space in scripts. I'm really appreciate if you can help me solve this problem.

**Comment by lshep** [comment]
Thank you for the updates please see comments below: 

**build report**

- [ ] Please fix the NOTES appearing in the build report

**README**

- [ ] Again please do not show writing/creating directly to a users working
  directory.  Use `tempdir()`

**Man pages**

- [ ] Do not write to a working directory with ` outdir="./"`  use `tempdir()`
  or `tempfile()`

**Vignette**

- [ ] Same comment. Don't `dir.create("test_tmp")` which would create in the
  working directory.  Use `tempdir()` or `tempfile()`

- [ ] The code chunk added does not seem to work properly:

```
> log_path <- list.files(paste(path.package("Rbec"), "inst/extdata/contamination_test", sep="/"), recursive=TRUE, full.names=TRUE)
> dir.create("test_tmp")
> writeLines(log_path, "test_tmp/log_file")
> Contam_detect("test_tmp/log_file", "test_tmp")
Error: 'NA' does not exist in current working directory ('/home/shepherd/PkgReviews/Rbec/vignettes').

```

**Comment by PengfanZhang** [comment]
> Thank you for the updates please see comments below:
> 
> **build report**
> 
> * [ ]  Please fix the NOTES appearing in the build report
> 
> **README**
> 
> * [ ]  Again please do not show writing/creating directly to a users working
>   directory.  Use `tempdir()`
> 
> **Man pages**
> 
> * [ ]  Do not write to a working directory with ` outdir="./"`  use `tempdir()`
>   or `tempfile()`
> 
> **Vignette**
> 
> * [ ]  Same comment. Don't `dir.create("test_tmp")` which would create in the
>   working directory.  Use `tempdir()` or `tempfile()`
> * [ ]  The code chunk added does not seem to work properly:
> 
> ```
> > log_path <- list.files(paste(path.package("Rbec"), "inst/extdata/contamination_test", sep="/"), recursive=TRUE, full.names=TRUE)
> > dir.create("test_tmp")
> > writeLines(log_path, "test_tmp/log_file")
> > Contam_detect("test_tmp/log_file", "test_tmp")
> Error: 'NA' does not exist in current working directory ('/home/shepherd/PkgReviews/Rbec/vignettes').
> ```

Hi @lshep , thanks for your review again. I have implemented the replacement with `tempdir()`, but I'm wondering if it's necessary to fix all the NOTES appearing in the BUILD report, as far as I know only the errors and warnings are mandatory to be fixed. Though I have tried to fix some NOTES anyway.

**Comment by lshep** [comment]
As all of BiocChecks are considered best practices and guidelines, Notes are strongly encouraged to fix.

But as it is not strictly required, I will accept the package now that the tempdir has been resolved.  thanks you

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PengfanZhang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rbec")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rbec

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
