### ISSUE TITLE
cyanoFilter

### ISSUE THREAD

**Issue by fomotis** [Bioconductor/Contributions#1917]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fomotis/cyanoFilter

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by fomotis** [comment]
The errors have been corrected, and the changes have been uploaded to Bioconductor upstream.

**Comment by LiNk-NY** [comment]
Hi Olusoji, @fomotis 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# cyanoFilter #1917

Are you depending on other packages that are using `Biobase`? Otherwise
it is recommended to use `SummarizedExperiment`. Some of my feedback here
is based on that assumption that `Biobase` is no longer used. This may be
different if your workflow uses `Biobase` extensively.
Consider separating the plotting and infrastructure functionality into
different packages. This will avoid the growth of dependencies on packages
that only use the infrastructure classes in your package.

## DESCRIPTION

* Can you provide more information about the `Config/testthat/edition` field?
* Is the `Biobase` dependency necessary? See note above.
* Some package version dependencies are overkill. You can remove them for the
internal packages such as `graphics`, `methods`, `stats`, `utils`, and
`grDevices` because those are tied to the R version.
* Unless you are using a specific feature in that version of the package, you
don't need to specify the version number dependency.

## NAMESPACE

* For package consistency, use either `camelCase` or `snake_case` function
naming conventions.
* Looks good.

## vignettes

* (optional) It is easier to review and maintain a vignette whose text is not
flowing off the side of the page. Keep the total column width to 80 characters.
* Avoid loading the `tidyverse` because it is not listed in the `Suggests`
field and the package loads a boatload of unnecessary dependencies for the
vignette. Consider only loading `dplyr`.

## R

* Set your default values to the intended value, e.g., when
`proportion = NULL`, the function changes it to `proportion = 1`. Why not have
`1` as the default value?
* Avoid accessing elements of your class with the `@` symbol. Create a formal
interface to your class.
* Make sure that your logic makes sense, e.g., in `R/debris_nc.R` there is an
`if` `else` statement that appears to do the same thing in both conditions.
* Isolate code differences within `if` `else` logic and only change the
parameter that changes, e.g., `pks <- if (lp2 >= 2) min(pks) else pks` in
`R/debris_nc.R`. This would reduce the number of lines of code and places
where you could have bugs / errors.
* There seems to be a typo in line 46 of `R/good_measurement.R`. It appears
that the code should be `!is.null(mxd_cellpML)`
* I would recommend an alternative name to the `exprs` function and slot name
in your class because it is considered legacy code for extracting and storing
an `ExpressionSet`.
* The tag `Error` does not need to be in your `stop` calls: see
`stop("Error:")`
* It will be confusing to the user to have two `new_flowframe` functions. Can
these be reduced to one?
* Avoid using `AnnotatedDataFrame` and use `S4Vectors::DataFrame`.
* Consider using a different name for your `summary` method because the
arguments do not match the S3 generic. Also, you're combining systems here
with S4 and S3 which may confuse users.
* Reduce cyclomatic complexity by simplifying these lines for checking inputs
in `phyto_filter`:
```r
  } else if(!is.null(pig_channels) & is.null(com_channels)) {

    channels <- pig_channels
    #gate based on the pigments

  } else if(is.null(pig_channels) & !is.null(com_channels)) {

    channels <- com_channels
    #gate based on the complexity channels

  } else {

    channels <- c(pig_channels, com_channels)
    #gate based on the pigments

  }
```
to this:
```r
channels <- c(pig_channels, com_channels)
```

## tests

* It is highly recommended that you add tests to your code to keep it
robust.

**Comment by fomotis** [comment]
Hello. I try to respond to most of the suggestions made in this new version.

However, I am afraid the dependency on Biobase is from my dependencies (flowCore and flowDensity).

**Comment by LiNk-NY** [comment]
Hi Olusoji Oluwafemi Daniel @fomotis 

That's okay, you can depend on Biobase. I am unable to test the package
locally because of an issue with `flowDensity`:

```r
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object 'flowWorkspace.so':
  flowWorkspace.so: undefined symbol: _ZN7cytolib11polygonGate6extendERNS_12MemCytoFrameEf
```

Please respond the the review line by line and make sure that the objects that
you are using in the code are documented or that you are using
`utils::globalVariables`. 

```r
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  PhytoFilter clusterExtract clusterExtractp debrisNc
  getChannel newFlowframe newFlowframe2 pairsPlot pigmentGate
  reducedFlowframe rowNumbers summaries
Undocumented S4 methods:
  generic 'summaries' and siglist 'DebrisFilter'
  generic 'summaries' and siglist 'MarginEvents'
  generic 'summaries' and siglist 'PhytoFilter'
All user-level objects in a package (including S4 classes and methods)
should have documentation entries.
See chapter Writing R documentation files in the Writing R
Extensions manual.
```

**Comment by fomotis** [comment]
@LiNk-NY concerning the error with flow Density. I really don't know why. I face the same with Travis build.
However, it works perfectly on windows. Tried it with my partner's Mac as well, and it builds just fine.

**Comment by LiNk-NY** [comment]
Hi Olusoji, @fomotis 

Please respond to the review when you're ready. 
I was able to install `flowDensity` recently and tried
to check the package but got this error because there
are some version enforcements that are not necessary
in the `DESCRIPTION` file: 

```
* checking package dependencies ... ERROR
Package required and available but unsuitable version: 'stats'

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

Best,
Marcel

**Comment by fomotis** [comment]
Hello Marcel,

Sorry for my delayed response.

I already removed all dependencies in the latest description file. You can have a look. The only restriction has to do with the R version. This is due to a Bioconductor requirement that requires the current R devel version. Is it okay to remove this as well?
If it is, then I can easily fix that.

Best,
Daniel

**Comment by LiNk-NY** [comment]
The restriction to the R version is okay to have in the `DESCRIPTION`. 
Either way, Bioconductor devel only works with R-devel. 

Best,
Marcel

**Comment by fomotis** [comment]
@LiNk-NY 
## Description

* Can you provide more information about the Config/testthat/edition field? **Test Field Removed since I didn't really do anything with the testthat package**
* Is the Biobase dependency necessary? See note above. **Yes because of the flowCore dependency**
* Some package version dependencies are overkill. You can remove them for the
internal packages such as graphics, methods, stats, utils, and
grDevices because those are tied to the R version. **All Package version dependencies have been removed**
* Unless you are using a specific feature in that version of the package, you
don't need to specify the version number dependency. **All Package version dependencies have been removed**

## Vignette

* (optional) It is easier to review and maintain a vignette whose text is not
flowing off the side of the page. Keep the total column width to 80 characters. **Tried to do that in the new version. I am not sure I achieved it though**
* Avoid loading the tidyverse because it is not listed in the Suggests
field and the package loads a boatload of unnecessary dependencies for the
vignette. Consider only loading dplyr. **Done**

## R

* Set your default values to the intended value, e.g., when
proportion = NULL, the function changes it to proportion = 1. Why not have
1 as the default value? **Default value now 1**
* Avoid accessing elements of your class with the @ symbol. Create a formal
interface to your class. **The @ symbol was not really for my class objects. I have used interfaces everywhere in the package**
* Make sure that your logic makes sense, e.g., in R/debris_nc.R there is an
if else statement that appears to do the same thing in both conditions. **I could not find the block of code you were referring to, but I made some changes to this function**
* Isolate code differences within if else logic and only change the
parameter that changes, e.g., pks <- if (lp2 >= 2) min(pks) else pks in
R/debris_nc.R. This would reduce the number of lines of code and places
where you could have bugs / errors. **Done. Thank you for this observation.**
* There seems to be a typo in line 46 of R/good_measurement.R. It appears
that the code should be !is.null(mxd_cellpML). **Indeed. thank you again for this observation**
* I would recommend an alternative name to the exprs function and slot name
in your class because it is considered legacy code for extracting and storing
an ExpressionSet. **There is no exprs function in the package.  I merely used exprs function from **
* The tag Error does not need to be in your stop calls: see
stop("Error:") **Correctedd all occurrences of this. Thank for this observation**
* It will be confusing to the user to have two new_flowframe functions. Can
these be reduced to one? **This is a tough one. The two functions are somewhat different. I just happen to be bad at naming**
* Avoid using AnnotatedDataFrame and use S4Vectors::DataFrame. **This is more about flowCore dependency**
* Consider using a different name for your summary method because the
arguments do not match the S3 generic. Also, you're combining systems here
with S4 and S3 which may confuse users. **Changed this to summaries() which is entirely S4**
* Reduce cyclomatic complexity by simplifying these lines for checking inputs
in phyto_filter: **Done. Thank you for the suggestion**

Regards,
Daniel

**Comment by lshep** [comment]
If you have made changes and are ready for a re-review,  please remember to bump the version number and push to git.bioconductor.org to trigger a new build report.

**Comment by fomotis** [comment]
Hello @Ishep,

I already did that. I am yet to get another feedback on the current push.

Regards,
Daniel

**Comment by LiNk-NY** [comment]
Hi Daniel, @fomotis 
Sorry for the delay. I am not seeing the build report for the changes that you've made. Can you try again by bumping the version and pushing to the Bioc git repository? Thank you. 
I will have a quick look at the changes. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Daniel, @fomotis 

> * Make sure that your logic makes sense, e.g., in R/debris_nc.R there is an
>   if else statement that appears to do the same thing in both conditions. **I could not find the block of code you were referring to, but I made some changes to this function**

This looks the same in both conditions. It looks like it does not need to be in an `if else` block.
```r
    if(sum(ch_chlorophyll_peaks$P.h[ch_chlorophyll_peaks$Peaks >= 0] > ph)
       < lp) {

        ch_chlorophyll_peaks2 <- flowDensity::getPeaks(flowframe, 
                                                       ch_chlorophyll,
                                                       tinypeak.removal = ph)


    } else {

        ch_chlorophyll_peaks2 <- flowDensity::getPeaks(flowframe, 
                                                       ch_chlorophyll,
                                                       tinypeak.removal = ph)

    }
```

> * I would recommend an alternative name to the exprs function and slot name
>   in your class because it is considered legacy code for extracting and storing
>   an ExpressionSet. **There is no exprs function in the package.  I merely used exprs function from **

Thanks for the update. It looks like it is coming from `flowCore` which probably imports it from `Biobase`.

> * It will be confusing to the user to have two new_flowframe functions. Can
>   these be reduced to one? **This is a tough one. The two functions are somewhat different. I just happen to be bad at naming**

After a quick look, you should be able to combine them into one function because
they seem to be doing similar things.

Best,
Marcel

**Comment by fomotis** [comment]
Okay @LiNk-NY,

I will have a look at these and update things accordingly.

Regards,
Daniel

**Comment by LiNk-NY** [comment]
Hi Daniel, @fomotis 
Any updates?

**Comment by fomotis** [comment]
none yet. been having some baby troubles lately. Will work on the updates tonight

**Comment by fomotis** [comment]
Hello @LiNk-NY ,

I finally executed both changes.

Regards,
Daniel

**Comment by LiNk-NY** [comment]
Hi Daniel, @fomotis 
I hope all is well with you. Thanks for making those changes. 
Please remove the commented code when you get a chance.

Thank you for your submission to Bioconductor. 
Your package has been accepted. 

Best regards,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fomotis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cyanoFilter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cyanoFilter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
