### ISSUE TITLE
methylscaper

### ISSUE THREAD

**Issue by rhondabacher** [Bioconductor/Contributions#1921]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rhondabacher/methylscaper

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Please see comments below: 

**README**

- [ ] Include Bioconductor installation instrcutions

**NEWS.md**

- [ ] Formatted incorrectly. See `news?` and [Bioc news](http://bioconductor.org/developers/package-guidelines/#news)


**DESCRIPTION

- [ ] Remove `LazyData: true`. This rarely proves useful and can actually slow installation


**inst**

- [ ] You will also need an `inst/script` directory that contains files explaining how the files in `inst/extdata` were generated. This should include source information and any processing.  In can be code, sudo-code, or text.

**vignette**

- [ ] Please include Bioconductor installation instructions


**R code/man pages**

- [ ] Bioconductor likes to see interoperability with existing classes.  The SingleCellExperiment is widely used for Single cell data in Bioconductor. Can you adapt to also be able to accept a SingleCellExperiment object as input or do a wrapper around the standard Bioconductor object? 

- [ ] Similarly Genomic positions should be GenomicRanges not data.frames. 

- [ ] You should be able to filter also by GenomicRanges in additional to start and end position. 


Please address the above issues. When ready please do a version bump to trigger a new build report and comment back here with how the package was updated and that it is ready for a re-review.  

Cheers

**Comment by rhondabacher** [comment]
Hi, 

We've pushed a successful build incorporating all the comments below and are ready for a re-review. Thank you for your time and consideration.

Two things I'd like to note for the re-review:

1. For SingleCellExperiment, there are no existing packages that I found that use this structure for single cell methylation (yet). We have included a function that could accept and reformat an SCE and which can also be updated as needed at any time in the future.
2. For GenomicRanges, this was an excellent point to include this and I began rewriting as indicated. However, after testing we found it was significantly slower than data.table for our purposes. I've included the code comparison as an attachment
[bioc_submission_example.txt](https://github.com/Bioconductor/Contributions/files/6183637/bioc_submission_example.txt)

In summary we compared a simple range subset using subsetByOverlaps() which takes just under 2 seconds, however the same operation using data.table completes in less than 0.1 seconds. On the practical side, since users can make many positional adjustments that need to appear in the plot as fast as possible the speed difference is quite significant. We hope that you understand and it is OK to use data.table. We are not doing any extensive or complicated range calculations where I expect that GenomicRanges is the much better performer.

> Thank you for your submission to Bioconductor. Please see comments below:
> 
> **README**
> 
> * [X]  Include Bioconductor installation instrcutions
> 
> **NEWS.md**
> 
> * [X]  Formatted incorrectly. See `news?` and [Bioc news](http://bioconductor.org/developers/package-guidelines/#news)
> 
> **DESCRIPTION**
> 
> * [X]  Remove `LazyData: true`. This rarely proves useful and can actually slow installation
> 
> **inst**
> 
> * [X]  You will also need an `inst/script` directory that contains files explaining how the files in `inst/extdata` were generated. This should include source information and any processing.  In can be code, sudo-code, or text.
> 
> **vignette**
> 
> * [X]  Please include Bioconductor installation instructions
> 
> **R code/man pages**
> 
> * [X]  Bioconductor likes to see interoperability with existing classes.  The SingleCellExperiment is widely used for Single cell data in Bioconductor. Can you adapt to also be able to accept a SingleCellExperiment object as input or do a wrapper around the standard Bioconductor object?
> * [X]  Similarly Genomic positions should be GenomicRanges not data.frames.
> * [X]  You should be able to filter also by GenomicRanges in additional to start and end position.
> 
> Please address the above issues. When ready please do a version bump to trigger a new build report and comment back here with how the package was updated and that it is ready for a re-review.
> 
> Cheers

**Comment by lshep** [comment]
Thank you for making the changes.  Given the leg work and example you provided it is fine to keep as you have implemented.  Cheers.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rhondabacher.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("methylscaper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methylscaper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
