### ISSUE TITLE
MsBackendMassbank

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#1932]
- Repository: https://github.com/RforMassSpectrometry/MsBackendMassbank

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Hi @jorainer ,

These warnings on Windows are spurious so let's ignore them.

OTOH the `R CMD check` note on all platforms ("There are ::: calls to the package's namespace in its code.") seems real and should be easy to avoid.

My understanding is that the `.sql` suffix is generally used for text files containing SQL commands (e.g. SQL dumps), and that for an SQLite database (binary file) like `MsBackendMassbank/inst/sql/minimassbank.sql`, the `.sqlite` suffix is preferred.

Explicit use of the `/` separator in file paths should be avoided. For example `system.file("sql", "minimassbank.sql", package="MsBackendMassbank")` should be used instead of `system.file("sql/minimassbank.sql", package="MsBackendMassbank")`.

Unfortunately the `` `r file.info("MsBackendMassbank.Rmd")$mtime` `` trick to get the date of last modification is not reliable because `git clone` will reset the timestamp on the file to the date and time of the cloning. So this won't work as expected in the context of the build system.

Other than that, all looks good. 

H.

**Comment by jorainer** [comment]
Thanks @hpages for the fast review and the comments!

regarding the `:::`, I recently added them because we got errors on the Windows build machine complaining that it can not find a package-internal function. This happened in the function to read massbank files that we call in `bplapply`. I guess it has to do that on Windows SNOW-based parallel processing is used and maybe the package is not loaded? Anyway, I tried to fix it now by removing all `:::` and calling `requireNamespace` in that function... Let's see what the Windows build machine says... 

Thanks for the hint on the *sql* file ending. Sure, you're right. I changed that.

Thanks also for the suggestion on avoiding to use `/` in file paths! I changed that.

OK, thanks, I was not aware of that but it makes sense. I removed `r file.info(...)$mtime` now.

See also https://github.com/rformassspectrometry/MsBackendMassbank/commit/d4009cd68f46b9497fc115e6b9bd6954687e22e5 for a quick look at the changes.

thanks!

jo

**Comment by hpages** [comment]
Excellent. That was fast :-)

**Comment by jorainer** [comment]
Thanks for your fast review Herve!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsBackendMassbank")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsBackendMassbank

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
