### ISSUE TITLE
miloR submission

### ISSUE THREAD

**Issue by MikeDMorgan** [Bioconductor/Contributions#1934]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarioniLab/miloR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
Please correct all ERRORs, Warnings, and Notes from the build report before a more thorough review will take place.  Thank you

**Comment by MikeDMorgan** [comment]
Hi @lshep The only remaining warnings are related to this previous issue with Window R doc building: https://www.mail-archive.com/bioc-devel@r-project.org/msg13662.html

Is there a known fix, or does one have to wait until a fix has percolated through from R-devel?

**Comment by lshep** [comment]
You can ignore that warning as it is a known issue.  I'll try to have a formal review for you within the next few days.

**Comment by MikeDMorgan** [comment]
Thanks @lshep

**Comment by lshep** [comment]
Thank you for the submission. Please see initial review comments below: 

**Build report**

- [ ] Is the suggested imports valid?

```
Consider adding
  importFrom("grDevices", "colorRampPalette")
  importFrom("graphics", "layout")
```


- [ ] Please clean up BiocCheck description and coding practice NOTES. Others are fairly optional but we prefer these two paricular NOTE to be applied.


**General**

- [ ] Please do not include the _pkgdown.yml and codecov.yml in the branches submitted to Bioconductor. We suggest moving them to a different branch or at least doing .gitignore so they are not included in the cloned repository


**Description**

- [ ] If you keep the license file in the top level please add a license field to the description

- [ ] As you mention it in the readme consider adding a `BugReports` line pointing to `https://github.com/MarioniLab/miloR/issues

**License**

- [ ] As R is distributed with the GPL license there isn't a need to include it but if you do please add the appropriate line in the DESCRIPTION to remove the R CMD check NOTE.

**README**

- [ ] Please add Bioconductor installations instructions.


**vignettes**

- [X] This is an issue with my particular machine but it replicated by various OS systems that don't necessarily have transparency graphs supported. Nothing to be done but in case you get questions about it
```
Warning message:
In grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size) :
  semi-transparency is not supported on this device: reported only once per page
```


**R/man**

- [ ] We recommend a package help page so if people do `?miloR` something would appear even redirecting to vignette or other relevant function man pages.


- [ ] Really minor but you shouldn't need a `paste0` or `paste` in message/warning/error. It does `paste0` formatting automatically so you should be able to adjust the messages appropriately without explicitly calling.

When ready please do a version bump to get a new build report for the package and comment here addressing the above issues.  Cheers

**Comment by MikeDMorgan** [comment]
Hi @lshep I have now resolved all of the outstanding notes, with the exception of substituting `sapply` for `vapply` in the coding practise notes. Is this last one strictly necessary?

**Comment by lshep** [comment]
No you do not have to update.  I will re-review over the next few days.

**Comment by MikeDMorgan** [comment]
Thank you!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MikeDMorgan.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("miloR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/miloR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
