### ISSUE TITLE
CIMICE

### ISSUE THREAD

**Issue by redsnic** [Bioconductor/Contributions#1950]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/redsnic/CIMICE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by redsnic** [comment]
If useful,  some more information about the 
ideas behind CIMICE are available at [this link](https://github.com/redsnic/CIMICEpresentations).

I suggest looking at BITS2019.pdf.

**Comment by LiNk-NY** [comment]
Hi Nicolò, @redsnic 

Thank you for your submission. See below for the review. 
There are some concerns with Bioconductor ecosystem interoperability. 
Perhaps this package is best suited for CRAN as it does not
take advantage of the number of data representations already available
in Bioconductor.

Best,
Marcel

---

# CIMICE #1950

## DESCRIPTION

* Minor point but the person function perhaps should be
`person("Nicolò", "Rossi")`? The first two arguments correspond to the first
and last names (nome e cognome), respectively.
* The `biocViews` tags should follow the hierarchy as shown here:
http://bioconductor.org/packages/release/BiocViews.html#___Software
* I noticed that you are not using any Bioconductor packages. We have packages
for working with mutation data (e.g., `maftools` and `RaggedExperiment` among
others).
* Consider supporting `Matrix` and/or `HDF5Array` for large sparse matrices
especially in the single cell context where the data can be quite large.
* A binary `RangedSummarizedExperiment` could also work. 

## NAMESPACE

* Avoid using `.` delimiters in your functions. They indicate method dispatch
in the S3 system which can cause some confusion. It is advisable to use
snake_case since you are already using the tidyverse.

* Please respond to the interoperability concerns raised in the review before
we can continue.

**Comment by redsnic** [comment]
Thank you for your reply and suggestions.

I will consider the issues about interoperability and report as soon as possible.

**Comment by redsnic** [comment]
## Description

* The person function should be now used correctly
* please check if now the `biocViews` are in the correct order
* I have added an interface to create valid mutational matrix from MAF files through `maftools`. 
* Using sparse matrices is a good idea, but I think the advantages of using `dplyr` for preprocessing are higher. Also the dataset is reduced in size during the analysis as duplicated rows in the mutational matrix are represented only once. I don't think memory usage should be much of a concern. 

## Namespace

* I have changed all the functions names so that they are in snake_case. I also have removed the dependency from `plyr`.
* Let me know if you have other suggestions

Thank you again,
Nicolò

**Comment by LiNk-NY** [comment]
Hi Nicolò, @redsnic 

What are the advantages of using `dplyr` over other sparse matrix representations (`dg*Matrix`, `HDF5Matrix`, `SingleCellExperiment`, `TileDB`, etc.)? 
I think the advantages breakdown once you have large single cell data. If you can show that `dplyr` is suited
for large multi-Gb data then by all means use `dplyr`. One of the advantages of using `HDF5Array` is that
you don't have to load all the data into memory, it is an on-disk representation. 

Best,
Marcel

Best,
Marcel

**Comment by redsnic** [comment]
Hi Marcel @LiNk-NY 

The first advantage of using dplyr at the moment is that it is very well suited to easily implement the majority of the 
preprocessing I do on the mutational matrix. Also I find dplyr code quite clean and easy to be understood.

In any case, dplyr offer a syntax that is inherited by dbplyr, another pakage
that is meant to manage data on a DB as if it was in a dataframe. I have used dbplyr to make a package to manage very large GDC MAF files from the TCGA-BRCA project and it works very well in that case. 

I want to take a closer look to HDF5Array, but I have concerns on the impact of such a change on the 
algorithm I have implemented and the code I have written. 
I feel that the advantages could be limited to the initial preprocessing phase (when I count the number of cells sharing the same genotype), and so on the same level of a dbplyr implementation.

Of course, by now I am not using dbplyr so everything is loaded on RAM. Importing data from huge MAF files would again require a way to manipulate this kind of files from disk, as far as I know, such a feature is not availabe in maftools.

Let me know if you have other suggestions or comments and thank you again,
Nicolò Rossi

**Comment by redsnic** [comment]
Hello Marcel @LiNk-NY 

Finally, I have decided to switch to an implementation based on sparse matrices.

Are you aware if `maftools` also permits the construction of a sparse mutational matrices directly, avoiding the 
construction of a dense one?

Thank you,
Nicolò Rossi

**Comment by LiNk-NY** [comment]
Hi Nicolò, @redsnic 

Thank you for making that change. I will take a second look at the package shortly. 

> Are you aware if `maftools` also permits the construction of a sparse mutational matrix directly from a MAF file but avoiding the creation of a dense matrix beforehand?

This is a good question for Anand (tagging @PoisonAlien). 

Thanks!
-Marcel

**Comment by LiNk-NY** [comment]
Hi Nicolò, @redsnic 

The changes look good. I would highly recommend that you use `rowSums` and `colSums` over `apply(x, 1, sum)` operations because these are optimized for matrices and even Matrices.
PS. There are faster ways of doing `ifelse(.>0, 1, 0)` (e.g., `as.numeric(x > 0)`). 
Your package is ready to be accepted. 

Best regards,
Marcel

**Comment by PoisonAlien** [comment]
Hi Nicolò and Marcel,

Unfortunately `maftools` does not support space matrices :|

FWIW, I have tested `maftools` on a cohort of >2000 samples with over 10K genes and had no issues with memory (on a decent computer with 16G RAM). I have not worked single-cell DNA-seq so can't really comment on the matrix size, but it should be fine even with up to 5K (probably even more) cells. (maybe downstream functions are memory hungry?)

All the best.

**Comment by redsnic** [comment]
Thank you again for your replies Marcel @LiNk-NY and Anand @PoisonAlien.

I have followed your performance tips and modified the code accordingly.

In the case of my package, importing a MAF file in RAM would be the most memory expensive activity, as I then operate only 
on the mutCount matrix. If I really happen to have memory problems, I can just create the mutational matrix myself reading the MAF file in small chunks.

@PoisonAlien, does `maftools` implement some strategies to speed up selection of MAF rows? For example to 
extract the rows related to a specific gene from the file?

@LiNk-NY, please, let me know if there is anything more I should do before the package is accepted.

Have you both a nice day,
Nicolò Rossi

**Comment by LiNk-NY** [comment]
Hi Nicolò, @redsnic 

As far as I know, you'd still have to load the matrix into memory despite reading in small chunks. 
The advantage of HDF5 is that you can have on-disk representation of the sparse matrix.
Perhaps the matrices aren't very large so it shouldn't be a problem but it is good to keep in
mind. 

Thanks for making those changes. I will accept your package. 

Best,
Marcel

**Comment by redsnic** [comment]
Hi Marcel @LiNk-NY,

Thank you for accepting my pakage, I am well aware of what you said. In my previous comment I just wanted to say that the sparse matrix should be quite smaller than the MAF file that originated it, as that format carries much more information.

Regards,
Nicoló Rossi

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/redsnic.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CIMICE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CIMICE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by PoisonAlien** [comment]
I apologize in advance for replying to a closed issue. 

@redsnic `maftools` has no such option for selecting specific rows. But it internally uses `data.table::fred()` which can accept system commands as input. If you wish to bypass `maftools` and write your own import function, you could use `grep` to selectively read rows with genes of interest.

```r
m_file = system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
cmd_txt = paste0("zcat < ",m_file, " | grep DNMT3A") #Select only rows with DNMT3A 

res = data.table::fread(cmd = cmd_txt)
> res[1:5, 1:10]
       V1   V2               V3 V4 V5       V6       V7 V8                V9 V10
1: DNMT3A 1788 genome.wustl.edu 37  2 25457243 25457243  + Missense_Mutation SNP
2: DNMT3A 1788 genome.wustl.edu 37  2 25457242 25457242  + Missense_Mutation SNP
3: DNMT3A 1788 genome.wustl.edu 37  2 25457243 25457243  + Missense_Mutation SNP
4: DNMT3A 1788 genome.wustl.edu 37  2 25459874 25459874  +       Splice_Site SNP
5: DNMT3A 1788 genome.wustl.edu 37  2 25467208 25467208  +       Splice_Site SNP
```

However, I am not sure how well this translates to Windows (especially piping). Hope this helps.
