### ISSUE TITLE
STROMA4

### ISSUE THREAD

**Issue by smisaleh** [Bioconductor/Contributions#196]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/smisaleh/STROMA4

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hpages** [comment]
Hi Sadiq,

Thanks for submitting the STROMA4 package.

Please address the 2 following issues:

1. The PDF of the vignette (Stroma4-vignette.pdf) doesn't belong to the git tree. Please rermove it.

2. Please improve/expand the documentation. Right now I can't figure out how to use `assign.properties()` (the only function in the package) on a different data set than the one used in the man page and vignette because those are too minimalist. For example how would I use it on the `ALL` data set from the ALL package? Or is the function aimed to be used on some specific data sets only? Please provide some details. Also the man page needs to explain how to set the `geneID.column` and `genelists` argument. The vignette should provide more context about what exactly the package is trying to achieve and at least some brief interpretation/comment/discussion of the output.

Thanks,
H.

**Comment by hpages** [comment]
Hi Sadiq,

Just wanted to check with you about the status of your submission. Are you planning to follow-up?

Thanks,
H.

**Comment by smisaleh** [comment]
Sorry, some personal issues prevented me from attending to these comments
earlier. I am in the process of following up at the moment.

Thanks for the follow up.

Sadiq

**Comment by smisaleh** [comment]
I would just like to follow up as it has been a month since I last received an update. Please let me know if there is anything additional that I need to do.

**Comment by mtmorgan** [comment]
Thanks and sorry for the delay.

## Other

Consider the following optional, since they were not included in the original review.

DESCRIPTION

- Expand the Description: field to read more like a paper abstract with enough information that a user could figure out whether the package is helpful to them. Minimally, provide enough information on what 'TNBC' and 'stromal properties' are.

- Consider more precise [biocViews][] terms; those that you suggest are very general and unlikely to help users decide on the suitability / relevance of your package.

- Use only Authors@R field; the Authors: and Maintainer: fields are generated from this when the package is built.

- The License: is GPL, but it is better to opt for a particular variant rather than commiting yourself to licenses named GPL that may not yet exist. E.g., GPL-3

Vignette

- The first paragraph would be an excellent place to define stroma and Lehman properties, and to provide a brief motivation for when and why one would want to have them assigned.

- In your vignette, please change `biocLite("Stroma4")` to match the name of the package `biocLite("STROMA4")`.

R

- Use `message()` rather than `cat()` for progress / verbose options.

- Avoid 'copy-and-append' variable creation, using 'pre-allocate and fill' instead, see [efficient code][] guidelines. For instance, in assign.property.R:58-:

        ret <- list()
        for (i in names(temp.envir)) {
            ...
            ret[[i]] <- "Error: No matching genes in expression matrix"
            
  is 'copy-and-append', and should be replaced with
  
        ret <- vector("list", length(temp.envir))
        for (i in names(temp.envir))
            ...
            ret[[i]] <- ...
            
  The `cbind(datrank, i)` in random.ranks.R:40 looks like a similar issue; instead, allocate a final column and update it `datrank[[last]] = i`.
  
- Avoid `1:n` in favor of `seq_len(n)` or `1:length(x)` in favor of `seq_along(x)`.

- Consider using [BiocParallel][] for parallel evaluation, so that Bioconductor users have a consistent user experience.

- Using a system call to 'renice' in random.ranks.R:36 obviously fails on Windows and makes your package OS-specific.

- The calculation at random.ranks.R:39 doesn't look that 'heavy' -- is it really necessary to use parallel evaluation? Maybe `matrixStats::row/colRanks()` provides adequate performance.

man

- The return value of assign.properties is a list of numeric vectors, but should instead be a data.frame of factors

        df <- as.data.frame(Map(factor, all.properties, 
            MoreArgs=list(labels=c("low", "intermediate", "high"))))

  The dimensions imply that these are associated with each sample, so why not return an expression set, cbind()ing this to pData
  
        pData(ESet) <- cbind(pData(ESet), df)

[biocViews]: http://bioconductor.org/packages/devel/BiocViews.html#___Software
[efficient code]: http://bioconductor.org/developers/how-to/efficient-code/
[BiocParallel]: https://bioconductor.org/packages/BiocParallel

**Comment by smisaleh** [comment]
Thank you, I will work on this and push an update soon.

**Comment by mtmorgan** [comment]
It looks like the major points of the review have been addressed. I will accepted this package and add it to the Bioconductor svn and nightly builds. More information via email in a few days.
