### ISSUE TITLE
ppcseq

### ISSUE THREAD

**Issue by stemangiola** [Bioconductor/Contributions#1985]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stemangiola/ppcseq

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by stemangiola** [comment]
Hello,

@Kayla-Morrell  thanks for reviewing my package.

All tests pass except windows, with


```
dependencies 'rstantools', 'tidybayes' are not available for package 'ppcseq'
```

Is it a problem on the server side?

**Comment by Kayla-Morrell** [comment]
@stemangiola - Thanks for pointing out this issue. I'll check with the team and see if there is something that needs to be done on our end to get this issues resolved. In the mean time I can start the initial review since the package builds cleanly on the other builders. I should have the review posted within the next few days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@stemangiola - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: Found the following hidden files and directories, 
        .travis.yml
        .github

## DESCRIPTION

- [ ] SUGGESTION: The Description field in DESCRIPTION is made up by less than
  3 sentences. Please consider expanding this field and structure it as a full
paragraph.

- [ ] REQUIRED: 'LazyData' should be set to 'false'. It is our experience that
  when this field is set to 'true' it can slow down the loading of the package,
especially if it include data.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' filed which
  includes a relevant link to GitHub for reporting Issues.

- [ ] REQUIRED: Unless you use actual functionality from `testthat` in your R
  code, it should be listed under 'Suggests:'.

## NAMESPACE

- [ ] REQUIRED: Undefined global functions or variables. Add to your NAMESPACE 
file.
        importFrom("base", "row", "sample")
        importFrom("graphics", "par")
        importFrom("stats", "sd")
        importFrom("utils", "data", "head", "packageVersion", "tail")

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.

## CITATION

- [ ] REQUIRED: It seems that the CITATION file is not formatted correctly. As
  stated in our documentation here,
https://bioconductor.org/developers/package-guidelines/#citation you should
check our CITATION file to be sure it is formatted properly.

## Vignette

- [ ] REQUIRED: I see that you are using `BiocStyle` for the formatting of the
  vignette (this should be listed under 'Suggests:' in the DESCRIPTION file) but
when I render the vignette it doesn't apper in this format. I think you need
change line 11 to be `%\VignetteEngine{knitr::rmarkdown}` and then add
`rmarkdown` to the 'Suggests:' in the DESCRIPTION file.

- [ ] REQUIRED: Line 2, the title needs to be changed.

- [ ] REQUIRED: Line 5, the package needs to be changed.

- [ ] REQUIRED: Line 9, the bibliography needs to be changed (or removed).

- [ ] REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the objective, models, unique functions, key points, etc
that distinguish the package from other packages of similar type.

- [ ] REQUIRED: Lines 26-30 seem unnecessary since these packages will get
  loaded when `ppcseq` does. I would move the `library(ppcseq)` call to after
you show how to install it and be sure to remove the `include = FALSE` so the
user knows to load the package.

- [ ] REQUIRED: At line 35, I would give more detail about what "exploit
  multi-threading" means. It seems that the vignette examples run fine without
this being set so what is the benefit of doing so?

- [ ] REQUIRED: For the installation you should be demonstrating for the user
  how to install/load the package from Bioconductor and not GitHub. The code
should look something like the following and include `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ppcseq")
```

- [ ] SUGGESTION: We suggest the use of table of contents, which I see you have
  set to true at line 8. But the table of contents doesn't actually populate
because you don't have any rmarkdown sections to your vignette.

## Man pages

- [ ] REQUIRED: 'figures/' is not an acceptable directory in this location. It
  doesn't seem like these figures are used anywhere, but if they are needed in
the package they should be moved to an 'inst/figures/' directory.

- [ ] REQUIRED: If you are going to include a package man page, please be sure
  there is relevant information within it.

- [ ] REQUIRED: In identify_outliers.Rd, unknown macro '\lifecycle'.

## R code

- [ ] REQUIRED: Clarify how 107 object(s) are initialized. Maybe they are part 
of a data set loaded with data(), or perhaps part of an object referenced in 
with() or within(). Some should be cleared up by adding the `importFrom()`'s
that were required up in the NAMESPACE section. 

- [ ] REQUIRED: Avoid sapply(); instead use vapply() if possible.

- [ ] REQUIRED: Avoid 1:...; instead use seq_len() or seq_along().

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 153 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There are 1482 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 64 lines that are not.

Best,
Kayla

**Comment by stemangiola** [comment]
> 
> 
> @stemangiola - Thank you for submitting to _Bioconductor_. Please see the initial review of
> the package below. The required changes must be made while the suggested
> changes do not have to be (though we strongly encourage them). Comment back
> here with updates that have been made and when the package is ready for a
> re-review.
> ## General package development
> 
>     * [ x]  REQUIRED: Found the following hidden files and directories,
>       .travis.yml
>       .github
> 
>> Added to .Rbuildignore
> 
> ## DESCRIPTION
> 
>     * [ x]  SUGGESTION: The Description field in DESCRIPTION is made up by less than
>       3 sentences. Please consider expanding this field and structure it as a full
>       paragraph.
> 
>     * [x ]  REQUIRED: 'LazyData' should be set to 'false'. It is our experience that
>       when this field is set to 'true' it can slow down the loading of the package,
>       especially if it include data.
> 
>     * [ x]  SUGGESTION: It is encouraged to include the 'BugReports:' filed which
>       includes a relevant link to GitHub for reporting Issues.
> 
>     * [x ]  REQUIRED: Unless you use actual functionality from `testthat` in your R
>       code, it should be listed under 'Suggests:'.
> 
> 
> ## NAMESPACE
> 
>     * [x ]  REQUIRED: Undefined global functions or variables. Add to your NAMESPACE
>       file.
>       importFrom("base", "row", "sample") >> row ->  I don't see where I use it
>       importFrom("graphics", "par")  >> I don't see where I use it
>       importFrom("stats", "sd") >> I have it already
>       importFrom("utils", "data", "head", "packageVersion", "tail")  >> data ->  I don't see where I use it
> 
> 
> ## NEWS
> 
>     * [ ]  SUGGESTION: Consider adding a NEWS file, so your package news will be
>       included in Bioconductor release announcements.
> 
> 
> ## CITATION
> 
>     * [x ]  REQUIRED: It seems that the CITATION file is not formatted correctly. As
>       stated in our documentation here,
>       https://bioconductor.org/developers/package-guidelines/#citation you should
>       check our CITATION file to be sure it is formatted properly.
> 
> 
> ## Vignette
> 
>     * [ x]  REQUIRED: I see that you are using `BiocStyle` for the formatting of the
>       vignette (this should be listed under 'Suggests:' in the DESCRIPTION file) but
>       when I render the vignette it doesn't apper in this format. I think you need
>       change line 11 to be `%\VignetteEngine{knitr::rmarkdown}` and then add
>       `rmarkdown` to the 'Suggests:' in the DESCRIPTION file.
> 
>     * [x ]  REQUIRED: Line 2, the title needs to be changed.
> 
>     * [ x]  REQUIRED: Line 5, the package needs to be changed.
> 
>     * [ x]  REQUIRED: Line 9, the bibliography needs to be changed (or removed).
> 
>     * [ x]  REQUIRED: There should be an 'Introduction' section that serves as an
>       abstract to introduce the objective, models, unique functions, key points, etc
>       that distinguish the package from other packages of similar type.
> 
>     * [x ]  REQUIRED: Lines 26-30 seem unnecessary since these packages will get
>       loaded when `ppcseq` does. I would move the `library(ppcseq)` call to after
>       you show how to install it and be sure to remove the `include = FALSE` so the
>       user knows to load the package.
> 
>     * [ ]  REQUIRED: At line 35, I would give more detail about what "exploit
>       multi-threading" means. It seems that the vignette examples run fine without
>       this being set so what is the benefit of doing so?
> 
>     * [x ]  REQUIRED: For the installation you should be demonstrating for the user
>       how to install/load the package from Bioconductor and not GitHub. The code
>       should look something like the following and include `eval = FALSE`.
> 
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("ppcseq")
> ```
> 
>     * [ ]  SUGGESTION: We suggest the use of table of contents, which I see you have
>       set to true at line 8. But the table of contents doesn't actually populate
>       because you don't have any rmarkdown sections to your vignette.
> 
> 
> ## Man pages
> 
>     * [ ]  REQUIRED: 'figures/' is not an acceptable directory in this location. It
>       doesn't seem like these figures are used anywhere, but if they are needed in
>       the package they should be moved to an 'inst/figures/' directory.
>
>> We had this issue before. The location is standard for CRAN, and figures are needed for README.md file
>> https://stat.ethz.ch/pipermail/r-package-devel/2017q3/001862.html
> 
>     * [x]  REQUIRED: If you are going to include a package man page, please be sure
>       there is relevant information within it.
> 
>     * [ ]  REQUIRED: In identify_outliers.Rd, unknown macro '\lifecycle'.
> 
>> I am not sure why. I have RdMacros: lifecycle
> 
> ## R code
> 
>     * [ ]  REQUIRED: Clarify how 107 object(s) are initialized. Maybe they are part
>       of a data set loaded with data(), or perhaps part of an object referenced in
>       with() or within(). Some should be cleared up by adding the `importFrom()`'s
>       that were required up in the NAMESPACE section.
> 
>     * [x ]  REQUIRED: Avoid sapply(); instead use vapply() if possible.
> 
>     * [x ]  REQUIRED: Avoid 1:...; instead use seq_len() or seq_along().
> 
>     * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 153
>       lines that are > 80 characters long.
> 
>     * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
>       There are 1482 lines that contain tabs.
> 
>     * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>       line indents. There are 64 lines that are not.
> 
> 
> Best,
> Kayla

**Comment by stemangiola** [comment]
Thanks @Kayla-Morrell  I have complied or replied (to all REQUIRED and some SUGGESTION)

**Comment by stemangiola** [comment]
Hello @Kayla-Morrell I have reviewed your comments, and the build succeeded except for Windows.

**Comment by stemangiola** [comment]
Hello @Kayla-Morrell I have now just one (I guess) "false positive warning".

```
* building 'ppcseq_0.99.18.tar.gz'
Warning: file 'ppcseq/configure' did not have execute permissions: corrected
```

**Comment by Kayla-Morrell** [comment]
@stemangiola - I've looked over the changes you've made and things look fine. The TIMEOUT on mac will need to be resolved though in order for me to accept the package.

**Comment by stemangiola** [comment]
Hello @Kayla-Morrell I have fixed the timeout.

**Comment by stemangiola** [comment]
Where can I find the Bioconductor nightly builds?

**Comment by PeteHaitch** [comment]
https://www.bioconductor.org/checkResults/

**Comment by stemangiola** [comment]
> 
> 
> https://www.bioconductor.org/checkResults/

Thanks Pete!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stemangiola.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ppcseq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ppcseq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
