### ISSUE TITLE
mia

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/Contributions#1987]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/microbiome/mia

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by FelixErnst** [comment]
AdditionalPackage: https://github.com/microbiome/miaViz

**Comment by FelixErnst** [comment]
@hpages the remaining error is limited to the Windows builder due to the unavailable experimental data package.

**Comment by FelixErnst** [comment]
@hpages the remaining warning is due to the names of the help pages containing the `<` character.

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 

I think it is safe to ignore those help page warnings on Windows. 
IIRC, they're products of the way the package is built and checked on Windows. 
I've looked at the package and posted the review below. 
Thanks.

Best,
Marcel

---

# mia #1987

* Consider separating analysis and plotting functions into separate packages to
make mia more lightweight.

## DESCRIPTION

* Looks good.

## NAMESPACE

* It may be more appropriate to have the conversion functions in
`TreeSummarizedExperiment` (the package where the class resides)
* I don't think the conversion
`exportMethods(makePhyloseqFromTreeSummarizedExperiment)` should be a method.
It can be a plain function or an `as` function. This is best done in the
`TreeSummarizedExeriment` package though.
* Consider removing dependencies on packages where you import only one or two
functions (e.g., 'yaml', 'rlang', 'stringr').

## vignettes

* Add an installation section to the vignette modeled after the Bioconductor
installation instructions on package landing pages.
* Add a package argument to `data(GlobalPatterns, package = "mia")`
to make it clear that this is coming from the package and not `phyloseq`.
Also, consider changing the name so that the names don't collide between
packages.

## R

* Avoid if possible creating methods for classes that you do not own (e.g.,
`meltAssay` on `SummarizedExperiment`). Perhaps these methods can be
implemented in `TreeSummarizedExperiment`? It also makes assumptions on the
data which are likely more apt for `TreeSummarizedExperiment`.

## tests

* Looks good.

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY,

thanks for the quick review.

I have a few questions:

## NAMESPACE
The conversion functions are a tricky business. We choose to implement the as functions in `mia` due to the following reasons:
- We didn't want to make the stack for `TSE` more complicated by introducing packages from specific areas of research. `TSE` is currently quite field agnositic from the implementation point of view. Thats why we didn't approch Ruizhu regarding these functions
- We use functions because conversion using `as` does not work in all cases and we would need to import specific packages increasing the dependency tree further. Currently the packages required reside in Suggests.
Can you comment on these specific aspects?

## R
- I cannot find another function called `meltAssay`. I used Mike's code search tool. Can you elaborate on this?

Thanks for any additional info!

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY,

summary of the changes pushed to Bioconductor's git/SPB:
- moved plotting functions to `miaViz`
- Moved packages to Suggests where possible/reasonable: 'yaml', 'stringr'. ('rlang' was not moved to Suggests, since it would be still in the Imports via `dplyr`)
- added install section to vignette(s)
- set package argument explicitly for all call to `data` in the vignette(s)

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 

> * We didn't want to make the stack for `TSE` more complicated by introducing packages from specific areas of research. `TSE` is currently quite field agnositic from the implementation point of view. Thats why we didn't approch Ruizhu regarding these functions

In general, the package that owns the data class should provide these conversion functions (see `HDF5Array` as an example). If the 'specific area of research' is much more different than the original class implementation, then it may be better to create a more specialized class in another package where you could then host these conversion functions. 

> * We use functions because conversion using `as` does not work in all cases and we would need to import specific packages increasing the dependency tree further. Currently the packages required reside in Suggests.

That is the cost of providing `setAs` methods. Perhaps `mia` can focus on the analysis and you could have another package that focuses on the infrastructure. These two aspects seem to be combined into one package.

> * I cannot find another function called `meltAssay`. I used Mike's code search tool. Can you elaborate on this?

You've created a method (`meltAssay`) for `SummarizedExperiment` which is not your own class. This can certainly be done but your method implementation is inconsistent with all `SummarizedExperiment` classes. It is better to create a derivative class that ensures the structure and names that you are looking for (with validity checks) and add provide that method. You can also create a plain function that errors when the name checking fails. 

Best,
Marcel

**Comment by FelixErnst** [comment]
Hi Marcel, @LiNk-NY 

Points 1. and 2. were originally addressed in a package called `MicrobiomeExperiment` implementing said specialized `SE` classed. We asked early on about this and basically the feedback was "Not yet another SE" (See slack and fionarhuang/TreeSummarizedExperiment#43). Because of this we put the referenceSeq slot in `TSE` and the conversion functions in `mia`. We can set up another package for the conversion functions only, but the required functionality of a `SE` class is provided by `TSE`. So I am stuck with the mixed messages now. Any idea how to resolve this?

Regarding 3.: I am not following. The function works with any `SE` since the data is accessed only via `rowData`, `colData`, `rownames`, `colnames` and `assay`. These are the default accessors and I don't see any inconsistancy there. Did I overlook something or do you have specific code part in mind?`
We also don't require any names in the `SE` to be present (except for the parts which the user selects) and just make sure, that if a clash is detected for `FeatureID` in `rowData` or `SampleID` in `colData`, which is then solved in a way that no data is lost.

The most straight forward way is to drop the conversion functions and `meltAssay` from `mia`, if that is required to move forward.

Best,
Felix

**Comment by LiNk-NY** [comment]
> Points 1. and 2. were originally addressed in a package called `MicrobiomeExperiment` implementing said specialized `SE` classed. We asked early on about this and basically the feedback was "Not yet another SE" (See slack and [fionarhuang/TreeSummarizedExperiment#43](https://github.com/fionarhuang/TreeSummarizedExperiment/pull/43)). Because of this we put the referenceSeq slot in `TSE` and the conversion functions in `mia`. We can set up another package for the conversion functions only, but the required functionality of a `SE` class is provided by `TSE`. So I am stuck with the mixed messages now. Any idea how to resolve this?
> 

I don't think the argument "Not yet another SE" holds when you're working with microbiome data especially when Bioconductor does not have a core data structure for working with this data. `TreeSummarizedExperiment` my provide some functionality and adding `referenceSeq` seems to show that the functionality was lacking; therefore, pointing to a need of a more particular class dedicated to microbiome data. Similar to how `SpatialExperiment` > `SingleCellExperiment` builds off of `SummarizedExperiment` for single cell and spatial data. If these conversion functions do not fit squarely with the purpose of `TreeSummarizedExperiment` then it speaks to a more bespoke class for microbiome data representation. 

> Regarding 3.: I am not following. The function works with any `SE` since the data is accessed only via `rowData`, `colData`, `rownames`, `colnames` and `assay`. These are the default accessors and I don't see any inconsistancy there. Did I overlook something or do you have specific code part in mind?
> We also don't require any special names in the `SE` to be present (except for the parts which the user selects) and just make sure, that if a clash is detected for `FeatureID` in `rowData` or `SampleID` in `colData`, it is then solved in a way that no data is lost.

This is best implemented as a plain function rather than a method because the code makes assumptions that will not work for **all** `SummarizedExperiment` objects (e.g., `.check_abund_values` abundance values are not always "Counts" assays). 
You are also making assumptions on the names: 

```r
MIA_MELT_ROW_NAME <- "FeatureID"
MIA_MELT_COL_NAME <- "SampleID"
```

These could be best handled by a dedicated function called `meltAssay` (if you'd like) with the arguments `sampleId = "SampleID", featureId = "FeatureID"`, etc.

Best regards,
Marcel

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY ,

I see your point on the first issue, but I still don't know, what you would like use to change.

I feel the discussion we are having is heading into is of a type "Should the purpose of the class be in the name of the class?". For us the answer was no and still is no. For the purpose of `mia`, `TSE` is the right class. If you want, I can spawn another `SE` called `MicrobiomeExperiment` and put all the conversion stuff into a new package. 

The implementation would be rather short:
```r
setClass("MicrobiomeExperiment",contains="TreeSummarizedExperiment")
```
Is this what I should do? @hpages 

(And to reiterate: I asked long before the submission on input on how this should be handled because I knew it could bite use. What is the lesson learned here? Asking during the submission is the right thing to do, because other options are waste of time?)

Regarding the second point, I disagree. I think it works with every `SE` out there. If you think otherwise, please provide me with a reproducable example or point me in the direction of the offending code. We also would like to mention, that we want to extend the function for `TSE` in the future. An implementation via an S4 method, is in my mind quite helpful, since with the current implementation, the defaults of an `SE` are covered and `TSE` specific data can be added with another method. 

As clarification: `.check_abund_values` just makes sure, that the `assay` the user has selected actually does exist. Should I rename the function into `.check_assay_present`, so that there is no misunderstanding? (Done that now anyway)

As suggested I made the names a users choice.

Best,
Felix

**Comment by FelixErnst** [comment]
> ```r
> MIA_MELT_ROW_NAME <- "FeatureID"
> MIA_MELT_COL_NAME <- "SampleID"
> ```

Just for clarification: These were hard-coded defaults, not assumptions.

**Comment by FelixErnst** [comment]
Hi Marcel @LiNk-NY,

thanks for the clarifications

> I don't think that is the right question. It is not simply a name change. The data container should agree with the assumptions that you are making on the data. If TSE, works well enough for you then don't change it though there is evidence that you had to make some adjustments for the different data. Had you not had the cooperation of the TSE maintainer, a new container would have likely spawned from it. 

That is actually true. However, we thought about Bioconductor as a whole and what would be better for the exiting class system. We were unsure and we asked around and the feedback was the "NYASE" statement mentioned above.

> My recommendation was that if you are providing conversion functions, those functions should live closest to the package that provides the class.

I would agree with that, if there weren't at least three file formats and one R format available for microbiome data, which are all slightly different.

> ```r
> library(SummarizedExpeirment)
> example(SummarizedExperiment)
> > meltAssay(rse)
> Error: Can't subset columns that don't exist.
> ✖ Column `FeatureID_row` doesn't exist.
> ```
> 
> Hard-coded values are assumptions.

That was actually a bug fixed in `0.99.7`

Best
Felix

PS: The SPB error are not consistent right now

**Comment by hpages** [comment]
Hi Felix @FelixErnst ,

Have you looked at `tidySummarizedExperiment::as_tibble()`? Isn't it kind of similar to what you are trying to achieve with `meltAssay()`?

Thanks,
H.

**Comment by FelixErnst** [comment]
Hi Herve @hpages 

maybe. I wasn't aware of it. I will have a look at it. Thanks for the tip!

**Comment by FelixErnst** [comment]
Hi Marcel, Hi Herve, @LiNk-NY @hpages 

I had a look at the the `tidySummarizedExperiment` package and in particular its `melt` functionality via `as_tibble`. It has some limitations for what we have in mind (no opt-in/opt-out for data from rowData, colData and assays which leads to potential problems with larger objects) and also experiences some inconsistencies with naming of the output columns. I opened a feature request on the GitHub repo (see link above). When these issues are addressed, we could drop `meltAssay`. For now we would like to keep it.

Can the review move forward, despite the errors on SPB?

Felix

**Comment by LiNk-NY** [comment]
Hi Felix, @FelixErnst 

Thanks for making these changes:

```
git diff 7774069..1c5fa8e
```

This looks good to me. The other points raised are issues to work on over the long term. 
Thank you for your contribution. 

Best regards,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mia")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mia

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FelixErnst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("miaViz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/miaViz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
