### ISSUE TITLE
karyoploteR

### ISSUE THREAD

**Issue by bernatgel** [Bioconductor/Contributions#199]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bernatgel/karyoploteR

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by bernatgel** [comment]
Hi,

I'm receiving Warning from BiocCheck about the version number. It is currently 0.99.1 which I think is correct for devel, but the message complains about the release version: 

Checking version number validity...
    * WARNING: y of x.y.z version should be even in release

Should I change anything? Why  is it thinking I'm on release?

Thanks

Bernat

**Comment by mtmorgan** [comment]
No, don't change anything. The single package builder is lagging behind and will be updated shortly.

**Comment by lawremi** [comment]
Uses `methods::hasArg()` instead of `missing()`, which is generally not good practice, in my opinion, when the argument is in the formals. missing() asserts that the argument is actually in the formals, catching any misspellings, while `hasArg()` will happily return `FALSE`. Also, `missing()` is just the convention. Strangely, besides `hasArg()` and `is()`, this package does not make use of the methods package. One might presume generics would be useful for plotting different data structures in different ways.

Uses `regioneR::toGRanges()` to coerce things to GRanges, which has some problems. First, it's not extensible, while we already have an extensible coercion mechanism: `as(x, "GRanges")`. Second, if coercion fails, `toGRanges()` just returns its input, which is something other than a GRanges. Third, `toGRanges()` is just too vague, i.e., it does too many different things with one name. Sometimes, it coerces, other times it imports, etc. Fourth,  the data.frame coercion is inconsistent with `makeGRangesFromDataFrame()`. Shouldn't we just have one convention for that? Fifth, can't the user just call `import()` when reading a file? Is it worth trying to support reading of arbitrary "txt" and "csv" files when manual intervention is likely needed?

Maybe this could make use of biovizBase?

**Comment by bernatgel** [comment]
Hi @lawremi,

Thanks for the quick review and the reasoned proposed changes.

I've changed methods::hasArg() for missing(), but I don't know why you find it strange that only hasArg() and is() is used from the methods package.

Although not as well defined as the standard coercion methods I think toGRanges() might be more convenient for the user in some cases. In any case, I have removed it from the code and it's only used in some of the examples and the vignette for convenience. Is it ok?

I've also changed two other functions (getCytobands and getCytobandColors) to make use of the biovizBase package, although for the colors I've left the old color scheme (obtained from circos) since I find it cleaner.

Do you think I should change anything else?

Thanks

Bernat

**Comment by bernatgel** [comment]
Hi, 
I understand that the deep review needed for inclusion in Bioconductor takes time. This is just to check that the version number warning triggered by the last build is not preventing the start of the review and that you are not expecting anything from me at this moment.

Thanks

Bernat

**Comment by mtmorgan** [comment]
Sorry for the delay; I will process you package by Monday.

**Comment by bernatgel** [comment]
Sure, no worries! I was just checking if you were expecting something from my part.

Thanks

**Comment by mtmorgan** [comment]
This package looks like it's in very good shape. I have the following minor comments.

## R

1. This is a bit of a tricky issue, but 'top-level' code such as this

```
getCytobands <- memoise::memoise(function(genome="hg19", use.cache=TRUE) {
```

is evaluated when the package is installed. This can cause problems
because the underlying package (memoise) might be updated without
triggering an update of karyoplotteR, and then the code in
karyoplotteR references code that no longer exists in memoise.. A
better strategy is to ensure that the code is evaluated at run-time,
maybe along the lines of

```
.getCytobands <- function(genome="hg19", use.cache=TRUE) {
...
}


## e.g., in file R/zzz.R
getCytobands <- NULL

.onLoad <- function(libname, pkgname) {
    getCytobands <<- memoise::memoise(.getCytobands)
}
```

2. It is not usually necessary to write `message(paste0(...))`;
`message()` already knows how to paste together it's arguments.

3. While strictly an aesthetic issue, code (including documentation) is
much more readable when wrapped to no wider than 80 characters.

**Comment by lawremi** [comment]
About `getCytobands()`, it looks like the function will break if `use.cache=TRUE`, because the definition of `data.cache` has been commented out. Or am I missing something? It would seem that someone should make a data package with cytoband information for every organism in UCSC. Or, if we're going to memoize, that should happen in `biovizBase::getIdeogram()`, which is obviously a mess. Or maybe better, rtracklayer should take advantage of HTTP caching via restfulr. Or maybe AnnotationHub is a solution?

**Comment by bernatgel** [comment]
Thanks @mtmorgan  and @lawremi for the review,

Martin, I'm happy you find karyoploteR in good shape. I'm away until wednesday, but I'll try to fix everything on thursday or friday. And thanks a lot for the explanation and code of the menoise problem, I was not aware that that code was evaluated on installation.

Michael, use.cache is actually true by default. The data is included in the sysdata file in the R directory and the file is updated when I manually uncomment and run the code below getCytobands. The idea behind the cache was to be able to produce a valid plot without internet connection so I would prefer not relying in htpp cache but use a more explicit caching mechanism. If it gets implemented somewhere else like in biobiz or similar i would be happy to us it.

Thanks again, 
Bernat

**Comment by lawremi** [comment]
I'm not sure I'm a big fan of the sysdata.rda mechanism. As we've seen here, it is somewhat magical. Let's put that information in a separate annotation package that other tools could use. We already know that ggbio and Gviz need it, so there's 3 packages at least.

**Comment by mtmorgan** [comment]
For the purposes of review I recommend that we continue with the package as is. If there are more substantial re-arrangements, then these can be implemented separately. Rather than an annotation package I'd suggest an AnnotationHub resource; see http://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHubData/inst/doc/IntroductionToAnnotationHubData.html#new-resources.

**Comment by lawremi** [comment]
The only problem with an AnnotationHub resource is that if a package depends on the data, it has to somehow get the data cached locally at installation time. Annotation packages do that automatically. AnnotationHub probably makes the most sense when we need to retrieve a subset of the data. For cytobands, we could easily put every UCSC cytoband track in the same package.

**Comment by bernatgel** [comment]
I have updated karyoploteR fixing the points raised by @mtmorgan:
  
1 - I've changed getCytobands so the memoised version is created onLoad following Martin's code. The only difference is that I've added an additional  `getCytobands <- NULL` statement in getCytobands.R to make roxygen happy.
2 - I've removed all `message(paste0(`
3 - I've shortened many lines but left some of them longer than 80 characters at my discretion, mainly in the roxygen documentation. Most of the code is below 80 characters, though.

@lawremi , following Martin's advice, I've left the sysdata file in place at the moment. I would be happy to use an annotation package or similar instead of a package specific cache as soon as it's available.

Thanks again for the review

Bernat

**Comment by bernatgel** [comment]
Sorry for the delay. I was away for a few days. Fixed the problem with keepSeqlevels pruning.mode parameter. 

Now it should be valid.

**Comment by mtmorgan** [comment]
Thanks I'm happy to mark this package as 'accepted'. It will be added to the Bioconductor SVN repository and nightly builds; more information will be forthcoming in the next several days.

**Comment by bernatgel** [comment]
Great :) Thanks for the review!

**Comment by bernatgel** [comment]
Just one final question. Since the build report (http://bioconductor.org/spb_reports/karyoploteR_buildreport_20161115082933.html) still shows the warning about " WARNING: y of x.y.z version should be even in release" the package landing page has not been generated. Is there anything I could do to solve that?

**Comment by mtmorgan** [comment]
The build reports for the single package builder are static, and the one you cite is old, so no need to worry about this.
