### ISSUE TITLE
CNViz

### ISSUE THREAD

**Issue by rebeccagreenblatt** [Bioconductor/Contributions#1991]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rebeccagreenblatt/CNViz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
Please see initial review below: 

**build report**

- [ ] Please fix as many NOTES as possible.

**NEWS**

- [ ] (optional) We strongly recommend adding a NEWS file.  See `?news` in R or  [news](http://bioconductor.org/developers/package-guidelines/#news).  We collate any changes identified in the NEWS file for Bioconductor release announcements. Example [release announcement](http://bioconductor.org/news/bioc_3_12_release/)

**DESCRIPTION**

- [ ]  Please remove `LazyData: true` this has rarely proved useful and can slow  package installations

**Vignette**

- [ ] You need to provide example files that can be used to actually launch and utilize your package.  You can provide small example/toy data sets in extdata, or provide the code you have hidden to create the dummy data.frames.

- [ ] I manually went in and copied all your hidden calls to launch the app. In exploring the other tab TCGA Pan-Cancer Atlas 2018 Data

```
Listening on http://127.0.0.1:7466
Warning: Specifying width/height in layout() is now deprecated.


Warning: 'cBioPortalData::getDataByGenePanel' is deprecated.
Use 'getDataByGenes' instead.
```

- [ ] Also since I did not have the cBioPortalData caching location set up, it hung waiting for a response in terminal and it fails if a user chooses not to create it.

```
Create cBioPortalData cache at 
    /home/shepherd/.cache/R/cBioPortalData? [y/n]: n
Warning: Error in setCache: 'cBioCache' directory not created. Use 'setCache'
 [No stack trace available]

```

**R/man**

- [ ] There doesn't seem to be good interoperability to existing high level use Bioconductor object. For instance really any genomic location data should also minimally take the form of GenomicRanges. There are objects like BiocSet::BiocSet and GSEABase::GeneSet.  Copy number data is also generally in an object like SummarizedExperiment; SummarizedExperiment is the standard rectangular feature x sample data object in Bioconductor.


- [ ] instead of using the `#` to make code not run in examples please use `donttest()`

- [ ] Please include documentation on sysdata.rda. What is included and source information. 


Please address the above issues.  When ready do a version bump to trigger a new build and comment back here with responses to the initial review and requesting re-review.  

Cheers

**Comment by rebeccagreenblatt** [comment]
Thank you very much for your review. I've gone through and addressed the points below:

- [x] Please fix as many NOTES as possible.

- [x] NEWS

- [x]  DESCRIPTION: Please remove LazyData: true this has rarely proved useful and can slow package installations

- [x] Vignette: You need to provide example files that can be used to actually launch and utilize your package. You can provide small example/toy data sets in extdata, or provide the code you have hidden to create the dummy data.frames.
**Provided small example data sets in external data for vignette**

- [x] cBioPortalData issues
**Removed dependency on cBioPortalData. Specifically, for the TCGA panel, instead of generating the data in real time using cBioPortalData, I created the file and added it as internal data. The code used to generate this file is included in the data-raw folder**

- [x] Warning: Specifying width/height in layout() is now deprecated: 
**Removed this warning** 

- [x] R/man: There doesn't seem to be good interoperability to existing high level use Bioconductor object. For instance really any genomic location data should also minimally take the form of GenomicRanges. There are objects like BiocSet::BiocSet and GSEABase::GeneSet. Copy number data is also generally in an object like SummarizedExperiment; SummarizedExperiment is the standard rectangular feature x sample data object in Bioconductor.
**The function now accepts probe_data, gene_data and segment_data as GRanges objects and snv_data as a VRanges object. Or they can still be input as dataframes if that is preferable to the user.**

- [x] instead of using the # to make code not run in examples please use donttest()

- [x] Please include documentation on sysdata.rda. What is included and source information.
**Included in R/data.R**

**Comment by lshep** [comment]
Thank you for the changes.  Everything looks good except please remove `devtools::load_all()` in your vignette and use `library('CNViz')`.  Once this change is made I am ready to accept the package.

**Comment by rebeccagreenblatt** [comment]
Thank you!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rebeccagreenblatt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CNViz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CNViz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
