### ISSUE TITLE
MouseThymusAgeing

### ISSUE THREAD

**Issue by MikeDMorgan** [Bioconductor/Contributions#1998]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarioniLab/MouseThymusAgeing

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by vjcitn** [comment]
It seems to me that the Collate field is inconsistent with the contents of the R folder.  Please run R CMD check, BiocCheck::BiocCheck, and when you have recommitted a working package to your github, comment here.  It also seems to me that your BiocViews are too expansive.  If this is an experiment data package do not use software-oriented views.

**Comment by MikeDMorgan** [comment]
Apologies for the slightly premature submission - R CMD check and BiocCheck complete without errors or warnings locally as of ae1946e35688617e7a77f176039bc5fabc399e6c.

**Comment by Kayla-Morrell** [comment]
@MikeDMorgan - Sorry for the delayed review. I have just a few requirements and suggestions for the package before being able to accept the package. Please comment back here when the package is ready for re-review.

## General package development

- [ ] REQUIRED: Since you are using a standard library, and you don't mention
  the file in the DESCRIPTION file, the LICENSE file should be removed.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less 
than 3 sentences. Please consider expanding this field, and structure it as a 
full paragraph.

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring and not
  include "." which indicates S3 dispatch.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package will be included 
in Bioconductor release announcements.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 143
  lines that are > 80 characters long.

Best,
Kayla

**Comment by MikeDMorgan** [comment]
Hi @Kayla-Morrell the latest push should be ready for re-review. Thanks.

**Comment by Kayla-Morrell** [comment]
@MikeDMorgan - Thank you for making those changes. There is just a slight formating issue with your NEWS.Rmd file. Please see our documentation [here](https://bioconductor.org/developers/package-guidelines/#news) on how to properly format it. Once this change has been made I'll be able to accept the package. 

Best,
Kayla

**Comment by MikeDMorgan** [comment]
Hi @Kayla-Morrell Sorry, about that - the NEWS file should now confirm to the markdown format.

**Comment by Kayla-Morrell** [comment]
@MikeDMorgan - We just need a version bump pushed as well so a new build report can be produced. Thanks!

**Comment by Kayla-Morrell** [comment]
@MikeDMorgan - Everything looks great now and I'm more than happy to accept the package.

Best,
Kayla

**Comment by MikeDMorgan** [comment]
Thanks @Kayla-Morrell!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MikeDMorgan.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MouseThymusAgeing")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MouseThymusAgeing

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
