### ISSUE TITLE
GenomicSuperSignature

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/Contributions#2003]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/seandavi/GenomicSuperSignature

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

Additional actors:
- @shbrief
- @lwaldron

**Comment by seandavi** [comment]
Thx for the quick look, @LiNk-NY .

**Comment by LiNk-NY** [comment]
Hi Sean and Sehyun, @seandavi @shbrief 
Thank you for submitting to Bioconductor. 
Please see the review below. 

Best regards,
Marcel 

---

# GenomicSuperSignature #2003

## DESCRIPTION

* Consider cutting down on the number of `Suggest`ed packages.
* Everything else looks good.

## NAMESPACE

* It looks good.

## vignettes

* Change the installation instructions to use `BiocManager`.
* Avoid installing packages in the vignette, simply use a `library` call to
load the package. These dependencies are stated in the `Suggests` field of
your `DESCRIPTION` file.
* `eval=FALSE` chunks in the Quickstart vignette should be evaluated or removed

## R

* Don't include manual outputs in your examples (`R/annotatePCcluster.R` and
others). Perhaps you can use these as templates for unit tests.
* To reduce the amount of repeated code, isolate the difference in the
conditions and make that the content of the `if` `else` statements, for
example in `R/annotatePCcluster.R`:
```r
FUN <- if (abs) { abs } else { I }
```
and then do:
```r
topAnnotation <- annotatedCluster[
    order(FUN(annotatedCluster$NES), decreasing = TRUE),,drop = FALSE][1:n,]
```
* Avoid using `1:n` sequence generation and use the more robust `seq_len(n)`.
* Test S4 class membership with `is(RAVmodel, "PCAGenomicSignatures")` from
the `methods` package. For S3, use `is.list` (`R/buildAvLoading.R`).
* Describe what the default NULL behavior does in `findStudiesInCluster`.
* Avoid using copy-and-append methods with for loops, use the allocate and
fill method (`buildAvgLoading`).
* Use coercion rather than wrapping when checking class membership in
`calculateScore`, e.g.,
```
> list(List())
[[1]]
List of length 0

> as.list(List())
list()
```
* Using `get` in package code is not usually recommended (`commonGene`).
If you're trying to load data from the package create an environment for
depositing that data and extract it from there:
```r
    local_data_store <- new.env(parent = emptyenv())
    data("sampleTypes", envir = local_data_store, package = "TCGAutils")
    sampleTypes <- local_data_store[["sampleTypes"]]
```
* Avoid setting a seed inside a function (`drawWordCloud`).
* Use the more robust `vapply` over `sapply`.
* If you created methods for the virtual class (`GenomicSignatures`) you may
not need to create additional methods for `PCAGenomicSignatures` because
they're automatically inherited, unless those methods are different.
* Some methods are compatible out of the box, e.g., `colData` because you
are inheriting from `SummarizedExperiment` so you don't need to create them.
* State your `rappdirs` dependency in the Imports field or use
`tools::R_user_dir`.
* Perhaps run `.RAVName` before creating the `PCAGenomicSignatures` class 
in the constructor function? Usually the class construction occurs after the
pre-processing steps.
* Some of the inputs in your class are matrix which perhaps should be your
class or even `SummarizedExperiment`? (`plotAnnotatedPCA`)
* Avoid using `class(x) %in% c("x", "y", "z")` constructions and use the S3
methods of `is.data.frame`, `is.matrix`, `is.list` (`subsetEnrichedPathways`).
* These functions can be reduced to one (`R/validatedSingatures.R`):
```r
.filterByClusterSize <- function(data, cutoff) {
  ind <- which(rownames(data) == "cl_size")
  val_ind <- which(data[ind,] >= cutoff)
  dat <- data[,val_ind]
  return(dat)
}

.filterByScore <- function(data, cutoff) {
  ind <- which(rownames(data) == "score")
  val_ind <- which(data[ind,] >= cutoff)
  dat <- data[,val_ind]
  return(dat)
}

.filterByAvgSW <- function(data, cutoff) {
  ind <- which(rownames(data) == "sw")
  val_ind <- which(data[ind,] >= cutoff)
  dat <- data[,val_ind]
  return(dat)
}
```

```r
.filterBy <- function(data, cutoff, type = c("cl_size", "score", "sw")) {
  type <- match.arg(type)
  ind <- rownames(data) == type
  val_ind <- which(data[ind,] >= cutoff)
  data[,val_ind]
}
```

Minor:
* You don't need to use `isTRUE`, `isFALSE`, or `x == TRUE` on expected
logical values. What you should do is check those inputs by doing something
like: `stopifnot(is.logical(abs), length(abs) == 1L, !is.na(abs))`.
* Note you can also use `utils::globalVariables` for line 29 in
`R/funcForGSEA.R`
* Stick to the 80 column width limits for your code.

## tests

* Add more tests to make the code more robust.

**Comment by seandavi** [comment]
@lshep and @hpages, any thoughts on whether phantomjs should be available on the build machines? If not, we'll just `\dontrun` the offending code, but I wanted to double-check. Thanks in advance.

**Comment by seandavi** [comment]
@LiNk-NY any thoughts about what to do with the warnings about filenames on Windows? 

```
Found the following significant warnings:
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/geneSets<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/updateNote<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/metadata<-,GenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/colData<-,GenomicSignatures,ANY-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/geneSets<-,GenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/updateNote<-,GenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/studies<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/silhouetteWidth<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/gsea<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/trainingData<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/mesh<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/PCAsummary<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/studies<-,PCAGenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/silhouetteWidth<-,PCAGenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/gsea<-,PCAGenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/trainingData<-,PCAGenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/mesh<-,PCAGenomicSignatures-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/PCAsummary<-,PCAGenomicSignatures-method.html': Invalid argument
```

**Comment by LiNk-NY** [comment]
> @LiNk-NY any thoughts about what to do with the warnings about filenames on Windows?
> 
> ```
> Found the following significant warnings:
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/geneSets<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/updateNote<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/metadata<-,GenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/colData<-,GenomicSignatures,ANY-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/geneSets<-,GenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/updateNote<-,GenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/studies<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/silhouetteWidth<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/gsea<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/trainingData<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/mesh<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/PCAsummary<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/studies<-,PCAGenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/silhouetteWidth<-,PCAGenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/gsea<-,PCAGenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/trainingData<-,PCAGenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/mesh<-,PCAGenomicSignatures-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/2003/bba1f1eaa98d23b369456f839ad5160306919554/GenomicSuperSignature.buildbin-libdir/00LOCK-GenomicSuperSignature/00new/GenomicSuperSignature/help/PCAsummary<-,PCAGenomicSignatures-method.html': Invalid argument
> ```

Hi Sean, @seandavi 
No need to do anything there. Those are artifacts of the way we build the package on Windows. 
Best,
Marcel

**Comment by hpages** [comment]
Sorry guys for completely missing the PhantomJS thing.

@seandavi Can you please list the system requirements in the `SystemRequirements` field and provide an `INSTALL` file (in the top-level folder) that shortly explains how to get those extra things for each platform? Thanks.

**Comment by seandavi** [comment]
Thanks, @hpages. I think we are good. No need to add complexity.

**Comment by hpages** [comment]
Thanks! Don't know how you're handling this but I want to mention that I took a look at what `webshot::install_phantomjs()` does and didn't really like what I saw: it's downloading an executable directly in the user's `~/bin` folder. This is not good.

**Comment by LiNk-NY** [comment]
Hi Sean, @seandavi 

Can you provide a summary of the changes? 
I can go ahead and take a second look at it if it's ready. 
Thank you. 

Best,
Marcel

**Comment by shbrief** [comment]
Hi Marcel, @LiNk-NY 
Here is the summary of the changes.

## vignettes
* Installation instructions are using `BiocManager` now.
* Packages are loaded but not installed in the vignettes.
* `eval=FALSE` chunks are removed. (Quickstart vignette)

## R
* Manual outputs under the examples are removed.
* Redundant codes are cleaned. (`annotatePCcluster`, `validatedSingatures`)
* `1:n` is updated to `seq_len(n)`.
* Class membership is evaluated using `methods::is` (S4 class) and S3 methods (e.g. `is.list`). (`buildAvgLoading`, `subsetEnrichedPathways`)
* The default NULL behavior of `findStudiesInCluster` is described.
* copy-and-append method in for loop is replaced with allocate-and-fill method. (`buildAvgLoading`)
* Coercion is used instead of wrapping. (`list(dataset)` to `as.list(dataset)` in `calculateScore`)
* Inherited methods are removed from GenomicSignatures-methods. (`colData` and `metadata`)
* Use `tools::R_user_dir` instead of `rappdirs::user_cache_dir`
* `commonGene` function is removed.
* Seed inside the function is removed. (`drawWordCloud`) 
* `sapply` is replaced with `vapply` in `buildAvgLoading`, `findSignature`, and `validate`. (`drawWordcloud` still uses `sapply` because the output has different lengths.)
* These functions accept different classes of input datasets now : `calculatedScore`, `plotAnnotatedPCA`, and `validate`.
* Removed `isTRUE`, `isFALSE`, and `x == TRUE` for expected logical values.

**Comment by LiNk-NY** [comment]
Hi Sehyun, @shbrief 
I'm getting an error when checking this on seandavi/GenomicSuperSignature@9820cf8. 
```
> score <- calculateScore(dset, miniRAVmodel)
Error in as.list.default(dataset) : 
  no method for coercing this S4 class to a vector
Calls: calculateScore -> as.list -> as.list.default
Execution halted
```

**Comment by seandavi** [comment]
@LiNk-NY, I think we fixed the issue--suggests package wasn't required in the example. 

Are builds still kicked off here based on changes? Looks like perhaps not?

**Comment by lshep** [comment]
There has to be a version bump on the main branch and it should kick off a new build

**Comment by lshep** [comment]
I don't think a version bump in a merge is picked up by the hook that triggers the build.

**Comment by seandavi** [comment]
Thanks, @lshep. Then I think I am missing something, as it looks like this commit didn't trigger a build:

https://github.com/seandavi/GenomicSuperSignature/commit/9f0cc099f2615802526f04a4cfdb39010f6a60dd

**Comment by lshep** [comment]
and you push to git.bioconductor.org as well ?

**Comment by seandavi** [comment]
Oops. I missed the change in workflow. Thanks again, @lshep

**Comment by LiNk-NY** [comment]
Thanks for making those changes Sehyun and Sean!
Please reduce the number of `NOTE`s in the package. Thanks!

Best regards,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/seandavi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GenomicSuperSignature")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GenomicSuperSignature

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
