### ISSUE TITLE
scShapes

### ISSUE THREAD

**Issue by Malindrie** [Bioconductor/Contributions#2011]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Malindrie/scShapes

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Malindrie** [comment]
Hi @nturaga 

I was wondering about the status of the review of our package? Greatly appreciate you looking into this.

Thanks!

**Comment by nturaga** [comment]
# scShapes Review

## General

- Fix NOTE:

```
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        model_param.R (line 79, column 36)
```


```
* checking R code for possible problems ... [11s/11s] NOTE
ks_test : KS_ZINB: no visible global function definition for ‘is’
model_bic : model_BIC: no visible global function definition for ‘is’
Undefined global functions or variables:
  is
Consider adding
  importFrom("methods", "is")
```

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## Dockerfile

- Please try include the Dockerfile in the inst/ folder if you'd like it
to be shipped with the package.

- you could also use the `bioconductor/bioconductor_docker:devel`
  image as a base.
  
- Same with the singularity image.
  
## vignettes

ok

## R

- Use BiocParallel instead of parallely to parallelize functions.

- When you usually do a `try()` you have to catch the eventual error and give something as an output to the user. Just a try() is rarely
  useful

- This is just a "protip" I guess, when you include a function like `version()`, you are setting yourself up for perpetual maintenance. Because the package version will change every time you update your DESCRIPTION file. And the `version()` function will have to mimic that. Right now it is hardcoded.
  
- Functions within functions are not useful for the way you've used them. Might as well make them explicit (model_bic()).

**Comment by nturaga** [comment]
Hi @Malindrie 

Please reply to each point as soon as your finish addressing them, or explain your reasoning for them. 

3 weeks from this post, I'll close the issue for inactivity if you cannot get to it. There is no problem with this, and you can get back to working on the package when you have more time. 

Best regards,

Nitesh

**Comment by Malindrie** [comment]
Hi @nturaga 

Thank you for the review! Apologies I couldn't address them yet, but I will do it within the next two weeks. I will trigger a new build when I address the points or will get back if I encounter any issues.

Thank you!

**Comment by Malindrie** [comment]
Hi @nturaga 

I have addressed almost all the points above. Hope it's fine now. Looking forward to hearing about the updated submission and whether there are any other points to be addressed. 

Best,
Malindrie

**Comment by Malindrie** [comment]
Hi @nturaga

I was wondering about the status of the review of our package after addressing the initial comments and feedback? Is it required that I reply to each point stating what I did? Greatly appreciate you looking into this.

Thank you 

Best,
Malindrie

**Comment by nturaga** [comment]
Please reply to each point.

**Comment by Malindrie** [comment]
Hi @nturaga,

Thank you for the review. I addressed points from both reviews and please find below the adjustments I made under each point.

- Fixed NOTEs

1. added seq_len(2) in line 79 of model_param.R 

* NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        model_param.R (line 79, column 36)

2. added @importFrom methods is in model_BIC.R

* checking R code for possible problems ... [11s/11s] NOTE
ks_test : KS_ZINB: no visible global function definition for ‘is’
model_bic : model_BIC: no visible global function definition for ‘is’
Undefined global functions or variables:
  is
Consider adding
  importFrom("methods", "is")

3. added sessionInfo() in vignette

* Checking vignette directory...
    * NOTE: 'sessionInfo' not found in vignette(s)
      Missing from file(s):
        vignette_scShapes.Rmd


- Dockerfile

4. added both Dockerfile and Singularity image in inst/ folder


- R

5. changed futures to BiocParallel, to parallelize functions.

6. tryCatch() added to print the error message in most functions and in others "NA" will be returned.

7. The function version() in version.R was removed.

8. The function within function in model_bic.R is now included outside of the main function.


Thank you. Looking forward to hearing from you.


Best,
Malindrie

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Malindrie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scShapes")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scShapes

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
