### ISSUE TITLE
tricycle

### ISSUE THREAD

**Issue by sjczheng** [Bioconductor/Contributions#2021]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hansenlab/tricycle

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi ShiJie, @sjczheng 

Thank you for your submission. Please see the review below. 
Remember to respond to the review bullet point by bullet point. 

Best,
Marcel

---

# tricycle #2021

## DESCRIPTION

* You may want to move the `methods` package to `Imports`..
* `org.*.db` packages should likely go in the `Suggests`
* If `dplyr` already exports the pipe, do you need `magrittr`?
* Add a `BugReports` URL.
* Make `LazyData: FALSE` in the `DESCRIPTION`.

## NAMESPACE

* Is there a reason for importing the `ANY` class in `methods`?
* It would be better for the user to not import the large `org.*.db` package.
* You should be able to reduce some of these dependencies (e.g., `forcats`,
`purrr`) and use base R functionality.

## vignettes

* It is easier to review a vignette that does not go off the page. This means
keeping to an 80 character width limit. The code should especially follow this
character width limit for display purposes.
* Use `library` to load packages in the vignette

Minor:
* `labs(x = "Oroginal"...)` should probably be "Original".

## R

* The S4 generics look like S3 functions which can lead to confusion. Perhaps
these should be plain functions or S3 methods?
* I recommend creating methods for classes you own so that you don't pollute
the methods environment for other classes. This means removing the `setMethod`
functions and creating a plain function that is conditional to each class
input. The methods all call `.getTheta` which can be called once in the new
plain function.
* Be more specific with error messages. "Something is wrong" is not very
helpful to the new user; describe the error.
* Optionally load packages if the user has them installed in `.getSYMBOL` &
`.humanSymbol`.  Otherwise, tell the user to install those packages in an
error (after these have been added to the `Suggests` field)

## tests

* We highly recommend that you add tests to your package to minimize bugs
and increase robustness in package code.

**Comment by sjczheng** [comment]
Hi Marcel,

I have made changes based on your comments.
Please find the following point-to-point response.
Thanks so much.

Best ,
Shijie

> 
> # tricycle #2021
> ## DESCRIPTION
> * You may want to move the `methods` package to `Imports`..      _Changed as requested_
> * `org.*.db` packages should likely go in the `Suggests`.   _Changed as requested_
> * If `dplyr` already exports the pipe, do you need `magrittr`?   _Remove magrittr dependence_ 
> * Add a `BugReports` URL.   _Added_ 
> * Make `LazyData: FALSE` in the `DESCRIPTION`.      _Changed as requested_
> 
> ## NAMESPACE
> * Is there a reason for importing the `ANY` class in `methods`?   _`ANY` class  removed_
> * It would be better for the user to not import the large `org.*.db` package.  _`org.*.db` no longer imported_ 
> * You should be able to reduce some of these dependencies (e.g., `forcats`,
>   `purrr`) and use base R functionality.    _Changed as requested, replcae`forcats` and `purrr` functions with base functions_
> 
> ## vignettes
> * It is easier to review a vignette that does not go off the page. This means
>   keeping to an 80 character width limit. The code should especially follow this
>   character width limit for display purposes.   _Changed as requested_
> * Use `library` to load packages in the vignette.  _Changed as requested_
> 
> Minor:
> 
> * `labs(x = "Oroginal"...)` should probably be "Original".   _Changed as requested_
> 
> ## R
> * The S4 generics look like S3 functions which can lead to confusion. Perhaps
>   these should be plain functions or S3 methods?  _Changed all S4 method to plain functions_
> * I recommend creating methods for classes you own so that you don't pollute
>   the methods environment for other classes. This means removing the `setMethod`
>   functions and creating a plain function that is conditional to each class
>   input. The methods all call `.getTheta` which can be called once in the new
>   plain function.   _Changed all S4 method to plain functions_
> * Be more specific with error messages. "Something is wrong" is not very
>   helpful to the new user; describe the error.    _Changed as requested, provide detailed error_
> * Optionally load packages if the user has them installed in `.getSYMBOL` &
>   `.humanSymbol`.  Otherwise, tell the user to install those packages in an
>   error (after these have been added to the `Suggests` field).  _Changed as requested_
> 
> ## tests
> * We highly recommend that you add tests to your package to minimize bugs
>   and increase robustness in package code.    _tests added_
> 
> For more information, see:
> 
> ```r
> BiocCheck::BiocCheck("tricycle")
> ```

**Comment by kasperdanielhansen** [comment]
It seems like the Mac OS host has problems; see the package size in the build report. We're bumping version number and trying again.

**Comment by sjczheng** [comment]
@LiNk-NY Hi Marcel, I have been trying to fixing error when building on mac host.
Unfortunately, I couldn't figure out what went wrong there. Could you take a look for us?
Thanks so much.

**Comment by LiNk-NY** [comment]
Hi Shijie, @sjczheng 

Thank you for making those changes. 

They look good. 

One thing I noticed was that you're putting some data in the `.GlobalEnv`. This is not recommended practice. Please load the data to a new and empty environment using `new.env(parent = emptyenv())`. See `data(RevelioGeneList, package = "tricycle", envir = environment())`. 

Best regards,
Marcel

**Comment by kasperdanielhansen** [comment]
This is a recent change (weekend) we made, so perhaps you missed it?

**Comment by LiNk-NY** [comment]
Hi Shijie, @sjczheng 

Data loaded inside of a function should not leave the function and go to the `.GlobalEnv`. 

```sh
R/estimate_Schwabe_stage.R:163:        data(RevelioGeneList, package = "tricycle", envir = environment())
```

Create an environment inside the fucntion using:

```r
data_env <- new.env(parent = emptyenv())
data("RevelioGeneList", package = "tricycle", envir = data_env)
RevelioGeneList <- data_env[["RevelioGeneList"]]
```

Best,
Marcel

**Comment by kasperdanielhansen** [comment]
We're following the recommendation laid out in `?data` under the heading "Good practice" where it says
>  Use of ‘data’ within a function without an ‘envir’ argument has the almost always undesirable side-effect of putting an object in the user's workspace (and indeed, of replacing any object of that name already there).  It would almost always be better to put the object in the current evaluation environment by ‘data(..., envir = environment())’.

**Comment by kasperdanielhansen** [comment]
We'll double check that this puts the data object inside the environment of the current function.

**Comment by kasperdanielhansen** [comment]
I have confirmed nothing gets loaded into the global workspace.

**Comment by LiNk-NY** [comment]
Hi Kasper, @kasperdanielhansen 

Thank you for clarifying and double checking.
That works as well but it does not resolve the `NOTE`:

```
* checking R code for possible problems ... NOTE
.estimate_Schwabe_stage: no visible binding for global variable
  ‘RevelioGeneList’
```
as opposed to the code provided.

**Comment by sjczheng** [comment]
Hi Marcel, @LiNk-NY 
I fix these notes now.
Best,
Shijie

**Comment by sjczheng** [comment]
Hi Marcel @LiNk-NY ,
I did what you requested. 
And we get a warning on Windows. However, I am not sure we can solve that at our ends.
"Warning: no function found corresponding to methods exports from 'S4Vectors' for: 'combineRows'"
Do you have any suggestions?

Best,
Shijie

**Comment by LiNk-NY** [comment]
Hi Shijie, @sjczheng 
I think that issue is on our end. You can safely ignore it for now. 
Thank you. 
-Marcel

**Comment by LiNk-NY** [comment]
Hi ShiJie, @sjczheng 
Thank you for making the changes. 
The package looks ready to go. Thank you for your submission.
Best regards,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sjczheng.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tricycle")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tricycle

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
