### ISSUE TITLE
supersigs

### ISSUE THREAD

**Issue by albertkuo** [Bioconductor/Contributions#2022]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/TomasettiLab/supersigs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by albertkuo** [comment]
I am not sure how to resolve the error in the build report. 
`Error: processing vignette 'supersigs.Rmd' failed with diagnostics:
package or namespace load failed for 'VariantAnnotation' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'rtracklayer'`

The package loads VariantAnnotation in the vignette, but doesn't use rtracklayer otherwise.

**Comment by lshep** [comment]
This is most likely on our side or on the rtracklayer folks to fix.  Your reviewer will review most likely will review the package disregarding this error for now.

**Comment by hpages** [comment]
Hi @albertkuo 

Thanks for submitting **supersigs**.

**rtracklayer**'s compilation issue on Windows [has been fixed](https://github.com/lawremi/rtracklayer/issues/44) and the package is now installed on our Windows builder again. Can you please bump **supersigs**'s version? This will trigger a new build.

Thanks,
H.

**Comment by albertkuo** [comment]
Hi @hpages, I bumped the version. Thanks!

**Comment by hpages** [comment]
Hi @albertkuo ,

Thanks for submitting **supersigs**.

Note that the `doc/` folders contains the HTML version of the vignette. This is not something that should be included in the _source tree_ of a package. Please remove.

Similarly it's not clear to me that the `docs/` folder belongs to the _source tree_ either. Seems to contain stuff generated by **pkgdown**. Not sure when/how these things are generated but please note that files that are automatically generated by `R CMD build <pkg>` should not be included in the package source tree.

Thanks,
H.

**Comment by albertkuo** [comment]
Hi @hpages,

OK I removed the `doc/` folder from the repository. Is that what you meant by source tree? 

I think I need to keep the `docs/` folder on the github repository to keep the pkgdown site running though, so I am not sure if I should remove it. 

Thank you for your help!

- Albert

**Comment by hpages** [comment]
Hi @albertkuo ,

Yes a git repository can contain a lot of things, it doesn't even have to be software, just files, but in the case of **supersigs** it contains the _source tree_ of an R package. Thanks for cleaning it.

Please bump the version of the package and push, so we get a new build report.

Thanks,
H.

**Comment by hpages** [comment]
Package is good to go. Thanks!

H.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/albertkuo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("supersigs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/supersigs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
