### ISSUE TITLE
KBoost

### ISSUE THREAD

**Issue by Luisiglm** [Bioconductor/Contributions#2027]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Luisiglm/KBoost

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by nturaga** [comment]
## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

- expand Description to match the abstract of a paper, provide more detail.

- LazyData:true is not needed.

## NAMESPACE

ok

## R

- Use <- instead
  =. http://bioconductor.org/developers/how-to/coding-style/ follow the coding style points closely.

- I think the package needs to use SummarizedExperiment and graph structures eventually.  These can be goals for revision during 3.13
  towards 3.14....

## General - BiocCheck

NOTE:
[4] "License 'LGPL (>= 3)' unknown; licenses cannot restrict use"                                                                                                                

[5] " Avoid redundancy in signalers"

**Comment by Luisiglm** [comment]
@nturaga 

Thank you very much for your comments.

Regarding the DESCRIPTION file, we have expanded the "Description" field to match the abstract of the preprint paper: https://www.biorxiv.org/content/10.1101/2021.04.01.438059v1. Please note, we have omitted the parts of the abstract that were not specific to the package.  As to the "LazyData" field, we hope it is Ok if we keep it as "true" as some of the functions were written to load package data in that manner. 

For the R folder, we have replaced "=" with "<-". Regarding your suggestion of including SummarizedExperiments and graph structure, it is something we will keep in mind. The package's first version was designed thinking of using matrixes to keep it as simple as possible. 

Kind regards,

Luis Iglesias-Martinez

**Comment by nturaga** [comment]
Ok, i'm accepting your package. Please keep in mind the change to add the use of a SummarizedExperiment object in the next devel cycle. I'll keep an eye out for this feature. 

Thank you for your contribution.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Luisiglm.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("KBoost")`. The package 'landing page' will be created at

https://bioconductor.org/packages/KBoost

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
