### ISSUE TITLE
SingleMoleculeFootprintingData

### ISSUE THREAD

**Issue by GuidoBarzaghi** [Bioconductor/Contributions#2034]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GuidoBarzaghi/SingleMoleculeFootprintingData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by GuidoBarzaghi** [comment]
AdditionalPackage: https://github.com/GuidoBarzaghi/SingleMoleculeFootprinting

**Comment by GuidoBarzaghi** [comment]
Hi @LiNk-NY,

I was wondering whether I misunderstood the procedure for submitting an additional package. I was expecting for it to automatically go through the build checks analogously to what happened to the primary one. Is there something I did wrong that is causing the system not to be prompted?

**Comment by LiNk-NY** [comment]
Hi Guido,  @GuidoBarzaghi 
It looks like the procedure to add the package worked out smoothly. 
Please see the result report and modify accordingly.

**Comment by GuidoBarzaghi** [comment]
@LiNk-NY thanks a lot for your reply. This is my first ever submission to Bioconductor so I'm not entirely sure on what to expect at each step.

I'm afraid I need to ask for your input again: there is an ERROR reported under the "tokay2 BUILD BIN output" section that I'm not sure how to tackle. I'm not entirely sure how I can influence the installation of dependencies on windows.  Do you have any suggestion?

**Comment by grimbough** [comment]
@GuidoBarzaghi It looks like Rbowtie & subsequently QuasR aren't available for 32-bit Windows.  You can specify not to build your package on that platform by adding the file `.BBSoptions` to the root of your package.  It should be fine to copy the one from QuasR at https://github.com/fmicompbio/QuasR/blob/master/.BBSoptions

**Comment by GuidoBarzaghi** [comment]
@grimbough Oh I see. Thank you for clarifying!

**Comment by LiNk-NY** [comment]
Hi Guido, @GuidoBarzaghi 

Thank you for your submission. Please see the reviews below.
Feel free to comment with questions.

Best regards,
Marcel

---

# SingleMoleculeFootprinting #2034

## DESCRIPTION

* Please use full sentences in the `Description` field (for `BiocCheck`).
* Do you need to import both `AnnotationHub` and `ExperimentHub`?
* Most often, the data package goes in the `Suggests` field.
* Make `LazyData: false` or remove the line.
* Add a `BugReports` field.

## NAMESPACE

* `AnnotationHub` seems out of place.
* Perhaps the `parallel` functionality listed here is for user-level commands?
* Everything else looks good.

## vignettes

* Please stick to the 80 width character limit convention. It makes it easier
to read and review.
* Load the packages that you use with `library(parallel)`, for example.
* Avoid using `eval = FALSE` in code chunks. Use an small example dataset to
show the functionality of your package. `eval=FALSE` chunks can become stale
quite quickly.
* Why are `\` backslashes needed in the text?
* I suggest moving the `Installation` section to the beginning of the vignette.
* Remove the `GitHub` installation section.
* The `AnnotationHub` query is not necessary when you already have a data
package that has a covenience function for loading the data. Use your own
package.
* Please don't move the file and keep it in the default cache. Otherwise,
your package will be downloading the data every time it gets checked on
our build system (BBS).
* Perhaps you can provide a runnable `qQCReport` with a small dataset?
* Avoid `1:n` sequence generation, use the more robust `seq_len(n)`.
* Do not use `print` even in the vignette. Use `message` if necessary.
* Provide a `sessionInfo` at the end of the vignette.

Minor:
* Our convention is to use `<-` for assignment instead of `=` but this not
strictly enforced.
* There are some typos chuck > chunk

## R

* You can use the data package for your examples, if necessary. Avoid using
the `tempdir()` especially for downloaded data as pointed out above.
* Some of the logic can be improved, for example:
```r
  MethSM_minus = MethSM[apply(MethSM[,IsMinusStrand], 1, function(i){sum(is.na(i)) != length(i)}) > 0, IsMinusStrand]
  MethSM_plus = MethSM[apply(MethSM[,!IsMinusStrand], 1, function(i){sum(is.na(i)) != length(i)}) > 0, !IsMinusStrand]
```
It's not clear in the code what you're trying to do. Perhaps `!all(is.na(i))`
is what you need to check for each row? or `rowSums(is.na(i)) > 0`? These are
likely to be faster.
* Add a `verbose` argument to functions like `CallContextMethylation` and
others.
* Where possible, avoid numeric indices and use named indices.
* Consider using `BiocParallel` instead of `parallel::makeCluster` for
`BaitCapture`. It may work better across systems.
* `SampleCorrelation` should be using data in the `extdata` directory.
* Avoid saving the file for the user in `SampleCorrelation`, create the plot
and display it in the graphics device. The user will then be able to choose
their format of choice (e.g., `png`).

## tests

* We highly recommend adding unit tests to your package.


---

# SingleMoleculeFootprintingData

## DESCRIPTION

* Please include more information in the `Description` field.

## vignette

* Show the user how to download the data for the package by calling
the function created by `createHubAccessor`.

**Comment by LiNk-NY** [comment]
**Note**. For more information, see:
```r
BiocCheck::BiocCheck("SingleMoleculeFootprinting")
```

**Comment by GuidoBarzaghi** [comment]
@LiNk-NY thanks a lot for your comments. I have tried to thoroughly address all the points you brought up.

I would just like to offer some clarifications about a couple of them:

### DESCRIPTION:

- Most often, the data package goes in the Suggests field.

In this case, some of the objects accessed through the data package are necessary for a couple of functions to work. Therefore it is necessary to import the data package when loading the software one

### VIGNETTE:

- Please don't move the file and keep it in the default cache. Otherwise, your package will be downloading the data every time it gets checked on our build system (BBS).

I actually just copy it in order to rename it with a relevant extension. This is necessary for one of the dependencies of SingleMoleculeFootprinting to recognise these files.

- Perhaps you can provide a runnable qQCReport with a small dataset?

Unfortunately, qQCreport will not run with a dataset that is too small (such is the case for the example data provided through SingleMoleculeFootprintingData). Consequently, I removed the code chunk relative to this and referred to the documentation of the package QuasR relative to the function qQCreport.

### R:
- Consider using BiocParallel instead of parallel::makeCluster for BaitCapture. It may work better across systems.

Because of this and other comments, I removed all the instances of makeCluster/stopCluster across the package and leave to the user the choice of how to create a cluster object. Still in the vignette and the example code in the function manuals I show how to do this using parallel since this is how the documentation of the dependency QuasR indicates.

- Where possible, avoid numeric indices and use named indices.

Unfortunately where numeric indices are still present they are strictly necessary as of now, I will keep this in mind for the future.

Once again, thanks for your suggestions I will keep them in mind as I go along and keep developing in the future. Let me know if I can further clarify something.

**Comment by LiNk-NY** [comment]
Hi Guido, @GuidoBarzaghi 

> ### DESCRIPTION:
> * Most often, the data package goes in the Suggests field.
> 
> In this case, some of the objects accessed through the data package are necessary for a couple of functions to work. Therefore it is necessary to import the data package when loading the software one

I would not require **everyone** to install data package. Only the users using those functions should install the data package.
You can implement this using some logic to check for the package availability (after putting the package in `Suggests`):
```
if (!requireNamespace("LargeDataPackage", quietly = TRUE))
    stop("Install the 'LargeDataPackage' to use this function")
```

> ### VIGNETTE:
> * Please don't move the file and keep it in the default cache. Otherwise, your package will be downloading the data every time it gets checked on our build system (BBS).
> 
> I actually just copy it in order to rename it with a relevant extension. This is necessary for one of the dependencies of SingleMoleculeFootprinting to recognise these files.
> 

I see the issue now. I think the software should work regardless of the extension but you don't have any control of `QuasR`... 
I will ask about a way to preserve the file extension. 

Thanks!
Best,
Marcel

**Comment by GuidoBarzaghi** [comment]
@LiNk-NY thanks for the suggestion: I am moving the data package to `Suggests`.

About the file extension issue, I was trying to work it out with the help of a member of the Bioconductor CoreTeam while uploading this data to the AWS. However, since this was not of the highest priority we decided to postpone addressing the issue. I am keen on implementing a better solution if available.

**Comment by grimbough** [comment]
Hi Marcel (@LiNk-NY),

As a minor contributor to this package, I just wanted to chime in with my 2 cents on the use of the cached ExperimentHub data.  We tried quite a few ways to "trick" QuasR into using the files as they R in the ExperimentHub cache, but things like symlinks were always resolved to the original file and then it would complain about the file extension.  Making a copy from the cache to `tempdir()` seemed like the least-worst strategy.  It should be relatively inexpensive as the cached version remains in place between runs, we can guarantee write access, and we aren't polluting anywhere else as the temporary copy will be deleted after the vignette or example has been run.

We did talk to @Kayla-Morrell about whether it would be possible to retain file extensions on entries in the cache, but I think that was something that would have to wait until after this release.  We would of course be willing to update the mechanism in the future if a solution like that become available, it would clearly be nicer to use the files in-place.

**Comment by lshep** [comment]
This is probably okay and the best middle ground for now and we can work on a better solution in the hubs and in collaboration with you over the next release cycle.

**Comment by LiNk-NY** [comment]
Thanks Lori and Mike for looking into this!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GuidoBarzaghi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingleMoleculeFootprintingData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingleMoleculeFootprintingData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GuidoBarzaghi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingleMoleculeFootprinting")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingleMoleculeFootprinting

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
