### ISSUE TITLE
dStruct

### ISSUE THREAD

**Issue by dataMaster-Kris** [Bioconductor/Contributions#2035]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dataMaster-Kris/dStruct

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Hi @dataMaster-Kris,

Thanks for submitting the **dStruct** package. Here is some feedback:

1. The package doesn't reuse Bioconductor core data structures and reinvents the wheel. For example, instead of doing:
    ```
    > nucleotide_positions <- c(1, 3, 2, 8, 4:7, 11:20)
    > getContigRegions(nucleotide_positions)
      Start Stop
    1     1    8
    2    11   20
    ```
    you should be doing:
    ```
    > library(IRanges)
    > as(sort(nucleotide_positions), "IRanges")
    IRanges object with 2 ranges and 0 metadata columns:
              start       end     width
          <integer> <integer> <integer>
      [1]         1         8         8
      [2]        11        20        10
    ```
    IRanges and GRanges objects are the standard way to represent ranges (or regions) and genomic regions.
    Also the `dStruct()` function should return an IRanges objects with metadata columns instead of the following data.frame:
    ```
      Start Stop        pval      del_d          FDR
    1    19  146 0.000145679 0.11071808 0.0007283952
    2   530  553 0.071184091 0.07939060 0.0711840914
    3   583  632 0.021902932 0.01748423 0.0365048862
    4  1122 1177 0.036887884 0.02047984 0.0461098552
    5  1187 1218 0.016484691 0.09202706 0.0365048862
    ```
    Please take the time to familiarize yourself with IRanges and GRanges objects and use them where appropriate in your package. IRanges and GRanges objects are implemented in the **IRanges** and **GenomicRanges** packages, respectively.

2. The first `dStructome()` call in the examples section of `dStructome`'s man page produces many "cannot compute exact p-value with zeroes" warnings (more than 50). Is this expected?

3. The man pages are too minimalist. The Description section is often a short one-liner that don't really provide enough information for the user to get a clue of what the function does. For example: "Calculates d score". But what is a d score? If it's a distance (as suggested by the name of the function `calcDis`) then the man page should say so. If it's not a distance and if the term "score" is more appropriate to describe it, then the name of the function should reflect that (good naming is important).

4. It's not clear what the purpose of the `two.eight.normalize()` function is or why it is in the package in the first place. It doesn't seem to be used anywhere, the example in the man page is not particularly illustrative, and the description is very minimalist. Also why is the naming style of the function (dot-separated words) different from the naming styles of the other functions in the package (most of them follow the camelCaps style)?

5. More about naming style: all functions in the package follow the camelCaps style except `two.eight.normalize`, `dStruct.guided`, and `plot_dStructurome`. Please use a consistent naming style for all your functions.

6. Coding style: please use the left arrow (`<-`) instead of `=` for assignments. Make sure to leave a space before and after the `<-`.

7. The `refs.bib` file is in the wrong place: it should be in the `vignettes/` folder. Then you can remove the `inst/extdata/` folder.

Thanks,
H.

**Comment by hpages** [comment]
Hi @dataMaster-Kris,

Are you planning to follow up on this submission?

Best,
H.

**Comment by dataMaster-Kris** [comment]
Hi @hpages Thanks for the review and following up! I am working to address your comments. Will submit it within the next couple of weeks, hopefully sooner. Please keep this review page open.

**Comment by hpages** [comment]
Ok. Thanks for the update.

**Comment by dataMaster-Kris** [comment]
Hi @hpages 

Thanks again for your time reviewing the code and valuable comments. I have revised the code and other files to address your comments as follows.

>     1. The package doesn't reuse Bioconductor core data structures and reinvents the wheel. For example, instead of doing:
>        ```
>        > nucleotide_positions <- c(1, 3, 2, 8, 4:7, 11:20)
>        > getContigRegions(nucleotide_positions)
>          Start Stop
>        1     1    8
>        2    11   20
>        ```
>        
>        
>        you should be doing:
>        ```
>        > library(IRanges)
>        > as(sort(nucleotide_positions), "IRanges")
>        IRanges object with 2 ranges and 0 metadata columns:
>                  start       end     width
>              <integer> <integer> <integer>
>          [1]         1         8         8
>          [2]        11        20        10
>        ```
>        
>        
>        Note that IRanges and GRanges objects are the standard way to represent ranges (or regions) and genomic regions in Bioconductor.
>        Also the `dStruct()` function should return an IRanges object with metadata columns instead of the following data.frame:
>        ```
>          Start Stop        pval      del_d          FDR
>        1    19  146 0.000145679 0.11071808 0.0007283952
>        2   530  553 0.071184091 0.07939060 0.0711840914
>        3   583  632 0.021902932 0.01748423 0.0365048862
>        4  1122 1177 0.036887884 0.02047984 0.0461098552
>        5  1187 1218 0.016484691 0.09202706 0.0365048862
>        ```
>        
>        
>        Please take the time to familiarize yourself with IRanges and GRanges objects and use them where appropriate in your package. IRanges and GRanges objects are implemented in the **IRanges** and **GenomicRanges** packages, respectively.
> 

dStruct now uses IRanges. See `getContigRegions` and other functions. 

>     2. The first `dStructome()` call in the examples section of `dStructome`'s man page produces many "cannot compute exact p-value with zeroes" warnings (more than 50). Is this expected?
> 

Yes, this is expected. 

>     3. The man pages are too minimalist. The Description section is often a short one-liner that doesn't really provide enough information for the user to get a clue of what the function does. For example: "Calculates d score". But what is a d score? If it's a distance (as suggested by the name of the function `calcDis`) then the man page should say so. If it's not a distance and if the term "score" is more appropriate to describe what it is, then the name of the function should reflect that (good naming is important).

I added more description for all the functions including `calcDis`.

> 
>     4. It's not clear what the purpose of the `two.eight.normalize()` function is or why it is in the package in the first place. Its description in very minimalist, the example in the man page is not particularly illustrative, and  it doesn't seem to be used anywhere. Also why is the naming style of the function (dot-separated words) different from the naming styles of the other functions in the package (most of them follow the camelCaps style)?
> 

I described the purpose of `two.eight.normalize()` in the vignette introduction and the function description, and renamed it as `twoEightNormalize`. 

>     5. More about naming style: all functions in the package follow the camelCaps style except `two.eight.normalize`, `dStruct.guided`, and `plot_dStructurome`. Please use a consistent naming style for all your functions.
> 

All names follow the camelCaps style now.

>     6. Coding style: please use the left arrow (`<-`) instead of `=` for assignments. Make sure to leave a space before and after the `<-`.
> 

Done.

>     7. The `refs.bib` file is in the wrong place: it should be in the `vignettes/` folder. Then you can remove the `inst/extdata/` folder.
> 
> 

I moved `refs.bib` to the `vignettes/` folder and deleted the `inst/extdata/` folder.

Thanks,
K.

**Comment by hpages** [comment]
Hi @dataMaster-Kris ,

Sorry for the delay. Your changes look good, thanks!

H.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dataMaster-Kris.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dStruct")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dStruct

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
