### ISSUE TITLE
PsiNorm submission

### ISSUE THREAD

**Issue by MatteoBlla** [Bioconductor/Contributions#2046]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MatteoBlla/PsiNorm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Hi @MatteoBlla,

This is a very simple normalization method that is implemented using about 5 lines of R code. Maybe it could go in an existing package that already provides normalization methods for raw counts? It seems a little bit hard to justify the introduction of a new package just for that.

Some Bioconductor packages might actually already provide this normalization method. Check **mQTL**, **pcaMethods**, **POMA**, **ropls**, **statTarget**, **structToolbox**, to name a few. If you don't see the _scaling normalization based on the Pareto distribution_ in these packages, you could ask on [our support site](https://support.bioconductor.org/) or [our Community Slack](https://bioc-community.herokuapp.com/). I would be surprised if this method is not already available in Bioconductor.

Thanks,
H.

**Comment by drisso** [comment]
Hi @hpages,

I helped @MatteoBlla writing this package and I was the one who suggested submitting it to Bioconductor.

Although the method is indeed quite simple, to our knowledge it was never applied to single-cell RNA-seq data and it's not implemented in any Bioconductor (or CRAN) package.

Most of the packages that you mentioned (and some others) implement a different scaling, which is called "Pareto scaling", which divides the data by the square root of the standard deviation. Our scaling normalization is different (although just as simple) in that it divides the data by the sum of the log counts. (It's a little more complicated than this but not by much).

Perhaps surprisingly, this simple method is very effective in normalizing single-cell data, more than dividing by the sum of the counts, but, because of its simplicity, it's equally scalable to large datasets, much more so than more complicated methods such as `scran` or `sc_transform` that are popular among practitioners. We have a preprint that compares these methods and shows the pros/cons of the different approaches (https://www.biorxiv.org/content/10.1101/2021.04.07.438822v1.abstract).

Because we've submitted the preprint to a bioinformatics journal, we want our implementation to be more stable than a simple github repo, hence my suggestion to submit a package to Bioconductor.

I realize that this is a very simple package. I'm actually a big fan of small, modular packages, but I understand that in the scope of the Bioconductor project this could be a too minimal package.

If you prefer that we add this function to an existing package, I can certainly add it to the [scone](http://bioconductor.org/packages/release/bioc/html/scone.html) package, which I currently maintain. Given that scone is about normalization of single-cell RNA-seq, I believe that PsiNorm would fit quite nicely in its scope.

I apologize for not thinking about this sooner and for wasting your time with this review. Please, let me know how you prefer that we proceed.

**Comment by drisso** [comment]
Hi @hpages,

can you please advise on how to proceed? Do you want me to add the PsiNorm function to scone and withdraw this package submission? (how do we do that?)

If this is the route, we would like to proceed soon so that PsiNorm makes it to the new release of scone, but I don't want to duplicate the function in two Bioconductor packages.

Thanks!
Davide

**Comment by hpages** [comment]
Hi @drisso ,

Thanks for taking the time to explain and provide some context, and sorry for the late answer.

Yes I also like small well-focused packages. But I also like the **scone** proposal. Sounds like it would be a good place for this new method. But I'm not familiar with the package so I can't really judge that. Another good thing about this proposal is that your group already has full control on the package, so it should be a no-brainer. Can we do that? It's your call, I don't want to push on that.

Thanks,
H.

**Comment by drisso** [comment]
Hi @hpages,

thanks for your flexibility! I agree with you that scone seems a good home for the PsiNorm method and I will add it there.

Please, feel free to close this issue.

Cheers,
Davide
