### ISSUE TITLE
FLAMES

### ISSUE THREAD

**Issue by OliverVoogd** [Bioconductor/Contributions#2049]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/OliverVoogd/FLAMES

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by OliverVoogd** [comment]
Hi @vjcitn, I'm having an issue with the remaining Warning showing in the latest build report from FLAMES. The Warning is that `FLAMES/configure` does not have correct build permissions however, this doesn't affect the completion of the build. I can't find any information on how to correct this warning, as git doesn't seem to track file permissions.
Thanks for your help!

**Comment by vjcitn** [comment]
I am really sorry for the delay in reviewing this package.  The persistence of the warning label bumped it down among priorities.  Now I have read the vignette and I feel it is too brief.  There is very little motivating commentary, and when I travel to the originating github site, the README.md has "Documentation Needed".   The vignette mentions minimap2 with no reference and is completely technical, addressing installation, setup, and execution.  The man page documentation seems too terse -- for example the page for samtools_sort_index says that argument bam_in is a bam file, but it is really character(1) path to a bam file, and likewise for the bam_out parameter.  The "Value" section for that man page reads "the same value as `bam_out`.  The value is a path.  Many of the other man pages could be enhanced by improving the precision of the descriptions of arguments and outputs.  Finally, the `sc_long_pipeline` function is really important and produces a SingleCellExperiment -- and the big picture of getting to this, with references to literature or source sites for key underpinnings of the process, would be the appropriate content of the vignette.   I hope that is helpful and if you have any more questions about the review please let me know.

**Comment by OliverVoogd** [comment]
Hi @vjcitn,
Thanks for reviewing the package.
I've made changes as per your comments:
- The vignette has been extended with a better explanation of the package, as well as references to a pre-print which further details the motivation of the package
- README.md has been re-written and "Documentation Needed" has been removed
- man pages have been reviewed and arguments are now properly typed and explained
- `sc_long_pipeline` has been added as content of the vignette

The package has one error remaining, on riesling1:
```
Warning in file(con, "r") :
  cannot open file 'D:/biocbuild/bbs-3.14-bioc/R/etc/x64/Makeconf': Permission denied
Error in file(con, "r") : cannot open the connection
* removing 'C:/Users/pkgbuild/AppData/Local/Temp/RtmpAVmUJQ/Rinst32ec72241ffa/FLAMES'
```
I'm unsure if this is caused by my package or the build system, and how I can fix it. Any help would be appreciated.

Thanks for your time.

**Comment by suke18** [comment]
> Hi @vjcitn,
> Thanks for reviewing the package.
> I've made changes as per your comments:
> 
> * The vignette has been extended with a better explanation of the package, as well as references to a pre-print which further details the motivation of the package
> * README.md has been re-written and "Documentation Needed" has been removed
> * man pages have been reviewed and arguments are now properly typed and explained
> * `sc_long_pipeline` has been added as content of the vignette
> 
> The package has one error remaining, on riesling1:
> 
> ```
> Warning in file(con, "r") :
>   cannot open file 'D:/biocbuild/bbs-3.14-bioc/R/etc/x64/Makeconf': Permission denied
> Error in file(con, "r") : cannot open the connection
> * removing 'C:/Users/pkgbuild/AppData/Local/Temp/RtmpAVmUJQ/Rinst32ec72241ffa/FLAMES'
> ```
> 
> I'm unsure if this is caused by my package or the build system, and how I can fix it. Any help would be appreciated.
> 
> Thanks for your time.

I am having the same issue here. Any suggestions on what this error is about?

**Comment by hpages** [comment]
There was a file permission issue on our Windows builder. It should be addressed now. Please bump the version of the package to trigger a new build by the SPB. Thanks!

**Comment by vjcitn** [comment]
The error on windows seems idiosyncratic.  Accepting as it succeeds on other platforms, but it would be nice to address the warning regarding Makevars.  Excellent vignette.

**Comment by OliverVoogd** [comment]
Thanks for your help @vjcitn , and @hpages . I'll start looking into the Makevars warning.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/OliverVoogd.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("FLAMES")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FLAMES

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
