### ISSUE TITLE
NeuCA

### ISSUE THREAD

**Issue by haoharryfeng** [Bioconductor/Contributions#2051]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/haoharryfeng/NeuCA

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by vjcitn** [comment]
You'll need networkD3 in Suggests if you use it in vignette.  Please fix errors noted above.

**Comment by haoharryfeng** [comment]
Hi @vjcitn We can't reproduce the TIMEOUT problem on our local machine. We've never seen this issue. Do you have any thoughts/suggestions?

**Comment by vjcitn** [comment]
tensorflow-dependent packages can be tricky.  i am looking at it now

**Comment by vjcitn** [comment]
http://bioconductor.org/spb_reports/NeuCA_buildreport_20210520175412.html#tokay2_check_anchor

seems to show plenty of conditions raised by BiocCheck that you can attend to.  Since the timeout is
specific to windows you might be able to condition some of your tests/vignette sections to complete the check
more quickly on windows

**Comment by vjcitn** [comment]
This is more of an FYI -- I am trying to check your package on an M1 mac and ```/Users/vincentcarey/Library/r-miniconda/envs/r-reticulate/lib/libpython3.7m.dylib - dlopen(/Users/vincentcarey/Library/r-miniconda/envs/r-reticulate/lib/libpython3.7m.dylib, 10): no suitable image found.  Did find:
	/Users/vincentcarey/Library/r-miniconda/envs/r-reticulate/lib/libpython3.7m.dylib: mach-o, but wrong architecture
	/Users/vincentcarey/Library/r-miniconda/envs/r-reticulate/lib/libpython3.7m.dylib: mach-o, but wrong architecture
--- failed re-building ‘NeuCA.Rmd’``` -- the typical approach to installing isn't going to pan out

**Comment by vjcitn** [comment]
I have now been able to build on linux and read your vignette.  1) It would be nice to explain the origins of the Baron and Seg datasets.2) prediction occurs with "one line of code" but what is the relationship between settings of tuning parameters and prediction accuracy?  are there uncertainty measures available for the predictions?  Thank you for your submission.

**Comment by haoharryfeng** [comment]
Hi @vjcitn. We've updated the package as suggested by you: (1) Detailed explanation of Baron and Seg datasets are now included. (2) Section on tuning parameters, model sizes choices, and accuracy has been expanded. Would you take a look and see if NeuCA is acceptable in its current form, please? Thank you for your review.

**Comment by vjcitn** [comment]
Almost there.  The Sankey diagram does not seem to correspond to the preceding confusion matrix (which has only one error in my build of your vignette.)

**Comment by vjcitn** [comment]
Just checking in -- comment on Sankey diagram?  Is it from a different run?

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/haoharryfeng.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NeuCA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NeuCA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
