### ISSUE TITLE
sechm (moved)

### ISSUE THREAD

**Issue by plger** [Bioconductor/Contributions#2057]
The functions included in this package were moved from the _SEtools_ package (and will be afterwards removed from there), so as to increase granularity and reduce dependencies, as suggested by @hpages 

---

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/plger/sechm

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi Pierre-Luc, @plger 
Thank you for your submission. Please see the review below. 

Best,
Marcel

---

# sechm #2057

## DESCRIPTION

* Looks good.

## NAMESPACE

* Looks pretty compact.

## vignettes

* Remove the GitHub installation code upon acceptance.
* Use a more descriptive dataset name rather than `SE`. You could even use the
author's name and year of publication.
* Everyhthing else looks good.


## R

* Avoid using `eval(parse(...))` in `resetAllSechmOptions`. You can simply
list and set them to `NULL`.
* Would `.getDef("assayName")` return the value `assay` in the `switch`
function? These should probably agree to avoid errors.
* It may be better to create a package-wide environment / object for the
various options. See here for an example:
https://github.com/Bioconductor/SOUNDBoard/blob/master/R/zzz.R.
* Deprecations in un-released packages are not usually necessary. If you wish,
you can deprecate arguments with `.Deprecated`.
* Describe what type of data can `ses` contain.
* The code looks quite complicated and the number of arguments in `sechm`
can overwhelm any user. Try to reduce the number of specifiable arguments in
the function calls, if possible.

## tests

* We highly recommend adding unit tests to the package.

## NEWS

* Please add a `NEWS` file.

**Comment by plger** [comment]
Hi @LiNk-NY , thanks for the review and suggestions (neat idea with the package options!), I've included everything I think except i) unit tests, ii) I didn't reduce the arguments (while users typically need only a few of them, I've got many collaborators using the various functionalities regularly...)

**Comment by plger** [comment]
Ok:

**Vignette:**
- _Remove the GitHub installation code upon acceptance._ -> removed from vignette
- _Use a more descriptive dataset name rather than SE._ -> renamed to AuthorYear as suggested

**R:**
- _Avoid using eval(parse(...)) in resetAllSechmOptions._ -> 
- _Would .getDef("assayName") return the value assay ..._ -> corrected to have the same argument name everywhere (thanks)
- _It may be better to create a package-wide environment / object for the various options_ -> did exactly that
- _Deprecations in un-released packages are not usually necessary._ -> it is in this case, since this was moved: I need to nudge users into updating their scripts that were using the same function formerly in `SEtools`. I've however changed it to `.Deprecated` as suggested.
- _Describe what type of data can ses contain._ -> I'll admit I didn't get what you meant there. Could it be that you didn't see it in the `@param` because of the linebreak? Or were you thinking of a more detailed description?
- _Try to reduce the number of specifiable arguments in the function calls_ -> I didn't, I'm afraid we need all of this from time to time (it's still quite small WRT to the underlying `ComplexHeatmap::Heatmap`)

**tests:**
- _We highly recommend adding unit tests to the package._ -> I didn't. It'd be easy to add 2-3 tests just to pretend I've done it, but this doesn't make much sense unless it's done thoroughly, and at the moment I'm afraid I don't have time. But I do aim to get there eventually ;)

**news:**
- _Please add a NEWS file._ -> added

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/plger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sechm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sechm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
