### ISSUE TITLE
awst

### ISSUE THREAD

**Issue by drisso** [Bioconductor/Contributions#2059]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/drisso/awst

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
The package looks very nice.  A few minor comments below: 


**Build Report**

- [ ] Please consider cleaning up the few remaining suggested NOTES.


**DESCRIPTION**

- [ ] Please remove `LazyData: true`

**README**

- [ ] Please include Bioconductor installation instructions

**NEWS.md**

- [ ] I believe in formatting you would still need a list element before `None` to accurately be displayed in the appropriate header section

Cheers.

**Comment by drisso** [comment]
Thanks @lshep for the review!

I'll reply below to the raised points.

> **Build Report**
> 
> * [ ]  Please consider cleaning up the few remaining suggested NOTES.

I fixed most of them. As far as I can tell the remaining NOTEs are related to the width and indentation of the man pages. I'm not sure how to fix them since they are built with roxygen. Is there a specific option that I should use in roxygen to enforce these rules? Otherwise, I'd prefer to keep the note than to change the man pages manually.

There's also a NOTE about BiocViews, but I don't think the suggested views are relevant for my package.

> 
> **DESCRIPTION**
> 
> * [x]  Please remove `LazyData: true`

Done!

> 
> **README**
> 
> * [x]  Please include Bioconductor installation instructions

Done!

> 
> **NEWS.md**
> 
> * [ ]  I believe in formatting you would still need a list element before `None` to accurately be displayed in the appropriate header section

I hope I interpreted your comment in the right way, is the issue fixed in the version 0.99.3? How can I check?

**Comment by lshep** [comment]
Yep everything looks good. thank you

**Comment by drisso** [comment]
Awesome! Thank you @lshep!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/drisso.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("awst")`. The package 'landing page' will be created at

https://bioconductor.org/packages/awst

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
