### ISSUE TITLE
mistyR

### ISSUE THREAD

**Issue by jtanevski** [Bioconductor/Contributions#2060]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saezlab/mistyR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by jtanevski** [comment]
@nturaga the build of the vignettes fails on macOS due to a missing package (hdf5r) that is declared in Suggests. Everything else seems to be in order on other OSs. Can you please check. Thanks.

**Comment by jtanevski** [comment]
Will the HDF5 library be installed on the machv2 or should i address the error by removing the dependence on hdf5r or removing the vignette needing it?

**Comment by nturaga** [comment]
# Review

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

ok

## vignette

- ok

## R

- Instead of magrittr pipes, R has built in pipes which don't require
  you to depend on a new package that look like `|>` if you do insist
  on using pipes.
  
- use these end-user-message functions appropriately

```
message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```

- internal functions the way you are using them are not useful, they
  only make debugging harder. You can just make them explicit
  functions.

## General

- There are NOTEs you need to fix,

```
 NOTE: Usage of dontrun{} / donttest{} found in man page examples.
      44% of man pages use one of these cases.
      Found in the following files:
        add_juxtaview.Rd
        add_paraview.Rd
        add_views.Rd
        collect_results.Rd
        plot_contrast_results.Rd
        remove_views.Rd
        run_misty.Rd
    * NOTE: Use donttest{} instead of dontrun{}.
      Found in the following files:
        add_juxtaview.Rd
        add_paraview.Rd
        add_views.Rd
        collect_results.Rd
        plot_contrast_results.Rd
        remove_views.Rd
        run_misty.Rd
```

- NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

**Comment by jtanevski** [comment]
Dear @nturaga thank you for the review. Hopefully the package can be added to this release. The WARNING on windows is related to the reexporting of the pipe operator as explained below and from what i have read it is known issue and can be ignored. I have addressed your comments as follows:

> ## R
> * Instead of magrittr pipes, R has built in pipes which don't require
>   you to depend on a new package that look like `|>` if you do insist
>   on using pipes.

As outlined in the documentation the package is designed for contructing workflows by chaining functions using a pipe operator.  Since the `|>` operator is a new addition to R since R 4.1.0 i prefer to keep the use of the more well-known operator `%>%`. Another reason is the new pipe passing the current data as the first argument only and cannot be used as a direct argument, which is a feature that i make use of in the package.

Although the original implementation of the pipe operator is in `magrittr` it is reexported in other packages that are imported such as `tibble` and `dplyr`, so i have removed `magrittr` from `Ipmorts` and reexported the pipe operator to facilitate its use.

> * use these end-user-message functions appropriately
> 
> ```
> message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
> warning() communicates unusual situations handled by your code.
> stop() indicates an error condition.
> cat() or print() are used only when displaying an object to the user, e.g., in a show method.
> ```

Fixed.

> * internal functions the way you are using them are not useful, they
>   only make debugging harder. You can just make them explicit
>   functions.

The internal functions are now explicit, documented, but not exported.

> 
> ## General
> * There are NOTEs you need to fix,
> 
> ```
>  NOTE: Usage of dontrun{} / donttest{} found in man page examples.
>       44% of man pages use one of these cases.
>       Found in the following files:
>         add_juxtaview.Rd
>         add_paraview.Rd
>         add_views.Rd
>         collect_results.Rd
>         plot_contrast_results.Rd
>         remove_views.Rd
>         run_misty.Rd
>     * NOTE: Use donttest{} instead of dontrun{}.
>       Found in the following files:
>         add_juxtaview.Rd
>         add_paraview.Rd
>         add_views.Rd
>         collect_results.Rd
>         plot_contrast_results.Rd
>         remove_views.Rd
>         run_misty.Rd
> ```

The `dontrun{}` sections contained alternatives to the use of the function given in the evaluated example to offer users a better understanding. Since the examples are based on a real analysis scenario rerunning in several times would have been very time consuming. These sections are now removed and the NOTE is fixed.


> * NOTE: Consider adding unit tests. We strongly encourage them. See
>   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

I appreciate the suggestion and am working on implementing unit tests. In order to meet the deadline for the package to be hopefully be included in this release of Bioconductor and to produce a better quality tests this NOTE will be properly addressed in the next release.


> * When I run the vignette it creates a large local file called `~/.mistyR`. Is this needed? Are you warning the user before you do this?

Creating a cache directory named `.misty.temp` in the current working directory is a documented feature and is used to reduce computational time when rerunning similar workflows. However, in order to reduce the size of this folder i have changed the default behavior of the functions to not use caching.

**Comment by nturaga** [comment]
Hi,

I've accepted your package, but please add test cases to make sure your package (which is substantial) works the way it's supposed to. 

Test cases are integral to packages. I'll keep my eye out for your package test cases in the coming devel cycle.

Best,

Nitesh

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jtanevski.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mistyR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mistyR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
