### ISSUE TITLE
scanMiR

### ISSUE THREAD

**Issue by fridoling** [Bioconductor/Contributions#2067]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:  https://github.com/ETHZ-INS/scanMiR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by plger** [comment]
Hi @hpages, honored to have you as reviewer ;)
We had initially planned to add a companion `ExperimentData` package to the submission via `AdditionalPackage`, namely https://github.com/ETHZ-INS/scanMiRData , however BiocCheck on `scanMiRData` gives a warning due to the size of some of the RData files (which are ~3, ~8 and ~12 Mb). Each object contains a KdModelList (a class defined by `scanMiR`) containing the affinity data of all miRNAs.
Can we submit this here as a traditional `ExperimentData` package, despite the warning? Or must it be transformed into an ExperimentHub package?
Thanks in advance for the help,
Pierre-Luc & Fridolin

**Comment by hpages** [comment]
Hi @plger ,

I would need to be able to take a look at those files in **scanMiRData** to provide some advice but unfortunately the link you provided doesn't work. Can you fix it?

Thanks,
H.

**Comment by plger** [comment]
sorry @hpages , I thought it was public already... now the link should work

**Comment by hpages** [comment]
Hi @plger ,

scanMiRData_0.99.2.tar.gz is 23M which maybe is a little bit more than what we usually recommend for a data experiment package, so moving the datasets to ExperimentHub would make sense. However it's not crazy big either so we can work with that, at least for now. And since the 3 datasets are serialized instances of a new S4 class that is part of the submission (the KdModelList class), I actually think that it's going to be easier if the datasets live in the data package and not on ExperimentHub. Just in case the design of the S4 class changes during the review process (in which case updating the serialized datasets is going to be easier if they live in the package).

So yes, please submit **scanMiRData** as an additional package.

Thanks,
H.

**Comment by fridoling** [comment]
AdditionalPackage: https://github.com/ETHZ-INS/scanMiRData

**Comment by hpages** [comment]
Hi @fridoling,

Not sure why the SPB didn't provide a build report for additional package **scanMiRData**. On my laptop `R CMD check scanMiRData_0.99.2.tar.gz` produced the following warnings and notes:
```
* using log directory ‘/home/hpages/pkgreviews/scanMiR.expressreview/scanMiRData.Rcheck’
* using R version 4.1.0 beta (2021-05-06 r80268)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘scanMiRData/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘scanMiRData’ version ‘0.99.2’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘scanMiRData’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 23.3Mb
  sub-directories of 1Mb or more:
    data  22.6Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... NOTE
Malformed Title field: should not end in a period.
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
getKdModels: no visible global function definition for ‘data’
Undefined global functions or variables:
  data
Consider adding
  importFrom("utils", "data")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented data sets:
  ‘mmu’ ‘rno’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... WARNING
  
  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
            old_size new_size compress
  hsa.RData   11.1Mb    7.9Mb       xz
  mmu.RData    8.3Mb    5.8Mb       xz
  rno.RData    3.2Mb    2.2Mb       xz
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... NOTE
'library' or 'require' call not declared from: ‘BiocStyle’
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘scanMiRData.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 2 WARNINGs, 4 NOTEs
See
  ‘/home/hpages/pkgreviews/scanMiR.expressreview/scanMiRData.Rcheck/00check.log’
for details.
```
Please address.

Thanks,
H.

**Comment by vjcitn** [comment]
We have a problem with scanMiRData: files are too large for inclusion in git.  @hpages this is the 
precheck phase of admission to moderation for this package.
```
Cloning into 'scanMiRData'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 72 (delta 28), reused 57 (delta 17), pack-reused 0
Receiving objects: 100% (72/72), 45.17 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (28/28), done.
Error in .precheck_filesize(wd) : files larger than 5Mb:
  /data/hsa.RData
  /data/mmu.RData

Enter a frame number, or 0
```

**Comment by hpages** [comment]
@vjcitn @lshep Looks like you were able to add **scanMiRData** to git.bioconductor.org despite the big files. Thanks for that and sorry for the trouble!

@fridoling This is a data package so the terms you put in the `biocViews` field must be offsprings of the `ExperimentData` term e.g. `miRNAData` instead of `miRNA` (the latter is an offspring of the `Software` term). Please refer to the `inst/dot/biocViewsVocab.dot` file in the **biocViews** package for the complete biocViews ontology. I suggest that you add at least the following terms to your `biocViews` field: `ExperimentData`, `Homo_sapiens_Data`, `Mus_musculus_Data`, and `Rattus_norvegicus_Data`.

Also you still need to document the `mmu` and `rno` datasets.

Thanks,
H.

**Comment by plger** [comment]
@hpages we've got a third (and last!) package ( https://github.com/ETHZ-INS/scanMiRApp ) depending on scanMiR. It's the dependency-heavy one, containing wrappers & extras & a shiny app... should we add it here again, or maybe wait for this review to be over and start a fresh new one after?

**Comment by lshep** [comment]
Sorry for the delay.  If it is a related package that uses scanMiR or scanMirData than I would say it is okay to add it here as an AdditionalPackage.  Cheers

**Comment by vjcitn** [comment]
This package is in good shape.  I think it would be good to address BiocCheck events:
```
 [3] "Consider adding these automatically suggested biocViews: Alignment"                                                                                                                
 [4] " Avoid 1:...; use seq_len() or seq_along()"                                                                                                                                        
 ...                                                                                                                                     
 [6] "Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements."                                                                         
 [7] "Consider adding unit tests. We strongly encourage them. See\n  http://bioconductor.org/developers/how-to/unitTesting-guidelines/."  
```
specifically the unit test suggestion is important; if you don't want to do it please indicate why.

**Comment by vjcitn** [comment]
I also took the liberty of trying out the app.   I used the example and was able to generate

```Listening on http://127.0.0.1:7166
Warning: Error in dots_list: argument "subtitle" is missing, with no default
  [No stack trace available]
Warning: The 'plotly_click' event tied a source ID of 'manhattan' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_click')` to the plot (`p`) that you wish to obtain event data from.
'select()' returned 1:1 mapping between keys and columns
```
Do you want to address these?

**Comment by plger** [comment]
@vjcitn the two scanMiRApp warnings are now fixed.
For this one I'll be the maintainer, is that going to create permission conflicts if we add it through this issue? (@fridoling being the scanMiR maintainer... he'll also be addressing your above scanMiR-related queries)
Thanks

**Comment by lshep** [comment]
Honestly, I dont know if a different maintainer on an additionalpackage would cause an issue;  my suspicion is yes we would run into permission issue.  The catch with opening a new issue is if these accompanied packages are not accepted yet and in the official Bioconductor repository then the new issue will not be able to find the dependent package so there may be a delay in reviewing the newly opened issue

**Comment by fridoling** [comment]
@vjcitn we have added "Alignment" to the biocViews, a NEWS file, and unit tests (> 70% code coverage). We have used 1:... only if ranges are defined by hardcoded digits, so this cannot possibly cause any problems.

**Comment by fridoling** [comment]
@lshep Thanks for the info. We are not in a hurry, so we can wait for the review of scanMiR to be finished and then open a new issue.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fridoling.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scanMiR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scanMiR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fridoling.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scanMiRData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scanMiRData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
