### ISSUE TITLE
systemPipeTools

### ISSUE THREAD

**Issue by dcassol** [Bioconductor/Contributions#2071]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/systemPipeR/systemPipeTools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by dcassol** [comment]
Dear @vjcitn, 
On the Windows system, I have the following error, which I can not reproduce locally. Could you please advise? 
```
* creating vignettes ... ERROR
--- re-building 'systemPipeTools.Rmd' using rmarkdown
Quitting from lines 110-113 (systemPipeTools.Rmd) 
Error: processing vignette 'systemPipeTools.Rmd' failed with diagnostics:
error in evaluating the argument 'what' in selecting a method for function 'do.call': object 'combineRows' not found
--- failed re-building 'systemPipeTools.Rmd'
```
On the first build, I didn't have this particular error, I haven't chance anything to affect this. 
I appreciate any information here. 

Thank you very much!
All the best, 
Daniela

**Comment by vjcitn** [comment]
I would wait for some stabilization on the combineRows functionality on the builders.

**Comment by vjcitn** [comment]
Try a version bump and push in a day or two.

**Comment by dcassol** [comment]
Okay, I will do that! Thank you very much!

**Comment by hpages** [comment]
@dcassol @vjcitn The problem was on our side. Many packages (including **S4Vectors**) were lagging behind on tokay2, the machine used by the SPB to build/check packages on Windows. I just went on tokay2 to update all the packages so everything should be current now.

@dcassol Try a version bump and push again. Sorry for the inconvenience.

**Comment by dcassol** [comment]
Thank you, @hpages!

**Comment by vjcitn** [comment]
Sorry that this review has been taking a while.  Here are some basic comments

- look at the output of BiocCheck::BiocCheck and try to take advantage of the suggestions
- from PCAplot
```
    if (all(!methods::is(exploredds) == "DESeqTransform")) {
        warning("'exploredds' needs to be assignes an object of class 'DESeqTransform'.
``` 
i see a spelling error and I wonder if this is a valid use of is(),  which is a function of two arguments -- it is passing check, which is odd, maybe the code never gets called?

- from exploreDDSplot 
```
    if (is.numeric(samples)) {
        samples <- SampleName[samples]
        if (!all(samples %in% SampleName)) {
            stop(paste("samples position can be assigned from the following options",
                paste0(1:length(SampleName),
                    collapse = ", "), sep = " "))}
    } else if (is.character(samples)) {
        if (all(samples == "ALL")) {
            samples <- SampleName
            if (!scattermatrix == "TRUE") stop("'scattermatrix' argument needs
                                               to set as TRUE in the case of ALL
                                               the samples selected.")
        } else {
            samples <- SampleName[samples]
            if (!all(samples %in% SampleName)) {
                stop(paste("samples names can be assigned from the following options",
                    paste0((SampleName),
                        collapse = ", "), sep = " "))}
        }
    }
```

the conditioning is getting pretty deep here and I wonder if this needs to be looked at for simplification

- vignette looks good
- i think we are close with this package so see what you can do in the short term to address some of these concerns.  I ran covr::package_coverage() and it looks like you have reasonable coverage.  but the odd use of is() above is concerning.

**Comment by dcassol** [comment]
Thank you, @vjcitn, for taking the time to review our package. We really appreciate that.

- From `PCAplot`, I replaced all `is(obj)` with `inherit(obj, "className")`. In addition, execution will be interrupted if the wrong object is provided.
- From `exploreDDSplot`, conditioning has been simplified.

Thank you!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dcassol.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("systemPipeTools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/systemPipeTools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
