### ISSUE TITLE
cnAnalysis450k

### ISSUE THREAD

**Issue by mknoll** [Bioconductor/Contributions#208]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mknoll/cnAnalysis450k

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Hi. Please ignore the pdflatex ERROR I believe this is an ERROR on our system.

**Comment by hpages** [comment]
Hi Max,

Thanks for submitting the cnAnalysis450k package. I see 2 important issues at the moment:

1) All the man pages need to have examples illustrating the use of the functions. Right now, the examples contain this single line:
```
print("Please refer to the 'completeWorkflow' vignette!")
```
2) Also please don't use the RGcontrolSetEx data set from the CopyNumber450kData package in your vignette. This data set is currently broken in devel:
```
library(CopyNumber450kData)
RGcontrolSetEx
# class: RGChannelSet 
# Error in nrow(x@elementMetadata) : 
#   no slot of name "elementMetadata" for this object of class "RGChannelSet"
validObject(RGcontrolSetEx)
# Error in slot(from, what) : 
#   no slot of name "colData" for this object of class "RGChannelSet"
```
This issue actually shows up on the [daily build report for CopyNumber450kData](https://bioconductor.org/checkResults/3.5/data-experiment-LATEST/CopyNumber450kData/malbec2-buildsrc.html)

But most importantly the package seems abandoned (we've been trying to contact its maintainers for months without success) so we will likely deprecate it soon. If you really want to use that data set in your vignette, you might want to try to contact the maintainers yourself, maybe you'll have more luck. If they're not interested in continuing the maintenance of CopyNumber450kData maybe you can discuss the possibility that they transfer ownership to you.

I'll have more feedback for you but these 2 important issues would need to be addressed first.

Thanks,
H.

**Comment by mknoll** [comment]
Thanks for the feedback.

1) The CopyNumber450kData package is now removed; datasets for illustions now come from the minfiData and minfiDataEPIC packages.

2) Runnable examples are added for each function. 


Best 
Max

**Comment by lshep** [comment]
Please ignore the Biobase ERROR this is an ERROR on our end that we are working on.

**Comment by hpages** [comment]
Hi Max,

Thanks for your work on cnAnalysis450k. I took a closer look at the package (version 0.99.24). Unfortunately my overall impression is that the package has too many documentation/usability issues at the moment to be included in Bioconductor. It will need a lot of work in this area to reach an acceptable level. See details below.

Cheers,
H.

1. The GenomicFeatures, org.Hs.eg.db, and pheatmap packages are used in the vignette would need to be added to the Suggests field of the DESCRIPTION file.

2. Here is an `R CMD check` warning that would need ot be investigated:
```
* checking package subdirectories ... WARNING
Invalid citation information in ‘inst/CITATION’:
  Error in class(x) <- c("citation", "bibentry"): attempt to set an attribute on NULL
```

3. Several problems with this (in the man page for `createBins()`):
```
 noCores: number of cores for parallelization: needed to pass the cran examples :/
```
  a. Not sure that the "needed to pass the cran examples" part is of interest to the end user.

  b. The name of the argument is quite unconventional and, one could argue, possibly confusing since "noCores" reads as "no cores". I suggest you use a more conventional name for this e.g. 'cores' since you actually pass this value to the 'cores' argument of the `doParallel::registerDoParallel()` function.

  c. The default for `noCores` is -1. Please explain what happens in that case. Is execution linear (i.e. no parallelization at all), or is it still using multiple cores and, if so, how many? It looks to me that you're using all the available cores minus 1 in that case, which 

4. When building the vignette or running the examples on a testing machine, I've observed that sometimes 8 R workers are spawned. Using so much resource in the vignette or examples is not reasonable and will cause problems on our build machines when we run 'R CMD build' and 'R CMD check' in the context of our daily builds. It will also create problems on any server/cluster where someone tries to run the code in the vignette or examples. Please limit the nb of workers to 2 in your vignette and examples.

5. Why is `createBins()` always issuing this warning?
```
  Warning message:
  In createBins(data, ctrl, ctrlAll, binsize = 5e+07, noCores = 2) :
    Might be unstable!
```
  What does it mean exactly? The man page says nothing about the `createBins()` function being "unstable" (whatever that means). More generally speaking, warnings are ok to signal some unusual situations created by some particular combination of user input. But why would a function **unconditionally** issue a warning?

6. Also the warnings I get when running the `runConumee()` example are pretty obscure and confusing:
```
  Warning messages:
  1: In runConumee(samples, ctrl, "segments") :
    This is NOT the original conumee CNV.fit function!
  2: In runConumee(samples, ctrl, "segments") :
    All infinite values are set to NA!
  3: In runConumee(samples, ctrl, "segments") :
    All NA values are substituted using impute.knn from 
              the impute package!
  4: In runConumee(samples, ctrl, "segments") :
    These values have been excluded in the original version!
  5: NaNs produced 
```
  Like the `createBins()` warning, they seem to be unconditional. How can the user make sense of these warnings and what can s/he make of this kind of information? S/he has no control on them. For example the first warning is really surprising: the user is warned about the internal use of a function that is not the original conumee `CNV.fit()` function. But I don't see anything in the documentation that would make me assume that `runConumee()` is using the original function in the first place, so I don't need to be warned that it uses a different function.

7. Documentation of function arguments and returned value is way too minimalist. For example when you document the arguments of a function like here:
```
      data: sample data

      ctrl: control data

   ctrlAll: CN data of all control samples
```
  it's not enough to describe the nature of the data. You also need to explain in what form the data needs to be supplied. In other words, you need to tell the user in what data structure the data needs to be supplied. Is it a vector, a matrix, a data frame, a factor, or any other kind of object? Also what type of vector or matrix (numeric? character? etc...), and what length or dimensions. Should it have names, rownames, colnames? Do they matter? If they matter, what should they be, how is the function going to treat them, etc...

  In some cases, nothing is said at all, not even the nature of the argument. Like here:
```
    data: inputdata
```
  The same applies to the return value. Telling the user that `createBins()` returns:
```
      bins with their corresponding value
```
  doesn't really tell him/her anything it doesn't know by just looking at the name of the function. You need to provide useful information here, including what the value looks like and its relationship with the input.

8. The `findCutoffs()` function has a `zeichne` argument (is that german?) that is FALSE by default. The only thing the man page says about it is:
```
    zeichne: Debugging
```
  But if I set `zeichne` to TRUE, `findCutoffs()` displays a plot! Hopefully I don't need to detail all the things that are wrong with this argument and what it does.

9. Setting `what` to `"transcripts"` instead of `"segments"` when running the `runConumee()` example gives an error:
```
> runConumee(samples, ctrl, "transcripts")
[1] "## Extracting transcripts ..."
using genome annotations from UCSC
getting 450k annotations
 - 470870 probes used
Error in .testForValidKeys(x, keys, keytype, fks) : 
  'keys' must be a character vector
```
I might be doing something wrong but it's hard to know with such an uninformative error message and given the scarcity of the man page.

10. Most functions are just too verbose and what they display doesn't seem very useful. It's just distracting. Please make your functions verbose only when this is actually useful and reduce verbosity to its strict minimum. 

11. Despite its name and what its man page says, the `createConumeeMatrix()` function returns a data.frame, not a matrix:
```
  > m <- createConumeeMatrix(candidatesDATA)
  > class(m)
  [1] "data.frame"
```

12. The `getAnnoData()` function is such a thin wrapper to `minfi::getAnnotation()` that it adds almost no value. It might actually confuse the user. Furthermore, the user doesn't seem to need it (it's not used in the vignette or in the other man pages, it only seems to be used internally). So I would suggest that you don't export it and that you remove its man page.

13. `getTxValuesFast()` seems to only accept transcript names from the UCSC knownGene track for hg19. I know this because I looked at the implementation of `getTxValuesFast()` but the documentation says nothing about that. How do you expect the user to be able to use the function if you don't give him/her this kind of information?

14. But also why impose such an arbitrary choice (the knownGene track) on the user without even telling him/her? The man page only says:
```
    tx: vector of list of transcripts
```
Note that "vector of list" is not accurate. It looks to me that `tx` must be a "vector of UCSC transcript names".

15. When passing transcripts uc001aih.1 and  uc022brq.1 to `getTxValuesFast()` I get:
```
.$data
              smp1   smp2 smp3
uc001aih.1 -1.7825 -2.045   NA

$p.val
uc001aih.1 
0.01288683 

$statistic
[1] "wilcoxon"
```
What happened to the uc022brq.1 transcript?

16. The quality of the 2 vignettes is poor. The 1st vignette (shortWorkflow) is made of 3 lines of introduction followed by a big single block of code followed by an obscure plot. The plot is impossible to understand and has no caption or comment. The 2nd vignette (completeWorkflow) tries to provide more details but has so many problems that it's barely usable. I'll just give an example. Here is the "Data loading" section (1st section):
```
    Data loading

    Idat files can be loaded with read.methyarray() of minfi. This gives
    an RGChannelSet.

      ## Use minfiData example dataset
      dataset <- minfiData::RGsetEx

      ## Setting options('download.file.method.GEOquery'='auto')

      ## Setting options('GEOquery.inmemory.gpl'=FALSE)
```
  Problems:
    a) Illumina’s format is IDAT, not Idat. Case matters.
    b) minfi has no `read.methyarray()` function. I actually don't see any `read.methyarray()` function in Bioconductor.
    c) The 2 lines about Setting GEOquery options are almost certainly going to confuse the reader. I know you didn't put them there but the fact is that they are there and they seriouly hurt the readbillity of the vignette so you need to do something about it.

  I'd rather see a single higher quality vignette.

**Coding style**

17. This is hard to read:
```
data <- data.frame(smp1=c(0,1,1,-1,0),
smp2=c(0,1,0,1,1),
smp3=c(1,1,0,0,0))
rownames(data) <- c("chr1:10000", "chr1:50000", 
"chr1:100000", "chr1:150000", "chr1:200000")
```
Please use proper indentation. It will make your code much easier to read.

18. Don't use this syntax in your examples or vignette:
```
  m <- minfi::getMeth(minfiData::MsetEx[,1])
```
  Instead use `library()` to load any package that you're about to use and just call the function from that package without using the fully qualified form e.g.
```
    library(minfi)
    m <- getMeth(minfiData::MsetEx[,1])
    u <- getUnmeth(minfiData::MsetEx[,1])
```

19. Don't do this inside your own package (`R CMD check` produces a NOTE about this):
```
    anno <- cnAnalysis450k::getAnnoData(arrayType)
```
  Just do:
```
    anno <- getAnnoData(arrayType)
```

**Comment by hpages** [comment]
Hi Max,
Thanks for the improvements to the package. Unfortunately the vignette produces a time out that needs to be addressed. Thanks!
H.

**Comment by hpages** [comment]
Hi Max,
Are you planning to follow up on this submission? If we don't hear back from you in the next couple of weeks, we'll close this issue.
Regards,
H.
