### ISSUE TITLE
MSstatsLOBD

### ISSUE THREAD

**Issue by devonjkohler** [Bioconductor/Contributions#2081]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsLOBD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by devonjkohler** [comment]
Hi I wanted to follow up on this package because it does not seem like it has been reviewed. Has it been accepted or is it still in the queue?

**Comment by nturaga** [comment]
It is yet to be reviewed by me.

**Comment by nturaga** [comment]
# Review

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## vignette

ok

## man 

ok

## test cases

- This needs to be expanded.

## R

- Use `<-` instead of `=` for assignment.

- Fix the NOTEs

```
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        linear_quantlim.R (line 120, column 27)
        nonlinear_quantlim.R (line 135, column 27)
        nonlinear_quantlim.R (line 180, column 33)
        nonlinear_quantlim.R (line 184, column 24)
```

**Comment by devonjkohler** [comment]
I am trying to push an update which fixes the issues in the review but Bioconductor is rejecting the push. Is there something that would be stopping it on your end or is the issue on my end? 

remote: FATAL: W refs/heads/main packages/MSstatsLOBD devonjkohler DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/MSstatsLOBD
 ! [remote rejected] main -> main (hook declined)

**Comment by devonjkohler** [comment]
@nturaga I fixed the code issues you indicated (<- and using seq_along). Our plan for tests is too add more over the medium-long term, I think the baseline testing is generally covered.

**Comment by nturaga** [comment]
Ok, I'll keep an eye out for your updates for the test cases in the coming devel cycle. I'll accept your package for this release, but please make sure to add test cases to make it more robust.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/devonjkohler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsLOBD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsLOBD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
