### ISSUE TITLE
cosmosR

### ISSUE THREAD

**Issue by katharinazirngibl** [Bioconductor/Contributions#2086]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saezlab/cosmosR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Kayla-Morrell** [comment]
@katharinazirngibl - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The 'docs/' directory should be removed, this isn't something we
  allow in Bioconductor packages.

## DESCRIPTION

- [ ] REQUIRED: Since you are using a standard library, you don't need to use
  the LICENSE file and it should be removed.

- [ ] REQUIRED: 'LazyData:' in the DESCRIPTION file should be set to false or
  removed.

## NEWS

- [ ] REQUIRED: It's great practice to include a NEWS file but it looks like
  yours is not formatted properly. Please take a look at our documentation
[here](https://bioconductor.org/developers/package-guidelines/#news) and
reformat the file.

## Vignette

- [ ] REQUIRED: Add an "Installation" section that demonstrates to the user how
  to download the package from Bioconductor. The code should look like the
following and include `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("cosmosR")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] REQUIRED: We don't allow for a figures directory in the man directory. If
  these figures are needed that they should go in 'inst/figures'.

## R code

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` were possible. Found in files:
        display_node_neighborhood.R, lines 49, 56, and 64
        filter_pkn_expressed_genes.R, lines 68 and 71
        format_COSMOS_results.R, lines 34, 47, 66, 159, 252, 332, 339, and 369

- [ ] REQUIRED: Avoid the use of 'paste' in condition signalers. Found in files:
        check_network_data_coverage.R, lines 40 and 55
        cosmos_data.R, lines 140 and 156

- [ ] REQUIRED: Avoid redundancy in signalers. Found in files:
        convert_ensembl_to_entrezid.R, line18

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 294 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line 
indents. There are 497 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@katharinazirngibl - I should have mentioned in my review above to keep in mind that the deadline to accept new packages into the Bioconductor 3.13 release is May 12th. Any packages accepted after this date will be included in the next release.

Best,
Kayla

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/katharinazirngibl.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cosmosR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cosmosR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
