### ISSUE TITLE
Splatter

### ISSUE THREAD

**Issue by lazappi** [Bioconductor/Contributions#209]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Oshlack/splatter/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lazappi** [comment]
The error I got was because I wasn't signed up to the mailing list. I've signed up now, do I need to do anything to trigger a new build?

**Comment by lshep** [comment]
Please make sure your web hook is set up [see instructions](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) and then a version bump would trigger a new build.   For now I'll kick off a build manually. If everything runs without WARNINGS/ERRORS I will begin a formal review of the package; if there are any other ERROR or WARNINGS please correct.  New builds are always triggered with a version bump of the package

**Comment by lshep** [comment]
Please fix all ERROR and WARNINGS.  Please also be advised we currently do not allow package dependencies that are not either on CRAN or Bioconductor (possibly problematic for scDD)

**Comment by lazappi** [comment]
I was hoping the package wouldn't apply to scDD because it is only suggested? If that's not the case I will try and convince the authors to submit it to Bioconductor.

In the mean time I will address the WARNINGS.

**Comment by lshep** [comment]
Yes. Please encourage them to submit their package to Bioconductor

**Comment by lshep** [comment]
scDD has been accepted to Biocondcutor.

**Comment by lshep** [comment]
Please fix any ERRORS or WARNINGS in the package. Once the package can be checked without ERRORS, we will further review for additional Bioconductor best practices.

**Comment by lshep** [comment]
Hello, 
It appears that you never get a build report with a valid push because there are problems running the unit tests (testthat) on windows. Which is causing the R CMD check to stall. 
When it tries to check the unit tests it gets held up and from the logs on our system I traced it down to: 

> test_check("splatter")
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'startup.Rs': No such file or directory
Execution halted


Please investigate into this issue.

**Comment by lshep** [comment]
Thank you for your updates. The package is very close to acceptance.  Some minor suggestions/issues below: 

Vignette: 
- [ ] Thank you for putting Bioconductor download instructions in the README.  We encourage this section to also be in the vignette
```
source("https://bioconductor.org/biocLite.R")
biocLite("Oshlack/splatter", dependencies=TRUE, build_vignettes=TRUE)
```
- [ ] In the Simulating Counts section when you describe the gene by cell info and assayData. There is no description of the counts matrix also provided. 

Random: 
- [ ] Please remove the .Rproj and any other unnecessary top level files/hidden files 
- [ ] Please also note you are just below the requirement for R check to take less than 5 min to complete. No action is required but be cautious of this. 

R/Code: 
- [ ] Please see the following [efficient code reference](http://bioconductor.org/developers/how-to/efficient-code/) .  Of particularly mention, you could make your code more robust using seq_len/seq_along rather than 1:n/1:lengths(x). 
- [ ] Please fix the global variable NOTE for scDatEx .  `?globalVariables` in R might be of use. 


Please comment back here when you are finished making any updates indicating which have been addressed or justification for current implementation. Thank you.

**Comment by lazappi** [comment]
Thank you for your updates. The package is very close to acceptance. Some minor suggestions/issues below:

Vignette:

- [x] Thank you for putting Bioconductor download instructions in the README. We encourage this section to also be in the vignette
```{r}
source("https://bioconductor.org/biocLite.R")
biocLite("Oshlack/splatter", dependencies=TRUE, build_vignettes=TRUE)
```
_**Added Installation section to vignette**_
- [x] In the Simulating Counts section when you describe the gene by cell info and assayData. There is no description of the counts matrix also provided.

_**Added more detail about the counts matrix to this section**_

Random:

- [x] Please remove the .Rproj and any other unnecessary top level files/hidden files

_**Removed .Rproj. I want the other top level files in (eg .travis.yml) in the repository but they should be ignored from the build.**_

- [x] Please also note you are just below the requirement for R check to take less than 5 min to complete. No action is required but be cautious of this.

_**I've taken note of this. There are probably a couple of easy things I could change if it become a problem.**_

R/Code:

- [x] Please see the following efficient code reference . Of particularly mention, you could make your code more robust using seq_len/seq_along rather than 1:n/1:lengths(x).

_**Replaced `1:x` with `seq_len(x)` and `1:length(x)` with `seq_along(x)`**_

- [ ] Please fix the global variable NOTE for scDatEx . `?globalVariables` in R might be of use.

_**I've tried `globalVariables` and a couple of other things but they have caused errors which are worse than the note. I suspect I don't fully understand what is happening. Do you have any suggestions?**_

Please comment back here when you are finished making any updates indicating which have been addressed or justification for current implementation. Thank you.

**Comment by lshep** [comment]
How did you specify the globalVariable and what sort of ERRORS occurred worse than the NOTE?  I know of two possibly ways to correct this NOTE. 

When I add the following 
```
newSCDDParams <- function(...) {
 Your function call
} 

utils::globalVariables("scDatEx")

#' @importFrom checkmate checkInt checkClass checkNumeric
setValidity("SCDDParams", function(object) {

```
It corrects the NOTE and does not cause any ERRORS for me.  
For clarification this NOTE is occurring because there is no `scDatEx`  set in the locale environment before scDatEx is used as the argument in newSCDDParams. scDatEx is set though loading through the utils data and therefore is set but the locale environment doesn't know if this is successful.  The other option then is to initialize scDatEx object in the newSCDDParams functions: 
```
scDatEx = NA
utils::data("scDatEx", package = "scDD", envir = environment())
```

Also, 
If there are a couple of easy things you could do to cut down on the check time we would greatly appreciate if they are implemented in the current version.

**Comment by lazappi** [comment]
I don't remember what the exact errors were but I think they were because I had `globalVariables` in the wrong place. I has initalised `scDatEx` which seems to have fixed the note. Thanks for the tip.

I also set some of the examples to not run which should hopefully reduce the check time.

**Comment by lshep** [comment]
Thank you for making these changes.  Everything looks good now and I will recommend package acceptance.  Please keep the issue open and you will receive svn instructions so that the package will be included in the devel version of Bioconductor (normally within a week).
