### ISSUE TITLE
RTDetect

### ISSUE THREAD

**Issue by jackieduckie** [Bioconductor/Contributions#2098]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PapenfussLab/RTDetect

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Kayla-Morrell** [comment]
@jackieduckie - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION
- [ ] REQUIRED: Please reconsider the amount of packages you have declared as  'Depends:'. These packages provide essential functionality for users of yourpackage. It is unusual for more than three packages to be listed here. If theydon't provide essential functionality I would suggest moving them to the'Imports:' field.
- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field which  includes the relevant link to GitHub for reporting Issues.
## Data
- [ ] REQUIRED: We require documentation for any files in 'inst/extdata'  directory. The documentation should be in an 'inst/script/' directory. Thescripts in this directory can vary. A related script must be present that veryclearly states how the data was generated. It should include source urls and anyimportant information regarding filtering or processing. It can be executablecode, sudo code, or a text description. A user should be able to download thedata and roughly reproduce the file or object that is present as data.
## Vignette
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to  the user how to download and load the package from Bioconductor. The codeshould look like the following and should include `eval = FALSE`.
```{r}if(!requireNamespace("BiocManager", quietly = TRUE))    install.packages("BiocManager")BiocManager::install("RTDetect")```
## R code
- [ ] REQUIRED: It seems that the svaRetro.R file should be changed to reflect  the name of the package.
- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` if possible. Found in files:        eventDetection.R, lines 42, 64, 69, 70, 82, 107, 110, 111, 118, 128, and        134        scoreByTranscripts.R, line 15
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 85 lines that are &gt; 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider 4 spaces instead of tabs.  There are 5 lines that contain tabs.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line indents. There are 24 lines that are not. 

Best,
Kayla

**Comment by jackieduckie** [comment]
Hi @Kayla-Morrell, 

Thank you for your kind comments. I have changed the package name from RTDetect to svaRetro and reopened an issue. Other than that I have addressed all your comments in the latest push to the GitHub repository. Should I close this issue and wait the moderator to update the new issue? 

Kind regards,
Ruining

**Comment by Kayla-Morrell** [comment]
@jackieduckie - Yes, I will close this issue and you can continue the review process on the new issue. You will be assigned a new reviewer and they might have more notes to make about the package, but they will let you know on that issue.

Best,
Kayla
