### ISSUE TITLE
aracne.networks

### ISSUE THREAD

**Issue by federicogiorgi** [Bioconductor/Contributions#21]
Dear all,

I would like to submit a Bioconductor package called aracne.networks. This package contains gene regulatory networks extracted from the biggest cancer dataset ever created (TCGA). These networks are used extensively in pipelines to infer protein activity, already implemented in the viper package, and have been the scaffold for several network-based analyses published over the years from the Califano Lab at Columbia University.

Repository: https://github.com/federicogiorgi/aracne.networks
Confirm the following by editing each check box to '[x]'

 I understand that by submitting my package to Bioconductor,
- [x] the package source and all review commentary are visible to the
general public.

- [x] I have read the Bioconductor Package Submission
instructions. My package is consistent with the Bioconductor
Package Guidelines.

- [x] My package addresses statistical or bioinformatic issues related
to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
includes monitoring the support site for issues that users may
have, subscribing to the bioc-devel mailing list to stay aware
of developments in the Bioconductor community, responding promptly
to requests for updates from the Core team in response to changes in
R or underlying software.

I am familiar with the essential aspects of Bioconductor software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six months, for bug fixes.
- [x] Bioconductor version control using Subversion (optionally via GitHub).
For help with submitting your package, please subscribe and post questions
to the bioc-devel mailing list.

**Comment by federicogiorgi** [comment]
Dear all,

not sure how to proceed now. The only warning I get concerns the size of the package:

> * checking installed package size ... NOTE
>   installed size is 191.3Mb
> 
> * checking data for ASCII and uncompressed saves ... WARNING
>   Note: significantly better compression could be obtained
>         by using R CMD build --resave-data

**Comment by lshep** [comment]
Hello,

You can ignore these WARNINGS for now as this will be an ExperimentalData
package.  We will review your package further and get back to you shortly.

Lori

**Comment by federicogiorgi** [comment]
Thank you so much! Looking forward to hearing from you.

Federico

**Comment by lshep** [comment]
Hi Federico,  

Please see the comments below.  

1. Add an example in aracne.networks-package.Rd

2. Remove static package version/date information in the aracne.networks-package.Rd : duplicated from DESCRIPTION file

3. Please add depends >= R 3.3

4. It seems like the "regulon" class is the class definition and format used in the viper package. We do not want duplicated classes across packages as it can create confusion for the user, duplicate help page entries, and duplicate code. Also when the user loads the data they now have a regulon object to deal with. Any getters/setters/methods viper has defined on the regulon class won't be available unless viper is on the search path; by adding viper to 'depends' these functions do become available and the user can manipulate the object as expected. Please remove the class from your package, move viper to a depends field in DESCRIPTION, and import in the NAMESPACE.

5. Please enhance the value section for the datasets.  "regulon" is not a well-known class and should be better defined as far as object's elements, dimensions, etc. And/or assuming the above is implemented, reference the viper help page \link[viper]{regulon-class}. 

6. It is suggested that you might add in a little detail describing the ARACNe algorithm rather than just including a reference. 

7. It is also suggested that you might enhance the example included in the vignette to show a small workflow to demonstrate how the output from write.regulon() is utlized and truely useful.

8. Please remove the following files from vignettes/
aracne.networks-concordance.tex 
aracne.networks.log 
aracne.networks.pdf
aracne.networks.synctex.gz 
aracne.networks.tex

9. The vignette indicates the data were downloaded on April 15, 2016.  This information should also be included in the man pages. Is there a version associated with the data or just a download date? 

Look forward to hearing from you. 
Cheers, 
Lori

**Comment by lshep** [comment]
Hi Federico,

Thank you for making those changes. The package looks okay now and will be accepted. You should get svn instructions via email in the next couple of days. 
Thank you for your time and effort

Lori

**Comment by federicogiorgi** [comment]
Dear Lori,

no thank YOU for your time and effort :-) I really appreciate your help.

Federico

**Comment by federicogiorgi** [comment]
Dear Lori,

can you please send me the instructions on how to proceed with SVN? No
rush, at your earliest convenience :-)

Federico

**Comment by mtmorgan** [comment]
On 06/23/2016 04:04 PM, federicogiorgi wrote:
> Dear Lori,
>
> can you please send me the instructions on how to proceed with SVN? No
> rush, at your earliest convenience :-)

The instructions will arrive shortly, today or tomorrow. Martin

>
> Federico
>
> On 20 June 2016 at 19:04, Martin Morgan <notifications@github.com> wrote:
>
>  > Closed #21 <https://github.com/Bioconductor/Contributions/issues/21>.
>  >
>  > —
>  > You are receiving this because you were mentioned.
>  > Reply to this email directly, view it on GitHub
>  >
> <https://github.com/Bioconductor/Contributions/issues/21#event-698348882>,
>  > or mute the thread
>  >
> <https://github.com/notifications/unsubscribe/ABVkLDGc0UxNV2i4VsFtiha4p0s0IUYeks5qNxx5gaJpZM4IzZkp>
>  > .
>  >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Bioconductor/Contributions/issues/21#issuecomment-228167174>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAHPGAVvQBbmXbrO_9t8V0XCyqhaUJBYks5qOua8gaJpZM4IzZkp>.
>


This email message may contain legally privileged and/or confidential information.  If you are not the intended recipient(s), or the employee or agent responsible for the delivery of this message to the intended recipient(s), you are hereby notified that any disclosure, copying, distribution, or use of this email message is prohibited.  If you have received this message in error, please notify the sender immediately by e-mail and delete this email message from your computer. Thank you.

**Comment by federicogiorgi** [comment]
Dear Martin,

sorry to bug you again about the aracne.networks package, but you said you
would send the instructions within one or two days :-)

Thanks and sorry again!

Federico
