### ISSUE TITLE
NUMTDetect

### ISSUE THREAD

**Issue by jackieduckie** [Bioconductor/Contributions#2100]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PapenfussLab/NUMTDetect

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi Ruining, @jackieduckie 

Thank you for your submission. Please see the review below. 
Remember to respond to the review line by line. 

Best regards,
Marcel

---

# NUMTDetect #2100

* The package looks good. A few minor changes are requested.

## DESCRIPTION

* Add more details to the `Description` field (at least 3 sentences).
* Add a `BugReports` field.
* Remove the dependency on `covr`. If you need this for `.travis.yml` you can
install the package as a preparation step.

## NAMESPACE

* Looks good.
* Consider using the same case as the package name for your main function.

## vignettes

* We recommend keeping to an 80 character width limit.
* Use `library` calls for loading packages.
* Use chunk options
```
include=TRUE,results="hide",message=FALSE,warning=FALSE
```
to avoid using `suppressPackageStartupMessages` for a single package loading
chunk.
* If you are using an _small_ example `vcf`, please include it in the
`inst/extdata` folder and load it with `system.file`
* Remove commented code.

## R

* For S4 classes, use `methods::is` to test for class membership rather than
`class(x) == "y"`.
* Where possible, use dedicated methods for classes, e.g., `isEmpty(gr)`
instead of `length(gr) > 0`.
* Avoid the use of `sapply` and use `lapply` or `vapply`.
* Remove commented code.
* Use `@keywords internal` for documentation of internal helper functions
(`.mtLen`)

## tests

* You should not need to add tests for `GenomicRanges` objects. The tests
should ensure that all the possible outputs of your functions are tested,
as well as errors, warnings, and messages. This is something to work on
in the long run.

**Comment by LiNk-NY** [comment]
Hi Ruining, @jackieduckie 
Please respond to the review line by line when you're ready. 
Thanks!
-Marcel

**Comment by jackieduckie** [comment]
@LiNk-NY 
Hi Marcel,
Thank you so much for the review. I'm currently addressing your comments and will let you know once it's been finished!
Regards,
Ruining

**Comment by jackieduckie** [comment]
@LiNk-NY 
Hi Marcel,
Hope all is well.
I have addressed all your kind  comments in the current version, but there is one problem. I have changed the package name in the latest push and the automated check returns errors due to the mismatching repository name. Is there a way to change the bioconductor repo name, or should I open a new issue? Thanks in advance for your help.
Regards,
Ruining

**Comment by LiNk-NY** [comment]
Hi Ruining, @jackieduckie 
I am on holiday and I will get back to the review as soon as next week. 
Thanks for your patience. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
Can the maintainer change the package name? 

@jackieduckie I will review the rest of the changes. 

Thanks,
Marcel
