### ISSUE TITLE
fgga

### ISSUE THREAD

**Issue by fspetale** [Bioconductor/Contributions#2103]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fspetale/fgga

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by lshep** [comment]
Please see initial review below: 

**build report**

- [ ] High amount of donttests in man pages?


**NAMESPACE**

- [ ] Do not use `exportPattern("^[[:alpha:]]+")`.  Please selectively export the functions that should be user facing and keep others internal.   


**NEWS**

- [ ] Do not have empty sections. Essentially this is a blank NEWS file. Please populate.  Many choose to do an initial entry of `Submitted to Bioconductor`


**vignette**

- [ ] Why is the code section in 4.2 and 4.3 in an `eval=FALSE`?  it seems quick enough to run the code? 
  

- [ ] Section 4.4, I am not able to run as idsTrain is not exposed to user code anywhere

```
> modelFGGA <- fgga2bipartite(mygraphGO)
> varianceGOs <- varianceGO(tableGOs = CfData[["tableCfGO"]][idsTrain, ], 
+                         dxCharacterized = CfData[["dxCf"]][idsTrain, ], 
+                         kFold = 5, graphGO = mygraphGO, rootNode = rootGO, 
+                         kernelSVM = "radial")
Error in as.matrix(tableGOs[order(rownames(tableGOs)), ]) : 
  object 'idsTrain' not found

```
Please expose the code to correctly make this variable. It seems there is an `include=FALSE` code chunk that has this information.

- [ ] In section 4.5 I can't run the code either

```
> matrixFGGATest <- t(apply(matrixGOTest, MARGIN = 1, FUN = msgFGGA, 
+                         matrixFGGA = modelFGGA, graphGO = mygraphGO,
+                         tmax = 50, epsilon = 0.001))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed
```

- [ ] Since I can't make the above variable, I cannot test that section 5 works or not.


**man pages**

- [ ] We would recommend not having static information in the fgga-package.Rd that often gets forgotten to update

```
\tabular{ll}{
Package: \tab fgga\cr
Type: \tab Package\cr
Version: \tab 0.99.0\cr
Date: \tab 2021-04-06\cr
License: \tab GPL 3.0\cr
LazyLoad: \tab yes\cr

```

- [ ] The example in the donttest doesn't work? That's generally why we don't encourage the use of dontest/dontrun 
```
> fggaResults <- fgga(graphGO = CfData[["graphCfGO"]],
+                     tableGOs = CfData[["tableCfGO"]],
+                     dxCharacterized = dxCfTrainCharacterized,
+                     dxTestCharacterized = dxCfTestCharacterized,
+                     kFold = 5, tmax = 50, epsilon = 0.001)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'nodes' for signature '"matrix"'

```

**R code**

- [ ] In preCoreFG.R Files that are accessed from the web should be cached so that if the website goes down or becomes unavailable users could use already investigated data or a downloaded version of the files.

- [ ] Please use message instead of print so user could potentially silence messages.



Please make changes and when ready do a version bump to trigger a new build report.  Please also comment here on how the above concerns have been addressed.  

Cheers

**Comment by fspetale** [comment]
Thanks @lshep for the review!
I'll reply below to the raised points.

 **build report**

* [x]  High amount of donttests in man pages?
Removed the use of donttests by redesigning the test samples

 **NAMESPACE**

 * [x]  Do not use `exportPattern("^[[:alpha:]]+")`.  Please selectively export the functions that should be user facing and keep others internal.
ExportPattern was removed and the functions that should be user facing and keep others internal were selected

 **NEWS**
 
* [x]  Do not have empty sections. Essentially this is a blank NEWS file. Please populate.  Many choose to do an initial entry of `Submitted to Bioconductor`
The NEWS file was modified based on the suggestion made by the reviewer
 
 **vignette**
 
* [x]  Why is the code section in 4.2 and 4.3 in an `eval=FALSE`?  it seems quick enough to run the code?
Sections 4.2 and 4.3 have been modified and are being evaluated.
* [x]  Section 4.4, I am not able to run as idsTrain is not exposed to user code anywhere
Section 4.1 has been modified and is being evaluated.

* [x]  In section 4.5 I can't run the code either
Section 4.5 has been modified and is being evaluated.  The result of matrixFGGATest is now available because all functions are evaluated in vignette


* [x]  Since I can't make the above variable, I cannot test that section 5 works or not.
Section 5 has been modified and is being evaluated.

**man pages**

* [x]  We would recommend not having static information in the fgga-package.Rd that often gets forgotten to update
Static information has been removed

* [x]  The example in the donttest doesn't work? That's generally why we don't encourage the use of dontest/dontrun
The example was checked and is working. Additionally, the use of donttest was eliminated to check its operation in the package building.

**R code**

* [x]  In preCoreFG.R Files that are accessed from the web should be cached so that if the website goes down or becomes unavailable users could use already investigated data or a downloaded version of the files.
The preCore function was modified to cache GO ontologies that are extracted from the web. This function uses the BiocFileCache package
* [x]  Please use message instead of print so user could potentially silence messages.
The use of print was changed to message

Regards, Flavio
