### ISSUE TITLE
CTCF

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/Contributions#2109]
Repository: https://github.com/mdozmorov/CTCF

This is the AnnotationHub package. The e-mail requesting further instructions and the AWS S3 access has been sent to bioc-devel@r-project.org.

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by lshep** [comment]
Before we continue in the review process a few comments.   biocViews should be from one category either Annotation or Software but not both and only contain valid biocViews (CTCF is not a valid biocView) .   If you run BiocCheck on your package before submission it would catch this (and the previous version numbering issue).  
The placeholder code for man pages and R code should be removed rather than having a dummy function. 
The dev folder also should probably be in a .gitignore and not passed through on a git clone since it seems like biocthis setup information.  
I emailed you additional changes to the metadata file for getting the data files available in the hubs.  
Cheers,

**Comment by mdozmorov** [comment]
- BiocViews- fixed.
- `dev` folder - ignored and removed from the repository.
- metadata - removed CTCF tag, updated BiocVersion to 3.14

The main issue is "The placeholder code for man pages and R code should be removed rather than having a dummy function." If removed, BiocChecks passes but `devtools::check()`generates a warning:
```
checking for unstated dependencies in examples ... WARNING
  no parsed files found
```
It is very difficult to google and it took a while to work out a solution with that placeholder R code. In [this](https://github.com/mdozmorov/CTCF/commit/e10769eb15335e66902128ac28e024ae787b36d3) and the previous commits, I removed the placeholder, the warning is [there](https://github.com/mdozmorov/CTCF/runs/2620104859?check_suite_focus=true#step:22:93), but BiocChecks passes.

**Comment by mdozmorov** [comment]
The `ERROR: Maintainer must add package name to Watched Tags on the support site;` should be fixed. I pushed the version-bumped changes. Also, the README and the vignette were updated to describe how to get the package's data from AHub.

**Comment by LiNk-NY** [comment]
Thank you Mikhail, @mdozmorov 
I am on holiday and will review your package early next week. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 

Thank you for your contribution. Please see the review below. 

Best regards,
Marcel

---

# CTCF #2109

## DESCRIPTION

* Looks good.
* `LazyData: true` is not needed and can be slow with big datasets. Please
remove.

## NAMESPACE

* Empty

## vignettes

* Remove the GitHub installation instructions.
* We discourage the use of external hosting platforms for data. Why can't these
be hosted on `AnnotationHub`?
* Do you need to track the time it takes to build the vignette in the vignette?
* I suggest you use `time R CMD build CTCF`.

**Comment by mdozmorov** [comment]
Thanks, Marcel, learning how to submit a data package. The issues should be fixed now:

- LazyData: true - removed
- Is empty NAMESPACE unacceptable? This is a data package, doesn't have any functions.
- The GitHub installation instructions - removed from the vignette and README
- "discourage the use of external hosting platforms" - the vignette and README describe how to get the data from `AnnotationHub`. I removed the link to the Google Drove folder, it was necessary to get the data to AHub.
- "Do you need to track the time it takes to build the vignette in the vignette" - removed. It was the default in `biocthis`.

These changes are noted in `NEWS.md`. Please, let me know if anything else.
Mikhail

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 

* Yes, it is acceptable to have an empty `NAMESPACE`. 

> "Do you need to track the time it takes to build the vignette in the vignette" - removed. It was the default in biocthis.

That's strange. Perhaps this option should be disabled by default.

Thanks for making the changes. Can you bump the package's `z` version and push upstream? 

Best,
Marcel

**Comment by mdozmorov** [comment]
Done. Noticed two warnings, not sure if they are critical for a data package. 
```
* checking for unstated dependencies in examples ... WARNING
no parsed files found

WARNING: Import AnnotationHub in NAMESPACE as well as DESCRIPTION.
```

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 
Sorry for the delay. `AnnotationHub` should go into the `Suggests` field in the `DESCRIPTION`
as it is only used in the vignettes. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Thanks Mikhail! @mdozmorov

**Comment by mdozmorov** [comment]
Thank you, Marcel! Closing the issue, thanks again! @LiNk-NY 
Mikhail

**Comment by LiNk-NY** [comment]
We will close the issue once it is added to the repository. Thanks!

**Comment by mdozmorov** [comment]
Sorry for the premature closing. Will wait for instructions.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mdozmorov.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CTCF")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CTCF

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
