### ISSUE TITLE
svaRetro

### ISSUE THREAD

**Issue by jackieduckie** [Bioconductor/Contributions#2116]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PapenfussLab/svaRetro

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by jackieduckie** [comment]
Hi there, this is the resubmission of the open issue RTDetect. The changes of this submission include a new name for the package as well as notes from the previous build report.

**Comment by jackieduckie** [comment]
Hi @nturaga,

The package now has passed the checks. Could you please review the package?
Thank you.

-Ruining

**Comment by jackieduckie** [comment]
Dear @nturaga, 
Hope all is well. Just checking if you could provide the initial reviews on the package?
Thank you in advance!

Ruining

**Comment by nturaga** [comment]
# Review

##  General

- The repo is currently on the 'main' branch on Github, instead of the
'master' branch. Please change to master branch, and sync to the
master branch on the bioconductor git repo.

## R CMD build

ok

## R CMD INSTALL 

ok

## DESCRIPTION

- ok, but indentation is off for some.

## NAMESPACE 

ok

## NEWS

ok

## LICENSE

ok

## vignette

- Use BiocStyle to get additional Bioc sytle CSS elements in your
  vignette. It does a lot of the work for you.
  
- Vignette is also very short, it only demonstrates the one exported
  function in the package 'rtDetect'. Please elaborate.
  
## R

- Remove commented out code

- Break up your functions into smaller helper functions. There are
  many chunks of code that are repeated. 'eventDectection.R'
  
- Remember the 80 char limit and try to line wrap to make code more readable. Try to follow this,
  http://bioconductor.org/developers/how-to/coding-style/
    
## tests

- ok

## man

ok

**Comment by jackieduckie** [comment]
Dear @nturaga,

Thanks for your review comments. I've addressed what you've pointed out in the latest push, specially:

- I've moved the repo to the master branch on GitHub and now set as the default branch. 
- Fixed description indentation.
- Switched the vignette output to BiocStyle styled html.
- Cleaned the code by removing the commented code.
- Followed the 80 char limit strictly.
- Modified the vignette, although no big changes.
- Broke down the main function to a series of smaller ones.

Right now the package has one main function, which takes structural variant breakpoints (in GRanges), identifies retrotransposed transcripts (RT), and returns the relevant breakpoints in a list of GRanges. This is about all this package is designed to do, which is an R-based RT detection tool within the Bioconductor environment. All the other functions are internal (not exported), there to assist with the internal ranking and filtering process. 

The vignette in its latest version explains the input and output of the main function with a working example. It also includes an use case on how the output can be integrated in a typical analysis, by demonstrating how to generate a circos plot of a detected RT event. 

Please let me know if further modifications are required. Thanks again!

-Ruining

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jackieduckie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("svaRetro")`. The package 'landing page' will be created at

https://bioconductor.org/packages/svaRetro

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
