### ISSUE TITLE
spatzie

### ISSUE THREAD

**Issue by kkrismer** [Bioconductor/Contributions#2123]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jhammelman/spatzie

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by vjcitn** [comment]
Thank you for this submission.  The vignettes lack prose narration.  Please write a paragraph
of introduction and explanation of the key functions of your package.

**Comment by kkrismer** [comment]
@vjcitn 
Thank you for your feedback and for keeping Bioconductor running!

I added an introduction explaining the objective of the analysis and the data involved, and explained the various steps and the key functions involved, for both vignettes.

**Comment by vjcitn** [comment]
Please look at these outputs of BiocCheck run on Bioc 3.14 in R 4.1 and rectify those
you can.  The LazyData prescription could be ignored if you use spatzie::[dataset] in 
code.  I want to look further into that BiocCheck note.
 
[1] "'LazyData:' in the 'DESCRIPTION' should be set to false or removed"                                                                                                                
 [2] "Update R version dependency from 4.0 to 4.1."                                                                                                                                      
 [3] "Consider adding these automatically suggested biocViews: Transcription, CRISPR"                                                                                                    
 [4] " 'sessionInfo' not found in vignette(s)"                                                                                                                                           
 [5] "Recommended function length <= 50 lines."                                                                                                                                          
 [6] "Consider adding runnable examples to the following man pages which document exported objects:"                                                                                     
 [7] "Usage of dontrun{} / donttest{} found in man page examples."                                                                                                                       
 [8] "Use donttest{} instead of dontrun{}."                                                                                                                                              
 [9] "Consider shorter lines; 34 lines (2%) are > 80 characters long."                                                                                                                   
[10] "Consider multiples of 4 spaces for line indents, 318 lines(15%) are not."

**Comment by kkrismer** [comment]
```[1] "'LazyData:' in the 'DESCRIPTION' should be set to false or removed"```

I follow Hadley Wickham's recommendation (https://r-pkgs.org/data.html). Not sure what the philosophy behind that BiocCheck rule is, but since my data objects are only used in examples and unit tests, I figured it's better to load them lazily?

```[2] "Update R version dependency from 4.0 to 4.1."```

Done.

```[3] "Consider adding these automatically suggested biocViews: Transcription, CRISPR"```

I added 'Transcription'. 'CRISPR' is not a valid suggestion in this case.

```[4] " 'sessionInfo' not found in vignette(s)"```

Done.

```[5] "Recommended function length <= 50 lines."```

The 50 lines are exceeded in three cases and I'd argue refactoring these functions would not improve readability.

```
[6] "Consider adding runnable examples to the following man pages which document exported objects:"
[7] "Usage of dontrun{} / donttest{} found in man page examples."
[8] "Use donttest{} instead of dontrun{}."
```

I use `dontrun` in some examples to skip examples with long run times. I can't use `donttest` because of the newly introduced behavior of executing `donttest` blocks. I provide runnable examples wherever possible.

```[9] "Consider shorter lines; 34 lines (2%) are > 80 characters long."```

Reflowing these lines is either impossible (long package names) or undesirable (readability issues).

```[10] "Consider multiples of 4 spaces for line indents, 318 lines(15%) are not."```

These lines are aligned to function calls or definitions, i.e., the indentation is intentional.

Thanks again for your feedback!

About the errors/warnings from before, they were due to issues on the Bioconductor build server, thus unrelated to the code changes.

**Comment by vjcitn** [comment]
Thanks for the update.  I still feel the vignette "single-call" could use some explanation.  For example, the
concluding heatmap suggests that YY1 motif coenrichment is stronger with AP2.1 than with YY1.  Is this
because you are using a "toy" motif database?  Read the vignette like a user coming in cold and try to 
remedy basic puzzlement.  I will look at the other vignette now.

**Comment by vjcitn** [comment]
Still pretty terse in the individual steps.  Be sure any necessary references are available.  For example, HOCOMOCO, and the spatzie paper, could be clearly referenced in the vignette to save reader the
work of hunting around for them.

**Comment by kkrismer** [comment]
@vjcitn 

Thanks for your valuable feedback!

I've improved the vignettes by adding references to relevant papers, a link to the spatzie paper and website, additional explanations for individual steps, and a paragraph about the spatzie results, including a note that the motif database and the interactions data used in the vignette are only meant for demonstration purposes.

About the build error, these are again related to temporary issues on the Bioconductor build servers and not the code changes (there were none) - I suspect that the package cache on the build server is corrupt (e.g., `package 'S4Vectors' required by 'GenomicRanges' could not be found`).

**Comment by kkrismer** [comment]
The only purpose of this last commit was to trigger a new build on the Bioconductor server to remove the wrong error label, see previous comment.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kkrismer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spatzie")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spatzie

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
