### ISSUE TITLE
m6Aboost

### ISSUE THREAD

**Issue by Codezy99** [Bioconductor/Contributions#2126]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ZarnackGroup/m6Aboost

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by Codezy99** [comment]
Dear Bioc team,

I have made a clone of git@git.bioconductor.org:packages/m6Aboost in my Rstudio with the Git verson control. I was wondering if I can directly commit the changes and trigger the new build in this way. 

Besides, I met some problem with "X11 forwarding request failed on channel 0". My working system is MacOS 11.4. I have tried all the possible solution on the internet but none of them work. I was wondering if I can not directly commit changes in Rstudio whether you would have any suggest for me to fix this problem. Thank you so much for your help.

Best regards,
You Zhou

**Comment by Codezy99** [comment]
Dear Marcel,

I have pushed the changes back to git@git.bioconductor.org:packages/m6Aboost. But I did not see the build process occur. I was wondering whether you could help me to check what is going wrong there. Thank you~

Best regards,
You Zhou

**Comment by LiNk-NY** [comment]
Hi You, @Codezy99 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# m6Aboost #2126

## DESCRIPTION

* Looks good.
* Perhaps define what miCLIP2 data is in the `Description` field.

## NAMESPACE

* Looks good.
* Consider using a more descriptive function name for `getFeatures`.

## vignettes

* Good introduction.
* Please remove the GitHub installation code and use the `BiocManager`
conditional code found on package landing pages when accepted.

## R

* Why not use `rowData` instead of `getFeatures`. The description says that
the function is not only extracting the features but also doing some
calculations. Perhaps these steps should be separated.
* What is the reason for using code conditional to Windows OS?
* Why not use a logical to define whether the peak would overlap in
`.assignment`? It would be easier to work with down the line, e.g., simply
having `object %over% UTR3`.
* You don't need `isTRUE` for inputs that will be evaluated to logical, e.g.,
in `isTRUE(!colname_reads %in% meta_name)` in the `getFeatures` method.
* Remove any old commented code.
* Avoid creating methods for classes that are not your own to avoid polluting
the class's methods environment. `m6Aboost` and `truncationAssignment` can be
plain functions that take `GRanges` as input.

## tests

* Looks good.

## README.md

* Please provide a more substantial description of the package

**Comment by Codezy99** [comment]
Hi Marcel, thank you for all these nice suggestions : ) Here are the changes that I made for the package.

# DESCRIPTION
* Looks good.
* Perhaps define what miCLIP2 data is in the Description field. 
>> I added one sentence about the data should store in a Granges object. And user can find more detail in the vignette.
# NAMESPACE
* Looks good.
* Consider using a more descriptive function name for getFeatures.
>> The feature here represents the features that use to train the machine learning model. And `getFeatures` means getting all the features that required by the model. Now I change the name of this function to `preparingData`, I was wondering whether this name would be a bit more intuitive. 
# vignettes
* Good introduction.
* Please remove the GitHub installation code and use the BiocManager conditional code found on package landing pages when accepted.
>> I have changed the installation to BiocManager conditional code.
# R
* Why not use rowData instead of getFeatures. The description says that the function is not only extracting the features but also doing some calculations. Perhaps these steps should be separated.
>> The features here represents the features that required by our model m6Aboost. From my side, I would like to reduce the steps for running the package and keep the package easy to use. So I am not sure whether is necessary to split this function into two.
* What is the reason for using code conditional to Windows OS?
>> Actually, I met a windows only bug which looks like this way:

>     test <- CtoTAssignment(test, bw_positive=ctotBw_p, bw_negative=ctotBw_n,
>        sampleName = "CtoT_WT1")
>Warning in .local(con, format, text, ...) :
>  Invalid argument
>lseek(5, 366, invalid 'whence' value (1822621639)) failed
>Error in .local(con, format, text, ...) : UCSC library operation failed
>Calls: CtoTAssignment ... import -> import -> import -> import -> .local -> .Call
>Execution halted
>** running examples for arch 'x64' ... [35s] OK
>Examples with CPU (user + system) or elapsed time > 5s
>        user system elapsed
>m6Aboost 10.7   1.13   12.42
>* checking for unstated dependencies in 'tests' ... OK
>* checking tests ...
>** running tests for arch 'i386' ...
 > Running 'testthat.R' [31s]
 >[31s] ERROR
>Running the tests in 'tests/testthat.R' failed.
>Last 20 lines of output:
>   7.       \-BiocIO::import(con, "BigWig", ...)
>  8.         +-BiocIO::import(FileForFormat(con, format), ...)
>    9.         \-rtracklayer::import(FileForFormat(con, format), ...)
>  10.           \-rtracklayer:::.local(con, format, text, ...)
>  -- Error (test_truncationAssignment.R:9:5): truncationAssignment works as expected --
> Error: UCSC library operation failed
>  Backtrace:
>       x
>    1. +-m6Aboost::truncationAssignment(...) test_truncationAssignment.R:9:4
>    2. \-m6Aboost::truncationAssignment(...)
>    3.   \-m6Aboost:::.readBW(bw_positive, bw_negative)
>    4.     +-rtracklayer::import.bw(con = file_N)
>    5.     \-rtracklayer::import.bw(con = file_N)
>    6.       +-BiocIO::import(con, "BigWig", ...)
>    7.       \-BiocIO::import(con, "BigWig", ...)
>    8.         +-BiocIO::import(FileForFormat(con, format), ...)
>    9.         \-rtracklayer::import(FileForFormat(con, format), ...)
>   10.           \-rtracklayer:::.local(con, format, text, ...)
I tested the package on my windows machine, and it does not report me any error like this. Then I googled it and found the maintainer of “karyoplotR” also met this issue. This issue seems to relate to “rtracklayer” import function in windows. The conditional code that I used is the solution in “karyoplotR” package. 
* Why not use a logical to define whether the peak would overlap in .assignment? It would be easier to work with down the line, e.g., simply having object %over% UTR3.
>> That is a good point thank you. But since the model has already finished and published, the input for each feature is fixed. That means the model can only take YES/NO as input. But I think I will do it next time : )
* You don't need isTRUE for inputs that will be evaluated to logical, e.g., in isTRUE(!colname_reads %in% meta_name) in the getFeatures method.
>> Thank you for the suggestion. I have corrected this issue.
* Remove any old commented code.
>> The old code has been removed now.
* Avoid creating methods for classes that are not your own to avoid polluting the class's methods environment. m6Aboost and truncationAssignment can be plain functions that take GRanges as input.
>> Thank you for the suggestion. Since all the function within m6Aboost take GRanges as input, I change all the function back to plain function.
# tests
* Looks good.
# README.md
* Please provide a more substantial description of the package
>> The README file has now improved.

**Comment by LiNk-NY** [comment]
Hi You, @Codezy99 

Thanks for making those changes. Here is some commentary to your responses.

>> The features here represents the features that required by our model m6Aboost. From my side, I would like to reduce the steps for running the package and keep the package easy to use. So I am not sure whether is necessary to split this function into two.

It looks like changing the name will suffice. 

> I tested the package on my windows machine, and it does not report me any error like this. Then I googled it and found the maintainer of “karyoplotR” also met this issue. This issue seems to relate to “rtracklayer” import function in windows. The conditional code that I used is the solution in “karyoplotR” package.

Perhaps open / review the issues in https://github.com/lawremi/rtracklayer/ and see if there are any that are related, otherwise ping the maintainer for a fix. 

Best,
Marcel

**Comment by Codezy99** [comment]
Hi Marcel, @LiNk-NY 

I will open an issue in rtracklayer to check whether the maintainer could help to fix this problem. Thank you : )

Best,
You

**Comment by LiNk-NY** [comment]
Thank you for your contribution. 
Best,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Codezy99.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("m6Aboost")`. The package 'landing page' will be created at

https://bioconductor.org/packages/m6Aboost

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
