### ISSUE TITLE
metapone

### ISSUE THREAD

**Issue by tianwei-yu** [Bioconductor/Contributions#2131]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tianwei-yu/metapone

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by lshep** [comment]
Please updates ERROR, WARNINGS, and NOTES from the report before an in-depth review proceeds.  Thank you

**Comment by lshep** [comment]
Thank you for your submission. please find the initial review below: 

**General**

  Currently the package does not show much interoperability for Bioconductor classes and structure nor does it use existing
  Bioconductor functionality for parallelization (BiocParallel).  

**Build Report**

- [ ] Please fix all NOTES of the build report

**DESCRIPTION**

- [ ] See notes from build report

**data/man**

- [ ] There is no information on how the neg or pos data was generated? And it is not well documented in the vignette either; if they are outcomes of data it should be documented, if they are simulated data then how it was generated selected should be made more clear. 
- [ ]  There should be more explanation on how all the data was generated. The the data man pages are minimal. It would be helpful to not only describe the structure of the data object but any filters, specifications, etc..  There is no real detail on the source information provided. What it is? How its used? 

**inst**

- [ ] All vignettes should be in the vignette directory and not inst/doc/. Please git remove. 

**vignette**

- [ ] Based on the README and vignette which seem the same, you should create accessor methods for different parts of your results object rather than using the `@` directly.

- [ ] The vignette is very superficial.  Please explain more about what your package accomplishes and how it is different from other applications.  
  
- [ ] Again pos and neg are not well defined or clear if it is outcome of real experiments or if they are simulated.

- [ ] The table at the end of the vignette is too big and does not display properly. Consider truncating and formatting.

- [ ] What are SMPDB and mummichog. There are no references or explanation.

- [ ] It would be useful to show how other existing Bioconductor packages would fit into using your package. 

**R/man**

- [ ] Generally we like to see formalized S4 classes rather than S3 classes.

- [ ] Use BiocParallel instead of generic parallelization.

- [ ] Are there any exisiting Bioconductor classes and structures that could be utilized?
  

Please address the above issues.  When ready please comment back here with explanations and how the above concerns have been addressed and kick off a version bump in the description to trigger a new build.  Thank you.

**Comment by lshep** [comment]
Checking in. Do you plan on submitting any updates soon?  We like to see progress within 2-3 weeks.

**Comment by tianwei-yu** [comment]
Dear Ms. Shepherd,

Sorry I missed the previous deadline for revising my package, and the issue was closed. Now I cannot find a way to submit the revised package. Could you re-open the issue? Many thanks!

Best,
Tianwei

**Comment by lshep** [comment]
Please let me know when you are ready for a re-review and please comment on the initial review items and how they were addressed.

**Comment by tianwei-yu** [comment]
Sorry for forgetting to send the response to the comments. 

General
Currently the package does not show much interoperability for Bioconductor classes and structure nor does it use existing Bioconductor functionality for parallelization (BiocParallel).
Build Report
•	[] Please fix all NOTES of the build report
We still have some notes from BiocCheck, mostly about line length etc. Do we need to change code to get rid of all the notes?
DESCRIPTION
•	[X] See notes from build report
data/man
•	[X] There is no information on how the neg or pos data was generated? And it is not well documented in the vignette either; if they are outcomes of data it should be documented, if they are simulated data then how it was generated selected should be made more clear.
We have added the source information. It’s from a recent paper. 
•	[X] There should be more explanation on how all the data was generated. The the data man pages are minimal. It would be helpful to not only describe the structure of the data object but any filters, specifications, etc.. There is no real detail on the source information provided. What it is? How its used?
We added the information about data generation in the Rd files. 
inst
•	[X] All vignettes should be in the vignette directory and not inst/doc/. Please git remove.
Done.
vignette
•	[X] Based on the README and vignette which seem the same, you should create accessor methods for different parts of your results object rather than using the @ directly.
We added S4 methods to access the data. 
•	[X] The vignette is very superficial. Please explain more about what your package accomplishes and how it is different from other applications.
We added explanations to the package in the vignette.
•	[X] Again pos and neg are not well defined or clear if it is outcome of real experiments or if they are simulated.
We added description to the Rd files.
•	[X] The table at the end of the vignette is too big and does not display properly. Consider truncating and formatting.
We have changed the vignette to display a subset of the information. 
•	[X] What are SMPDB and mummichog. There are no references or explanation.
We added the reference website to the Rd and README files. 
•	[X] It would be useful to show how other existing Bioconductor packages would fit into using your package.
We explained more about what data structure is needed by our method. It’s pretty generic. Essentially any testing / regression output can be formatted easily to use the package. 
R/man
•	[X] Generally we like to see formalized S4 classes rather than S3 classes.
We have changed to S4.
•	[ ] Use BiocParallel instead of generic parallelization.
We have changed to BiocParallel.
•	[X] Are there any exisiting Bioconductor classes and structures that could be utilized?
Unfortunately the method cannot use an existing structure, as it uses new fractional count approach.

**Comment by tianwei-yu** [comment]
Sorry for forgetting to post the response to comments. Please see below.

General
Currently the package does not show much interoperability for Bioconductor classes and structure nor does it use existing Bioconductor functionality for parallelization (BiocParallel).
Build Report
•	[] Please fix all NOTES of the build report
We still have some notes from BiocCheck, mostly about line length etc. Do we need to change code to get rid of all the notes?
DESCRIPTION
•	[X] See notes from build report
data/man
•	[X] There is no information on how the neg or pos data was generated? And it is not well documented in the vignette either; if they are outcomes of data it should be documented, if they are simulated data then how it was generated selected should be made more clear.
We have added the source information. It’s from a recent paper. 
•	[X] There should be more explanation on how all the data was generated. The the data man pages are minimal. It would be helpful to not only describe the structure of the data object but any filters, specifications, etc.. There is no real detail on the source information provided. What it is? How its used?
We added the information about data generation in the Rd files. 
inst
•	[X] All vignettes should be in the vignette directory and not inst/doc/. Please git remove.
Done.
vignette
•	[X] Based on the README and vignette which seem the same, you should create accessor methods for different parts of your results object rather than using the @ directly.
We added S4 methods to access the data. 
•	[X] The vignette is very superficial. Please explain more about what your package accomplishes and how it is different from other applications.
We added explanations to the package in the vignette.
•	[X] Again pos and neg are not well defined or clear if it is outcome of real experiments or if they are simulated.
We added description to the Rd files.
•	[X] The table at the end of the vignette is too big and does not display properly. Consider truncating and formatting.
We have changed the vignette to display a subset of the information. 
•	[X] What are SMPDB and mummichog. There are no references or explanation.
We added the reference website to the Rd and README files. 
•	[X] It would be useful to show how other existing Bioconductor packages would fit into using your package.
We explained more about what data structure is needed by our method. It’s pretty generic. Essentially any testing / regression output can be formatted easily to use the package. 
R/man
•	[X] Generally we like to see formalized S4 classes rather than S3 classes.
We have changed to S4.
•	[X] Use BiocParallel instead of generic parallelization.
We have changed to BiocParallel.
•	[X] Are there any exisiting Bioconductor classes and structures that could be utilized?
Unfortunately the method cannot use an existing structure, as it uses new fractional count approach.

**Comment by lshep** [comment]
Thank you for your changes.  Some final comments: 

**Build Report Notes**

We can make some exceptions for some notes. There are some that are still
recommended

- [ ] Adding a `sessionInfo()` section to the bottom of the vignette

- [ ] Adding a NEWS file. While this is optional. If metaphone makes future
  updates, they will not be included in the Bioconductor release announcement
  without a news file.  see example [release
  announcement](http://bioconductor.org/news/bioc_3_13_release/)

- [ ] We strongly recommend unit tests to test proper functionality of the
  package. If all functions have executable examples in either vignette or man
  page there can be exception.


These however, do not hinder package acceptance and are only recommended.  Cheers

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tianwei-yu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metapone")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metapone

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
