### ISSUE TITLE
COTAN

### ISSUE THREAD

**Issue by seriph78** [Bioconductor/Contributions#2151]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/seriph78/COTAN

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by seriph78** [comment]
Hi,
I'm trying to fix my release on the Windows server. Last push gives me this error

Windows Server 2019 Standard/x64	  WARNINGS  	  ERROR  	  OK  	  OK  

 but when I check the details I found: 

Error: Your current architecture is 32bit; however, this version of Python was compiled for 64bit.
  Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.

I'm missing something or the problem is not my package but the installation of windows server? Because, from what I understood from the first line the machine is a x64 architecture but python is compiled for a x32... am I wrong?

The warning was one
Warning: file 'COTAN/configure' did not have execute permissions: corrected

So I think that I just need to wait... 

Thanks in advance for the help

**Comment by seriph78** [comment]
Dear @nturaga ,

I modified the permissions on my server and it looks fine... 
-rwxrwxr-x  1 seriph seriph   70 lug  4 17:15 configure
-rwxrwxr-x  1 seriph seriph   87 lug  4 17:15 configure.win

Where do you think still the problem?

Best regards

**Comment by nturaga** [comment]
Hi, 

Please take a closer look at the build reports you have. There are several NOTE issues that need to be addressed 

```
 * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        COTAN_main.R (line 70, column 31)
        COTAN_main.R (line 71, column 31)
        COTAN_main.R (line 74, column 31)
        COTAN_main.R (line 213, column 25)
        COTAN_main.R (line 930, column 38)
        COTAN_main.R (line 997, column 37)
        COTAN_main.R (line 1222, column 60)
        internal_functions.R (line 201, column 50)
    * NOTE: Avoid the use of 'paste' in condition signals
      Found in files:
        /tmp/Rtmplxkda9/file52edf720a03ff/COTAN/R/COTAN_main.R (line
      1384, column 24)
        /tmp/Rtmplxkda9/file52edf720a03ff/COTAN/R/internal_functions.R
      (line 343, column 24)
    * NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions
      Found in files:
        /tmp/Rtmplxkda9/file52edf720a03ff/COTAN/R/COTAN_main.R (line
      433, column 28)
        /tmp/Rtmplxkda9/file52edf720a03ff/COTAN/R/COTAN_main.R (line
      1360, column 24)
        /tmp/Rtmplxkda9/file52edf720a03ff/COTAN/R/COTAN_main.R (line
      1384, column 30)
        /tmp/Rtmplxkda9/file52edf720a03ff/COTAN/R/internal_functions.R
      (line 343, column 30)
```

and

```
* Checking parsed R code in R directory, examples, vignettes...
    Found @ in man/get.expected.ct.Rd
    Found @ in man/get.gene.coexpression.space.Rd
    Found @ in man/get.observed.ct.Rd
    Found @ in vignettes/Guided_tutorial.Rmd
    * NOTE: Use accessors; don't access S4 class slots via '@' in
      examples/vignettes.
```


Although these are NOTE messages and not WARNING or ERROR, they are still important. 

Please fix and issue a new build report.  We are looking into the Windows issue you have encountered, it is most likely identified already. Please try again.

**Comment by seriph78** [comment]
All notes are fixed. Now only the warning regarding the execute permissions for the configure file remains .

**Comment by seriph78** [comment]
Dear @nturaga do I have to built another version to consider the last warning? As already mention, it does not seems to be a package problem but a problem regarding the windows compiler.... I think...

**Comment by nturaga** [comment]
Yes. Please.

**Comment by seriph78** [comment]
Dear @nturaga I fixed everything except the warning: "file 'COTAN/configure' did not have execute permissions" that I don't think depend on my code... Is it now ok? 

Best regards

**Comment by nturaga** [comment]
Hi @seriph78 Yes, this is much better. I will review your package now. 

Best

**Comment by nturaga** [comment]
# COTAN review

General	comments: Please note the release schedule that is posted here -\
 http://bioconductor.org/developers/release-schedule/.

We'll try to get your package in before	that.

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* ok

## NAMESPACE

ok

## R

* NOTE: Use donttest{} instead of dontrun{}.

* Remove commented out code.

* Use `<-` for assignment and not `=`.

## Vignette

- Use BiocStyle

**Comment by lshep** [comment]
@seriph78  may we expect to see updates soon?  We like to see progress and response to review within 3-4 weeks.

**Comment by seriph78** [comment]
Sorry. Now I will have time to work on it again... Posting here automatically reopen the issue or I should create a new issue?

**Comment by seriph78** [comment]
Perfect. Thanks!

**Comment by seriph78** [comment]
Hi, as usual there is "Warning: file 'COTAN/configure' did not have execute permissions: corrected" also if the file already has the right permissions,

**Comment by seriph78** [comment]
Sorry, may be I missed something I don't see COTAN anywhere in Bioconductor website. Do I need to do something?

**Comment by lshep** [comment]
I will be running the processing script for accepted packages this afternoon. Once that occurs, it should appear in devel within 24-48 hours.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/seriph78.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("COTAN")`. The package 'landing page' will be created at

https://bioconductor.org/packages/COTAN

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
