### ISSUE TITLE
methylclock package

### ISSUE THREAD

**Issue by dpelegri** [Bioconductor/Contributions#2159]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isglobal-brge/methylclock

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by dpelegri** [comment]
Hello,

I'm trying to update the changes in Bioconductor git but I get an error


```
git push upstream RELEASE_3_13
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 497 bytes | 497.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: FATAL: W refs/heads/RELEASE_3_13 packages/methylclock dpelegri DENIED by fallthru
remote: error: hook declined to update refs/heads/RELEASE_3_13
To git.bioconductor.org:packages/methylclock.git
 ! [remote rejected] RELEASE_3_13 -> RELEASE_3_13 (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/methylclock.git'
```

my current branch is RELEASE_3_13, I try to create a new branch RELEASE_3_14  with the same content and I have tried  updating the data but I get the same error. I don't know why it gives me this error, a few days ago I uploaded it without problems.

Thanks,

Dolors

**Comment by lshep** [comment]
This package is yet to be in Bioconductor.  Therefore the RELEASE_3_13 branch does not exist on git.bioconductor.org and will not as it will be submitted under RELEASE_3_14.  Until the official release in fall, the RELEASE_3_14 branch also does not exist, this branch is considered the devel branch of Bioconductor and uses master branch for pushes.

**Comment by dpelegri** [comment]
I changed the branch name to master and all works ok.  
Thanks

**Comment by dpelegri** [comment]
Hello,

I'm getting errors in windows and mac compilation and I don't know why

In **Mac** : 

```
Quitting from lines 124-128 (methylclock.Rmd) 
Error: processing vignette 'methylclock.Rmd' failed with diagnostics:
could not find function "get_TestDataset"
--- failed re-building methylclock.Rmd

SUMMARY: processing the following file failed:
  methylclock.Rmd

Error: Vignette re-building failed.
Execution halted
```

The same vignette works fine when I compile it on linux. The `get_TestDataset` function refers to a function from the methylclockData package just loaded. I don't understand why it can be found on Linux and not on mac.

**Windows** : 
```
make: D:/biocbuild/bbs-3.14-bioc/R/etc/x64/Makeconf: Permission denied
g++    -c -o NewModel1Clean.o NewModel1Clean.cpp
NewModel1Clean.cpp:9:10: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
          ^~~~~~~~
compilation terminated.
make: *** [<builtin>: NewModel1Clean.o] Error 1
ERROR: compilation failed for package 'methylclock'
* removing 'C:/Users/pkgbuild/AppData/Local/Temp/RtmpWqw8Ac/Rinst4287ef767/methylclock'
      -----------------------------------
ERROR: package installation failed
```

This errors seems to be from the server, i get the error : "Permission denied" and can't find the  `Rcpp.h` library

**Comment by lshep** [comment]
I don't see a `library(methylclockData)`  in the vignette.  I would add the `library(methylclockData)` call before using any function from that package. 

I'll look more into the windows error soon.

**Comment by dpelegri** [comment]
Hi,

I don't know why it worked on linux and not on mac but it doesn't matter, I have added library (methylclockData) in the vignette and as you told me and it has worked.

Thanks

**Comment by lshep** [comment]
Thank you for your submission.  Please see initial review below: 

**Build Report**

- [ ] Please clean up as many NOTES as possible from the build report


**DESCRIPTION**

- [ ] (optional) we don't recommend having things like 'Date' in the descirption
  as maintainers sometimes forget to update static fields.

**NAMESPACE**

- [ ] Please do not use the '.' in function names. The '.' has a historical
  connotation to represent S3 dispatch. Please either use an underscore or
  camelcase

**NEWS**

- [ ] You currently are using `.Rd` format but have specified `NEWS.md`.

```
> utils::news(package="methylclock")
NULL
```
Please update the file to be called `NEWS.Rd`


**README**

- [ ] Any installation sections should be `eval=FALSE`.

- [ ] Please update installation instructions to be Bioconductor installations
  instructions and do not show install_github instructions.

**inst**

- [ ] Please also have an `inst/scripts` directory that provides the information
  for how the file in `inst/extdata` is generated.  It can be code, sudo-code,
  or text but should include source information and any processing or filters
  utilized.

**data/man**

- [ ] Please expand on the man page for the data files. The man pages should
  include more information on the structure and the relevant source information
  for the data.


**vignette**

- [ ] The vignette directory should only contain the source file of the vignette
in Rmd format.  Please remove the `*.html` files and the rsconnect directory.

- [ ] Do not install from github.  Please show Bioconductor installation
  instructions

- [ ] Generally instead of direct access with '$' or '@' we recommend creating
  accessor type functions. So instead of `cpgs.missing$Hannum` it would be a
  function with an argument for which value you would like
  `function(cpgs.missing, clock="Hannum")`


**R/man**

- [ ] We generally don't like to see large repeated chunks of code. It seems
  like a lot of the initial checks are the same in functions and could be moved
  to a universal validation function or the like.

- [ ] This message seems confusing

```
    stop("You wrote the name of an unavailable clock: Horvath, Hannum, Levine, BNN, Horvath2, PedBE, Wu, TL")
```

If the later part is what the available options are might be worth clarifing
```
    stop("You wrote the name of an unavailable clock. Available clocks are:  Horvath, Hannum, Levine, BNN, Horvath2, PedBE, Wu, TL")
```
Or list the invalid listed clock as maybe a user would have a typo that is not
as easily spotted

```
 stop("You wrote the name of an unavailable clock. Invalid entry: <value>)
```

- [ ] Message should be used instead of cat so users could suppress output if
  desired

- [ ] `stop`, `message`, `warning` automatically paste multiple arguments so the
paste is unnecessary in something like: 
```
  stop(paste("subset", subset.name, "and beta matrix have no features in common"))

```

- [ ] Why is the example code in normalization.R in a `dontrun`? 

- [ ] Use message instead of print whenever possible so user have option of
  suppressing output

- [ ] Keeping comments in code is encouraged, but please remove any commented
  out code that is no longer being run


When ready please push a version bump to trigger a new build report and comment back here addressing the above issues and notifying you are ready for a re-review.  
Thank you 
Cheers

**Comment by dpelegri** [comment]
> Thank you for your submission. Please see initial review below:
> 
> **Build Report**
> 
> * [x]  Please clean up as many NOTES as possible from the build report

I removed some NOTES and reduced the number of occurrences in which I have not been able to clean

> **DESCRIPTION**
> 
> * [x]  (optional) we don't recommend having things like 'Date' in the descirption
>   as maintainers sometimes forget to update static fields.

Removed Date from description

> **NAMESPACE**
> 
> * [x]  Please do not use the '.' in function names. The '.' has a historical
>   connotation to represent S3 dispatch. Please either use an underscore or
>   camelcase

Functions renamed

> **NEWS**
> 
> * [x]  You currently are using `.Rd` format but have specified `NEWS.md`.

Moved NEWS.Rd to /inst

 
> **README**
> 
> * [x]  Any installation sections should be `eval=FALSE`.

Changed

> * [x]  Please update installation instructions to be Bioconductor installations
>   instructions and do not show install_github instructions.

All with bioconductor instructions

> **inst**
> 
> * [x]  Please also have an `inst/scripts` directory that provides the information
>   for how the file in `inst/extdata` is generated.  It can be code, sudo-code,
>   or text but should include source information and any processing or filters
>   utilized.

Added information about source in data.R file.

> **data/man**
> 
> * [x]  Please expand on the man page for the data files. The man pages should
>   include more information on the structure and the relevant source information
>   for the data.

Added

> **vignette**
> 
> * [x]  The vignette directory should only contain the source file of the vignette
>   in Rmd format.  Please remove the `*.html` files and the rsconnect directory.

Removed files, only remains .Rmd and .bib for references

> * [x]  Do not install from github.  Please show Bioconductor installation
>   instructions

All with bioconductor instructions

> * [x]  Generally instead of direct access with '$' or '@' we recommend creating
>   accessor type functions. So instead of `cpgs.missing$Hannum` it would be a
>   function with an argument for which value you would like
>   `function(cpgs.missing, clock="Hannum")`

Added new accessor functions

> **R/man**
> 
> * [x]  We generally don't like to see large repeated chunks of code. It seems
>   like a lot of the initial checks are the same in functions and could be moved
>   to a universal validation function or the like.

Created new functions to check data

> * [x]  This message seems confusing
> ```
>     stop("You wrote the name of an unavailable clock: Horvath, Hannum, Levine, BNN, Horvath2, PedBE, Wu, TL")

Message replaced.

>  * [x]  Message should be used instead of cat so users could suppress output if
>   desired

Replaced

> * [x]  `stop`, `message`, `warning` automatically paste multiple arguments so the
>   paste is unnecessary in something like:

Removed paste


>  * [x]  Why is the example code in normalization.R in a `dontrun`?
I have removed this function because in this version it was not being used

> * [x]  Use message instead of print whenever possible so user have option of
>   suppressing output

Updated

> * [x]  Keeping comments in code is encouraged, but please remove any commented
>   out code that is no longer being run
I removed some commented out code

I push the new version and the build report is ok

Thank you

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dpelegri.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("methylclock")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methylclock

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
