### ISSUE TITLE
goSTAG

### ISSUE THREAD

**Issue by brianbennettphd** [Bioconductor/Contributions#216]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/brianbennettphd/goSTAG

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by brianbennettphd** [comment]
It appears that an ERROR was thrown during the CHECK phase because the maintainer was not subscribed to the bioc-devel mailing list. We just went to the link and subscribed to the bioc-devel mailing list, so this error should not appear next time.

**Comment by mtmorgan** [comment]
Please bump the version on your package to 0.99.1 to trigger a re-build.

**Comment by nturaga** [comment]
Hi @brianbennettphd 

Please address the `NOTE` messages as well, they are fairly straight forward. There are also a few `WARNING` messages in build reports, which are easy to resolve. We highly encourage a clean build. If you have any trouble, feel free to ask questions. And like @mtmorgan mentioned, each time you make a fix, please bump the version to trigger the build system.

```
Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                              old_size new_size compress
  goSTAG_go_genes_human.RData    876Kb    536Kb       xz
  goSTAG_go_genes_mouse.RData    875Kb    504Kb       xz
  goSTAG_go_genes_rat.RData      664Kb    384Kb       xz
```
```
Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/
```
```
Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
```
```
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 175 lines (17%) are > 80 characters
      long.
    First 6 lines:
      NAMESPACE:4 importFrom( "graphics", "close.screen", "image", "par", "pl...
      NAMESPACE:5 importFrom( "stats", "as.dendrogram", "as.dist", "cor", "di...
      man/annotateClusters.Rd:5 Annotates each cluster of GO terms with the t...
      man/annotateClusters.Rd:12   A list of vectors. Each element of the lis...
      man/annotateClusters.Rd:16 All of the GO terms within all of the cluste...
      man/annotateClusters.Rd:22 Bennett B and Bushel P. goSTAG: Gene Ontolog...
    * NOTE: Consider multiples of 4 spaces for line indents, 298 lines
      (28%) are not.
    First 6 lines:
      man/annotateClusters.Rd:11   \item{clusters}{
      man/annotateClusters.Rd:12   A list of vectors. Each element of the lis...
      man/annotateClusters.Rd:13   }
      man/groupClusters.Rd:11   \item{hclust_results}{
      man/groupClusters.Rd:12   An object of class "hclust" containing a tree...
      man/groupClusters.Rd:13   }
    See http://bioconductor.org/developers/how-to/coding-style/
```
```
Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages: man/goSTAG_example_gene_lists.Rd,
      man/goSTAG_go_genes_human.Rd, man/goSTAG_go_genes_mouse.Rd,
      man/goSTAG_go_genes_rat.Rd, man/plotHeatmap.Rd
```

**Comment by pbushel** [comment]
Hi nturaga,

I'm a co-developer of goSTAG with brianbennettphd.   We are under a deadline to resubmit a revised version of a paper based on the goSTAG R Bioconductor package.  1) Is it mandatory at this time to address all the NOTE messages or can we address some of them after the package validates is released? 2) Will the URL for the release of the package be: www.bioconductor.org/packages/release/bioc/html/goSTAG.html

If so, I'll place that in the paper, if not, what would it be?  Will the URL be case sensitive?

Thanks

**Comment by nturaga** [comment]
Hi @pbushel 

1) It is not mandatory, but as I mentioned it is highly encouraged. Small things like the `NEWS` file, and other basic style changes are extremely simple. And all changes and updates you make can go into the `NEWS` file, making it easy for users to follow the updates.

2) For your package final url will be `https://bioconductor.org/packages/goSTAG` ; the package enters `devel` version of Bioconductor immediately, but does not enter the release branch until our next release, in April. The URL is case-sensitive so your package should be called `goSTAG`. 

Good luck with your deadline.

**Comment by brianbennettphd** [comment]
Hi @nturaga 

I really appreciate your help with the submission of our package! I have a question about the WARNING thrown by R CHECK, which is for having empty \value sections in a few of our man pages. Four of these man pages are for data files, which have no return value, and the other man page is for a function that plots to the active graphics device and doesn't return anything either.

Since these items do not return anything, it doesn't seem natural to include a \value section in the man pages. Should we just ignore this warning during the check phase? If not, what do you suggest I put in the \value section?

**Comment by nturaga** [comment]
They don't need to return anything, but they must be creating an object. I would suggest showing the class of the object or showing 'None, the function is invoked for its side effect'. 

Example:
```
\value{
 None, the function is invoked for its side effect.
}
```
or, example from `RGraphviz`
```
\value{
  A laid out object of type \code{Ragraph}.
}
```

**Comment by pbushel** [comment]
Thanks @nturaga

**Comment by nturaga** [comment]
@pbushel , i'm going through the code, and I highly recommend going through the https://www.bioconductor.org/developers/how-to/coding-style/. I suggest adding a few comments to your code, users sometimes look at the functions. It also makes it easier to maintain in the future.

**Comment by pbushel** [comment]
@nturaga Much appreciated.

**Comment by pbushel** [comment]
@nturaga Glad that our goSTAG package built successfully.  Do you have an idea when the package will be added to the ‘devel’ branch of Bioconductor?  That way I can notify the journal reviewers of our paper that the development version is available for them to look over.
Thanks.

**Comment by nturaga** [comment]
@pbushel Building successfully does not mean acceptance of package. We still have to check for other things, which are mentioned in https://www.bioconductor.org/developers/package-submission/. I will give you an suggestions/comments as I go through it this week. But as a heads up, it would really help if there were a few comments in your source code files (`.R`) as i'd have to go through the code.

**Comment by pbushel** [comment]
Thanks @nturaga .  @brianbennettphd will be adding additional commenting.

**Comment by brianbennettphd** [comment]
I added some comments to the R code to increase its readability.

**Comment by nturaga** [comment]
Great thanks @brianbennettphd , also, you have a pull request if you'd like to add the README.md file as well.

**Comment by mtmorgan** [comment]
Hi @brianbennettphd,

@nturaga  and I worked on reviewing your package together. Can you please address the following suggestions?

- You can easily get rid of the one NOTE which you have by shortening
the lines in the `NAMESPACE` by using something like this,

```
importFrom("graphics", "abline", "axis", "box", "image", "layout", "lines",
    "par", "plot", "points", "segments", "strwidth", "text", "Axis")
```

- Also, in the `man/annotateClusters.Rd`, it would get rid of the NOTE
if you shortened your lines. The 80 char limit is part of the style
guide in `BiocStyle`.

DESCRIPTION

- Title: should be an informative one-line summary users can scan
  (e.g., on) to identify appropriate pacakges. So like the current
  Description: field.
- Description: should be a paragraph-length summary, like a paper
  abstract, of the methods used and their merits / particular reasons
  to use instead of alternatives.
- Bioconductor recommends a single Maintainer:; for more fine-grained
  author attribution, use the Authors@R field (_instead_ of Author:
  and Maintainer:)
- Long lines in the DESCRIPTION file can be wrapped using, with
  continuation lines indented (by 4 spaces, for instance)

NAMESPACE

- OK

vignette

- Looks great!
- Pay attention to long code lines, since these wrap poorly in the
  vignette, e.g.,
  
        clusters_larger_threshold <- groupClusters( hclust_results_euclidean, distance_threshold = 0.05 )

- Consider adding affiliation, contact, and 'edit date' (in addition
  to the automatic processing date), so the vignette can be attributed
  appropriately.
- As best practice, include a final section containing the command

        sessionInfo()
        
R

- No need to terminate lines with `;` !
- (optional) Use the package [GSEABase][1] to import GMT (`getGmt()`)
  and to represent gene sets. This reuses code and improves
  interoperability with other packages in the Bioconductor ecosystem.
- Consider using `switch()` rather than nested if / else for
  representing complex conditionals, e.g., annotateClusters.R:3
  
        parents <- switch(Ontology( GOTERM[ clusters[[1]][1] ] ),
            BP = as.list(GOBPPARENTS),
            CC = as.list(GOCCPARENTS),
            MF = as.list(GOMFPARENTS),
            stop("Invalid domain")
         )

- For this code chunk

        for( i in 1:length(clusters) ) {
            ## Define the recursive function to get the number of paths to the root
            get_num_paths = function( go_id, parents ) {
                this_parents = parents[[go_id]]
                this_parents = this_parents[ unlist( lapply( strsplit(names(this_parents),"[.]"), function(x) return( x[2] == "is_a" ) ) ) ];
                if( this_parents[1] == "all" ) {
                    return(1);
                } else {
                    return( sum( unlist( lapply( this_parents, function(x) return( get_num_paths( x, parents ) ) ) ) ) );
                }
            }
    
            ## Get the number of paths to the root for each GO term in the cluster
            num_paths = unlist( lapply( clusters[[i]], function(x) return(get_num_paths(x,parents)) ) );
    
            ## Select the GO term with the largest number of paths to the root
            cluster_labels[i] = Term( GOTERM[ clusters[[i]][ which.max(num_paths) ] ] );
        }

  I pulled the `get_num_paths()` function definition out of the loop
  to avoid re-definition on each iteration.
  
  Because of the way R symbol resolution works, it is not necessary to
  pass `parents` to `get_num_paths()`.

        get_num_paths = function( go_id ) {

  Extract the `go_id` element of `parents` using `[[`
  
        this_parents = parents[[go_id]]

  Subset to contain only the `is_a` parents with (this is an example
  of a _vectorized_ operation, with a single call to `names() ==`
  rather than an _iteration_ with a call to each `names() ==` for each
  element of `this_parents`).

        this_parents = this_parents[names(this_parents) == "is_a"]
        
  Since `get_num_paths()` always returns an integer, use `vapply()`
  rather than `unlist(lapply())` on the recursive call. 

        if( this_parents[1] == "all" ) {
            1L
        } else {
            sum( vapply( this_parents, get_num_paths, integer(1) ) )
        }
  
  The pattern in the outer loop, starting at annotateClusters.R:14 is
  'copy-and-append' where a 0-length result is allocated and then
  appended to on each iteration through the loop. See
  [pre-allocate and fill][2] for avoiding this pattern, either using a
  `for()` loop but pre-allocating and filling, or using an `lapply()`
  to avoid the need for explicit memory management. Likewise,
  [avoid 1:n style iterations][3].  I wrote
  
        sapply(clusters, function(cluster) {
            ...
        })

  In the function applied to each cluster, `num_paths` can be
  simplified to use `vapply()`, since each iteration is guaranteed to
  return an integer
  
        num_paths <- vapply(cluster, get_num_paths, integer(1))

  and then return the cluster label is
  
        Term(GOTERM[ cluster[ which.max(num_paths) ] ])

  The code chunk is
        
        sapply(clusters, function(cluster) {
            ## Get the number of paths to the root for each GO term in the
            ## cluster
            num_paths = vapply(cluster, get_num_paths, integer(1))
            Term( GOTERM[ cluster[ which.max(num_paths) ] ] )
        })
            
  but `GOTERM[]` is vectorized, and it is better to vectorize where possible
  
        ## Cycle through all the clusters
        idx <- vapply(clusters, function(cluster) {
            ## Get the number of paths to the root for each GO term
            num_paths = vapply(cluster, get_num_paths, integer(1))
            cluster[ which.max(num_paths) ]
        }, character(1))
        Term( GOTERM[ idx ] )
            
  This is the revised code

        annotateClusters1 = function( clusters ) {
            ## Load the GO parents from the GO.db package
            parents <- switch(
                Ontology( GOTERM[ clusters[[1]][1] ] ),
                BP = as.list(GOBPPARENTS),
                CC = as.list(GOCCPARENTS),
                MF = as.list(GOMFPARENTS),
                stop("Invalid domain")
            )
        
            ## Define the recursive function to get the number of paths to the 
            ## root
            get_num_paths = function( go_id ) {
                this_parents = parents[[go_id]]
                this_parents = this_parents[ names(this_parents) == "is_a" ]
                if( this_parents[1] == "all" ) {
                    1L
                } else {
                    sum(vapply(this_parents, get_num_paths, integer(1)))
                }
            }
        
            ## Cycle through all the clusters
            idx <- vapply(clusters, function(cluster) {
                ## Get the number of paths to the root for each GO term in the 
                ## cluster
                num_paths = vapply(cluster, get_num_paths, integer(1))
                cluster[ which.max(num_paths) ]
            }, character(1))
            Term( GOTERM[ idx ] )
        }
          
  which produces identical results, is more robust, and faster (using
  `clusters` created by running `example(annotateClusters)` as a test
  case).

          > system.time(res0 <- annotateClusters(clusters))
             user  system elapsed 
            3.952   0.000   3.953 
          > system.time(res1 <- annotateClusters1(clusters))
             user  system elapsed 
            2.284   0.000   2.281 
          > identical(res0, unname(res1))
          [1] TRUE

- A final improvement likely to be relevant in real cases is to
  'memoise' the `get_num_paths()` function. Memoisation keeps a
  look-up table of function arguments and the result of the
  function. When the same argument is seen, it uses the previously
  calculated value rather than re-calculating. This can be very
  helpful in recurssive algorithms like the one you use, where the
  same 'root' paths are repeatedly traveresed.
  
        get_num_paths = memoise::memoise(function( go_id ) {
            this_parents = parents[[go_id]]
            this_parents = this_parents[ names(this_parents) == "is_a" ]
            if( this_parents[1] == "all" ) {
                1L
            } else {
                sum(vapply(this_parents, get_num_paths, integer(1)))
            }
        })
  
  The evaluation time with the sample data is about 1s, rather than
  the original 4s.
- It looks like similar considerations (especially reducing highly
  nested evaluation lines, more robust approaches to iteration, and
  using vectorization where possible) can be applied to the other
  major functions in your package.

man

- Some of the functions, like performGOEnrichment, takes for granted
  that the user has to search for all the arguments in the functions
  you use from other packages. In this case, p.adjust, I think it can
  be made easier for the user by giving him the available
  options. There are other examples like that in other functions in
  goSTAG as well.

[1]: https://bioconductor.org/packages/GSEABase
[2]: http://bioconductor.org/developers/how-to/efficient-code/#pre-allocate-and-fill-if-iterations-are-necessary
[3]: http://bioconductor.org/developers/how-to/efficient-code/#avoid--style-iterations

**Comment by brianbennettphd** [comment]
Thanks @mtmorgan and @nturaga for your in-depth review of our package! Many of your suggestions are great ideas that I will carry forward as I continue to develop in the future.

The only comment that I was not able to address (due to time constraints) was to shorten all of the lines that are greater than 80 characters. However, I have addressed all of your other concerns, making significant changes throughout the entire package. Please let me know if you are satisfied with my revisions and if you have any other concerns.

**Comment by pbushel** [comment]
@mtmorgan and @nturaga Please let us know an estimate of when the package will be approved as we need to resubmit the manuscript on goSTAG in the coming days.  Thanks

**Comment by mtmorgan** [comment]
Thanks I looked at your changes and see that they address the issues raised in the initial review. I'll mark your package as 'accpeted'; it will be added to Bioconductor svn and nightly builds, likely appearing in Friday or Saturday's build. More information will be sent by email in a day or  so.

**Comment by pbushel** [comment]
That's great news!  Thanks so much @mtmorgan We'll submit the paper early next week with the following url:
https://bioconductor.org/packages/goSTAG  
and let the reviewers know that they can search Bioconductor for the development version.

**Comment by brianbennettphd** [comment]
@mtmorgan Should I increment the version number to 1.0.0?

**Comment by mtmorgan** [comment]
No, it is in the 'devel' branch. At the next release (later this spring) it'll be copied to the release branch and version bump to 1.0.0; the devel branch version will bump to 1.1.0. Until then any changes you make should be increment the 'z' part of 0.99.z.
