### ISSUE TITLE
BentoBoxData

### ISSUE THREAD

**Issue by nekramer** [Bioconductor/Contributions#2165]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PhanstielLab/BentoBoxData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by nekramer** [comment]
AdditionalPackage: https://github.com/PhanstielLab/BentoBox

**Comment by LiNk-NY** [comment]
Hi Nicole, @nekramer 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# BentoBoxData #2165

* Please remove the 85 Mb of `.git/object/pack` files with the BFC repo cleaner

## DESCRIPTION

* Looks good.
* Add `BugReports` and `URL` fields

## vignettes

* Either load the package with `library` or use the package argument in the
`data` call.
* Consider dropping the `bb_` prefix from the data names.
* Consider renaming `bb_imrHiCData` and dropping the word 'Data' as this is
understood for a data resource.
* Please use more descriptive names (`bb_bedData`)
* Perhaps the cytoband data should be in a separate `AnnotationHub` package?
(See also: `AHCytoBands`)

---

# BentoBox #2165

* BentoBox has the same issue with large `.git/object/pack` files. Please
remove these with the BFG repo cleaner.

## DESCRIPTION

* Add a `BugReports` field
* It does not look like you use the Bioconductor infrastructure to the fullest
extent but you do provide some Bioconductor packages in the `Suggests` field.

## NAMESPACE

* Perhaps it's a matter of personal preference but consider removing the `bb`
prefix from all of your functions. Users who would like to see what functions
are available in the package could use `help(package = "BentoBox")` or
`ls(2)` after loading the package.
* Do all of these functions need to be exported? Some look like helper
functions for plotting and may not need to be exported.

## vignettes

* Consider breaking up the vignette into smaller ones. These can get pretty
dense and having separate vignettes for the four functionalities may be
helpful for the user.

## R

* The general recommendation for checking whether a package exists or not in
the users installation is to use `requireNamespace`. You could then emit an
error when the package is not avialable (instead of `check_loadedPackage`).
This is described in the package guidelines.
* One general strategy to use is to create a data.frame for listing the
supported genome assemblies, creating a multiplier for the 'just' argument
(e.g., in `bb_annoHighlight`), etc. This way you have an actual data
representation rather than code with embedded data. This is also easier to
expand and maintain.
* Avoid using numeric indices for subsetting and use character ones, i.e.,
`df[, "chr1"]` is more robust than `df[, 1]`.
* Throughout the code you have `as.numeric` in many places, this indicates
that you should have more control over the data inputs rather than coercing
repeatedly. You could also use `utils::type.convert` iteratively on the data,
if necessary.
* Due to the size of the package. I am unable to review all of the code.
Please ensure that you are following the [package guidelines](https://www.bioconductor.org/developers/package-guidelines/).

## tests

* Avoid using the `skip_on_bioc()` for tests. The save functionality does
not need tests as that is pretty robust and not really related to your
package.
* Please include more tests for checking the helper functions in the package.

**Comment by nekramer** [comment]
Hi @LiNk-NY,
Thank you for your package review! We have addressed the comments as follows:
> # BentoBoxData #2165
> * Please remove the 85 Mb of `.git/object/pack` files with the BFC repo cleaner

**The large `.git/object/pack` files have been removed.**
> ## DESCRIPTION
> * Looks good.
> * Add `BugReports` and `URL` fields

**These fields have been added to the DESCRIPTION file.**
> ## vignettes
> * Either load the package with `library` or use the package argument in the
>   `data` call.

**`library(BentoBoxData)` has been added to beginning of the vignette.**
> * Consider dropping the `bb_` prefix from the data names.

**All data have now been renamed, with the `bb_` prefixes dropped.**
> * Consider renaming `bb_imrHiCData` and dropping the word 'Data' as this is
>   understood for a data resource.

**All data have been renamed with the word 'Data' dropped.**
> * Please use more descriptive names (`bb_bedData`)

**Thank you for this helpful advice. All data have been renamed with more descriptive names, which now include specific cell types, genomic assays and targets, and data format. For example `bb_bedData` is now `IMR90_ChIP_CTCF_reads`.**
> * Perhaps the cytoband data should be in a separate `AnnotationHub` package?
>   (See also: `AHCytoBands`)

**We have now implemented a hybrid approach in `BentoBox` that utilizes the `AHCytoBands` `AnnotationHub`, but can also accept external data. Since `AnnotationHub` depends on a valid connection, we would like to keep this data as part of `BentoBoxData` as a failsafe. Thus, if less experienced Bioconductor users cannot access `AnnotationHub`, they have a straightforward place to retrieve this data and can use our function.**
> # BentoBox #2165
> * BentoBox has the same issue with large `.git/object/pack` files. Please
>   remove these with the BFG repo cleaner.

**The large `.git/object/pack` files have been removed.**
> ## DESCRIPTION
> * Add a `BugReports` field

**A `BugReports` field has been added to the DESCRIPTION file.**
> * It does not look like you use the Bioconductor infrastructure to the fullest
>   extent but you do provide some Bioconductor packages in the `Suggests` field.

**We have added additional integration with the Bioconductor infrastructure including using `AnnotationHub` for cytoband annotation data. `BentoBox` uses TxDb, orgDb, and BSgenome Bioconductor packages for getting genomic information, plotting gene and transcript structures, and plotting genomic sequences. Relevant functions are also tightly integrated with existing Bioconductor data structures like GRanges and GInteractions. Although many Bioconductor packages only appear in the `Suggests` field, these packages are suggested rather than explicitly imported so users must only install the 
specific Bioconductor dependencies they need depending on which specific functions they want to use, which will be suggested as warning messages after checking with `requireNamespace`.**	

> ## NAMESPACE
> * Perhaps it's a matter of personal preference but consider removing the `bb`
>   prefix from all of your functions. Users who would like to see what functions
>   are available in the package could use `help(package = "BentoBox")` or
>   `ls(2)` after loading the package.

**This is a very reasonable suggestion and is something we have debated for a long time. We feel the `bb_` prefix is helpful for less experienced R users, particularly with interfacing with R IntelliSense to help auto-complete function names. We have found it’s easier and quicker to find all `BentoBox` functions with the `bb_` prefix.**

> * Do all of these functions need to be exported? Some look like helper
>   functions for plotting and may not need to be exported.
> 

**We have double checked all of the exported functions, and yes they are all intentionally exported for use.**
> ## vignettes
> * Consider breaking up the vignette into smaller ones. These can get pretty
>   dense and having separate vignettes for the four functionalities may be
>   helpful for the user.
> 

**There is a lot of information in each vignette but we have already broken it up into five vignettes. Beyond the introduction vignette, we have vignettes that go into greater detail on `BentoBox` pages, plot annotations, plot aesthetics, and external plot elements. Breaking up the main vignette into vignettes for the four functionalities could be helpful, but we feel that 
the current structure of the main vignette is necessary for users to understand the overall workflow of the package.  We feel that further splitting the vignettes would make the information too fragmented for the structure of the package and difficult to find.**
> ## R
> * The general recommendation for checking whether a package exists or not in
>   the users installation is to use `requireNamespace`. You could then emit an
>   error when the package is not avialable (instead of `check_loadedPackage`).
>   This is described in the package guidelines.

 **We have updated checking packages to `requireNamespace` as described in the package guidelines.**
> * One general strategy to use is to create a data.frame for listing the
>   supported genome assemblies, creating a multiplier for the 'just' argument
>   (e.g., in `bb_annoHighlight`), etc. This way you have an actual data
>   representation rather than code with embedded data. This is also easier to
>   expand and maintain.

**data.frames are now used to store internal information about supported genome assemblies, justifications, etc. ** 
> * Avoid using numeric indices for subsetting and use character ones, i.e.,
>   `df[, "chr1"]` is more robust than `df[, 1]`.

**We have now tried to avoid numeric indices for subsetting as much as possible, but due to the flexibility of some functions, there are some cases where this is not entirely possible.** 
> * Throughout the code you have `as.numeric` in many places, this indicates
>   that you should have more control over the data inputs rather than coercing
>   repeatedly. You could also use `utils::type.convert` iteratively on the data,
>   if necessary.

**`as.numeric` has been removed from unnecessary sections and has been changed to `utils::type.convert` when necessary to convert data to its original type in `apply` functions. Any `as.numeric` calls that remain are not used for coercing data inputs. In addition, more robust checks for required input types have been added.**
> * Due to the size of the package. I am unable to review all of the code.
>   Please ensure that you are following the [package guidelines](https://www.bioconductor.org/developers/package-guidelines/).
> 

**We certainly understand.  We have read and made every attempt to adhere to the package guidelines to the best of our abilities.**
> ## tests
> * Avoid using the `skip_on_bioc()` for tests. The save functionality does
>   not need tests as that is pretty robust and not really related to your
>   package.

**We have removed this unnecessary test and now do not have any tests with `skip_on_bioc()`.**
> * Please include more tests for checking the helper functions in the package.

**We have roughly tripled the number tests for checking the helper functions in the package and now have over 90 tests.**

Thank you for your helpful comments.

Best,
Nicole Kramer

**Comment by LiNk-NY** [comment]
Hi Nicole, @nekramer 

Thank you for making those changes. 
Please see my responses below. 

Best, 
Marcel

---

> since annotationhub depends on a valid connection, we would like to keep
this data as part of bentoboxdata as a failsafe.

this is not a good reason to keep duplicated data. most users will have an
internet connection; otherwise, they would not be able to download your
package. if the resources are there, use them and avoid duplication. the
`annotationhub` resources are cached and only need to be downloaded once,
therefore the users' internet has to only be reliable once.

also, "experience" with `annotationhub` is not a necessary component of usage
because the developer (you) can make the download of resources easy for the
user through easy-to-use functions.

>  we feel the bb_ prefix is helpful for less experienced r users,
particularly with interfacing with r intellisense to help auto-complete
function names. we have found it’s easier and quicker to find all bentobox
functions with the bb_ prefix.

i am not sure what the uptake is on intellisense and visual studio for r but
this is certainly not a typical setup. bioconductor users are more likely to
be using either rstudio or the command line. rstudio provides an auto complete
version where the user can enter `bentobox::` and then press <kbd> tab </kbd>
to see all the exported functions in the package. Users on the command line
would likely know to use `help(package = "BentoBox")` or `ls(2)`.

> Breaking up the main vignette into vignettes for the four functionalities
could be helpful, but we feel that the current structure of the main vignette
is necessary for users to understand the overall workflow of the package. We
feel that further splitting the vignettes would make the information too
fragmented for the structure of the package and difficult to find.

Having a large vignette is conducive to losing / overwhelming users. It is
easy to get lost in lots of nuanced examples. That is why I was proposing a
break up by funcitonality to make these operations easier to find for
the user that is searching for it.

**Comment by nekramer** [comment]
Hi Marcel, @LiNk-NY 

First of all, thanks so much for taking the time to review our package and for doing such a thorough job with what we acknowledge is a substantial amount of code. Your input was really valuable and we think improves the quality, stability, and usability of the final package.


>  This is not a good reason to keep duplicated data. most users will have an internet connection; otherwise, they would not be able to download your package. if the resources are there, use them and avoid duplication. The `annotationhub` resources are cached and only need to be downloaded once, therefore the users' internet has to only be reliable once. Also, "experience" with `annotationhub` is not a necessary component of usage  because the developer (you) can make the download of resources easy for the user through easy-to-use functions.

These are excellent points. We are using `AnnotationHub` as directed, and although this is the default option, we just want an easily accessible, non-`AnnotationHub` based version as a backup. You are entirely correct in that we as the developers make the download of resources easy for the user, but relying solely on `AnnotationHub` ultimately induces a (lower case 'd') dependency that limits the package utility if it breaks. For example, the `AnnotationHub` cache could become corrupt or moved accidentally. It would be frustrating if someone already had the package installed with a previously working script that suddenly stopped working offline because there was an `AnnotationHub` cache issue with no alternative option. This is not intended to be the primary source of cytoband data, and the data is overall very small and only available for 9 genome assemblies, so it does not take up significant space in the package. In addition, seeing the format of this data with our package can help users understand how to format custom cytoband data if they desire.

>  i am not sure what the uptake is on intellisense and visual studio for r but this is certainly not a typical setup. bioconductor users are more likely to be using either rstudio or the command line. rstudio provides an auto complete version where the user can enter `bentobox::` and then press tab to see all the exported functions in the package. Users on the command line would likely know to use help(package = "BentoBox") or ls(2).

That makes sense. We surveyed our current user base and they universally responded that they liked the prefix; however to conform to Bioconductor guidelines we have removed the underscore and capitalized the following letter so that the function names are in the indicated camelCase. We believe that this naming scheme is now both fully compliant with Bioconductor guidelines and is user approved.

>  Having a large vignette is conducive to losing / overwhelming users. It is easy to get lost in lots of nuanced examples. That is why I was proposing a break up by functionality to make these operations easier to find for the user that is searching for it.

Thank you for this suggestion. It is definitely easy to feel your own vignette is intuitive when you are the one who has developed the package! We have now followed your suggestion and further broke up our vignette into additional guides, based on functionality.

Again, thank you so much for your incredibly helpful review. I look forward to hearing your response!
Best,
Nicole

**Comment by LiNk-NY** [comment]
Hi Nicole, @nekramer 

Thank you for following up and making those changes. 

> These are excellent points. We are using `AnnotationHub` as directed, and although this is the default option, we just want an easily accessible, non-`AnnotationHub` based version as a backup. You are entirely correct in that we as the developers make the download of resources easy for the user, but relying solely on `AnnotationHub` ultimately induces a (lower case 'd') dependency that limits the package utility if it breaks. For example, the `AnnotationHub` cache could become corrupt or moved accidentally. It would be frustrating if someone already had the package installed with a previously working script that suddenly stopped working offline because there was an `AnnotationHub` cache issue with no alternative option. This is not intended to be the primary source of cytoband data, and the data is overall very small and only available for 9 genome assemblies, so it does not take up significant space in the package. In addition, seeing the format of this data with our package can help users understand how to format custom cytoband data if they desire.
> 

I understand your concerns but the scenario you describe is quite unlikely. `AnnotationHub` is robust and unlikely to break. We do not encourage users to manipulate the cache and we do have functions to remove corrupt cache resources for those rare occasions. Therefore, the alternative option is not necessary. Data included in the package always gets downloaded with every update of the package, as opposed to only downloading the `AnnotationHub` resource once. For offline users, administrators can download all the resources required for the package beforehand. 

Best,
Marcel

**Comment by nekramer** [comment]
Hi Marcel @LiNk-NY,

Thank you for hearing out our concerns. With your added assurance, we have removed the cytoband data from our packages and now solely rely on `AnnotationHub`. 

Best,
Nicole

**Comment by LiNk-NY** [comment]
Hi Nicole, @nekramer 

Thank you for making those changes. We are putting the package on hold until
we figure out how you were able to make the default branch `main` for `BentoBoxData`. 

We'll get back to you soon. 
Feel free to add any supporting information. 

Best,
Marcel

**Comment by nekramer** [comment]
Hi Marcel @LiNk-NY,

Please let me know if there's anything on my end I can do to assist that process! Thank you for all the time you've taken on this package.

Best,
Nicole

**Comment by LiNk-NY** [comment]
Hi Nicole, @nekramer 

We've updated the repository on git.bioconductor.org to have master as the default branch. 
You have to pull from there to sync and bump the version for a last build before acceptance.
Let me know if you encounter any issues. 

Thank you!
-Marcel

**Comment by nekramer** [comment]
Hi Marcel @LiNk-NY,

Thank you for working on this so quickly. I have pulled and synced the repositories and bumped the version for `BentoBoxData`.

Best,
Nicole

**Comment by LiNk-NY** [comment]
Hi Nicole, @nekramer 

Thanks for that! 
Your package has been accepted to Bioconductor. 

Note. I really like your sticker but it does not represent a bento box and I think [sushi](https://www.bioconductor.org/packages/release/bioc/html/Sushi.html) instead  :sweat_smile: 

Best,
Marcel

**Comment by nekramer** [comment]
Thank you for all your help, Marcel @LiNk-NY! `BentoBox` is actually a relative of the `Sushi` package, hence the Japanese food metaphors and imagery 😂

Best,
Nicole

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nekramer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BentoBoxData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BentoBoxData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nekramer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BentoBox")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BentoBox

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
