### ISSUE TITLE
FindIT2

### ISSUE THREAD

**Issue by shangguandong1996** [Bioconductor/Contributions#2166]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shangguandong1996/FindIT2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by shangguandong1996** [comment]
Hi, @hpages 
I can run my bigwig successfully on my 64 bit R on windows, but I failed on 32 bit R. Accoring to the https://github.com/Bioconductor/Contributions/issues/2126, https://github.com/lawremi/rtracklayer/issues/52, and [rtracklayer::import() BigWig issue on windows (solved)](https://support.bioconductor.org/p/129446/), it seems that rtracklayer have some issue on 32 bit windows.

Best wishes

Guandong Shang

**Comment by shangguandong1996** [comment]
Hi， @LiNk-NY 
I just want to say that I am ready to receive review and thanks for your review

Best wishes
Guandong Shang

**Comment by LiNk-NY** [comment]
Hi Guandong, @shangguandong1996 

Thank you for following up.
Your package is currently the next one on my review list.
I will provide a review in a day or so. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Please see the review below: 

# FindIT2 #2166

* Please rename your package as it does not seem related to the `FindIt`
package on CRAN and could cause confusion.

## DESCRIPTION

* Looks good.
* Consider removing the magrittr dependency if you're only using it for the
pipe operator (which is also exported by `dplyr`).

## NAMESPACE

* Consider seperating the `shiny` functionality from the package and creating
a dedicated `shiny` version of the package
* Consider removing the `findIT` prefixes. These generally do not add much
to the function name other than increasing the length of it.

## vignettes

* Avoid package installations instructions that are not consistent with the
current availability of the package in Bioconductor. Next time, please
add `BiocManager::install` and remove the GitHub installation instructions
_after_ the review has been concluded.
* Consider reformatting the vignette to stay within the 80 character limit.
This makes it easier to review and even maintain.

## R

* Avoid using `cat` to send messages to the user. Use `message` instead and
include a `verbose` argument for minimizing the verbosity.
* Avoid right hand assignment `->` as it hinders readability
* Use more specific / informative names rather than `input_genes` and
`input_feature_id` for datasets in the package.
* Describe the inputs in the documentation, e.g., for `input_feature_id`,
should it be a `character` vector or `GRanges`?
* List all options in arguments, e.g., `output_type` in `getAssocPairNumber`
should be `c("feature_id", "gene_id")` by default, then you can use
`match.arg` to resolve the input inside the function.
* Avoid using the `quiet` and `sink()` functions in `R/utils.R`

## tests

* Looks good.

**Comment by shangguandong1996** [comment]
Hi, @LiNk-NY 

Thanks for your reivew, which is helpful for me !!! For a new one to pacakge, I may not know the true reason for some review. Please correct me if I misunderstand your review.

# FindIT2
>  Please rename your package as it does not seem related to the FindIt package on CRAN and could cause confusion.

I am sorry it may cuase a confusion. I think consider FindIt is on CRAN and it seems not related to bioinformatics, it may not cause too much confusion. The expanded name of FindIT2 is `Find influential TF and influential Target`.  I have add this expanded name on my github README title and vignette. I hope it can avoid confusion for user of FindIT2 or FindIt. 

# DESCRIPTION
> Consider removing the magrittr dependency if you're only using it for the pipe operator (which is also exported by dplyr).

I have removed magrittr dependency in DESCTIPTION and all R code.

# NAMESPACE
>  Consider seperating the shiny functionality from the package and creating a dedicated shiny version of the package

The reason I write two shiny function in packages is that I hope it can help user who is new to bioconductor classes explore result interactively. This two shiny function do not disturb the whole package. Consider there are only two shiny function in packages, it may hard for me to wrtie a another shiny version package.


> Consider removing the findIT prefixes. These generally do not add much to the function name other than increasing the length of it.

For a user who use many R packages everyday, I always forget which function can do specific things, so I have to search over and over again. Consider FinIT2 have several module and can do several things(I apologize for that it do more than one thing……), and user may be confused about so many function. So I add the prefix on function in correspondent modules The functions in `mmAnno` all have prefix `mm` ,  the functions in `calcRP` all have prefix `calcRP`, and all the functions in `find_influential_TF` have prefix `findIT`.  I just want my user can use function more smoothly even the name of function is long, I believe add prefix can help user know which module they use now. After all, `Tab` is much easier than google :). 


# vignettes
> Avoid package installations instructions that are not consistent with the current availability of the package in Bioconductor. Next time, please add BiocManager::install and remove the GitHub installation instructionsafter the review has been concluded.

I have removed Github installation on vignettes.


> Consider reformatting the vignette to stay within the 80 character limit. This makes it easier to review and even maintain.

I have reformated the vignette to stay within the 80 character limit.




# R

> Avoid using cat to send messages to the user. Use message instead and include a verbose argument for minimizing the verbosity.

I have convert all `cat` into `message` and add verbose in paramter. 

> Avoid right hand assignment -> as it hinders readability

I have convert all -> into <- in all R code

> Use more specific / informative names rather than input_genes andinput_feature_id for datasets in the package.

I remove the `input_genes` and `input_feature_ids` in dataset. Instead, I add `test_geneSet` and `test_featureSet`


> Describe the inputs in the documentation, e.g., for input_feature_id, should it be a character vector or GRanges?

I have add more detailed information about inputs object attributes.


> List all options in arguments, e.g., output_type in getAssocPairNumber should be c("feature_id", "gene_id") by default, then you can usematch.arg to resolve the input inside the function.

I have listed all options in arguments and add match.arg in R code

> Avoid using the quiet and sink() functions in R/utils.R

I have removed all code related quiet and sink() in all R code

**Comment by shangguandong1996** [comment]
Hi, @LiNk-NY 
As for the package name, I just want to say that if you insist on changing package name. I can rename it into `FindITIT`. I have searched  this name on CRAN, bioconductor and google. I beileve it will not cause too much confusion with `FindIt`. 
Or I can rename it into `FITIT`. But I find a software named [Fitit](http://nano.sfedu.ru/research/projects/fitit/), but it is not related with R or even biology. As for CRAN, I just find a package named `FIT`.

And I will create a new repo and edit my first comment according to 
> Additional Actions
To change the repository of your package during the review process:
Edit the first comment in the issue associated with your package. Change the Repository: link to point to your new repository.
Post a comment in your issue, tagging your reviewer, indicating that you have changed the repository.
Once the comment is acknowledged, bump the package version in the new repository to trigger a new build.

Best wishes

Guandong Shang

**Comment by LiNk-NY** [comment]
Hi Guandong, @shangguandong1996 
Thank you for making those changes. 
I have a few responses.

> The reason I write two shiny function in packages is that I hope it can help user who is new to bioconductor classes explore result interactively. This two shiny function do not disturb the whole package. Consider there are only two shiny function in packages, it may hard for me to wrtie a another shiny version package.

Because the two shiny functions do not disturb the package, meaning they are not essential to the code base, it would be best to put this functionality in a standalone shiny package. This will not only reduce the amount of dependencies in `FindIT2` but also allow the users of the shiny package to have a much simpler interface (without all the other functions in `FindIT2`). 

> For a user who use many R packages everyday, I always forget which function can do specific things, so I have to search over and over again. Consider FinIT2 have several module and can do several things(I apologize for that it do more than one thing……), and user may be confused about so many function. So I add the prefix on function in correspondent modules The functions in mmAnno all have prefix mm , the functions in calcRP all have prefix calcRP, and all the functions in find_influential_TF have prefix findIT. I just want my user can use function more smoothly even the name of function is long, I believe add prefix can help user know which module they use now. After all, Tab is much easier than google :).

Yes, I agree but also `help(package = "FindIT2")` or even `ls(2)` after loading is just as easy for listing all the functions in the package. The prefix is not really necessary but you can leave them in if you'd like. 

> As for the package name, I just want to say that if you insist on changing package name. I can rename it into FindITIT. I have searched this name on CRAN, bioconductor and google. I beileve it will not cause too much confusion with FindIt.
Or I can rename it into FITIT. But I find a software named Fitit, but it is not related with R or even biology. As for CRAN, I just find a package named FIT.

This is ultimately up to you as the developer to make this decision. We can only advise you to not have a name so similar to other software. From our point of view, it is easier to keep the name even though it may cause confusion among your users and `FindIt` users. 

Best regards,
Marcel

**Comment by shangguandong1996** [comment]
Hi, @LiNk-NY 

Thanks for your detailed explanation. I am glad I can keep this name, it is hard to think a package name for me :).  As for the shiny function, I have moved all shiny related function into a new package : [InteractiveFindIT2](https://github.com/shangguandong1996/InteractiveFindIT2) and removed shiny dependencies in DESCRIPTION and NAMESPACE. And I also correct related things in vignettes. Although `InteractiveFindIT2` now is ugly, but it at last can work :). I will improve it in the future and hope to do some modification so that I can post it into Bioconductor one day :)

And Thanks again for your review.

Best wishes
Guandong Shang

**Comment by LiNk-NY** [comment]
Hi Guandong, @shangguandong1996 

Thanks for making those changes. It looks like the package is ready to go.
Please make sure you follow up on the notes produced by `BiocCheck::BiocCheck()`.

Best regards,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shangguandong1996.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("FindIT2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FindIT2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
