### ISSUE TITLE
cageminer

### ISSUE THREAD

**Issue by almeidasilvaf** [Bioconductor/Contributions#2177]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/almeidasilvaf/cageminer

Confirm the following by editing each check box to '[x]'

- [ x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x ] The 'devel' branch for new packages and features.
- [ x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by almeidasilvaf** [comment]
Hi @lshep 

Bioconductor now requires registration to support.bioconductor.org. I was not aware of this change, but I have signed up and added my packages to the "Watched tags" section. To trigger a new build, I guess I should push a modified version of `cageminer`, but there's nothing to change. How should I proceed now?

**Comment by lshep** [comment]
Please push a version bump to trigger the new build.

**Comment by almeidasilvaf** [comment]
Hi, @lshep 

The build process was returning TIMEOUT because of examples that were taking a long time to run. I've managed to simplify them, but there seems to be something wrong with the Windows build. 2 functions are taking much longer to run on Windows as compared to macOS and Linux. The package now builds perfectly on Linux and macOS, but the TIMEOUT on Windows persists. See below:

- Linux:
Examples with CPU (user + system) or elapsed time > 5s
            user system elapsed
mine_step3 6.521  4.215   6.925
mine_step2 4.492  2.786   5.003


- macOS:
Examples with CPU (user + system) or elapsed time > 5s
                 user system elapsed
mine_step3      9.304  8.073  11.654
plot_snp_circos 8.701  0.281   9.575
mine_step2      4.588  3.855   5.653


- Windows:
Examples with CPU (user + system) or elapsed time > 5s
            user system elapsed
mine_step3 16.51   0.25  376.52
mine_step2 15.56   0.16  359.14


To put it in perspective, the package builds with no problems on Windows in the GitHub Action created with biocthis. See: https://github.com/almeidasilvaf/cageminer/runs/3035808750?check_suite_focus=true

I wonder if this is a problem with the Bioconductor build system itself. Do you have any idea on what may have happened?

**Comment by lshep** [comment]
I'll review the package based on the other two platforms in the meantime and when I have time I'll try to jump on the builder to see if I can narrow down why there is a slow down or what is causing the issue.  Please expect a review within the next two weeks.

**Comment by almeidasilvaf** [comment]
Great! Thank you very much.

**Comment by lshep** [comment]
Nicely well written package especially the vignette.   My only minor comment is perhaps adding a package man page so users would get either information or pointers to the main function if they did `?cageminer`.  This however is optional and does not prevent acceptance. Cheers.  As far as the windows timeout,  let's see what happens when it gets on the daily builder.  if it encounters timeouts there, please let me know and I'll investigate further what function is causing the slow down on windows.

**Comment by almeidasilvaf** [comment]
Hi, @lshep 

Thank you very much for your review and feedback. I have been waiting for the build results of `cageminer` in the daily builder to see if the TIMEOUT on Windows will persist. Has the package been sent to the Bioc daily builder yet?

**Comment by lshep** [comment]
Not yet.  I'll check on the processing of accepted packages.

**Comment by almeidasilvaf** [comment]
Great! Thank you for your time.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/almeidasilvaf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cageminer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cageminer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
