### ISSUE TITLE
enhancerHomologSearch

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#2181]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/enhancerHomologSearch

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by LiNk-NY** [comment]
Hi Jianhong, @jianhong 

Thank you for your submission. 
Please see the review below. Feel free to ask any questions.

Best regards,
Marcel

---

# enhancerHomologSearch #2181

## DESCRIPTION

* Include a `BugReports` and `URL` field.
* Looks good.

## NAMESPACE

* The usual Bioconductor convention is to use a capital letter name for
class names, e.g., `SummarizedExpeirment` vs `enhancers`.

## vignettes

* Concise. Looks good.
* Add an installation section using `BiocManager`.
* Avoid using double `$` which suggests a nested list. Perhaps use S4
extractors and replacers.

## R

* Use a single worker by default in the examples (`alignmentOne`).
* Create helper functions to check for typical cases (those in `stopifnot`)
and re-use them in `alignmentOne` and `alignment`, for example.
* Consider using explicit / documentable arguments in the `enhancers`
constructor function rather than the elipses `...`.
* Avoid using `$` for extraction or setting of a slot. Create a dedicated
extractor function, e.g., `assay` method for `SummarizedExperiment`. `$` are
indicative of list classes and can cause confusion when used outside of that
context.
* Consider using caching in `getENCODEdata`, possibly via `BiocFileCache`.
* The `dir <- tempdir()` is not used in `getENCODEdata`.
* Avoid writing to the users file system without explicit instruction.
The `output_folder` in `saveAlignments` should be `tempdir` instead of `.`.

## tests

* We strongly recommend adding unit tests for more robust code.

**Comment by LiNk-NY** [comment]
Hi JianHong, @jianhong 
Please respond to the review when you're ready. 
Thank you.
-Marcel

**Comment by jianhong** [comment]
Hi Marcel,

Yes, the package is ready for review again. Sorry I missed this step.

**Comment by LiNk-NY** [comment]
Hi JianHong, @jianhong 
We would like you to respond to the review line by line. 
Thank you for your contribution. 
Best,
Marcel

**Comment by jianhong** [comment]
Hi Marcel,

I add multiple single line comments in 

https://github.com/jianhong/enhancerHomologSearch/commit/fcf0e41fc8500971f8e53212a44008bf9e9de2a7#r53899615

to indicate the changed lines. Let me if that does not work.

> # enhancerHomologSearch #2181
> ## DESCRIPTION
> * Include a `BugReports` and `URL` field.

Added `BugReports` and `URL` in DESCRIPTION.

> * Looks good.
> 
> ## NAMESPACE
> * The usual Bioconductor convention is to use a capital letter name for
>   class names, e.g., `SummarizedExpeirment` vs `enhancers`.
> 

Changed the class name from `enhancers` to `Enhancers`.

> ## vignettes
> * Concise. Looks good.
> * Add an installation section using `BiocManager`.

Added a section "Installation"

> * Avoid using double `$` which suggests a nested list. Perhaps use S4
>   extractors and replacers.
> 

Added multiple S4 extractor and replace methods: distance, genome, seqinfo, peaks. 

> ## R
> * Use a single worker by default in the examples (`alignmentOne`).

Changed the default workers from 2 to 1 in documentation of `alignmentOne`.

> * Create helper functions to check for typical cases (those in `stopifnot`)
>   and re-use them in `alignmentOne` and `alignment`, for example.

Helper function `checkQuerySubject ` were added.

> * Consider using explicit / documentable arguments in the `enhancers`
>   constructor function rather than the elipses `...`.

Rewrote the constructor function by removing the \dots.

> * Avoid using `$` for extraction or setting of a slot. Create a dedicated
>   extractor function, e.g., `assay` method for `SummarizedExperiment`. `$` are
>   indicative of list classes and can cause confusion when used outside of that
>   context.

Added multiple S4 extractor and replace methods: distance, genome, seqinfo, peaks. 

> * Consider using caching in `getENCODEdata`, possibly via `BiocFileCache`.

Added `BiocFileCache`  to cache the downloaded files in `getENCODEdata`

> * The `dir <- tempdir()` is not used in `getENCODEdata`.

The line is removed.

> * Avoid writing to the users file system without explicit instruction.
>   The `output_folder` in `saveAlignments` should be `tempdir` instead of `.`.
> 

Replaced '.' by `tempdir()`

> ## tests
> * We strongly recommend adding unit tests for more robust code.

Added multiple unit tests.

**Comment by LiNk-NY** [comment]
Hi Jianhong, @jianhong 

Thank you for making those changes. Please bump the `Z` version (in x.y.z) of the package and push upstream for another build. 

I would also recommend contacting the maintainers of `msa` to ask them to fix the conflicting versions of `gc` by either updating or downgrading the `gc` they provide in the package. Note that without a working version of `msa`, users cannot use your package. See here for more details: https://support.bioconductor.org/p/132420/

Best regards,
Marcel

**Comment by jianhong** [comment]
I forget they were lacking ability to maintain the package. I will try to contact them to keep the package updated.

**Comment by LiNk-NY** [comment]
Thank you Jianhong @jianhong for following up.
I would also re-consider relying on a fragile package. 

Your package has been accepted to Bioconductor, 
thank you for your submission.

Best regards,
Marcel

**Comment by jianhong** [comment]
Hi Marcel,

Good suggestion. I will put it to my todo list.

Best!

Your sincerely,

Jianhong Ou

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jianhong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("enhancerHomologSearch")`. The package 'landing page' will be created at

https://bioconductor.org/packages/enhancerHomologSearch

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
