### ISSUE TITLE
branchpointer

### ISSUE THREAD

**Issue by betsig** [Bioconductor/Contributions#219]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/betsig/branchpointer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@LiNk-NY  will review this package, but I note that you will almost certainly want to re-use rtracklayer::import() for parsing GTF files (rather than 'rolling your own') and will want to use GenomicRanges::GRanges() for representing ranges in a robust and interoperable way.

**Comment by LiNk-NY** [comment]
Hi Beth @betsig,
Thank you for submitting to Bioconductor. 

Your package currently has an error in the vignette. 

```
    * ERROR: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.
```

It appears that your front matter has improper syntax. Your `%\Vignette*` lines have to be in their own line and without a "vignette:" _key_. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Beth @betsig, 
Thank you for your submission. Please find the package review below. 
If you have any questions, please let me know. 
Best regards,
Marcel 

---

### Branchpointer

Overall, the package uses some Bioconductor resources such as `rtracklayer` and some extractors from `GenomicRanges`. It could be made more inter-operable if you were to use a `GRanges` class for your manipulations. Much of the code written in the package operates on a `data.frame` rather than the more convenient `GRanges` representation. 

#### Package format
* It's good to include scripts used for publications in the package. Please move it to `inst/scripts`. 
* It may be possible to combine some `*.R` files based on functional groupings. 

#### Data structures
* A lot of manipulations in the package involve `data.frame` subsetting. This can get a little messy especially if you're subsetting by index. Please use a structured class (i.e., `GRanges`) with accessors to ensure that the correct type of data is extracted. 

#### Grammar
* Reduce/consolidate the checking done in `getBranchpointSeq`. Perhaps use a table or create a class with some validity checks and operate on said class. Create a character vector of error messages for output. 
* I wouldn't recommend exporting the `getCanonical335` function. It doesn't seem to do much and perhaps can be included as a helper function? 
* Break up the attributes line argument for the `getPPT` function. Provide a function with defaults rather than expecting index `3` to contain the data you need. 
* We recommend to not use underscores `_` in argument names. If you have to use a delimiter, try using dots `.` for switch type arguments. 
* The `gtfToExons` function should only load data to the environment and not write it. The user can do that separately. 

Thank you for your submission! 

Marcel

**Comment by betsig** [comment]
Hi Marcel @LiNk-NY 

**Changes made as follows:**

The package now works primarily on the Granges class.
Consequently a lot of the functions have been slightly modified to work with this instead of data.frames.
`getPPT` now doesn't rely on correct indexing due to this change.

The example script has been moved to` inst/scripts`.

`getBranchpointSequence `checks are now reduced to two.

`getCanonical335` along with other functions (`exonsToIntrons`, `getExonDists`, `getPPT`, `getBranchpointSequence`) have been made into internal functions, as users should not need to call them.

Argument names were changed to camel case and "." used where appropriate.
I have kept the colnames of GRanges metadata with underscores, as this keeps with the convention used by GTF files. 

`gtfToExons` now will not write a file.

Kind Regards,
Beth

**Comment by LiNk-NY** [comment]
Hi Beth @betsig,
Thank you for making those changes!
I will review them shortly.
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Beth @betsig, 
Please make sure you are using `GRanges` accessor functions for exposing data in the class. For example, use `strand(grange)` instead of `grange@strand` and `mcols(grange)` instead of `grange@elementMetadata`. 

Regards,
Marcel

**Comment by betsig** [comment]
Hi @LiNk-NY,

The build report is giving "Failed to locate the 'texi2pdf' output file (by engine 'knitr::knitr') for vignette with name 'branchpointer'" 
on ONLY the windows build.

I'm not sure what the issue is here and to fix it.
The vignette is unchanged from the previous working build.
Can you advise?

Regards,
Beth

**Comment by LiNk-NY** [comment]
Hi Beth @betsig, 
Sorry about the delay. This is an issue with the build system and not the package. The build on the other systems looks good. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Beth @betsig, 
Your package is close to approval! 
Just make a few minor changes and it will be ready. 

* Avoid growing a vector - See the preallocate and fill section in the [package guidelines](http://www.bioconductor.org/developers/how-to/efficient-code/#vectorize) and [R/predictBranchpoints.R#318](https://github.com/betsig/branchpointer/blob/master/R/predictBranchpoints.R#L318) in your code. 

Quick minor tips: 
* Keep your `grepl` calls should be more robust. If you are just looking for an exact match in the vector, use the `%in%` operator. 
```
# Instead of
grepl("biotype", colnames(mcols(gtf.track)))
# try
"biotype" %in% tolower(colnames(mcols(gtf.track)))
```


Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Beth @betsig,
Thank you for contributing to Bioconductor, your package has been accepted! 

Best regards,
Marcel
