### ISSUE TITLE
GEOexplorer

### ISSUE THREAD

**Issue by guypwhunt** [Bioconductor/Contributions#2191]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/guypwhunt/GEOexplorer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Guy, @guypwhunt 

Thank you for your submission.
Please fix the typo error in the build report. 
Below is the package review.
Feel free to ask any questions. 

Best,
Marcel

---

# GEOexplorer #2191

## DESCRIPTION

* (optional) Keep to the 80 character width limit in the `DESCRIPTION` file
for easier review.
* Update the `License` field.
* Include packages such as `shiny` in the `Depends` field since you use the
functions in the package extensively.
* Add `Biobase` dependency to the `DESCRIPTION` when using functions like
`exprs` and `pData`.

## NAMESPACE

* The function names are quite long but are these user-level functions?
* Perhaps these funcitons need not be exported given that it is a `shiny`
package.

## vignettes

* Restricting the text to the 80 character-width limit is better for reviewing
and even maintaining.
* I think the vignette for a shiny-app package should include
screenshots that show the user how to interact with the app and the coding
should be minimal.
* Can a user input code from the shiny app?

## R

* Remove `library` calls from inside functions (see note in `DESCRIPTION`).
* The functions provided do not need to be exported for the shiny app, AFAICT.
* Perhaps you may want to separate the analysis and visualization functions
from the shiny funcitonality into separate packages?
* Functions like `convertAdjustment` should probably be a lookup table rather
than a series of `if` `else` statements.

## /

* Please remove the errors folder.
* Sourcing the R files should not be necessary in `app.R`.
* Remove the `rsconnect` folder. This should only be on your local computer.

## tests

* Looks good.

**Comment by guypwhunt** [comment]
> Hi Guy, @guypwhunt
> 
> Thank you for your submission.
> Please fix the typo error in the build report.
> Below is the package review.
> Feel free to ask any questions.
> 
> Best,
> Marcel
> 
> # GEOexplorer #2191
> ## DESCRIPTION
> * (optional) Keep to the 80 character width limit in the `DESCRIPTION` file
>   for easier review.
> * Update the `License` field.
> * Include packages such as `shiny` in the `Depends` field since you use the
>   functions in the package extensively.
> * Add `Biobase` dependency to the `DESCRIPTION` when using functions like
>   `exprs` and `pData`.
> 
> ## NAMESPACE
> * The function names are quite long but are these user-level functions?
> * Perhaps these funcitons need not be exported given that it is a `shiny`
>   package.
> 
> ## vignettes
> * Restricting the text to the 80 character-width limit is better for reviewing
>   and even maintaining.
> * I think the vignette for a shiny-app package should include
>   screenshots that show the user how to interact with the app and the coding
>   should be minimal.
> * Can a user input code from the shiny app?
> 
> ## R
> * Remove `library` calls from inside functions (see note in `DESCRIPTION`).
> * The functions provided do not need to be exported for the shiny app, AFAICT.
> * Perhaps you may want to separate the analysis and visualization functions
>   from the shiny funcitonality into separate packages?
> * Functions like `convertAdjustment` should probably be a lookup table rather
>   than a series of `if` `else` statements.
> 
> ## /
> * Please remove the errors folder.
> * Sourcing the R files should not be necessary in `app.R`.
> * Remove the `rsconnect` folder. This should only be on your local computer.
> 
> ## tests
> * Looks good.

Good morning Marcel

It is nice to E-meet you.

Thank you for the feedback. I have made all the necessary updates.

I am just looking at the check and build bin errors and warnings.

All the best,
Guy

**Comment by LiNk-NY** [comment]
Hi Guy, @guypwhunt 

Please respond to the review line by line. 
Thank you for your contribution. 

**Note**. There are still some errors in `check` stage of the package. Please resolve those.

Best,
Marcel

**Comment by guypwhunt** [comment]
Good afternoon Marcel @LiNk-NY  

I hope you had a lovely weekend.

I have fixed all the check errors and timeouts.

There are a couple of warnings remaining.

Do I need to fix the warnings as well before we proceed to the next step? 

Thanks for all your help, it is really appreciated.

All the best,
Guy

**Comment by guypwhunt** [comment]
Good afternoon Marcel @LiNk-NY 

I fixed all the warnings as well. So ignore my last comment.

What is the next step?

Thanks for all your help.

All the best,
Guy

**Comment by LiNk-NY** [comment]
Hi Guy, @guypwhunt 

Please respond to the review item by item and mention the changes you've made. 

https://github.com/Bioconductor/Contributions/issues/2191#issuecomment-887708814

Thank you!

Best,
Marcel

**Comment by guypwhunt** [comment]
Afternoon Marcel @LiNk-NY 

Of course, my friend. Below are the details of the errors, warnings and notes fixed for each version plus the updates.

### General updates:
**Description file**
Reduced lines to 80 characters or less
Updated license to standard license specification
Depends updated with shiny, limma, Biobase, plotly

**Namespace file**
Remove all unnecessary exports

**Vignettes file**
Reduced lines to 80 characters or less
Included screenshots that show the user how to interact with the app

**Unit tests**
The unit tests were consolidated to avoid timeout issues and more scenarios were added

**R folder**
Remove library calls from inside functions
Updated convertAdjustment to a lookup table

**Additional files**
Removed unnecessary files


### Version Updates
**Version 99.2**
Error: processing vignette 'my-vignette.Rmd' failed with diagnostics: could not find function "nonInteractiveDesnityPlot"
Update: Vignettes spelling error updated

**Version 99.3**
Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata.
Update: Vignettes file name updated

**Version 99.4**
ERROR: Package Source tarball exceeds Bioconductor size requirement. 
Update: Reduced picture sizes in Vignettes folder

WARNING: The following files are over 5MB in size: 'inst/doc/GEOexplorer.html'
Update: Reduced size of large files

ERROR: Maintainer must subscribe to the bioc-devel mailing list. Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
Update: I subscribed to the bioc-devel mailing list

ERROR: Maintainer must add package name to Watched Tags on the support site; Edit your Support Site User Profile to add Watched Tags.
Update: I added the watched tags

**Version 99.5**
WARNING: Undocumented arguments in documentation object 'nonInteractiveBoxAndWhiskerPlot' platform 
Undocumented arguments in documentation object 'nonInteractiveUmapPlot' knn
Undocumented arguments in documentation object 'sourceServer' input output session
Functions with \usage entries need to have the appropriate \alias entries, and all their arguments documented. The \usage entries must correspond to syntactically valid R code. See chapter Writing R documentation files in the Writing R Extensions manual.
Update: Update functions examples with all required variables

**Version 99.6**
WARNING: Malformed Title field: should not end in a period.
Update: Removed the period from the title field

NOTE: Rd file 'calculateDifferentialGeneExpression.Rd': \examples lines wider than 100 characters: fit2 <- calculateDifferentialGeneExpression(gsms, limmaPrecisionWeights, forceNormalization, gsetData, knnDataInput) 
Update: Remove non-exported Rd files

ERROR: Running examples in GEOexplorer-Ex.R failed
Update: Remove non-exported Rd files

ERROR: Running the tests in tests/testthat.R failed.
Update: Updated unit tests to look at the length of string responses

**Version 99.7**
N/A: cosmetic updates

**Version 99.8**
ERROR: Running the tests in tests/testthat.R failed.
Update: Consolidated unit tests to prevent timeout. This reduced the number of API calls required, and therefore reduced the test time but all functions were still tested.

**Version 99.9**
NOTE: Consider adding 
importFrom("grDevices", "palette") 
importFrom("graphics", "abline", "boxplot", "hist", "par", "text")
importFrom("stats", "complete.cases", "cor", "model.matrix", "na.omit", "prcomp", "princomp", "quantile")
Update: Added import statements to functions, namespace and description files

WARNING: Add non-empty \value sections to the following man pages: man/loadApp.Rd
Update: Added value section to loadApp function

NOTE: Consider shorter lines; 409 lines (10%) are > 80 characters long
Update: Formatted and reduced lines to less than 80 characters were possible

Additional update: further unit testing added

**Version 99.10**
ERROR: Running the tests in tests/testthat.R failed.
Update: Updated unit testing to look at the length of string responses rather than long string texts. 

**Version 99.11**
Error: package or namespace load failed for GEOexplorer in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called impute
Update: Namespace rewritten

ERROR: Running the tests in tests/testthat.R failed.
Update: Bug fixes and added additional unit tests for more scenarios

**Version 99.12**
ERROR: Running the tests in tests/testthat.R failed
Update: Removed test_microarrayGseWithPoorDataQuality.R unit test as it required the Sys.setenv("VROOM_CONNECTION_SIZE") to be updated and is largely tested during the test_microarrayGseWithMissingValues.R unit test

**Version 99.13**
NOTE: calculateTopDifferentiallyExpressedGenes: warning in topTable(fit2, adjust = adjustment, sort.by = "B", number = 250): partial argument match of 'adjust' to 'adjust.method'
Update: Updated of 'adjust' to 'adjust.method' in necessary functions

**Version 99.14**
WARNING: Found the following significant warnings:
Warning: replacing previous import ggplot2::last_plot by plotly::last_plot when loading GEOexplorer
Warning: replacing previous import shiny::dataTableOutput by DT::dataTableOutput when loading GEOexplorer
Warning: replacing previous import shiny::renderDataTable by DT::renderDataTable when loading GEOexplorer
Update: Updated of functions and namespace to exclude last_plot from ggplot2 and dataTableOutput and renderDataTable from shiny import

WARNING: Non-standard license specification
Update: Updated description file with standard license specification

Let me know if you have any questions or need anything else from my side.

All the best,
Guy

**Comment by LiNk-NY** [comment]
Hi Guy, @guypwhunt 

Thank you for making those changes. 
Please make sure to resolve this note. You can use `utils::globalVariables`. 

```r
* checking R code for possible problems ... NOTE
interactiveMeanVariancePlot: no visible binding for global variable
  ‘ID’
interactivePrcompPcaIndividualsPlot: no visible binding for global
  variable ‘ID’
interactivePrincompPcaIndividualsPlot: no visible binding for global
  variable ‘ID’
sourceServer: no visible binding for '<<-' assignment to ‘gsetData’
sourceServer: no visible binding for global variable ‘gsetData’
sourceServer: no visible binding for '<<-' assignment to
  ‘expressionData’
sourceServer: no visible binding for global variable ‘expressionData’
sourceServer: no visible binding for '<<-' assignment to ‘dataInput’
sourceServer: no visible binding for global variable ‘dataInput’
sourceServer: no visible binding for '<<-' assignment to ‘knnDataInput’
sourceServer: no visible binding for global variable ‘knnDataInput’
sourceServer : <anonymous>: no visible global function definition for
  ‘write.csv’
Undefined global functions or variables:
  ID dataInput expressionData gsetData knnDataInput write.csv
Consider adding
  importFrom("utils", "write.csv")
to your NAMESPACE file.
```

Your package has been accepted. 
Thank you for your contribution. 

Best regards,
Marcel

**Comment by guypwhunt** [comment]
Thanks, Marcel @LiNk-NY 

In version 0.99.16 and version 0.99.17 I:
- Removed the global variables.
- Added error handling to handle the variables that are now not global.
- Added importFrom("utils", "write.csv") to namespace file and function.
- Added import utils to Description file.

Thanks for all your help.

All the best,
Guy

**Comment by LiNk-NY** [comment]
Thank you Guy for following up. :+1: 
Best, 
Marcel

**Comment by guypwhunt** [comment]
No problem Marcel 

All the best,
Guy

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/guypwhunt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GEOexplorer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GEOexplorer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
