### ISSUE TITLE
BaalChIP

### ISSUE THREAD

**Issue by InesdeSantiago** [Bioconductor/Contributions#22]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/InesdeSantiago/BaalChIP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by InesdeSantiago** [comment]
I changed the version to 0.99.1

**Comment by InesdeSantiago** [comment]
Changed typis in "Author" and "Maintainer" in the DESCRIPTION FILE

**Comment by mtmorgan** [comment]
Can you explain why you closed this issue? I guess you mean that you do not want to submit to Bioconductor?

**Comment by InesdeSantiago** [comment]
Sorry, I thought I had to close once I fixed the problem.

**Comment by mtmorgan** [comment]
@InesdeSantiago It looks like you've been developing your package, but that there is still quite a ways to go. I suggest that we close the current issue, that you continue to develop your package in your github repository, running `R CMD build BaalChIP` / `R CMD check BallChIP_*gz` (or other tools, like the devtools package) until it is closer to complete, and then open a new issue for package review. If you have questions about package development for Bioconductor in particular, please don't hesitate to ask on the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

Does that sound ok?

**Comment by InesdeSantiago** [comment]
Ok, no problem. I will submit later on.
thank you.
All the best,
ines

**Comment by InesdeSantiago** [comment]
Hello. The package is ready, but the bot doesnt seem to start the build automatically.

**Comment by mtmorgan** [comment]
What's the status of the package?  I see that you re-opened / closed the issue. If it's ready for review, let me know via a comment on this issue and I'll manage the next build.

**Comment by InesdeSantiago** [comment]
Hello, yes, it is ready for review. 
thank you!

**Comment by InesdeSantiago** [comment]
I corrected the error (a non-ASCII character) and made a valid Push. But I think it should start automatically.. it didnt!

**Comment by mtmorgan** [comment]
Is the web hook https://github.com/Bioconductor/Contributions#adding-a-web-hook still active?

**Comment by InesdeSantiago** [comment]
it was, I deleted it and added it again. Then I updated the version again and did a push. Hopefully it will work! thank you very much for all your help!

**Comment by mtmorgan** [comment]
OK, sorry for the problems. I'll trouble-shoot from our end tomorrow and let you know...

**Comment by mtmorgan** [comment]
Issues require the '2. review in progress' label to be associated with the issue, so I've added that. If you could try again with a version bump and commit...

I think also though that even with the label missing there should have been a comment posted to this issue, so please also verify that the web hook is exactly right before doing the version bump and commit.

If this fails, it will help to make me a 'Collaborator' on your project, via the 'Settings' widget at the top right of your repository.

**Comment by InesdeSantiago** [comment]
Hi. Do I need to do anything else now? I think it passed

**Comment by mtmorgan** [comment]
I'll review this package and post the review here...

**Comment by mtmorgan** [comment]
DESCRIPTION, NAMESPACE

- good

R

- rather than using `new("BaalChIP", ...)` create a constructor function

        BaalChIP <- function(samplesheet, hets, ...) {
            ## arg checking, coercion, etc...
            new("BaalChIP", ...)
        }

  the function can have named arguments and can be separately
  documented, helping the user in object creation. A constructor
  separates the 'interface' from the 'implementation', making it
  easier for you to make changes in class representation that do not
  wreck havoc with your users.
  
  Likewise, create simple 'accessor' functions rather than direct slot
  access like objects@hets, etc. Use the accessors everywhere.

- avoid using `cat()` for progress updates; use
  `message()`. `message()` sends output to stderr, the standard stream
  for diagnostic messages.
  
- avoid `1:nrow(snps)` and similar, which produce unexpected results
  when `nrow(snps) == 0`; use `seq_len(nrow(snps))` instead.
  
- use `drop=FALSE` when sub-setting data.frames, unless you are certain
  that users' data can result in 1-row or 1-column data frames that
  will be dropped unexpectedly to vectors.
  
- avoid paradigms like
  https://github.com/InesdeSantiago/BaalChIP/blob/master/R/applyBayes.R#L32
  where a vector grows over iterations of a `for` loop. Instead,
  pre-allocate and fill or use `lapply()` or similar to manage list
  creation. See
  http://bioconductor.org/developers/how-to/efficient-code/#common-solutions

- avoid iteration (`for` loops, `lapply()`, etc) in favor of
  vectorization, e.g., at
  https://github.com/InesdeSantiago/BaalChIP/blob/master/R/applyBayes.R#L150
  which might be written along the lines of (untested!)
  
        id_tf <- seq_len(TF_num)
        Ref_count <- SNP_hit_Peaks_sum[i, 2 + 3 * (id_tf - 1) + 1]
        total_count <- SNP_hit_Peaks_sum[i, 2 + 3 * (id_tf - 1) + 2]
        idx <- SNP_hit_Peaks_sum[i, 2 + 3*(id_tf - 1)] == 1

        for (id_tf1 in id_tf[idx])
            temp[id_tf1] <- log(pi) +
                log_genotype_llh(Ref_count, total_count, bias_in, allele_bias,
                                 precision)

  If I'm reading the code correctly, I think that `log_genotype_llh()`
  can itself be adjusted to work on vector arguments, so the loop is
  not necessary at all. Working on this chunk of code would seem to be
  worth-while, perhaps removing the need for parallel evaluation.

- (Optional) We encourage but do not require the use of BiocParallel
  as a unified back-end.
  
- (Optional) Consider formatting your code in a more traditional and
  consistent manner, e.g., using the formatR package

vignettes

- minimize the number of lines of code in `eval=FALSE` chunks (e.g.,
  construct objects and load data in evaluated chunks) to reduce the
  opportunity for 'bit rot' to compromise the correctness of your
  vignette.

man

- improve the provenance of the UniqueMappability50bp_hg19,
  ENCODEexample, and other large objects by including the code used to
  retrieve and generate these objects.

Other

- the content of the inst/extra directory does not seem very useful to
  other users, e.g., containing hard-coded file paths and making
  narrow assumptions about the availability and location of external
  software tools. The perl script seems easily implemented in R?
  
- Consider adding more extensive unit tests; these are essential for
  producing and maintaining high-quality code.

**Comment by mtmorgan** [comment]
Once it _does_ pass (it'll built when the version number changes) can you please provide a brief description of how you responded to the issues in the review?

**Comment by InesdeSantiago** [comment]
Hi Martin, i am still working on the issues. I did a commit but it is not
the final one. I will get back to you soon with details on how I have delt
with all issues. Ines

**Comment by InesdeSantiago** [comment]
Dear Martin,
I have extensively reviewed the package code and have now implemented all suggestions. 
Please see below details about how I address each of the points raised.
I will add the paper reference as soon as the paper is out (still under review).
Thank you for all the helpfull input.
Looking forward to see BaalChIP on the next bioconductor release! 
ines

R:
1) I created a contructor function "BaalChIP" rather than using "new". Replaced the examples in the manual pages and in the vignette
2) Included accessor function (getBaalSlot) everywhere - instead of direct slot access like object@hets
3) Used message() for progress updates - instead of cat 
4) Replaced 1:nrow() by seq_len(nrow()) everywhere. And also 1:length() by seq_len(length()). This avoids the cases that do not handle 0 length.
5) I now make use of drop=FALSE when sub-setting data.frames, to make sure that the output is not an unexpected data type.
6) I replaced all the unnacessary for loops by lapply/sapply to make the code more efficient and avoid paradigms  

vignettes:
7) Replace "new" by the "BaalChIP" constructor function
7) Minimized a number of lines in the code with eval=FALSE. Before I had >20% eval=FALSE. (10 out of 42 chunks). Now I have 5 eval=FALSE.
8) Used formatR to format the code 

manual:
9) The provenience of UniqueMappability50bp, blacklisted_hg19 and pickrell_hg19 are now given in help page of those objects. Added more details about those 3 objects
10) The provenience of ENCODEexample comes from a paper (under review) and this is now also stated in the help page.

other:
11) the content in inst/extra directory now accepts user arguments for file paths instead of hard-coded file paths and making narrow assumptions about the availability and location of external software tools. I added the documentation ot this argument in the vignette with examples.
12) Added extensive unit tests. Added 14 new unit tests. 

Looking forward,
ines
