### ISSUE TITLE
netOmics

### ISSUE THREAD

**Issue by abodein** [Bioconductor/Contributions#2204]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/abodein/netOmics

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Thank you for submitting to Bioconductor. Please see initial review below: 


**BUILD REPORT:**

- [ ] Please clean up as many notes as possible


**README:**

- [ ] Please include Bioconductor installation instructions using BiocManager


**DESCRIPTION:**


- [ ] (Optional) we recommend `lazyData: false` as setting to true we have
  rarely found useful and could slow package installation.

- [ ] Typo  “combinasion” -> “combination”

- [ ] We would encourage updating R dependency to `(>= 4.1)`

- [ ] A package URL and BugReports field is encouraged althougth not required

**NAMESPACE:**


- [ ] See build report on suggested importFrom

- [ ] It may be worth selectively importing from packages instead of importing
  the whole package. (E.G. using importFrom instead of import)


**data**


- [ ] Please expand on the man page for the data file. Please include source
  information and any processing that was done to create the object

**package man**

- [ ] (Optional) we would hightly encourage have a package man page so users
  would be directed to the main functions of the packages when doing `?netOmics`
  in R

- [ ] man page examples would be easier to read with additional linebreaks after
  function arguments


**vignette**

- [ ] Please change the vignette name. Generic names like vignette or intro have
  a tendency to conflict with other package vignette names. Depending on the
  package load order if a user does `vignette("vignette")` they might not get
  your vignette when expected; in fact currently it will load the mixOmics
  vignette instead of netOmics.

- [ ] I notice your VignetteIndexEntry is timeOmics? perhaps this should be
  updated to `netOmics`?

- [ ] Please show Bioconductor installation instructions.

- [ ] When I'm trying to run your optional code. I assumed I could plug in
  `hmp_T2D$raw` for raw and be able to run the check which is not the case

```
> data.filter <- imap(hmp_T2D$raw, ~{remove.low.cv(.x, cutoff = fc.threshold[[.y]])})
Error in `[.data.frame`(X, , cv > cutoff) : undefined columns selected

```

Please make sure shown code works and is able to be replicated.


- [ ] SpiecEasi is not a valid R package in that it is not on CRAN or
  Bioconductor. You probably should reference the repo you used for this
  section. Obviously since being on CRAN and Bioconductor is a requirement for
  all dependencies, it is correct to leave this code in eval=FALSE. We don't
  necessarily recommend adding not evaluated packages that are not on CRAN or
  Bioconductor as there are no checks. 

- [ ] In the basics network exploration section 7.1.
  How long should this take to run `res.mod <-
  edge.betweenness.community(FULL$All)` when I was walking through your code, I
  ended up killing this command as I wasn't sure the time period to complete and
  was over several minutes long? It would be good to have a time estimate there.

- [ ] There seem to be a few typos. Please consider re-reading for ERRORs

- [ ] considering add a `sessionInfo` at the end of the vignette

- [ ] Please try to keep to an 80 character limit as the code will otherwise be
  difficult to read when displayed online. One suggested alternative is to
  include linebreaks after function arguments.

**General comments after running through vignette**

- [ ] Since you are referencing evaluation of expression data, It is common and
  recommended practice to be able to also use a SummarizedExperimen.  This can
  be as simple as being able to pass these objects into your functions, checking
  the class, and if it is a class object extracting the data.frame as needed and
  proceeding with your code implementation.

- [ ]  Do your functions always need to fully complex list of lists objects or can
  individual data.frames be provided at each step?


**R code / man pages**

- [ ] See coding practice notes in the build report. All of these NOTES should
  try and be addressed.

- [ ] Try and be consistent with coding style. Some basic recommendation can be
  found [here](https://bioconductor.org/developers/how-to/coding-style/). It is
  only recommended but can make the code easier to read.

- [ ] Comments in code are encouraged but please remove any unused/comment out
  code.

- [ ] stop/warning/message does not need a paste0 call. They do a paste0
  automatically so it is an inefficiency. (mostly in utils.R)

- [ ] You seem to set a custom class (e.g. interaction.igraph) for various object but these classes aren’t
defined or documented anywhere. Please provide more information about what these classes are
and how they should be used. Accessors like getters/setters would also be
recommended depending on the functionality and key featuers/data of the class.

- [ ] please consider adding more linebreaks, as the code is currently
somewhat hard to read, especially when viewed online (e.g., on GitHub).
The recommended maximum number of characters per line is 80.
E.g., the simplest way to make the code more readable would be
to add linebreaks after pipes (%>%).

- [ ] Consider changing for loops to vapply (recommended) or lapply. They make
  the code much more efficient when iteration over vector/list elements.
  E.G:

```
# this...
# (note that 'names(X)' are retained automatically)
db.subgraph.list <- lapply(X, function(x) {
    .interaction_from_dataframe(
        X = x, 
        db = db, 
        ego = user.ego, 
        type = type)
    })

# ...instead of
db.subgraph.list <- list()
for (i in names(X)) {
db.subgraph.list[[i]] <- .interaction_from_dataframe(
    X = X[[i]], 
    db = db, 
    ego = user.ego, 
    type = type)
}
```

- [ ] (optional) Is there an opportunity to parallize any of the loops as well
  to improve efficiency? 


When ready please remember to do a version bump and push to git.bioconductor.org to trigger a new build report.  Please also comment back here with what has been addressed or any comments regarding concerns above and requesting a re-review. Cheers!

**Comment by lshep** [comment]
Hello,  Just checking in to see if we can expect any updates soon? We like to see updates in 2-3 weeks to keep a review moving

**Comment by abodein** [comment]
Hi @lshep, 
I have just returned to the office after a summer holiday. I will review the package within the week.
Thank you.

**Comment by abodein** [comment]
Hello @lshep, 

Thank you for the review of our package. 
Almost all comments have been addressed. 
We have commented on the remarks for which we could not answer.
Please see the remarks below.

> **BUILD REPORT:**
> 
>     * [x]  Please clean up as many notes as possible
>> We fixed as many NOTEs as possible. However, there are still a few notes concerning the length of the functions, the limit on the number of characters per line, the number of spaces per tab and the clarification of the initialization of objects.
> 
> 
> **README:**
> 
>     * [x]  Please include Bioconductor installation instructions using BiocManager
> 
> 
> **DESCRIPTION:**
> 
>     * [x]  (Optional) we recommend `lazyData: false` as setting to true we have
>       rarely found useful and could slow package installation.
> 
>     * [x]  Typo  “combinasion” -> “combination”
> 
>     * [x]  We would encourage updating R dependency to `(>= 4.1)`
> 
>     * [x]  A package URL and BugReports field is encouraged althougth not required
> 
> 
> **NAMESPACE:**
> 
>     * [x]  See build report on suggested importFrom
> 
>     * [x]  It may be worth selectively importing from packages instead of importing
>       the whole package. (E.G. using importFrom instead of import)
> 
> 
> **data**
> 
>     * [x]  Please expand on the man page for the data file. Please include source
>       information and any processing that was done to create the object
> 
> 
> **package man**
> 
>     * [x]  (Optional) we would hightly encourage have a package man page so users
>       would be directed to the main functions of the packages when doing `?netOmics`
>       in R
> 
>     * [x]  man page examples would be easier to read with additional linebreaks after
>       function arguments
> 
> 
> **vignette**
> 
>     * [x]  Please change the vignette name. Generic names like vignette or intro have
>       a tendency to conflict with other package vignette names. Depending on the
>       package load order if a user does `vignette("vignette")` they might not get
>       your vignette when expected; in fact currently it will load the mixOmics
>       vignette instead of netOmics.
> 
>     * [x]  I notice your VignetteIndexEntry is timeOmics? perhaps this should be
>       updated to `netOmics`?
> 
>     * [x]  Please show Bioconductor installation instructions.
> 
>     * [x]  When I'm trying to run your optional code. I assumed I could plug in
>       `hmp_T2D$raw` for raw and be able to run the check which is not the case
> 
> 
> ```
> > data.filter <- imap(hmp_T2D$raw, ~{remove.low.cv(.x, cutoff = fc.threshold[[.y]])})
> Error in `[.data.frame`(X, , cv > cutoff) : undefined columns selected
> ```
>> For some reason, I don't understand why this command failled. Now the object is casted as a matrix and it works fine.

> Please make sure shown code works and is able to be replicated.
> 
>     * [x]  SpiecEasi is not a valid R package in that it is not on CRAN or
>       Bioconductor. You probably should reference the repo you used for this
>       section. Obviously since being on CRAN and Bioconductor is a requirement for
>       all dependencies, it is correct to leave this code in eval=FALSE. We don't
>       necessarily recommend adding not evaluated packages that are not on CRAN or
>       Bioconductor as there are no checks.
> 
>     * [x]  In the basics network exploration section 7.1.
>       How long should this take to run `res.mod <- edge.betweenness.community(FULL$All)` when I was walking through your code, I
>       ended up killing this command as I wasn't sure the time period to complete and
>       was over several minutes long? It would be good to have a time estimate there.
>> This chunk is note evaluated. Running time is based on the size of the graph and edge betweenness may take several minutes for larger graphs.
> 
>     * [x]  There seem to be a few typos. Please consider re-reading for ERRORs
> 
>     * [x]  considering add a `sessionInfo` at the end of the vignette
> 
>     * [x]  Please try to keep to an 80 character limit as the code will otherwise be
>       difficult to read when displayed online. One suggested alternative is to
>       include linebreaks after function arguments.
> 
> 
> **General comments after running through vignette**
> 
>     * [x]  Since you are referencing evaluation of expression data, It is common and
>       recommended practice to be able to also use a SummarizedExperimen.  This can
>       be as simple as being able to pass these objects into your functions, checking
>       the class, and if it is a class object extracting the data.frame as needed and
>       proceeding with your code implementation.
>> We appreciate this recommendation, however the package is intended to be used in conjunction with others and we prefer to keep the consistency of the objects across these different packages. 
>
>     * [x]   Do your functions always need to fully complex list of lists objects or can
>       individual data.frames be provided at each step?
>> As mentionned above, we would like to keep the consistency of the user interfaces between the different packages.
> 
> **R code / man pages**
> 
>     * [x]  See coding practice notes in the build report. All of these NOTES should
>       try and be addressed.
> 
>     * [x]  Try and be consistent with coding style. Some basic recommendation can be
>       found [here](https://bioconductor.org/developers/how-to/coding-style/). It is
>       only recommended but can make the code easier to read.
>> We applied formatR on the R directory.
> 
>     * [x]  Comments in code are encouraged but please remove any unused/comment out
>       code.
> 
>     * [x]  stop/warning/message does not need a paste0 call. They do a paste0
>       automatically so it is an inefficiency. (mostly in utils.R)
> 
>     * [x]  You seem to set a custom class (e.g. interaction.igraph) for various object but these classes aren’t
>       defined or documented anywhere. Please provide more information about what these classes are
>       and how they should be used. Accessors like getters/setters would also be
>       recommended depending on the functionality and key featuers/data of the class.
>> These objects are just S3 lists. The class tags just allow us to check internally the validity of the objects for each specific function.
>> These objects are generated and used by these specific functions. Furthermore, the output of these functions (the classes) are already documented.
>> Finally, because the objects are already handled by theses functions, we do not feel the need to add additional accessors.
> 
>     * [x]  please consider adding more linebreaks, as the code is currently
>       somewhat hard to read, especially when viewed online (e.g., on GitHub).
>       The recommended maximum number of characters per line is 80.
>       E.g., the simplest way to make the code more readable would be
>       to add linebreaks after pipes (%>%).
> 
>     * [ ]  Consider changing for loops to vapply (recommended) or lapply. They make
>       the code much more efficient when iteration over vector/list elements.
>       E.G:
> 
> 
> ```
> # this...
> # (note that 'names(X)' are retained automatically)
> db.subgraph.list <- lapply(X, function(x) {
>     .interaction_from_dataframe(
>         X = x, 
>         db = db, 
>         ego = user.ego, 
>         type = type)
>     })
> 
> # ...instead of
> db.subgraph.list <- list()
> for (i in names(X)) {
> db.subgraph.list[[i]] <- .interaction_from_dataframe(
>     X = X[[i]], 
>     db = db, 
>     ego = user.ego, 
>     type = type)
> }
> ```
>> We modified the simpler loop to use lapply instead of for. However, we kept the more complex loop that does multiple operations.
> 
>     * [ ]  (optional) Is there an opportunity to parallize any of the loops as well
>       to improve efficiency?
>> We do not currently parallize the loops.

**Comment by lshep** [comment]
A few minor comments: 

**vignette**

- [ ] The VignetteIndexEntry is still timeOmics insetead of your package name
  `netOmics`

- [ ] 7.1 several minutes may be an understatement. I ran the code with
  benchmark to try to get a time, and I killed it off after running for over an
  hour! In your example in the man page you use a little dummy example but have
  you actually tested it with real data and have benchmarks for time of
  analysis?



**General**

- [X] Bioconductor main class structure for expression data is a
  SummarizedExperiment. Your functions again, can as default use data.frames but
  there should be a minimal adaptablity to Bioconductor's main class
  strcutures. Again, as simple as testing if the input given is a data.frame or
  class of SummarizedExperiment and subset accordingly. But if you insist on
  keeping a data.frame please keep interoperability and being compatible with
  the highly used Bioconductor classes when you want to submit a Bioconductor
  package.

**Comment by abodein** [comment]
Hello @lshep , 
I fixed the last mistakes.

> **vignette**
> 
> * [x]  The VignetteIndexEntry is still timeOmics insetead of your package name
>   `netOmics`
> * [x]  7.1 several minutes may be an understatement. I ran the code with
>   benchmark to try to get a time, and I killed it off after running for over an
>   hour! In your example in the man page you use a little dummy example but have
>   you actually tested it with real data and have benchmarks for time of
>   analysis?

I removed this line. I used an other algorithm to perform modularity analysis which is faster.

> 
> **General**
> 
> * [x]  Bioconductor main class structure for expression data is a
>   SummarizedExperiment. Your functions again, can as default use data.frames but
>   there should be a minimal adaptablity to Bioconductor's main class
>   strcutures. Again, as simple as testing if the input given is a data.frame or
>   class of SummarizedExperiment and subset accordingly. But if you insist on
>   keeping a data.frame please keep interoperability and being compatible with
>   the highly used Bioconductor classes when you want to submit a Bioconductor
>   package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/abodein.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("netOmics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/netOmics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
