### ISSUE TITLE
ProteoDisco

### ISSUE THREAD

**Issue by J0bbie** [Bioconductor/Contributions#2206]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ErasmusMC-CCBC/ProteoDisco

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Hi @J0bbie ,

Thanks for submitting ProteoDisco.

The package looks good and is almost ready for acceptance. Please address the 2 minor issues below.
Thanks,

H.

- Please name your class union `DNAStringSet_OR_BSgenome` instead of `DNAStringSetORBSgenome`.

- The rendered HTML vignette is missing title and author(s). It starts immediately with the Abstract:

![Screenshot from 2021-08-17 09-49-15](https://user-images.githubusercontent.com/8810451/129767647-49a8b3ff-8c68-4790-a321-f0ae2a788c7c.png)

**Comment by J0bbie** [comment]
Hi @hpages,

Thanks for the review! My apologies for the late reply due to holidays.

After some ordeals with also trying to improve the test/example run-times by adding an example dataset instead of generating the example/test dataset from scratch each time, it finally works again with also the requested changes to the vignette / class.

Please let me know if anything else is required!

Kind regards,

Job van Riet

**Comment by hpages** [comment]
Hi @J0bbie ,

Thanks for the changes.

2 things:
1. The rendered HTML vignette still starts immediately with the Abstract and is still missing title and author(s).
2.  Your vignette contains a call to `ProteoDisco::generateJunctionModels()` that uses 20 workers (`threads = 20`). This will put too much stress on the Bioconductor build machines or on any machine where `R CMD build ProteoDisco` gets run.  Please do not use more than 4 workers in your vignette, examples, or unit tests.

I'm also not sure I see the value of renaming `workers` -> `threads` in your functions, but that's a minor consideration.
 
Thanks,
H.

**Comment by J0bbie** [comment]
Dear @hpages,

My apologies for the "threads = 20", it was left there during testing.. 
I've also reduced the nr. of large tests as it was sometimes giving a TIMEOUT due to one of our larger test-cases.

I've changed to engine from `%\VignetteEngine{knitr::knitr}` to `%\VignetteEngine{knitr::rmarkdown}` and hope that solved the issue as I also noticed that the .css wasn't getting loaded in your output.

Using `%\VignetteEngine{knitr::rmarkdown}` and `devtools::install_github(repo = "ErasmusMC-CCBC/ProteoDisco", build_vignettes = T)` on my external PC yielded a vignette incl. the authors.

Please let me know if this fixed the issue!

Kind regards,

Job van Riet

**Comment by hpages** [comment]
Thanks. Package is good to go.

Cheers,
H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/J0bbie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ProteoDisco")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ProteoDisco

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
