### ISSUE TITLE
scanMiRApp

### ISSUE THREAD

**Issue by plger** [Bioconductor/Contributions#2208]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ETHZ-INS/scanMiRApp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

@lshep @vjcitn , following-up on the scanMiR submission, I guess it makes more sense if someone already familiar with the whole thing handles the review?

**Comment by plger** [comment]
There's currently one check warning, namely the use of calls like:
`BSgenome.Hsapiens.UCSC.hg38:::BSgenome.Hsapiens.UCSC.hg38`
The idea is to make building the annotation easy, but not require a systematic installation of those genome packages, since a user might just need one of them (or none). The error message when it's not installed is pretty clear... but if you have better suggestions about how to proceed with this kind of issue, we're all ears!
Thanks in advance, PL

**Comment by plger** [comment]
sorry, a breaking commit had been pushed in the meantime... now we're back to just the aforementioned warning.

**Comment by vjcitn** [comment]
This is looking great and I am glad you have some unit tests.  Have you had a look at https://shiny.rstudio.com/articles/testing-overview.html and have you tried it?

**Comment by plger** [comment]
Thanks @vjcitn , I hadn't, I now added some server tests (what I could easily with toy data).

**Comment by vjcitn** [comment]
Thanks a lot for trying this out.  I got 
```
Performing 3' alignment...
── Failure (test-shiny.R:11:3): shiny app (server) works ───────────────────────
start(h) (`actual`) not equal to c(281L, 482L) (`expected`).

  `actual`:   1   1
`expected`: 281 482
Backtrace:
  1. shiny::testServer(...) test-shiny.R:11:2
 22. testthat::expect_equal(start(h), c(281L, 482L)) test-shiny.R:26:4

```
I think you need GenomicRanges::start ...

**Comment by vjcitn** [comment]
Please look at the warnings.

**Comment by plger** [comment]
Oops, indeed, thanks for spotting it (I hadn't realized that it was skipped in the GA, I fixed that too).

I had asked earlier regarding the warning:

> There's currently one check warning, namely the use of calls like:
> `BSgenome.Hsapiens.UCSC.hg38:::BSgenome.Hsapiens.UCSC.hg38`
> The idea is to make building the annotation easy, but not require a systematic installation of those genome packages, since a user might just need one of them (or none). The error message when it's not installed is pretty clear... but if you have better suggestions about how to proceed with this kind of issue, we're all ears!
> Thanks in advance, PL

I know `Suggests` is supposed to be for that, but in practice R tries to install those packages as well, so I haven't found a better solution to this general problem.
`scDblFinder` has the same warning because the `mbkmeans` dependency was not necessary (just speed-up) and creating installation troubles on some systems. There I wanted to use it if it's available, and use `kmeans` otherwise.
How would one proceed to avoid warnings as well as having these in the imports?
(Checking now in case something like `requireNamespace` would pass the checks...)

**Comment by vjcitn** [comment]
You don't need :::.  :: is sufficient.  Maybe that is not the concern you are asking about.
You can put the Bsgenome.* packages in Suggests.  Then a pattern like
```
if (!requireNamespace("BSgenome.Hsapiens.UCSC.hg19"))
  stop("Install BSgenome.Hsapiens.UCSC.hg19 with BiocManager to use this function.")
```
can be used when the usage requires it; if the package is installed then :: will get what user needs.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/plger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scanMiRApp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scanMiRApp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
