### ISSUE TITLE
Add HiC-DOC to BioCConductor

### ISSUE THREAD

**Issue by mzytnicki** [Bioconductor/Contributions#2212]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mzytnicki/HiCDOC

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Hi @mzytnicki  ,

Please address the errors and warnings reported by the SPB (Single Package Builder). Thanks!

Best,
H.

**Comment by mzytnicki** [comment]
Thank you very much @hpages ,

If I am not wrong, I did push a patch correcting the warnings to https://github.com/mzytnicki/HiCDOC.git and git@git.bioconductor.org:packages/HiCDOC.git shortly after the report of the SPB issued 4 days ago.
Is there anything I did wrong?  Sorry for delay.

Thank you very much,

Matthias.

**Comment by hpages** [comment]
Did you bump the version of the package? New builds are triggered only when the version is bumped e.g. from 0.99.0 to 0.99.1. Thanks!

**Comment by mzytnicki** [comment]
D'oh!

**Comment by hpages** [comment]
Hi @mzytnicki,

Thanks for submitting **HiCDOC**.

I see 2 problems with the vignette:

1. It should display the name of the author(s).
2. The "1.3.2 Normalizing biases" subsection contains hundreds of "Warning in simpleLoess ..." lines. This is in the rendered version of the vignette, after the code chunks have been evaluated.

A more general concern with the growing number of Hi-C packages in Bioconductor:

There is a strong focus towards interoperability via "standard containers" in Bioconductor.

However it looks like almost each of the several Bioconductor packages dedicated to Hi-C data manipulation implements its own S4 class for handling this type of data. For example the **HiTC** package with the `HTCexp` and `HTClist` classes, the **multiHiCcompare** package with the `Hicexp` class, the **HiCBricks** package with the `BrickContainer` class, etc... and now the **HiCDOC** package with the `HiCDOCDataSet` class.

I don't know the specifics of each class and it could be that they address completely different use cases and that their functionalities don't overlap. But it could also be that they share a lot in common. This would be unfortunate because it hurts interoperability and it would also mean that each package is reinventing the wheel. So hopefully at some point we see an effort to implement a container for Hi-C data that can be reused across various packages, like this was done years ago for the `SummarizedExperiment` container and other "standardized containers".

Thanks,
H.

**Comment by mzytnicki** [comment]
Dear @hpages,

First, let me thank you for you thorough review.

It is true that we did not pay attention to the available classes, and it is also true that it is unfortunate that there are so many similar classes.
That said, I do not know whether there is a "basic" container, such as `SummarizedExperiment` for Hi-C (maybe `HiCBricks`?), which could be used by all the Hi-C packages.
Having so many classes is maybe not the key issue.  `DESeq2` has its `DESeqDataSet`, and `edgeR` its `DGEList`.  This is probably OK, since their analyses are somewhat different.  But both use `SummarizedExperiment` internally (well, I guess).

We will try to correct the package ASAP, and warn you when the modifications have been implemented.

Cheers,

Matthias.

**Comment by mzytnicki** [comment]
Dear @hpages,

Looking at the available packages, we found no classes that would suit clearly our needs.
 - The `HiTexp` stores the data into a `Matrix`, which, in our study, is not appropriate because our data is sparse, and a matrix could not store all the data.
 - `HiCBricks` stores the data into HDF5 files.  It could be a good idea, but we still do not feel it is a standard procedure.
 - `Hicexp` stores the data into a `data.table`.  This is a probably a good idea, but we tried to avoid it, as we already used the `tidyverse`.
This probably calls for a uniform, optimized, data structure for 2D genomic data, just like `SummarizedExperiment` is the reference data structure for 1D data.  However, we are not confident enough (mostly because it would require a significant work) to implement one.
However, if you have one in mind, we will try to use it.
This said, we understand and share your concern about the need for interoperability. What we can do is to propose a parser for our class to import data from standard R format (`data.frame`). This way, anyone could easily transfer data from another HiC class to HICDOC. Of course we are aware that it is not a perfect solution, but we believe that it would be a nice improvement towards interoperability between existing and future Hi-C packages, as long as they also provide a way to export data to standard R objects - which is already the case for HiCDOC.

I hope it helps.

Best regards,

Matthias.

**Comment by hpages** [comment]
Thanks Matthias for taking the time to look at the existing classes and to evaluate other options. It sounds like there's no clear consensus yet on what a "greatest common denominator" data container for Hi-C analyses should be. I just wanted to point this out, with the hope that at some point in the near future we'll see an effort to address this.

Your proposal of a parser sounds good. Another way to improve interoperability is to provide coercion methods back and forth between `HiCDOCDataSet` and similar classes defined in other Hi-C related packages. Of course it only makes sense to do this if the other class has enough similarities with `HiCDOCDataSet` w.r.t. what they can contain/represent.

During an off-line discussion, Vince Carey (@vjcitn) suggested that we invite Mikhail Dozmorov (@mdozmorov) to this discussion. @mdozmorov Do you have something to say about this Mikhail? Any plans for a reusable Hi-C data class in the near future? You're welcome to take a look at this new submission (**HiCDOC**) and comment. Your feedback is greatly appreciated. Thanks!

Cheers,
H.

**Comment by mzytnicki** [comment]
Well, thank you for reviewing our package!
We will try to make parsers from other classes available.
We are also waiting for @mdozmorov suggestions (and glad that there are still off-line discussions in these troubled times).
Best regards,
Matthias.

**Comment by mdozmorov** [comment]
Briefly mention that I'm looking into it, interesting package! As for the common denominator for Hi-C data storage, or at least a general way to operate on paired interactions, I've been looking into https://bioconductor.org/packages/GenomicInteractions/ and the base class it is using, https://bioconductor.org/packages/InteractionSet/.

**Comment by vjcitn** [comment]
Thanks @mdozmorov !!

**Comment by mzytnicki** [comment]
Thanks a lot @mdozmorov.  We will look at that!

**Comment by hpages** [comment]
@mzytnicki Any update on this? Thanks

**Comment by mzytnicki** [comment]
@hpages  Well, sorry for being quiet.
Actually, this is a major rewrite.  Not only should we change our R code, but our Rcpp code too.
So, we will need quite a bit of time...

**Comment by hpages** [comment]
Thanks for letting me know and for your work on **HiCDOC**.

H.

**Comment by mzytnicki** [comment]
Well, thank you for you patience...  It is a major rewrite, so do not hold your breath.

**Comment by lshep** [comment]
Please request we reopen this issue when you are ready with updates, changes, and to continue with the review process.

**Comment by mzytnicki** [comment]
Dear @lshep and @hpages , we basically rewrote the whole package from scratch, and we now use `GenomicInteractions`.  We still need a `HiCDOCDataSet` class, because we have to store additional data (essentially the compartment classification).
Would it be possible to reopen the issue?
I thank you very much for your patience, and your work.

**Comment by mzytnicki** [comment]
Will do, thanks!

**Comment by hpages** [comment]
Hi @mzytnicki, please let me know when **HiCDOC** is ready for review. Thanks -- H.

**Comment by mzytnicki** [comment]
Dear @hpages,
Well, it is ready!
Many thanks,
Matthias.

**Comment by hpages** [comment]
Thanks @mzytnicki.

We're very busy with our upcoming release (BioC 3.15, scheduled for next Wednesday) and it won't be possible to expedite the review process in time for this release. I'll review this new version of **HiCDOC** in the next couple of weeks and we'll add it to BioC 3.16 upon acceptance.

Thanks for your patience.

Best,
H.

**Comment by mzytnicki** [comment]
Dear @hpages,

Sure!  No problem on my side.  Take it easy.
My priorities are: first, a fine 3.15 BioC; then, if time permits, a BioC with HiCDOC.

Best regards,

Matthias.

**Comment by hpages** [comment]
Hi @mzytnicki ,

Sorry for the long delay. I finally got some time to take a new look at **HiCDOC**. Package looks good, only a few minor issues:

1. Contrary to some popular belief it's not necessarily a good idea to list all your dependencies in the `Imports:` field as this tends to hurt usability of your package. For example, if your package defines a class that extends a class defined in another package, then you should list this other package in `Depends:`. Otherwise, you put your users in a situation where the objects that you present to them don't work out-of-the-box:
    ```
    library(HiCDOC)
    data(exampleHiCDOCDataSet)

    class(exampleHiCDOCDataSet)
    # [1] "HiCDOCDataSet"
    # attr(,"package")
    # [1] "HiCDOC"

    ## Because the HiCDOCDataSet class extends InteractionSet, the InteractionSet accessors are
    ## expected to work on exampleHiCDOCDataSet, but they don't:
    
    is(exampleHiCDOCDataSet, "InteractionSet")
    # [1] TRUE
    
    assay(exampleHiCDOCDataSet)
    # Error in assay(exampleHiCDOCDataSet) : could not find function "assay"
    
    interactions(exampleHiCDOCDataSet)
    # Error in interactions(exampleHiCDOCDataSet) : 
    #   could not find function "interactions"

    ## The user first needs to explicitly attach the InteractionSet package to the search path for
    ## the above to work:
    
    library(InteractionSet)
    
    head(assay(exampleHiCDOCDataSet))
    #      [,1] [,2] [,3] [,4] [,5] [,6] [,7]
    # [1,]  488  896   NA  535  748  876  843
    # [2,]  614 1008   NA  577  785  907  865
    # [3,]  571 1028   NA  575  911  962 1024
    # [4,]  588  987   NA  591  786 1069  844
    # [5,]  551 1064   NA  592  793  938  945
    # [6,]  503  879   NA  470  760  907  870

    interactions(exampleHiCDOCDataSet)
    # StrictGInteractions object with 43480 interactions and 1 metadata column:
    #         seqnames1     ranges1     seqnames2     ranges2 | chromosome
    #             <Rle>   <IRanges>         <Rle>   <IRanges> |      <Rle>
    #     [1]         W       0-136 ---         W       0-136 |          W
    #     [2]         W       0-136 ---         W     137-273 |          W
    #     [3]         W       0-136 ---         W     274-410 |          W
    #     [4]         W       0-136 ---         W     411-547 |          W
    #     [5]         W       0-136 ---         W     548-684 |          W
    #     ...       ...         ... ...       ...         ... .        ...
    # [43476]         Z 26989-27125 ---         Z 27126-27262 |          Z
    # [43477]         Z 26989-27125 ---         Z 27263-27399 |          Z
    # [43478]         Z 27126-27262 ---         Z 27126-27262 |          Z
    # [43479]         Z 27126-27262 ---         Z 27263-27399 |          Z
    # [43480]         Z 27263-27399 ---         Z 27263-27399 |          Z
    # -------
    # regions: 560 ranges and 1 metadata column
    # seqinfo: 4 sequences from an unspecified genome; no seqlengths
    ```

2. Don't use curly braces (`{` and `}`) in the definition of your generic functions. This makes them appear as "non standard generics", which is almost never what you want:
    ```
    compartments
    # nonstandardGenericFunction for "compartments" defined from package "HiCDOC"
    # function (object, passChecks = TRUE) 
    # {
    #     standardGeneric("compartments")
    # }
    # <bytecode: 0x55cc2f23d3a8>
    # <environment: 0x55cc2f244fb8>
    # Methods may be defined for arguments: object, passChecks
    # Use  showMethods(compartments)  for currently available ones.
    ```

3. Your `conditions()` generic function clashes with the `conditions()` generic function defined in **BiocGenerics**. As a consequence, depending on the order in which packages are loaded, one generic will mask the other one:
    ```
    library(HiCDOC)
    data(exampleHiCDOCDataSetProcessed)
    
    conditions(exampleHiCDOCDataSetProcessed)
    # [1] "2" "1" "2" "1" "3" "3" "1"
    
    library(BiocGenerics)
    
    conditions(exampleHiCDOCDataSetProcessed)
    # Error in (function (classes, fdef, mtable)  : 
    #   unable to find an inherited method for function ‘conditions’ for signature ‘"HiCDOCDataSet"’
    ```
   As an ecosystem, Bioconductor packages need to be careful to not mask functionalities from other packages. The **BiocGenerics** package was introduced a few years ago to mitigate this. The recommendation is to either:
    - Re-use the `conditions()` generic defined in **BiocGenerics**, that is,`Depends:` on **BiocGenerics**,  `importFrom(BiocGenerics,conditions)`, and define a `conditions()` method for HiCDOCDataSet objects.
    - Just use a different name for your generic. 

4. Running the `HiCDOC` example produces more than 50 warnings:
    ```
    example(HiCDOC)
    #
    # HiCDOC> data(exampleHiCDOCDataSet)
    #
    # HiCDOC> # Default HiCDOC pipeline
    # HiCDOC> object <- HiCDOC(exampleHiCDOCDataSet)
    # Keeping chromosomes with at least 100 positions.
    # Kept 3 chromosomes: X, Y, Z
    # Removed 1 chromosome: W
    # Keeping replicates filled with at least 30% non-zero interactions.
    # ...
    # There were 50 or more warnings (use warnings() to see the first 50)
    
    warnings()
    # Warning messages:
    # 1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   pseudoinverse used at 1
    # 2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   neighborhood radius 1
    # 3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   reciprocal condition number  0
    # 4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   There are other near singularities as well. 1
    # ...
    # 48: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   There are other near singularities as well. 1
    # 49: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   zero-width neighborhood. make span bigger
    # 50: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
    #   zero-width neighborhood. make span bigger
    ```
    From an end-user point of view, these warnings are cryptic and confusing. It's hard to know if they are expected or not, and what to do about them.

5. The Value section of the man page for HiCDOCDataSet methods (?`HiCDOCDataSet-methods`) says the following:
    ```
    ... a data.table (for ‘interactions’ and ‘positions’) ...
    ```
    but that doesn't seem to be the case for `interactions()`:
    ```
    class(interactions(exampleHiCDOCDataSet))
    # [1] "StrictGInteractions"
    # attr(,"package")
    # [1] "InteractionSet"
    ```
    Also there doesn't seem to be a `positions()` accessor:
    ```
    positions(exampleHiCDOCDataSet)
    # Error in positions(exampleHiCDOCDataSet) : 
    #   could not find function "positions"
    ```

6. About the HiCDOCDataSet man page:
    - Listing the slots of the HiCDOCDataSet class is not that useful. Slots are internal business and the end-user should never try to access them directly. They should always use the accessor functions for that e.g. `compartments()`, `concordances()`, etc... So more importantly than listing the slots and their type, this man page should document the accessors, or, if the accessors are documented in a separate man page, it should direct the user to that (via a See also section).
    - Note the description provided for some slots doesn't seem to be accurate e.g. slots `compartments`, `concordances`, `differences`, etc... are not data.table objects.
 
Please address at your earliest convenience.

Cheers,
H.

**Comment by hpages** [comment]
One more thing. The first range here

    regions(interactions(exampleHiCDOCDataSet))[1:3]
    # GRanges object with 3 ranges and 1 metadata column:
    #       seqnames    ranges strand |     index
    #          <Rle> <IRanges>  <Rle> | <numeric>
    #   [1]        W     0-136      * |         1
    #   [2]        W   137-273      * |         2
    #   [3]        W   274-410      * |         3
    #   -------
    #   seqinfo: 4 sequences from an unspecified genome; no seqlengths

is 0-136 on chromosome W. However, please note that Bioconductor uses the 1-based convention for range representation, which means that the first nucleotide of a chromosome is at position 1, not at position 0. This also means that for example the W:51-80 region covers 30 nucleotides as reported by the width of this range:

    GRanges("W:51-80")
    # GRanges object with 1 range and 0 metadata columns:
    #       seqnames    ranges strand
    #          <Rle> <IRanges>  <Rle>
    #   [1]        W     51-80      *
    #   -------
    #   seqinfo: 1 sequence from an unspecified genome; no seqlengths

    width(GRanges("W:51-80"))
    # [1] 30

More generally speaking, the _width_ of a range (i.e. the number of base positions covered by it) is equal to its end position minus its start position plus one.

All this to say that this W:0-136 range is suspect and suggests that maybe you're using 0-based ranges. This would need to be corrected.

Thanks!

**Comment by mzytnicki** [comment]
Dear @hpages,
Thank you very much for you detailed review.  We will try to implement the changes ASAP.
Best regards.

**Comment by mzytnicki** [comment]
Dear @hpages,
We tried to implement the changes you suggested.
Is it better ?
Thanks a lot.

**Comment by hpages** [comment]
Yep. Everything looks good now. Thanks!

H.

**Comment by mzytnicki** [comment]
Great! Thank you!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mzytnicki.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HiCDOC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HiCDOC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
