### ISSUE TITLE
scATAC.Explorer

### ISSUE THREAD

**Issue by agibsonk** [Bioconductor/Contributions#2214]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shooshtarilab/scATAC.Explorer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

ok

## NAMESPACE

ok 

## vignette

ok 

## NEWS

- empty. 

## R

- There are some NOTE(s) in the build report which are easily addressed. Please resolve. 
- Some issues in the code, like `fetchATAC` , for example 

        expression <- downloadATAC(df, row, 'sparse_matrix_link', bfc)

   the expression could be null based on the `downloadATAC()` code. There is no validity check to see if the return value is NULL or not. This will cause failures, since the dataset will not have any expression counts.  

   Make validity checks that are robust. 

- Please write test cases. This is highly recommended. 

- The error function in the tryCatch statement in the `queryATAC()` function is not very helpful. Please do more than print the error message. There are no graceful failures built into `fetchATAC`.

**Comment by nturaga** [comment]
Hi,

We usually give authors about 21 days to get back to us with replies to the review. I will close this package for inactivity, please open it once you are ready with updates. 

It won't stop the process. 

General comments: Please note the release schedule that is posted here - http://bioconductor.org/developers/release-schedule/.

**Comment by agibsonk** [comment]
My apologies for the inactivity. I have made the requested changes to the package. The tests were very helpful for catching errors I made when making the changes! I can push my changes if the issue is reopened @nturaga .

**Comment by agibsonk** [comment]
To give an update on the changes:

1. I added test cases for the main query function.
2. I changed the error functions in queryATAC() and fetchATAC() to add error handling, and have added error handling in the case that the expression data is returned as NULL.
3. I removed some of the long lines that the biocheck pointed out in the NOTES. The remaining lines that are too long are from the documentation. The same is true of the 'multiples of four lines' note, where it is only an issue in the Rd files. Is it necessary to shorten/change these too?
4. I have added updates to the NEWS file.

**Comment by agibsonk** [comment]
I just noticed a NOTE that I forgot to commit the changes for too. It is removing the usage of paste() in condition signals. I will push those changes.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/agibsonk.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scATAC.Explorer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scATAC.Explorer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
