### ISSUE TITLE
ggspavis

### ISSUE THREAD

**Issue by lmweber** [Bioconductor/Contributions#2220]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lmweber/ggspavis

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Lukas, @lmweber 
Thank you for your submission. Please see the review below. 
Feel free to ask any questions. 
Best regards, 
Marcel

--- 
# ggspavis #2220

## DESCRIPTION

* Looks good.
* Consider adding `ggplot2` to the `Depends` field given the number of imported
functions in the `NAMESPACE`.
* (Minor) Format the `Authors@R` field to wrap the text to less than 80 column
width.

## NAMESPACE

* There are only a handful of exported functions. Looks good.

## vignettes/

* Consider restricting the text to 80 column width. It makes it easier to
review and maintain IMO.
* Nice visuals and examples. The vignette is concise.

## R

* Make sure you are using `match.arg` in `plotDimRed` to ensure that your code
is robust to inputs outside of `c("UMAP", "PCA")`.
* Plotting the example in `plotDimRed` does not use the default palette. It
looks like it depends on `annotate` being present, otherwise the palette input
does not work.
* Consider using `.get_pal` in `plotDimRed` as well.
* Add some checks to inputs (e.g., `molecule` in `plotMolecules`) to ensure
robustness
* Avoid redundancy by using a character input for `in_tissue` and using
`df[[in_tissue]]` within the code. The default argument value can be
`"in_tissue"` or even rename the argument to `tissue_column`.

* Minor: Consider using `identical(palette, "libd_layer_colors")` etc. within
your `if` conditions.
* Minor: Consider using `cbind.data.frame` instead of
`as.data.frame(cbind(...))` in `plotQC`.

## /

* Update section in `README.md` to reflect the use of `BiocManager` for
installation (after acceptance).

## tests

* Consider adding unit tests to make the code more robust.

**Comment by lmweber** [comment]
Thanks Marcel @LiNk-NY ! Will work through these comments and push some updates.

**Comment by lmweber** [comment]
Hi Marcel @LiNk-NY - I have pushed the following updates. Thank you!

---

## DESCRIPTION

> Looks good.

> Consider adding ggplot2 to the Depends field given the number of imported
> functions in the NAMESPACE.

Done

> (Minor) Format the Authors@R field to wrap the text to less than 80 column
> width.

Done

## NAMESPACE

> There are only a handful of exported functions. Looks good.

## vignettes/

> Consider restricting the text to 80 column width. It makes it easier to
> review and maintain IMO.

I prefer to leave this with the longer lines of text, since for me this is easier to maintain. I use RStudio as my IDE, which wraps the text, so I find it easier to rewrite a paragraph if it is all in a single line. I use the 80 character column width in my code blocks.

> Nice visuals and examples. The vignette is concise.

## R

> Make sure you are using match.arg in plotDimRed to ensure that your code
> is robust to inputs outside of c("UMAP", "PCA").

Done (in `plotDimRed` and other functions)

> Plotting the example in plotDimRed does not use the default palette. It
> looks like it depends on annotate being present, otherwise the palette input
> does not work.

Done. I replaced the example with some longer code that generates a real plot.

> Consider using .get_pal in plotDimRed as well.

Done (in `plotDimRed` and other functions)

> Add some checks to inputs (e.g., molecule in plotMolecules) to ensure
> robustness

Done (in `plotMolecules` and other functions)

> Avoid redundancy by using a character input for in_tissue and using
> df[[in_tissue]] within the code. The default argument value can be
> "in_tissue" or even rename the argument to tissue_column.

Done

> Minor: Consider using identical(palette, "libd_layer_colors") etc. within
> your if conditions.

Now using `.get_pal()` instead, so I have removed these `if` statements.

> Minor: Consider using cbind.data.frame instead of
> as.data.frame(cbind(...)) in plotQC.

Done (in `plotQC` and other functions)

## /

> Update section in README.md to reflect the use of BiocManager for
> installation (after acceptance).

Will update after acceptance.

## tests

> Consider adding unit tests to make the code more robust.

Done

**Comment by lmweber** [comment]
I also added `uwot` to `Suggests` in dependencies after noticing this was giving an error in my GitHub Actions build, due to the new example code that depends on `uwot`.

**Comment by LiNk-NY** [comment]
Hi Lukas, @lmweber 

Thank you for making those changes. They look great!
Thank you for your contribution to Bioconductor. 

Best regards,
Marcel

**Comment by lmweber** [comment]
Great, thanks Marcel @LiNk-NY !

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lmweber.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggspavis")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggspavis

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
