### ISSUE TITLE
orthogene

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/Contributions#2225]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/neurogenomics/orthogene

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Thank you for the submission. Please find initial review below: 

**Build Report**

- [ ] Remove system files from being git tracked.

- [ ] Please see coding practice Warning about using `is()` rather than `==/!=`

- [ ] Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online. One suggested alternative is to
include linebreaks after function arguments.

- [ ] All NOTES/Warning/ERROR should be fixed or justified. 


**README**

- [ ] Please also include Bioconductor installation instructions in the  eval=FALSE section

**inst**

- [ ] You have tmp_license that includes LICENSE different than what is listed in the DESCRIPTION? Can you clarify why these are here or remove if not necessary?

- [ ] How is the information in these sub-directories used?

- [ ] benchmark and hexsticker feel more approrpiate here as additional documentation and probably should be removed from the vignettes directory. 

**vignette**

- [ ] Please remove intermediate `.R` and `.html` files. These should be generated automatically when the package is built.

- [ ] It seems like hexSticker is not appropriate to include as a vignette for your package but is a helper function for you to make a sticker.  Please remove from the vignette directory. For reference in your package it probably should be in a inst/doc directory.  (For reference - Love! your sticker!)

- [ ] Benchmark vignette is good for reference and efficiency and probably should be moved to the inst/doc rather than vignette.

- [ ] Highly recommend a vignette with the package name so naive users could do `vignette(orthogene)`.

- [ ] There needs to be at least one vignette that describes in detail the usage of your package and show the main package functionality and run functions.  It seems like your README.Rmd should/could actually be the orthogene.Rmd vignette?

- [ ] Please decide on a working vignette and I will continue the review of the vignette and code at that time. 

When ready please do a version bump to trigger a new build and comment back here with updates and comments and request a re-review. 
Cheers

**Comment by bschilder** [comment]
Hi @lshep, thanks so much for the feedback! 

## Build Report

- [x] **Remove system files from being git tracked.**

- [x] **Please see coding practice Warning about using is() rather than ==/!=**

This was from some old code in `inst/tmp_code` and I've since deleted it.

- [x] **Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online. One suggested alternative is to
include linebreaks after function arguments.**

Corrected all of these with a couple exceptions: 
- Long links (is there a way to break these up?)
`R/convert_orthologs.R:128 #' \href{https://cran.r-project.org/web/packages/gprofiler2/vignettes/gprofiler2.html}{...`
- Inherited params, e.g.:
` @inheritParams gprofiler2::gconvert`

- [x] **All NOTES/Warning/ERROR should be fixed or justified.**
 
Tried to get function lengths down as short as I can, but I'm afraid some of them are still over. I'll keep trying to whittle these down in future versions, if that's ok.

## README

- [x] **Please also include Bioconductor installation instructions in the eval=FALSE section
inst**

- [x] **You have tmp_license that includes LICENSE different than what is listed in the DESCRIPTION? Can you clarify why these are here or remove if not necessary?**

I typically use a GNU-GPL3 license by default for all my packages, but when I entered anything other than `License: Artistic-2.0` in my DESCRIPTION, I'd get an error. Is only having a single Artistic license a requirement for Bioc?

Removed `inst/tmp_license/` for now.

- [x] **How is the information in these sub-directories used?**

*benchmark/*: Precomputed benchmarking results for the `benchmarks.Rmd` example.
*hex/*: This is included so the GitHub README can find and show the hext sticker. 
*images/*: File necessary to run `hexSticker.Rmd`.

- [x] **benchmark and hexsticker feel more approrpiate here as additional documentation and probably should be removed from the vignettes directory.**

(please see reply below)

## vignette

- [x] **Please remove intermediate .R and .html files. These should be generated automatically when the package is built.**

- [x] **It seems like hexSticker is not appropriate to include as a vignette for your package but is a helper function for you to make a sticker. Please remove from the vignette directory. For reference in your package it probably should be in a inst/doc directory. (For reference - Love! your sticker!)** 

I tried putting `hexSticker.Rmd` in `inst/doc`, but then whenever I try to run `devtools/build_site()` this `doc` subfolder gets automatically deleted. Also, putting .Rmd/html files in `inst/doc` means that they won't appear in the documentation website (only the raw .Rmd code). 

In the meantime, going to put extra .Rmd within other respective subfolders (`int/benchmark` and `inst/hex`).

And thanks! I spent far too much time on it 😝

- [x] **Benchmark vignette is good for reference and efficiency and probably should be moved to the inst/doc rather than vignette.**

Same issues as with `hexSticker.Rmd`.

- [x] **Highly recommend a vignette with the package name so naive users could do vignette(orthogene).**

 **There needs to be at least one vignette that describes in detail the usage of your package and show the main package functionality and run functions. It seems like your README.Rmd should/could actually be the orthogene.Rmd vignette?**

 **Please decide on a working vignette and I will continue the review of the vignette and code at that time.**

This makes a lot of sense, I reduced my README to just the basics and then put the rest in a new `vignettes/orthogene.Rmd` file.

---
Just bumped to v0.99.1!

**Comment by bschilder** [comment]
Hi @lshep, just wanted to check in and see if there's anything else you need me to do atm.

**Comment by lshep** [comment]
Please allow 2-3 weeks for reviewer feedback.  I am working on your review now and should have comments within the next day.

**Comment by lshep** [comment]
Please see additional comments:

**License:**
You should be able to use any of the [R Licenses](https://www.r-project.org/Licenses/).  If it gave you an ERROR this is probably a bug in our code that should be corrected.


**Rcode**

- [ ] Packages like grr, DelayedArray, and similar should be in Imports not
  in Suggest. They should be declared appropriately in the DESCRIPTION and
  NAMESPACE with Imports or ImportsFrom. Generally functions that are used from
  packages by `::` should be declared. If you really feel like they should only
  be in Suggest the functions that utilize `::` from a package should do a
  require to make sure the package is installed. 

- [ ] Data should not be pulled from github. Tricking the system to still
  accomplish this is not correct.  In your function
  get_orgdb_genomeinfodbdata, you should download the data through the package
  like in the comment out code you have (except use require instead of library)

```
require(GenomeInfoDbData)
data(specData)
```

Please address the above issues. 
Cheers,

**Comment by bschilder** [comment]
When I try the above suggestion, the following Note is produced upon running R cmd check, which is why I switched to the other solution:

## GenomeInfoDbData

### Problem

```
 'library' or 'require' call to ‘GenomeInfoDbData’ in package code.
     Please use :: or requireNamespace() instead.
     See section 'Suggested packages' in the 'Writing R Extensions' manual.
```



Trying this new suggestion instead seems to resolve the problem with R CMD check:

```
 requireNamespace("GenomeInfoDbData")
 utils::data("specData")
```

...However, a new Warning is now produced when running  `BiocCheck::BiocCheck()` despite the fact that `requireNamespace` was used. 

```
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import GenomeInfoDbData in NAMESPACE as well as DESCRIPTION.
```


Adding `@import GenomeInfoDbData` to the function seems to resolve this Warning. This technically works, but requiring `GenomeInfoDbData` is not ideal since this function (and package) will be rarely used and intended only as a backup when the reference organism is not available in the default database. Thus, including `GenomeInfoDbData` as an Import will lengthen installation time unncessarily, and thus seems better as a Suggest. What do you think?




## License

### Problem 

When I include the non-artistic license  using `usethis::use_gpl3_license()` and then adding the following to the DESCRIPTION:
```
License: GPL (>= 3) + file LICENSE.md
```

... the following Warning is produced:

```
 checking DESCRIPTION meta-information ... WARNING
  Non-standard license specification:
    GPL (>= 3) + file LICENSE.md
  Standardizable: FALSE
```

Removing the `+ file LICENSE.md` seems to get rid of this Warning in the R CMD check:

```
License: GPL (>= 3)
```

However, upon running `BiocCheck::BiocCheck()` the following Note is produced. Is this something I need to address?

```
  * NOTE: License 'GPL (>= 3)' unknown; licenses cannot restrict use
```

**Comment by vjcitn** [comment]
If you don't want to import GenomeInfoDbData, use a pattern like
```
if (!requireNamespace("GenomeInfoDbData")) stop("install GenomeInfoDbData to use this function")
```
you can then use `GenomeInfoDbData::` qualifications and put that package into Suggests.

For the LICENSE/usethis issue, perhaps usethis is not compliant with https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing ... just follow the doc.

**Comment by bschilder** [comment]
Thanks for the suggestions, @vjcitn!

- Since `GenomeInfoDbData` doesn't use `LazyData`, it appears that datasets cannot be accessed via `::`. For example, `GenomeInfoDbData::specData` doesn't work, as far as I can tell.
- Changing `License: GPL (>= 3)` to `License: GPL-3` seemed to fix the license Note from`BioCheck`. Thanks!

@lshep I just pushed the license name change, so that should be the last thing (that I can think of).

**Comment by lshep** [comment]
Please remove the commented out code referencing pulling from github from the R files. Non-used code should not be included in R files.  Once this is completed I will accept the package.

**Comment by bschilder** [comment]
> Please remove the commented out code referencing pulling from github from the R files. Non-used code should not be included in R files. Once this is completed I will accept the package.

@lshep this is now done

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bschilder.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("orthogene")`. The package 'landing page' will be created at

https://bioconductor.org/packages/orthogene

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
