### ISSUE TITLE
surfaltr

### ISSUE THREAD

**Issue by PGangras** [Bioconductor/Contributions#2256]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EliLillyCo/surfaltr

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by PGangras** [comment]
@vjcitn Hello, I checked the build report, the error is only with the MacOS system and its relates to a dependency, Biostrings package, not being available. I am not sure what the next steps here should be, please advise. Thanks, Pooja
![image](https://user-images.githubusercontent.com/86016116/130828988-477ad3a3-9e92-4a50-967a-6d981627cd0b.png)

**Comment by vjcitn** [comment]
The review is proceeding.

**Comment by PGangras** [comment]
@vjcitn 
Hello, Hope you are doing well! Sorry to bother you but I was wondering if there is any update regarding the review since tomorrow it will be 5 weeks since I submitted the package and the deadline for the BioC release is fast approaching. 
Thank you for your time, 
Pooja.

**Comment by vjcitn** [comment]
It isn't easy for me to review.  You are using msa, which is throwing
```
* checking compiled code ... NOTE
Note: information on .o files is not available
File ‘/home/biocbuild/bbs-3.13-bioc/R/library/msa/libs/msa.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
  Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
  Found ‘__printf_chk’, possibly from ‘printf’ (C)
  Found ‘abort’, possibly from ‘abort’ (C)
  Found ‘exit’, possibly from ‘exit’ (C)
  Found ‘putchar’, possibly from ‘putchar’ (C)
  Found ‘puts’, possibly from ‘printf’ (C), ‘puts’ (C)
  Found ‘rand’, possibly from ‘rand’ (C)
  Found ‘srand’, possibly from ‘srand’ (C)
  Found ‘stderr’, possibly from ‘stderr’ (C)
  Found ‘stdout’, possibly from ‘stdout’ (C)

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.
```
Do you really need this package imported?  I will work on surfaltr in time for release.

**Comment by vjcitn** [comment]
I know that is only a note.  But it is troubling.  And I can't install msa on M1 mac.

**Comment by PGangras** [comment]
Thank you for your prompt response. I am sorry to hear that surfaltR has not been easy to review. Is it due to the msa installation issue? I have been able to install it on Linux and Windows machines but do not have access to a mac to test installation. I also came across this stack exchange post which describes this NOTE being an issue for several packages (https://stackoverflow.com/questions/64402688/information-on-o-files-for-x64-is-not-available-note-on-r-package-checks-using). I am not sure how to resolve this, do you have any suggestions?

surfaltR needs to import msa since 2 of its functions depend on msa. msa is not required for the major capability of surfaltR which is TM prediction and graphical output of the topology. It is only required for the additional/bonus functionality of aligning protein sequences of interest which is done using 2 standalone functions for within organism and across organism alignment.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PGangras.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("surfaltr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/surfaltr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
