### ISSUE TITLE
transformGamPoi

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/Contributions#2262]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/const-ae/transformGamPoi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by const-ae** [comment]
Hi, 

`BiocCheck` currently detects 1 Warning and 6 Notes:

# Warning

The warning concerns the `biocViews` term 'VarianceStabilization'. I am aware that this is not in the list of [biocTerms](http://bioconductor.org/packages/devel/BiocViews.html); however, I would like to suggest adding it. There are already three Bioconductor packages dedicated to this topic: [vsn](https://www.bioconductor.org/packages/vsn/), [lumi](https://www.bioconductor.org/packages/lumi/), and [flowVS](https://www.bioconductor.org/packages/flowVS/). If however, that is not possible I can of course also remove that term again.

# Notes

> [2] " Avoid redundant 'stop' and 'warn*' in signal conditions"                                                                                                                        

I assume this refers to [rethrowing](https://github.com/const-ae/transformGamPoi/blob/master/R/helpers.R#L137) an error inside a `tryCatch()`. I don't quite understand why this is problematic. I call a function from a separate package that sometimes fails. I want to give the user additional information about what happened and what the alternatives are without automatically picking an alternative for the user. Is there a better way to achieve this?

**Comment by lshep** [comment]
@const-ae  VarianceStabilization is not a valid biocViews term. Please remove from the list of biocViews in the description

**Comment by const-ae** [comment]
> VarianceStabilization is not a valid biocViews term. Please remove from the list of biocViews in the description

@lshep, okay. Done.

**Comment by hpages** [comment]
Hi @const-ae , @wolfganghuber, @lshep ,

Should we add `VarianceStabilization` to the **biocViews** vocabulary? I see that we have a few other Bioconductor packages that provide tools for variance stabilization (**vsn**, **lumi**, **flowVS**, **pmp**, **blima**, etc...). Would be nice to be able to group them under a common view.

The name of the package (**transformGamPoi**) is made of a verb + an object. About the verb: so the package provides tools to _transform_ Gamma Poisson Data. Note that there are many ways to transform data but the package specifically provides _variance stabilizing_ transformations. Why not use a more specific name like **GamPoiVS**? About the object: I can see that using "GamPoi" to describe the type of data that the package is dealing with avoids implying that the package only applies to single cell data, but it also makes the name slightly more cryptic than necessary.

Anyways, these are minor concerns and none of this matters if the package can easily be found under the  `VarianceStabilization` and `SingleCell` views. So this is maybe one more reason to support the `VarianceStabilization` term?

Thanks,
H.

**Comment by wolfganghuber** [comment]
Hi Hervé

Thank you. 

A VarianceStabilization term seems to fine-grained to me, I’d probably prefer Preprocessing.

But who uses search by Keywords…? This sounds like Yahoo.com in 1998… At least in my experience, “everyone” is used to full text search (e.g. Google, Amazon, Netflix), and/or recommender systems that would suggest similar packages. So I’d rather make sure that many of the relevant keywords are in the package description and perhaps also in man pages and vignettes, and that these are text-mined and indexed for a clustering and search engine. 

Agree with you that mnemonic, easily rememberable, descriptive package names are desirable and that the one in question is not really there yet.

Kind regards
Wolfgang

**Comment by const-ae** [comment]
Hi sorry for the silence.

> The name of the package (transformGamPoi) is made of a verb + an object. About the verb: so the package provides tools to transform Gamma Poisson Data. Note that there are many ways to transform data but the package specifically provides variance stabilizing transformations. Why not use a more specific name like GamPoiVS? About the object: I can see that using "GamPoi" to describe the type of data that the package is dealing with avoids implying that the package only applies to single cell data, but it also makes the name slightly more cryptic than necessary.

Yeah, tbh I am not super happy with the name either. My thought process for choosing _transformGamPoi_ is that the verb relates to [_sctransform_](https://CRAN.R-project.org/package=sctransform) which is closely related to my package. The noun _GamPoi_ is indeed partially motivated to not just limited the application to single-cell data. However, the bigger motivation is to stay consistent with my other package _glmGamPoi_ as they follow a similar philosophy.

> A VarianceStabilization term seems to fine-grained to me, I’d probably prefer Preprocessing.

I [added](https://github.com/const-ae/transformGamPoi/commit/30770dded8d4a126db0aed22ad7981ef005e8119) _Preprocessing_ as a term

**Comment by hpages** [comment]
Thanks guys for explaining.

I realize now that the `Preprocessing` and `Normalization` views (which are both under the [`WorkflowStep`](https://bioconductor.org/packages/release/BiocViews.html#___WorkflowStep) view) are leaf views. This suggests that adding `VarianceStabilization` as a subview of `Preprocessing` would take us to a level of refinement that we are not used too, so maybe not this time.

Otherwise the package looks good, thanks!

Cheers,
H.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/const-ae.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("transformGamPoi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/transformGamPoi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
