### ISSUE TITLE
tripr

### ISSUE THREAD

**Issue by iofeidis** [Bioconductor/Contributions#2267]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BiodataAnalysisGroup/tripr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by iofeidis** [comment]
Hello @lshep,

Last build push (0.99.2) was made for eliminating the `seq_len()` **NOTE** of `BiocCheck()`.

**Comment by lshep** [comment]
Thank you for your submission. Please find your initial review below: 

**Documentation**

- [x] Excellent

**CITATION.cff**

- [ ] Is this file necessary? 

**LICENSE/LICENSE.md**

- [ ] Are both of these files necessary? 

**README.md/README.Rmd**

- [ ] Are both of these files necessary? Is there a concern for one getting out
  of date of the other? 

**vignettes**

- [ ] When I run the `tripr::run_app()` I get the following Warnings, is there
  concern?
```
> tripr::run_app()

Listening on http://127.0.0.1:7110
Warning: Error in $: $ operator is invalid for atomic vectors
  [No stack trace available]
Warning: Error in $: $ operator is invalid for atomic vectors
  103: <Anonymous>
```

- [ ] When running the shiny app is there a way to change the output directory?

- [ ] It would be nice if you can change the output directory, to also be able
  to change the "previous session" to allow for selection of a past section? is
  this possible or does it always do the last session only?


- [ ] When running via command line in the vignette, Please change the output
  directory to use a `tempdir()`. `output_path <- file.path(tempdir(),
  "myoutput")`


**R**

- [ ] In your `zzz.R` it seems like you make an output folder in the
  installation folder for tripr. This should be avoided and should use a
  tempdir() by default.  Not all users will have access to the installation
  folder especially if R or the packages were installed as root.

- [ ] run_TRIP seems like it could benefit from some argument checking to make
  sure the user enters valid arguments especially when the arguments have
  limited options.

- [ ] run_TRIP is also a very long function. In the future it might benefit to
  break sections into helper functions for earier reading and understanding of
  code.

- [ ] Please remove commented out code in R files. Notes and comments are
  encouraged but unused code and debugging code should be removed.

- [ ] In helpers.R please use message instead of cat so users can optionaly
  suprress.

- [ ] Large sectios of repeated code should be avoided. It seems a lot of the
  helper functions are closely relate and share large amounts of code
  (examples but should be applied throughout the code:  imgtfilterLow/imgtfilter
  and imgtcleaning/imgtcleaningLow.  These should be one function with an
  argument to control the differences between the functions. On quick glance I'm
  not finding many differences in the code base. Not only does this shorten and
  simplify the code, if a bug or correction should be made then its in one
  location instead of many.

- [ ] Similarly there are large amounts of repeated code in app_server.R and
  run_TRIP_without_ui.R. The sections of code that are repeated ideally would be
  in an internal function that both of these files call. Simplifing the code.

- [ ] In global. similarly to zzz.R, It should not be assumed the user has
  access to write to the installation directory and it is somewhat bad practice
  to write to that directory. We highly recommend using a tempdir as default and
  allow the user to change to a directory of their choice.


Please address the above issues.  When ready please bump the version to trigger a new build report and comment back here commenting on how the above have been addressed or any additional comments and requesting a re-review.  Cheers

**Comment by iofeidis** [comment]
Hi @lshep!

Thank you for reviewing our package and making suggestions!
We will look into them and come back with the corresponding changes.

Cheers

**Comment by iofeidis** [comment]
Hi @lshep ,

See below our comments on the review:

> CITATION.cff
> 
> - [ ] Is this file necessary?

Although it's not necessary for the code, we would prefer to have this for the Github repo citation, as recommended by the [best practices](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files). If this poses a serious issue, we could move it to another branch, but it would be less than ideal.


> LICENSE/LICENSE.md
> - [X]  Are both of these files necessary?

Only LICENSE is needed. The other file is now removed.

> README.md/README.Rmd
> 
> - [X]  Are both of these files necessary? Is there a concern for one getting out
>    of date of the other?

The README.Rmd file was used for the initial creation of .md - it has been now removed.

> vignettes
> 
> - [ ]  When I run the tripr::run_app() I get the following Warnings, is there
>     concern?
> 
> 
> 	> tripr::run_app()
> 	
> 	Listening on http://127.0.0.1:7110
> 	Warning: Error in $: $ operator is invalid for atomic vectors
> 	  [No stack trace available]
> 	Warning: Error in $: $ operator is invalid for atomic vectors
> 	  103: <Anonymous>

This warning is due to the $ operator on shiny apps. It has no effect on the main functionality, so it can be safely ignored.

> - [X] When running the shiny app is there a way to change the output directory?

In shiny app, we have now made the default output directory based on `tempdir()`, and we expect the user to access its files through the `Download` button. However, if need be, we can add an explicit choice of selecting the output directory from the UI before pressing the button (although this would not be optimal). In either case, the explicit choice of output folder is already done in the `run_TRIP()` function.

> - [ ] It would be nice if you can change the output directory, to also be able
> to change the "previous session" to allow for selection of a past section? is
> this possible or does it always do the last session only?

So far the tool has been designed to work only with the previous session. However, it's in our future plans to enable support for all past sessions as well.

> - [X]  When running via command line in the vignette, Please change the output
>     directory to use a tempdir(). output_path <- file.path(tempdir(), "myoutput")

Done.

> R
> 
> - [X] In your zzz.R it seems like you make an output folder in the
> installation folder for tripr. This should be avoided and should use a
> tempdir() by default. Not all users will have access to the installation
> folder especially if R or the packages were installed as root.

Done.

> - [X] run_TRIP seems like it could benefit from some argument checking to make
> sure the user enters valid arguments especially when the arguments have
> limited options.

Done.

> - [ ] run_TRIP is also a very long function. In the future it might benefit to
> break sections into helper functions for earier reading and understanding of
> code.

We have already started a discussion about a refactoring of the codebase. However, given the extend of the code, this will require substantial time and therefore it will probably be addressed in future versions of the package.

> - [X] Please remove commented out code in R files. Notes and comments are
> encouraged but unused code and debugging code should be removed.

Done.

> - [X] In helpers.R please use message instead of cat so users can optionaly
> suppress.

`cat()` is used for printing into the `logFile`, not for messages on the console, so it needs to be kept.

> - [ ] Large sectios of repeated code should be avoided. It seems a lot of the
> helper functions are closely relate and share large amounts of code
> (examples but should be applied throughout the code: imgtfilterLow/imgtfilter
> and imgtcleaning/imgtcleaningLow. These should be one function with an
> argument to control the differences between the functions. On quick glance I'm
> not finding many differences in the code base. Not only does this shorten and
> simplify the code, if a bug or correction should be made then its in one
> location instead of many.

As mentioned before, we do intend to restructure our codebase for shortening and simplification, but in order to ensure that no bugs/issues slip through the process, it will be addressed in a future version of the package.

> - [ ] Similarly there are large amounts of repeated code in app_server.R and
> run_TRIP_without_ui.R. The sections of code that are repeated ideally would be
> in an internal function that both of these files call. Simplifing the code.

Same as before.

> - [X]  In global. similarly to zzz.R, It should not be assumed the user has
>     access to write to the installation directory and it is somewhat bad practice
>     to write to that directory. We highly recommend using a tempdir as default and
>    allow the user to change to a directory of their choice.

Done.

The latest push includes the aforementioned changes.
Looking forward to your re-review.

Cheers!

**Comment by lshep** [comment]
We highly recommend the refactoring and simplifying of code; I strongly encourage to implement this as stated in a future update to the package as it will help with bugs and maintainability.

**Comment by iofeidis** [comment]
Thank you @lshep for reviewing our package!

We will work into refactoring the codebase as stated.

Regarding the package itself, how can a user now install `tripr` through `BiocManager`?

**Comment by lshep** [comment]
In a few days the package will be added to the daily manifest and build on the daily builder; once it builds on the daily builder it will be available through BiocManager

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/iofeidis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tripr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tripr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
