### ISSUE TITLE
excluderanges

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/Contributions#2269]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mdozmorov/excluderanges

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mdozmorov** [comment]
Does the "Warnings" label prevent the review? From previous experience, it wasn't a problem, but I want to make sure it's not the reason for the delay.

**Comment by lshep** [comment]
No it should not prevent review @vjcitn

**Comment by vjcitn** [comment]
Can I ask why there are csv files in /man in this package?

**Comment by mdozmorov** [comment]
Some may prefer links to the source files, per @mikelove's suggestion. These tables were originally embedded in Markdown. I can keep csv files only on GitHub, and embed the tables for BioC submission.

**Comment by vjcitn** [comment]
It seems to me that if you want to provide CSV data, you could put it in inst/extdata or inst/csv.  I have a feeling this selection of /man as the location has a somewhat involved history -- but I don't know of any other examples of putting csv data in /man.  I see images in /man and I have a recollection that this is a workaround for getting images into the github README.  I don't think the same practice should be used for small csv data, but I could be persuaded otherwise.

**Comment by mdozmorov** [comment]
The CSV files are now in inst/extdata. It indeed seems the right place for them, according to https://r-pkgs.org/data.html.

**Comment by vjcitn** [comment]
did you push revisions and bump version number to
```
origin	https://git.bioconductor.org/packages/excluderanges (fetch)
origin	https://git.bioconductor.org/packages/excluderanges (push)
```

**Comment by mdozmorov** [comment]
I double-checked - I cannot push to https://git.bioconductor.org/packages/excluderanges. The error is:

fatal: remote error: FATAL: W any packages/excluderanges nobody DENIED by
fallthru
(or you mis-spelled the reponame)

I also tried git@git.bioconductor.org:packages/excluderanges.git, and also
rejected

 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to ***@***.***:
packages/excluderanges.git'

The changes are in the original repository, including version bump https://github.com/mdozmorov/excluderanges

**Comment by mikelove** [comment]
I think this is because GitHub main / Bioc master. Try this:

```
git push upstream main:master
```

this is from the comment in step 5 here: https://bioconductor.org/developers/how-to/git/new-package-workflow/

**Comment by mdozmorov** [comment]
Worked like a charm! Didn't know one can match branch names. Thanks, @mikelove

**Comment by vjcitn** [comment]
Very nice vignette.  But are the download operations in eval=FALSE going to be replaced with Hub operations?  I think we are ready to accept, but BiocCheck complains that too few vignette chunks are evaluated.

**Comment by mdozmorov** [comment]
Yes, after the files will be added to AHub, I'll update the vignette and the readme to use AHub IDs. Download links will be gone.

**Comment by vjcitn** [comment]
Please do make the changes to use hub resources before this is accepted.

**Comment by mdozmorov** [comment]
Sent the e-mail to hubs@bioconductor.org, and will make changes asap.

**Comment by lshep** [comment]
Please check your metadata.csv file and the files you have uploaded.  I had everything added to the hub and since removed as in testing some of the file names are not matching up. For instance the very first entry the RDataPath excluderanges/ce10.Kundaje.ce10-blacklist.rds  does not match any file uploaded,  I assume this is the uploaded excluderanges/ce10.Kundaje.ce10-Excludable.rds  -- I'm not sure how many other of these mistakes there are but please check and either update the metadata.csv file or reupload the entire data set with the correct names to S3 (the same access credentials will be good)

**Comment by mdozmorov** [comment]
I'm sorry for the oversight, strange. I re-generated the data from scratch and ensured the file names match entries in the [metadata table](https://github.com/mdozmorov/excluderanges/blob/main/inst/extdata/metadata.csv). Just uploaded the updated data with all file names matched.

![image](https://user-images.githubusercontent.com/864945/136405482-88afb18b-0ec1-4800-8e83-0458781fe7d8.png)

**Comment by lshep** [comment]
The **RDataPath** field has still not been updated.   As pointed out before this is the problematic field and still is.

**Comment by mdozmorov** [comment]
Should be updated. Lots of renaming has been done, I forgot about the RDataPath field in metadata.

**Comment by lshep** [comment]
The data has been added to the hub 
```
> ah = AnnotationHub()
snapshotDate(): 2021-10-08


> query(ah, "excluderanges")
AnnotationHub with 42 records
# snapshotDate(): 2021-10-08
# $dataprovider: UCSC, ENCODE, mitra.stanford.edu/kundaje/akundaje/release/b...
# $species: Homo sapiens, Mus musculus, Drosophila melanogaster, Caenorhabdi...
# $rdataclass: GRanges
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH95908"]]' 

            title                                                    
  AH95908 | ce10.Kundaje.ce10-Excludable.rds                         
  AH95909 | dm3.Kundaje.dm3-Excludable.rds                           
  AH95910 | hg19.Bernstein.Mint_Excludable_hg19.rds                  
  AH95911 | hg19.Birney.wgEncodeDacMapabilityConsensusExcludable.rds 
  AH95912 | hg19.Crawford.wgEncodeDukeMapabilityRegionsExcludable.rds
  ...       ...                                                      
  AH95945 | mm10.UCSC.telomere.rds                                   
  AH95946 | mm9.UCSC.centromere.rds                                  
  AH95947 | mm9.UCSC.contig.rds                                      
  AH95948 | mm9.UCSC.fragment.rds                                    
  AH95949 | mm10.UCSC.scaffold.rds         

> temp = ah[["AH95908"]]
 GRanges object with 122 ranges and 0 metadata columns:
        seqnames            ranges strand
           <Rle>         <IRanges>  <Rle>
    [1]     chrI     933000-934500      *
    [2]     chrI   2542900-2544000      *
    [3]     chrI   3171400-3172600      *
    [4]     chrI   3664800-3666100      *
    [5]     chrI   3989700-3991000      *
    ...      ...               ...    ...
  [118]     chrX 14388000-14389200      *
  [119]     chrX 14907900-14909700      *
  [120]     chrX 15226900-15228800      *
  [121]     chrX 15807400-15811200      *
  [122]     chrX 16758300-16760000      *
  -------
  seqinfo: 6 sequences from ce10 genome
        
```

Please update the vignettes accordingly 
Cheers

**Comment by vjcitn** [comment]
Vignette should not have:

```
BiocManager::install("mdozmorov/excluderanges")
```

And should revise
```
## Use excluderanges

{r eval = FALSE}
# hg38 excluderanges coordinates
download.file(url = "https://drive.google.com/uc?export=download&id=1Jy_7cvFj5ZHUUwHgGUKZeFk8lFCalpKk", destfile = "hg38.Kundaje.GRCh38_unified_Excludable.rds")
```

etc

**Comment by mdozmorov** [comment]
I realized I didn't push the update to BioC, only to GitHub. This push uses all AHub data, no `download.file` etc., and BioCcheck() returns zero warnings.

**Comment by vjcitn** [comment]
If you can figure out the warning, please fix -- and let me know how you figured it out.  Seems like an immature warning condition in R CMD check.

**Comment by lshep** [comment]
The warning is because there are no man pages whatsoever so there are no files to parse.  We would recommend having at least a package level man page to describe the package and point to any relevant functions so something like `?excluderanges` would work for a user

**Comment by vjcitn** [comment]
I suspected this.  Can BiocCheck introduce a clearer response to this condition?  A package with no man pages at all should be exceptional if allowed at all.  @LiNk-NY ...

**Comment by lshep** [comment]
This came from  `R CMD check` not BiocCheck -- so you would still get he cryptic error unless fixed in base R

**Comment by mdozmorov** [comment]
It may help to check for such cases in `BioCcheck` and explicitly suggest adding [package documentation](https://r-pkgs.org/man.html#man-packages). I couldn't understand the problem from `R CMD check` output. Pushed the documentation, will monitor if it resolves the warning.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mdozmorov.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("excluderanges")`. The package 'landing page' will be created at

https://bioconductor.org/packages/excluderanges

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
