### ISSUE TITLE
scatterHatch

### ISSUE THREAD

**Issue by atuldeshpande** [Bioconductor/Contributions#2272]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FertigLab/scatterHatch

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by atuldeshpande** [comment]
Hi @hpages, we made a couple of minor edits in our `DESCRIPTION` file amounting to the following:
```
-    R (>= 4.0)
-    biocViews: Visualization, SingleCell, CellBiology, Software

+    R (>= 4.1)
+    biocViews: Visualization, SingleCell, CellBiology, Software, Spatial
```
I was wondering if it would be OK to wait for your review comments to push the next version?

**Comment by hpages** [comment]
Hi @atuldeshpande ,

Feel free to push any improvements during the review.

4 problems with this man page:

![Screenshot from 2021-10-06 15-27-58](https://user-images.githubusercontent.com/8810451/136292382-4a9a6c03-b023-42ae-a860-e2c0e5488d29.png)

1. The data frame has only 3 variables:
    ```
    > head(pdacData)
      frame       Xt       Yt
    1     1 1342.878  801.154
    2     4 5688.494 1391.393
    3     4 6295.826 1393.807
    4     4 5344.257 1391.650
    5     4 5640.034 1391.416
    6     4 5923.357 1390.776
    ```

2.  These variables need to be explained.

3. The colon at the end of
    
    > A data frame with 158159 rows and 41 variables:
    
    is followed by... nothing!

4. The `Source:` section is too minimalist and the parentheses around it are not needed.

Thanks,
H.

**Comment by hpages** [comment]
Thanks for fixing `pdacData`'s man page.

One more thing: please always use `<-` instead of `=` for assignment. With a space before and after the left arrow e.g.:
```
pdacData$cellID <- paste0('cell_', 1:nrow(pdacData))
```
Thanks,
H.

**Comment by atuldeshpande** [comment]
Thank you so much for the feedback @hpages! Let me know if anything else is needed.

**Comment by hpages** [comment]
Thanks. All is good now.

Cheers,
H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/atuldeshpande.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scatterHatch")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scatterHatch

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
