### ISSUE TITLE
monaLisa: MOtif aNAlysis with Lisa

### ISSUE THREAD

**Issue by mbstadler** [Bioconductor/Contributions#2276]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fmicompbio/monaLisa

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment]
Hi @mbstadler 

Thanks for submitting **monaLisa** :tada:! I think this is a really high-quality package with great documentation and some extensive testing. There are a few things I have found but they should be fairly minor and quick to address.

Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional

## General package development

- [ ] :warning: The package built fine on the Bioconductor system but I got this error when I tried locally.
      It could be a random number thing but maybe worth checking out in case it comes up again.

```r
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  >
  > test_check("monaLisa")
  ══ Skipped tests ═══════════════════════════════════════════════════════════════
  • empty test (1)

  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test_kmers.R:222:5): calcBinnedKmerEnr works as expected ───────────
  colSums(assay(res2, "negLog10P")) not equal to c(`[1,1.5]` = 24.5599369371223, `(1.5,2]` = 41.9051486968493).
  2/2 mismatches (average diff: 7.9)
  [1] 39.5 - 24.6 == 14.916
  [2] 42.8 - 41.9 ==  0.885

  [ FAIL 1 | WARN 5 | SKIP 1 | PASS 532 ]
  Error: Test failures
  Execution halted
```
- [ ] :warning: There is a build note about long lines. Please check if it's possible to reduce any of those.
- [ ] :warning: `BiocCheck::BiocCheck()` also warns about examples for a couple of functions.
      Please check if you can add those (I think there is a good reason not to for at least one of them).

## DESCRIPTION files

- [ ] :green_circle: It is recommended to add a `BugReports` field. Usually this links to your GitHub issues or the Bioconductor support site.
- [ ] :green_circle: It is recommended to add a `URL` field. Usually this links to your GitHub repository or Bioconductor package page (you can add multiple URLs separated by commas).

## NAMESPACE file

- [ ] :rotating_light: The whole **{GenomicRanges}** package is imported using `import()` rather than specific functions using `importFrom()`. Please avoid this if you can.

## The NEWS file

- [ ] :warning: Check that the versions in `NEWS.md` match the package versions.

## Documentation

### Vignette

- [ ] :rotating_light: Please add a table of contents to the vignettes
- [ ] :rotating_light: The `quick` chunk in the main vignette is not evaluated. This should (preferably) be evaluated or if it can't please clearly note in the text that it isn't run.
- [ ] :rotating_light: Please add an *Installation* section to the main vignette. This should include the Bioconductor installation instructions and should NOT be evaluated.
- [ ] :rotating_light: One of the chunks in the regression vignette uses `BiocParallel::MulticoreParam()`, please use `BiocParallel::SerialParam()` instead to avoid using multiple cores on users/build systems.
- [ ] :green_circle: There is a blank line with a single slash on L142 of the regression vignette (I think this is a typo but maybe not).

### Man pages

- [ ] :green_circle: The common imports in `motif_finding.R` could be moved to the package documentation `monaLisa-package.R` file as a more standard place to put them

## Code

### R

- [ ] :warning: There are a few things in `anno_seqlogo()` which are accessed directly using `@`. Please avoid this by using a getter function if you can.
- [ ] :warning: I noticed one instance of `<-` instead of `=` in `seqlogo.R` L251. Please check if there are others.
- [ ] :rotating_light: I think most of the `for` loops are appropriate but there are some like in `pfm2ic()` where `apply` functions could be used instead.
      Please check if any can be replaced.
- [ ] :rotating_light: Some of the functionality requires the **HOMER** scripts. If possible it would be good to have these included as a system dependency (I'm not sure of the details how to do that so might need to consult the bioc devel mailing list).
      If not please document where to install **HOMER** from (I didn't see anything but I might have missed it)
- [ ] :rotating_light: There are some dead commented code block in some functions (`.compareMotifPair()`, `.compareMotifKmer()`, `.calcExpFg()`, maybe others, please check).
      Please delete these.
- [ ] :green_circle: `bin()` is a very generic function name (I'm surprised its not a base function). Maybe worth renaming to something more specific to avoid clashes with other packages (up to you)?
- [ ] :rotating_light: There is an assignment in an if statement in `findHomer()`. Probably just a typo but please fix.
- [ ] :warning: A couple of functions like `plotBinDiagnostics()` don't have a clear return. In this case it's common to return `invisible(TRUE)` (no need for `return(invisible(TRUE))`).
- [ ] :green_circle: In general I found what was returned a bit inconsistent, sometimes `TRUE`, sometimes `invisible(TRUE)`, sometimes `return()`, sometimes a function call.
      Not a big deal but might be worth checking that you have what you want in the right place.

**Comment by mbstadler** [comment]
_Hi @lazappi_

_Thank you for your useful and detailed feedback to our package._
_We have copied your points below and added our responses below each point in italics._

_Michael, Charlotte and Dania_  

**General package development**
⚠️ The package built fine on the Bioconductor system but I got this error when I tried locally.
It could be a random number thing but maybe worth checking out in case it comes up again.
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  >
  > test_check("monaLisa")
  ══ Skipped tests ═══════════════════════════════════════════════════════════════
  • empty test (1)

  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test_kmers.R:222:5): calcBinnedKmerEnr works as expected ───────────
  colSums(assay(res2, "negLog10P")) not equal to c(`[1,1.5]` = 24.5599369371223, `(1.5,2]` = 41.9051486968493).
  2/2 mismatches (average diff: 7.9)
  [1] 39.5 - 24.6 == 14.916
  [2] 42.8 - 41.9 ==  0.885

  [ FAIL 1 | WARN 5 | SKIP 1 | PASS 532 ]
  Error: Test failures
  Execution halted
 
_Yes, this error was indeed caused by the recent changes to BiocParallel. We have updated the tests accordingly._  

⚠️ There is a build note about long lines. Please check if it's possible to reduce any of those.

_We have addressed this as far as we were able._ 

⚠️ BiocCheck::BiocCheck() also warns about examples for a couple of functions.
Please check if you can add those (I think there is a good reason not to for at least one of them).

_We have added examples to all exported functions._ 

**DESCRIPTION files**
🟢 It is recommended to add a BugReports field. Usually this links to your GitHub issues or the Bioconductor support site.

_We have added a BugReports field that links to our GitHub issues._

🟢 It is recommended to add a URL field. Usually this links to your GitHub repository or Bioconductor package page (you can add multiple URLs separated by commas).

_We have added a URL field that links to our GitHub repository, future Bioconductor landing page and pkgdown documentation._

**NAMESPACE file**

🚨 The whole {GenomicRanges} package is imported using import() rather than specific functions using importFrom(). Please avoid this if you can.

_We have removed the full import of {GenomicRanges} and added importFrom statements where needed._

**The NEWS file**

⚠️ Check that the versions in NEWS.md match the package versions.

_We have bumped the version (to 0.99.1) and added corresponding entries in the NEWS.md file._ 

**Documentation**

**Vignette**
🚨 Please add a table of contents to the vignettes

_We have added a table of contents to both vignettes._

🚨 The quick chunk in the main vignette is not evaluated. This should (preferably) be evaluated or if it can't please clearly note in the text that it isn't run.

_We have indicated in the vignette that this example is not run, and added additional comments in the code chunk, that people need to create the needed objects. This chunk is meant as a short “pseudo-code” overview of the analysis, and a more detailed, evaluated example is contained further below in the vignette._



🚨 Please add an Installation section to the main vignette. This should include the Bioconductor installation instructions and should NOT be evaluated.

_We have added an installation section to both the README and the main vignette._ 

🚨 One of the chunks in the regression vignette uses BiocParallel::MulticoreParam(), please use BiocParallel::SerialParam() instead to avoid using multiple cores on users/build systems.

_We have changed all BiocParallel::MulticoreParam() to BiocParallel::SerialParam() in both vignettes, and added additional documentation in the text on how to run in parallel mode using BiocParallel::MulticoreParam()._

🟢 There is a blank line with a single slash on L142 of the regression vignette (I think this is a typo but maybe not).

_We have removed it._


**Man pages**
🟢 The common imports in motif_finding.R could be moved to the package documentation monaLisa-package.R file as a more standard place to put them

_We would prefer to keep them in motif_finding.R, as they are specific to the functions in that file._

**Code**
**R**
⚠️ There are a few things in anno_seqlogo() which are accessed directly using @. Please avoid this by using a getter function if you can.

_We are now setting the fields directly in the constructor and have removed the use of @._

⚠️ I noticed one instance of <- instead of = in seqlogo.R L251. Please check if there are others.

_We fixed this, and went through the code to find any additional instances._

🚨 I think most of the for loops are appropriate but there are some like in pfm2ic() where apply functions could be used instead.
Please check if any can be replaced.

_We replaced the for loop in pfm2ic() by vapply._

🚨 Some of the functionality requires the HOMER scripts. If possible it would be good to have these included as a system dependency (I'm not sure of the details how to do that so might need to consult the bioc devel mailing list).
If not please document where to install HOMER from (I didn't see anything but I might have missed it).

_We have added a link to the Homer installation instructions page, in the monaLisa vignette and the documentation of calcBinnedMotifEnrHomer. We prefer not to have it as a system dependency, since it is not strictly required for the package functionality. We have kept the calcBinnedMotifEnrHomer function for historical reasons, when the Homer tool was used in the binned approach. We also recommend the use of the calcBinnedMotifEnrR function in the vignette, to do the binned analysis, which does not require Homer to be installed._


🚨 There are some dead commented code block in some functions (.compareMotifPair(), .compareMotifKmer(), .calcExpFg(), maybe others, please check).
Please delete these.

_We removed commented code blocks._

🟢 bin() is a very generic function name (I'm surprised its not a base function). Maybe worth renaming to something more specific to avoid clashes with other packages (up to you)?

_This is a valid point - in order to not break users' current code (and since there currently is no clash), we would however prefer to keep the current name of the function._ 

🚨 There is an assignment in an if statement in findHomer(). Probably just a typo but please fix.

_We have separated-out the assignment from the if statement._

⚠️ A couple of functions like plotBinDiagnostics() don't have a clear return. In this case it's common to return invisible(TRUE) (no need for return(invisible(TRUE))).

🟢 In general I found what was returned a bit inconsistent, sometimes TRUE, sometimes invisible(TRUE), sometimes return(), sometimes a function call.
Not a big deal but might be worth checking that you have what you want in the right place.

_We reviewed the return values, especially in the plotting functions that are called for their side effects: They now either return invisible(TRUE) or a plot-specific object that may be useful to further modify or annotate the generated plots._

**Comment by lazappi** [comment]
Thanks @mbstadler. I'm happy with this so will mark the package as approved 🎉! It can take a few days for the build system to pick it up but it should be added to Bioconductor devel soon.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mbstadler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("monaLisa")`. The package 'landing page' will be created at

https://bioconductor.org/packages/monaLisa

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
