### ISSUE TITLE
Cepo

### ISSUE THREAD

**Issue by HaniJieunKim** [Bioconductor/Contributions#2284]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PYangLab/Cepo

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

-  [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HaniJieunKim** [comment]
Hi @hpages. 

Thank you so much for reviewing our package! Please let us know if you require any additional information and I look forward to your suggestions. 

Best wishes, 
Hani

**Comment by hpages** [comment]
Hi @HaniJieunKim ,

Sorry for the delay. This is not how to install a Bioconductor package:
```
install.packages("remotes")
remotes::install_github("PYangLab/Cepo")
```
A Bioconductor package should _always_ be installed with `BiocManager::install()`:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Cepo")
```
Please modify your vignette.

Also, direct slot access (`@`) like here:
```
hallmarkList <- lapply(hallmark@.Data, function(x) x@geneIds)
names(hallmarkList) <- lapply(hallmark@.Data, function(x) x@setName)
```
is forbidden! Here you are looping on a GeneSetCollection object to extract the gene ids of each individual GeneSet object in the collection. First: you can call `lapply()` on `hallmark` for this, no need to call it on `hallmark@.Data`. Second: you should use the `geneIds()` accessor function defined in the **GSEABase** package to extract the gene ids from the individual GeneSet objects. So this gives:
```
hallmarkList <- lapply(hallmark, geneIds)
```
To extract the names, just call `names()` on the GeneSetCollection object:
```
names(hallmarkList) <- names(hallmark)
```
But wait! It seems that the `geneIds()` accessor function can also be called directly on the GeneSetCollection object and it will do exactly what you want. So the 2 lines above can be replaced with just:
```
hallmarkList <- geneIds(hallmark)
```
Please make sure to get rid of any use of `@` in your package.

I strongly suggest that you add the **GSEAbase** package to your `Depends` field. Thanks!

Regards,
H.

**Comment by hpages** [comment]
Hi @HaniJieunKim ,

Thanks for the changes. Note that you are still using direct slot access in your code where you should absolutely not be doing this e.g. in the `Cepo()` function (file `R/Cepo.R`, lines 108-113):
```
        types = unique(unlist(lapply(batch_result, function(x) {
            names(x$stats@listData)
        })))
        idx = Reduce(intersect, lapply(batch_result, function(x) {
            x$stats@rownames
        }))
```
Then again later in the same file (lines 115-120):
```
        averageCepo <- lapply(types, function(celltype) {
            mat <- do.call(cbind, lapply(batch_result, function(x) {
                x$stats@listData[[celltype]][idx]
            }))
            return(rowMeans(mat))
        })
```
Then again later in the same file (lines 131-136):
```
            averageCepoPvals <- lapply(types, function(celltype) {
                mat <- do.call(cbind, lapply(batch_result, function(x) {
                    x$pvalues@listData[[celltype]][idx]
                }))
                return(mat)
            })
```
In all these cases, you are using direct slot access to access various components of a DataFrame object e.g. you're doing `names(x$stats@listData)` to get the `colnames()` of DataFrame object `x$stats`, then `x$stats@rownames` to get its `rownames()`, then `x$stats@listData[[celltype]][idx]` to extract the value from row `idx` and column `celltype`. There is absolutely no need to use such obfuscated code to do things that can be accomplished using the "standard data.frame API" (which DataFrame objects support).

One more thing: I found several places where you use `=` instead of `<-` for assignment in your code. Please always use `<-` for assignment (with one space before and one space after the left arrow).

After these simple changes, the package will be ready for acceptance.

Thanks,
H.

**Comment by HaniJieunKim** [comment]
Hi @hpages!

Thank you very much for your time and comments! I have incorporated your suggestions.

Best regards,

Hani

**Comment by hpages** [comment]
Perfect, thanks!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HaniJieunKim.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Cepo")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Cepo

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
