### ISSUE TITLE
biodbKegg (biodb extension package)

### ISSUE THREAD

**Issue by pkrog** [Bioconductor/Contributions#2288]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pkrog/biodbKegg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nturaga** [comment]
Hi @pkrog 

Please issue another build, I'd like to see your package build on all three platforms.

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

ok

## NAMESPACE 

ok

## Vignettes 

- Good documentation

## R

- The r6 class system seems to be used here for providing access to a database. Is this design needed?
- Is there any code that is reused in the packages you submitted recently? You seem to have submitted multiple packages on the same day. Since different reviewers are assigned it's hard to judge all of them.


## General

- Can you tell me how this is different from KEGGREST, a package already in Bioconductor? Or what additional functionality it provides?

**Comment by pkrog** [comment]
Thanks for your review.

All the biodb* packages submitted these days are all extensions of the biodb package that was submitted in the previous release. So, yes, there is common code between those packages, and it is inside the main biodb package.

I've chosen R6 in order to make sure only one instance of a connector type exists, and control this way the access to the associated remote database. I used R6 sometimes in the packages for consistency, more than for any other reason, but this is needed for the connector classes and the entry classes.

Good question about KEGGREST. One of the goal of biodb is to handle itself a cache of downloaded entries and request results. I did not see how to that with KEGGREST at the time I wrote this package. Maybe I missed something. Anyway I've already planned to look at KEGGREST again as soon as I have time.

**Comment by vjcitn** [comment]
I have taken over the review of the biodb* packages to help reduce repetitive effort.  I have already raised some general questions in the biodbUniprot review, related to providing helper 'wrapper' functions.  This should be considered in this case too.  Here is an example that might be more general:
```
bdb_helper = function(resource = "kegg.compound", inputs = c('C00133', 'C00751'), method1 = "getEntry",
     method2 = "entriesToDataframe", ...) {
  mybiodb <- biodb::newInst()                         # setup
  con = try(mybiodb$getFactory()$createConn(resource))    # get connection
  if (inherits(con, "try-error")) stop(sprintf("could not connect with resource %s", resource))
  on.exit(mybiodb$terminate())                        # tear down when done
  ents = try( con[[method1]](inputs))
  if (inherits(ents, "try-error")) stop(sprintf("could not apply method %s on supplied inputs", method))
  mybiodb[[method2]](ents)
}
```
It works fine as `bdb_helper()`.  But we don't explain what the inputs could be, or validate them, and if we try
```
bdb_helper(resource = "uniprot", inputs = "P51587")
```
it doesn't work.  But why?  getEntry and entriesToDataframe seem pretty generic ...

**Comment by vjcitn** [comment]
I am not so clear on why you have two vignettes.  The 'databases' vignette material follows naturally from the intro material.  In the databases vignette, you don't give any indication what a compound id is, and the intro vignette has a good example linking compound ids to compound names.

The printing events near end of databases vignette (Linking to ImageMagick, and the tibble) seem extraneous.
```
img <- kegg.path.conn$getDecoratedGraphPicture(pathways[[1]],
                                               color2ids=color2ids)
## Linking to ImageMagick 6.9.12.21
## Enabled features: fontconfig, freetype, ghostscript, lcms, webp
## Disabled features: cairo, fftw, heic, pango, raw, rsvg, x11
print(img)
## # A tibble: 1 × 7
##   format width height colorspace matte filesize density
##   <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
## 1 PNG     1135    809 sRGB       TRUE         0 28x28
```

**Comment by pkrog** [comment]
> I am not so clear on why you have two vignettes. The 'databases' vignette material follows naturally from the intro material. In the databases vignette, you don't give any indication what a compound id is, and the intro vignette has a good example linking compound ids to compound names.
> 
> The printing events near end of databases vignette (Linking to ImageMagick, and the tibble) seem extraneous.
> 
> ```
> img <- kegg.path.conn$getDecoratedGraphPicture(pathways[[1]],
>                                                color2ids=color2ids)
> ## Linking to ImageMagick 6.9.12.21
> ## Enabled features: fontconfig, freetype, ghostscript, lcms, webp
> ## Disabled features: cairo, fftw, heic, pango, raw, rsvg, x11
> print(img)
> ## # A tibble: 1 × 7
> ##   format width height colorspace matte filesize density
> ##   <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
> ## 1 PNG     1135    809 sRGB       TRUE         0 28x28
> ```

I have merged the two vignettes as you have suggested, and remove outputs from magick package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pkrog.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biodbKegg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biodbKegg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
