### ISSUE TITLE
NxtIRF data package submission

### ISSUE THREAD

**Issue by alexchwong** [Bioconductor/Contributions#2293]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/alexchwong/NxtIRFdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by alexchwong** [comment]
Hi there,

The errors on R cmd check is due to tests failing. These tests check whether the queried data exists on AnnotationHub / ExperimentHub and are probably failing because these are not yet available.

I have already uploaded the requisite files to S3 bucket and provided the required metadata.csv which is included with this package. However, the data does not seem to have been included yet.

Once the data is accepted and included in AnnotationHub / ExperimentHub, this build should pass all checks. Could you please check if there are any problems with the data / metadata I have provided? Thanks in advance

**Comment by alexchwong** [comment]
AdditionalPackage: https://github.com/alexchwong/NxtIRFcore

**Comment by alexchwong** [comment]
Please note that NxtIRFcore depends the NxtIRFdata package. It will not pass R CMD CHECK unless NxtIRFdata package is available.

**Comment by alexchwong** [comment]
Hi @hpages 
A "warning" is triggered by R cmd build on Windows due to this:
* building 'NxtIRFcore_0.99.1.tar.gz'
Warning: file 'NxtIRFcore/cleanup' did not have execute permissions: corrected
Warning: file 'NxtIRFcore/configure' did not have execute permissions: corrected

These scripts have "755" permissions and do not trigger warning on linux and MacOS. But I note this occurs in windows because it uses a non-posix file system.

In my package, "configure" and "config" is used to detect between linux and MacOS, and checks for OpenMP on the latter to add appropriate flags. The files are not used on Windows builds. I have searched extensively online and cannot find any way to rectify the "file permissions" problem on Windows.

Can this warning be safely ignored? If not, could you advise how I could fix this?

**Comment by alexchwong** [comment]
Hi @hpages 

I tried resolving the execute permissions issue on Windows without much luck. The warning seems to appear regardless of the execute permissions. Please advise if anything more can be done to solve this build warning issue on Windows.

**Comment by hpages** [comment]
Hi @alexchwong,

Sorry for the slow answer. Let's ignore the execute permissions issue on Windows. We've seen it before for other packages and it's not clear what's going on but it looks like a false positive. 

Package looks good and is almost ready for acceptance. Only one minor cosmetic thing: please use `<-` instead of `=` for assignment, with a space before and after the left arrow. Using `=` is not good R programming style and it can cause problems in some situations (e.g. when you wrap the expression inside a `system.time()` or `suppressMessages()` statement).

Thanks,
H.

**Comment by alexchwong** [comment]
Thanks @hpages . The `=` to `<-` changes have been made in the latest build.

**Comment by alexchwong** [comment]
Apologies, a few minor necessary additions. Hopefully no more edits required.

Added updates:
0.99.6: Added convenience functions `BAM2COV()` and `GetCoverageRegions()`
0.99.8: Fixed memory leak when writing COV files

**Comment by hpages** [comment]
These updates look good to me.

Thanks for using `<-` instead of `=` for assignment.

~Package is~ Packages are good to go.

Cheers,
H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alexchwong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NxtIRFdata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NxtIRFdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alexchwong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NxtIRFcore")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NxtIRFcore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
