### ISSUE TITLE
sccomp

### ISSUE THREAD

**Issue by stemangiola** [Bioconductor/Contributions#2299]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stemangiola/sccomp

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by stemangiola** [comment]
Hello @lshep ,

I have fixed the repo, including rewriting the history to delete the files in the git that produce the failure in the check

```

This is BiocCheckGitClone version 1.29.14. BiocCheckGitClone is a work
in progress. Output and severity of issues may change.
* Checking valid files...
    * ERROR: System Files found that should not be git tracked:
        src/RcppExports.o
        dev/latex_equations.log
```

I am trying to push to upstream forcing (because of the history change) however Bioconductor does not let me do

```
git push upstream master --force
```

```
rstudio-1 258 % git push upstream master --force
Counting objects: 820, done.
Delta compression using up to 56 threads.
Compressing objects: 100% (225/225), done.
Writing objects: 100% (785/785), 3.42 MiB | 1.80 MiB/s, done.
Total 785 (delta 574), reused 747 (delta 543)
remote: Resolving deltas: 100% (574/574), completed with 22 local objects.
remote: FATAL: + refs/heads/master packages/sccomp stemangiola DENIED by fallthru
remote: error: hook declined to update refs/heads/master
To git@git.bioconductor.org:packages/sccomp.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/sccomp.git'
```

Could you please advise? Maybe we can start over?

**Comment by lshep** [comment]
@nturaga   any suggestions on this?

**Comment by lshep** [comment]
We do not allow users to do a force push.  I think I have reset the repository.  Please try to do a version bump to kick off a new build.

**Comment by stemangiola** [comment]
> We do not allow users to do a force push. I think I have reset the repository. Please try to do a version bump to kick off a new build.

Thanks, I will today.

**Comment by stemangiola** [comment]
Hello @lshep,

for the error 

```
* ERROR: Remove install() calls (found 1 times)
        install.packages() in R/functions_dirichlet_multinomial.R (line
      285, column 5)
```

This install.package is inside a function that is mostly for internal benchmarking (and possible extremely rarely used by a user), but integrated into the package, and I don't want to add non-necessary dependencies.

Could we ignore this error for publication? (I'm solving the other errors/warnings)

**Comment by stemangiola** [comment]
> Hello @lshep,
> 
> for the error
> 
> ```
> * ERROR: Remove install() calls (found 1 times)
>         install.packages() in R/functions_dirichlet_multinomial.R (line
>       285, column 5)
> ```
> 
> This install.package is inside a function that is mostly for internal benchmarking (and possible extremely rarely used by a user), but integrated into the package, and I don't want to add non-necessary dependencies.
> 
> Could we ignore this error for publication? (I'm solving the other errors/warnings)

I solved all other errors ;)

**Comment by vjcitn** [comment]
Hi Stefano -- this sounds like a case for "Enhances" for the package in question.  I'd propose that you use
```
if (!requireNamespace("[pkg u don't want to depend on]")) stop("please install [pkg...] to use this function")
```
and put the pkg... in the Enhances field in DESCRIPTION.  Other approaches could be used as well, but we really want to be systematic about removing `install` operations from user code.

**Comment by lshep** [comment]
I agree with the above suggest.  Please implement the above suggestion.  I will provide a more detailed review shortly.

**Comment by stemangiola** [comment]
Hello @Kayla-Morrell ,

for the warning

```
 WARNING: R CMD check exceeded 10 min requirement
```

my package has to compile C++ code and takes a bit longer. Is this a deal-breaking problem? (I will try to optimise in the future)

**Comment by Kayla-Morrell** [comment]
@stemangiola - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

Also, I would say the WARNING above is fine for now but should be addressed in the future.

## General package development

- [ ] REQUIRED: What is the purpose of the 'dev/' directory? This isn't usually
  something we include in Bioconductor packages.

## DESCRIPTION

- [ ] REQUIRED: Malformed Title field, should not end in a period.

- [ ] SUGGESTION: The Description field is made up by less than 3 sentences.
  Please consider expanding this field, and structure it as a full paragraph.

- [ ] REQUIRED: 'LazyData' should be set to false or removed.

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports' field which
  includes a relevant link to GitHub for reporting issues.

## NAMESPACE

- [ ] SUGGESTION: Consider adding
    importFrom("graphics", "par")
    importFrom("utils", "data")

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be
  included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: The documentations for the data could use a bit more
  information. For almost all of them, the description is just the name of the
data file. There should be a bit more information about creation if possible.

## Vignettes

- [ ] REQUIRED: When I generate the vignette, the logo does not display. This
  should be resolved. My suggestion would be to move all figures/images needed
for the vignette to the vignette directory, then reference from there.

- [ ] REQUIRED: There needs to be an Introduction section that serves as an
  abstract to introduce the objective, models, unique functions, key points, etc
that distinguish the package from other packages in the same area.

- [ ] REQUIRED: The Installation section should demonstrate to the user how to
  install the package from Bioconductor. The code should look like the following
and include `eval = FALSE`.

```{r}
if (!requireNamespace("BiocManager")) {
  install.packages("BiocManager")
}
BiocManager::install("sccomp")
```

- [ ] REQUIRED: The table of contents didn't render when I generated the
  vignette.

- [ ] REQUIRED: All code chunks need to be evaluated. There should be some text
  that accompany the code chunks explaining what is being demonstrated.

- [ ] REQUIRED: It should be visable to users what libraries and data are being
  loaded, lines 26-33 should be shown.

## Man pages

- [ ] REQUIRED: There should not be figures in this directory. Depending on
  where they are used they should either be in the vignettes directory or the
inst directory.

- [ ] REQUIRED: All exported objects need to be documented,
design_matrix_and_coefficients_to_simulation is undocumented and is exported.

- [ ] REQUIRED: For examples, the function being documented needs to be shown.
  For example, in the replicate_data man page the example code is demonstrating
sccomp_glm and not replicate_data.

- [ ] SUGGESTION: For any unexported object that is documented I would suggest
  adding the `@keywords internal` tag to remove the function from the
documentation index.

## Unit tests

- [ ] REQUIRED: It doesn't seem like your tests in test-sccomp.R are actually
  testing anything. There are no `expect_*` statements. If I'm wrong please
justify.

## R code

- [ ] SUGGESTION: Consider clarifying how 152 objects are initialized. Maybe
  they are part of a data set loaded with data(), or perhaps part of an object
referenced in with() or within(). See the BiocCheck result of the build report
for the list of objects.

- [ ] REQUIRED: We don't like to see seeds being used in code. The user should
  always have the option for setting the seed and know when it is being invoked.

- [ ] REQUIRED: Avoid sapply(); use vapply() instead where possible. Found in
files:
    R/stanmodels.R, line 12
    R/validation.R, line 16

- [ ] REQUIRED: Use is() instead of class() == and class() !=.

- [ ] REQUIRED: Avoid 1:..., use seq_len() or seq_along() instead where
possible. Found in files:
    functions_dirichlet_multinomial.R, lines 53, 177, 178, 333, and 336
    functions_multi_beta_binomial.R, lines 52, 281, 288, and 391
    function_multi_beta.R, line 36
    methods.R, lines 297 and 376
    utilities.R, lines 248, 272, 287, 292, 439, 554, 634, 683, 686, 764, 765,
    767, 768, and 783

- [ ] REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible. Found in
  files:
    R/utilities.R, lines 263, 410, and 422

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 250
  lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There are 8 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 1076 lines that are not.

Best,
Kayla

**Comment by stemangiola** [comment]
Thanks a lot, @Kayla-Morrell for your feedback.

> @stemangiola - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> Also, I would say the WARNING above is fine for now but should be addressed in the future.
> 
> ## General package development
> * [x]  REQUIRED: What is the purpose of the 'dev/' directory? This isn't usually
>   something we include in Bioconductor packages.
> 

This directory includes some R scripts for paper publication, that has always been part of our Github repositories. This is in the .Rbuildignore. 

> ## DESCRIPTION
> * [x]  REQUIRED: Malformed Title field, should not end in a period.

Done.

> * [x]  SUGGESTION: The Description field is made up by less than 3 sentences.
>   Please consider expanding this field, and structure it as a full paragraph.

Done

> * [x]  REQUIRED: 'LazyData' should be set to false or removed.

When we use Bayesian inference this option needs to be 'true' Bioconductor already accepted this for our package `ppcseq`

> * [x]  SUGGESTION: We strongly encourage the use of the 'BugReports' field which
>   includes a relevant link to GitHub for reporting issues.

Thanks done.

> 
> ## NAMESPACE
> * [x]  SUGGESTION: Consider adding
>   importFrom("graphics", "par")
>   importFrom("utils", "data")

I have added utils data, for par I don't find where I use it.

> 
> ## NEWS
> * [x]  SUGGESTION: Consider adding a NEWS file, so your package news will be
>   included in Bioconductor release announcements.

Done

> 
> ## Data
> * [x]  REQUIRED: The documentations for the data could use a bit more
>   information. For almost all of them, the description is just the name of the
>   data file. There should be a bit more information about creation if possible.

Done

> 
> ## Vignettes
> * [x]  REQUIRED: When I generate the vignette, the logo does not display. This
>   should be resolved. My suggestion would be to move all figures/images needed
>   for the vignette to the vignette directory, then reference from there.

Done

> * [x]  REQUIRED: There needs to be an Introduction section that serves as an
>   abstract to introduce the objective, models, unique functions, key points, etc
>   that distinguish the package from other packages in the same area.

Done

> * [x]  REQUIRED: The Installation section should demonstrate to the user how to
>   install the package from Bioconductor. The code should look like the following
>   and include `eval = FALSE`.
> 
> ```
> if (!requireNamespace("BiocManager")) {
>   install.packages("BiocManager")
> }
> BiocManager::install("sccomp")
> ```
> 

Done

> * [ ]  REQUIRED: The table of contents didn't render when I generated the
>   vignette.



> * [x]  REQUIRED: All code chunks need to be evaluated. There should be some text
>   that accompany the code chunks explaining what is being demonstrated.

Done

> * [x]  REQUIRED: It should be visable to users what libraries and data are being
>   loaded, lines 26-33 should be shown.

Done

> 
> ## Man pages
> * [x]  REQUIRED: There should not be figures in this directory. Depending on
>   where they are used they should either be in the vignettes directory or the
>   inst directory.

Done

> * [x]  REQUIRED: All exported objects need to be documented,
>   design_matrix_and_coefficients_to_simulation is undocumented and is exported.

design_matrix_and_coefficients_to_simulation  is not exported anymore

> * [x]  REQUIRED: For examples, the function being documented needs to be shown.
>   For example, in the replicate_data man page the example code is demonstrating
>   sccomp_glm and not replicate_data.

Done

> * [x]  SUGGESTION: For any unexported object that is documented I would suggest
>   adding the `@keywords internal` tag to remove the function from the
>   documentation index.
> 

Done

> ## Unit tests
> * [x]  REQUIRED: It doesn't seem like your tests in test-sccomp.R are actually
>   testing anything. There are no `expect_*` statements. If I'm wrong please
>   justify.
> 

Done

> ## R code
> * [ ]  SUGGESTION: Consider clarifying how 152 objects are initialized. Maybe
>   they are part of a data set loaded with data(), or perhaps part of an object
>   referenced in with() or within(). See the BiocCheck result of the build report
>   for the list of objects.
> * [x]  REQUIRED: We don't like to see seeds being used in code. The user should
>   always have the option for setting the seed and know when it is being invoked.

I changed the argument to mcmc_seed and specified that this seed is sampled at random (by default) and needed for Markov Chain Monte Carlo reproducibility if a user chooses so.

> * [x]  REQUIRED: Avoid sapply(); use vapply() instead where possible. Found in
>   files:
>   R/stanmodels.R, line 12
>   R/validation.R, line 16

Done for validation. For stanmodel.R this was automatically generated by Stan, and must not be edited by hand.

> * [x]  REQUIRED: Use is() instead of class() == and class() !=.

Done

> * [x]  REQUIRED: Avoid 1:..., use seq_len() or seq_along() instead where
>   possible. Found in files:
>   functions_dirichlet_multinomial.R, lines 53, 177, 178, 333, and 336
>   functions_multi_beta_binomial.R, lines 52, 281, 288, and 391
>   function_multi_beta.R, line 36
>   methods.R, lines 297 and 376
>   utilities.R, lines 248, 272, 287, 292, 439, 554, 634, 683, 686, 764, 765,
>   767, 768, and 783

Done

> * [x]  REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible. Found in
>   files:
>   R/utilities.R, lines 263, 410, and 422

For line 263, pivot_longer generates a benign warning that is not clear how to avoid given their documentation. For separate was extra="drop".

For lines 410 and 422, rstan generated benign warnings about unjustified thresholds of convergence (they are currently addressing those). Those although completely benign, confuse users about the results, that we have extensively benchmarked and soon published.

I will take care of those ASAP, according to the Stan community

> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 250
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
>   There are 8 lines that contain tabs.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 1076 lines that are not.
> 
> Best, Kayla

**Comment by stemangiola** [comment]
Hello @Kayla-Morrell fixed issues, please find my reply to your review above.

Thanks for your time.

**Comment by stemangiola** [comment]
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> On one or more platforms, the build results were: "WARNINGS". This may mean there is a problem with the package that you need to fix. Or it may mean that there is a problem with the build system itself.
> 
> Please see the [build report](http://bioconductor.org/spb_reports/sccomp_buildreport_20211022201000.html) for more details. This link will be active for 21 days.
> 
> ** Remember: **if you submitted your package after July 7th, 2020, when making changes to your repository push to `git@git.bioconductor.org:packages/sccomp` to trigger a new build. A quick tutorial for setting up remotes and pushing to upstream can be found [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/).

I am a bit confused as I see WARNINGS in the summary but I don't see any warnings for

```
WARNING count: 
```

**Comment by lshep** [comment]
Its coming from the longer check time.

**Comment by stemangiola** [comment]
> Its coming from the longer check time.

I see. Thanks. We agreed that it is a goal to optimise compilation down the road. Please let me know if anything else is needed.

Thanks a lot for your time.

**Comment by stemangiola** [comment]
Hello @lshep and @Kayla-Morrell thanks for your effort in reviewing sccomp.

I see that sccomp has not been added to the 3.14 release. Given our discussion can I please know the reason?

This submission was for me very important in the perspective of imminent article submission.

Is there any chance the package can be admitted, considering that the only warning is the long compilation time, that I have been told to fix in the future?

**Comment by Kayla-Morrell** [comment]
@stemangiola - Thank you for making the necessary changes. I have re-reviewed the package and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stemangiola.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sccomp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sccomp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The package is now accepted and added to the devel branch of Bioconductor (3.15).  The landing page for the package should be generated over the weekend.  For publication it is best to reference the short url for the package as it will default to the current release version of the package landing page if available, and if it is not yet in a release branch default to the development page.  The short url for your package is:  https://bioconductor.org/packages/sccomp/

**Comment by stemangiola** [comment]
Thanks for your time, @lshep @Kayla-Morrell
