### ISSUE TITLE
PharmacoGx

### ISSUE THREAD

**Issue by p-smirnov** [Bioconductor/Contributions#23]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/PharmacoGx

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by p-smirnov** [comment]
Hello Valerie,

I am resubmitting through the new github tracker as you directed. To address the main issues that will come up, we want to transfer the package from CRAN to Bioconductor since it heavily relies on other Bioconductor packages and fits with the focus well. We will ask CRAN to remove the package once the review process is finished, but the version number should remain > 1.1.6 as that is the version currently on CRAN. Should we bump the version number of the submission to 1.99.z or similar?

Best,
Petr

**Comment by vobencha** [comment]
Hi,
Thanks for resubmitting in the new location. It's fine to leave the package on CRAN until the approval process is done; just wanted to make sure you were aware it would have to be removed. Why don't you bump the version to 1.1.7 and we'll go from there. Below I've pasted in my comments from the first review. Please let me know which issues have been addressed (of those that are still relevant).
Valerie

From the old tracker:

I've done a first review of PharmacoGx. The package looks good, just a few suggestions and comments below.

1) removal from CRAN

We can't add the package to Bioconducotor until it is removed from CRAN.

2) biocCheck issues

Please address these:

* Checking R Version dependency...
    * RECOMMENDED: Update R version dependency from 3.2 to 3.3.

* Checking for F...
      Found F in R/geneDrugPerturbation.R (line 62, column 199)
    * RECOMMENDED: Use FALSE instead of F (found in 1 files)

* Checking man pages...
    * RECOMMENDED: Add non-empty \value sections to the following man
      pages:
      CCLEsmall.Rd, checkPSetStructure.Rd, CMAPsmall.Rd,
      drugDoseResponseCurve.Rd, GDSCsmall.Rd, HDAC_genes.Rd,
      PharmacoSet-class.Rd, show-PharmacoSet-method.Rd,
      show-PharmacoSig-method.Rd, showSigAnnot.Rd,
      sub-PharmacoSet-method.Rd
* Checking exported objects have runnable examples...
    * CONSIDER: Adding runnable examples to the following man pages
      which document exported objects:
      availablePSets.Rd, computeAUC.Rd, computeIC50.Rd,
  downloadPertSig.Rd, downloadPSet.Rd, drugDoseResponseCurve.Rd,
  logLogisticRegression.Rd, PharmacoSet.Rd, showSigAnnot.Rd

* Checking for bioc-devel mailing list subscription...
    * REQUIRED: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

3) unnecessary files in vignettes/

I think CreatingPharmacoSet-concordance.tex in vignettes/ is unnecessary? Please remove or explain why you 
have it there.


4) man pages for data/ files

Please explain the data files in more detail. What type of object are they (e.g., matrix, data.frame, named 
vector) and what data do they contain. If the data are manipulated or derived please note the origin and 
what was done to produce the final output.

For example, data(CMAPsmall) loads a PharmacoSet that is 51 by 1018. What do the 51 and 1018 stand for? 
mention that there are 5 cell lines, 5 drug compounds etc.


5) S4 classes

It looks like you define two S4 classes, PharmacoSig and PharmacoSet but only PharmacoSet is exported. The 
getters and setters for this class should be defined using '@' slot access. Once that's done all other 
methods should use the getters and setters and not direct slot access with'@'.

For example, why does the show,PharmacoSet-method use '@'? The show method should use the defined getters 
and setters.


6) Why the layered PharmacoSet and .PharmacoSet class design?

**Comment by p-smirnov** [comment]
Hello Valerie,

Going in order: 
* The R version dependency addressed.
* The F's being picked up by the check are from a column name, specifically the F test value being returned by a call to anova (the column name is "Pr(>F)"$). They appear in two places now, "geneDrugPerturbation" and "geneDrugSensitivity". 
* Value sections: I believe all the function listed are show methods or plotting methods (or datasets which have a format section instead of a value section)
Runnable examples added to the some functions, other functions either download objects from the Internet or plot/print values. The PharmacoSet constructor has a vignette dedicated to it as it is more complex than would be intelligible in a man page. 

* Vignette extra files: I cleaned up all extra files except for the built pdf files. Should I also delete the pdf files or is it enough to add then to RBuildIgnore and RInstIgnore? I think they could be useful to keep in the github repository for people looking at the source. 
* The small datasets are a bit tricky. I want to downplay their existence in the package, as they really have been reduced in size to the point where they are totally meaningless. They are included only to enable the examples to run on a proper PharmacoSet object, but the intention is that the user will use the downloadPSet function to download the full datasets hosted on our webserver. The are several reasons to host on our own server instead of submitting an associated data package: 

1. In the case that errors are discovered in our curation of the cell line and drug identifiers, we would want to update the objects. This may happen often enough for newer datasets that, especially in conjunction with the size of the data, it would place an unfair burden on your build/check system. 
2. If we release studies analyzing datasets for which we create new PharmacoSet objects, we want to have those objects easily accessible to users immediately so they are able to reproduce the analysis. This does not mesh well with the release cycle model of Bioconductor. 
Users should be able to download only the datasets they need. We could create a separate data package for each dataset we curate, but that seems like a lot of wrapping for what is effectively one .rda file. 
3. We do plan to write vignettes detailing exactly how we processed the raw data and which versions of which packages were used to create each object and make them available through our website alongside the objects. 

* The PharmacoSig class is not exported because it is highly unlikely that it will ever be of any use to someone to create their own objects or to extend it. It exists only to record information about the call used to generate the object, and to overload the show method for the class to prevent the whole object printing out when it is entered into an R session. The object is a 3D array, and they can get quite big (~12000*1200*6). R prints out arrays by treating them as matrices splitting by the last dimensions, but that means that if someone accidentally prints out this array, they are flooded with 6 consecutive matrices of the maximum print size. To prevent this the simple show method was implemented, but the class itself is very simple. 
* I removed many of the @ slot access calls, in some places they are required however (like the subsetTo function) to access slots that don't have a get or set function. For example, the object realizes the storage of an arbitrary number of ExpressionSet objects for molecular data through a list, so the list of all the ExpressionSets is stored in the molecularData slot. However, there is a get/set function to access each element of the molecularData list, but not to access the list as a whole, as the realization of the storage should be abstracted away. However, to operate on all the objects for functions like subsetTo, it is necessary to retrieve the list as a whole through direct slot access. 
* Finally, the layered PharmacoSet design is because, as above, the slots don't correspond to the arguments of the constructor. Specifically, the sensitivity slot is a list that has a fixed maximum number of elements (4), and those are each separate (optional) arguments to the constructor. This construction was also emulated off of the ExpressionSet constructor, as originally we attempted to extend that class (but quickly realized that it would be too confusing to the user since the objects don't behave similarly in many cases).

**Comment by p-smirnov** [comment]
@vobencha There have also been some new functions added to the package, could you run the package through the bioconductor test build system to test the current version of the package?

**Comment by vobencha** [comment]
Hi,

To start a new build, commit the changes to your github repo and bump the version DESCRIPTION. The incremented version is the trigger.

Thanks for making the changes and for giving detailed explanations. You asked about the built pdf files - we don't want them in svn because they are redundant when the files (pdf and Rnw) are in sync and stale when they aren't. Unless you build the package yourself each time a change is made the pdf on github will likely be out of date. The problem with using .RBuildIgnore and .RInstallIgnore is that the pdf file is still checked into svn.

If you want to maintain a separate directory of documentation under inst/, such as inst/extdocs you could. The problem is (again) that the vignette pdf stored in inst/extras will be out of snyc of the vignette built with R CMD build unless you hand build, untar, transfer the file and retar.

Valerie

**Comment by p-smirnov** [comment]
@vobencha Ok, no problem to remove those files! 
I am not 100% sure about the current build system, but looking at the process for the review of other packages, they were all marked "approved for building" with a message to set up the web hook to the repository, which hasn't happened in this review process. Would the web hook still work without confirmation from your side?

**Comment by vobencha** [comment]
Did you set up a web hook in the PharmacoGx repo as described here:

https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

If you've done that then the problem is on our side.

**Comment by vobencha** [comment]
I see, the initial build didn't even happen. Let me look into this with Martin and Lori. In the mean time, please make sure your webhook is set up.
Thanks.

**Comment by p-smirnov** [comment]
@vobencha: 
Hi Valerie,

If I had to guess, I think the issue is that the default branch (only branch) of our repository is not named master, so the build system cannot fetch the package automatically. The file size is reported as -1 KB.

Petr

**Comment by p-smirnov** [comment]
Hi @mtmorgan, @vobencha,

The build system still fails to download the package and check it, although the failure is inconsistent between checks. 

Also, from the previous check I could not reproduce the vignette building error and it resolved itself this time around. 

Best ,
Petr

**Comment by vobencha** [comment]
Hi,

We're away at BioC2016 and will look into the build problem when we get back on Wednesday.

A few follow up questions:

1) Are you registered on bioc-devel?

* Checking for bioc-devel mailing list subscription...
    * REQUIRED: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

2) I want to revisit this bullet from your message above:

" Value sections: I believe all the function listed are show methods or plotting methods (or datasets which have a format section instead of a value section)
Runnable examples added to the some functions, other functions either download objects from the Internet or plot/print values. The PharmacoSet constructor has a vignette dedicated to it as it is more complex than would be intelligible in a man page. "

Which trigger these BiocCheck messages:

* Checking man pages...
    * RECOMMENDED: Add non-empty \value sections to the following man
      pages:
      CCLEsmall.Rd, checkPSetStructure.Rd, CMAPsmall.Rd,
      computeSlope.Rd, dim-PharmacoSet-method.Rd,
      drugDoseResponseCurve.Rd, GDSCsmall.Rd, HDAC_genes.Rd,
      PharmacoSet-class.Rd, show-PharmacoSet-method.Rd,
      show-PharmacoSig-method.Rd, showSigAnnot.Rd,
      sub-PharmacoSet-method.Rd
* Checking exported objects have runnable examples...
    * CONSIDER: Adding runnable examples to the following man pages
      which document exported objects:
      availablePSets.Rd, downloadPertSig.Rd, downloadPSet.Rd,
  drugDoseResponseCurve.Rd, mDataNames.Rd, PharmacoSet.Rd,
  showSigAnnot.Rd

i) You said all man pages that did not have \value had a \format section. That is not true for quite a number of those pages. Looks like these have neither \value or \format:
checkPSetStructure.Rd
computeSlope.Rd
dim-PharmacoSet-method.Rd
drugDoseResponseCurve.Rd
PharmacoSet-class.Rd
show-PharmacoSet-method.Rd
showSigAnnot.Rd
sub-PharmacoSet-method.Rd

ii) The point of the man pages and vignette is to test exported functions in the nightly builds. The idea is early detection when something goes wrong with either your package or a dependency, a change in R etc. Ideally, if a function is not tested in the man page it should be run in the vignette. Because of all the eval=FALSE statements in the vignette, these functions do not have run-able man page examples and are not tested in the vignette so they are not tested anywhere in the package:
availablePSets.Rd
downloadPertSig.Rd
downloadPSet.Rd,
drugDoseResponseCurve.Rd
mDataNames.Rd
showSigAnnot.Rd

Are you concerned about runtime?

iii) Please mention the vignette in the \details or \description section of PharmacoSet.Rd and add an example section that directs the user to the vignette, e.g.,
browseVignettes("PharmacoGx")

Valerie

**Comment by p-smirnov** [comment]
Hi Valerie (@vobencha),


Thank you for your help dealing with the issues! The last build seemed to go through, even though moscato still reports a package size of -1.0 KB. 

1) The maintainer is subscribed to the mailing list now.

2) For the following files:
show-PharmacoSet-method.Rd
showSigAnnot.Rd
sub-PharmacoSet-method.Rd

They do not return anything, they only print using cat/warnings/message/print/stop to the respective output connections. 

The file:
drugDoseResponseCurve.Rd
Graphs to the current graphics device but does not return anything.
The remaining files have value sections added.

Similarly: 
availablePSets.Rd
downloadPertSig.Rd
downloadPSet.Rd,
All download files from the internet of 100's of MBs. It seems bad practice to have them run on your package check servers. Also, drugDoseResponseCurve is not run by the check in case the servers don't have access to a graphics device (And also because it does not close the graphics device).

The other two files I added runnable examples.

3) Reference added to the documentation page. 

I sent the package for another build, hopefully no new errors come up.

Thank you once again! 
Petr Smirnov

**Comment by vobencha** [comment]
Hi Petr,

According to section 2.1.2 of Writing R Extensions, \format is used to describe data sets, not functions, whereas \value is for function return values. 

Additionally, you need to have one \value section per man page. The one page per function approach of roxygen is not very useful and combining methods of similar type or class-related would make more sense. It looks like there are a couple of ways that roxygen documentation can occupy the same man page. One way is to use @rdname when within each component (e.g., parameter args) are collated in the order they appear in the .R file. I think there is also @describeIn. Whatever you decide, each page needs a \value section even if it just says 'no output' or 'describes contents of object "x"', etc.

* Please use \value instead of \format in your function man pages and make sure each page has a \value section. The package will not be approved until the output of BiocCheck is clean, i.e., all man pages have \value section.
* For the man pages that take too long (download too much data) please wrap the example in 
```
if interactive() {
 ...
}
```
This way a user calling example(availablePSets) from a workspace can see what the function does.

Valerie

**Comment by vobencha** [comment]
Hi,
Just checking in. Let me know if you have any questions.
Valerie

**Comment by p-smirnov** [comment]
Hi @vobencha,

We were fixing some issues pointed out by users of the package and also addressing the rest of the documentation issues. I think the main issues are address, for some reason BiocCheck does not recognize that these are dataset documentation pages and not functions, requiring a format and not value section: 
 RECOMMENDED: Add non-empty \value sections to the following man
      pages:
      CCLEsmall.Rd, CMAPsmall.Rd, GDSCsmall.Rd, HDAC_genes.Rd

Otherwise I think all the other doc pages have the required information. 

Petr

**Comment by p-smirnov** [comment]
Hi @vobencha.

I was wondering if you had a chance to take a look at the latest push. I believe all the issues have been addressed in the build, please let me know if anything else is required.

Thank you,
Petr

**Comment by vobencha** [comment]
No, sorry, I haven't. For some reason I thought you were still working on it. Will look at it today.
Valerie

**Comment by vobencha** [comment]
OK, I think we can call it good. Thanks for making all the changes and improving the package.

You'll get an email from Martin in the next week with svn credentials and next steps. Once the package is in Bioconductor you'll need to contact the CRAN maintainers to get it removed. Having the package in both CRAN and Biocondcutor will be a problem for biocLite() which looks in both repos.

I would also reccomend bumping the github version to 1.2.0 so there is a clear distinction from the 1.1.* version in CRAN.

Valerie

**Comment by vobencha** [comment]
Actually make that 1.3.0. The convention is that Bioconductor versions (x.y.z) are odd 'y' in devel and even 'y' in release.

**Comment by p-smirnov** [comment]
Ok, perfect! Thank you for your help and feedback, will bump the version to 1.3.0 before its pushed to svn. We will continue working on the package, incorporating feedback from users and improving the documentation prior to the next BioC release.
