### ISSUE TITLE
lineagespot

### ISSUE THREAD

**Issue by npechl** [Bioconductor/Contributions#2314]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BiodataAnalysisGroup/lineagespot

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Nikolas, @nikopech 

Thank you for your submission. Please see the comments below. 

Best regards,
Marcel

--- 

# lineagespot #2314

* Please explain how you leverage and integrate with the Bioconductor
ecosystem in `lineagespot`.
* See https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
* Consider submission to CRAN.

**Comment by npechl** [comment]
Hi @LiNk-NY,

Thank you for your comments. 

The main goal of `lineagespot` is to support the identification and quantification of SARS-CoV-2 lineage from wastewater samples using NGS data. As such, it is already used as part of a larger computational pipeline that produces the VCF files (used as examples here). In this context, we believe that it fits well within the BioConductor ecosystem, as it will also facilitate the connection to other open-source Bioinformatics platforms, such as [Galaxy](https://usegalaxy.eu/).

Although in the initial submission of `lineagespot` we were using the `vcfR` package to handle VCF files, we have now replaced that with the corresponding funcitionality offered by the `VariantAnnotation` package, present within Bioconductor. Although the overall performance has been now slightly reduced (it requires additional time for execution), we plan to continue optimizing this down the road. Of course, any suggestions/comments on how to improve this would be greatly appreciated.

Looking forward to your feedback.

Nikolas

**Comment by LiNk-NY** [comment]
Hi Nikolas, 
Please use the standard interface for working with vcf objects. 
That means using `rowRanges(vcf)`, `fixed(vcf)`, `info(vcf)`, etc. Please do not access slots using `@`. 
Also, please use `assays(x)[["AD"]]` instead of `x@assays@data$AD`.
Best,
Marcel

**Comment by npechl** [comment]
Hi @LiNk-NY 

Thank you for your comments. 
As you suggested, we changed specific parts of the code in order to use more standard functions for working with VCFs.

Looking forward to your response.

Regards,
Nikolas

**Comment by LiNk-NY** [comment]
Hi Nikolas, @nikopech 

Thank you for making those changes. I haven't seen a `CITATION.cff` used before.
It seems to work with `citation(package = "lineagespot")` though there is a warning:

```r
Warning messages:
1: In citation(package = "lineagespot") :
  no date field in DESCRIPTION file of package 'lineagespot'
2: In citation(package = "lineagespot") :
  could not determine year for 'lineagespot' from package DESCRIPTION file
```

Best regards,
Marcel

**Comment by npechl** [comment]
Hi @LiNk-NY,

Thank you for noticing the *citation warning*. 

In the provided repository, a `CITATION.cff` file is already contained. If for some reason it is not available through the `git@git.bioconductor.org:packages/lineagespot` repo, please let me know. 

In any case, after updating the DESCRIPTION file, command `citation(package = "lineagespot")`  works without any warning and gives the following:

```{r}
To cite package ‘lineagespot’ in publications use:

  Nikolaos Pechlivanis, Maria Tsagiopoulou, Maria Christina Maniou, Anastasis Togkousidis, Evangelia Mouchtaropoulou, Taxiarchis Chassalevris,
  Serafeim Chaintoutis, Chrysostomos Dovas, Maria Petala, Margaritis Kostoglou, Thodoris Karapantsios, Stamatia Laidou, Elisavet Vlachonikola,
  Anastasia Chatzidimitriou, Agis Papadopoulos, Nikolaos Papaioannou, Anagnostis Argiriou and Fotis E. Psomopoulos (2021). lineagespot:
  Detection of SARS-CoV-2 lineages in wastewater samples using next-generation sequencing. R package version 0.99.7.
  https://github.com/BiodataAnalysisGroup/lineagespot

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {lineagespot: Detection of SARS-CoV-2 lineages in wastewater samples using
next-generation sequencing},
    author = {Nikolaos Pechlivanis and Maria Tsagiopoulou and Maria Christina Maniou and Anastasis Togkousidis and Evangelia Mouchtaropoulou and Taxiarchis Chassalevris and Serafeim Chaintoutis and Chrysostomos Dovas and Maria Petala and Margaritis Kostoglou and Thodoris Karapantsios and Stamatia Laidou and Elisavet Vlachonikola and Anastasia Chatzidimitriou and Agis Papadopoulos and Nikolaos Papaioannou and Anagnostis Argiriou and Fotis E. Psomopoulos},
    year = {2021},
    note = {R package version 0.99.7},
    url = {https://github.com/BiodataAnalysisGroup/lineagespot},
  }
```
Looking forward to your response.

Best regards,
Nikolas

**Comment by npechl** [comment]
Hi @LiNk-NY,

I have made a small update on the `README.md` file. 
May I kindly ask you to continue with the review process?

Thank you for your time! Looking forward to your response. 

Regards,
Nikolas

**Comment by LiNk-NY** [comment]
Hi Nikolas, @nikopech 

We have received a lot of package submissions and I apologize for the delay. 
Please see the review below. Please remember to respond to all bullet points
made in the review. 

Best regards,
Marcel

---

# lineagespot #2314

## DESCRIPTION

* Looks good.

## NAMESPACE

* (optional) Consider shortening the function to `report_lineage` (verbs may
be easier to remember).
* Looks good.

## vignettes

* The timings in the vignette are not necessary. This information will be part
of the build report and can be acheived outside of R using `time R CMD check`.
* The `Installation` instructions will have to change. Once the package is
accepted, we will add it to the devel version of Bioconductor. The submission
process was not completed in time for the release.
* Use the less ambiguous assignment operator `<-` instead of `=` in all code.
* Please keep the text within the 80 character width limit (in vim you can use
`gqq` or `gq` after highlighting several lines)

### Minor
* `eval = TRUE` is not necessary when it is the default.

## R

* Please clarify the documentation regarding function arguments (e.g.,
`vcf_table`) by explicitly stating the type expected; in this case the output
of `merge_vcf`).
* Include more function input checks to ensure robust code, e.g., checking
that `vcf_table` is of a certain class or file (as this is not clear).
* Avoid writing files for the user in `lineagespot_hits` within the
`print.out` condition and simply return the table without saving a file. The
user can choose to save a file if they wish and in the format of their
choosing.
* Remove the `print.out` argument from lineagespot and related functions.
Writing to files for the user is not a desirable side effect.
* It is not necessary to use the `base::` qualifier for default functions.

## tests

* We highly recommend adding unit tests to increase robustness of the code.

**Comment by LiNk-NY** [comment]
Closed due to inactivity. Thank you for your submission. 
Best,
Marcel

**Comment by npechl** [comment]
@LiNk-NY @lshep 

Hello to you all,

A couple of months ago, we submitted `lineagespot` package as a new contribution to Bioconductor. 

Unfortunately, there were some changes regarding the team structure and we delayed the package development (we apologize for this). We have now considered all the comments above and corrected them. 

However I am not sure if I should open a new issue for the package contribution or if you can open the closed issue that already exists.

Thank you in advance!

Regards,
Nikolas

**Comment by lshep** [comment]
@nikopech   Please push the change to git.bioconductor.org to trigger the updated build report

**Comment by npechl** [comment]
@lshep 

Thank you for your quick response! I have just pushed to git.bioconductor.org and waiting for the build report.

**Comment by LiNk-NY** [comment]
Hi Nikolaos, @nikopech
Please respond to the review line by line to continue the process.
Thank you for your submission. 
Best,
Marcel

**Comment by npechl** [comment]
Hi Marcel, @LiNk-NY 

Thank you for your reply! Below I try to address each one of the issues you had raised.

> ## NAMESPACE
> * (optional) Consider shortening the function to `report_lineage` (verbs may
>   be easier to remember).
> * Looks good.

* For the moment we have not changed any functions' names, but we will definitely consider using verbs for naming the functions.

> ## vignettes
> * The timings in the vignette are not necessary. This information will be part
>   of the build report and can be acheived outside of R using `time R CMD check`.
> * The `Installation` instructions will have to change. Once the package is
>   accepted, we will add it to the devel version of Bioconductor. The submission
>   process was not completed in time for the release.
> * Use the less ambiguous assignment operator `<-` instead of `=` in all code.
> * Please keep the text within the 80 character width limit (in vim you can use
>   `gqq` or `gq` after highlighting several lines)

* The timings have been removed.
* We have not changed anything yet regarding the `Installation` instructions. Once the package is accepted we will update the instructions according to the devel version of Bioconductor. In case you think we should make the changes at this stage of the submission we can update the instructions and commit a new version. 
* All assigments with the `=` operator have been replaced with `<-`.
* We reformatted the code in order to be contained within the 80 character width limit.

> ### Minor
> * `eval = TRUE` is not necessary when it is the default.

* We have removed the `eval = TRUE` parameter.

> ## R
> * Please clarify the documentation regarding function arguments (e.g.,
>   `vcf_table`) by explicitly stating the type expected; in this case the output
>   of `merge_vcf`).
> * Include more function input checks to ensure robust code, e.g., checking
>   that `vcf_table` is of a certain class or file (as this is not clear).
> * Avoid writing files for the user in `lineagespot_hits` within the
>   `print.out` condition and simply return the table without saving a file. The
>   user can choose to save a file if they wish and in the format of their
>   choosing.
> * Remove the `print.out` argument from lineagespot and related functions.
>   Writing to files for the user is not a desirable side effect.
> * It is not necessary to use the `base::` qualifier for default functions.

* We clarified all functions' arguments as you suggested.
* We added more input checking functions to avoid any false inputs.
* We avoid any output file writing.
* The `print.out` arguments has been removed.
* Any direct package calling (`base::`) has beed corrected.

> ## tests
> * We highly recommend adding unit tests to increase robustness of the code.

* We have now included unit testing to ensure robust code.

Thank you for your time. Looking forward to your feedback.

Regards,
Nikolas

**Comment by LiNk-NY** [comment]
Hi Nikolas, @nikopech 

Thank you for your response and making those changes. 

I would recommend: 
* remove the `\dontrun{}` from the examples and
provide a small example that queries the API and caches the result.

* Consider renaming `list_gff3` to `is_gff3` for identification of gff3 files. 
* Please make these functions more robust, currently this returns `TRUE`
even though the file does not exist and the extension is not `gff3`.
```r
list_gff3("/path/to/fake/gff3/file.csv")
#' [1] TRUE
```

Best regards,
Marcel

**Comment by npechl** [comment]
Hello Marcel, @LiNk-NY 

We have applied some changes in order to take into incsideration your last reccomendations:

> * remove the `\dontrun{}` from the examples and
>   provide a small example that queries the API and caches the result.

This is now removed. We have also changed the unit testing part in order to include the situation for which the API does not provide the necessary information.

> * Consider renaming `list_gff3` to `is_gff3` for identification of gff3 files.
> * Please make these functions more robust, currently this returns `TRUE`
>   even though the file does not exist and the extension is not `gff3`.
> 
> ```r
> list_gff3("/path/to/fake/gff3/file.csv")
> #' [1] TRUE
> ```

The name of the function has been changed, and its functionality has become more robust.

Thank you for your time!

Regards,
Nikolas

**Comment by LiNk-NY** [comment]
Hi Nikolas, @nikopech 
Thank you for making those changes. 
Your package has been accepted. 
Best,
Marcel

**Comment by npechl** [comment]
Hello Marcel, @LiNk-NY 

Thank you for reviewing lineagespot package.

Is there anything that should be done by our side regarding the process following acceptance?

Thank you for your time!

Regards,
Nikolas

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nikopech.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("lineagespot")`. The package 'landing page' will be created at

https://bioconductor.org/packages/lineagespot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by LiNk-NY** [comment]
> Hello Marcel, @LiNk-NY
> 
> Thank you for reviewing lineagespot package.
> 
> Is there anything that should be done by our side regarding the process following acceptance?
> 
> Thank you for your time!
> 
> Regards, Nikolas

Hi Nikolas, @nikopech

I would recommend being familiar with this section of our guidelines:
https://contributions.bioconductor.org/git-version-control.html

These always come in handy whenever making improvements to the package. 
Best regards,
Marcel
