### ISSUE TITLE
pengls

### ISSUE THREAD

**Issue by sthawinke** [Bioconductor/Contributions#2316]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sthawinke/pengls

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Package looks good and is almost ready for acceptance.

2 minor cosmetic things:
1. Please use `<-` instead of `=` for assignment, with a space before and after the left arrow. Using `=` is not good R programming style and it can cause problems in some situations (e.g. when you wrap the expression inside a `system.time()` or `suppressMessages()` statement.
2. Vignette is strangely formatted e.g. the table of content appears at the top before the title and sections are not numbered. The end result is not particularly visually pleasing:
![Screenshot from 2021-10-12 21-09-02](https://user-images.githubusercontent.com/8810451/137065732-c4efbd0b-c39c-4e8a-b223-681574235933.png)


Thanks,
H.

**Comment by sthawinke** [comment]
Thanks for the review, the changes you requested have been made to the package.

Cheers,

Stijn

**Comment by hpages** [comment]
Thanks @sthawinke for the changes but please make sure that the rendered vignette has a title and author. This is how it looks in **pengls** 0.99.5:

![Screenshot from 2021-10-18 20-45-00](https://user-images.githubusercontent.com/8810451/137840478-e2680b99-1ec3-4a95-9883-0ac00578fab2.png)

Thanks,
H.

**Comment by hpages** [comment]
Thanks.

The title of the vignette ("Manual for the pengls pacakage") contains a typo in "pacakage". Also note that, in Bioconductor, vignettes are expected to demonstrate typical workflows so are not exactly the same as manuals.

Finally, in section "2 Installation instuctions" of your vignette you have:
```
library(BiocManager)
install("pengls", update = FALSE)
```
It's good practice to use `update=TRUE` here (which is the default).

Then later you have:
```
library(devtools)
install_github("sthaw/pengls", update = FALSE)
```
This is not how one is expected to install the development version of a Bioconductor package. Bioconductor is an ecosystem with tight interaction between packages and installing directly from GitHub will not play well with this. To install the development version of a Bioconductor package, one should first install the development version of Bioconductor with:
```
BiocManager::install(version="devel")
```
Note that this command itself might require to first update R to R-devel.

Then, one installs the development version of any Bioconductor package with `BiocManager::install()`, like for the release version.

Please correct section 2 of your vignette.

Thanks again,
H.

**Comment by sthawinke** [comment]
Dear H.

Thanks for your remarks, the corresponding changes haven been made in the readme and vignette.

Cheers,

Stijn

**Comment by hpages** [comment]
Thanks! Package is ready to go.

Cheers,
H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sthawinke.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pengls")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pengls

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
