### ISSUE TITLE
ggmsa

### ISSUE THREAD

**Issue by nyzhoulang** [Bioconductor/Contributions#2318]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/ggmsa

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package ggmsa

The package is in pretty good shape.
There are some minor issues need to be addressed.

## General package development

- [ ] Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin credentials). Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

- [ ] Please include Bioconductor installation instructions using BiocManager in README file.

## The DESCRIPTION file

- [ ] Please try to keep to an 80 character limit as `Description` field will otherwise be difficult to read when displayed online.
- [ ] A package URL and BugReports field is encouraged although not required

## The NEWS file

- [ ] The version in News file Does not fit the submission.

## Package data

- [ ] Raw data in `inst/extdata/` need documentation. `sysdata` in R folder may need documentation if the source is available.

## Documentation

- [ ] Vignette using `BiocStyle` package for formatting is suggested.
- [ ] Please include Bioconductor installation instructions using BiocManager.
- [ ] Please include `sessionInfo()` in vignette.
- [ ] Multiple rmd files are in `vignettes/guides` directory but not build.
- [ ] The VignetteIndexEntry are same for all the Rmd files.
- [ ] CONDUCT.md is not required for vignettes. Please move it to proper path.
- [ ] Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online.
- [ ] Package name and the main function name are same. The help page does not contain the help information for the package.

## Unit tests

- [ ] Consider adding unit tests. We strongly encourage them. See   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] Coding and syntax:
    * `message()`, `warning`, `stop` instead of `cat`.
    * Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online. 
    * clean up unused code.
    * `::` is not suggested in R code.
- [ ] Function arguments should be tested for validity, eg `tidymsa` in `mas_data`, `msa` in `ggmsa`.

**Comment by jianhong** [comment]
Could you please answer the review line by line to speed up the process when you are ready.

**Comment by nyzhoulang** [comment]
Dear Jianhong,

Thanks for the reminder.  Actually, I have only  completed part of the review at  present. 
    
I will report them in the above manner when I am fully prepared.
    
> Could you please answer the review line by line to speed up the process when you are ready.

Kind regards,
Lang

**Comment by nyzhoulang** [comment]
Dear Jianhong,
Here is a summary of the changes. Thank you!

> Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin credentials). Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

Done.  I am sure that I subscribed to the bioc-devel mailing list.

>  Please include Bioconductor installation instructions using BiocManager in README file.

Yes,  added.

> Please try to keep to an 80 character limit as Description field will otherwise be difficult to read when displayed online.
>  A package URL and BugReports field is encouraged although not required

Done.

> The version in News file Does not fit the submission.

Done, fixed the version number in `News` file.

> Raw data in inst/extdata/ need documentation. sysdata in R folder may need documentation if the source is available.

Yes, I added documentation for all raw data in  `inst/extdata/`

> Vignette using BiocStyle package for formatting is suggested.
>  Please include Bioconductor installation instructions using BiocManager.
>  Please include sessionInfo() in vignette.

Done 

>  Multiple rmd files are in vignettes/guides directory but not build.

 Done. I removed all rmd files from  `vignettes/guides` and build them on my `gh-pages` branch individually.

> The VignetteIndexEntry are same for all the Rmd files.

Done, ` VignetteIndexEntry`  have  be renamed.

>Function arguments should be tested for validity, eg tidymsa in mas_data, msa in ggmsa.
 
Done.  (in tests/testthat)


>CONDUCT.md is not required for vignettes. Please move it to proper path.

Done.

> Please try to keep to an 80 character limit as the code will otherwise be difficult to read when displayed online.
 
Done.

> Package name and the main function name are same. The help page does not contain the help information for the package.

It seems difficult to rename as they were determined at the beginning of the design.

>Consider adding unit tests. We strongly encourage them. See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

Done, unit tests added for `msa` in tidy_data,  `tidymsa` in `mas_data` and  `msa` in `ggmsa` by the  `thattest` package.

> message(), warning, stop instead of cat.
> Please try to keep to an 80 character limit as the code will otherwise be difficult to read when displayed online.
> clean up unused code.
> :: is not suggested in R code.
 
Done,  Now it is improved and clear. (only `base::strsplit` was remained to prevent function collisions)

**Comment by jianhong** [comment]
Please double check the email you used in the authors list is subscribed to the bioc-devel mailing list. Others look great to me.

**Comment by nyzhoulang** [comment]
Thanks,  jianhong

Sure. I have checked the `Bioc-devel` subscribers list.  The email (nyzhoulang@gmail.com) I used in the `authors list` is in the subscribers list.

![image](https://user-images.githubusercontent.com/46915370/136005845-7dff560e-f0bb-4a54-a2ca-331670a90e1c.png)
![image](https://user-images.githubusercontent.com/46915370/136006074-a1132f75-3d9b-4b9f-87cd-a58a2b2443ec.png)



> Please double check the email you used in the authors list is subscribed to the bioc-devel mailing list. Others look great to me.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nyzhoulang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggmsa")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggmsa

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
