### ISSUE TITLE
pairkat

### ISSUE THREAD

**Issue by cameronsevern** [Bioconductor/Contributions#2324]
Update the following URL to point to the GitHub repository of
the package you wish to submit to Bioconductor

Repository: https://github.com/Ghoshlab/pairkat
Confirm the following by editing each check box to '[x]'

[x ] I understand that by submitting my package to Bioconductor,
the package source and all review commentary are visible to the
general public.

[x ] I have read the Bioconductor Package Submission
instructions. My package is consistent with the Bioconductor
Package Guidelines.

[ x] I understand Bioconductor Package Naming Policy and acknowledge
Bioconductor may retain use of package name.

[x ] I understand that a minimum requirement for package acceptance
is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS.
Passing these checks does not result in automatic acceptance. The
package will then undergo a formal review and recommendations for
acceptance regarding other Bioconductor standards will be addressed.

[ x] My package addresses statistical or bioinformatic issues related
to the analysis and comprehension of high throughput genomic data.

[ x] I am committed to the long-term maintenance of my package. This
includes monitoring the support site for issues that users may
have, subscribing to the bioc-devel mailing list to stay aware
of developments in the Bioconductor community, responding promptly
to requests for updates from the Core team in response to changes in
R or underlying software.

[x ] I am familiar with the Bioconductor code of conduct and
agree to abide by it.

I am familiar with the essential aspects of Bioconductor software
management, including:

[ x] The 'devel' branch for new packages and features.
[ x] The stable 'release' branch, made available every six
months, for bug fixes.
[ x] Bioconductor version control using Git
(optionally via GitHub).
For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the Bioconductor website to sign up.

**Comment by lshep** [comment]
A few minor comments.


**DESCRIPTION**

- [ ] (Optional) We recommend having a BugReport field in the description that
  also points to https://github.com/Ghoshlab/pairkat/issues referenced in the
  README


**R code**

**PaIRKAT.R**

- [ ] Sould there be some format checking for a users input for formula.H0 and
  networks in the PaIRKAT function? to ensure the user passes the correct type
  of input.

- [ ] In formula_fun, the double paste/paste0 for a length(covs)  == 1 is not
  necessary?

- [ ] Please remove unused code. Comments are encouraged but commented out code
  that is not evaluated should be removed (ie. pval[i] = at the end of KAT.pval)


Once these few issues are addressed please bump the version to kick off a new build and comment back here that you are ready for a re-review.

**Comment by cameronsevern** [comment]
Hi @lshep. Thank you for your suggestions. I have made the changes you've recommended and am ready for re-review. Thanks again!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cameronsevern.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pairkat")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pairkat

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
