### ISSUE TITLE
RiboCrypt

### ISSUE THREAD

**Issue by m-swirski** [Bioconductor/Contributions#2328]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/m-swirski/RiboCrypt
Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```Loading required package: Rsamtools
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
Outputting libraries from: ORFik
1 :  RFP
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Loading required namespace: BSgenome.Hsapiens.UCSC.hg19
Quitting from lines 52-58 (RiboCryptOverview.rmd) 
Error: processing vignette 'RiboCryptOverview.rmd' failed with diagnostics:
could not find function "caller_env"
--- failed re-building ‘RiboCryptOverview.rmd’
```
Please check your package.

**Comment by vjcitn** [comment]
Do you really need to construct a TxDb object in the vignette?

**Comment by Roleren** [comment]
It is a very small sample gtf, so takes just a few milliseconds to create. 

The problem here was the new caller_env we added using rlang, pushing a fix now.

**Comment by m-swirski** [comment]
caller_env is fixed now.

**Comment by Roleren** [comment]
A question, we have been pushing fixes to:
git@git.bioconductor.org:packages/RiboCrypt.git

But the changes have not propagated to bioconductor,
and the bot above says push to:
git@git.bioconductor.org:packages/RiboCrypt
(Without .git in the end)

Does this matter ? As the submission tutorial states we must add .git in the end.

**Comment by vjcitn** [comment]
Your package passes check but I really wonder whether it should.
```
>   if (requireNamespace("BSgenome.Hsapiens.UCSC.hg19")) {
+     multiOmicsPlot_ORFikExp(extendLeaders(extendTrailers(cds[which.max(overlaps)], 30), 30), df = df,
+                             reference_sequence = BSgenome.Hsapiens.UCSC.hg19::Hsapiens, 
+                             frames_type = "columns")
+   }
Error in get_domains(length(plots), nrows, margin, widths = widths, heights = heights) : 
  The sum of the widths and heights arguments must be less than 1
```
That's me trying to run it by hand.  Your vignette does not produce the graphic.  It seems to generate HTML in the tempdir().  You are using rlang::caller_env ... I need to understand more of what is going on before I can accept this package.

**Comment by vjcitn** [comment]
OK, here's what I get when I use linux instead of M1 mac
![ribpic](https://user-images.githubusercontent.com/4624066/137480443-e83cef2b-9de5-4446-b634-d772d5e54202.png)

Now if you cannot render this inside the vignette itself, make a static image available so that the prospective user can understand what is being proposed.  I guess we can ignore the error in the previous comment.

The vignette is too terse.  Provide references and some explanation of what "frames for Ribo-seq / TCP-seq" are.  Does your dataset include outputs from these sequencing protocols?  Explain what ORFik.template.experiment is.  Can you give more information on what the ENSDART IDs are?  We need Hsapiens genome to run the function but the annotation shown is a zebrafish gene.  Try to make the vignette self-explanatory or provide convenient references for reader to obtain adequate background.

**Comment by vjcitn** [comment]
You can probably use htmlwidgets to render the display interactively in the generated html.  It is worth learning how to do this.

**Comment by m-swirski** [comment]
Hi Vince, I'll let Hakon answer the specific questions about the vignette. In general the vignette will be expanded to show all functionalities, I'll do my best to push new version over the weekend to give you time to review it before the Bioc 3.14 manifest.
Thanks for the suggestion about the htmlwidgets. We're aiming to do exactly what you're saying, and we'll be adding these functionalities successively - so far we prototyped sequence display on zoom (which is not yet added to the major branch), but the idea is to add much more features like that.

**Comment by vjcitn** [comment]
Just a reminder here, let me know when you have wrapped up for 3.14.

**Comment by m-swirski** [comment]
Hi, we pushed version with expanded vignette. It doesn't build correctly yet, because newest version of ORFik is required, which is not yet pushed to bioc. I attach zipped vigniette html, hopefully you'll find a moment to look at it.
The quality of the dummy data we created is admittedly not ideal yet, but hopefully the vignette is informative enough now. It's of course work in progress and we're improving a lot of things. You can see how it works with real data on my rpubs: https://rpubs.com/mswirski
We'll try to implement similar biologically relevant examples in the vignette, either as sampled real data or designed dummy datase
[RiboCrypt_overview.html.zip](https://github.com/Bioconductor/Contributions/files/7376205/RiboCrypt_overview.html.zip)
t.

**Comment by Roleren** [comment]
ORFik was pushed to devel now, so when bioc devel rebuilds, this vignette will work

**Comment by Roleren** [comment]
We believe the package now has a more comprehensive vignette, which should clearly show what RiboCrypt is useful for. And we believe it will pass the CMD check before Friday (since ORFik must first be re-built on devel first).

I will just note that we will add unit tests after release and expand the examples/vignette even more. We wait to make sure nothing breaks before the CMD deadline on Friday. 
Anything else needed before registering RiboCrypt to the package manifest?

**Comment by Roleren** [comment]
Any update on when you think the devel system will build, so that it will use newest ORFik?
The deadline is tomorrow right?

**Comment by lshep** [comment]
The top of [this page](http://bioconductor.org/developers/how-to/troubleshoot-build-report/) shows the timing for the builds. Since you pushed Tuesday evening, you missed the pull for Wednesday's build but it should be reflected on today's report. The new package assuming it built OK on our builds would be available later this afternoon.

**Comment by Roleren** [comment]
We now only have a remaining warning that our vignette contains interactive plots and therefore the vignette HTML file is > 5MB. 
We want to have interactive plots in vignette, as this is the whole point of the package. 
So can we keep it or what do you recommend?

**Comment by vjcitn** [comment]
it is sometimes possible to control data volume in HTML.  think about it, see if you can
slim it down.  i will look too.

**Comment by m-swirski** [comment]
The vignette is just 6MB, so to cut it below 5MB I can just remove one of the plots or put less data in it. In general we'll scale this down by combining several plots by dynamic dataset change etc, but for now it has to stay this way. So, should I just cut it below 5MB?

**Comment by vjcitn** [comment]
it seemed to me that one plot could go. first one seemed somewhat repetitious with second one.   i had 5.5MB built on linux so dropping one will probably scotch the warning

**Comment by vjcitn** [comment]
Will you trim the plot out of the vignette?  We will squeeze this in if so.

**Comment by m-swirski** [comment]
I have, vigniette was 4.9M on linux, so I thought it would be ok. I'll try to minimise it even more now.

**Comment by m-swirski** [comment]
Now it's 4.4, so should be a safe margin

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/m-swirski.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RiboCrypt")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RiboCrypt

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
