### ISSUE TITLE
IntramiRExploreR

### ISSUE THREAD

**Issue by sbhattacharya3** [Bioconductor/Contributions#233]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sbhattacharya3/IntramiRExploreR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by sbhattacharya3** [comment]
Hello,

I just saw that I just saw that I have 2 errors on my latest run. those are "Maintainer must subscribe to the bioc-devel mailing list." and "Maintainer must register at the support site."  I have already registered to both the sites last week.

Please let me know what is the procedure to get rid of those 2 errors.

Thanks,
Surajit

**Comment by mtmorgan** [comment]
DESCRIPTION, NAMESPACE

- OK

R

- It is not appropriate for software packages to contain large data
  objects. These could be isolated as a separate 'experiment data'
  package
  http://bioconductor.org/developers/package-guidelines/#package-types
  However, the data seems to be an ad-hoc summary of Target-scan and
  other data. These data objects are not sufficiently documented or
  processed in a reproducible way to be included in
  _Bioconductor_. I'm also concerned about re-distribution of data
  without appropriate licensing and permissions. For these reasons the
  data objects should be removed. They should be replaced by
  instructions for the user to download the data from their original
  source, and functions that take the downloaded data and transform it
  to a format useful to this package.
- e.g., `MiR_ChipBase()` but throughout -- follow the guidelines for
  avoiding iteration, using pre-allocate and fill, and vectorization;
  your current code is unacceptably
  inefficient. http://bioconductor.org/developers/how-to/efficient-code/
- Whenever providing a default file path, provide it in a temporary
  location, e.g., `tempdir()` or `tempfile()`.
- Create file paths using `file.path()` rather than `paste()`.
- If a user provides a file path your code should fail if the path
  already exists (`stopifnot(file.exists(...))`) or require that the
  user explicitly allows the file to be over-written (e.g., with an
  argument `overwrite=FALSE`).
- Validate all input parameters, e.g., `MiR_ChipBase()` should start
  with `stopifnot(is.character(m), length(m) == 1L, !is.na(m))` or
  similar.
- please adopt standard and consistent approaches to indentation,
  e.g., format the code at Chipbase_database.r:80 in the same was as
  at line 69. Consider using tools such as [formatR][] to arrive at
  consistent formatting.
- Ensure that your package conforms to overall Bioconductor size (and
  check time) constraints.
  http://bioconductor.org/developers/package-guidelines/#correctness
  
[formatR]: https://cran.r-project.org/package=formatR

vignettes

- Please update the installation instructions to match those after
  Bioconductor acceptance, i.e.

        source("https://bioconductor.org/biocLite.R")
        biocLite("IntramiRExploreR")

- `miRtargets()` line 44 has argument `outpath`, but this is (a)
  undefined and (b) unused in the function. Remove it, and review
  arguments in this and all function calls to ensure that they are (a)
  defined and (b) used).

- `GetGOS_ALL()` line 107 has argument `path="C://"`, apparently
  writing to the root directory. Do not do this, but instead use a
  temporary location, for a directory use `tempdir()` or for a
  temporary file `tempfile()`. Review all vignette and example code to
  ensure that ALL file arguments or outputs are located in temporary
  locations.
  
- review the output of all vignette code, making sure that it is
  visually meaningful; for instance the output of a[1:4,] is too wide
  for the output medium.

man

- Use R conventions (e.g., `character(1)`, `data.frame`) rather than
  ad-hoc descriptions for parameter and return values (e.g., "String",
  "Dataframe").

Other

- It is not appropriate to include the GPL LICENCES file; this is
  distributed with base R and implied by the `License:` field of the
  DESCRIPTION file.
- The NEWS file is not in a format that can be parsed by base R.
- The tests directory and testthat.R file imply testthat-style unit
  tests, but the actually tests imply RUnit. The net effect is that no
  tests are evaluated. The tests as written cover an inadequate amount
  of the code. Adopt a consistent testing framework (testthat is
  appropriate) and write sufficiently comprehensive tests (see, e.g.,
  the [covr][] package).
  
[covr]: https://cran.r-project.org/package=covr

**Comment by sbhattacharya3** [comment]
Thanks a lot for the review comments. I am presently working on the same, and would update the tool as soon as possible.

**Comment by mtmorgan** [comment]
Your package requires a version bump to trigger a build; did you intend to do that?

**Comment by sbhattacharya3** [comment]
Hello Martin,

I am working on some of the reviews suggested by you. I would be updating
the package and doing a version bump this week.

Thanks,
Surajit

**Comment by mtmorgan** [comment]
If your package is ready for final review please provide  a brief summary of how each issue has been addressed. The deadline for adding new packages in time for the next release is Friday.

**Comment by sbhattacharya3** [comment]
Hello Morgan,

Please find my comments inline in bold.

DESCRIPTION, NAMESPACE

OK
R

It is not appropriate for software packages to contain large data
objects. These could be isolated as a separate 'experiment data'
package
http://bioconductor.org/developers/package-guidelines/#package-types
However, the data seems to be an ad-hoc summary of Target-scan and
other data. These data objects are not sufficiently documented or
processed in a reproducible way to be included in
Bioconductor. I'm also concerned about re-distribution of data
without appropriate licensing and permissions. For these reasons the
data objects should be removed. They should be replaced by
instructions for the user to download the data from their original
source, and functions that take the downloaded data and transform it
to a format useful to this package.: **We have deleted all the .RData files related to the public databases like TargetScan, Pita, miRanda and ChipBase. The file size , although remains an issue. The purpose of the package is to identify targets for intragenic miRNAs  in fruit flies by statistical analysis of approximately 350 microarray experiments from Gene Expression Omnibus. The package right now can be used to not only query the targets but also visualize the results using network visualisation methods and geneontology using available R and Bioconductor packages. We can also submit it as a experiment package, if you think that would be the correct classification of these type of packages.**
e.g., MiR_ChipBase() but throughout -- follow the guidelines for
avoiding iteration, using pre-allocate and fill, and vectorization;
your current code is unacceptably
inefficient. http://bioconductor.org/developers/how-to/efficient-code/: **Updated and removed iteration where ever needed.** 
Whenever providing a default file path, provide it in a temporary
location, e.g., tempdir() or tempfile().: **checked and updated where needed.**
Create file paths using file.path() rather than paste().: **Checked and changes made.**
If a user provides a file path your code should fail if the path
already exists (stopifnot(file.exists(...))) or require that the
user explicitly allows the file to be over-written (e.g., with an
argument overwrite=FALSE).: Did the appropriate checks.
Validate all input parameters, e.g., MiR_ChipBase() should start
with stopifnot(is.character(m), length(m) == 1L, !is.na(m)) or
similar.**Did the appropriate checks.**
please adopt standard and consistent approaches to indentation,
e.g., format the code at Chipbase_database.r:80 in the same was as
at line 69. Consider using tools such as formatR to arrive at
consistent formatting.: **used formatR to format.**
Ensure that your package conforms to overall Bioconductor size (and
check time) constraints.
http://bioconductor.org/developers/package-guidelines/#correctness
vignettes

Please update the installation instructions to match those after
Bioconductor acceptance, i.e.

  source("https://bioconductor.org/biocLite.R")
  biocLite("IntramiRExploreR"): **Will do that once it gets accepted** 
miRtargets() line 44 has argument outpath, but this is (a)
undefined and (b) unused in the function. Remove it, and review
arguments in this and all function calls to ensure that they are (a)
defined and (b) used).: **Updated**

GetGOS_ALL() line 107 has argument path="C://", apparently
writing to the root directory. Do not do this, but instead use a
temporary location, for a directory use tempdir() or for a
temporary file tempfile(). Review all vignette and example code to
ensure that ALL file arguments or outputs are located in temporary
locations.: **Updated**

review the output of all vignette code, making sure that it is
visually meaningful; for instance the output of a[1:4,] is too wide
for the output medium.: **Updated and checked**

man

Use R conventions (e.g., character(1), data.frame) rather than
ad-hoc descriptions for parameter and return values (e.g., "String",
"Dataframe").: **updated the man folder with the changes.**
Other

It is not appropriate to include the GPL LICENCES file; this is
distributed with base R and implied by the License: field of the
DESCRIPTION file.: **Removed the license file. It was erroneously put there.**
The NEWS file is not in a format that can be parsed by base R.: News file has been added
The tests directory and testthat.R file imply testthat-style unit
tests, but the actually tests imply RUnit. The net effect is that no
tests are evaluated. The tests as written cover an inadequate amount
of the code. Adopt a consistent testing framework (testthat is
appropriate) and write sufficiently comprehensive tests (see, e.g.,
the ).: **test directory was updated, and comprehensive tests were added.**

Thanks,
Surajit
—

**Comment by mtmorgan** [comment]
It looks like your package has been revised but without a version bump. If you bump the version I will complete the review process promptly.

**Comment by sbhattacharya3** [comment]
Hi Martin,

I have done a version bump on the package. I have also answered all the questions and comments you had regarding the package inline.

Please let me know if you have any further questions and the package is now ready for your kind perusal.

Thanks again.

Surajit
