### ISSUE TITLE
TargetDecoy

### ISSUE THREAD

**Issue by ElkeDebrie** [Bioconductor/Contributions#2331]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/statOmics/TargetDecoy

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi @ElkeDebrie 

Sorry for the delay. Thank you for your submission.
Please see the review below. 

Best regards,
Marcel 

---

# TargetDecoy #2331

* Nicely formatted and cleanly written.
* Consider removing the shiny app component of the package and making that
a standalone package.

## DESCRIPTION

* Looks good.

## NAMESPACE

* Exported functions are minimal. Consider using more descriptive names for
your functions.

## vignettes

* No need to track the timing of your vignette, the build report will do that
for you. Also you can run `time R CMD build TargetDecoy`.
* Please don't jump the gun and advertise the package as installable from
Bioconductor.
* It would be good to have runnable examples of the plots rather than just
images.
* Consider separating the shiny code from the package to keep functionality
modular.
* Can the functions return a single plot as arranged by `grid.arrange` or
perhaps have one function return one plot?
* `Sys.time` sections are not needed and could be removed.

## R

* Your function should stick to the default value `log10 = TRUE` in the body
and test for deviations e.g., `stopifnot(is.logical(log10))` etc. rather
than testing if `missing` or `NULL`.
* Combine similar errors for `decoy` and `score`, e.g.,
`stop("Column(s) not found:", ...)` in `app.R`
* It's good that you have something like `.check_args`.
* Make sure your default value for `log10` is consistent throught your
functions `app.R` vs `evalTargetDecoys()`.

## tests

* Coverage looks good:

```r
> covr::package_coverage()
TargetDecoy Coverage: 57.41%
R/app.R: 15.95%
R/Scores.R: 97.92%
R/createPPlotObjects.R: 100.00%
R/evalTargetDecoys.R: 100.00%
R/plots.R: 100.00%
R/utils.R: 100.00%
```

**Comment by ElkeDebrie** [comment]
Hi @LiNk-NY

Thanks for the review and the feedback. I addressed your comments. The shiny app has been removed and can later be given as a separate package.

Best regards
Elke

**Comment by LiNk-NY** [comment]
Hi Elke, @ElkeDebrie 
Please respond to each point in the review. 
Thank you. 
Best,
Marcel

**Comment by ElkeDebrie** [comment]
Hi Marcel, @LiNk-NY 
Thanks for your reply. See attached the comments to each point.
[RespondReview.pdf](https://github.com/Bioconductor/Contributions/files/7375494/RespondReview.pdf)

**Comment by LiNk-NY** [comment]
Hi Elke, @ElkeDebrie 
Thank you for your prompt response. 
Please respond as an inline comment by clicking on the dots on the top right and
hitting "quote reply" and do not attach files next time.
Your package has been accepted. Thank you for your contribution. 
Best regards,
Marcel

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ElkeDebrie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TargetDecoy")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TargetDecoy

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
