### ISSUE TITLE
ggmanh

### ISSUE THREAD

**Issue by leejs-abv** [Bioconductor/Contributions#2338]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/leejs-abv/ggmanh

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please see initial review below. 


**inst**

- [ ] Please provide an `inst/scripts` directory that has a file that indicates
  how the data in `inst/extdata` was generated. It can be R code, sudo-code, or
  plain text but minimally should indicate the source of the data.


**vignette**

- [ ] (optional) we recommend using BiocStyle or at the very least an addition
  of a table of contents at the top of the vignette.

- [ ] There seems to be minimal to little interaction with existing Bioconductor
  classes for GWAS data. You attempt to show a linking to SeqArray but after
  loading the data from the package fail to use it in the vignette examples.
  Please adjust. 
  

**Rcode**

- [ ] Bioconductor prefers the creation of S4 classes rather than S3 classes.


- [ ] When working with Bioconductor objects and classes, genomic positions are
  commonly represented as GenomicRanges. it should be 

- [ ] _data.R_  This data does not appear to be included in the package? If this
  is the data file provided in extdata than please say that in the man page


Please respond to the above concerns. When ready please initiate a version bump to trigger a new build and request a re-review

**Comment by leejs-abv** [comment]
Hi, thank you for the detailed insight! I have added more information about the data in `inst/extdata` as well as provide more documentation of the usage of annotation leveraging SeqArray package. I have triggered a new build regarding these changes, and now working on other points.

**Comment by lshep** [comment]
> Hi, thank you for the detailed insight! I have added more information about the data in `inst/extdata` as well as provide more documentation of the usage of annotation leveraging SeqArray package. I have triggered a new build regarding these changes, and now working on other points.


Excellent just let me know when you are ready for a re-review

**Comment by leejs-abv** [comment]
Hi, I would like to submit the package for re-review. I have added extra support for GRanges object from GenomicRanges package. So long as the P.value column name from the meta data from the GRanges object is provided, the package will plot the manhattan plot, using the center of the range. 
I would also like to discuss about the creation of S4 class as opposed to S3 class for MPdata object. Currently the object serves as a tentative placeholder for plot data while plot output parameters are adjusted. I was thinking that S3 class will serve this purpose. I'd be happy to hear your opinion and make adjustments!

**Comment by lshep** [comment]
Please see further comments:

Use of S3 instead of S4 class is fine given explanation. 

**vignette**

- [ ] We recommend showing the table of content with `toc: true`

- [x] In future package development I highly recommend researching the common
  classes for Bioconductor and try to make your packages compatible with those
  data structure. There are many common class structure for gene expression
  data, chromosome position information, sequence data, etc. We normally insist
  on more overlap with the existing infrastructure.



**R code/man pages**

- [ ] Consider expanding on your package man page to point them to the relevant
  function or vignette for the package so they have a starting point.


- [ ] There is a lot of repeated code for filtering on a chromosome. It feels
  like the specialized functions should not exist and the argument should be
  moved to the main function where if a chromosome is specified it does the
  filtering and if it is not specified it does the full plot. Large repeated
  code chunks should always be avoided.

**Comment by leejs-abv** [comment]
Hi I changed the man page for my package to include more description and how to open the vignette. The main function `manhattan_chromosome` is now deprecated and a chromosome argument is added to the `manhattan_plot` function for that feature. I have also added `toc: true` to the vignette's yaml section. I added BiocStyle to my vignette, but it does not seem like it is being applied when I open the vignette on my machine. Is this normal?

**Comment by leejs-abv** [comment]
The package is ready for a re-review

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/leejs-abv.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggmanh")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggmanh

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
