### ISSUE TITLE
sparrow

### ISSUE THREAD

**Issue by lianos** [Bioconductor/Contributions#2342]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lianos/sparrow

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Hi Steve, it's been a long time!

Thanks for this new submission. You're apparently aware of the existence of the **BiocSet** package by @Kayla-Morrell, @mtmorgan, @kevinrue, and @llrs. From your vignette (which is very nice):

> NOTE: The GeneSetDb class was initially developed to address some peculiarities of storing, querying, and manipulating gene sets using the old-school GSEABase::GeneSetCollection class. It is not meant to replace the more recently developd BiocSet class, and we plan to support and migrate to that gene set container in the future. This section provides a quick overview of some of the functionality of gene set container.

Any reason why you're not just using that? I'm worried that getting a GeneSetDb-centric **sparrow** into Bioconductor will make a later migration to BiocSet much harder than if the package was migrated now, before people start using it and depending on it.

Small problem with section numbers in the vignette:

![Screenshot from 2021-10-05 18-14-30](https://user-images.githubusercontent.com/8810451/136127365-cb4893dc-a9d8-4c04-a0e3-d07dc490baab.png)

Thanks,
H.

**Comment by llrs** [comment]
Many thanks for mentioning me but I'm not an author of the package just a contributor on the discussions. 

The [Bioconductor common Methods and Classes page](http://bioconductor.org/developers/how-to/commonMethodsAndClasses/) mentions GSEABase classes for gene set, if this is discouraged maybe the website might need to be updated. 

Last there is also my package [BaseSet](https://cran.r-project.org/package=BaseSet) on CRAN with similar functionalities. It already allows to load data from GSEABase GeneSetCollection to its own class.

**Comment by lianos** [comment]
Hi Herve!

Thanks for the quick feedback, and yes: has been a very long time!

> Any reason why you're not just using that [a BiocSet]? I'm worried that getting a GeneSetDb-centric sparrow into Bioconductor will make a later migration to BiocSet much harder than if the package was migrated now, before people start using it and depending on it.

Yes, I was worried that you would be worried about that :-)

The reason I'm not using that at the moment is that it would take quite a while to refactor and test. There has been a lot of functionality baked into the GeneSetDb class over the years, and I just haven't had the time to check and port over to BiocSet. I do plan on taking a shot at porting it over in the future.

Why am I submitting now? It has long been on my todo list, but also there are updates in another package a colleague of mine has in Biocondcutor (gCrisprTools) that has incoming updates for next release that rely on functionality in sparrow, and was hoping to support those developments there by getting sparrow published now.

I can understand why this gives you pause, though. The good news, perhaps, is that while the GeneSetDb class plays an important role *within* the package, its use is quite ... uhm ... not so important "outside" of the package. I suspect users would interact very little (if at all) with the GeneSetDb, as the majority of the use cases I've found working with sparrow simply return data.frames of gene sets after analyses.

For instance, if you run the main analysis function `seas()` by giving it a `GeneSetCollection`'s worth of gene sets, you can very likely never even have to know what a GeneSetDb is.

Would you be OK if, for now, I simply add the ability to provide a gene set collection as a `BiocSet` as inputs to the main user-facing functions (`seas()` being the primary one, but also probably `scoreSingleSamples()`) and iterate on migrating the internals of the package to BiocSet in time?

It's not often that users will extract the internal GeneSetDb class, but I can also provide the ability to have it returned as a BiocSet as well.

Would that be sufficient?

Also, thank you for pointing out the header-level issue in the vignette, I'll fix each section to use an `h1` header element and readjust from there.

**Comment by kevinrue** [comment]
Thanks for mentioning me as well @hpages 

I also haven't directly contributed to BiocSet, but I have very much appreciated the discussions that ensued from the parallel efforts on [BiocSet](https://bioconductor.org/packages/release/bioc/html/BiocSet.html), [BaseSet](https://cran.r-project.org/web/packages/BaseSet/index.html), and my own [unisets](https://github.com/kevinrue/unisets).
(I haven't pushed `unisets` to any other repository than GitHub, to avoid further confusion, and leave full visibility to BiocSet moving forward).

To be honest, I would point out that even since `BiocSet` was released, I haven't witnessed wide community adoption of the package (yet).
From a brief look at https://bioconductor.org/packages/release/bioc/html/BiocSet.html I see today 1 package that Depends on BiocSet and 1 package that Suggests it.

Obviously, Rome wasn't built in a day, and the rich-gets-richer way of software adoption means that `BiocSet` probably won't be appealing to many developers until more developers buy into the new infrastructure and create a critical mass of users, developers and documentation driving others to it.

While `sparrow` could be one of those early adopters, I wouldn't blame anyone for waiting to see how others get along with `BiocSet` before investing their own time into migrating their own package. Some deity somewhere probably knows what the future holds for `BiocSet` and whether some other infrastructure might come along and motivate yet another migration.

In many ways gene set analysis and infrastructure unfortunately very much still feels like a wild west of data structures, much in need of homoegeneisation between packages (hence the efforts invested in BiocSet, BaseSet and unisets). However, old favourites (e.g. clusterProfiler) are still implicitly supporting certain older data structures, and the amount of work involved in migrating those packages from one infrastructure to another are considerable factors, in my view, holding back the adoption of new data structures for gene sets.

I'm not the package reviewer here, but that part of @lianos 's latest message 

>  I suspect users would interact very little (if at all) with the GeneSetDb, as the majority of the use cases I've found working with sparrow simply return data.frames of gene sets after analyses.

makes me feel that this package might not hurt any user by using the `GeneSetDb` internally, since it accepts a major Bioconductor data structure as input (`GeneSetCollection`) and produce `data.frame` as ouput.

Having said that, of course, using standard Bioconductor data structures internally is always encouraged for readability and contributions/maintenance by other Bioconductor developers. Packages that somehow get accepted into Bioconductor while not using standard containers are more challenging (and lonely) to maintain and more likely to fall into deprecation over time.

**Comment by lianos** [comment]
Thanks for your thoughtful commentary, @kevinrue.

Looking a bit more closely at BiocSet, there are areas of clear overlap with the GeneSetDb class I implemented, as well as functionality that is specific to my GeneSetDb class that sparrow relies on internally that I don't yet see has a clear analog for in BiocSet (yet :-).

Hopefully the extra functionality I rely on is useful to the design/implementation of BiocSet, and working on an internal conversion of GeneSetDb to BiocSet can help make that more clear. If the functionality is also useful to other end-users and GSEA package developers, as well, I am happy to help discuss/contribute changes to BiocSet to make that happen.

My hope is that sparrow can be approved with its internal GeneSetDb now, and we can gradually work towards the GeneSetDb -> BiocSet transition in time. 🤞

As it is, I've already [added GeneSetDb <-> BiocSet conversion functions](https://github.com/lianos/sparrow/commit/49f3f5503fe4436fde94871e27e8d483eb6a728c) that allow users to send in BiocSet objects into sparrow functions and convert a GeneSetDb object back to a BiocSet in the event that the user wants to pull this object out of the classes in sparrow.

Once those changes work their way through my github actions to ensure all package level tests pass, I can also push back to the bioconductor git repo (or should I wait for a more formal review of the codebase as it currently is?)

**Comment by lianos** [comment]
Just to keep everyone up to speed, I've run through the package and made more changes to promote the use of a `BiocSet` where `GeneSetDb` has been used for all the main user facing functions of this package.

This package also provides convenience functions that return `GeneSetDb` objects from different sources, like:

* `getMSigGeneSetDb()` for a wrapper to msigdbr to get the MSigDb collections;
* `getKeggGeneSetDb()` to get KEGG annotations, etc.

I've added sibling functions to all these methods to return a `BiocSet` of the same, so they can easily be used in the analyses provided by sparrow (ie. `getMSigCollection()`, `getKeggCollection()`, etc)

I also have changed documentation and the vignette to suggest a `BiocSet` first use of the package to end users, although the vignette itself is still using a GeneSetDb.

I can/will continue to make these modifications over time, but just want to make it abundantly clear that I'm putting in a good-faith effort to assuage any fears of not being willing to do a full `BiocSet` migration when it can be done down the road.

I can not completely replace the internals of sparrow to use `BiocSet` because there is (well tested) functionality and speed found in the `GeneSetDb` class and how the functions in sparrow interact with it.

Again, I just want to re-iterate that as the package now stands, users can use any/all functionality it provides by providing a `BiocSet`'s worth of gene sets to the sparrow functions, and the use of a `GeneSetDb` is an implementation detail that is internal to the package. This makes it possible to carefully migrate the internals without disrupting the use of sparrow by the community since the interface won't change (and that interface now supports a `BiocSet`).

Thanks for your consideration.

**Comment by kevinrue** [comment]
Again, I'm not the reviewer here, but as a fellow package developer, I cannot stress how much I appreciate hearing updates from someone taking `BiocSet` for a test run. Your willingness to do this is providing evidence that might convince/comfort/motivate others (including me) that `BiocSet` is a viable infrastructure ready to be re-used across the Bioconductor project, not just a concept package that just looks pretty.

From the sounds of it, you are also providing the feedback that `BiocSet` developers/maintainers have been needing to further consider functionality that it might miss to cater for the needs of developers holding back still.

Thanks for your work and hard effort!

**Comment by lianos** [comment]
Thanks again for the thoughtful comments, @kevinrue !

@hpages according to the build report, the linux buildbot "nebbiolo2" seems to be taking ~5x longer to run the code in the package than the other two, and has timed out on the R CMD check run, which has now slapped a warning label on the submission.

I'll wait to make some meatier changes primarily to the documentation to push another commit to trigger the re-build. If this "warning" label is holding up the package review, though, I can try to tickle the build bot again to see if I get some better luck on the next build.

**Comment by hpages** [comment]
Thanks @llrs and @kevinrue for chiming in.

@kevinrue Agree with you on the importance of exposing BiocSet thru more real world use cases and gathering feedback that will ultimately allow the container to improve and convince. Steve's work will help tremendously achieve that goal.

@lianos All is fine. I didn't realize that GeneSetDb was mostly used behind the scene and that migrating the internals of the package to use BiocSet instead of GeneSetDb wouldn't turn out to be so disruptive after all. Thanks for adding GeneSetDb <-> BiocSet conversion functions. They will definitely help interoperability and pave the way to a future migration to BiocSet. Your other changes/additions sound good too. The vignette is _very_ nice.

Best,
H.

**Comment by lianos** [comment]
@hpages that's great news, thanks for your feedback and taking the time to review the package!

Thank you also to @llrs and @kevinrue for sharing your thoughts, as well.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lianos.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sparrow")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sparrow

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
