### ISSUE TITLE
benchdamic

### ISSUE THREAD

**Issue by mcalgaro93** [Bioconductor/Contributions#2344]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mcalgaro93/benchdamic

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Package is in good shape.  I would propose dealing with some of the output of BiocCheck::BiocCheck() [please run it]
```
                                                                 
 [2] "Update R version dependency from 4.0.0 to 4.1.0."                                                                                                                                  
 [3] "Use accessors; don't access S4 class slots via '@' in examples/vignettes."                                                                                                         
 [4] "Avoid 'suppressWarnings'/'*Messages' if possible (found 15 times)"                                                                                                                 
 [5] "Recommended function length <= 50 lines."                                                                                                                                          
 [6] "Consider adding runnable examples to the following man pages which document exported objects:"                                                                                     
 [7] "Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements."        
```
and then I will accept it.

**Comment by mcalgaro93** [comment]
Dear Vince,
thank you for the feedback. Here there are some informations abount my last submission:
- I managed to solve entirely the points [2], [3], [6], and [7]; 
- regarding the point [4], I've removed a `suppressMessages()` and a `suppressWarnings()` from the function `createTIEC()`. In all the other cases those `suppressMessages()` are inside `if` clauses: if the user decide to set `verbose = TRUE`, those `suppressMessages()` will be completely ignored. I had to use them because for some functions, such as `DESeq2::sizeFactors()`, it is not possible to suppress the messages using internal parameters;
- Regarding the point [5], I was not able to split further the long functions into shorter ones.

All the informations are available now into the NEWS file too.

**Comment by vjcitn** [comment]
Glad it is building cleanly.  Material like
```
#    user  system elapsed 
##   0.456   0.018   0.476 
##    user  system elapsed 
##   0.019   0.001   0.021 
##    user  system elapsed 
##   0.050   0.001   0.051 
##    user  system elapsed 
##   0.020   0.001   0.022 
##    user  system elapsed 
##   0.062   0.008   0.070 
##    user  system elapsed 
##   0.021   0.000   0.021 
##    user  system elapsed 
##   0.038   0.001   0.039 
##    user  system elapsed 
##   0.019   0.001   0.020 
## [1] "Iteration 2 Newton's update, log-likelihood-5685.43132815568"
## [1] "Iteration 3 Newton's u
```
should be suppressed in the vignette, I think.  Maybe you can set verbose=FALSE.
Also consider reporting fewer decimal places throughout.

The following looks like it might be a common way of comparing methods, so perhaps
you should encapsulate it in a function with intuitive parameters.
```
RMSE_ZPD_16S <- plyr::ldply(GOF_stool_16S,
  .fun = function(df) cbind("RMSE" = RMSE(df[, "ZPD"])),
  .id = "Model"
)
```
This part of vignette
```
GOF_stool_16S <- fitModels(
  counts = as(otu_table(ps_stool_16S), "matrix"),
  models = c("NB", "ZINB", "DM", "ZIG", "HURDLE"),
  scale_ZIG = c("median", "default"),
  scale_HURDLE = c("median", "default"),
  verbose = TRUE
)
```
also seems clumsy.  Could fitModels work directly on the class of `ps_stool_16S`

It would be good to narrate the display after
```
MDs and ZPDs are also available in this other output layout:
```
and in fact I don't know that ZPD is defined in the vignette.  Please give definitions for acronyms.

Otherwise this seems ready to go.  Let me know how you want to proceed.

**Comment by mcalgaro93** [comment]
Thank you for all these suggestions. I'll work on them as soon as possible.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mcalgaro93.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("benchdamic")`. The package 'landing page' will be created at

https://bioconductor.org/packages/benchdamic

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
