### ISSUE TITLE
miaSim

### ISSUE THREAD

**Issue by YagmurSimsekk** [Bioconductor/Contributions#2346]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/microbiome/miaSim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Hi,

Seems like you've decided to make all your functions generic functions with a single method. However I don't see a good reason for doing this (they all dispatch on their first argument which is expected to be a single number). More generally speaking, systematically defining generic functions when regular functions can be used is not good practice. Please make `powerlawA()`, `randomA()`, `simulateGLV()`, `simulateHubbell()`, `simulateSOI()`, and `tDyn()` regular functions.

Also, this is not how one is expected to install the development version of a Bioconductor package (from section 2.0.2 of your vignette):
```
remotes::install_github("microbiome/miaSim")
```
Bioconductor is an ecosystem with tight interaction between packages and installing directly from GitHub will not play well with this. To install the development version of a Bioconductor package, one should first install the development version of Bioconductor with:
```
BiocManager::install(version="devel")
```
Note that this command itself might require to first update R to R-devel.

Then, one installs the development version of any Bioconductor package with `BiocManager::install()`, like for the release version.

Please remove section 2.0.2 from your vignette.

Other than that, the package is ready for acceptance.

Thanks,
H.

**Comment by YagmurSimsekk** [comment]
Hi @hpages ,

Thank you for your review! I have considered your points and changed the files. I could push them into main repository, but it didn't work for Bioconductor upstream repository. I kept getting this error even though my SSH keys and emails are matching and I have R W access to my package.

remote: FATAL: W refs/heads/main packages/miaSim YagmurSimsekk DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/miaSim.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/miaSim.git'  

Clearly, I must be missing something.

**Comment by hpages** [comment]
I don't know what's going on and I don't know how to help with this, sorry. But maybe @nturaga, @lshep, or @vjcitn can help? Thanks

**Comment by lshep** [comment]
It is the issue with the default naming branch. See Number 5 Notes on the http://bioconductor.org/developers/how-to/git/new-package-workflow/ page  specifically doing `git push upstream main:master`

**Comment by hpages** [comment]
Thanks for the changes @YagmurSimsekk . Note that you will need to re-roxygenize to refresh the man pages (they still contain `\docType{methods}` and aliases for the methods that are gone e.g. `\alias{simulateGLV,numeric-method}`). Please do this at your earliest convenience. I'm labeling the package as accepted.

Cheers,
H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YagmurSimsekk.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("miaSim")`. The package 'landing page' will be created at

https://bioconductor.org/packages/miaSim

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
