### ISSUE TITLE
scDDboost

### ISSUE THREAD

**Issue by xiuyuma** [Bioconductor/Contributions#2349]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wiscstatman/scDDboost

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package scDDboost Review

The package is in good shape but there are some issues need to be fixed.

## General package development

- [ ] Please include Bioconductor installation instructions using BiocManager.

## The DESCRIPTION file

- [ ] `Depends` field is empty
- [ ] 'library' or 'require' call not declared from: ‘ggplot2’
- [ ] Consider adding these automatically suggested
      biocViews: DifferentialExpression, Bayesian
- [ ] Consider adding `BugReports` and `URL` field

## The NAMESPACE file

- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
- [ ] Namespace with empty importFrom: ‘stats’
- [ ] Consider adding importFrom("methods", "is")

## The NEWS file

- [ ] Consider adding a NEWS file, so your package news
      will be included in Bioconductor release announcements.

## The CITATION file

- [ ] Consider to add Citation file.

## Documentation

- [ ] Vignette uses `BiocStyle` package for formatting.
- [ ] \newpage and \newline will not work for html output.
- [ ] Vignette has an *Installation* section.
Please include Bioconductor installation instructions using BiocManager.
- [ ] Vignette should have a table of contents.
- [ ] 'sessionInfo' not found in vignette(s)
- [ ] html file should be removed from `vignettes/` directory
- [ ] Vignette is not finished yet.

## Unit tests

- [ ] Consider adding unit tests. We strongly encourage
      them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] Please clean up unused code.
- [ ] Avoid `sapply()`; use `vapply()` at R/PDD.R (line 37, column 17)
- [ ] `<-` instead of `=`.
- [ ] Avoid the use of 'paste' in `message`, `warning`, `stop` in R/PDD.R
- [ ] Avoid 1:...; use `seq_len()` or `seq_along()` in files:
        * g_cl.R (line 25, column 21)
        * g_cl.R (line 27, column 14)
        * listsize.R (line 19, column 23)
        * lsz.R (line 23, column 23)
        * MDD.R (line 65, column 15)
        * PDD_random.R (line 26, column 11)
        * PDD_random.R (line 28, column 11)
        * PDD_random.R (line 29, column 11)
        * PDD_random.R (line 30, column 14)
        * PDD.R (line 37, column 24)
        * PDD.R (line 47, column 11)
        * PDD.R (line 125, column 18)
        * PDD.R (line 169, column 27)
        * PDD.R (line 173, column 18)
        * rwMLE.R (line 15, column 14)
- [ ] Function arguments should be tested for validity.

## C and Fortran code

- [ ] `Makevars` and `Makefile` is missing, no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’.  It is good practice to register native routines and to disable symbol
  search. See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.

**Comment by lshep** [comment]
@xiuyuma may we expect updates soon?  We like to see progress and responses to review within a 3-4 week time frame?

**Comment by xiuyuma** [comment]
Hi,

Sorry for the delay, I will update later this week, Thank you.

Best Regards,
Xiuyu Ma
________________________________

**Comment by xiuyuma** [comment]
Could you please reopen the issue, I have addressed those issues previously raised, sorry for the delay and thanks

**Comment by xiuyuma** [comment]
Could you please reopen the issue, I have addressed those issues previously raised, sorry for the delay and thanks
@lshep

**Comment by xiuyuma** [comment]
Hi @lshep, I pushed the new package and it passed for the windows server, but has problems with the other two, where they mainly complain that packages declared at import field from the DESCRIPTION file are not available. Not sure how I should proceed. Thanks 

updated, tried to resubmit and now it yields no error or warnings, thanks!

**Comment by jianhong** [comment]
# Package 'scDDboost' Review
The package passed check and build. It is in pretty good shape. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] R version is not clear in DESCRIPTION.
- [ ] It is recommended to use ‘given’ instead of ‘middle’ for `person`.

## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 2 import(RcppEigen)
	* in line 3 import(BiocParallel)
	* in line 4 import(EBSeq)
	* in line 5 import(SingleCellExperiment)
	* in line 6 import(cluster)
	* in line 7 import(mclust)
	* in line 8 import(Oscope)
	* in line 9 import(ellipsis)
	* in line 10 import(vctrs)
- [ ] Function names use `camelCase` or `snake_case` for `PDD` and `listsize`. Function name `lsz` is not readable.
	* in line 15 export(PDD,cal_D,detK,lsz,listsize,pat,extractInfo)
- [ ] Package in Depends field not imported from: ‘ggplot2’
These packages need to be imported from (in the NAMESPACE file)
for when this namespace is loaded but not attached.

## The NEWS file
- [ ] The news file is not updated. Please check the format of your news file, see ref https://contributions.bioconductor.org/news.html

## R code
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/g_cl.R:
		+ at line 24 found '    bp <- BiocParallel::MulticoreParam(ncores)'
	* In file R/PDD.R:
		+ at line 143 found '        bp <- BiocParallel::MulticoreParam(ncores)'
- [ ] Export `BPPARAM` as parameter instead of define the parameter in function like `bp <- BiocParallel::MulticoreParam(ncores)`.
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/detK.R:
		+ at line 20 found '     for(i in 2:9){'
	* In file R/g_cl.R:
		+ at line 27 found '    for(i in seq_len(length(clus))){'
	* In file R/MDD.R:
		+ at line 65 found '    for( j in seq_len(nrow(pat)) )'
	* In file R/PDD_random.R:
		+ at line 31 found '    for(i in sequence){'
	* In file R/PDD.R:
		+ at line 105 found '        for(i in seq_len(K)){'
		+ at line 148 found '        for(i in seq_len(nrandom)){'
	* In file R/rwMLE.R:
		+ at line 15 found '    for(i in seq_len(n)){'
- [ ] Remove unused code.
	* In file R/detK.R:
		+ at line 24 found '         #inter[i - 1] = sum(D[x,x]) / (i * (i - 1))'
		+ at line 30 found '    #mins = min(s)'
		+ at line 31 found '    #ss = s/mins - 1'
	* In file R/genRClus.R:
		+ at line 13 found '    #dst.star <- as.dist(bar)'
	* In file R/MDD.R:
		+ at line 20 found '    ##res <- sum(lgamma(tt+alpha_b)) + sum(lgamma(nn)) - sum(lgamma(tt+nn))'
		+ at line 42 found '    #nn <- table(pp)  ## counts block sizes'
	* In file R/PDD_random.R:
		+ at line 41 found '    #modified_p <- sapply(1:np,function(i) sum(post[which(ref[[K]][,i] == 1)]))'
		+ at line 48 found '    #    else{'
		+ at line 49 found '    #        message("small number of clusters, using exact EBSeq")'
		+ at line 50 found '    #       rowmeans = apply(data_counts,1,mean)'
		+ at line 51 found '    #        tmp = which(rowmeans > 0)'
		+ at line 52 found '    #        data_tmp = data[tmp,]'
		+ at line 53 found '    #        res = EBTest(Data = data_tmp, Conditions = cstar, sizeFactors = sz, maxround = 2)'
		+ at line 54 found '    #        tmpDE = rep(0, nrow(data))'
		+ at line 55 found '    #        tmpDE[tmp] = res$PPDE'
		+ at line 56 found '    #        DE = cbind(1 - tmpDE, tmpDE)'
		+ at line 57 found '    #    }'
	* In file R/PDD.R:
		+ at line 31 found '    #data(ref.RData)'
- [ ] Functional programming: code repetition.
	* repetition in `PDD` and `PDD_random`
		+ in PDD
			- line 56:        if (K >= 2) {
			- line 57:            res <- EBS(data, ccl, gcl, sz, iter, hp, Posp, stp1, 
			- line 58:                stp2)
			- line 59:            DE <- res$DEpattern
			- line 60:        }
			- line 68:        for (i in seq_len(K)) {
			- line 69:            cur <- which(ccl == i)
			- line 70:            z1[i] <- length(which(cur <= n1))
			- line 71:            z2[i] <- length(which(cur > n1))
			- line 72:        }
			- line 73:        alpha1 <- rep(1, K)
			- line 74:        alpha2 <- rep(1, K)
			- line 75:        post <- MDD(z1, z2, Posp, alpha1, alpha2)
			- line 76:        np <- nrow(Posp)
		+ in PDD_random
			- line 9:    for (i in sequence) {
			- line 10:        cur <- which(cstar == i)
			- line 11:        z1[i] <- length(which(cur <= n1))
			- line 12:        z2[i] <- length(which(cur > n1))
			- line 13:    }
			- line 14:    alpha1 <- rep(1, K)
			- line 15:    alpha2 <- rep(1, K)
			- line 16:    post <- MDD(z1, z2, Posp, alpha1, alpha2)
			- line 17:    np <- nrow(Posp)
			- line 19:    if (K >= 2) {
			- line 20:        res <- EBS(data, cstar, gcl, sz, iter, hp, Posp, stp1, 
			- line 21:            stp2)
			- line 22:        DE <- res$DEpattern
			- line 23:    }

## C/CPP code
- [ ] File ‘scDDboost/libs/scDDboost.so’:
     Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’
   
   It is good practice to register native routines and to disable symbol
   search.

## Documentation

- [ ] Use `<-` instead of `=` in vignettes.
- [ ] Please double check your vignettes format. Only `sessionInfo` will be shown in table of contents.

**Comment by xiuyuma** [comment]
Hi Jianhong,

@jianhong. Thanks for your suggestions. I have changed the codes to accommodate most of them, except the cpp code,
May I ask if you would elaborate more on how to "register native routines and to disable symbol
search"? Appreciate your help.

**Comment by jianhong** [comment]
@xiuyuma The simple way is use roxygen to create one. See https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html for Rcpp part.

**Comment by xiuyuma** [comment]
> @xiuyuma The simple way is use roxygen to create one. See https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html for Rcpp part.

Thanks @jianhong , have pushed the latest version.

**Comment by jianhong** [comment]
# Package 'scDDboost' Review
The package passed check and build. It is almost there.

## The DESCRIPTION file
- [ ] Important: R version should be no less than 4.2

## The NAMESPACE file
- [ ] NOTE: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 2 import(RcppEigen)
	* in line 3 import(BiocParallel)
	* in line 4 import(SingleCellExperiment)
	* in line 5 import(ellipsis)
	* in line 6 import(vctrs)

- [ ] Important: Package in Depends field not imported from: ‘ggplot2’
These packages need to be imported from (in the NAMESPACE file)
for when this namespace is loaded but not attached.

## R code
- [ ] Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
	* In file R/pdd.R:
		+ at line 156 found '    tmp_z1<-table(ccl[1:n1])'

- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 1 times)
    suppressWarnings() in R/rwMle.R (line 18, column 13)
  
## Documentation
- [ ] Important: Please double check your vignettes format. Only sessionInfo will be shown in table of contents.

- [ ] NOTE: use '<-' instead of  '=' for assignment in sample codes in Rd files.

**Comment by xiuyuma** [comment]
Hi @jianhong,

Thanks for your quick response. I have addressed those issues

The DESCRIPTION file
Important: R version should be no less than 4.2

Fixed, now it requires R version >=4.2

The NAMESPACE file
NOTE: Selective imports using importFrom instead of import all with import.
in line 2 import(RcppEigen)
in line 3 import(BiocParallel)
in line 4 import(SingleCellExperiment)
in line 5 import(ellipsis)
in line 6 import(vctrs)

Fixed, the only import used is for RcppEigen since it basically gives a header file for c

Important: Package in Depends field not imported from: ‘ggplot2’
These packages need to be imported from (in the NAMESPACE file)
for when this namespace is loaded but not attached.

Fixed, import functions used from ggplot2

R code
Important: 1:n is not suggested in source code. Use seq_along or seq.int instead.
In file R/pdd.R:
at line 156 found ' tmp_z1<-table(ccl[1:n1])'

Fixed, used seq_len and seq.int instead

NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 1 times)
suppressWarnings() in R/rwMle.R (line 18, column 13)

Fixed, removed the suppressWarnings function

Documentation
Important: Please double check your vignettes format. Only sessionInfo will be shown in table of contents.

Fixed, now table of contents presents other sections

NOTE: use '<-' instead of '=' for assignment in sample codes in Rd files.The DESCRIPTION file

Fixed, examples in Rd are using '<-' instead of '='

**Comment by jianhong** [comment]
# Package 'scDDboost' Review
 It is almost there.
 
## Documentation

- [ ] Important: Please double check your vignettes format. Only sessionInfo will be shown in table of contents. I think you may want to add a blank space between `#` and the session title.

**Comment by xiuyuma** [comment]
@jianhong 
Hi Jianhong,

Thanks, I have added a blank space between the section title and # .

**Comment by jianhong** [comment]
> @jianhong Hi Jianhong,
> 
> Thanks, I have added a blank space between the section title and # .

Congratulations! Thank you for your contribution in Bioconductor!

**Comment by xiuyuma** [comment]
@jianhong 
Thanks for your review and advice

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xiuyuma.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scDDboost")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scDDboost

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
