### ISSUE TITLE
nullrangesData

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/Contributions#2352]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nullranges/nullrangesData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mikelove** [comment]
AdditionalPackage: https://github.com/nullranges/nullranges

**Comment by lshep** [comment]
@mikelove  hey sorry I was away on vacation last week the SPB auto messages stopped working while I was gone.  Before we moderation the issues can you make sure to update the descriptions to be  x.99.z format.  Bioconductor assumes the y=99 and won't process otherwise.

**Comment by lshep** [comment]
just comment back here when it is corrected and I will proceed

**Comment by mikelove** [comment]
Thanks for your time @lshep. 

Ok got it, I just pushed a bump to *nullrangesData* to be 0.99.1.

Just a note: the data package and *nullranges* both depend on Ehub submissions, I just pinged the email thread. I'll quickly add back in all the examples/eval=TRUE the vignette chunks once the experiment data is online.

**Comment by lshep** [comment]
@mikelove  that's I'll be looking at adding data to the hub later today.  Don't forget to also change the version number in nullranges as well.

**Comment by mikelove** [comment]
Thanks! 

Duh, I forgot _nullranges_ 🤦‍♂️ Now both are 0.99.1.

**Comment by mikelove** [comment]
Ok, I've now updated *nullranges* to use the new Ehub packages, should be good to start SPB checks here.

**Comment by lshep** [comment]
The additional package build report will post shortly

**Comment by lshep** [comment]
Looks good.  
Minor comments for nullranges: 

- [ ] Is man-roxygen directory needed?

**vignette**

- [ ] I would reconsider using a generic name like `intro.Rmd` depending on
  package load order a user would have to specify the name of the package to
  pull up the correct vignette. On naive attempt it pulls up biovizBase instead

```
> vignette("intro")
Warning message:
vignette 'intro' found more than once,
using the one found in '/home/shepherd/R-Libraries/4.1-Bioc3.14/biovizBase/doc' 

```

Consider using `nullranges.Rmd`?

- [ ] Perhaps in the vignette show the command to list the vignettes for the
  package since there are multiple. `vignette(package="nullranges")`


Let me know your thoughts on these points, else looks good to accept.

**Comment by mikelove** [comment]
@lshep thanks for your help and time in reviewing. Agree with all your points. I've removed `man-roxygen`, renamed `intro.Rmd` to `nullranges.Rmd`, and I added an initial un-evaluated chunk to explain how to find those vignettes:

https://github.com/nullranges/nullranges/blob/main/vignettes/nullranges.Rmd#L19-L24

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mikelove.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("nullrangesData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/nullrangesData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mikelove.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("nullranges")`. The package 'landing page' will be created at

https://bioconductor.org/packages/nullranges

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
