### ISSUE TITLE
GeoMxWorkflows

### ISSUE THREAD

**Issue by JasonWReeves** [Bioconductor/Contributions#2357]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nanostring-Biostats/GeoMxWorkflows

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Glad this has gotten out of error state.  I am surprised that the base class is ExpressionSet.  Did
you consider SummarizedExperiment?

Building the vignette by hand results in
```
> warnings()
Warning messages:
1: In readNanoStringGeoMxSet(dccFiles = DCCFiles, pkcFiles = PKCFiles,  ... :
  The following DCC files had no counts: DSP-1001250007864-D-C10.dcc, These will be excluded from the GeoMxSet object.
2: Removed 6 rows containing missing values (geom_bar).
3: Removed 6 rows containing missing values (geom_bar).
4: Removed 6 rows containing missing values (geom_bar).
5: Removed 6 rows containing missing values (geom_bar).
6: Removed 6 rows containing missing values (geom_bar).
7: Removed 3 rows containing missing values (geom_vline).
8: Duplicated aesthetics after name standardisation: size
9: ggrepel: 6 unlabeled data points (too many overlaps). Consider increasing max.overlaps
10: ggrepel: 6 unlabeled data points (too many overlaps). Consider increasing max.overlaps
11: Duplicated aesthetics after name standardisation: size
```
Acceptable?

Vignette looks good but takes a long time to compile.  It also has lots of very complex code
```
results2 <- c()
for(region in c("glomerulus", "tubule")) {
    ind <- pData(target_demoData)$region == region
    mixedOutmc <-
        mixedModelDE(target_demoData[, ind],
                     elt = "log_q",
                     modelFormula = ~ testClass + (1 | slide),
                     groupVar = "testClass",
                     nCores = parallel::detectCores(),
                     multiCore = FALSE)
    
    # format results as data.frame
    r_test <- do.call(rbind, mixedOutmc["lsmeans", ])
    tests <- rownames(r_test)
    r_test <- as.data.frame(r_test)
    r_test$Contrast <- tests
    
    # use lapply in case you have multiple levels of your test factor to
    # correctly associate gene name with it's row in the results table
    r_test$Gene <- 
        unlist(lapply(colnames(mixedOutmc),
                      rep, nrow(mixedOutmc["lsmeans", ][[1]])))
    r_test$Subset <- region
    r_test$FDR <- p.adjust(r_test$`Pr(>|t|)`, method = "fdr")
    r_test <- r_test[, c("Gene", "Subset", "Contrast", "Estimate", 
                         "Pr(>|t|)", "FDR")]
    results2 <- rbind(results2, r_test)
}
```
It is rarely appropriate to initialize an object with `c()`.  This tabulation process
should be encapsulated for the user.  The columns of r_test seem a fairly standard
set of quantities to report.  Since there is no "R" folder in this package, there is 
no place to place methods that would be repeatedly used.  Perhaps you should
add an R folder and set up functions corresponding to reusable 'workflows' for
your assay.

**Comment by JasonWReeves** [comment]
Hi @vjcitn - For GeoMxTools and the inherited NCTools, we have a plan for future work to migrate over to SummarizedExperiment as the platform for those two packages. We want to make sure we thoroughly replace when migrating which couldn't be achieved during this release.

I'll work to see how many of those errors in the manual vignette build can be mitigated currently over the next day or two as well as changing the initialization for the DE code chunks as well.

Regarding the time-length we did know that this would take longer to knit - especially the mixed-effect modeling chunks. Those are pretty critical component to explain about the assay and analysis. That's why we broke this vignette out and are submitting as a workflow package instead of as part of the original software package - we didn't want time-out errors to cause problems and wanted to showcase a full analysis workflow. One related question I'd like to confirm though - are the vignettes in the vignettes folder built automatically for bioconductor or should I run vignette() and upload the package with the resulting files in it?

I was unclear if workflow packages could contain separate R/ folders - it mentioned on the website that it was preferable to include any extra hard-coding inline and minimize the external R files in the workflow package if at all possible https://www.bioconductor.org/developers/how-to/workflows/. We do plan on ingesting some of these functions into GeomxTools in future releases to the software package, so some of this will simplify in future updates as well.

**Comment by vjcitn** [comment]
Thanks this is all very reasonable.  I will get back to you.  forget my suggestion about R ... I think we need
to reevaluate our prescriptions but for now this is fine.

**Comment by vjcitn** [comment]
Let me know when you have come to closure on vignette modifications.

**Comment by JasonWReeves** [comment]
@vjcitn I was able to resolve most of the issues noted above.

The warning:
```8: Duplicated aesthetics after name standardisation: size```
appears to be from ggrepel, and I cannot seem to resolve this one directly and suspect it may be a bug in a recent version of their code. This happens even when calling just ggrepel and never using size as an aesthetic. The other warnings should be resolved though.

I've also removed the r_test initialization with ```c()``` and added logic for binding the tests together instead. Let me know if there's any other adjustments that would help the package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/JasonWReeves.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GeoMxWorkflows")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeoMxWorkflows

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
