### ISSUE TITLE
MSstatsLiP

### ISSUE THREAD

**Issue by devonjkohler** [Bioconductor/Contributions#2359]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsLiP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Devon, @devonjkohler 

Thank you for your submission. Please see the review below.

Best regards,
Marcel

---

# MSstatsLiP #2359

## DESCRIPTION

* Can you make a comment in the `Description` field about how this package
relates to `MSstatsTMTPTM`? Does this package replace it? Does the
functionality overlap?

## NAMESPACE

* Looks good.

## vignettes

* Consider modifying the code chunk options when loading the required packages
in the vignette to reduce the amount of noise, e.g.,
(`{r,include=TRUE,results="hide",message=FALSE,warning=FALSE}`)
* Consider saving intermediate objects e.g.,
`lip <- MSstatsLiP_Summarized[["LiP"]]`, to help improve readability.
* Remove commented code.
* Format the code for readability and so it does not exceed 80 character
widths.

## R

* List all the possible inputs in the `model_type` argument (and others) as
a character vector. Then, within the function, use `match.arg` to select
one from the inputs.
* Avoid inefficient code such as splitting `model.data` into two `data.frame`s
then binding them into one `data.frame` rather than just using adding the
result of `adj.pvalue < adj.pvalue.cutoff & abs(log2FC) >= FC.cutoff` to the
`data.frame` (`BarcodePlotLiP`).
* Avoid using `ifelse` if you are using `TRUE` and `FALSE` as the results
because you can simplify to, e.g.,
`combined_df$NTERMINUS <- combined_df$start == 1` in `calculateTripticity`
* Consider using the name of the element in `data` as the `model_type` input
so that you can simply pass that input for subsetting `data`, i.e.,
`data[[model_type]]` in `BarcodePlotLiP`.
* Do not save files for the user and do not use the current working directory
as default. If anything use the `tempdir()` folder. Memory is limited on the
Bioconductor builders.
* Remove the `pdf` function call from `BarcodePlotLiP` and only output the
plot from `ggplot`.
* If you want to plot, plot to the graphics device as the output of the
function.
* Avoid nested for loops wherever possible.
* Do not create a log by default in the users working directory. Consider
setting the path to the `tempfile` or not creating one unless the users
provides a path for it.
* Consider using `messages` instead of saving a text file as a log.
* Consider combining similar calls so that there is less repitition, e.g.,
`Trp.model` can be set to `NULL` if `Trp.model` does not have any rows.
* Combine checks and/or create a helper function for `.locateCheck`.
* Please do not use `print` within a function, use `message` instead.

* Minor: Use `seq_along` instead of `seq(length())`.
* Why not use `is.character()` rather than `identical(typeof(), "character")`
on `fasta_file` in `calculateTripticity`?
* Also, you already ask the user to run `tidyFasta()` on the file so why
do it again yourself?
* Double evaluation of a logical is not necessary within an `if()`, e.g.,
`if (use_log_file == TRUE)` can be simplified to `if (use_log_file)`.
* `if (nrow(x))` is equivalent to `if (nrow(x) != 0)`


## covr

* You have good coverage in some functions. Please consider adding more test to functions that have 0 coverage. 

```r
> covr::package_coverage()
MSstatsLiP Coverage: 38.75%
R/BarcodePlotLiP.R: 0.00%
R/PCAPlotLiP.R: 0.00%
R/SkylinetoMSstatsLiPFormat.R: 0.00%
R/SpectronauttoMSstatsLiPFormat.R: 0.00%
src/model_adjustment.cpp: 0.00%
R/locatePTM.R: 19.59%
R/utils_checks.R: 39.44%
R/dataSummarizationLiP.R: 62.50%
R/correlationPlotLiP.R: 76.74%
R/groupComparisonPlotsLiP.R: 82.35%
R/groupComparisonLiP.R: 86.49%
R/trypticHistogramLiP.R: 94.23%
R/calculateTrypticity.R: 96.77%
R/dataProcessPlotsLiP.R: 100.00%
```

**Comment by devonjkohler** [comment]
Hey Marcel,@LiNk-NY

Thank you for your review, your comments were very helpful. 

I just pushed an update and tried to address everything. Please see below.

### DESCRIPTION

I fixed the description field. This is a new package that uses some of the backend of MSstatsPTM.
That should be reflected now.

### Vignettes

I updated everything here like you suggested.

### R

I tried to make all the code updates you suggest. 

The only thing I was unable to change was the logging and pdf writing to the user's directory.
This is how the entire family of MSstats packages (MSstats/MSstatsTMT/MSstatsPTM) write logs 
and pdfs and this package relies on them to write the majority of the files (other than a couple 
of the new plotting functions I wrote for this package specifically).

I will talk to the other developers of MSstats about this and we will work on a different 
idea for saving logs and plots. This one is more major and requires updates to a number of packages.

For now, the option to not save logs or plots is available to the user and I updated the vignette to not save 
logs or plots to the user's directory. 

### covr

I added more tests to try to cover the remaining functions. The only one that does not have coverage 
now is SkylinetoMSstatsLiPFormat.R. I do not have raw skyline example data in the package so 
it is hard to write meaningful tests for it.

I hope all of this makes sense!

Best,
Devon

**Comment by LiNk-NY** [comment]
Hi Devon, @devonjkohler 
Thanks for making those changes. 
Perhaps there may be some existing packages that make Skyline data available ([`lipidr`](https://bioconductor.org/packages/release/bioc/vignettes/lipidr/inst/doc/workflow.html)?). 

**Update**: Please resolve this note. 
```r
* checking R code for possible problems ... NOTE
BarcodePlotLiP: no visible binding for global variable ‘fully_TRI’
BarcodePlotLiP: no visible binding for global variable ‘ProteinName’
BarcodePlotLiP: no visible binding for global variable ‘uniprot_iso’
BarcodePlotLiP: no visible binding for global variable ‘Label’
BarcodePlotLiP: no visible binding for global variable
  ‘PeptideSequence’
BarcodePlotLiP: no visible binding for global variable ‘sig’
BarcodePlotLiP: no visible binding for global variable ‘Coverage’
BarcodePlotLiP: no visible binding for global variable ‘Index’
PCAPlotLiP: no visible binding for global variable ‘FULL_PEPTIDE’
PCAPlotLiP: no visible binding for global variable ‘Protein’
SkylinetoMSstatsLiPFormat: no visible binding for global variable
  ‘Intensity’
SpectronauttoMSstatsLiPFormat: no visible binding for global variable
  ‘R.Condition’
calculate.pc: no visible binding for global variable ‘Cond_rep’
calculate.pc: no visible binding for global variable ‘LogIntensities’
calculate.pc: no visible binding for global variable ‘FULL_PEPTIDE’
calculate.pc: no visible binding for global variable ‘Protein’
calculate.pc: no visible global function definition for ‘prcomp’
correlationPlotLiP: no visible global function definition for ‘cor’
correlationPlotLiP: no visible binding for global variable ‘SUBJECT’
correlationPlotLiP: no visible binding for global variable ‘variable2’
correlationPlotLiP: no visible binding for global variable ‘variable’
correlationPlotLiP: no visible binding for global variable ‘value’
dataProcessPlotsLiP: no visible binding for global variable ‘PROTEIN’
dataProcessPlotsLiP: no visible binding for global variable ‘Protein’
dataProcessPlotsLiP: no visible binding for global variable
  ‘FULL_PEPTIDE’
dataSummarizationLiP: no visible binding for global variable ‘PROTEIN’
dataSummarizationLiP: no visible binding for global variable ‘Protein’
groupComparisonLiP: no visible binding for global variable ‘PEPTIDE’
groupComparisonLiP: no visible binding for global variable ‘Protein’
groupComparisonLiP: no visible binding for global variable
  ‘GlobalProtein’
groupComparisonPlotsLiP: no visible binding for global variable
  ‘..keep’
groupComparisonPlotsLiP: no visible binding for global variable
  ‘FULL_PEPTIDE’
groupComparisonPlotsLiP: no visible binding for global variable
  ‘Protein’
groupComparisonPlotsLiP: no visible binding for global variable
  ‘..adjusted.keep’
trypticHistogramLiP: no visible global function definition for ‘.’
trypticHistogramLiP: no visible binding for global variable ‘GROUP’
trypticHistogramLiP: no visible binding for global variable ‘SUBJECT’
trypticHistogramLiP: no visible binding for global variable ‘fully_TRI’
trypticHistogramLiP: no visible binding for global variable
  ‘percent_plot’
Undefined global functions or variables:
  . ..adjusted.keep ..keep Cond_rep Coverage FULL_PEPTIDE GROUP
  GlobalProtein Index Intensity Label LogIntensities PEPTIDE PROTEIN
  PeptideSequence Protein ProteinName R.Condition SUBJECT cor fully_TRI
  percent_plot prcomp sig uniprot_iso value variable variable2
Consider adding
  importFrom("stats", "cor", "prcomp")
to your NAMESPACE file.
```

* Please make sure that log files are not saved in the users filesystem unless explicitly requested perhaps with a package-wide option. 

Best regards,
Marcel

**Comment by devonjkohler** [comment]
Hey Marcel, @LiNk-NY

I made the final changes you mentioned in your last comment. I added some skyline data from the MSstats package to test the function on and cleaned up the note. For the log writing, I set it to not write to the directory, while still giving them the option if desired.

Hope this takes care of everything!

Best,
Devon

**Comment by LiNk-NY** [comment]
Hi Devon, @devonjkohler 

Thank you for making those changes and for your contribution.
Your package has been accepted to Bioconductor.

Best regards,
Marcel

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/devonjkohler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsLiP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsLiP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
