### ISSUE TITLE
txcutr

### ISSUE THREAD

**Issue by mfansler** [Bioconductor/Contributions#2361]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mfansler/txcutr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mfansler** [comment]
Hi @jianhong and thanks for reviewing! 

The tests all passed on Linux under time. The Windows build seems to take unexpectedly longer on the unit tests (90s on Linux; > 513s on Windows). Is that typical? While the R CMD CHECK on GitHub Actions does run slightly longer on Windows, it never took 5 times as long (see [recent result](https://github.com/mfansler/txcutr/actions/runs/1294083466)).

I'm not sure why the OSX version failed - it couldn't check out the repository. How does that get dealt with?

**Comment by lshep** [comment]
OSX was on our end. Our machine ran out of space. I'm kicking off a manual build that hopeful should produce results for OSX.

**Comment by mfansler** [comment]
@lshep thanks!

@jianhong is it possible the Windows `R CMD check` is having issues with tests that write files?

**Comment by mfansler** [comment]
@jianhong @lshep do I need to resolve this timeout issue before a review will be done?

**Comment by lshep** [comment]
@jianhong  please proceed with the review; I'll try to look into the windows slow down early next week.

**Comment by jianhong** [comment]
# Package txcutr Review

The package is almost ready. There are some minor issues need to be fixed.

## The DESCRIPTION file

- [ ] `Depends` is missing
- [ ] Consider adding these automatically suggested `biocViews`: Sequencing, Alignment

## The NAMESPACE file

- [ ] Consider adding
  *  importFrom("methods", "slot", "slot<-")
  *  importFrom("utils", "capture.output")
  *  importFrom("S4Vectors","elementNROWS")
  *  importFrom("GenomicFeatures","makeTxDbFromGRanges")
  *  importFrom("AnnotationDbi","taxonomyId")

## Documentation

- [ ] consider to use `tempdir,tempfile` in vignette for the following files:
    ‘sacCer3.sgdGene.w500.fa’ ‘sacCer3.sgdGene.w500.fa.gz’
    ‘sacCer3.sgdGene.w500.gtf’ ‘sacCer3.sgdGene.w500.gtf.gz’
    ‘sacCer3.sgdGene.w500.merge.tsv’ ‘sacCer3.sgdGene.w500.merge.tsv.gz’


## R code

- [ ] Function arguments should be tested for validity, eg 
	`txdb` is not test in `txdbToGRangesList`

## Unacceptable files

- [ ] merge the .gitignore in vignettes to root folder or remove it.

**Comment by mfansler** [comment]
@jianhong thanks for the informative feedback. Suggested changes have been integrated.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mfansler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("txcutr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/txcutr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
