### ISSUE TITLE
easierData

### ISSUE THREAD

**Issue by olapuentesantana** [Bioconductor/Contributions#2374]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/olapuentesantana/easierData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by olapuentesantana** [comment]
I am tagging @federicomarini, @arsenij-ust, @FFinotello and @eduati as co-authors for this package. Now waiting for a `review in progress` tag to submit `easier` package

**Comment by olapuentesantana** [comment]
Hello @mtmorgan,

I was wondering if the "review in progress" tag isn't assigned before the issue closed, are we going to still be able to submit our software package `easier` (https://github.com/olapuentesantana/easier)?

**Comment by olapuentesantana** [comment]
AdditionalPackage: https://github.com/olapuentesantana/easier

**Comment by olapuentesantana** [comment]
Hello, 

`easier` led to the following error in R CMD check in merida1 and riesling1, but not in nebbiolo2. Please, could you help us to gain a better understanding of this error?

`checking examples ... ERROR TIMEOUT: R CMD check exceeded 14 mins 
`
Thanks,
Oscar

**Comment by federicomarini** [comment]
I think it is just that it took too long to perform `R CMD check` on the builder machine.
No clue why it is only on that one machine (maybe different settings of how long it takes to trigger the timeout?)

**Comment by olapuentesantana** [comment]
Hello @lshep,

I tried several times to subscribe to the bioc-devel mailing list but without succeeding. Could you help me with that?

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

Regards,
Óscar

**Comment by lshep** [comment]
Normally there is a confirmation email that sometimes gets filter to spam?

**Comment by olapuentesantana** [comment]
Unfortunately, that is not the case. I do not receive any reply back.

**Comment by lshep** [comment]
And you registered the same email as in the description `o.lapuente.santana@tue.nl` ?

**Comment by olapuentesantana** [comment]
Yes, I am using that one.  And, this what the website returns, but afterwards I get no further notice.
![Screen Shot 2021-10-08 at 16 35 25](https://user-images.githubusercontent.com/42207933/136575801-ae991473-4230-47b1-bcff-1b1a46a8e471.png)

**Comment by olapuentesantana** [comment]
AdditionalPackage: https://github.com/olapuentesantana/easier

**Comment by olapuentesantana** [comment]
And, also I wasn't sure what to build again the new bumped version of the software package `easier` which depends on the data package `easierData`.  I think I just messed it up.

I thought once is pushed to `git@git.bioconductor.org:packages/easier`, it will be built after `easierData` but it doesn't seem to be the case. So @lshep may I ask for your help here as well?

**Comment by lshep** [comment]
We do a moderation step for each package submitted before allowing build on demand by version bump.  This is the correct process for packages that depend on each other and once we look at the package and approve for building it will get an auto build

**Comment by olapuentesantana** [comment]
Hello @lshep,

I am getting the following error when trying to bump version to start a new build. I am getting this error via the command line:

```
Total 3 (delta 2), reused 0 (delta 0)
remote: Error: Please bump the version again and push.
remote: 
remote: The build did not start as expected. If the issue persists,
remote: please reach out at bioc-devel@r-project.org or post on the
remote: Github issue where your package is being reviewed.
remote: 
remote: 500 Server Error: Internal Server Error for url: https://issues.bioconductor.org/start_build
remote: 
To git.bioconductor.org:packages/easierData.git
   c0c2bdd..c18bcc8  main -> master
```

I think this is because this issue entered in `awaiting moderation` tag.  Could that be the reason?

From the introductions on how to submit new builds (https://github.com/Bioconductor/Contributions#submitting-related-packages), I do not understand that this tag should change. Could you briefly explain me how to submit a new build when submitting related packages? 

Thanks and kind regards,
Óscar

**Comment by lshep** [comment]
When I try to build the easier package locally I am getting an error about a missing package that doesn't seem to be declared anywhere?  I'm wondering where this dependency comes from and perhaps a selective import needs to be a full import so that the package builds/installs correctly? 
```
* creating vignettes ... ERROR
--- re-building ‘easier_user_manual.Rmd’ using rmarkdown
Quitting from lines 356-363 (easier_user_manual.Rmd) 
Error: processing vignette 'easier_user_manual.Rmd' failed with diagnostics:
coin package needed to be installed before using this function. Type this in R: install.packages('coin')
```

I'm looking at the packages now and will have a more in-depth review shortly.

**Comment by lshep** [comment]
a few other minor comments. The same comments for both packages: 

**easierData**

**README**

- [ ] Please include Bioconductor installation instructions

**general**

- [ ] I noticed a custom citation in the readme and description. You might want
  to consider including a CITATION file in the inst directory so that it also
  appears on the Bioconductor package landing page.
  
**test**

- [ ] Please include actual tests for your package or remove. Having non
  applicable tests is not appropriate


---------------------------------------------------------

**easier**

**LICENSE/LICENSE.md**

- [ ] Consider changing more specific than "The Authors" to at least the easier
  authors?


**README**

- [ ] Please include Bioconductor installation instructions

**general**

- [ ] I noticed a custom citation in the readme and description. You might want
  to consider including a CITATION file in the inst directory so that it also
  appears on the Bioconductor package landing page.


**test**

- [ ] Please include actual tests for your package or remove. Having non
  applicable tests is not appropriate


Please address the above concerns and when ready push a version bump to trigger a new build.  Then comment back here that you are ready for a re-review. 
Cheers

**Comment by lshep** [comment]
A reminder the last day to be added to the manifest for release 3.14 is tomorrow. Please make the appropriate changes before packages will be accepted.

**Comment by olapuentesantana** [comment]
Hello @lshep ,

In explore_biomarkers.R, we employ rstatix::wilcox_effsize() which calls coin::wilcoxsign_test(). However it seems that the coin  package is included in the DESCRIPTION file as Suggests, unclear why it is not an import, which lead to the following error.

To solve this, we added the coin package as a dependency leading to the corresponding WARNING label, because this package is not being used in our namespace. 

Any input on how we could further address this?

* creating vignettes ... ERROR
--- re-building ‘easier_user_manual.Rmd’ using rmarkdown
Quitting from lines 356-363 (easier_user_manual.Rmd) 
Error: processing vignette 'easier_user_manual.Rmd' failed with diagnostics:
coin package needed to be installed before using this function. Type this in R: install.packages('coin')

Despite what commented above, we are ready for re-review.

**Comment by lshep** [comment]
I'd be fine with the warning. Or you could selectively import the one function with the `importFrom(coin,wilcoxsign_test)`  but if you feel more comfortable excluding all together since it really stems from a dependency of a dependency I'm okay with that too. Cheers

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/olapuentesantana.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("easierData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/easierData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/olapuentesantana.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("easier")`. The package 'landing page' will be created at

https://bioconductor.org/packages/easier

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
