### ISSUE TITLE
tuberculosis

### ISSUE THREAD

**Issue by schifferl** [Bioconductor/Contributions#2375]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/schifferl/tuberculosis

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

---

> Adding a note here, there are a number of places where code is commented out because the requisite `ExperimentHub` records have not been inserted into the production database yet. I have uploaded to S3 and sent my `metadata.csv` file, but from conversation with Marcel I understand no one is available to finalize the process until at least Monday. I am submitting the package here to meet the deadline for the release and will make a few changes when the `ExperimentHub` resources become available. The package will work much like `curatedMetagenomicData` does.

**Comment by schifferl** [comment]
Some biocViews had to be removed to make the `bioc-issue-bot` accept the package, they were added back after the comment above. 

The DESCRIPTION file for this package is:

```
Package: tuberculosis
Title: Tuberculosis Gene Expression Data for Machine Learning
Description:
    The tuberculosis R/Bioconductor package features tuberculosis gene
    expression data for machine learning. All human samples from GEO that did
    not come from cell lines, were not taken postmortem, and did not feature
    recombination have been included. The package has more than 10,000 samples
    from both microarray and sequencing studies that have been processed from
    raw data through a hyper-standardized, reproducible pipeline.
Authors@R:
    person(given = "Lucas", family = "Schiffer", role = c("aut", "cre"),
           email = "schiffer.lucas@gmail.com",
           comment = c(ORCID = "0000-0003-3628-0326"))
biocViews:
    ExperimentHub,
    ExpressionData,
    Homo_sapiens_Data,
    MicroarrayData,
    SequencingData,
    ReproducibleResearch
Version: 0.99.0
License: Artistic-2.0
Depends:
    R (>= 4.1.0)
Imports:
    stringr
Suggests:
    BiocStyle,
    dplyr,
    ggplot2,
    hrbrthemes,
    knitr,
    magrittr,
    purrr,
    readr,
    rmarkdown,
    scater,
    tidyr,
    usethis,
    utils
URL: https://github.com/schifferl/tuberculosis
BugReports: https://github.com/schifferl/tuberculosis/issues
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
VignetteBuilder: knitr
```

**Comment by LiNk-NY** [comment]
Perhaps it's tripping up because there is no biocView on the same line as `biocViews: ` but `biocViews: x, y` works. 
Thanks for the update Lucas.

**Comment by nturaga** [comment]
Hi @schifferl 

This package looks good to me. I will accept it with no further comment.

**Comment by schifferl** [comment]
Thanks @nturaga! I'll look forward to the release and add a NEWS file before the package comes out. Thanks again 🙏

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/schifferl.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tuberculosis")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tuberculosis

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
