### ISSUE TITLE
GeoDiff

### ISSUE THREAD

**Issue by zhiiiyang** [Bioconductor/Contributions#2377]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nanostring-Biostats/GeoDiff

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by zhiiiyang** [comment]
@LiNk-NY, we filed a request to change the maintainer from Lei Y to me. If possible, could you facilitate that process so we can get to the reviewing process soon?

**Comment by lshep** [comment]
@zhiiiyang you should now have access to push changes to git.bioconductor.org for GeoDiff.

**Comment by zhiiiyang** [comment]
@lshep, thank you! I have the following error while pushing new changes. Do you possibly know the cause? Do I have write access to the upstream main branch?
![image](https://user-images.githubusercontent.com/7269113/136251848-ee2db43b-d9a4-4843-ac02-982145643c59.png)

**Comment by lshep** [comment]
Bioconductor still uses master as the default branch instead of main. try `git push upstream main:master`
   See step 5 of https://bioconductor.org/developers/how-to/git/new-package-workflow/

**Comment by LiNk-NY** [comment]
Hi Zhi, @zhiiiyang 

Thank you for your submission. Please see the comments below.

Best regards,
Marcel

---

# GeoDiff #2377

* Please explain how do you make use of the established Bioconductor
infrastructure in your package.
* `Biobase` is not a modern Bioconductor package and has been supplanted by `SummarizedExperiment`.
* Based on the files reviewed, it seems that `CRAN` would be more appropriate.

## DESCRIPTION

* Please wrap your `Description` field with a limit of 80 characters so that it
is legible.
* Add `URL` and `BugReports` fields.
* Update the R dependency version to `R (>= 4.1.0)`.

## NAMESPACE

* Consider using the native pipe `|>` rather than `magrittr`'s.
* Consider suggesting `NanoStringNCTools` if you are only using one function
from the package.

**Comment by NicoleEO** [comment]
@LiNk-NY Thanks for reviewing Marcel.
GeoDiff does not have its own infrastructure, but uses an existing Bioconductor package (GeomxTools) for a version of its ingestion. For GeoMxTools and the inherited NCTools, we have a plan for future work to migrate over to SummarizedExperiment as the platform for those two packages. For GeoDiff, there are functions to use matrices as entrypoints, but we need to have a level of compatibility with GeoMxTools as this package includes unique infrastructure for GeoMx data and therefore is required to be compatible as a corporate goal. As GeoMxTools migrates over to SummarizedExperiment, so will GeoDiff as that compatibility needs to remain.

**Comment by LiNk-NY** [comment]
Hi Nicole, @NicoleEO 

Support for both `matrix` and `SummarizedExperiment` is certainly welcome. 

The dependency on `GeomxTools` is soft (`Suggests` field) and should actually be an 
`Imports` if you are using a function from the package and setting methods 
(though generally not recommended for external classes). 

We generally do not condone the use of `ExpressionSet` anymore as the class has
been superseded. We do make exceptions (reluctantly) if you are using established
infrastructure that was written with `Biobase`. But please be aware that newer tools
are developed with `SummarizedExperiment` as the predominant representation. 

Best regards,
Marcel

**Comment by NicoleEO** [comment]
@LiNk-NY Thanks Marcel. We'll add GeomxTools to Imports. You should be seeing the other edits coming in the next day or two.

**Comment by zhiiiyang** [comment]
@LiNk-NY, we have addressed all your comments in the last commit. Please review it and let us know your thoughts.

**Comment by LiNk-NY** [comment]
Hi Nicole @NicoleEO and Zhi Yang @zhiiiyang,
Thank you for making those changes. Please follow up on the output of `BiocCheck::BiocCheck()` as you continue to improve your package. 

Your package has been accepted and will be added to the development branch of Bioconductor. 

Best regards,
Marcel

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhiiiyang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GeoDiff")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeoDiff

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
