### ISSUE TITLE
GBScleanR

### ISSUE THREAD

**Issue by tomoyukif** [Bioconductor/Contributions#2380]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tomoyukif/GBScleanR

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
Please fix the errors and warnings to meet the requirement of review process. If you need any help, please let me known or ask help in develop mailing list.

**Comment by tomoyukif** [comment]
Hi @jianhong,
Thank you for your contribution to review my package.
Since this is my first package to register in Bioconductor, I do not know what I should do next.
Should I just wait your review or have to do something?

**Comment by jianhong** [comment]
Hi @tomoyukif,

I will post my review within couple days. Thank you for your patient.

Jianhong.

**Comment by jianhong** [comment]
# Package GBScleanR Review

The package is in good shape but there are some issues need to be fixed.

## Documentation

- [ ] Consider `BiocStyle` package for vignette formatting.
- [ ] Table of contents in vignette is missing.
- [ ] Consider [citing references by bibliographies](https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html).
- [ ] Two Vignettes contain duplicated contents.
   

## Unit tests

- [ ] Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] Typo: AllUitlities.R should be AllUtilities.R?
- [ ] Function arguments need to be tested for validity.
- [ ] Coding and syntax:
- [ ] please consider to access slot with accessors but not `@`
- [ ] `paste0` function found in `message()` methods. No need to do that. eg. AllUtilities.R line 67-68 can be simplified to `message(out_fn, ' exists!')`.
- [ ] `::` is not suggested in source code.
- [ ] Bioconductor package does not allow writing files to directory without prompt unless the file is saved to a `tempfile()`. e.g.: In `AllUitlities.R::.convertGDS`, please export the `new_gds_fn` as a parameter.  `tmp_gds`, and `out_fn_tmp` in methods `gbsrGDS2VCF` 
- [ ] call `closefn.gds` by `on.exit` when you call `openfn.gds`.
- [ ] Avoid 'suppressWarnings'/'*Messages' if possible in `Methods-GbsrGenotypeData_HMM.R` and `Methods-GbsrGenotypeData.R`
- [ ] Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online. 
- [ ] Merge repetitive code as much as possible.
- [ ] Consider to export `ggplot` object rather than print it.
- [ ] Consider to replace `for` loops to vectorized functions. eg in `Methods-GbsrGenotypeData_HMM.R line 357-362` can be replaced by `pat <- do.call(rbind, lapply(chr, FUN=function(i)...))`

## C and Fortran code

- [ ] clean up unused code.

**Comment by tomoyukif** [comment]
@jianhong,
Thank you so much for your detailed review.
I will take a few days to fix the issues.

**Comment by tomoyukif** [comment]
@jianhong,
I finally finished to fix the issues you pointed out.
The codes were largely reorganized with making several sub functions to avoid redundancy.
I also changed file creation functions so that all intermediate files are saved to `tempfile()`.
I hope the revised version meets all of the requirements.

**Comment by jianhong** [comment]
@tomoyukif almost there. Please fix the following issues:

- [ ] suggest change `AllUtillities.R` line 55-56 to `message(out_fn, ' exists!')`
- [ ] always call `closefn.gds` by `on.exit` when you call `openfn.gds`; `on.exit` can be overloaded if you close the file manually. see `?on.exit` for more help.
- [ ] Please fix the documentation `return` section if you output the `ggplot` object for `pairsGBSR`.

**Comment by tomoyukif** [comment]
@jianhong 
The call `closefn.gds` by `on.exit` for a manually closed file gave an error message saying "the GDS file is closed or uninitialized".
Therefore, I set to call `closefn.gds` by `on.exit` whenever I call `openfn.gds`, but I reset `on.exit` if I manually closed the file connection.
Is this way acceptable?

**Comment by jianhong** [comment]
> @jianhong The call `closefn.gds` by `on.exit` for a manually closed file gave an error message saying "the GDS file is closed or uninitialized". Therefore, I set to call `closefn.gds` by `on.exit` whenever I call `openfn.gds`, but I reset `on.exit` if I manually closed the file connection. Is this way acceptable?

Yes, that is exactly what I mean.

**Comment by tomoyukif** [comment]
@jianhong,
Thank you so much for your support and detailed review for my package.
The revision process made me consider more about user friendly implementation and practical effective coding.
Really good experience!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tomoyukif.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GBScleanR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GBScleanR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
