### ISSUE TITLE
crisprBase

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#2398]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jfortin1/crisprBase

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, thanks for reviewing this package. The only error now for the package comes from the fact that `testthat` does not build on CRAN at the moment.

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

It looks like `testthat` should be [available on Mac now](https://cran.r-project.org/web/checks/check_results_testthat.html). 
Please bump the version for another build. 
I will review your package today. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 
Thank you for your submission. Please see the review below. 
Best regards,
Marcel

---

# crisprBase #2398

## DESCRIPTION

* Please run `BiocCheck::BiocCheck()`.
* Remove `LazyData` field from the `DESCRIPTION` or set to `FALSE`.
* Include `BugReports` and `URL` fields.

## NAMESPACE

* Where possible, avoid using generic names e.g., `info` and `name`.
Presumably, `info` could be renamed to `metadata`.

## vignettes

* Provide an `Installation` section.

## R

* Remove the `if (require(GenomicRanges))` code. `GenomicRanges` should be
available for the examples. Otherwise, use `library(GenomicRanges)` if not
available.
* Avoid mentioning `@` in `setValidity` errors. These are not meant to be
used by end-users.
* Examples should show how data was loaded avoid lazy loading.

## tests

* Coverage looks good.
```
> covr::package_coverage()
crisprBase Coverage: 70.09%
R/CrisprNuclease-class.R: 46.58%
R/utils.R: 52.86%
R/AllGenerics.R: 61.90%
R/Nuclease-class.R: 74.07%
R/arithmetics.R: 92.38%
```

**Comment by Jfortin1** [comment]
Thanks @LiNk-NY for your review -- I've improved the package to incorporate your comments and suggestions. 
The only exception is leaving `LazyData=TRUE` as 
- Our objects are very small
- Given the core utility of those already-constructed `CrisprNuclease` objects for CRISPR ecosystem packages (crisprBowtie and crisprDesign), we do want to access `SpCas9` by simply calling `crisprBase::SpCas9`

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 
This is not a good argument for using `LazyData`. I can see the convenience but for readability's sake, it is best to use `data("SpCas9", package = "crisprBase")` instead. This makes the user immediately aware of what is being requested and from where. 
Please remember to respond to the review line-by-line. Thank you.

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, I have now modified the package to use `LazyData=False`, and please find below my line-by-line review. The package has now an ERROR because of the DESCRIPTION file being malformed, supposedly. I cannot recapitulate this error locally with BiocCheck 1.31.14. Any idea what could be going on?


### DESCRIPTION

* Remove LazyData field from the DESCRIPTION or set to FALSE: **done**.
* Include BugReports and URL fields: **done**.

### NAMESPACE

- Where possible, avoid using generic names e.g., info and name.
Presumably, info could be renamed to metadataDone. **We changed `info` to `metadata`, and change `name` to `nucleaseName`**

### Vignette

- Provide an Installation section. **Done**.

### R

- Remove the if (require(GenomicRanges)) code. GenomicRanges should be
available for the examples. Otherwise, use library(GenomicRanges) if not
available. **Done**
- Avoid mentioning @ in setValidity errors. These are not meant to be
used by end-users. **Done**
- Examples should show how data was loaded avoid lazy loading.
tests **Done**

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Thank you for making those changes. They look good. 
Please use dedicated getter functions and avoid using the `@`
operator in the `CrisprNuclease` show method. 

The `metadata` generic is defined in `S4Vectors` and 
you can use it to create a method for your class. 

Best regards,
Marcel

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY,

We have now changed the show method for both `CrisprNuclease` and `Nuclease` to only use getter functions. We were already importing `metadata` from `S4Vectors`, so we used that. Thanks!

Waiting for the build to finish now.

Best,
JP

**Comment by LiNk-NY** [comment]
Hi Jean-Phlippe, @Jfortin1 

Sorry for the mix up. The appropriate way to get the `metadata` functionality is by adding

```
contains = "Annotated"
```

to the class definition.

This will grant you a `metadata` method via inheritance so you won't need to define the method. 

Best, 
Marcel

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY, that's a great suggestion, thank you. 
I have now changed the `Nuclease` object to extend the `Annotated` class, and reused the `metadata` method via inheritance. Documentation and vignette are updated as well.

**Comment by LiNk-NY** [comment]
Thanks!

**Comment by Jfortin1** [comment]
Thank you for all of your time and feedback, much appreciated!

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, It seems the package is not yet building in BioC 3.15 -- is there anything else I should do from my side?

**Comment by lshep** [comment]
@Jfortin1  nothing else to do from your sorry.  I needed to process the accepted packages.  I will do that now and it should appear available within the next 48 hours as long as it still install/builds/checks cleanly on the daily builder.  Sorry for the delay

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("crisprBase")`. The package 'landing page' will be created at

https://bioconductor.org/packages/crisprBase

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
