### ISSUE TITLE
`healthyControlsPresenceChecker`

### ISSUE THREAD

**Issue by davidechicco** [Bioconductor/Contributions#2416]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/davidechicco/healthyControlsPresenceChecker

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by davidechicco** [comment]
Hi everyone,
thanks for considering my package submission to Bioconductor. I made some minor changes and just submitted a new version, and I noticed that surprisingly my package does not pass the checks on macOS anymore:

>  R CMD BUILD
> 
> * checking for file healthyControlsPresenceChecker/DESCRIPTION ... OK
> * preparing healthyControlsPresenceChecker:
> * checking DESCRIPTION meta-information ... OK
> * installing the package to build vignettes
>       -----------------------------------
> ERROR: dependency GEOquery is not available for package healthyControlsPresenceChecker
> * removing /private/var/folders/7y/c__3_48d5y18p1_rhfs_4x9c0000gt/T/Rtmp4woFuk/Rinst11d3d2b0265ff/healthyControlsPresenceChecker
>       -----------------------------------
> ERROR: package installation failed

This is a bit weird to me, because my package has been using the `GEOquery` library in the last days too, and no error came up back then. Any idea on how to solve this issue? I'm developing my package on a computer running Linux Ubuntu 18.

**Comment by lazappi** [comment]
I think this is probably an issue with **{GEOquery}** rather than your package. It looks like the release version has failed to build (on Windows though, not macOS) http://bioconductor.org/checkResults/release/bioc-LATEST/GEOquery/. Given that the other platforms build I'm happy to do the package review. It might be worth doing another version bump once **{GEOquery}** is building ok to trigger the submission build system again.

**Comment by davidechicco** [comment]
Thanks @lazappi for the clarification. It would be great if you could start the package review anyway. Yes, I'll do another version dump once `GEOquery` builds correctly on Windows.

**Comment by vjcitn** [comment]
Hi, I had a look at the function in this package.  I wonder why the string "healthy controls" has such a privileged role.  Is this a convention throughout GEO?  If it is not, the function might be more useful if user could supply a string to check, with "healthy controls" the default value.

**Comment by davidechicco** [comment]
Hi @vjcitn, thanks for your message.
The string "healthy controls" has an extremely important role in gene expression datasets and among biomedical datasets in general because, if data of healthy controls are present in the dataset among data of patients, the researcher will be able to carry out a scientific analysis on both these conditions, and compare the results. 
Most of the datasets on GEO contain only data of sick individuals (for example, with bladder cancer). These datasets are useful, of course, but anything discovered among those patients is specific to them. When a dataset contains both data of patients and data of healthy controls, instead, a bioinformatician can run her/his analysis on the former group, then repeat it on the latter group, and then compare the results found among the two groups. 

I hope I clarified.

**Comment by lazappi** [comment]
Hi @davidechicco

I have done a first review of your package which I will post below. I just wanted to address some other points first.

* To clarify Vince's question I don't think he was asking my healthy controls themselves are important but why use only `"healthy controls"` as a search term. Is this a specified term by GEO? If not, it seems likely that whoever uploaded the data could describe the controls using different words, for example "samples 1-3 are from disease X and samples 4-6 are from _normal individuals_" or "sample 1 is from a disease model and sample 2 is _wildtype_" or "samples 1-6 are from tumour and samples 7-10 are from _healthy tissue_". Having a range of default terms and/or letting the user specify the term could make the function more generalisable.
* Have you considered submitting the function to an existing package (maybe **{GEOquery}**)? This would make the function available to whoever already uses that package and would avoid all the overhead with having to maintain another package just for this function.

**Comment by lazappi** [comment]
# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional

## General package development

- Package check should be ok once dependencies are building properly
- [ ] :warning: There are some notes from `BiocCheck::BiocCheck()` in the build report. Please have a look at these and see if you can address any.

## NAMESPACE file

- [ ] :warning: Generally use `importFrom` instead of importing all functions from a package with `import`. This is probably ok for **{stat}** and **{utils}** though.
- [ ] :rotating_light: Please export individual functions rather than using `exportPattern(".")`

## The NEWS file

- [ ] :green_circle: Please check that the versions in the NEWS file match the package versions

## Documentation

### README

- [ ] :rotating_light: Please add a `README` file
  - Any installation instructions in `README` should include Bioconductor instructions

### Vignette

- [ ] :rotating_light: Please add some content to your vignette. This should include:
  - [ ] An *Introduction* section
  - [ ] An *Installation* section (with Bioconductor installation instructions)
  - [ ] A description of the core functionality of the package
  - [ ] A `sessionInfo()` chunk at the end
- [ ] :rotating_light: The vignette should use the `BiocStyle` package for formatting
- [ ] :rotating_light: Please delete the `healthControlsPresenceChecker.R` file in the `vignettes/` directory

### Man pages

- [ ] :warning: It is recommended to add a package man page

## Unit tests

- [ ] :rotating_light: Please add unit testing to the package

## Code

### R

- [ ] :rotating_light: Please use accessor functions rather than `@` or `slot()` (if possible, they may not exist for these objects)
- [ ] :rotating_light: Please use `message()`, `warning()`, `stop()` instead of `cat()`
- [ ] :rotating_light: Please check that your access of web resources follow the [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/) guidelines

**Comment by davidechicco** [comment]
Hi @lazappi 
Thanks for your message and your review. 

> * To clarify Vince's question I don't think he was asking my healthy controls themselves are important but why use only `"healthy controls"` as a search term. Is this a specified term by GEO? If not, it seems likely that whoever uploaded the data could describe the controls using different words, for example "samples 1-3 are from disease X and samples 4-6 are from _normal individuals_" or "sample 1 is from a disease model and sample 2 is _wildtype_" or "samples 1-6 are from tumour and samples 7-10 are from _healthy tissue_". Having a range of default terms and/or letting the user specify the term could make the function more generalisable.

This is a very good point. I checked several datatasets and I noticed that another keyword used instead of ``healthy controls`` and ``healthy control`` is just ``healthy``, so I edited my script in order to capture that information. The word ``normal``, instead, cannot be used here because it can refer to some genetics aspect that can be normal or an aberration, and has nothing to do with the status of the patient. For example, in the [GSE19429](https://www.ncbi.nlm.nih.gov/geo/geo2r/?acc=GSE19429) dataset, the field ``Genome/variation`` contains some values as ``normal`` but that feature is unrelated to the healthy status of the samples. Therefore I'm going to keep my package searching only for the ``healthy`` and ``healthy control(s)`` keywords. 

> * Have you considered submitting the function to an existing package (maybe **{GEOquery}**)? This would make the function available to whoever already uses that package and would avoid all the overhead with having to maintain another package just for this function.

This is a good suggestion, too. Despite the effort needed, I actually would prefer to keep this package separated from the existing GEOquery package for the moment.

I already started to take care of your review, by addressing many points. Is there some automated way I can check by myself if my changes satisfy the requirements needed, by any chance?

Thanks again

**Comment by davidechicco** [comment]
@lazappi No need to repeat your review at the moment, I still have to address some points. I submitted a new package version to see if the label could move from ERROR to OK, which fortunately happened.

**Comment by davidechicco** [comment]
Thanks @lazappi for all the time and the effort you dedicated to review my package!
I just submitted a new version of it. Here are my replies to the comments:

> # Review
> **Key:** rotating_light Required warning Recommended green_circle Optional
> 
> ## General package development
> * Package check should be ok once dependencies are building properly
> * [ ]  warning There are some notes from `BiocCheck::BiocCheck()` in the build report. Please have a look at these and see if you can address any.

Davide: I checked them but I prefer not to change my code because it’s clearer in the way I wrote it for myself.

> ## NAMESPACE file
> * [x]  warning Generally use `importFrom` instead of importing all functions from a package with `import`. This is probably ok for **{stat}** and **{utils}** though.

Davide: Done.

> * [x]  rotating_light Please export individual functions rather than using `exportPattern(".")`

Davide: Done.

> ## The NEWS file
> * [x]  green_circle Please check that the versions in the NEWS file match the package versions

Davide: Done.

> ## Documentation
> ### README
> * [x]  rotating_light Please add a `README` file
>   * Any installation instructions in `README` should include Bioconductor instructions

Davide: Done
 
> ### Vignette
> * [x]  rotating_light Please add some content to your vignette. This should include:

Davide: Done

>   * [x]  An _Introduction_ section
>   * [x]  An _Installation_ section (with Bioconductor installation instructions)
>   * [x]  A description of the core functionality of the package
>   * [x]  A `sessionInfo()` chunk at the end

Davide: Done

> * [x]  rotating_light The vignette should use the `BiocStyle` package for formatting
> * [x]  rotating_light Please delete the `healthControlsPresenceChecker.R` file in the `vignettes/` directory

Davide: Done

> ### Man pages
> * [x]  warning It is recommended to add a package man page

Davide: Done

> ## Unit tests
> * [x]  rotating_light Please add unit testing to the package

Davide: Done

> ## Code
> ### R
> * [ ]  rotating_light Please use accessor functions rather than `@` or `slot()` (if possible, they may not exist for these objects)

Davide: I tried but could not find other methods to access those fields

> * [x]  rotating_light Please use `message()`, `warning()`, `stop()` instead of `cat()`

Davide: Done

> * [x]  rotating_light Please check that your access of web resources follow the [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/) guidelines

Davide: I checked it.

**Comment by lazappi** [comment]
Hi @davidechicco. I have a few more follow-up comments:

* There are still some `import()` statements in `NAMESPACE` (rather than `importFrom()`)
* A few points on the vignette (some of these also apply to `README`)
  * Code chunks showing functionality should be evaluated (the exception is installation instructions)
  * I probably wouldn't include GitHub installation instructions in the vignette as this will be shown for the built Bioconductor package and could be confusing to users (it is also generally preferable to recommend `remotes::install_github("user/repo")` rather than suggesting users manually download the git repo)
  * Please use the **BiocStyle** package to format the vignette rather than the default template
  * There are a few typos you might want to double-check 
* I wasn't able to find a package man page (not required but it's nice to have and you replied "done" to the point above)

Did you consider making the search keyword an argument to the function (with "health control" as a default)? This would probably be most flexible and avoid you having to think of every possible term. You could also make it a vector so people could check multiple terms at once.

**Comment by davidechicco** [comment]
Hi @lazappi, thanks again for your review. Please see my replies and few questions below:

> * There are still some `import()` statements in `NAMESPACE` (rather than `importFrom()`)

True; sorry I missed them, I fixed them in the new version I'm developing.

> * A few points on the vignette (some of these also apply to `README`)
>   
>   * Code chunks showing functionality should be evaluated (the exception is installation instructions)

I'm not sure what you mean here...

>   * I probably wouldn't include GitHub installation instructions in the vignette as this will be shown for the built Bioconductor package and could be confusing to users (it is also generally preferable to recommend `remotes::install_github("user/repo")` rather than suggesting users manually download the git repo)

Okay, I'll remove them.

>   * Please use the **BiocStyle** package to format the vignette rather than the default template

I will do it; sorry I missed it earlier.

>   * There are a few typos you might want to double-check

I cannot find any actually; I will double check more in detail.

> * I wasn't able to find a package man page (not required but it's nice to have and you replied "done" to the point above)

I actually created the [man Rd page](https://github.com/davidechicco/healthyControlsPresenceChecker/tree/main/man) and I thought it was sufficient and it what you meant. Isn't it?

> Did you consider making the search keyword an argument to the function (with "health control" as a default)? This would probably be most flexible and avoid you having to think of every possible term. You could also make it a vector so people could check multiple terms at once.

Yes, I considered it and I decided not to go that way, as I explained in a [previous message](https://github.com/Bioconductor/Contributions/issues/2416#issuecomment-973130052):

> I checked several datatasets and I noticed that another keyword used instead of `healthy controls` and `healthy control` is just `healthy`, so I edited my script in order to capture that information. The word `normal`, instead, cannot be used here because it can refer to some genetics aspect that can be normal or an aberration, and has nothing to do with the status of the patient. For example, in the [GSE19429](https://www.ncbi.nlm.nih.gov/geo/geo2r/?acc=GSE19429) dataset, the field `Genome/variation` contains some values as `normal` but that feature is unrelated to the healthy status of the samples. Therefore I'm going to keep my package searching only for the `healthy` and `healthy control(s)` keywords.

Thanks again! :-)

**Comment by davidechicco** [comment]
Hi again @lazappi 
I just submitted a new version of my package; I think I was able to address all your points except the man page one, about which I'm not completely sure I understood the needed requirements. As I mentioned earlier, my package [Rd man page](https://github.com/davidechicco/healthyControlsPresenceChecker/tree/main/man) is already present within the package.

Please let me know if there's anything else I should address in my software package, and thanks again for all your time and your energy spent on this review.

**Comment by lazappi** [comment]
Sorry for the confusion. What you have there is documentation for your function but you can also document the package itself as described here https://r-pkgs.org/man.html#man-packages. This is totally optional though so no stress if you don't want to worry about it.

**Comment by davidechicco** [comment]
> Sorry for the confusion. What you have there is documentation for your function but you can also document the package itself as described here https://r-pkgs.org/man.html#man-packages. This is totally optional though so no stress if you don't want to worry about it.

Thanks @lazappi for this clarification; I added a man page for the package itself in the new software package version I just resubmitted to Bioconductor. I hope it's okay now.

I look forward to moving to the next steps soon. Thanks again for your time and your effort for my package review.

**Comment by lazappi** [comment]
There are still a couple of minor issues with the vignette. The YAML front matter is a bit messed up, I think you just need to delete the very first line with a URL. The other thing is to make the installation instructions an unevaluated code chunk using:

````
```{r eval=FALSE}
# Code goes here
```
````

**Comment by davidechicco** [comment]
> There are still a couple of minor issues with the vignette. The YAML front matter is a bit messed up, I think you just need to delete the very first line with a URL. The other thing is to make the installation instructions an unevaluated code chunk using:
> 
> ```
> ```{r eval=FALSE}
> # Code goes here
> ```
> ```

Hi @lazappi, thanks for your additional comments. I addressed these points in the latest package version (version 0.99.14). I hope everything's okay now.

**Comment by davidechicco** [comment]
I just found and addressed a minor issue regarding the keyword search, and I submitted a new package version (0.99.15), which should be the final one.

**Comment by lazappi** [comment]
Hmmm...the YAML is still rendering weirdly for me. Maybe because it is indented?

![image](https://user-images.githubusercontent.com/6869320/143898169-013ee76e-83dc-4de0-aa49-e96480a7ecfb.png)

It should look more like this

![image](https://user-images.githubusercontent.com/6869320/143898550-a99aebd5-bd21-4575-a4df-8b9f93302e1c.png)

**Comment by davidechicco** [comment]
Hi @lazappi, thanks for your additional feedback. I think I was able to fix the YAML file following [this example](https://raw.githubusercontent.com/drisso/SingleCellExperiment/master/vignettes/intro.Rmd). 
Unfortunately, a new error came out and I cannot fix it... the online checks say the DESCRIPTION file is missing or malformatted, but it's actually in the same place where it has always been and it is formatted in the same old way it used to be formatted. I also ran the ` BiocCheckGitClone('healthyControlsPresenceChecker')` and `BiocCheck('healthyControlsPresenceChecker')` commands on my computer and everything went smoothly.  Any suggestions on how to proceed? Thanks

**Comment by lshep** [comment]
https://stat.ethz.ch/pipermail/bioc-devel/2021-November/018712.html    on our end please ignore that error for now

**Comment by davidechicco** [comment]
Thanks @lshep for the clarification.
@lazappi Please let me know if everything's okay now, thank you.

**Comment by lazappi** [comment]
Looks like it's all good now. I will approve this but it can take a few days to be picked up by the build system.

**Comment by davidechicco** [comment]
Thanks for this great news! :-)

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/davidechicco.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("healthyControlsPresenceChecker")`. The package 'landing page' will be created at

https://bioconductor.org/packages/healthyControlsPresenceChecker

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
