### ISSUE TITLE
OGRE submission

### ISSUE THREAD

**Issue by svenbioinf** [Bioconductor/Contributions#2431]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/svenbioinf/OGRE

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@svenbioinf - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: Set `LazyData` to false.
- [ ] REQUIRED: Update R version dependency from 4.0 to 4.2.0.
- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:  Sequencing.
- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field which includes a relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] SUGGESTION: We strongly encourage the use of `importFrom()` over importing the entire package.
- [ ] SUGGESTION: Consider adding `importFrom("grDevices", "dev.off", "pdf")` and `importFrom("stats", "setNames")` to your NAMESPACE file.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: We require documentation of data in the `inst/extdata/` directory to be present in the `inst/scripts/` directory. The scripts in this directory can vary. Most importantly the script must clearly document how the data was generated. It should include source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. Users should be able to download and roughly reproduce the file or object that is present as data.

## Vignette

- [ ] SUGGESTION: We recommend using the `BiocStyle` package for formatting.
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install and load the package from Bioconductor. The code should look like the following and include `eval = FALSE`.
```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
	install.packages("BiocManager")
BiocManager::install("OGRE")
```
- [ ] REQUIRED: 'sessionInfo' not found in vignette(s).
- [ ] SUGGESTION: We encourage the use of a package man page with an overview of the package and links to the main functions.
- [ ] SUGGESTION: For any function that is documented but not exported I would suggest adding the `@keywords internal` tag so the function is removed from the documentation index.

## Unit testing

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] SUGGESTION: Partial argument match of 'chr' to 'chromosome' (this came from R CMD check).
- [ ] SUGGESTION: Consider clarifying how 8 object(s) are initialized. Maybe they are part of a data set loaded with data(), or perhaps part of an object referenced in with() or within().
- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` if possible. Found in files: R/methods.R, lines 158 and 165.
- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` if possible. Found in files: methods.R, lines 221.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 93 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. There is 1 line that contains tabs.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 153 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@svenbioinf - Checking in to see if any progress has been made on the review I posted. We like to see changes within 2-3 weeks to be sure the package is actively being worked on. If there are no improvements made in the next few days I will have to close this issue for inactivity.

Best,
Kayla

**Comment by svenbioinf** [comment]
> @svenbioinf - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## DESCRIPTION
> * [x]  SUGGESTION: Set `LazyData` to false.
> * [ ]  REQUIRED: Update R version dependency from 4.0 to 4.2.0.
> * [x]  SUGGESTION: Consider adding these automatically suggested biocViews:  Sequencing.
> * [x]  SUGGESTION: We strongly encourage the use of the 'BugReports:' field which includes a relevant link to GitHub for reporting Issues.
> 
> ## NAMESPACE
> * [ ]  SUGGESTION: We strongly encourage the use of `importFrom()` over importing the entire package.
> * [x]  SUGGESTION: Consider adding `importFrom("grDevices", "dev.off", "pdf")` and `importFrom("stats", "setNames")` to your NAMESPACE file.
> 
> ## NEWS
> * [x]  SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.
> 
> ## Data
> * [x]  REQUIRED: We require documentation of data in the `inst/extdata/` directory to be present in the `inst/scripts/` directory. The scripts in this directory can vary. Most importantly the script must clearly document how the data was generated. It should include source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. Users should be able to download and roughly reproduce the file or object that is present as data.
> 
> ## Vignette
> * [ ]  SUGGESTION: We recommend using the `BiocStyle` package for formatting.
> * [x]  REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install and load the package from Bioconductor. The code should look like the following and include `eval = FALSE`.
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
> 	install.packages("BiocManager")
> BiocManager::install("OGRE")
> ```
> 
> * [x]  REQUIRED: 'sessionInfo' not found in vignette(s).
> * [x]  SUGGESTION: We encourage the use of a package man page with an overview of the package and links to the main functions.
> * [x]  SUGGESTION: For any function that is documented but not exported I would suggest adding the `@keywords internal` tag so the function is removed from the documentation index.
> 
> ## Unit testing
> * [x]  SUGGESTION: Consider adding unit tests. We strongly encourage them.
> 
> ## R code
> * [x]  SUGGESTION: Partial argument match of 'chr' to 'chromosome' (this came from R CMD check).
> * [x]  SUGGESTION: Consider clarifying how 8 object(s) are initialized. Maybe they are part of a data set loaded with data(), or perhaps part of an object referenced in with() or within().
> * [x]  REQUIRED: Avoid `sapply()`; use `vapply()` if possible. Found in files: R/methods.R, lines 158 and 165.
> * [x]  REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` if possible. Found in files: methods.R, lines 221.
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 93 lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. There is 1 line that contains tabs.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 153 lines that are not.
> 
> Best, Kayla

Hi Kayla,
I managed to address various points during the christmas holidays, however there are a couple of issues I would appreciate your input:
- REQUIRED: Update R version dependency from 4.0 to 4.2.0.
The latest R release I found was 4.1, I updated accordingly.
- Your internal MacOS buildcheck stops with "Graphics API version mismatch" It seems to be fine on Linux though
are you able to do anything from your side?
I also started to provide dataset access to OGRE by AnnotationHub.

Thank you for your support!

Best and Happy new year,
Sven

**Comment by svenbioinf** [comment]
Dear Kayla,
could you please comment on the note I wrote to you responding to your suggestion/requirements list?
Here it is again:
"Your internal MacOS buildcheck stops with "Graphics API version mismatch" It seems to be fine on Linux though
are you able to do anything from your side?"

So I updated all my R packages, do you need to do the same for your MacOS testing system maybe? (Just guessing)
Best,
Sven

**Comment by Kayla-Morrell** [comment]
@svenbioinf - I will bring this to the attention of our team. I was able to build it locally on my mac so I'm assuming it's something on our end. In the mean time I will re-review the package based on the other builders. I will have the rereview posted here in the next few days.

Best,
Kayla

**Comment by svenbioinf** [comment]
> @svenbioinf - I will bring this to the attention of our team. I was able to build it locally on my mac so I'm assuming it's something on our end. In the mean time I will re-review the package based on the other builders. I will have the rereview posted here in the next few days.
> 
> Best, Kayla

@Kayla-Morrell Just to keep you updated: 
I added more of your suggested points, however the Error from your builder system still pops up. 
Best, Sven

**Comment by Kayla-Morrell** [comment]
@svenbioinf - Thank you for making the necessary changes. I've looked them over and everything looks good, I'm more than happy to accept the package. In regards to the Mac ERROR - this can be ignored for now. Our team did some digging and found that `ggsave()` uses packages `ragg` and `textshaping` which CRAN has not provided Mac binaries yet for R 4.2. Until this happens the ERROR will persist. If there are further changes that need to be made we will notify you.

Best,
Kayla

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/svenbioinf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("OGRE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OGRE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by svenbioinf** [comment]
Thank you Kayla & the Bioconductor Team!
This is good news and I am happy to have OGRE accepted here at Bioconductor.
Have a nice day,
Sven
