### ISSUE TITLE
PanomiR submission

### ISSUE THREAD

**Issue by pouryany** [Bioconductor/Contributions#2440]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pouryany/PanomiR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by pouryany** [comment]
Hi @lshep 

Thank you for your feedback! The pre-review changes were addressed as requested. 

The issue:
https://github.com/pouryany/PanomiR/issues/79

Best,
Pourya

**Comment by vjcitn** [comment]
Thank you for your efforts.  Despite clean passage of R CMD check, there is additional work to be done.

---

This requirement is from BiocCheck::BiocCheck run in the root folder of your package:

`[1] "Update R version dependency from 4.1.0 to 4.2.0."   `

Make this change to DESCRIPTION.  You should be testing on the devel branch of R.

---

```
> library(PanomiR)
1/1 packages newly attached/loaded, see sessionInfo() for details.
> ls(2)
 [1] "%>%"                         "clusterPlot"                
 [3] "differentialPathwayAnalysis" "getDesignMatrix"            
```

Why are you exporting `%>%`?  R 4.1 has `|>` as a pipe operator in the language.  Please use it.

---

Vignette:
```
head(summaries)[,1:2]
#>                                                       TCGA-BC-A10S-01A-22R-A131-07
#> Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS                                  127079201
#> Pathway.KEGG_CITRATE_CYCLE_TCA_CYCLE                                     150409327
#> Pathway.KEGG_PENTOSE_PHOSPHATE_PATHWAY                                   116435143
#> Pathway.KEGG_PENTOSE_AND_GLUCURONATE_INTERCONVERSIONS                    128073170
```
Please explain the meaning of the large numbers in the vignette.

Redistributing content of KEGG pathway databases is not allowed.  Use KEGGREST to acquire pathway
data from KEGG.

---
```
3. Finding clusters of pathways
PanomiR provides a function to find groups coordinated differentially activated pathways based on the PCxN methodology.
```
What is PCxN methodology?  Provide a clear definition for the reader and a reference.

---
```
 Here, we provide a pre-processed table for LIHC table and in the next section, we will explain how to generate the customized tables.

Note that in the example below, we use a sampling rate of 50,
```
Both LIHC and "sampling rate" are used without explanation.  Please make the vignette reasonably self-explanatory.

---

Please follow the license terms at http://www.gsea-msigdb.org/gsea/index.jsp

These suggest citation of several papers.  However, you should seriously consider
reusing Bioconductor resources for MsigDb, see

https://bioconductor.org/packages/release/data/experiment/vignettes/msigdb/inst/doc/msigdb.html

which discusses both MSigDb and KEGG.

---

Consider a show or print method so that the user doesn't have to see all the details of

```
head(tempEnrich)
#>                             x                                       y      pval
#> 1    hsa-miR-1-3p/hsa-miR-206 Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS 0.1901934
#> 2            hsa-miR-101-3p.1 Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS 0.5697729
#> 3 hsa-miR-103a-3p/hsa-miR-107 Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS 1.0000000
#> 4             hsa-miR-1185-5p Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS 0.1629978
#> 5                hsa-miR-1193 Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS 0.3583626
#> 6                hsa-miR-1197 Pathway.KEGG_GLYCOLYSIS_GLUCONEOGENESIS 1.0000000
#>   Intersect mirset_Size not_mirset pathway_Size   ratio_in   ratio_out
#> 1         2          11        834           62 0.03333333 0.010791367
#> 2         1          11        834           62 0.01639344 0.011990408
#> 3         0          10        835           62 0.00000000 0.011976048
#> 4         2          10        835           62 0.03333333 0.009580838
#> 5         2          17        828           62 0.03333333 0.018115942
#> 6         0          18        827           62 0.00000000 0.021765417
#>   ratio_ratios
#> 1     3.088889
#> 2     1.367213
#> 3     0.000000
```

---

**Comment by pouryany** [comment]
Dear @vjcitn and @lshep 

I am not able to detect the sources of error in building the package in the automated builder. In my local machine and Github actions, the package builds without any errors, and the R CMD check passes completely.

I have edited the package according to your thorough and constructive review and I will post detailed responses shortly.

**Comment by pouryany** [comment]
Dear Vince (@vjcitn),
Happy new year! Thank you very much for your very constructive feedback.  As per my previous post, I am not sure why the package doesn't build on automated testing machines. My prime suspects are building/installing errors on one or more of the dependencies, most likely related to `clusterProfiler` or `DOSE`. I have made changes according to your comments and suggestions. Please find detailed responses to your comments as follows.

Best,
Pourya 

***
1. > This requirement is from BiocCheck::BiocCheck run in the root folder of your package:
    > `[1] “Update R version dependency from 4.1.0 to 4.2.0.“`
    > Make this change to DESCRIPTION. You should be testing on the devel branch of

The description file has been updated as instructed. The package is tested on the devel branch, both locally and using Github actions on Linux, Windows, and Mac.

***
2. > Why are you exporting `%>%`? R 4.1 has `|>` as a pipe operator in the language. Please use it.

The package now uses only the R `|>` operator. No local pipe operator is exported.

***
3. > Please explain the meaning of the large numbers in the vignette.

I have added explanations and references for how these numbers are generated. I have also enabled the normalization argument in the function to avoid having large, uninterpretable numbers.

> Redistributing content of KEGG pathway databases is not allowed. Use KEGGREST to acquire pathway
>data from KEGG.

I have removed all instances in the package data and examples that contain KEGG pathway contents. I have added a section in the vignette that explains how interested users can get access to KEGG pathways using appropriate permissions.

***
4. > What is PCxN methodology? Provide a clear definition for the reader and a reference.

Appropriate references to R packages and publications have been added to the vignette. A short description of PCxN has been added as well.

> Both LIHC and “sampling rate” are used without explanation. Please make the vignette reasonably self-explanatory.

Clarifications and explanations have been added to the vignette. We are planning an imminent journal/bioArxiv submission of a manuscript that describes PanomiR methodology and technical details. We will update vignettes with links and additional information once the manuscript is released.
***
5. > Please follow the license terms at http://www.gsea-msigdb.org/gsea/index.jsp
    > These suggest citation of several papers.

Appropriate citations have been added in the text of the vignette along with a references section.

>  However, you should seriously consider
> reusing Bioconductor resources for MsigDb, see
> https://bioconductor.org/packages/release/data/experiment/vignettes/msigdb/inst/doc/msigdb.html
> which discusses both MSigDb and KEGG.

I have added new functions to the package and instructions in the vignette to help users easily utilize `GSEABase` geneset objects in PanomiR. I have added instructions and links on how to use these features to incorporate MSigDB annotated pathways directly from the source or programmatic interfaces.

***
6. > Consider a show or print method so that the user doesn’t have to see all the details of [table]

I have added a new function `reportEnrichment()` to create publication-ready and readable tables from outputs of the `miRNAPathwayEnrichment()` function.  Details on this function have been added to the vignette.

**Comment by pouryany** [comment]
Dear @vjcitn 

The build error has been addressed and disappeared with some recent updates in Bioc packages (relating to [this post](https://stat.ethz.ch/pipermail/bioc-devel/2022-January/018782.html) on Biocdevel mailing list).

Please find my response to your review above. Thank you very much.

Best,
Pourya

**Comment by vjcitn** [comment]
I will accept the package.  Please consider using BiocStyle::html_document() for your vignette formatting.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pouryany.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PanomiR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PanomiR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
