### ISSUE TITLE
RolDE (Robust longitudinal Differential Expression)

### ISSUE THREAD

**Issue by tsvali** [Bioconductor/Contributions#2442]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/elolab/RolDE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
This is a very nice package.  However, it does not interoperate with relevant Bioconductor data structures.  Annotated experimental data for multiple samples should use SummarizedExperiment.  Please have a look at SummarizedExperiment package and if you have questions about how to use it please get in touch on slack.

**Comment by tsvali** [comment]
Thank you for your response. I will take a look at the SummarizedExperiment package and get back to you.

**Comment by tsvali** [comment]
Thank you again for your comment. I have now added support for the SummarizedExperiment data structure for the RolDE package.

**Comment by lshep** [comment]
@tsvali  Please fix ERROR, Warnings, and NOTES before kayla will do an in-depth review.  thank you.

**Comment by tsvali** [comment]
Thank you for the information. I will look into these issues. Do all the NOTES regarding coding practices also have to be corrected for? This might require substantial rethinking & coding of the proposed package and can take some time.

**Comment by Kayla-Morrell** [comment]
@tsvali - All ERRORs and WARNINGS should be fixed but NOTES are general suggestions. I will look over these NOTES as part of my review and let you know if I deem any of them to be required changes.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
Hello @tsvali,
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The installation instructions in the README file should also
  include Bioconductor installation instructions.

## DESCRIPTION

- [ ] SUGGESTION: Since you are using a standard license and don't use 'file
  LICENSE' in the 'License:' field this file can be removed from your package.
- [ ] REQUIRED: 'LazyData:' should be set to false or removed.
- [ ] REQUIRED: Update the R version dependency from 3.1.0 to 4.2.0 since this
  is the current version of R that is used with the devel version of
Bioconductor.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be
  included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: If possible, add more information about creation and/or source
  for data1, des_matrix1, des_matrix2, des_matrix3, res1, and res3.

## Vignette

- [ ] REQUIRED: There are code blocks that are set to `eval = FALSE`. We require
  most code blocks (except for installation instructions) to be executable.
- [ ] SUGGESTION: We encourage the use of the `BiocStyle` package for vignette
  formatting.
- [ ] REQUIRED: There should be an 'Installation' section that shows the users
  how to download and load the package from Bioconductor. These instructions
should be in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: We strongly encourage a table of contents.
- [ ] REQUIRED: Only the source vignette file (.Rnw or .Rmd) and any necessary
  static images should be in the vignette directory. The .html file should be
removed.

## Man pages

- [ ] SUGGESTION: Rd files 'RolDE.Rd' and 'RolDE_Main.Rd' the \examples lines
  are wider than 100 characters. These lines will be truncated in the PDF
manual, so you should consider fixing them.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead.
- [ ] REQUIRED: Use various `apply` functions instead of `for` loops. See the
  section in our documentation about vectorization, see here:
https://contributions.bioconductor.org/r-code.html#r-code-development.
- [ ] REQUIRED: Avoid `cat` outside of `show` method.
- [ ] REQUIRED: Avoid using `=` for assignment and use `<-` instead.
- [ ] REQUIRED: Avoid redundant `stop` and `warn*` in signal conditions.
- [ ] REQUIRED: Avoid `suppressWarnings`/`*Messages` if possible.
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 679
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. There are 973 lines that are not.

Best,
Kayla

**Comment by tsvali** [comment]
Dear Kayla,

Thank you very much for the review. I will take a look at these and get back to you.

Best Regards,
Tommi Välikangas

**Comment by Kayla-Morrell** [comment]
@tsvali - Just checking in to see if there has been any progress made on the review I posted. We generally like to see changes made in 2-3 weeks to be sure the package is actively being work on. Please keep in mind that the deadline to accept new packages into the Bioconductor 3.15 release is 4/20. Any packages accepted after this date will be included in the next release.

Best,
Kayla

**Comment by tsvali** [comment]
@Kayla-Morrell 

Thank you for checking up and for the heads up. Unfortunately, I have been unable to work with this package lately. I will get back to this and try to resolve these issues as soon as possible. 

Best,
Tommi

**Comment by tsvali** [comment]
Dear @Kayla-Morrell

We have now implemented most of the requested modifications to our RolDE package:

> ## General package development
> * [x]  REQUIRED: The installation instructions in the README file should also
>   include Bioconductor installation instructions.
> 
> ## DESCRIPTION
> * [x]  SUGGESTION: Since you are using a standard license and don't use 'file
>   LICENSE' in the 'License:' field this file can be removed from your package.
> * [x]  REQUIRED: 'LazyData:' should be set to false or removed.
> * [x]  REQUIRED: Update the R version dependency from 3.1.0 to 4.2.0 since this
>   is the current version of R that is used with the devel version of
>   Bioconductor.
> 
> ## NEWS
> * [x]  SUGGESTION: Consider adding a NEWS file so your package news will be
>   included in Bioconductor release announcements.
> 
> ## Data
> * [x]  REQUIRED: If possible, add more information about creation and/or source
>   for data1, des_matrix1, des_matrix2, des_matrix3, res1, and res3.
> 
> ## Vignette
> * [ ]  REQUIRED: There are code blocks that are set to `eval = FALSE`. We require
>   most code blocks (except for installation instructions) to be executable.

The code blocks in the vignette with eval = FALSE include code for running RolDE on example data sets. The evaluation of these code chunks could take several minutes (up to 5-10 depending on the used hardware) and are thus set to FALSE in the interest of saving time when compiling the vignette. Instead, the results of these operations are included in the RolDE package and used in the vignette. We hope this would be ok. 

> * [ ]  SUGGESTION: We encourage the use of the `BiocStyle` package for vignette
>   formatting.

Thank you for this suggestion. We will famialiarize ourselves more with the BiocStyle package and hope to implement this style change in the future. 

> * [x]  REQUIRED: There should be an 'Installation' section that shows the users
>   how to download and load the package from Bioconductor. These instructions
>   should be in an `eval = FALSE` code chunk.
> * [x]  SUGGESTION: We strongly encourage a table of contents.
> * [x]  REQUIRED: Only the source vignette file (.Rnw or .Rmd) and any necessary
>   static images should be in the vignette directory. The .html file should be
>   removed.
> 
> ## Man pages
> * [x]  SUGGESTION: Rd files 'RolDE.Rd' and 'RolDE_Main.Rd' the \examples lines
>   are wider than 100 characters. These lines will be truncated in the PDF
>   manual, so you should consider fixing them.
> 
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them. See
>   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

Thank you very much for this suggestion. This is something we hope to add to the package in the future after careful planning of the required and useful unit tests. 

> ## R code
> * [x]  REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead.
> * [x]  REQUIRED: Use various `apply` functions instead of `for` loops. See the
>   section in our documentation about vectorization, see here:
>   https://contributions.bioconductor.org/r-code.html#r-code-development.

We have now replaced most of the for loops with various apply functions. However, some more complex for loops could not be replaced without seriously compromising the functionality of the method, thus these for loops were not modified. 

> * [x]  REQUIRED: Avoid `cat` outside of `show` method.
> * [x]  REQUIRED: Avoid using `=` for assignment and use `<-` instead.
> * [x]  REQUIRED: Avoid redundant `stop` and `warn*` in signal conditions.
> * [x]  REQUIRED: Avoid `suppressWarnings`/`*Messages` if possible.
> * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 679
>   lines that are > 80 characters long.

We thank you for this suggestion. This suggestions was not implemented at this point but will be considered in the future. 

> * [x]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
>   indents. There are 973 lines that are not.

Best Regards,
Tommi Välikangas

**Comment by Kayla-Morrell** [comment]
@tsvali - Thank you for making the necessary changes. You marked off that there was an Installation section added to the vignette but I don't see this change made. Once this is fixed I'll be able to accept the package.

Best,
Kayla

**Comment by tsvali** [comment]
> @tsvali - Thank you for making the necessary changes. You marked off that there was an Installation section added to the vignette but I don't see this change made. Once this is fixed I'll be able to accept the package.
> 
> Best, Kayla

@Kayla-Morrell Thank you for spotting this. It must have gotten lost in the process. I have now updated the vignette to include the installation section and the Bioconductor installation instructions. 

Best,
Tommi

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tsvali.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RolDE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RolDE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
