### ISSUE TITLE
MetaboAnnotation

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#2443]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rformassspectrometry/MetaboAnnotation

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jorainer** [comment]
Just to let you know Herve (@hpages), errors and warnings are now fixed. 
Looking forward to your review and feedback.

**Comment by hpages** [comment]
Hi @jorainer , sorry for the long delay. I'm looking at the package now.

**Comment by hpages** [comment]
Ok, I finally managed to look at **MetaboAnnotation**. Sorry again for the delay.

Package looks good. It's carefully crafted and it's clear that a lot of effort went into it. Some minor cosmetic details only:

1. Rmd vignette contains:
    ```
    package: MetaboCoreUtils
    ```
    Should be:
    ```
    package: MetaboAnnotation
    ```

2. Using direct slot access in user-visible code (e.g. `mo@matches` in `?Matched`) is strongly discouraged. You have a `matches()` accessor for this, why not use it?

3. Have you considered using a Hits object instead of a data.frame for the `matches` slot of a Matched object?

4. The class definitions of MatchedSummarizedExperiment and MatchedSpectra should over-specify the slots provided by their parent Matched. Right now the slot specifications for these two classes are exactly the same as in their parent:
    ```
    > showClass("MatchedSummarizedExperiment")
    Class "MatchedSummarizedExperiment" [package "MetaboAnnotation"]

    Slots:
                                                             
    Name:       query     target    matches   metadata    version
    Class:        ANY        ANY data.frame       list  character

    Extends: "Matched"

    > showClass("MatchedSpectra")
    Class "MatchedSpectra" [package "MetaboAnnotation"]

    Slots:
                                                                 
    Name:       query     target    matches   metadata    version
    Class:        ANY        ANY data.frame       list  character
    
    Extends: "Matched"
    ```
    but if you do:
    ```
    setClass(
      "MatchedSummarizedExperiment",
      contains = "Matched",
      slots = c(query="SummarizedExperiment")   
    )
   ```
    then you get:
    ```
    > showClass("MatchedSummarizedExperiment")
    Class "MatchedSummarizedExperiment" [package "MetaboAnnotation"]

    Slots:
                                                                     
    Name:                 query               target              matches
    Class: SummarizedExperiment                  ANY           data.frame
                                                
    Name:              metadata              version
    Class:                 list            character
    
    Extends: "Matched"
    ```
    and you no longer need to use a validity method to enforce the type of the `query` slot.
    Note that this approach is simpler, cleaner, and it allows `showClass("MatchedSummarizedExperiment")`
    to produce a more informative output. Another positive side effect is that it fixes
    `new("MatchedSummarizedExperiment")` (right now this returns an invalid object which can sometimes
    cause problems in the context of extending MatchedSummarizedExperiment).

5. The `CompareSpectraParam` examples produce many warnings:
    ```
    'filterPrecursorMz' is deprecated. Please use 'filterPrecursorMzRange' instead.
    ```
    26 in total. The warnings seem to originate from the various calls to `matchSpectra()`. I see the same warnings in the compiled vignette.

Thanks,
H.

**Comment by jorainer** [comment]
Hi Herve @hpages ! Thanks for the review! I've addressed all your comments (see https://github.com/rformassspectrometry/MetaboAnnotation/commit/1651b163bd92e58b16023a8569d99def95cdc36d). Regarding point 3, no, haven't checked the `Hits` class, but that's a good suggestion. I'll look into it. 

We've got now WARNINGS that I however don't really understand, but maybe you can help here: we're getting:

```
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import ProtGenerics in NAMESPACE as well as DESCRIPTION.
```

But `ProtGenerics` **is** in `Imports:` in the DESCRIPTION **and** in the NAMESPACE. So I don't know how to solve this.

**Comment by hpages** [comment]
I don't understand this warning either. Maybe @LiNk-NY or @lshep can help? Thx

**Comment by LiNk-NY** [comment]
Hi Johannes, @jorainer 
Thanks for pointing this out. It looks like a bug in `BiocCheck`. It should be fixed in `1.31.29`. 
Best,
Marcel

**Comment by hpages** [comment]
Thanks Marcel.

Package is good to go.

H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MetaboAnnotation")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaboAnnotation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
