### ISSUE TITLE
TEKRABber submission

### ISSUE THREAD

**Issue by ferygood** [Bioconductor/Contributions#2446]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ferygood/TEKRABber

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
In R CMD check:
```
Files named as vignettes but with no recognized vignette engine:
   'vignettes/TEKRABber.Rmd'
(Is a VignetteBuilder field missing?)
```
Also you are using multisample matrices for which SummarizedExperiment design is intended.  Please use SummarizedExperiment in your package.  Get in touch on slack if there are questions.

**Comment by ferygood** [comment]
Dear Vince,

Thank you very much for your time reviewing my package. I have fixed the "VignetteBuilder" message in R CMD check. I also arrange the data which has the same row names into a SummarizedExperiment object. Please have a look, and if you have further questions/suggestions, please let me know. Many thanks!

Best,
Yao-Chung

**Comment by vjcitn** [comment]
You've made a fair amount of progress achieving the interoperability condition.  Now I'd like to consider one more issue.  The man page for speciesCorr in the package reads
```
     Dataset contains 2 normalized data from human and chimpanzee
     RNA-seq data. For a quick demo, here we only subset a

Usage:

     speciesCorr
     
Format:

     A data list with 2 expression counts:

     geneCorr containing gene expression data from human and chimpanzee

     teCorr containing TE expression data from human and chimpanzee

```
The description is an incomplete sentence.  But in addition to this I think we would like to see if code like 
```
hmGeneCorrInput <- assay(speciesCorr$geneCorr[, speciesCorr$geneCorr$Species=="human"])
hmTECorrInput <- assay(speciesCorr$teCorr[, speciesCorr$teCorr$Species=="human"])
chimpGeneCorrInput <- assay(speciesCorr$geneCorr[, speciesCorr$geneCorr$Species=="chimpanzee"])
chimpTECorrInput <- assay(speciesCorr$teCorr[, speciesCorr$teCorr$Species=="chimpanzee"])
```
can be avoided -- multiple dollar signs on a line are not forbidden but are very clumsy.  Since the combination of expression and TE data will be a common event for users, you might consider creating a class that can help increase reliability of data combination, and methods on class instances that produce the data representations useful for analysis.   See the next comment.

**Comment by vjcitn** [comment]
Here is some boilerplate code that should run:
```
setClass("TekSet", slots=c(geneSE="SummarizedExperiment",
  teSE="SummarizedExperiment"))

setGeneric("geneSE", function(x) standardGeneric("geneSE"))
setGeneric("teSE", function(x) standardGeneric("teSE"))
setMethod("geneSE", "TekSet", function(x) x@geneSE)
setMethod("teSE", "TekSet", function(x) x@teSE)

avail_species = function(teset) {
  c(unique(geneSE(teset)$Species), unique(teSE(teset)$Species))
}

setMethod("show", "TekSet", function(object) {
 spec = avail_species(object)
 cat(sprintf("TekSet instance for species %s and %s.\n",
       spec[1], spec[2]))
})

TekSet = function(gse, tse) {
  new("TekSet", geneSE=gse, teSE=tse)
}

setValidity("TekSet", function(object) {
  tst = all(colnames(geneSE(object))==colnames(teSE(object)))
  if (!tst) return("colnames don't agree")
  gcdn = names(colData(geneSE(object)))
  tcdn = names(colData(teSE(object)))
  if (!("Species" %in% gcdn)) return("no 'Species' variable in colData(geneSE)")
  if (!("Species" %in% tcdn)) return("no 'Species' variable in colData(teSE)")
  tst
})
```

It is a bit cumbersome, but let's consider the payoff.  We start by constructing the formal
object from your list:

```
myobj = TekSet(speciesCorr$geneCorr, speciesCorr$teCorr)
```
The show method gives us a compact report -- you could enhance this by adding output concerning numbers of samples and features...
```
> myobj
TekSet instance for species human and chimpanzee.
```
Our validity method verifies some conditions on our object:
```
> validObject(myobj)
[1] TRUE
```
This guards the user against certain mistakes ...
```
> myobj = TekSet(speciesCorr$geneCorr, speciesCorr$teCorr[,1:10])
Error in validObject(.Object) : 
  invalid class "TekSet" object: colnames don't agree

Enter a frame number, or 0 to exit   

1: TekSet(speciesCorr$geneCorr, speciesCorr$teCorr[, 1:10])
2: #2: new("TekSet", geneSE = gse, teSE = tse)
3: initialize(value, ...)
4: initialize(value, ...)
5: validObject(.Object)
```
Our function for extracting the quantifications now hides all the dollar signs:
```
> dim(assay_by_species(myobj, "te", "human"))
[1] 50 10
> dim(assay_by_species(myobj, "te", "chimpanzee"))
[1] 50 10
```
and it was programmed defensively:
```
> dim(assay_by_species(myobj, "te", "chimp"))
Error in assay_by_species(myobj, "te", "chimp") : 
  species %in% avail_species(object) is not TRUE

Enter a frame number, or 0 to exit   

1: assay_by_species(myobj, "te", "chimp")
2: #3: stopifnot(species %in% avail_species(object))

Selection: 0
```

**Comment by vjcitn** [comment]
You can change the name of the class or follow this strategy in other directions.  But I do think something should be done to reduce the complexity of code in the vignette.

**Comment by ferygood** [comment]
Dear Vince,

I have updated TEKRABber repo:
(1) Create a **TekCorrSet** class object to contain the input files for running the vignette. All dollars signs are hidden and it looks neater now. 
(2) A new function `assay_tekcorrset()` is added to access TekCorrSet class object for running the vignette.
(3) I also check the sentences in documentation files (function, and data).

Thank you very much for your advice and the boilerplate code which helps me a lot. Please have a look at the latest version. If you have further questions, please let me know. 

Best,
Yao-Chung

**Comment by vjcitn** [comment]
Thanks.  The package will go into the review cycle.  You should hear in the next week or so how the build system has handled it.

**Comment by ferygood** [comment]
@HelenaLC 
Dear Helena,
I have built my package on Bioconductor server with no errors and warnings last week. Could you let me know when you have time to take a look at my package? 
Many thanks!

Best,
Yao-Chung

**Comment by HelenaLC** [comment]
# README

- [ ] Please include Bioconductor installation instructions using `BiocManager`.

# DESCRIPTION

- [ ] We would encourage an R dependency of >= 4.2.

- [ ] We recommend `lazyData: false` as setting it to `true`  
is rarely useful and could slow package installation.

- [ ] Consider adding a `URL:` field pointing to the code repo,  
and a `BugReports:` field for reporting issues (e.g., to Github)

- [ ] The `Description:` might be worth expanding, and there are  
various typos and grammar mistakes that should be fixed.

# documentation

- [ ] The package help page (`?TEKRABber`) currently  
contains only a template and no actual information.

- [ ] In the corresponding man pages, please add details on  
how the toy data were generated (perhaps the code for this?),  
and on the source information for data that is not synthetic.

- [ ] Have you considered using `roxygen2` for imports/exports?  
Currently, you are importing all dependencies *in full*.  
We would encourage importing only selected functionality  
(e.g., using `@importFrom`) to avoid namespace conflicts.  

- [ ] In addition to the above, I'd strongly recommend considering  
making the app part of the package *optional* by placing all related code  
in the `inst` directory and including all related dependencies as  
`suggests` (vs. `depends`) in the DESCRIPTION. For an example, see [here](https://github.com/HelenaLC/CATALYST/tree/RELEASE_3_8/inst/shinyGUI).  
The advantage of this would be that users could install a light-weight version  
of the package if they're only interested in script-based (non-interactive) analysis.

# vignettes/

- [ ] It would be nice to hyperlink any packages you mention. E.g., `r Biocpkg("biomaRt")`  
(`BiocStyle` has similar commands for CRAN and GitHub packages)

- [ ] Especially in the vignette, please try to keep to an 80 character limit  
as the code will otherwise be difficult to read when displayed online.

# R/

- `assay_tekcorrset()` is defined for class `TekCorrSet`, but I cannot  
see where this class is defined / coming from. Could you please clarify?

- [ ] Various parts of examples are currently commented out; this is  
equivalent to a "don't run" tag, which would appear in the build report.  
Please make runnable examples (i.e., uncomment all code)  
and use comments for descriptive purposes only.

- [ ] Please do consider adding unit-tests, we strongly encourage them (see [here](http://bioconductor.org/developers/how-to/unitTesting-guidelines)).

- [ ] Avoid using `"directory/file_name"` (or similar) as this isn't operating system-agnostic  
(Windows uses `\`!), and use `file.path("directory", "file_name")` instead.  
I think this needs fixing in `corrOrthologTE.R`, `DECorrInputs.R`, and `DEgeneTE.R`. 

- [ ] In addition to the comment above, it might be worth providing users with  
the option to not write results to a file at all, but instead just return them  
(e.g., when the specified output file name / directory is `NULL` or similar).  
As it stands, many functions will force writing results to files.

- [ ] For all affected functions, I'd highly recommend adding an argument  
to let users specify where outputs should be written to vs. hard-coding  
the creation of a `results/` directory in the current working directory.  
E.g., users might want to write files to a different location,  
or provide a more meaningful directory name for their analysis.

- [ ] Please see the build report NOTE instances;  
all of these should be tried to be addressed. For example,  
avoid the use of `1:...` and use `c()` or `seq_len/along` instead (e.g., in  
`corrOrthologTE.R`: `[1:2] -> c(1, 2)`, `c(1:nrow(.)) -> seq_len(nrow(.))`)

- [ ] The code in `DEgeneTE.R` is highly repetitive and would be worth simplifying.  
For example, `write.table`s and `output` are identical and could be placed outside  
the `if ... else`, which only needs to determine how `gene/teDE` are computed,  
and whether or not to create a directory for the output results.

- [ ] There are currently many build report NOTES stating  
"no visible binding for" that are due to non-standard `dplyr` evaluation.  
`dplyr` itself is also "heavy" (large number of dependencies).  
It would be worth considering rewriting the code as to  
omit `dplyr` as a dependencies by using base R syntax instead.  
In many cases, this would also greatly simplify the code.  
To give a couple examples:

```{r}
# in othologScale.R:
geeCountRef <- geneCountRef %>%
  mutate(refMean = rowMeans(select(., 2:ncol(geneCountRef))))
  
# could be rewritten as:
idx <- seq_len(ncol(geneCountRef))[-1]
sub <- geneCountRef[, idx]
geneCountRef$refMean <- rowMeans(sub)

# in corrOrthologTE.R
df.corr <- df.corr %>%
  mutate(padj = p.adjust(pvalue, method=padjMethod))
  
# could be rewritten as:
df.corr$padj <- p.adjust(
  df.corr$pvalue, 
  method=padjMethod)
```

Note that many of the above are suggestions and not strictly required (e.g., "consider..."). Please comment back here with what has been addressed or any comments regarding any needed clarification or questions you might have. Cheers!

**Comment by ferygood** [comment]
> # README
> * [x]  Please include Bioconductor installation instructions using `BiocManager`.

The instruction using `BiocManager::install()` is added. 

> # DESCRIPTION
> * [x]  We would encourage an R dependency of >= 4.2.

Currently, the latest version of R is 4.1.2 (Bird Hippie). I have checked the version and set it as R( >= 4.1) based on the guideline only keeping the first two digits. 

> * [x]  We recommend `lazyData: false` as setting it to `true`
>   is rarely useful and could slow package installation.

I have changed lazyData from true to `false`.

> * [x]  Consider adding a `URL:` field pointing to the code repo,
>   and a `BugReports:` field for reporting issues (e.g., to Github)

The URLs of code repo and BugReports are added.

> * [x]  The `Description:` might be worth expanding, and there are
>   various typos and grammar mistakes that should be fixed.

Sorry for the inconvenience of typos and grammar mistakes. I have added more information and checked the typos in the Description field. 

> # documentation
> * [x]  The package help page (`?TEKRABber`) currently
>   contains only a template and no actual information.

The help page is added. It can be accessed with `?TEKRABber` now.

> * [x]  In the corresponding man pages, please add details on
>   how the toy data were generated (perhaps the code for this?),
>   and on the source information for data that is not synthetic.

I have described the methods of how we generated the data, including which bioinformatics tools we used. The source information is now synthetic. 
At the moment, there are various methods to estimate the gene/TE from RNA-seq data and it can be decided on preferences before using TEKRABber. However, we would like to consider providing the codes in the future as a reference for users. I suppose it will be a Snakemake/Nextflow pipeline. 

> * [x]  Have you considered using `roxygen2` for imports/exports?
>   Currently, you are importing all dependencies _in full_.
>   We would encourage importing only selected functionality
>   (e.g., using `@importFrom`) to avoid namespace conflicts.

I have changed the importing methods with roxygen2 tags to import only selected methods. The namespace conflicts issues are now solved.

> * [x]  In addition to the above, I'd strongly recommend considering
>   making the app part of the package _optional_ by placing all related code
>   in the `inst` directory and including all related dependencies as
>   `suggests` (vs. `depends`) in the DESCRIPTION. For an example, see [here](https://github.com/HelenaLC/CATALYST/tree/RELEASE_3_8/inst/shinyGUI).
>   The advantage of this would be that users could install a light-weight version
>   of the package if they're only interested in script-based (non-interactive) analysis.

Thanks for sharing an example! I have moved the app content to inst/ directory. The dependencies are now at the Suggests. So it is now optional to download the dependencies. 

> # vignettes/
> * [x]  It would be nice to hyperlink any packages you mention. E.g., `r Biocpkg("biomaRt")`
>   (`BiocStyle` has similar commands for CRAN and GitHub packages)

The packages from Bioconductor are all mentioned with hyperlinks using BiocStyle::Biocpkg().

> * [x]  Especially in the vignette, please try to keep to an 80 character limit
>   as the code will otherwise be difficult to read when displayed online.

Some of the parameters have long names for clearness. I have managed the lengths of code less than 80 characters limit. 


> # R/
> * `assay_tekcorrset()` is defined for class `TekCorrSet`, but I cannot
>   see where this class is defined / coming from. Could you please clarify?

Yes, of course. TekCorrSet class is only defined for running examples in the vignettes (TEKRABber.Rmd). The reason was I accessed count data by multiple dollar signs $ from a dataframe in the previous version. Vince suggested that I used a SummarizedExperiment Class to avoid this issue. 
Both TekCorrSet and assay_tekcorrset() will not affect the usage of others when they are running their own sample. They can decide the format for saving their data based on their preferences. 

> * [x]  Various parts of examples are currently commented out; this is
>   equivalent to a "don't run" tag, which would appear in the build report.
>   Please make runnable examples (i.e., uncomment all code)
>   and use comments for descriptive purposes only.

I have uncommented the codes and added some of them with `donottest` tags. The reason is that the initialization step (orthologScale function) querying ortholog information from BioMart is a time-consuming step and depends on the internet connection. Therefore, the examples required for this step are added with `donnottest` tags.  

> * [x]  Please do consider adding unit-tests, we strongly encourage them (see [here](http://bioconductor.org/developers/how-to/unitTesting-guidelines)).

I have started to add unit tests for my functions. I will keep adding them when I encounter bugs for future updates.

> * [x]  Avoid using `"directory/file_name"` (or similar) as this isn't operating system-agnostic
>   (Windows uses `\`!), and use `file.path("directory", "file_name")` instead.
>   I think this needs fixing in `corrOrthologTE.R`, `DECorrInputs.R`, and `DEgeneTE.R`.

I have added a parameter called `fileDir` to these functions and also a `fileName` for corrOrthologTE.R. These two changes now let users decide if they want to save the results based on their preference. The slash symbol is now replaced by using the `file.path()` function to avoid issues on different OS.

> * [x]  In addition to the comment above, it might be worth providing users with
>   the option to not write results to a file at all, but instead just return them
>   (e.g., when the specified output file name / directory is `NULL` or similar).
>   As it stands, many functions will force writing results to files.

Same as above, the default now is to only return the results. If users want to save their results, they can specify with the new-added parameters, `fileDir` and `fileName`.

> * [x]  For all affected functions, I'd highly recommend adding an argument
>   to let users specify where outputs should be written to vs. hard-coding
>   the creation of a `results/` directory in the current working directory.
>   E.g., users might want to write files to a different location,
>   or provide a more meaningful directory name for their analysis.

As previously mentioned, I decided to add new parameters instead of creating a directory for the users if they want to save their results.

> * [x]  Please see the build report NOTE instances;
>   all of these should be tried to be addressed. For example,
>   avoid the use of `1:...` and use `c()` or `seq_len/along` instead (e.g., in
>   `corrOrthologTE.R`: `[1:2] -> c(1, 2)`, `c(1:nrow(.)) -> seq_len(nrow(.))`)

I have tried to address NOTEs from the build report. However, there are still several NOTEs which I think I can keep at the moment. For example, (1) there are some functions that are more than 50 lines which I do not think is reasonable to split into multiple smaller functions. (2) The long affiliation starting from the vignettes is decided with my supervisor. If I make an indentation, the vignettes builder will not able to knit it. (3) I did not include a runnable example in the Shiny function because it needs to repeat all the previous functions to get the same inputs. 

> * [x]  The code in `DEgeneTE.R` is highly repetitive and would be worth simplifying.
>   For example, `write.table`s and `output` are identical and could be placed outside
>   the `if ... else`, which only needs to determine how `gene/teDE` are computed,
>   and whether or not to create a directory for the output results.

Yes, it was highly repetitive. I have replaced the conditional repetitive parts of the content (from 89 lines to 62 lines). Users can also decide if they want to create a directory for saving their results by the new parameter `fileDir`.

> * [x]  There are currently many build report NOTES stating
>   "no visible binding for" that are due to non-standard `dplyr` evaluation.
>   `dplyr` itself is also "heavy" (large number of dependencies).
>   It would be worth considering rewriting the code as to
>   omit `dplyr` as a dependencies by using base R syntax instead.
>   In many cases, this would also greatly simplify the code.
>   To give a couple examples:
> 
> ```
> # in othologScale.R:
> geeCountRef <- geneCountRef %>%
>   mutate(refMean = rowMeans(select(., 2:ncol(geneCountRef))))
>   
> # could be rewritten as:
> idx <- seq_len(ncol(geneCountRef))[-1]
> sub <- geneCountRef[, idx]
> geneCountRef$refMean <- rowMeans(sub)
> 
> # in corrOrthologTE.R
> df.corr <- df.corr %>%
>   mutate(padj = p.adjust(pvalue, method=padjMethod))
>   
> # could be rewritten as:
> df.corr$padj <- p.adjust(
>   df.corr$pvalue, 
>   method=padjMethod)
> ```
> 
> Note that many of the above are suggestions and not strictly required (e.g., "consider..."). Please comment back here with what has been addressed or any comments regarding any needed clarification or questions you might have. Cheers!

I have replaced most of the dplyr functions with base functions as you suggested to release heavy dependencies. Now my package is much "thinner" now. 

Thank you for all of the suggestions. Looking forward to your feedback. 

Best,
Yao-Chung

**Comment by HelenaLC** [comment]
Looking good. Thanks for all this! Only a few comments left (I think) that could (minor) or should (major) be addressed (again, most of these are suggestions for improvements / better coding practices):

**minor:**

- [ ] Please add an example in `appTEKRABber`  
demonstrating how to launch the app.

- [ ] The example of `DECorrInputs.R` is not runnable due to  
`hmTE` being undefined; should set `hmTE <- speciesCounts$hmTE`.

- [ ] While you have minimized `dplyr` usage, it is still a dependency.  
There are only very few lines now that could easily be rewritten.  
I'd recommend this as to not depend on `dplyr` for so little usage.
  - in `DECorrInputs.R` and `orhologScale.R`,  
  `inner_join` could be replaced by base R's `merge`
  - in `DECorrInputs.R`:

```r
geneCountCompare <- geneCountCompare %>%
  mutate(across(2:ncol(geneCountCompare), norm_scale))
# could be written as...
# (analogous for 'teCountCompare')
for (i in seq_len(ncol(geneCountCompare)[-1])
  geneCountCompare[, i] <- norm_scale(geneCountCompare[, i])
```

- [ ] For readability & robustness, I'd suggest refraining from  
indexing by position, and to instead index by name.  
This appears in many places, here's just one example:     

```r
# DECorrInputs.R
orthologTable_ID <- orthologTable[, c(3,7)]
# could be...
i <- c("refEnsemblID", "compareEnsemblID")
orthologTable_ID <- orthologTable[, i]
```

- [ ] Similarly, some could is overly complicated  
and could be greatly simplified:

```r
refCount <- ncol(geneCountRef[, 2:ncol(geneCountRef)])
# could be...
refCount <- ncol(geneCountRef)-1
```

- [ ] Thanks for putting in some unit tests and planning to add  
more over time! For now, perhaps consider adding some for  
`orthologScale` as there are currently none:

```r
# devtools::test_coverage()
TEKRABber Coverage: 54.55%
R/appTEKRABber.R: 0.00%
R/orthologScale.R: 0.00%
R/assay_tekcorrset.R: 45.83%
R/DEgeneTE.R: 68.97%
R/corrOrthologTE.R: 84.62%
R/DECorrInputs.R: 100.00%
src/rcpp_corr.cpp: 100.00%
```

**major:**

- Having `dontrun` examples is far from optimal.  
Each time the package is being build (e.g., when there's a bug fix),  
these will be run as part of the checks. At the moment,  
any failures will be missed (e.g., see 1st comment above).
  - [ ] The `corrOrthologTE` example runs in less than a second for me  
and is not dependent on internet-connection; please remove `dontrun`  
(and set `fileDir = NULL` as to not generate an output file).
  - [ ] If `orhologScale` is the bottleneck here, have you considered  
saving it's output inside the package? Then, downstream examples  
could simply load the results without having to re-run `orhologScale`.  
I think you have done this for the `DEgeneTE` example already?  
(Specifically, once the `corrOrhologTE` example is runnable,  
`DECorrInputs` has a `dontrun` left; besides `orthologScale`)

**Comment by ferygood** [comment]
> Looking good. Thanks for all this! Only a few comments left (I think) that could (minor) or should (major) be addressed (again, most of these are suggestions for improvements / better coding practices):
> 
> **minor:**
> 
> * [x]  Please add an example in `appTEKRABber`
>   demonstrating how to launch the app.

I have added an example in `appTEKRABber.R` to show the inputs and how to launch the app. 

> * [x]  The example of `DECorrInputs.R` is not runnable due to
>   `hmTE` being undefined; should set `hmTE <- speciesCounts$hmTE`.

This bug is fixed and it will not return an error when running `R CMD check`.

> * [x]  While you have minimized `dplyr` usage, it is still a dependency.
>   There are only very few lines now that could easily be rewritten.
>   I'd recommend this as to not depend on `dplyr` for so little usage.
>   

All of the `dplyr` dependencies were removed. It feels a little bit strange at first, but I agree with you replacing them with base functions.

>   * in `DECorrInputs.R` and `orhologScale.R`,
>     `inner_join` could be replaced by base R's `merge`
>   * in `DECorrInputs.R`:
> 
> ```r
> geneCountCompare <- geneCountCompare %>%
>   mutate(across(2:ncol(geneCountCompare), norm_scale))
> # could be written as...
> # (analogous for 'teCountCompare')
> for (i in seq_len(ncol(geneCountCompare)[-1])
>   geneCountCompare[, i] <- norm_scale(geneCountCompare[, i])
> ```
> 

Thank you for providing me with some examples of this. It makes me more easily understand the idea.

> * [x]  For readability & robustness, I'd suggest refraining from
>   indexing by position, and to instead index by name.
>   This appears in many places, here's just one example:
> 
> ```r
> # DECorrInputs.R
> orthologTable_ID <- orthologTable[, c(3,7)]
> # could be...
> i <- c("refEnsemblID", "compareEnsemblID")
> orthologTable_ID <- orthologTable[, i]
> ```
> 

I have replaced indices with column names to improve code-reading. By using column names, it is now much easier to go through each line of code.

> * [x]  Similarly, some could is overly complicated
>   and could be greatly simplified:
> 
> ```r
> refCount <- ncol(geneCountRef[, 2:ncol(geneCountRef)])
> # could be...
> refCount <- ncol(geneCountRef)-1
> ```
> 

I did not realize the complicated structure at first. Thank you for the suggestions. They are all modified.

> * [x]  Thanks for putting in some unit tests and planning to add
>   more over time! For now, perhaps consider adding some for
>   `orthologScale` as there are currently none:
> 
> ```r
> # devtools::test_coverage()
> TEKRABber Coverage: 54.55%
> R/appTEKRABber.R: 0.00%
> R/orthologScale.R: 0.00%
> R/assay_tekcorrset.R: 45.83%
> R/DEgeneTE.R: 68.97%
> R/corrOrthologTE.R: 84.62%
> R/DECorrInputs.R: 100.00%
> src/rcpp_corr.cpp: 100.00%
> ```
> 

The first step of `orthologScale()` is to query orthology information from BioMart based on the species selected by users. However, I found out the connection to BioMart via `biomaRt::useEnsembl()` has the chance to fail due to maintenance.  `test-orthologScale.R` was added for unit tests. I have already reduced the input size and the test can be finished around 2-4 minutes. Though it still has the chance to fail if all of the mirrors of BioMart are under maintenance. I have checked if the connection is okay, `R CMD check` and `testthat:test()` should work without errors.

> **major:**
> 
> * Having `dontrun` examples is far from optimal.
>   Each time the package is being build (e.g., when there's a bug fix),
>   these will be run as part of the checks. At the moment,
>   any failures will be missed (e.g., see 1st comment above).
>   
>   * [x]  The `corrOrthologTE` example runs in less than a second for me
>     and is not dependent on internet-connection; please remove `dontrun`
>     (and set `fileDir = NULL` as to not generate an output file).

The example is modified by removing the `donttest` tag and setting `fileDir=NULL`.

>   * [x]  If `orhologScale` is the bottleneck here, have you considered
>     saving it's output inside the package? Then, downstream examples
>     could simply load the results without having to re-run `orhologScale`.
>     I think you have done this for the `DEgeneTE` example already?
>     (Specifically, once the `corrOrhologTE` example is runnable,
>     `DECorrInputs` has a `dontrun` left; besides `orthologScale`)

All of the `dontrun` and `donttest` tags are removed. Yes, I have prepared the output for letting the user run the vignettes if they do not want to wait for the query steps. The bottleneck is if the connection failed due to internet or maintenance issues, tests including steps using `orthologScale()` will also return an error. At this moment, I provide relatively small datasets to make sure `orthologScale()` passes the test within 2-4 minutes. However, I do not know when all the mirrors of BioMart will be maintained. As the developer, I can still distinguish the problem is from my code or the internet. I have also mentioned this situation in the vignettes and documentation for users if they encounter BioMart maintenance. 

Thank you for all the major/minor suggestions. Looking forward to hearing from you!

**Comment by HelenaLC** [comment]
Hey there. Thanks for all this, especially having made example runnable and thus testable by the regular builds. Two very minor comments. Once these are resolved, I will accept the package:

**1)** For clarity, could you remove `fileName = "correlationResult.csv"` in the `corrOrhologTE` example? Since `fileDir = NULL` and the example does not produce an output file, I think removing the argument would avoid confusion.

**2)** As you can see in the build report, there's a NOTE regarding the assignment of global variables by `appTEKRABber`. Generally, it is bad practice for functions to have side-effects such as touching the global environment. I have done some research and indeed, could not find a proper alternative for this as a `Shiny` app that is run via `runApp` will have `global.R` access the global environment only (independent of, e.g., explicitly calling `runApp` inside another environment). 

So, I think it would be sensible to i) remove all of the `assign`s in `appTEKRABber` and ii) instead ask users to specify the required variable before calling it. E.g., the user should explicitly set `appDE/Ref/Compare/Meta`. Does that make sense? Feel free to ask for clarification if it isn't.

Note that, from a user-perspective, there's no loss here in terms of effort:
```
# pass arguments
appTEKRABber(
  DEresult = hmchimpDE,
  corrRef = hmCorrResult,
  corrCompare = chimpCorrResult,
  metadata = meta)
  
# vs. pre-set required variable
appDE <- hmchimpDE
appRef <- hmCorrResult
appCompare <- chimpCorrResult
appMeta <- meta
appTEKRABber()
```

**Comment by ferygood** [comment]
> Hey there. Thanks for all this, especially having made example runnable and thus testable by the regular builds. Two very minor comments. Once these are resolved, I will accept the package:
> 
> **1)** For clarity, could you remove `fileName = "correlationResult.csv"` in the `corrOrhologTE` example? Since `fileDir = NULL` and the example does not produce an output file, I think removing the argument would avoid confusion.
> 

I have removed the `fileName` parameters from the example. It will be more clear for users when they are reading the document.

> **2)** As you can see in the build report, there's a NOTE regarding the assignment of global variables by `appTEKRABber`. Generally, it is bad practice for functions to have side-effects such as touching the global environment. I have done some research and indeed, could not find a proper alternative for this as a `Shiny` app that is run via `runApp` will have `global.R` access the global environment only (independent of, e.g., explicitly calling `runApp` inside another environment).
> 
> So, I think it would be sensible to i) remove all of the `assign`s in `appTEKRABber` and ii) instead ask users to specify the required variable before calling it. E.g., the user should explicitly set `appDE/Ref/Compare/Meta`. Does that make sense? Feel free to ask for clarification if it isn't.
> 
> Note that, from a user-perspective, there's no loss here in terms of effort:
> 
> ```
> # pass arguments
> appTEKRABber(
>   DEresult = hmchimpDE,
>   corrRef = hmCorrResult,
>   corrCompare = chimpCorrResult,
>   metadata = meta)
>   
> # vs. pre-set required variable
> appDE <- hmchimpDE
> appRef <- hmCorrResult
> appCompare <- chimpCorrResult
> appMeta <- meta
> appTEKRABber()
> ```

I agree with your suggestion. Previously, I was also searching for solutions and thinking of if I wanted the user to create or assign the variables for them. Though assigning global variables from the functions might seem "neat", it will somehow surprise the user by changing the environment. I have modified `appTEKRABber()` as you suggested:
(1) Ask the user to pre-set all app-prefix variables: `appDE`, `appRef`, `appCompare`, and `appMeta` before running `appTEKRABber()`
(2) Add instructions and modify related codes in vignettes, appTEKRABber.R, and appTEKRABber.Rd

Please have a look, and see if it can be accepted now. 
Many thanks!

**Comment by HelenaLC** [comment]
Yeah, I had thought there'd be a cleaner way, but it seams not. - Looks good! Thank you for considering this as well as putting explanations in both the app doc & vignette!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ferygood.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TEKRABber")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TEKRABber

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
