### ISSUE TITLE
MuData

### ISSUE THREAD

**Issue by gtca** [Bioconductor/Contributions#2453]
- Repository: https://github.com/ilia-kats/MuData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment]
Hi @gtca. Just FYI I will be on leave from next week until 11 January so I probably won't review this until I get back (am excited to have a look at it though!).

**Comment by LiNk-NY** [comment]
Hi Danila, @gtca 

Thank you for your submission.

Please see the review below. 

Best regards,
Marcel

---

# MuData #2453

## DESCRIPTION

* Looks good.

## NAMESPACE

* Please use lowercase for function names i.e., readH5AD, etc. 
(Sentence case functions are commonly used for class constructors)
* Based on the number of functions imported, consider depending on `rhdf5`.

## vignettes

* Do not use `BiocManager::install('MuData')` until the package has been
accepted into Bioconductor.
* Make sure that the temporary GitHub repo location is correct.
* For legibility and maintenance, stick to the 80 character width limit.
* Avoid using non-standard notation with `H5IdComponent` objects e.g.,
`h5&'mod'`, etc. Use `h5ls` instead to show the structure of the file.
* Replace instances where you use `assays`
(`assays(acc_b[["RNASeq2GeneNorm"]])[[1]][1:5,1:3])`)  with `assay`
(`assay(acc_b, "RNASeq2GeneNorm")`)
* Avoid using `print(class(...))` and simply use `class(...)`.

## R

* If `backed = TRUE` and the user does not have `HDF5Array` error and allow
the user to install the package rather than changing the argument to `FALSE`.
* Any reason why `ReadH5AD` is changing the class of the original object?
In the example for `ReadH5AD`,  the original object is a `SummarizedExperiment`
but when it's read in, it becomes a `SingleCellExperiment`. Any user would
expect it to be the same class.
```r
WriteH5AD(miniACC[[1]], "miniacc.h5ad")
sce <- ReadH5AD("miniacc.h5ad")
```
* The data format should not change the class memberships, this also happens
with the `ReadH5MU` function on the `MultiAssayExperiment` where everything
becomes a `SingleCellExperiment`.
* It is recommended to keep the order of the assays the same as the original
`MultiAssayExperiment` after saving and reading.
* Avoid creating methods for classes that are not your own. Create plain
functions for writing classes (`WriteH5MU`) similar to `write_data_frame` and
`write_matrix`. This will avoid cluttering of the class's namespace.
* Preserve the metadata from the original object e.g., `metadata(miniACC)`

## tests

* Consider increasing coverage to your main functions.

```r
> covr::package_coverage()
MuData Coverage: 63.26%
R/read_h5mu.R: 54.97%
R/write_h5mu.R: 68.08%
R/utils.R: 71.74%
```

**Comment by gtca** [comment]
Hey @LiNk-NY, thank you for the useful feedback!

We've addressed most of the bullet points and commented on the rest. If any of these are still critical to be changed in your opinion, we're happy to discuss further and to find ways to address them.

Please let us know what you think!

## NAMESPACE

- [x] Please use lowercase for function names i.e., readH5AD, etc.
- [x] Based on the number of functions imported, consider depending on rhdf5.

## vignettes

- [x] Do not use `BiocManager::install('MuData')` until the package has been accepted into Bioconductor.
- [x] Make sure that the temporary GitHub repo location is correct.
- [x] For legibility and maintenance, stick to the 80 character width limit.
- [x] Avoid using non-standard notation with `H5IdComponent` objects e.g., `h5&'mod'`, etc. Use `h5ls` instead to show the structure of the file. 
- [x] Replace instances where you use `assays` (`assays(acc_b[["RNASeq2GeneNorm"]])[[1]][1:5,1:3])`) with assay
(`assay(acc_b, "RNASeq2GeneNorm")`)
- [x] Avoid using `print(class(...))` and simply use `class(...)`.

## R

- [x] If `backed = TRUE` and the user does not have `HDF5Array` error and allow the user to install the package rather than changing the argument to `FALSE`.

[Now](https://github.com/ilia-kats/MuData/blob/10aebf2e79c1f2117fd30de3dcf5a9d0697cf2d3/R/read_h5mu.R#L113) we simply error out in that case.

> Any reason why `ReadH5AD` is changing the class of the original object?
In the example for `ReadH5AD`, the original object is a `SummarizedExperiment`
but when it's read in, it becomes a `SingleCellExperiment`. Any user would
expect it to be the same class.

The reason is that there is no way to distinguish between those in a general case.

As `.h5ad` / `.h5mu` is a cross-language format intended for data exchange between languages, and we can expect any R-specific information we write would be lost after a roundtrip to [Python](https://github.com/scverse/mudata) or [Julia](https://github.com/scverse/Muon.jl). Thus, having `read` return the same object type regardless of where the `.h5ad` / `.h5mu` file comes from seems actually more consistent.

To go into more details, the logic behind this was making it easier to reason for the user: `readH5AD()` will always return a `SingleCellExperiment` object. We can store the original object type as an attribute or as unstructured information in the file. To note though, as an `.h5ad` / `.h5mu` file can be (and probably is) written from another language, e.g. Python, one cannot expect a file have this information and we'll have to default to e.g. `SingleCellExperiment` in the end. 

In this regard it also seems important to consider that `SingleCellExperiment` is a subclass of `SummarizedExperiment` rather than an unrelated class.

> The data format should not change the class memberships, this also happens
with the `ReadH5MU` function on the `MultiAssayExperiment` where everything
becomes a `SingleCellExperiment`.

Same as above.

- [x] It is recommended to keep the order of the assays the same as the original
MultiAssayExperiment after saving and reading. 

Now the I/O supports the assay order preservation ([→test](https://github.com/ilia-kats/MuData/blob/fe9356a4c9587dd01f46e6f4b438e1539372e6ee/tests/testthat/test_mae_bioc_eg.R#L87)).

> Avoid creating methods for classes that are not your own. Create plain
functions for writing classes (`WriteH5MU`) similar to `write_data_frame` and
`write_matrix`. This will avoid cluttering of the class's namespace.

Implementation of these functions as methods was actually done following the respective feedback from Bioconductor users who worked with earlier versions of this package. While we can change it back to plain functions, should we discuss this point further to figure out which might be best for the end user, considering we also received feedback favouring methods over plain functions?

- [x] Preserve the metadata from the original object e.g., `metadata(miniACC)`

While there's no possibility to (de)serialise arbitrary objects in `metadata` / `.uns` slot, we [implemented](https://github.com/ilia-kats/MuData/commit/fe9356a4c9587dd01f46e6f4b438e1539372e6ee) handling of simple use cases ([→test](https://github.com/ilia-kats/MuData/blob/10aebf2e79c1f2117fd30de3dcf5a9d0697cf2d3/tests/testthat/test_readh5mu.R#L41)).

## tests

- [x] Consider increasing coverage to your main functions.

```r
> covr::package_coverage()
MuData Coverage: 74.69%
R/read_h5mu.R: 71.67%
R/write_h5mu.R: 74.27%
R/utils.R: 85.96%
```

**Comment by LiNk-NY** [comment]
Hi Danila, @gtca 

> > Any reason why ReadH5AD is changing the class of the original object?
In the example for ReadH5AD, the original object is a SummarizedExperiment
but when it's read in, it becomes a SingleCellExperiment. Any user would
expect it to be the same class.

> The reason is that there is no way to distinguish between those in a general case.

If you are writing the file there is a way because you have control of the data and metadata.
You can see some save and load examples in `HDF5Array/R/saveHDF5SummarizedExperiment.R`. 

> As .h5ad / .h5mu is a cross-language format intended for data exchange between languages, and we can expect any R-specific information we write would be lost after a roundtrip to Python or Julia. Thus, having read return the same object type regardless of where the .h5ad / .h5mu file comes from seems actually more consistent.

For this, you can create a general function, e.g., `readH5ADSingleCellExperiment` where the user will know what class will be imported. 

> To go into more details, the logic behind this was making it easier to reason for the user: readH5AD() will always return a SingleCellExperiment object. We can store the original object type as an attribute or as unstructured information in the file. To note though, as an .h5ad / .h5mu file can be (and probably is) written from another language, e.g. Python, one cannot expect a file have this information and we'll have to default to e.g. SingleCellExperiment in the end.

> In this regard it also seems important to consider that SingleCellExperiment is a subclass of SummarizedExperiment rather than an unrelated class.

You can also have a `readH5ADSummarizedExperiment` for those that had a `SummarizedExperiment` to begin with. 

>> Avoid creating methods for classes that are not your own. Create plain
functions for writing classes (WriteH5MU) similar to write_data_frame and
write_matrix. This will avoid cluttering of the class's namespace.

> Implementation of these functions as methods was actually done following the respective feedback from Bioconductor users who worked with earlier versions of this package. While we can change it back to plain functions, should we discuss this point further to figure out which might be best for the end user, considering we also received feedback favouring methods over plain functions?

I would follow the model provided by `HDF5Array` that uses plain functions to save/write. Also, please see https://contributions.bioconductor.org/r-code.html?q=method#methods-development

**Comment by gtca** [comment]
Thanks, @LiNk-NY!

### Preserving the class of the original object

This has now been implemented using HDF5 attributes so that the file format stays compliant with the rest of the ecosystem.
Currently `SummarizedExperiment` and `SingleCellExperiment` object classes are recovered accordingly, and it defaults to `SingleCellExperiment` if no information is in the file, e.g. if the file was written by the Python library.

This is also being tested for, [e.g. here](https://github.com/ilia-kats/MuData/blob/33e82894112f44cf86a6f6d4602151da9cb216ce/tests/testthat/test_readh5mu.R#L20).

This seems to cover the points above regarding the preservation of the class of the original object where possible.

### Write methods

We could change them to multiple if/else clauses instead of using dynamic dispatch, e.g. as [HDF5Array does in the linked function](https://github.com/Bioconductor/HDF5Array/blob/db6b7cf8f7c47ed61182c11e870fdebe16408318/R/saveHDF5SummarizedExperiment.R#L145). We're not sure that is going to result in a cleaner code but that seems to be the way we can refactor the code in if you think this follows the community guidelines better. Just wanted to double-check if that's what you implied? 

And just to leave it as a note here, as we govern the on-disk format, there should be no big problem with method collision, which is mentioned as the major concern in the guidelines above, in other words I see this more of a problem with methods such as `writeSummarisedExperiment()` rather than the ones that specify a particular format as `writeH5MU()`.

**Comment by LiNk-NY** [comment]
> ### Preserving the class of the original object
> This has now been implemented using HDF5 attributes so that the file format stays compliant with the rest of the ecosystem. Currently `SummarizedExperiment` and `SingleCellExperiment` object classes are recovered accordingly, and it defaults to `SingleCellExperiment` if no information is in the file, e.g. if the file was written by the Python library.
> 
> This is also being tested for, [e.g. here](https://github.com/ilia-kats/MuData/blob/33e82894112f44cf86a6f6d4602151da9cb216ce/tests/testthat/test_readh5mu.R#L20).
> 
> This seems to cover the points above regarding the preservation of the class of the original object where possible.
> 

Sounds good. 

> ### Write methods
> We could change them to multiple if/else clauses instead of using dynamic dispatch, e.g. as [HDF5Array does in the linked function](https://github.com/Bioconductor/HDF5Array/blob/db6b7cf8f7c47ed61182c11e870fdebe16408318/R/saveHDF5SummarizedExperiment.R#L145). We're not sure that is going to result in a cleaner code but that seems to be the way we can refactor the code in if you think this follows the community guidelines better. Just wanted to double-check if that's what you implied?
> 
> And just to leave it as a note here, as we govern the on-disk format, there should be no big problem with method collision, which is mentioned as the major concern in the guidelines above, in other words I see this more of a problem with methods such as `writeSummarisedExperiment()` rather than the ones that specify a particular format as `writeH5MU()`.

Yes, avoiding writing methods for classes that are external to the package is, in general, cleaner code. If, for example, `SummarizedExperiment` provided a `writeH5MU` method along side yours, how would users know which one is the appropriate one? Collision is less of a risk if you create a plain function similar to what `HDF5Array` has implemented.

**Comment by gtca** [comment]
Hi Marcel @LiNk-NY, I think this is ready for another look as we changed the write methods as suggested (mostly [this commit](https://github.com/ilia-kats/MuData/commit/fa40c4f3e24879fec67790a999dbf93388372e9e)).

**Comment by LiNk-NY** [comment]
Hi Danila, @gtca 

Thank you for making those changes. The package looks good to me!
I will accept your package. 
Make sure to resolve the WARNING and some of the NOTEs from `BiocCheck::BiocCheck()`
as you continue to improve your package. 

Best regards,
Marcel

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gtca.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MuData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MuData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
