### ISSUE TITLE
CBNplot

### ISSUE THREAD

**Issue by noriakis** [Bioconductor/Contributions#2477]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/noriakis/CBNplot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for your submission.  We need some pre-review changes.  1) please don't call your vignette vignette.Rmd   2) in the vignette `counts = read.table("GSE133624_reads-count-all-sample.txt", header=1, row.names=1)` doesn't work because the file is not present.  If it is a large file you'll have to make an arrangement to contribute to ExperimentHub.  Or you might be able to use code based on GEOquery to retrieve the necessary resource.

**Comment by noriakis** [comment]
@vjcitn Thank you very much for checking the package. We have made the changes as follows.
1) We have renamed vignette.Rmd to basic_usage.Rmd.
2) Thank you very much for your suggestion. We have changed the code to use `GEOquery` and download the necessary resource.

**Comment by vjcitn** [comment]
You do not have DESeq2 or GEOquery in Suggests of DESCRIPTION.  All packages employed in the vignette or tests or examples must be noted in the DESCRIPTION.

**Comment by lshep** [comment]
Also:   Please also put an explicit `eval=FALSE` for the installation code section of the vignette.  `devtools::install_github` should be updated to `BiocManager::install`.  The vignette name basic_usage is also very generic and could introduce conflicts with other packages.  We highly recommend using the name of the package as the vignette name.

**Comment by noriakis** [comment]
@vjcitn Thank you very much for your reply. I apologize for not putting these packages to DESCRIPTION. I added two packages in Suggests.

@lshep Thank you very much for checking the package. I put `eval=FALSE` for the installation code section, and replaced `devtools::install_github` with `BiocManager::install`. Additionally, I changed the vignette name to "CBNplot_basic_usage.Rmd".

**Comment by vjcitn** [comment]
Please run R CMD check on a clean checkout from your repo.  Your basic vignette has library(CBNplot) deactivated with eval=FALSE and so I cannot build without changing source.  Please do us a favor.  Be sure that an unaffiliated user of your repo can have a successful run of R CMD check and BiocCheck on your package so that they can be able to review it!  Bump the version number for every change.

**Comment by vjcitn** [comment]
```
Quitting from lines 67-73 (CBNplot_basic_usage.Rmd) 
Error: processing vignette 'CBNplot_basic_usage.Rmd' failed with diagnostics:
could not find function "bngeneplot"
--- failed re-building ‘CBNplot_basic_usage.Rmd’
```

**Comment by vjcitn** [comment]
ANY change to source has to result in you running R CMD check again on the new sources

**Comment by noriakis** [comment]
Dear @vjcitn,
Thank you very much for taking the time to review the package. I sincerely apologize for putting the `library()` line to `eval=FALSE` section. I fixed the problem, and I make sure that `R CMD check`, `BiocCheckGitClone`, and `BiocCheck` produces no errors or warnings.

**Comment by Kayla-Morrell** [comment]
@noriakis - 
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.15
release is 4/20. Any packages accepted after this date will be included in the
next release.

## General package development

- [ ] REQUIRED: If the README file contains package installation instructions,
  there should also be instructions on how to install from Bioconductor.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        NetworkEnrichment

## NAMESPACE

- [ ] SUGGESTION: Consider adding `importFrom("stats", "cor", "p.adjust",
  "prcomp", "weights")` to your NAMESPACE file.

## Data

- [ ] REQUIRED: If possible, there should be some information in the
  documentation of the data about creation and source information.

## Vignette

- [ ] REQUIRED: There should be a bit more context explaining the function calls
  from the package. What is the difference between each function? Why would a
user choose to use one over the other? It's not enough to just provide the code.
- [ ] SUGGESTION: We encourage the use of `BiocStyle` for formatting.
- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main fuctions. Users should be able to have a
relevant page display with `?<package name>`.
- [ ] SUGGESTION: There are many \examples lines that are wider than 100
  characters. These lines will be truncated in the PDF manual.
- [ ] REQUIRED: Add runnable examples to the following man pages which document
exported objects:
        queryCpDistLs.Rd
        queryCpDistLw.Rd
- [ ] REQUIRED: Usage of donttest{} / dontrun{} found in man page examples. If
absolutely necessary use donttest{} instead of dontrun{}, donttest{} requires
valid R code while dontrun{} does not. Found in files:
        queryCpDistLs.Rd
        queryCpDistLw.Rd

## Unit tests

- [ ] SUGGESTION: Consider adding unit test. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

  - [ ] SUGGESTION: For the function `coord_flip()` there is a partial argument
  match of `y` to `ylim`. Found for `bngeneplot`, `bngeneplotCustom`,
`bnpathplot`, `bnpathplotCustom`.
- [ ] SUGGESTION: Undefined global functions or variables.
- [ ] REQUIRED: Avoid using `=` for assignment and use `<-` instead.
- [ ] REQUIRED: There should be no direct slot acces with `@`, accessors should
  be implemented and used instead.
- [ ] REQUIRED: Avoid `suppressWarnings` / `*Messages` if possible,
  `suppressMessages()` was found in R/bnpathplot.R, line 195.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 355
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents, 398 lines are not.

Best,
Kayla

**Comment by noriakis** [comment]
Dear @Kayla-Morrell,
Thank you for reviewing the package. I will try to address your comments and report back to you when completed.

**Comment by Kayla-Morrell** [comment]
@noriakis - Checking in to see if there has been any progress made on addressing the points from my review. If there is no progress made within the next week I'll have to close this issue for inactivity, then you will have to reopen when you have sufficient time to work on the package.

Best,
Kayla

**Comment by noriakis** [comment]
Dear @Kayla-Morrell, Thank you for the mention. I apologize for the long delay in revising. I am working on the package, and am currently struggling to implement accessors. As I cannot guarantee to report the revision within the next week, I would be grateful if you could close it once, and I will reopen it when the revision is ready.

**Comment by Kayla-Morrell** [comment]
@noriakis - Please comment here on the issue when you are ready for it to be reopened.

**Comment by noriakis** [comment]
Dear @Kayla-Morrell, I apologize for the late response, but I have fixed the problems you pointed out in the review.
Would it be possible to restart the reviewing process again?

**Comment by Kayla-Morrell** [comment]
@noriakis - Please be sure you push a valid version bump with any changes that were made so that a new build report is produced. Thanks!

**Comment by noriakis** [comment]
Dear @Kayla-Morrell @lshep,

Thank you very much for thoroughly reviewing the package, and reopening the reviewing process.
I apologize for the late response, but I have made necessary changes pointed out in the review as described below.
I would be very grateful if you could spare some time to review it again.

> ## General package development
> * [x]  REQUIRED: If the README file contains package installation instructions,
>   there should also be instructions on how to install from Bioconductor.

I added how one can install from Bioconductor using BiocManager on README.md, along with the installation code using devtools.

> ## DESCRIPTION
> * [x]  SUGGESTION: Consider adding these automatically suggested biocViews:
>   NetworkEnrichment

I added a biocView NetworkEnrichment on DESCRIPTION.

> ## NAMESPACE
> * [x]  SUGGESTION: Consider adding `importFrom("stats", "cor", "p.adjust", "prcomp", "weights")` to your NAMESPACE file.

I added the suggested lines to NAMESPACE.

> ## Data
> * [x]  REQUIRED: If possible, there should be some information in the
>   documentation of the data about creation and source information.

I added how the data was created on data.R.

> ## Vignette
> * [x]  REQUIRED: There should be a bit more context explaining the function calls
>   from the package. What is the difference between each function? Why would a
>   user choose to use one over the other? It's not enough to just provide the code.

Thank you for this critical comment. As you stated, it is not clear why one would choose between functions like between bngeneplot() and bngeneplotCustom(). The primary aim for the custom function is providing more flexibility for the visualization like glowing edges and nodes, while the plain function provides the raw visualization. I added more examples to vignettes and try to explain the differences.

> * [x]  SUGGESTION: We encourage the use of `BiocStyle` for formatting.

I specified the BiocStyle formatting for vignette.

> * [x]  SUGGESTION: We strongly encourage the use of table of contents.

I have enabled the toc option.

> 
> ## Man pages
> * [x]  SUGGESTION: We encourage having a package man page with an overview of the
>   package and links to the main fuctions. Users should be able to have a
>   relevant page display with `?<package name>`.

As you stated, the man page for the package is needed as pointed out in your comment regarding Vignette. I added a package man page describing overviews and links to main functions.

> * [x]  SUGGESTION: There are many \examples lines that are wider than 100
>   characters. These lines will be truncated in the PDF manual.

I have adjusted the \examples text to fit within 100 characters.

> * [x]  REQUIRED: Add runnable examples to the following man pages which document
>   exported objects:
>   queryCpDistLs.Rd
>   queryCpDistLw.Rd

Thank you for the comment. I added runnable examples to these two functions.

> * [x]  REQUIRED: Usage of donttest{} / dontrun{} found in man page examples. If
>   absolutely necessary use donttest{} instead of dontrun{}, donttest{} requires
>   valid R code while dontrun{} does not. Found in files:
>   queryCpDistLs.Rd
>   queryCpDistLw.Rd

I added runnable examples, and dontrun{} is removed.

> ## Unit tests
> * [x]  SUGGESTION: Consider adding unit test. We strongly encourage them. See
>   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

I have added unit tests to cover the main function.

> ## R code
> * [x]  SUGGESTION: For the function `coord_flip()` there is a partial argument
>   match of `y` to `ylim`. Found for `bngeneplot`, `bngeneplotCustom`,
>   `bnpathplot`, `bnpathplotCustom`.

Thank you for this comment. I fixed the code.

> * [x]  SUGGESTION: Undefined global functions or variables.

I have removed all the undefined global functions and variables.

> * [x]  REQUIRED: Avoid using `=` for assignment and use `<-` instead.

I have replaced = with <- for assignment.

> * [x]  REQUIRED: There should be no direct slot acces with `@`, accessors should
>   be implemented and used instead.

Thank you for this. I have removed direct access with @.

> * [x]  REQUIRED: Avoid `suppressWarnings` / `*Messages` if possible,
>   `suppressMessages()` was found in R/bnpathplot.R, line 195.

I have removed suppressWarnings().

> * [x]  SUGGESTION: For formatting reasons, consider shorter lines. There are 355
>   lines that are > 80 characters long.

I adjusted the lines in the main functions to be less than 80 characters.

> * [x]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents, 398 lines are not.

The line indents are set to multiples of 4 spaces, except for Rd files.

**Comment by Kayla-Morrell** [comment]
@noriakis - Thank you for making the necessary changes.  I have just one additional requirement. Once the change is made I'll be happy to accept the package.

## DESCRIPTION

- [ ] REQUIRED: Update the R version dependency from 4.2.0 to 4.3.0 since this is the version of R that the package will first be available for.

Best,
Kayla

**Comment by noriakis** [comment]
Dear @Kayla-Morrell, Thank you very much for taking the time to review the package again. 
I have changed the R version dependency in DESCRIPTION.

> ## DESCRIPTION
> * [x]  REQUIRED: Update the R version dependency from 4.2.0 to 4.3.0 since this is the version of R that the package will first be available for.

**Comment by Kayla-Morrell** [comment]
@noriakis - Thank you for making that change. I'm more than happy to accept the package now.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/noriakis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CBNplot")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CBNplot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by noriakis** [comment]
@Kayla-Morrell Thank you for reviewing and accepting the package, and I once again apologize for the late responses.
@lshep Thank you for the detailed instruction. I will proceed as you have instructed.
