### ISSUE TITLE
rgoslin submission

### ISSUE THREAD

**Issue by nilshoffmann** [Bioconductor/Contributions#2485]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lifs-tools/rgoslin

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nilshoffmann** [comment]
@PeteHaitch I have updated my repository at https://github.com/lifs-tools/rgoslin, removing the Rstudio project file that seems to have caused the build error, according to the logs. I do not seem to have rights to push to Bioconductor's git at this point. How should we proceed?

**Comment by lshep** [comment]
@nilshoffmann  you should have permission to push to git.bioconductor.org.  You will need to activate your GitCredentials account as mentioned about and add ssh-keys for access.  https://git.bioconductor.org/BiocCredentials   .  Then follow the instructions for pushing to git.bioconductor.org  https://bioconductor.org/developers/how-to/git/new-package-workflow/

**Comment by PeteHaitch** [comment]
Thanks @nilshoffmann. I aim to do the initial review this week (mid-next week at the latest).

**Comment by PeteHaitch** [comment]
Hi @nilshoffmann,

I see that **rgoslin** provides R bindings to the 'Goslin grammars'  and that there are analogous packages for other programming languages.
I started to review **rgoslin**, but before I go too far I'd like to clarify why you chose to submit to Bioconductor rather than, say, [CRAN](https://cran.r-project.org/)?
In asking this, I don't mean to discourage the submission of **rgoslin** to Bioconductor.

I appreciate that lipids could certainly fall under Bioconductor's broad aim of supporting the "analysis of data from current and emerging biological assays", but **rgoslin** currently does not depend on any Bioconductor packages nor do the examples demonstrate how **rgoslin** would fit into a workflow that makes use of existing Bioconductor software around lipidomics, metabolomics, etc.

Since a key aim of the Bioconductor project is package interoperatability, some demonstration of this is generally considered essential.
Are there packages within the [LipidOmics](https://bioconductor.org/packages/release/BiocViews.html#___Lipidomics), [Metabolomics](https://bioconductor.org/packages/release/BiocViews.html#___Metabolomics), or [MassSpectrometry](https://bioconductor.org/packages/release/BiocViews.html#___MassSpectrometry) biocViews terms that you could use in your vignette to demonstrate how **rgoslin** fits into a typical analysis to properly showcase its features and benefits to a user?

Cheers,
Pete

**Comment by nilshoffmann** [comment]
Hi @PeteHaitch,

thanks for the review and feedback on rgoslin. Proper lipid naming and reporting is still an unsolved problem. Goslin and rgoslin for R, aim at simplifying the process of parsing different shorthand nomenclatures that are currently in active use and aims to standardize lipid naming by providing a normlized shorthand lipid name, following the latest recommendations of the lipidomics standards initiative. As such, it is also the first library to support this use case in R and, as you already checked, many other programming languages.

I am in contact or have been with the authors of [lipidr](https://bioconductor.org/packages/release/bioc/html/lipidr.html) @ahmohamed, [xcms](https://bioconductor.org/packages/release/bioc/html/xcms.html) @sneumann, @michaelwitting and others. I will be happy to discuss different examples / use cases to include in the rgoslin vignette with them, or even direct inclusion of rgoslin in one of these libraries. Since rgoslin is a utility library I designed it to have minimal dependencies. 

Cheers,
Nils

**Comment by PeteHaitch** [comment]
Hi @nilshoffmann,

Thanks for the above response.
Overall, the package is in good shape.
For acceptance into Bioconductor, I have a few **Required** points, as well as some **Recommended** points, that I would ask you to first please address.
I've also asked someone from the core Bioconductor team to chime in on a couple of points (tagging @vjcitn).

Given that you are managing a number of language-specific interfaces to **goslin**, if the Bioconductor-specific requirements seem too burdensome then you should consider submission to CRAN.
As a utility library for biological data, I can see arguments for submission of **rgoslin** to either Bioconductor or CRAN.
Bioconductor packages, such as **lipidr** and **xcms**, would still be able to depend on **rgoslin** if it was available on CRAN.
Again, this is not intended to discourage submission to Bioconductor but I just wanted to make sure you aware of all the options :)

## Required

- The vignette must demonstrate interoperability with other Bioconductor software. It sounds like some thought has been given to demonstrating use cases or examples, so if you add a section to the vignette that will suffice. (I would advise against directly including **rgoslin** in one of these other packages because I suspect it will complicate maintenance).
- The vignette must have an *Introduction* section (essentially the existing *Prerequisites*)
- The vignette must have an *Installation* instruction with the official Bioconductor installation instructions (see https://contributions.bioconductor.org/docs.html?q=installation#installation). Once the package is accepted into Bioconductor, these will look like

```r
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("rgoslin")
```

Please also add these to the `README.md` (replacing the current `devtools::install_github()`-based instructions).

- Please add a table of contents to the vignette

## Recommended

- Is it worth simplifying the R-level API to essentially `parseLipidNames()`?
  - As far as I can tell, there is a one-to-one mapping between the length of `lipidNames` and the number of rows in the returned _data.frame_, so the 'non-pluralised' versions of the two main functions (`parseLipidName()` and `parseLipidNameWithGrammar()`) feel redundant.
  - Could `parseLipidNames(lipidNames)` change to something like `parseLipidNames(lipidNames, grammer = NULL)` where `grammar = NULL` is equivalent to the current `parseLipidNames(lipidNames)` with automagic guessing of the grammar and `parseLipidNames(lipidNames, grammer = value)` is equivalent to the current `parseLipidNamesWithGrammar(lipidNames, grammer = value)`?
  - If you want to retain `parseLipidNames()` and `parseLipidNamesWithGrammar()` as two separate functions, then if `parseLipidNamesWithGrammar()` is not supplied with a `grammar` (e.g., `parseLipidNamesWithGrammar("PC 32:1")`) then it should probably return an error to the effect of "Please supply a 'grammar'" rather than returning `NULL`.
- Consider adding a `inst/CITATION` file (see https://contributions.bioconductor.org/citation.html)
- What is `renovate.json` needed for?
- The **BiocStyle** package is encouraged for vignette formatting.
 (https://contributions.bioconductor.org/docs.html?q=vignette#installation)
- Vignette needs a table of contents
- Consider removing **pkgdown**. Once the package is accepted into Bioconductor, it will have a software landing page and links to the documentation and vignettes available from 	https://bioconductor.org/packages/rgoslin/. I'll ask @vjcitn to chime in with any 'official' advice on whether separate **pkgdown**-based sites are okay.
- Consider adding tests that cover the error cases.
  - E.g., a silly (perhaps unrealistic) example like `parseLipidNames(c("A", "B"))` and `parseLipidNames(c(1, 2))` may not be triggering the intended error message?
  - You can run `covr::report()` for a standalone code coverage report (this is how I saw that these lines are not covered by the current unit tests).
- There's a broken link in the README and vignette to the C# implementation (https://github.com/lifs-tools/csgoslin)
- Again tagging @vjcitn, would a C-expert mind checking the `src/Makevars`?

**Comment by PeteHaitch** [comment]
> Consider removing pkgdown. Once the package is accepted into Bioconductor, it will have a software landing page and links to the documentation and vignettes available from https://bioconductor.org/packages/rgoslin/. I'll ask @vjcitn to chime in with any 'official' advice on whether separate pkgdown-based sites are okay.

I've checked with the BioC core team and there's no need to remove **pkgdown**.

You probably no longer need **pkgKitten** in `Suggests` in the `DESCRIPTION`.
As far as I'm aware, this is only needed/used to setup the initial structure of an R package and it's then no longer required.

**Comment by PeteHaitch** [comment]
Hi @nilshoffmann ,

Do you wish to proceed with the submission?
We like to see some activity on the issue within 3 weeks.
It's no problem if it's taking longer, but for now I will close the issue and you can re-open it if you wish to proceed and when you are ready.

Cheers,
Pete

**Comment by nilshoffmann** [comment]
Hi @PeteHaitch ,

thanks for the heads up. 
I will try to address the remaining issues until the end of this week.

Cheers,
Nils

**Comment by nilshoffmann** [comment]
@PeteHaitch I am ready to recommence with the submission. How do I reopen the issue?

**Comment by nilshoffmann** [comment]
Current status of requested changes:

### Required

- [x] The vignette must demonstrate interoperability with other Bioconductor software. It sounds like some thought has been given to demonstrating use cases or examples, so if you add a section to the vignette that will suffice. (I would advise against directly including rgoslin in one of these other packages because I suspect it will complicate maintenance).
- [x] The vignette must have an Introduction section (essentially the existing Prerequisites)
- [x] The vignette must have an Installation instruction with the official Bioconductor installation instructions (see https://contributions.bioconductor.org/docs.html?q=installation#installation). Once the package is accepted into Bioconductor, these will look like

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("rgoslin")
```

- [x] Please also add these to the README.md (replacing the current devtools::install_github()-based instructions).

- [x] Please add a table of contents to the vignette

### Recommended

Is it worth simplifying the R-level API to essentially parseLipidNames()?
As far as I can tell, there is a one-to-one mapping between the length of lipidNames and the number of rows in the returned data.frame, so the 'non-pluralised' versions of the two main functions (parseLipidName() and parseLipidNameWithGrammar()) feel redundant.
- [x] Could parseLipidNames(lipidNames) change to something like parseLipidNames(lipidNames, grammer = NULL) where grammar = NULL is equivalent to the current parseLipidNames(lipidNames) with automagic guessing of the grammar and parseLipidNames(lipidNames, grammer = value) is equivalent to the current parseLipidNamesWithGrammar(lipidNames, grammer = value)?
        If you want to retain parseLipidNames() and parseLipidNamesWithGrammar() as two separate functions, then if parseLipidNamesWithGrammar() is not supplied with a grammar (e.g., parseLipidNamesWithGrammar("PC 32:1")) then it should probably return an error to the effect of "Please supply a 'grammar'" rather than returning NULL.
- [x] Consider adding a inst/CITATION file (see https://contributions.bioconductor.org/citation.html)
- [x] What is renovate.json needed for? (*removed*)
- [x] The BiocStyle package is encouraged for vignette formatting.
    (https://contributions.bioconductor.org/docs.html?q=vignette#installation)
- [x] Vignette needs a table of contents
- [x] Consider removing pkgdown. Once the package is accepted into Bioconductor, it will have a software landing page and links to the documentation and vignettes available from https://bioconductor.org/packages/rgoslin/. I'll ask @vjcitn to chime in with any 'official' advice on whether separate pkgdown-based sites are okay. (*removed*)

Consider adding tests that cover the error cases. 
  - [x] E.g., a silly (perhaps unrealistic) example like parseLipidNames(c("A", "B")) and parseLipidNames(c(1, 2)) may not be triggering the intended error message?
  - [x] You can run covr::report() for a standalone code coverage report (this is how I saw that these lines are not covered by the current unit tests).
- [x] There's a broken link in the README and vignette to the C# implementation (https://github.com/lifs-tools/csgoslin) 
- [ ] Again tagging @vjcitn, would a C-expert mind checking the src/Makevars?

**Comment by PeteHaitch** [comment]
Thanks, @nilshoffmann.
Please post a message once you're done addressing the review comments and I'll take another look

**Comment by nilshoffmann** [comment]
> Current status of requested changes:
> ### Required
> 
>     * [x]  The vignette must demonstrate interoperability with other Bioconductor software. It sounds like some thought has been given to demonstrating use cases or examples, so if you add a section to the vignette that will suffice. (I would advise against directly including rgoslin in one of these other packages because I suspect it will complicate maintenance).
> 
>     * [x]  The vignette must have an Introduction section (essentially the existing Prerequisites)
> 
>     * [x]  The vignette must have an Installation instruction with the official Bioconductor installation instructions (see https://contributions.bioconductor.org/docs.html?q=installation#installation). Once the package is accepted into Bioconductor, these will look like
> 
> 
> ```
> if (!require("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> 
> BiocManager::install("rgoslin")
> ```
> 
>     * [x]  Please also add these to the README.md (replacing the current devtools::install_github()-based instructions).
> 
>     * [x]  Please add a table of contents to the vignette
> 
> 
> ### Recommended
> 
> Is it worth simplifying the R-level API to essentially parseLipidNames()? As far as I can tell, there is a one-to-one mapping between the length of lipidNames and the number of rows in the returned data.frame, so the 'non-pluralised' versions of the two main functions (parseLipidName() and parseLipidNameWithGrammar()) feel redundant.
> 
>     * [x]  Could parseLipidNames(lipidNames) change to something like parseLipidNames(lipidNames, grammer = NULL) where grammar = NULL is equivalent to the current parseLipidNames(lipidNames) with automagic guessing of the grammar and parseLipidNames(lipidNames, grammer = value) is equivalent to the current parseLipidNamesWithGrammar(lipidNames, grammer = value)?
>       If you want to retain parseLipidNames() and parseLipidNamesWithGrammar() as two separate functions, then if parseLipidNamesWithGrammar() is not supplied with a grammar (e.g., parseLipidNamesWithGrammar("PC 32:1")) then it should probably return an error to the effect of "Please supply a 'grammar'" rather than returning NULL.
> 
>     * [x]  Consider adding a inst/CITATION file (see https://contributions.bioconductor.org/citation.html)
> 
>     * [x]  What is renovate.json needed for? (_removed_)
> 
>     * [x]  The BiocStyle package is encouraged for vignette formatting.
>       (https://contributions.bioconductor.org/docs.html?q=vignette#installation)
> 
>     * [x]  Vignette needs a table of contents
> 
>     * [x]  Consider removing pkgdown. Once the package is accepted into Bioconductor, it will have a software landing page and links to the documentation and vignettes available from https://bioconductor.org/packages/rgoslin/. I'll ask @vjcitn to chime in with any 'official' advice on whether separate pkgdown-based sites are okay. (_removed_)
> 
> 
> Consider adding tests that cover the error cases.
> 
>     * [x]  E.g., a silly (perhaps unrealistic) example like parseLipidNames(c("A", "B")) and parseLipidNames(c(1, 2)) may not be triggering the intended error message?
> 
>     * [x]  You can run covr::report() for a standalone code coverage report (this is how I saw that these lines are not covered by the current unit tests).
> 
>     * [x]  There's a broken link in the README and vignette to the C# implementation (https://github.com/lifs-tools/csgoslin)
> 
>     * [ ]  Again tagging @vjcitn, would a C-expert mind checking the src/Makevars?

@PeteHaitch I have added an example usage with lipidr in the vignette and have addressed all of your remarks. Only the external check of Makevars by @vjcitn is still open.

**Comment by PeteHaitch** [comment]
Thanks, @nilshoffmann!
I'll take a look in the next few days (although might not be until next week)

**Comment by PeteHaitch** [comment]
Hi @nilshoffmann 

Some additional comments based on the changes:

- [x] Shouldn't have **testthat** in `LinkingTo`
- [x] Consistent use of `<-` instead of `=` in vignette (this was automatically fixed by running `styler::style_pkg(filetype = "Rmd")`)
- [x] Need `library(stringr)` and `library(ggplot2)` in echoed and evaluated chunk in vignette, otherwise a user copy-pasting the code from the rendered vignette won't be able to run the example.
- [x] **lipidr** example is a great addition to vignette but code (and comments) are a bit hard to read (some of this was automatically fixed by running `styler::style_pkg(filetype = "Rmd")` and the rest with some manual tweaks to spacing and indentation).
- [ ] No need to mention **RTools** in installation instructions. In any case, [**RTools**](https://cran.r-project.org/bin/windows/Rtools/) is only applicable to those on Windows building from source, which will be a tiny minority of users because BioC will serve Windows (and macOS) binaries.
- [ ] I got a lot of errors when running `lipidNames <- parseLipidNames(rowData(d)$clean_name)` from the vignette (vignette shows the same errors); it sort of seems like this error is expected but could perhaps be made clearer and explained in vignette.

I implemented fixes for those ticked ones, which I planned to submit as a PR to https://github.com/lifs-tools/rgoslin.
However, this github-hosted repo wasn't in-sync with the Bioconductor-hosted git repo so I couldn't do that.
Instead, I've attached the output of `git diff bioc-re-review > bioc-re-review-diff.txt`, i.e. comparing the `master` branch of the Bioconductor-hosted git to my `bioc-re-review` branch.
You may need to manually apply the changes I ticked off, but hopefully the patch helps somewhat.

Once those last issues are address I think we'll be ready to accept the package.

Thanks,
Pete
[bioc-re-review-diff.txt](https://github.com/Bioconductor/Contributions/files/8337515/bioc-re-review-diff.txt)

**Comment by nilshoffmann** [comment]
Hi @PeteHaitch 
thanks for the style fixes. Spaces versus tabs, I see :-). 

* I have incorporated the fixes from your diff patch.
* I have added all libraries required to run the **lipidr** example to an eval = FALSE block.
* I have removed RTools from the vignette, it is now only mentioned in the README.md with an explicit remark that only installation from source code may require that, but not regular installation via bioconductor.
* I have added further NOTE blocks and inline explanations to the vignette about expected messages, warnings and errors.

As to why there is a difference between the GitHub repo and the one on Bioconductor:
We have quite some large files included in the cppgoslin and goslin subtrees that would not pass the bioc-checks and would not need to be included for the R implementation to run. I am currently merging the contents manually between the two repos, but will switch to using proper patches due to your remark.

Thanks for this great and interactive review!

**Comment by PeteHaitch** [comment]
Hi @nilshoffmann,

Congratulations 🎉 
I'm marking the package as accepted.
Thank you for your contribution to Bioconductor.

I would still recommend running `styler::style_pkg(filetype = "Rmd")` on your package to make some cosmetic changes to the code in the vignette because it seems like these weren't incorporated when you manually applied the patch.

Cheers,
Pete

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nilshoffmann.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rgoslin")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rgoslin

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
