### ISSUE TITLE
SPOTlight

### ISSUE THREAD

**Issue by MarcElosua** [Bioconductor/Contributions#2488]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarcElosua/SPOTlight

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Marc, @MarcElosua 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel 

---

# SPOTlight #2488

## DESCRIPTION

* Looks good.

## NAMESPACE

* Functions that start with a period are not meant to be exported. Please
rename the functions or unexport.

## vignettes

* Images should be in the vignettes folder unless they're used by R in some
other way (re: `schematic.png`).
* Consider simplifying the examples with `lapply` e.g, filtering by
`mean.AUC`, with exported functions, especially if you use the same code
in the package examples.
* `Suggest` the `colorBlindness` package if you are using their palette.

Minor:

* Perhaps only present the data accession interface provided by `TENxVisiumData`
and remove the `query` instructions in the 'Loading the data' section.
* Note that `sce$age` and `sce$free_annotation` are inherited from
`SummarizedExperiment` and could be used for the subset examples. Subsetting
with the `subset` is not very common (AFAICT) and it would help users to
provide both methods.

## R

* `setMethod` for class "matrix" looks awkward in `plotCorrelationMatrix`.
Perhaps use a plain function?
* Please make these functions more robust and consider creating plain functions
rather than S4 methods on generic S3 classes like `character`. A file with
different case breaks `plotImage`:
```r
> newpath
[1] "/home/user/bioc/SPOTlight/inst/extdata/SPOTlight.PNG"
> plotImage(newpath)
Error in .local(x, ...) : 'x' should be of file type JPG, JPEG or PNG
```
* Avoid creating methods for classes outside of the package's `NAMESPACE`; see:
http://contributions.bioconductor.org/r-code.html?q=methods#methods-development
* Note that you can use `requireNamespace` to check if a package is installed
and then throw an error if the package is not available (`.test_installed`).
* Why check if `methods` is installed? Isn't it always? (`plotTopicProfiles`)

## code coverage

* Looks good.

```r
> covr::package_coverage()
SPOTlight Coverage: 91.19%
R/plotSpatialScatterpie.R: 53.33%
R/plotImage.R: 82.50%
R/SPOTlight.R: 90.32%
R/utils.R: 95.76%
R/data.R: 98.41%
R/AllGenerics.R: 100.00%
R/plotCorrelationMatrix.R: 100.00%
R/plotInteractions.R: 100.00%
R/plotTopicProfiles.R: 100.00%
```

**Comment by HelenaLC** [comment]
Dear Marcel, would you be able to advise us regarding:
```
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import NMF, Matrix, matrixStats, SeuratObject, stats in
      NAMESPACE as well as DESCRIPTION.
    * WARNING: Import colSums, rowSums, basis, coef, nmf, nmfModel,
      GetAssayData, GetImage, GetTissueCoordinates, Idents, Images,
      cbind, colLabels, counts, colMedians, rowAlls, rowSds, aggregate,
      rnbinom, runif in DESCRIPTION as well as NAMESPACE.
```
I can see all mentioned packages/functions in the [NAMESPACE](https://github.com/MarcElosua/SPOTlight/blob/main/NAMESPACE) as well as [DESCRIPTION](https://github.com/MarcElosua/SPOTlight/blob/main/DESCRIPTION), and we are not sure how recent changes could have caused these warnings. Any hints would be greatly appreciated!

As a side note, there's also this at the top of the `BiocCheck` part of the build report, but we don't know what that means:
```
* Checking Package Dependencies...
Warning in system2(cmd, args, stdout = TRUE, stderr = FALSE, env = "R_DEFAULT_PACKAGES=NULL") :
  running command 'R_DEFAULT_PACKAGES=NULL '/home/biocbuild/bbs-3.15-bioc/R/bin/R' -q --vanilla --slave -f /home/biocbuild/bbs-3.15-bioc/R/library/BiocCheck/script/checkBadDeps.R --args "/home/pkgbuild/packagebuilder/workers/jobs/2488/eab8b0bc7014e886d9d62fa5ef6a3beae00bbe10/SPOTlight_0.99.3.tar.gz" "/tmp/RtmpKtgCKP/file122d5e2795c7d2/lib" 2>/dev/null' had status 1
```

**Comment by LiNk-NY** [comment]
Hi Helena, @HelenaLC 

Thanks for pointing this out. That was a bug in `BiocCheck`. It has been fixed in version `1.31.31`. 

As a reminder, please see https://contributions.bioconductor.org/r-code.html?q=methods#methods-development
WRT creating methods for external classes.

* AFAICT `NMF` is not a class and perhaps `NMFfit` should be the class in the method definition. 

I will have to take a closer look at the warning on the BBS. Please ignore for now.

**Comment by MarcElosua** [comment]
Apologies for the delay in answering to the comments, finishing up a round of modifications and will update by the end of the week.

**Comment by MarcElosua** [comment]
I want to update

**Comment by LiNk-NY** [comment]
Hi @MarcElosua, 
You should be able to re-open the issue once and push changes once you are ready. 
Best,
Marcel

**Comment by MarcElosua** [comment]
Here are some comments on previous your previous round of revisions @LiNk-NY 

## NAMESPACE

* Functions that start with a period are not meant to be exported. Please
rename the functions or unexport.

> Since these functions are used to generate mock data for some function's examples we decided to export them. Since they are not meant to be used in a real life setting we have made it clear in the function's documentation.

## vignettes

* Images should be in the vignettes folder unless they're used by R in some
other way (re: `schematic.png`).

> Done

* Consider simplifying the examples with `lapply` e.g, filtering by
`mean.AUC`, with exported functions, especially if you use the same code
in the package examples.

> In this case, since the marker genes can come in varying data structures - list, dataframe... we want to give the user the flexibility to choose the source of the marker genes. Therefore, we propose this in the vignette as an example of how the mgs should look when inputing it to `SPOTlight`.

* `Suggest` the `colorBlindness` package if you are using their palette.

> Done

Minor:

* Perhaps only present the data accession interface provided by `TENxVisiumData`
and remove the `query` instructions in the 'Loading the data' section.

> Done

* Note that `sce$age` and `sce$free_annotation` are inherited from
`SummarizedExperiment` and could be used for the subset examples. Subsetting
with the `subset` is not very common (AFAICT) and it would help users to
provide both methods.

> Done

## R

* `setMethod` for class "matrix" looks awkward in `plotCorrelationMatrix`.
Perhaps use a plain function?

> Done

* Please make these functions more robust and consider creating plain functions
rather than S4 methods on generic S3 classes like `character`. A file with
different case breaks `plotImage`:

> We fixed the issue making the grep that checks for the file extension case insensitive. We used an S4 method for this function since the input can be a character path, a `Spatial Experiment` object, a `Seurat` object, an array or a rastergrob. Could you confirm this is an appropriate use of S4 methods here?

* Avoid creating methods for classes outside of the package's `NAMESPACE`; see:
http://contributions.bioconductor.org/r-code.html?q=methods#methods-development

> We understand the reasoning behind this comment. In this package we aim to be flexible to various types of common input such as `SCE`, `SP` and `Seurat`. However we want to limit the dependencies of `SPOTlight`. Being `SCE`, `SP` and `Seurat` packages with a large amount of dependencies what would you suggest to do here? For example `SCE` and `SE` users might no be interested in having `Seurat` and viceversa. If this is required would you suggest moving `Seurat`, `SCE` and `SPE` from suggests to dependencies?

* Note that you can use `requireNamespace` to check if a package is installed and then throw an error if the package is not available (`.test_installed`).

> Could you clarify if you were suggesting to get rid of `.test_install`. We now use `requireNamespace` to test if a package is installed. We decided to keep the `.test_installed` to give an informative error message to the user. 

* Why check if `methods` is installed? Isn't it always? (`plotTopicProfiles`)

> Done

* AFAICT NMF is not a class and perhaps NMFfit should be the class in the method definition.

> Done, changed in the function plotTopicProfiles.


## Additions
We have added 2 new functions
- `trainNMF` and `runDeconvolution` to be ablt to run `SPOTlight` stepwise and save the intermediate model so it can be reused across ST datasets.
- We have also added the possibility of using the jaccard index for `plotInteractions`

**Comment by LiNk-NY** [comment]
Hi Marc, @MarcElosua 

> * Please make these functions more robust and consider creating plain functions
>   rather than S4 methods on generic S3 classes like `character`. A file with
>   different case breaks `plotImage`:
> 
> > We fixed the issue making the grep that checks for the file extension case insensitive. We used an S4 method for this function since the input can be a character path, a `Spatial Experiment` object, a `Seurat` object, an array or a rastergrob. Could you confirm this is an appropriate use of S4 methods here?

> * Avoid creating methods for classes outside of the package's `NAMESPACE`; see:
>   http://contributions.bioconductor.org/r-code.html?q=methods#methods-development
> 
> > We understand the reasoning behind this comment. In this package we aim to be flexible to various types of common input such as `SCE`, `SP` and `Seurat`. However we want to limit the dependencies of `SPOTlight`. Being `SCE`, `SP` and `Seurat` packages with a large amount of dependencies what would you suggest to do here? For example `SCE` and `SE` users might no be interested in having `Seurat` and viceversa. If this is required would you suggest moving `Seurat`, `SCE` and `SPE` from suggests to dependencies?

These are all related. The general recommendation is to avoid creating methods for classes that are not your own. If for example, `SpatialExperiment` decides to export a `plotImage` method, then that would create a conflict with your method. Also shouldn't this method live in the `SpatialExperiment`'s namespace rather than in another package (yours)? 

The alternative is to create a plain `plotImage` function that has a helper for each class of input object. Dependencies won't be a problem if you check for imports as you have with `.test_installed`.

**Comment by MarcElosua** [comment]
Hi @LiNk-NY ,

Thanks a lot for your feedback. We have applied the changes you recommended to `plotImage`. Before we re-submit, should we follow the same approach for `trainNMF`,  `runDeconvolution`, and `SPOTlight`? These three function names are unlikely to be used by either `Seurat` or `SpatialExperiment` and they are central to our package. 

Thanks!

**Comment by LiNk-NY** [comment]
Hi Marc, @MarcElosua 

> Thanks a lot for your feedback. We have applied the changes you recommended to `plotImage`. Before we re-submit, should we follow the same approach for `trainNMF`, `runDeconvolution`, and `SPOTlight`? These three function names are unlikely to be used by either `Seurat` or `SpatialExperiment` and they are central to our package.

Ideally, yes. That's the recommended practice. And for some classes you don't need to do much other than run `as.matrix` on them which in turn makes your code more flexible to new classes. If the operation fails, you can provide a helpful error message as well. 

-Marcel

**Comment by MarcElosua** [comment]
Hi @LiNk-NY ,

We had discussed setting S4 methods with @HelenaLC and have revisited the conversation. We agree that `plotImage` should not be a an S4 Method since it's name can easily overlap with a function name in `Seurat`, `SpatialExperiment`, and `SingleCellExperiment`. However, for the `SPOTlight` specific functions discussed above -- `trainNMF`, `runDeconvolution`, and `SPOTlight` we followed practices employed by other commonly used packages in `Bioconductor` used to analyze Single-Cell data, like `scran`, `scater`, `scuttle`.

At the moment we would prefer to stick with the current design while being aware of the potential conflicts this could cause and  commit to rapidly adapt the code in case these happen.

Thank you for the input and looking forward to hearing from you!

**Comment by LiNk-NY** [comment]
Hi Marc, @MarcElosua 

Some of those classes are from the same developer e.g., `SingleCellExperiment` but some methods are inconsistently implemented. On the other hand, you may consider the `scran::clusterCells` approach. 

It's best to avoid polluting the class's namespace unless you developed the original class and are implementing analysis methods in a different package (as may be the case for the packages you listed). 

Best regards,
Marcel

**Comment by MarcElosua** [comment]
Hi @LiNk-NY 

Following your advice we have removed all the methods and replaced them with helper functions now found in `R/utils.R`. We also added unit tests for them in `tests/testthat/test-utils.R`. Lastly, we brushed up on some minor issues users had reported.

Thank you for ll your help,
Best,
Marc

**Comment by MarcElosua** [comment]
As the previous Check failed due to TimeOut I used mock data for the example of the function `SPOTlight` to speed it up.

**Comment by LiNk-NY** [comment]
Hi Marc, @MarcElosua 

Thank you for making those updates!
Your package has been accepted. 

Best regards,
Marcel

PS. As you continue to improve your package, please take care of this `NOTE`
and use `BiocCheck`.

```
* checking R code for possible problems ... NOTE
plotSpatialScatterpie: no visible binding for global variable ‘coord_x’
plotSpatialScatterpie: no visible binding for global variable ‘coord_y’
Undefined global functions or variables:
  coord_x coord_y
```

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MarcElosua.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SPOTlight")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SPOTlight

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by MarcElosua** [comment]
Hi @LiNk-NY,

Thank you so much for you help and input in this process!
Regarding the `NOTE` you mention in your last comment I think it comes from `ggplot` when I pass coord_x and coord_y to `aes`. Shoud I use `aes_string` in this case?

Thank you!
Marc

**Comment by LiNk-NY** [comment]
Hi @MarcElosua 

Yes, you should use the programmatic interface or you could also just use `utils::globalVariables`. 

Best,
Marcel
