### ISSUE TITLE
BLMA: A package for bi-level meta-analysis

### ISSUE THREAD

**Issue by nguyentin** [Bioconductor/Contributions#250]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nguyentin/BLMA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nguyentin** [comment]
Hi,

I made changes to the package and also incremented the version to 0.99.1, how could I request for a new build?

**Comment by nguyentin** [comment]
Hi Admins,

I need help here with the following issues:

1/ I do not know how to resolve the warning on Windows platform "Warning: vfs customization not available on this platform. Ignoring value: vfs = unix-none". It looks like this warning is from existing Bioconductor packages, including KEGG.db and PADOG

2/ There are contradictory requirements from "R CMD check" and "R BiocCheck" regarding the folder inst/doc: 
i) If the folder inst/doc exists, then "R CMD BiocCheck" will have a warning "WARNING: Remove vignette sources from inst/doc; they belong in vignettes/". 
ii) If I remove the folder inst/doc then "R CMD check" will complain "Files in the 'vignettes' directory but no files in 'inst/doc'"

**Comment by hpages** [comment]
Hi Tin,

Thanks for your submission.

Please ignore 1/. We're aware of this issue and will fix it. FYI it's a regression introduced recently to the AnnotationDbi package that affects Windows users only.

For 2/ you only need to have the source vignette (i.e. BLMA.Rnw) in the vignettes/ folder. You don't need the inst/doc/ folder in the git tree as it will automatically be created and populated by `R CMD build`. So please remove the inst/doc/ folder from the git tree. Then make sure you always run `R CMD check` on the source tarball produced by `R CMD build`.

Thanks,
H.

**Comment by nguyentin** [comment]
Thanks, it looks like only the windows issue left. Please let me know how to proceed.

**Comment by nguyentin** [comment]
Hi, just want to make sure that things are ok. It looks like only 1 warning left, which I was told to ignore. Is there anything I can do at the moment to get the package approved? Many thanks, Tin.

**Comment by hpages** [comment]
Hi Tin,
There are some minor issues with BLMA, mostly cosmetic. See below.
Cheers,
H.

1. A well-established convention in Bioconductor is to not start function names with a capital letter. Please rename your functions with names that start with a lower case letter (e.g. `bilevelAnalysisClassic` instead of `BilevelAnalysisClassic`).

2. Why an "s" in `fishersMethod` and no "s" in `stoufferMethod`?

3. The `loadKEGGPathways()` function add files to the installation folder of the package. This is not allowed. The installation folder of a package should always be treated as read-only. That's because on a system where R is shared by all the users on the system, R and all the R packages are often installed in a folder where the end user doesn't have write access. So `loadKEGGPathways()` will fail on such system.

4. You sometimes use `<-` and sometimes `=` for assignments. Please use `<-` consistently. Make sure you put a space before and after it.

5. The man pages of the 8 datasets included in the package are poorly written:
  - Title is "This is data to be included in my package" for all of them.
  - You have 4 pairs of datasets in your package and 1 man page for each dataset (so 8 man pages in total for the datasets). Please reduce the number of man pages to 4 by documenting 1 pair per man page i.e. by documenting datasets `data_GSEXXXXX` and corresponding `group_GSEXXXXX` in the same man page. Then add the GSEXXXXX alias to that man page so the user can access it with `?GSEXXXXX`.
  - Description section is "Please see the package vignette for description" for all of them but the vignette doesn't say much either. Besides, the man page should be considered the primary place for documenting functions and datasets. So please provide details about each dataset in the description section of their man page. It's ok to repeat part of that information in the vignette, or to refer to the man page in the vignette. This is better than the other way around.

6. Several man pages (e.g. `BilevelAnalysisGene`, `BilevelAnalysisGeneset`, `BilevelAnalysisPathway`) and the vignette contain the following code for preparing the `dataList` and `groupList` objects:
```
    dataList <- list()
    groupList <- list()
    for (i in 1:length(dataSets)) {
        dataset=dataSets[i]
        group <- get(paste("group_",dataset,sep=""))
        data=get(paste("data_",dataset,sep=""))
        dataList[[i]] = data
        groupList[[i]] = group
    }
    names(dataList)=names(groupList)=dataSets
```
  This is clumpsy. The "R way" to do these things is:
```
    names(dataSets) <- dataSets
    dataList <- lapply(dataSets,
                       function(dataset) get(paste0("data_", dataset)))
    groupList <- lapply(dataSets,
                        function(dataset) get(paste0("group_", dataset)))
```
  This is actually done twice in the vignette (in subsections 3.1 and 4.2). Please do it only once.

7. Also the "R way" to time things is with `system.time()` e.g.
```
    system.time(ORAComb <- BilevelAnalysisGeneset(...))
```
instead of (found in the vignette):
```
    t1=Sys.time()
    ORAComb=BilevelAnalysisGeneset(...)
    t2=Sys.time();
    # running time
    t2-t1
```

8. The "R way" to display the first or last 10 rows of a data.frame 'X' is:
```
    head(X, n=10)
    tail(X, n=10)
```
  instead of (found in the vignette):
```
    X[1:10,]
    X[(nrow(X)-10):nrow(X),]
```

9. Proper indentation of your code makes it much easier to read. For example:
```
    ORAComb <- BilevelAnalysisGeneset(gslist, gs.names, dataList, groupList,
                                      enrichment="ORA")
    ORAComb[1:10, c("Name", "pBLMA", "pBLMA.fdr", "rBLMA")]
```
  is easier to read than:
```
    ORAComb=BilevelAnalysisGeneset(gslist = gslist, gs.names = gs.names, 
    dataList = dataList, groupList = groupList, enrichment = "ORA")
    ORAComb[1:10, c("Name", "pBLMA", "pBLMA.fdr", "rBLMA")]
```
  Also note that it is not necessarily a good idea to name all the arguments when calling a function. For example naming the `gslist`, `gs.names`, `dataList`, and `groupList` arguments in your call to `BilevelAnalysisGeneset()` has no benefit and only makes your code longer and "noisy".

10. Why export and document the `splitS()` function? Is it intended to be used directly by the user? For what? The man page doesn't say. The function doesn't seem to be used in the vignette either. If this is an internal helper only then it doesn't need (and should not) be exported and documented.

**Comment by nguyentin** [comment]
I fixed the concerns raised. However, I do not know why the buildVignettes fails under Windows

**Comment by hpages** [comment]
Hi Tin,
The vignette build failure on Windows seems to be a problem on our side. Let's ignore it for now. I'll have a 2nd look at the package in the next few days. Thanks for making changes to the package.
H.

**Comment by nguyentin** [comment]
Hi,

I'd like to ask if there is anything else I should do to get the package approved. The release date of Bioconductor 3.5 is approaching and I wonder if it is possible to have this BLMA package released this April.

Thanks,
Tin

**Comment by hpages** [comment]
Hi Tin,
I'll give BLMA another look ASAP. Sorry for the delay and thanks for your patience.
H.

**Comment by hpages** [comment]
Hi Tin,
Thanks for your patience. I finally got a chance to take a look at your changes and they look good. Thanks for making these changes. I'm marking the package as accepted. Congratulations!
In the next few days, we will add the package to our Subversion repository and to our daily builds. We will send you important information about this.
Regards,
H.
