### ISSUE TITLE
updateObject

### ISSUE THREAD

**Issue by hpages** [Bioconductor/Contributions#2507]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/updateObject

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
asked for vignette

**Comment by hpages** [comment]
just added one (in version 0.99.1)

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 

Thanks for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# updateObject #2507

Looks good overall. The package presents two facets. User-level and power-user
serialized object updates. The package should emphasize the user-level aspect
which is the typical use-case. I am not a big fan of the `git` commands but I can
see that they are necessary for the core team in order to manage large numbers
of packages that may not be available on one's computer.

## DESCRIPTION

* Add at least 2 more sentences to the Description. Perhaps mention that it is
still experimental?

## NAMESPACE

* Looks good.
* There is a mixture of snake_case and camelCase functions. Is there a
distinction between them? They are not mentioned in the vignette.

## vignette

* Looks good.
* As in the note above, more information about the snake_case functions would
be helpful.
* Perhaps the vignette should have an example that is not dependent on a
git clone. Currently it errors because of it.
* There should be more emphasis on updating source packages rather
than Git clones, as that is the typical use-case.

## R

* I wonder if some of these functions like `bump_pkg_version`, `get_descpath`,
`.infer_pkgname_from_path` should go in a general use Bioconductor package,
e.g., `BiocUtils` / `biocthis`. There are all functions that are re-written
throughout packages.
* The `git` push command should have arguments for remotes and branches, e.g.,
`git push origin main`.
* Looks good overall.

## tests

* Add unit tests.

**Comment by hpages** [comment]
Hi Marcel,

Thanks for the feedback.

I fixed the vignette and examples by using HTTPS access to clone packages.

I'd like to keep these files in the package:

    inst/scripts/find_serialized_DataFrame_instances-20211119.log
    inst/scripts/find_serialized_DataFrame_instances-20220113.log

They are useful to me to keep track of progress of the `DataFrame` -> `DFrame` migration, but **BiocCheck** doesn't like them :disappointed:

The package is meant to be used by package developers, not by regular Bioconductor users or power-users. This is explained in the introduction of the vignette. I added a sentence in the Description to clarify this. 

I'm not sure where the 3-sentences requirement for Description is coming from. I could add one more sentence to my Description to please **BioCheck** but it sounds a little bit artificial.

The snake_case functions are low-level functions that the user typically does not need to call directly. They are still exported and documented for 2 reasons:
1. There are some rare situations where more advanced users might need them.
2. I find it easier to organize the overall documentation by displacing some of the gory details of what a high-level function does to the man page of a lower-level function that it uses internally.

The vignette focuses on the typical use case so low-level functions are intentionally omitted.

The git branch to work on is specified via the `branch` argument of `updateBiocPackageRepoObjects()`. This will set the specified branch as the working branch. If the user specifies `push=TRUE`, then that branch will be pushed. This covers the central use case. For more complex git push scenarios, the user should use `git` at the command line.

It's not totally clear yet what the typical use-case for this package will be. One strong use case so far was for me to use it to update old objects in other people packages (I did this for dozens of packages after the `DataFrame` -> `DFrame` change in **S4Vectors**). Maybe at some point people will start using it to do this on their own package, hard to know. But using it in the core team to update dozens or hundreds of packages will probably remain a strong use case for a while (e.g. we'll do this again when we make [changes to the SimpleList internals](https://github.com/Bioconductor/S4Vectors/issues/97)). Also, at some point, I will move the `updateObject()` generic from **BiocGenerics** to this package and add another vignette that discusses best practices for implementing `updateObject()` methods. So the scope/focus of the package will slightly change.

I'm trying to come up with some unit tests. Not clear how to write good tests for this kind of stuff.

H.

**Comment by LiNk-NY** [comment]
Hi Hervé, 

The logs should probably not be uploaded with the package. 
We're trying to reduce the amount of extra files e.g., compilation by-products, that 
may be associated with a package but not part of the core functionality. 
Perhaps you can keep the logs in a gist if you'd like them to be tracked? 

> I'm not sure where the 3-sentences requirement for Description is coming from. I could add one more sentence to my Description to please BioCheck but it sounds a little bit artificial.

I think this is based on the number of sentences other `Description` fields have.
It's good to have a concise summary and three sentences is a good minimum.

> Maybe at some point people will start using it to do this on their own package, hard to know.

I think that is the path forward though it will require some advertising.
I am not sure how many packages still need to update their serialized instances but
this package should make it easier for them to do so.

Best,
Marcel

**Comment by hpages** [comment]
Hi Marcel,

I've added some basic unit tests, using the **testthat** framework. However I'm not too lucky with this framework so far: https://github.com/r-lib/testthat/issues/1584 (this is only my 2nd package using **testthat** instead of **RUnit**).

Think of the `.log` files as data files. It's more convenient for me to have them in the package itself next to the script that was used to generate the data. The package source tarball is only 1.2 M so hopefully it's ok to keep them in the package. When I suggested that **BiocCheck** checks for the presence of `.log` files a few years ago, the primary use case was to find TeX/LaTeX artifacts that we often see in the `vignettes/` folder (e.g. `.log`, `.tex`, `.aux`, and `.toc` files). It's always a mistake to include those files in the package. But for files located under `inst/` things are less clear, and maybe **BiocCheck** could only issue a warning in that case?

Thanks,
H.

**Comment by hpages** [comment]
Ok so that's the best I can do. I need the `Sys.setenv()` calls unless there's a better way to specify the git user that doesn't rely on a `.gitconfig` file. I also want to keep the `.log` files in the package.

I went thru the **BiocCheck** NOTEs and they're all signaling things that are actually intended (it would be nice if the count of function lines didn't include empty lines or lines of comments).

Thanks,
H.

**Comment by LiNk-NY** [comment]
Thanks for making those changes! It looks good to me. 
I can update the error to a warning for .log files in `/inst`.

**Comment by LiNk-NY** [comment]
**Update**:

> I went thru the **BiocCheck** NOTEs and they're all signaling things that are actually intended (it would be nice if the count of function lines didn't include empty lines or lines of comments).

I was able to parse R files and remove empty lines in `BiocCheck` but I can't get rid of the comments because of the way that `parseFile` works. Even if the actual comment text is removed in the parsed data `data.frame`, the line indices in the data do not change resulting in the same calculation of line numbers. It's a little complicated but it's better to not remove lines that contain comments because they may also contain code. 

Best,
Marcel

**Comment by hpages** [comment]
I see. Well, never mind. At least the NOTE about function length is only a note so helps remind people about the importance of breaking down complicated logic into small/simple functions. Thanks for taking a look at this!

H.

**Comment by LiNk-NY** [comment]
One compromise is to remove lines that are _only_ comments, i.e., start with a `#`. 
I can look into this a bit further. 
Thanks!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpages.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("updateObject")`. The package 'landing page' will be created at

https://bioconductor.org/packages/updateObject

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
