### ISSUE TITLE
Rbwa

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#2511]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jfortin1/Rbwa

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Jfortin1** [comment]
Hi Nitesh @nturaga,

Thank you for reviewing my package. The error above comes form the fact that the Windows machine is trying to build the package while I did specify in the DESCRIPTION file that it's UNIX only.

**Comment by lshep** [comment]
By eliminating Windows you will lose nearly half of Bioconductor users;  is there no way to implement a solution on windows? 
If you would like to proceed with excluding windows,  Please create a `.BBSoptions` file in the top level of your package repository (dot and caps matter) and include a single line in the file `UnsupportedPlatforms: win` .

**Comment by Jfortin1** [comment]
Hi @lshep, I would also like to make the package accessible to all users, but `BWA` itself was not built with Windows machines in mind. I did attempt to modify the source code to make it windows-friendly, but I was unsuccessful as some of the core libraries used are unix only.

**Comment by Jfortin1** [comment]
Good morning, is there something I can do to move this forward? I would like to submit `crisprBwa` soon so that we can also submit our major package for CRISPR gRNA design called `crisprDesign`.

**Comment by nturaga** [comment]
Hi @Jfortin1 I'll send you the package review today. Can you issue a new build please?

**Comment by nturaga** [comment]
# Review 

## DESCRIPTION

ok

## NAMESPACE

ok

## man

ok 

## tests

good

## src

- I'm guessing this is just the BWA source code copied into the `src` folder?

## R

- Use `system2` instead here: https://github.com/Jfortin1/Rbwa/blob/master/R/xa2multi.R#L65, it's more robust than `system`. The same change should be made in other places where `system` is used.

- Overall, good code. 

## Vignette

This line seems incomplete - https://github.com/Jfortin1/Rbwa/blob/master/vignettes/Rbwa.Rmd#L35

**Comment by Jfortin1** [comment]
Thank you @nturaga. I've now addressed your reviews (see below) and pushed the latest version:


## src

I'm guessing this is just the BWA source code copied into the src folder?

JP: yes.

## R

Use system2 instead here: https://github.com/Jfortin1/Rbwa/blob/master/R/xa2multi.R#L65, it's more robust than system. The same change should be made in other places where system is used.

JP: thank you for the suggestion; I've now changed `system` to `system2` everywhere in the package

## Vignette

This line seems incomplete - https://github.com/Jfortin1/Rbwa/blob/master/vignettes/Rbwa.Rmd#L35

JP: indeed, removed now. thanks!

**Comment by nturaga** [comment]
Thanks, @Jfortin1 ! Package accepted.

Hope things are well otherwise.

**Comment by Jfortin1** [comment]
Thanks @nturaga !

**Comment by Jfortin1** [comment]
Hi @nturaga, I still cannot see Rbwa in https://www.bioconductor.org/checkResults/3.15/bioc-LATEST/#C -- do I need to do anything else?

**Comment by nturaga** [comment]
@lshep will better answer this question.


Nitesh Turaga
Scientist II, Department of Data Science,
Bioconductor Core Team Member
Dana Farber Cancer Institute

**Comment by lshep** [comment]
I have not run the ingest for accepting packages yet.  I will do so shortly.  Once that occurs the package will appear in the build report within 48 hours.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rbwa")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rbwa

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Jfortin1** [comment]
ah thanks @lshep !
