### ISSUE TITLE
MsBackendMsp

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#2518]
Short info: `MsBackendMsp` adds support for files in MSP format to the `Spectra` Bioconductor package and hence allows to import and export mass spectrometry data from (to) such files.

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RforMassSpectrometry/MsBackendMsp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'MsBackendMsp' Review
The package passed check and build. Test coverage is 92.86%, awesome job!
However there are several minor things need to be fixed.
## The .Rbuildignore file
- [ ] NEWS.md now supported by CRAN and doesn't need to be ignored.

## General package development
- [ ] Non-standard file/directory found:
    ‘logo.png’

## R code
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/functions-msp.R:
		+ at line 70 found '    spv <- Spectra:::.SPECTRA_DATA_COLUMNS'
		+ at line 79 found '    res$mz <- IRanges::NumericList(res$mz, compress = FALSE)'
		+ at line 80 found '    res$intensity <- IRanges::NumericList(res$intensity, compress = FALSE)'
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/functions-msp.R:
		+ at line 65 found '    for (i in seq_along(sp))'
		+ at line 72 found '    for (i in seq_along(res)) {'
		+ at line 127 found '        for (name in names(dup_res))'
		+ at line 238 found '    for (m in mult) {'
- [ ] Remove unused code.
	* In file R/MsBackendMsp.R:
		+ at line 171 found '              ## object$centroided <- TRUE'

**Comment by jorainer** [comment]
Thanks for the detailed review @jianhong !

I've addressed all your points (see https://github.com/rformassspectrometry/MsBackendMsp/commit/0e6d8765dd19f844ada7dba141345bbe5ff7975d) except some of the `for` loops. *Real* vectorization is unfortunately not possible in these cases and `lapply` IMHO does not improve (and in some cases is also not easily possible):

- `for` loop in lines [69-74](https://github.com/rformassspectrometry/MsBackendMsp/blob/master/R/functions-msp.R#L69-L74): I'm looping here over the columns (should be fast anyway) and need to get also the name of the column. With `lapply` I could also loop over the columns, but would not have access to the names of the columns (which I need in the `spv[col][1]` call to determine the expected data type of that column).

- `for` loop in lines [124-125](https://github.com/rformassspectrometry/MsBackendMsp/blob/master/R/functions-msp.R#L124-L125): I did also not find a better (vectorized) solution to this one.

- `for` loop in lines [235-239](https://github.com/rformassspectrometry/MsBackendMsp/blob/master/R/functions-msp.R#L235-L239): same as for the first `for` loop. Would work also with `lapply` if I would not need in addition the column name within the loop.

I'm happy if you (or @lshep ?) could suggest a better vectorized solution to these `for` loops - I could not come up with a better solution. 

Thanks again for the detailed code review!

**Comment by lshep** [comment]
I think in this use case it is acceptable to leave the for loops. Cheers

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsBackendMsp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsBackendMsp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
