### ISSUE TITLE
UCell

### ISSUE THREAD

**Issue by mass-a** [Bioconductor/Contributions#2520]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/carmonalab/UCell

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mass-a** [comment]
I pushed an update to the origin repo aimed at improving interoperability (v1.99.1).

UCell signature scoring can now take directly as input a SingleCellExperiment object, and returns results in a SingleCellExperiment structure as well. This functionality was previously available, but unnecessarily stored in a separate function. 

Cheers!

**Comment by mass-a** [comment]
Hello @vjcitn
what else should be done from our side to get the package into the review stage?

Thanks,
-m

**Comment by mass-a** [comment]
Thanks in advance for taking the time to review our package!

There is now 1 warning related to the package version. The method has been published and cited by other publications with versions > 1.0, it would probably be confusing to roll back the version numbering. Is that an option to come into BioC starting with version 2.0?

-m

**Comment by lazappi** [comment]
This is probably a question for the core team. Maybe @lshep can jump in?

**Comment by lshep** [comment]
Yes we can make an exception for this.  The recommended action is what you currently have:  1.99.0 so that when officially released in Bioconductor it will automatically be bumped to 2.0.0.

**Comment by lazappi** [comment]
Hi @mass-a

Thanks for submitting **UCell** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: There are some notes from `BiocCheck::BiocCheck()` in the build report. Please address these as much as possible.

## DESCRIPTION file

- [ ] :warning: It is recommended to add a URL to the `BugReports` field. Usually this is for the package GitHub issues page or the Bioconductor support form.
- [ ] :warning: It is recommended to add a URL to the `URL` field. Usually this is to the package GitHub repository (you can also give multiple URLs).

## NAMESPACE file

- [ ] :warning: Function names should use `camelCase` or `snake_case` rather than a mix or `UpperCamelCase`. For example `storeUCellRankings()` rather than `StoreRankings_UCell()`.

## The NEWS file

- [ ] :green_circle: Please try to keep the `NEWS` file up to date

## Package data

- [ ] :rotating_light: Please add more documentation for the sample dataset. This should include information about the source of the data, any processing done to it etc.

## Documentation

### README

- [ ] :rotating_light: Please use Bioconductor installation instructions in the `README`

### Vignette

- [ ] :rotating_light: Please add a namespace check for **{BiocManager}** to the Bioconductor installation instructions

```r
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("UCell")
```

- [ ] :warning: It is good to show how to set the parameter for running on multiple cores but 4 four cores may not always be available depending on where the vignette is being run.

### Man pages

- [ ] :warning: It is recommended to add a package man page, see https://r-pkgs.org/man.html#man-packages or `usethis::use_package_doc()`
- [ ] :rotating_light: Please make the examples in man pages runnable unless there is a reason this cannot be done
- [ ] :rotating_light: There are some references to the **{future}** package which should be removed as it is no longer used

## Code

### R

- [ ] :rotating_light: Please remove the `seed` argument which is no longer used
- [ ] :rotating_light: Please use accessor functions for Seurat objects rather than `@` or `slot()`
- [ ] :warning: Please consider adding validity tests for function arguments
- [ ] :rotating_light: When using **{BiocParallel}** users should be able to choose how parallelisation is done. This should be done by having a `BPPARAM` argument which takes a `BiocParallel::bpparam()` object (rather than creating it inside a function).

**Comment by mass-a** [comment]
Hello Luke,
thanks for the review!

Please find my responses below.


> ## General package development
> 
>     * [ ]  ⚠️ There are some notes from `BiocCheck::BiocCheck()` in the build report. Please address these as much as possible.

Most notes should be solved now. There are a few long lines and lines not indented by 4, but these are mostly auto-generated by roxygen for the man pages.
 
> 
> ## DESCRIPTION file
> 
>     * [ ]  ⚠️ It is recommended to add a URL to the `BugReports` field. Usually this is for the package GitHub issues page or the Bioconductor support form.

Done.

>     * [ ]  ⚠️ It is recommended to add a URL to the `URL` field. Usually this is to the package GitHub repository (you can also give multiple URLs).

Done.

> 
> ## NAMESPACE file
> 
>     * [ ]  ⚠️ Function names should use `camelCase` or `snake_case` rather than a mix or `UpperCamelCase`. For example `storeUCellRankings()` rather than `StoreRankings_UCell()`.
> 

This is the only point I am reluctant about. Renaming all the functions would probably cause problems to active users and compatibility with existing pipelines. There are at least two other packages that I know of that depend on UCell ([escape](https://github.com/ncborcherding/escape) and [scGate](https://github.com/carmonalab/scGate)). If there is flexibility on this point I would prefer not to rename the functions.


> ## The NEWS file
> 
>     * [ ]  🟢 Please try to keep the `NEWS` file up to date

Added a new entry with the most recent updates.

> 
> ## Package data
> 
>     * [ ]  🚨 Please add more documentation for the sample dataset. This should include information about the source of the data, any processing done to it etc.

Added a short description of the test dataset and reference to original publication.

> ## Documentation
> ### README
> 
>     * [ ]  🚨 Please use Bioconductor installation instructions in the `README`

Added Bioc installation instructions.

> ### Vignette
> 
>     * [ ]  🚨 Please add a namespace check for **{BiocManager}** to the Bioconductor installation instructions
> 
> 
> ```r
> if (!requireNamespace("BiocManager", quietly=TRUE))
>     install.packages("BiocManager")
> BiocManager::install("UCell")
> ```

Done.

>     * [ ]  ⚠️ It is good to show how to set the parameter for running on multiple cores but 4 four cores may not always be available depending on where the vignette is being run.

I have set to eval=FALSE the chunk that shows how to run on multiple cores, so it outlines the syntax without actually running the code. I hope this is what you were suggesting.

> ### Man pages
> 
>     * [ ]  ⚠️ It is recommended to add a package man page, see https://r-pkgs.org/man.html#man-packages or `usethis::use_package_doc()`

Thanks for the suggestion, done.
 
>     * [ ]  🚨 Please make the examples in man pages runnable unless there is a reason this cannot be done

Done.

>     * [ ]  🚨 There are some references to the **{future}** package which should be removed as it is no longer used

Done.

> ## Code
> ### R
> 
>     * [ ]  🚨 Please remove the `seed` argument which is no longer used

Done.

>     * [ ]  🚨 Please use accessor functions for Seurat objects rather than `@` or `slot()`

I have re-written the code and examples to avoid using @ and slot()
 
>     * [ ]  ⚠️ Please consider adding validity tests for function arguments

Added some parameter format checks.

>     * [ ]  🚨 When using **{BiocParallel}** users should be able to choose how parallelisation is done. This should be done by having a `BPPARAM` argument which takes a `BiocParallel::bpparam()` object (rather than creating it inside a function).

Good point. I have implemented both: a user can either give a `BiocParallel::bpparam()` object, or specify the number of cores as an integer. The vignette was updated to use the BPPARAM parameter for parallel processing.

That's it!
-massimo

**Comment by lazappi** [comment]
Thanks! I have a few follow up comments but overall I think this is looking pretty good and we can probably approve this once you respond to these.

> This is the only point I am reluctant about. Renaming all the functions would probably cause problems to active users and compatibility with existing pipelines. There are at least two other packages that I know of that depend on UCell ([escape](https://github.com/ncborcherding/escape) and [scGate](https://github.com/carmonalab/scGate)). If there is flexibility on this point I would prefer not to rename the functions.

I think this is probably reasonable as this is a more mature package than average. @lshep please jump in if the core feels more strongly about this.

> Added a short description of the test dataset and reference to original publication.

Could you please add what processing has been done to the data, if any (i.e. what the matrix values are)? Also it took me a while to find where in the code this was so maybe worth moving to a `datasets.R` file (up to you though).

> I have set to eval=FALSE the chunk that shows how to run on multiple cores, so it outlines the syntax without actually running the code. I hope this is what you were suggesting.

That's a reasonable approach I think, maybe worth mentioning in the text that it isn't run though. The other alternative I was thinking of was to run the code but just set the number of workers to 1. Slightly less good as an example but then you don't have to worry about checking the code is still up to date.

> Good point. I have implemented both: a user can either give a BiocParallel::bpparam() object, or specify the number of cores as an integer. The vignette was updated to use the BPPARAM parameter for parallel processing.

Great! Maybe add to the documentation that `BPPARAM` overrides `ncores` and that if `ncores` is used then it uses `BiocParallel::MulticoreParam()`.

**Comment by mass-a** [comment]
Thanks @lazappi!

your comments are all well taken.

> Could you please add what processing has been done to the data, if any (i.e. what the matrix values are)? Also it took me a while to find where in the code this was so maybe worth moving to a datasets.R file (up to you though).

Moved the test data documentation to a dedicated `datasets.R` file, and included details about the processing.

> That's a reasonable approach I think, maybe worth mentioning in the text that it isn't run though. The other alternative I was thinking of was to run the code but just set the number of workers to 1. Slightly less good as an example but then you don't have to worry about checking the code is still up to date.

I finally went for your second suggestion: setting `workers=1` and explaining in writing how the behavior can be altered to parallelise execution.

> Great! Maybe add to the documentation that BPPARAM overrides ncores and that if ncores is used then it uses BiocParallel::MulticoreParam().

Updated the documentation to clarify this point, along the lines of your suggestion.

Thanks again and let me know if you see anything else.

Best,
-m

**Comment by lazappi** [comment]
I'm happy with this so I will mark it as approved. Congratulations on getting **{UCell}** into Bioconductor 🎉! It can take a few days for the build system to pick things up but the package should be part of Bioconductor devel soon.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mass-a.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("UCell")`. The package 'landing page' will be created at

https://bioconductor.org/packages/UCell

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
