### ISSUE TITLE
bandle

### ISSUE THREAD

**Issue by ococrook** [Bioconductor/Contributions#2521]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ococrook/bandle

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ococrook** [comment]
@lazappi The error relates so being on the mailing list but I am subscribed - how long does that take to go through so I dont keep sending in builds that are going to fail?

**Comment by lshep** [comment]
@ococrook Did you confirm subscription?  Normally there is a confirmation step that sometimes ends up in peoples spam folders?

**Comment by ococrook** [comment]
I thought so, I'll try again

**Comment by lshep** [comment]
I do see you registered @lazappi  if this ERROR continues please ignore.  If it continues I will look further into it.

**Comment by ococrook** [comment]
I triggered another build, so we can see if ERRORs again

**Comment by lazappi** [comment]
@ococrook I will try to review this next week. In the meantime please try to address the warnings in the build report.

**Comment by lazappi** [comment]
Hi @ococrook

Thanks for submitting **bandle** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :rotating_light: There are warnings from `R CMD check` in the build report (I also got these locally). Please address these.
- [ ] :warning: There are also warnings from `BiocCheck::BiocCheck()`. Please address these as much as possible.

## DESCRIPTION file

- [x] :green_circle: Please capitalise "Bioconductor" in the `Description` field
- [x] :rotating_light: There are some licensing issues around depending on the **{akima}** package ([see here](https://github.com/Oshlack/splatter/issues/108) for some more information). I would strongly suggest replacing this with another package if it is at all possible.

## NAMESPACE file

- [x] :rotating_light: Please use `importFrom` instead of `import` to import dependecies
- [x] :rotating_light: Please export individual functions using the `@export` **{roxygen2}** tag rather than `exportPattern("^[[:alpha:]]+")`

## The NEWS file

- [x] :rotating_light: Please make sure there is at least one entry in the `NEWS` file and that versions match package versions

## Documentation

- [x] :green_circle: I noticed some minor typos in various parts of the documentation. The `usethis::use_spell_check()` function can be used to add automatic spell checking.

### README

- [x] :warning: Please use Bioconductor installation instructions in the `README`

### Vignette

- [x] :rotating_light: Please add an *Installation* section to the _Getting started_ vignette.
  - This should use Bioconductor installation instructions
  - The installation code chunk should **NOT** be evaluated (`eval = FALSE`)
- [x] :green_circle: I would suggest echoing the chunks that load packages so that users can clearly see what packages are used in the vignette
- [x] :green_circle: I think this sentence is incomplete? _"We visualise the data by using principal"_

### Man pages

- [x] :warning: You have combined documentation for a lot of functions into the same page (plotting and the `bandle` functions for example). I think this will be confusing for users so I suggest having an individual page for each function. You could still have overview pages that link to the individual functions if you want.

## Unit tests

- [x] :rotating_light: There is a `Rplots.pdf` file in the `tests/` directory. Please remove this.

## Code

### R

- [x] :rotating_light: Please use `vapply` instead of `sapply`
- [x] :rotating_light: Please use accessor functions rather than `@` and `slot()` as much as possible (sometimes this is unavoidable)
- [ ] :rotating_light: Please don't `require()` packages inside functions. Import them as needed instead.
- [x] :warning: Please check if any of the `for` loops can be avoided
- [x] :warning: Please separate analysis from plotting. By that I mean functions which are performing analysis should not produce plots as side effects.
- [x] :warning: Similarly, plotting functions should not return other outputs
- [x] :warning: Plotting functions that use **{ggplot2}** should return a `ggplot` object. Please do not print the object inside the function.
- [x] :warning: There are standard recommended names for files containing S4 classes (`AllClasses.R`, `methods-???.R`), see https://contributions.bioconductor.org/r-code.html?q=AllClasses#rcode-file-names
- [x] :green_circle: I love how thorough your argument checks are :tada:! If you want to you can probably combine your `stopifnot()` statements into a single function call which could be a bit neater.

```r
stopifnot(
    "Condition 1" = TRUE,
    "Condition 2" = FALSE,
    ...
)
```

- [x] :green_circle: Rather than using `utils::globalVariables()` to define variables used in **{ggplot2}** code you can use `.data$var`, see https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html

### C and Fortran code

- [x] :warning: Please check that your C code checks for user interruptions

**Comment by ococrook** [comment]
Thanks Luke, will get around to these asap

**Comment by ococrook** [comment]
Hi @lazappi 

Trying to fix a couple of things but there are two things that I don't make sense to me at the moment. The first is the warning from R CMD Check pertains to:

`Warning: multiple methods tables found for 'bin'
Warning: multiple methods tables found for 'compareSpectra'`

However, we don't import `bin` or `compareSpectra` from any packages, so I'm not sure how to remove this warning. 

The second is removing the `require(Biobase)` from inside the function. When I do this, I get the following error message from running the main function in the package:

`Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error: could not find function "exprs"`

Even though `exprs` is explicitly called from the Biobase package and `exprs` is imported from Biobase in the NAMESPACE.

You can reproduce these errors by navigating to the develop branch and simply trying compile the vignette. Any hints would be much appreciated.

**Comment by lazappi** [comment]
> `Warning: multiple methods tables found for 'bin' Warning: multiple methods tables found for 'compareSpectra'`

The build report isn't available anymore so I can't properly check but I think this happens when two packages create the same generic. I suspect this is not coming from your package (because I don't think you define either of these) so for now address the other comments and we will see if this is still happening on the build system.

> The second is removing the `require(Biobase)` from inside the function. When I do this, I get the following error message from running the main function in the package:
> 
> `Error: BiocParallel errors 1 remote errors, element index: 1 0 unevaluated and other errors first remote error: could not find function "exprs"`
> 
> Even though `exprs` is explicitly called from the Biobase package and `exprs` is imported from Biobase in the NAMESPACE.
> 
> You can reproduce these errors by navigating to the develop branch and simply trying compile the vignette. Any hints would be much appreciated.

Could you provide a more specific example? I was able to build the vignettes using your `develop` branch without any issue.

**Comment by lshep** [comment]
@lazappi  you can view older build reports at http://staging.bioconductor.org:8000/

**Comment by lazappi** [comment]
@ococrook Did you have any luck with these issues?

**Comment by ococrook** [comment]
Still going in circles with the biobase build warning, will clear up the other issues in the next couple of days.

**Comment by lmsimp** [comment]
@lazappi Once released am I able to have commit access to bandle please, if possible? (CC: @ococrook)

I was reading you are only allowed one sole maintainer listed on any package, but I can be given access to commit to the repo by requesting it through [bioc-devel@r-project.org]() (which is what I also read online [here](https://bioconductor.org/developers/package-guidelines/))

Quoting:
> Only one person should be listed as the Maintainer to ensure a single point of contact. This person by default will have commit access to the git repository on [git.bioconductor.org](http://git.bioconductor.org/). Commit access can be given to other developers by request on the bioc-devel mailing list.

I’ve been reading the maintainer docs and am registered on support and devel mailing list, I can’t add my ssh key (which i think is through this form https://git.bioconductor.org/BiocCredentials/account_activation/) as I need to given access first).

Also, @ococrook can you tick off the above and trigger a new build as I am currently unable to. Thanks 👍

**Comment by lazappi** [comment]
> @lazappi Once released am I able to have commit access to bandle please, if possible? (CC: @ococrook)

This needs to be handled by the core Bioconductor team. I would suggest emailing the mailing list after the package has been accepted.

For some reason the bot hasn't replied with the build report from your latest commit but you can see it here http://staging.bioconductor.org:8000/job/17229/. It looks like there are still some issues with timeouts and errors so please look into those.

**Comment by ococrook** [comment]
Hi @lazappi, the MLinterfaces package seems to not appear on the Mac build but available in bioconductor. This is causing the current error on mac

**Comment by ococrook** [comment]
> Hi @ococrook
> 
> Thanks for submitting **bandle** 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.
> 
> Luke
> 
Thank you for the review, we very much appreciate the time taken.

> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [ ]  🚨 There are warnings from `R CMD check` in the build report (I also got these locally). Please address these.
> * [ ]  ⚠️ There are also warnings from `BiocCheck::BiocCheck()`. Please address these as much as possible.

A warning remain from `R CMD check` from calling require(biobase) in side the code. After many attempt to get to the bottom of this warning. The code fails in windows from biocparrallel when this is removed. Somehow Biobase is not exported when using SnowParams(). I can force the error on a branch in bandle if you want to reproduce yourself.

I also note a cryptic warning from the compiled code, will attempt a fix now but want to put everything else here first.


> ## DESCRIPTION file
> * [x]  🟢 Please capitalise "Bioconductor" in the `Description` field

done
> * [x]  🚨 There are some licensing issues around depending on the **{akima}** package ([see here](https://github.com/Oshlack/splatter/issues/108) for some more information). I would strongly suggest replacing this with another package if it is at all possible.

switched to the interp package
> 
> ## NAMESPACE file
> * [x]  🚨 Please use `importFrom` instead of `import` to import dependecies

done
> * [x]  🚨 Please export individual functions using the `@export` **{roxygen2}** tag rather than `exportPattern("^[[:alpha:]]+")`
> 
done
> ## The NEWS file
> * [x]  🚨 Please make sure there is at least one entry in the `NEWS` file and that versions match package versions

done 
> ## Documentation
> * [x]  🟢 I noticed some minor typos in various parts of the documentation. The `usethis::use_spell_check()` function can be used to add automatic spell checking.

fixed as many typos as I could find
> ### README
> * [x]  ⚠️ Please use Bioconductor installation instructions in the `README`

done 
> ### Vignette
> * [x]  🚨 Please add an _Installation_ section to the _Getting started_ vignette.
>   * This should use Bioconductor installation instructions
>   * The installation code chunk should **NOT** be evaluated (`eval = FALSE`)

done 
> * [x]  🟢 I would suggest echoing the chunks that load packages so that users can clearly see what packages are used in the 
vignette

done 

> * [x]  🟢 I think this sentence is incomplete? _"We visualise the data by using principal"_
completed sentence

> ### Man pages
> * [x]  ⚠️ You have combined documentation for a lot of functions into the same page (plotting and the `bandle` functions for example). I think this will be confusing for users so I suggest having an individual page for each function. You could still have overview pages that link to the individual functions if you want.

seperated documentation

> ## Unit tests
> * [x]  🚨 There is a `Rplots.pdf` file in the `tests/` directory. Please remove this.

removed

> ## Code
> ### R
> * [x]  🚨 Please use `vapply` instead of `sapply`

done, except in two cases. One were sapply return NULL and the other when it was designed to check the object validity.

> * [x]  🚨 Please use accessor functions rather than `@` and `slot()` as much as possible (sometimes this is unavoidable)

these have been changed 

> * [ ]  🚨 Please don't `require()` packages inside functions. Import them as needed instead.

not yet changed due parrellelisation issue

> * [x]  ⚠️ Please check if any of the `for` loops can be avoided

where possible have replaced for loops with vapply's (there are a lot in the package because we use monte-carlo which requires dependency on previous iterations.

> * [x]  ⚠️ Please separate analysis from plotting. By that I mean functions which are performing analysis should not produce 
plots as side effects.

Apologies for this, we have remove this an added a new class and method to handle this.

> * [x]  ⚠️ Similarly, plotting functions should not return other outputs

We have correct this also.

> * [x]  ⚠️ Plotting functions that use **{ggplot2}** should return a `ggplot` object. Please do not print the object inside the function.

We have corrected this

> * [x]  ⚠️ There are standard recommended names for files containing S4 classes (`AllClasses.R`, `methods-???.R`), see https://contributions.bioconductor.org/r-code.html?q=AllClasses#rcode-file-names

We have renamed and reorganised some files

> * [x]  🟢 I love how thorough your argument checks are 🎉! If you want to you can probably combine your `stopifnot()` statements into a single function call which could be a bit neater.
> 
> ```r
> stopifnot(
>     "Condition 1" = TRUE,
>     "Condition 2" = FALSE,
>     ...
> )
> ```

These statements have been cleared up.

> * [x]  🟢 Rather than using `utils::globalVariables()` to define variables used in **{ggplot2}** code you can use `.data$var`, see https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html

We have remove using `utils::globalVariables()` with a couple of fixed .data$var did not always work 

> ### C and Fortran code
> * [x]  ⚠️ Please check that your C code checks for user interruptions

We now check for user interruptions in long C code.

**Comment by lazappi** [comment]
> A warning remain from `R CMD check` from calling require(biobase) in side the code. After many attempt to get to the bottom of this warning. The code fails in windows from biocparrallel when this is removed. Somehow Biobase is not exported when using SnowParams(). I can force the error on a branch in bandle if you want to reproduce yourself.

Ok. I have looked into this a bit and I think this is correct that the library needs to be loaded within the function to work properly with `SnowParam`. I guess if you want to support that then this is unavoidable. I would suggest adding a comment explaining why this is done for anyone who looks at the code in the future.

> > * [x]   🚨 Please use `importFrom` instead of `import` to import dependecies
> 
> done
> 
> > * [x]   🚨 Please export individual functions using the `@export` **{roxygen2}** tag rather than `exportPattern("^[[:alpha:]]+")`
> 
> done

It's fine if you want to do this manually but usually it's easier to use the `@export` and `@importFrom` tags and let **{roxygen2}** populate the `NAMESPACE` file for you.

> > * [x]   🚨 Please add an _Installation_ section to the _Getting started_ vignette.
> >   
> >   * This should use Bioconductor installation instructions
> >   * The installation code chunk should **NOT** be evaluated (`eval = FALSE`)
> 
> done

Please use the standard Bioconduction installation chunk here.

`````
```{r, eval=FALSE}
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("bandle")
```
`````

> > * [x]   🚨 Please use `vapply` instead of `sapply`
> 
> done, except in two cases. One were sapply return NULL and the other when it was designed to check the object validity.

I think you can probably rewrite these to avoid `sapply()`. The plotting one would maybe be better as a for loop (because nothing is returned). The validity one is more complex, I couldn't quite work out what was going on there.

**Comment by ococrook** [comment]
Hi @lazappi 

I have added a note about the `require` inside the function.

I find `roxygen2` often creates problems when there is `cpp` code, so prefer to do imports and export manually.

I've added the Bioconductor install chunk you sugget. 

I've rewritten to avoid the sapply's

**Comment by lazappi** [comment]
Thanks! I will mark this as accepted now 🎉! It can take a few days to be picked up by the build system but then the package should be part of Bioconductor devel and the next release. You will probably continue to see warnings from the build system so if come across another solution to the `require()` problem at some stage that would be prefereable.

**Comment by ococrook** [comment]
Thanks @lazappi, I'll revist the `require()` issue fairly frequently to see if we can remove it.

**Comment by lazappi** [comment]
One idea I should have thought of earlier. If it is only for `SNOWParams()` that this is needed you could put it inside an if statement. That would probably avoid it being needed for most users and possibly let you pass the checks without the warning.

**Comment by ococrook** [comment]
I can make that change, I think we'll still get a warning unfortuntaly.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ococrook.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bandle")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bandle

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
