### ISSUE TITLE
omicsViewer

### ISSUE THREAD

**Issue by mengchen18** [Bioconductor/Contributions#2523]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mengchen18/omicsViewer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
remember to change the BugReports and URL in the description to point to the newly named repo.

**Comment by mengchen18** [comment]
Thanks. The links are fixed now.

**Comment by lshep** [comment]
As the above message indicates, please push changes to git.bioconductor.org to trigger a new build report before a review will continue.  Cheers,

**Comment by mengchen18** [comment]
> 

@lshep Thanks. A new build has done. Just for me to confirm, should I still do something else before the review?

**Comment by lshep** [comment]
Nope. @nturaga  will review the package in the next few weeks. Cheers

**Comment by nturaga** [comment]
# Review 

## DESCRIPTION

- ok

- The depedency tree of this package is pretty big, please check to see if there any chance to trim the dependency tree.

## NAMESPACE

ok

## Dockerfile

If you use the `bioconductor_docker:devel` dockerfile, you are able to make use of many features

1. Starting next release (April 27th 2022) - Binary package
   insallation, i.e when you do, `BiocManager::install('package')`, it
   will install packages very quickly as no compilation is needed. But
   regardless, you should be using `BiocManager::install` to install
   ALL packages from both CRAN and Bioconductor.

2. You will also get a "dependable" docker image that is updated based
   on the version of the package, i.e right now, you inherit from
   rocker/shiny:4.1.2, but your package is in devel and it should work
   with R 4.2. The docker image provided by Bioconductor would take
   care of that for you. 
   
3. You might need to install "shiny"

4. The Dockerfile could be in `inst/extdata`, so it can be potentially
   distrubuted with the package.
   
## vignette

ok

## tests

- please write better tests so that you are testing the functionality
  of the package.
  
  https://shiny.rstudio.com/articles/testing-overview.html

## R 

-  There are some NOTEs in your build report that are easy to solve,
   please fix them.

**Comment by mengchen18** [comment]
Hi @nturaga , 

Thanks for your suggestions. May I ask one thing about a "note" from build report, I don't understand what means by this:

```
 * NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions
      Found in files:
        R/auxi_queryStringdb.R (line 66, column 13)
        R/auxi_queryStringdb.R (line 158, column 13)
```
The code is like:
```
  if (!is.data.frame(dd)) {
    message('stringdb error, return NULL!')
    return(dd)
  }
```
I don't have stop/warn, so which function is redundant here? Thanks.

**Comment by nturaga** [comment]
Hi, 

I see that you didn't move the Dockerfile, do you intend to distribute it with the package?

**Comment by mengchen18** [comment]
> 

Yes, I want to distribute the dockerfile together with package. Now I have moved Dockerfile to the ```inst/extdata``` folder.
The last build has a "warning" message " there is no package called DelayedArray". I will trigger another build later to see if the problem resolved.

**Comment by nturaga** [comment]
Please push your commits to GitHub as well. Your package looks ready to accept. 

Just an FYI, your Dockerfile won't work with the updated repo on Bioconductor if you have this line,

```
RUN R -e 'devtools::install_github("mengchen18/omicsViewer", dependencies = FALSE)'
```

Please update that to just install with BiocManager.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mengchen18.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("omicsViewer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/omicsViewer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
