### ISSUE TITLE
ASURAT

### ISSUE THREAD

**Issue by keita-iida** [Bioconductor/Contributions#2524]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/keita-iida/ASURAT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for the nice submission and vignette.  Don't use 
```
urlpath <- "https://github.com/keita-iida/ASURATDB/blob/main/transcriptome/"
load(url(paste0(urlpath, "pbmc_counts.rda?raw=true")))
```
Are the PBMC data the ones from TENx?  If so use the Bioconductor package https://bioconductor.org/packages/release/data/experiment/html/TENxPBMCData.html ... if not, prepare an ExperimentHub contribution.

**Comment by keita-iida** [comment]
We appreciate your careful review.
According to the suggestion, we added TENxPBMCData package to the DESCRIPTION file and fixed the vignettes.
We have done R CMD check and BiocCheck.

Keita Iida

**Comment by keita-iida** [comment]
We appreciate Bioconductor's careful review.
Getting the above message, we look forward hearing from the reviewer's instructions.

Keita Iida

**Comment by nturaga** [comment]
# Review 

## DESCRIPTION 

ok

## NAMESPACE

ok 

## src

I'm surprised you didn't find a fast implementation of bubble sort in C++ in the form a library. But this is good to know. 

## R 

- Why are you making a data.frame and then referencing individual columns again. Just use the "sce" directly. This is inefficient coding.

https://github.com/keita-iida/ASURAT/blob/968948296a7d33925bd1a681e2d46dce61151110/R/create_signs.R#L38

- Use `seq_along` instead of `seq_len(length(genes_vari))`. Same everywhere, will give you similar result.

## Vignettes 

ok

## man

ok

## General

Check the build report for some NOTEs which are easily solvable.

**Comment by keita-iida** [comment]
Dear Nitesh Turaga,

I appreciate all of your careful review.
Following your instruction, I fixed some R functions.
However, there is one point that I kept as it was.

Understanding your first comment for R, I tried replacing the data.frame with direct use of sce.
However, using SummerizedExperiment functions, such as rowData(sce), is very time-consuming, especially in loops.
Hence, I took back that part as it was.
But many thanks again.

Just before, I pushed an updated version, ASURAT ver. 0.99.10.
Could you consider releasing ASURAT from Bioconductor?

Sincerely yours,
Keita Iida

**Comment by nturaga** [comment]
I will see the new build report and if it is clean I'll accept it. 

Please issue another build, after your changes.

**Comment by keita-iida** [comment]
I really thanks your line-by-line review, that greatly improved ASURAT.
Sincerely yours,
Keita Iida

**Comment by nturaga** [comment]
You still need to issue a version bump for a new build report. I cannot review the package a second time without a new build report. 

http://contributions.bioconductor.org/bioconductor-package-submissions.html#whattoexpect

```
To trigger a new build, include a version bump in your commit, e.g., from Version: 0.99.0 to Version: 0.99.1. Pre-release versions utilize the 0.99.z format. 
```

**Comment by keita-iida** [comment]
I apologize for my mistake.
I pushed a new version, increasing the package version from 0.99.10 to 0.99.11.
Sincerely yours,
Keita Iida

**Comment by nturaga** [comment]
I still don't see a new build.

**Comment by keita-iida** [comment]
I appreciate your message.
I felt strange because I have not yet gotten any build report after pushing an updated package.
I followed the instruction in [this page](https://bioconductor.org/developers/how-to/git/new-package-workflow/).
Hence, I am afraid to ask you to check the following push commands (here "$" is a terminal prompt):
$ git remote add upstream git@git.bioconductor.org:packages/ASURAT.git
$ git remote -v
$ git merge upstream/master
$ git merge origin/main
$ git add .
$ git commit -m "(something)"
$ git push upstream main:master
$ git push origin main

Sincerely yours,
Keita Iida

**Comment by nturaga** [comment]
I only see the commands, not the output of the commands. Please paste the output of the commands.

**Comment by keita-iida** [comment]
Many thanks.
I see, I will try again soon, increasing the version number from 0.99.11 to 0.99.12.

**Comment by lshep** [comment]
it looks like there might be an issue with our windows builder that is not producing reports. investigating

**Comment by keita-iida** [comment]
I am sorry but I got some error as follows:

$ git remote add upstream git@git.bioconductor.org:packages/ASURAT.git
error: remote upstream already exists.
$ git remote -v
origin	https://github.com/keita-iida/ASURAT (fetch)
origin	https://github.com/keita-iida/ASURAT (push)
upstream	git@git.bioconductor.org:packages/ASURAT.git (fetch)
upstream	git@git.bioconductor.org:packages/ASURAT.git (push)
$ git merge upstream/master
Already up to date.
$ git merge origin/main
Already up to date.
$ git add .
$ git commit -m "Increase the version number from git 0.99.11 to 0.99.12."    
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

**Comment by nturaga** [comment]
Don’t worry about that error, it’s just saying you’ve already run this command previously and have the remote upstream added.

> 
> ASURAT$git remote add upstream ***@***.***:packages/ASURAT.git
> error: remote upstream already exists.

From the looks of it, @lshep is taking a look at why a build isn’t getting triggered.

**Comment by keita-iida** [comment]
I appreciate a lot.
Now I understood the situation.

**Comment by keita-iida** [comment]
Now I got the build report, producing WARNINGS and TIMEOUT, but it may look strange.
The build times between Linux and macOS are too different.
I think I should wait for the next announcement from Bioconductor.

**Comment by lshep** [comment]
The build time even for linux is 10 min which is quite long.  The mac has been timing out since your initial submission.

**Comment by keita-iida** [comment]
Many thanks for your message.

**Comment by lshep** [comment]
There is something specific not allowing your package to post the build report. This ERROR is on our end and I'm looking into a solution.  You can monitor builds from [here](http://staging.bioconductor.org:8000/jobs/1638/ ) to see the latest report.  Note still getting a mac timeout.

**Comment by keita-iida** [comment]
I appreciate your massage.
I will further reduce some data size to pass the mac building.

**Comment by keita-iida** [comment]
Fortunately, I confirmed that ASURAT passed both macOS and Linux builds.
Many thanks again.

**Comment by nturaga** [comment]
I don't understand why there are no windows builds here.

**Comment by lshep** [comment]
@nturaga this is on us.  Ive announced in multiple times to reviewers. Please review without windows while I'm investigating palamino3 activity on the SPB

**Comment by keita-iida** [comment]
Now I saw the message.
I deeply appreciate the greatest help of @nturaga, @Ishep, others in Bioconductor, and the contributor.

Sincerely yours,
Keita Iida

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/keita-iida.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ASURAT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ASURAT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
