### ISSUE TITLE
MobilityTransformR

### ISSUE THREAD

**Issue by LiesaSalzer** [Bioconductor/Contributions#2526]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LiesaSalzer/MobilityTransformR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Do not use
```
The <code>MobilityTransformR</code> package can be installed directly from 
GitHub using 

devtools::install_github("LiesaSalzer/MobilityTransformR")
```
in your vignette.  Please see the guidelines.  Even if it is eval=FALSE this code should not be given in the vignette of a Bioconductor package submission.

**Comment by LiesaSalzer** [comment]
Thank you for the feedback! I changed it in the last commit into:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("MobilityTransformR")
```

**Comment by HelenaLC** [comment]
Overall, things are in pretty good shape already. Here a couple comments, most of which are for your consideration and not mandatory:

# README

- [ ] Please include Bioconductor installation instructions using `BiocManager`.

# DESCRIPTION

- [ ] We would encourage an R dependency of >= 4.2.

- [ ] Consider expanding on `biocViews`  
(some suggestions are given in the `BiocCheck` report)

# documentation

- [ ] Consider adding a package *.man* page (`?MobilityTransformationR`)  
so users would be directed to the main functions of the package.

- [ ] Please add details on the example data under `inst/extdata`  
as well as its source information (e.g., under a `?data` man page).

# vignette

- [ ] Lines 20-22: The package (& its version) as well as the complication data  
can be included in the HTML header via *package: "`r BiocStyle::pkg_ver('MobilityTransformationR')`"* and *date: "`r BiocStyle::doc_date()`"*, respectively. Also, I think the last modification date could be removed, as this will always be linked to the package version built on the Bioc server.

- [ ] Nothing wrong here, but you can use single back-ticks  
to highlight code instead of \<code>...\</code> (much easier to type & read!).

- [ ] To direct users to relevant external packages  
and highlight/make them distinguishable from general code,  
you can hyperlink them via  `BiocStyle::CRANpkg("package_name")`  
(or `Githubpkg` or `Biocpkg`, depending on where the package sits).

- [ ] Super minor, but there's a "dataframe" in line 159  
that should probably be written as "\`data.frame`"  
(i.e., using code highlighting and adding ".")

# R/

- [ ] Consider having a look at some of coding style guidelines [here](https://bioconductor.org/developers/how-to/coding-style/).  
While these are *recommendations*, it's nice to be consistent  
(e.g., we recommend 4 space tab indentation).  
Some code looks rather messy and is difficult to read mostly because  
indentation is inconsistent (mix of 2 spaces & vertical alignment)  
and produces a lot of white space.

- [ ] Might be worth resolving this in the build report:
```r
* NOTE: Avoid using '=' for assignment and use '<-' instead
  Found in files:
    R/transform.R (line 117, column 9)
    R/transform.R (line 122, column 9)
    R/transform.R (line 128, column 9)
```


# coverage

- looks great!

```r
# devtools::test_coverage()
MobilityTransformR Coverage: 100.00%
R/getMt.R: 100.00%
R/transform.R: 100.00%
```

**Comment by LiesaSalzer** [comment]
Hi @HelenaLC , 
Thank you very much for reviewing my code! It was very helpful. 
I tried to address all you comments in my last commit. 
I think except of some minor style issues all of the points were addressed. 
Really looking forward to the next steps of Bioconductor submission!

**Comment by HelenaLC** [comment]
- There's currently a `README.md` and `README`,  
please remove the latter (blank) one.

- As I said previously, in the vignette, I'd recommend    
directing users to relevant external packages (e.g., line 59).  
You can hyperlink them via `BiocStyle::CRANpkg("package_name")`  
(or `Githubpkg` or `Biocpkg`, depending on where the package sits).

- I am not too familiar with MS data, but the example data is currently quite  
large (installed size is 7.8Mb, 6.7Mb of which are data). If there's a way to    
further reduce this, besides filtering on `rt` and `mz`, that'd be great.  

- I can see that you documented the example data in `inst/extdata/`,  
however, the documentation is currently not being generated  
(i.e., there's no corresponding `.Rd` page under `man/`).  
To have e.g. `devtools::document()` generate this, there has    
to be a function definition under the roxygen documentation.  
In this case, you can simply add `NULL` (without "#'"), i.e., in `data.R`:

```
#' @name data
#' ...
#' ...
#' ...
#' @author Liesa Salzer
NULL
```

**Comment by LiesaSalzer** [comment]
Thanks again for this feedback @HelenaLC !! 
I just made a commit with you requested changed (if possible): 

> There's currently a README.md and README,
> please remove the latter (blank) one.

Done! I probably missed it before. 

> As I said previously, in the vignette, I'd recommend
> directing users to relevant external packages (e.g., line 59).
> You can hyperlink them via BiocStyle::CRANpkg("package_name")
> (or Githubpkg or Biocpkg, depending on where the package sits).

Thanks for pointing that out again! Now I know how to do it :)


> I am not too familiar with MS data, but the example data is currently quite
> large (installed size is 7.8Mb, 6.7Mb of which are data). If there's a way to
> further reduce this, besides filtering on rt and mz, that'd be great.

To answer that question I need to explain a little bit more of the functions: 
So `mobilityTransformR `can handle different inputs, i.e. numeric vectors, `Spectra `Objects (From the `Spectra `Package, which is also on BioC) and `OnDiskMSnExp `Objects (from the `MSnBase `Package, which is on BioC). 
However, because most users that have e.g. Metabolomics data, will work with functions from `Spectra  `and `MSnbase`. 
But to load data using these packages, the input data needs to have more requirements then simply the `mz `and `rt `values. And this is the reason why I cant reduce them further :/ 
If the data size is still to big, do you think it would be possible then to outsource the data to an external source somehow? 


> I can see that you documented the example data in inst/extdata/,
> however, the documentation is currently not being generated
> (i.e., there's no corresponding .Rd page under man/).
> To have e.g. devtools::document() generate this, there has
> to be a function definition under the roxygen documentation.
> In this case, you can simply add NULL (without "#'"), i.e., in data.R:

Done. Sorry, I didn't know that.

**Comment by HelenaLC** [comment]
If I remember correctly, @lgatto, you're familiar with MS data? Could you advise whether it is possible to reduce `.mzML` data for use in examples or how other packages deal with file size limitations? Currently, the data is filtered based on `rt` and `mz` (see comments above) Any input would be greatly appreciated 🙏

**Comment by LiesaSalzer** [comment]
> If I remember correctly, @lgatto, you're familiar with MS data? Could you advise whether it is possible to reduce .mzML data for use in examples or how other packages deal with file size limitations? Currently, the data is filtered based on rt and mz (see comments above) Any input would be greatly appreciated 🙏

Or maybe also @jorainer ?

**Comment by jorainer** [comment]
Filtering by `rt` is usually a good first thing to do. I assume you have centroided data? If not you could centroid it. Let me know if you need help on that.

The ideal thing would be to add this file to the `msdata` package maybe? That's where we have most of our (small) test files. Best to contact @sneumann or @lgatto if you want to add the file there.

**Comment by LiesaSalzer** [comment]
Thanks @jorainer for the response! 
I already have centroid data :) 

I will talk to Steffen about `msdata`, thanks for that suggestion!

**Comment by jorainer** [comment]
Yes, I think that would be the best/cleanest solution.

**Comment by LiesaSalzer** [comment]
Hi @HelenaLC 
Now the data was moved to the `msdata` package, which is currently in the Bioc development version. 
I replaced therefore in the vignette and unit test loading the data into: 
```
fl <- dir(system.file("CE-MS", package = "msdata"), 
          full.names = TRUE)
```
and added `msdata (>= 0.35.3)` in `suggest` in the `DESCRIPTION`. 
When I run the vignette on my computer everything runs fine, but as you can see I am getting repeatedly the error message from the build report: 
```
Quitting from lines 124-130 (MobilityTransformR.Rmd) 
Error: processing vignette 'MobilityTransformR.Rmd' failed with diagnostics:
invalid subscript type 'list'
```
And I have no idea how to solve this :( 

Do you have any suggestions?

**Comment by jorainer** [comment]
maybe just increase the version to start a new build? Maybe it takes some time for the `msdata` to be properly available/installed on the build machines?

**Comment by lshep** [comment]
I just went on merida1 (macos) and tested the code manually and it seems to work so I would agree to wait it out and see if it clears up on its own.  If it doesn't let me know and I can investigate further. Please also remove `MobilityTransformR.html` from the vignette directory; vignettes should be built through the build/check process automatically.

**Comment by LiesaSalzer** [comment]
Thanks @lshep for checking! 
I removed the `.html` file from the package (it was not intended to be there) and I will wait some more days to see if it will work. :)

**Comment by LiesaSalzer** [comment]
@HelenaLC finally all the issues were solved

**Comment by HelenaLC** [comment]
Great, thanks, looks all good to me now. Just a minor comment: There's no right / wrong,  
but perhaps consider improving on code style consistency and legibility with time.  
E.g., just a few things worth noting (nothing major):

- You almost entirely use 4-space tab indentation, but  
vertical alignment in the function definitions only.

- Lines 93+ in `getMt.R` would be easier to comprehend  
if function call after a pipe would go into a new line

- In `transform.R` lines 333+, `fData(xTransf)$fileIdx == i` occurs 4x!  
and the code is really broken up / hard to read. In general, I'd recommend  
voiding any exact code repeats, defining intermediate variables, and  
separating compute & assign when the computation is long

```
# this...
fData(xTransf)[fData(xTransf)$fileIdx == i, ]$retentionTime <-
  convertMtime(
    x = rt_file[[i]] / 60,
    rtime = marker[marker$fileIdx == i, ]$rtime / 60,
    mobility = marker[marker$fileIdx == i, ]$mobility,
    tR = tR, U = U, L = L
  )
fData(xTransf)[fData(xTransf)$fileIdx == i, ] <-
  fData(xTransf)[fData(xTransf)$fileIdx == i, ][order(fData(
    xTransf
  )[fData(xTransf)$fileIdx == i, ]$retentionTime), ]
  
# ...(I think) could be written as
marker_i <- marker[marker$fileIdx == i, ]
rt <- convertMtime(
  x = rt_file[[i]] / 60,
  rtime = marker_i$rtime / 60,
  mobility = marker_i$mobility,
  tR = tR, U = U, L = L)
  
j <- fData(xTransf)$fileIdx == i
fData(xTransf)[j, ]$retentionTime <- rt
fData(xTransf)[j, ] <- fData(xTransf)[j, ][order(rt), ]
```

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiesaSalzer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MobilityTransformR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MobilityTransformR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
