### ISSUE TITLE
PSMatch

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/Contributions#2529]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rformassspectrometry/PSMatch

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lgatto** [comment]
The error is 
```
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .
```

but I confirm that I have an account - see https://support.bioconductor.org/u/5645/

**Comment by lshep** [comment]
Its because the email in the description for the maintainer is different than the registered email on the support site.

**Comment by lgatto** [comment]
I have changed it on the support site just now.

**Comment by lgatto** [comment]
Hello - I pushed a minor update on github (version 0.99.1 with some typos fixed and some rephrasing) and I would have assumed that it would have propagated here. Or not?

**Comment by lgatto** [comment]
Error above addressed: I have now added the package to my watched tags on the support site.

**Comment by Kayla-Morrell** [comment]
@lgatto - great, I'm working on the initial review now and should have it posted by tomorrow.

**Comment by lgatto** [comment]
Thank you @Kayla-Morrell - no hurry at all, and thank you for reviewing the package.

**Comment by Kayla-Morrell** [comment]
@lgatto - Sorry for the delay!
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        SequenceMatching

## NEWS

- [x] REQUIRED: When I ran BiocCheck::BiocCheck() on the package I got a WARNING
  that the NEWS file was malformed. I don't see anything unusual about the
formatting. My only suggestion would be to move the date from line 5 to line 3
after the heading. Something like: ` ## Changes in 0.99.1 (2022-03-04)`. Also i
think the bullet points need to be '+' instead of '-'. 

## Vignettes

- [x] REQUIRED: The vignettes should include an Installation section that
  demonstrates to the user how to download and load the package from
Bioconductor.

## Man pages

- [x] REQUIRED: Add non-empty \value sections to the following man pages:
        man/ConnectedComponents.Rd

## R code

- [ ] REQUIRED: Avoid sapply(); use vapply() if possible. Found in files:
        R/PSM-reduce.R, line 23
- [ ] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods. Found in files:
        R/PSM-class.R, lines 203, 204, 207, 208, 212, and 213
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 81
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 326 lines that are not.

Best,
Kayla

**Comment by lgatto** [comment]
- The `SequenceMatching` tag really doesn't apply. 
- I can't change the `sapply()` in `PSMatch-reduce.R` to a `vapply()` because de point here is to verify if the output is converted to a list or a vector. 
- I confirm that the `cat()` is used in the `show()` method, but not directly, it's called in the `show()`'s subfunction `showDetails()`.  
- I checked the lines > 80 character: they are properly formatted and can't really be shortened.
- Regarding the indentation, I leave this to my editor emacs. 
- I have updated the `ConnectedComponents` man page. 
- I have added installation instructions to the vignette, 
- I can't reproduce the issue with the NEWS.md file using BiocCheck version 1.31.36. I'm pretty sure it's neither the bullet points (I use the `-` in all other packages), nor the date (which I also often put at the end of the bullet point when there are multiple bullet points/changes per version). I have removed it for now as it wasn't really important here, hoping it sorts the issue. 

Version 0.99.2 with the changes on its way.

**Comment by Kayla-Morrell** [comment]
@lgatto - Thank you for making the necessary changes, I have looked them over and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lgatto** [comment]
Thank you for your review @Kayla-Morrell

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgatto.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PSMatch")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PSMatch

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
