### ISSUE TITLE
biotmle

### ISSUE THREAD

**Issue by nhejazi** [Bioconductor/Contributions#254]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nhejazi/biotmle

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nhejazi** [comment]
@bioc-issue-bot @mtmorgan 

Based on the build outputs, it appears that the there are two severe problems with the package:

1. `Warning: file 'biomarkertmleOut.rda' has magic number 'versi'` - this appears to be induced by the use of `git-lfs` to store the larger data set (~30MB) for compliance with Bioconductor standards. The package was building fine on Travis-CI prior to this, but `git-lfs` seems to induce some kind of data corruption. Is there some recommended workaround for BioC compliance?

2. `ERROR: At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not: biomarkertmle.Rd` - while this error is self-explanatory, it currently is not possible to include a runnable example for this function (it typically takes on the order of hours, with parallelization). There is an example included using `dontrun{...}` for the sake of clarity. Based on my past experience using BioC packages, there are several that take quite long to run, so I would guess there is some established workaround, though I have had trouble locating this in the BioC policies.

Any help/recommendations would be much appreciated.

**Comment by mtmorgan** [comment]
I think the issue with 1. is a build system configuration issue, requiring git-lfs to be installed; we ( @lshep ) will address this. But the constraint is on built tarball size rather than repository size, so the fact that the data is in git-lfs is not a solution. How is the data used? If as an 'annotation' resource or 'experiment' (example) data then the data should be separated into an annotation or experiment data package, or annotation or experiment hub resource. From the help page it looks like experimental results.

The runnable examples test is there both to ensure that the user has a reasonable 'ground truth' from which to understand how to use the function for their own purposes, and as a way to 'test' code. It's important to create realistic if artificial examples that execute in a timely manner, so I would encourage you to develop reduced example that can be used here and in the vignette (and in formal unit tests, which are recommended but not required).

**Comment by nhejazi** [comment]
@mtmorgan @lshep 

In regard to the two issues raised about the package:

1. The data sets included with package are indeed experimental data, but they are modified such that they would not be expected to be of use for biological research (i.e., these are examples only, and that is why I felt it would be best to leave them as part of the package rather than packaging them for submission separately). I see that I misunderstood the size constraint; it appears that even with Git LFS, the size of the data might make the package unsuitable for submission (at least for now...).

2. I certainly agree with the sentiment behind the requirement of packages having runnable examples, and I include examples where appropriate in all other functions. I will look into re-structuring the example for this function to make it runnable. After the package builds successfully on Travis and Appveyor with this new example, I will trigger another build through the Bioc bot.

**Comment by nhejazi** [comment]
@mtmorgan @lshep 

The outstanding error related to running examples has now been resolved. The remaining warnings appear to be due to a requirement to set the R version to 3.4. Additionally, was there a specific recommendation I missed on how to properly deal with the size of the data (~30MB)?

**Comment by mtmorgan** [comment]
- The NMF package seems to have been broken by the current version of
  grid -- processing the vignette leads to

        > heatmap_biotmle(x = limmaTMLEout, designMat = design, FDRcutoff = 0.05,
        +                 top = 25)
        Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
          object 'L_currentViewport' not found
        In addition: Warning message:
        In (function (display = "", width, height, pointsize, gamma, bg,  :
          X cannot set locale modifiers
        > traceback()
        13: get(name, envir = asNamespace(pkg), inherits = FALSE)
        12: grid:::L_currentViewport at grid.R#36
        11: grid.Call(grid:::L_currentViewport) at grid.R#43
        10: current.viewport() at grid.R#51
        9: f_current.vpPath()
        8: current.vpPath_patched()
        7: heatmap_motor(mat, border_color = border_color, cellwidth = cellwidth,
               cellheight = cellheight, treeheight_col = treeheight_col,
               treeheight_row = treeheight_row, tree_col = tree_col, tree_row = tree_row,
               filename = filename, width = width, height = height, breaks = breaks,
               color = color, legend = legend, annTracks = annTracks, annotation_legend = annotation_legend,
               txt = txt, fontsize = fontsize, fontsize_row = cexRow * fontsize,
               fontsize_col = cexCol * fontsize, main = main, sub = sub,
               info = info, verbose = verbose, gp = gp)
        6: NMF::aheatmap(as.matrix(biomarkerTMLEout_top), scale = "row",
               Rowv = TRUE, Colv = NULL, annCol = annot, annColors = "Set2",
               main = paste("Heatmap of Top", top, "Biomarkers", "( FDR =",
                   FDRcutoff, ")"))
        5: heatmap_biotmle(x = limmaTMLEout, designMat = design, FDRcutoff = 0.05,
               top = 25) at exposureBiomarkers.R#62
        4: eval(ei, envir)
        3: eval(ei, envir)
        2: withVisible(eval(ei, envir))
        1: source("biotmle/vignettes/exposureBiomarkers.R", echo = TRUE,
               max = Inf)

- The representation of data in the `illuminaData` set, and the
  signatures of your function calls, are not consistent with
  _Bioconductor_ data representations and best practices that
  facilitate interoperabbility and reproducibility.
  
  In particular your data and functions should use the
  SummarizedExperiment package and class. For instance, the
  illuminaData should be represented as a SummarizedExperiment

        library(SummarizedExperiment)
        rownames(illuminaData) <- illuminaData$id
        se = SummarizedExperiment(
            t(as.matrix(illuminaData[,-(1:3)])), 
            colData=illuminaData[,2:3]
        )

  The data transformation at the start of your vignette might then be
  
        colData(se) <- 
            colData(se) %>% data.frame %>% 
            mutate(age=quantile(age, 0.25)) %>% 
            DataFrame
            
  or simply `se$age = quantile(se$age, 0.25)`
            
  The 'genes' (with row and col names) are `assay(se)`.

  Likewise, `biomarkertmle()` should accept a SummarizedExperiment and
  extract relevant components inside the function, e.g., `se[1,]` for
  the first biomarker. A major benefit of this is that the
  responsibility for 'bookkeeping' to ensure that data arrives in a
  coordinated fashion from the user to the developer (of
  SummarizedExperiment, and to your function). This a strong benefit.
  
  The changes required for the above may not be as complicated as they
  sound -- you're basically implementing an interface to enable
  interoperability; the interface may well call existing functions to
  implement your compulations.
  
- The return value of `biomarkertmle` is an S3 object. In addition, it
  does not have an adequate set of methods for manipulation and
  display
  
        > methods(class="biotmle")
        [1] plot
        see '?methods' for accessing help and source code
        
  In particular, if I try to `print()` the object I get a screen full
  of numbers. Instead, I think this should be a simple sub-class of
  SummarizedExperiment, perhaps like
  
         .BiotMLE <- setClass(
             "BiotMLE",
             contains="SummarizedExperiment",
             slots=list(call="call")
         )

  (I'm not sure what `biomarkerTMLEout$topTable` will contain,
  probably `colData()`). Internally, your function would create and
  return this to the user, e.g., from your original object
  
         .BiotMLE(
             SummarizedExperiment(
                 as.matrix(biomarkerTMLEout[["tmleOut"]])
             ),
             call=biomarkerTMLEout[["call"]]
         )

  In practice, your `.BiotMLE` would be constructed to propagate the
  row and column names, and colData, of the input.


## Additional comments

DESCRIPTION, NAMESPACE, inst/CITATION, inst/NEWS

- OK

vignettes

- The 'outcomeBiomarkers.Rmd' vignette seems to be a placeholder and
  should be removed (e.g., moved to another branch in git) if the
  topic is not relevant to your package, or fully developed if it is.
- It is conventional to include a final code chunk with the output of
  the `sessionInfo()` command.
  
R

- avoid use of `1:n`, which produces surprising results when `n = 1`;
  use `seq_len(n)` or `seq_along(x)` instead.
- (Optional) Use [BiocParallel][] rather than foreach; it provides
  users with a more consistent experience in the Bioconductor universe.
- A common pattern in _R_ is to start a function with checks for valid
  parameters, allowing one to 'fail early', avoiding unnecessary
  computation and code complexity. For instance `biomarkertmle()` has
  an argument `type` that is restricted to particular values. Before
  performing any computations, the code should test the validity of
  the argument. For this particular case, one approach is to use
  
        f <- function(..., type=c("exposure", "outcome")) {
            type <- match.arg(type)
            ## rest of code
        }
        
  This fails if `type` is not one of the allowed values.

- Consider simplifying the package startup message to a single call

        packageStartupMessage(
            "biotmle: Targeted Learning for Biomarker Discovery",
            "\nVersion: ", utils::packageVersion("biotmle")
        )

man

- good, thanks for providing useful end-user documentation.

[BiocParallel]: https://bioconductor.org/packages/BiocParallel

**Comment by mtmorgan** [comment]
Have you updated your package in response to the comments? I see that a version bump is still required.

**Comment by nhejazi** [comment]
Thanks for checking in. I've noted the improvements that you suggested in the detailed review of the package, but I have yet to implement most of these changes.

**Comment by mtmorgan** [comment]
Please complete revisions this week, so that we can complete the review process.

**Comment by mtmorgan** [comment]
The deadline for adding packages to this release is this Friday. If there is no response by then I'll mark the package as 'declined'.

**Comment by nhejazi** [comment]
Apologies for the delay. Nearly all recommended changes have been made and the current form of the package passes all tests. The outstanding (required) change is conversion of the core class to a subclass of `SummarizedExperiment`.

I will bump the version number to trigger a build again, but I have had little luck fixing the error:
`no definition was found for superclass “SummarizedExperiment” in the specification of class “bioTMLE”`.

This results from the definition:
```r
.biotmle <- setClass(
        "bioTMLE",
        contains = "SummarizedExperiment",
        slots = list(call = "call",
        tmleOut = "data.frame",
        modtestOut = "data.frame",
        topTable = "data.frame")
)
```

I will continue attempting to debug the error, but if you have any advice, it would surely go more quickly.

**Comment by mtmorgan** [comment]
Likely you need to `importClassesFrom(SummmarizedExperiment, SummarizedExperiment)`, or just `import(SummarizedExperiment)`

**Comment by nhejazi** [comment]
I've now nearly completed all changes, including completing the switch to having the `bioTMLE` class being a subclass of `SummarizedExperiment`, but have one final error. Perhaps you might be able to advise just a bit further?

The package includes a method for the standard `plot` (`plot.biotmle`), which now fails when given a `bioTMLE` object (due to the S4). The error is `Error in as.vector(x, mode = "numeric") : no method for coercing this S4 class to a vector`. This is particularly odd to me, for, as written, `plot.biotmle` extracts a standard `data.frame` from a slot in the S4 object. Short of abandoning the generic and writing a custom plot function, I'm not entirely sure what the best fix might be here.

**Comment by mtmorgan** [comment]
Your class is named `bioTMLE`  but the method is for a class named `biotmle`; rename as `plot.bioTMLE`. The error you see is plot.default being invoked because there was no matching plot method. The `stopifnot()` check inside `plot.bioTMLE()` is not necessary, since only bioTMLE objects will be dispatched to the function.

**Comment by nhejazi** [comment]
AdditionalPackage: https://github.com/nhejazi/biotmleData

**Comment by nhejazi** [comment]
The current __ERROR__ tag appears to be due to some kind of failure on the Bioconductor build system. The package passed all required checks on the Linux and Windows builds but encountered this error on the Mac OS X build:
```
* Checking for bioc-devel mailing list subscription...
Error in curl::curl_fetch_memory(url, handle = handle) :
```

Please let me know if there's more I can do to make sure the package is up to Bioconductor requirements for this release.

**Comment by nhejazi** [comment]
Looks like all issues with the package have been resolved. Thank you very much for your help throughout this process -- both in recommendations for software improvement and debugging -- @mtmorgan. Please let me know if there's any more I can do to get the package up to Bioconductor standards.

**Comment by mtmorgan** [comment]
Thanks for your changes. I'm marking this package as accepted. It will be added to our svn repository and nightly builds, with additional instructions via email in a few days.
