### ISSUE TITLE
Macarron

### ISSUE THREAD

**Issue by sagun98** [Bioconductor/Contributions#2546]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biobakery/Macarron

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi @sagun98 

Thank you for your submission. Please see the review below.

Best regards,
Marcel

---

# Macarron #2546

## DESCRIPTION

* Ensure the package name in the `Description` field is updated to the new
name.
* Consider wrapping text in the `Description` field to an 80 char width limit.

## NAMESPACE

* The main function's letter case should match that of the package.
* Consider using a more descriptive name for `makeSumExp`

## vignettes/

* Update all mentions of `MACARRoN` to `Macarron` to avoid confusion and for
consistency.
* Consider using `BiocStyle` for the vignette output
* The installation of CRAN dependencies section is not necessary, those should
be automatically obtained when using `BiocManager` or even `devtools` and
`dependencies = TRUE` to include `Suggests`.
* Is there a way to include the CMD line usage (`### Options` section) in the
vignette from R? This would avoid stale documentation in the vignette.

## R

* Use the default argument inputs as preferred column names rather than taking
the first element in `se`, e.g. in `calAVA`, `metadata_variable`.
* Documentation of `metadata_variable` says column 2 but code is
`names(colData(se))[1]` is this right?
* Use variable names instead of indices wherever possible.
* Update documentation in `R/calQval.R` to reflect the name change `Macarron`.
* It is generally discouraged to write files for the user (e.g. in
`decorateID`). The user can simply save the `tax_df` in the format of their
choosing.
* Avoid code duplication where possible, e.g., both `makeDisMat` and
`Macarron` have code with `.getCorMat` and similar code in both `findMacMod`
and `Macarron`. It's harder to maintain duplicated code.
* Minor: Avoid messages like `'Summarized experiment created'`. This is what
the user expects when using `makeSumEx`.

## tests

* We strongly recommend including tests to make the code more robust. 

```
> covr::package_coverage()
Macarron Coverage: 0.00%
R/calAVA.R: 0.00%
R/calES.R: 0.00%
R/calQval.R: 0.00%
R/decorateID.R: 0.00%
R/findMacMod.R: 0.00%
R/MACARRoN.R: 0.00%
R/makeDisMat.R: 0.00%
R/makeSumExp.R: 0.00%
R/prioritize.R: 0.00%
```

**Comment by amrishabhosle** [comment]
Hi Marcel,
Many thanks for your feedback on the Macarron package. I have addressed all of your comments and you will find that the package is significantly improved from the initial commit.  Please see the point-by-point response to your feedback:

DESCRIPTION

- Ensure the package name in the Description field is updated to the new name - DONE
- Consider wrapping text in the Description field to an 80 char width limit - DONE

NAMESPACE

- The main function's letter case should match that of the package - DONE
- Consider using a more descriptive name for makeSumExp - DONE: changed to `prepInput`

vignettes

- Update all mentions of MACARRoN to Macarron to avoid confusion and for  consistency - DONE
- Consider using BiocStyle for the vignette output - DONE
- The installation of CRAN dependencies section is not necessary - This bit is now removed.
- Is there a way to include the CMD line usage (### Options section) in the vignette from R? - I have added a very short README.txt file to the `inst/scripts` folder for non-R users. 

R 

- Use the default argument inputs as preferred column names rather than taking  the first element in se, e.g. in calAVA, metadata_variable - DONE: Default is 1 and users can provide both characters or indices as inputs.
- Documentation of metadata_variable says column 2 but code is names(colData(se))[1] is this right? - This was right but I have now made changes to the code so that there is no confusion and consistency between the indices.
- Use variable names instead of indices wherever possible - Please see answer to point 1. The default variable name for `metadata_variable` is hard to define since metabolomics data comes from different experiments. I have used `metadata_variable = 1` in all functions that require this argument for consistency and ease of understanding. I have also included a formatting constraint requesting the users to prepare the metadata file appropriately. After revision, users can still provide a column name as input to arguments like `metadata_variable`, `standard_identifier` and `anchor_annotation` .
- Update documentation in R/calQval.R to reflect the name change Macarron - DONE
- Avoid writing files for users - Now, only the `Macarron::Macarron()` function writes output to a folder. This is because several useful intermediate files are created during Macarron implementation which help the user to interpret results and change parameters if required. The output folder stores all of this accessory information along with the main output files.
- Avoid code duplication where possible - DONE
-- Minor: Avoid messages like 'Summarized experiment created' - DONE

tests
- Tests have now been included.

I hope that the revisions are per your (and Bioc) expectations. Please let me know what I can do to further improve the package.

Many thanks,
Amrisha

**Comment by LiNk-NY** [comment]
Hi Amrisha, @amrishabhosle 
I don't see those changes reflected in the repository. Have you pushed to git.bioconductor.org?
See `git remote -v`
```
origin	git@git.bioconductor.org:packages/Macarron
```
Thanks!
CC: @sagun98

**Comment by sagun98** [comment]
Hi @LiNk-NY,

I just pushed the changed to  `origin git@git.bioconductor.org:packages/Macarron`. Please let us know if any further changes are required from us. 

Thanks,
Sagun

**Comment by LiNk-NY** [comment]
Hi Sagun, @sagun98
It looks like you are not subscribed to BioC-devel mailing list. Can you make sure you use the same email in both the DESCRIPTION and mailing list? 

```
  * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

Best regards,
Marcel

**Comment by sagun98** [comment]
Hi @LiNk-NY, 

Many thanks for the quick reply. I have now subscribed to BioC-devel mailing list using the same email. It should be good now. 

Thanks,
Sagun

**Comment by lshep** [comment]
Please kick off a new build report by pushing a valid version bump so we may verify.

**Comment by LiNk-NY** [comment]
Hi Sagun @sagun98 Amrisha @amrishabhosle 

Thanks for making those changes. 
Please follow up on those warnings where possible. 
Thank you for your submission. We've accepted your package. 

Best regards,
Marcel

**Comment by amrishabhosle** [comment]
Hi @LiNk-NY 
This is great news for us! We will follow up on the warnings.

Many thanks,
Amrisha

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sagun98.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Macarron")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Macarron

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
