### ISSUE TITLE
ScreenR package submission

### ISSUE THREAD

**Issue by EmanuelSoda** [Bioconductor/Contributions#2555]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EmanuelSoda/ScreenR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please correct the ERROR and trigger a new build report before a formal in-depth review will take place.

**Comment by lazappi** [comment]
There is an issue with the build report being pushed to GitHub at the moment but you can view it here http://staging.bioconductor.org:8000/job/17270/. It looks like there are still some errors to address.

**Comment by EmanuelSoda** [comment]
Thank you for the answer, one of the error is "System Files found that should not be git tracked", but I already added those files to the .gitignore file. Do you have any clue why they are still tracked?
Many Thanks

**Comment by lshep** [comment]
If they were already committed once you would have to `git rm`  them and `git commit`  for them to be removed?

**Comment by EmanuelSoda** [comment]
Ok, I'll try this way

**Comment by lshep** [comment]
We are still having issues with our windows builder preventing the build report from display (I'm actively investigating).  You can check out the recent build reports here: http://staging.bioconductor.org:8000/jobs/1646/   .

**Comment by EmanuelSoda** [comment]
Is the building report now working correctly?

**Comment by lshep** [comment]
I have temporarily removed the windows builder while I debug it, so you will able to see a mac and linux build if you push a change now.

**Comment by EmanuelSoda** [comment]
Sorry for my question.
I have to do other things or I have just to wait for the review?

Many thanks

**Comment by lazappi** [comment]
Now that the build is passing please wait for a review. I will try to do it in the next few days.

**Comment by lazappi** [comment]
Hi @EmanuelSoda

Thanks for submitting **ScreenR** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please address as many of the NOTES from `BiocCheck::BiocCheck()` as possible

## DESCRIPTION file

- [ ] :green_circle: It is recommended to add an ORCiD to your`Authors@R` field
- [ ] :warning: Bioconductor recommends setting `LazyData: False`
- [ ] :rotating_light: Please set `Depends: R (>=4.2)`
- [ ] :green_circle: It is recommended to set a `BugReports` field, this usually points to the GitHub issues page or the Bioconductor support forum
- [ ] :green_circle: It is recommended to set a `URL` field, this usually points to the GitHub repository or another package website

## NAMESPACE file

- [ ] :rotating_light: Please be consistent about naming functions using `camelCase` or `snake_case`
- [ ] :rotating_light: Please import functions selectively using `importFrom` instead of *import all* with `import`

## The NEWS file

- [ ] :rotating_light: Please check the format of the NEWS file is correct

## Package data

- [ ] :rotating_light: Please expand the data documentation, it should include what the data is, where it comes from and any associated references

## Documentation

- [ ] :green_circle: I noticed quite a few typos in the documentation, you can check for these using the **{spellcheck}** package

### Vignette

- [ ] :green_circle: You may want to consider a more meaningful name for the vignette
- [ ] 🚨 Please use the **{BiocStyle}** package for formatting the vignette
- [ ] :rotating_light: Please add a table of contents to the vignette
- [ ] :warning: Please expand the *Introduction* section with more information about the package
- [ ] :rotating_light: Please add an *Installation* section which includes Bioconductor installation instructions and is ***NOT*** evaluated
- [ ] :rotating_light: Please remove the additional files from the `vignette/` directory (only the `.Rmd` file is needed)
- [ ] :warning: I felt the vignette could do with more detail about the package functionality (what does each section of code do and what is the input/output)
- [ ] :question: Is it necessary to rename the loaded data? At the moment it feels like unnecessary variables are being created
- [ ] :question: Is RPMS the same as CPM (Counts Per Million)? If yes, please use this name which is more widely known.
- [ ] :warning: I got a warning from the code which produces the Venn diagram, please check if there is an issue here
- [ ] :warning: In general all code chunks should display messages and warnings so that the vignette is as simliar as possible to what users will see when they run the code

### Man pages

- [ ] :warning: It is recommended to add a package man page
- [ ] :rotating_light: All exported functions should have runnable examples

## Unit tests

- [ ] :green_circle: If you find it useful the test scan be separated into multiple files to help organise things

## Code

### R

- [ ] :rotating_light: Is it necessary to create a custom class or could you use a standard Bioconductor object such as `SummarizedExperiment`?
- [ ] :rotating_light: If you do need to have your own class then it should have implemented getting and setting functions
- [ ] :rotating_light: Check that function names describe what the function does (I think there is one plotting function that in unclear)
- [ ] :rotating_light: Some of the function argument documentation is very limited, please expand this
- [ ] :rotating_light: Please check that optional function arguments have reasonable defaults
- [ ] :warning: Consider adding checks that exported functions are provided with valid input

**Comment by lshep** [comment]
@EmanuelSoda  may we expect updates soon? We like to see progress in a 3-4 week time frame to keep the review process moving.

**Comment by EmanuelSoda** [comment]
@lshep I'm sorry for the delay, there were crazy day at work. I'm working on it. I'll push the updated version as soon as possible.

**Comment by EmanuelSoda** [comment]
Sorry for my late replay, I have tried to address all the reviews comment. I have just few doubts/points left to ask:

❓is it necessary to rename the loaded data? At the moment it feels like unnecessary variables are being created

In order to use some of the ScreenR the name of the column of the count table has to be separated by “_”. The vignetta shows an example in which this is not the case and so it shows how to do that in order to enable ScreenR to work properly. 


❓ Is RPMS the same as CPM (Counts Per Million)? If yes, please use this name which is more widely known.

Yes, sorry I have changed the name in CPM. 

⚠️ I got a warning from the code which produces the Venn diagram, please check if there is an issue here
I checked the warning unfortunately this does not depend on my code but is due to another package ScreenR uses to create the venn diagram. I have sent to the creator of the package a pull request in order to fix this bug but I haven’t received any answer yet. Anyway is just a  warning due  to wrong parsing but it doesn’t affect the result displayed.


🚨 Is it necessary to create a custom class or could you use a standard Bioconductor object such as SummarizedExperiment?
ScreenR uses an own object that now has getter and setter methods. 

🚨 Please check the format of the NEWS file is correct
Sorry, what do you mean? Can you please tell me the correct format for the NEWS file? I have created this NEWS file using biocthis::use_bioc_news_md()

Thanks a lot 
Emanuel

**Comment by EmanuelSoda** [comment]
I have pushed again but the massage from the bot did not appeared

**Comment by lshep** [comment]
Did you include a version bump?  It will only rebuild with a version bump and push to git.bioconductor.org

**Comment by EmanuelSoda** [comment]
Yes, you are right! My bad, I'm very new to this. Do you have any clue why on linux is giving me that error? Those function are not present anymore because are now in camel_case.

**Comment by lshep** [comment]
linux is case sensitive.  So while you have changed to lowercase in the DESCRIPTION collate,  you need to also rename your files in the R directory to match.

**Comment by EmanuelSoda** [comment]
Hi @lazappi when you have time you can take a look to the changes that I have made

**Comment by lazappi** [comment]
Hi @EmanuelSoda 

Sorry, I missed this was now passing checks. I will try to take a look this week.

Luke

**Comment by lazappi** [comment]
> ❓is it necessary to rename the loaded data? At the moment it feels like unnecessary variables are being created
> 
> In order to use some of the ScreenR the name of the column of the count table has to be separated by “_”. The vignetta shows an example in which this is not the case and so it shows how to do that in order to enable ScreenR to work properly.

Ok. This should be mentioned in the text of the vignette so that it is clear to the user why this is done.

> 🚨 Is it necessary to create a custom class or could you use a standard Bioconductor object such as SummarizedExperiment?
> ScreenR uses an own object that now has getter and setter methods.

Could you explain why you feel it is necessary to have a custom object? It looks like most of the functionality requires converting to a `DGEList` anyway so maybe the package could be build around that instead? Resuing standard objects makes it much easier for users to combine Bioconductor packages in their workflows and reduces the maintenance burden for developers.

> 🚨 Please check the format of the NEWS file is correct Sorry, what do you mean? Can you please tell me the correct format for the NEWS file? I have created this NEWS file using biocthis::use_bioc_news_md()

Yeah, this looks fine. I can't remember why I commented on this originally.

### Further comments

- The dataset documentation still doesn't include a source. There should be a reference or at least a URL for where the data came from. 
- You have defined setter and getter generics for your object but I couldn't find any implementation of these?
- Please add a table of contents to the vignette
- There is no need to include manual installation instructions in the vignette. Bioconductor installation instructions should be sufficient (and maybe GitHub if you really feel that's necessary). Please use the standard Bioconductor installation chunk.
- Messages and warnings are still turned off for a lot of the code in the vignette.
- There is a small typo in the name of `ScreenR-pacakage.R`

**Comment by EmanuelSoda** [comment]
Hi @lazappi thanks for the answer.  
I have a doubts or questions Here some points: 
 
**Could you explain why you feel it is necessary to have a custom object?**
The idea at the base of ScreenR is to perform a **DE analysis** of shRNAs associated to genes in a **tidy** way to do this the ScreenR object contains all the information to perform this type of analysis and it try to take care of how the analysis is implemented in a low level (for example transforming the ScreenR object in a DGEList or using the data_table to perform operation or plot data).
  
 
**You have defined setter and getter generics for your object but I couldn't find any implementation of these?**
 Sorry but I didn't quite get the question. I have defined generics in the generics.R file using the **setGeneric()** function and then I have used the **setMethod()** ( in the **screenr-class.R** file) to implement the methods associated to **screenr_object** the specific signature. Is this not enough? If not, could you please explain how to implement those functions?
 
 
**Please add a table of contents to the vignette**
 I have used the following configuration in the YAML block but I don't know why it does not show the table of content. Do you have any suggestions on this?
 
```
output: 
    BiocStyle::html_document:
    toc: true
```
 
**The dataset documentation still doesn't include a source. There should be a reference or at least a URL for where the data came from**
 The data comes from un still unpublished shRNAs synthetic lethality screening perform in my lab for this reason I cannot add a link right now. But basically, we followed the Cellecta protocol as reported in the web page. If is this really a problem a could try to find some already published data online.

**Comment by lazappi** [comment]
> Hi @lazappi thanks for the answer. I have a doubts or questions Here some points:   **Could you explain why you feel it is necessary to have a custom object?** The idea at the base of ScreenR is to perform a **DE analysis** of shRNAs associated to genes in a **tidy** way to do this the ScreenR object contains all the information to perform this type of analysis and it try to take care of how the analysis is implemented in a low level (for example transforming the ScreenR object in a DGEList or using the data_table to perform operation or plot data). 

I think you could probably have done that with an existing object but it should be ok if you think there is enough reason for a custom one. In the future it might be worth providing exported functions which allow the user to convert to some of the more standard formats.

> **You have defined setter and getter generics for your object but I couldn't find any implementation of these?**  Sorry but I didn't quite get the question. I have defined generics in the generics.R file using the **setGeneric()** function and then I have used the **setMethod()** ( in the **screenr-class.R** file) to implement the methods associated to **screenr_object** the specific signature. Is this not enough? If not, could you please explain how to implement those functions?

Somehow I managed to miss these, I just had a quick look and they should be ok.

>**Please add a table of contents to the vignette**  I have used the following configuration in the YAML block but I don't know why it does not show the table of content. Do you have any suggestions on this?  
> 
> ```
> output: 
>     BiocStyle::html_document:
>     toc: true
> ```

This should be fine. Obviously I wasn't really awake when I checked this, sorry about that.

>   **The dataset documentation still doesn't include a source. There should be a reference or at least a URL for where the data came from**  The data comes from un still unpublished shRNAs synthetic lethality screening perform in my lab for this reason I cannot add a link right now. But basically, we followed the Cellecta protocol as reported in the web page. If is this really a problem a could try to find some already published data online.

I will leave this up to you. I think ideally the data should be public so that users can see all the details if they are interested (also that means you don't have to share your unpublished data). If you do keep what you have currently then I think you need to add some more detail about what the data is (another reason to use public data, you can just point to the original description). Let me know what you decide to do but I think this is probably the last thing to sort out.

**Comment by EmanuelSoda** [comment]
Hi @lazappi, now should be all good. Let me know If there are other issue to address. 

Thanks Emanuel

**Comment by lazappi** [comment]
Hi @EmanuelSoda. I am happy with the dataset documentation now so I'm going to approve this. Congratulations for getting the package into Bioconductor 🎉! It can take a couple of days to be picked up by the build system but then it should be part of Bioconductor devel.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/EmanuelSoda.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ScreenR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ScreenR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
