### ISSUE TITLE
ATACCoGAPS

### ISSUE THREAD

**Issue by rossinerbe** [Bioconductor/Contributions#2557]
- Repository: https://github.com/FertigLab/ATACCoGAPS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
There is no content in the vignette.  Please remedy.  "Tutorial files" set should be managed in a compliant way.

**Comment by rossinerbe** [comment]
Thanks, I migrated the file previously labeled tutorial over to the vignette and have removed the non-compliant files.

**Comment by vjcitn** [comment]
```
--- re-building ‘ATACCoGAPS.Rmd’ using rmarkdown
Loading required package: CoGAPS
Quitting from lines 36-39 (ATACCoGAPS.Rmd) 
Error: processing vignette 'ATACCoGAPS.Rmd' failed with diagnostics:
there is no package called 'repmis'
--- failed re-building ‘ATACCoGAPS.Rmd’

SUMMARY: processing the following file failed:
  ‘ATACCoGAPS.Rmd’

Error: Vignette re-building failed.
```
Need in Suggests in DESCRIPTION?

**Comment by vjcitn** [comment]
```
[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-2)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-3)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-4)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-5)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-6)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-7)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb1-8)[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb2-1)#installing required Bioconductor packages
BiocManager::install(c("GenomicRanges", "projectR", "TFBSTools", "GeneOverlap", "msigdbr", "motifmatchr", "chromVAR", "GenomicFeatures", "IRanges", "fgsea", "rGREAT", "Homo.sapiens", "Mus.musculus"))

#installing latest version of CoGAPS algorithm
devtools::install_github("FertigLab/CoGAPS")

#installing ATACCoGAPS
devtools::install_github("FertigLab/ATACCoGAPS")
Attach the ATACCoGAPS package, which attaches CoGAPS as a dependency

library(ATACCoGAPS)
To outline the ATACCoGAPS pipeline, we will use as an example data set single-cell ATAC sequencing data containing 10 cell lines, published by Schep et al, 2017. The data was downloaded from GEO accession number GSE99172 and preprocessed using dataSubsetBySparsity() from the ATACCoGAPS package to remove cells and peaks with more than 99% sparsity (more than 99% zeroes). For the code used in preprocessing this data, see: https://github.com/rossinerbe/ATACCoGAPS-Analysis-Code/blob/master/Schep_data_analysis/main_analysis_peak_summarization.Rmd[](http://127.0.0.1:12914/library/ATACCoGAPS/doc/ATACCoGAPS.html#cb3-1)

repmis::source_data("https://github.com/FertigLab/ATACCoGAPS/blob/PaperVersion/data/schepFilteredData.rda?raw=true")
## Downloading data from: https://github.com/FertigLab/ATACCoGAPS/blob/PaperVersion/data/schepFilteredData.rda?raw=true
## SHA-1 hash of the downloaded data file is:
## ec9a9d3cc915ef91f52ca05727b037d3e67a6835
## [1] "schepFilteredData"
```
you should not be downloading data from github for your vignette.  it should be in ExperimentHub.  @lshep

**Comment by vjcitn** [comment]
also the various installation instructions do not belong in the vignette.  see the guidelines for the standard advice.

**Comment by rossinerbe** [comment]
Okay, I refactored the vignette to use a subset of the data that's small enough to reasonably include under data/
I also used the subset to make the examples easier to run.

I removed installation instructions from the vignette as well

And I added the repmis package to Suggests

Thanks for your help!

**Comment by vjcitn** [comment]
```
ℹ Updating ATACCoGAPS documentation
Error in read_dcf(con) : Duplicate DESCRIPTION fields: 'Suggests'
```
please fix this.  it kill devtools::document

**Comment by vjcitn** [comment]
Do you build/check your package on a "clean" system with no presuppositions?
```
PC002284:SUBMISSIONS vincentcarey$ R CMD build ATACCoGAPS
1/11 packages newly attached/loaded, see sessionInfo() for details.
* checking for file 'ATACCoGAPS/DESCRIPTION' ... OK
* preparing 'ATACCoGAPS':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘ATACCoGAPS.Rmd’ using rmarkdown
Loading required package: CoGAPS
Quitting from lines 31-34 (ATACCoGAPS.Rmd) 
Error: processing vignette 'ATACCoGAPS.Rmd' failed with diagnostics:
object 'schepSubCellTypes' not found
--- failed re-building ‘ATACCoGAPS.Rmd’
```

**Comment by vjcitn** [comment]
```
PC002284:SUBMISSIONS vincentcarey$ ls ATACCoGAPS/data
schepCelltypes.rda	schepCogapsResult.rda	schepGranges.rda	schepPeaks.rda		subsetSchepData.rda
```
is it an orthography problem?

**Comment by rossinerbe** [comment]
Sorry, I did test the build so I'm not sure how that got through. I think I must have tested the build from the master branch, while the updated package was still in the update branch. Both things should be fixed now.

**Comment by lshep** [comment]
I am having trouble processing your package because your biocViews are invalid -- I will manually force this through but you need to update biocViews to be valid.  biocViews are not package names they need to come from the list of terms http://bioconductor.org/packages/release/BiocViews.html#___Software .   Make sure you have run BiocCheck on your package as well as this should have been indicated in the output of the checks.

**Comment by lshep** [comment]
You can not store data on github.  that is not allowed. It must be on a trusted public server (institution, AWS S3 buckets, microsoft data lakes, zenodo, etc) or in the Bioconductor experimenthub.  See [Creating a Hub package](https://bioconductor.org/packages/devel/bioc/vignettes/HubPub/inst/doc/CreateAHubPackage.html)

**Comment by rossinerbe** [comment]
okay, those two things should be fixed, along with the biocCheck errors. Thanks for your help

**Comment by lshep** [comment]
Sorry about the delay. Not sure if you were waiting for a build report. It seems it has stalled. I'm kicking off a manual build now. please address any timeout, error, or warnings

**Comment by rossinerbe** [comment]
Okay, thanks. Looks like there were some problems with the examples. Those should be fixed now

**Comment by rossinerbe** [comment]
The error I'm getting is that I am not subscribed to the bioc-devel mailing list. I have tried to subscribe but it does not seem to be finding me. Do I just need to wait for it to be processed or something?

**Comment by lshep** [comment]
Have you checked your spam/junk folder? The confirmation email often gets labelled as spam

**Comment by rossinerbe** [comment]
Ah, yep, that was it. I should be subscribed now. Thanks

**Comment by rossinerbe** [comment]
Do these warnings need to be resolved?

**Comment by Kayla-Morrell** [comment]
@rossinerbe - I can review the package with WARNINGs but I'll most likely have them as something that needs to be addressed in your review. So up to you if you want to address them now or once I've posted the review.

**Comment by rossinerbe** [comment]
Okay, I fixed the warning related to docs, the others seem like they might not need to be addressed. Please let me know though

**Comment by rossinerbe** [comment]
@lshep I think the build report has stalled again. Could you please try restarting?

**Comment by rossinerbe** [comment]
@Kayla-Morrell could you do the review please and see if the warnings need to be addressed?

**Comment by Kayla-Morrell** [comment]
@rossinerbe - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: In the README file the installation instructions for ATACCoGAPS
should demonstrate to the user how to install from Bioconductor not from your
github.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 3.5.0 to 4.2.0.
- [ ] REQUIRED: '::' or ':::' import in vignette not declared from 'viridis'. I
  would add this package to the 'Suggests' field since it is only used in the
vignette.
- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
      Transcription, Sequencing, Microarray, Pathways, Bayesian,
      Clustering, GeneExpression, RNASeq, ImmunoOncology,
      DifferentialExpression, GeneSetEnrichment, MultipleComparison,
      GO, DimensionReduction, TimeCourse
- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field which
  includes the relevant link to GitHub for reporting Issues. 

## NAMESPACE

- [ ] REQUIRED: Consider adding to your NAMESPACE file:
	`importFrom("grDevices", "rainbow")`
	`importFrom("graphics", "legend", "par")`
	`importFrom("stats", "p.adjust")`
	`importFrom("utils", "head")`
- [ ] REQUIRED: Namespaces in Imports field not imported from. All declared
  Imports should be used.
- [ ] REQUIRED: Package in Depends field not imported from. This package needs
  to be imported from (in the NAMESPACE file) for when this namespace is loaded
but not attached.

## Vignette

- [ ] SUGGESTION: We strongly encourage the use of the BiocStyle package for
  formatting.
- [ ] REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the objective, models, unique functions, key points etc
that distinguish the package from othere packages in the same area. Be sure to
include a short motivation for the package in general as well as motivation for
inclusion of the package in Bioconductor.
- [ ] REQUIRED: There should be an 'Installation' section that shows users how
  to download and load the package from Bioconductor. These instructions and any
installation instructions should be in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] REQUIRED: Add runnable examples to man pages that document exported
  objects. 8% of man pages use either dontrun{} or donttest{}. If these are
necessary we suggest using donttest{} instead of dontrun{} since donttest{}
requires valid R code.

## Unit tests

- [ ] SUGGESTION: We strongly encourage the use of unit tests.

## R code

- [ ] REQUIRED: Avoid `1:...`, use `seq_len()` or `seq_along()` instead.
- [ ] REQUIRED: Avoid `cat` and `print` outside of `show` methods.
- [ ] REQUIRED: Avoid using `=` for assignment and use `<-` instead.
- [ ] REQUIRED: Avoid use of `paste` in condition signals.
- [ ] REQUIRED: Remove use of `set.seed()`. Found 4 times.
- [ ] REQUIRED: Avoid `supressWarnings`/`*Message` if possible.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 102
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 676 lines that are not.


Best,
Kayla

**Comment by rossinerbe** [comment]
@Kayla-Morrell should be ready for re-review. With the caveat that I had to remove the suggested changes to NAMESPACE as these created an error in the build check above. Let me know if this is a problem

**Comment by rossinerbe** [comment]
@Kayla-Morrell do I need to do anything for the review process at this point?

**Comment by Kayla-Morrell** [comment]
@rossinerbe - Sorry for the delay in posting my re-review comments. There are two points that need to be addressed before I can accept the package, see below. Please respond with any comments.

## NAMESPACE

- [ ] REQUIRED: There needs to be some sort of importing in the NAMESPACE file. There is a warning in BiocCheck that needs to be addressed/cleared. Perhaps there was a moment of miscommunication between the builders with you pushed your changes because Rhdf5lib is most definitely available, see [here](https://bioconductor.org/packages/devel/bioc/html/Rhdf5lib.html). Try to implement these changes again and if you see the same ERROR we can attempt to troubleshoot together.

## Man pages

- [ ] REQUIRED: There is still the use of `dontrun{}` instead of `donttest{}`. Did you attempt to implement this?

Best,
Kayla

**Comment by rossinerbe** [comment]
Okay, I have made those changes. Changing from `dontrun` to `donttest` seems to lead to `WARNING: R CMD check exceeded 10 min requirement` (I'm not sure why) which is why I hadn't done it previously, but if it's required we can include it

**Comment by Kayla-Morrell** [comment]
@rossinerbe - Interesting, I'm not sure why that would cause an issue. If you want to switch that back to avoid the WARNING I'd allow it. Thank you for making the changes, I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rossinerbe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ATACCoGAPS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ATACCoGAPS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
