### ISSUE TITLE
EpiMix

### ISSUE THREAD

**Issue by YuanningEric** [Bioconductor/Contributions#2558]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gevaertlab/EpiMix.data

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Please do not use the name vignette.Rmd for your vignette.    Also, when attempting to check your package I get
```
* creating vignettes ... ERROR
--- re-building ‘vignette.Rmd’ using rmarkdown
Loading required package: EpiMix.data
Quitting from lines 297-317 (vignette.Rmd) 
Error: processing vignette 'vignette.Rmd' failed with diagnostics:
could not find function "EpiMix"
--- failed re-building ‘vignette.Rmd’

```
Please be sure to install your package and check it with R CMD check on a clean system so that another person attempting this will succeed.

**Comment by YuanningEric** [comment]
Hi Vince,

Thanks for the review !

I have renamed the vignette.md. I tried to build the package in a clean environment but could not reproduce the issue. It was very surprised to  see the error, because "EpiMix" is one of the main exported functions of this package. So, if the package has been installed, then the function should exist.

Could you please fetch the updated repository and build it again?

Thanks!

**Comment by YuanningEric** [comment]
@vjcitn Please also note that the  "EpiMix.data" package is the supporting data package of  "EpiMix".  They are stored in two different git repositories. I assume that the error occurred when you tried to build the main "EpiMix" package.

**Comment by vjcitn** [comment]
I need to understand this better.  
```
    else {
        cat("Searching lncRNA data for:", CancerSite, "\n")
        url = "https://github.com/gevaertlab/ncRNA_pancancer_new/raw/main/"
        destfile = paste0(TargetDirectory, "/", CancerSite, "_lncRNA.txt")
        downloader::download(paste0(url, CancerSite, "_lncRNA.txt"), 
            destfile)
        MAdirectories = destfile
    }
    return(MAdirectories = MAdirectories)
}
<bytecode: 0x11600ef30>
```
Is your package downloading data from github?  Instead you have to use ExperimentHub.

**Comment by vjcitn** [comment]
@lshep ^^

**Comment by lshep** [comment]
@vjcitn  / @YuanningEric   Bioconductor does not allow data to be stored on github.  It minimally must be on a public server at an Institution or something like Zenodo and implement a caching like system (like BiocFileCache) for managing downloads.  Bioconductor provides opportunity for hosting data through Bioconductor provided location.  We encourage data to be distributed through the ExperimentHub.  Please see   https://bioconductor.org/packages/devel/bioc/vignettes/HubPub/inst/doc/CreateAHubPackage.html

**Comment by YuanningEric** [comment]
@vjcitn  Hi, Vince!  I have started the procedures to upload these data to ExperimentHub. After this has been accomplished, I will modify the corresponding code and notify you about the change.  At the mean time, please let us know if there are any other problems we need to fix for our package. Thanks a lot!

**Comment by vjcitn** [comment]
Thanks for this.  I guess a basic question is why you had to write code to use firehose instead of reusing code in TCGAbiolinks.  Are the data of interest not provided in curatedTCGAData?

**Comment by vjcitn** [comment]
RTCGAToolbox also has similar functionality.  Had you looked at these?

**Comment by YuanningEric** [comment]
@vjcitn Thanks for your question, Vince!

I took a close look at both packages you mentioned. The `TCGAbiolinks` first downloads data from the GDC portal, which includes one patient data per file, then it combined all the patient files together for additional preprocessing. This takes significant higher amount of time and disk space than using the firehose, from which the  downloaded data has already been  a single zipped file including preprocessed data for all the patients. 

The RTCGAToolbox uses a very similar function than what we wrote. The reason we used our own code is that we built our current package by extending our previous Bioconductor package, called `MethylMix`. We did reuse a few bottom functionalities from MethylMix, because we know that those functions worked well. This also reduces the number of package dependency by avoiding to downloading another package.

Hope this helps, and please let me know if you have any other questions!

**Comment by YuanningEric** [comment]
The data package has been built. Here is our main package:

https://github.com/gevaertlab/EpiMix

**Comment by lshep** [comment]
Please see the proper way to submit the related package at https://github.com/Bioconductor/Contributions#circular-dependencies  you need to use an `AdditionalPackage:` indication

**Comment by YuanningEric** [comment]
AdditionalPackage: https://github.com/gevaertlab/EpiMix

**Comment by YuanningEric** [comment]
@lshep @Kayla-Morrell  
Hi Kayla!  I saw there is a deadline for the new package to be built on Bioconductor in order for catching up the release of V3.15. Could you please move our additional package to the repo? 
Both our data package and the main (additional) package have been scrutinized during the pre-check phase (see comments above), and we want them to be released with Bioc 3.15 instead of waiting for the next release period.  
We appreciate your time and effort!

**Comment by lshep** [comment]
Please be aware EpiMix currently has a mixture of biocViews.  Please only use one hierarchy.  I will manually force this in and designate EpiMix a software package.

**Comment by lshep** [comment]
@YuanningEric  There also seems to be a discrepancy in our credentials app -- I assume the correct spelling of your email  is `eric2021@stanford.edu`  -- currently in the BiocCredentails app it is `erci2021@stanford.edu`.  Would you like me to update the credentials app for you? I can't finish the processing without the name mismatch (and the biocViews) corrected.

**Comment by YuanningEric** [comment]
> @YuanningEric There also seems to be a discrepancy in our credentials app -- I assume the correct spelling of your email is `eric2021@stanford.edu` -- currently in the BiocCredentails app it is `erci2021@stanford.edu`. Would you like me to update the credentials app for you? I can't finish the processing without the name mismatch (and the biocViews) corrected.

@lshep Thanks for checking this! Yes, please use `eric2021@stanford.edu`

**Comment by YuanningEric** [comment]
@lshep Hi !  From the BiocCheck report, I saw an error: At least 80% of man pages documenting exported objects
      must have runnable examples"
What if some of my functions take a really long time to run or  need to save exported objects to the file system? For example, one of my functions is to download the gene expression data from the TCGA project. In this case, which folder should I save the download file?

**Comment by lshep** [comment]
Functions generally need to be run somewhere vignette or examples or tests. One of the reasons I think @vjcitn  also mentioned the TCGAbiolinks is it already utilizes Bioconductor standards like experimenthub and biicfilecache.  Anything downloaded from the internet should have a caching mechanism to download; that way the expensive download is done once and the a user can use the cached file in subsequent runs and only redownload if the file changes. I would see about implementing biocfilecache. 

Also we would consider skipping running that example but implement a long test that would run and test functionality. http://contributions.bioconductor.org/long-tests.html

**Comment by YuanningEric** [comment]
@lshep Thanks a lot for your advice! In a future release, we will consider to using TCGAbiolinks or RTCGAToolBox as mentioned by @vjcitn . Now, our package has passed the `R CMD check`. The only error and warning arising from the `BiocCheck` is that we need to test more chunks in vignette and/or examples. 

For those functions I tested in the vignette, do I need to test it again in the function examples? 

In addition, I plan to move those functions taking long time to run to the `long test` as you mentioned, but this may take me a few days. Whether this will affect the release of our package with Bioc 3.15?

**Comment by YuanningEric** [comment]
Hi @lshep @Kayla-Morrell, I have included the vast majority of functions as runnable examples in the Vignette. Since there is a time limit for `R CMD check`, the functions that have been run in the Vignette were not included as runnable examples in the man pages. Can you accept our package? 

Thanks!

**Comment by Kayla-Morrell** [comment]
@YuanningEric - We do not accept packages simply based off the build report, there is a formal review process that must take place. I will begin reviewing both packages and post back here with required/suggested changes that should be made to the package before being accepted. I will attempt to get the review posted within the next week.

Best,
Kayla

**Comment by YuanningEric** [comment]
@Kayla-Morrell  Thanks, Kayla! Please let me know if you have any questions

**Comment by Kayla-Morrell** [comment]
@YuanningEric - Thank you for submitting to _Bioconductor_. Please see the initial review of
the packages below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

# EpiMix.data

## DESCRIPTION

- [ ] REQUIRED: Since this is a data package we recommend not including
  'LazyData: TRUE'. It's our experience that it only slows down the loading of
the package. Either set to 'FALSE' or remove.
- [ ] REQUIRED: Update R version dependency from 4.1.0 to 4.2.0.
- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with
a relevant link to GitHub for reporting issues.

## NEWS

- [ ] REQUIRED: It is great that a NEWS file is included with the package.
  However, it seems that the file is not formated properly. Please see the
following link on how to format your file: https://contributions.bioconductor.org/news.html

## Unit tests

- [ ] SUGGESTION: We strongly encourage the use of unit tests.

## R code 

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 17
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 7 lines that are not.

# EpiMix

## DESCRIPTION

- [ ] REQUIRED: Either set 'LazyData' to false or remove it.
- [ ] REQUIRED: Update R version dependency from 4.1.0 to 4.2.0.
- [ ] SUGGESTION: Consider adding this automatically suggested biocView
	Preprocessing
- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with
  relevant links to GitHub for reporting issues.

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring and not
  include '.' which indicates S3 dispatch.

## NEWS

- [ ] REQUIRED: It is great to include a NEWS file but yours does not seem to be
  formatted properly. Please see the following link for correct format of NEWS
files: https://contributions.bioconductor.org/news.html.

## Vignette

- [ ] REQUIRED: The name of the vignette should be more descriptive. 
- [ ] REQUIRED: There should be no `eval = FALSE` sections of code besides the
  installation code chunk.
- [ ] SUGGESTION: We strongly encourage the use of BiocStyle for formatting of
  the vignette.
- [ ] REQUIRED: The last section of the vignette should be 'Session Information'
  and should include `sessionInfo()`.
- [ ] REQUIRED: Only the source vignette file and any necessary static images
  should be in the vignette directory (the style file is fine as well). Please
remove any unnecessary files, I could only find reference to the Workflow.png
file. All others should be removed if not needed.
- [ ] REQUIRED: Use accessors; don't access S4 slots via '@'.
- [ ] REQUIRED: There is a lot of repeated code in your vignette that could be
  simplified. You don't need call `library()` in each code chunk, once is
sufficient. The same goes for the `data()` calls.
- [ ] REQUIRED: When running through the vignette code, the code chunk starting
  at line 312 and line 331 does not run resulting in the following error. This 
is why it is crucial to have all code chunks evaluated so you know when code is 
not working properly.
```{r}
Error in wilcox.test.default(expr.high.values, expr.low.values, alternative = ifelse(correlation ==  :
  not enough 'y' observations
>
```
- [ ] REQUIRED: Line 481, Correlation is misspelled. If I run this line of code
  I get NULL. If I change to `plots$CorrelationPlot` then a plot is produced.
- [ ] REQUIRED: All saved files/results should be in a temp directory. When
  running through the code I ended up with two directories that results were
saved to, "Test" and "ReferenceEpigenomes".

## Man pages

- [ ] REQUIRED: At least 80% of man pages documenting exported objects must have
  runnable examples.
- [ ] REQUIRED: If examples must not be run we prefer using donttest{} over
  dontrun{} since donttest{} requires valid R code.
- [ ] REQUIRED: You mentioned examples being run in vignettes but the function
  TCGA_GetData is never actually run in the vignette, it's included in eval =
FALSE code chunks. Therefore, the function is never being run to know if it is
working properly. It must be run some where, whether that be in the vignette,
with runnable man page examples, or unit tests.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests, we strongly encourage them.

## R code

- [ ] SUGGESTION: Undefined global function/variable, 'query'.
- [ ] REQUIRED: Avoid sapply(); use vapply() instead.
- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along() instead.
- [ ] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods.
- [ ] REQUIRED: Avoid using '=' for assignment and use '<-' instead.
- [ ] REQUIRED: Avoid the use of 'paste' in condition signals.
- [ ] REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible, found 24
  times.
- [ ] REQUIRED: Function names should use camelCase, not use '.' within the name, 
and non-exported functions should have the prefix '.'.
- [ ] REQUIRED: Make sure web resources follow the guidelines [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/).
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 1565
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There are 5 lines that contain tabs.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 2931 lines that are not. 


Best,
Kayla

**Comment by YuanningEric** [comment]
@Kayla-Morrell 

Hi Kayla,

I have addressed all your comments with the two following notes:

1. The exported functions are either run in the Vignette or in the code example, but not both.  The vignette covers > 95% exported functions, while the others are included as runnable examples in the code. 

2.  We have tried to accommodate as many issues you mentioned in the `R Code` section. However, at the current stage, it is impossible for us to change every lines of the code with similar issues. I understand that some of the suggestions are considered as “best practice” or as a convention. However, having testing our package on multiple datasets, we have known that our package behaves properly. Changing multiple lines of codes at the current time in order to fit these conventions may actually cause unpredictable effect. I hope you can understand.

Could you please take a look at the revised package and see if you can accept it?

Thanks you in advance !
Yuanning

**Comment by Kayla-Morrell** [comment]
@YuanningEric - Could you please check the boxes of the items you have addressed from my review. This will make it easier for me when re-review.

Thanks,
Kayla

**Comment by YuanningEric** [comment]
@Kayla-Morrell - The boxes in front your comments are not clickable. Is there a way I can check them?

**Comment by YuanningEric** [comment]
@Kayla-Morrell  Hi Kayla, please do let me know how to check the boxes in front of you comments.

**Comment by Kayla-Morrell** [comment]
@YuanningEric - I believe you need to copy the text and paste in the comment box, then you'll be able to click the boxes on your own comment. If that doesn't work just indicate in text which points were addressed.

**Comment by YuanningEric** [comment]
> # EpiMix.data
> ## DESCRIPTION
> * [x]  REQUIRED: Since this is a data package we recommend not including
>   'LazyData: TRUE'. It's our experience that it only slows down the loading of
>   the package. Either set to 'FALSE' or remove.
> * [x]  REQUIRED: Update R version dependency from 4.1.0 to 4.2.0.
> * [x]  SUGGESTION: We strongly encourage including the 'BugReports:' field with
>   a relevant link to GitHub for reporting issues.
> 
> ## NEWS
> * [x]  REQUIRED: It is great that a NEWS file is included with the package.
>   However, it seems that the file is not formated properly. Please see the
>   following link on how to format your file: https://contributions.bioconductor.org/news.html
> 
> ## Unit tests
> * [ ]  SUGGESTION: We strongly encourage the use of unit tests.
> 
> ## R code
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 17
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 7 lines that are not.
> 
> # EpiMix
> ## DESCRIPTION
> * [x]  REQUIRED: Either set 'LazyData' to false or remove it.
> * [x]  REQUIRED: Update R version dependency from 4.1.0 to 4.2.0.
> * [x]  SUGGESTION: Consider adding this automatically suggested biocView
>   Preprocessing
> * [x]  SUGGESTION: It is encouraged to include the 'BugReports:' field with
>   relevant links to GitHub for reporting issues.
> 
> ## NAMESPACE
> * [x]  REQUIRED: Exported functions should use camel case or underscoring and not
>   include '.' which indicates S3 dispatch.
> 
> ## NEWS
> * [x]  REQUIRED: It is great to include a NEWS file but yours does not seem to be
>   formatted properly. Please see the following link for correct format of NEWS
>   files: https://contributions.bioconductor.org/news.html.
> 
> ## Vignette
> * [x]  REQUIRED: The name of the vignette should be more descriptive.
> * [x]  REQUIRED: There should be no `eval = FALSE` sections of code besides the
>   installation code chunk.
Comment: The `TCGA_GetData` function is now tested using the *longtests*, since it takes too long to run in the Vignette. 

> * [ ]  SUGGESTION: We strongly encourage the use of BiocStyle for formatting of
>   the vignette.
> * [x]  REQUIRED: The last section of the vignette should be 'Session Information'
>   and should include `sessionInfo()`.
> * [x]  REQUIRED: Only the source vignette file and any necessary static images
>   should be in the vignette directory (the style file is fine as well). Please
>   remove any unnecessary files, I could only find reference to the Workflow.png
>   file. All others should be removed if not needed.
> * [x]  REQUIRED: Use accessors; don't access S4 slots via '@'.
> * [x]  REQUIRED: There is a lot of repeated code in your vignette that could be
>   simplified. You don't need call `library()` in each code chunk, once is
>   sufficient. The same goes for the `data()` calls.
> * [x]  REQUIRED: When running through the vignette code, the code chunk starting
>   at line 312 and line 331 does not run resulting in the following error. This
>   is why it is crucial to have all code chunks evaluated so you know when code is
>   not working properly.
> 
> ```
> Error in wilcox.test.default(expr.high.values, expr.low.values, alternative = ifelse(correlation ==  :
>   not enough 'y' observations
> >
> ```
> 
> * [x]  REQUIRED: Line 481, Correlation is misspelled. If I run this line of code
>   I get NULL. If I change to `plots$CorrelationPlot` then a plot is produced.
> * [x]  REQUIRED: All saved files/results should be in a temp directory. When
>   running through the code I ended up with two directories that results were
>   saved to, "Test" and "ReferenceEpigenomes".
> 
> ## Man pages
> * [ ]  REQUIRED: At least 80% of man pages documenting exported objects must have
>   runnable examples.
> * [x]  REQUIRED: If examples must not be run we prefer using donttest{} over
>   dontrun{} since donttest{} requires valid R code.
> * [x]  REQUIRED: You mentioned examples being run in vignettes but the function
>   TCGA_GetData is never actually run in the vignette, it's included in eval =
>   FALSE code chunks. Therefore, the function is never being run to know if it is
>   working properly. It must be run some where, whether that be in the vignette,
>   with runnable man page examples, or unit tests.

Comment: The "TCGA_GetData" function is now tested using the *longtests*

> 
> ## Unit tests
> * [x]  SUGGESTION: Consider adding unit tests, we strongly encourage them.
> 
> ## R code
> * [x]  SUGGESTION: Undefined global function/variable, 'query'.
> * [x]  REQUIRED: Avoid sapply(); use vapply() instead.
> * [ ]  REQUIRED: Avoid 1:...; use seq_len() or seq_along() instead.
> * [ ]  REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods.
> * [x]  REQUIRED: Avoid using '=' for assignment and use '<-' instead.
> * [ ]  REQUIRED: Avoid the use of 'paste' in condition signals.
> * [x]  REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible, found 24
>   times.
> * [ ]  REQUIRED: Function names should use camelCase, not use '.' within the name,
>   and non-exported functions should have the prefix '.'.
> * [x]  REQUIRED: Make sure web resources follow the guidelines [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/).
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 1565
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
>   There are 5 lines that contain tabs.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 2931 lines that are not.
>

**Comment by YuanningEric** [comment]
@Kayla-Morrell  Hi Kayla. I have completed the revisions and checked the boxes. Please take a look and let us know if you can accept the package. Thanks!

**Comment by Kayla-Morrell** [comment]
@YuanningEric - Thank you for making the necessary changes. I've looked them over and have just one more points that need to be addressed.

## Man pages

- [ ] REQUIRED: We still need to address some of the exported functions and where they are being tested. Out of the 17 functions that are exported 12 of them have their examples in `donttest{}` code chunks. I was able to locate 8 of these functions being run in evaluated code chunks in the vignette. But that still leaves 4 functions that are not being run anywhere. Please clarify where in the package (vignette, man, or tests) that these functions are being run:

- `GEO_Download_DNAMethylation()`
- `TCGA_Download_DNAMethylation()`
- `TCGA_GetData()`
- `TCGA_Preprocess_DNAMethylation()`

You mention that `TCGA_GetData()` is being tested using long tests, but when I look in the test file I see `EpiMix()` being run and tested, not `TCGA_GetData()`.

Until we are certain that all exported function are being tested in some way I cannot accept the package.

Best,
Kayla

**Comment by YuanningEric** [comment]
> @YuanningEric - Thank you for making the necessary changes. I've looked them over and have just one more points that need to be addressed.
> 
> ## Man pages
> * [x]  REQUIRED: We still need to address some of the exported functions and where they are being tested. Out of the 17 functions that are exported 12 of them have their examples in `donttest{}` code chunks. I was able to locate 8 of these functions being run in evaluated code chunks in the vignette. But that still leaves 4 functions that are not being run anywhere. Please clarify where in the package (vignette, man, or tests) that these functions are being run:
> * `GEO_Download_DNAMethylation()`                      "longtests/test_GEO_download.R"
> * `TCGA_Download_DNAMethylation()`                    "vignette / chunk 20"
> * `TCGA_GetData()`                                                     "longtests / test_TCGA_GetData.R"
> * `TCGA_Preprocess_DNAMethylation()`                 "vignette / chunk 22"

@Kayla-Morrell 

Hi Kayla, 
Thanks for your review! The `TCGA_Download_DNAMethylation()` and `TCGA_Preprocess_DNAMethylation()`  functions were actually tested in the vignette, and I have explicitly labeled the chunk ids above.  I have now added the tests for the `GEO_Download_DNAMethylation()`  and `TCGA_GetData()`  functions in the longtests. The location for the test scripts are also labeled above. 

Please take a look. Thanks!

Yuanning

**Comment by Kayla-Morrell** [comment]
@YuanningEric - Thank you for making that more clear for me. I see now that these functions are tested. I am happy to accept the packages.

Best,
Kayla

**Comment by YuanningEric** [comment]
@Kayla-Morrell Hi Kayla, thanks for letting us know this great news! We appreciate your effort and suggestions in reviewing the package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YuanningEric.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EpiMix.data")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EpiMix.data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YuanningEric.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EpiMix")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EpiMix

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
