### ISSUE TITLE
cogeqc

### ISSUE THREAD

**Issue by almeidasilvaf** [Bioconductor/Contributions#2559]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/almeidasilvaf/cogeqc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Package looks good.  But you are doing something with Herper and miniconda.  We would like our python interoperations to proceed through the basilisk protocol.  Please see the vignettes for Aaron Lun's basilisk package  in Bioconductor.

**Comment by almeidasilvaf** [comment]
Hi, @vjcitn. I imported Herper just to make things easier for users who want to run BUSCO from an R session. An easier workaround would be to remove the native interoperation with Herper in `cogeqc` and let users do it by themselves if they want to, or install BUSCO manually. This way, the package itself wouldn't depend on any framework to interoperate with conda (neither Herper nor basilisk), and users could choose whether they want to use the external dependency with conda or not. What do you think?

Note: the package doesn't require BUSCO to pass checks. It was developed in a similar fashion to https://github.com/snystrom/memes.

**Comment by almeidasilvaf** [comment]
Hi, @vjcitn, I have just removed the native integration with Herper. I think the best thing to do is to let users decide how they want to handle the external dependency. I have also included BUSCO (>=5.1.3) in the SystemRequirements field of my DESCRIPTION and added a side note in one of the vignettes to let users know they can use Herper to handle the external dependency if want they want.

**Comment by almeidasilvaf** [comment]
Hi, BioC team.

It's been a month since the package built successfully. Has the package been reviewed?

**Comment by nturaga** [comment]
I’ll issue a review today.

Thanks.

Nitesh Turaga

**Comment by nturaga** [comment]
# Review

## DESCRIPTION 

ok, no depends on a Bioconductor package - Maybe include `BioStrings` to take in sequence files as input.

## NAMESPACE 

ok

## data

ok

## man

ok

## R

- Can you use the 'Biostrings' package as well to take in sequence data? This will add interoperability with other Bioconductor packages.

## vignette

ok

**Comment by nturaga** [comment]
Your package is very close to getting accepted. Good work!

**Comment by almeidasilvaf** [comment]
Thank you for your review, @nturaga!

Great suggestion. Users can now input a *StringSet object, so the package interoperates with Biostrings.

**Comment by nturaga** [comment]
Please fix these two notes. I'll accept your package. The second one, only if it's relevant to your package.

* NOTE: Update R version dependency from 4.1 to 4.2.0.
 
* NOTE: Consider adding these automatically suggested biocViews:
      NetworkInference, Network

**Comment by almeidasilvaf** [comment]
Done! 

I added Network to biocViews, but not NetworkInference (not relevant to the package).

Thank you very much for your helpful suggestions.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/almeidasilvaf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cogeqc")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cogeqc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
