### ISSUE TITLE
cytoMEM

### ISSUE THREAD

**Issue by cytolab** [Bioconductor/Contributions#2570]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cytolab/cytoMEM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by cytolab** [comment]
Hi @Kayla-Morrell,

Error addressed: 
- Maintainer subscribed to the bioc-devel mailing list (jonathan.irish@vanderbilt.edu)


Warning addressed:
- Updated class membership checks with is() and == / != to is(x, 'class') for S4 classes

**Comment by Kayla-Morrell** [comment]
@cytolab - 
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.15
release is 4/20. Any packages accepted after this date will be included in the
next release.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.1 to 4.2.0.
- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with 
relevant links to GitHub for reporting issues. 

## NEWS

- [ ] REQUIRED: Running `utils::news(package="cytoMEM")` within R results in
  `NULL`. This is because the file isn't formatted using markdown. When I
changed the file to contain markdown (headings using `#` and the list elements
with `*`), rebuilt and installed the package, then ran
`utils::news(package="cytoMEM")` then a proper news file was created. Please
change the format of this file. 

## CITATION

- [ ] REQUIRED: The CITATION file should not be a markdown file, but just as
  'inst/CITATION'. When I change the file type and run
`readCitationFile("inst/CITATION")` without the package being loaded with a
library call, there is an error that should be addressed.

## Vignette

- [ ] SUGGESTION: We encourage the use of `BiocStyle` for formatting.
- [ ] SUGGESTION: We strongly encourage a table of contents.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?cytoMEM`.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Avoid `cat` and `print` outside of `show` methods. Instead use
  `message`, `warning` or `stop`.
- [ ] REQUIRED: Avoid using `=` for assignment and use `<-` instead. 
- [ ] SUGGESTION: Undefined global function or variables:
        cluster
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 163
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 185 lines that are not.    

Best,
Kayla

**Comment by cytolab** [comment]
Hi @Kayla-Morrell,

Thank you so much for your review of cytoMEM. Here are the updates made to the package:

- Updated R version dependency to 4.2.0
- Updated NEWS file to be read by R
- Updated file type of CITATION file
- Included show methods in the build_heatmaps function
- Replaced = with <- for assignment in all R code files

Package is ready for re-review.

**Comment by cytolab** [comment]
Hi @Kayla-Morrell,

Thank you so much for your review of cytoMEM. Here are the updates made to the package:

- Updated R version dependency to 4.2.0
- Updated NEWS file to be read by R
- Updated file type of CITATION file
- Included show methods in the build_heatmaps function
- Replaced = with <- for assignment in all R code files

Package is ready for re-review.

**Comment by cytolab** [comment]
Great! Thank you so much @Kayla-Morrell for the quick review! Happy to contribute to Bioconductor.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cytolab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cytoMEM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cytoMEM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
