### ISSUE TITLE
standR

### ISSUE THREAD

**Issue by ningbioinfo** [Bioconductor/Contributions#2574]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DavisLaboratory/standR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
vignette has
```
url_base <- "http://nanostring-public-share.s3-website-us-west-2.amazonaws.com/GeoScriptHub/KidneyDataset/"
```

do not do this.  please create an ExperimentHub contribution.   @lshep

**Comment by ningbioinfo** [comment]
Hi @vjcitn ,
Thanks for the suggestion. 
I just had a read of the ExperimentHub vignette, do you mean I need to write the data as a ExperimentHub package while upload the data to the S3 bucket? Or I'll just wait for a pull request on github?

**Comment by vjcitn** [comment]
You can use ExperimentHub protocol to produce a reference from the hub to your S3 resource.  Then your vignette code would be modified to use ExperimentHub, which would implicitly cache reusable resources for the user.  Please read the doc on ExperimentHub or HubPub. If you have questions post to bioc-devel.

**Comment by lshep** [comment]
We recommend using the ExperimentHub for increased visibility of the data outside the package and because it has a caching mechanism built into the back end.   Minimal updates to your package for ExperimentHub would include creating the needed metadata.csv file,  adding the biocView ExperimentHubSoftware, requesting the data be added to the hub database, and than slightly altering your code to use ExperimentHub interface to download.  And as @vjcitn  mentioned please review https://bioconductor.org/packages/devel/bioc/vignettes/HubPub/inst/doc/CreateAHubPackage.html

**Comment by ningbioinfo** [comment]
Hi @lshep, many thanks for the advises. 
I've made an ExperimentHub package and I've emailed you for my credentials to allow me to upload the data to S3 bucket.

**Comment by lshep** [comment]
@ningbioinfo  I don't see a request for credentials. Could you please try  emailing hubs@bioconductor.org again and cc: lori.shepherd@roswellpark.org.  Thanks

**Comment by ningbioinfo** [comment]
Hi @lshep , sure I just sent another email for the request.

**Comment by ningbioinfo** [comment]
Hi @lshep , did you receive my email for the request? It was sent from liu.n@wehi.edu.au.

**Comment by ningbioinfo** [comment]
Hi @lshep , many thanks for your helps! I’ve added the metadata.csv to the standR package (https://github.com/DavisLaboratory/standR), and added ExperimentDataSoftware to the biocViews of the package.
Can you help me try add the resource?

**Comment by lshep** [comment]
My fault -- could you change the biocViews in the DESCRIPTION to `ExperimentHubSoftware`  instead of `ExperimentDataSoftware` .  Thank you. 

There was also an issue using the default data.frame option as DispathClass.  I updated to FilePath and would appreciate updating your metadata file to be the same.  The default data.frame assumed a different structure.  The FilePath will return the locally downloaded file path that you can put in the appropriate read/load functions.  See below example but you can alter as you deem necessary.


The data has been added and you can now use ExperimentHub interface for data download.  Below is an example: 
```
> eh = ExperimentHub()
snapshotDate(): 2022-03-29

> query(eh, "standR")
ExperimentHub with 3 records
# snapshotDate(): 2022-03-29
# $dataprovider: Nanostring
# $species: NA
# $rdataclass: data.frame
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH7364"]]' 

           title                   
  EH7364 | GeomxDKDdata_count      
  EH7365 | GeomxDKDdata_sampleAnno 
  EH7366 | GeomxDKDdata_featureAnno


## Double bracket Downloads file
> file = eh[["EH7366"]]
see ?standR and browseVignettes('standR') for documentation
downloading 1 resources
retrieving 1 resource
  |======================================================================| 100%

loading from cache

> file
                                                   EH7366 
"/home/shepherd/.cache/R/ExperimentHub/41335ed0c3ef_7416" 
> tbl = read.table(file, header=TRUE)
> head(tbl)
      RTS_ID TargetName ProbeID Negative
1 RTS0020877        A2M   35614    FALSE
2 RTS0020878       NAT2   35615    FALSE
3 RTS0020879      ACADM   35616    FALSE
4 RTS0020880      ACADS   35617    FALSE
5 RTS0020881      ACAT1   35618    FALSE
6 RTS0020882     ACVRL1   35619    FALSE
```

**Comment by ningbioinfo** [comment]
Hi @vjcitn and @lshep , the URL in the vignette is now replaced by using ExperimentHub to request the data.

**Comment by ningbioinfo** [comment]
Hi Vince @vjcitn , do I need to make any more action for the package? Or I'll just need to wait for it to be proceed to be reviewed? 😀

**Comment by LiNk-NY** [comment]
Hi Ning @ningbioinfo 
Thank you for your submission. Please see the review below.

Best regards,
Marcel

---

# standR #2574

## DESCRIPTION

* Looks good.

## NAMESPACE

* Looks good.

## vignettes

* Please keep the text within the 80 character width limit. It's easier to
read and maintain.
* There is probably no reason to keep the link of the resource shown in the
vignette since the main avenue for users is to obtain the data via
`ExperimentHub`
* Consider using the native pipe operator to avoid additional dependencies
(`|>`)

## R

* Use selective importing via `@importFrom SummarizedExperiment function` or
namespace import with `@import SummarizedExperiment` to avoid repeated double
colon imports in `addQCstat.R`.
* Update examples to use `ExperimentHub` in `R/geomx_import_data.R`.
* Use S3 class membership checks, e.g., `is.data.frame` vs
`is(x, "data.frame")`
* Fix typos in error messages (`geomxNorm` in `R/normalisation.R`)
* Provide the options on a new line with proper spacing in `geomxNorm`
* Use the proper class name `SpatialExperiment` in the `@return` of `geomxNorm`
* Avoid using abbreviated arguments as they're harder to remember and
recognize e.g., `rl` in `plotPCA`
* Your `plotPCA` method conflicts with the implementation in `scater` for
`SingleCellExperiment`. How is yours different and is it necessary?
https://code.bioconductor.org/search/search?q=setMethod%5C%28%5C%22plotPCA%5C%22
Consider using a different name.
* `metadata` and `colData` are different concepts in Bioconductor. Consider
renaming `plotMetadata`.
* The downside of using non-descriptive names is that they can be confused
with others e.g., `RLE` is also run-length encoding. Consider renaming
`plotRLE`.
* Address the warnings in the examples for `computeClusterEvalStats`.
* Use the names of assays instead of the indices as arguments. It is more
descriptive and less likely to cause mistakes (e.g., 2 vs "logcounts" in
`computeClusterEvalStats`), especially when the workflow provides a consistent
name to use.
* Add `mclustcomp` to the `Imports` field if you are using them in
`computeClusterEvalStats` rather than in the `Suggests`.
* Minor: `if (hasNegProbe == TRUE)` is equivalent to `if (hasNegProbe)`

## tests

* Coverage looks good:
```r
standR Coverage: 79.30%
R/plotMetadata.R: 10.00%
R/geomx_import_data.R: 34.44%
R/utils.R: 73.33%
R/plotDR.R: 76.67%
R/plotRLE.R: 79.31%
R/batchCorrection.R: 85.98%
R/plotLibQC.R: 87.76%
R/pcaOtherPlotting.R: 89.80%
R/sumBatchCorEval.R: 95.00%
R/addQCstat.R: 95.45%
R/normalisation.R: 97.96%
R/plotGeneQCs.R: 100.00%
```

## NEWS.md

* Theres a typo in the file.

**Comment by ningbioinfo** [comment]
Hi Marcel @LiNk-NY ,

Thanks for your review.

Here are changes according to your comments:

### Vignette

1. Vignette is changed to keep the text within the 80 character width limit.
2. URL of the data was removed
3. native pipe is now used and magrittr library is now removed from the vignette.


### R
All of the mentioned comments are addressed accordingly. Some specific ones are mentioned below:
1. All the "%>%" are now becoming native pipe "|>" and magrittr has been removed from the import list.
2. plotPCA is now re-named as drawPCA to avoid conflicts. Comparing to the scater::plotPCA, the drawPCA in the standR package is accepting pre-precomuted PCA as a dataframe or the function will computed the PCA for the user using either scater::compuatePCA (if scater is installed) or stats::prcomp. And it's compatible with multiple datatypes, including DGEList, ExpressionSet, SummarizedExperiment, SingleCellExperiment and SpatialExperiment, all of which are common data types in transcriptomic data analysis.
3. plotRLE is now re-named as plotRLExpr to avoid mis-understanding.
4. mclustcomp is now added to the import field.

### NEWS.md
Typo is fixed.


Again, thanks for the review, please let me if there are anymore things I need to address.

Best regards,
Ning

**Comment by LiNk-NY** [comment]
Hi Ning, @ningbioinfo 

Thanks for making those changes. 
Your package has been accepted. 

Make sure to run `BiocCheck` and resolve any issues there
as you continue to improve your package. 

Best regards,
Marcel

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ningbioinfo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("standR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/standR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
