### ISSUE TITLE
fastreeR

### ISSUE THREAD

**Issue by gkanogiannis** [Bioconductor/Contributions#2575]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gkanogiannis/fastreeR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  We have to ask for some changes prior to review:
```
temp_vcf_url <-
    paste0("https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/",
        "1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/",
        "supporting/related_samples/",
        "ALL.chrX.shapeit2_integrated_snvindels_v2a_related_samples_27022019.",
        "GRCh38.phased.vcf.gz")
temp_vcf <- tempfile(fileext = ".vcf.gz")
on.exit(unlink(temp_vcf))
options(timeout=30)
tout <- utils::download.file(url=temp_vcf_url, destfile=temp_vcf, method="auto")

if(tout!=0) {
    #Couldn't download vcf. Use small sample vcf from package
    temp_vcf <- system.file("extdata", "samples.vcf.gz", package="fastreeR")
}
```
You should use BiocFileCache for this retrieval process so that it is not repeated needlessly for our build system or for users.  Please see the BiocFileCache vignette and pose any questions about its use to the bioc-devel mailing list.

For the following:
```
3.3Download sample fasta files
We download, in temporary location, 5 small bacterial genomes and we merge them into a single fasta file. If for any reason we cannot download, we use the small sample fasta from the package.

temp_fastas_urls <- c(
    paste0("https://ftp.ncbi.nih.gov/genomes/archive/old_refseq/Bacteria/",
            "Mycobacterium_liflandii_128FXT_uid59005/NC_011355.fna"),
    paste0("https://ftp.ncbi.nih.gov/genomes/archive/old_refseq/Bacteria/",
            "Pelobacter_propionicus_DSM_2379_uid58255/NC_008607.fna"),
    paste0("https://ftp.ncbi.nih.gov/genomes/archive/old_refseq/Bacteria/",
            "Rickettsia_prowazekii_Chernikova_uid158053/NC_017049.fna"),
    paste0("https://ftp.ncbi.nih.gov/genomes/archive/old_refseq/Bacteria/",
            "Salmonella_enterica_serovar_Newport_SL254_uid58831/NC_009140.fna"),
    paste0("https://ftp.ncbi.nih.gov/genomes/archive/old_refseq/Bacteria/",
            "Staphylococcus_aureus_JH1_uid58457/NC_009619.fna")
)
```
it is of some concern that `old_refseq` are being used.  Should these be in AnnotationHub?  The download outputs should be cached or made part of the permanent ecosystem.

**Comment by gkanogiannis** [comment]
Dear @vjcitn thanks for the recommendations. 
I updated vignette to use `BiocFileCache` for caching downloaded sample vcf and fasta files.
I updated vignette to use latest refseq links for downloading some example bacteria genomes.
Version bump to 0.99.1 (on github repository).

**Comment by gkanogiannis** [comment]
Dear @lazappi, my package requires Java (>=8).
Build on merida1 fails with message "No Java runtime present, requesting install."
Apparently merida1 does not have a JDK (=>8) installed.
Do I need to do something, like some extra setting in my package's DESCRIPTION?

**Comment by gkanogiannis** [comment]
Just to add that my package's DESCRIPTION had already the line "SystemRequirements: Java (>= 8)" and indeed nebbiolo1 (ubuntu) and riesling1 (windows) did not have a problem with providing the Java requirement.

**Comment by lshep** [comment]
@jwokaty do you know what version merida1 has ?

**Comment by jwokaty** [comment]
```
merida1:~ biocbuild$ java --version
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

**Comment by gkanogiannis** [comment]
Hm, that is weird. JDK is there.
Message " No Java Runtime present,requesting to install " is coming from package rJava.

**Comment by gkanogiannis** [comment]
According to answers to [this](https://stackoverflow.com/q/44009058), `JAVA_HOME` environment variable needs to be correctly set up.

**Comment by lshep** [comment]
I believe there was a similar conversation recently on the mailing list that JAVA_HOME shouldn't be relied upon but I could be mistaken.  And there are several Bioconductor packages that rely on java on merida1 that are not failing.

**Comment by gkanogiannis** [comment]
@lshep you must be right. Something else must be going wrong.
The error message "No Java runtime present, requesting install." is coming while building my package's vignette and in a point that already many operations that use `rJava` have been processed correctly.
For example in
```
* creating vignettes ... ERROR
--- re-building fastreeR_vignette.Rmd using rmarkdown
Loading required package: dbplyr
VCF2ISTATS : Fri Mar 25 09:47:59 EDT 2022
Num of Ind = 150
2022/03/25 09:49:12 Variants Processed : 	50000
2022/03/25 09:49:37 Variants Processed : 	100000
VCF2DIST : Fri Mar 25 09:47:59 EDT 2022
cpus=24
using=2
2022/03/25 09:49:44 VCFManager: START READ
33554432
2022/03/25 09:49:49 VariantProcessor: 0	50000
2022/03/25 09:49:50 VCFManager: END READ
2022/03/25 09:49:51 VariantProcessor: 0	100000

Processed variants : 	  106963
2022/03/25 09:49:54 CalculateDistancesChildTask(45): 	50
2022/03/25 09:49:58 CalculateDistancesChildTask(79): 	100
2022/03/25 09:50:00 CalculateDistancesChildTask(107): 	150
DIST2Hist : Fri Mar 25 09:47:59 EDT 2022
150 0
No Java runtime present, requesting install.
```
both `VCF2ISTATS` and `VCF2DIST` operations run correctly (and they rely on Java and `rJava`).

**Comment by lshep** [comment]
I found the mailing list post granted it was referencing windows instead of mac but not sure if its helpful https://stat.ethz.ch/pipermail/bioc-devel/2021-October/018594.html

**Comment by gkanogiannis** [comment]
@lshep thanks for the link, but as you mentioned, this must not be the reason.
I am doing some tests with the actual openjdk version of merida1 (14.0.1) and I will let you know.

**Comment by gkanogiannis** [comment]
Dear @lazappi, my package builds and checks ok on all systems. Eliminated previous error (apparently some incompatibility of a java grahics library I was using). Looking forward for your review.

**Comment by lazappi** [comment]
Hi @gkanogiannis

Thanks for submitting **fastreeR** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :green_circle: I had a problem with running `R CMD build` locally where the vignette did not finish building. As long as the build system passes that is ok but it may be an issue for users.

## Package data

- [ ] :rotating_light: Please document the data in `inst/extdata/` with a file in `inst/script`

## Documentation

- [ ] :green_circle: I noticed typos in a few places. You might what to check for these using the **spellcheck** package or `usethis::use_spellcheck()`

### Vignette

- [ ] :rotating_light: Please add a table of contents
- [ ] :warning: It would be good to explain in more detail what the `options(java.parameters="-Xmx1G")` code does for people who aren't familiar with Java
- [ ] :green_circle: I wasn't able to run the code in the vignette because I kept getting a `java.lang.ClassNotFoundException`. Again, this is ok if it works on the build system but maybe a potential issue for users.

### Man pages

- [ ] :warning: Most of the time there is no need for an explicit `@usage` tag as this will be automtically generated from the function description

## Unit tests

- [ ] :rotating_light: Please add more unit tests to cover more functionality in the package
- [ ] :rotating_light: The **testthat** package is listed as a dependency but doesn't seem to be used, please remove it if not needed

## Code

### R

- [ ] :warning: No existing Bioconductor classes are used by the package. Please see if there is anything you can use to increase compatibility with other packages.
- [ ] :green_circle: You may want to add more validity checks for function arguments
- [ ] :warning: I noticed some inconsistency in function argument naming (some `camelCase` and some `dot.case`), please be as consistent as possible

### Java

I am not very familiar with Java and `rJava` so I will ask if another reviewer is able to help with reviewing this part of the package

**Comment by gkanogiannis** [comment]
Hi @lazappi ,

Thank you for your time with reviewing my package **fastreeR**.

Please find bellow my reply with corrections, updates and comments to your points.
My package's version `0.99.7` has been already pushed to git.bioconductor.org and it builds and checks without errors and warnings to all 3 OSs.

I am looking forward to your updates and comments.

Anestis


## General package development

- [x] Updated Java back-end to address issues that could cause hanging while executing `R CMD build` and building vignettes.

## Package data

- [x] Documented sample data in `inst/extdata` with `inst/script/fastreeR_sample_data.md`.

## Documentation

- [x] Corrected various typos throughout package documentation.
- [x] Added `inst/WORDLIST` with local terms, abbreviations and acronyms.
- [x] Run `devtools::spell_check()` with no spelling errors.

### Vignette

- [x] Added `toc: true` on vignette's header.
- [x] Added paragraph in *vignette* and *README*, explaining the use of `options(java.parameters="-Xmx1G")`.
- [x] It is possible to get `java.lang.ClassNotFoundException` when running vignette or other package code, while the package is not yet properly installed. This is happening because the required .jar files, have not yet moved from `inst/java` to `java` location. This can be bypassed, by manually copying .jar files from `inst/java` to `java`.

### Man pages

- [x] Explicit `@usage` tags have been previously used, to avoid notes from `BiocCheck::BiocCheck()`. `Roxygen2` automatic usage generation, pads lines with 2 spaces (instead with the required multiple of 4 for `BiocCheck`). Nevertheless, as per your recommendation, explicit `@usage` tags have now been removed.

## Unit tests

- [x] Added more unit tests in `test/testthat` to cover more functionality for all functions in the package.
- [x] Updated *DESCRIPTION* by adding packages used for testing (*testthat*) and removing unused ones.

## Code

### R

- [x] This package's functions, operate on raw vcf or fasta files and the majority of operations are handled by a Java back-end implementation. I could not think of an existing Bioconductor library that could be extended. At one point of the calculation, there is the need of plotting trees, in Newick text format, and we use `ape::read.tree()` to convert the string into a dendrogram for plotting. Bioconductor's package `treeio` could also be used at this point, but it can only read the Newick tree from a file and not from a character vector and hence it would be an overkill to write the string to a temp file in order to re-read it with `treeio`. If you could propose me of possible Bioconductor's packages that could be useful for this package, we would be happy to make use of them.
- [x] Added more validity checks for function arguments.
- [x] Renamed all function arguments to follow a common and consistent naming format (`camelCase`).

### Java

Please let me know for any help I can provide with the Java code.

**Comment by lazappi** [comment]
> * [x]  It is possible to get `java.lang.ClassNotFoundException` when running vignette or other package code, while the package is not yet properly installed. This is happening because the required .jar files, have not yet moved from `inst/java` to `java` location. This can be bypassed, by manually copying .jar files from `inst/java` to `java`.

Yes, I was able to get the vignette to run if I installed the package properly rather than using `devtools::load_all()`. I still had an issue with `R CMD build` hanging but it works on the build system so maybe that is an issue with my setup.

> * [x]  Updated _DESCRIPTION_ by adding packages used for testing (_testthat_) and removing unused ones.

> * [x]  This package's functions, operate on raw vcf or fasta files and the majority of operations are handled by a Java back-end implementation. I could not think of an existing Bioconductor library that could be extended. At one point of the calculation, there is the need of plotting trees, in Newick text format, and we use `ape::read.tree()` to convert the string into a dendrogram for plotting. Bioconductor's package `treeio` could also be used at this point, but it can only read the Newick tree from a file and not from a character vector and hence it would be an overkill to write the string to a temp file in order to re-read it with `treeio`. If you could propose me of possible Bioconductor's packages that could be useful for this package, we would be happy to make use of them.

Yes, I think this is difficult with this package as you are mostly passing paths to Java and getting results back. There are possibly Bioconductor packages that could be used for some of the plotting but I don't think that's a big deal.
 
> ### Java
> Please let me know for any help I can provide with the Java code.

As long as you are following the guidelines for Java in ["Writing R extensions"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Non_002dR-scripts-in-packages) this should be ok. I think you are doing that already but it would be worth doing a quick search through this to check.

**Comment by gkanogiannis** [comment]
Hi @lazappi ,

Thank you for the follow-up. Please find my comments bellow.

> > * [x]   It is possible to get `java.lang.ClassNotFoundException` when running vignette or other package code, while the package is not yet properly installed. This is happening because the required .jar files, have not yet moved from `inst/java` to `java` location. This can be bypassed, by manually copying .jar files from `inst/java` to `java`.
> 
> Yes, I was able to get the vignette to run if I installed the package properly rather than using `devtools::load_all()`. I still had an issue with `R CMD build` hanging but it works on the build system so maybe that is an issue with my setup.
> 

Could you tell me the JDK version number of your system? Are there any messages printed before the hang occur?

> > * [x]   Updated _DESCRIPTION_ by adding packages used for testing (_testthat_) and removing unused ones.
> 
> > * [x]   This package's functions, operate on raw vcf or fasta files and the majority of operations are handled by a Java back-end implementation. I could not think of an existing Bioconductor library that could be extended. At one point of the calculation, there is the need of plotting trees, in Newick text format, and we use `ape::read.tree()` to convert the string into a dendrogram for plotting. Bioconductor's package `treeio` could also be used at this point, but it can only read the Newick tree from a file and not from a character vector and hence it would be an overkill to write the string to a temp file in order to re-read it with `treeio`. If you could propose me of possible Bioconductor's packages that could be useful for this package, we would be happy to make use of them.
> 
> Yes, I think this is difficult with this package as you are mostly passing paths to Java and getting results back. There are possibly Bioconductor packages that could be used for some of the plotting but I don't think that's a big deal.

It is my intention to update, in a future version, **fastreeR** with more functionality and possibly use of more Bioconductor packages. This first version of  **fastreeR** is intented to make use in R of the functionality already implemented in Java.

> 
> > ### Java
> > Please let me know for any help I can provide with the Java code.
> 
> As long as you are following the guidelines for Java in ["Writing R extensions"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Non_002dR-scripts-in-packages) this should be ok. I think you are doing that already but it would be worth doing a quick search through this to check.

Yes, I think that I am following the quidelines for Java code. My Java code is byte-compiled and packaged into .jar file located in `inst/java`. Because my java code is open source, the actual .java files are located in `java` (the source files should not be installed). A couple more .jar files for dependency tools (jcommander is a command line arguments parser tool and trove4j is an object and primitive collections library) are located also in `inst/java`.

Anestis

**Comment by lazappi** [comment]
This is what I get from `java -version`:

```
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
```

When I killed the `R CMD build` process there was some output from the vignette but I can't remember exactly where it got up to. Once this is accepted the building should be done on the Bioconductor side and users shouldn't have to worry about this (except on Linux maybe). As long as the build system passes it should be fine.

**Comment by gkanogiannis** [comment]
Hi @lazappi. Your JDK seems fine. Do I need to do something else from my part at this point, or I should wait for the review to finish?

**Comment by lazappi** [comment]
No I think you are good and I can mark this as approved 🎉! It can take a few days to be picked up by the build system but then your package should be added to Bioconductor devel.

**Comment by gkanogiannis** [comment]
This is excellent! Thank you again @lazappi for your time and the effort to review my package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gkanogiannis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("fastreeR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/fastreeR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
