### ISSUE TITLE
ompBAM

### ISSUE THREAD

**Issue by alexchwong** [Bioconductor/Contributions#2584]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/alexchwong/ompBAM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Is this right?  Vignette run on m1 mac.  So many zeroes?
```
idxstats(ompBAM::example_BAM("scRNAseq"), 2)
#> /private/var/folders/n4/p9th81md60s8nv12yv40sv8m0000gp/T/RtmpdV863Y/Rinstc8a31475592c/ompBAM/extdata/MGE_E35_1.bam summary:
#> Name Length  Number of reads
#> 1    195471971   50000
#> 10   130694993   0
#> 11   122082543   0
#> 12   120129022   0
#> 13   120421639   0
#> 14   124902244   0
#> 15   104043685   0
#> 16   98207768    0
#> 17   94987271    0
#> 18   90702639    0
#> 19   61431566    0
#> 2    182113224   0
#> 3    160039680   0
#> 4    156508116   0
#> 5    151834684   0
#> 6    149736546   0
#> 7    145441459   0
#> 8    129401213   0
#> 9    124595110   0
#> MT   16299   0
#> X    171031299   0
#> Y    91744698    0
```

**Comment by alexchwong** [comment]
@vjcitn  Yes it is correct. This example file is the first 50k alignments of a coordinate-sorted bam, so it is expected all the alignments belong to chromosome 1. It is a small bam file so that it can be included as 'extdata' within the package.

**Comment by alexchwong** [comment]
@vjcitn  I notice the R cmd build trigger warning in Windows and BiocCheck triggered a warning message regarding the vignette. Please consider two points:

(1) The R cmd build warning is due to "Warning: file 'ompBAM/inst/examples/ompBAMExample/configure' did not have execute permissions: corrected". This type of warning is windows specific and has been ignored for submission of other packages to Bioconductor in the past, and I ask you consider ignoring this here.

(2) The BiocCheck warning is triggered by: "WARNING: Evaluate more vignette chunks". In ompBAM, the vignette is used to extensively document functions for the C++ API library, and uses Rcpp code blocks for this purpose. These code blocks are not supposed to be runnable. The code works as demonstrated by the compilation of the example package in the first section. Please consider ignoring this warning specifically for this package.

Thanks in advance!

**Comment by hpages** [comment]
Thanks @alexchwong for submitting **ompBAM**.

The code in the vignette does not work for me:
```
library(MyPkg)
idxstats(ompBAM::example_BAM("Unsorted"), 2)
# Error in idxstats(ompBAM::example_BAM("Unsorted"), 2) : 
#   could not find function "idxstats"
```
It seems that `idxstats()` is indeed defined in **MyPkg** but is not exported. But even using `:::` doesn't work:
```
> ompBAMtestPkg:::idxstats
function (bam_file, n_threads) 
{
    idxstats_pbam(bam_file, n_threads)
}
<bytecode: 0x562788193400>
<environment: namespace:ompBAMtestPkg>

> ompBAMtestPkg:::idxstats(ompBAM::example_BAM("Unsorted"), 2)
Error in idxstats_pbam(bam_file, n_threads) : 
  could not find function "idxstats_pbam"
``` 
The underlying problem is that many code chunks are not evaluated so are never checked by `R CMD build` or `R CMD check`. Unfortunately, this is known to cause code rot in the long run, and sometimes even from the very start like here.

I'm actually skeptical about the usefulness of this package. It seems that you've figured out how to write and compile openMP-enabled C++ code to work with BAM files, which is great. But instead of actually providing a package that puts what you've learned in practice, you're providing a package that helps other potential developers to do that. Nothing inherently wrong about this but I find it strange that your submission is not accompanied by a package that builds on top of **ompBAM** and provides functionalities that Bioconductor _end users_ can _immediately_ use. That is, without having to go thru the hassle of writing their own openMP-enabled C++14 code, which sounds quite challenging, even for advanced users or developers! 

Also I wonder where **ompBAM** stands with respect to HTSlib. Is **ompBAM** exposing a C++ API for accessing BAM files? Is this API documented somewhere? How rich/complete is this API compared to HTSlib? **ompBAM** doesn't seem to rely on HTSlib at all for reading/parsing BAM files. Maybe you've discarded HTSlib because it doesn't support openMP and its maintainers have no plans to support it? Have you discussed this with them? Having HTSlib support openMP would be a much more satisfying solution than your proposal. 

Thanks,
H.

**Comment by alexchwong** [comment]
Hi @hpages , thanks for reviewing my package.

> The code in the vignette does not work for me: idxstats(ompBAM::example_BAM("Unsorted"), 2)

To make this line work, you need to have followed the steps detailed in the vignette section **Making and compiling an example ompBAM-based package**, paraphrased here as follows:
(1) Create the MyPkg package using use_ompBAM() (code block line 67-69).
(2) Open the newly created MyPkg.Rproj in RStudio as a project
(3) Roxygenise the package using devtools::document() (code block line 77)
(4) Run **Install and Restart** from the **Build** tab

I suspect you omitted step 3, which exports the `idxstats()` function from its roxygen tag. Please follow the above steps and try again? I reproduced it this morning on my end, and some time ago my colleague reproduced it on his end, so it definitely should work for you.

Actually, `MyPkg::idxstats()` is also run by the vignette (code block lines 105 and109) after creating / compiling MyPkg using an automated equivalent method, using the code block in lines 96-101:

```
library(ompBAM)
pkg_path = file.path(tempdir(), "MyPkg")
use_ompBAM(pkg_path)
devtools::document(pkg_path)
devtools::load_all(pkg_path)
library(MyPkg)
```

> I'm actually skeptical about the usefulness of this package ... I find it strange that your submission is not accompanied by a package that builds on top of ompBAM and provides functionalities that Bioconductor end users can immediately use

You are one step ahead of me. Actually, my previously submitted package NxtIRFcore, which was reviewed and accepted last year by yourself (https://bioconductor.org/packages/release/bioc/html/NxtIRFcore.html) is built on top of the ompBAM library. In that case, the ompBAM source code was included within NxtIRFcore, since ompBAM wasn't available. Once ompBAM is accepted, I intend to update NxtIRFcore without the ompBAM source code, and instead to link to (and therefore compile using) ompBAM library. On my end and using GitHub actions, I know this will work without R cmd check errors. 

NxtIRFcore is a complex program that demonstrate how powerful ompBAM can be, but is not easy for developers to peruse its source code to learn from and build their own packages from scratch. Therefore I provide ompBAM as a separate package. The vignette itself (sections (3) and (4)) is a detailed API documentation of all the functions provided by the two ompBAM objects `pbam_in` and `pbam1_t`.

> Also I wonder where ompBAM stands with respect to HTSlib. ... Maybe you've discarded HTSlib because it doesn't support openMP and its maintainers have no plans to support it? Have you discussed this with them? 

Indeed, ompBAM does not use HTSlib, and is therefore a direct competitor. It does not have the range of functionality that HTSlib offers, which is beyond the intended scope of ompBAM, which is (for now) **only** to read (sequentially) BAM files. However, it does so using OpenMP parallelization, and it has a well documented API (in the vignette), with a detailed step by step guide on how to use it (section (2) of the vignette). I had great difficulty finding HTSlib documentation (as had others - see https://www.biostars.org/p/216322/), and could not find a guide on how to start using HTSlib; my experience was an inspiration to create my own API.

Actually, another inspiration to produce ompBAM came from a bioc-devel post of someone who had exactly the same problem but he didn't know where to start: https://www.mail-archive.com/bioc-devel@r-project.org/msg14255.html . I would say, if he asked the same question today, we could point him to use ompBAM. I believe the fully-worked example in the vignette (chapters 1 and 2), plus some knowledge on C++ and how to create OpenMP loops (which are taught step by step in chapter 2 anyway), would really smoothen the difficulty curve of anyone wishing to create their own OpenMP-supported R package to process BAM files.

Please reconsider ompBAM for Bioconductor. In particular, please look at my vignette in detail (especially the worked example and the API). I am open to any suggestion you may have to improve the vignette to improve its clarity and make it more user friendly. I believe ompBAM will be a very useful resource for Bioconductor. In fact, I am preparing a manuscript describing ompBAM and NxtIRF (it is almost ready for submission), which will also greatly enhance their usage.

**Comment by hpages** [comment]
Hi @alexchwong,

Thanks for providing the backstory of why you decided to come up with **ompBAM**. It helps me understand where the package would fit in the Bioconductor ecosystem. I know it can be a challenge to use HTSlib. When I was migrating **Rsamtools** to **Rhtslib** a couple of years ago, I spent a lot of time trying to figure out how to extract records from a VCF or BCF file for a particular region. I wrote [this document](https://github.com/Bioconductor/Rsamtools/wiki/How-to-extract-records-within-a-user-specified-region-from-a-VCF-or-BCF-file-with-htslib-1.7) when I finally succeeded.

Yes I omitted step 3 (_Roxygenise the package using devtools::document()_) when I was following the vignette. When I go thru a vignette, I don't always take the time to read all the text. I pay more attention to the code chunks and I expect them to work.  Unfortunately you've not turned this step into a programmatic step. Why rely on the RStudio environment for this step? Some users (like me) don't use RStudio. It would be better to show how to Roxygenise programmatically. It would be even better to put the code in an evaluated chunk. I actually see no reason why the entire workflow could not be achieved with code chunks that get evaluated. You can still mention how to do this from the RStudio environment as an FYI, but the basic workflow should not rely on RStudio.

I'll take a closer look at the package now.

Thanks,
H.

**Comment by hpages** [comment]
Hi @alexchwong,

Can you please take care of the above, that is, use evaluated code chunks in the vignette that don't rely on the RStudio environment? Thanks.

H.

**Comment by alexchwong** [comment]
Thanks for your feedback @hpages ! I have amended the vignette as per your suggestion. Please let me know if you have any further suggestions.

Alex

**Comment by alexchwong** [comment]
@hpages, again the warning flags is from BiocCheck regarding the unevaluated code blocks in the vignette; otherwise the package passes without other warnings. In the vignette, only section 0 (installation and quick-start) is intended to have example code for the R console. In the remainder of the vignette, the code blocks are used to discuss, step-by-step, segments of the worked examples, as well as of each function of the two objects in the ompBAM library. I used the vignette for this purpose because it is (hopefully) more accessible to end users and the function documentation can follow a logical (instead of alphabetical) order. Please let me know whether this is ok.

**Comment by hpages** [comment]
Thanks for the changes to the vignette. The _Installation and Quick-Start_ section now works like a charm for me, from an old-fashion Unix terminal :wink: 

I think the package is good to go as is, even though I'm sure it will evolve and improve in the future, as you migrate **NxtIRFcore** to use **ompBAM** internally, and as the package gets adopted by other packages as an alternative to **Rhtslib**.

Best,
H.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alexchwong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ompBAM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ompBAM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
