### ISSUE TITLE
VectraPolarisData

### ISSUE THREAD

**Issue by julia-wrobel** [Bioconductor/Contributions#2594]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/julia-wrobel/VectraPolarisData

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by julia-wrobel** [comment]
I fixed the error (it came about because I was not subscribed to the bioc-devel email list). What are next steps?

**Comment by gkanogiannis** [comment]
@julia-wrobel you should bump the version number (i.e. ftom 0.99.0 to 0.99.1) in your DESCRIPTION file, before pushing to git.bioconductor.org, in order to inform the automatic system to rebuild your package.

**Comment by lshep** [comment]
Hi there.  A few minor comments before acceptance: 

**README**

- [ ] Do you need both README.md and README.Rmd? Having both runs the risk of
  one getting out of date.

**inst**

- [ ] I noticed you have citations in your README and vignette. Would you like
  to include them on the package landing page and for default citation. If so
  please include `inst/CITATION` file. It must be able to be read by
  `readCitationFile`  without the package being loaded with library. If you
  don't include a citation file the default package citation will be generated
  from the DESCRIPTION.
  

**vignette**

- [ ] Please rename the vignette. `vignette.Rmd` is too generic and can cause
  naming conflicts depending on which packages a user has loaded and the search
  path.  We highly recommend using the name of the package
  `VectraPolarisData.Rmd`

 
Please rename the vignette and then the package is ready for acceptance.

**Comment by lshep** [comment]
@julia-wrobel  please also try to push up these changes before Friday so that the package can be accepted and included in the Bioconductor 3.15 release.

**Comment by julia-wrobel** [comment]
> Hi there. A few minor comments before acceptance:
> 
> **README**
> 
> * [ ]  Do you need both README.md and README.Rmd? Having both runs the risk of
>   one getting out of date.
> 
> **inst**
> 
> * [ ]  I noticed you have citations in your README and vignette. Would you like
>   to include them on the package landing page and for default citation. If so
>   please include `inst/CITATION` file. It must be able to be read by
>   `readCitationFile`  without the package being loaded with library. If you
>   don't include a citation file the default package citation will be generated
>   from the DESCRIPTION.
> 
> **vignette**
> 
> * [ ]  Please rename the vignette. `vignette.Rmd` is too generic and can cause
>   naming conflicts depending on which packages a user has loaded and the search
>   path.  We highly recommend using the name of the package
>   `VectraPolarisData.Rmd`
> 
> Please rename the vignette and then the package is ready for acceptance.

Just made these changes! Let me know if I need anything else.

**Comment by lshep** [comment]
The vignette is still `vignette.Rmd`.  It needs to be renamed preferably VectraPolarisData.Rmd. 

I will assume then you do not want to include the CITATION file as it is still not present.

**Comment by lshep** [comment]
I think you accidentally removed the vignette entirely instead of renaming it?

**Comment by julia-wrobel** [comment]
I'm having some issues because I made the changes you requested on a different computer (including renaming the vignette) than the one I committed and pushed them on- should have it worked out by the end of the day!

**Comment by lshep** [comment]
sounds good thanks!

**Comment by lshep** [comment]
Thanks!

**Comment by julia-wrobel** [comment]
Thanks!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/julia-wrobel.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VectraPolarisData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VectraPolarisData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
