### ISSUE TITLE
tomoseqr

### ISSUE THREAD

**Issue by shingenmochi** [Bioconductor/Contributions#2597]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bioinfo-tsukuba/tomoseqr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this interesting submission.  Some changes will be needed before review.

The following is not standard practice for Bioconductor vignettes.
```
download.file("https://figshare.com/ndownloader/files/34384922", destfile = "sheld_AV.tsv")
download.file("https://figshare.com/ndownloader/files/34384925", destfile = "sheld_LR.tsv")
download.file("https://figshare.com/ndownloader/files/34384928", destfile = "sheld_VD.tsv")
download.file("https://figshare.com/ndownloader/files/34523069", destfile = "mask_97x97x97.rda")
library(readr)

sheld_AV <- read_tsv("sheld_AV.tsv")
sheld_LR <- read_tsv("sheld_LR.tsv")
sheld_VD <- read_tsv("sheld_VD.tsv")
load("mask_97x97x97.rda") 
```
Please see the developer guidelines on external data, 13.2.4 at http://contributions.bioconductor.org/data.html.  Probably we would want to see these resources in an ExperimentHub; at a minimum the retrieval would have to employ BiocFileCache.

**Comment by shingenmochi** [comment]
Hello, @vjcitn 
Thank you very much for your advice!
I have modified the code to use BiocFileCache and pushed to main branch.
Am I responding correctly to your request?

**Comment by vjcitn** [comment]
I get it, but I don't think this is the best way to proceed.
```
> tomoseqr:::GetTomoseqrCache
function () 
{
    cache <- R_user_dir("tomoseqrCache", which = "cache")
    BiocFileCache(cache)
}
<bytecode: 0x11f740040>
<environment: namespace:tomoseqr>
>  tomoCache <- DownloadJunker2014()
/Users/vincentcarey/Library/Caches/org.R-project.R/R/tomoseqrCache
  does not exist, create directory? (yes/no): junker2014 <- LoadJunker2014(tomoCache)
/Users/vincentcarey/Library/Caches/org.R-project.R/R/tomoseqrCache
  does not exist, create directory? (yes/no): yes
Downloading sheld_AV......
Downloading sheld_VD......
Downloading sheld_LR......
Downloading mask97x97x97......
>  tomoCache <- DownloadJunker2014()
Downloading sheld_AV......
Downloading sheld_VD......
Downloading sheld_LR......
Downloading mask97x97x97......
```
You have "downloading" messages which are not needed if BiocFileCache is used in an appropriate way.  @lshep

**Comment by vjcitn** [comment]
No download is occuring.  You are deserializing from a cache.  The message should not be printed.

**Comment by shingenmochi** [comment]
Sorry, I was unaware of this problem because I did not clear the cache before testing.
I have fixed it so that it downloads correctly. I would appreciate your confirmation.

**Comment by shingenmochi** [comment]
I understood that this code would print a download message even when using cache.
I removed Download messages.

**Comment by jianhong** [comment]
# Package 'tomoseqr' Review
The package passed check and build. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] R version should be no less than 4.2

## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 17 import(jsonlite)
- [ ] Use `camelCaps` to name your function, see [coding style](http://bioconductor.org/developers/how-to/coding-style/). `CamelCaps` is used for class names.

## General package development
- [ ] empty NEWS file are not acceptable.
- [ ] Please consider to arrange image files in `inst` to a subfolder under `inst`.
- [ ] test failure in `expect_equal`. Please set tolerance for the test. 
Error: Failure in `── Failure (test-Estimate3dExpressions.R:20:5): Reconstruction of 3D expression pattern ──
sum((result1 - true1)^2) (`actual`) not identical to 0 (`expected`).

  `actual`: 0.00000000000000000004
`expected`: 0.00000000000000000000
── Failure (test-Estimate3dExpressions.R:21:5): Reconstruction of 3D expression pattern ──
sum((result2 - true2)^2) (`actual`) not identical to 0 (`expected`).

  `actual`: 0.000000000000000000007
`expected`: 0.000000000000000000000
── Failure (test-Estimate3dExpressions.R:22:5): Reconstruction of 3D expression pattern ──
sum((result3 - true3)^2) (`actual`) not identical to 0 (`expected`).

  `actual`: 0.000000000000000000003
`expected`: 0.000000000000000000000
── Failure (test-Estimate3dExpressions.R:23:5): Reconstruction of 3D expression pattern ──
sum((result4 - true4)^2) (`actual`) not identical to 0 (`expected`).

  `actual`: 0.000000000000000000002
`expected`: 0.000000000000000000000
── Failure (test-FindAxialGene.R:6:5): Extract peak genes at axial ─────────────
`testAll` (`actual`) not identical to `resultAll` (`expected`).

    actual$meanExeptMax  | expected$meanExeptMax    
[1] 551.02040816326519   - 551.02040816326530    [1]
[2] 2333.67346938775518  | 2333.67346938775518   [2]
[3] 22.44897959183672    - 22.44897959183674     [3]
[4] 26897.95918367346894 | 26897.95918367346894  [4]
── Failure (test-FindAxialGene.R:7:5): Extract peak genes at axial ─────────────
`testPartial` (`actual`) not identical to `resultPartial` (`expected`).

  `actual$meanExeptMax`: 551.02040816326519 22.44897959183672
`expected$meanExeptMax`: 551.02040816326530 22.44897959183674

## R code
- [ ] No `paste` in `message()`, `message()`, `stop()`.
* In file R/inner_functions.R:
           + at line 7 found  '                str_c('
           + at line 17 found '        stop(str_c(queryNotInStr, ' is not in data.'))'

- [ ] Vectorize: no unnecessary `for` loops present.Try to re-arrange dimension by `dim` and add `unit test` to validate your code. 
	* In file R/functionForShiny.R:
		+ at line 63 found '    for (i in seq_along(plotArray[1, 1, ])) {'
	* In file R/inner_functions.R:
		+ at line 35 found '    for (i in seq_len(lenZ)) {'
		+ at line 111 found '    for (i in seq_len(numIter)) {'
		+ at line 223 found '    for (i in seq_along(plotArray[1, 1, ])) {'
	* In file R/run_function.R:
		+ at line 73 found '    for (geneID in query) {'
- [ ] Remove unused code.
	* In file R/ImageViewer.R:
		+ at line 51 found '                            # style = "overflow-y: scroll",'
		+ at line 69 found '                                # animate=TRUE,'
		+ at line 142 found '                            # style = "overflow-y: scroll",'
		+ at line 160 found '                                # animate=TRUE,'
		+ at line 233 found '                            # style = "overflow-y: scroll",'
		+ at line 251 found '                                # animate=TRUE,'
- [ ] Functional programming: code repetition.
	* repetition in `Animate2d` and `ShinyAnimate2d`
		+ in Animate2d
			- line 12:    }
			- line 13:    reconstArray <- tomoObj[["results"]][[geneID]][["reconst"]] %>% 
			- line 14:        aperm(perm = c(xaxis, yaxis, 6 - (xaxis + yaxis)))
			- line 15:    maskArray <- tomoObj[["mask"]] %>% aperm(perm = c(xaxis, 
			- line 16:        yaxis, 6 - (xaxis + yaxis)))
			- line 17:    saveGIF(AnimateForGIF(reconstArray = reconstArray, maskArray = maskArray, 
			- line 18:        main = main, xlab = xlab, ylab = ylab, zlim = zlim, aspectRatio = aspectRatio, 
			- line 19:        type = target), movie.name = file, interval = interval, 
			- line 20:        autobrowse = FALSE)
		+ in ShinyAnimate2d
			- line 3:{
			- line 4:    reconstArray <- tomoObj[["results"]][[geneID]][["reconst"]] %>% 
			- line 5:        aperm(perm = c(xaxis, yaxis, 6 - (xaxis + yaxis)))
			- line 6:    maskArray <- tomoObj[["mask"]] %>% aperm(perm = c(xaxis, 
			- line 7:        yaxis, 6 - (xaxis + yaxis)))
			- line 9:        saveGIF(ShinyAnimateForGIF(reconstArray = reconstArray, 
			- line 10:            maskArray = maskArray, main = main, xlab = xlab, 
			- line 11:            ylab = ylab, zlim = zlim, aspectRatio = aspectRatio, 
			- line 12:            type = target), movie.name = file, interval = interval, 
	* repetition in `AnimateForGIF` and `PlotForImageViewer`
		+ in AnimateForGIF
			- line 1:    maskArray, main, xlab, ylab, zlim, aspectRatio, type) 
			- line 2:{
			- line 3:    if (length(aspectRatio) < 2) {
			- line 4:        plotDim <- dim(reconstArray)
			- line 5:        asp <- plotDim[2]/plotDim[1]
			- line 6:    }
			- line 7:    else {
			- line 8:        asp <- aspectRatio[2]/aspectRatio[1]
			- line 9:    }
			- line 10:    plotArray <- MakePlotArray(reconstArray = reconstArray, maskArray = maskArray, 
			- line 11:        zlim = zlim, type = type)
		+ in PlotForImageViewer
			- line 1:    maskArray, main, xlab, ylab, zlim, aspectRatio, type, sectionNumber) 
			- line 2:{
			- line 3:    if (length(aspectRatio) < 2) {
			- line 4:        plotDim <- dim(reconstArray)
			- line 5:        asp <- plotDim[2]/plotDim[1]
			- line 6:    }
			- line 7:    else {
			- line 8:        asp <- aspectRatio[2]/aspectRatio[1]
			- line 9:    }
			- line 10:    plotArray <- MakePlotArray(reconstArray = reconstArray, maskArray = maskArray, 
			- line 11:        zlim = zlim, type = type)
## Documentation
- [ ] Vignette should have an *Introduction* section..
	* rmd file vignettes/tomoseqr.Rmd
- [ ] If appropriate, we strongly encourage a table of contents.

**Comment by shingenmochi** [comment]
Thank you for your review!
I'll try to fix.

**Comment by shingenmochi** [comment]
Hello, @jianhong

I fixed my code!

## The DESCRIPTION file

- [x] R version should be no less than 4.2

## The NAMESPACE file

- [x] Selective imports using importFrom instead of import all with import.
> in line 17 import(jsonlite)

- I removed this statement because I found no need to import jsonlite.
(This need for import was due to an unusual dependency of the shiny package in my environment.)

- [x] Use camelCaps to name your function, see coding style. CamelCaps is used for class names.

## General package development

- [x] empty NEWS file are not acceptable.

- [x] Please consider to arrange image files in inst to a subfolder under inst.

- moved image files to `inst/images`.

- [x] test failure in expect_equal. Please set tolerance for the test.

- I set tolerance to 1e-6.

## R code

- [x] No paste in message(), message(), stop().

- [ ] Vectorize: no unnecessary for loops present.Try to re-arrange dimension by dim and add unit test to validate your code.

- I got rid of most of the for loops, but could not get rid of one (in `singleEstimate()`). Here, the value is updated at each step of the loop, and the (n)th result is used for the (n+1)th calculation. Therefore, I think it would be difficult to apply the apply function, etc.

- [x] Remove unused code.

- [x] Functional programming: code repetition.
> repetition in Animate2d and ShinyAnimate2d

- I have integrated Animate2d with ShinyAnimate2d.

> repetition in AnimateForGIF and PlotForImageViewer

- PlotForImageViewer is no longer needed and I have removed it.

## Documentation

- [x] Vignette should have an Introduction section..

- [x] If appropriate, we strongly encourage a table of contents.

**Comment by jianhong** [comment]
@shingenmochi Great job. I will put the package as accepted. Please make improvement in the future in following two aspects:
1. improve the test coverage.
2. add  runnable examples to doadJunker2014.Rd, downloadJunker2014.Rd

**Comment by shingenmochi** [comment]
Thank you for your review and accepting!
I would keep improving this package!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shingenmochi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tomoseqr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tomoseqr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
