### ISSUE TITLE
extraChIPs

### ISSUE THREAD

**Issue by smped** [Bioconductor/Contributions#2598]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/steveped/extraChIPs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Looks good.  Lots of Gviz.  Have you looked at TnT for interactive data+gene models visualization?

**Comment by smped** [comment]
Ooh. Thanks for the heads up Vince. That might be really useful! I'll put it on my list of things to explore

**Comment by lshep** [comment]
I haven't looked at the R code yet but in the meantime here are some initial comments 

**Build Report**

- [ ] Please clean up ERROR, Warning, Notes of the build report

**Other**

- [ ] We recommend having extra extensions like  _pkgdown.yml and codecov.yml on
  separate branches rather than in the Bioconductor branches.   

**Description**

- [ ] We don't recommend including static fields like Date that often are not
  updated or forgotten to be updated.

- [ ] It looks like the license is actually GPL-3?


**README**

- [ ] Please update installation to be `BiocManager::install("extraChIPs")`. You
  may keep a reference of how to install the github version for 'latest/devel'
  but should also reference how to download the stable/release version.

**data**

- [ ] In the man page could you please indicate if the data was simulated or if
  it is a subset of existing data please provide a reference. 

**inst/extdata**

- [ ] Please include code, sudo-code, or text in `inst/scripts` that describes
  how the files were created/generated and any relevant source informatio for
  the files provided in `inst/extdata`


**man**

- [ ] Please provide a package level man page so that a user may get information
  from `?extraChIPs`.  It could link to the main functions of the package or the
  vignette but some overview/summary information on the package.

**Vignette**

**range**

- [ ] Update installation instructions for `BiocManager::install('extraChIPs')"`

**differential**

- [ ] In differential instllation section I think you also meant to add pkg as
  argument to first install as well as update to be stable/release version of
  your package instead of github installation.

- [ ] I am unable to run the sectino to create wincounts
```
> wincounts <- windowCounts(
+   bam.files = bfl,
+   spacing = 60,
+   width = 180,
+   ext = 200,
+   filter = 1,
+   param = rp,
+   BPPARAM = bpparam()
+ )
Error in .local(x, ...) : 
  'getOption("timeout")' must be positive integer(1)

```
Since I am unable to create wincounts, I'm unable to work through the rest of this vignette.  Please update before I do a more in-depth of the R code.  

Cheers,

**Comment by smped** [comment]
HI @lshep ,

Thanks for the feedback. I'll work may way through everything. I have a couple of questions though as I'm unsure about two of those points.

1. I don't get any ERROR messages when I build using github actions or the bioc-devel docker. I do get a WARNING on the bioc-devel docker though which is `‘qpdf’ is needed for checks on size reduction of PDFs`. As there are no pdfs in the package, this seems like an odd message. Searching has lead me to believe this is a stand-alone tool which needs to be on the build server. (https://stat.ethz.ch/pipermail/r-package-devel/2020q2/005335.html) Is this the error you are seeing? Are you able to provide any details as to which system you're seeing these on, or what they are if that's not the problem? (I can see a few things from BiocCheck which I can tidy though)
2. For the vignette issues, that's concerning. It's a call to `windowCounts()` from `csaw` giving that error so should be unrelated to `extraChIPs`. What do you get from `file.exists(path(bfl))`? I can't reproduce the error on any of my machines, but they are all Linux. Do we need to flag this with the `csaw` authors?
 
Thanks in advance

**Comment by lshep** [comment]
1. Click on the build report posted in the comment above to see the full build report.  The ERROR have to do with signing up for the Bioconductor support site and developer mailing list which is a requirement of maintainers. 

2. I am also on a linux machine. It seems to come from BiocParallel 
```
> wincounts <- windowCounts(
+   bam.files = bfl,
+   spacing = 60,
+   width = 180,
+   ext = 200,
+   filter = 1,
+   param = rp,
+   BPPARAM = bpparam()
+ )
Error in .local(x, ...) : 
  'getOption("timeout")' must be positive integer(1)


> traceback()
5: stop("'getOption(\"timeout\")' must be positive integer(1)")
4: .local(x, ...)
3: bpstart(BPPARAM)
2: bpstart(BPPARAM)
1: windowCounts(bam.files = bfl, spacing = 60, width = 180, ext = 200, 
       filter = 1, param = rp, BPPARAM = bpparam())

> file.exists(path(bfl))
[1] TRUE TRUE TRUE

> sessionInfo()
R Under development (unstable) (2022-01-07 r81458)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /home/shepherd/R-Installs/bin/R-devel/lib/libRblas.so
LAPACK: /home/shepherd/R-Installs/bin/R-devel/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] rtracklayer_1.55.4          BiocParallel_1.29.19       
 [3] csaw_1.29.1                 SummarizedExperiment_1.25.3
 [5] Biobase_2.55.1              MatrixGenerics_1.7.0       
 [7] matrixStats_0.61.0          Rsamtools_2.11.0           
 [9] Biostrings_2.63.3           XVector_0.35.0             
[11] GenomicRanges_1.47.6        GenomeInfoDb_1.31.7        
[13] IRanges_2.29.1              S4Vectors_0.33.16          
[15] BiocGenerics_0.41.2         forcats_0.5.1              
[17] stringr_1.4.0               dplyr_1.0.8                
[19] purrr_0.3.4                 readr_2.1.2                
[21] tidyr_1.2.0                 tibble_3.1.6               
[23] ggplot2_3.3.5               tidyverse_1.3.1            
[25] praise_1.0.0                BiocManager_1.30.16        

loaded via a namespace (and not attached):
 [1] httr_1.4.2               edgeR_3.37.1             jsonlite_1.8.0          
 [4] modelr_0.1.8             assertthat_0.2.1         GenomeInfoDbData_1.2.7  
 [7] cellranger_1.1.0         yaml_2.3.5               pillar_1.7.0            
[10] backports_1.4.1          lattice_0.20-45          glue_1.6.2              
[13] limma_3.51.5             rvest_1.0.2              colorspace_2.0-3        
[16] Matrix_1.4-1             XML_3.99-0.9             pkgconfig_2.0.3         
[19] broom_0.7.12             haven_2.4.3              zlibbioc_1.41.0         
[22] scales_1.1.1             tzdb_0.3.0               generics_0.1.2          
[25] ellipsis_0.3.2           withr_2.5.0              cli_3.2.0               
[28] magrittr_2.0.3           crayon_1.5.1             readxl_1.4.0            
[31] fs_1.5.2                 fansi_1.0.3              xml2_1.3.3              
[34] tools_4.2.0              hms_1.1.1                BiocIO_1.5.0            
[37] lifecycle_1.0.1          munsell_0.5.0            reprex_2.0.1            
[40] locfit_1.5-9.5           DelayedArray_0.21.2      compiler_4.2.0          
[43] rlang_1.0.2              grid_4.2.0               RCurl_1.98-1.6          
[46] rstudioapi_0.13          rjson_0.2.21             bitops_1.0-7            
[49] restfulr_0.0.13          gtable_0.3.0             DBI_1.1.2               
[52] R6_2.5.1                 GenomicAlignments_1.31.2 lubridate_1.8.0         
[55] utf8_1.2.2               metapod_1.3.0            stringi_1.7.6           
[58] parallel_4.2.0           Rcpp_1.0.8.3             vctrs_0.4.0             
[61] dbplyr_2.1.1             tidyselect_1.1.2        
> 

```


I had our GenomicRanges expert take a quick peak.  I will look at the R functions in more detail too but his quick comments on the implementation: 
* not every function needs to be a generic function
* not every generic function needs to have the ellipsis (...) in its arguments
* it rarely makes sense to have a generic function dispatch on all its arguments
* there's no need to define a default method that returns the following error:
```
> distinctMC(letters)
Method not implemented for character
```
The dispatch method already does that 
```
> foo(letters)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'foo' for signature '"character"'
```


Cheers,

**Comment by smped** [comment]
Hi @lshep ,

Thanks for all those clarifications. I'm well on the way fixing all those things on the to-do list now. Just one quick question about the vignette though. Does that code work for you if you run.

```r
wincounts <- windowCounts(
   bam.files = bfl,
   spacing = 60,
   width = 180,
   ext = 200,
   filter = 1,
   param = rp
 )
```

I can't reproduce that error so I'm hoping that works for you. If so it'll be a quick fix for now, but I might have to rethink how to demonstrate BiocParallel. 

And also, thanks for the heads up about the `ANY` methods. I was asked to put them into a previous package submission and really found it a bit pointless for the reasons you describe. And they make the `man` pages look messy.

Cheers

**Comment by lshep** [comment]
I do not get an ERROR trying the above code.  I'll work through the rest of that vignette and have a glance at the R code.  If there is anything else additional I will post by the end of day today.  Cheers

**Comment by lshep** [comment]
I get a similar error when trying to run dualFilter 

```
> filtcounts <- dualFilter(
+   x = wincounts[, !is.na(wincounts$treat)],
+   bg = wincounts[, is.na(wincounts$treat)], 
+   ref = peaks,
+   q = 0.8 # Better to use q = 0.5 on real data
+ )
Error in .local(x, ...) : 
  'getOption("timeout")' must be positive integer(1)

```
The vignette seemed to run fine on the builders so maybe this is just my issue.  I'll proceed with code review but just be mindful that at least I encounter these types of errors.

**Comment by smped** [comment]
Hmm. Thanks @lshep .

I'm just using what I thought would be fairly simple call to `bpparam()` by setting a function argument `BPPARAM = bpparam()`. Clearly this is problematic. Do you have any suggestions? Should I set an argument like `BPPARAM = SerialParam()` as Aaron Lun has done for `csaw::windowCounts()`

**Comment by smped** [comment]
Ah! Maybe I should set BiocParallel in the `Depends` field for the `DESCRIPTION` file?

**Comment by lshep** [comment]
If your functions absolutely depend on BiocParallel to run than yes but if it is optional, I don't think the heavier dependency will matter.  I haven't used BiocParallel much in my own work so not sure how setting the different param may make a difference.  Again since it worked on the builders, I'm okay with you leaving as is but just be aware that you may get questions in the future if someone has similar issues as myself.

**Comment by lshep** [comment]
Everything else looks good. let me know when you are ready for re-review after you make the additional changes

**Comment by smped** [comment]
Thanks @lshep. Much appreciated. I'm just digging through Aaron's code & have found how he is handling the `bpstart()` issue. I'll do some porting. :)

**Comment by smped** [comment]
Hi @lshep . I think I'll stop tweaking now & call it ready for review. I think I've hit every point you mentioned and have also cut back the S4 methods. Thanks again

**Comment by lshep** [comment]
@steveped  sounds good.  can you push up a version bump to trigger a new build report please.

**Comment by lshep** [comment]
Remember to activate your git credentials account [here](https://git.bioconductor.org/BiocCredentials) to add ssh-keys for push access.   And useful documentation for setting up remotes to push to git.bioconductor.org can be found [here](http://contributions.bioconductor.org/git-version-control.html#new-package-workflow)

**Comment by smped** [comment]
Thanks @lshep . Most helpful links. I'd missed the bit where I needed to add `upstream`. Been a while...

**Comment by smped** [comment]
Hi @lshep. I've set everything to have a build time just over 5 mins on Linux, but it still times out at 15min on OSX. Is that common, or do I need to keep tidying things? My current tricks for time saving were using `\donttest{}` on time-consuming examples and dropping a few tests from `testthat`

**Comment by lshep** [comment]
hmm. I'll try to investigate more on the mac builder.  We would prefer to leave as many examples and test running as possible.  Maybe also look at moving test to the [long test framework](http://contributions.bioconductor.org/long-tests.html)  You'll still want some to run daily for regular checks but this would be a good option for very time consuming tests.  I'm also inclined to review based on the linux outputs and timings to see what happens when its moved over to the daily builder once accepted.  It might just be the single package builder being overloaded during release time for the strong difference between platforms.

**Comment by smped** [comment]
Ooh. Didn't know about the long test framework. Thanks! I'll check the results from codecov and will see what I can get back in there. Dropping tests definitely feels like an unsatisfactory solution, so this could be the solution.

**Comment by smped** [comment]
HI @lshep. I've migrated a few tests to longtests & have even managed to get these into my github actions so they actually get tested on push. There's still a big discrepancy between Mac & Linux build times though. It's about 6 minfor Linux, but still times out for Mac. Happy to keep playing if you'd like, but obviously, getting the package finalised & accepted would be brilliant if I can manage it.

**Comment by lshep** [comment]
I'll review.  If the timeout still occurs after acceptance please follow up.  I'll also try to hop on our mac to see if I can nail down what function / functions are taking the longest.  
Cheers,

**Comment by lshep** [comment]
I just went on the mac and checked the timings and nothing seems to be taking
extraordinarily long.  I think I'm happy making the review on linux and see if
this reoccurs when its on the daily builder.  If it occurs again there we will
have to debug further.


**data/man**

- [ ] In the man page could you please indicate if the data was simulated or if
    it is a subset of existing data please provide a reference/source/citation


**vignette**

I now get an error on this step similar to before: 

```
> filtcounts <- dualFilter(
+   x = wincounts[, !is.na(wincounts$treat)],
+   bg = wincounts[, is.na(wincounts$treat)], 
+   ref = peaks,
+   q = 0.8 # Better to use q = 0.5 on real data
+ )
Error in .local(x, ...) : 
  'getOption("timeout")' must be positive integer(1)

```
which again prevents me from moving forward with the rest of the vignette.

The rendered vignette looks good and is very informative.


**R/code**

Looks good. 


I don't want to prevent acceptance if this is an issue with my own local computer but just be aware that if other users start reporting these cases it will be something to investigate.   Once you add the data clarification I will accept and if you would like to investigate my errors further i would be glad to help test or trial.  

Cheers,

**Comment by smped** [comment]
Thanks @lshep . This is clearly caused by my setting the argument `BPPARAM = bpparam()`. I'm really struggling to know how to handle this. I've included the following lines in the function, and loaded BiocParallel using Depends, but it hasn't worked
```
if (!bpisup(BPPARAM)) {
   bpstart(BPPARAM)
   on.exit(bpstop(BPPARAM))
}
```

Given that I don't get this error, does inclusion of the following line before calling `dualFilter()` make any difference?

```
register(SerialParam())
```
Are there any other suggestions? I just want to call `bpparam()` like I see in other functions but this seems surprisingly difficult.

**Comment by lshep** [comment]
Sadly I don't have much experience with BiocParallel. I'll take some BiocParallel people and see if they have any advice

**Comment by lshep** [comment]
@mtmorgan  @Jiefei-Wang  -- Is this an issue with my set up or with implementation?

**Comment by smped** [comment]
Thanks @lshep. Much appreciated. If we can't get it fixed, I'll change the default argument to `BPPARAM = SerialParam()`. Internally it's just passed to `csaw::windowCounts()` and that's the default argument for that function. Maybe that'll sort it out as a last resort.

**Comment by Jiefei-Wang** [comment]
Thanks @lshep for letting me know the issue. I will take a look at it today

**Comment by mtmorgan** [comment]
This sounds like a local configuration issue; what does `class(getOption("timeout"))` give? From `?options`, this should be a non-negative integer; maybe it's a real number, `1` instead of `60L`?

**Comment by lshep** [comment]
```
> class(getOption("timeout"))
[1] "numeric"
> 
> getOption("timeout")
[1] 300

```

**Comment by mtmorgan** [comment]
So I think you must be setting this, say in `~/.Rprofile`, as `options(timeout = 300)` and it could be changed to `options(timeout = 300L)`. BiocParallel can be less strict on this... I'll open an issue.

**Comment by smped** [comment]
Thanks @mtmorgan. Appreciate the help & nice to know I haven't ventured too far off the sensible path.

**Comment by lshep** [comment]
@mtmorgan  Yes changing to 300L in my .Rprofile allowed me to run the code.  
@steveped feel free to change back whatever was changed on my account/BiocParallel strictness.

@steveped  I think you should mention how the data was generated in the man page as well as `inst/scripts/ex_datasets.md` or at least put a pointer to the `inst/scripts/ex_datasets` in the man page so that users can really understand what the data is and how if they wanted to copy.  Minor issue since it is documented somewhere I will continue with acceptance. Again I didn't see anything on the mac that would indicate why or what is causing the timeout but if it continues on the daily builder I'll be glad to help debug further. It seemed to run within time limits when I ran manually.  Changing my .Rprofile allowed me to run the other vignette on my linux and it looks good. 

Cheers,

**Comment by smped** [comment]
Thanks @lshep. That's great news! I've just done a version bump & which includes a link to that script in the man page. Good luck with getting the release all sorted too.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/steveped.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("extraChIPs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/extraChIPs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
