### ISSUE TITLE
sSNAPPY

### ISSUE THREAD

**Issue by Wenjun-Liu** [Bioconductor/Contributions#2599]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Wenjun-Liu/sSNAPPY

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Vignettes is taking inordinately long to compile.  Can you thin it out?  Maybe use some precomputed entities?  If you need long tests, use that facility.

**Comment by Wenjun-Liu** [comment]
Hi Vince, Thank you for your suggestion! I have updated my vignette to let it use pre-computed results. Compiling of it should be fairly quick now. Please let me know if you see any other problems.

Cheers, 
Wenjun

**Comment by Wenjun-Liu** [comment]
Hi, I have made changes based on the build report but I cannot push to `git@git.bioconductor.org:packages/sSNAPPY`. When I tried to do it, it says "permission denied". I was trying to submit my SSH to the BioCredential site by firstly activating my account . But after filling in the information at: https://git.bioconductor.org/BiocCredentials/account_activation/, I didn't receive any email. Did I do something wrong? Thank you in advance for your help.

**Comment by lazappi** [comment]
Hi @Wenjun-Liu. Someone from @Bioconductor/core should be able to help out with this. As a first suggestion please check that your email in the package `DESCRIPTION` file is the same as the one you used to sign up on the BiocCredentials site.

**Comment by lshep** [comment]
@Wenjun-Liu  did you check your spam folder? Sometimes the verification email gets flagged as spam?

**Comment by Wenjun-Liu** [comment]
Thank you @lshep and @lazappi! The verification emails did go to my spam folder. I should have checked!

**Comment by lazappi** [comment]
Hi @Wenjun-Liu

Thanks for submitting **sSNAPPY** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please address as many of the notes from `BiocCheck::BiocCheck()` as possible
- [ ] :rotating_light: Please remove the complied `.o` from the git repository as suggested by `BiocCheck::BiocCheckGitClone()`

## DESCRIPTION file

- [ ] :rotating_light: Bioconductor recommends setting `LazyData: False`
- [ ] :warning: It is recommended to set a `BugReports` field, this usually points to the GitHub issues page or the Bioconductor support forum

## NAMESPACE file

- [ ] :rotating_light: Please be consistent with the use of `camelCase` or `snake_case` for function names

## Package data

- [ ] :rotating_light: Please document the data in `inst/extdata` with scripts in `inst/script`

## Documentation

- [ ] :green_circle: I noticed typos in a few places, you can check for these using the **spellcheck** package (see `usethis::use_spellcheck()`)

### README

- [ ] :rotating_light: Please use the standard Bioconductor installation chunk

````
```r
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("sSNAPPY")
```
````

### Vignette

- [ ] :rotating_light: Please add a table of contents to the vignette
- [ ] :rotating_light: Please avoid having unevaluated chunks in the vignette
- [ ] :rotating_light: Please avoid having hidden chunks in the vignette (`eval = FALSE`)
- [ ] :rotating_light: Please add an *Installation* section to the vignette with the standard installation chunk (this should have `eval = FALSE`)
- [ ] :rotating_light: The vignette should not create new files (see the comment about caching below)
- [ ] :green_circle: Please see the **{BiocStyle}** for details on how to format the vignette (things like linking to other packages)
- [ ] :green_circle: I found some of the code in the vignette difficult to read. You may want to look at how it is formatted or even if some of it could be made into functions in the package.
- [ ] :warning: The output of the `ssPertScore` chunk was empty when I ran the vignette, please check what is happening here

## Code

### R

- [ ] :rotating_light: Please use `vapply` instead of `sapply`
- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :rotating_light: No not need to use `paste0` in `message()`, `warning()`, `stop()`
- [ ] :green_circle: Please think about whether you could support a standard Bioconductor object like `SummarizedExperiment`
- [ ] :warning: Consider adding validity checks for function arguments in exported functions
- [ ] :rotating_light: Please check you are following the guidelines for [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/)
- [ ] :rotating_light: Downloaded files should be cached with `BiocFileCache`. This will make things easier for users and avoid some of the issues you have with files being saved.
- [ ] :warning: It would be better if `weightedAdjMatrix()` returned the object rather than just creating a file which the user needs to load
- [ ] :rotating_light: Please avoid `suppressWarnings()` if possible

### C and Fortran code

- [ ] :rotating_light: Please check that your C code checks for user interruption
- [ ] :rotating_light: Please removed the commented code in the C source files

### Third-party code

- [ ] :rotating_light: I noticed some code borrowed from other packages. Please make sure this follows the [guidelines](https://contributions.bioconductor.org/third-party-code.html) and matches the original license.

**Comment by Wenjun-Liu** [comment]
Hi Luke @lazappi, thank you very much for your suggestions! I have fixed my codes accordingly. Please see the summary below:

### General package development
- [x] ⚠️ Please address as many of the notes from BiocCheck::BiocCheck() as possible
- [x] 🚨 Please remove the complied .o from the git repository as suggested by BiocCheck::BiocCheckGitClone()
### DESCRIPTION file
- [x]  🚨 Bioconductor recommends setting LazyData: False
 - [x] ⚠️ It is recommended to set a BugReports field, this usually points to the GitHub issues page or the Bioconductor support forum
### NAMESPACE file
 - [x] 🚨 Please be consistent with the use of camelCase or snake_case for function names
Package data
 - [x] 🚨 Please document the data in inst/extdata with scripts in inst/script
Documentation
- [x]  🟢 I noticed typos in a few places, you can check for these using the spellcheck package (see usethis::use_spellcheck())
### README
 - [x] 🚨 Please use the standard Bioconductor installation chunk
### Vignette
 - [x] 🚨 Please add a table of contents to the vignette
 - [ ]  🚨 Please avoid having unevaluated chunks in the vignette
 - Some of my functions take very long to run so I saved the output of those functions in `inst/extdata` and set the chunks holding those code to `eval = FALSE` so my vignette won't take forever to build. Could you let me know if you have any alternative suggestions?
- [x] 🚨 Please add an Installation section to the vignette with the standard installation chunk (this should have eval = FALSE)
- [x] 🚨 The vignette should not create new files (see the comment about caching below)
- [x] 🟢 Please see the {BiocStyle} for details on how to format the vignette (things like linking to other packages)
- [x]  🟢 I found some of the code in the vignette difficult to read. You may want to look at how it is formatted or even if some of it could be made into functions in the package.
- [ ] ⚠️ The output of the ssPertScore chunk was empty when I ran the vignette, please check what is happening here
 - I couldn't replicate this problem. Did codes following that chuck work alright for you? 
### Code
#### R
- [x] 🚨 Please use vapply instead of sapply
- [x] 🚨 Please use seq_along()/seq_len() instead of 1:...
- [x] 🚨 No not need to use paste0 in message(), warning(), stop()
- [x] 🟢 Please think about whether you could support a standard Bioconductor object like SummarizedExperimen
 - The package still only accepts logCPM matrix at this stage but I will keep this at the back of my mind!
- [x] ⚠️ Consider adding validity checks for function arguments in exported functions
- [x] 🚨 Please check you are following the guidelines for [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/)
 🚨 Downloaded files should be cached with BiocFileCache. This will make things easier for users and avoid some of the issues you have with files being saved.
 ⚠️ It would be better if weightedAdjMatrix() returned the object rather than just creating a file which the user needs to load
 - I have changed `weightedAdjMatrix()` (now called `retrieve_topology()`) to return the object directly, instead of storing the output as a file. This function is a wrapper around a chain of functions from the `graphite` package. I believe that they have dealt with the caching problem. But please let me know if there's anything that you think i should add to my package!
- [x] 🚨 Please avoid suppressWarnings() if possible
#### C and Fortran code
- [x] 🚨 Please check that your C code checks for user interruption
- [x] 🚨 Please removed the commented code in the C source files
#### Third-party code
- [x] 🚨 I noticed some code borrowed from other packages. Please make sure this follows the [guidelines](https://contributions.bioconductor.org/third-party-code.html) and matches the original license.
 - Codes for one of the helper functions, which replaces the nth occurrence of a string with a pattern was borrowed from a github package (`martinctc/textworks`). The original function prints a message for every search it does and it cannot be turnt off. I have changed the codes to turn that feature off.

**Comment by lazappi** [comment]
> * [x]  ⚠️ Please address as many of the notes from BiocCheck::BiocCheck() as possible

There are still several notes in the [build report](http://bioconductor.org/spb_reports/sSNAPPY_buildreport_20220417215104.html). Please address those, particularly the following:

- Update R version dependency from 4.1.0 to 4.2.0
- Avoid the use of 'paste' in condition signals
- Avoid 'suppressWarnings'/'*Messages' if possible (found 2 times)
- Consider adding runnable examples to the following man pages which document exported objects: retrieve_topology.Rd
- Usage of dontrun{} / donttest{} found in man page examples. 40% of man pages use one of these cases.
- Use donttest{} instead of dontrun{}.

> * [x]  🚨 Please be consistent with the use of camelCase or snake_case for function names

There is still a mixture of styles used, for example `compute_perturbationScore()` should be either `compute_perturbation_score()` or `computePerturbationScore()`

> * [ ]   🚨 Please avoid having unevaluated chunks in the vignette
> * Some of my functions take very long to run so I saved the output of those functions in `inst/extdata` and set the chunks holding those code to `eval = FALSE` so my vignette won't take forever to build. Could you let me know if you have any alternative suggestions?

I don't think any of the chunks in your vignette took a long time to run. I would set everything to `eval = TRUE` and see if any of the checks complain. If they don't everything is fine, if they do you can consider other options like using a smaller example dataset or providing pre-computed version of some of the steps.

> * [ ]  ⚠️ The output of the ssPertScore chunk was empty when I ran the vignette, please check what is happening here
> * I couldn't replicate this problem. Did codes following that chuck work alright for you?

This still happens with the current version and then there is an error in the `normalizedScores` chunk. It seems to be fine on the build system though so maybe it's something I did wrong.

> * [x]  🟢 Please think about whether you could support a standard Bioconductor object like SummarizedExperimen
> * The package still only accepts logCPM matrix at this stage but I will keep this at the back of my mind!

Please look at doing this before the package is accepted. It is not a lot of work and will make your package compatible with a lot of existing Bioconductor packages. All you have to do is write small wrappers or methods which extract the required information from a `SummarizedExperiment` and pass it to your current functions.

>   🚨 Downloaded files should be cached with BiocFileCache. This will make things easier for users and avoid some of the issues you have with files being saved.
>   ⚠️ It would be better if weightedAdjMatrix() returned the object rather than just creating a file which the user needs to load
> * I have changed `weightedAdjMatrix()` (now called `retrieve_topology()`) to return the object directly, instead of storing the output as a file. This function is a wrapper around a chain of functions from the `graphite` package. I believe that they have dealt with the caching problem. But please let me know if there's anything that you think i should add to my package!

I just want to be sure how you have handled this. I think what you are doing now is downloading files to a temporary directory and then returning an object from the function? This would need to be done in every new R session. If you want to reuse things between sessions then you will need to use **{BiocFileCache}**. This is a little bit trickier because **{graphite}** does the downloading but might be worth it if what you are downloading doesn't change often. 

> * [x]  🚨 Please avoid suppressWarnings() if possible

This is still used in `compute_perturbationScore()`

> #### Third-party code
> * [x]  🚨 I noticed some code borrowed from other packages. Please make sure this follows the [guidelines](https://contributions.bioconductor.org/third-party-code.html) and matches the original license.
> * Codes for one of the helper functions, which replaces the nth occurrence of a string with a pattern was borrowed from a github package (`martinctc/textworks`). The original function prints a message for every search it does and it cannot be turnt off. I have changed the codes to turn that feature off.

The **{textworks}** package has a [GPL-3 license](https://choosealicense.com/licenses/gpl-3.0/) which requires any package that copies, modifies or resues code to have the same license. Please make sure you have read this license, understand what the requirements are and have followed them.

**Comment by Wenjun-Liu** [comment]
Sorry Luke @lazappi! I have fixed all problems that I overlooked now, except the caching one. To be honest with you, I am not very familiar with using **{BiocFileCache}**. I gave it a try but didn't have much luck. Is this something that I could possibly add on after my package is accepted? 

Apart from that, I have fixed:

- [x] Update R version dependency from 4.1.0 to 4.2.0
- [x] Avoid the use of 'paste' in condition signals
- [x] Avoid 'suppressWarnings'/'*Messages' if possible (found 2 times)
- [x] Consider adding runnable examples to the following man pages which document exported objects: retrieve_topology.Rd
- [x] Use donttest{} instead of dontrun{}.
- [x] Please be consistent with the use of camelCase or snake_case for function names
- [x] Please avoid having unevaluated chunks in the vignette
 - The `permutedScore` step in the vignette takes around 20 minutes to run on a 8-core machine. When I set that chuck to `eval = TRUE`, I got a timeout error. So now I set it back to `eval = FALSE` and provided pre-computed output. Hope that's ok! (I have reduced the example dataset size by half. But it still takes that long to run. If I use a even smaller subset of example data, I won't be able to have enough output demonstrating the use of visualisation function)
- [x] The output of the ssPertScore chunk was empty when I ran the vignette, please check what is happening here
 - I think I have found the problem behind this and fixed it. The error shouldn't occur anymore. 
- [x] Please think about whether you could support a standard Bioconductor object like SummarizedExperiment
 - SummarizedExperiment and DGEList are now accepted as inputs. 
- [x] I noticed some code borrowed from other packages. Please make sure this follows the [guidelines]
 - I have edited the license.

**Comment by lazappi** [comment]
> Sorry Luke @lazappi! I have fixed all problems that I overlooked now, except the caching one. To be honest with you, I am not very familiar with using **{BiocFileCache}**. I gave it a try but didn't have much luck. Is this something that I could possibly add on after my package is accepted?
> 
> Apart from that, I have fixed:
> 
> * [x]  Please be consistent with the use of camelCase or snake_case for function names

The package should consistently use camelCase or snake_case but you still you have a mix of both (`computePerturbationScore()` and `plot_gs_network()`, should be with `computePerturbationScore()` and `plotGSNetwork()` or `compute_perturbation_score()` and `plot_gs_network()`).

> * [x]  Please avoid having unevaluated chunks in the vignette
> * The `permutedScore` step in the vignette takes around 20 minutes to run on a 8-core machine. When I set that chuck to `eval = TRUE`, I got a timeout error. So now I set it back to `eval = FALSE` and provided pre-computed output. Hope that's ok! (I have reduced the example dataset size by half. But it still takes that long to run. If I use a even smaller subset of example data, I won't be able to have enough output demonstrating the use of visualisation function)

Ok, I have looked at this again and that chunk does take a long time to run. Maybe I accidentally skipped over it before, sorry for that. I think the solution you have now with showing that code but loading the results from a saved file is ok. Please echo the code that loads the data and include some text that explains what you are doing. There are some other code chunks where `echo = FALSE`, these should be shown to the user as well. The `normalisedScores` chunk also has `eval = FALSE` but that is quick so should be evaluated.

I also noticed the `gsTopology.rda` has returned to the `vignettes/` directory. Please remove this from the git repository and check that it is not created by running the vignette.

> * [x]  The output of the ssPertScore chunk was empty when I ran the vignette, please check what is happening here
> * I think I have found the problem behind this and fixed it. The error shouldn't occur anymore.

Yep, worked fine now 👍🏻 .

> * [x]  Please think about whether you could support a standard Bioconductor object like SummarizedExperiment
> * SummarizedExperiment and DGEList are now accepted as inputs.

Awesome, thanks for doing this! 🎉 It will make things much smoother for users.

I think there are just the small things with the function names and the vignette and then you will be good to go.

**Comment by Wenjun-Liu** [comment]
Thank you for your prompt response @lazappi! I have fixed the naming problem, removed the `gsTopology.rda` from `vignette/` directory, and set all vignette chunks to be `echo = TRUE`. For the `normalisedScores` chunk, I set it to be `eval = FALSE` because output of the `permutedScore` step was too big so I only stored a subset of it but with the subset of permutation result I still wouldn't be able to show the use of visualisation function. So I also pre-computed the full `normalisedScores`. I realised it could be confusing so I removed the subsetted permutation result and have added texts to explain that the  `permutedScore`  and `normalisedScores`  steps were set to be not executed because they take long time to run and the final result was pre-computed. Hope it makes sense!

**Comment by lazappi** [comment]
I think this is ok now, I will approve the package. Congratulations on getting it into Bioconductor 🎉! It can take a couple of days to be picked up by the build system but should hopefully make it into the next release.

**Comment by Wenjun-Liu** [comment]
Thank you @lazappi! This is great news! I really appreciated all of your help and feedback. Looking forward to the new bioconductor release. :)

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Wenjun-Liu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sSNAPPY")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sSNAPPY

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
