### ISSUE TITLE
CVE

### ISSUE THREAD

**Issue by andreasmock** [Bioconductor/Contributions#26]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/andreasmock/CVE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Hello, 

We had some trouble with the initial build and check of your package.  It appears that the code at some point is trying to connect to a local server. May we suggest enclosing the part of the example that runs the server in `\donttest{}`, so that the user can see and run it but the builder does not.  Also it doesn't appear that you have any unit tests for your package.  It is highly recommended that you add some unit tests for the overall functionality of the code.  An example would be adding unit test that pings the server and fails gracefully (e.g., time out after a suitable short time, a few seconds). 
I look forward to working with you further on reviewing your package. 

Cheers, 
Lori

**Comment by andreasmock** [comment]
Dear Lori,

thank you very much for your quick review of the package. As recommended, I have enclosed the examples in \donttest{} and added a unit test that pings the local server for the Shiny app and checks the right format of the input file.

Best regards,
Andreas

**Comment by andreasmock** [comment]
Dear Lori,

I have resolved all required issues except for having runnable examples. This is due to using 
\donttest{} in the openCVE function that calls the local server for the Shiny app. How do I proceed?

Best,
Andreas

**Comment by lshep** [comment]
I will review your package and reply with any comments or concerns soon.

**Comment by lshep** [comment]
Hello, 

Thank you for submitting your package to Bioconductor.  Please see the following comments/suggestions/questions and respond accordingly: 


GENERAL
It appears that there is a large amount of Data provided with the current application.  Please remove the Data in the package and submit as an ExperimentalData package. The package then can be linked to the current package ( https://github.com/Bioconductor/Contributions#submitting-related-packages ) 
The related package would then be listed in the appropriate field of the description and namespace. 
Unless there is a reason not to?
This will help clarify what are the main functions and applications vs what is specific to data provided.  
This should work for a users' provided data and it seemed unclear at what generic data could be.  A more generic example would be helpful. 

GENERAL
There seem to be random .DS_Store files in a number of different directorys (Data/,  inst/ , etc.). Is there a purpose for this file or can it be removed? 

DESCRIPTION 
In the description file there are some problems with depends, imports, suggests. 
1. Please remove BiocStyle and rmarkdown from imports and leave in suggests.   
2. The suggests field should contain the packages used in the the inst/doc ,vignettes, and test but not in code.  Please move the following to suggests:  pingr, limma, phytools, 
3. It was unclear where GO.db, GO.stats, GSEABase, impute, and prepocessCore are used.  I see that some of them are used in the vignette.  Please move the ones that were used in the vignette to suggests and remove any that are not used.  Please also add the library call to the code section of the vignette that utilizes these rather than just referencing the package in the text. 

NAMESPACE 
Please import the functions, classes, or packages that are being used with import(), importFrom(), importClassFrom(), etc.  
In general you should not need to access these packages with the (::) .  The (::) should be removed in the code and add the needed calls to the namespace. Everything that is listed in the import section of the description file should have some entry in the namespace.     

INST/DOC
This seems to have the same information/documentation as the vignettes.  Please remove since duplicated. 

VIGNETTE
CVE_tutorial 
It would be helpful to have a clarification on what is being displayed in the Shiny app.  A description of the widgets and tabs that are produced and what it is showing? What widgets are user interactive? 
A more generic implementation of how the user could implement their data would also be helpful
WGCNA_from_TCGA_RNAseq
As mentioned earlier please also include the library call in the code of section 4 to the GOstats


Thank you for your efforts and I look forward to an updated submission and comments. 

Lori

**Comment by andreasmock** [comment]
Dear Lori, @lshep

thank you very much for your quick review and your valuable suggestions. Please find my comments to your remarks in the following:
___

_GENERAL
It appears that there is a large amount of Data provided with the current application. Please remove the Data in the package and submit as an ExperimentalData package. The package then can be linked to the current package ( https://github.com/Bioconductor/Contributions#submitting-related-packages ) 
The related package would then be listed in the appropriate field of the description and namespace. 
Unless there is a reason not to?
This will help clarify what are the main functions and applications vs what is specific to data provided._

- Please correct me if I'm wrong but the only piece of data that could be outsources to a data package is the oncotator_example.RData file with 0.6 MB. 
- The second RData file (WGCNAmelanoma_extension.RData) is with 2.1MB larger, but an integral part of the package.

_This should work for a users' provided data and it seemed unclear at what generic data could be. A more generic example would be helpful._
- To facilitate the use of CVE, I have extended the CVE vignette by describing the input file needed in more detail.

_There seem to be random .DS_Store files in a number of different directorys (Data/, inst/ , etc.). Is there a purpose for this file or can it be removed?_
- I have removed the .DS_Store files, as they are not needed.

_DESCRIPTION 
In the description file there are some problems with depends, imports, suggests. 
1. Please remove BiocStyle and rmarkdown from imports and leave in suggests.
2. The suggests field should contain the packages used in the the inst/doc ,vignettes, and test but not in code. Please move the following to suggests: pingr, limma, phytools, 
3. It was unclear where GO.db, GO.stats, GSEABase, impute, and prepocessCore are used. I see that some of them are used in the vignette. Please move the ones that were used in the vignette to suggests and remove any that are not used. Please also add the library call to the code section of the vignette that utilizes these rather than just referencing the package in the text._
- Thank you for the helpful remarks, I changed the description file accordingly.

_NAMESPACE 
Please import the functions, classes, or packages that are being used with import(), importFrom(), importClassFrom(), etc.
In general you should not need to access these packages with the (::) . The (::) should be removed in the code and add the needed calls to the namespace. Everything that is listed in the import section of the description file should have some entry in the namespace._
-  Thank you for clarifying this point. I imported all functions accordingly.

_INST/DOC
This seems to have the same information/documentation as the vignettes. Please remove since duplicated._
- done

_VIGNETTE
CVE_tutorial 
It would be helpful to have a clarification on what is being displayed in the Shiny app. A description of the widgets and tabs that are produced and what it is showing? What widgets are user interactive? 
A more generic implementation of how the user could implement their data would also be helpful_
- This is a point well taken. I have added further description of the CVE functionality to the vignette.

_WGCNA_from_TCGA_RNAseq
As mentioned earlier please also include the library call in the code of section 4 to the GOstats_
- done

___

Best wishes,
Andreas

**Comment by andreasmock** [comment]
Dear Lori, @lshep 
did you already encounter additional issues with the package I can address?
Best regards,
Andreas

**Comment by lshep** [comment]
Some new additional comments: 

GENERAL: From the new section in the vignette, it is my understanding that this application only works with output from the Oncotator Annotation Tool.  This should be specified in the packages descriptions and made more clear. It is okay to have specialized tools but it should be stated. 

DESCRIPTION/NAMESPACE: It appears your shiny app requires RColorBrewer, gplots, plyr, and ggplot2 in order to display correctly.  These packages should be listed in Depends of the DESCRIPTION file and removed from Imports. They can also be removed in the NAMESPACE imports. 

DESCRIPTION:  where is impute used?  This should be removed if not used. 

MAN:  
openCVE.Rd:  add a \value section indicating that the shiny app is launched. 

WGCNAmelanoma_extension.Rd:  you included all the individual data files in WGCNAmelanoma_extension.RData object.  Could you also include a WGCNAmelanoma_extension.Rd file indicating these objects can be loaded by loading that data file. 

VIGNETTE: 
WGCNA_from_TCGA_RNAseq.Rmd
It is unclear to me what this documentation describes. Is this how you created the extension data you use in the package or does a user have to go through all these steps in order to use the shiny app? 
None of the code in this vigentte is evaluated, why?  We generally like code evaluated when generating the vignette. 
I can't run through the example in this vignette because the RNAseq object you utilize right away is not included with the package data and it is not clear how that is created.  

Thank you 
Lori

**Comment by andreasmock** [comment]
Dear Lori, @lshep,

thanks, this is most helpful!

1) I have added the description of the input file to the DESCRIPTION file.

2) I have updated the DESCRIPTION/NAMESPACE. It turns out, that CVE and its extension need all packages in “depends” to execute properly.

3) MAN: a \value section was added to openCVE.Rd

4) VIGNETTE: WGCNA_from_TCGA_RNAseq.Rmd
I understand that having vignettes that are not executable is not common in Bioconductor packages. This vignette was only thought to be a source of additional information for those interested in using WGCNA for RNAseq data. It is not the focus of the package and the manuscript and is not needed to use the Shiny app. We even thought about of excluding this tutorial, in order not to confuse the user of the package.
We did not supply the RNAseq object because (i) it is the exact RNAseq2 level 3 data from the TCGA data portal for cutaneous melanoma and I was not sure about the policy to redistribute TCGA data and (ii) it is with approx. 30 MB quite large. 

Best regards,
Andreas

**Comment by lshep** [comment]
Thank you for your updates.  Your package is looking good. Just a few other comments. 

R CODE: 
If you run the application with the extension data  
`openCVE(oncotator_example, sample_names='case study', extension='WGCNAmelanoma') `

When you click on `Melanoma WGCNA `  tab a Warning message comes up.  If this is possible to fix please fix it, if not please explain why (if it is a problem with a different program). This warning is repeated any time you click on that tab or change any of the widgets on that page. 
Example warning: 
Warning in rect(9, 5, 10, 5.7, add = TRUE, xpd = TRUE, col = "grey", border = "grey") :
  "add" is not a graphical parameter
Warning in rect(8.75, 2, 10.25, 8, add = TRUE) :
  "add" is not a graphical parameter


NAMESPACE:  
This is my fault from my last comment, please add the packages in depends of the DESCRIPTION file to the NAMESPACE as import()  


DESCRIPTION:  
Please update the R version requirement from 3.2.1 to 3.3 


MAN:  
Please add a WGCNAmelanoma_extension.Rd to indicate what is loaded with data(WGCNAmelanoma_extension). The individual man files for the objects are great! but there should be a man page for the this too to indicate where all those objects are come from. 

VIGNETTE: 
CVE_tutorial.Rmd:  Please add a table of contents 

WGCNA_from_TCGA_RNAseq.Rmd:  Thank you for clarifying in your last comment.  Two suggestions: 
a. At the very least could you please clarify at the beginning of the vignette that it is a proof of principal example and can't be run as listed.  I think it is good to still include this to show how someone would create the data. 
b. Consider exploring the Bioconductor experimental data packages for example data that can be freely loaded and used.  You can search the packages [here](http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData).  I'm not sure if it is appropriate for your application but some available software packages are ["pasilla"](http://bioconductor.org/packages/release/data/experiment/html/pasilla.html) and ["pasillaBamSubset"](http://bioconductor.org/packages/release/data/experiment/html/pasillaBamSubset.html) that have RNASeq data. Including this vignette as a runable example would be a great help to the bioconductor community, showing how to use existing data/data objects with your application.  

Thank you 
Lori

**Comment by andreasmock** [comment]
Dear Lori, @Ishep,

thanks again, I am very grateful for your help.

I have 
- fixed the Warning message in the Melanoma WGCNA tab
- updated the NAMESPACE
- changed the R version requirement
- added a WGCNAmelanoma_extension.Rd documentation

Regarding the vignette CVE_tutorial.Rmd
- Indeed, a great amount of work was put into a recent experimental data package summarising all TCGA data (RTCGA package). Unfortunately, the TCGA Data Portal is no longer operational and the data was moved to Genomic Data Commons. Hence, major changes are needed to account for this change in data structure. 
- As a consequence I abstained from using the RTCGA data, but I am very happy to update my vignette once the changes have been undertaken. 
- As suggested by you, I have clarified at the beginning of the vignette, that it can’t be run as listed  at the moment and only serves as a proof of principal example.

Best wishes,
Andreas

**Comment by lshep** [comment]
Thank you for making those changes. 
Please add import(RColorBrewer) to the NAMESPACE.  Once this is done and the new build completes, I will recommend your package be accepted. You should get svn instructions via email in the next couple of days. 
Thank you for all your time and effort.  
Lori

**Comment by andreasmock** [comment]
I added import(RColorBrewer),
Thank you gain for your great help and valuable suggestions!
Andreas

**Comment by modarzi** [comment]
Hi,
I install R version 3.4.4 and try to install "WGCNA_from_TCGA_RNAseq" package but in my RStudio console receive this warning:

Warning message:
package ‘WGCNA_from_TCGA_RNAseq’ is not available (for R version 3.4.4) 

I appreciate if you share your comment with me.
Best Regards,
Mohammad

**Comment by mtmorgan** [comment]
@modarzi ask support questions on https://support.bioconductor.org. Provide enough detail for your question to be reproduced. 'WGCNA_from_TCGA_RNAseq' does not seem like a package name.
