### ISSUE TITLE
spaSim

### ISSUE THREAD

**Issue by fuerzhou** [Bioconductor/Contributions#2605]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/TrigosTeam/spaSim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Please remove or qualify carefully
```
# install from GitHub
install.packages("devtools")
devtools::install_github("TrigosTeam/spaSim", ref = "dev")
```

**Comment by fuerzhou** [comment]
Thank you for the reminder. I have fixed it.

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

ok

## NAMESPACE 

ok

## NEWS

ok - make sure it can be parsed by `utils::news()`.

## R 

- Indent your R code by 4 spaces. https://bioconductor.org/developers/how-to/coding-style/ - follow this.

- Explain the default arguments: https://github.com/TrigosTeam/spaSim/blob/09b9ff57000e54161cfbb9201177edd778a18c5a/R/multiple_images_with_immune_rings.R#L59 , not just in this function but throughout your codebase.

- Lines 50, 51 are not needed, https://github.com/TrigosTeam/spaSim/blob/09b9ff57000e54161cfbb9201177edd778a18c5a/R/simulate_background_cells.R#L50. Please make sure there is 'space' efficiency in your code, don't assign variables for no reason. 

- Is the goal of a function like this to have the user run it without any user parameters given as input? The number of parameters in this function is not very helpful. There are also no validity checks for the parameters. It is very likely to break unless they know exactly what to input. 

https://github.com/TrigosTeam/spaSim/blob/09b9ff57000e54161cfbb9201177edd778a18c5a/R/simulate_background_cells.R#L50

There is a risk of failure if there are no validity checks for the parameters, please include them. And this risk increases as the number of parameters increase.

- Why is the `sysdata.rda` file in the `R/` folder? Whatever you want to install with the package should go in the `inst/extdata` section.

## inst

- Include data here instead of the `R/` directory

## man

ok, try to include more details on the parameters. 

## tests 

ok

## vignettes 

ok

**Comment by fuerzhou** [comment]
Thank you @nturaga for the comments. Much appreciated.

### The following issues have been solved :

- [X] NEWS can be parsed by `utils::news()` after installation. 
- [X] R files are now indented by 4 spaces.
- [X] Deleted unnecessary codes.
- [X] Added validity checks for parameters. 

### There are two things that I would like to discuss with you:

- On the number of parameters and the default arguments:
We note that this package generates simulated data based on user parameters, rather than analysing external datasets. Hence, most functions require more parameters than functions from a regular package. For functions where there is a larger number of parameters, we set the default arguments to generate a typical simulation, giving users an example of what can be obtained with the function. We also have`@examples` in the manual which include the code to generate the same results as that with the default parameters. We believe this set up will improve user experience. We have added clarifications in the `@description` of those functions - "The default values for the arguments give an example which enables an automatic simulation without the specification of any argument." 

-  On the internal data:
The `sysdata.rda` file is the internal data that is not visible to the users. I followed the guidance in this book [data](https://r-pkgs.org/data.html#:~:text=If%20you%20want%20to%20store%20parsed%20data%2C%20but%20not%20make%20it%20available%20to%20the%20user%2C%20put%20it%20in%20R/sysdata.rda.%20This%20is%20the%20best%20place%20to%20put%20data%20that%20your%20functions%20need). The function I used to generate the data is `usethis::use_data()` which automatically generates the data in `R/` folder. Could you please give more instructions on why and how the internal data should be stored in `inst/extdata`?

**Comment by fuerzhou** [comment]
I tried pushing the updated version 0.99.1 to Bioconductor. However, I encountered an error:

```
$ git push upstream main
The authenticity of host 'git.bioconductor.org (34.192.48.227)' can't be established.
ED25519 key fingerprint is SHA256:h60zj69etEaWmD4S9vpI3KFRBvPlodTMxZjYpGh4ZjQ.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git.bioconductor.org' (ED25519) to the list of known hosts.
Enumerating objects: 88, done.
Counting objects: 100% (88/88), done.
Delta compression using up to 8 threads
Compressing objects: 100% (57/57), done.
Writing objects: 100% (57/57), 22.82 KiB | 417.00 KiB/s, done.
Total 57 (delta 45), reused 0 (delta 0), pack-reused 0
remote: FATAL: W refs/heads/main packages/spaSim fuerzhou DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/spaSim.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/spaSim.git'
```

Looks like the issue was not the SSH. It might have something to do with hooks on remote. Could you please help me with this? Thank you!

**Comment by lshep** [comment]
Multiple issues: 
1.  As mentioned in a previous message, you need to activate your git credentials account and add ssh keys to the account for access. https://git.bioconductor.org/BiocCredentials
2.  There is no main branch on bioconductor.  Bioconductor currently uses master. See http://contributions.bioconductor.org/git-version-control.html#new-package-workflow  particularly the note under `#5` of the given new package workflow git .

**Comment by fuerzhou** [comment]
@lshep Thank you very much for the advice. I have now pushed the new version to Bioconductor.

**Comment by nturaga** [comment]
# Review 2

- Remove ORCID id if not available, https://github.com/TrigosTeam/spaSim/blob/3afc583d5d41cfb3e25202cc4fff7114a54ab957/DESCRIPTION#L9

- Please check the latest build report https://bioconductor.org/spb_reports/spaSim_buildreport_20220603124633.html and fix as many of the simple "NOTE" issues as possible. 

Otherwise, it looks good to me. As soon as the build finishes, I'll accept it. Please make the change above.

**Comment by fuerzhou** [comment]
@nturaga Thank you for the update! I have added the ORCID id. 

Meanwhile, we are thinking about updating the main data object from `SingleCellExperiment` to `SpatialExperiment` as `SpatialExperiment` is the standard class for spatial data on Bioconductor. The other package that we have submitted, `SPIAT`, was suggested to do the same update. This will not take long, as `SpatialExperiment` is an extension of `SingleCellExperiment`. We would appreciate your comments on this!

**Comment by lshep** [comment]
SpatialExperiment is probably appropriate modification.

**Comment by nturaga** [comment]
Hi @fuerzhou 

Let me know when you have switched the object class, and i'll take a look again (please issue a new build report).

**Comment by fuerzhou** [comment]
@nturaga We have updated the package and the builds are successful. There are several notes that we could not resolve. 

1. Could not set LazyData to false - if set to false, our external data can not be accessed by the user.
2. NOTE: Consider multiples of 4 spaces for line indents; 465 lines (13%) are not.  I have tried my best to change the indentation generated from Roxygen2, but they can not be changed manually.
3. NOTE: Consider shorter lines; NOTE: The recommended function length is 50 lines or less. These two notes are related to each other and I have tried to reduce them.
4. NOTE: Avoid using '=' for assignment and use '<-' instead. - I checked all the files and there shouldn't be any. Do you have any suggestions on how to find out where the issue is?

Please let me know if we should do any further changes. Thank you!

**Comment by fuerzhou** [comment]
> @nturaga We have updated the package and the builds are successful. There are several notes that we could not resolve.
> 
> 1. Could not set LazyData to false - if set to false, our external data can not be accessed by the user.
> 2. NOTE: Consider multiples of 4 spaces for line indents; 465 lines (13%) are not.  I have tried my best to change the indentation generated from Roxygen2, but they can not be changed manually.
> 3. NOTE: Consider shorter lines; NOTE: The recommended function length is 50 lines or less. These two notes are related to each other and I have tried to reduce them.
> 4. NOTE: Avoid using '=' for assignment and use '<-' instead. - I checked all the files and there shouldn't be any. Do you have any suggestions on how to find out where the issue is?
> 
> Please let me know if we should do any further changes. Thank you!

I have deleted the workflow file from the repo.

**Comment by fuerzhou** [comment]
Thank you @nturaga @vjcitn @lshep for all your help!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fuerzhou.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spaSim")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spaSim

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
