### ISSUE TITLE
twoddpcr

### ISSUE THREAD

**Issue by idno0001** [Bioconductor/Contributions#261]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CRUKMI-ComputationalBiology/twoddpcr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
This seems to be a very well thought-out package using many advanced
programming concepts; congratulations.

DESCRIPTION

- it looks like there should be one or more new biocViews term added
  to appropriately characterize this package. Please respond by
  suggesting where in the hierarchy
  (http://bioconductor.org/packages/devel) these terms should be
  added, and incorporate them in your DESCRIPTION file.
- The title could be more descriptive of what the package does;
  currently it seems to promise to do everyhng related to 2-D droplet
  digital PCR.
- The License: field should indicate GPL-3, rather than `file
  LICENSE`; the LICENSE file itself can be included or not as the
  author sees fit (it is distributed with base R, so redundant).

NAMESPACE

- When the number of imports from a package becomes substantial, it
  often seems more appropriate, robust, and consistent with R coding
  practice to simply import the entire package; the shiny package
  seems to be an example of this.

vignettes

- Generally, the vignette looks great, congratulations!
- The installation instructions should be replaced with those
  appropriate for installation once accepted to Biocondcutor, i.e.,
  
        source("https://bioconductor.org/biocLite.R")
        biocLite("twoddpcr")

- The code chunk to install the package should be marked `eval =
  FALSE`, otherwise running the vignette code (which requires that the
  package is already installed) will install the package again!
- It is customary to include a final vignette chunk with the command
  and output `sessionInfo()`, so that the reader of the vignette can
  debug installation issues or compare the version of their package
  with the version of the package used in the vignette they are
  reading.
- Consider using the [BiocStyle][] package, for consistent
  Biocondcutor formatting.
  
[BiocStyle]: https://bioconductor.org/packages/BiocStyle

R

- (Optional) Consider more compact _R_ coding, e.g., replacing

          setMethod(f="getPlateCentres",
            signature="ddpcrPlate",
            def=function(theObject, cMethod)
            {
              return(lapply(getWells(theObject),
                            function(w)
                            {
                              getCentres(w, cMethod)
                            }
                            ))
            }
          )
          
  with 
  
        setMethod("getPlateCentres", "ddpcrPlate", function(theObject, cMethod) {
            lapply(getWells(theObject), getCentres, cMethod)
        })

  This: (1) does not use `return()`; (2) does not create an
  unnecessary anonymous function during `lapply()`; (3) does not use
  named arguments in signatures.
- Use of `sapply()` can be problematic for robust code, because it
  does not return a consistent type, e.g,. `sapply(1:2, sqrt)` returns
  a numeric vector, but `sapply(integer(0), sqrt)` returns a list. Use
  `vapply()` instead. 
- (clusterStats.R::getClassMeans specifically, but throughout the
  code): avoid nested iterations (sapply, apply); these are likely to
  be highly inefficient. Superficially, this looks like `colMeans()`
  on `droplets`, followed by manipulation of the mean vector.
- It looks like class `ddpcrPlate` is a list where all elements are
  `ddpcrWell`. Reuse the `S4Vectors::SimpleList` class instead. Avoid
  use of the 'native' generator function returned by `setClass()`,
  opting for a simple constructor that separates user interface from
  implementation (e.g., slot name) details.

        .ddpcrPlate = setClass("ddpcrPlate",
            contains="SimpleList",
            prototype=c(elementType="ddpcrWell")
        )
        
        ddpcrPlate = function(...) {
            .ddpcrPlate(listData=list(...))
        }
        
        
- A simple constructor also provides an appropriate place for defining
  `initialize`-like functionality; `initialize` methods are
  notoriously difficult to get correct, because they must serve as a
  null constructor, a copy constructor, and a standard constructor;
  for instance, your method (e.g., ddpcrPlate.R:951) is not a copy
  constructor and fails when a derived class is introduced.
- (Optional) The `setWell()` / `getWells()` formulation is somehow a
  carryover from other object systems with reference-based
  semantics. Instead, use standard _R_ paradigms `wells(x)`, `wells(x)
  <- value`, where the latter is implemented as
  
        setGeneric("wells<-", 
            function(x, ..., value) standardGeneric("wells<-")
        )
        setReplaceMethod("wells", c("ddpcrPlate", "list"),
            function(x, ..., value) {
                ## like setWells,ddpcrPlate-method
            }
        )

- I do not recommend introducing synonyms for common _R_ concepts, for
  instance, `ddpcrPlate` is a list, and `numWells()` is the length of
  the list. So simply use `length()`. Likewise, use `names<-` rather
  than `setWellNames()`, etc. This is beneficial to your user (they do
  not need to learn your specialized vocabulary) and beneficial to you
  (you do not need to re-implement functionality that has been
  established for a very long time). These types of changes will
  greatly reduce your code base, and this might initially be hard to
  accept, but in the end it means that you can focus on more
  interesting aspects of coding and your particular domain.
- Avoid unnecessary 'cyclomatic complexity', where your code branches
  to handle different cases of unclear merit (e.g., `bindAll`,
  ddpcrPlate.R:745). Each conditional doubles the cognitive burden
  required to understand your code, doubles the opportunities for
  bugs, and doubles the cost of maintaining your code.
- Never use direct slot access (e.g., ddpcrPlate.R:728,
  `theObject@wells`) in the body of your code. Instead, define and use
  accessor functions (these do not have to be exported from the package
  namespace) that isolate interface from implementation details.
- Superficially, it seems (e.g., ddpcrPlate.R:886) that you have
  implemented a 'list-of-classes' rather than a 'class-of-vectors',
  i.e., one would rather a class where basic operations are vectorized
  (a vector of classification methods, perhaps with a 'partitioning'
  that defines the element to which a classification method belongs)
  rather than iterative (a list of objects, each of which has a
  classification method).
- (Optional) for highly derived concepts, e.g., `getDroplets()`, there
  is little value in providing a generic and method. Start with a
  plain-old-function (`droplets()`), being prepared to introduce the
  generic + method if alternative `droplets()` methods become
  necessary.
- The use of `capture.output()` in the `show,ddpcrWell-method()` is
  very unusual, and implies that computatable information is being
  printed to the screen rather than returned from a function. The
  function should be modified to return a value that can be computed
  on directly.
- (mahRain.R:162) I don't understand why an `sapply()` is used; it
  seesms one wants something like

        n = length(ddpcr$classes)
        setNames(rep(maxDistances, n), names(ddpcr$classes))
- (e.g., relabelClasses.R:97) avoid `1:nrow(distance)`, which has
  unexepcted results when `nrow(distnace) == 0`; use
  `seq_len(nrow(distance))` instead.
- (e.g., relabelClasses.R:96) avoid 'copy-and-append', where `labels`
  is copied each iteration. Instead, use 'preallocate-and-fill'
  (`labels=vector("list", nrow(distances); ...; labels[[i]] = ` or
  simply `lapply()`.
  
man

- (exportTable.R:25) `\dontrun{}` chunks are very dangerous, because
  they are rapidly subject to bit-rot such that the example code no
  longer matches the implementation. Use `tempdir()` or `tempfile()`
  to write output during package build and check and when the user
  invokes `example()` to write to a location that will not interfere
  with the user's own files.
- (exportTable.R:259) The `setwd()` after `stop()` will not be
  evaluated. If changing directory, use the approach
  
        owd <- setwd(tmpDir)
        on.exit(setwd(owd))

**Comment by idno0001** [comment]
Thank you for taking the time to review our package. Your comments are greatly appreciated and I have learned a lot in the process.

I have made most of the suggested changes with comments below. Before pushing a version bump, should I wait for the new biocView to be added?

Thanks

> DESCRIPTION
>
> - [x] it looks like there should be one or more new biocViews term added
>     to appropriately characterize this package. Please respond by
>     suggesting where in the hierarchy
>     (http://bioconductor.org/packages/devel) these terms should be
>     added, and incorporate them in your DESCRIPTION file.

 I have added the "ddPCR" biocView, which should be added below _Software - Technology_.

> - [x] The title could be more descriptive of what the package does;
>     currently it seems to promise to do everyhng related to 2-D droplet
>     digital PCR.
> - [x] The License: field should indicate GPL-3, rather than file LICENSE; the LICENSE file itself can be included or not as the
>     author sees fit (it is distributed with base R, so redundant).
> 
> NAMESPACE
> 
> - [x] When the number of imports from a package becomes substantial, it
>     often seems more appropriate, robust, and consistent with R coding
>     practice to simply import the entire package; the shiny package
>     seems to be an example of this.
>
> vignettes
>
> - [x] Generally, the vignette looks great, congratulations!

Thank you!

> - [x] The installation instructions should be replaced with those
>     appropriate for installation once accepted to Biocondcutor, i.e.,
> 
>       source("https://bioconductor.org/biocLite.R")
>       biocLite("twoddpcr")

This has been added as the main (i.e. first) option. I have left the GitHub and "from source" installation instructions as alternatives; let me know if you'd prefer that I remove them.

> - [x] The code chunk to install the package should be marked eval = FALSE, otherwise running the vignette code (which requires that the
>     package is already installed) will install the package again!
> 
> - [x] It is customary to include a final vignette chunk with the command
>     and output sessionInfo(), so that the reader of the vignette can
>     debug installation issues or compare the version of their package
>     with the version of the package used in the vignette they are
>     reading.
> 
> - [x] Consider using the BiocStyle package, for consistent
>     Biocondcutor formatting.
>
> R
>
> - [x] (Optional) Consider more compact R coding, e.g., replacing
> 
>         setMethod(f="getPlateCentres",
>           signature="ddpcrPlate",
>           def=function(theObject, cMethod)
>           {
>             return(lapply(getWells(theObject),
>                           function(w)
>                           {
>                             getCentres(w, cMethod)
>                           }
>                           ))
>           }
>         )
> 
>     with
> 
>       setMethod("getPlateCentres", "ddpcrPlate", function(theObject, cMethod) {
>           lapply(getWells(theObject), getCentres, cMethod)
>       })
> 
>     This: (1) does not use return(); (2) does not create an
>     unnecessary anonymous function during lapply(); (3) does not use
>     named arguments in signatures.

I have done this where possible, but have left some things where it makes more sense, e.g. retaining `return` statements in some places to improve readability.

> - [x] Use of sapply() can be problematic for robust code, because it
>     does not return a consistent type, e.g,. sapply(1:2, sqrt) returns
>     a numeric vector, but sapply(integer(0), sqrt) returns a list. Use
>     vapply() instead.
>
> - [x] (clusterStats.R::getClassMeans specifically, but throughout the
>     code): avoid nested iterations (sapply, apply); these are likely to
>     be highly inefficient. Superficially, this looks like colMeans()
>     on droplets, followed by manipulation of the mean vector.
>
> - [x] It looks like class ddpcrPlate is a list where all elements are
>     ddpcrWell. Reuse the S4Vectors::SimpleList class instead. Avoid
>     use of the 'native' generator function returned by setClass(),
>     opting for a simple constructor that separates user interface from
>     implementation (e.g., slot name) details.
> 
>       .ddpcrPlate = setClass("ddpcrPlate",
>           contains="SimpleList",
>           prototype=c(elementType="ddpcrWell")
>       )
>       
>       ddpcrPlate = function(...) {
>           .ddpcrPlate(listData=list(...))
>       }
> 
> - [x] A simple constructor also provides an appropriate place for defining
>     initialize-like functionality; initialize methods are
>     notoriously difficult to get correct, because they must serve as a
>     null constructor, a copy constructor, and a standard constructor;
>     for instance, your method (e.g., ddpcrPlate.R:951) is not a copy
>     constructor and fails when a derived class is introduced.
> 
> - [x] (Optional) The setWell() / getWells() formulation is somehow a
>     carryover from other object systems with reference-based
>     semantics. Instead, use standard R paradigms wells(x), wells(x) <- value, where the latter is implemented as
> 
>       setGeneric("wells<-", 
>           function(x, ..., value) standardGeneric("wells<-")
>       )
>       setReplaceMethod("wells", c("ddpcrPlate", "list"),
>           function(x, ..., value) {
>               ## like setWells,ddpcrPlate-method
>           }
>       )
>
> - [x] I do not recommend introducing synonyms for common R concepts, for
>     instance, ddpcrPlate is a list, and numWells() is the length of
>     the list. So simply use length(). Likewise, use names<- rather
>     than setWellNames(), etc. This is beneficial to your user (they do
>     not need to learn your specialized vocabulary) and beneficial to you
>     (you do not need to re-implement functionality that has been
>     established for a very long time). These types of changes will
>     greatly reduce your code base, and this might initially be hard to
>     accept, but in the end it means that you can focus on more
>     interesting aspects of coding and your particular domain.

This has been done, but I have left the `numDroplets` method because it is more clear that way.

> - [x] Avoid unnecessary 'cyclomatic complexity', where your code branches
>     to handle different cases of unclear merit (e.g., bindAll,
>     ddpcrPlate.R:745). Each conditional doubles the cognitive burden
>     required to understand your code, doubles the opportunities for:
>     bugs, and doubles the cost of maintaining your code.

I have done this where possible, e.g. I have added new signatures for the `ddpcrWell` and `ddpcrPlate` constructors to handle differing input types and the code feels much cleaner now.

> - [x] Never use direct slot access (e.g., ddpcrPlate.R:728,
>     theObject@wells) in the body of your code. Instead, define and use
>     accessor functions (these do not have to be exported from the package
>     namespace) that isolate interface from implementation details.
> 
> - [ ] Superficially, it seems (e.g., ddpcrPlate.R:886) that you have
>     implemented a 'list-of-classes' rather than a 'class-of-vectors',
>     i.e., one would rather a class where basic operations are vectorized
>     (a vector of classification methods, perhaps with a 'partitioning'
>     that defines the element to which a classification method belongs)
>     rather than iterative (a list of objects, each of which has a
>     classification method).

I understand your point. However, it makes more intuitive sense to implement `ddpcrPlate` as a list of `ddpcrWell` classes. My colleagues/acquaintances sometimes use the same ddPCR plate to analyse different things (e.g. checking for different mutations), and thus vectorising everything might not make sense.
 
> - [ ] (Optional) for highly derived concepts, e.g., getDroplets(), there
>     is little value in providing a generic and method. Start with a
>     plain-old-function (droplets()), being prepared to introduce the
>     generic + method if alternative droplets() methods become
>     necessary.

I decided against this because the generic and method allows us to perform a form of type-checking on the parameters. If I was to use a plain-old-function, I would need to include a few lines to do the type-checking. The pros and cons are minimal here, so I left things as they are. Please correct me if I am wrong here.
 
> - [x] The use of capture.output() in the show,ddpcrWell-method() is
>     very unusual, and implies that computatable information is being
>     printed to the screen rather than returned from a function. The
>     function should be modified to return a value that can be computed
>     on directly.
>
> - [x] (mahRain.R:162) I don't understand why an sapply() is used; it
>     seesms one wants something like
> 
>       n = length(ddpcr$classes)
>       setNames(rep(maxDistances, n), names(ddpcr$classes))
> 
> - [x] (e.g., relabelClasses.R:97) avoid 1:nrow(distance), which has
>     unexepcted results when nrow(distnace) == 0; use
>     seq_len(nrow(distance)) instead.
> 
> - [x] (e.g., relabelClasses.R:96) avoid 'copy-and-append', where labels
>     is copied each iteration. Instead, use 'preallocate-and-fill'
>     (labels=vector("list", nrow(distances); ...; labels[[i]] = or
>     simply lapply().
> 
> man
> 
> - [x] (exportTable.R:25) \dontrun{} chunks are very dangerous, because
>     they are rapidly subject to bit-rot such that the example code no
>     longer matches the implementation. Use tempdir() or tempfile()
>     to write output during package build and check and when the user
>     invokes example() to write to a location that will not interfere
>     with the user's own files.
> 
> - [x] (exportTable.R:259) The setwd() after stop() will not be
>     evaluated. If changing directory, use the approach
> 
>       owd <- setwd(tmpDir)
>       on.exit(setwd(owd))
> 
>

**Comment by mtmorgan** [comment]
Thanks for your conscientious update. Please provide a version bump and ignore any problems from unknown biocViews.

**Comment by mtmorgan** [comment]
Thanks for your efforts, I've taken a quick look at your revisions and am pleased to accept your package to Bioconductor. It will be added to our svn repository and nightly builds, with additional information sent via email in the next several days.

**Comment by idno0001** [comment]
Thank you, I really appreciate the time you've spent on reviewing our package.
