### ISSUE TITLE
stJoincount

### ISSUE THREAD

**Issue by Nina-Song** [Bioconductor/Contributions#2610]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nina-Song/stJoincount

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Do you check your package before submitting, on a "clean" system?  Vignette:
```
```{r setup, message = FALSE, warning=FALSE}
library(joincount)
```
That doesn't exist.

**Comment by Nina-Song** [comment]
Dear @vjcitn ,

My apology for the mistake, "joincount" is the package that I built for testing. I restart the R session and now it passed the R cmd check.

During the R cmd check, there is one warning that I could not fix for a while.
checking data for non-ASCII characters (1.3s)
     Error loading dataset 'humanBC':
      Error in .requirePackage(package) : 
       unable to find required package 'Seurat'
     
     The dataset(s) may use package(s) not declared in Depends/Imports.

I have tried putting "Seurat" in either Depends or imports, but none of them get this warning sign fixed. "#' @ import Seurat" is also present at the beginning of each function that needs this package.

Thanks in advance!

Nina

**Comment by vjcitn** [comment]
Thanks for your reply.  I will pass the package for review.  But this should not be in the vignette: 
```
bfc <- BiocFileCache::BiocFileCache()
bc.url <-
  paste0(
    "https://cf.10xgenomics.com/samples/spatial-exp/",
    "1.1.0/V1_Breast_Cancer_Block_A_Section_1/",
    c(
      "V1_Breast_Cancer_Block_A_Section_1_filtered_feature_bc_matrix.tar.gz",
      "V1_Breast_Cancer_Block_A_Section_1_spatial.tar.gz",
      "V1_Breast_Cancer_Block_A_Section_1_analysis.tar.gz"
    )
  )


h5.url <-
  paste0(
    "https://cf.10xgenomics.com/samples/spatial-exp/",
    "1.1.0/V1_Breast_Cancer_Block_A_Section_1/",
    "V1_Breast_Cancer_Block_A_Section_1_filtered_feature_bc_matrix.h5"
  )
```
We have no guarantees that 10xgenomics will maintain this.  The data should be added to ExperimentHub.  @lshep

**Comment by lshep** [comment]
@vjcitn It's up for debate.  Since they are caching and the 10xgenomics site seems to be well maintained public entity, I'm inclined to leave as is since they have implemented the caching mechanism.  Just make sure that the caching is set up/working properly.   But @vjcitn will have the final say in this matter.

**Comment by vjcitn** [comment]
OK.  Ignore my comment.  Thanks!

**Comment by lazappi** [comment]
Hi @Nina-Song

Thanks for submitting **stJoincount** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :rotating_light: Please address as many of the warnings and notes from `BiocCheck::BiocCheck()` in the build report as possible

## DESCRIPTION file

- [ ] :warning: It is recommended to add ORCiDs to the `Authors@R` field
- [ ] :rotating_light: Bioconductor packages should use the Bioconductor **{rhdf5}** package rather than the CRAN **{hdf5r}** package
- [ ] :green_circle: You may want to add `Software` to `BiocViews`
- [ ] :warning: It is recommended to add a `BugReports` field, this is usually the URL for your GitHub issues page or the Bioconductor support forum
- [ ] :warning: It is recommended to add a `URL` field, this is usually the URL for your GitHub repository or another package website

## NAMESPACE file

- [ ] :rotating_light: Please selectively import functions using `importFrom` instead of *import all* with `import`

## The NEWS file

- [ ] :rotating_light: Please check the format of your NEWS file is correct, [see here](https://r-pkgs.org/release.html#news) for more info

## Package data

- [ ] :rotating_light: Internal data in the `inst/extdata/` directory should be documented in `inst/script`
- [ ] :rotating_light: `BiocFileCache` should be used for downloaded data. I think you have done this for most things but not the `.h5` file in the vignette.
- [ ] :warning: If you are using the data in your examples it may be better to export it

## Documentation

- [ ] :green_circle: I noticed typos in some places, you can check for these using the **{spellcheck}** package or `usethis::use_spellcheck()`

### Vignette

- [ ] :rotating_light: Vignettes should use the `BiocStyle` package for formatting
- [ ] :rotating_light: Please add a table of contents to the vignette
- [ ] :rotating_light: Please add an *Introduction* section
- [ ] :rotating_light: Please add an *Installation* section, this should include the Bioconductor installation instructions with `eval = FALSE`
- [ ] :rotating_light: The vignette should be more than just a list of functions. It should describe the functionality of the package and demonstrate how they can be used together to perform a task. Please add more detail.
- [ ] :rotating_light: In general vignettes should use `warnings = TRUE` so that the output is as close as possible to what users will see when they run the code.

### Man pages

- [ ] :rotating_light: In general your function documentation is very brief, please add more detail about what the functions do
- [ ] :warning: It is recommended to add a package man page

## Unit tests

- [ ] :rotating_light: Please add unit tests to the package. These should cover all exported functions.

## Code

### R

- [ ] :rotating_light: Please use `vapply` instead of `sapply`
- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :rotating_light: Please access data in objects using getter or setter methods, not directly with `@` or `slot()`
- [ ] :warning: Check you are consistent in using `<-` rather than `=`, I think I noticed some `=` in the vignette
- [ ] :rotating_light: Please use`message()`, `warning()`, `stop()` instead of `cat()` or `print()`
- [ ] :rotating_light: The **{Seurat}** package is not part of Bioconductor. While it is ok to support `Seurat` objects your package should also support equivalent Bioconductor objects, in this case probably `SpatialExperiment` or one of the classes it inherits from (`SingleCellExperiment`/`SummarizedExperiment`)
- [ ] :rotating_light: The documentation for function arguments is brief, please expand this
- [ ] :warning: Consider adding validity checks for function arguments
- [ ] :warning: Please check that all your `for` loops are necessary
- [ ] :warning: Please remove any commented code that is not used

**Comment by Nina-Song** [comment]
Hi @lazappi ,

Thanks a lot for your feedback and these valuable comments. I will make adjustments as soon as possible.

I am wondering if there is a deadline for developers to make changes before getting accepted?

Thanks again for your help. @lazappi 

Sincerely,
Nina

**Comment by lazappi** [comment]
You can find the release schedule here https://bioconductor.org/developers/release-schedule/. You may have just missed the deadline for acceptance already but @Bioconductor/core can confirm.

**Comment by lshep** [comment]
@Nina-Song May we expect updates soon? We like to see progress in a 3-4 week time frame to keep the review process moving?

**Comment by Nina-Song** [comment]
Hi @lshep ,

Thank you for following up! I am working on those issues, and should have them down by this week. I will keep you posted.

Thanks again!

Nina

**Comment by Nina-Song** [comment]
Hi @lazappi,

My apology for the delay. The majority of the comments have been addressed, there are some minor questions that remained:

- The package is built based on the Seurat object. The majority of functions use the Seurat objects as the input. If we would like to support the SpatialExperiment object, does it refers to writing separate functions which do the same thing but use the SpatialExperiment object as the input?

- While defining a vignette is to demonstrate how users can be used together to perform a task, should we only present and explain those commands in the main workflow?

Thanks for your help!

Nina

**Comment by lazappi** [comment]
> * The package is built based on the Seurat object. The majority of functions use the Seurat objects as the input. If we would like to support the SpatialExperiment object, does it refers to writing separate functions which do the same thing but use the SpatialExperiment object as the input?

Yes, but you should avoid duplicating code. Usually the best approach is to have one function which extracts the required information from the supported objects and passes it to another function which does the internal processing. This can be done something like this:

```r
my_func <- function(x) {
	if (is(x, "Seurat") {
		x <- ...
	}

	if (is(x, "SpatialExperiment") {
		x <- ...
    }

	.my_func_internal(x)
}

.my_func_internal <- function(x) {
	# Do the processing here
}
```

It's a little bit more work but a better way is to S3 dispatch with a method for each of the supported objects and a default method which does the processing.

```r
 my_func <- function (x, ...) {
   UseMethod("my_func", x)
 }

my_func.Seurat <- function(x, ...) {
	x <- ...
	my_func(x, ...)
}

my_func.SpatialExperiment <- function(x, ...) {
	x <- ...
	my_func(x, ...)
}

my_func.default <- function(x, ...) {
	# Do the processing here
}
```

Hopefully that makes sense but let me know if it's not clear.

> * While defining a vignette is to demonstrate how users can be used together to perform a task, should we only present and explain those commands in the main workflow?

Yes, you don't need to cover every function or function argument but you should cover the main things. It's also useful to include things like how a plot should be interpreted or when a function argument should be used to how to choose a value for things that need to be set manually.

**Comment by lazappi** [comment]
Hi @Nina-Song. It looks like the build is running without any issue now which is great. Please comment with the changes you have made when you are ready for me to review the package again.

**Comment by Nina-Song** [comment]
Hi @lazappi,

Thank you so much for your last advice. The input format now has been changed to a CSV file, which won't affect all of the major analyses, as well as avoids using Seurat or SpatialExperiment objects (which could be quite large and unnecessarily time-consuming for this statistical analysis pipeline). Currently, I am working on adding unit tests for functions. Once this step gets done, the package will be ready to under review.

Thank you again for your advice and patience!

Best,
Nina

**Comment by Nina-Song** [comment]
Hi @lazappi, 

Thank you again for your patience and valuable advice! 
The following changes have been made in each category  - 

DESCRIPTION file
 🟢 Added Software to BiocViews
 🟢 Added a BugReports field and a URL field
 🟢 Added ORCiD

NAMESPACE file
 🟢 Selectively import functions using importFrom instead of import all with import

The NEWS file
 🟢 Changed the format of NEWS file

Package data
 🟢 Internal data in the inst/extdata/ directory has been documented in inst/script

Vignette
 🟢 Followed the BiocStyle package for formatting
 🟢 Added an Introduction section and  an Installation section
 🟢 Presented the workflow as well as the functionality of the package
 🟢 Set warnings = TRUE 

Unit tests
 🟢 Added unit tests to the package that cover all exported functions.

R code
 🟢 Majority of those issues have been addressed. 
 🔵 The input format  now has been changed to a CSV file, which won't affect all of the major analyses. Therefore, previous issues such as rhdf5, BiocFileCache, or using Seurat vs. SpatialExperiment objects were no longer there.

- For the part of "getter or setter methods", there was one @ access in the previous version of this package, clusterName@data@values. clusterName is a S4 Class RasterLayer. 
- After adding `setGeneric("getValues", function(x){standardGeneric("getValues")})` `setMethod("getValues", c(x = "RasterLayer"),function(x){return(x@data@values)})` , it gave an error "cannot add bindings to a locked environment". I am not sure if I understood the term of getter and setter correctly. 

Thank you again!

Sincerely,
Nina

**Comment by lazappi** [comment]
>  🟢 Changed the format of NEWS file

You don't need the ```` ```markdown ```` code formatting. I'm also not sure what will happen with the ``` ------- ``` lines when this is read by the Bioconductor release system.

>  🟢 Internal data in the inst/extdata/ directory has been documented in inst/script

I couldn't find any documentation here. This should be a text/R file that describes where the data in `/inst/extdata` comes from, not an `.Rda` file.

There doesn't actually seem to be any data in `inst/extdata` anymore, just some PNG files? I'm not sure what changed here or what these images are for.

> 🟢 Added an Introduction section and an Installation section 

The installation section should go at the start of the vignette.

I also noticed a few typos. You can check for these using the **{spellcheck}** package.

> Unit tests 🟢 Added unit tests to the package that cover all exported functions.

I find the `checkInput()` functions in your tests a bit strange, particularly as the aren't reused, but I think it's fine if that works for you. 

> R code 🟢 Majority of those issues have been addressed.

- Some of your function argument documentation refers to a specific dataset, this should be more general and tell the user what they need to provide
- There are still some places where `1:...` is used, please replace these
- I noticed a few uses of `=` instead of `<-`, please check for these

> 🔵 The input format now has been changed to a CSV file, which won't affect all of the major analyses. Therefore, previous issues such as rhdf5, BiocFileCache, or using Seurat vs. SpatialExperiment objects were no longer there.

- I couldn't find any references to a CSV file, instead the input seems to be a `data.frame`
- There is no information about what this `data.frame` needs to contain, this should be clearly described in the function documentation and explained in the vignette
- The example data has clearly come from a Seurat object, if your package is now based around a simpler object I suggest cleaning this up a bit to make it a bit more generic and only contain the information you actually need
- While basing the package on a `data.frame` makes things simpler for you it makes it more difficult to use as the user can no longer provide objects they are likely to already have directly. If you don't want to add support for `SpatialExperiment`/`SummarizedExperiment`/`Seurat` as I suggested above then I think you should at least include sections in the vignette showing how to extract the relevant information from these objects. Without this information it is very difficult for users to know how to include your package in their existing workflows.

> * For the part of "getter or setter methods", there was one @ access in the previous version of this package, clusterName@data@values. clusterName is a S4 Class RasterLayer.
> * After adding `setGeneric("getValues", function(x){standardGeneric("getValues")})` `setMethod("getValues", c(x = "RasterLayer"),function(x){return(x@data@values)})` , it gave an error "cannot add bindings to a locked environment". I am not sure if I understood the term of getter and setter correctly.

If this object is defined in another package then you won't be able to add getter/setter functions yourself. In this case, if they aren't provided by the package authors then you have no choice but to use `@` or `slot()` (but if they are provided please use them).

**Comment by Nina-Song** [comment]
Hi @lazappi ,

Thank you again for your valuable feedback!
The following changes have been made:

- [ ] Changed the format of NEWS file
- [ ] Added text description of extdata in inst/script
- [ ] Reordered installation section and checked the spelling in the vignette
- [ ] Optimized R code (<- and 1:...)
- For the example data: 
1. [ ] Cleaned up the data format that now only contains important information
2. [ ] Added sections in the vignette showing how to extract the relevant information from Seurat/SpatialExperiment objects, and how to generate the same data.frame
3. [ ] Added a detailed explanation of this data.frame

Thank you again!

Sincerely,
Nina

**Comment by lazappi** [comment]
> * [ ]  Changed the format of NEWS file

I think there is still one `----------` line in there

> * [ ]  Added text description of extdata in inst/script

There is still some information missing here, mostly links to the source for the dataset (GEO, publication etc.). Ideally this would be an R script that shows where you got the data from and how it was processed.

> [ ]  Added sections in the vignette showing how to extract the relevant information from Seurat/SpatialExperiment objects, and how to generate the same data.frame

These sections should be evaluated, you may need to add more example data to make this possible. This code could also do with some more comments or explanation of the steps in the text (and I still think it would be better to let users supply a Seurat/SpatialExperiment directly)

**Comment by lazappi** [comment]
Hi @Nina-Song

Another follow up comment, sorry. Another reviewer noticed that the `data.frame` format is not documented in the function documentation. Each function parameter documentation should say that the input is a `data.frame` and what columns etc. it must have.

They also suggested that another solution to the object problem would be to write a preparation function that creates the `data.frame` from a `Seurat`/`SpatialExperiment`. Then the workflow for the user would be input object -> prepared `data.frame` -> analysis functions. We strongly feel that letting the user use standard objects as the input to your package without requiring manual manipulation would make the package much more useable and accessible (and therefore more likely to be used).

**Comment by Nina-Song** [comment]
Dear @lazappi ,

Thank you so much for your valuable suggestions and prompt follow-up comment, they are very helpful.

- For function parameter documentation: thanks for reminding me, I will change it to data.frame and add explanation for columns at the beginning of each function.

- For the second part, it is also what we are thinking about - to provide functions just like what has been shown in Vignette to let users directly use the function, instead of creating the data.frame by themselves. 

One thing we are not sure about is, whether could we create this data preparation function without showing an example (like dummy Seurat/SpatialExperiment objects) to this one, and still keep the current external data (the data.frame in /extdata) as the example data for the rest functions? Since if adding two more objects, even if they are 'dummy', they might be larger than 5 MB; and for the rest functions, they may not be necessary to run start very beginning. 

Thanks again for your time and looking forward to hearing back from you!

Sincerely,
Nina

**Comment by Nina-Song** [comment]
Dear @lazappi ,

Thank you so much for your valuable suggestions and prompt follow-up comment again!

As the last comment suggested, data preparation functions are added to make the workflow for the user from input object -> prepared data.frame -> analysis functions. Dummy examples for Seurat and SpatialExperiment objects are added to `extdata`. Each function parameter documentation now includes an explanation of the input `data.frame` requirements. 

Thanks again and please let me know if there is anything else needed. We are looking forward to hearing back from you!

Best,
Nina

**Comment by Nina-Song** [comment]
Hello @lazappi , 

Since today is the deadline for API changes, I just wanted to follow up on the review process. Thank you again for your help. 

Best,
Nina

**Comment by lshep** [comment]
@Nina-Song  the API deadline is mostly for package already accepted in Bioconductor. Since there is a lot of interdependent packages we encourage the API deadline to prevent last minute changes having a cascading effect to break packages dependent on it. You'll still have until the 26 to be accepted.

**Comment by lazappi** [comment]
> As the last comment suggested, data preparation functions are added to make the workflow for the user from input object -> prepared data.frame -> analysis functions.

Thank you for implementing these! From the vignette it seems like they work really well and make it much easier to use your package.

> Dummy examples for Seurat and SpatialExperiment objects are added to `extdata`.

Please document these in `inst/script`. As I mentioned previously, ideally there should be an R script for each dataset showing how it was obtained and processed to get the saved objects. At a minimum you should have a text description for each object, including links to where it originally came from and any associated citations.

> Each function parameter documentation now includes an explanation of the input `data.frame` requirements.

- Please check the parameter descriptions to make sure they are general enough. For example, I think in one it says the dataset has to be from breast cancer but (as far as I can tell) the data could be from any tissue.
- It can be helpful to link to related functions in the function documentation. For example the description for the `sampleInfo` parameter could say something like "as produced by the `dataPrepSeurat()`/`dataPrepSpE()` functions".
- It is useful to describe the type of the returned value (`vector`, `data.frame` etc.)
- Please check that the descriptions of the returned values are correct. For example I think the description for `customDict()` is from another function
- Some of your `man` pages are missing titles. This causes some weird formatting and the description to be displayed twice. Please check these.

Other:

- Check that you use all the imported functions. I think you import `Load10x_Spatial()` but it's not actually used for example.
- If you have functions that aren't meant to be used by the user you don't need to export them (`extentBuffer()` maybe?)

**Comment by Nina-Song** [comment]
Hi @lazappi ,

Thanks for your valuable feedback again.

- Documentations for `extdata` are added to `inst/script`, showing how to get and generate example data. Now all of the data are coming from a 10X genomics public data set, these links can be found in scripts as well.
- Parameter descriptions, return values and titles have been changed. Function documentation has been modified. 
- Unnecessary import has been removed. 
- For `extentBuffer`,  the export is kept since users might want to check how much the width and height have been extended before generating a raster layer.

Thank you for your time and please let me know if anything else is needed.

Nina

**Comment by lazappi** [comment]
Hi @Nina-Song 

I think I am happy with this now so that it makes it into the next release. There are still some things that I think could do with tidying up (for example the description for the `sampleInfo` parameter still specifically mention breast cancer) but they are minor and can be done as you maintain the package. Congratulations :tada:!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Nina-Song.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("stJoincount")`. The package 'landing page' will be created at

https://bioconductor.org/packages/stJoincount

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
