### ISSUE TITLE
qsvaR

### ISSUE THREAD

**Issue by joshstolz** [Bioconductor/Contributions#2612]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LieberInstitute/qsvaR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lcolladotor** [comment]
Hi @joshstolz,

Please ask your questions on a public forum or Slack channel so others can benefit from the answers, instead of emailing me. Louise @lahuuki can also help you for example.

Once you resolve the following:

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    Maintainer is registered at support site.
    * ERROR: Maintainer must add package name to Watched Tags on the
      support site; Edit your Support Site User Profile to add Watched
      Tags.
```

then you just need to bump the version number of `qsvaR` from 0.99.0 to 0.99.1 (aka, the `z` from `x.y.z`), then push it. The previous auto-comment by the @bioc-issue-bot includes a link to https://bioconductor.org/developers/how-to/git/new-package-workflow/ with the detailed instructions for synching your Git history from GitHub with the Git history from the Bioconductor repository.

Best,
Leo

**Comment by lshep** [comment]
The package looks in very good standards.   A few additional minor comments 

**Build Report**

- [ ] Please fix ERROR, Warning, Notes

**NAMESPACE**

- [ ] (Optional) If your package depends on SummarizedExperiment, It might be
  more beneficial to do a full import of the package instead of selective. Users
  will then have full functionality of SummarizedExperiment automatically with
  your package.

**README**

- [ ] Please ensure the installation instructions especially for the `.Rmd`
  version are in eval=FALSE sections

**data**

- [ ] Man page for transcripts.Rd seems to be missing a closing quote after
  standard `The "top1500" model is the same as the "standard model except the
  union of the top 1500 ge` ... 

Please let me know when you are ready for a review. 

Cheers,

**Comment by lcolladotor** [comment]
Thanks Lori! I'll meet with Josh later today and we'll go over your comments =) We'll add `SummarizedExperiment` to depends too.

Best,
Leo

**Comment by lshep** [comment]
@lcolladotor  it was already listed in description as depends which is why i recommended the full import in the namespace.

**Comment by lcolladotor** [comment]
ahh, thanks for the clarification! I misread your earlier comment, my bad!

**Comment by joshstolz** [comment]
Hi Lori,
Thanks for your feedback. We have updated the NAMESPACE and package to directly import SummarizedExperiment. We fixed the typo in the transcripts data description. Lastly in `README.Rmd` we set `eval=FALSE` for the installation instructions. I have added the qsvaR tag to my bioc support account and just subsribed to bioc-devel mailing list. Thanks again for your help.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/joshstolz.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("qsvaR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/qsvaR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by joshstolz** [comment]
Hi Lori,
Thanks so much again for reviewing my first bioconductor package. My github account already has a ssh key so we should be good to go.
