### ISSUE TITLE
GenomicInteractionNodes

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#2633]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/GenomicInteractionNodes

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
@LiNk-NY This is a update package for the old issue `GenomicInteractionHub`.

**Comment by LiNk-NY** [comment]
Hi JianHong, @JianHong

The updates look good and the package is passing `R CMD check`. 

Please make sure you run BiocCheck on the package and respond to any `ERROR`s. 

For instance,
```
* ERROR: Maintainer must add package name to Watched Tags on the
      support site; Edit your Support Site User Profile to add Watched
      Tags.
```

Thank you for your submission. Your package has been accepted. 

Best regards,
Marcel

**Comment by jianhong** [comment]
@LiNk-NY Thank you Marcel for the reminder. I add the watch tags 'GenomicInteractionNodes'.

**Comment by hpages** [comment]
@jianhong Hi Jianhong,

Please put a valid email address in the DESCRIPTION file. The current address:
``` 
Maintainer: Jianhong Ou <jianhong.ou@duke.com>
```
bounces back for me with the following error:
```
The response was:

550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces.
```

Many of the other packages you maintain have the same problem: **ATACseqQC**, **dagLogo**, **GeneNetworkBuilder**, **InPAS**, **motifStack**, **NADfinder**, **ribosomeProfilingQC**, and **trackViewer**. Please fix them all.

Thanks,
H.

**Comment by hpages** [comment]
I forgot to include **cleanUpdTSeq** and **enhancerHomologSearch** in the above list.

Because `jianhong.ou@duke.com` no longer works, you're not able to receive the automatic build failure notifications that are sent to this address when these packages have errors on the daily builds. It's also very likely that you used this address to subscribe to the bioc-devel mailing list in the past, so, unfortunately, you are no longer receiving important announcements sent on a regular basis to this list.

You'll need to update the email address used for your bioc-devel membership so that it matches the address you put in the DESCRIPTION file of the packages you maintain.

Thanks for your contribution to Bioconductor.

H.

**Comment by hpages** [comment]
Oh wait... now I realize that you're using two different "duke" addresses in your packages: `jianhong.ou@duke.com` in **ATACseqQC**, and `jianhong.ou@duke.edu` in most others.

Plus `ou.jianhong@gmail.com` in **ChIPpeakAnno**. That's three addresses for the same maintainer!

Also it seems that only `jianhong.ou@duke.com` is invalid, so it's only **ATACseqQC** that needs to be fixed (as I already communicated to you via email). As far as **GenomicInteractionNodes** is concerned, we're good to go.

Please fix **ATACseqQC** ASAP. I would also suggest that you use the same email address in all packages including in **ChIPpeakAnno**.

Thanks in advance and sorry for the confusion.

Best,
H.

**Comment by jianhong** [comment]
Hi Hervé,

Thank you for figure it out. I already the email address for ATACseqQC and ChIPpeakAnno.

Jianhong.

From: Hervé Pagès ***@***.***>
Date: Thursday, April 14, 2022 at 9:55 PM
To: Bioconductor/Contributions ***@***.***>
Cc: JIANHONG OU ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] GenomicInteractionNodes (Issue #2633)

Oh wait... now I realize that you're using two different "duke" addresses in your packages: ***@***.*** in ATACseqQC, and ***@***.*** in most others.

Plus ***@***.*** in ChIPpeakAnno. That's three addresses for the same maintainer!

Also it seems that only ***@***.*** is invalid, so it's only ATACseqQC that needs to be fixed (as I already communicated to you via email). As far as GenomicInteractionNodes is concerned, we're good to go.

Please fix ATACseqQC ASAP. I would also suggest that you use the same email address in all packages including in ChIPpeakAnno.

Thanks in advance and sorry for the confusion.

Best,
H.

**Comment by lshep** [comment]
Since this was a continuation and labels were changed manually,  this never got added to git with the new name -- I'm temporarily adding 'pre-check passed' back so I can use the auto scripts to auto add  and then will run the acceptance script on this package --

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jianhong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GenomicInteractionNodes")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GenomicInteractionNodes

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by hpages** [comment]
Thanks @lshep  and sorry that I messed around with labels.

@jianhong Thanks for fixing the email address in **ATACseqQC** and **ChIPpeakAnno**.

H.

**Comment by lshep** [comment]
@hpages  normally okay to do -- but in this case meant it didnt get into git.bioconductor.org with the right name.  But all taken care of now

**Comment by hpages** [comment]
@jianhong Are you sure you fixed the maintainer address in **ATACseqQC**? I still see `jianhong.ou@duke.com` there and the last commit is from Mar 30 (commit 3942cc17b). Maybe you forgot to push?

H.

**Comment by jianhong** [comment]
Opps. Just pushed.

Jianhong.

From: Hervé Pagès ***@***.***>
Date: Monday, April 18, 2022 at 8:21 PM
To: Bioconductor/Contributions ***@***.***>
Cc: JIANHONG OU ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] GenomicInteractionNodes (Issue #2633)

@jianhong<https://github.com/jianhong> Are you sure you fixed the maintainer address in ATACseqQC? I still see ***@***.*** there and the last commit is from Mar 30 (commit 3942cc17b). Maybe you forgot to push?

H.

**Comment by jianhong** [comment]
Thank you both @hpages @lshep for working on this.

Best!

Your sincerely,

Jianhong Ou
