### ISSUE TITLE
SpotClean

### ISSUE THREAD

**Issue by zijianni** [Bioconductor/Contributions#2637]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zijianni/SpotClean

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by drisso** [comment]
Dear @zijianni,

this looks like a really interesting and useful package! Thanks for contributing it to Bioconductor!

Looking at your code, I've noticed that you have a custom reader function for 10X Visium data and that you use SummarizedExperiment to store the data, storing the spatial information inside the `metadata` slot. Do I understand correctly?

I wanted to make sure that you are aware of the [SpatialExperiment](https://bioconductor.org/packages/release/bioc/html/SpatialExperiment.html) package, which is our attempt at extending SummarizedExperiment to store spatial transcriptomic data.

In that package, we provide the [read10xVisium function](https://github.com/drighelli/SpatialExperiment/blob/master/R/read10xVisium.R) to read 10X Visium data. This function returns a SpatialExperiment object that stores all the data that you need for your package (including the image). It shouldn't be much work to restructure the package to use SpatialExperiment and this will ensure interoperability between your and other spatial transcriptomic packages. For instance, it will allow users to visualize the data using the [ggspavis package](https://bioconductor.org/packages/release/bioc/html/ggspavis.html).

We are very open to engaging with the community and getting feedback by developers on the SpatialExperiment class.

Tagging @lmweber @HelenaLC @drighelli who are actually developing SpatialExperiment in case they have further input.

Anyway, thanks for considering this.

**Comment by zijianni** [comment]
Hi @drisso  et al,

Thanks for the message! I do know about `SpatialExperiment` and I'm happy to extend my package to directly apply SpotClean to `SpatialExperiment` class.

One thing I was hesitated using `read10xVisium()` is that it makes too strong assumption about the structure of the folders and files. In practice I'm not seeing a very consistent naming and structure of Visium output files, either due to different spaceranger versions or customized naming. As a result, I always have to manually arrange the files so that they can be recognized by `read10xVisium`.

I'm working on making our main function `SpotClean()` runnable on `SpatialExperiment` object constructed using `read10xVisium`. Happy to add more features if SpotClean is found useful by the community in the future.

**Comment by drighelli** [comment]
Hi @zijianni ,

thanks for taking into consideration using the `SpatialExperiment` class for your package.

Taking into account your comments on the `read10xVisium()` function, would you mind [opening a new issue in our repository](https://github.com/drighelli/SpatialExperiment/issues/new) describing the problems you encountered?
This would be very useful for us to further improve our class.

Thanks,
Dario

**Comment by zijianni** [comment]
> Hi @zijianni ,
> 
> thanks for taking into consideration using the `SpatialExperiment` class for your package.
> 
> Taking into account your comments on the `read10xVisium()` function, would you mind [opening a new issue in our repository](https://github.com/drighelli/SpatialExperiment/issues/new) describing the problems you encountered? This would be very useful for us to further improve our class.
> 
> Thanks, Dario

Hi @drighelli ,

Actually it's not the issue with `read10xVisium()`. `read10xVisium()` works very well for the output data directly from the Spaceranger pipeline, where we have the raw/filtered data matrix in folders as well as in HDF5 format, and the `spatial` folder containing tissue images etc. And this is how `read10xVisium()` has been designed for.

I've experienced tons of datasets where their data files are not organized as from Spaceranger output, so `read10xVisium()` cannot find the files it expects to see in the specified directory. Usually I have to load the count matrix and spatial information separately and then combine them together, which is more flexible but more complicated. That's why I have two functions `Read10xRaw()` and `Read10xSlide()` for loading data and `CreateSlide()` for merging into one object in my package.

Best,
Zijian

**Comment by zijianni** [comment]
Hi @lazappi ,

What's the expected timeline for reviewing this package? I'm leaving my current institution by the end of this month. It will be great if we can make some progress before that. Thanks!

Best,
Zijian

**Comment by lazappi** [comment]
Hi @zijianni 

Sorry I was on leave last week and I wasn't quite able to get to this before I left. I will try to find time this week.

**Comment by lazappi** [comment]
Hi @zijianni

Thanks for submitting **SpotClean** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :rotating_light: Please address as many of the `BiocCheck` notes in the build report as possible

## DESCRIPTION file

- [ ] :rotating_light: Please update the depended R version to 4.2
- [ ] :rotating_light: You have C++11 listed in `SystemRequirements` but I couldn't see any C++ code. Please remove this if it isn't needed.

## NAMESPACE file

- [ ] :rotating_light: Please use `lowerCamelCase` for function names, `UpperCamelCase` is reserved for objects

## Documentation

### Vignette

- [ ] :rotating_light: Please add a table of contents to the vignette
- [ ] :rotating_light: All code chunks in the vignette should be executed
- [ ] :rotating_light: Please includes a motivation for submitting the package to Bioconductor in the _Introduction_ section
- [ ] :rotating_light: Please mention related or alternative packages in the _Introduction_ section

### Man pages

- [ ] :green_circle: It is recommended to add a package man page
- [ ] :green_circle: Rather than using comments you can use Roxygen tags to document internal functions and mark them as internal

## Code

### R

- [ ] :warning: It is recommended to test that function arguments are valid in exported functions
- [ ] :green_circle: Please check the advice for [including **ggplot2** in packages](https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html)

**Comment by zijianni** [comment]
Hi @lazappi 
Thanks for your careful review of my package! Please see below my point-by-point response. I’ve addressed your concerns to the best of my ability. Let me know if anything is unclear. Further suggestions are definitely welcome.

> Hi @zijianni
> 
> Thanks for submitting **SpotClean** 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.
> 
> Luke
> 
> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [x]  🚨 Please address as many of the `BiocCheck` notes in the build report as possible

I’ve addressed as many of the `BiocCheck` notes as I can. 

For the remaining notes: 
- There is no runnable example in `convert_to_seurat.R` since this function requires external image-related files (the sizes of which can be large). Since this is not a major function in my package, I don't think it worths sacrificing the size of the packge only to make this single example runnable. Instead, I’m instructing users to correctly specify the path to image-related files by themselves.
- Lines that are longer than 80 characters are url links.
- Lines that do not satisfy the indent requirements are the coding style of arranging function arguments. I believe it does not negatively affect the readability of my codes. 

> ## DESCRIPTION file
> * [x]  🚨 Please update the depended R version to 4.2

Done.

> * [x]  🚨 You have C++11 listed in `SystemRequirements` but I couldn't see any C++ code. Please remove this if it isn't needed.

I’ve removed the C++ requirement.

> ## NAMESPACE file
> * [x]  🚨 Please use `lowerCamelCase` for function names, `UpperCamelCase` is reserved for objects

Below are the function name changes to comply with the `lowerCamelCase` rule:
- ARCScore -> arcScore
- ConvertToSeurat -> convertToSeurat
- CreateSlide -> createSlide
- KeepHighGene -> keepHighGene
- Read10xRaw -> read10xRaw
- Read10xRawH5 -> read10xRawH5
- Read10xSlide -> read10xSlide
- SpotClean -> spotclean
- VisualizeHeatmap -> visualizeHeatmap
- VisualizeLabel -> visualizeLabel
- VisualizeSlide -> visualizeSlide

> ## Documentation
> ### Vignette
> * [x]  🚨 Please add a table of contents to the vignette

Done.

> * [x]  🚨 All code chunks in the vignette should be executed

Now only 3 chunks in the Quick Start section that are not executed: 
- The first one is the illustration of package installation. 
- The second one is a summary of the Detailed Steps section containing exactly the same codes. In order to save package build time, this chunk is set to not be evaluated.
- The third one is the illustration of the application of SpotClean on SpatialExperiment class. Again, more details are at the Detailed Steps section. In order to save package build time, this chunk is set to not be evaluated.

Only 1 chunk in the Detailed Steps section is not executed:
- An illustration of connecting SpotClean results with Seurat pipeline. Since Seurat requires a path to external image-related files (which my package does not include), I’m just illustrating the basic format to call the function.

> * [x]  🚨 Please includes a motivation for submitting the package to Bioconductor in the _Introduction_ section

Done.

> * [x]  🚨 Please mention related or alternative packages in the _Introduction_ section

Done.

> ### Man pages
> * [x]  🟢 It is recommended to add a package man page

Added a package man page.

> * [x]  🟢 Rather than using comments you can use Roxygen tags to document internal functions and mark them as internal

Thanks for the suggestion! I will try to address them in future updates.
 
> ## Code
> ### R
> * [x]  ⚠️ It is recommended to test that function arguments are valid in exported functions

I’ve added more codes to validate function arguments for major functions in the package.

> * [x]  🟢 Please check the advice for [including **ggplot2** in packages](https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html)

Now my package only imports necessary ggplot2 functions via `importFrom` instead of importing the whole ggplot2 package.

**Comment by lazappi** [comment]
> * There is no runnable example in `convert_to_seurat.R` since this function requires external image-related files (the sizes of which can be large). Since this is not a major function in my package, I don't think it worths sacrificing the size of the packge only to make this single example runnable. Instead, I’m instructing users to correctly specify the path to image-related files by themselves.

This function needs to be tested in some way, currently it doesn't have a runnable example, successful tests or is run in the vignette. There are a few options for how to do this. You could include some example data in this package (I understand your concerns about size but it should be possible to come up with a small example), you could reuse example data in another package (maybe **{SpatialExperiment}** or **{Seurat}**) or you could use **{BiocFileCache}** to download a public dataset to test on.

There is also a small typo in `tissue_lowres_iamge.png` in the function documentation 😸 

> > * [x]   🚨 All code chunks in the vignette should be executed
> 
> Now only 3 chunks in the Quick Start section that are not executed:
> 
> * The first one is the illustration of package installation.
> * The second one is a summary of the Detailed Steps section containing exactly the same codes. In order to save package build time, this chunk is set to not be evaluated.

I would still be concerned that this will not be kept up to date if there were any future changes to these functions. It should be mentioned in the text that this is not run and the steps are explained in the later sections.

> * The third one is the illustration of the application of SpotClean on SpatialExperiment class. Again, more details are at the Detailed Steps section. In order to save package build time, this chunk is set to not be evaluated.

Why have you chosen to base your package around **SummarizedExperiment** rather than **SpatialExperiment**? It seems like **SpatialExperiment** would be the natural fit for this kind of data and would make maintenance easier as you could reuse functionality in existing packages.

> > * [x]   🟢 Please check the advice for [including **ggplot2** in packages](https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html)
> 
> Now my package only imports necessary ggplot2 functions via `importFrom` instead of importing the whole ggplot2 package.

👍🏻  What I was specifically referring to is using `.data$imagerow` rather than statements like `imagerow <- imagecol <- barcode <- NULL` to avoid warnings about undeclared variables.

**Comment by zijianni** [comment]
Hi @lazappi
Thanks again for your additional comments! Please see updates below. Let me know if you have further questions and comments.

> > * There is no runnable example in `convert_to_seurat.R` since this function requires external image-related files (the sizes of which can be large). Since this is not a major function in my package, I don't think it worths sacrificing the size of the packge only to make this single example runnable. Instead, I’m instructing users to correctly specify the path to image-related files by themselves.
> 
> This function needs to be tested in some way, currently it doesn't have a runnable example, successful tests or is run in the vignette. There are a few options for how to do this. You could include some example data in this package (I understand your concerns about size but it should be possible to come up with a small example), you could reuse example data in another package (maybe **{SpatialExperiment}** or **{Seurat}**) or you could use **{BiocFileCache}** to download a public dataset to test on.

I’ve put some image-related files to `inst/extdata`. Now this function has runnable examples as well as unit tests.

Given that I’ve added raw image-related files, I’ve discarded the use of `data/mbrain_slide_info.rda` and updated all the examples, tests, and vignette accordingly.
 
> There is also a small typo in `tissue_lowres_iamge.png` in the function documentation 😸

Fixed. Thanks!

> > > * [x]    🚨 All code chunks in the vignette should be executed
> > 
> > 
> > Now only 3 chunks in the Quick Start section that are not executed:
> > 
> > * The first one is the illustration of package installation.
> > * The second one is a summary of the Detailed Steps section containing exactly the same codes. In order to save package build time, this chunk is set to not be evaluated.
> 
> I would still be concerned that this will not be kept up to date if there were any future changes to these functions. It should be mentioned in the text that this is not run and the steps are explained in the later sections.

I’ve further reduced non-runnable chunks and added notes to clarify that in the vignette.
 
> > * The third one is the illustration of the application of SpotClean on SpatialExperiment class. Again, more details are at the Detailed Steps section. In order to save package build time, this chunk is set to not be evaluated.
> 
> Why have you chosen to base your package around **SummarizedExperiment** rather than **SpatialExperiment**? It seems like **SpatialExperiment** would be the natural fit for this kind of data and would make maintenance easier as you could reuse functionality in existing packages.

To be honest, I was not aware that **SpatialExperiment** is becoming an officially supported and encouraged Bioconductor package when I wrote my package. I also have additional concerns about using it, as discussed earlier in this thread. 

Saying that, **SummarizedExperiment** and **SpatialExperiment** share many similar properties, and there has been many examples to convert between them (and **SingleCellExperiment**). I hope this won’t be a big problem for future maintenance.
 
> > > * [x]    🟢 Please check the advice for [including **ggplot2** in packages](https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html)
> > 
> > 
> > Now my package only imports necessary ggplot2 functions via `importFrom` instead of importing the whole ggplot2 package.
> 
> 👍🏻 What I was specifically referring to is using `.data$imagerow` rather than statements like `imagerow <- imagecol <- barcode <- NULL` to avoid warnings about undeclared variables.

Thanks! I’ve made updates to incorporate that.

**Comment by lazappi** [comment]
Hi @zijianni. I am happy with this now so will mark it as accepted. Congratulations on getting the package into Bioconductor 🎉!  It can take a couple of days to be picked up by the build system but then it should be available in Bioconductor devel.

**Comment by zijianni** [comment]
Thanks again @lazappi for your time reviewing my package!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zijianni.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpotClean")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpotClean

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
