### ISSUE TITLE
goSorensen

### ISSUE THREAD

**Issue by pablof1988** [Bioconductor/Contributions#2658]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pablof1988/goSorensen

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
remove .Rproj.   verify that BiocCheck is passed on a clean machine.  remove build/vignette.rds

**Comment by pablof1988** [comment]
Thank you. Changes are done and these are in the git-hub repository (https://github.com/pablof1988/goSorensen). Say me please, where I have to send these changes ?

Best regards.

**Comment by pablof1988** [comment]
Dear reviewer.

I just have pushed the changes to git Bioconductor.

Best regards

**Comment by ococrook** [comment]
Hi, thanks for submitting @pablof1988 

It looks like there are some ERRORs etc to clean-up before we can get the review started. Could you take a looked at the build report and make the changes required for the package to build cleanly? It looks like your examples are also too long, these should be quick code snippets that simply demonstrate the function and do not do much analysis. Once you've address that, I can review the package in more detail.

Best wishes,
Olly

**Comment by pablof1988** [comment]
Dear Oliver

Thank you for your comments. Ok, I'll try to improve the examples but I have a problem about the errors you mention: The build report says "ERROR: Use Authors@R field not Author/Maintainer fields. Do not use both", I have done it, I have deleted Author/ Maintainer fields and I have used only Authors@R (exactly the same as shown in the image at the bottom), however, when running the build report, the Author and Maintainer fields are generated automatically and I don't know what to do to solve it.

Best wishes.

Pablo.

![image](https://user-images.githubusercontent.com/64914241/168675120-afe4e2c7-98c7-4b34-9e14-2751a2ea0b2c.png)

**Comment by ococrook** [comment]
Hi Pablo,

Have you push to the bioconductor git to trigger a new build - remember you'll need to increment the version to 0.99.1? Let me know if you need help doing that.

**Comment by pablof1988** [comment]
Dear Oliver.

I just have pushed to Bioconductor git ´the change of version. I hope I did it well, I send a capture.

Best regards,

Pablo.

![image](https://user-images.githubusercontent.com/64914241/168874320-3b99bb63-6d05-4a97-930b-58e97611202f.png)

**Comment by ococrook** [comment]
Thanks for removing the timeout and build ERRORs. I will now formally review the package. This may take upto 10 days complete. In the meantime you may wish to look at the Notes, as addressing these will likely be part of the review.

**Comment by pablof1988** [comment]
Ok, Thank you very much

**Comment by pablof1988** [comment]
Hello Oliver.

I just want to say that the article "An equivalence test between features lists, based on the Sorensen–Dice index and the joint frequencies of GO term enrichment" has been published in BMC Bioinformatics. This paper collect all the theoretical fundation of the goSorensen package (under revision). I think that article could be a base for your revision because We explain all the methodology implemented to make comparisson between gene list and the aplication was made by the goSorensen package. You can find the article in https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-022-04739-2 .

Best regards.

**Comment by ococrook** [comment]
Hi @pablof1988 thanks for the paper link, the method looks very useful. Could you address the following issues or explain why they are not possible? If you could write a brief response to say that you have made these changes then that would be great. Remember to bump the package version once you have made the changes. 

# Description:

- [ ] Authors, please add ORCID if possible

- [ ] LazyData please set this to false.

- [ ] Add biocViews: Reactome, Clustering, KEGG

# Unit tests:

 - [ ] There is a lot of uncommented code, please remove this if it is not run

# Namespace:

- [ ] Please selectively import using importFrom rather than importing a whole package.

# Readme.md

Please add the following

- [ ] Installation instructions (Bioconductor and Github)
- [ ] A brief rationale of the package - what objects do we input?
- [ ] Contribution guidelines
- [ ] References to publications

# News.md

Please a news.md file that records

- [ ] The package version
- [ ] The updates that occur at each package version, bug fixes etc.

# R code

- [ ] Classes should be contained in Allclasses.R
- [ ] Methods should be contained in methods-goSorensen.R
- [ ] Bioconductor requires use of S4 objects and methods, not S3, for example `equivSDhtest` could be better made as an S4 class. 
- [ ] Please avoid for loops and sapply, in general please use vapply
- [ ] Avoid constructions such as 2:numLists, please use seq_along or seq_len depending on the situation.
- [ ] Please check that key inputs to functions are valid, for example if x should be numeric your code should check that x is indeed numeric.
- [ ] Make sure all functions are documented, even if they are not exported from the package.
- [ ] Please remove “stop” and “warn” from code

# Vignette

- [ ] Please use the bioconductor vignette template
- [ ] Please add bioconductor install instructions, please do not evaluate this code chunk though
- [ ] Please add a sessionInfo() to the end of the vignette
- [ ] Could the vignette be divided up with headings to make it easier to follow

**Comment by pablof1988** [comment]
Hello Dear Olive @ococrook 
Thank you for your observations. Please, I have a question:
The S3 class “equivSDTest” is a paradigmatic example of why we opted for the S3 class model: An “equivSDTest” is an “htest”, i.e., inheriting from “htest” we have all its methods, like ‘print’. 
In fact, we prefer S4 and possibly opting for S3 was a wrong decision. In any case, we must address the task of migrating from S3 to S4. Continuing the “equivSDTest” example, what do you think is best? To rewrite from scratch a S4 counterpart of “htest” (we are not aware of the existence of a standard S4 version of “htest”) or to mix both class systems, e.g., by means of S4 registering “htest” with ‘setOldClass’ and making “equivSDTest” to inherit from it?

**Comment by ococrook** [comment]
I don't think you need to strictly Inherit 'htest'. An S4 object that contains everything you need would work. I'm not entirely confident that S4 is actually necessary here so I'm going to ask for a 2nd opinion.

@lshep, how much do you think a package would benefit from an S4 object rather than S3 in this case?

**Comment by lshep** [comment]
We recommend it but not require if adequate justification is provided. In the future we prefer S4 as it provides a more structured class and method approach but S3 is probably okay in this case because of the reasons given

**Comment by pablof1988** [comment]
Hello @ococrook 
Thank you very much for the recommendations, we have worked to improve the package based on them. These are the changes we have made, we also write a justification when we could not do it. The things that we fulfill, we have simply marked it with a check.

**DESCRIPTION:**
- [✓] Authors, please add ORCID if possible
- [✓] LazyData please set this to false.
- [✓] Add biocViews: Reactome, Clustering, KEGG

**UNIT TESTS:**
- [✓] There is a lot of uncommented code, please remove this if it is not run

**NAMESPACE:**
- [✓] Please selectively import using importFrom rather than importing a whole package.

**Readme.md**
- [✓] Installation instructions (Bioconductor and Github)
- [✓] A brief rationale of the package - what objects do we input?
- [✓] Contribution guidelines
- [✓] References to publications

**News.md**
Please a news.md file that records
- [✓] The package version
- [✓] The updates that occur at each package version, bug fixes etc.

**R code**
- [  ] Classes should be contained in Allclasses.R
- [  ] Methods should be contained in methods-goSorensen.R
 Note: In our opinion, these first two requirements would not be mandatory under S3, provided its less formal definition of classes and methods. We are now working on a future S4 version, but please see the next note.
- [  ] Bioconductor requires use of S4 objects and methods, not S3, for example equivSDhtest could be better made as an S4 class.
Note: We fully agree, S4 would be a better option. However, if deemed acceptable in order to match –approximately– the date of the method publication and its implementation, please accept for the time being this package version based on S3. Likely, S4 will not add new functionalities but more rigorous programming structure. Possibly, this is also the point of view of contributor “lshep” to this conversation.
- [ ✓] Please avoid for loops and sapply, in general please use vapply 
Note: ’vapply’ is faster than ‘sapply’ but needs providing in advance a prototype of the result of the function being iterated, by means of its argument ‘FUN.VALUE’. All remaining ‘sapply’ in the package are impossible to change because the varying nature of this prototype.
- [ ✓] Avoid constructions such as 2:numLists, please use seq_along or seq_len depending on the situation.
- [ ✓] Please check that key inputs to functions are valid, for example if x should be numeric your code should check that x is indeed numeric.
- [ ✓] Make sure all functions are documented, even if they are not exported from the package.
- [ ✓] Please remove “stop” and “warn” from code

**Vignette:**
- [ ✓] Please use the bioconductor vignette template.
- [ ✓] Please add bioconductor install instructions, please do not evaluate this code chunk though.
- [ ✓] Please add a sessionInfo() to the end of the vignette
- [ ✓] Could the vignette be divided up with headings to make it easier to follow.

Best regards.

**Comment by pablof1988** [comment]
Dear @ococrook 

We would like to comment you that **CHECK**, generates a ‘warning’ providing notice of the presence of ‘library’ statements in the package code (literally says: "_WARNING: Avoid the use of 'library' or 'require' in R code_"). These statements are at function ‘buildEnrichTable’ which in the first versions of the package was too slow, because it performs countless enrichment tests. The solution we found was make it parallel, but due to some particularities of parallel computing in Windows, each node running in parallel needs additional information on node-local variables and packages. If these ‘library’ statements were suppressed, parallelization would run still fine in Lynux and MacOS, but to produce an error in Windows.

Best regards.

**Comment by ococrook** [comment]
Hi Pablo

You can ignore that warning for the moment. The package looks good, I've got a few small requests left.

# Small remaining changes

- [ ] The NEWS.md isn't upto date with the Description file
- [ ] There are still some unrobust constructs such as 1:n in your code, take a look at the (s,v,l)apply and edit based on the previous advice
- [ ] Some functions still provide errors that are a little hard to debug, because the inputs are not checked or the documentation is not quite clear. For example, `dSorensen` says x can be a character, but when I try  `dSorensen("Sec1", onto = "BP")`, I get a cryptic error. I appreciate that I've purposely broken this function but your user will likely be more obtuse than me so help them provide the correct arguments.

**Comment by pablof1988** [comment]
Hello @ococrook 

We have worked on your observations, these are the changes (things fulfilled simply has a check):

- [✓] The NEWS.md isn't upto date with the Description file.
- [✓] There are still some unrobust constructs such as 1:n in your code, take a look at the (s,v,l)apply and edit based on the previous advice
- [✓] Some functions still provide errors that are a little hard to debug, because the inputs are not checked or the documentation is not quite clear. For example, dSorensen says x can be a character, but when I try dSorensen("Sec1", onto = "BP"), I get a cryptic error. I appreciate that I've purposely broken this function but your user will likely be more obtuse than me so help them provide the correct arguments.
We have done changes in the help of functions duppSorensen, equivtestSorensen, dSorensen, seSorensen and buildEnrichTable. Now, it is controlled in a more informative way that the lists of genes that we provide to analyze match with their representation in the "universe of genes" in which we work.
In addition, we have added a test script that executes the statement dSorensen("Sec1", onto = "BP"), where you can see more satisfactory results, different from those obtained previously.

Best regards

**Comment by ococrook** [comment]
Hi Pablo, looks good to me. Is there any chance you could remove the following notes if at all possible?

    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
    * NOTE: Avoid using '=' for assignment and use '<-' instead

**Comment by pablof1988** [comment]
Hello @ococrook 

ok, changes are done and these notes have disappeared

Best regards

**Comment by ococrook** [comment]
Great, could you revist the warning from time to time to see if it can be removed.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pablof1988.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("goSorensen")`. The package 'landing page' will be created at

https://bioconductor.org/packages/goSorensen

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by pablof1988** [comment]
Dear @ococrook @lshep 

Please need your help. Seven days ago goSorensen package was accepted to publish in Bioconductor (We are very pleasure to publish an R package in Bioconductor. Thanks to accept it), but  We are a bit worried since up to now the installation cannot be done using the classic "BiocManager::install("goSorensen")" which is used to install the packages found in Bioconductor, We understand that it is because package is not yet available/published, also, on the Bioconductor web page, the package still appears as a development version. Please coud you say me if We are forgetting some step? or is there some aditional thing that We have to do before publication? We have the ssh key and We have submited it to Bioconductor, maybe Have We to create a new ssh key? or Have We to change the version of package (currently is 0.99.13)?

Please help me!

**Comment by ococrook** [comment]
Hi @pablof1988 

The package will be available via bioconductor at the next release. There are two releases per year. There will always be a devel version which you can also install. The devel version is the one that becomes available in the next release. 

You'll be able to install your package using that command in a few months. Until that you can add the devel argument if you want the bioconductor version that will be released. 

Does that answer your question?

Best,
Olly

**Comment by pablof1988** [comment]
Thank you very much for your answer@ococrook, now all is clear for me.

**Comment by pablof1988** [comment]
Good afternoon.

We have just updated the goSorensen package, adding new functions and results. We uploaded these changes to the GitHub repository. We would like to know what procedure we need to perform so that these changes can be displayed as a package update in a future release of Bioconductor. Will it update automatically (it just needs to be on GitHub)? Or should we submit the update to a review process? If so, how can I carry out that process?

**Comment by ococrook** [comment]
Hi!

You need to push the changes to Bioconductor: https://contributions.bioconductor.org/git-version-control.html#sync-existing-repositories

Let me know if you need help! We don't review changes to packages - of course if your package ends up with Errors after updating, these will need to be fixed.

**Comment by pablof1988** [comment]
Ok, Thank you for the help; I will try it

**Comment by pablof1988** [comment]
Hello @ococrook 

Please help me!!

I have tried to push the changes to Bioconductor, but I have not been successful because when doing, for example, "git fetch --all" or, more specifically, "git fetch upstream," the message "git@git.bioconductor.org: Permission denied (publickey)" appears. 
I guess this problem is produced because I now have a different computer than the one I used when I uploaded the changes for the first version of the package. I remember that before, it simply asked me for the password and let me continue. The problem is that now it does not ask me for this password, which I remember but can't use.

**Comment by pablof1988** [comment]
Hello again, @ococrook. 

To give a possible solution to the above problem mentioned, I created a new ssh key, and I associated this key to the git project using the following git code: "_git remote set-url upstream git@github.com:pablof1988/goSorensen.git_" This process allowed me to use the ssh key and delete the error message mentioned above. Now all the processes run, but I wonder if the changes were really sent to Bioconductor, for I remind that when one sends something to Bioconductor, a notification immediately arrives, but this time nothing has arrived. 
Can you please help me? Likely I am making some mistakes.

**Comment by ococrook** [comment]
If you push to the bioc branch again, it would tell you everything is upto date. Remember you are pushing to devel, so you can also clone the devel branch at bioc and check that it's the same

**Comment by pablof1988** [comment]
When I do "git push upstream master," it shows a message "Everything up-to-date." So, I suppose all is ok, and the changes are in Bioconductor.
