### ISSUE TITLE
proteasy

### ISSUE THREAD

**Issue by martinry** [Bioconductor/Contributions#2660]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/martinry/proteasy

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```> ## ----Search substrate, eval = TRUE--------------------------------------------
> 
> # Kininogen-1
> searchSubstrate(protein = "P01042", summarize  .... [TRUNCATED] 
Error in searchSubstrate(protein = "P01042", summarize = TRUE) : 
  object 'mer' not found

```
that's from attempting to build the vignette.  The Collate statement in DESCRIPTION does not agree with the content of R folder ... Methods.R vs methods.R.  Please be sure that R CMD check and BiocCheck are running satisfactorily on a clean system.

**Comment by martinry** [comment]
Thank you for your response. I have changed methods.R to Methods.R so it agrees with Collate statement. I am however not able to reproduce the error. (Edit: I have corrected what I think caused the error). Here is what I have checked on a clean install of R (and dependencies) on Mac Big Sur and Windows 10 and found no error:
```
git clone https://github.com/martinry/proteasy.git
R CMD build proteasy
R CMD check proteasy_0.99.0.tar.gz
```
I am also able to run, without error
```
devtools::build_vignettes("proteasy")
devtools::install_github("martinry/proteasy", build_vignettes = T)
```
Can you advise on how I may reproduce the error? Thank you.

**Comment by vjcitn** [comment]
```
--- re-building ‘proteasy.Rmd’ using rmarkdown
Quitting from lines 53-57 (proteasy.Rmd) 
Error: processing vignette 'proteasy.Rmd' failed with diagnostics:
object 'merops_map' not found
--- failed re-building ‘proteasy.Rmd’
```

**Comment by vjcitn** [comment]
You must have some initializations that give you merops_map.

**Comment by martinry** [comment]
Thank you. I have made adjustments (R CMD build/check and BiocCheck OK). Hoping the problem has been fixed and I would like to request another build attempt.

**Comment by vjcitn** [comment]
please bump the package version number for EVERY source commit

**Comment by vjcitn** [comment]
```
--- re-building ‘proteasy.Rmd’ using rmarkdown
Quitting from lines 64-68 (proteasy.Rmd) 
Error: processing vignette 'proteasy.Rmd' failed with diagnostics:
x is not a data.table
--- failed re-building ‘proteasy.Rmd’

SUMMARY: processing the following file failed:
  ‘proteasy.Rmd’

Error: Vignette re-building failed.
```

**Comment by martinry** [comment]
I can reproduce the error only by removing sysdata.rda from proteasy/R/. I have rebuilt the internal data using usethis::use_data(), and set LazyData: true in DESCRIPTION file. Requesting another build attempt. Thank you.

**Comment by vjcitn** [comment]
CMD check takes over my browser with https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=A01.009

**Comment by martinry** [comment]
Apologies, I have added a \dontrun tag for the affected function's example.

**Comment by vjcitn** [comment]
You could do `if (interactive())` with some warning to the user in a comment, if you want to have that in the example.

**Comment by martinry** [comment]
Thank you. I have updated the example as per your suggestion.

**Comment by Kayla-Morrell** [comment]
@martinry - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The installation instructions in the README file should also
  include Bioconductor installation instructions. 

## DESCRIPTION

- [ ] SUGGESTION: The Description field is made up by less than 3 sentences.
  Please consider expanding this field and structure it as a full paragraph.
- [ ] SUGGESTION: Since you are using a standard license it is not necessary to
  include 'LICENSE' and the license file in your package.
- [ ] REQUIRED: 'LazyData:' should be set to false.
- [ ] REQUIRED: There needs to be at least 2 terms listed for biocViews.

## Data

- [ ] REQUIRED: We do not allow data that is being used in the package to be
  included as sysdata.rda. This data should be part of the package as either
exported data that is included in a `data/` directory or as raw data included in
the `inst/extdata/` directory. We also require all data to be documented
properly. See our documentation on package data
[here](https://contributions.bioconductor.org/data.html).

## Vignette

- [ ] REQUIRED: There should be relevant text accompaning each code chunk. It's
  not enough to just display code, there should be some narrative as to what is
being done in the code, why this code should be used. Details are needed besides
just descriptive section headers and comments in code chunks.
- [ ] REQUIRED: The code chunk in section 3.4 should be uncommented out. Since
  you include this code chunk in `eval = FALSE` the code won't be evaluated but
it needs to be shown to the user as executable code.
- [ ] REQUIRED: The Introduction section should also include information about
  the motivation for the package as well as motivation for inclusion in
Bioconductor.
- [ ] REQUIRED: The Installation section code should not be commented out. Since
  you included `eval = FALSE` this code will not be evaluated but should be
visible as code to the user.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to main functions.
- [ ] REQUIRED: Use `donttest{}` instead of `dontrun{}` since `donttest{}`
  requires vaild R code while `dontrun{}` does not.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests, we strongly encourage them.

## R code

- [ ] REQUIRED: Avoid `1:...`, use `seq_len()` or `seq_along()` instead.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 67
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 32 lines that are not.

Best,
Kayla

**Comment by martinry** [comment]
Hi @Kayla-Morrell,

Thank you for you comments and suggestions. I have addressed all required points and most suggestions. Main changes include:

- Changing from sysdata.rda to two individual compressed, tab-delimited files in _inst/extdata_. Documentation for these files are found in _inst/script/data-gen.Rmd_ (please let me know if this is an appropriate way of documenting such files. Does it need to be a .R file?).
- Improved vignette by adding more comments and examples,  and a more descriptive introduction with "Motivation" and "Package scope and limitations" sub headings.

> ## General package development
> * [X]  REQUIRED: The installation instructions in the README file should also
>   include Bioconductor installation instructions.
> 
> ## DESCRIPTION
> * [X]  SUGGESTION: The Description field is made up by less than 3 sentences.
>   Please consider expanding this field and structure it as a full paragraph.
> * [X]  SUGGESTION: Since you are using a standard license it is not necessary to
>   include 'LICENSE' and the license file in your package.
> * [X]  REQUIRED: 'LazyData:' should be set to false.
> * [X]  REQUIRED: There needs to be at least 2 terms listed for biocViews.
> 
> ## Data
> * [X]  REQUIRED: We do not allow data that is being used in the package to be
>   included as sysdata.rda. This data should be part of the package as either
>   exported data that is included in a `data/` directory or as raw data included in
>   the `inst/extdata/` directory. We also require all data to be documented
>   properly. See our documentation on package data
>   [here](https://contributions.bioconductor.org/data.html).
> 
> ## Vignette
> * [X]  REQUIRED: There should be relevant text accompaning each code chunk. It's
>   not enough to just display code, there should be some narrative as to what is
>   being done in the code, why this code should be used. Details are needed besides
>   just descriptive section headers and comments in code chunks.
> * [X]  REQUIRED: The code chunk in section 3.4 should be uncommented out. Since
>   you include this code chunk in `eval = FALSE` the code won't be evaluated but
>   it needs to be shown to the user as executable code.
> * [X]  REQUIRED: The Introduction section should also include information about
>   the motivation for the package as well as motivation for inclusion in
>   Bioconductor.
> * [X]  REQUIRED: The Installation section code should not be commented out. Since
>   you included `eval = FALSE` this code will not be evaluated but should be
>   visible as code to the user.
> 
> ## Man pages
> * [X]  SUGGESTION: We encourage having a package man page with an overview of the
>   package and links to main functions.
> * [X]  REQUIRED: Use `donttest{}` instead of `dontrun{}` since `donttest{}`
>   requires vaild R code while `dontrun{}` does not.
> 
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests, we strongly encourage them.
> 
> ## R code
> * [X]  REQUIRED: Avoid `1:...`, use `seq_len()` or `seq_along()` instead.
> * [X]  SUGGESTION: For formatting reasons, consider shorter lines. There are 67
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 32 lines that are not.

I will kindly ask you for a re-review of proteasy. Thank you!

Martin

**Comment by Kayla-Morrell** [comment]
@martinry - Thank you for making the necessary changes. I have re-reviewed everything and it all looks great. I am more than happy to accept the package.

Best,
Kayla

**Comment by martinry** [comment]
Hi @Kayla-Morrell and thank you for review and accepting the package. Off topic for this issue, but I wrote an email to packages@bioconductor.org (which seems to have bounced) about creating an annotation package using data from MEROPS. It would contain identifier mapping, and information related to organism, cleavage sites, residue specificity etc. The data would be obtained from https://www.ebi.ac.uk/merops (Download -> MEROPS Release 12.1, I can elaborate about current data format if necessary) and require minimal curation. Can you give any advice on how to move forward with this idea? It would require access to data lake as described in [CreateAHubPackage](https://www.bioconductor.org/packages/devel/bioc/vignettes/HubPub/inst/doc/CreateAHubPackage.html).

Best regards,
Martin

**Comment by Kayla-Morrell** [comment]
@martinry - Try emailing hubs@bioconductor.org, someone who takes care of Hub requests will be able to give you access to data lakes (via SAS token or URL). It would be good to include in the email a link to the metadata file from the GitHub repo.

Best,
Kayla

**Comment by martinry** [comment]
Thanks @Kayla-Morrell , I'll try that!

Best regards,
Martin

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/martinry.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("proteasy")`. The package 'landing page' will be created at

https://bioconductor.org/packages/proteasy

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
