### ISSUE TITLE
katdetectr

### ISSUE THREAD

**Issue by daanhazelaar** [Bioconductor/Contributions#2676]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ErasmusMC-CCBC/katdetectr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
maftools produces a rainfall plot https://www.bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/maftools.html

any chance you can reuse that or other related functions already in bioconductor?

**Comment by daanhazelaar** [comment]
Dear vjcitn,

The rainfall plot function of katdetectr is build around the ggplot2 package. We prefer using the tidy format for organising our data and subsequent visualisation. Maftools rainfall plot is generated using R graphics package which does not fit well into the workflow of katdetectr. We have not found a related function on bioconductor that generates a rainfall plot (or something similar) and fits well into a tidy format workflow. Therefore, we prefer using katdetectrs custom rainfall plot function. 

Kind regards,
Daan Hazelaar

**Comment by daanhazelaar** [comment]
Dear reviewer,

I see the WARNINGS originate from undocumented code objects. However, all mentioned functions and classes are documented using roxygen2. I also do not get these WARNINGS when running CMD check my self (both on linux en macOS). Can you perhaps give a suggestion on how to fix these WARNINGS?

kind regards,
Daan Hazelaar

**Comment by lazappi** [comment]
Hmmm...that's a bit weird. Can you check that the documentation has been generated by **{roxygen2}** (probably with `devtools::document()`) and that you have committed the files to your git repository (and pushed them to the Bioconductor remote)? I think the most likely explanation is that you have them locally but for some reason they haven't made it to the build system. You can also try cloning from the Bioconductor git address above to see exactly what is there.

**Comment by daanhazelaar** [comment]
Dear lazappi,

Aha for some reason the man folder generated by roxygen2 was not included in the git repository. I think that was the problem. I have included it now but I can't push to the bioconductor remote. I followed all steps of the manual and all credentials seem correct to me. Can you perhaps tell me why I'm denied writing acces to git@git.bioconductor.org:packages/katdetectr.git?


![Screenshot 2022-05-31 at 10 32 24](https://user-images.githubusercontent.com/55545896/171129627-716f9dbb-2470-4640-ae71-f9aeb6b8233e.png)

**Comment by lazappi** [comment]
You need to push to `upstream master`, the Bioconductor git server still uses `master` as the main branch rather than `main`.

**Comment by daanhazelaar** [comment]
Now I get the following. I have not been able to solve it. Do you have any advice?

![Screenshot 2022-05-31 at 13 05 30](https://user-images.githubusercontent.com/55545896/171159704-a3906906-075f-4746-afd7-47cb64171dca.png)

**Comment by lshep** [comment]
Please see #5  of [new package workflow](http://contributions.bioconductor.org/git-version-control.html#new-package-workflow) .

**Comment by nturaga** [comment]
You seemed to be able to push now! Great news!

**Comment by daanhazelaar** [comment]
Dear nturaga,

Yes definitely great! 😅

Kind regards,
Daan Hazelaar

**Comment by lazappi** [comment]
Hi @daanhazelaar

Thanks for submitting **katdetectr** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please address as many of the notes from `BiocCheck::BiocCheck()` as possible

## DESCRIPTION file

- [ ] :rotating_light: Please update `Depends: R >= 4.2`
- [ ] :warning: Usually the `BugReports` URL points directly to the GitHub issues page

## NAMESPACE file

- [ ] :warning: I don't think you need to import **{BiocStyle}** to use it in the vignette

## Package data

- [ ] :warning: Could you access the `APL_primary.maf` file directly from **{maftools}** rather than copying it?

## Documentation

### Vignette

- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: Please add an *Introduction* section. This should include:
  - Motivation for inclusion in Bioconductor
  - Comparison to similar packages (if applicable)
- [ ] :rotating_light: Please add an *Installation* section. This should use Bioconductor installation instructions and **NOT** be evaluated.
- [ ] :warning: I think you have done a good job of showing how the package can be used but I think you could provide some more detail describing the outputs and how to interpret them. If there are any parameters that are particularly important it would be good to discuss how to set those as well.
- [ ] :warning: Usually any packages used in the vignette are loaded in a chunk visible to users
- [ ] :warning: If your paper isn't available yet it's probably better to have no link than to link to Google which will be confusing for readers
- [ ] :rotating_light: In general any results/errors/warnings should not be hidden so that user output matches what is in the vignette. If there is a reason to hide things it should be mentioned in the text that this has been done.

### Man pages

- [ ] :warning: It is recommended to add a package man page


## Code

### R

- [ ] :rotating_light: Accessor function should be used rather than `@` or `slot()` (except when the object comes from another package which does not provide them)
- [ ] :rotating_light: You should allow users to provide a `BiocParallel` rather than just a number of workers, this allows the user to control how the parallelisation is done
- [ ] :rotating_light: You should provide an exported constructor function for any exported objects
- [ ] :green_circle: Using pipes in functions can make debugging difficult, I would try to avoid this

**Comment by daanhazelaar** [comment]
Dear Luke,

Apologies for my late reply, I missed your previous comment. Thanks for your review and feedback! I'm working on implementing it. 

However, I have encountered a strange problem. When I run R CMD check on the current version of katdetectr (as it is available on the bioconductor repo now) which has been build on linux, Windows and Mac without errors and warnings. I get the following warning:

![Screenshot 2022-06-20 at 19 48 23](https://user-images.githubusercontent.com/55545896/174655591-3d73dba0-451f-46b2-80ed-1241c0ed464c.png)

It seems to be related to the .Rd files in the man folder. When I delete the man folder (and do not run devoots::document()) then I don't get this error. When I call devools::document() (which generates the man directory) en run R CMD check I again get the same error.

Do you know where this comes from? Some advice would be great!

Kind regards,
Daan Hazelaar

**Comment by lazappi** [comment]
Hi @daanhazelaar 

I noticed that as well when I was reviewing your package. I think it is something that has changed in **{rtracklayer}**. I can see the same warning just from loading **{rtracklayer}** (using the Bioconductor development versions):

```r
#> library(rtracklayer)
# Warning message:
# replacing previous import ‘utils::download.file’ by ‘restfulr::download.file’ when loading ‘rtracklayer’  
```

I think for now don't worry too much about this and try to address the other comments I made, once those have been addressed we can see if you still need to do something about this.

**Comment by daanhazelaar** [comment]
Hi Luke,

Thanks for your reply. Updating to R 4.2 made this warning disappear. I'll continue with implementing your other remarks.

Kind regards,
Daan Hazelaar

**Comment by daanhazelaar** [comment]
-	Please address as many of the notes from BiocCheck::BiocCheck() as possible
o	NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials). 
	I’m subscribed for the Bioc-Devel mailing list
o	NOTE: Consider multiples of 4 spaces for line indents; 29 lines (2%) are not.
	I removed all those I could find
o	NOTE: Consider shorter lines; 248 lines (13%) are > 80 characters long.
	This decreases readability in my opinion
o	NOTE: Recommended function length <= 50 lines.There are 2 functions > 50 lines.
	I think these 2 functions are readable and understandable with their current length 
-	DESCRIPTION file
o	Please update Depends: R >= 4.2
	Done
o	Usually, the BugReports URL points directly to the GitHub issues page
	Done
-	NAMESPACE file
o	I don't think you need to import {BiocStyle} to use it in the vignette
	Done, removed BiocStyle from import
-	Package data
o	Could you access the APL_primary.maf file directly from {maftools} rather than copying it?
	I also use this file for many of the unit tests. If the maintainer of maftools decides to make an adjustment to this file than my test will likely fail. Therefor I prefer keeping it as it is now.
-	Documentation
-	Vignette:
o	Please add a table of contents
	Done
o	Please add an Introduction section. This should include: Motivation for inclusion in Bioconductor. Comparison to similar packages (if applicable)
	Done, I included this in the introduction. However, we are working on publishing an application note for katdetectr which includes extensive performance evaluation of katdetectr and other kataegis detection packages (maftools, seqkat, ClusteredMutations, Kataegis and SigProfilerClustered). When this paper is published, I will of course link to this paper in the vignette. I personally think it’s not necessary to include performance evaluation / comparison to other packages in our vignette.
o	Please add an Installation section. This should use Bioconductor installation instructions and NOT be evaluated.
	Done
o	I think you have done a good job of showing how the package can be used but I think you could provide some more detail describing the outputs and how to interpret them. If there are any parameters that are particularly important it would be good to discuss how to set those as well.
	Done, I addressed the other parameters of detectKataegis() and added more detailed explanation of the output.
o	Usually, any packages used in the vignette are loaded in a chunk visible to users
	Done
o	If your paper isn't available yet it's probably better to have no link than to link to Google which will be confusing for readers
	Done
o	In general, any results/errors/warnings should not be hidden so that user output matches what is in the vignette. If there is a reason to hide things it should be mentioned in the text that this has been done.
	Done, all code chuncks show the resulting output and not errors or warnings are supressed.
-	Man pages
o	It is recommended to add a package man page
	Done
-	Code
o	Accessor function should be used rather than @ or slot() (except when the object comes from another package which does not provide them)
	Done, except for cptChromosome@cpts (file: function_performChangepointDetection line 67) as Changepoint::cpts() does not give the same output as object@cpts so I still use object@cpts in this case. Also maf@data (file function_importGenomicVariants line 73) as maftools does not provide a getter method for this slot.  I also kept object@slot in the tests (is this ok?) I prefer this for readability.
o	You should allow users to provide a BiocParallel rather than just a number of workers, this allows the user to control how the parallelisation is done
	Done
o	You should provide an exported constructor function for any exported objects
	Done
o	Using pipes in functions can make debugging difficult, I would try to avoid this
	Using pipes makes debugging more difficult indeed as debug() becomes basically useless. However, I still really like using pipes for keeping my code clean and readable.
-	Question:
o	browseVignettes("katdetectr") does not work when the vignettes are placed in the vignettes directory. How does a user easily access the vignette of katdetectr?

**Comment by daanhazelaar** [comment]
Dear @lazappi ,

I have addressed your comments and summed up my reply or solution in the previous comment. I'm curious towards your feedback.

Kind regards,
Daan Hazelaar

**Comment by lazappi** [comment]
> * Please address as many of the notes from BiocCheck::BiocCheck() as possible
>   o	NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials).
>   	I’m subscribed for the Bioc-Devel mailing list

If this is happening locally it's ok, if it's happening on the build system it will need to be looked into

>   o	Usually, the BugReports URL points directly to the GitHub issues page
>   	Done

I think here I meant `https://github.com/ErasmusMC-CCBC/katdetectr/**issues**` but it's not a big deal

> * Package data
>   o	Could you access the APL_primary.maf file directly from {maftools} rather than copying it?
>   	I also use this file for many of the unit tests. If the maintainer of maftools decides to make an adjustment to this file than my test will likely fail. Therefor I prefer keeping it as it is now.

Hmmm...ok. I still think it's better not to duplicate things and the file is probably unlikely to change but I can see this could be an issue.

> * Documentation
> * Vignette:
>   o	Please add a table of contents
>   	Done

I can't see this. You need to set `toc: TRUE` in the YAML frontmatter.

>   o	Please add an Introduction section. This should include: Motivation for inclusion in Bioconductor. Comparison to similar packages (if applicable)
>   	Done, I included this in the introduction. However, we are working on publishing an application note for katdetectr which includes extensive performance evaluation of katdetectr and other kataegis detection packages (maftools, seqkat, ClusteredMutations, Kataegis and SigProfilerClustered). When this paper is published, I will of course link to this paper in the vignette. I personally think it’s not necessary to include performance evaluation / comparison to other packages in our vignette.

No, you definitely don't need to include a full performance comparison here. We just want maintainers to acknowledge existing similar packages and mention any important differences between them and the new package.

>   o	Please add an Installation section. This should use Bioconductor installation instructions and NOT be evaluated.
>   	Done

I think suggesting people install development versions from GitHub is a bit of a grey area. Once the package is accepted both the development and release versions will be available from Bioconductor. (sidenote: you only need the **{remotes}** package to install from GitHub rather than the (much bigger) **{devtools}** package).

>   o	Accessor function should be used rather than @ or slot() (except when the object comes from another package which does not provide them)
>   	Done, except for cptChromosome@cpts (file: function_performChangepointDetection line 67) as Changepoint::cpts() does not give the same output as object@cpts so I still use object@cpts in this case. Also maf@data (file function_importGenomicVariants line 73) as maftools does not provide a getter method for this slot.  I also kept object@slot in the tests (is this ok?) I prefer this for readability.

There are some potential problems with using `@` in tests which is that if something changes in the getter function that won't be transferred to your tests and you could get results that don't match what would happen for a user.

>   o	You should allow users to provide a BiocParallel rather than just a number of workers, this allows the user to control how the parallelisation is done
>   	Done

Generally it's best to use `BiocParallel::SerialParam()` as the default because it should be fine on any system and doesn't accidentally use multiple cores.

> * Question:
>   o	browseVignettes() does not work when the vignettes are placed in the vignettes directory. How does a user easily access the vignette of katdetectr?

That should work but you probably have to fully install the package. Personally I usually find it easier to look at the rendered version on the Bioconductor website but this should also work. 

I think you are pretty close, just a few minor things. Just so you know I will be going on leave next week so likely won't be able to make any further comments until mid-July (possibly later).

**Comment by daanhazelaar** [comment]
Dear @lazappi 

Thanks for your reply. I'll implement your comments. I hope you have a great time on your leave. 

Do you think you'll be able to review katdetectr if I implant your comments today? I'll be giving a presentation regarding katdetectr and its performance comparison next week Wednesday. It would be great if I can add a slide with: accepted on Bioconductor! 🎉

Kind regards
Daan Hazelaar

**Comment by lazappi** [comment]
If you can make changes today I will try to look at it one more time but no guarantees it will be approved by then.

**Comment by daanhazelaar** [comment]
Dear @lazappi 

It would be great if you can find the time for a review before your leave. Regardless, I hope you have a nice time on your leave!

Hereby my reply to your comments:

•	Regarding my subscription to the Bioc-Devel mailing list. The build system does recognise me as a subscriber.

•	I added a link to the issues page of katdetect. I thought I did that already but now it’s there for sure.

•	Regarding the MAF data set from maftools. I hope it’s ok to keep it as is.

•	I added toc:TRUE to the YAML frontmatter.

•	In the vignette I have acknowledged all other kataegis detection packages I know off. Which are also included in our performance evaluation.

•	I removed the github install suggestion from the vignette and the README.md

•	I replaced all @ symbols with its corresponding getter function in the tests

•	I replaced BiocParallel::MulticoreParam(workers = 1) with BiocParallel::SerialParam()

•	I removed the browseVignettes() suggestion from the README.

Kind regards,
Daan Hazelaar

**Comment by lazappi** [comment]
> • I added toc:TRUE to the YAML frontmatter.

The `toc: TRUE` needs to go under the output type, so something like:

```yaml
output:
  BiocStyle::html_document:
    toc: true
```

You should be able to see the contents in the rendered vignette if it has worked correctly.

> • I replaced BiocParallel::MulticoreParam(workers = 1) with BiocParallel::SerialParam()

I think it's probably best to do that in the tests as well.

**Comment by lazappi** [comment]
Hi @daanhazelaar 

I am going to approve this now and trust you to make these final minor changes. Congratulations on getting **{katdetectr}** into Bioconductor 🎉 ! It can take a couple of days to be picked up by the build system but then should be available in Bioconductor devel.

**Comment by daanhazelaar** [comment]
Hi @lazappi!

Great to hear! I'll implement these minor changes immediately. Thank for your time and effort.

Enjoy your leave!

Kind regards,
Daan Hazelaar

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/daanhazelaar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("katdetectr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/katdetectr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
