### ISSUE TITLE
ATACseqTFEA

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#2679]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/ATACseqTFEA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Why does the "Real data" section of vignette have no results?

**Comment by jianhong** [comment]
> Why does the "Real data" section of vignette have no results?

The Real data section is used for user to copy and run. There is no real data included in the package. Should I remove that session?

Jianhong.

**Comment by jianhong** [comment]
Hi @vjcitn @ococrook,
I have trouble in removing the warning message:
Warning message:
replacing previous import ‘utils::download.file’ by ‘restfulr::download.file’ when loading ‘rtracklayer’ 

Do you have any suggestion?

Jianhong.

**Comment by ococrook** [comment]
Hi @jianhong 

Looks liked you worked it out. I'll start review the package shorlty. It will probably take me up to 10 days to go through the package. Do let me know if you have any deadlines, however. 

Best wishes,
Olly

**Comment by jianhong** [comment]
Hi @ococrook

 Thank you for your help. No rush at all. I did not resolve the issue. They just be skipped by the building system.

Jianhong.

**Comment by ococrook** [comment]
Hi @jianhong, could you try and trigger another build so that we can see the build reports? I managed to build on linux and windows without problems so should be fine. Otherwise, the package looks good and I found very few concerns. Could you take a look at the review and implement the suggestions. If something is not possible please write a note explaining why. Remember to bump version numbers.

# Description

- [ ] Please fix the license, it doesn’t make sense to have a variable license option.

# Namespace

Looks good

# News.md

Looks good

# Readme.md

Please add contribution guidelines

Please add reporting bug/issues guidelines

# R code

- [ ] Methods and classes should have a dedicated file name, please see 15.2.4 https://contributions.bioconductor.org/r-code.html

- [ ] If you get a change the code could be tidied, more white space, new arguments on new lines etc. I generally found the code quite cluttered.

- [ ] In `reduceByPercentage`, I’m not excited about the whilte(TRUE) usage. If there is a bug this could end up running forever. Is there any way to avoid this?

- [ ] Please do not print a ggplot object within a function, the functions should return a ggplot object which is then printed to the console (outside the function)

- [ ] If any of the for loops can be replaced with an appropriate apply that would be excellent

- [ ] It is quite difficult to read a do.call with an lapply inside, consider separating

- [ ] If any functions can be broken up that would be great, some of them are quite long 

- [ ] The `show` for the TFEAresults is quite long, I think this should be a smaller indication of what’s in the results


# Man files

- [ ] The package would benefit from a package documentation file

# Extdata

- [ ] There is quite a lot going on in this subdirectory without any indication of what these files actually are. It would be good to add a readme so that people can navigate the origin and purpose of these files

# Vignette

- [ ] Please use bioconductor style 

- [ ] Please add bioconductor install instruction but set eval = FALSE

- [ ] View results is missing any explanation

- [ ] Please remove any uncommented code, if you wish to do this put it in a new chunk and set eval = FALSE, explaining that it is not evaluated and what it does

- [ ] There is quite a bit of bespoke code in the vignette, which is unnecessarily complicated to expose to the user. Helper functions would be great here.

- [ ] Real data section is missing explanation

- [ ] Load all libraries used at the beginning of the file.

**Comment by jianhong** [comment]
@ococrook,

 Thank you for your detailed comments. I will try to address all the issues soon.

Jianhong.

**Comment by jianhong** [comment]
@ococrook 
I will update the package soon. Here I list the changes according your comments. Sorry for the lots of changes in the updates.

> # Description
> * [x]  Please fix the license, it doesn’t make sense to have a variable license option.

I updated the license from 'GPL (>=2)' to 'GPL-3'

> # Readme.md
> Please add contribution guidelines
> Please add reporting bug/issues guidelines

I add additional sections with guidelines for bug report and contribution.

> # R code
> * [x]  Methods and classes should have a dedicated file name, please see 15.2.4 https://contributions.bioconductor.org/r-code.html

I split the class and method into three files: R/AllClasses.R, R/AllGenerics.R, and methods-TFEAresults.R.

> * [x]  If you get a change the code could be tidied, more white space, new arguments on new lines etc. I generally found the code quite cluttered.

I insert more spaces and newlines to the functions.

> * [x]  In `reduceByPercentage`, I’m not excited about the whilte(TRUE) usage. If there is a bug this could end up running forever. Is there any way to avoid this?

I use loop count no more than `MAX_LOOPS` to control the nested loops.

> * [x]  Please do not print a ggplot object within a function, the functions should return a ggplot object which is then printed to the console (outside the function)

`ggplot` is returned for the `plotES` function.

> * [x]  If any of the for loops can be replaced with an appropriate apply that would be excellent

The `for` loops are replaced by `vapply` when calculate the enrichment score.

> * [x]  It is quite difficult to read a do.call with an lapply inside, consider separating

The scripts were split into two lines.

> * [x]  If any functions can be broken up that would be great, some of them are quite long

The `TFEA` function were broken into multiple functions.

> * [x]  The `show` for the TFEAresults is quite long, I think this should be a smaller indication of what’s in the results

The `show` outputs are simplified.

> # Man files
> * [x]  The package would benefit from a package documentation file

Man page for the package was add.
 
> # Extdata
> * [x]  There is quite a lot going on in this subdirectory without any indication of what these files actually are. It would be good to add a readme so that people can navigate the origin and purpose of these files

A readme file and a help page were add into the package.

> # Vignette
> * [x]  Please use bioconductor style
Use `BiocStyle::html_document` to create the html page.

> * [x]  Please add bioconductor install instruction but set eval = FALSE
`Installation` section was appended.

> * [x]  View results is missing any explanation
Add more explanation for that section.

> * [x]  Please remove any uncommented code, if you wish to do this put it in a new chunk and set eval = FALSE, explaining that it is not evaluated and what it does
The scripts were moved to `inst` folder.

> * [x]  There is quite a bit of bespoke code in the vignette, which is unnecessarily complicated to expose to the user. Helper functions would be great here.
I cleaned the scripts.

> * [x]  Real data section is missing explanation
The scripts were moved to `inst` folder.

> * [x]  Load all libraries used at the beginning of the file.
Move all the loading to the beginning of the file.

Jianhong

**Comment by ococrook** [comment]
Thanks Jianhong this looks good! I have one more request, could you change the name of the file of

`privateUtility.R` to something like `internal-utils.R`. This is because private means something very specific in programming languages which isn't relevent here.

Before, I move to accept I would want to see the build reports for windows and mac @lshep, do you know why I can't see them?

Best wishes,
Olly

**Comment by jianhong** [comment]
@ococrook 
Thank you for your review. I changed the file name. I don't know why there is no building for windows and mac. I developed the package in a mac machine. I also want to know the building output for windows.

Jianhong.

**Comment by ococrook** [comment]
@jianhong Can you update the version and push to bioconductor again? I'll have a look at the build report but I've built locally on windows and everything looks fine, so I'll probably suggest to accept the package shortly

**Comment by ococrook** [comment]
Thanks for the fixes, looks good to me!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jianhong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ATACseqTFEA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ATACseqTFEA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
