### ISSUE TITLE
(inactive) WebGestalt

### ISSUE THREAD

**Issue by wangj26** [Bioconductor/Contributions#269]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wangj26/WebGestalt

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by wangj26** [comment]
I have uploaded the new version. When can Bioconductor run the new version again?

**Comment by mtmorgan** [comment]
Trigger a new build by incrementing the version to 0.99.1

**Comment by mtmorgan** [comment]
## Good!

- R CMD build works fine.
- R CMD install works fine.
- R-dev CMD Stangle WebGestalt.Rnw 

        source('WebGestalt.R', echo=TRUE, max=Inf) # Runs fine

## General

- As I understand it, the source code for GSEA.jar is not
  available. It is not consistent with the open-source nature of _R_
  and _Bioconductor_ to interface with closed source tools. For this
  reason, I do not think use of GSEA.jar is appropriate, and this
  should be removed from your package.

## Build report

- Follow standard formatting, as indicated by the build report

    NOTE: Consider shorter lines; 494 lines (18%) are > 80 characters
      long.

    NOTE: Consider 4 spaces instead of tabs; 1911 lines (69%) contain
      tabs.

    NOTE: Consider multiples of 4 spaces for line indents, 275
      lines(10%) are not.

- Follow these notes from the build report

    NOTE: Consider adding these automatically suggested biocViews: GO

    NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.

## DESCRIPTION

- remove unused data.table dependency
- rjson, pkgmaker are probably not needed by the 'end user'. Probably
  pkgmaker belongs in the 'Suggests:' field, and 'rjson' belongs in
  'Imports:'.
- It seems like the package has a system requirement for Java. This
  should be indicated in the Description file using the
  SystemRequirements: tag.
- Please use the Description: tag to provide a more comprehensive
  description of your tool, e.g., the specific approach to gene set
  analysis it uses, and how it differs from the implementations
  available in other packages, and how it can be used in conjunction
  with other _Bioconductor_ packages in an overall work flow.
- Use standard spacing and formatting, e.g., for the Description,
  break at 80 characters
  
          Description: WebGestalt R package is the R version of our well-known
            web application tool WebGestalt (www.webgestalt.org). The
            advantage of this R package is it can be integrated to other
            pipeline or simultaneous analyze multiple gene lists.
        
- The package does not make use of other _Bioconductor_ packages, for
  instance GSEABase for working with gene sets. Please justify.

## NAMESPACE

- is pkgmaker used in the package, or rather for unit tests or when
  building your package? If the later then it does not need to be
  imported.
- Format lines to a maximum of 80 characters.

          export(WebGestalt, IDMapping, GOSlimSummary, listGeneSet, listIDType,
              listOrganism, readGMT, listReferenceSet)
          
## Vignette

- long code lines do not wrap in pdf output; format your code so that
  it is readable in the PDF output.
- Your vignette is now a collation of man page 'references'. It needs
  to be revised to provide the user with a narative description of how
  the package is used. Ideally, it will indicate how your software
  integrates with other Bioconductor packages in a typical work flow.
- Please review the LaTeX style files at the top of the vignette,
  carefully deciding whether they are relevant to your vignette.
- The `\VigettePackage{}` tag reference NetSAM, which is not correct.
- The text before the `\title` tag results in a confusing
  document. Maybe you mean for this to be a `\begin{abstract}
  ... \end{abstract}` chunk after `\maketitle`?
- Please update the installation instructions to reflect its
  acceptance in _Bioconductor_. It is not necessary to manually
  install dependencies, but rather
  
        source("https://bioconductor.org/biocLite.R")
        biocLite("WebGestalt")
- Use a temporary directory (`tempdir()` or `dir.create(tempfile())`)
  rather than the working directory for vignette (and example)
  calculations.
- Use different names for chunk labels (all are currently named
  `Example`, `<<Example>>=`) to help localize compilation problems.
- Format your code appropriately; long lines simply spill off the
  printed page and are therefore meaningless to your users.

## man

- Wrap code in examples so that they display appropriately.

## R 

- (WebGestalt.R:597) Do not use system dependencies such as `tar`; use
  _R_'s bult-in `tar()` / `untar()`.
- Please format your code in a consistent manner, following standard
  indentation and spacing. This greatly increases the ability of
  another person to follow your code. See the
  [Bioconductor style guide][1] for suggestions.
  
[1]: http://bioconductor.org/developers/how-to/coding-style/

- Setting `options(stringsAsFactors=FALSE)` is changing the default
  user environemnt settings.  This is not the correct way of going
  about it, as you'd have to set it back to the default after you are
  done with this option. Even though you set the option, you still use
  an explicit argument everytime you call `stringsAsFactors` where you
  use the `data.frame`. Please avoid setting global variables, and
  remove `options(stringsAsFactors=FALSE)`.
- Signal errors with

        stop("'is.output' should be logical(1)")

  Instead of printing error messages and returning to the main program
  (WebGestalt.R:37)
  
		error <- "is.output should be an R logical object (TRUE or FALSE)!\n"
	    cat(error)
        return(error)

- Avoid using `cat()` to communicate with users. Instead use
  `message()`, which directs output to the error stream. Use
  `warning()` to signal conditions that are incorrect but do not cause
  your code to stop.
- Consider using a templating package to create report and other
  templates (e.g., WebGestalt.R:960), e.g., [whisker][]

[whisker]: https://cran.r-project.org/package=whisker

- Parts of your code like the following, follow a very procedural
  style, and can be made much shorter if you wrote helper
  functions. For instance, GoSlibSummary.R:28-48

          bpfile1 <- tapply(bpfile[,1],bpfile[,2],length)
          ccfile1 <- tapply(ccfile[,1],ccfile[,2],length)
          mffile1 <- tapply(mffile[,1],mffile[,2],length)
          
          bpfile1 <- bpfile1[bpfile1>0]
          ccfile1 <- ccfile1[ccfile1>0]
          mffile1 <- mffile1[mffile1>0]
          
          bpfile <- unique(bpfile[,c(2,3)])
          ccfile <- unique(ccfile[,c(2,3)])
          mffile <- unique(mffile[,c(2,3)])
          
          bpfile1 <- data.frame(goacc=names(bpfile1),genenum=bpfile1,stringsAsFactors=FALSE)
          ccfile1 <- data.frame(goacc=names(ccfile1),genenum=ccfile1,stringsAsFactors=FALSE)
          mffile1 <- data.frame(goacc=names(mffile1),genenum=mffile1,stringsAsFactors=FALSE)
          
          colnames(bpfile) <- c("goacc","goname")
          colnames(ccfile) <- c("goacc","goname")
          colnames(mffile) <- c("goacc","goname")
          
          bpfile <- merge(x=bpfile,y=bpfile1,by="goacc")
          ccfile <- merge(x=ccfile,y=ccfile1,by="goacc")
          mffile <- merge(x=mffile,y=mffile1,by="goacc")
          bpfile <- bpfile[order(-bpfile[,3]),]
          ccfile <- ccfile[order(-ccfile[,3]),]
          mffile <- mffile[order(-mffile[,3]),]
          
  could be written with a helper function
  
        .merge_helper <-function(file) {
            file <- tapply(file[,1], file[,2], length)
            file <- file[file > 0]
            file <- unique(file[, c(2, 3)])
            ...
         }
         bpfile <- .merge_helper(bpfile)
         ccfile <- .merge_helper(ccfile)

  Similar changes can be made to other parts of your code, e.g., the
  plotting functions later in GOSlimSummary.R.
- Please limit the use of `!` in your messages; it scares the users!!
- Please choose a more modest welcome banner in `.onAttach()`; users
  load many packages and do not need the extra clutter.
- Use of `return()` is optional in _R_, and in this case seems to
  clutter the code (e.g., readGMT.R:18)
- Be sure to remove any itermediate files from user results, e.g., the
  tar.gz file.

**Comment by wangj26** [comment]
Hi mtmorgan,

Thank you for your review!

For the GSEA question, because GSEA only provides jar file that can integrate to other workflow, if we want to include this most famous enrichment analysis tool into our R package, do you mean we can not publish our package in the Bioconductor?

Thanks

**Comment by wangj26** [comment]
Hi mtmorgan,

Thank you for your kindly review!

For the GSEA comment, whether can we add some description in somewhere to show how to look at the java source code from jar file like http://stackoverflow.com/questions/11271138/how-to-view-the-source-code-inside-a-jar-file?

I just went through the bioconductor to see whether we can use some R version GSEA. But, I found that although some packages say they support GSEA (e.g. EnrichmentBrowser), they just use the simple ks test instead of the permutation method to get the p value, which is incorrect and does not consider the bias of gene set size. Only using the real GSEA package can perform the correct analysis and get the correct results. GSEA website (http://software.broadinstitute.org/gsea/downloads.jsp) only provides java jar file as the only way to integrate GSEA to other pipelines.

If publishing in the Bioconductor, our package will be the unique one to perform the real GSEA analysis that is the most popular tool in the area of enrichment analysis. 

Please let me know whether our package can be published in Bioconductor if we have the jar file.

Thanks,

**Comment by mtmorgan** [comment]
We will not wrap a closed-source tool in Bioconductor, so you must find another solution.

**Comment by wangj26** [comment]
Thank you for all your kindly comments!

Because we want to keep the correct things, we will submit it to CRAN.

Thanks again!
