### ISSUE TITLE
imageanalysisBrain

### ISSUE THREAD

**Issue by mknoll** [Bioconductor/Contributions#270]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mknoll/imageanalysisBrain

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
My concerns with the package are that the code may be highly
inefficient, the package may not leverage existing _Bioconductor_
infrastructure, and the documentation is not sufficient to help a user
to benefit from the effort the developer has extended. I try to
indicate where these concerns come from in the following comments.

DESCRIPTION

- The Description: field should be a paragraph-length 'abstract' that
  succinctly summarizes the capabilities, strengths and weaknesses
  of this package, perhaps in comparison with other packages.
- The package makes no reference to other _Bioconductor_ packages, so
  it is not clear why this is being submitted to _Bioconductor_? In
  particular, it seems like great benefit would be had from using the
  [EBImage][] package.

[EBImage]: https://bioconductor.org/packages/EBImage

R

- (determineTissueClasses.R:20, extrFast2.R:29, elsewhere) Avoid
  `copy-and-append` in favor of [pre-allocate and fill][], especially
  `lapply()`.
- `determineTissueClasses()`: Nested iterations such as this function
  can be very inefficient, and can often be 'vectorized'. Please do so
  here and elsewhere. It's difficult to parse code and identify
  vectorization, but in `getSubclasses()` it seems like you're
  interested in assigning a particular column of `data` to a range in
  `split`; perhaps a fast solution is
  
        group <- findInterval(data[, index], split[,"key"])
        split(data, group)
        
- `getSubclasses()` It seems like the `split` argument is expected to
  be a `data.frame`, but the function only ever uses the `key`
  column. So it's very unclear why it is defined to take a data.frame
  with `key` and `value` columns instead of a vector `key`. The
  example for this function is also poorly formatted, excessively
  verbose (e.g., `y=rep(1:5, each=10)`), and provides more data than
  necessary to illustrate functionality.
- Please use meaning function names. For example, `extr()` is not
  adequate.
- `sampleData()` I doubt that parallel evaluation is necessary here;
  rather the underlying _R_ code needs to be implemented
  efficiently. The function name is very ambiguous.
  
[pre-allocate and fill]: http://bioconductor.org/developers/how-to/efficient-code/#pre-allocate-and-fill-if-iterations-are-necessary

man

- Avoid use of non-informative jargon and help pages that are not
  useful to the end user, e.g., enc2dec.Rd provides no information on
  what an encoded coordinate is, and does not indicate when a user
  might wish to use this functionality.
- Provide a meaningful description of parameter and return values. For
  instance, `enc2dec()` has parameter `values`, but it is not at all
  clear what type these 'values' are (e.g., integer()?) or what
  constraints exist (`values` must be the same length as `enc`, I
  think?). Augment the description of a return value as `data.frame()`
  or `list()` with a description of the columns of the data.frame or
  elements of the list.
  
  For all help pages, follow the basic convention to document
  parameters as variable-data type-description,
  
        @param x character(1) Description of x.

- Please adopt standard _R_ typographical convention in man page
  examples, e.g., spaces around `<-` (enc2dec.Rd), consistent use of
  `<-` rather than mixing with `=` (determineTissueClasses.Rd)

- Please provide meaningful examples, for instance
  `example(extrFast2)` returns a list with an empty data.frame. This
  is obviously not informative to a user trying to understand the
  function.

vignettes

- The vignette is not satisfactory. It currently consists of large
  code chunks. The code chunks consist of large parts that are not
  evaluated (`if (FALSE) ...`) and that contain abstruse _R_
  programming paradigms `do.call(rbind, lapply(...))`. It is unclear
  from the vignette what functionality the package provides, why the
  user would want to use it, what the data inputs are, and how the
  user would apply the functionality of the package to their own
  data.
  
  An appropriate vignette provides text, code, and results (e.g.,
  summary output and figures) that walk the user through a typical use
  case. There are many examples in _Bioconductor_; an exemplary one is
  [DESeq2][].
  
[DESeq2]: https://bioconductor.org/packages/DESeq2

**Comment by mtmorgan** [comment]
Any progress on these revisions, or shall we close the issue?

**Comment by mknoll** [comment]
Thanks a lot for the feedback - the mentioned points are really helpful. 

I'm still working on the different issues.

**Comment by mtmorgan** [comment]
Is this package ready for completing the review process? If so please commit a 'version bump' from 0.99.1 to 0.99.2 to trigger a new build.

**Comment by mknoll** [comment]
> DESCRIPTION
- The description field was rewritten. 
- The package was redesigned, a central class was introduced which stores imageing data an inherits from the EBImage::Image class

> R
Most loops were removed.
Not all key/val data.frames are yet eleminated -> TODO.
Functions were refactored with more meaningful names. 
The sampleData function name was changed to identifyMinima.
Several calls to internal functions / objects were introduced to speed up calculations -> several WARN

> man
I'm still adapting the man pages according to the suggestions -> TODO.

> vignettes
The main vignette was shortened and code split into smaller chunks.

**Comment by mtmorgan** [comment]
There hasn't been any activity here so I'll close the issue; re-open it when you're ready for the review to continue.
