### ISSUE TITLE
signifinder

### ISSUE THREAD

**Issue by SPirrotta** [Bioconductor/Contributions#2701]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CaluraLab/signifinder

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
@nilseling Please take the lead on this review.  thank you

**Comment by nilseling** [comment]
Thanks @lshep, will do and post my review soon.

**Comment by nilseling** [comment]
Hi @SPirrotta,

thanks for submitting `signifinder`. In general it's a nicely written package. There are a few things that need to be addressed/clarified:

## General comments

- [x] please add the Bioconductor installation instructions to the README file upon acceptance
- [x] please exclude the `IPSOVSign` function as it does not contain functional code 
- [x] it is recommended to prefix non-exported functions with `.` (e.g., `.myFunction`)
- [x] the signature functions but not the plotting functions support `Seurat` objects. Please be consistent when supporting `Seurat` objects across the package.
- [x] it is not fully clear which data transformation steps are used for the individual signatures. Please consider adding an additional column to `availableSignatures` that lists the data transformation step.
- [x] you can consider moving `fakeData` into `UtilityFunctions.R`

## Documentation 

**General comments:**

- [x] please check the vignette and man pages for typos and grammar.
- [x] it is encouraged to add a package level man page that gives users relevant information when calling `?signifinder`

**Vignette:**

- [x] Introduction: it is now recommended to include a motivation for inclusion into Bioconductor
- [x] Introduction: it might be beneficial to explain how these signatures were selected for inclusion into `signifinder`
- [x] Introduction: if applicable, please mention similar R packages that compute tumor signatures
- [x] all code chunks in the vignette need to be runnable. Please remove `eval=FALSE`
- [x] be consistent with the use of `knit::kable` and `echo=FALSE`
- [x] for readability, please be consistent when using code highlighting for functions, variables and packages
- [ ] it might be beneficial to highlight the use of a previously fitted survival model as input to the `survivalSignPlot` function as the description states:

```
Description
It creates survival curves from either a formula (e.g. the Kaplan-Meier), a previously fitted Cox model, or a previously fitted accelerated failure time model.
```

**Man pages:**

- [x] please indicate which entries to `nametype` are allowed
- [x] please adjust the documentation of the returned value to indicate that the returned object is of the same `class` as the input object.

```
Value
A SummarizedExperiment object in which the Epithelial and Mesenchymal scores are added in the colData section.
```

- [x] the `heatmapSignPlot` function contains an unclear description of the `data` argument. It appears the second sentence is obsolete? 

```
data	
An object of type SummarizedExperiment coming from signatures functions. Th function takes as input a matrix where each row represents a signature and each column represent a samples.
```

- [x] similar as above, there are inconsistencies between the description and the `data` argument in the documentation of the `correlationSignPlot` function 

```
Description
Given a matrix of multiple signatures, the function gives the opportunity to observe signatures correlates between each other.

data	
An object of type SummarizedExperiment coming from signatures functions.
```


## The DESCRIPTION file

- [x] the `LazyData:` entry should be set to false or removed
- [x] please consider adding more biocViews from e.g. [BiologicalQuestion](https://bioconductor.org/packages/devel/BiocViews.html#___BiologicalQuestion) or [ResearchField](https://bioconductor.org/packages/devel/BiocViews.html#___ResearchField)
- [ ] please add a `BugReports`  and `URL` field.

## The NEWS file

- [x] it is recommended to add a `NEWS` file
	  
## Package data

- [ ] the `ovse` dataset is not properly documented. Please provide instructions for its creation, source information e.g. in form of a citation and its entries. 
- [x] the first assay name of `ovse` is empty. Please consider providing an informative name such as `counts`.
- [x] the variables in `R/sysdata.rda` need to be documented in `inst/script/`. It can be executable code, pseudo code, or a text description and needs to describe how the variables were generated and what they contain.

## Unit tests

- [ ] please consider increasing the package coverage by adding unit tests for the plotting functions.

```
signifinder Coverage: 53.84%
R/Plots.R: 0.00%
R/UtilityFunctions.R: 62.36%
R/SignatureFunction.R: 75.82%
R/fakeData.R: 77.78%
```

- [x] the internal function `fakeData` can be directly accessed without the need to call it via `signifinder:::fakeData`

## R code

- [x] NOTE: Avoid sapply(); use vapply()
- [x] NOTE: Avoid using '=' for assignment and use '<-' instead
- [ ] it is not recommended to use `::` for accessing functions and import all needed functions via `@importFrom`
- [x] for code consistency, please avoid line breaks after the assignment operator when possible

**Comment by nilseling** [comment]
Hi @SPirrotta,
we would like to continue with the revision process and usually expect changes to the package within 2-3 weeks. Would you be able to post the requested changes soon?

**Comment by SPirrotta** [comment]
Hi Nils,
I have not yet been able to complete all the changes to the package. I will publish the ones I have already made today or tomorrow. Then, I’ll send the others as soon as I can.
Thank you.

**Comment by nilseling** [comment]
Hi @SPirrotta 
I'm closing this for now. Please re-open once you are ready to submit the requested changes.

**Comment by SPirrotta** [comment]
Hi,
I completed all the requested changes:

### General comments

- Bioconductor installation instructions added to the README file
- IPSOVSign function added
- Non-exported functions prefixed with .
- Seurat objects are not supported anymore by any function
- An additional column is added to availableSignatures that lists the data transformation steps.
- .fakeData moved into UtilityFunctions.R

### Documentation
**General comments:**

- Vignette and man pages checked for typos and grammar
- Package level man page added

**Vignette:**

- Motivation for inclusion into Bioconductor included
- Explanation of how these signatures were selected for inclusion into signifinder added
- Similar R packages mentioned
- eval=FALSE removed
- knit::kable and echo=FALSE are now consistent
- Code highlighting used for all functions, variables and packages
- description of survivalSignPlot function input improved

**Man pages:**

- Entries to nametype stated
- Documentation of the returned value adjusted
- Description of the data argument inside heatmapSignPlot function adjusted
- Description of the data argument inside correlationSignPlot function adjusted

### The DESCRIPTION file

- LazyData set to false
- More biocViews added
- BugReports and URL field added

### The NEWS file

- NEWS file added

### Package data

- Instructions on how to create the ovse dataset are now present in inst/scripts/howToGenerateOvse.Rmd
- The first assay of ovse is now called ‘counts’
- Variables in R/sysdata.rda documented in inst/script/datamanuallycurated.txt

### Unit tests

- Unit tests for the plotting functions added
- the internal function .fakeData is now directly accessed and not via signifinder:::fakeData

### R code

- All the sapply() are substituted by vapply()
- All '=' for assignment are substituted by  '<-'
- All needed functions are imported via @importFrom
- All line breaks after the assignment operator are removed

I am ready now to reopen the issue.

**Comment by nilseling** [comment]
Hi @SPirrotta,

thanks for submitting the changes. I'll reopen the issue and go through the package next week.

**Comment by nilseling** [comment]
Hi @SPirrotta 
could you please push your changes to Bioconductor to trigger a new build?

**Comment by nilseling** [comment]
Hi @SPirrotta 

thanks for adding the changes. I have ticked off the points that have been addressed. However, there are still a couple of things that need to be addressed:

- [x] Please fix the issue when using `vapply`. For example, in line 1208 in `SignatureFunctions.R` the `vapply` function expects an integer vector of length 1. However, when running the examples, a vector of length 40 is returned.
- [x] In the `.getMatrix` function, the ` userdata <- as.matrix(assay(userdata))` call defaults to the first assay entry in the object. Is this intended or do you want to give the user the choice to specify which assay to use?
- [x] It is recommended to use `is` instead of `class`. E.g. in the `.getMatrix` function.
- [x] Please adjust the vignette to describe the additional `transformationStep` column.
- [x] You can consider to add an explanation on how the statistics in the `survivalSignPlot` function is computed. 
- [x] In the `DESCRIPTION` file the `BugReports` entry should be `https://github.com/CaluraLab/signifinder/issues` and the URL entry should be `https://github.com/CaluraLab/signifinder`
- [x] The package version in the `NEWS.Rd` file does not match the package version in `DESCRIPTION`.
- [x] Please add more info explaining the `ovse` dataset. All relevant information should be contained in the `data.R` documentation. E.g. it is not clear that the data were extracted from TCGA.
- [x] You have now increased the package coverage but 40% of lines are not covered. This is not strictly enforced but on the long run, please consider adding more unit tests. 

```
signifinder Coverage: 63.55%
R/Plots.R: 38.40%
R/UtilityFunctions.R: 71.16%
R/SignatureFunction.R: 75.58%
```

- [x] Please make sure to import functions via `@importFrom` rather than `pkg::function`. There are still quite a few cases (e.g. `AnnotationDbi::mapIds`, `org.Hs.eg.db::org.Hs.eg.db`, `viridis::magma`) where this is not the case.
 
 Please let me know once you have addressed these points and we can proceed with the acceptance.

**Comment by nilseling** [comment]
Hi @SPirrotta 
I just quickly wanted to check in if you'd like to address the last couple of changes before the deadline on the 26.10. next week?

**Comment by SPirrotta** [comment]
Hi @nilseling,
I am working on it. I should be able to submit everything before the 26th.

**Comment by nilseling** [comment]
Hi @SPirrotta 
thanks for the update. Keep in mind that that package needs to be accepted before the 26.10 (https://bioconductor.org/developers/release-schedule/). I'll do my best to directly have a final check but will need a bit of buffer time.

**Comment by SPirrotta** [comment]
Hi @nilseling ,
here you can see my last changes:

- Issues when using vapply fixed
- Now, functions expect an assay called “norm_expr”
- "class" substituted with "is"
- Description of the transformationStep column added in the vignette
- More info on the statistics in the survivalSignPlot function added
- BugReports and URL In the DESCRIPTION file adjusted
- Now, the package version in the NEWS.Rd file matches the one in DESCRIPTION
- More info explaining the ovse dataset added in data.R
- I will add more unit tests as soon as it will be possible
- All functions now are imported via @importFrom rather than pkg::function

Thank you.

**Comment by nilseling** [comment]
Hi @SPirrotta 

thanks for making these changes! I will now accept the package.
One thing that I noticed for future reference is that 

```
if (is(userdata)[1] %in% c(
            "SpatialExperiment",
            "SummarizedExperiment",
            "SingleCellExperiment")) {
```
can be simply replaced by

```
if (is(userdata, "SummarizedExperiment")) {
```

as `SingleCellExperiment` and `SpatialExperiment` inherit from `SummarizedExperiment`.

**Comment by SPirrotta** [comment]
Hi @nilseling,
thank you so much for the help and advice!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SPirrotta.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("signifinder")`. The package 'landing page' will be created at

https://bioconductor.org/packages/signifinder

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
