### ISSUE TITLE
crisprVerse

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#2735]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/crisprVerse/crisprVerse

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment]
Few minor comments below! Note that many are suggestions and not strictly  
required (e.g., "consider..."). Please comment back here with what has/not been  
addressed. Cheers!

# vignette

- [ ] Type in line 33: adn -> and
- [ ] To highlight / distinguish the name from the package "crisprVerse",  
I'd recommend using code style for the latter (currently, it's \`..."; typo?).
- [ ] Could simplify line 25 to "[...] that can easily  
be installed with the `crisprVerse` package."
- [ ] To direct users to relevant external packages,  
rather than linking to the corresponding Github directories,  
consider using "`r BiocStyle::Biocpkg("package_name")`"  
(or `CRANpkg` or `Githubpkg`, depending on where the package sits).

# other

- [ ] In the README file, please include Bioconductor  
installation instructions using `BiocManager`.
- [ ] The DESCRIPTION file lists `crisprBwa` under `Suggests:`, however,  
I cannot see where this is being needed/used. Could be removed?
- [ ] The DESCRIPTION file lists `testthat` under `Suggests:`, however,  
there's currently no `tests/` directory. Consider adding unit tests;  
we strongly encourage them (see [here](https://contributions.bioconductor.org/tests.html))!
- [ ] *attach.R* currently checks that all `crisprX` packages (variable `pkgs`)  
are attached, and loads them otherwise; and, installing `crisprVerse` will  
install them (as they are listed as `Imports:`). However, if I'm not mistaken,  
there's currently no check to assure these are up to date. Perhaps worth  
including `BiocManager::valid(pkgs)` in `crisprVerse_attach()`?

**Comment by Jfortin1** [comment]
Thanks @HelenaLC for the fast review and great suggestions! I've now addressed all of them, and created a new function called `crisprVerse_update`, similar to `tidyverse_update` that will check if the latest versions of the packages are installed, and will install/update them if that's not the case.

**Comment by Jfortin1** [comment]
- Type in line 33: adn -> and **Fixed**
-  To highlight / distinguish the name from the package "crisprVerse",
I'd recommend using code style for the latter (currently, it's `..."; typo?). **Done**
-  Could simplify line 25 to "[...] that can easily
be installed with the crisprVerse package." **Done**
-  To direct users to relevant external packages,
rather than linking to the corresponding Github directories,
consider using "r BiocStyle::Biocpkg("package_name")"
(or CRANpkg or Githubpkg, depending on where the package sits).
other **Done**

- In the README file, please include Bioconductor
installation instructions using BiocManager. **Done**
 - The DESCRIPTION file lists crisprBwa under Suggests:, however,
I cannot see where this is being needed/used. Could be removed? **Yes, removed now**
- The DESCRIPTION file lists testthat under Suggests:, however,
there's currently no tests/ directory. Consider adding unit tests; 
we strongly encourage them (see [here](https://contributions.bioconductor.org/tests.html))! **I've now added a test similar to the test in the tidyverse package**
- attach.R currently checks that all crisprX packages (variable pkgs)
are attached, and loads them otherwise; and, installing crisprVerse will
install them (as they are listed as Imports:). However, if I'm not mistaken,
there's currently no check to assure these are up to date. Perhaps worth
including BiocManager::valid(pkgs) in crisprVerse_attach()? **I've now created a new function called `crisprVerse_update`, similar to `tidyverse_update` that will check if the latest versions of the packages are installed, and will install/update them if that's not the case.**

**Comment by HelenaLC** [comment]
-  To direct users to relevant external packages,
rather than linking to the corresponding Github directories,
consider using "r BiocStyle::Biocpkg("package_name")"
(or CRANpkg or Githubpkg, depending on where the package sits).
> I can see this in the vignette now; perhaps also doing the same in the README?
- The DESCRIPTION file lists testthat under Suggests:, however,
there's currently no tests/ directory. Consider adding unit tests; 
we strongly encourage them (see [here](https://contributions.bioconductor.org/tests.html))!
> Thanks for addressing this. Perhaps something like this ... would be more complete? Otherwise, all the test really does is check that "crisprBase" is listed under "Imports:" in the DESCRIPTION. But I can see how unit tests are a little tricky here.
```
test_that("...", {
    out <- crisprVerse_packages(include_self = FALSE)
    out <- out[grep("^crispr[A-Z][a-z]+", out)]
    expect_true(all(out %in% rownames(installed.packages())))
    expect_setequal(out, c("crisprBase", "crisprBowtie", "crisprDesign", "crisprScore"))  
})
```
- The overall coverage is still low (~35%) owing to the newly added *update.R*. Perhaps simply testing that it runs "quietly" on the Bioc build server? My intuitive guess is that since `crisprVerse_deps()` checks installed vs. Bioc versions, this should always pass when while package is being build. 
```
test_that("...", {
    str <- capture.output(crisprVerse_update())
    expect_true(length(str) == 1)
    expect_true(grepl("All.*up-to-date", str))
})
```

**Comment by Jfortin1** [comment]
Thanks @HelenaLC, here's my response:


- `I can see this in the vignette now; perhaps also doing the same in the README?`
**Done.**


- `Thanks for addressing this. Perhaps something like this ... would be more complete? Otherwise, all the test really does is check that "crisprBase" is listed under "Imports:" in the DESCRIPTION. But I can see how unit tests are a little tricky here.`

```
test_that("...", {
    out <- crisprVerse_packages(include_self = FALSE)
    out <- out[grep("^crispr[A-Z][a-z]+", out)]
    expect_true(all(out %in% rownames(installed.packages())))
    expect_setequal(out, c("crisprBase", "crisprBowtie", "crisprDesign", "crisprScore"))  
})
```
**Done.**

- `The overall coverage is still low (~35%) owing to the newly added update.R. Perhaps simply testing that it runs "quietly" on the Bioc build server? My intuitive guess is that since crisprVerse_deps() checks installed vs. Bioc versions, this should always pass when while package is being build.`

```
test_that("...", {
    str <- capture.output(crisprVerse_update())
    expect_true(length(str) == 1)
    expect_true(grepl("All.*up-to-date", str))
})
```

**Great suggestion, the test passed on the Bioc build server. Can always modify it in the future if it causes sporadic problems for some reason.**

**Comment by HelenaLC** [comment]
Nice, thanks for the prompt changes. And yes, definitely good to keep an eye out on that unit test and potentially adapt it as I'm not 100% sure about the intricacies of the build system; but for now, it seems to work as expected. - Accepted!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("crisprVerse")`. The package 'landing page' will be created at

https://bioconductor.org/packages/crisprVerse

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Jfortin1** [comment]
@HelenaLC Thank you!
