### ISSUE TITLE
(inactive) iDA submission

### ISSUE THREAD

**Issue by reesyxan** [Bioconductor/Contributions#2737]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reesyxan/iDA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Does your package build on R 4.2/Bioc 3.16?
```
> start <- Sys.time()

> sce <- iDA(sce)
1000 variable features found using scran::getTopHVGs. 

Error in (t(i - clustermeans[[k]])) %*% (i - clustermeans[[k]]) : 
  requires numeric/complex matrix/vector arguments

Enter a frame number, or 0 to exit   

1: source("iDAvignette.R", echo = TRUE)
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(ei, envir)
5: iDAvignette.R#43: iDA(sce)
6: iDA(sce)
7: .local(object, ...)
8: .iDA_core(var.data, ...)
9: WCS(splitclusters = splitclusters, diag = diag)

```

**Comment by reesyxan** [comment]
Hello,

The error is fixed now.

**Comment by lazappi** [comment]
Hi @reesyxan

Thanks for submitting **iDA** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Questionl

## General package development

- [ ] :warning: There are some notes from `BiocCheck::BiocCheck()` in the build report, please address as many of these as possible
- [ ] :warning: I got a note from `R CMD check` about **{gridExtra}** needing to be added as a suggested dependency, it doesn't seem to be on the main build report though

## DESCRIPTION file

- [ ] :warning: The `Description` field is quite long and has a lot of general introduction, have a look at the advice [here](https://r-pkgs.org/Metadata.html#description-title-description) and [here](https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file)
- [ ] :warning: It is recommended to add ORCiDs to the `Authors@R` field
- [ ] :warning: It is recommended to have a `BugReports` field, usually this is a link to your GitHub issues page or the Bioconductor support forum
- [ ] :warning: It is recommended to have a `URL` field, usually this is a link to your GitHub page or the Bioconductor package page

## NAMESPACE file

- [ ] :rotating_light: In general you should use `importFrom` instead of *import all* with `import`

## The NEWS file

- [ ] :rotating_light: You currently have a Markdown `NEWS.md` file but you use R documentation style formatting in it, the formatting and the file type should match

## The CITATION file

- [ ] :warning: You mention a publication in the vignette, consider adding a proper `CITATION` file with this information

## Documentation

### README

- [ ] :rotating_light: The images in your `README` are not linked correctly and aren't shown on the GitHub webpage

### Vignette

- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: You currently have some unevaluated code blocks, please remove these (except for the installation instructions), some of these also contain invalid code
- [ ] :rotating_light: Please rename the **Overview** section to **Introduction**
  - [ ] :rotating_light: Please add motivation for including the package in Bioconductor (using common objects, interactions with other packages, using annotations etc.)
  - [ ] :rotating_light: Please mention other packages that can be used to perform the same task and how you package compares to them (if applicable)
- [ ] :green_circle: You have some code chunks that just print timing information, I would suggest either combining this with the function code or incorporating them into the text using inline code
- [ ] :green_circle: In some places you extract information from the SCE/SE as a new variable and use it for things like computing a t-SNE, I would suggest using existing functions (for example from the **{scuttle}**/**{scater}** packages) that operate on these objects directly instead

### Man pages

- [ ] :warning: It is recommended to add a package man page
- [ ] :warning: Please check the `?iDA` man page, there is some repeated and unrelated information here
- [ ] :warning: Please check the formatting in your man pages, there are some places where the markup is incorrect and can be seen in the rendered page

## Unit tests

- [ ] :warning: Please consider adding more unit tests, particularly for the different input types (matrix/SCE/SE...)
- [ ] :warning: The naming for test files should generally match the naming of your `.R` files

## Code

### R

- [ ] :warning: Consider adding validity tests for arguments in all exported functions
- [ ] :rotating_light: I think some of your `for` loops could be replaced with `apply` statements, please check these
- [ ] :green_circle: Currently you calculate highly variable genes as part of your functions but in current workflows, this is usually done as a separate step before dimensionality reduction. I would strongly suggest modifying your functions to follow this workflow.
  - [ ] :warning: Check that the `nfeatures` argument is used properly in functions, I think there are some places where there is a hardcoded value

## Additional files

- [ ] :rotating_light: There are some additional files in `inst/`. I'm not sure what these are for but please remove them if not necessary.
