### ISSUE TITLE
EDIRquery

### ISSUE THREAD

**Issue by lauravongoc** [Bioconductor/Contributions#2758]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lauravongoc/EDIRquery

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  The package does not use any Bioconductor data structures.  A GRanges instance would probably be useful for 
```
head(results)
#> chromosome repeat_length repeat_seq start end repeat_seq2 start2
#> 3930 17 7 CCGCGGG 80101595 80101602 CCGCGGG 80101734
#> 3931 17 7 CCGAGGC 80105602 80105609 CCGAGGA 80105843
#> 3932 17 7 CGGAGGG 80110005 80110012 GCGAGGG 80110061
#> 3933 17 7 CCAAGGG 80118254 80118261 CCGAGGG 80118270
#> 3934 17 7 CCGAGGG 80118270 80118277 GCGAGGG 80118318
#> 3935 17 7 CCGAGGG 80118270 80118277 CAGAGGG 80118533
#> end2 distance ensembl_gene_id hgnc_symbol gene_range
#> 3930 80101741 132 ENSG00000171298 GAA 80101556-80119881
#> 3931 80105850 234 ENSG00000171298 GAA 80101556-80119881
#> 3932 80110068 49 ENSG00000171298 GAA 80101556-80119881
#> 3933 80118277 9 ENSG00000171298 GAA 80101556-80119881
#> 3934 80118325 41 ENSG00000171298 GAA 80101556-80119881
#> 3935 80118540 256 ENSG00000171298 GAA 80101556-80119881
#> ensembl_transcript_id transcript_range intron_exon intron_exon2
#> 3930 ENST00000302262 80101581-80101890 E1 E1
#> 3931 ENST00000302262 80105133-80105748 I2 E3
#> 3932 ENST00000302262 80109945-80110055 E9 I9
#> 3933 ENST00000302262 80118193-80118357 E18 E18
#> 3934 ENST00000302262 80118193-80118357 E18 E18
#> 3935 ENST00000302262 80118193-80118357 E18 I18
#> feature mismatch
#> 3930 same exon 0
#> 3931 spanning intron-exon 1
#> 3932 spanning intron-exon 1
#> 3933 same exon 1
#> 3934 same exon 1
```
Please consider.

**Comment by lauravongoc** [comment]
Thank you for your comment.

GRanges is not adapted for our data, as it only highlights a single range of positions, whereas each row in our data includes 2 sequences with their respective start and end positions, the distance between the two, as well as additional annotation.

**Comment by vjcitn** [comment]
How about the GenomicInteractions class?  How about using DNAString to represent your sequences?  Do you use Bioconductor with your data?

**Comment by vjcitn** [comment]
Hi, do you plan to work on interoperation of this package with Bioconductor?  Please let us know.

**Comment by lauravongoc** [comment]
Hi, apologies for the delay.

The package files in the repo have been updated with the added implementation of GInteractions class.

**Comment by ococrook** [comment]
Hi @lauravongoc 

I hope to look at this week, thank you for removing the warnings. 

Best wishes,
Olly

**Comment by ococrook** [comment]
HI @lauravongoc 

My apologies for the delay - it's be a busy month. Please see the following review before we can accept the package:

- [x] Bioconductor install instruction in the .readme and vignette
- [x] What does `sysdata.rda` in the R folder do? I imagine this needs to be remove or moved
- [x] package version should match between Descriptions and News
- [x] R to version >= 4.2
- [x] FIx a license, variable lincenses are not allowed
- [x] Do you need to import all of the packages and package functions in the NAMESPACE - export and import selectively if possible
- [x] Please add unit tests
- [ ] Avoid use of `cat` in R functions

Otherwise looks good - thank you!

**Comment by lauravongoc** [comment]
Dear @ococrook 

Thank you so much for the review, and my apologies as well for the delay.

The above points have been addressed. Concerning the 2nd point, the file `sysdata.rda` in the R directory contains internal data that is parsed by the `gene_lookup()` function if no `path` parameter with additional data is not specified.

**Comment by ococrook** [comment]
Great, thank you! Does the sysdata.rda have to be in the R folder, could it be moved to the data or inst folders?

**Comment by lauravongoc** [comment]
Dear @ococrook, 

Putting internal data in `sysdata.rda` in the R folder was done following the R Packages guidelines I referenced from Hadley Wickham & Jenny Bryan, specifically the [Data](https://r-pkgs.org/data.html) section. I cannot seem to find a way to direct the calls to this data in the function to another source folder.

**Comment by lshep** [comment]
Yes I think this is okay as long as the sysdata.rda is documented and proper indication of source/licensing referenced (if not in a man page than in a file in inst/scripts)

**Comment by ococrook** [comment]
Hi @lauravongoc 

Sorry, it looks like I got confused which data was being referred where. As suggested, could you make it clear in the package what the data is and where it came from? If I understand correctly the documentation currently there is for the data in the `/data` folder?

**Comment by lauravongoc** [comment]
Dear @ococrook

Indeed the documentation that was already there was for the data in `/data`. I have now added documentation for the sysdata.R in the `/inst/scripts/` folder as suggested.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lauravongoc.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EDIRquery")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EDIRquery

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
