### ISSUE TITLE
DNAfusion

### ISSUE THREAD

**Issue by CTrierMaansson** [Bioconductor/Contributions#2759]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CTrierMaansson/DNAfusion

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  I think
```
head(EML4_ALK_detection(file = H3122_bam, 
                        genome = "hg38", 
                        mates = 2))
#>          pos cigar     mpos
#> 726 42299657 94M2S 29223691
#> 727 42299657 94M2S 29223375
#> 728 42299657 94M2S 29223479
#> 729 42299657 94M2S 29223686
#> 731 42299657 94M2S 29223636
#> 733 42299657 94M2S 29223687
#>                                                                                                  seq
#> 726 TTGCTTCTTTCACTTAGTTTTTTTTGTTTTGTTTTGTTTGTTTGTTTTTTGAGATGGGGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGGTCT
#> 727 TTGCTTCTTTCACTTAGTTTTTTTTGTTTTGTTTTGTTTGTTTGTTTTTTGAGATGGGGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGGTCT
#> 728 TTGCTTCTTTCACTTAGTTTTTTTTGTTTTGTTTTGTTTGTTTGTTTTTTGAGATGGGGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGGTCT
#> 729 TTGCTTCTTTCACTTAGTTTTTTTTGTTTTGTTTTGTTTGTTTGTTTTTTGAGATGGGGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGGTCT
#> 731 TTGCTTCTTTCACTTAGTTTTTTTTGTTTTGTTTTGTTTGTTTGTTTTTTGAGATGGGGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGGTCT
#> 733 TTGCTTCTTTCACTTAGTTTTTTTTGTTTTGTTTTGTTTGTTTGTTTTTTGAGATGGGGTTTCACTCTTGTTGCCC
```
should not be a data frame but an instance of a class deriving from GenomicAlignments.  Would you have a look at GenomicAlignments package?  I think the Bioconductor representations may be advantageous.

**Comment by CTrierMaansson** [comment]
Hello

Hello I have changed the output of EML4_ALK_detection() to a GAlingments object. Futhermore, I have made the appropriate changes to the other functions, as well as the documentation. 

I have changed this at my GitHub repository, however I'm unsuccefull in pushing the update to git@git.bioconductor.org:packages/DNAfusion.git. 
Am I doing something wrong?

Kind regards 
Christoffer

**Comment by vjcitn** [comment]
be sure to read the FAQ about git pushing issues and consider pushing to https://github.com/bioconductor.org/packages/DNAfusion

**Comment by LiNk-NY** [comment]
Hi Christoffer @CTrierMaansson and Vince @vjcitn 
I believe once the package passes the `1. Awaiting Moderation` stage, it will be added to the Bioconductor git server.
Lori can confirm this @lshep 
Best,
Marcel

**Comment by vjcitn** [comment]
Oh, right, I have to change the labels once I look at the revisions.  Thanks @LiNk-NY !!

**Comment by vjcitn** [comment]
Even when it gets to "pre-check passed" there is a manual ingestion step needed.

**Comment by CTrierMaansson** [comment]
I'm sorry. Do I need to do anything? or do I need to wait until  @vjcitn changes the labels?

**Comment by LiNk-NY** [comment]
> I'm sorry. Do I need to do anything? or do I need to wait until @vjcitn changes the labels?

Hi Christoffer, @CTrierMaansson 
You do not need to do anything. We are a little backed up and your package will be ingested soon. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Christoffer, @CTrierMaansson 
Thank you for the submission. Sorry for the delay. 
Please see the review below. 
Feel free to post any questions. 
Best,
Marcel

---

# DNAfusion #2759

## DESCRIPTION

* Looks good.
* Are `usethis` and `devtools` needed in the `Suggests`?

## NAMESPACE

* Looks good.

## vignettes

* Avoid the code duplication and assign the output of `EML4_ALK_detection` to a
variable(s) and re-use.

## R

* Avoid using numeric indices and use named indices, e.g., `3` in
`index_helper`.
* Return an empty `GAlignments()` instead of the message "No EML4-ALK was
detected" in `EML4_ALK_detection` and check any downstream results with
`isEmpty()`.
* Optional. Minor. Consider using `BiocBaseUtils` for type checking e.g., with
`isScalarCharacter`.

## test

* It's great that you have tests. 100% coverage is quite feasible, I think.

```r
> covr::package_coverage()
DNAfusion Coverage: 87.07%
R/DNAfusion_functions.R: 87.07%
```

**Comment by CTrierMaansson** [comment]
> 
Dear Marcel

Thank you for the review!

# DNAfusion #2759

## Description

1. Are `usethis` and `devtools` needed in the Suggests?

- `usethis` has been removed from `Suggests`
- `devtools::session_info` is used in the vignettes and `devtools` is therefore in `Suggests`

## vignettes

1. Avoid the code duplication and assign the output of `EML4_ALK_detection` to a
variable(s) and re-use.

- I have now created two variables (`H3122_result` & `HCC827_result`) as the
output of `EML4_ALK_detection`

## R

1. Avoid using numeric indices and use named indices, e.g., `3` in
`index_helper`.

- This has been implemented and the package now uses named
indices, e.g., `"index"` & `"seq"`

2. Return an empty `GAlignments()` instead of the message "No EML4-ALK was
detected" in `EML4_ALK_detection` and check any downstream results with
`isEmpty()`.

- When no gene fusions are detected `EML4_ALK_detection` now returns
a empty `GAlignments` object. The downstream functions now check if
the parameter `reads` is empty using `isEmpty`. Becuase og this `S4Vectors`
has been added to the DESCRIPTION and the NAMESPACE.

3. Optional. Minor. Consider using `BiocBaseUtils` for type checking e.g., with
`isScalarCharacter`.

- A good suggestion. Where applicable `isa` has been substituted with
`BiocBaseUtils` functions. `BiocBaseUtils` has been added to the 
DESCRIPTION and NAMESPACE

## test

1. It's great that you have tests. 100% coverage is quite feasible, I think.

- The tests should now have a coverage of 100%

**Comment by LiNk-NY** [comment]
Hi Christoffer, @CTrierMaansson 

Thank you for making those changes. 
One, minor follow up:

> * `devtools::session_info` is used in the vignettes and `devtools` is therefore in `Suggests`

`devtoools` points to `sessioninfo` so it is better to simply add `sessioninfo` to the `Suggests` field.

The package looks to be in good shape for acceptance. 
Best regards,
Marcel

**Comment by CTrierMaansson** [comment]
Hi Marcel, @LiNk-NY 

Thank you!

1. `devtoools` points to `sessioninfo` so it is better to simply add `sessioninfo` to the `Suggests` field.

- Good point! I had missed this. I've made the change to the `Suggests`

Best regards

Christoffer

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/CTrierMaansson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DNAfusion")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DNAfusion

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
We had an issue processing packages -- I'm temporarily reopening so I can reprocess and get your package on the daily builders. Sorry for any confusion and delay

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/CTrierMaansson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DNAfusion")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DNAfusion

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
