### ISSUE TITLE
MaxContrastProjection

### ISSUE THREAD

**Issue by DragonDuck** [Bioconductor/Contributions#276]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DragonDuck/MaxContrastProjection

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nturaga** [comment]
Hi @DragonDuck,

Before we start the review process, could you please address this issue as specified in the [build report](http://bioconductor.org/spb_reports/MaxContrastProjection_buildreport_20170217085713.html
)? 

```
* ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

**Comment by DragonDuck** [comment]
Hi Nitesh,I've subscribed to the mailing list and addressed another minor issue in the R version dependency. I updated the version number to 0.99.1 in the hopes of triggering the build process again. Is there a problem with the mailing list subscription?Cheers,JanOn February 21, 2017 at 8:45 PM Nitesh Turaga <notifications@github.com> wrote:Hi @DragonDuck,Before we start the review process, could you please address this issue as specified in the build report?* ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by nturaga** [comment]
Hi @DragonDuck ,

It looks like your webhook is broken. Please take a look at https://github.com/Bioconductor/Contributions#additional-actions. Specifically, the part which reads:  **To debug packages commits that don't trigger a response on the corresponding issue.**

**Comment by mtmorgan** [comment]
MaxContrastProjection Package Review
==

* `R-dev CMD build MaxContrastProjection` Works fine

* `R-dev CMD INSTALL MaxContrastProjection_0.99.1.tar.gz` Works fine


## DESCRIPTION

* The `Description` item in the DESCRIPTION file should be more like
  an abstract for a paper. The current description just lists the
  methods that were implemented.

* `methods` should probably be in `Imports:`

* No need for SystemRequirements: ?

* Select more specific biocViews term; see
  https://bioconductor.org/packages/devel

## NAMESPACE

Looks good.

## R

* As the NOTE mentions in the build report, make your lines <80 chars,
  and use proper indentation. Addressing all the NOTES is also a good
  idea, as we recommend clean builds.

* Consider removing commented out lines of code (e.g., projection.R:413)

* Magic numbers in **projection.R**, e.g., `nrow`, `ncol`, `lambda` in

        indexMap_adjusted = propagate(x = matrix(0, nrow = 2048, ncol = 2048), 
            seeds = seed_map, lambda = 1e6)

  make the code difficult to parse. Provide comments in the code or
  other documentation that will help people (including your future
  self!) understand these choices.

* Global variables are not good practice. Since `.BRUSH_SHAPE` and
  `.PROJ_TYPES` are only used in the `validateVariables` function,
  create variables local to this function instead.

* avoid `1:nrow()` etc. and problems when `nrow() == 0`; use
  `seq_len(nrow())` instead.

## man

Good man pages! Well done!

## vignettes

* Good vignette.

* The installation instructions should be replaced with those
  appropriate for installation once accepted to Biocondcutor, i.e.,

        source("https://bioconductor.org/biocLite.R")
        biocLite("MaxContrastProjection")

* Vignette needs to show the actual session info, without being
  interrupted by the images.  (Fig 4a, 4b). Use appropriate spacing to
  fix that.

NEWS

- Adopt a standard NEWS file format, e.g., rename as NEWS.Rd and 

        \name{MaxContrastProjection}
        \title{MaxContrastProjection NEWS}
        
        \section{CHANGES IN VERSION 1.0.0}{
          \subsection{SIGNIFICANT USER-VISIBLE CHANGES}{
            \itemize{
              \item One change
              \item Another change
            }
          }
          
          \subsection{NEW FEATURES}
          
          \subsection{BUG FIXES}
        }

**Comment by DragonDuck** [comment]
Thank you for the comprehensive review! I've made the changes. There are no specific system requirements, so I've left the entry blank.

**Comment by mtmorgan** [comment]
Thank you I've marked the package as accepted; it will be added to the Bioconductor svn repository and nightly builds, with additional information forwarded by mail in the next several days.
