### ISSUE TITLE
MetaPhOR

### ISSUE THREAD

**Issue by emilyise** [Bioconductor/Contributions#2765]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/emilyise/MetaPhOR

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Please don't use the name my-vignette.Rmd for your vignette text,

**Comment by lshep** [comment]
Can you please add an [INSTALL file](http://contributions.bioconductor.org/sysdep.html)  that explains how to install your system dependency for all 3 platforms?  @hpages / @jwokaty  any comments about adding this as a system dependency on the builders?

**Comment by hpages** [comment]
Problem is that even on a machine that has Cytoscape, the user still needs to _manually_ start it for the example in the `cytoPath()` man page to work. So unless this is addressed, installing Cytoscape won't solve the current `R CMD check` error.

Note that **RCy3**/Cytosscape are "heavy" dependencies:
- Adding **RCy3** to your Imports field increases the number of dependencies (direct + indirect) of your package significantly: from 125 to 145!
- Cytoscape itself is a heavy machinery that has proven difficult to manage on our build machines in the past. So at some point we asked package authors to find alternatives.

Also the use of Cytoscape in your package (by the `cytoPath()` function, via the **RCy3** package) seems quite marginal. The examples in the package only call `cytoPath()` twice: once in the vignette where the call is actually disabled (`eval=FALSE`), and once in the man page of the `cytoPath()` function. Therefore it looks like this is a case where having **RCy3** in `Suggests` instead of `Imports` would make more sense. Then you would need to do the following changes:
1. Add a note in the man page of `cytoPath()`, and in the vignette, that the function requires **RCy3** plus a local instance of Cytoscape in order to work.
2. Modify the `cytoPath()` function so that it takes care of loading the **RCy3** namespace. It should display an informative error message in case of failure. For example, put something like this at the very beginning of the function:
    ```
        if (!requireNamespace("RCy3", quietly=TRUE))
            stop("Failed to load the RCy3 package. Is it installed?\n",
                 "  Note that the cytoPath() function requires RCy3.\n",
                 "  Please install it with BiocManager::install(\"RCy3\").")
    ```
3. Wrap the `cytoPath()` example inside a `\donttest` directive:
    ```
    \donttest{
      #open Cytoscape locally before running
      cytoPath(pathway = "Tryptophan Metabolism",
               DEGpath = system.file("extdata", "BRCA_DEGS.csv", package="MetaPhOR"),
               figpath = file.path(tempdir(), "example_map"),
               genename = "X",
               headers = c("logFC", "adj.P.Val"))
    }
    ```
    (As a side note, please use proper code formatting/indentation for all the code in the package like I did above. This will greatly improve the readability of your code.) 
4. Finally, edit the `SystemRequirements` line as follow:
    ```
    SystemRequirements: Cytoscape (>= 3.9.0) for the cytoPath() examples
    ```
Hope this makes sense.

Thanks,
H.

**Comment by jianhong** [comment]
# Package 'MetaPhOR' Review
Thank you for submition your package to Bioconductor. The package passed check and build. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.

## The NAMESPACE file
- [ ] NOTE: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 8 import(ggplot2)

## General package development
- [ ] Important: Consider clarifying how 8 object(s) are
      initialized. Maybe they are part of a data set
      loaded with data(), or perhaps part of an
      object referenced in with() or within().
      Undefined global functions or variables:
           commandsRun cytoscapePing exportImage fitContent installApp
           loadTableData setNodeColorDefault setNodeColorMapping
- [ ] Important: Consider adding unit tests. We strongly
      encourage them. See
      https://contributions.bioconductor.org/tests.html
           
## R code
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/DataSummary.R:
		+ at line 5 found 'utils::globalVariables(c("Scores", "ABSScores", "ScorePvals"))'
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/cytoPath.R:
		+ at line 60 found '    for (i in seq_len(nrow(node.table))){'
	* In file R/metaHeatmap.R:
		+ at line 41 found '    for (i in seq_along(scorelist)){'
	* In file R/pathwayAnalysis.R:
		+ at line 63 found '    for (i in seq_len(ncol(AllPathwaysKEGGPS))){'
		+ at line 64 found '        for (j in c("Score", "ABSScore")){'
		+ at line 74 found '    for (i in c("Score", "ABSScore")){'
		+ at line 75 found '        for (j in seq_len(ncol(AllPathwaysKEGGPS))){'
		+ at line 76 found '            for (k in seq_len(iters)){boot.Scores <- sample(MP_Scores[,i],'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays.
	* In file R/bubblePlot.R:
		+ at line 32 found '    scorelist <- scorelist[,-4]'
		+ at line 37 found '        datalabs <- scorelist[order(-abs(scorelist$Scores))[seq_len(10)],]'
		+ at line 39 found '        datalabs <- scorelist[order(scorelist$ScorePvals)[seq_len(10)],]'
	* In file R/metaHeatmap.R:
		+ at line 57 found '    hmat <- hmat[rowSums(hmat[]) > 0, ]'
- [ ] NOTE: Consider handle the error for `cytoscapePing` in line 36 of `cytoPath.R` to avoid the building error and 'donttest{}'.
        
## Documentation
- [ ] Important: Vignette should use `BiocStyle` package for formatting.
	* rmd file vignettes/MetaPhOR-vignette.Rmd
- [ ] Important: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/MetaPhOR-vignette.Rmd
- [ ] NOTE: To avoid the "* NOTE: Consider adding runnable examples to man pages that documentexported objects." in BiocCheck, could you please remove `donttest` from
	* CytoPath.Rd

**Comment by emilyise** [comment]
### **The NAMESPACE file**
NOTE: Selective imports using importFrom instead of import all with import.
in line 8 import(ggplot2)
**Resolved** 

### **General package development**
 Important: Consider clarifying how 8 object(s) are
initialized. Maybe they are part of a data set
loaded with data(), or perhaps part of an
object referenced in with() or within().
Undefined global functions or variables:
commandsRun cytoscapePing exportImage fitContent installApp
loadTableData setNodeColorDefault setNodeColorMapping
**Resolved** 

 Important: Consider adding unit tests. We strongly
encourage them. See
https://contributions.bioconductor.org/tests.html
**We do not think the addition of unit testing is necessary at this time.**

### **R code**
 NOTE: :: is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
In file R/DataSummary.R:
at line 5 found 'utils::globalVariables(c("Scores", "ABSScores", "ScorePvals"))'
**Resolved**

 NOTE: Vectorize: for loops present, try to replace them by *apply funcitons.
In file R/cytoPath.R:
at line 60 found ' for (i in seq_len(nrow(node.table))){'
In file R/metaHeatmap.R:
at line 41 found ' for (i in seq_along(scorelist)){'
In file R/pathwayAnalysis.R:
at line 63 found ' for (i in seq_len(ncol(AllPathwaysKEGGPS))){'
at line 64 found ' for (j in c("Score", "ABSScore")){'
at line 74 found ' for (i in c("Score", "ABSScore")){'
at line 75 found ' for (j in seq_len(ncol(AllPathwaysKEGGPS))){'
at line 76 found ' for (k in seq_len(iters)){boot.Scores <- sample(MP_Scores[,i],'
**Resolved**

 Important: Please consider to add drop=FALSE to avoid the reduction of dimension for matrices and arrays.
In file R/bubblePlot.R:
at line 32 found ' scorelist <- scorelist[,-4]'
at line 37 found ' datalabs <- scorelist[order(-abs(scorelist$Scores))[seq_len(10)],]'
at line 39 found ' datalabs <- scorelist[order(scorelist$ScorePvals)[seq_len(10)],]'
In file R/metaHeatmap.R:
at line 57 found ' hmat <- hmat[rowSums(hmat[]) > 0, ]'
**Resolved**

 NOTE: Consider handle the error for cytoscapePing in line 36 of cytoPath.R to avoid the building error and 'donttest{}'.
**The cytoPath function requires a local instance of CytoScape, and will not build if the example is run. The example may be run by the user successfully if there is a local instance of CytoScape open. Please see previous discussion regarding this topic.**

### **Documentation**
 Important: Vignette should use BiocStyle package for formatting.
rmd file vignettes/MetaPhOR-vignette.Rmd
**Resolved**

 Important: Vignette includes motivation for submitting to Bioconductor as part of the abstract/intro of the main vignette.
rmd file vignettes/MetaPhOR-vignette.Rmd
**The opening line of our vignette describes our motivation for submitting to Bioconductor:  _"to enable users to assess metabolic dysregulation using transcriptomic-level data (RNA-sequencing and Microarray data) and produce publication-quality figures"_**

 NOTE: To avoid the "* NOTE: Consider adding runnable examples to man pages that documentexported objects." in BiocCheck, could you please remove donttest from
CytoPath.Rd
**The cytoPath function requires a local instance of CytoScape, and will not build if the example is run. The example may be run by the user successfully if there is a local instance of CytoScape open. Please see previous discussion regarding this topic.**

**Comment by jianhong** [comment]
Thank you for the updates. Almost there. Please try to fix the following minor issues.

- [ ] NOTE: Try to check the edge condition when using `seq.int` or `seq_len`. For example using `seq.int(min(5, nrow(data)))` to replace `seq.int(5)`
	* In file R/bubblePlot.R:
		+ at line 39 found '                                [seq_len(10)], , drop = FALSE]'
		+ at line 42 found '                                [seq_len(10)], , drop = FALSE]'

**Comment by emilyise** [comment]
Thank you for the review. I have resolved the following issue: 

 NOTE: Try to check the edge condition when using seq.int or seq_len. For example using seq.int(min(5, nrow(data))) to replace seq.int(5)
In file R/bubblePlot.R:
at line 39 found ' [seq_len(10)], , drop = FALSE]'
at line 42 found ' [seq_len(10)], , drop = FALSE]'

**Comment by jianhong** [comment]
Great! Don't forget to update your NEWS.md file when you update anything. Thank you for contribute to Bioconductor!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/emilyise.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MetaPhOR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaPhOR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
