### ISSUE TITLE
simpleSeg

### ISSUE THREAD

**Issue by anic0077** [Bioconductor/Contributions#2774]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/simpleSeg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nilseling** [comment]
Hi @anic0077,

thanks for submitting `simpleSeg`. It's a great addition to the image analysis side of Bioconductor.
Before we can accept the package there are a few things that need to be addressed, see below. 
Please respond to the comments point-by-point and let me know if things are unclear.

## General package development

- [x] Please fix the last NOTEs by adding the missing functions to the imports. Some of these can already be fixed by running `roxygen2::roxygenise("simpeSeg")` and therefore updating the `NAMESPACE` file. 

```
* checking R code for possible problems ... NOTE
.estimateTolerance: no visible global function definition for ‘coef’
.prepNucSignal: no visible binding for global variable ‘sd’
.prepNucSignal: no visible binding for global variable ‘cor’
.prepNucSignal: no visible global function definition for ‘cor’
.prepNucSignal: no visible global function definition for ‘is’
calcTissueMask: no visible global function definition for ‘is’
normalizeCells: no visible global function definition for ‘is’
normalizeCells : PC1: no visible global function definition for ‘resid’
nucSeg: no visible global function definition for ‘median’
simpleSeg: no visible global function definition for ‘runif’
simpleSeg: no visible global function definition for ‘is’
Undefined global functions or variables:
  coef cor is median resid runif sd
```

- [x] It is not needed to specify `R` in `Depends` but if you do, please update it to the newest version (`4.2.0`).  
- [x] As you are submitting the package to Bioconductor you can rely on exiting classes (as you already do). For the `simpleSeg` function you could only support a `CytoImageList` object as input instead of a single `Image` or list of `Image` objects. This would make the validity checks (see below) easier, you could directly use existing getter/setter functions (e.g. `cytomapper::getChannels(images, nucleusIndex)`) and it would fit to the class of the returned object. The same applies for the `normalizeCells` function which would only need to support `SummarizedExperiment` type objects. 

## The DESCRIPTION file

- [x] I would recommended to extend the description of the package by a brief overview on the different ways that cells can be segmented.
- [x] Please add a `BugReports` and `URL` field
- [x] Add `ggplot2` to the `Suggests` field as you are using this package in the vignette.

## The NAMESPACE file

- [x] Selectively import functionalities and classes from the `cytomapper` package instead of importing the whole package. Alternatively you can move the `cytomapper` package to `Depends`.
- [ ] Avoid calling functions via `pkg::function` but rather specify the import via `@importFrom pkg function`

## The NEWS file

- [x] It is recommended to add a NEWS file.

```
* NOTE: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.
```
	  
## Package data

- [ ] Please provide a script (code, pseudo code or a text description) on how the data in `inst/extdata/` was generated. see [https://contributions.bioconductor.org/docs.html#doc-inst-script](https://contributions.bioconductor.org/docs.html#doc-inst-script) for more information. 

## Documentation

### Vignette

- [x] Please remove `eval = FALSE` from chunk headers in the vignette (except the installation instructions) - all included code chunks should be evaluated
- [x] It is recommended to have a package-level man page that lists core functionalities and can be displayed via `?simpleSeg`.
- [x] I would recommend to remove `simpleSeg.html` from the vignettes folder as this will be generated by the Bioconductor build system upon acceptance.
- [x] You could think of a more descriptive vignette title.
- [x] Please update the README file and the vignette with Bioconductor installation instructions

```
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

BiocManager::install("simpleSeg")
```

- [x] Please include a motivation for the inclusion into Biocodunctor in your Introduction/Overview section. This could be along the lines of `simpleSeg` extending existing functionalities of Bioconductor packages such as `EBImage` and `cytomapper`.
- [x] As you are using functions of the `cytomapper` and `EBImage` package you might want to link to both (e.g. via `r Biocpkg("EBImage")`)
- [x] Please double check the vignette for spelling, style and readability.

### Man pages

Concerning the `simpleSeg` function:

- [ ] It is a bit unclear what the `nucleus="PCA"` default parameter is doing. By looking at the code I get an idea but you might want to add an explanation in a `@section` entry to the documentation. 
- [x] The `sizeSelection` threshold is resolution-specific and I'm not quite sure if a reasonable default value can be set. You could consider setting it to `NULL` meaning no size exclusion is performed. But this is definitely up to you.
- [x] I would recommend to add some explanation regarding the `transform` parameter. For example, it is not clear from the man page what the `tissueMask` normalization is doing.

## Unit tests

- [x] It is recommended to add unit tests covering the main functionality of the package.

## R code

- [x] Please address the following NOTEs.

```
* NOTE: Avoid sapply(); use vapply()
* NOTE: Avoid 1:...; use seq_len() or seq_along()
```

- [x] It is recommended to add validity checks for all function arguments (including the input objects).
- [x] You currently don't allow the user to set the `BPPARAM` argument but create it internally. It is recommended to add a `BPPARAM` argument directly to the exported functions as it allows the user to specify error handling, logging and random number use. The defaults can either be `BPPARAM = SerialParam()` or `BPPARAM = bpparam()` depending if you want to default to serial or parallelised computations.
- [x] By changing the way you handle parallelised computations the following WARNING will disappear

```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘generateBPParam’
```

- [x] I would recommend to indicate all internal/non-exported function with a `.` prefix (e.g. `.calcTissueMask` instead of `calcTissueMask`)

**Comment by nick-robo** [comment]
Hey @nilseling, we addressed most of your comments, but we are having some technical issues with pushing the new version to the bioconductor git (the access rights were allocated incorrectly). Would you mind checking the new version on our repo?

**Comment by nilseling** [comment]
Hi @nick-robo 
could you please indicate which comments you addressed, which ones you are still working on and which ones you might disagree with? @lshep could you potentially assist with setting the access rights? Thanks for your help!

**Comment by lshep** [comment]
Should be all set after re-activation of GitCredentials account. See private email for explanation

**Comment by nick-robo** [comment]
Here are the points that have not been addressed (@nilseling): 

- After some consideration, we would rather not change the inputs to simpleSeg.
- We haven't added a package-level man page yet. 
- We would rather keep the default `sizeSelection` parameter.
- We modified the `simpleSeg` function such that it can accept `BPPARAM` objects.

The rest of the points have been addressed directly.

We really appreciated your extensive and detailed list of comments. Unfortunately markdown in GitHub comments cannot be copied meaning that we could not work on your list directly. Just for your future reference.

**Comment by nilseling** [comment]
Hi @nick-robo 
thanks for the info! Could you please push the newest version to Bioconductor? I'll have a look at the changes soon.

**Comment by nilseling** [comment]
Hi @nick-robo, 

thanks for addressing the comments! 

> Here are the points that have not been addressed (@nilseling):
> 
> * After some consideration, we would rather not change the inputs to simpleSeg.

That's ok as you are highlighting the use of individual functions with `CytoImageList` and `SummarizedExperiment` objects.

> * We haven't added a package-level man page yet.

Also ok as the vignette shows the main functionality of the package.

> * We would rather keep the default `sizeSelection` parameter.

That's fine for me but keep in mind that with low-res technologies (e.g. pixel size > 1µm) you will by default lose all smaller (e.g. immune cells) if you perform nuclear segmentation. 

> * We modified the `simpleSeg` function such that it can accept `BPPARAM` objects.

That's good.

> 
> The rest of the points have been addressed directly.
> 
> We really appreciated your extensive and detailed list of comments. Unfortunately markdown in GitHub comments cannot be copied meaning that we could not work on your list directly. Just for your future reference.

I do have a couple of smaller comments that should be addressed before acceptance:

- [x] Please update the version number in the NEWS file.
- [x] I would recommend to adjust the unit tests in a way that only the pixel information is compared. Currently also the `int
_metadata` entries of both objects are compared leading to test failures once the version of `cytomapper` updates.
- [x] Please provide a script (code, pseudo code or a text description) on how the data in `inst/extdata/` was generated. see https://contributions.bioconductor.org/docs.html#doc-inst-script for more information.
- [x] It is not clear what the `PCA` entry to `nucleus` in `simpleSeg` is doing. Based on the description (`The marker or list of markers corresponding to the nuclei marker/s. PCA can also be specified in addition to or in place of a marker.`) I can only speculate. Do you assume PC1 will always capture the nuclear signal? 

Please let me know if you have questions. Once you perform the last adaptations, push the changes and we can move on to acceptance.

**Comment by nilseling** [comment]
Hi @nick-robo 

thanks for addressing the last comments! I will now accept the package. 
For the future I would recommend to increase the coverage of the package by including more unit tests.

```
simpleSeg Coverage: 25.00%
R/calcTissueMask.R: 0.00%
R/normalizeCells.R: 0.00%
R/utilities.R: 21.05%
R/simpleSegHelper.R: 31.16%
R/simpleSeg.R: 36.00%
```

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anic0077.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("simpleSeg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/simpleSeg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
We had an issue processing packages -- I'm temporarily reopening so I can reprocess and get your package on the daily builders. Sorry for any confusion and delay

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anic0077.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("simpleSeg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/simpleSeg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
