### ISSUE TITLE
MsQuality

### ISSUE THREAD

**Issue by tnaake** [Bioconductor/Contributions#2776]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tnaake/MsQuality

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lgatto** [comment]
Hi @tnaake - could you please address the issue mentioned in the [build report](http://bioconductor.org/spb_reports/MsQuality_buildreport_20220926104807.html). They should be easy to fix. 

Just a few quick comments that you can already address before the more in-depth review:

- You don't need to install `devtools` to install packages from GitHub, you only need `remotes`. You could also use `BiocManager::install("tnaake/MsQuality")` to install from GitHub, but you are asked to provide instructions to (also) install from Bioconductor. Your installation instructions could thus be:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

if (!requireNamespace("remotes", quietly = TRUE))
    install.packages("remotes")

## to install from Bioconductor
BiocManager::install("MsQuality")

## to install from GitHub
BiocManager::install("tnaake/MsQuality")
``` 

- Could you also mention other packages that address MS quality control that are available in Bioconductor. proteoQC comes to mind, but there might be another or two, which you should be able to find with the biocViews. 

- Why does `qualityMetrics()` need an object of class `Spectra` as input? It only returns a vector of QC metric names. I tried with `sps_sciex`, `sps_c_hilic`, `sps_c_rplc` and the manually created `sps`, and I get the same set of metrics.

-  We already had the discussion about 1 sample or all samples per Spectra object in Heidelberg. In you `sps_c_rplc` and `sps_c_hilic` example objects seem to confirm that you don't limit yourself to one sample/file per Spectra object, which is good (the other would be wrong). Why to you have two in your vignette, and concatenate the metrics, as opposed to concatenating the Spectra object:

```
calculateMetrics(c(sps_c_hilic, sps_c_rplc))
``` 
Both are valid, just curious why you illustrate it explicitly, and making sure my understanding of the sample per Spectra is correct.

**Comment by tnaake** [comment]
Dear @lgatto 

many thanks for this initial screen. I have now fixed the issues in the [build report](https://bioconductor.org/spb_reports/MsQuality_buildreport_20221012073517.html) and addressed your comments.

- `devtools`/`remotes`: I changed this accordingly in the vignette and the `README.md` file.
- `other packages`: I have added a subsection in the vignette that mentions other packages in Bioconductor. `proteoQC` doesn't seem to be maintained any longer (at least it's only available via the RIKEN and TU Dortmund mirrors).
- `qualityMetrics()`: We have implemented this in this way since we would like to get all available metrics for this kind of object. As you may know, we have also included some functionality for `MsExperiment` objects in another branch in the GitHub repository. We are planning to merge this branch into the `main` branch once `MsExperiment` is accepted in Bioconductor. The `qualityMetrics()` will allow us in future to get a vector of class-specific metrics either for `Spectra`, `MsExperiment` or other objects in future versions (e.g. `Chromatogram`). 
- `calculateMetrics(c(sps_c_hilic, sps_c_rplc))`: Good point, I think this has something to do with how the data of the article (Lee et al. 2019) we are using in the vignette is organized. This is basically a matrix with samples in columns and metabolites in rows. The metabolites have an appendix specifying if the metabolite was measured by RPLC or HILIC (the metabolites were measured via both methods, such that we have metabolite quanitifaction for each metabolite from both RPLC and HILIC). I understand that this might be a bit complicated for the reader and I show the creation of the `Spectra` object only in the `Lee2019-data.R` file. I have rewritten this such that we now creacte a new `Spectra` object (`c()`) in the beginning and pass to `calculateMetrics` the RPLC+HILIC-combined `Spectra` object. Do you think it's better this way? I thought that it might be nice to use a real-world data set to showcase the calculation rather than only with the data sets from `msdata` but this can be changed of course if you think this might be too complicated/confusing here.

Many thanks again for this initial (and future) review!

**Comment by lgatto** [comment]
Following up from your previous replies, yes, I think the update in
the vignette where you combine the `Spectra` first is nice and clean.

## General package development

- Please add `.github` to a `.Rbuildignore` file so that it doesn't
  end up in the package tar file.

## The DESCRIPTION file

Here are a couple of notes from `BiocCheck` that you might want to
address:

- The Description field in the DESCRIPTION is made up by less than 3
  sentences. Please consider expanding this field, and structure it as
  a full paragraph.
- License 'GPL (>= 3)' is reported as unknown by BiocCheck. I think
  this would go away with GPL-3 which at the moment would be
  equivalent... and if one day there's a version 4, you might want to
  read it and update accordingly.
- Update R version dependency from 4.1.0 to 4.2.0.

Some additional suggestions:

- You could add a `BugReports` field in your DESCRIPTION file to point
  to your GitHub issues.
- You could add a `URL` field in your DESCRIPTION file to point to
  your GitHub repo (or pkgdown if you plan to create one, which I
  recommend).

## The NEWS file

- Do you know that you can use markdown for your news and have
  `NEWS.md`. This plays well with a pkgdown site.

## Package data

- Installed package size is 7.5Mb, and data is 2.7Mb. Could you reduce
  the size of the data? An alternative would be to move Lee 2019 data
  to `msdata` (or better, later to `MsDataHub` that will put it on
  ExperimentHub).

## Documentation

- Lee_2019 documentation: the 'Source' section is a bit weird
  formatted as comments and code. If you want to keep it like that, I
  would suggest to remove the `##` in front of the text, and you might
  be able to use markdown syntax for code chunks. A clean alternative
  would be to put the script in `inst/scripts/` and point to it in the
  manual page.

- You have a \dontrun{} in you shinyMsQuality example. You could also
  enclose `shinyMsQuality(qc = qc)` in an `if (interactive())` so that
  the example is run by the user interactively.

**Comment by tnaake** [comment]
Dear @lgatto,

many thanks again for the review! I have gone through your points and changed the package accordingly. Please see here for my responses:

- **.github**: added to `.Rbuildignore` 
- **Description** in `DESCRIPTION`: I have extended the description.
- **License** in `DESCRIPTION`: changed to `GPL-3`.
- **R version** in `DESCRIPTION`: dependency bumped to 4.2.0.
- **BugReports** and **URL** in `DESCRIPTION`: I added the links to the github repo.
- **NEWS** file: changed to .md format
**package size**: I have discussed this with @jorainer and we agreed to transfer the example data to `MsDataHub` once `MsDataHub` is ready. Could we transfer the dataset after acceptance of `MsQuality` and `MsDataHub` to Bioconductor ? As a side note, I was a bit astonished by the large file size of the `doc` part, which is due to `plotly` graphics. I have added `partial_bundle` to `plotly` graphics which reduced the file size substantially.
- **Lee2019**: I have added a script in `inst/scripts` and am refering to it in the `Lee2019-data.R` file.
- **dontrun**: I have changed this to `if (interactive())` as suggested.


Many thanks again for having a detailed look into the package! 


Best,
tnaake

**Comment by lgatto** [comment]
Great. Thank you for your contribution!

**Comment by tnaake** [comment]
Thank you once more for your review!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tnaake.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsQuality")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsQuality

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
