### ISSUE TITLE
BioMartGOGeneSets

### ISSUE THREAD

**Issue by jokergoo** [Bioconductor/Contributions#2777]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jokergoo/BioMartGOGeneSets

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jokergoo** [comment]
This package provides pre-compiled GO gene sets for more than 600 organisms from BioMart. Manually creating such gene sets is not difficult (as we have demonstrated in https://jokergoo.github.io/BioMartGOGeneSets/articles/biomart.html), but it would still be nice if the gene sets are already compiled and especially good for the users who are not experienced with Bioconductor or studying non-model organisms.

The script for generating the gene sets is also included in the package (https://github.com/jokergoo/BioMartGOGeneSets/blob/master/inst/scripts/biomart_genesets.R). Currently all the gene set data are stored on github.io (https://github.com/jokergoo/BioMartGOGeneSets_data). We will update the data regularly.

**Comment by vjcitn** [comment]
Trying to review, hitting
```
--- re-building ‘biomart.Rmd’ using rmarkdown
Ensembl site unresponsive, trying uswest mirror
Ensembl site unresponsive, trying asia mirror
Quitting from lines 83-86 (biomart.Rmd) 
Error: processing vignette 'biomart.Rmd' failed with diagnostics:
```

**Comment by jokergoo** [comment]
I think this should be an internet issue when connecting to the BioMart web service (using `biomaRt` package). There might be one of the following two reasons:

1. Currently you cannot connect to Ensembl BioMart service? Maybe you can try it later.
2. These lines retrieve GO-gene relations for all GO terms. The data is relatively huge. The downloading might be interrupted? (This is unlikely because I guess if so it will give a different error message)

Now I save the intermediate results (GO-gene relations in lines 83-86) to an object, and these lines are not executed in the vignette while I directly read the cached object. Hope this problem will be solved.

**Comment by vjcitn** [comment]
Every time I try to review, it fails.  Can you introduce some fault tolerance so that the value of the package is illustrated even if the networking fails?  Messages to the user about what happens in the ideal case?
```
--- re-building ‘biomart.Rmd’ using rmarkdown
Quitting from lines 63-65 (biomart.Rmd) 
Error: processing vignette 'biomart.Rmd' failed with diagnostics:
Timeout was reached: [www.ensembl.org:443] Operation timed out after 10000 milliseconds with 294464 bytes received
--- failed re-building ‘biomart.Rmd’
```

**Comment by jokergoo** [comment]
```
--- re-building ‘biomart.Rmd’ using rmarkdown
Quitting from lines 63-65 (biomart.Rmd) 
Error: processing vignette 'biomart.Rmd' failed with diagnostics:
Timeout was reached: [www.ensembl.org:443] Operation timed out after 10000 milliseconds with 294464 bytes received
--- failed re-building ‘biomart.Rmd’                                 ~~~~~~~~~~~~~~~~~~
```

I can see the timeout limit on your machine is only 10 seconds. I guess it relates to which biomart mirror to use. As far as I have checked, the useast mirror has a timeout limit of 10 seconds and uswest mirror has a timeout limit of 5min.

The vignette "biomart.Rmd" has nothing related to the functionalities of the **BioMartGOGeneSets** package. It is just a demonstration of how the data is gathered. Now in the new version, I directly generated the corresponding .md file for this vignette.

Also in the vignette, I additionally inform users to change the biomart mirrors when they see the "timeout" error.

**Comment by jokergoo** [comment]
The error was a false positive:

```
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
```

I've already subscribed the bioc-devel mailing list.

**Comment by lshep** [comment]
I can confirm user is subscribed to mailing list.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jokergoo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BioMartGOGeneSets")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BioMartGOGeneSets

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
