### ISSUE TITLE
speckle package submission

### ISSUE THREAD

**Issue by bphipson** [Bioconductor/Contributions#2778]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/phipsonlab/speckle

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ococrook** [comment]
@bphipson thanks for the submission, I'll get around to having a look at the package shortly. I can take upto 10 days to get back to you. If you could have a look at the warning in the meantime that would be great.

**Comment by bphipson** [comment]
Thanks @ococrook . I checked the warning and it is to do with missing or empty \VignetteIndexEntry. However %\VignetteIndexEntry{} is present in the speckle.Rmd file, so I am a bit confused as to why this warning is coming up and I'm not sure how to fix it.

**Comment by PeteHaitch** [comment]
I ran `R CMD check` on my mac and didn't get this warning - I wonder if it's specific to Linux (which the `nebbiolo2` Bioconductor Single Package Builder is)?
I thought it might be due to the [VignetteIndexEntry entry being broken up over 2 lines](https://github.com/phipsonlab/speckle/blob/1a4993a1ec09ff7138b1504c68b9f66cafd3d65b/vignettes/speckle.Rmd#L8-L9)
Perhaps worth changing to a single line and pushing a new version to see if the warning goes away?

**Comment by bphipson** [comment]
Thanks @PeteHaitch, I have pushed that change.

**Comment by ococrook** [comment]
Apologies for they delay if reviewing the package. I'll finished with my review this week.

**Comment by ococrook** [comment]
Hi @bphipson 

This looks pretty good and the vignette was very clear. I have some suggestions for changes to the package.

Description
- [ ]  Could you make the package version match with the NEWS.md file
- [ ] Lazy data entry to false.

Unit tests
- [ ] Please add unit tests

install instruction
- [ ] Please add install instruction to both the vignette and readme

package name
- [ ] I'm not sure speckle is a good name and could be confused with another tool: https://github.com/specklesystems

R code
- [ ] Careful with 1:3 construction and use the appropriate `seq` functions
- [ ] Please place proper returns in the R code

Thanks!
Olly

**Comment by bphipson** [comment]
Hi Ollie, thanks so much for your review and apologies for taking so long to address the comments. I just pushed the changes and fingers crossed it builds ok. We addressed all your comments except regarding the package name - we have just published the propeller paper which explicitly links to the speckle package so I would be very reluctant to change it at this stage.

I also added a section to the vignette about how to use propeller on any proportions data, but it required a small proportions matrix, which I have included in the package as sysdata.Rda. I am not sure if that aligns with Bioconductor's best practices.  

Thanks again!

**Comment by bphipson** [comment]
Hi, I have checked the warning and it is due to a function being recently replaced in edgeR. I'm not sure how to resolve the warning, and I can't reproduce the warning on my windows laptop. The warning is:

  Warning: S3 methods effectiveLibSizes.default, effectiveLibSizes.DGEList, effectiveLibSizes.DGEGLM, effectiveLibSizes.DGELRT were declared in NAMESPACE but not found

Any ideas? I have also emailed Gordon Smyth.

Thanks, Belinda

**Comment by ococrook** [comment]
Thanks for compeleting the revision @bphipson. For the new data can you move to a `/data` folder? You can find the expectations here: https://r-pkgs.org/data.html. Let me know when you've managed to sort that an add docuentation for it and then we can move to accept the package.

Best wishes,
Olly

**Comment by bphipson** [comment]
Hi Ollie, I moved the data to the `/data` folder and added documentation. Hopefully should be all good now. Thanks for your time reviewing the package.

Cheers,
Belinda

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bphipson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("speckle")`. The package 'landing page' will be created at

https://bioconductor.org/packages/speckle

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
