### ISSUE TITLE
MSstatsShiny

### ISSUE THREAD

**Issue by devonjkohler** [Bioconductor/Contributions#2783]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsShiny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
I think the "Title" field in DESCRIPTION may be wrong.

**Comment by devonjkohler** [comment]
Hi @vjcitn,

Thanks for pointing that out. I've updated the title on my end.

Devon

**Comment by lshep** [comment]
Please add `ShinyApps` to your biocViews fields.

**Comment by devonjkohler** [comment]
Hello,

Just curious where this package is in the review. Concerned that the deadline is approaching.

Devon

**Comment by PeteHaitch** [comment]
I've started the review but please appreciate that the reviewers' workload is substantially increased close to release.
We aim to have reviews within 3 weeks of the package building successfully on the BioC build machine and I expect to provide yours in the next few days.

**Comment by devonjkohler** [comment]
Hi @PeteHaitch,

Thank you a bunch for taking a look at the package! I Definitely understand that the releases are a lot of work. I was just a little worried by the Wednesday deadline listed in the release schedule. 

Devon

**Comment by PeteHaitch** [comment]
Hi @devonjkohler,

I've completed my initial review of **MSstatsShiny**.
However, I have asked other Bioconductor package reviewers for comments because I do not have much experience with Shiny apps as a user or developer.
In particular, I'm unsure how much the requirements and advice in the [chapter on Shiny apps in the Developer & Reviewer's Guide](https://contributions.bioconductor.org/shiny.html) have to be followed for acceptance of the package into Bioconductor.

I will say that my general impression is that the app is useful and running the example data through the app was easy to do and understand.

While we wait for the advice of the other reviewers and/or @Bioconductor/core, there are a number of Required points, as well as Recommended points, that I would ask you to first please address before acceptance into Bioconductor.
Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers,
Pete

## Required

- [ ] Fix or otherwise address all WARNINGs raised by `R CMD check` and `BiocCheck::BiocCheck()`

```
Warning: replacing previous import ‘shinyjs::show’ by ‘marray::show’ when loading ‘MSstatsShiny’
Warning: replacing previous import ‘plotly::select’ by ‘biomaRt::select’ when loading ‘MSstatsShiny’
```

- [ ] Related to the above, we recommend selective imports using `@importFrom pkg fun` **roxygen2** tag rather than `@import pkg`. This will reduce the chances of name clashes, as in the warning above.
- [ ] Please use **BiocStyle**. for vignette formatting.
- [ ] Please add an *Introduction* section to the vignette. This should include motivation for inclusion to Bioconductor.
- [ ] Please add a table of contents to the vignette.
- [ ] All man pages should have runnable examples, i.e. they should be more like `?lf_summarization_loop`.
- [ ] Use `TRUE`, `FALSE` instead of `T`, `F`.

## Recommended

- [ ] It's generally a good idea to fix or otherwise address all NOTEs raised by `R CMD check` and `BiocCheck::BiocCheck()`. 
- [ ] Using `<-` for assignment is standard R, but if you want to use `=` that's okay.
- [ ] Consider adding a [`inst/CITATION` file](https://contributions.bioconductor.org/citation.html).
- [ ] Consider adding a [package man page](https://contributions.bioconductor.org/docs.html#package-level-documentation).
- [ ] Please take a look at `covr::report()` to identify under-tested areas of code.
- [ ] I recommend removing dead (commented-out) code (e.g., https://github.com/Vitek-Lab/MSstatsShiny/blob/9f17458b5cdc6ff88fed07bf90619999a84e8ab2/inst/MSstatsShiny/server.R#L15-L16).

**Comment by devonjkohler** [comment]
Hey @PeteHaitch,

Thank you for reviewing the package. Your comments make sense and I am in the process of addressing them now. I should have an updated version by tomorrow morning.

Best,
Devon

**Comment by PeteHaitch** [comment]
Hi @devonjkohler,

I've received some feedback from other Bioconductor package reviewers about the guidelines in the [chapter on Shiny apps in the Developer & Reviewer's Guide](https://contributions.bioconductor.org/shiny.html).
From @vjcitn, Project Lead of Bioconductor, "At this point in our experience with (Shiny) apps, I'd propose that the rules in the guidelines be taken as advisory.", so we'll stick with that for this submission.

If you haven't already, please familiarise yourself with the guidelines and take them into consideration.
The main guideline that I think you should seriously consider following is to have all the UI and server code under the `R/` directory of the package (rather than under `inst/MSshinyStats`).
This would then ensure that the UI and server code are checked by `R CMD check` and `BiocCheck::BiocCheck()`.

Thanks,
Pete

**Comment by devonjkohler** [comment]
Hi @PeteHaitch,

I just pushed an updated version of the package responding to your review. I was able to address all your main points (see below).

In terms of the BioC guidelines for shiny packages I have reviewed them and they make sense. I agree that the code should be refactored under the R directory. In this update I was not able to change it because it is actually a very big undertaking, as the entire server side of the package needs to be refactored into functions. My hope is that we can use this version for the initial submission and refactor the code in subsequent releases. We are hoping to publish a paper on the application in the coming months and Bioconductor makes it much easier for users to install and use (especially because our user base is mainly people without a programming background).

I hope this makes sense!

Devon


## Required
[x] Fix or otherwise address all WARNINGs raised by R CMD check and BiocCheck::BiocCheck()
  - Package is no longer returning any warnings

[x] Related to the above, we recommend selective imports using @importFrom pkg fun roxygen2 tag rather than @import pkg. This will reduce the chances of name clashes, as in the warning above.

  - I went through the package, found all the imports, and replaced them with @importFrom (other than ggplot2 which calls a ton of different functions). There are no more clashes being returned by the package.

  
[x] Please use BiocStyle. for vignette formatting.
  - This has been added to the vignette
  
[x] Please add an Introduction section to the vignette. This should include motivation for inclusion to Bioconductor.

  - This has been added to the vignette

  
[x] Please add a table of contents to the vignette.

  - This has been added to the vignette

  
 All man pages should have runnable examples, i.e. they should be more like ?lf_summarization_loop.
  - All functions now have runnable examples that call the function they refer to.
  
 Use TRUE, FALSE instead of T, F.

  - All instances of T, F have been swapped out.

  
## Recommended
 It's generally a good idea to fix or otherwise address all NOTEs raised by R CMD check and BiocCheck::BiocCheck().

   - I tried to address most of the notes here. The only remaining ones are generally related to code style. I am going to continue to address these as I refactor the shiny panels into functions.

  
 Using <- for assignment is standard R, but if you want to use = that's okay.

   - This was actually done on purpose to be consistent with the new versions of the MSstats packages. Thus I kept = for assignment.

  
 Consider adding a [inst/CITATION file](https://contributions.bioconductor.org/citation.html).

  - We currently have a paper for this package under review, and I will add a citation file referring to it once it is published.

  
 Consider adding a [package man page](https://contributions.bioconductor.org/docs.html#package-level-documentation).

  - Package man page has been added

  
 Please take a look at covr::report() to identify under-tested areas of code.

  - Tests have been added for every main function in the package. The plotting functionality is still missing some coverage, but we are testing the main parameters and functionalities.

  
 I recommend removing dead (commented-out) code (e.g., https://github.com/Vitek-Lab/MSstatsShiny/blob/9f17458b5cdc6ff88fed07bf90619999a84e8ab2/inst/MSstatsShiny/server.R#L15-L16).
  - This has been done.

**Comment by PeteHaitch** [comment]
Thank you for making the required changes and considering the recommended ones.
I'm happy to accept **MSstatsShiny** into Bioconductor!
Thank you for your contribution.

I _think_ we've just snuck the package acceptance in before the before today's deadline but hopefully @lshep may be able confirm.

Some minor comments to your response.

-----

> In terms of the BioC guidelines for shiny packages I have reviewed them and they make sense. I agree that the code should be refactored under the R directory. In this update I was not able to change it because it is actually a very big undertaking, as the entire server side of the package needs to be refactored into functions. My hope is that we can use this version for the initial submission and refactor the code in subsequent releases. We are hoping to publish a paper on the application in the coming months and Bioconductor makes it much easier for users to install and use (especially because our user base is mainly people without a programming background).

That's totally fine :)
As you can tell, our 'best-practises' for Shiny apps are still in-development and we aim to continue to develop them over the next release cycles.
It will be valuable to hear from you as a Shiny developer about your experience (e.g., what you find valuable, points of friction, tips and tricks) on submitting a Shiny app to Bioconductor for incorporation into the guide. 

I can imagine **MSstatsShiny** being very helpful to non-R users to analyse their proteomics data - the GUI is slick and convenient.

> I went through the package, found all the imports, and replaced them with @importFrom (other than ggplot2 which calls a ton of different functions). There are no more clashes being returned by the package.

That's a fair trade off.
If you're using lots of functionality from a dependency, then `@import` may be appropriate and simpler.
`@importFrom` is preferable if you're only using a small subset of a dependency's functionality and to avoid explicit clashes.

> I tried to address most of the notes here. The only remaining ones are generally related to code style. I am going to continue to address these as I refactor the shiny panels into functions.

The coding style stuff is generally only recommendations, so don't feel obliged to force your code into that style if it doesn't suit you or your colleagues style (e.g., using `=` instead of `<-` makes sense for you and your team).

**Comment by PeteHaitch** [comment]
Please double-check the syntax in your vignette, the headers don't seem quite right (see screenshot from opening the vignette on my computer)

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1049741/198130765-cda049b2-7dd7-4877-9503-e281f9296ad6.png">

Aside: did you mean to switch the vignette to a PDF rather than HTML?
**BiocStyle** supports either (via `BiocStyle::pdf_document` or `BiocStyle::html_document` in the YAML frontmatter)

**Comment by devonjkohler** [comment]
Hi @PeteHaitch,

Thank you for pointing the vignette formatting issue out. I am adding in a fix now.

Devon

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/devonjkohler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsShiny")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsShiny

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
