### ISSUE TITLE
PathwaySplice

### ISSUE THREAD

**Issue by aiminy** [Bioconductor/Contributions#279]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SCCC-BBC/PathwaySplice

Confirm the following by editing each check box to '[x]'

- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by aiminy** [comment]
Thank you
look forward to your news

**Comment by aiminy** [comment]
For the label of VERSION BUMP REQUIRED, what I should process on my side?

**Comment by hpages** [comment]
Thanks for submitting PathwaySplice. The package has many serious problems that prevent its inclusion in Bioconductor. It will need to go thru a major refactoring with a lot more focus on quality and usability. See below for the details.

Regards,
H.

**Broken examples**

1. Almost all the examples in your man pages are broken. You've wrapped them inside `\donttest` directives, so `R CMD check` does not detect the problem. It goes without saying that the examples in your man pages and vignettes should of course work. They should not be turned off (e.g. with `\donttest`, or `\dontrun`, or `eval=FALSE`).

**Coding style**

2. Rename file R/ZZZ.R -> R/zzz.R

3. Don't start your function names with a capital letter.

4. Use proper indentation to make your code readable e.g. this code (found in `?enrichmentMap`) is very hard to read:
```
     Example.Go.adjusted.by.exon<-Run_pathwaysplice(mds,ad="exon_SJ",
     sub_feature="E",0.05,genomeID="hg19",geneID="ensGene",
     gene_model=hg19,method="Sampling")
     re.w.adjusted<-enrichmentMap(Example.Go.adjusted.by.exon,n=5,SimilarityThreshold=0)
     Example.Go.unadjusted<-Run_pathwaysplice(mds,ad="exon_SJ",
     sub_feature="E",0.05,genomeID="hg19",geneID="ensGene",
     gene_model=hg19,method="Hypergeometric")
     re.w.unadjusted<-enrichmentMap(Example.Go.unadjusted,n=5,SimilarityThreshold=0)
```

5. Leave a space before and after the assignment operator (`<-`). This will also help make your code easier to read.

6. Your code uses a mix of `<-` and `=` for assignment. Please use `<-` consistently.

7. Use `file.path()` instead of `paste0()` to build file or dir paths e.g.
```
    path.file.sample <- file.path(dir.name, file.sample)
```
  Using `paste0()` is not portable.

8. Poor variable name choices e.g. `file.sample`, `file.gff`, and `file.count` are files so should preferably be named `sample.file`, `gff.file`, and `count.file`. This is just an example, there are more. Also please avoid starting variable names with a capital letter (like in `Re.example`).

9. Load only packages that are actually needed for your examples. For example in the man page for `makeGeneWiseTable()` you do `library(Biobase)` but I don't see how the Biobase package has anything to do with the example that follows.

10. Generally speaking your code is obfuscated, confused and hard to read. For example (found in the man page for the `GetResultsFromJunctionSeq` function):
```
    file.sample="Sample_info.txt"
    dir.name=dirname(system.file("extdata","Sample_info.txt", package = "PathwaySplice"))
    dir.name=paste0(dir.name,"/")
    file.gff="flat.chr22.gff"
    file.count="/QC.spliceJunctionAndExonCounts.forJunctionSeq.txt"
    Re.example<-GetResultsFromJunctionSeq(dir.name,file.sample,file.count,file.gff)
```
  Should be something like:
```
    dir.name <- system.file("extdata", package="PathwaySplice")
    sample.file <- "Sample_info.txt"
    count.file <- "QC.spliceJunctionAndExonCounts.forJunctionSeq.txt"
    gff.file <- "flat.chr22.gff"
    res <- GetResultsFromJunctionSeq(dir.name, sample.file, count.file, gff.file)
```
  Note that the user shouldn't need to append `/` to `dir.name` or prepend it to `count.file`.

  Just an example. Many man pages have these problems.

11. So please revisit all your code and make sure it is clear, concise, well formatted, and that it adheres as much as possible to established good coding practices.

**Data sets**

12. It's a bad idea to include your own annotations in the package (e.g. the `hg19`, `hg38`, and `mm10` data sets). Bioconductor already provides a vast amount of annotations via annotation packages and AnnotationHub, including gene annotations for hg19, hg38, and mm10 (see OrgDb, TxDb, EnsDb, and OrganismDb packages). Generally speaking, a software package should not include annotation data but use the existing annotations instead.

13. Having to do `data(TinyData)` in order to load the `tiny.data` data set is just a potential source of confusion that is easy to avoid. The same applies to the `mds.11.sample` data set (needs to be loaded with `data(mds11)`).

14. Incorrect nb of rows reported for `mds` data set in man page.

15. The man pages for the data sets need to explain where the data is coming from and how it was generated.

16.  `mds`, `mds2`, `tiny.data`, and `mds.11.sample` have long and cryptic row names:
```
  > rownames(mds)[1:3]
  [1] "ENSG00000223972.ENSG00000223972+ENSG00000227232+ENSG00000243485+ENSG00000274890"
  [2] "ENSG00000227232.ENSG00000223972+ENSG00000227232+ENSG00000243485+ENSG00000274890"
  [3] "ENSG00000243485.ENSG00000223972+ENSG00000227232+ENSG00000243485+ENSG00000274890"
```
Having such long and cryptic row names hurts the readability of the data frame. Is this intended? If yes then these row names should be explained in the man pages. Otherwise remove them or use shorter and less confusing row names.

17. All the columns (except the geneID column) in `mds`, `mds2`, `tiny.data`, and `mds.11.sample` are list objects with list elements of length 1. These columns should be atomic vectors instead.

18. Use the appropriate types to represent the data in `mds`, `mds2`, `tiny.data`, and `mds.11.sample` e.g.:
    - the values in the start and end columns should be stored as integer,
      not character;
    - the values in the baseMean column should be stored as numeric, not
      character;
    - etc...

**Other issues**

19. Please explain in details what the 're.gene.based' argument of the `Cbs()` function should be. "Gene based table converted from DU results" is not enough. People are not going to use a function like `Cbs()` on `mds` only. They'll use it on their own 're.gene.based' object so they need to know how to prepare such object.

20. The man page for `Cbs()` doesn't say that the function generates a plot.

**Comment by hpages** [comment]
Thanks for trying to improve PathwaySplice. Unfortuntaely the package still has many serious problems that prevent its inclusion in Bioconductor. I'll reiterate that it will need a lot more work to improve its documenation and usability. See below for some new feedback.

Regards,
H.

**Previous issues not properly addressed**

3. Please don't make your function names all lower-case without separator e.g. `getresultsfromjunctionseq` or `makegenewisetable`. This makes them hard to read. Either use camelCase style (e.g. `getResultsFromJunctionSeq`) or use the underscore as a separator e.g. `get_results_from_junction_seq`. The preferred style in Bioconductor is camelCase.

4. Lot of code is still not indented properly, making it hard to read.  E.g.
```
     ...
     res1 <- runpathwaysplice(tiny.data,adjust='exon_SJ',sub_feature='E',
     0.05,genomeID='hg19',geneID='ensGene',gene2cat=res,method='Wallenius')
     res2 <- runpathwaysplice(tiny.data,adjust='exon_SJ',sub_feature='E',
     0.05,genomeID='hg19',geneID='ensGene',gene2cat=res,method='Hypergeometric')
     dir.name <- tempdir()
     ...
```

7. You're still using `paste0()` instead of `file.path()` in the `reformatpath()` function to construct a file path. Note that this function doesn't seem to make much sense anyway but it's hard to tell because its man page is almost empty.

13. This issue was not addressed (the data set and the object it contains still have different names).

15. Thanks for providing some details in the man page for the `tiny.data` data set. Unfortunately, the Details section is poorly formatted and somewhat cryptic. Please put yourself in the shoes of an end user: after installing the package, open the man page of the data set with `?tiny.data` and read it like if it was the first time you're going to use this data set. Hopefully you'll agree with me.

**New issues**

21. The current vignette is not serious. It contains 26 words split in 3 short sentences, 3 code chunks, and 3 plots. And that's it! How are your users going to figure out what the package is about with such poor vignette? To be totally honest with you, the overall documentation of the package is still so poor that I'm still not quite sure what the package does and how one is supposed to use it on real data.

22. Some of your man pages still use the old names to refer to some functions e.g. in `?enrichmentmap`:
```
    GoSeqRes: Object returned from Run_pathwaysplice
```

23. You're mixing naming styles for your function arguments. For example the `enrichmentmap()` has arguments `SimilarityThreshold`, `output.file.dir`, and `label_vertex_by_index`. This is not good. Please use a consistent naming style for your function arguments.

24. The Value section in the man page for `enrichmentmap()` says:
```
    A figure for visualizing enrichment network
```
  Maybe the function produces a plot. But the returned value is something else:
```
     enmap <- enrichmentmap(...)
     enmap   # <- this is the returned value and the Value section in the man
             #    page needs to explain what it is
```

25. If the `tiny.data` data set contains 500 genes (according to its man page), why does it have only 252 rows?

**Comment by hpages** [comment]
Hi Aimin,
Do you plan to follow up on that submission or should I close the issue?
Thanks,
H.

**Comment by aiminy** [comment]
Thank you,

I am changing codes, and will follow up on that submission.

Aimin

**Comment by hpages** [comment]
Hi Aimin,
Thanks for all the improvements to the package. It looks much better but the vignette still needs to be improved. Right now it's just a bunch of commands with no introduction and no explanations. Thanks!
H.

**Comment by aiminy** [comment]
Yes, thank you, we are working that one.
Aimin

**Comment by aiminy** [comment]
Dear reviewer,
 
Thank you for your recent review of our R package PathwaySplice. In the past few months, we have completely revised the documentation for the package to make it more informative and user friendly. A new vignette has been added to describe the details and usage of PathwaySplice. We hope this new submission address your concerns well.
 
Appreciate your help!
 
Aimin

**Comment by hpages** [comment]
Hi Aimin,
Thanks for improving the vignette. It looks much better. Note however that it doesn't have a title and the reference section is empty. Could you please address this?
Thanks,
H.

**Comment by lxw391** [comment]
Dear Reviewer, 

I'm a co-author of the PathwaySplice package, Aimin is on vacation until 10/13, so I went ahead and made changes for the title and references. For the title, I've used "# PathwaySplice" to indicate the title. 

I noticed the package now requires a "version bump", Aimin will work on this when he is back. 

Meanwhile, please let us know if there are any other changes that we need to make. 

Thanks so much for your help, 

-Lily

**Comment by hpages** [comment]
Hi Lily,

Please don't add the `tutorial.html`, `tutorial.pdf`, and `PathwaySplice-manual_9-19-2017.pdf` files to the package source tree. These are the rendered versions of the vignette and manual, and they do not belong to, and should not be included in, the package source tree. They get automatically generated and added to the source package by `R CMD build`. Changes to the vignette need to be done in `tutorial.Rmd`. After your changes, please recreate and check the HTML vignette. To do this, build and install the source package with `R CMD build PathwaySplice` and `R CMD INSTALL PathwaySplice_0.99.25.tar.gz`, then start R and open the vignette with `vignette("tutorial", package="PathwaySplice")`. Hope this helps.

Don't hesitate to ask on the bioc-devel mailing list if you have any questions or concerns about this.

Regards,
H.

**Comment by aiminy** [comment]
Dear reviewer,

When I use this command rmarkdown::render("vignettes/tutorial.Rmd", output_format="all") to generate vignettes, I got tutorial.html and tutorial.pdf files, and they include the title and reference section. However, when I tried to use Build&Reload in RStudio to generate vignettes, I got tutorial.html, and this file does not have the title and reference section. Do you have some idea How this situation happens.

Aimin Yan

**Comment by aiminy** [comment]
Dear reviewer,

I reset to VignetteEngine{knit::rmarkdown} in the YAML header for vignettes/tutorial.Rmd file, and use this setting to regenerate vignettes again. By this way, tutorial.html file includes the title and reference section now.

I hope this new submission addresses your concerns about the vignettes.

Thank you !

Aimin

**Comment by hpages** [comment]
Hi Aimin,

Yep, everything looks good now! I'm labeling the package as accepted. Thanks again for your contribution to Bioconductor and for your patience thru the long review process.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aiminy.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"PathwaySplice\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PathwaySplice

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
