### ISSUE TITLE
SparseSignaturesPlus

### ISSUE THREAD

**Issue by danro9685** [Bioconductor/Contributions#2798]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/danro9685/SparseSignaturesPlus

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  There are already a few packages in Bioconductor addressing mutational signatures -- MutationalPatterns, SomaticSignatures, musicatk.  Can you give some background on how your package adds to the toolset for analysts in this domain?  Are any of the data structures in those packages -- or other Bioconductor data structures -- worth reusing in your package?

**Comment by danro9685** [comment]
Dear @vjcitn,

This package implements a new algorithm for mutational signatures analysis, which is not currently included in any of the packages you have mentioned.
We will clarify this and also check for other Bioconductor packages that might be worth reusing.

Thank you.

Best,
Daniele

**Comment by danro9685** [comment]
Dear @vjcitn,

We have updated the documentation as suggested.
Please let us know if you have additional  pre-review suggestions.

Thanks,
Daniele

**Comment by luca-dex** [comment]
Dear @vjcitn 
I'm the maintainer of the package. I already added the bioconductor remotes to our package and we're trying to push some changes but, at the moment, SparseSignaturePlus is not among the packages to which I access on git.bioconductor.org so my SSH key is not accepted.

```
$ git fetch --all
Fetching origin
Fetching upstream
FATAL: R any packages/SparseSignaturePlus l.desano DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream
```

Could you please help us in sorting out this issue?

Thanks

**Comment by lshep** [comment]
@luca-dex Bioconductor by default (and encourages) only one active maintainer. Daniele was given immediate access as that was who was listed as the maintainer in the DESCRIPTION. I have made the necessary adjustments on our end and you should have access now.

**Comment by luca-dex** [comment]
Thank @lshep , I'll wait to have SpareSignaturePlus in the list of package on BiocCredentials after it will be hopefully accepted.  

@vjcitn we did the necessary updates on our github, so the issue that were highlighed by BiocCheck, should have been solved

Thanks for the support

**Comment by lshep** [comment]
@luca-dex sorry I forgot to push the changes up.  You should have access now.

**Comment by nilseling** [comment]
Dear @luca-dex and @danro9685 ,

thanks for submitting the `SparseSignaturesPlus` package. I had a first look at the package and there are some things that need to be addressed before acceptance (see below). 
You are currently maintaining the `SparseSignatures` package and I was wondering about the motivation to create a new package rather than integrating the described functions into the existing package?

Please provide a point-by-point response to the checklist below and let me know if you have questions. 

## General package development

- [x] Please address the following NOTE in `R CMD build`:

```
* checking R code for possible problems ... NOTE
get.MNV.counts: no visible global function definition for ‘.’
get.SBS.counts: no visible global function definition for ‘.’
groups.CN.plot: no visible binding for global variable ‘value’
groups.CN.plot: no visible binding for global variable ‘alt’
groups.CX.plot: no visible binding for global variable ‘value’
groups.MNV.plot: no visible binding for global variable ‘Context’
groups.MNV.plot: no visible binding for global variable ‘value’
groups.MNV.plot: no visible binding for global variable ‘alt’
groups.SBS.plot: no visible binding for global variable ‘Context’
groups.SBS.plot: no visible binding for global variable ‘value’
groups.SBS.plot: no visible binding for global variable ‘alt’
patients.CN.plot: no visible binding for global variable ‘alt’
patients.CN.plot: no visible binding for global variable ‘patient’
patients.CN.plot: no visible binding for global variable ‘value’
patients.CX.plot: no visible binding for global variable ‘patient’
patients.CX.plot: no visible binding for global variable ‘value’
patients.MNV.plot: no visible binding for global variable ‘Context’
patients.MNV.plot: no visible binding for global variable ‘alt’
patients.MNV.plot: no visible binding for global variable ‘patient’
patients.MNV.plot: no visible binding for global variable ‘value’
patients.SBS.plot: no visible binding for global variable ‘Context’
patients.SBS.plot: no visible binding for global variable ‘alt’
patients.SBS.plot: no visible binding for global variable ‘patient’
patients.SBS.plot: no visible binding for global variable ‘value’
signatures.CN.plot: no visible binding for global variable ‘alt’
signatures.CN.plot: no visible binding for global variable ‘value’
signatures.CX.plot: no visible binding for global variable ‘value’
signatures.MNV.plot: no visible binding for global variable ‘Context’
signatures.MNV.plot: no visible binding for global variable ‘alt’
signatures.MNV.plot: no visible binding for global variable ‘value’
signatures.SBS.plot: no visible binding for global variable ‘Context’
signatures.SBS.plot: no visible binding for global variable ‘alt’
signatures.SBS.plot: no visible binding for global variable ‘value’
```

For the plotting functions you could use `aes_string()` instead of `aes()` to resolve the issue.

## The DESCRIPTION file

- [x] I would recommend to move the `Name` field entry to the `Title` field entry and remove the `Name` field.
- [x] The `parallel` package is missing in `Imports`
- [x] It is not necessary to define the R version in `Depends` but if you do, please update it to the current release (`4.2.0`)
- [x] I would recommend to change the `BugReports` field to `BugReports: https://github.com/danro9685/SparseSignaturesPlus/issues`

## The NAMESPACE file

- [x] Please use `camelCase` or `snake_case` for function names and avoid the use of `.` as this indicates a method in the S3 class system. 
- [ ] Selectively import the needed functions via `@importFrom` instead of importing the whole package via `@import`. Also make sure that you specifically import functions rather than calling them via `pkg::function` within the code.

## The NEWS file

- [x] The package version in the `NEWS.Rd` file does not match the package version in `DESCRIPTION`.
	  
## Package data

- [ ] For the user it might be nice to see where the data can be accessed online. You could consider adding a link to the original data repository.

## Documentation

**Vignette**

- [x] From the vignette it is not clear how the signatures are computed. Please add more details on the actual approach especially considering that there is currently no manuscript linked in the vignette. 
- [x] The vignette states that `SparseSignaturesPlus` supports different types of mutational signatures including MNV, CX, and CN. If this is part of the functionality of `SparseSignaturesPlus` it should also be highlighted in the vignette. Looking at the man pages I did not find information on how to compute the different types of signatures. 
- [x] It is recommended to provide the vignette in `.Rmd` format using `BiocStyle`. I would propose to merge the 2 `.Rmd` vignettes that you already have so that your vignette contains an Introduction section and use `BiocStyle` for formatting. The name of the vignette could be `SparseSignaturesPlus.Rmd` as currently the `.Rnw` vignette can only be accessed via `vignette("vignette")` in R. Please refer to the [vignettes](https://contributions.bioconductor.org/docs.html#vignettes) section for more info.
- [x] The package name indicates that `SparseSignaturesPlus` is a follow-up package to `SparseSignatures`. In the Introduction of the vignette, please refer to `SparseSignatures` and how the current package is different. In this context you can motivate the inclusion of `SparseSignaturesPlus` into Bioconductor.   
- [x] Please add an Installation section to the vignette highlighting the Bioconductor installation instructions in an `eval=FALSE` chunk.
- [ ] You could consider refering to existing packages that compute mutational signatures and how they differ from `SparseSignaturesPlus`.

**Man pages**

- [x] It is recommended to add a package-level man page which can be accessed via `?SparseSignaturesPlus`.
- [x] At least 80% of man pages documenting exported objects must have runnable examples. Please add examples to the functions that currently don't contain any.

## Unit tests

- [ ] Please consider adding unit tests covering the main functions of your package.

```
SparseSignaturesPlus Coverage: 0.00%
R/data.import.R: 0.00%
R/mutational.signatures.discovery.R: 0.00%
R/mutational.signatures.significance.R: 0.00%
R/visualization.R: 0.00%
```

## R code

- [ ] Please address the following errors flagged by `BiocCheck`. In general it is not recommended setting a seed within but rather directly before calling the function. 

```
* NOTE: Avoid 1:...; use seq_len() or seq_along()
* NOTE: Avoid 'cat' and 'print' outside of 'show' methods
* NOTE: Avoid using '=' for assignment and use '<-' instead
* WARNING: Avoid class membership checks with class() / is() and == / !=; Use is(x, 'class') for S4 classes
* WARNING: Remove set.seed usage (found 4 times)
* WARNING: Avoid the use of 'library' or 'require' in R code
```

- [ ] Please add validity checks for all function arguments. 
- [ ] It is recommended to use `BiocParallel` for parallelisation. The way you set up parallelised computations appreas quite complex and using `BiocParallel` might help with that. 
- [x] It is recommended to indicate non-exported functions with a `.` prefix.
- [x] I would recommend to unquote function names. 
- [ ] Some lines such as the one below are difficult to parse. It is recommended to shorten them by creating input variables before the function call and by adding line breaks. 
    
```
res <- cv.glmnet(cbind(t(curr_beta_values),matrix(rep(0,ncol(curr_beta_values)),ncol=1)),as.vector(x[j,]),type.measure="mse",nfolds=10,nlambda=10,family="gaussian",lower.limits=0.00)
```

**Comment by danro9685** [comment]
Dear @nilseling,

Thanks for your very detailed review of our package.

We have just pushed on the GitHub page of the tool changes addressing: (i) all your points for "General package development", "The DESCRIPTION file" and "The NAMESPACE file" and (ii) most of your points for "Documentation" and "R code". We are taking care of the remaining things as soon as possible.

In the mean time, we wanted to ask your advice regarding the package name. This tool (SparseSignaturesPlus) implements a new algorithm for mutational signatures analysis. The related paper is in preparation and will be referred in the package as soon as it is ready, but we don't think this will happen by the next Bioconductor release. To this end, besides providing details on the algorithm, do you think it would make sense to also change the package name? Maybe this would reduce the confusion regarding the already published SparseSignatures algorithm, from which SparseSignaturesPlus takes some inspiration, but the two methods are different.

Please let us know your thoughts.
Thanks,
Daniele and @luca-dex

**Comment by nilseling** [comment]
Hi @luca-dex and @danro9685 

I would then propose to change the name of the package to avoid confusion. If you agree with this I will close this issue and wait for you to open a new issue with the new name (see [package name](https://contributions.bioconductor.org/package-name.html) for guidance). We will then fast track the issue and I will continue with the review where we left off here. Does that sound alright?

**Comment by danro9685** [comment]
Dear @nilseling,

This sounds great, as new name, what about: RESOLVE (Robust EStimation Of mutationaL signatures Via rEgularization).
If this is good, we can proceed as you suggested.

Thanks,
Daniele and Luca

**Comment by nilseling** [comment]
Sounds good. I had a quick check with `available("RESOLVE")` and the name seems to be alright. I will close this issue now - please open a new issue using `RESOLVE`

**Comment by danro9685** [comment]
Dear @nilseling I have opened the issue for the new package.
Please add @luca-dex as primary maintainer of the package.
Thanks!
