### ISSUE TITLE
(inactive) InSituType

### ISSUE THREAD

**Issue by davidpross** [Bioconductor/Contributions#2799]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nanostring-Biostats/InSituType

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Vignettes do not explain or give a reference to CosMx.  Please give scientific role of the package/technology in the vignette introductions so that newcomers are given context.

**Comment by davidpross** [comment]
> Vignettes do not explain or give a reference to CosMx. Please give scientific role of the package/technology in the vignette introductions so that newcomers are given context.

Hi @vjcitn, thanks for taking a look at our package and the feedback. Good timing, the [CosMx paper](https://www.nature.com/articles/s41587-022-01483-z) was released online yesterday. I added a reference to the paper to the vignettes as well as a short description and a reference to the public dataset. I bumped the version of the package to 0.99.1 along with these changes.

Let me know if there are any other items to address to move package forward in submission process. Thanks!

**Comment by vjcitn** [comment]
Thanks for being so responsive.  Now I feel we need to think about interoperability.
```
counts <- mini_nsclc$counts
str(counts)
#>  num [1:2198, 1:960] 0 0 0 0 0 0 0 0 0 0 ...
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : chr [1:2198] "c_3_18_2" "c_3_18_3" "c_3_18_4" "c_3_18_5" ...
#>   ..$ : chr [1:960] "AATK" "ABL1" "ABL2" "ACE" ...
counts[25:30, 9:14]
#>           ACTA2 ACTG2 ACVR1 ACVR1B ACVR2A ACVRL1
#> c_3_18_39     0     0     0      0      0      0
#> c_3_18_40     0     0     0      0      0      0
#> c_3_18_41     1     0     1      0      0      0
#> c_3_18_45     2     0     0      0      0      0
#> c_3_18_46     0     0     0      0      0      0
#> c_3_18_47     0     0     0      0      0      0
```
is from the "clustering a small..." vignette.  Bioconductor packages use SummarizedExperiment or related classes whenever possible to help bind metadata about experiments and features right to the numerical quantifications.  Please consider adopting this discipline.

**Comment by davidpross** [comment]
> Bioconductor packages use SummarizedExperiment or related classes whenever possible to help bind metadata about experiments and features right to the numerical quantifications. Please consider adopting this discipline.

I've opened [an issue](https://github.com/Nanostring-Biostats/InSituType/issues/177) in our repository to track this suggestion. I don't think it is something that can be integrated for the timeline of the 3.16 Bioconductor release. Is it a requirement for inclusion in that release?

In the interim our package can be used in related workflows by extracting and transforming the counts matrix, `t(assays(se)$counts)`.

**Comment by lshep** [comment]
Interop would need to be implemented in some fashion before inclusion.

**Comment by davidpross** [comment]
With [this PR](https://github.com/Nanostring-Biostats/InSituType/pull/178) I added the option to use a `SingleCellExperiment` class object with the core package functions `insitutype` and `insitutypeML` and to retrieve the counts matrix from that object. In addition there is a new vignette detailing how to use `insitutype` with a SingleCellExperiment object.

**Comment by davidpross** [comment]
Hello @vjcitn and @lshep, with Bioconductor Release 3.16 just ahead, how can we move this forward in the review process? Thanks!

**Comment by vjcitn** [comment]
I'd suggest you look at your vignettes, which do not use BiocStyle, and compare them to others in the ecosystem. The early screens of NSCLC-clustering-SingleCellExperiment-vignette.html are dominated by loading messages and data dumps, and
```
# define cluster colors:
cols <-
  c(
    '#8DD3C7',
    '#BEBADA',
    '#FB8072',
    '#80B1D3',
    '#FDB462',
    '#B3DE69',
    '#FCCDE5',
    '#D9D9D9',
    '#BC80BD',
    '#CCEBC5',
    '#FFED6F',
    '#E41A1C',
    '#377EB8',
    '#4DAF4A',
    '#984EA3',
    '#FF7F00',
    '#FFFF33',
    '#A65628',
    '#F781BF',
    '#999999'
  )
cols <- cols[seq_along(unique(unsup$clust))]
names(cols) <- unique(unsup$clust)

par(mfrow = c(1, 2))
par(mar = c(0, 0, 3, 0))

plot(mini_nsclc$x, mini_nsclc$y, pch = 16, cex = .75, asp = 1, cex.main = 0.75,
          main = "cells in physical space",
     col = cols[unsup$clust], xlab = "", ylab = "", xaxt = "n", yaxt = "n")

plot(mini_nsclc$umap, pch = 16, cex = .75, asp = 1, cex.main = 0.75,
     main = "cells in UMAP space",     
     col = cols[unsup$clust], xlab = "", ylab = "", xaxt = "n", yaxt = "n")
legend("bottomleft", pch = 16, col = cols, legend = names(cols), cex = 0.7)
```
isn't indicative of a user-friendly procedure. Can you have plot methods with reasonable defaults that are callable with concise code?

**Comment by HelenaLC** [comment]
Hey there, as it's been 2 weeks, just a note in case this wasn't clear: We usually don't start formal review until there's a clean (warning- and error-free) build on on the Bioc system (see report above). If you have any questions regarding current issues, feel free to ask/discuss here.

**Comment by davidpross** [comment]
I've updated the package on GitHub to fix the errors in the build report. I am unable to push the changes to `git@git.bioconductor.org:packages/InSituType` though, I get the following error: `FATAL: W any packages/InSituType patrickjdanaher DENIED by fallthru`. Is it possibly because in the version on bioconductor.org I am not the package maintainer? The error mentions patrickjdanaher which is the GitHub handle for the maintainer listed in the DESCRIPTION file currently on the bioconductor.org git. In the [changes ](https://github.com/Nanostring-Biostats/InSituType/pull/183) I've recently made on the GitHub branch I am now the package maintainer.

**Comment by lshep** [comment]
Please try again. We have resolved the issue on our end and you should be able to push now.

**Comment by HelenaLC** [comment]
Here a few initial comments. Note that some are suggestions and, although desirable, not strictly required (e.g., "encourage."). I marked some with !!! that are arguably more significant. Please comment back here with what has/not been addressed how/why not, or any comments regarding any needed clarification or questions you might have; happy to help/discuss. Cheers!

# `DESCRIPTION`

- [ ] style/typos/grammar in the `Description:` field: Insitutype > InSituType, in which cells both > in which both

- [ ] perhaps worth adding "Spatial" under `biocViews:`

- [ ] `LazsyData: TRUE` should be removed or set to `FALSE` (see [here](http://contributions.bioconductor.org/description.html?q=lazy#description-lazydata))

- [ ] `Depends: R (>= 3.5.0)` doesn't seem very reasonable and should be removed as Bioc 3.17/.18 (where `inSituType` will end up) is incompatible with anything <4.2

- [ ] The `umap` package is currently used only in `flightpath_layout.R`. I'd suggest moving it from `Imports:` to `Suggests:` as to not have `InSituType` depend on it. See [here](http://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances) for details as to why this might be desirable.

# vignette

- [ ] We encourage using `BiocStyle::html_document` as rendering target.

- [ ] To highlight / distinguish code from normal text, I'd recommend consistently using back-ticks.

- [ ] Similarly, when mentioning R packages, `BiocStyle` has designated functions that highlight and hyperlink them, e.g., `r Biocpkg("...")` (there are similar commands for CRAN and GitHub packages). This is nice in that it distinguishes packages from plain code and directly directs users to external packages.

- [ ] Especially in the vignette, I would suggest sticking to a 80-character limit to assure code readability (especially when displayed in an online browser). Perhaps worth switching to 4-space tab indentation as opposed to vertical alignment as well to prevent large amounts of additional white space.

# code

- [ ] Avoid `sapply()` and use `vapply()` instead.

- [ ] Avoid `1:...` and use `seq_len/along()` instead.

- [ ] Avoid `paste/0()` in `message/stop()`; just this `message/stop("text", "more text")` works.

- [ ] For `insitutype()` (and any other function using `message()`), I'd suggest adding a `verbose` argument such that user can choose whether or not to print information of progress to the console.

- [ ] !!! I can see some S4 methods for `SingleCellExperiment` (e.g., `insitutype/ML()`), however, this is not consistently implemented. It'd be desirable to have functions work on both raw inputs (e.g., matrix) or Bioc objects (e.g., SCE) via extracting relevant pieces of data (see also comment below regarding `mini_nsclc`).

- [ ] I find the code-style currently quite difficult to read, largely due to vertical alignment and, consequently, 80+ characters in a lot of places... perhaps worth considering [this](http://contributions.bioconductor.org/r-code.html?q=style#coding-style) in the future.

# documentation

- [ ] Please add documentation for any `data` (e.g., source information under a `?data` page, and/or `inst/scripts` code for how the data were generated).

- Just in case this wasn't on purpose, you can use `@importFrom package function1 function2` instead of having a separate line per imported function.

- [ ] Throughout the DESCRIPTION, README, vignette etc., you refer to "insitutype". I'd suggest strictly distinguishing between "insitutype" and "InSituType" when referring to the function and package, respectively (in code-style / with back-ticks in either case).

# other

- [ ] !!! The `mini_nsclc` example dataset is currently a list of target & negative probe counts, xy-coordinates, and a UMAP. This could easily be stored in a `SingleCellExperiment` (SCE) or `SpatialExperiment` (SPE) instead, which would make for a more comprehensible object that inter-operates nicely with existing Bioc infrastructure.

- [ ] !!! Related to the above, and as Vince already pointed out, the visualizations are currently very cluttered and far from user-friendly. Using a SCE/SPE instead would allow you to, for example, use `scater` for visualization (e.g., `plotUMAP()` or, more generally, `ggcells()`). Even constructing a `data.frame` of cell metadata and spatial coordinates, and plotting with `ggplot2` would greatly improve this already.

- [ ] There are currently two licenses. The DESCRIPTION points to LICENCE (not the .md), though this one is empty and the .md it not. Please resolve this to keep one file only.

- [ ] In the README, please include Bioc installation instructions with `BiocManager`. I see there are place-holder installation instructions in the vignette; I'd say that these can be omitted as they will be included automatically on the Bioc website where the package vignette is to be found eventually.

- [ ] There are currently a few superfluous files in the package's base directory that should not be on Bioc's GH (e.g., by removing them or including them under .gitignore) e.g., *reqs.md* and *specs.md*, any *vignettes/.html* files (the *.lintr* should be sufficient to keep on you local but not the Bioc branch, I believe).
