### ISSUE TITLE
Statial

### ISSUE THREAD

**Issue by fame2827** [Bioconductor/Contributions#2818]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/Statial

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Your README.md has "The goal of betAS is to ... This is a line from RStudio".

**Comment by fame2827** [comment]
Hi @vjcitn looks like you might have the wrong package :)

**Comment by DarioS** [comment]
Statial is a package for analysing colocalisation of cell types. Its relevance to Bioconductor is strong. My findings are:
• The vignette has a good introduction to the problem domain and it introduces a timely and relevant data set for demonstrating the functionality of the package.
• Please update installation instructions to use BiocManager instead of devtools.
• The `cellType` vector is confusing. It is more of a cell ID rather than a cell type. It looks like you manually type out the cell types instead (e.g. `bcells <- c("BC1", "BC2", "BC3")`). If the user has one thousand cells, do they have to type out each one of the one thousand cells, like the example code shows?
• Scatter plot. Make the plot area smaller and the axes font size bigger to improve readability.
• Vignette mentions Keren et al. 2018 and Ferguson et al. 2022. Please provide full references at the end of the vigette.
• A recent requirement of Bioconductor packages is [Unit Tests](https://contributions.bioconductor.org/tests.html). Most of your functions need to have unit tests. See the developer's guide for more guidance about those.
• The documentation of exported functions is brief. You need a Description section and, sometimes, also a Details section.
• [Use vapply instead of for loops where applicable](https://contributions.bioconductor.org/r-code.html#code-syntax-and-efficiency). See also [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) section.
```r
parentDfs <- list()
for (i in seq_along(names(parentList))) {
  parentDfs[[i]] <- crossing(
  from = parentList[[i]],
  parent_name = names(parentList)[i])
}
```
Your code has for loop structures which could easily be converted into the Bioconductor requirement.
• Please use informative variable names that would be easily understood by a new programmer reading the code.
```r
p$d <- cut(p$d, Rs, labels = Rs[-1], include.lowest = TRUE)
w <- rep(1, length(X))
p$wt <- rep(1, length(p$d))
```
All these single-character variable names are hard to read and not consistent with the principle of [self-documenting code](https://en.wikipedia.org/wiki/Self-documenting_code).
• Only one function, `inhomL`, depends on `data.table`. Could you achieve the same result in another way and avoid this package dependency to make package installation and loading slightly faster?
• Some robustness against incorrect user input would be beneficial. For example, if `cells` is not either a `SingleCellExperiment` or `list` or `SpatialExperiment`, then it won't be caught and notified to the end user.
• SpatialExperiment is just mentioned once in the repository.
> `cells`: A SingleCellExperiment or **SpatialExperiment** or a list of single images.

Does the package provide interoperability with `SpatialExperiment` or not? Given that it is a spatial omics data analysis package, I think users would naively expect it to have interoperability with `SpatialExperiment`. Also, for "a list of single images", what class does each element of the list need to have? Explicitly state this somewhere.

**Comment by fame2827** [comment]
Hi Dario, thanks for your feedback! Regarding the cellType vector, these are in fact cellTypes the Ferguson data unfortunately has cellType names which look like cellIDs. I do agree it's confusing, would you have any suggestions on how I can make this clearer?

**Comment by DarioS** [comment]
Ah, now I get it! They are basically different subtypes of a cell type. This data could be ideal for [TreeSummarizedExperiment](https://bioconductor.org/packages/release/bioc/html/TreeSummarizedExperiment.html).

> `TreeSummarizedExperiment` has extended `SingleCellExperiment` to include hierarchical information on rows or columns.

**Comment by fame2827** [comment]
@DarioS I have addressed most of the feedback. Regarding the data.table import, data.table speeds up the inhomL function considerably which, if not included would slow down every function in Statial. At the cost of slightly slower import times, could I leave this import in, so that the overall package performs efficiently.

In the meantime I will be updating the descriptions sections of documentation. Let me know what you think!

**Comment by DarioS** [comment]
That's a good plan. Think of Title ≡ one sentence and Description ≡ one paragraph.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fame2827.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Statial")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Statial

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
