### ISSUE TITLE
planttfhunter

### ISSUE THREAD

**Issue by almeidasilvaf** [Bioconductor/Contributions#2835]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/almeidasilvaf/planttfhunter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by almeidasilvaf** [comment]
Package resubmission after name change, as suggested by @vjcitn in #2811.

**Comment by almeidasilvaf** [comment]
Hi, @vjcitn 

I submitted this package 6 days ago, before the deadline for possible inclusion on Bioc 3.16, and it is still awaiting moderation. Other submissions after this one already have a reviewer assigned. 

I have already changed the name, as you proposed in #2811. Is there anything else I need to do?

Best,
Fabricio

**Comment by lazappi** [comment]
Hi @almeidasilvaf

Thanks for submitting **planttfhunter** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## Documentation

### Vignette

- [ ] :rotating_light: Please mention these in the *Introduction*
  - [ ] :rotating_light: Motivation for including your package in Bioconductor
  - [ ] :rotating_light: Existing package that have similar functionality and comparison to them (if applicable)
- [ ] :warning: I think most of the functionality depends on having **HMMER**, it would be good to be clearer about which functions are **HMMER** wrappers and which are new functionality of your package
- [ ] :warning: I think the solution for using example data in the package when **HMMER** isn't available works but it would be good to explain in the text that is the case so it's clear for users

### Man pages

- [ ] :green_circle: It is recommended to add a package man page `usethis::use_package_doc()`

## Unit tests

- [ ] :warning: I think its probably better to use `testthat::expect_s3_class()` or `testthat::expect_type()` rather than `testthat::expect_equal(class(object), "class")`

## Code

### R

- [ ] :warning: When creating temporary files I think it's probably better to use `tempfile()` directly rather than `file.path(tempdir(), "file.name")` or when you are creating multiple files just get the temp directory once like:

```r
work_dir <- tempdir()
file1 <- file.path(work_fir, "file1.ext")
file2 <- file.path(work_fir, "file2.ext")
```
- [ ] :green_circle: I wonder if there is a better way to encode the different labels in the family checking functions? I'm not really familiar with these but I would be worried that I could easily get some of the conditions in the wrong order. I think a `switch` statement could maybe be used for some of the simpler ones but not sure about the more complex cases.
- [ ] :green_circle: Maybe it would be clearer to rename `is_valid()` to something like `is_valid_cmd()` so the name tells you want kind of validity it is checking?

## Additional files

- [ ] :warning: There is non-standard `dev/` directory in the repository. It seems to have been created by **{biocthis}** though and is included in `.Rbuildignore` so it could be ok. Maybe @Bioconductor/core can clarify?

**Comment by almeidasilvaf** [comment]
Hi, @lazappi 

Thank you for your time to review this package. Here are my replies to each of your points.

> ## Documentation
> ### Vignette
> * [x]  rotating_light Please mention these in the _Introduction_
>   
>   * [x]  rotating_light Motivation for including your package in Bioconductor

Done. I included more details on how this package interoperates with other Bioconductor packages.

>   * [x]  rotating_light Existing package that have similar functionality and comparison to them (if applicable)

Not applicable.

> * [x]  warning I think most of the functionality depends on having **HMMER**, it would be good to be clearer about which functions are **HMMER** wrappers and which are new functionality of your package

That was actually a mistake I made in the vignette. The only function that requires HMMER is `annotate_pfam()`, and this was already indicated in the vignette. There was an if statement to check if HMMER was installed for the function `classify_tfs`, but it should not have been there, as `classify_tfs()` does not depend on HMMER. I've also added a sentence explaining that the wrapper function `get_tf_counts()`, which does everything in a single step (from a list of `AAStringSet` objects to a `SummarizedExperiment` of TF counts), also requires HMMER, as it uses `annotate_pfam` under the hood. 

> * [x]  warning I think the solution for using example data in the package when **HMMER** isn't available works but it would be good to explain in the text that is the case so it's clear for users

Done. I added a note to make this clear.

> 
> ### Man pages
> * [x]  green_circle It is recommended to add a package man page `usethis::use_package_doc()`

Done.

> ## Unit tests
> * [x]  warning I think its probably better to use `testthat::expect_s3_class()` or `testthat::expect_type()` rather than `testthat::expect_equal(class(object), "class")`

Disagree, as they are not the same. For instance, the following test would fail:

```
m <- matrix(c(1,2,3,4), ncol=2)
expect_type(m, "matrix")
```

Thus, I did not change the tests. The package has test coverage of 100%, anyway. 

> 
> ## Code
> ### R
> * [x]  warning When creating temporary files I think it's probably better to use `tempfile()` directly rather than `file.path(tempdir(), "file.name")` or when you are creating multiple files just get the temp directory once like:
> 
> ```r
> work_dir <- tempdir()
> file1 <- file.path(work_fir, "file1.ext")
> file2 <- file.path(work_fir, "file2.ext")
> ```

Done. 

> * [X]  green_circle I wonder if there is a better way to encode the different labels in the family checking functions? I'm not really familiar with these but I would be worried that I could easily get some of the conditions in the wrong order. I think a `switch` statement could maybe be used for some of the simpler ones but not sure about the more complex cases.

I wondered the same thing during the development of this package. `switch` statements would be helpful in a tiny fraction of them, because classification schemes are complex (they vary based on number of domains, and on the presence/absence of auxiliary domains). One could get them in wrong order, but that's what unit tests are for, right?

> * [x]  green_circle Maybe it would be clearer to rename `is_valid()` to something like `is_valid_cmd()` so the name tells you want kind of validity it is checking?

Done.

> ## Additional files
> * [x]  warning There is non-standard `dev/` directory in the repository. It seems to have been created by **{biocthis}** though and is included in `.Rbuildignore` so it could be ok. Maybe @Bioconductor/core can clarify?

This is an old discussion (see here, for instance: https://github.com/lcolladotor/biocthis/issues/21). There is no problem with `/dev` directories, and they are present in several Bioc packages. Besides, as you rightly pointed out, they are listed in .Rbuildignore, so neither R CMD check nor `BiocCheck()` flags them as a problem.


Best,
Fabricio

**Comment by lazappi** [comment]
This looks good from my point to view now. The only reason I haven't marked this as accepted is because of the `dev/` directory. I know this has been discussed before (and personally I think it's fine) but I think the official position is still that these shouldn't be included so I would like to hear from @Bioconductor/core on whether this is ok or not.

**Comment by lshep** [comment]
Yes it is okay. If you are comfortable please accept.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/almeidasilvaf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("planttfhunter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/planttfhunter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/almeidasilvaf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("planttfhunter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/planttfhunter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
