### ISSUE TITLE
RESOLVE

### ISSUE THREAD

**Issue by danro9685** [Bioconductor/Contributions#2841]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/danro9685/RESOLVE

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nilseling** [comment]
Hi @lshep, 
this issue addresses the package name change from #2798. Could you please add @luca-dex as maintainer?
Thanks for your help with this!

**Comment by danro9685** [comment]
Dear @nilseling,

We should have addressed all the issues you have listed in your previous post.
Moreover, @luca-dex also added package name to Watched Tags, so the ERROR should also have been dealt with.

Please let us know if you have additional comments.

Thanks,
Daniele & @luca-dex

**Comment by nilseling** [comment]
Hi @danro9685 and @luca-dex
thanks for addressing most of the comments. There are still some that have not been addressed and I'd like to ask you to comment on the points below once you address them or give an explanation if you are not planing on adapting them.

- [x] The vignette title is missing.
- [ ] Please include a motivation for `RESOLVE` to be included in Bioconductor (in the Introduction section of the vignette). This can be done by referencing existing packages within Bioconductor that perform similar things.
- [x] I would recommend setting `message=FALSE` in chunks where you load packages to suppress startup messages.
- [x] The unit tests are OK for now but on the long run we recommend to increase the code coverage.

```
RESOLVE Coverage: 41.91%
R/visualization.R: 0.00%
R/mutational.signatures.discovery.R: 47.64%
R/mutational.signatures.significance.R: 70.99%
R/data.import.R: 97.14%
```
- [x] Please add `sessionInfo()` to the vignette.
- [x] Please address the following R code issues:

```
* NOTE: Avoid 1:...; use seq_len() or seq_along()
* NOTE: Avoid 'cat' and 'print' outside of 'show' methods
* NOTE: Avoid using '=' for assignment and use '<-' instead
* WARNING: Avoid the use of 'library' or 'require' in R code
```

- [x] The last R code issue relates to the use of `parallel`. Would you consider using `BiocParallel` for parallel computation?
- [x] The recommended line length is 80 characters and you can use line breaks to make some of your long lines more readable.

**Comment by danro9685** [comment]
Dear @nilseling,

1) In the latest update on GitHub we should have addressed all your points regarding the vignette.
2) Sounds good about the unit tests.
3) Regarding BiocParallel: we are planning to move to BiocParallel for parallel computation, however the current implementation is quite complex and we don't think we enough bandwidth (among this and the work for the other packages we have submitted/support) to perform these changes (without including bugs) by the upcoming release. Would it be acceptable if we plan to upgrade the package in the future, after acceptance?
4) R code: the WARNING: Avoid the use of 'library' or 'require' in R code is related to Q3, as the function library is used for the parallel computation. We will remove this when moving to BiocParallel.
Furthermore: Avoid 1:...; use seq_len() or seq_along() should be fixed now.

Please let us know if we missed anything or if you have any additional feedback while we address the remaining things.

Thanks,
Daniele and @luca-dex

**Comment by nilseling** [comment]
Hi @danro9685 and @luca-dex

> 1. In the latest update on GitHub we should have addressed all your points regarding the vignette.

Thanks for adding the title and more general info on how to detect mutational signatures. I think what would still help the user is to understand why `RESOLVE` is part of Bioconductor instead of e.g. CRAN. You have already developed the `SpareSignatures` Bioconductor package and it would be straight forward for users that are familiar with this package to now also use `RESOLVE`. You could add a sentence or two in the vignette stating that `RESOLVE` is an addition to other  Bioconductor packages such as `SparseSignatures`, `MutationalPatterns`, `musicatk`, among others that now implements a new approach for detecting mutational signatures.    

> 2. Sounds good about the unit tests.

Done

> 3. Regarding BiocParallel: we are planning to move to BiocParallel for parallel computation, however the current implementation is quite complex and we don't think we enough bandwidth (among this and the work for the other packages we have submitted/support) to perform these changes (without including bugs) by the upcoming release. Would it be acceptable if we plan to upgrade the package in the future, after acceptance?

I think it's fine to adapt the package after release. 

> 4. R code: the WARNING: Avoid the use of 'library' or 'require' in R code is related to Q3, as the function library is used for the parallel computation. We will remove this when moving to BiocParallel.
>    Furthermore: Avoid 1:...; use seq_len() or seq_along() should be fixed now.

Thanks for addressing these warnings and notes and the warning regarding the `library` call will be ignored for now. However, there are new NOTEs in your R code :

```
NOTE: Avoid the use of 'paste' in condition signals
```

This one relates to lines like:

```
message(paste0("Performing repetition ", cv_repetitions, " out of ",
                    cross_validation_repetitions, "..."), "\n")
```

which you can simply fix by:

```
message("Performing repetition ", cv_repetitions, " out of ",
                    cross_validation_repetitions, "...", "\n")
```

The following NOTE

```
* NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions
```

relates to 

```
results <- tryCatch({}, error = function(e) {
                    message(paste0("An error has occurred: ",
                      e$message), "\n")})
```

which you can simply resolve by:

```
results <- tryCatch({}, error = function(e) {
                    paste0("An error has occurred: ", e$message, "\n")})
```

> Please let us know if we missed anything or if you have any additional feedback while we address the remaining things.

Could you please push these changes to Bioconductor to trigger another built?

**Comment by danro9685** [comment]
Dear @nilseling,

Thanks for the feedback, we have just updated our GitHub repository with all the necessary changes.
@luca-dex please perform the push to Bioconductor.

Thanks,
Daniele

**Comment by nilseling** [comment]
Hi @luca-dex,

could you please push the changes to Bioconductor so that the checks pass before Wednesday? 
Let me know if there are issues with the access rights.

**Comment by luca-dex** [comment]
Hi @nilseling ,

last week the system was not accepting the push, but I just tried again and it worked.

Thanks

**Comment by nilseling** [comment]
Thanks for pushing the changes! I will now accept the package. For the next release I would recommend to switch to `BiocParallel` to address the last `WARNING`.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/danro9685.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RESOLVE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RESOLVE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
