### ISSUE TITLE
NADfinder

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#285]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/NADfinder

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
Vignette needs development. Glanced at the `tileCount()` function. Consider using `slidingWindows()` instead of `tileGRanges()`. You can coerce a Seqinfo to a GRanges with `as(x, "GRanges")`. The code checks for a GRangesList representing multiple samples using an odd heuristic. First, for efficiency reasons, the user should use SimpleGenomicRangesList to represent data over several samples, not GRangesList, so this code should check for GenomicRangesList, not GRangesList. Second, it would probably be best to provide an argument rather than rely on a heuristic. The code could be cleaned up there, e.g., using `head()` to select the first 100, using `lengths()`, etc. I think you could also use the `cbind()` method on SummarizedExperiment to combine the overlap results. Why convert the SummarizedExperiment to a GRanges at the end?

**Comment by mtmorgan** [comment]
DESCRIPTION

- Provide more specific biocViews terms

vignette

- Provide a narrative better explaining use of the package, rather
  than the currrent more-or-less minimally annotated script.

R

- Please indicate how you have responded to @lawremi's comments
- e.g., callPeaks.R:87 use `rowMeans(.)` rather than `apply(., 1,
  mean)` for efficiency. Use vectorized rather than iterative
  operations in place of other uses of `apply()`,
  e.g.,getCorrelations.R:75 `rowSums(.ele >= cutoff) == ncol(.ele)`
- Use `seq_len(.)` or `seq_along(.)` rather than `1:.` to avoid
  problems when `. == 0`.
  
man

- for each parameter, indicate argument type (e.g., `logical(1)`) and
  clearly define how the parameter is used. Example of poor
  documentation: countByOverlaps inter.feature argument is documents
  as 'inter feature' -- what is the user suppsoed to do with this
  information? Indeed, the argument is ignored, so why is it presented
  to the user? Please review ALL documentation.

**Comment by jianhong** [comment]
Thanks  @lawremi and @mtmorgan for the comments.

I tried to update the packages by the changes as followings:

# biocViews

* add DNASeq, PeakDetection

# vignette

* provide more details to explain how to use the package.

# R

* change GRanges to RangedSummarizedExperiment to record the counts, ratios, correct ratios, smoothed ratios and z-scores.
* change the function name from plotCorrelations to getCorrelations to give more freedom in plotting the correlations.
* change the function name from sig2bedgraph to exportSignals to allow users to export signals in other formats.
* change function tileGRanges to slidingWindows to avoid misleading. Indeed I did not notice that there is a function slidingWindows already in GenomicRanges package. Should I remove this function?
* add new function cumulativePercentage for quality control.
* try to use vectorized rather than iteractive operations in place of other uses of `apply()`.
* use `seq_len` and `seq_along` to replace `:`

# man

* indicate argument type for each parameter in the documentations. 
* add more descriptions in documentation.

**Comment by mtmorgan** [comment]
Thanks I'm accepting the package to Bioconductor. It will be added to our nightly builds and svn repository, with additional information via email in a couple of day.s

**Comment by jianhong** [comment]
Thank you @mtmorgan.

I will continue to update the documentations.

**Comment by mtmorgan** [comment]
Please be sure that your changes are ported to the svn repository, which is now available with your existing svn credentials at https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/NADfinder

**Comment by jianhong** [comment]
Thank you for reminder. I got it.

**Comment by lawremi** [comment]
Yes, the hope was that you would use the `slidingWindows()` function in GenomicRanges.
