### ISSUE TITLE
(inactive) edgeCounter

### ISSUE THREAD

**Issue by yeyuan98** [Bioconductor/Contributions#2856]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yeyuan98/edgeCounter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
commit 4bd6ababfc909e979dcb6f7cb5f8cc9a9ddde1ea
Author: jorainer <johannes.rainer@gmail.com>
Date:   Wed Nov 9 11:42:33 2022 +0100

    fix: remove disjointExons method

```
so you can't use ensembldb::disjointExons ... try GenomicFeatures

```
Quitting from lines 96-103 (atac-demo.Rmd) 
Error: processing vignette 'atac-demo.Rmd' failed with diagnostics:
package or namespace load failed for 'ATACseqQC':
 object 'disjointExons' is not exported by 'namespace:ensembldb'
--- failed re-building ‘atac-demo.Rmd’
```

**Comment by yeyuan98** [comment]
Thanks a lot for your feedback. I think this error comes from the existing ChIPpeakAnno package. Just opened an issue to hopefully help fix that soon. Will update asap.

https://github.com/jianhong/ChIPpeakAnno/issues/21

**Comment by vjcitn** [comment]
In vignette I am seeing
```
#> Warning in restoreRecordedPlot(x, reloadPkgs): snapshot recorded in different R
#> version (4.2.1)
```

**Comment by HelenaLC** [comment]
Here a few initial comments; overall, things are in pretty good shape already. Note that some are suggestions and, although desirable, not strictly required (e.g., "encourage."). I marked especially important points with !!!. Please comment back here with what has/not been addressed how/why not, or any comments regarding any needed clarification or questions you might have; happy to help/discuss. Cheers!

# vignette

- [ ] We encourage using `BiocStyle::html_document` as rendering target.

- [ ] When mentioning R packages, `BiocStyle` has designated functions that highlight and hyperlink them, e.g., `r Biocpkg("...")` (there are similar commands for CRAN and GitHub packages). This is nice in that it distinguishes packages from plain code and directly directs users to external packages.

- [ ] !!! The chunk at line 111+ runs fast and without issues for me; why is it not being evaluated? Similarly, latter parts of the vignette are not run at all "due to package size consideration". Is there perhaps the possibility to include a small (in file size) subset of the data required to run the workflow in its entirety? Flags such as `eval = FALSE` undermine the benefit of a vignette and are generally not allowed.

# documenation

- [ ] !!! Connected to the above, there is currently no example for `varMeanPlot`, though `edgeExperimentFromCounts` has one for constructing `edges`. I understand that results might be "only meaningful with real data", however, it is desirable from both a user and developer perspective to include complete runnable examples in both documentation and vignette. Irrespective of using toy data (which you might still want to point out to the reader), this nevertheless i) can demonstrate how the function/workflow is run and what it outputs; and, ii) allow of unit-testing and testing on-the-fly (when examples are being run and the vignette is built).

- [ ] Consider adding a package *.man* page so users would get an overview of the package's basic workflow and key functions with `?edgeCounter`.

- [ ] Please add documentation of any `inst/extdata` (e.g., source information under a `?data` page, and/or `inst/scripts` code for how the data were generated); see [here](http://contributions.bioconductor.org/data.html#raw-data-and-the-instextdata-directory).

- [ ] When directing to other pieces of documentation, the correct syntax is `\code{\link[package]{function}}`. For example in *edgeExperiment.R* line 62: `@seealso [SummarizedExperiment::RangedSummarizedExperiment]` should be `\code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}`. When linking to a function of `edgeCounter` itself, the package part can be omitted, i.e., `\code{\link{function}}`. In any case, functions should be written by name only, without parentheses (this breaks the link because a link is made to the .Rd file, not the function); e.g., in *countEdges.R* lines 90+.

# other

- [ ] !!! There are currently no imports in the NAMESPACE, as all external functions are called explicitly with `package::function`. While this "looks" fine, installing `InSituType` will not install any of its dependencies. In short, this means that a user can install the package but will immediately get an error as soon as a function is run whose dependencies aren't available in the user's library by chance already. Ideally, any external functions should be imported (e.g., in roxygen-style with `@importFrom package function1 function2 ...`) if they are necessary for key functionality. Only dependencies that are perhaps optional could be included under `Suggests`: instead (see [here](http://contributions.bioconductor.org/description.html#depends-imports-suggests-enhances) for details).

- [ ] The LICENSE contains placeholders such as "name of author", "year" etc. Please fill these in.

- [ ] In the README, please include Bioc installation instructions with `BiocManager`.

- [ ] Unit test coverage is quite low currently. I'd encourage improving this:

```r
# devtools::test_coverage()
edgeCounter Coverage: 45.28%
R/edgeCounterOptions.R: 0.00%
R/zzz.R: 0.00%
R/edgeExperiment.R: 25.42%
R/ecParallel.R: 42.59%
R/utils.R: 53.40%
R/ranges.R: 97.22%
R/countEdges.R: 100.00%
```
