### ISSUE TITLE
MsBackendSql package submission

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#2859]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RforMassSpectrometry/MsBackendSql

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
Hello @jorainer - Thank you for submitting to _Bioconductor_. Reviewing the package I see no required changes. I have a few minor suggestions that could be made (which are below). Feel free to make these changes. If you don't think they will add anything to the package than just let me know and I'd be happy to accept the package as is.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
	Proteomics

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be
  included in the Bioconductor release announcements.

**This is more so a note for the devel team, which I'll bring up to them.** I see that there is a NEWS.md file provided, it looks like proper markdown code, and it renders properly in github. I'm not sure why it's saying it's not part of the package.

**Something that you might want to look into:** I did build and install the package locally with `R CMD build` and `R CMD INSTALL`. When I tried running `utils::news(package="MsBackendSql")` it resulted in `NULL`. I tried moving the file to and `inst/` directory thinking maybe it was in the wrong location but this didn't help. The code all looks correct to me, so I'm not sure on this one.

## R code

- [ ] SUGGESTION: Avoid using '=' for assignment and use '<-' instead. Found in
  files:
	R/MsBackendSql.R, line 386 
- [ ] SUGGESTION: Avoid 'suppressWarnings'/'Messages' if possible. Found 4
  times:
	`suppressWarnings()` in R/MsBackendSql-functions.R, line 183
	`suppressWarnings()` in R/MsBackendSql-functions.R, line 184
	`suppressWarnings()` in R/MsBackendSql-functions.R, line 210
	`suppressWarnings()` in R/MsBackendSql-functions.R, line 211 
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 57 
lines that are > 80 characters long.     
- [ ] SUGGESTION: For formating reasons, consider mulitples of 4 spaces for 
line indents. There are 73 lines that are not. 

Best,
Kayla

**Comment by jorainer** [comment]
Hi Kayla @Kayla-Morrell !

Thanks for your review! I've:

- added *Proteomics* to the BiocViews.
- replaced `=` by `<-`.
- removed all `suppressWarnings` calls.
- shortened some lines in the documentation. All code lines are for sure less then 80 characters long and also the roxygen documentation. I guess the lines that are still longer than 80 characters (and the 4 space indents) are generated/caused by `devtools::document` and are only present in the documentation files.

Regarding the `NEWS.md` - I could also rename that to `NEWS` if it helps - I just think it would be better to keep the .md ending if possible.

Thanks again!

cheers, jo

**Comment by jorainer** [comment]
Btw - I've pushed the changes to the *main* branch and also bumped the version, but it seems the bioc-bot did not trigger a new check?

**Comment by jorainer** [comment]
Btw - I've pushed the changes to the *main* branch and also bumped the version, but it seems the bioc-bot did not trigger a new check?

**Comment by lshep** [comment]
did you push to git.bioconductor.org master branch? 

See  step 5  of http://contributions.bioconductor.org/git-version-control.html#new-package-workflow

**Comment by jorainer** [comment]
Ups - of course I forgot that! thanks for the reminder @lshep !

**Comment by jorainer** [comment]
Is there anything missing (@Kayla-Morrell)? No urgency in this, just wanted to ensure that I'm not forgetting/missing something - or that I pushed to the wrong branch... :)

**Comment by Kayla-Morrell** [comment]
@jorainer - Sorry for the delay. I've looked over your changes and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsBackendSql")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsBackendSql

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
