### ISSUE TITLE
GeoTcgaData

### ISSUE THREAD

**Issue by huerqiang** [Bioconductor/Contributions#2862]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/GeoTcgaData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by huerqiang** [comment]
@LiNk-NY Hi, I see there is an errror: 'ERROR: System files found that should not be Git tracked. GeoTcgaData.Rproj'. I have delete this rproj file. 
And there is also a warning: 'directory GeoTcgaData/man/figures is empty'. I don't know what's causing this. The GeoTcgaData/man/figures folder isn't empty. Can you help me with this warning? Thank you very much.

**Comment by LiNk-NY** [comment]
Hi ErQiang, @huerqiang 

Thank you for your submission. Please see below. 

Best regards,
Marcel

---

# GeoTcgaData #2862

After a cursory review, it seems that the package does not integrate well with
Bioconductor. It uses `data.frame` as the common output formats, it does
not depend on any Bioconductor packages, e.g., `SummarizedExperiment`, and it
does not follow Bioconductor Package Guidelines
<https://contributions.bioconductor.org/>. Suggesting Bioconductor
packages is not enough to merit Bioconductor inclusion. If you would like the
package to be reconsidered, please make use of common Bioconductor classes
seen at
<https://contributions.bioconductor.org/important-bioconductor-package-development-features.html#reusebioc>

## DESCRIPTION

* Remove `LazyData` field
* Looks good.

## NAMESPACE

* Use the native pipe `|>` instead of `magrittr`'s `%>%`.
* Consider avoiding the vague term "diff" in function names.
* Avoid vague names e.g., `rep1` and `rep2`
* Avoid class names in functions e.g., `*_matrix`, `*_vector` instead make
clear the return value in the documentation.

**Comment by huerqiang** [comment]
@LiNk-NY Hi, we have updated the package, and now it can use SummarizedExperiment object. We have also changed functions, such as rep1, rep2,  *_matrix, and diff_*.

**Comment by LiNk-NY** [comment]
Hi ErQiang, @huerqiang 

Thank you for making those changes.
Please see the review below. 

Best,
Marcel

---

# GeoTcgaData #2862

* Update the version so that it is greater than the last known version on CRAN
(`1.1.1`)

## DESCRIPTION

* Looks good.

## NAMESPACE

* Avoid long function names like `differential_RNA_SummarizedExperiment` and
`methydifferential_SummarizedExperiment`. The name of the compatible class
does not need to be in the function name.
* Avoid using `sink` and use standard functions to suppress messages, e.g.,
`suppressMessages` etc., if necessary.

## /

* Remove the `docs` folder from the package. It gets populated when the package
is built.
* Include only one `.gitignore` in the base folder
* Remove `cran-comments.md`

## vignettes

* Avoid using `eval=FALSE` in the vignettes. Any package submitted to
Bioconductor should have a runnable vignette.

## R

* Provide a proper description and full documentation of arguments for all
functions, including `arrayDiff`.
* Describe in detail, where the data come from in `R/data.R`. If possible,
use more descriptive names.
* `Merge_methy_tcga` should take `data.frame`s as inputs rather than files. If
files are absolutely necessary, include a precise description of the files
and the directory structure. You could also provide a helper function to read
in the methylation files from a directory which could then serve as the input
to the merge operation.
* Avoid the using `sink` and remove the `quiet` function. Use
`utils::capture.output`, if needed.
* Create a single `methydifferential` / `differential_RNA` function that
handles `matrix`, `data.frame`, and `SummarizedExperiment` inputs.
* Avoid functions that work with directory inputs. Interoperable functions
should operate on the base data representations i.e., `DataFrame`, `matrix`,
etc. (see `tcga_cli_deal`)
* Remove commented code.
* See our Data section at https://contributions.bioconductor.org/data.html?q=Data#exported-data-and-the-data-directory
for `id_conversion`
* Make sure datasets in the package have proper type conversion. That is
columns like `entrez_id`, `gene_len`, `start`, `end` etc. are numeric.

## tests

* Include more tests for your functions.

```r
> covr::package_coverage()
GeoTcgaData Coverage: 2.25%
R/calculate_mean_module.R: 0.00%
R/calculate_mean_profile.R: 0.00%
R/CNV.R: 0.00%
R/fpkm_count_conversion.r: 0.00%
R/id_conversion_all.r: 0.00%
R/prepareChi.r: 0.00%
R/Proce_cli.R: 0.00%
R/rep.R: 0.00%
R/RNA_seq.R: 0.00%
R/SNP.R: 0.00%
R/TCGA_id_conversion.R: 0.00%
R/utilities.R: 0.00%
R/Merge_methylation.R: 8.07%
R/arrayDiff.R: 22.22%
```

**Comment by huerqiang** [comment]
@LiNk-NY  Hi, I have fixed these issues:
(1) Update the version so that it is greater than the last known version on CRAN
(1.1.1)
**When I update it to 1.1.2, I get the error whe push: remote: Error: Illegal version bump from '0.99.3' to '1.1.2'. So I changed it to '0.99.5'**
(2)Avoid long function names like differential_RNA_SummarizedExperiment and
methydifferential_SummarizedExperiment. The name of the compatible class
does not need to be in the function name.
**I changed to use generic functions for differential_RNA and differential_methy**
(3)Avoid using sink and use standard functions to suppress messages, e.g.,
suppressMessages etc., if necessary.
**I removed the quiet function who use sink.**
(4)Include only one .gitignore in the base folder.
**I removed other files in the base folder.**
(5)Provide a proper description and full documentation of arguments for all
functions, including arrayDiff.
Describe in detail, where the data come from in R/data.R. If possible,
use more descriptive names
**I have updated the documents of the functions and data.**
(6)Merge_methy_tcga should take data.frames as inputs rather than files. If
files are absolutely necessary, include a precise description of the files
and the directory structure. You could also provide a helper function to read
in the methylation files from a directory which could then serve as the input
to the merge operation.
**The function Merge_methy_tcga() is used to merge methylation data downloaded from TCGA. When the methylation data is downloaded from TCGA, each sample is saved in a folder, which contains the methylation value file and the descriptive file. So the input need to be a directory. And I have update the document of this function.**
(7)Avoid the using sink and remove the quiet function. Use utils::capture.output, if needed.
**I removed the quiet function.**
(8)Create a single methydifferential / differential_RNA function that handles matrix, data.frame, and SummarizedExperiment inputs.
**I changed to use generic functions for differential_RNA and differential_methy**
(9)Avoid functions that work with directory inputs. Interoperable functions
should operate on the base data representations i.e., DataFrame, matrix,
etc. (see tcga_cli_deal)
**I removed the tcga_cli_deal function.**
(10)Remove commented code
**I removed the commented code.**
(11)See our Data section at https://contributions.bioconductor.org/data.html?q=Data#exported-data-and-the-data-directory
for id_conversion
**This id_conversion function doesn't need to be used, so I removed it.**
(12)Make sure datasets in the package have proper type conversion. That is columns like entrez_id, gene_len, start, end etc. are numeric.
I am sure they are correct.
(13)Include more tests for your functions.

> covr::package_coverage()
> GeoTcgaData Coverage: 24.29%
> R/AllGenerics.R: 0.00%
> R/RNA_seq.R: 0.00%
> R/SNP.R: 0.00%
> R/TCGA_id_conversion.R: 0.00%
> R/arrayDiff.R: 4.60%
> R/Merge_methylation.R: 26.58%
> R/CNV.R: 82.76%
> R/fpkm_count_conversion.r: 89.58%
> R/calculate_mean_module.R: 100.00%
> R/calculate_mean_profile.R: 100.00%
> R/prepareChi.r: 100.00%
> R/rep.R: 100.00%

**Comment by LiNk-NY** [comment]
Hi Erqiang, @huerqiang 

Thank you for making those changes. The documentation looks better.
There are still a few unresolved comments with the package. 

> When I update it to 1.1.2, I get the error whe push: remote: Error: Illegal version bump from '0.99.3' to '1.1.2'. So I changed it to '0.99.5'

Please keep it at a version number above the CRAN release, e.g., `1.99.0`. We will update accordingly to accept the version. cc: @lshep 

* Avoid creating S3 / S4 methods for classes you do not own. `differential_methy` should be a plain function that can handle `matrix`, `SummarizedExperiment`, and other data structures.
* Remove functions e.g., `differential_methy.matrix` etc. create a plain function as above.

Best,
Marcel

**Comment by huerqiang** [comment]
@LiNk-NY Hi, I have update the version to '1.99.0' and use the plain functions 'differential_methy' and 'differential_RNA' instead of generic functions.

**Comment by lshep** [comment]
@huerqiang I have temporarily made an exception to the hook and you should be able to push the updated version to git.bioconductor.org.  Please proceed and let me know when you are finished so we can re-establish the hook when you are done to prevent any bad version numbers.  To Confirm:  it should be 1.99.0  and then any further changes simply bump the z of version x.y.z .  Cheers

**Comment by huerqiang** [comment]
@lshep Hi， I have push to the BioC and it now shows: 
```r
$ git push upstream master
Everything up-to-date
```
The version now is '1.99.0'.

**Comment by lshep** [comment]
Can you please check again and that you have the remotes set up correctly?  When I pulled from `git@git.bioconductor.org:packages/GeoTcgaData`  it is still showing 0.99.5

**Comment by lshep** [comment]
thank you!

**Comment by huerqiang** [comment]
@lshep I push it again, and it should be OK now. I don't know why it failed before.

**Comment by lshep** [comment]
yes I can see it now.  thank you.   You'll likely get a note in the BiocCheck about have 1.99.0 which can be ignored in this case.

**Comment by LiNk-NY** [comment]
Thanks Lori! @lshep

**Comment by huerqiang** [comment]
@LiNk-NY @lshep Hi, do I need to make any other changes?

**Comment by huerqiang** [comment]
@LiNk-NY @lshep Hi, since April 19 is the deadline to add new packages to the Bioc 3.17 manifest, so can we speed up the review process? Is there anything I need to change?

**Comment by LiNk-NY** [comment]
Hi ErQiang, @huerqiang 
Sorry for the delay. It looks like the package is good to go. 
Thank you for your submission. 
Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/huerqiang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GeoTcgaData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeoTcgaData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
