### ISSUE TITLE
BG2

### ISSUE THREAD

**Issue by willja16** [Bioconductor/Contributions#2871]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/marf-at-vt/BG2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Why is the issue closed?  Are you withdrawing the submission?

```
load(url("https://github.com/marf-at-vt/Case_studies/blob/main/BG2_Data/AThaliana_CaseStudy.rda?raw=true"))
```

is not appropriate in vignette.  Demonstrative data must have a durable provenance like ExperimentHub or zenodo; personal or organization github are not suitable.

Additionally, it would be good to interoperate with Bioconductor data structures for variant collections like VRanges or VcfStack.  If there is no interoperation with Bioconductor structures or methods, consider distributing via CRAN.

**Comment by willja16** [comment]
Hello,

Am I required to remove the Github URL link?

Jake Williams

**Comment by lshep** [comment]
yes. We don't allow data to be retrieved from github.  Changes corresponding to @vjcitn comments are required before an official review will take place.

**Comment by willja16** [comment]
Ok, I can make that change. After the change is made should I open a new issue or just update the my personal repo?

**Comment by lshep** [comment]
Just update your personal repo at this time and leave a message here that changes have been made to request re-approval. Cheers

**Comment by willja16** [comment]
The personal repo has been updated to reflect the changes requested. I did not change the version number.

**Comment by willja16** [comment]
Hello,

I have not recieved work about my R-Package in a couple of days. The git repo is updated with a new vignette that does not include a URL link to a github dataset. I would like my package to continue in the development cycle for Bioconductor packages.

Jake Williams

**Comment by lshep** [comment]
Please see initial review below.  When ready remember to push changes to git.bioconductor.org to trigger a new build and comment back here addressing the following concerns: 



**Build Reports**

- [ ] See notes indicated in [Build Report](http://bioconductor.org/spb_reports/BG2_buildreport_20230103142613.html)

**DESCRIPTION**

- [ ] You mention both GPL-2 | GPL-3 license in the description. This is
  unusual; why are both listed?  It seems you included GPL-3 so that should be
  sufficient

- [ ] Could you expand on the Description in the Description?  

- [ ] Consider adding biocViews for 'GenomeWideAssociation'

- [ ] We recommend removing 'LazyData:TRUE' unless you have a strong use case

**man**

- [ ] You mention a paper data is lifted from  but do not provide the
  citation. Please provide the citation

- [ ] Similar in the BG2 you reference a manuscript but then do not provide a
  citation to the manuscript. Please provide reference.

- [ ] Please provide an example in the BG2 example.


**Vignette**

- [ ] Again you mention a manuscript with no cited reference in the
  Introduction.
  
- [ ] Could you provide some information or comparison to existing Bioconductor
  packages that anaylze GWAS data and how this is different/better




**tests**

- [ ] Please provide unit test for package

**NEWS**

- [ ] We strongly suggest adding a NEWS file to keep track of package
  changes. The NEWS file is what is collated each Bioconductor release to
  announce changes and happenings to a package. 

**R code**

- [x] Some comments for the future, Separating out helper functions from the
  main function will allow reviewers to better be able to separate out what is
  doing what.  And `stopifnot` might be handy to clean up argument checking. As
  well as defining a argument in the function call like
  `family=c("poisson","bernoulli")` and then using `match.arg`

- [ ] Remove functions that are not called, not used, not exported, and not
  documented:  SMA

- [ ] There is still no interoperation with Bioconductor structures or
  methods. Vince had previously suggested maybe VRanges or VcfStack might be
  apprpriate but it would be good to see some integration of Bioconductor common
  use cases.


Thank you.

**Comment by willja16** [comment]
> **Build Reports**
> 
> * [x]  See notes indicated in [Build Report](http://bioconductor.org/spb_reports/BG2_buildreport_20230103142613.html)
> 
> **DESCRIPTION**
> 
> * [x]  You mention both GPL-2 | GPL-3 license in the description. This is
>   unusual; why are both listed?  It seems you included GPL-3 so that should be
>   sufficient
Changed to GPL-3

> * [x]  Could you expand on the Description in the Description?
Added another sentence expanding on details of BG2.
> * [x]  Consider adding biocViews for 'GenomeWideAssociation'
Done
> * [x]  We recommend removing 'LazyData:TRUE' unless you have a strong use case
Changed to LazyData:FALSE and changed the corresponding examples and vignettes appropriately
> 
> **man**
> 
> * [x]  You mention a paper data is lifted from  but do not provide the
>   citation. Please provide the citation
Added appropriate citation in all man files that referenced the paper the data was lifted from.
> * [x]  Similar in the BG2 you reference a manuscript but then do not provide a
>   citation to the manuscript. Please provide reference.
Added a reference for the BG2 manuscript.
> * [x]  Please provide an example in the BG2 example.
Done
> 
> **Vignette**
> 
> * [x]  Again you mention a manuscript with no cited reference in the
>   Introduction.
Done.
> * [x]  Could you provide some information or comparison to existing Bioconductor
>   packages that anaylze GWAS data and how this is different/better
Added information about other Bioconductor packages within the vignette.
> 
> **tests**
> 
> * [x]  Please provide unit test for package
Done.
> 
> **NEWS**
> 
> * [x]  We strongly suggest adding a NEWS file to keep track of package
>   changes. The NEWS file is what is collated each Bioconductor release to
>   announce changes and happenings to a package.
Done.
> 
> **R code**
> 
> * [x]  Some comments for the future, Separating out helper functions from the
>   main function will allow reviewers to better be able to separate out what is
>   doing what.  And `stopifnot` might be handy to clean up argument checking. As
>   well as defining a argument in the function call like
>   `family=c("poisson","bernoulli")` and then using `match.arg`
> * [x]  Remove functions that are not called, not used, not exported, and not
>   documented:  SMA
Done.
> * []  There is still no interoperation with Bioconductor structures or
>   methods. Vince had previously suggested maybe VRanges or VcfStack might be
>   apprpriate but it would be good to see some integration of Bioconductor common
>   use cases.
Thanks for the suggestion about VRanges and VcfStack. Currently, when performing the first step of BG2, which is a Bayesian single marker analysis, we estimate the regression coefficients for all generalized linear mixed models at the same time with some few matrix operations. This takes full advantage of R implementations with optimized linear algebra libraries such as Intel MKL and OpenBLAS. We are able to do that by representing all SNPs data in a single matrix. We think that if we were to represent SNPs data with VRanges or VcfStack, then computations would possibly get much slower.

**Comment by willja16** [comment]
Hello,

I have addressed all of the comments from the review. When will I here an update on BG2?

Jake Williams

**Comment by lshep** [comment]
I will look at the package sometime this week.

**Comment by lshep** [comment]
For What its worth you marked tests and NEWS as resolved but they are still missing from the git.bioconductor.org version of the repository. We still strongly strongly recommend the use of both. 
Otherwise thank you for your modifications and explanations.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/willja16.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BG2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BG2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
