### ISSUE TITLE
INTACT

### ISSUE THREAD

**Issue by jokamoto97** [Bioconductor/Contributions#2872]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jokamoto97/INTACT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jokamoto97** [comment]
Hello,
I would like to remove this submission from consideration by the Bioconductor team. The package does not interoperate with data structures listed in the Common Bioconductor Methods and Classes section of the Bioconductor website. 

Thank you,
Jeff

**Comment by vjcitn** [comment]
Can we help achieve this basic aim?  I don't think it would be too hard.

**Comment by vjcitn** [comment]
And I think the problem area you address should be part of the ecosystem if possible.

**Comment by jokamoto97** [comment]
Thank you for your responses. Is there any chance you might be able to tell me what kind of modifications I would need to make in order to achieve this aim? Of the data structures and infrastructure listed, I am not sure which would be applicable to INTACT.

**Comment by nilseling** [comment]
Hi @jokamoto97,

thank you for submitting the `INTACT` package for inclusion in Bioconductor. The package is in a good state and I have a few comments below which need to be addressed before we can accept it. Please provide a point-by-point response detailing what has been changed or explaining your design choices.

## General package development

- [ ] Regarding your comment on using a Bioconductor core class I would recommend to check out the [SummarizedExperiment](https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html) class. To adapt `INTACT` to use a `SummarizedExperiment` object you would simply need to store all relevent entries in `rowData(se)` where `se` is a `SummarizedExperiment` object. `rowData(se)` would replace the information stored in `INTACT::simdat`. The question here is if you always have the expression data available as output of the TWAS? These could be stored in `assay(se, "counts")`. Otherwise you can also use a `SummarizedExperiment` object with no `assays` specified. But since the data input for `INTACT` is a simple `data.frame` you could continue using the current implementation of the package.

## The DESCRIPTION file

- [ ] It is recommended to set the 'LazyData:' field in the 'DESCRIPTION' file to `false` or remove it.
- [ ] It won't be necessary to fix the package versions in `Imports` as the newest version will be installed as package dependencies. 
- [ ] I would recommend to add `https://github.com/jokamoto97/INTACT/issues` to the `BugReports` field.
- [ ] I would recommend to add `https://github.com/jokamoto97/INTACT` to the  `URL` field.


## The NAMESPACE file

- [ ] It is recommended to selectively import functions via `importFrom(SQUAREM,squarem)` rather than calling `SQUAREM::squarem` in your code. Since you are using `roxygen2` for documentation you can add `@importFrom SQUAREM squarem` to the `roxygen2` header for the `em_est` function. Please do the same for `bdsmatrix` and `numDeriv`.
- [ ] Please address the following NOTE:

```
enrich_res: no visible global function definition for ‘pnorm’
enrich_res: no visible global function definition for ‘qnorm’
pi1_fun: no visible global function definition for ‘pnorm’
Undefined global functions or variables:
  pnorm qnorm
Consider adding
  importFrom("stats", "pnorm", "qnorm")
to your NAMESPACE file.
```

## Documentation

**Vignette:**

- [ ] It is recommended to use `BiocStyle::html_document` as output document type.
- [ ] As someone who is not very familiar with the terms `colocalization probabilites` and `colocalization analysis` I would appreciate a bit more explanations in an `Introduction` section of the vignette. Could you please expand on the type of data that `INTACT` can analyse and the type of analysis that `INTACT` can perform. 
- [ ] Could you please include a note on the motivation of `INTACT` to be included in Bioconductor? This can be done by referring to other Bioconductor packages that perform similar types of analyses.
- [ ] The following warning can be avoided by using single `` ` `` instead of `` ``` `` to highlight variables in the vignette:


```
WARNING: Evaluate more vignette chunks.
5 code chunks / 10 total = 50% percent unevaluated
4 non-exec code chunks (e.g., '``` r')
```
        
- [ ] The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are exported by `INTACT` but their use is not demonstrated in the vignette. If you want the user to directly apply these functions it might be worth to document their use cases in the vignette. 

## Unit tests

- [ ] It is recommended to add unit tests to your package that cover all exported (and ideally also internal) function.

## R code

- [ ] Please expand the validity checks for function parameters. You would also want to replace the `print` statement in `intact` by `stop`, which would resolve the following NOTE: 

```
* NOTE: Avoid 'cat' and 'print' outside of 'show' methods
```

It is recommended to check each function parameter for its validity. For the `intact` function these would include the following parameters: `GLCP_vec`, `prior_fun`, `z_vec`, `t`, `D`, `K`, `twas_priors`, `twas_BFs`.

**Comment by jokamoto97** [comment]
Thank you for your comments. I have provided a point-by-point response detailing what I have changed and my design choices below. 

## 

> Hi @jokamoto97,
> 
> thank you for submitting the `INTACT` package for inclusion in Bioconductor. The package is in a good state and I have a few comments below which need to be addressed before we can accept it. Please provide a point-by-point response detailing what has been changed or explaining your design choices.
> 
> ## General package development
> * [ ]  Regarding your comment on using a Bioconductor core class I would recommend to check out the [SummarizedExperiment](https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html) class. To adapt `INTACT` to use a `SummarizedExperiment` object you would simply need to store all relevent entries in `rowData(se)` where `se` is a `SummarizedExperiment` object. `rowData(se)` would replace the information stored in `INTACT::simdat`. The question here is if you always have the expression data available as output of the TWAS? These could be stored in `assay(se, "counts")`. Otherwise you can also use a `SummarizedExperiment` object with no `assays` specified. But since the data input for `INTACT` is a simple `data.frame` you could continue using the current implementation of the package.
##

Thank you for this recommendation. To answer your question, expression data will not always be available as output for TWAS. We anticipate that the only TWAS output users will have access to will be gene-level z-scores. I will continue using the current implementation of the package, as you suggested.

##
> ## The DESCRIPTION file
> * [ ]  It is recommended to set the 'LazyData:' field in the 'DESCRIPTION' file to `false` or remove it.
> * [ ]  It won't be necessary to fix the package versions in `Imports` as the newest version will be installed as package dependencies.
> * [ ]  I would recommend to add `https://github.com/jokamoto97/INTACT/issues` to the `BugReports` field.
> * [ ]  I would recommend to add `https://github.com/jokamoto97/INTACT` to the  `URL` field.
##

I have set the 'LazyData:' field to `false`. I have removed the package versions and added `stats` in `Imports`. I have added `https://github.com/jokamoto97/INTACT/issues` to the `BugReports` field. I have added `https://github.com/jokamoto97/INTACT` to the  `URL` field.

##
> ## The NAMESPACE file
> * [ ]  It is recommended to selectively import functions via `importFrom(SQUAREM,squarem)` rather than calling `SQUAREM::squarem` in your code. Since you are using `roxygen2` for documentation you can add `@importFrom SQUAREM squarem` to the `roxygen2` header for the `em_est` function. Please do the same for `bdsmatrix` and `numDeriv`.
> * [ ]  Please address the following NOTE:
> 
> ```
> enrich_res: no visible global function definition for ‘pnorm’
> enrich_res: no visible global function definition for ‘qnorm’
> pi1_fun: no visible global function definition for ‘pnorm’
> Undefined global functions or variables:
>   pnorm qnorm
> Consider adding
>   importFrom("stats", "pnorm", "qnorm")
> to your NAMESPACE file.
> ```
> 
##

I have added:

`@importFrom SQUAREM squarem` to the `em_est` `roxygen2` header;
`@importFrom numDeriv hessian`, `@importFrom bdsmatrix gchol`, and `@importFrom stats pnorm qnorm` to the `enrich_results` `roxygen2` header; and 
`@importFrom stats pnorm qnorm` to the `pi1_fun` `roxygen2` header.


##
> ## Documentation
> **Vignette:**
> 
> * [ ]  It is recommended to use `BiocStyle::html_document` as output document type.
> * [ ]  As someone who is not very familiar with the terms `colocalization probabilites` and `colocalization analysis` I would appreciate a bit more explanations in an `Introduction` section of the vignette. Could you please expand on the type of data that `INTACT` can analyse and the type of analysis that `INTACT` can perform.
> * [ ]  Could you please include a note on the motivation of `INTACT` to be included in Bioconductor? This can be done by referring to other Bioconductor packages that perform similar types of analyses.
> * [ ]  The following warning can be avoided by using single `` ` `` instead of `` ``` `` to highlight variables in the vignette:
> 
> ```
> WARNING: Evaluate more vignette chunks.
> 5 code chunks / 10 total = 50% percent unevaluated
> 4 non-exec code chunks (e.g., '``` r')
> ```
> 
> * [ ]  The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are exported by `INTACT` but their use is not demonstrated in the vignette. If you want the user to directly apply these functions it might be worth to document their use cases in the vignette.
> 
##
Thank you for this feedback on improving the vignette. I have updated the output document type to `BiocStyle::html_document`. There is now an 'Introduction' section that details the terms `colocalization probabilities` and `colocalization analysis`, expanding on the type of data that `INTACT` can analyze and the type of analysis that `INTACT` can perform. 

I included a note in the 'Introduction' section on the motivation of `INTACT` to be included in Bioconductor by referring to other Bioconductor packages that perform similar types of analyses: 

"This package is intended for performing integrative genetic association analyses in tandem with other Bioconductor packages such as `biomaRt` or `GO.db`, which could be used to obtain gene set annotations for gene set enrichment analysis."

I updated instances of `` ``` `` to single `` ` `` for variable names.

The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are helper functions for other functions intended for the user, `intact` and `intactGSE`. We do not anticipate that the user will need to directly apply these functions in their analysis.

##
> ## Unit tests
> * [ ]  It is recommended to add unit tests to your package that cover all exported (and ideally also internal) function.
> 
##

I have added unit tests for the functions `step`, `linear`, `expit`, and `hybrid` in the file `inst/unitTests/test_Priors.R`. All other functions have more complicated input and output, and I am unsure of how to write unit tests for these.

##
> ## R code
> * [ ]  Please expand the validity checks for function parameters. You would also want to replace the `print` statement in `intact` by `stop`, which would resolve the following NOTE:
> 
> ```
> * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
> ```
> 
> It is recommended to check each function parameter for its validity. For the `intact` function these would include the following parameters: `GLCP_vec`, `prior_fun`, `z_vec`, `t`, `D`, `K`, `twas_priors`, `twas_BFs`.
##
I have updated the `print` statement in `intact` to `stop` and expanded on the validity checks for all function parameters for those functions intended for the user (`intact` and `intactGSE`).
For `intact`, I have implemented checks for validity for `GLCP_vec`, `prior_fun`, `z_vec`, `t`, `D`, `K`, `twas_priors`, `twas_BFs`. 
For `intactGSE`, I have implemented checks for validity for `gene_data`,`prior_fun` , `t` ,`D` ,`gene_sets`,`sig_lev`,`SE_type`, and `boot_rep`.

**Comment by nilseling** [comment]
Hi @jokamoto97,

in you vignette you would need to call `data(simdat)` first and replace all occurrences of `INTACT::simdat` by `simdat`.

**Comment by jokamoto97** [comment]
Hi @nilseling,

Thank you for this feedback. I have edited the vignette so that I first call `data(simdat)` and replace all occurrences of `INTACT::simdat` by `simdat`. I have done the same for `gene_set_list`.

**Comment by nilseling** [comment]
Hi @jokamoto97 

please have a look at the [build report](https://bioconductor.org/spb_reports/INTACT_buildreport_20230126095234.html). The `data(simdat)` call is missing in some of the examples.

**Comment by jokamoto97** [comment]
Hi @nilseling, 

I have added `data(simdat)` and `data(gene_set_list)` to each relevant example. I am still getting the following warning in the build report: `'::' or ':::' import not declared from: BiocGenerics`. I tried adding `BiocGenerics` to the `Imports` section of the `Description` file, but it still results in a warning: `Import BiocGenerics in NAMESPACE as well as DESCRIPTION.`. I am using the `BiocGenerics` function '`testPackage`' in the script `tests/runTests.R`. 

Do you know how I might be able to resolve this warning?

**Comment by nilseling** [comment]
So it seems you want to use `RUnit` for unit testing, right? In that case have a look at their [vignette](https://cran.r-project.org/web/packages/RUnit/vignettes/RUnit.pdf). I'm personally not so familiar with `RUnit` but it seems like you would need to call 

```
library(RUnit)
runTestSuite()
``` 

In your test script. Make sure that you add `RUnit` to `Suggests`. The alternative would be to use [testthat](https://r-pkgs.org/testing-basics.html).

**Comment by jokamoto97** [comment]
@nilseling Thank you for pointing me to `testthat`. I implemented the unit tests using this rather than `RUnit` and the warning was resolved.

**Comment by nilseling** [comment]
Hi @jokamoto97 

thanks for addressing my comments! The vignette reads really nicely now!
Please have a look at my last comments below and let me know what you think.

> > ## Documentation
> > **Vignette:**
> > 
> > * [ ]   The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are exported by `INTACT` but their use is not demonstrated in the vignette. If you want the user to directly apply these functions it might be worth to document their use cases in the vignette.
>
> The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are helper functions for other functions intended for the user, `intact` and `intactGSE`. We do not anticipate that the user will need to directly apply these functions in their analysis.
> 

If you don't want to provide these functions to the user you won't need to export them. You can simply remove the `@export` label from the documentation and it is recommended to use the `.` prefix to indicate that these are hidden/helper function. E.g. `pi1_fun` would be named `.pi1_fun`. 

> > ## Unit tests
> > 
> > * [ ]   It is recommended to add unit tests to your package that cover all exported (and ideally also internal) function.
> 
> I have added unit tests for the functions `step`, `linear`, `expit`, and `hybrid` in the file `inst/unitTests/test_Priors.R`. All other functions have more complicated input and output, and I am unsure of how to write unit tests for these.

Currently the unit tests you provide only cover 4% of the package:

```
INTACT Coverage: 4.55%
R/bootstrap_se.R: 0.00%
R/em_est.R: 0.00%
R/enrich_results.R: 0.00%
R/fixptfn.R: 0.00%
R/fixptfn2.R: 0.00%
R/intact.R: 0.00%
R/intactGSE.R: 0.00%
R/loglik.R: 0.00%
R/pi1.R: 0.00%
R/expit_prior.R: 100.00%
R/hybrid_prior.R: 100.00%
R/linear_prior.R: 100.00%
R/step_prior.R: 100.00%
```

you can think of setting up unit tests that test the output of the functions by using the example `simdat` data you provide. This would be one example (or similar):

```
test_that("intact works", {
    data(simdat)
    cur_out <- intact(GLCP_vec=simdat$GLCP, z_vec = simdat$TWAS_z)
    
    expect_equal(sum(cur_out == 1),18)
})
```

**Comment by jokamoto97** [comment]
Hi @nilseling,

Thanks for the comments! Please see my responses below.

> Hi @jokamoto97
> 
> thanks for addressing my comments! The vignette reads really nicely now! Please have a look at my last comments below and let me know what you think.
> 
> > > ## Documentation
> > > **Vignette:**
> > > 
> > > * [ ]    The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are exported by `INTACT` but their use is not demonstrated in the vignette. If you want the user to directly apply these functions it might be worth to document their use cases in the vignette.
> > 
> > 
> > The functions `em_est`, `enrich_bootstrap_se`, `enrich_res`, `logistic_em`, `logistic_em_nopseudo`, `logistic_loglik` and `pi1_fun` are helper functions for other functions intended for the user, `intact` and `intactGSE`. We do not anticipate that the user will need to directly apply these functions in their analysis.
> 
> If you don't want to provide these functions to the user you won't need to export them. You can simply remove the `@export` label from the documentation and it is recommended to use the `.` prefix to indicate that these are hidden/helper function. E.g. `pi1_fun` would be named `.pi1_fun`.
##

I removed the `@export` label from the documentation and used the `.` prefix to indicate hidden/helper functions, as suggested. However, I when I call `devtools::check()`, the package cannot seem to find the helper functions, resulting in an error. Do you know how I might be able to fix this?

##
> 
> > > ## Unit tests
> > > 
> > > * [ ]    It is recommended to add unit tests to your package that cover all exported (and ideally also internal) function.
> > 
> > 
> > I have added unit tests for the functions `step`, `linear`, `expit`, and `hybrid` in the file `inst/unitTests/test_Priors.R`. All other functions have more complicated input and output, and I am unsure of how to write unit tests for these.
> 
> Currently the unit tests you provide only cover 4% of the package:
> 
> ```
> INTACT Coverage: 4.55%
> R/bootstrap_se.R: 0.00%
> R/em_est.R: 0.00%
> R/enrich_results.R: 0.00%
> R/fixptfn.R: 0.00%
> R/fixptfn2.R: 0.00%
> R/intact.R: 0.00%
> R/intactGSE.R: 0.00%
> R/loglik.R: 0.00%
> R/pi1.R: 0.00%
> R/expit_prior.R: 100.00%
> R/hybrid_prior.R: 100.00%
> R/linear_prior.R: 100.00%
> R/step_prior.R: 100.00%
> ```
> 
> you can think of setting up unit tests that test the output of the functions by using the example `simdat` data you provide. This would be one example (or similar):
> 
> ```
> test_that("intact works", {
>     data(simdat)
>     cur_out <- intact(GLCP_vec=simdat$GLCP, z_vec = simdat$TWAS_z)
>     
>     expect_equal(sum(cur_out == 1),18)
> })
> ```
##

I added unit tests for the other functions included in the package using the example data `simdat`. The total coverage should be 100% now.

**Comment by nilseling** [comment]
Could you please also push the changes to your Github so that I can have a look?

**Comment by jokamoto97** [comment]
Yes! I just pushed them to my Github. Sorry about that.

**Comment by nilseling** [comment]
Ok, I see where the error is coming from. The hidden functions are not exported by `INTACT` anymore. This means the following calls would not work:

```
library(INTACT)
data(simdat)

.em_est(d_vec = sample(c(0,1),1197,replace=TRUE)
```

The hidden functions are however internally available for other package functions. In your case it means you would just need to remove all examples for the hidden functions. The unit tests now cover 60% of the package and that's sufficient for now.

```
INTACT Coverage: 57.88%
R/intactGSE.R: 34.40%
R/em_est.R: 50.00%
R/intact.R: 58.06%
R/enrich_results.R: 63.46%
R/bootstrap_se.R: 100.00%
R/expit_prior.R: 100.00%
R/fixptfn.R: 100.00%
R/fixptfn2.R: 100.00%
R/hybrid_prior.R: 100.00%
R/linear_prior.R: 100.00%
R/loglik.R: 100.00%
R/pi1.R: 100.00%
R/step_prior.R: 100.00%
```

**Comment by jokamoto97** [comment]
Thank you! I have deleted the examples for hidden functions and the error went away.

**Comment by nilseling** [comment]
This is great! I have no further comments and will accept the package now. Good work.

**Comment by jokamoto97** [comment]
Great, thank you so much for your help and comments!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jokamoto97.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("INTACT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/INTACT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
