### ISSUE TITLE
HiCExperiment

### ISSUE THREAD

**Issue by js2264** [Bioconductor/Contributions#2879]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/js2264/HiCExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by js2264** [comment]
Hi @vjcitn , 

Just to let you know, this package is mostly a reformating of `HiContacts` package, published in Bioconductor since 3.16. `HiContacts` was originally reviewed by Marcel @LiNk-NY ([issue here](https://github.com/Bioconductor/Contributions/issues/2757)). Upon their suggestion, I splitted the package in two and created `HiCExperiment` package to define parsing methods and classes. I am happy for any Bioconductor member to review this package, of course. 

FYI, there is also an upcoming `HiCool` package, which will be submitted if & when `HiCExperiment` is accepted. All of this is summarized in 2 figures in the `HiCExperiment` README (https://github.com/js2264/HiCExperiment). 

Let me know if I can provide any further information regarding this package. 
Best, J

**Comment by vjcitn** [comment]
You don't have to delay submitting the HiCool package if it requires HiCExperiment ... there is a protocol for managing/reviewing related packages together.

**Comment by js2264** [comment]
Fair enough, I'll provide HiCool as an `AdditionalPackage` when a reviewer is assigned then. Thanks for your suggestion.

**Comment by js2264** [comment]
Hi @DarioS, 
Thank you for agreeing to review my package. 
I have fixed all the errors/warnings. There is a single warning remaining, due to tests exceeding Bioc 10min limit. I'll work on reducing this length, but I think package is ready for review now. 
Let me know if you need any information, 
Best, J

**Comment by js2264** [comment]
@DarioS , 

The only remaining warning is for merida1 (macOS machine), which consistently takes between 10 and 11 minutes to perform `R CMD CHECK`. Of note, nebbiolo1 (Linux) SPB runner takes under 10min, and the three OSes run <10min using GHA (including MacOS runner: [https://github.com/js2264/HiCExperiment/actions/runs/3839418414/jobs/6537156295#step:2:5932](https://github.com/js2264/HiCExperiment/actions/runs/3839418414/jobs/6537156295#step:2:5932) ). I guess the SPB AWS instance is somewhat weaker/struggling more than Github runners. 

I would be happy to either (1) further reduce tests or (2) switch to long tests, in your opinion, is any of these options necessary? If so, let me know which one you prefer and I'll make required changes. 
Best, J

**Comment by js2264** [comment]
AdditionalPackage: https://github.com/js2264/HiCool

**Comment by js2264** [comment]
AdditionalPackage: https://github.com/js2264/fourDNData

**Comment by js2264** [comment]
Hi @DarioS, 
It's been two weeks since the review has started; just wanted to know where were you in the reviewing process, and if I could provide any help! Thanks, J

**Comment by DarioS** [comment]
In Australia, we just returned to work this week from summer holidays, so the formal review of HiCExperiment will begin in the next couple of days. I enquired about the time-out on merida1 with the Bioconductor core team on Monday and one of them replied today to just igore that issue. It's interesting how it takes much longer than the GitHub Actions computer does.

**Comment by DarioS** [comment]
HiCExperiment and its companion packages represent an impressive framework for storing and analysing chromatin interaction data. It has good interoperability with existing S4 classes such as `InteractionSet` and `ContactMatrix`. Each S4 class has a show method defined to print it nicely to the R console. Only a few minor issues are identified.

- For consistency in style with other packages in Bioconductor ecosystem, please use camelCase variable naming. Please refer to [Variable Names section](https://contributions.bioconductor.org/r-code.html#variable-names) of R Code chapter of the contributors guide. Related to this, please use variable names which are meaningful to people who might join the project in the future (e.g. You begin supervising a research student who also helps to maintain the package code). Variable names such as `an1`, `re`, `xx` and `gi` are not immediately undestandable for others. Please see [self-documenting code](https://hackbrightacademy.com/blog/writing-self-documenting-code/#:~:text=What%20is%20self%2Ddocumenting%20code,not%20heard%20the%20term%20before.) for advice. Again, see the contributor's guide and instructions about camelCase variables (I understand that this is the exact opposite to tidyverse convention which you might be accustomed to).
- Some of the function parameters lack meaningful descriptions in the documentation. For example,
  > `file`: file
  > `resolution`: resolution
  > `bed:` bed

  Please provide meaningful, full-sentence descriptions of parameters. For example, `file` could be described as "A character vector of length 1 specifying the file path to the HiC-Pro matrix file." It is ambiguous from the one-word description above if you want the user to provide an open _file connection_ using `base::file()` or simply to specify _the path to a file_.
- Some examples are very long and lack interpretability. Please break these down into sections of a few lines each separated by a newline and add a comment above or below each section to explain to the end-user what each section of commands does. For example, HiCExperiment.Rd's Examples section has:

    ```r
    mcool_path <- HiContactsData::HiContactsData('yeast_wt', 'mcool')
    contacts_yeast <- HiCExperiment(mcool_path, resolution = 16000, focus = 'II')
    contacts_yeast
    resolutions(contacts_yeast)
    resolution(contacts_yeast)
    focus(contacts_yeast)
    scores(contacts_yeast)
    tail(scores(contacts_yeast, 1))
    tail(scores(contacts_yeast, 'balanced'))
    scores(contacts_yeast, 'test') <- runif(length(contacts_yeast))
    tail(scores(contacts_yeast, 'test'))
    data(centros_yeast)
    topologicalFeatures(contacts_yeast, 'centromeres') <- centros_yeast
    topologicalFeatures(contacts_yeast, 1)
    topologicalFeatures(contacts_yeast, 'centromeres')
    pairsFile(contacts_yeast)
    fileName(contacts_yeast)
    interactions(contacts_yeast)
    length(contacts_yeast)
    contacts_yeast[seq_len(10)]
    seqinfo(contacts_yeast)
    bins(contacts_yeast)
    anchors(contacts_yeast)
    regions(contacts_yeast)
    contacts_yeast
    as(contacts_yeast, 'GInteractions')
    as(contacts_yeast, 'ContactMatrix')
    as(contacts_yeast, 'matrix')[seq_len(10), seq_len(10)]
    as(contacts_yeast, 'data.frame')[seq_len(10), seq_len(10)]
    ```
    
    It might be best to pick a few important commands, rather than showing every possible one in this example which is an overwhelming amount of output to see all at once. Based on my exeperience in designing workshops, beginners tend to copy and paste everything. Break it down into chunks for them.
- Vignette needs an introduction and more details for novices. Installation instructions are also missing. Please see [Vignette Introduction](https://contributions.bioconductor.org/docs.html#vignette-introduction) and [Installation](https://contributions.bioconductor.org/docs.html#installation) sections of the contributor's guide.

  > ... introduce the objective, models, unique functions, key points, etc that distinguish the package from other packages in the same area.
  
  For example, the vignette mentions that the package supports three different file types; Cool files, HiC files, and HiC-Pro files. What are the advantages and disadvantages of each file type? Do they all store the same data or do any of them store more details than the others? This would be valuable information for beginners.
  
  Also, the introduction mentions "... **analytical** and **visualization** tools to investigate contact maps ..." but analytical and visualization words are never mentioned in the vignette again. Does HiCExperiment provide that functionality or does one of the accessory packages, such as HiContacts, provide that? Perhaps this sentence should be changed to provide cross-links to your other packages to guide the end-user to the functionality which is perhaps no longer found in HiCExperiment.
  
- Some cross-links could be added to Rd files. For example, "The `ContactsFile` class describes a `BiocFile` object" could use `[BiocIO::BiocFile]` Roxygen macro to link to the HTML documentation of BiocFile for browsing in RStudio I.D.E.

**Comment by js2264** [comment]
Hi @DarioS, 
Thank you for your review. Listed below are the commits I have made to answer your comments. 

* [48e35c2](https://github.com/js2264/HiCExperiment/commit/48e35c2) - avoid snake_case or snake.case
* [ca9dfad](https://github.com/js2264/HiCExperiment/commit/ca9dfad) - add cross-refs
* [b8886ec](https://github.com/js2264/HiCExperiment/commit/b8886ec) - imrpove doc
* [6c0af8a](https://github.com/js2264/HiCExperiment/commit/6c0af8a) - extends vignette
* [ab951c2](https://github.com/js2264/HiCExperiment/commit/ab951c2) - break down HiCExperiment.R examples in chunks
* [0127830](https://github.com/js2264/HiCExperiment/commit/0127830) - improve documentation of function parameters

> * For consistency in style with other packages in Bioconductor ecosystem, please use camelCase variable naming. Please refer to [Variable Names section](https://contributions.bioconductor.org/r-code.html#variable-names) of R Code chapter of the contributors guide. 

I have amended the code to limit the use of snake_/.case. All functions use camelCase, except check_* and is_*, which follow a more standard R naming convention. 

Related to this, please use variable names which are meaningful to people who might join the project in the future (e.g. You begin supervising a research student who also helps to maintain the package code). Variable names such as `an1`, `re`, `xx` and `gi` are not immediately undestandable for others. Please see [self-documenting code](https://hackbrightacademy.com/blog/writing-self-documenting-code/#:~:text=What%20is%20self%2Ddocumenting%20code,not%20heard%20the%20term%20before.) for advice. 

I have limited the use of non-self-explanatory functions as much as possible. `gi` (GInteractions), `an` (anchors), `re` (regions) are "shortcuts" that mimic the way objects from other classes (e.g. `se` for SummarizedExperiments, `gr` for GRanges, ...) are referred to in other packages' documentation. Let me know if you still would like this to be changed. 

> * Some of the function parameters lack meaningful descriptions in the documentation. For example,
>   > `file`: file
>   > `resolution`: resolution
>   > `bed:` bed
>   
>   
>   Please provide meaningful, full-sentence descriptions of parameters. For example, `file` could be described as "A character vector of length 1 specifying the file path to the HiC-Pro matrix file." It is ambiguous from the one-word description above if you want the user to provide an open _file connection_ using `base::file()` or simply to specify _the path to a file_.

Done. Again, let me know if you think more details are necessary. 

> * Some examples are very long and lack interpretability. Please break these down into sections of a few lines each separated by a newline and add a comment above or below each section to explain to the end-user what each section of commands does. For example, HiCExperiment.Rd's Examples section has:
>   ```r
>   mcool_path <- HiContactsData::HiContactsData('yeast_wt', 'mcool')
>   contacts_yeast <- HiCExperiment(mcool_path, resolution = 16000, focus = 'II')
>   contacts_yeast
>   resolutions(contacts_yeast)
>   resolution(contacts_yeast)
>   focus(contacts_yeast)
>   scores(contacts_yeast)
>   tail(scores(contacts_yeast, 1))
>   tail(scores(contacts_yeast, 'balanced'))
>   scores(contacts_yeast, 'test') <- runif(length(contacts_yeast))
>   tail(scores(contacts_yeast, 'test'))
>   data(centros_yeast)
>   topologicalFeatures(contacts_yeast, 'centromeres') <- centros_yeast
>   topologicalFeatures(contacts_yeast, 1)
>   topologicalFeatures(contacts_yeast, 'centromeres')
>   pairsFile(contacts_yeast)
>   fileName(contacts_yeast)
>   interactions(contacts_yeast)
>   length(contacts_yeast)
>   contacts_yeast[seq_len(10)]
>   seqinfo(contacts_yeast)
>   bins(contacts_yeast)
>   anchors(contacts_yeast)
>   regions(contacts_yeast)
>   contacts_yeast
>   as(contacts_yeast, 'GInteractions')
>   as(contacts_yeast, 'ContactMatrix')
>   as(contacts_yeast, 'matrix')[seq_len(10), seq_len(10)]
>   as(contacts_yeast, 'data.frame')[seq_len(10), seq_len(10)]
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   It might be best to pick a few important commands, rather than showing every possible one in this example which is an overwhelming amount of output to see all at once. Based on my exeperience in designing workshops, beginners tend to copy and paste everything. Break it down into chunks for them.

Thank you for the great suggestion. I have now separated this set of commands in organized subexamples, and it makes a lot more sense. 

> * Vignette needs an introduction and more details for novices. Installation instructions are also missing. Please see [Vignette Introduction](https://contributions.bioconductor.org/docs.html#vignette-introduction) and [Installation](https://contributions.bioconductor.org/docs.html#installation) sections of the contributor's guide.
>   > ... introduce the objective, models, unique functions, key points, etc that distinguish the package from other packages in the same area.
>   
>   
>   For example, the vignette mentions that the package supports three different file types; Cool files, HiC files, and HiC-Pro files. What are the advantages and disadvantages of each file type? Do they all store the same data or do any of them store more details than the others? This would be valuable information for beginners.
>   Also, the introduction mentions "... **analytical** and **visualization** tools to investigate contact maps ..." but analytical and visualization words are never mentioned in the vignette again. Does HiCExperiment provide that functionality or does one of the accessory packages, such as HiContacts, provide that? Perhaps this sentence should be changed to provide cross-links to your other packages to guide the end-user to the functionality which is perhaps no longer found in HiCExperiment.

I have added a Introduction and Installation section in the vignette, and removed the paragraph you mentioned. You were correct thinking that this bit (analytical and visualisation) has been migrated to HiContacts.

> * Some cross-links could be added to Rd files. For example, "The `ContactsFile` class describes a `BiocFile` object" could use `[BiocIO::BiocFile]` Roxygen macro to link to the HTML documentation of BiocFile for browsing in RStudio I.D.E.

Thanks for this suggestion. I have added some cross-references to HiCExperiment.R and *File.R doc sections, although I am not really familiar with them. Hopefully they are ok. Let me know if you wish me to add more of them.

**Comment by DarioS** [comment]
All issues have been satisfactorily dealt with.

**Comment by js2264** [comment]
Hi @DarioS,
Thank you for your feedback and your review. Glad to hear that HiCExperiment is accepted. Does this also include the additional packages I submitted in this issue (HiCool and fourDNData)? Thanks in advance, J

**Comment by lshep** [comment]
I'll let @DarioS  comment on if the other two packages were reviewed but from the admin stand point, they  have not yet been added to git or had a bioconductor builder report so I added the necessary tags back for processing.

**Comment by js2264** [comment]
Hi @lshep, thank your for your reply. Regarding the absence of builder report, I think this is because the 2 additional packages have not been assigned a reviewer yet, so builds were not triggered. Would there be anything to do (assigning a reviewer? Manually triggering builds?) regarding this? Thanks for your input, J

**Comment by lshep** [comment]
I will be processing packages later today and tomorrow;  we will have a quick glance and then mark them for moderation.

**Comment by vjcitn** [comment]
In checking HiCool i hit
```
Loading required package: HiCExperiment
Error: package or namespace load failed for 'HiCool':
 object 'GenomicRanges' is not exported by 'namespace:GenomicRanges'
Execution halted
```
and indeed I see this in the NAMESPACE.  Why?

**Comment by js2264** [comment]
@vjcitn This is because I've messed up, it should be `#' @importFrom GenomicRanges GRanges` in R/loops.R. I fixed it in [ceb5891](https://github.com/js2264/HiCool/commit/ceb5891e424c1998f19c6b8ccb5a920d25fd15b8).

**Comment by DarioS** [comment]
Ah, I did not review two associated packages. I thought the lack of build reports indicated they might each get their own issues.

**Comment by lshep** [comment]
We hold additionalpackages to have a glance to make sure like with incoming packages they look like packages, are in decent enough shape to have a review, and aren't doing anything malicious.

**Comment by lshep** [comment]
Running the two additional packages now for build reports.

**Comment by js2264** [comment]
@lshep, 

Thanks for letting my 2 extra packages run on the builder. I have now fixed things and:
- fourDNData builds without any error/warnings
- HiCool runs with a single warning, corresponding to check time > 10min (~ 14min). This is because the example takes time to run: it triggers the installation of a basilisk environment with several python packages and conda being super-slow, solving the environment takes ~10min. Any idea on how to improve this? I don't know how to make this run faster. 

Also, should @DarioS review these packages, or someone else take over? 
Cheers, J

**Comment by DarioS** [comment]
I will continue the review process. One of the Bioconductor employees might know how to solve the Python-related timeout.

**Comment by vjcitn** [comment]
With every version bump, all python infrastructure is re-downloaded and installed.  I think there is no desirable workaround at the basilisk/client end.  However if @lshep would manually trigger a rebuild, the installed python infrastructure should be available -- it goes to .cache/R, as long as that is not purged with every build it should be reusable.

**Comment by lshep** [comment]
I'll try a manual trigger now to see how it changes --

**Comment by js2264** [comment]
@DarioS gentle ping: is there anything you would need for the review of HiCool and fourDNData? Cheers, J

**Comment by DarioS** [comment]
Just more free time. I have got seven packages to review and university administrative work, too. I should do it next week.

**Comment by js2264** [comment]
AdditionalPackage: https://github.com/js2264/DNAZooData

**Comment by js2264** [comment]
Hi @DarioS @lshep 👋, 

Just to let you know I have added (yet) another AdditionalPackage (`DNAZooData`). It is also a ExperimentData package, providing programmatic access to HiC and genome references generated by the DNA Zoo consortium. It operates the same way than the `fourDNData` package, by fetching metadata from the consortium database, caching the HiC contact matrix file and creating a `HicFile` (`BiocFile` variant) to be imported in R with `HiCExperiment::import()`. Sorry for the extra burden, and please let me know if I should rather submit it as a separate issue. 
Cheers, J

**Comment by DarioS** [comment]
Additional Packages Review

**HiCool**

The parameter descriptions are good and not single words like previously in HiCExperiment. Checks don't have any warnings or errors. Parameters could use more explanation. For example

```r
#' @param balancing_args Balancing arguments for cooler (Default: " --cis-only --min-nnz 3 --mad-max 7 ")
```

What are all of the valid parameter names? Are there more than just `--cis-only`, `--min-nnz`, `--mad-max` acceptable? A link to some list of valid options somehere would be desirable.

The package now has a vignette but it only has one code chunk and it is a template rather than executable code. Although this package does some intensive processing, I think it could be demonstrated on real data, perhaps subset to chr22, a small chromosome.

One of the outputs produced is "several diagnostic plots". What quality control does each one show and how should the package user interpret the graphs?

**fourDNDdata**

R CMD check ERROR on all operating systems. Vignette is well-written and shows how to programatically download a data set from the consortium.

**DNAZooData**

Not yet accepted for review, but it looks similar in spirit to fourDNDdata. The parameters are not similar, however, but I wonder if downloading from both consortiums could be merged into a single package. Currently, both packages consist of just three R files, so even after merging, the package would not be big.

**Comment by js2264** [comment]
Thanks for this extra round of reviews @DarioS. 

I have made some internal changes and contribution changes in `HiCExperiment` package and forgot to push it to Bioc, so perhaps the fourDNData-related CHECK errors you are seeing are due to a mismatch in versions. I have now bumped `HiCExperiment` to 0.99.10 and pushed it to Bioc and build/check was ok (except for the [previously reported](https://github.com/Bioconductor/Contributions/issues/2879#issuecomment-1385907904) check > 10min **only in mac builder**). I have also bumped fourDNData to 0.99.3, pushed it to Bioc and build/check is ok. I have also bumped HiCool to 0.99.4 and pushed it to Bioc and build/check was ok (except for time limit due to building the basilisk env. **only in mac builder** as previously reported). 

**Regarding documentation changes:**

* [x] #' param balancing_args Balancing arguments for cooler (Default: " --cis-only --min-nnz 3 --mad-max 7 ")
What are all of the valid parameter names? Are there more than just --cis-only, --min-nnz, --mad-max acceptable? A link to some list of valid options somehere would be desirable. 

I have now clarified this in `HiCool` doc and in the vignette. 

* [x] The package now has a vignette but it only has one code chunk and it is a template rather than executable code. Although this package does some intensive processing, I think it could be demonstrated on real data, perhaps subset to chr22, a small chromosome.

I have added an executable chunk in the vignette, to demonstrate real use (on a subset of yeast fastq files)

* [x] One of the outputs produced is "several diagnostic plots". What quality control does each one show and how should the package user interpret the graphs?

I have added a paragraph re: this in the vignette. 

**Regarding fourDNData:**

* [ ] R CMD check ERROR on all operating systems for fourDNData. 

Could you please provide the check results? Bioc SPB builds/checks fourDNData without errors, perhaps yours are due to a mismatch in versions. I've bumped all packages up, would be worth updating all of them. 

**Regarding DNAZoo:**

* [x] The parameters for DNAZoo are not similar to fourDNData

This is because the two consortia have very different strategies to label data, different associated metadata and different types of files. E.g. 4DN consortium can provide contact matrices (`.cool` files), but also automatically processed `.bigwig` files, or `.bed` files, ... matching a single dataset. One may wish to recover all of these files together or only a subset of them, hence the added `type` argument in `fourDNData`. On the other hand, DNA Zoo only provides a contact map per species. 

* [x] I wonder if downloading from both consortiums could be merged into a single package. Currently, both packages consist of just three R files, so even after merging, the package would not be big.

It is feasible, but I don't think it would be a valuable improvement. The 2 consortia do provide contact matrices, but processing workflows are vastly different. 4DN processes data from published experiments (from a 20+ different labs) on known genome references (90% human or mouse). DNA Zoo is a project led by a single lab (working in collaboration with others of course), and aims to correct/improve genome assemblies of non-model organisms. So the contact map is the result of a large amount of upstream work to re-assemble an original genome reference into an improved reference. IMO, providing a gateway to the two types of contact matrices in the same package would feel unnatural. Let me know what you think based on this answer.

**Comment by js2264** [comment]
Hi @DarioS @lshep 👋,

> Just to let you know I have added (yet) another AdditionalPackage (`DNAZooData`). It is also a ExperimentData package, providing programmatic access to HiC and genome references generated by the DNA Zoo consortium. It operates the same way than the `fourDNData` package, by fetching metadata from the consortium database, caching the HiC contact matrix file and creating a `HicFile` (`BiocFile` variant) to be imported in R with `HiCExperiment::import()`. Sorry for the extra burden, and please let me know if I should rather submit it as a separate issue.

Gentle nudge following my replies to @DarioS review, to ask whether the AdditionalPackage `DNAZooData` could be added to the the build report? As @DarioS said, it follows the exact same structure than `fourDNData` which has already be added to the builds.
Thanks! J

**Comment by js2264** [comment]
Hi @lshep, sorry for being pushy, but would it be possible to add `DNAZooData` to the build system? Many thanks for your help, 
J

**Comment by js2264** [comment]
Hi @DarioS 👋
Sorry for coming back to it, I know this has been a heavy reviewing assignment, but would it be possible to wrap this up soonish? Let me know if I can provide any help. 
May thanks! J

**Comment by DarioS** [comment]
I have no further requests and the packages seem to be building well together. Thanks for your comprehensive infrastructure.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HiCExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HiCExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HiCool")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HiCool

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("fourDNData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/fourDNData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DNAZooData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DNAZooData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
