### ISSUE TITLE
OutSplice

### ISSUE THREAD

**Issue by GuoLabUCSD** [Bioconductor/Contributions#2888]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GuoLabUCSD/OutSplice

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thank you for your contribution!  

Do not do this!:
```
> print(paste0("Output is located at: ", dir))
[1] "Output is located at: /home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/OutSplice/extdata/OutSplice_TCGA_Vignette_Output//"
```
The elements of .libPaths() are to be touched only by installation utilities.  If you are writing output to disk, arrange with the user to find a place that is agreeable.  For example, set things up under `tempdir()` and give the user the option to specify another destination.

**Comment by vjcitn** [comment]
Please use tempdir() or some other location that the user has control over for any writes to disk.  Please run R CMD check and BiocCheck on your package on a clean system so that you will know if there are problems to arise on Bioc's build system.

**Comment by GuoLabUCSD** [comment]
Hi Vince,

Thank you for the help! Once the change is made, do I need to push the changes to my repository on git.bioconductor.org, or can I just make the edits in our repository on GitHub. Also, is there another step after the push I will need to do to get it looked at again?

Best,
Joseph
________________________________

**Comment by vjcitn** [comment]
until precheck is passed you only work on your github repo.  there is nothing for your package at git.bioconductor.org yet.

**Comment by GuoLabUCSD** [comment]
Hi @vjcitn ,

I have made some changes to the package and was hoping to get it run through the pre-review again.

Thank you,
Joseph

**Comment by GuoLabUCSD** [comment]
Hi @vjcitn 

I just wanted to see if there was an update in getting my package run through Bioconductor's pre-review again. I have made the requested change and after running R CMD build on my own end, believe there should be no more issues.

**Comment by GuoLabUCSD** [comment]
Hi @lazappi 

Our maintainer should now be registered on the bioc-devel mailing list and has also added "OutSplice" to their list of watched tags. I believe these were the only two errors found in the build report. Please let me know if there is anything else we will need to do!

Thanks,
Joseph

**Comment by lazappi** [comment]
That should fix the errors in the report but can you please push a version bump to confirm that? I hope to have time to review this some time this week.

**Comment by GuoLabUCSD** [comment]
Hi @lazappi,

Thanks for the response. We have fixed the registration and Watched Tags error messages and pushed a version bump. It seems to build correctly on the macOS platform, however for some reason I am getting an error saying "there is no package called BiocGenerics" in BiocCheck on the Linux platform. Do you know why this could be?

**Comment by lazappi** [comment]
Hmmm... That's a bit weird. I don't think this is something you can resolve so let's ignore it for now and hope it is fixed for the next push.

**Comment by GuoLabUCSD** [comment]
Sounds good. Please let me know once you get some time to review the rest of the package. Thank you for all of the help!

**Comment by lazappi** [comment]
Hi @GuoLabUCSD

Thanks for submitting **OutSplice** :tada:!

I had some issues getting your package to install on my system (I think it's a problem on my end, not with your package). Rather than making you wait I have reviewed as much as I can by looking at the code. Just keep in mind there were some things I couldn't check and it's likely there will be more comments when I can look at those. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please try to address as many of the notes from **{BiocCheck}** in the build report as you can

## DESCRIPTION file

- [ ] :warning: Consider adding ORCIDs to the `Authors@R` field
- [ ] :green_circle: Check if it is a appropriate to add any of the `biocViews` suggested by **{BiocCheck}**
- [ ] :green_circle: Consider adding a `BugReports` field, this is usually a link to the GitHub issues page or the Bioconductor support site
- [ ] :green_circle: Consider adding a `URL` field, this is usually a link to the GitHub repository or the Bioconductor package page

## NAMESPACE file

- [ ] :rotating_light: Function names should be `camelCase` or `snake_case`, `UpperCamelCase` is reserved for classes
- [ ] :rotating_light: Functions should be selectively imported using `importFrom` instead of with `import`
- [ ] :green_circle: I think you have written the `NAMESPACE` file by hand, consider using the `roxygen2` package to generate it automatically (see the man page section below)

## Package data

- [ ] :warning: Some of the files in `inst/extdata` are quite large, it might be worth compressing these
- [ ] :warning: I think some of the scripts files mentioned in `create_testset.R` don't exist, it would be better if all the code was included somewhere

## Documentation

### Vignette

- [ ] :rotating_light: Please use the document formatin the the `BiocStyle` package
- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: Please update the introduction of the vigette to mention your motivation for inclusion in Bioconductor and any existing packages with similar functionality (if applicable)
- [ ] :rotating_light: The instructions for installing from source can be removed

### Man pages

- [ ] :warning: It is recommended to add a package man page
- [ ] :green_circle: I highly recommend using the **{roxygen2}** package for function documentation, this is the standard for new packages and is much easier to read and maintain

## Unit tests

- [ ] :rotating_light: Please add unit tests that cover a large part of core functionality

## Code

### R

- [ ] :rotating_light: Please use `vapply` instead of `sapply`
- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :warning: Please use named indicies instead of numeric indices
- [ ] :green_circle: I didn't notice much reuse of Bioconductor data structures, are there any that could be used?
- [ ] :warning: The `OutSplice` and `OutSplice_TCGA` functions are very similar, can you move some of the common code into shared sub-functions?
- [ ] :warning: Consider adding validity checks for function arguments
- [ ] :green_circle: I found your code very difficult to read because of the lack of consistent indenting, please consider adjusting this (the **{styler}** and **{BiocStyle}** packages can help with this)
- [ ] :green_circle: I think L25 in `OGSAfunctionwFisher.R` can be simplified to `no.of.normals<-sum(PHENO==0])`
- [ ] :green_circle: L30 in `OGSAfunctionwFisher.R` is redundant given it is overwritten on the next line
- [ ] :green_circle: Avoid returning inside `return()` (i.e. `return(x <- y)`))
- [ ] :warning: It is usually better to return function output and let the user decide how to handle than write directly to files within a function

**Comment by GuoLabUCSD** [comment]
Hi @lazappi,

Thanks for looking our package over! We are currently in the process of revising and will let you know when it is done. 

I did have a question about your comment on the use of named indicies instead of numeric indices. Is there a particular part of the code where this is an issue that you see? I am having some trouble figuring out what exactly should be changed regarding this.

**Comment by lazappi** [comment]
> I did have a question about your comment on the use of named indicies instead of numeric indices. Is there a particular part of the code where this is an issue that you see? I am having some trouble figuring out what exactly should be changed regarding this.

In general, this means using something like `df[, "columnName"]` rather than `df[, 1]`. I think I saw this in a few places but I can't remember exactly where. It's not super important in terms of getting the package accepted but it's worth looking out for because it tends to lead to errors over time (if a new column is added, or columns reordered etc.). The same applies to lists and other objects with names.

**Comment by GuoLabUCSD** [comment]
Thanks @lazappi,

I did have one other question as we are going through your comments. You mentioned using importFrom instead of import. However, I have been getting the below issue when I try to use importFrom(GenomicRanges, findOverlaps) or importFrom(IRanges, findOverlaps). However, the error disappears when I just use import(GenomicRanges). Is it acceptable to use the general import statement for the GenomicRanges package? If not, would you know how I could handle this issue? The subject and query I have been calling the function on are GRanges objects. (Lines 148 and 168 in SplicingOutliers_Function.R).

`error in evaluating the argument 'query' in selecting a method for function 'findOverlaps': each range must have an end that is greater or equal to its start minus one`

**Comment by lazappi** [comment]
> I did have one other question as we are going through your comments. You mentioned using importFrom instead of import. However, I have been getting the below issue when I try to use importFrom(GenomicRanges, findOverlaps) or importFrom(IRanges, findOverlaps). However, the error disappears when I just use import(GenomicRanges). Is it acceptable to use the general import statement for the GenomicRanges package? If not, would you know how I could handle this issue? The subject and query I have been calling the function on are GRanges objects. (Lines 148 and 168 in SplicingOutliers_Function.R).
> 
> `error in evaluating the argument 'query' in selecting a method for function 'findOverlaps': each range must have an end that is greater or equal to its start minus one`

Hmmm...I think this probably means there is something else that needs to be loaded/imported, maybe associated with the GRanges object. This might be hard to track down so it's probably ok to leave it if you can't find an easy solution, particularly if you are working with GRanges and associated functions a lot anyway.

**Comment by GuoLabUCSD** [comment]
Thanks for all the help @lazappi,

 We are almost ready for you to check the package again. However, I did have one last question before I push the updates and generate the build report. Would it be ok to have functions longer than 50 Lines, and lines longer than 80 characters, or is this going to be a requirement? We do have functions and lines over these recommended values, however I do not think it drastically impacts the readability and it would require more in depth re-working.

**Comment by lazappi** [comment]
> Thanks for all the help @lazappi,
> 
> We are almost ready for you to check the package again. However, I did have one last question before I push the updates and generate the build report. Would it be ok to have functions longer than 50 Lines, and lines longer than 80 characters, or is this going to be a requirement? We do have functions and lines over these recommended values, however I do not think it drastically impacts the readability and it would require more in depth re-working.

No, this is more a guideline than a requirement. Most of the time it is good advice but there are definitely cases where it doesn't make sense. As long as you have looked at it and made changes where it makes sense that is the main thing.

**Comment by GuoLabUCSD** [comment]
Hi @lazappi,

I have put some responses/comments to each of your points below and am ready to get the package checked over again. There was recently an issue where some BiocGenerics Functions got moved to MatrixGenerics causing some difficulties getting the package to build again (https://app.slack.com/client/T35G93A5T/CLUJWDQF4/thread/CLUJWDQF4-1680053933.709209).  It now seems to be building correctly on nebbiolo1, but not merida1, which gives the error `objects rowSums, colSums, rowMeans, colMeans are not exported by 'namespace:BiocGenerics'`.

> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [ ]  ⚠️ Please try to address as many of the notes from **{BiocCheck}** in the build report as you can

Notes from BiocCheck have been addressed and only the below remain:
Multiples of 4 spaces for line indents are used in most instances across the package code. (Generated using the styler package). The cases where this isn’t used are restricted to the man pages, which get formatted independently from roxygen2 or the BiocStyle package.
Lines of 80 characters or more and functions longer than 50 lines have been left in as is. Each function still has one main purpose and the new styling should make them easier to read. Restricting the code to 80 characters per line also seems to make it more difficult to interpret during our process.
 
> ## DESCRIPTION file
> * [ ]  ⚠️ Consider adding ORCIDs to the `Authors@R` field

ORCIDs have been added where possible to the corresponding field.

> * [ ]  🟢 Check if it is a appropriate to add any of the `biocViews` suggested by **{BiocCheck}**

The following biocViews have been added from ‘biocViews’:
	DifferentialExpression, DifferentialSplicing, VariantAnnotation
However, we do not believe the recommended tag “Network” is appropriate for this package.

> * [ ]  🟢 Consider adding a `BugReports` field, this is usually a link to the GitHub issues page or the Bioconductor support site

This field has been added to the DESCRIPTION file with a link to the GitHub issues page.

> * [ ]  🟢 Consider adding a `URL` field, this is usually a link to the GitHub repository or the Bioconductor package page

This field has been added to the DESCRIPTION file with a link to the GitHub repository.

> ## NAMESPACE file
> * [ ]  🚨 Function names should be `camelCase` or `snake_case`, `UpperCamelCase` is reserved for classes

Functions have been renamed to use the correct convention. Also, the outsplice function has been renamed to outspliceAnalysis.
> * [ ]  🚨 Functions should be selectively imported using `importFrom` instead of with `import`

All functions are now imported using this method except for import(GenomicRanges) package. It seems that the findOverlaps function only works properly when importing the whole package.

> * [ ]  🟢 I think you have written the `NAMESPACE` file by hand, consider using the `roxygen2` package to generate it automatically (see the man page section below)
 
The ‘NAMESPACE’ file is now generated using ‘roxygen2.’

> ## Package data
> * [ ]  ⚠️ Some of the files in `inst/extdata` are quite large, it might be worth compressing these

The HNSC_genes_normalized.txt, TCGA_HNSC_genes_normalized.txt, HNSC_junctions.txt, and TCGA_HNSC_junctions.txt files have now been compressed.

> * [ ]  ⚠️ I think some of the scripts files mentioned in `create_testset.R` don't exist, it would be better if all the code was included somewhere

Thank you for catching this. These were some old script files that we had used originally and forgot to remove. ‘create_testset.R’ now correctly reflects this. Additionally, the wrong rawcounts file was listed on L9 of this file and it has now been corrected.

> ## Documentation
> ### Vignette
> * [ ]  🚨 Please use the document formatin the the `BiocStyle` package

The vignette has now been updated to use this style.

> * [ ]  🚨 Please add a table of contents

The vignette now includes a table of contents.

> * [ ]  🚨 Please update the introduction of the vigette to mention your motivation for inclusion in Bioconductor and any existing packages with similar functionality (if applicable)

The introduction in the vignette has now been rewritten to include this.

> * [ ]  🚨 The instructions for installing from source can be removed

This section has been removed.

> ### Man pages
> * [ ]  ⚠️ It is recommended to add a package man page

A man page with the package overview and links to the functions has now been included.

> * [ ]  🟢 I highly recommend using the **{roxygen2}** package for function documentation, this is the standard for new packages and is much easier to read and maintain

This has now been integrated into the package. Roxygen2 comments can now be seen above the exported functions.

> ## Unit tests
> * [ ]  🚨 Please add unit tests that cover a large part of core functionality

We have added 3 Unit Test Files to tests/testthat which represent the 3 core functions of OutSplice with each one making sure no exceptions/errors are found and that the number of outliers found in our test data for an example event stays the same during testing. All other functions that OutSplice uses are called when running the main functions, so these tests encompass those as well. Please let us know if these tests will need to be expanded upon. A testthat.R file has also been added to the tests directory.

> ## Code
> ### R
> * [ ]  🚨 Please use `vapply` instead of `sapply`

This has been corrected in all scripts.

> * [ ]  🚨 Please use `seq_along()`/`seq_len()` instead of `1:...`

This has been corrected in all scripts.

> * [ ]  ⚠️ Please use named indicies instead of numeric indices

This has been corrected in some instances, however if possible, we would prefer to leave the remaining as is. The reason for using numeric indices in these functions is to specifically subset the first column which should always contain the user provided junctions. By using numeric instead of named indices for this, the user will not have to name this column something specific to work with the package.

> * [ ]  🟢 I didn't notice much reuse of Bioconductor data structures, are there any that could be used?

Currently, we are using the GenomicRanges package for genomic coordinates. OutSplice is also compatible with any annotation database on Bioconductor (“org.HS.eg.db”, “org.Mm.eg.db”, etc). and their associated TxDb packages (“TxDb.Hsapiens.UCSC.hg19.knownGene”, “TxDb.Mmusculus.UCSC.mm39.refGene”, etc.). The SummarizedExperiment may be useful to store the original matrices provided by the user when running OutSplice, however this can most likely be added on in the future if necessary.

> * [ ]  ⚠️ The `OutSplice` and `OutSplice_TCGA` functions are very similar, can you move some of the common code into shared sub-functions?

Most of the common code has now been moved into the following sub-functions: checkArgs, getExpressions, getGenomicInfo, getRPM, normalizeJunctions, subset_overEx, and subset_underEx.

> * [ ]  ⚠️ Consider adding validity checks for function arguments

Validity checks using “stopifnot()” have been added to the outspliceAnalsyis and outSpliceTCGA functions to check if the required argument files exist. The plotJunctionData function also now has a check if the data file argument exists and if the number of junctions to be plotted is an appropriate value. This function also contains IF statements that check to make sure the GENE and SYMBOL arguments are correctly specified.

> * [ ]  🟢 I found your code very difficult to read because of the lack of consistent indenting, please consider adjusting this (the **{styler}** and **{BiocStyle}** packages can help with this)

We have now used the styler package to help format the code and believe it should now be easier to read.

> * [ ]  🟢 I think L25 in `OGSAfunctionwFisher.R` can be simplified to `no.of.normals<-sum(PHENO==0])`

Yes, you are correct. This has been changed in this line and in L26 as well.

> * [ ]  🟢 L30 in `OGSAfunctionwFisher.R` is redundant given it is overwritten on the next line

We believe this line to be correct as written. Removing this line results in changes to the output and the results being incorrectly calculated.

> * [ ]  🟢 Avoid returning inside `return()` (i.e. `return(x <- y)`))

This has now been corrected.

> * [ ]  ⚠️ It is usually better to return function output and let the user decide how to handle than write directly to files within a function

If possible, we would prefer to leave this as is. OutSplice produces a few matrices, and for users who are inexperienced with R, directly getting output files is generally easier than having to get the matrices from a list of objects or from having to run multiple different functions. By having the set-up as is, the user will only need to run one function and get all of their splicing results in the folder of their choice. However, if you believe this is required for acceptance we will make the change.

**Comment by lazappi** [comment]
> It now seems to be building correctly on nebbiolo1, but not merida1, which gives the error `objects rowSums, colSums, rowMeans, colMeans are not exported by 'namespace:BiocGenerics'`.

Yes, hopefully that sorts itself out on the next update but I don't think it's something you have control over.

> Notes from BiocCheck have been addressed and only the below remain: Multiples of 4 spaces for line indents are used in most instances across the package code. (Generated using the styler package). The cases where this isn’t used are restricted to the man pages, which get formatted independently from roxygen2 or the BiocStyle package. Lines of 80 characters or more and functions longer than 50 lines have been left in as is. Each function still has one main purpose and the new styling should make them easier to read. Restricting the code to 80 characters per line also seems to make it more difficult to interpret during our process.

Ok. This is a style thing for me so I'm not going to insist but having a limit for line length (usually 80, sometimes 120) is fairly standard best practice across different languages and I find it quite difficult to read and understand your code because of the length of the lines.

> > * [ ]   🟢 Check if it is a appropriate to add any of the `biocViews` suggested by **{BiocCheck}**
> 
> The following biocViews have been added from ‘biocViews’: DifferentialExpression, DifferentialSplicing, VariantAnnotation However, we do not believe the recommended tag “Network” is appropriate for this package.

You may also want to add the "Software" view

> > * [ ]   ⚠️ I think some of the scripts files mentioned in `create_testset.R` don't exist, it would be better if all the code was included somewhere
> 
> Thank you for catching this. These were some old script files that we had used originally and forgot to remove. ‘create_testset.R’ now correctly reflects this. Additionally, the wrong rawcounts file was listed on L9 of this file and it has now been corrected.

I didn't think of this before but please confirm that the licenses etc. for TCGA allow you to redistribute this data.

> > * [ ]   🚨 Please update the introduction of the vigette to mention your motivation for inclusion in Bioconductor and any existing packages with similar functionality (if applicable)
> 
> The introduction in the vignette has now been rewritten to include this.

Just a small note, you have skipped a level of headings (you go from `#` to `###`). Not super important but it might look strange in the table of contents.

> We have added 3 Unit Test Files to tests/testthat which represent the 3 core functions of OutSplice with each one making sure no exceptions/errors are found and that the number of outliers found in our test data for an example event stays the same during testing. All other functions that OutSplice uses are called when running the main functions, so these tests encompass those as well. Please let us know if these tests will need to be expanded upon. A testthat.R file has also been added to the tests directory.

This looks ok for now. Test can always be expanded so they are never perfect, I tend to add things whenever a bug comes up.

> > * [ ]   ⚠️ Please use named indicies instead of numeric indices
> 
> This has been corrected in some instances, however if possible, we would prefer to leave the remaining as is. The reason for using numeric indices in these functions is to specifically subset the first column which should always contain the user provided junctions. By using numeric instead of named indices for this, the user will not have to name this column something specific to work with the package.

This is true but then the user has the have columns in a specific order to work with the package 😸. What can sometimes work well to handle this is to have a parameter that specifies which column to use, something like:

```r
func1 <- function(x, use_col = 1) {
	...
}
```

That way you can set a default but use a named variable within the function (and the user can set which column to use without modifying their data if needed).

> > * [ ]   ⚠️ The `OutSplice` and `OutSplice_TCGA` functions are very similar, can you move some of the common code into shared sub-functions?
> 
> Most of the common code has now been moved into the following sub-functions: checkArgs, getExpressions, getGenomicInfo, getRPM, normalizeJunctions, subset_overEx, and subset_underEx.

I think this is better now, the function still seem very similar though. 
 
> > * [ ]   ⚠️ It is usually better to return function output and let the user decide how to handle than write directly to files within a function
> 
> If possible, we would prefer to leave this as is. OutSplice produces a few matrices, and for users who are inexperienced with R, directly getting output files is generally easier than having to get the matrices from a list of objects or from having to run multiple different functions. By having the set-up as is, the user will only need to run one function and get all of their splicing results in the folder of their choice. However, if you believe this is required for acceptance we will make the change.

I'll admit this is a personal preference so I won't insist but I would really like to see this change. A simple compromise would be to move the code that saves the output to disk to a separate function. This would let inexperienced users save the output without needing to understand any more code but people familiar with R could decide how to handle the output. Having the results available in R without having read them from a file could also be useful to users who are likely to want to do further analysis of them (making plots etc.).

**Comment by GuoLabUCSD** [comment]
Hi @lazappi,

Here are some more fixes. Regarding the TCGA here is a link to their [data policy](https://broadinstitute.atlassian.net/wiki/spaces/GDAC/pages/844333156/Data+Usage+Policy). I have also gotten an email from them saying they are discussing this and am waiting for their reply. I know that the deadline for acceptance is April 19th, so I do not want to wait for their response, but would like to include this data if it is possible. What is the latest I should wait before replacing our data with basic and non-biologically relevant example tables.

> Ok. This is a style thing for me so I'm not going to insist but having a limit for line length (usually 80, sometimes 120) is fairly standard best practice across different languages and I find it quite difficult to read and understand your code because of the length of the lines.

I have gone through and trimmed/re-formatted most of the coding lines to not be longer than 120 at least.
 
> You may also want to add the "Software" view

The "Software" view  has been added.

> I didn't think of this before but please confirm that the licenses etc. for TCGA allow you to redistribute this data.

I am double checking this currently with the Broad Institute.

> Just a small note, you have skipped a level of headings (you go from `#` to `###`). Not super important but it might look strange in the table of contents.

Thanks for catching this. This has been fixed. 

> This is true but then the user has the have columns in a specific order to work with the package 😸. What can sometimes work well to handle this is to have a parameter that specifies which column to use, something like:
> 
> ```r
> func1 <- function(x, use_col = 1) {
> 	...
> }
> ```
> 
> That way you can set a default but use a named variable within the function (and the user can set which column to use without modifying their data if needed).

This is a good point and I have changed this for the outspliceAnalysis function which uses user-defined matrices. However, I believe this is not necessary for outSpliceTCGA for now. This function is specifically designed to work with TCGA formatted matrices and has columns/rows that are required to be in certain positions and removed, so a user shouldn't be editing these downloaded files for use with outSpliceTCGA specifically. Any edits to the matrices involving moving these indices would probably warrant the use of the regular function.

> I think this is better now, the function still seem very similar though.

I have added a new file called processMatrices.R which contains 2 functions with a substantial amount of shared code. I believe this should correct the issue now.

> I'll admit this is a personal preference so I won't insist but I would really like to see this change. A simple compromise would be to move the code that saves the output to disk to a separate function. This would let inexperienced users save the output without needing to understand any more code but people familiar with R could decide how to handle the output. Having the results available in R without having read them from a file could also be useful to users who are likely to want to do further analysis of them (making plots etc.).

This is a good point, outSpliceAnalysis and outSpliceTCGA now take an optional parameter to save these results to disk through the new saveResults() function. By default no files will be written and all of the results matrices will now be returned by the functions and available in R.

**Comment by GuoLabUCSD** [comment]
Hi @lazappi,

Here are some more fixes. Regarding the TCGA here is a link to their [data policy](https://broadinstitute.atlassian.net/wiki/spaces/GDAC/pages/844333156/Data+Usage+Policy). I have also gotten an email from them saying they are discussing this and am waiting for their reply. I know that the deadline for acceptance is April 19th, so I do not want to wait for their response, but would like to include this data if it is possible. What is the latest I should wait before replacing our data with basic and non-biologically relevant example tables.

> Ok. This is a style thing for me so I'm not going to insist but having a limit for line length (usually 80, sometimes 120) is fairly standard best practice across different languages and I find it quite difficult to read and understand your code because of the length of the lines.

I have gone through and trimmed/re-formatted most of the coding lines to not be longer than 120 at least.
 
> You may also want to add the "Software" view

The "Software" view  has been added.

> I didn't think of this before but please confirm that the licenses etc. for TCGA allow you to redistribute this data.

I am double checking this currently with the Broad Institute.

> Just a small note, you have skipped a level of headings (you go from `#` to `###`). Not super important but it might look strange in the table of contents.

Thanks for catching this. This has been fixed. 

> This is true but then the user has the have columns in a specific order to work with the package 😸. What can sometimes work well to handle this is to have a parameter that specifies which column to use, something like:
> 
> ```r
> func1 <- function(x, use_col = 1) {
> 	...
> }
> ```
> 
> That way you can set a default but use a named variable within the function (and the user can set which column to use without modifying their data if needed).

This is a good point and I have changed this for the outspliceAnalysis function which uses user-defined matrices. Now the function will accept optional arguments to specify the columns to use if they are in a different position, defaulting to 1. However, I believe this is not necessary for outSpliceTCGA for now. This function is specifically designed to work with TCGA formatted matrices and has columns/rows that are required to be in certain positions and removed, so a user shouldn't be editing these downloaded files for use with outSpliceTCGA specifically. Any edits to the matrices involving moving these indices would probably warrant the use of the regular function.

> I think this is better now, the function still seem very similar though.

I have added a new file called processMatrices.R which contains 2 functions with a substantial amount of shared code. I believe this should correct the issue now.

> I'll admit this is a personal preference so I won't insist but I would really like to see this change. A simple compromise would be to move the code that saves the output to disk to a separate function. This would let inexperienced users save the output without needing to understand any more code but people familiar with R could decide how to handle the output. Having the results available in R without having read them from a file could also be useful to users who are likely to want to do further analysis of them (making plots etc.).

This is a good point, outSpliceAnalysis and outSpliceTCGA now take an optional parameter to save these results to disk through the new saveResults() function. By default no files will be written and all of the results matrices will now be returned by the functions and available in R.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GuoLabUCSD.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("OutSplice")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OutSplice

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
