### ISSUE TITLE
scMultiome

### ISSUE THREAD

**Issue by xiaosaiyao** [Bioconductor/Contributions#2901]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xiaosaiyao/scMultiome

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by xiaosaiyao** [comment]
I have trouble verifying whether I have subscribed to the mailing list with yao.xiaosai@gene.com

I thought I did but I cannot log in or retrieve password reminder 

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by lshep** [comment]
I do not see you registered. Please check spam folders. there is normally a confirmation email that gets sent and sometimes it is marked as spam

**Comment by xiaosaiyao** [comment]
I still have a warning about unevaluated chunks. These chunks are for demonstrating how to upload new data and cannot be evaluated. Can we still proceed with the review?

**Comment by lgatto** [comment]
I spotted this new submission, which looks really interesting and I'll look more into it. I just also wanted to point to [SingleCellMultiModal](https://bioconductor.org/packages/release/data/experiment/html/SingleCellMultiModal.html), which seems to address similar needs. I would suggest @xiaosaiyao to cite SingleCellMultiModal in their [vignette intro](https://contributions.bioconductor.org/docs.html#vignette-introduction) and highlight any commonalities and differences. Once scMultimodal makes it into Bioc, I would suggest to send a PR to SingleCellMultiModal to update that vignette accordingly (and I'm happy to be reminded to do so if I forget).

**Comment by xiaosaiyao** [comment]
Thank you for the suggestion @lgatto. I will cite [SingleCellMultiModal](https://bioconductor.org/packages/release/data/experiment/html/SingleCellMultiModal.html) in my vignette

**Comment by hpages** [comment]
Hi @xiaosaiyao,

Thanks for submitting **scMultiome**. Can you please clarify what license is being used for the package? Based on the LICENSE file it looks like it's one of the Creative Commons licenses, but the file is not very clear about which one exactly. Also the file has many formatting issues, suggesting that maybe it's not the original version. It would be _much_ better if the `License` field could give the _exact name_ of the license. See the list of all Creative Commons licenses [here](https://creativecommons.org/licenses/).

Also please be aware that using a Creative Commons license for software is unusual and not recommended. From the [wikipedia article](https://en.wikipedia.org/wiki/Creative_Commons_license):

> While software is also governed by copyright law and CC licenses are applicable, the CC recommends against using it in software specifically due to backward-compatibility limitations with existing commonly used software licenses.[17][18] Instead, developers may resort to use more software-friendly free and open-source software (FOSS) software licenses. 

I'm going to take a closer look at the package now and will let you know if I have more feedback.

H.

**Comment by xiaosaiyao** [comment]
Thank you @hpages. The reason for having the Creative Commons license is because one of the datasets in this package came from ChIP-Atlas whose data follows a Creative Commons [license](https://dbarchive.biosciencedbc.jp/en/chip-atlas/lic.html) and after consulting with our legal team, we decided to follow their license. I will update the license to the exact name.

**Comment by hpages** [comment]
Hi @xiaosaiyao,

I noticed that the **scMultiome** relies a lot on the  **ArchR** package to demonstrate some important operations, but unfortunately **ArchR** is not a Bioconductor or CRAN package. This leads to the following situation: **ArchR** is used in the vignette and in various man pages but none of the code that demonstrates its use is actually evaluated, with the consequence that this code cannot be validated via the standard `R CMD build` and `R CMD check` commands.

Note that we insist that new contributions to Bioconductor interact with the existing Bioconductor ecosystem, which means that they should not rely on R packages that are not part of it. Disabling all the code in the vignette and examples that use **ArchR** is not considered good practice, and also doesn't address the real problem that **ArchR** is not part of the ecosystem in the first place. Have you considered discussing the submission of the **ArchR** package to Bioconductor with its authors/maintainers?

Other than that, I spotted 2 minor issues:

- In the vignette's introduction, I would suggest being more accurate about this (my proposed edits are in bold):

  "The MultiAssayExperiment **container (implemented in the `` `r Biocpkg("MultiAssayExperiment")` `` package)** provides a framework to package the various modalities into a single ~dataset~ **object** on a per cell basis."

- I see a lot of path constructions with things like `paste0(outdir,"/", genome, "/", TF.list[i],".bed")` or `paste0(dir, "chipatlas/", genome, "/", chipatlas.TFs[i])` where the path separator `/` is hardcoded. This is not considered good practice because it's not portable. It's always better to build file paths with `file.path()` or `system.file()`. This also has the extra benefit of making the code more readable.

Thanks

**Comment by xiaosaiyao** [comment]
Thank you so much for your comments @hpages. I will correct the minor issues.

Indeed, the integration between scMultiome and ArchR was intended to be seamless but was made challenging by the fact that ArchR is part of the BioC ecosystem. In fact, I am actively collaborating with @rcorces, the maintainer of ArchR.  I have spoken with @rcorces on this and the issue is that many of ArchR's dependencies are not in BioC/CRAN. @rcorces can chime in more. In situations like this, what do you recommend @hpages ?

**Comment by hpages** [comment]
> ... but was made challenging by the fact that ArchR is part of the BioC ecosystem.

You mean "by the fact that **ArchR** is NOT part of the BioC ecosystem".

> In situations like this, what do you recommend?

I would recommend focusing on getting **ArchR**'s dependencies on CRAN or Bioconductor. Then on getting **ArchR** itself on Bioconductor. Then finally on getting **scMultiome** in Bioconductor. This is the logical order. I'm afraid that trying to start with **scMultiome** is like trying to put the cart before the horse, unfortunately.

Best,
H.

**Comment by xiaosaiyao** [comment]
Thank you for your suggestions, @hpages 

Combining input from @rcorces, here is my reply:

1. ArchR has 3 dependencies not currently in BioC/CRAN and this includes Monocle3. At this point, it's really beyond us to convince the other folks to get their packages into CRAN/BioC

2. I still believe scMultiome should be in BioC because it is an ExperimentHub data package and contains standalone functions independent from ArchR

3. We have 2 sections called *ArchR Multiome Workflow* and *Conversion to MAE* in the vignette. These sections may have created some confusion and misled the reader into thinking that scMultiome requires these 2 steps to function. This is not the case since scMultiome contains multimodal datasets with raw counts that are compatible with other downstream packages. I suggest to remove these 2 sections from the vignette. Our plan is to release a separate package to address ArchR-MAE integration. 

I have already incorporated the other changes suggested by you and @lgatto
1. Update the introduction of the vignette to address the similarities and differences between scMultiome and singleCellMultiModal
2. Update the introduction of the vignette to properly cite the MultiAssayExperiment package 
3. Use `file.path` to construct paths rather than `paste0`

I hope the changes are acceptable

**Comment by hpages** [comment]
> ArchR has 3 dependencies not currently in BioC/CRAN.

It's less than that. Strictly speaking all **ArchR** dependencies, i.e. all the packages listed in its `Depends` field, are already in BioC/CRAN. Now it seems that **ArchR** also relies on some additional packages that can be installed with `ArchR::installExtraPackages()`, and only one of them, **presto**, is not in BioC/CRAN at the moment. It's worth noting that [**presto**'s README.md file](https://github.com/immunogenomics/presto) says that the package can be installed with `install.packages('presto')`, even though that's not actually the case, but might be an indication that the authors intend to have the package on CRAN soon.

Note that for some reason `ArchR::installExtraPackages()` installs **harmony** from GitHub even though the package is available on CRAN.

As for **monocle3**, I don't see it as a dependency, direct or indirect. But it's still worth noting that the [DESCRIPTION file](https://github.com/cole-trapnell-lab/monocle3/blob/master/DESCRIPTION) in the package has a `biocViews` field, which suggests that the authors intend to submit the package to Bioconductor soon.

Anyways, the good news is that the situation is not as bad as you might think. In the end, only **presto** is not on BioC/CRAN yet, but it's not inconceivable that this could change soon :wink: 

> I suggest to remove these 2 sections from the vignette. Our plan is to release a separate package to address ArchR-MAE integration.

Sounds like a reasonable thing to do.

Thanks for the latest changes. I'll take another look ASAP.

H.

**Comment by xiaosaiyao** [comment]
Hi @hpages, ArchR does depend on monocle3 in its trajectory [analysis](https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/Trajectory.R#L969). ArchR does not state Monocle3 as a dependency in the DESCRIPTION file but it installs Monocle3 through the `.requirePackage` function.

I will proceed to remove the two sections from the vignette

**Comment by xiaosaiyao** [comment]
Two further changes:
1. Updated the license information in the DESCRIPTION file
2. Removed data preprocessing section in the vignette since this is not a functionality supported by the scMultiome package. The preprocessing information of every dataset can be found in the metadata as pseudocode or description

**Comment by rcorces** [comment]
@xiaosaiyao @hpages - just to clarify about ArchR's dependencies.

Some of the things that are being discussed had previously been changed on the `dev` branch of ArchR. In particular, the `DESCRIPTION` file was inaccurate in previous versions and I updated it a few months ago but those updates are still sitting on `dev` (https://github.com/GreenleafLab/ArchR/blob/dev/DESCRIPTION). In particular, monocle3 is now Suggested by ArchR.

**Comment by xiaosaiyao** [comment]
@hpages Could you please comment on whether the package is good to go with all the latest changes? Thank you!

**Comment by vjcitn** [comment]
he's away for a few days.  he'll be back next week

**Comment by xiaosaiyao** [comment]
Just checking in on this submission...

**Comment by hpages** [comment]
Hi @xiaosaiyao ,

Sorry for the delay. Package looks good and is ready for inclusion to Bioconductor. Please delete the HTML vignette located in `scMultiome/vignettes/`. The HTML vignette will be automatically generated by `R CMD build` and placed in the resulting source tarball, so it should not be precomputed and placed in the package git repo.

Thanks,
H.

**Comment by xiaosaiyao** [comment]
Sorry for the late reply @hpages as I was away for a conference. I have removed the html file and I saw that you have accepted the package.  Thank you very much for your invaluable feedback!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xiaosaiyao.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scMultiome")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scMultiome

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
