### ISSUE TITLE
TDbasedUFE 

### ISSUE THREAD

**Issue by tagtag** [Bioconductor/Contributions#2906]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tagtag/TDbasedUFE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by tagtag** [comment]
I have pushed a new one as follows

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 215 bytes | 215.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0), pack-reused 0
To git.bioconductor.org:packages/TDbasedUFE
   51ddf28..c4443ae  master -> master

But no replies from bot which usually post that it received a valid push.
How long will it take to receive a message from bot here?

**Comment by lshep** [comment]
I responded to the mailing list as well -- you did not push a version bump. The Bioconductor system only process commits with a valid version bump (to trigger a new build in this process -- and to propagate to users on the daily build system).  Please bump the z of version x.y.z  -- (e.g. 0.99.1)

**Comment by tagtag** [comment]
> I responded to the mailing list as well -- you did not push a version bump. The Bioconductor system only process commits with a valid version bump (to trigger a new build in this process -- and to propagate to users on the daily build system). Please bump the z of version x.y.z -- (e.g. 0.99.1)

Thanks and sorry for my stupidness.

**Comment by Kayla-Morrell** [comment]
@tagtag - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: Installation instructions in the README file should also include
  Bioconductor installation instructions. Something like the following and for
the .Rmd should include `eval = FALSE` in the code chunk:

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("TDbasedUFE")
```

## DESCRIPTION

- [ ] REQUIRED: There is an extra 'DESCRIPTION~' file that should be removed.
- [ ] SUGGESTION: 'Based' is misspelled in the Title.
- [ ] SUGGESTION: Since you are using a standard license it's not necessary for
  you to include a LICENSE.md file with the package.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an
  entire package.

## Vignettes

- [ ] REQUIRED: Both vignettes need an 'Installation' section that demonstrates
  to the user how to download and load the package from Bioconductor. The code
should look like the following and include `eval = FASLSE` in the code chunk.

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("TDbasedUFE")
```

## Man pages

- [ ] REQUIRED: We don't allow for a `figures/` directory in the `man/`
  directory. I would suggest moving this to an `inst/figures/` directory and
changing the file path in the README file.

## R code 

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 67
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. There are 45 lines that are not.

Best,
Kayla

**Comment by tagtag** [comment]
@Kayla-Morrell 
Thank you very much for your excellent comments! I believed that I have addressed all the comments you raised. Only exception is "SUGGESTION: For formatting reasons, consider shorter lines. There are 67 lines that are > 80 characters long."  There are still two lines longer than 80 characters, but they include URL longer than 80 characters, which cannot be divided.  I am more than happy if you can advice me how to divide URL into two lines in Rmarkdown format. I have also done small modification in R code by which no problem has happened if I executed devtools::check(). I am glad if you can accept this package in your earliest opportunity. I would like to thank you again for your quick and proper evaluation of my package!

**Comment by tagtag** [comment]
@Kayla-Morrell 
Since I have noticed that I have failed to correct some of following points other than two URLs that I have mentioned in the above,

 SUGGESTION: For formatting reasons, consider shorter lines. There are 67
lines that are > 80 characters long.
 SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line
indents. There are 45 lines that are not.

I have corrected them and pushed version 0.99.3. Now the remaining issues are surely only two long URLs that I do not know how to write them up to 80 characters per one line. I am glad if you can verify this version and accept it!

**Comment by Kayla-Morrell** [comment]
@tagtag - Thank you for making the necessary changes. I've looked everything over and it looks good. I am more than happy to accept the package.

Best,
Kayla

**Comment by tagtag** [comment]
@Kayla-Morrell Thank you very much for your prompt evaluation and acceptance of my package. I really appreciate for your every effort to my package!
@lshep I am glad if you can include mine into Bioconductor nightly builds in the earliest opportunity!

**Comment by tagtag** [comment]
@lshep It was some time ago that it was accepted, but the issue is not closed. I am glad if you can inform me when this issue will be closed and the package is released in development ones. Sorry for bothering you in spite of your business.

**Comment by lshep** [comment]
I'm very sorry for the delay.  We have been working on some infrastructure updates that prevented us from ingesting packages into the nightly builds.  I believe they are remedied and I will proceed with this later today. Sorry for the inconvenience

**Comment by tagtag** [comment]
@lshep Thanks for your prompt reply in spite of your business. I am looking forward to hearing from you soon again!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tagtag.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TDbasedUFE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TDbasedUFE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
