### ISSUE TITLE
BiocHubsShiny

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#2915]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/BiocHubsShiny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
This is great!  so much better than interactive display backend that was laggish.  A few comments: 

**R code**

- [x] Should the links be changed to Bioconductor instead of LiNk-NY in about.R


**vignette**

- [x] Should the installation instructions be update to not install from the
  remote/github

- [x] You might want to hide the code to make the images appear. e.g:

```
knitr::include_graphics("figures/MusMusculusSelection.png")

```


**App**

- [x] When I choose "Download metadata", it downloads an rds file. I would've
  assumed I could load that into R?

```
> load("AnnotationHub_meta_sel_2023-02-24_12h50m.Rds")
Error in load("AnnotationHub_meta_sel_2023-02-24_12h50m.Rds") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  truncating string with embedded nuls
2: file 'AnnotationHub_meta_sel_2023-02-24_12h50m.Rds' has magic number 'X'
  Use of save versions prior to 2 is deprecated 

```

- [ ] taxonomyid gives a slider option to filter. This doesn't seem like it
  would be useful and if I try to enter an exact taxonomyid it won't let me not
  use the slider range.

- [ ] Is there a way to see suggested or valid suggestions for any of the
  filters?


Cheers!

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
I don't have a good answer for the filters. 
Perhaps @Kayla-Morrell can share some insights as she has worked with extending their functionality. 
I'll be happy to implement the improvements. 


> * When I choose "Download metadata", it downloads an rds file. I would've
>   assumed I could load that into R?

You should 'load' the Rds with `readRDS`. I have added a way to send the data to the
current session but this only works for users who run the app interactively (locally) 
and are not viewing it on a website (hosted).

Thanks!

**Comment by lshep** [comment]
Excellent. @Kayla-Morrell any thoughts on changing the slider functionality for taxonomyId and if there is a way to see any sort of valid or suggested filter values?  I still think a slider value for taxonomyId is not useful and should be treated as direct input for filter like a character vector would be -- suggested values would be nice but not necessary as most will probably know what they are looking for.

**Comment by lshep** [comment]
Once this is accepted @LiNk-NY I would encourage you to add a section to both AnnotationHub/ExperimentHub vignettes suggesting its use and advertising more heavily :)

**Comment by LiNk-NY** [comment]
I've updated the section in the `AnnotationHub` vignette https://github.com/Bioconductor/AnnotationHub/pull/36. 
I will work on the `ExperimentHub` one as well. Thanks!

**Comment by Kayla-Morrell** [comment]
@lshep @LiNk-NY The filtering option is dependent on the data type of the column. If you look at the [DT documentation](https://rstudio.github.io/DT/) you'll find info about how the filter option is handled, specifically:

"Depending on the type of a column, the filter control can be different. Initially, you see search boxes for all columns. When you click the search boxes, you may see different controls:

For numeric/date/time columns, [range sliders](http://refreshless.com/nouislider/) are used to filter rows within ranges;
For factor columns, [selectize inputs](http://brianreavis.github.io/selectize.js/) are used to display all possible categories, and you can select multiple categories there (note you can also type in the box to search in all categories);
For character columns, ordinary search boxes are used to match the values you typed in the boxes;"

So I'm assuming the taxonomyId column is a numeric value and therefore would be a range slider. To change the filter type I would change the data type for the specific column and go with the default behavior from DT. Hope this helps!

**Comment by lshep** [comment]
since it seems it default we can leave for now rather than switching data types.  If you get feedback with that column being as such as least there is some direction on how to potentially alter it.

**Comment by LiNk-NY** [comment]
Here is the PR for ExperimentHub: https://github.com/Bioconductor/ExperimentHub/pull/28

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocHubsShiny")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocHubsShiny

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
