### ISSUE TITLE
flowGate

### ISSUE THREAD

**Issue by NKInstinct** [Bioconductor/Contributions#2920]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/NKInstinct/flowGate

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ococrook** [comment]
HI @NKInstinct 

Thanks for the submission, I hope to look at this within the next 10 days. Please let me know if you have other dealines that we can try to accomodate.

Best wishes,
Olly

**Comment by NKInstinct** [comment]
Hi Olly - thanks so much! No deadlines at all, so please take all the time
you need.

Thanks again,

-Andrew

**Comment by ococrook** [comment]
Hi @NKInstinct 

This package is awesome! The vignette was so helpful, I have some suggestions before I move to accept the package. 

# Readme
 - [ ] Add statement about contributions/PRs etc
 - [ ]  Bioconductor install instructions
# News
- [ ] Make sure package versions match to description
# Vignette
- [ ] Add Bioc install instructions (eval = FALSE)
- [ ] Note theat devtools install will be an unstable development version
- [ ] I don’t see a `Clear` button in the GUI do you mean reset?
# Extdata
- [ ] Is it possible to document the data in extdata, for example add a readme so we know where this data come from and how it was generated
# R code
Looks good!
- [ ] You have some `:::` calls - are these needed?

**Comment by NKInstinct** [comment]
Hi @ococrook - thanks for the review and the enthusiasm around the package! I've implemented all of your excellent suggestions, thank you for catching my documentation goofs. 

The only comment I wanted to address here rather than change in the code is the use of ::: in the transformation function. Unfortunately, pulling out ggcyto's unexported fortify methods was the only way I could get a gating object to become reactive in shiny (it isn't an issue in the normal gating function because the gate itself doesn't need to be reactive, but here it needs to adjust based on how the user is transforming the gate). 

Currently my plan to handle this is just to have "make sure the ggcyto fortify methods haven't changed a bunch" at the top of my debugging flowchart, and then if flowGate gains a decent following, reach out to the ggcyto maintainers and see if they are willing to export this.

Happy to reconsider if you have another suggestion about how to address this!

**Comment by ococrook** [comment]
Hi @NKInstinct 

I agree with your strategy here. In the meantime, how about the following approach to improve robustness:

Have a specific unit test that checks that these methods are indeed doing what you expect?

**Comment by NKInstinct** [comment]
That's a great idea - I'll let you know once I've got it implemented.

**Comment by NKInstinct** [comment]
Hi @ococrook - just an update that the unit tests you suggested have been added and everything is building as expected.

Thanks again for all your help with this review!

**Comment by ococrook** [comment]
Great!  I look forward to seeing the package on bioconductor!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/NKInstinct.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("flowGate")`. The package 'landing page' will be created at

https://bioconductor.org/packages/flowGate

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
