### ISSUE TITLE
screenCounter

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#2940]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/crisprVerse/screenCounter
- 
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Aaron, @LTLA 
Thank your for your submission. 
Please see the review below. 
Apologies for the delay. 

Overall, the package looks to be in good shape. 
Best,
Marcel

--- 

# screenCounter #2940

The package looks good to go. Not many changes are required.
Thank you for your submission.

## DESCRIPTION

* Looks good.
* Add `BugReports` and `URL` fields.
* Consider adding ORCiD identifier to the `Authors@R` field.

## NAMESPACE

* Looks good.

## vignettes

* Looks good.

## R

* Probably no need to depreacate arguments in the function but you may have
had previous use internally.
* Default `BiocParallel` params look good.

## tests

* Coverage overall looks good:
```r
> covr::package_coverage()
screenCounter Coverage: 83.66%
inst/include/byteme/GzipFileReader.hpp: 0.00%
inst/include/kaori/handlers/CombinatorialBarcodesPairedEnd.hpp: 56.32%
inst/include/kaori/ScanTemplate.hpp: 70.83%
src/count_single_barcodes.cpp: 70.83%
inst/include/kaori/SimpleSingleMatch.hpp: 71.29%
src/count_dual_barcodes.cpp: 71.43%
src/count_combo_barcodes_single.cpp: 73.33%
src/count_combo_barcodes_paired.cpp: 75.86%
inst/include/kaori/MismatchTrie.hpp: 82.64%
inst/include/kaori/handlers/DualBarcodes.hpp: 85.07%
inst/include/byteme/SomeFileReader.hpp: 85.71%
R/countComboBarcodes.R: 90.00%
R/countSingleBarcodes.R: 90.00%
inst/include/byteme/RawFileReader.hpp: 90.48%
inst/include/kaori/FastqReader.hpp: 91.57%
src/utils.cpp: 92.31%
R/countDualBarcodes.R: 92.65%
inst/include/kaori/process_data.hpp: 93.18%
inst/include/kaori/BarcodePool.hpp: 93.33%
R/parseBarcodeTemplate.R: 93.75%
inst/include/kaori/handlers/CombinatorialBarcodesSingleEnd.hpp: 94.12%
R/combineComboCounts.R: 94.12%
inst/include/kaori/utils.hpp: 94.20%
inst/include/kaori/BarcodeSearch.hpp: 95.56%
inst/include/byteme/Reader.hpp: 100.00%
inst/include/kaori/handlers/DualBarcodesWithDiagnostics.hpp: 100.00%
inst/include/kaori/handlers/SingleBarcodeSingleEnd.hpp: 100.00%
R/countPairedComboBarcodes.R: 100.00%
src/utils.h: 100.00%
```

**Comment by LTLA** [comment]
Thanks for the review - changed to `DESCRIPTION`, removed deprecated arguments.

**Comment by LiNk-NY** [comment]
Thank you for your submission.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("screenCounter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/screenCounter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
