### ISSUE TITLE
DESpace

### ISSUE THREAD

**Issue by peicai** [Bioconductor/Contributions#2946]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/peicai/DESpace

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
Quitting from lines 276-278 (DESpace.Rmd) 
Error: processing vignette 'DESpace.Rmd' failed with diagnostics:
The package `concaveman` is required to calculate concave hulls
--- failed re-building ‘DESpace.Rmd’

```
Maybe a dependency fails to declare this requirement.  In any case, please add concaveman to 'Suggests' in DESCRIPTION.

**Comment by peicai** [comment]
Hi @vjcitn 
Thanks for your comment. I have updated the description as suggested.

Best, Peiying

**Comment by SimoneTiberi** [comment]
Hi Nils @nilseling,
happy to have you as our reviewer.

I noticed this `pandoc` related error just arose in all my Bioc packages: is this a temporary issue, or should `pandoc` be added in Imports (and NAMESPACE) when using rmarkdown?

```
--- re-building DESpace.Rmd using rmarkdown
Error running filter pandoc-citeproc:
Could not find executable pandoc-citeproc
Error: processing vignette 'DESpace.Rmd' failed with diagnostics:
pandoc document conversion failed with error 83
--- failed re-building DESpace.Rmd
```

**Comment by SimoneTiberi** [comment]
Hi Nils @nilseling,
glad to have you as reviewer.

I don't quite understand the error we got on mac OS BUILD:

```
--- re-building DESpace.Rmd using rmarkdown
Quitting from lines 83-108 (DESpace.Rmd) 
Error: processing vignette 'DESpace.Rmd' failed with diagnostics:
package or namespace load failed for 'spatialLIBD' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'AnnotationHub'
--- failed re-building DESpace.Rmd
```

It seems that, in the vignettes, when trying to load `spatialLIBD`, R doesn't find `AnnotationHub`, which is in `spatialLIBD` Imports.
We never use `AnnotationHub` directly, so it's not in our DESCRIPTION, and `spatialLIBD` is only in Suggests because we only use it in vignettes and examples (and not in our functions).
It feel we're doing things correctly; is the issue on our side?

Btw, we built it successfully on 2 mac OS laptops.

Thanks in advance,
Simone

**Comment by nilseling** [comment]
Hi @peicai,

thank you for submitting the `DESpace` package and apologies for the delay in reviewing it. The package is in a really good state and I only have minor comments to keep in line with the package guidelines. 

## The NAMESPACE file

- [x] Please check that you write all imported functions into the NAMESPACE file via `@importFrom package function` rather than calling `package::function` in the code.

## Documentation

**vignette**

- [x] In the Introduction section of your vignette please include a motivation for inclusion in Bioconductor. Here, you can also reference Bioconductor packages that perform similar analysis.
- [x] Please provide a Bioconductor Installation section in the vignette.
- [ ] Some of the code chunks that perform plotting operations are not easy to read. 

**man pages**

- [x] Please describe the exact outputs of the `individual_test` and `top_results` functions.

## Unit tests

- [x] Thanks for adding unit tests. The coverage is alright for now but I would recommend to increase it in the future.

```
DESpace Coverage: 45.70%
R/DESpace_test.R: 31.78%
R/FeaturePlot.R: 37.31%
R/plots_vignettes.R: 38.96%
R/individual_test.R: 49.25%
R/DESpace-internal.R: 50.67%
R/top_results.R: 81.36%
```

## R code

- [ ] There are quite a few lines of commented-out code in the package. I would recommend to exclude them as it's not clear why they are there.
- [ ] Please be consistent when perfuming assignment operations using `=` and `<-` at least in the vignette and man pages. This also relates to the following NOTE:

```
    * NOTE: Avoid using '=' for assignment and use '<-' instead
```

- [x] You provide the results of the `DESpace_test` function as `data.table` and not `data.frame` object. Is there a reason to not use `data.frame` or `DataFrame` instead? To me it appears as an additional dependency that you might not need.

**Comment by SimoneTiberi** [comment]
Hi @nilseling, 
thanks a lot for your review; this is very accurate and useful!
We actually missed most of the things you spotted, thanks for pointing them out.

We'll implement your comments and resubmit.

Take care,
Simone

**Comment by peicai** [comment]
Hi @nilseling,

Thank you for your review and time. I have already updated the package according to your comments.
Here are my updates:

- [x] The NAMESPACE file

removed all `package::function` in our function.

- [x] The vignette
included a motivation for inclusion in Bioconductor;
provided a Bioconductor installation;
added a few comments for plotting operation codes.

- [x] Main pages
provided a more detailed description of the outputs of the `individual_test` and `top_results` functions.

- [x] R code
removed unnecessary commented-out code in the package;
re-formatted the code style: used "<-" for all assignments;
used `data.frame` instead of `data.table` as the results of the `DESpace_test`.

As for the unit tests, we'd increased it in the future. 
Let me know if I missed anything.

Best,
Peiying

**Comment by nilseling** [comment]
That's great, thanks for addressing my previous comments.

What I meant with

> Some of the code chunks that perform plotting operations are not easy to read.

can still be seen for example in code chunk 10 `view LIBD layers`. It could use more line breaks to separate the individual `ggplot` commands and reduced the line length to 80 characters (which should be checked in all code chunks to make the vignette more readable).

**Comment by peicai** [comment]
Hi @nilseling 

Just an update that more line breaks in the vignette have been added.

Thanks again for all your comments!

Best,
Peiying

**Comment by nilseling** [comment]
Great, thanks! Then I'm happy to accept the package.

**Comment by SimoneTiberi** [comment]
Thanks for you time and your comments Nils.

**Comment by SimoneTiberi** [comment]
Hi @nilseling , I see the package is still not online: should we do anything?
I thought it would appear on the next day, but maybe I misunderstood timings.

Thanks,
Simone

**Comment by lshep** [comment]
@SimoneTiberi nothing more needs to be done on your end.   I normally ingest newly accepted packages within a week.  As you can imagine its quite busy during release time.  I most likely will get them on today or tomorrow.

**Comment by SimoneTiberi** [comment]
Hi @lshep,
thanks for the clarification.
I didn't mean to pressure you; I misunderstood the message below, so I thought I was missing something.
`It will be added to the Bioconductor nightly builds.`

No rush, thanks and have a good day,
Simone

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/peicai.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DESpace")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DESpace

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
