### ISSUE TITLE
BiocHail

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#2947]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/BiocHail

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
I am glad to see this is building on linux.  I may have to disable macos build ... interactions of java and python and spark may be too delicate for that OS.  I am checking a windows system now.

**Comment by ococrook** [comment]
Maybe worth checking the environmental variable is pointing to the jdk installation on MAC OS. (Assuming Java is installed)

On MAC OS this is usually somewhere in `/Library` rather than `/usr`. This is outside my expertise to make these changes on `merida1`, however.

**Comment by vjcitn** [comment]
Thanks.  My sense is that this is not going to work on windows [note from team](https://discuss.hail.is/t/using-hail-with-windows-subsystems-for-linux/1426/2); that was 2020 but I tried more recently to no avail.  And I don't think it will work on mac unless we downgrade jdk to 11 at latest.  I am trying to get time on an intel mac; I have definitely failed with M1.  For now I am going to set both macos and win to UnsupportedPlatform in .BBSoptions.

**Comment by ococrook** [comment]
Is it expected to work on all linux systems? If I can't install it on Fedora I may need to assign the review to someone else

**Comment by vjcitn** [comment]
I would expect it to run on any reasonably current x86_64 linux system.  If you have a problem and post the error messages here I will comment further.  It uses basilisk so the first install/execute leads to cached installation of miniconda and all necessary python infrastructure.  I am using 
```
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
```
and I think JDK <= 11 may be a hard requirement.  This could scupper this submission but it has to do with spark versions supported.  [Here](https://discuss.hail.is/t/tempo-of-infrastructure-upgrades-containerization/3146) is some relevant discussion with hail support.  (If you are working with JDK > 11, it may still work but with warnings...)

**Comment by vjcitn** [comment]
I guess you can have multiple jdks in linux?  So maybe I need to add a requirement and do some configuration.... I seem to have gotten lucky on the BBS

**Comment by ococrook** [comment]
Thanks @vjcitn, I'll try soon to see if I can get it install and hopefully I don't come up against any challenges if I do, I'll let you know.

**Comment by hpages** [comment]
@vjcitn Could you add a `.BBSoptions` file to the package to specify the unsupported platforms? E.g.

    UnsupportedPlatforms: win, mac

if the package is only going to be supported on Linux. Thanks

**Comment by vjcitn** [comment]
It runs on intel mac too.  I will add the .BBSoptions for win

**Comment by vjcitn** [comment]
@ococrook I finally made changes to get this to run cleanly on the linux builder.  I will have to go into the mac platform to get it to work there; could be a java config step needed.  Have you had a chance to try on fedora?  It won't work with jdk > 11 AFAIK.

**Comment by ococrook** [comment]
Hi @vjcitn and @lshep 

Unfortuntely, I don't have a way to install this package as my linux computer doesn't have admin rights so can't upgrade to the required dependencies and the package isn't supported on windows. I've had a look through the package and don't see anything to drawn concerns. Though I think someone who can put the package through some more thorough testing would be great to have a look at the package too.

Best wishes,
Olly

**Comment by vjcitn** [comment]
Can I ask which dependencies can't be met?  pip install at the user level should succeed to get hail itself in without privileges, and that is taken care of by basilisk.  The only other requirement would be java <= 11 and I have to work on configuration for that.   That might not be solvable, but admins could install jdk 11 alongside whatever is running and then the configuration could use it.  Of course we will try to find another reviewer, sorry to take up your time.

**Comment by ococrook** [comment]
We're actually stuck at R 4.1.2 or lower still, I can ask admins to see when when updade to 4.2 can happen

**Comment by Kayla-Morrell** [comment]
@vjcitn - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review. Also, keep in mind that the deadline for packages to be accepted for the 
upcoming release is April 19th.

## DESCRIPTION

- [ ] SUGGESTION: The 'Description:' field is made up by less than 3 sentences.
  Please consider expanding this field and structure it as a full paragraph.
- [ ] REQUIRED: Update R version dependency from 4.2 to 4.3.0.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be
  included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: The README.txt should be moved to `inst/script/`. This is
  where the documenation should be for any of the data in `inst/extdata/`.
- [ ] REQUIRED: There needs to be documentation in `inst/script/` for myss2.zip.

## Vignettes

- [ ] REQUIRED: There should be 'Installation' sections in the vignettes to show
  users how to download and load the package from Bioconductor.
- [ ] REQUIRED: The final section of the vignettes should be 'Session
  Information' and include `sessionInfo()`.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?BiocHail`.
- [ ] REQUIRED: There should be runnable examples to all man pages that document
  exported objects.
- [ ] SUGGESTION: Use `donttest{}` instead of `dontrun{}`. `donttest{}` requires
  valid R code while `dontrun{}` does not.

## R code

- [ ] SUGGESTION: Avoid 1:...; use seq_len() or seq_along().
- [ ] SUGGESTION: Avoid using '=' for assignment and use '<-' instead.
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 129
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider 4 spaces instead of tabs. 1
  line contains tabs.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. Thre are 201 lines that are not.


Best,
Kayla

**Comment by vjcitn** [comment]
I just did another commit after running styler, so now I think all comments have been addressed except the suggestion for making an overview man page.  I don't know how to do that with roxygen.  Thanks for the review!

**Comment by Kayla-Morrell** [comment]
@vjcitn - Thank you for making the necessary changes. I have reviewed everything and the package looks good. I'm more than happy to accept it.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocHail")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocHail

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
