### ISSUE TITLE
Rcollectl

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#2948]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/Rcollectl

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Thank you for the submission. Please see initial comments below. When ready please push changes to git.bioconductor.org with a valid version bump to trigger a new build and comment back here with a summary of updates. 

**NEWS**

- [ ] (Optinoal but strongly encouraged) Please include a NEWS file. At release
  time all updates captured in the NEWS files are added to the release
  announcement

**inst**

- [ ] It looks like most of these are templates.  Could you have an accompanied
  file that describes the data in `demotab/demo_1123.tab.gz` that includes any
  relevant source information and/or instructions on how to replicate it. It can
  be text, pseudocode, or code.

**vignette**

- [ ] I'm unclear at what data is taken as input or what needs to be run prior
  to running the commands. There is a section:
  
```
id = cl_start([target file prefix])
[use R until task to be measured is complete]
cl_stop(id)
usage_df = cl_parse(dir(patt=[target file prefix]))
# analyze or filter the usage_df (for example, to trim away
# time related to task delay or delay of `cl_stop`
plot_usage(usage_df)
```
But from the vignette it is unclear at what 'target file prefix' is.

- [ ] If this takes data collected from using collectl, I think a bigger
  reference to that at the start with a reference link to how to use that tool might
  be necessary. 

- [ ] Perhaps remove the comment in code chunk  `# March 8 blocking as SPB is
  erroring here`


**R code/man pages**

- [ ] When I try to run `browse_units()` it ends up launching teams and doesn't
  pull up anything to browse.


Cheers!

**Comment by lshep** [comment]
Just wanted to check in.  Please push updates and comment back here when ready for a re-review

**Comment by vjcitn** [comment]
thanks i will try to revise this week

**Comment by vjcitn** [comment]
**NEWS**

- [ok ] (Optinoal but strongly encouraged) Please include a NEWS file. At release
  time all updates captured in the NEWS files are added to the release
  announcement

*ADDED*

**inst**

- [ok ] It looks like most of these are templates.  Could you have an accompanied
  file that describes the data in `demotab/demo_1123.tab.gz` that includes any
  relevant source information and/or instructions on how to replicate it. It can
  be text, pseudocode, or code.

*Several folders removed, README.txt added to units.  demo_1123.tab.gz is described
in the cl_parse man page.*

**vignette**

- [ ] I'm unclear at what data is taken as input or what needs to be run prior
  to running the commands. There is a section:
  
```
id = cl_start([target file prefix])
[use R until task to be measured is complete]
cl_stop(id)
usage_df = cl_parse(dir(patt=[target file prefix]))
# analyze or filter the usage_df (for example, to trim away
# time related to task delay or delay of `cl_stop`
plot_usage(usage_df)
```
But from the vignette it is unclear at what 'target file prefix' is.

*revised to clarify the `[target file prefix]` notation*

- [ ] If this takes data collected from using collectl, I think a bigger
  reference to that at the start with a reference link to how to use that tool might
  be necessary. 

*reference added*

- [ ] Perhaps remove the comment in code chunk  `# March 8 blocking as SPB is
  erroring here`

*Done*

**R code/man pages**

- [ ] When I try to run `browse_units()` it ends up launching teams and doesn't
  pull up anything to browse.

*fixed thanks to herve's suggestion*


Cheers!

**Comment by lshep** [comment]
I'm still having trouble 

- [ ] I still cannot get `browse_units()` to work and still tries to launch
  teams.

**Comment by lshep** [comment]
Figured out the issue... 

Could you pass extra arguments to browserURL with `...` ?  I may be a specific case, but `browseURL(paste0("file://", path))` still opens up teams because if I do the default for browser for browseURL
```
> getOption("browser")
[1] "/usr/bin/xdg-open"
```
If I can pass my browser argument to use firefox of chromium it works fine
```
> browseURL(paste0("file://", path), browser="/snap/bin/firefox")
```
So if you can expand,
```
> browse_units
function () 
{
    path = system.file("units", "cl_units.html", package = "Rcollectl")
    browseURL(paste0("file://", path))
}
```
to have `...` that pass arguments to browseURL I think I would be ready to accept

**Comment by vjcitn** [comment]
The requested change was made

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rcollectl")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rcollectl

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
