### ISSUE TITLE
demuxSNP

### ISSUE THREAD

**Issue by michaelplynch** [Bioconductor/Contributions#2952]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/michaelplynch/demuxSNP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by michaelplynch** [comment]
Most recent changes (March 30th, March 31st) were updating dependencies from moves from BioCGenerics to MatrixGenerics of colSums and rowSums, and updates to unit testing. I welcome any feedback/ comments that could speed up approval! 
Thanks,
Michael

**Comment by LiNk-NY** [comment]
Hi Michael, @michaelplynch 

Thank you for your submission. See the review below. 

Best regards,
Marcel

---

# demuxSNP #2952

## DESCRIPTION

* Add a `BugReports` and `URL` fields pointing to the GitHub repository
* Looks good.

## NAMESPACE

* Looks good and minimal.

## vignettes

* (optional) Consider wrapping text to 80 column width.
* It may be better to run through the workflow itself rather than have an
examplar workflow steps that have `eval=FALSE` (Workflow section).
Alternatively, you could summarize the workflow steps conceptually as bullet
points.
* Everything else looks good.

## R

* Perhaps the test in `add_snps` can be a bit more semantically explicit?
`identical(mat, round(mat))` does this mean that the values in the matrix
should be whole numbers?
* Consider using more descriptive names in `data.R`.
* Consider using the "allocate and fill" rather than the "copy and append"
method in the `for` loop in the `reassign` function. This most often will
improve performace.

## NEWS.md

* Make sure you can parse the NEWS.md file with `utils::news` (use `*` instead
of `+`).

## README.md

* Consider adding more content to the `README.md`

## tests

* Coverage looks good.

**Comment by michaelplynch** [comment]
Hello @LiNk-NY , and many thanks for your review and suggestions!

I believe I have addressed each point. Please see responses below.

> # demuxSNP #2952
> ## DESCRIPTION
> * Add a `BugReports` and `URL` fields pointing to the GitHub repository
BugReports and URL fields added and pointing to package github repo
> * Looks good.
> 
> ## NAMESPACE
> * Looks good and minimal.
> 
> ## vignettes
> * (optional) Consider wrapping text to 80 column width.
I have wrapped the vignette text to 80 column width. There are a small number of lines in vignette and code (e.g. error catches with messages, markdown hyperlinks) where I feel it sensible to leave as one line but am happy to change these if you feel strongly. 
> * It may be better to run through the workflow itself rather than have an
>   examplar workflow steps that have `eval=FALSE` (Workflow section).
>   Alternatively, you could summarize the workflow steps conceptually as bullet
>   points.
Workflow has been made executable with a subset of the dataset so as not to add much to build time. There is one eval=FALSE remaining in the Function Explanation section, the function arguments are split into multiple lines so this is the clearest way I could find to present this particular case.
> * Everything else looks good.
> 
> ## R
> * Perhaps the test in `add_snps` can be a bit more semantically explicit?
>   `identical(mat, round(mat))` does this mean that the values in the matrix
>   should be whole numbers?
Yes, the default output of VarTrix which is input to this function should contain only 0s, 1s, 2s and 3s (thats how VarTrix codes different outcomes). The alternative VarTrix output contain proportions. So this was a check (maybe a little crude?) to catch if the wrong output matrix was being used. If you feel this needs to be more specific I'm happy to update but I felt this check should cover most misuse cases in a simple manner. I've also updated the error message and documentation slightly to highlight which matrix should be used.
> * Consider using more descriptive names in `data.R`.
Does this refer to the variable names (e.g. 'sce','vcf') or their description? I've now updated the description for each object. I was aiming to keep the variable names short and to the point- but please advise if I have misunderstood.
> * Consider using the "allocate and fill" rather than the "copy and append"
>   method in the `for` loop in the `reassign` function. This most often will
>   improve performace.
Agreed and changed. I've also slightly recoded some of this to make it a bit more robust

> ## NEWS.md
> * Make sure you can parse the NEWS.md file with `utils::news` (use `*` instead
>   of `+`).
Fixed and appears to be parsing ok with utils::news() and no longer raising issues in check()
> 
> ## README.md
> * Consider adding more content to the `README.md`
Updated to include short intro to the package, installation instructions and short descriptions of the functions, is this sufficient? Or should I expand further?
> ## tests
> * Coverage looks good.

I would also like to advise I'll be on leave from Friday 7th of April until after the April release date. If there are any outstanding issues at that point, please leave the issue open and I will address these on my return at the end of April.


Thanks, and regards,
Michael

**Comment by LiNk-NY** [comment]
Hi Michael, @michaelplynch 
Thank you for making those changes. Here are a few additional comments. 
Best,
Marcel

> > * Perhaps the test in `add_snps` can be a bit more semantically explicit?
> >   `identical(mat, round(mat))` does this mean that the values in the matrix
> >   should be whole numbers?
> >   Yes, the default output of VarTrix which is input to this function should contain only 0s, 1s, 2s and 3s (thats how VarTrix codes different outcomes). The alternative VarTrix output contain proportions. So this was a check (maybe a little crude?) to catch if the wrong output matrix was being used. If you feel this needs to be more specific I'm happy to update but I felt this check should cover most misuse cases in a simple manner. I've also updated the error message and documentation slightly to highlight which matrix should be used.

Perhaps you can check for an integer matrix instead? You could also include checks for the range of values. 

> > * Consider using more descriptive names in `data.R`.
> >   Does this refer to the variable names (e.g. 'sce','vcf') or their description? I've now updated the description for each object. I was aiming to keep the variable names short and to the point- but please advise if I have misunderstood.

Yes, the names should be more descriptive than 'sce'. Consider including the source of the data in the name. 

> > * Consider adding more content to the `README.md`
> >   Updated to include short intro to the package, installation instructions and short descriptions of the functions, is this sufficient? Or should I expand further?

It depends on how much you want your users to learn about the package from the GitHub page. 
Some packages use the main vignette as the `README.md`.

**Comment by michaelplynch** [comment]
Hi Marcel @LiNk-NY  ,
Thanks for your response.
1. Test in add_snps() has been updated to check it contains either 0s 1s 2s or 3s specifically.
2.  Variable names have been updated to be more descriptive of what they contain.
3.  readme.md has been extended to introduce that package, motivate its use and show a worked example at a similar level of details to the vignette.

Please let me know if you have any further comments!

Best,
Michael

**Comment by LiNk-NY** [comment]
Hi Michael, @michaelplynch 

Thank you for making those changes. I think it would be better to use the `%in%` operator instead of e.g., `x == 1 | x == 2` when checking the values in the matrix (in `add_snps()`). Also, if you expect the values to be integer, you may want to use `1L` rather than `1`.  
Other than that, everything looks good. Thank you for renaming the data objects. 

Best,
Marcel

**Comment by michaelplynch** [comment]
Hi Marcel, @LiNk-NY 
Of course, using %in% is a much cleaner way. Updated.
I've added a line to convert the matrix to integer within the function (after the above check), rather than requiring the user to supply an integer matrix.

Thanks,
Michael

**Comment by LiNk-NY** [comment]
Thanks for those changes. We have accepted your package. 
See this space for additional instructions and https://contributions.bioconductor.org for package maintenance tips. 
Best,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/michaelplynch.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("demuxSNP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/demuxSNP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
