### ISSUE TITLE
retrofit submission

### ISSUE THREAD

**Issue by akp6031** [Bioconductor/Contributions#2957]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/qunhualilab/retrofit

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment]
Hi @akp6031

Thanks for submitting **retrofit** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please address as many of the warnings from `BiocCheck::BiocCheck()` as possible

## Package data

- [ ] :rotating_light: Please expand the documentation for the datasets, this should describe the source of the data and what it contains

## Documentation

### README

- [ ] :warning: Once the package is accepted links to the vignettes can be updated to point to the Bioconductor package site

### Vignette

- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: Please expand the *Introduction* section to better desribe what the package is for. This should include your motivation for including the package in Bioconductor and mention any similar packages (if applicable).
- [ ] :warning: It wasn't clear to me which is the "main" vignette that a user should start with. It is ok to have a vignette that focuses on the paper results but I would expect there to be one that explains how to use the package, including what functions do, what the effect of parameters is, how to interpret plots etc.
- [ ] :warning: Please avoid `echo = FALSE` and `include = FALSE`, in general the vignette should show what the user would see if they were to run the code themselves
- [ ] :warning: It would be better if the image in the vignette was included in the package or downloaded using **BiocFileCache** (including it is probably easier)
- [ ] :green_circle: Could any of the plotting functions be included in the package? I imaging they would be useful for users and it would make the vignettes simpler.

### Man pages

- [ ] :warning: Please check there is rendered documentation for the `retrofit()` function, I could only find the package man page (maybe because they have the same name?)

## Code

### R

- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :warning: Where possible please use named indicies instead of numeric indices
- [ ] :rotating_light: Please use `<-` instead of `=`
- [ ] :warning: Please check if any of the `for` loops can be replaced
- [ ] :warning: Please remove any commented "dead" code
- [ ] :warning: It is generally clearer to use `nrow(x)/ncol(x)` rather than `dim(x)[1]/dim(x)[2]`

### C and Fortran code

- [ ] :warning: I'm not an expert on C++, what you have looks ok but please check:
  - [ ] Internal functions from R's C library are used (e.g. `R_alloc`)
  - [ ] C function registration used (See [Registering native routines](http://cran.fhcrc.org/doc/manuals/R-exts.html#Registering-native-routines))
  - [ ] The code checks for user interruption
  - [ ] `Makevars` and `Makefile` within a package

**Comment by akp6031** [comment]
Hi Luke, thank you for your valuable feedback!
We have carefully followed your instructions and updated the package. Here are the details with our comments.

# Review
**Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
###
**Answer:** O completed, V skipped with the reason in the comment.

## General package development
* [O]  ⚠️ Please address as many of the warnings from `BiocCheck::BiocCheck()` as possible
* A: We recognize the importance and will make sure to resolve any warning from BiocCheck()! The build bot of bioconductor is not showing any warning. 

## Package data
* [O]  🚨 Please expand the documentation for the datasets, this should describe the source of the data and what it contains
* A: We updated data.R to describe the contents and the sources of the datasets for Vignettes. Also we added references in the Vignette.

## Documentation
### README
* [V]  ⚠️ Once the package is accepted links to the vignettes can be updated to point to the Bioconductor package site
* A: Thank you! We will update the package shortly after a link is generated!

### Vignette
* [V]  🚨 Please add a table of contents
* A: Vignettes have rendered TOC since the initial submission. It seems there's a minor glitch that the visibility depends on different viewer apps in different devices. Please check two screenshots below. The rendered html contains TOC tag but the object may or may not show up in different softwares. We believe it will not make an issue in the bioconductor website. 

-- Opened with chrome (safari works the same)

<img src="https://user-images.githubusercontent.com/90921267/230820174-fd332590-d579-46ba-8485-31059a700872.png" width="400" height="300">

-- Opened with iphone

<img src="https://user-images.githubusercontent.com/90921267/230820159-e52554ea-d573-497c-ab5f-caad70681731.png" width="300" height="600">

* [O]  🚨 Please expand the _Introduction_ section to better desribe what the package is for. This should include your motivation for including the package in Bioconductor and mention any similar packages (if applicable).
* A: We have added more decription in Readme file regarding introduction, vignettes and similar work. Also, we have updated the introduction sections for the vignettes to better describe the package usage.
###
* [O]  ⚠️ It wasn't clear to me which is the "main" vignette that a user should start with. It is ok to have a vignette that focuses on the paper results but I would expect there to be one that explains how to use the package, including what functions do, what the effect of parameters is, how to interpret plots etc.
* A: Simulation Vignette is the main vignette that users should start with. We modified readme to state it more clearly, and also added more user friendly descriptions to the vignette. This vignette provides the overall functionalities of how to use the package, what the functions do, and how to interpret plots, etc.
###
* [O]  ⚠️ Please avoid `echo = FALSE` and `include = FALSE`, in general the vignette should show what the user would see if they were to run the code themselves
* A: We have removed echo=FALSE from the section of library(retrofit). However, knitr section seems to be suitable to set include=false.
###
* [O]  ⚠️ It would be better if the image in the vignette was included in the package or downloaded using **BiocFileCache** (including it is probably easier)
* A: Thank you for your suggestion! Now images are loaded with BiocFileCache.
###
* [V]  🟢 Could any of the plotting functions be included in the package? I imaging they would be useful for users and it would make the vignettes simpler.
* A: Thank you for this great suggestion! We would believe that RETROFIT results can be visualized by the widely-used ggplot2 package, as demonstrated in our current vignettes, and thus we did not find it necessary to develop our own visualization function in the current version of RETROFIT package.
However, we agree that visualization functions always provide invaluable benefits to users. We would like to first publish the RETROFIT package in BioC, gather user feedback, and then develop appropriate functions for visualization in light of the feedback for the next version of RETROFIT package.  

### Man pages
* [O]  ⚠️ Please check there is rendered documentation for the `retrofit()` function, I could only find the package man page (maybe because they have the same name?)
* A: Now both package and function documents are correctly rendered. However, since their names are same, they are both included in the same document: retrofit.Rd. We followed this advice: https://github.com/r-lib/roxygen2/issues/861

## Code
### R
* [O]  🚨 Please use `seq_along()`/`seq_len()` instead of `1:...`
* A: We have applied it.
###
* [O]  ⚠️ Where possible please use named indicies instead of numeric indices
* A: We have prioritized using named indices if the dataset supports it appropriately.
The remaining cases are usually dry computation, not having very specific domain meaning.
We would like to update the practices as we gain more insight about the computations.
###
* [O]  🚨 Please use `<-` instead of `=`
* A: We have applied it.
###
* [O]  ⚠️ Please check if any of the `for` loops can be replaced
* A: We have minimized using index-based for loops whenever possible but there were many cases vectorizations make confusions. If further modification is beneficial, we will make a schedule for refactorying.
###
* [O]  ⚠️ Please remove any commented "dead" code
* A: We have applied it.
###
* [O]  ⚠️ It is generally clearer to use `nrow(x)/ncol(x)` rather than `dim(x)[1]/dim(x)[2]`
* A: We have applied it.

### C and Fortran code
* [O]  ⚠️ I'm not an expert on C++, what you have looks ok but please check:
    * [O]  Internal functions from R's C library are used (e.g. `R_alloc`)
    * A: None of our codes is applicable.
    
    * [O]  C function registration used (See [Registering native routines](http://cran.fhcrc.org/doc/manuals/R-exts.html#Registering-native-routines))
    * A: None of our codes is applicable.
 
    * [O]  The code checks for user interruption
    * A: None of our codes is applicable.
 
    * [O]  `Makevars` and `Makefile` within a package
    * A: None of our codes is applicable.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/akp6031.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("retrofit")`. The package 'landing page' will be created at

https://bioconductor.org/packages/retrofit

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
