### ISSUE TITLE
pairedGSEA

### ISSUE THREAD

**Issue by shdam** [Bioconductor/Contributions#2958]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shdam/pairedGSEA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment]
First round of comments below! Note that many are suggestions and not strictly required. Please comment back here with what has/not been addressed how/why not, or any comments regarding any needed clarification or questions you might have; happy to help/discuss. Cheers!

# DESCRIPTION

- [ ] There's quite a lot of what one might call convenient but unnecessary dependencies (namely, `dplyr, magrittr, stringr, tibble, tidyr`). All of these are designed to facilitate coding for the general public, but not necessarily to replace base R in package development... Perhaps worth considering working around at least some. Given the overall package size and how often they occur in the `NAMESPACE`, it seems to me like there's an overly large number of dependencies. Some examples:
(Of course, many of these have overlapping dependencies, so they might not add much net weight. Yet, as a developer, it's desirable to get accustomed to implementation without relying on these "extras" when they don't provide much benefit - but yes, it depends...)
  - To give a trivial example, `'%!in%' <- Negate('%in%')` could be `!(x %in% y)` with base R... 
  - `tidyr` is being used twice in the entire package, and there only `separate()` is being used.
  - `magrittr` is only being imported for the pipe operator (`%>%`), which is not necessary to use.
  - What's being called from `stringr` is pretty straightforward with `gsub` and `strsplit`... 
  - The "Bioc-version" of a `tibble` would be for results to be returned as a `S4Vectors::DFrame` - this could then easily be added to the SE's `rowData` without additional coercion...

- # code

- [ ] The `paired_diff` example currently takes close to a minute to run (see build report), but the target here is less than 5 seconds. Is there a way to perhaps downsample or run on a sensible subset?

- [ ] Declaring global variables via `utils::globalVariables` is quite uncommon I'd say, and defeats the purpose of standard checks a little bit... I understand this is to work around non-standard evaluations by, e.g., `dplyr`. Again, coming back to the point above: That is why some generally recommend against non-standard evaluations in package development, and the packages that do this (if possible and when they don't add justifiable benefits).

- [ ] Strongly recommend adding some input argument validity checks at the top of functions... E.g., if a function expects results from an upstream step within the package, specific variable names are expected and their absence might cause confusing errors. Similarly, if a function expects a specific type of input (e.g., a formula, or input to `DESeq`), this can easily be checked. In addition, there could be checks for specific input types (e.g., single logical value) - to give a trivial example why this matters, `if (!quite)` fails if `quiet` is anything but `TRUE/FALSE`. But here are many cases where errors might be really confusing... e.g., when they occur during data wrangling because some variable isn't where/what it should be...

- [ ] Unit test coverage is at > 80%, however, there are currently only 1-6 hits/line (meaning everything is tested only very minimally)... Consider adding to these - you'll be grateful in the long run.

# documentation

- [ ] Across all man pages / roxygen documentation, consider highlighting variables, function and packages names as such, i.e., using code-style via `\code{...}` (this distinguishes R-related content from plain text, and thereby aids readability and comprehension). Also, it's nice to link to external functions and packages via `\link{...}` so that users can easily jump to relevant information if they wish.

- [ ] In the vignette, `BiocStyle` has designated functions to hyperlink external packages via `Biocpkg/CRANpkg/Githubpkg()` - consider using these.

# other

- type in `paired_ora` line 149: Defualt > Default

- [ ] The scripts in `data-raw/` should go in `extdata/inst/scripts` (see [here](https://contributions.bioconductor.org/data.html#raw-data-and-the-instextdata-directory)).

**Comment by shdam** [comment]
Hi Helena,

Thanks for the excellent input!

I have implemented all your comments in v.0.99.3. The latest push (v.0.99.4) addresses the warning, removes a redundant feature added with v.0.99.3, adds some tests, and fixes a minor issue.

- The code now solely uses the `ggplot2` tydiverse package.

- `utils::globalVariables` has been reduced to only contain `.data` (for `ggplot2`). Let me know if you know of a better solution.

- Not sure why `paired_diff` example takes so long. But I have downsampled it to run faster.

- I believe I added code style and links at all relevant places in the documentation, but please let me know if you spot any oversights.

- I put the `data-raw` scripts in `inst/script` according the the link you sent.

- I have added several unit tests, but will add more going forward.

I am aware of the note saying I should add `R (>= 4.3.0)` to the DESCRIPTION. I will do that after your next round of feedback.

Thanks again for your valuable feedback!

Best regards,
Søren

**Comment by shdam** [comment]
I am a bit confused with the warning. Should data man pages also include a `value` field?

**Comment by shdam** [comment]
Forgot to respond to your good point about adding a `DFrame` to an `SE`. I agree, but I guess there is a problem when `paired_diff` aggregates to gene-level, as the number of rows are no longer the same.
Anyhow, the function now returns a `DFrame` and a user can use that as they like.

A question: `fgsea` returns a `data.table`. For now, I don't do any coercion. Does Bioconductor recommend coercing to a `DFrame` or simply leaving the output as it is from this other Bioconductor package (`fgsea`)?

**Comment by HelenaLC** [comment]
Thanks for the speedy & attentive revision! All looks good now, and it's nice you could "lighten the weight" my working around unnecessary dependencies. Accepted, but you should (have to? not sure) still fix that warning! I.e.,
- re data man pages: yeah, R CMD check complains about that... In principle, you can put anything you like here. For example, [here](https://github.com/HelenaLC/CATALYST/blob/RELEASE_3_16/R/data.R) I described all data in a single document, and just put "see above" under `@return`. Alternatively, if there's a man page for each data, you could put the object type (e.g., a `data.frame`). 
- re `data.table` as output: not sure here... I'd say there is no clear recommendation. I'd argue that if an output could, in principle, be collected in the object, a `DFrame` would be nice... But as `data.table` also has a similar show method (not blowing up the console like a standard `data.frame`), there is no big difference in this context, though one might say a `data.table` is not very standard in Bioc...

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shdam.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pairedGSEA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pairedGSEA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
