### ISSUE TITLE
HiBED

### ISSUE THREAD

**Issue by zzhang23** [Bioconductor/Contributions#2965]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SalasLab/HiBED

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Ze, @zzhang23 
Thank you for your submission. 
See the review below. 
Best,
Marcel

---

# HiBED #2965

The package needs to make use of existing Bioconductor data representations
such as `SummarizedExperiment`. Currently it only uses matrix. The
implementation code needs revision and unit test coverage should be increased.

## DESCRIPTION

* Add a `BugReports` field.
* Consider adding your ORCiD ID.

## NAMESPACE

* Looks good.
* Consider renaming the main function to the name of the package (i.e.,
`HiBED()`)

## vignettes

* Consider including only one `data("HiBED_Libraries")` call in the vignette.
That is, evaluate the `data` call in line 33 and remove from 46.
* Remove the redundant use of `print`.
* Organize your vignette to include `Installation` and `Loading packages`
sections.

## R

* Remove the `.onLoad` function.
* Add a `@usage` section to the `HiBED_Libraries` documentation as
`@usage data("HiBED_Libraries")`
* Please format the code so that it fits the 80 character width limit and
remove uncommented code.
* Run `BiocCheck` and adjust the syntax accordingly.
* Consider using native pipes `|>` rather than `%>%` to avoid the dependency.
* Avoid evaluating large chunks of code within the `message` function
* Include the data type in the argument documentation as there are instances
where `h` is character (see line 138 in `HiBED_deconvolution.R`)
* Avoid using data from the `.GlobalEnv` and follow our recommendations in
https://contributions.bioconductor.org

## tests

* We strongly recommend that you increase coverage

```r
> covr::package_coverage()
HiBED Coverage: 1.37%
R/zzz.R: 0.00%
R/HiBED_deconvolution.R: 1.39%
```

**Comment by zzhang23** [comment]
Hi Marcel, @LiNk-NY 

Thank you for your review. I believe I have addressed your comments below

# HiBED #2965
The package needs to make use of existing Bioconductor data representations such as `SummarizedExperiment`. Currently it only uses matrix. The implementation code needs revision and unit test coverage should be increased.

**I changed the matrices to the format of `SummarizedExperiment`.**

> ## DESCRIPTION
> * Add a `BugReports` field.
>**Added.**
> * Consider adding your ORCiD ID.
> **Added.**
> ## NAMESPACE
> * Looks good.
> * Consider renaming the main function to the name of the package (i.e.,
>   `HiBED()`)
> 
> ## vignettes
> * Consider including only one `data("HiBED_Libraries")` call in the vignette.
>   That is, evaluate the `data` call in line 33 and remove from 46.
>**Removed**
> * Remove the redundant use of `print`.
>**Removed**
> * Organize your vignette to include `Installation` and `Loading packages`
>   sections.
> **Updated**
> ## R
> * Remove the `.onLoad` function.
>**Removed**
> * Add a `@usage` section to the `HiBED_Libraries` documentation as
>   `@usage data("HiBED_Libraries")`
>**Added.**
> * Please format the code so that it fits the 80 character width limit and
>   remove uncommented code.
> **Updated**
> * Run `BiocCheck` and adjust the syntax accordingly.
> **Updated**
> * Consider using native pipes `|>` rather than `%>%` to avoid the dependency.
> **`dplyr` is imported so this should be fine.**
> * Avoid evaluating large chunks of code within the `message` function
> **Updated**
> * Include the data type in the argument documentation as there are instances
>   where `h` is character (see line 138 in `HiBED_deconvolution.R`)
> **Updated**
> * Avoid using data from the `.GlobalEnv` and follow our recommendations in
>   https://contributions.bioconductor.org
> **New environment was created to store data.**
> ## tests
> * We strongly recommend that you increase coverage
> **Updated**

Please let me know if more things need to be addressed.

Best,
Ze

**Comment by LiNk-NY** [comment]
Hi Ze, @zzhang23 

Thank you for making those changes. It looks better. 
The documentation does not indicate that `SummarizedExperiment` is a possible input. Please adjust the function so that it can handle both `matrix` and `SummarizedExperiment` inputs (you may have to use `assay` to extract the `matrix` from the `SummarizedExperiment` object). 

It looks like [line 164 in `HiBED_deconvolution.R`](https://github.com/SalasLab/HiBED/blob/fb3e2542636e4e0067c5f1178be07434350e2127/R/HiBED_deconvolution.R#L164) is still looking for `h` of character type. Please fix this or it will not run if the expected input is numeric. 

Best,
Marcel

**Comment by zzhang23** [comment]
Hi Marcel, @LiNk-NY 

Thank you for your time. I misunderstood some of your previous comments but now corrected them accordingly.


> Thank you for making those changes. It looks better. The documentation does not indicate that `SummarizedExperiment` is a possible input. Please adjust the function so that it can handle both `matrix` and `SummarizedExperiment` inputs (you may have to use `assay` to extract the `matrix` from the `SummarizedExperiment` object).
**I updated the function to allow `SummarizedExperiment` as a possible input.**

> It looks like [line 164 in `HiBED_deconvolution.R`](https://github.com/SalasLab/HiBED/blob/fb3e2542636e4e0067c5f1178be07434350e2127/R/HiBED_deconvolution.R#L164) is still looking for `h` of character type. Please fix this or it will not run if the expected input is numeric.
**I corrected h as a numeric variable.**

Please let me know if more things are needed. Thanks.

Best,
Ze

**Comment by LiNk-NY** [comment]
Hi Ze, @zzhang23 

Sorry for the delay in getting back to you. 

* Can you please make use of the `assay` function as mentioned previously? 
E.g., 
`HiBED_Libraries$Library_Layer1@assays@data@listData$counts` should be something like  `assay(HiBED_Libraries$Library_Layer1, "counts")`
* consider moving large data packages such as `IlluminaHumanMethylation450kmanifest` to the `Suggests` field if the code in the package does not directly need it. It can also be loaded conditionally whenever the function is run (with `requireNamespace`). 

Best,
Marcel

**Comment by zzhang23** [comment]
Hi Marcel, @LiNk-NY 

Thank you for your feedback. I have made changes accordingly. 
> * Can you please make use of the `assay` function as mentioned previously?
>   E.g.,
>   `HiBED_Libraries$Library_Layer1@assays@data@listData$counts` should be something like  `assay(HiBED_Libraries$Library_Layer1, "counts")`

**I have updated that in lines 56-62 in `HiBED_deconvolution.R`.** 

> * consider moving large data packages such as `IlluminaHumanMethylation450kmanifest` to the `Suggests` field if the code in the package does not directly need it. It can also be loaded conditionally whenever the function is run (with `requireNamespace`).

**I have moved `IlluminaHumanMethylation450kmanifest` and `IlluminaHumanMethylationEPICmanifes`  to the `Suggests` field.**

Let me know if more changes are needed. Thanks a lot.

Best,
Ze

**Comment by LiNk-NY** [comment]
Hi Ze, @zzhang23 
Thank you for making those changes. 

It seems that the package does not make use of  `IlluminaHumanMethylation450kmanifest` and `IlluminaHumanMethylationEPICmanifest`. Do they need to be in the `Suggests` field? 
It seems to me that they can be removed. 

Best,
Marcel

**Comment by zzhang23** [comment]
Hi Marcel, @LiNk-NY 

Thanks for the suggestion.

`IlluminaHumanMethylation450kmanifest` is actually essential to load our example data but `IlluminaHumanMethylationEPICmanifest` is redundant. We kept `IlluminaHumanMethylation450kmanifest` and removed `IlluminaHumanMethylationEPICmanifest`.

Let me know if more changes are needed.

Best,
Ze

**Comment by LiNk-NY** [comment]
Hi Ze, @zzhang23 

Thank you for the update and for making those changes. 
Please address the `NOTE` from `R CMD check` at your earliest convenience. 

```r
* checking R code for possible problems ... NOTE
HiBED_deconvolution: no visible global function definition for ‘data’
HiBED_deconvolution: no visible binding for global variable ‘Sum’
Undefined global functions or variables:
  Sum data
Consider adding
  importFrom("utils", "data")
to your NAMESPACE file.
```

Best regards,
Marcel

**Comment by zzhang23** [comment]
Hi Marcel, @LiNk-NY 

>Please address the `NOTE` from `R CMD check` at your earliest convenience.
 **I believe I have addressed the `NOTE`.**

Thank you!

Best,
Ze

**Comment by LiNk-NY** [comment]
Thank you for making those changes. The package has been accepted. 
Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zzhang23.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HiBED")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HiBED

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
