### ISSUE TITLE
TOP

### ISSUE THREAD

**Issue by Harry25R** [Bioconductor/Contributions#2971]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/TOP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Your package has CPOP in description.  There is a package called "cpop" on CRAN.  Please correct your DESCRIPTION so that it uses only CRAN or Bioconductor packages in Imports/Suggests/Depends ...

**Comment by Harry25R** [comment]
I updated the description because it turns out it was unneeded

**Comment by vjcitn** [comment]
```
1/11 packages newly attached/loaded, see sessionInfo() for details.
** help
Warning: TOP_data_binary.Rd:11: unknown macro '\item'
```
that's causing problems for CMD check.

**Comment by vjcitn** [comment]
```
* checking for unstated dependencies in vignettes ... NOTE
'::' or ':::' import not declared from: ‘devtools’
'library' or 'require' calls not declared from:
  ‘Biobase’ ‘curatedOvarianData’ ‘ggbeeswarm’ ‘ggsci’ ‘survminer’
  ‘tidyverse’
```

**Comment by lshep** [comment]
Please remember R is case sensitive -- In your DESCRIPTION you have `CPOP` but I believe the CRAN package is lower case `cpop`

**Comment by Kayla-Morrell** [comment]
@Harry25R - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.17
release is 4/19. Any packages accepted after this date will be included in the
next release.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
  'comment=c(ORCID-"...")'.
- [ ] REQUIRED: 'LazyData:' in the 'DESCRIPTION' should be set to false or 
removed.
- [ ] REQUIRED: The 'Data:' field should be removed as this isn't usual practice
  for Bioconductor packages.
- [ ] REQUIRED: The following packages should be added to 'Suggests:' since they
  are called/used in the vignette.
	'Biobase', 'curatedOvarianData', 'ggbeeswarm', 'ggsci', 'survminer',
        'tidyverse'

## NAMESPACE

- [ ] REQUIRED: The package 'statmod' is listed as a Depends but is not imported
  from in the NAMESPACE file. This should be added.
- [ ] SUGGESTION: Consider adding `importFrom("stats", "coef", "offset", "sd")`.
- [ ] REQUIRED: The '%>%' is has both internal and export listed in its
  documentation. I would not export this function.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?TOP`.
- [ ] REQURIED: There should be runnable examples to man pages that document
  exported objects. The man page for calculateCCA does not have a runnable
example.
- [ ] REQUIRED: The use of donttest and dontrun is discouraged and generally not
  allowed; exceptions can be made with proper justification. If this option is
used it is preferable to use donttest instead of dontrun. donttest requires
valid R code while dontrun does not.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html.

## R code

- [ ] REQUIRED: Undefined global functions or variables:
        . Feature Features Organ Pathways coef coef_abs freq from lambda.min n
        name offset score sd to value variable
- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` instead.
- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` if possible.
- [ ] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods.
- [ ] REQUIRED: Avoid using '=' for assignment and use '<-' instead.
- [ ] REQUIRED: Avoid the use of 'paste' in condition signals.
- [ ] REQUIRED: Avoid 'suppressWarnings'/'Messages' if possible (found 1 times)
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 110 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
 indents. There are 111 lines that are not.

Best,
Kayla

**Comment by Harry25R** [comment]
@Kayla-Morrell 
Dear Kayla,
Thank you very much for your feedback! I've incorporated all of the requirements and pushed the new version 0.99.10. 
I've also attached below the suggestions that we've incoperated. 

## DESCRIPTION

- [x] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
  'comment=c(ORCID-"...")'.
  - Added Harry's ORCID ID.
- [x] REQUIRED: 'LazyData:' in the 'DESCRIPTION' should be set to false or 
removed.
 - LazyData is set to false.
- [x] REQUIRED: The 'Data:' field should be removed as this isn't usual practice
  for Bioconductor packages.
  - Removed Data.
- [x] REQUIRED: The following packages should be added to 'Suggests:' since they
  are called/used in the vignette.
	'Biobase', 'curatedOvarianData', 'ggbeeswarm', 'ggsci', 'survminer',
        'tidyverse'
  - Added suggestions to the Description file.

## NAMESPACE

- [x] REQUIRED: The package 'statmod' is listed as a Depends but is not imported
  from in the NAMESPACE file. This should be added.
  - Added statmod.
- [x] SUGGESTION: Consider adding `importFrom("stats", "coef", "offset", "sd")`.
  - Byproduct of lazy evaluation.
- [x] REQUIRED: The '%>%' is has both internal and export listed in its
  documentation. I would not export this function.
  - Removed export.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.
## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and lin_fixedks to the main functions. Users should be able to have a
relevant page display with `?TOP`.
- [x] REQURIED: There should be runnable examples to man pages that document
  exported objects. The man page for calculateCCA does not have a runnable
example.
  - Removed calculateCCA.
- [x] REQUIRED: The use of donttest and dontrun is discouraged and generally not
  allowed; exceptions can be made with proper justification. If this option is
used it is preferable to use donttest instead of dontrun. donttest requires
valid R code while dontrun does not.
Removed all cases where donttest and dontrun appear.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html.

## R code

- [x] REQUIRED: Undefined global functions or variables:
        . Feature Features Organ Pathways coef coef_abs freq from lambda.min n
        name offset score sd to value variable
  - Byproduct of tidyverse lazy evaluation.
- [x] REQUIRED: Avoid `sapply()`; use `vapply()` instead.
Changed all cases of sapply to vapply.
- [x] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` if possible.
- [x] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods.
- [x] REQUIRED: Avoid using '=' for assignment and use '<-' instead.
  - calcChanged all instances of this.
- [x] REQUIRED: Avoid the use of 'paste' in condition signals.
Removed stop(paste(...)) to stop(...)
- [x] REQUIRED: Avoid 'suppressWarnings'/'Messages' if possible (found 1 times)
Removed this case.
- [x] SUGGESTION: For formating reasons, consider shorter lines. There are 110 
lines that are > 80 characters long.
- [x] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
 indents. There are 111 lines that are not.
 
 Thanks again,
 Harry

**Comment by Harry25R** [comment]
@Kayla-Morrell Just wanted to clarify that the suggestions that were not checked off will be made a priority after review is complete. I was just aware of the approaching deadline you mentioned in your comments :) 

Kind regards,
Harry

**Comment by Kayla-Morrell** [comment]
@Harry25R - Thank you for making the necessary changes. I have reviewed everything and have just one requirement before I can accept the package. Let me know when the change has been made and I'll review it. I'm very confident this can be done by the April 19th deadline.

## NAMESPACE

- [ ] REQUIRED: I see you added the internal tag in the documentation for '%>%' but it is still being exported in your NAMESPACE file. Please be sure this export gets removed.

Best,
Kayla

**Comment by Harry25R** [comment]
@Kayla-Morrell Thanks for the feedback! :)
All comments have been addressed, and we will make your suggestions a priority after release.
Thanks for the support,
Harry

**Comment by Kayla-Morrell** [comment]
@Harry25R - Great, thanks for making that change! I'm happy to accept the package now.

Best,
Kayla

**Comment by Harry25R** [comment]
Thank you very much for all your help @Kayla-Morrell

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Harry25R.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TOP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TOP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
