### ISSUE TITLE
S4Arrays

### ISSUE THREAD

**Issue by hpages** [Bioconductor/Contributions#2978]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/S4Arrays

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Hi @ococrook,

The CHECK error was expected. It's because **S4Arrays** suggests the **SparseArray** package which I haven't submitted yet but will add to this submission ASAP (today or tomorrow).

Best,
H.

**Comment by ococrook** [comment]
Hi @hpages 

Great! If you comment when this change has been made I can review the package.

BW,
Olly

**Comment by hpages** [comment]
AdditionalPackage: https://github.com/Bioconductor/SparseArray

**Comment by hpages** [comment]
AdditionalPackage: https://github.com/Bioconductor/SparseArray

**Comment by hpages** [comment]
Hmm... the ERROR says that suggested package **SparseArray** is missing even though I added it as an AdditionalPackage.

Any idea what I am doing wrong @lshep @jwokaty?

**Comment by jwokaty** [comment]
I don't know the actual behavior here, but I noticed that S4Arrays is in `Depends` of SparseArray whereas SpareArray is in Suggests for S4Arrays. Did you do the version bumps: https://github.com/Bioconductor/Contributions/#circular-dependencies?

**Comment by lshep** [comment]
@hpages i have to precheck, process,  and add it to git before it would be found … I can do this later this afternoon when I’m on my computer

**Comment by lshep** [comment]
Additional packages are still reviewed before we add to any system to make sure someone does not do something nasty

**Comment by hpages** [comment]
@jwokaty I did the version bumps.

@lshep Thanks for your help!

**Comment by lshep** [comment]
give me a minute -- I'm adding it now

**Comment by lshep** [comment]
You'll get an auto report for SparseArray like you do for the original package when its been added -- then the traditional build on version bump happens

**Comment by hpages** [comment]
It worked. Thanks @lshep!

**Comment by ococrook** [comment]
Hi @hpages 

This looks great! A very easy vignette to follow and the r code is very clean. A couple of comments, though if they're not relevent then let me know:

Major comment

- [ ] It’s not clear from the README.md what the package is trying to do or why it’s needed. A brief rationale for the package here would aid users greatly.

Minor comments

- [ ] What’s the intended location of the link in the README.md?
- [ ] Is the suppressWarnings needed in `mapToGrid.R`
- [ ] I didn’t quite understand the functions in `array_selection.R` an example or expected output might help here?
- [ ] Does the disabled code need to be in the package?
- [ ] Could you update the NEWS/Description files to the packages match

when that done, if you could also add some intallsation instructions.

Thanks!
Olly

**Comment by hpages** [comment]
Hi @ococrook ,

Thanks for the feedback and sorry for the slow response.

FWIW the remaining "WARNING: Empty or missing \value sections found in man pages" is a false positive. The `Array-class.Rd` man page documents a class (`\docType{class}`) and no function (the class is virtual and has no associated constructor), so there's no notion of returned value.

> It’s not clear from the README.md what the package is trying to do or why it’s needed. A brief rationale for the package here would aid users greatly.

The `README.md` file is just the standard minimalist `README.md` that I use for other Bioconductor packages. See for example https://github.com/Bioconductor/BiocGenerics#readme or https://github.com/Bioconductor/Biostrings#readme. It just redirects to the official package landing page where all the details about the package can be found. Right now the link in **S4Arrays**' `README.md` doesn't work because the package doesn't have a landing page yet, but hopefully it will have one soon.

> Is the `suppressWarnings` needed in `mapToGrid.R`?

Yes, `suppressWarnings` is needed around calls to `min(x, na.rm=TRUE)` or `max(x, na.rm=TRUE)` to get rid of the annoying warning we get in the case where `x` contains only `NA`s. It's possible to avoid the use of `suppressWarnings()` by explicitely checking for the "all `NA`s" situation before calling `min()` or `max()`, but that is not as efficient as doing `suppressWarnings(min(x, na.rm=TRUE))` (it requires 2 passes on `x` instead of 1).

> I didn’t quite understand the functions in `array_selection.R` an example or expected output might help here?

I've tried to clarify what these functions do by expanding the `\examples` section. Keep in mind that they're not intended for end users, only for developers or advanced users curious about the internals of the **SparseArray** or **DelayedArray** packages.

> Does the disabled code need to be in the package?

Not sure what disabled code you're referring to. The non-evaluated code showed in the `\details` section of `array_selection.Rd` illustrates the narrative of the section.

> Could you update the NEWS/Description files to the packages match

The `NEWS` file anticipates the version bump to 1.0.0 that will happen on release day. So when all the `NEWS` files from all Bioconductor packages are collected and compiled into the 3.17 release announcement, the `NEWS` file for **S4Arrays** will reflect the just-released version of the package.

Let me know if you have further questions.

Thanks,
H.

**Comment by ococrook** [comment]
Thanks! Looks good!

**Comment by lshep** [comment]
@ococrook  does looks good mean accepted?  I would like to do a final processing today so all packages can get a build before the release?

**Comment by ococrook** [comment]
yes, I thought I already changed the tag last night

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpages.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("S4Arrays")`. The package 'landing page' will be created at

https://bioconductor.org/packages/S4Arrays

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpages.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SparseArray")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SparseArray

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
