### ISSUE TITLE
adverSCarial

### ISSUE THREAD

**Issue by GhislainFievet** [Bioconductor/Contributions#2983]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GhislainFievet/adverSCarial

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Please look at the Title field in your DESCRIPTION.  Revise and bump the version and push to your repo.

**Comment by vjcitn** [comment]
Your vignette is called "doc.Rmd"; please use a meaningful filename for your vignette -- eventually there may be multiple such.  It includes `shorttitle: "Short title for headers"` ... do not use the template without reading through.  Please run R CMD check on your package before bumping again and verify that there are no ERRORs.

**Comment by GhislainFievet** [comment]
Hi, thank you for your messages.

I modified what was asked and I ran the R CMD check command with 0 error and 0 warning.

**Comment by GhislainFievet** [comment]
The tool I submit is a parameter search, and building the vignette can take up to an hour. In my case I had to run the "ulimit -s unlimited" before the check to increase the available memory.

**Comment by vjcitn** [comment]
Thanks for this comment.  We have to be able to check the package in a modest amount of time.  THere is a longtests protocol.  You should sharply constrain the search in your vignette, or precompute and use a saved run.  RIght now I am seeing 
```
--- re-building ‘adverSCarial.Rmd’ using knitr
Error: processing vignette 'adverSCarial.Rmd' failed with diagnostics:
C stack usage  7969824 is too close to the limit
--- failed re-building ‘adverSCarial.Rmd’

SUMMARY: processing the following file failed:
  ‘adverSCarial.Rmd’

Error: Vignette re-building failed.
Execution halted

```
on a machine that can build all submissions.  Please check carefully and follow the contributor guidelines.  Thanks

**Comment by GhislainFievet** [comment]
Thank you for the advices :-) I did constraint the search for a vignette, and precomputed the others. There is no memory limit issue anymore, and the r cmd check command runs in 4 minutes. I did update my github repo.

What is the next step? Do I have too handle the push to git@git.bioconductor.org:packages/<YOUR-REPOSITORY-NAME>.git yet, to trigger the "10 tasks"?

Best regards.

Ghislain

**Comment by lshep** [comment]
Until you pass precheck, the package is not on git.bioconductor.org yet.  Once a reviewer is assigned then yes you would need to push there to trigger new builds.  For now just pushing to your github and commenting back here for us to look at it again is sufficient

**Comment by GhislainFievet** [comment]
Ok, thank you!

**Comment by DarioS** [comment]
The package is for perturbation analysis of classification by single cell RNA data.
 
- The adverScarial.Rmd vignette uses a TENxPBMCData data set and it compiles slowly on my old laptop computer with 4 GB RAM. Please see [Memory](https://contributions.bioconductor.org/general.html#memory) section of developer's guide. Vignettes should be able to run quickly even on 32-bit hardware (mine is 64-bit).

- List creation is inefficient. For example

```r
modifications <- list()
modifications[[1]] <- list("perc1")
modifications[[2]] <- list("perc99")
```

This should be done efficiently as `modifications <- c("perc1", "perc99")`. Please read [Pre-allocate and Fill](https://contributions.bioconductor.org/r-code.html#pre-allocate-and-fill-if-iterations-are-necessary) It also shouldn't be a list because all of the elements have the same data type. A character vector is sufficient.

- The code in the vignette overView_analysis.Rmd is not executed. The output is hard-coded. Please make all code chunks in this vignette executable. Same for advRandWalkMinChange.Rmd and adapt_classifier.Rmd.

- Use `camelCase` parameters and variabes, not `snake_case`. Please read [Variable Names](https://contributions.bioconductor.org/r-code.html#variable-names).

- Because there is more than one vignette document and it is not clear which order the vignettes should be read in a README.md file should be part of the repository to guide users how to read the guide. Please see [README File](https://contributions.bioconductor.org/readme.html?q=README#readme) for what to include.

- The first vignette which the user should read needs to contain biological motivation at the beginning of it. Why should readers care about min change attack and max change attack? Is it only a theoretical argument or is it modelling some read-world problem about single cell RNA data?

- The package needs interoperbility with existing Bioconductor classes. It currently only accepts base data structures such as matrix and data.frame as input. At a minimum it should accept SingleCellExperiment and DataFrame. Also, there is no input validitity checking by functions.
  > @param exprs a matrix or dataframe of numeric RNA expression

- It is unclear what function `MClassifier` does. The title of documentation is "Example cell type classifier for the pbmc3k dataset" but the parameters are `exprs`, `clusters`, `target`. Why is this function described as working on only one data set? Couldn't it work on any clustered data set?

- In many cases the parameter descriptions do not match their example values. For example, function `minChangeOverview` has `excl_genes = c()` and `genes = c()`. The definitions of these parameters are "a list of genes to exclude from the analysis" and "a list of genes in case you want to limit the analysis on a subset of genes" and Examples section has `genes <- c("CD4", "CD8A")`. Note that

```r
> class(genes)
[1] "character"
```

Please don't use `list` and character vector interchangeably. They are different types in R language.

- All function documentation files lack a Details section. Most of them should have such a section with a paragraph explaining how a function works. For example, `MClassifier`'s documentation doesn't explain the classification algorithm used. Is it k-Nearest Neighbours? Is it Nearest Shrunken Centroids? The reader doesn't know how classification works and how limited it is.

- `for` loops are not to be used in Bioconductor packages. For example, `for (cell_type in unique(clusters))`. Please refer to [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) of developer's guide. Please convent into vapply loops.

- Don't use `1:something` to create sequences. For example, `1:round(1 / step_change_ratio)`. It should be rewritten as `seq_len(step_change_ratio)`.

- adverscarial.R is has 1197 lines and almost all of the functions in the package are inside of it. Please put one function into one file, unless there are helper function directly related to a main function. Please refer to [Organise Functions into Files](https://r-pkgs.org/code.html#sec-code-organising).

**Comment by GhislainFievet** [comment]
Thank you for the review :-)
A lot of useful advices, I'm on it.

**Comment by GhislainFievet** [comment]
Hi,

I modified the package according to the review.

A few points:
- I modified the vignettes to increase the number of evaluated chunk, 2 out of 4 vignettes are fully evaluated, and the other are precomputed as advised by vjcitn in the firsts comments of this issue. I wanted to add real world examples with published data like the pbmc3k dataset, and the Bioconductor CHETAH classifier, but I couldn't make it computing time friendly. Vignettes can now be built quite quickly on any computer.
- I have eliminated most of the for loops in the code, but there are still a few that contain side effects.
- Instead of using `modifications <- c("perc1", "perc99")` as suggested, I have used `modifications <- list(c("perc1"), c("perc99"))`. This enables users to provide more advanced parameters, such as `list(c("perc1"), c("full_row_fct", myFct))`. I have included detailed instructions on how to construct these parameters in the vignettes and documentation.
- I have added the `DataFrame` data structure to all functions, but not `SingleCellExperiment`. This is because classifiers use different parts of SingleCellExperiment objects, such as the raw or normalized data, ENTREZ or gene symbols. To avoid confusion, users should provide the input data matrix directly.

Best regards.

Ghislain

**Comment by DarioS** [comment]
- Code still widely uses snake_case e.g. `tests_grid`, `gene_ind`, `modif_ind`, `exprs_temp`, `row_results`, etc.
- There still remain unnecessary `for` loops. For example:
  ```r
  row_results <- c()
  for (gene_ind in seq_len(length(genes)))
  {
     ...
     row_results <- c(row_results, paste(modifications[[modif_ind]], collapse = " "))
  }
  ```
  This is ideally suitable for `vapply`. Also, `seq_len(length(genes))` is unnecessary and could simply be `seq_along(genes)`.
  
  Similarly, `cbind` at the end of a `for` loop to incrementally grow a table is not efficient.
  
  ```r
  df_result <- data.frame(todel = unique(clusters))
  for (modif_ind in seq_len(length(modifications)))
  {
      ...
      df_result <- cbind(df_result, attacks_length)
  }
  ```
  
  Consider how to use `vapply` and `do.call(cbind, listOfResultingDataFrames)` instead.
  
- I didn't mean that the input should accept `DataFrame`. `DataFrame` is not used for gene expression data because the table will not have multiple variable types but they will all be a single numeric type. A few of your return values are `data.frame` and that would be suited to `DataFrame` for more compact display. For example `#' @return data.frame results of the classification of all the grid combinations.` is a return type of plain `data.frame`.
- The reasoning about not including `SingleCellExperiment` support is unclear. Which classifiers use raw, unnormalised data for classification? I don't think it makes sense to do that if there are batch effects or different numbers of RNA-seq reads per sample. The documentation is also vague: "#' @param classifier a classifier in the suitable format" what is "the suitable format" precisely? Please provide information in Details section. There's some information in the vignette but it is not clear:

> A classifier function has to be formated as follow to be used with *adverSCarial*:
> ```R
> classifier = function(expr, clusters, target){
>        
>    c("cell type", trust_value)
>  }
> ```

What is `trust_value`? Please define the output vector clearly.

- The user shouldn't have to manually convert single cell data by executing `matrixFromSCE` but this function could be used internally at the beginning of user-facing functions if the user specifies a `SingleCellExperiment` object to them.
- Lots of hidden code chunks at end of first vignette that do nothing important.
![image](https://user-images.githubusercontent.com/631218/232490964-1fa99034-4719-4741-9d0a-ab1707e59d38.png)

**Comment by GhislainFievet** [comment]
Ok, thank you, I'll correct these points.

Regards.

**Comment by GhislainFievet** [comment]
Hi, here are my corrections.

- ok for camelCase
- I used the `do.call(cbind , myList) ` with lapply
- The first for loop you mentionned modifies two exterior variables: `rowResults` and `exprsTemp`, I considered it as side effect, is it ok?
- I removed the DataFrame from the possible input, and made it the output format for `minChangeOverView`, `maxChangeOverview`, `advGridMinChange` and `advRandWalkMinChange`
- I added explanation on documentation on how to format a classifier, and added information about what is `trust_value` (which I renamed `score`)
- I removed the hidden chunks in vignettes.

**Comment by GhislainFievet** [comment]
About the `SingleCellExperiment` and the `matrixFromSCE`:
I would like my tool to be versatile. Users should be able to easily adapt any classifier in the appropriate format.

The [CHETAH](https://github.com/jdekanter/CHETAHclassifier) wants as input a SCE, easily created from raw data, eventhough they use normalized data to avoid batch effects. It is easy to adapt the CHETAH classifier to make it take as input a raw data matrix.
```
input <- SingleCellExperiment(assays = list(counts = input_counts),
                              reducedDims = SimpleList(TSNE = input_tsne))

## Run CHETAH
input <- CHETAHclassifier(input = input, ref_cells = reference)
```

The [scType](https://github.com/IanevskiAleksandr/sc-type) classifier takes as input a scaled matrix.
```
es.max = sctype_score(scRNAseqData = pbmc[["RNA"]]@scale.data, scaled = TRUE, 
                      gs = gs_list$gs_positive, gs2 = gs_list$gs_negative) 
```
In every cases it is easy to provide a data matrix, and make the classification from it.


It is also more convenient for my other functions. Let's say I accept SCE as input for `advMinChange`:
- I should add a parameter to specify which gene ID I want to use. The `pbmc3k` from `TENxPBMCData` comes with ENTREZ id as default, whereas I need gene symbols for the classifier.
- I should add a parameter to specify whether to send to the classifier the SCE object if it is CHETAH, or the scaled data if it is scType. I also need the information to know on which matrix I should make the RNA expression modifications.

It seems a lot easier to handle matrix of data.

I made the `matrixFromSCE` function for one specific situation, to show as an example in the vignette. But users should make their own functions to get the right matrix from the objects they use, SCE, Seurat, or raw data from the sequencing.

**Comment by GhislainFievet** [comment]
I have a general review related question. When using the bioconductor check function I tried to avoid 'NOTE' notifications, so I limited functions to 50 lines and lines to 80 characters. This makes my code quite difficult to read. Is this a point I should worry about? Can I let this go a little bit?

Thank you, best regards.

Ghislain

**Comment by lshep** [comment]
@GhislainFievet  yes we can be a little lenient when it comes to these stylistic preferences.  We put in a check as many would submit with no spacing, run-on lines, and massive functions that really should have been broken up for easy of maintenance.  If it doesn't make sense for your code base and your code is readable to review you can ignore the warning.

**Comment by GhislainFievet** [comment]
ok thanks :-)

**Comment by DarioS** [comment]
Thanks for the updates. However, I notice there is one more code block that incrementally grows an empty vector.

```r
lSplitsResults <- c(); i <- 1
while(i <= firstDichot) {
  lSplitsResults <- c(lSplitsResults, somethingElse)
 ...
 i <- i + 1
}
```

Also, operating on foundational classes such as SummarizedExperiment and SingleCellExperiment is a firm requirement for Bioconductor packages. @vjcitn, is only accepting a numeric matrix or `data.frame` of RNA-seq data O.K.?

> #' @param exprs a matrix or a data.frame of numeric RNA expression, cells are rows and genes are columns.
> users should make their own functions to get the right matrix from the objects they use, SCE, Seurat, or raw data

Also, in the vignette, it shows how to import single cell RNA-seq data from a TSV file. I don't think single cell RNA-seq data would ever realistically be distributed as a TSV file. For example [Human Cell Atlas Data Portal](https://data.humancellatlas.org/) uses loom format. Simlarly,  EMBL-EBI [Single Cell Expression Atlas](https://www.ebi.ac.uk/gxa/sc/home) uses MatrixMarket format.

> ```r
> matPbmc <- system.file("extdata", "pbmc_short.tsv", package="adverSCarial")
> matPbmc <- read.table(matPbmc, sep="\t")
> cellTypes <- system.file("extdata", "cell_type_short.tsv", package="adverSCarial")
> cellTypes <- read.table(cellTypes, sep="\t")$cell_type
> ```

It also recommends using Seurat objects which is generally incompatible with Bioconductor data containers.

> Then we convert the `test` dataset into a `Seurat` object for visualization purpose.

- Unexecuted code in third vignette gives warnings. The split warning of unequal lengths usually means incorrect calculations.

```r
> adv_max_change <- advMaxChange(rna_matrix, clusters_id, "DC", CHETAHClassifier, advMethod="perc99", maxSplitSize = 2000)
genes size: 14405
current gene results length: 0
Modify data for 7203 genes for cluster DC
Preparing data....
Running analysis...
Warning messages:
1: In split.default(unlist(genes), c(1, 2)) :
  data length is not a multiple of split variable
```

  Also, the result of this command, `mat_max_adver`, is very big:

  ```r
    ...        ...
                   PTTG1IP ITGB2 ITGB2-AS1 LINC01547 FAM207A ADARB1 POFUT2 COL18A1 SLC19A1 PCBP3 COL6A1 COL6A2
                   SPATC1L LSS MCM3AP-AS1 MCM3AP YBEY C21orf58 PCNT DIP2A S100B PRMT2 ND1 ND2 COX1 COX2 ATP8 ATP6
                   COX3 ND3 ND4L ND4 ND5 ND6 CYTB LOC389831 LOC102724770 LOC107987373 LOC102724250
 [ reached getOption("max.print") -- omitted 4217 rows ]
  ```

  You need to define a container class and `show` method for each kind of result, so the R command line isn't flooded.

- The fourth vignette, which is all unevaluated code, doesn't work.

   ```r
  > seurat_markers <- FindMarkers(pbmc, ident.1 = "DC", ident.2="CD14+ Mono")
      Error in ValidateCellGroups(object = object, cells.1 = cells.1, cells.2 = cells.2,  :
      Cell group 1 is empty - no cells with identity class
  ```

- Third and fourth vignettes (which use pre-determined results) need to be re-run with R version 4.3.0, now that it is the current version.

    ```r
    ## R version 4.2.0 (2022-04-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.4 LTS
    ```

**Comment by GhislainFievet** [comment]
Ok, thank you !
I will change that.

**Comment by lshep** [comment]
@GhislainFievet all dependent packages must be on CRAN or Bioconductor. Please remove loomR.

**Comment by GhislainFievet** [comment]
> @GhislainFievet all dependent packages must be on CRAN or Bioconductor. Please remove loomR.

Ok, thanks :-)

**Comment by GhislainFievet** [comment]
Hello Darios,

here are the changes related to your last review:

- I replaced the while loop by a lapply
- I added the possibility to add a SingleCellExperiment in the functions, with a new argument argForClassif to specify which object needs to be given to the classifier
- I converted my example single cell dataset as a loom file
- I removed all use of Seurat functions and used BioConductors packages instead
- the split warning was because I sometimes have to split uneven vectors, I coded a custom function to handle it without the warnings
- I double checked the unevaluated chunks, everything should work fine, and faster
- I upgraded to R 4.3

I have a concern about one point. Sometimes the results of my functions, avdMinChange and advMaxChange, can contain a lot of items, and you advised me to define specific class and a show method attached to them. I created two classes "advChar" and "advList", and specific show functions, which are declared on the .onLoad function. It works well, but it triggers a warning, I am a bit blocked on this. I understood that you can sometimes accept packages with warnings, could it be the case here? If it is not the case I would be very grateful to have an advice on how I could fix that :-)

Thanks again for your time.

Regards.

Ghislain

**Comment by DarioS** [comment]
Oh, please don't define classes in `.onLoad`. They should be defined in an ordinary R file, such as classes.R. Also, there is no documentation of the two new classes. Because the user will get an object of that class back from processing, the classes need to be documented. Please [see how DESeqDataSet is implemented](https://github.com/mikelove/DESeq2/blob/devel/R/AllClasses.R) in the famous Bioconductor package DESeq2 for insipration. Also, thanks for switching to the Bioconductor package LoomExperiment for data management and increasing interoperability.

**Comment by GhislainFievet** [comment]
Ok thank you, I'm on it :-)

**Comment by GhislainFievet** [comment]
Hi Dario,

I've made the modifications related to your last post:
- I removed the .onLoad function
- I added a allClasses.R file to store the classes
- I added documentation about these custom classes

Best regards

Ghislain

**Comment by DarioS** [comment]
Thanks for updates.

My main concern is that your package depends on plain matrices and data frames. The data is sparse and mostly zero. How much RAM would a realistic data set take if it has ten thousand rows (genes) and one hundred thousand columns (cells)? I think comprehensive support for [DelayedArray](https://bioconductor.org/packages/release/bioc/html/DelayedArray.html) needs to be provided. Converting into matrix is very inefficient for sparse single-cell RNA data.
```r
if (is(exprs,'SingleCellExperiment')) exprs <- as.matrix(t(counts(exprs))) # RAM usage explosion.
```

> The package contains a marker based classifier working on the pbmc3k dataset: `MClassifier`. We verify it is classifying properly. 


What is "properly" and why does the output mean it is working properly? Please add clarity.

```r
> resClassif
[1] "DC" "1" 
```

Remember to use Bioconductor style assignment `<-` instead of `=`.

```r
# Known markers for each cell type
markers = c("IL7R", "CCR7", "CD14", "LYZ", "S100A4", "MS4A1", "CD8A", "FCGR3A", "MS4A7", "GNLY", "NKG7", "FCER1A")
```

Vignette 2 has syntax error due to unmatched backticks and so it doesn't compile.

![image](https://github.com/Bioconductor/Contributions/assets/631218/25679b54-6cda-4159-a371-bb316caddb96)

```r
> modifOutlier <- function(x){
+     return (max(x)*1000)
+ }
> 
> ```{r use the function, warning = FALSE}
Error: attempt to use zero-length variable name
```

Vignette 3 has `train_3k` and `test_4k` data sets. Are they directly comparible or is batch effect correction needed? I noticed a different instrument and different chemistry for the two data sets.

```r
> head(colData(train_3k))
DataFrame with 6 rows and 11 columns
       Sample          Barcode       Sequence   Library Cell_ranger_version Tissue_status Barcode_type   Chemistry Sequence_platform    Individual Date_published
  <character>      <character>    <character> <integer>         <character>   <character>  <character> <character>       <character>   <character>    <character>
1      pbmc3k AAACATACAACCAC-1 AAACATACAACCAC         1              v1.1.0            NA      GemCode Chromium_v1        NextSeq500 HealthyDonor2     2016-05-26
2      pbmc3k AAACATTGAGCTAC-1 AAACATTGAGCTAC         1              v1.1.0            NA      GemCode Chromium_v1        NextSeq500 HealthyDonor2     2016-05-26
3      pbmc3k AAACATTGATCAGC-1 AAACATTGATCAGC         1              v1.1.0            NA      GemCode Chromium_v1        NextSeq500 HealthyDonor2     2016-05-26
4      pbmc3k AAACCGTGCTTCCG-1 AAACCGTGCTTCCG         1              v1.1.0            NA      GemCode Chromium_v1        NextSeq500 HealthyDonor2     2016-05-26
5      pbmc3k AAACCGTGTATGCG-1 AAACCGTGTATGCG         1              v1.1.0            NA      GemCode Chromium_v1        NextSeq500 HealthyDonor2     2016-05-26
6      pbmc3k AAACGCACTGGTAC-1 AAACGCACTGGTAC         1              v1.1.0            NA      GemCode Chromium_v1        NextSeq500 HealthyDonor2     2016-05-26

> head(colData(test_4k))
DataFrame with 6 rows and 11 columns
       Sample            Barcode         Sequence   Library Cell_ranger_version Tissue_status Barcode_type   Chemistry Sequence_platform    Individual Date_published
  <character>        <character>      <character> <integer>         <character>   <character>  <character> <character>       <character>   <character>    <character>
1      pbmc4k AAACCTGAGAAGGCCT-1 AAACCTGAGAAGGCCT         1                v2.1            NA     Chromium Chromium_v2         Hiseq4000 HealthyDonor1     2017-11-08
2      pbmc4k AAACCTGAGACAGACC-1 AAACCTGAGACAGACC         1                v2.1            NA     Chromium Chromium_v2         Hiseq4000 HealthyDonor1     2017-11-08
3      pbmc4k AAACCTGAGATAGTCA-1 AAACCTGAGATAGTCA         1                v2.1            NA     Chromium Chromium_v2         Hiseq4000 HealthyDonor1     2017-11-08
4      pbmc4k AAACCTGAGCGCCTCA-1 AAACCTGAGCGCCTCA         1                v2.1            NA     Chromium Chromium_v2         Hiseq4000 HealthyDonor1     2017-11-08
5      pbmc4k AAACCTGAGGCATGGT-1 AAACCTGAGGCATGGT         1                v2.1            NA     Chromium Chromium_v2         Hiseq4000 HealthyDonor1     2017-11-08
6      pbmc4k AAACCTGCAAGGTTCT-1 AAACCTGCAAGGTTCT         1                v2.1            NA     Chromium Chromium_v2         Hiseq4000 HealthyDonor1     2017-11-08
```

`logNormCounts` is failing because of a problem in a dependency package. This should fix itself soon, so no action needed.

```r
> test_4k <- logNormCounts(test_4k)
Error: BiocParallel errors
  1 remote errors, element index: 1
  2 unevaluated and other errors
  first remote error:
Error in .OLD_read_block(x, viewport, as.sparse = as.sparse): could not find function ".OLD_read_block"
```

Functions have `verbose = FALSE` parameter but it seems ignored and the R console is flooded with output regardless.

```r
> genesMaxChange <- advMaxChange(matPbmc, cellTypes, "DC", MClassifier, exclGenes = markers, advMethod = "perc99")
genes size: 186
current gene results length: 0
Modify data for 93 genes for cluster DC
B
1
genes size: 93
current gene results length: 0
Modify data for 46 genes for cluster DC
B
1
genes size: 46
current gene results length: 0
Modify data for 23 genes for cluster DC
DC
1
same cellType
Modify data for 23 genes for cluster DC
B
1
genes size: 23
current gene results length: 23
Modify data for 12 genes for cluster DC
B
1
genes size: 12
current gene results length: 23
Modify data for 6 genes for cluster DC
B
1
genes size: 6
current gene results length: 23
Modify data for 3 genes for cluster DC
B
1
genes size: 3
current gene results length: 23
Modify data for 2 genes for cluster DC
B
1
genes size: 2
current gene results length: 23
Modify data for 1 genes for cluster DC
B
1
Modify data for 1 genes for cluster DC
DC
1
same cellType
check if concat lists still gives target
length of tested gene list: 24
Modify data for 24 genes for cluster DC
YES: merge results
results length after merge: 24
Modify data for 1 genes for cluster DC
DC
1
```

Some unnecessary `for` loops remaining. For example, `.getUniqueIndex` could be avoided using `unique` and `match`.

```r
.getUniqueIndex <- function(cArray) {
    cPrev <- c()
    cResult <- c()
    for (i in seq_along(cArray)) {
        if (!is.na(cArray[i])) {
            if (!cArray[i] %in% cPrev) {
                cResult <- c(cResult, i)
                cPrev <- c(cPrev, cArray[i])
            }
        }
    }
    cResult
}
```

It can be written in one line using existing R functions without the need to define, test, maintain a function.

```r
> data <- c(1, 2, 3, 3, 4, NA, 5)
> setdiff(match(unique(data), data), which(is.na(data))) # Determines the unique indices, avoids missing values.
  1 2 3 5 7
```

**Comment by GhislainFievet** [comment]
Ok, thank you :-)
I will look into the matrix/dataframe/sparse matrix issue, and fix mentionned points.

Ghislain

**Comment by GhislainFievet** [comment]
Hello Dario,


I made the modifications related to your previous post.

- thank you for the "setdiff(match( ..." it is way more elegant
- I fixed the verbose issues
- in the [CHETAH documentation](https://www.bioconductor.org/packages/release/bioc/vignettes/CHETAH/inst/doc/CHETAH_introduction.html) it says in paragraph 7.2 that datasets should be of the same biological type, not a lot more. After looking at the results on a UMAP we can see the similar composition in term of cell types bewteen the pbmc3k and the classified pbmc4k, it seems to be working fine.
- I fixed the vign2 syntax error
- I remove the '=' and replaced them with '<-'
- I added explanations in the vignette about the 'properly classified'

About the DelayedMatrix matters. This is effectly memory saving but it takes longer to modify the matrix. So I added the use by default of DelayedMatrix for the functions making only small modifications like advRandWalkMinChange and advGridMinChange. And I set the default to data.frame for advMinChange, advMaxChange, maxChangeOverview and minChangeOverview. I added support for DelayedMatrix in all the functions, and user can choose the format used during the modification with the option argForModif.

Here is an example showing the difference of execution time for data.frame vs DelayedMatrix modification.
  
```
> mat <- matrix(0, nrow = 3000, ncol = 20000)
> random_indices <- sample(length(mat), 0.1 * length(mat))
> mat[random_indices] <- sample(1:10, length(random_indices), replace = TRUE)
> 
> # Same dataframe and DelayedMatrix
> df_mat <- as.data.frame(mat)
> delayed_mat <- DelayedArray(mat)
> 
> # Random genes and cell type vectors
> genes = sample(1:20000, 100)
> cells = sample(1:3000, 500, replace=T)
> 
> system.time({df_mat[cells, genes] <- 1})
   user  system elapsed 
  0.010   0.000   0.017 
> system.time({delayed_mat[cells, genes] <- 1})
   user  system elapsed 
  0.056   0.003   0.069 
```
 You mentionned an issue with hundred thousand cells datasets. It indeed seems complicated, for data.frame or DelayedMatrix, to handle at the same time the memory issue and a reasonnable computing time to repeatedly modify hundreeds of cells and genes. Users should therefore subsample their data relative to their computational capacities.

Best regards, have a nice day.

Ghislain

**Comment by DarioS** [comment]
The issues have been addressed satisfactorily.

**Comment by GhislainFievet** [comment]
Hello @DarioS 
 
thank you again for all your help, and your endless patience which permitted me to improve the package to be bioconductor quality :-) I learned a lot, and I will use this knowledge for my future works!

best regards

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GhislainFievet.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("adverSCarial")`. The package 'landing page' will be created at

https://bioconductor.org/packages/adverSCarial

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
