### ISSUE TITLE
gdrplatform release [second package: gDRtestData]

### ISSUE THREAD

**Issue by bczech** [Bioconductor/Contributions#2987]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gdrplatform/gDRtestData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of gDRtestData.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by gladkia** [comment]
Hi @vjcitn  and @lshep,

The error that appears: `Packages suggested but not available: 'gDRutils', 'gDRstyle', 'gDRcore'` is due to the fact that we are submitting all these packages to Bioc 3.17.  
Thanks in advance for the hints on how to deal with it properly.

Best,
Arek

**Comment by gladkia** [comment]
Hi @lshep,

I'm not able to trigger the build by pushing to the `git@git.bioconductor.org:packages/gDRtestData`. The following error occurs: 
```
gladkia@gladkia-UHMD6M gDRtestData % export LANG=en_US.utf8 git push 
gladkia@gladkia-UHMD6M gDRtestData % LANG=en_US.utf8 git push  
FATAL: W any packages/gDRtestData gladkia DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

gladkia@gladkia-UHMD6M gDRtestData % LANG=en_US.utf8 git status
On branch devel
Your branch is ahead of 'upstream/devel' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

gladkia@gladkia-UHMD6M gDRtestData % head -n 15 .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:gdrplatform/gDRtestData.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
	url = git@git.bioconductor.org:packages/gDRtestData.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "master"]
	remote = origin
```
@bczech, tried as well and the same error appeared.

Thanks in advance for your help!

**Comment by lshep** [comment]
@gladkia  you should now have access.  On submission, we assume the person submitting is the maintainer and would be pushing changes to the package during the review process.  Normally a package has a single maintainer.  I have granted you and the submitter access.  If you cannot push and @bczech  cannot push, I suggest you active BiocCredentials accounts and add new ssh keys.

**Comment by gladkia** [comment]
> @gladkia you should now have access. On submission, we assume the person submitting is the maintainer and would be pushing changes to the package during the review process. Normally a package has a single maintainer. I have granted you and the submitter access. If you cannot push and @bczech cannot push, I suggest you active BiocCredentials accounts and add new ssh keys.

It works now. Thanks!

**Comment by gladkia** [comment]
> Hi @vjcitn and @lshep,
> 
> The error that appears: `Packages suggested but not available: 'gDRutils', 'gDRstyle', 'gDRcore'` is due to the fact that we are submitting all these packages to Bioc 3.17. Thanks in advance for the hints on how to deal with it properly.
> 
> Best, Arek

@lshep, can you please provide a hint on how to deal with this error? The `gDRstyle` package is not seen because we are trying to submit it as well (built with no errors and warnings here: https://github.com/Bioconductor/Contributions/issues/2976).

**Comment by lshep** [comment]
@gladkia You can't solve this because of the way you choose to submit them. You needed to have related packages use the AdditionalPackage but since they have all been processed as separate issues we need to proceed as such now.  It will be extra work for the reviewer to try to review all of these at once now.

**Comment by gladkia** [comment]
Got it. @vjcitn, sorry about it!

**Comment by vjcitn** [comment]
the vignette could be more descriptive of the purpose of the package.  it is not clear to me why it is a separate package.  Couldn't the functions be in gDRcore?

**Comment by vjcitn** [comment]
License says
```
GNE_LICENCE
COPYRIGHT AND LICENSE
  This software is copyright (c) by Genentech.
  This is unreleased software and should not be distributed outside of Genentech.
  All rights reserved.
```

**Comment by gladkia** [comment]
> the vignette could be more descriptive of the purpose of the package. it is not clear to me why it is a separate package. Couldn't the functions be in gDRcore?

Yes, we've moved the functions to the gDRcore recently. We will update the vignette. 
We decided to have a dedicated package for the test data that is used across gdrplatfrom (e.g. in gDRutils and gDrcore).

**Comment by gladkia** [comment]
> License says
> 
> ```
> GNE_LICENCE
> COPYRIGHT AND LICENSE
>   This software is copyright (c) by Genentech.
>   This is unreleased software and should not be distributed outside of Genentech.
>   All rights reserved.
> ```

Yes. This should be changed. Can you please provide a hint of which license should we switch to?

**Comment by vjcitn** [comment]
see http://contributions.bioconductor.org/license.html

Artistic-2.0 is typical

**Comment by gladkia** [comment]
@vjcitn done.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bczech.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gDRtestData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gDRtestData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
