### ISSUE TITLE
escheR

### ISSUE THREAD

**Issue by boyiguo1** [Bioconductor/Contributions#2988]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/boyiguo1/escheR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'escheR' Review
Thank you for submition your package to Bioconductor. The package passed check and build. It is in pretty good shape. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please condsider; Important: must be addressed.

## The DESCRIPTION file
- [ ] R version is not clear in DESCRIPTION.

## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 8 import(SpatialExperiment)
	* in line 9 import(ggplot2)
	* in line 10 import(spatialLIBD)

## R code
- [ ] Important: No `paste` in `message()`, `message`, `stop`
	* In file R/add_fill.R:
		+ at line 34 found '        stop(paste0("Please add the variable ", var, " to colData(spe)."))'
	* In file R/add_ground.R:
		+ at line 37 found '        stop(paste0("Please add the variable ", var, " to colData(spe)."))'
	* In file R/add_symbol.R:
		+ at line 36 found '        stop(paste0("Please add the variable ", var, " to colData(spe)."))'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
	* In file R/make_escheR.R:
		+ at line 58 found '    d <- as.data.frame(cbind(colData(spe), SpatialExperiment::spatialCoords(spe)), optional = TRUE)'
		+ at line 64 found '        SpatialExperiment::imgRaster('
		+ at line 86 found '                x = pxl_col_in_fullres * SpatialExperiment::scaleFactors(spe, sample_id = sampleid, image_id = image_id) - adjust$x,'
		+ at line 87 found '                y = pxl_row_in_fullres * SpatialExperiment::scaleFactors(spe, sample_id = sampleid, image_id = image_id) - adjust$y,'
- [ ] Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
	* In file R/add_fill.R:
		+ at line 59 found '    #       setNames(c(paste0("L", 1:6), "WM", "NA", "WM2"))'
- [ ] Important: Remove unused code.
	* In file R/add_fill.R:
		+ at line 31 found '    # browser()'
		+ at line 37 found '    # if(is.numeric(p$data[,var])) {'
		+ at line 38 found '    #   stop("")'
		+ at line 39 found '    #   p <- suppressMessages({p + scale_fill_continuous()})'
		+ at line 40 found '    # } else{'
		+ at line 41 found '    #   p <- suppressMessages({p + scale_fill_discrete()})'
		+ at line 42 found '    # }'
		+ at line 45 found '    # browser()'
		+ at line 54 found '    # if(!is.numeric(p$data[,var]))'
		+ at line 55 found '    #   tmp <- tmp +'
		+ at line 56 found '    #   scale_fill_manual('
		+ at line 57 found '    #     name = "",'
		+ at line 58 found '    #     values = libd_layer_colors |>'
		+ at line 59 found '    #       setNames(c(paste0("L", 1:6), "WM", "NA", "WM2"))'
		+ at line 60 found '    #   )'
		+ at line 63 found '    # tmp$scales <- tmp$scales[[-1]]'
	* In file R/make_escheR.R:
		+ at line 51 found '    ## (http://spatial.libd.org/spatialLIBD/)'
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
	* In file R/add_fill.R:
		+ at line 39 found '    #   p <- suppressMessages({p + scale_fill_continuous()})'
		+ at line 41 found '    #   p <- suppressMessages({p + scale_fill_discrete()})'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `add_fill` and `add_ground` and `add_symbol`
		+ in add_fill
			- line 1:    point_size = 2, ...) 
			- line 2:{
			- line 3:    if (!is.character(var) || length(var) != 1) {
			- line 4:        stop("The argument var must be character of length one.")
			- line 5:    }
			- line 6:    if (!var %in% colnames(p$data)) {
			- line 7:        stop(paste0("Please add the variable ", var, " to colData(spe)."))
			- line 8:    }
			- line 9:    p + geom_point(aes(fill = !!sym(var)), shape = 21, stroke = 0, 
		+ in add_ground
			- line 1:    var, stroke = 0.5, point_size = 2, ...) 
			- line 2:{
			- line 3:    if (!is.character(var) || length(var) != 1) {
			- line 4:        stop("The argument var must be character of length one.")
			- line 5:    }
			- line 6:    if (!var %in% colnames(p$data)) {
			- line 7:        stop(paste0("Please add the variable ", var, " to colData(spe)."))
			- line 8:    }
			- line 9:    p + geom_point(aes(color = !!sym(var), ), shape = 21, fill = "transparent", 
		+ in add_symbol
			- line 1:    var, size = 1, ...) 
			- line 2:{
			- line 3:    if (!is.character(var) || length(var) != 1) {
			- line 4:        stop("The argument var must be character of length one.")
			- line 5:    }
			- line 6:    if (!var %in% colnames(p$data)) {
			- line 7:        stop(paste0("Please add the variable ", var, " to colData(spe)."))
			- line 8:    }
- [ ] Note: move `theme` in function `make_escheR.SpatialExperiment` to a sub_function.
- [ ] Note: Use `dots` to pass parameters to `geom_point` in `add_symbol` function and `add_fill` function and let user to overwrite the defaults.
## Documentation
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/SRT_eg.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/SRT_eg.Rmd

**Comment by boyiguo1** [comment]
Dear @jianhong,

Thank you very much for your careful review. I have addressed all the **important** comments and most of the **notes**. The rest of the unaddressed **notes** will be considered in the next update of `escheR`.
 
 Please find the line-by-line response to your comments at https://github.com/boyiguo1/escheR/issues/4.
 
  My responses are highlighted in 
> Response: _italic font_.

Please find all changes to the `escheR` package in the recent pull request at https://github.com/boyiguo1/escheR/pull/6.

Again, thank you very much for your review. Please let me know if there is anything else I need to address for this submission.

Sincerely,
Boyi

**Comment by jianhong** [comment]
Great Job. Just update your R dependence version from current >=3.6 to >=4.3.0 will be OK for acception. This is required by Bioconductor.

Jianhong.

**Comment by boyiguo1** [comment]
@jianhong Thank you very much for your feedback!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/boyiguo1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("escheR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/escheR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
