### ISSUE TITLE
RAIDS

### ISSUE THREAD

**Issue by belleau** [Bioconductor/Contributions#2995]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/KrasnitzLab/RAIDS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by belleau** [comment]
Hi Dario,

I get the following error when I try to push changes to Bioconductor repository. Can you help with this?

git push upstream main:devel
FATAL: W any packages/RAIDS p.belleau DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is it because my user is belleau and in the message it is p.belleau ?
Thank you very much,
Best,
Pascal

**Comment by belleau** [comment]
Hi @DarioS ,
Can you help me with this?

git push upstream main:devel
FATAL: W any packages/RAIDS p.belleau DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is it because my user is belleau and in the message it is p.belleau ?
Thank you very much,
Best,
Pascal

**Comment by DarioS** [comment]
I am unsure if that is the reason for the push failure but you can check your username and package access at [BiocCredentials](https://git.bioconductor.org/BiocCredentials/login/).

Also, note that Bioconductor packages are expected to have camelCase style [variable naming](https://contributions.bioconductor.org/r-code.html#variable-names) and [function naming](https://contributions.bioconductor.org/r-code.html#rcode-function-names) but your package uses a mix of different styles e.g. `pedFile`, `PATHGENO`,  `batch.v`. Please harmonise to Bioconductor style. Your package will also need to be redesigned to leverage databases already in Bioconductor rather than relying on various supplementary files from your research group's server. I think that [MafDb.1Kgenomes.phase3.GRCh38](http://bioconductor.org/packages/release/data/annotation/html/MafDb.1Kgenomes.phase3.GRCh38.html) would have the information needed.

You also depend on external software installation and execution.
> This step requires installation of the external code [snp-pileup](https://github.com/mskcc/facets/tree/master/inst/extcode) which is associated to the facets package (Shen and Seshan 2016). Given a VCF file containing SNP locations, [snp-pileup](https://github.com/mskcc/facets/tree/master/inst/extcode) application outputs, for each location, the read counts for the reference and alternative nucleotides from the BAM input.

This needs to be replaced by `pileup` from [Rsamtools](https://bioconductor.org/packages/Rsamtools).

**Comment by belleau** [comment]
Hi Dario,

In the credential, the user is belleau and the SSH-key is there but I don’t see the package in the “Which packages do I have access to?” section (just my previous package is there). The key is also in my GitHub.

Pascal

**Comment by lshep** [comment]
Please try again I think the push error should now be fixed.

**Comment by adeschen** [comment]
The push error has been fixed. Thanks

**Comment by belleau** [comment]
Hi Dario,

We have modified the package following your comments:

1. The variable naming and function naming have been harmonized to Bioconductor style.

2. The package doesn't depend on snp-pileup anymore. Generic pileup files, generated by RSamtools or any other software, can be used as input.

However, the package still offers to upload pre-formated supplementary files related to 1000 Genomes (1KG) data. Those files are offered to ease the use of the package as the genotype information for the 1000 Genomes is not available in any Bioconductor package. Our vignette contains a vignette explaining how to generate your own reference dataset. However, those steps are time and space-consuming. As an example, to regenerate the 1000 Genomes reference dataset, all 1KG VCF genotype files would have to be downloaded.

Best Regards,
Pascal

**Comment by DarioS** [comment]
Thanks for the high-level changes. I have further reviewed the package in great detail.

- Some of the documentation is incomplete. For example,

```r
#' @title TODO
#'
#' @description TODO
#'
#' @param snp.pos a \code{data.frame} containing the genotype information for a SNV dataset. TODO
```

Please provide a completed R package for review. Documentation completeness is important.

- There are unnecessary [for](url) loops in some places. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) for coding requirements. For example,

```r
chrInfo <- integer(25L)
for(i in seq_len(22L)){ chrInfo[i] <- length(Hsapiens[[paste0("chr", i)]])}
chrInfo[23] <- length(Hsapiens[["chrX"]])
chrInfo[24] <- length(Hsapiens[["chrY"]])
chrInfo[25] <- length(Hsapiens[["chrM"]])
```

  You could have simply done

```r
> seqlengths(Hsapiens)[1:25] # Avoids unnecessary creation of the chrInfo vector one element at a time.
     chr1      chr2      chr3      chr4      chr5      chr6      chr7      chr8      chr9     chr10     chr11     chr12 
248956422 242193529 198295559 190214555 181538259 170805979 159345973 145138636 138394717 133797422 135086622 133275309 
    chr13     chr14     chr15     chr16     chr17     chr18     chr19     chr20     chr21     chr22      chrX      chrY 
114364328 107043718 101991189  90338345  83257441  80373285  58617616  64444167  46709983  50818468 156040895  57227415 
     chrM 
    16569
```

Please change all such unnecessary `for` loops into `vapply` or `lapply` loops. `for` might in **some** cases be more appropriate. 

- The package seems hard-coded to hg38 reference sequence. Sadly, some international cancer consortiums use other reference genomes. I.C.G.C. [Pan-Cancer Analysis of Whole Genomes](https://www.nature.com/articles/s41586-020-1969-6) (P.C.A.W.G.) is an example.

  > To generate a consistent set of somatic mutation calls that could be used for cross-tumour analyses, we analysed all 6,835 samples using a uniform set of algorithms for alignment, variant calling and quality control. We used the BWA-MEM algorithm to align each tumour and normal sample to human reference build hs37d5 (as used in the 1000 Genomes Project).

  Also, the ancestry information can only take 1000 Genomes data as input, it seems.

![image](https://github.com/Bioconductor/Contributions/assets/631218/46a4177f-bbfa-4b45-9d06-f8205c634900)

  Please make the package generalisable to more than a single resource. 

- The package may attempt to modify a computer's system directory which might be read-only.

```r
> dataDirGenotyping <- file.path(system.file("extdata", package="RAIDS"), "demoAddGenotype")
> dataDirGenotyping
[1] "C:/Program Files/R/R-4.3.0/library/RAIDS/extdata/demoAddGenotype"
> dir.create(dataDirGenotyping, recursive=FALSE, mode="0777")
Warning message:
In dir.create(dataDirGenotyping, recursive = FALSE, mode = "0777") :
  cannot create dir 'C:\Program Files\R\R-4.3.0\library\RAIDS\extdata\demoAddGenotype', reason 'Permission denied'
```

  Please design the package to robustly work on a multi-user shared system.

- Examples sometimes load packges in Suggests using `library`. For example,

```r
#' @examples
#'
#' ## Required package
#' library(withr)
```

These should be conditionally loaded using `requireNamespace`, not `library`. See [Suggested Packages](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages) instructions.

- Some sections of the vignette are Linux-specific. Bioconductor packages [should be designed for all operating systems](https://www.bioconductor.org/help/faq/#install-packages-faq).

> **Sub-Step 2.1 Create a directory containing the 3 required reference files**
> The 3 required reference files may be downloaded:
> 
> ####################################
> ## The 1KG GDS file
> ####################################
> wget https://labshare.cshl.edu/shares/krasnitzlab/aicsPaper/matGeno1000g.gds
> 
> ####################################
> ## The 1KG SNV Annotation GDS file
> ####################################
> wget https://labshare.cshl.edu/shares/krasnitzlab/aicsPaper/matAnnot1000g.gds
> 
> ####################################
> ## The 1KG SNV Retained VCF file
> ####################################
> wget https://labshare.cshl.edu/shares/krasnitzlab/aicsPaper/snvSel0.01.vcf.gz

  There are also other commands in the vignette that might write to a folder that could be read-only.

```r
dataDir <- system.file("extdata", package="RAIDS")
demoPEDFile <- file.path(dataDir, "Demo_PED.RDS")
```

- Sub-step 2.2 and 2.3 are mandatory but there is no code to do them, just a flowchart illustration.

- The F.A.Q. at the end of the vignette recommends command-line tool `snp-pileup` which has [installation instructions](https://github.com/mskcc/facets/tree/master/inst/extcode)

> This code can be compiled using 
>      `g++ -std=c++11 snp-pileup.cpp -lhts -o snp-pileup`

Bioconductor packages need to seamlessly cross-platform and, similar to the GDS download instructions, these are also not.

**Comment by lshep** [comment]
@belleau may we expect updates soon?  We like to see changes in a 2-3 week time frame to keep reviews moving forward.

**Comment by belleau** [comment]
We will submit an update soon.

Thank you,

Best,

Pascal
________________________________
De : lshep ***@***.***>
Envoyé : 28 juillet 2023 10:11
À : Bioconductor/Contributions ***@***.***>
Cc : Pascal Belleau ***@***.***>; Mention ***@***.***>
Objet : Re: [Bioconductor/Contributions] RAIDS (Issue #2995)


@belleau<https://github.com/belleau> may we expect updates soon? We like to see changes in a 2-3 week time frame to keep reviews moving forward.

**Comment by belleau** [comment]
Dear [@DarioS](https://github.com/DarioS) ,

We thank you for the thoughtful comments and, in response, have revised the code as follows.

- **Some of the documentation is incomplete.** 

We have completed all the documentation.


- **There are unnecessary [for](https://github.com/Bioconductor/Contributions/issues/url) loops in some places. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) for coding requirements.** 

We have vectorized most of the **for** loops. However, the  **for** loops where calculation of one value depends on a previous value have been kept. 


- **The package seems hard-coded to hg38 reference sequence. Sadly, some international cancer consortiums use other reference genomes. I.C.G.C. [Pan-Cancer Analysis of Whole Genomes](https://www.nature.com/articles/s41586-020-1969-6) (P.C.A.W.G.) is an example.**

We revised the documentation in order to clarify that the package can handle any reference genome sequence provided by the user and is not hard-coded to the hg38 reference. Specifically, we have updated all illustrations to refer to the “Formatted Reference Data'' instead of the “Formatted 1KG Data”.  As a courtesy, we are providing the 1KG formatted reference files used in the Cancer Research publication which introduces the RAIDS method. The parameter names related to the reference files, in public functions, have also been modified to more generic terminology (ex: gdsReference, fileReferenceGDS, fileReferenceAnnotGDS).

A vignette describing the content of the Reference GDS files has also been created. This vignette will help users create their own reference GDS files, as needed.


- **The package may attempt to modify a computer's system directory which might be read-only.**

The examples in RAIDS documentation have been modified to only create files in the current directory after validating that the directory is in writable mode and that the files do not already exist. After usage, all temporary files are deleted.


- **Examples sometimes load packages in Suggests using library.** 

All examples that used the *library()* method with suggested libraries have been modified to use the *requireNamespace()* method instead, as described in [Suggested-packages](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages) document.


- **Some sections of the vignette are Linux-specific. Bioconductor packages [should be designed for all operating systems](https://www.bioconductor.org/help/faq/#install-packages-faq). There are also other commands in the vignette that might write to a folder that could be read-only.**

We have removed all Linux-specific sections from the vignette. The vignette is now applicable across all operating systems. In addition, the current directory is used for writing by the code in the vignette, only if that directory has a write permission. The existing files in the current directory are also protected against overwriting.


- **Sub-step 2.2 and 2.3 are mandatory but there is no code to do them, just a flowchart illustration.**

The sub-steps 2.2 and 2.3 have been removed. The associated illustrations have been updated.


- **The F.A.Q. at the end of the vignette recommends command-line tool snp-pileup which has [installation instructions](https://github.com/mskcc/facets/tree/master/inst/extcode). Bioconductor packages need to be designed for all operating systems.**

The F.A.Q. section, which included the snp-pileup information, has been removed. The vignette is now applicable across all operating systems.

Best,

Astrid and Pascal

**Comment by adeschen** [comment]
Hi @DarioS, @vjcitn,

Although @bioc-issue-bot did not remove the "ERROR" label, there are no errors in the current checks.

Best,
Astrid

**Comment by DarioS** [comment]
Thanks for the update. I notice some more issues in the latest version.

- `Create_Reference_GDS_File.Rmd` doesn't actually explain how to _create_ the GDS files. It specifies what files are needed:

> Two different files are generated from a reference dataset:
> - The Population Reference GDS File
> - The Population Reference SNV Annotation GDS file

  and what their structure is:

> ```r
> pathReference <- system.file("extdata/example/", package="RAIDS")
> fileReferenceGDS <- file.path(pathReference, "gdsRef", "ex1kg.gds")
> gdsRef <- snpgdsOpen(fileReferenceGDS)
> ## Show the file format
> print(gdsRef)
> ```

However, there are no instructions for creating a new one. Please instruct the user how to do it.

- I had an incorrect idea about what snp-pileup does. I was erroneously thinking of samtools `mpileup`. snp-pileup simply calculates the number of reads supporting the reference sequence and the variant sequence for each variant so Rsamtools advice is not relevant. RAIDS should improve its interoperability with Biocondctor by using [VariantAnnotation](https://bioconductor.org/packages/release/bioc/html/VariantAnnotation.html) to import VCF files, which is the file format used by many cancer sequencing projects such as ICGC and TCGA, VCF files have `AD` element in `GT` field, which stores these counts. For example, if GT is 0/1 and AD is 14,15, it means that 14 reads support reference and 15 reads support the variant. There is simply no need for creating pileups on disk if the AD can directly be extracted from the VCF file which already exists. Please remove redundant pileups generation step requiring extra tool.

- The documentation still has unnecessary hard-coded values which could be gotten from other Bioconductor packages, as I showed in my previous response.

```r
chrInfo <- c(248956422L, 242193529L, 198295559L, 190214555L,
 181538259L, 170805979L, 159345973L, 145138636L, 138394717L, 133797422L,
 135086622L, 133275309L, 114364328L, 107043718L, 101991189L, 90338345L,
 83257441L,  80373285L,  58617616L,  64444167L,  46709983L, 50818468L,
 156040895L, 57227415L,  16569L)
```

The hard-coding of chromosome lengths instead of getting them from `Hsapiens` is widespread.

![image](https://github.com/Bioconductor/Contributions/assets/631218/8b6ccdd4-4ec4-437e-adde-f82c8d1636ac)

- The example database file used for the vignette takes 12 hours to download to Australian university's Debian server.

![image](https://github.com/Bioconductor/Contributions/assets/631218/af9cae1c-2edd-471e-8e5b-a5413cd91d80)

Example data sets in other Bioconductor packages are often small subsets of real data. Please consider a different example and also refer to [Other Data](https://contributions.bioconductor.org/data.html?q=tempdir#other-data) of Developer's Guide.

>  Downloads of files and external data from the web should be avoided.

 - Intermediate files must not be placed in `getwd()` but in `tempdir()`. Also refer to [Other Data](https://contributions.bioconductor.org/data.html?q=tempdir#other-data) of Developer's Guide.

>  It is not allowed to download or write any files to a users home directory, working directory, or installed package directory.

Thanks for updating the package. Continue to make the package more self-contained with better Bioconductor interaction.

**Comment by adeschen** [comment]
Hi @DarioS,

We thank you for the thoughtful comments.

Concerning the following point:

- The documentation still has unnecessary hard-coded values which could be gotten from other Bioconductor packages, as I showed in my previous response.

We do no currently import the _GenomeInfoDb_ nor the _BSgenome.Hsapiens.UCSC.hg38::Hsapiens_ libraries as those are not required in the code. Should we add those into the _Depends_ section and change code to this (in the examples and in the vignette):

`chrInfo <- GenomeInfoDb::seqlengths(BSgenome.Hsapiens.UCSC.hg38::Hsapiens)[1:25]`

Best Regards,
Astrid

**Comment by DarioS** [comment]
No, in Suggests and `requireNamespace` used to check for availability. Please see [Depends, Imports, Suggests, Enhances](https://contributions.bioconductor.org/description.html?q=Suggests#depends-imports-suggests-enhances).

Also, there's one other issue which I overlooked yesterday. Note that [each data object needs its own manual page](https://contributions.bioconductor.org/docs.html?q=data#data-man) explaining its origin and structure. Currently, there are over 100 data objects in the examples folder which is far too excessive. You will want to be much more selective about what you put in there. Please also refer to [Package Reviewer Checklist](https://contributions.bioconductor.org/docs/package-review-checklist.md). Something which needs clarification is how the example data files were created. They are much smaller than the full 15 GB file. For example, you could state that only one chromosome was used instead of the genome, if that's the case, but origin of each data file is essential.

> Exported data has correct format, is compressed and documented. Included data not too large.

Large also refers to the number of files, not just the size in megabytes. This should be worded better in the checklist.

**Comment by belleau** [comment]
Dear [@DarioS](https://github.com/DarioS) ,

We thank you for the thoughtful comments and, in response, have revised the code as follows.

- **Create_Reference_GDS_File.Rmd doesn't actually explain how to create the GDS files. It specifies what files are needed: the Population Reference GDS File and the Population Reference SNV Annotation GDS file. However, there are no instructions for creating a new one. Please instruct the user how to do it.**

We have added a code section in the _Create_Reference_GDS_File_ vignette that shows how to generate a **Population Reference GDS** file. We also have added a second code section to show how to generate a **Population Reference SNV Annotation GDS** file.

- **RAIDS should improve its interoperability with Bioconductor by using [VariantAnnotation](https://bioconductor.org/packages/release/bioc/html/VariantAnnotation.html) to import VCF files, which is the file format used by many cancer sequencing projects such as ICGC and TCGA.**

We have added a new function called _readSNVVCF()_ that is able to parse a VCF file as an alternative to snp-pileup or the generic version. The variants in the VCF must be germline variants and should include the genotype of the wild-type homozygous at the selected positions in the reference.

- **The documentation still has unnecessary hard-coded values which could be gotten from other Bioconductor packages, as I showed in my previous response. The hard-coding of chromosome lengths instead of getting them from Hsapiens is widespread.**

We have removed the hard-coding of chromosome lengths and are now using 
`chrInfo <- GenomeInfoDb::seqlengths(BSgenome.Hsapiens.UCSC.hg38::Hsapiens)[1:25]`
in the documentation. 

- **The example database file used for the vignette takes 12 hours to download to Australian university's Debian server.** 

We have modified the vignette to clarify that the download of the **1KG Reference GDS** file is not required to run the examples in the vignette. We added text describing the two demo population GDS files (called _ex1_good_small_1KG.gds_ and _ex1_good_small_1KG_Annot.gds_) that are included in the package and that are used in the examples. 

- **Intermediate files must not be placed in getwd() but in tempdir(). Also refer to [Other Data](https://contributions.bioconductor.org/data.html?q=tempdir#other-data) of Developer's Guide.**

The intermediate files are now all placed in _tempdir()_.

- **Note that [each data object needs its own manual page](https://contributions.bioconductor.org/docs.html?q=data#data-man) explaining its origin and structure.**

We have added a **README** file that describes the demo files present in the _‘inst/extdata’_ directory.  When possible, we have added R script files in the same directory that enable the users to recreate some of the demo files present in the directory.  Moreover, we also have deleted some redundant files. 

In addition, some of the files have been removed and transformed into loadable data objects, through _data()_ function, that are part of the package. Those 7 fully documented and available objects are: _pedSynthetic_, _matKNNSynthetic_, _snpPositionDemo_, _demoPCA1KG_, _demoPCASyntheticProfiles_, _demoKnownSuperPop1KG_ and  _demoPedigreeEx1_ objects.

Best Regards,

Astrid and Pascal

**Comment by DarioS** [comment]
The outstanding items have been satisfactorily addressed.

**Comment by belleau** [comment]
Dear @DarioS ,

Great!,
Many thanks

Astrid and Pascal

**Comment by lshep** [comment]
I currently cannot process this package because of the inclusion of `BiocViews` in the `biocViews` of the DESCRIPTION. Please remove `BiocViews` as that is not an acceptable term.  Thank you

**Comment by lshep** [comment]
Thank you. I'll look at processing later this afternoon.

**Comment by belleau** [comment]
Hello @Ishep

I got the message when I merged:
remote: Error: Please bump the version again and push.
remote: 
remote: The build did not start as expected. If the issue persists,
remote: please reach out at bioc-devel@r-project.org or post on the
remote: Github issue where your package is being reviewed.
remote: 
remote: 400 Client Error: Bad Request for url: https://issues.bioconductor.org/start_build
remote: 
To git.bioconductor.org:packages/RAIDS.git
   1749bf72..07e3ce4b  main -> devel

Is it ok or I have something to do?

Thank you,

Best,

Pascal

**Comment by lshep** [comment]
Yes that is okay. Since your package was already marked as accepted we turn off auto builds.  Its an expected message.  I check the changes were pushed up correct onto git.bioconductor.org and you should be all set.  Cheers

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/belleau.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RAIDS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RAIDS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
