### ISSUE TITLE
gdrplatform release [third package: gDRutils]

### ISSUE THREAD

**Issue by darsoo** [Bioconductor/Contributions#2996]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gdrplatform/gDRutils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
they are all in error state.

**Comment by gladkia** [comment]
Hi,

Yes,  This is because we submitted all packages at once instead of
using the 'AdditionalPackages' tag. See
https://github.com/Bioconductor/Contributions/issues/2987#issuecomment-1513045781.
Sorry about that.

Best,
Arek

**Comment by lshep** [comment]
This seems to have a connection error rather than a package not found that could be investigated?

**Comment by gladkia** [comment]
> This seems to have a connection error rather than a package not found that could be investigated?

Yes, this is a connection error resulting from the 'package not found' problem (no gDRtestData available). See https://github.com/gdrplatform/gDRutils/blob/master/vignettes/gDRutils.Rmd#L35 and https://github.com/gdrplatform/gDRutils/blob/master/R/utils.R#L383).

**Comment by vjcitn** [comment]
please read the vignette after compiling to HTML.  it has many screenfuls of useless information.  please trim the prints.  the vignette should guide the reader to an understanding of the package.

**Comment by gladkia** [comment]
@vjcitn fixed.

**Comment by vjcitn** [comment]
my current checkouts yield
```
* checking package dependencies ... ERROR
Package required and available but unsuitable version: 'gDRtestData'
```

**Comment by vjcitn** [comment]
ues BiocStyle to format the vignettes throughout your platform.  when that is done I will accept.

**Comment by gladkia** [comment]
> use BiocStyle to format the vignettes throughout your platform. when that is done I will accept.

@vjcitn - done for: 
-  https://github.com/gdrplatform/gDRutils/pull/74
- https://github.com/gdrplatform/gDRcore/pull/87
- https://github.com/gdrplatform/gDR/pull/34
- https://github.com/gdrplatform/gDRimport/pull/53 
- https://github.com/gdrplatform/gDRtestData/pull/44. 

No changes were required for gDRstyle (BiocStyle is currently used: [link](https://github.com/gdrplatform/gDRstyle/blob/main/vignettes/gDRstyle.Rmd#L9)).

All 'devel' branches have been synced with default branches (from github.com/gdrplatform).

**Comment by gladkia** [comment]
@vjcitn, thanks in advance for having a  look into the latest versions of gDRtestData, gDRutils, gDRimport, gDRcore, and gDR packages :)!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/darsoo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gDRutils")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gDRutils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
