### ISSUE TITLE
RITANdata

### ISSUE THREAD

**Issue by MTZimmer** [Bioconductor/Contributions#300]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MTZimmer/RITANdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by MTZimmer** [comment]
AdditionalPackage: https://github.com/MTZimmer/RITAN

**Comment by hpages** [comment]
Hi Michael,

Thanks for your submission.

1. Please also submit the RITAN software package (in this same issue). There is not much point for us to add RITANdata to Bioconductor if it's not accompanied by the RITAN package.

2. `R CMD build RITANdata` is not building the HTML vignette because of 2 problems:
   a) You already have a prebuilt HTML version of the vignette in the inst/doc/ folder. It needs to be removed.
   b) You also need to add the following line
    ```
       VignetteBuilder: knitr
    ```
     to the DESCRIPTION file of the package.

    With these changes `R CMD build RITANdata` will build the HTML vignette and include it in the resulting source package tarball. This is the standard mechanism for producing a source tarball that contains an HTML vignette that is guaranteed to be in sync with the Rmd vignette.

3. Please remove the last line of the DESCRIPTION file:
    ```
    Packaged: 2017-02-01 02:26:00 UTC
    ```
    This line will be automatically added to the source package tarball when we run `R CMD build` on the package (and it will reflect the real packaging time).

4. The vignette doesn't say anything about the `cached_coding_genes` data set. Is this intended? Also the man page for this data set says:
    ```
    gene symbols for protein coding genes - cached for use in vignettes -
    ```
    but I can't figure out where it's used in the vignette.

5. The man pages for the data sets should explain how these data sets were generated e.g. where the data is coming from, how it was curated, etc... Ideally, and for the sake of reproducibility, the code used to generate them should be made available.

Regards,
H.

**Comment by MTZimmer** [comment]
Dear @hpages ,

I believe I have made all changes that you itemized last week. The most recent versions of both RITANdata and RITAN have passed the buildreport without errors or warnings. Please let me know if you find any additional items that need adjustment, or if you have any further questions.

Sincerely,

**Comment by hpages** [comment]
Thanks Michael,

Packages (software and data) look good and I'm marking them as accepted. There are a few minor issues (see below). However, because we are very short of time for the release, I'm only listing them here as an FYI in the hope that you'll be able to address them at some point.

Thanks for you contribution to the project,
H.

6. You need to import the following packages: graphics, stats, utils.

7. Calling `readSIF()`, `readGMT()`, or `writeGMT()` with no argument currently displays a message explaining how to use the function but they should raise an error instead (and the current message should be the message displayed by the error).

8. The `readSIF()`, `readGMT()`, and `writeGMT()` functions need to have real examples in their man pages.

9. There are several problems with the man pages of the vac1.* and vac2.* data sets:
  - The *.Rd files should contain `\docType{data}`
  - The `\description` sections should not contain code showing how to use the data set. Instead they should describe the data set. The code they contain should be moved to an `\examples` section.
  - Since you are using `LazyData: TRUE` in the DESCRIPTION file, you don't need to load the data sets with `data()` before you can use them. You can use them immediately.

**Comment by MTZimmer** [comment]
Dear Hpages and BioC Moderators,

With the BioC version 3.5 builds, RITAN builds now return an immediate error that RITANdata cannot be found. Were both packages accepted? If so, is there an additional step needed to enable access to packages new to the most recent release?

Please let me know if there's any additional information I can provide.

Also, due to family events, I won't be able to immediately, but I willupdate RITAN with the additional points out have outlined above. 

Sincerely,
