### ISSUE TITLE
marinerData

### ISSUE THREAD

**Issue by EricSDavis** [Bioconductor/Contributions#3002]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EricSDavis/marinerData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Hello  It looks like the data was never officially added to the ExperimentHub.  I am one of the maintainers of the experimenthub data base would you like me to proceed with the addition?  It looks like you are hosting the data on zenodo, is that correct?

**Comment by EricSDavis** [comment]
> Hello It looks like the data was never officially added to the ExperimentHub. I am one of the maintainers of the experimenthub data base would you like me to proceed with the addition? It looks like you are hosting the data on zenodo, is that correct?

Yes please, that is correct!

**Comment by lshep** [comment]
May I suggest a slight change in the metadata.csv file where the Location_Prefix is `https://zenodo.org/`  and the RDataPath the rest of the unique identifier (ie.  `record/7786502/files/LEUK_HEK_PJA27_inter_30.hic?download=1`  and likewise for the second file?)

**Comment by EricSDavis** [comment]
Sounds good to me, should I make that change and push it?

Another question: These are actually `.hic` files, but I've listed them as "TXT" files since there is no valid `SourceType` for `.hic`. Is this appropriate or should I list them as another file type?

**Comment by lshep** [comment]
I can add `HIC` as a valid source type. We just haven't had any submitted to this point but it seems reasonable to add.  If you would like to make both of those changes and push up.  I will then use the corrected metadata file to add the files to the database so they are discoverable and can let you know when they are available

**Comment by EricSDavis** [comment]
Great, thanks! I'll push the `HIC` change momentarily.

**Comment by lshep** [comment]
The data is now available in devel ExperimentHub 

```
> eh = ExperimentHub()
snapshotDate(): 2023-04-04
> query(eh, "marinerData")
ExperimentHub with 2 records
# snapshotDate(): 2023-04-04
# $dataprovider: Phanstiel Lab
# $species: Homo sapiens
# $rdataclass: HIC
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH8088"]]' 

           title                      
  EH8088 | LEUK_HEK_PJA27_inter_30.hic
  EH8089 | LEUK_HEK_PJA30_inter_30.hic

```

On quick glance of the package, please make sure to update the inst/script to describe how the data object that are on zenodo were created and any relevant source/reference data for them.  Please also include at least a man page for the package so that `?marinerData` shows how to get started. 

I'll do a further review once the package can build and check  without ERROR.  Please see the other ERROR's in the report given above.

**Comment by EricSDavis** [comment]
Thank you! I'll add that documentation. I can see the resources on the devel `ExperimentHub` but when I try to access the resources I get a 404 error:

```r
> library(ExperimentHub)
> eh = ExperimentHub()
> eh[["EH8088"]]
snapshotDate(): 2023-04-04
see ?marinerData and browseVignettes('marinerData') for documentation
downloading 1 resources
retrieving 1 resource
Downloading: 2.9 kB     
Error: failed to load resource
  name: EH8088
  title: LEUK_HEK_PJA27_inter_30.hic
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: ‘https://experimenthub.bioconductor.org/fetch/8147’
  local file path: ‘/home/rstudio/.cache/R/ExperimentHub/12c32b690d8_8147’
  reason: Not Found (HTTP 404). 
2: bfcadd() failed; resource removed
  rid: BFC5
  fpath: ‘https://experimenthub.bioconductor.org/fetch/8147’
  reason: download failed 
3: download failed
  hub path: ‘https://experimenthub.bioconductor.org/fetch/8147’
  cache resource: ‘EH8088 : 8147’
  reason: bfcadd() failed; see warnings()
  ```
I'm running this code on the bioconductor/bioconductor_docker:devel image. Do you have any suggestions for how I can access these?

**Comment by lshep** [comment]
hmm... I also get that
```
> library(httr)
> httr::HEAD("https://experimenthub.bioconductor.org/fetch/8147")
Response [https://zenodo.org/record/7786502/files/LEUK_HEK_PJA27_inter_30.hic%3Fdownload%3D1]
  Date: 2023-04-04 14:03
  Status: 404
  Content-Type: text/html; charset=utf-8

```
The resources are publicly available ? Could this be helpful at all? is there an encoding?  https://stat.ethz.ch/pipermail/bioc-devel/2023-March/019565.html

**Comment by lshep** [comment]
Looking at the download path --  I don't think yo need the `?download=1` in the RDataPath for the download  
```
> library(httr)
> httr::HEAD("https://zenodo.org/record/7786502/files/LEUK_HEK_PJA27_inter_30.hic")
Response [https://zenodo.org/record/7786502/files/LEUK_HEK_PJA27_inter_30.hic]
  Date: 2023-04-04 14:07
  Status: 200
  Content-Type: application/octet-stream
<EMPTY BODY>

```
I can update in the database and also please make the change in the metadata.csv file for consistency.

**Comment by EricSDavis** [comment]
Ahh I see! I'll make that change in the `metadata.csv` along with something for `?marinerData` and push those.

**Comment by lshep** [comment]
I should have time to update the database in the next 30 min or so, so maybe wait until the change is done so it can register and get a more accurate report?

**Comment by lshep** [comment]
Should be all set now

**Comment by lshep** [comment]
Just talked to some members on the team who decided to update R; I'll remind them to post about it next time. This should be resolved soon. Sorry for the inconvenience

**Comment by EricSDavis** [comment]
AdditionalPackage: https://github.com/EricSDavis/mariner

**Comment by lshep** [comment]
It doesn't seem like the mariner package is complete or ready for processing.   

There is no applicable vignette. A requirement of all Biconductor packages is a vignette with active running code and description of how to run the package, along with justification for submission to Bioconductor and if applicable comparison to existing packages.

**Comment by EricSDavis** [comment]
@lshep 
I will update the "Introduction to mariner" vignette to give an overview and quick-start code for using the package. I'll also add some more detailed vignettes and workflows after the package builds successfully on the Bioc git server.

Several examples (and the vignettes I'm developing) use the `.hic` files that are now located in `marinerData`. How would you suggest incorporating `marinerData` so that the packages still builds correctly? Should I add `marinerData` to `Suggests` and use the development version of ExperimentHub?

**Comment by lshep** [comment]
Please add a vignette before we proceed. We will not add it to a review queue until it passes a pre-check which includes having a vignette. 

Yes you can now suggest the data package in mariner and use ExpeirmentHub code to download the data and use the data in your package.

**Comment by EricSDavis** [comment]
@lshep 
The intro vignette is now updated! (https://github.com/EricSDavis/mariner/blob/ba67aed730acdd1d10dfb8c4b125b775d4785680/vignettes/introduction_to_mariner.Rmd#L1-L691)

My GitHub Actions workflows which do an R CMD check, BioC check, and pkgdown build seem to fail because they can't find `marinerData` to build the vignette (despite being listed in Suggests). Do you know how I can get these to find `marinerData`? Locally I install the development version of `ExperimentHub` and install `marinerData` via GitHub which seems to work. Thanks!

**Comment by lshep** [comment]
I cannot process your additional package until you remove the large files from the package 
```
Error in .precheck_filesize(wd) : files larger than 5Mb:
  /inst/extdata/test_hic/LEUK_HEK_PJA27_inter_30.hic
  /inst/extdata/test_hic/LEUK_HEK_PJA30_inter_30.hic

```

**Comment by EricSDavis** [comment]
> I cannot process your additional package until you remove the large files from the package
> 
> ```
> Error in .precheck_filesize(wd) : files larger than 5Mb:
>   /inst/extdata/test_hic/LEUK_HEK_PJA27_inter_30.hic
>   /inst/extdata/test_hic/LEUK_HEK_PJA30_inter_30.hic
> ```

I've removed these files from the repo and cleaned the git repo history. If there are any remaining .git objects that cause issues please let me know. I'd like to avoid re-initializing the repo and losing the history, but can if necessary.

**Comment by EricSDavis** [comment]
@lshep 
I've added 10 additional datasets (small .txt files) to `marinerData` to try and reduce the `mariner` package size. Could you please add these resources to `ExperimentHub` when you have a chance?

**Comment by lshep** [comment]
@EricSDavis  I need there to be metadata entries either in the existing metadata.csv or an additional `.csv` file name of your choice but formatted for ExperimentHub resources.

**Comment by EricSDavis** [comment]
> @EricSDavis I need there to be metadata entries either in the existing metadata.csv or an additional `.csv` file name of your choice but formatted for ExperimentHub resources.

Ahh these changes were on my GitHub repo and weren't pushed to the Bioc git server. Apologies, they should be on there now! Thanks!

**Comment by lshep** [comment]
The data has been added.

**Comment by EricSDavis** [comment]
It looks like accessing the cached ExperimentHub files for examples is significantly slowing down the R CMD Check and leading to this timeout. After downloading the files it should be pretty quick to reference the file paths, but sometimes it can take minutes to return a file path. Before moving these resources to the ExperimentHub data package, everything built quickly. Any suggestions on how to move forward?

**Comment by lshep** [comment]
> It looks like accessing the cached ExperimentHub files for examples is significantly slowing down the R CMD Check and leading to this timeout. After downloading the files it should be pretty quick to reference the file paths, but sometimes it can take minutes to return a file path. Before moving these resources to the ExperimentHub data package, everything built quickly. Any suggestions on how to move forward?

It looks like this has been resolved?  After the first instance its cached and faster correct?

**Comment by lshep** [comment]
Are the packages ready for review or are you still making changes?

**Comment by EricSDavis** [comment]
They are ready for review! The package seems to be building quicker today, still unsure why it took so long yesterday but it was consistent problem both in the bioconductor_docker:devel image and in the build system.

**Comment by lshep** [comment]
Everything is looking very nice. A few minor comments for each package: 

**marinerData**

- [ ] `inst/scripts` Please update `make-data.R` with information on how the data that you provide through the ExperimentHub were created and any relevant source/licensing information. It looks like you  might have included this in man/vignette but for consistency can you repeat it in this file. 

- [ ] Please remove testthat or put it relevant, not fake test.   `expect_true(TRUE)` does not test anything. We would rather have the warning of no tests than not have relevant tests for the sake of removing the warning. 


--------------------------------------------------------------------------

**mariner**

**general comment**

- [ ] We generally encourage removing any non standard files that should not be shared with users from inclusion in git; namely `pkgdown_yml`. Generally we advise to have these on a different branch than the one uploaded to
  git.bioconductor.org

**README**

- [ ] Please also include Bioconductor installation instructions.

**man**

- [ ] Please have a package level man page so information is displayed if a user does `?mariner`

**vignette**

- [ ] Please include a Bioconductor installation section.

**Comment by EricSDavis** [comment]
> Everything is looking very nice. A few minor comments for each package:
> 
> **marinerData**
> 
> * [x]  `inst/scripts` Please update `make-data.R` with information on how the data that you provide through the ExperimentHub were created and any relevant source/licensing information. It looks like you  might have included this in man/vignette but for consistency can you repeat it in this file.
> * [x]  Please remove testthat or put it relevant, not fake test.   `expect_true(TRUE)` does not test anything. We would rather have the warning of no tests than not have relevant tests for the sake of removing the warning.
> 
> **mariner**
> 
> **general comment**
> 
> * [ ]  We generally encourage removing any non standard files that should not be shared with users from inclusion in git; namely `pkgdown_yml`. Generally we advise to have these on a different branch than the one uploaded to
>   git.bioconductor.org
> 
> **README**
> 
> * [x]  Please also include Bioconductor installation instructions.
> 
> **man**
> 
> * [x]  Please have a package level man page so information is displayed if a user does `?mariner`
> 
> **vignette**
> 
> * [x]  Please include a Bioconductor installation section.

Thank you for the review! These changes have been made and pushed. If possible, could I keep the `_pkgdown.yml` file? Every Bioconductor package that I've seen with a pkgdown site has this file on the branch pushed to git.bioconductor.org (for example, `plyranges`, `nullranges`, `plotgardener` all contain this file when cloned from the Bioconductor git server).

**Comment by lshep** [comment]
since its already been committed yes I suppose we can make this exception but please in any future submissions try to keep it on a separate branch. The reasoning is also that if Bioconductor every decided to take advantage of such configurations, we then would have to worry about conflicting existing. Since this is hypothetical in nature right now we can make the exception.  Cheers

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/EricSDavis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("marinerData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/marinerData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/EricSDavis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mariner")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mariner

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
