### ISSUE TITLE
concordexR

### ISSUE THREAD

**Issue by kayla-jackson** [Bioconductor/Contributions#3006]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pachterlab/concordexR/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by kayla-jackson** [comment]
Hi @LiNk-NY,

I'm hoping to get a bit of help with the errors from BiocCheck.  It seems that BiocCheck failed with the following error: 

`Error in loadNamespace(x) : there is no package called BiocFileCache` 

The error on the first build suggested that I subscribe to bioc-devel mailing list, and the only changes between the first and second builds were to the `Version:` field in the `DESCRIPTION` file. I haven't be able to reproduce this error locally so I'm not sure if there is a problem I can address, or if this is an issue with the Bioconductor build system. 

Any advice would be appreciated.

**Comment by LiNk-NY** [comment]
Hi @kayla-jackson 
Thank you for your submission. 
Please see the review below. 
Best regards,
Marcel

--- 

# concordexR #3006

## DESCRIPTION

* Looks good

## NAMESPACE

* Looks good

## vignettes

* (optional) Wrap text at the 80 column width limit for dev readability
* Resolve warning in vignette: partial match of 'val' to 'value' in
`x_by_out$val` and `y_by_out$val`
* Looks good.
* Remove GitHub code chunk from overview vignette.
* What is the advantage of creating a method for "ANY" versus a plain function
that accepts a `matrix`?

## tests

* Coverage looks good. Consider increasing coverage for `R/plot.R`.

```r
> covr::package_coverage()
concordexR Coverage: 96.15%
R/plot.R: 37.50%
R/AllGenerics.R: 100.00%
R/concordex.R: 100.00%
R/utils.R: 100.00%
```

**Comment by kayla-jackson** [comment]
Hi @LiNk-NY, 

Thank you for your feedback. 

**Vignettes**
- We've updated the vignettes to reflect your suggestions
- In the current iteration, there's no practical advantage for having an ANY method vs. a plain function that accepts a `matrix`. That said, we are actively developing methods for additional S4 classes, including `SFE`, `SPE`, `SFE`, and `Seurat`, to be released in the future versions. We wrote the ANY method with these extensions in mind. 

**Tests**
- We have increased the coverage for `R/plot.R` considerably
```
> covr::package_coverage()
concordexR Coverage: 100.00%
R/AllGenerics.R: 100.00%
R/concordex.R: 100.00%
R/plot.R: 100.00%
R/utils.R: 100.00%
```

**Comment by lambdamoses** [comment]
Also, when you said "Resolve warning in vignette: partial match of 'val' to 'value' in x_by_out$val and y_by_out$val", there is no such code in our repo.

**Comment by LiNk-NY** [comment]
> Also, when you said "Resolve warning in vignette: partial match of 'val' to 'value' in x_by_out$val and y_by_out$val", there is no such code in our repo.

Thanks, I filed an issue here: https://github.com/Alanocallaghan/scater/issues/196

**Comment by LiNk-NY** [comment]
> `Error in loadNamespace(x) : there is no package called BiocFileCache`

Sorry I missed this but perhaps it was a builder issue?
Thank you for making those changes. I took a second look at the package, it looks good. 
Thank you for your submission.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kayla-jackson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("concordexR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/concordexR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
