### ISSUE TITLE
PLSDAbatch

### ISSUE THREAD

**Issue by EvaYiwenWang** [Bioconductor/Contributions#3009]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EvaYiwenWang/PLSDAbatch

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Please check on a clean system
```
Quitting from lines 240-246 (brief_vignette.Rmd) 
Error: processing vignette 'brief_vignette.Rmd' failed with diagnostics:
could not find function "varpart"
--- failed re-building ‘brief_vignette.Rmd’
```

**Comment by EvaYiwenWang** [comment]
Hi vjcitn,

We fixed the error. Please check again. Many thanks.

Best regards,
Eva

**Comment by vjcitn** [comment]
You will probably be advised to use a SummarizedExperiment derivate like TreeSummarizedExperiment to manage your multisample data.

**Comment by LiNk-NY** [comment]
Hi YiWen, @EvaYiwenWang 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# PLSDAbatch #3009

* Please make it easier on the user to implement the operations demonstrated
in the vignette. Remember that the vignette should highlight the major
functionality provided by the package and not show a full workflow (that is
reserved for workflow type of packages).

## DESCRIPTION

* Add a `URL` field to point to the GitHub repository of the package.

## NAMESPACE

* Looks good.

## vignettes

* Consider wrapping text to a character limit of 80.
* No need to use a vector of package names. You can simply use repeated
`library()` calls. This is more common practice, i.e., remove the `sapply`
calls and use `library`.
* Please use a central representation such as `TreeSummarizedExperiment` to
represent the data, e.g., `AD_data`. Otherwise, it would be hard for the user
to follow all of the operations performed in the Pre-filtering section of the
vignette.
* Consider using `Biocpkg()` and `CRANpkg()` instead of `colorize`.

## R

* Consider using the 'allocate and fill' strategy for your `for` loops, e.g. in
`alignment_score`. Use `vector` to create an empty vector with the same size
as the expected output.
* Remove extra `###*` lines from R files. 
* Data documentation looks complete.

## tests

* Package coverage looks good.
```
> covr::package_coverage()
PLSDAbatch Coverage: 75.35%
R/plsda_batch.R: 66.67%
R/managing_batch_effects.R: 67.35%
R/batch_detection.R: 91.46%
R/batch_assessment.R: 96.15%
R/alignment_score.R: 100.00%
R/data_preprocessing.R: 100.00%
R/pb_color.R: 100.00%
```

**Comment by EvaYiwenWang** [comment]
To whom it may concern,

We have updated our package accordingly. We are very sorry for the late updates and will maintain it promptly afterwards. Could you reopen the issue? 

Best regards,
Eva

**Comment by LiNk-NY** [comment]
Hi YiWen, @EvaYiwenWang 
Could you please respond to the review? 
Thank you!
Best,
Marcel

**Comment by EvaYiwenWang** [comment]
Dear Marcel,

Many thanks for your message.
Do I need to reply to the review one by one to see if I solved the problems? I have updated my package according to the suggestions you gave in your previous review. I may list them to you then.

Best regards,
Eva

**Comment by EvaYiwenWang** [comment]
Dear Marcel,

Many thanks for your review and I am listing my answers as follows:

DESCRIPTION
Add a URL field to point to the GitHub repository of the package.
----> I added a URL like this. URL: https://github.com/EvaYiwenWang/PLSDAbatch

NAMESPACE
Looks good.
-----> Thank you.

vignettes
Consider wrapping text to a character limit of 80. 
-----> I tried to wrap as many texts as possible to the limit of 80. However, 10 lines are in the vignette code chunks which include the figure captions that I cannot shorten them. Example: ```{r ADpcaBefore, out.width = '80%', fig.align = 'center', fig.cap = 'The PCA sample plot with densities in the AD data.'}...```

No need to use a vector of package names. You can simply use repeated
library() calls. This is more common practice, i.e., remove the sapply
calls and use library.
----> Done.

Please use a central representation such as TreeSummarizedExperiment to
represent the data, e.g., AD_data. Otherwise, it would be hard for the user
to follow all of the operations performed in the Pre-filtering section of the
vignette.
----> I have reorganised the datasets with the package TreeSummarizedExperiment.

Consider using Biocpkg() and CRANpkg() instead of colorize.
-----> I removed the home-made function colorize(). For different colors of text, I used `$\color{blue}{\bf{\text{Anaerobic digestion.}}}$` instead.

R
Consider using the 'allocate and fill' strategy for your for loops, e.g. in
alignment_score. Use vector to create an empty vector with the same size
as the expected output.
----> Done.

Remove extra ###* lines from R files.
----> Done.

Data documentation looks complete.
----> Thanks.

tests
Package coverage looks good.
> covr::package_coverage()
PLSDAbatch Coverage: 75.35%
R/plsda_batch.R: 66.67%
R/managing_batch_effects.R: 67.35%
R/batch_detection.R: 91.46%
R/batch_assessment.R: 96.15%
R/alignment_score.R: 100.00%
R/data_preprocessing.R: 100.00%
R/pb_color.R: 100.00%
-----> Thanks.

Best regards,
Eva

**Comment by LiNk-NY** [comment]
Hi YiWen, @EvaYiwenWang 
Thank you for the update on the review. 
Your package has been accepted. 
Best regards,
Marcel

**Comment by EvaYiwenWang** [comment]
Many thanks, Marcel and the Bioconductor team!

Best regards,
Eva

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/EvaYiwenWang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PLSDAbatch")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PLSDAbatch

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
