### ISSUE TITLE
multiOmicsViz

### ISSUE THREAD

**Issue by wangj26** [Bioconductor/Contributions#301]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wangj26/multiOmicsViz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@lshep will review your package, but a basic observation is that it should interoperate with other Bioconductor packages -- minimally, your functions should accept SummarizedExperiment objects and make use of GenomicRanges infrastructure.

**Comment by lshep** [comment]
Thank you for your interest in Bioconductor. Please see the following comments:

**General:** 
 - [ ] Please correct the ERRORS, WARNINGS and NOTES found in the [build report](http://bioconductor.org/spb_reports/multiOmicsViz_buildreport_20170303181654.html#malbec2_buildsrc_anchor)


**Vignette:** 

 - [ ] add installation instructions for your package
``` 
source("https://bioconductor.org/biocLite.R")
biocLite("multiOmicsViz", dependencies=TRUE) 
```
This will also take care of the installing of parallel, doParallel, and foreach so you could remove the install.package instruction for these. 
 - [ ] instead of writing to getwd(), please write to a tempdir().
 - [ ]  Your input to multiOmicsViz is a R matrix or data.frame -  are there specifications on rows/names/etc? You should also make your function able to work with known Bioconductor objects for omics data; minimally be compatible with summarizedExperiment. 
 - [ ]  does the output always have to be saved to a file? could it be run interactively? what format is the output saved as?
- [ ] similarly for calculateCorForTwoMatrices: are there any restrictions or assumptions on the two matrix or data.frame objects?  same dimension? same order? etc. ?  Also should be able to use Bioconductor objects such as (minimally) summarizedExperiment.

**Man Files:** 
 - [ ] please also have man files for your included data (in extdata) and how it was generated. 
 - [ ] multiOmicsViz-package.Rd
please remove date and version from description. This will be outdated and kept track in DESCRIPTION file of the package. 

**R code:** 
multiOmicsViz.R
- [ ] Why is there a limit of 3 target omics? 
- [ ] What is the point of the Names arguments?
- [ ] use seq_along and seq_len instead of 1:length(x) See efficient coding [guidelines](http://bioconductor.org/developers/how-to/efficient-code/)

&nbsp;
&nbsp;
&nbsp;

Please address the above issues and comment back here when finished with how they have been addressed or further clarification on implementation.  Thank you.

**Comment by wangj26** [comment]
Question:  does the output always have to be saved to a file? could it be run interactively? what format is the output saved as?
Reply: This is visualization package. The output file is a heat map saved in a png file.

Question: Why is there a limit of 3 target omics?
Reply: Usually, researchers do not have more than three types of data. And more target omics data will take longer time to plot the heat map.

Question: What is the point of the Names arguments?
Reply: The name arguments is for the names of the heat map, x and y axis.

I have fixed other problems based on the comments.

Thanks

**Comment by wangj26** [comment]
Hi Ishep,

I got the error in windows like 

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'Biobase'

But I do not use Biobase in the package.

Could you please give me some suggestion about how to fix this problem?

Thanks,

**Comment by lshep** [comment]
The Biobase is an issue on our end and are in the process of resolving.  Thank you for your other changes; I will review again shortly and advise with anymore feedback.

**Comment by lshep** [comment]
Thank you for the changes.  I will recommend your package be accepted.  Please leave the issue open and you will receive svn instructions via email (normally within a week) for inclusion in Bioconductor devel.  

I would consider future revisions and be mindful on feedback for: 
1. increasing the limit beyond 3 target omics to allow for greater flexibility. it shouldn't effect the time if researchers only use <=3, and should use more with the understanding that it would be slower. 
2. allowing a flexibly output.  both to run interactively instead of directly saving to a png file as well as giving an option to the file type (png, pdf, etc)

**Comment by wangj26** [comment]
Hi Ishep,

I will increase the limit for the omics data. 

For the output format, because the output may be a very big heat map, output as a pdf may be very difficult for the users to open it and use it for the publication. Thus, we finally select the png format that has a good resolution and can be easily used for the publication.

Thanks for all your helpful comments!

**Comment by lshep** [comment]
Thank you for the clarification.  
Cheers and welcome to Bioconductor
