### ISSUE TITLE
smokingMouse

### ISSUE THREAD

**Issue by daianna-glez** [Bioconductor/Contributions#3024]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LieberInstitute/smokingMouse

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lcolladotor** [comment]
Hi @LiNk-NY,

Do you have any suggestions on how @daianna21 can resolve the warnings she has at http://bioconductor.org/spb_reports/smokingMouse_buildreport_20230530085709.html? Like

```
Warning: replacing previous import utils::findMatches by S4Vectors::findMatches when loading AnnotationForge
```

I don't think we can use https://github.com/LieberInstitute/spatialLIBD/blob/edc8b72505af097895dcbf35887df28da8122e3c/NAMESPACE#L53 or similar selective imports since Daianna is importing just 2 packages (none of the ones involved in the warning) https://github.com/LieberInstitute/smokingMouse/blob/d4e45975a02d1ca57131d858e06307e7565da37f/NAMESPACE#L3-L4C22. So it seems like the warning is outside of @daianna21's control.

Best,
Leo

**Comment by lcolladotor** [comment]
Sorry @LiNk-NY, I just saw that @lazappi is the one assigned to this package submission.

**Comment by lazappi** [comment]
I agree this is coming from a dependency that you don't really have control over so I think it's fine. Have you tried using `importFrom` (we usually require that anyway)? I'm not very familiar with how `ExperimentHub` packages work but maybe you don't even need these dependencies if they are only used in the dataset creation script (or maybe they can be suggested rather than imported).

**Comment by lcolladotor** [comment]
Thanks @lazappi for the feedback.

We are currently trying to do this as you can see at https://github.com/LieberInstitute/smokingMouse/commits/devel. @daianna21's email changed so she's trying to get that updated. Also, would it be possible to give me git push access to this repo (`git@git.bioconductor.org:packages/smokingMouse.git`)? Thanks!

```bash
% git push upstream
FATAL: W any packages/smokingMouse l.collado-torres DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Best,
Leo

**Comment by daianna-glez** [comment]
Hi, 
I think we already corrected the above warning but now I'm trying to set
up remotes to push to git.bioconductor.org and I'm getting this error:

```
MacBook-Pro-de-Daianna:smokingMouse daiannagonzalez$ git push upstream
ssh: connect to host git.bioconductor.org port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any ideas of what could be going on?

**Comment by lshep** [comment]
@lcolladotor you should now have access as well

**Comment by lshep** [comment]
@daianna21  let me know if you need help with email change on credential app.   Is your default branch name devel?  `git push upstream devel`  or if your local repo name is different you might have to map to it, for example if the local branch is main  `git push upstream main:devel`

**Comment by daianna-glez** [comment]
Hi @lshep, yes I think I need help to change my email and the default branch is `devel`. 

```
MacBook-Pro-de-Daianna:smokingMouse daiannagonzalez$ git push upstream devel
ssh: connect to host git.bioconductor.org port 22: Undefined error: 0
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Thanks.

**Comment by lcolladotor** [comment]
Thanks Lori @lshep! I just `git push`ed to the bioconductor git. Once @daianna21 tells me that she can access https://git.bioconductor.org/BiocCredentials/login/?next=/BiocCredentials/ with her new email, I'll meet with her to verify what's the issue with her `git push`es.

**Comment by lcolladotor** [comment]
@daianna21 There are 2 new errors on the latest build report http://bioconductor.org/spb_reports/smokingMouse_buildreport_20230612120802.html, likely related to you switching emails:

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/
```

**Comment by daianna-glez** [comment]
I just subscribed with my new email and the errors are gone but I still not able to do `git push upstream devel`. I already sent an email to bioc-devel@r-project.org but I haven't gotten response.

**Comment by lshep** [comment]
The email on the Credentials app is updated.  You should be able to log in and manage keys now

**Comment by lcolladotor** [comment]
Thanks Lori!

**Comment by daianna-glez** [comment]
Hi,

I still can't `git push upstream` and I'm not sure why.

```bash
% cd Desktop/smokingMouse
% ls
DESCRIPTION		README.md		smokingMouse.Rproj
NAMESPACE		dev			tests
NEWS.md			inst			vignettes
R			man
README.Rmd		pkgdown

% git remote -v
origin	https://github.com/LieberInstitute/smokingMouse.git (fetch)
origin	https://github.com/LieberInstitute/smokingMouse.git (push)
upstream	git@git.bioconductor.org:packages/smokingMouse.git (fetch)
upstream	git@git.bioconductor.org:packages/smokingMouse.git (push)
daiannagonzalez@MacBook-Pro-de-Daianna smokingMouse % git fetch --all
Fetching origin
Fetching upstream
ssh: connect to host git.bioconductor.org port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream

% git --version
git version 2.37.1 (Apple Git-137.1)
```

From the above `git remote -v` and http://contributions.bioconductor.org/git-version-control.html#new-package-workflow, I don't see any typos or issues with the `upstream` remote configuration.

```bash
% cd ~/.ssh
% more config
Host github.com
  Hostname ssh.github.com
  Port 443      
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519

% more id_ed25519.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDmnf4cjVTX7rhe4I+XOPMNmvZNwaW0tmDR9DWl9tbmG daianna2121@outlook.es

% ssh -T git@github.com
Hi daianna21! You've successfully authenticated, but GitHub does not provide shell access.
```

From the above and https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection, it does look like my `ssh` key for GitHub is well configured.

From https://git.bioconductor.org/BiocCredentials/permissions_by_user/ I do see that I have access to `smokingMouse`.

```
Bioconductor Git Credentials

[Logout](https://git.bioconductor.org/BiocCredentials/logout/)
[View User Profile](https://git.bioconductor.org/BiocCredentials/profile/)
[Which packages do I have access to?](https://git.bioconductor.org/BiocCredentials/permissions_by_user/)
'glezdaianna@gmail.com' has access to the following packages:

smokingMouse
```

Leo and I don't know what else to check or what else could be wrong. We've double checked for typos and don't see anything wrong. Leo also doesn't think that my old email being listed on the `.pub` ssh file is an issue. Re-making the `upstream` remote didn't work either:

```bash
% git remote rm upstream
% git remote add upstream git@git.bioconductor.org:packages/smokingMouse.git
% git fetch --all        
Fetching origin
Fetching upstream
ssh: connect to host git.bioconductor.org port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream
```

Maybe my IP is being blocked by git.bioconductor.org or something like that?

If you have any ideas or suggestions on what else to try, please let us know.

Thanks!
Daianna (co-written with @lcolladotor)

**Comment by daianna-glez** [comment]
As an FYI, starting with a fresh clone of https://github.com/LieberInstitute/smokingMouse didn't work either:

```bash
% git clone git@github.com:LieberInstitute/smokingMouse.git smokingMouse_fresh
Cloning into 'smokingMouse_fresh'...
remote: Enumerating objects: 590, done.
remote: Counting objects: 100% (269/269), done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 590 (delta 137), reused 201 (delta 79), pack-reused 321
Receiving objects: 100% (590/590), 13.70 MiB | 795.00 KiB/s, done.
Resolving deltas: 100% (275/275), done.

% cd smokingMouse_fresh 

% git remote -v
origin	git@github.com:LieberInstitute/smokingMouse.git (fetch)
origin	git@github.com:LieberInstitute/smokingMouse.git (push)

% git remote add upstream git@git.bioconductor.org:packages/smokingMouse.git
% git remote -v
origin	git@github.com:LieberInstitute/smokingMouse.git (fetch)
origin	git@github.com:LieberInstitute/smokingMouse.git (push)
upstream	git@git.bioconductor.org:packages/smokingMouse.git (fetch)
upstream	git@git.bioconductor.org:packages/smokingMouse.git (push)

% git fetch --all
Fetching origin
Fetching upstream
ssh: connect to host git.bioconductor.org port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream
```

My internet connection is likely fast enough for this work.

<img src ="https://www.speedtest.net/es/result/14876873664.png" />

**Comment by lshep** [comment]
What do you see with  `ssh -T git@git.bioconductor.org`

**Comment by daianna-glez** [comment]
This:
```
$ ssh -T git@git.bioconductor.org
ssh: connect to host git.bioconductor.org port 22: Operation timed out
```

**Comment by lcolladotor** [comment]
I know that Daianna @daianna21 can't ssh into JHPCE https://jhpce.jhu.edu/ from her current location in Zacatecas (also with a port 22 error) and was able to from her previous location in Morelos. So maybe it's related to her ISP in Zacatecas. She'll be in Baltimore Monday through Wednesday next week, so we can test this ISP theory then. 

In the meantime, I triggered a new Single Package Builder (SPB) run to check if the `BiocCheck` error related to Daianna's email is now resolved. That is, to verify whether Daianna is registered on the BioC support website and the BioC-devel mailing lists with her current email.

**Comment by lcolladotor** [comment]
@daianna21 can you resolve this new `ERROR` from `BiocCheck` by following the instructions? Then let me know and I'll bump the version again to trigger a new SBP run. Full details at http://bioconductor.org/spb_reports/smokingMouse_buildreport_20230621125519.html#lconway_check_anchor.

```
* Checking for support site registration...
    Maintainer is registered at support site.
    * ERROR: Maintainer must add package name to Watched Tags on the
      support site; Edit your Support Site User Profile to add Watched
      Tags.
```

**Comment by daianna-glez** [comment]
Hi, I just did it, you can try again Leo and thank you so much for your help :)

**Comment by lshep** [comment]
Yes everything seems set up correctly on our end and yours and given that even 
```
ssh -T git@git.bioconductor.org
ssh: connect to host git.bioconductor.org port 22: Operation timed out
```
results in a timeout my suspicion is a firewall or security protocol is blocking.

**Comment by daianna-glez** [comment]
Hi, the problem (as suspected) was my personal connection. I'm able to `git push upstream` now:

```
$ git push upstream devel
Everything up-to-date
```

Thanks.

**Comment by lazappi** [comment]
I've been unavailable for a bit and have lost track of this. Can you please let me know when it is ready to be reviewed?

**Comment by lcolladotor** [comment]
It is ready @lazappi =)

**Comment by lazappi** [comment]
Hi @daianna21 

Thanks for submitting **smokingMouse** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

- [ ] :rotating_light: Something that must be done
- [ ] :warning: Something that is recommended
- [ ] :green_circle: Something that is optional

## The CITATION file

- [ ] :warning: There are some TODOs in here, please make sure that they are updated. If they aren't ready yet it might be better to remove them to avoid confusing users.
- [ ] :green_circle: Maybe the original publications the data came from should be mentioned here? I think you can do something like:

```
To cite this package please use the following citation:

...

To cite the original data sources please use the following citations:

...
```

## Documentation

### Vignette

- [ ] :rotating_light: The example code isn't run at the moment (I think this is because it won't work until the package is accepted?). Please make sure you update it as soon as you can. This also applis to the `README`.
- [ ] :rotating_light: Please rename the first section to **Introduction** for consistency with other packages.
  - [ ] :green_circle: We try to encourage people to include their motivation for submitting to Bioconductor and mention any similar packages. I'm not sure that applies to data packages but please add if you think it's appropriate.
- [ ] :green_circle: I don't think it's necessary to include the code for rendering the vignette.

## Additional files

- [ ] :warning: I think you can delete the `data-raw` directory if it's not used.

As you can see my comments are pretty minor. I haven't reviewed an ExperimentHub package before so I am going to check if there is anything else I should look at but I think this should be pretty quick.

**Comment by daianna-glez** [comment]
Hi, I just corrected all your suggestions but now I'm getting a new error: 

```
Failed tests 
   Error ('test_metadata.R:5:5'): metadata is valid 
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])`: there is no package called 'S4Vectors'
```

Any ideas of how to solve it?
Thanks,

Daianna

**Comment by lcolladotor** [comment]
Hi,

From the recent commits at https://github.com/LieberInstitute/smokingMouse/commits/devel I don't see anything related to `S4Vectors`. Also from http://bioconductor.org/spb_reports/smokingMouse_buildreport_20230712150755.html#lconway_check_anchor, I see another error:

```
===============================

 BiocCheckGitClone('smokingMouse')

===============================

Error: package or namespace load failed for BiocCheck in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called Biobase
Execution halted
```

So it seems like something is wrong on the SBP (Single Package Builder) on the macOS machine. So let's not worry about this error for now.

Related to:

> 🚨 The example code isn't run at the moment (I think this is because it won't work until the package is accepted?). Please make sure you update it as soon as you can. This also applis to the README.

Daianna is going to follow the instructions at https://bioconductor.org/packages/release/bioc/vignettes/HubPub/inst/doc/CreateAHubPackage.html#storage-of-data-files to get the credentials required to upload the data. At that point, then she'll be able to edit the code so it actually does download the data, etc.



Best,
Leo

**Comment by lcolladotor** [comment]
Hm... from http://bioconductor.org/spb_reports/smokingMouse_buildreport_20230721175728.html#nebbiolo2_buildsrc_anchor it looks like `ExperimentHub::ExperimentHub()` doesn't have access to today's (2023-07-21) snapshot just yet.

We can wait a few days and try again. In any case, @daianna21 has completed the process for submitting the data to `ExperimentHub` and it works as shown at http://research.libd.org/smokingMouse/articles/smokingMouse.html#downloading-the-data-with-smokingmouse with Bioconductor 3.18 (current bioc-devel).

**Comment by lcolladotor** [comment]
Looks like next week Daianna will be able to respond properly to https://github.com/Bioconductor/Contributions/issues/3024#issuecomment-1619814733 =)

**Comment by daianna-glez** [comment]
Hi @lazappi. 
I already corrected the things you pointed in https://github.com/Bioconductor/Contributions/issues/3024#issuecomment-1619814733, in the CITATION file, the vignette and I deleted `data-raw` directory as you suggested. Please let me know if there's something else to verify. 

Thanks.

**Comment by lazappi** [comment]
Hi @daianna21. I am happy to accept your package 🎉! It can take a few days to be picked up by the build system but then it should be available as part of Bioconductor devel.

**Comment by daianna-glez** [comment]
That's great! thank you!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/daianna21.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("smokingMouse")`. The package 'landing page' will be created at

https://bioconductor.org/packages/smokingMouse

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
