### ISSUE TITLE
RegionalST

### ISSUE THREAD

**Issue by ziyili20** [Bioconductor/Contributions#3027]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ziyili20/RegionalST

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ziyili20** [comment]
@ococrook Dear Reviewer Ococrook:
I carefully checked the Warning message from the BiocCheck output. There is only one:

Checking man page documentation...
    * WARNING: Empty or missing \value sections found in man pages.

I tried to reproduce this warning message on my local machine but I couldn't. I carefully read through all the man pages, all of them have non-empty input for the \value section except the five data-related man pages (exampleRes, example_sce, pathways_hallmark, pathways_kegg, pathways_reactome). All the man pages are created using roxygen2. Should I add any additional section to these data-related man files? Thank you for any suggestion or comment!

Ziyi

**Comment by ococrook** [comment]
Hi Ziyi,

I don't think you need to worry about the warning here. I'll finish my review in the next couple of days, though I noticed you don't have unit tests so maybe you want to start thinking about those?

Best wishes,
Olly

**Comment by ococrook** [comment]
Hi Ziyi, sorry to the delay! Thanks for the submission and we are excited to see an update version after some changes. I think the vignette needs some work. 

Regional ST review

- Update R version to 4.3
- avoid using 1:... for interators as it isn’t robust you can using seq_len etc instead
- always use <- for assignments
- remove the @ from the vignette (write an accessor function)
- please add unit tests
- Please add NEWS file so you can keep track of changes

Ggplot functions

Avoid printing instead return the ggplot itself
Add bioconductor install instructions 

Vignette
Add Bioc install instructions
There are quite some eval = FALSE better to separate into two vignettes one with an easy example and the other with more detailed features which may be less simple to run
I get an error in the vignette on line 109:

example_sce <- spatialPreprocess(example_sce, platform="Visium", log.normalize=TRUE)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'type': invalid class “DelayedMatrix” object: 
    'dim(x)' must work


R code 

- try to be consistent with spaces and new lines, somtimes it's very difficult to read
- could you more carefully check the inputs of the function to make sure they are correct (otherwise the use if faced with abstrct errors.)

**Comment by ziyili20** [comment]
Hi @ococrook:
Thank you very much for your review. I have modified the package based on the suggestions. Please find the point-to-point response below:
Regional ST review
•	Update R version to 4.3
_ZL: I have updated R version to >= 4.3._
•	avoid using 1:... for interators as it isn’t robust you can using seq_len etc instead
_ZL: I have checked all the R codes and replaced 1:… to seq_len(…)._
•	always use <- for assignments
_ZL: I have checked all the R codes and used <- for assignments._
•	remove the @ from the vignette (write an accessor function)
_ZL: Removed most of the @ from vignette except three places (my email [zli16@mdanderson.org](mailto:zli16@mdanderson.org); CARD_obj@Proportion_CARD; \@ref(manual-roi-selection)). I carefully checked and CARD package and couldn’t find accessor function associated with the CARD_object. Proportion_CARD(CARD_obj) won’t work._ 
•	please add unit tests

_ZL: Unit test added. _
•	Please add NEWS file so you can keep track of changes
_ZL: Added NEWS file to /inst folder._
Ggplot functions
: Avoid printing instead return the ggplot itself
_ZL: I have modified functions DrawDotplot(), DrawRegionProportion_withProp(), DrawRegionProportion(), Replaced the print() function by return() for ggplot object._  

Add bioconductor install instructions
_ZL: Installation instruction through Bioc has been added to vignette as suggested (following the suggestion below)._ 
Vignette
: Add Bioc install instructions
_ZL: I have added as suggested._ 

There are quite some eval = FALSE better to separate into two vignettes one with an easy example and the other with more detailed features which may be less simple to run
_ZL: I actually don’t think it is necessary to separate the current vignette into two. The portions that have “eval=FALSE” sections are not complicated sections, they are intended to show alternative ways of reading data (supported by BayesSpace package) or the usage of CARD package. Those are not the purpose of this package but can be helpful when users want to use the RegionalST package._ 

I get an error in the vignette on line 109:
example_sce <- spatialPreprocess(example_sce, platform="Visium", log.normalize=TRUE)
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'type': invalid class “DelayedMatrix” object:
'dim(x)' must work
_ZL: spatialProcess() function is from BayesSpace package. I couldn’t reproduce this error, but it gives me another error when BayesSpace crashes. I have removed the spatialProcess() function by a built-in mySpatialProcess() function. Let me know if the error persists._ 

R code
•	try to be consistent with spaces and new lines, somtimes it's very difficult to read
•	could you more carefully check the inputs of the function to make sure they are correct (otherwise the use if faced with abstrct errors.)
_ZL: Thank you for the suggestion. I have gone through the functions and tried to make the format consistent. The inputs of the functions are also tested to make sure they are correct. Please let me know if you have any specific suggestion. I am happy to make the changes._

Thank you for your review. Let me know if you have any additional suggestion!

Ziyi

**Comment by ziyili20** [comment]
Hi @ococrook, it has been a while since the update and I just want to follow up the status. Thank you!

**Comment by ococrook** [comment]
Hi @ziyili20,

Sorry I have been away from the office for several weeks. There are still a few minor things that have been missed but perhaps you forgot to push a new version.

Please use <- for assignment rather than =. See line 162, 281, etc  in your vignette and similar in your readme

You still have cases of 1:X in your vignette. For example in line 163, please check elsewhere (Note the build report will find them for you)

I think you should add an accessor for CARD_obj@Proportion_CARD (you could even write a pull request for that package). Especially given this is from another package is likely to be very confusing otherwise.

It is still quite easy to provide the wrong argument types and then get cryptic errors. My suggestion is go through each function and ask what the argument type inputs need to be. If they are required to be numeric or a particular object type you should check for that with a `stopifnot`. This will save you and users a lot of time in the future.

Best wishes,
Olly

**Comment by ziyili20** [comment]
Hi @ococrook,

Thank you for another round of helpful review! Hope you enjoyed a wonderful summer break! Please find my point-to-point response below:

_Please use <- for assignment rather than =. See line 162, 281, etc in your vignette and similar in your readme_
Thank you for pointing them out. I have modified them. I have also gone through the code function by function, and hopefully corrected all the places. 

_You still have cases of 1:X in your vignette. For example in line 163, please check elsewhere (Note the build report will find them for you)_
I modified this place now. I actually try to find such usage elsewhere but couldn't find them in functions or manuals. I think I corrected them all. I didn't see specific locations in build report. Maybe this indicates that all the places have been corrected?

_I think you should add an accessor for CARD_obj@Proportion_CARD (you could even write a pull request for that package). Especially given this is from another package is likely to be very confusing otherwise._
I had a hard time understanding this suggestion. What does it mean by "add an accessor for CARD_obj@Proportion_CARD"? CARD is just one example for cell type deconvolution in spatial transcriptomics and there are other packages, such as RCTD mentioned in the vignette. Note that CARD is not a bioconductor/CRAN package. I am not sure if it is a good idea to emphasize it through pull request. 

_It is still quite easy to provide the wrong argument types and then get cryptic errors. My suggestion is go through each function and ask what the argument type inputs need to be. If they are required to be numeric or a particular object type you should check for that with a stopifnot. This will save you and users a lot of time in the future._
Thank you for the suggestion. I have gone through all the functions and add argument check step with "stopifnot".

I just submitted a new version of the package 0.99.8. It seems to build successfully in all platforms. Let me know if you have any additional comment or suggestion. Thank you very much for your review!

Ziyi

**Comment by ococrook** [comment]
Hi Ziyi,

Looks good. For the accessor comment. For removing the accessor symbol @ - which can be confusing for users. I suggest writing a function that extracts the proportions instead. E.g.

```{r,}

# Define an accessor method for Proportion_CARD

getProportion <- function(card) {

  if (!inherits(card, "CARD_obj")) { # you should replace with the appropriate object
    stop("Input must be a CARD_obj")
  }
  return(card@Proportion_CARD)
}

# usage
getProportion(Card_Obj)
```
 I hope that clearer but let me know if not.

**Comment by ziyili20** [comment]
Hi @ococrook,

Thank you for the helpful suggestion! I have added this getProportions() function to the package and bumped the package version. Personally I don't see a must to add this function, because we just list CARD as an example in the vignette. There are many other packages that serve the same purpose. But I agree that adding this accessor function may help reduce any confusion regarding the extraction of proportion information from CARD result. 

Let me know if you have any additional comments. Thank you!

Ziyi

**Comment by ococrook** [comment]
Great - thank you! If there are many packages for which you can access the the proprotions then all the more reasons to have a general accessor function that can easily be adapted to extract the proportions you need. Any new user will have some difficulty knowing exactly which slot to find the proportion's in so you are helping avoid any mistakes down the line.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ziyili20.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RegionalST")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RegionalST

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
