### ISSUE TITLE
ImpulseDE2

### ISSUE THREAD

**Issue by davidsebfischer** [Bioconductor/Contributions#303]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YosefLab/ImpulseDE2

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by davidsebfischer** [comment]
BiocCheck flags version number 0.99.0 as a warning when I run it - this is required by Bioconductor guidelines though. Happy to change this as required.

**Comment by mtmorgan** [comment]
I'll provide a more extensive review once the package has been built by the single package builder. As an initial comment, it will be necessary to modify your package to work with [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment) so that your users can benefit from integration with other Bioconductor packages and work flows. This might be straight-forward, e.g., testing whether inputs are a SummarizedExperiment and if so extracting `assay()`.

**Comment by davidsebfischer** [comment]
Thanks for the comments! Pushed 0.99.1:
1. Added SummarizedExperiment as a valid input type (as matCountData).
2. Addressed check time outs - reduced three examles with run-time >1min on your server in function annotation: fitSigmoidModels, updateDEAnalysis, plotHeatmap.
Reduced long example in vignette (Heatmap).
3. Registered for mailing list.
4. S4Vectors does not seem to be available on tokay2?

**Comment by davidsebfischer** [comment]
@mtmorgan Do you have any idea why build takes 1.5 and 2 min on windows and linux but >10min on your mac os machine? it s also faster on my mac.

**Comment by mtmorgan** [comment]
looks like it failed on our linux builder malbec2 most recently. The two common problems are an unreliable web service or buggy parallel implementation. Are either of those likely to apply?

**Comment by davidsebfischer** [comment]
Thanks for your help! ImpulseDE2 uses BiocParallel for parallelisation but it should only be called in sequential mode in vignette examples and function annotation examples. There is no web interface.

**Comment by davidsebfischer** [comment]
The mac os server build 0.99.3 in 2 minutes, there are hardly any changes to 0.99.5 (building in >10min), added knitr and Biobase into namespace and modified one annotation example to reduce build time.

**Comment by mtmorgan** [comment]
The builder is used for multiple purposes and it can be that the builds take a long time because they are competing for resources; I recommend that you do not worry about this timeout.

**Comment by mtmorgan** [comment]
## Build

`R-dev CMD build ImpulseDE2` : works fine.

`R-dev CMD INSTALL ImpulseDE2_0.99.3.tar.gz` : Works fine.


## DESCRIPTION

* More elaborate Description. It should be like the abstract of a paper. Describe the unique
  aspects of your method.

* Spell check

* LICENSE: Please choose a standard open source license. No recent Bioconductor package,
           uses an academic-only license.

## NAMESPACE

* Ok.

## Vignette

* Remove HTML document, this is not needed as the vignette gets built.

* Spell check many places.

* Session Information missing from vignette to see which platform and what   packages were used exactly.

  ```
  sessionInfo()
  ```

## man

* Nice man pages!

## R

* Use better indentation for the code. 4 spaces or 8 spaces is preferred, makes the code more readable. Consider using the [formatr][] package to present your code in a more standardized way.

* To minimize the number of lines crossing 80 chars, you can open close your `if` statements with `{` and `}`. Makes the code way more readable for package reviewers.

    ```
    if (test && test) {
        do something
    } else {
        do something else
    }
    ```

* Consider using `&&` logical operator for the double `if` statements. You could use short circuiting logic there to make your code more readable. Eg: line 104, 105 in `ImpulseDE2_plotGenes.R`. 


* Use `message` instead of `print` for displaying information during the processing of the functions.
  Eg: ImpulseDE2_main.R, line 198

    ```
      strMessage <- "# Process input"
      if(boolVerbose) {
          message(strMessage)
      }
    ```

* Remove commented code in `src_ImpulseDE2_runDESeq2.R`.

* MAXIT in `srcImpulseDE2_fitSignmoid.R` has default=100 in the code, but 1000 in the documentation. Check the default values through out the package if they are correct and as needed.

* Review your code for efficient implemenetation. For instance,
  original code, srcImpulseDE2_fitImpulse.R:55:
  
    ```
  	vecBatchFactorsConfounder <- sapply(unique(vecidxBatch), 
        function(batch){
  		    mean(vecCountsSFcorrected[vecidxBatch==batch] / 
                mean(vecCounts, na.rm=TRUE), na.rm=TRUE)
  	})
    ```

    `mean(vecCounts, na.rm=TRUE)` is calculated repeatedly, but can be
    calculated only once.

    ```
    meanVecCounts <- mean(vecCounts, na.rm=TRUE)
  	vecBatchFactorsConfounder <- sapply(unique(vecidxBatch), 
        function(batch){
  		    mean(vecCountsSFcorrected[vecidxBatch==batch] / 
                meanVecCounts, na.rm=TRUE)
  	})
    ```

    Note that
    
    ```
    vecCountsSFcorrected[vecidxBatch==batch] / meanVecCounts
    ```
    
    is the same as

    ```
    (vecCountsSFcorrected / meanVecCounts)[vecidxBatch==batch]
    ```
    
    and `(vecCountsSFcorrected / meanVecCounts)` is again constant
    over the loop, so
    
    ```
    meanVecCounts <- mean(vecCounts, na.rm=TRUE)
    x <- vecCountsSFcorrected / meanVecCounts
  	vecBatchFactorsConfounder <- sapply(unique(vecidxBatch), function(batch) {
       mean(x[vecidxBatch == batch], na.rm=TRUE)
    })
    ```
    
    Another example: in lines 72-80

    ```
    scaNTimepoints <- length(vecTimepointsUnique)
    scaMaxMiddleMean <- max(vecExpressionMeans[2:(scaNTimepoints-1)], na.rm=TRUE)
    scaMinMiddleMean <- min(vecExpressionMeans[2:(scaNTimepoints-1)], na.rm=TRUE)
    ...
    ```
    
    `2:(scaNTimepoints-1)` is used repeatedly. Calculate once and re-use

    ```
    idx <- 2:(scaNTimepoints-1)
    scaMaxMiddleMean <- max(vecExpressionMeans[idx], na.rm=TRUE)
    scaMinMiddleMean <- min(vecExpressionMeans[idx], na.rm=TRUE)
    ...
    ```
    
    Also `2:n` is very dangerous, because `n` can be less than 2,
    
    ```
    > 2:1
    [1] 2 1
    ```
    
    consider more robust alternatives, e.g.,
    `tail(seq_len(scaNTimepoints - 1), -1)`
    
    As a third example, on line 79
    
    ```
    vecGradients <- unlist( lapply(c(1:(scaNTimepoints-1)),function(x) {
        (vecExpressionMeans[x+1] - vecExpressionMeans[x]) / 
            (vecTimepointsUnique[x+1]-vecTimepointsUnique[x])
    }) )

    ```

    calculate the difference between successive values using `diff()`
    
    ```
    d1 <- diff(vecExpressionMeans)
    d2 <- diff(vecTimepointsUnique)
    vecGradients <- d1 / d2
    ```
    
    There are obviously a very large number of opportunities to
    improve your code.
    
* Define and use 'accessor' functions instead of direct slot access `@`. The 'accessor' functions can be plain-old R functions (not methods) and do not have to be exported to the user.
    
[formatr]: https://yihui.name/formatr/

**Comment by mtmorgan** [comment]
The deadline for adding packages to the next release is Friday; if you'd like your package to receive continued consideration, please respond by then.

**Comment by davidsebfischer** [comment]
Largely adopted the changes, I have not yet switched from direct slot access to accessor functions yet.

**Comment by davidsebfischer** [comment]
Thank you for the detailed feedback!

**Comment by davidsebfischer** [comment]
Switch from direct slot accession to accessor functions is included in the last commit, I addressed all issues raised before.

**Comment by mtmorgan** [comment]
Thank you. I'm marking this package as accepted. It will be added to our nightly builds and svn repository, with additional instructions via email in a few days.
