### ISSUE TITLE
HPO.db

### ISSUE THREAD

**Issue by huerqiang** [Bioconductor/Contributions#3031]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/HPO.db

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by huerqiang** [comment]
I have updated the HPO.db package and it passed the RCMD check with 
0 errors ✔ | 0 warnings ✔ | 0 notes ✔

**Comment by vjcitn** [comment]
Are you checking on a clean system?
```
ℹ Loading HPO.db
Error in getClass(Class, where = topenv(parent.frame())) : 
  "MPODb" is not a defined class
```

**Comment by huerqiang** [comment]
@vjcitn Hi, I have update the HPO.db package to version 0.99.1 to fix some typo, please test this version. The previous error '"MPODb" is not a defined class' was because I only pushed local modifications to my own repository (git@github.com:huerqiang/HPO.db.git) and forgot to push them to the our team repository (git@github.com:YuLab-SMU/HPO.db.git)

**Comment by huerqiang** [comment]
@Kayla-Morrell Hi, I would like to ask how the reivew is going, is there anything that needs to be modified?

**Comment by Kayla-Morrell** [comment]
@huerqiang - Sorry for the delay on the initial review.
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less 
than 3 sentences. Please consider expanding this field, and structure it as a 
full paragraph.

## NAMESPACE

- [ ] REQUIRED: The importFrom for packageVersion should not have quotes around
  utils.

## Data

- [ ] SUGGESTION: I would move the two R files in the inst/extdata to the
  inst/script directory.

## Vignette

- [ ] SUGGESTION: We suggest using the `BiocStyle` package for formatting. 
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install the package via Bioconductor. The code chunk should be
include `eval = FALSE`.
- [ ] SUGGESTION: We suggest using table of contents.

## R code

- [ ] SUGGESTION: Avoid 'suppressWarning'/'Messages' if possible (found 2 times)
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 11 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
 indents. There are 54 lines that are not.

Best,
Kayla

**Comment by huerqiang** [comment]
@Kayla-Morrell Hi, I have updated the package and made changes to all required items and some suggestgion items.

> ## DESCRIPTION
> * [x]  SUGGESTION: The Description field in the DESCRIPTION is made up by less
>   than 3 sentences. Please consider expanding this field, and structure it as a
>   full paragraph.
> 
> ## NAMESPACE
> * [x]  REQUIRED: The importFrom for packageVersion should not have quotes around
>   utils.
> 
> ## Data
> * [x]  SUGGESTION: I would move the two R files in the inst/extdata to the
>   inst/script directory.
> 
> ## Vignette
> * [ ]  SUGGESTION: We suggest using the `BiocStyle` package for formatting.
> * [x]  REQUIRED: There should be an 'Installation' section that demonstrates to
>   the user how to install the package via Bioconductor. The code chunk should be
>   include `eval = FALSE`.
> * [ ]  SUGGESTION: We suggest using table of contents.
> 
> ## R code
> * [ ]  SUGGESTION: Avoid 'suppressWarning'/'Messages' if possible (found 2 times)
> * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 11
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
>   indents. There are 54 lines that are not.

**Comment by Kayla-Morrell** [comment]
@huerqiang - Thank you for making the necessary changes. I've reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/huerqiang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HPO.db")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HPO.db

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
