### ISSUE TITLE
HarmonizR

### ISSUE THREAD

**Issue by SimonSchlumbohm** [Bioconductor/Contributions#3037]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HSU-HPC/HarmonizR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Interesting package.  Have you considered the use of SummarizedExperiment or its derivates, or MultiAssayExperiment, for managing the combinations of phenotypes and assays that you are working with?  This is a standard approach to dealing with multiple assays on multiple samples and we strongly encourage this approach.

**Comment by SimonSchlumbohm** [comment]
Dear @vjcitn ,

thank you for your comment on the submitted package. We included support for the S4 SummarizedExperiment data type within the HarmonizR package and updated documentation accordingly.  HarmonizR will now parse and return S4 SummarizedExperiment data to support more fluent data pipelining.

A version-bump to 0.99.1 has been made according to Bioconductor guidelines.

With best regards

Simon Schlumbohm

**Comment by ococrook** [comment]
Hi @SimonSchlumbohm 

I'm very sorry for the delay. I've been out of office for July. The package looks really good and it very clear to follow. Some trivial things before acceptance:


- update to R 4.3
- Add Bioc instruction (remember eval = FALSE) to the vignette and readme
- If I'm being picky could you remember to add spaces between `=` so it is `A = B` rather than `A=B`. The former is much easier to read.
- Could you seperate out the main processing function and any plotting into two seperate functions? It is still fine to have a plot argument in the function which calls this plotting aspect but it good practice to keep these things seperated. 

Best wishes,
Olly

**Comment by SimonSchlumbohm** [comment]
Dear @ococrook 

thank you for the response. The package has been modified in the following ways:

- An update to R 4.3 has been made
- Instructions on how to install HarmonizR from Bioconductor were added to the README and the vignette (currently marked with "upon availibility")
- Spaced have been added in various places to improve readability
- The code concerning plotting preparations has been separated from the main processing function and is now its own function

Sincerely

Simon Schlumbohm

**Comment by ococrook** [comment]
Brilliant, thank you Simon

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SimonSchlumbohm.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HarmonizR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HarmonizR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by SimonSchlumbohm** [comment]
@vjcitn @ococrook @lshep 
I would like to express a thank you from my side to everyone who has been involved in the process.

Sincerely

Simon Schlumbohm
