### ISSUE TITLE
orthosData

### ISSUE THREAD

**Issue by ppapasaikas** [Bioconductor/Contributions#3042]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fmicompbio/orthosData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ppapasaikas** [comment]
AdditionalPackage: https://github.com/fmicompbio/orthos

**Comment by lshep** [comment]
sorry for the delay.  I was away at a conference. I will be doing reviews over the next few days.

**Comment by ppapasaikas** [comment]
Of course! No problem, thank you for all the effort you put in reviewing the packages :-)

Regarding the orthosData package:
There is a change in the zenodo repository where the data are deposited.  The change affects the Location_Prefix of all the datasets and the RDataPath of one file.
The updated metadata.csv file has been committed to the orthosData github repo:
[metadata](https://github.com/fmicompbio/orthosData/blob/devel/inst/extdata/metadata.csv)

Please let me know if you have any other question.
Many thanks!

**Comment by lshep** [comment]
We'll have to either remove and readd the data and make the change manually ---  it would probably be faster to make the change manually -- could you please identify the one RDataPath that is affected -- I should be able to change the location_prefix in batch if the change is uniform across all

**Comment by ppapasaikas** [comment]
Absolutely:

The affected file:
```
Title: decomposed_contrasts_human_hdf5
Old  RdataPath: human_v212_c100assays.h5
New RdataPath: human_v212_NDF_c100assays.h5
```

Old Location_Prefix:
https://zenodo.org/record/7554915/files/
New Location_Prefix:
https://zenodo.org/record/7908269/files/

The Location_Prefix change is indeed uniform across all the data.

**Comment by lshep** [comment]
In the future it would be better to use  `Location_Prefix`  as `https://zenodo.org/` and then the RDataPath as everything else.  We have other researches that use zenodo also so this would reuse the same location_prefix and have each dataset under unique

**Comment by lshep** [comment]
haven't looked into the details yet (I'm reviewing now -- I was having trouble getting reticulate installed and actually opened an issue on their github) but it is also taking a fair amount of build on my local machine.  Do you download a lot of data in the vignette?

**Comment by ppapasaikas** [comment]
Hi,
Most of the time spent (also on the github actions for orthos, which take ~30' per build) is coming from building the conda environment.
There are no extremely big datasets downloaed for the vignette.  Only the models and the DEMO version of the DB.  Largest file is 450Mb. Total size is 2Gb.

**Comment by ppapasaikas** [comment]
fwiw. I currently get the same error [you reported](https://github.com/rstudio/reticulate/issues/1400) when trying to install reticulate with R.4.3.0 devel.

**Comment by lshep** [comment]
yeah my temporary work around is to manually install version 1.28 of reticulate but not ideal

**Comment by lshep** [comment]
**orthosData**

- [x] Good

- [ ] We recommend still having a package level man page so something occurs
  with `?orthosData` but this is optional.


---------------------------------------------

**orthos**

**inst**

- [ ] Please have accompanied inst/script to describe how the data in
  `inst/extdata` was generated and appropriate source/licensing information.

- [ ] optional. I see in the vignette you call TopHits$RESIDUAL_CONTRASTS fairly
  often. maybe it would be worth having a helper function to retrieve this
  instead of the user typing the entire thing out.

- [ ] R CMD check when I run locally has a test failure. I'm hoping because the
  python environments are saved that on next run we can see what the builds show
  as well. 

```
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  [ FAIL 1 | WARN 4 | SKIP 1 | PASS 228 ]
  
  ══ Skipped tests (1) ═══════════════════════════════════════════════════════════
  • cannot test `mustWork` when data is available (1): 'test-decomposeVar.R:66:5'
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-plotQueryResults.R:97:5'): plotQueryResultsViolin works ──────
  file.info(tf)["size"] > 20000 is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  
  [ FAIL 1 | WARN 4 | SKIP 1 | PASS 228 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK


```

- [ ] Here are the results of BiocCheck locallly too. Not sure whats going on
  with all the do_eval

```
> BiocCheck("orthos_0.99.0.tar.gz")
─ BiocCheckVersion: 1.37.4
─ BiocVersion: 3.18
─ Package: orthos
─ PackageVersion: 0.99.0
─ sourceDir: /tmp/Rtmp4U83Gw/file7a137872e3ea/orthos
─ installDir: /tmp/Rtmp4U83Gw/file7a131ae7893
─ BiocCheckDir: /home/lorikern/PkgReview/orthos.BiocCheck
─ platform: unix
─ isTarBall: TRUE

* Installing package...
* Checking for deprecated package usage...
* Checking for remote package usage...
* Checking for 'LazyData: true' usage...
* Checking version number...
* Checking for version number mismatch...
* Checking version number validity...
    Package version 0.99.0; pre-release
* Checking R version dependency...
* Checking package size...
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
* Checking package type based on biocViews...
    Software
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
* Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews:
      Sequencing, Coverage
Search 'biocViews' at https://contributions.bioconductor.org
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for proper Description: field...
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
* Checking License: for restrictive use...
* Checking for pinned package versions...
* Checking DESCRIPTION/NAMESPACE consistency...
* Checking .Rbuildignore...
* Checking for stray BiocCheck output folders...
* Checking vignette directory...
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
* Checking package installation calls in R code...
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
Error in eval(x, envir = envir) : object 'do_eval' not found
* Checking for library/require of orthos...
* Checking coding practice...
* Checking parsed R code in R directory, examples, vignettes...
* Checking function lengths...
    * NOTE: The recommended function length is 50 lines or less. There
      are 5 functions greater than 50 lines.
* Checking man page documentation...
    * NOTE: Consider adding runnable examples to man pages that
      document exported objects.
    * NOTE: Usage of dontrun{} / donttest{} tags found in man page
      examples. 14% of man pages use at least one of these tags.
* Checking package NEWS...
* Checking unit tests...
* Checking skip_on_bioc() in tests...
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 122 lines (5%) are > 80 characters
      long.
    * NOTE: Consider multiples of 4 spaces for line indents; 223 lines
      (8%) are not.
    See https://contributions.bioconductor.org/r-code.html
    See styler package: https://cran.r-project.org/package=styler as
      described in the BiocCheck vignette.
* Checking if package already exists in CRAN...
* Checking for bioc-devel mailing list subscription...
    Maintainer is subscribed to bioc-devel.
* Checking for support site registration...
    Maintainer is registered at support site.
    Package name is in support site watched tags.

─ BiocCheck results ──
0 ERRORS | 0 WARNINGS | 6 NOTES

See the orthos.BiocCheck folder and run
    browseVignettes(package = 'BiocCheck')


```

**Comment by ppapasaikas** [comment]
Many thanks for going over the packages.
We have addressed your comments (see below). Please let us know if you have any additional comments.

> **orthosData**
> 
> * [x]  Good
> * [x]  We recommend still having a package level man page so something occurs
>   with `?orthosData` but this is optional.

Done

> 
> **orthos**
> 
> **inst**
> 
> * [x]  Please have accompanied inst/script to describe how the data in
>   `inst/extdata` was generated and appropriate source/licensing information.

Done

> * [ ]  optional. I see in the vignette you call TopHits$RESIDUAL_CONTRASTS fairly
>   often. maybe it would be worth having a helper function to retrieve this
>   instead of the user typing the entire thing out.

We plan to rework the way results are returned from the querying function, but while we do this we will stick with the current setup.

> * [x]  R CMD check when I run locally has a test failure. I'm hoping because the
>   python environments are saved that on next run we can see what the builds show
>   as well.

This looks ok now.

>  * [x]  Here are the results of BiocCheck locallly too. Not sure whats going on
>   with all the do_eval

The do_eval parametrisation is now removed from the vignette. This should take care of this issue.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ppapasaikas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("orthosData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/orthosData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ppapasaikas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("orthos")`. The package 'landing page' will be created at

https://bioconductor.org/packages/orthos

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
