### ISSUE TITLE
GenomicPlot

### ISSUE THREAD

**Issue by shuye2009** [Bioconductor/Contributions#3046]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/shuye2009/GenomicPlot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by shuye2009** [comment]
There is a warning for large files related to .git pack file and .Rproj.user which are hard to deal with, maybe you can provide some help. Thank you.

**Comment by lshep** [comment]
http://contributions.bioconductor.org/git-version-control.html#remove-large-data-files-and-clean-git-tree

**Comment by shuye2009** [comment]
Ishep, thanks for the link. I tried the method described in the link, and the pack file size got bigger, it cleaned git history but not the pack file.

**Comment by vjcitn** [comment]
You will want to read the guidelines about vignette formatting and inclusion of sessionInfo

**Comment by shuye2009** [comment]
I have reformatted the vignette using BiocStyle and put the sessionInfo into Appendix

**Comment by shuye2009** [comment]
Hi Helena,
I have addressed issues in the build report, but having difficulties in pushing to upstream:
Here is what git remote -v shows in my local repository:
$ git remote -v
origin  https://github.com/shuye2009/GenomicPlot (fetch)
origin  https://github.com/shuye2009/GenomicPlot (push)
upstream        git@git.bioconductor.org:packages/GenomicPlot.git (fetch)
upstream        git@git.bioconductor.org:packages/GenomicPlot.git (push)

and Bioconductor Git Credential shows:
'shuye2009@gmail.com' has access to the following packages:
GenomicPlot

but when I do: (release is my github default branch)
$ git push upstream release
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Thanks for your help.

Shuye

**Comment by HelenaLC** [comment]
Did you follow the [Git Version Control](https://contributions.bioconductor.org/git-version-control.html?q=ssh#git-version-control) guidelines? At the very bottom there's instructions regarding setting up SSH credentials.

**Comment by shuye2009** [comment]
@HelenaLC: Somehow the public key for Rstudio terminal is not working, I managed to push to upstream with gitbash public key. Thanks for pointing me to the instructions.

**Comment by shuye2009** [comment]
Hi Helena,

In BiocCheck, I got this output:
* Installing package...
* Checking for deprecated package usage...
Error in `[.data.frame`(pkg_status, , "PackageStatus") : 
  undefined columns selected
Calls: BiocCheck ... getAllDeprecatedPkgs -> get_deprecated_status -> [ -> [.data.frame
Execution halted

Any ideas what might be the problem? When I run BiocCheck locally, it did not happen.

**Comment by lshep** [comment]
This is an issue on the Bioconductor side we are investigating

**Comment by shuye2009** [comment]
> This is an issue on the Bioconductor side we are investigating

@lshep : Is this issue resolved? I am ready to push my changes to upstream.

Thanks.

**Comment by lshep** [comment]
Yes it should be resolved.

**Comment by shuye2009** [comment]
@HelenaLC: In the build report, there is only one warning when build BIN on macOS: "Warning: replacing previous import Biostrings::pattern by grid::pattern when loading genomation". This is caused by the imported package 'genomation'. I have no idea how to get rid of this warning and it seems that it is out of my control. Any suggestions? Thanks.

**Comment by HelenaLC** [comment]
# general

- [ ] In the DESCRIPTION, update R version dependency from 4.2.0 to 4.3.0 (see build report).

- [ ] In the README, please include Bioc installation instructions, i.e., via `BiocManager::install("GenomicPlot", version = "devel")`.

- [ ] Consider adding a NEWS file to track version-specific changes (see build report and [here](https://contributions.bioconductor.org/news.html?q=news#news) for instructions).

- [ ] The files *vignettes/GenomicPlot_vignettes.R* and *.html* should not be contained in the upstream Bioc repo; please remove these or add them to your local *.gitignore*.

- [ ] Unit test coverage (of non-long tests) is currently at <9% overall, which is fairly minimal given the amount of code in the package (~2,000 lines of code are not tested at all). Please consider adding (a lot) more unit tests to guarantee long term stability. This should be easier to achieve if the code were factorized more (see related comment below).

```r
# devtools::test_coverage()
GenomicPlot Coverage: 8.88%
R/HandleDataMatrix.R: 0.00%
R/DrawingFunctions.R: 4.90%
R/GenomicPlot.R: 6.38%
R/ReadData.R: 16.02%
R/HandleFeatures.R: 21.70%
R/Parallel.R: 48.72%
```

# code

- [ ] Please have a look at the code style guidelines summarized [here](https://contributions.bioconductor.org/r-code.html#coding-style). Specifically, I'd highly encourage 4-space/tab indentation, and upholding an 80-character/line limit. The style is currently highly inconsistent and difficult to read, primarily because there are few line breaks (see also the corresponding NOTEs in the build report).

- [ ] The recommended function length is 50 lines; currently, there are functions with 100s of lines (e.g., in *GenomicPlot.R*). Please consider factorizing code such that parts of functions are more easily testable, maintainable, and understandable (see also the corresponding NOTEs in the build report).

- [ ] Related to the above... In the long term, the code base might be easier to track/maintain if functions had a designated script. E.g., now, *GenomicPlot.R* has ~3,600 lines of code, containing all plotting functionality. Just a suggestion though...

- [ ] Plotting functions in *GenomicPlot.R* expect specific types of input arguments (e.g., character vector of files names of a specific type, numeric vector, scalar integer...). Consider adding argument validity checks at the top of each. For example, a function might execute 50% and then fail because the input `binSize = "x"` or `0.5` is invalid (same holds for any function, of course).

# documentation

- [ ] Consider adding a package documentation page (accessible via `?GenomicPlot`) such that users would be directed to the package's main functionality, a summary of the general workflow/main features, relevant resources etc.

- [ ] *extdata/* should be accompanied by (a) related script(s) demonstrating how the data was generated; in general, *all example data must be documented*, i.e., in designated *.man* pages for each/a set of dataset (see [here](https://contributions.bioconductor.org/docs.html#data-man) for instructions); documentation should include, e.g., source information/reference, data type and content/variable description, brief biological/experimental description etc.

- [ ] *.man* pages that export functions should contain runnable examples (see corresponding NOTE in the build report); to give one example, `plot_overlap_genes()` currently does not.

- [ ] `eval=FALSE` flags and similar undermine the benefit of vignettes and are generally not allowed (see [here](https://contributions.bioconductor.org/docs.html?q=vigne#vignettes) for guidelines). For example, you are inserting pre-generated graphics as opposed to dynamically generate outputs using the package.

- [ ] In the vignette, consider using code-style (back ticks) to highlight/distinguish R-related content (e.g., variable, argument, function, package names etc.) from plain text. This aids readability a lot, especially in larger text blocks.

- [ ] Especially in the vignette, please stick to an 80-character per line limit. This document will be consulted by most users online, as an HTML, and is easier to follow if code "fits" the page without the need to scroll horizontally.

**Comment by shuye2009** [comment]
@HelenaLC Thanks for the detailed review report. I will make changes according to your comments and valuable suggestions.

**Comment by shuye2009** [comment]
Fixed a bug in plot_peak_annotation.R

**Comment by HelenaLC** [comment]
Thanks for all this, especially splitting the code into easier-to-track separate scripts! Couple comments outstanding, but looking good overall.

- [ ] The DESCRIPTION currently lists 6 packages under `Depends:`, which is fairly unusual. I'd suggest moving anything other than `GenomicRanges` to `Imports:` (see [here](https://contributions.bioconductor.org/description.html#depends-imports-suggests-enhances) for details).

- [ ] R CMD CHECK is filled with `no visible binding` NOTEs. You can address these by calling `utils::globalVariables()`, listing all variables that undergo non-standard evaluation such as `ggplot`ing (e.g., in *Setup.R* of above/below corresponding functions); this should stop R CMD CHECK from complaining.

- [ ] In `plot_locus()`, there's an argument `heatmap` ("indicating whether a heatmap of the score matrix should be generated"); but I don't see this happening in the vignette? Sorry if I'm missing something, but I found this confusing/worth mentioning.

- [ ] Same as before: All *man* pages of exported functions should contain runnable examples (see build report NOTE on this). Some currently don't (e.g., `plot_region`, `plot_locus`).

- [ ] In the vignette, consider directing users to external software through hyperlinks using `BiocStyle`, e.g., `BiocStyle::Biocpkg("CoverageView")`.

- [ ] Recommended function length is 50 lines, but I see this is unreasonable with `ggplot`ing. However, some of the functions might be worth re-factorizing (e.g., `plot_locus()` is ~700 lines!) such that there are sub-functions for, say in `plot_5parts_metagene`, coverage and heatmap, or setting up the data vs. rendering plots, or generating sub-parts of the plots etc. etc... Just a suggestion though.  

- [ ] I see you now documented the `inst/extdata`, but this was tricky to find without searching the code base (which users typically don't). Perhaps you could link the files using `@aliases test_file1.txt ...` so that one could, in principle, find this information more easily when running, e.g., some example code.

- [ ] Also on data documentation: expect for `gencode.v19.annotation_chr19.gtf`, the documentation currently does not include any source information, but only a brief description of the data types. Please include this and, if applicable, scripts to generate these data (see also previous review and [here](https://contributions.bioconductor.org/docs.html#data-man) for details). 

- [ ] Try avoiding `for`-loops in favor of `l/vapply` when possible (see [here](https://contributions.bioconductor.org/r-code.html#pre-allocate-and-fill-if-iterations-are-necessary) for details). E.g., the nested loop at lines 165+ in *GenomicPlot.R* could be written using as

```
fil <- ifelse(stranded, 
  filter_by_overlaps_stranded, 
  filter_by_overlaps)
counts <- vapply(grList, function(i) 
  vapply(grList, function(j)
  length(fil(i, j)), integer(1)), 
  integer(length(grList))) |> t()
  
# or
ij <- seq_along(grList)
ij <- expand.grid(ij, ij)
fil <- ifelse(stranded, 
  filter_by_overlaps_stranded,
  filter_by_overlaps)
counts <- mapply(
  i=ij[, 1], j=ij[, 2], function(i, j) 
  length(fil(grList[[i]], grList[[j]]))) |>
  matrix(nrow=length(grList))
```

- [ ] Might be worth adding very simple unit tests for each for the `plot_` functions, perhaps varying some of the input parameters (such that you actually try out all those `if...else` cases that control the plotting results), and testing that outputs are what you expect. Again, the purpose of this is to quickly detect when & where functions break, e.g., due to dependency changes. Still quite a few untested functions:

```
GenomicPlot Coverage: 35.93%
R/Plot_5parts_metagene.R: 0.00%
R/Plot_locus_with_random.R: 0.00%
R/Plot_locus.R: 0.00%
R/Plot_region.R: 0.00%
R/Plot_start_end_with_random.R: 0.00%
R/Plot_start_end.R: 0.00%
R/HandleFeatures.R: 59.41%
R/Plot_peak_annotation.R: 62.26%
R/DrawingFunctions.R: 71.20%
R/HandleDataMatrix.R: 77.51%
R/ReadData.R: 81.27%
R/GenomicPlot.R: 81.37%
R/Parallel.R: 91.84%
R/Plot_bam_correlation.R: 92.44%
```

**Comment by shuye2009** [comment]
@HelenaLC Thanks for the guidance which helps a lot to improve the package to meet the Bioconductor's standards.  I have made changes to address all your suggestions, except for the length of functions. I totally agree with you that some functions are exceptionally long, and I am planning to improve on them in the future release.

**Comment by shuye2009** [comment]
Hi, 
My last build on July 28, 2023 was error free, but the ERROR label has not been removed so far, can you please look into it? Thanks a  lot.

**Comment by lshep** [comment]
We had issues with the auto label remover.  They have been correct and labels with be added/removed correctly moving forward.

**Comment by shuye2009** [comment]
Dear Bioconductor team, 

Thank you for accepting our package 'GenomicPlot'. Thank you, especially @HelenaLC, for reviewing the package which helped a lot in improving its quality. 

Is it okay for me to push small changes to upstream before release?

Shuye

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shuye2009.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GenomicPlot")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GenomicPlot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
