### ISSUE TITLE
multiWGCNAdata

### ISSUE THREAD

**Issue by dariotommasini** [Bioconductor/Contributions#3063]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dariotommasini/multiWGCNAdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
@lshep this may be a multiple package submission?  multiWGCNA is required for this package to install

**Comment by dariotommasini** [comment]
Hi, that's correct this is a two package submission. I don't think multiWGCNA should be required for this data package to install. It is required for the vignette however. Should I add the Additional Package line for multiWGCNA?

**Comment by lshep** [comment]
Sorry I'm behind on processing packages and assigning reviewers -- I'll get to this today or tomorrow.  You can add the additional package AFTER the 'review in progress' tag and a reviewer is assigned.  thanks!

**Comment by dariotommasini** [comment]
Hi, I am trying to push changes to trigger a new build. I keep getting this error: 

git fetch --all
Fetching origin
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream

Here is the output of git remote -v
origin	https://github.com/dariotommasini/multiWGCNAdata.git (fetch)
origin	https://github.com/dariotommasini/multiWGCNAdata.git (push)
upstream	git@git.bioconductor.org:packages/multiWGCNAdata.git (fetch)
upstream	git@git.bioconductor.org:packages/multiWGCNAdata.git (push)

I do have an ssh key added to my github account, but perhaps its not finding it.

**Comment by lshep** [comment]
Did you activate the bioc git credentials account as mentioned in the comment above?

**Comment by dariotommasini** [comment]
Sorry, I didn't even see that there were two comments. 

I tried activating, but it doesn't recognize my email. I think this is my fault, because I put a different email in this package DESCRIPTION file from the one I use for Github. I get the following error: 

dtommasini0@gmail.com is not associated with a maintainer of a Bioconductor package. Please check the spelling or contact bioc-devel@r-project.org for help.

Is there an easy way to fix this?

**Comment by lshep** [comment]
The emails don't have to match for the one you use in the DESCRIPTION to the one you use on github.  If you sign in on the app with dtommasini@berkeley.edu you can activate your account and change keys for access.   if you would like me to reset the account with gmail I can take care of this on Monday if you feel more comfortable using that email for the app.

**Comment by dariotommasini** [comment]
Okay, do you mind changing to email to dtommasini0@gmail.com? Sorry about this!

**Comment by lshep** [comment]
It is changed.  Please see email for temporary password to activate account

**Comment by dariotommasini** [comment]
The first build failed because it couldn't find the software package (multiWGCNA) for which this data package is for. I added multiWGCNA to Suggests since its only used in the vignette, but I still get error "there is no package called multiWGCNA." Would this classify as a circular dependency? Do you recommend I remove multiWGCNA from Suggests and the vignette?

**Comment by lshep** [comment]
Yes it is a soft circular dependency.   It will find it once I process the Software package the same as I did for the data package.  You can add it now with `AdditionalPackages`  as described https://github.com/Bioconductor/Contributions#circular-dependencies .  We will take a quick peek like we did the data package to make sure nothing malicious and looks like a package and then it would be able to find it in this issue.

**Comment by dariotommasini** [comment]
Okay, thank you! I'll add the software package soon, I just need to finish addressing some of the warnings from `BiocCheck` and `R CMD check`.

**Comment by dariotommasini** [comment]
AdditionalPackage: https://github.com/fogellab/multiWGCNA

**Comment by lshep** [comment]
sorry for the delay.  I was away at a conference. I will be doing reviews over the next few days.

**Comment by lshep** [comment]
I just kicked off a manual rebuild of the data package to get the reports now that the software package is available to find in the issue. Working on the review now and it will be posted in the next few hours

**Comment by lshep** [comment]
**multiWGCNAdata**

**build report**

- [ ] Clean up report from ERROR/WARNINGS/NOTES

- [ ] Please include in the `inst/scripts` information on how the files that
  were uploaded to ExperimentHub were generated. The process and include any
  relevant source and licensing information.







--------------------------------------------------------


**multiWGCNA**

**build report**

- [ ] Clean up report from ERROR/WARNINGS/NOTES

**README**

- [ ] Include Bioconductor installation instructions

**man**

- [ ] We recommend a package level man page so that `?multiWGCNA` shows
  something.

**vignette**

- [x] word of caution. general_workflow is generic and has the potential to have
  naming conflicts depending on other package vignettes loaded.

- [ ] The two vignettes seem very similar and on first glance I don't understand
  the difference. I see there are slightly different usese of function arguments
  but maybe somewhere how/why they are different.  

_genearl\_workflow_

- [ ] include Bioconductor installation instructions

- [ ] Please provide an Introduction that proides an overview of the
  package/like an abstract and also describes why the package should  be in
  Bioconductor and comparison to similar packages.

- [ ] You might consider bolding or making each step a section so its easier to
  distinguish. 

- [ ] You might consider a summary function for the results of constructNetworks
  as the output object is lengthy

_astrocyte\_map\_v2_

- [ ] While it is not run to save time the `constructNetworks` call can not be
  performed because the datExpr is not defined.  Is datExpr suppose to be the
  summarizedexperiment object?


**R code**

- [ ] apply through out but do stronger arguement checking to ensure arguments are of expected
  value from user. character vector? single value? object of class? Example:
  moduleExpressionPloe If mode can only be "PC1" or "averageZscore" that there
  should be a match.arg or some check. Apply to all scripts/functions.

- [ ] Remove commented out code.  Comments are fine but commented, unused code
  should be removed.

- [ ] `cat` and `print` should be avoided. Use `message` instead so if a user
  desires they can suppress messages/output.

**Comment by dariotommasini** [comment]
Thank you for the thorough review! These are all very good revisions that will improve the package. 

Do you think every single NOTE in the report should be addressed? For example, the line width limit of 50 characters.

**Comment by lshep** [comment]
No the stylist of line width and function length are optional

**Comment by dariotommasini** [comment]
Okay, thanks. Regarding the error: Maintainer must subscribe to the bioc-devel mailing list. Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel. I did this, but haven't heard back for a few days. Do you know how long it takes normally for the moderator to approve my subscription?

**Comment by lshep** [comment]
Have you checked your spam folder?  Sometime the validation ends up marked as spam?

**Comment by lshep** [comment]
Are the packages ready for a re-review?  When you are ready can you comment on the changes?

**Comment by dariotommasini** [comment]
No and yes. I think I can fix that last WARNING about missing /value sections in the man pages. I'll keep you posted, thanks!

**Comment by dariotommasini** [comment]
> **multiWGCNAdata**
> 
> **build report**
> 
> * [x]  Clean up report from ERROR/WARNINGS/NOTES
> * [x]  Please include in the `inst/scripts` information on how the files that
>   were uploaded to ExperimentHub were generated. The process and include any
>   relevant source and licensing information.
> 
> **multiWGCNA**
> 
> **build report**
> 
> * [x]  Clean up report from ERROR/WARNINGS/NOTES
> 
> **README**
> 
> * [x]  Include Bioconductor installation instructions
> 
> **man**
> 
> * [x]  We recommend a package level man page so that `?multiWGCNA` shows
>   something.
> 
> **vignette**
> 
> * [x]  word of caution. general_workflow is generic and has the potential to have
>   naming conflicts depending on other package vignettes loaded.
> * [x]  The two vignettes seem very similar and on first glance I don't understand
>   the difference. I see there are slightly different usese of function arguments
>   but maybe somewhere how/why they are different.
> 
> _genearl_workflow_
> 
> * [x]  include Bioconductor installation instructions
> * [x]  Please provide an Introduction that proides an overview of the
>   package/like an abstract and also describes why the package should  be in
>   Bioconductor and comparison to similar packages.
> * [x]  You might consider bolding or making each step a section so its easier to
>   distinguish.
> * [ ]  You might consider a summary function for the results of constructNetworks
>   as the output object is lengthy
> 
> _astrocyte_map_v2_
> 
> * [x]  While it is not run to save time the `constructNetworks` call can not be
>   performed because the datExpr is not defined.  Is datExpr suppose to be the
>   summarizedexperiment object?
> 
> **R code**
> 
> * [x]  apply through out but do stronger arguement checking to ensure arguments are of expected
>   value from user. character vector? single value? object of class? Example:
>   moduleExpressionPloe If mode can only be "PC1" or "averageZscore" that there
>   should be a match.arg or some check. Apply to all scripts/functions.
> * [x]  Remove commented out code.  Comments are fine but commented, unused code
>   should be removed.
> * [x]  `cat` and `print` should be avoided. Use `message` instead so if a user
>   desires they can suppress messages/output.

**Comment by dariotommasini** [comment]
The packages are ready for review. 

Comments: I have not addressed all the NOTES as some of these are style guidelines, but all ERRORS and WARNINGS have been addressed. I will definitely consider a summary function for constructNetworks output, but in the mean time I modified the show method for class WGCNA.

**Comment by dariotommasini** [comment]
Hi @lshep,

What is the status of the review?

**Comment by lshep** [comment]
Data package looks good.  Can you comment or fix the following for the software package. 

**Build Report**


- [ ] Are the suggested importFroms in R check relevant?

```
Consider adding
  importFrom("grDevices", "dev.off", "pdf", "rgb")
  importFrom("graphics", "legend")
  importFrom("stats", "IQR", "anova", "dist", "lm", "na.omit",
             "p.adjust", "phyper", "quantile", "runif", "sd", "t.test",
             "var")
  importFrom("utils", "capture.output", "head", "write.csv",
             "write.table")
to your NAMESPACE file.

```

- [ ] Can these coding notes be cleaned up?

```

* NOTE:  Avoid 'cat' and 'print' outside of 'show' methods
Found in files:
print() in R/diffModuleExpAnalysis.R (line 312, column 17)
print() in R/generalFunctions.R (line 232, column 38)
print() in R/generalFunctions.R (line 234, column 38)
print() in R/overlaps.R (line 388, column 17)
print() in R/overlaps.R (line 438, column 17)
print() in R/preservation.R (line 192, column 17)
print() in R/preservation.R (line 255, column  9)
print() in R/preservation.R (line 256, column  9)
print() in R/preservation.R (line 257, column  9)
print() in R/runWGCNA.R (line 105, column 17)
* NOTE:  Avoid the use of 'paste' in condition signals
Found in files:
R/diffModuleExpAnalysis.R (line 313, column 25)

```

- [ ] We strongly advise adding unit tests to test for internal fuctionality.

**Comment by dariotommasini** [comment]
Yes, definitely. I've added those to my NAMESPACE and I will add the unit tests as well.

I've cleaned up a few of those print statements which i had forgotten to change to message. However, some of those are printing ggplot objects. What is the best practice for a single function to print a ggplot object and return another object, like a list or data.frame?

**Comment by lshep** [comment]
print as in print to screen or save to file?  And then you want to return something else that is not a plot?

**Comment by dariotommasini** [comment]
The former: print to screen. Eg the function needs to generate a plot and also return a different object. 

For example in this stack overflow answer: https://stackoverflow.com/questions/11799317/custom-function-ggplot-and-return-values

**Comment by dariotommasini** [comment]
I've addressed those importFrom suggestions from R CMD CHECK, the code remarks, and added tests. If you're fine with having print statements for ggplot objects, then I think this version should be ready for review.

**Comment by dariotommasini** [comment]
Hi @lshep 

Hope all is well. Is there anything else you need from me?

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dariotommasini.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("multiWGCNAdata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/multiWGCNAdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dariotommasini.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("multiWGCNA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/multiWGCNA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
