### ISSUE TITLE
GloScope

### ISSUE THREAD

**Issue by wtorous** [Bioconductor/Contributions#3073]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/epurdom/GloScope

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
We first load the GloScope package and the aforementioned example dataset.

library(GloScope)
data("example_data")
The example data contains the first 50
 principal components of the subsampled cells, as well as the sample and phenotype labels associated with each cell. Note that each row of both data.frames corresponds to the same single cell.

head(example_data$pca_embeddings[,1:10])
```
Seems appropriate to use SingleCellExperiment for this example dataset?

**Comment by wtorous** [comment]
@vjcitn We agree and have refactored our package to use SingleCellExperiment objects in the vignette and ROxygen examples.

**Comment by jianhong** [comment]
# Package 'GloScope' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 5 import(BiocParallel)
	* in line 6 import(ggplot2)
## *unacceptable* files
- [ ] *unacceptable* files present (see [.gitignore](https://contributions.bioconductor.org/gitignore.html) for a listing).
	* ./vignettes/GloScope_vignette.html
## General package development
- [ ] Important: Package files exceed the 5MB size limit.
- [ ] NOTE: Consider adding these automatically suggested biocViews:
      QualityControl
- [ ] Please add scripts about how to generate the example data in `extdata` folder
- [ ] News file is not up to date

## R code
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/distMat.R:
		+ at line 126 found '    for (i in seq_len(ncol(sample_pairs))){'
	* In file R/utils.R:
		+ at line 23 found '    for ( i in seq_len(length(z))){'
- [ ] Important: Remove unused code.
	* In file R/calc_dist.R:
		+ at line 100 found '            #kl <- .KLvar(pi_1, pi_2,mu_1, mu_2, cov_1, cov_2)'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
	* In file R/distMat.R:
		+ at line 65 found '                               function(x){nrow(embedding_matrix[cell_sample_ids==x,])},integer(1))'
		+ at line 86 found '        embedding_matrix <- embedding_matrix[!(cell_sample_ids %in% knn_withheld_samples),]'
		+ at line 96 found '                                 function(x){embedding_matrix[(cell_sample_ids==x),]})'
	* In file R/plotMDS.R:
		+ at line 49 found '        metadata_df <- metadata_df[match(rownames(dist_mat), metadata_df[,sample_id]),]'
- [ ] NOTE: Try to check the edge condition when using `seq.int` or `seq_len`. For example using `seq.int(min(5, nrow(data)))` to replace `seq.int(5)`
	* In file R/calc_dens.R:
		+ at line 27 found '.calc_dens <- function(df_list, dens = c("GMM","KNN"), k = 50, num_components = seq_len(9),'
	* In file R/distMat.R:
		+ at line 46 found '                     r = 10000, num_components = seq_len(9), k = 50,'
## Documentation
- [ ] Note: Vignette should have an *Introduction* section. Rename `Overview` to `Introduction`.
	* rmd file vignettes/GlosTutorial.Rmd
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/GlosTutorial.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/GlosTutorial.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/GlosTutorial.Rmd

**Comment by wtorous** [comment]
@jianhong 

Dear Jianhong,

Thank you for your careful consideration of our package and helpful feedback.
We respond to each of your points below and have pushed an update of our package which implements your suggestions and passes the remote checks.
We have checked the boxes next to points which we believe do not need further discussion.

## The NAMESPACE file

> - [ ] Selective imports using `importFrom` instead of _import all_ with `import`.
>    - in line 5 import(BiocParallel)
>    - in line 6 import(ggplot2)

We note that after this refactor if the user wants to set parallelization options other than those given by `bpparam()` and `SerialParam()`, then they will have to explicitly use the `BiocParallel::` namespace operator. We wish to confirm that this is desirable behavior. For example, after these changes `gloscope(embedding_matrix,sample_ids,BPPARAM=SnowParam())` will raise an error and need to be replaced by `gloscope(embedding_matrix,sample_ids,BPPARAM=BiocParallel::SnowParam())`.

To use selective imports for functions from `ggplot2` in our `plotMDS()` function, we needed to add dependency on the `rlang` package and its `.data` pronoun. 

## _unacceptable_ files

> - [x] unacceptable files present (see .gitignore for a listing).
>    - ./vignettes/GloScope_vignette.html

We have removed this knit HTML vignette from the repository.

## General package development

> - [ ] Important: Package files exceed the 5MB size limit.

We are not able to recreate this issue. The largest files in our package appear to be the `.Rda` prinicpal components, which are each less than 2 MB. When running the remote Bioconductor checks, our package does not raise the file size WARNING.

> - [x] NOTE: Consider adding these automatically suggested biocViews:
>	QualityControl 

We have added this biocView to our package.

> - [x] Please add scripts about how to generate the example data in `extdata` folder

We have added a script to `inst/script` which generates a copy of the example `SingleCellExperiment` object to place in the `inst/extdata` folder. As the original data which we then subset takes several hours to download via FTP, we have added a Boolean flag in `inst/script/create_example_data.R` which the user must set to `TRUE` in order to execute the process.

> - [x] News file is not up to date

We have updated our `NEWS` file with information about our two prior pushes to Bioconductor, as well as with the content of the push which implements the changes described in this response.

## R code

> - [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.

We have verified that we use the namespace operator for all imported functions and that they match the DESCRIPTION file. We do not understand your suggestion about forcing a dependency check. Can you please clarify how to do this?

> - [x] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` functions. 
>    - In file R/distMat.R:
>        - at line 126 found ' for (i in seq_len(ncol(sample_pairs))){'
>    - In file R/utils:
>        - at line 23 found ' for ( i in seq_len(length(z))){'

We have replaced in code at line 23 with an `lappply` and the code at line 126 with an equivalent matrix operation.

> - [x] Important: Remove unused code.
>    - In file R/calc_dist.R:
>        - at line 100 found ' #kl <- .KLvar(pi_1, pi_2,mu_1, mu_2, cov_1, cov_2)'

We have removed this unused code.

> - [x] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.  
>    - In file R/distMat.R:
>        - at line 65 found ' function(x){nrow(embedding_matrix[cell_sample_ids==x,])},integer(1))'
>        - at line 86 found ' embedding_matrix <- embedding_matrix[!(cell_sample_ids %in% knn_withheld_samples),]'
>        - at line 96 found ' function(x){embedding_matrix[(cell_sample_ids==x),]})'
>    - In file R/plotMDS.R:
>        - at line 49 found ' metadata_df <- metadata_df[match(rownames(dist_mat), metadata_df[,sample_id]),]'

We agree that adding `drop=FALSE` is a safer choice and have modified each of these four lines to include that optional argument.

> - [x] NOTE: Try to check the edge condition when using `seq.int` or `seq_len`. For example using `seq.int(min(5, nrow(data)))` to replace `seq.int(5)`
>    - In file R/calc_dens.R:
>        - at line 27 found '.calc_dens <- function(df_list, dens = c("GMM","KNN"), k = 50, num_components = seq_len(9),'
>    - In file R/distMat.R:
>        - at line 46 found ' r = 10000, num_components = seq_len(9), k = 50,'

The potential edge condition which can arise in `R/calc_dens.R` occurs when a user specifies to fit more GMM components than there are cells in a sample. We have added code which checks for this, and, should it occur, both raises a warning and fits a GMM with the-number-of-cells-minus-one components instead. We have also added test cases to confirm this functionality works as expected.

We have not changed the code in `R/distMat.R` because the `num_components` optional argument is set directly by the user here, and any potential edge conditions will be caught by our edit to `R/calc_dens.R`.

## Documentation  

We have renamed our tutorial from `vignettes/GlosTutorial.Rmd` to `vignettes/GloscopeTutorial.Rmd` to match the name of our package.

> - [x] NOTE: Vignette should have an Introduction section. Rename `Overview` to `Introduction`
>    - rmd file vignettes/GlosTutorial.Rmd

We have renamed that section of our vignette.

> - [x] Important: Vignette should have an Installation section.
>    - rmd file vignettes/GlosTutorial.Rmd

We have added an `Installation` section to our vignette directly after the introduction.

> - [x] Important: Please include Bioconductor installation instructions using BiocManager.
>    - rmd file vignettes/GlosTutorial.Rmd

As note above, our new `Installation` section includes instructions for installation from Bioconductor (as if the package has been accepted).

> - [x] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
>    - rmd file vignettes/GlosTutorial.Rmd

We have added our motivation in the `Introduction` section.

**Comment by jianhong** [comment]
@wtorous Everything looks good to me. Please update your readme file with `BioManager` when you got a chance.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wtorous.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GloScope")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GloScope

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
