### ISSUE TITLE
compSPOT

### ISSUE THREAD

**Issue by sydney-grant** [Bioconductor/Contributions#3079]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sydney-grant/compSPOT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment]
Hi @sydney-grant

Thanks for submitting **compSPOT** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: There are some notes in the build report, please try to address as many of these as you can. Remember to check the **BiocCheck** section.

## DESCRIPTION file

- [ ] :green_circle: You can add line breaks to the `Description` field to make it easier to read
- [ ] :green_circle: Consider adding ORCiDs to the `Authors@R` field
- [ ] :rotating_light: The package should depend on the version of R at release

## NAMESPACE file

- [ ] :rotating_light: Function names should use `camelCase` or `snake_case` and not include `.`
- [ ] :warning: I think you can use selective imports for **{plotly}** rather than importing the whole package

## The NEWS file

- [ ] :green_circle: Remember to update the `NEWS` as you make changes


## Package data

- [ ] :green_circle: It would be helpful to have more specific names for the example data, the current names are fairly generic and may clash with other packages

## Documentation

### README

- [ ] :warning: There are some image files in the repository that I think are for the `README`. You might want to used an RMarkdown `README` instead which would make sure these are always up to date. If you decide to keep them you should make sure they are included in `.Rbuildignore` and maybe move them somewhere else in the package.

### Vignette

- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: Please add your motivation for submitting the package to Bioconductor to the *Introduction* section and comparision to similar packages (if applicable)
- [ ] :rotating_light: Please remove the `*.R` file from the `vignette/` directory
- [ ] :green_circle: I got several warnings when I displayed the plot in `group_comp[[2]]`. You might want to check if these can be avoided.

### Man pages

- [ ] :green_circle: It is recommended to have a package man page
- [ ] :green_circle: Text in the documentation section can be split over multiple lines to make it easier to read
- [ ] :green_circle: Function imports can be combined into one line like `@importFrom package function1 function2 function3...`
- [ ] :warning: Some of your functions assume particular column names, these should be clearly documented. Alternatively, you could add arguments to let users specify which columns to use.
- [ ] :warning: When are function returns a list place make that clear in the documentation and explain what the items in the list are

## Unit tests

- [ ] :warning: The unit tests are currently quite limited, please consider expanding them to cover more of the package functionality.
  - You can have several `expect_XXX` function calls within a test to check different parts of an output if needed

## Code

### R

- [ ] :rotating_light: Please use `vapply` instead of `sapply`
- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :rotating_light: There is not need to use `paste0` in `message()`, `warning()`, `stop()`
- [ ] :warning: Your package currently doesn't use any core Bioconductor packages or objects. Can you make use of any of these to increase compatibility with other Bioconductor packages?
- [ ] :rotating_light: I think most of your `for` loops could be replaced with `apply` function. Please try to do this where you can.
  - If you keep `for` loops you should pre-allocate the object for storing results rather than building it with `c()`
- [ ] :green_circle: Some of you lines are quite long, breaking this over multiple lines would make the code easier to read
- [ ] :warning: In most cases it is better to avoid nested functions, instead you can define an internal helper function
- [ ] :warning: Usually we want to separate code that performs analysis from code that visualises the results, please try to do that where you can
- [ ] :green_circle: Consider making your function names more descriptive, it wasn't obvious what they do from the name. Using verbs like `calculate_X()`, `plot_X()`, ... can help.

**Comment by sydney-grant** [comment]
Hi @lazappi I have made changes to my package based on your comments, but I am having issues getting the revised version to the bioconductor repository. I was getting a warning with BiocCheck that one of my files is over 5 MB, I am assuming this was because of the .git folder size. I pulled repository from my page (git@github.com:sydney-grant/compSPOT.git) and used git filter-repo to remove some of the unnecessary objects that are no longer included in the package. I was able to push back to my repository without issues, but I cannot push upstream to the bioconductor repository and am getting an error that updates are rejected because the pushed branch tip is behind the remote counterpart. Do you have a potential solution for how I can push the updated repo to bioconductor?

Thank you for your help,
Sydney

**Comment by lazappi** [comment]
This sounds tricky and we might need some help from the people who manage the Bioconductor git repos. The usual fix for the message about a branch being behind a remote is to do a pull from that remote first. This should make sure you have any/all commits on upstream and hopefully let your push work.

**Comment by sydney-grant** [comment]
I have tried this a few times, but even if I pull directly from the Bioconductor repo, delete a file from the .git folder and try to push back, I am getting denied. Do you know who I might be able to contact to help with this?

**Comment by lshep** [comment]
I can assist.  Can you should the commands you are trying with output?

**Comment by sydney-grant** [comment]
13156@DESKTOP-TVDQOC1 MINGW64 ~
$ cd ./Documents

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents
$ git clone git@git.bioconductor.org:packages/compSPOT.git
Cloning into 'compSPOT'...
Enter passphrase for key '/c/Users/13156/.ssh/id_rsa':
remote: Enumerating objects: 324, done.
remote: Counting objects: 100% (324/324), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 324 (delta 167), reused 270 (delta 140), pack-reused 0
Receiving objects: 100% (324/324), 2.39 MiB | 3.18 MiB/s, done.
Resolving deltas: 100% (167/167), done.

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents
$ cd ./compSPOT

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents/compSPOT (devel)
$ alias git-filter-repo='/c/Users/13156/AppData/Local/Programs/Python/Python39/Scripts/git-filter-repo'

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents/compSPOT (devel)
$ git-filter-repo --path-glob 'group.spot_output.png' --invert-paths
Parsed 80 commitsHEAD is now at d3740b4 Description Update
Enumerating objects: 323, done.
Counting objects: 100% (323/323), done.
Delta compression using up to 8 threads
Compressing objects: 100% (162/162), done.
Writing objects: 100% (323/323), done.
Total 323 (delta 168), reused 276 (delta 150), pack-reused 0

New history written in 0.47 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Completely finished after 0.89 seconds.

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents/compSPOT (devel)
$ git remote add origin git@git.bioconductor.org:packages/compSPOT.git

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents/compSPOT (devel)
$ git push --set-upstream origin devel --force
Enter passphrase for key '/c/Users/13156/.ssh/id_rsa':
Enumerating objects: 323, done.
Counting objects: 100% (323/323), done.
Delta compression using up to 8 threads
Compressing objects: 100% (144/144), done.
Writing objects: 100% (323/323), 1.27 MiB | 6.62 MiB/s, done.
Total 323 (delta 168), reused 323 (delta 168), pack-reused 0
remote: Resolving deltas: 100% (168/168), done.
remote: FATAL: + refs/heads/devel packages/compSPOT sydney-grant DENIED by fallthru
remote: error: hook declined to update refs/heads/devel
To git.bioconductor.org:packages/compSPOT.git
 ! [remote rejected] devel -> devel (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/compSPOT.git'

13156@DESKTOP-TVDQOC1 MINGW64 ~/Documents/compSPOT (devel)
$ git push --force --mirror
Enter passphrase for key '/c/Users/13156/.ssh/id_rsa':
Enumerating objects: 323, done.
Counting objects: 100% (323/323), done.
Delta compression using up to 8 threads
Compressing objects: 100% (144/144), done.
Writing objects: 100% (323/323), 1.27 MiB | 4.62 MiB/s, done.
Total 323 (delta 168), reused 323 (delta 168), pack-reused 0
remote: Resolving deltas: 100% (168/168), done.
remote: Error: You cannot push without resolving merge conflicts.
remote:
remote: Please check the files in the commit pushed to the git-server
remote: for merge conflict markers like '<<<<<<<', '========', '>>>>>>>'.
remote:
To git.bioconductor.org:packages/compSPOT.git
 ! [remote rejected] devel -> devel (pre-receive hook declined)
 ! [remote rejected] refs/replace/109bf666cae53196682058a49779db4e66c4b9c8 -> refs/replace/109bf666cae53196682058a49779db4e66c4b9c8 (pre-receive hook declined)
 ! [remote rejected] refs/replace/1921ae3548a9f0c0f3930e330bea9352c853efab -> refs/replace/1921ae3548a9f0c0f3930e330bea9352c853efab (pre-receive hook declined)
 ! [remote rejected] refs/replace/22582e3e01a111c7946aeda94736a17379c24a71 -> refs/replace/22582e3e01a111c7946aeda94736a17379c24a71 (pre-receive hook declined)
 ! [remote rejected] refs/replace/2dab3f32fe3300844fb7eda35a318c5356a7f1d9 -> refs/replace/2dab3f32fe3300844fb7eda35a318c5356a7f1d9 (pre-receive hook declined)
 ! [remote rejected] refs/replace/3707d99920bb7821c66d456c681c5c2018488cc1 -> refs/replace/3707d99920bb7821c66d456c681c5c2018488cc1 (pre-receive hook declined)
 ! [remote rejected] refs/replace/39b5ba29a61e7c311a9813c0e8f95c8b6017fcd2 -> refs/replace/39b5ba29a61e7c311a9813c0e8f95c8b6017fcd2 (pre-receive hook declined)
 ! [remote rejected] refs/replace/3e9a59352d21048f137949c66700fe7faf824848 -> refs/replace/3e9a59352d21048f137949c66700fe7faf824848 (pre-receive hook declined)
 ! [remote rejected] refs/replace/4568ae3cd9cec2aad5a2e5ed2c05c41b6908a52a -> refs/replace/4568ae3cd9cec2aad5a2e5ed2c05c41b6908a52a (pre-receive hook declined)
 ! [remote rejected] refs/replace/5312bab16641c418bd2a51ade3dab3d3c8e92605 -> refs/replace/5312bab16641c418bd2a51ade3dab3d3c8e92605 (pre-receive hook declined)
 ! [remote rejected] refs/replace/5eb8b4f3ad2191edb53d6af903bb1b4f84a74a49 -> refs/replace/5eb8b4f3ad2191edb53d6af903bb1b4f84a74a49 (pre-receive hook declined)
 ! [remote rejected] refs/replace/6275cfcf42c66fcf31347548181b6bcc8c8126f3 -> refs/replace/6275cfcf42c66fcf31347548181b6bcc8c8126f3 (pre-receive hook declined)
 ! [remote rejected] refs/replace/68192219e8600789c82d81f6b0b806a914c7fa12 -> refs/replace/68192219e8600789c82d81f6b0b806a914c7fa12 (pre-receive hook declined)
 ! [remote rejected] refs/replace/68abd1dc4f0cf440653912e302161ff02d8b57fa -> refs/replace/68abd1dc4f0cf440653912e302161ff02d8b57fa (pre-receive hook declined)
 ! [remote rejected] refs/replace/8589f7a7305e980d73702a11e11c9212484c7117 -> refs/replace/8589f7a7305e980d73702a11e11c9212484c7117 (pre-receive hook declined)
 ! [remote rejected] refs/replace/862ea8426c5ab7ac27f6bdad18b6948b002e35b4 -> refs/replace/862ea8426c5ab7ac27f6bdad18b6948b002e35b4 (pre-receive hook declined)
 ! [remote rejected] refs/replace/8c13d30d4d1f9b8de809fa24e6ab2bc6a24f1dd3 -> refs/replace/8c13d30d4d1f9b8de809fa24e6ab2bc6a24f1dd3 (pre-receive hook declined)
 ! [remote rejected] refs/replace/93a131817bbcbb8c15316e149c1efaf14065e585 -> refs/replace/93a131817bbcbb8c15316e149c1efaf14065e585 (pre-receive hook declined)
 ! [remote rejected] refs/replace/9e7d537ea09cc3b6750dc8a7b1f7730a8b6aab33 -> refs/replace/9e7d537ea09cc3b6750dc8a7b1f7730a8b6aab33 (pre-receive hook declined)
 ! [remote rejected] refs/replace/a84335386d4c3085e15542e4c5e666af34c497c7 -> refs/replace/a84335386d4c3085e15542e4c5e666af34c497c7 (pre-receive hook declined)
 ! [remote rejected] refs/replace/ab0e0df39d69e5ff3b6dfad92c38e94e1ad0a321 -> refs/replace/ab0e0df39d69e5ff3b6dfad92c38e94e1ad0a321 (pre-receive hook declined)
 ! [remote rejected] refs/replace/ac6f0460cd1b612150e2e2d7c2d1e040b45476c9 -> refs/replace/ac6f0460cd1b612150e2e2d7c2d1e040b45476c9 (pre-receive hook declined)
 ! [remote rejected] refs/replace/adf56fe4d5f11737f781710510c7e421c106e5d2 -> refs/replace/adf56fe4d5f11737f781710510c7e421c106e5d2 (pre-receive hook declined)
 ! [remote rejected] refs/replace/bf4eff0844a679469af75e131b037b9a1ae61a2a -> refs/replace/bf4eff0844a679469af75e131b037b9a1ae61a2a (pre-receive hook declined)
 ! [remote rejected] refs/replace/df2942d830b7ce2f7db2948417fade45ff6e474d -> refs/replace/df2942d830b7ce2f7db2948417fade45ff6e474d (pre-receive hook declined)
 ! [remote rejected] refs/replace/e022cd3e90365673e2e58913cdb60ec0fe52c664 -> refs/replace/e022cd3e90365673e2e58913cdb60ec0fe52c664 (pre-receive hook declined)
 ! [remote rejected] refs/replace/e0dc8a1b58f0c1852f59d67646a949b7dc7434fd -> refs/replace/e0dc8a1b58f0c1852f59d67646a949b7dc7434fd (pre-receive hook declined)
 ! [remote rejected] refs/replace/f475973ba54c591f72581e87a00459ce69ae43d4 -> refs/replace/f475973ba54c591f72581e87a00459ce69ae43d4 (pre-receive hook declined)
 ! [remote rejected] refs/replace/fd7c82c26fc4a9c82b0e73cd41133aed05ee44fa -> refs/replace/fd7c82c26fc4a9c82b0e73cd41133aed05ee44fa (pre-receive hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/compSPOT.git'

**Comment by lshep** [comment]
You said you were able to update your github repo?  We do not allow force pushes to git.bioconductor.org. So the best option will probably be to delete and reset the repository on git.bioconductor.org to your github if your github is now clean.

**Comment by sydney-grant** [comment]
Yes, I have been able to force push to my own github repo

**Comment by lshep** [comment]
ok.  Is it okay if I reset our git.bioconductor.org repo with your github then?   I can work on it shortly. Don't be alarmed if I put the `pre check passed` label back on;  it will just allow me to do it automatically instead of manually.

**Comment by sydney-grant** [comment]
That is fine with me - thank you!

**Comment by lshep** [comment]
Ok. it has been reset on our system.  Cheers

**Comment by sydney-grant** [comment]
I am still getting the warning that I have a file in the repo over 5 MB, I am not sure what file this is referring to. None of my files appear to be over this limit and the entire package is 1.4M. Is there something I am missing here?

SY43548@85SG1S2 MINGW64 //cellstress/csb$/CSBLabParagh/Sydney/compSPOT (main)
$ du -h
64K     ./.git/hooks
4.0K    ./.git/info
4.0K    ./.git/logs/refs/heads
8.0K    ./.git/logs/refs/remotes/origin
4.0K    ./.git/logs/refs/remotes/upstream
12K     ./.git/logs/refs/remotes
16K     ./.git/logs/refs
20K     ./.git/logs
4.0K    ./.git/objects/00
4.0K    ./.git/objects/21
4.0K    ./.git/objects/f6
0       ./.git/objects/info
736K    ./.git/objects/pack
748K    ./.git/objects
1.0K    ./.git/refs/heads
2.0K    ./.git/refs/remotes/origin
1.0K    ./.git/refs/remotes/upstream
3.0K    ./.git/refs/remotes
0       ./.git/refs/tags
4.0K    ./.git/refs
863K    ./.git
208K    ./data
24K     ./man
48K     ./R
160K    ./README_Images
16K     ./tests/testthat
20K     ./tests
16K     ./vignettes
1.4M    .

**Comment by lazappi** [comment]
I think this is being run on the built package which includes the built vignette etc. You can try running `R CMD build` on your package directory and seeing what the size of the built `.tar.gz` file is.

**Comment by sydney-grant** [comment]
Hi @lazappi, thank you for your patience and for taking the time to review my package. Below are the tasks I have addressed and comments on how I have addressed them.
> 
> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [x]  ⚠️ There are some notes in the build report, please try to address as many of these as you can. Remember to check the **BiocCheck** section.
> •	As many remaining notes from BiocCheck as possible were addressed.
> ## DESCRIPTION file
> * [x]  🟢 You can add line breaks to the `Description` field to make it easier to read
•	Breaks have been added to description field to make this more readable.
> * [x]  🟢 Consider adding ORCiDs to the `Authors@R` field
•	ORCiD IDs have been added to authors who have them.
> * [x]  🚨 The package should depend on the version of R at release
> 
> ## NAMESPACE file
> * [x]  🚨 Function names should use `camelCase` or `snake_case` and not include `.`
> * [x]  ⚠️ I think you can use selective imports for **{plotly}** rather than importing the whole package
> •	Version dependency has been added to description file
> ## The NEWS file
> * [x]  🟢 Remember to update the `NEWS` as you make changes
> 
> ## Package data
> * [x]  🟢 It would be helpful to have more specific names for the example data, the current names are fairly generic and may clash with other packages
> •	Names for two example datasets has been updated.
> ## Documentation
> ### README
> * [x]  ⚠️ There are some image files in the repository that I think are for the `README`. You might want to used an RMarkdown `README` instead which would make sure these are always up to date. If you decide to keep them you should make sure they are included in `.Rbuildignore` and maybe move them somewhere else in the package.
> •	Images have been removed.
> ### Vignette
> * [x]  🚨 Please add a table of contents
> * [x]  🚨 Please add your motivation for submitting the package to Bioconductor to the _Introduction_ section and comparision to similar packages (if applicable)
•	Rationale for adding compSPOT to Bioconductor and suggestions of additional Bioconductor packages to use along with compSPOT has been added to introduction.
> * [x]  🚨 Please remove the `*.R` file from the `vignette/` directory
> * [x]  🟢 I got several warnings when I displayed the plot in `group_comp[[2]]`. You might want to check if these can be avoided.
•	Changes have been made to code for data visualization sections – there are no longer warning messages.
> 
> ### Man pages
> * [x]  🟢 It is recommended to have a package man page
•	Man page has been added.
> * [x]  🟢 Text in the documentation section can be split over multiple lines to make it easier to read
•	Code lines and lines in documentation sections have been reformatted.
> * [x]  🟢 Function imports can be combined into one line like `@importFrom package function1 function2 function3...`
•	This change has been made in all man pages.
> * [x]  ⚠️ Some of your functions assume particular column names, these should be clearly documented. Alternatively, you could add arguments to let users specify which columns to use.
> * [x]  ⚠️ When are function returns a list place make that clear in the documentation and explain what the items in the list are
> •	More detailed documentation has been added to .R and man files for main functions. 
> ## Unit tests
> * [x]  ⚠️ The unit tests are currently quite limited, please consider expanding them to cover more of the package functionality.
>  
>   * You can have several `expect_XXX` function calls within a test to check different parts of an output if needed
>  •	Additional unit tests have been added for each main package function.
> ## Code
> ### R
> * [x]  🚨 Please use `vapply` instead of `sapply`
> * [x]  🚨 Please use `seq_along()`/`seq_len()` instead of `1:...`
> * [x]  🚨 There is not need to use `paste0` in `message()`, `warning()`, `stop()`
> * [ ]  ⚠️ Your package currently doesn't use any core Bioconductor packages or objects. Can you make use of any of these to increase compatibility with other Bioconductor packages?
•	At this time, I do not see any areas to easily implement any core Bioconductor packages. Description of how compSPOT may be used in combination with other Bioconductor packages such as RTCGA packages and seq.hotSPOT has been added to vignette.
> * [x]  🚨 I think most of your `for` loops could be replaced with `apply` function. Please try to do this where you can.
>   
>   * If you keep `for` loops you should pre-allocate the object for storing results rather than building it with `c()`
•	All large for loops in main functions have been rewritten using helper functions and apply functions.
> * [x]  🟢 Some of you lines are quite long, breaking this over multiple lines would make the code easier to read
•	Code has been reformatted.
> * [x]  ⚠️ In most cases it is better to avoid nested functions, instead you can define an internal helper function
•	Majority of nested functions have been separated from main function to serve as internal helper functions.
> * [x]  ⚠️ Usually we want to separate code that performs analysis from code that visualises the results, please try to do that where you can
•	More internal helper functions have been written for data visualization to be separated from those for analysis purposes.
> * [x]  🟢 Consider making your function names more descriptive, it wasn't obvious what they do from the name. Using verbs like `calculate_X()`, `plot_X()`, ... can help.
•	The names of most functions have been changes to be more descriptive of their purpose.

**Comment by lazappi** [comment]
> > * [x]   🚨 Please add a table of contents

This works but maybe just check it looks how you would expect. At the moment everything is under one heading.

> > * [x]   ⚠️ The unit tests are currently quite limited, please consider expanding them to cover more of the package functionality.
> >   
> >   * You can have several `expect_XXX` function calls within a test to check different parts of an output if needed
> >     •	Additional unit tests have been added for each main package function.

This is better, but generally you want as much code as possible inside the `test_that()` functions (I think **{testthat}** complains if anything is outside). You can also make more use of the `expect_X()` functions rather than using `if` statements. So instead of :

```r
if (nrow(comp_test[[1]]) <= length(unique(hotspots$Label))){
  output <- TRUE
}
if (nrow(comp_test[[1]]) > length(unique(hotspots$Label))){
  output <- FALSE
}

test_that("check number significant spots", {
  expect_true(output)
})
```

Something like:

```r
test_that("number of significant spots is correct", {
	expect_true(nrow(comp_test[[1]]) <= length(unique(hotspots$Label)))
}
```

There are a range of `expect_X()` functions you can use for different things so in most cases you don't have to check things manually.

> > * [x]   🚨 I think most of your `for` loops could be replaced with `apply` function. Please try to do this where you can.
> >   
> >   * If you keep `for` loops you should pre-allocate the object for storing results rather than building it with `c()`
> >     •	All large for loops in main functions have been rewritten using helper functions and apply functions.

The remaining loops are mostly ok but `spot_rank()` still builds a `data.frame` one row at a time.

> > * [x]   ⚠️ Usually we want to separate code that performs analysis from code that visualises the results, please try to do that where you can
> >   •	More internal helper functions have been written for data visualization to be separated from those for analysis purposes.

This is ok but I would prefer more separation, so separate functions for doing a comparison and plotting the results rather than a combined function like `compare_groups()`. This is a bit of a personal preference though so up to you if you do that or keep it this way.

Other minor comments:

- Be careful using "graph" instead of "plot" (like in the `plot_features()` documentation). It took me a while to work out it was returning a plot rather than a graph with nodes and edges. I usually say "`ggplot`object" to refer to the plot objects created by **{ggplot2}**
- You can define lists using `list(item1, item2, ...)` rather than `x <- c(); x[[1]] <- item1; x[[2]] <- item2, ...`

**Comment by sydney-grant** [comment]
> > > * [x]    🚨 Please add a table of contents
> 
> This works but maybe just check it looks how you would expect. At the moment everything is under one heading.
> **TOC has been reformatted.**
> 
> > > * [x]    ⚠️ The unit tests are currently quite limited, please consider expanding them to cover more of the package functionality.
> > >   
> > >   * You can have several `expect_XXX` function calls within a test to check different parts of an output if needed
> > >     •	Additional unit tests have been added for each main package function.
> 
> This is better, but generally you want as much code as possible inside the `test_that()` functions (I think **{testthat}** complains if anything is outside). You can also make more use of the `expect_X()` functions rather than using `if` statements. So instead of :
> 
> ```r
> if (nrow(comp_test[[1]]) <= length(unique(hotspots$Label))){
>   output <- TRUE
> }
> if (nrow(comp_test[[1]]) > length(unique(hotspots$Label))){
>   output <- FALSE
> }
> 
> test_that("check number significant spots", {
>   expect_true(output)
> })
> ```
> 
> Something like:
> 
> ```r
> test_that("number of significant spots is correct", {
> 	expect_true(nrow(comp_test[[1]]) <= length(unique(hotspots$Label)))
> }
> ```
> 
> There are a range of `expect_X()` functions you can use for different things so in most cases you don't have to check things manually.
> 
> **More of the code has been included within the testthat functions when possible.**
>
> > > * [x]    🚨 I think most of your `for` loops could be replaced with `apply` function. Please try to do this where you can.
> > >   
> > >   * If you keep `for` loops you should pre-allocate the object for storing results rather than building it with `c()`
> > >     •	All large for loops in main functions have been rewritten using helper functions and apply functions.
> 
> The remaining loops are mostly ok but `spot_rank()` still builds a `data.frame` one row at a time.
> 
> **spot_rank function has been revised to not have a for loop**
>
> > > * [x]    ⚠️ Usually we want to separate code that performs analysis from code that visualises the results, please try to do that where you can
> > >   •	More internal helper functions have been written for data visualization to be separated from those for analysis purposes.
> 
> This is ok but I would prefer more separation, so separate functions for doing a comparison and plotting the results rather than a combined function like `compare_groups()`. This is a bit of a personal preference though so up to you if you do that or keep it this way.
> 
> **I would prefer to keep the function as is for now.**
>
> Other minor comments:
> 
> * Be careful using "graph" instead of "plot" (like in the `plot_features()` documentation). It took me a while to work out it was returning a plot rather than a graph with nodes and edges. I usually say "`ggplot`object" to refer to the plot objects created by **{ggplot2}**
>
> **text has been adjusted accordingly**
>
> * You can define lists using `list(item1, item2, ...)` rather than `x <- c(); x[[1]] <- item1; x[[2]] <- item2, ...`
>
> **code has been adjusted accordingly**

**Comment by lazappi** [comment]
Thanks for your work responding to my comments, I am happy to accept the package now. Congratulations on getting **{compSPOT}** into Bioconductor 🎉! It can take a couple of days to be picked up by the build system but then it should be part of Bioconductor devel.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sydney-grant.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("compSPOT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/compSPOT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
