### ISSUE TITLE
Submit CytoPipelineGUI package

### ISSUE THREAD

**Issue by phauchamps** [Bioconductor/Contributions#3081]
Preliminary NOTE: this new candidate package is a 'companion' package of `CytoPipeline` (already on Bioconductor).
It implements two shiny applications that :
- read data stored on a disk cache that was created by a preliminary pipeline run with `CytoPipeline`
- make use of plotting functionalities implemented in `CytoPipeline` and expose them in a user interactive fashion

- Repository: https://github.com/UCLouvain-CBIO/CytoPipelineGUI

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Sorry for the delay; I was away on holiday. I should have a review for you by the end of the week.

**Comment by lshep** [comment]
Thanks for the submission please see following comments: 

**man**

- [ ] We suggest having a package level man page so that something appears for
  the naive user doing `?CytoPipelineGUI` perhaps describing what appears to be
  the two differnt apps that can be run ScaleTransformApp and
  CytoPipelineCheckApp or how to get started.
   

- [ ] Instead of commenting out the piece of code that launches the app, we
  generally recommend placing it in an `if(interactive()){}`. So that users
  would still be able to copy and paste man page examples directly into a
  browser and have them run.  

**vignette**

- [ ] I'm slightly concerned with no runnable code in the vignette and man
  pages an minimal testing code how can you ensure the package is working
  properly and without error?

- [ ] At the very least I would have a quick start section on how to launch the
  app in the vignette without having to watch a video.

- [ ] Based on the man pages it looks like there are two different apps tha can
  be launched ScaleTransformApp and  CytoPipelineCheckApp so it would be good to
  have a section without having to play a video that describes what these do. 

Cheers,

**Comment by phauchamps** [comment]
Hi Lori,

Thanks for your comments! 
I'll update the package according to your suggestions, in the coming days. I'll let you know when this is done.

Cheers,

Philippe

**Comment by phauchamps** [comment]
Hi Lori,

I have just pushed a new version 0.99.1 of the package, with some updates regarding man pages and vignette, according to your suggestions.
Now, I created a specific vignette (apart from the video links that are still availale in another `Demo.rmd` vignette), with some minimal introduction, content and also briefly demonstrating some of the functions that are also called in the shiny apps. 

Let me know if these updates are good enough to address your valid concerns :-)

Cheers,

Philippe

**Comment by lshep** [comment]
Yes I would be comfortable accepting now.  One last note:  We do have a biocView  for shiny applications  `ShinyApps`  if you wouldn't mind adding to the biocViews of the DESCRIPTION.

**Comment by phauchamps** [comment]
OK to add `ShinyApps` as additional biocView !

**Comment by lshep** [comment]
This is ok and the change is reflected in Bioconductor. thank you.  I will process the package into the official Bioconductor repo later this week.

**Comment by phauchamps** [comment]
ok, so no need to worry about the error message ? :-)

**Comment by lshep** [comment]
Nope.  Just saying you won't get the auto build on your last push cause its already accepted and will display when its on the daily builder.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/phauchamps.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CytoPipelineGUI")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CytoPipelineGUI

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
