### ISSUE TITLE
semisup

### ISSUE THREAD

**Issue by rauschenberger** [Bioconductor/Contributions#309]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rauschenberger/semisup

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@hpages will review this package, but I note that it makes no use of other Bioconductor packages, including standard ways of representing genomic coordinates (GRanges from the GenomicRanges package) and experimental data (SummarizedExperiment class and package). Please update your package to work with these objects, so that Bioconductor users may more easily and robustly interoperate with your package.

**Comment by mtmorgan** [comment]
# 18 March, 2017

DESCRIPTION

- please provide a more comprehensive Description: like a paper abstract, indicating how your package provides unique functionality, and how it differs from similar offerings.

- There are no Bioconductor packages listed in the Depends / Imports / Suggests. Dependencies imply interoperability and re-use, both of which benefit end users. It seems like the GenomicRanges and SummarizedExperiment packages are relevant. Please support these packages as inputs to and outputs from your API.

NAMESPACE

- Do not export functions intended solely for internal use, e.g,. debug.mixtura

vignettes

- Good

- Do include vignette products (pdf, tex,log, out, ...) in repository.

man

- do not be too clever in introducing markup into the man pages. For instance, in the text version of the mixtura man page the argument y appears with a confusing collection of '*':

        y: *observations**:* numeric vector of length 'n'

R

- avoid `1:p` when generating sequences, use `seq_len(p)` or `seq_along(x)`.

- Consider using BiocParallel instead of parallel, so that Bioconductor users are exposed to a single parallel processing paradigm.

- vectorize where possible, e.g., functions.R:172

        raw <- apply(null,1,function(x) sum(x>=x[1])/perm)
    
  becomes
  
        raw <- rowSums(null > null[,1]) / perm

- avoid 'copy-and-append' functions.R:474

        trial <- list()
        for(i in 1:starts){
            trial[[i]] <-...
            
  in favor of pre-allocate and fill
  
        trial <- vector("list", starts)
        ...
        
  or simply use `lapply()` or `replicate()`. Since the distribution does not change during the iteration, 'hoist' this from the loop
  
        if (dist == "norm")
            trial <- replicate(starts, intern.norm(y,  z, it.em, epsilon))
        else ...

**Comment by rauschenberger** [comment]
Thanks @mtmorgan for reviewing the R package semisup.


DESCRIPTION

- The description has been made more comprehensive.

- The function scrutor now accepts objects of class SummarizedExperiment.

NAMESPACE

- The internal function debug (before: debug.mixtura) has been removed from the namespace. All other internal functions have only been removed from the package index, as they might be of interest for developers.

vignettes

- All vignette products have been removed. Now the vignettes folder only contains the files semisup.Rnw and semisup.bib.

man

- The redundant asterisks have been deleted.

R

- Now the colon operator is only used in the examples. Sequence generation by 1:p has been replaced by seq_len(p) and seq_along(x). 

- Parallel processing has been deactivated, because it lead to memory problems under Windows. BiocParallel will be supported at a later stage.

- Vectorisation has been used where possible.

- The function fit.wrap (before: intern.wrap) now uses lapply instead of a for loop.

**Comment by mtmorgan** [comment]
Thank you for your changes; I am happy to accept the package. It will be added to the Bioconductor svn repository and nightly builds, with additional information by email in the next several days.
