### ISSUE TITLE
scMitoMut: single cell mitochondrial mutation calling tool

### ISSUE THREAD

**Issue by wenjie1991** [Bioconductor/Contributions#3095]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wenjie1991/scMitoMut

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ococrook** [comment]
Hi, sorry for the delay in the review! This will be completed in the next dew days!

**Comment by wenjie1991** [comment]
Hi Oliver, no need to worry. There's no rush.

**Comment by ococrook** [comment]
Looks good! Thanks for the submission, just a couple of things, but the package is great otherwise

- [ ] update the R dependency to 4.3
- [ ] remove code that has been commented out
- [ ] check that argument function provide by the user are correct (especially if not resonable defaults)
- [ ] Update the news.md (currently it is empty)
- [ ] add Bioconductor install instruction (eval = FALSE in vignette)
- [ ] please check for user interrupts in the c++ code (probably in the main function somewhere)
- [ ] The package description could be expanded
- [ ] biocviews: SingleCell might be appropriate?
- [ ] I think your ORCID isnt formatted correctly
- [ ] line 54 in 'io.R' avoid 1:length(x) use seq_len(length(x)) etc, similar elswhere
- [ ] To remove the makevars warning check here: https://stackoverflow.com/questions/76360902/checking-for-gnu-extensions-in-makefiles-warning#:~:text=%E2%9D%AF%20checking%20for%20GNU%20extensions,'Writing%20R%20Extensions'%20manual.
- [ ] Any chance you could remove the `no visible bindings ...` notes

**Comment by wenjie1991** [comment]
Thank you for reviewing the submission. I'm glad to hear that overall, the package looks great. I appreciate your feedback and would be happy to address any concerns or make necessary adjustments.

**Comment by lshep** [comment]
@wenjie1991  the deadline for new submission acceptance for the Bioc 3.18 release is this week. Please pushed changes addressing the above issues.

**Comment by wenjie1991** [comment]
Hello @lshep,
Thank you for the reminder. I'm currently jammed by other tasks and will resume the submission process next week.
If it's not feasible to release with Bioc 3.18, I am also comfortable waiting until 3.20 ;-)

**Comment by wenjie1991** [comment]
Hi @ococrook,

Thank you for your comments once again. I have made some changes:

* update the R dependency to 4.3
    * Done.
* remove code that has been commented out
    * Done. I still have a few remaining as I intend to activate them in the future. I believe this will not compromise the quality of the package.
* check that argument function provide by the user are correct (especially if not resonable defaults)
    * Done. I carefully make checkers for almost all parameters of exported functions.
* Update the news.md (currently it is empty)
    * Done. 
* add Bioconductor install instruction (eval = FALSE in vignette)
    * Done.
* please check for user interrupts in the c++ code (probably in the main function somewhere)
    * The model fitting subroutine now includes a user interrupt.
* The package description could be expanded
    * Done. I added more info in description
* biocviews: SingleCell might be appropriate?
    * Thanks for this suggestion! I updated the biocviews tags.
* I think your ORCID isnt formatted correctly
    * Thank you for pointing out the issue. I have added the correct ORCID and included my supervisor as a co-author.
* line 54 in 'io.R' avoid 1:length(x) use seq_len(length(x)) etc, similar elswhere
    * Yes, all “1:length” cases have been replaced with seq_len or seq_along.
* To remove the makevars warning check here: https://stackoverflow.com/questions/76360902/checking-for-gnu-extensions-in-makefiles-warning#:~:text=%E2%9D%AF%20checking%20for%20GNU%20extensions,'Writing%20R%20Extensions'%20manual.
    * It's brilliant idea and it works like magic.
* Any chance you could remove the no visible bindings ... notes
    * The issue arises from using data.table. When a variable is used in the data table, it is identified as "no visible bindings". I believe this does not cause any harm.

**Comment by ococrook** [comment]
Thanks!

Final comment is that the README.md should indicate its a bioconductor package, how to make issues and how to contribute to the package (if you're open to that).

Then we can move to accept tha package.

best wishes,
Olly

**Comment by wenjie1991** [comment]
@ococrook Thank you for your suggestions; they prompted me to consider aspects I hadn't previously thought of.

The following changes have been implemented:
1. A GitHub issue link has been added to the DESCRIPTION file.
2. An announcement that scMitoMut is an R/Bioconductor package has been included in the README.
3. A contribution section has been created to explicitly encourage contributions from the community.

Wenjie

**Comment by ococrook** [comment]
Sorry for the delay can you add that the bioconductor install instructions to the .readme ?

**Comment by wenjie1991** [comment]
The  bioconductor install instructions have been added to the readme.

Surprisingly, the updated package got error in macOS platform. I guess it is not scMitoMut package issue for the Error in the Bioconductor Single Package Builder report above.
Since the error is about the dependencies in macOS platform and scMitoMut package has passed the biocCheck in [Github Action](https://github.com/wenjie1991/scMitoMut/actions/runs/7561253129).
I will bump version and try it again in another day.

**Comment by wenjie1991** [comment]
The error may stem from the absence of a binary package for R-devel on the macOS platform, as described here: https://contributions.bioconductor.org/troubleshooting-build-report.html#cran-binaries-not-available-for-r-4.0

Anyway, I am not sure.

**Comment by lshep** [comment]
yes this is true.  some mac binaries are not available yet as they have not been made for r-devel yet.  We can ignore the mac error for now.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wenjie1991.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scMitoMut")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scMitoMut

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
