### ISSUE TITLE
CytoMethIC

### ISSUE THREAD

**Issue by jfanale26** [Bioconductor/Contributions#3097]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhou-lab/CytoMethIC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
There are numerous references to "askMe". Like in the vignette.  `'askMe' package` .  Please correct these.  

We recommend renaming your vignette to the package name rather than something common and not unique like quickstart as there could be naming conflicts with other packages loaded in a user environment.  The vignette does not meet the conditions of the contributions guidelines. Please explain the use of the tool and its relationship to Bioconductor. Try to imagine a newcomer to your package who needs to get the flavor of it, and who can be inspired to try it out by what you write.

Please provide test relevant to your package code not that the download from the dependent package works correctly. 

Any data provided in `inst/extdata` should have an associated file in `inst/scripts` describing its creation.  It looks like this might be an experiment data package?  You should have a script that describes how the files that were uploaded to Azure were generated as well. 

You export both cmi_classify_rda and cmi_classify but I only see runnable example code for cmi_classify?

**Comment by lshep** [comment]
@jfanale26 any responses on the above?

**Comment by jfanale26** [comment]
Sorry about the delayed response. All of these issues should be fixed now- let me know what else needs to be done.

**Comment by jfanale26** [comment]
Just following up on this, as the deadline for review completion is in 2 days @lshep

**Comment by lshep** [comment]
I will process this into git.bioconductor.org so that we can proceed in the review process however there is still not a description in inst/scripts that describes how the objects uploaded to the hub were created with any relevant source information.   It would also be helpful to provide more text on what is occurring and how it is significant in each of your vignette sections.

**Comment by jfanale26** [comment]
All described issues have been addressed, and the only remaining error is "Maintainer must subscribe to the bioc-devel mailing list", though I am subscribed to this mailing list with the email in the DESCRIPTION file. Let me know how I should proceed from here. @lshep

**Comment by jianhong** [comment]
Please bump the version number and remove the error tag first.

**Comment by jianhong** [comment]
Could you fix the warnings?

**Comment by jianhong** [comment]
Should I expect any updates soon?

**Comment by jfanale26** [comment]
Sorry, I have been extremely busy with exams and classes lately. I have been trying to fix the "package is over 5MB" warning, but I don't get this warning on my local computer, only when I update the version and push to Bioconductor. Will update you as I make progress.

**Comment by jfanale26** [comment]
@jianhong We have been getting a warning when built on the Bioconductor system, but this warning does not show up on local builds (tested on multiple machines). Is this a common issue/how would we troubleshoot this problem?

**Comment by jianhong** [comment]
# Package 'CytoMethIC' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## The DESCRIPTION file
- [ ] NOTE: Provide 'URL', 'BugReports' field(s) in DESCRIPTION
- [ ] NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R'
      with 'comment=c(ORCID="...")'
## The NAMESPACE file
- [ ] Important: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 8 import(randomForest)

## R code
- [ ] Important:`is()` or `inherits()` instead of `class()`.
	* In file R/cytomethic.R:
		+ at line 100 found '  if (grepl("randomForest", class(cmi_model[["model"]])[1])) {'
		+ at line 109 found '  } else if (grepl("svm", class(cmi_model[["model"]])[1])) {'
		+ at line 118 found '  } else if (grepl("xgb", class(model)[1])) {'
		+ at line 126 found '    num_classes <- length(pred_probabilities)'
		+ at line 127 found '    pred_prob_matrix <- matrix(pred_probabilities, nrow = 1, ncol = num_classes, byrow = TRUE)'
		+ at line 131 found '  } else if (grepl("keras", class(model)[1])) {'
- [ ] Important: `warning`, `message`, `stop` instead of `cat` and `print` outside of `show` methods.
	* In file R/cytomethic.R:
		+ at line 60 found '      if(is.na(df[1, i])) print(colnames(df)[[i]])'
		+ at line 66 found '      if(is.na(df[1, i])) print(colnames(df)[[i]])'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
	* In file R/cytomethic.R:
		+ at line 96 found '    cmi_model <- list(model = keras::unserialize_model(cmi_model[["model_serialized"]]),'
		+ at line 108 found '    tibble::tibble(response = names(res)[1], prob = res[1])'
		+ at line 117 found '    tibble::tibble(response = as.character(res), prob = prob_max)'
		+ at line 124 found '    betas <- xgboost::xgb.DMatrix(t(as.matrix(betas)))'
		+ at line 130 found '    tibble::tibble(response = pred_label, prob = max_probability)'
		+ at line 141 found '    tibble::tibble(response = pred_label, prob = max_probability)'
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/cytomethic.R:
		+ at line 37 found '    for (i in seq_len(ncol(df))) {'
		+ at line 41 found '    for (i in seq_len(nrow(df))){'
		+ at line 59 found '    for (i in seq_len(length(colnames(df)))) {'
		+ at line 65 found '    for (i in seq_len(length(colnames(df)))) {'

## Documentation
- [ ] Note: Vignette should use `BiocStyle` package for formatting.
	* rmd file vignettes/CytoMethIC.Rmd
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/CytoMethIC.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/CytoMethIC.Rmd
- [ ] Important: First time to load sesameData need to run `sesameDataCache()`, otherwise error:

| File HM450.1.TCGA.PAAD needs to be cached to be used in sesame.
| Please make sure you have updated ExperimentHub and try
| > sesameDataCache()
| to retrieve and cache needed sesame data.
--- failed re-building ‘CytoMethIC.Rmd’

**Comment by jianhong** [comment]
Should I expect any updates soon?

**Comment by jfanale26** [comment]
Hi, I made many of the changes you suggested, but adding an Installation section raised an error during build. The installation code in  vignettes/CytoMethIC.rmd is as follows: 
![image](https://github.com/Bioconductor/Contributions/assets/65561585/0d813328-2547-4609-9c87-0ca03e3b7508)
The error is as follows: 
`* Checking vignette directory...
    * ERROR: Installation calls found in vignette(s)`
Is there another way I should write the installation section?

**Comment by jianhong** [comment]
Please set `eval=FALSE` after or among `r, message=FALSE...`

**Comment by jianhong** [comment]
Should I expect any updates soon?

**Comment by jfanale26** [comment]
> Should I expect any updates soon?

We are finished with the requested modifications, please let us know what else should be done @jianhong

**Comment by jianhong** [comment]
@jfanale26 Thanks for the updates. Could you please fix the file size warning?

**Comment by jfanale26** [comment]
@jianhong The warning should be fixed, let me know what our next steps are.

**Comment by jianhong** [comment]
# Package 'CytoMethIC' Review
Amost there. There are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## General package development
- [ ] Important: NEWS file is not updated and the content is not correlated with the update of the package.

## R code
- [ ] Important: input validation are not fully covered. For example, `betas` in function `cmi_classify`. Should that must be a matrix? And there is no input check for `impute_mean` function.

## Documentation
- [ ] Note: Vignette should use `BiocStyle` package for formatting.
	* rmd file vignettes/CytoMethIC.Rmd

**Comment by jfanale26** [comment]
Thank you for the speedy review, @jianhong. We have amended all of the comments you made:

> Important: NEWS file is not updated

We have added the most recent build to NEWS. 

> Important: input validation are not fully covered.

We have added input validation for the `cmi_classify` function, see lines 112-118 of [CytoMethIC.R](https://github.com/zhou-lab/CytoMethIC/blob/devel/R/cytomethic.R). Please note that the `impute_mean` function has been removed, as the updated function no longer uses it. 

> Note: Vignette should use BiocStyle package for formatting.

We have changed the output of the Rmd file to `BiocStyle::html_document`. See lines 4-6 of [CytoMethIC.Rmd](https://github.com/zhou-lab/CytoMethIC/blob/devel/vignettes/CytoMethIC.Rmd).

Please let us know what else needs to be done.

**Comment by jianhong** [comment]
The new function `cmi_checkVersion`. You may want to simply the function by something like:

```
rv <- R.Version()
message(
        "CytoMethIC requires matched versions of ",
        "R, sesame, sesameData and ExperimentHub.\n",
        "Here is the current versions installed:\n",
         "Bioconductor: ", version(), "\n",
        "CytoMethIC: ", packageVersion("CytoMethIC"), "\n",
        "sesame: ", packageVersion("sesame"), "\n",
        "sesameData: ", packageVersion("sesameData"), "\n",
        "ExperimentHub: ", packageVersion("ExperimentHub"), "\n"
)
```

**Comment by jianhong** [comment]
Also, please double check your documentations. There are some minor typos.

**Comment by jfanale26** [comment]
@jianhong we have fixed cmi_checkVersion and proofread for typos. Let us know what else should be done.

**Comment by jianhong** [comment]
Please always update your NEWS file to the newest updates once you changed anything.

**Comment by jfanale26** [comment]
Pushed NEWS file update, but did not build on system.  @jianhong

**Comment by jianhong** [comment]
@jfanale26 I will make it as accepted now. Certainly, we kindly request that you remember to update your NEWS file whenever you make any changes. Your attention to this matter is greatly appreciated.

**Comment by jfanale26** [comment]
@jianhong, thank you so much for all of the help in getting this package ready for release! We will be sure to update NEWS as we make changes.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jfanale26.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CytoMethIC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CytoMethIC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
