### ISSUE TITLE
Rvisdiff

### ISSUE THREAD

**Issue by BioinfoUSAL** [Bioconductor/Contributions#3102]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BioinfoUSAL/Rvisdiff

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  The vignette does not meet the conditions of the contributions guidelines.  Please explain the use of the tool and its relationship to Bioconductor.  Try to imagine a newcomer to your package who needs to get the flavor of it, and who can be inspired to try it out by what you write.

**Comment by BioinfoUSAL** [comment]
We have updated the vignette with a new description and detailed examples of use. It shows the connection with Differential Expression packages of bioconductor and explains the main features of the package.

**Comment by lshep** [comment]
The current Bioconductor builders only support R 4.3;  is R 4.4 a necessary requirement as it is not scheduled to be release by CRAN until next Spring?  Our devel builder will not have R 4.4 until after the October Bioconductor release.

**Comment by BioinfoUSAL** [comment]
Thanks for the comment, the package supports older R versions. R dependency has been updated to 4.3.0.

**Comment by lshep** [comment]
Can you please follow the instructions for pushing to git.bioconductor.org to trigger a new build report.  See [previous post](https://github.com/Bioconductor/Contributions/issues/3102#issuecomment-1728272703)

**Comment by HelenaLC** [comment]
# code

- [ ] I see quite a few checks on the input data, however, these should be tested more thoroughly (see also comment below). E.g., running the `DEreport` example and setting `names(dr)[6] <- "padjj"` already breaks the volcano and MA plot. Implementing a proper validity check on what `edgeR/DESeq2/limma` outputs would look like should catch this, and perhaps provide the user with an informative message on what's wrong/how to fix it.

- [ ] Complementary to the above, it might be helpful to expose some key arguments to the user, e.g., to let users provide the names of columns containing (adjusted) p-values etc.

- [ ] File/directory paths should be constructed using `file.path()` as opposed to `paste0(..., "/...")` to be OS-agnostic, e.g., in `createHTML()`.

# documentation

- [ ] Consider adding a package help-(*man*-)page (to be viewed via `?Rvisdiff`) summarizing the packages functionality.

- [ ] In the vignette, consider using `BiocStyle` functions to hyperlink external packages in order to direct users to these directly, e.g., `` `r BiocStyle::Biocpkg("edgeR")` ``.

- [ ] Similarly, considering using code-style in order to distinguish/highlight anything R-related (package/function/argument/variable name), including Rvisdiff; this aids general readability.

# other

- [ ] Please keep tracking changing in the NEWS file; it's still listing version 0.99.0 only.

- [ ] In the README, please provide Bioconductor installation instructions using `BiocManager::install()`.

- [ ] Please consider implementing more comprehensive unit testing; current coverage is fairly minimal (~37% coverage with 1 hit/line according to `devtools::test_coverage()`).

**Comment by BioinfoUSAL** [comment]
We have introduce input checks in the code. Input parameters have been updated to adjust column names. Directory paths are now constructed with file.path function.
We have created a help man page and add code style to help functions.
News file has been updated, README file has been modified with BiocManager install and new unit tests have been added.

**Comment by HelenaLC** [comment]
Great, thanks for addressing these quickly and comprehensively! One last thing:
- The package currently `Imports`: (i.e., depends) on all of `edgeR`, `limma`, and `DESeq2`. However, my understanding is that `DEreport()` would work on any of these, independent of the users preferred framework.
- Would it be possible to place these packages under `Suggests:` instead (see [here](https://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances) for details), i.e., only demanding users to have one of these frameworks installed vs. all possibilities?
- This would, of course, depend on whether or not functions from all frameworks are required in any case/independent on what `DEreport()` is being run on.

**Comment by BioinfoUSAL** [comment]
Dear Helena, thanks for your useful comments. We have updated dependencies to enable optional installations.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BioinfoUSAL.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rvisdiff")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rvisdiff

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
