### ISSUE TITLE
CardinalIO

### ISSUE THREAD

**Issue by kuwisdelu** [Bioconductor/Contributions#3110]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kuwisdelu/CardinalIO

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@kuwisdelu - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
  'comment=c(ORCID="...")'.
- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
	Preprocessing, DimensionReduction

## NAMESPACE

- [ ] SUGGESTION: Generally 'importFrom()' is encouraged over importing an
  entire package. However, if there are many functions from a single package,
'import()' can be acceptable.

## Data

- [ ] REQUIRED: Data included in the 'inst/extdata/' directory requires
  documentation in an 'inst/script/' directory. The scripts in this directory
can vary. Most importantly a related script must be present that clearly
documents how the data was generated and source information. It should include
source URLs and any key information regarding filtering or processing. It can be
executable code, sudo code, or a text description. Users should be able to
download and roughly reproduce the file or object that is present as data.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?CardinalIO`.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 93
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There are 1206 lines that contain tabs.

Best,
Kayla

**Comment by kuwisdelu** [comment]
Thank you for the initial review!

> @kuwisdelu - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## DESCRIPTION
> * [ ]  SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
>   'comment=c(ORCID="...")'.
> * [ ]  SUGGESTION: Consider adding these automatically suggested biocViews:
>   Preprocessing, DimensionReduction

The package does not perform pre-processing or dimension reduction, so I have not added them, nor do I currently have an ORCID iD.

> ## NAMESPACE
> * [ ]  SUGGESTION: Generally 'importFrom()' is encouraged over importing an
>   entire package. However, if there are many functions from a single package,
>   'import()' can be acceptable.

I used importFrom() where I was only using a few functions, and import() where I was using more functions and it seems more convenient/appropriate. I left this as-is.

> ## Data
> * [ ]  REQUIRED: Data included in the 'inst/extdata/' directory requires
>   documentation in an 'inst/script/' directory. The scripts in this directory
>   can vary. Most importantly a related script must be present that clearly
>   documents how the data was generated and source information. It should include
>   source URLs and any key information regarding filtering or processing. It can be
>   executable code, sudo code, or a text description. Users should be able to
>   download and roughly reproduce the file or object that is present as data.

I did not initially include this as the files were directly downloaded as official examples of the imzML format without any additional processing, as documented in `?exampleImzMLFile`.

However, I've now added "manifest.md" to inst/script to satisfy this requirement, which lists the files and where they were originally downloaded from.

> ## Man pages
> * [ ]  SUGGESTION: We encourage having a package man page with an overview of the
>   package and links to the main functions. Users should be able to have a
>   relevant page display with `?CardinalIO`.

I have added this.

> ## R code
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 93
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
>   There are 1206 lines that contain tabs.

I generally try to keep lines around ~80 characters, but some lines would be made more awkward/less readable if shortened, and some lines are pre-formatted XML templates. Lastly, I have a strong preference for tabs.

> Best, Kayla

I have made the changes where required and considered all suggestions.

Thank you.

-Kylie

**Comment by Kayla-Morrell** [comment]
@kuwisdelu - Thank you for making the necessary changes. I have reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by kuwisdelu** [comment]
Thank you!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kuwisdelu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CardinalIO")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CardinalIO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
