### ISSUE TITLE
(inactive) Submission of package cleanse

### ISSUE THREAD

**Issue by martijnvanattekum** [Bioconductor/Contributions#3114]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/martijnvanattekum/cleanse

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  Would you please have a look at https://github.com/tidyomics/tidyomicsWorkshopBioc2023 and consider joining the tidygenomics slack channel https://community-bioc.slack.com/archives/CEQD45CHK ... I believe there is a significant relationship between your project and the work developing there.

**Comment by martijnvanattekum** [comment]
Thank you for your reply. I am familiar with the tidySummarizedExperiment package. The main difference is that it strictly uses tidy (long format) data, whereas cleanse stays closer to the original se dimensions (wide format). Particularly aggregate operations and arithmetic (also contained in cleanse) functions are easier/safer to perform on wide format data. As an example, randomly sampling columns (`se %>% sample_slice(col, n=10)` in cleanse) is not easy/possible to do in tidySummarizedExperiment.
I therefore think my package can be considered an alternative approach compared to tidySummarizedExperiment, and I don't see an immediate solution to integrate both approaches into one package. 
When published, I could note this difference in the readme, and join the tidyTranscriptomics community to ensure that there is no overlap between our packages.

**Comment by LiNk-NY** [comment]
Hi Martijn, @martijnvanattekum 

Thank you for your submission.
Please see the review below. 
Best,
Marcel

---

# cleanse #3114

* The package does not seem to provide a cohesive central representation and
straddles the line between the tidyverse and the S4 SummarizedExperiment class
leading to inefficiencies due to multiple data copies.
* Consider depending on `tidySummarizedExperiment` and / or providing solely
the function(s) that convert the data to tidy (wide) format.
* The exported S3 operations are not needed once the data is in the wide
format `tibble`.
* The package should adhere to the tidyverse semantics and avoid using
arguments like `axis`. 

## DESCRIPTION

* Avoid specifying versions for all packages in `Imports`, is is not
necessary.

## NAMESPACE

* I am not sure that providing S3 methods for `SummarizedExperiment` 
(as implemented) is the right direction.
* Avoid using `%>%` and use the native `|>`

## R

* It seems to me like the package should only provide ways to convert a
`SummarizedExperiment` into the tidy data class.
* Once converted, the package's S3 methods are not needed.
* It is less memory efficient to operate with both tidyverse and
`SummarizedExperiment` versions of the data.
* See the `tidySummarizedExperiment` implementation and consider depending on
their interface.
* Remove package startup messages.

**Comment by LiNk-NY** [comment]
Hi Martijn, @martijnvanattekum 
Any updates on the response to the review? 
Otherwise, we will close the issue due to inactivity. 
Best,
Marcel
