### ISSUE TITLE
CCPlotR

### ISSUE THREAD

**Issue by Sarah145** [Bioconductor/Contributions#3116]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Sarah145/CCPlotR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Sarah145** [comment]
Hi, 
The ERROR was due to me not being subscribed to the bioc-devel mailing list. I had subscribed with a different email address but have subscribed with the correct one now too so the ERROR should be resolved.

**Comment by ococrook** [comment]
Hi

Sorry for the delay. I thought I had already posted a review! I think the package is very good and useful! My main comment is the suitability for Bioconuductor. I realise the packages intended use is to be quite generic but it's not clear how it's meant to integrate within the wider ecosystem. That doesn't mean it shouldn't be a Bioconductor package, I just need to be convinced.

Please check through the build report carefully, there are a few things in there that can be straightforwardly handled such as setting laxydata to FALSE - unless you need it to be true for some reason?

I think the package would also benifit from unit tests.

The vignette can't be name `UserGuide` this is too generic for a Bioconductor package.

Function arguments with no default should be checked for validty - else I get error messages I cant debug very easily.

You will also need bioconductor install instructions in the readme and vignette. Remember to set the `eval = FALSE`

Thanks¬

**Comment by Sarah145** [comment]
Hi,

Thanks for taking the time to review the package and for the helpful suggestions! I've addressed each of your points below:

- **Suitability for Bionductor** - Although the intended use of the package is to be generic, I feel it fits in well with the wider Bioconductor ecosystem. The package is designed to work with the output of tools that predict cell-cell interactions from single-cell expression data, many of which are included in Bioconductor (e.g. [SingleCellSignalR](https://www.bioconductor.org/packages/release/bioc/html/SingleCellSignalR.html), [scTensor](https://www.bioconductor.org/packages/release/bioc/html/scTensor.html), [InterCellar](https://www.bioconductor.org/packages/release/bioc/html/InterCellar.html)). CCPlotR can be used alongside these other Bioconductor tools to generate enhanced visualisations of the results.
- **Addressing notes from the build report** -  I've updated the package to address notes from the build report by setting Lazydata = false, including a NEWS and CITATION file and adding a URL and BugReports field to the DESCRIPTION.
- **Function arguments with no default should be checked for validity** - I've added checks for all function arguments that don't have a default so they should display helpful error messages.
- **Adding unit tests** - I've included tests for all of the plotting functions.
- **Change vignette name and add Bioconductor install instructions** - I've updated the vignette name so it's less generic and have added bioconductor install instructions to both the vignette and the README.

Thanks again for the input and please let me know if any more changes are required!

**Comment by ococrook** [comment]
Thank you!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Sarah145.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CCPlotR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CCPlotR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
