### ISSUE TITLE
hoodscanR

### ISSUE THREAD

**Issue by ningbioinfo** [Bioconductor/Contributions#3117]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DavisLaboratory/hoodscanR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
vignette must include prose introduction explaining purpose of package and relation to bioconductor

**Comment by ningbioinfo** [comment]
Hi @vjcitn , the vignette has been updated with including a paragraph of introduction of the package at the front.

**Comment by HelenaLC** [comment]
Hey, thanks for your submission, it is nice to see some development on spatial analyses and also directly leveraging existing Bioc infrastructure. A couple thoughts below, but nothing major. Please report back with what has/has not been addressed, or if you have any questions/need for clarity. 

# code

- [ ] Avoid the use of `sapply()` and use `vapply()` instead (see build report). Specifically, in *plot_heatmap.R* line 112 `numeric_cols <- sapply(df, is.numeric)` should be `vapply(df, is.numeric, logical(1))`. 

- [ ] I would highly encourage implementing some minimal validity checks on input arguments, e.g., many functions expect a `SpatialExperiment` object with certain information (e.g., spatial coordinates). So something like `is(..., "SpatialExepriment")`, `!is.null(spatialCoordsNames(spe))` etc. would be nice, throwing informative messages when minimal requirements aren't met. Similarly for other non-SPE arguments.

# vignette

- [ ] I feel the vignette currently contains *only* a quick start, demoing all functions with a brief comment on what they do. It would be appreciated if there was a little more explanation on what different computations are trying to achieve and how they are to be interpreted (see also comment below); less statistically inclined users may be interest in these methods from a biological perspective, but may let the know-how of what different metrics/plots mean exactly.

- [ ] We encourage the use of `` `r BiocStyle::Biocpkg("BiocStyle")` `` for formatting with `html_document` as rendering target, i.e., 
```
output:
  BiocStyle::html_document:
```

- [ ] Considering making use of `BiocStyle` functionality to highlight/distinguish and hyperlink external package as to aid readability and directly users to these directly, e.g., `` `r BiocStyle::Biocpkg("SpatialExperiment")` ``.

- [ ] Typo summarisatino -> summarisation

# documentation

- [ ] On the corresponding help-page, please provide a description and source information for the example dataset `spe_test`.

- [ ] In the package help-(*man*-)page (`?hoodscanR`), it would be nice to direct users to key functions (via `\code{\link{<function>}}`) to grasp an idea of the main analysis workflow.

- [ ] In the corresponding *.man* pages, more detail on theory/methodology of the underlying methods would be nice. E.g., `calcMetrics()`: (briefly!) what are entropy and perplexity, how are they calculated, what is there value range, how are they to be interpreted etc. (same for others).

# other

- [ ] In the READEME, please provide Bioconductor installation instructions using `BiocManager::install()`. 

- [ ] Please properly track changes in the NEWS file; it is currently listing version 1.0.0, which never should have existed, while the DESCRIPTION is at 0.99.1.

- [ ] Unit testing looks quite all right (70% overall coverage), but might be worth improving on (there's currently only 1-11 hits per line according to `devtools::test_coverage()`). 

- [ ] The LICENSE contains placeholders from the template (e.g., "<one line to give the program's name and a brief idea of what it does.> Copyright (C) <year>  <name of author>"); please provide a proper one.

**Comment by ningbioinfo** [comment]
Hi @HelenaLC , Thanks for the feedbacks.

Here are the report after addressing the feedbacks/suggestions.

# Code
- [x] `sapply` change to `vapply`.
- [x]  validity checks on inputs are now added to all functions using either is(spe, "SpatialExperiment") or is(m, "matrix") etc.

# vignette
- [x] Explanation of plots and algorithm inside different functions are now added to the vignette briefly.
- [x] BiocStyle are now used.
- [x] BiocStyle to hyperlink packages are now used.
- [x] Typo summarisatino is now fixed.

# documentation
- [x] data description of the test data has been added.
- [x] cross-link key function have added to the package help page.
- [x] the equation and theory of the calcMetrics are now added in the help page.

# other
- [x] Bioconductor installation instructions is now added to the readme file.
- [x] NEWS file is now currently listing v 0.99.1.
- [x] code coverage is now almost 85%.
- [x] The LICENSE placeholders is now edited.

**Comment by HelenaLC** [comment]
Thanks for the prompt addressing of these points. It's looking fairly good to me. On a quick glance, I have a couple suggestions to improve some parts of the code as well as "user perspective/experience"-related bits, but nothing major.

- [ ] Again, please try to properly track changes in the NEWS file. It is now at 0.99.3, however, changes for previous versions are gone. Ideally, each version should be listed with a couple of bullet points *briefly* tracking bug fixes, additional features, general changes (e.g., "documentation revision"") etc. Perhaps have a look at how other packages do this, but of course find your own style!

- [ ] For anything *adding* information to the input SPE and returning that, I'd be happy to see in the documentation (under "Value"/`@value`) where that's gone. E.g., `clustByHood()` stores results in the `cluster` slot of `colData`.

- [ ] Complementary to the above, any function adding data should check that that slot is empty and/or expose an argument that let's them control where to store results, otherwise the user's data might be unintentionally overwritten. E.g., `cluster` might be something that users have already used up previously.

- [ ] I'd suggest to check that spatial coordinates are actually defined in the input SPE (i.e., `!is.null(spatialCoordsNames(spe))`) *everywhere* they are needed, as their absence gives a quite confusing error, specially to novice users, e.g.:
```
> spatialCoords(spe) <- NULL
> findNearCells(spe, k = 100)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2]
  not equal to array extent
```

- [ ] *calc_metrics.R* lines 53+ could be written as `colData(spe)[colnames(result)] <- result`

- [ ] *utils.R* line 10+ argument `rn="rwoname"` should be `"rowname"`

- [ ] *merge_by_group.R* lines 38+ initializes an empty `data.frame` that's filled with a `for`-loop. That sort of thing can be written as (also note the conversion of a logial to numeric matrix via `1*`):
```
out_df <- vapply(uniquegroups, \(g) {
  mask <- 1 * (group_df == g)
  rowSums(mask * pm)[rownames(df)]
}, numeric(nrow(df)))
```

**Comment by ningbioinfo** [comment]
Hi @HelenaLC , thanks for the comments, quite useful!

- [x] NEWS file updated, listed what I've changed since the first submission.
- [x] output values are now all specified in the value slot of the documentation.
- [x] parameter val_names is added to relevant functions now, allowing user to define output names if necessary.
- [x] spatialCoordsNames check is now added to both findNearCells() and readHoodData().
- [x] for loop is now gone. Same as in the mergeHoodSpe().
- [x] typo is fixed.
- [x] Thanks for this vapply, works really good, have replaced the for loop.

**Comment by HelenaLC** [comment]
Fantastic. Note that *merge_by_group.R* lines 38-40 can be dropped now, and any commented out code should also be removed eventually. - happy to accept.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ningbioinfo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("hoodscanR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hoodscanR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
