### ISSUE TITLE
BiocBook

### ISSUE THREAD

**Issue by js2264** [Bioconductor/Contributions#3118]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/js2264/BiocBook

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by js2264** [comment]
Hi @hpages thanks for reviewing this package. 

The error from the SPB is : 

```
/home/biocbuild/bbs-3.18-bioc/R/bin/R CMD build --keep-empty-dirs --no-resave-data BiocBook
* checking for file BiocBook/DESCRIPTION ... OK
* preparing BiocBook:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building stub.Rmd using rmarkdown
--- finished re-building stub.Rmd

quarto render ../inst/
make: quarto: No such file or directory
make: *** [Makefile:4: render] Error 127
Error in tools::buildVignettes(dir = ".", tangle = TRUE) : 
  running 'make' failed
Execution halted
```

When running locally on `bioconductor_docker:devel`, everything works (with some warnings), unless I remove `quarto`, in which case I can replicate the error from SPB: 

```
root@b2baeba14765:/opt# R CMD build --keep-empty-dirs --no-resave-data BiocBook
* checking for file ‘BiocBook/DESCRIPTION’ ... OK
* preparing ‘BiocBook’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘BiocBook_0.99.0.tar.gz’

root@b2baeba14765:/opt# command -V quarto
quarto is /usr/local/bin/quarto

root@b2baeba14765:/opt# mv /usr/local/bin/quarto /usr/local/bin/quarto.bak

root@b2baeba14765:/opt# quarto check
bash: quarto: command not found

root@b2baeba14765:/opt# R CMD build --keep-empty-dirs --no-resave-data BiocBook
* checking for file ‘BiocBook/DESCRIPTION’ ... OK
* preparing ‘BiocBook’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘stub.Rmd’ using rmarkdown
--- finished re-building ‘stub.Rmd’

quarto render ../inst/
make: quarto: No such file or directory
make: *** [Makefile:4: render] Error 127
Error in tools::buildVignettes(dir = ".", tangle = TRUE) :
  running 'make' failed
Execution halted
```

Can you confirm me that the SPB sets up `quarto` prior to building the package? Thanks

**Comment by hpages** [comment]
Let me take a look

**Comment by hpages** [comment]
Ok Quarto is now installed on the Linux builders. Please bump the package version to trigger another build by the SPB.

Note that Quarto is not on the Mac builders yet so we're going to ignore this platform for now (we only build books on Linux at the moment anyways, see https://bioconductor.org/checkResults/3.18/books-LATEST/).

Thanks!

**Comment by js2264** [comment]
@hpages thanks for setting up `quarto` on Linux builders. The checks are now all green for Linux, the remaining ERRORs are for Mac, as you mentioned.

**Comment by lshep** [comment]
@js2264 we have temporarily removed the ability to trigger build/check on our system until pending pre-review changes regarding the `.gitconfig` file are resolved

**Comment by hpages** [comment]
Thanks Lori @lshep 

@js2264 It seems that you still have code that tries to alter the `.gitconfig` file of the local user e.g. the examples in `man/BiocBook.Rd` contain:
```
gert::git_config_global_set('user.name', value = 'js2264')
gert::git_config_global_set('user.email', value = 'jacquesserizay@gmail.com')
```
Please remove ASAP and make sure that `R CMD build` and `R CMD check` do not alter any sensible file on the user machine. Thanks!

**Comment by js2264** [comment]
@lshep Thanks for changing the triggering settings, hopefully this will prevent side effects from any ill-conceived code until this issue is resolved. I apologise again for the trouble this issue is causing to the SPB. 

@hpages I have bumped to v0.99.5 on both my `origin` (https://github.com/js2264/BiocBook/commit/d647bcc30880c98d496ba493872046b730df2458) and Bioc `upstream`. I have now purged the commands you mentioned from the examples and re-built doc, thank you for pointing this out. I carefully went through the rest of the code to make sure it does not change the git config or other directories for the end user. `R CMD build/check` should not affect any file from the user machine anymore. I hope I did not miss anything, please let me know if you spot remaining issues. I also tried to comment as much as possible what each command does. Once again, I apologise for messing things up with some poorly thought-out code.

Thanks!

**Comment by hpages** [comment]
Thanks @js2264. I just allowed SPB builds/checks again by changing the label to "review in progress". Can you please bump the version again so we get a new build/check report? Thanks

**Comment by hpages** [comment]
~Hmm... still no SPB report after 9 hours. Any thought @lshep?~   <--- please ignore :flushed:

**Comment by hpages** [comment]
Ignore my previous comment. I see the report now.

**Comment by hpages** [comment]
Hi @js2264 

**BiocBook** has a dual nature (from a Bioconductor organizational perspective). It's a software package that contains tools that help the user create their own book. But it's also a book-containing package. This means that if we add it to the software builds and repository, the book it contains won't be deployed so the user won't have access to it. And if we add it to the book builds and repository, then we won't run `R CMD check` on it (this is not needed on a pure book-containing package) and it's going to make it harder for people who need the software tools to find them.

How can we work around that? Do you think the package could be split in 2 packages? E.g. **BiocBook** for the software part and **BiocBookDemo** for the book part, or **BiocBookTools** for the software part and **BiocBook** for the book part? In any case the software package would need a traditional vignette (i.e. not Quarto) that covers the tools.

Thanks,
H.

**Comment by js2264** [comment]
Hi @hpages, how the **BiocBook** **book** itself would be deployed (versus the package) is something I had not anticipated, thanks for pointing this out.  I can submit an independent `BiocBookDemo` package containing the **book** content itself (most of the `inst` folder) and remove this content from the current `BiocBook` package, replacing it with more focused vignette(s) instead. Would that work for you? 

I take this opportunity to ask: do you reckon a `biocViews: Book` should be added to template `DESCRIPTION` for `BiocBook`s? I am not sure it is actually of any use, but it seems it has been a recommendation at some point for books? Is it a feature actually supported by Bioconductor? 

Thanks, 
J

**Comment by js2264** [comment]
@hpages, following your suggestion, I split `{BiocBook}` in two packages. The initial `{BiocBook}` package (currently in the SPB) contains the functions to create/edit a _BiocBook_, and the new `{BiocBookDemo}` package has been created using `BiocBook::init('BiocBookDemo')`, and book pages have been migrated from the original `{BiocBook}` to `{BiocBookDemo}`. 

This means that there is no more `gh-pages` branch available for `{BiocBook}` but there is one for `{BiocBookDemo}`, curretnly serving the `devel` version of the `{BiocBookDemo}` online book. 

- https://github.com/js2264/BiocBookDemo
- https://js2264.github.io/BiocBookDemo/devel/

Let me know your thoughts regarding this organization. If this works for you, should I add the `BiocBookDemo` package to this submission issue with an `AdditionalPackage:` comment?

**Comment by hpages** [comment]
I think this organization makes a lot of sense. Yes please submit the new **BiocBookDemo** package as an additional package. Thanks @js2264 !

**Comment by js2264** [comment]
AdditionalPackage: https://github.com/js2264/BiocBookDemo/

**Comment by js2264** [comment]
@hpages I have added `BiocBookDemo` to this issue

**Comment by js2264** [comment]
Thanks @lshep. Should the "1. awaiting moderation" tag be removed, as this is an additional package and @hpages is already reviewer for the main package? Thanks!

**Comment by lshep** [comment]
now quite yet -- as I haven't added BiocBookDemo to git and I need the tag to process -- @hpages  it should still go into out git.bioconductor.org even tho it is a book correct?

**Comment by js2264** [comment]
@lshep thank you very much for handling the submission process and adding `BiocBookDemo` to git. 
@hpages the demo book build/check are green (for Linux), and the rendered website can be viewed from the bundle: `inst/doc/book/index.html`

**Comment by hpages** [comment]
> it should still go into out git.bioconductor.org even tho it is a book correct?

Correct. Thanks @lshep

**Comment by hpages** [comment]
Thanks @js2264 for splitting the package.

Here is some feedback:

1. Make sure that you actually need all the packages listed in the `Imports` and `Suggests` fields of the **BiocBook** package. For example are you sure you need to suggest **BiocVersion**, **BiocCheck**, or **RefManageR**, to name a few?

2. Nothing should get installed from GitHub. Bioconductor packages should always be installed with `BiocManager::install()`. Trying to install them from GitHub is a recipe for package version mismatches.

3. **BiocBookDemo** is not a software package so the `biocViews` field cannot contain the term `Software`. Also the `Infrastructure` and `ReportWriting` terms are offsprings of the `Software` term so can't be used either. Unfortunately we still don't have a biocViews vocabulary for book packages (we need to work on it) so let's just drop this field for now.

4. Add `BiocType: Book` to `BiocBookDemo/DESCRIPTION`. We still need to discuss internally what to do about the `BiocType` field. This field will become redundant with the `biocViews` field once we have a biocViews ontology for books, so things might change in the future. We'll communicate in the near future about this and it will be easy to adjust the `BiocBookDemo/DESCRIPTION` file.

5. About the vignete in the **BiocBook** software package:

   - Would be nice to have a short introduction that explains what the package is about.

   - Something strange happened to the section numbers:
![Screenshot from 2023-10-03 13-33-07](https://github.com/Bioconductor/Contributions/assets/8810451/e50b3cfd-6012-4a1c-a638-ea0dcf1aee55)

      Strangely, the numbers are repeated and the first number is prefixed with `0.`.

   - The vignette should not show command output in images. Code chunks should be used instead.
 
   - No need to include all installed packages in the "Session info" section. Just use `sessioninfo::session_info(include_base=TRUE)`. The standard `sessionInfo()` also works and has the benefit to reduce the number of dependencies.

6. Found in `BiocBookDemo/inst/pages/biocbook-vs-rebook.qmd`:
   > In fact, this very **online book** is shipped in the {`BiocBook`} **package**, which also provides functions to create/edit books.

   This needs to be updated to reflect the 2-package split. Maybe there are other places in **BiocBook** and **BiocBookDemo** where similar updates need to be made?

7. If you use non-ASCII characters in your DESCRIPTION file (like you do in `BiocBook/DESCRIPTION`) then you need to specify the encoding of the file _before_ the occurence of the first non-ASCII character. In the case of `BiocBook/DESCRIPTION`, it seems that the non-ASCII character is the ellipsis used in the `Description` field. Doesn't seem worth using a specific encoding just for that though, when you can use three dots (`...`). 

Thanks,
H.

**Comment by js2264** [comment]
Thanks @hpages for your comments. Here are some answers: 


- [x] 1. Make sure that you actually need all the packages listed in the `Imports` and `Suggests` fields of the **BiocBook** package. For example are you sure you need to suggest **BiocVersion**, **BiocCheck**, or **RefManageR**, to name a few?

Thank you for pointing out these outdated deps (they should have been deleted after spinning off `BiocBookDemo` as an independent package. I have removed them as well as other unnecessary ones. 

- [x] 2. Nothing should get installed from GitHub. Bioconductor packages should always be installed with `BiocManager::install()`. Trying to install them from GitHub is a recipe for package version mismatches.

I have corrected `BiocBookDemo` chapter 2 and the READMEs.

**Question:** 

In `BiocBook::init()`, I fetch a versioned book **template** from github: https://github.com/js2264/BiocBook.template/archive/refs/tags/v1.0.4.tar.gz. So strictly speaking, this link is not used to **install** a package, but kickstart a new one (whose version is preset to 0.98.0) using a github-versioned template. This file is versioned using Github releases: https://github.com/js2264/BiocBook.template/releases. Is this ok? Or should `BiocBook.template` also be included in Bioconductor, one way or another, and synced with BiocBook versions? The easiest approach I can think of, in order not to have to download this archive from GitHub, would be to include this template as `extdata` in `BiocBook` package itself. Would you want me to do this, or would using the github-versioned template be ok? 

- [x] 3. **BiocBookDemo** is not a software package so the `biocViews` field cannot contain the term `Software`. Also the `Infrastructure` and `ReportWriting` terms are offsprings of the `Software` term so can't be used either. Unfortunately we still don't have a biocViews vocabulary for book packages (we need to work on it) so let's just drop this field for now.

biocViews field removed entirely. 

- [x] 4. Add `BiocType: Book` to `BiocBookDemo/DESCRIPTION`. We still need to discuss internally what to do about the `BiocType` field. This field will become redundant with the `biocViews` field once we have a biocViews ontology for books, so things might change in the future. We'll communicate in the near future about this and it will be easy to adjust the `BiocBookDemo/DESCRIPTION` file.

`BiocType: Book` added for future updates.

5. About the vignete in the **BiocBook** software package:   

- [x] Would be nice to have a short introduction that explains what the package is about.
- [x] Something strange happened to the section numbers: strangely, the numbers are repeated and the first number is prefixed with `0.`.
- [x] The vignette should not show command output in images. Code chunks should be used instead.
- [x] No need to include all installed packages in the "Session info" section. Just use `sessioninfo::session_info(include_base=TRUE)`. The standard `sessionInfo()` also works and has the benefit to reduce the number of dependencies.


- [x] 6. Found in `BiocBookDemo/inst/pages/biocbook-vs-rebook.qmd`:
>   In fact, this very **online book** is shipped in the {`BiocBook`} **package**, which also provides functions to create/edit books.

I fixed this where needed, thanks for noticing. 

- [x] 7. If you use non-ASCII characters in your DESCRIPTION file (like you do in `BiocBook/DESCRIPTION`) then you need to specify the encoding of the file _before_ the occurence of the first non-ASCII character. In the case of `BiocBook/DESCRIPTION`, it seems that the non-ASCII character is the ellipsis used in the `Description` field. Doesn't seem worth using a specific encoding just for that though, when you can use three dots (`...`).

Fixed as well.

**Comment by js2264** [comment]
Thanks @hpages for your comments. Here are some answers: 


- [x] 1. Make sure that you actually need all the packages listed in the `Imports` and `Suggests` fields of the **BiocBook** package. For example are you sure you need to suggest **BiocVersion**, **BiocCheck**, or **RefManageR**, to name a few?

Thank you for pointing out these outdated deps (they should have been deleted after spinning off `BiocBookDemo` as an independent package. I have removed them as well as other unnecessary ones. 

- [x] 2. Nothing should get installed from GitHub. Bioconductor packages should always be installed with `BiocManager::install()`. Trying to install them from GitHub is a recipe for package version mismatches.

I have corrected `BiocBookDemo` chapter 2 and the READMEs.

**Question:** 

In `BiocBook::init()`, I fetch a versioned book **template** from github: https://github.com/js2264/BiocBook.template/archive/refs/tags/v1.0.4.tar.gz. So strictly speaking, this link is not used to **install** a package, but kickstart a new one (whose version is preset to 0.98.0) using a github-versioned template. This file is versioned using Github releases: https://github.com/js2264/BiocBook.template/releases. Is this ok? Or should `BiocBook.template` also be included in Bioconductor, one way or another, and synced with BiocBook versions? The easiest approach I can think of, in order not to have to download this archive from GitHub, would be to include this template as `extdata` in `BiocBook` package itself. Would you want me to do this, or would using the github-versioned template be ok? 

- [x] 3. **BiocBookDemo** is not a software package so the `biocViews` field cannot contain the term `Software`. Also the `Infrastructure` and `ReportWriting` terms are offsprings of the `Software` term so can't be used either. Unfortunately we still don't have a biocViews vocabulary for book packages (we need to work on it) so let's just drop this field for now.

biocViews field removed entirely. Note that this triggers the "ERROR" in BiocCheck... 

- [x] 4. Add `BiocType: Book` to `BiocBookDemo/DESCRIPTION`. We still need to discuss internally what to do about the `BiocType` field. This field will become redundant with the `biocViews` field once we have a biocViews ontology for books, so things might change in the future. We'll communicate in the near future about this and it will be easy to adjust the `BiocBookDemo/DESCRIPTION` file.

`BiocType: Book` added for future updates.

5. About the vignete in the **BiocBook** software package:   

- [x] Would be nice to have a short introduction that explains what the package is about.
- [x] Something strange happened to the section numbers: strangely, the numbers are repeated and the first number is prefixed with `0.`.
- [x] The vignette should not show command output in images. Code chunks should be used instead.
- [x] No need to include all installed packages in the "Session info" section. Just use `sessioninfo::session_info(include_base=TRUE)`. The standard `sessionInfo()` also works and has the benefit to reduce the number of dependencies.


- [x] 6. Found in `BiocBookDemo/inst/pages/biocbook-vs-rebook.qmd`:
>   In fact, this very **online book** is shipped in the {`BiocBook`} **package**, which also provides functions to create/edit books.

I fixed this where needed, thanks for noticing. 

- [x] 7. If you use non-ASCII characters in your DESCRIPTION file (like you do in `BiocBook/DESCRIPTION`) then you need to specify the encoding of the file _before_ the occurence of the first non-ASCII character. In the case of `BiocBook/DESCRIPTION`, it seems that the non-ASCII character is the ellipsis used in the `Description` field. Doesn't seem worth using a specific encoding just for that though, when you can use three dots (`...`).

Fixed as well.

**Comment by hpages** [comment]
Thanks @js2264 for the changes.

> The easiest approach I can think of, in order not to have to download this archive from GitHub, would be to include this template as extdata in BiocBook package itself

Definitely some advantages to this approach:
- Would prevent repeated downloads of the template. For example, once the **BiocBook** package gets added to the Bioconductor daily builds, the template will get downloaded twice a day (one during the release builds, and one during the devel builds) when BBS runs `R CMD check` on the package.
- Another advantage of this approach is that it creates a hard tie between the template and the software. This eliminates the risk of running into a situation where changes in the software also require changes in the template that are not backward compatible with earlier versions of the software.
- It would allow the user to work offline, granted they call `init()` with `skip_availability=TRUE` and `.local=TRUE`.
- Finally this would also make the `init()` interface slightly simpler by getting rid of the `version` argument. The `template` argument could stay, but I'm not sure what it would become. Maybe the path or URL to an alternative template? Default value could be `NULL`, which would mean "use the template included in the package". Another option is to simply get rid of the `template` argument.

I can't think of any drawbacks to this approach. The template is small (`v1.0.4.tar.gz` is 152K) so size is not a concern.

Note that one could argue that a package template is not really data so feel free to put this anywhere under `inst/`.

The recommendation for a software package is to set the `URL` field to the canonical URL of its landing page (a.k.a. "Package Short URL"), which will be `https://bioconductor.org/packages/BiocBook` in the case of **BiocBook** (the page does not exist yet but it will get automatically created after the package gets added to our daily builds). The `BugReports` field already points people to the issue tracker on GitHub. Bioconductor prefers to make the package landing page the primary URL, and not advertize the URL of the Github repo too much because this encourages people to install the package from there (which is bad) or to use the issue tracker to ask questions about how to use the software (which is also bad).

Also I would suggest to set the `BugReports` field to the issue part of the GitHub repo: `https://github.com/js2264/BiocBook/issues`

Found in `BiocBook/README.md`:

> To install `BiocBook` development version, you can use:
> 
> ```r
> install.packages("devtools")
> devtools::install_github("js2264/BiocBook")
> ```

You should still not do this. If you want to install the development version, you _first_ need to make sure that you are using the development version of Bioconductor (depending on the time of the year, this might require installing R devel), then doing `BiocManager::install("BiocBook")` will bring the development version of **BiocBook**. As mentioned earlier, installing directly from GitHub has the potential to mess up your installation by introducing version mismatches. In other words, `BiocManager::install()` is the only safe way to install Bioconductor packages.

Similar problem found in `BiocBookDemo/inst/pages/Chapter-2.qmd`:
```
if (!require(BiocBook)) BiocManager::install('js2264/BiocBook')
```

Not sure why I get the following message when I try to use an existing name:
```
> init('OSCA', .local = TRUE)
...
! `available` server is currently unavailable. Skipping validation...
...
```
Also shouldn't this be a hard error? I.e. the function should stop and not create the `OSCA` folder.

I find the name of the `commit` argument misleading. IIUC this is about _pushing_ commits, not _committing_ changes. Also the default for `commit` is `NA` but the man page says it's `FALSE`. Furthermore, based on the code, it seems that `commit=NA` and `commit=FALSE` don't have the same meaning but the man page does not document the meaning of the former. 

Given that the BiocBook man page (`?BiocBook`) documents more than one function, the `\value` section should either document them all, or at least clarify which one it refers to. Right now it's up to the user to figure this out:
```
Value:

     A ‘BiocBook’ object (invisible).
```

No need to re-implement `tempfile()`. Instead of:
```
    tmpdir <- paste0('.', paste0(
        sample(c(seq(0, 9), LETTERS), 8, replace = TRUE), collapse = ""
    ))
    dir.create(tmpdir)
```
just do something like:
```
    tmpdir <- tempfile()  # or tempfile("BiocBook.template."), but it does not matter _at all_
    dir.create(tmpdir)
```
Note that an important feature of `tempfile()` is that it returns the path to a file that will be created _inside_ `tempdir()`. This means that the file is guaranteed to get removed at the end of the R session. Right now your code explicitely needs to take care of that (with `unlink(tmpdir, recursive = TRUE)`). However, if for whatever reason the call to `init()` dies prematurely, the tmp dir that your code created in the working directory will remain there, hence contaminating the user's folder with a stale hidden subfolder. See `?tempfile` for more info.

This seems like a lot of code only to copy the content of one folder to an empty folder:
```
    ## Move files from temp folder to `new_package` folder
    d <- list.dirs(tmpdir, full.names = TRUE, recursive = TRUE)
    d <- d[dirname(d) != '.']
    pattern <- file.path(tmpdir, basename(d)[dirname(dirname(d)) == '.'])
    d <- d[dirname(dirname(d)) != '.']
    f <- list.files(
        tmpdir, 
        all.files = TRUE, full.names = TRUE, recursive = TRUE
    )
    f <- f[!grepl("archive.zip$", f)]
    for (.d in d) dir.create(gsub(pattern, repo, .d))
    for (.f in f) file.copy(from = .f, to = gsub(pattern, repo, .f))
```
Is this because the various files that need to be skipped (the  `*archive.zip` files) can be located at any depth in the `tempdir` tree? Otherwise copying the content can be done with:
```
    content <- list.files(tmpdir, all.files=TRUE, full.names=TRUE, no..=TRUE)
    file.copy(content, repo, recursive=TRUE)
```
If the file to skip is located at the top of the `tmpdir` tree, then add:
```
    content <- content[!grepl("archive.zip$", content)]
```
before calling `file.copy()`.

Not sure what the purpose of the ` invisible(BiocBook(repo))` line is here:
```
        if (!is.na(commit)) {
            if (commit) {
                gert::git_push(repo = repo)
                cli::cli_alert_success(cli::col_grey("Commits pushed to origin {cli::col_cyan(gert::git_remote_list(repo = repo)$url[1])}"))
            }
            else {
                invisible(BiocBook(repo))
            }
        }
       ...
```
The `if` statement is not the last expression in the body of the `init()` function so the `invisible(BiocBook(repo))` line won't return anything. It's just a no-op.

The body of the `init()` function is very long. Readbility, troubleshooting, and long-term maintainability, could be improved significantly by breaking it down into smaller internal helper functions, one for each major step accomplished by the big function.

Thanks again,
H.

**Comment by js2264** [comment]
Thanks @hpages , these comments are super helpful. You'll see my answers below.

- [x] 1. Integrating the book template in `inst/template/`

You are right that this strategy makes a lot of sense. 

- [x] 2. The recommendation for a software package is to set the URL field to the canonical URL of its landing page (a.k.a. "Package Short URL"), which is https://bioconductor.org/packages/BiocBook in the case of BiocBook. The BugReports field already points people to the issue tracker on GitHub. Bioconductor prefers to make the package landing page the primary URL, and not advertize the URL of the Github repo so much because this encourages people to install the package from there (which is bad) or to use the issue tracker to ask questions about how to use the software (which is also bad). Also I would suggest to set the BugReports field to the issue part of the GitHub repo: https://github.com/js2264/BiocBook/issues

Fixed 

- [x] 3. Found in BiocBook/README.md:

> "To install BiocBook development version, you can use:"
> ```
> install.packages("devtools")  
> devtools::install_github("js2264/BiocBook")  
> ```
> You should still not do this. If you want to install the development version, you first need to make sure that you are using the development version of Bioconductor (depending on the time of the year, this might require installing R devel), then doing BiocManager::install("BiocBook") will bring the development version of BiocBook. As mentioned earlier, installing directly from GitHub has the potential to mess up your installation by introducing version mismatches. In other words, BiocManager::install() is the only safe way to install Bioconductor packages.
> Similar problem found in BiocBookDemo/inst/pages/Chapter-2.qmd:
> ```
> if (!require(BiocBook)) BiocManager::install('js2264/BiocBook')
> ```

I see, I didn't realize that the devel version as well should strictly be pointing to Bioconductor. Thanks for clarifying this. 

- [x] 4. Not sure why I get the following message when I try to use an existing name:

> init('OSCA', .local = TRUE)
> ...
> ! `available` server is currently unavailable. Skipping validation...
> ...
> Also shouldn't this be a hard error? I.e. the function should stop and not create the OSCA folder.

Thanks for catching this bug, it's now fixed. 

- [x] 5. I find the name of the commit argument misleading. IIUC this is about pushing commits, not committing changes. Also the default for commit is NA but the man page says it's FALSE. Furthermore, based on the code, it seems that commit=NA and commit=FALSE don't have the same meaning but the man page does not document the meaning of the former.

I renamed `commit` boolean argument to `push` and updated the documentation. 

- [x] 6. Given that the BiocBook man page (?BiocBook) documents more than one function, the \value section should either document them all, or at least clarify which one it refers to. 

I updated the doc. 

- [x] 7. No need to re-implement tempfile(). Note that an important feature of tempfile() is that it returns the path to a file that will be created inside tempdir(). This means that the file is guaranteed to get removed at the end of the R session. Right now your code explicitely needs to take care of that (with unlink(tmpdir, recursive = TRUE)). However, if for whatever reason the call to init() dies prematurely, the tmp dir that your code created in the working directory will remain there, hence contaminating the user's folder with a stale hidden subfolder. See ?tempfile for more info.

I refactored most of this when I embedded the template within the package. I am now using the approach you suggested in your comment, thank you. 

- [x] 8. This seems like a lot of code only to copy the content of one folder to an empty folder ... Is this because the various files that need to be skipped (the *archive.zip files) can be located at any depth in the tempdir tree? Otherwise copying the content can be done with:

I originally had another approach which required me to use this rather convoluted code. But now that I rely on the embedded archive it's much easier, I've used your code, thanks!

- [x] 9. Not sure what the purpose of the  invisible(BiocBook(repo)) line is here ... The if statement is not the last expression in the body of the init() function so the invisible(BiocBook(repo)) line won't return anything. It's just a no-op.

It's now fixed. 

- [x] 10. The body of the init() function is very long. Readbility, troubleshooting, and long-term maintainability, could be improved significantly by breaking it down into smaller internal helper functions, one for each major step accomplished by the big function.

I've split this super-big function in smaller chunks, thanks for the input.

**Comment by js2264** [comment]
@hpages do you think you will have more comments to add to this review? Or do you want me to work more on some of the points already mentionned? I don't want to sound pushy, but it would be super helpful if these packages could be added to the current devel a few days before the release, so that I have some time to check that everything runs ok on the BBS, since `BiocBookDemo` is slightly different package compared to others. Thanks!

**Comment by hpages** [comment]
Hi @js2264, thanks for your patience. We've received many last minute package submissions for 3.18 that keep us quite busy.

Thanks again for the many improvements.

One last nitpicking. I was wondering if the following packages actually need to be listed in the `Suggests` field of **BiocBookDemo** as I don't see them used anywhere in the package: **BiocCheck**, **rcmdcheck**, **quarto**. For **quarto**, I see that external command `quarto` is used, but not the CRAN package **quarto**. Reliance on the `quarto` command should be declared with something like `SystemRequirements: quarto`. Note that this is for **BiocBookDemo** only. **BiocBook** depends on CRAN package **quarto** but doesn't use the `quarto` command directly, so doesn't need to change anything.

Other than that **BiocBook**/**BiocBookDemo** are in good shape and ready to go.

H.

**Comment by js2264** [comment]
Thanks for your reply @hpages , and thank you for your time and effort in reviewing this package and others. I've now removed the unnecessary deps from Suggests.

**Comment by hpages** [comment]
@lshep 2 packages accepted: **BiocBook** (software package) and **BiocBookDemo** (book). Thanks!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocBook")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocBook

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocBookDemo")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocBookDemo

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
