### ISSUE TITLE
easylift

### ISSUE THREAD

**Issue by nahid18** [Bioconductor/Contributions#3122]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nahid18/easylift

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
Thanks @nahid18 for submitting the **easylift** package.

Here is some feedback:

1. About the Description field:
    > The package performs genomic liftover different genome assemblies given GRanges, genome and chain file.

    It feels like a word is missing between "liftover" and "different". Also I'd suggest to use "GRanges object" instead of just "GRanges", and "target genome" instead of just "genome".

2. Move **GenomicRanges** to the `Depends` field. Then remove the following lines from the example in the man page:
    ```
    library(GenomicRanges)
    library(easylift)
    ```
    Also remove `library(GenomicRanges)` from the vignette.

3. The man page should reference the `liftOver()` function from the **rtracklayer** package which `easylift()` is based on. This is typically done via a `\seealso` section.
 
4. Code like this is hard to read:
    ```
    gr <- GRanges(seqname = Rle(c("chr1", "chr2"), c(100000, 100000)),
    ranges = IRanges(start = 1, end = 200000))
    ```
    Please use proper indentation in multiple-line expressions to improve readibility.

5. About this check at the beginning of the `easylift()` function:
    ```
    if (any(is.na(GenomeInfoDb::genome(x)))) {
        stop("The genome information is missing. Please set genome(x) before using easylift.")
    }
    ```
    - Use `anyNA(...)` instead of `any(is.na(...))`.
    - But also what happens if `genome(x)` has more than 1 unique value, that is, if GRanges object `x` contains genomic ranges on more than 1 genome. This is a rare situation but it can happen. Is this something that `easylift()` can handle? If not, it might be better to detect this situation early and fail with a clear error message.

6. README file in `inst/extdata/` is not a markdown file. Please restore its original extension which is `.txt`.

7. Proper use of `system.file()` is `system.file("extdata", "hg19ToHg38.over.chain.gz", package="easylift")`. Doing `system.file("extdata/hg19ToHg38.over.chain.gz", package="easylift")` is not platform-independent. Also this comment in the vignette is confusing/misleading:
    > here, we use the `system.file()` function because this is a vignette

    The primary reason you use `system.file()` is because you want to access a file that is included in the package. Note that you do the same in the example provided in the man page.

8. Proper way to install a Bioconductor package is with `BiocManager::install("easylift")` (this will work once the package is added to Bioconductor). In particular, Bioconductor packages should never be installed directly from GitHub. Please correct the vignette.

9. One interesting feature of `easylift()` is that it can search the files stored locally in **BiocFileCache** for the appropriate chain file. Unfortunately this feature is poorly documented e.g. the man page doesn't even mention it, only the vignette, and I don't see explained how to actually store a chain file in **BiocFileCache**. There are no working examples provided either, and this usecase is not covered by the unit tests, so we don't know if that feature works. Finally, maybe the following error message could be improved to display the name of the chain file that was searched for (this would help the user know what file to search for):
    ```
    > easylift(gr, "hg38")
    Error in easylift(gr, "hg38") : 
      Chain file not specified and not found in BiocFileCache
    ```

10. Why would you do `paste("chr", 1, sep = "")` when you can just do `"chr1"`?

11. Not need to use `paste()` inside `stop()` since the latter will take care of concatenating the supplied string. For example, instead of doing:
    ```
    stop(paste("The genome", to, "is not available or recognized."))
    ```
    just do:
    ```
    stop("The genome ", to, " is not available or recognized.")
    ```

Thanks,
H.

**Comment by nahid18** [comment]
@hpages Thank you so much for such comprehensive review! I will go through each and resolve the issues.

**Comment by mikelove** [comment]
Thank you @hpages for your time in reviewing the package (and for your initial code and help on Slack)

Re: point 7, I can make the vignette sentence more clear. The point is that, I have had many users see `system.file()` in a vignette, where it is referring to an example file for importing data, and then they think they need to use `system.file()` on their end also, when in fact they can point directly to the file. For example, I've even had users think they need to put a file into a package so they can use `system.file()` to then read in that file! So I just wanted to make the point that, while the vignette uses `system.file()` they don't need to use that function in their workflow.

**Comment by hpages** [comment]
> So I just wanted to make the point that, while the vignette uses system.file() they don't need to use that function in their workflow.

I understand the concern as I've seen users being confused by the use of `system.file()` in vignettes or examples too. But that's typically because people don't understand what the purpose of `system.file` is. So I still think it's better to explain what the real purpose of `system.file` is (so they don't get the wrong idea). If you are still worried that people might be confused, then you're welcome to provide very explicit guidance e.g. with something like:

    # here, we use the `system.file()` function because the chain file is in the
    # package (however if you need to point to any other file on your machine,
    # just do 'chain <- "path/to/your/file"'):
    chain <- system.file("extdata", "hg19ToHg38.over.chain.gz", package="easylift")

Would that work?

**Comment by mikelove** [comment]
Great suggestion

**Comment by nahid18** [comment]
@hpages We have resolved all the issues according to your insightful comments and pushed to bioconductor

- [x] 1. Updated description texts
- [x] 2. Moved and removed GenomicRanges
- [x] 3. Added `\seealso` section
- [x] 4. Indentations are fixed with RStudio
- [x] 5. Applied both changes
- [x] 6. Markdown extension fixed
- [x] 7. Added the comment to clarify `system.file()` usage
- [x] 8. Corrected installation command
- [x] 9. Added `BiocFileCache` documentation and unit tests. Also updated the error message to show proper filename
- [x] 10. Removed unnecessary `paste` 
- [x] 11. Removed unnecessary `paste` inside `stop`

**Comment by hpages** [comment]
Thanks @nahid18 for the improvements.

- About item 7.: please note that `system.file()` usage still needs to be corrected in various places.

- About item 9: It's preferrable to use `\dontrun{}` instead of commenting out code that should not be run in the examples:
    ```
    \dontrun{
      # To use `BiocFileCache` for the chain file, you can add it to the cache as follows:
      chain_file <- "/path/to/your/hg19ToHg38.over.chain.gz"
      bfc <- BiocFileCache()
      bfcadd(bfc, chain_file)

      # Then, you can use it in `easylift` like this:
      easylift(gr, "hg38")
    }
    ```
  Also please note that **BiocFileCache** is only in `Imports` so does not automatically get added to the search path when loading **easylift**. This means that the above code needs to explicitely load the package with `library(BiocFileCache)` before it can use it.

  Finally about this error message:
    ```
    > easylift(gr, "mm10")
    Error in easylift(gr, "mm10") : 
      Chain file not specified and not found in BiocFileCache. Look for a chain file
      named 'hg19ToMm10.over.chainhg19ToMm10.over.chain' for liftover to 'mm10' in
      your BiocFileCache or provide the 'chain' argument with the file path.
    ```
  2 things:
    - The name of the chain file (`hg19ToMm10.over.chainhg19ToMm10.over.chain`) seems wrong.
    - I don't think it makes sense to tell the user to look for the chain file in their BiocFileCache. If the file was there, one would hope that `easylift()` would have found it. My original suggestion was only to display the name of the chain file in the error message, so the user knows what to look for. However note that they would typically look for the file on the UCSC Genome site, and download it from there. This is why knowing the name of the file is very useful.

Thanks again,
H.

**Comment by nahid18** [comment]
@hpages 

1. Added `\dontrun{}` 

2. Moved the `BiocFileCache` package under the `Depends` field instead of `Imports`, therefore no need to explicitly import that package.

3. Now the error message will be like this:
```
Error in easylift(gr, to) : hg19ToMm10.over.chain file not found!
```

4. Corrected the usage of `system.file()` in the remaining places. Changed this:
```
chain <- system.file("extdata/hg19ToHg38.over.chain.gz", package = "easylift")
```
to this:
```
chain <- system.file("extdata", "hg19ToHg38.over.chain.gz", package = "easylift")
```

**Comment by hpages** [comment]
Looks good.

But why reduce the error message so much? Now it gives the name of the file, which is good, but it no longer mentions the 2 other things that were originally mentioned: (1) that the user didn't specify the chain file, and (2) that the file was not found _in BiocFileCache_. This information really helps the user understand what's going on, so it's good to keep it. What about something like:
```
Chain file not specified and hg19ToMm10.over.chain file not found in BiocFileCache default location.
```
Additionally, by looking at your code, it seems that it's not strictly looking for a file named `hg19ToMm10.over.chain`, but for any file that contains the `hg19ToMm10.over.chain` pattern in its name. The error message should reflect that in order to not mislead the user.

Sorry for the nitpicking but I strongly believe in carefully formulated error messages. They can really make the difference between a friendly user experience and a frustrating one.

Getting the chain file from the BiocFileCache default location is a well defined and contained task, so the code in charge of it would typically be in a helper function e.g.:
```
### 'from' and 'to' are expected to be single strings containing UCSC genome names.
.get_chain_from_BiocFileCache <- function(from, to) {
    bfc <- BiocFileCache()
    capTo <- paste0(toupper(substr(to, 1, 1)), substr(to, 2, nchar(to)))
    trychainfile <- paste0(from, "To", capTo, ".over.chain")
    q <- bfcquery(bfc, trychainfile)
    if (nrow(q) == 0)
        stop(...)
    bfc[[q$rid[1]]]
}
```
This is just standard good coding practice (it makes the code easier to read, test, debug, and maintain). 

Finally please note that calling `bfcadd()` _always_ adds the specified resource to the cache, regardless of whether the resource is already there or not. So it would be good to check for the presence/absence of the resource before actually adding it to the cache e.g.:
```
if (nrow(bfcquery(bfc, basename(chain_file))) == 0)
    bfcadd(bfc, chain_file)
```
This applies to the various places where you show how to use `bfcadd()` (e.g. in your README files, vignette, and man page), even if the code is not evaluated, for the sake of encouraging good practices. Note that, because of this, the same resource gets added over and over again to the cache each time the **easylift** unit tests are run (via `R CMD check` or directly with `testthat::test_check("easylift")`). However, for the unit tests, a better alternative is to use a temporary location for the cache. This has 2 benefits: (1) whatever you add to the cache will not persist across sessions, and (2) the unit tests won't alter the real cache.

Thanks again for your work on this.

H.

**Comment by mikelove** [comment]
Thanks Hervé for these detailed improvements. @nahid18 I will fix the temporary BFC location for testing now, maybe you can take the other todos?

**Comment by mikelove** [comment]
Here is how I would recommend the temp location for testing (also generalizes the code a bit):

https://github.com/nahid18/easylift/commit/5aaae8d8ca28a36fddd394f0177b33488a9de2bc

**Comment by nahid18** [comment]
@hpages Thank you so much for such thorough code review and great insights!

@mikelove Thank you so much! I will handle the other todos and will push as soon as I am done.

**Comment by nahid18** [comment]
@hpages 

1. Error message now updated
```
"Chain file not specified and filename with ", trychainfile,  " pattern not found in BiocFileCache ", bfc_str, " location."
```
Here, `trychainfile` is the filename and `bfc_str` is either `default` or `provided` due to the fact that we added a new argument `bfc` primarily for testing.

2. Three new helper functions added to clean the code a bit

3. Checking if the file already exists in cache prior to executing `bfcadd` has been added everywhere in documentation

4. `tempfile()` has been utilized for `BiocFileCache` unit-testing

5. Increased test coverage

**Comment by hpages** [comment]
Thanks for the improvements.

It's easy to forget to name the `bfc` argument when providing a BiocFileCache object, in which case one gets this:
```
> easylift(gr, "mm10", BiocFileCache())
Error in as.character.default(text) : 
  no method for coercing this S4 class to a vector
```
Maybe error handling could be a little bit better. Generally speaking it's a good idea to perform some basic sanity checks on the user input.

Note that we should not directly check the class of an object with `class(x) == "some class"` or `class(x) %in% "some class"`. Instead we should use `inherits(x, "some class")` for an S3 class and `is(x, "some class")` for an S4 class.

Finally those 3 lines:
```
    is_bfc_faulty <- .get_bfc_status(bfc)
    if (is_bfc_faulty) {
      bfc <- BiocFileCache()
    }
```
should really be part of the `.get_chain_from_BiocFileCache()` helper.

Almost there. Thanks again!

**Comment by nahid18** [comment]
@hpages 

- [x] added a new helper function to perform sanity check on user input
- [x] moved if logic inside `.get_chain_from_BiocFileCache()`

Thank you so much for your help!

**Comment by nahid18** [comment]
@hpages 

- [x] added a new helper function to perform sanity check on user input
- [x] moved if logic inside `.get_chain_from_BiocFileCache()`
- [x] more tests

Thank you so much for your help!

**Comment by nahid18** [comment]
@hpages

- [x] added a new helper function to perform sanity check on user input
- [x] moved if logic inside .get_chain_from_BiocFileCache()
- [x] more tests

Thank you so much for your help!

**Comment by hpages** [comment]
Hi @nahid18 ,

This test is incorrect:
```
  if (!is(x, "GRanges") && !isS4(x)) {
    stop("Please provide a valid 'GRanges' object 'x'.")
  }
```
because it's going to evaluate to `FALSE` if `x` is an S4 object that is not a GRanges object (e.g. `x` is an Rle, DataFrame, Biostrings, SummarizedExperiment, BiocFileCache, etc... object).

We _know_ that GRanges is an S4 class, this is not going to change, so you just need to do `if (!is(x, "GRanges")) ...`. If you wanted to check that an object `x` is a data.frame or derivative, then you should do `inherits(x, "data.frame")`, because data.frame is an S3 class. Or even better, you'd be using `is.data.frame()` which is a simple helper function that just does `inherits(x, "data.frame")`.

Same problem with:
```
  if (!is(bfc, "BiocFileCache") && !isS4(bfc)) {
     stop("Please provide a 'BiocFileCache' object 'bfc'.")
  }
```

This `R CMD check` NOTE:
```
* checking R code for possible problems ... [30s/30s] NOTE
.perform_sanity_check: no visible global function definition for is
Undefined global functions or variables:
  is
Consider adding
  importFrom("methods", "is")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
```
should be addressed. `is()` is defined in the **methods** package so the package must be listed in `Imports`, and the `is` symbol must be imported. Alternatively, in the particular case of the **methods** package, we often recommend to import the full namespace with `import(methods)`, instead of trying to import individual symbols selectively.

Note that the biocViews term `Workflow` is for _workflow_ packages, but **easylift** is a _software_ package, not a workflow package. Also `BasicWorkflow` can't be used here either because it's an offspring of `Workflow`. Maybe you meant to use `WorkflowStep` instead? This term is an offspring of `Software` i.e. it is part of the `Software` sub-ontology. There are probably a few other terms from the `Software` sub-ontology that you'd want to consider adding to the `biocViews` field.

About this BiocCheck NOTE:
```
* Checking for recommeded fields in DESCRIPTION...
    * NOTE: Provide 'BugReports' field(s) in DESCRIPTION
```
Probably a good idea. The `BugReports` field should preferably be the URL to the issues in the GitHub repo. Some packages set `BugReports` to the URL of the Bioconductor support site but that site is more for questions about usage of the software.

Thanks,
H.

**Comment by nahid18** [comment]
Hi @hpages,

- [x] `!isS4()` part has been removed from both places
- [x] `methods` package has been added in both `DESCRIPTION` under `Imports` field and in `NAMESPACE`
- [x] `biocViews` has been updated to be `Software, WorkflowStep`. Added more views recommended by biocCheck as well: `Sequencing, Coverage, GenomeAssembly, DataImport`.
- [x] `BugReports` field has been added.

`R CMD check` now shows 0 NOTE, `biocCheck` shows 4 NOTES

Thank you so much for your patience.

**Comment by hpages** [comment]
Package is good to go. Thanks a lot!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nahid18.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("easylift")`. The package 'landing page' will be created at

https://bioconductor.org/packages/easylift

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
