### ISSUE TITLE
plasmut package submission

### ISSUE THREAD

**Issue by aditharun** [Bioconductor/Contributions#3127]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cancer-genomics/plasmut

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by aditharun** [comment]
Hi @Kayla-Morrell , the one error in the build report was the BiocCheckGitClone() where some . files were being tracked. I updated the .gitignore and reran BiocCheckGitClone() and it now passes. Please let me know if there is anything else to be done for approval!

**Comment by Kayla-Morrell** [comment]
@aditharun - You need to push a version bump with these changes in order to kick off another build. See our documentation [here](https://contributions.bioconductor.org/git-version-control.html#new-package-workflow) for pushing upstream. Without a clean build report I can not move forward with my initial review. 

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@aditharun - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [x] REQUIRED: In the README file, the Installation section should also include
  Bioconductor installation instructions. See Bioconductor package installation
instructions on any current Bioconductor package landing page.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
  'comment=c(ORCID="...")'.
- [x] REQUIRED: Update R version dependency from 4.1.0 to 4.3.0.
- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with a
  relevant link to the GitHub for reporting issues. 
- [ ] SUGGESTION: If you do not include the 'BugReports:' field we strongly
  encourage adding the 'URL:' field with a link to the source code repo (usually
github).

## NEWS

- [ ] REQUIRED: It's great practice to include a NEWS file. However, it seems
  that the NEWS file is not formatted properly. Please see our documentation
[here](https://contributions.bioconductor.org/news.html) for how to format this
file. If done correctly you should be able to produce the NEWS file when running
`utils::news(package="plasmut")`.

## Data

- [ ] REQUIRED: Thank for including documentation for the extdata file in the
  `inst/script` directory. There does need to be some information added to the
script about how the data was generated and/or source information. Maybe add
another file specifically for the "cairo5-matched-sequencing.csv" file, which
could be just a text description stating how that file was created or where it
came from.

## Vignette

- [x] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install and download the package from Bioconductor.

## Man pages

- [x] REQUIRED: You do not need to document a function that is being used
  internally and is not exported to the user, this would be in reference to
`importance_samples()`. 
- [x] REQUIRED: The man page for `model_w()` needs to have a runnable example using
  that function. It currently just uses `importance_sampler()`.

## R code

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 45
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. There are 86 lines that are not.

Best,
Kayla

**Comment by aditharun** [comment]
Hi @Kayla-Morrell, all of the required updates have been made! Thanks!

**Comment by Kayla-Morrell** [comment]
@aditharun - You need to push these changes with a valid version bump so a new build can be triggered, as I mentioned previously.

**Comment by aditharun** [comment]
Hi @Kayla-Morrell, pushed off a new build - looking forward to your decision. Thanks!

**Comment by Kayla-Morrell** [comment]
@aditharun - Thank you for making those changes. There are two points above that were not addressed. Please address these issues and then I'll be happy to accept the package.

## NEWS

- [ ] REQUIRED: It's great practice to include a NEWS file. However, it seems
that the NEWS file is not formatted properly. Please see our documentation
[here](https://contributions.bioconductor.org/news.html) for how to format this
file. If done correctly you should be able to produce the NEWS file when running
utils::news(package="plasmut").

## Data

- [ ] REQUIRED: Thank for including documentation for the extdata file in the
inst/script directory. There does need to be some information added to the
script about how the data was generated and/or source information. Maybe add
another file specifically for the "cairo5-matched-sequencing.csv" file, which
could be just a text description stating how that file was created or where it
came from.

Best,
Kayla

**Comment by aditharun** [comment]
Hi @Kayla-Morrell - I believe the news file is properly formatted now and I added a description to data.R for the matched-sequencing file. Please let me know if that is an appropriate way to add this description or if there is a better way?

**Comment by Kayla-Morrell** [comment]
@aditharun - The news file looks good now. Since the matched-sequencing file is in the 'inst/extdata/' directory, the documentation should not be in a man page but in the 'inst/script/' directory instead. I would suggest taking the description you added to data.R and put it in a text file within 'inst/script/'. That should take care of the requirement.

**Comment by aditharun** [comment]
Hi @Kayla-Morrell, thanks! Just, updated with a txt file in inst/script!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aditharun.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("plasmut")`. The package 'landing page' will be created at

https://bioconductor.org/packages/plasmut

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
