### ISSUE TITLE
regionalpcs

### ISSUE THREAD

**Issue by tyeulalio** [Bioconductor/Contributions#3131]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tyeulalio/regionalpcs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Tiffany, @tyeulalio 
Thank you for your submission. 
Please see the review below. 
Best,
Marcel

---

# regionalpcs

* The package looks sound. It should use Bioconductor functionality such
as `TxDb.*` and `GenomicFeatures`. You can also download methylation data from
a number of packages that provide it (e.g., `curatedTCGAData` (disclaimer: my
package), `GenomicDataCommons`, `RTCGA.methylation`, `TCGAbiolinks`, etc.)

## DESCRIPTION

* Looks good

## NAMESPACE

* Minimal number of exports, good.
* Avoid using magrittr pipe `%>%` and use the native pipe `|>`.

## vignettes

* Add `author:` in yaml header
* First part of the vignette seems to be closer to a workflow. Can it be
reduced just to highlight the package functionality?

## R

* Use `match.arg` in `compute_regional_pcs` (and others) and use `c("gd",
"mp")` as the default `pc_method` argument.
* Use Bioconductor infrastructure instead of providing your own data. There
are packages that allow you to download promoter regions and methylation data
and possibly avoid using `liftOver`.

**Comment by tyeulalio** [comment]
Hello Marcel, @LiNk-NY 
Thank you for the helpful review. I have incorporated your feedback into the newest package update. I've responded to each comment below with the changes that were implemented. 
Best,
Tiffany


> # regionalpcs
> * The package looks sound. It should use Bioconductor functionality such
>   as `TxDb.*` and `GenomicFeatures`. You can also download methylation data from
>   a number of packages that provide it (e.g., `curatedTCGAData` (disclaimer: my
>   package), `GenomicDataCommons`, `RTCGA.methylation`, `TCGAbiolinks`, etc.)

Thanks for the suggestion, I wasn't familiar with many of these packages. I removed all of the data that I had included with my package. I opted for TxDb+minfi to get the genomic annotations and a small example methylation dataset for the vignette.

> ## DESCRIPTION
> * Looks good
> 
> ## NAMESPACE
> * Minimal number of exports, good.
> * Avoid using magrittr pipe `%>%` and use the native pipe `|>`.

I replaced all pipes with the native pipe throughout the entire package.

> ## vignettes
> * Add `author:` in yaml header
> * First part of the vignette seems to be closer to a workflow. Can it be
>   reduced just to highlight the package functionality?

Added author to yaml header as requested. I cut out the beginning of the vignette and went straight from loading the data to using the package.

> ## R
> * Use `match.arg` in `compute_regional_pcs` (and others) and use `c("gd", "mp")` as the default `pc_method` argument.
> * Use Bioconductor infrastructure instead of providing your own data. There
>   are packages that allow you to download promoter regions and methylation data
>   and possibly avoid using `liftOver`.

Thanks, `match.arg` is quite useful! I used this in all functions where appropriate. As mentioned above, I removed all data that was included with the package and used Bioconductor packages instead. No longer using liftOver in the package.

**Comment by LiNk-NY** [comment]
Hi Tiffany, @tyeulalio 
I'm glad to hear that you were able to re-use existing datasets!
The package looks good. 

Best, 
Marcel 

PS. Note that you can use switch to obtain the appropriate function if both function calls have the same signature: 

```r
compute_dimension <- function(x, var_explained, noise_select, method = c("gd", "mp"), verbose = FALSE) {
  method <- match.arg(method)
  FUN <- switch(
    method, 
    gd = PCAtools::chooseGavishDonoho,
    mp = PCAtools::chooseMarchenkoPastur
  )
  FUN(var.explained = var_explained, nose = noise_select)
}
```

**Comment by tyeulalio** [comment]
Hi Marcel, @LiNk-NY 

Thanks for the tip! I updated the `compute_dimension` function using the switch statement.

Best,
Tiffany

**Comment by LiNk-NY** [comment]
Thanks for making those changes. Your package has been accepted. 
Best,
Marcel

**Comment by tyeulalio** [comment]
Thank you Marcel! @LiNk-NY 
That's great news! I appreciate all of your time and help with my package.
Best,
Tiffany

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tyeulalio.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("regionalpcs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/regionalpcs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
