### ISSUE TITLE
iSEEpathways

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/Contributions#3133]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/iSEE/iSEEpathways

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by kevinrue** [comment]
Watchers: @csoneson @federicomarini @LTLA @tomsing1

**Comment by federicomarini** [comment]
IIRC, we are not allowed to have the Remotes field populated in the description.
But now that is probably not needed as iSEEde is already on Bioc?

**Comment by kevinrue** [comment]
Woopsidaisies. Missed that in my latest round of proofreading 😇 

**EDIT:** fixed.

**Comment by lshep** [comment]
**Description**

- [ ] Perhaps add `ShinyApps` to the biocViews list. 


**Namespace**

- [ ] Do all the `.` methods need to be exported?  Noramlly a start with
  indicates an internal function?

**Vignette**

- [ ] Is there suppose to be a connection betweeen pathwyas analysis Table 1 and
  GSEA enrichment plot 1 views? If I select a view in one should it highlight or
  something in the other? When I run the example vignette for iSEEpathways, it
  will only show for the initially select pathwy_1350. Should I be able to
  change that at all? I can't figure out the interactivity of this vignette?

**Comment by federicomarini** [comment]
Thanks @lshep for the review!
We started working on your points in a dedicated branch (`bioc_review`), we will get back to you once we addressed them all.

**Comment by kevinrue** [comment]
Agree 💯 on all points.

1)
Will add `ShinyApps` in the next version.

2)
Yes the `.` methods need to be exported. We got away with this now a couple of times when submitting iSEE extensions, but I agree that those methods need to be renamed without `.`. It's a leftover from the early days of iSEE when those methods were internal.
If you don't mind letting it slide one last time, I would like to tackle that deprecation/renaming in the next release cycle (Oct23-Apr24)

3)
'pathway' panels cannot yet transmit 'outgoing' selections due to how selections are implemented in iSEE (rows = genes, columns = samples). I've started discussing the implementation of such functionality with @LTLA , but that will require some careful refactoring in iSEE itself, which is definitely not going to happen before the next release cycle.

I look forward to your thoughts on points 2 and 3.

**Comment by federicomarini** [comment]
> Yes the . methods need to be exported. We got away with this now a couple of times when submitting iSEE extensions, but I agree that those methods need to be renamed without .. It's a leftover from the early days of iSEE when those methods were internal.
If you don't mind letting it slide one last time, I would like to tackle that deprecation/renaming in the next release cycle (Oct23-Apr24)

On this one: I am thinking of the "best alternative" on how to do that. Would a prefix in front of each function name be *good enough*? We are happy to comply with whatever best option is used in this or other ecosystems where that is also something one cannot escape.

**Comment by lshep** [comment]
as long as 3 is known and there is a valid explanation. Just was confused as generally there is interaction and customization in an app launched.   2. Yes we can let that '.' slide for now in favor of a future rename/deprecation.  I think the immediate will be adding the biocView and you can be all set for now.

**Comment by federicomarini** [comment]
>  I think the immediate will be adding the biocView and you can be all set for now.

Perfect, PR is already on its way with that and a couple of other meaningful ones we missed in the first place.
@kevinrue we just need to trigger the SPB, and we continue the renaming conversation on Slack 😉

**Comment by kevinrue** [comment]
I’ll merge and trigger the SPB tonight.

The rest is indeed an overdue discussion on slack :)

**Comment by kevinrue** [comment]
Hold that thought. Still a bunch of WARNINGS that can be easily resolved before adding to BioC :)

**Comment by kevinrue** [comment]
github action in progress, locally BiocCheck says only 4 NOTES left, which I'm all happy with (line width, 4 space tabs, cannot check maintainer on mailing list, BiocViews).

When github action completes, I'll merge and push to the bioc remote to trigger the SPB.

Stay tuned :)

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinrue.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("iSEEpathways")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iSEEpathways

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
