### ISSUE TITLE
ggsc

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/Contributions#3136]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/ggsc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by GuangchuangYu** [comment]
don't know why there is no new build triggered. The error, <https://github.com/Bioconductor/Contributions/issues/3136#issuecomment-1719634193>, is due to a typo of importing `theme_minimal()` from `ggplot2` and it has been fixed two days ago.

**Comment by lshep** [comment]
Please correct the Errors, Warnings, and Notes in the build report before a more in depth review will take place.  Please also note and correct the message
```
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
```

**Comment by GuangchuangYu** [comment]
@lshep We have fixed all the issues to satisfy BiocCheck.



Currently, our visualization methods support `SingleCellExperiment`, `SpatialExperiment`, and `Seurat` objects. 


For the note you mentioned, we can't do anything about it because it is an issue with the Seurat package.  


```
> asNamespace(ns="Seurat")
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
<environment: namespace:Seurat>
```

**Comment by GuangchuangYu** [comment]
> @lshep We have fixed all the issues to satisfy BiocCheck.
> 
> Currently, our visualization methods support `SingleCellExperiment`, `SpatialExperiment`, and `Seurat` objects.
> 
> For the note you mentioned, we can't do anything about it because it is an issue with the Seurat package.
> 
> ```
> > asNamespace(ns="Seurat")
> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
> which was just loaded, will retire in October 2023.
> Please refer to R-spatial evolution reports for details, especially
> https://r-spatial.org/r/2023/05/15/evolution4.html.
> It may be desirable to make the sf package available;
> package maintainers should consider adding sf to Suggests:.
> The sp package is now running under evolution status 2
>      (status 2 uses the sf package in place of rgdal)
> <environment: namespace:Seurat>
> ```


The issue will be fixed in the next release of Seurat. Currently, we can ignore this note.

**Comment by lshep** [comment]
**general**

- [ ] Makefile looks like a helper file for you and should not be in git or
  git tracked


**docs**

- [ ] have a package level man page so if a naive user does `?ggsc` they get an
  overview or pointer how to get started.

**vignette**

- [ ] Please include an intro that explains why it is being included in
  Bioconductor and any comparisons to similar packages.  See
  [vignette](http://contributions.bioconductor.org/important-bioconductor-package-development-features.html#bioc-vignette).
  There also is no textual context to what the code in the vignette is
  doing. Why are the plots significant, important, different from what is
  already provided in Bioconductor or by default. 

- [ ] You have some commented out code in the vignette coding sections. do not
  include code that is not part of the example. Similarly in the R code if there
  are commented unused code chunks please remove. 


- [ ] Why is the transformation from a dgTMatrix to dgCMatrix necessary?

**Comment by xiangpin** [comment]
+ The `Makefile` is not just the helper file for a single developer, it is useful for developers to `build` or `check` ... on the local computer since it can save time by collecting.

+ the `ggsc` man and `vignette` will be updated as quickly as possible.

+ Yes, it is not necessary to  convert `dgTMatrix`  to `dgCMatrix`.

**Comment by lshep** [comment]
Please remember to push updates to git.bioconductor.org to trigger a new build and comment back here with the updates when you are ready for a re-review.

**Comment by GuangchuangYu** [comment]
1. The `Makefile` is for maintaining the package and it is added in the `.Rbuildignore`. We have this file in several BioC packages (e.g., clusterProfiler and ggtree) and I think it is fine to have it.
2. A package level man page is added
3. vignette have updated as suggested.
4. We have change to using `dgTMatrix` instead of `dgCMatrix`

**Comment by GuangchuangYu** [comment]
> * WARNING: Empty or missing \value sections found in man pages.

@lshep The warning reported by `BiocCheck` is weird. All the man pages of exported functions have `\value` session. 

We can check the `.Rd` files in the man folder and all files contain `value` session except the `ggsc-package.Rd` and `reexports.Rd`.

**Comment by GuangchuangYu** [comment]
@lshep By adding `\value` session in `reexports.Rd`, all issues have been solved.

**Comment by lshep** [comment]
Thank you. everything looks good now.  I am happy to accept.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GuangchuangYu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggsc")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggsc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
