### ISSUE TITLE
igvShiny submission

### ISSUE THREAD

**Issue by gladkia** [Bioconductor/Contributions#3155]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gladkia/igvShiny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Arek, @gladkia 

Thank you for your patience and submission. 
Please see the review below. 

Best regards,
Marcel

--- 

# igvShiny #3155

## DESCRIPTION

* Include `URL`, and `BugReports` fields
* Wrap `Description` field text to 80 width (and fix typos).
* R dependency should be `R (>= 4.4.0)`.
* Include a more descriptive `Title:`.

## NAMESPACE

* Avoid long function names with dots (`.`). Dots in function names should
generally be used for S3 methods.
* Have you considered using `RCurl::url.exists`?

## vignettes

* Looks good.
* Consider reducing the complexity of the examples by adding a folder argument
for predetermined files in `parseAndValidateGenomeSpec`.
* Minor: Wrap the text to 80 column-width.

## R

* `common.always.available.stock.genomes` along with `basic.offerings` should
be a package constant rather than a function.
* Would it be easier to add the `genomes.json` file to the package rather
than host it on AWS?
* Consider increasing package coverage and using `shinytest2`
```r
> covr::package_coverage()
igvShiny Coverage: 20.53%
R/igvShiny.R: 0.00%
R/GWASTrack.R: 59.68%
R/genomeSpec.R: 88.73%
R/test_igvShiny_package.R: 100.00%
```

**Comment by lshep** [comment]
@gladkia just wanted to check in that you saw the above review comments and are working on updates?

**Comment by gladkia** [comment]
Hi @lshep. Thanks for the reminder :)! 

Yes, I'm working on the updates, supported by @karollayna. I hope we will finish within the next two weeks.

**Comment by gladkia** [comment]
Hi @LiNk-NY,

Thanks a lot for your review. Sorry for the late response.

Please find the summary of the changes made in response to your review:
### DESCRIPTION
* Include URL, and BugReports fields [DONE]
* Wrap Description field text to 80 width (and fix typos) [DONE]
* R dependency should be R (>= 4.4.0). 
    * We will introduce this change latter. Currently, it might affect the users using the package
* Include a more descriptive Title: [DONE]

### NAMESPACE
* Avoid long function names with dots (.). Dots in function names should generally be used for S3 methods [DONE]
* Have you considered using RCurl::url.exists?
    * Thanks for the hint. Done.

### Vignettes
* Consider reducing the complexity of the examples by adding a folder argument for predetermined files in parseAndValidateGenomeSpec.
    *  I've added the issue to work on it in the future (https://github.com/gladkia/igvShiny/issues/64).
* Minor: Wrap the text to 80 column-width. [DONE]

### R
* common.always.available.stock.genomes along with basic.offerings should be a package constant rather than a function.
    * [DONE]
* Would it be easier to add the genomes.json file to the package rather than host it on AWS?
    * We would like to keep the current logic to assure that igvShiny and the library it depends on (igv.js) are in sync ([link](https://github.com/igvteam/igv.js/blob/77d88fac63564111462b010f739ce691ac44c321/js/genome/genomeUtils.js#L3-L4))
* Consider increasing package coverage and using shinytest2
    * We've added the .github pipeline supporting shinytest2 ([link](https://github.com/gladkia/igvShiny/blob/master/.github/workflows/check-bioc.yml)) as well as some shinytests2 tests.

@lshep FYI.

**Comment by LiNk-NY** [comment]
Hi Arek, @gladkia 

Thank you for making those changes. 
See the comments below. 

> * R dependency should be R (>= 4.4.0).
>   
>   * We will introduce this change latter. Currently, it might affect the users using the package

You can also remove the R version dependency from the `Depends` field. Note that once the package is in Bioconductor devel, users will have to use R-devel (4.4.0). 

> * Would it be easier to add the genomes.json file to the package rather   than host it on AWS?
>   
>   * We would like to keep the current logic to assure that igvShiny and the library it depends on (igv.js) are in sync ([link](https://github.com/igvteam/igv.js/blob/77d88fac63564111462b010f739ce691ac44c321/js/genome/genomeUtils.js#L3-L4))

FWIW, in packages like `AnVIL` and `cBioPortalData` we use the strategy to compare md5 sums between local and remote API files and provide a warning when there is a difference. We also have added a push-button GitHub Action to automatically update the API in the package. This is more transparent to the user that hosting a remote file. 

PS. For future development, consider resolving some of the 10 `NOTES` from `BiocCheck` mainly ORCID and 'URL' / 'BugReports' fields, etc.

We have accepted your package. Thank you for your submission. 

Best,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gladkia.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("igvShiny")`. The package 'landing page' will be created at

https://bioconductor.org/packages/igvShiny

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
