### ISSUE TITLE
saseR

### ISSUE THREAD

**Issue by alexandresegers** [Bioconductor/Contributions#3156]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/statOmics/saseR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
havok does not appear to be a CRAN or Bioconductor package?  all package dependencies must be on CRAN or Bioconductor or they cannot be used as a dependency.

**Comment by alexandresegers** [comment]
Dear Reviewer,

I still obtain the BiocCheck error related to registration:

* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/

Nonetheless, both my GitHub account email and email in description (Alexandre.segers@ugent.be) are registered on this site.
What else should I do to avoid this error?

Thank you in advance,
Alexandre

**Comment by lshep** [comment]
We will ignore that error on our side as I can validate you are indeed registered.  We will look into why that is not validating but it is an issue on our end.  Please try to correct as many of the other Warnings and Notes as possible.

**Comment by alexandresegers** [comment]
Dear Reviewer,
 
I tried to correct the warning and notes that were left. However, these are the ones I did not resolve:
 
- Warning: replacing previous import utils::findMatches by S4Vectors::findMatches when loading ASpli
I do not manage to avoid this warning. I have to import ‘ASpli’ for many functions, and even non-exported ones (see later). However, trying to import ASpli as first package (both in vignettes, functions and in description file), or after other packages did not resolve this warning. I assume this is a problem within ASpli itself. For the next release (3.19), I will try to not depend on ASpli.
 
- Unexported objects imported by ':::' calls:
  'ASpli:::.condenseTargetsConditions' 'ASpli:::.counterBin'
  'ASpli:::.counterGenes' 'ASpli:::.counterJbin'
  'ASpli:::.counterJunctions' 'ASpli:::.extractCountColumns'
  'ASpli:::.extractDataColumns' 'ASpli:::.filterJunctionBySample'
  'ASpli:::.generateSamplesNames' 'ASpli:::.junctionsPSI_SUM'
  'ASpli:::.makeClusters' 'ASpli:::.makeCountDataWithClusters'
  See the note in ?`:::` about the use of this operator.
 
One of my functions is a small adaptation from ASpli. Therefore, I did not want to copy all the non-exported functions. The adaptation is however required as in the current implementation, parallelisation is not feasible, nor is using a dataset with all controls. 
 
- * checking R code for possible problems ... [38s/39s] NOTE
.bamToCounts: no visible binding for global variable 'i'
.locusPValues: no visible binding for global variable 'locus'
jcounts: no visible binding for global variable 'df0'
jcounts: no visible global function definition for '.junctionsDiscover'
jcounts: no visible global function definition for '.sumByCond'
jcounts: no visible global function definition for
  '.createGRangesExpJunctions'
jcounts: no visible global function definition for '.e1e2JPIR'
jcounts: no visible global function definition for
  '.extractCountColumns'
jcounts: no visible global function definition for '.getJPSIByOverlap'
Undefined global functions or variables:
  .createGRangesExpJunctions .e1e2JPIR .extractCountColumns
  .getJPSIByOverlap .junctionsDiscover .sumByCond df0 i locus
 
This is mainly due to the imported ASpli functions. I hope this is not of any problem.


    * NOTE: The recommended function length is 50 lines or less. There
      are 11 functions greater than 50 lines.
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 2 lines (0%) are > 80 characters
      long.
    * NOTE: Consider multiples of 4 spaces for line indents; 317 lines
      (9%) are not.

I used a different coding style, and hope this is acceptable. the shorter lines are only ones from the description file which I do not manage to bring to 80 characters. 

I look forward to any feedback.
Best regards,
Alexandre Segers

**Comment by lshep** [comment]
Please consider renaming your vignette. With something as generic as Vignette it can have naming conflicts depending on the order of packages loaded.

**Comment by alexandresegers** [comment]
Dear Reviewer,

Is there already some kind of feedback for our package submission?

Best regards,
Alexandre Segers

**Comment by DarioS** [comment]
The package is in a high quality state. My main concern is that it uses `:::` 18 times to use another package's private functions. Have you contacted developers of ASpli and asked them to make their functions exported? It seems like a lot of ways to break. It is also concerning that ASpli has [a simple warning in development branch](https://bioconductor.org/checkResults/devel/bioc-LATEST/ASpli/) and a [list of unanswered issues on GitHub](https://github.com/chernolab/ASpli/issues). The warning stems from a poorly written NAMESPACE file which does not selectively import the functions which it needs, leading to a clash.

```r
import(S4Vectors)
import(utils)
```

The [main branch](https://github.com/chernolab/ASpli) has not been updated since March 2021 which is coincidentally exactly when the [software was published in a journal](https://academic.oup.com/bioinformatics/article/37/17/2609/6156815). So, it is effectively became neglected immediately after peer review finished. Also, issues raised by Bioconductor core team appear to be ignored.
![image](https://github.com/Bioconductor/Contributions/assets/631218/0ee1b4a2-d8a2-4f5d-ae90-6d3fdee5ff18)

**Comment by alexandresegers** [comment]
Hey DarioS,

I have not contacted the developers of ASpli. However, because you mention that they are not responsive, I doubt that that will have an influence.

I could copy their functions and include them in the saseR package, while citing them properly. In the next update (as release is quite near...) I could further check if I can remove their functions completely.

Would that approach be fine for you? 

Best regards,
Alexandre Segers

**Comment by lshep** [comment]
@alexandresegers I'm not quite sure where the package stands. As far as ASpli, they had a maintainer change recently that may be more active/attentive. You could try reaching out.

**Comment by alexandresegers** [comment]
Dear Reviewer,

I have adapted the code such that no internal functions of ASpli are used. Instead, I have copied/adapted these functions, such that I can use them for my application, as the exported functions of ASpli require a design with at least 2 different groups, while this is not the case for my application. This way, I can also keep my package up to date when ASpli is not maintained.

I hope this solves the remainder of your comments.
Best regards,
Alexandre Segers

**Comment by DarioS** [comment]
One last task for you to complete.

> * Checking for support site registration...
>     * ERROR: Maintainer must register at the support site; visit
>       https://support.bioconductor.org/accounts/signup/

**Comment by alexandresegers** [comment]
Dear Reviewer,

As mentioned before, I already registered, although the system does not recognise it. 


> Dear Reviewer,
> 
> I still obtain the BiocCheck error related to registration:
> 
> * Checking for support site registration...
>   
>   * ERROR: Maintainer must register at the support site; visit
>     https://support.bioconductor.org/accounts/signup/
> 
> Nonetheless, both my GitHub account email and email in description ([Alexandre.segers@ugent.be](mailto:Alexandre.segers@ugent.be)) are registered on this site. What else should I do to avoid this error?
> 
> Thank you in advance, Alexandre




Ishep responded the following.

> We will ignore that error on our side as I can validate you are indeed registered. We will look into why that is not validating but it is an issue on our end. Please try to correct as many of the other Warnings and Notes as possible.




So I think this issue should be alright?

Best regards,
Alexandre

**Comment by lshep** [comment]
@DarioS yes okay to ignore this for now; I have verified they are indeed registered and there is an issue with the validation api that still hope to fix this week (if not today)

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alexandresegers.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("saseR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/saseR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
