### ISSUE TITLE
raerdata

### ISSUE THREAD

**Issue by kriemo** [Bioconductor/Contributions#3160]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rnabioco/raerdata

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by kriemo** [comment]
AdditionalPackage: https://github.com/rnabioco/raer

**Comment by kriemo** [comment]
Regarding the R CMD CHECK `checking compiled code ... WARNING` seen on the package builds.  This warning arises from the use of Rhtslib, which includes source code with `sprintf` usage. From my understanding this is an expected warning, and is found with all packages that use Rhtslib (https://bioconductor.org/checkResults/3.18/bioc-LATEST/Rhtslib/ ).

**Comment by Kayla-Morrell** [comment]
@kriemo - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.18
release is 10/18. Any packages accepted after this date will be included in the
next release.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an
  entire package. However, if there are many functions from a single package
`import()` can be acceptable. One should just be selective with the use of
`import()`.

## Vignette

- [ ] REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the objective, models, etc that distinguish the package
from other packages in the same area. 
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  users how to download the package from Bioconductor.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 74 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 5 lines that are not.

Best,
Kayla

**Comment by kriemo** [comment]
@Kayla-Morrell. Many thanks for the review. I have one quick question before I begin addressing the comments. Is the review in reference to both submitted packages or just the experiment data `raerdata` package?

Thanks,
Kent

**Comment by Kayla-Morrell** [comment]
@kriemo - I'm so sorry I missed the additional package line! This would be a review for just `raerdata`. If you want to work on addressing that review I can work on getting a review together for `rear` and have it posted shortly.

Best,
Kayla

**Comment by kriemo** [comment]
ok great, thank you.

**Comment by kriemo** [comment]
I've made the requested changes to the `raerdata` package and fixed most of the suggested formatting notes

## NAMESPACE
 - [X] SUGGESTION: Generally importFrom() is encouraged over importing an
entire package. However, if there are many functions from a single package
import() can be acceptable. One should just be selective with the use of
import().

*I have replaced all imports with importFrom()*

## Vignette
 - [X] REQUIRED: There should be an 'Introduction' section that serves as an
abstract to introduce the objective, models, etc that distinguish the package
from other packages in the same area.

*I have added an Introduction section with some additional details*

 - [X] REQUIRED: There should be an 'Installation' section that demonstrates to
users how to download the package from Bioconductor.

*I have added an Installation section*

## Unit tests
 - [X] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
https://contributions.bioconductor.org/tests.html

*I have added unit tests to ensure that the package functions return the expected experimentHub resources*

## R code
 - [X] SUGGESTION: For formatting reasons, consider shorter lines. There are 74
lines that are > 80 characters long.

*I have reduced the number of lines > 80 characters down to 2 documentation lines, which reference URLs*

 - [X] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
line indents. There are 5 lines that are not.

*I have fixed this formatting issue*

**Comment by Kayla-Morrell** [comment]
@kriemo - Below is my review for **raer**. I'll work on re-reviewing **raerdata** while you work on addressing these points.

## Data

- [ ] REQUIRED: The `inst/exdata/` data needs accompanying documentation. This
  documentation belongs in `inst/scripts/`. There should be scripts present that
document very clearly how the data was generated and source information. It
should include source URLs and any key information regarding filtering or
processing. It can be executable code, sudo code, or a text description. Perhaps
your README file in `inst/extdata/` should be moved to `inst/scripts/`. 

## Vignette

- [ ] REQUIRED: All code chunks should be executable, except for installation
  code chunks.
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install the package from Bioconductor. This code chunk should
include `eval = FALSE`.
- [ ] SUGGESTION: It is not clear from the table of contents that there is a
  session info section included. I would suggest making this a section that
users could easy jump to instead of having to expand the hidden code chunk.

## Man pages

- [ ] REQUIRED: The `figures/` directory does not belong in `man/`. I would
  suggest moving this directory to `inst/figures/`.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 323 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 217 lines that are not.

Best,
Kayla

**Comment by kriemo** [comment]
@Kayla-Morrell  Many thanks for your prompt review of the `raer` package. I believe I have addressed your comments, with the exception of the request to remove the `man/figures` directory, which I justify in the notes below. The WARNING from the single package builder is the same warning related to the use of `Rhtslib` in the package that I mentioned [previously](https://github.com/Bioconductor/Contributions/issues/3160#issuecomment-1743328867) in the issue.

# Data
 - [X] REQUIRED: The inst/exdata/ data needs accompanying documentation. This
documentation belongs in inst/scripts/. There should be scripts present that
document very clearly how the data was generated and source information. It
should include source URLs and any key information regarding filtering or
processing. It can be executable code, sudo code, or a text description. Perhaps
your README file in inst/extdata/ should be moved to inst/scripts/.

*I have moved the README from `inst/extdata` to `inst/scripts` and updated the README text. I copied the corresponding scripts from `raerdata` referenced in the README into `inst/scripts` and kept only code relevant for making the files present in the `inst/extdata` directory.*
 
# Vignette
 - [X] REQUIRED: All code chunks should be executable, except for installation
code chunks.

*I have modified the code to make it executable (lines 183 - 203)*

 - [X] REQUIRED: There should be an 'Installation' section that demonstrates to
the user how to install the package from Bioconductor. This code chunk should
include eval = FALSE.

*I have added this section (lines 35 - 43)*

 - [X] SUGGESTION: It is not clear from the table of contents that there is a
session info section included. I would suggest making this a section that
users could easy jump to instead of having to expand the hidden code chunk.

*I have made the sessionInfo an entry in the table of contents and removed the html that made the content a hidden code chunk.*

# Man pages
 **- [ ] REQUIRED: The figures/ directory does not belong in man/. I would
suggest moving this directory to inst/figures/.**

*I would like to request an exemption to this required change. The image files included in `man/figures` are referenced as part of the documentation for the package (`?raer`) and used by the pkgdown documentation site for the package. The `man/figures` directory is a standard directory that is supported by CRAN, and the suggested location for images used in the documentation. https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Figures*

*The `man/figures` directory is also currently used by many Bioconductor packages that use pkgdown for their documentation: (e.g. results from a [BioC code search](https://code.bioconductor.org/search/search?q=man%2ffigures%2flogo.png&num=450) for packages that reference an man/figures/logo.png file)*

*I have moved the illustrator file (`raer-logo.ai`) to `inst/misc` as this is not necessary for pkgdown or the R documentation.*

# R code


- [X]  SUGGESTION: For formatting reasons, consider shorter lines. There are 323
lines that are > 80 characters long.

*I have reduced the number of lines > 80 from 323 lines to 70 lines. Most of the remaining
lines > 80 characters are in .Rd documentation files.*

- [X] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
line indents. There are 217 lines that are not.

*I have reduced the number of line indents not multiples of 4 spaces from 217 lines to 115 lines. Most of the remaining problematic lines idents are in .Rd documentation files.*

**Comment by Kayla-Morrell** [comment]
@kriemo - Thank you for making all the necessary changes. I have re-reviewed both **raer** and **raerdata** and everything looks good. I'm more than happy to accept the packages.

Best,
Kayla

**Comment by kriemo** [comment]
Great, thank you so much for all of your help!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kriemo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("raerdata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/raerdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kriemo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("raer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/raer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
