### ISSUE TITLE
phantasusLite

### ISSUE THREAD

**Issue by assaron** [Bioconductor/Contributions#3174]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ctlab/phantasusLite

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@assaron - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.18
release is 10/18. Any packages accepted after this date will be included in the
next release.

## General package development

- [ ] REQUIRED: The README files should include Bioconductor installation
  instructions. See Bioconductor package installation instructions on any
current Bioconductor package landing page. 

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less
  than 3 sentences. Please consider expanding this field and structure it as a
full paragraph.
- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in Authors@R` with
  `comment=c(ORCID="...")`.
- [ ] REQUIRED: Update R version dependency from 4.2 to 4.3.0.
- [ ] SUGGESTION: Provide `BugReports:` field in DESCRIPTION with a relevant
  link to github for reporting issues.
- [ ] SUGGESTION: Provide `URL:` field in DESCRIPTION.

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring and not
  include '.' which indicates S3 dispatch.
- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an
  entire package. If there are many functions from a single package, `import()`
can be acceptable, but usage should be selective.

## NEWS 

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: `inst/testdata/` is not an acceptable directory for data
  included in Bioconductor packages. We allow `inst/extdata/` for raw data and
`data/` for readily availabe data. I would suggest putting this data in
`inst/extdata/` and documentation must be present in `inst/scripts/`. See our
documentation [here](https://contributions.bioconductor.org/data.html#data)
about package data and documentation.
- [ ] REQUIRED: Also, be sure that is data is being download from the web that 
is is completely necessary and be sure to utilize BiocFileCache were possible.

## Vignette

- [ ] SUGGESTION: We strongly suggest using the `BiocStyle` package for
  formatting.
- [ ] REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the objective, models, unique functions, key points,
etc. that distinguish the package from other packages in the same area.
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  users how to install the package from Bioconductor. These installation
instructions should be included in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: We strongly encourage the use of table of contents.
- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and
  include `sessionInfo()`.
- [ ] REQUIRED: Use accessors, don't access S4 class slots via `@` in vignette
  code.

## Man pages

- [ ] SUGGESTION: Non-exported functions do not need to be documented. I would
  suggest adding the tag `@keywords internal` if you would like the man page to
be created but not be present in the function index.
- [ ] SUGGESTION: It's encouraged to have a package man page with an overview of
  the package and links to the main functions. Users should be able to have a
relevant page display with `?phantasusLite`. 

## R code

- [ ] SUGGETSION: Unexported object imported by a ':::' call:
  'rhdf5client:::submitRequest'
- [ ] SUGGESTION: Undefied global functions or variables:
. accession collection_type directory file_name list_dirs
- [ ] REQURIED: Avoid `sapply()`; use `vapply()` instead.
- [ ] REQUIRED: Avoid `1:...`, use `seq_len()` or `seq_along()` instead.
- [ ] REQUIRED: Avoid using `=` for assignment and use `<-` instead.
- [ ] REQUIRED: Avoid the use of `paste` in condition signals.
- [ ] REQUIRED: Avoid redundant `stop` and `warn` in signal conditions.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 65 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There is 1 line that contains tabs.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 354 lines that are not.

Best,
Kayla

**Comment by assaron** [comment]
@Kayla-Morrell thank you for your comments, we've addressed all of the required ones and some of the suggested.

>  REQUIRED: The README files should include Bioconductor installation
    instructions. See Bioconductor package installation instructions on any
    current Bioconductor package landing page.

Now README recommends to install package from Bioconductor.

> REQUIRED: Update R version dependency from 4.2 to 4.3.0.

Done.

> SUGGESTION: Provide BugReports: field in DESCRIPTION with a relevant
link to github for reporting issues.

Done.

>   SUGGESTION: Provide URL: field in DESCRIPTION.

Done.

> REQUIRED: Exported functions should use camel case or underscoring and not
include '.' which indicates S3 dispatch.

The functions were renamed to not contain '.'.

> REQUIRED: inst/testdata/ is not an acceptable directory for data
included in Bioconductor packages. We allow inst/extdata/ for raw data and
data/ for readily availabe data. I would suggest putting this data in
inst/extdata/ and documentation must be present in inst/scripts/. See our
documentation [here](https://contributions.bioconductor.org/data.html#data)
about package data and documentation.

We moved the files to `inst/extdata/testdata` (and removed unused files). 

>   REQUIRED: Also, be sure that is data is being download from the web that
    is is completely necessary and be sure to utilize BiocFileCache were possible.

I believe we do not download any files in the standard meaning: we use HTTP API to access parts of the remote files. Thank you for your suggestion about BiocFileCache, I don't think it can be applied in a straightforward manner, but we will consider it for future versions. Hope that would be OK for now.

> SUGGESTION: We strongly suggest using the BiocStyle package for
formatting.

We're now using BiocStyle::html_document.

> REQUIRED: There should be an 'Introduction' section that serves as an
abstract to introduce the objective, models, unique functions, key points,
etc. that distinguish the package from other packages in the same area.

We've added introduction section.

> REQUIRED: There should be an 'Installation' section that demonstrates to
users how to install the package from Bioconductor. These installation
instructions should be included in an eval = FALSE code chunk.

We've added installation section

> SUGGESTION: We strongly encourage the use of table of contents.

We've added table of contents

> REQUIRED: The last section of the vignette should be 'Session Info' and
include sessionInfo().

We've added session info section

>  REQUIRED: Use accessors, don't access S4 class slots via @ in vignette
    code.

We replaced using '@' with accessor function.

> SUGGESTION: Non-exported functions do not need to be documented. I would
suggest adding the tag @keywords internal if you would like the man page to
be created but not be present in the function index.

Thank you, we didn't know about it. We've added `internal` keyword for all of the non-exported functions.

> REQURIED: Avoid sapply(); use vapply() instead.

We've switched from sapply to vapply

> REQUIRED: Avoid 1:..., use seq_len() or seq_along() instead.

We've removed usage of 1:...

> REQUIRED: Avoid using = for assignment and use <- instead.

Fixed.

> REQUIRED: Avoid the use of paste in condition signals.

We've removed use of `paste` in `message` calls.

> REQUIRED: Avoid redundant stop and warn in signal conditions.

Fixed.

**Comment by Kayla-Morrell** [comment]
@assaron - Thank you for making the necessary changes. I have just one note that needs to be addressed before I can accept the package.

## Data

- [ ] REQUIRED: Thank you for moving the data into an `inst/extdata/testdata/` directory. There needs to be documentation present for the files in this directory. The documentation belongs in `inst/scripts/` and needs to very clearly state how the data was generated and source information. It should include source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. 

Best,
Kayla

**Comment by assaron** [comment]
@Kayla-Morrell 

>  REQUIRED: Thank you for moving the data into an inst/extdata/testdata/ directory. There needs to be documentation present for the files in this directory. The documentation belongs in inst/scripts/ and needs to very clearly state how the data was generated and source information. It should include source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description.

We've added `inst/script/testdata.md` file with the text description of how the files were obtained.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/assaron.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("phantasusLite")`. The package 'landing page' will be created at

https://bioconductor.org/packages/phantasusLite

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
