### ISSUE TITLE
pathlinkR

### ISSUE THREAD

**Issue by travis-m-blimkie** [Bioconductor/Contributions#3179]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hancockinformatics/pathlinkR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by travis-m-blimkie** [comment]
Hello,

I have worked on the package and made the changes need to fix the error identified in the build reports above, pushing everything to the Github "main" branch throughout. Because the issue involved the package being too large, I followed the instructions provided [here](https://contributions.bioconductor.org/git-version-control.html#removing-large-files-from-history-with-bfg-repo-cleaner) and on the [BFG page](https://rtyley.github.io/bfg-repo-cleaner/) to clean the git history and get the package size below 5MB. However, I was unable to push these changes to the Bioconductor git repository (via [these](https://contributions.bioconductor.org/git-version-control.html#new-package-workflow) instructions). I tried pulling/merging from "upstream", and fixing the resulting conflicts, but now it says I'm ahead of "origin/main" by 133 commits, and I'm worried a push to Github may mess up the fixes I've done.

What's the recommended solution here? Is it possible to have the Bioconductor version of pathlinkR be updated from the current Github version? Maybe a fresh clone of the repository? That way all the changes I've made on Github won't be overwritten.

I'm new to this process, so if there's something I'm missing please let me know.

Cheers!

**Comment by lshep** [comment]
Yes we don't allow force pushes to the git.bicoonductor.org repo but we can reset it on our side from the github.  I will try to get to this later today.

**Comment by travis-m-blimkie** [comment]
Perfect, thank you so much!

**Comment by HelenaLC** [comment]
First round of comments to get things started... Please respond back with what has/not been addressed, or if anything's unclear- happy coding.

For future reference: when first submitted to Bioconductor, a package should have pre-release version 0.99.0. I don't think this will be possible to implement now, as decreasing the version will not trigger a new built... but please checkout the info provided [here](https://contributions.bioconductor.org/description.html?q=version#description-ver) regarding correct versioning of Bioc packages.

**major:**

- I wonder whether the package is interoperable with other existing Bioc infrastructure; specifically, the vignette is limited to `DESeq` results- what about `DESeq2` and `edgeR`? In principle, the output of these frameworks is quite similar, and they should be supported. For example, `eruption()` should expose arguments to specify logFC and (adjusted) p-value columns rather than hard-coding these and limiting the function to `DESeq` only. Running the `?edgeR::topTags` example, I don't see what this type of output should not work just the same. I would urge you to make the package more flexible in order to work with other dominant frameworks by 1. exposing relevant parameters to the users, 2. determining the origin of the input programmatically (and adjusting function-behavior accordingly), and 3. failing when both is unsuccessful. (similarly, other functions could expose more arguments as to not enforce a very specific naming scheme of, e.g., `pValueAdjusted` for pathways...)

- Somewhat related to the above, Bioc's standard infrastructure for RNA-seq data is the S4 `SummarizedExperiment` class (SE). Meanwhile, the entire package works with `data.frame`s only and is written in `tidyr`-style. *Where applicable*, I'd ask that users may also be able to provide a SE instead, in which case corresponding pieces of information (logFC etc.) are extracted from the `rowData`. If the point above is taken care of, this should be simple to realize; i.e., determine what's needed (logFC, FDR, ...) > get it from the input (whatever that may be) > execute.

**minor:**

# DESCRIPTION

- [ ] update R version dependency from 4.2.0 to 4.3.0
- [ ] `LazyData:` should be set to `false` or removed (see [here](https://contributions.bioconductor.org/description.html?q=laz#description-lazydata))
- [ ] consider adding a `URL:` field point to https://github.com/hancockinformatics/pathlinkR

# documentation

- [ ] in the README, please include Bioc installation instructions using `BiocManager::install()`
- [ ] consider adding a package help/*.man* package (`?pathlinkR`), e.g., briefly summarizing the package's functionality, hyperlinking key function etc.
- [ ] the `data/` help-pages is incorrectly formatted, I believe; the long pieces of text should probably be preceded by a `@description` tag (by default, the 1st line is taken as `@title`)
- [ ] all `data/` are well described in terms of data structure, but source information is missing (see [here](https://contributions.bioconductor.org/docs.html?q=data#data-man) for details)
- [ ] `dontrun` flags in examples are generally *not allowed*, and `if (FALSE)` in does just that in a sneaky way... (e.g., *pathnetGGraph.R*; overall I see it 4 times)

# vignette

- [ ] consider using `BiocStyle` to hyperlink external packages, e.g., `r BiocStyle::Biocpkg("DESeq2")` (there are analogous functions of packages hosted through CRAN and GitHub) 
- [ ] for clarity, I'd suggest distinguishing between variables/arguments/classes and functions by adding parentheses, e.g., `ppiBuildNetwork()` and `ppiPlotNetwork()` in lines 118+; this is sometimes, but not always done; consistency here would be nice 

# code

- [ ] regarding `tests/`, I am getting various *warnings* from `devtools::test_coverage()`, which isn't great. Ideally, unit tests should run cleanly, and I'd highly recommend addressing these to the best of your abilities
- [ ] avoid `1:...` and use `seq_len/along()` instead (*ppiExtractSubnetwork.R* line 168)

**Comment by travis-m-blimkie** [comment]
Thanks for the feedback and suggestions! I'll get to work on making changes, and come back with updates/questions.

**Comment by travis-m-blimkie** [comment]
I have made (nearly) all the changes as outlined in the "minor" section, and will start working on the "major" changes r.e. input classes. 

For the warnings from `devtools::test()`, I've fixed what I can, but there are a few I don't think I can fix, outlined below. Open to suggestions for these:
- Adding new snapshot: Only appears on the first run of `devtools::test()`. Any subsequent tests don't produce this warning.
- Removed "x" rows containing missing values (`geom_label_repel()` or `geom_text_repel()`): Some of the plotting functions with point labels (e.g. `eruption()`) use NAs in the label column to prevent the plot from becoming too crowded, or because we only want to label a user-selected subset of points.
- Using the `size` aesthetic in this geom was deprecated in ggplot2 3.4.0: This seems to be coming from the `ggraph` dependency, and appears when running their example, found [here](https://ggraph.data-imaginist.com/#an-example).

***

Updated to-do list for the rest:

## DESCRIPTION
- [x] update R version dependency from 4.2.0 to 4.3.0
- [x] consider adding a URL: field point to https://github.com/hancockinformatics/pathlinkR
- [x] LazyData: should be set to false or removed (see [here](https://contributions.bioconductor.org/description.html?q=laz#description-lazydata))

## Documentation
- [x] in the README, please include Bioc installation instructions using BiocManager::install()
- [x] consider adding a package help/.man package (?pathlinkR), e.g., briefly summarizing the package's functionality, hyperlinking key function etc.
- [x] the data/ help-pages is incorrectly formatted, I believe; the long pieces of text should probably be preceded by a @description tag (by default, the 1st line is taken as @title)
- [x] all data/ are well described in terms of data structure, but source information is missing (see [here](https://contributions.bioconductor.org/docs.html?q=data#data-man) for details)
- [x] dontrun flags in examples are generally not allowed, and if(FALSE) in does just that in a sneaky way... (e.g., pathnetGGraph.R; overall I see it 4 times)

## Vignette
- [x] consider using BiocStyle to hyperlink external packages, e.g., `BiocStyle::Biocpkg("DESeq2")` (there are analogous functions of packages hosted through CRAN and GitHub)
- [x] for clarity, I'd suggest distinguishing between variables/arguments/classes and functions by adding parentheses, e.g., ppiBuildNetwork() and ppiPlotNetwork() in lines 118+; this is sometimes, but not always done; consistency here would be nice

## Code
- [x] avoid 1:... and use seq_len/along() instead (ppiExtractSubnetwork.R line 168)

**Comment by HelenaLC** [comment]
Thanks for addressing (many) earlier comments - here a revised review of what's been addressed so far (last one being more of a comment/thinking out loud than critique):

- [ ] in the DESCRIPTION, `BugReports: https://github.com/hancockinformatics/pathlinkR` should be `.../issues`, I think

- [ ] for the time being, Bioc installation instructions should be `BiocManager::install("pathlinkR", version="devel")`

- [ ] at the moment, the package help page is not found (what I'd call) intuitively, i.e., via `?pathlinkR` - I think it'd be worth adding `@aliases pathlinkR` to the roxygen header in *pathlinkR.R* to make this so

- [ ] the `data-raw` scripts should be placed under `extdata/inst/scripts` 

- looking at [this](https://contributions.bioconductor.org/data.html?q=raw#raw-data-and-the-instextdata-directory) information on example data, I am not entirely sure where the line is drawn between *raw* data, and data which has been loaded/parsed; but I guess the `data/` may well go into `inst/extdata` (i.e., you are pulling these from databases not, say, making them up/simulating).  
Not 100% familiar with the different data types involved here, but it looks to me like the workflow to generate some of these examples is quite complex... We *recommend* to find existing data provided in other packages or the hubs; would this be an option here? Perhaps something to consider.

**Comment by travis-m-blimkie** [comment]
Going back to your "major" comments r.e. input classes - I have tweaked the code so it can now accept "DESeqResults" (from `DESeq2`), or "TopTags" (from `edgeR`); in each case, column names for fold changes and p values are determined based on the class. Or, the input can be a simple "data.frame", with arguments to specify the requisite columns, allowing for greater flexibility of inputs.

I looked into the `SummarizedExperiment` class as you mentioned (primarily their [vignette](https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html)), but it seems that its intended for RNA-Seq count data, whereas the other classes ("DESeqResults" and "TopTags", which aren't derived from "SE") are tables of DE genes, which are "downstream" from said count data. From what I could find, the "SE" class is used only for earlier stages in the RNA-Seq analysis process than what we're targeting with `pathlinkR`. If I've missed something here please let me know, and if there are examples of DE gene tables stored as "SE" objects that'd be especially helpful.

Other minor points I've addressed:
- [x] in the DESCRIPTION, BugReports: https://github.com/hancockinformatics/pathlinkR should be .../issues, I think
- [x] for the time being, Bioc installation instructions should be BiocManager::install("pathlinkR", version="devel")
- [x] at the moment, the package help page is not found (what I'd call) intuitively, i.e., via ?pathlinkR - I think it'd be worth adding @aliases pathlinkR to the roxygen header in pathlinkR.R to make this so

**Comment by HelenaLC** [comment]
Agreed, if the whole package operates on downstream results only - supporting both `DESeq(2)` and `edgeR`, as well as arbitrary `data.frame`s with corresponding results (as specified by optional function arguments) - then all is well in terms of interoperability, I think. Perhaps I am missing something, but did you merge/push these changes? I still do not see the flexibility you mentioned implemented (e.g., `error: all(c("padj", "log2FoldChange") %in% colnames(deseqResult))`).

**Comment by travis-m-blimkie** [comment]
I just pushed those updates now (along with a some other changes), if you want to take a look.

Regarding your comments on the data:
- I don't mind moving the scripts into `inst/script` as suggested, but if possible I'd like to keep the data objects in `data`, if for no other reason than making them more readily available to the package, and also the end user.
- I can look more into finding existing data packages that may suit our needs. Though, in a few cases we are using existing packages as starting points (e.g. `reactome.db` and `msigdbr`), but with some changes or additions being made. So I'm not sure about finding a drop-in replacement for these...

**Comment by travis-m-blimkie** [comment]
Following up on the previous comments:
- All the data generation scripts have been relocated to `inst/script` as requested
- I tried searching for data packages or other resources that may be of use, but I couldn't seem to find anything suitable.

All these changes have been pushed to the Github and Bioconductor repositories.

**Comment by HelenaLC** [comment]
Apologies for the delay, but I didn't get notified about a new build - so just to make sure, did you push with a version bump? Looking at your local branch, I don't see the DESCRIPTION changing versions, hence no build report/notification here on GH - but not sure if the recent release of Bioc 3.18 could have cause any issues (I don't think it should).

*Perhaps just to note that I do see the changes you made (appreciated!), and it's looking great. But at this point need a clean build and check before finalizing...

**Comment by travis-m-blimkie** [comment]
I hadn't pushed a version bump yet, figured I'd wait until most of the changes were settled first. But I will do that today and make sure everything is passing.

**Comment by HelenaLC** [comment]
Thank you for all your efforts so far in addressing review comments. I noticed a very last thing that needs fixing, and am happy to accept afterwards. 

While `DESeq2` returns a class of it's own, which to test for via `is(..., "DESeqResults")`, this is not the case for `edgeR` or in general. As a result, `is(..., "TopTags")` will always fail (e.g., *pathwayEnrichment.R*).

`topTags` returns a plain `data.frame`, and users could, in principle, get a suitable table (containing, p-values and FCs) from anywhere (say, a *.csv* file).

I think a more general approach would simply be to test that the specified columns exist (if it's not a `DESeqResults` object). Otherwise put, it doesn't matter what class the input is, as long as you can find what you need (p-values, FCs etc.).

**Comment by HelenaLC** [comment]
Thanks for all your efforts in addressing review comments! Appreciate especially the changes made towards more flexible handling of inputs towards interoperability!

**Comment by travis-m-blimkie** [comment]
Of course, thanks for all your help and patience :) If there's anything else just let me know.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/travis-m-blimkie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pathlinkR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pathlinkR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
