### ISSUE TITLE
TumourMethData

### ISSUE THREAD

**Issue by richardheery** [Bioconductor/Contributions#3189]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/richardheery/TumourMethData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
I haven't figured out why yet but something changed and is preventing the build report from posting.  It is limited to this package.

**Comment by richardheery** [comment]
Should I try bump the package to initiate another build?

**Comment by lshep** [comment]
If you have updates to the package yes.  If there aren't any updates no; I already tried to manually set off a build this morning and it also failed.

**Comment by lshep** [comment]
In the meantime, here are my review comments: 

**man**

- [ ] Please have the default download directory use a `tempdir()` instead of
  the users working directory for `download_dataset`


**R code**

- [ ] Instead of moving files after they are downloaded with the Hubs is it
  possible instead to create links with the desired names?  Moving the files out
  of the cache after download will break the caching mechanism. And might be 
  related to the failure occurring. 

**vignette**

- [ ] Could you please provide an abstract/intro section in your vignette that
  provides motivation for inclusion in Bioconductor and when appropriate a
  review and comparison to existing Bioconductor packages with similar
  functionality or scope.

- [ ] It might be useful in the vignette to describe and demonstate the call to
  download the data. Perhaps there is smaller one that won't take quite as long?
  Or perhaps this chunk could be in an `eval=FALSE`

**Comment by lshep** [comment]
@richardheery were you able to work on the above points at all and push these changes to git.bioconductor.org?

**Comment by richardheery** [comment]
I've updated the download function to keep the files in the cache and use symbolic links to them and also to use tempdir() as the default location to locate these links.

I've also added an example of downloading data in the vignette and expanded the introduction/abstract. 

I added a function to download RNA-seq count datasets corresponding to the methylation datasets in the package. Since this data isn't in ExperimentHub yet, I can't add an example for downloading it so now I'm getting an error from BiocCheck saying that less than 80% of functions have examples. Is it okay to leave this as it is for now?

**Comment by lshep** [comment]
Yes okay to leave for now.  When do you expect to have the data uploaded to ExperimentHub? I will review the rest of the changes later today and provide any additional feedback

**Comment by richardheery** [comment]
I will try to get the final datasets uploaded today or else tomorrow. I have some of the RNA-seq data already on Zenodo, but I guess it's easier to let you know once I've everything finalized so you can add all the remaining data at once?

**Comment by lshep** [comment]
Yes once would be easier.

**Comment by lshep** [comment]
If a user calls a call again, wouldn't you want to skip the download and load instead of failing?  
```
_wgbs_hg38_chr11")
snapshotDate(): 2023-10-13
see ?TumourMethData and browseVignettes('TumourMethData') for documentation
downloading 2 resources
retrieving 2 resources
  |======================================================================| 100%
  |======================================================================| 100%

  |======================================================================| 100%
  |======================================================================| 100%

loading from cache
require("rhdf5")
> mcrpc_wgbs_hg38_chr11 = TumourMethData::download_meth_dataset(dataset = "mcrpc_wgbs_hg38_chr11")
Error in TumourMethData::download_meth_dataset(dataset = "mcrpc_wgbs_hg38_chr11") : 
  /tmp/RtmpMO0qa0/mcrpc_wgbs_hg38_chr11 already exists

```

**Comment by richardheery** [comment]
I just changed the download function to load the dataset if it was already downloaded instead of giving an error

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/richardheery.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TumourMethData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TumourMethData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
