### ISSUE TITLE
MGnifyR

### ISSUE THREAD

**Issue by TuomasBorman** [Bioconductor/Contributions#3191]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EBI-Metagenomics/MGnifyR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment]
# `code/`

- [ ] `BiocCheck()` NOTEs
  - avoid `T`/`F` variables and use `TRUE`/`FALSE` instead
  - avoid `sapply()` and use `vapply()` instead
  - avoid using `=` for assignment and use `<-` instead
  - avoid `1:...` and use `seq_len()` or `seq_along()` instead
  - avoid the use of `paste(0)()` in condition signals such as `message()`;  
  e.g., `stop(paste("ban", "ana"))` should be `stop("ban", "ana")`

- [ ] commented out code chunks that are not utilized
should be removed (e.g., *doQuery.R* lines 221+)

- [ ] in order to be OS-agnostic, use `file.path()` as opposed to
`paste0(..., "/", ..., ".x")` to construct paths (e.g., *utils.R* line 176)

- [ ] for clarity, we recommend S4 class and generic definitions to be placed in a single file: `AllClasses.R` and `AllGenerics.R`, respectively (see [here](https://contributions.bioconductor.org/r-code.html?q=allcla#rcode-file-names))

- [ ] `@` for slot accession should never be used; please define accessors
for the `MgnifyClient` S4 class and, throughout the package's code base, 
access data elements via, e.g., `cacheDir(object)`

- [ ] while we don't enforce a specific code-style, we appreciate consistency;
the style is currently rather inconsistent, e.g., there's a mix of 4-space tab
indentation and vertical alignment, sometimes with/without spaces around `=`,
sometimes missing space after `,`, `if ( condition )` or `if(condition)` etc.
please consider consulting the recommended [code-style guidelines](https://contributions.bioconductor.org/r-code.html?q=style#coding-style) or,
at the very least, implementing a consistent style

# documentation

- [ ] `BiocCheck()` NOTE: `Description:` field in the DESCRIPTION is too brief

- [ ] in the README, please add installation instruction using `BiocManager::install()`

- [ ] I see that there's a package help page, but it is not accessible via `?MGnifyR`;
I think this should be fixed by adding `@aliases MGnifyR` in the *MGnifyR.R* documentation

# `vignettes/`

- [ ] the `eval=FALSE` flag, or equivalent tricks in markdown,
undermine the benefit of vignettes and are generally *not allowed*

- [ ] `devtools::install_github("EBI-Metagenomics/MGnifyR")`
should become `BiocManager::install(MGnifyR)`

- [ ] please include a section with the `SessionInfo()` at the end

- [ ] it recommend *not* using code-style for TreeSE (as this is an acronym), 
and (for clarity) using `xxx()` instead of `xxx` when referring to functions
rather than, say, arguments, variables, classes etc.

- [ ] considering using `BiocStyle::Biocpkg()` to directly link to external 
packages (e.g., `(Tree)SummarizedExperiment`); there are analogous functions
available for CRAN, GitHub packages etc.

- [ ] we encourage the use of `r BiocStyle::Biocpkg("BiocStyle")`
for formatting with `html_document` as rendering target, e.g.:

```
output:
  BiocStyle::html_document:
    toc: true
    toc_depth: 2
```

# other

- [ ] `man/figures/` should go in `inst/extdata/`

- [ ] consider adding a NEWS file to track of changes, in non-technical language,  
in the code from one release version to the next (it's there, I guess, but empty)

**Comment by HelenaLC** [comment]
Any update on this? Note that you need to push to the upsteam Bioc remote *with* a version bump in the DESCRIPTION in order to trigger a build'n'check run in the system.

**Comment by TuomasBorman** [comment]
Hello!

Now I have taken into account comments. There are some chances that improved the quality. I pushed to upstream.

**Comment by lshep** [comment]
Did you push with a valid version bump?  You need to push to git.bioconductor.org  devel branch with a version bump to trigger a new build report

**Comment by TuomasBorman** [comment]
Hello! I am wondering if everything is now good and clear?

To note: I disabled the other longer vignette. There is good information but fetching the data from the database makes the build run too long

**Comment by HelenaLC** [comment]
The build resulted in ERRORs; please address these! We typically wait for a clean build before proceeding and eventually finalizing reviews- thanks 🙏

**Comment by TuomasBorman** [comment]
Sorry to ask probably stupid questions, but the build report above from last week is for version 0.99.2. I made a push couple days ago for version 0.99.3, but there is no build report available?

**Comment by HelenaLC** [comment]
Did you push to bioc? See the instructions by the chat bot further above - if done right, it would pop up here shortly that a new build has been triggered

**Comment by TuomasBorman** [comment]
> Received a valid push on git.bioconductor.org; starting a build for commit id: 73c9128b6a8b0c8f929f637d10eab3c5192714d1

I have to check once more, but based on this it was correctly done

**Comment by lshep** [comment]
We aren't seeing this with other packages but there is something causing the check to fail and crash the reporting process so a check is not returned.

**Comment by TuomasBorman** [comment]
OK, hmmm. The problem is probably related to vignette. I will check.

**Comment by TuomasBorman** [comment]
Hello,

now the error label is gone

**Comment by HelenaLC** [comment]
Could you please respond to the reviews dated Oct 9th, and comment on any other changes (if any)? Thanks! 🙏

**Comment by TuomasBorman** [comment]
> # `code/`
> 
>     * [ ]  `BiocCheck()` NOTEs
>       
>       * avoid `T`/`F` variables and use `TRUE`/`FALSE` instead
>       * avoid `sapply()` and use `vapply()` instead
>       * avoid using `=` for assignment and use `<-` instead
>       * avoid `1:...` and use `seq_len()` or `seq_along()` instead
>       * avoid the use of `paste(0)()` in condition signals such as `message()`;
>         e.g., `stop(paste("ban", "ana"))` should be `stop("ban", "ana")`

--> Code is improved so that it follows these listed recommendations.

>     * [ ]  commented out code chunks that are not utilized
>       should be removed (e.g., _doQuery.R_ lines 221+)

--> These commented lines are removed.

>     * [ ]  in order to be OS-agnostic, use `file.path()` as opposed to
>       `paste0(..., "/", ..., ".x")` to construct paths (e.g., _utils.R_ line 176)

--> Paths are constructed with `file.path()`.

>     * [ ]  for clarity, we recommend S4 class and generic definitions to be placed in a single file: `AllClasses.R` and `AllGenerics.R`, respectively (see [here](https://contributions.bioconductor.org/r-code.html?q=allcla#rcode-file-names))

--> Added files `AllClasses.R` and `AllGenerics.R`.
 
>     * [ ]  `@` for slot accession should never be used; please define accessors
>       for the `MgnifyClient` S4 class and, throughout the package's code base,
>       access data elements via, e.g., `cacheDir(object)`

--> Created accessors and mutators for `MgnifyClient` object's slots.
 
>     * [ ]  while we don't enforce a specific code-style, we appreciate consistency;
>       the style is currently rather inconsistent, e.g., there's a mix of 4-space tab
>       indentation and vertical alignment, sometimes with/without spaces around `=`,
>       sometimes missing space after `,`, `if ( condition )` or `if(condition)` etc.
>       please consider consulting the recommended [code-style guidelines](https://contributions.bioconductor.org/r-code.html?q=style#coding-style) or,
>       at the very least, implementing a consistent style

--> Consistency is taken into account. I tried to fix coding style to follow `BioCheck(), e.g., code follows now 4-space indentation. However, function length is something that I did not fix. I also tried to fix inconsistent coding style as best I could. 

> # documentation
> 
>     * [ ]  `BiocCheck()` NOTE: `Description:` field in the DESCRIPTION is too brief

--> Fixed.

>     * [ ]  in the README, please add installation instruction using `BiocManager::install()`

--> Fixed.
 
>     * [ ]  I see that there's a package help page, but it is not accessible via `?MGnifyR`;
>       I think this should be fixed by adding `@aliases MGnifyR` in the _MGnifyR.R_ documentation

--> Now help page can be accecced with `?MgnifyR`
> 
> # `vignettes/`
> 
>     * [ ]  the `eval=FALSE` flag, or equivalent tricks in markdown,
>       undermine the benefit of vignettes and are generally _not allowed_

--> There is currently two vignettes. The shorter vignette is now evaluated, however, the longer one has still `eval=FALSE`. The longer has important information but as the data is fetched from database, the build would take too long if the longer was also evaluated. 

>     * [ ]  `devtools::install_github("EBI-Metagenomics/MGnifyR")`
>       should become `BiocManager::install(MGnifyR)`

--> Fixed.

>     * [ ]  please include a section with the `SessionInfo()` at the end

--> Added.

>     * [ ]  it recommend _not_ using code-style for TreeSE (as this is an acronym),
>       and (for clarity) using `xxx()` instead of `xxx` when referring to functions
>       rather than, say, arguments, variables, classes etc.

--> I added explanation for these acronyms. Functions are now referred like `function()`.

>     * [ ]  considering using `BiocStyle::Biocpkg()` to directly link to external
>       packages (e.g., `(Tree)SummarizedExperiment`); there are analogous functions
>       available for CRAN, GitHub packages etc.

--> Added

>     * [ ]  we encourage the use of `r BiocStyle::Biocpkg("BiocStyle")`
>       for formatting with `html_document` as rendering target, e.g.:
> 
> 
> ```
> output:
>   BiocStyle::html_document:
>     toc: true
>     toc_depth: 2
> ```

--> Using BiocStyle::html_document

> # other
> 
>     * [ ]  `man/figures/` should go in `inst/extdata/`

--> Fixed.

>     * [ ]  consider adding a NEWS file to track of changes, in non-technical language,
>       in the code from one release version to the next (it's there, I guess, but empty)

--> NEWS file is updated.

Additional change:
	- There was no timeout when data was fetched. Now there is, and it can be controlled with `timeout` parameter.

**Comment by HelenaLC** [comment]
Thanks for all this; couple small things to iron out in the (hopefully final) round:

- [ ] In the DESCRIPTION, please update R version dependency from 4.3 to 4.4.0.

- [ ] `tests-MgnifyClient.R` still uses `@` for accession; please replace this by the corresponding accessors.

- [ ] `test-utils.R` is currently empty and should be removed or have tests added.

- [ ] Super minor and just to explain "why"? - `allX.R` scripts should be called `AllX.R`; the motivation here is that scripts are usually ordered alphabetically (e.g., within RStudio and GitHub) > capitals are preferred > `A...` scripts will remain at the top, independent of other scripts being added that begin with `a`. Again, this is largely to be transparent about what classes and generics are being "declared" by a package.

- [ ] Class validity checks should use `is()` rather than `class(.) == TRUE`; in general, but also while unit testing (e.g., `test-getResults.R` line 49+ should use `expect_is(object, class)`).

- [ ] The "small" vignette is still not being evaluated due to line 23, which globally sets `eval=FALSE`.

- [ ] I'd generally appreciate a little more details in the vignette. Specifically, each section currently states (in a sentence) what is being done/returned. Could you perhaps expand a little on what the outputs are and their components? This can be heavily "inspired" by what's already in the docs.

- [ ] In the package help page (`?MGnifyR`), links aren't showing correctly because the syntax `[text](link)` is markdown and doesn't work with roxygen; you should use `\url{link}` or `\href{link}{text}` instead (see (here)[https://stuff.mit.edu/afs/athena/software/r/current/RStudio/resources/roxygen_help.html]).

- [ ] Please remember to *update* the NEWS file to track changes, in non-technical language, in the code from one release version to the next; it is still at v0.99.0 while the package is at v0.99.11 (see (here)[https://contributions.bioconductor.org/news.html?q=news#news] for details).

**Comment by TuomasBorman** [comment]
1. In the DESCRIPTION, please update R version dependency from 4.3 to 4.4.0. --> OK

2. tests-MgnifyClient.R still uses @ for accession; please replace this by the corresponding accessors. --> OK

3. test-utils.R is currently empty and should be removed or have tests added. --> OK

4. Super minor and just to explain "why"? - allX.R scripts should be called AllX.R; the motivation here is that scripts are usually ordered alphabetically (e.g., within RStudio and GitHub) > capitals are preferred > A... scripts will remain at the top, independent of other scripts being added that begin with a. Again, this is largely to be transparent about what classes and generics are being "declared" by a package. --> OK

5. Class validity checks should use is() rather than class(.) == TRUE; in general, but also while unit testing (e.g., test-getResults.R line 49+ should use expect_is(object, class)). --> OK

6. The "small" vignette is still not being evaluated due to line 23, which globally sets eval=FALSE. --> OK

7. I'd generally appreciate a little more details in the vignette. Specifically, each section currently states (in a sentence) what is being done/returned. Could you perhaps expand a little on what the outputs are and their components? This can be heavily "inspired" by what's already in the docs. --> OK

8. In the package help page (?MGnifyR), links aren't showing correctly because the syntax [text](link) is markdown and doesn't work with roxygen; you should use \url{link} or \href{link}{text} instead (see (here)[https://stuff.mit.edu/afs/athena/software/r/current/RStudio/resources/roxygen_help.html]). --> OK
	
9. Please remember to update the NEWS file to track changes, in non-technical language, in the code from one release version to the next; it is still at v0.99.0 while the package is at v0.99.11 (see (here)[https://contributions.bioconductor.org/news.html?q=news#news] for details). --> OK


ADDED: I noticed that there is a need for new function to flexibly retrieve all kinds of "raw" data from the database. `getData()` function added. 


Sorry that it took so long. Now I believe everything is taken into account and the package fulfills the Bioconductor standards.

-Tuomas

**Comment by HelenaLC** [comment]
Hm, apologies for the delay, but I realized pulling the package still gives me v0.99.11 (see also the build report above) and the changes you listed are not reflected in the code; I see that your GitHub branch is at v0.99.21 - could you please check you've pushed this to Bioc? There should be a new build triggered with the report stating the same version as your origin GitHub branch.

**Comment by TuomasBorman** [comment]
Sorry, I forgot to push to Bioc

**Comment by HelenaLC** [comment]
build report still states v0.99.11 and "update R version dependency from 4.3 to 4.4.0" - not sure what's happening since pushing without version bump shouldn't have triggered a new build, but something's off still.

**Comment by TuomasBorman** [comment]
Same thing... it should be 0.99.22. I try to figure out the problem

**Comment by TuomasBorman** [comment]
Hello @HelenaLC!

I have been trying to fix the issue, but I have no idea what is causing it, and the Bioc build report does not help. I tried to solve warnings that might have caused this problem (I found out that the size of pre-downloaded data used in longer vignette was too large. I though that it might cause Bioc build to fail silently), but none of them worked.

So:

1. It seems that push to upstream is correctly done, because it triggers the build.
2. Build is done successfully.
3. The version does not update even though I push new version successfully.

--> Has something changed in Bioc since I am doing everything similarly than before?

I am using master branch and pushing to upstream with command `git push upstream`. I have noticed that Bioc recommends to use devel branch and use of master is deprecated.

```
remote: Use of 'master' branch is deprecated on git.bioconductor.org;
remote:   Access to 'master' will eventually be revoked.
remote:   Please use 'devel' to update Bioconductor devel version.
```

Might this cause the issue?

-Tuomas

**Comment by HelenaLC** [comment]
If you have a look at the [Git version control](https://contributions.bioconductor.org/git-version-control.html#git-version-control) guidelines, you'll see that changes should be made to either the `devel` or `RELEASE_3_NN` branch (the later will only be applicable upon release); hence the message "'master' branch will be deprecated [...] please use 'devel'". That been said, you should create and merge into a new `devel` branch on your GH and link that to the upstream Bioc remote for maintenance; ideally, local developments should be made on some temporary branch (can arbitrarily named, e.g., "update_vignette" or "bug_fix_xyz"), merged into `devel` and pushed to Bioc, while only pressing changes should be made to the release version (see guidelines).

**Comment by TuomasBorman** [comment]
@HelenaLC Thank you, that solved the issue

**Comment by HelenaLC** [comment]
Glad the GH issue could be resolved and thanks for addressing previous comments. I'm hoping this'll be the last of it, though I'd appreciate if you could spend extra attention on 3. - thanks!

- in the vignette `BiocManager::install(MGnifyR)` should be `BiocManager::install("MGnifyR")`; it's not being evaluated, but the former wouldn't work

- previous comment "in the package help page (`?MGnifyR`), links aren't showing correctly [...]" hasn't been fixed

- I'd highly encourage you to give the vignette a second thought. The point of the vignette is not to print any output generated (users can do that on their own in the console if they wish), especially not when there is no compact show method (as for, e.g., some S4 classes). Rather, it serves to demonstrate and describe what the package does -- each function's purpose, important arguments, methodological details, output/result contents/structure/meaning etc. Displaying online, one has to (in theory) scroll through 10+ pages to read a 10+ sentences in total. E.g., I'd suggest showing `names(analyses_metadata)` (or perhaps a part of that table that is especially relevant, if applicable) and briefly summarizing key contents rather than printing the `head()`; similarly, for `head(samples)` and `head(publications)` - what are the rows/columns? what's perhaps most interesting to actually print (=show in the vignette)? etc.

**Comment by TuomasBorman** [comment]
Hello!

1. Fixed to `BiocManager::install("MGnifyR")`

2. Fixed links in `?MGnifyR`

3. Those are fair points about vignette. I tried to print only essential.

4.

As discussed in [HoloFoodR submission](https://github.com/Bioconductor/Contributions/issues/3353), I want that MGnifyR and HoloFoodR packages are in same place. That is why I modified BiocViews. Hopefully, it is ok still at this point.

**Comment by HelenaLC** [comment]
Thank you. The vignette looks at lot better and is more readable now (at least imo)! 
- rather confused by that error. I can't see `biomformat` being used anywhere in the package, though it still appears in the DESCRIPTION as a dependency.
- unrelated: the report states `stats` isn't being used, in which case it should be dropped from the DESCRIPTION.

**Comment by TuomasBorman** [comment]
1.

`biomformat` is used in function `mia::loadFromBIOM()`. In mia, the `biomformat` is not  package dependency; it is only dependency for single function and availability of it is checked in the beginning of function.

The choice in `mia` was made to lower the number of dependency packages (the function is used only if you have BIOM files). We have the option to either make `biomformat` a dependency of `mia` or retain it as a dependency for `MGnifyR` package.

2. I will remove `stats`

**Comment by HelenaLC** [comment]
- if `mia` is being used, I am not suggesting you remove it, but
- there's a difference in whether a package `Depends:` on, `Imports:` or `Suggests:` a dependency (see the resources I mentioned above)
- from what I understand from what you say, both `mia` and `biomformat` are not needed for `MGnifyR`s core functionality, and only used when BIOM files are presents; so, the most adequate solution would be to place both under `Suggests:` and check that they are available if that functionality is triggered

**Comment by TuomasBorman** [comment]
`mia::loadFromBiom()` is used in core functionality of `MGnifyR` because the fetched microbiota data is parsed with it.

What I meant was that:

- `MGnifyR::getResult()` uses `mia::loadFromBiom()`
- `loadFromBiom()` utilizes `biomformat` package
- `biomformat` is not imported with `mia` (It's in Suggests of `mia`).  `loadFromBiom()` checks that `biomformat` is available
- To ensure that `biomformat` is available for `MGnifyR`, we have to Import it in `MGnifyR`

**Comment by HelenaLC** [comment]
Alright, thanks for clarifying that - so why not place it under `Imports:` and add `@importFrom mia loadFromBiom` (if this is the only function being imported)? Having it dependent on seems rather overkills if its usage is not guaranteed.

**Comment by TuomasBorman** [comment]
1. I moved `mia` to Imports. 
2. I removed `stats`
3. I moved `biomformat` to Suggests so that tests will go through.

**Comment by HelenaLC** [comment]
Alriiight, that makes a lot more sense, I think; thanks! 

- The report should be free of WARNINGs for release. Could you please resolve the build report WARNING related to `biocView:`s? I have not seen this in previous versions.
- Related: there are 10 occurences of `.Deprecated(), however, these include functions included in the vignette. Showing package functionality that should not be used and will be removed in the future seems off; please clarify or resolve.
- Please add a check if `biomformat` is available; this won't be guaranteed now that it's under `Suggests:` (again, see [here]() for details) - something like the below, which should go 1. anywhere the package will be used and 2. as early as possible (i.e., once it's determined that it'll be used):

```
if (!requireNamespace('biomformat', quietly = TRUE))
    stop("Install 'biomformat' to use this function.")
... # code requiring 'biomformat'
```

**Comment by TuomasBorman** [comment]
1. BiocViews related WARNINGS are now resolved

2.
There is only one WARNING and it is related to deprecated functions.

This package has already been existing many years. The new version contains updated version of functions. That is why some of the functions are deprecated. However, I cannot see that any of these deprecated functions are used in vignette.

3. Added check for biomformat availability.

**Comment by HelenaLC** [comment]
1&2) Super! 3) Apologies, they aren't - I misread the R search I did; my mistake. Thanks for your prompt, clear responses and corresponding modifications.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/TuomasBorman.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MGnifyR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MGnifyR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
