### ISSUE TITLE
plyinteractions

### ISSUE THREAD

**Issue by js2264** [Bioconductor/Contributions#3194]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tidyomics/plyinteractions

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by js2264** [comment]
Hi @HelenaLC thanks for reviewing this package. 

Build on linux is all green, but it errors on MacOS when building the vignette, specifically the `process_pairs.Rmd` vignette, at the step where a pairs file is fetched from ExperimentHub (id `EH7707`) using the `HiContactsData` package. I suspect that there might be an issue with this recently updated file, but I cannot figure out what fails. When I try running bioconductor devel docker in the cloned repo on a local Mac, things work:

```r
BiocManager::install("tidyomics/plyinteractions", force = TRUE)
library(plyinteractions)
devtools::build_vignettes()
## This finishes ok
```

Any idea why it the vignette build would fail specifically on Mac, when trying to fetch a resources from `ExperimentHub`? 
Thanks, J

**Comment by HelenaLC** [comment]
Trying to build the package on my personal laptop ('23 arm64 MacBook) I am getting this...
```
processing file: process_pairs.Rmd                                                                                                         
Quitting from lines 47-58 [importPairs] (process_pairs.Rmd)
Error in `vroom_()`:
! bad value
Backtrace:
 1. rlang::set_names(...)
 2. vroom::vroom(pairs_file, delim = "\t", col_names = FALSE, comment = "#")
 3. vroom:::vroom_(...)
Execution halted
```
...google also found [this](https://support.bioconductor.org/p/9154550/) saying `"bad value"`, so (I think) it might be something `vroom`-related, and hopefully it will be fixed by 'them' eventually.

**Comment by js2264** [comment]
> Trying to build the package on my personal laptop ('23 arm64 MacBook) I am getting this...
> 
> ```
> processing file: process_pairs.Rmd                                                                                                         
> Quitting from lines 47-58 [importPairs] (process_pairs.Rmd)
> Error in `vroom_()`:
> ! bad value
> Backtrace:
>  1. rlang::set_names(...)
>  2. vroom::vroom(pairs_file, delim = "\t", col_names = FALSE, comment = "#")
>  3. vroom:::vroom_(...)
> Execution halted
> ```
> 
> ...google also found [this](https://support.bioconductor.org/p/9154550/) saying `"bad value"`, so (I think) it might be something `vroom`-related, and hopefully it will be fixed by 'them' eventually.

Thanks @HelenaLC for your input, I've dropped vroom in favor of read.delim, takes much longer but it works cross-platform. Let me know if you need anything else while reviewing the code!

**Comment by HelenaLC** [comment]
# code

- [ ] for clarity, we recommend S4 class and generic definitions to be placed in a single file: `AllClasses.R` and `AllGenerics.R`, respectively (see [here](https://contributions.bioconductor.org/r-code.html?q=allcla#rcode-file-names))

- [ ] avoid the use of `paste()` in condition signals (*internals.R* line 5); it's not necessary (e.g., `stop("hello", "world")` works)

- [ ] validity checks on the S4 classes defined in the package are currently missing; e.g., running (`ggi=GroupedGInteractions`) `ggi@group_keys <- DataFrame()` and break anything afterwards - not that anyone would ever do this, but S4 class definitions should generally come with a sensible validity method for long-term development/maintenance purposes and against undesirable user-behavior (see 1.3 [here](https://bioconductor.org/help/course-materials/2017/Zurich/S4-classes-and-methods.html) for a minimal example) - e.g., here, `n_groups()` should be length 1, `names(group_keys())` should occur in the data, `nrow(group_keys())` should match `n_groups()`, etc.

# documentation

- [ ] consider adding a package *.man* page (i.e., `?plyinteractions`), e.g., describing the package's generally functionality (see other packages for examples)

- [ ] the package currently `Depends: R (>= 2.10)`, however, it will not be installable under anything less than R v4.3 (Bioc v3.18); I'd suggest bumping R version requirements accordingly (note also that R's native pipe operator `|>` wasn't available until recently, so this won't work with R v2.1 in any case!)

- [ ] `LazyData:` should be set to `false` or removed (see [here](https://contributions.bioconductor.org/description.html?q=lazy#description-lazydata) for details)

- [ ] in the `BiocCheck()` report, there are NOTEs related to the number of characters in examples (> 100 characters make things hard to read when viewing *.man*. pages via `?...`); might be worth considering 1. inserting a few additional line breaks, and 2. not using spaces around `=`s to keep things more compact (this is also the recommended code style in general)

# vignette

- [ ] type line 184: dependant > dependent

- [ ] please add a brief `# Introduction` section (see [here](https://contributions.bioconductor.org/docs.html#vignette-introduction) for details)

- [ ] no 'issue' *per se*, but I find the `plyinteractions.Rmd` vignette very hard to digest, primarily because there is a lot of lengthy code output and comparability little text; while thorough documentation is highly appreciated, perhaps consider compacting this to something more readable (to give one example, many `tidy` verbs form groups with similar behavior, and it might be sufficient to list those and only demo/evaluate an example; e.g., the code chunk at line 444 executes 14 things - without any comment on what's happening in each - is this really necessary? wouldn't it be more informative to name (not execute) relevant functions and highlight selected examples instead?

# other

- [ ] I *strongly* urge you to consider implementing unit tests; these are indispensable for both package development and maintenance (`testthat` is currently listed in the DESCRIPTION, but I don't see any tests)

- [ ] consider adding a NEWS file to keep track of changes to the code from one version to the next

- [ ] the scripts at `data-raw/` should be placed under `inst/scripts/` (see [here](https://contributions.bioconductor.org/docs.html?q=inst/sc#doc-inst-script) for details)

**Comment by js2264** [comment]
Thanks @HelenaLC for the review! I'm now working on it. I'll ping you when I have answered all your comments. 

> # code
> * [x]  avoid the use of `paste()` in condition signals (_internals.R_ line 5); it's not necessary (e.g., `stop("hello", "world")` works)
> * [x]  for clarity, we recommend S4 class and generic definitions to be placed in a single file: `AllClasses.R` and `AllGenerics.R`, respectively (see [here](https://contributions.bioconductor.org/r-code.html?q=allcla#rcode-file-names))
> * [x]  validity checks on the S4 classes defined in the package are currently missing; e.g., running (`ggi=GroupedGInteractions`) `ggi@group_keys <- DataFrame()` and break anything afterwards - not that anyone would ever do this, but S4 class definitions should generally come with a sensible validity method for long-term development/maintenance purposes and against undesirable user-behavior (see 1.3 [here](https://bioconductor.org/help/course-materials/2017/Zurich/S4-classes-and-methods.html) for a minimal example) - e.g., here, `n_groups()` should be length 1, `names(group_keys())` should occur in the data, `nrow(group_keys())` should match `n_groups()`, etc.


> # documentation
> * [x]  the package currently `Depends: R (>= 2.10)`, however, it will not be installable under anything less than R v4.3 (Bioc v3.18); I'd suggest bumping R version requirements accordingly (note also that R's native pipe operator `|>` wasn't available until recently, so this won't work with R v2.1 in any case!)
> * [x]  `LazyData:` should be set to `false` or removed (see [here](https://contributions.bioconductor.org/description.html?q=lazy#description-lazydata) for details)
> * [x]  consider adding a package _.man_ page (i.e., `?plyinteractions`), e.g., describing the package's generally functionality (see other packages for examples)
> * [x]  in the `BiocCheck()` report, there are NOTEs related to the number of characters in examples (> 100 characters make things hard to read when viewing _.man_. pages via `?...`); might be worth considering 1. inserting a few additional line breaks, and 2. not using spaces around `=`s to keep things more compact (this is also the recommended code style in general)


> # vignette
> * [x]  type line 184: dependant > dependent
> * [x]  please add a brief `# Introduction` section (see [here](https://contributions.bioconductor.org/docs.html#vignette-introduction) for details)
> * [x]  no 'issue' _per se_, but I find the `plyinteractions.Rmd` vignette very hard to digest, primarily because there is a lot of lengthy code output and comparability little text; while thorough documentation is highly appreciated, perhaps consider compacting this to something more readable (to give one example, many `tidy` verbs form groups with similar behavior, and it might be sufficient to list those and only demo/evaluate an example; e.g., the code chunk at line 444 executes 14 things - without any comment on what's happening in each - is this really necessary? wouldn't it be more informative to name (not execute) relevant functions and highlight selected examples instead?

> # other
> * [x]  I _strongly_ urge you to consider implementing unit tests; these are indispensable for both package development and maintenance (`testthat` is currently listed in the DESCRIPTION, but I don't see any tests)
> * [x]  consider adding a NEWS file to keep track of changes to the code from one version to the next
> * [x]  the scripts at `data-raw/` should be placed under `inst/scripts/` (see [here](https://contributions.bioconductor.org/docs.html?q=inst/sc#doc-inst-script) for details)

**Comment by js2264** [comment]
Hi @HelenaLC, I've taken all your comments into account every time it was possible. Please let me know if there is anything I can change to improve the package, thanks! 

* https://github.com/tidyomics/plyinteractions/commit/8d2c0ef - doc: fix missing @return field 
* https://github.com/tidyomics/plyinteractions/commit/f81612b - test: add validity functions for new classes 
* https://github.com/tidyomics/plyinteractions/commit/9646e15 - test: add tests (~90%) 
* https://github.com/tidyomics/plyinteractions/commit/24c4ca2 - doc: fix lines > 80 characters 
* https://github.com/tidyomics/plyinteractions/commit/bf8b198 - doc: move generics and classes to separate R files
* https://github.com/tidyomics/plyinteractions/commit/ea61406 - fix: load data interactively 
* https://github.com/tidyomics/plyinteractions/commit/76bd692 - doc: add package-level doc 
* https://github.com/tidyomics/plyinteractions/commit/6d91765 - doc: improve vignettes 
* https://github.com/tidyomics/plyinteractions/commit/51e18f9 - fix: R version 4.3.0 required 
* https://github.com/tidyomics/plyinteractions/commit/c242681 - refactor: rm paste in stop call 
* https://github.com/tidyomics/plyinteractions/commit/a20420c - doc: add NEWS.md 
* https://github.com/tidyomics/plyinteractions/commit/06bf563 - doc: mv data scripts to inst/scripts

**Comment by HelenaLC** [comment]
Thanks for the prompt response & action - it's come along nicely! While none of these are a *necessity* for acceptance, I'd like to leave you with a couple more (minor) comments that might be worth addressing prior to release, or a bit of a learning opportunity perhaps. As indicated, happy to accept in any case (!), just that fixes won't immediately come through once the package enters the Bioc build system. There's still more than a week of time to realize (some of) these, so, it's you're call - just let me know!

- [ ] in the package help (*plyinteractions.man*) page, it would be nice to
hyperlink the functions you mention, i.e., using `\code{\link{<function>}}`

- [ ] in the vignettes, I'd suggest getting rid of the package pre-loading (lines 28-31)
because this code chunk is not being `echo`ed, as to avoid (accidental) confusion
should a library be added/removed at any point in the future

- [ ] in the vignettes, for clarity, I'd suggest using `xxx()` as opposed to
`xxx` (i.e., adding empty parentheses) when referring to functions rather than,
say, variables, arguments, classes etc. (of course, just my opinion, you're call!)

- [ ] throughout the vignettes, consider using `r BiocStyle::CRANpkg("dplyr")` when
mentioning `dplyr` package (and other CRAN packages), or `r BiocStyle::Githubpkg()`
(should there be any mention of a GH package that I missed); this is currently under
*Acknowledgments* at the very end, but easy to miss/seldomly reached in my opinion...

- [ ] appreciate some class validity checks, though these could be a little more
extensive/fail-save, ideally, *really* checking everything is *exactly* as it should...
(just a random example:) `@pin <- as.integer(c(1, 2))` on a `PinnedGInteractions`
breaks the `if`-statement in *AllClasses.R* line 51 since `@pin` should be scalar
(dumb example, but S4 class definitions should ideally be very, very robust...)

- [ ] while unit test coverage is not at 87%+ with a few hits per line, it's *very* minimalist -
e.g., many current tests check that a function basically works (e.g., an S4 object is returned) -
ideally, tests should cover relevant use- and edge-cases such as invalid input arguments,
more complex computations, the actual data in the output (not just its class) etc.
Testing that a function *just* works is no guarantee for correctness of outputs

**Comment by js2264** [comment]
Hi @HelenaLC, thanks for your fast reivew and great suggestions. I did learn a bit while trying to improve the package following your recommendations. 

Regarding validity checks, I have tried to make them robust enough. I have slightly improved and fixed some bugs in the validity checks, which limits misuse form the end user. Note that I specifically did not create dedicated constructors for the new classes `(AnchoredPinnedGInteractions` and `GroupedGInteractions`); instead, these classes are created when using `group_by()`, `pin_by()` and `anchor_*()`, and these methods should take care of use and edge cases (as much as I could think). Also, my understanding is that once a `S4` object is created, changing it directly with `@<-` does not trigger the validity check, is this incorrect? 

Regarding unit tests, I am currently improving them to control for expected output value rather than class. I also included some tests reflecting "real" tidy workflows. I still need to go over the `dplyr`-related and setters tests, this should be over by tomorrow. 

[x] in the package help (plyinteractions.man) page, it would be nice to hyperlink the functions you mention, i.e., using \code{\link{<function>}}
[x] in the vignettes, I'd suggest getting rid of the package pre-loading (lines 28-31) because this code chunk is not being echoed, as to avoid (accidental) confusion should a library be added/removed at any point in the future
[x] in the vignettes, for clarity, I'd suggest using xxx() as opposed to xxx (i.e., adding empty parentheses) when referring to functions rather than, say, variables, arguments, classes etc. (of course, just my opinion, you're call!)
[x] throughout the vignettes, consider using r BiocStyle::CRANpkg("dplyr") when mentioning dplyr package (and other CRAN packages), or r BiocStyle::Githubpkg() (should there be any mention of a GH package that I missed); this is currently under Acknowledgments at the very end, but easy to miss/seldomly reached in my opinion...
[x] appreciate some class validity checks, though these could be a little more extensive/fail-save, ideally, really checking everything is exactly as it should... (just a random example:) @pin <- as.integer(c(1, 2)) on a PinnedGInteractions breaks the if-statement in AllClasses.R line 51 since @pin should be scalar (dumb example, but S4 class definitions should ideally be very, very robust...)
[x] while unit test coverage is not at 87%+ with a few hits per line, it's very minimalist - e.g., many current tests check that a function basically works (e.g., an S4 object is returned) - ideally, tests should cover relevant use- and edge-cases such as invalid input arguments, more complex computations, the actual data in the output (not just its class) etc. Testing that a function just works is no guarantee for correctness of outputs

**Comment by HelenaLC** [comment]
Great efforts, thanks! Re tests, yeah, would be good to cover the basics here. I recall that for `tidySingleCellExperiment` I basically went to `dplyr/tidyr` and copied & modified some of their tests. But tests are definitely something that can and should grow over time, as issues arise etc.

You're correct in that `@<-` won't trigger validity checks, and I don't have a strong argument here other than: it's a principle of the matter to assure classes we define remain valid, also from a developer perspective (i.e., a good validity check should prevent any functions downstream from (by accident) creating something invalid).

Not familiar with all the details, but if the 'new' classes have a `dplyr` class underlying them, perhaps calling their validity checks in a some way might be the easier and most comprehensive solution? Else, I think it's pretty straightforward to implement yourself.

I'll hold out until the next update/for you're 'go' to accept!

**Comment by js2264** [comment]
Thanks @HelenaLC for all your inputs and comments. I've worked a bit further on the tests. I will also continue working on improving validity tests in the coming weeks, but I won't have time to do that in the coming days, so I think it's ok to give it a go and send it to `devel` as it is now, if this is ok for you. Thanks again for your review!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("plyinteractions")`. The package 'landing page' will be created at

https://bioconductor.org/packages/plyinteractions

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
