### ISSUE TITLE
AUCell

### ISSUE THREAD

**Issue by s-aibar** [Bioconductor/Contributions#320]
- Repository: https://github.com/aertslab/AUCell

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
# 19 March, 2017

DESCRIPTION

- Provide a more extensive Description:, analogous to a paper abstract where the method being implemented is described in sufficient detail to help the user decide whether the package is appropriate for them.

- LICENSE: The license appears to be non-standard, and 'academic use' only. Generally, such academic-only licenses are not appropriate for Bioconductor packages.

vignette

- good

R

- The use of '.' in function names is discouraged, use snake_case or camelCase instead.

- To facilitate interoperability with other Bioconductor packages and work flows, use the [GSEABase][] package to input, output, and represent gene sets.

- Vectorize where appropriate, e.g.,

        tmp <- unname(sapply(readLines(fileName), function(x) strsplit(as.character(x),"\t"))) 
        
  is `tmp <- strsplit(readLines(fileName), "\t"))`

- E.g., 01_buildRankings.R:35 `paste()` is not usually required inside `warning()` and friends.

- Consider using [BiocParallel][] for parallel evaluation, so that Bioconductor users experience a more consistent interface.

- avoid `1:length(x)` in favor of `seq_along(x)` (more robust when length(x) == 0) or `seq_len()`

- Consider wrapping code and documentation lines to 80 character width, to increase readability. Indent consistently, e.g., in `priv_auc.assignmnetThreshold_v5.R:25` Also, format `if()` statements so that clauses are on distnict lines, e.g., write (03_AUCell.exploreThresholds.R:81

        if(verbose) message(paste("Using", getDoParWorkers(), "cores."))
  as
  
        if (verbose)
            message("Using ", getDoParWorkers(), " cores.")

  for `tryCatch()` e.g., `priv_auc.assignmnetThreshold_v5.R:56`, avoid
  excessive indentation by using a form like
  
        result <- tryCatch({
            ....
        }, error = function(e) {
            ...
        })

- Do NOT manipulate the random number generator `set.seed()` inside function.

- Use the [SummarizedExperiment][] class instead of `matrixWrapper` so that Bioconductor users do not need to learn how to use yet another class. E.g., `SummarizedExperiment(list(AUC=..., ranking=...)`

[GSEABase]: https://bioconductor.org/packages/GSEABase
[BiocParallel]: https://bioconductor.org/packages/BiocParallel
[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by mtmorgan** [comment]
The deadline for addition of packages to the next Bioconductor release is this Friday. If you'd like your package to be considered, please update your package and provide a written response to the review comments above.

**Comment by s-aibar** [comment]
Hello,

Thank you for reviewing the package and the heads-up about the deadline. We are working on the points mentioned on the review, but we are not expecting to be included in the next release of Bioc. We will push the new version to Github when it is ready -probably within a few weeks-.
 
Thank you,
Sara Aibar

**Comment by mtmorgan** [comment]
It looks like development on this package has stalled. I will close the issue. Feel free to re-open it when you are ready to continue.

**Comment by s-aibar** [comment]
Dear @mtmorgan ,

I have submitted a new version which addresses your [comments](https://github.com/Bioconductor/Contributions/issues/320#issuecomment-287621677). (Thank you for the suggestions, some of them were very useful!)

R CMD check and BiocCheck also run without error or warnings, except this one (which I'm not sure how to address):

> Warning: replacing previous import SummarizedExperiment::shift by data.table::shift when loading AUCell

Thank you,
Sara Aibar

PS: I think I cannot [re-open](https://github.com/Bioconductor/Contributions/issues/320#issuecomment-301246442) the issue...

**Comment by mtmorgan** [comment]
In the NAMESPACE, instead of importing the entire package `import(data.table)` import only the things that you want `importFrom(data.table, foo, bar)` or `import(data.table, except=shift)`.

**Comment by mtmorgan** [comment]
Thanks very much for your revisions, which are mostly in line with the original comments. Unfortunately...

DESCRIPTION

- LICENSE is academic use only, and this is not acceptable for new Bioconductor submissions. Can this be changed?

**Comment by s-aibar** [comment]
Hello,

We have changed the License to GPL-3 (plus a couple minor improvements). 
Please, let me know if everything is in order now.

Regards,
Sara Aibar

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/s-aibar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"AUCell\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AUCell

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
