### ISSUE TITLE
spillR

### ISSUE THREAD

**Issue by ChristofSeiler** [Bioconductor/Contributions#3214]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/marcoguazzini/spillR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'spillR' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. 
Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The DESCRIPTION file
- [ ] Important: `Depends` field is not found in DESCRIPTION.`Depends` field is suggested in DESCRIPTION.
- [ ] Important: R version is not clear in DESCRIPTION. Must be no less than 4.3.1.
## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 7 import(CATALYST)
	* in line 8 import(dplyr)
	* in line 9 import(ggplot2)
	* in line 10 import(tibble)
## General package development
- [ ] Important: Consider adding unit tests. We strongly
      encourage them. See
      https://contributions.bioconductor.org/tests.html

## R code
- [ ] Important: `vapply` instead of `sapply`.
	* In file R/compCytof.R:
		+ at line 124 found '        channels_null <- names(which(sapply(fit_list, is.null)))'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
- [ ] Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
	* In file R/plotDiagnostics.R:
		+ at line 53 found '        cell = 1:nrow(exprs),'
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/compCytof.R:
		+ at line 101 found '                               for (i in seq(length(spillover_barcodes))) {'
		+ at line 138 found '        for (i in seq_len(length(channel_names))) {'
	* In file R/compensate.R:
		+ at line 66 found '        for (marker in spillover_markers) {'
		+ at line 115 found '        for (i in seq(2, n_iter)) {'
- [ ] NOTE: Avoid using '=' for assignment and use '<-' instead. Please user `styler` package to reformat your package.
	* In file R/compensate.R:
		+ at line 184 found '            names(tb_compensate)[1] = "uncorrected"'
## Documentation
- [ ] Important: Vignette should have an *Installation* section.
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
- [ ] Note: the plot in section 'Compensation Workflow' is blank.

**Comment by ChristofSeiler** [comment]
Many thanks for the thorough review! Here are our line by line replies:

> # Package 'spillR' Review
> Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. Please try to answer the comments line by line when you are ready for a second review. Code: Note: please consider; Important: must be addressed.
> 
> ## The DESCRIPTION file
> * [x]  Important: `Depends` field is not found in DESCRIPTION.`Depends` field is suggested in DESCRIPTION.

We moved the essential packages to the `Depends` field.

> * [x]  Important: R version is not clear in DESCRIPTION. Must be no less than 4.3.1.

We added the version to the `Depends` field.

> 
> ## The NAMESPACE file
> * [x]  Selective imports using `importFrom` instead of _import all_ with `import`.
>   
>   * in line 7 import(CATALYST)
>   * in line 8 import(dplyr)
>   * in line 9 import(ggplot2)
>   * in line 10 import(tibble)

We changed to selective imports everywhere.

> 
> ## General package development
> * [x]  Important: Consider adding unit tests. We strongly
>   encourage them. See
>   https://contributions.bioconductor.org/tests.html

We added unit tests using `testthat`.

> 
> ## R code
> * [x]  Important: `vapply` instead of `sapply`.
>   
>   * In file R/compCytof.R:
>     
>     * at line 124 found '        channels_null <- names(which(sapply(fit_list, is.null)))'

We replaced `sapply` with `vapply`.

> * [x]  NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.

We removed all `::` except in the doc examples.

> * [x]  Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
>   
>   * In file R/plotDiagnostics.R:
>     
>     * at line 53 found '        cell = 1:nrow(exprs),'

We replaced `1:n` with `seq_along(n)`.

> * [x]  NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
>   
>   * In file R/compCytof.R:
>     
>     * at line 101 found '                               for (i in seq(length(spillover_barcodes))) {'

Replaced the `for` loop by `vapply`.

>     * at line 138 found '        for (i in seq_len(length(channel_names))) {'

Replaced the `for` loop with `lapply`.

>   * In file R/compensate.R:
>     
>     * at line 66 found '        for (marker in spillover_markers) {'

Replaced the `for` loop with `lapply`.

>     * at line 115 found '        for (i in seq(2, n_iter)) {'

Replaced the `for` loop with a `while` loop.

> * [x]  NOTE: Avoid using '=' for assignment and use '<-' instead. Please user `styler` package to reformat your package.
>   
>   * In file R/compensate.R:
>     
>     * at line 184 found '            names(tb_compensate)[1] = "uncorrected"'
> 

We reformatted our code using `styler`.

> ## Documentation
> * [x]  Important: Vignette should have an _Installation_ section.
> * [x]  Important: Please include Bioconductor installation instructions using BiocManager.

We added _Installation_ using `BiocManager` section.

> * [x]  Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.

We added a motivation at the end of our _Introduction_ section.

> * [x]  Note: the plot in section 'Compensation Workflow' is blank.

We fixed this issue by loading the necessary packages.

**Comment by ChristofSeiler** [comment]
Hi @jianhong,

Thanks again for your feedback. We fixed all your comments. We set `R (>= 4.3.0)`. The builder uses 4.4 and only builds on linux. The builder also reports warnings now. But I don't see any warning in the build report. Thanks for your help!

Best,
Christof

**Comment by jianhong** [comment]
Congrats and thank you for contribution in Bioconductor.
Interesting, it marked as `Warning` but I did not see it. If the warning appear again please fix it.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ChristofSeiler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spillR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spillR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
