### ISSUE TITLE
coexnet: An R package to build CO-EXpression NETworks from Microarray Data

### ISSUE THREAD

**Issue by juancholkovich** [Bioconductor/Contributions#322]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gibbslab/coexnet

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Before I start the review process, please set the package version to 0.99.0. Since this step is part of the [package submission checklist](http://bioconductor.org/developers/package-submission/#checklist), please also review other parts of the package guidelines and package submission page, and the the items that you have checked

**Comment by juancholkovich** [comment]
@mtmorgan new version bump

**Comment by juancholkovich** [comment]
@mtmorgan 

Dear Dr. Morgan

I writing to you to ask about a problem related to the package "Biobase" as a dependency of my package "coexnet". When it is checked to Windows os, the result is the next ERROR:

ERROR: dependency 'Biobase' is not available for package 'coexnet'

What is the solution of this ERROR?
I passed this prove several days ago and I edited the name of an author in the DESCRIPTION file and now I have this problem.

Best regards.

**Comment by mtmorgan** [comment]
Please ignore this; it is a problem on our end. I'll review your package shortly.

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 

I will be reviewing your package. One of the first things that I noticed was that your git repository was a really big download (~`96 Mb`). Please consider reducing the size of your git repository by using a tool such as BFG Repo Cleaner https://rtyley.github.io/bfg-repo-cleaner/. 

Regards, 
Marcel

**Comment by juancholkovich** [comment]
Hi Marcel, @LiNk-NY 

I have already followed your suggestion and I reduced the git repository size from ~95M to ~ 35M.

Regards,

Juan.

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 
The repository is still pretty big. I don't think it should be that big. 
Your `./.git/objects/pack` folder has about `38 Mb`.

I took a quick look at your package and I noticed that you could be using a `SummarizedExperiment` as the argument for many of your functions. Interoperability is an important part of the review process. Please make sure that you are reusing existing Bioconductor data structures for your functions. 

A couple of additional points: 

* Avoid the use of periods `.` in function names. Please use `camelCase` naming conventions.
* Keep the `@author` and `@export` tags inside the roxygen blocks. 

Regards,
Marcel

**Comment by juancholkovich** [comment]
Hi Marcel @LiNk-NY 

I have already made the suggested actions. The repository size is ~5M.

Regards.

Juan.

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 
Thank you for making those changes. The repository size is looking much better. This size is more convenient for those who want to contribute to the package. 

Please keep in mind that new package submissions should strive to increase interoperability between packages already in Bioconductor. Your package can use the `SummarizedExperiment` class to represent expression data. Making it easy for other packages to work with yours is one of the major aims of the project. 

Best regards,
Marcel

**Comment by juancholkovich** [comment]
Hi Marcel @LiNk-NY 

Is mandatory the use of SummarizedExperiment object? I use Affybatch object to store the raw expression data and ExpressionSet as an intermediate object in the normalization whose result is a numerical matrix.

Regards,

Juan.

**Comment by llrs** [comment]
Hi Juan,

I was looking how you combine different sources of data, and I noticed the following: [`return(cat("..."))`](https://github.com/gibbslab/coexnet/blob/dad12882f73f66ef4ad831160d44e2390a015160/R/CCP.R#L35). If it is an error you should use stop, if it is a message to the user use message. But returning a string it might be unexpected to the user.
Also, why the user can't select any other way to combine the graphs? Say, limit to genes with degree above a certain threshold in both graphs or something similar.

**Comment by juancholkovich** [comment]
Hi Lluis   @llrs 

I will change the return of these functions by the stop, but in the second suggestion, we consider the global alignment of the networks to obtain the common patterns of connectivity as a new proposed method by us.

Regards,

Juan.

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 
We want to keep any new submissions interoperable with the existing Bioconductor software. The use of `ExpressionSet` has been superseded by that of `SummarizedExperiment`. We recommend that you make your software compatible with Bioconductor by allowing the input as a `SummarizedExperiment` class object. 

Regards,
Marcel

**Comment by juancholkovich** [comment]
Hi Marce @LiNk-NY 

I already created the option to use the SummarizedExperiment as input in my functions and I made other changes following other suggestions.

Regards.

Juan.

**Comment by llrs** [comment]
Hi Juan,

Sorry to bother you again, but you don't need to `return(stop(`. Stop will already abort the function with an error. See the help page of `stop`.

> we consider the global alignment of the networks to obtain the common patterns of connectivity as a new proposed method by us.

Totally true (AFAIK), but it can be more helpful if you let the users define those common patterns of connectivity. Of course, it is your choice what do you want to allow users to do. 
PS: In the Details of CCP you have a sentence duplicated.

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 
Thanks for making those changes. I will have a look at them soon. 
Regards,
Marcel

**Comment by juancholkovich** [comment]
Hi Luis @llrs 

I have already changed the stop statement according to the suggestions. On the other hand, I modified the CCP function to obtain results through a range of degree values or above a specific degree in the networks.

Regards.

Juan

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 
It seems like the size of your repository grew again. It is currently at `~40Mb`. 
I will have another quick look at your package and post some comments and suggestions.

Regards,
Marcel

**Comment by juancholkovich** [comment]
Hi Marcel @LiNk-NY 

I already processed the repository and now have a size of ~5M.

Regards,
Juan

**Comment by LiNk-NY** [comment]
Hi Juan, @juancholkovich 

Thank you for reducing the repository size. It is down to `~5Mb` again. 
Please see the review below. 
If you have any questions, feel free to contact me.

Regards,
Marcel 

----
# coexnet #322

## Overall
I am glad that you were able to integrate your package with existing Bioconductor classes (namely `SummarizedExperiment`). 

### Package
The organization of the package looks good. I see that you included unit tests. 
* Imports: You should be more specific with functions that you would like to import. Use the `@importFrom` roxygen tag to specify particular functions that you want to import from a package (e.g., `igraph::as_data_frame`).

### Grammar
A few items that you can address here are: 
* Use `is(obj, "SummarizedExperiment")` to test the class of the object rather than checking to see if it is not a `matrix` or `data.frame`
* Some examples you include have `t` object assignment. Please avoid using function names for object assignment as this may give you trouble when `t` is not defined.
* Argument names should reflect the class that is accepted (i.e., avoid using an `eset` argument for a `SummarizedExperiment` input). This can confuse your user. 
* Plotting should be an option and not a side effect. Any calls to graphic devices should be explicit and should not a side effect of a function. I would suggest either adding an argument for optional plotting or creating a separate function for plotting. 
* Avoid the use of `1:length(n)` sequence styles. You should use the more robust `seq_len` or `seq_along`. 
* Avoid changing the working directory within the function. Use the `dir` argument to code for the path using `file.path`. Also, avoid using a defined function name as an argument (in this case `dir`). Try `directory`.  
* Your input arguments should only specify one type of input. You should not have one argument for 2 different types of inputs (e.g., `ppiNet(input = "")`). Create two different arguments such as `molecularIDs` and `file`). 
* Please avoid the copying of a vector. Use the pre-allocate and fill approach. This also applies to matrices. See instances where `<- vector()` and `<- matrix()` are present. 
Please read the package guidelines for more details. 
http://www.bioconductor.org/developers/how-to/efficient-code/

---

**Comment by juancholkovich** [comment]
Hi Marcel @LiNk-NY 

I already made the suggested changes.
Also, I tried to be as specific as possible in the dependencies imports in the internalFunction.R file

I will be attentive to any other suggestion.

Regards,

Juan.

**Comment by juancholkovich** [comment]
Hi Marcel @LiNk-NY 

I already made the suggested changes.
Also, I tried to be as specific as possible in the dependencies imports in the internalFunction.R file

I will be attentive to any other suggestion.

Regards,

Juan.

**Comment by juancholkovich** [comment]
Dear @mtmorgan 

I writing to wonder you about an error produced in tokay1 when it create the pdf file of the vignette:

LaTeX Error: File `framed.sty' not found.

I already passed all the package builder requirements before, in this case, I only changed the dependency to 3.4 and now I have this problem. How can I fix it?

**Comment by vobencha** [comment]
I just went on tokay1 and successfully built version 0.99.17 of coexnet which indicates there aren't any missing latex dependencies on the builder. For now I would ignore this error and proceed with the review.

Valerie

**Comment by LiNk-NY** [comment]
Hi Juan @juancholkovich, 
Thanks for making those changes. 

Just a few minor comments:
- You should use general terms for arguments that are not only a matrix (i.e., `expmat` argument in `createNet` and others should be `expData`). 
- Try to use the more robust `vapply` instead of `sapply` in your code.
- Error messages should be intelligible. For `sharedComponents` it should read: "No shared components between networks" or something close. 

Almost there!

Regards,
Marcel

**Comment by juancholkovich** [comment]
Dear Marcel @LiNk-NY 

I already made the suggested changes in the package.
I'll be aware of any additional change.

Regards.

**Comment by LiNk-NY** [comment]
Hi Juan @juancholkovich, 
Thanks for making those changes. Your package has been approved. 
Thank you for submitting to Bioconductor!

PS. To continue improvement and robustness of your package, please see [MangoTheCat/goodpractice](https://github.com/MangoTheCat/goodpractice) and [Bioconductor Guidelines](http://bioconductor.org/developers/package-guidelines/) for tips . 

Regards,
Marcel
