### ISSUE TITLE
AlphaMissenseR

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/Contributions#3221]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mtmorgan/AlphaMissenseR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 

Thank you for your submission. 
Please see the review below.

Best regards,
Marcel

---

# AlphaMissenseR #3221

## DESCRIPTION && NAMESPACE

* Looks good.

## vignettes

* Should `sql_template` be exported or should the template be copied and
pasted into the vignette? It is good to avoid using `:::` in the vignette.
* Would it make sense to provide a `clear_cache` wrapper function for
removing resources that can be identified as incompatible with newer versions
of DuckDb? It may not be necessary if new users of the package are
already on newer versions of DuckDb.
* Minor: It would be good to have the file size info shown when downloading.

## R

* Consider using `BiocBaseUtils` for type checking of arguments.
* Looks good.

## tests

Consider increasing coverage for some files. Overall, they look good.

```r
> covr::package_coverage()
AlphaMissenseR Coverage: 44.08%
R/AlphaFold.R: 0.00%
R/alphamissense_connection.R: 0.00%
R/am_aa.R: 0.00%
R/zzz.R: 0.00%
R/AlphaMissense.R: 57.69%
R/GenomicRanges.R: 72.22%
R/template.R: 85.71%
R/db.R: 91.58%
R/utilities.R: 91.67%
```

**Comment by mtmorgan** [comment]
Thanks Marcel @LiNk-NY 

> ## vignettes
> * Should `sql_template` be exported or should the template be copied and
>   pasted into the vignette? It is good to avoid using `:::` in the vignette.

I include the template directly

> * Would it make sense to provide a `clear_cache` wrapper function for
>   removing resources that can be identified as incompatible with newer versions
>   of DuckDb? It may not be necessary if new users of the package are
>   already on newer versions of DuckDb.

This is really an exceptional situation for very early adopters. The package requires a current version of DuckDB, so it will not create 'old' tables. There's a chance that the finalized DuckDb will change formats (there's only one release left for finalization, according to their plan...) but it's not known what changes will be required then.

> * Minor: It would be good to have the file size info shown when downloading.

Done, e.g.,

```
* [21:56:17][info] retrieving file name 'AlphaMissense_hg38.tsv.gz' (613.2 Mb)
```

> ## R
> * Consider using `BiocBaseUtils` for type checking of arguments.

Done
> ## tests
> Consider increasing coverage for some files. Overall, they look good.
> 
> ```r
> > covr::package_coverage()
> AlphaMissenseR Coverage: 44.08%
> R/AlphaFold.R: 0.00%
> R/alphamissense_connection.R: 0.00%
> R/am_aa.R: 0.00%
> R/zzz.R: 0.00%
> R/AlphaMissense.R: 57.69%
> R/GenomicRanges.R: 72.22%
> R/template.R: 85.71%
> R/db.R: 91.58%
> R/utilities.R: 91.67%
> ```

I increased test coverage, thanks. Currently

``` r
> covr::package_coverage()
AlphaMissenseR Coverage: 65.43%
R/zzz.R: 0.00%
R/AlphaFold.R: 29.73%
R/AlphaMissense.R: 55.56%
R/GenomicRanges.R: 72.22%
R/db.R: 92.63%
R/alphamissense_connection.R: 100.00%
R/am_aa.R: 100.00%
R/template.R: 100.00%
R/utilities.R: 100.00%
```

`R/zzz.R` is `.onLoad()`, so difficult to test directly, but `test-zzz.R` does make sure that all side effects of `.onLoad()` are realized (e.g., 'memoizing' key functions).

`R/AlphaFold.R` is somehow suspect -- there was 30% coverage before I added another test that I expected to result in much higher coverage, but covr reported a decrease...

Examples and vignettes cover more of the package.

Please let me know if there are more changes you would like made.

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
Thank you for making those changes.

Coverage looks great: 
```r
> covr::package_coverage(type="all")


AlphaMissenseR Coverage: 87.01%
R/zzz.R: 0.00%
R/AlphaMissense.R: 72.22%
R/GenomicRanges.R: 72.22%
R/db.R: 92.63%
R/AlphaFold.R: 97.30%
R/alphamissense_connection.R: 100.00%
R/am_aa.R: 100.00%
R/template.R: 100.00%
R/utilities.R: 100.00%
```

Your package has been accepted. 
Thank you for your contributions!

Best,
Marcel

**Comment by mtmorgan** [comment]
Thanks Marcel for your review and help with this package.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mtmorgan.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AlphaMissenseR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AlphaMissenseR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
