### ISSUE TITLE
PIUMA

### ISSUE THREAD

**Issue by BioinfoMonzino** [Bioconductor/Contributions#3245]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BioinfoMonzino/PIUMA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Your license in your description is GPL-2 but you provided the LICENSE file for GPL-3.  It would be better to update to GPL-3 in your DESCRIPTION file for consistency.

**Comment by BioinfoMonzino** [comment]
Dear Lori @lshep,
I fixed the two minor issues, but I got this warning:
```
* checking data for ASCII and uncompressed saves ... WARNING
  
  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                  old_size new_size compress
  vascEC_norm.rda    1.6Mb    984Kb       xz 
```

I used to build packages with` --resave-data` argument; thus, I have never get this warning. What should I do to solve this issue? 
Thanks in advance, 
Mattia.

**Comment by lshep** [comment]
You can either grab the files from the built tar on your system when you have run --resave-data that have the files compressed and then move them into your source package, or you can resave the data files using the suggested compression type (xz).   This is an old mailing list post but accurate https://stat.ethz.ch/pipermail/r-devel/2012-March/063649.html  .

**Comment by BioinfoMonzino** [comment]
@lshep 
I got this error
```
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```
It's quite strange since I am the mantainer of other two packages. However, I filled out the form again. But everytime I try to check the subscribers list with my account I got this message:
**Error
Bioc-devel roster authentication failed**

**Comment by lshep** [comment]
That is  odd.  I do not see you registered in the list.  Would you like me to register you manually?

**Comment by BioinfoMonzino** [comment]
It would be great!
Many thanks,
Mattia

Il giorno 15 dic 2023, alle ore 18:09, lshep ***@***.***> ha scritto:

﻿

That is odd. I do not see you registered in the list. Would you like me to register you manually?

**Comment by BioinfoMonzino** [comment]
@lshep, please let me know when everything is ok so that I push a new build/check.

**Comment by lshep** [comment]
I have manually added you to the bioc-devel mailing list.  If you still get an ERROR we can ignore as I can confirm registration. Please try and push a new build/check at your earliest convenience

**Comment by lazappi** [comment]
Hi @BioinfoMonzino

Thanks for submitting **PIUMA** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: I got some notes when checking the packages. The important ones should be mentioned below but please check the build report after making changes to see if there are any others.

## DESCRIPTION file

- [ ] :warning: Please check the formating of the title
- [ ] :rotating_light: There is a check warning related to the `License` field. You either need to change the `LICENSE: ` to `GPL-3 + file LICENSE` (preferred) or delete the `LICENSE` file.
- [ ] :rotating_light: Bioconductor recommends setting `LazyData: false`
- [ ] :warning: It is recommended to add a `BugReports` field. This is usually a link to the GitHub issues page for the package or the Bioconductor support forum.
- [ ] :warning: It is recommended to add a `URL` field. This is usually a link to the GitHub repository for the package.

## NAMESPACE file

- [ ] :rotating_light: Please import functions from `patchwork` rather than importing the whole package.

## The CITATION file

- [ ] :rotating_light: The citation currently isn't read correctly. You can test this with `readCitationFile("inst/CITATION")`.

## Package data

- [ ] :warning: The documentation of the datasets could be expanded. It should be clear what the source of each dataset is. I think there is some code in the vignette that could be included here.
- [ ] :warning: I think the `@format` tag should be sufficient for data documentation and you don't need to include `@return` (double check this doesn't lead to warnings though)

## Documentation

- [ ] :green_circle: It wasn't clear to me from the documentation what data types the package is designed for. You may want to make this clearer.
- [ ] :green_circle: I noticed a few typos in difference parts of the documentation. The **{spelling}** package can help with finding these.

### README

- [ ] :rotating_light: Please include Bioconductor installation instructions

### Vignette

- [ ] :rotating_light: Please name the first section *Introduction* for consistency with other Bioconductor packages
  - [ ] This should include motivation for including the package in Bioconductor and comparions to similar packages (if applicable)
- [ ] :warning: It is generally preferred to have a HTML rather than PDF website. These are better incorporated into the Bioconductor website and are more accessible to users.

### Man pages

- [ ] :warning: It is recommended to add a package man page

## Unit tests

- [ ] :rotating_light: Tests should be placed inside a `test_that()` block. Something like:

```r
test_that("function A works", {

  out <- functionA(...)

  expect_equal(out, ...)
})
```

## Code

### R

- [ ] :rotating_light: Please use `vapply` instead of `sapply`
- [ ] :warning: Please try to used named indicies instead of numeric indices
- [ ] :rotating_light: Please use `message()` instead of `cat()` or `print()`
- [ ] :rotating_light: Currently your package does not depend on any other Bioconductor packages or data structures. Can your functions be adjusted to use standard objects to increase compatibility with other Bioconductor pacakges.
- [ ] :rotating_light: Please remove commented code that is no longer used
- [ ] :warning: It is better to have separate functions for analysis and visualisation rather than doing both in one function (eg. `checkScaleFreeModel()`, `dfToProjection()`)
- [ ] :warning: It is generally better to avoid nested functions
- [ ] :warning: Chained allocation (`x <- y <- z`) can be confusing and is generally not recommended
- [ ] :green_circle: The styling is inconsistent in some places, you might want to consider using the **{styler}** package to help with this.

**Comment by BioinfoMonzino** [comment]
@lazappi Thanks a lot for the valuable feedbacks which surely help us to improve PIUMA. We will try to address all your concerns. I ill give you a feedback in the next upcoming weeks.
Thanks again,
Mattia

**Comment by BioinfoMonzino** [comment]
Dear @lazappi 
We tried to fix all your concerns. The flagged checkbox means that the task has been accomplished, in accordance with your suggestions. The **bold text** gives you motivation about our choices .

I still see a check error about vignette generation that I cannot reproduce in my systems. I try to look a bit deeper.

**Comment by BioinfoMonzino** [comment]
> Hi @BioinfoMonzino
> 
> Thanks for submitting **PIUMA** 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.
> 
> Luke
> 
> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [x]  ⚠️ I got some notes when checking the packages. The important ones should be mentioned below but please check the build report after making changes to see if there are any others.
	**Thanks for the feedback. We fixed almost all the relevant notes from Check and BiocCheck. In addition, no Errors and Warnings happened from our side during check and biocCheck.**
> 
> ## DESCRIPTION file
> * [x]  ⚠️ Please check the formating of the title
> * [x]  🚨 There is a check warning related to the `License` field. You either need to change the `LICENSE: ` to `GPL-3 + file LICENSE` (preferred) or delete the `LICENSE` file.
> * [x]  🚨 Bioconductor recommends setting `LazyData: false`
> * [x]  ⚠️ It is recommended to add a `BugReports` field. This is usually a link to the GitHub issues page for the package or the Bioconductor support forum.
> * [x]  ⚠️ It is recommended to add a `URL` field. This is usually a link to the GitHub repository for the package.
> 
> ## NAMESPACE file
> * [x]  🚨 Please import functions from `patchwork` rather than importing the whole package.
> 
> ## The CITATION file
> * [x]  🚨 The citation currently isn't read correctly. You can test this with `readCitationFile("inst/CITATION")`.
> 
> ## Package data
> * [x]  ⚠️ The documentation of the datasets could be expanded. It should be clear what the source of each dataset is. I think there is some code in the vignette that could be included here.
**We extended the data documentation for those datasets used for vignette, highlighting the paper purposes, the data repository and adding a brief description.**
**
> * [x]  ⚠️ I think the `@format` tag should be sufficient for data documentation and you don't need to include `@return` (double check this doesn't lead to warnings though)
Removing `@return` tag from data documentation leads to a Warning, during the check. Therefore, we re-added this tag to each dataset.

> 
> ## Documentation
> * [x]  🟢 It wasn't clear to me from the documentation what data types the package is designed for. You may want to make this clearer.
> * [x]  🟢 I noticed a few typos in difference parts of the documentation. The **{spelling}** package can help with finding these.
> 
> ### README
> * [x]  🚨 Please include Bioconductor installation instructions
> 
> ### Vignette
> * [x]  🚨 Please name the first section _Introduction_ for consistency with other Bioconductor packages
>   
>   * [x]  This should include motivation for including the package in Bioconductor and comparions to similar packages (if applicable)
> * [x]  ⚠️ It is generally preferred to have a HTML rather than PDF website. These are better incorporated into the Bioconductor website and are more accessible to users.
> 
> ### Man pages
> * [x]  ⚠️ It is recommended to add a package man page
> 
> ## Unit tests
> * [x]  🚨 Tests should be placed inside a `test_that()` block. Something like:
> 
> ```r
> test_that("function A works", {
> 
>   out <- functionA(...)
> 
>   expect_equal(out, ...)
> })
> ```
> 
> ## Code
> ### R
> * [x]  🚨 Please use `vapply` instead of `sapply`
> * [ ]  ⚠️ Please try to used named indicies instead of numeric indices
**In most cases, our functions loop over the features of matrices and data.frames, than can exhibit different names, each time. In such cases, we believe that numeric indices are more practical than named indices.**


> * [x]  🚨 Please use `message()` instead of `cat()` or `print()`
> * [x]  🚨 Currently your package does not depend on any other Bioconductor packages or data structures. Can your functions be adjusted to use standard objects to increase compatibility with other Bioconductor pacakges.
**We stressed this point even more in the vignette. TDA can be performed on any high-dimensional and sizable datasets, such as scRNA-seq experiment. To be compliant with the Bioconductor data compatibility we generated a 'TDAobj' (S4) object which can easily interact with the most popular Bioconductor data types, such as SummarizedExperiment, as shown in the vignette.**

> * [x]  🚨 Please remove commented code that is no longer used
> * [ ]  ⚠️ It is better to have separate functions for analysis and visualisation rather than doing both in one function (eg. `checkScaleFreeModel()`, `dfToProjection()`)
**We have designed these functions so as to provide the user with immediate visual feedbacks that allows appreciating the effect of parameters combination. However, we agree that in some cases, such as in a 'grid-search' test, the generation of several images can be heavy and not very useful. Accordingly, we decided to set to false by default the arguments that control the graphs generation, without create additional dedicated functions.**


> * [ ]  ⚠️ It is generally better to avoid nested functions
**We used nested functions in two situations: scaling data and calculating Jaccard's indexes; these functions are 1) very small (1 to 5 lines) and 2) used just one time inside the 'outer function'. Therefore, we do not believe that it is necessary to generate a dedicated script (with documentation, test, manual and so on).**

> * [x]  ⚠️ Chained allocation (`x <- y <- z`) can be confusing and is generally not recommended
> * [x]  🟢 The styling is inconsistent in some places, you might want to consider using the **{styler}** package to help with this.

**Comment by lazappi** [comment]
> > * [x]   ⚠️ I got some notes when checking the packages. The important ones should be mentioned below but please check the build report after making changes to see if there are any others.
> >   **Thanks for the feedback. We fixed almost all the relevant notes from Check and BiocCheck. In addition, no Errors and Warnings happened from our side during check and biocCheck.**

There is an error on the build report now, please check and correct this

> > * [x]   🚨 The citation currently isn't read correctly. You can test this with `readCitationFile("inst/CITATION")`.

If you don't currently have a citation available I would suggest removing this file. Bioconductor will generate a full reference full the package including DOI etc. but that will be overwritten by what is in the file.

> > * [x]   🚨 Tests should be placed inside a `test_that()` block. Something like:

> > * [ ]   ⚠️ Please try to used named indicies instead of numeric indices
> >   **In most cases, our functions loop over the features of matrices and data.frames, than can exhibit different names, each time. In such cases, we believe that numeric indices are more practical than named indices.**

- This is ok for loops, I was referring more to cases such as accessing a column from a `data.frame` using `df[, "column_name"]` rather than `df[, 1]`
- It is clearer to use `nrow(x)`/`ncol(x)` rather than `dim(x)[1]`/`dim(x)[2]` 

> > * [x]   🚨 Currently your package does not depend on any other Bioconductor packages or data structures. Can your functions be adjusted to use standard objects to increase compatibility with other Bioconductor pacakges.
> >   **We stressed this point even more in the vignette. TDA can be performed on any high-dimensional and sizable datasets, such as scRNA-seq experiment. To be compliant with the Bioconductor data compatibility we generated a 'TDAobj' (S4) object which can easily interact with the most popular Bioconductor data types, such as SummarizedExperiment, as shown in the vignette.**

- I did not see any mention of compatibility with `SummarizedExperiment` or other objects in the vignette, maybe I missed it?
- It is not an absolute requirement but there would be much greater compatibility if you operated directly on something like a `SummarizedExperiment` directly rather than creating your own object. This would allow your package to be easily included in workflows involving other Bioconductor packages.
- If you do choose to have your own custom object then you need to create getter, setter and constructor methods rather than using `@` or `slot()`

> > * [x]   🚨 Please remove commented code that is no longer used

- Please check this again, I saw some in the tests but there may be more in other places

> > * [ ]   ⚠️ It is better to have separate functions for analysis and visualisation rather than doing both in one function (eg. `checkScaleFreeModel()`, `dfToProjection()`)
> >   **We have designed these functions so as to provide the user with immediate visual feedbacks that allows appreciating the effect of parameters combination. However, we agree that in some cases, such as in a 'grid-search' test, the generation of several images can be heavy and not very useful. Accordingly, we decided to set to false by default the arguments that control the graphs generation, without create additional dedicated functions.**

Having unexpected plots appear is one consideration but there are others. Having separate functions would make it easier to modify the plots (changing themes for example). It also makes the code easier to follow and maintain when functions only do one thing.

> > * [ ]   ⚠️ It is generally better to avoid nested functions
> >   **We used nested functions in two situations: scaling data and calculating Jaccard's indexes; these functions are 1) very small (1 to 5 lines) and 2) used just one time inside the 'outer function'. Therefore, we do not believe that it is necessary to generate a dedicated script (with documentation, test, manual and so on).**

Ok. I think the code would be easier to maintain if you moved these small functions to a `utils.R` file and you would not necessarily need separate tests for them but it is probably up to you.

**Additional points:**

- Please give the test file a more meaningful name. The convention is to have one test file for each `.R` code file.
- I think these lines in `makeTDAobj()` are identical, maybe check that is what you want?

  ```r
  # find numeric columns
  indNumInt <- which(vapply(df, class, FUN.VALUE = character(1)) %in%
                       c("numeric", "integer"))

  # find factor columns
  indFact <- which(vapply(df, class, FUN.VALUE = character(1)) %!in%
                   c("numeric", "integer"))
  ```
          
- You should use `is()` (or `is.numeric()` etc.) rather than `class()`
- Please use `seq_len()`/`seq_along()` rather than `1:x`

**Comment by BioinfoMonzino** [comment]
> > > * [x]    ⚠️ I got some notes when checking the packages. The important ones should be mentioned below but please check the build report after making changes to see if there are any others.
> > >   **Thanks for the feedback. We fixed almost all the relevant notes from Check and BiocCheck. In addition, no Errors and Warnings happened from our side during check and biocCheck.**
> 
> There is an error on the build report now, please check and correct this
> 
> > > * [x]    🚨 The citation currently isn't read correctly. You can test this with `readCitationFile("inst/CITATION")`.
> 
> If you don't currently have a citation available I would suggest removing this file. Bioconductor will generate a full reference full the package including DOI etc. but that will be overwritten by what is in the file.
> 
> > > * [x]    🚨 Tests should be placed inside a `test_that()` block. Something like:
> 
> > > * [ ]    ⚠️ Please try to used named indicies instead of numeric indices
> > >   **In most cases, our functions loop over the features of matrices and data.frames, than can exhibit different names, each time. In such cases, we believe that numeric indices are more practical than named indices.**
> 
> * This is ok for loops, I was referring more to cases such as accessing a column from a `data.frame` using `df[, "column_name"]` rather than `df[, 1]`
> * It is clearer to use `nrow(x)`/`ncol(x)` rather than `dim(x)[1]`/`dim(x)[2]`
> 
> > > * [x]    🚨 Currently your package does not depend on any other Bioconductor packages or data structures. Can your functions be adjusted to use standard objects to increase compatibility with other Bioconductor pacakges.
> > >   **We stressed this point even more in the vignette. TDA can be performed on any high-dimensional and sizable datasets, such as scRNA-seq experiment. To be compliant with the Bioconductor data compatibility we generated a 'TDAobj' (S4) object which can easily interact with the most popular Bioconductor data types, such as SummarizedExperiment, as shown in the vignette.**
> 
> * I did not see any mention of compatibility with `SummarizedExperiment` or other objects in the vignette, maybe I missed it?
> * It is not an absolute requirement but there would be much greater compatibility if you operated directly on something like a `SummarizedExperiment` directly rather than creating your own object. This would allow your package to be easily included in workflows involving other Bioconductor packages.
> * If you do choose to have your own custom object then you need to create getter, setter and constructor methods rather than using `@` or `slot()`
> 
> > > * [x]    🚨 Please remove commented code that is no longer used
> 
> * Please check this again, I saw some in the tests but there may be more in other places
> 
> > > * [ ]    ⚠️ It is better to have separate functions for analysis and visualisation rather than doing both in one function (eg. `checkScaleFreeModel()`, `dfToProjection()`)
> > >   **We have designed these functions so as to provide the user with immediate visual feedbacks that allows appreciating the effect of parameters combination. However, we agree that in some cases, such as in a 'grid-search' test, the generation of several images can be heavy and not very useful. Accordingly, we decided to set to false by default the arguments that control the graphs generation, without create additional dedicated functions.**
> 
> Having unexpected plots appear is one consideration but there are others. Having separate functions would make it easier to modify the plots (changing themes for example). It also makes the code easier to follow and maintain when functions only do one thing.
> 
> > > * [ ]    ⚠️ It is generally better to avoid nested functions
> > >   **We used nested functions in two situations: scaling data and calculating Jaccard's indexes; these functions are 1) very small (1 to 5 lines) and 2) used just one time inside the 'outer function'. Therefore, we do not believe that it is necessary to generate a dedicated script (with documentation, test, manual and so on).**
> 
> Ok. I think the code would be easier to maintain if you moved these small functions to a `utils.R` file and you would not necessarily need separate tests for them but it is probably up to you.
> 
> **Additional points:**
> 
> * Please give the test file a more meaningful name. The convention is to have one test file for each `.R` code file.
> * I think these lines in `makeTDAobj()` are identical, maybe check that is what you want?
>   ```r
>   # find numeric columns
>   indNumInt <- which(vapply(df, class, FUN.VALUE = character(1)) %in%
>                        c("numeric", "integer"))
>   
>   # find factor columns
>   indFact <- which(vapply(df, class, FUN.VALUE = character(1)) %!in%
>                    c("numeric", "integer"))
>   ```
> * You should use `is()` (or `is.numeric()` etc.) rather than `class()`
> * Please use `seq_len()`/`seq_along()` rather than `1:x`

Dear @lazappi,
I'm supposed to have addressed your last concerns; specifically:

- I added a utils.R file with 'one-line' and plot functions
- I created setter and getter methods for TDAobj to interact with its attributes
- I created a new import function to create a TDAobj from a SummarizedExperiment object
- I removed the CITATION file
- I created a test file for each .R code file
- I fixed the minor code issues, (1:x, is/class, "column name",nrow/ncol), when appropriate.

**Comment by lazappi** [comment]
> * I added a utils.R file with 'one-line' and plot functions

Thanks. I think things could be organised a bit better (moving plotting to a different file for example) but this is ok.

- In the `jaccard()` function it would be clearer to using `length(union(a, b))`
- If you have a binary function argument it is better to use `arg = c(TRUE, FALSE)` rather than `arg = c("yes", "no")`

For some reason, the last build doesn't seem to have worked. If you can push a new version to restart that and it completes successfully I think this can be accepted.

**Comment by BioinfoMonzino** [comment]
@lazappi I fixed your last issues and pushed a new build (v.0.99.8).
Thanks again

**Comment by lazappi** [comment]
Great! I am happy to accept this now.

**Comment by lazappi** [comment]
Congratulations on getting **{PIUMA}** accepted into Bioconductor 🎉! It can take a few days to get picked up by the build system but then it should be available as part of Bioconductor devel.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BioinfoMonzino.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PIUMA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PIUMA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
