### ISSUE TITLE
ClustAll

### ISSUE THREAD

**Issue by asiort** [Bioconductor/Contributions#3253]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/translationalBioinformaticsUnit/ClustAll

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
All package dependencies must be active on CRAN or Bioconductor.  clusteval was removed from CRAN in June of 2021.  See https://cran.r-project.org/web/packages/clusteval/index.html .  You must not use this package as a dependency or reach out to the clusteval maintainers to reinstate on CRAN.

**Comment by asiort** [comment]
I have fixed the dependencies problem and updated my GitHub repository. But when I push to git@git.bioconductor.org:packages/ClustAll I have problems with the credentials.

I am following the tutorial [21.5.1 New package workflow](https://contributions.bioconductor.org/git-version-control.html#new-package-workflow) but when doing "git fetch --all" I get the following error: 
"""
$ git fetch --all
Fetching origin
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream
"""
How could I fix it?

Thanks in advance.

**Comment by lshep** [comment]
I will put this through to getting on our git and getting our build reports but when I ran this locally there were many ERROR and Warnings that need to be cleaned up before a reviewer will be assigned for in depth review.

**Comment by DarioS** [comment]
I have evaluated the package and identified some improvements which are needed.
- Inefficient `for` loops mustn't be used. Use lapply or vapply instead, in accordance with [the Developer's Guide](https://contributions.bioconductor.org/r-code.html#pre-allocate-and-fill-if-iterations-are-necessary).
  ```r
  createEmptyArrays <- function(nvariables, data_use) {
    summary_matrices <- vector("list", nvariables)
    for(i in seq_len(nvariables)) {
      summary_matrices[[i]] <- as_FBM(matrix(0,nrow(data_use),nrow(data_use)))
  }
  ```
- `ClustAllObject` has no `show` method. It floods my R console when printed out. Also, there are no accessors.
```
> obj_noNA
   ...       ...
   560        0.096530    0.2112            0.08732
561        0.104800    0.2250            0.08321
562        0.000000    0.1566            0.05905
563        0.235600    0.4089            0.14090
564        0.254200    0.2929            0.09873
565        0.221600    0.2060            0.07115
566        0.162800    0.2572            0.06637
567        0.141800    0.2218            0.07820
568        0.265000    0.4087            0.12400
569        0.000000    0.2871            0.07039

Slot "dataImputed":
NULL

Slot "dataValidation":
  [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 1 1 1 1 1 2 2 1 2 2 1 1 1 1 2 1 2 2 1 1 1 1 2 1 2 2 1 2 1 2 2 1 1
 [82] 1 2 2 1 2 2 2 1 1 1 2 1 1 2 2 1 1 1 2 2 1 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 2 2 2 1 2 2 1 1 1 2 2 1 2 1 2 2 1 2 2 1 1 2 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2
[163] 2 1 2 1 1 2 2 1 1 2 2 1 1 1 1 2 1 1 2 2 2 1 2 1 2 1 1 1 2 1 1 2 2 1 2 2 2 2 1 2 2 2 1 2 1 2 1 1 2 1 2 2 2 2 1 1 2 2 1 1 1 2 1 1 1 1 1 2 2 1 1 2 1 1 2 2 1 2 1 1 1
[244] 1 2 1 1 1 1 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 2 1 2 1 1 2 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 2
[325] 1 1 1 1 2 2 2 1 1 1 1 2 1 2 1 2 1 1 1 2 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 2 2 1 2 2 2 1 2 2 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 2 1 1 2 2 1 1 1 1 1 1 2 1 1 1 1
[406] 1 1 1 2 1 1 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1 2 1 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
[487] 1 2 1 2 1 1 2 1 1 1 1 1 2 2 1 2 1 2 1 1 1 1 1 2 1 1 2 1 2 1 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
[568] 2 1

Slot "nImputation":
[1] 0

Slot "processed":
[1] FALSE

Slot "summary_clusters":
NULL

Slot "JACCARD_DISTANCE_F":
NULL
```
- Vignette needs work. The breast cancer example consists of a bunch of headings and code blocks with no interpretation of output. Also, the first part is just a list of arguments and definitions from the functions. Don't duplicate such information.
- There is only one unit test and it simply creates an S4 object. Needs non-trivial testing for correctness of calculations.

**Comment by asiort** [comment]
@DarioS Thanks for evaluating the package. I will implement your suggestions as soon as possible :)

**Comment by asiort** [comment]
@DarioS I have implemented the changes you suggested:

-  I modify the inefficient for loop using apply. You will find those implementations in the following functions:
   From ClustAll_runClustAll_internal.R file: createEmptyArrays (line 7), cstats.table_hclust (line 113).
   From ClustAll_ClustAllObject_Methods.R file: resStratification (lines 205 and 207), plotSANKEY (line 380)
   From ClustAll_ClustAllObject_Methods_internal.R file: chooseClusters (line 80)
   
- Implemented show and accessors (with the exception of the accessor to access data slot to not overwrite the utils::data() function. Instead I have generated the method showData). Now look like this:

```
> obj_noNA1
ClustAllObject
Data: Number of variables: 30. Number of patients: 569
Imputation: NO.
Number of imputations: 0
Processed: TRUE
Number of stratifications: 72
```

- The vignette has been improved, focusing more on the explanation and interpretation of the output.
- More unit tests have been added for non-trivial testing. 

Thanks for your time!

**Comment by DarioS** [comment]
The issues have been partially addressed. I still think that the vignette and code both have room for improvement.

- `# This part of the code is commented out as it exceeds the R CMD check time on the macOS 12.7.1 Monterey.` That's actually fine, so please uncomment this. It is a known issue and the timeout for that machine is fine to have happening.
- The unit tests still check only for object creation. Please add at least one test for numerical correctness (e.g. `checkEquals`).
- There are still numerous unnecessary `for` loops. For example,
```r
      paint_names <- c()
      for (i in seq_len(length(res))) {
        paint_names <- c(paint_names, res[[i]][[1]][1])
        paint_names <- c(paint_names, res[[i]][[length(res[[i]])]][1])
      }
```
This has the exact define-and-grow format which the developer's guide requires us not to do. 27 `for` loops remain. Some of them look necessary but all of the ones that are indexed from one to the length of a vector are very likely not necessary.
- Plot in vignette lacks readable y-axis labels due to overlapping text placement. Change `fig.height` or hide the labels.
![image](https://github.com/Bioconductor/Contributions/assets/631218/17c68402-953a-4e3a-b1e0-72d050827b10)
- Bioconductor vignettes need to use [BiocStyle](https://bioconductor.org/packages/release/bioc/html/BiocStyle.html) style.

Also, one minor observation. The package is called ClustAll but, in the vignette, it varies between ClustALL and ClustAll. ALL makes me think of Acute Lymphoblastic Leukemia, so perhaps it is best to use ClustAll consistently.

**Comment by asiort** [comment]
Hi @DarioS  I've implemented the new suggestions:

Regarding the tests:
- I've uncommented the lines in the test tests/runClustAll_example.R.
- More tests can be found at inst/unitTests. You will also find commented lines regarding tests that I performed on internal functions during development. On the other hand, inside tests/, you will find general examples of methods (different scenarios of object creation and parallelization).


Regarding the Vignette:
- The plot size has been corrected.
- BiocStyle style has been implemented according to the documentation. 
- Spelling and typos have been corrected

Regarding the for loops:
- I have checked all for loops and changed all unnecessary ones. In total, I have modified 16 into applys. I have kept 11 for loops necessary due to their complexity or parallelization.

Find here the for loops that I modified into applys:
- ClustAll_CreateClustAll_internal: Lines 40; 55 and 57
- ClustAll_ClustAllObject_Methods: Lines 106 and 110.
- ClustAll_ClustAllObject_Methods_internal: Lines 88 and 97.
- ClustAll_runClustAll: Lines line192; 220; 260; 278; 349; 377; 415; 429 and 539.

Here are the for loops that I consider necessary:
- ClustAll_runClustAll.R: Lines 484 and 512. 
- ClustAll_runClustAll_internal.R: 60; 85; 219; 220; 255 and 256.
- ClustAll_ClustAllObject_Methods_internal.R: Lines: 12; 30 and 89.

Please let me know if any other improvements would be necessary to implement or discuss.
Thanks again for your time.

**Comment by DarioS** [comment]
Thank you.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/asiort.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ClustAll")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ClustAll

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
