### ISSUE TITLE
(inactive) RNASeqHelper

### ISSUE THREAD

**Issue by mtekman** [Bioconductor/Contributions#3261]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mtekman/RNASeqHelper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please use `tempdir()` to specify the temporary output directory instead of manually "/tmp" this ensure cross OS compatibility and write access by the user making the calls.

**Comment by mtekman** [comment]
Added changes:
- now uses tempdir()
- minor spacing fixes for other warnings

**Comment by mtekman** [comment]
I keep hitting this error with svglite. It's definitely a required module for the `svg` device to work.

It builds fine locally on my machine, but it seems to fail on the CI. Any ideas?

**Comment by lshep** [comment]
I just did a quick check and the version is 2.1.2  on merdia1 but 2.1.3 is required.  @jwokaty  can you check why this CRAN package is not picking up the most recent version on CRAN;  https://cran.r-project.org/web/packages/svglite/index.html.  I will note I just restarted the linux builder and checked the version there and that is 2.1.3 so on the next try hopefully you would get farther on that OS check

**Comment by mtekman** [comment]
okay, I will push tomorrow just in case more time is needed, thanks!

**Comment by jwokaty** [comment]
@mtekman `svglite` 2.1.3 is installed on merida1 now. It wasn't installed automatically because the CRAN macOS binaries lag behind the source packages, so I had to manually update it.

**Comment by mtekman** [comment]
Thanks all! The message I am getting now is:

> WARNING: R CMD check exceeded 10 min requirement

My examples (and indeed the vignette) require at least 1000 features to function properly. Too small, the dispersion of the DESeq2 fitting become useless, and clustering produces nonsensical clustering that serves no educational purpose.

Is the 10min limit a hard requirement?

**Comment by lshep** [comment]
It will be important to try and cut back on the check time as much as possible.

**Comment by lshep** [comment]
In your vignette, you currently are writing to the home directory when you are doing `~/myanalysis/` and `~/myanalysis2`;  This is very problematic! Please do not write to the home directory and write all output to `tempdir()` instead of `~/` .

**Comment by mtekman** [comment]
Hi @lshep, thanks for the warning!

I've also noticed that my code falls apart if there is no "time" component in my phenotype data, so this is something I will fix before I ask you to review it again.

Cheers!

**Comment by mtekman** [comment]
Hello again, new version with:

* Changed `~/` → `tempdir()`
* Fix to phenotype data without time info
* Linting checks, default checks, biocchecks
* Reduced test time from 10m → 2m
* BiocStyle in Vignette

Hopefully this is the one! 
Happily awaiting your review.

**Comment by DarioS** [comment]
I have evaluated the software and have major revisions to request, mainly about improved Bioconductor interoperability..

- Function and variable naming does not confirm to [coding style requirements](https://contributions.bioconductor.org/r-code.html#rcode-function-names) in Developer's Guide. `camelCase` not `snake_case` unlike tidyverse.
- Depends on tidyverse variable types such as `tibble` rather than Bioconductor variable types such as [`DataFrame`](https://rdrr.io/bioc/S4Vectors/man/DataFrame-class.html). e.g.
    `\item{long_data}{A tibble containing columns: gene, condition, value, and optionally time}`. Please switch.
- Input RNA-seq data is required to be a plain numeric matrix.
 `\item{tab}{a matrix of samples (columns) and genes (rows)}`.
 Needs to support `RangedSummarizedExperiment` input to demonstrate improved interoperability with Bioconductor.    
- Package is named RNASeqHelper but it only supports DESeq2 as back-end. How about edgeR? edgeR is 24th-ranked and DESeq2 is 26th-ranked based on monthly downloads, so such a pipeline should support both frameworks at a minimum. Don't instantly exclude about 50% of your future citations!
- The developers of DESeq2 have a special package named [tximport](https://bioconductor.org/packages/release/bioc/html/tximport.html) for importing RNA-seq data. This is important for avoiding confounding by changes in gene length but not gene abundance. RNASeqHelper ignores this best-practice.
- All of the code is in a single file 1344 lines long. Please modularise into separate .R files to make finding functions easy.
- The vignette shows how RNASeqHelper operates on simulated data. Instead, please demonstrate how your package is useful for analysing a real data set. Please find a data set from [Experiment Data](https://bioconductor.org/packages/3.18/BiocViews.html#___ExperimentData) view and use that instead. Also, note that using `rnorm` is unsuitable for simulating RNA-seq data. `makeExampleDESeqDataSet` from DESeq2 is ideal.
- Vignette needs to follow the sections of the Developer's Guide [Vignettes](https://contributions.bioconductor.org/docs.html#vignettes) section. In particuar, there is no Installation section.
- The unit tests seem incomplete. Most don't have `expect` or `succeed` or `fail` in them.

**Comment by mtekman** [comment]
Dear Dario,

Thank you for your comprehensive review, you have definitely given me a
lot to think about.

> - RangedSummarizedExperiment, makeExampleDESeqDataSet, tximport,
>   Installation, better unit tests.

Thanks for these hints, I will do these changes!

> - edgeR

I do not have too much experience with edgeR, but I think you're right that it would be a huge win to incorporate it into the library, and it would even offer a nice "keepgenes" alternative method.

> - `tibble` rather than `DataFrame`

I will remove tidyverse variable types, but can I at least keep dplyr `%>%` piping, or is that also bad?

> - Function and variable naming does not confirm to [coding style requirements](https://contributions.bioconductor.org/r-code.html#rcode-function-names) in Developer's Guide. `camelCase` not `snake_case` unlike tidyverse.

All of my functions were previously camelCase, but I was told that I failed many linting checks, and so changed them all to snake_case at the behest of lintr.

Since the default lintr rules do not seem to be encouraged, may I ask which lintr rules are? I found [this](https://github.com/Bioconductor/BiocCheck/issues/62), but the rules do not seem to work with the current version of lintr.

> - All of the code is in a single file 1344 lines long. Please
> modularise into separate .R files to make finding functions easy.

I find it much easier to keep things in a single R file, since I only need to mentally grapple with a single buffer. It also greatly helps when I produce a dependency map of my code (see image below). Is this a _strict_ requirement?

![image](https://github.com/Bioconductor/Contributions/assets/20641402/2714bb20-91e7-4714-95c9-9eb14da73f47)

Thanks again,
Mehmet

**Comment by DarioS** [comment]
The coding style requirements are in [R Code](https://contributions.bioconductor.org/r-code.html) chapter. You may keep functions in one file. How about [base R pipe](https://r4ds.hadley.nz/workflow-style.html#sec-pipes) `|>` ?

**Comment by mtekman** [comment]
You just blew my mind about the base R pipe, I genuinely thought that was a dplyr implementation only.

I guess I will try `formatR` as a linter, cheers

**Comment by mtekman** [comment]
TODO: 
- Use the new tidyomics package to maintain some of the piping structure and other tidy-based functions and variables
