### ISSUE TITLE
tpSVG

### ISSUE THREAD

**Issue by boyiguo1** [Bioconductor/Contributions#3264]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/boyiguo1/tpSVG

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by boyiguo1** [comment]
@lshep I apologize for tagging you. I believe the the package builder warning is a false positive.

In the previous two build reports [build report](http://bioconductor.org/spb_reports/tpSVG_buildreport_20240110111610.html) for 0.99.2 and [build report](http://bioconductor.org/spb_reports/tpSVG_buildreport_20240110121617.html) for 0.99.3, an outstanding warning message in _Check_ is associated with bioconductor software dependencies.
 
> * Checking for Bioconductor software dependencies...
    * WARNING: No Bioconductor dependencies detected; consider a CRAN
      submission.

IMO, the package depends on [`SpatialExperiment`](https://bioconductor.org/packages/release/bioc/html/SpatialExperiment.html) either via "Imports"(0.99.2) or "Depends" (0.99.3).

If this is a false positive, I'm happy to create a issue and document it in [BiocCheck](https://github.com/Bioconductor/BiocCheck/issues). Otherwise, I would appreciate any of your input.

Thank you so much!

Best,
Boyi

**Comment by lshep** [comment]
Yes please open an issue on BiocCheck if you think it is a false positive.  It was recently added this past week and may need some tweaking.

**Comment by boyiguo1** [comment]
Hi,

I wonder if there is a timeline for when the peer-review would be starting. I would be extremely grateful for this information so that I could plan for manuscript submission, etc. 

I understand that there are a lot unseen efforts going on, and I really appreciate all!

Sincerely,
Boyi

**Comment by lshep** [comment]
We try to look and moderate once a week or every other week.  I will look at assigning a reviewer likely later today or tomorrow at the latest.  Sorry for the inconvenience.

**Comment by boyiguo1** [comment]
Got it. Thanks for sharing this information with me. It is very helpful for me to plan for other efforts.

I really appreciate the Bioconductor team for the responsiveness and huge efforts putting into to running and maintaining a such valuable community!!!

**Comment by lshep** [comment]
We strongly advise adding unit test to make sure your function is behaving as expected

**Comment by lshep** [comment]
We strongly advise adding unit tests to check whether the function is behaving as expected.
In your intro_to_tpSVG could you expand the intro to provide comparisons to existing packages like nnSVG on how this package differs.

**Comment by boyiguo1** [comment]
Sounds great! I think I would be able to do that. I'm looking for about 3-week-ish turnaround time for the unit tests and comparison, if this is okay.

**Comment by lshep** [comment]
yes. thank you.

**Comment by lshep** [comment]
also completely optionally but considering the second vignette is so short it might be worth just adding as a supplemental section at the end of the intro vignette

**Comment by boyiguo1** [comment]
@lshep  Thanks for your patience! I've addressed the previous comments via a recent PR (https://github.com/boyiguo1/tpSVG/pull/14)

> We strongly advise adding unit tests to check whether the function is behaving as expected.

_I've initiated some unit tests to check if the error prevention for arguments._

> In your intro_to_tpSVG could you expand the intro to provide comparisons to existing packages like nnSVG on how this package differs.

_I've added the a paragraph in the vignette explains the innovation of our package, `tpSVG`, which provides a scalable and flexible framework to model count data instead of log-transformed count. A specific example is given comparing the gene ranking from `nnSVG` (modeling log-transformed gene counts with Gaussian process model ) and from `tpSVG` (modeling gene counts with thin plate regression spline), which results different inference results._

> also completely optionally but considering the second vignette is so short it might be worth just adding as a supplemental section at the end of the intro vignette

_I have placed the shorter vignette to the end of the intro vignette._

Thank you very much!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/boyiguo1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tpSVG")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tpSVG

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
