### ISSUE TITLE
Submission of the tidyomics package

### ISSUE THREAD

**Issue by william-hutchison** [Bioconductor/Contributions#3268]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tidyomics/tidyomics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by william-hutchison** [comment]
Hello, this is a small package with the purpose of installing and loading other packages in our software collection. In our minds, it would be ideal for the user to install all packages in the collection with:
`BiocManager::install("tidyomics")`

and then load all packages with:
`library(tidyomcis)`

In the same manner as the **tidyverse** package does for the tidyverse software collection. We are submitting the **tidyomics** package to Bioconductor as most packages in the collection are also in Bioconductor. The three warnings currently produced are a result of the function of the package:

- `WARNING: Avoid the use of 'library' or 'require' in R code `- Library is needed to load the other packages in the collection
- `WARNING: No Bioconductor dependencies detected; consider a CRAN submission.` - No Bioconductor functions are called, but Bioconductor packages are listed as imports for installation  
- `WARNING: Evaluate more vignette chunks. 3 out of 5 code chunks = 60% unevaluated 0 non-exec code chunk(s) (e.g., '```r')` - We do not want to evaluate documentation code which describes installing packages on the user's computer

Let me know if you would like to see any changes to this package or if you have any comments. Thank you for considering **tidyomics** for inclusion in Bioconductor. 

Kind regards,
William

**Comment by lshep** [comment]
I'm confused in the vignette at why plyinteractions and tidySpatialExperiment are not able to automatic installation as they have been accepted into Bioconductor?   We don't endorse advertising install packages from github or using packages that are not in CRAN or Bioconductor so we would recommend removing 'tidyof' until it is officially submitted to CRAN or Bioconductor.

**Comment by william-hutchison** [comment]
Hi @lshep, thank you for your feedback. 

I have updated the **tidySpatialExperiment** installation method to BiocManager now that the package is in Bioconductor and have removed GitHub installation instruction for **tidytof**.  

Although **plyinteractions**, **tidytof** and **tidySpatialExperiment** are all solid packages, they are very new. Our idea is to reserve automatic installation for the most mature packages in our _tidyomics_ ecosystem. 

Let me know if you would like to see any further changes.

Kind regards,
William

**Comment by lshep** [comment]
Please update the vignette to show install from Bioconductor.

**Comment by lshep** [comment]
**man**

- [ ] Please have a man page display when a naive user does `?tidyomics`


**vignette**

- [ ] Please use your helper function `tidyomics_packages()` to show the `core
  packages` rather than cite a line of code.

- [ ] Please update to show Bioconductor installation instead of github

- [ ] Please update the vignette according. Again `plyinteractions` and
  `tidySpatialExperiment` are now in Bioconductor and should not show github
  installations.  Please remove the mention on `tidyof` until `tidyof` is in
  CRAN. We do not endorse advertising packages that are not on Bioconductor or
  CRAN.

- [ ] Perhaps an explaination of why you choose not to include these packages in
  the auto install would be reasonable in the vignette. As someone can easily
  see how to add them to the autoinstall.

- [ ] It would likely be useful to list the packages installed automatically and
  how they can be used. Similar to the table provided at
  https://github.com/tidyomics#key-tidyomics-packages but included in the
  vignette so users don't have to click to multiple places to find this useful
  information.

 - [ ] Please include a `sessionInfo()` section at the end of the vignette

**Comment by william-hutchison** [comment]
Thank you for your advice. I am occupied with a different project for the next few days, but I will make these changes as soon as possible - probably by mid-next week.

**Comment by william-hutchison** [comment]
Hi @lshep, I have made all requested changes to the **tidyomics** package. Let me know if you have any further suggestions. Thanks again.

**Comment by lshep** [comment]
Thanks

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/william-hutchison.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tidyomics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tidyomics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
