### ISSUE TITLE
TransOmicsData ExperimentHub package

### ISSUE THREAD

**Issue by PYangLab** [Bioconductor/Contributions#3270]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PYangLab/TransOmicsData

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Note: when I `R CMD build` your package right now it ERROR with `could not find function "listDatasets"`.  You should do a `library(TransOmicsData)` to load your package before calling your package function in the vignette.

**Comment by carissaynchen** [comment]
Hi Ishep, is the doi issued after publishing the package? I'm not sure how to address the warning about the doi.

**Comment by lshep** [comment]
yes a doi is issued after acceptance. You can ignore that warning for now

**Comment by carissaynchen** [comment]
Hi @Kayla-Morrell, thank you for reviewing this package. Are there any updates on this package review?

**Comment by Kayla-Morrell** [comment]
@carissaynchen - So sorry for the delay, I've been transitioning between jobs. I'll work on getting an initial review posted over the next couple of days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@carissaynchen - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

- [ ] REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. Since you are using a standard license you shouldn't need to include the LICENSE file with the package.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field, and structure it as a full paragraph.
- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with 'comment=c(ORCID="...")'.
- [ ] SUGGESTION: Provide 'URL' or 'BugReports' field in DESCRIPTION.

## NAMESPACE

- [ ] REQUIRED: Package in Depends field not imported from: 'ExperimentHub'. This package needs to be imported from (in the NAMESPACE file) for when this namespace is loaded but not attached.

## CITATION

- [ ] SUGGESTION: Include the 'doi' argument in CITATION 'bibentry()'.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install the package from Bioconductor.

## R code

- [ ] REQUIRED: In listDatasets, 'read.table()' partial argument match of 'head' to 'header'.
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 5 lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line indents. There are 2 lines that are not.

Best,
Kayla

**Comment by carissaynchen** [comment]
Hi Kayla, I have made the changes below:

> ## General package development
> * [X]  REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. Since you are using a standard license you shouldn't need to include the LICENSE file with the package.
> 
> ## DESCRIPTION
> * [X]  SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field, and structure it as a full paragraph.
> * [X]  SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with 'comment=c(ORCID="...")'.
> * [X]  SUGGESTION: Provide 'URL' or 'BugReports' field in DESCRIPTION.
> 
> ## NAMESPACE
> * [ ]  REQUIRED: Package in Depends field not imported from: 'ExperimentHub'. This package needs to be imported from (in the NAMESPACE file) for when this namespace is loaded but not attached.
_I have removed the package ExperimentHub from the Depends field as my function does not require the package._

> ## CITATION
> * [ ]  SUGGESTION: Include the 'doi' argument in CITATION 'bibentry()'.
_I will add this when I have been issued a doi._
> ## Vignette
> * [X]  REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install the package from Bioconductor.

> ## R code
> * [X]  REQUIRED: In listDatasets, 'read.table()' partial argument match of 'head' to 'header'.
> * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 5 lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line indents. There are 2 lines that are not.

**Comment by carissaynchen** [comment]
@Kayla-Morrell I have tried to resolve the error regarding subscribing to the bioc-devel mailing list and I'm not sure why that has appeared as the maintainer has signed up to the mailing list...

**Comment by carissaynchen** [comment]
Hi @Kayla-Morrell I've been trying to resolve the error with the bioc-devel subscription, and the maintainer has signed up to the mailing list so I'm not sure why the error is unresolved. Is there a way around this?

**Comment by lshep** [comment]
Just to be clear here,  This assumes that the submitter and the maintainer in the package is registered.  The currently listed maintainer and maintainer email is:  `person(given = "Di", family = "Xiao", email = "d.xiao@sydney.edu.au", role=c("aut", "cre")`   So it is looking for d.xiao@sydney.edu.au  to be registered.  Sometime the registration requires confirmation and the confirmation email can end up in the spam folder.  I currently do not see this email registered.  If you do not see a confirmation email in spam, let us know and we can follow up.

**Comment by carissaynchen** [comment]
Hi @lshep, could you check again whether d.xiao@sydney.edu.au is registered? we are both receiving the bioc-devel emails now.

**Comment by lshep** [comment]
yes I can see them

**Comment by Kayla-Morrell** [comment]
@PYangLab - Thank you for making the necessary changes. I have looked everything over and I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PYangLab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TransOmicsData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TransOmicsData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
