### ISSUE TITLE
dinoR

### ISSUE THREAD

**Issue by xxxmichixxx** [Bioconductor/Contributions#3273]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xxxmichixxx/dinoR

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Thank you for your submission. Please see comments below: 

**inst**

- [ ] Please provide an `inst/script` directory that contains information on how
  the data in `inst/extdata` was generated. Include any relevant source or
  licensing information. It can be code, pseudocode, or text but should indicate
  how a user would create the data.

**man**

- [ ] Please include a package level man page so when a naive user tried
  `?dinoR` they have some indication of how to get started.

**vignette**

- [ ] Please provide an introductory section that describes the package
  functionality and why you are submitting to Bioconductor; including any
  relevant comparison to existing packages of similar functonality. 

- [ ] Please update vignette installation instructions to be from Bioconductor

- [ ] Are their plans to submit the referenced Github only packages fetch-NOMe
  and NOMeConverteR to CRAN or Bioconductor?  We generally discourage
  advertising use of non CRAN / Bioconductor packages.

- [ ] Would it make more sense to move the rds file to a data directory to be
  able to load automatically with a `data()` call in man page examples and
  vignette?

- [ ]  In the section "Determine fragment counts for five chromatin patterns:
  TF, open, upNuc, downNuc, Nuc" ,  I'm unclear at what footprintCalc vs
  footprintQuant is doing especially since you overwrite the object by passing
  the first result as the argument to the second (which is fine if you can
  better distinguish what happens in each step)

**NAMESPACE**

- [ ] While we generally encourage selective imports as you have done,  if you
  are using a standard class as output (ie. SummarizedExperiment) it might be
  better to import the entire package so that all class functionality can be
  inherited directly when loading your package rather than having to separately
  load the class library.

**R code**

- [ ] Please consider formatting recommendation from BiocCheck. There are some
  helpful tools that can automate this process.

- [ ] Please have argument checking for functions. If a user is expected to
  provide certain objects or has a limited set of options please check for
  that. Using compareFootprints.R but should be applied throughout all: if
  footprints_percentages should be a certain expected class type (like a tibble)
  check for that.  arguments that have limited set of acceptable values like
  WTsamples and KOsamples should ues something like `match.arg` to check for
  validity.

**Comment by xxxmichixxx** [comment]
Thank you for the helpful review. Please see my answers below:

**inst**

The data for the vignette were moved to the data directory as suggested, and are described in data.R. The other two small data files were removed and data are generated directly in the examples now.

**man**

I added a package man page.

**vignette**

An introduction was added and installation instructions were updated.

The fetch-NOMe function will be submitted to Bioconductor as part of a bigger package later. I can submit the  NOMeConverteR  package already, or add the function to dinoR. However, it might make sense to wait for fetch-NOMe since NOMeConverteR  has only one function that is to convert the fetch-NOMe output into a Ranged Summarized Experiment? In the meantime, I suggest an alternative package that is available on Bioconductor in the vignette, that can be used to map the reads and get the methylation calls. 

I moved the data for the vignette so they can be loaded with data().

I split the two different steps for "Determine fragment counts for five chromatin patterns” and added more explanations. 

**NAMESPACE**

I added SummarizedExperiment to the  “depends”  section of the DESCRIPTION.

**R code**

I formatted all code and text to match the BiocCheck reccomendations (except the automatically generated .rd files). I added argument checking to all functions.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xxxmichixxx.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dinoR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dinoR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
