### ISSUE TITLE
transmogR

### ISSUE THREAD

**Issue by smped** [Bioconductor/Contributions#3277]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/smped/transmogR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
you will likely be asked to make in `inst/script` that should have code, pseudocode, or text describing how the files in `inst/extdata` were creating including any relevant source or licensing information.

**Comment by smped** [comment]
Hi @lshep ,

Thanks for the heads up. I have these documented in `data-raw` as markdown files. Should I move these files to `inst/scripts`?

**Comment by LiNk-NY** [comment]
Hi Stevie, @smped 

Thank you for your submission.
Please see the review below. 

Best regards,
Marcel

--- 

# transmogR #3277

Overall, a solid package with good re-use of Bioconductor functionality
(GRanges, etc.).

## DESCRIPTION

* Looks good.

## NAMESPACE

* Consider separating plotting functionality into another package.

## vignettes

* The `## Installation` code example should only install `transmogR`. The
other packages are assumed to be available (when added to the `Suggests` field
in the `DESCRIPTION`)
* Looks good.

## R

* Consider using a default empty mask in the method function signature, i.e.,
`mask = GRanges()` rather than using `if missing(mask) ...` in `genomogrify.R`
* Remove old code from methods e.g., in the `indelcator`
XString,GRanges-method: `cl <- class((x))`.
* Avoid class checks in S4 methods, they are not necessary
(owl,XStringSet,GRanges-method).
* Consider conditionally importing packages for plotting e.g., `ComplexUpset`
by including it in the `Suggests`. See https://contributions.bioconductor.org/
for details.

## tests

* Coverage looks excellent:

```r
> covr::package_coverage()
transmogR Coverage: 97.28%
R/genomogrify.R: 90.74%
R/parY.R: 94.12%
R/helpers.R: 94.83%
R/sjFromExons.R: 97.44%
R/transmogrify.R: 98.82%
R/indelcator.R: 100.00%
R/overlapsByVar.R: 100.00%
R/owl.R: 100.00%
R/upsetVarByCol.R: 100.00%
R/varTypes.R: 100.00%
```

**Comment by smped** [comment]
Thanks Marcel. Appreciate the suggestions & some great pickups there too. I'll update & push over the next few days

**Comment by smped** [comment]
Hi Marcel,

Changes made are:

- Moved `ComplexUpset` and `InteractionSet` to Suggests
- Removed unnecessary class checks
- Added `mask = GRanges()` for `genomogrify()`
- Removed extraneous installations from the vignette 

Let me know if you spot anything else & I'll get onto it.

**Comment by smped** [comment]
Hi again @LiNk-NY ,

I can't push to Bioc. Is there a problem that needs to be rectified? Here's my `git` settings for the repo

``` bash
$ git remote -v
origin	git@github.com:smped/transmogR.git (fetch)
origin	git@github.com:smped/transmogR.git (push)
upstream	git@git.bioconductor.org:packages/transmogR.git (fetch)
upstream	git@git.bioconductor.org:packages/transmogR.git (push)
```

I figured these out from Section 21.5.2 [here](https://contributions.bioconductor.org/git-version-control.html)

The output I see when I try is

``` bash
$ git push upstream devel
FATAL: W any packages/transmogR steveped DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I changed my git username to `smped` a year or two back because `steveped` was problematic, so could that be the issue?

**Comment by lshep** [comment]
We had to make a change in our configuration file.  It should be updated and you should have access now. Sorry for the inconvenience.

**Comment by smped** [comment]
Thanks @lshep! Looks like that's done the trick.

**Comment by smped** [comment]
Hi @lshep & @LiNk-NY 

Going through the above report, it's pretty clear that `merida1` is about 2-2.5 times slower at nearly every step. Where I see 12s on `nebbiolo1`, I can see 28s on `merida1`, and this applies for nearly every checking step with a timing provided. I read Vince's comment to the developers of `MIRit` and it seems this is a commonly emerging issue that you're actively trying to resolve, even though I'm seeing the issue on `merida1` instead of `kjohnson3` as discussed elsewhere.

If I optimise examples by setting don't run on OSX on a few I could probably cut 15-20s, but to me it seems like most of the timing blowout is coming from checks where I don't really have much control. Is either of you able to offer any helpful suggestions as I'm really not sure where else to start cutting my code down?

Thanks in advance

**Comment by lshep** [comment]
Yes merida1 is currently being maxed out at times which slows the process;  if you are hitting the times on the linux nebbiolo1 machine I think we can ignore the warnings.

**Comment by smped** [comment]
Thanks @lshep . I also went & checked my latest [gh-actions run](https://github.com/smped/transmogR/actions/runs/7752972977) and the Linux R CMD check took 4:32 whilst the OSX check took 5:42 and Windows took 4:51. So there's definitely an OSX platform slowdown beyond the BBS but it seems lees profound.

Do I need to make some edits & update the version to trigger a rebuild?

**Comment by LiNk-NY** [comment]
Hi Stevie, @smped 
Thank you for making those changes. 
Please remove the `{}` from `setGeneric` calls as they cause performance issues. 
For reference: https://adv-r.hadley.nz/s4.html?q=setGeneric#s4-generics
Everything else looks good to go. 
Thanks, 
Marcel

**Comment by smped** [comment]
Thanks for the tip Marcel @LiNk-NY ! Don't know how Id missed that, so that's a really good thing to know. Might sneak off to tidy up another package or two. :)

It looks like I'm still over 10min on merida1, but am much closer to the target. It looks like the big changes in timings were in the examples & tests, which tracks with the performance issues Hadley mentions. I could possibly move a couple of tests to longtests if you think that might help? That way I'd still keep the tests in good shape, but might just sneak under that 10min line-in-the-sand

**Comment by LiNk-NY** [comment]
Hi Stevie, @smped 
Thank you for making those changes. 
Your package has been accepted. 
Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/smped.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("transmogR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/transmogR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
