### ISSUE TITLE
findIPs: a new package to detect influential points for feature rankings

### ISSUE THREAD

**Issue by ShuoStat** [Bioconductor/Contributions#3288]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ShuoStat/findIPs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please remove `vignette.html` and `vignette.Rmd` from the `inst` directory.  Vignettes should be built automatically through `R CMD build`.   Please also rename your vignette to something more meaningful (like your package name findIPs.Rmd) as a generic name can cause loading conflicts depending on other packages loaded in a users session.

**Comment by ShuoStat** [comment]
I have made corrections following your instructions in my git repository. Do I need to resubmit a new issue or continue with this issue?

**Comment by lshep** [comment]
You can continue with this issue.  I will look at it shortly

**Comment by lshep** [comment]
The package currently does not interop with any standard Bioconductor classes.  Can an example be added showing this interoperability?

**Comment by ShuoStat** [comment]
Thanks for your constructive comments. I added two examples to show the interoperability with the Bioconductor class (SummarizedExperiment and ExpressionSet classes). In addition, I added some argument checkings, e.g., 'method' in findIPs() and sumRanks(). The revised package wasa re-run with R CMD build, R CMD check, and BiocCheck() in BiocCheck package. Thanks

**Comment by ShuoStat** [comment]
Thanks and please do not hesitate to share me more suggestions to improve the package

**Comment by Kayla-Morrell** [comment]
@ShuoStat - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

- [ ] REQUIRED: Installation instructions in the README file should also include how to install from Bioconductor.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.0.0 to 4.4.0.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an entire package.

## NEWS

- [ ] SUGGESTION: We strongly encourage the use of NEWS files so that changes are included in the Bioconductor release announcement. Be sure your NEWS file actually contains information.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install the package from Bioconductor. This code chunk should include `eval = FASLE`.
- [ ] SUGGESTION: We suggest the use of table of contents.

## R code 

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 14 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 203 lines that are not.

Best,
Kayla

**Comment by ShuoStat** [comment]
Dear Kayla, 

I want to express my gratitude for taking the time to provide your insightful comments and suggestions regarding our package. 
Your input has been invaluable in enhancing its quality. As a result of your feedback, several modifications and corrections 
have been implemented:

**General package development**  
- [x] REQUIRED: Installation instructions in the README file should also include how to install from Bioconductor.  

**DESCRIPTION**  
- [x] REQUIRED: Update R version dependency from 4.0.0 to 4.4.0.  

**NAMESPACE**  
- [x] SUGGESTION: Generally importFrom() is encouraged over importing an entire package.  
*Use more importFrom(), but not all import() is replaced by importFrom()*  

**NEWS**  
- [x] SUGGESTION: We strongly encourage the use of NEWS files so that changes are included in the Bioconductor release announcement. Be sure your NEWS file actually contains information.  

**Vignette**  
- [x] REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install the package from Bioconductor. This code chunk should include eval = FASLE.  
- [x] SUGGESTION: We suggest the use of table of contents.

**R code**  
- [x] SUGGESTION: For formatting reasons, consider shorter lines. There are 14 lines that are > 80 characters long.  
*I tried but cannot to remove these lines, probablity because there line indeed are the chunk options in the Vignette*  
- [x] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 203 lines that are not.
 
*I tried to use the multiples of 4 spaces for line indents, and the number of lines without  4 spaces reduces to 51 lines*  

Furthermore, I've corrected issues with the sumRanks() and plotRankScatters() functions, and updated the corresponding test_that script accordingly.  
Thanks for your work, and do not hesitate to contact me if you have mmore comments. 

Best wishes,
Shuo Wang

**Comment by Kayla-Morrell** [comment]
@ShuoStat - In order to see the changes and produce a build report, please push a valid version bump to the DESCRIPTION file.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@ShuoStat - Thank you for making the necessary changes. I have looked everything over and I have just one requirement before I can accept the package. Please make this change and let me know when you are ready for a re-review.

## NEWS

- [ ] REQUIRED: Thank you for adding a news file. However, it doesn't look formatted properly. Please take a look at our documentation here on how to format.
https://contributions.bioconductor.org/news.html

Best,
Kayla

**Comment by ShuoStat** [comment]
Dear Kayla, 

I have updated the NEWS following your suggestions. The updated version has been pushed to git.bioconductor.org.

**NEWS**
- [x]  REQUIRED: Thank you for adding a news file. However, it doesn't look formatted properly. Please take a look at our documentation here on how to format.
https://contributions.bioconductor.org/news.html

Thanks for all your work and have a nice day.
Kind regard,
Shuo Wang

**Comment by Kayla-Morrell** [comment]
@ShuoStat - Thank you for making the necessary changes. I have reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by ShuoStat** [comment]
Dear Kayla,

I am happy to hear about that. and thanks for your contribution to this package. 

Kind regard
Shuo Wang

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ShuoStat.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("findIPs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/findIPs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
