### ISSUE TITLE
cydar

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#329]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarioniLab/cydar

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
DESCRIPTION

- Good

NAMESPACE

- Consider wrapping long lines to 80 columns

vignette

- consider adding an 'Last modified' date

R

- avoid 'copy-and-append' in favor of 'pre-allocate and fill', see [efficient code][] (also diffIntDistr.R:43 and elsewhere)

        out.cells <- out.index <- list()
        for (i in seq_along(out)) {
            if (is.character(out[[i]])) { stop(out[[i]]) }
            out.cells[[i]] <- out[[i]]$cells
            out.index[[i]] <- out[[i]]$index
        }
        
  becomes 
  
        out.cells <- out.index <- vector("list", length(out))
        ...

  other instances (e.g., expandRadius.R:19) can simply use `lapply()` to avoid the need for allocating and filling a list.k

- consider CapitalCamelCase class naming convention `CyData`

- define and always use (e.g., in validity methods) accessors rather than direct slot access; setter / getter accessors can be plain-old R functions and do not need to be exported if not relevant. Accessors provide minimal separation of interface from implementation.

- The cyData validity method could be written in the style of accumulating text imperfections and returning that, so the user does not need to iterate through individul problems

        txt <- character()
        if ()
            txt <- c(txt, "one problem")
        if ()
            txt <- c(txt, "another problem")
            
        if (length(txt)) txt else TRUE
        
- (interpretSpheres.R: 75) Consider adopting an indentation style with more modest spacing.

- Consider replacing explicit `require(flowStats)` with `loadNamespace("flowStats"); flowStats::warpSet` to avoid altering user namespace and ensuring full symbol resolution.

src

- looks ok, including PROTECT() and error handling.

man

- seems to be comprehensive and complete.

[efficient code]: http://bioconductor.org/developers/how-to/efficient-code/

**Comment by LTLA** [comment]
Thanks Martin. I've implemented most of the suggestions.

> NAMESPACE: Consider wrapping long lines to 80 columns

Done.

> vignette: consider adding an 'Last modified' date

Done.

> R: avoid 'copy-and-append' in favor of 'pre-allocate and fill'

Done in almost all cases. The exception is in `pickBestMarkers` where the list is not of a fixed length.

> R: consider CapitalCamelCase class naming convention

Done.

> R: define and always use (e.g., in validity methods) accessors rather than direct slot access

Done, except in `CyData` subsetting where assignment via setters triggers a `validObject()` check. This fails as the rest of the object has not yet been subsetted.

> The cyData validity method could be written in the style of accumulating text imperfections and returning that

Done.

> Consider adopting an indentation style with more modest spacing.

Done.

> Consider replacing explicit require(flowStats) with loadNamespace("flowStats")

I wish I could. However, something inside `warpSet` breaks the latter approach, as demonstrated with the MWE below.

```{r}
library(flowCore)
data(GvHD)
testFUN <- function(...) { 
    loadNamespace("flowStats")
    flowStats::warpSet(...) 
}
testFUN(GvHD, stains="FL1-H")

## Error in fdPar(wbasis, 1, 1e-04) : could not find function "fd"
```

**Comment by mtmorgan** [comment]
Thanks I've marked the package as accepted and will add it to svn and nightly builds. More information in a day or so via email.
