### ISSUE TITLE
muleaData ExperimentHubData Bioconductor package

### ISSUE THREAD

**Issue by barizona** [Bioconductor/Contributions#3291]
Dear BioC Team,

Here we provide the `muleaData` ExperimentHubData Bioconductor package for the `mulea` (ELTEbioinformatics/mulea on github) R package. `mulea` is a comprehensive overrepresentation and functional enrichment analyser R package which reads ontologies (gene and protein sets) in a standardised GMT (Gene Matrix Transposed) format. We provide these GMT files for 27 different model organisms, ranging from _Escherichia coli_ to human, all acquired from publicly available data sources. The GMT files are provided with multiple gene and protein identifiers such as UniProt protein IDs, Entrez, Gene Symbol, and Ensembl gene IDs. The GMT files and the scripts we applied to create them are available at the _GMT_files_for_mulea_ (ELTEbioinformatics/GMT_files_for_mulea on github) repository. For the `muleaData` we read these GMT files with the `mulea::read_gmt()` function and saved it to .rds files with the standard R `saveRDS()` function.
I've got the SAS token from Lori Shepard and uploaded the .rds files to the Azure Data Lake. She wrote that the data is now added:
```
> query(eh, "muleaData")
ExperimentHub with 879 records
# snapshotDate(): 2024-02-07
# $dataprovider: muleaData
# $species: Drosophila melanogaster, Homo sapiens, Mus musculus, Caenorhabdi...
# $rdataclass: data.frame
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH8571"]]' 

           title                                                              
  EH8571 | Genomic_location_Ensembl_Arabidopsis_thaliana_10genes_EnsemblID.rds
  EH8572 | Genomic_location_Ensembl_Arabidopsis_thaliana_10genes_EntrezID.rds 
  EH8573 | Genomic_location_Ensembl_Arabidopsis_thaliana_10genes_GeneSymbol...
  EH8574 | Genomic_location_Ensembl_Arabidopsis_thaliana_10genes_UniprotID.rds
  EH8575 | Genomic_location_Ensembl_Arabidopsis_thaliana_20genes_EnsemblID.rds
  ...      ...                                                                
  EH9445 | Genomic_location_Ensembl_Zea_mays_5genes_UniprotID.rds             
  EH9446 | Protein_domain_PFAM_Zea_mays_EnsemblID.rds                         
  EH9447 | Protein_domain_PFAM_Zea_mays_EntrezID.rds                          
  EH9448 | Protein_domain_PFAM_Zea_mays_GeneSymbol.rds                        
  EH9449 | Protein_domain_PFAM_Zea_mays_UniprotID.rds         
```          

Best wishes,
Eszter Ari

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ELTEbioinformatics/muleaData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
An in-depth review will occur once the package builds without ERROR. please let me know if you have any questions or concerns.

**Comment by barizona** [comment]
Dear @lshep and @bioc-issue-bot,
@stitam has fixed the issue and I pushed the new version to git@git.bioconductor.org:packages/muleaData.
These changes were made:

1. There was a man file for muleaData() but no function with that name so the man file was deleted.
2. LICENCE.md is unnecessary and may be confusing. Licence is already set in the DESCRIPTION file. So the LICENCE.md was deleted.
3. Started tracking .Rbuildignore by git and added README.Rmd since the .Rmd version should not be part of the build.
4. I made a minor change in the README

I used the following git commands:
```
git remote add upstream git@git.bioconductor.org:packages/muleaData.git
git fetch --all
git checkout main
git merge origin/main
git checkout devel
git merge main
git push upstream devel
git checkout main
```

Sincerely,
Eszter

**Comment by barizona** [comment]
Dear @lshep and @bioc-issue-bot,

I have added a **NEWS** file and an empty **test/testmake-data.R** file, and change the spaces in the vignette to let `BiocCheck::BiocCheck('new-package'=TRUE)` run without other NOTES than the

> * Checking for bioc-devel mailing list subscription...
    * NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires
      admin credentials). Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

I rebuilt the package and pushed the changes to git@git.bioconductor.org:packages/muleaData.git.

Best,
Eszter

**Comment by lshep** [comment]
**test**

- [ ] Please write actual tests or remove. Do not keep an empty directory
  around.  Tests can ensure data is being downloaded or formatted correctly.

**man**

- [ ] Please include a package level man page so that a naive users will have
  something displayed if they try `?muleaData`

**vignette**

- [ ] The code in your vignette is wrong and I have already expressed this
  twice. Please show and execute ExperimentHub calls for retrieving data. Vignettes must have executed code.

- [ ] Please also include an abstract/intro that details why this package is
  being submitted to Bioconductor and what the data contains (similar to your
  README).

**general**

- [ ] Is this data meant to be used with an existing Bioconductor package? Or
  will this be accompanied by a package that utilizes this data?

**Comment by barizona** [comment]
Dear @lshep ,

Thank you for showing these problems.
I solved all:

**test**

- [x]  Please write actual tests or remove. Do not keep an empty directory around. Tests can ensure data is being downloaded or formatted correctly.

_I have removed the test directory with the empty file._

**man**

- [x]  Please include a package level man page so that a naive users will have something displayed if they try ?muleaData
vignette.

_I have added R/muleaData.R that converted to man/muleaData.Rmd and now the ?muleaData works fine._

**vignette**

- [x] The code in your vignette is wrong and I have already expressed this
twice. Please show and execute ExperimentHub calls for retrieving data. Vignettes must have executed code.

- [x] Please also include an abstract/intro that details why this package is
being submitted to Bioconductor and what the data contains (similar to your
README).

_I have added mueaData.Rmd to the vignette folder that contains executed code and an abstract (the same as in the README)._

**general**

- [x] Is this data meant to be used with an existing Bioconductor package? Or
will this be accompanied by a package that utilizes this data?

We will submit the referred `mulea` package to Bioconductor within a week. So it is an existing package but not submitted to bioconductor yet.

Best,
Eszter

**Comment by lshep** [comment]
Thank you.  One last comment.  Please remove the hard coded version in the BiocManager call.  It will work with 3.19 and any future but that will change an installation for a user to use strictly 3.19 and never a future more updated version and ask them to downgrade a current version to the lower version.   You should assume the user is on a correct version of Bioc/R to run your code and simply use 
```
{r 'install', eval=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ExperimentHub")
BiocManager::install("muleaData")
```

**Comment by barizona** [comment]
Dear @lshep ,
Thank you for the suggestion. I have changed it in the README and the vignette.
Best,
Eszter

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/barizona.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("muleaData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/muleaData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
