### ISSUE TITLE
SVAPLSseq: An R package to adjust for the hidden factors of variability in  differential gene expression studies based on RNAseq data.

### ISSUE THREAD

**Issue by sutigit21** [Bioconductor/Contributions#33]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sutigit21/SVAPLSseq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by sutigit21** [comment]
I am submitting a new version of the R package in a new issue.

**Comment by sutigit21** [comment]
I have fixed the error.

**Comment by sutigit21** [comment]
Do I need to modify the package ?

**Comment by lshep** [comment]
I will review the package and comment with any suggestions or concerns if applicable soon.

**Comment by sutigit21** [comment]
Ok.

**Comment by lshep** [comment]
Thank you for you effort and interest in Bioconductor. Please see the following comments and respond or correct accordingly: 

GENERAL:
It seems like your package relies heavily and is building upon limma and edgeR. Please add more detail to the 'Overview' section of the vignette explaining where the methods in the package came from and what your original contributions are. What is coming from limma and edgeR and what are your new improvement or adaptations. 


INPUT/OUTPUT: 
In generaly Bioconductor prefers S4 convention rather than S3 and we try to encourage compatiblity with other Bioconductor standard objects. 

The 'dat' argument of both functions should be able to work with Bioconductor objects particularly the S4 classes that work with limma and edgeR since you are importing and building upon them.  May we suggest the SummarizedExperiment and/or edgeR::DGEList classes.  

The output of the functions we would prefer to be in S4. 
It looks like you wanted to use the S3 methods plot() and summary() on
the outputs of your functions. We suggest 1 of 2 options. 

i) Make svpls.test and svpls.surr S4 classes (choose better names since
'.' indicates S3 dispatch). Create S3/S4 combo methods for

plot.svplsTest
plot.svplsSurr
summary.svplsTest
summary.svplsSurr

An example of creating S3/S4 combos are in GenomicAlignments NAMESPACE.

~/proj/bioCpackages/Rpacks/GenomicAlignments/R >grep combo *
OverlapEncodings-class.R:### S3/S4 combo for levels.OverlapEncodings
OverlapEncodings-class.R:### S3/S4 combo for as.data.frame.OverlapEncodings


ii) Make the output a list, which it already is, and give the plot and
summary new names such as plotSVPLS() and summarySVPLS().



FUNCTIONS:
The names svapl.surr() and svapl.test() use the dot '.' which represents
S3 dispatch. These are not S3 methods and should be renamed with
underscores or camelCase.


DESCRIPTION:  
add BiocStyle to suggests
it appears the description has erroneous spaces and indentations. please correct

NAMESPACE: 
Don't need to import both doParallel and parallel - doParallel depends
on parallel and builds upon that infrastructure.
The proper way to use doParallel is with the foreach package, e.g.,
cl <- makePSOCKcluster(2)
registerDoParallel(cl)
m <- matrix(rnorm(9), 3, 3)
foreach(i=1:nrow(m), .combine=rbind)
stopCluster(cl)
The code has calls to parallel::mclapply(). Why? This is not necessary
when using doParallel.

You could also consider BiocParallel as an alternative to doParallel/foreach

INST/DOC: 
this documentation is the same as the vignettes. plesae remove

VIGNETTE: 
change verbatim to code chunks to be evaluated.  The code in the vignette should be run and checked. The vignette code chunks should be a runnable example. 
In the example there is a section referring to surr$sv but there is none.  It looks like it was renamed to surr (surr$surr) and was never updated
It would help to include a real data example utilizing data from Bioconductor's experimental data.  

MAN: 
SVAPLSseq-package.Rd: 
remove static information (version, date) these are in the description and will be outdated with any changes to the package. This information is already kept and updated automatically in the DESCRIPTION file 
At the end of the details, you point to the two functions of the package \code{svpls.surr}, \code{svpls.test} Please link to these functions \code{\link{ }}

In both of the function man pages, for the \value{}  you describe the sublevels of the returned object but not what the object itself is.  If it is a list with those sublevels that should be stated. 

Thank you 
Lori

**Comment by sutigit21** [comment]
I have modified the R package SVAPLSseq by considering all the comments.

**Comment by sutigit21** [comment]
I have modified the package as suggested in the previous evaluation. Please let me know if I need to do anything else.

**Comment by lshep** [comment]
Thank you for your changes. Everything is looking great.  A few other comments to address: 

R CODE: 
svplsSurr and svplsTest should be able to take in a Bioconductor object as input as 'dat' . May we suggest SummarizedExperiment and/or edgeR::DGEList.   This can be a simple changes, as easy as checking the 'dat' class and if it is one of those classes, assigning 'dat' to the appropriate matrix from those objects. 

svplsSurr and svplsTest: At the end of the code where you make the new object, it is cleaner and more efficient to assign the slots when creating the object (ie.  `new("svplsSurr", surr = surr, prop.vars = prop.vars)` )rather than directly accessing slots.  

Suggested for future but not a requirement for acceptance:  The getter/setter methods for the slots of the object are great to have. The nomenclature you currently use with the "." can be confusing as the "." normally indicates S3 object disbatch.  In the future consider changing to camel case. 

 VIGNETTE: 
In sections 3 and 4, still reference old functions svlps.surr and svpls.test.  Please update with new names. 
Please add an example using a Bioconductor object / data.  Suggestions include showing how your package works with a SummarizedExperiment or the edgeR::DGEList

MAN: 
SVAPLSseq-package.Rd
At the end of the description the \code{\link{svplsSurr}}, \code{\link{svplsTest}}  should be moved to a \seealso section 

svplsSurr.Rd / svplsTest.Rd
The current information that is in the \value{}  section should be moved into the details of the class (svplsSurr-class.Rd \ svplsTest-class.Rd ) and the value section should reference (or link to) an object of those classes. 

Looking good. With these minor changes it is just about ready for acceptance.  
Lori

**Comment by sutigit21** [comment]
I have modified the package as suggested. Please let me know if I need to do anything else.

**Comment by lshep** [comment]
Thank you for making these changes. The package looks okay now and I will recommend be accepted. You should get svn instructions via email in the next couple of days.

**Comment by sutigit21** [comment]
Ok. Thanks

**Comment by sutigit21** [comment]
I haven't received any email yet.

**Comment by sutigit21** [comment]
No email yet..
