### ISSUE TITLE
BREW3R.r

### ISSUE THREAD

**Issue by lldelisle** [Bioconductor/Contributions#3313]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lldelisle/BREW3R.r

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi @lldelisle 

Thank you for your submission. Please see the review below. 

Best regards,
Marcel

--- 

# BREW3R.r

* Overall, the package looks good. It looks like the range operations
rely heavily on the `tidyverse` which is not really designed for that in
mind. Consider using methods in `GenomicRanges` that may help
the code be more robust.

## DESCRIPTION

* Looks good.

## NAMESPACE

* Minor: Consider using the native pipe over `dplyr::'%>%'`.

## vignettes

* Keep the text at a max 80 character width. IMO, it is easier to review and
maintain.
* Avoid mentioning `devtools` in the vignette. Simply use `BiocManager` with
a `username/repo` character input.
* Consider adding `mustWork = TRUE` argument to `system.file` calls
* Consider providing a `verbose = FALSE` default to the `extend_granges`
function. Prioritize informative text and remove text e.g., "Extend last
exons.", "Extending them.", etc.
* Load `GenomicRanges` in the vignette and avoid using `GenomicRanges::`
qualifiers.
* Use `runValue` on the `Rle` to extract the character strand value,
e.g.,  `runValue(strand(gene_after[1]))` and add one to the output i.e.,
`(x == "+") + 1` instead of using `if ... else` (seen in plotting chunks).

## R

* Consider using `@importFrom GenomicRanges ...` to import functions such as
`strand`, `start()<-`, etc.
* Consider reducing the cyclomatic complexity of the `extend_granges` function
currently it is at a value of 16: `cyclocomp::cyclocomp(extend_granges)`
* Have you considered using `intra-range` methods from `GenomicRanges`, e.g.,
`flank`, `resize`, `shift` etc. It seems like those could be useful and robust
operations.

## tests

Coverage looks good:

```r
covr::package_coverage()
BREW3R.r Coverage: 89.71%
R/extend_granges.R: 76.29%
R/helpers.R: 92.23%
```

**Comment by lldelisle** [comment]
Thank you very much for your review. I have started to adress your points in https://github.com/lldelisle/BREW3R.r/pull/1

- For the verbose, I decided to include 3 levels of verbose with default set to 1 with only stats. The problem is that with large gtf the function can be very long, it can be useful to have messages that indicates the progression.
- The cyclomatic complexity seems to be directly linked to the optional messages that display progression. I would prefer to keep these, is it ok for you?

I am trying to strongly reduce the usage of tidyverse in favor of resize etc... but this needs a lot of rethinking.

**Comment by LiNk-NY** [comment]
Hi Lucille, @lldelisle 

Please consider this resource for working with verbosity: https://ropensci.org/blog/2024/02/06/verbosity-control-packages/
Usually, a package-wide option (along with a wrapper function provided by e.g., `rlang`, `cli`, `futile.logger`, etc.) is preferred and as a side-effect, it will cut down on the number of conditional statements. 

-Marcel

**Comment by lldelisle** [comment]
Hi @LiNk-NY ,
Thank you very much for the tip. I have included this, see https://github.com/lldelisle/BREW3R.r/pull/1/commits/661e9bc002fcd6abf5b3e4cdf08e4b3b47a5d425
So I converted my verbose = 1 to rlang::inform, my verbose = 2 to a new function progression_msg and debug to debug_msg. But this did not decreased the cyclomatic complexity as my function progression_msg has a conditional statement inside...

Except from that my PR contains a new version which do not use dplyr anymore. Do you want to review my PR or should I merge it and then you review?

**Comment by LiNk-NY** [comment]
> But this did not decreased the cyclomatic complexity as my function progression_msg has a conditional statement inside...

Hi Lucille, @lldelisle 
Thank you for making those changes. The improvement can be seen via: 

```r
> cyclocomp::cyclocomp(expr=BREW3R.r::extend_granges)
[1] 4
```

It looks good!

Please merge first and I can follow up with the review. 

-Marcel

**Comment by lldelisle** [comment]
I have merged.

**Comment by LiNk-NY** [comment]
Hi Lucille, @lldelisle 
Have you pushed your changes to `git.bioconductor.org`? 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Please make sure that the global variables are accounted for. See the `NOTE`: 

```r
* checking R code for possible problems ... NOTE
add_new_exons: no visible binding for global variable ‘transcript_id’
add_new_exons: no visible binding for global variable ‘start’
add_new_exons: no visible binding for global variable
  ‘three_prime_query’
add_new_exons: no visible binding for global variable ‘end’
add_new_exons: no visible binding for global variable ‘exon_number’
adjust_for_collision: no visible binding for global variable
  ‘old_width’
adjust_for_collision: no visible binding for global variable ‘width’
extend_granges: no visible binding for global variable ‘type’
extend_granges: no visible binding for global variable ‘id’
extend_using_overlap: no visible binding for global variable ‘type’
extract_last_exon: no visible binding for global variable ‘type’
filter_new_exons: no visible binding for global variable
  ‘collision_base’
filter_new_exons: no visible binding for global variable ‘start’
filter_new_exons: no visible binding for global variable ‘end’
overlap_different_genes: no visible binding for global variable
  ‘query_gene_id’
overlap_different_genes: no visible binding for global variable
  ‘subject_gene_id’
Undefined global functions or variables:
  collision_base end exon_number id old_width query_gene_id start
  subject_gene_id three_prime_query transcript_id type width
Consider adding
  importFrom("stats", "end", "start")
```

You can use `with()` inside of a `subset` function to avoid the `NOTE` e.g., 

```r
subset(mtcars, with(mtcars, mpg > 20))
```

* There are some typos in the argument names. See `groupping_variable` in the ~extend_last_exon~ `extract_last_exon` function.

All else looks good. Please bump the version and push to `git.bioconductor.org` for another build and check. 
Thanks,
-Marcel

**Comment by lldelisle** [comment]
Indeed they are all within a subset...
Thanks for the typo, I will fix them tomorrow. groupping should be grouping, right? And extend last exon? should be exons?

**Comment by LiNk-NY** [comment]
> groupping should be grouping, right? 

Yes

> And extend last exon? should be exons?

Sorry, I meant to type `extract_last_exon` as the name of the function where `groupping_variable` is an argument. 
But it does seem like the function should also be plural as the documentation title suggests.

**Comment by lldelisle** [comment]
Hi @LiNk-NY ,
I fixed the 2 typos and used `with` in the `subset` to avoid the NOTE about the undefined variables.
Are you happy with my changes. Or do I need to change something else?
Thanks

**Comment by LiNk-NY** [comment]
Hi @lldelisle ,
Thank you for making those changes. The package has been accepted. 
Best regards,
Marcel

**Comment by lldelisle** [comment]
Thanks

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lldelisle.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BREW3R.r")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BREW3R.r

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
