### ISSUE TITLE
BioGA

### ISSUE THREAD

**Issue by danymukesha** [Bioconductor/Contributions#3315]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/danymukesha/BioGA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Could you please provide an abstract/intro section in your vignette that provides motivation for inclusion in Bioconductor and show interoperability with a [common Bioconductor class](http://contributions.bioconductor.org/important-bioconductor-package-development-features.html#reusebioc)

**Comment by danymukesha** [comment]
I made the changes asked above. Could you review the updates please?

**Comment by lshep** [comment]
Please add any needed dependency to the DESCRIPTION of your package in Suggest field.

**Comment by danymukesha** [comment]
I pushed the modifications. Could you please check if everything is alright?

**Comment by lshep** [comment]
Please see previous post  https://github.com/Bioconductor/Contributions/issues/3315#issuecomment-2012229816   You will need to push your changes to git.bioconductor.org to trigger a new build

**Comment by danymukesha** [comment]
I already committed the modification to bioconductor

**Comment by lshep** [comment]
You need to do a version bump so that a new build is triggered.

**Comment by jianhong** [comment]
Could you please fix the error first? Thank you.

**Comment by danymukesha** [comment]
> Could you please fix the error first? Thank you.

@jianhong , I fixed the error

**Comment by jianhong** [comment]
# Package 'BioGA' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The DESCRIPTION file
- [ ] Important: `Depends` field is not found in DESCRIPTION.
- [ ] Important: R version is not clear in DESCRIPTION.
- [ ] Important: If you are not using the namespace in the R code, please move `biocViews` and `sessioninfo` into `Suggests`
## The NAMESPACE file
- [ ] Important: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 12 import(SummarizedExperiment)
	* in line 13 import(animation)
	* in line 14 import(biocViews)
	* in line 15 import(ggplot2)
	* in line 16 import(graphics)
	* in line 18 import(sessioninfo)
## General package development
- [ ] Important: Consider adding more unit tests. Current unit tests only covered 10.435% (less than 30%).
## Documentation
- [ ] Note: Vignette should use `BiocStyle` package for formatting.
	* rmd file vignettes/Introduction.Rmd
	* rmd file vignettes/Overview.Rmd
	* rmd file vignettes/Usage.Rmd
- [ ] Important: Vignette should have an *Introduction* section..
	* rmd file vignettes/Overview.Rmd
	* rmd file vignettes/Usage.Rmd
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/Introduction.Rmd
	* rmd file vignettes/Overview.Rmd
	* rmd file vignettes/Usage.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/Introduction.Rmd
	* rmd file vignettes/Overview.Rmd
	* rmd file vignettes/Usage.Rmd
## C and Fortran code
- [ ] NOTE: `Makevars` and `Makefile` not within a package when CPP version is lower than 0.11.0 or not restricted.
- [ ] Important: Using [R's internal random number generator](https://cran.r-project.org/doc/manuals/R-exts.html#Random-numbers) instead of std::rand
    * file src/crossover.cpp
            - line 30:    int parent1_index = rand() % num_parents;
            - line 31:    int parent2_index = rand() % num_parents;
    * file src/initialize_population.cpp
            - line 1:#include <cstdlib> // Include the header for rand() function
            - line 30:       int sample_index = std::rand() % num_samples;
    * file src/replacement.cpp
            - line 34:    int index_to_replace = rand() % population_size;
- [ ] Note: If you are modifying code from somewhere, the original license should also be included.

**Comment by jianhong** [comment]
Just wanted to check in to see if we may expect any updates soon? Otherwise, I will close this issue.

**Comment by danymukesha** [comment]
I will be workin the issue this week. Thank you for reminding!

**Comment by danymukesha** [comment]
@jianhong I pushed the updates to fix the issues you mentioned. 

Could you please check if everything is alright?

**Comment by jianhong** [comment]
Sure I will do that soon.Best!Your sincerely,Jianhong OuOn May 28, 2024, at 12:40 PM, Dany Mukesha ***@***.***> wrote:﻿
@jianhong I pushed the updates to fix the issues you mentioned.
Could you please check if everything is alright?

**Comment by jianhong** [comment]
Almost there. 

## The DESCRIPTION file
- [ ] Important: R version should be no less than 4.4
## Documentation
- [ ] Note: Will it be better to add the authors and date in the vignettes?

**Comment by danymukesha** [comment]
> Almost there. 
> 
> ## The DESCRIPTION file
> - [ ] Important: R version should be no less than 4.4
> ## Documentation
> - [ ] Note: Will it be better to add the authors and date in the vignettes?
> 

@jianhong thank you for the review.

I just did the modifications you asked. 
Could you please check if everything is alright?

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/danymukesha.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BioGA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BioGA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
