### ISSUE TITLE
bettr

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/Contributions#3321]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/federicomarini/bettr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by csoneson** [comment]
cc @federicomarini

**Comment by lazappi** [comment]
Hi @csoneson

Thanks for submitting **bettr** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

I only have some minor comments:

- [ ] Please add Bioconductor installation instructions to the `README` and vignette
- [ ] The vignette should have an *Introduction* section that includes motivation for inclusion in Bioconductor and comparison to any similar tools
- [ ] It might be useful to show some of the preparation of the clustering data in the vignette. There is a small toy example of this but I'm not sure how helpful that will be for users to prepare real input.
- [ ] Similar for the OECD example. I don't think people will be able to find the script without an actual link to it. Maybe you could make this into a second vignette or a live examples somewhere?
- [ ] Please double check the [Shiny guidelines](https://contributions.bioconductor.org/shiny.html). I think you are already following these but just in case (maybe the organisation part?).

**Comment by csoneson** [comment]
@lazappi Thanks a lot for your review! Below are our responses. You can also see all the changes in [this PR](https://github.com/federicomarini/bettr/pull/22).

> * [x]  Please add Bioconductor installation instructions to the `README` and vignette

Done.

> * [x]  The vignette should have an _Introduction_ section that includes motivation for inclusion in Bioconductor and comparison to any similar tools

We expanded the Introduction section to address this.

> * [x]  It might be useful to show some of the preparation of the clustering data in the vignette. There is a small toy example of this but I'm not sure how helpful that will be for users to prepare real input.

We adapted this section of the vignette to start from a single csv file with metric information (which is probably the most likely starting point for users).

> * [x]  Similar for the OECD example. I don't think people will be able to find the script without an actual link to it. Maybe you could make this into a second vignette or a live examples somewhere?

We added a link to the script on GitHub to the vignette section. The reason we didn't explicitly include the data in the package is that we were a bit uncertain of whether we were able to redistribute it in this form (but we somehow still wanted to mention it since their interface was the main inspiration for `bettr`). 

> * [x]  Please double check the [Shiny guidelines](https://contributions.bioconductor.org/shiny.html). I think you are already following these but just in case (maybe the organisation part?).

We double-checked and believe we are following the relevant guidelines. All code is included in exported functions that can also be run (and are tested) outside the Shiny app. On the side, we are experimenting a bit with `shinytest2`, which works ok locally but somehow doesn't seem to translate well when we push to other platforms (e.g., GitHub Actions) 🤔 Thus, we haven't yet integrated it into the package.

**Comment by lazappi** [comment]
Thanks for the quick changes. Looks good to me, I will accept the package.

**Comment by lazappi** [comment]
Congratulations on getting **{bettr}** into Bioconductor 🎉! It can take a couple of days to be picked up by the build system but then the package should be available as part of Bioconductor devel and the next release.

**Comment by jwokaty** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/csoneson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bettr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bettr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
