### ISSUE TITLE
simPIC

### ISSUE THREAD

**Issue by sagrikachugh** [Bioconductor/Contributions#3323]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sagrikachugh/simPIC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Note: In your vignette you use `counts <- readRDS("../inst/extdata/test.rds")`; you should not hard code a path to the file and instead use what you did inside your examples `counts <- readRDS(system.file("extdata","test.rds", package = "simPIC"))` .

**Comment by HelenaLC** [comment]
Thanks for submitting your package to Bioc, it's in fantastic shape already! A few minor points (mostly suggestions/optional improvements); please report back with what's been addressed and how, or any questions you might have.

# misc

- [ ] in the DESCRIPTION, please add R version dependency 4.4.0 (see `BiocCheck` NOTE in the build report)

- [ ] since the core functionality of the package is simulation, you might want to consider moving `ggplot2` (or any other plotting-related dependency) to `Suggests:` (see [here](https://contributions.bioconductor.org/description.html?q=sug#depends-imports-suggests-enhances) for details); this could make the package more robust/light-weight to install

# code

- [ ] looks like all code is indented by one tab/4 spaces; is this intentional? It's a little annoying as it shifts all code to the write/out of screen when viewing with an 80-character line limit

- [ ] consider having a look at Bioc's [coding style guidelines](https://contributions.bioconductor.org/r-code.html?q=style#coding-style) and implementing these; e.g., no space about argument `=`s, tab/4-space indentation rather vertical code alignment

- [ ] might be an edge-case, but just to point out that matrix-subsetting should be done using `x[i, j, drop=FALSE]` (e.g., line 68 in `simPICestimate.R`); else, subsetting a single row/column will return a vector causing downstream code that expects a matrix to fail; this is generally a good habit to build

- [ ] repeated `if (verbose) message(...)` statements could be combined into a single one in a few places

- [ ] `if (x == "a") ... else if (x == "b")` kind of statements can be nicely written using `switch()`, e.g., in `simPICsimulate.R`:

```
switch(pm.distr, 
    gamma={ 
        ...
    },
    weibull={
        ...
    })
```

- [ ] also, if an argument should match a specific value from a set of choices, you should list valid choices in the function definition and validate the argument inside the function using `match.arg`; e.g.

```
simPICsimulatePeakMean <- \(..., 
    pm.distr=c("gamma", "weibull", ...)) {
    pm.distr <- match.arg(pm.distr)
    ...
}
```

# docs

- [ ] we encourages having a package man page with an overview of the package and links to the main functions; users should be able to have a relevant page display with `?simPIC`

- [ ] please provide provenance and data structure information for any example data used in the package; for now, that's `inst/extdata/test.rds` only; (see [here](https://contributions.bioconductor.org/docs.html?q=data#data-man) for details)

- [ ] in the vignette, there're some inconsistencies in the use of code-style vs. plain text (e.g., "simPICcount object"); also, you might consider hyperlinking external packages (maybe the first time they're mentioned) using `BiocStyle` (e.g., \`r BiocStyle::Biocpkg("SingleCellExperiment")\`)

- [ ] `simPICcount.R` lists some pretty specific default parameters; please document where these are coming from (e.g., source information, supplementary code in `inst/script` if there's some data processing involved, or whatever is appropriate)

**Comment by sagrikachugh** [comment]
@HelenaLC @lshep Thank you for reviewing my package. I have addressed all the comments/suggestions but I am stuck with a new error from BiocCheck::BiocCheckGitClone(".") that says system file simPIC.Rproj found. I have tried multiple times and  have this in my .gitignore and it should not be tracked. Here are the contents of my .gitignore file -

simPIC.Rproj
.Rproj.user
.Rhistory
.RData
.Ruserdata
/doc/
/Meta/

Could you please advice me how to avoid this error?

**Comment by sagrikachugh** [comment]
Hi Bioconductor team,

I am having issues with BiocCheck::BiocCheckGitClone() that says system
file simPIC.Rproj found. I have this file in my .gitignore so it should not
be tracked. Despite multiple attempts the error still persists.

Could you please advice me how to fix this?

Here is my .gitignore file

simPIC.Rproj
.Rproj.user
.Rhistory
.RData
.Ruserdata
/doc/
/Meta/


Thanks,
Sagrika

**Comment by sagrikachugh** [comment]
@HelenaLC Thank you for taking the time to review my package. I have addressed all your comments/suggestions. Also, I was able to solve my recent .gitignore issue that I raised earlier. Here is a detail of all the addressed suggestions-

# misc

- [ ] R version dependency has been updated to 4.4.0
- [ ] ggplot2 dependency has been moved to Suggests:

# code

- [ ]  Indentation has been fixed using styler::tidyverse_style (tab/4space indentation)
- [ ] repeated `if (verbose) message(...)` statements have been combined
- [ ] `switch` has been used instead of if/else statements in `simPICsimulate.R` and `simPICestimate.R`

# docs

- [ ] package man page with links to all main functions has been added 
- [ ] provenance and data structure for test data has been provided in `inst/script`. Supplementary code `inst/script/testdata.R` has been added to demonstrate how the test data was generate and `inst/script/testdata.txt` provides all the necessary information for creating test data
- [ ] Vignette inconsistencies have been fixed and external packages are now hyperlinked

@lshep I have addressed your suggestion and updated `counts <- readRDS(system.file("extdata","test.rds", package = "simPIC")) ` in the vignette. Also, I was able to resolve my earlier issue with .gitignore


Thanks,
Sagrika

**Comment by HelenaLC** [comment]
Thanks for this; I think most comments have been sufficiently addressed. Couple comments outstanding...
- [ ] `simPICcount.R` lists some pretty specific default parameters; please document where these are coming from [...] (see above) ... if they are estimated from a specific dataset (maybe what's in `inst`?), please say so in the `simPICcount` documentation
- [ ] I think moving `ggplot2` to `Suggests:` makes a lot of sense here; however, you should check that it's available in the relevant function(s) following [these instructions](https://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances) 
- [ ] I'd suggest adding `drop=FALSE` at `simPICestimate.R` line 67 and any other time a matrix is being subsetted (see comment above)
- [ ] Remember to track changes in the NEWS file; package is at v0.99.4 as opposed to v0.99.1 in the NEWS file (especially for release, where latest changes these will be put on the website)

Also, please try and address any NOTEs in the build report above, e.g.
- In the DESCRIPTION, provide `URL:` and `BugReports:` fields pointing to https://github.com/sagrikachugh/simPIC and .../issues, respectively
- avoid `sapply` and use `vapply` instead; avoid `1:n` and use `seq_len/along` instead (`simPICestimate.R` line 238+; see [here](https://contributions.bioconductor.org/r-code.html?q=sapply#code-syntax-and-efficiency) for details)
- code style still doesn't align with [Bioc guidelines](https://contributions.bioconductor.org/r-code.html?q=style#coding-style); but this is really optional and I am leaving it to you if you really prefer using a linter...

**Comment by sagrikachugh** [comment]
@HelenaLC Thanks for the additional comments. I have now addressed them as follows

- [ ] `simPICcount.R` documentation has been updated providing information on the default parameters and how to generate them.  _The default parameters are based on PBMC10k dataset and can be reproduced using test data and script provided in inst/script_
- [ ]  I have added `drop= FALSE` to  line65 in `simPICestimate.R` where the matrix is being subsetted.
- [ ] `NEWS.md` has been updated to reflect latest updates. 
- [ ] `DESCRIPTION` now includes `URL:` and `BugReports:` fields
- [ ] `1:nCells` has been updated to `seq_len(nCells)` in `simPICsimulate.R`. `simPICestimate.R` doesn't have `1:nCells`
- [ ] I have kept `sapply` as the output from `simPICsimulateTrueCounts` function is consistent across iterations and doesn't require explicit control.
- [ ] The NOTE: Consider shorter lines; 2 lines (0%) are > 80 characters long is related to two URLs in vignette, hence I cannot reduce the character limit

**Comment by HelenaLC** [comment]
Thanks for this. Just to say that "the output from [...] is consistent across iterations" is exactly what `vapply` is made for; see `?vapply`: "`vapply` is similar to `sapply`, but has a pre-specified type of return value, so it can be safer (and sometimes faster) to use." Here, the output should *always* be an integer vector of length `nPeaks`, so you'd use `vapply(seq_len(nCells), sim_true_counts, integer(nPeaks))`. I'd recommend getting in the habit of using `lapply` when outputs are *not* consistent, and `vapply` when they are! I'll accept once that NOTE is cleared as I feel it is very simple to resolve (and in our experience doesn't happen usually after acceptance...)

**Comment by sagrikachugh** [comment]
@HelenaLC Thanks, I have updated `simPICsimulateTrueCounts` function of `simPICsimulate.R` to use `vapply`.

**Comment by jwokaty** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sagrikachugh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("simPIC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/simPIC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
