### ISSUE TITLE
tidytof

### ISSUE THREAD

**Issue by keyes-timothy** [Bioconductor/Contributions#3331]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/keyes-timothy/tidytof

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by keyes-timothy** [comment]
(This is my first submission to Bioconductor - thank you for your help and patience in the review process! I'm sure I will learn a lot through this first experience.)

**Comment by hpages** [comment]
Thanks @keyes-timothy for this submission.

Given the amount of vignettes (11 in total), it's gonna be a challenge for a newcomer like me to navigate them:

![image](https://github.com/Bioconductor/Contributions/assets/8810451/50319912-7f1f-47f6-8b6d-eac1692a9014)

There's a "Getting started with tidytof" vignette, so I suppose that users will be able to figure out where to start but then it's not clear where to go after that. Can the other vignettes be read in any order or is there an order that you recommend?

It would be nice if the introduction vignette could be made more prominent, maybe by using uppercase in the title (e.g. "GETTING STARTED with tidytof"), and if the introduction vignette had a "where to go next" section -- or something like that -- that lists the other vignettes in the recommended order of reading and provides a short description for each of them.

Also what does `tof` stand for? It's part of the package name and is the prefix of a bunch of function names defined in the package, but I can't figure out where it's comming from. I'm curious why you didn't choose **tidycyto** for the package name since it would have made the package's relationship with cytometry immediately obvious. Anyways would be nice to explain the `tof` acronym in the introduction vignette.

Thanks,
H.

**Comment by keyes-timothy** [comment]
Hi @hpages, 

Thanks for your comments, and for your patience waiting on my responses. I've just pushed some changes to incorporate your feedback, and I've replied to your comments with specific in-line responses below. Please let me know if you have any other thoughts, concerns, or suggestions! 

Timothy

> Thanks @keyes-timothy for this submission.
> 
> Given the amount of vignettes (11 in total), it's gonna be a challenge for a newcomer like me to navigate them:
> 
> ![image](https://private-user-images.githubusercontent.com/8810451/317075874-50319912-7f1f-47f6-8b6d-eac1692a9014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDg0NTksIm5iZiI6MTcxNTA0ODE1OSwicGF0aCI6Ii84ODEwNDUxLzMxNzA3NTg3NC01MDMxOTkxMi03ZjFmLTQ3ZjYtOGI2ZC1lYWMxNjkyYTkwMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDIxNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIxY2QwZWJiMTU2NGM3NDc1ZjEzNmExYjJkMWYyMTgwNjJjZTRmYWM2ZDhkNGIxZjVmMmNiOWI1OTk5ODkzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._TDsr1nxwSnuNXTaLtEbbrQJUrD_VoM4DHSQClsVc8s)
> 
> There's a "Getting started with tidytof" vignette, so I suppose that users will be able to figure out where to start but then it's not clear where to go after that. Can the other vignettes be read in any order or is there an order that you recommend?
> 
> It would be nice if the introduction vignette could be made more prominent, maybe by using uppercase in the title (e.g. "GETTING STARTED with tidytof"), 

I've made this change! The vignette title is now "GETTING STARTED with tidytof", which I think helps it stand out in the list of vignettes. 

>and if the introduction vignette had a "where to go next" section -- or something like that -- that lists the other vignettes in the recommended order of reading and provides a short description for each of them.

To your point, I've added a "Where to go next" section to the introductory vignette that includes a suggested order for visiting the remainder of the vignettes. The schema that I've proposed starts small (at the cell-level) and works its way up to higher-order (i.e. cluster and then sample-level) operations. 

I've also added references to the tidytof [manuscript](https://academic.oup.com/bioinformaticsadvances/article/3/1/vbad071/7192984) and the manuscript describing the larger ["tidyomics" project](https://www.biorxiv.org/content/10.1101/2023.09.10.557072v2)

> Also what does `tof` stand for? It's part of the package name and is the prefix of a bunch of function names defined in the package, but I can't figure out where it's comming from. I'm curious why you didn't choose **tidycyto** for the package name since it would have made the package's relationship with cytometry immediately obvious. Anyways would be nice to explain the `tof` acronym in the introduction vignette.

This is a great question, and at some point in the future I've been considering building a next-generation version of tidytof (that would probably have the name "tidycyto"). The "tof" in "tidytof" comes from [CyTOF](https://en.wikipedia.org/wiki/CyTOF#:~:text=Cytometry%20by%20time%20of%20flight,using%20an%20ICP%2DMS%20detector.) (mass cytometry), which is a high-dimensional cytometry technology that much of the field focuses on (including myself). tidytof works for high-dimensional cytometry platforms other than CyTOF, but the implicit focus is on CyTOF (where there is less tidy tooling, compared to `tidyFlowCore` that essentially works right out-of-the-box for any cytometry platform that can be analyzed with `flowCore`.) 

To this point, I've added a brief parenthetical that explains the naming in the introductory vignette. It reads as follows: 

`{tidytof}` ("tidy" as in ["tidy data"](https://r4ds.had.co.nz/tidy-data.html); "tof" as in ["CyTOF"](https://onlinelibrary.wiley.com/doi/10.1002/cyto.a.23621), a flagship high-dimensional cytometry technology) implements a concise, integrated "grammar" of single-cell data analysis capable of answering a variety of biological questions.

> 
> Thanks, H.

**Comment by vjcitn** [comment]
Just a quick comment concerning the number of vignettes,  I had a look at the pkgdown site and was impressed by:

![tofsh](https://github.com/Bioconductor/Contributions/assets/4624066/8c457314-0da4-4f9f-87c8-2bae1ff89516)

**Comment by vjcitn** [comment]
I don't know how to do that (substructuring the articles tab content) and will look at the sources for guidance.  It would be great if R's HTML help pages could incorporate such substructure but that's likely a ways down the road.

**Comment by hpages** [comment]
Hi @keyes-timothy,

Thanks for all the improvements to the vignettes and sorry for the slow response. This is great documentation!

Note that changing the title of the vignette to "GETTING STARTED with tidytof" unfortunately has no effect on the listing produced by `browseVignettes(package="tidytof")`. So I'm still in the same situation as before. To actually control that listing you also need to change the `%\VignetteIndexEntry{}` line which is still:
```
%\VignetteIndexEntry{Getting started with tidytof}
```
Also `browseVignettes()` lists vignettes in alphabetical order of  `\VignetteIndexEntry{}` value so you can use that to control the _order_ of the listing by adding a number (or a letter) before the title e.g.
```
%\VignetteIndexEntry{1. GETTING STARTED with tidytof}
```
I suggest that you use this to your advantage to list the vignettes in the order of suggested reading, that is, in the order that you have them listed in the "Where to go next" section of the "GETTING STARTED with tidytof". This will also control the order in which the vignettes get listed on the landing page of the package. FWIW I started to use this recently to control the order of my vignettes e.g. on [**DelayedArray**'s landing page](https://bioconductor.org/packages/DelayedArray).

Finally, I think it would be useful to suggest the use of `browseVignettes(package="tidytof")` at the end of the "Where to go next" section. This will make it easy for your readers to find these vignettes and continue their reading.

Other than that package looks good and is ready to go.

Best,
H.

**Comment by hpages** [comment]
Hi @keyes-timothy,

Just a reminder that the package is still waiting for the minor (and hopefully easy) improvements listed above. Let me know if you have questions.

Best,
H.

**Comment by keyes-timothy** [comment]
Hi @hpages, 

Thank you for your comments - and for your reminder to wrap up these small changes! I've incorporated your feedback by adding indexes to the titles of the vignettes, and I've added the example call to `browseVignettes(package = "tidytof")` to the "Where to go next" section of the introductory vignette. The vignettes are now displayed to the user in a nice, ordered format: 

![Screenshot 2024-08-25 at 4 45 51 PM](https://github.com/user-attachments/assets/a2fbfda4-54cf-4983-b9fb-d637ba72b719)

I think we may be good to go! 
Timothy

**Comment by hpages** [comment]
Excellent! Thank you

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/keyes-timothy.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tidytof")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tidytof

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
