### ISSUE TITLE
UPDhmm

### ISSUE THREAD

**Issue by martasevilla** [Bioconductor/Contributions#3335]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/martasevilla/UPDhmm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment]
Hi @martasevilla

Thanks for submitting **UPDhmm** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

# General package development

- [ ] :rotating_light: Please address the errors from `BiocCheck::BiocCheck()` in the build report
- [ ] :rotating_light: Please address the errors from `BiocCheck::BiocCheckGitClone()` in the build report

## DESCRIPTION file

- [ ] :green_circle: Consider adding additional `biocViews` such as the type of data the package can be used for


## The NEWS file

- [ ] :green_circle: Remember to update the `NEWS` file as you make changes to the package

## Documentation

- [ ] :green_circle: I noticed typos in a few places, you can use the **{spellcheck}** package to help with this

### README

- [ ] :rotating_light: Please add a `README` file. This should contain Bioconductor installation instructions
### Vignette

- [ ] :rotating_light: Please remove the `fig/` directory as these are not used in the vignette
- [ ] :warning: Please check that the rendered vignette is formatted correctly, I noticed some issues with the authors etc. You can check this will `devtools::build_vignettes()`.
- [ ] :warning: Please check the function names in the vignette text match the actual function names in the package
- [ ] :green_circle: It would be nice to add sentence or two explaining how to interpret the final plot

## Unit tests

- [ ] :rotating_light: Please remove the `test.vcf.gz` file

## Code

### R

- [ ] :rotating_light: Compulsory function arguments should not have a default value, instead of using a default of `NULL`
- [ ] :rotating_light: Please check the explanation of the function arguments for exported function. For example it is not clear to me what the input to the `hmm` argument should be.
- [ ] :warning: Consider adding validity checks for function arguments
- [ ] :rotating_light: Please remove the `extractTrioNA19675.sh` and `getFileExdata.txt` files from the `R/` directory
- [ ] :green_circle: I found the lack of indentation in your code made it hard to read. You can use the **{styler}** package to help with this as described here https://www.bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#formatting-checks.
- [ ] :green_circle: This code:

  ```r
  colnames(largecollapsedVcf) <- gsub(father, "father",colnames(largecollapsedVcf))
  ```

  Would be clearer written as:

  ```r
  colnames(largecollapsedVcf)[colnames(largecollapsedVcf) == father] <- "father"
  ```

**Comment by martasevilla** [comment]
> Hi @lazappi
> 
> Thanks for the review of **UPDhmm** 🎉! Below is my responde to the suggestions:
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.
> 
> Luke
> 
> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> # General package development
> * [x]  🚨 Please address the errors from `BiocCheck::BiocCheck()` in the build report
> * [x]  🚨 Please address the errors from `BiocCheck::BiocCheckGitClone()` in the build report
_I have already solve the Errors abouth tagged packages_
> 
> ## DESCRIPTION file
> * [x]  🟢 Consider adding additional `biocViews` such as the type of data the package can be used for
_I have add a new biocViews: Genetics, referring to the type of data used_
> 
> ## The NEWS file
> * [x]  🟢 Remember to update the `NEWS` file as you make changes to the package
> 
> ## Documentation
> * [x]  🟢 I noticed typos in a few places, you can use the **{spellcheck}** package to help with this
> 
> ### README
> * [x]  🚨 Please add a `README` file. This should contain Bioconductor installation instructions
> 
> ### Vignette
> * [x]  🚨 Please remove the `fig/` directory as these are not used in the vignette
> * [x]  ⚠️ Please check that the rendered vignette is formatted correctly, I noticed some issues with the authors etc. You can check this will `devtools::build_vignettes()`.
> * [x]  ⚠️ Please check the function names in the vignette text match the actual function names in the package
> * [x]  🟢 It would be nice to add sentence or two explaining how to interpret the final plot
> 
> ## Unit tests
> * [x]  🚨 Please remove the `test.vcf.gz` file
_I have placed this file inside inst/ folder as is the file used for the tests_
> 
> ## Code
> ### R
> * [x]  🚨 Compulsory function arguments should not have a default value, instead of using a default of `NULL`
> * [x]  🚨 Please check the explanation of the function arguments for exported function. For example it is not clear to me what the input to the `hmm` argument should be.
_I have add a explanation about the format needed, I hope it is clear now_
> * [x]  ⚠️ Consider adding validity checks for function arguments
> * [x]  🚨 Please remove the `extractTrioNA19675.sh` and `getFileExdata.txt` files from the `R/` directory
> * [x]  🟢 I found the lack of indentation in your code made it hard to read. You can use the **{styler}** package to help with this as described here https://www.bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#formatting-checks.
> * [x]  🟢 This code:
>   ```r
>   colnames(largecollapsedVcf) <- gsub(father, "father",colnames(largecollapsedVcf))
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Would be clearer written as:
>   ```r
>   colnames(largecollapsedVcf)[colnames(largecollapsedVcf) == father] <- "father"
>   ```

**Comment by martasevilla** [comment]
Thank you very much for the revision. I have assessed all the suggested changes. Please let me know if I have missed something; I won't hesitate to make further adjustments.

**Comment by lazappi** [comment]
- A new build doesn't seem to have been triggered for some reason. Maybe you forgot to update the version number?
- The `test.vcf.gz` is still present in the test directory
- The `test.vcf.gz` file in `inst/` should be documented `inst/scripts/`
- Compulsory arguments should come before optional arguments in function definitions
- The default value for the `hmm` argument doesn't match the description. The description seems to imply a list (although it doesn't say that) but the default is a string. As this is an optional argument this may be a case where the default should be `NULL` with an explanation in the description of what happens in that case.
- Optional function arguments should have some default rather than using `missing()`. This makes it clearer to the user which arguments they have to supply.
- The `else` part of this code doesn't do anything and can be removed

```r
if (missing(genotypes)) {
    genotypes <- c(
        "0/0" = "1", "0/1" = "2", "1/0" = "2", "1/1" = "3",
        "0|0" = "1", "0|1" = "2", "1|0" = "2", "1|1" = "3"
    )
} else {
    genotypes
}
```

**Comment by martasevilla** [comment]
Thank you very much for your answer. I will assess this problem as soon as possible.

**Comment by martasevilla** [comment]
Dear @lazappi. I have already assessed the pertinent changes

> * A new build doesn't seem to have been triggered for some reason. Maybe you forgot to update the version number?
[x] I believe this issue is addressed now.
> * The `test.vcf.gz` is still present in the test directory
[x] Already removed
> * The `test.vcf.gz` file in `inst/` should be documented `inst/scripts/`
[x] The `test.vcf.gz` and `test_het_mat.vcf.gz` files are documented in `inst/scripts/getFilesExdata.sh`
> * Compulsory arguments should come before optional arguments in function definitions
> * The default value for the `hmm` argument doesn't match the description. The description seems to imply a list (although it doesn't say that) but the default is a string. As this is an optional argument this may be a case where the default should be `NULL` with an explanation in the description of what happens in that case.
> * Optional function arguments should have some default rather than using `missing()`. This makes it clearer to the user which arguments they have to supply.
> * The `else` part of this code doesn't do anything and can be removed
> 
> ```r
> if (missing(genotypes)) {
>     genotypes <- c(
>         "0/0" = "1", "0/1" = "2", "1/0" = "2", "1/1" = "3",
>         "0|0" = "1", "0|1" = "2", "1|0" = "2", "1|1" = "3"
>     )
> } else {
>     genotypes
> }
> ```
[x] The remaining comments have also been addressed.

Thank you very much in advance. 
I hope everything is clear now. 
Looking forward to hear from you.

**Comment by lazappi** [comment]
> > * Compulsory arguments should come before optional arguments in function definitions

This should be fixed in `vcfCheck()`

> > * The default value for the `hmm` argument doesn't match the description. The description seems to imply a list (although it doesn't say that) but the default is a string. As this is an optional argument this may be a case where the default should be `NULL` with an explanation in the description of what happens in that case.

Explanation of what happens when `hmm = NULL` is still missing. In the function, it would be better to check for `is.null(hmm)` rather than `!is.list(hmm)`.

> > * Optional function arguments should have some default rather than using `missing()`. This makes it clearer to the user which arguments they have to supply.

You don't need to use `missing()` for compulsory arguments, R will take of this for you. It is useful to check for what has been provided to those arguments though.

I think there is still some general tidying etc. of the package that can be done but that is relatively minor so I am happy to accept the package as is and hope you will continue to improve it.

**Comment by lazappi** [comment]
Congratulations on having the package accepted into Bioconductor 🎉! It can take a few days to be picked up by the build system but then it should be available in Bioconductor devel.

**Comment by martasevilla** [comment]
Thank you very much! I will incorporate the pertinent modifications you suggested and also take an overview of the code to identify any potential improvements related to general tidiness.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/martasevilla.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("UPDhmm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/UPDhmm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
