### ISSUE TITLE
scaeData

### ISSUE THREAD

**Issue by ahmadalajami** [Bioconductor/Contributions#3338]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/AGImkeller/scaeData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ahmadalajami** [comment]
@federicomarini
@agimkeller
@jonas-schuck

**Comment by ahmadalajami** [comment]
@agimkeller

**Comment by lshep** [comment]
**vignette**
- [ ] 
Since this line in the vignette seems to download all your data from each of the sets 
```
pbmc_5k <- scaeDataGet("pbmc_5k")
pbmc_10k <- scaeDataGet("pbmc_10k")
pbmc_20k <- scaeDataGet("pbmc_20k")

pbmc_20k
```
perhaps it would be best to only execute the pbmc_20k that you use for examples and show but not execute (eval=FALSE) the other sets? Let users download the sets they would like?

- [ ] You don't need to reference github to download the lookup tables that are provided in `inst/extdata`.  You can retrieve those interactively in R through a system.file command combined with read.csv. Something similar to 
```
lookup = read.csv(system.file("extdata", "pbmc_20k_lookup_table.csv", package="scaeData"))
```

- [ ] Why is the last section where you run read_allele_counts in an `eval=FALSE` ?  This should be executed.  I see it depends on SingleCellAlleleExperiment -- since these were not submitted as related packages, we can assume it will be accepted and I can test locally / you can ignore the error that will occur that the package cannot be found. 

**man**
- [ ] Please provide a package level man page so when a naive user does `?scaeData` something is displayed.

**Comment by federicomarini** [comment]
Thanks for the review comments @lshep !

We will be starting right away to work on them on a specific `bioc_review` branch!

One clarification about the unevaluated chunk in the vignette (with `read_allele_counts`) - We thought that having the function from `SingleCellAlleleExperiment` in there (and run, i.e. including that as Suggests) would introduce a circular dependency, which we wanted to explicitly avoid. I wanted to apologize for not seeing this one earlier - https://github.com/Bioconductor/Contributions/blob/devel/CONTRIBUTING.md#circular-dependencies.  
This seems exactly like our case, so we should (here) Suggest `SingleCellAlleleExperiment` and there Depend on `scaeData`?

**Comment by lshep** [comment]
If this example will be run in the SingleCellAlleleExperiment we can let it go if you want to avoid the dependency.  But yes Suggest seems appropriate here since its used in the vignette but the data isn't dependent on a defined class in the Software package;  The SingleCellAlleleExperiment will depend on where and how you use the data to define if it should be Suggest, Import, or Depend.

**Comment by federicomarini** [comment]
> If this example will be run in the SingleCellAlleleExperiment we can let it go if you want to avoid the dependency. But yes Suggest seems appropriate here since its used in the vignette but the data isn't dependent on a defined class in the Software package

Fair enough. It does make sense to test it also here, "because why not show the full workflow" at least to read things in fully.
The corresponding edits will be done, with `SingleCellAlleleExperiment` going into "Suggests"

> The SingleCellAlleleExperiment will depend on where and how you use the data to define if it should be Suggest, Import, or Depend.

Ok, thanks for clarifying this. In there, `read_allele_counts` will definitely make use of the data. Probably a "Suggests" entry is too soft, even if we just use it in the examples.

But given `scaeData` only exports one function (`scaeDataGet`), I think we can be safe and call it a "Depends", as no masking of the namespaces are expected to happen.

**Comment by ahmadalajami** [comment]
Thanks a lot for your suggestions, @lshep! Please find below my response:

------------------------------------------------

**vignette**

[x]
Since this line in the vignette seems to download all your data from each of the sets

```
pbmc_5k <- scaeDataGet("pbmc_5k")
pbmc_10k <- scaeDataGet("pbmc_10k")
pbmc_20k <- scaeDataGet("pbmc_20k")

pbmc_20k
```

perhaps it would be best to only execute the pbmc_20k that you use for examples and show but not execute (eval=FALSE) the other sets? Let users download the sets they would like?

--> AA: thank you for this suggestion. We split this into two chunks, the first is `eval=FALSE` and contains the first two datasets. The second chunk, which we want to execute and show as an example, contains the third dataset and is `eval=TRUE`.

[x] 
You don't need to reference github to download the lookup tables that are provided in `inst/extdata`. You can retrieve those interactively in R through a system.file command combined with read.csv. Something similar to

`lookup = read.csv(system.file("extdata", "pbmc_20k_lookup_table.csv", package="scaeData"))`

--> AA: this is definitely a better way to access the data. We changed this accordingly. Thank you.

[x]
Why is the last section where you run read_allele_counts in an `eval=FALSE`? This should be executed. I see it depends on SingleCellAlleleExperiment -- since these were not submitted as related packages, we can assume it will be accepted and I can test locally / you can ignore the error that will occur that the package cannot be found.

--> AA: upon your suggestion, we added `Suggests: SingleCellAlleleExperiment`, which as expected, threw an error in the vignette. I am ignoring this per your request.

**man**

[x]
Please provide a package level man page so when a naive user does ?scaeData something is displayed.

--> AA: thank you for reminding us! We have created an `scaeData-pkg.R` to resolve this.

------------------------------------------------

All changes have been made upon your request. Please note the error the vignette is throwing after adding `Suggests: SingleCellAlleleExperiment`.

Thanks once again and we are looking forward to your feedback :)

**Comment by Jonas-Schuck** [comment]
Hello @lshep and thanks for your helpful comments - just a little heads up regarding the local testing of `scaeData` with the new `Suggests:SingleCellAlleleExperiment` change, in case you missed the most recent push in `SingleCellAlleleExperiment`.  Please use the most recent version of `SingleCellAlleleExperiment 0.99.1`, pushed just now, otherwise errors would be expected. Thanks!

**Comment by lshep** [comment]
Thanks looks good.  I'll accept and get it on the builders so SingleCellAlleleExperiment review can progress.  
Cheers,

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ahmadalajami.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scaeData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scaeData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by federicomarini** [comment]
Thanks @lshep for the timely review!
Looking forward to receiving the feedback from the reviewers for the companion package, `SingleCellAlleleExperiment`!
