### ISSUE TITLE
SingleCellAlleleExperiment

### ISSUE THREAD

**Issue by Jonas-Schuck** [Bioconductor/Contributions#3339]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/AGImkeller/SingleCellAlleleExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Jonas-Schuck** [comment]
@AGImkeller
@federicomarini
@ahmadalajami

**Comment by lshep** [comment]
Just a reminder, because this package utilizes scaeData that is also under review we would not be able to review this package until scaeData is accepted and on the builders since this was not submitted as an additionalpackage to the scaeData submission.

**Comment by Jonas-Schuck** [comment]
Hello @lshep , since `scaeData` is now integrated after the successful nightly build, we performed a version bump here to re-trigger the building process. Sadly, we got a `WARNING` as we don’t quite scratch the max allowed time of `CMD CHECK`. Currently it lies at 10:58 minutes. Would this be an issue for the review process to begin, while we figure out a way to squeeze the check time a little more (if really necessary, as its already quite close to the time limit)? We would be happy for your advice on how to proceed here, thanks a lot in advance!

**Comment by HelenaLC** [comment]
In the interest of time, I am posting a first round of comments here to get the ball rolling... Specifically, please try and address comments related to dependencies and class development, also considering the corresponding guidelines - the current implementation "feels" like a set of functions rather than an S4 class. This is not bad, per se. However, defining a reader and subsetting of these data for an SCE would be sufficient, plus a couple checks that the `rowData` match your expectation - unless the overhead of defining a class properly is met.

If there're any questions, points that aren't clear etc., fell free to ask/discuss here - cheers!

# NAMESPACE

- [ ] since the package's purpose is to implement an S4 class, I'd strongly encourage working towards a minimal number of dependencies. Any visualizations, processing etc. could be demoed in the vignette/examples with the corresponding libraries under `Suggests:` (see [here](https://contributions.bioconductor.org/description.html#depends-imports-suggests-enhances) for details). The motivation here is that other packages dedicated to analysis and visualization etc. may only need the class definition/constructor/accessor/replacement methods, but needn't have additional dependencies. Specifically,
  - there's no reason to depend on any data packages; these can be attached for use in tests, examples, the vignette, but can go under `Suggests:`
  - there's no need to depend on `ggplot2`; the plot could be generated in the vignette, but SCAE-specific visualizations should be dispatched in a separate package (or made optional by suggesting the package)
  - `scuttle` also seems rather superfluous; for demonstration, `logcounts` could be computed in the vignette, using this or any other method, but suggesting the package should suffice (making that computation optional in the function is also possible when suggesting the package)

# docs

- [ ] `SingleCellAlleleExperiment.Rd` is missing a runnable example; since the class is what "it's all about", could also demo (in code and/or comments) some aspects of how the object compares to an SCE; have a look at the SCE doc for inspiration, or SPE for more extended examples 

- [ ] in the vignette, consider linking to external packages using `BiocStyle` functions (`CRANPkg/BiocPkg()` for packages distributed through GitHub/CRAN/Bioc)

# code

- [ ] please have a look at these [guidelines](https://contributions.bioconductor.org/r-code.html#class-development) regarding class development and try to follow them -- e.g., code and script organization

- [ ] related, the class is missing a validity method and, potentially, appropriate replacement methods (e.g., something like `rowData(scae)$NI_I <- 'xyz'` would break lots of things and setting `NI_I/Quant_Type` to NULL gives basically a plain SCE, I think?); validity and setters need to assure the object cannot be "broken"

- [ ] related, it'd be nice if there was a simple show method to distinguish a SCAE object from a SCE; printed in the console, it's hard to tell the difference - e.g., could print the number NI/I features or ??? ...something that you feel is worth highlighting (if anything?)

- [ ] being the only exported getter, it'd be great if `scae_subset` (and/or the functions being called by it)  implemented appropriate validity checks on input arguments and structure (of the input SCAE)

- [ ] a general suggestion to better stick to the recommend 80-character line limit, improve legibility, and make your life easier: consider defining intermediate variables when, say, the same series of symbols is used repeatedly in a function, e.g.:

```
# e.g., this...
get_nigenes <- function(scae) {
  subset_rows <- stats::complete.cases(rowData(scae)$NI_I, rowData(scae)$Quant_type)
  agenes <- scae[subset_rows & rowData(scae)$NI_I == "NI" & rowData(scae)$Quant_type == "G", ]
  return(agenes)
}

# ...could be
rd <- rowData(scae)
subset_rows <- stats::complete.cases(rd$NI_I, rd$Quant_type)
agenes <- scae[subset_rows & rd$NI_I == "NI" & rd$Quant_type == "G", ]

# or...
rd <- rowData(scae)
ni <- rd$NI_I
qt <- rd$Quant_type
subset_rows <- stats::complete.cases(ni, qt)
agenes <- scae[subset_rows & ni == "NI" & qt == "G", ]

# another example:
rowData(final_scae[rownames(final_scae) %in% uniqs])$NI_I <- "I"
rowData(final_scae[rownames(final_scae) %in% uniqs])$Quant_type <- "F"

# ...vs.
idx <- rownames(final_scae) %in% uniqs
rowData(final_scae)$NI_I[idx] <- "I"
rowData(final_scae)$Quant_type[idx] <- "F"
```

**Comment by Jonas-Schuck** [comment]
Thanks for your timely review @HelenaLC, we are looking into this and will update/change the package accordingly!

**Comment by Jonas-Schuck** [comment]
Hello @HelenaLC , please find below our comments and changes. We appreciate your review and the points you raised.

> In the interest of time, I am posting a first round of comments here to get the ball rolling... Specifically, please try and address comments related to dependencies and class development, also considering the corresponding guidelines - the current implementation "feels" like a set of functions rather than an S4 class. This is not bad, per se. However, defining a reader and sub-setting of these data for an SCE would be sufficient, plus a couple checks that the `rowData` match your expectation - unless the overhead of defining a class properly is met.
>
This is a very good point. We agree that the package structure was not clear enough and the definition of a novel data structure was impaired by additional (and default) “convenient” functionalities. We decided to follow your suggestion and focused on the implementation of a S4 class. We think that implementing a multi-layered data structure, more specifically, aggregating information about groups of expression features via an ontology approach and keeping those multiple layers accessible throughout the process, is a valuable addition to Bioconductor. In the future, this structure can also be useful for other biological applications, where features have different levels of meaningful annotation (e.g. splicing variant, tRNAs, …)

> # NAMESPACE
>
> 	* [ ]  since the package's purpose is to implement an S4 class, I'd strongly encourage working towards a minimal number of dependencies. Any visualizations, processing etc. could be demoed in the vignette/examples with the corresponding libraries under `Suggests:` (see [here](https://contributions.bioconductor.org/description.html#depends-imports-suggests-enhances) for details). The motivation here is that other packages dedicated to analysis and visualization etc. may only need the class definition/constructor/accessor/replacement methods, but needn't have additional dependencies. Specifically,	

Thanks for bringing this up. By focusing on the core functionality of our S4 object we reduced the number of dependencies significantly. Find more info in the following points.
 
>   * there's no reason to depend on any data packages; these can be attached for use in tests, examples, the vignette, but can go under `Suggests:`

The `scaeData`  package already was listed under `Suggests:`. If we missed other data packages, please let us know.

>   * there's no need to depend on `ggplot2`; the plot could be generated in the vignette, but SCAE-specific visualizations should be dispatched in a separate package (or made optional by suggesting the package)

This is fixed. `ggplot2` as well as `DropletUtils` went to `Suggests:`. This makes the potential filtering based on a computed knee plot optional. If the read in function `read_allele_counts()` is used with the parameter `filter_mode=”yes”`, data is still filtered on the inflection point of the corresponding knee plot. But instead of plotting it, all necessary information is passed to the `metadata(scae)[[`knee_info’]]` slot, ready to be plotted later on. 

>   * `scuttle` also seems rather superfluous; for demonstration, `logcounts` could be computed in the vignette, using this or any other method, but suggesting the package should suffice (making that computation optional in the function is also possible when suggesting the package)
>

This is also optional now with `scuttle` moved to `Suggests:`. But **toggled on** by default. The reason behind this is the following: If the user would miss the part about how to properly normalize the multi-layered data, this would result in falsely normalized data. As the assays in the `SCAE` data structure are extended (more rows are added to the raw data counts) it is necessary to compute libraryFactors only on the raw data layers. Otherwise the Size Factors would not be correct (immune features would contribute to the size factor multiple times). We appreciate the point you raised to make this optional, but we still would like to keep it as a default (but optional) functionality, which still offers experienced users to perform a different normalization method later on.

Additionally, we also moved all packages related to computing new gene symbols under suggests, making this an optional feature as well.

We think our newly implemented changes allow us to keep things simple on default, having only few dependencies for the implementation of the core data structure, but still provide us with the option to use more advanced functionalities if necessary/wanted. 



> # docs
>
> 	* [ ]  `SingleCellAlleleExperiment.Rd` is missing a runnable example; since the class is what "it's all about", could also demo (in code and/or comments) some aspects of how the object compares to an SCE; have a look at the SCE doc for inspiration, or SPE for more extended examples
>

Thanks for raising this. We added an example and exported the Constructor. 


> 	* [ ]  in the vignette, consider linking to external packages using `BiocStyle` functions (`CRANPkg/BiocPkg()` for packages distributed through GitHub/CRAN/Bioc)
>

This was changed accordingly. Additionally, new sections can be found in the vignette, giving information about the (now) optional functionalities.

> # code
>
>  * [ ]  please have a look at these [guidelines](https://contributions.bioconductor.org/r-code.html#class-development) regarding class development and try to follow them -- e.g., code and script organization
>

Changes to code and script organisation were done. Now there is a file for each exported function, which also includes their respective internal functions. One additional file for misc functions, currently containing the show method. Inspiration taken from SCE/SPE.

>  * [ ]  related, the class is missing a validity method and, potentially, appropriate replacement methods (e.g., something like `rowData(scae)$NI_I <- 'xyz'` would break lots of things and setting `NI_I/Quant_Type` to NULL gives basically a plain SCE, I think?); validity and setters need to assure the object cannot be "broken"
>

That’s a very good point. Thanks for bringing this to our attention. We added some validity checks to make sure that handling the rowData is done in a more robust manner now. We are aware that this might not catch every single point on how one might break the object, but we are having an eye on this now, willing to extend this if additional relevant cases come up. Also a setter for the rowData was defined, testing for the validity checks.

>  * [ ]  related, it'd be nice if there was a simple show method to distinguish a SCAE object from a SCE; printed in the console, it's hard to tell the difference - e.g., could print the number NI/I features or ??? ...something that you feel is worth highlighting (if anything?)
>

Thanks for bringing this up. We defined an extension to the SCE show method, giving information about the content of the newly defined layers.
> 	* [ ]  being the only exported getter, it'd be great if `scae_subset` (and/or the functions being called by it)  implemented appropriate validity checks on input arguments and structure (of the input SCAE)
>

We incorporated validity checks for the output of `scae_subset` as well as a check (for input type and class type) for the chosen subset input. Please find the changes in the scaeSubset.R file.

> 	* [ ]  a general suggestion to better stick to the recommend 80-character line limit, improve legibility, and make your life easier: consider defining intermediate variables when, say, the same series of symbols is used repeatedly in a function, e.g.:
>

Thanks for the examples. We made changes to the code to better stick to the 80-character line limit and increase legibility. 

This is it for now. We look forward to hearing back from you!

**Comment by HelenaLC** [comment]
Thanks for all that, big improvement overall! I have 2 outstanding comments (+ 1 very minor one) that I feel should be addressed; especially correct implementation of mandatory/optional (`Imports/Suggests:`) packages. Packages under `Suggests:` will *not* be automatically installed. So running functions with missing dependencies will currently fail even when part of the execution is optional - you need to check for this and execute accordingly (details below)!

- minor comment on show method: are there cases where the number of included features differs from `nrow(scae)`? If yes, all good. If no, I find the line "Including a total of N features:" redundant.

- invalid replacement (e.g., `rowData(scae)$NI_I <- NULL`) now give an error and return the object in it's original form, however, it'd be desirable to give a more meaningful message here (currently, the message from the validity method is given). E.g., in `SpatialExperiment`, the must-have `colData` is retained silently or a message is given why a replacement is invalid (vs. an "invalid object" error); see [here](https://github.com/drighelli/SpatialExperiment/blob/devel/R/SpatialExperiment-colData.R)

- any calls to packages under `Suggests:` should check that the package is available and either skip that functionality (for optional things) or give a meaningful message to the user; see [here](https://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances). E.g., `SingleCellAlleleExperiment()` will just fail when `scuttle` or `DelayedArray` are unavailable, but it should still work without normalization & creating a delayed matrix, if it truly is "optional"? If not, these packages would be necessary for core functionality (class construction) and there should be under `Imports:` instead. Vice versa, something like `get_ncbi_org()` cannot work without `org.Hs.eg.db` and `AnnotationDbi`, so the user should be told so.

**Comment by Jonas-Schuck** [comment]
Thanks for your second round of comments! We will address them and come back to you early next week.

**Comment by HelenaLC** [comment]
Sure! Note that the package has to be in my Wed April 24th to be added to the 3.19 release - so the earlier you push & pass the better, just in case 🙏

**Comment by Jonas-Schuck** [comment]
Hello @HelenaLC, please find below our comments and changes.
> Thanks for all that, big improvement overall! I have 2 outstanding comments (+ 1 very minor one) that I feel should be addressed; especially correct implementation of mandatory/optional (`Imports/Suggests:`) packages. Packages under `Suggests:` will _not_ be automatically installed. So running functions with missing dependencies will currently fail even when part of the execution is optional - you need to check for this and execute accordingly (details below)!
>
> 	* minor comment on show method: are there cases where the number of included features differs from `nrow(scae)`? If yes, all good. If no, I find the line "Including a total of N features:" redundant.
>
Thanks for the advice. We removed redundancy and now give information about how many immune-related features the SCAE-object contains.
![image](https://github.com/Bioconductor/Contributions/assets/106832949/511baa8a-386f-4fde-af36-3218bed3d2bd)

> 	* invalid replacement (e.g., `rowData(scae)$NI_I <- NULL`) now give an error and return the object in it's original form, however, it'd be desirable to give a more meaningful message here (currently, the message from the validity method is given). E.g., in `SpatialExperiment`, the must-have `colData` is retained silently or a message is given why a replacement is invalid (vs. an "invalid object" error); see [here](https://github.com/drighelli/SpatialExperiment/blob/devel/R/SpatialExperiment-colData.R)
>
Thanks for providing the `SPE` example! We implemented silent retention and extended the error messages when setting invalid values. More specifically:
* When performing `rowData(scae)<-NULL` we silently retain the NI_I and Quant_type column (inspired by `SPE`).
* Additional error messages and more detailed information inside the setter functions rather than having all checks in the validity method.

Examples:
![image](https://github.com/Bioconductor/Contributions/assets/106832949/a16b4d6f-b415-4948-b237-614f1d18bbdc)
![image](https://github.com/Bioconductor/Contributions/assets/106832949/94a298d3-eda9-4f71-8eff-3bffcaf64419)

> 	* any calls to packages under `Suggests:` should check that the package is available and either skip that functionality (for optional things) or give a meaningful message to the user; see [here](https://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances). E.g., `SingleCellAlleleExperiment()` will just fail when `scuttle` or `DelayedArray` are unavailable, but it should still work without normalization & creating a delayed matrix, if it truly is "optional"? If not, these packages would be necessary for core functionality (class construction) and there should be under `Imports:` instead. Vice versa, something like `get_ncbi_org()` cannot work without `org.Hs.eg.db` and `AnnotationDbi`, so the user should be told so.


Thank you, this is indeed an important point. We had the checks already set in the read-in function `read_allele_counts()` but missed to also check in the SCAE-Constructor. Now all packages that are related to optional functionalities (e.g. `scuttle`, `DropletUtils`, `org.Hs.eg.db`, `AnnotationDbi`) should be checked for installation before using the functionality and give a corresponding message if they’re not installed. You can now find the corresponding function in the `validity.R` file and/or in the first few lines of code of the `SingleCellAlleleExperiment()` and `read_allele_counts()` functions. 

See below for examples:

![image](https://github.com/Bioconductor/Contributions/assets/106832949/77b44122-9a31-40c2-8aaa-5df90dd635e6)


Thank you again for your valuable comments. We think that the package improved a lot throughout the review!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jonas-Schuck.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingleCellAlleleExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingleCellAlleleExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
