### ISSUE TITLE
UCSC.utils

### ISSUE THREAD

**Issue by hpages** [Bioconductor/Contributions#3343]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/UCSC.utils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 

Thank you for your submission. See the review below. 

Best regards,
Marcel

--- 

# UCSC.utils

## DESCRIPTION

* Looks good.

## NAMESPACE

* It seems like there are some struggles to get the data in the format required;
consider using `jsonlite::fromJSON` which will provide a `data.frame` for each
chromosome e.g., in:

```r
UCSC.utils:::.API_query(
    "getData/track",
    query = list(genome = "mm9", track = "cytoBandIdeo"),
    api.url = UCSC.utils::UCSC.api.url()
) |>
    httr::content(as = "text", encode = "UTF-8") |>
    jsonlite::fromJSON()
```

## vignettes

* Looks good.

## R

* Consider using `httr::stop_for_status` to check for errors. There may be conditions that are not exactly errors e.g., codes <300.
* Note that both `httpcache` and `httr2` provide caching mechanisms. Where the
former may be easier to use.

## tests

* Coverage looks good.

```r
> covr::package_coverage(type="all")
UCSC.utils Coverage: 90.06%
R/zzz.R: 0.00%
R/00utils.R: 20.00%
R/UCSC.api.url.R: 77.78%
R/REST_API.R: 84.31%
R/fetch_UCSC_track_data.R: 84.62%
R/UCSC_dbselect.R: 87.50%
R/list_UCSC_genomes.R: 94.37%
R/get_UCSC_chrom_sizes.R: 95.45%
R/list_UCSC_tracks.R: 98.77%
```

**Comment by hpages** [comment]
Thanks Marcel for suggesting to switch to `jsonlite::fromJSON()`. The fact that it automatically turns JSON tabular data into a data frame is a nice feature. UCSC's JSON is quite messy though so some data massaging and sanity checks will still be needed even after the switch. This will require some extensive testing.

**Comment by hpages** [comment]
Switch from `rjson::fromJSON` to `jsonlite::fromJSON` done  in **UCSC.utils** 0.99.4 (see https://github.com/Bioconductor/UCSC.utils/commit/f82b56085c3dcd5448778eb040ba0c20fc831312).

> Consider using `httr::stop_for_status` to check for errors.

Done.

> Note that both **httpcache** and **httr2** provide caching mechanisms.

That's good to know. However doing my own caching is _very_ easy and the caching facilities that these packages bring to the table don't have enough value to justify introducing a new dependency or switching from **httr** to **httr2**. Also I'm caching the parsed JSON, or a transformed version of it, not the raw HTTP response. 

Thanks again for your feedback.

H.

**Comment by LiNk-NY** [comment]
Thanks Hervé @hpages 
I tried to run the example in the comments and got an error in `R/REST_API.R`. 
It looks like `json_string` should be `text` instead. See the diff: 

```diff
diff --git a/R/REST_API.R b/R/REST_API.R
index 608c15b..1891f06 100644
--- a/R/REST_API.R
+++ b/R/REST_API.R
@@ -20,7 +20,7 @@
     json_string <- content(response, as="text", encoding="UTF-8")
     stopifnot(is.character(json_string), length(json_string) == 1L)
     if (is.na(json_string)) {
-        json_string <- content(response, as="json_string",
+        json_string <- content(response, as="text",
                                encoding="Windows-1252")
         stopifnot(isSingleString(json_string))
     }
```
FWIW: Here is the example:
```r
    query <- list(genome="eboVir3", track="iedbBcell")
    .API_query("getData/track", query=query)
```

**Comment by hpages** [comment]
arghh.. thanks for the eagle eyes!

Fixed in **UCSC.utils** 0.99.5

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 

Thank you for making the change. 
Your package has been accepted. 

Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpages.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("UCSC.utils")`. The package 'landing page' will be created at

https://bioconductor.org/packages/UCSC.utils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
