### ISSUE TITLE
iSEEfier

### ISSUE THREAD

**Issue by NajlaAbassi** [Bioconductor/Contributions#3348]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/NajlaAbassi/iSEEfier

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by NajlaAbassi** [comment]
cc @federicomarini

**Comment by NajlaAbassi** [comment]
I already subscribed to the Bioc-devel mailing list

**Comment by lshep** [comment]
I can confirm this; please ignore as it should clear up on the next build

**Comment by federicomarini** [comment]
Perfect, thanks for confirming this @lshep !
Shall we still re-trigger a new build, or is this now superfluous?

**Comment by LiNk-NY** [comment]
Hi @NajlaAbassi 

Thank you for your submission. 
Overall, the package looks to be in good shape. I only made some minor suggestions. 

Best regards,
Marcel

---

# iSEEfier

## DESCRIPTION

* Looks good.

## NAMESPACE

* Looks good.

## vignettes

* Minor: Consider wrapping text to fit an 80 character column width.
* It looks good.

## R

* The documentation text and even code goes past the 80 column width and makes
it hard to read and review.
* Combine multiple `stopifnot` calls into one, e.g.,
```r
stopifnot(is.character(collection), identical(length(collection), 1L))
```
* Consider using `BiocBaseUtils` for checking assertions with e.g.,
`isScalarCharacter` instead of the example above.
* Tell the user what package needs to be installed in the error message in
`iSEEnrich`.

## tests

* Looks good:

```r
> covr::package_coverage(type = "all")
iSEEfier Coverage: 98.91%
R/utils.R: 98.51%
R/iSEEinit.R: 99.13%
R/iSEEnrich.R: 100.00%
```

## BiocCheck results

* Consider resolving some of the notes. Overall, it looks good.

```r
─ BiocCheck results ──
0 ERRORS | 0 WARNINGS | 6 NOTES
```

**Comment by NajlaAbassi** [comment]
Thank you for your timely positive review @LiNk-NY !

We addressed the points you raised in a separate branch `BiocReview`, which we just merged in `devel` (link to the PR for you to check all thins at once: https://github.com/NajlaAbassi/iSEEfier/pull/8).  
Please find below our comments, in a point by point fashion.

> ## vignettes
> 
>     * Minor: Consider wrapping text to fit an 80 character column width.
> 
>     * It looks good.
> 
> 

We changed the text to fit a 80 character limit.

> ## R
> 
>     * The documentation text and even code goes past the 80 column width and makes
>       it hard to read and review.

Similar to the vignette, the code and documentation were wrapped into lines of 80 characters. BiocCheck is still raising a note for this, but only for a few extra characters and only a few occurrences.

> 
>     * Combine multiple `stopifnot` calls into one, e.g.,
> 
> 
> ```r
> stopifnot(is.character(collection), identical(length(collection), 1L))
> ```
> 
>     * Consider using `BiocBaseUtils` for checking assertions with e.g.,
>       `isScalarCharacter` instead of the example above.


Thanks a lot for pointing out `BiocBaseUtils`, we rewrote these checks in a more compact manner.

> 
>     * Tell the user what package needs to be installed in the error message in
>       `iSEEnrich`.
> 

Good point, thanks. We updated the error message accordingly.

> ## BiocCheck results
> 
>     * Consider resolving some of the notes. Overall, it looks good.
> 
> 
> ```r
> ─ BiocCheck results ──
> 0 ERRORS | 0 WARNINGS | 6 NOTES
> ```

- NOTE: Avoid 'cat' and 'print' outside of 'show' methods

→ The print() statement is there on purpose to render the htmlWidget output of the function, so we cannot remove it.
	
- NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions

→ In the context of that function (`glue_initials()`), we thought it was meaningful to have the message returned with this combination of conditions. 

- NOTE: The recommended function length is 50 lines or less. There are 4 functions greater than 50 lines
- NOTE: Consider shorter lines; 26 lines (2%) are > 80 characters long
- NOTE: Consider multiples of 4 spaces for line indents; 255 lines (24%) are not

→ We opted for an indentation of 2 spaces instead of 4, and worked by reflowing the code and comments to reduce its width. Regarding the length of the functions, we felt we could not modularize the routines further, which is why we kept them as they were.

- NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials).

→ Both Federico and I are correctly registered and subscribed to the bioc devel mailing list, this might be a false positive hit that we also get while running the checks locally.


---

Please let us know if we need to do some additional work. Thank you again for the feedback!

**Comment by LiNk-NY** [comment]
Hi Najla, @NajlaAbassi 

Thank you for making those changes!
Your package has been accepted. 

Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/NajlaAbassi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("iSEEfier")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iSEEfier

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
