### ISSUE TITLE
ggtreeSpace

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/Contributions#3356]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/ggtreeSpace

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Could you please provide an abstract/intro section in your vignette that provides motivation for inclusion in Bioconductor and when appropriate a review and comparison to existing Bioconductor packages with similar functionality or scope.

**Comment by GuangchuangYu** [comment]
@lshep We have updated the vignette with a more detail introduction.

**Comment by lazappi** [comment]
Hi @GuangchuangYu

Thanks for submitting **ggtreeSpace** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- :warnings: Ther are some `BiocCheck` notes in the build report, please check these and address them if necessary

## DESCRIPTION file

- :rotating_light: There are some licensing issues with the **{akima}** package that make it difficult to use as a dependency. It is highly recommended to replace this with an alternative package (including by the package authors). You can see some discussion of this issue here https://github.com/Oshlack/splatter/issues/108.

## NAMESPACE file

- [ ] :rotating_light: Please be consistent with function naming and use `camelCase` or `snake_case` and do not include `.`

## Documentation

- [ ] :green_circle: I noticed typos in a few places, you can use the **{spelling}** package to help with finding these.

### README

- [ ] :rotating_light: Please add more content to the `README`. Any installation instructions should include Bioconductor instructions.

### Vignette

- [ ] :rotating_light: Please use the `BiocStyle` package for formatting vignette. It should include a table of contents.
- [ ] :rotating_light: Please add an *Installation* section that:
  - [ ] Uses Bioconductor installation instructions
  - [ ] Installation code is not evaluated
- [ ] :warning: I feel there could be more detail about the functionality of the package including how to interpret the plots and what a "phylomorphospace" is.
- [ ] :rotating_light: You only need to load libraries once at the start of the document, not in every chunk

## Unit tests

- [ ] :rotating_light: It is highly recommended to add unit tests

## Code

### R

- [ ] :rotating_light: Please use `message()`, `warning()`, `stop()` instead of `cat()`
- [ ] :warning: Consider add more detail to function argument descripions. It is not clear to me what all the arguments should be.
- [ ] :warning: If function arguments include `...` then it should be clear in the description how additional arguments are used.
- [ ] :warning: Consider adding validity checks to function arguments
- [ ] :green_circle: I think you have included global variables to avoid check warnings but it may be possible to avoid these in other ways
- [ ] :rotating_light: The `aes_string()` function from the **{ggplot2}** function is deprecated and should not be used. Please see the ["Using ggplot2 in packages"](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html) and ["Extending ggplot2"](https://ggplot2.tidyverse.org/articles/extending-ggplot2.html) guides for alternatives.
- [ ] :question: The functions in this package seem to be minimal wrappers around **{ggtree}** and other packages. Can you please explain what you think the main added value of this package is?

**Comment by GuangchuangYu** [comment]
Thank you for your detailed examination and constructive feedback on our package. We greatly appreciate the time and effort you have invested in reviewing our work. Below, we address your comments as follows:

**General package development**

- ⚠️ Ther are some BiocCheck notes in the build report, please check these and address them if necessary
	- **✅Response**: We have addressed some of the notes by enriching the `Description` section in the *DESCRIPTION* file and shortening the code lines. However, some notes, such as those regarding function length, require significant code restructuring. We plan to tackle these in forthcoming updates. Many thanks for your valuable suggestions.
**DESCRIPTION file**
- 🚨 There are some licensing issues with the **{akima}** package that make it difficult to use as a dependency. It is highly recommended to replace this with an alternative package (including by the package authors). You can see some discussion of this issue here [Replacement for akima::aspline()? Oshlack/splatter#108](https://github.com/Oshlack/splatter/issues/108).
	-  **✅Response**: We have replaced the `interp` function from {akima} package with `interp` function from {interp} package. 

**NAMESPACE file**
- 🚨 Please be consistent with function naming and use `camelCase` or `snake_case` and do not include `.`
	- **✅Response**: We have change the naming of the `ggtreeSpace` , `geom_treeSpace`, `theme_treeSpace1` and `theme_treeSpace2` fuction into `ggtreespace` , `geom_treespace` ,`theme_treespace1` and `theme_treespace2` in order to match the `snake_case`. Thank you for pointing out our mistake.

**Documentation**
- 🟢 I noticed typos in a few places, you can use the **{spelling}** package to help with finding these.
	- **✅Response**: We have fixed the typos found by `spell_check_package` function of {spelling} package. Sorry for the inconvenience. 

**README**
- 🚨 Please add more content to the README. Any installation instructions should include Bioconductor instructions.
	- **✅Response**: We have updated the README file to add installation instruction, quick example and author information. Thank you for your feedback.
**Vignette**
- 🚨 Please use the BiocStyle package for formatting vignette. It should include a table of contents.
	- **✅Response**: We have updated the vignette of {ggtreeSpace} with BiocStyle formatting. 

- 🚨 Please add an _Installation_ section that:

	1. Uses Bioconductor installation instructions
	2. Installation code is not evaluated
	- **✅Response**: We have added an *Installation* section in the vignette. Thanks for the tip.

-  ⚠️ I feel there could be more detail about the functionality of the package including how to interpret the plots and what a "phylomorphospace" is.
	- **✅Response**: We have added some information to help explain what "phylomorphospace" is and interpret the plots. For examples:
		- "Phylomorphospace is a graphical representation that combines phylogenetic information and morphological (trait) data, mapping the evolutionary trajectories of species in a multidimensional space."
		- "You can plot basic phylomorphospace easily with the `ggtreespace` function, and add annotation to it with the `+` operator. In this example, we add symbolic point to the tip of phylomorphospace. From the phylomorphospace plot, we can observe the evolutionary trajectories of different species, illustrating how they diverge and adapt in their respective trait dimensions. This visual representation allows us to identify patterns of convergence and divergence among species, highlight instances of adaptive radiation, and so on. "
		- "You can also introduce an additional heatmap layer based on your data, adding another dimension of data to better elucidate how this data can affect evolutionary patterns. For example, species may cluster together in the morphospace due to shared environmental adaptations, and we can visualize this through the heatmap. This can provide insights into the underlying mechanisms driving species evolution and diversification."
	- Thank you for your helpful suggestions.

- 🚨 You only need to load libraries once at the start of the document, not in every chunk
	- **✅Response**: We have fixed this by loading libraries only at the start. Grateful for your keen observations.

**Unit tests**
- 🚨 It is highly recommended to add unit tests
	- **✅Response**: We have added some unit tests with `testthat`. 
**Code**

**R**
- 🚨 Please use message(), warning(), stop() instead of cat()
	- **✅Response**: We have replaced the following code in the `phylospm` function. 

- ⚠️ Consider add more detail to function argument descripions. It is not clear to me what all the arguments should be.
	- **✅Response**: We have updated the argument descripions of some main functions, for example:
```r
#' @title Plot phylomorphospace
#'
#' @description This function plots a phylomorphospace by mapping a tree
#' object onto a vector space like morphospace.
#' @param tr a tree object. This should be an object of class that is 
#'           compatible with `ggtree`, typically an object of class 
#'           `phylo` or `treedata`.
#' @param data Trait data as a data frame or matrix, where each row 
#' represents a tree tip or node. 
#' 
#'   For data matching the number of tips, ancestral traits are reconstructed 
#'   for internal nodes. 
#'   
#'   For data equal to the total number of nodes, values are directly used as 
#'   node coordinates.
#' @param mapping aesthetic mapping
#' @param ... additional parameters for customization with `ggtree`
```

- ⚠️ If function arguments include ... then it should be clear in the description how additional arguments are used.
	- **✅Response**: We have enriched the description of function arguments that include ... , for example:
```r
#' @param ... additional parameters for customization with `ggtree`. Please 
#' use `?ggtree::ggtree` fot more information.
```

- ⚠️ Consider adding validity checks to function arguments
	- **✅Response**: We have added validity checks to function arguments in main functions.

- 🟢 I think you have included global variables to avoid check warnings but it may be possible to avoid these in other ways
	- **✅Response**: We have fixed this issue.

- 🚨 The aes_string() function from the **{ggplot2}** function is deprecated and should not be used. Please see the ["Using ggplot2 in packages"](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html) and ["Extending ggplot2"](https://ggplot2.tidyverse.org/articles/extending-ggplot2.html) guides for alternatives.
	- **✅Response**: We have fixed this issue.

- ❓ The functions in this package seem to be minimal wrappers around **{ggtree}** and other packages. Can you please explain what you think the main added value of this package is?
	- **✅Response**:  While this package indeed serves as a wrapper around the {ggtree} and other related packages, its primary value lies in significantly simplifying the process for users unfamiliar with the underlying structure of {ggtree}. This simplification enables users to efficiently generate phylomorphospace visualizations without delving into the complexities of {ggtree}. Additionally, {ggtreeSpace} serves as a foundational package. In forthcoming updates, we plan to introduce more graphical layers specifically designed for phylomorphospace annotation, thereby enriching the package's capabilities for the community.

**Comment by lazappi** [comment]
> * ⚠️ Ther are some BiocCheck notes in the build report, please check these and address them if necessary
>   
>   * **✅Response**: We have addressed some of the notes by enriching the `Description` section in the _DESCRIPTION_ file and shortening the code lines. However, some notes, such as those regarding function length, require significant code restructuring. We plan to tackle these in forthcoming updates. Many thanks for your valuable suggestions.

There seems to be an issue with the build reports at the moment so I can't check this but sounds like you have addressed this.
 
> * 🚨 Please add an _Installation_ section that:
>   
>   1. Uses Bioconductor installation instructions
>   2. Installation code is not evaluated
>   
>   
>   * **✅Response**: We have added an _Installation_ section in the vignette. Thanks for the tip.

I think this usually goes after the introduction section but it probably doesn't matter too much. It would be nice to have a bit of text to go with the code though.

> * 🚨 You only need to load libraries once at the start of the document, not in every chunk
>   
>   * **✅Response**: We have fixed this by loading libraries only at the start. Grateful for your keen observations.

Please do this in a separate chunk with `include = TRUE` so it is visible to the reader.

**Additional point:** Please don't disable warnings in the vignette so that the output matches what users will see.
  
> * ⚠️ Consider add more detail to function argument descripions. It is not clear to me what all the arguments should be.
>   
>   * **✅Response**: We have updated the argument descripions of some main functions, for example:

Please do this for all exported function, some arguments are still missing descriptions

> * ⚠️ If function arguments include ... then it should be clear in the description how additional arguments are used.
>   
>   * **✅Response**: We have enriched the description of function arguments that include ... , for example:
> 
> ```r
> #' @param ... additional parameters for customization with `ggtree`. Please 
> #' use `?ggtree::ggtree` fot more information.
> ```

This is also missing in some places (e.g. `ggTreeSpace()`)

> * ❓ The functions in this package seem to be minimal wrappers around **{ggtree}** and other packages. Can you please explain what you think the main added value of this package is?
>   
>   * **✅Response**:  While this package indeed serves as a wrapper around the {ggtree} and other related packages, its primary value lies in significantly simplifying the process for users unfamiliar with the underlying structure of {ggtree}. This simplification enables users to efficiently generate phylomorphospace visualizations without delving into the complexities of {ggtree}. Additionally, {ggtreeSpace} serves as a foundational package. In forthcoming updates, we plan to introduce more graphical layers specifically designed for phylomorphospace annotation, thereby enriching the package's capabilities for the community.

Ok. It would be good to cover this in the vignette, maybe by showing an example comparing doing something manually with **{ggtree}** and your package.

**Additional comments:**

- You assign a class to the output of the `phylospm()` function but I'm not sure what purpose this has as it doesn't seem to be reused anywhere and there are no functions/methods for this class.

**Comment by GuangchuangYu** [comment]
Thank you very much for your thorough review. Below is our response to the feedback provided.

> - ⚠️ Ther are some BiocCheck notes in the build report, please check these and address them if necessary
>     
>     - **✅Response**: We have addressed some of the notes by enriching the `Description` section in the _DESCRIPTION_ file and shortening the code lines. However, some notes, such as those regarding function length, require significant code restructuring. We plan to tackle these in forthcoming updates. Many thanks for your valuable suggestions.

There seems to be an issue with the build reports at the moment so I can't check this but sounds like you have addressed this.

>  - 🚨 Please add an _Installation_ section that:
>     
>     1. Uses Bioconductor installation instructions
>     2. Installation code is not evaluated
>     
>     - **✅Response**: We have added an _Installation_ section in the vignette. Thanks for the tip.

I think this usually goes after the introduction section but it probably doesn't matter too much. It would be nice to have a bit of text to go with the code though.

- **✅Response**: We have moved this section after the introduction section, and added some text. Thank you for pointing this out.

> - 🚨 You only need to load libraries once at the start of the document, not in every chunk
>     
>     - **✅Response**: We have fixed this by loading libraries only at the start. Grateful for your keen observations.

Please do this in a separate chunk with `include = TRUE` so it is visible to the reader.

- **✅Response**: We have fixed this issue.

**Additional point:** Please don't disable warnings in the vignette so that the output matches what users will see.
- **✅Response**: We have fixed this issue.

> - ⚠️ Consider add more detail to function argument descripions. It is not clear to me what all the arguments should be.
>     
>     - **✅Response**: We have updated the argument descripions of some main functions, for example:

Please do this for all exported function, some arguments are still missing descriptions

- **✅Response**: I apologize for the oversight. We have reviewed and updated the descriptions for all exported function arguments. We have ensured that no exported function argument is left undocumented.

> - ⚠️ If function arguments include ... then it should be clear in the description how additional arguments are used.
>     
>     - **✅Response**: We have enriched the description of function arguments that include ... , for example:
> 
> ```r
> #' @param ... additional parameters for customization with `ggtree`. Please 
> #' use `?ggtree::ggtree` fot more information.
> ```

This is also missing in some places (e.g. `ggTreeSpace()`)

- **✅Response**: I'm sorry but we have reviewed our package and found no `...` parameters undocumented. Could you please specify where you found them missing? Thank you for your patience.

> - ❓ The functions in this package seem to be minimal wrappers around **{ggtree}** and other packages. Can you please explain what you think the main added value of this package is?
>     
>     - **✅Response**: While this package indeed serves as a wrapper around the {ggtree} and other related packages, its primary value lies in significantly simplifying the process for users unfamiliar with the underlying structure of {ggtree}. This simplification enables users to efficiently generate phylomorphospace visualizations without delving into the complexities of {ggtree}. Additionally, {ggtreeSpace} serves as a foundational package. In forthcoming updates, we plan to introduce more graphical layers specifically designed for phylomorphospace annotation, thereby enriching the package's capabilities for the community.

Ok. It would be good to cover this in the vignette, maybe by showing an example comparing doing something manually with **{ggtree}** and your package.

- **✅Response**: We have added the corresponding content in the vignette. Thank you for your 

**Additional comments:**

- You assign a class to the output of the `phylospm()` function but I'm not sure what purpose this has as it doesn't seem to be reused anywhere and there are no functions/methods for this class.

- **✅Response**: We have removed the class assignment.

**Comment by lazappi** [comment]
Thanks for your replies, I have one more comment. The `%<+%` operator is not commonly used (I'm not even sure what it does) so I would avoid using it in the vignette.

This is only minor though, and we are close to the deadline so I will accept this package as is and trust you to make this change.

**Comment by lazappi** [comment]
Congratulations on getting **{ggtreeSpace}** accepted into Bioconductor 🎉! It can take a few days to be picked up by the build system but then it should be available in Bioconductor devel and the next release.

**Comment by GuangchuangYu** [comment]
This operator was defined in {**ggtree**} package for more than 8 years and it is widely used in {**ggtree**} and derived packages.  I think there is no need to change it. We will add references to it.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GuangchuangYu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggtreeSpace")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggtreeSpace

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
