### ISSUE TITLE
NOMAD

### ISSUE THREAD

**Issue by carlmurie** [Bioconductor/Contributions#336]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/carlmurie/NOMAD

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@LiNk-NY will review this package, but it's surprising that it makes no use of other Bioconductor packages or best practices.

It seems like your data is frequently a data.frame (confusingly described as a \code{vector} and 'matrix' in the documentation) with specific columns. Rather than checking for this repeatedly, it makes much more sense to create an S4 class and validity method that ensures, in one place so guaranteeing consistency, that the data is correctly formatted.

A big part of Bioconductor is interoperability with other software packages with similar functionality. Often this is enhanced by using data representations defined in other packages. So maybe you don't need to re-invent a class, but instead can identify other packages that define similar representations and re-use them.

**Comment by LiNk-NY** [comment]
Hi @carlmurie, 
Any thoughts about moving forward with the comment above? 

Regards,
Marcel

**Comment by carlmurie** [comment]
Hi,

Yes, I could convert the data.frame to an S4 object. Maybe I misunderstood
but I thought that a reviewer was going to look at the package and make
recommendations. I was going to wait for that before I started modifying
the code.

Carl

**Comment by LiNk-NY** [comment]
Hi Carl, 

Yes, you can use an S4 class to represent your data and include validity checks. You should also look at what is available in Bioconductor for this type of data and reuse existing software.

Interoperability is a major factor in our review process and we want to ensure that your package is working well with the Bioconductor infrastructure before the review process. 
Otherwise, we'd be reviewing all non-Bioconductor packages submitted. Thank you. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Your issue has been closed due to inactivity. To submit your revised package to Bioconductor, please create another issue. Thank you. 
-Marcel
