### ISSUE TITLE
smartid

### ISSUE THREAD

**Issue by Gene233** [Bioconductor/Contributions#3360]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DavisLaboratory/smartid

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Gene233** [comment]
The warnings should be OK. There is only one warning in the build report `WARNING: R CMD check exceeded 10 min requirement`. But what I changed is just to add some tests for some functions. And the tests can be done within 1 min on my own PC.

I also did the same check on my own PC and on github actions, both indicating the duration is less than 10 mins.  So I suppose this was caused by some random effects and should be fine for a new buiding.

**Comment by HelenaLC** [comment]
Yeah, also not sure what happened there - proceeding with review for now. First round of comments below. Please respond back with what has/not been addressed how/why not and, of course, any questions you might have - cheers!

- in general, please address the NOTES in the build report to the best of your abilities; many of the points below are just a reiteration of those, and most of them are only acceptable in exceptional cases.

- also, consider having a look at the code-style guidelines [here](https://contributions.bioconductor.org/r-code.html#coding-style) - e.g., 4-space tab indentation, not vertical alignment; spaces around logical operators and after comma, not argument equals etc. - although we don't enforce these, we appreciate consistency (with your own style at least)

# misc

- in the README, please add Bioc installation instructions using `BiocManager::install()`

- related to that, for release, please drop `devtools` installation instructions from the vignette

- in the DESCRIPTION, please bump R version dependency to >= 4.4

- in the DESCRIPTION, `LazyData:` should be set to `false` or removed

- in the DESCRIPTION, the `Description:` states "TF-IDF modified methods", however, not everyone browsing packages might be familiar with that acronym (e.g., I had to look it up); please spell that out once

- any classes declared by a package should go under `AllClasses.R`; i.e., renaming `objects.R` resolves this

# docs

- at the core of the package are TF, IDF and IAE, however, I only see a one-liner in the vignette line 117 explaining these, which is rather confusing and missing from the R documentation... maybe spelling this out a little more/different phrasing could help, e.g., "inverse cell frequency" and "average expression" aren't clear to me at all, although I work with single-cell data - per label/group? across everything?; and, "similar to CPM" - meaning what exactly? There are some commented out math-chunks in various scripts - what's happened to those? - though a verbal explanation would already help a lot (in both the R docs and vignette)!

- related, `?calc_sco`, `?tf`, `?idf`, `iae` spell out acronyms but don't describe the computation (e.g., under details) and output structure (under return value) etc.

- vignette typos/spelling/grammar
  - line 35: specifc -> specific
  - line 111: expectatiion -> expectation
  - line 145: im-balanced -> imbalanced
  - line 170: this gene's -> this genes
  - line 270: tranform -> transform

- for readability, I'd suggest using math-style at line 119 and 243 (and possibly others I missed), i.e., wrapping the computation with single `$`s in the text (`$$` yields centered, out-of line math as already done correctly; `$` is for in-line math mode)

- consider hyperlinking external packages using, e.g., `BiocStyle::Biocpkg("splatter")` (similar functions are available for packages hosted on CRAN and GitHub)

- very minor, but "smartid" is sometimes in plain text, once bold, and usually in code-style; would be nice to be consistent here

- for clarity, might be worth considering to use `function()` when something is a function (e.g., `markers_mclust()`) and `variable/argument/slot` when it is not (e.g., `top_m`, `GeneMean`)

# code

- please do not use `@` for data retrieval and use the corresponding accessor methods instead, e.g., `metadata()` not `x@metadata` -- everywhere (also the vignette) -- and the same goes for assignments, e.g., `metadata(x)$a <- b` not `x@metadata$a <- b`

- commented out code should be removed for release (see, e.g., `select_markers.R`, `scale_mgm.R`, `iae_hdb()` etc.)

- when subsetting matrices for downstream computations that expect a matrix still, one should always use `x[i, j, drop=FALSE]`; else, subsetting single rows/columns will return a vector instead, causing failure (see, e.g., `idf_prob()` but it's all over the place)

- use `vapply()` instead of `sapply()` (e.g., `tf_idf_iae_wrapper.R`) - see [here](https://contributions.bioconductor.org/r-code.html?q=vapply#code-syntax-and-efficiency) and also the build report - perhaps worth doing a package-wide search (shift+command+F on my Mac) for any `sapply`s

**Comment by Gene233** [comment]
> Yeah, also not sure what happened there - proceeding with review for now. First round of comments below. Please respond back with what has/not been addressed how/why not and, of course, any questions you might have - cheers!
> 
> * in general, please address the NOTES in the build report to the best of your abilities; many of the points below are just a reiteration of those, and most of them are only acceptable in exceptional cases.
> * also, consider having a look at the code-style guidelines [here](https://contributions.bioconductor.org/r-code.html#coding-style) - e.g., 4-space tab indentation, not vertical alignment; spaces around logical operators and after comma, not argument equals etc. - although we don't enforce these, we appreciate consistency (with your own style at least)
> 
> # misc
> * in the README, please add Bioc installation instructions using `BiocManager::install()`
> * related to that, for release, please drop `devtools` installation instructions from the vignette
> * in the DESCRIPTION, please bump R version dependency to >= 4.4
> * in the DESCRIPTION, `LazyData:` should be set to `false` or removed
> * in the DESCRIPTION, the `Description:` states "TF-IDF modified methods", however, not everyone browsing packages might be familiar with that acronym (e.g., I had to look it up); please spell that out once
> * any classes declared by a package should go under `AllClasses.R`; i.e., renaming `objects.R` resolves this
> 
> # docs
> * at the core of the package are TF, IDF and IAE, however, I only see a one-liner in the vignette line 117 explaining these, which is rather confusing and missing from the R documentation... maybe spelling this out a little more/different phrasing could help, e.g., "inverse cell frequency" and "average expression" aren't clear to me at all, although I work with single-cell data - per label/group? across everything?; and, "similar to CPM" - meaning what exactly? There are some commented out math-chunks in various scripts - what's happened to those? - though a verbal explanation would already help a lot (in both the R docs and vignette)!
> * related, `?calc_sco`, `?tf`, `?idf`, `iae` spell out acronyms but don't describe the computation (e.g., under details) and output structure (under return value) etc.
> * vignette typos/spelling/grammar
>   
>   * line 35: specifc -> specific
>   * line 111: expectatiion -> expectation
>   * line 145: im-balanced -> imbalanced
>   * line 170: this gene's -> this genes
>   * line 270: tranform -> transform
> * for readability, I'd suggest using math-style at line 119 and 243 (and possibly others I missed), i.e., wrapping the computation with single `$`s in the text (`$$` yields centered, out-of line math as already done correctly; `$` is for in-line math mode)
> * consider hyperlinking external packages using, e.g., `BiocStyle::Biocpkg("splatter")` (similar functions are available for packages hosted on CRAN and GitHub)
> * very minor, but "smartid" is sometimes in plain text, once bold, and usually in code-style; would be nice to be consistent here
> * for clarity, might be worth considering to use `function()` when something is a function (e.g., `markers_mclust()`) and `variable/argument/slot` when it is not (e.g., `top_m`, `GeneMean`)
> 
> # code
> * please do not use `@` for data retrieval and use the corresponding accessor methods instead, e.g., `metadata()` not `x@metadata` -- everywhere (also the vignette) -- and the same goes for assignments, e.g., `metadata(x)$a <- b` not `x@metadata$a <- b`
> * commented out code should be removed for release (see, e.g., `select_markers.R`, `scale_mgm.R`, `iae_hdb()` etc.)
> * when subsetting matrices for downstream computations that expect a matrix still, one should always use `x[i, j, drop=FALSE]`; else, subsetting single rows/columns will return a vector instead, causing failure (see, e.g., `idf_prob()` but it's all over the place)
> * use `vapply()` instead of `sapply()` (e.g., `tf_idf_iae_wrapper.R`) - see [here](https://contributions.bioconductor.org/r-code.html?q=vapply#code-syntax-and-efficiency) and also the build report - perhaps worth doing a package-wide search (shift+command+F on my Mac) for any `sapply`s

Hi @HelenaLC , thank you very much for your quick response and detailed advice. I've updated based on your suggestions. Here're the details:

- in general, fixed notes as many as possible.
- [x] set false for 'LazyData' in the 'DESCRIPTION'.
- [x] Update R version dependency from 4.3 to 4.4.
- [x] Replace sapply with vapply.
- [x] Replace print() with show().
- [x] Use function instead of accessors `@`.
- code-style, used styler to tidy the code-style.

# misc
- [x] add Bioc installation instructions in README.
- [x] drop `devtools` installation instructions from the vignette.
- [x] bump R version.
- [x] set false for `LazyData`.
- [x] spell TF-IDF out in DESCRIPTION.
- [x] rename `objects.R` as `AllClasses.R`.

# docs
- [x] add details for TF, IDF and IAE in details of functions and vignette.
- [x] fix the typo/grammer/spelling in the vignette.
- [x] use single `$`s instead of `$$`s in the text.
- [x] add hyperlink for external packages.
- [x] keep "smartid" consistent as code-style in vignette.
- [x] use `function()` for real functions and `variable/argument...` for  non-functions.

# code
- [x] replace accessors `@` with functions.
- [x] removed some commented codes, the rest remaining commented codes will be updated in the future for some extra functions (e.g. threshold for IDF/IAE offset).
- [x] add drop=FALSE when subsetting matrices.
- [x] use `vapply()` instead of `sapply()`.

# Summary
These are my updates in response to your feedback, and I'm glad to discuss specific details of the changes with you.

Cheers,
Jinjin

**Comment by HelenaLC** [comment]
Thanks a lot - build report is very clean now and I appreciate the extended documentation on the three terms! 
- [ ] typo in the email address at `smartid-package.R` line 18.
- [ ] couple instances of `@` left (`sim_sce_test.R` line 25 and `test-gs_score.R` line 27)
- [ ] please add definition of symbols in the corresponding man pages as well (as you did in the vignette), e.g., `?iae` has a formula but doesn't say what $n,i,j,\hat{N}_{ij}$ are
- [ ] vignette lines 116+ are formatted rather weirdly (see screenshot)
  - using `$$ ... $$` will display centered, out-of-line math, which I would display more nicely/readable equations here
  - au contraire, `$ ... $` should rather be used for brief in-line math (e.g., "where $N_{ij}$ is [...]")
  - perhaps worth rendering the vignette yourself and seeing how things are being rendered outside of RStudio (in the html)
![image](https://github.com/Bioconductor/Contributions/assets/14542264/1383f795-b805-4186-a102-d0629bd97cf3)

**Comment by Gene233** [comment]
> Thanks a lot - build report is very clean now and I appreciate the extended documentation on the three terms!
> 
> * [x]  typo in the email address at `smartid-package.R` line 18.
> * [x]  couple instances of `@` left (`sim_sce_test.R` line 25 and `test-gs_score.R` line 27)
> * [x]  please add definition of symbols in the corresponding man pages as well (as you did in the vignette), e.g., `?iae` has a formula but doesn't say what n,i,j,N^ij are
> * [x]  vignette lines 116+ are formatted rather weirdly (see screenshot)
>   
>   * using `$$ ... $$` will display centered, out-of-line math, which I would display more nicely/readable equations here
>   * au contraire, `$ ... $` should rather be used for brief in-line math (e.g., "where Nij is [...]")
>   * perhaps worth rendering the vignette yourself and seeing how things are being rendered outside of RStudio (in the html)
>     ![image](https://github.com/Bioconductor/Contributions/assets/14542264/1383f795-b805-4186-a102-d0629bd97cf3)

Hi @HelenaLC , thank you for your always quick response. I did update what you mentioned above, i.e. fix email adress in `smartid-package.R`, replace `@` in test files and data scripts, add definition of symbols in details, and update equation formats in the vignette.

Hope this looks better now.

Cheers,
Jinjin

**Comment by HelenaLC** [comment]
much improved, thanks

**Comment by Gene233** [comment]
@HelenaLC Thank you so much for your patience and helpful advice to improve my package!

Cheers,
Jinjin

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Gene233.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("smartid")`. The package 'landing page' will be created at

https://bioconductor.org/packages/smartid

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
