### ISSUE TITLE
pwalign

### ISSUE THREAD

**Issue by hpages** [Bioconductor/Contributions#3361]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/pwalign

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
**pwalign** contains the `pairwiseAlignment`-related stuff taken from **Biostrings**. The plan is to deprecate this stuff in **Biostrings** (in BioC 3.19), and to redirect the user to the stuff that is now in **pwalign**. Then to defunct it in **Biostrings** (in BioC 3.20), and to finally remove it from **Biostrings** (in BioC 3.21).

The motivations for this split are:
- **Biostrings** is too big and hard to maintain. In particular, the `pairwiseAlignments`-related stuff in it adds a lot of complexity to the package (via additional specialized classes, generics, and methods, and a lot of complex C code to support them). This split will make **Biostrings** about 20% smaller. This in turn will make its maintenance easier and will also make `R CMD check` slightly faster.
- About 500 Bioconductor packages depend on **Biostrings**. However, very few of them need the `pairwiseAlignment` functionality. So this split won't affect most of **Biostrings** revdeps. However they will now depend on a lighter  **Biostrings** that will be slightly faster to install (faster to download, compile, and load).
- Separation of responsibilities: The plan is for Aidan Lakshman (@ahl27) to take over maintenance of **Biostrings** in the near future while I'll remain the maintainer of **pwalign**. This split will remove the burden of maintaining the `pairwiseAlignment`-related stuff from Aidan's plate.

H.

**Comment by lshep** [comment]
I can pass this into building the reports however it will fail until the latest version of Biostrings is available.

**Comment by hpages** [comment]
**Biostrings** 2.71.5 (latest version) is already on nebbiolo1 so we should be good to go.

**Comment by lshep** [comment]
It has not propagated yet https://bioconductor.org/checkResults/devel/bioc-LATEST/Biostrings/

**Comment by hpages** [comment]
It doesn't need to. It's on the machine.

**Comment by hpages** [comment]
The 2 WARNINGs were expected.

One is about using RMarkdown instead of Sweave for the vignette. Note that the vignette was just taken from **Biostrings** and put in **pwalign**. You can see it [here](https://bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/PairwiseAlignments.pdf). It was written a long time ago by Patrick Aboyoun, the original author of the `pairwiseAlignment` stuff. Since it contains a lot of mathematical formulae that would be tricky to translate to markdown, I don't intend to make the conversion, at least not for now.

The other WARNING is about "Empty or missing \value sections found in man pages.". This is a false positive that I reported [here](https://github.com/Bioconductor/BiocCheck/issues/211) yesterday.

Let me know if you have questions.

H.

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 

Thank you for your submission. 
Please see the review below.

Best regards,
Marcel

---

# pwalign

* Overall, the package is great for pairwise alignment and calculating
string distance matrices. The code seems to be robust but some unit tests
can still increase the coverage. It seems that the `useMpi` functionality is
in question. I mostly provided minor notes given that this code is
established and ported over from `Biostrings`.

## DESCRIPTION

* Note that `LazyLoad` field is now ignored. The replacement `LazyData` should
be set to `false` or not included. Users should use `data(...)` to load a
dataset rather than have them in the `.GlobalEnv`.

## NAMESPACE

* Looks good.

## vignettes

* Consider converting the `Rnw` file to `Rmd`.
* Looks good.

## R

* `RTobjs` does not seem to be used anywhere, consider its removal.
* __Minor__: Consider reducing cyclomatic complexity by simply coercing type
rather than checking and coercing, e.g. in
`mismatchSummary,AlignedXStringSet0-method` (and others),

```r
weight <- as.integer(weight)

## instead of

if (!is.integer(weight))
    weight <- as.integer(weight)

```
* Minor: To avoid repetition, perhaps use a default
`compareStrings,ANY,ANY-method` to coerce both `pattern` and `subject` inputs
to character and dispatch to the `compareStrings,character,character-method`

```r
setMethod("compareStrings",
          signature = c(pattern = "ANY", subject = "ANY"),
          function(pattern, subject) {
              compareStrings(as.character(pattern), as.character(subject))
          })
```
* It looks like `useMpi` is disabled. Will it work again or should it be
removed?
* The arguments should list all possible options e.g., in `stringDist` the
default `method` argument should be the vector of possibilities i.e.,
`c("levenshtein", "hamming", "quality", "substitutionMatrix")` and `match.arg`
will ensure that one of them is selected
* Consider promoting functions from `Biostrings` to exported functions rather
than using `:::` (in `R/utils.R`).

## tests

* Consider increasing the coverage of some files like
`AlignedXStringSet-class.R`:

```r
> covr::package_coverage(type = "all")
pwalign Coverage: 76.46%
R/AlignedXStringSet-class.R: 0.00%
R/align-utils.R: 38.89%
R/PairwiseAlignmentsSingleSubject-class.R: 39.22%
R/pairwiseAlignment.R: 49.49%
R/zzz.R: 50.00%
R/00datacache.R: 66.67%
R/stringDist.R: 71.76%
R/PairwiseAlignments-class.R: 72.22%
R/PairwiseAlignments-io.R: 86.01%
R/substitution_matrices.R: 87.76%
src/align_pairwiseAlignment.c: 89.47%
src/align_utils.c: 99.48%
R/InDel-class.R: 100.00%
src/R_init_pairwiseAlignment.c: 100.00%
```

**Comment by hpages** [comment]
Thanks Marcel for the feedback.

> Note that `LazyLoad` field is now ignored. 

Removed.

> Consider converting the `Rnw` file to `Rmd`.

See my previous comment from 2 weeks ago above.

> `RTobjs` does not seem to be used anywhere, consider its removal.

Removed.

> ```
> if (x is not the thing we want)
>      x <- turn_x_into_the_thing_we_want(x)
> ```

I prefer that idiom over an unconditional `x <- turn_x_into_the_thing_we_want(x)`. That's because even if `x` is already the thing we want, sadly `turn_x_into_the_thing_we_want()` is not guaranteed to be a no-op. For example `as.character(x)` will drop the names of character vector `x`, and `as(x, "A")` might transform `x` even if `is(x, "A")` is `TRUE`. It might matter (e.g. when the object is big and `turn_x_into_the_thing_we_want(x)` triggers a copy) or not (like here).

FWIW this has hit me a few times in the past so I got into the habit of _systematically_ using the `if (x is not the thing we want) x <- turn_x_into_the_thing_we_want(x)` idiom without even thinking about it.

> Minor: To avoid repetition, perhaps use a default `compareStrings,ANY,ANY-method` etc...

I simplified the `compareStrings()` methods a bit. Minor disavantage of a `compareStrings,ANY,ANY-method` that blindly coerces anything you throw at it to character is that it might do some weird/unexpected things for some exotic stuff. And the error that will result in that case will probably not be of great help to the end user.

> It looks like `useMpi` is disabled. Will it work again or should it be removed?

I disabled this. **Rmpi** has been in `Enhances` (as opposed to `Suggests`) for the last 15 years or so, and the way things are implemented in `pairwiseAlignments()` is that it will be used only if the user _explicitly_ loads it before calling the function. This means that the `useMpi` mode has not been tested on the daily builds for the last 15 years. Furthermore, since this is an undocumented feature, I suppose that nobody has ever used it, except Patrick. Last but not least: it's not covered by the unit tests either.

I might re-enable it at some point in the not too distant future but some serious testing will be required first. Also, this predates **BiocParallel** so the **Rmpi** approach might be completely obsolete, I don't know. Will need to revisit, test, assess, and decide what to do with it.

Disclaimer: I've never used **Rmpi** myself (Patrick Aboyoun implemented this) .

> The arguments should list all possible options e.g., in `stringDist()`

Usually yes. I think maybe the reason Patrick didn't do it in this case is that the list of all possible values for the `method` argument is a little bit long (`c("levenshtein", "hamming", "quality", "substitutionMatrix")`) so it could be ugly to see such a long list in the definition of the S4 generic and all its methods, especially in the `\usage` section of the man page. Also maybe not all the `stringDist()` methods might support all these options at the moment, or future methods might want to support different options.
As long as the man page for `stringDist()` lists all the supported `method`'s I can live with that.

> Consider promoting functions from Biostrings to exported functions rather than using `:::`

My understanding is that this is acceptable when the upstream and client packages have the same maintainer, which is why `R CMD check` doesn't say anything in that case.

H.

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 
Thanks for making those changes.
The package has been accepted. 
Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpages.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pwalign")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pwalign

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
