### ISSUE TITLE
omicRexposome

### ISSUE THREAD

**Issue by carleshf** [Bioconductor/Contributions#337]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isglobal-brge/omicRexposome

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
The Description: field is incomplete and the vignette contains a few commands with little text -- are you sure your package is ready for submission?

**Comment by carleshf** [comment]
I've just pushed several changes (+ version bump) according to this last comment.

**Comment by carleshf** [comment]
Dear @mtmorgan ,

I do not understand what is happening here. As you can see, the webhood is properly set:

![image](https://cloud.githubusercontent.com/assets/2046180/25179131/d50b64cc-2508-11e7-92d6-e94e485ce5eb.png)

But any one of the commits done to the repository has an effect in this issue. What can I do?

C.

**Comment by mtmorgan** [comment]
I think the package was still in the 'waiting moderation' stage so that the commits were being ignored. It should build now.

**Comment by mtmorgan** [comment]
Sorry for my very slow review

DESCRIPTION, NAMESPACE

- Spell check this and all documents.
- For the Description: field, provide a more extensive description of
  what the package does. Mention if there are other similar packages.
- Review the biocViews terms, for instance 'tatisticalMethod' is not a
  term.

vignette

- generally good
- No need for the html version of the vignette to be under version
  control; remove it.
- Use standard _Biocondcutor_ installation instructions rather than
  devtools; biocLite() installs dependencies so update this sentence.
- include a final code chunk with `sessionInfo()`.

R

- Biobase::ExpressionSet() is being replaced by
  [SummarizedExperiment][]; consider updating your code to accept
  either.
- spell check warning and error messages, e.g., 'No samles in common...'
- avoid using `@` for slot access; write (internal-only) plain-old
  functions as accessors.
- avoid highly nested calls, e.g., 

    ```
    res <- data.frame(do.call(rbind, lapply(1:length(names(object)), function(ii) {
    ```
    
  which are hard to read and debug.


data / extdata

- the size of the data objects mean that the package exceeds
  Biocondcutor [guidelines][] (package size no more than 4MB); create
  more modes example data or separate the data as an Experiment data
  package (with vignette) and add as an '[Additional package][]'
- verify that the data in inst/extdata is actually used in your package

[guidelines]: http://bioconductor.org/developers/package-guidelines/#correctness
[Additional package]: https://github.com/Bioconductor/Contributions#submitting-related-packages

man

- provide more extensive documentation for the `exp_r`, `gexp_r`, and
  other data objects, indicating what data it represents, how it was
  created, what the most important features of it are.

[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by mtmorgan** [comment]
Looks like your package is not building; so I take it this is still a work in progress...?

**Comment by carleshf** [comment]
Dear @mtmorgan ,

I'm currently working on the `rexposome` review (that is a bit extensive). Since `rexposome` is a dependence of `omicRexposome` (and I'm moving some function from one to the other) I thin that is better if I finish the changes on `rexposome` before going to `omicRexposome`. Is it fine?

**Comment by mtmorgan** [comment]
Yes, please be sure when your revisions to omicRexposome are complete to post a summary here, so that I know to continue my review.

**Comment by carleshf** [comment]
AdditionalPackage: https://github.com/isglobal-brge/brgedata

**Comment by carleshf** [comment]
AdditionalPackage: https://github.com/isglobal-brge/brgedata

**Comment by carleshf** [comment]
Dear @mtmorgan ,

We are having some troubles to understand what is happening with the additional experimental package. We have seen in the build-report that `PackageFileSize: -1.00 KiB`. This is strange since it contains several completed omic data-sets. 

We used the `lfs` feature from GitHub to store this package, could this be the root of the problem? If yes, can you provide us with instructions to properly deploy the package in Bioconductor's testing servers?

Kind regards,
C.

**Comment by mtmorgan** [comment]
Yes this looks like a problem on our end; we'll investigate.

**Comment by mtmorgan** [comment]
Can you please increment the version of your package, to trigger a new build?

**Comment by mtmorgan** [comment]
remember that only CRAN and Bioconductor dependencies are allowed.

**Comment by carleshf** [comment]
Dear @mtmorgan,


Follows my comments on `omicRexposome`review (also about the last fail in the build).


# DESCRIPTION, NAMESPACE

  * Spell check this and all documents.

I spell checked all the documents.

  * For the Description: field, provide a more extensive description of what the package does. Mention if there are other similar packages. Review the biocViews terms, for instance 'tatisticalMethod' is not a term.

I updated the *description* of the package. Follows current one:

> omicRexposome systematizes the association evaluation between exposures and omic data, taking advantage of MultiDataSet for coordinated data management, rexposome for exposome data definition and limma for association testing. Also to perform data integration mixing exposome and omic data using multi co-inherent analysis (omicade4) and multi-canonical correlation analysis (PMA).

I also updated the `biocViews` section. The new selected terms are: `WorkflowStep`, `MultipleComparison`, `Visualization`, `GeneExpression`, `DifferentialExpression`,  `DifferentialMethylation`, `GeneRegulation`, `Epigenetics`, `Proteomics`, `Transcriptomics`, `StatisticalMethod`, `Regression`

# vignette

  * generally good
  * No need for the html version of the vignette to be under version control; remove it.

The HTML version was removed.

 * Use standard Bioconductor installation instructions rather than `devtools`; `biocLite()` installs dependencies so update this sentence. include a final code chunk with `sessionInfo()`.

I do not know the time where I should change from `devtools` to `biocLite` since the package is still in *ISGlobal* GitHub repository.

As you suggested I change this line.

I also added the `sessionInfo()` at the end of the vignette.

# R

  * `Biobase::ExpressionSet()` is being replaced by `SummarizedExperiment`; consider updating your code to accept either.

Changed `assocES` to `association` and updated `crossomics` Now they work on `MultiDataSet` objects, that can store both `eSet`-like and `SummarizedExperiment`-like objects.

  * spell check warning and error messages, e.g., 'No samles in common...'

I think I spell checked all the messages and warnings.

  * avoid using @ for slot access; write (internal-only) plain-old functions as accessors.

As suggested I removed most all used of `@`. I keep three:

 1. I keep one occurrence in `getIntegration`, since its usage is in the implementation of a getter.
 2. Two occurrences in the two integration methods that ensure the name of a list stored in `ResultSet`. 

  * avoid highly nested calls, e.g.,
  ```
  res <- data.frame(do.call(rbind, lapply(1:length(names(object)), function(ii) {
  ```
  which are hard to read and debug.

I updated some functions to avoid this *highly nested* calls: `plot_integration_mcca` and `snpToContinuous`.

# data / extdata

  * The size of the data objects mean that the package exceeds Biocondcutor guidelines (package size no more than 4MB); create more modes example data or separate the data as an Experiment data package (with vignette) and add as an 'Additional package' verify that the data in `inst/extdata` is actually used in your package

We have created an experiment package called `BRGEdata` that contains the different omic data-sets and the exposome-set used by `omicRexosome` and `MEAL` package.

Then three new objects were created and save in `omicRexposome`, to be used in methods' examples.

# man

    provide more extensive documentation for the exp_r, gexp_r, and
    other data objects, indicating what data it represents, how it was
    created, what the most important features of it are.

All the data-sets were removed and moved to `BRGEdata` experimental data package. Unfortunately, I still don't know how to properly link the LFS repository to this issue.

Then minimal data-sets were generated and included in `omicRexposome` (`asr`, `mds`, `crs`) for example purposes.

# Checks

Result of R CMD check

```#
R CMD check results
0 errors | 1 warning  | 0 notes

R CMD check succeeded
```

**Comment by mtmorgan** [comment]
I think the lfs issue on our end is solved, and the the data package requires a version bump.

**Comment by mtmorgan** [comment]
Not sure where we stand on this? I think BRGEdata needs a version bump to trigger a build.

**Comment by mtmorgan** [comment]
Any update, or shall I close this issue?

**Comment by carleshf** [comment]
Dear @mtmorgan ,

I updated the `BRGEdata` package, making it a bit less heavy. but, unfortunately, I think it sill not being clone properly. 

When looking at the build report I see that its size is -1.00 KiB:

```
Package: brgedata
--
Version: 0.99.3
RVersion: 3.4
BiocVersion: 3.6
BuildCommand: /Library/Frameworks/R.framework/Versions/Current/Resources/bin/R CMD build --keep-empty-dirs --no-resave-data brgedata
BuildTime: 4 minutes 37.84 seconds
CheckCommand: /Library/Frameworks/R.framework/Versions/Current/Resources/bin/R  CMD check --no-vignettes --timings  --no-multiarch  None  &&   /Library/Frameworks/R.framework/Versions/Current/Resources/bin/R CMD  BiocCheck --build-output-file=R.out --new-package None
CheckTime: 0 minutes 0.39 seconds
BuildBinCommand: /Users/pkgbuild/packagebuilder/workers/build-universal.sh None libdir
BuildBinTime: 0 minutes 0.81 seconds
Status: skipped
PackageFile:
PackageFileSize: -1.00 KiB
BuildID:: brgedata_20170922175419
PreProcessing: Accessing  git_info. Starting Git clone. Installing dependencies. Installing  package: brgedata. Starting Build package. Starting Check package.  Starting Build package.
PostProcessing: Accessing  git_info complete. Finished Git clone. Installing dependency status: 0.  Installing package status: 0. Build Package status: 0. Checking Package  status: 1. Build Package status: 1.
InstallCommand:      source("http://bioconductor.org/scratch-repos/pkgInstall.R")
```
Both `omicRexposome` and `BRGEdata` passes standard `R CMD check` and `BiocCheck` locally.

**Comment by mtmorgan** [comment]
Thanks for your revisions; I think the timeout is not important for the package review process, and I'll mark this package as 'accepted'.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carleshf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"omicRexposome\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/omicRexposome

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carleshf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"brgedata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/brgedata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment]
@carleshf I know that other team members have communicated with you about renaming the dependency BRGEdata to BRGEdata. I made this change for you in the Bioconductor git repository in both the release and devel branches. cc'ing @nturaga @lshep
