### ISSUE TITLE
AnVILBase

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#3374]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/AnVILBase

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
AdditionalPackage: https://github.com/Bioconductor/AnVILAz

**Comment by lshep** [comment]
I can't process AnVILAz because it does not have biocViews in description

**Comment by LiNk-NY** [comment]
> I can't process AnVILAz because it does not have biocViews in description

@lshep Sorry about that. I have added some terms. Thanks!

**Comment by lshep** [comment]
Sorry @LiNk-NY  not sure why this triggered multiple builds

**Comment by LiNk-NY** [comment]
AdditionalPackage: https://github.com/Bioconductor/AnVILGCP

**Comment by LiNk-NY** [comment]
Hi @lshep 
Can `AnVILGCP` be run through the SPB? Thank you.

**Comment by lshep** [comment]
DataStorageAndAnalysis is not a valid biocViews term and causing issues when processing

**Comment by LiNk-NY** [comment]
@lshep 
Sorry about that. I fixed it.

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 

I hope you are doing well. 
The review has been pending for a bit. 
I am sure you are busy with other things.

Should someone else be assigned, Lori? @lshep 

Thank you.

Best regards,
Marcel

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - Sorry for the delay. The review of the packages are below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the packages are ready for a 
re-review.

# AnVILBase

- [ ] REQUIRED: The `R CMD check` did not finish because of the other AnVIL packages suggests. Any issues should be corrected once this is resolved and can complete.
- [ ] SUGGESTION: No Bioconductor dependencies detected.

# AnVILAz

- [ ] SUGGESTION: All declared Imports should be used.
- [ ] SUGGESTION: Import utils in NAMESPACE as well as DESCRIPTION.
- [ ] SUGGESTION: Empty or missing \value sections found in man pages.

# AnVILGCP

- [ ] SUGGESTION: Provide 'URL', 'BugReports' field(s) in DESCRIPTION
- [ ] SUGGESTION: Import parallel in DESCRIPTION as well as NAMESPACE
- [ ] REQUIRED: 'sessionInfo' not found in vignette(s).
- [ ] SUGGESTION: Avoid using '=' for assignment and use '<-' instead.
- [ ] SUGGESTION: Avoid the use of 'paste' in condition signals.
- [ ] SUGGESTION: Avoid redundant 'stop' and 'warn*' in signal conditions.
- [ ] REQUIRED: There should be runnable examples in man pages that document exported objects.
- [ ] REQUIRED: Use 'donttest{}' instead of 'dontrun{}' where possible.
- [ ] SUGGESTION: Consider adding a NEWS file.

Best,
Kayla

**Comment by LiNk-NY** [comment]
> @LiNk-NY - Sorry for the delay. The review of the packages are below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the packages are ready for a re-review.
> 

Thank you Kayla @Kayla-Morrell for your review.
I have updated the packages. Please see below. 

> # AnVILBase
> * [x]  REQUIRED: The `R CMD check` did not finish because of the other AnVIL packages suggests. Any issues should be corrected once this is resolved and can complete.

Both `AnVILAz` and `AnVILGCP` packages should be installed first. I am not sure why there is an error in the SPB since both packages should be installed before `AnVILBase` gets run. Any insights Lori? @lshep 

https://bioconductor.org/spb_reports/AnVILBase_buildreport_20240603105555.html

> * [x]  SUGGESTION: No Bioconductor dependencies detected.
> 

AnVILBase is an infrastructure package and does not use Bioconductor dependencies. The downstream packages `AnVIL`, `AnVILAz`, and `AnVILGCP` do. 

> # AnVILAz
> * [x]  SUGGESTION: All declared Imports should be used.
> * [x]  SUGGESTION: Import utils in NAMESPACE as well as DESCRIPTION.
> * [x]  SUGGESTION: Empty or missing \value sections found in man pages.

I don't see this when running `BiocCheck`

> # AnVILGCP
> * [x]  SUGGESTION: Provide 'URL', 'BugReports' field(s) in DESCRIPTION
> * [x]  SUGGESTION: Import parallel in DESCRIPTION as well as NAMESPACE
> * [x]  REQUIRED: 'sessionInfo' not found in vignette(s).
> * [x]  SUGGESTION: Avoid using '=' for assignment and use '<-' instead.
> * [x]  SUGGESTION: Avoid the use of 'paste' in condition signals.
> * [x]  SUGGESTION: Avoid redundant 'stop' and 'warn*' in signal conditions.

Some are false positives, e.g., "first error" in the error message, "function returned an error" in the converted warning

> * [x]  REQUIRED: There should be runnable examples in man pages that document exported objects.
> * [x]  REQUIRED: Use 'donttest{}' instead of 'dontrun{}' where possible.
> * [x]  SUGGESTION: Consider adding a NEWS file.

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - Thank you for making the necessary changes. I would like to see a clean build report of AnVILBase before I accept the packages. If that issue can get resolved than I'd be more than happy to accept.

Best,
Kayla

**Comment by LiNk-NY** [comment]
Hi Kayla, @Kayla-Morrell 
Thanks for taking a look. 

All the packages are passing build and check now.

There is a false positive from the SPB but it only affects [one platform](https://bioconductor.org/spb_reports/AnVILBase_buildreport_20240702122457.html#lconway_check_anchor):

```r
* checking package dependencies ... ERROR
Packages suggested but not available: 'AnVILAz', 'AnVILGCP'
```


Best regards,
Marcel

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - Looks good, thanks!

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AnVILBase")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AnVILBase

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AnVILAz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AnVILAz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AnVILGCP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AnVILGCP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
