### ISSUE TITLE
pgca

### ISSUE THREAD

**Issue by gcohenfr** [Bioconductor/Contributions#338]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gcohenfr/pgca

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hpages** [comment]
Hi Gabriela,

Thanks for submitting the pgca package. I had a quick look at it and have some feedback for you. See below. Please address these issues at your earliest convenience.

Regards,
H.

1. Please delete `intro.html` and `intro.R` from the `vignettes/` folder of the package. These files should not be added to the git tree because they will be automatically generated by `R CMD build` when we build the source tarball of the package. This guarantees that they will be in sync with `intro.Rmd` and also that will end up in the right location (which is inst/doc/, not vignettes/).

2. Add the Proteomics and MassSpectrometry terms to the biocViews field. This will make your package show up in these categories:
    https://bioconductor.org/packages/release/BiocViews.html#___Proteomics
    https://bioconductor.org/packages/release/BiocViews.html#___MassSpectrometry
Bioconductor provides 1300+ packages so using specific biocViews terms is important as it will help people find your package.

3. The spelling "Bioconductor" is preferred over "BioConductor" (found in the vignettte).

4. Note that Bioconductor strongly discourages the use of dots in function names. The camelCase convention is the preferred naming style. Using underscores (`_`) is also an accepted convention.

5. The `translate()` function in pgca conflicts with the `translate()` generic function defined in the Biostrings package. Please rename it.

6. The `out.dir` argument of the `translate()` function should have a default (e.g. NULL) so the user doesn't need to specify this argument when s/he doesn't want to save the result.

7. Please explain where the `accs_no_*.txt` files are coming from. How they were produced?

8. The vignette introduction is too minimalist. Maybe it could provide a little bit more context e.g. what kind of multiple experimental runs are we talking about, what kind of data they produce, what is meant exactly by "connected local groups" and "global protein groups", what's the grouping criteria, why identifying "global protein groups" is important, etc... Don't assume that the reader is an expert in the area. This also applies to the Description field in the DESCRIPTION file.

9. The "4 Translation" section says:
```
    We see that PGC 10 is used for FGG in both data files.
```
  But I see PGC 14, not 10. Furthermore, and unless I'm missing something, I don't think that doing `subset(translated[[1]], PGC == 14)` is actually how someone would realistically find out what PGC is used for FGG because it requires that s/he already knows the answer. Shouldn't the user do something like the following instead?
```
    subset(translated[[1]], Gene_Symbol == "FGG")
```
  Note that this is what you use in the "5.1 A larger example" section.

10. Please turn the `save.dict()` example into a running example. Write the output to a temporary file with something like:
```
    output_file <- tempfile()
    save.dict(dict, file=output_file)
```

11. You provide a set of functions for *building* a pgca.dict object from various kinds of input: `pgca()`, `pgca.data()`, and `pgca.files()`. There are a few problems related to this:

  a) The man page for these functions contains:
```
       Details of the algorithm can be found in XX, YY (2017).
```
  I'm not sure what this reference is. In any case, a man page should be as self-contained as possible so a few words about how these functions build the dictionary wouldn't hurt.

  b) Why provide 3 functions when 1 would be enough e.g.:
```
       pgca(..., col.mapping, master.gene.identifier)
```
where `...` is an arbitrary number of data frames, filenames, or directory paths. So the user wouldn't need to remember which function to use exactly (note that the current names of the 3 functions don't really help), and also s/he would be able to provide input that is a mix of different things (e.g. a mix of data frames and filenames).

  c) The Value section in the man page says:
```
       An object of type ‘accession.dict’.
```
     But what I get is a pgca.dict object:
```
       > class(dict)
       [1] "pgca.dict"
```
  d) The names of the functions are not particularly intuitive. If we see the 3-in-1 `pgca()` function as the pgca.dict constructor function, the convention would be to name it `pgca.dict()`. An alternative would be to name it `build.pgca.dict()` to emphasize the fact that some algorithm is used for combining the data from the supplied inputs. Since Bioconductor strongly discourages the use of dots in function names, the class should actually be renamed (e.g. `pgca_dict`), which means that the function would become `pgca_dict()` or `build_pgca_dict()`.

**Comment by gcohenfr** [comment]
Thanks @hpages for the valuable feedback!

We have addressed points 1–6 and 9–11. In particular we changed the name and signature of the main function to
```r
pgcaDict(..., col.mapping, master.gene.identifier)
```
where `...` can be any combination of directory names, file names, data frames, or lists thereof.
We also renamed the `translate` function to `applyDict` and the class of the built dictionary to `pgcaDict` as you suggested.

For points 7 and 8 we provisionally improved the vignette by using another example and fixing some of the explanations. We agree that the Vignette needs additional work and it is in our interest that the user can clearly understand how to use our algorithm. We will continue working on these points.

We also want to mention that we wrote an accompanying paper that is currently under review in PLoS ONE which contains more details about the problem and the algorithm. It will be great if the package comes live in Bioconductor since the reviewers and editor may try to download it to finish the second revision of our manuscript.

We will submit a new version of the package with the changes mentioned above, which we hope can now pass your revision. In the meantime, we will add more information to the Vignette and manual.

Regards,
Gabriela Cohen Freue (@gcohenfr) and David Kepplinger (@dakep)

**Comment by gcohenfr** [comment]
Dear Herve @hpages,
we haven't heard back from you regarding our new package `pgca`. You have addressed all points made and we will continue to edit the Vignette for future versions of the package. As I indicate before, our accompanying manuscript is under revision and the reviewers may want to access the library. Thus, it is important to us to have the package running as soon as possible. Please, let us know if there is any additional requirement from us at this point. 
Regards,
Gabriela

**Comment by hpages** [comment]
Hi Gabriela,
Thanks for making all these improvements. Points 7 & 8 are important. Please address them at your earliest convenience. Thanks!
Regards,
H.

**Comment by hpages** [comment]
Hi Gabriela,
Just a reminder that points 7 & 8 need your attention and that we are very close to the next Bioconductor release (it's in 4 days). We won't be able to add your package to this release after Sunday.
Regards,
H.

**Comment by dakep** [comment]
Hi Hervé @hpages,
thanks for reminding us about the deadline on Sunday! We have expanded the vignette with a more thorough introduction and explained how the example data was produced. We hope the vignette now addresses all your points adequately. Thank you for your feedback!
Regards,
David (@dakep) and Gabriela (@gcohenfr)

**Comment by gcohenfr** [comment]
Dear Harve @hpages
Please review our new Vignette. We have addressed all you comments. In particular, we changed the source files, explained how they were obtained and their content. We have also added more information about he algorithm and a full description of local vs global groups. The new Vignette provides a summary of the problem, a description of our solution and an example to illustrate the problem, the algorithm and the functions in our package. 

We hope this version gets approved before tomorrow's deadline. It is important for us to get this in Bioconductor to link it to our accompanying paper, in second round revision. 
Thanks 
Gabriela and David

**Comment by hpages** [comment]
Hi Gabriela,
These are great improvements.,thanks! I'm marking pgca as accepted. We will make sure to add the package to our Subversion repository and build system ASAP. Also we'll send you an email very soon with a follow-up on this.
Thanks for your contribution to Bioconductor,
Regards,
H.

**Comment by gcohenfr** [comment]
Great Herve @hpages !! Thanks again for  your insightful comments! It helped us to improve our Vignette!!
