### ISSUE TITLE
broadSeq resubmission

### ISSUE THREAD

**Issue by vondoRishi** [Bioconductor/Contributions#3381]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dasroy/broadSeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please include an `inst/scripts` that has a file that describes how the data in `inst/extdata` was generated.  It can be text, psuedo-code, or code but should contain any relevant source and licensing information.

**Comment by vondoRishi** [comment]
Looking forward to the reviewer's comments.  :)

**Comment by lshep** [comment]
I'm so sorry for the long delay; I have been extremely backed up with post release tasks.  I will have a review for you within the next day.

**Comment by lshep** [comment]
**README**

- [ ] Include Bioconductor installation instructions

**man**

- [ ] Please have a package level man page so that if a naive user does
  `?broadSeq` they are directed appropriately how to get started.

**DESCRIPTION**

- [ ] When doing R CMD build the following occurs

```
  NB: this package now depends on R (>= 3.5.0)
  WARNING: Added dependency on R >= 3.5.0 because serialized objects in
  serialize/load version 3 cannot be read in older versions of R.
  File(s) containing such objects:
    'broadSeq/inst/extdata/rat_vole_mouseSE_salmon.rds'
```

We would appreciate a manual entry of R (>= 4.4.0) as this is the R value tested
against on our builders


**BiocCheck**

- [ ] Plesae correct coding NOTES

**general**

- [ ] We like to see endomorphism whenever possible. Curious your reasoning for
  taking in a SummarizedExperiment but then not returning it?


**vignette**
 broadSeq.rmd

- [ ] Could you please provide an abstract/intro section in your vignette that
  provides motivation for inclusion in Bioconductor and when appropriate a
  review and comparison to existing Bioconductor packages with similar
  functionality or scope.

- [ ] This vignette shows no evaluated code. If I were a user I would not know
  where to start.  Please include either references to the other vignettes or
  show/reference the main functions that can be used.

**test**

- [ ] We really strongly encourage tests to ensure functions are working
  correctly

**NEWS**

- [ ] We strongly advise a NEWS file. NEWS file not only make changes visible to
  end users, we collate the NEWS file for the Bioconductor relesae
  announcements. See example [release announcement](https://bioconductor.org/news/bioc_3_19_release/)

**Comment by vondoRishi** [comment]
Hi,

Are all of these comments mandatory?

**Comment by lshep** [comment]
For the most part yes.  You could justify why something shouldn't be implemented and if reasonable I could potentially make an exception.

**Comment by vondoRishi** [comment]
> **README**
> 
> * [x]  Include Bioconductor installation instructions
> 
> **man**
> 
> * [x]  Please have a package level man page so that if a naive user does
>   `?broadSeq` they are directed appropriately how to get started.
> 
> **DESCRIPTION**
> 
> * [x]  When doing R CMD build the following occurs
> 
Fixed the serialized object
> ```
>   NB: this package now depends on R (>= 3.5.0)
>   WARNING: Added dependency on R >= 3.5.0 because serialized objects in
>   serialize/load version 3 cannot be read in older versions of R.
>   File(s) containing such objects:
>     'broadSeq/inst/extdata/rat_vole_mouseSE_salmon.rds'
> ```
> 
> We would appreciate a manual entry of R (>= 4.4.0) as this is the R value tested against on our builders
> 
> **BiocCheck**
> 
> * [ ]  Plesae correct coding NOTES
> 

There is no preprint or publication for this package yet

> **general**
> 
> * [x]  We like to see endomorphism whenever possible. Curious your reasoning for
>   taking in a SummarizedExperiment but then not returning it?

There are many functions which return SummarizedExperiment object , like 
broadSeq::transformDESeq2 or broadSeq::normalizeEdgerCPM

> 
> **vignette** broadSeq.rmd
> 
> * [x]  Could you please provide an abstract/intro section in your vignette that
>   provides motivation for inclusion in Bioconductor and when appropriate a
>   review and comparison to existing Bioconductor packages with similar
>   functionality or scope.
> * [x]  This vignette shows no evaluated code. If I were a user I would not know
>   where to start.  Please include either references to the other vignettes or
>   show/reference the main functions that can be used.
> 
> **test**
> 
> * [ ]  We really strongly encourage tests to ensure functions are working
>   correctly

At this moment, there is no manpower to write tests.

> 
> **NEWS**
> 
> * [ ]  We strongly advise a NEWS file. NEWS file not only make changes visible to
>   end users, we collate the NEWS file for the Bioconductor relesae
>   announcements. See example [release announcement](https://bioconductor.org/news/bioc_3_19_release/)

In future releases, news will be included.

**Comment by vondoRishi** [comment]
Hi any update about the last resubmission?

**Comment by lshep** [comment]
Could you please fix the NOTES in BiocCheck. Some may be ignored but the coding practices and BugReports field in the description should minimally be fixed.   

There is still no package level page. Nothing appears with a `?broadSeq` call
```
> ?broadSeq
No documentation for 'broadSeq' in specified packages and libraries:
you could try '??broadSeq'
```

**Comment by vondoRishi** [comment]
How can I add package-level documentation? Though I have added `R/broadSeq-package.Rd`

**Comment by lshep** [comment]
See something like the following [txdbmaker example](https://code.bioconductor.org/browse/txdbmaker/blob/devel/man/txdbmaker-package.Rd).  You want to actually have values not be internal so that something displays with `?broadSeq`

**Comment by vondoRishi** [comment]
With this new build, there should be displays with `?broadSeq`. Can you please confirm?

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vondoRishi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("broadSeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/broadSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
