### ISSUE TITLE
PepSetTest

### ISSUE THREAD

**Issue by JmWangBio** [Bioconductor/Contributions#3417]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JmWangBio/PepSetTest

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please see initial comments: 

**General**

- [ ] Is it possible to show interopability with current Bioconductor classes
  for LC-MS/MS proteomics data. http://contributions.bioconductor.org/important-bioconductor-package-development-features.html#commonclass


**inst**

- [ ] What are these scripts used for? I do not see them referenced anywhere in
  the package?

**man**

- [ ] Please have a package level man page so when a naive user does
  '?PepSetTest' they get information on how to get started.

**vignette**

- [ ] We advise renaming the vignette to something more unique like
  PepSetTest.Rmd to avoid naming conflicts pending package load order.

- [ ] Could you please expand the intro/abstract to compare/contrast to existing
  Bioconductor methodologies to highlight novel approaches.

- [ ] Please show an example using Bioconductor common classes for MS data.

**Comment by JmWangBio** [comment]
Thanks for the comments! Please see my response below:

> Please see initial comments:
> 
> **General**
> 
>     * [X]  Is it possible to show interopability with current Bioconductor classes
>       for LC-MS/MS proteomics data. http://contributions.bioconductor.org/important-bioconductor-package-development-features.html#commonclass
> 

The interopability with SummarizedExperiment, a common class for proteomics data, is now demonstrated in the revised package.

> 
> **inst**
> 
>     * [ ]  What are these scripts used for? I do not see them referenced anywhere in
>       the package?
> 

These scripts can be used to reproduce the analysis shown in Wang et al (2024) Bioinformatics 40(5):btae270, as indicated in the "Code availability" section of the paper. The purpose of these scripts is now clarified in the vignette.

> 
> **man**
> 
>     * [ ]  Please have a package level man page so when a naive user does
>       '?PepSetTest' they get information on how to get started.
> 

A package-level man page has been added.

> 
> **vignette**
> 
>     * [ ]  We advise renaming the vignette to something more unique like
>       PepSetTest.Rmd to avoid naming conflicts pending package load order.
> 

The vignette has been renamed as suggested.

>
>     * [ ]  Could you please expand the intro/abstract to compare/contrast to existing
>       Bioconductor methodologies to highlight novel approaches.
> 

The abstract and introduction have been expanded to highlight the comparison between the peptide set test and existing Bioconductor methodologies.

>
>     * [ ]  Please show an example using Bioconductor common classes for MS data.
>

An example using SummarizedExperiment, a common class for MS data, has been added to the vignette (Example 2).

**Comment by LiNk-NY** [comment]
Hi @JmWangBio 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# PepSetTest #3417

The main data representations in the package are matrices and data.frames.
There are a couple of functions that allow `SummarizedExperiment` inputs.
Should most functions support a `SummarizedExperiment` representation,
especially those that require a mapping `data.frame`?

## DESCRIPTION

* Add `BugReports` and `URL` fields.
* Include your ORCID ID or remove the comment argument.

## NAMESPACE

* Consider using the native pipe `|>` rather than `%>%` in `magrittr`
* Looks good.

## vignette

* Consider wrapping the text to 80 character width for readability.
* Optional. Consider using `BiocStyle::html_document`
* Optional. Use `bibliography:` in the yaml header and include an
`inst/REFERENCES.bib` file to cite your publication and direct users to
`citation(package = "PepSetTest")`.
* Promote safe coding practices and use `seq_along(group)` rather than
`1:length(group)`
* Consider simplifying the code in example 3 (`contrasts_res`) to make it more
reader friendly or use helper functions.

## R

* Avoid using `sapply` and use `vapply` or `lapply`
* Avoid using `eval(parse())` and use `switch` instead.
* Reconsider the sequence of calls in `CompPepSetTest` and
`EnframeContrastsRes`, i.e., `result %>% filter(!is.na(get(stats)))`. Your
intention seems different than the code, perhaps use `.[[stats]]` or
`.data[[stats]]`.

**Comment by JmWangBio** [comment]
Hi Marcel (@LiNk-NY ),

We appreciate your detailed comments and have updated our package following your suggestions. Please see our response below:

> # PepSetTest #3417
> 
> The main data representations in the package are matrices and data.frames. There are a couple of functions that allow `SummarizedExperiment` inputs. Should most functions support a `SummarizedExperiment` representation, especially those that require a mapping `data.frame`?
>

Our package has three major workflows: the competitive peptide set test workflow, the self-contained workflow, and the aggregation-based limma workflow. Following your suggestion, we have made all three workflows compatible with the `SummarizedExperiment` representation.

> ## DESCRIPTION
> 
>     * Add `BugReports` and `URL` fields.
>

`BugReports` and `URL` fields have been added.

> 
>     * Include your ORCID ID or remove the comment argument.
> 

The comment argument has been removed.

> 
> ## NAMESPACE
> 
>     * Consider using the native pipe `|>` rather than `%>%` in `magrittr`
> 
>     * Looks good.
> 

`%>%` in `magrittr` has been replaced by `|>` throughout the package.

> 
> ## vignette
> 
>     * Consider wrapping the text to 80 character width for readability.
> 

All text in the vignette has been wrapped to 80 character width.

>
>     * Optional. Consider using `BiocStyle::html_document`
> 

`BiocStyle::html_document` is now used in the vignette.

>
>     * Optional. Use `bibliography:` in the yaml header and include an
>       `inst/REFERENCES.bib` file to cite your publication and direct users to
>       `citation(package = "PepSetTest")`.
> 

We have included an `inst/REFERENCES.bib` file and updated the vignette accordingly to cite our publication.

>
>     * Promote safe coding practices and use `seq_along(group)` rather than
>       `1:length(group)`
> 

`seq_along(group)` is now used in the vignette. 

>
>     * Consider simplifying the code in example 3 (`contrasts_res`) to make it more
>       reader friendly or use helper functions.
> 

Example 3 has been removed to improve readability.

> 
> ## R
> 
>     * Avoid using `sapply` and use `vapply` or `lapply`
> 

We have replaced `sapply` with suggested alternatives in all R scripts.

>
>     * Avoid using `eval(parse())` and use `switch` instead.
> 

We have removed `eval(parse())` from all R scripts.

>
>     * Reconsider the sequence of calls in `CompPepSetTest` and
>       `EnframeContrastsRes`, i.e., `result %>% filter(!is.na(get(stats)))`. Your
>       intention seems different than the code, perhaps use `.[[stats]]` or
>       `.data[[stats]]`.
>

We have fixed this line of code by renaming the `stats` argument of `CompPepSetTest`.

Please let us know if you have any additional questions or comments.

**Comment by LiNk-NY** [comment]
Hi @JmWangBio
 
Thanks for making those changes. Your package has been accepted. 
We would strongly encourage you to add unit tests. 
These would make the package more robust to changes. 

Please run `BiocCheck()` on the package to see all the 12 `NOTES`. 

Best regards,
Marcel

**Comment by JmWangBio** [comment]
Hi Marcel ( @LiNk-NY )

I added a new function to this package and would like the change to be reflected in the BioConductor build. Would it still be possible for me to do so, if not too much trouble? I think this new function will make the package more useful to the users.

**Comment by LiNk-NY** [comment]
Hi @JmWangBio 

You'd have to wait until the package is added to the official list of Bioconductor packages to see the build results. 
In the meantime, please rely on the output of your local `R CMD build` and `R CMD check` or GitHub Actions. 

Best,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/JmWangBio.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PepSetTest")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PepSetTest

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
