### ISSUE TITLE
StabMap

### ISSUE THREAD

**Issue by shazanfar** [Bioconductor/Contributions#3426]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/StabMap

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment]
I sincerely apologies for the delay (traveling etc.) ... package is in really good shape already, and I think my comments are fairly minor/should be addressable promptly. Please respond to what has/not been addressed why/how, or any Qs you might have; cheers!

# code

- [ ] `seq_len/along()` should be used instead of `1:n` (see [here](https://contributions.bioconductor.org/r-code.html?q=seq_len#code-syntax-and-efficiency)).

- [ ] Commented out code etc. should be removed for release (see [here](https://contributions.bioconductor.org/r-code.html?q=comment#rcode-comments)); e.g., `getAdaptiveK.R`.

- [ ] Consider adding a `verbose=TRUE/FALSE` option where applicable; users might want to suppress superfluous console output, and it's nice to let them do that easily; e.g., `stabMap.R`.

- [ ] Consider implementing more "advanced" validity checks on input arguments to i) avoid computations that fail downstream and ii) give users informative errors (R errors might not always be...); e.g., `stabMap(..., ncomponentsReference=50)` fails with `length of 'dimnames' [2] not equal to array extent`.  

- [ ] When an argument should match one of a defined set of character strings, I'd recommend using `match.arg` (e.g., in `classifyEmbedding.R`: `type <- match.arg()` with the function definition specify valid choices via `classifyEmbedding <- function(..., type=c("uniform_fixed", ...))`, where the 1st is the default).

# other

- [ ] Please consider implementing unit tests; we strongly encourage them!

- [ ] Not sure where/if it's being used, but `vignettes/raw.R` should probably go under `inst/scripts` (see [here](https://contributions.bioconductor.org/docs.html?q=scripts#doc-inst-script)), or be removed. 

- [ ] `UpSetR` is only being used by `mosaicDataUpSet.R`; consider putting it under `Suggests:` rather than depending on it (see [here](https://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances)).

- [ ] Please add a NEWS file to keep track of version-wise changes (see [here](https://contributions.bioconductor.org/news.html?q=news#news)).

- [ ] In the README, please add Bioc installation instructions using `BiocManager::install()`.

**Comment by shazanfar** [comment]
Thanks so much for your review, Helena! I believe we have addressed all your comments, the checklist and comments below,

# code

- [x] `seq_len/along()` should be used instead of `1:n` (see [here](https://contributions.bioconductor.org/r-code.html?q=seq_len#code-syntax-and-efficiency)).

Fixed in `stabmap.R`

- [x] Commented out code etc. should be removed for release (see [here](https://contributions.bioconductor.org/r-code.html?q=comment#rcode-comments)); e.g., `getAdaptiveK.R`.

Fixed in `getAdaptiveK.R`, `classifyEmbedding_utils.R`, `classifyEmbedding.R`, and `adaptiveKNN.R`

- [x] Consider adding a `verbose=TRUE/FALSE` option where applicable; users might want to suppress superfluous console output, and it's nice to let them do that easily; e.g., `stabMap.R`.

Fixed in `stabmap.R`

- [x] Consider implementing more "advanced" validity checks on input arguments to i) avoid computations that fail downstream and ii) give users informative errors (R errors might not always be...); e.g., `stabMap(..., ncomponentsReference=50)` fails with `length of 'dimnames' [2] not equal to array extent`.  

Thanks for flagging this example error (which occurs when the input number of PCs is higher than the number of samples for a given reference dataset), the issue itself is fixed by taking the columns of the reference PCs. Also fixed argument in the call to scran::modelGeneVar() to deal with density error when `stabMap(..., maxFeatures = )` argument is set too low.

- [x] When an argument should match one of a defined set of character strings, I'd recommend using `match.arg` (e.g., in `classifyEmbedding.R`: `type <- match.arg()` with the function definition specify valid choices via `classifyEmbedding <- function(..., type=c("uniform_fixed", ...))`, where the 1st is the default).

Thanks for this! Implemented for `classifyEmbedding()` arguments `type` and `error_measure`.


# other

- [x] Please consider implementing unit tests; we strongly encourage them!

Unit tests implemented for `stabMap`, `classifyEmbedding` and `imputeEmbedding` functions

- [x] Not sure where/if it's being used, but `vignettes/raw.R` should probably go under `inst/scripts` (see [here](https://contributions.bioconductor.org/docs.html?q=scripts#doc-inst-script)), or be removed. 

Thanks for this, removed

- [x] `UpSetR` is only being used by `mosaicDataUpSet.R`; consider putting it under `Suggests:` rather than depending on it (see [here](https://contributions.bioconductor.org/description.html?q=suggests#depends-imports-suggests-enhances)).

fixed

- [x] Please add a NEWS file to keep track of version-wise changes (see [here](https://contributions.bioconductor.org/news.html?q=news#news)).

added

- [x] In the README, please add Bioc installation instructions using `BiocManager::install()`.

added!

Please let us know if there are any further issues to fix, thanks again

**Comment by HelenaLC** [comment]
Thanks, getting close; few outstanding comments, some of which I didn't catch before... from most to least "severe", but all minor:

- [ ] related to the next point, `scater` is a rather heavy dependency when considering it is being used only for `calculatePCA()`; could this be omitted in favor of `stats::prcomp`?

- [ ] not sufficiently familiar with the details to judge, but is `scran::modelGeneVar()` a requirement, or could users in principle pass a subset of features selected for previously? In the latter case, `scran` should go under `Suggests:` as it is only used for feature selection in `stabMap`, which could be done by other means (your call!).

- [ ] `classifyEmbedding()` currently initializes an empty list and appends results, which is inefficient and should be avoided (see [here](https://contributions.bioconductor.org/r-code.html?q=append#pre-allocate-and-fill-if-iterations-are-necessary)); please pre-allocate and instead (e.g., `train_k` could be done in one line using `replicate`, and the rest using `l/mapply` or similar)... also anywhere else where applicable.

- [ ] again, not (yet) a requirement, but I'd very much encourage more thorough unit testing, i.e., spending a day to cover as much of the package as possible, not just testing that a function runs (documentation examples already do this), but testing failure for unexpected inputs (e.g., the ones mentioned above), any edge-cases you can think of, various argument input combinations, output structure (dimensions, names, content, etc.) - anything you can come up with, really... proper unit testing is crucial for long-term maintenance, and also makes it easier on developers themselves!

- [ ] for consistency (&  guidelines)... *(test-)classifyEmbedding.R*:  
`1:nrow(.)` -> `seq_len(nrow(.))`, `1:length(.)` -> `seq_along(.)`

**Comment by shazanfar** [comment]
Thanks for these comments Helena, please see responses below and let me know your thoughts,

- [X]  related to the next point, `scater` is a rather heavy dependency when considering it is being used only for `calculatePCA()`; could this be omitted in favor of `stats::prcomp`?

This is a good point! Instead of replacing with `stats::prcomp`, we have replaced it with `BiocSingular::runPCA`. Since scater package takes from BiocSingular this means that the results are the same up-to-rotations. As a bit of a bonus we can pass on the parallel BPPARAM over as well. As a result of this, the scater dependency is now removed (moved to Suggests for the vignette), and we have added the BiocSingular and BiocParallel dependencies.

- [X]  not sufficiently familiar with the details to judge, but is `scran::modelGeneVar()` a requirement, or could users in principle pass a subset of features selected for previously? In the latter case, `scran` should go under `Suggests:` as it is only used for feature selection in `stabMap`, which could be done by other means (your call!).

Yes, scran is now in Suggests:, and the feature selection step within stabMap function (needed when maxFeatures argument is used) has been moved to its own function selectFeatures

- [X]  `classifyEmbedding()` currently initializes an empty list and appends results, which is inefficient and should be avoided (see [here](https://contributions.bioconductor.org/r-code.html?q=append#pre-allocate-and-fill-if-iterations-are-necessary)); please pre-allocate and instead (e.g., `train_k` could be done in one line using `replicate`, and the rest using `l/mapply` or similar)... also anywhere else where applicable.

Fixed, added preallocation of the list object

- [X]  again, not (yet) a requirement, but I'd very much encourage more thorough unit testing, i.e., spending a day to cover as much of the package as possible, not just testing that a function runs (documentation examples already do this), but testing failure for unexpected inputs (e.g., the ones mentioned above), any edge-cases you can think of, various argument input combinations, output structure (dimensions, names, content, etc.) - anything you can come up with, really... proper unit testing is crucial for long-term maintenance, and also makes it easier on developers themselves!

Thanks for this, we have added error and warning unit tests along with the consistency of expected outputs from the previous tests that were in place.

- [X]  for consistency (&  guidelines)... _(test-)classifyEmbedding.R_:
  `1:nrow(.)` -> `seq_len(nrow(.))`, `1:length(.)` -> `seq_along(.)`

Thanks! fixed

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shazanfar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("StabMap")`. The package 'landing page' will be created at

https://bioconductor.org/packages/StabMap

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
