### ISSUE TITLE
DuplexDiscovereR

### ISSUE THREAD

**Issue by Egors01** [Bioconductor/Contributions#3453]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/Egors01/DuplexDiscovereR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
I'm very sorry for the delayed response.  I went out with long covid. I should have a review for you by tomorrow at the latest.

**Comment by lshep** [comment]
Please find your review below.  When ready please kick off a new build report
and respond here to the review comments.


**build report**

- [ ] There are a lot of no visible binding notes. Can these be cleaned up?


**Description**

- [ ] Broken links in URL and BugReports

- [ ] Please ensure any package imported in NAMESPACE is also appropriately
  declared in the DESCRIPTION
  

**vignette**

- [ ] We recommend a more unique file name for the vignette rather than
  tutorial. Having a generic name can cause load conflicts depending on load
  order of other packages.  We strongly recommend renaming the file to the name
  of the package.

- [ ] It would be worth running through a spell checker and there are multiple
  typos

- [ ] 3.1 is not rendering correctly as a list. It renders as a paragraph. You
  likely need a line break 

```
Full DuplexDiscovereR workflow consists of the following steps: - Pre-processing of the input. For the chimeric alignment generated by STAR, this step calls the classification based in the CIGAR strings - 2arm reads (only one chimeric junction per aligned read) - multi-split (two or more one chimeric junctions per aligned read) - multi-mapped reads - Comparing the 2arm chimericly mapped reads against the splice junctions. Alignments across the exon-exon junctions typically contaminate the ‘true’ chimeric alignments originated from the RNA duplexes - Deduplication of the identical read alignments - Clustering into DGs

```

- [ ] Since it is mentioned in the README that ViennaR has a different license
  it should likely also be mentioned in the vignette in the section it is used again so that users take caution
  and make sure there is no restrictions no their use case. 

**general**

- [ ] You seem to have multiple `.gitignore` files.  It would be better to
  combined into one top level instead of having individual in subfolders
  (ie. vignettes/.gitignore)

**R code**

- [ ] Consider replacing for loops with applies that are generally more
  efficient.

- [ ] Please remove unused/unrun code chunks. notes are fine but if code is
  commented out it should be removed.

- [ ] system2 is recommended over system calls.

- [ ] It might be beneficial to expand out object accessor methods so that
  direct access wtih @ or subsetting with [ are not needed by the end user. That
  there is an accessor for values of list elements. This could be expanded to
  internal use to clean up code readability as well.

- [ ] Since it is mentioned in the README that ViennaR has a different
  license we would also recommend having a message if this section of code is
  run to indicate that there may be restrictions on use/reporting.

**Comment by Egors01** [comment]
Thanks @lshep for the review. I just want to confirm that I am working on it and will make an updated push addressing the points within a couple of weeks.

**Comment by lshep** [comment]
Just wanted to check back in to see if there will be updates soon

**Comment by Egors01** [comment]
Dear @lshep

I am sorry for the delay. We found a bug in the code that took some time to track down and I had to fix it first. You can expect the version that addresses your review comments this Friday/early next week.

**Comment by Egors01** [comment]
Dear @lshep, 

The new version has been pushed and is ready for review. 
Here are my comments on the requested changes 

 **build report**
>     * [x]  There are a lot of no visible binding notes. Can these be cleaned up?
Most of these seem to be produced because of the tidyverse expressions that are flagged by R code tools check  
I have found some discussions on this issue e.g. [here](https://forum.posit.co/t/how-to-solve-no-visible-binding-for-global-variable-note/28887?u=shamindras) or [here](https://github.com/STAT545-UBC/Discussion/issues/451#issuecomment-385731301) Most of the solutions are silencing in one way or another. 
Based on the suggested options, I have ended up adding the following to the DuplexDiscovereR-package.R 
`if (getRversion() >= "2.15.1") utils::globalVariables(varlist, add = FALSE)` where the varlist are the longlist of names triggering the NOTE. 
An existing alternative is to change all dplyr code to use the `.data`, but this will make a lot of code more bulky, and this pronoun is [deprecated](https://www.tidyverse.org/blog/2022/10/tidyselect-1-2-0/) in selections, so I would prefer not to touch it. 

 **Description**
>     * [x]  Broken links in URL and BugReports
>     * [x]  Please ensure any package imported in NAMESPACE is also appropriately
>       declared in the DESCRIPTION
Fixed links and modified DESCRIPTION

**vignette**
>     * [x]  We recommend a more unique file name for the vignette rather than
>       tutorial. Having a generic name can cause load conflicts depending on load
>       order of other packages.  We strongly recommend renaming the file to the name
>       of the package.
>     * [x]  It would be worth running through a spell checker and there are multiple
>       typos
>     * [x]  3.1 is not rendering correctly as a list. It renders as a paragraph. You
>       likely need a line break
Changed as suggested. Fixed typos and spelling throughout the vignette. 
>     * [x]  Since it is mentioned in the README that ViennaR has a different license
>       it should likely also be mentioned in the vignette in the section it is used again so that users take caution
>       and make sure there is no restrictions no their use case.
Added license warning when  RNAHybrids is called from vignette. 

> **general**
>     * [x]  You seem to have multiple `.gitignore` files.  It would be better to
>       combined into one top level instead of having individual in subfolders
>       (ie. vignettes/.gitignore)
Moved all  `.gitignore` to single file at the top
> **R code**
>     * [x]  Consider replacing for loops with applies that are generally more
>       efficient.
>     * [x]  Please remove unused/unrun code chunks. notes are fine but if code is
>       commented out it should be removed.

Commented code removed and one for loop in `clusterDuplexGroups` changed to lapply.  
There is one `for` loop in `collapseSimilarChimeras`, which I will leave unchanged.  In practice, code within it runs from 0 to 3-5 times, and objects are changing on every iteration, so its logic is cannot be changed to vectorized operation. 

>     * [x]  system2 is recommended over system calls.
Changed calls from `system `to `system2 `as suggested
>     * [x]  It might be beneficial to expand out object accessor methods so that
>       direct access wtih @ or subsetting with [ are not needed by the end user. That
>       there is an accessor for values of list elements. This could be expanded to
>       internal use to clean up code readability as well.
I have added a class `DuplexDiscovererResults` for storing the results produced by the full analysis. It has documentation and accessor methods for the objects which were returned as the list elements. 
 
>     * [x]  Since it is mentioned in the README that ViennaR has a different
>       license we would also recommend having a message if this section of code is
>       run to indicate that there may be restrictions on use/reporting.
Added license warning message to the  `getRNAHybrids `function call

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Egors01.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DuplexDiscovereR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DuplexDiscovereR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
