### ISSUE TITLE
eoPredData

### ISSUE THREAD

**Issue by wvictor14** [Bioconductor/Contributions#3458]
This is an experimentHub data package. Also pinging author @iciarfernandez

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wvictor14/eoPredData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by wvictor14** [comment]
Hi given build report is clean (no errors or warnings) will the package now be moved to next stage of review?

From [Contributions:](https://github.com/Bioconductor/Contributions?tab=readme-ov-file#what-to-expect)

> Once your package builds and checks without errors or (avoidable) warnings, the package is assigned a reviewer. The package will be labelled 2. Review in progress.

**Comment by LiNk-NY** [comment]
Hi @wvictor14 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel 

--- 

# eoPredData #3458

## DESCRIPTION

* Include a more descriptive `Title` field. What is `eoPred`?

## NAMESPACE

* Looks OK.

## vignettes

* Remove timing code from the vignette. The BBS will provide timings.
* The vignette mentions `minfi` but the code displayed installs `mixOmics`. Is
that correct?
* Note that `rmarkdown` / `knitr` can also handle references by adding
`bibliography: filename.bib` in the yaml header. That would avoid the
`RefManageR` code.
* Consider adding a retrieval or `.onLoad` function to the package that helps
the users access data resources by name. See the `HubPub` vignette section
2.1.2.4.
* Describe the data in the vignette.

**Comment by wvictor14** [comment]
Thanks @LiNk-NY 

I addressed your comments:

> ## DESCRIPTION
> * Include a more descriptive `Title` field. What is `eoPred`?

added more descriptive title.


> ## vignettes
> * Remove timing code from the vignette. The BBS will provide timings.

Removed.

> * The vignette mentions `minfi` but the code displayed installs `mixOmics`. Is
>   that correct?

removed mention of minfi being required as it is not.

> * Note that `rmarkdown` / `knitr` can also handle references by adding
>   `bibliography: filename.bib` in the yaml header. That would avoid the
>   `RefManageR` code.

Thanks, will keep in mind for future

> * Describe the data in the vignette.

Data is described in [these lines](https://github.com/wvictor14/eoPredData/blob/49caa959c419e974be6529b61d7c391419f2e20e/vignettes/eoPredData.Rmd#L57) of vignette:

```
There are 2 objects associated with eoPredData:

**EHEH8090** Pre-trained model object using `mixOmics`. This model object can be used to create predictions on DNA methylation profiles collected from placental samples. Details on training and validation are described in 
`r Citep(bib[["eoPredData"]])`.

**EHEH8403** Placental DNA methylation test data (49 samples, 452 453 CpGs), used to demonstrate prediction of preeclampsia status using eoPred model. A `matrix` [cpg x sample].

```

**Comment by LiNk-NY** [comment]
Hi Victor, @wvictor14 

It looks like `mixOmics` is not used in the package code, only in the vignette. 
Please put `mixOmics` in the `Suggests` field. 
`planet` does not seem to be used in the package code either. 
It can be removed from the `DESCRIPTION` file or if needed to load the Hub resource, 
move the package to the `Suggests` field. 

Best regards,
Marcel

**Comment by wvictor14** [comment]
Thank you, both these suggestsions have been pushed 

> Hi Victor, @wvictor14
> 
> It looks like `mixOmics` is not used in the package code, only in the vignette. Please put `mixOmics` in the `Suggests` field. `planet` does not seem to be used in the package code either. It can be removed from the `DESCRIPTION` file or if needed to load the Hub resource, move the package to the `Suggests` field.
> 
> Best regards, Marcel

**Comment by LiNk-NY** [comment]
Hi Victor, @wvictor14 

Thank you for the updates.
Your package has been accepted.

Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wvictor14.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("eoPredData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/eoPredData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
