### ISSUE TITLE
EnrichDO

### ISSUE THREAD

**Issue by liangcheng-hrbmu** [Bioconductor/Contributions#3468]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/liangcheng-hrbmu/EnrichDO

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Can you please expand the abstract/introduction in your vignette that provides motivation for inclusion in Bioconductor and when appropriate a review and comparison to existing Bioconductor packages with similar functionality or scope. Is it possible to show interoperability with any existing Bioconductor infrastructure classes? 

The data in `Meta` should be moved to an official recognized directory, either `data` or `inst/extdata` and if in `inst/extdata` there should be an `inst/script` that describes the data, how it was created, source information, etc.

**Comment by liangcheng-hrbmu** [comment]
> Can you please expand the abstract/introduction in your vignette that provides motivation for inclusion in Bioconductor and when appropriate a review and comparison to existing Bioconductor packages with similar functionality or scope. Is it possible to show interoperability with any existing Bioconductor infrastructure classes?
> 
> The data in `Meta` should be moved to an official recognized directory, either `data` or `inst/extdata` and if in `inst/extdata` there should be an `inst/script` that describes the data, how it was created, source information, etc.

We have modified the uploaded package according to your suggestion.

**Comment by lshep** [comment]
Can you please make sure any default print/save/writes are defaulted to write to a `tempdir()` rather than a working directory. 

When I'm rerunning the vignette I'm getting different results for the plotting functions. Is there some random effect that is not shown or controlled?  Or if all sections of the vignettes are run (as some seem to be designated eval=FALSE) , that means the object used in plotting is different?

**Comment by liangcheng-hrbmu** [comment]
> Can you please make sure any default print/save/writes are defaulted to write to a `tempdir()` rather than a working directory.
> 
> When I'm rerunning the vignette I'm getting different results for the plotting functions. Is there some random effect that is not shown or controlled? Or if all sections of the vignettes are run (as some seem to be designated eval=FALSE) , that means the object used in plotting is different?

@lshep We have submitted some new changes.

**Comment by DarioS** [comment]
Major changes required to bring it to Bioconductor standard.

- Vignette needs to have an Installation section. See [Installation](https://contributions.bioconductor.org/docs.html#installation).
- The vignette uses `eval = FALSE`. No code chunks are allowed to use `eval = FALSE`. Please see [Vignettes](https://contributions.bioconductor.org/docs.html?q=eval#vignettes).
- Vignette shouldn't repeat content of function Rd files.

    ![image](https://github.com/user-attachments/assets/6ffe73a3-dc2b-40b9-930c-c6c3786140cb)
    
- Function calls explicitly use same values as default. If not different, don't specify the values to avoid redundancy.

```r
doEnrich(interestGenes = demo.data, 
          test         = "hypergeomTest", 
          method       = "BH", 
          m            = 1, 
          maxGsize     = 5000,
          minGsize     = 5,
          traditional  = FALSE,
          delta        = 0.01, 
          result_do    = NULL,
          penalize     = T)    
```

- Use spaces around binary operators. For example, `weight_result<-doEnrich(interestGenes = demo.data)` does not. Please refer to [Use of Space](https://contributions.bioconductor.org/r-code.html#use-of-space) in the chapter named [R Code](https://contributions.bioconductor.org/r-code.html).
- The output is a plain `data.frame`. Please use Biocoductor's `DataFrame` class from [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html) instead.

```r
> class(enrich)
  "data.frame"
```

- No biological interpretation. Please explain what the important biological aspects are, not just a list of definitions.

    ![image](https://github.com/user-attachments/assets/425ade21-1ee4-4251-97d9-97d1a63a950e)
    
    Which disease terms were statistically significant? What does this suggest about the disease? Interpret the results.
    
- The vignette still writes to the currently working directory: `writeDoTerms(doterms,file = "doterms.txt")`.
- Inconsistent variable naming style e.g. `weight_matrix`, `fisherTest`. [Bioconductor requires camelCase](https://contributions.bioconductor.org/r-code.html?q=write#variable-names) for consistency.
- Too much copying and pasting of code. Please restructure your functions to remove redundancy.
    ![image](https://github.com/user-attachments/assets/5928d656-64c7-462e-9ac6-cf13e49e09c9)
- Don't use `for` loops e.g. `for(i in max(enrich$level):m)` but vectorise with `lapply` or `vapply`. See [Vectorize](https://contributions.bioconductor.org/r-code.html?q=vapply#vectorize).
- Unnecessary usage of global variables.

```r
enrich <<- enrich %>% arrange(p)
enrich <<- mutate(enrich, p.adjust=p.adjust(p, method=method))
```

- Package submitted for review should not contain `EnrichDO.Rproj` file. See [Undesirable Files](https://contributions.bioconductor.org/general.html?q=Rproj#undesirable-files).
- Package lacks unit tests. Please read [Chapter 14: Unit Tests](https://contributions.bioconductor.org/tests.html) and add some meaningful correctness tests.
- There are many data files in extdata folder such as PAAD_GSE16515.csv. They are not used in examples or the vignette,
- Function parameters that have a limited set of valid values are not properly implemented. For example,  

> `test`: One of "fisherTest","hypergeomTest","binomTest","chisqTest" and "logoddTest". Default is hypergeomTest.

is implemented as `test = "hypergeomTest"` and inside the function there is no validity check. See [match.arg](https://www.r-at-work.com/functions/base/match-arg.html) and use it.
- Don't use `cat` for user messages. Use `message` instead. See [End-user Messages](https://contributions.bioconductor.org/r-code.html#end-user-messages).
- `doEnrich` function's described return type does not match the actual type that is returned.

> Value: A `enrich` instance.

```r
> class(demo_result3)
  "data.frame"
```

- Figure 3 of vignette has poor readability due to an unfortunate default colour scheme.

    ![image](https://github.com/user-attachments/assets/0f70f589-0be4-4b74-a876-d0d45f42a155)
    
- Vignette needs a session information section at the end of it. See [Session Information](https://contributions.bioconductor.org/docs.html#session-information).

**Comment by liangcheng-hrbmu** [comment]
Thank you for your suggestion！We have made corresponding modifications.

for(i in max(enrich$level):m), among them, regarding the use of the for loop, our algorithm needs to be calculated layer by layer and cannot calculate all levels simultaneously. Thus, except for the for loop, we have not come up with a better approach.

**Comment by liangcheng-hrbmu** [comment]
hi @DarioS , I am getting this warning on Bioconductor server at macOS, not sure yet what's the reason:
WARNING: R CMD check exceeded 10 min requirement

**Comment by DarioS** [comment]
That warning is fine to have. I will re-review your package soon.

**Comment by DarioS** [comment]
The package has been moderately improved. However, some major issues remain.

- The software doesn't implement [Functional Programming](https://www.codingdojo.com/blog/what-is-functional-programming). It has widespread use of global assignment.

![image](https://github.com/user-attachments/assets/612b9e36-3240-4575-824d-b7ed079b3355)

- The unit test is not meaningful. It tests whether the p-value is between 0 and 1.

```r
res <- sapply(c("fisherTest","hypergeomTest","binomTest","chisqTest","logoddTest" ), function(test){
  aa<-doEnrich(interestGenes = demo.data, test = test) ;return(aa@enrich$p)})
  expect_true(all(res >= 0) && all(res <= 1))
```

The p-values are calculated by base R functions and would never produce values outside of 0 and 1. For example,

```r
p<-phyper(wa-1,wa+wb,wc+wd,wa+wc,lower.tail = FALSE)
```

- The code does not use whitespace around binary operators. For example,

```r
p<-phyper(wa-1,wa+wb,wc+wd,wa+wc,lower.tail = FALSE)
```

- An S4 class was defined. But, it has no accessor functions and the examples ask the user to use `@` e.g. `demo_result@enrich`. `@` should only ever be used by a package developer, not by a package user. Please refer to [Class Design](https://contributions.bioconductor.org/r-code.html?q=accessor#class-design).

- Result floods the R console because the S4 class lacks a required `show` method.

![image](https://github.com/user-attachments/assets/10088144-df4d-4edc-b4ab-e696094ef3c6)

 From Class Design section,
> Implement a show() method to effectively convey information to your users without overwhelming them with detail.

**Comment by liangcheng-hrbmu** [comment]
@DarioS Thank you for your suggestion！We have made corresponding modifications.

**Comment by DarioS** [comment]
The package improves but outstanding issues remain.

- The authors implemented an S4 `show` method. However, there is still a vast amount of text in console. This is attempted to be hidden by using comments in R chunks and hiding the real output of the variable. `show` method needs to be used.

![image](https://github.com/user-attachments/assets/a9749bd8-3637-4213-8216-66dcdea6dfcd)

- The code still does not use whitespace around binary operators.

**Comment by liangcheng-hrbmu** [comment]
hi，@DarioS .The feature of our algorithm lies in calculating the ontology structure layer by layer. Thus, we aim to present the calculation status of each layer to the user. The running time of the algorithm is approximately 10 seconds, indicating that the calculation results can prevent the user from waiting for an extended period. If the above explanation does not conform to the rules, we will revise it again. We have modified the binary operators, thank you for your reminding！

**Comment by DarioS** [comment]
The result of `doEnrich` function now has a nice `show` method. However, the result of `EnrichTab` floods the R console with text. The request to use `DataFrame` was previously made and it would easily address this issue.
- The output is a plain `data.frame`. Please use Biocoductor's `DataFrame` class from [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html) instead.
- The support for `DataFrame` input is variable across the package.
```r
> DOterms <- DataFrame(doterms)
> writeDoTerms(DOterms, file = file.path(tempdir(), "doterms.txt"))
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "c('DFrame', 'DataFrame', 'SimpleList',
  'RectangularData', 'List', 'DataFrame_OR_NULL', 'Vector', 'list_OR_List', 'Annotated', 'vector_OR_Vector')"
```
- Lack of robustness to edge cases. For example, `gene_n = 1`:
```r
> drawHeatmap(interestGenes = demo.data, enrich = Enrich,gene_n = 1, fontsize_row = 8, readable = TRUE)
gene symbol conversion result: 
Error in hclust(d, method = method) : must have n >= 2 objects to cluster
```
Input parameters need validity checking by package code.

> Always use space after a comma. This: a, b, c.

from [Section 15.2.7.2](https://contributions.bioconductor.org/r-code.html?#use-of-space) has also not been done.
- Warnings from ggplot2 need to be avoided.
> drawPointGraph(enrich=enrich,delta = 0.05)
Warning message:
Using size for a discrete variable is not advised.
- The code still does not use whitespace around binary operators. For example,
```r
  enrichWeight<-get("enrichWeight",envir = .EnrichDOenv)
  enrichPvalue<-get("enrichPvalue",envir = .EnrichDOenv)
  enrichgeneArr<-get("enrichgeneArr",envir = .EnrichDOenv)

  genes<-enrichgeneArr[[DOID]]
  weights<-enrichWeight[[DOID]]
```
Another round of modifications and review is warranted.

**Comment by liangcheng-hrbmu** [comment]
Hi @DarioS , I am sorry for the repeated problems. Fortunately, we have found a suitable way to solve the above problems.

- We have corrected the format using formatR. 
- Our package currently does not use plain data.frame and also supports DataFrame input. 
- In addition, the parameter Settings of other functions are also limited, and inappropriate parameter input will be warned. 

besides，for the internal data--doterms, although it is a data.frame, we set up the appropriate showDoTerms(doterms) to show the structure of doterms, and the function writeDoTerms supports DataFrame(doterms) as input.

Thank you for your review over the past two months. We look forward to hearing from you.

**Comment by liangcheng-hrbmu** [comment]
Hello @DarioS , thank you for your review and encouragement. Additionally, we need a download address for EnrichDO provided by Bioconductor for our paper, but EnrichDO has not been deployed to the devel branch yet. How long does it usually take to successfully deploy it, or is there another download address we can use?

**Comment by DarioS** [comment]
It is performed manually by Lori Kern of the Bioconductor core team. It usually happens once per week.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/liangcheng-hrbmu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EnrichDO")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EnrichDO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
