### ISSUE TITLE
A package for 3D plot of epigenetic data

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#3534]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/geomeTriD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
I apologize for the delay. 

In extdata there are several files. in inst/script there is only scripts that
indicate how 4DNFI1UEG1HD.feature.gr.rds and pbmc_small.3d.rds.  Can you please
have a file of text, pseudo code, or code that explains the other files included
and any relevant licensing information.

Is there a separate license or information on what the threejs is licensed
under.  I think it is important to list that information too.

Could you please include a package man page so that if a naive user does
?geomeTriD there is some direction on how to start.

When I try to run the vignette,
```
## create threeJsGeometry objects
list3d <- view3dStructure(obj,
  feature.gr = feature.gr,
  renderer = "none"
)
## plot the data
threeJsViewer(list3d)

```
creates an empty graphic window and opens a browser that says file not found?
This seems true for most of the plotting through the first half of the
vignette. eventually some plots show but many do not. is there more set up or
configuration that needs to be done?  See screenshot 

![Screenshot from 2024-10-04 11-32-23](https://github.com/user-attachments/assets/a2e67d35-52f7-4806-ab5a-f10665fb5adb)

**Comment by jianhong** [comment]
@lshep Thank you for the review. Could you please double check if the issue is caused by snap installing discussed [here](https://github.com/karma-runner/karma-firefox-launcher/issues/183)? Could you please try to relocated the tmp folder in your `${HOME}/.Renviron` file and retry the plot? Let me know if it does not work.

Jianhong.

**Comment by jianhong** [comment]
@lshep 
This update may contain multiple bug fix. 
And according your comments, I add a md file to list all the file information and saved it at `extdata/filelist.md`.
Additional items were added into the LICENSE file. The full documentation of license is listed in `LICENSE.md` file.
Let me know if I missed anything.

Jianhong.

**Comment by lshep** [comment]
Thank you that worked and all looks good.  I would consider mentioning this firefox bug somewhere in the documentation in case others are using it.  I fixed it by changing the default to chrome that I also had installed but others might not have that option

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jianhong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("geomeTriD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/geomeTriD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
