### ISSUE TITLE
MIRA

### ISSUE THREAD

**Issue by j-lawson** [Bioconductor/Contributions#355]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/databio/MIRA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hpages** [comment]
Hi John,

Thanks for your submission.

1. An important issue with MIRA is that the package doesn't use a standard Bioconductor container to represent methylation data. The data.table package is great but Bioconductor already has dedicated containers for methylation data e.g. the BSseq class in the bsseq package. This class extends the SummarizedExperiment class defined in the package of the same name. I don't know if the BSseq class is the authority: it could be that other Bioconductor packages define similar classes for methylation data. All of them should extend the SummarizedExperiment class though. The Bioconductor project encourages the use of existing containers. I suggest that you could ask on the bioc-devel mailing for advice on which container to use for your methylation data. At the very least, you should use the SummarizedExperiment container, which is the common denominator of many more specialized classes. By using SummarizedExperiment objects, you will improve interoperability of your package with the Bioconductor ecosystem.

Other issues:

2. The man page for the `exampleBSDT` data set needs to provide more information about this methylation data e.g. where it's coming from and how it was generated.

3. It's unfortunate (and confusing) that the object you get when loading a data set doesn't have the name of the data set. For example:
```
> data(ewingMyobigBinDT1)
> ls()
[1] "bigBinDT1"
```

4. The titles of your man pages don't really look like titles. For example, the title of the man page of the `addMethPropCol()` function is:
```
    Adding methylProp column that has proportion of reads that were methylated for each site. Note:
    Assigns methylProp column by reference with ":="
```
Note that this title repeats exactly the content of the Description section. This content is ok for a Description, but not for a title.

5. Man pages for data sets don't need to have a Value section (the concept of returned value applies to functions, not to data sets).

6. The section numbers in the 2 vignettes all start with "0." (e.g. 0.1, 0.2, etc...). Please use more conventional numbers (e.g. 1, 2, etc...).

Please address these issues. Don't hesitate to ask on the bioc-devel mailing list if you have questions or concerns about this.

Best,
H.

**Comment by j-lawson** [comment]
Hello Hervé,

Thanks for the helpful feedback! I am not sure why the package build has not been completed yet since it generally seemed to be pretty quick but I'll go ahead and discuss the changes that were made. We have updated the package based on each of your comments:

1. We added more information about the exampleBSDT dataset including GEO accession information for the data it was generated from.

2. We changed the name of the datasets so that the names of the files match the names of the objects that are loaded into R.

3. We made shorter descriptive titles for the functions and put the more in-depth information in the appropriate section.

4. We removed the Value section from the man pages for data sets.

5. We fixed the section numbers in the vignettes.

6. For your major suggestion of using the SummarizedExperiment container, we considered at length how best to accomplish this. While it would be great to use SummarizedExperiment for the sake of interoperability with other Bioconductor packages, we also need to preserve efficiency and speed in the large aggregation operations that are used in MIRA. Our solution was to make a format conversion function that can be used with any container based on SummarizedExperiment that just requires the user to enter the appropriate region and assay data. It is not easy to implement a universal converter where we pull out the needed data within the function because each methylation class has different function names for accessing the slots and classes do not always contain the same data (eg having proportion of methylated reads but not number of total and methylated reads). We did include a wrapper of this function to specifically convert BSseq objects to data.table format because bsseq seemed to be the most widely used R package for next generation sequencing-based DNA methylation data based on the download statistics on the Bioconductor website (721 downloads last month and ahead of other packages we checked by such as methylkit, BiSeq, methylPipe, and a few others by over 200/300 downloads per month).
	We chose this solution for several reasons. Since aggregation of methylation data is so crucial to our package and the data is so large, we need the data.table operations in order to efficiently add the methylation data from a large number of chosen loci across the genome. Additionally, data.table allows easy parallelization by sample since each sample will have its own data.table as opposed to all the samples being in one SummarizedExperiment object. Since MIRA could realistically be used with hundreds of DNA methylation samples and hundreds of region sets in a single analysis (resulting in thousands of sample/region set combinations), using data.table will allow our package to be used with the large amount of data effectively. The conversion functions are left outside of the aggregateMethyl function so as not to confuse the user by having several input formats to aggregateMethyl and combining the ideas of format conversion and the actual purpose of aggregateMethyl. After we aggregate the methylation data into bins (output of aggregateMethyl), we are no longer using genomic coordinates and the basic unit of analysis is no longer a sample (it is a sample/region set combination) so we do not use SummarizedExperiment format for the output at that point. I hope this is a workable solution! Again, thanks for the feedback as it has improved our package!

Best,
John

**Comment by j-lawson** [comment]
Hello Hervé,

I'm not sure why the build process stopped halfway before but it looks like the build completed this time. Please see above for my comments on our changes to the package.

Best,
John

**Comment by j-lawson** [comment]
Hi Hervé,

Thanks for the suggestions about using the Gpos class for storing methylation data! I looked into the class and it seems to be a good way for efficient representation of single nucleotide coordinates but seems to be geared primarily towards memory efficiency. While memory efficiency is very valuable, our primary concern with MIRA is time efficiency. The major benefit of using data.table for our operations is that it has the ability to do operations very efficiently by group (eg add methylation level values for all rows that are in a certain group (bin) which we want to aggregate across the genome). This operation is crucial for us to facilitate the large scale application of MIRA which we envision. For example, if I had 100 region sets which I wanted to use with 5,000 methylation samples which we had assembled from various studies or projects like ENCODE, that would make 500,000 sample/region set combinations which means running MIRA (and aggregating) 500,000 times. For a large scale analysis like that, having fast aggregation by groups would make a big impact on the compute time needed. Also, while not as important as speed, I thought it could be helpful to note that since DNA methylation data is sparse and the genomic coordinates are often not consecutive, methylation data misses out on some of the optimization that Gpos has for consecutive coordinates. Gpos is a valuable package for memory efficient representation of single nucleotide coordinates but just may not be the best fit for our specific needs. We definitely do want to have compatibility with other Bioconductor packages though. Based on your previous comments, I added a function which could convert from SummarizedExperiment class to data.table for use in our functions.  Additionally, I have now updated that conversion function to be compatible with Gpos ranges in the SummarizedExperiment object. Hopefully this can make our package compatible with other Bioconductor packages while still preserving the speed we need for large analyses with MIRA! Please let me know any feedback you have on this proposed solution!

Thanks,
John

**Comment by j-lawson** [comment]
Hello Hervé,

We have made some updates to MIRA that could increase the user experience and interoperability with Bioconductor. First, we made "BSseq" objects an acceptable input to the main MIRA function, performing conversion to data.table within the function as opposed to outside it. Second, we generally improved the required input/parameters for functions, making them more flexible and easier to use. Third, we simplified the user interface to the scoreDip() function so that it no longer requires the user to know the special data.table syntax. As far as I know, it should now be possible for the user to use MIRA without needing to do any special data.table syntax (although knowing it would certainly be a plus). Hopefully these changes will improve the user experience with MIRA! We look forward to your review of our changes! 

(Also please see previous posts on changes because there have been a few since your last review.) 

Thanks,
John Lawson

**Comment by hpages** [comment]
Hi John,

Was nice talking with you in Boston. Thanks a lot for making all these changes, they sound great! I'll take a look at them ASAP. Sorry for the slow response and thanks for your patience.

Cheers,
H.

**Comment by hpages** [comment]
Hi John,

These changes greatly improve the usability of MIRA. The 2 vignettes are excellent! Thanks for all the work you've put into the package. It will be a great addition to Bioconductor.

It's ok to stick with data.table objects for representing the bisulfite data. If one day you decide to switch to GPos, it will be an easy change anyway. Note that despite the fact that the genomic positions are typically not consecutive in the bisulfite data table, using GPos still reduces memory footprint significantly (by about 35% for `exampleBSDT`) because the metadata columns can then be stored as Rle objects, which you can't do with data.table. The more Rle metadata columns, the more memory footprint reduction you'll get compared to data.table. Also in my experience, reducing memory footprint almost always improve speed. Objects with big memory footprints are inherently slow to process. Especially on a machine with reduced memory where the OS will start swapping data to disk because of the size of the objects. If reduction of memory footprint can allow some users to go from swapping to not swapping, then the speed boost will be dramatic e.g. by 1000x or more!

Anyway the package is in very good shape and almost ready to go. Just a couple of minor cosmetic issues:

a) Note that `"BSseq" %in% class(BSDT)` will fail (but shouldn't) if `BSDT` is a BSseq derivative. The proper idiom for testing whether object `BSDT` is a BSseq object is with `is(BSDT, "BSseq")`. This will return `TRUE` if `BSDT` belongs to the BSseq class or one of its subclasses.

b) Please use `<-` instead of `=` for assignment.

c) The title in the man pages of the `exampleBSDT` and `bigBinDT1` datasets is too long for a title (7 lines, 3 sentences for exampleBSDT; 5 lines, 3 sentences for bigBinDT1). These titles are actually an exact copy of the Description section. Please use appropriate titles.

d) The man page for the `exampleBSseqObj` dataset has the same problem.

Thanks again for all the good work and for your patience,
H.

**Comment by j-lawson** [comment]
Hi Herve,

Thanks for the additional feedback! You have a good point about the memory footprint of the metadata and I will keep that in mind. I fixed the things you commented on: I changed the %in% statements to is() statements, updated the assignment operators, and added titles for our built-in data. The build system reported an error for MIRA on Windows but I was not able to find the error when looking at the "CHECK" report. There was a line in the report that said, 
" 'BiocCheck' is not recognized as an internal or external command,
operable program or batch file." 
so I am wondering if this a an error with the build system itself?

Thanks,
John

**Comment by hpages** [comment]
Hi John,
This was a hiccup with the Windows builder. Let's ignore it. Everything looks good now. I'm marking the package as accepted.
Cheers,
H.

**Comment by j-lawson** [comment]
Hi Hervé,

Great! Thanks for all the input and suggestions about the package! 

Best,
John

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/j-lawson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MIRA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MIRA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
