### ISSUE TITLE
MOSClip

### ISSUE THREAD

**Issue by AnnaBortolato** [Bioconductor/Contributions#3560]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CaluraLab/MOSClip

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@anna-bortolato - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

- [ ] REQUIRED: The installation instructions should also include how to install the package from Bioconductor.

## NEWS 

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

## R code

- [ ] SUGGESTION: Avoid 'suppressWarnings'/'*Messages' if possible.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 72 lines that are not.

Best,
Kayla

**Comment by AnnaBortolato** [comment]
Dear @Kayla-Morrell, 
Thank you for your reply. We made some changes to accomplish some of your requests.

## General package development
- [x] REQUIRED: The installation instructions should also include how to install the package from Bioconductor.

We added instructions for installation from Bioconductor in the README.md file.

## NEWS
- [x] SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

We included a NEWS file in the package.

## R code
- [ ] SUGGESTION: Avoid 'suppressWarnings'/'*Messages' if possible.

This suppressWarnings is used to suppress a warning generated by a function for plotting (plotFrequencies). The warning is "Vectorized input to `element_text()` is not officially supported. ℹ Results may be unexpected or may change in future versions of ggplot2". We are aware of this warning and we will monitor the behavior of the function with future versions of ggplot2. At the moment this warning is not affecting the final output of the function and we think it could be annoying for the user; for this reason, we would like to keep the suppressWarnings in the code. 

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 72 lines that are not.

We used styler R package to indent lines. At the moment, only 72 lines, that correspond to the 1% of the code and are mainly in the vignette, are not correctly indented.


Let us know if it is ok, 
thank you

Anna

**Comment by Kayla-Morrell** [comment]
@anna-bortolato - Thank you for making the necessary changes and/or providing clarification on the other notes. I have reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anna-bortolato.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MOSClip")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MOSClip

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
