### ISSUE TITLE
MetMashR

### ISSUE THREAD

**Issue by grlloyd** [Bioconductor/Contributions#3582]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/computational-metabolomics/MetMashR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by grlloyd** [comment]
This package extends our existing package [struct](https://bioconductor.org/packages/release/bioc/html/struct.html) and compliments our [structToolbox](https://bioconductor.org/packages/release/bioc/html/structToolbox.html) package by adding a new set of templates and workflow steps to facilitate the processing of metabolite annotations from multiple sources/databases.

**Comment by hpages** [comment]
Thanks @grlloyd for this new submission.

Package looks good overall. The vignettes are great!

Some minor things, mostly cosmetic:

1. Code readibility. For example, here's the code you're showing in the man page for `AnnotationDb_database`:
    ```
    M = AnnotationDb_database( table = character(0), tag = character(0),
    data = data.frame(), source = character(0))
    ```
   It looks like the 2 lines of code are both assignments (`M =` and then `data =`).  when in fact there's only one assignment (to `M`) and the 2nd line is the continuation of the 1st line.
   Readibility could be greatly improved by:
   - Using `<-` rather than `=` for the assignment.
   - Indenting the 2nd line.

   It will look like this:
    ```
    M <- AnnotationDb_database(table = character(0), tag = character(0),
                               data = data.frame(), source = character(0))
    ```
   This was just an example. Please make sure to use `<-` for assignment and proper indentation everywhere in the package (i.e. in the vignettes, man page examples, internal code, and unit tests).

2. `R CMD check` reports problematic use of curly brackets in many man pages (see Single Package Builder report above). For eample:
    ```
    * checking Rd files ... [1s/1s] NOTE
    checkRd: (-1) AnnotationDb_database.Rd:54: Lost braces; missing escapes or markup?
        54 | Other {annotation databases}: 
           |       ^
    checkRd: (-1) BiocFileCache_database.Rd:78: Lost braces; missing escapes or markup?
        78 | Other {database}: 
           |       ^
    checkRd: (-1) GO_database.Rd:61: Lost braces; missing escapes or markup?
        61 | Other {annotation databases}: 
           |       ^
    etc...
    ```
   This NOTE should not be ignored.

3. Are the functions prefixed with a dot (`.`) meant for the end user? Good practice is to only export (and document) functions and symbols that are meant to be used by your users. All the other things used internally in your package should remain well.. internal i.e. non-exported.

Best,
H.

**Comment by grlloyd** [comment]
Dear @hpages 

Thank you for your review comments. We are pleased you like the vignettes. We have pushed to following changes in response to your other comments:

- We have used `styler` in combination with `biocthis::bioc_style` to try and make our code fit the style guidelines more closely, and specifically checked that the assignment operator `<-` is used instead of `=` in all cases.
- We have updated our documentation to ensure that `<-` is used for assignment, and improved the code indentation of our examples.
- We have resolved the incorrect use of curly braces causing cmd check warnings
- We have renamed all functions starting with a dot that are intended for external use to names without a dot, and updated our documentation accordingly.

Best regards,

Gavin

**Comment by hpages** [comment]
Sounds good. Thanks!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/grlloyd.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MetMashR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetMashR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
