### ISSUE TITLE
LimROTS

### ISSUE THREAD

**Issue by AliYoussef96** [Bioconductor/Contributions#3599]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/AliYoussef96/LimROTS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by js2264** [comment]
Hi @AliYoussef96, sorry for the wait, I am now going through your package. I'll come back to you with a full review later today, but one thing I wonder whether you could wrap the object returned by  the`LimROTS()` main function into a `SummarizedExperiment` object? You don't necessarily need to create a new class for your package if you don't want to, you could simply append the result data to the `metadata` or `colData` of the original SE object. I believe changes would be mostly transparent to the end-user (eg you can still access to `limrots.results$BH.pvalue`, but would maintain a data structure familiar to Bioc users.

**Comment by AliYoussef96** [comment]
Hi @js2264, 

Thank you for taking the time to review the package! I appreciate your suggestion and think it’s a great idea. I’ll make the adjustment to wrap the object returned by the `limROTS()` function into a `SummarizedExperiment` object, later today.

**Comment by js2264** [comment]
## Overall comments

The `{LimROTS}` package source code is in relatively good shape and the package is well documented. However, there are a few points that could be improved. As it is, `SummarizedExperiment` objects are used as input to the main function `LimROTS()`, but the results are returned as a list. Bioconductor end-users are used to working with `SummarizedExperiment` objects and endomorphic functions. Returning the results as an updated `SummarizedExperiment` object would greatly improve the user experience.

The package needs a few updates to be compliant with the Bioconductor guidelines, in particular to implement more formal tests and well as argument checks in the main function.
Currently, the main function `LimROTS()` will fail with non-very-helpful error messages if some arguments are not explicitely specified by the end-user. 

My review is based on the current Bioconductor guidelines and reviewer checklist (https://contributions.bioconductor.org/docs/package-review-checklist.md). 

## The DESCRIPTION file

Refer to the [DESCRIPTION](https://contributions.bioconductor.org/description.html) section in the BioC package guideline for details on the individual points.

- [ ] `Depends`, `Imports`, `Suggests`, `Enhances` fields.

Bioconductor 3.21 (current `devel`) will work along R `4.5.0`. Please update R version dependency from 4.4.0 to 4.5.0. 

Also, I'd suggest moving `SummarizedExperiment` to the `Depends:` field, if you 
do end up using it as a container for your results object. 

## The NAMESPACE file

- [ ] Function names use `camelCase` or `snake_case` and do not include `.`.

`bootstrapSamples.limRots()` function has a `.` in the name. This `.` nomenclature suggests that you have defined a generig `bootstrapSamples()` function and then a method for a specific `limRots` class, however this is not the case. Consider renaming the function to remove the `.`. Also consider not exporting this function if not used by end-users (see below). 

Other functions (eg `calOverlaps.slr()`) have a `.` in the name, but they are not 
exported. Consider fixing it for consistency.

- [ ] Selective imports using `importFrom` instead of *import all* with `import`.

All functions from `doRNG` and `utils` packages are imported, which is not necessary. 
In the case of `doRNG`, it is not a huge problem, as only few functions are exported by the package. However, in the case of `utils`, it is better to import only the necessary functions. Currently, end-users may end up with conflicts during their analysis if they run `library(LimROTS)` and it imports all functions from `utils` under the hood. 

- [ ] Individual functions/methods are exported instead of all.

Why are `bootstrapS()`, `bootstrapSamples.limRots()` and `calculateFalseDiscoveryRate()` exported? Their documentation does not suggest that they are intended for end-users. If they are indeed meant to only be used internally, consider not export them. 

## The NEWS file

- [x] News file in correct location and format.

It's nice to have a NEWS file in the package, but it is not strictly mandatory. If you do have one, please make sure it is regularly updated!

## Documentation

- [ ] Vignette present and does describe the core functionality of the package.

In the "Parameter Description for `LimROTS`" section, consider first mentioning that 
the `LimROTS()` function is the main function provided to the end users in the `{LimROTS}` package. 

Consider removing the list of all parameters in this section. If these parameters or 
their description evolves, it is likely that the vignette will become outdated. Instead,
consider linking to the help page of the function, which will always be up-to-date.

- [ ] Vignette has an *Introduction* section. This should include motivation for inclusion to Bioconductor

Following Bioconductor's recommendation, consider adding a section that describes the main purpose of the package. This could be a lightened version of what you have in the README, for example.

- [ ] Vignette has an *Installation* section.

Consider adding an "Installation" section with: 

``````
```{r, eval=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ROTS")
```
``````

- [ ] When relevant, vignette provides review/comparison to other packages with similar functionality or scope

I am not familiar with `ROTS`, but would a comparison between `LimROTS` and `ROTS` be useful for the users, to highlight the benefits of using `LimROTS`?

## Unit tests

- [ ] Unit tests present and covering large part of core functionality.

Several tests are included, but not for the main user-facing function `LimROTS()`. Consider adding tests for this function.

## R code

- [ ] Re-use of classes and functionality (if appropriate).

As suggested, consider using `SummarizedExperiment` as a container for the results object. 

- [ ] Functional programming: no code repetition.

- [ ] Function argument names descriptive and documented.

IMO, `B` argument is rather obscure. Why not something more generic, eg `niter`? I would suggest renaming this argument.

In `SanityChecK()`, many arguments are not used (eg, `a1`, `formula.str`, ...). Consider removing them if they are not used.

- [ ] Function arguments are tested for validity.

Perhaps this is linked to the point just above, but if `meta.info`, `group.name` or `fomula` (and perhaps other arguments) are not specified (default are `NULL`), `LimROTS()` will throw an error. Consider adding failsafe mechanisms to handle these cases. Or even better, consider having these arguments as required (ie do not specify any default value), if they are indeed necessary for the function to run.

- [ ] Parallelisation uses `BiocParallel`.

For parallelized computing, could you rely on `BiocParallel` generic infrastructure, rather than `parallel`? Or do you have a strong reason not to use it? You may find that it is easier to maintain in the long term.

**Comment by AliYoussef96** [comment]
Hi @js2264 

Thank you again for taking the time to provide the review for the package. I am almost done addressing all of the comments, but regarding `BiocParallel`, I tried to make it work on Windows with `SnowParam`. Unfortunately, it cannot access the unexported functions from the package. As a result, using `BiocParallel` for now will restrict the package to be used only on Linux and macOS. I am unsure if there is a way to export these functions to the workers, or if I may have overlooked something.

**Comment by js2264** [comment]
Great to read that you are making good progress. 
Regarding `SnowParam()`: which unexported functions do you want to use within a `SnowParam` call? Some from your package? It should run ok, AFAICT. Would you mind sharing more detail?

**Comment by AliYoussef96** [comment]
Yes the functions are from my package.

So, this is the modified `Boot_parallel` function.

```{r}
Boot_parallel <- function(i , seed.cl = 1234, samples, data,
formula.str, group.name, groups, meta.info,
a1 = NULL, a2 = NULL, trend = TRUE, robust = TRUE,
permutating.group = FALSE) {
samples.R <- split(samples[i, ], groups)
d_result <- s_result <- pd_result <- ps_result <- NULL
if (is.null(a1) | is.null(a2)) {
fit <- Limma_bootstrap(
x = lapply(samples.R, function(x) data[, x]),
group.name = group.name, meta.info = meta.info,
formula.str = formula, trend = trend, robust = robust
)
d_result <- fit$d
s_result <- fit$s
}
pFit <- Limma_permutating(
x = lapply(split(seq_len(length(groups)), groups), function(x) data[, x]),
group.name = group.name, meta.info = meta.info,
formula.str = formula, trend = trend, robust = robust,
permutating.group = permutating.group
)
pd_result <- pFit$d
ps_result <- pFit$s
return ( list(
ds = data.frame(d_result = d_result, s_result = s_result),
pdps = data.frame(pd_result = pd_result, ps_result = ps_result)
) )
}
````

Then, this function was called from the main `LimROTS` function as follows:

```{r}
BPPARAM <- SnowParam(workers = 4)
results_list <- bplapply(seq_len(nrow(samples)), FUN = Boot_parallel,
BPPARAM = cluster,
seed.cl = seed.cl,
samples = samples,
data = data,
formula.str = formula.str,
group.name = group.name,
groups = groups,
meta.info = meta.info,
a1 = a1 , a2 = a2,
trend = trend,
robust = robust,
permutating.group = permutating.group)
````

Which throws an error

```{r}
Error in Limma_bootstrap(x = lapply(samples.R, function(x) data[, x]), : could not find function "Limma_bootstrap"
````

I tried to export them using the `exports` option from `BPOPTIONS`, but it did not work either.  This is happening when creating vignettes, and I try to build the package using `devtools::build()`.

**Comment by AliYoussef96** [comment]
Hi @js2264 

Regarding `BiocParallel`, I got it to work. I’m not sure if this is the ideal solution, but it works with `BiocParallel` now.  
I had to export the functions to the workers in this way.

```{r}
      for (name in names(export_funcs)) assign(name, export_funcs[[name]])
```

The `Boot_parallel()` function now look like this

```{r}
Boot_parallel <- function(cluster = NULL, seed.cl, samples, data,
                          formula.str, group.name, groups,
                          meta.info, a1, a2, trend, robust,
                          permutating.group) {
  
  if (is.null(cluster)) {
    if (isWindows()) {
      cluster <- SnowParam(workers = 2)
      message("Using SnowParam (Windows) with two workers.")
    } else {
      cluster <- MulticoreParam(workers = 2)
      message("Using MulticoreParam (Unix-like OS) with two workers.")
    }
  } else {
    message("Using provided parallel backend cluster.")
  }
  
  cluster$RNGseed <- seed.cl
  
  export_vars <- list(
    samples = samples,
    data = data,
    formula.str = formula.str,
    group.name = group.name,
    groups = groups,
    meta.info = meta.info,
    a1 = a1,
    a2 = a2,
    trend = trend,
    robust = robust,
    permutating.group = permutating.group
  )
  
  export_funcs <- list(
    Limma_bootstrap = Limma_bootstrap,
    Limma_permutating = Limma_permutating
  )
      for (name in names(export_vars)) assign(name, export_vars[[name]])
      for (name in names(export_funcs)) assign(name, export_funcs[[name]])
  
  results_list <- bplapply(
    seq_len(nrow(samples)),
    function(i) {
      samples.R <- split(samples[i, ], groups)
      d_result <- s_result <- pd_result <- ps_result <- NULL
      if (is.null(a1) | is.null(a2)) {
        fit <- Limma_bootstrap(
          x = lapply(samples.R, function(x) data[, x]),
          group.name = group.name, meta.info = meta.info,
          formula.str = formula.str, trend = trend, robust = robust
        )
      }
      d_result <- fit$d
      s_result <- fit$s
      df1 <- data.frame(d_result = d_result, s_result = s_result)
      pFit <- Limma_permutating(
        x = lapply(split(seq_len(length(groups)), groups), function(x)
          data[, x]),
        group.name = group.name, meta.info = meta.info,
        formula.str = formula.str, trend = trend,
        robust = robust, permutating.group = permutating.group
      )
      
      pd_result <- pFit$d
      ps_result <- pFit$s
      df2 <- data.frame(pd_result = pd_result, ps_result = ps_result)
      list(ds = df1, pdps = df2)
    },
    BPPARAM = cluster, BPOPTIONS = bpoptions(packages = c("utils", "stringr", "stats", "limma"))
  )
  
  return(results_list)
}
```

**Comment by js2264** [comment]
@AliYoussef96 let's see what the Bioc Builder says and move from there. I'll review your changes once you've bumped version and pushed to bioconductor upstream!

**Comment by AliYoussef96** [comment]
Hi @js2264 

The package has been successfully built without errors or warnings on all platforms, and I have carefully addressed all the comments you provided:

1. I introduced `LimROTS` as the main user-facing function.  
2. All unnecessary parameters in the vignette have been removed.  
3. An introduction section has been added to the vignette for better context.  
4. Installation instructions for `ROTS` and `limma` have been included in the vignette.  
5. A comparison of `LimROTS` with `ROTS` and `limma` has been added to the vignette.  
6. A unit test has been implemented for the `LimROTS()` function.  
7. Results from `LimROTS` are now appended to the input `SummarizedExperiment` object.  
8. The argument `B` has been renamed to `niter` for clarity.  
9. Arguments essential for running `LimROTS` now have no default values to avoid unintended behavior.  
10. The parallelization framework now uses `BiocParallel`, adhering to Bioconductor standards.

**Comment by AliYoussef96** [comment]
Hi @js2264 

Are there any updates on the final version I pushed to Bioconductor upstream?

Thank you!

**Comment by js2264** [comment]
Hi @AliYoussef96 , 

Updates look great, thank you. Minor suggestions for future updates: 

- `cluster` parameter, which takes a `BiocParallelParam` object: this argument is traditionally named `BPPARAM` and passed directly to the `BPPARAM` argument of the `{BiocParallel}` function used internally (in your case: `bplapply()`). 
- In the vignette, you use `elementMetadata()`, which is ok, but the way people typically access this data is with `rowData()`. This way, you don't have to manually define the columns to import, just run: `limrots.result.df <- as_tibble(rowData(UPS1.Case4), rownames = 'proteins')`
- I would strongly advise improving the coverage, in particular for `R/LimROTS.r` file. 

```{r}
> covr::package_coverage('repos/bioconductor/LimROTS')
LimROTS Coverage: 62.98%
R/Bootstrap_functions.r: 18.60%
R/Check_SummarizedExperiment.R: 19.23%
R/Check_meta_info.R: 35.71%
R/LimROTS.r: 47.58%
R/Boot_parallel.R: 51.72%
R/Limma_permutating.R: 65.91%
R/Limma_fit.R: 69.70%
R/Limma_bootstrap.r: 77.94%
R/SanityChecK.R: 87.80%
R/Optimizing.R: 96.15%
R/calculateFalseDiscoveryRate.R: 100.00%
R/calOverlaps_slr.R: 100.00%
R/calOverlaps.R: 100.00%
```

I'll accept the package as it is now, but feel free to implement the suggestions above in a newer version (incrementing eg to `0.99.11` and pushing to bioconductor `upstream` branch, as always).

**Comment by AliYoussef96** [comment]
Hi @js2264 

Thank you again for taking the time to review the package! I will take your latest suggestions into consideration and might work on them later today!

**Comment by AliYoussef96** [comment]
hi @lshep 

I made some minor changes as suggested, and a new version (v0.99.11) is now available on the default branch of my GitHub repository. However, the last version I pushed to the Bioconductor upstream was v0.99.10. Will this cause any issues for the next steps?

Also, can I know the timeline for the package to be published on Bioconductor? 

Thanks!

**Comment by lshep** [comment]
The version on github is inconsequential to Bioconductor;  Bioconductor will only know of what is pushed to git.bioconductor.org.  We recommend keeping them in sync for easier maintenance. 
The message above indicated that the package was accepted and a push occurred after acceptance.  basically to let the reviewer know there were changes made before the package has been processed that might need to be looked at.  Since the package is accepted it no longer gets a build on demand feature and will be moved to the daily builder that builds, well, daily.   The version we have pushed is also 0.99.11 so I think you are all set
I normally process packages Tue/Fri loosely.  So it will be added today or tomorrow and be building over the weekend (early next week at the very latest)

**Comment by AliYoussef96** [comment]
Thank You!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/AliYoussef96.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("LimROTS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/LimROTS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
