### ISSUE TITLE
plyxp

### ISSUE THREAD

**Issue by jtlandis** [Bioconductor/Contributions#3616]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jtlandis/plyxp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jtlandis** [comment]
Hello @hpages, 
Please note this is a resubmission of #3572  except under a new name to better represent the functionality of the package. Shall I close the other submission?

**Comment by hpages** [comment]
Great, thanks! I'll close the **biocmask** submission (issue #3572).

@lshep Can you please ingest and reassign me? Thanks

**Comment by hpages** [comment]
@jtlandis Looks like you still have a few occurences of "biocmask" in the source code:
```
hpages@XPS15:~/plyxp$ find . -type d -name '.git' -prune -o -type f -exec grep -Hi 'biocmask' {} \;
./LICENSE:COPYRIGHT HOLDER: biocmask authors
./R/biocmask.R:#' @title New Biocmask
./R/data.R:#' @title Biocmask Simple Example Summarized Experiment
./man/se_simple.Rd:\title{Biocmask Simple Example Summarized Experiment}
./LICENSE.md:Copyright (c) 2024 biocmask authors
./NEWS:## biocmask 0.99.18
./NEWS:## biocmask 0.99.13
./NEWS:  ever becomes loaded with `biocmask`.
./NEWS:## biocmask 0.99.12
./NEWS:## biocmask 0.99.11
```
Also some filenames still contain "biocmask":
```
hpages@XPS15:~/plyxp$ find . -name '*biocmask*'
./R/biocmask.R
./R/biocmask-R6.R
./R/biocmask-quos.R
./R/biocmask-R6-manager.R
./tests/testthat/test_biocmask_R6.R
./tests/testthat/test_biocmask_manager.R
```

Anyways, the major issue remains: loading **plyxp** after **tidySummarizedExperiment** breaks the latter:
```
library(tidySummarizedExperiment)
data(pasilla)
pasilla |> filter(.sample == "untrt1")
## A SummarizedExperiment-tibble abstraction: 14,599 × 5
## Features=14599 | Samples=1 | Assays=counts
#   .feature    .sample counts condition type      
#    <chr>       <chr>    <int> <chr>     <chr>     
#  1 FBgn0000003 untrt1       0 untreated single_end
#  2 FBgn0000008 untrt1      92 untreated single_end
#  3 FBgn0000014 untrt1       5 untreated single_end
#  4 FBgn0000015 untrt1       0 untreated single_end
#  5 FBgn0000017 untrt1    4664 untreated single_end
#  6 FBgn0000018 untrt1     583 untreated single_end
#  7 FBgn0000022 untrt1       0 untreated single_end
#  8 FBgn0000024 untrt1      10 untreated single_end
#  9 FBgn0000028 untrt1       0 untreated single_end
# 10 FBgn0000032 untrt1    1446 untreated single_end
## ℹ 40 more rows
## ℹ Use `print(n = ...)` to see more rows
```
Now loading **plyxp**:
```
library(plyxp)
# Registered S3 methods overwritten by 'plyxp':
#   method                         from                    
#   filter.SummarizedExperiment    tidySummarizedExperiment
#   group_by.SummarizedExperiment  tidySummarizedExperiment
#   mutate.SummarizedExperiment    tidySummarizedExperiment
#   pull.SummarizedExperiment      tidySummarizedExperiment
#   select.SummarizedExperiment    tidySummarizedExperiment
#   summarise.SummarizedExperiment tidySummarizedExperiment
#   summarize.SummarizedExperiment tidySummarizedExperiment
# ────────────────────────────────────────────────────────────────────────────────
# ! you have loaded plyxp after tidySummarizedExperiment
# 
# Note that these packages are exclusive and present different APIs for working
# with <SummarizedExperiment> objects. As such conflicts and unexpected behaviors
# may arise!
#
# Attaching package: ‘plyxp’
# 
# The following object is masked from ‘package:stats’:
# 
#     filter
```
I appreciate the effort to warn the user about things getting nasty from there, but still:
```
pasilla |> filter(.sample == "untrt1")
# Error in `filter()`:
# ! Cannot filter in `assays` context
# ✖ review expression indices 1 in dots
# ℹ consider wrapping expressions in rows(...) or cols(...)
# Run `rlang::last_trace()` to see where the error occurred.
```
I don't think this is acceptable.

Remember that the user won't necessarily choose to have both **plyxp** and **tidySummarizedExperiment** on their search path. This might happen without them even being aware e.g. as a side effect of loading other packages that depend directly or indirectly on one or the other.

FWIW this even confuses the **conflicted** package (which could have been a good option to explore here to try and make things more user-friendly, _maybe_):
```
library(conflicted)
pasilla |> filter(.sample == "untrt1")
# Error:
# ! [conflicted] filter found in 2 packages.
# Either pick the one you want with `::`:
# • plyxp::filter
# • stats::filter
# Or declare a preference with `conflicts_prefer()`:
# • `conflicts_prefer(plyxp::filter)`
# • `conflicts_prefer(stats::filter)`
# Run `rlang::last_trace()` to see where the error occurred.
```
Unfortunately, it doesn't list the `filter.SummarizedExperiment` method defined in **tidySummarizedExperiment**, probably because it isn't exported.

I don't think we want to allow mutually exclusive packages in Bioconductor, sorry. This would be a first. Since the beginning of Bioconductor there's been a strong focus on avoiding them and making sure that all the packages in the ecosystem work in harmony. See for example the coordination/centralization of S4 generics via packages like **BiocGenerics**, **MatrixGenerics**, **ProtGenerics**, etc... Their purpose was exactly to avoid these kinds of conflicts.

Best,
H.

**Comment by jtlandis** [comment]
Hello @hpages 

Thank you for taking the time to review the package. I have intentionally left some file names as "biocmask" as a reminder of the files that may be split into its own package in the future. I can change the name of these files and references to the old name if it truly is an issue.

The main reason `plyxp` was developed was to provide a faster alternative to `tidySummarizedExperiment` which with large data sets, is unreasonably slow to use. I do not feel that having `tidySummarizedExperiment` flat out use `plyxp` would be a good solution at first since their syntax's are wildly different. It would be too much of a breaking change for `tidySummarizedExperiment` to adopt.

There are a few avenues we could take given your feedback.

1) Forego submitting `plyxp` to Bioconductor and let it live on Github in the meantime.
2) Not export `dplyr` generics, but perhaps new generics with suffixed names specific to `plyxp`, such as `mutate_xp(.data, ...)` or `mutate_ctx(.data, ...)`.
3) Create a Shell S4 object just for the purpose of avoiding namespace conflicts. This would have an effect on opting into `plyxp` syntax based on the return type.

**Comment by hpages** [comment]
Hi @jtlandis,

> I have intentionally left some file names as "biocmask" as a reminder of the files that may be split into its own package in the future. I can change the name of these files and references to the old name if it truly is an issue.

Up to you. Just wanted to bring this to your attention just in case it was unintentional.

> The main reason plyxp was developed was etc...

I understand what you are trying to achieve, at least I think, and I appreciate the work that you're doing. It's an interesting and novative approach. I do see the value in it. If the package was not introducing such a blatant conflict with an existing Bioconductor package, I would be more than happy to accept it. Unfortunately, it's a little bit of an "early bird get the worm" situation, in the sense that, whoever first came up with an API (i.e. set of verbs + syntax) for operating on SE-as-tibble abstractions got the privilege to "set the rules".  They established a de-facto standard and now they own it. So whoever comes after that must be careful to do it in a non-conflicting manner.

> 1. Forego submitting plyxp to Bioconductor and let it live on Github in the meantime.

Hopefully there's a better option. My goal was never to discourage you.

> 2. Not export dplyr generics, but perhaps new generics with suffixed names specific to plyxp, such as `mutate_xp(.data, ...)` or `mutate_ctx(.data, ...)`.
> 3. Create a Shell S4 object just for the purpose of avoiding namespace conflicts. This would have an effect on opting into plyxp syntax based on the return type.

Both options sound like valid approaches to me. In my view there are some important object design considerations to keep in mind when treating a SummarizedExperiment as a tibble abstraction. This abstraction is _conceptually_ a different object. Its _shape_ (i.e. dimensions) in particular is different. So IMO the cleaner approach is to create a shell S4 object to reflect (and formalize) its different nature. And yes, it should be a _shell_ object as you're proposing, and not an extension. In other words _composition_ should be used here and not _inheritance_.

This might involve some significant refactoring of the package so maybe it won't be ready in time for the 3.20 release (in less than 2 weeks). I hope it's ok.

Thanks for understanding and for your patience. Looking forward to see what you will come up with.

Best,
H.

**Comment by jtlandis** [comment]
Hello @hpages 

Could you please clarify what you mean by "composition" vs "inheritance"? 

I have thought of a possible 4th option.

`plyxp` takes `tidySummarizedExperiment` as a dependency, ensuring that it is always loaded before `plyxp`.

`plyxp`'s `dplyr` methods will use `tidySummarizedExperiment` methods by default, but will use `plyxp`'s methods dependent on the presence of a metadata field:

```r
## example code

tidySE_namespace <- loadNamespace("tidySummarizedExperiment", partial = TRUE)
mutate_tidyse <- get("mutate.SummarizedExperiment", envir = tidySE_namespace)
mutate_plyxp <- function(.data, ...) {
 # ...
}
 
#' @export
use_plyxp <- function(x) {
  metadata(x)[["use_plyxp"]] <- TRUE
  x
}

 #' @export
 mutate.SummarizedExperiment <- function(.data, ...) {
   if (isTRUE(metadata(.data)[["use_plyxp"]])) {
    mutate_plyxp(.data, ...)
    } else {
    mutate_tidyse(.data, ...)
  }
 }
```

Pros: `plyxp`'s functionality is gated behind an opt-in mechanism on the class and will not clash with `tidySummarizedExperiment` by default
Cons: takes a fairly heavy dependency of `tidySummarizedExperiment`.

> Both options sound like valid approaches to me. In my view there are some important object design considerations to keep in mind when treating a SummarizedExperiment as a tibble abstraction. This abstraction is conceptually a different object. Its shape (i.e. dimensions) in particular is different. 

For clarity, the "tibble-abstraction" in `tidySummarizedExperiment` is partly for printing, but a valid way to think of how `tidySummarizedExperiment` handles its operations. In part, this is why `tidySummarizedExperiment` is slow. In `plyxp`, the "show_tidy" is only for glimpsing at the data like a tibble, however our operations do not unwide data into a tibble, so its dimensionality is preserved.

**Comment by hpages** [comment]
Well, you want to use **dplyr** verbs like `arrange()`, `filter()`, `mutate()`, `select()`, etc... They all expect a _data-frame-like_ object so what you will pass to them better be a data-frame-like object.

In your case it's going to be an object that represents the _long form_ version of a SummarizedExperiment object. This does not mean that you actually need to unwind the assay data in your object, it only means that your object should look and feel _like_ it contains the unwinded data.

More concretely:
```
## LF stands for long form ("tidy" prefix already taken by the tidySummarizedExperiment package).
setClass("LFSummarizedExperiment", slots=c(x="SummarizedExperiment"))
```
As you can see, I use _composition_ ("has a" relationship), not _inheritance_ ("is a" relationship). Using inheritance means making LFSummarizedExperiment a subclass (a.k.a. extension) of SummarizedExperiment, by doing:
```
setClass("LFSummarizedExperiment", contains="SummarizedExperiment")  # don't do this!
```
Then:
```
## Constructor:
LF <- function(x) new("LFSummarizedExperiment", x=x)

setMethod("show", "LFSummarizedExperiment", function(object) show_tidy(object@x))

lfse <- LF(se_simple)
lfse
## A SummarizedExperiment-tibble Abstraction: 5 × 4
#     .features .samples | counts logcounts | gene  length direction | sample
#     <chr>     <chr>    |  <int>     <dbl> | <chr>  <int> <chr>     | <chr> 
#   1 row_1     col_1    |     14      2.64 | g1         1 -         | s1    
#   2 row_2     col_1    |     19      2.94 | g2        24 +         | s1    
#   3 row_3     col_1    |     16      2.77 | g3        60 +         | s1    
#   4 row_4     col_1    |     11      2.40 | g4        39 -         | s1    
#   5 row_5     col_1    |     18      2.89 | g5        37 +         | s1    
#   …   …         …             …        …     …         … …            …    
# n-4 row_1     col_4    |      9      2.20 | g1         1 -         | s4    
# n-3 row_2     col_4    |      4      1.39 | g2        24 +         | s4    
# n-2 row_3     col_4    |     20      3.00 | g3        60 +         | s4    
# n-1 row_4     col_4    |      3      1.10 | g4        39 -         | s4    
# n   row_5     col_4    |      5      1.61 | g5        37 +         | s4    
## ℹ n = 20
## ℹ 1 more variable: condition <chr>
```
Define the **dplyr** verbs as follow (they must act as endomorphisms):
```
filter.LFSummarizedExperiment <- function(.data, ..., .preserve=FALSE)
    LF(plyxp:::filter.SummarizedExperiment(.data@x, ..., .preserve=.preserve))

filter(lfse, cols(condition=="drug"))
## A SummarizedExperiment-tibble Abstraction: 5 × 2
#    .features .samples | counts logcounts | gene  length direction | sample
#    <chr>     <chr>    |  <int>     <dbl> | <chr>  <int> <chr>     | <chr> 
#  1 row_1     col_3    |      7      1.95 | g1         1 -         | s3    
#  2 row_2     col_3    |      1      0    | g2        24 +         | s3    
#  3 row_3     col_3    |     15      2.71 | g3        60 +         | s3    
#  4 row_4     col_3    |     10      2.30 | g4        39 -         | s3    
#  5 row_5     col_3    |     12      2.48 | g5        37 +         | s3    
#  6 row_1     col_4    |      9      2.20 | g1         1 -         | s4    
#  7 row_2     col_4    |      4      1.39 | g2        24 +         | s4    
#  8 row_3     col_4    |     20      3.00 | g3        60 +         | s4    
#  9 row_4     col_4    |      3      1.10 | g4        39 -         | s4    
# 10 row_5     col_4    |      5      1.61 | g5        37 +         | s4    
## ℹ 1 more variable: condition <chr>
```
`lfse` _looks and feels_ like a tibble. This makes it a _data-frame-like_ object.

To formalize their data-frame-like nature, LFSummarizedExperiment objects should try to mimic the data.frame API, or at least a subset of it, by supporting things like `dim()`, `nrow()`, `ncol()`, `length()`, `colnames()`, `names()`, `[[`, `$`, etc... Note that having `dim()` and `length()` return the dimensions and length (i.e. nb of columns) of the tibble abstraction, instead of the dimensions and length of the original SummarizedExperiment object, is what I was alluding to earlier when I said that the _shape_ (i.e. dimensions) of your shell object is different from the shape of the original object.

Of course supporting the full data.frame API is not going to happen e.g. things like `[`, `cbind()`, `rbind()` don't really make sense on LFSummarizedExperiment objects.  

Hope this clarifies,
H.

**Comment by jtlandis** [comment]
Hello @hpages 

We have changed the implantation for our `dplyr` verbs to be utilized on a new S4 shell class named `PlySummarizedExperiment`. We have provided the accessor function `se()` to access the underlying `SummarizedExperiment` object. 
Since this is a new class, its default show method is the `show_tidy()` method created earlier in our previous comments.

I would like to take a moment to emphasize that it is never the intention of `plyxp`'s to have the user think about the SummarizedExperiment object as a "long form" data frame. Instead it's specific syntax within dplyr verbs enforce users to think about the SummarizedExperiment structure, in either the contexts of the rowData, the colData, or assays.

The print method, is simply a convenience to view the data within, not to imply a certain underlying structure.

**Comment by hpages** [comment]
Hi @jtlandis,

Thanks for the changes.

> I would like to take a moment to emphasize that it is never the intention of plyxp's to have the user think about the SummarizedExperiment object as a "long form" data frame.

Really? Now I'm confused and I'm wondering what was the reason you were originally trying to display the long form version of the SummarizedExperiment object _by default_, hence masking its native form.

FWIW I cannot tell you how much I found it helpful to actually see the long form display. It really helped me understand what was going on e.g. it suddenly made sense and seemed natural to me that one would want to be able to feed such thing to a **dplyr** verb. I'm sure I won't be the only one to feel that way.

Anyways, I didn't mean to force you into that direction. Options (1), (2) and (4) above, or any other option that you can think of are ok with me as long as **plyxp** doesn't clash with **tidySummarizedExperiment**.

Taking a look at the latest version now...

**Comment by jtlandis** [comment]
@hpages 

Im glad you found the display helpful.  I always liked the DataFrame and and data.table printing methods in that they displayed top and bottom values of the data and I though to emulate those methods. `plyxp` does provide an interface into the SummarizedExperiment class that feels like a longform data.frame, but a user should still be aware or thoughtful of their object’s structure.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(plyxp)
#> 
#> Attaching package: 'plyxp'
#> The following object is masked from 'package:stats':
#> 
#>     filter
```

for example, the exported 5 x 4 SummarizedExperiment, we can get the size of each context using `dplyr::n()` and the `rows(...)` and `cols(...)` helpers to switch from the default context, which is “assays”.

``` r
dim(se_simple)
#> [1] 5 4
out <- mutate(se_simple,
       assay_seq = seq_len(n()), # default assay context
       rows( # evaluate within rowData context
         rowData_seq = seq_len(n())
       ),
       cols( # evaluate within colData context
         colData_seq = seq_len(n())
       ))
se(out) #access underlying data
#> class: SummarizedExperiment 
#> dim: 5 4 
#> metadata(0):
#> assays(3): counts logcounts assay_seq
#> rownames(5): row_1 row_2 row_3 row_4 row_5
#> rowData names(4): gene length direction rowData_seq
#> colnames(4): col_1 col_2 col_3 col_4
#> colData names(3): sample condition colData_seq
assay(out, "assay_seq")
#>       col_1 col_2 col_3 col_4
#> row_1     1     6    11    16
#> row_2     2     7    12    17
#> row_3     3     8    13    18
#> row_4     4     9    14    19
#> row_5     5    10    15    20
rowData(out)
#> DataFrame with 5 rows and 4 columns
#>              gene    length   direction rowData_seq
#>       <character> <integer> <character>   <integer>
#> row_1          g1         1           -           1
#> row_2          g2        24           +           2
#> row_3          g3        60           +           3
#> row_4          g4        39           -           4
#> row_5          g5        37           +           5
colData(out)
#> DataFrame with 4 rows and 3 columns
#>            sample   condition colData_seq
#>       <character> <character>   <integer>
#> col_1          s1       cntrl           1
#> col_2          s2       cntrl           2
#> col_3          s3        drug           3
#> col_4          s4        drug           4
```

Additionally data outside the contexts are not available

``` r
mutate(
  out,
  product = rowData_seq * colData_seq
)
#> Error in `.f()`:
#> ! an error occured in group 1 of `assays` context
#> Caused by error:
#> ! object 'rowData_seq' not found
```

but they can be requested via `rlang` pronouns `.rows`, `.cols`

``` r
.x <- mutate(
  out,
  row_seq = .rows$rowData_seq,
  col_seq = .cols$colData_seq
) 
pull(.x, row_seq)
#>       col_1 col_2 col_3 col_4
#> row_1     1     1     1     1
#> row_2     2     2     2     2
#> row_3     3     3     3     3
#> row_4     4     4     4     4
#> row_5     5     5     5     5
pull(.x, col_seq)
#>       col_1 col_2 col_3 col_4
#> row_1     1     2     3     4
#> row_2     1     2     3     4
#> row_3     1     2     3     4
#> row_4     1     2     3     4
#> row_5     1     2     3     4
```

The assay context is probably the most like a longform data frame, however if pulling data into the rows context or columns context, the user needs to be careful. 

Data outside the rows context is returned as a list of an appropriate size for the context

``` r
.x <- mutate(
  out,
  rows(
    assay_seq = .assays$assay_seq,
    col_seq = .cols$colData_seq
    )
) 
pull(.x, rows(assay_seq)) # the assay named "assay_seq" sliced by rows
#> [[1]]
#> col_1 col_2 col_3 col_4 
#>     1     6    11    16 
#> 
#> [[2]]
#> col_1 col_2 col_3 col_4 
#>     2     7    12    17 
#> 
#> [[3]]
#> col_1 col_2 col_3 col_4 
#>     3     8    13    18 
#> 
#> [[4]]
#> col_1 col_2 col_3 col_4 
#>     4     9    14    19 
#> 
#> [[5]]
#> col_1 col_2 col_3 col_4 
#>     5    10    15    20
pull(.x, rows(col_seq)) # the entirety of colData "col_seq" replicated to len 5
#> [[1]]
#> [1] 1 2 3 4
#> 
#> [[2]]
#> [1] 1 2 3 4
#> 
#> [[3]]
#> [1] 1 2 3 4
#> 
#> [[4]]
#> [1] 1 2 3 4
#> 
#> [[5]]
#> [1] 1 2 3 4
```

In the above may be helpful to thinking about your data as if it were nested by the rows.

If the above behavior is undesirable, we have alternative pronouns suffixed by `_asis`, allowing users to get the actual data

``` r
mutate(
  out,
  rows(
    matrix_mult = as.vector(.assays_asis$assay_seq %*% .cols_asis$colData_seq)
  )
) |>
  pull(rows(matrix_mult))
#> [1] 110 120 130 140 150
```

For the sake of brevity, I will omit examples in the colData context.

I hope the above helps show some of the functionality of the package. FWIW, thank you for taking the time to review the package. Hopefully it isn't too painful 😅 

Best,
Justin

<sup>Created on 2024-10-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by hpages** [comment]
Interesting and educative, thanks.

I still view a PlySummarizedExperiment object as a data-frame-like object, that is, as an object that has a different shape than the original SE object. There would be some benefits in formalizing this e.g. I could just do `colnames()` to extract all the colnames of the "tibble abstraction". Right now, I'm not really sure how to do that without explicitly turning the object into a data.frame or tibble (with `as.data.frame()` or `as_tibble()`) first, and then calling `colnames()` on that. Not ideal because this is obviously going to be very inefficient on a big object.  But I won't insist any further on that.

Also I'm not denying the fact that, for a proficient use of **plyxp**, the user definitely needs to be familiar with, and think about, the SummarizedExperiment structure. But one doesn't exclude the other, and having 2 classes for representing the same object allows to easily switch from one shape to the other.

Note that you don't need to create the class union SE_OR_RangedSE because a RangedSummarizedExperiment `is()` a SummarizedExperiment. So there's no difference between being a SummarizedExperiment and being an SE_OR_RangedSE from an `is()` point of view, that is, doing `is(x, "SE_OR_RangedSE")` and `is(x, "SummarizedExperiment")` will always produce the same result. For example, both return `TRUE` on a SingleCellExperiment object.

This is analog to what happens with sets in mathematics where the union of a set A with a subset of A is A.

In short: you don't need the SE_OR_RangedSE class and you can simply define the PlySummarizedExperiment class with:
```
setClass("PlySummarizedExperiment", slots = c(se = "SummarizedExperiment"))
```
This will be semantically equivalent to the current definition where slot `se` is required to be an SE_OR_RangedSE.

We should be able to access the man pages of the methods defined in your package with just `?mutate` or `?select` (in which case a pop-up window will ask the user to disambiguate), or with `?plyxp::mutate` or `?plyxp::select`. Right now doing so opens a very generic, and not so informative man page that lists all the verbs that are reexported from other packages. But it doesn't document the methods that you implemented for these verbs. So one could come to the conclusion that your methods are not documented when they are in fact documented, and can be accessed with `?mutate.PlySummarizedExperiment` or `?select.PlySummarizedExperiment`. It took me a while to figure this out and I bet that most users will never be able to find those man pages. This is easy to fix: just add the `mutate` and `select` aliases etc... to the man pages where the methods are documented.

Also doing `?summarize` or `?summarize.PlySummarizedExperiment` doesn't access any **plyxp** man page so it seems that some aliases are missing for that too.

Thanks,
H.

**Comment by jtlandis** [comment]
Hello @hpages 

I was actually curious if the following was sufficient.

```r
setClass("PlySummarizedExperiment", slots = c(se = "SummarizedExperiment"))
```

In my testing, with the above definition, passing a `RangedSummarizedExperiment` into the constructor would coerce the object into a `SummarizedExperiment`. Am I missing something?

> We should be able to access the man pages of the methods defined in your package with just ?mutate or ?select 

I will work on getting the documentation to the correct method up in running.

**Comment by hpages** [comment]
Oops, yes. This is probably due to the default `initialize()` method being a little bit too zealous here.

You can work around this by defining the constructor function with:
```
PlySummarizedExperiment <- function(se) 
{
    ans <- new("PlySummarizedExperiment")
    ans@se <- se
    ans
}
```
This works as expected:
```
library(SummarizedExperiment)

example(RangedSummarizedExperiment)

class(rse)
# [1] "RangedSummarizedExperiment"
# attr(,"package")
# [1] "SummarizedExperiment"

setClass("PlySummarizedExperiment", slots = c(se = "SummarizedExperiment"))

PlySummarizedExperiment <- function(se) 
{
    ans <- new("PlySummarizedExperiment")
    ans@se <- se
    ans
}

plyrse <- PlySummarizedExperiment(rse)

class(plyrse@se)
# [1] "RangedSummarizedExperiment"
# attr(,"package")
# [1] "SummarizedExperiment"
```
Note that this is a perfectly valid PlySummarizedExperiment instance:
```
validObject(plyrse)
# [1] TRUE
```
Any object `se` that satisfies `is(se, "SummarizedExperiment")` is allowed to go in the `@se` slot. E.g. a SingleCellExperiment object will be ok. Again, this is the default `initialize()` method that is doing unwarranted things IMO.

H.

**Comment by hpages** [comment]
Thanks for the changes @jtlandis. Let me know when I can take a look again.

**Comment by jtlandis** [comment]
@hpages, it should be ready for you to look again. the following changes were made:

* Fixed documentation of `?plyxp::mutate` and other dplyr functions reexported
  by `plyxp`.
* `PlySummarizedExperiment` should be able to hold any `SummarizedExperiment` 
  object

**Comment by hpages** [comment]
All looks good, thanks!

**Comment by mikelove** [comment]
Thank you @hpages for your time reviewing this package!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jtlandis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("plyxp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/plyxp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
