### ISSUE TITLE
zinbwave

### ISSUE THREAD

**Issue by drisso** [Bioconductor/Contributions#364]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/drisso/zinbwave

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by drisso** [comment]
Hi @hpages !

I've recently made a few minor changes to the package (most notably adding the possibility to specify the covariates with a formula rather than with a matrix).

These changes currently leave in a separate branch on GitHub (https://github.com/drisso/zinbwave/tree/summarizedexp), but if you haven't started your review yet, I would like to merge them into master so that you review the latest version. If you already started reviewing the package I can wait to merge this feature after your initial review.

Please, let me know what you prefer!

**Comment by mtmorgan** [comment]
Thanks for the great looking package. When the following are
addressed, please post a comment to this issue summarizing your
response.

DESCRIPTION

- Title: / Description: please make the description more like a paper
  abstract to help the user know that this package is appropriate for
  them. Perhaps indicate how your package differs from other similar
  packages.
- Depends: / Imports: good. Interoperable with other Bioconductor
  packages.
- Consider using BiocParallel instead of parallel, so that windows
  users also benefit from parallel evaluation.
- biocViews: good
- License: good
- Author: and Maintainer: fields are redundant when Authors@R is
  present (the fields are generated when the package is built). Please
  remove Author: and Maintainer:.
  
NAMESPACE

- good

vignettes

- Excellent!

R

- Use your existing accessors `getEpsilon_gamma_mu()` rather than
  direct slot access, e.g., in validity methods.
- Use of `initialize()` can be problematic, because it has a complex
  contract of both constructor and copy-constructor. Consider instead
  placing the initialization code in the user-facing constructor
  `zinbModel()`.
- helper-methods.R: Creating an object with `object@X <- ...`
  `object@Y <- ...` _copies_ `object` on each assignment. Consider
  instead creating appropriate values, e.g., `if (missing(Y)) Y <-
  NULL` and then a single call to `new(..., Y=Y)`.
- helper-methods.R:627 can the call to `rnbinom()` (and elsewhere) be
  _vectorized_ as

    ```
    i <- seq(n*J)
    rnbionm(length(i), mu = mu[i], size = theta[ceiling(i / n)])
    ```
- solveRidgeRegression.R:31 Consider 'hoisting' the constant
  conditional outside the function definition (similarly for `g()`).
  
    ```
    f <- if (family == "gaussian") {
             function(b) {
                 eta <- x %*% b + offset
                 l <- sum((y-eta)^2)/2
                 l + sum(epsilon*b^2)/2
             }
         } else if (family == "binomial") {
             function(b) {
                 eta <- x %*% b + offset
                 l <- sum(-y*eta + copula::log1pexp(eta))
                 l + sum(epsilon*b^2)/2
             }
         }
    ```
- zinb_fit.R:65 (and elsewhere) use `message()` instead of `cat()` for
  informative messages during evaluation.
- zinb_fit.R:121 (and elsewhere) no need to `stop(paste0("foo",
  "bar"))`, just `stop("foo", "bar')`.
- zinb_fit.R:302 Use `seq_len(iter)` or `seq_along(x)` instead of
  `1:iter` to avoid surpises when `iter == 0`.
- zinb_fit.R:302 This `for()` loop introduces nested iterations that
  necessarily have quadratic evaluation time. Is there a way to reduce
  the amount of computation involved, e.g., hoisting common
  calculations outside the loop or performing vectorized instead of
  iterative computation?
  
man

- good; some parameter descriptions are too brief for a user to
  realistically understand what values are appropriate.
  
tests

- OK.
- Would be appropriate to test numerical correctness, e.g., in
  test_design.R:28
  
other

- Is the NEWS file formatted so that it can be parsed by, e.g.,
  `news()`?

**Comment by drisso** [comment]
Thank you @mtmorgan for the very helpful review!

I will address the issues and report back!

**Comment by drisso** [comment]
Hi @mtmorgan 

I've started addressing your comments and I'm at a point where I thought it would be useful to commit to master and bumped the version to see if I can still pass all the Bioc checks on your system.
However, I'm not done with the required changes, I still want to switch from parallel to BiocParallel and try and see if there are some strategies to avoid nested loops in the big loop in zinbFit. 

I will let you know when I'm done with the revision so that you can review the changes.

Thanks!

**Comment by mtmorgan** [comment]
yes, just provide a comment indicating that you're ready to go and summarizing the response to reviewer comment.s

**Comment by drisso** [comment]
Hi @mtmorgan 

I believe that the package is now ready for you to re-review. For some reason, though, the bot did not send a build report even though it said that it started a new build after receiving a valid push. Is there a way to restart the build?

I've addressed most of your comments (see below). One interesting point is whether we could do a better job at vectorizing the calls to `optim()` to avoid some of the `*apply()` calls. For some reason (probably my limited programming skills!) I cannot find a way to write efficient vectorized code in this case. To give you a concrete example, I started working on what I thought was a more efficient version of solveRidgeRegression, in a separate branch. 

Original version (master): https://github.com/drisso/zinbwave/blob/master/R/solveRidgeRegression.R#L26
called, e.g., here:
https://github.com/drisso/zinbwave/blob/master/R/zinb_fit.R#L193

New version (summarizedexp branch):
https://github.com/drisso/zinbwave/blob/summarizedexp/R/solveRidgeRegression.R#L29
called, e.g., here:
https://github.com/drisso/zinbwave/blob/summarizedexp/R/zinb_fit.R#L196

I tested them, and these functions give the same numerical results, but I thought that the new version would be faster. However, it turns out that the original version is faster. Am I missing something?

Because of this, I didn't integrate these changes to master, and I haven't even attempted (yet) at vectorizing the analogous functions in zinbOptimize (which would require substantial changes to the log-likelihood functions. 

I hope that the package will be acceptable for Bioconductor without these changes, and I hope that I will find some help over the summer to vectorize this code in a sensible way (I think that in principle it should be doable).

I addressed the other comments as follows.

> Title: / Description: please make the description more like a paper
abstract to help the user know that this package is appropriate for
them. Perhaps indicate how your package differs from other similar
packages.

I've updated the description with a more detailed explanation of the model.

> Consider using BiocParallel instead of parallel, so that windows
users also benefit from parallel evaluation.

Done! 

> Author: and Maintainer: fields are redundant when Authors@R is
present (the fields are generated when the package is built). Please
remove Author: and Maintainer:.

Done!

> Use your existing accessors getEpsilon_gamma_mu() rather than
direct slot access, e.g., in validity methods.

Done!

> Use of initialize() can be problematic, because it has a complex
contract of both constructor and copy-constructor. Consider instead
placing the initialization code in the user-facing constructor
zinbModel().

Done. The initialization code is now in the zinbModel() constructor.

> helper-methods.R: Creating an object with object@X <- ...
object@Y <- ... copies object on each assignment. Consider
instead creating appropriate values, e.g., if (missing(Y)) Y <- NULL and then a single call to new(..., Y=Y).

I've made extensive changes to both zinbFit() and helper methods, so that I only make a single call to zinbModel() instead of constantly copying the object with object@Y <- ....

> helper-methods.R:627

These calls are now vectorized.

> solveRidgeRegression.R:31 Consider 'hoisting' the constant
conditional outside the function definition (similarly for g()).

Done.

> zinb_fit.R:65 (and elsewhere) use message() instead of cat() for
informative messages during evaluation.

Done.

> zinb_fit.R:121 (and elsewhere) no need to stop(paste0("foo", "bar")), just stop("foo", "bar').

Changed all these instances.

> zinb_fit.R:302 Use seq_len(iter) or seq_along(x) instead of
1:iter to avoid surpises when iter == 0.

Done.

> zinb_fit.R:302 This for() loop introduces nested iterations that
necessarily have quadratic evaluation time. Is there a way to reduce
the amount of computation involved, e.g., hoisting common
calculations outside the loop or performing vectorized instead of
iterative computation?

See above.

> tests

I included tests for numerical correctness in some special cases.

> Is the NEWS file formatted so that it can be parsed by, e.g.,
news()?

Yes, `news(package = "zinbwave")` gives a nicely formatted view.

**Comment by mtmorgan** [comment]
Thanks for the changes, I was hoping to get some time to help with the performance issue but I seem not to have been able to get to that.

**Comment by drisso** [comment]
Thank you @mtmorgan !

I'll be happy to incorporate any suggestions in future versions if you ever find the time to look into it!
