### ISSUE TITLE
Onassis package

### ISSUE THREAD

**Issue by eugeniaeueu** [Bioconductor/Contributions#365]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/eugeniaeueu/Onassis

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Hello, Thank you for your submission.  Since you have submitted your package for review, we have implemented our MAC builder;  I am going to manually kick off a new build to have that information in the report as well.  I will review the package and leave feedback in the next few days.

**Comment by lshep** [comment]
Can you please investigate this ERROR? I am unable to build or install a local version of your package as well.

**Comment by eugeniaeueu** [comment]
Hi, I'm trying to solve the issues. The former ones were only on windows platforms and they were arising from the java libraries I am importing from sourceforge. I am compiling them again on Windows and checking if they still work in os and linux.

**Comment by lshep** [comment]
Is there a reason you aren't bundling the java libraries with the package?

**Comment by eugeniaeueu** [comment]
I want to add the java libraries in the extdata of the package. Since they are large 85 mb I thought to put them already compiled on sourceforge and download them when the package is installed as extdata. The solution worked on my Os X but doesn't work in windows. I temporally changed the code to show the java classpath during the BUILD. I'm going to trigger a new build. Have you got any hint ? Thanks

**Comment by eugeniaeueu** [comment]
Hi, this is the report from the latest commit 

http://bioconductor.org/spb_reports/Onassis_buildreport_20170518065752.html and the problem is again with windows. I tried to add the jar file to the java classpath in a R console with the following commands having the jar in the current working directory
library(rJava)
.jinit()
.jaddClassPath("C:/Users/defaultUser/Downloads/similarity-0.0.1-SNAPSHOT-jar-with-dependencies.jar")
.jnew("iit.comp.epigen.nlp.similarity.Similarity")

In this case the class is created, but I really don't understand what goes wrong with the initJavaLibs method in Onassis

**Comment by mtmorgan** [comment]
Hi @eugeniaeueu -- I've taken over the review from Lori, to help navigate this issue.

I think first we're reluctant to rely on large jar downloads from 'third party' sites. There are several issues. 

1. Bioconductor is supposed to be 'open source', but since only the jar files are available it's not straight-forward for users to discover the underlying code.
2. Redistributing software generally requires conformance to the license of the underlying software, but there is no license on the jar files.
3. using a third-party resource (in this case sourceforge) is not ideal, partly because Bioconductor tries to provide users with a reproducible environment ('normal' Bioconductor packages are available in our SVN repository 'forever') but we cannot guarantee the long-term availability of the sourceforge resource.
4. A second concern with third-party resources is the cost to our build system of downloading the resource on a nightly basis -- packages are built 'fresh' each night, so the build system would pay this price each night.

To work through these, I think

1. The java source code needs to be available, preferably in a versioned (e.g., github) repository.
2. The license for the java code needs to be clearly determined, and of course your redistribution allowed by the license and appropriately acknowledged in the package.
3. Ideally, the java source code and / or jar files would be incorporated into your package or an 'experiment data' package. Likely the  java files contain a great deal of infrastructure that is not relevant to their use in R, and they would be trimmed as appropriate.
4. After these hurdles are addressed, we might focus on the specifics of how the jar files are managed; [BiocFileCache][] would be  a better solution (using a directory in the installed package directory does not work, because packages are often installed under an 'administrator' account and the installed package directory  is not writable by end users).

Let me know what your thoughts are.

**Comment by eugeniaeueu** [comment]
Dear Martin, thank you for your kind help, 
For 1 and 2 
Regarding the Java source code, I simply compiled with maven a jar including dependencies from the already available repository at https://github.com/UCDenver-ccp/ccp-nlp. This is their license https://github.com/UCDenver-ccp/ccp-nlp/blob/master/LICENSE
For the semantic similarity part I modified some source code files, created a new class and compiled the other jar with dependencies from this other repository https://github.com/sharispe/slib. The license in this case is a CeciLL one. 
Should I fork both the repositories in my github, update the second one with my modifications, copy the license files and then add this information in the DESCRIPTION file of the Onassis repository? Should I also change the License field in the DESCRIPTION file of the Onassis package?

Concerning 3, I already tried to remove some of the infrastructure that is not relevant but the dependencies are so intricate that it's impossible to make the library work without any of the modules. Anyway, I'll give it a try again. I thought that it wasn't possible to create an experiment data for java and jar files, but I can create it and upload it in github.  
I'll also give a look at the BiocFileCache. 
I look forword to hear from you soon. Thanks again,

Eugenia

**Comment by mtmorgan** [comment]
Thanks for the submission. Sorry for the slow reply. I won't make any
comments on OnassisJavaLibs; t seems fine as it is. When the issues
below are addressed, please post a brief summary of the changes you
have made.

DESCRIPTION

- Good

vignette

- Good

R

- Validity methods should return text describing errors, rather than
  stopping. So for instance

    ``` 
    setClass(
        Class = "CMoptions", 
        representation(arguments = "list"),
        validity = function(object) {
            text <- character()
            ...
            if (class(object@arguments) != "list") {
                text <- c(text, "Invalid arguments: Arguments should be a list")
            ...
            if (length(text)) text else TRUE
        }
    )
    ```

- Consider constructors `CMdictionary <- ...` instead of direct calls
  to `new()` to separate 'interface' from 'implementation', a major
  benefit of object-oriented approaches.
- Likewise, _always_ define and use accessor function e.g.,
  `dict_location <- function(x) x@dict_location`. The accessor
  functions do not need to be exported if the slot is not meant to be
  accessed by the user.
- use `inherits()` (S3) or `is()` (S4) rather than `class()`.
- Consider formatting code to standard 80 character width, e.g,. using
  package formatR.
- for generics with multiple arguments, consider using `signature=` to
  limit dispatch to the arguments for which dispatch is actually
  required. This simplifies reasoning about code -- only one
  alternative path, rather than multiple, required.
- Consider using `loadNamespace()` rather than `library()`
  (CMdict-methods.R:153)
- `eval(parse(text=...))` CMdict-methods.R:155 can usually be avoided;
  I think you want `org <- loadNamespace(inputFileOrDb); org[[inputFileOrDb]]`
- `message()` doesn't need `paste0()` inside -- it pastes args.

man

- good

NEWS

- format so parsed by `utils::news()`

**Comment by mtmorgan** [comment]
have you finished revisions in response to the initial review?

**Comment by eugeniaeueu** [comment]
Yea, I made all the corrections
