### ISSUE TITLE
miRBaseConverter

### ISSUE THREAD

**Issue by xtsvm** [Bioconductor/Contributions#367]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xtsvm/miRBaseConverter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
The data set miRNATest seems to be derived from [TarBase][], but bulk
downloading the data takes the user to a web page where they are
required to register. Further, the license restricts use to
non-commericial use or with consent. This licensing does not seem to
be consistent with data redistributiion in this package, with the
license used for the package, or with _Bioconductor_ policy for
licenses that do not restrict access to academic-only
institutions. The package therefore cannot be accepted as is.

One possibility is to provide the user with instructions for
downloading the data to their own computer, independently of your
package. A good approach might use [BiocFileCache][] to manage the
downloaded data for the user. Your package would still require some
'mock' data to illustrate functionality and test implementation.

DESCRIPTION, NAMESPACE

- good.

vignettes

- The vignette is very terse and barely acceptable. A more complete
  vignette would perhaps identify or create an appropriate experiment
  data package containing, e.g., a [SummarizedExperiment][], and
  illustrate how the rows can be annotated appropriately.
- Since users have access to the tangles / purled source of your
  vignette, it is inappropriate to perform actions such as
  `rm(list=ls())` that would alter (catastrophically) their global
  environment.
- consider adopting standard R code formatting, in particular
  introducing spacing around `=` and after `,` or `##`. Consider
  introducing blank lines before code comments `##` or separate the
  single code chunk into separate code chunks. Represent the text that
  is currently a comment within a code chunk as plain text between
  chunks
- Avoid abusing HTML headers for what amounts to body content, e.g., 

    ```
    ####(1) We provide a function for miRBase name conversion in different versions. This function can detect all the match miRNA name with the same Accession ID in history versions. So it may not totally exact matched.
    ```
    
  could be

    ```
    1. miRBase name conversion.  This function can detect all the match
       miRNA name with the same Accession ID in history versions. So it
       may not totally exact matched.
    ```
    
  To associated code chunks with enumerated points, indent the code
  chunk by four spaces.
- In addition to providing the commands required to achieve the
  solution, descrie in words what the outcome is.

R

- The _R_ code uses iteration (`for` loops) when vectorization is
  appropriate and easily implemented. For instance, the first few
  lines of this iteration in miRBaseConvert.R
  
      ```
      for(i in 1:length(sYM_ID))
      {
        if(!is.na(sYM_ID[i]))
        {
          ind1=which(sYM_ID[i]==ACC_SYM[,2])
          ACC_ID=ACC_SYM[ind1,1]
          ind3=match(ACC_ID,miRNA_data[[ver_index]]$ACC)
          ACC_ID=ACC_ID[!is.na(ind3)]
          ind3=ind3[!is.na(ind3)]
          ...
      ```
      
  are more simply and efficiently expressed as a vectorized
  calculation that does not require the `for` loop.
  
      ```
      ind1 <- match(sYM_ID, ACC_SYM[,2])
      ACC_ID <- ACC_SYM[ind1, 1]
      ind3 <- match(ACC_ID, miRNA_data[[ver_index]]$ACC)
      ACC_ID <_ ACC_ID[!is.na(ind3)]
      ind3 <- ind3[!is.na(ind3)]
      ```
  
  It seems likely that the entire function, AND ALL CODE IN THE
  PACKAGE, can be vectorized in this way.

- Use `message()` rather than `cat()` to communicate messages to the
  user, e.g,. about multiple matched miRNAs.
- Use a consistent naming scheme, e.g, camelCase, rather than
  camelCase and mixed camel- and snake case snake_CameCase.

man

- The documentation for miRNATest data is inadequate. The column names
  listed in the Description are not the names of the columns in the
  data. Provide an explicit URL that represents the source of the
  data. Describe in a fully reproducible way (ideally, with an _R_
  script in `inst/scripts`) how the data are retrieved and
  processed. It is unclear why version 6.0 is provided, when version
  7.0 is available.
- in miRBaseConverter.Rd, use `\describe` (section 2.4 of Writing R
  Extensions) rather than _ad hoc_ formatting \strong{} of column
  names. Refer to columns by name rather than "Column 1", etc.


[TarBase]: http://diana.imis.athena-innovation.gr/DianaTools/index.php?r=tarbase/index. 
[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment
[BiocFileCache]: https://bioconductor.org/packages/BiocFileCache

**Comment by xtsvm** [comment]
Dear mtmorgan,
Thank you very much for you detailed and constructive comments about the miRBaseConverter package.
I have modified the most parts you pointed out. But I want to make a detailed explanation for two related issues.
1. The miRBaseConverter package embedded a test dataset ( called miRNATest ). In last version, I extracted all the miRNA names from the Tarbase 6.0 database table. I supposedly thought that wouldn’t violate the license restrict. Because the Tarbase is a miRNA- mRNA interactions databases, while I just extracted the miRNA names for package functions’ test. I don’t use the Tarbase database for any annotations in miRBaseConverter package.
Based on the comment about the test data set, I give a dummy miRNA name collection for package functions’ test in new version. It will avoid any license restrict. Thank you.
2. Thank you for your advice about the R code could be implemented in more efficient way using the vectorization method. But the vectorization approach can’t get the exact mapped result.
In the example you presented, the reason of the “for loops” is that the base::match() function just returns a vector of the positions of (first) matches. The vectorization method of using match() can’t  get all the matched elements in a vector elements. So, I keep the code as the original in this part. Thank you for your comment that leads to this discussion. 
Thank you again for your comments as they have helped improve the quality of this package.

Best regards,
Taosheng

**Comment by mtmorgan** [comment]
For your response 2, what is a simple example that illustrates when vectorization fails? E.g., does the first example on the help page illustrate the problem with vectorization?

```
data(miRNATest)
miRNANames=miRNATest$miRNA_Name
result1=miRNAVersionConvert(miRNANames,targetVersion="v13",exact=TRUE)
```
?

**Comment by xtsvm** [comment]
Dear @mtmorgan,
Thank you for your review.
I try to explain the question in this way.
The base::match() function can’t retrieve all the matched elements in a vector. It only returns the first matched element.  For example,
>Test=c("aa","bb","cc","bb","dd")
>match("bb",Test)
## Only the first “bb” can be detect.
> 2
The miRNA names had changed a lot in different versions. In some special cases, a miRNA name has the corresponding Accession ID in one version, but the same miRNA name could map to another Accession ID. If we use base::match() for these miRNA names, it would miss the multiple match information. I give another example.
## I pick out some human miRNAs which  have multiple Accession IDs in different versions.
>miRNANames = c( "hsa-let-7c","hsa-miR-3190-3p","hsa-miR-34b","hsa-miR-378","hsa-miR-499a-3p" , "hsa-miR-499a-5p","hsa-miR-500","hsa-miR-516a-5p","hsa-miR-550","hsa-miR-589" )
>result1=miRNAVersionConvert(miRNANames , targetVersion="v21", exact=TRUE)
##********************************************
##The multiple matched miRNAs are list below: 
##      original                     Version v21                                      accession
##1 hsa-miR-34b     hsa-miR-34b-5p&hsa-miR-34b-3p        MIMAT0000685&MIMAT0004676
##2 hsa-miR-378     hsa-miR-378a-5p&hsa-miR-378a-3p    MIMAT0000731&MIMAT0000732
##3 hsa-miR-500     hsa-miR-500a-3p&hsa-miR-500a-5p    MIMAT0002871&MIMAT0004773
##4 hsa-miR-550     hsa-miR-550a-3p&hsa-miR-550a-5p    MIMAT0003257&MIMAT0004800
##5 hsa-miR-589     hsa-miR-589-3p&hsa-miR-589-5p        MIMAT0003256&MIMAT0004799

The multiple match is just some special cases. I am sorry I can’t take your specified code for illustration.

Best regards,
Taosheng

**Comment by mtmorgan** [comment]
Thank you for the example. When I look at your code more carefully it seems that you are merging between data.frames. Use `merge()` for a more efficient approach, instead of iteration. Here is a version of the function:

```
miRNAVersionConvert <-
    function(miRNANames,targetVersion="v21",exact=TRUE)
{
  ver_index=match(tolower(targetVersion),VER[,2])
  if (is.na(ver_index))
      stop("It is a wrong target version, Please check it")
  VMAP <- miRNA_data[[ver_index]][, c("ACC", "SYM")]

  uid = unique(as.vector(miRNANames))
  SYM_ID = match(uid, SYM$SYM)

  df <- data.frame(uid = uid, SYM = SYM_ID, stringsAsFactors=FALSE)
  df <- merge(df, ACC_SYM)[, c("uid", "ACC")]
  df <- unique( merge(df, VMAP, by="ACC") )
  target <- data.frame(
      OriginalName = df$uid,
      VersionName = SYM$SYM[df$SYM],
      AccessionID = ACC$ACC[df$ACC],
      stringsAsFactors = FALSE
  )

  if (exact) {
      idx <- target$OriginalName == target$VersionName |
          !target$OriginalName %in% target$VersionName
      target <- target[idx, , drop=FALSE]
  }

  ## collapse 1:many maps
  splitpaste <- function(x, f) {
      result <- vapply(split(x, f), paste, character(1), collapse="&")
      result[!nzchar(result)] <- NA
      result
  }
  f <- factor(target$OriginalName, levels=uid)
  target <- data.frame(
      OriginalName = uid,
      VersionName = splitpaste(target$VersionName, f),
      AccessionID = splitpaste(target$AccessionID, f),
      row.names=NULL, stringsAsFactors = FALSE
  )
  names(target)[2] <- paste("Version", targetVersion)
  
  ## FIXME: verbose
  target[match(miRNANames, target$OriginalName),]
}
```

Here is some test code

```
miRNANames <- miRNATest$miRNA_Name

result0 <- miRBaseConverter::miRNAVersionConvert(
    miRNANames , targetVersion="v21", exact=TRUE
)
result0 <- as.data.frame(result0, stringsAsFactors=FALSE)
names(result0)[1] <- "OriginalName"

VER <- miRBaseConverter:::VER
SYM <- miRBaseConverter:::SYM
ACC <- miRBaseConverter:::ACC
ACC_SYM <- miRBaseConverter:::ACC_SYM
miRNA_data <- miRBaseConverter:::miRNA_data
result1 <- miRNAVersionConvert(miRNANames , targetVersion="v21", exact=TRUE)

f0 <- function()
    miRBaseConverter::miRNAVersionConvert(
        miRNANames , targetVersion="v21", exact=TRUE
    )

f1 <- function()
    miRNAVersionConvert(miRNANames , targetVersion="v21", exact=TRUE)
```

The results are identical but 10x faster

```
> identical(result0, result1)
[1] TRUE
> microbenchmark(f0(), f1(), times=10)
Unit: milliseconds
 expr       min        lq     mean    median        uq      max neval
 f0() 445.69359 452.13460 456.5644 453.23402 461.08631 475.8817    10
 f1()  28.09709  28.27334  30.1711  29.16023  29.44923  35.9054    10
```

Note that 1. the return value should be a data.frame; 2. the return value column name had spelling mistake.

Please also carefully look at ALL of your code -- I think each iteration can be replaced by much more efficient operations.

**Comment by xtsvm** [comment]
Dear @mtmorgan,
Thank you very much for your great contribution for this package. It indeed greatly improves the efficiency of the retrieval.
I have followed your style to rewrite the most functions in this package. There are some detail information in below.
1.	The functions miRNAVersionConvert(), miRNA_AccessionToName(), miRNA_NameToAccession(), getMiRNASequence() have been rewritten based on merge().
2.	The functions getMiRNAHistory(), checkMiRNAVersion() are still the original version based on the for loops. Because they need to check all the different versions in a list with different data frames.
3.	I add a new function goToMiRBase() to open the miRbase webpage for a specific miRNA in this version. 
Best regards,
Taosheng

**Comment by xtsvm** [comment]
Dear @mtmorgan,
Base on the build report  in the above , why  the  Ubuntu and OS  X 10 system could not find the R base function shell.exec()? I can pass the BiocCheck in local.
Is it a problem with the build system itself?
Thank you!
Best regards,
Taosheng

**Comment by mtmorgan** [comment]
shell.exec is a windows-only function. I think you want instead `browseURL()`.

**Comment by xtsvm** [comment]
Thanks @mtmorgan,
The error has been fixed.

Best regards,
Taosheng

**Comment by llrs** [comment]
Hi @xtsvm ,
I was reading the discussion and found the `match` "problem" that only retrieves the first match, using `which` might be the solution to vectorize the code:

```r
Test <- c("aa","bb","cc","bb","dd")
match("bb", Test)
## 2
which(Test == "bb")
## 2 4
```
Hope this helps

**Comment by xtsvm** [comment]
Thanks @llrs ,
Thank you very much for your demonstration.
Yes, which() can get all the exact indexes of one single element in a vector.  The code is just a simple example to explain why match() can't work.
Here we want to get multiple matched elements  in a vectorization way.  As mtmorgan's illustration,  the merge() function is the perfect choice for this specified situation.  Thanks again.

Best regards,
Taosheng

**Comment by xtsvm** [comment]
Dear @mtmorgan,
There are two weeks with no updated comments for the miRBaseConverter package. I am afraid you miss my comment for the updated version. I attach the comment here. Thank you for your review! 

Dear @mtmorgan,
Thank you very much for your great contribution for this package. It indeed greatly improves the efficiency of the retrieval.
I have followed your style to rewrite the most functions in this package. There are some detail information in below.

The functions miRNAVersionConvert(), miRNA_AccessionToName(), miRNA_NameToAccession(), getMiRNASequence() have been rewritten based on merge().
The functions getMiRNAHistory(), checkMiRNAVersion() are still the original version based on the for loops. Because they need to check all the different versions in a list with different data frames.
I add a new function goToMiRBase() to open the miRbase webpage for a specific miRNA in this version.

Best regards,
Taosheng

**Comment by mtmorgan** [comment]
Thanks, I did see and review your changes, but forgot to accept the package!

**Comment by xtsvm** [comment]
Thanks  @mtmorgan,
I am proud my new package can be accepted in Bioconductor. Thank you very much for your contribution to greatly improve this package.

Best regards,
Taosheng
