### ISSUE TITLE
scoreInvHap

### ISSUE THREAD

**Issue by yocra3** [Bioconductor/Contributions#371]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isglobal-brge/scoreInvHap/ 

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
The names `snpfier` and `classifierPipeline()` seem too general... why not be more explicit about the purpose of finding inversions?

**Comment by yocra3** [comment]
We agree that the names were very vague. We have been talking about it and we think that _scoreInvHap_ could be a good name for both, the function and the package. Should I open a new issue or can I simply change the package name in the repository?

**Comment by lawremi** [comment]
That sounds better. @LiNk-NY might know how best to change the name.

**Comment by yocra3** [comment]
Hi, 

We have included some extra functions to perform QC on the results. The vignette has been updated to include these functions. We are waiting for your reply regarding the change of the package name.

**Comment by yocra3** [comment]
Hi, 

Yesterday I got an error in the Windows' build because the package Biobase was not available. Should I bump the version number to get another build?

**Comment by nturaga** [comment]
Hi @yocra3 ,

Please ignore that error. You can expect a review by Friday May 26th.

**Comment by nturaga** [comment]
snpfier Review
==================

## Build

R-release CMD build snpfier: Ok

R-release CMD INSTALL snpfier: Ok

## DESCRIPTION

*  Good Description.

## NAMESPACE

* ok

## Vignette

* Informative vignette. Good Introduction, listing out other packages which perform the task and listing out pros and cons is good practice. :) 

## man

* (E.g., classifierPipeline.R) Pay attention to formatting of @example code; it wraps poorly and without indentation (view in plain console for illustration).

## R

* It's really confusing to call the package 'snpfier' but to document the package with 'SNPfier', and in general changing case on SNP causes confusion. Maybe it would be better to be consistent?

* Consider documenting functions not exported from the package, eg: 'computeScore' in classifSNPs.R. Makes it easier to maintain in the long run. Mark the documentation pages with `@description Internal` or similar.

* Use a consitent style for R code, 4 spaces indentation.

* Use BiocParallel rather than parallel, so that all users (including those on Windows, about 1/2 of the Bioconductor community) can benefit from parallel evaluation.

* The use of mclapply at classifSNPs.R:46 seems unnecessary -- can `computeScore()` (and also `classifSNPsImputation()`) be written in a more efficient, vectorized way? There are additional simplifications, for instance, moving the `tryCatch()` from in the `vapply()` in classifSNPs.R to validation outside the loop.

**Comment by lawremi** [comment]
I still recommend improving the name of the package...

**Comment by nturaga** [comment]
@lawremi I agree as well. 

@yocra3  You can change the git repo's name, and edit the name of the issue you opened for BiocContributions. We'll fix it from there onwards.

**Comment by yocra3** [comment]
Hi, 

I have updated the name of the repository, the issue and the package.

I have also made some changes to the package to address the issues mentioned in your previous comment. There is only one thing I haven't been able to solve: simplifying the classifSNPs. I changed the code in computeScores to run it in a vectorized way. However, I don't see how can I improve the implementation to avoid the lapply.

**Comment by nturaga** [comment]
I will review your latest version and get back to you.

**Comment by yocra3** [comment]
I just modified the scripts included in inst folder to generate the objects required by scoreInvHap. As it won't affect package functionality, I won't bump the version.

**Comment by nturaga** [comment]
Bump the version.
