### ISSUE TITLE
(inactive) gene simulation

### ISSUE THREAD

**Issue by shaileshtripathi** [Bioconductor/Contributions#373]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shaileshtripathi/sgnesimR
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
This is the same package that was declined 7 days ago. It is declined again. The vignette remains inadequate. There is no effort to integrate with other Bioconductor packages. This decision is final.

**Comment by shaileshtripathi** [comment]
Hi Martin,

I could not understand the meaning of this 'There is no effort to integrate
with other Bioconductor packages'. I submitted two packages before to
bioconductor but never had this problem can you please describe me what is
the problem regarding integration. I couldn't find any answer of this on
bioconductor page for package submission. Also, my package is running fine
with BiocCheck command on my system.

Best
Shailesh

**Comment by mtmorgan** [comment]
A key strength of Bioconductor is the ability to easily use different packages for comparison, or for integration across a work flow. This is facilitated by re-use of Bioconductor containers such as SummarizedExperiment, GRanges, etc. for general purpose functionality, or by re-use of more domain-specific data structures from related packages. Robust code (and also ease-of-use) is also  facilitated by re-use rather than re-implementation of common functionality, such as the S4Vectors data representations.

Your package does not Depend: or Import: any Bioconductor package, and the Suggests: field was only modified to include BiocStyle after your 'vignette' was included (BiocGenerics seems to be in Suggests: for no reason). Not even your own, related, package is mentioned. From this it seems that your package does not benefit from being in Bioconductor, and conversely that your users do not require the Bioconductor ecosystem. CRAN might be a suitable place for it.

I will also say that the initial submission, without a vignette, is like submitting a paper without a discussion section -- of course it is declined. Your revised submission includes a 'vignette', but it is obviously copied from elsewhere and the content is like a technical appendix rather than an exposition of how to use the package. The revision did not address other comments in the original decision. So again the package was declined. Your final submission made trivial changes to the DESCRIPTION file, and so again it was declined.

**Comment by shaileshtripathi** [comment]
Thanks Martin,

Now I understand real reasons behind the rejection, these were not
explained previously.
I will keep these things  in mind for next submissions.

Best,
Shailesh
