### ISSUE TITLE
VULCAN: VirtUaL ChIP-Seq data Analysis using Networks

### ISSUE THREAD

**Issue by federicogiorgi** [Bioconductor/Contributions#379]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/federicogiorgi/vulcan

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by federicogiorgi** [comment]
AdditionalPackage: https://github.com/federicogiorgi/vulcandata

**Comment by mtmorgan** [comment]
The vignette is not adequate; let me know (comment on this issue) when you have a vignette describing overall use of the package, including integration with other Bioconductor packages. Remember that Bioconductor vignettes include code chunks that actually exercise your code.

Also, the biocViews terms are confusing -- this looks like a 'software' package (i.e., substantial R code) but the views include 'Annotation' package terms (Homo_sapiens_Data); software packages should choose terms from the [software][] hierarchy.

[software]: http://bioconductor.org/packages/release/BiocViews.html#___Software

**Comment by federicogiorgi** [comment]
Dear Martin and Community. I've updated the biocViews and vignette for your inspection:
https://github.com/federicogiorgi/vulcan
https://github.com/federicogiorgi/vulcandata

**Comment by mtmorgan** [comment]
@lshep can you help with instructions for solving the build issue -- vulcandata data package as a dependency here; I can never keep straight what the Depends / Imports / Suggests relationship between data and software packages is supposed to be, and I don't know which package is supposed to be added to the tracker first. And in the current case I really don't know how to get the SPB back on track!

**Comment by lshep** [comment]
@mtmorgan The suggests and depends are correct.  The `vulcan` package suggests the `vulcandata` data package and the data package depends on the software package.  Its slightly tricky in this case as we need both packages to be installed to pass - now that `vulcan` has been installed @federicogiorgi  please make sure the [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is also set up on the `vulcandata` repository and do a version bump on `vulcandata`.  This should build and install `vulcandata`.  Once that package has a clean install, build, check ,  a version bump on the `vulcan` software package would then find `vulcandata` and be able to build

**Comment by federicogiorgi** [comment]
@ishep @mtmorgan I set up the webhooks and did a version bump. Thanks a lot for the help :-)

**Comment by lshep** [comment]
@federicogiorgi  Please set the webhook and Bump the version on vulcandata not vulcan

**Comment by federicogiorgi** [comment]
@ishep I did bump the version and set up the webhook on vulcandata, but somehow my push doesn't trigger a build of vulcandata

**Comment by federicogiorgi** [comment]
AdditionalPackage: https://github.com/federicogiorgi/vulcandata

**Comment by federicogiorgi** [comment]
@ishep it seems I had to rewrite the "AdditionalPackage" thing :-) it seems to be working now.

**Comment by lshep** [comment]
Thank you.  I will try and keep an eye on this too but if you find it is not building the package you version bumped please let me know.

**Comment by federicogiorgi** [comment]
For some reason, I've stopped receiving build reports since yesterday. Is there a problem?

**Comment by lshep** [comment]
we are looking into this and should have it fixed soon. sorry for the inconvenience.

**Comment by nturaga** [comment]
@federicogiorgi Please remove all the files which are not essential to the package by using a `.gitignore` file. Once that is done, please message when you are ready for a review.

**Comment by federicogiorgi** [comment]
I did add not essential files to the .gitignore list, and I am ready for a review :-)

**Comment by nturaga** [comment]
# vulcan Review

## Build

R-release CMD build vulcan:  Delete `Depends` section in vulcandata. It does NOT depend on vulcan.

R-release CMD INSTALL vulcan : ok.


## DESCRIPTION

* Not enough in the `Description` section, it needs to be similar to the abstract of at paper. Shortening the overview in the vignette would be a good way to go about this.

## NAMESPACE

* Recreate with roxygen2, and do not edit by hand.

## man

* Some more work could help, 

* For example, 'vulcan.Rd : Value', more detail in the return value and also the description needs to be informative about method being employed.

## vignette

* Vignette is very limited and needs to be more of a walkthrough explaining the data inputs and outputs. 

* Mainly the vulcan pipeline doesn't explain "Why" the pipeline works in those steps.

## R

* Use `formatR` to follow the same style. (https://cran.r-project.org/web/packages/formatR)

* In gsea.R: line 184, and 190.

   184, Avoid using 1:np use seq_len(np). See (https://www.bioconductor.org/developers/how-to/efficient-code/)

   190, consider the case when length of inSet is 0.

* Delete code which is commented out , gsea.R : line 269 - 274. And similar in vulcan.R and other R scripts.

* The code for each method (topvar, lowvar, strongest, etc) is repeated, and can be written as a function and reused here. Write a function which does that , and reuse for both rawcount matrix and rpkm matrix. 

```
     if(method=="topvar"){
         for(i in seq_along(genes)){
             gene<-genes[i]
             if(peakspergene[gene]>1){
                 subanno<-dfanno[dfanno$feature==gene,]
                 vars<-apply(subanno[,allsamples],1,var)
                 top<-which.max(vars)
                 rawcounts[gene,allsamples]<-as.numeric(subanno[top,allsamples])
             }
         }
     }
```

Rearrange the code so that the for loop is only over possible genes

```
    idx0 <- seq_along(genes)
    idx <- idx0[peakspergene[idx0] > 1]
    for (gene in genes[idx]) {
        ...
    }
```
        
The identification of `subanno` is quadratic -- a scan of dfanno$feature for each gene. Also, the entire data frame dfanno is subset, but only the column allsamples is needed. Instead, do this in linear time and for just the data that is required.

```
subanno <- split(dfanno$allsamples, dfanno$feature)[gene]
vars <- sapply(subanno, var)
```

This code is not quite right but hopefully gives the idea -- the explicit loop over genes does not seem necessary.


* l. 408 is 'copy-and-append', but should be 'pre-allocate and fill' or a simple lapply; see the 'robust code' link above.

* Remove .Rhistory from your package.

* Fix all the NOTES in the  R CMD Check part of the build report.

## vulcandata review

* The experiment data packages need to have a vignette as well. 

* The vignette could describe how the data is derived and where it comes from, and how it could be used.

**Comment by federicogiorgi** [comment]
Thank you! I will implement the changes as soon as possible.

**Comment by federicogiorgi** [comment]
@nturaga I implemented your suggestions, thank you for making them, they were bright and enlightening, especially those on optimizing the loops. However, I kept the pipelines for RPKMs and Raw Counts separated, as they may be different in the future due to the different nature of the input data. I will upload the updated package shortly.

**Comment by nturaga** [comment]
hi @federicogiorgi i'll take a look at the changes and reply soon.

**Comment by nturaga** [comment]
* Build/install ok.

* man pages not changed.

* l:159 in gsea.R, you do not need this line. You overwrite it in the very next line.

* Please fix these instances as well, from 1:ncol/length() to seq_len. Please fix all instances of this "1:". Account for 0.

	```
	~/D/b/v/R ❯❯❯ grep "1:length" *                                              master ◼
	generic.R:        for (i in 1:length(x)) {
	gsea.R:            null_inSet <- inSet[sample(1:length(inSet))]
	rea.R:    for (i in 1:length(wgroups)) {
	vulcan.R:    for (i in 1:length(listcounts)) {
	vulcan.R:    for (i in 1:length(listcounts)) {
	vulcan.R:    names(dfanno) <- 1:length(dfanno)
	vulcan.R:    names(dfanno) <- 1:length(dfanno)
	vulcan.R:    for (i in 1:length(samples)) {
	~/D/b/v/R ❯❯❯ grep "1:ncol" *                                                master ◼
	vulcan.R:    for (j in 1:ncol(rawcounts)) {
	vulcan.R:    for (j in 1:ncol(rpkms)) {
	```


* Fix NOTES:

    ```
	* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  	  and vignette source...
    * NOTE: Consider shorter lines; 84 lines (3%) are > 80 characters
      long.
    First 6 lines:
      R/generic.R:167 val2col <- function(z, col1 = "navy", col2 = "white", c...
      R/generic.R:319 textplot2 <- function(x, y, words, cex = 1, pch = 16, p...
      R/generic.R:339     text(lay[, 1] + 0.5 * lay[, 3], lay[, 2] + 0.5 * la...
      R/generic.R:370         legend("topright", paste0("fragment-length = ",...
      R/gsea.R:24 gsea <- function(reflist, set, method = c("permutation", "p...
      R/gsea.R:121             newp.value <- ppareto(abs(es), threshold = q95...
    * NOTE: Consider multiples of 4 spaces for line indents, 11
      lines(0%) are not.
    First 6 lines:
      R/gsea.R:287                   ytop = 10, col = colBarcode, border = NA)
      R/gsea.R:293                   srt = 90, offset = 0, pos = 4, font = 2)
      R/gsea.R:324                   3), sep = "")), bg = "white")
      R/rea.R:43              matrices of identical size")
      man/gsea.Rd:8   gsea_null = NULL)
      man/plot_gsea.Rd:8   colBarcode = "black", title = "Running Enrichment ...
    See http://bioconductor.org/developers/how-to/coding-style/
	```

* These sets of repeated code can be made a function, and reused.

	```
	     # Method closest: when multiple peaks are found, keep only the closest to the TSS
     # as the representative one
     if (method == "closest") {
         for (gene in genesmore) {
             subanno <- dfanno[dfanno$feature == gene, ]
             closest <- which.min(subanno$distanceToStart)
             rawcounts[gene, allsamples] <- as.numeric(subanno[closest, allsamples])
         }
     }

     # Method farthest: when multiple peaks are found, keep only the closest to the
     # TSS as the representative one
     if (method == "farthest") {
         for (gene in genesmore) {
             subanno <- dfanno[dfanno$feature == gene, ]
             farthest <- which.max(subanno$distanceToStart)
             rawcounts[gene, allsamples] <- as.numeric(subanno[farthest, allsamples])
         }
     }
	```

	for example:

	```
	dist_calc <- function(method, dfanno, rawcounts, genesmore) {
		my_func <- switch (method,
            farthest = which.max,
            closest = which.min,
            ## more types of methods
            ## custom_function = function(x) ...
            ## default:
            stop("unsupported method ", method)
         )
		for (gene in genesmore) {
		  subanno <- dfanno[dfanno$feature == gene, ]
		  result <- my_func(subanno$distanceToStart)
		  rawcounts[gene, allsamples] <- as.numeric(subanno[result, allsamples])
	  }
	```

Please fix all these issues.

**Comment by federicogiorgi** [comment]
@nturaga thank you!
I have one question: how do you know which lines are not correctly indented? The standard BiocCheck doesn't give me that in the output. I checked the lines and used tidy_source() from the formatR package but it doesn't seem to find the nasty lines.

**Comment by federicogiorgi** [comment]
@nturaga I implemented all the changes you suggested.

There is nothing I can do about the single warning, which seems to be on the server side:
"Installed Rcpp (0.12.12) different from Rcpp used to build dplyr (0.12.11)."

Also, 9 lines (0%) are not indented with multiples of 4 spaces, but those are man pages automatically generated by roxygen2.

**Comment by nturaga** [comment]
Hi @federicogiorgi 

I'll review your package again soon. But you need to fix a couple of things before that. 

1. Your formatting seems to have disappeared entirely on your R code.

2. `vobj` in vulcan, is a list containing samples, peak counts, and
   other data.frames, why not describe the contents of the list in the
   man pages, if it is being returned by the function `vulcan`?

   Please update the `man` pages, to be more informative, wherever else needed.

**Comment by federicogiorgi** [comment]
Thanks @nturaga. OK give me some time to manually fix every single line. The tidy_source function from formatR cannot at the same time force line length below 80 columns and transform indentation in multiples of 4 white spaces, for some reason. Ha, I've spent 90% of this package time on formatting indentation, no jokes :-)

**Comment by federicogiorgi** [comment]
@nturaga I have updated the man pages with extra info and reformatted the indentation of the source code :-) Again, I get this single server-side (I think) warning:
"Installed Rcpp (0.12.12) different from Rcpp used to build dplyr (0.12.11)."

**Comment by federicogiorgi** [comment]
@nturaga and all: I implemented all the suggested fixes, the package is ready for your inspection :-)

**Comment by federicogiorgi** [comment]
@lshep @mtmorgan @nturaga All the suggested fixes have been fixed a few weeks ago, the package is ready for your inspection :-)

**Comment by nturaga** [comment]
I'll have your second-review done by mid next week.

**Comment by federicogiorgi** [comment]
Any news on the second review? :-)

**Comment by nturaga** [comment]
* Please import to fix that NOTE.

```
Consider adding
  importFrom("graphics", "abline", "grid", "layout", "legend", "lines",
             "par", "plot", "points", "rect", "text")
  importFrom("stats", "ks.test", "pchisq", "pnorm", "pt", "qnorm", "qt",
             "rnorm", "setNames")
  importFrom("utils", "read.csv", "setTxtProgressBar", "txtProgressBar")

```

Also needed are

```
importFrom("GenomicRanges", "GRanges")
importFrom("S4Vectors", "Rle")
```

```
Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 33 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    object (function)
      Rle (average_fragment_length)
      lines (average_fragment_length)
      abline (average_fragment_length)
      legend (average_fragment_length)
      pt (corr2p)
      pchisq (fisherp)
      qt (p2corr)
      qnorm (p2z)
      ks.test (pareto.fit)
      e2s (plot_gsea)
      layout (plot_gsea)
      par (plot_gsea)
      plot (plot_gsea)
      rect (plot_gsea)
      abline (plot_gsea)
      text (plot_gsea)
      grid (plot_gsea)
      lines (plot_gsea)
      legend (plot_gsea)
      qnorm (rea)
      plot (textplot2)
      points (textplot2)
      lines (textplot2)
      text (textplot2)
      colorpanel (val2col)
      GRanges (vulcan.annotate)
      read.csv (vulcan.import)
      exprs (vulcan.normalize)
      setNames (vulcan.pathways)
      rnorm (vulcan.pathways)
      txtProgressBar (vulcan.pathways)
      setTxtProgressBar (vulcan.pathways)
      pnorm (z2p)
```

* Many place where you remove objects in the middle of the function eg:  `rm(rawmat)`
  vulcan.R, l 67, l, 82.

  This is not needed, if you are rewrinting the object, by creating a new matric in l71.


* In vulcan.R,

```
 232     ### Fix data types as needed
 233     for (j in seq_len(ncol(rawcounts))) {
 234         rawcounts[, j] <- as.numeric(rawcounts[, j])
 235     }
 236     rawcounts <- as.matrix(rawcounts)
 237
 238     for (j in seq_len(ncol(rpkms))) {
 239         rpkms[, j] <- as.numeric(rpkms[, j])
 240     }
 241     rpkms <- as.matrix(rpkms)
```

 can be replaced with,

 ```
 rawcounts = matrix(as.numeric(rawcounts), nrow(rawcounts))
 rpkms = matrix(as.numeric(rpkms), nrow(rpkms))
 ```


* Did not fix, `dist_calc` in vulcan.R. Lot of repeating code chunks.

**Comment by federicogiorgi** [comment]
@nturaga Thank you for your review! I implemented the suggested changes

- Fixed imports
- Removed the unnecessary rm()
- Corrected the vulcan.R lines as suggested (the suggested edit lacked dimnames, so I added that as well)
- Condensed repeated lines of code in dist_calc

**Comment by nturaga** [comment]
@federicogiorgi 

Your package times out in the build report because R CMD check takes more than 10 mins on the mac builder. Please fix this issue.

Otherwise, your package looks in good shape for acceptance.

**Comment by federicogiorgi** [comment]
@nturaga not sure why the R CMD Check times out on the Mac server. It didn't before, and the recent changes I've made to the package were formalities in the code. On our Mac, it takes ~3minutes. Any suggestion?

**Comment by federicogiorgi** [comment]
@nturaga I reduced the dummy dataset size (and the time of the examples) by 25%, but the time on the Mac server doesn't seem to change. I will try with some more example simplifications, but I believe it is possible that the delay is due to the Mac server. I am open to suggestions!

**Comment by federicogiorgi** [comment]
Dear @nturaga 
I cannot find a way to avoid the TIMEOUT on your Mac Server. R CMD check takes less than a minute on our Mac machine. I reduced the example data and the examples themselves (since the log tells me it is hanging there), but it didn't fix the problem. It's worth noticing that the check worked on the same server before the minor changes you suggested in the last review round (which had to do with code style, but didn't change at all the package functionality). I am not sure what to do now, I have no idea how to prevent the TIMEOUT on the Mac server :-/

**Comment by mtmorgan** [comment]
I ran this 'by hand' on the build server, where R CMD check took between 8 and 12 minutes. When run to completion, the examples prints out

```
* checking examples ... OK
Examples with CPU or elapsed time > 5s
                          user system elapsed
vulcan.pathways         56.571  7.022  62.722
vulcan                  48.242  3.804  57.260
...
```
On my Linux laptop `example(vulcan.pathways)` takes 60-70s. The example code starts with

```
library(vulcandata)
vfile<-'deleteme.csv'
vulcandata::vulcansheet(vfile)
vobj<-vulcan.import(vfile)
unlink(vfile)
```
The sequence takes about 60s, and is repeat on 6 man pages -- so about 6 minutes! I think that you must be checking your package without checking examples -- remember to build the package `R CMD build vulcan` and then check the built package `R CMD check vulcan_0.99.x...`.

Do the above code once, e.g., on `?vulcan.import`. Add the object resulting form `vulcan.import()` to vulcandata, provide a convenient way to access it, e.g., `vulcandata::vulcanexample()`, and use that on all other man pages.

Rather than creating a file in the user directory, create a temporary file

```
vfile <- tempfile()
```

I'm surprised that you have not corrected the following NOTEs, which I think are easy to address and not false positives:

```
* checking dependencies in R code ... NOTE
Packages in Depends field not imported from:
  'caTools' 'gplots'
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
...
* checking R code for possible problems ... NOTE
plot_gsea: no visible global function definition for 'e2s'
val2col: no visible global function definition for 'colorpanel'
vulcan.normalize: no visible global function definition for 'exprs'
Undefined global functions or variables:
  colorpanel e2s exprs
```

It was disappointing to see that the `vobj` returned by `vulcan.import()` contained GRanges-like objects but as simple data.frames. I revised `vulcan.import` to conclude with

```
    # Count reads in binding sites intervals
    dbcounts <- dba.count(dbobj, summits = intervals)
    
    # Extract counts from the dbacount object
    listcounts <- dbcounts$peaks
    names(listcounts) <- dbcounts$samples[, 1]
    
    ## Prepare RPKM matrix
    counts <- rpkms <- makeGRangesFromDataFrame(listcounts[[1]][1:3])
    mcols(counts) <- DataFrame(lapply(listcounts, `[[`, "Reads"))
    mcols(rpkms) <- DataFrame(lapply(listcounts, `[[`, "RPKM"))
    
    # Create an annotation structure
    samples <- split(sheet$SampleID, sheet$Condition)
    
    # Return output
    list(peakcounts = counts, samples = samples, peakrpkms = rpkms)
```
This means that subsequent code (e.g., in `vulcan.annotate()`) can be simplified by removing calls to `GRanges()`

**Comment by mtmorgan** [comment]
Oops, I'm sorry, my build machine times were based on a current version of the package but the suggestions above were from an old version.

**Comment by federicogiorgi** [comment]
@mtmorgan No problem! And thank you for taking your time and review this! I will embrace your suggestion of creating an example file in the vulcandata package, that will fix the TIMEOUT problem for sure :-)

**Comment by federicogiorgi** [comment]
@nturaga Success! :-)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/federicogiorgi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"vulcan\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/vulcan

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/federicogiorgi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"vulcandata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/vulcandata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
