### ISSUE TITLE
HiCdiff

### ISSUE THREAD

**Issue by jstansfield0** [Bioconductor/Contributions#394]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dozmorovlab/HiCcompare

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
These comments after a quick look so could be misguided; not meant to be a formal review.

The package doesn't seem to play well with other Bioconductor sequence analysis work flows; it should re-use existing infrastructure and present a user-oriented API around the GenomicRanges infrastructure, including the infrastructure in existing HiC-oriented packages.

It's really disappointing that 'straw' is accessible only as a command-line tool, which leads to very fragile work flows and data management.

**Comment by mdozmorov** [comment]
We've debated whether to use GRanges. The problem that Hi-C data formats and concepts are quite different to fit nicely into GRanges framework. Therefore, we kept simple "data.frame" structures while conforming with basics of BED and BEDPE formats. 
Any suggestions which Hi-C oriented package may be used as an example? Thanks

**Comment by mtmorgan** [comment]
[InteractionSet][] and [diffHic][] are possible examples; presumably your package overlaps closely with diffHiC, so it would be very valuable to distinguish the unique features you provide in the Description: filed and vignette. Have you communicated with @LTLA  ?

[InteractionSet]: https://bioconductor.org/packages/InteractionSet
[diffHic]: https://bioconductor.org/packages/diffHic

**Comment by mdozmorov** [comment]
We are looking into it and will update the submission asap. We do cite diffHic and describe the difference in the manuscript (submitted to biorXiv), and will describe in the Description, vignette. Thanks for the suggestions!

**Comment by lawremi** [comment]
Considering that GRanges and Pairs of GRanges were designed to support the "basics of the BED and BEDPE formats", I'm surprised that they don't work for you.

**Comment by mdozmorov** [comment]
The package has been updated to work with `InteractionSet` objects. Both input and output can be `InteractionSet` objects. The vignette has been updated to reflect the `InteractionSet` functionality.

**Comment by dvantwisk** [comment]
Hello!

Your package has build errors and failed to generate a build report on malbec1 (our windows single package builder), thus bioc-issue-bot didn't give you any build report.  The link below will give you a report on the errors.  Once the package builds without errors, warnings, or timeouts, we will begin reviewing it.

http://staging.bioconductor.org:8000/job/2621/

Thank You!

**Comment by jstansfield0** [comment]
We are done updating the package to correct for errors/warnings and it is ready for the formal review.

**Comment by dvantwisk** [comment]
We've reviewed your package.  It looks very good, but there is room for improvement, including places where the code can be better optimized.

DESCRIPTION
- Title / Description: Looks good
- Depends / Imports: Looks good
- Consider using `BiocParallel` instead of `parallel`
- biocView: Looks good!
- License: MIT license requires LICENSE file to be included in any software that uses the MIT license.  It is available here: https://cran.r-project.org/web/licenses/MIT

NAMESPACE
- It would be better to explicitly state what is being exported instead of exporting everything without a leading period.
- Consider explicitly enumerating each symbol that is being imported from each package using `importFrom()` unless there are too many symbols used from a package that it becomes tedious.
- Consider using `roxygen2` for generating the namespace.  Use `@export`, `@import`, and `@importFrom` inside `roxygen2` descriptions.


R

R/Cournac_normalization.R
- L33: `sqrt(colSums(a^2))` is better
- L34: Best to use `seq_len()` in loops in place of `:` to avoid the unexpected
  cases. (e.g. `1:0` results in `0`)
- L34: Rethink use of for loops and instead vectorize code to improve speed.
```{r}
    for(j in 1:n.cols) {
      for(i in 1:n.rows){
        a.new[i,j] <- a[i,j] / a.col.norms[j]
      }
    }
```
- Can be swapped for:
```{r}
	a.new <- t(t(a) / a.col.norms)
```

R/KRnormalization.R
- L88: Consider vectorizing for-loop with: 
```{r}
	idx <- as.matrix(NAlist[, 1:2])
	result[idx] <- NA
```

R/create_hic_table.R
- L79: use `is` to determine if s4 object is of a certain class:
```{r}
	is(sparse.mat1, "GInteractions") & is(sparse.mat2, "GInteractions")
```

- L160: Consider changing return value of create.hic.table to `data.frame`, `GRanges`, or `InteractionSet` instead of using `data.table`.  These other representations would be easier for the user to utilize.


R/hic_diff.R
- Consider using `BiocParallel` here instead of `parallel`.  i.e. use `bplapply` instead of `mclapply` and `mcmapply`.


R/hic_simulate.R
- L31: avoid the double for loop by using vectorization to increase speed.  
- `j` can be calculated as `unlist(Map(seq, 1:ncol(cell1), MoreArgs=list(ncol(cell1))))`
- `i` can be calculated as `rep(seq_len(nrow(cell1)), times=head(rev(seq_len(ncol(cell1)))`, nrow(cell1)))
- `distance`, `Bmean`, and `noise.sd` can be broguth out of the loop.
- L36: instead use `cell1[cbind(i, j)] <- round(Bmean) + round(rnorm(i, 0, noise.sd))`

- L260: use `message()` instead of `print(paste())`

R/internal_functions.R
- Consider liquidating file and to place internal functions in respective R files.
- L128: `paste()` is unnecessary

R/matrix_transformations.R
- L68: Instead of iterating through rows, create an index matrix of `rcix <- sparse.mat[,c(2, 5)]`
- populate `mat[rcix] <- sparse.mat[,3]`
- `rcix <- rcix[, c(2, 1)]` and `mat[rcix] <- sparse.mat[,3]`

- L162: avoid copy and append pattern
- preallocate instead of iteratively adding to list with `sparse.list <- vector("list", length(chroms))`
https://www.bioconductor.org/developers/how-to/efficient-code#pre-allocate-and-fill-if-iterations-are-necessary

man

- Good!


tests

- test_pipeline_works.R: sections 'Pipeline works' and 'Settings for hic_loess work'
both have no tests.

- Tests seems rather sparse in general.  Consider adding more tests to ensure code has desired functionality for the user.  For example, consider adding tests to verify that functions stop properly on bad input, etc.


Vignette

- 'Install packages' section not needed once your package is accepted to Bioconductor.
- Remove section about installing through github.

**Comment by jstansfield0** [comment]
I have updated the package to address the issues in your review. We are also considering changing the name of our package to avoid confusion with diffHic and were wondering what the process would be to change the name of our package before it is put up on Bioconductor?

**Comment by dvantwisk** [comment]
To change the name of the package, we need you to modify the name of the repository url in your first post to include the new name of your package.

**Comment by jstansfield0** [comment]
I created a new repository with our package under the name HiCcompare and changed the URL in the first post along with setting up the webhook. The version number has been bumped, but the "version bump required" tag is still there. Do I need to do anything else or did I set something up incorrectly?

**Comment by dvantwisk** [comment]
Can you double check the webhook and try a version bump once more.  If the package refuses to build again, we will look further into the issue.

**Comment by jstansfield0** [comment]
I deleted the webhook and re-added it then bumped the version again. It still does not seem to be building the package.

**Comment by mtmorgan** [comment]
Repos name changes need a manual step; I've done that so one more version bump should do the trick.

**Comment by jstansfield0** [comment]
I bumped the version again. On my end it still does not seem to have triggered a rebuild of the package.

**Comment by mtmorgan** [comment]
OK, sorry, one 'last' time.

**Comment by jstansfield0** [comment]
I am now getting the following warning: checking for unstated dependencies in 'tests' ... WARNING
'library' or 'require' call not declared from: 'HiCdiff'

This was not an issue until the name change. I'm guessing it thinks the functions being used in the tests are coming from the old package instead of the current package name as I have a library(HiCcompare) statement in all of my tests. I have tried googling the warning but the results all deal with using objects from imported packages not being declared or loaded. How can I fix this?

**Comment by dvantwisk** [comment]
Is the package ready for the review to continue?

**Comment by jstansfield0** [comment]
Yes, please continue the review.

**Comment by dvantwisk** [comment]
Things looks good!  We are accepting your package.  We do, however, recommend that once your package is accepted, that you remove the remaining commented out code.

**Comment by dvantwisk** [comment]
One last thing!  You have the file `HiCcompare.Rproj` in your packages root directory.  This file isn't needed and it would be best to include this in `.gitignore`.
