### ISSUE TITLE
consensusOV

### ISSUE THREAD

**Issue by kofiav** [Bioconductor/Contributions#397]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/consensusOV

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
DESCRIPTION, etc.

- Please provide a more extensive Description: like a paper abstract
  describing what specific functionality is provided by this package.
- It looks like this is meant to be a 'software' package, so the
  biocViews terms should come from the Software hierarchy
  
    http://bioconductor.org/packages/release/BiocViews.html#___Software

- A NEWS file is good practice, but it should be parsable by
  `utils::news()`.

R

- use `base::trimws()` rather than dataset.merging.R:30
  `strip.white.space()`
- use `seq_len()` rather than `1:n` see
  http://bioconductor.org/developers/how-to/efficient-code/
- carefully consider each use of 'iteration' (`for` loops,
  `l`/`sapply`, `apply`, ...) and replace with 'vectorization', e.g.,
  get.verhaak.subtypes.R:24 use row/colMin/Max() where appropriate.
  
[BiocParallel]: https://bioconductor.org/packages/BiocParallel

vignette

- The code chunks in the vignette are a confusing collection of
  `results="hide"` and `eval=FALSE` chunks -- present exactly what the
  user will do, with fully evaluated chunks.
- Consider a more modern approach (`ggplot2::facet_grid()`) to
  visualization.

other

- it seems like the fData columns 'probeset', 'gene', 'EntrezGene.ID'
  of the data set are all factors, but should be character().
- I find your code quite hard to read from a stylistic perspective, with the problem being long lines of nested logic. As an example

      helland.gene.set <- Reduce(function(x,y) union(x, y), lapply(entrez.id.logFC.list.helland, function (x) x$ENTREZID))
  
  might be formatted to 80 characters and broken into more natural 'phrases'
  
      helland.gene.set <- Reduce(
          union, 
          lapply(entrez.id.logFC.list.helland, `[[`, "ENTREZID")
      )

  likewise

      subtype.scores <- sapply(entrez.id.logFC.list, function(x) {
          ordered.expression.subset <- expression.matrix[match(x$ENTREZID, entrez.ids),]
          return(apply(ordered.expression.subset, 2, function(y) sum((y * x$logFC))))
      })

  might end up as
  
      subtype.scores <- sapply(entrez.id.logFC.list, function(x) {
          idx <- match(x$ENTREZID, entrez.ids)
          ordered.expression.subset <- expression.matrix[idx, , drop=FALSE]
          colSums(ordered.expression.subset * x$logFC)  # FIXME: correct?
      })

**Comment by lawremi** [comment]
Maybe you could avoid the `Reduce()` altogether and just use `unlist()` and `unique()`.

```
helland.gene.set <-unique(unlist(lapply(entrez.id.logFC.list.helland, `[[`, "ENTREZID")))
```

**Comment by mtmorgan** [comment]
Is your package ready for continued review? IF so please add a version bump to trigger a build, and post a brief comment indicating how you have responded to comments.

**Comment by kofiav** [comment]
@mtmorgan 

The package is ready for continued review. We addressed all the concerns raised in the previous review

- extended DESCRIPTION

- added appropriate software biocViews

- replaced iterations with vectorizations based on matrixStats

- re-working of vignette incl. displaying results and ggplot2-based facet plots

- changed fData columns from type factor to type character

- fixed line formatting to stay at 80 char limit
