### ISSUE TITLE
omicsPrint

### ISSUE THREAD

**Issue by mvaniterson** [Bioconductor/Contributions#400]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/molepi/omicsPrint

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mvaniterson** [comment]
Dear Marcel Ramos, 
The warnings the appear are from BiocCheck a few long lines and spaces. I would like to leave this as it is I think it clarifies the code. Can we close this issue and continue the review process?

Regards, 
Maarten

**Comment by LiNk-NY** [comment]
Hi Maarten, @mvaniterson
Clear code is neatly formatted.
You don't have to worry about the Note from `BiocCheck`.
The number of lines over the limit are few.

Thank you,
Marcel

**Comment by LiNk-NY** [comment]
Hi Martin, @mvaniterson
Please reduce the size of your repository. 
I am currently getting a download size greater than 200 MB. 
You should be excluding any compiled files and reports from the repository via `.gitignore`.
If you have already commited large files, I recommend you remove them and subsequently use the BFG Repo-Cleaner.

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Any updates on this Martin @mvaniterson ?

**Comment by mvaniterson** [comment]
Dear Marcel,

Indeed, I generated vignettes in pdf format which became too large. I've
made a new push and remove the pdfs only retaining the html vignettes.

Cheers,
Maarten

**Comment by LiNk-NY** [comment]
Hi Martin, @mvaniterson
Sorry for the delay. I will have a look at your package soon. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Martin, @mvaniterson
I recommend that you use https://rtyley.github.io/bfg-repo-cleaner/ for removing large git history files from your repository. 
I am currently getting a total size of `158M	omicsPrint/` for your folder. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Martin, @mvaniterson

Thank you for submitting to Bioconductor. 
Please see `omicsPrint`'s review below. 

If you have any questions, please feel free to contact me.

Best regards,
Marcel

---

# omicsPrint #400

Overall, it is very useful to do quality control for multiple 'omics
experiments. It would be beneficial for your package to integrate these
checks along with a unifying multi-omics structure such as `MultiAssayExperiment`,
`MultiDataSet`, etc. Please look into `RaggedExperiment` for
representing Copy Number data as the functionality may be of interest.

## DESCRIPTION

* Please wrap your lines to less than 80 width.
* There are no Bioconductor packages in your Imports field.
We recommend that you work with the existing Bioconductor infrastructure.

## NAMESPACE 

Looks okay

## vignettes

* Suggestion: It would be good to have an example of functionality with
real-world data put here instead of in `inst/doc`

## R

* Please support existing Bioconductor infrastructure as input for
`alleleSharing` such as `SummarizedExperiment`. 

## Formatting

* Please keep code neat and do not go past 80 column widths. This
improves readability.

---

**Comment by LiNk-NY** [comment]
Hi Martin, @mvaniterson 
Any updates on making changes to the package? 
Regards,
Marcel

**Comment by mvaniterson** [comment]
Hi Marcel,
I got another job. I'm trying to get someone how can replace me in this submission.
Cheers,Maarten


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Marcel Ramos <notifications@github.com> Datum: 22-09-17  20:31  (GMT+01:00) Aan: Bioconductor/Contributions <Contributions@noreply.github.com> Cc: "M. van Iterson" <mviterson@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [Bioconductor/Contributions] omicsPrint (#400) 
Hi Martin, @mvaniterson

Any updates on making changes to the package?

Regards,

Marcel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Bioconductor/Contributions","title":"Bioconductor/Contributions","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Bioconductor/Contributions"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LiNk-NY in #400: Hi Martin, @mvaniterson \r\nAny updates on making changes to the package? \r\nRegards,\r\nMarcel"}],"action":{"name":"View Issue","url":"https://github.com/Bioconductor/Contributions/issues/400#issuecomment-331526217"}}}

**Comment by mvaniterson** [comment]
Hi Marcel,

We found a someone, Davy Cats, who is willing to continue the submission
and will make the requested additions.

His is in the cc!

How do we proceed the changing of developers?

Cheers,
Maarten

**Comment by LiNk-NY** [comment]
Hi Martin, @mvaniterson 
Please add Davy to [molepi/omicsPrint](https://github.com/molepi/omicsPrint) so that he has commit access to the repository. 
He should also be included in the Description file as the maintainer. 
Please also have him fill the Google Form found here (http://master.bioconductor.org/developers/how-to/git/new-package-workflow/) in Step 1.
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Maarten, @mvaniterson 
Any updates on this? 
Thanks,
Marcel

**Comment by DavyCats** [comment]
Hey Marcel,

I have filled in the form. 

Best regards,
Davy Cats

**Comment by mvaniterson** [comment]
Dear Marcel,

Davy has extended the package with an interface for SummarizedExperiment
objects. We have added data that was available in a local package
(DNAmArray) to omicsPrint this makes it easier to run the additional
vignettes.

We still struggle with how to add the extended vignettes because they
require data download from GEO which takes too long for the bioc build
system. I check some other vignettes, i.e MultiAssayExperiments and noticed
that not all are build by the bioc build system but use prebuild vignettes.
We provide these for omicsPrint in the inst/doc folder. Would this be
sufficient?

Please let us known if there is a better approach.

Kind regards,
Maarten

**Comment by LiNk-NY** [comment]
Hi Maarten, @mvaniterson
Yes, ideally you would have a smaller dataset that can be used as an example 
in the vignette. 

Please try to keep the data downloads minimal as your package
could timeout in our build system.

We don't provide prebuilt vignettes in `MultiAssayExperiment` but rather a reference
sheet for methods for the user's convenience. We also don't encourage static code
in the vignettes and we are working on providing a runnable example in `MultiAssayExperiment`.

Best regards,
Marcel

**Comment by mvaniterson** [comment]
Hi Marcel,

We found a smaller dataset on geo and added a use-case with this data to
the vignette. The package and vignette pass all checks now!

Cheers,
Maarten

**Comment by LiNk-NY** [comment]
Hi Maarten, @mvaniterson 
* The built tarball is quite large at `8 Mb`. Please reduce the size of the tarball by using smaller
data files in the package.
* Please do not provide static vignettes in the `docs` directory. We highly encourage runnable vignettes.

Many issues can arise with static code as it is not tested and API changes can often break it.

We recently increased the time allowed for vignettes to run on our build machines.
This should provide some leeway in the time it takes to run vignette code in your package.

* The git repository seems quite large, registering at `172 Mb` on my machine. Please note that after using the BFG-repo cleaner, all local repos that did not get the BFG treatment should be deleted and such repos should be re-cloned from GitHub.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Maarten, @mvaniterson 

Thank you for making those changes.

Your package has been accepted. Thank you for contributing to Bioconductor!

Best regards,
Marcel

**Comment by mvaniterson** [comment]
Hi Marcel,

Thanks for the good news!

Regards,
Maarten

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mvaniterson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"omicsPrint\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/omicsPrint

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
