### ISSUE TITLE
scmap

### ISSUE THREAD

**Issue by wikiselev** [Bioconductor/Contributions#404]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hemberg-lab/scmap

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
When you've addressed these issues, please post a comment summarizing your response.

DESCRIPTION

- Description: field should be more like a paper abstract to help
  users distinguish the unique features associated with your package.
  
vignettes

- ok
- consider adding a final `sessionInfo()` section.

R

- consider using the `signature=` argument to `setGeneric()` to limit
  dispatch to arguments that will be of different type (e.g.,
  `signature="object"` for `getFeatures()`.
- Use accessors when available, rather than direct slot access, e.g.,
  CoreMethods.R:39 simply use `fData()`.
- Use constructors when available e.g.,
  CoreMethods.R:43`AnnotatedDataFrame()` rather than
  `new("AnnotatedDataFrame")`.
- Simplify `setMethod("getFeatures")` to remove the anonymous function
  that simply forwards to a funtion with the same signature

    ```
    setMethod("getFeatures", "SCESet", getFeatures.SCESet)
    ```
- Signal errors with `stop()` when appropriate, e.g,. CoreMethods.R:82
  the `message()` seems really to be an error.
- No need to `message(paste0())` -- `message()` pastes its arguments
  anyway. Likewise with `warning()`, `stop()`.
- Use `inherits()` (S3) or `is()` (S4) rather than `class()`, e.g.,
  CoreMethods.R:163.
- Consider `matrixStats::colMaxs()` rather than `apply(..., max)` and
  similar.
- CoreMethods.R:258 the sequence
  `matrix(unlist(apply(matrix(unlist(apply(tmp, ...` seems highly
  unnecessary -- maybe `tmp` should be a matrix and then the coercions
  are not necessary, or the internal function should return a
  consistent type so that `apply()` recognizes the return as a matrix.
- Consider using formatR or similar to provide standardized code formatting.

man

- ok

misc

- format NEWS to be parsed by `utils::news()`.

**Comment by wikiselev** [comment]
Hi Martin,

Many thanks for your comments. I have addressed all of them - please see my latest commit.

Cheers,
Vladimir
