### ISSUE TITLE
Doscheda

### ISSUE THREAD

**Issue by brunocontrino** [Bioconductor/Contributions#406]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/brunocontrino/Doscheda

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by brunocontrino** [comment]
I have now subscribed to the Bioc-devel. Apologies for this oversight

**Comment by nturaga** [comment]
# Doscheda Review

## BUIlD

* R CMD build Doscheda: ok

* R CMD INSTALL Doscheda: ok

## DESCRIPTION

* Description needs to be more like a paper abstract, and it needs to give more information.

* BiocViews need to be more informative.

## NAMESPACE

* Ok

## man

* Try to explain what the output values are, e.g runDoscheda returns a class ChemoProtSet, where can I find documentation for that class?

* Address similar issues in other man pages.

* But everything else is well documented.

## Vignette

* BiocStyle CSS is not being applied. There is likely an error in your vignette.

* Not sure why you are setting eval=FALSE on chunk runDosEX 

* Link to manual for App is dead. Check all links. 

## R

* Use 4 spaces to indent as needed. Use `formatR` package (https://cran.r-project.org/web/packages/formatR. Check coding style and re style your code (https://www.bioconductor.org/developers/how-to/coding-style/).


* Remove commented code (line 22: non_exported.R)

* vectorize this ?

	```
     for(i in 1:nrow(columnindex)){

      columnindex[i,4] <- index.mat[columnindex[i,1],columnindex[i,2]]
      # same as columnindex[,4] <- index.mat[ columindex[, 1:2] ]
      columnindex[i,5] <- index.mat[columnindex[i,1],columnindex[i,3]]

    }
	```  
	Can be replaced by

    ```
    columnindex[,4] <- index.mat[ columnindex[, c(1,2)] ]
    columnindex[,5] <- index.mat[ columnindex[, c(1,3)] ]
    ```


* No need of a for loop here

    ```
     for( i in 1:nrow(columnindex)){
       create.names[i] <- paste(ser[columnindex[i,4]], "vs", ser[columnindex[i,5]])
     }
	```
	can be,

	```
    create.names <- paste(ser[columnindex[,4]], "vs", ser[columnindex[,5]])
	```

Now that we have given an example of those two, you can evaluate if you really need `for` loops in other places of your code.


* Use `seq_len(nchan)` instead of `1:nchan`. This will account for a possible 0 value. (in non_exported.R)

	```
	  for(i in  1:nchan){
    	newframe[(minrow+1):maxrow,i]<- mean(small.pep[,i])
  	}
	``` 
	
	 other example: `1:length(df_ordered$GeneID)`. Replace all instances of such code. There are multiple instances.

	You actually don't need a loop here, you can used `colMeans` which is vectorized. Check all loops like this.


* 	Here you have a for loop and then an "apply" function.	

	```
	for(i in 1:length(prot2)){

        ## grep for total intensity () includes non unique peps
        protdf2[i,1:chans] <- apply(newdf2[grep(prot2[i],newdf2$Accession),1:chans],2,stats::median,na.rm = TRUE)
 	```

	`rowMedian` (package: matrixStats)  is a vectorized function. Use that instead of an apply function.

* `..count..` notation, does it have any special meaning? (plot.ChemProtSet.R l:20) 

* The main slots of the ChemoProtSet should be accessible to the user with functions, instead of using the `@` symbol.

**Comment by brunocontrino** [comment]
# Description

All points addressed

# Vignette 
- BiocStyle CSS applied. Output is html

-  eval=FALSE on chunk runDosEX because the code has been run in the vignette, aimed to show the example in the vignette without seeing all the different chunks.

- Link to manual changed and working.

# man
- see also has been added to relevant functions / methods that contain a `ChemoProtSet` object

# R 
- All changes attempted. 

- removed loops where possible.

- `..count..` came from the output of another package, attempted changing name but caused problems. 

- main slots available through accessor function in `accessor.R`

**Comment by nturaga** [comment]
I'll have your second-review by mid next week.

**Comment by nturaga** [comment]
@brunocontrino 
Please remove to get rid of warnings on the build report.

```
inst/doc:
Doscheda.R    Doscheda.html
```

**Comment by brunocontrino** [comment]
Files have been removed

**Comment by mtmorgan** [comment]
Your ssh public keys have been added from GitHub; you can access your
Bioconductor repository using the corresponding private key(s); the
command

    ssh git@git.bioconductor.org

should include a line like

    R W    packages/YOUR_PACKAGE_NAME

indicating read / write access is available.

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.
