### ISSUE TITLE
TFHAZ

### ISSUE THREAD

**Issue by albmarch** [Bioconductor/Contributions#428]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DEIB-GECO/TFHAZ

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Thanks for your package and sorry for the delay in this initial review.

DESCRIPTION

- Consider more precise biocViews terms

- Consider a slightly more extensive Description: to provide the user with a better understanding of the methods implemented in the package.

- No need to include the file LICENSE for Artistic-2.0; the text of this license is always available at `R.home("share/licenses")`

vignette

- Your key function, `accumulation()` is not evaluated in the vignette. This is a very poor idea, especially since your package has no unit tests -- it is all to easy for your documentation to change from implementation, and then the user is frustrated at the very first step. Carefully identify a smaller subset of data that can be analyzed in a reasonable amount of time but that retains relevance to your package.

- Consider using BiocStyle to format your vignette. 

- Generally, html-based vignettes are much easier for users.

R

- Examine each `for` loop for opportunities to vectorize, i.e., write a single function call that operates on vectors, rather than iterating through elements. start by cleaning up the code, with correct formatting. Then 'hoist' common expressions out of the loop. 

- For instance: accumulation.R:50 can be revised as

```
for (i in 1:length((start(chrom_tf)))) {
    if (start(chrom_tf[i])-w <=0) {
        v_tf[1:(end(chrom_tf[i])+w)]= v_tf[1:(end(chrom_tf[i])+w)]+1
    } else {
        v_tf[(start(chrom_tf[i])-w):(end(chrom_tf[i])+w)]=v_tf[(start(chrom_tf[i])-w):(end(chrom_tf[i])+w)]+1
    }
}

## code clean-up -- use a variable `idx` to hold intermediate expressions, 
## Introduce space (like 'words') around operators
## use `seq_along()` to generate sequences that are robust to length-0 vectors
for (i in seq_along(chrom_tf)) {
    start <- start(chrom_tf[i]) - w
    end <- end(chrom_tf[i]) + w
    if (start <=0) {
        idx <- seq_len(end)
        v_tf[idx]= v_tf[idx] + 1
    } else {
        idx <- start:end
        v_tf[idx] = v_tf[idx] + 1
    }
}


## if the same value is calculated in both branches of the if statement, 
## calculate it outside the if. 
for (i in seq_along(chrom_tf)) {
    start <- start(chrom_tf[i]) - w
    end <- end(chrom_tf[i]) + w
    if (start <= 0) {
        idx <- seq_len(end)
    } else {
        ## start:end = (start - 1) + seq_len(end - (start - 1))
        idx <- (start - 1) + seq_len(end - (start - 1))
    }
    v_tf[idx] = v_tf[idx] + 1
}

## pull expressions that can be caculated in a vectorize fashion out of the loop
starts <- start(chrom_tf) - w
ends <- end(chrom_tf) + w
for (i in seq_along(chrom_tf)) {
    start <- starts[i]
    end <- ends[i]
    if (start <= 0) {
        ## nb: seq_len(end) = (1 - 1) + seq_len(end - (1 - 1))
        idx <- seq_len(end)
    } else {
        idx <- (start - 1) + seq_len(end - (start - 1))
    }
    v_tf[idx] = v_tf[idx] + 1
}

## move the condition outside the loop by updating start when it is less than 1
## vectorize end - start (one call, instead of length(chrom_tf) calls)
starts <- start(chrom_tf) - w - 1  ## 'start - 1'
starts[starts < 1] <- 1
ends <- end(chrom_tf) + w - starts
for (i in seq_along(chrom_tf)) {
    idx <- starts[i] + seq_len(ends[i])
    v_tf[idx] = v_tf[idx] + 1
}

```

This code will be considerably faster than the iteration, because we are making many fewer calls to R functions. It also seems much easier to read.

I think though that what you are doing is to take ranges and expand them

```
start(chrom_tf) <- pmax(1, start(chrom_tf) - w)
end(chrom_tf) <- end(chrom_tf) + w
```

and then calculating the coverage

```
cvg <- coverage(chrom_tf)
```

To test the different approaches, I wrote the following little functions

```
f0 <- function(chrom_tf, w = 10) {
    v_tf <- sparseVector(0, 0, max(end(chrom_tf)) + w)
    for (i in 1:length((start(chrom_tf)))) {
        if (start(chrom_tf[i])-w <=0) {
            v_tf[1:(end(chrom_tf[i])+w)]= v_tf[1:(end(chrom_tf[i])+w)]+1
        } else {
            v_tf[(start(chrom_tf[i])-w):(end(chrom_tf[i])+w)]=v_tf[(start(chrom_tf[i])-w):(end(chrom_tf[i])+w)]+1
        }
    }
    v_tf
}

f1 <- function(chrom_tf, w = 10) {
    v_tf <- sparseVector(0, 0, max(end(chrom_tf)) + w)
    starts <- start(chrom_tf) - w - 1
    starts[starts < 1] <- 1
    ends <- end(chrom_tf) + w - starts
    for (i in seq_along(chrom_tf)) {
        idx <- starts[i] + seq_len(ends[i])
        v_tf[idx] = v_tf[idx] + 1
    }
    v_tf
}
f2 <- function(chrom_tf, w = 10) {
    start(chrom_tf) <- pmax(1, start(chrom_tf) - w)
    end(chrom_tf) <- end(chrom_tf) + w
    coverage(chrom_tf)
}
```

generated some test data

```
testdata <- function(n) {
    start <- ceiling(runif(n, 1, 100000))
    end <- start + ceiling(runif(n, 100, 200))
    GRanges("chr1", IRanges(start, end))
}

set.seed(123)
gr <- testdata(100)
```

and then tested them for performance and (more importantly) consistency

```
> system.time(res0 <- f0(gr))
   user  system elapsed 
  1.744   0.000   1.745 
> system.time(res1 <- f1(gr))
   user  system elapsed 
  0.108   0.000   0.110 
> system.time(res2 <- f2(gr))
   user  system elapsed 
  0.016   0.000   0.017 
> identical(res0, res1)
[1] TRUE
> all.equal(as.vector(res0), as.vector(res2$chr1))
[1] TRUE
```

For this small data set of 100 ranges, the simplified base R approach is about 20 times faster and much easer to read. The GRanges approach is 100x faster, and just three lines of more-or-less intelligible code. The GRanges approach should scale better than the base R approach, because it is implemented with a little more sophisticated algorithm

```
> library(microbenchmark)
> gr100 <- testdata(100); gr200 <- testdata(200); gr500 <- testdata(500)
> microbenchmark(f1(gr100), f1(gr200), f1(gr500), times=5)
Unit: milliseconds
      expr       min        lq      mean    median        uq       max neval
 f1(gr100)  105.3171  106.0144  106.1833  106.0772  106.3301  107.1776     5
 f1(gr200)  335.4242  338.2077  384.0478  338.2351  340.3300  568.0418     5
 f1(gr500) 1908.5547 1914.0102 1957.5360 1915.6793 1917.8836 2131.5524     5
> gr1000 <- testdata(1000); gr10000 <- testdata(10000)
> microbenchmark(f2(gr100), f2(gr200), f2(gr500), f2(gr1000), f2(gr10000), times=5)
Unit: milliseconds
        expr      min       lq     mean   median       uq      max neval
   f2(gr100) 15.53677 15.54683 16.24059 15.61588 15.71575 18.78769     5
   f2(gr200) 15.60508 15.60963 15.86663 15.68851 15.95221 16.47773     5
   f2(gr500) 15.86266 15.92075 16.28874 15.94486 16.84758 16.86785     5
  f2(gr1000) 16.34693 16.38228 16.83074 16.39721 17.10435 17.92291     5
 f2(gr10000) 24.12971 24.20321 24.81380 24.63983 25.18818 25.90806     5
```

- The above took me a couple of hours of fairly careful analysis, so the task for you is daunting but necessary -- there are very substantial performance gains to be had.

- Generally, your code will be more performant if you use S4Vectors data structures like the Rle from `coverage()`, rather than data structures from the Matrix package.

- Please format your code in a standard way, e.g., following the [Bioconductor style guide][1]; the formatR package may be helpful. Please especially pay attention to consistent indentation (4 spaces recommended and avoiding lines longer than 80 characters.

- use `seq_len()` or `seq_along()` instead of `1:n` throughout.

- Start each function with code that validates arguments, e.g., `accumulation()` should check that `data` is the appropriate class, that `acctype` is from the appropriate choices (e.g., using `match.arg()`, etc.

- use `message()`, `warning()`, or `stop()` to communicate with your user inside functions, rather than `print`.

- never use `@` to access elements of S4 objects structures; use accessors provided by the class

man

- OK

[1]: http://bioconductor.org/developers/how-to/coding-style/

**Comment by albmarch** [comment]
@mtmorgan 
Hello.
Thanks for the suggestions, they were very helpful.
I made the required changes, but I have a problem with the automated builder.
On Linux there is an error in the vignettes creation:

creating vignettes ... ERROR
pandoc: Could not fetch ./dense_zones_12.png
./dense_zones_12.png: openBinaryFile: does not exist (No such file or directory)
Error: processing vignette 'TFHAZ.Rmd' failed with diagnostics:
pandoc document conversion failed with error 67

For the other OS this error is not present and I don't know how to solve the problem.
Do you have any suggestion?

Best regards,
Alberto Marchesi

**Comment by mtmorgan** [comment]
Use correct capitalization -- linux file systems are case sensitive.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (tithub.com/<username>.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]

1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/

[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/

https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
