### ISSUE TITLE
scPipe: a package for single cell RNA-seq data processing

### ISSUE THREAD

**Issue by LuyiTian** [Bioconductor/Contributions#431]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LuyiTian/scPipe

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LuyiTian** [comment]
I have updated the package to fix errors: https://github.com/LuyiTian/scPipe/commit/cc3260078c854c94f28cef1fda4ee955e43db6ed

also added the Webhook to my repo, but the first delivery is failed with error: "Only push, issue, and issue comment event hooks supported". I have selected "Just the push event."

**Comment by lawremi** [comment]
There seem to be a lot of partially overlapping packages for single cell RNA-seq. Rather than package up an entire workflow, why not release each of these steps as a separate package? Users could then mix and match algorithms to construct pipelines. It's fine to publish a workflow package, but it should probably just combine other, independent components. With the convergence towards common data structures like SingleCellExperiment, it seems like there is now a critical mass for these packages to start working towards modular interoperability.

Btw, this should probably generate a SingleCellExperiment, or at least a SummarizedExperiment.

**Comment by LuyiTian** [comment]
@lawremi Thanks for your advice. 

Yes I agree there are a huge amount of scRNA-seq packages now but instead of the whole workflow, scPipe only tries to fill the gap between fastq and gene counting matrix and QC information, generating the consistent result for different protocols. It does the similar things as [Cellranger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger) does for 10X, but works for all the scRNA-seq protocols like CEL-seq and Drop-seq.

I have an SCData object, designed in a similar way as SCE in scater and the workflow does generate an SCData object in the end. But now I am working on transforming all the SCData related functions to SingleCellExperiment since more packages are gonna use it in the near future.

**Comment by LuyiTian** [comment]
@vobencha @lawremi  My package does not work on windows because of the C++ code. Could you tell me how do I suppress the build on windows platform?  Currently, the only error comes from the windows. Thank you very much.

**Comment by vobencha** [comment]
Suppressing the build on windows is not an option. The package must build on all 3 platforms - this is part of the new package requirements. 
Valerie

**Comment by LuyiTian** [comment]
@vobencha  We are working on the code so it could be built on win. But is it possible to limit my package to only linux the Mac, because my package contains a lots of C++ code which compiles at unix but failed in win platform by mingw_64.

**Comment by vobencha** [comment]
I won't be doing a full review until the package passes build and check on all 3 platforms. As I mentioned before, the requirements are that that package build on all 3 platforms or it won't be accepted into the BioC repository. You are welcome to submit to CRAN if you can't make it build on windows.
Valerie

**Comment by vobencha** [comment]
Hi,

I've taken a look at the package. I think we should postpone review until you've switched the code over to use SingleCellExperiment or scatter::SCESet as appropriate and removed the SCData structure.

I also think the package should be renamed to something more descriptive. scPipe doesn't say much about what the package does. You said you're focusing on  "the gap between fastq and gene counting matrix and QC information, generating the consistent result for different protocols.". Maybe something along the lines of SingleCellQC?

Some general comments on package development:

1) Format the code to be <= 80 characters wide.

2) man page examples and /dontrun
In general, all man pages need examples and should not have /dontrun statements. Even if this is pipeline small examples of relavent functions should be shown. If you feel there are special cases these will need to be explained.

3) Inconsistent naming of package functions and classes

    Currently there is a mixture of camelCase and underscores. Please choose one consistent name scheme:
```
~//scPipe/man >ls
calQCMetrics.Rd    create_report.Rd      FACSData.Rd         merge_SCData.Rd  plotQC_pair.Rd      sc_celseq2_simulator.Rd  sc_detect_bc.Rd      scPipe.Rd           tpm.Rd
convert_geneid.Rd  create_scd_by_dir.Rd  fpkm.Rd             newSCData.Rd     QCMetrics.Rd        SCData.Rd                sc_dim_reduction.Rd  sc_sample_data.Rd
counts.Rd          detect_outlier.Rd     gene_id_type.Rd     organism.Rd      remove_outliers.Rd  SCData-subset.Rd         sc_exon_mapping.Rd   sc_sample_qc.Rd
cpm.Rd             DimReducedExpr.Rd     get_genes_by_GO.Rd  plot_mapping.Rd  run_scPipe.Rd       sc_demultiplex.Rd        sc_gene_counting.Rd  sc_trim_barcode.Rd
```
4) S4 methods
S4 methods in R do not use the dot '.' for dispatch. It looks like you've created helpers (named with dot) for your accessors and then exported them. Usually helpers are created when code is reused by several functions or something rather complicated is going on. I see neither case here.

    For example, I don't see the point of creating counts.SCData(); instead the one-liner could just be part of counts(). If you feel you need the helper then it should be internal only and not exported.
```
counts.SCData <- function(object) {
  object@assayData$counts
}
setMethod("counts", signature(object = "SCData"), counts.SCData)
```
These should not be exported:
```
~/repos/git/software/scPipe >grep '\.SCData' NAMESPACE
export(FACSData.SCData)
export(QCMetrics.SCData)
export(counts.SCData)
export(fpkm.SCData)
export(gene_id_type.SCData)
export(organism.SCData)
export(tpm.SCData)
```

5) Instead of dir.create() in the vignette user tempdir().

6) general tidy
The package has many typos and does not use capitalization for complete sentences. For example, here is lack of capitalization on the convert_geneid.Rd man page:
```
\item{returns}{the gene id which is set as return. default to be `external_gene_name`
A possible list of attributes can be retrieved using the
function \code{listAttributes} from \code{biomaRt} package. the commonly used
id types are `external_gene_name`, `ensembl_gene_id` or `entrezgene`.}

\item{all}{logic. for genes that cannot covert to new gene id, keep them with the old
id or delete them. the default is keep them.}
```
Typos on convert_geneid.Rd:  
The argument name is 'returns' but the example uses 'return':
```
scd = convert_geneid(scd, return="entrezgene")
```
Please review the man pages and vignette for typos, capitalization and code format (max 80 characters wide).

I would like to close this issue and have you open a new issue once SingleCellExperiment has been incorporated and the package has been renamed.

Valerie

**Comment by LuyiTian** [comment]
@vobencha Thank you for your comment. Your suggestions are very helpful, though I would be conservative about the package naming.

I will close the issue and resubmit it soon.
