### ISSUE TITLE
stageR

### ISSUE THREAD

**Issue by statOmics** [Bioconductor/Contributions#432]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/statOmics/stageR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
I wonder if the _stageRTx_ class could extend _SummarizedExperiment_

**Comment by statOmics** [comment]
Dear @lawremi 

I agree with the philosophy that it is a good practice to build upon existing Bioconductor classes. However, I feel that the SummarizedExperiment class would rather be appropriate for storing raw- and metadata.
The classes defined in the stageR package in essence store p-values, which depend on a model etc. Therefore, I think that extending SummarizedExperiment to contain model-based results may be somewhat confusing, and potentially dangerous.
Also, the object dimensions are different for the analysis of DGE experiments with complex designs (say testing 3 hypotheses for all genes, dimension Gx3 with G number of genes) as compared to transcript-level analysis of the results, where the number of p-values per gene differs between genes due to a different number of transcripts for every gene. However, it is this nesting of p-values within a gene that is essential for the method and this has to be maintained, which is nicely done by the stageR and stageRTx classes.

Do let me know if you feel otherwise, or have any specific suggestions for SummarizedExperiment extensions.

Best,
Koen

**Comment by lawremi** [comment]
I don't think it matters whether data are raw or the result of a model fit. It's just data, and it's nice to have data stored along with the metadata on features and samples, even if the samples might correspond to something like a model contrast. They're just different stages in the pipeline.

**Comment by statOmics** [comment]
Thank you for the suggestion, @lawremi .
I will await the review from @LiNk-NY and get going from there.

**Comment by LiNk-NY** [comment]
Hi @statOmics,
Thank you for submitting to Bioconductor.
Please find your review below. 

If you have any questions, please let me know. 
Best regards,
Marcel

----

# stageR #432

I agree with Michael @lawremi, I don't see why you wouldn't be able to
extend `SummarizedExperiment` for the `stageR` class. You would benefit
from the already established structure.

## DESCRIPTION

* Please indicate the appropriate packages in the
imports and suggests field. If you require packages
for the vignette examples but not for the code
in the package, put them under the suggests field.
If you are using external functions for the code in your package
use the imports field. If you are building on top of other
functions outside of your package, indicate them in the
depends field. 

## NAMESPACE

* It seems like your accessor functions don't need to be prepended
with 'get'. It is a matter of preference but my suggestion would be
to remove 'get' and leave just the camelCase nouns. 

## Formatting

* Please make sure you're formatting your code to not exceed 80 column
widths. This makes it harder to read and to maintain.

## R

* Please follow the packages guidelines as listed in Bioconductor.org
* Avoid using, `1:length(x)` sequence generation, the `=` for setting
variables, sapply for looping.
* Don't repeat yourself, create helper functions when you need to run
similar operations under different 'methods', e.g. `.stageWiseTest`
* Use accessor functions to extract data within your class,
avoid using `@`
* Avoid using numeric indices for accessing data vectors, use more robust
names for extracting columns, e.g., `df[, "var1"]` vs. `df[, 1]`
* Define methods for your class so that you don't need to check for
S4 class membership because it will only dispatch to that class
(`.getResults`)
* You don't need to create an off function for your show method, just
include the function as part of the `setMethod` call

## vignettes

* Please include your dataset generation script under `inst/extdata`,
no need to include it in R (`constructDTUDataset.R`)
* Load data appropriately using `system.file` in your example.
* Avoid downloading data in the vignette
* Don't install packages programatically in the vignette, just provide
the library calls. Users will donwload them on their own.
* Use `require` to check availability of packages rather than
`installed.packages()`
* Use meaningful variable names in the vignette, L, v, and d are not very
illustrative.

**Comment by LiNk-NY** [comment]
Hi Koen Van den Berge and @statOmics, 
Please respond to the review items and whether those have been addressed or not. 

Thank you, 
Marcel

**Comment by LiNk-NY** [comment]
Hi Koen Van den Verge and @statOmics, 
As a reminder, please respond to the initial review otherwise, I will have to close the issue.
Best regards,
Marcel

**Comment by statOmics** [comment]
Hi @LiNk-NY 
Apologies for our delay in responding. We are working on changing the package and hope to give a detailed response soon.
Best,
Koen Van den Berge

**Comment by koenvandenberge** [comment]
Dear @LiNk-NY 

First of all, our apologies for our delay in taking so long.
Many thanks for your comprehensive review of our package and your welcome suggestions.

We have now adapted the package, but I am unsure on the origin of the ERROR label, since it is not documented in the build output. Are you able to provide more details on this?

Please find below a list of changes:

The stageR and stageRTx classes now extend the SummarizedExperiment class.

DESCRIPTION
- Imports and suggests fields have been modified to conform suggestions.

NAMESPACE
- accessor functions are still prepended with `get’.

R
- I have moved repetitive elements in .stageWiseTest higher up in the function to avoid repetition.
- I only use @ subsetting when defining accessor functions.
- I have eliminated 1:length(x) loops. I have avoided sapply loops where possible, but have kept sapply at relevant places, i.e. in adjustment types “dte” and “dtu” in . stageWiseTest. Here, we loop over the significantGenes character vector and the sapply is easily readable.
- I have avoided using numeric indices when selecting columns from data frames, but have kept this when using the tx2gene object, since the only requirement for users would be to have the gene names in column 1 and transcript names in column 2 as specified in the help files.
- the show functions are now incorporated in the setMethod call for the stageR and stageRTx class.

VIGNETTE
- moved constructDTUDataset to inst/extdata
- I appropriately load data objects from within package using data(), which also avoids downloading data in vignette
- relevant variable names are used in the vignette

**Comment by LiNk-NY** [comment]
Hi Koen, @koenvandenberge 
I have requested another build of the package.
Please stay tuned for the build report. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Koen, @koenvandenberge @statOmics 
Thank you for making those changes. 
Your package has been conditionally accepted.
Please ensure that the formating of the code does not pass 80 column widths,
as soon as possible to be able to make it into release.

Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by koenvandenberge** [comment]
Dear @LiNk-NY 

Thank you for accepting the package.
I have updated the package to respect the 80 column margin width, and have bumped the version number.

Thanks for the useful comments!

Best,
Koen

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/statOmics.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"stageR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/stageR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
