### ISSUE TITLE
apeglm

### ISSUE THREAD

**Issue by azhu513** [Bioconductor/Contributions#446]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/azhu513/apeglm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Carefully consider how your package can interoperate more effectively with Bioconductor packages, in particular through re-use of [common classes][1] for input and (possibly) output.

[1]: http://bioconductor.org/developers/how-to/commonImportsAndClasses/

**Comment by mikelove** [comment]
@mtmorgan we expect the functions here will mostly be run as a routine within a DESeq2 function.

Still, we can easily change so `apeglm` works with *SummarizedExperiment* input with counts as assay and then output a *GRanges* (the primary output of the main function is log fold changes). Would that be better?

**Comment by mtmorgan** [comment]
yes, better to work with SE and output GRanges.

**Comment by azhu513** [comment]
Hi, 
When I run BiocCheck locally I didn't have this error. I have subscribed to the bioc-devel mailing list as well.
Can I know how to fix it then please?

**Comment by dvantwisk** [comment]
I am not seeing the maintainer's email, `anqizhu@live.unc.edu`, on the list of mailing list subscribers.  The mailing list should have sent you an email asking you to verify your subscription, did you confirm your subscription with this email?

**Comment by azhu513** [comment]
I just found this confirmation email in my spam folder. Just confirmed.

**Comment by dvantwisk** [comment]
Great!  We'll start reviewing your package now!

**Comment by dvantwisk** [comment]
DESCRIPTION:
- [CONSIDER] LICENSE: specify a specific GPL license version.

NAMESPACE:
- Looks fine!

R/apelgm.R
- L65: [CONSIDER] Create lightweight S4 object for output to `apeglm()` with accessors
instead of outputting a list of matrices.
- L140: [CONSIDER] Consider using `match.arg()` to improve style of function declaration.
For example, the parameter `interval.type` can have three values: "laplace",
"HPD", or "credible".  The parameter in the function declaration can be written 
as `interval.type=c('laplace', 'HPD', 'credible')`.  The value that the chooser 
uses can be obtained with `interval.type <- match.arg(interval.type)`.  The
first value (in this case `laplace`) is the default argument.  Using this method
makes it clear to users what the allowed inputs to a function are and may also
make error catching easier.

R/bbEstDisp.R
- Looks fine!

R/grid.R
- L342-350, L363-371: [CONSIDER] These two for-loops are essentially the same.
Consider making a function and invoking it in these two locations instead of
repeating blocks of code.

R/logLikes.R
- Looks fine!

R/priorVar.R
- Looks fine!

R/svalue.R
- L27: [CONSIDER] use `seq_along()` here.

test
- [CONSIDER] add tests to your package using the `testthat` package.

vignettes
- Looks fine!

**Comment by azhu513** [comment]
Hi Daniel, Just wondering if everything is ok with the package? Should we do something now? Thanks!

**Comment by dvantwisk** [comment]
Hi,

We were just waiting for you to finish your changes.  I assume you have addressed the issues we put forward in our review, so we can have another look at your package now.  Is this correct?

**Comment by azhu513** [comment]
Yes, we addressed all except the we did not create an S4 class output for the package, as this package will be called via DESeq2's `lfcShrink` function which has it's own input and output classes. Thus we prefer to just have list output of the apeglm() function.

**Comment by dvantwisk** [comment]
Hello,
We've reviewed the package again. The only remaining issue is that the tests that you added in `tests/testthat` directory do not contain any tests.  Tests contain the key functions `expect_*()` (for example, `expect_true()` would be a test).  After adding tests, they can be run with devtools::test() in your package directory.  Here is a resource on writing testthat tests: https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf

**Comment by azhu513** [comment]
hi @dvantwisk, we have added tests, can you please review?

**Comment by dvantwisk** [comment]
Everything looks good now!

**Comment by azhu513** [comment]
Hi, 
Just wondering if this is hosted on Bioconductor yet? I never got the information about the Bioconductor git repo. I'd like to make a change, should i just push to my Github repo please?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.
To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (tithub.com/<username>.keys is not empty), then no further steps are required. Otherwise, do the following:
1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]
[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
See further instructions at
https://bioconductor.org/developers/how-to/git/
for working with this repository. See especially
https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/
to keep your GitHub and Bioconductor repositories in sync.
Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at
https://bioconductor.org/checkResults/
(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will be created at
https://bioconductor.org/packages/YOUR_PACKAGE_NAME
If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
