### ISSUE TITLE
ChIPanalyser

### ISSUE THREAD

**Issue by patrickCNMartin** [Bioconductor/Contributions#452]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/patrickCNMartin/ChIPanalyser

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Please correct any ERRORs and WARNINGS in the above build report.  Also, the package should take less than 5 minutes to run R CMD check and it currently takes >10min.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Some questions and comments below: 

Working through the Vignette:
- [ ] There are some typos in your vignette (ie. in the intro packageresides, in step 4 there is an extra SitesAboveThreshold) please review for accuracy. 
- [ ] I really like the quick example utilizing a BSgenome 
- [ ] PFM is a path to file yet everything else is an object. It seems from the full guide that this can be an object (matrix) too?  Is this correct? 
- [ ] geneRef should be a GRangesList.  It says it is but the output of code is a regular list. 
- [ ] eveLocusChip as this is a list I assume in can be longer than length 1 and have multiple values?  Is there a reason this is not a NumericList?
- [ ] When running `chipProfile` in step 5 the function produces warnings that should be corrected in the code perhaps with an `any() or all()`
```
> chipProfile <- computeChipProfile(setSequence = eveLocus,
+     occupancy = Occupancy,occupancyProfileParameters = OPP)
Computing ChIP Profile 

Warning messages:
1: In if (method == "exact") { :
  the condition has length > 1 and only the first element will be used
2: In if (method == "truncated_kernel") { :
  the condition has length > 1 and only the first element will be used
3: In if (method == "moving_kernel") { :
  the condition has length > 1 and only the first element will be used

```
- [ ] It says that chipProfile is a GRangesList but the output produced is a regular list - update to GRangesList object. 
- [ ] if keeping a list - is there an accessor method to just extract the GRange object from the list? The list structure seems odd and difficult for the user to navigate to retrieve this information. 

Data: 
- [ ] You mentioned your data is from Berkeley Drosophila Transcription Network Project (bdtnp.lbl.gov) - is there any special licensing for that site? Is the data freely available for use and redistribute? 

R code: 
- [ ] Write seq_len(n) or seq_along(x) rather than 1:n or 1:length(x). This protectsagainst the case when n or length(x) is 0 (which often occurs as an unexpected ‘edge case’ in real code) or negative.
- [ ] The use of GRanges (and potentially GRangeList) is very good. Is it at all possible to construct other common Bioconductor classes used for other packages for chipseq like a RangedSummarizedExperiment or edgeR::DGEList so the data produced could be used in other packages? 

We appreciate your submission. Please update the code and respond back here with what has been updated and further clarifications on questions when you are ready for another review. 

Cheers, 
Lori

**Comment by patrickCNMartin** [comment]
Dear Lori,

I have read your comments and tried to address as many points as possible. 

The vignette:

- I hope to have found all typos in the vignette.

- You are right in saying that PFM is a path to file as opposed to other data objects. This was to demonstrate that ChIPanalyser can handle and parse PFM files. It is not necessary to have a PFM matrix within R. However,  to make things clear, I explicitly explain this choice and the different possibilities in the vignette. I realised that I was not as clear as I had hoped.

- geneRef should indeed be a list and not a GRangesList

-eveLocusChip only contains one numeric vector for this example. I didn't want to make the Rda object to heavy. However, it is possible to add as many numeric vectors to this list as one would wish. As long as they are named and represent the Loci of interest. When it comes to NumericList, I must admit that I did not know they existed but for the time being I'm not sure it would be beneficial to migrate towards NumericList as opposed to simple lists.

- I have addressed the warning issues with computeChipProfile

- The output of computeChipProfile should indeed be a list. I have modified the vignette accordingly.

-You are absolutely right in saying that the list can be difficult to navigate. In order to overcome this issue, I wrote an accessor/search function for this list (also works for "genomicProfileParameters" objects). The function is called searchSites and enables extraction and searching for specific Loci and combination of parameters. Even though the structure of this list may be unconventional, this function makes extraction and sub-setting extremely easy.

The Data:
- Berkeley Drosophila Transcription Network Project (bdtnp.lbl.gov) is ,as far as I am aware of free to use and distribute. There is no licensing required to access their data.

R code:
- I have followed your advice and changed 1:n and 1:length(x) to seq_len(n) and seq_along(x).
- In its current format, ChIPanalyser is a full workable pipeline and it not directly compatible with other formats such as RangedSummarizedExperiment or edgeR::DGEList. However, the next version (one that I will be developing in the next few months) will contain pre and post  data processing functions.  Adding compatibility to other packages could be an excellent addition to the package. 


Thank you for your comments.

Patrick

**Comment by lshep** [comment]
Thank you for making the suggested updates.  Some additional: 

**General Comments:**
* Please keep in mind things like NumericList, CharacterList, etc for future. 
* Is there a reason you didn't use a GRangesList? 
* Please ensure that the pre and post processing functions will be compatible withother Bioconductor standard object;  It will make your package much more accessible to the broader Biocondcutor community.  Generally we have moved forward with requiring that the package workflows work with other Bioconductor standard object but as it is a standalone workflow, I won't push this.  But... I really, strongly encourage you to develop those other pre/post functions with mutual compatibility. 

**R/CODE:** 
- [ ] The searchSite is a good added feature.  When running in your vignette: 
```
searchSites(chipProfile, ScalingFactor=c(1.5,2.5), BoundMolecules=c(1000,1500) ,Locus=c("eve","odd"))

Warning message:
In if (Locus == "all") { :
  the condition has length > 1 and only the first element will be used
```
Please fix this warning with an any or all, which ever appropriate

**Comment by patrickCNMartin** [comment]
Dear Lori,

- I will keep those elements in mind and try to use them in the next version.
- I preferred using a list as they offer a bit more flexibility then a GRangesList. The way I designed the code flow made the use of GRangesList a bit more tricky. 
- It is my wish to make ChIPanalyser as universal as possible and compatible with other Bioconductor packages. Pre-Processing will mainly handle ChIP-seq data (going from wig, bigwig, bed, big Bed etc to a list type object as is it required in this package. ) and DNA Accessibility data. All other additional functions will be wrapper functions in order to parse data from other packages or to parse data from ChIPanalyser to other packages. I am currently testing the package on various formats of data in order to include as many variants as possible. 
- I have addressed the warning in searchSites.

Once again, thank you for your feedback and comments 

Patrick

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (tithub.com/<username>.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"YOUR_PACKAGE_NAME\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
