### ISSUE TITLE
PROPS

### ISSUE THREAD

**Issue by lhan22** [Bioconductor/Contributions#458]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lhan22/PROPS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by dvantwisk** [comment]
Hello,
We've review your package!  Please address the following issues and message us back when you are ready for us to continue the review.

DESCRIPTION
- [REQUIRED] Description too short.

NAMESPACE

R/PROPS-internal.R
- [REQUIRED] Remove random seed.  Do not modify random number generator.

R/props.R
- [REQUIRED] Support `ExpressionSet` from the Biobase package as input.
https://bioconductor.org/packages/3.3/bioc/vignettes/Biobase/inst/doc/ExpressionSetIntroduction.pdf
- [REQUIRED] "ERROR:" inside of `stop()` is redundant.

man
- [REQUIRED] Descriptions for data files are too short.  Include more
information such as the source of the data and the format of the data.

tests
- [Consider] Add tests to your package using the `testthat` package.

data
- [CONSIDER] `example_data.rda` and `example_healthy.rda` data files are too
large.  Try to reduce the size of these files.

**Comment by dvantwisk** [comment]
Hello,
I see that you've made some changes to your code since we gave you our initial review.  Shall we proceed with reviewing your package?

**Comment by lhan22** [comment]
Yes please. Thanks.

Lichy

**Comment by dvantwisk** [comment]
Sorry for the delay!  We had to make some changes to our documentation before we could get back to your package.  It looks like you've made all the changes we suggested in our review.  We did find, however, that your `data` directory contains large files (namely `example_data.rda` and `example_healthy.rda`).  We ask that you do either one of four things:

- Separate out these large files and include them in an ExperimentalData package.  This package would effectively just include the data files, while PROPS would import and access the data from the package.  This new package would have to be resubmitted.
-  Submit the data to `ExperimentHub` as described [here](https://github.com/Bioconductor/ExperimentHub/blob/master/vignettes/CreateAnExperimentHubPackage.Rmd).
- Consider reducing the size of your example data.  Generally, we would like packages to be below 4MB, so the size of these data files would have to be reduced accordingly.
- Lastly, if this data (or similar data) is present in another package, you could just import this data from that package and use that data.

**Comment by dvantwisk** [comment]
Hello,
Are you able to address the above issue?

**Comment by lhan22** [comment]
Hello,

Yes, I am working on addressing this, and will update the package in a few days. I plan on either reducing the data size, or separating out the larger files into a separate package. Thanks.

**Comment by lhan22** [comment]
Hello, 

I've decreased the size of the data and updated the package. When I build the package, the .tar.gz file is now 3.8MB, down from what was previously ~25MB. Thanks.

**Comment by dvantwisk** [comment]
Looks good!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lhan22.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"PROPS\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PROPS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
