### ISSUE TITLE
CancerSubtypes

### ISSUE THREAD

**Issue by xtsvm** [Bioconductor/Contributions#46]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xtsvm/CancerSubtypes

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by xtsvm** [comment]
I want to start another build again. I think this time the errors should be fixed.

**Comment by xtsvm** [comment]
Hi @vobencha,
How long does the review process usually take and what should I do for next? Thanks!
Best regards,
Taosheng

**Comment by vobencha** [comment]
Hi,
It looks like you have a clean build report so no more to do on your end. I'll have a full review for you by the end of this week (Fri 8).
Valerie

**Comment by vobencha** [comment]
Hi,

I've done a first review of CancerSubtypes. Please see comments / suggestions below.

1) commented out code in man pages

These should be evaluated or removed:

~/Downloads/CancerSubtypes/man >grep "#" *
drawHeatmap.Rd:#drawHeatmap(GeneExp,Title="GBM Gene Expression")
drawHeatmap.Rd:#drawHeatmap(GeneExp,group,scale="max_min",Title="GBM Gene Expression")
drawHeatmap.Rd:#drawHeatmap(miRNAExp,group,silhouette=silhouette,scale="max_min",Title="GBM miRNA Expression")
drawHeatmap.Rd:#drawHeatmap(GeneExp,group,silhouette=silhouette,scale="max_min",
drawHeatmap.Rd:#            color="-RdYlBu",Title="GBM Gene Expression")
ExecuteCC.Rd:#data(GeneExp)
ExecuteCC.Rd:#data(miRNAExp)
ExecuteCC.Rd:#GBM=list(GeneExp=GeneExp,miRNAExp=miRNAExp)
ExecuteCC.Rd:#result=ExecuteCC(clusterNum=3,d=GBM,maxK=5,clusterAlg="hc",distance="pearson",title="GBM")
ExecuteCC.Rd:#result$group
sigclustTest.Rd:#sigclust1=sigclustTest(GeneExp,group, nsim=1000, nrep=1, icovest=3)
sigclustTest.Rd:#sigclust2=sigclustTest(GeneExp,group, nsim=1000, nrep=1, icovest=1)
sigclustTest.Rd:#sigclust3=sigclustTest(miRNAExp,group, nsim=1000, nrep=1, icovest=1)

2) sihouette2()

Please rename this function, maybe to something like sihouette_SimilarityMatrix(). The behavior is too similar to sihouette() from cluster. It is confusing (and error prone) to have statements like these in a man page:

"Note that: the function "Silhouette()" in R package "cluster" is based on dissimilarity matrix. We rewrite this function to solve the
computation based on the similarity matrix. The result of our function is compatible to the function "Silhouette()" in R package "cluster".
..."

###If use the silhouette() in R package "cluter", the result
###is meaningless because this is a similarity matrix.
sil1=silhouette(result$group, result$distanceMatrix)
plot(sil1)  ##wrong result

3) vignette

i) Please use real data in the vignette (several examples are simulated). The description mentions this package is useful for TCGA data - there are many TCGA data sets to choose from in the experimental data packages, type 'TCGA' in the search field:

  http://www.bioconductor.org/packages/devel/BiocViews.html#___ExperimentData

ii) Clarify which packages you are building on and what methods you are "integrating". I would suggest listing the methods used (e.g., name of clustering function, name of package) in the 'Overview of the Package' section. I see they are listed in 'Data Processing' and 'Clustering methods ....' but they get rather lost. The vignette is long and it's difficult to dig out the relevant information.

iii) plots

There are 28 plots in the vignette none of which are explained in detail. It isn't clear to me that the plots really add much information to the vigntte and explaination of the analysis. I would recommend reducing the number of plots and explaining what they mean. What are they showing? How are these useful to the user QCing their data?

iv) 'References' section appears empty in the html version.

v) Bullet in 'Overview' section:

"Unified input and output interface to perform all clustering methods."

What is the interface and how is it unified? Do you mean a subset of common functions? Are the input and output always of the same class? Do all input functions have the same arguments?

vi) Bullet in 'Overview' section:

"Provides a framework to identify cancer subtypes and result validation."

What do you mean by framework? Do you mean workflow? Framework (to me) implies classes or data structures. Is there a common data structure?

4) parallel

Some of the functions are very core-intensive. The number of workers spawned max out the available cores. It should be stated in the vignette that this package depends on NMF which uses foreach and will spawn the maximum number of workers available.

5) Format of author and maintainer field

There should not be a comma between the first and last name. It looks like Xu Taosheng is one name so there should not be a comma after Xu.

Author: Xu, Taosheng<taosheng.x@gmail.com>, Thuc Le<Thuc.Le@unisa.edu.au>
Maintainer: Xu, Taosheng<taosheng.x@gmail.com>

Valerie

**Comment by xtsvm** [comment]
Hi @vobencha ,
I encounter a problem.
You advised me to use some Bioconductor ExperimentData package for my package's vignette. But it comes out an error when my package is built in moscato1 server. 
 The error information is “Error: processing vignette 'CancerSubtypes-vignette.Rmd' failed with diagnostics:there is no package called 'RTCGA.mRNA'   Execution halted”. 
Is this a problem in the moscato1 server? Could you please help to check it?

Best regards,
Taosheng

**Comment by xtsvm** [comment]
I have modified the package as the reviewer suggested. Please let me know if I need to do anything else. Thank you!

**Comment by vobencha** [comment]
Thanks for making the changes. I'm marking the package as approved. You'll get an email from Martin in the next few days with svn instructions and next steps.

Valerie

**Comment by xtsvm** [comment]
Hello,
I didn't get email from Martin about svn instructions these days.  Is it some problems about it?
Best regards,
Taosheng

**Comment by vobencha** [comment]
I think he's just a little behind ... hopefully will get to it this week.
Valerie
