### ISSUE TITLE
SPONGE package for inferring genome-wide competing endogenous RNA networks 

### ISSUE THREAD

**Issue by mlist** [Bioconductor/Contributions#461]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mlist/SPONGE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
I'll provide a more complete review in a few days.

Please modify your package so that it interacts smoothly with the Bioconductor ecosystem, in particular accepting Biobase::ExpressionSet as a resource for gene expression values.

Carefully consider the number of packages listed in your DESCRIPTION file and used in your code -- trim only marginally useful functionality so that the dependencies are reduces and your package less susceptible to breakage when upstream changes occur.

Consider using BiocParallel so that Bioconductor users have a common parallel experience; see it's vignette for developer guidelines.

**Comment by mlist** [comment]
Thanks for the quick response. I'll add support for Biobase:ExpressionSet right away and I will also see if I can remove a few packages from DESCRIPTION. 

With respect to BiocParallel: I was looking into this. I use foreach for parallelization and mention in the vignette that this is compatible with BiocParallel as long as DoparParam is used. Should I handle this differently?

**Comment by mtmorgan** [comment]
Please modify your package in response to these and the original comments, and provide a brief response comment when ready for the review to continue.

General

- With respect to BiocParallel -- I personally find the extensive use of `foreach()` and `data.table()` makes your code difficult to parse, but I realize that this is my limitation. 

- I strongly think that the end user should not be exposed to data.table (because of the awkward syntax and pass-by-reference semantics).

- The use of `foreach()` with `%do%` seems really (to me) to just obscure basic iteration; is it really adding value?

DESCRIPTION / NAMESPACE
 
- Please simplify the dependencies

 
vignettes

- please remove build products (SPONGE.html) from your master branch

- Is it neccessary to present verbose loggin information? This will not be useful to the individual trying to follow your package.

R

- generally the code seems to be well structured and appropriate.

- fn_simulation.R:213 I doubt that the early exit of

    ```
    i <- 1
    within_constraints <- TRUE
    while(i < length(u2.scaled)){
        if((u2.scaled[i] > constraints[i]) ||
           (u2.scaled[i] < -constraints[i])) {
            within_constraints <- FALSE
            break
        }
        i <- i+1
    }
    ```
    
  gains any speed relative to (did I get the `abs()` right?)

    ```
    within_constraints <- any(abs(u2.scaled) > constraints)
    ```
    
- `1:n` specification of domains for iteration are problematic when `n == 0`; use `seq_len(n)` or `seq_along()` instead. I don't know how this plays with `foreach()`.

NEWS

- hmm, looks like a place-holder; write and maintain so parsable by `tools::news()` or omit.

tests

- nice to see a stab at tests, but really these need to be much more extnesive and focused on 'units' of computation, rather than at the integrative level of `sponge()`, etc.

**Comment by mlist** [comment]
General

> Please modify your package so that it interacts smoothly with the Bioconductor ecosystem, in particular accepting Biobase::ExpressionSet as a resource for gene expression values.

All functions now accept ExpressionSet as gene or miRNA expression data.

> With respect to BiocParallel -- I personally find the extensive use of foreach() and data.table() makes your code difficult to parse, but I realize that this is my limitation.

We deliberately chose to work with foreach and data.table for performance reasons and would like to stick to it, also considering that the use of foreach is officially supported by BiocParallel. We explain in the vignette how to register the parallel backend of foreach with BiocParallel.

> I strongly think that the end user should not be exposed to data.table (because of the awkward syntax and pass-by-reference semantics).

The new default behaviour of sponge is to return a data frame but we keep the option to return a data table via a parameter return_as_dt.

> The use of foreach() with %do% seems really (to me) to just obscure basic iteration; is it really adding value?

We see two advantages: (i) consistency of looping which allows you to switch to parallel execution where needed; (ii) foreach is highly configurable and allows specifying a function for combining results, for instance.

DESCRIPTION / NAMESPACE

> Please simplify the dependencies

We have removed some dependencies and turned others into suggestions.

vignettes

> please remove build products (SPONGE.html) from your master branch

Done.

> Is it neccessary to present verbose loggin information? This will not be useful to the individual trying to follow your package.

We have changed the default logging level to "ERROR" to avoid verbose logging information.

R

> generally the code seems to be well structured and appropriate.

Thank you.

> fn_simulation.R:213 I doubt that the early exit of

```
i <- 1
within_constraints <- TRUE
while(i < length(u2.scaled)){
    if((u2.scaled[i] > constraints[i]) ||
       (u2.scaled[i] < -constraints[i])) {
        within_constraints <- FALSE
        break
    }
    i <- i+1
}
```
> gains any speed relative to (did I get the abs() right?)

`within_constraints <- any(abs(u2.scaled) > constraints)`

We fully agree and have changed the code accordingly. 

> 1:n specification of domains for iteration are problematic when n == 0; use seq_len(n) or seq_along() instead. I don't know how this plays with foreach().

Good point. We have changed this as well. 

NEWS

> hmm, looks like a place-holder; write and maintain so parsable by tools::news() or omit.
tests

tools::checkNEWS seems to be defunct. We have tried to follow the example of Biobase for changing the NEWS file. 

> nice to see a stab at tests, but really these need to be much more extnesive and focused on 'units' of computation, rather than at the integrative level of sponge(), etc.

We agree and have implemented a full suite of unit tests now. 

Looking forward to your feedback on the improved version.

**Comment by mtmorgan** [comment]
Thanks these changes look great.

**Comment by mtmorgan** [comment]
See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.
