### ISSUE TITLE
methyvim

### ISSUE THREAD

**Issue by nhejazi** [Bioconductor/Contributions#464]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nhejazi/methyvimData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nhejazi** [comment]
AdditionalPackage: https://github.com/nhejazi/methyvim

**Comment by nhejazi** [comment]
@mtmorgan @vobencha -- It seems that the repo corresponding to the analysis package is already being tracked by the issue for the first submission attempt (though #463 is now closed). What is the best way to continue with the submission process?

**Comment by vobencha** [comment]
Please address this issue raised by the single package builder:
* Checking exported objects have runnable examples...
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      fdr_msa.Rd, methytmle-class.Rd, methyvim.Rd

Once the package passes with no errors I'll do a full review.
Valerie

**Comment by vobencha** [comment]
Checking in. Are you planning to submit a new version?
Valerie

**Comment by nhejazi** [comment]
Thanks for checking in. Yes -- I will be submitting a new version with examples for the few exported objects that are mentioned above. I plan to have this done by the end of the week and will bump the package version to trigger a new build at that point.

**Comment by nhejazi** [comment]
@vobencha, the error you noted has now been resolved and I believe we can proceed with a full review of the package at your convenience.

**Comment by nhejazi** [comment]
@vobencha -- Thanks for your input. I've made the requested changes on both packages (in the case of the data package, I've tried to provide as much detail as we feel comfortable with and added a few examples using the `minfiData` package in case it might help the target audience appreciate that the package is usable with 450K or 850K data).

I'm working out an error related to the tests failing on Bioconductor's build systems, but I cannot replicate the build locally or via Travis/Appveyor -- perhaps you could advise on how to proceed here? Thanks in advance for the help.

**Comment by nhejazi** [comment]
Thanks for confirming that you're able to reproduce the error. Here's relevant parts of the output produced (abbreviated for convenience) when I run `R CMD check` on my macOS machine with R v3.4.1:
```
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... WARNING
Package vignette without corresponding PDF/HTML:
   ‘using_methyvim.Rmd’

* checking running R code from vignettes ...
   ‘using_methyvim.Rmd’ using ‘UTF-8’ ... OK
```

Additionally, [here](https://travis-ci.org/nhejazi/methyvim/jobs/280169863) is a log from Travis-CI confirming the package builds/checks successfully on R-release with Ubuntu Trusty, and, similarly, [here](https://ci.appveyor.com/project/nhejazi/methyvim) is a log from Appveyor-CI, confirming the same for Windows.

I agree completely with you about the number of packages being loaded -- I wasn't aware of this. Further, many of them appear to be dependencies for packages used directly but not things that `methyvim` uses directly. Any advice on reducing this would be very welcome when we get to that stage of the review process.

**Comment by nhejazi** [comment]
In the interest of facilitating the package review process, I've (temporarily) removed the broken unit test -- in retrospect, this was a poorly thought-out test anyhow. I've also implemented a few minor changes to ensure that the package passes `BiocCheck` without any warnings or errors. Perhaps we could begin a full review if you have time this week @vobencha?

**Comment by vobencha** [comment]
I will review the package today.
Valerie

**Comment by nhejazi** [comment]
Thanks very much, Valerie -- looking forward to your review. At this point, I've worked out all errors and warnings from the builds. The lingering error is something that I cannot quite pin down on the tokay1 machine. It might something obvious to you, but I'm missing it.

**Comment by vobencha** [comment]
Hi,
* Data Package
  - Nice man page. Please add a small example showing how to load the data and manipulate.
  - Remove LazyData: true

* Software Package
  - Remove LazyData: true
  - All man pages need running examples or explain why you think you can't provide one.
  - Vignette is well written with good examples.

Valerie

**Comment by nhejazi** [comment]
Hi Valerie ---

Thanks very much for your review. I have made nearly all of the requested changes in the most recent PRs to the `methyvimData` and `methyvim` repos. In particular each of the following have been addressed:

* Data Package
   -[x] Nice man page. Please add a small example showing how to load the data and manipulate.
   -[x] Remove LazyData: true

* Software Package
  -[x] Remove LazyData: true
  -[ ] All man pages need running examples or explain why you think you can't provide one.

**Comment by vobencha** [comment]
Hi Nima,
If those functions are just used internally then you probably don't need a man page. Is there a reason why you feel you need one? 

If you feel strongly about keeping the man pages I would mark them as 'Internal Use Only' and be clear about the use / intent.
Valerie

**Comment by vobencha** [comment]
Yes, keeping the man pages and marking them as 'Internal' sounds good.
Valerie

**Comment by vobencha** [comment]
Did you implement the change in the man pages? Once that's done I can go ahead and approve the package.

**Comment by nhejazi** [comment]
Thanks for checking in. As of the latest build, I've added the text "INTERNAL USE ONLY" to the main description for each of those functions; moreover, I've also marked them with `@keywords internal` in their Roxygen documentation, so as to suppress the functions appearing in the manual and index but still preserve their help pages. This seemed like a good compromise of what we had discussed.

**Comment by vobencha** [comment]
Looks good. Thanks for making the changes - package is approved.
Valerie

**Comment by nhejazi** [comment]
Great to hear. @vobencha -- thanks very much for the review!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nhejazi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"methyvimData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methyvimData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nhejazi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"methyvim\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methyvim

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
