### ISSUE TITLE
anota2seq

### ISSUE THREAD

**Issue by ChrOertlin** [Bioconductor/Contributions#472]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ChrOertlin/anota2seq/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hpages** [comment]
Hi Christian,

Thanks for submitting the anota2seq package!

Please use `BiocStyle::latex()` instead of `BiocStyle::latex2()` in your vignette. The latter is deprecated. Using the former will also make the current `R CMD build` error (happening at the end of vignette creation) go away. After you make that change please don't forget to bump the version of the package in order to trigger a new build/check.

Thanks,
H.

**Comment by hpages** [comment]
Hi Christian,

anota2seq is in good shape. It's clear that a lot of work has been put in the package and in particular in its documentation. The vignette is excellent. I only have a few minor issues to report, all of them cosmetic. See below.

Regards,
H.

1. All the arguments in your function have default values, even mandatory arguments for which the default value is set to `NULL`. For example:
```
    > args(anota2seq.get.covariates)
    function (object = NULL) 

    > args(anota2seqPlotGenes)
    function (object = NULL, selContrast = NULL, analysis = NULL, 
        geneNames = NULL, plotToFile = TRUE, fileName = NULL) 

    > args(anota2seqDataSetFromSE)
    function (se = NULL, assayNum = 1, dataType = NULL, normalize = FALSE, 
      transformation = "TMM-log2", filterZeroGenes = FALSE, varCutOff = NULL)
``` 
This is not a good design. The 1st argument for all these functions is of course mandatory and it wouldn't make sense to set it to `NULL`. Best practice is to use default argument values only for optional arguments. Mandatory arguments don't need and shouldn't have a default value.

2. Please adhere to Bioconductor naming style for your classes and functions:
  - Names of S4 classes should start with a capital letter e.g. `Anota2seqDataSet` instead of `anota2seqDataSet`.
  - Don't use dot-separated names like `anota2seq.get.output()` for functions. Bioconductor recommended naming style for functions is `camelCase` like you did for other functions (e.g. `anota2seqPlotGenes()`). But more importantly than the particular style you choose, pick a style and stick to it. Don't mix styles.
  - It's a good idea to use a different naming style for your datasets e.g. underscore-separated names (`anota2seq_data_T`, `anota2seq_data_P`, and `anota2seq_pheno_vec`). This avoids potential confusion.

3. According to their man page, the `anota2seqDataT` and `anota2seqDataP` matrices have 10736 rows. However, it seems that they have in fact 10748 rows.

**Comment by ChrOertlin** [comment]
Hello,

Thank you for the comments, we will update them as soon as possible!

Cheers,
Christian

**Comment by ChrOertlin** [comment]
Hi,

Thank you very much for these constructive comments. We have now submitted a new version of anota2seq (version 0.99.2) which address these remarks (see below). 

Regards,

Christian Oertlin, Julie Lorent and Ola Larsson.

**_Reply to comments:_**

1. All the arguments in your function have default values, even mandatory arguments for which the default value is set to `NULL`. For example: 

```
> args(anota2seq.get.covariates)
    function (object = NULL) 
> args(anota2seqPlotGenes)
    function (object = NULL, selContrast = NULL, analysis = NULL, 
        geneNames = NULL, plotToFile = TRUE, fileName = NULL) 
> args(anota2seqDataSetFromSE)
    function (se = NULL, assayNum = 1, dataType = NULL, normalize = FALSE, 
      transformation = "TMM-log2", filterZeroGenes = FALSE, varCutOff = NULL)
```

This is not a good design. The 1st argument for all these functions is of course mandatory and it wouldn't make sense to set it to NULL. Best practice is to use default argument values only for optional arguments. Mandatory arguments don't need and shouldn't have a default value.

**_Reply: We have modified all functions to remove default values of mandatory arguments. Moreover, we modified the default values of two optional arguments: `filterZeroGenes` in `anota2seqDataSetFromMatrix` and `anota2seqDataSetFromSE` as well as `fileName` in the plot functions (`anota2seqPlotFC`, `anota2seqPlotPvalues` and `anota2seqPlotGenes`). `filterZeroGenes` is now TRUE by default if the user provides raw RNAseq counts and FALSE by default otherwise. The `fileName` parameter was renamed `fileStem` because the contrast number will be added at the end of the provided stem. Its default values are now `"ANOTA2SEQ_FoldchangePlot"`, `"ANOTA2SEQ_pvalue_density"` and `"ANOTA2SEQ_significantGenes_plot"` respectively for functions `anota2seqPlotFC`, `anota2seqPlotPvalues` and `anota2seqPlotGenes`._**

2. Please adhere to Bioconductor naming style for your classes and functions: 
Names of S4 classes should start with a capital letter e.g. `Anota2seqDataSet` instead of `anota2seqDataSet`. 
Don't use dot-separated names like `anota2seq.get.output()` for functions. Bioconductor recommended naming style for functions is `camelCase` like you did for other functions (e.g. `anota2seqPlotGenes()`). But more importantly than the particular style you choose, pick a style and stick to it. Don't mix styles. 
It's a good idea to use a different naming style for your datasets e.g. underscore-separated names (`anota2seq_data_T`, `anota2seq_data_P`, and `anota2seq_pheno_vec`). This avoids potential confusion.

**_Reply: we have renamed all classes, functions (using camelCase naming style) and datasets as suggested._**

3. According to their man page, the `anota2seqDataT` and `anota2seqDataP` matrices have 10736 rows. However, it seems that they have in fact 10748 rows.

**_Reply: Thank you for notifying this mistake, we corrected it._**

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ChrOertlin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"anota2seq\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/anota2seq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
