### ISSUE TITLE
package rhdf5client submission

### ISSUE THREAD

**Issue by sampoll** [Bioconductor/Contributions#474]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sampoll/rhdf5client

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Your package failed to build because the DESCRIPTION file is malformed, specifically the line with the terminating `)` should be a "continuation" line, i.e., indented, and email addresses require closing quotes. Also, the Author: and Maintainer: fields are built from Authors@R, and are not needed (and in this case incorrect). Here's a diff capturing these

```
rhdf5client master$ git diff
diff --git a/DESCRIPTION b/DESCRIPTION
index 3b304d0..cdbd3c7 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -3,16 +3,14 @@ Title: Access HDF5 content from h5serv
 Description: Provides functionality for reading data from h5serv server
  from within R.
 Version: 0.99.0
-Author: Samuela Pollack <spollack@jimmy.harvard.edu>
 Authors@R: c(
   person("Samuela", "Pollack", email = "spollack@jimmy.harvard.edu", role = c("cre", "aut")),
-  person("Shweta", "Gopaulakrishnan", email = "reshg@channing.harvard.edu, role = c("aut")),
-  person("Vincent", "Carey", email = "stvjc@channing.harvard.edu, role = c("aut")),
-)
+  person("Shweta", "Gopaulakrishnan", email = "reshg@channing.harvard.edu", role = c("aut")),
+  person("Vincent", "Carey", email = "stvjc@channing.harvard.edu", role = c("aut"))
+  )
 Suggests: knitr, testthat
 Imports: S4Vectors, httr, rjson
 Depends: R (>= 3.4), methods
-Maintainer: Samuela Pollack <spollack@jimmy.harvard.edu>
 License: Artistic-2.0
 LazyLoad: yes
 BiocViews: infrastructure
```

**Comment by mtmorgan** [comment]
Hi Sam -- please update your package in response to the following comments, and post a brief comment summarizing your response when done.

DESCRIPTION

- Is the Description: a sufficiently accurate and comprehensive description of the package, for instance it seems like the emphasis is on 'read-only' and 'array-like' data.

- Capitalize BiocViews term Infrastructure; are there other terms that will help users?

vignette

- Is the url in the vignette 54.174.163.77 somehow permanent enough for a vignette that will be in a package for years to come? I'm not sure what to suggest instead...

- The vignette ends abruptly, it would be much better to indicate how this data can be incorporated into a standard Bioconductor object or work flow.

R

- Generally good.

- Please adopt a consistent indentation scheme, e.g., the body of the 'show' method at h5serv.R:18 is not indented. Tools to help with this include the formatR and lintr packages. Excessive spacing in the setReplaceMethod at h5serv.R:222 was also a little grating.

- Not really a big issue but it can be clearer to use a single `cat()`, e.g., 

        cat(
            "HDF5 server domain: ", object@serverURL,
            "\n  There are", nrow(object@dsmeta), "groups.",
            "\n  Use groups(), links(), ..., to probe and access metadata.",
            "\n  Use dsmeta() to get information on datasets within groups.",
            "\n  Use [[ [dsname] ]]  to get a reference suitable for [i, j] subsetting.",
            "\n"
        )
        
- h5serv.R:45 when constructing an object it's usually better to process / formulate the arguments and then conclude with a call to `new()`, rather than creating a somehow incomplete object and updating it.

- prefer `vapply()` to `sapply()` (`sapply()` has surprises when it's first argument is of length 0)

- prefer `seq_len()` or `seq_along()` to `1:n` (which has surprises when n == 0).

- h5serv.R:165 avoid direct slot access even in 'internal' code (except of course for accessors, which do not have to be exported)

- h5serv.R:280 `ifelse()` is really meant for vectors, rather than an abbreviation for `if () {} else {}`.

- h5serv.h:299, indx.R:36 no need for explicit `return()`

- the `warning(); print(); stop()` sequence will normally `print()` then `stop()`, then `warning()`, as warnings are buffered until R returns to the top level. An awkward solution might 


    ```
    stop(
        "dataset tags...",
        capture.output(print(.)),
        "please ..."
    )
    ```
    
- I'm generally not a fan of `if () ...` on one line; it seems excessively cramped.

- submatrix.R: a matrix subset by a two-column matrix `midx` treats column 1 as the row index and column 2 as the column index, so I think this slow iterative code can be replaced by a fast vectorized code

    ```
    midx <- cbind(unlist(i), unlist(j))
    dset[midx]
    ```

man

- try to use standard R notation / terminology when describing slots and arguments, e.g., `character(1)` rather than 'character string'.

inst/NEWS

- either provide content that can be parsed by news() (and is kept current, e.g., for release announcements) or remove.

tests

- nice to see unit tests, thanks!

**Comment by mtmorgan** [comment]
@sampoll don't forget to bump the package version to trigger a re-build on the single package builder.

**Comment by sampoll** [comment]
Will definitely bump version number when we're ready for re-build.

**Comment by lawremi** [comment]
Some random comments:
 - The required columns `dsmeta` slot should probably be formalized into their own slots.
 - The `H5S_Source` function defines `targs` but does not use it
 - Is it a good idea to name a class with an underscore? It's unconventional.
 - Maybe `transfermode` should be `transferMode`?
 - I wonder whether H5S_Source could be modeled as a list of H5S_datasets, i.e., it could extend List with an element type of H5S_dataset?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sampoll.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"rhdf5client\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rhdf5client

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
