### ISSUE TITLE
BASiCS (Bayesian Analysis of Single Cell Sequencing data)

### ISSUE THREAD

**Issue by catavallejos** [Bioconductor/Contributions#475]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/catavallejos/BASiCS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by catavallejos** [comment]
I am now registered at the developers mailing list (which is the error mentioned in the build report). Therefore, the error should now be resolved.

**Comment by nturaga** [comment]
Hi @catavallejos 

Please address the issue

```
Quitting from lines 67-81 (BASiCS.Rmd)
Error: processing vignette 'BASiCS.Rmd' failed with diagnostics:
assignment of an object of class "GRangesList" is not valid for slot 'rowRanges' in an object of class "SingleCellExperiment"; is(value, "GenomicRanges_OR_GRangesList") is not TRUE
Execution halted
```

Your package does not build at this moment, because of errors in the vignette.

**Comment by catavallejos** [comment]
Hi @nturaga 

Thanks for the message. The package seems to build well on the computers I tried. However, I realised that the problem seems to be that the package requires the devel version of Bioconductor due to the dependency to the SingleCellExperiment package. 

If I don't use the devel version, I get the same error. 

Is this a problem? 

Cata

**Comment by nturaga** [comment]
Just use the `devel` version. This was actually on my end, and I had some packages which weren't updated. 

I'll review your package soon. It builds fine.

**Comment by catavallejos** [comment]
Great! Thank you for letting me know.

**Comment by nturaga** [comment]
# BASiCS review

## DESCRIPTION

* Ok

## NAMESPACE 

* ok 

## NEWS

* Good job on including a NEWS file.

## vignettes

* Delete cached folder which includes i.e BASiCSIntro_cache cached data from vignette.

* Keep only Rmd, and jpg (or other image formats). Delete html as well.

## src 

* ok.

* Please indent the c++ code in BASiCS_CPPcode.cpp, using a formatter. It is hard to read the code.

## R

* Use `colMedians` from the `matrixStats` package instead of 

```
Phi = apply(Chain@phi, 2, median)
Nu = apply(Chain@nu, 2, median)
```

use `colMedians` thoughout your code as needed. In all apply statements, you can use functions such as `colSums` or `colMedians` (index=1)instead of loops. Try to vectorize your code. (or `rowMedins` or `rowSums` for index=2)

* Use `message` instead of `print` and `cat` (BASiCS_DenoisedRates.R)

```
    print(paste("This calculation requires a loop across the", N,
                "MCMC iterations"))
    print("Please be patient ... ")
    cat("\n")
    print("To see a progress report use PrintProgress = TRUE")
    cat("\n")
```

Do this everywhere. NOTE, `message` does not require the `paste` function. This is a wasted call.

`cat` and `print` go to `stdout`, whereas `message` goes to `stderr`, and stderr is informational for messages. You use cat and print variably throughout your code.


* You can optimize the your code in BASiCS_DenoisedRates.R as, 


original code,

```
    for (m in 1:N) {
        if (PrintProgress) {
            print(paste("Iteration", m, "has been completed."))
        }
        aux1 = assay(Data)[1:q.bio, ] + 1/Chain@delta[m, ]
        aux2 = t(tcrossprod(Chain@phi[m, ] * Chain@nu[m, ],
                            Chain@mu[m, 1:q.bio])) + 1/Chain@delta[m, ]
        rho = rho + aux1/aux2
    }
```

This can be improved by calling functions outside the loop just once, as needed to reduce the number of calls, and improving speed. The print/message statments for every value of N would be very expensive as well.

```
    range = seq_len(qbio)
    phi_nu = Chain@phi * Chain@nu
    assay_range = assay(Data, withDimnames=FALSE)[range, ,drop=FALSE]
    delta_inv = 1/Chain@delta
    chain_mu = Chain@mu[, range, drop=FALSE]
    for (m in seq_len(N)) {
        if (PrintProgress && (m %% 1000 == 0)) {
            message("Iteration ", m, " has been completed.")
        }
        aux1 = assay_range + delta_inv[m, ]
        aux2 = t(tcrossprod(phi_nu[m, ], chain_mu[m, ])) + delta_inv[m, ]
        rho = rho + aux1/aux2
    }
```

Examine your code for similar changes throughout, to optimize.


* Use `seq_along(VarThresholdsGrid)` instead of `for (i in 1:length(VarThresholdsGrid))` in BASiCS_VarThresholdSearchHVG_LVG.R::line55. Similarly in other locations(the list of places below is not exhaustive). Try to use `seq_len` or `seq_along` instead of `1:length(x)` or `1:x`.

```
BASiCS_DetectHVG_LVG.R-
BASiCS_DetectHVG_LVG.R:    GeneIndex = 1:length(Mu)
BASiCS_DetectHVG_LVG.R-    Table = cbind.data.frame(GeneIndex = Genes, GeneNames = GeneNames,
--
--
BASiCS_DetectHVG_LVG.R-    GeneNames = colnames(Chain@mu)
BASiCS_DetectHVG_LVG.R:    GeneIndex = 1:length(Mu)
BASiCS_DetectHVG_LVG.R-    Table = cbind.data.frame(GeneIndex = Genes, GeneNames = GeneNames,
--
--
BASiCS_TestDE.R-    # Update after removing DE genes from Disp table!  Reordering the tables
BASiCS_TestDE.R:    GeneIndex = 1:length(MuBase)
BASiCS_TestDE.R-
--
--
BASiCS_VarThresholdSearchHVG_LVG.R-
BASiCS_VarThresholdSearchHVG_LVG.R:    for (i in 1:length(VarThresholdsGrid)) {
BASiCS_VarThresholdSearchHVG_LVG.R-        VarThreshold = VarThresholdsGrid[i]
--
--
BASiCS_VarThresholdSearchHVG_LVG.R-
BASiCS_VarThresholdSearchHVG_LVG.R:    for (i in 1:length(VarThresholdsGrid)) {
BASiCS_VarThresholdSearchHVG_LVG.R-        VarThreshold = VarThresholdsGrid[i]
```

* In Classes.R, you should not be using `stop` to generate an error. Just use `return` instead.

```
    if (length(object@mu) == 0 | length(object@delta) == 0 | length(object@phi) == 0 | length(object@s) == 0 |\
 length(object@nu) ==
        0 | length(object@theta) == 0) {
        errors <- c(errors, "One or more slots are missing")
        stop(errors) ## return(errors)
    }
```

Do the same for all your `setClass` calls. 

* In the Methods.R, instead of `message` you should be using `cat` because you want those printed to the stdout.

* In the file, HiddenFunctions.R, there are a lot of calls which are already vectorized in R, rowSums, colSums, rowMedians etc. Use those instead of the apply functions, and crating wrappers around it.

* Check your R code formatting for lines over 80 chars. Makes it easier to read, use the package `formatR` if you need to.

**Comment by catavallejos** [comment]
Thanks @nturaga 

I will go through your comments and get back to you asap.

**Comment by catavallejos** [comment]
Hi @nturaga 

As requested, I went through the code and implemented the suggested changes (+ some extra!)

A summary of the main changes is listed below.

Please let me know if anything is unclear (or if anything is missing)

Best

Cata



## vignettes: 
- html + cache files have been removed
- Formatted file to avoid long lines

## src
- Merge of `HiddenBASiCS_MCMCcpp` and `HiddenBASiCS_MCMCBatchcpp` to avoid redundant code
- `HiddenBASiCS_DenoisedRates` has been translated to C++ (previously implemented in R)
- General clean-up

## R
- `matrixStats` functions (e.g. `colMeans2`) to replace `apply` calls 
- Use of `seq_len` and `seq_along` to avoid `1:length(x)` and `1:x` calls 
- `print` and `cat` calls replaced by `message` calls
- Use of `return` rather than `stop` in Classes.R
- `BASiCS_DenoisedRates` optimised as requested (also moved to C++ for speed)
- Missing examples added for `BASiCS_DenoisedRates` and `BASiCS_DenoisedCounts`
- `BASiCS_MCMC` adapted to the C++ functions that were merged
- General clean-up and format to avoid long lines

## tests
- Additional unit tests have been implemented

**Comment by catavallejos** [comment]
Hi @nturaga 

In addition to the changes listed above, I just made a small change to modify the default value for `PriorDelta` in the `BASiCS_MCMC` function. I do not plan to make further changes. 

My apologies for any inconvenience.

Best

Cata

**Comment by nturaga** [comment]
Hi @catavallejos ,

I will review your package tomorrow. Please make any other changes you wish to make by then.

**Comment by nturaga** [comment]
# Updates:

 * `inst` directory empty, not needed.

 * good vignette, but generates a lot of warnings(). (50 to be exact)

 ```
 !> > warnings()
  Warning messages:
  1: In segments(x0 = Column, y0 = object[Column, 2], y1 = object[Column,  ... :
    "log" is not a graphical parameter
  2: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  3: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  4: In segments(x0 = Column, y0 = object[Column, 2], y1 = object[Column,  ... :
    "log" is not a graphical parameter
  5: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  6: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  7: In segments(x0 = Column, y0 = object[Column, 2], y1 = object[Column,  ... :
    "log" is not a graphical parameter
  8: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  9: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  10: In segments(x0 = Column, y0 = object[Column, 2], y1 = object[Column,  ... :
    "log" is not a graphical parameter
  11: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
  12: In segments(x0 = Column - BarLength, y0 = object[Column,  ... :
    "log" is not a graphical parameter
 ```

 * Otherwise package looks fine.

**Comment by catavallejos** [comment]
Thanks @nturaga !

The bug should be fixed now.

Best

Cata

**Comment by catavallejos** [comment]
Hi @nturaga 

I'm sorry to bother you but, after fixing the warnings you suggested and triggering a new build, there seems to be a problem when running the CHECK in Windows. 

It looks like the problems is `matrixStats`:

```
* checking whether package 'BASiCS' can be installed ... WARNING
Found the following significant warnings:
  Warning: package 'matrixStats' was built under R version 3.4.2
``` 

Do you have any suggestions about how to fix that?

Many thanks in advance!

Cata

**Comment by nturaga** [comment]
hi @catavallejos 

This is on our end. It should be resolved soon.

**Comment by catavallejos** [comment]
Thanks for the update @nturaga

**Comment by nturaga** [comment]
Please bump the version.

**Comment by catavallejos** [comment]
Done!

**Comment by nturaga** [comment]
Nicely done @catavallejos

**Comment by catavallejos** [comment]
Thanks @nturaga! And thank you very much for your comments, the code is much nicer now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/catavallejos.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BASiCS\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BASiCS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
