### ISSUE TITLE
package restfulSE submission

### ISSUE THREAD

**Issue by shwetagopaul92** [Bioconductor/Contributions#476]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shwetagopaul92/restfulSE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
Probably should separate the HDF5 rest stuff from BigQuery, into two packages. 

The code needs a lot of work. Is it infeasible to support `assays()`? Probably should have two classes, one that extends just SummarizedExperiment, and another RangedSummarizedExperiment. Right now it forces RangedSummarizedExperiment, but then `[()` for some reason checks which one it is. I wonder if `assay()` could be simplified by using whatever logic DelayedArray uses to track lazy restriction.

I'd be more comfortable if you just used `BiocGenerics:::replaceSlots()`, instead of copying and pasting.

**Comment by shwetagopaul92** [comment]
@lawremi Thank you for your feedback. We would work on this once the package passes check!

**Comment by vjcitn** [comment]
@lawremi -- I hoped to avoid package sprawl and thus kept HDF5server and BigQuery approaches together.  I would like to understand how to factor away the data back end from SummarizedExperiment concept.  Hdf5 server and BigQuery would just be two of many possible options for external data supply.  DelayedArray/HDF5Array is a natural place to look for antecedent principles but when this was started it was just not clear to me how to satisfy those contracts with these data sources.  "restfulSE" is a catchy and concise name for what is going on here, but ultimately we might just want to add some code to SummarizedExperiment that supports these alternate back ends.  I hate to think that this package would be so ephemeral as it represents a lot of experimental work, but ultimately this strategy seems appropriate for SummarizedExperiment and the restfulSE authors would -- if this pans out --  become coauthors of SummarizedExperiment.

I would imagine you have some clear ideas about how to go about this externalization of the assays and we welcome your thoughts on this.

**Comment by lawremi** [comment]
Yes, I think the goal should be push the logic down to the assays, i.e., have DelayedArray backends for HDF5 REST and BigQuery. In the long term, we could have a DelayedDataFrame that holds the feature and/or column data, but I guess those are small enough for now. In principle, SummarizedExperiment should just be a dumb container of smarter objects.

**Comment by vjcitn** [comment]
We might want to be more upbeat about SummarizedExperiment's role.  I view it as a broker between the biologically informed interrogator and the more generic assay store.  So the tight binding between annotation and addresses and the object is fundamental.   You are right that as the metadata grows in volume it too may be externalized, but the methods to which the object must respond are biologically interpretable -- filtered using a list of genes or genomic positions and so on.  Setting the boundary between the pure numerical data and the metadata is not so trivial -- keeping them close has been important for reliability, and it works well when in-memory holism is feasible.  I think there are real risks emerging when we separate assay and annotation.  So I don't plan to do much coding on this any time soon -- I recognize that we cater for RangedSummarizedExperiment only, and that is a definite blemish.  But I really want to have a clean concept going forward before we do major surgery on this package.  I hope we can engage more folks who have an interest in the class design.

**Comment by lawremi** [comment]
I'm afraid that we might be talking past each other a bit. From the point of view of the user, the assay data and metadata are contained in the same object. But they could be stored in entirely different ways, and we'd want the flexibility to support that.

**Comment by vobencha** [comment]
Checking in. Are you planning modifications based on the discussion or should I go ahead with the review?
Val

**Comment by vjcitn** [comment]
We'll do a bit more work and let you know when to start.

**Comment by vjcitn** [comment]
We have just gone through the experiment of having RESTfulSummarizedExperiment extend SummarizedExperiment instead of RangedSummarizedExperiment.  We don't feel it is worth it at this time.  The code changes are minimal, but so much of what we are working with has ranges and should have ranges, we are faced with the dilemma -- introduce two classes of RESTful SE (one ranged, one non-ranged) or just use one and lose the (useful) constraints of ranged character.

@lawremi mentioned an issue with assays() and we do have that method, but we do not cater for multiple assays in a RESTfulSummarizedExperiment at this time.

We agree that in the long term, multiple back ends and multiple assays could be supported.  But I don't see any major modifications to the code base in this package any time soon, unless mandated, so go ahead with review, @vobencha.  Thanks!

**Comment by lawremi** [comment]
I'll let @vobencha run the show, but it just seems to make more sense to create a DelayedArray backend and just use SummarizedExperiment as-is. Then you're using composition and there is no longer an issue with combinatorial inheritance, and `assays()` just works.

**Comment by vjcitn** [comment]
I have spent a few hours trying to make a DelayedH5SMatrix class.  Progress has been made, but we run into things like
```
> subset_seed_as_array(jj@seed, list(1:3,1:5))
           [,1]      [,2]       [,3]       [,4]        [,5]
[1,]  0.4733963 1.2943041 -0.8084735  1.0056166 -0.90349832
[2,]  1.2364086 0.2099817 -0.2683763 -1.2354204 -0.02221144
[3,] -0.2225818 1.6236857 -0.8654838 -0.3172301 -0.02754413
> jj
Error in dim(ans) <- .get_DelayedArray_dim_before_transpose(x) : 
  attempt to set an attribute on NULL
```
The requirements on seed behavior are not clear enough to me.  We will continue to explore this but it should not impede the review.

**Comment by vjcitn** [comment]
i have created experimental package in github repo vjcitn/DelayedExternal that seems to work for defining DelayedHDF5SMatrix (the S indicates using HDF server) and for using that as an assay in  a SummarizedExperiment (example("DelayedHDF5SMatrix-class").  i will check with Herve to see if this satisfies the contract.  if it does we will slide this into rhdf5client and adjust restfulSE accordingly.

**Comment by vobencha** [comment]
Sorry for the delay ... first on my list for tomorrow.

**Comment by vobencha** [comment]
Hi @vjcitn  and @shwetagopaul92 

I've done a first pass. Please see comments and suggestions below.

1) Imports and Depends

    When a package is in 'Depends' it's loaded (attached to search path) when restfulSE is loaded. It doesn't make sense to use selective imports for a package in 'Depends'. Selective importing is used for packages in 'Imports'. 

    There are different approaches to handling packages in 'Depends'. Some people fully import them in the NAMESPACE and others leave the package out of the NAMESPACE.  I personally think it is more clear to fully import, e.g.,
```
    import(methods)
    import(dplyr)
    etc...
```

  Please remove selective imports for packages in 'Depends' and either fully import or leave them out of the NAMESPACE.

2) SummarizedExperiment package

    restfulSE extends the SummarizedExperiment class. Any reason why you don't have SummarizedExperiment in 'Depends'? It seems highly likely you'd want some inherited methods from SummarizedExperiment available to the user.

3) Description in DESCRIPTION

    I would add a little more to the Description. This is what you currently have:

    " Description: We wrap HDF5Server content or BigQuery content in SummarizedExperiment interface."

    SummarizedExperiment is a class and not a method for downloading data. Maybe the package provides functions to interface with BigQuery and HDF5Server and parses the data into a SummarizedExperiment? Or something along those lines.

4) A software package should be <= 4MB on disk:

    http://www.bioconductor.org/developers/package-guidelines/#correctness

    We have some trimming to do:
```
    ~/repos/github/packageReview >du -h restfulSE_0.99.2.tar.gz
    49M    restfulSE_0.99.2.tar.gz
```
5) man pages for classes and functions

    The man pages need some work. Many are sparse and incomplete. For example, this is the man page for BQSummarizedExperiment-class:

```
    \docType{class}
    \name{BQSummarizedExperiment-class}
    \alias{BQSummarizedExperiment-class}
    \title{define a class to use BigQuery data through SummarizedExperiment interface}
    \description{
    define a class to use BigQuery data through SummarizedExperiment interface
    }
```

Contrast this with the ?SummarizedExperiment or ?RangedSummarizedExperiment man pages. If you need examples of complete man pages please see GenomicRanges, GenomicAlignments, Rsamtools, IRanges etc.

6) man pages for datasets

    I think you'll need to remove or trim the datasets to get the package size <4MB. Once that's done, please consider grouping the datasets and puting several on one man page. This makes discovery easier for the user and (I think) it's easier for you to maintain less man pages.

    For examples of complete man pages for datasets see
```
    library(minfiData)
    ?MsetEx
```

7) Remove the oldREADME.md.

8) library() calls in vignette

    You only need to load packages once - usually at the top of the vignette in a section called 'set up' or something similar. This is a matter of style and not a requirement but I would recommend only loading packages once:
```
~/repos/github/packageReview/restfulSE >grep library vignettes/restfulSE.Rmd
library(restfulSE)
library(GO.db)
library(org.Hs.eg.db)
library(SummarizedExperiment)
library(restfulSE)
library(org.Mm.eg.db)
library(restfulSE)
library(SummarizedExperiment)
library(Rtsne)
library(rhdf5client)
library(restfulSE)
library(org.Mm.eg.db)
library(restfulSE)
```

9) Please address these issues from the Single Package Builder output

```
checking R code for possible problems ... NOTE
.RESTfulSummarizedExperiment: no visible global function definition for
  is
.RESTfulSummarizedExperiment: no visible global function definition for
  new
TCGA_tablerefs: no visible global function definition for new
...
Consider adding
  importFrom("methods", "as", "is", "new", "slot", "slot<-",
             "validObject")

* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 17 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    object (function)
      is (.RESTfulSummarizedExperiment)
      new (.RESTfulSummarizedExperiment)
      ...
      slot (unsafe_replaceSlots)
      slot<- (unsafe_replaceSlots)

```

**Comment by vjcitn** [comment]
Thanks for all this.  I agree that we should move the data out.

We will do this by creating a related data experimental data package along
these lines

https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages

**Comment by lawremi** [comment]
Point number 1 needs some correction. Packages in Depends are indeed attached to the search path, but that is pretty much orthogonal to importing in NAMESPACE. All symbols referenced by the package code need to be imported in order to ensure that they are resolved correctly. The Imports in DESCRIPTION is just for those dependencies that shouldn't be attached. 

Why import? Consider the case where package A has "Depends: B" but does not import(B) in NAMESPACE. If the code in A calls `foo()` from package B, but the user has defined their own `foo()` in `.GlobalEnv`, package A will call the user's `foo()`, not `B::foo()`.

To summarize point 9, S4-based packages should pretty much always just `import(methods)`, and probably also have methods in Depends although that may not be needed anymore.

**Comment by vobencha** [comment]
For my own clarification, having dplyr in  'Depends' yet selectively importing in NAMESPACE, e.g., 
```
~/repos/github/packageReview/restfulSE >grep dplyr NAMESPACE
importFrom(dplyr,filter)
importFrom(dplyr,filter_)
importFrom(dplyr,one_of)
importFrom(dplyr,tbl)
```
means only filter, one_of and tbl are used internally and we only care about resolving those symbols. Attaching to the search path via 'Depends' is just a convenience for the user. Is this more correct?

**Comment by lawremi** [comment]
Yes

**Comment by vobencha** [comment]
@lawremi Thanks for jumping in and clarifying.

**Comment by vjcitn** [comment]
I am not sure how we'll resolve this but at the moment it seemed to me
that the user is not expected to be working with dplyr, so we are moving
dplyr and magrittr to imports and importing selectively.

**Comment by lawremi** [comment]
Out of curiosity I looked at the dplyr code. I'm not very familiar with it, but I thought you could simplify the `seByTumor()` function a lot by using a join, something like:

```
clin <- clinRef %>% filter(project_short_name==newn)
rowData <- inner_join(clin, assayRef, by=colkey) %>%
    dplyr::select(rdColsToKeep)
```

**Comment by hpages** [comment]
Totally agree with @lawremi that SummarizedExperiment should just be a dumb container of smarter objects.

Creating SummarizedExperiment or/and RangedSummarizedExperiment extensions that have the same semantic as their parent but only differ in that they use a specific storage for the assays can easy lead to exponential proliferation of subclasses (e.g. RESTfulDESeqDataSet, HDF5ArrayDESeqDataSet, RleArrayDESeqDataSet etc... one for each type of storage, then do the same for DESeqTransform and for the 30+ SummarizedExperiment/RangedSummarizedExperiment extensions currently defined in Bioconductor). We could easily end up with 120+ SummarizedExperiment extensions!

Solving the problem of SummarizedExperiment objects with on-disk or external assay data is really solving the problem of array-like objects with on-disk or external data. Solving it at this level not only avoids the proliferation of SummarizedExperiment subclasses but it also has the immense benefit of making your array-like objects reusable in a broad range of contexts, not just in the SummarizedExperiment context, not just in biology, but any context where one needs to operate on array data that is too big to fit in memory.

Another inconvenient of RESTfulSummarizedExperiment is that it doesn't allow mixing assay storage types e.g. it wouldn't support an object with a RESTfulArray (or RemoteArray) assay and an HDF5Array assay. I think that's something we want to support.

**Comment by hpages** [comment]
BTW I originally ended up here because I've been assigned the tenXplore package which was recently submitted by Vince (https://github.com/vjcitn/tenXplore). I struggled a little bit to install its dependencies because a couple of them (restfulSE, ontoProc) are also in the process of being reviewed and thus have to be installed from GitHub. I noticed that restfulSE was depending on restfulSEData, which is also only available on GitHub at the moment. Since restfulSE only uses restfulSEData in the examples and unit tests, I was wondering if it could be moved to Suggests so people can still use restfulSE and/or tenXplore without having to download 49M of data that they don't need.
Thanks,
H.

**Comment by vjcitn** [comment]
yes that can be done.

**Comment by vjcitn** [comment]
well, we are working in that direction.  i am grateful for your guidance as
to how the DelayedArray concept can be extended; i put our correspondence
as issues in vjcitn/DelayedRemote repo.  there is a pragmatic aspect to my
approach here -- i had to demonstrate to myself that HDF5 server could be
used to interact with data "as if" one were working with a summarized
experiment.  In my view there is still a substantial vulnerability that has
nothing to do with S4 ... how to take an arbitrary G, S in the standard
X[G, S] idiom and translate it reliably and efficiently to a request to the
remote store, returning the requested data.  This has to be solved for HDF5
server, bigquery, etc. etc.  We have something that seems to work and Sam
Pollack is improving it.  Any error in that part of the task is
unacceptable.

I have no problem evolving this to a state where there is nothing but a
little extra code in SummarizedExperiment that handles these remote
resources.  It wasn't possible given what I knew when this proof of concept
began, and I am not sure it is possible now.  We are trying to provide
working code that satisfies genuine use cases.  Harmonious design is
certainly important and we are not deliberately being inconvenient.  If
there are ways we can help with the review please let us know.

**Comment by hpages** [comment]
What about RESTfulArray or RemoteArray instead of DelayedRemote? And RESTfulArraySeed or RemoteArraySeed for the corresponding seed class? That would be more consistent with the other DelayedArray specializations HDF5Array and RleArray (HDF5ArraySeed and RleArraySeed being the corresponding seed classes).

**Comment by vjcitn** [comment]
thank you for these suggestions, i will implement ASAP

**Comment by shwetagopaul92** [comment]
Hi @vobencha 
Thank you for all the feedback. We have made the changes required. 

Addressing each issue individually : 
1.)  Selective importing has been removed for packages in "Depends". 

2.) SummarizedExperiment has been added to "Depends". 

3.) We have made the description field in DESCRIPTION more elaborate. 

4.) The size of the package has been reduced. The datasets in /data has been moved to a new data package - restfulSEData, which would be an ExperimentHub package soon.  
> du -h restfulSE_0.99.10.tar.gz
436K	restfulSE_0.99.10.tar.gz

5.) We have made changes to make the man pages more complete. 

6.) The datasets have been moved to a new package - restfulSEData, and the man pages are now found in that. 

7.) oldREADME.md has been removed. 

8.) We feel that it is crucial to have library() in the different examples of the vignette. If a user wants to run an example from the middle of the vignette, the library() would have to be used at that time.  

9.) These issues have been addressed. 

We would be happy to make any other change if required. Thank you !

**Comment by vobencha** [comment]
Thanks @shwetagopaul92  for making the changes.

Which changes discussed in https://github.com/Bioconductor/Contributions/issues/476#issuecomment-333027569 are you planning to implement? It's not clear to me if this package is supposed to go forward as is or if it's being rewritten according to that discussion.

**Comment by vjcitn** [comment]
Package should go forward as is.  The longer term implementation of the RemoteArray API will take more collaborative work, but will not disrupt/degrade behavior of this package.

**Comment by vobencha** [comment]
OK, thanks. Package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shwetagopaul92.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"restfulSE\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/restfulSE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by vjcitn** [comment]
restfulSE depends on rhdf5client which is still under review.  restfulSE
will fail in the biocdevel build system until rhdf5client is also
included.  we are sorry we did not use the "related package" framework for
this ... an oversight.  let us know how to remedy this.  i will take a look
at rhdf5client to see its status, i think it was quite close to final.
