### ISSUE TITLE
submitting ontoProc package

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#478]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/ontoProc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by dvantwisk** [comment]
Hello,

Sorry for the delay, we needed to make some relevant changes to our documentation before we submitted it.  At any rate, the package looks very good, and we only have a few changes.

The most important thing is that your package contains large data files in it (such as inst/obo/checbi.obo.gz).  We would require this package to be transitioned into an ExperimentHubData package that would provide access to the data via Biocondcutor's ExperimentHub. Documentation on the required files and process in achieving this can be found [here](https://github.com/Bioconductor/ExperimentHub/blob/master/vignettes/CreateAnExperimentHubPackage.Rmd).

This review was done a few weeks back at an earlier version of your package and currently does not reflect changes you made to it during your recent commits.  After your address these issues, we will look through your package again and consider the newer changes that you have made.  Please message us back when you have completed your changes so that we may continue our review.

DESCRIPTION
- [REQUIRED] The description is too short.  Try to provide more detail. 

R/countClasses.R
- [CONSIDER] Remove commented out code.

R/data.R
- [REQUIRED] Be more descriptive about the format of the data and its origin.

R/getOntos.R
- [CONSIDER] It would be better to use `.rds` instead of `.rda` files and use
`readRDS()`.

R/termProc.R
- [REQUIRED] L52-57: Avoid expensive copy and append pattern:
```
j <- seq_len(args)
ansu <- unlist(lapply(args, function(elt) elt@ontoTags))
ansf <- do.call(rbind, lapply(args, function(elt) elt@cleanFrame))
```
inst/

vignette
- remove the file `vignettes/ontoproc.pdf`

**Comment by vjcitn** [comment]
We've had a little discussion with Martin about how to move the high
volume information to AnnotationHub.  @mtmorgan was going to set up a slack
issue on this i think.

On Thu, Oct 12, 2017 at 11:43 AM, Daniel Van Twisk <notifications@github.com

**Comment by dvantwisk** [comment]
Okay, thanks for the update.  That should solve the data file size issues, so all that's left is the few changes we have.

**Comment by dvantwisk** [comment]
Hello,
I just need to inform you that the small changes that I mentioned in my review should be implemented today if you want this package to be included in the 3.6 release.  Please fix the [REQUIRED] issues I pointed out in the review above.

**Comment by vjcitn** [comment]
Thanks, the REQUIRED have now been done.  I submitted for building.

**Comment by dvantwisk** [comment]
Everything looks good.

**Comment by vjcitn** [comment]
I am assuming that the move of the larger .rda files to AnnotationHub will
be addressed later, for the next release.  I have not had time to address
the suggestion to move to rds.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ontoProc\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ontoProc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
