### ISSUE TITLE
seqCAT

### ISSUE THREAD

**Issue by fasterius** [Bioconductor/Contributions#482]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fasterius/seqCAT

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Pretty much a first -- package build and check without error or warning on first go -- congratulations! Very nicely put together package. Please revise your package in response to the following comments, posting a short comment summarizing your changes when done.

DESCRIPTION

- great!
- no eed for Author: and Maintainer: fileds when Authors@R: present
(generated when package built)

vignette

- great!

R

- clar and well-formated, thanks!
- `stop(paste0("foo ", "bar"))` can be written as `stop("foo ", "bar")` likewise with `message()`, `warning()`.
- it may sometimes help readability to write less nested code, e.g., compare_profiles.R:189

    ```
    ridx = data[[mcol_s1]] == data[[mcol_s2]]
    data[ridx, mcol] <- data[[mcol_s1]]
    data[!ridx, mcol] <-
                paste0("[", data[[mcol_s1]], ",", data[[mcol_s2]], "]")
    ```
- create_profile.R:64 use `ScanVcfParam()` to selectively import
  relevant fields from VCF.
- create_profile.R:42 consider non-exported functions `create_profile_python()` / `create_profile_R()` to allow for less nested code.
- create_profile_R:52 check for error condition on `system2()`.
- create_profile_R:146 and elsewhere avoid `1:n`, using `seq_along()` or `seq_len()` instead (robust to `n == 0`).
- create_profile_R:146 this is a 'copy and append' pattern `df0 = data.frame(); for (i in 1:nrow(x)) df0 = rbind(df0, data.frame())` which is very ineffcient. Better is to `res = lapply(seq_len(nrow(df)), function(...) data.frame()); do.call(rbind, res)`.
- create_profile_R:146 is there scope for hoisting common operations out of the loop to increase vectorization, e.g., `ann <- tidy::separate_()` on the entire column rather than single row.  A trivial example is `data_cols` line 197.
- create_profile_R:209 this loop can be replaced with `ann[data_cols] <- data[n, data_cols]`

man

- consider param descriptions that include type info, e.g., `@param a numeric(1) Similarity score parameter a`.

**Comment by fasterius** [comment]
Thanks a lot, mtmorgan! I appreciate the feedback and tips for improvements. I have performed all the changes as you suggested; hopefully I interpreted them correctly. 

- I added a function for checking if there's an error when running the python version of the create_profile script (*i.e* checking for errors in `system2()`), hopefully what I did was something along the lines of what you had in mind.
- I hoisted many of the vectorisable parts of the `create_profile` function out of the for loop and changed the for loop accordingly. I tried in vain to create an equivalent with `lapply` (the things I tried either gave me a "killed: 9" exit or yielded incorrect results), but in the end I managed to optimise it by pre-allocating a list for each unique position and loop over that, replacing values in the list rather than using the copy & replace process used before. If you have any more ideas on further optimisation of this I'm happy to hear them!

**Comment by mtmorgan** [comment]
Thanks for the changes, the revisions look good.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fasterius.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"seqCAT\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/seqCAT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
