### ISSUE TITLE
oncomix

### ISSUE THREAD

**Issue by dpique** [Bioconductor/Contributions#484]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dpique/oncomix

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# oncomix Review

 R CMD build: ok

 R CMD INSTALL: ok

 ## DESCRIPTION

 * Ok

 * No bioconductor packages being used.

 ## NAMESPACE

 * ok

 ## vignettes

 * ok. Good job.

 ## man

 * ok

 ## R

 * Wouldn't it be easier if dfNml, and dfTumor were just matrices? Support the class           SummarizedExperiment as input to your function.

 * Accept transposed data, where rows are genes and patients are columns, which is common in   bioinformatics.

 * Replace 1:ncol (L:58:oncoMix_two_component_mixture_models.R) to seq_len(ncol(dfNml))

 ## data

 * Describe the data more, i.e how they were obtained and processed.

**Comment by dpique** [comment]
Hi @nturaga, 

Thanks for your feedback on my package. I have listed the changes as sub-bullet points below each of your comments. 

Please let me know if there's anything that needs clarification.

Best,
Daniel


DESCRIPTION
----------------
- No bioconductor packages being used.
	- I added compatibility with the SummarizedExperiment class (see below) to improve integration of oncomix with Bioconductor and standard container classes.
	
R
----------------
- Wouldn't it be easier if dfNml, and dfTumor were just matrices? Support the class SummarizedExperiment as input to your function.
	- Yes. I added a new function, toMatrix, to convert SummarizedExperiment and data.frame objects to matrices. I added toMatrix to the body of functions where dfNml and dfTumor – which are now matrices – are used as inputs. 
	- I renamed dfNml and dfTumor to exprNml and exprTum to avoid confusion about the object class that is required as input (now that several matrix-like classes, not just a dataframe (df), can be used as input to the mixModelParams and plotGeneHist functions).
- Accept transposed data, where rows are genes and patients are columns, which is common in bioinformatics.
	- I rearranged the functions to accept matrices in which the rows are genes and patients are columns.
- Replace 1:ncol (L:58:oncoMix_two_component_mixture_models.R) to seq_len(ncol(dfNml))
	- I made this change, and I also updated the man examples to include seq_len() where possible.
- Other:
	- I updated the description of the return value for the `mixModelParams` function.

data
----------------
- Describe the data more, i.e how they were obtained and processed.
	- I added descriptions on how the data were obtained and processed to the man pages. I also changed the dataset names (dfNmlIsof and dfTumorIsof are now exprNmlIsof and exprTumIsof, respectively) because these objects are now matrices and not dataframes (df).

**Comment by nturaga** [comment]
Hi @dpique 

Once you are ready with the changes, please provide a brief summary for each point. I will review your package again after you reply.

**Comment by dpique** [comment]
Hi @nturaga, 

Thanks for your message. I updated the package based on your feedback, and a summary of the changes that I made are listed below. Please let me know if there's anything that needs clarification. Looking forward to hearing your feedback on this new set of changes.

Best,
Daniel

DESCRIPTION
----------------
- I added compatibility with the SummarizedExperiment class (see below) to improve integration of oncomix with Bioconductor.
	
R
----------------
- I added a new function, `toMatrix`, to convert SummarizedExperiment and data.frame objects to matrices. I added `toMatrix` to the body of functions where dfNml and dfTumor – which are now matrices – are used as inputs. 

- I renamed dfNml and dfTumor to exprNml and exprTum to avoid confusion about the object class that is required as input (now that several matrix-like classes, not just a dataframe (df), can be used as input to the mixModelParams and plotGeneHist functions).

- I rearranged the functions to accept matrices in which the rows are genes and patients are columns.

- I replaced 1:ncol (L:58:oncoMix_two_component_mixture_models.R) with seq_len(ncol(dfNml)). I also updated the man examples to include seq_len() where possible.

- I updated the description of the return value for the `mixModelParams` function.

data
----------------
- I added descriptions on how the data were obtained and processed to the man pages. I also changed the dataset names (dfNmlIsof and dfTumorIsof are now exprNmlIsof and exprTumIsof, respectively) because these objects are now matrices and not dataframes (df).

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dpique.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"oncomix\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/oncomix

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
