### ISSUE TITLE
scPipe: a package for single cell RNA-seq data processing and quality control

### ISSUE THREAD

**Issue by LuyiTian** [Bioconductor/Contributions#489]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LuyiTian/scPipe

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LuyiTian** [comment]
This is a resubmission of my package. 

It now uses the SingleCellExperiment as the base class and works well with other packages like scater and scran. It also supports the recently released official bam tags for the UMI and cell barcode:https://github.com/samtools/hts-specs/pull/200#event-1221322336. 

We have decided not to change the package name because we think it covers the main point of this package, which is a preprocessing pipeline of scRNA-seq. Apart from that, all other comments in the previous submission have been followed.

**Comment by LuyiTian** [comment]
Hi @hpages I think all errors and warnings are fixed and it can be reviewed now. :)

**Comment by vobencha** [comment]
Changing reviewer to vobencha since I reviewed of the original submission.

**Comment by vobencha** [comment]
Hi,

The package looks much better. Thank you for reusing SingleCellExperiment. A few comments below.

1) man pages for datasets

Please describe the matrices. Are there column/row names and what do they mean? Were the data QC'd? The souce simply lists a person's name - better to have a web site or paper reference. Please include as many details as you can about the data.

Also add an \examples section where you show how to load and manipulate the data.

2) There are several typos in the vignette. You may want to run a spell checker.

Valerie

**Comment by vobencha** [comment]
I just edited my [review](https://github.com/Bioconductor/Contributions/issues/489#issuecomment-334206176) to include a comment on LazyData.

**Comment by LuyiTian** [comment]
Hi, @vobencha I have made changes according to your review.

**Comment by vobencha** [comment]
Thank you. Package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LuyiTian.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"scPipe\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scPipe

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
