### ISSUE TITLE
chromswitch

### ISSUE THREAD

**Issue by sjessa** [Bioconductor/Contributions#490]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sjessa/chromswitch

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment]
Hi Selin,
Thanks for your submission. chromswitch is in good shape and will be a nice addition to Bioconductor. The vignette looks great. There are only a few minor points that would need your attention. Most of them are cosmetic. See below.
Cheers,
H.

1. The user will typically interact a lot with GRanges objects when using chromswitch so please move GenomicRanges from Imports to Depends and replace all the `GenomicRanges::GRanges()` calls with `GRanges()` in the man pages and vignette. This will make interacting with GRanges objects much more
convenient.

2. Note that having GenomicRanges in Depends will automatically attach IRanges to the search path when loading chromswitch. So, for the sake of convenience, also please replace all the `IRanges::IRanges()` calls with `IRanges()`.

3. The documentation for `localPeaks` is confusing. There are 2 man pages, accessible with `?localPeaks` and `class?localPeaks`. The former seems to document localPeaks objects and has a \usage section showing how to call a `localPeaks()` function that looks like a constructor but is not available. The latter is a 1-liner. None of them has examples.
Please merge the 2 man pages in one. Both `?localPeaks` and `class?localPeaks` should open it. Either export the `localPeaks()` function (if it's actually intended to be used by the end-user) and add an example section showing how to use it, or keep it unexported and don't document it in the man page.

4. Also please move all the accessor functions for localPeaks objects (e.g. `lpkPeaks()`, `lpkRegion()`, `lpkSamples()`) to the man page of these objects.
Note that the recommended practice for accessor functions is to define them as methods of existing or new generics. Then, because the accessor is generic, its name doesn't need to (and shouldn't) try to encode the type of objects that it operates on. So here the names would just be `peaks()`, `region()`, and `samples()`. Note that `peaks()` and `region()` would be new generics, but `samples()` is a generic that is already defined in the Biobase package so you would need to import Biobase. Finally, the name of the argument of the accessor shouldn't try to encode the type of object either so should be `x` or `object`.

5. Please define an `"isEmpty"` method for localPeaks objects instead of introducing the new `is.empty()` generic for this. The `isEmpty()` generic is defined in S4Vectors.

6. Why provide man pages for things that are not available?

7. The man page for `normalizePeaks()` has `winsorNorm` in its \seealso section but `winsorNorm()` is not exported. Since `winsorNorm()` implements an operation that is so central to `normalizePeaks()`, it should be exported and its man page have an \examples section. This would greatly help the user understand what `normalizePeaks()` does.

8. The 1st argument of `reducePeaks()`, `summarizePeaks()`, and `binarizePeaks()` is `localpeaks`, `localpeaks`, and `lpks`, respectively, and, for the 3 functions, is expected to be a localPeaks object. Is there any reason why the name of the argument is not the same for the 3 functions?

9. The \description section for the `cluster()` function contains the single word "cluster" and the man page has no \details section. Please improve this man page by describing what the function does. Typically the
\description section should give a brief overview (in a short sentence or two) and more details should be provided in the \details section.

**Comment by sjessa** [comment]
Hi @hpages, thanks for your suggestions - those are very helpful! I will make the appropriate changes, bump the version of the package, and respond to your comments shortly.

**Comment by sjessa** [comment]
Hi @hpages, thanks again for your comments! I've addressed them all in my recent commits, and responded below.

> 1. The user will typically interact a lot with GRanges objects when using chromswitch so please move GenomicRanges from Imports to Depends and replace all the GenomicRanges::GRanges() calls with GRanges() in the man pages and vignette. This will make interacting with GRanges objects much more convenient.
>
> 2. Note that having GenomicRanges in Depends will automatically attach IRanges to the search path when loading chromswitch. So, for the sake of convenience, also please replace all the IRanges::IRanges() calls with IRanges().

I've moved GenomicRanges to Depends and removed all the namespacing in these calls (but left it for functions from these packages other than `GRanges()` and `IRanges()`).

> 3. The documentation for localPeaks is confusing. There are 2 man pages, accessible with ?localPeaks and class?localPeaks. The former seems to document localPeaks objects and has a \usage section showing how to call a localPeaks() function that looks like a constructor but is not available. The latter is a 1-liner. None of them has examples.
> Please merge the 2 man pages in one. Both ?localPeaks and class?localPeaks should open it. Either export the localPeaks() function (if it's actually intended to be used by the end-user) and add an example section showing how to use it, or keep it unexported and don't document it in the man page.

I've moved all the documentation for the class to the class man page, and made the constructor `localPeaks()` non-exported. Both `??localPeaks` and `class?localPeaks` now open the class man page.
 
> 4. Also please move all the accessor functions for localPeaks objects (e.g. lpkPeaks(), lpkRegion(), lpkSamples()) to the man page of these objects.
> Note that the recommended practice for accessor functions is to define them as methods of existing or new generics. Then, because the accessor is generic, its name doesn't need to (and shouldn't) try to encode the type of objects that it operates on. So here the names would just be peaks(), region(), and samples(). Note that peaks() and region() would be new generics, but samples() is a generic that is already defined in the Biobase package so you would need to import Biobase. Finally, the name of the argument of the accessor shouldn't try to encode the type of object either so should be x or object.

I have made all three accessors into methods as you suggested, using the names `samples()`, `region()`, and `peaks()`, and I've also added a *Methods* section documenting these in the `localPeaks` class documentation, which links to their individual documentation.

If I may make a suggestion for Bioconductor's documentation for developers, I was following the [Essential S4 Interface](http://bioconductor.org/developers/how-to/efficient-code/#essential-s4-interface) when implementing the class - I think it would be useful to add to that section your clarifications about best practices for accessors.

> 5. Please define an "isEmpty" method for localPeaks objects instead of introducing the new is.empty() generic for this. The isEmpty() generic is defined in S4Vectors.

Thanks; done.

> 6. Why provide man pages for things that are not available?

Good point - I've  either exported these functions and added examples in the case of small utility functions, or made the documentation for these functions into non-Roxygen comments in the .R files so they no longer have man pages, but are still documented in the code for clarity/in case they need to be exported in the future.

> 7. The man page for normalizePeaks() has winsorNorm in its \seealso section but winsorNorm() is not exported. Since winsorNorm() implements an operation that is so central to normalizePeaks(), it should be exported and its man page have an \examples section. This would greatly help the user understand what normalizePeaks() does.

Agreed; `winsorNorm()` is now exported and the documentation improved by an example.

> 8. The 1st argument of reducePeaks(), summarizePeaks(), and binarizePeaks() is localpeaks, localpeaks, and lpks, respectively, and, for the 3 functions, is expected to be a localPeaks object. Is there any reason why the name of the argument is not the same for the 3 functions?

Thanks for catching this! I've changed the argument name for `binarizePeaks()` for consistency.

> 9. The \description section for the cluster() function contains the single word "cluster" and the man page has no \details section. Please improve this man page by describing what the function does. Typically the \description section should give a brief overview (in a short sentence or two) and more details should be provided in the \details section.

I've improved the documentation of this function with a brief description.

Please let me know if you have any further suggestions!

Thanks,
Selin

**Comment by sjessa** [comment]
Hi @hpages,

Just wanted to give you a heads up that along with [responding to your review](https://github.com/Bioconductor/Contributions/issues/490#issuecomment-333325291), I've pushed some changes to the package recently, mostly minor, but they include an update to the vignette. We think the new version is significantly clearer. Looking forward to your feedback.

Thanks,
Selin

**Comment by hpages** [comment]
Thanks for these improvements.

There are a few leftovers (and 2 new things) that would need to be addressed and the package will be good to go. See below.

Regards,
H.

A. Please rename the class _localPeaks_ -> _**L**ocalPeaks_ (class names should start with a capital letter in Bioconductor). This is not a leftover but something I forgot to report earlier. Sorry for that.

B. Another Bioconductor convention is that the constructor function for the class should be named like the class so please also rename the `localPeaks()` function -> `LocalPeaks()`.

C. This constructor function is actually not exported so don't put it in the \usage section in the man page of the LocalPeaks class. What should go in this section instead are the 3 accessor methods defined for this class:
```
\usage{
\S4method{region}{LocalPeaks}(x)
\S4method{samples}{LocalPeaks}(object)
\S4method{peaks}{LocalPeaks}(x)
}
```

D. No need to have separate man pages for the `region()` and `peaks()` generic functions. Please remove these man pages and add the `region`, `samples`, and `peaks` aliases to the man page for the LocalPeaks class. This way when the user does `?region`, or `?samples`, or `?peaks`, s/he will get that man page.

E. Other problems in the man page for the LocalPeaks class:
    - "A localPeaks object is a S4 class, a container for the peaks etc": an _object_ is not the same thing as a _class_. Something like "The LocalPeaks class is a container for the peaks etc " would be more appropriate.
    - It doesn't seem to be the case that the `region`, `samples`, and `peaks` methods allow one to _set_ slots as stated in the man page. IIUC these methods are _getters_, not _setters_.
    - Please add an \examples section that shows how one typically generates a LocalPeaks object and how to use the accessors on it.

F. Do not put curly brackets around the `standardGeneric()` call in your `setGeneric` statements. So for example, it should be:
```
setGeneric("region", function(x) standardGeneric("region"))
```
instead of:
```
setGeneric("region", function(x) {standardGeneric("region")})
```

**Comment by sjessa** [comment]
Hi @hpages,

Thanks for your comments - I've incorporated all your notes into the definition & documentation for the LocalPeaks class in the latest version update. Let me know if the man page is suitable now, and if you have any other feedback. 

Thanks,
Selin

**Comment by hpages** [comment]
Hi Selin,
Thanks for all the changes. Maybe I was not clear enough but you don't need to have separate man pages for the `region`, `sample`, and `peaks` accessors. These accessors are already documented in the man page for the LocalPeaks class. Thanks!
H.

**Comment by sjessa** [comment]
Hi @hpages - got it, thank you. I've removed those man pages.

**Comment by hpages** [comment]
Perfect! Thanks for the quick response. I'm marking the package as accepted.

Thanks for your contribution to Bioconductor!

H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sjessa.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"chromswitch\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/chromswitch

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by sjessa** [comment]
Great, thanks for all your help, @hpages!
