### ISSUE TITLE
package restfulSEData submission

### ISSUE THREAD

**Issue by shwetagopaul92** [Bioconductor/Contributions#498]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shwetagopaul92/restfulSEData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Because of the size of the files we would recommend reformatting this package into and ExperimentHub package with the data stored on the Bioconductor AWS S3 buckets. Please see [Creating ExperimentHub Package](https://github.com/Bioconductor/ExperimentHub/blob/master/vignettes/CreateAnExperimentHubPackage.Rmd)

**Comment by shwetagopaul92** [comment]
@lshep Hi Lori, Thank you for the feedback.  I am working on making an ExperimentHub package.

**Comment by lshep** [comment]
Thank you!

**Comment by lshep** [comment]
Hi,  
You can ignore those WARNINGS and ERROR; those are on our end.  
I will work on getting the data moved officially over into ExperimentHub and into the production database today and tomorrow. Once that occurs you will be able to test it and make the examples access through the hub live.  
Cheers!
Thank you again for modifying;  I think it will be very useful to store these files in the hub.

**Comment by shwetagopaul92** [comment]
@lshep  Hi Lori!  Thank you for your response. We would be happy to make any other change if required.

**Comment by lshep** [comment]
Actually you will need to add in a column in the metadata.csv entitiled "RDataPath" ,  it would contain the path of the file in AWS eg.  "restfulSEData/tasicST6.rda", "restfulSEData/gtexRecount.rda"

**Comment by lshep** [comment]
To ensure that the metadata.csv file is formatted correctly with necessary information , please make sure you can run AnnotationHub::readMetadataFromCsv("<pathToPackage/>restfulSEData")

**Comment by shwetagopaul92** [comment]
@lshep Thank you for your response. I have made the changes. 
I have added RDataPath to the metadata.csv file and capitalized "Rda" for DispatchClass. I was able to run AnnotationHub::readMetadataFromCsv("restfulSEData").
Thank you!

**Comment by lshep** [comment]
Hey there.  It looks like the last commit b57edfe reverted the "Rda" to "rda"  - I'll manually update a local version I copied to get the resource into ExperimentHub but please update when you get a chance.

**Comment by lshep** [comment]
The data has been added to the production ExperimentHub database and is now accessible 
```
> library(ExperimentHub)
> eh = ExperimentHub()
snapshotDate(): 2017-10-06
> myfiles
ExperimentHub with 7 records
# snapshotDate(): 2017-10-06 
# $dataprovider: 10x Genomics, GEO, GTex, Illumina 450 methylation assay, yr...
# $species: Homo Sapiens, Mus Musculus (E18 mice), Homo sapiens, Mus Musculu...
# $rdataclass: RangedSummarizedExperiment, DataFrame, GRanges
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH551"]]' 

          title         
  EH551 | banoSEMeta    
  EH552 | st100k        
  EH553 | st400k        
  EH554 | full_1Mneurons
  EH555 | gr450k        
  EH556 | gtexRecount   
  EH557 | tasicST6      
```
Please update the metadata script as mentioned above as the last commit reverted the "Rda". 
Also I would recommend adding either in the vignette or man (or both) the list of data object with the brief  description so users have an idea of what is available. 

e.q 
```
banoSEMeta:	Metadata RangedSummarizedExperiment shell for banovichSE
st100k:	Metadata RangedSummarizedExperiment shell for 100k cells from 10x genomics 1.3 million neuron dataset
st400k:	Metadata RangedSummarizedExperiment shell for 400k cells range-sorted from 10xgenomics 1.3 million neuron dataset	

etc... 
```
After those changes are implemented, I will accept the package. 
Thank you for making the changes and adapting to ExperimentHub. 
Cheers, 
Lori

**Comment by shwetagopaul92** [comment]
@lshep Hi Lori, I have implemented the required changes. 
Thank you very much!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shwetagopaul92.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"restfulSEData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/restfulSEData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
