### ISSUE TITLE
chromVAR

### ISSUE THREAD

**Issue by AliciaSchep** [Bioconductor/Contributions#499]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GreenleafLab/chromVAR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
DESCRIPTION

- Great!

vignette

- The built vignette does not have a title, author, etc
- The 'master' branch will be mirrored in the Bioconductor git repository; it may not be desired to include the Articles/ folder on this branch.
  
R

- background_peaks.R:30 `apply()` for functions like `sum()` is usually much less efficient than `rowSums()` / `colSums()` (and similar from the matrixStats package; this line could for instance be written as `rowSums(nucfreqs[, 2:3]) / rowSums(nucfreqs)`.

- avoid `1:*` constructs, prefering `seq_len()` or `seq_along()` for robustness. Likewise, prefer `vapply()` to `sapply()` (the latter returning a list() when the iteration is over 0 elements).

- the extreme nesting of code at line cis.R:47 makes this difficult to read; try (there are other examples of conceptually long lines of code that have been wrapped to 80 columns, but remain difficult to read, e.g., clustering.R:35, compute_devaitions.R:148)

    ```
    if (length(chr_ix) > stepsize) {
      idx <- seq_len(length(chr_ix) %/% stepsize)
      tmp <- lapply(idx, function(x) {
        start0 <- (x - 1L) * stepsize
        end <- min(start0 + grpsize, length(chr_ix))
        chr_ix[(start0 + 1L):end]
      })
      names(tmp) <- sapply(seq_along(tmp), function(x) {
          paste(chrs[i], x, sep = "_", collapse = "")
      })

      tmp <- lapply(1:(length(chr_ix)%/%stepsize), function(x) )
    ```

  a line like differential_tests.R:49 can be made more readable with an indentation style like (args on new lines, indented by 4 rather than aligned to opening paren)
  
    ```
          reshaped <- lapply(
              seq_len(nrow(inputs[[1]])),
              function(x) {
                  lapply(inputs, function(y) y[x,])
              }
          )
    ```
    
  but such doubly-nested iterations are likely to be very inefficient -- is there an approach to writing these in a more vectorized fashion, e.g., by representing the primary data in a more 'tidy' format (columns with partitioning)?

- `message(paste())` (also `stop()`, `warning()`) usually do not require `paste()`

- Is now a good time to remove deprecated.R?

- looks like get_annotations.R:164 implements its own BED file  parser; is there a reason not to use `rtracklayer::import()`?

- get_inputs.R:295 the use of `with()` (here and elsewhere) has been made redundant by use of `tmp$...`

src

- Makevars and Makevars.win are the same; delete Makevars.win

- Some of the utility functions, e.g., col_sds, seem like they could be replaced by the robust, tested, and fast `matrixStats::` functions

**Comment by AliciaSchep** [comment]
Thanks for the review!  I will go through the items and address them in the next week.

**Comment by lawremi** [comment]
Too much of the vignette code is unevaluated. There are inconsistencies between the code and text. For example, the code has `getDounts()` while the text mentions the more believable `getCounts()`. Is `get` an informative enough verb there? It's sort of confusing because there's an accessor called `counts()`.  There's also mention of `getMotifs()` but the code has `getJasperMotifs()`.

Is there any advice on getting a set of peaks in the first place? It seems like that's one of the trickiest steps, because every sample will have its own peaks and somehow those need to be resolved to a common set.

**Comment by AliciaSchep** [comment]
@mtmorgan  I have made changes in response to your review:

vignette

* The built vignette does not have a title, author, etc 
**Added title and author to vignette**
* The 'master' branch will be mirrored in the Bioconductor git repository; it may not be desired to include the Articles/ folder on this branch. 
**The Built version of the articles (the docs folder) has now been moved to a separate branch (gh-pages).  The Rmd articles are still in the main branch.  Moving it to another branch would add a lot of complications to how the documentation website made with with pkgdown is built, so I would prefer not to move the articles if possible.  I guess I don't really see why it would be a problem to have those in the Bioconductor git. The only reason those additional vignettes are not included in built package is so that R CMD check doesn't take too long**

R

* background_peaks.R:30 apply() for functions like sum() is usually much less efficient than rowSums() / colSums() (and similar from the matrixStats package; this line could for instance be written as rowSums(nucfreqs[, 2:3]) / rowSums(nucfreqs).
**Made the suggested change**

* avoid 1:* constructs, prefering seq_len() or seq_along() for robustness. Likewise, prefer vapply() to sapply() (the latter returning a list() when the iteration is over 0 elements).
**I have replaced 1: and sapply with the more robust constructs**


* the extreme nesting of code at line cis.R:47 makes this difficult to read; try (there are other examples of conceptually long lines of code that have been wrapped to 80 columns, but remain difficult to read, e.g., clustering.R:35, compute_devaitions.R:148)
**I have tried to improve the readability of this code**

* a line like differential_tests.R:49 can be made more readable with an indentation style like (args on new lines, indented by 4 rather than aligned to opening paren but such doubly-nested iterations are likely to be very inefficient -- is there an approach to writing these in a more vectorized fashion, e.g., by representing the primary data in a more 'tidy' format (columns with partitioning)?
**I have updated the code for differential_tests to be less ugly, with less nesting. I think the new code is more readable, although not more efficient.**

* message(paste()) (also stop(), warning()) usually do not require paste()
**I have removed unnecessary paste in these expressions**

* Is now a good time to remove deprecated.R?
**Sure, I have removed it**

* looks like get_annotations.R:164 implements its own BED file parser; is there a reason not to use rtracklayer::import()?
**I wanted more flexibly with bed format (only require first three columns to be standard). My understanding of the import in rtracklayer is that it expects first 6 columns to be standard bed format**

* get_inputs.R:295 the use of with() (here and elsewhere) has been made redundant by use of tmp$...
**I have removed this redundancy**

src

* Makevars and Makevars.win are the same; delete Makevars.win
**I deleted Makevars.win; was a bit confused as to whether this was needed, thanks for clarification**

* Some of the utility functions, e.g., col_sds, seem like they could be replaced by the robust, tested, and fast matrixStats:: functions
**col_sds was actually never used internally and not exported, so I have deleted it.  row_sds is used within another Rcpp function.  Does matrixStats package have functions for use within C++ code?  If so, would be happy to sub that into the code. I guess I could still substitute the calls to row_sds within the R code with the matrixStats version; let me know if that is desirable. (My slight preference is against it as according to my benchmarking the row_sds function is a bit faster)**

Re comments from @lawremi, I have updated the vignettes to fix the typos and evaluate all the chunks.  I also added more into the vignette on recommendations for the peaks input.

**Comment by lawremi** [comment]
Thanks for addressing the comments. rtracklayer is supposed to only require the first three columns to be standard. The names of the non-standard columns need to be passed via `extraCols`. If that's not working, please file a report.

**Comment by AliciaSchep** [comment]
Thanks @lawremi or clarification on rtracklayer; will update package to make use of that.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/AliciaSchep.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"chromVAR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/chromVAR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
