### ISSUE TITLE
mpra

### ISSUE THREAD

**Issue by lmyint** [Bioconductor/Contributions#510]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hansenlab/mpra

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
Is it really worth having functions for parsing outputs specific to a single publication? Maybe it would be better to create data packages for those two, containing the preprocessed/formatted data. That way, other packages could use the same data.

**Comment by lmyint** [comment]
Thanks for taking a look, Michael. Which functions were you referring to? The only place where we have specific processing for the cited publication (Inoue) is in `inst/scripts` where we create the example data. Otherwise the functions that we export are related to general purpose analysis for any experiment. This is predicated on users to creating the `MPRASet` object themselves though as we explain in the first section of the vignette. We have set it up this way because data from these experiments often come in a series of text files with no prescribed formatting, columns, etc.

**Comment by lawremi** [comment]
Sorry, I meant to post that on a different issue but now I have no idea which one it was, because there are so many in play. I'll delete my comment.

**Comment by mtmorgan** [comment]
Sorry I meant to post these brief comments earlier; your package looks really good, if you can make the changes outlined below in the next few days I will try to add it in time for the release at the end of October.

DESCRIPTION

- provide a more descriptive Description: so that users can figure out the relevance of this package to their needs.

vignettes

- looks good

R

- fit.R:8 use `match.arg(model_type)` for validation

- generally: spend more time validating inputs, especially to top-level functions, to avoid complicated or subtle errors later.

- mpra_set.R:39 the `show()` method seems to be a no-op, remove?

- utils.R:3 using `stop()` with `sprintf()` is redundant; `stop()` does the equivalent of `paste()` internally.

man

- good!

- mpralm.Rd:14 provide some additional detail on need for agreement between dimensions of `object` and `design`.

**Comment by lmyint** [comment]
Hi Martin,
Thank you for the feedback. We have made the changes that you've suggested above, and bumped the version a few times, each without a triggered rebuild. With each push, I see that the webhook has a 404 error, so I'm not sure if something is down with the build system.

The specific changes we made include

- DESCRIPTION: the Description field has been updated to indicate the specific pieces of functionality provided.
- fit.R:8 use `match.arg(model_type)` for validation
- Validating inputs: added checking of object type in several functions and dimension concordance in the functions in `fit.R`
- `show()`: we included information about the existence of barcode information, which is useful to users who want to know if their data may have been aggregated already
- utils.R: updated `stop()`
- mpralm.Rd: expanded description for `design` to detail need for dimension agreements

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lmyint.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"mpra\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mpra

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
