### ISSUE TITLE
chromloop

### ISSUE THREAD

**Issue by ibn-salem** [Bioconductor/Contributions#511]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ibn-salem/chromloop

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ibn-salem** [comment]
Hi @kasperdanielhansen 
this is my first package submission to Bioconductor. Please apologize, if I miss something obvious. I have a question regarding the automatic build on windows. As you can see in the build report, my package "chromloop" passes build and check on linux and OS X but cause errors in R CMD check on windows (tokay1). 
I think the issue is reading of bigWig files using `rtracklayer::import.bw()` in examples, tests and vignette of my package. I learned that `BigWigFile` functions from rtracklayer package are not supported on windows (see `?rtracklayer::BigWigFile`). 
The method implemented in my package depend on reading genomic signals from bigWig files. That's why I don’t like to remove all bigWig related code from test cases, examples and vignette.
What is the best way to proceed?

- Is there way to flag functions that do not work on windows (like `rtracklayer::import.bw`)?
- Or do I have to remove all bigWig related code from examples, tests and vignette to pass R CMD check on windows?

Any hints or suggestions are very welcome!
Thanks in advance,
Jonas

**Comment by kasperdanielhansen** [comment]
Hi Jonas,

Good question. Personally, I know the interface to BigWig in rtracklayer sometimes work on Windows and sometimes not. It makes a lot of sense to build on BigWig files for this application. An advantage of BigWig is that it is easy and efficient to grab a portion of the file on fly.

I would separate parsing and loop construction. And have loop construction functions which can operate on the track from a full genome in memory. That way you only have a dependence on rtracklayer in a few (perhaps only 1) data access functions. This is good design anyway, because you also want to be able to handle data which is not in BigWig. You could then have rtracklayer in Suggests and test for it existence (or for non-windows) in the parsing function.

In addition, it would be nice to have BigWig parsing work dependently on Windows.

What I would do (if possible) would be to separate the reading of BigWig files and the loop construction. Ie. have loop construction functions which builds on the having the entire BigWig file in memory. Or at least can work on everything in memory. You're probably utilizing that you can grab portions of the BigWig file as you go

**Comment by ibn-salem** [comment]
Hi @kasperdanielhansen

thanks a lot for your answer and suggestions! 

I now tried to modify the main workfolow of the package in a way to work independently of bigWig file reading. The user can add ChIP-seq signals to `GRanges` as a `NumericList` object by any means. 

All bigWig related functionality should raise warnings when executed on windows. Furthermore, I modified unit tests and examples in function doc to check if OS is windows before running. 
I will now merge my changes and bump version to see if CMD check passes on windows too.

Thanks again for your help!

**Comment by lshep** [comment]
Could you please push a version bump for your package to trigger a new build?  Thank you.

**Comment by ibn-salem** [comment]
Hi @lshep 
Did it. Seems to trigger a build now. Thanks!

**Comment by vobencha** [comment]
@lshep can you please re-run this one so we get a Windows build?
Thanks.

**Comment by lshep** [comment]
Its on now you should have a new report shortly

**Comment by vobencha** [comment]
@ibn-salem When I visit your GitHub repo I do not see a package named chromloop bur instead I see sevenC. Did you rename the package?

I realize it's been awhile since you first submitted this. Are you still interested in going forward with it? Maybe we need to close this issue (since chromloop no longer exists) and you can re-open a new one for sevenC when you are ready. Let me know what you'd like to do.

Valerie

**Comment by ibn-salem** [comment]
Hi @vobencha 
thank you for looking into it. Yes, I renamed the package from "chromloop" into "sevenC". I would like to submit it again by creating a new issue in the next few days. I close this one now.
