### ISSUE TITLE
(inactive) FastProjectR

### ISSUE THREAD

**Issue by talashuach** [Bioconductor/Contributions#516]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YosefLab/FastProjectR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your vignette must consist of code chunks that are evaluated (i.e., not eval=FALSE).

**Comment by lawremi** [comment]
Needs to be based on SingleCellExperiment.

**Comment by talashuach** [comment]
@mtmorgan The vignette only has one chunk with eval=F. Since that chunk launches a local webserver. Evaluating that when building the Vignette would cause the whole vignette creation to hang. Other than that chunk, all other chunks are evaluated.

@lawremi I added possible input of SummarizedExperiment, which would also support any extending class (i.e SingleCellExperiment). Is that what you meant?

**Comment by talashuach** [comment]
We're getting this warning during the build stage:
** * checking whether package FastProjectR can be installed ... [31s/31s] WARNING
Found the following significant warnings:
  Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE**

I can't figure out how to solve this warning... Any ideas?

**Comment by lawremi** [comment]
Before writing up a formal review, I think we should discuss some of the design decisions. Let's start with why there is an _ExpressionData_ class that is not just a _SummarizedExperiment_. Same thing for _ServerExpression_. Why implement a custom jug-based app instead of one based on Shiny?

Btw, you shouldn't override `initialize()`. Just let the default implementation set the slots. After making that change, no longer encourage the user to call `new()` directly, as it will expose slot and (as before) class name information. Instead, add constructor functions named after the class, e.g., `ExpressionData()`.

**Comment by talashuach** [comment]
@lawremi, thanks for the comments!

1 - jug vs. shiny: FastProjectR is a re-write into R of the existing python-based FastProject, so much of the front-end was already implemented. Translating and expanding the back-end of FastProject was our main focus, we saw no need or clear advantage that justifies translating the Front-end into a shiny app.
2 - overriding `initialize` - the only initialization function that is exported is the FastProject object initializer, which follows what you suggested. Since the other objects (and respective initializers) are not exported, we don't see an issue with exposing anything to the user. Is this a general convention in R development? Should we change this even for internal code?
3 - ExpressionData vs SummarizedExperiment: this is something we've looked into, and may look into again in the future, as there are similarities between the data structures. However - the goals and usage cases are different enough that we decided to stay with a custom container.
SummarizedExperiment, as far as we understand it, is meant to hold elaborate data structures that maintain inter-relationships between the data and corresponding metadata, and allow easy manipulation of both (i.e subsetting the data would also appropriately subset meta-data, etc). 
While this is very flexible and useful in the general case, internally a custom data structure seemed more appropriate. For example: FastProject treats sample meta-data as a type of signature, so these metadata are stored in containers similar to the (internally computed) gene signature scores. These are subsetted accourding to each filter, and each filter-level is normalized separately, so to properly utilize SummarizedExperient we would still need to store several instances of SE objects, each for each filter level. Since we don't use any of the advanced features SE objects provide, we decided this would add unnecessary complexity to the internal code.
We do support SE objects as input, and are considering making that input method utilize all of the object metadata (i.e automatically creating the precomputed signatures from sample metadata). We're not sure this will always fit what the user expects and is interested in, so right now the user needs to provide the precomputed signatures explicitly.

I hope these answers are satisfactory.
Thanks a lot!

**Comment by lawremi** [comment]
> 1 - jug vs. shiny:

Ok, thanks, that makes sense. It is interesting to see a non-Shiny web app.

> 2 - overriding initialize

Yes, I would recommend leaving initialize() alone, even for internal objects. It would simplify things.

> 3 - ExpressionData vs SummarizedExperiment

Ok, thanks for the explanation.

I will dig deeper today.

**Comment by talashuach** [comment]
@lawremi ,
As you suggested, we removed all initialize() overrides and replaced them with regular function calls. Thanks!

Also, do you happen to have any advice on how to solve this warning:
*** checking whether package FastProjectR can be installed ... [36s/41s] WARNING
Found the following significant warnings:
  Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
See /Users/pkgbuild/packagebuilder/workers/jobs/516/b6fae87/FastProjectR.Rcheck/00install.out for details.**?
We could not reproduce this locally...

Thanks, and looking forward to your feedback!

**Comment by lawremi** [comment]
I don't know much about the builds but my initial guess would be that something is trying to use rgl but is failing because the build machine is headless.

**Comment by lawremi** [comment]
# Overall<a id="orgheadline1"></a>

It is interesting to see an R web app not based on Shiny. Given the
complexity of the web app, it is probably wise to split it off from
the fast projection utilities, which are probably generally useful,
beyond the visualizations. There might also be benefits to
integration with the GSEAbase package, since signatures are
involved. The SingleCellExperiment data structure (from the package
of the same name) extends SummarizedExperiment to hold projections;
this package generates projections, so there may be a match.

The code looks like it was copy/pasted from some other language. It
needs to be converted to vectorized, idiomatic R code. The
object-oriented framework is well-engineered at first glance; just
some S4 particulars need to be polished. Overall, the package is
well integrated with Bioconductor.

Something that absolutely has to be fixed is the setting of the
random seed inside of functions like `applyICA()`. The random seed
is used to replicate executions of an analysis, so it is the domain
of the user, not the software. Moreover, it is unnecessary for a
reusable function to have a fixed seed, and it defeats the purpose
of randomness in the first place. This package even sets the seed
globally on load, which is also a terrible idea, for the
aforementioned reasons.

# `DESCRIPTION`<a id="orgheadline3"></a>

## Dependencies<a id="orgheadline2"></a>

-   This package has a lot of dependencies, which in part motivates
    the recommendation to split it into more manageable pieces
-   It looks like the data.table dependency is for fread(),
    presumably for performance reasons. Did you try read.table() with
    colClasses specified? It is weird how read.table() is used for
    reading the column names, and fread() for the data. Since the
    code is loading a matrix, have you tried using `scan(x,
         quiet=TRUE)` and wrapping the vector result up in a matrix (the
    number of columns is figured out separately)? It would be
    interesting to see how that compares.

# `NAMESPACE`<a id="orgheadline4"></a>

-   I recommend importing the functions used from the utils, tools and
    stats packages, because having `utils::` in the code is
    noisy. Those are base R functions; everyone will recognize them.
-   Import generics that override base (or otherwise imported)
    functions, like `Matrix::rowSums()`. Otherwise, the reader might
    think that `Matrix::rowSums()` is a different function from
    `base::rowSums()`, whereas in fact the distinction is somewhat
    artificial. Treat them like the abstraction that they are.
-   Import all of the methods package; the package is using it
    extensively but only currently importing `new()`.

# Vignette<a id="orgheadline5"></a>

This does a good job of showing the user how to run the pipeline and
launch the dynamic report. However, there is no documentation for
how to use the report. Some screenshots + instructions would
help. If there are interesting conclusions to be drawn from the
example data, it would help demonstrate how the user could have
discovered those with the app.

# API<a id="orgheadline12"></a>

## Classes<a id="orgheadline6"></a>

-   Looks like there are many slots which should be of type "integer"
    but instead are of type "numeric" (real values).
-   Could some of the "list" slots be formalized into typed
    S4Vectors/IRanges List classes, e.g., IntegerList? You can also
    easily define lists of high-level objects by deriving from
    SimpleList and setting the `elementType` in the prototype.
-   For TreeProjection, perhaps you could use an igraph data
    structure for representing the tree structure?
-   Classes should have accessors for their slots, in order to
    protect code (both internally and in user extensions) from
    changes in object representation

## Generics<a id="orgheadline7"></a>

-   When defining generics, do not call `{()` in the function
    definition. That causes the methods package to interpret the
    generic as non-standard, which is not the intent.
-   It seems like virtually all of these generics should only
    dispatch on their first argument, yet all arguments are included
    in the signature. Restrict the signature by passing the relevant
    argument names via `signature`.
-   Should `Analyze()` be capitalized?

## Inputs<a id="orgheadline8"></a>

There seems to be a heavy reliance on file inputs. While that makes
sense for standardized gene signature formats, it's not clear
whether it is worth the effort supporting text files for the
housekeeping genes and precomputed signatures.

## `readExprToMatrix()`<a id="orgheadline9"></a>

-   Probably should be named `readExprAsMatrix()`.
-   The `delimiter` argument should be called `sep` for consistency
    with the other reading functions.

## `readHKGToMatrix()`<a id="orgheadline10"></a>

-   Similar comments to `readExprToMatrix()`.
-   Why is this function so complicated when it is just reading a
    single column of gene names? Why return the data as a matrix
    instead of just a vector?

## `FastProject()`<a id="orgheadline11"></a>

-   Does the `filters` argument only support "fano"? If there are
    more, list them in the default value. Also document what they do.

# Code<a id="orgheadline29"></a>

## `readExprToMatrix()`<a id="orgheadline13"></a>

-   Look into `file_ext()` and `basename()` to make things easier.

## `readSignaturesInput()`<a id="orgheadline14"></a>

-   See `readExprToMatrix()` tips
-   The GSEAbase package already supports parsing GMT files. Its data
    structures are designed for reuse; please reuse them.

## Filter functions<a id="orgheadline15"></a>

-   A lot of these would benefit from vectorized routines in the
    matrixStats package. This package already depends on matrixStats,
    but for a function that seems tangential to matrices. There a
    bunch of other places in the code that would benefit from
    matrixStats. Try to get rid of all calls to `apply()`.
-   It is possible to pass `[()` a logical subscript,
    no need for `which()`. No need (and it is dangerous) to call
    `subset()` for that. Evaluate all of the `which()` calls across
    the codebase.

## Object initialization<a id="orgheadline16"></a>

My advice to replace `initialize()` with ordinary functions was in
part motivated by the convenient default behavior of
`initialize()`, which sets all slots passed to `new()`. For
example,

    ServerExpression <- function(data, sample_labels, gene_labels) {
        .Object <- new("ServerExpression")
        .Object@data <- data
        .Object@sample_labels <- sample_labels
        .Object@gene_labels <- gene_labels
    
        return(.Object)
    }

Could become:

    ServerExpression <- function(data, sample_labels, gene_labels) {
        new("ServerExpression", data=data, sample_labels=sample_labels,
            gene_labels=gene_labels)
    }

Please also update the docs, which currently say that the user
should not call these functions directly (left overs).

## Object coercion<a id="orgheadline17"></a>

There are lot of JSON coercions. Consider using a generic, instead
of separate functions.

## `applyMicroClustering()`<a id="orgheadline18"></a>

-   `paste0()` is vectorized, no need to loop
-   The second `lapply()` seems inefficient; why subset the whole
    data just to get the colnames? Probably could use
    `S4Vectors::extractList()` here.

## `louvainCluster()`<a id="orgheadline19"></a>

-   Look into `split()`. This code:
    
        nnl <- lapply(1:nrow(nn), function(i) nn[i,])
    
    Could be:
    
        nn1 <- split(nn, row(nn))
    
    This code:
    
        for (i in 1:length(mem)) {
            n <- as.character(mem[[i]])
            if (n %in% names(clusters)) {
                clusters[[n]] <- c(clusters[[n]], i)
            } else {
                clusters[[n]] <- c(i)
            }
        }
        clusters <- lapply(clusters, function(i) i <- rownames(data)[i])
    
    Could be:
    
        split(rownames(data), mem)
    
    There are other places in the code that would benefit from
    similar treatment.  Also avoid using `[[()` on atomic vectors,
    because it makes no sense to extract an element of something that
    is atomic.

## `merge_intervals()`<a id="orgheadline20"></a>

Should just be `IRanges::reduce()`.

## `getNormalizedCopy()`<a id="orgheadline21"></a>

This should use `switch()`, perhaps in conjunction with
`match.arg()`.

## `Analyze()`<a id="orgheadline22"></a>

-   This function is too long; please break it up into manageable
    chunks.
-   A lot of vectorization has to happen. Note that `ifelse()` is
    vectorized.
-   Why extract all the slots of an object from a list, and pass that
    to a function, instead of passing the object itself? Seems weird
    to break the abstraction like that.

## `saveFPOutAndViewResults()`<a id="orgheadline23"></a>

You could use `tempfile()` to generate a unique filename, but it
seems better to require the user to provide a meaningful name.

## `viewResults,FastProjectOutput()`<a id="orgheadline24"></a>

Look into using `system.file()`.

## `sigEqual()`<a id="orgheadline25"></a>

-   Protect against a non-Signature second argument by specifying the
    type in the method signature

## `registerMethods()`<a id="orgheadline26"></a>

-   Could be just one call to `c()`

## `applyPermutationWPCA()`<a id="orgheadline27"></a>

-   `for()` loops are not needed here. Look into `replicate()`. Inner
    loop is easily vectorized.

## C++ code<a id="orgheadline28"></a>

This looks like it implements KNN classification. That is already
available in the class package. How is this different? One of the
functions modifies its input in place, which is not safe,
particularly for a function exported to R.

# Tutorial on vectorization<a id="orgheadline30"></a>

The code is not very idiomatic R, in that it is not making use of
the vectorized nature of the language. Vectorized code is often
easier to read, and is often faster, thanks to the native
implementation of the loops. Let us take the code for reading the
"txt" format in `readSignaturesInput()`:

    sigList <- list()
    inp <- as.matrix(utils::read.table(filename, sep="\t"))
    
    for (r in 1:nrow(inp)) {
        dat <- inp[r,]
        sigName <- dat[[1]]
    
        if (length(dat) == 2) {
            key <- "none"
            gene <- toupper(dat[[2]])
        } else {
            key <- tolower(dat[[2]])
            gene <- toupper(dat[[3]])
        }
    
        if (sigName %in% sig_names) {
            next
        }
    
        if (sigName %in% names(sigList)) {
            sigList[[sigName]][gene] <- as.numeric(1.0*keys[key])
        } else {
            sigList[[sigName]] <- c()
            sigList[[sigName]][[gene]] <- as.numeric(1.0*keys[key])
        }
    
    }

Constructing an empty list and concatenating an element with each
iteration is going to have quadratic complexity (in principle,
although R is getting smarter about this), since the list needs to
be copied with each addition to preserve copy-on-write (COW)
semantics. We could preallocate the list, but that is not going to
clarify the code at all. Instead, read the data as a data.frame and
operate on the columns as vectors.

    inp <- utils::read.table(filename, sep="\t"))
    colnames(inp) <- c("sigName", if (ncol(inp) > 2L) "key", "gene")
    if (ncol(inp) == 2L) {
        inp$key <- "none"
    }
    weights <- keys[tolower(inp$key)]
    names(weights) <- toupper(inp$gene)
    sigList <- split(weights, inp$sigName)

Sometimes we need an explicit loop, such as when creating the
Signature objects:

    for (sig in names(sigList)) {
        newSig <- Signature(sigList[[sig]], sig, f, "", isPrecomputed=FALSE,
                            isFactor=FALSE, cluster=0)
        sig_data <- c(sig_data, newSig)
        sig_names <- c(sig_names, sig)
    }

Ideally, Signature would itself be a vector/table
of signatures (a *vectorized data structure*), but for now we can
loop using functional iteration:

    sig_data <- mapply(function(sig, sig_name) {
        Signature(sig, sig_name, f, "", isPrecomputed=FALSE,
                  isFactor=FALSE, cluster=0)
    }, sigList, names(sigList))

Stay away from `sapply()` though, as its behavior is not
predictable. Try to remove all occurrences of it.

**Comment by deto** [comment]
Hi @lawremi ,

Thanks for such a detailed review of our package!  There's a lot of lessons here on R development in general and you've given us a lot to think about.

You're correct in your assessment that some of the code is idiomatic for another language.  Most of the methods here were translated from idiomatic Python (the original [FastProject](https://github.com/YosefLab/FastProject), which I authored) into working R, but not all the way into idiomatic R.  

We'll be working on applying as many of these fixes as we can over the next week.  The code has to be locked in by Oct 24th, correct?

**Comment by lawremi** [comment]
Yes, I think that's right. I'm glad the review was helpful.

**Comment by talashuach** [comment]
@lawremi, thanks a lot for the feedback!

Regarding removing explicit calls from stats, utils:
When we import the entire package, as you suggested, we get the following warning from R CMD check:
**checking whether package 'FastProjectR' can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import 'Rcpp::.DollarNames' by 'utils::.DollarNames' when loading 'FastProjectR'
  Warning: replacing previous import 'Rcpp::prompt' by 'utils::prompt' when loading 'FastProjectR'**

Is there a way to avoid this warning? Should we ignore it? 
we don't use any of the replaced functions by either package.

Thanks!

**Comment by mattjones315** [comment]
Hi @lawremi ,

Thank you again for your detailed and diligent review of our package. We've discussed the changes we'd like to make to our package with your reviews in mind and have decided it would be best to work towards the next submission deadline for Bioconductor, rather than rush to get the package ready by the code freeze next week. As such, we'd like to remove our package from Bioconductor's consideration - can you please direct us to how this can be done as quickly as possible? 

Thank you again for your time, consideration, and robust feedback!

**Comment by lawremi** [comment]
Couldn't we keep the issue open, even though they are not targeting this release? I don't want to lose track of the history.

**Comment by mtmorgan** [comment]
When the authors are ready to continue the submission, the issue is re-opened and tagged as under review.
