### ISSUE TITLE
Submission of package GOfuncR

### ISSUE THREAD

**Issue by sgrote** [Bioconductor/Contributions#518]
- Repository: https://github.com/sgrote/GOfuncR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Bioconductor has a long history of providing 'annotation' packages such as GO.db and org.Hs.eg.db. One can also access online resources via biomaRt and similar. Before moderating this package to the review queue, please explain why you do not use these resources or more completely integrate with Bioconductor packages and classes such as GSEABase, ExpressionSet, GOstats, etc.

**Comment by sgrote** [comment]
Hi Martin,
thanks for your suggestions. Regarding the annotations of GO-categories and gene coordinates I will modify the package to use "Homo.sapines" OrganismDb by default, and optionally also take another OrganismDb package. For other species then mouse, rat and human, I could also offer to use the corresponding orgDb package in combination with a TxDb package for the gene coordinates.
Regarding the ontology graph, it would be nice to use GO.db, but GOfuncR uses the GO-enrichment software FUNC in the background which needs the graph in the LEAD database format (http://www.geneontology.org/page/lead-database-schema), namely term, term2term and graph_path. How I understand GO.db works, it seemed rather time-consuming to create those tables from GO.db, compared to having them in the sysdata.
Sorry if I missed something obvious.

Best
Steffi

**Comment by mtmorgan** [comment]
Can you outline how you build the sysdata? I guess there is a script but I do not see it in the package. Also, consider using Organism.dplyr rather than OrganismDb; it is more modern and flexible.

**Comment by sgrote** [comment]
Thank's for pointing me to Organism.dplyr, I did not know it, and it looks very useful. For the moment, however, I am already quite far with implementing the OrganismDb / OrgDb+TxDb variant, and I think it is fine for just extracting GO-annotations and gene-coordinates here. But I'll keep Organism.dplyr in mind for future work.
For the sysdata, I downloaded the ontology from http://archive.geneontology.org/latest-termdb/, loaded term.txt, term2term.txt, and graph_path.txt into R and saved them as /GOfuncR/R/sysdata.rda (using save()).

**Comment by sgrote** [comment]
I just pushed a new version 0.99.1, which now works with OrganismDb, OrgDb/TxDb.
Let me know if you have any questions or suggestions.
Thanks a lot

**Comment by mtmorgan** [comment]
DESCRIPTION & NAMESPACE

- good

vignette

- good
- don't include .Rhistory files in version control

R

- mixing `message()` and `print()` doesn't really make sense; `message()` writes to standard error, whereas `print()` writes to standard output. Messages should be written with `message()`, with the worst-case being `output <- capture.output(print(...)); message(output)`.
- `message(paste(...))` (also `warning()`, `stop()`) can usually be re-written as simply `message(...)`.
- use `seq_along()` or `seq_len()` rather than `1:n`.
- consider a more readable formating for complicated tests at blocks_to_genes.R:131, e.g., 

    ```
    for (i in 1:nrow(test_reg)){ 
        test <- test_reg[i,1] == test_reg[,1] & (
            (test_reg[i,2] > test_reg[,2] & test_reg[i,2] < test_reg[,3]) | 
            (test_reg[i,3] > test_reg[,2] & test_reg[i,3] < test_reg[,3]) | 
            (test_reg[i,2] < test_reg[,2] & test_reg[i,3] > test_reg[,3])
        )
        if (any(test)) {
    ```
- avoid iteration when vectorization possible, e.g., get_child_nodes.R:24 `out[, 1:3] = as.character(out[, 1:3])`.
- the `get_*` functions look highly similar; can they be re-factored to use shared code instead of copy-and-pasting code?

src

- I'm highly skeptical of the need for the volume of C++ code in this package; it is much easier to write buggy C++ code, and of course more tedious to evaluate through a compilation cycle and debug. I guess you've made the investment now...
- now would be a good time to remove 'dead' code (e.g., introduced when debugging or for 'verbose' stages of development.

man

- good.
- be sure to specify argument types, e.g., get_anno_categories.Rd

        \item{genes}{character() vector of...
        ...
        \value{
        A data.frame() with folur columns: gene (character()), ...
        
other

- nice to see unit tests & NEWS

**Comment by sgrote** [comment]
Hi Martin,
thanks for your helpful review. I made the changes you suggested above:

* removed .Rhistory from /vignettes
* removed 'print', also 'paste' in message(), warning(), stop()
* replaced for(... 1:n) with for(...seq_len/seq_along)
* made overlap-test in block_to_genes.R more readable
* use shared code for get_parent_nodes() and get_child_nodes()
* remove some outcommented code and unneeded includes from C++ files
* specify argument types in man-pages

only vectorization seems not to work for conversions (`out[, 1:3] = as.character(out[, 1:3])`), e.g.

`x = data.frame(a=letters[1:3], b=letters[4:6], c=as.character(1:3), d=as.character(2:4))`
`as.character(x[,1:2])`

> [1] "1:3" "1:3"

`as.numeric(x[,3:4])`

> Error: (list) object cannot be coerced to type 'double'

But in that specific case I could avoid the conversion by creating the data frame with `data.frame(..., stringsAsFactors=FALSE)` in the first place.
Let me know if you have further suggestions.

Best,
Steffi

**Comment by sgrote** [comment]
Thank you very much for your help and for adding the package to bioconductor!
Best,
Steffi

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sgrote.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"GOfuncR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GOfuncR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
