### ISSUE TITLE
bnbc

### ISSUE THREAD

**Issue by kasperdanielhansen** [Bioconductor/Contributions#519]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hansenlab/bnbc

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for you submission to Bioconductor.  Please see the following:

- [ ]  [Consider] What about InteractionSet as an existing alternative to ContactGroup?
- [ ]  [Consider] in cg*Apply, use BiocParallel instead of mclapply?
- [ ]  `1:n` --> `seq_len(n)`; see also `seq_along()`
- [ ]  use accessors, e.g., `colData()` instead of slot access, always. sometimes you use your access method and sometimes you object@colData. 
- [ ]  no need to `warning(paste0(ii))` ; warning( ) is sufficient 
- [ ] [Consider] adding a `verbose=FALSE` argument to bnbc() and use to optionally print `cat()`; use `message()` rather than `cat()` to communicate progress; consider using `utils::txtProgressBar()`
- [ ] The man page for the data set is lacking. Please provide more detail on where/how original data was produced.  Also there is no example (even if not run) of working with any sort of raw data to produce the necessary structures for your object. 

Please address or respond to the above comments.  Don't forget to set up the webhook and push a version bump when ready for another review.  The deadline for new packages to be included in the Oct 31 release is next Tue 17. 

Thank you 
~L

**Comment by kasperdanielhansen** [comment]
Comments

> [Consider] What about InteractionSet as an existing alternative to ContactGroup?

We have added a small section in vignette explaining the existence of InteractionSet. As we explain there, we would like to eventually move towards using InteractionSet instead of ContactGroup, but right now we have fast code (including Rcpp-based routines) for manipulating ContactGroup matrices. So besides porting the code we would need to test and possibly fix band access in InteractionSet's which is non-trivial (might not be hard, but non-trivial).

> [Consider] in cg*Apply, use BiocParallel instead of mclapply?
 
In our experience, BiocParallel is not robust, but its been a while since we used it. We are sticking with mclapply for the time being.

> 1:n --> seq_len(n); see also seq_along()

Fixed

> use accessors, e.g., colData() instead of slot access, always. sometimes you use your access method and sometimes you object@colData.

Fixed. We now only used @ in accessors and replacement accessors.

> no need to warning(paste0(ii)) ; warning( ) is sufficient

Fixed

> [Consider] adding a verbose=FALSE argument to bnbc() and use to optionally print cat(); use message() rather than cat() to communicate progress; consider using utils::txtProgressBar()

Done. We added verbose=TRUE and also used txtProgressBar (in case verbose is set).

> The man page for the data set is lacking. Please provide more detail on where/how original data was produced. Also there is no example (even if not run) of working with any sort of raw data to produce the necessary structures for your object.

We have expanded on the man page. For the raw data the issue is that there is no standard Hi-C data format, but a lot of custom variants. We have added a section in the vignette giving an overview on how to get the data into R; this is what we do currently and it does involve manually parsing various matrix files. Until the Hi-C community gets their act together it is hard to see how to make substantial progress here. This will however happen soon I think.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kasperdanielhansen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"bnbc\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bnbc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
