### ISSUE TITLE
RGMQL

### ISSUE THREAD

**Issue by Sim1Pall8a** [Bioconductor/Contributions#524]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DEIB-GECO/RGMQL

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Sim1Pall8a** [comment]
Hi,

This package need a manual installation of specific version of scala (2.11.8) and javaSE 8 and settings for JAVA_HOME and SCALA_HOME as environment variable for working correctly.
how can I specify additional settings to be performed as a pre-install phase?

**Comment by lawremi** [comment]
Bioconductor already offers this functionality in terms of SummarizedExperiment, RaggedExperiment, MultiAssayExperiment, GenomicRanges, etc. This API is not idiomatic from the R perspective, and has problematic dependencies on Java/Scala. So I'm worried that users will struggle to integrate this with their workflows. It would be great to see a scalable compute engine _underneath_ our existing APIs.

**Comment by marcomass** [comment]
@lawremi 
Thank you Michael for your fast answer. Can you elaborate it a bit more to better clarify it to us?

The RGMQL package has the aim to make available to R/Bioconductor users the powerful functionalities of GMQL (http://www.bioinformatics.deib.polimi.it/GMQL/), an innovative query language (as simple as SQL, but applicable to genomic data and metadata in text files) which allows through simple scripts the processing and evaluation of genomic region data of interest from big data of typically Next Generation Sequencing experiments. 
Thanks to the new API of GMQL, the RGMQL package enables the user to apply the powerful GMQL functionalities through simple statements, either on data on user's computer or on a remote cluster where GMQL is installed (we provide public access to such a cluster, where public data from ENCODE and TCGA are available to be processed by GMQL). Furthermore, thanks to RGMQL, GMQL computation results are seamless provided within typical R structures (GRanges) for their easy management and processing with all the many function available in R.  
To the best of our knowledge the functionalities that RGMQL offers are not currently available in Bioconductor. 

Being developed for cloud computing, GMQL API are coded in Scala; for this reason we used the Rscala package and some settings listed above; if they are not idiomatic from the R perspective, please support us in how changing them to make the RGMQL package conform to Bioconductor.
Other packages that use java libraries have been recently accepted and made available in Bioconductor.
Thank you.

**Comment by lawremi** [comment]
It would be good to clarify, e.g., in the vignette, what this does offer beyond the current capabilities in Bioconductor. Regardless, GMQL needs a better embedding in R. For example, the `select()` function is going to conflict with the widely used dplyr package, and passing the expression as a string in another language is obviously not idiomatic. The cryptically named `extend()` function seems analogous to `stats::transform()` or `dplyr::mutate()`. Etc.

A general problem with GMQL after my cursory inspection is that the flat structure of the data model makes it unclear whether the data are being restricted by sample, feature, or assay. It's important to carry those semantics through the API.

**Comment by marcomass** [comment]
Sure, we can follow your advice and improve the package, but we would like before to solve the issues of the dependencies which prevent passing the automatic checking (particularly in windows environment). If these are not overcome, there is no point in working on the others.
Can you help us to solve them?
Thanks a lot.

**Comment by Sim1Pall8a** [comment]
Hi @mtmorgan @LiNk-NY @lawremi 

We completely revised our initial submitted RGMQL package solving all the previously present issues and addressing your comments following your advices. In particular, we:
1) removed all previous needs of manual installation or environment variable settings by using the rJava package instead of the rScala one
2) provided better embedding of GMQL operators in R, through best possible support of idiomatic R syntax
3) completely rewrote RGMQL vignette, clarifying the purpose, used data model structure and unique features of the RGMQL package, which enables the seamless use in R/Bioconductor of the powerful GMQL functionalities and provides GMQL computation results directly within typical R structures (GRanges) for their easy management and processing in R/Bioconductor. Particularly, GMQL allows processing and evaluation of genomic region data of interest from big data typically of Next Generation Sequencing experiments, taking advantage of cloud computing technologies and running either on user's computer or on a remote cluster where GMQL is installed (we provide public access to such a cluster, where public data from ENCODE and TCGA are available to be processed by GMQL). 

We are waiting for your kind revision of our last submitted package version.

4) The present warning regards the size of the included jar file. In the previous submission of the package, such jar file was already about 100 MB and it passed the previous Biocheck version 1.13.2. Now the BiocCheck version is 1.14.0 and it gives the following size warning: 
WARNING: The following files are over 5MB in size:
      'inst/java/GMQL.jar'  
Is there a way to overcome this limitations? Or is there any practice we can apply to limit overall size?

**Comment by lawremi** [comment]
Thanks for making some efforts. Many of my previous comments still stand. Bioconductor users want to use Bioconductor APIs. I think RGMQL has the potential to do two things: (1) provide a scalable cloud-based implementation of Bioc data structures and (2) potentially extend the Bioconductor API with some new operations. But it has to be an implementation and extension of what is already there. You should really look into the GenomicRanges and dplyr packages and think about how GMQL can be _embedded_ into their language, rather than introducing conflicts. 

Just to make this concrete, you should do things like change `select()` into a method on `subset()`. Instead of `map()`, look into maybe a method on `mapToTranscripts()`. Instead of defining your own non-standard `order()` function, define a `sort()` method for it instead, supporting the `by=`  argument as introduced by S4Vectors. That sort of thing.

**Comment by Sim1Pall8a** [comment]
@lawremi 

My apologizes, it's bit hard to understand what you exactly are requiring.

For example you say I should use "native" subset() instead of my select as users are accustomed to use it in other packages.
So I'm exploring this solution:

a) after initialize GMQL i usually execute

r = read_dataset(<param>)
so r is an object that represent my data (even if is not a standard R object )

b) I extend the base function subset as you suggest in this way, as specified in http://adv-r.had.co.nz/S3.html:

mean <- function (x, ...) {
   UseMethod("mean", x)
 }
mean.numeric <- function(x, ...) sum(x) / length(x)
mean.data.frame <- function(x, ...) sapply(x, mean, ...)
mean.matrix <- function(x, ...) apply(x, 2, mean)

c) in my case I'll do something like that:

subset <- function (x, ...) {
   UseMethod("subset", x)
 }

subset.GMQLClass <- function(<my_param>) {
	my_select(<my_param>)
}
note that in this case the result of the call of the "overloaded" will be my GMQL class object that "holds" the data: this object can be passed to other "remapped" functions that will behave in a similar way

Am I on the right way? or am I completely wrong? 
thanks in advance

**Comment by lawremi** [comment]
You are on the right track. `subset()` is already an S3 generic. But you should use S4, not S3. We have the S4 generic defined in BiocGenerics, so you can just import that. You should think about having your GMQLClass (probably best called GMQLDataset or something) derive from the DataTable class in S4Vectors. I haven't looked into whether that would make sense or not but it's worth considering. It would take care of `subset()` for you, as long as low-level hooks were implemented.

**Comment by Sim1Pall8a** [comment]
Hi @lawremi 

I "wrapped" my function to GMQLDataset methods following your suggestion.
I found functions in some packages thaat closely resemble my functionalities, so I used the same names in my R package.
I would appreciate if you want to give a view to check and tell me if it correct and what is necessary to do, 
Every seggugestion about naming will be gladly accepted especially about the "ancillary" class object (ALL, BAG, COUNT, SUM, MIN, ASC, DG, and so on... ).
I know that R already defines some of these functions but they also perform the real operation.
let's make it clear with an example:

consider my "extended function (become mutate now)
res = mutate(exp, list(RegionCount = COUNT(), MinP = MIN("pvalue")))

in this case MIN("pvalue") have not to perform operation as :
1. first param is a string 
2. must notify GMQL scala API that 'I'm using MIN with pvalue

same applies to COUNT even if it is not take any input.

Any suggestion about handling these.. will be really appreciated
Thanks

**Comment by lawremi** [comment]
Thanks for making these improvements. There is a base R function called `transform()` that has the same semantics and syntax as `mutate()`. Both `transform()` and `mutate()` work via non-standard evaluation, i.e., they specially compute on the expressions of the passed arguments, like lisp macros. There are some problems with NSE, and I wouldn't recommend going that route if there weren't such a precedent. This new design is problematic because it is similar to existing APIs, but not the same, so it will lead to confusion. I don't think there's any benefit to naming the function `mutate()` if the rest of the syntax is different. I think your approach is interesting though. By capitalizing the function names and relying on strings for column names, you have approached the simplicity of dplyr without using NSE. A simple improvement would be to take the arguments from `...` instead of through a list argument, that would enable:
```
res = mutate(exp, RegionCount = COUNT(), MinP = MIN("pvalue"))
```
That's still quite different from `dplyr::mutate()` and `transform()`, so I think you'll need to use a different name for the function. I'm not a big fan of the `extend()` name though. Relational algebra would suggest `project()`, another suggestion is `tform()`. The other option of course is to move to NSE.

**Comment by marcomass** [comment]
Dear @lawremi
Thank you for the fast interaction and the suggestions. We understand the issue of avoiding misunderstanding through the use of names that are used already in other R/Bioconductor packages for different, although similar, purposes or with different implementations. There are so many useful packages that it is very difficult to avoid such possible conflicts. 
We designed the original GMQL functions having well in mind the relational algebra operations; one of the main authors of GMQL is Stefano Ceri, who is well known worldwide in the database community and who previously gave a lot of contributions to that community. 
Although partially resembling linear algebra, GMQL has typical unique features, also related to the processing of both genomic region data and metadata in the cloud, that guided us also in the naming of its operators. 
If here the main issue is avoiding misunderstandings, do you think that it could be fine changing the name of all RGMQL functions that represent GMQL operations by prefixing them with "GMQL" (i.e. GMQLextend())?

**Comment by lawremi** [comment]
It's not really about avoiding conflicts. It's about unification with existing R notions and being an extension of those. I realize that GMQL is its own language, and that there is a tension between consistency with GMQL (a direct embedding of the language) and consistency with R. I think RGMQL's users will consist almost entirely of those familiar with R but not GMQL, which is why I've been pushing for consistency with R. GMQL could be a backend of dplyr, with some extensions. But I've been suggesting more of a compromise. I think a lot of progress has been made so far. 

I also suggest citing Bioconductor's SummarizedExperiment data model, which is very similar to that of GMQL. That's another potential integration point.

**Comment by Sim1Pall8a** [comment]
Hi @lawremi  @LiNk-NY 

I completed the process of "wrapping" my GMQL functions into S4 fashion, I hope.
I would appreciate if you want to take a look.

In the last report 
http://bioconductor.org/spb_reports/RGMQL_buildreport_20171117095112.html

I found a blocking error and two warnings I would like to fix to allow submission.

the error is 
ERROR: dependency rJava is not available for package RGMQL

but on the previous report http://bioconductor.org/spb_reports/RGMQL_buildreport_20171018035622.html

it worked fine. 

The first warning is about the R version dependency from 3.4.2 to 3.5.
the second is about the size of jar > 5MB

I would like to fix these issues.

Thanks in advance for assistance

**Comment by lawremi** [comment]
Please use generics from BiocGenerics/S4Vectors/IRanges where they match, and make sure the formals match up. For example, `aggregate()` has formal arguments `(x, ...)` not `(data, ...)`. `merge()` is the R equivalent of `join()`.  You should support `subset()` if you already support `filter()`.  dplyr uses `collect()` instead of `materialize()`.

**Comment by Sim1Pall8a** [comment]
I have already moved to generics for the following functions:
GMQL ----------> R
union ---------->union
difference------>setdiff
select---------->filter
project-------->subset
order ---------> sort
materialize -----> collect, as you suggest 
extend --------> extend

I use `subset` for GMQL `project` since project reminds the SQL projection (π) and I think R `subset` the nearest match in R to extract "columns".

You suggested to use `project` in place of `extend`, so I guess the use of `project` name is fine.
In this way I can use `subset` to implement GMLQ select , and `project` for GMQL "project".

the following mapping remains outstanding:

cover---------> cover
map ----------> map
merge -------> ???
join-----------> join

let's proceed with order:

- "cover" could be overridden by `findbyOverlap` present in other packages, but `findbyOverlap` works on two objects, while  my "cover" works on one object, a dataset:  
Do you think using `findbyOverlap` can be misleading or can be the right choice?

- You suggest to use `mapToTranscripts` instead of  my "map", but I think `mapToTranscripts`  is too specific compared to mine, while  my "map" computes also aggregates.
I think is better to keep "map" or alternatively rename it mapTo()., for example.

- `merge` is probably the right choice for my "join" but GMQL has already a "merge" verb so we will generate a conflict. 
Since my "join" resembles "SQL join", we decided to use that name. 
My "merge" is more like R `combine`:  as my "merge" logically takes many samples (even if it syntactical accepts one parameter, a dataset) and produces a sample, but of course the syntax is different respect to R.

PS
did You read my other two questions about submission errors?
( report it below for your convenience):
http://bioconductor.org/spb_reports/RGMQL_buildreport_20171117095112.html

**Comment by lawremi** [comment]
`subset()`, like `filter()`, restricts by rows. There is a `select` argument that selects columns. In dplyr, there is a separate function called `select()`, so the mapping should be `select`->`subset()`/`filter()`, `project`->`select()`(and `select=` arg to `subset()`). I think it's probably a good idea to map `join` to `merge()`. The other stuff seems OK. Your `merge` could probably become the base R `aggregate()`.  It looks like you've already made that change? The `cover` operation is similar (in the feature reduction sense) to stuff in the RaggedExperiment package.

**Comment by lawremi** [comment]
Wanted to add two things:
1. Someone else will need to help with those errors. My role is just as a heckler.
2. Thanks for your diligence in making this accessible to R users. The R/Bioconductor community will appreciate it, and GMQL will gain popularity as a result. Now back to heckling.

**Comment by Sim1Pall8a** [comment]
Hi @LiNk-NY 

Could you please verify the change that I've made? and tell me how to fix errors and warnings message rose on the report?

Thank you for your assistance

**Comment by LiNk-NY** [comment]
Ciao Simone, @Sim1Pall8a 

I will ask Lori @lshep to have a look at what is going on. 
You don't have to worry about it on your end. 

Thanks Michael @lawremi for all the useful feedback ! 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Simone, 
I got an error when checking the package (`RGMQL 0.99.36`) locally. 
```
* checking examples ... ERROR
Running examples in ‘RGMQL-Ex.R’ failed
[truncated...]
join_data = merge(TSS, HM, 
+ genometric_predicate = list(list(MD(1), DL(1200))), DF("provider"), 
+ region_output = "RIGHT")
Error in gmql_join(ptr_data_x, ptr_data_y, genometric_predicate, joinBy,  : 
  All elements should be DISTAL object
Calls: merge -> merge -> .local -> gmql_join
Execution halted
```
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Simone, @Sim1Pall8a 
After a quick look at the package, it looks like you're still defining the generics instead of importing them from other packages as suggested by Michael. Please use the `@importFrom` directive to import the generic. 
Best,
Marcel

**Comment by Sim1Pall8a** [comment]
Hi @LiNk-NY 

Thank you for worrying about the rJava error.

I fixed the example error above and soon I will push a new build.

I've already discuss with Michael about the "mapping".

Of course I defined some generics, as some function are not "cover" by any package (`take`, `cover`, `map`, `extend`)

`filter`, `select`, `collect`, `arrange` are functions of dplyr package and they are not defined as generics, how can I set a methods without generics? 

Thanks, 
Simone

**Comment by LiNk-NY** [comment]
Ciao Simone, 

Thank you for making changes to the package.
I was looking at the warning message about the  `jar` file. It does seem pretty big. 

I consulted with one of our team members and his suggestions was: 
Is there any way you can reduce the size of this file and call it `GMQL-lite.jar`?
Perhaps you may not need everything in the file. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Simone, @Sim1Pall8a 
Thank you for your submission to Bioconductor. Please see the review below. 
@lawremi Please chime in with additional comments / suggestions. 

Regards,
Marcel 

---
# RGMQL #524

The RGMQL package ports the GenoMetric Query Language
into R. We acknowledge that this is a big undertaking and
will certainly be useful. Special care should be taken
of the implementation details as there is potential for other
packages to build on the language.

## DESCRIPTION

* Please shorten the `Description` field for readability.

## NAMESPACE

* It seems like you're exporting many functions that might
not be necessary for end users (e.g., `DF`, `EX`, `FN`)

## R

* Please avoid repetition for functions such as `FN`, `EX`,
`DF`. They all appear to be doing the same thing but with
a different value name.
* Avoid the use of `@` calls. Please create a accessor function
to extract values from the `GMQLDataset` class.
* For `gmql_join` helper function and others, it looks like you
should use `if (!output %in% c("CAT", ...))`
* Set default values where appropriate (e.g., `num_fetch = 0L`)
* Be a bit more specific with function names for example, use
`read_GMQL` instead of `read_datset`
* Avoid using `1:n` sequence generation, use the more robust
`seq_len` or `seq_along`
* Avoid name collisions with R functions such as `data` and `c`
* For some functions, you can use the S3 generic to dispatch on
the `GMQLDataset` or Aggregate class (e.g., `max.GMQLDataset`).
It looks like you're using only regular functions 


### Minor

* `length(x) == 0` is the same as `!length(x)` and
`length(x) >= 1` is the same as `length(x)` when evaluating
with `if`
* Avoid the use of `sapply` use `vapply` for predictable and
robust code
* Use `file.path` for creating paths
* You can use `\n` line breaks in warning messages.

## vignettes

* Rename vignette file to `RGMQL-vignette.Rmd` or similar. Use a meaningful
title in `%\VignetteIndexEntry{}`
* No need to use `eval = TRUE`. Chunks are evaluated by default.
* Consider creating a "quick start" vignette for beginner users with
basic commands to get started using `RGMQL`

## inst

* As mentioned previously, reduce the size of the `jar` file, if possible.
* Add updates to `NEWS` file

**Comment by lawremi** [comment]
I of course agree with this review. Obviously, integrating something like GMQL with R/Bioconductor is not a simple task. I think we've made enough headway though to accept the package after those comments are addressed.

**Comment by Sim1Pall8a** [comment]
Hi @LiNk-NY


1) The jar file could be a problem.
I've already tried to reduce the size of the `jar` with no success
I've seen the package `Onassis`, already available in Bioconductor, that use an external package containing only the jar file (`OnassisJavaLibs`)
I wonder if it is possible to follow the same idea as in `Onassis` package


2)  As the changes made to`RGMQL`, we would like to change the name into `BiocGMQL`; of course the code will be the same.

**Comment by LiNk-NY** [comment]
Hi Simone, @Sim1Pall8a 
1. Yes, this is a possibility. Perhaps you can call it `RGMQLlib` or similar. 
2. Changing the name of `RGMQL` requires effort on both sides. We would have to change 
the issue tracker back-end to coincide with the new name. My inclination is to leave it as is 
since it already works quite well. 
Best,
Marcel

**Comment by Sim1Pall8a** [comment]
Hi @LiNk-NY 

I created a new repository with only RGMQL jar files.
I think the submission procedure is the same of any R package, right?

Waiting for your confirmation, best regards 

Simone

**Comment by LiNk-NY** [comment]
Hi Simone, @Sim1Pall8a 
Yes, I had a look at it and made one minor comment. 
It looks ready to go.

Have you made changes to `RGMQL` according to the review? 

Thanks,
Marcel

**Comment by Sim1Pall8a** [comment]
Hi @LiNk-NY 

Thank you.
Not yet. 
1. I need to reduce the `description`
2. I need to use `file.path`

About the last point of R section of review (the S3 generics):

All the S3 functions (are not and) cannot be dispatched on GMQLDataset but only on character so I can not satisfy the request.

**Comment by Sim1Pall8a** [comment]
ok i reduced the description and used file.path

**Comment by LiNk-NY** [comment]
Hi Simone, @Sim1Pall8a (cool handle btw :)

Thank you for making those changes.
Your package has been approved. Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by Sim1Pall8a** [comment]
Hi @LiNk-NY 

Thank you for accepting the package.
I am working on small fixes and minor upddates to code and docs, that will be released soon.

**Comment by LiNk-NY** [comment]
Hi Simone, @Sim1Pall8a 

Please send those in as soon as possible. 

Regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Sim1Pall8a.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"RGMQL\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RGMQL

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
