### ISSUE TITLE
pcxnData

### ISSUE THREAD

**Issue by BioSok** [Bioconductor/Contributions#526]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hidelab/pcxnData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vobencha** [comment]
Assign to self.

**Comment by vobencha** [comment]
@BioSok go ahead and add the software package as described in
https://github.com/Bioconductor/Contributions#submitting-related-packages

**Comment by BioSok** [comment]
AdditionalPackage: https://github.com/hidelab/pcxn

**Comment by BioSok** [comment]
AdditionalPackage: https://github.com/hidelab/pcxn

**Comment by BioSok** [comment]
https://github.com/hidelab/pcxn

**Comment by BioSok** [comment]
AdditionalPackage: https://github.com/hidelab/pcxn

**Comment by BioSok** [comment]
Dear @vobencha , 

I have the pcxn package ready but it seems that the old (combined) pcxn package is already in your tracker, therefore I cant add this new software pcxn package. How can I remove the old package from the tracker?

-Sokratis

**Comment by BioSok** [comment]
AdditionalPackage: https://github.com/hidelab/pcxn

**Comment by vobencha** [comment]
Did you remove the webhook from pcxn when you closed the old issue?

**Comment by BioSok** [comment]
Yes. I even deleted and remade it with the same name.

**Comment by vobencha** [comment]
@lshep can you help us out? @BioSok had this previous submission:
https://github.com/Bioconductor/Contributions/issues/501

We decided to break the original submission  into a data and software package. AFAIK, the approach is to submit the data package, get a clean build, then add the software to the same issue. The software package has the same name as the original issue and we keep getting this error:

https://github.com/Bioconductor/Contributions/issues/526#issuecomment-335796673

Thoughts? Direction?
Thanks.
Val

**Comment by lshep** [comment]
This had to be corrected on our end.  I have manually pushed a build and you should receive a report shortly.  Please ensure the webhook is re-established for updates.

**Comment by vobencha** [comment]
Thanks @lshep .

**Comment by BioSok** [comment]
Thank you @lshep ! I re-established the web-hook for updating through github. The present error is the one I got previously and posted in Bioc-devel: 

> Hi all,
>Today I submitted a new package called "pcxn" in bioconductor and I got the following Abnormal built >result:
>
>Warning in fun(libname, pkgname) :
>  no display name and no $DISPLAY environment variable
>
>Error: processing vignette 'usingPCxNdb.Rnw' failed with diagnostics:
> chunk 4 (label = pcxn.network) 
>Error in structure(.External(.C_dotTclObjv, objv), class = "tclObj") : 
> [tcl] invalid command name "font".
>
> The pcxn.network function uses igraph::tkplot to return a network, which works every time on several > local machines. After searching for a while it seems that whenever this problem arises its because of  > the igraph package installation. How can I deal with this? Thanks in advance.

To which I got the answer (from Shepherd, Lori):

>Yes, this seems to be a problem on our side. We are looking into it. For now you can ignore this ERROR.  
>There was a similar post here: 
>https://stat.ethz.ch/pipermail/bioc-devel/2017-September/011773.html

As a temporary solution I can comment the problematic line in man files and vignette.

**Comment by lshep** [comment]
Yes. This ERROR is a problem on our end and we are still in the process of coming up with a solution so please ignore for now.

**Comment by BioSok** [comment]
Dear @vobencha ,

regarding the pcxn package, my builds come out with various errors although they are clear in my local checks and biocChecks. In windows it fails to locate the 'texi2pdf' output file for my vignette. In the other two servers it cannot find my datasets (again this doesnt happen in my local checks, biocChecks). Thanks for any advice on that.

-Sokratis

**Comment by vobencha** [comment]
Hi,

I've done a first review. A few comments and suggestions below. The deadline for getting into BioC 3.7 is Tuesday, Oct 17.

Data package:

1) Now that we've moved from svn to git you no longer need the external_data_store.txt file. Please remove it.


Software package:

1) When you define S4 methods you should fully import the methods package in the NAMESPACE, e.g.,
import(methods)

2) Description in DESCRIPTION

This description does not sound like a software package:

Description: PCxN database contains correlation coefficients and p values between pre-defined gene sets within MSigDB H hallmark gene sets, MSigDB C2 CP (Canonical pathways), MSigDB C5 GO BP gene sets and Pathprint respectively.

3) Please remove LazyData = true. In our experience this has only caused problems.

4) function names

You have a mixture of dots and underscores in the function names. Historically the dot '.' in R indicates an S3 method. The part before the dot is the method and the part that follows is the object type. For example,

> summary.
summary.aov         summary.Date        summary.glm         summary.matrix      summary.proc_time   summary.stepfun
summary.connection  summary.default     summary.lm          summary.POSIXct     summary.srcfile     summary.table
summary.data.frame  summary.factor      summary.manova      summary.POSIXlt     summary.srcref  

I think it's confusing that your functions are name in this fashion: pcxn.explore, pcxn.analyze, etc. Your pcxn.obj class is an S4 class, not S3. Please rename the functions to have just underscores or camelCase.

5) Please consider naming pcxn.obj to just pcxn. This name is somewhat awkward and redundant.

6) Why the \dontrun on /pcxn.obj-class.Rd?

7) Why not have a constructor for the pcxn-obj class? If this were named pcxn the constructor would just be pcxn().

Valerie

**Comment by BioSok** [comment]
Dear @vobencha ,

I have implemented the following based on your comments/suggestions:

Data package:
1. File external_data_store.txt file removed.

Software package:
1. Now using import(methods) in NAMESPACE.
2. Description updated, along with other pieces of documentation.
3. LazyData = true, removed.
4. Changed the function names to only use underscores.
5. pcxn.obj renamed to pcxn.
6. Updated example in pcxn-class.Rd?
7. Encountered problems with constructor pcxn(). List representation was not accepted by the constructor so I had to retain the use of new.

Generally, both packages had this error on the Windows server:

>Error in find_vignette_product(name, by = "texi2pdf", engine = engine) : 
  Failed to locate the 'texi2pdf' output file (by engine 'utils::Sweave') for vignette with name 'usingpcxnData'. The following files exist in directory '.': 'Rplots.pdf', 'usingpcxnData-concordance.tex', 'usingpcxnData.Rnw', 'usingpcxnData.tex'
Calls: <Anonymous> -> find_vignette_product
Execution halted

-Sokratis

**Comment by BioSok** [comment]
Dear @vobencha ,

I fixed everything in both packages and they now are in the OK state. However, I had to comment out the the line that causes the problem I have mentioned previously (since this problem is not on my side):

>Error in find_vignette_product(name, by = "texi2pdf", engine = engine) :
Failed to locate the 'texi2pdf' output file (by engine 'utils::Sweave') for vignette with name 'usingpcxnData'. The following files exist in directory '.': 'Rplots.pdf', 'usingpcxnData-concordance.tex', 'usingpcxnData.Rnw', 'usingpcxnData.tex'
Calls: -> find_vignette_product
Execution halted

I hope we are able to meet the deadline!

Regards,
Sokratis

**Comment by llrs** [comment]
Dear @BioSok, I found your package interesting. However I couldn't manage to understand how the correlations are calculated between the pathways. Has the data the expression levels to correlate between gene sets or how is this correlation calculated? Many thanks

**Comment by vobencha** [comment]
@BioSok yes, I understand about the texi2dpf error. Thanks for making the changes - the packages are approved.
Valerie

**Comment by BioSok** [comment]
Hi @llrs , 

Sorry for the delay. In short we are using partial correlation between the pathways! The relevant paper is under re-submission at the moment but here is the abstract:

> A goal of genomics is to understand the relationships between biological processes. Pathways contribute to biological processes through complex but poorly understood interactions. Although understanding of these interactions is essential, only limited functional references for global pathway relationships exist. Pathway annotations from databases such as KEGG, Reactome and Biocarta provide means to analyze biological processes in genomic data. However, pathway based methods describe pathway relationships limited to a specific context. For instance gene set enrichment methods between individual pathways and phenotype comparisons. Other approaches describe pathway relationships by simple overlap, linking pathway annotations that have genes in common, or based on a single experiment. We have addressed global understanding of functional interaction between pathways by systematically quantifying coexpression relationships between 1,330 canonical pathways from the Molecular Signatures Database (MSigBD) to establish the Pathway Coexpression Network (PCxN). We estimated the correlation between canonical pathways across a diverse collection of expression data from 50,277 human microarrays in 863 experiments from the Gene Expression Omnibus. PCxN accounts for shared genes between annotations to estimate significant correlations between pathways with related functions valid in a broad context rather than with high content similarity. PCxN provides novel insight into mechanisms of complex diseases. To better understand pathways linked to known Alzheimer’s Disease (AD) genes, we retrieved pathways significantly correlated with an expert curated Alzheimer’s disease (AD) gene list. These pathways were significantly enriched for genes independently associated with AD. PCxN complements the results of gene set enrichment methods by revealing relationships between enriched pathways and finding additional pathways correlated with enriched pathways. PCxN revealed a cluster of pathways involved in angiogenesis and hypoxia inducible factors, and connections with pathways from the extracellular matrix in the enrichment results from an AD expression profiling study. PCxN provides a powerful framework for interrogation of global pathway relationships. Comprehensive exploration can be performed at PCxN at http://pcxn.org:8080/.

Following that I can see that you are involved with the BioCor package which interests me. May I ask if in that package the correlations are by gene identity or co-expression?

Regards,
Sokratis

**Comment by llrs** [comment]
Thanks, now I understand it better. PCxN needs expression data to perform the exploration between pathways (and the pathways/gene sets definition, of course).

In BioCor the "correlations" (Maybe would be more accurate to say co-occurrence)  are by gene identity. Based on the pathways where the genes play a role a similarity (derived from the Dice similarity) is calculated. In the vignette I explain how to use this similarity with other similarities like the ones calculated with GOSemSim or derived from co-expression via WGCNA (and maybe  in the future with this package).

**Comment by BioSok** [comment]
Indeed you are correct @llrs . Thank you for the info about BioCor! In case you need to contact me in the future you can find my email in my github profile (since this issue will be closed soon I suspect).

Cheers,
Sokratis

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BioSok.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"pcxn\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pcxn

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BioSok.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"pcxnData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pcxnData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
