### ISSUE TITLE
scFeatureFilter

### ISSUE THREAD

**Issue by gdevailly** [Bioconductor/Contributions#527]
Hi, 
I wish to submit the following package to Bioconductor:

- Repository: https://github.com/gdevailly/scFeatureFilter

It is my first R package, I apologize for all the silly mistake I may have left uncorrected.
Many thanks for your time,

Guillaume

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by gdevailly** [comment]
Just to be sure I understand the process correctly:
At this step, I just need to wait for the reviewer comments?
Thanks,
Guillaume

**Comment by hpages** [comment]
Hi @gdevailly,
Thanks for your submission. I'll have a look at the scFeatureFilter package in the next couple of days.
H.

**Comment by gdevailly** [comment]
Great! Many thanks @hpages  :)
Guillaume

**Comment by hpages** [comment]
Hi @gdevailly,

I finally got a chance to look at scFeatureFilter. Please accept my apologize for the delay.

The package looks good and is almost ready for inclusion to Bioconductor. Only a couple of minor cosmetic issues with the vignette. See below.

Thanks,
H.

- The title of the vignette doesn't appear in the rendered (HTML) version.

- Same for authors and date.

- Please do not encourage your users to install scFeatureFilter from GitHub. Installing Bioconductor packages from GitHub is almost always a source of trouble and confusion. The standard and highly recommended way to install a Bioconductor package is with `biocLite()`. See https://bioconductor.org/install/

**Comment by gdevailly** [comment]
Hi @hpages 

Thanks for your time!

I updated installation instructions. I'm not quite sure why title and author informations were missing?
I definitely see them in my copy of the vignette. I will investigate more if you found them still missing.

I'm not quite sure what the "Version Bump Required" label means? Do I have to do anything about it?

In any cases, please do not work on this package review during the end of the year break!

Guillaume

**Comment by hpages** [comment]
Hi @gdevailly,

I see the title and author information in the HTML vignette now. Not sure why that didn't show up last time I built the vignette with `R CMD build`.

I see you bumped the version but that didn't trigger a new build and the "Version Bump Required" label remains. Not sure why. @lshep Do you know why this is happening?

I'm labeling the package as accepted. Happy new year!

H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gdevailly.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"scFeatureFilter\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scFeatureFilter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by gdevailly** [comment]
Great news, thanks @hpages & @mtmorgan !
