### ISSUE TITLE
esATAC

### ISSUE THREAD

**Issue by wzthu** [Bioconductor/Contributions#529]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wzthu/esATAC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by wzthu** [comment]
Hi @mtmorgan, 

I renamed [ATACFlow #505 ](https://github.com/Bioconductor/Contributions/issues/505) as this package(ATACpipe)  following @hpages 's suggestion. 

Best,
Zheng

**Comment by hpages** [comment]
Hi Zheng,

Thanks for resubmitting.

Qian Liu is helping me with this review and will provide feedback here very soon. Thanks!

H.

**Comment by Liubuntu** [comment]
Hi Zheng, 

This is a joint review of your package by @hpages and myself. Your package generally looks good, might need some further refinement in the vignette and some of the R code documentation. Please address these issues and reply here when you are ready for a 2nd review. Thanks. 

### DESCRIPTION

- License: should usually just refer to one particular version (e.g., GPL-3). Since you also have a LICENSE file so should mention it in the License field. (e.g., GPL-3 + file\
 LICENSE)

### NAMESPACE

- looks good.

### MAN

- Please add documentation for dataset, S4/R6 classes and methods.
- Add documentation for the package, and add `@seealso` within the package documentation to link to main functions of the package.
- All man pages need running examples.

### vignettes

- consider adding a flowchart to summarize your major functions and steps in your pipeline.
- add documentation for the datasets you have used in vignette.
- add more explanation for each step in vignette. There are more R code and the output could make the readers confusing without proper explanation.
- Seems like there are too many `eval=FALSE`. Is it because the time limit for compiling or any other concern? Please check if all `eval=FALSE` code chunks are runnable (witho\
ut potential coding error), and if not very time-consuming, make some to be `eval=TRUE`.
- There are several typos in the vignette. You may want to run a spell checker.


## R code

- generally looks very good, functions are nicely indented in a very reabable format.
- Add runnable example for atacPipe, atacPipe2 (could generalize to other R functions)
- Seems there are many classes defined. Is it necessary?
   
## GENERAL
  
- Generally too many dependencies could make your own package fragile.

Best, 
Qian

**Comment by lawremi** [comment]
R6 classes? Why?

**Comment by wzthu** [comment]
Hi @Liubuntu @lawremi  ,

Thank you for your suggestions. We will revise the package ASAP.

The reason for many classes definition and using R6 classes:
The integrated elements in ATAC-seq data processing workflow are very multifarious so we need to build a framework that are more easy for us to maintain and extend new elements in the future. 

The framework is described below.
- The framework for each element in workflow
The abstract class ATACProc is the base class of all workflow element classes, which extract the shared method that will be used by inherited classes, define the abstract methods that have to be implemented by inherited classes and expose the public methods as interface for users. It is easy to make common 
changes for all workflow elements. And, it is also easy to integrate more tools for a specific workflow element class(e.g. Fseq and Hotspot for peak calling process) in the future if it is necessary.
- Dataflow graph management
All implemented workflow element classes are managed by a dataflow graph to check if the object (of a inherited ATACProc class) is a valid prior result for generating a new object (of a inherited ATACProc class). Users can know what to do at the beginning and what to do next when finish several process from this graph ([this is an example generated by our package](http://bioinfo.au.tsinghua.edu.cn/member/zwei/example/map.jpeg))
- Wrapper of classes
We wrap all of these classes with callable functions because most of users do not familiar with OOP. That will be more simply for users to use and understand. So the classes will not expose to the users. They may only pass the object generated by these functions to the other valid functions.   

R6 is an OOP framework for R. More OOP features are included compared to S3/S4/RC. For example, it supports setting private and public members for classes respectively. Therefore, R6 may provide better classes encapsulation and interfaces realizing. Besides, R6 based on S3, which may be more efficient. That is why we use R6 to implement our package.

Zheng

**Comment by lawremi** [comment]
It is completely untrue that R6 offers more features compared to S4. S4 offers typed fields, multiple dispatch, automatic validation, etc, but most importantly, it's objects can be values or references. R6 is purely reference-based, which is rarely the right thing for an R API. The private/public members is the only thing, and it's debateable whether that is even useful. As every programmer knows, one needs to be careful about public fields. But more importantly, providing two different syntaxes in an API (function call and field access) seems like an unnecessary complication to me. Bioconductor is S4-based, let's keep things in the same framework if at all possible.

**Comment by Liubuntu** [comment]
Hi Zheng, 

You're right that you don't need to document those non-exported methods or classes. Those are just general guidelines for documentation, and you do need to add runnable examples for each exported methods, though you could mark them as `\dontrun` if it has prolonged running time when doing the `R CMD check`. Also please consider Michael's suggestion of unifying your classes using S4. 

Best,
Qian

**Comment by wzthu** [comment]
Hi @Liubuntu @lawremi ,

Thank you very much for your reply. Your suggestions are reasonable and we will rewrite the package with S4 classes.

Best,
Zheng

**Comment by wzthu** [comment]
Hi @Liubuntu ,

We rewrites all of the R6 classes with S4 classes and revised the package following your suggestions.
The only ERROR still comes from importing QuasR, which do not support win32 platform, mentioned before.
We are ready for next review now. Would you please to have a look at our package?
Thanks!

These are the changes we made.
 
## Remove R6 dependence
- We rewrite all of R6 classes with S4 classes and remove R6 in DESCRIPTION import field. 

## DESCRIPTION
- We change license field in DESCRIPTION file follow your suggestion.

## MAN

- More details are added in the exported class and methods documents. 
- ATACpipe Package documentation is added and merged to atacPipe man pages because they shared the name. atacPipe function is also a good example for the whole package. Some links are added in @seealso field. 
- We add runable examples to atacPipe, atacPipe2, methods of ATACProc class and other example-less functions. Time consuming examples are commended with \dontrun. 

## vignettes
- We move flowchart forward and add overview section to show and summarize functions and steps in pipeline. 
- Datasets are documented and described more detailedly in each sections. 
- We remove the useless output and add more comments for each output.  
- Many codes in vignettes are time-consuming. We pre-run some of the codes and store the result to show in vignettes.
- We have rechecked the spelling.

## R code
- We add examples for atacPipe, atacPipe2 and some other functions mentioned above.
- The reason for many classes definition has been mentioned last time. 

## GENERAL
- Unlike other packages, pipeline has to integrate many functions from other packages. That may be the meaning of pipeline. And we have tried our best to reduce dependency. For example, Rbowtie2 is developed by us and many functions are implemented with C++. We will check the package state frequently once the package is accepted.


Best,
Zheng

**Comment by Liubuntu** [comment]
Hi Zheng, 

It's very impressive that you could make major changes within several days. After a second review from @hpages and myself, there are still some minor issues you need to address. If all done within 2-3 days, we may still consider to include it in the Bioc 3.6 release. Thank you for your contribution to Bioconductor. 

## vignette
- The newly added flowchart looks great! 

## R
-  `ATACpipe.R` is an empty file with 0 lines (0 sloc), 0 Bytes. 

## NEWS
- Add a NEWS file, so your package news will be included in Bioconductor release announcements.

## unit tests
- Consider adding unit tests. We strongly encourage them. See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## inst/extdata
- please clean you folder and remove any unused files. (e.g., `chr20_1.1.fq.bz2`, `chr20_1.fq.bz2`, `chr20_sample_peak.bed.bz2`)
- check and clean other doc files. 

## others
-- NOTE message: no visible binding problem. (building report: http://bioconductor.org/spb_reports/ATACpipe_buildreport_20171023040835.html) 
```
Consider adding
importFrom("grDevices", "dev.off", "pdf")
importFrom("graphics", "abline", "axis", "plot")
importFrom("stats", "fft", "runif")
importFrom("utils", "download.file", "read.table", "write.table")
```
Please also import masks, DNAStringSet, injectHardMask from Biostrings. Check your `no visible global function definition` problems for potential non-imported functions.  
Other 'no visible global function' NOTEs seem like errors in your code e.g.
`initialize,SamToBam: no visible binding for global variable bamInput`  
in `SamToBam.R` file where the initialize,SamToBam method is implemented, it makes reference to a `bamInput` variable that doesn't seem to be defined anywhere.  
Please investigate all these NOTEs and address them.

Best, 
Qian

**Comment by wzthu** [comment]
Hi @Liubuntu ,
Our package is  "An Easy-to-use Systematic Pipeline for ATACseq data analysis" .
Can we change our package name as sysATAC or esATAC ?
Thanks !

**Comment by Liubuntu** [comment]
Hi Zheng, 

Please do the following for changing your package name: 

- update the package name in the DESCRIPTION file
- update the repository name to match the new package name
- update the link in the comment that started the issue. (by editing the first comment 16 days ago)
```
Update the following URL to point to the GitHub repository of
the package you wish to submit to Bioconductor
    **Repository: https://github.com/wzthu/ATACpipe**
```
- do a version bump

 it will fail to build, and requires some manual intervention to update our database of issues. Let me know when you've updated your repo, and someone in Bioconductor core team will update the data base and trigger a build manually. 

Qian

**Comment by wzthu** [comment]
Hi Qian @Liubuntu ,

I have updated the package repo for changing package name.
We are ready now.  Would you please help us update the database of issue?
Thank you for your help !

Best,
Zheng

**Comment by Liubuntu** [comment]
HI Zheng, 

The name change of your package is successful and the database is updated. Please address the other issues we returned. Thanks. 

Best,
Qian

**Comment by wzthu** [comment]
Hi @Liubuntu @hpages ,
Thank you again for your suggestion and your help. 
We have revised our package following your suggestions.
Would you please have a look at our package again whether it is ready to be accepted ?
Thank you very much!

These are the changes we made:

## R
- Empty file ATACpipe.R is removed.

## NEWS
- NEWS file is added at inst/NEWS.

## unit test
- We add unit tests following the guide line at tests/.

## inst/ext
- We have checked and removed unused files(chr20_1.1.fq.bz2, chr20_1.fq.bz2 and files in adrm). 20_sample_peak.bed.bz2 is used in vignettes.
- We have also checked the doc files. The doc files (Report1.Rmd and Report2.Rmd) are used to generate quality control report for users in atacPipe and atacPipe2.

## others

- We fix all of the NOTEs you mentioned

Best,
Zheng

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wzthu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"esATAC\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/esATAC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
