### ISSUE TITLE
GRmetrics

### ISSUE THREAD

**Issue by NicholasClark** [Bioconductor/Contributions#53]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/uc-bd2k/GRmetrics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by NicholasClark** [comment]
@vobencha
To pass the BiocCheck, I had to bump the "depends" R version up to 3.3. I'm worried this is not really necessary and will cause problems for the majority of users with slightly older versions of R.
Will this make the package completely inaccessible for users with, say, R 3.2?

Do you know if there is a good reason to require >= R 3.3?
Is there a good way around this, or any way I could make the version older or get rid of that "depends"?

**Comment by vobencha** [comment]
Hi,

New packages are developed against the R/Bioconductor devel branches and, once approved, are added to the Bioconductor devel repository:
  http://www.bioconductor.org/checkResults/devel/bioc-LATEST/
as opposed to the release repository:
  http://www.bioconductor.org/checkResults/release/bioc-LATEST/

The idea is that new packages should be compatible with the most recent changes in R and can't be guaranteed to work with earlier versions. Once approved, the package is only available in devel until the next release (October 2016) at which time it becomes available in both release (R 3.3, Bioconductor 3.4) and devel (R 3.4, Bioconductor 3.5). We are currently in a 6 month period where R is the same for Biocondcutor release and devel and anyone with >=R-3.3 can use the package; <R-3.3 cannot.

Valerie

**Comment by NicholasClark** [comment]
Ah, ok. Thanks for the explanation, Valerie.

**Comment by vobencha** [comment]
Sorry for the delay in review. I'll have comments to you in the next couple of days.
Valerie

**Comment by NicholasClark** [comment]
Any updates?

**Comment by vobencha** [comment]
Hi,

Sorry for the delay in review. I've taken a first look at GRmetrics - please see comments below.

(1) vignette

- Add a background section to explain what the package is doing, why it is different (e.g., is there no other R package that graphs these curves?)

- Please instruct loading the package with biocLite(), not devtools::install_github.

  http://www.bioconductor.org/install/

- If you're going to mention the 3 cases they need to be implemented and documented in this R package. It's not ok to say A is implemented in this R package, B is in Matlab and for C the user needs to go to github. Please describe the details of cases A, B and C and remove reference to the github site.

(2) Format the code in R/ man/ and vignette/ to a maximum of 80 characters wide.

(3) output from GRfit

Instead of a list with an imposed class name, please output the data in a SummarizedExperiment class from the SummarizedExperiment package. The class has an assays() slot for the data tables, a colData() slot to store control/treatment information and a metadata() slot for storing information related to the overall experiment.

This avoids the need for the old style S3 GRfit class and integrates your package with existing Biocondcutor infrastructure. The functions that currently take a GRfit class can be made methods that dispatch on SummarizedExperiment, e.g.,

```
setMethod("GRbox", signature=c(fitData="SummarizedExperiment"),
    function(fitData, GRmetric, groupVariable, pointcolor, factors = "all", plotly = TRUE) {
       ## extract parameter table from assays(fitData) where fitData is a SummarizedExperiment
       ## the rest of the code is the same
        ...
        ...
    }
)
```

Please make the following changes:
- Output a SummarizedExperiment from GRfit().
- Either make methods for GRbox(), GRDrawDRC(), GRscatter() to dispatch on SummarizedExperiment OR keep these as regular functions with the 'fitData' argument as a SummarizedExperiment.


(4) inputs to GRfit

You have a "case" argument that is supposed to dictate the structure of the input data. Given that, it doesn't seem necessary to have so many input arguments that describe column names.

- Please clearly describe the expected data input for cases A, B and C
- Modify the code to check for the appropriate column names based on "case". You should be able to remove these arguments:
concentration
cell_count
time
cell_count_time0
cell_count_ctrl

Let me know if you have questions.

Valerie

**Comment by NicholasClark** [comment]
Valerie,

1) You say to remove the references to github in the vignette. Do you want them all removed, including the lines 
"Corresponding MATLAB and Python scripts available on repo https://github.com/sorgerlab/gr50_tools" and 
"Much of the description below has been adapted from https://github.com/sorgerlab/gr50_tools/blob/master/README.md. See there for additional details on corresponding MATLAB and Python scripts."
or do you just want the "install_github" line and the references to the example input files removed?

2) You say to not mention 3 cases and only implement 2... Is it okay to just delete the reference to "Case B" (which I never intended to implement in this package) to fix this?

3) You say to clearly describe the expected data input for the cases... I describe each necessary column of the data frame for each case, suggest what additional columns may be, and give access to example input via data(inputCaseA) and data(inputCaseC).
I'm not sure what else I can do... do you think it's currently unclear? If so, what should I add?

Thanks,
Nick

**Comment by vobencha** [comment]
Hi,

1) references

- man pages

Put the python scripts used to create inputCaseA and inputCaseC in the inst/scripts/ directory of the package. On the man pages, refer the user to the scripts/ directory for scripts used to create the data and mention they are in python.

The man pages for inputCaseA and inputCaseC should not refer the user to 'example 1 in MATLAB scripts'. The example should either be on the relevant R function man page or in the vignette. Please remove these references to MATLAB.

All these github references should be removed:
~/GRmetrics/man >grep github *
GRfit.Rd:\url{https://github.com/sorgerlab/gr50_tools/blob/master/README.md}}
GRfit.Rd:here \url{https://github.com/sorgerlab/gr50_tools/blob/master/README.md}
GRfit.Rd:\url{https://github.com/sorgerlab/gr50_tools/blob/master/README.md} 

- vignette

-- This piece is ok except that it should explain if all the R code is reproduced in MATLAB and Python or only in part:

"Corresponding MATLAB and Python scripts available on repo https://github.com/sorgerlab/gr50_tools 
Much of the description below has been adapted from https://github.com/sorgerlab/gr50_tools/blob/master/README.md. "

-- This part is not ok because it infers that information is available on github only and not in the R package. Again, the idea is that the package contain everything necessary for the user to understand package functions without going to github for essential examples, background or demonstration. If all the same functionality is implemented R, MATLAB and Python you should clearly state that. What exactly is in each language and where is it found?

"See there for additional details on corresponding MATLAB and Python scripts.

-- This should be removed but it sounds like that's in the plans:

Case B: three files with control values labelled with a key
Implemented in MATLAB code. Not yet implemented in R package or online calculator."

-- This should be removed; the example should be in the package:

See the following link for an example "Case A" input data file:
https://github.com/sorgerlab/gr50_tools/blob/master/INPUT/toy_example_input1.tsv

-- This should be modified to use biocLite():

devtools::install_github("uc-bd2k/GRmetrics", build_vignettes=TRUE)


2) Yes, it's ok to only implement 2 cases and remove reference to the third.

3) The man pages do have a complete description of the columns etc. contained int he sample datasets. This information should be on the man pages of the functions that use case A or case C data as input (or referenced by these pages). The GRfit man page currently refer the user to github:

\item{case}{either "A" or "C", indicating the format of the input data. See
here \url{https://github.com/sorgerlab/gr50_tools/blob/master/README.md}
or details below for descriptions of these formats.}

The GRfit.Rd should explain the data format and point the user to ?inputCaseA or ?inputCaseC for details. Both input* man pages should clearly state that not only are the sample datasets in this format but this is the required format for the 'inputData' argument of the GRfit() function.

Valerie

**Comment by NicholasClark** [comment]
Thanks for your patience and explanation!
I'm working on the changes now. Will it immediately trigger you when I push the changes to Github or should I comment and ask for a second review? i.e. should I wait until I'm finished with all changes to push to Github?

**Comment by vobencha** [comment]
Yes, when you push to github I am notified. The single package builder won't rebuild the package unless you bump the version.
Best practice is to make all changes locally, run R CMD build and check locally, then commit to github. The idea  is to commit an error-free version to github if possible - at least one that passes build and check.

**Comment by NicholasClark** [comment]
I've changed the GRfit output to a SummarizedExperiment object.
Before, the output was a list of two data frames and a vector. One data frame was "gr_table", which had just had the original data along with an extra column of "GR" values. The points (concentration, GR) are used to derive the parameters that fit the sigmoidal curve. Those parameters along with other metrics were stored in the data frame "parameter_table". And lastly the vector was a list of "grouping variables", the key variables that are not averaged over.

Now, I've separated "parameter_table" into the 3 DataFrames required for a SummarizedExperiment object. Since the other objects ("gr_table" and "groupingVariables") are information about the data used to fit the curve and not the parameters/properties of the curve itself, I stored them in a list in the "metadata" of the SummarizedExperiment.

Is this setup acceptable?

**Comment by NicholasClark** [comment]
Valerie,

My package didn't build at all after a valid push two days ago. Today I bumped the version number and got the error message above... it seemed to not build again.

Do you know what's going on here? It seems like there might be a problem with the build system... BiocCheck is not returning any errors or warnings.

Thanks,
Nick

**Comment by vobencha** [comment]
I'll ask Lori to look into it.

**Comment by vobencha** [comment]
Re: your other comment 2 days ago (don't know how to link to a specific comment). Yes, the arrangement of the data structure you describe sounds good. I'll take one more look once we get a clean build/check on the SPB

**Comment by vobencha** [comment]
Looks like we're down to this:

* Checking whether vignette is built with 'R CMD build'...
    * REQUIRED: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.

**Comment by vobencha** [comment]
Great! I'm marking the package as approved. You should get an email from Martin in the next week with svn credentials and next steps.

Thanks for all of your work on the package.
Valerie
