### ISSUE TITLE
HMP16SData

### ISSUE THREAD

**Issue by schifferl** [Bioconductor/Contributions#532]
Hi guys, this is an `ExperimentHub` package so maybe review should be done by @lshep or @vobencha. Data are there on S3 already and the `metadata.csv` file has been prepared as well. Will just need to add the resources to production to evaluate the vignette. Both Build and Check pass for me : ) It is a tiny package, can go into release or devel – either is fine. Thanks x 10^6

These commands, to look at the objects quickly without `ExperimentHub`:

```
BiocInstaller::biocLite("waldronlab/HMP16SData")
library(HMP16SData)
data("20171011.V13")
data("20171011.V35")
V13
V35
```

- Repository: https://github.com/waldronlab/HMP16SData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hey because of the time crunch that today is the deadline for bioc 3.6  it is probably best to go into devel Bioc 3.7 - can you update the BiocVersion in the metadata.csv and I'll get the files into production.

**Comment by schifferl** [comment]
Great! I will update with the later `BiocVersion` and then evaluate the vignette once the resources are in production.

**Comment by lshep** [comment]
Checking the metadata.csv file: 
````
> library(AnnotationHub)
> temp = readMetadataFromCsv("HMP16SData/")
missing values for 'Coordinate_1_based set to TRUE'
Error in readMetadataFromCsv("HMP16SData/") : 
  RDataPath must start with package name: HMP16SData
```
Looks like the metadata RDataPath specified uses a lowercase d instead of a capital D: HMP16Sdata/ - could you correct the capitalization please

**Comment by schifferl** [comment]
Thanks @lshep, capitalization issue is resolved.

**Comment by lshep** [comment]
HI there, 

now that Bioc 3.7 is out the resources are available with the new devel. 
```
Bioconductor version 3.7 (BiocInstaller 1.29.0), ?biocLite for help
> library(ExperimentHub)
> eh = ExperimentHub()
updating metadata: retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-30
> query(eh, "HMP16SData")
ExperimentHub with 2 records
# snapshotDate(): 2017-10-30 
# $dataprovider: NIH Common Fund Human Microbiome Project
# $species: Homo Sapiens
# $rdataclass: SummarizedExperiment
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH1037"]]' 

           title
  EH1037 | V13  
  EH1038 | V35  
```

Please update the vignette, examples, and remove data accordingly and I will take a look at the package. 

Note:  The single package builder builds will fail as I have not updated the version of Bioconductor they use yet (we normally do this about a week or so after the official release). But I can build and check locally with the understanding that once on our system if any misc ERRORs arise they will need to be fixed asap.

**Comment by schifferl** [comment]
These errors are related to BBS and annotation packages, will just wait a week or so for things to smooth out and then push a small change to rebuild : )

**Comment by schifferl** [comment]
@lshep This is ready for a check whenever you want. We can either wait for the SPB version bump or it could be checked locally. The package is passing R CMD check and BiocCheck on Travis CI (https://travis-ci.org/waldronlab/HMP16SData). While that's Linux only, I don't expect different results on macOS or Windows. Many thanks!

**Comment by lshep** [comment]
Hi Sean, Sorry for the delay.  Looks good and ready to accept.  My only comment - You might consider importing all of SummarizedExperiment since your data objects are SummarizedExperiments, once you load the data, you can't explore the objects without manually installing the library (eg. I couldn't do assays(V13) because assays wasn't found).

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/schifferl.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"HMP16SData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HMP16SData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
