### ISSUE TITLE
signet R package

### ISSUE THREAD

**Issue by algorythmes** [Bioconductor/Contributions#533]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CMPG/signet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
DESCRIPTION & NAMESPACE

- ok

vignette

- looks good.
- use `tempfile()` and evaluate one of the `writeXGMML()` code chunks.

R

- Use a formal (S4) class for 'signet', e.g.,

    ```
    .Signet <- setClass(
        "Signet",
        slots = c(
            pathway = "...",
            connected_comp = "...",
            ...
        )
    )
    
    createSignetObject <- function(...) {
       ...
       .Signet(
           pathway=pathway,
           connected_comp=connected_comp,
           network=network,
           subnet_score=subnet_score,
           subnet_size=subnet_size,
           subnet_genes=subnet_genes,
           p.value=NA
       )
    }
    
    setMethod("show", "Signet", function(object) {
        ...
    })
    ```
    
- use `seq_len()` or `seq_along()` rather than `1:n` paradigm (fails when n == 0)
- prefer `message()` to `message("\n", appendLF=FALSE)`. Similarly for `stop()`, `warning()`
- consider a less indented style, with spacing around mathematical operators and punctuation, e.g.,

            background <- data.frame(
                k = seq_len(200),
                mu = sqrt(seq_len(200) * mean(scores$score, na.rm=TRUE),
                sigma = rep(sd(scores$score, na.rm=TRUE), 200)
            )

- prefer `message(...)` rather than `message(paste(...))`
- searchSubnet.R:74 use `lapply()` rather than `for()` to avoid need for explicit memory management
- avoid `<<-` non-local assignment, e.g., testSubnet.R:36

        idx <- lengths(sigObj) > 1
        sigObj[idx] <- lapply(sigObj[idx], function(x) {
            x$p.value <- mean(nullD > x$subnet_score, na.rm=TRUE)
            x
        })
- undocumentedFunctions.R:293 `wrapper` can be written more simply as

    ```
    wrapper <- function(...) {
        setTxtProgressBar(pb, counter)
        counter <<- counter + 1L
        FUN(...)
    }
    ```

man

- `kegg_human` provide much more extensive description of how this object was derived. Make the construction of this object reproducible via a script in `inst/script`. Do you have permission to redistribute KEGG data? Consider instead constructing this object 'on the fly' from queries using the KEGGREST package.
- `scores` provide much more extensive description of how this data is related to the cited publication. Make the description of this data sufficiently detailed that an interested party could reproduce it.
- signet.Rd: refer the user to the vignette rather than include a `\dontrun` code chunk.
- make each Rd example section runnable, so that your code is actually tested and the user can use the example as a benchmark. If the example as written is too resource consuming, identify a more modest but still illustrative example data set. Use `tempfile()` as the location to write output, if necessary.

other

- inst/NEWS is empty; populate it in a manner that can be parsed by `utils::news()` or omit.
- remove the `misc` directory from the master branch of your github repository

**Comment by algorythmes** [comment]
Dear Martin,

Thank you for the very detailed review. I considered all your comments, please find a point-by-point response below:

> vignette
> •	looks good.
> •	use tempfile() and evaluate one of the writeXGMML() code chunks.

I added a non-echoed chunk using tempfile() that can be evaluated. 

> R
> •	Use a formal (S4) class for 'signet', e.g.,
> •	…

I now use formal S4 classes for “signet” and “signetList” objects and updated the rest of the code accordingly.

> •	use seq_len() or seq_along() rather than 1:n paradigm (fails when n == 0)
> •	prefer message() to message("\n", appendLF=FALSE). Similarly for stop(), warning()
> •	consider a less indented style, with spacing around mathematical operators and punctuation, e.g.,
> •	      background <- data.frame(
> •	          k = seq_len(200),
> •	          mu = sqrt(seq_len(200) * mean(scores$score, na.rm=TRUE),
> •	          sigma = rep(sd(scores$score, na.rm=TRUE), 200)
> •	      )
> •	prefer message(...) rather than message(paste(...))
> •	searchSubnet.R:74 use lapply() rather than for() to avoid need for explicit memory management
> I considered all the previous points and updated my code accordingly.
> •	avoid <<- non-local assignment, e.g., testSubnet.R:36
> •	  idx <- lengths(sigObj) > 1
> •	  sigObj[idx] <- lapply(sigObj[idx], function(x) {
> •	      x$p.value <- mean(nullD > x$subnet_score, na.rm=TRUE)
> •	      x
> •	  })
> •	undocumentedFunctions.R:293 wrapper can be written more simply as
> •	wrapper <- function(...) {
> •	    setTxtProgressBar(pb, counter)
> •	    counter <<- counter + 1L
> •	    FUN(...)
> •	}

I replaced all the non-local assignments. However, a single one remains (undocumentedFunctions.R:80) in the wrapper function. I can go back to the old version of this function if you prefer.

> man
> •	kegg_human provide much more extensive description of how this object was derived. Make the construction of this object reproducible via a script in inst/script. Do you have permission to redistribute KEGG data? Consider instead constructing this object 'on the fly' from queries using the KEGGREST package.

I updated the vignette and example sections that depended on the kegg_human object. Now, I systematically use the graphite package to generate this list of the first KEGG pathways. Therefore I don’t need to redistribute KEGG data and make the construction of the kegg_human object reproducible.

> •	scores provide much more extensive description of how this data is related to the cited publication. 
> Make the description of this data sufficiently detailed that an interested party could reproduce it.

I updated the documentation of this data, explaining how it was generated and giving a link to the raw data.

> •	signet.Rd: refer the user to the vignette rather than include a \dontrun code chunk.
> •	make each Rd example section runnable, so that your code is actually tested and the user can use the example as a benchmark. If the example as written is too resource consuming, identify a more modest but still illustrative example data set. Use tempfile() as the location to write output, if necessary.

I replaced all the \dontrun code chunks by runnable examples.

> other
> •	inst/NEWS is empty; populate it in a manner that can be parsed by utils::news() or omit.
> •	remove the misc directory from the master branch of your github repository

I updated the NEWS file and removed the misc directory from the master branch.

I ran R CMD Check and BiocCheck on two machines (Windows 10 and Ubuntu 16.04) and both have succeeded. However, an error is occurring during the build on Bioconductor package builder (e.g. http://bioconductor.org/spb_reports/signet_buildreport_20171124104155.html). I cannot reproduce this error on my machines. Do you have any idea of what is happening or how I could identify the problem?

Best,
Alexandre

**Comment by algorythmes** [comment]
Dear @mtmorgan,

> I ran R CMD Check and BiocCheck on two machines (Windows 10 and Ubuntu 16.04) and both have succeeded. However, an error is occurring during the build on Bioconductor package builder (e.g. http://bioconductor.org/spb_reports/signet_buildreport_20171124104155.html). I cannot reproduce this error on my machines. Do you have any idea of what is happening or how I could identify the problem?

I identified the problem, the vignette couldn't be built because of the use of a dependency in the first chunk to generate the input (package `graphite`). I then had to reduce the runtime of the examples and vignette. The package is now built without errors or warnings.

Please refer to my previous comment for a response to your other concerns.

Best
Alexandre

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/algorythmes.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"signet\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/signet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
