### ISSUE TITLE
MACPET

### ISSUE THREAD

**Issue by IoannisVardaxis** [Bioconductor/Contributions#538]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/IoannisVardaxis/MACPET

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by IoannisVardaxis** [comment]
Hey,

Should I ask questions here on bioc-devel@r-project.org?

I am trying here first. 

I have set up a push hook on your repository I think. I did what is on the instructions. (sorry i havent done this before and it takes time to understand.)

I have some questions for the errors I got, because I dont get any when I build or check the package on my MAC.

On the build report it says that "unknown macro '\insertRef'" somewhere at the beginning. I include a reference file for an article, how can I avoid this warning? I am not aware of any other macro to include references in roxygene.

A little further down I get an error " error: round is not a member of std", 
I didnt have any such error before in the algorithm and no problems with std for c++ in general. However I checked again now and for functions for std::log, std::round and std::ceil I get error that the "the call to function is ambigious". the header of my c++ script is:
#include <Rcpp.h>
using namespace Rcpp;

Should I change that somehow? 

Finally, when I make all the changes locally at my MAC and then push the changes, will this automatically update the package and trigger a new check or do I need to do something more?

Thanks for all your held and time!

**Comment by nturaga** [comment]
Hi `bioc-devel` is better venue for this.

**Comment by IoannisVardaxis** [comment]
Thanks :)

**Comment by IoannisVardaxis** [comment]
Hey,

I have pushed the changes now. However I havent changed the version from 0.99.0 to 0.99.1 myself. Is it done automatically? How can I verify that my new push is updated in the system and the checking is done again? I have added the webhook as suggested.

**Comment by IoannisVardaxis** [comment]
Hey,

Now that the package is at stage 2. progress, should I do anything or just wait for a response?

**Comment by nturaga** [comment]
HI @IoannisVardaxis I will review your package this week and post a review.

**Comment by IoannisVardaxis** [comment]
Ok!

Thanks:)

Ioannis Vardaxis
Stipendiat NTNU
Sendt fra min iPhone

30. okt. 2017 kl. 14:25 skrev Nitesh Turaga <notifications@github.com<mailto:notifications@github.com>>:


HI @IoannisVardaxis<https://github.com/ioannisvardaxis> I will review your package this week and post a review.

**Comment by IoannisVardaxis** [comment]
Hi @nturaga , have you checked the package?

**Comment by nturaga** [comment]
Your review will be posted by tomorrow.

**Comment by IoannisVardaxis** [comment]
How is it going with the review?

**Comment by nturaga** [comment]
# MACPET_review

## Build and Install 

* R CMD Build: ok

* R CMD INSTALL: ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## man 

* ok

   
## vignette

* In line 393, missing package error doesn't manifest properly because of the way 'BSgenome.Hsapiens.UCSC.hg19' is called.

```
Quitting from lines 393-401 (MACPET.Rmd)
Error: processing vignette 'MACPET.Rmd' failed with diagnostics:
GenomePkg is not installed! See ??BSgenome::installed.genomes
Execution halted
```

The problem with this error, is it doesn't tell me what package is missing but instead says `GenomePkg`. 

* The vignette also needs more detail on how to use the classes, and what use cases they can handle. right now, it looks mostly like an  the classes and a few plots. Try to write up the vignette like you did the last section in `Peak calling workflow`.

* Explain the functions which are being called and "why". Explain the plots as well, i.e, your barplots and heatmaps. This will help new users.

* Also think about producing the vignette so that the text wraps around or format the PDF to fit the width of the page. This will make it easier for users to follow.

## R

* Please use `seq_len` or `seq_along` instead of `1:length(x)` or `1:x`. Eg: Stage_1_PeakFinderFunctions_R.R l355
```
      for(chri in 1:length(Peaks.Info_list))
```
  I suggest a code wide search of wherever you using this pattern, and replace as needed.


*  Instead of `if(class(x.self)=="PSelf"` AnalysisStatistics.R,l130. You can use
```
      is(x.self, "PSelf)
```
   You can do this across your package. 


* A few things regarding this block of code AnalysisStatistics.R: l181
```
    #print:
    cat(paste(rep("-",25),collapse=""))
    cat("\n PETs Counts Summary \n")
    cat(paste(rep("-",25),collapse=""))
```

Use `message()` instead of `cat()` so that diagnostic messages go to stderr rather than stdout, if that is your intention.

You don't need `cat(paste(`, you can just use `cat`. `cat(rep("-",25),sep="")` will work just fine. Using `paste` is not needed. 

Same thing with `return(cat("...` and also `stop(paste(..`. There is no need to use `paste`.

Do this throughout your code as there are multiple instances.

* You use `rm(list=ls())`, in PeakCallerUlt.R. This is not needed. R does this after every function be default.

* It would be really helpful to review the code better if you used this package `formatR` to format your code. 

* Maybe you meant "heatmap" summary-methods.R  L181, L243

```
  	stop("hitmap has to be logical!")
```

* Remove commented out code, and please indent your C++ code better to make it more readable. I will send in a more detailed review of your code once that is done.

**Comment by IoannisVardaxis** [comment]
Thanks! I will push the new version as soon as i am done with the changes. What do you mean with : " indent your C++ code better to make it more readable" on the last point? 
Also, I would like to add something to the sysdata.rda, and this will update some Rd files. Is it ok to do it know?

**Comment by IoannisVardaxis** [comment]
I made all the changes you suggested.
For the vignette I wrote a little more, however I think everything is well explained. I can surely make more changes if you think that it is not enough.

**Comment by nturaga** [comment]
Yes, go ahead. I can only re-check your package after Nov 28th.

**Comment by IoannisVardaxis** [comment]
Perfect, you can wait until I send the next push. It might be after Nov 28th.

**Comment by nturaga** [comment]
Hi @IoannisVardaxis Please issue a version bump, so that your latest changes can build.

**Comment by IoannisVardaxis** [comment]
Hey,
I sent the new updates. I didnt change much on the old functions, but I made two new big scripts so the rest of the functions had to be updated a little.
I also wrote more in the vignette, but I could write even more if you want.

**Comment by nturaga** [comment]
# Updates

 * A few things regarding this block of code AnalysisStatistics.R: l165, do you need the print statements?

  Consider `message` instead of `cat`, everywhere.


 Try using "futile.logger" instead of writing to a LogFile seperately. That will save you a lot of lines and you don't have to reinvent the wheel.


 * In ConvertToPE_BAM.R

   This shouldn't happen in a function where you supress all warnings.


         options(warn = -1)
         invisible(Rsamtools::sortBam(file = BAM_file_2, destination = BAM_file_2.sorted,
             byQname = FALSE))
         options(warn = 0)

   There really is no point in making these calls `invisible`,

         invisible(Rsamtools::filterBam(file = BAM_file_1, index = BAM_file_1.bai, destination = BAMfilt1,
         param = SBparam, indexDestination = FALSE))


   If you really want to supress warnings use `suppressWarnings()`. The other bad practice is to adjust the global options. Instead of `options(warn = -1);    options(warn = 0)` (which changes as user specified o`options(warn = 1)`) capture the old value and reset to that `(oopt = options(warn = -1);                options(oopt)`).

 * You do a good job of using seq_len, and seq_along eveywhere. You missed a few though, eg. Stage_3_PeakFinderFunctions.R: l 477

         1:nrow(Peaks_Info_x)

**Comment by IoannisVardaxis** [comment]
For the AnalysisStatistics I would prefer having it as cat because the function works as a summary, if I use message then everything will be in orange letters which I dont want. But It is not important for me so I could change it if you want. 

The reason I used options(warn=-1) is that suppressWarnings() did not work. I would also like to avoid it. Maybe it has something to do with the R-devel, i dont know.

I was making the calls invisible because they return a directory, which I dont really need. I will remove them.

**Comment by nturaga** [comment]
@IoannisVardaxis When you are ready, please bump the version and let the package build again. I'll take that as a sign to review your package again.

**Comment by IoannisVardaxis** [comment]
I made the updates except from the "futile.logger" which I couldnt figure out how to create a log file and how to write in it actually.

**Comment by nturaga** [comment]
Hi @IoannisVardaxis Did you take a look at this? 
https://cran.rstudio.com/web/packages/futile.logger/README.html

The section you want is `flog.appender`

```
To change the appenders assigned to a logger, use flog.appender():

# Change the 'quiet' logger to write to a file
flog.appender(appender.file('quiet.log'), 'quiet')
flog.warn("Goodbye, %s", "world", name='quiet')
```

**Comment by IoannisVardaxis** [comment]
I made the changes with the "write" to "futile.logger". However I get an error when I push the new version:

* Checking library calls...
Error in parse(rfiles_full[idx], keep.source = TRUE) : 
  invalid multibyte character in parser at line 16
Calls: <Anonymous> ... checkLibraryCalls -> lapply -> FUN -> getParseData -> parse

It seems the error is in the lapply function all of a sudden. I dont get any error when I build the package on my MAC though. I tried to find what causes the error but I cant.

**Comment by IoannisVardaxis** [comment]
I have been trying to find and fix the error I get with no success. I think the problem is with the encoding, however I havent changed anything like that. The problem came after i changed the write function with the futile.logger function but I dont understand if it that which causes the error.

**Comment by IoannisVardaxis** [comment]
Hi, 
Can you please help me with the error so that I can send a valid push?

**Comment by nturaga** [comment]
Hi This is on our end. We are fixing it. I would suggest a version bump for a new build.

**Comment by nturaga** [comment]
@IoannisVardaxis Why do you have a sysdata.rda file in your `R/` directory within your package?

**Comment by IoannisVardaxis** [comment]
@nturaga Because this is a list of data.frames and each data.frame contains coordinates of black listed regions based on the genome used. I use sysdata to remove input data which overlaps with those coordinates.

**Comment by nturaga** [comment]
Hi,

You have warnings because of the way you are referencing your man pages. (https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Cross_002dreferences). 

I think the links are wrong, you want `\code{\link[Rbowtie:Rbowtie]{bowtie}}`

**Comment by IoannisVardaxis** [comment]
Hi,
I did as you suggested but I get the same warnings again.

**Comment by nturaga** [comment]
Hi @IoannisVardaxis 

Your package looks fine and is ready to be accepted. But the warnings are caused because you reference the wrong files.

`\item{object}{An object of \code{\link[InteractionSet:GInteractions]{GInteractions}} class.}`

is supposed to be

`\item{object}{An object of \code{\link[InteractionSet:GInteractions-class]{GInteractions}} class.}`

Take a look the GInteractions-class.Rd file in the InteractionSet package. That's the best way to reference these classes. 

I will accept your package as soon as you fix this.

**Comment by IoannisVardaxis** [comment]
I made the changes but I still get error on windows. I will try to fix it in one of the following days.

Note I made a small modification to the Stage_3_PeakFinderSubFunctions such that it returns four more parameters which I am going to need on a later update after the package is accepted. 
So i also needed to update vignette and the data for documenting those four parameters. But the changes are not big.

**Comment by IoannisVardaxis** [comment]
@nturaga now everything seems to be ok! Thank you for your help!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/IoannisVardaxis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MACPET\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MACPET

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
