### ISSUE TITLE
BioThingsClient

### ISSUE THREAD

**Issue by thomascjohnson** [Bioconductor/Contributions#548]
@newgene

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biothings/BioThingsClient.R

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by newgene** [comment]
Ping @mtmorgan for overriding the above error msg as discussed in #540 . Thanks!

**Comment by mtmorgan** [comment]
Sorry I know you're waiting for me on this and will get there eventually...

**Comment by newgene** [comment]
@mtmorgan No worry. Just wanted to make sure you are aware of this new issue we have submitted. Thanks.

**Comment by thomascjohnson** [comment]
Friendly ping

**Comment by mtmorgan** [comment]
yes sorry, it's taking a little time to get there...

**Comment by mtmorgan** [comment]
I'm really sorry to be slow at this; I'll see that the remainder of the review is expedited. However, it seems like the requirement for match between github repository name and package name is strict -- can you temporarily rename your package in the DESCRIPTION file to BioThingsClient.R and bump the version to 0.99.1? We can rename the package when finally accepted. Sorry again for being so slow.

**Comment by mtmorgan** [comment]
DESCRIPTION

- please provide a more naive user-oriented description of what your package does, in particular what useful information one might find at biothings.io.

vignette

- The vignette needs to be 'live', ie., have code chunks that evaluate during processing. Particularly expensive queries may be an exception to this requirement, but the majority of code chunks need to be evaluated.

- Present the interface in the reverse order, emphasizing first the user-friendly data-frame like queries where fields are specified, and only secondarily for 'advanced' use indicate the general form of the query.

- Generally, I think the package would benefit greatly by thinking carefully about what the user will want, and how to provide that in a familiar and convenient manner -- I don't think the user wants to have to struggle processing nested lists.


R

- Classes shoul dhave 'show' methods, providing users with a summary of the object and API without relying on direct display of slots and their implementation detail.

- Classes should have 'accessor' methods, rather than direct slot access via `slot<-()` or `@<-`.

- provide functionality that allows the user to discover what fields are available for use in the 'fields' argument of `btGet()`.

- Formatting is a personal thing, but consider adopting a style that has consistent indentation and does force one to use excessively short lines, e.g., biothings_client.R:28

    ```
    endpoints = list(
        "query" = list(path = "query"),
        "annotation" = list(
            path = "gene", return_types = c("records", "text", "data.frame"),
            fields = c("symbol", "name", "taxid", "entrezgene")
        ),
        "metadata" = list(path = "metadata"),
        "metadata_fields" = list(path = "metadata/fields")
    )
    ```

- get.R:71 Use a single call to `message()` rather than three successive calls; introduce new lines with `"\n"`.

- utils.R:22 avoid `1:n` (which has surprising results when `n == 0`) in favor of `seq_len(n)`.

man

- ok. A bit terse; consider adding more precise information on argument types (e.g., verbose: logical(1)) and descriptions.

tests

- good

**Comment by mtmorgan** [comment]
@thomascjohnson just wanting to make sure that we are not passing each other in the night...

**Comment by newgene** [comment]
@mtmorgan @thomascjohnson I just updated the description text in the DESCRIPTION file.

**Comment by thomascjohnson** [comment]
@mtmorgan Thanks for the detailed response. I'm sorry for the slow response. I will update accordingly.

**Comment by mtmorgan** [comment]
I'll close this issue now; when you're ready to continue add a comment here and I'll re-open it.
