### ISSUE TITLE
M3DExampleData

### ISSUE THREAD

**Issue by tallulandrews** [Bioconductor/Contributions#55]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tallulandrews/M3DExampleData

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by tallulandrews** [comment]
AdditionalPackage: https://github.com/tallulandrews/M3Drop

**Comment by hpages** [comment]
Hi Tallulah,

Thank you for your submission. Here below are a few minor issues I found with the M3Drop package.

Vignette:

1) Please remove this sentence from your vignette:

> You can download the R-package containing this data here https://github.com/tallulandrews/M3DExampleData

  Note that this installation method is strongly discouraged for Bioconductor packages. The installation method that you should advertize in your vignette is to use biocLite().

2) The vignette feels unfinished. For example the last section (Comparing to Other Methods) ends abruptly with 2 figures (Figures 4 & 5) but nothing is said about them.

3) A good practice is to reference the figures in the text. For example:

> Visual inspection of the resulting plot **(see Figure 1)** shows that...

This avoids any possible confusion, especially when the figure is not at immediate proximity of the sentence that refers to it.

4) The captions of your figures don't get properly formatted (in the PDF version of the vignette). For example in the Figure 1 caption, "Figure 1:" is all the way to the right of the page.

Coding style:

5) Please use `<-` instead of `=` for assignment in your code.

6) Function naming style: e.g. `M3Drop_Clean_Data()`
Are you sure you want to use this naming style for your functions? This is very unconventional and requires more typing than other more conventional naming styles like `M3Drop_clean_data()` or `M3DropCleanData()`. Also you are not using a consistent style e.g. you have `M3Drop_Get_Extremes()` and `M3Drop_Get_Heatmap_Cell_Clusters()` on one side and `M3Drop_getmarkers()` and `Brennecke_getVariableGenes()` on the other side. Whatever naming style you choose, please be consistent.

7) Please format your code in the vignette and examples so that it fits in an 80-character wide terminal. For example:

```
# Remove all cells with < 2000 detected genes and convert to cpm
cpm <- M3Drop_Clean_Data(Mmus_example_list$data, Mmus_example_list$labels,
                         is.counts=TRUE, min_detected_genes=2000)
```
instead of everything on a single line:

`cpm = M3Drop_Clean_Data(Mmus_example_list$data, Mmus_example_list$labels, is.counts=TRUE, min_detected_genes=2000) # Remove all cells with < 2000 detected genes and convert to cpm `

Other:

- The example in the man page for `M3Drop_Differential_Expression()` returns a data.frame with 0
  rows.

Thanks,
H.

**Comment by tallulandrews** [comment]
I have addressed all points.

Cheers,
Tallulah

**Comment by hpages** [comment]
Hi Tallulah,

Thanks for the changes. However not all points were addressed: 5) and 7) remain and the example in the man page for `M3DropDifferentialExpression()` still returns a data.frame with 0 rows.

Thanks,
H.

**Comment by tallulandrews** [comment]
I have addressed all points.

Cheers,
Tallulah

**Comment by tallulandrews** [comment]
Is there anything else needed for approval?

Tallulah

**Comment by hpages** [comment]
Hi Tallulah,
Thanks for these changes. I'm now marking the M3Drop and M3DExampleData packages as accepted. They will be added to the bioc svn repository and nightly builds. You will receive more information in the next several days.
Cheers,
H.

**Comment by tallulandrews** [comment]
Dear Martin Morgan,

I've only got a default acceptance letter about M3DExampleData and none of the links work, neither package has appeared on the Bioconductor website devel branch either. Is there anything else I need to do?

Sincerely,
Tallulah
