### ISSUE TITLE
CHARGE

### ISSUE THREAD

**Issue by BenjaminAdelaide** [Bioconductor/Contributions#550]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BenjaminAdelaide/CHARGE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Hello,

I see your most recent commit to the package was on November 9.  Are you still making changes to the package or do you need help with some of the errors you are getting?

**Comment by BenjaminAdelaide** [comment]
Hello,

The error was in relation to not being subscribed to the Bioc-devel maintainer mailing list. I have now subscribed and bumped the version of CHARGE and still intend to submit and work on the package.

**Comment by dvantwisk** [comment]
Hello,
Your package is not building.  Normally packages rebuild after a version bump.  First off, I need to confirm that you've set up the webhook properly: https://github.com/Bioconductor/Contributions#adding-a-web-hook.  Second, It appears that the way you are bumping your package isn't being seen by our build machine.  Can you please make a new commit and change you version to `0.99.3` instead of `0.99.03`.  If these two conditions are met, your package should build again.  We just need to confirm that everything builds okay before we can begin our review.

**Comment by BenjaminAdelaide** [comment]
Hi there,

Thanks for the instructions to build the package it looks like the package is now building, but the error is still in relation to not being signed up to the mailing list, although I have signed up and am receiving the emails.

**Comment by dvantwisk** [comment]
It looks like the mailing list issue is resolved.  There appear to be just a few small warnings that need to be corrected before we can begin our review.

**Comment by BenjaminAdelaide** [comment]
Hi there,

All errors have now been resolved (they were regarding compressing tutorial data)

Thanks

**Comment by dvantwisk** [comment]
Thanks for fixing the errors.

As for the review, I don't have much to add.  The code is very well written.  Consider writing tests for your package using the `testthat` package.  Also, if there is any further information you can add to the description of your package, datasets, and functions, this would be helpful to do as well; they seem a little sparse.

These two things are just things to consider.  I am able to accept your package as is.  Just message me back telling me what you plan to do.

**Comment by BenjaminAdelaide** [comment]
Hi there,

Thanks for your quick review of my package and your suggestions. I would like to avoid using ```testthat``` with my package for now but will be sure to use it in future submissions to Bioconductor. I have also added a details section for each function thereby adding more description for each function. 

The current ERROR seems to be in relation to not building the vignette on one of the Host machines, which I'm not sure if it is an issue on my end or not.

**Comment by dvantwisk** [comment]
This seems to be an issue on our end.

**Comment by dvantwisk** [comment]
Great!  It looks like your package runs without issues now.  Will you make any more changes or would you like me to accept it now?

**Comment by BenjaminAdelaide** [comment]
Hi there,

Can you please accept the package as it is? Thanks for your suggestions.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BenjaminAdelaide.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CHARGE\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CHARGE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
