### ISSUE TITLE
HTSanalyzeR2: A R/Bioconductor package for gene set enrichment and network analysis of various high-throughput data

### ISSUE THREAD

**Issue by linazhu3** [Bioconductor/Contributions#561]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CityUHK-CompBio/HTSanalyzeR2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
There can be several Authors: but only one Maintainer; the maintainer name and email address need to be formatted correctly. The vignettes directory should not contain the 'built' vignette products, i.e., Rmd but no html files.

**Comment by llrs** [comment]
I am not the official reviewer but I noticed the packages and gave it a look at the vignette:
- It seems that is needed to access slots directly in the vignettes. Could you provide accessors to the relevant information of the objects ? This way will be easier for end users. 
- You use the name GSCA for an object and it is not clear to me how is related to "hypergeometric test in order to find the gene sets sharing significant overlapping with hits". Also it reminds me of another package for [Gene Set Coexpression Analysis](https://www.biostat.wisc.edu/%7Ekendzior/GSCA/). Could you clarify this object purpose?
- There is also the need to call `new`, instead of providing a function to create the object of GSCA class.  This would help the users to know which kind of data is needed to build a GSCA object. 

Hope this helps

**Comment by linazhu3** [comment]
Dear IIrs,

Thanks for your suggestions!
For the s4 class slot and 'new' function, we will polish them ASAP in a more suitable way.
For the 'GSCA' class, we named it as gene set collection analysis which can perform both hypergeometric test and gene set enrichment analysis.

**Comment by linazhu3** [comment]
Hi @LiNk-NY 

I've revised some unsuitable parts as suggested by @llrs. Could you please take a look at my package? I would be very appreciated if you can check it and give some useful suggestions.

Best,
Lina

**Comment by lgeistlinger** [comment]
Hi @linazhu3 ,

According to

https://www.bioconductor.org/developers/package-guidelines/#name

Bioconductor packages should avoid names that imply a temporal (e.g., ExistingPackage2) relationship.

In your case, it seems rather appropriate to modify/extend your existing package

http://bioconductor.org/packages/HTSanalyzeR

instead of submitting a new one.

**Comment by linazhu3** [comment]
Dear @lgeistlinger,

Thanks for your recommendation. Actually, this package has been totally rewritten in a more efficient way and add many new functions. So perhaps I can rename it and submit a new one?

Best, 
Lina

**Comment by LiNk-NY** [comment]
Hi Lina, @linazhu3 
We prefer that you not duplicate the functionality in `HTSanalyzeR`.
It is always better to improve the previous package with the new and rewritten functions.

I am inclined to close the issue and encourage collaboration since one of the authors
of `HTSanalyzerR` is also part of the team on this package.

Any additional comments @mtmorgan ? 

Regards,
Marcel

**Comment by xinwang2hms** [comment]
@mtmorgan @lgeistlinger 

Hi gentlemen, 

This is ridiculous!!!! You are wasting our time!! 

I'm Xin Wang, assistant professor at City Universtiy of Hong Kong, PI of this project. HTSanalyzeR2 is fundamentally different from HTSanalyzeR in the design, functionalities and user interface. These changes **cannot** be made simply by revising or rewriting functions in HTSanalyzeR!!! 

We are astonished that we have submitted this application for a few weeks, but got only a simple feedback of "prefer that you not duplicate the functionality xxx". This is absolutely unacceptable. If you cannot provide any help, we will no longer consider Bioconductor as the repository any more. 

Please kindly provide your professional feedback asap. Otherwise, we will submit to other platforms. 

Regards, 

-Xin

**Comment by lgeistlinger** [comment]
Dear @xinwang2hms,

Your response is inappropriate.
Considering the `NAMESPACE` file of `HTSanalyzeR` and `HTSanalyzeR2` reveals numerous duplicated functions.
Rewriting code and adding new features is part of normal package maintenance.

Improving and extending your existing package is thereby advantageous, as it allows your existing user community of `HTSanalyzeR` to quickly adopt these new features (whereas a new package typically takes time until being noticed).
The `NEWS` file is intended to make your users aware of such changes.
Also publishing on substantial extensions to existing software is a good practice to spread the word.

**Comment by xinwang2hms** [comment]
@lgeistlinger 

Are you judging the similarity only based on NAMESPACE? How funny! Let me repeat the design, interface and functionalities are very different from HTSanalyzeR. The reason why we deliberately keep the same function names and arguments is to exactly allow our users to more easily adapt to the new package. 

I'll submit the package to somewhere else, and also, we will also withdraw the HTSanalyzeR package as well from bioconductor. 

It took us a few weeks to get such a ridiculous feedback. Terrible!

**Comment by xinwang2hms** [comment]
@mtmorgan @lgeistlinger 

Just curious! Have you guys ever looked into our package, or just spent a few minutes and wrote something ridiculously about the version number?

**Comment by llrs** [comment]
I am not a user of HTSanalyzeR but how is HTSanalyzeR different from HTSanalyzeR2? Which different/new functionalities does HTSanalyzeR2 have? 

If I, as a user, should adapt to the new HTSanalyzeR2, why don't change the underlying code in HTSanalyzeR using the code in HTSanalyzeR2? 
Many thanks for your help.

**Comment by mtmorgan** [comment]
@xinwang2hms let me know where you want to go with this; if I don't hear from you tomorrow I'll close the issue but wait for explicit instructions (Martin.Morgan at RoswellPark.org) before removing HTSanalyzeR.

**Comment by mtmorgan** [comment]
# 15 December, 2017

Thanks for your contribution. I'll assume that the recent commits imply that you wish to continue with the review process.

- Because one of the authors has expressed a desire to not submit the package, please have each author confirm, via posting a comment in this issue or emailing me (Martin.Morgan at RoswellPark.org) directly, that inclusion in Bioconductor is acceptable.
- As noted in earlier contributed comments, we strongly discourage packages with names such as `HTSanalyzeR_2_`. We would prefer that this contribution were simply an update to [HTSanalyzeR][]. If it is completely new version, then we would prefer to deprecate HTSanalyzeR in the 'devel' branch this release cycle, and then remove it next release cycle. This will give developers and users almost a year to adapt their code to the new version, following the standard package [end-of-life][] process. It will remove the burden of maintaining two packages from the authors. Users wishing the original functionality can install and use older versions of R and Bioconductor.
- I assume that you will increment the version number to trigger a re-build.
- post a comment summarizing your responses here when done.

[HTSanalyzeR]: https://bioconductor.org/packages/devel/HTSanalyzeR
[end-of-life]: http://bioconductor.org/developers/package-end-of-life/

DESCRIPTION, NAMESPACE

- Good

vignettes

- Required. Please do NOT include the PDF version of the vignette; it will be built by `R CMD build` for distribution with the package.
- The vignette provides a nice overview of package functionality; good!
- Recommended. I am concerned about the number of `eval = FALSE` code chunks, in particular the opportunity for the code chunks to become invalid. What steps are you taking to ensure that the code in these chunks remains valid?

R

- Batch_class.R:13. Recommended. Generally 'initialize' methods have a difficult 'contract' to fulfill. For instance, it is generally required that `new("GSCABatch")` succeeds, else writing a derived class will not work. Because of the complexity of this contract, the best practice is to write constructors (like your `GSCABatch()`) that serve as an interface between the arguments provided by users and the instantiation of a class, and to NOT implement `initialize()` methods.
- Batch_class.R:46. Recommended. Each assignment `.Object@... <- ` copies the entire object; consider `callNextMethod()` instead (this is obviously not a concern if no initiailize methods are defined).
- E.g., Batch_class.R:127: Recommended / required. Best practice is to implement slot 'accessors' for all slots, and to use them throughout, rather than to use direct slot access `@`. The accessors do not have to be methods on generics, and do not have to be exported to the user.
- class_union.R: Recommended. Class unions are very tricky, changing the semantics of existing classes. Consider carefully whether the class union statements here are essential to your package.
- gsca_analyze.R:229. Required. `lengths(listOfGeneSetCollections)` instead of `sapply()`; also elsewhere in the code.
- Required. `vapply()` rather than `sapply()`, throughout
- Required. `stop(...)`, rather than `stop(paste(...))`; likewise for `cat()`, `message()`, `warning()`.
- Required. `message()` rather than `cat()` when producing diagnostic (e.g., update progress) output; `message()` / `warning()` / `stop()` write to stderr, whereas `cat()`, `print()` write to stdout.
- Required. Use `seq_len()` or `seq_along()` rather than `1:...`, to avoid problems in, e.g., `1:numGeneSetCollections` when `numGeneSetCollections == 0`.
- gsca_analyze.R:280. Required. Use a simple helper function to avoid repetitive code, e.g., 

    ```
    helper <- function(x, cidx) {
        if (nrow(x) == 0)
            return(NULL)
        a <- x[[cidx]] < pValueCutoff
        x <- x[a, , drop = FALSE]
        if (any(a))
            x <- x[order(x[[cidx]]), , drop = FALSE]
        x
    }
    sign.hgt <- lapply(HGTresults, helper, "Pvalue")
    sign.hgt.adj <- lapply(HGTresults, helper, "PAdjusted.Pvalue")
    ```
- gsca_analyze.R:326. Required. Avoid 'copy and append' pattern were a result is grown, implicitly, via `overlap = list(); ...; overlap[[i]] <- ;`, instead, 'pre-allocate and fill', `overlap = vector("list", length(numGeneSetCollections)); ...; overlap[[i]] <- `. This avoids unnecessary copying when the list is extended.
- gsca_analyze.R:511 and throughout. Recommended. Consider using [BiocParallel][] rather than foreach, to better integrate with the Bioconductor ecosystem.
- gsca_load_genesets.R:183. Required `unlist(sapply(...))` does not make sense, use `unlist(lapply(...), use.names=FALSE)`
- gsca_summarize.R:3. Recommended. When a generic has several arguments, and only one or a few of those arguments will be used for dispatch, use `signature = ` to restrict dispatch to the specific arguments for which dispatch is required.
- nwa_analyze.R:103. Recommended. Load but do not attach annotation packages, e.g,

    ```
    nmspc < - loadNamespace(anno.db.species)
    obj <- get(anno.db.species, nmspc)
    ```

  Use newer `select()` and `mapIds()` rather than the 'bimap' interface to annotation resources, e.g.,

    ```
    AnnotationDbi::mapIds(obj, vertex_attr(module, "name"), "SYMBOL", "ENTREZID")
    ```
- nwa_preprocess.R:298 Recommended. Use [BiocFileCache][] to reduce the number of times resources are downloaded and to limit the need for users to manage files on disk. This also increases reliability of the nightly build system.
- nwa_view.R:135. Recommended. Avoid highly nested calls

    ```
    unique(Reduce(rbind, lapply(extractedValues, function(li){li$vertices[colsInCommon]})))
    ```
    
  in favor of more readable versions

    ```
    values <- lapply(extractedValues, function(li) li$vertices[colsInCommon])
    unique(Reduce(rbind, values))
    ```
- stat_test.R:117 et seq. Required. Simply assign the result of `sapply()` rather than pre-allocate and fill. No need to use an index if the object itself can be used.

    ```
    t.test.pvalues.one.sample <- sapply(replicates, function(replicate) {
        if (sum(!is.na(replciate)) < 2)
            return(1)
        t.test(replicate, mu, alternative)$p.value
    })
    ```
- zzz.R:2. Required. No need for this message.

man

- Recommended. A best practice is to organize the man pages into files identical to R code files, so that the file structure is 'parallel'. This is good practice because it emphasizes the logical coherence of source code in terms of functionality.
- Recommended. Please give additional consideration to the naivete of your users when describing data sets. For instance indicating that `Biogrid_HS_Mat` is an 'interactome matrix' is not helpful without knowing what an 'interactome matrix' is.

misc

- Required. Remove `sys/symbols.rds`.
- Required. Format inst/NEWS for parsing by news(), or remove.

[BiocFileCache]: https://bioconductor.org/packages/devel/BiocFileCache
[BiocParallel]: https://bioconductor.org/packages/devel/BiocParallel

**Comment by linazhu3** [comment]
Hi, @mtmorgan 

Thanks for your time and suggestions!

**Comment by mtmorgan** [comment]
@linazhu3 can you let me know what your plans are with this package? Thanks

**Comment by mtmorgan** [comment]
@linazhu3 I'll close the issue next week unless I hear from you. If you resume development the issue can be reopened.

**Comment by LiNk-NY** [comment]
@linazhu3,

Do you intend to have your package reviewed for submission by Bioconductor?
If so, I can reopen the issue. Otherwise, please remove the webhook in your package settings.

Regards,
Marcel

**Comment by xinwang2hms** [comment]
LIna, pls remove the webhook, as we would never consider Bioconductor
anymore in the future for any of our packages.

-Xin
