### ISSUE TITLE
flowCut

### ISSUE THREAD

**Issue by jmeskas** [Bioconductor/Contributions#562]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jmeskas/flowCut

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jmeskas** [comment]
My local errors/warnings/notes are below. I believe flowCut requires more than 4MBs of space (It only need 6.2MBs) since many examples are required to showcase all of flowCut's aspects. We have done an extensive search for data that was both small and showed our required traits. As one alternative, a data package could be created. But flowAI and flowClean both have around 3MBs of data. devtools::check() suggests to reduce the size of the PDF, but the quality of the images get reduced too much, in my opinion. Perhaps an html version of vignette would be smaller? Thanks.

R CMD build
Warning: invalid uid value replaced by that for user 'nobody'
Warning: invalid gid value replaced by that for user 'nobody'

devtools::check() / R CMD check
R CMD check results
0 errors | 1 warning  | 1 note 
checking sizes of PDF files under ‘inst/doc’ ... WARNING
  ‘gs+qpdf’ made some significant size reductions:
     compacted ‘flowCut.pdf’ from 3.0Mb to 1.1Mb
  consider running tools::compactPDF(gs_quality = "ebook") on these files
checking installed package size ... NOTE
  installed size is  6.2Mb
  sub-directories of 1Mb or more:
    data   3.1Mb
    doc    3.0Mb

BiocCheck("flowCut") / R CMD BiocCheck
$note
[1] "Consider shorter lines; 313 lines (25%) are > 80 characters long."

**Comment by jmeskas** [comment]
Dear reviewer,

flowCut is getting errors. The error is coming from flowDensity on Mac only. My co-worker is the maintainer of flowDensity and she says that the rgeos package is having problems. She thinks it has to do with the configuration of rgeos on macs. She has asked a question to bioconductor for help a few day ago, but no reply. What should I do here? Am I supposed to make sure all the dependency packages are working before I can add my own package? 

As a second question, I do not know why my builds/checks are not showing windows results. I know I will get errors there because flowDensity depends on flowWorkspace which is failing the windows build/check. I am surprised that I need to pass these tests because I only used importFrom for flowDensity, shouldn't it only borrow the functions I need? Or does importFrom act similar to import? My guess would be that it needs all the packages installed, but maybe bioconductor can do something smart?

Thank you for your clarifications.
Justin

**Comment by Liubuntu** [comment]
HI @jmeskas , 

To answer some of your questions: 

- The package size of 6.2 MB is OK. 
- Please update R version dependency from 3.4 to 3.5.0 in DESCRIPTION.
- For the note of "Consider shorter lines; 313 lines (25%) are > 80 characters long", you can check your scripts and consider truncating the long lines to be smaller as necessary, and using multiples of 4 indentation. 
- The Windows building system is temporarily down. The Bioconductor Core Team is working on that, and it will resume soon. 
- Sorry I didn't see your co-worker's question to Bioconductor due to my mail list setting. Could you ask her to send it again? or just comment it here, so that I could talk to the core team for a solution. Thanks. 

Cheers, 
Qian

**Comment by mehrnoushmalek** [comment]
Hi Qian,
I'm the maintainer of the package:flowDensity. I was in contact with Valerie (Bioc-devel), as I had problem updating my package in github.
It works on Ubuntu, but on Mac and windows, the error is due to some dependencies on other packages that failed the build part (flowWorkspace). However rgeos and car packages are in CRAN and the former one depends on system library: geos-config.
It would be great if you can let me know if I need to do anything on my end.

Thanks in advance,
Mehrnoush

**Comment by LiNk-NY** [comment]
Hi @jmeskas, 

The `flowWorkspace` build on Windows is failing due to a dependency on a CRAN package `XML` which is also failing to build/install.
To answer your question, the `importFrom` directive requires that the package you are importing from builds and installs so that you can make use of the functions. There is no other way since the imported functions may use multiple symbols/functions from the package.
The only option that we have at the moment is to wait for those CRAN binaries to build for devel version of R and for `XML` to work on Windows builder.

@mehrnoushmalek 
There's nothing to be done for the time being.

Regards,
Marcel

**Comment by Liubuntu** [comment]
Hi @jmeskas and @mehrnoushmalek , 

Thanks for your info. I just talked with Valerie and the core team. It happens for new packages that depend on R-devel. Because they are depending directly/indirectly on some CRAN packages, that CRAN fails to distribute the correct binaries on Windows and Mac. 

Here are some references to why the windows and mac builds have been failing in devel for more details: 
https://stat.ethz.ch/pipermail/bioc-devel/2017-November/012265.html
https://stat.ethz.ch/pipermail/bioc-devel/2017-November/012340.html

In the meantime, we can start reviewing your package and you can expect an official review within a few days. Thanks for your contribution. 

Cheers, 
Qian

**Comment by jmeskas** [comment]
Thanks @Liubuntu and @LiNk-NY. Looking forward to seeing the review.

Justin

**Comment by Liubuntu** [comment]
Hi @,

Here is an official review of your package. Please address the issues listed below, and bump the version before any valid push to trigger a new build. Thanks.

### DESCRIPTION
The DESCRIPTION looks good. Only comment is to consider using shorter lines and use multiples of 4 spaces for indentation, so that each line contains <=80 characters. E.g, rewrite this:  
```                                                                                                                                                                             
Title: Precise and Accurate Automated Removal of Outlier Events and Flagging of Files Based on Time Versus Fluorescence Analysis                                                
```                                                                                                                                                                             
into:
```                                                                                                                                                                             
Title: Precise and Accurate Automated Removal of Outlier Events and Flagging                                                                                                    
    of Files Based on Time Versus Fluorescence Analysis.                                                                                                                        
```                                                                                                                                                                             
### NAMESPACE
Looks good.

### README.md
- consider adding some contents for README file or remove it.

### NEWS
- putting the NEWS file under top folder instead of under `inst`, to better expose changes and news to user. I know that "http://bioconductor.org/developers/package-submission/" has said about ```Include an inst/NEWS file for providing users with information on package updates. ``` but the core team seems to be encouraging the former way. This is not mandatory though.

### MAN
The manual looks good, with appropriate documentation of data and functions. Only 1 comment: in the `Author(s)` field, please just say `author1<email>, author2<email>` instead of using `Maintainer / Authors` which are required in `DESCRIPTION`.

### Vignette
Looks really nice!
a personal side note :), you may consider using `.rmd` file for the vignette script, which is much easier than `.rnw`. I am saying it from my own experience, and I know this is all about personal preference. No worry, this will not affect anything about the package acceptance.

### R/
- you function is too long with 749 lines. Please consider breaking them down into smaller functions, for example, define some unexported function starting with ".", and use the exported functioin `flowCut` as a wrapper of the smaller unexported functions.

- It's bad practice to save/create any files without the user's consent. So please make sure nothing saved or generated by default. You may set the argument `printToConsole=TRUE` by default, or to be more readable and as an example for the above comment in breaking down functions, you may write a separate exported function like `plotFlowCut()` to generate the plot in console, call this small function in the major function `flowCut`. Also the user could call the smaller function `plotFlowCut`, and have their own choice to decide if they want to save it as `pdf()` or not.

- avoid using `for` loops which are not efficient. Try using `sapply/lapply` function when appropriate. Avoid using `1:some number`, try using `seq_len` and `seq_along` for more robust code. e.g.,  `for ( l in 1:(length(storeMeans2[[j]])-1) )` could be rewritten to `for (l in seq_len(length(...)))`. 

- Function has long lines. Please keep each line to be <= 80 characters.

- Indentation looks terrible... Please indent properly and use multiples of 4 indents. for example, rewrite your code (L200:205) as:

```{r, eval=FALSE}
res.temp <- calcMeansAndSegmentsRemoved(f=f, Segment=Segment, CleanChan.loc=CleanChan.loc, FirstOrSecond="Second", MaxValleyHgt=MaxValleyHgt,
                                        MaxPercCut=MaxPercCut, MaxContin=MaxContin, MeanOfMeans=MeanOfMeans, MaxOfMeans=MaxOfMeans,
                                        GateLineForce=GateLineForce, UseOnlyWorstChannels=UseOnlyWorstChannels,
                                        AmountMeanRangeKeep=AmountMeanRangeKeep, AmountMeanSDKeep=AmountMeanSDKeep, Verbose=Verbose)
quantiles2 <- res.temp$quantiles; storeMeans2 <- res.temp$storeMeans;
meanRangePerc2 <- res.temp$meanRangePerc; timeCentres2 <- res.temp$timeCentres; remove(res.temp)
``` 
as:
```{r, eval=FALSE}
res.temp <- calcMeansAndSegmentsRemoved(
    f=f,
    Segment=Segment,
    CleanChan.loc = CleanChan.loc,
    FirstOrSecond = "Second",
    MaxValleyHgt = MaxValleyHgt,
    MaxPercCut = MaxPercCut,
    MaxContin = MaxContin,
    MeanOfMeans = MeanOfMeans,
    MaxOfMeans = MaxOfMeans,
    GateLineForce = GateLineForce,
    UseOnlyWorstChannels = UseOnlyWorstChannels,
    AmountMeanRangeKeep = AmountMeanRangeKeep,
    AmountMeanSDKeep = AmountMeanSDKeep,
    Verbose = Verbose)
quantiles2 <- res.temp$quantiles
storeMeans2 <- res.temp$storeMeans;
meanRangePerc2 <- res.temp$meanRangePerc
timeCentres2 <- res.temp$timeCentres
remove(res.temp)
```

another example (L126:133):
```{r, eval=FALSE}
    if (length(Time.loc) == 0){
        message(paste0("Your data does not have a time channel. flowCut will create one, but now flowCut will not be as fully",
                    " functional as it could be. Consider recording the time for future projects."))
        f@exprs <- cbind(f@exprs, 1:nrow(f))
        colnames(f@exprs)[length(colnames(f))+1] <- "Time"
        f@parameters@data <- rbind(f@parameters@data, c("Time", "Time", 262144, -111, 262143))
        rownames(f@parameters@data)[length(colnames(f))] <- paste0("$P", length(colnames(f)))
```
as:
```{r, eval=FALSE}
    if (length(Time.loc) == 0){
        message("Your data does not have a time channel. ",
                "flowCut will create one,",
                "but now flowCut will not be as fully functional as it could be. ",
                "Consider recording the time for future projects.")
        f@exprs <- cbind(f@exprs, 1:nrow(f))
        colnames(f@exprs)[length(colnames(f))+1] <- "Time"
        f@parameters@data <- rbind(
            f@parameters@data,
            c("Time", "Time", 262144, -111, 262143)
        )
        rownames(f@parameters@data)[length(colnames(f))] <-
            paste0("$P", length(colnames(f)))
```

Best, 
Qian

**Comment by Liubuntu** [comment]
One more comment, most of the issues are cosmetics, more like styling problems. For the R script, please make some effort to break down the long function into smaller ones, and use the big function as a wrapper. Again, do not generate any file by default.

**Comment by mtmorgan** [comment]
Direct slot access using @ such as at https://github.com/jmeskas/flowCut/blob/master/R/flowCut.R#L129 should be avoided, use the 'API' instead, e.g., `exprs(f) <- exprs(f) ...`

**Comment by jmeskas** [comment]
Hi Qian @Liubuntu ,

Thank you for your review. I am obviously not as quick as you, thank you for your fast response. I have been editing based on your comments but I have a few questions:

1) Why can I not use the @ in my code? Am I allowed to use the $? Does this mean I need to switch f@parameters@data$desc to pData(parameters(f))$desc? I find this rather confusing. I would much rather access the variable left to right (parameters, data, then desc) as opposed to right to left and then right again (parameters, pData, desc). But I am very curious as to the reasoning behind this.

2) 80 characters is so little. What is the reason for only 80? Is it compatibility issues with old systems? Again very curious. I do admit that many parts look better now based on your suggestions, but I would have to say that some parts are definitely harder to read now. I have been editing my code to be less than 80, but I have a few parts that I don't know what to do. What would you do for this:

        if ( as.numeric(res_flowCut$data["Mean of % of range of means divided by range of data", ])
                <  as.numeric(resTable["Mean of % of range of means divided by range of data", ])){
            resTableOfResTable["Mean of % of range of means divided by range of data", ] <-
                resTable["Mean of % of range of means divided by range of data", ]
        }

Thank you for your time,
Justin

**Comment by Liubuntu** [comment]
HI @jmeskas , 

- When writing an R package, the use of @ and $ are both not encouraged. You can use the `[ ]`, `[[ ]]` for subsetting or extracting specific fields. The `$` is handy when doing interactive programming but should be discouraged for more production oriented code because of its limitations, namely the inability to interpolate the names or use integer indices. @mtmorgan , could you explain a little bit more about the disadvantage of using `@`? 

- It's ok to have some longer lines than 80 characters. 

Qian

**Comment by mtmorgan** [comment]
This response is a little out of the blue. Use of `@` for S4 slot access exposes the internal 'implementation' to the 'user', whereas a major motivation for using formal classes is to separate the 'implementation' from the 'interface'. Good examples of where this comes about are in the IRanges() class, where there are slots for two of start, end, width, but it is none of the user's (including the IRanges developer, after deciding which two should be represented) business what the implementation is -- `start()`, `end()`, `width()` hide this implementation detail. Biocstrings::DNAStringSet() is another example, where naively one might expect to see that the object contains a slot with a character vector of DNA sequences, but it contains nothing of the sort, with the representation arrived at for efficiency and other reasons that the user has no need to worry about.

I'm not sure about where `$` is coming from. If we're just talking about accessing list (including data.frame) elements, then use `$` or `[[` interchangably, to get the corresponding element / column; `[` has a different semantic, returning an endomorphism, i.e., a list or data.frame rather than the element or column. If talking about S3 classes, then the use of `$` rather than an accessor applies for the same reason as `@` for an S4 class.

**Comment by Liubuntu** [comment]
HI, 

Please make appropriate commits to show your effort in revising the package. We usually have a rule of 2 weeks for package review responses. If no response within this week (by Friday, 1/19/2018), or you think it should take a longer time in revising, the issue will be closed and you can reopen it with the same issue name whenever you think that would work for you. 

Best,
Qian

**Comment by jmeskas** [comment]
Hi Qian,

Unfortunately I don't have time right now to do this. Please close this issue/review. I will open one up when I have more time. 

Thank you,
Justin

**Comment by Liubuntu** [comment]
Totally understand. Good luck!

**Comment by jmeskas** [comment]
Hello @Liubuntu and @mtmorgan ,

Could we re-open this issue? Or should I open a new one?

My collaborator @sherrie9 will be taking over correspondence. She will join this conversation today.

We have changed the licence to Artistic-2.0, so we shouldn't have any license issues.

We have added a few parameters and changed some things. I notice that we have not changed everything you had asked for 2.5 years ago. Perhaps we should initiate a new review, since potentially some of the Bioconductor requirements have changed? If all of those still apply let us know and we can try to fix things.

However, I still strongly believe some things are not changeable:

1) Changing my code on the left to the other version on the right:
f@parameters@data$desc to pData(parameters(f))$desc

2) We cannot reduce the size of the package since we need all the data to show all the different issues and how to solve them in the vignette and the man example code.

3) Having functions <=50 lines seems like a Herculean task. Sherrie and I are not computer scientists. I am afraid that meeting this requirement will create some errors in our code. If the main reason is to reduce the chance of crashing, please note that we ran flowCut against all FlowRepository data and it didn't crash once. Perhaps we could compromise here and try to make the functions a bit smaller. But we would need your help with suggestions.

Thank you for your time and advice on this submission,
Justin

**Comment by mtmorgan** [comment]
Hi Justin -- I toggled the status of the package because commits were still triggering builds on our build system. and it seemed after all this time that the package wasn't going to be submitted after all -- the original submission was almost 2 1/2 years ago!

If the package is ready for review, rather than requiring further iterations, and if you and your collaborators are in a position to actively respond to and maintain the package, then certainly we can re-open the issue. I will take over the review process.

We will keep using this issue, but I will provide an initial review that may differ from the original. I have not looked closely but with respect to your comments above

1. It is well-established best-practice to use 'accessors' rather than direct slot access, so you would be required to update your code appropriately.

2. The solution for large packages is either to (1) compromise on the 'reality' of the scenario and instead focus on illustration or testing through small data sets (most packages are able to do this, effectively) or (2) make your large data available through a separate [ExperimentHub][1] resource and [package][2]; this is obviously more work.

3. Functions with many 100's of lines of code are very difficult for a human to understand, and that concern is what motivates this comment. I do not think this task is Herculean. A trivial example is the highly repetitive code
```
    if (!is.character(Directory)){
        message("Directory must be a character.")
        resTable["Has the file passed", ] <- "Directory must be a character."
        return(list(frame=f, ind=NULL, data=resTable, worstChan=NULL))
    }
```
which can be replaced by a function
```
.fail <- function(txt, index, frame, data) {
    message(txt)
    data[index,] <- txt
    list(frame = f, ind = NULL, data = data, worstChan = NULL)
}
```
and used with
```
if (!is.character(Directory)) {
    fail <- .fail("Directory must be a character", "Has the file passed", frame, resData)
    return(fail)
}
```
Conceptually we have to only understand and debug one block of code (the newly defined function) instead of 'guessing' that all of the repeated uses are logically equivalent and remembering to update all chunks if we change to a different approach. A little more generally, large `if` clauses like at https://github.com/jmeskas/flowCut/blob/cf6ad316ab02635085899f28cff56c42809c687a/R/flowCut.R#L277 are good candidates for implementation as a function `.is_monotonic()`. One advantage of this approach is that the more bite-sized functions are generally much easier to test -- do the particular inputs relevant to this function result in the correct computation?

My feeling is that, after a very brief glance at your package, there are a number of changes like those above that would make it much better (more correct, faster, and robust).

Again, if you are willing to engage in a second review, then certainly we can re-open the issue. Let me encourage you to reflect on the commitment, and if interested to continue to develop the package until it is ready for review. When you reach that stage, add a comment here and tag me, and I will review your package.

**Comment by sherrie9** [comment]
Hi, @mtmorgan I think we are ready for a second review. Thank you!

**Comment by mtmorgan** [comment]
can you increment the version to 0.99.22 to trigger a build? Thanks

**Comment by sherrie9** [comment]
Hi, @mtmorgan , I was wondering what should be expected from us now since you are opening a second review. I saw that the only error was due to package size about which I believe we had an earlier conversation and we were given an exception (due to the naturally large size of flow cytometry data). I also believe the warning generated is unavoidable.  Not much has changed for flowCut since we first published it on bioconductor, we only added one minor functionality to the code. I assume and hope the review process should be fairly quick. 
Thank you.

**Comment by mtmorgan** [comment]
please address the following comments. When you are ready for a second review, please provide a brief comment summarizing how each concern has been addressed.

DESCRIPTION

- please provide a description that is more like a paper abstract, identifying the unique features and analyses your package enables.

- The maintainer is listed as Justin Meskas, but maintenance seems to have been taken over by Sherrie Wang?

- Consider using the more flexible Authors@R: field, rather than separate Author: and Maintainer: fields.

NEWS

- Format this file to be parsed by news(); currently we have

    ```
    > news(package="flowCut")
    Version: 0.99.0
    Text:

    Version: 0.99.1
    Text:
    ...
    ```

vignettes

- remove build products (flowCut.html); these are produced by R CMD build

- the presence of images in the vignettes/ and vignettes/flowCut/ directories is confusing; is there a reason for this separation?

R

- as mentioned, the very long functions (e.g., 900+ lines for flowCut()) are impossible to maintain. The trivial example from earlier -- a helper function to validate -- has not been implemented. Creating functions  to implement complicated `if() {}` branches is also advised. Benefits of this more modular code include code re-use and easier testing.

- direct slot access is not satisfactory.

    ```
    t.name <- f@parameters@data$name
    ```

  becomes
  
    ```
    t.name <- parameters(f)$name
    ```
    
  `f@exprs` becomes `exprs(f)` and many other examples.


- please standardize formatting, for instance appropriately indenting `grep()` on lines 224-225. Consider using the formatR package.

- `message(paste0())` constructs like that on line 239 are usually not necessary -- `message()` pastes its arguments automatically `message("foo ", "bar")`.

- since `grep()` seems to be used regularly, develop a better understandign of efficient regular expressions -- e.g., line 248 `pattern = "(pulse|width|length|...)"`

- factor out common expressions, for clarity, robustness, and performance, e.g.,

    ```
    time.data[(diff.ind.strong[mono.ind]+1):length(time.data)] <- 
        time.data[(diff.ind.strong[mono.ind]+1):length(time.data)] + 
        abs(time.diff[diff.ind.strong[mono.ind]])
    ```

  as
  
    ```
    start <- diff.ind.strong[mono.ind]
    idx <- seq(start + 1, length(time.data))
    time.data[idx] <- time.data[idx] + abs(time.diff[start])
    ```

  simplifying in this way suggests further opportunities for more expressive and efficient code
  
    ```
    for (mono.ind in seq_along(diff.ind.strong)) {
        start <- diff.ind.strong[mono.ind]
        idx <- seq(start + 1, length(time.data))
        time.data[idx] <- time.data[idx] + abs(time.diff[start])
    }
    ```
    
  as
  
    ```
    time.diffs <- abs(time.diff[diff.ind.strong])
    for (mono.ind in diff.ind.strong)
        idx <- seq(mono.ind + 1, length(time.data))
        time.data[idx] <- time.data[idx] + time.diffs[mono.ind]
    }
    ```
    
  the principle of identifying common expressions to simply code appears at many places in the code, e.g.,
  
    ```
    if ( length(which(match(all.Time.loc, MonotonicWithTime, nomatch=0) >= 1)) >= 1){
        MonotonicWithTime <- MonotonicWithTime[-match(all.Time.loc, MonotonicWithTime, nomatch=0)]
    }
    ```
    
  as
  
    ```
    test <- match(all.Time.loc, MonotonicWithTime, nomatch=0)
    if ( any(test >= 1) ) {
        MonotonicWithTime <- MonotonicWithTime[-test]
    }
    ```

- scrutinize your code for opportunities for vectorization (one R function call) rather than iteration (n R function calls). For instance

    ```
    for(l in seq_len(length(storeMeans[[j]])-1) ){
        temp.vect[l] <-
            abs(storeMeans[[j]][l]-storeMeans[[j]][[l+1]]) /
            (quantiles[[j]]["98%"]-quantiles[[j]]["2%"])
    }
    ```
    
  as
  
    ```
    temp.vect <- abs(diff(storeMeans[[j]])) / 
        (quantiles[[j]]["98%"] - quantiles[[j]]["2%"])
    ```

manual pages

- good

unitTests/

- I believe the package has no unit tests, so this directory should be removed (or better, unit tests implemented)

**Comment by sherrie9** [comment]
Hi @mtmorgan , Thank you for your detailed feedback. I have done some modifications accordingly. Specifically:
> please address the following comments. When you are ready for a second review, please provide a brief comment summarizing how each concern has been addressed.
> 
> DESCRIPTION 
> 
> * please provide a description that is more like a paper abstract, identifying the unique features and analyses your package enables. (**DONE**)
> * The maintainer is listed as Justin Meskas, but maintenance seems to have been taken over by Sherrie Wang? (**Justin is still the maintainer, I am only helping him for now with regards to this submission because he is quite busy with other responsiblities at this time.**)
> * Consider using the more flexible Authors@R: field, rather than separate Author: and Maintainer: fields. (**DONE**)
> 
> NEWS
> (**I am not too clear how to do this, do I just type in required formatting into NEWS or do I need some special functions to do this? I tried to use new2Rd function but couldn't get it to work. P.S. how do you type in circles?**)
> * Format this file to be parsed by news(); currently we have
>   ```
>   > news(package="flowCut")
>   Version: 0.99.0
>   Text:
>   
>   Version: 0.99.1
>   Text:
>   ...
>   ```
> 
> vignettes
> 
> * remove build products (flowCut.html); these are produced by R CMD build (**DONE**)
> * the presence of images in the vignettes/ and vignettes/flowCut/ directories is confusing; is there a reason for this separation? (**the flowCut directory is created by flowCut plot function. Plots outside this directory is we adding external plots to show as examples (not created by flowCut)**)
> 
> R
> 
> * as mentioned, the very long functions (e.g., 900+ lines for flowCut()) are impossible to maintain. The trivial example from earlier -- a helper function to validate -- has not been implemented. Creating functions  to implement complicated `if() {}` branches is also advised. Benefits of this more modular code include code re-use and easier testing. (**I am not sure how to address this at this moment. We will definitely take this into consideration in our future effort** )
> * direct slot access is not satisfactory. (**DONE**, **there is only one instance where I did not change** `parameters(f)@data <- rbind(parameters(f)@data,c("Time",
"Time",262144,-111,262143)` **as it is trying to make modifications to the data instead of accessing and I am afraid making changes can affect the outcome.**  )
>   ```
>   t.name <- f@parameters@data$name
>   ```
>   
>   
>   becomes
>   ```
>   t.name <- parameters(f)$name
>   ```
>   
>   
>   `f@exprs` becomes `exprs(f)` and many other examples. (**DONE**)
> * please standardize formatting, for instance appropriately indenting `grep()` on lines 224-225. Consider using the formatR or styler package. (**DONE**)
> * `message(paste0())` constructs like that on line 239 are usually not necessary -- `message()` pastes its arguments automatically `message("foo ", "bar")`. (**DONE**)
> * since `grep()` seems to be used regularly, develop a better understandign of efficient regular expressions -- e.g., line 248 `pattern = "(pulse|width|length|...)"`
> * factor out common expressions, for clarity, robustness, and performance, e.g., (**DONE**)
>   ```
>   time.data[(diff.ind.strong[mono.ind]+1):length(time.data)] <- 
>       time.data[(diff.ind.strong[mono.ind]+1):length(time.data)] + 
>       abs(time.diff[diff.ind.strong[mono.ind]])
>   ```
>   
>   
>   as
>   ```
>   start <- diff.ind.strong[mono.ind]
>   idx <- seq(start + 1, length(time.data))
>   time.data[idx] <- time.data[idx] + abs(time.diff[start])
>   ```
>   
>   
>   simplifying in this way suggests further opportunities for more expressive and efficient code
>   ```
>   for (mono.ind in seq_along(diff.ind.strong)) {
>       start <- diff.ind.strong[mono.ind]
>       idx <- seq(start + 1, length(time.data))
>       time.data[idx] <- time.data[idx] + abs(time.diff[start])
>   }
>   ```
>   
>   
>   as (**DONE**)
>   ```
>   time.diffs <- abs(time.diff[diff.ind.strong])
>   for (mono.ind in diff.ind.strong)
>       idx <- seq(mono.ind + 1, length(time.data))
>       time.data[idx] <- time.data[idx] + time.diffs[mono.ind]
>   }
>   ```
>   
>   
>   the principle of identifying common expressions to simply code appears at many places in the code, e.g., (**DONE**)
>   ```
>   if ( length(which(match(all.Time.loc, MonotonicWithTime, nomatch=0) >= 1)) >= 1){
>       MonotonicWithTime <- MonotonicWithTime[-match(all.Time.loc, MonotonicWithTime, nomatch=0)]
>   }
>   ```
>   
>   
>   as
>   ```
>   test <- match(all.Time.loc, MonotonicWithTime, nomatch=0)
>   if ( any(test >= 1) ) {
>       MonotonicWithTime <- MonotonicWithTime[-test]
>   }
>   ```
> * scrutinize your code for opportunities for vectorization (one R function call) rather than iteration (n R function calls). For instance (**DONE**)
>   ```
>   for(l in seq_len(length(storeMeans[[j]])-1) ){
>       temp.vect[l] <-
>           abs(storeMeans[[j]][l]-storeMeans[[j]][[l+1]]) /
>           (quantiles[[j]]["98%"]-quantiles[[j]]["2%"])
>   }
>   ```
>   
>   
>   as
>   ```
>   temp.vect <- abs(diff(storeMeans[[j]])) / 
>       (quantiles[[j]]["98%"] - quantiles[[j]]["2%"])
>   ```
> 
> manual pages
> 
> * good
> 
> unitTests/ (**DONE, removed for now**)
> 
> * I believe the package has no unit tests, so this directory should be removed (or better, unit tests implemented)

**Comment by mtmorgan** [comment]
Thank you for your responses so far.

NEWS can be revised as NEWS.md with a major heading anticipating each release, unadorned paragraphs for major sections, and bullet lists for specific commits. A typical NEWS.md file might look like

```
# Changes for version 1.0.0

NEW FEATURES

- (v. 0.7.0) feature 1
- (v. 0.8.0) feature 2

BUG FIXES

- (v 0.7.1) bug fix 1
- (v 0.7.2) bug fix 2
```

Do you mean that the vignettes/flowCut directory is created when the vignette is built? If so it should be removed because these images will be re-created when the package is built (`R CMD build flowCut`).

'setters' are available, so
```
parameters(f)@data <- rbind(parameters(f)@data,c("Time", "Time",262144,-111,262143))
```
becomes
```
pData(parameters(f)) <- rbind(pData(parameters(f)), c("Time", "Time",262144,-111,262143))
```

Although I mentioned specific lines, the idea is to update all relevant code. For instance you removed one `message(paste())`, but there are 6 more
```
lowCut/R master$ grep "message(paste" *
        message(paste0("Either your Segment size is too large or your number", " of cells is too small."))
        message(paste0("Plot must be a character", "with one of the following", " options: 'None', 'All', or 'Flagged Only'."))
        message(paste0("Channels ", paste0(NoVariation, collapse = ", "), " have no variation and have been removed from the analysis."))
            message(paste0("Fixing file ", FileID, " for the monotonic time issue."))
                message(paste0("All of file ", FileID, "'s monotonic issues are larger than MonotonicFix and were not adjusted."))
        message(paste0("Channels ", paste0(MonotonicWithTime, collapse = ", "), " are monotonically increasing in time and have been removed from the analysis."))
```
(the last line has a nested `paste()` that uses `collapse=`; this is an appropriate use of `paste0()` in `message()`).

There are a number of additional places where the code can be clarified by identifying common expressions (there are a number associated with the use of `which(` in the code), and for vectorization instead of iteration (focus on the many `for` loops) and I encourage you to search for and improve those code snippets more aggressively.

Please let me know when you have completed the revisions and your package is ready for final review.

**Comment by sherrie9** [comment]
thank you @mtmorgan . I have one question, in the description file, I used Authors@R as follows:
`Authors@R: personList(person("Justin","Meskas", role=c("cre","aut"), email="justinmeskas@gmail.com"),
                      person("Sherrie","Wang", role = "aut"))`.
But in the build report, it resulted in an error saying this needs to be an R code. I am not sure what the error is or how to write it properly. Thanks!

**Comment by mtmorgan** [comment]
Use `c()` instad of `personList()`, like
```
Authors@R: c(
    person("Ima", "Person"),
    person("Iman", "Other")
  )
```
(I'm not totally sure why `personList()` does not work...)

**Comment by sherrie9** [comment]
Hi, @mtmorgan , I have completed my revisions and tried my best/humble attempts at code optimizations. I pushed about an hour ago but received no further build report. I am guessing that's it?

**Comment by sherrie9** [comment]
Hi, @mtmorgan , is it possible to start to final review now?

**Comment by sherrie9** [comment]
Great, thank you very much for all your help! @mtmorgan

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jmeskas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("flowCut")`. The package 'landing page' will be created at

https://bioconductor.org/packages/flowCut

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
