### ISSUE TITLE
GDCRNATools

### ISSUE THREAD

**Issue by Jialab-UCR** [Bioconductor/Contributions#569]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jialab-UCR/GDCRNATools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Seems like there are a lot of opportunities for synergy with [GenomicDataCommons](https://bioconductor.org/packages/GenomicDataCommons) @seandavi

**Comment by mtmorgan** [comment]
Please remember to increment the version of your package to trigger a new build; I'll review the package one no version bump is required.

**Comment by Jialab-UCR** [comment]
@mtmorgan Hi Morgan, really appreciate your help. I have made a build. Thanks again~

**Comment by Jialab-UCR** [comment]
@mtmorgan Hi Martin, is it ready for me to make revisions on the package? Thanks

**Comment by mtmorgan** [comment]
Sorry for the delay.

DESCRIPTION

- Good!

Vignette

- Please update the installation instructions to be those after acceptance in Bioconductor, i.e., 

    ```
    source("https://bioconductor.org/biocLite.R")
    biocLite("GDCRNATools")
    ```
    
- Instead of downloading data to arbitrary locations on the user's computer, consider using [BiocFileCache][] and in particular using this in the vignette, so that the builders only access the data periodically rather than each night. The code chunks can then be marked as `eval=TRUE`. This is important because the code chunks marked `eval = FALSE` frequently become out-of-date, e.g, from the vignette

    ```
    gdcRNADownload(manifest  = 'TCGA-PRAD/TCGA-PRAD.RNAseq.gdc_manifest.2017-11-23T14-40-52.txt',
                   directory = 'TCGA-PRAD/RNAseq')
    
    
    ##############################################################################
    Pathview is an open source software package distributed under GNU General
    Public License version 3 (GPLv3). Details of GPLv3 is available at
    http://www.gnu.org/licenses/gpl-3.0.html. Particullary, users are required to
    formally cite the original Pathview paper (not just mention it) in publications
    or products. For details, do citation("pathview") within R.
    
    The pathview downloads and uses KEGG data. Non-academic uses may require a KEGG
    license agreement (details at http://www.kegg.jp/kegg/legal.html).
    ##############################################################################
    > 
    + trying URL 'https://gdc.cancer.gov/system/files/authenticated%20user/0/gdc-client_v1.3.0_Ubuntu14.04_x64.zip'
    Content type 'application/zip' length 24647158 bytes (23.5 MB)
    ==================================================
    downloaded 23.5 MB
    
    arguments 'minimized' and 'invisible' are for Windows only
    Error in file(file, "rt") : cannot open the connection
    In addition: Warning message:
    In file(file, "rt") :
      cannot open file 'TCGA-PRAD/TCGA-PRAD.RNAseq.gdc_manifest.2017-11-23T14-40-52.txt': No such file or directory
    ```
    
- Generally, the large number of `eval = FALSE` chunks is not acceptable. Likely re-using already downloaded data (via BiocFileCache) and careful choice of data sets for analysis will make it possible to more completely evaluate code in the vignette.

- Consider Suggest:ing and using [RCy3][] for cytoscape-based network visualization.

R

- Is there an opporutnity to re-use functionality from the [GenomicDataCommons][] package, rather than re-inventing the software?

- Use `message()` instead of `cat()` to communicate with the user; consider one call to `message()` rather than two or more, and consider that too much enthusiasm can be tiring, e.g, gdcCEAnalysis.R:68 (hmm, not sure where step 3 is done?)

    ```
    message (
        'Step 2/3: Correlation analysis done',
        '\nStep 3/3: Regulation pattern analysis done'
    )
    ```

- gdcCEAnalysis.R:207 and throughput: use `vapply()` rather than `sapply()`, and `seq_len()` or `seq_along()` rather than `1:n` (to avoid problems when n = 0 or the argument is of length 0 (and `sapply()` returns a `list()`!)).

- Consider an indentation style that provides constant amounts of indentation and allows for longer lines, e.g., gdcDEGVisulization.R:28

    ```
    d <- data.frame(
        geneClass = c('Up','Down'),
        geneNums = c(up, down), 
        Regulation = factor(
            c('Up-regulated','Down-regulated'),
            levels=c('Up-regulated','Down-regulated')
        )
    )
    ```


[GenomicDataCommons]: https://bioconductor.org/packages/GenomicDataCommons
[BiocFileCache]: https://bioconductor.org/packages/BiocFileCache
[RCy3]: https://bioconductor.org/packages/RCy3

**Comment by Jialab-UCR** [comment]
Hi @mtmorgan 
Thank you so much for your help on the improvement of the package. I have learned a lot.
I have made some changes according to your suggestions:


**Vignette**
1. The installation instructions have been updated to:
```
source("https://bioconductor.org/biocLite.R")
biocLite("GDCRNATools")
```

2. The vignette has been re-designed. More chunks are changed to `eval=TRUE` . Only those require long time or cost large memory are kept `eval=FALSE`.

3. Because the edges and nodes files exported by the `exportNetwork` function can be easily imported to Cytoscape, so I didn't use `RCy3` for the network visualization. I do try it, but the output doesn't look good. 


**R**
1. Really appreciate your suggestions of using `GenomicDataCommons` package, which is an excellent package for accessing GDC data. I have modified the `gdcRNADownload` and `gdcClinicalDownload` functions in my package to use the API method in GenomicDataCommons as default method for data download.

2. All `cat()` are replaced with `message()`

3. All `sapply()` are replaced with `vapply(),` and `1:n` are replaced with `seq_len(n)`

4. Multiples of 4 spaces are used for line indents. Long lines are shortened to < 80 characters.


Again, thanks a lot for your help.



Best,
Ruidong

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jialab-UCR.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"GDCRNATools\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GDCRNATools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
