### ISSUE TITLE
omicplotR

### ISSUE THREAD

**Issue by dgiguer** [Bioconductor/Contributions#571]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dgiguer/omicplotR

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# omicplotR review

## Build and install

R CMD build: ok

R CMD INSTALL: ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## man

* ok.

* Author gives a description of how to run the app.

## vignettes

* Since it is a shiny app, only `omicplot.run()` is included. I recommend, adding screen shots to the vignette to help users understand how to use the tool, along with some small test datasets in the ".txt" format(for both, metadata and data). This will allow reviewers to quickly run the app along with the test data.

## R

* In internal.R: 150

             #samples
             for (i in 1:length(otu.names)) {
                 if (!(otu.names[i] %in% otus)) {
                     otu.missing[i] <- otu.names[i]
                 }
             }

  Do NOT use `1:length(X)`, `1:ncol()`, `1:nrow()` instead use `seq_len` or `seq_along` to get the range. Do this everywhere in your code.


```
            R/internal.R
151:            for (i in 1:length(otu.names)) {
183:            for (i in 1:length(names)) {
314:                                x <- data[order(colnames(data[1:(ncol(data) -
320:                                    (x[, 1:(ncol(x) - 1)], 2, sum) >=
327:                                        (data.0[,1:(ncol(data.0) - 1)], 1, max)
332:                                            (data.1[, 1:(ncol(data.1) - 1)], 1,
338:                                             apply(data.2[,1:(ncol(data.2) -
360:    for (i in 1:length(df$samples)) {
373:    for (i in 1:length(df$correct)) {
391:  for (i in 1:length(df$correct)) {
441:                        for (i in 1:length(df$correct)) {
463:                        for (i in 1:length(df.sort$age)) {
468:                        for (i in 1:length(df.sort$age)) {
493:                        for (i in 1:length(df$correct)) {
520:                          for (i in 1:length(sorted$col)) {
```


* For each loop or apply statement, consider carefully if it can be vectorized

internal.R: l 60

```
    #calculate CLR
    x.clr <-
    t(apply(data.0, 1, function(x) {
        log(x) - mean(log(x))
    }))


    # Use this instead
    t(log(data.0) - rowMeans(log(data.0)))
```

internal.R: l153

```
    for (i in 1:length(otu.names)) {
        if (!(otu.names[i] %in% otus)) {
            otu.missing[i] <- otu.names[i]
        }
    }

    # This does the same thing as above, but is vectorized
    otu.missing  <- otu.names[!otu.names %in% otus]
```
  
 internal.R: l 309

```
    d.frac <- apply(data.2, 2,
                        function(x){x/sum(x)})

    # This does the same thing as above, but is vectorized
     t(t(data.2) / colSums(data.2))

```


* Something went wrong with your function indentation after `omicplotr.getRemovedFeatures` in internal.R. Use the `formatR` package to fix it if you have issues. Do this for all your R files. It makes it very hard to read code which is not indented properly.


* There many apply functions in your code, which are not needed. `which(apply(x,2,sum)` in internal.R: l294. There is a function called `colSums`. Use that instead to vectorize your code. Use these vectorized functions instead of writing your own `sapply`, `apply` functions everywhere. Use vectorized versions of `max` as well, look at `matrixStats::colMaxes` and other similar functions. Your data seems to be in a data.frame, try `pmax` for similar vectorization.

* Internal.R: l327 (and others) You use `1:(ncol(x) - 1` in some apply functions, use seq_len or seq_along, whichever is more appropriate. Do not use `1:length(X)`, `1:ncol(x)`, `1:nrow(x)`.

* Instead of `sapply` use `vapply`, inst/shiny-app/server.r

```
    1133-    for(i in 1:dim(taxon)[1]){
    1134-      genera <- c(genera, sapply(strsplit(as.character(taxon[i, ]), "[[:punct:]]"),
    1135-      "[", 6))
    1136-    }

    ## This is what it will look like
    genera <- c(genera,
    vapply(strsplit(as.character(taxon[i, ], "[[:punct:]]"),
          "[", 6, character(1)))
```

`vapply` allows:

Slight speed improvement

Improves consistency by providing limited return type checks.

It is more verbose, but gives more informative error messages and never fails silently. It is better suited for use inside other functions.


* This is also vectorizable, internal.R : l397


```
                                        #colour the colour column for up to ten colours
    for (i in 1:length(df$correct)) {
        if (is.na(meta[column][df$correct[i], ])) {
            df$colour[i] <- "black"
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[1])) {
            df$colour[i] <- colours[1]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[2])) {
            df$colour[i] <- colours[2]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[3])) {
            df$colour[i] <- colours[3]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[4])) {
            df$colour[i] <- colours[4]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[5])) {
            df$colour[i] <- colours[5]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[6])) {
            df$colour[i] <- colours[6]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[7])) {
            df$colour[i] <- colours[7]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[8])) {
            df$colour[i] <- colours[8]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[9])) {
            df$colour[i] <- colours[9]
        } else if (meta[column][df$correct[i], ] ==
                   as.character(u[10])) {
            df$colour[i] <- colours[10]
        }
    }

    ## Use this instead
    idx = match(meta[column][df$correct], as.character(u))
    df$colour = colours[idx]
    df$colour[is.na(df$colour)] = "black"
```

* Internal.R: l 528
```
        sorted$col[sorted$col == 1] <- c[1]
        sorted$col[sorted$col == 2] <- c[2]
        sorted$col[sorted$col == 3] <- c[3]
        sorted$col[sorted$col == 4] <- c[4]
        
        # Use this instead
        sorted$col  <- c[sorted$col]
```

**Comment by dgiguer** [comment]
Hi @nturaga 

Thank you for the feedback and suggestions. I have implemented the changes you have suggested, vectorizing as many loops and apply statements as I could. I used `matrixStats` where appropriate. As for the vignette, when it is built to .pdf it should include screenshots if it builds correctly. I also added information in the vignette on how to load the data and metadata, and where to find the .txt files. 

Thanks, 
Daniel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dgiguer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"omicplotR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/omicplotR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
