### ISSUE TITLE
martini

### ISSUE THREAD

**Issue by hclimente** [Bioconductor/Contributions#576]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hclimente/martini/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@LiNk-NY will review your package; but please provide a more comprehensive Description: -- more like a paper abstract describing what your package does, the methods or approaches used, and especially compared to alternatives.

**Comment by mtmorgan** [comment]
Hi -- it's very fragile for us to support third-party libraries that require custom installation. Are there other solutions, e.g., including & building the library in the package itself (using GNU make)? Is the gin library cross-platform (Windows, macOS, Linux)?

**Comment by hclimente** [comment]
Hi @mtmorgan,

thanks for your suggestions. I have written a better explanation to Description field and README. And yes, I make sure libgin compiles in both Linux and macOS via Travis; I don't have access to a Windows computer to test it.

I share your concern about using the custom third-party library, libgin. I hope there will be doable suggestions, as I haven't found other R packages that work like this that I can take as example. I think there might be potential including libgin into martini via git submodules. I tried in the past but the build turned out to be really fragile, as I needed to handle two build methods, CMake and make. I will keep exploring this idea by trying to remove Cmake of the equation.

As far as I understand, it wouldn't it be possible to distribute the compiled version of libgin as part of martini as, at the very least, it's too big. Is that right?

**Comment by mtmorgan** [comment]
In some ways what you're trying to do is analogous to the packages Rsamtools, Rhtslib, Rhdf5lib, etc -- wrap a C library in an R package as a way to make that C library available to other R packages. Maybe the most likely strategy is an 'ginlib' package (like Rhtslib or Rhdf5lib) whose sole responsibility is to make an R package containing gin, and then martini uses that (the way csaw imports Rhtslib).

Probably there are technical problems in addition to size with distributing the compiled library; I don't think that's a particularly good direction.

**Comment by LiNk-NY** [comment]
Hi Héctor, @hclimente 

It seems like creating a `ginlib` R package and then having martini depend on the library is the viable solution.

Is this something that you would like to pursue? 

Regards,
Marcel

**Comment by hclimente** [comment]
Dear @mtmorgan  and @LiNk-NY,

Thanks a lot for the examples. It seems indeed a reasonable, robust solution, and something I want to pursue. However I can't say at the moment how long till I have finished the conversion. If that is okay, I will update you about my progress before February.

**Comment by hclimente** [comment]
Dear @mtmorgan and @LiNk-NY,

As suggested, I have simplified the whole installation to a
`biocLite("hclimente/martini")` command. Following Rsamtools example, I have created [Rgin](https://github.com/hclimente/Rgin) as wrapper of the C++ library. Rgin compiles on MacOS and Linux, and passes R CMD check with only 2 warnings. My intention will be to solve them and submit it to CRAN.

Is there any other issue I would need to address before the review?

**Comment by LiNk-NY** [comment]
Hi Héctor, @hclimente
You can use [appveyor](https://www.appveyor.com/) to test your package on Windows.

Why not submit the `Rgin` to Bioconductor? 
The submission will go hand in hand with the current package. 

Regards,
Marcel

**Comment by hclimente** [comment]
Hi Marcel,

I will work on the Windows version starting this week, as soon as I can get my hands on a Windows machine!

I planned to submit `Rgin` to CRAN as at this moment it is very limited. It is just a large C++ library other R packages can link to, without neither an R interface, good documentation, nor vignettes. And at this moment, I don't think investing it is relevant enough to invest that kind of time on the submission. Of course, if it is possible to submit it to Bioconductor with minimal changes, I would like to do so!

Best,
Héctor.

**Comment by LiNk-NY** [comment]
Hi Héctor, @hclimente

The lib package does not have to be extensively documented.
Here is an example of one that was recently accepted:
https://github.com/DEIB-GECO/RGMQLlib

Have you looked at [appveyor](https://www.appveyor.com/)?

Regards,
Marcel

**Comment by hclimente** [comment]
Great then, let's do a joint submission!

Yes, I checked appveyor. I will use it to ensure that I don't break anything from the moment I get it to compile on Windows. For the development, however, I think borrowing one of my labmate's computer would be (slightly) less nerve-wrecking than a cloud-based approach :)

**Comment by hclimente** [comment]
Dear Marcel, 

both `martini` and `Rgin` can be installed in all three platforms now.

Best regards,
Héctor.

**Comment by LiNk-NY** [comment]
Hi Héctor, 
Can you submit the `Rgin` package to the `Bioconductor/Contributions` repository?

Best regards,
Marcel

**Comment by hclimente** [comment]
[Sure](https://github.com/Bioconductor/Contributions/issues/644)!

**Comment by LiNk-NY** [comment]
Hi Héctor, @hclimente 
Thank you for submitting to Bioconductor. 
I have reviewed `martini`, a package for enhancing GWAS studies with SNP networks.

Please see the review below. If you have any questions, please contact me here. 

Best regards,
Marcel

---

# martini #575

## DESCRIPTION

* Format the file to have a limit of 80 column width.
* Remove the `Remotes` field. `Rgin` will be available in Bioconductor
concurrently with your submission.

## NAMESPACE

* Looks okay.
* What is the reason for importing the bracket `[` from `snpStats`?

## R

* Don't use unexported functions in examples. Either you want to consider
exporting them or not show their functionality directly.
* Consider using a more formal structure rather than a list for data storage
and manipulation
* Consider using `switch` instead of a series of `if`/`else` statements.
* Avoid creating sequences using `1:n` notation. Use the more robust
`seq_len(n)` or `seq_along(n)`.
* Avoid using numeric indices and use more robust character references when
subsetting.


Minor: 
* Make sure you are writing everything out in the man pages, such as `LD` for
"linkage disequilibrium".
* Specify `data.frame` or `DataFrame` in the man pages (ex: param `ld` in
`R/ld.R`)
* Use more robust double bracket `[[` extraction rather than the dollar sign
(`$`).
* Why not `genes$start_position[genes$start_position < 0] <- 0` instead of
using `ifelse`?
* Consider encoding your data in a `data.frame` rather than in a series of
`if` `else` statements in `encode_gwas`.

## vignettes

* It looks like your simulate phenotype vignette is incomplete.

## man

* Your documentation looks good. You even document unexported functions. :+1:
* Make sure you are explaining acronyms where needed.
* Try not to use cryptic argument names (e.g., for `N` use `nperm`; `n`, `p`). 

## tests

* Looks good.

**Comment by hclimente** [comment]
Dear @LiNk-NY,

Thanks for your review. I feel that the code has implemented as result of your suggestions! Please, find below my answer to all of them. I have implemented most. For a few I would need further clarification, as they involve practices I am not familiar with.

## DESCRIPTION

> Format the file to have a limit of 80 column width.

✅ Ok.
    
> Remove the Remotes field. Rgin will be available in Bioconductor concurrently with your submission.

✅ Ok.

## NAMESPACE

> What is the reason for importing the bracket [ from snpStats?

✅ It causes martini to load SnpMatrixes and be able to deal with them. I have fixed it by importing the class, instead of the operator that implicitely loads the class.

## R

> Don't use unexported functions in examples. Either you want to consider exporting them or not show their functionality directly.

Unless I have missed one, I am only using unexported functions in the examples of those same functions. I think it is a nice, at-a-glance example for the developer. Is that discouraged?

> Consider using a more formal structure rather than a list for data storage and manipulation

Do you mean the omnipresent `gwas` list? That is the output of the function `snpStats::read.pedfile` that the user will use read the input. I am not sure I can do much in this regard.

> Consider using switch instead of a series of if/else statements.

✅ I have replaced if/else statements by switch in get_evo_settings(), ldweight_edges() and encode_gwas(). I think it is much cleaner now.

> Avoid creating sequences using 1:n notation. Use the more robust seq_len(n) or seq_along(n).

✅  I have replaced two instances of 1:n by seq_len(n) in test_cones_modules().

> Avoid using numeric indices and use more robust character references when subsetting.

I do so to avoid the user having the specific colnames in the input data.frame. Is it preferred that I document the required format of the data.frame and access it by name?

> Make sure you are writing everything out in the man pages, such as LD for "linkage disequilibrium".

✅ I have updated ldweight_edges() accordingly. In addition, I have removed ld_prune(), as there are other tools, both in R and in the outside world that perform the task more efficiently.

> Specify data.frame or DataFrame in the man pages (ex: param ld in R/ld.R)

✅ Ok.

> Use more robust double bracket [[ extraction rather than the dollar sign ($).

Would you mind expanding on this or pointing me to some resource explaining this point? I have seen how it is more robust when dealing with lists. Is it the same when dealing with data.frames? I would like to avoid using it as much as it is not improving the code or disrespects a coding standard, as in my opinion it impacts negatively on both readability and "writability".

> Why not genes$start_position[genes$start_position < 0] <- 0 instead of using ifelse?

✅ Ok.

> Consider encoding your data in a data.frame rather than in a series of if else statements in encode_gwas.

✅ Ok.

## vignettes

> It looks like your simulate phenotype vignette is incomplete.

Ups. Time to finish it. I will get back to you about this with the remaining points.

## man

> Your documentation looks good. You even document unexported functions. 👍

✅ Thanks!

> Make sure you are explaining acronyms where needed.

✅ I have searched for acronyms in the man pages. I have explained all instances of LD. I spelled out the first instance of the three networks documented (GS, GM and GI) in their respective man pages. I have left as-are GWAS and SNP, as they are common vocabulary among the GWAS-community this package is oriented towards. Would you agree with that?

> Try not to use cryptic argument names (e.g., for N use nperm; n, p).

✅ I have improved cryptic arguments in simulate_causal_snps(), calculateG() and test_cones_modules().

**Comment by LiNk-NY** [comment]
Hi Héctor, @hclimente 

Thank you for making those changes. Please see my response below. 

> Avoid using numeric indices and use more robust character references when subsetting.
> > I do so to avoid the user having the specific colnames in the input data.frame. Is it preferred that I document the required format of the data.frame and access it by name?

The preferred way of doing this would be to allow the user to enter the name of the column that he
wants to operate on so that you will only handle the argument inside the function regardless of
what the name of the column in the `data.frame` may be. 

It really depends on what you're trying to accomplish. But another method that you could use 
is to create a data structure that will account for the importance of these columns in its structure. 

With regards to `[[` versus `$`: 
I don't have any resource at hand. Just be aware that the `$` operator uses fuzzy matching internally which can be a problem when a list has similar names or when you expect a name to be present 
in a list. 

```
example(data.frame)
dd <- as.list(dd)
names(dd)
dd$f
```

Ideally, you'd have a robust S4 class structure with validity checks and data acessors 
that do not need these type of semantics but this is not possible when using external
classes. 

Also, it's great that you provide examples for unexported functions. This is not a problem. 
You could mark them with `@keywords internal` as explained [here](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html). 

Best regards,
Marcel

**Comment by hclimente** [comment]
Dear @LiNk-NY,

Thanks a lot for your input. I see how all the suggestions make more sense than what I was doing before. Accordingly, I have made the following changes to `martini`:

- Finished vignette about how to simulate phenotypes.
- `$` replaced by `[[` for all user-provided data structures, and for most internal data.structures, where the names are under better control.
- Unexported functions have the `@keywords internal` tags.
- Added arguments col_ppi and col_genes to get_GM_network and get_GI_network allowing the user to use custom column names for the input data.frames. This replaces previously used numeric indexes.

Best regards,
Héctor

**Comment by LiNk-NY** [comment]
Hi Héctor, @hclimente 

Thanks for making those changes and contributing to Bioconductor! 
Your package has been accepted. 

Best,
Marcel

**Comment by hclimente** [comment]
Thank you for your dedication and helpfulness Marcel 😄

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hclimente.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"martini\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/martini

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
