### ISSUE TITLE
TCGAbiolinksGUI.data

### ISSUE THREAD

**Issue by tiagochst** [Bioconductor/Contributions#577]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI.data

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi @tiagochst ,

Thanks for your contribution to Bioconductor. Here is the official review of your data package. Please review and fix the follow issues and do a version bump before you do any valid commits to trigger a build. Thanks! 

## DESCRIPTION
- Should depend on R (>= 3.5.0). Since new packages will go to Bioc devel (Bioc 3.7), which works with R devel (3.5.0).
- typo for "fololowing" in `It includes the fololowing objects: `
- put the github links in DESCRIPTION instead of in vignette.
```                                                                                                                                                        
URL:https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI.data
BugReports: https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI.data/issues
```                                            

## vignette
- Install and load a package officially from Bioconductor by using the following code. You can include the github urls in the `DESCRIPTION` file if you want.

install the package:
```{r, eval=FALSE}
source("https://www.bioconductor.org/biocLite.R")
bioLite("TCGAbiolinksGUI.data")
```
Load the package:
```{r, eval=TRUE}
library(TCGAbiolinksGUI.data)
```

- put explanatory texts in main texts rather than inside R code chunks.
  
- avoid `eval=FALSE` for a vignette, and include runnable R code and examples for users.
  
- redundant texts of `TCGAbiolinksGUI.` in the end of this sentence in Introductor? ```This document provides an introduction of the TCGAbiolinksGUI.data, which contains supporting data for TCGAbiolinksGUI (T. C. Silva et al. 2017). TCGAbiolinksGUI. ```

## R
- write all data documentation into one `TCGAbiolinksGUI-data.Rd` file. You can do this by include `@rdname TCGAbiolinksGUI-data` for all the data documentation entry in the `TCGAbiolinksGUI.data.R` file.
- remove `dontrun` for all documentation. It doesn't take much time and could at least check for typos.

## MAN 
- put all data documentation into one `.Rd` file.
- add more details for some of the dataset, e.g., `maf.tumor` by using `@description` in documentation. The current documentation is not clear enough. Check other data documentation also.

Cheers, 
Qian

**Comment by tiagochst** [comment]
@Liubuntu Fixed. I'm just not sure if the man files are what you expected. I personally prefer to have several .Rd pages than only one.

**Comment by Liubuntu** [comment]
## DESCRIPTION
- typo IN "fololowing" in "It includes the fololowing objects: "

## Vignette
- put any of the needed packages within vignette into `Suggests` field in DESCRIPTION.
```
## library(readr)
## library(readxl)
## library(dplyr)
## library(caret)
## library(randomForest)
## library(doMC)
## library(e1071)
```

- It is not appropriate to show all the contents for `data(glioma.idh.model)`. They are showing like thousands of lines? The purpose of writing the vignette is to familarize users of your package and the main function with some short runnable examples, not with huge unreadable contents. You can show the `names(glioma.idh.model)`, and show some `head/tail` of the important slots inside this data.

- in Section `2.3 Creating Training models`, put corresponding code for each subsection under the explanatory contents, e.g., put corresponding code following `1. RF to classify between IDHmut and IDHwt:` and start a new explanatory contents of `2. RF to classify IDHmut specific clusters (Fig S3A):` and follow the corresponding code for that.

- you may want to remove `and` in the section name of `1.1 Installing and TCGAbiolinksGUI.data`?

- A very big code chunk is not readable for users and not very informative. split the big chunk of R code into smaller ones, and use some of the comments inside R code chunks as splitting points.

## Man

- the `@rdname` usage is correct and looks good to put all datasets into one `.Rd` file because they are in the same type. it's common and recommended to put all datasets / class-related things / method-related things into one `.Rd` file. But anyway, if you prefer to document them separately, it is ok and will not incure any problem for building.

- you manual is not generating correctly with all your documented datasets. Please refer: http://r-pkgs.had.co.nz/data.html#documenting-data and http://r-pkgs.had.co.nz/man.html for documentation. Let us know if you have further question.

**Comment by tiagochst** [comment]
@Liubuntu DESCRIPTION and Vignette were fixed, but I still kept  data(glioma.idh.model) as they are not big.

For the man pages, I added the package with a link to all datasets and a .Rd for each dataset as the ggplot package does (https://github.com/tidyverse/ggplot2/blob/8778b48b37d8b7e41c0f4f213031fb47810e70aa/R/data.R)

<img width="430" alt="screen shot 2017-12-28 at 9 56 54 am" src="https://user-images.githubusercontent.com/145529/34410245-dc5f8cd4-ebb5-11e7-86bd-1ffbed09bb48.png">


<img width="431" alt="screen shot 2017-12-28 at 9 57 02 am" src="https://user-images.githubusercontent.com/145529/34410244-dc307534-ebb5-11e7-9e43-6b67a1f2bfaf.png">

**Comment by Liubuntu** [comment]
HI, 

Sorry I think it was on my side generating thousands of lines for your data. For what you have included in your comments, 20 lines is absolutely good. I will take another look at especially your vignette. The man page looks good too. I would say it is quite close to acceptance.

Qian

**Comment by Liubuntu** [comment]
Hi @tiagochst , 

Now I could generate the correct vignette and it looks awesome! So I will have it accepted now. 

Cheers!

Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tiagochst.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TCGAbiolinksGUI.data\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TCGAbiolinksGUI.data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
