### ISSUE TITLE
Bias-free Footprint Enrichment Test (BiFET): A robust statistical test for transcription factor footprint data analyses

### ISSUE THREAD

**Issue by nlawlor** [Bioconductor/Contributions#585]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/UcarLab/BiFET

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Thanks for your contribution. A key part of Bioconductor packages is reuse of existing data structures to facilitate interoperability and robust computation. Your package has no Bioconductor dependencies, despite working with data that has excellent support, for instance the peak file at the start of your vignette should b represented as a GRanges() object rather than plain data frame.

Before adding your package to the review queue, please update it to use GenomicRanges and [other relevant Bioconductor representations][1]. You _must_ use these as inputs and outputs to user-facing functions; it will often be highly advantageous to use them in your internal package code, too.

In addition, your vignette must have code chunks primarily with `eval = TRUE`, so that the vignette accurately reflects the current capabilities of your software.

Please leave a comment here when you have updated your package along these lines.

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by nlawlor** [comment]
Thank you very much for the feedback!

The authors and I have updated the package code to represent peak and motif files as appropriate GenomicRanges objects. 

In addition, we have updated all package vignette chunks to `eval = TRUE`.

Thank you,
Nathan

**Comment by nlawlor** [comment]
Hello, 

The future maintainer of this package (Ahrim Youn (Ahrim.Youn@jax.org)) has been subscribed to the bioconductor support and level sites. Additional changes were made to the package to address remaining errors and warnings. 

Thanks,
Nathan

**Comment by lshep** [comment]
Hello, 
Thank you for you interest in Bioconductor.  Your package looks good with some minor revisions. Please see the following notes. 

**README**
- [ ] change install to bioconductor 
```
source("https://bioconductor.org/biocLite.R")
biocLite("BiFET")
```

**NAMESPACE**
- [ ] add imports for GenomicRanges, stats, and ppoibin since there aren't a lot of functions you are importing I might suggest actually an importfrom instead of import  
Then you could remove the ::  in the R code as the functions will be available 
Something along the lines of 
#' importfrom GenomicRanges GRangesList findOverlaps
#' importfrom stats quantile t.test binomial glm optim phyper
#' importfrom ppoibin ppoibin

**GENERAL**
- [ ] Please remove .DS_Store files from all directories

**INST/EXDATA**
- [ ] PBMC_PIQ.bed and islet_PBMC_consensus_peak.Rdata  - These don't appear to be used anywhere can they be removed. 

**MAN**
- [ ] Please document the input_peak_motif.Rdata  data.  Essentially the description you have in your vignette should also be in a man page describing how it was created and what objects are returned. 

**VIGNETTE:** 
- [ ] you only need one 
```
library(BiFET)
library(GenomicRanges
peak_file <- system.file
load(peak_file)
```
Don't repeat those in section 2 or 3.


**R CODE:**
- [ ] As mentioned, add the packages/package functions to the NAMESPACE and then the :: for functions will not be needed. 
- [ ] There are a few times you use 1:nrow(...)  Please use seq_along instead of 1:n/1:nrow
- [ ] Is the separate binding_TF_per_peak function really needed?  It seems like you could not expose this to the user and then have GRpeak and GRmotif as the only arguments to calculate_enrich_p.  Then you can do the matrix formation and grab the reads and GC counts for the user instead of requiring them to do that. 
  
 Please make the above changes and comment back here with what has been adjusted and any other clarification.  

Thank you

**Comment by nlawlor** [comment]
Hi Ishep,

- Changes to the README, NAMESPACE, GENERAL, and VIGNETTE have been made following your feedback above.

- Additional documentation has been provided for "input_peak_motif.Rdata" within the MAN section.

- PBMC_PIQ.bed and islet_PBMC_consensus_peak.Rdata files have been removed from INST/EXDATA.

- The "binding_TF_per_peak" function is no longer exposed to the user and the "calculate_enrich_p" function has been modified to instead take "GRpeaks" and "GRmotif" as input arguments. 

- R code has been updated to use seq_along instead of "1:nrow" and "::" references have been removed.

Thank you,
Nathan

**Comment by nlawlor** [comment]
Hi Ishep,

I updated the package README to alternatively include installation instructions via "install_github" because our group has a manuscript for BiFET currently undergoing review. As installation via biocLite() is not yet available, we added these additional instructions so our code is easily accessible for our manuscript reviewers. 

Thanks,
Nathan

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nlawlor.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BiFET\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiFET

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
