### ISSUE TITLE
DropletUtils

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#586]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarioniLab/DropletUtils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hi Aaron, 

I am having trouble building the package locally. I keep getting 
```
get_cell_barcodes.cpp:2:23: fatal error: c++/H5Cpp.h: No such file or directory
#include "c++/H5Cpp.h"
```

Martin suggested that it is a recent change in Rhdf5lib that may need an adjustment in your package, somewhere perhaps there is `#include  "c++/H5Cpp.h"` and should instead be `#include "H5Cpp.h"`

**Comment by LTLA** [comment]
Yes, that's right - I was waiting for the latest update to _Rhdf5lib_ to make it to the BioC-devel servers. I will update _DropletUtils_ ASAP.

**Comment by LTLA** [comment]
The package is CHECKing properly on x64 but not on i386, which suggests that the problem is occurring in `src/get_cell_barcodes.cpp` where I'm explicitly using 64-bit integers. However, if that were the case, a great many of the tests in `test-swapped.R` should fail, rather than just the 7 failures observed in the build log. I can't think of the nature of the fault; any suggestions?

**Comment by lshep** [comment]
Not off hand but maybe @hpages or @mtmorgan  might have some?

**Comment by mtmorgan** [comment]
the unit test is too high-level to see where problems might be occurring. As you say it's likely a code path uniquely covered by the test; it could be integer overflow or memory corruption (through off-by-one indexing), or ... sorry not to be more helpful

**Comment by LTLA** [comment]
I added some tests to check the barcode extraction from the 10X Genomics HDF5 file (i.e., the part of the C++ code that requires 64-bit integers). The good news is that this works fine on i386; the bad news is that the other failures are still occurring. Running `test-swapping.R` with valgrind on my unix system doesn't show anything, so it's probably not some memory issue in my C++ code.

The only remaining explanation is that of floating point shenanigans on i386. There are a number of tied doubles that weren't causing issues on my 64-bit machine, and this would explain the differences. I've modified `minfrac` so that it should no longer be possible to obtain ties - let's see how this goes.

**Comment by LTLA** [comment]
Thanks Lori. I've usually refrained from putting specialized plotting functions in packages that I've authored, because aesthetic choices tend to vary quite dramatically between different people (e.g., _ggplot_ vs base, where to put the legend, colour of the points, and so on). 

Even between members of the same lab (i.e., the one I'm in), we disagree vehemently over plotting aesthetics, so I don't know how useful a central plotting function would be.

**Comment by lshep** [comment]
Fair enough.  Cheers!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"DropletUtils\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DropletUtils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
