### ISSUE TITLE
recountNNLSdata

### ISSUE THREAD

**Issue by JMF47** [Bioconductor/Contributions#589]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JMF47/recountNNLSdata
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by JMF47** [comment]
Hey @nturaga! Happy new year :) I was wondering is it alright at this point to submit the related package for this? 

Best,
Jack

**Comment by nturaga** [comment]
@JMF47 Please do, I will take a look at both this week.

**Comment by JMF47** [comment]
https://github.com/JMF47/recountNNLS

**Comment by JMF47** [comment]
AdditionalPackage: https://github.com/JMF47/recountNNLS

**Comment by nturaga** [comment]
Hi @JMF47,

Please make sure that you have a clean BUILD. It is easier to review packages without any build ERRORs and as few NOTEs as possible

I'm particular about a couple of the NOTEs , i.e the sapply, and seq_len/seq_along points in the build report. Take a look at http://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#coding-practices-checks

**Comment by nturaga** [comment]
Hi @JMF47 ,

This package might be better served by hosting the data on ExperimentHub.

https://github.com/Bioconductor/ExperimentHubData/blob/master/vignettes/CreateAnExperimentHubPackage.Rmd.

You already have most of the pieces in place, but there is little overhead. Please check the document I posted above. I'll post the rest of the review below,

recounNNLS + recountNNLSdata review
============

# R CMD build

* ok

# R CMD INSTALL 

* ok

# DESCRIPTION

* Ok.

* Enhances: is empty, remove this if not needed.

* Imports: is empty in the data package DESCRIPTION. Remove it if not needed.

# NAMESPACE

* ok

# man

* Ok

# vignette

* Vignette is missing title, and BiocStyle formatting. Please use BiocStyle package for this.

* The vignette could also be more informative.

# R

* Package has ERROR on the build report, please fix before a further review.

* Consider using BiocParallel::bplapply for all the parallel tasks instead of mclapply.

* sapply should be replaced by `vapply`, everywhere. This is pointed out in the required coding style for bioconductor, http://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#coding-practices-checks

```
R/getExCounts.R
46:      cov_binned = sapply(names(grl_keep), .processChr, cov_rle_matched, grl_keep)

R/processPheno.R
57:      pheno$rls_group = sapply(pheno$rls, function(x) rls_avail[which.min(abs(rls_avail-x))])

R/processReadLength.R
37:            reads = do.call(rbind, sapply(info, function(x)x[[1]]))
41:            vars = do.call(rbind, sapply(info, function(x) x[[2]]))
43:            colin = do.call(rbind, sapply(info, function(x) x[[3]]))
78:      ems_sub = ems_sub[sapply(ems_sub, length)>0]
105:                        beta = sapply(lm_info, function(x) x[[1]])
106:                        Vbeta = sapply(lm_info, function(x) x[[2]])^2
```

* `1:length`, 1:nrow, 1:ncol, etc, should be replaced by seq_len or seq_along

```
R/getExCounts.R
32:      rownames(totCov) = paste0("e", 1:length(bins))

R/processReadLength.R
159:      for(i in 1:length(P_list)){
```

* You don't need `stop` and `paste0`, `stop` does the concatenation. In this line, you need the second paste0, but not the first.

```
R/processPheno.R
47:                  stop(paste0("Check the columns of your input meet requirements for function: ", paste0(required_columns, collapse=", ")))
```

* Use `is(pheno$paired_end, "logical")` instead of `class(pheno$paired_end)!="logical"`. Do this everywhere.

* Remove commented out code in recountNNLS.R and all remaning files.


* Code needs reformatting in a few files, use formatR if needed.

# data package

* vignette contains no information, please document how you generated the data.

* data files: ok

I'll get back to you with a second review once you have moved the data to ExperimentHub

**Comment by nturaga** [comment]
Hi @JMF47 Once you make your changes, please bump the version and let me know when you are ready for the second review.

**Comment by nturaga** [comment]
Hi @JMF47 Please respond if you are still working on the package. If not, we can close the issue and re-open at a more appropriate time.

**Comment by JMF47** [comment]
Hi @nturaga apologies about the delay. Yes, let's close this for now and reopen at a better time. Thanks!
