### ISSUE TITLE
DEScan2

### ISSUE THREAD

**Issue by drighelli** [Bioconductor/Contributions#590]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/drighelli/DEScan2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by drighelli** [comment]
I had a problem registering to the devel mailing list, now everything should be OK...

**Comment by vobencha** [comment]
Hi,
Before I do a full review can you tell me why the name is DEScan2 vs DEScan? Is this meant as a replacement or a second version of an existing package?
Valerie

**Comment by drighelli** [comment]
The first version is only available via github at this link https://github.com/jnkoberstein/DEScan .
This is intended as a second version completely rewrote using bioconductor coding style, functions and data structures. The main idea is the same, but the package is totally new.
We decided to keep the old name just adding the 2 at the end also because the two versions are intended as two separated products.

**Comment by vobencha** [comment]
OK thanks. I'll try to look at this today or tomorrow.

**Comment by vobencha** [comment]
Please bump the version to 0.99.1 and address these:
```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply() found in files:
    R/countMatrixFunctions.R (line 77, column 19)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
    R/finalRegionFunctions.R (line 94, column 45)
    R/finalRegionFunctions.R (line 122, column 34)
    R/finalRegionFunctions.R (line 300, column 15)
    R/peakCallFunctions.R (line 81, column 21)
    R/peakCallFunctions.R (line 325, column 45)
```

**Comment by vobencha** [comment]
Full review:

1) All man pages need running examples
2) Please remove coverage.html from vignettes/ (I don't think this is used ...?)
3) I would recommend using tempdir() and tempfile() as defaults for 'filepath' and 'filename' in your save functions.
4) Depend or Import all of GenomicRanges
The package is too heavily dependent on GenomicRanges to not depend on or import this package. It's not such a heavy package that it will slow down loading of DEScan2. Was there a particular reason why you have not done this?

    Your code creates and manipulates GRanges so the class methods and accessors are necessary. To accomplish this you library(GenomicRanges) in all examples. Indeed the products produced by DEScan2 don't "work" unless GenomicRanges is loaded.

5) Use accessors, seqinfo(), seqnames(), seqlengths() etc. instead of direct slot access '@':
```
~/repos/github/packageReview/DEScan2/R >grep '@seqlengths' *
peakCallFunctions.R:                            chrLength=chrGRanges@seqinfo@seqlengths,
utilities.R:    if( (sum(is.na(GenomeInfoDb::seqinfo(bedGRanges)@seqlengths)) > 0) ||
utilities.R:    idxm <- which(maxlengths >= chrSeqInfo@seqlengths)
utilities.R:        widths[idxm] <- chrSeqInfo@seqlengths - starts[idxm]

~/repos/github/packageReview/DEScan2/R >grep '@seqinfo' *
peakCallFunctions.R:                            chrLength=chrGRanges@seqinfo@seqlengths,
peakCallFunctions.R:            chrZRanges <- createGranges(chrSeqInfo=chrGRanges@seqinfo,
peakCallFunctions.R:                                            seqlengths=chrBedGRanges@seqinfo,
utilities.R:        GRanges@seqinfo <- sqi
utilities.R:        bedGRanges@seqinfo <- bedGRanges@seqinfo[as.character(uniqueSeqnames)]
utilities.R:    interestedChrs <- GRanges@seqinfo@seqnames
utilities.R:            bgr@seqinfo <- GRanges@seqinfo[x]

~/repos/github/packageReview/DEScan2/R >grep '@seqnames' *
countMatrixFunctions.R:    regionsRN <- paste0(regionsGRanges@seqnames, ":",
finalRegionFunctions.R:                " and chromosome ", as.character(grj@seqnames@values),
peakCallFunctions.R:                        chrBedGRanges@seqnames@values,
utilities.R:        bed <- GenomicRanges::GRanges(seqnames=bed@seqnames,
utilities.R:    uniqueSeqnames <- droplevels(unique(GRanges@seqnames@values))
utilities.R:    seqNamesIdx <- which(genomeInfo@seqnames %in% uniqueSeqnames)
utilities.R:        sqi <- genomeInfo[genomeInfo@seqnames[seqNamesIdx]]
utilities.R:        sqi <- sqi[sqi@seqnames[order(sqi@seqnames)],]
utilities.R:    uniqueSeqnames <- droplevels(unique(bedGRanges@seqnames))
utilities.R:        (length(GenomeInfoDb::seqinfo(bedGRanges)@seqnames) == 0 ))
utilities.R:                length(GenomeInfoDb::seqinfo(bedGRanges)@seqnames))
utilities.R:        bedGRanges@seqnames <- droplevels(bedGRanges@seqnames)
utilities.R:                " located on sequence ",  chrSeqInfo@seqnames, ".",
utilities.R:    gr <- GenomicRanges::GRanges(seqnames=as.character(chrSeqInfo@seqnames),
utilities.R:    interestedChrs <- GRanges@seqinfo@seqnames
```

**Comment by vobencha** [comment]
Checking in - are you planning to submit a new version?
Valerie

**Comment by drighelli** [comment]
yes, sorry for this delay!
But I'm still fixing the revisions...
thanks!
dario

**Comment by drighelli** [comment]
Hi, 

we made all the requested revisions. 

But about this last warning we don't know how and if we have to fix it, we are not so expert on windows...

Valerie, what do you suggest?

Thanks,
dario

**Comment by vobencha** [comment]
Please explain why you feel you need the configure script. It is incredibly long and complicated ... 3637 lines.
What is it that's not being handled by default that makes this necessary?

**Comment by drighelli** [comment]
I didn't know there was a limitation on the configure script.
Anyway, I found another way without it in these days.
I proceed with a new version bump submission.
dario

**Comment by vobencha** [comment]
There isn't a limitation on the length of the script. It's more a question of whether or not it's necessary. No point in having an additional layer of complication if we don't need it. Since it's evidently not needed, thanks for removing it.

It looks like not all man pages have examples, e.g., generateDFofSamplesPerChromosomes.Rd. Please double check these. A man page that describes the package does not need examples but pages for functions or data files do.

Valerie

**Comment by drighelli** [comment]
No problem at all!

I fixed also the example, it was a forgetfulness.

Do I have to bump the version again?

thanks,
dario

**Comment by vobencha** [comment]
Yes, please do.

**Comment by vobencha** [comment]
Thanks for making the changes. The package is approved.

**Comment by drighelli** [comment]
thanks for your revisions @vobencha !

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/drighelli.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"DEScan2\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DEScan2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
