### ISSUE TITLE
scmeth

### ISSUE THREAD

**Issue by Divyagash** [Bioconductor/Contributions#592]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aryeelab/scmeth

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Divyagash** [comment]
Not quite sure why there is this error `ERROR: dependency Repitools is not available for package scmeth`
Build with travis seems to work fine, is this a problem with the build system?

**Comment by Liubuntu** [comment]
The ERROR you mentioned might be due to the building machine. Our people are working on that. 

Please look at the new building report for "malbec2", there is another error in your vignette: 
```
Quitting from lines 131-134 (my-vignette.Rmd) 
Error: processing vignette 'my-vignette.Rmd' failed with diagnostics:
'file' is not a slot in class "HDF5ArraySeed"
Execution halted
```
Please look to fix this while our people fixing the building error.

**Comment by Divyagash** [comment]
I am not getting any errors with the vignette when I use `devtools::check` in my local machine or in Travis CI. But the build in bioconductor is failing repeatedly. Any idea why this would happen?

**Comment by Liubuntu** [comment]
Hi, first please depend your package on R(>=3.5.0) in DESCRIPTION. Because the new packages will be in the Bioc devel 3.7 (not release 3.6), and the devel 3.7 will be consistent with the R development version of 3.5. 

2nd, please check the package version for `DelayedArray` and `SummarizedExperiment`. These packages are under active development. Please make sure to use the most recent versions from github, which are `0.5.15` and `1.9.5`.  

Please do the above and regenerate files in your `exdata` folder, like this: 
 ```directory<-system.file("extdata","bismark_data",package='scmeth')```
 and manually run your vignette and let me know further message.

I suspect there is a little bug in the package of `SummarizedExperiment` but not quite sure yet. So please let me updated for the latest error. Thanks. 

Qian

**Comment by Liubuntu** [comment]
I just made a pull request here: https://github.com/Bioconductor/SummarizedExperiment/pull/3

Please wait until it got merged into the master branch of `SummarizedExperiment` and use the updated version of `1.5.6`, and regenerate your files in `extdata`. Let me know for furtuer questions.

**Comment by Divyagash** [comment]
@Liubuntu Thank you for the input. I made the version changes and I am getting the following error `'loadHDF5SummarizedExperiment' is not an exported object from 'namespace:SummarizedExperiment'`

**Comment by PeteHaitch** [comment]
@Divyagash `loadHDF5SummarizedExperiment()` recently moved from **SummarizedExperiment** to the **HDF5Array** (https://github.com/Bioconductor/SummarizedExperiment/commit/4faf8e1eca1e96a22da74e61cba4975db7d6bc40 and https://github.com/Bioconductor/HDF5Array/commit/21a0d4420069fc3618a4dd79070136c8952b41d2). You'll need to add **HDF5Array** to the 'Imports' of your `DESCRIPTION` file and import `loadHDF5SummarizedExperiment()` into your `NAMESPACE`

**Comment by Divyagash** [comment]
I have made the specified version changes and I am currently using the function `loadHDF5SummarizedExperiment` from `HDF5Array` and I am having this previous error that I had `no slot of name "filepath" for this object of class "HDF5ArraySeed"`

**Comment by Liubuntu** [comment]
Hi, please depend on the newest version of `HDF5Array` package from github: https://github.com/Bioconductor/HDF5Array

The maintainer of `HDF5Array` has just moved the 2 functions of `save/loadHDF5SummarizedExperiment` from `SummarizedExperiment` into `HDF5Array`, and a test run of the these 2 functions seems work quite good for me.

**Comment by Liubuntu** [comment]
Did you import `HDF5Array::loadHDF5SummarizedExperiment()` into your NAMESPACE?

**Comment by Liubuntu** [comment]
Just a kind reminder that Bioconductor core team has a non-official rule for responses within 2 weeks of the technical review. Please make effort in addressing the issues and bump the version to trigger a valid build. But it does not necessarily to be fixing all within the 2 weeks. As long as you are making efforts in revising, the issue will keep open. Thanks!   

Your error seems not a hard one. if you are using `roxygen2` for generating the documentations, just add`@importFrom HDF5Array loadHDF5SummarizedExperimen` to have this function available in NAMESPACE, it will be ready to use. 

Have a good weekend!

**Comment by Divyagash** [comment]
HI @Liubuntu, Thank you for the input. Currently my `NAMESPACE` file looks like this 
```
# Generated by roxygen2: do not edit by hand

export(bsConversionPlot)
export(chromosomeCoverage)
export(coverage)
export(cpgDensity)
export(cpgDiscretization)
export(downsample)
export(featureCoverage)
export(mbiasplot)
export(methylationDist)
export(readmetrics)
export(repMask)
export(report)
import(BSgenome)
import(DT)
import(GenomicRanges)
import(SummarizedExperiment)
import(knitr)
import(magrittr)
importFrom(DelayedArray,colSums)
importFrom(DelayedArray,rowSums)
importFrom(GenomeInfoDb,seqlevelsStyle)
importFrom(HDF5Array,loadHDF5SummarizedExperiment)
importFrom(annotatr,annotate_regions)
importFrom(annotatr,build_annotations)
importFrom(annotatr,builtin_genomes)
importFrom(annotatr,summarize_annotations)
importFrom(bsseq,getCoverage)
importFrom(ggthemes,theme_tufte)
importFrom(scales,comma)
importFrom(stats,dbinom)
importFrom(stats,relevel)
importFrom(stats,sd)
importFrom(utils,read.csv)
importFrom(utils,read.delim)
importFrom(utils,read.table)
importFrom(viridis,scale_fill_viridis)
```

And following is the content of the `DESCRIPTION` file

```
Package: scmeth
Type: Package
Title: Functions to conduct quality control analysis in methylation data
Version: 0.99.12
Author: Divy Kangeyan <divyswar01@g.harvard.edu>
Depends: R (>= 3.4.0)
Imports:
  ggplot2,
  knitr,
  rmarkdown,
  bsseq,
  AnnotationHub,
  Repitools,
  GenomicRanges,
  reshape2,
  stats,
  utils,
  BSgenome,
  DelayedArray (>= 0.5.15),
  annotatr,
  SummarizedExperiment (>= 1.5.6),
  GenomeInfoDb,
  DT,
  ggthemes,
  scales,
  viridis,
  magrittr,
  dplyr,
  HDF5Array (>= 1.7.5)
Suggests:
  BSgenome.Mmusculus.UCSC.mm10,
  BSgenome.Hsapiens.NCBI.GRCh38,
  Biobase,
  BiocGenerics,
  Biostrings
Maintainer: Divy Kangeyan <divyswar01@g.harvard.edu>
Description: Functions to analyze methylation data can be found here.
             Some functions are relevant for single cell methylation data but most other
             functions can be used for any  methylation data.
             Highlight of this workflow is the comprehensive quality control report.
biocViews: DNAMethylation, QualityControl, Preprocessing, SingleCell
License: GPL-2
LazyData: TRUE
RoxygenNote: 6.0.1
VignetteBuilder: knit
```

But this error `no slot of name "filepath" for this object of class "HDF5ArraySeed"` seems to be persistent. Is this due to some difference in `HDF5ArraySeed` class vs. `HDF5Array`class?

**Comment by Divyagash** [comment]
I figured it is that the HDF5 files that I generated few weeks ago with previous version of the package are no longer compatible and I am working on this.

**Comment by Liubuntu** [comment]
Hi, 

your current error `ERROR: dependency Repitools is not available for package scmeth` is because that `Repitools` depends on an CRAN package which is not available. So nothing we can do now for this error. Not anyone's fault. 

I will go ahead review your package in a few days. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi, 

Thank you for submitting you package. Please look at the following issues and seek to address them. Always make a version bump to trigger a valid build. Please comment back when you are ready for a 2nd review. Thanks!

### DESCRIPTION
- Add a field for `Maintainer`. E.g.,
```
Author: Hervé Pagès
Maintainer: Hervé Pagès <hpages@fredhutch.org>
```

### NAMESPACE
Looks good.

### MAN/
- add documentation for the `scmeth` package. with `\type{package}` and `NULL` in the body. Refer to: http://r-pkgs.had.co.nz/man.html#man-packages. Put this documentation in a file called <package-name>.R under `R/`. E.g.,
```
#' scmeth: a package to ....
#'
#' some description...
#' @docType package
#' @name scmeth

NULL
```
- similar and non-clear description for `repMask` and `cpgDensity`.
-  typo in `downsample.Rd` documentation. `\description{ Downsample the CpG covergae matrix for saturation analysis}`

### Vignette/
- Keep only the `my-vignette.Rmd` in this folder. Remove all unnecessary folders and files. The `.html` file and `.R` file will be generated automatically when installing the package. If any files are needed inside the vignette, you could put them under `inst/ext/` and use `system.file()`.
- put your `2017-04-21_HG23KBCXY_2_AGGCAGAA_TATCTC_pe.M-bias.txt` in `/inst/ext` and use `system.file()` to call it in vignette. Also modify the calling in example of `mbiasPlot.Rd`.
- add `sessionInfo()` in the end of the vignette.

### R/
- general: put white space before and after the assignment signal `<-` for assignment. Go through your script and revise all!
- If there is default value for arguments, you should specify them in the function documentation. e.g., `cpgDiscretization<-function(bs,subSample=1e6,offset=50000,coverageVec=NULL)`.

- `report.R`: Since the arguments of `organism` and `genome` only takes specific values, it's suggested to write them in this way:
```
report <- function(bsObj,outdirectory,organism=c("Mmusculus", "Hsapiens"), genome=c("mm10", "hg38"), ...)
organism <- match.arg(organism)
genome <- match.arg(genome)
```
Same for the R scripts of `cpgDensity`, `repMask` and `featureCoverage` which takes these kind of arguments. It will do the automatic check to avoid wrong input.

- `cpgDensity.R`: `cpgDensity<-function(bs,organism,windowLength=1000)`, the `organism` has been used in both `GenomeInfoDb::seqlevelsStyle(organism)` and `Repitools::cpgDensityCalc`. However, these 2 arguments has different specification for these 2 function. 1st requires that `must have a ‘seqlevels’ method or be a ‘character’ vector.` and the 2nd function requires that `organism: The‘BSgenome’ object to calculate CpG density upon.`. So there are some inconsistency in using of the same `organism` argument. And that's why your example returns an error:
```
cpgDensity(bs,Hsapiens,1000)
        Error in GenomeInfoDb::seqlevelsStyle(organism) :
object 'Hsapiens' not found
```
Please check and revise your script.

### report: 

`inst/qcReport.Rmd`:L136, should the argument inside the function be param$genome instaed of genome? `featureCoverage(bs,c('genes_promoters','genes_exons',...), genome)`

**Comment by Divyagash** [comment]
Hi @Liubuntu,
                       I think I have addressed the comments that you pointed in the first review. Please take a look at the package for the 2nd review.

Thank you,
Divy

**Comment by Liubuntu** [comment]
Hi, 

Please check out the following comments and seek to address them. Comment back with any question and when you have fixed all and bumped the version. 

## MAN/
- The documentation of `scmeth.R` is not generated in this repo. (try add a white space after `#' ` for those don't).
- For `repMask` and `cpgDensity`, the argument `organism` used `Hsapiens` or `Mmusculus` in the example, but mentioned in documentation with full name, which is not clear to users by only seeing the documentation. You can make it clearer by adding the abbreviated name in documentation: `@parameter organism scientific name of the organism of interest, e.g. Mus musculus(Mmusculus) or Homo sapiens(Hsapiens)`.

## vignette
- Why do you have this file `vignettes/my-vignette_files/figure-html/unnamed-chunk-6-1.png` here? Seems it is not used inside your vignette. You should remove all unnecessary files here.
- Update section 2 name, and add `library(scmeth)` into new section 2, e.g., `2. Installation and package loading`. Remove the `library(scmeth)` in following codes.
- Since you have `library(scmeth)` in your vignette, you don't need to add `scmeth::` before calling any function.
-typo: "1. Introduction... scmeth package offers a few functions to **asseess** the quality of the methylation data."
- `3. Input files: ... can be read via loadHDF5SummarizedExperiment function in SummarizedExperiment package.`. This function is now in `HDF5Array` package. Please be consistent throughout.

Cheers!
Qian

**Comment by Divyagash** [comment]
Hi @Liubuntu,
                       I have updated the package according to the comments. Please take a look.
Thank you,
Divy

**Comment by Liubuntu** [comment]
Hi @Divyagash ,

Thanks for your efforts in contributing to Bioconductor. You package is accepted. Wish you success in your career, and Happy Chinese New Year!

Cheer,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Divyagash.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"scmeth\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scmeth

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by Divyagash** [comment]
Hi @Liubuntu,
                       Thank you for your time and suggestions for improving the package. Happy Chinese New Year to you as well.

Divy
