### ISSUE TITLE
kissDE

### ISSUE THREAD

**Issue by aursiber** [Bioconductor/Contributions#596]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aursiber/kissDE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Thanks for your package. Please update your code in line with the comments below, and provide a brief summary (including the @mtmorgan tag) when ready for further review. Remember to bump version numbers to trigger new builds.

# DESCRIPTION, NAMESPACE, vignette, man pages

All very good!

# R

- code looks basically well-structured; checking input parameters,
  using `message()`, etc.

- diffExpressedVariants.R:47 etc the 'copy-and-append' pattern `li <- c() ... li <- c(li, i)` is inefficient; better to extend with an index, e.g., `j <- j + 1; li[[j]] = i` or (best) vectorize.

- diffExpressedVariants.R:72, etc generally, `stop(paste(...))` can be simply `stop(...)` (also `message(paste())`, `warning(paste())`.

- kisssplice2counts.R:34 it's often cleaner to avoid long nested comments, e.g,.

        values <- c(
            "deletion", "insertion", "IR", "ES", "altA", "altD", "altAD", 
            "alt", "unclassified"
        )
        if (!element %in% values) {...
    
  This iteration can actually be vectorized
  
        test <- keep %in% values
        if (!all(test)) {
            ...
    
- kissplice2counts.R:103, etc. it seems like the fasta line parsing can be vectorized in many ways; even partial vectorizations, e.g., 

        lines <- readLines(fpath)
        lines <- lines[startsWith(lines, ">")]
        lines <- sub("^>", "", lines)
        strsplit(lines, "|", fixed=TRUE)
        
  are likely to provide significant performance gains, but I believe that much more of the code can be vectorized.

- qualityControl.R:8 allow the user to select the directory in which figures are stored; use `tempfile()` or `tempdir()` by default.

- qualityControl.R:41 parts of this loop also look like candidates for vectorization or other strategies for more efficient computation. For instance,

        for (i in seq_len(n)) {
            for (j in seq_len(nr[i])) {
                countsData2$PSI <- countsData2[, (1+j+sum(nr[0:(i-1)]))] /
                    (countsData2[, (1+j+sum(nr[0:(i-1)]))] + 
                        countsData2[, (1+sum(nr)+j+sum(nr[0:(i-1)]))])
                        
  recomuptes `1 + sum(nr[0:(i-1)])` at least three times on each iteration. The 0-based indexing looks wrong. A different structure might be
  
        nr_cumsum <- 1 + cumsum(rn)
        nr_tot <- sum(nr)
        for (i in seq_len(n)) {
            for (j in seq_len(nr[i])) {
                nr_j <- j + nr_cumsum[i - 1]
                PSI_j <- countsData2[, nr_j] / 
                    (countsData2[, nr_j] + countsData2[, nr_tot + nr_j])

  This part of the inner loop itself seems to simplify, too
  
        for (i in seq_len(n)) {
            nr_i <- seq_len(nr[i]) + nr_cumsum[i - 1]
            denominator <- (countsData2[, nr_i] + countsData2[, nr_tot + nr_i])
            PSI <- countsData2[, nr_i] / denominator
            ## maybe that's t(t(countsData2[, nr_i]) / t(denominator))...

- utils.R:559 etc use fast `rowMeans()` and `rowVars()` (and possibly functions from `matrixStats()` rather than `apply(,, mean)`, etc

**Comment by aursiber** [comment]
Dear @mtmorgan,
We have improved our package taking into account all your comments. 
Some suggestions have helped to improve widely the performance of the exported functions.
Thanks a lot.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aursiber.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"kissDE\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/kissDE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
