### ISSUE TITLE
TCGAutils

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#597]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/TCGAutils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 

There is an issue with `S4Vectors` where `mendoapply` wont accept mixed
`list` and `List` objects as input. Hopefully this will be resolved soon. 

Regards,
Marcel

**Comment by lawremi** [comment]
Had trouble understanding the vignette. Would be nice to see how these utilities can be used together to carry out a workflow. Right now it's much closer to just a list of functions with vague descriptions. The section about the importers to GRangesList was especially vague. For example, there is no explanation of the structure of the returned GRangesList objects. Are they they the regions of copy change by sample? I have no idea.

The names of the import functions seem too generic, e.g., `makeGRangesListFromTCGA()` handles a particular copy number format used by the TCGA. Do we really want to use such a general name for it?

We should think about generalizing some of these. For example, `addClinical()` sounds like a potential `mergeColData()`. Maybe `separateSamples()` should be `splitAssays()` since the text says it "partitions the assays". And rather than have the user coerce to a class name, like MatchedAssayExperiment, why not have a function that does the split and the coercion. Call it `matchAssays()` or something.

Haven't looked at the code yet.

**Comment by LiNk-NY** [comment]
Hi Michael, @lawremi 
Thanks for providing the useful feedback. 
I agree that the package needs a unifying workflow for all of the functionality it provides.

I will work on making those changes, such as using more specific names for convenience read-in
functions. I've already made some name changes that I will push shortly. 

I think it is useful to keep this intermediate step so that the user may see can see the result of the
operation and decide to subsequently match the assays with the 
`as(mae, "MatchedAssayExperiment")` coercion function. I will also consider using the `MatchedAssayExperiment` constructor to do the coercion from a `MultiAssayExperiment`. 

Best regards,
Marcel

**Comment by nturaga** [comment]
Review TCGAutils
===============


# R CMD build:

ok

# R CMD INSTALL

ok

# DESCRIPTION

* Ok.

# NAMESPACE

* ok

# vignette

* vigentte says "Waldron lab" but this is probably more accurate by
  just giving the names of the authors.

* Good vignette overall.

# man

* Good documentation for functions.

# R

* You can move data-raw scripts to inst/scripts.

* Using 1L vs 1 interchangebly in list indexing, it doesn't make a
  difference but you could use the same format everywhere.

* Why not explicitly import readr in the NAMESPACE? and use read_delim
  as necessary? Just make it a requirement instead of using read.delim
  and read_delim in the "if else" statement. This will make your
  resulting `btData`, always of the same type.   Use readr.
    
```
    readr_avail <- requireNamespace("readr", quietly = TRUE)
```

* Pretty clean code overall.


# NEWS

* Make sure the NEWS file can be parsed by utils::news() function.

# data-raw

* ok

# inst/extdata

* ok

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 

I would like to keep the scripts to generate the data in the package in `data-raw` as
recommended in http://r-pkgs.had.co.nz/data.html#data-extdata. This folder is added
to the `.Rbuildignore` so it won't be an issue for the package. 

I want to keep `readr` in the `Suggests` field and give user the option to use `readr`
when it is available in their system. I only use one function from the package and
I thought it would be better to provide it as a `Suggests`. 

The `NEWS` files have been updated. Thanks!

Regards,
Marcel

**Comment by lawremi** [comment]
Why not put the scripts for generating the data files in `data/` itself? The script could generate the object dynamically, or it could look to see if the serialized file exists and load that. You could use `Biobase::cache()` to do that. That's the standard R way of doing it.

**Comment by LiNk-NY** [comment]
Hi Michael, @lawremi 

Thanks for the suggestion. I have started to use `BiocFileCache` for managing URLs and datasets.
These are developer side scripts and would better go in `data-raw` directory. Since the URLs have
an expiration time of 5 minutes, it would not be worth it to run these scripts in the data directory when
considering the frequency of changes in these datasets. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Michael, @lawremi 

Thanks for your feedback. As far as I understand it, the automatic generation would require the
cached expression to be present in the `data` folder and that this expression gets evaluated during
the package build. 

This would then imply that all the packages used to generate the script be available in
the `Suggests` field. 

Is this correct? 

Best regards,
Marcel

**Comment by lawremi** [comment]
It's the data that are cached, not the expression. The expression only gets evaluated if the cached data are missing. It makes sense to have those packages in Suggests though, if only to document the potential dependency.

**Comment by LiNk-NY** [comment]
Hi Michael, @lawremi 

I tried to do this with the current data that I have such as `clinicalNames.rda` -> `clinicalNames.Rdata`
but I was getting errors during package build. The script that I use to generate the data
(found in `data-raw/clinicalNames.R` which was moved to the `data` directory) tries to
access a web resource and this is not favorable during the building of the package it seems...

It was one of the reasons why I opted to use `BiocFileCache` so that the URL could be managed
and any updates to the datasets could be made when a change in the URL was detected (although
this also does not work well with URLs that have short expiration times!).

I don't have a clean use case for `Biobase::cache` with this type of data but I will keep it in mind
for non-web datasets. Thank you!

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Nitesh, @nturaga 

I updated those locations where the extra conversion to numeric index was not necessary. 
I kept the rest where I am testing conditions on index length and for that I would like to have
a numeric index. 

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TCGAutils\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TCGAutils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
