### ISSUE TITLE
submitting pogos package

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#598]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/pogos

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vjcitn** [comment]
Is there a time frame for hearing whether this will get into devel?

**Comment by nturaga** [comment]
@vjcitn I can get you a review by end of Monday. Based on which it can go into devel.

**Comment by vjcitn** [comment]
OK, thanks ... just didn't want it to get forgotten.

**Comment by vjcitn** [comment]
hi -- i want to be sure this (pogos) is not confused with hmdbQuery which did recently get into devel.... thanks

**Comment by nturaga** [comment]
pogos review
============

## R CMD build

* build fails on vignette because of missing data

```
Quitting from lines 218-220 (pogos.Rmd)
Error: processing vignette 'pogos.Rmd' failed with diagnostics:
no data for requested cell lines
Execution halted
``` 

build fails here:

```
#plot(DRTraceSet(dataset="CCLE"))
```

DRTraceSet doesn't work because

```
Browse[2]> lkc("SK-ES-1",dataset)
Error in validObject(.Object) :
  invalid class "DRProfile" object: 1: invalid object for slot "drug" in class "DRProfile": got class "NULL", should be or extend class "character"
invalid class "DRProfile" object: 2: invalid object for slot "drug_code" in class "DRProfile": got class "NULL", should be or extend class "numeric"
``` 

This needs to be fixed or removed from the vignette.

Consider using the CRAN package "magick" https://cran.r-project.org/web/packages/magick/index.html, instead of system calls to ImageMagik.

## R CMD INSTALL 

* ok

## DESCRIPTION

* Looks good.

## NAMESPACE 

* looks good.

## man 

* ok

## vignette 

* Cool vignette. Very nice use of datatable.

## R

* Fix these NOTE's on the build report. Use `vapply` instead of `sapply` so that the FUN.VALUE can be defined by the call. The NOTE points out where these occur. Refer to http://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#coding-practices-checks. 

NOTE: Avoid sapply(); use vapply() found in files:
R/lkcomb.R (line 97, column 9)
R/rxdbHandling.R (line 42, column 9)
R/rxdbHandling.R (line 43, column 9)
R/rxdbHandling.R (line 49, column 9)
R/rxdbHandling.R (line 50, column 9)
R/shin.R (line 53, column 14)

```
ids = sapply(comps, "[[", "id")
nms = sapply(comps, "[[", "name") 
```

These can be written as

```
ids <- vapply(comps, `[[`, "id", character(1))
nms <- sapply(comps, `[[`, "name", character(1))
```

* Use `seq_len()` or `seq_along()` instead of `1:length()`, the NOTE points out where this occurs. Refer to http://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#coding-practices-checks.

```
kp = (1:length(cell_lines))
```

* NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
R/lkcomb.R (line 137, column 9)

* Please consider reformatting your code. Please use the package "formatR" to tidy up your code, also lines under 80 chars. (formatR::tidy_dir("pogos", recursive=TRUE))

* compoundsByCell function doesn't work like expected. It would be nice to include screen shots of a working version of the shiny app.

```
pogos::compoundsByCell()
 acquiring CHEBI
 done
 Loading required package: shiny

 Listening on http://127.0.0.1:6235
 Warning: Error in [: incorrect number of dimensions
 Stack trace (innermost first):
     83: renderDataTable
     82: func
     81: origRenderFunc
     80: output$nres
      5: <Anonymous>
      4: do.call
      3: print.shiny.appobj
      2: print
      1: pogos::compoundsByCell
```



## tests

* Tests fail. Please check.

## NEWS

* Either remove the emplty NEWS file or make sure that `utils::news` parses it.

**Comment by vjcitn** [comment]
Thanks for this review.  I think I have answered all the concerns -- except
the NEWS file which
I will now remove, and some issues of line length and indentation.  The
builder now succeeds.

**Comment by vjcitn** [comment]
Actually there was one comment in the review concerning Magick that I did
not understand.
I don't do anything with images that isn't standard figure processing for
Rmd.

**Comment by nturaga** [comment]
Hi Vince, the package looks good now. The package was not building because of an error with the software "ImageMagick". This might not be necessary. 

The rest of the changes look good.

There is one other issue, when I try to run the "interactive" shiny app, the man pages or vignette doesn't give any instruction on how to use that app or how to navigate it without an error. 

<img width="847" alt="screen shot 2018-01-19 at 9 36 24 am" src="https://user-images.githubusercontent.com/2746443/35155655-571836fe-fcfc-11e7-81a1-88d01ba4e46a.png">

**Comment by vjcitn** [comment]
Thanks for sticking with this Nitesh.  Very instructive for me to get
vapply right with a more complicated
return than is customary.  The compoundsByCell app includes a little more
annotation, and the man
page indicates that app will wait if cell line and dataset selections are
not compatible.

**Comment by nturaga** [comment]
Looks good @vjcitn. Thanks for fixing.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"pogos\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pogos

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
