### ISSUE TITLE
gsean

### ISSUE THREAD

**Issue by dongminjung** [Bioconductor/Contributions#599]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dongminjung/gsean

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vobencha** [comment]
Hi,
Just a few comments below.

1) function names
The dot '.' is used for S3 dispatch in R. To avoid confusion, please rename your functions to use camelCase or underscores.

2) man pages
All man pages need examples. Even if they only describe data, the object type should be mentioned, number of columns, rows, dimname etc. How was the data created, qc, downloded from where etc. GO.dme.Rd and KEGG.hsa.Rd are especially incomplete.

**Comment by dongminjung** [comment]
Hello, @vobencha
I have made changes according to your review.

**Comment by vobencha** [comment]
Thank you. Package is approved.

**Comment by dongminjung** [comment]
Thank you for taking the time to review the package.

**Comment by lgeistlinger** [comment]
Hi @dongminjung,

To which extent is your approach different from the one implemented here:

https://cran.r-project.org/web/packages/CePa/index.html

**Comment by dongminjung** [comment]
Hi @lgeistlinger 

Thank you for your interest in the package. This package is designed to easily available to use for network-based functional enrichment analysis. So, label propagation is used for ORA but centrality measures are not necessary. In GSEA, degree centrality or node strength is used as a centrality measure by default for simplicity. Both methods are based on the function fgsea::fgsea. Thus it is expected to run faster than before.

**Comment by dongminjung** [comment]
Hi @lgeistlinger

Thank you for your interest in the package. This package is designed to be easily available to use for network-based functional enrichment analysis. So, label propagation is used for ORA but centrality measures are not necessary. In GSEA, degree centrality or node strength is used as a centrality measure by default for simplicity. Both methods are based on the function fgsea::fgsea. Thus it is expected to run faster than before.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dongminjung.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"gsean\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gsean

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
