### ISSUE TITLE
MDTS

### ISSUE THREAD

**Issue by JMF47** [Bioconductor/Contributions#600]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JMF47/MDTS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Jack, @JMF47 
Thank you for submitting to Bioconductor.
I will be reviewing your package.
It appears that there are some errors in the package examples. Please see the report. 

```
* checking examples ... ERROR
Running examples in MDTS-Ex.R failed
```
Best regards,
Marcel

**Comment by JMF47** [comment]
Thank you very much @LiNk-NY! I have pushed the fixes that should make the errors go away. Looking forward to working together.

Best,
Jack

**Comment by LiNk-NY** [comment]
Hi Jack, @JMF47 

Apologies for the delay, I will review your package shortly. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
# MDTS #600

* Please use make sure that your files do not exceed 80 column widths.

## DESCRIPTION

* You can use the `Authors@R` field to provide author and maintainer in
a single field.
* Other than formatting, it looks good.

## NAMESPACE

* It looks like `pData` is an old idiom for `colData`. From the vignette,
it doesn't look like you want to use `pData` in the same way (as an accessor).
Please rename the function. 

## R

* Please use arguments that are not abbreviated. For example, use `readLength`
instead of `rl`. 
* Avoid growing a vector and the use of `1:n` sequences.
* Please see the Bioconductor coding practices at
http://bioconductor.org/developers/how-to/efficient-code/
* Avoid the use of `sapply`
* Avoid hard coded names in functions such as `pData$subj_id`. It may work
with the example data but not all dataset may have this variable. Provide
an argument with a default value for identifiers ("subj_id") and use double
bracket `[[id_var]]`.
* It is generally preferable to import selective functions rather than the
entire package due to potential name collisions, please use `@importFrom`
where possible, especially when the number of imported functions is low.
* Please rename `pData` as the general contract for pData does not accept
a file path input.
* Please use `<-` assignment rather than `=`.
* Avoid conditions where just a variable can be the difference (eg., `map` and
`GC`).

Minor:
* Avoid switching from numerical to logical index, e.g., `which(rle_track>0)`
* All `if` conditions evaluate to logical. No need to test equality with a
logical, for example `if (hasChr == FALSE)` is really `if (!hasChr)`

## vignettes

* Please avoid using an external dataset such as the one in `JMF47/MDTSdata`.
* If you plan on including this package with your submission please,
add it accordingly. 
* Otherwise, include a small example dataset for use in the vignette.
* Again, please format the vignette to not exceed 80 column widths.
* Please use `<-` assignment rather than `=`.
* Include the `sessionInfo`.

**Comment by JMF47** [comment]
Thank you! I will work towards implementing these changes.

**Comment by LiNk-NY** [comment]
Hi Jack, @JMF47 

Any updates on moving forward with these suggestions? 

Best regards,
Marcel

**Comment by JMF47** [comment]
Hi @LiNk-NY, thanks for checking in! I had implemented most of the changes, but something else came up that required my attention. I should have an updated version pushed here very soon. Thank you!

**Comment by JMF47** [comment]
Hi @LiNk-NY sorry about all the bumps - I kept finding places where the documentation needed to be updated. Just a quick question, is there something going on with the build system? The newer pushes are starting a build, but never get confirmed. Thanks!

**Comment by LiNk-NY** [comment]
Hi Jack, @JMF47 
Thanks for making those changes. 
I would have to check with Lori @lshep about the status of the SPB. 
Regards,
Marcel

**Comment by JMF47** [comment]
Hi @LiNk-NY thanks for checking up with the builder. Looks like everything is now good to go!

**Comment by LiNk-NY** [comment]
Hi Jack, @JMF47 

Thanks for making those changes. 
Can you respond to the changes suggested by the review? 

Best regards,
Marcel

**Comment by JMF47** [comment]
Hi @LiNk-NY, thanks for all your help!

**DESCRIPTION**
> -You can use the Authors@R field to provide author and maintainer in
a single field.

Fixed!

**NAMESPACE**

> - It looks like pData is an old idiom for colData. From the vignette, it doesn't look like you want to use pData in the same way (as an accessor). Please rename the function.

Renamed to `getMetaData`

**R**

> - Please use arguments that are not abbreviated. For example, use readLength instead of rl.

Updated `rl, med, min` to `readLength, medianCoverage, minimumCoverage` etc

> - Avoid growing a vector and the use of 1:n sequences. Please see the Bioconductor coding practices at http://bioconductor.org/developers/how-to/efficient-code/

Removed all `1:n` formulations

> - Avoid the use of sapply

Removed all `sapply`

> - Avoid hard coded names in functions such as pData$subj_id. It may work with the example data but not all dataset may have this variable. Provide an argument with a default value for identifiers ("subj_id") and use double bracket [[id_var]].

Reworked `getMetaData` to reflect this.

> - It is generally preferable to import selective functions rather than the entire package due to potential name collisions, please use @importFrom where possible, especially when the number of imported functions is low. 

Used `@importFrom` for functions from other packages. No longer loading entire namespace.

> - Please rename pData as the general contract for pData does not accept a file path input.

Renamed to `getMetaData`

> - Please use <- assignment rather than =.

Fixed!

> - Avoid conditions where just a variable can be the difference (eg., map and GC).

Removed helper function and directly added mappability and GC adjustment in `normalizeCounts`

> - Avoid switching from numerical to logical index, e.g., which(rle_track>0)

Fixed!

> - All if conditions evaluate to logical. No need to test equality with a logical, for example if (hasChr == FALSE) is really if (!hasChr)

Fixed

**vignettes**

> - Please avoid using an external dataset such as the one in JMF47/MDTSdata. If you plan on including this package with your submission please, add it accordingly. Otherwise, include a small example dataset for use in the vignette.

The dataset referenced is not required for running the vignette. I have included all processed data as accessible objects during the install of `MDTS`. I thought about providing the location of the raw data in case people wanted access to it.


> - Again, please format the vignette to not exceed 80 column widths.

Fixed!

> - Please use <- assignment rather than =.

Fixed!

>- Include the sessionInfo.

Fixed!

**Comment by JMF47** [comment]
May thanks @LiNk-NY !

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/JMF47.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MDTS\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MDTS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
