### ISSUE TITLE
FELLA

### ISSUE THREAD

**Issue by SergiPicart** [Bioconductor/Contributions#612]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/b2slab/FELLA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by SergiPicart** [comment]
Dear Nitesh, is anything else I need to do before the review? 
Thank you!

**Comment by llrs** [comment]
Hi Sergi,

FELLA seems to work only with KEGG database. KEGG requires a license (and a payment) in order to have full access. Is there a way to use FELLA with reactome, or STRING or other pathway databases? Does the package accept other input outside KEGG pathways and metabolites? 

Many thanks

**Comment by SergiPicart** [comment]
Hi Lluís, 
Everything needed for using FELLA is internally retrieved through the KEGGREST package, also available in Bioconductor. FELLA relies on a knowledge model that has been developped on the top of KEGG. Generalising this approach for Reactome/STRING requires a considerable effort and while it is part of our further work, it will take time. 
On your second question, FELLA only accepts KEGG compound identifiers at the moment. The manual refers the user to resources for mapping the identifiers between databases - although it probably is a good idea to manually double check this step. 

Please feel free to open tickets in our FELLA repo for such features - we want to know the users' needs.
Thank you!

**Comment by SergiPicart** [comment]
Hi @nturaga
The review for FELLA is still awaiting, is there anything I have forgotten to do?
Thank you!

**Comment by nturaga** [comment]
@SergiPicart I will post your review tomorrow. No, you have not forgotten anything.

**Comment by nturaga** [comment]
FELLA review
============

# R CMD build

* ok

# R CMD INSTALL 

* ok

# DESCRIPTION

* Don't need Authors@R and Authors, just use one e.g: Authors@R.

# NAMESPACE

* ok

# man

* ok 

# vignette

* Looks good and detailed.

# R


* AllMethods.R, 247 You don't need `stop(paste0(`, the stop function
  concatenates by default. Same with `warning` as well, which is done
  in other functions. Please check.

* You dont need to remove, objects like this, once the function is
  executed R automatically removes the objects.

```
rm(R, K, diffusion.matrix)
```

You do this in many places through out your code, it is not needed.

* Use `!is(data,"FELLA.DATA")` instead of if `(class(data) !=
  "FELLA.DATA")` in enrich.R:l 148


## Tests

* Good test cases and use of testthat


## data-raw

* please consider using inst/script instead of data-raw to store your
  scripts.

* In data-raw, please fix these 1:n calls just like in the other
  places, use seq_len or seq_along which ever is more appropriate.

```
data-raw/buildGraphFromKEGG.R
286:    for (i in 1:length(list.module)) {
470:    for (i in 1:length(list.enzyme)) {
579:    for (i in 1:length(list.reaction)) {
698:    for (i in 1:length(list.compound)) {
749:    for (i in 1:total) {
759:            for (k in 1:lcat) {
773:            for (k in 1:lcat) {
783:    return(EDGE[1:count, ])
960:  for (v in 1:vcount(graph.curated)) {
1000:    for (i in 1:length(gene.all)) {
```

# NEWS 

* Remove the NEWS.md file, keep only the NEWS file without the .md
  extension. If you are using a NEWS file, make sure it can be parsed
  by utils::news()

# General comments

* Good and well written package overall.

**Comment by SergiPicart** [comment]
Hi @nturaga , thank you for the throrough review!
The last version (0.99.5) addresses everything but the following:

> You dont need to remove, objects like this, once the function is
> executed R automatically removes the objects.

The `rm` calls were included because these variables can weight hundreds of megabytes. It can happen that a big matrix (`diffusion`) sticks around while another big matrix (`pagerank`) is being built. I am aware that these variables are removed after the function ends, but within its execution they might pile up. If this is irrelevant, I will remove them. 

There is another issue with the build, which is erroring now. The tests need a working network connection and I suspect the ERROR comes from a connection error. I cannot reproduce it (nor in TravisCI, neither locally), and the error appears in a different server everytime. Can you confirm this is the case? If so, what should I do?

Thank you for everything,

**Comment by SergiPicart** [comment]
Hi @nturaga , what should I do at this point?

**Comment by nturaga** [comment]
Hi @SergiPicart , 

Please remove the `rm` calls.  Please bump the version. I will investigate once there is a new build report and the ERROR persists.

**Comment by SergiPicart** [comment]
The `rm` calls have been removed and last build seems ok

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SergiPicart.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"FELLA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FELLA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
