### ISSUE TITLE
PowerExplorer

### ISSUE THREAD

**Issue by xuqiao93** [Bioconductor/Contributions#615]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xuqiao93/PowerExplorer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Xu Quiao, @xuqiao93

Thank you for submitting to Bioconductor.
Please see the review below. 

Best, 
Marcel

---

# PowerExplorer #615

* Your package does not appear to make use of existing Bioconductor
functionalities.
* Please support `SummarizedExperiment` input and classes related
to proteomics.

## DESCRIPTION

* Consolidate both `Author` and `Maintainer` fields by using the
`Authors@R` field.
* Use release `roxygen2`

## NAMESPACE

* Can these long function names be avoided?

## R

* Avoid creating empty vectors and subsequently copying and filling them.
Use the allocate and fill method. See Bioconductor coding practice guidelines.
* Avoid nesting `for` loops.
* Avoid providing arguments for saving datasets within a function
(`saveRData`, `saveSimulatedData`). At the very least, leave these options
turned off by default.
* It will suffice to provide the data within the resulting object.
* Use helper functions to avoid repeating code.
* It seems like the package is lacking a formal S4 class with a show method.
* Consider using `switch` for when you want to assign a variable using multiple
conditions, i.e.,
`dataTypeSelect <- switch(dataType, RNAseq = TRUE, Proteomics = FALSE)`
* Do not include any `savePlot` functionality. The user may save plots via the
device output by running `pdf`, `png`, etc.
* Consider separating plot functionalities by having a function for each
`plotType`.
* Avoid using `with` in package code. Break complicated code into smaller
and compute on those smaller pieces.
* Include a `seed` argument for functions that use random number generators
(`simCounts`).
* Avoid using `rm` inside a function, no need for it.
* Code can be shortened by conditionally assigning character variables and
function names in `R/simulateData.R`.

Minor:
* Please use the more robust `[[` method for list access rather than `$`. 
* Avoid double evaluation in `if`. Example, use `if (saveRData)` instead of
`if (saveRData == TRUE)`.

## vignettes

* Remove intermediate files in the `vignettes` folder.
* Please keep text within an 80 column width.
* No need to include images in the vignette, they should be generated
by the run.

## data

* Consider shortening the names of the datasets

**Comment by xuqiao93** [comment]
Thanks, Marcel @LiNk-NY  
I have made some changes regarding your suggestion.

Kind regards,
Xu

**Comment by LiNk-NY** [comment]
Hi Xu Qiao, @xuqiao93 

Can you respond to the individual items in the review? 
You can briefly state what you did to address them.
Thanks!

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Xu Qiao, @xuqiao93 
Just a reminder to post your response to the review here. 
Regards,
Marcel

**Comment by xuqiao93** [comment]
Hi Marcel, @LiNk-NY 

I apologize for the late response. Currently, I am adding some new features to the tool regarding the performance, so I was going to give you all the summaries at once. I will get back to you shortly. Thanks for your reminder.

Kind regards,
Xu

**Comment by xuqiao93** [comment]
Hi, @bioc-issue-bot @LiNk-NY 

I tried multiple times to update my package today, but it seemed to be having issues with the Mac platform at first. But now it has been tagged as ABNORMAL while the build report says everything is OK.

Could you please give me a further diagnosis regarding this results?

Many thanks,
Xu

**Comment by xuqiao93** [comment]
Hi, Marcel @LiNk-NY 

Here are the summaries regarding the modifications to the package:

> DESCRIPTION
•	Consolidate both Author and Maintainer fields by using the
Authors@R field.
•	Use release roxygen2

Fixed the mentioned fields

> NAMESPACE
•	Can these long function names be avoided?

Shortened the long function names as much as possible

> R
•	Avoid creating empty vectors and subsequently copying and filling them.
Use the allocate and fill method. See Bioconductor coding practice guidelines.
•	Avoid nesting for loops.

The above two issues are solved by replacing nested for loop with apply functions

> •	Avoid providing arguments for saving datasets within a function
(saveRData, saveSimulatedData). At the very least, leave these options
turned off by default.

These options have been set to FALSE as default

> •	It will suffice to provide the data within the resulting object.

The simulated data often have large size, therefore I leave it as optional

> •	Use helper functions to avoid repeating code.

The shared code chunks have been isolated as single functions

> •	It seems like the package is lacking a formal S4 class with a show method.

Implemented 'SummarizedExperiment' and added a subclass of SE named as PEObject to contain input data and results.

> •	Consider using switch for when you want to assign a variable using multiple
conditions, i.e.,
dataTypeSelect <- switch(dataType, RNAseq = TRUE, Proteomics = FALSE)

Modified these parts accordingly

> •	Do not include any savePlot functionality. The user may save plots via the
device output by running pdf, png, etc.

plot saving options are removed

> •	Consider separating plot functionalities by having a function for each
plotType.

plot functions are separated, heatmap is removed since the lineplots are already informative enough.

> •	Avoid using with in package code. Break complicated code into smaller
and compute on those smaller pieces.

with() has been replaced

> •	Include a seed argument for functions that use random number generators
(simCounts).

The method of this tool is based on simulation, each simulation is required to have different generated data, if the seed is fixed, all the simulation would end up with the same data.
However, setting the seed before calling simulateData would give the used generators the same start point, which will keep the reproducibility of the whole generated data matrix.

**Fundamental idea:**
_simulate data from a distribution for 100 times using_
`set.seed(10); vapply(1:100, rnorm(10, 5, 1), numeric(10))`
_instead of_
`vapply(1:100, function(x) {set.seed(10); rnorm(10, 5, 1)}, numeric(10))`

> •	Avoid using rm inside a function, no need for it.

removed rm()

> •	Code can be shortened by conditionally assigning character variables and
function names in R/simulateData.R.

removed redundant strings

-----------------------
Additional changes:
package ROTS is added to the package as an optional statistical model.
some calculation-wise adjustments.

Kind regards,
Xu

**Comment by LiNk-NY** [comment]
Hi Xu Qiao, @xuqiao93 

Thank you for making those changes. It's looking better!
Good call on not adding the seed to the functions. 

* It still looks like you could separate the API from the implementation a bit more
by avoiding the use of `@` for extraction for the `PEObject` class.
You can create extractor functions for that.
* The class name is a bit vague and you may want to consider using a more descriptive name. 


Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Xu Qiao, @xuqiao93 
Please bump the version of your package for another build in the SPB. 
Best regards,
Marcel

**Comment by xuqiao93** [comment]
Hi Marcel, @LiNk-NY 
I have changed the class name and added the needed extractor functions. In addition, I have also implemented BiocParallel in the package to enable parallelization among simulations.

Kind regards,
Xu

**Comment by LiNk-NY** [comment]
Hi Xu, @xuqiao93 
Thanks for making those changes. I will accept your package. 
Thank you for your submission!

Best regards,
Marcel

**Comment by xuqiao93** [comment]
Hi Marcel, @LiNk-NY 
Also thanks for your consideration.

Best regards,
Xu

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xuqiao93.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"PowerExplorer\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PowerExplorer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
