### ISSUE TITLE
hgu133plus2CellScore

### ISSUE THREAD

**Issue by nmah** [Bioconductor/Contributions#616]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nmah/hgu133plus2CellScore

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nmah** [comment]
AdditionalPackage: https://github.com/nmah/CellScore

**Comment by Liubuntu** [comment]
Seems that the only error comes from here, please fix it to build successfully for an official technical review.

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

These are for further issues you may considering fixing right now, these will be in the technical review: 

- Consider adding some unit tests, http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
- Consider adding a NEWS file in the top directory, for new features and functions in each version of your package, and your package news will be included in Bioconductor release announcements.

Cheers!

**Comment by nmah** [comment]
Hello,

I subcribed to the bioc-devel list now using same email address in github account and in the package, I hope it will fix the error now.

Cheers
n
________________________________

**Comment by Liubuntu** [comment]
Hi @nmah , 

Sorry for the delay in reviewing your package. I just went through the whole package and found it very well organized with appropriate documentation and explanatory vignette. 

There is just one minor issue you need to address. Please comment back when it's fixed! 
 
## DESCRIPTION

- If you have the `Author` and `maintainer` field, then you don't need the `Authors@R` field. They are repeated. If you decide to use the former, just keep them like this by removing the quote marks and notes:

```
Author: Nancy Mah, Katerina Taskova
Maintainer: Nancy Mah <nancy.l.mah@googlemail.com>
```
Cheers!
Qian

**Comment by lgeistlinger** [comment]
It would be great if new packages could be encouraged to use `SummarizedExperiment` instead of `ExpressionSet`

http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by Liubuntu** [comment]
Thanks @lgeistlinger for your input. I do agree that we should encourage people to use `SummarizedExperiment` for rectangular data. But as the DESCRIPTION of this data package says: `This standard dataset only contains data from the Affymetrix GeneChip Human Genome U133 Plus 2.0
 microarrays.` And the `ExpressionSet` is such an established data structure for MicroArray data, so it should be appropriate that they use the `ExpressionSet`. @mtmorgan also agreed.

**Comment by nmah** [comment]
Hello @Liubuntu, 
Thanks for your comments. I have deleted the redundancy in the author files in both hgu133plusCellScore and CellScore.
Cheers
Nancy

**Comment by nmah** [comment]
Hello, 
Does the review of the Additional package (https://github.com/nmah/CellScore) automatically start, or am I required to do something else?
Thanks
Nancy

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nmah.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"hgu133plus2CellScore\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hgu133plus2CellScore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nmah.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CellScore\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CellScore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
