### ISSUE TITLE
SEPIRA

### ISSUE THREAD

**Issue by YC3** [Bioconductor/Contributions#619]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YC3/SEPIRA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before the package can be added to the review queue, the vignette needs to have code chunks that are evaluated (`eval = TRUE`); it cannot contain significant numbers of chunks with eval = FALSE. Please update your vignette, and confirm that the revisions are consistent with Biocoductor package guidelines on [time and space requirements][1]. When ready, add a comment to this issue using the tag @mtmorgan.

[1]: http://bioconductor.org/developers/package-guidelines/#correctness

**Comment by YC3** [comment]
@mtmorgan I have updated the vignette according to your last message. Please take a look. Thank you！

**Comment by YC3** [comment]
Hi,
I found the error was that I have not subscribed to the mailing lists. I have subscribed two both mailing lists.
Could you check again please?

Thanks!
Y

**Comment by dvantwisk** [comment]
Please do another version bump in order for your package to be rebuilt on our build system.

**Comment by dvantwisk** [comment]
I apologize for being late with the review.  Please address the following issues and comment back when you are done.  I wasn't able to run all the suggested code changes so some might not be entirely accurate.  Don't hesitate to reply back if you have any comments or questions.

GENERAL:
- [CONSIDER] use `BiocParallel` instead of `parallel`.
- [REQUIRED] in `Roxygen2` headers, be specific about the type of object
required for input to a function or returned from a function.  For example, in
`LimmaFN()`, the return is given as "A table" when it seems that a `list` object
is actually returned.  This would help the users better understand the
functions.
- [REQUIRED] Multiple locations: Use `seq_len()` or `seq_along()` instead of
`1:` to slightly improve performance.
- [CONSIDER] At various places, base functions such as `c` and `t` are used as
variable names.  This makes things somewhat difficult to read and is not
advisable.

R/LimmaFn.R
- [REQUIRED] L50-59: Inefficient copy and append patterns and unnecessary
for-loops, replace with (this should work but I was not able to test it):
```
i1 <- rep(seq_len(ntypes-1), times=rev(seq_len(ntypes-1)))
i2 <- unlist(lapply(1:10, function(x){tail(seq.int(x, 10),-1)})
c <- seq_len(ncol(design.sample))

cont.m[i1, c] <- -1
cont.m[i2, c] <- 1

tmp.v[c] <- paste(sampletypes.v[i2], "--", sampletypes.v[i1], sep = "")
```
- [REQUIRED] L71-73: Better to use lapply than copy and append pattern.
```
top.lm <- lapply(seq_len(ncol(cont.m)), function(c){
    topTable(bay.o, coef = c, adjust.method = "fdr", number = nrow(data))
})
```

R/sepiraInfNet.R
- [REQUIRED] L148-149: Avoid inefficient for-loop:
```
gtexNET.m2 <- gtexNET.m
gtexNET.m3 <- gtexNET.m

gtexNet.m2[gteNET.m2 != 1] == 0
gtexNet.m2[gteNET.m2 == 1] == 1

gtexNet.m3[gteNET.m3 != -1] == 0
gtexNet.m3[gteNET.m3 == -1] == 1

sumnetTF.m[2,] <- rowSums(gtexNET.m2)
sumnetTF.m[3,] <- rowSums(gtexNET.m3)
```
- [REQUIRED] L177-182: Better to use lapply than append to list.
```
toiTF.lv <- lapply(seq_along(topTOI.lm), function(i) {
    statTF.m <- topTOI.lm[[i]][match(colnames(gtexNETf.m), rownames(topTOI.lm[[i]])), c(1, 3, 4, 5)]
    toiTF.idx <- intersect(which(statTF.m[, 4] < degth[i]), which(statTF.m[, 1] > lfcth[i]))
    toiTF.lv[[i]] <- rownames(statTF.m[toiTF.idx, ])
}
```
- [REQUIRED] L201-205: avoid inefficent for loop.
```
act.idx <- matrix(nrow = ncol(netTOI.m), ncol = 3)
act.idx[netTOI.m != 1] <- 0

inact.idx <- matrix(nrow = ncol(netTOI.m), ncol = 3)
inact.idx[netTOI.m != -1] <- 0
inact.idx[netTOI.m == -1] <- 1

distNet.m[, 2:3] <- rbind(colSums(act.idx), colSums(inact.idx))
```

test/testthat.R
- [CONSIDER] This appears to be a placeholder.  Consider adding tests that are
applicable to the functionality of the packages, or simply delete the `tests`
directory if you do not plan to add any.

**Comment by dvantwisk** [comment]
Hello,

Have you been working on the changes that we requested?  We plan to have a new Bioconductor release in early May, so If you want your package to be included in that release, it will need to be accepted by mid-April.  Please message me back and feel free to ask for any help if it is needed.

**Comment by YC3** [comment]
Hi @dvantwisk,

Sorry I missed your last message. 
Thank you for your comments. I will address all these issues soon.

Best,

**Comment by YC3** [comment]
Hi @dvantwisk, 

I have addressed all the issues in your comments and it seems the updated version has passed the build test. Would you mind telling me what else should I do next?

Thanks,
Yuting

**Comment by dvantwisk** [comment]
it doesn't seem that you've addressed my issues with `R/LimmaFn.R` and `R/sepiraInfNet.R`.  Getting rid of some of these for-loops in particular can really help with the performance of your package.

**Comment by YC3** [comment]
Let me see...

**Comment by YC3** [comment]
Hi @dvantwisk, this time I changed all the for loops would you mind take another look?

**Comment by dvantwisk** [comment]
Everything looks fine now.  I'm going to move to accept the package.

**Comment by YC3** [comment]
Thank you for your help @dvantwisk.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YC3.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"SEPIRA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SEPIRA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
