### ISSUE TITLE
RNAdecay

### ISSUE THREAD

**Issue by reedssorenson** [Bioconductor/Contributions#620]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reedssorenson/RNAdecay

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by reedssorenson** [comment]
Hi @hpages, 
I have submit my package RNAdecay and resolved all Warnings and Errors from the checker. Thank you for serving as a reviewer. Do you have any additional comments for me? 
Thanks, Reed

**Comment by hpages** [comment]
Hi @reedssorenson ,

Thanks for submitting RNAdecay. Any reason why you put your C++ code in `RNAdecay/inst/src/` and request that the user explicitly compiles and loads it via calls to `TMB::compile(...)` and `dyn.load(TMB::dynlib(...))` instead of using the standard approach of having it in `RNAdecay/src/` ? This is a very non-standard approach to embedding native code in an R package and will very very likely cause all kinds of usability issues.

Best,
H.

**Comment by reedssorenson** [comment]
Hi H., 

The main reason is that I do not know C++ and could not get the compiling to work with a makevars file from RNAdecay/src on install. 

The TMB package makes C++ efficiency accessible for mathematical computations in R with only the objective function of the modeling coded in C++. We have 8 individual objective functions, that all need to be compiled separately. Using TMB::compile function, it worked fine so I used it. I don't really understand how R interacts with the compiled files, but it does so through another TMB function. In essence, I stuck with their workflow for using C++ because I wasn't sure if it would work the other way.

I could give another try, if you recommend. For this, I would really appreciate any insight or suggestions. If you're interested, here is the makevars file I tried using for non-Windows machines:

```
all: general_dExp_1sse.so general_Exp_1sse.so general_dExp_2sse.so general_Exp_2sse.so general_dExp_3sse.so general_Exp_3sse.so general_dExp_4sse.so general_Exp_4sse.so

general_dExp_1sse.so: general_dExp_1sse.cpp
	Rscript --vanilla -e "TMB::compile('general_dExp_1sse.cpp')"

general_Exp_1sse.so: general_Exp_1sse.cpp
	Rscript --vanilla -e "TMB::compile('general_Exp_1sse.cpp')"

general_dExp_2sse.so: general_dExp_2sse.cpp
	Rscript --vanilla -e "TMB::compile('general_dExp_2sse.cpp')"

general_Exp_2sse.so: general_Exp_2sse.cpp
	Rscript --vanilla -e "TMB::compile('general_Exp_2sse.cpp')"

general_dExp_3sse.so: general_dExp_3sse.cpp
	Rscript --vanilla -e "TMB::compile('general_dExp_3sse.cpp')"

general_Exp_3sse.so: general_Exp_3sse.cpp
	Rscript --vanilla -e "TMB::compile('general_Exp_3sse.cpp')"

general_dExp_4sse.so: general_dExp_4sse.cpp
	Rscript --vanilla -e "TMB::compile('general_dExp_4sse.cpp')"

general_Exp_4sse.so: general_Exp_4sse.cpp
	Rscript --vanilla -e "TMB::compile('general_Exp_4sse.cpp')"

clean:
	rm -rf *o
```
Reed

**Comment by hpages** [comment]
Hi Reed,

Why do you need a Makevars file? If you don't have "special needs" (e.g. need to compile with non-standard options or need to link to a system library etc...) you just drop your C/C++ code in the `RNAdecay/src/` folder and that's basically it. `R CMD build` will then generate a source tarball that can be installed with `R CMD INSTALL`. `R CMD INSTALL` will take care of compiling/linking the C/C++ code found in `RNAdecay/src/`. Note that this will only work for users who have development tools on their machine (e.g. compiler, linker, etc...). However our build system will take care of generating binary packages that people with no such tools will be able to install. All this works if the code to compile is in the right place (`RNAdecay/src/`).

Also I don't see the need for using templates or C++. Looking at your cpp files, they contain very simple functions that don't need any of the C++ features so could just be implemented in C. The C or C++ code needs to be called via the `.Call` interface (see the "Writing R Extensions" manual for how to do this, then look at some Bioconductor packages with C code for real examples), or you could use Rcpp to interface your C++ code with your R code. I don't have any particular experience with Rcpp but everybody seems to agree that it makes interfacing C++ code with R code **very** easy. See the Rcpp documentation for the details. Don't hesitate to go and ask questions on general R forums. C/C++ code integration in an R package is not a Bioconductor-specific topic.

Hope this helps,
H.

**Comment by reedssorenson** [comment]
Hi @hpages, 

Ok, to address your comments: I do have some "special" needs. I am using the TMB package (https://github.com/kaskr/adcomp/wiki)  which only uses objective functions written in C++.  This is also why I use the compile function from their package. The automatic compiling by Rcpp from RNAdecay/src did not work for some reason; however, I was able to use a "makefile"/"makefile.win" that will compile the files during the build. 

The "Warnings" flag remains because the compiled files are larger than 5 Mb, but this cannot be helped. 

Can you give me additional comments? 

Thanks,
Reed

**Comment by reedssorenson** [comment]
Hi @hpages,

I image this is a very busy time for you. Will you be able to review RNAdecay this week so that I might make the release deadline? The warning that remains is unavoidable as my compiled files are larger than 5 MB. Thank you for your work on this.

Reed

**Comment by hpages** [comment]
Hi Reed,

Yes, very busy time indeed. We're getting close to the next BioC release and we've been receiving many submissions lately. I took a look at RNAdecay and was pleased to find out that compilation now happens at installation time. This is a great improvement, thanks!

I also found the following issues:

1. Your Makefiles assume that the Rscript command is in the PATH. However this is not always going to be the case in which case compilation will fail. Another common situation is that an Rscript command is in the PATH but corresponds to an R installation that is not the same as the R that was invoked to install the package. This would also lead to all kinds of problems. All these problems can be avoided by calling with `${R_HOME}/bin/Rscript` in the Makefiles.

2. The functions defined in the package use different naming styles:
    
    - camelCaps e.g. modOptimization, myTheme, groupMap, dExp
    - CamelCaps e.g. DecayPlot
    - lower case with underscore separator e.g. constraint_fun_list_maker
    - lower case with dot separator e.g. a.high, b.low
    
    Some names even mix more than 1 style e.g. C_eps.fun, sse.nulldExp.fun  Please pick up one style and stick to it.

3. Many of the exported functions are actually internal helpers. Note that it's generally recommended to not export internal helpers as they pollute the `search()` path and will complicate the long term maintenance of the package (it will be harder to make internal changes to the package in the future if people have started to use these internal helpers in their code).

4. Out of the 24 functions exposed to the user, 9 have the string "fun" in their name: `C_eps.fun`, `constraint_fun_list_maker`, `fun_aic`, `fun_aicc`, `fun_nPar`, `LL.fun`, `sig.fun`, `sse.nulldExp.fun`, `sse.nullExp.fun`. Except for `constraint_fun_list_maker` (which indeed returns a list of functions), such naming is not considered good practice.

5. The choice of splitting the vignette in 3 non-independent vignettes is questionable. What are the benefits? How is it better than having a single document with 3 parts? The user doing `browseVignettes("RNAdecay")` will see an unnumbered list of 3 vignettes so will be confused and won't know where to start.

6. Wrapping sanity checks inside `try()` statements like here has not benefits and only contributes to code obfuscation:
    ```
    try(if (nTreat > 4)
        stop("modOptimization can only handle up to 4 treatments."))
    ```

7. The following sanity check at the beginning of the `modOptimization()` function has several problems:
    ```
    try(if (sum(grepl(paste0("_", nTreat, "sse"), names(getLoadedDLLs()))) != 2)
      stop(
      "high performance objective functions need to be loaded as compilied
      dynamically linked libraries (.dll or .so) before modeling. You can
      check which are loaded using 'getLoadedDLLs()'",
      call. = FALSE
    ))
    ```
    1) It's not robust (it will wrongly fail if `grepl()` also returns matches to DLL names from other packages).
    2) It displays an obscure error message (most end-users would have no idea what's going on).
    3) But most importantly it's not needed (DLLs get automatically loaded when the package is loaded).

8. Please use `<-` instead of `=` for assignment. Place a space before and after the left arrow.

Please address at your earliest convenience.

Best,
H.

**Comment by lshep** [comment]
I'm looking into why the file size isn't displaying on the build report but malbec and merida build products are under 4MB (~2.7) so the windows WARNING about size can be ignored.

**Comment by reedssorenson** [comment]
Hi @ hpages and @lshep, 

I have made the recommended changes. I believe that the oversize warning is to to the fact that the compiled files are larger on Windows. I do not know why they are larger. 

Do you have further comments or recommendations for me? 

Thank you for helping me make _RNAdecay_ better, 
Reed

**Comment by vobencha** [comment]
Hi @reedssorenson ,

It looks like you've addressed all issues raised in https://github.com/Bioconductor/Contributions/issues/620#issuecomment-381087582. Since we're under a tight deadline and Herve is out of town this week, I'm going to approve this package for him.

Valerie

**Comment by vobencha** [comment]
@reedssorenson One last minor detail. In the README you suggest the devel version of the package be installed with
```
install.packages("devtools")
devtools::install_github("reedssorenson/RNAdecay@R-v4.2")
library(RNAdecay)
```
This should be changed to biocLite(). The function will install the release or devel version of the package depending on what version of R it's called from. You can make this change now or after the package is in the Bioconductor git repository.

Thanks.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/reedssorenson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"RNAdecay\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RNAdecay

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by nturaga** [comment]
Please use the following link to [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/). The link listed in the previous message is deprecated.
