### ISSUE TITLE
iteremoval

### ISSUE THREAD

**Issue by cihga39871** [Bioconductor/Contributions#622]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cihga39871/iteremoval

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before adding this package to the review queue, please update it to interoperate with well-established Biocoductor packages, especially SummarizedExperiment. Post a comment here including @mtmorgan when this change has been made.

**Comment by cihga39871** [comment]
Hi, @mtmorgan 
This package is just a method that is aimed to filter features from the *statistic results* of data, mainly probabilities. Thus, although the method is tailored for the statistical result of NGS data, this package has nothing to do with Bioconductor packages related to the genome coordinates, or raw experimental data, etc.
So, I hope you could understand why I did not add interoperation with some Bioconductor packages like SummarizedExperiment.

**Comment by mtmorgan** [comment]
Hi @cihga39871 it's obvious that your package uses data suitable for representation using Bioconductor data structures. For instance the first help page I looked at was SWR0.Rd, where the columns describe genomic coordinates and hence should be represented as GenomicRanges::GRanges. The first line of the vignette uses ad-hoc subsetting to separate genomic coordinates from annotations on them. The arguments to `feature.removal()` are described as 'row of feature, column of observation', describing the `assay()` component of SummarizedExperiment; storing multiple assays in a single SummarizedExperiment provides a robust way to ensure that the data sets have identical dimensions ad appropriate type.

A major benefit to Biocoductor users is interoperability between packages. Interoperability is enabled by use of standard data representations. Please update your package accordingly.

**Comment by cihga39871** [comment]
Hi @mtmorgan 
Thank you a lot for the useful suggestion! I added the interoperation with GRanges and SummarizedExperiment to my package. Now you can add this package to the review queue. Thanks!

**Comment by mtmorgan** [comment]
@cihga39871 can you explain what you have done? For instance the original data objects are still present and the function still accepts data.frames rather than SummarizedExperiment.

**Comment by cihga39871** [comment]
Hi @mtmorgan
`feature.removal` now accepts two kinds of data.
1. The original `g1` and `g0` datasets are kept, since not all people, especially those who might use this package for non-biological purposes, have an easy way to call the function.
2. Now it also accepts a `SummarizedExperiment` object, and the second parameter is to define which samples are control samples.

For example, you can call the function in the following way:
```r
result.simple.A <- feature.removal(g1, g0, cutoff1=0.95, cutoff0=0.95)
result.simple.B <- feature.removal(SummarizedData, SummarizedData$Group==0,
    cutoff1=0.95, cutoff0=0.95)
```

**Comment by cihga39871** [comment]
Bug fixed now. Please run the build again.

**Comment by lshep** [comment]
In order for the build to be run again you have to [set up a webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)  and then increase the version number.

**Comment by cihga39871** [comment]
Thank you, Ishep!

**Comment by cihga39871** [comment]
Hi @lshep 
I am sorry to bother you. But I have a small but strange problem.
The build on Linux and OSX is failed for
```
Warning: file SWRG0.rda has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
```

I just used `save(obj, file="obj.rda")` and it works fine on my Linux. I did not find any problem with loading the rda files. Plus, it also passed `R CMD check iteremoval_0.99.5.tar.gz` and `R CMD BiocCheck iteremoval_0.99.5.tar.gz` on my computer.

Could you please tell me what is the possible reason for it and how I could fix it?

**Comment by lshep** [comment]
Could something like [this be the issue](
https://stackoverflow.com/questions/12463583/what-could-cause-a-bad-magic-number-error-when-loading-an-r-workspace-and-how)

**Comment by cihga39871** [comment]
Thank you, @lshep. I fixed the problem.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see the following suggestions/comments/questions: 

**Fix Notes in build report:**
- [ ] LICENSE is missing from DESCRIPTION file
- [ ] partial match argument  warning 
- [ ] global variable warning see `?globalVariables`
- [ ] Add unit tests
- [ ] Add top level NEWS file to keep track of changes 
- [ ] Consider shortening lines to 80 characters long. we prefer lines to be no longer than 80 characters and to wrap appropriately because of standard default window lengths in R/Rstudio/web browsers ect. shorten if possible


**License**
- [ ] Because you are using GPL-2 you do not need to include the license in the top level directory. Please remove

**package_build**
- [ ] Can this file be deleted? 

**data-ignore / data-raw** 
- [ ] Can these directories be deleted? 

**General**
- [ ] function names should not contain a dot ".". This implies S3 dispatch. Please change function names to either camelcase or use an underscore "_"

**demo**
When I try to run the demo code I get ERROR that the object is not found. it looks like the names of the objects are wrong?
```
> library(iteremoval)
Loading required package: ggplot2
Use suppressPackageStartupMessages() to eliminate package startup
messages.
> 
> g1 = SWR1[,5:ncol(SWR1)]
Error: object 'SWR1' not found
> g0 = SWR0[,5:ncol(SWR0)]
Error: object 'SWR0' not found
```

**vignette**
- [ ] execute all code in the vignette - why is there eval=FALSE for summarizedExperiment example especially when the code is quick to run?
- [ ] Probably should specifiy that the two datasets SWRG1 and SWRG2 are data.frames - it is implied with row and column but better to explicitly state and still describe. 
- [ ] The description of SummarizedExperiment object should be a little more explicit too. Where the colData contains a column 'Group' indicating normal(0) from malignant (1). Does the column containing this information have to be the name 'Group', if so this should be stated? Does it have to be contained within the SummarizedExperiment?
 

**man**
- [ ] For the data. SWRG0, SWRG1, and SummarizedData can you please indicate how the data was generated and where it came from. Should have a more descriptive element like in vignette row represents, columns represents, etc... 

**R code**
- [ ] As mentioned before don't use  dot "." in function names as this indiciates S3 dispatch. A "." indicating an internal function is fine (ie. .feature.remove.iteration could become .featureRemovalInteration or .feature_removal_interation if it is not exposed to the user)
- [ ] Fix spacing and indentation - we recommend an indentation of 4 and lines to be no more than 80 characters. There is a package `formatR` that can assist. 
- [ ] sometimes you use "=" and sometimes you use "<-" to assign variables. Please update all to use "<-"

feature_removal.R 
.multiple.feature.removal.interation
- [ ] Since you use the same initializing factor I believe it can be shortened to `df.removed.feature_names = df.removed.scores = df.max.scores = data.frame(...)`

import.R 
- [ ] generally we encourage these import calls to be in the R script that utilizes them. This should be removed and the imports should be included where relevant code. 

methods.R
- [ ] if you are really describing in detail in the other help page, you can use @aliases and @describeIn for it to be documented in the same place. 
- [ ] reciprocal.colSums, ones, min_max, linear.combine all seem helper functions that shouldn't be exported to the user.

Please make appropriate changes, do a version bump for new build, and comment back here in response to the above.  I will then conduct another review.  

Cheers and thank you for your interest in Bioconductor.

**Comment by cihga39871** [comment]
Hi @lshep,
Thank you for the detailed suggestions! Those are really helpful! 
I updated my code and the details are listed below. Could you please conduct another review?

**Fix Notes in build report:**

- [x]  LICENSE is missing from DESCRIPTION file
- [x]  partial match argument warning
- [x]  global variable warning see ?globalVariables
- I checked the variables, and those are variables in other functions.

| Var | Explanation |
|-|-|
|.feature.removal.iteration: no visible binding for global variable . | dot refers to the first parameter of `$>$` |
|feature.prevalence: no visible binding for global variable . | dot refers to the first parameter of `$>$` |
|ggiteration_trace: no visible binding for global variable Index | defined in function `.multiple.feature.removal.iteration` |
|ggiteration_trace: no visible binding for global variable ind | defined in function `utils::stack` |

- [x]  Add unit tests
- [x]  Add top level NEWS file to keep track of changes
- [x]  Consider shortening lines to 80 characters long. we prefer lines to be no longer than 80 characters and to wrap appropriately because of standard default window lengths in R/Rstudio/web browsers ect. shorten if possible
- Few lines are not changed for "\n" will print on the screen if I do so.

**License**

- [x]  Because you are using GPL-2 you do not need to include the license in the top level directory. Please remove

**package_build**

- [x]  Can this file be deleted?
- I did not delete it, because It is useful when I check the package, and it is added to .Rbuildignore

**data-ignore / data-raw**

- [x]  Can these directories be deleted?
- I can delete data-ignore. But when I remove data-raw, the build might fail.

**General**

- [x] function names should not contain a dot ".". This implies S3 dispatch. Please change function names to either camelcase or use an underscore "_"

**demo**

- [x] When I try to run the demo code I get ERROR that the object is not found. it looks like the names of the objects are wrong?
```r
> library(iteremoval)
Loading required package: ggplot2
Use suppressPackageStartupMessages() to eliminate package startup
messages.
> 
> g1 = SWR1[,5:ncol(SWR1)]
Error: object 'SWR1' not found
> g0 = SWR0[,5:ncol(SWR0)]
Error: object 'SWR0' not found
```
- Fixed.

**vignette**

- [x]  execute all code in the vignette - why is there eval=FALSE for summarizedExperiment example especially when the code is quick to run?
- Changed to eval=TRUE. I thought it might be slow, but it seems quick to run.
- [x]  Probably should specifiy that the two datasets SWRG1 and SWRG2 are data.frames - it is implied with row and column but better to explicitly state and still describe.
- I specified it in `man/SWRG*.md`
- [x]  The description of SummarizedExperiment object should be a little more explicit too. Where the colData contains a column 'Group' indicating normal(0) from malignant (1). Does the column containing this information have to be the name 'Group', if so this should be stated? Does it have to be contained within the SummarizedExperiment?
- I added the Group description to `man/SummarizedData.md`. Besides, `man/feature_removal.md` specified that parameter `SE` has to be SummarizedExperiment object, and that paramter `g0.filter` does not require the same name of 'Group', and it only need a bool vector (`SummarizedData$Group==0`).1

**man**

- [x]  For the data. SWRG0, SWRG1, and SummarizedData can you please indicate how the data was generated and where it came from. Should have a more descriptive element like in vignette row represents, columns represents, etc...

**R code**

- [x]  As mentioned before don't use dot "." in function names as this indiciates S3 dispatch. A "." indicating an internal function is fine (ie. .feature.remove.iteration could become .featureRemovalInteration or .feature_removal_interation if it is not exposed to the user)
- [x]  Fix spacing and indentation - we recommend an indentation of 4 and lines to be no more than 80 characters. There is a package formatR that can assist.
- I modified most of the lines, but I did not change some lines related to print a string to the screen, because that might print a wrong `\n`.
- [x]  sometimes you use "=" and sometimes you use "<-" to assign variables. Please update all to use "<-"

feature_removal.R
.multiple.feature.removal.interation

- [x]  Since you use the same initializing factor I believe it can be shortened to df.removed.feature_names = df.removed.scores = df.max.scores = data.frame(...)
- Thanks! That looks nice on my code.

import.R

- [x]  generally we encourage these import calls to be in the R script that utilizes them. This should be removed and the imports should be included where relevant code.
- Thanks. I removed the file.

methods.R

- [x]  if you are really describing in detail in the other help page, you can use @Aliases and @describein for it to be documented in the same place.
- Thanks! I consulted the roxygen documentation and used \@rdname instead for I can rename the md file.
- [x]  reciprocal.colSums, ones, min_max, linear.combine all seem helper functions that shouldn't be exported to the user.
- I did not change this part. For if might cause inconvenience for users to use `feature_removal`, and please see the code block below.

```r
# Now they can use it this way:
feature_removal(g1=NULL, g0=NULL, cutoff1, cutoff0, lt=">",
    offset=1,
    weight.method=ones,
    scoreStandardization.method=min_max,
    scoreCombine.method=linear_combine)

# If not exporting those functions, uses have to specify the package. This is because the input of **.method can be functions.
feature_removal(g1=NULL, g0=NULL, cutoff1, cutoff0, lt=">",
    offset=1,
    weight.method=iteremoval::ones,
    scoreStandardization.method=iteremoval::min_max,
    scoreCombine.method=iteremoval::linear_combine)
```

**Comment by cihga39871** [comment]
Hi @lshep 
I updated it. Could you please check the package?

**Comment by lshep** [comment]
Thank you for your updates.  Please see the following to additionally address:

- [ ] Extra directories and files : The extra directories and files will not be permitted in Bioconductor.  We suggest you make a separate github branch, perhaps 'maintenance' that has all the extra directories and files you would like to keep and use for your own purposes, and have the 'master' branch be a clean package structure. A clean structure would involve removing Rplots.pdf, package_build, and the data-raw directory and please place iteremoval.Rproj in the .gitignore file.  The data-raw directory seems to contain a script to convert raw data to the data included in the package, this type of file should be included in an inst/script directory. 

- [ ] Thank you for identifying the global variables but you still need to correct by using `globalVariables`. Please fix. We recommend identifying a global variable in/near the usage. 

- [ ] Add runnable example to reexports.Rd

Thank you.  As before, please do a version bump to kick off a new build and comment back here when the above are addressed.

**Comment by cihga39871** [comment]
Hi @lshep 
Thank you for checking the package.

I fixed the three problems you commented.

The extra directories and files were removed;
I modified the code to avoid the error of the undetectable global variables;
reexports.Rd was removed since it was generated by `importFrom` in roxygen2 and it was not necessary. I just used another way to import graphics.

Now I guess the package meets all the demands. Thank you.

**Comment by lshep** [comment]
Thank you for your effort

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cihga39871.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"iteremoval\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iteremoval

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
