### ISSUE TITLE
GeneStructureTools Submission

### ISSUE THREAD

**Issue by betsig** [Bioconductor/Contributions#627]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/betsig/GeneStructureTools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
This package promises to be very useful. Reading the vignette, it looks like these alternative splicing programs produce multiple outputs for the same input, and the vignette manipulates these outputs individually to produce the plots. Would it make things easier for the user if there was a way to read all of the files for a given project at once into a single, self-contained object? Not sure I like the `format*` functions that coerce whatever was read in (a data.frame?) into a GRanges. There should be more direct ways of getting to a GRanges or other formal object.

**Comment by betsig** [comment]
@lawremi 
I've updated some of the functions to read in whippet data files as a single object, which should make things a little less messy. 
There are summary functions (e.g. `whippetTranscriptChangeSummary()`) that run all of the individual alternative splicing programs (exon skipping, intron retention, alt splice sites, alt first/last) at once, but I've gone through individual examples in the vignette as well.

**Comment by vobencha** [comment]
Hi,

I've done a first review. A few comments and suggestions -

1) combine man pages
I'd recommend grouping the man pages into categories that make sense to you. You could combine all readWhippet* functions, find* functions etc. or you could put all methods for the shippetDataSet together.  I think this makes discovery easier and gives the user a 'bigger picture' of what is possible.

2) all man pages need running examples

3) function argument names
gtf.exons and gtf. transcripts are actually GRanges and not gtf files. Why not name them exons and transcripts?

4) Remove R/sysdata.rda and vignettes/Vignette.html

5) DEXSeq vs DEXSeq2
Does the package also support output from DEXSeq2? If no, why not? Please explain this in the vignette since DEXSeq2 has replaced DEXSeq in general use.

    Also, there is no explanation of how dexseq_processed.Rdata was created or curated. How can the user create this data for themselves?

6) Please rename the vignette to something informative. You can just use the name of the package or 'Introduction to ...'.

**Comment by betsig** [comment]
Hi @vobencha 
I've tried to address all your comments in the version 0.99.3 update.

1 & 2. The man pages were all generated automatically by roxygen2. Because of this they all are generated as separate files for each function. While it is possible to manually group them into fewer, larger files this creates extra hassle when updating any of the entries. 

In addition, generally users would search for function man using ?function_name, which brings up the man page for that single function, and therefore grouping does not provide additional help.

3. As far as I am aware, all exported functions have working examples. This was checked by R CMD Check prior to submission. Internal functions do not require running examples, as they are not available to the user.

4. I am not sure what you mean by this. Could you please clarify? I have tried to give functions argument names which are short, descriptive, and are camelCase where possible.

5. I have renamed these transcripts and exons.

6. I have removed sysdata.Rdata and Vignette.html

7 & 8. As far as I am aware, DE**X**Seq2 does not exist. There is another package (DESeq & DESeq2) which is used for differential gene expression, and not differential exon usage. GeneStructureTools can be used with DE**X**Seq data and not DESeq data.

**Comment by vobencha** [comment]
Hi,

The response you wrote back has 8 points where the original message I wrote has 6. It's a little confusing to know exactly how your responses relate to my questions.

Responding to your 1-8 above:

1/2. How is the user going to know the names of all of the functions so they can read the individual man pages? Where is the big picture and how do they know which functions are related to each other by class or function?

3. There are several man pages without examples:
coordinate-methods.Rd
diffSplicingResults-methods.Rd
...
I'm not going to list them all here. Man pages for data sets also need examples. Neither of these pages explain what exactly is in the data set, column names, row names if any, where did the data come from how was it curated (if it was) etc.

For example, someone unfamiliar with 'whippet' would have no idea what this means:
```
\value{
whippet event coordinates GRanges
}
```
4. I don't know what you are referring to. Please clarify. My question number 4 had nothing to do with function names.
5. This is addressing my number 3. Thank you for renaming the arguments.
6. Thank you for removing those files.
7. Ah yes. This was an oversight on my part - I completely missed the 'X'.

**Comment by betsig** [comment]
@vobencha Sorry I think the formatting got a bit jumbled up so anything on a new line had a number

The \*-methods.Rd should all now have examples.

> Man pages for data sets also need examples

None of the datasets are located in data/, where they would need to be documented.
They are all either internal data (in R/sysdata.Rdata), which doesn't need documentation, or in extdata/, which also doesn't require documentation as per: http://r-pkgs.had.co.nz/data.html#documenting-data

For the data in extdata/ all of it is explained by reading the vignette - which is why it is included in the first place (beyond having running, relevant examples for each exported function). 
They are mostly samples of output you would receive from any of the three input tools (DEXSeq, leafcutter, Whippet), and thus a detailed description of them is available by checking their respective manuals (which I have also made clearer in the vignette). 

> How is the user going to know the names of all of the functions so they can read the individual man pages? Where is the big picture and how do they know which functions are related to each other by class or function?

Users can find out the names of functions and how to use for their primary purposes by reading the vignette. In terms of 'big picture' all I can conceivably do without adding extra unnecessary steps prior to package building is add @family roxygen tags to all exported functions. 
All functions should now have a family - which points users towards other functions in the same family (under See Also in the man page).

> I don't know what you are referring to. Please clarify. My question number 4 had nothing to do with function names.

Original point 3 got split at the line break, so I thought this by itself was a question. In light of this, my response made no sense either. 

Thanks for your comments, and let me know again if there's anything else I have missed.

**Comment by vobencha** [comment]
@lshep can you please do an SPB re-run of this issue?

**Comment by betsig** [comment]
The errors are coming from "Cannot utime: Permission denied" 
I assume this is to do with the way windows installs the package and doesn't receive correct permissions? 
Is there any way to correct this? The package passes checks on linux and OSX

**Comment by vobencha** [comment]
Thanks for adding the function families. I think that was a good solution.
Package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/betsig.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"GeneStructureTools\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeneStructureTools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
