### ISSUE TITLE
adaptest

### ISSUE THREAD

**Issue by wilsoncai1992** [Bioconductor/Contributions#628]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wilsoncai1992/adaptest

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your repository so that 'master' contains only the components corresponding to the package (e.g., move paper/ etc to a new branch).

**Comment by wilsoncai1992** [comment]
thanks @mtmorgan , I will remove them

**Comment by wilsoncai1992** [comment]
For the build error, it is due to my using a bleeding-edge version of `origami`. my co-author, nima hejazi, will work on bumping the `origami` version

**Comment by LiNk-NY** [comment]
Hi Wilson, @wilsoncai1992

It seems to me like your package does not provide any integrative features to
the Bioconductor environment.

Please see the link below for a brief overview of potential classes to provide functionality for. 
http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

Regards,
Marcel

**Comment by wilsoncai1992** [comment]
Thank you Marcel @LiNk-NY for bringing this up! In fact a wrapper facing `SummarizedExperiment::SummarizedExperiment()` is almost ready and will be soon pushed to `master`. Once that wrapper is ready, I will ping you for proceeding?

**Comment by LiNk-NY** [comment]
Yes, please do. Thanks.

**Comment by LiNk-NY** [comment]
Hi Wilson, @wilsoncai1992 

Any updates on implementing these changes? 

Regards,
Marcel

**Comment by wilsoncai1992** [comment]
hi Marcel @LiNk-NY ! We are actively implementing the changes on branches of `adaptest`. We will update by next Mon.

**Comment by LiNk-NY** [comment]
Hi Wilson, @wilsoncai1992 
Thanks for the update! 
M.

**Comment by wilsoncai1992** [comment]
hi Marcel @LiNk-NY ! The integrative features to the Bioconductor environment has been completed in our latest PR:
https://github.com/wilsoncai1992/adaptest/pull/39

**Comment by LiNk-NY** [comment]
Hi Wilson, @wilsoncai1992 

Can you please respond the the individual items in the review?
Please state how you addressed these points. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Wilson, @wilsoncai1992 
Just a reminder to post your response to the review here. 
Best regards,
Marcel

**Comment by wilsoncai1992** [comment]
Dear Marcel @LiNk-NY , thanks for reminder! I am actively preparing a response and will post them before the end of the week! Thanks again for your patience!
Best regards,
Wilson

**Comment by wilsoncai1992** [comment]
Dear Marcel @LiNk-NY , I confirm that all issues that all BIOC requirements have been met, and that I would love to request a full review on the package. Thank you!

**Comment by wilsoncai1992** [comment]
> Hi Wilson, @wilsoncai1992
> 
> It seems to me like your package does not provide any integrative features to
> the Bioconductor environment.
> 
> Please see the link below for a brief overview of potential classes to provide functionality for.
> http://bioconductor.org/developers/how-to/commonMethodsAndClasses/
> 
> Regards,
> Marcel

Dear Marcel, now there is a BIOC integrating wrapper called `bioadaptest` in the package. An example of using the wrapper can be found in the vignette! The wrapper is facing the `SummarizedExperiment::SummarizedExperiment()` object class.

**Comment by wilsoncai1992** [comment]
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> Congratulations! The package built without errors or warnings
> on all platforms.
> 
> Please see the build report for more details.
 Dear @LiNk-NY Marcel, glad to inform you that all builds are passing

**Comment by wilsoncai1992** [comment]
Dear Marcel @LiNk-NY  just want to make sure we do not miss the contribution deadline for BioC 3.7?

**Comment by LiNk-NY** [comment]
Hi Wilson, @wilsoncai1992 

We have not missed it. Please see: http://www.bioconductor.org/developers/release-schedule/
I will post the review soon. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Wilson,
Thank you for your submission. 
I have reviewed your package. Please see below. 

If you have any questions, don't hesitate to ask. 

Best regards,
Marcel

---

# adaptest #628

## DESCRIPTION

* Looks good
* Use the release version of `roxygen2`

## NAMESPACE

* You may want to separate the "shinyprint" functionality into a different
package?

## R

* Avoid using cryptic argument names, use names that are descriptives and
helpful for the end user
* The `data_adapt` class is based on a list which is not the best structure
to use as you can't really enforce any validity checks to the components of
the class as easily as you would with an S4 class.
* You've added support for `SummarizedExperiment` which is good :+1:
* Avoid the use of `1:n` constructions
* Use the allocate and fill method, e.g.,
 `ls <- vector("list", ncol(adaptY_composition))`
* Avoid using `grep` to find colnames in `cv_param_est`. Let the user provide
the colname directly from the argument.
* Replace `sapply` calls with the more robust `vapply`
* You shouldn't need to "wrangle" the supported `SummarizedExperiment` class
for your main function, it should just work with it as part of the integration
process. In other words, it should make use of the `SummarizedExperiment` API
rather than the `assay(x); t(x)` and `rownames(x) <- colnames(x) <- NULL`
version. 
* A proper API should not use `@` accessor functions. See: 
http://bioconductor.org/developers/how-to/efficient-code/

## data

* Provide descriptive names for your data,`Y` and `A` can mean anything.

## vignette

* It looks like you commented `BiocStyle` out.
* Please add an installation chunk. It doesn't have to run. 
* Looks good overall.

**Comment by wilsoncai1992** [comment]
Thank you @LiNk-NY Marcel! My team will address all your comments in the next few days

**Comment by nhejazi** [comment]
Hello @LiNk-NY ---

I am @wilsoncai1992's co-author on this package. I'm just writing to let you know that we have addressed nearly all of the review items you kindly pointed out in your recent review. About half of the items were address in [`adaptest`/41](https://github.com/wilsoncai1992/adaptest/pull/41) while the remainder were addressed in [`adaptest`/43](https://github.com/wilsoncai1992/adaptest/pull/43). Here are a few specifics on how major review items have been resolved (all addressed items were dealt with as part of `adaptest`/41 and `adaptest`/43) and an exception that we would like to the review:

- [x] You shouldn't need to "wrangle" the supported `SummarizedExperiment` class for your main function, it should just work with it as part of the integration process. In other words, it should make use of the `SummarizedExperiment` API rather than the `assay(x)`; `t(x)` and `rownames(x) <- colnames(x) <- NULL` version.
   - addressed by having the `adaptest` function wrangle `RangedSummarizedExperiment` objects differently from `data.frame` or `Matrix`, making the analysis function more extensible (#43)
- [x] A proper API should not use `@` accessor functions. See: http://bioconductor.org/developers/how-to/efficient-code/
   - addressed by addition of `get_results_adaptmle` accessor function in #43
- [ ] The `data_adapt` class is based on a `list` which is not the best structure to use as you can't really enforce any validity checks to the components of the class as easily as you would with an S4 class.
   - currently, we use the standard S3-style ad-hoc classed `list` as the core structure (despite, having authored 2 other Bioconductor packages, agreeing that it is bad practice to do so) for across-community compatibility of the statistical routine exposed by this software. It is our aim to make this new statistical technique easy to use for the Bioconductor community via the `bioadaptest` wrapper function while still making the core software easy to inspect for those well-versed in the methodology produced by our statistical community but yet unfamiliar with Bioconductor and related best practices (though we do hope to slowly remove this part of the code base and replace with S4, or maybe R6, as the package picks up users). Would it be acceptable to delay this until a future release? With some input from you, we could likely make this happen very easily and quickly, certainly in time for BioC 3.8 later this year.

**Comment by LiNk-NY** [comment]
Hi Wilson and Nima, @wilsoncai1992 and @nhejazi

Thank you for making those changes! It's looking better. 

I've noticed that you're using the magrittr pipe `%>%`. 
I think you can do without the dependency since you're only using it for ~6 lines in the code. 

I saw that you haven't made any changes to some argument names that are hard to figure out.
Namely, arguments `Y` and `A` would be better if they were named `biomarkers`, `treatment` or
something to that effect. 

Other than that, it looks good. 

Best regards,
Marcel

**Comment by wilsoncai1992** [comment]
> Hi Wilson and Nima, @wilsoncai1992 and @nhejazi
> 
> Thank you for making those changes! It's looking better.
> 
> I've noticed that you're using the magrittr pipe %>%.
> I think you can do without the dependency since you're only using it for ~6 lines in the code.
> 
> I saw that you haven't made any changes to some argument names that are hard to figure out.
> Namely, arguments Y and A would be better if they were named biomarkers, treatment or
> something to that effect.
> 
> Other than that, it looks good.
> 
> Best regards,
> Marcel


Thank you @LiNk-NY Marcel! your latest comments will be quickly addressed.

**Comment by nhejazi** [comment]
Hello @LiNk-NY ---

Thanks for the quick follow-up on this. Finding that unnecessary `dplyr` dependency was great --- looks like we were only using it in a script that belonged on a development branch and importing it needlessly in a few other places. It's been completely removed as of the latest commits that built on the Bioconductor machines.

With respect to the argument names (e.g., A, Y), I assume you're referring to the [`adaptest` function](https://github.com/wilsoncai1992/adaptest/blob/master/R/adaptest.R). For this particular function, we intentionally did not change the names away from (W, A, Y), since this is the notation using in the [Targeted Learning (TL)](http://www.targetedlearningbook.com/) literature, on which the technique that `adaptest` implements is based. In order to keep the package friendly/accessible to those in the TL community, we are trying to be consistent with notation (e.g., matching the [drtmle](https://github.com/benkeser/drtmle/) package). As mentioned above, those in the Bioconductor community should not use this function and instead use the `bioadaptest` function, which has argument names that ought to be easily interpretable. Maintaining this distinction ensures that those in the TL community who want to employ this data-adaptive testing strategy outside of the context of computational biology are able to do so, without thinking in terms of different notation, without at all affecting our intended audience in the Bioconductor community. Hope this clears up our perspective.

Please feel free to let us know if there's any more that we can do to make `adaptest` Bioconductor ready/friendly. Finally, thank you very much for the time spent on this thorough review.

**Comment by LiNk-NY** [comment]
Great! Thanks for that. 
Your package has been accepted. 
Thank you for your submission to Bioconductor!

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wilsoncai1992.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"adaptest\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/adaptest

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
