### ISSUE TITLE
MetaGxOvarian

### ISSUE THREAD

**Issue by mzon7** [Bioconductor/Contributions#636]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/MetaGxOvarian

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hello, 

Thank you for your submission to Bioconductor.  Please see the following comments concerning the package: 

**BUILD REPORT**
- [ ] Packages listed in Depends in your DESCRIPTION should be imported in your namespace. Consider selective imports in NAMESPACE if only certain functions are needed (ie. importFrom(stats, quantile) etc.), I don't think you need to specify AnnotationHub, ExperimentHub will load AnnotationHub for you. 
- [ ] See ?globalVariables for help on defining global variables and see suggested imports for functions. 
- [ ] Add unit tests
- [ ] See coding practice about sapply and 1:n syntax ... 
- [ ] possible warning with vignette - 

**README**
- [ ] Add Bioconductor installation instructions
```
source("https://bioconductor.org/biocLite.R")
biocLite("MetaGxOvarian")
``` 

**MAN PAGES**
- [ ] Please document patientselection.config, BenDuplicate.rda

**VIGNETTE**
- [ ] vectorize where possible
ex:
obtaining sample counts in dataset can be vectorized with a vapply:
```
numSamples <- vapply(seq_along(esets), FUN=function(i, esets){length(sampleNames(esets[[i]]))}, numeric(1), esets=esets)
```
- [ ] apply best coding practices to code included in vignette See if phenotype data can be vectorized at very least update from using 1:n notation in for loops. 

**R code**
- [ ] you could leave the explict Biobase:: ExperimentHub::  but when the NAMESPACE is updated to include the relavent imports you should just be able to call the function.  

**Notes**
It might also be nice to eventually convert the eSets over to the more formalized SummarizedExperiment objects and to include both formats of data in the ExperimentHub and accessible through the package. SummarizedExperiments are generally recommended in place of eSets but eSets are still valuable to have. 

Please address the above concerns. When ready for a second review please ensure a new build has been triggered with a version bump and comment back here addressing the above concerns. 

Cheers.

**Comment by mzon7** [comment]
Hi, I have addressed the above concerns and triggered a new build. More specifically and in the order listed above, I have addressed the following in the Build Report. 
- I made sure the packages in the Description file were imported into the namespace. I decided to leave the AnnotationHub import so I could add importFrom(annotationHub, query) to the namespace in order to get rid of the Note saying that query is not globally defined, as I thought global definitions Notes were part of your concers (the next point)
- I adjusted the package so that global variables and functions were not complained about during the build process. I believe this was in part due to the naming conventions of the variables having dots in them
- Unit test have been added 
- I removed any sapply code that contained a 1:n syntax
- The vignette warning is quite confusing and I am not sure what to do here. The vignette appears to build with no problems on Linux, but has 1 warning when building on OSX. Any insight into this would be much appreciated. The only thing I have to go on from the build report is the following, "LaTeX errors when creating PDF version.
This typically indicates Rd problems."

Readme
- I added the installation instructions to the readme file, although I did this after I triggered a new build

vignette
- I changed all the could to be vectorized

R code
- I decided to leave the :: notation in the code although I know it is not neccessary, but I can remove this if it is required

Notes
We will definitely consider converting the esets to summarizedExperiment objects down the line. For now our current objective is to get this package, and the equivalent breast dataset package on to experimentHub. Then put our package that analyzes the datasets on to the hub as well.

Thanks for the help!

**Comment by lshep** [comment]
Thank you for the update.  I believe we are almost ready for acceptance: 

There are still a few coding practice instances where sapply is used (we highly recommend vapply over sapply)  and where there is 1:n syntax instead of seq_along or seq_len 
```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply() found in files:
    loadOvarianEsets.R (line 67, column 24)
    loadOvarianEsets.R (line 69, column 19)
    loadOvarianEsets.R (line 169, column 34)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
    loadOvarianEsets.R (line 60, column 70)
    loadOvarianEsets.R (line 86, column 12)
    loadOvarianEsets.R (line 111, column 13)
```
Could you please update these?


As far as the PDF ERROR -  
There is some suggestion on stack overflow to try to run the following command to debug latex issues
```
R CMD Rd2pdf MetaGxOvarian --no-clean
```
I'm not overly concerned with this WARNING since the vignette does seem to generate and display but it would be nice if it could be cleaned up. 

Cheers

**Comment by mzon7** [comment]
Hi,
I changed each instance of sapply mentioned above to vapply and replaced 1:n syntax with seq() functions. I also managed to replace the sapply functions in the vignette with vapply. I ran Rd2pdf but was unfortunately still unable to find anything that looked like it could be the cause of the OSX warning in the build report. Let me me know what else needs to be done to get the package accepted. Once it is accepted I will be submitting a package that is more or less identical but contains breast datasets instead. Thanks for the assistance!

**Comment by lshep** [comment]
Hey, sorry a new build report never got posted.  I'm going to manually kick off a build now so I can look at it again -  ignore the ERROR for now, I think this was the legacy from the one that didn't finish the other day but seems like it is our issue.

**Comment by lshep** [comment]
I think everything looks okay.  I'll ignore the warnings for now and see once it gets on the main builders if it clears up or if there is a better indication of what is going on with the vignette.  Once the landing page gets generated I encourage you to look at the vignette that is created to see if it looks correct or if anything looks odd there.  

Let me know when you have the breast data package set to get the data onto the hubs. 
Cheers -

**Comment by mzon7** [comment]
Great, I will definitely check out the vignette when the landing page is up. The breast data should actually be on the hub already (MetaGxBreast). I will get started on the package asap.

Cheers

**Comment by lshep** [comment]
Th MetaGxBreast is in the S3 bucket but I can't make it accessibly through the ExperimentHub without the metadata.csv file in the package -  so let me know when that file is ready and send me a link to the github repo please.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mzon7.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MetaGxOvarian\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaGxOvarian

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment]
This 'Experiment Data' package needs to use biocViews terms exclusively from the 'Experiment Data' [hierarchy][1]. Since the package has been accepted, the biocViews terms need to be updated in the [Bioconductor git repository][2].

[1]: http://bioconductor.org/packages/devel/BiocViews.html#___ExperimentData
[2]: http://bioconductor.org/developers/how-to/git/new-package-workflow/

**Comment by mzon7** [comment]
Hi,

I have attached the metadata.csv file for the breast data to this email
along with a link to the github repo. However, please be advised the github
repo is not complete yet.
https://github.com/bhklab/MetaGxBreast

Best,
Michael

**Comment by mzon7** [comment]
Hi,

Sorry, I attached the ovarian metadata.csv. Here is the correct csv file.

Michael
