### ISSUE TITLE
diffcoexp

### ISSUE THREAD

**Issue by wenbinwei** [Bioconductor/Contributions#638]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hidelab/diffcoexp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
As an initial comment, your package must expose to the user functions that accept [SummarizedExperiment][1] objects. This facilitates reuse and iteroperability in the Bioconductor community.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by wenbinwei** [comment]
Dear Martin,
Thank you for reviewing the diffcoexp package. Following your initial comment, I have modified my three functions to accept SummarizedExperiment objects. I have pushed the changes to the Github repository with version number 0.99.1.
BW,
Wenbin

**Comment by wenbinwei** [comment]
I am puzzled why the push of version of 0.99.1 did not trigger rebuilding of my package in bioconductor. I have added the webhook following the instruction of https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook.

**Comment by mtmorgan** [comment]
There could be a problem on our end, but can you check out the return value of the web hook, following [these instructions][1]?

[1]: https://github.com/Bioconductor/Contributions#additional-actions

**Comment by wenbinwei** [comment]
The response was "OK" yesterday but since I clicked the 'Redeliver' button ten minutes ago, I have not received a response.

**Comment by wenbinwei** [comment]
Version 0.99.1 has been rebuilt by bioconductor successfully. Hopefully I have addressed your initial comment about accepting SummarizedExperiment objects.

**Comment by mtmorgan** [comment]
Please address the following comments, update the version number, and post a comment briefly summarizing your response.

DESCRIPTION

- Consider whether packages in the "Depends:" field should instead be listed inthe "Imports:" field. This would be the case if the package were used strictly internally to your package.

vignette

- update installation instructions to reflect the status of the package after acceptance -- `biocLite("diffcoexp")`
- Describe the inputs to the function -- what are rows, columns, values (e.g., normalized?)
- Describe the output columns of each data frame. Consider offering an informative visualization and interpretation.
- Provide some guidance other parameter choices, e.g., why `r.method = "spearman"`?
- Note in the vignette that the first arguments can be SummarizedExperiments.

R

- diffcoexp.R:160 use `is(exprs.1, "SummarizedExperiments")` to test for class, et.
- use `message()`, `warning()`, `stop()` rather than `print()`; when updating, note that it is often not needed to use `paste()` inside `message()`.

data

- The data are really a matrix rather than data.frame; represent as such.

Other

- NEWS: Format so that `utils::news()` parses the file.
- Nice to see unit tests!

**Comment by mtmorgan** [comment]
Don't forget to bump your package version (to 0.99.2) to trigger the build system. If you're ready to continue the review process please post a short comment here indicating the changes you've made.

**Comment by wenbinwei** [comment]
Thank you for the comments. I have made the following changes accordingly.

DESCRIPTION

    moved some packages in the "Depends:" field to  "Imports:" field. 

vignette

    updated installation instructions to reflect the status of the package after acceptance -- biocLite("diffcoexp")
     added section 3 to describe the inputs to the function -- what are rows, columns, values 
     mentiond that details of the output columns of each data frame can be found in help page. 
     added section 4 to discuss visualization and interpretation of DCGs and DCLs.
     mentioned where to find further details of other parameters, e.g.,  r.method 
     mentioned that the first arguments can be SummarizedExperiments.

R

   diffcoexp.R:160 use is(exprs.1, "SummarizedExperiments") to test for class, et. Done
    use message(), warning(), stop() rather than print(); when updating, note that it is often not needed to use paste() inside message(). Done

data

    The data are really a matrix rather than data.frame; represent as such. Done

Other

    NEWS: Format so that utils::news() parses the file. Done formatting. Will check with utils::news()

**Comment by wenbinwei** [comment]
NEWS file cab be  parsed by utils::news().

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wenbinwei.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"diffcoexp\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/diffcoexp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
