### ISSUE TITLE
DominoEffect

### ISSUE THREAD

**Issue by peterblattmann** [Bioconductor/Contributions#642]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/peterblattmann/DominoEffect

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@LiNk-NY will review this package. It seems like it should support standard Bioconductor representations of relevant data types, e.g., variants from VCF files imported using [VariantAnnotation][1]. Please update your package to support relevant [Bioconductor classes][2].

[1]: https://bioconductor.org/packages/VariantAnnotation
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by peterblattmann** [comment]
Dear @mtmorgan and @LiNk-NY, 
thank you for reviewing our package and your comment. 

We have now included the possibility to use vcf and txdb objects for our SnpData and DominoData, respectively in the package (see new functions import_vcf.R and import_txdb.R that are also called  within the function identify_hotspots.R.). 

We also updated the package to remove the warnings displayed in the previous version. 

The Note about "import_txdb: warning in select(txdb_object, key = genes, columns =
  c("GENEID", "TXNAME", "TXTYPE", "CDSID", "CDSSTART", "CDSEND"),
  keytype = "GENEID"): partial argument match of 'key' to 'keys' "  we do not know how to address. 

Thank you very much for your help and support.

**Comment by LiNk-NY** [comment]
Hi Peter, @peterblattmann

I had drafted a message about the review but it was lost in my browser cache.

Apologies for the delay.

I originally intend to ask about the status of implementing VCF and related class support.

I see that you went ahead and started working on that. Great! 

I will formally review your package today.

Best regards,
Marcel

**Comment by peterblattmann** [comment]
Hi Marcel, @LiNk-NY 

thank you very much for your message. We are looking forward to your comments and if you have any questions do not hesitate to write us. 

Best regards,
Peter and Marija

**Comment by LiNk-NY** [comment]
Hi Peter, @peterblattmann 

Please note that the warning in `import_txdb` is about using a `key` argument 
instead of `keys` argument in `select`.

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Peter @peterblattmann and Marija,

Thank you for submitting to Bioconductor.
`DominoEffect` provides mechanisms for identifying and annotating 
hotspot residues in proteins. 

Please find the review below. If you have any questions please contact me here.

Best regards,
Marcel

---

# DominoEffect #642

* Please keep in mind that lines greater than 80 column width are harder
to read and maintain.
* It appears that the interoperability efforts for this package 
reduce the class structure and transform the contained data to conform
to the already written code.
* It would be good to see full interoperability with these classes by
providing direct use of class methods by not having to "import_*" from
the class.

## DESCRIPTION

* Looks good overall. 
* You could do without the `Packaged` field.
* Please format lines to less than 80 column width.

## NAMESPACE

* Please remove the `exportPattern` line. It's best practice to explicitly
export functions.
* No class imports present.

## R

* Please make use of native R functions such as `sort` in
`R/calculate_boundary.R`
* Have a section of code at the top of the function that is checking for
argument requirements, for example `length(flanking_region) == 2L`.
* Write helper functions to reduce repetitive code.
* Where possible, use established Biocondcutor classes as function outputs.
This helps your package 
* Allow the possible input of Bioconductor classes such as `GPos` for
snp_data and `GRanges` or `GRangesList` for mutation datasets. 
* Remove the use of the `globalVariables` in all code.
* Do not write to the user's file by default. Keep the file system clean
unless the user explicitly decides to save a file.
* Please remove the default datasets as arguments
(`TestData`, `DominoData`, etc.).
* Requiring that datasets contain the same exact names as indicated in your
code makes the function less flexible to other datasets that have slight
variations. 
* Where possible use character names instead of interger indices in subsets
such as `mutation_dataset[,"Original_aa"]` instead of `mutation_dataset[, 3]`.
If you add functio arguments like `Original_aa` you could just use
`mutation_dataset[, Original_aa]` in the code regardless of the actual column
name that indicates original amino acids. If you expect all datasets to have
this name than it would make sense to keep the current way of coding this,
although this is hardly ever the case.
* Add more tests, especially for the main `DominoEffect` function.

Minor: 
* `if(length(snp_data) > 0)` is equivalent to `if(length(snp_data)`


## vignettes

* Looks good. Please update the formatting for readability.

## man

* Looks good.

**Comment by peterblattmann** [comment]
Dear Marcel @LiNk-NY, 

thank you very much for your comments and advice. We addressed now all the comments in our new version DominoEffect v.0.99.2. 
We implemented that also GPo objects can be used as input for the SnpData (as well as vcf). Furthermore, we implemented that the mutation_dataset can be provided as a GRangesList or GRanges object and that the results of our package can be exported as a GPos object.
Moreover, we followed your suggestions in improving the code and among others implemented testing the argument requirement at the beginning of functions, removing the default arguments for the datasets, shortening lines to 80 characters where possible, and use arguments to call the different columns. We adapted also the Vignette accordingly. 
Only the import_tbxd.R we did not remove as we feel it is clearer if this remains as a separate function. 

With this we thank you very much for your input and support and are looking forward to your response. 

Best

Peter and Marija

**Comment by LiNk-NY** [comment]
Hi Peter @peterblattmann and Marija, 

Thank you for making those changes.
Your package has been accepted. Thank you for contributing to Bioconductor!

Best regards,
Marcel

**Comment by peterblattmann** [comment]
Dear Marcel @LiNk-NY, 
this is great, thank you very much for your help during the whole process. 
Best regards
Peter and Marija

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/peterblattmann.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"DominoEffect\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DominoEffect

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
