### ISSUE TITLE
SummarizedBenchmark 

### ISSUE THREAD

**Issue by areyesq89** [Bioconductor/Contributions#651]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/areyesq89/SummarizedBenchmark

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
I like the self-contained the data structure. However, the argument quotation in this API obfuscates the code. In the vignette, it was not at all clear that `pval` is referring to a component of the input data. Mixing arguments to the method function with other arguments like `blabel` is also confusing. Why not just have the user pass a function that accepts the BenchDesign object or the data and provides an explicit implementation?

**Comment by pkimes** [comment]
@lawremi thanks for taking a look at this!

To clarify, are you suggesting changing the API to something like:
```
addBMethod(
   bd = my_benchdesign, 
   blabel = "bh", 
   bfunc = function( data ){   
      p.adjust( data$pvals, method="BH" ) 
   } )
```
where the user just supplies a single function which takes the data as input and runs the method?

One thing we wanted to do with this package was automate grabbing metadata for each method (e.g. package name, package version) when the benchmarking experiment is actually run. This was one reason why we wanted to keep the primary functions/methods separate from the parameters. If we used wrapper functions, my understanding is that this would become a lot harder.

Another reason why we want to keep functions and parameters separate was to makes it easier to know which results were generated by the same/different functions, and using same/different parameters (since this is all stored as columns in the colData of the benchmark results). For example, suppose I want to compare running k-means clustering with different "k" (along with possibly other clustering algorithms) on a data set. The returned SummarizedBenchmark will have cluster labels in the assay for rows = samples, columns = clustering methods. With the current setup, the colData will include columns "`bfunc`" and "`k`" that I can use to subset on only `colData(se)$bfunc == "kmeans"` results, and I can also use the "`k`" column to compare across the kmeans parameter. If we used wrapper functions, we're back to manually trying to parse the anonymous function to figure out which one used what clustering algorithm with what parameters.

The point about mixing method arguments and arguments actually passed to `addBMethod` (like `blabel`) is well taken. We can try to clarify this by having users specify the method parameters to a single named parameter, e.g. `params =`, rather than ellipses. the call could look like:
```
addBMethod(
   bd = my_benchdesign, 
   blabel = "bh", 
   bfunc = p.adjust,
   params = list(p = pvals, method = "BH" ) 
)
```
The idea would be (maybe?) similar to the use of `aes()` in `ggplot2`.

**Comment by lawremi** [comment]
That's better. Still don't like that bare `pvals` there. What about using `alist()` there instead of `list()`? Or, while I'm not a huge fan of the tidy language, it probably has an equivalent of `alist()` that supports unquoting. And I think the function should just be named `addMethod()`.. why have the cryptic abbreviation `B` in there?

**Comment by pkimes** [comment]
The function started off as `addMethod()`. I don't like the cryptic `B` too much either, but I changed the function names when I realized a lot of them sounded confusingly similar to functions in the `methods` package. (The only actual conflict was `showMethods` to print the list of methods in the `BenchDesign`, but I could just call this `printMethods`.) If you think I/we are worrying too much, completely happy to drop `b`/`B` from everything.

**Comment by pkimes** [comment]
Is there a big difference between: 
- [A] having the user specify the parameters in something like `alist(...)` and 
- [B] having the user specify a `list` and capturing the expressions at the top of the function (what we're doing right now)? 

My assumption is that most people aren't familiar with `alist`, and taking care of the quoting for the user would be easier/better than asking them to remember to quote their inputs. (Just want to be as "user friendly" as possible.)

i.e.
```
myfunc1 <- function(...) { 
    quo_params <- eval(substitute(alist(...)))
    ## do stuff w/ quo_params
}
myfunc1(p = pval)
```
or, without ellipses:
```
myfunc1 <- function(params = list(p = pval)) { 
    quo_params <- rlang::lang_args(rlang::enquo(params))
    ## do stuff w/ quo_params
}
myfunc1(params = list(p = pval))
```
vs. 
```
myfunc2 <- function(quo_params) { 
    ## do stuff w/ quo_params
}
myfunc2(quo_params = alist(p = pval))
```

**Comment by lawremi** [comment]
Because using `alist()` makes it obvious that they are not just constructing a list but are rather quoting everything (and specifically constructing an argument list). Calling `alist()` will work outside of the call to the function, but `list()` would fail. To me, this implicit quoting is really confusing, but maybe that's just me and my brain that is used to R code being evaluated as R code.

**Comment by pkimes** [comment]
Point well taken. 
It wouldn't be too much work to change things to an API where users explicitly quote parameters which should be passed to the method, e.g.
```
addMethods <- function(bd, label, func, params) { 
    ...
}

addMethods(
   bd = my_benchdesign, 
   label = "bh", 
   func = p.adjust,
   params = rlang::quos(p = pval, method = "BH")
)
```
I/we'll think about this more (since our build is stuck behind a different package broken in devel anyway).

Thanks.

**Comment by pkimes** [comment]
In version 0.99.2, we've updated the package to reflect suggestions made above.
Namely:
1. dropped `b/B` prefixes from functions and parameters,
2. changed the API so method params are passed to `params =`,
3. changed the API so params must be passed using `rlang::quos()`.

We decided to stick with `rlang::quos()` rather than something like `alist()` as quosures keep track of environments. This can help avoid "surprises", e.g. if a user passes a variable with the same name as a variable defined within one of our functions (example below). 

```
## function in our package ------------
myfunc <- function(x) {
    foo <- 100
    cat("proportion significant: ",
        mean(rlang::eval_tidy(x[[1]]) < 0.10), "\n")
}

## user workspace ---------------------
foo <- seq(0, 0.99, by = 0.01)

myfunc(x = rlang::quos(pvals = foo))
# proportion significant:  0.1

myfunc(x = alist(pvals = foo))
# proportion significant:  0
```
We've also included a note on using `rlang::quos()` in the vignette, and added an informative error message if a user passes parameters without using `rlang::quos()` (i.e. if `!rlang::is_quosures(params)`).

Thanks for the feedback!

**Comment by areyesq89** [comment]
Hi @vobencha. Thanks for agreeing to review our package! We are trying to interpret the build report. The package passes R CMD build and R CMD check successfully. However, it marks that there is an error in the "postprocessing" step for all OS and the build system does not throw an informative error message that we could use to trace the source of these errors. Any recommendation?

**Comment by lshep** [comment]
This ERROR is on our end you can ignore it for now.

**Comment by vobencha** [comment]
Hi,
Nice job with the vignettes. Just a few comments about the man pages.
1) Please add examples to the class and data man pages. 

2) Detail on data man pages
Add more detail describing where the data came from, how generated or curated, row / column names if any etc. For example, this from availableMetrics.Rd is not very descriptive:
```
\value{
A data.frame with available performance metrics.
}
\description{
List default performance metrics available in this package.
}
```

@lawremi did you have any more comments?

Valerie

**Comment by lawremi** [comment]
Looks OK from my end. Remain skeptical about the NSE.

**Comment by pkimes** [comment]
Hi @vobencha, thanks for taking a look at this!
Based on your feedback, we've made the following changes to the package.

- Added more description and examples to the data and class man pages. Namely, in the most recent commit, we've update the documentation for `tdat.Rd`, `sb.Rd`, `allSB.Rd`, and `SummarizedBenchmark-class.Rd`. (see [here](https://github.com/areyesq89/SummarizedBenchmark/tree/e86b4cb/man).)
- Updated the description in the `availableMetrics.Rd` (see [here](https://github.com/areyesq89/SummarizedBenchmark/blob/e86b4cb/man/availableMetrics.Rd).)

We've also made the following changes to the package.

- Added a `catchErrors = TRUE` option to `buildBench()` which determines whether errors thrown by methods included in the benchmark should be caught and handled (`=TRUE` default) or thrown (`=FALSE`) causing `buildBench()` to fail.
- Added a call to `sessionInfo()` during `buildBench()` which is stored in the metadata of the generated _SummarizedBenchmark_ object.
- Updated the `Description:` in the `DESCRIPTION` file.
- Updated the `SummarizedBenchmark.Rmd` vignette with a newer figure and made minor fixes to typographical errors.

**Comment by vobencha** [comment]
Great. Thanks for making the changes - the package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/areyesq89.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"SummarizedBenchmark\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SummarizedBenchmark

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
