### ISSUE TITLE
iCNV

### ISSUE THREAD

**Issue by zhouzilu** [Bioconductor/Contributions#654]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhouzilu/iCNV

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by zhouzilu** [comment]
@Liubuntu The only warning I receieved is the R version update. In order for this package to be applicable to most of the user, I decided to maintain the requred R version to 3.3.1. Is that possible?

**Comment by zhouzilu** [comment]
@Liubuntu Just to make sure it doesn't swamp by the bot. The only warning I receieved is the R version update. In order for this package to be applicable to most of the user, I decided to maintain the requred R version to 3.3.1. Is that possible?

**Comment by Liubuntu** [comment]
Hi @zhouzilu , Please do the following `Update R version dependency from 3.3.1 to 3.5.` in `DESCRIPTION` file. Because the newly accepted packages will go to the Bioc 3.7 devel, which is supposed to work interactively with the R version of 3.5 and up. The Bioc versions are bumped in accordance with the R versions. Thanks!

**Comment by mtmorgan** [comment]
Just to clarify -- specifying R 3.5 is highly recommended, but not strictly required.

**Comment by zhouzilu** [comment]
@mtmorgan @Liubuntu  Thank you for clarifying this, Martin and Qian. After talked with other author of this package, we have decide to keep our R version as `R 3.3.1` due to
- Most of the available computing cluster is not `R 3.5`
- This package is built based on `R 3.3.1` environment
- Our downstream analysis will be done in a computer cluster that has `R 3.3.1`

Hope this address your concern. In addition, the related paper for this package is going to be finilized in three days. I wonder if we could accelarate the package review process, such that I could include the Bioconductor link in this paper.

Please let me know if you need any other addtional information to proceed.

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

Here is the initial review of your package. Please seek to fix all of them and bump the version for a new build. A normal technical review will take about 2 weeks to a month (or longer) depending on the responsiveness and package fixes. The reviewers in the core team has other important responsibilities from Bioconductor. But we could try to accelerate the process working together more efficiently. 

## DESCRIPTION
- ok. 
## NAMESPACE

- Please import all the packages used in your `Depends` and `Imports` in `DESCRIPTION` file. See those `no visible global function definition for ...` in your build report?Most of those could go away once you use `@import` or `@importFrom` inside your R scripts.
```
Undefined global functions or variables:
        #CHROM ALT FILTER FORMAT INFO QUAL REF aggregate axis bafs
        colorRampPalette dev.off dnorm dunif grid kmeans legend par pdf pib
        pir plot points read.table sd write.table zs
Consider adding
  importFrom("grDevices", "colorRampPalette", "dev.off", "pdf")
  importFrom("graphics", "axis", "grid", "legend", "par", "plot",
                     "points")
  importFrom("stats", "aggregate", "dnorm", "dunif", "kmeans", "sd"
  importFrom("utils", "read.table", "write.table")
to your NAMESPACE file.
```

## Vignette

- The author, title and dates are duplicated.
- Please add a table of contents for better organization. This could be easily specified in the header. check here: https://rmarkdown.rstudio.com/html_document_format.html

```
---
title: ...
output:
  html_document:
      toc: true
---
```
- you can keep the demo for installing the most current version from github. But please also include demo for how to load the package from Bioconductor in the vignette, as if it is already available from Bioconductor.
- Where is the red box? `This package specifically emphasizes on the steps within the red box.`.
- some figures are too big. Check out here: https://sebastiansauer.github.io/figure_sizing_knitr/ to set figure sizes within rmarkdown.
- Add `sessionInfo()` in the end of vignette for the info of your R environment.
- Multiple typos. E.g., typo in "We will **seperately** shows normalization for WES and SNP array." and "At this step, we should **alreday** have PLR and variants BAF from sequencing, ...". "This is mainly to **accomadate** the fact that ...". You may want to run a spell checker.

## R

Please fix the following first, and a closer check of R scripts might be given later.

- When there are default values for function arguments, please specify them in the `@parameter` documentation.

The following are for a more robust R coding practice:

- use ` <- ` for assignment. E.g., `iCNV_detection = function` to `iCNV_detection <- function()`. Check code inside the functions also.
- Avoid using of `sapply`, use `vapply` instead to be safer. You can also replace it with `lapply` if originally `sapply(simplify=FALSE)`.
- Avoid using of `1:...`, use `seq_len` or `seq_along` instead so that your code won't break for edge cases. E.g., in "iCNV_detection_function.R:L529", `for (j in 1:length(CNVs)){` could be `for (j in seq_len(CNVs)){`. Search your R scripts for similar cases.
- Long lines. E.g., in "iCNV_detection_function.R". Please use new lines and tab for indentation. Use multiples of 4 for indentation.


## others

- This is not required. But consider adding unit tests. We strongly encourage them. See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

Cheers!

**Comment by zhouzilu** [comment]
@Liubuntu Thank you for your comment. I will edit my package accordingly and bump the version once finished.

**Comment by zhouzilu** [comment]
@Liubuntu Hi Qian, I have finished fixing most of the issue you mentioned except the 4 space indent. This seems a little bit trivial... Is it fine just keep it that way? Other than that, it's all finished. Thank you again!

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

Thanks for making those changes to the review. It will surely make your package a better one with more users. I will take another look at your newly modified package and give another review very soon. 

First of all, the indentation thing is not strictly required, but we highly recommend for the good R coding styles. 

Actually, you can use "tab" key in emacs and it will automatically give you correct indentation. Also for longer lines (> 80 characters), you can use "alt+q" to do the automatic reformatting of the line lengths. OR if you are using Rstudio, the indentation could be done automatically when you goes to the next line ("tab" could also be used). 

You can refer to the following sites for coding styles: 
https://www.bioconductor.org/developers/how-to/coding-style/
http://r-pkgs.had.co.nz/style.html

Like Hadley said in his article, "Good style is important because while your code only has one author, it’ll usually have multiple readers." You really should use a consistent style to make it a better and more readable package for a broader users.

Thanks!
Qian

**Comment by zhouzilu** [comment]
Hi @Liubuntu ,these are really great comments! I will be careful with all the details when I developed my second package. Thank you again!

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

Thanks for making your efforts in modifying your package. Here are some additional things to do, but most are just cosmetic. Please bump your version and comment back when you are ready for the final review or with any questions. Thanks!

## NAMESPACE
- you need to import `CODEX` in namespace! Remember to import all packages that are mentioned in `Depends` and `Imports` fields of DESCRIPTION. Or remove any unused ones from DESCRIPTION.

## no visible binding problem. 
There are still this note in build report for `no visible binding for global variable ...`. These comes from the using of `dplyr`. Please use `.data$` before each use of these variable. E.g., rewrite:
```
bambaf_from_vcf.R:    dt <- dt %>% dplyr::filter(QUAL!='.') %>% dplyr::select(-REF,-ALT,-QUAL,-FILTER,-INFO)
```
into:
```
bambaf_from_vcf.R:    dt <- dt %>% dplyr::filter(.data$QUAL!='.') %>% dplyr::select(-.data$REF,-.data$ALT,-.data$QUAL,-.data$FILTER,-.data$INFO)
```
And import `.data` from `rlang`. Remember to add `rlang` into your DESCRIPTION in `Imports` field. This will remove the build check messages:

More information, please check https://community.rstudio.com/t/tidyeval-equivalent-of-mutate/1295/5

build report notes:
```
bam.baf: no visible binding for global variable QUAL
bam.baf: no visible binding for global variable REF
bam.baf: no visible binding for global variable ALT
bam.baf: no visible binding for global variable FILTER
bam.baf: no visible binding for global variable INFO
bam.baf: no visible binding for global variable FORMAT
bambaf_from_vcf : <anonymous>: no visible binding for global variable
  #CHROM
```
Search through your source code for all these cases. These are the recommended way for doing it correctly. Try your best, and comment back for any question.

## R scripts
- Since the argument of `dir`, `pattern` and `projectname` are character strings as said in your parameter documentation, it is recommended to write:
``` get_array_intput <- function(dir,pattern,chr=NULL,projectname='')```
        as:

```
get_array_intput <- function(dir=character(),pattern=character(),chr=NULL,projectname=character())
```
and it will do the automatic check for your input and return error if the input is not in character. You can also use `integer()` or `numeric()` for integer or numeric arguments. Search and correct for other similar cases.

## Vignette
- looks much better now! Thanks!

Cheers!
Qian

**Comment by zhouzilu** [comment]
@Liubuntu Thanks, Qian! I will modify accordingly, bump the version and contact you once finished.

**Comment by zhouzilu** [comment]
@Liubuntu Quick question about auto check for input type in function. Seems like it doesn't work that way. Do you mind send me your reference? I may have made a mistake somewhere. Also, if I have a default value, for example '.', should I use dir = character('.')
Thank you!

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

That was from my misunderstanding and sorry for passing that information without checking the validity. 

But indeed, it's a better practice to give a default value (of the required data type) for function arguments, and also add some checking for input in the beginning of the function. E.g., 
```
foo <- function(x=character(), y=numeric())
{
    stopifnot(is.character(x))
    stopifnot(is.numeric(y))
    message("name: ", x, "\n", "Age: ", y, "\n")
}
```
So that the input value of wrong data type should return an error. 
```
foo("Mei", 23)
## name: Mei
## Age: 23
foo(22, 52)
## Error in foo(22, 52) : is.character(x) is not TRUE
foo("Mei", "a")
## Error in foo("Mei", "a") : is.numeric(y) is not TRUE
```
And also when users types in `args(foo)`, it will return the arguments with default values, which could serve as a reminder for the correct data type. While it's always useful to specify the required data type in the `@param` documentation also. 
```
## function (x = character(), y = numeric())
## NULL
```
This will keep you code robust. You can also add unit tests for these testings and more. We strongly encourage them. See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

For your other question, default values like "." does not need to specify the data type within the argument. But please include it in the `@param` documentation.

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

About the "no visible binding problem" in my previous review, there has been discussions within the Bioconductor core team. There are multiple ways of dealing with it, including adding the pronoun as I commented from Hadley's solution, or using "utils::globalVariables" to mute those note messages (which is not recommended, and could be masking of any inappropriate use of that variable), or just prevent using the pipe syntax (Because the pipe syntax is convenient way for end-users, but not appropriate for lower-level programming). There was not a conclusion yet, but soon some guideline about using the pipe syntax in writing an R package will be added. 

To simplify, since you are already using this pipe syntax in your own package, and it looks tedious to add the pronoun before each call of the data fields. Although the guideline of reviewing Bioconductor packages is to take care of things that are under control, I would say it is OK to leave those note messages unattended. It should be much simpler to address the rest of issues that are only cosmetic. 

Cheers!
Qian

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

Please make effort in addressing the issues in the last review. Read the comments and adjust accordingly. Since most of the needed things are just cosmetic and could be easy to fix.  Bioconductor usually has a 2 weeks rule, and if no reponse (comments / questions / new commits or anything showing your are working to improve your package), the issue will be closed. It was 8 days ago for your last response. So please response within a week so that we can keep this issue open and the package is already very close to acceptance. Thanks!

Best,
Qian

**Comment by zhouzilu** [comment]
Hi @Liubuntu 
Sorry. I was working on my other project. I will work on it during the weekend and push the update.

Thanks,
Zilu

**Comment by zhouzilu** [comment]
@Liubuntu Qian, really quick question. So I understand I need to add CODEX to the NAMESPACE. However, since CODEX is a Bioconductor package, how should I import it? Is it different from other R packages?

Thank you!

**Comment by zhouzilu** [comment]
Hi Qian @Liubuntu ,

I have finished. Please take a look at them.

Thank you again!
Zilu

**Comment by Liubuntu** [comment]
Hi @zhouzilu 

Thanks for making the changes. Last 2 questions: 

- Did you see the previous comment about setting default data type for arguments and checking the validity of argument input? https://github.com/Bioconductor/Contributions/issues/654#issuecomment-371962287 Please make modifications on your argument values and validity checks to have a more robust package? 
- Should the function name of "get_array_intput" be "get_array_input"? or is it intended for a meaning to have "t" there?

Cheers,
Qian

**Comment by zhouzilu** [comment]
Hi Qian @Liubuntu 
Thank you so much for your comment! 
Regarding the first question, now I understand why this is necessary after reading your comments again. I am on it.
About second question, you are absolutely right!

For the data in inst/extdata and data/, they are all important files for vignette and example files. I have to keep it that way.

I will bump the version and reply to you once everything is finished.

Zilu

**Comment by zhouzilu** [comment]
@Liubuntu I have add default parameter type if there isn't any default value (except couple complex list). Please let me know what to do to proceed.

**Comment by Liubuntu** [comment]
Hi @zhouzilu , 

You package is accepted. Thanks for your contribution to Bioconductor and efforts in addressing technical review issues. Wish you success in your future career. 

Cheers!
Qian

**Comment by zhouzilu** [comment]
Hi Qian, @Liubuntu 

Thank you so much! It was nice working with you. Good luck to you, too.

Zilu

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhouzilu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"iCNV\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iCNV

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
