### ISSUE TITLE
ChIC: ChIP-seq quality Control package

### ISSUE THREAD

**Issue by carmencita** [Bioconductor/Contributions#657]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/carmencita/ChIC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by carmencita** [comment]
AdditionalPackage: https://github.com/carmencita/chic.data.git

**Comment by mtmorgan** [comment]
Please update your repository to include the 'man' pages.

**Comment by carmencita** [comment]
@mtmorgan Both packages already contain the "man" pages:
https://github.com/carmencita/CHIC/tree/master/man
https://github.com/carmencita/chic.data/tree/master/man
Or are you referring to something else?

**Comment by mtmorgan** [comment]
Oops sorry don't know how I missed them... I'll have a review for you in the next several days...

**Comment by mtmorgan** [comment]
It looks like there is an accompanying data package required to build this package. Please add a comment following [the instructions][1] for including additional packages.

I don't know what the spp package is; presumably neither CRAN nor Bioconductor. You package must not have dependencies from other repositories.

[1]: https://github.com/Bioconductor/Contributions#submitting-related-packages

**Comment by mtmorgan** [comment]
Can you try adding the AdditionalPackage: line again, after deleting the original, now that the package is in the review process.

**Comment by carmencita** [comment]
AdditionalPackage: https://github.com/carmencita/chic.data.git

**Comment by lshep** [comment]
Please try without the .git at the end

**Comment by carmencita** [comment]
AdditionalPackage: https://github.com/carmencita/chic.data

**Comment by mtmorgan** [comment]
CHIC cannot depend on the non-CRAN / Bioconductor package spp. Will you be able to update your package to remove this dependency? Also, strong consideration should be given to replacing genomeIntervals with [GenomicRanges][1]

[1]: https://bioconductor.org/packages/GenomicRanges

**Comment by carmencita** [comment]
spp will be soon available on CRAN. The package was supposed to be out, but we had some problems with the submission.

**Comment by carmencita** [comment]
spp is now available on CRAN: https://cran.r-project.org/web/packages/spp/index.html

**Comment by mtmorgan** [comment]
spp doesn't install on our system because it tests for installed boost libraries of a particular version. the library headers are not installed, but the check (in spp) seems superfluous, since these are provided by the BH R library via LinkingTo:. This seems to be something that should be resolved in spp...

**Comment by carmencita** [comment]
There is now a new version of spp available.

**Comment by mtmorgan** [comment]
Great, the new build report is available. Looks like there are Windows problems with spp, but let's ignore those for now.

**Comment by carmencita** [comment]
spp has been build for unix-like systems only (OS_type unix). As my package depends on spp should I mark it with the same tag?
Thanks

**Comment by mtmorgan** [comment]
do you mean that spp will never run on Windows? That's too bad (I guess it's the bz2 dependency?). Add a file `.BBSoptions` to the root of your package repository with the single line
```
UnsupportedPlatforms: win
```

**Comment by carmencita** [comment]
Hi @mtmorgan,
thank you for the hint with .BBSoptions.
The package builds now under Linux and Mac. Do I have to "Close" the issue and then the package is available for the users? 

Thank you,
Carmen

**Comment by mtmorgan** [comment]
No, the package needs to be reviewed. This is my responsibility and I will try to do this ASAP.

**Comment by mtmorgan** [comment]
Please address the following review and when ready submit a comment here indicating that you are ready for the review to continue and briefly summarizing how you have updated your package.

General

- please make sure that there are no unintended files in your
  repository, e.g., vignettes/.ChIC_Vignette.Rnw.swp. Use a
  `.gitignore` file in the top level directory to ensure that these
  are not commited in the future.
  
- Either write a meaningful NEWS file that can be parsed by utils::news() or remove this file.

DESCRIPTION

- Provide a more informative Description: field describing what your package does, e.g., the types of QC checks performed and how it compares to other avaialble solutions.

- Use [GenomicRanges][1] rather than genomeIntervals; GenomicRanges is much more mature software.

- Remove the LICENSE.md file; this is not needed in R packages

[1]: https://bioconductor.org/packages/GenomicRanges

vignette

- The vignette needs to actually evaluate your code, rather than include verbatim code chunks; most evaluated code chunks are simply producing plots or reading pre-computed resuls. This may require careful curation of an example data set to meet Biocoductor [space and time guidelines][2].

[2]: http://bioconductor.org/developers/package-guidelines/#correctness

R

- createMetaGeneProfilePlots_ForComparison.R:47 Write more robust functions by validating inputs, e.g.,

    ```
    stopifnot(
        is.character(chrommark), length(chrommark) == 1L, !is.na(chrommark),
        chrommark %in% c(...),
        ...
    )
    ```
    
- Follow the 'Good practice' section of `?data()` when loading data
- Use `message()`, `warning()`, `error()` to communicate with user, rather than `print()`, `cat()`. Note that `message(paste(.))` is usually not necessary.
- Consider a style that is easier to read, with spacing aroud operators `name  paste(...`, e.g., using [formatR][3]
- createMetaGeneProfilePlots\_ForComparison.R:73 Use small helper functions rather than copy-and-paste code chunks to reduce repetition
- Simplify code where possible, e.g., GlobalFunctions.R:603 `TOTAL_reads <- sum(lengths(chip.test))`
- use vectorization rather than iteration wherever possible, e.g., PrivateFunctions.R:72 it looks like you are looking for locations where `deriv` changes sign, e.g., 

    ```
    > set.seed(123)
    > x = rep(rnorm(5), as.integer(runif(5, 2, 4)))
    > c(FALSE, diff(sign(x)) != 0)
    [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
    [13] FALSE
    ```
    
  allowing easy vectorized construction of `field` without using a `for()` loop. Look carefully at your code for other examples of this.
- Use `BiocParallel::bplapply()` rather than `mclapply()` for portability; make sure your code works with `register(SnowParam())` (independent processes).
- The pattern at PrivateFunctions.R:850 allocates an empty vector and then appends to it. This is very inefficient. Instead, identify strategies to vectorize or reduce the number of times a new data frame is constructed, e.g., replacing the `for () {}` loop with `result <- lapply(); do.call(rbind, result)`. Do this throughout your code.

[3]: https://cran.r-project.org/package=formatR

man

- More completely document return values, e.g., from `calculateCrossCorrelation()`
- Work toward _meaningful_ runnable examples on _all_ help pages, e.g., metagenePlotsForComparison.Rd says only `print("possible usage:")` but the important stuff is marked `dontrun{}`. This means that your code is not tested, and will almost certain not work for the user. For instance, the don't run chunk fails, for obvious reasons, if I try to paste it into my R session because `Meta_Result` is not known!
- Always use a temporary file or directory `tempfile()`, `tempdir()` for example or vignette output, so that you do not accidentally overwrite your user's data.

**Comment by carmencita** [comment]
Dear Martin,

thank you for the feedback and the constructive suggestions. 
I would need some more explanations regarding data() and the vignette if possible:

- "Follow the 'Good practice' section of ?data() when loading data"
I though I was already following the good practices when using the following command to load objects into a function environment
"data(compendium_db,package="ChIC.data",envir = environment())"
Does your comment mean I should use instead the following command to access lazy load objects
"ChIC.data::compendium_db"

-"vignette"
Running a complete analysis would need from 2 to 3 hours. Should I really incorporate all commands in chunks as running examples? Do you have any advice on that?

Thank you,
Carmen

**Comment by mtmorgan** [comment]
The ability to specify a dataset by name (without quotes) is a
     convenience: in programming the datasets should be specified by
     character strings (with quotes).

but also

    That need [use of data()] has been
     almost entirely superseded by lazy-loading of datasets.

The vignette should do a real analysis, within the time constraints outlined in package guidelines. Often this means careful choice of a subset of data rather than an analysis of a full data set, although efficiently  written code analyzing a full data set (e.g., in the DESeq2 package) often completes in a timely fashion.

**Comment by carmencita** [comment]
Dear Martin Morgan,

I am ready for the review. I hope all the changes I did are in line with the Bioconductor requirements.

Please note that the vignette contains now evaluated code, as requested. But building the vignette takes a lot of time (a few hours) as it starts from the download of two bam files and executes the entire pipeline. I also load data now with data() using quotes as suggested, but I get the following NOTE from BiocCheck: Consider clarifying how 5 object(s) are initialized. Maybe they are part of a data set loaded with data(), or perhaps part of an object referenced in with() or within().

A short list of other updates I did on the package:
General: removed unintended files, NEWS and  LICENSE.md
DESCRIPTION: added a description of the package

R: 
- cleaned the code by: substituting for() with lapply(); simplified code where possible; created helper functions to reduce repetitions; removed code to use vectorization
- validating inputs for more robust functions
- using message() ecc. Instead of print()
- substituting parallel::mclapply() with BiocParallel::bplapply using BPPARAM = BiocParallel::MulticoreParam(workers=mc) to indicate the number of workers
- substituted genomeIntervals with GenomicRanges 
- Used formatR to tidy up the code

man
- running examples are now provided, but still under dontrun{} as the calculations are really time intensive
- using setwd(tempdir()) to not overwrite users data

Thank you

**Comment by carmencita** [comment]
AdditionalPackage: https://github.com/carmencita/ChIC.data
Name of the package changed

**Comment by carmencita** [comment]
Repository: https://github.com/carmencita/ChIC
My repository name changed

**Comment by mtmorgan** [comment]
Please try to trigger a build fro your  revised package ChIC by incrementing version number to 0.99.8. If a build is not triggered, please trouble-shoot the web hook from your end, following instructions [linked above][1].
[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by fferrari** [comment]
Dear Martin,

Thanks for your detailed feedback.

The package submitted by @carmencita is meant to run a comprehensive quality control analysis on ChIP-seq data. The analysis takes long because it involves several steps, on large genome-wide sequencing datasets.


The examples in the vignette and manual pages are based on real publicly available data. This would be helpful for the users as they can then try the tool on publicly available data and get the exact same results.

The only option to use a subset of data would be, for example, extracting only one chromosome from the input dataset.
However, in  that case the user would be confused because:
1) the analysis is meant to be run on the entire chip-seq sample, not a single chromosome
2) the results in the vignette would not be the same as what could be obtained from the original public dataset


Thus we would propose two strategies, which do not involve getting the users confused:

a) Set "eval=FALSE” for the time consuming calculations in the vignette, but using the pre-computed results object (in ChIC.data package) to plot figures when the vignette is built.
NOTE: we revised the vignette, compared to the previous version you evaluated. The current version (with "eval=TRUE” in almost all chunks) can be built without errors, but it takes a couple of hours

b) Doing the same in the man pages (with dontrun{} for time consuming analyses)
NOTE: the code in the current (fixed) man pages and vignette examples has been revised. All of the "dontrun" code will actually work if it is copied and pasted into the R shell.

**Comment by mtmorgan** [comment]
Evaluated code chunks in the vignette and examples are required -- it is too easy for the code to become invalid, as changes occur in your own code or in code that your package depends on. This is from many years of experience. Several features of your package make it particularly important to have evaluated code chunks. Your package has no formal unit tests, so there is no way to know that the code continues to function. Your package is very ambitious in what it implements, with many intricate dependencies both within the package itself and between the package and its dependencies; this makes it very susceptible to small changes in underlying code, and these changes will not be revealed by unevaluated code chunks.

Vignettes and examples are meant to illustrate use rather than replicate analysis; if you're interested in replicating an actual analysis then consider in addition an experiment data package with a comprehensive vignette, where time and space constraints are more relaxed; it would still be unrealistic to have a vignette requiring 2 hours of processing time.

**Comment by carmencita** [comment]
Dear Martin Morgan,

I am ready for the review. I hope all the changes I did are in line with the Bioconductor requirements.

I am loading data now with data() using quotes as suggested, but I get the following NOTE from BiocCheck: Consider clarifying how 5 object(s) are initialized. Maybe they are part of a data set loaded with data(), or perhaps part of an object referenced in with() or within().

A short list of other updates I did on the package:

General: removed unintended files, NEWS and LICENSE.md
DESCRIPTION: added a description of the package

R:
- cleaned the code by: substituting for() with lapply(); simplified code where possible; created helper functions to reduce repetitions; removed code to use vectorization
- validating inputs for more robust functions
- using message() ecc. Instead of print()
- substituting parallel::mclapply() with BiocParallel::bplapply using BPPARAM = BiocParallel::MulticoreParam(workers=mc) to indicate the number of workers
- substituted genomeIntervals with GenomicRanges
- Used formatR to tidy up the code

man
-running examples are now provided, but still under dontrun{} as the calculations are really time intensive
using setwd(tempdir()) to not overwrite users data

Thank you

**Comment by fferrari** [comment]
The latest [build report](http://bioconductor.org/spb_reports/ChIC_buildreport_20180406104225.html) does not show any result on linux. Looks like it didn't even try to compile.

Any maintenance going on on Bioconductor servers?

**Comment by mtmorgan** [comment]
Thanks, please address NOTEs like this
```
NOTE
f_t.get.gene.av.density_TES : <anonymous>: warning in
  f_feature.bin.averages(tl_current$td[[chr]], data.frame(x =
  gdl[[chr]]$txEnd[!nsi]), m = m, nbins = nbins, nu.point.omit =
  FALSE): partial argument match of 'm' to 'min.feature.size'
```
by using full argument names. I'll then mark your package as accepted.

**Comment by carmencita** [comment]
Dear Martin Morgan,
I resubmitted the revised version of my package.
Thank you,
Carmen

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carmencita.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ChIC\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ChIC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carmencita.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ChIC.data\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ChIC.data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
