### ISSUE TITLE
slinky

### ISSUE THREAD

**Issue by erikor** [Bioconductor/Contributions#660]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/VanAndelInstitute/slinky

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
vobencha will review your package.

Probably you want to aim for the more modern [SummarizedExperiment][1] rather than ExpressionSet.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by erikor** [comment]
@mtmorgan Ah yes, good point.  I will make that change along with any others recommended by the reviewer.

**Comment by vobencha** [comment]
Sorry for the delay in review - I'll get to this today or tomorrow.
Valerie

**Comment by vobencha** [comment]
Hi,

I've done a first review. Overall I don't feel the vignette does a compelling job in convincing the user the Slinky class is value added when analyzing L1000 data. There are many methods in R/Bioconductor avaialble to read in data efficiently and stat methods that can operate of these data. I've tried to highlight these points and suggest possible improvements in the comments below.

1) SummarizedExperiment and HDF5 back-end
Thanks for converting to SummarizedExperiment from ExpressionSet. You might be able to also leverage the HDF5Array back-end for SummarizedExperiment Herve recently developed:

  https://www.bioconductor.org/packages/release/bioc/html/HDF5Array.html

  This implementation would useful (I think) if you returned a SummarizedExperiment from some of your functions. More on this in (8) below.

2) Reference Class
Why do you feel the Slinky class needs to be a reference class instead of S4? How do reference class semantics benefit the user in this case?

3) Vignette Background
I think the background should more clearly state what the slinky package offers. How does the single slinky class make accessing and analyzing this data easier? Maybe mention right up front the methods offered in the class and why they are important or not available from other sources? Does using the Slinky class really make analyzing these data more efficient when we already have things like DelayedArray or HDF5Array back-ends?

    This sentence mentions a slinky library ...
```
"Alternatively, you can use the slinky library itself to fetch this file. Again, this will take a while and may fail if your connection is not rock solid."
```
Please explain. Do you mean a third party library from the command line, i.e., not from R or?

4) Vignette 'References' section
This section is blank. Please remove or add references.

5) DESCRIPTION
The Description field in the DESCRIPTION file says:
```
"Wrappers to clue.io REST API as well as ..."
```

  I don't see an explanation of what clue.io is in the vignette or the man page ... did I miss this? How does it relate to the LINCS L1000 data?

6) References to ExpressionSet
It looks like there are some leftover 'eset' variables. You may want to change these since you're now using SummarizedExperiment:

```
~/slinky >grep -R eset *
tests/testthat/test.R:  eset <- sl$toSummarizedExperiment(index = list(1:978, 1:10),
tests/testthat/test.R:  expect_equal(eset$inst_id[1],  "CPC020_MCF7_24H_X1_F1B4_DUO52HI53LO:P17")
tests/testthat/test.R:  expect_true(all.equal(SummarizedExperiment::assays(eset)[[1]][5,10], 
tests/testthat/test.R:  expect_equal(as.numeric(nrow(eset)),  978)
tests/testthat/test.R:  expect_equal(as.numeric(ncol(eset)),  10)
tests/testthat/test.R:  eset <- sl$toSummarizedExperiment(where_clause = where_clause)
tests/testthat/test.R:  expect_equal(eset$inst_id[1],  "CPC020_MCF7_24H_X1_F1B4_DUO52HI53LO:P17")
tests/testthat/test.R:  expect_equal(as.numeric(nrow(eset)),  978)
tests/testthat/test.R:  expect_equal(as.numeric(ncol(eset)),  5)
tests/testthat/test.R:  eset <- sl$toSummarizedExperiment(where_clause = where_clause,
tests/testthat/test.R:  expect_equal(eset$inst_id[1],  "CPC020_MCF7_24H_X1_F1B4_DUO52HI53LO:P17")
tests/testthat/test.R:  expect_equal(as.numeric(nrow(eset)),  978)
tests/testthat/test.R:  expect_equal(as.numeric(ncol(eset)),  64)
tests/testthat/test.R:eset <- sl$toSummarizedExperiment(index = list(1:978, 1:10),
tests/testthat/test.R:  tt <- sl$chDir(eset[, 1:4], eset[, 5:10])
tests/testthat/test.R:  tt <- sl$chDir(SummarizedExperiment::assays(eset)[[1]][, 1:4],
tests/testthat/test.R:                 SummarizedExperiment::assays(eset)[[1]][, 5:10])
vignettes/LINCS-analysis.Rmd:amox_gold_eset <- sl$toSummarizedExperiment(index = list( NULL, ix))
vignettes/LINCS-analysis.Rmd:amox_gold_eset <- sl$toSummarizedExperiment(ids = amox_gold)
vignettes/LINCS-analysis.Rmd:amox_gold_eset <- sl$toSummarizedExperiment(
vignettes/LINCS-analysis.Rmd:fda_gold_eset <- sl$toSummarizedExperiment(ids = fda_pert, controls = TRUE)
vignettes/LINCS-analysis.Rmd:eset <- sl$toSummarizedExperiment(index = list(seq_len(978), seq_len(131)))
vignettes/LINCS-analysis.Rmd:ts <- Rtsne(t(SummarizedExperiment::assays(eset)[[1]]), perplexity = 10)
vignettes/LINCS-analysis.Rmd:                        treatment = eset$pert_iname,
vignettes/LINCS-analysis.Rmd:                        plate = eset$rna_plate)
```
7) Function Names
For exported functions, please avoid using the dot '.'. This indicates S3 dispatch. Use underscores or camelCase instead. (I don't mean functions that are preceded with dot, just those with a dot in the middle, e.g., clue.count, clue.instances etc.)

8) Return Values
Why not return a SummarizedExperiment from functions such as readGCTX(), ks(), rzs()? The SummarizedExperiment class holds both data and the associated metadata. The case could be made that the return value would benefit from this additional information vs a bare matrix, especially if this is an endpoint of an analysis. 

    This recommendation is probably most relevant for functions that can return a large amount of data. In those cases, it seems returning a SummarizedExperiment with the HDF5Array back-end would be worthwhile.

Let me know if you have questions.
Thanks.
Valerie

**Comment by vobencha** [comment]
Are you planning to submit a new version? The deadline for packages to be included in BioC 3.7 is April 16:
https://www.bioconductor.org/developers/release-schedule/

**Comment by erikor** [comment]
I am, although I am not sure if I will meet the deadline. On clinical service this week.

**Comment by vobencha** [comment]
That's fine. 

We're starting a new policy of '2 week notice'. If we don't get a new version in 2 weeks (which is April 25) I'll close this issue. You can reopen it anytime when you're ready with a new version. This helps us with bookkeeping on our end.

**Comment by vobencha** [comment]
Hi,
The new material in the vignette looks good - thanks for adding it. Yes, please go ahead with other changes. Addressing issues 1 and 7 (actually think this was 8) are up to you, issue 2 is more more important.
Thanks.
Valerie

**Comment by erikor** [comment]
@vobencha In the latest commit, I have refactored the package using the S4 model rather than RC, and updated the Vignette accordingly.  What do you think?

BiocCheck gives me the following warning:
Import stats, utils in DESCRIPTION as well as NAMESPACE." 

Stats and utils are not actually imported in my DESCRIPTION (I presume they are default imports), and if I remove the importFrom directives involving stats and utils, then R CMD CHECK gives warnings.  Can I ignore this, or is there a solution?

Thanks!

**Comment by erikor** [comment]
I am not sure how to interpret this:
```
* Checking coding practice...
Warning in res[i] <- withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),  :
  number of items to replace is not a multiple of replacement length
Warning in res[i] <- withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),  :
  number of items to replace is not a multiple of replacement length
```
And I am not sure how to fix this:
```
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import stats, utils in DESCRIPTION as well as NAMESPACE.
```
As I noted above, there is no import of those in the DESCRIPTION, and if I remove the imports from NAMESPACE I get R CHECK errors.

Any guidance?  Thank you!

**Comment by vobencha** [comment]
You are selectively importing from stats and utils in NAMESPACE that means they need to be in the 'Imports' field in DESCRIPTION.

My guess is that the "withCallingHandlers" warning is coming from knitr and is related to incorrect specification of your bash code chunk:
```{r, engine = 'bash', eval=FALSE}
aria2c -x 8 -s 8 https://goo.gl/3TigFI
gzip -d *.gz
```
I'm not a knitr expert and don't have a clean solution but changing this to an R code chunk with comments explaining these are shell commands will probably fix this. You could ask for input on the mailing list - maybe someone else knows how to properly handle these with knitr.

Please also fix this:
```
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'diffexp':
\S4method{diffexp}{Slinky}
  Code: function(x, treat, control = "auto", method = "cd",
                 split_by_plate = FALSE, where_clause = list(), gold =
                 TRUE, inferred = TRUE, verbose = FALSE, ...)
  Docs: function(x, treat, control = "auto", method = "cd",
                 split_by_plate = TRUE, where_clause = list(), gold =
                 TRUE, inferred = TRUE, verbose = FALSE, ...)
  Mismatches in argument default values:
    Name: 'split_by_plate' Code: FALSE Docs: TRUE
```

**Comment by erikor** [comment]
OHHHH, I thought it was describing the error, not telling me what to do to fix it.  Now that makes total sense.  Will fix and push.

**Comment by erikor** [comment]
@vobencha it looks like the only issue at the moment is that CHECK takes more than 5 minutes on the Windows box.  Is it essential to resolve that?  (The package completes R CMD CHECK in 4 minutes on my Windows box, but obviously there is variation depending on hardware, load etc.)

**Comment by vobencha** [comment]
@lshep We have a 'warning' in the SPB report for Windows but I'm not seeing the warning flagged in the check output. Both `R CMD check` and `BiocCheck` count zero warnings at the bottom. Is this warning due to the time (> 5 min) like @erikor thought or am I missing something else?

@erikor please tidy up this SPB Note:
```
* Checking exported objects have runnable examples...
    * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      diffexp.Rd, rownames.Rd, rzs.Rd
```

**Comment by lshep** [comment]
Yes that is the reason for the check. I'll investigate why the message Doesn't appear in the long output. But it states it in the summary section.

**Comment by vobencha** [comment]
Thanks @lshep .

@erikor 
Can you please fix the SPB note and bump the version? The check time is just over 5 minutes so that is not a problem.

**Comment by erikor** [comment]
@vobencha done.  thanks!

**Comment by erikor** [comment]
@vobencha great news!  Thank you very much for your assistance.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/erikor.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"slinky\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/slinky

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
