### ISSUE TITLE
Multi-dataset model-based differential expression proteomics analysis pipeline

### ISSUE THREAD

**Issue by yuliya8k** [Bioconductor/Contributions#665]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yuliya8k/MultiMat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package looks incomplete, for instance the Description: field of the DESCRIPTION file does not summarize the package. Your package should provide an interface that works with established Bioconductor proteomics classes. This facilitates interoperability and code re-use.

**Comment by Liubuntu** [comment]
Hi @yuliya8k , 

Please check your build report carefully and modify accordingly to remove all ERROR and most warning messages. Comment back here when you are ready for the technical review or having any questions. 

Cheers!
Qian

**Comment by yuliya8k** [comment]
Hi Qian,
I made the necessary changes and update the repository on GitHub. I added the webhook which is currently saying "OK starting build". 
Possible to confirm that you received a resubmission? 
Thank you,
Yuliya

**Comment by Liubuntu** [comment]
Hi @yuliya8k , 

Seem that your link is not correctly in the initial comment: ```Repository: https://github.com/yuliya8k/MultiMat/e```. 

Please correct it by removing the "/e" in the end and bump the version again. You will see the automatic build messages in this issue if all correct. 

Let me know for any question. 

Qian

**Comment by yuliya8k** [comment]
Hi Quan, 
I changed the URL, I have a question about the version is that only possible to bump the version via the DESCRIPTION file and a new commit? Thanks! And my apologies for the typo, not sure how I managed that..

**Comment by yuliya8k** [comment]
One more question, Bioconductor is using R version 3.5, this version is not available for High Sierra Mac OS even as an unstable development version. This part gets a WARNING which I cannot address. Should I change the version just prior to pushing to GitHub to solve this issue?
Thanks again!

**Comment by Liubuntu** [comment]
Hi @yuliya8k , 

Sorry for missing your questions. Yes, just bump the version inside the DESCRIPTION file. The building machine will detect it and do the automatic building. 

- R version: Because the newly accepted packages will go to the Bioc 3.7 devel, which is supposed to work interactively with the R version of 3.5 and up. The Bioc versions are bumped in accordance with the R versions. However, it is not strictly required. 

- error message:
```
ERROR: Maintainer must subscribe to the bioc-devel mailing list.
Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

Please check if your subscription is successful. Usually there will be an email sent for confirmation. Please check you spam folder for any of these email to confirm the registration. Thanks!

Best,
Qian

**Comment by yuliya8k** [comment]
Hi Quan, thank you for your response! 
I have confirmed my email with bioc-devel. I should definitely be subscribed! 
Can you please let me know if there are any other issues? 
Many thanks,
Yuliya

**Comment by Liubuntu** [comment]
Hi, 

One possibility is that you have subscribed with another email which is different from the email address in DESCRIPTION file. Go to this link: https://stat.ethz.ch/mailman/listinfo/bioc-devel and "Bioc-devel Subscribers" section, put your email address (in you DESCRIPTION file) and password to see if you can see the subscribers list. Let me know for any question, thanks!

Qian

**Comment by yuliya8k** [comment]
Hi Quan, 
so I am still not signed up? 
I am able to log in to the Bioconductor support page, here is what I see:
User: yuliya.k
Last seen:
17 seconds ago
Joined:
4 weeks, 1 day ago
Email:
yuliya.k@gmail.com

Which is the email provided in DESCRIPTION file. 
The username is different from the one I have on GitHub, I think that should not matter, right? 

When this is worked out, do I need to do another commit with a bumped version? 
Thank you!

**Comment by Liubuntu** [comment]
Hi @yuliya8k ,

The support site is different from the bioc-devel mailing list.   
```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    Maintainer is registered at support site.
```
you building log shows that you are successfully registered at the support site, but not for the bioc-devel mailing list. Please Go to this link: https://stat.ethz.ch/mailman/listinfo/bioc-devel and "Bioc-devel Subscribers" section, put your email address (in you DESCRIPTION file) and password to see if you can see the subscribers list. If not, at the same page, please register with your email address provided in the DESCRIPTION file. If it is successful, you should be able to receive emails from the bioc-devel mailing list. This mailing list is for Bioconductor users to ask questions and share with the Bioconductor community. 

Please let me know for further question. When done, please bump the version again for a new build, so that the error could be removed. Thanks!

Best,
Qian

**Comment by yuliya8k** [comment]
Oh, my apologies, I finally registered on the right site! Address confirmed! 
Many thanks for your assistance Qian!

**Comment by Liubuntu** [comment]
So you need to bump the version in DESCRIPTION for a new build without error. So that we can initiate the technical review. Thanks!

**Comment by Liubuntu** [comment]
Hi @yuliya8k , 

Sorry for the delay in the package review. An initial technical review will be given shortly. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @yuliya8k , 

Thank you for your contribution to Bioconductor. Here is the initial review of your package. Please seek to address most of them and comment back with when finished and ready for a 2nd review OR with any questions. Thanks! 

Best,
Qian 

## DESCRIPTION
- Looks good.

## NAMESPACE
- No issue.

## Vignette

- add a table of contents for your vignette. (https://rmarkdown.rstudio.com/html_document_format.html) Use descriptive section names to organize your vignette. E.g., Introduction, Installation, Pipeline, EigenMS normalization... SessionInfo.
- Add section of `Introduction` to introduce briefly about the package usage, and the structure of your vignette.
- Add section of `Installation` and show users how to download and library this package as if it is already available in Bioconductor. E.g.,
```                                                                                                                                                                                                                                                          
BiocInstaller::biocLite("MultiMat")                                                                                                                                                                                                                          
```                                                                                                                                                                                                                                                          
You can also add a subsection to show to users how to use the development version on github. E.g.,
```                                                                                                                                                                                                                                                          
devtools::install_github("yuliya8k/MultiMat")                                                                                                                                                                                                                
```                                                                                                                                                                                                                                                          
- Consider adding a flowchart to represent your analysis pipeline.
- add SessionInfo() in the end.
  
- Add more descriptive words in each section. The code trunks are occupying large proportion of your vignette with poor descriptions. Consider moving some descriptive words inside the code trunks outside, and break the big code trunks to be smaller sec\
tions.

- Consider enlarge the figures inside the vignette for a better illustration using options of "fig.height, fig.width" e.g., `{r Fig2, echo=FALSE, fig.height=5, fig.width=5...}`

## R

- biocViews terms suggestion:
```                                                                                                                                                                                                                                                          
* Checking for recommended biocViews...                                                                                                                                                                                                                      
* NOTE: Consider adding these automatically suggested biocViews:                                                                                                                                                                                             
  DifferentialExpression                                                                                                                                                                                                                                     
```                                                                                                                                                                                                                                                          

- coding practice
```                                                                                                                                                                                                                                                          
* NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:                                                                                                                                                                                            
 EigenMS.R (line 360, column 13)                                                                                                                                                                                                                             
 MBImpute.R (line 350, column 21)                                                                                                                                                                                                                            
 peptideLevel_DE.R (line 432, column 22)                                                                                                                                                                                                                     
 peptideLevel_DE.R (line 460, column 22)                                                                                                                                                                                                                     
```                                                                                                                                                                                                                                                          
- use ` <- ` for assignment instead of `=`.
- remove unused commented codes except for those succinct ones for description of major steps. Those about reference papers could be added to the function documentation in `Details` or `Description`.
- Suggestion which is nor forced: It is always a better practice to name un-exported function starting with ".". E.g., `.some_utility_function <- function(...)` and call these utility function inside exported fuctions.


## man
- No issue.

## general
- there are multiple typos in your documentation. You may consider running a spell check for your package.

**Comment by yuliya8k** [comment]
Hi Quan,
my apologies for the delay, Gmail was incorrectly placing messages from
Bioconductor team into spam. I have addressed this issue and should be
receiving your emails in my Inbox now.

In addition, I have addressed the issues raised in the review and
committed the changes to GitHub. Could I please ask you to review the
changes?

Thank you, and again, my apologies for the delay.

Yuliya

**Comment by yuliya8k** [comment]
Hi Qian,
I am following up on my earlier email, I have gotten the package to produce
no errors and currently have one warning about exceeding 5 min., I am not
sure what I can do about the warning as that may depend on the load of
the computers.

Could you please let me know on the status of my package and if it still i*n
the running of becoming America's next top model*? If that TV show still
exists...
I am hoping I did not miss a chance of getting the correction in for it to
be approved.

Thank you,
Yuliya
