### ISSUE TITLE
gCrisprTools

### ISSUE THREAD

**Issue by OscarBrock** [Bioconductor/Contributions#67]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/OscarBrock/gCrisprTools

Confirm the following by editing each check box to '[x]'

- [ X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X ] The 'devel' branch for new packages and features.
- [ X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by OscarBrock** [comment]
It looks to me like something might be going on with the windows host? I got a check error on that host that I tried to work around, but it doesn't seem to have fixed things. 

The error seems to suggest that I'm not able to load the org.Mm.eg.db library on that host, and unfortunately I don't have access to a windows machine to troubleshoot this issue. Can anyone suggest a fix? The code that is causing the error is:

        org.pkg <- "org.Mm.eg.db"
      if (!requireNamespace(org.pkg)) {
        stop(org.pkg, " bioconductor package required for this species query")
      }


Thanks,

-Russ

**Comment by dtenenba** [comment]
`org.Mm.eg.db` just happens to be loaded on the Mac and Linux build machines but it's not loaded on windows because you have not specified that it needs to be in the `DESCRIPTION` file. The package should be in the `Imports`, `Depends`, or `Suggests` field of that file (perhaps `Suggests`, since you are using the package in an example).

**Comment by OscarBrock** [comment]
Ah, thanks so much. Updating now. 
-R

**Comment by OscarBrock** [comment]
Hi, just wanted to be sure that everything is proceeding properly at this point- it's my first submission to Bioc. 

I'm catching a warning in check for uncompressed data, which I think is unavoidable on my end for an unbuilt package... if I need to be doing something else, please let me know. 

-R

**Comment by OscarBrock** [comment]
Thanks!

Sorry, forgot the version bump. As I say, I'm new to this.

-R

**Comment by lshep** [comment]
Thank you for your submission.  Below are some suggestions and comments. 


GENERAL:
In general we like the built package tar to be under 4M.  Have you compressed your data included in the package when saving it? (i.e  save(object, file=filename, compress=TRUE))


NAMESPACE: 
Please consider adding the imports suggested from the build report to fix the no visible global function definition notes. 
Consider adding
  importFrom("grDevices", "colorRampPalette", "rgb")
  importFrom("graphics", "abline", "axis", "barplot", "layout", "legend",
             "lines", "mtext", "par", "plot", "points", "polygon",
             "segments")
  importFrom("stats", "density", "lm", "median", "na.omit", "p.adjust",
             "pbeta", "phyper", "predict", "pt", "smooth.spline")
  importFrom("utils", "capture.output", "getFromNamespace")

Also consider fixing the no visible binding for global variables.  See `?globalVariables` in an R session



R CODE: 
You should not need "::" .  These librarys are listed in the DESCRIPTION depends and are imported so there is no need for the "::" , you can call the functions directly. 


MAN: 
1. In examples, please use library(packageName) rather than packageName::function().  If you did a library call than there is no need for the "::" 
2.  For Internal use only functions please add \keyword{internal} to the man page.
3. Considering make links to the package functions including those from other packages when describing or referencing. An example, the item description for lib.size in ct.normalizeNTC.Rd, has `\code{edgeR::calcNormFactors}`, consider changing to `\link[edgeR::calcNormFactors]{calcNormFactors}`.  



VIGNETTE: 
gCrisprTools_Vignette.Rmd
1. Please add a table of contents
2. There is a type on section 1.1  Ass = As
3.  Please remove "::", you shouldn't need these since you have the library calls. 
4. Please add an installation section 
```
source("https://bioconductor.org/biocLite.R")
biocLite("gCrisprTools")
```


DOCUMENTATION/VIGNETTE:
Generally vignettes are the documentation type in the vignette directory.  
The gCrisprTools_package_design.pptx  should probably be moved into inst/ directory (perhaps inst/scripts) as well as Mageck_&_gCrisprTools.html. Could you make your Crispr_example_workflow.R a vignette too? Else it should also be moved to the inst directory.  Also for the workflow.R, again you should remove the "::" as the functions will be available after the library(package) invocation.


Cheers, 
Lori

**Comment by OscarBrock** [comment]
Thanks very much for your helpful and timely comments. Please see the newer
version in the repository.

-R

**Comment by OscarBrock** [comment]
In case it wasn't clear, I'm still catching an error on the windows machine. Please let me know if there is something I can do on my end to help with that.

**Comment by lshep** [comment]
Hello, 

As far as the windows ERROR:  It seems like it is failing in the example in the man page for ct.generateResults .  Does the code use any C code? It might be a bug there.  If not, there may also be an issue with time out.  It looks like the example (as well as some of the other examples) take a fairly long time to run.  Is there any way to speed these up? See the elapsed time from the [previous build ](http://bioconductor.org/spb_reports/gCrisprTools_buildreport_20160727100931.html) that ran. 

Thank you for making the other changes.  
For the vignette Crispr_example_workflow.Rmd,  Please remove "::" and call the functions directly.

**Comment by lshep** [comment]
We are working on this new error to try to figure out why it is occurring.

**Comment by OscarBrock** [comment]
Ah, I didn't realize that there was a timeoput. That function takes a
little while to finish, I will modify the example code (and vignette) for
the next commit.

-R

**Comment by OscarBrock** [comment]
Hello, I just wanted to check in on the progress with this. I think that
the warnings are not avoidable, as they refer to resaving data during
package build (which happens on your end).

Thanks in advance,

-R

**Comment by dtenenba** [comment]
They are avoidable. Run 

    R CMD build --resave-data gCrisprTools

This will create a tarball that has the data files compressed as small as possible. Untar this file and copy the data files in it over the ones in your git working copy, then recommit those, with a version bump.

**Comment by OscarBrock** [comment]
Hi, tried to make the specified update but now the build results are listed
as ERROR, WARNINGS- the warnings appear to refer to notes and
recommendations, and the ERROR doesn't seem to have any explanation. Could
you suggest what else I need to do here?

-R

**Comment by OscarBrock** [comment]
Hi, wanted to ping about this again- hopefully things are moving forward?

-R

**Comment by lshep** [comment]
Thank you for your recent updates. Please see the following comments: 

GENERAL: 
1. Was the build directory created automatically or can this be deleted?
2. Please delete the legacy DESCRIPTION~ 

FROM REPORT: 
1. Please update the R dependency to 3.3 
2. It seems you have added invalid biocViews: Crispr, PooledScreesn.  Were you attempting to add biocViews or were you using them as keywords? Invalid biocViews are not allowed. 
   
MAN: 
1. (ct.alignmentChart,  ct. generateResults, ct.guide.CDF, ct.prepareAnnotation) It seems in several man pages you reference ExpressionPlot and functions like ep.alignment.class.counts or ep.load.annot.   Where are these from?  There is no package reference to know where these came from. 
2.  ct.gRNARankByRepliate : where is calcNormFactors from?  Can you add more details in the description or a reference link for the argument lib.size on what is voom-appropriate library size adjustments? 
3.  ct.normalizeGuide :  consider adding a \seealso{ }  section with the mentioned normalization functions. 

VIGNETTE: 
Crispr_example_workflow.R 

1. Please remove  "::"  shouldn't need these because of the library calls.  
2. ct.GCbias(es, ann, sk)  cannot be run.  It looks like this function was never exported in the NAMESPACE 

gCrisprTools_Vignette.R 
1.  Section 5.1.  Can you add more description on what RRAaggregation is?  In the man pages you also reference RRAa but don't go into any detail on the algorithm or where it came from.  

Thank you for your time and effort.  I think with these modifications the package will be close to acceptance.

**Comment by OscarBrock** [comment]
Hi Lori,

Thanks for your continued help with this.

Yes, I was hoping to add some new biocViews. I asked around the department
about the right way to submit suggestions, and the R gurus recommended that
I do it this way; if there is a better way for me to suggest new biocViews
I'm happy to use whatever approach you recommend.

All of your comments are clear and reasonable. I'll clarify the source of
those functions as you suggest, and improve the documentation of RRAa in
the vignette specifically; I agree that it is hard to track down a clear
explanation in the various ancillary documents and man pages. The
Expression Plot mentions are included in error- they refer to an internal R
package that is used at our institution, but isn't available to most Bioc
users. I'll go through again and purge the remainder of these references.

Best,

-R

**Comment by lshep** [comment]
Where were you thinking the two terms should be located?: see [biocViews](http://bioconductor.org/packages/devel/BiocViews.html#___Software)

**Comment by OscarBrock** [comment]
Most likely in the Technology tree, perhaps with Pooled Screens on the
Sequencing branch.

-R

**Comment by lshep** [comment]
We have added the new biocViews: CRISPR and PooledScreens.  They will become available after our next build (~48 hrs).  Please be aware they are case sensitive to adjust if necessary.

**Comment by OscarBrock** [comment]
Hi, still catching that error on the windows machine (I'm emailing because
I'm not sure if you hear about builds that fail). Hopefully everything else
is shipshape now...

-R

**Comment by lshep** [comment]
Thank you for making these changes. The package looks okay now and I will recommend be accepted. You should get svn instructions via email in the next couple of days.

**Comment by OscarBrock** [comment]
Excellent! Thanks so much for your careful work and patience.

-R

**Comment by OscarBrock** [comment]
Hi Lori,

I wanted to follow up on next steps for submitting the package to the svn...

Thanks,

-R

**Comment by lshep** [comment]
Sorry for the delay you should be receiving instructions soon.
