### ISSUE TITLE
hpAnnot

### ISSUE THREAD

**Issue by martahidalgo** [Bioconductor/Contributions#671]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/babelomics/hpAnnot

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
AdditionalPackage: https://github.com/babelomics/hipathia

**Comment by mtmorgan** [comment]
I believe that we are back on track here -- commits to either hipathia or hpAnnot should trigger new builds.

**Comment by martahidalgo** [comment]
Hi,
hpAnnot is the annotation package for hipathia. I opened issue #690 because I’ve been told so, since #613 was in theory closed and hpAnnot was building without errors on all platforms.

However, it is my understanding that hpAnnot should be in AnnotationHub for hipathia to work. I guess that until hpAnnot is accepted, new builds of hipathia will continue to return an ERROR, isn’t it?

On the other hand, I made a commit to hipathia, and the build was triggered and posted by Issue #613, which is closed, and not by this one. Is that as it should be?

Thank you,

Marta

________________________________
De: Martin Morgan <notifications@github.com>
Enviado: Wednesday, March 28, 2018 5:38:19 PM
Para: Bioconductor/Contributions
Cc: Marta R. Hidalgo; Mention
Asunto: Re: [Bioconductor/Contributions] hpAnnot (#671)


I believe that we are back on track here -- commits to either hipathia or hpAnnot should trigger new builds.

**Comment by mtmorgan** [comment]
The intended order of event was

1. open issue with hpAnnota
2. iterate on changes to hpAnnota until building successfully
3. in the same issue, add AdditionalPackage: hipathia
4. iterate on changes to hipathia; it  will 'find' hpAnnota because it is in the same issue.

I made a change on our side so that the next build of hipathia should build to this issue. Can you please try one more version bump on hipathia?

**Comment by martahidalgo** [comment]
Done, now it builds on this issue.
Thanks

________________________________
De: Martin Morgan <notifications@github.com>
Enviado: Thursday, March 29, 2018 5:52:51 PM
Para: Bioconductor/Contributions
Cc: Marta R. Hidalgo; Mention
Asunto: Re: [Bioconductor/Contributions] hpAnnot (#671)


The intended order of event was

  1.  open issue with hpAnnota
  2.  iterate on changes to hpAnnota until building successfully
  3.  in the same issue, add AdditionalPackage: hipathia
  4.  iterate on changes to hipathia; it will 'find' hpAnnota because it is in the same issue.

I made a change on our side so that the next build of hipathia should build to this issue. Can you please try one more version bump on hipathia?

**Comment by mtmorgan** [comment]
Thanks for your patience.

## hpAnnot

DESCRIPTION

- No need for Author: and Maintainer: fields when Authors@R: present.
- Please provide additional Description: so that a user would know how Hipathia can be used; I realize that this is the corresponding annotation package.
- biocViews: for annotation packages should come from the [AnnotationData][1] hierarchy

[1]: http://bioconductor.org/packages/release/BiocViews.html#___AnnotationData

vignettes

- Consider a little more exploration and explanation of the data along with a few brief words of orientation, e.g., 

    ```
    mcols(hp)[, c("title", "description")]
    xtabs(~dataprovider + species, mcols(hp))
    head(hp[["AH60887"]])
    ```
    
## hipathia

DESCRIPTION

- No need for Author: and Maintainer: fields when Authors@R: present.
- Please elaborate on the Description: field, like a package abstract indicating the specific methods implemented and perhaps orienting the user to the types of data the package can be used on and how it compares with other packages with similar functionality.

NEWS

- be sure the NEWS file can be parsed by `utils::news()`.

vignette, man pages, tests

- look great!
- always write to `tempdir()` or `tempfile()` rather than to the current working directory, eg., save.R:36

R

- use `seq_len()` or `seq_along()` instead of `1:n` and similar; this is more robust in user-oriented code, where n can be 0.
- consider `matrixStats::col*()` functions (e.g., `colProds()` rather than `apply(...)` for performance and compact expression.
- use `message()`, `warning()` (e.g., at main.R:179) and `stop()` rather than `cat()` and `print()` when communicating with users.
- `message()` and friends don't generally need `paste0()`, e.g., utils.R:309

    ```
    message("loaded ", length(metageinfo$pathigraphs), " pathways")
    ```

- consider `vapply()` rather than `sapply()` for more robust code.
- use `lengths()` rather than `sapply(x, length)`.
- for readability, avoid highly nested calls in favor of a more procedural style, e.g., 

    ```
    idx <- lengths(last_node_functions) == 0
    last_node_functions[idx] <- NA
    ```

  instead of

    ```
    last_node_functions[sapply(last_node_functions,
                               function(x) length(x)) == 0] <- NA
    ```
- consider a style that allows longer lines, e.g., main.R:134

    ```
                        prob <- summarize_probabilities(
                            genes_vals[list1,, drop = FALSE], summ
                        )
    ```

  utils.R:611 (n.b., the following could use `split()` more effectively)

    ```
    go_labels <- sapply(go_terms, function(term) {
        go_bp_frame[go_bp_frame$name == term, "id"]
    })
    ```

- consider a package-global cache of the AnnotationHub() object, e.g.,

    ```
    hub = local({
        hp = NULL
        function() {
            if (is.null(hp)) {
                hp <<- query(AnnotationHub(), "hpAnnot")
            hp
        }
    })
    ```

  Use this to reduce the cost of hub access with
  
    ```
    ## update original code to use cache
    ## ah <- suppressMessages(AnnotationHub())
    ## hp <- query(ah, "hpAnnot")
    hp <- hub()
    ```

- `which()` is usually redundant, e.g., `x[x < quan_inf] <- quan_inf` at stats.R:109
- vectorize wherever possible, e.g, stats.R:127

    ```
    min <- rowMins(x, na.rm = TRUE)
    max <- rowMaxs(x, na.rm = TRUE)
    x = (x - min) / (max - min)
    ```
    
  utils.R:441
  
    ```
    n <- nchar(snames)
    idx <- n > maxchar
    n[idx] <- maxchar - 3
    paste0(substr(snames, 1, n), ifelse(idx, "...", ""))
    ```

- consider `split()` rather than iteration, e.g., stats.R:557

    ```
    pvals = split(comp[,"FDRp.value"], comp$pathways)
    ```

**Comment by martahidalgo** [comment]
Hi,

Thank you for your exhaustive analysis of the package.

I’ve gone through all the comments except for the “vapply instead of sapply” one. I got no time to do it properly now. If possible, I’ll let that for next release.

However, I’m getting some WARNINGs (size of the package, building time) which I didn’t have before. The size of the package is almost the same as in v0.99.22, and no error appeared. Also, it takes now more than 20 minutes to build in v0.99.32 for Linux, but in v0.99.31 it took only 4 minutes, and the only change between versions is the removal of a data file. Am I missing something?

Thank you in advance,
Marta


________________________________
De: bioc-issue-bot <notifications@github.com>
Enviado: Monday, April 9, 2018 1:14:12 AM
Para: Bioconductor/Contributions
Cc: Marta R. Hidalgo; Mention
Asunto: Re: [Bioconductor/Contributions] hpAnnot (#671)


Dear Package contributor,

This is the automated single package builder at bioconductor.org.

Your package has been built on Linux, Mac, and Windows.

On one or more platforms, the build results were: "skipped, TIMEOUT, WARNINGS".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.

Please see the build report<http://bioconductor.org/spb_reports/hipathia_buildreport_20180408191410.html> for more details.

**Comment by mtmorgan** [comment]
Thanks for your work. A few additional minor changes please

- The warnings about size and time were added to the build system checks on our end. The size of the package is not too large; please ignore this warning. 

- Address these NOTEs by import'ing the relevant functions in the package NAMESPACE.
    ```
    NOTE
    annotate_paths: no visible global function definition for do_call
    do_pca: no visible global function definition for is
    do_wilcoxon: no visible global function definition for is
    heatmap_plot: no visible global function definition for is
    hhead: no visible global function definition for is
    hipathia: no visible global function definition for is
    hipathia: no visible global function definition for DataFrame
    node_color_per_de: no visible global function definition for is
    normalize_data: no visible global function definition for is
    translate_data: no visible global function definition for is
    Undefined global functions or variables:
      DataFrame do_call is
    Consider adding
      importFrom("methods", "is")
    to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
    contains 'methods').
    ```
- try to reduce the run-time of the examples that take the longest, e.g., using only the mouse example on `load_pathways()`.

**Comment by martahidalgo** [comment]
Ok, modifications done.
Thanks for your comments.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/martahidalgo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"hpAnnot\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hpAnnot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/martahidalgo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"hipathia\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hipathia

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by martahidalgo** [comment]
Hi Martin,

With respect to the SSH public key, please note that my user is martahidalgo, but the R package is in github.com/babelomics. Should I still check in https://github.com/martahidalgo.keys ?

Thank you

Marta

________________________________

Marta Hidalgo


________________________________
De: Martin Morgan <notifications@github.com>
Enviado: sábado, 14 de abril de 2018 19:39
Para: Bioconductor/Contributions
Cc: Marta R. Hidalgo; Mention
Asunto: Re: [Bioconductor/Contributions] hpAnnot (#671)


The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/martahidalgo.keys is not empty), then no further steps are required. Otherwise, do the following:

  1.  Add an SSH key to your github account<https://help.github.com/articles/connecting-to-github-with-ssh/>
  2.  Submit your SSH key to Bioconductor<https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform>

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using biocLite(\"hipathia\"). The package 'landing page' will be created at

https://bioconductor.org/packages/hipathia

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment]
Yes, the submission is associated with your user name (martahidalgo); keys were scraped from there when you package was added to the bioc git repository; you should have access using those keys.

**Comment by martahidalgo** [comment]
Perfect, then everything is clear.
Thanks!

________________________________

Marta Hidalgo


________________________________
De: Martin Morgan <notifications@github.com>
Enviado: miércoles, 18 de abril de 2018 17:35
Para: Bioconductor/Contributions
Cc: Marta R. Hidalgo; Mention
Asunto: Re: [Bioconductor/Contributions] hpAnnot (#671)


Yes, the submission is associated with your user name (martahidalgo); keys were scraped from there when you package was added to the bioc git repository; you should have access using those keys.
