### ISSUE TITLE
tissueTreg

### ISSUE THREAD

**Issue by cimbusch** [Bioconductor/Contributions#673]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cimbusch/tissueTreg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your interest in Bioconductor. Please address the following notes: 

**Build Report Notifications:** 
Fix Notes and Warning:
- [ ] Malformed Description field: should contain one or more complete sentences.  It looks like you may have started a newline that it is picking up on. 
- [ ] Add unit tests. This could be as simple as checking if one dataset is downloaded is it what
you expect as far as data type/class. 
- [ ] Dependency/ Namespace. Import the needed packages or package functions in the NAMESPACE with `import()` or `importFrom()`.  Or remove from Description or change location - If these are needed to work with the downloaded datasets they probably should be in suggests of description instead of import. 
```
  * WARNING: Import bsseq, SummarizedExperiment in NAMESPACE as well
      as DESCRIPTION.
```
- [ ] Add a NEWS file in the top directory to keep track of any changes or updates to the package or data. 

**Other Issues**
- [ ] remove tissueTreg.Rproj from the git tree. This will require doing a `git rm` on the file and committing. After the file is removed and committed with the remove, please put *.Rproj in the .gitignore file so that you can have the local copy but that it is not under version control. 
- [ ] Vignette. I suggest changing the name to something meaningful, like the name of your package
so that when a user does vignettes() it would be like vignettes(tissueTreg) instead of vignette(my-vignette)
- [ ] Man: I suggest adding a man page for the package so the user could get information on
the data by  ?tissueTreg

Please ensure that your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is set up; this will ensure a rebuild of the package upon a version bump.  Please address the above issues and comment back here with what has been updated and/or any additional comments for a re-review. 

Cheers.

**Comment by cimbusch** [comment]
Dear lshep,
thanks for reviewing. I have tried to address the issues raised, rebuilding and checking for errors, the webhook is set up. Please let me know if there should be some issue left I might have overlooked.

Cheers,
  Charles

**Comment by lshep** [comment]
If you are sure the webhook is set up correctly, many forget to change the Content type drop-down menu to  application/json -  have you done a version bump in the Description file?

**Comment by lshep** [comment]
Thanks for the update! 

From the build report it is suggested to remove empty sections for the man page
```
* checking Rd files ... NOTE
prepare_Rd: tissueTreg.Rd:15-17: Dropping empty section \details
prepare_Rd: tissueTreg.Rd:21-23: Dropping empty section \references
```

This is minor and not urgent so I will accept the package - please leave the issue open and you will get more information in the next few days. 

Cheers and welcome to Bioconductor.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cimbusch.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"tissueTreg\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tissueTreg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
