### ISSUE TITLE
BioNetStat

### ISSUE THREAD

**Issue by jardimViniciusC** [Bioconductor/Contributions#674]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jardimViniciusC/BioNetStat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by llrs** [comment]
I couldn't find any reference about the methodologies/algorithms/methods implemented to analyze the network analysis in the README or the vignette. What does this package do?

**Comment by jardimViniciusC** [comment]
Hi Ilrs, in fact, I didn't insert any reference about the methodology implemented.
Now I inserted a short abstract and the reference in the README.
Thank you

**Comment by vobencha** [comment]
Sorry for the delay on this. I'll review it tomorrow.
Valerie

**Comment by vobencha** [comment]
Hi,
I've done a first review. Please see comments below and let me know if you have any questions.
1) Remove the DESCRIPTION~ file.

2) Remove date field from DESCRIPTION. It becomes stale. The package will be stamped with a build date when the build system runs R CMD build.

3) man pages
    i) Please consider grouping your man pages by family or topic area. When similar functions appear on the same man page it's easier for the user to discover them.
    ii) Several man pages are incomplete. They all need running examples, a somewhat detailed description of what it does, what type of return value etc.

    For example, the 'JS' man page has this in the value section:

```
\value{
returns the Jensen-Shannon divergence between the corresponding graphs
}
```

    This does not tell us what type of object the value is, the dimension, length etc. Please revisit the man pages to add more detail and running examples.

4) README
i) biocLite() can install both Bioconductor and CRAN packages - you don't need a separate call to install.packages(). Please remove install.packages().

    ii) The links at the bottom of the README should not point to github but to the eventual landing page for the package on the Bioconductor build system.

5) vignette
i) The package should be self contained and the user should not have to go to github for specific functionality. Please remove this line
```
runGitHub("jardimViniciusC/BioNetStat",subdir = "inst/shiny")
```


    ii) Please add a background section to the vignette which includes
        - what type of data this package is intended for
        - what methods are used in the package
        - what does this package do that other R/Bioconductor network packages do not

    iii) I think the vignette would benefit from a Table of Contents

**Comment by jardimViniciusC** [comment]
Thank you @vobencha for review. 
I did almost all modification suggested.
I have only three doubts:
1. I thought that man pages were produced one by function, could you show me an example of how to group the functions in man pages?
2. The links that I excluded from the tutorial (e.g. GitHub links), can I let them without links and when or if the package is accepted, I insert the right links?
3. To commit this changes, I have to update the package version from 0.99.3 to 0.99.4?

**Comment by vobencha** [comment]
1) https://gist.github.com/jefferys/b79fe87314b0dc72fec9
https://stackoverflow.com/questions/15932585/multiple-functions-in-one-rd-file

2) My fault, I misunderstood what you were doing. I didn't realize `runGitHub` was a function from shiny specifically to run shiny apps from GitHub!  I thought you were pointing to information on GitHub that was missing from your package. That isn't the case so it's fine to leave these in the vignette.

3) Yes.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jardimViniciusC.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BioNetStat\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BioNetStat

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
