### ISSUE TITLE
ccfindR

### ISSUE THREAD

**Issue by hjunwoo** [Bioconductor/Contributions#675]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hjunwoo/ccfindR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please re-use the [SingleCellExperiment][1] representation (any matrix-like object can be used for the `assays()`) as the primary way to represent single cell count data to facilitate interoperability and use of your software.

[1]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by LTLA** [comment]
Just seconding @mtmorgan's suggestion. Switching to a _SingleCellExperiment_ class should allow you to avoid having to write getters/setters for the `counts`, `genes` and `cells` slots. You can also store cell-based dimensionality reduction results (`coeff`?) in `reducedDims` slot of the SCE. For the other slots, you'll have to subclass the SCE, but that's no more work than what you're already doing.

**Comment by hjunwoo** [comment]
Thanks @mtmorgan and @LTLA for suggestion. I switched to SingleCellExperiment as suggested. I did have to add extra slots for storing matrices because they have different dimensions and typically there are a lot of them. I considered using metadata slot but then I thought I do need it for real metadata. Hope it is better now.

**Comment by mtmorgan** [comment]
Thanks for your change; I think the version numbering must be 0.99.x (not 0.99-x), and that the next version number should be 0.99.2

**Comment by hjunwoo** [comment]
Thanks, I fixed the version number.

**Comment by LiNk-NY** [comment]
Hi Jun Woo, @hjunwoo 
Thank you for your submission.

Please see the package review below. 
Best regards,
Marcel

---

# ccfindR #675

## DESCRIPTION

* You should only include `Authors@R`. The `Author` and `Maintainer`
fields are not needed.
* No need to include a `Packaged` field.
* Title shouldn't include `R package`. That is understood.

## NAMESPACE

* Looks good.

## R

* Avoid using `1:n` sequence generation, use the more robust `seq_len` or
`seq_along`. 
* Avoid using `sapply` in code
* Separate the plot functionality from the `filter_genes` function
* Remove any default arguments that are files from the `read_10x` and
`write_10x` function definitions.
* Fix typo in `cell_map` documentation
* No need to convert logical to numerical index in most cases,
i.e., `which(ranks(object) == rank)` can just be `ranks(object) == rank`
* Show method repeats class name twice.
* Avoid unnecessary calculations as much as possible:
`h <- t(x); apply(h, 1, f(x) {which(x == max(x))})`
instead do: `apply(x, 2, which.max)`.

Minor:
* No need to use `;`. You can include the code on another line and make
it more readable.
* Use logical evaluation once. For example:
`if (bayes) { do(this) } else { do(that) }`
* `if (x != 0)` is the same as `if (x)`

## vignettes

* remove extra files (.pdf, .R, etc.)
* `eval` is `TRUE` by default

## inst/extdata

* You should put your example data files in this folder (e.g., `barcodes.tsv`)

## NEWS

* Update the NEWS file

**Comment by hjunwoo** [comment]
Hi Marcel, @LiNk-NY 

Thanks for reviewing our package and providing us inputs.  
I revised the package to address the issues. 
Thanks again for your help.

Best regards,
Jun

# DESCRIPTION
* The `Author` and `Maintainer` fields were removed. 
* `Packaged` field was removed. 
* Title was revised (no `R package`).

# R 
* Sequence generations were changed to `seq_len`.
* `sapply` was changed into either `apply` or `vapply`.
* Plot functionality from `filter_genes` was split into a new function `plot_genes`.
* File name arguments of `read_10x` and `write_10x` were removed.
* Typo in cell_map documentation was fixed.
* Now `ranks(object) == rank` is used whenever possible without index conversion.
* Class `show `method was changed to display class name only once.
* Redundant matrix manipulations were removed using `which.max` function.
* Semicolon uses were replaced into multiple lines of code.
* Multiple logicals were simplified, including `if /else` and `if(x!)`.

# Vignettes
* Extra files were removed.
* `eval=TRUE` were removed.

# inst/extdata
* Vignette data files were moved into `inst/extdata`.

# NEWS
* NEWS file was updated.

**Comment by hjunwoo** [comment]
Hi Marcel, @LiNk-NY 

I was unsure about it too; indeed the file names I previously put as defaults are used as such almost always. It would help users if they don't have to type them in every time because `read_10x` is such a workhorse. I put the file name arguments back. 

Thanks again for your help.
Jun

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hjunwoo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ccfindR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ccfindR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by nturaga** [comment]
Please use the following link to [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/). The link listed in the previous message is deprecated.
