### ISSUE TITLE
CytoDx: Robust Prediction of Clinical Outcomes Using Cytometry Data

### ISSUE THREAD

**Issue by hzc363** [Bioconductor/Contributions#676]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hzc363/CytoDx

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi @hzc363 , 

Thanks for your contribution to Bioconductor. Please seek to address all the "ERROR" and "WARNING" messages in the building report. Once it builds successfully, we can initiate the technical review. Let me know for any question. 

Cheers, 
Qian

**Comment by hzc363** [comment]
@Liubuntu 

Hi, one of the warnings I got is "change R dependency from >=3.4 to >= 3.5". The latest R release is 3.44. Why does the system ask for >=3.5?

**Comment by Liubuntu** [comment]
Hi @hzc363 , 

That is because the newly accepted packages will go to the Bioc 3.7 devel, which is supposed to work interactively with the R development version which is 3.5. There are 2 releases each year for Bioconductor in accordance with new releases of R. The Bioconductor version is bumped in accordance with the R versions. Thanks! 

Best,
Qian

**Comment by hzc363** [comment]
@Liubuntu 

I see. Thank you for the explanation!  

 I saw that Bioconductor 3.7 won't be released until Tuesday May 1.  I am planning to submit my manuscript. Will the community be able to access my package in the development version of BioC 3.7 before May 1?  If so, I am worried that the R>=3.5 will give them an error when they try to install the package. 

Zicheng

**Comment by Liubuntu** [comment]
Hi @hzc363 , 

For your question, `Will the community be able to access my package in the development version of BioC 3.7 before May 1?`, the answer is yes. Here is how:

The Bioconductor release version is updated twice each year, and is appropriate for most users. The release version is for stable packages. There is also a development version, to which new packages or existing package with new features are added prior to incorporation in the release. 

So the current release version is Bioconductor 3.6, and current development version is Bioconductor 3.7. The packages accepted between Oct 31, 2017 and May 1st, 2018 will be added to Bioc 3.7. Anyone who want to use these packages will need to use the Bioc 3.7, here is the instruction: https://bioconductor.org/developers/how-to/useDevel/. **Basically, they will need to install the R devel which is R3.5, and then use `library(BiocInstaller); useDevel()` to use the development version of Bioconductor, which is Bioc 3.7.** After May 1st, 2018, the development version becomes new release, which is Bioc 3.7, and a new Development version will be Bioc 3.8. By then, users could install and use your package directly by using the release version of R and Bioconductor. 

Hope this helps. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @hzc363 , 

Thank you for your contribution to Bioconductor. Here are some technical review issues. Please seek to address all / most of them. Comment back when you are finished and ready for a 2nd review OR with any questions. Remember to bump the version when you push changes so that it could do the automatic building. 

## DESCRIPTION

- Imports: `grDevices` and `graphics` are mentioned twice for each.
- Description: not clear enough. Please add more contents about single cell data, clinical outcomes and make it more descriptive and distinguished from other packages.
- Licence: should use one fixed version. e.g., `GPL-2`.

## NAMESPACE
- no issue.

## R

- `CytoDx.fit(x, y, xSample, family, ...)`
  -- Since y is strictly required to have length equal to nrow(x). You can add some check function in the beginning of the script, and fail if it does not. Same with argument `xSample`. E.g,
  ```
  stopifnot(length(y) != nrow(x))
  ```
  -- `family` must be one of the following: "gaussian","binomial","poisson","multinomial","cox","mgaussian"
  You can add these values inside your function arguments, and do the `match.args` for checking. If no input for this argument, the first element would be the default value, in this case, "gaussian". E.g.,
  ```
  CytoDx.fit(..., family = c("gaussian","binomial","poisson","multinomial","cox","mgaussian"), ...) {
      family <- match.arg(family)
  }
  ```
  Check with your other R scripts for similar situations.

- `pRank.R`
  -- check `xSample` for length as above.
  -- remove unused commented code.

- `rank.ub.average.R` and `rank.ub.random.R`
These 2 functions are almost identical. It is recommended to combined these 2 function into 1, and add the argument of `ties.method` to distinguish different methods. E.g.,
```
rank.ub <- function(x, ties.method = c("average", "random")) {
        ties.method <- match.arg(ties.method)
        ...
        if(n>1){x =(rank(x,ties.method=ties.method)-1)/(N-1)*100}
        ...
}
```
- put your unexported function together into `AllUtilities.R` instead of saving them into subdirectory.
- coding practice
```
* NOTE: Avoid sapply(); use vapply() found in files:
set2DF.R (line 46, column 14)
*NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
CytoDx.fit.R (line 95, column 46)
fcs2DF.R (line 71, column 32)
fcs2DF.R (line 100, column 19)
set2DF.R (line 46, column 21)
set2DF.R (line 54, column 13)
```
- Use ` <- ` instead of ` = ` for assignment.

## man
- Looks good.

## vignette

- add a table of contents for your vignette. (https://rmarkdown.rstudio.com/html_document_format.html) Use descriptive section names to organize your vignette. E.g., Introduction, Installation, Pipeline, EigenMS normalization... SessionInfo.
- Add section of `Introduction` to introduce briefly about the package usage, and the structure of your vignette.
- Add section of `Installation` and show users how to download and library this package as if it is already available in Bioconductor. E.g.,
```                                                                                                                                                                                                                                                          
BiocInstaller::biocLite("CytoDx")                                                                                                                                                                                                                            
```                                                                                                                                                                                                                                                          
You can also add a subsection to show to users how to use the development version on github. E.g.,
```                                                                                                                                                                                                                                                          
devtools::install_github("hzc363/CytoDx")                                                                                                                                                                                                                    
```                                                                                                                                                                                                                                                          
- add SessionInfo() in the end.
- the flowchart looks nice!

Cheers,
Qian

**Comment by hzc363** [comment]
Hi @Liubuntu ,

Thank you for the thoughtful review! It is very helpful. I have updated my packages (0.99.4)  to address the listed issues. 

Zicheng

**Comment by hzc363** [comment]
Hi @Liubuntu ,

Thank you for the additional comments. I have updated my package accordingly. 

I created "rank.ub.random.R" during the development stage. It is not used in the final version. So removing it won't affect the package. 

Bests,
Zicheng

**Comment by Liubuntu** [comment]
Hi @hzc363 , 

Thanks for the quick fix. Seems that you wasn't able to add the NEWS file. But since this is the first version of you package we can do without it. But when you make further changes to the development version of this package, (namely in the master branch on github, which will be the development version used in Bioc devel 3.8 after May 1st), please add a NEWS file on the top folder with key features you have added for each version (not necessarily all versions). E.g., 

```
CHANGE IN VERSION 0.99.11 
---------------------------------------------
- key feature change 1
- key change 2

CHANGE IN VERSION 0.99.8 
---------------------------------------------
- key feature change 1
- key change 2
```
I'll accept this package now to make it for the new release, with the deadline of adding being next Monday. Thank you again for your contribution to Bioconductor. 

Cheers, 
Qian

**Comment by hzc363** [comment]
Thank you! @Liubuntu.

It's weird that the NEWS file did not appear on your end. I added an empty NEWS file in the top directory (the same level where DESCRIPTION and NAMESPCAE are). Maybe it is skipped due to the fact that it is empty? Anyway, I will definitely update the NEWS file in future versions. 

Thank you again for your help in the whole process!

Zicheng

**Comment by Liubuntu** [comment]
Sorry, it is there. My overlook.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hzc363.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CytoDx\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CytoDx

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
