### ISSUE TITLE
MetaboSignal

### ISSUE THREAD

**Issue by AndreaRMICL** [Bioconductor/Contributions#68]
- Repository: https://github.com/AndreaRMICL/MetaboSignal

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
I took a preliminary look at your package while moderating it. I'm concerned that the 'copy-and-append' pattern (where a vector is created by growing it, `x=c(); for (...) x = c(x, new_value)`, or using `rbind()` and a data.frame), e.g., [here](https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/MetaboSignal_matrix.R#L461) but at a very large number of places in your code, is known to be very inefficient when data are reasonably sized, as explained [here (point 2)](http://bioconductor.org/developers/how-to/efficient-code/#common-solutions). In at least some places, it seemed that the results could be computed as a single function call without iteration. In other places it would be better to use `lapply()` and then combine the results in one call, e.g., `unlist()` or `do.call("rbind", ...)`.

I'll provide more comprehensive comments at a later date, once the package has built successfully, but it would be great if you could address the above point before a more complete review.

**Comment by AndreaRMICL** [comment]
Hi Martin,


Thanks very much for your fast reply. I will try to address your comments as soon as possible.

Based on the message I just received from Bioconductor, the package builds OK in Mac, Linux and Windows. However, I got a skipped message for build in in Linux and in postprocessing in Windows. I still will work on it to understand why this happens.


Thanks very much,


Andrea

________________________________

**Comment by mtmorgan** [comment]
It is failing on the BiocCheck part of the check, specifically because

```
* Checking for bioc-devel mailing list subscription...
    * REQUIRED: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

**Comment by AndreaRMICL** [comment]
Hi Martin, 

I have been trying to address your comment  regarding the 'copy-and-append' pattern. Based on your suggestion, I have tried to replace this pattern by mapply, lapply and sapply in several places my code. I hope it looks better now, otherwise I can keep on working on it. 

Thanks very much in advance, 
Andrea

**Comment by AndreaRMICL** [comment]
Hi Martin, 
I was a bit worried, so before reading your message I submitted another push. Sorry about this.
Thanks, 
Andrea

**Comment by AndreaRMICL** [comment]
Hi Martin, 

We added a README file to the package. However, when we pushed the package again we got a warning message from Linux, which seems to be :"checking a package with encoding  'UTF-8'  in an ASCII locale". 
We did not get this message before, so we thought it could be because of some text in the Rmd files of the vignette. So we resaved the vignette and push the package again and we still get this warning.... 

Thanks in advance, 
Andrea

**Comment by mtmorgan** [comment]
Hi,

The UTF-8 / ASCII issue seems to be a change in the build environment of zin1; please ignore it.

Please also address the NOTE to add

```
 importFrom("graphics", "hist")
  importFrom("stats", "na.omit")
  importFrom("utils", "capture.output", "write.table")
```
to the NAMESPACE file.

I'll provide a formal review after your next commit.

**Comment by AndreaRMICL** [comment]
Hi Martin, 

Thanks for your reply. Just now we got for windows: 
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :  there is no package called 'graph'

I am not sure what the problem is..

Thanks very much in advance, 
Andrea

**Comment by mtmorgan** [comment]
Yep, its from trying to fix the first problem; ignore this warning, please.

**Comment by AndreaRMICL** [comment]
Ok! Thanks very much.

**Comment by mtmorgan** [comment]
Thanks for your package and dilegent pursuit of an error free build
report!

DESCRIPTION, NAMESPACE, NEWS

- Great!

vignettes

- Good; a completely optional suggestion is to use [BiocStyle][] to
  format the vignette. Benefits would include a look consistent with
  other Bioconductor packages (including, e.g., a format appropriate
  for printing) and a dis-incentive to include html in the markdown!
  
- In the YAML at the top of the vignette, the text '
  %\VignetteIndexEntry{...' should be on new lines, as
  
        vignette: |
        %\VignetteEngine{knitr::rmarkdown}
        %\VignetteIndexEntry{MetaboSignal}
        \usepackage[utf8]{inputenc}
      
  The text for "VignetteIndexEntry" should be the title of the the
  vignette. The relevance can be seen by building and installing the
  package, and then looking at `vignette(package="MetaboSignal")`,
  where the text of VignetteIndexEntry is shown (this also shows up in
  the HTML help page for the package).
  
        R CMD build MetaboSignal
        R CMD INSTALL MetaboSignal_0.99.12.tar.gz 
        R -e "vignette(package='MetaboSignal')"
       
tests

- nice to see unit tests, thanks!

R. The following are meant to be examples of areas for improvement,
rather than an exhaustive enumeration.

- [1][] changes the global `options()`. Usually it's better to write
  code that does not rely on particular values of `options()`. If
  absolutely necessary, the best practice is to ensure that the
  options are reset to their original value whether or not the
  function succeeds. This is typically done by
 
        oopt = options(warn=-1)
        on.exit(options(oopt), add=TRUE)

- The pattern of setting a result list or vector to length zero, then
  'copy-and-appending' in a loop (e.g., for entrezgene starting at
  [2][] is very inefficient; it is better to 'pre-allocate and fill'
  or use e.g., `lapply()` to manage the result vector; see item 2 of
  [3][]. A similar concern involves `rbind()` / `cbind()` and implicit
  vector extension (`x[i] = 1`, where `i > length(x)`) elsewhere in
  your code.

- using [4][] as an example, it's better to write code to avoid errors
  rather than relying on `try()` / `tryCatch()` to recover from
  errors. Is the relevant test that generates an error
  
        response <- query(q="fdf", size=1, species=organism_name)
        if (NROW(response$hits) != 0L) {
            ...

- The KEGG query at [5][] is one gene at a time. The API supports
  multiple queries, using `+` as a separator, and this will be much
  more efficient. 

        readLines("http://rest.kegg.jp/conv/genes/ncbi-geneid:293949+ncbi-geneid:293949")
  
  Consider also using the [KEGGrest][] package as a
  more robust interface, rather than relying on direct `readLine()` access

- Your code seems to do a good job of validating that the user has
  provided reasonable input. A common pattern is to put this
  validation at the very top of the function, so no unnecessary
  computation occurs. For instance [6][] might be moved to be
  immediately after line 12.

- Watch for opportunities to vectorize, typically in `for` loops such
  as [7][], which might be replaced by something along the lines of
  
        idx = grepl("_", MetaboSignal_table)
        nodes = MetaboSignal_table[idx]
        MetaboSignal_table[idx] = substr(nodes, 11, nchar(nodes))
        
man

- The help pages seem to be well done, thanks!


[BiocStyle]: https://bioconductor.org/packages/BiocStyle
[1]: https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/Find_support_Functions.R#L30
[2]: https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/Find_support_Functions.R#L39
[3]: http://bioconductor.org/developers/how-to/efficient-code/#common-solutions
[4]: https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/Find_support_Functions.R#L44-L56
[5]: https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/Find_support_Functions.R#L68
[KEGGrest]: https://bioconductor.org/packages/KEGGrest
[6]: https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/MetaboSignal_matrix.R#L23
[7]: https://github.com/AndreaRMICL/MetaboSignal/blob/master/R/MetaboSignal_matrix.R#L208

**Comment by AndreaRMICL** [comment]
Hi Martin, 

Again thanks very much for your feedback. As suggested, we have modified the vignette, which looks much better now. Thanks! Regarding the R section, we have tried to modify the code taking into account your recommendations. Some specific comments below:

-When possible, we have used the KEGGREST package instead of "readLines()". Regarding "multiple-query", after doing some tests, we came to the conclusion that the maximum number of queries for "keegConv()" is 100. However, I think this is not specified in the reference manual, so I hope the assumption we made is correct....

-Regarding "try()", we have replaced it in the example you mentioned and in some other places. However, in other cases, we think it'd be safer to leave "try()" if possible. See some examples below: 
--"getReactions()" gives an error if the pathway does not have an appropriate format (e.g. if the pathway is not actually a metabolic-pathway). 
-- "keggList()" gives a very non-specific error when the "organism_code" is not valid. We think this error might be difficult to interpret and hence fix by the user. 
--"MS_ChangeNames()" depends of "http://rest.kegg.jp/get/" . When the "query" is not valid, and error is generated and therefore the function stops. However, we want the function to keep on working with the remaining queries. 
-- select(org.Hs.eg.db, keys = symbols, columns = c("ENSEMBL"), keytype = "SYMBOL"),  generates an error when none of the keys (in this case symbols) can be linked to ENSEMBL ids. 

We have done a number of tests, and we think the package is now working like before. We hope the R code looks better now. 

Thanks very much in advance, 

Best wishes, 

Andrea
