### ISSUE TITLE
SeSAMe

### ISSUE THREAD

**Issue by zwdzwd** [Bioconductor/Contributions#685]
Hello,
I'd like to contribute the SeSAMe package to bioconductor. It's my first attempt of a bioconductor submission. Let me know what I am missing. Thank you!

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zwdzwd/sesame

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by PeteHaitch** [comment]
Hi Wanding,

I don't see this in the README or the vignette, so I'll ask it here. What are the major differences between **SeSAMe** and **minfi** (or indeed other Bioconductor packages for analysing Illumina methylation arrays)? There seems to me a large overlap in terms of functionality. 

From a (very brief) look at the code, **SeSAMe** seems to be reimplementing much of this shared functionality because you've opted to define and use the _SignalSet_ class (an R6 class) to represent the methylation array data (rather than re-use an existing S4 class from **minfi**, for example). Why not re-use the existing infrastructure available in Bioconductor? 

Cheers,
Pete

**Comment by zwdzwd** [comment]
Hi @PeteHaitch,

Thank you very much for sharing your thoughts. The fundamental difference between SeSAMe and other packages like minfi, wateRmelon and ChAMP is the special attention paid to intensities. We have a manuscript currently in revision with NAR showing that ignoring intensities can cause substantial artifacts (we included comparisons with minfi and methylumi). We are happy to share the manuscript if that helps you to decide.  In addition, intensities can be used to infer copy number alterations, and more and more groups are aware of that.  Easy access to intensity-level data is needed in light of these two arguments. Current implementation based the SignalSet R6 class increased the transparency of this essential information. What’s more, as you are likely aware, R6 class is more efficient, light-weight and reduces the data-copy overhead. Our current implementation is single-sample based, meaning it can be applied to operate on a large number of samples. This was necessary for big projects like TCGA. minfi adopted single-sample preprocessing in parallel recently.

In addition, we implemented much stricter QC and more proper preprocessing (discussed in Zhou 2017 NAR and Zhou 2018 in revision), and some functionalities that are convenient for people using DNA methylation data. The former includes a comprehensive probe quality masking, bleed-through correction in background subtraction, nonlinear dye bias correction, non-detection calling and control for bisulfite conversion based on C/T-extension probes; The latter includes gender, age, and ethnicity inference (based on channel-switching Type-I probes) directly from the data, so people can correct for these common covariates even if such information had not been collected. Many such features exist uniquely to SeSAMe as far we know. SeSAMe is also designed to be a suite that integrates a set of tools for our own routine DNA methylation data analysis tasks, including differential methylation calling, copy number inference, cell type deconvolution etc..

We developed SeSAMe initially for internal use before the other packages made changes to accommodate the latest EPIC array and kept it private for quite a long time, but got so many requests to share the package that we decided to make it available through BioC. ICGC and NCI Genomic Data Commons have both started adopting SeSAMe for their DNA methylation processing pipelines, and we feel that it would be convenient to have it hosted on BioC. Hope this makes sense. Let me know if you have more questions.

Thanks,

**Comment by PeteHaitch** [comment]
Thanks for your detailed reply, @zwdzwd. I should have clarified: I'm not an official reviewer of the package, but I am an interested onlooker :)

**Comment by vobencha** [comment]
Hi,
I've done a first review. Some comments and suggestions below.

1) vignette
Nice job with the vignette. Please format the code to 80 characters wide to improve readability. I'd also add relevant detail from this conversation to the vignette background: https://github.com/Bioconductor/Contributions/issues/685#issuecomment-375454884. That would be helpful information for anyone looking to use the package.

2) BiocParallel
The mc.* functions from the parallel are not supported on Windows with more than one core. Please use the BiocParallel package instead of parallel. BiocParallel is supported across all platforms and builds on the snow and parallel packages; in other words, you aren't loosing functionality by using BiocParallel.

3) Remove sysdata.rda the from R/ directory.

4) R code files
Please rename your files to more descriptive names. For example, the test.R file contains code for simulating data. Why not call this simulate.R or simulate_data.R?

5) Remove SeSAMeGetExample and getBuiltInData
AFAICT these functions download data for the examples followed by a complicated caching mechanism. Why did you take this approach instead of including small sample datasets in the package?

  I would recommend removing these functions and including sample data in the data/ directory. Load the files in examples with the standard data() or load().

6) man pages
The man pages need more detail. In general they don't explain enough about what the function does, the input/output object, number of samples (?), genes (?), cols, rows what type of data, what the data can be used for etc.

  These are a few examples lacking detail but I would encourage you to through all of them and add more information.
```
meanIntensity
makeExampleTinyEPICDataSet
makeExampleSeSAMeDataSet
readIDATs
...
```

7) dontrun on readIDATs man page
Why is the dontrun in the example necessary? This wrapper is sometimes used when an example takes too long to evaluate but this one doesn't even run:
```
> library(sesame)
> ssets <- readIDATs(c('data/5775041003_R02C01', 'data/5775041003_R03C01'))
Error in illuminaio::readIDAT(paste0(idat.name, "_Grn.idat")) :
  Unable to find file data/5775041003_R02C01_Grn.idat
```

8) Please remove the date field from DESCRIPTION - this quickly becomes stale.

9) reference classes
I think using reference classes in the package is probably unnecessary and certainly confusing. Most R users are not familiar with or expecting reference class behavior. Implementation of the 'in.place' argument (default of FALSE) means you have situations where the standard R semantics (copy on change) are preferred over reference semantics. Having both of these behaviors exposed in one package is not a clean design.

  A reference class might make sense in a situation where one function performed multiple steps behind the scenes and modified the data (full copy) in each step. However I don't see that scenario in this package. Instead I see each function as an individual step in the analysis at which point the user may want to inspect results and compare with the previous.

  If you are concerned about efficiency in managing large data there are several options available in Bioconductor, DelayedArray and derivatives are a place to start. Or maybe you have another reason for implementing reference classes that I have overlooked ... ?

  Please consider using standard S4 classes instead of the reference classes.

**Comment by zwdzwd** [comment]
Thanks for the very detailed review @vobencha . These are educating the helpful. I currently have trouble putting all the annotation data and example data in data/. My annotation data can be a couple hundred MB big. These can become quite clumsy even for github to handle. That's why we had getBuiltInData which tried to retrieve data from the internet by needs. I understand this could potentially limit users with restricted internet access. So then we devised this caching mechanism. Apparently all these are not the most orthodox ways to do in BioC. Do you think I should add a data package as a dependency? I previously had tried to avoid that just for simplicity. But it looks like there is no simple way around? Thanks for your help again!

**Comment by zwdzwd** [comment]
Dear @vobencha ,
While I am addressing the rest of the issues, I made the following [data package](https://github.com/zwdzwd/sesameData) that sesame depends on. And have 
`Remotes:  zwdzwd/sesameData`
in `DESCRIPTION`.
The data package is around 360MB. I am not sure if I should leave the data package on github and let installation pull from github like how it's setup now, or submit the data package to bioC too.

For the latter, I read [this](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages), it seems I should add 

`AdditionalPackage: https://github.com/zwdzwd/sesameData`

But it also seems I should've submitted sesameData first, and then make sesame the additional package. I wonder if I do the other way, do I get cyclic dependency? I am not sure what is the best way to squeeze in the data package given that I already set up the sesame repo. Many thanks for any insight!

**Comment by zwdzwd** [comment]
Hi @vobencha ,
Thanks for your instruction and the heads-up. I will close this issue and reopen a new one for the annotation package. I finished addressing all the issues raised in your first review. I will post my response once the data package get through. I am entirely with you that getting the package structure correct and robust is more important than making the deadline. I will let you decide based on the new version. Thanks so much for taking the time to review!
