### ISSUE TITLE
Requesting new bioconductor submission called Ularcirc (a shiny app)

### ISSUE THREAD

**Issue by davhum** [Bioconductor/Contributions#688]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/VCCRI/Ularcirc

Confirm the following by editing each check box to '[x]'

- [ x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x ] The 'devel' branch for new packages and features.
- [ x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [  x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by davhum** [comment]
Dear Marcel,

Any clues what/where the timeout is due to? I have included a "\donttest" around the two exported functions. There is no R code in vignette as this package is heavily based on the GUI as provided by Shiny.
Regards,
Dave

**Comment by davhum** [comment]
Hi @LiNk-NY ,

Any clues what/where the timeout is due to? I have included a "\donttest" around the two exported functions. There is no R code in vignette as this package is heavily based on the GUI as provided by Shiny.
Regards,
Dave

**Comment by davhum** [comment]
Dear @LiNk-NY ,

I have resolved the timeout issue which was occuring in the manual documentation with code demonstrating how to commence the shiny app. This has now turned into the following warning as the only line of code that the build now sees is the library command and it thinks it is not necessary.

WARNING: The following files call library or require on Ularcirc.
      This is not necessary. man/Ularcirc.Rd


The other warning I see that I cannot resolve is the following:

* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import data.table, gsubfn, Biostrings, GenomicFeatures,
      GenomeInfoDb, GenomeInfoDbData, Sushi, moments, DT, yaml, httpuv
      in NAMESPACE as well as DESCRIPTION. 


All these libraries are required in the shiny app which is not seen by the build engine (i.e. code lives in the inst/shiny directory).  I would prefer to leave the description file as is so that all libraries are available prior to loading the shiny app.

Are you happy to review package in current state?
Regards,
Dave

**Comment by LiNk-NY** [comment]
Hi David, @davhum 

Thank you for your submission.
Please see the review below. 

Feel free to contact me with any questions. 

Best regards,
Marcel

---

# Ularcirc #688

* Remove `docs` folder from git repository and add to `.gitignore`
* Ensure that your formatting is following recommendations. Keep lines of code
shorter than 80 column width. It makes code easier to maintain and review :)

## DESCRIPTION

* Looks good, you should format the `Description` and `Imports` fields so that
they fit under 80 column width.
* Minor: Author and Maintainer can be combined into the `Authors@R` field

## R

* Avoid using `1:length(x)` sequence generation. Use the more robust `seq_along`
and `seq_len`. 
* You may just want to provide a `data.frame` as the output of
`Compatible_Annotation_DBs` with 2 columns. The data type and the actual
name, e.g., `data.frame(dataType = "Annotations", name = "org.Bt.eg.db")`
* It's recommended that you use the allocate and fill method for creating
vectors rather than the copy and append (Line#63).
* I ran the shiny app and kept getting an error: 
`object 'idx' not found`. After selecing `Hsapiens.UCSC.hg19` in the setup
tab. Default "states" in other tabs should just work or have a default
message for additional input rather than an error.

Minor:
* `if(length(x) > 0)` is the same as `if(length(x))`

## inst/extdata

* The datasets contained in this folder are pretty big (~7.8 MB).
Can you reduce the size of these?
* Why not include the functions found in the shiny app directory in the
package?

## vignettes

* It looks good. Step 5 should be finished. 

## man

* It looks okay. Capitalize Bioconductor in `Compatible_*` man page.

**Comment by LiNk-NY** [comment]
Hi David, @davhum 
Please respond to the items in the review. 

Best regards,
Marcel

**Comment by davhum** [comment]
Hi Marcel, 
Thank you for the review, I do appreciate the effort you went to. Apologies that I have not responded yet. I will complete items in review over the next couple of days. 

Kind regards,
David

**Comment by davhum** [comment]
Hi Marcel,

Have a couple of questions relating to your comments:

* "You may just want to provide a data.frame as the output of Compatible_Annotation_DBs with 2 columns"

Currently this function returns a list object that when referenced will display  R code that can be copied and pasted to install databases. This purpose of this implementation was to provide an easy way for users to identify what databases are available and to produce code that will install new databases. Your suggestion for returning a data.frame with two columns is a neat solution that will also identify what databases are available. However it doesn't provide a the exact code required to download databases. There is a good chance inexperienced R users will want to use this package and I want to make it as easy as possible for them to be successful. Would you be OK if I left it the way it is (or perhaps have another suggestion)?  

Can you clarify the folllowing comment "allocate and fill method for creating vectors". 
How do you allocate when you do not know in advance how big the vector will be? 

Kind regards,
David

**Comment by LiNk-NY** [comment]
Hi David, @davhum 

It's actually more confusing when you assign with the function. The user gets a vector
printout and upon inspection of the object, the user sees a list...

I think you want to use the `data.frame` as mentioned above and then write a small
function to create the command for beginners (for a single row). This way, you'll have a
pure function in `Compatible_Annotation_DBs`, meaning that it returns a consistent output 
(you may also want to support search pattern inputs).

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi David, @davhum 
Can you push a version bump to rebuild the package? 
Thanks,
Marcel

**Comment by LiNk-NY** [comment]
Hi David, @davhum 

Please submit your changes with a version bump. 
Otherwise, I will be forced to close the issue due to inactivity. 
You will be able to submit at a later time when the package has been revised. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi David, @davhum 
Thanks for making those changes. 

* Don't worry about the allocate and fill method. Recent updates to R will make this 
more efficient by default.

* Compatible_Annotation_DBs: It's an awkward way of helping the user because the return value does not match what is shown when printing the object. I would rather create a small vignette about using this function and returning a `data.frame` object with the names of the associated packages.
It also might be the case that this feature is no longer needed as you could do a query in `BiocManager::available("*\\.dm\\.*")`

* You can add those as you further develop your package. 

Regards,
Marcel

**Comment by davhum** [comment]
Hi Marcel,

Thanks for additional comments. What do you think of the current version of Compatible_Anotation_DBs?

In this version I have modified it so that:
     -the default is to return a dataframe (3 columns : one for annotation database, one for genome and one for transcript database).
      -  If pass a boolean of TRUE then will return the unconventional list. I'll delete this option completely if you still wish.
     - no longer prints out a list of genomes 

Regards,
David

**Comment by LiNk-NY** [comment]
Hi David, @davhum 

Apologies for the numerous revision requests but I'm seeing this function in a different way.

What I was suggesting is that the function return _just_ a `data.frame` with the **exact** results of the package names (e.g., don't truncate 'TxDb' in `TxDb.Btaurus.UCSC.bosTau8.refGene`).

You could even add an argument to search for a particular organism and return a single row `data.frame`.

You could then use this output in _another_ function that will make it convenient for the user to copy and paste the command. Please make sure that you are just using `cat` instead of returning a vector so that you don't get the `[1]` number outputs.

To see an example, you can refer to [Bioconductor/BiocManager::valid](https://github.com/Bioconductor/BiocManager/blob/master/R/valid.R#L122). 

If you feel like this is too much, you can take it as a work in progress. But it would be really good to have a function that consistently returns a single type of output (pure function; see [Functions](http://adv-r.had.co.nz/Functions.html) for details).

Marcel

**Comment by davhum** [comment]
Hi Marcel,

Have fixed Compatible_Annotation_DBs so that it now returns a dataframe (rather than use the invisible command). I have also added a feature that will enable searching for a search term so that the returned dataframe only contains a subset of entries.

Please let me know if there is anything else you require for this submission.
Regards,
David.

**Comment by LiNk-NY** [comment]
Hi David, 

Thanks for making those changes!
I'm not sure why it made sense to use a `matrix` but that is your choice as a developer. 
Thank you for your submission. It has been accepted. 

Regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/davhum.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"Ularcirc\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Ularcirc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
