### ISSUE TITLE
ASICS

### ISSUE THREAD

**Issue by GaelleLefort** [Bioconductor/Contributions#695]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GaelleLefort/ASICS

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@lshep will review, but note that a 'real' vignette is required, with fully evaluated code illustrating use of your package and perhaps integration with other parts of the Bioconductor ecosystem. Usually this identifying an interesting subset of data for analysis, so that your package remains within the guidelines for time and space during R CMD build / check.

**Comment by GaelleLefort** [comment]
Dear @lshep 

A timeout appears with the last check on tokay2 but yesterday there was no timeout on this server with the same package (I only change a line in DESCRIPTION file). How can that be explained? 

Moreover, only one error remains about the package already on CRAN.
I ask CRAN team to remove my package few days ago but I don't have any answer yet. Do you think it's possible to review the package despite this error ?

Thanks,
Gaëlle

**Comment by lshep** [comment]
The windows platform is checked on both x64 and i386, it could've taken longer if you were downloading resources or something of the like  - Regardless of the timeout on windows - the check time is too long for merida2 and malbec2 as the check time should be less than 5 min on one of these platforms as stated in the [package guidelines](http://bioconductor.org/developers/package-guidelines/) . I haven't looked at the package yet but perhaps there is room for some [more efficient programming](http://bioconductor.org/developers/how-to/efficient-code/)  or perhaps smaller sets of data can be used for examples/vignettes 

I will do a more indepth official review within the next few days but the package will not be accepted until it is removed from CRAN -

**Comment by GaelleLefort** [comment]
I change some examples and tests so the check is faster now. The package have also been removed from CRAN. 

Gaëlle

**Comment by lshep** [comment]
- [ ] You also might considering adding a new line at the end of your customized show methods for your objects:

```
> resASICS
An object of class ASICSResults 
It contains 1 spectra of 31087 points. 

ASICS results: 
 2 metabolites are identified for this set of spectra. 
Most concentrated metabolites are: Lactate, L-Alanine> 
```

- [ ] As I'm working through the code in the html user guide I'm finding I can't run all the code - (which is why we don't encourage these types of documents because you can't catch errors as easy with non run code)

```
> new_pure_library <- createPureLibrary(pure_spectra, 
+                                         nb.protons = c(5, 4, 9, 9))
Error in validObject(.Object) : 
  invalid class "PureLibrary" object: Vector contaning the numbers of protons must be of same length than the sample name vector.
```


- [ ] I also don't see where you utilize your newly defined  AnalysisResults-class?

**Comment by GaelleLefort** [comment]
Thank you for the review!
I add .R and .Rmd files for the user's guide. We decide to do this way to have a realistic example and stay within the time limits for build and check. We look for a solution to have only one vignette for a next release.
The error is due to recent changes in example data I correct it.
The  AnalysisResults-class is use in all analysis functions : pca, oplsda and krukalWallis.

Gaëlle

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GaelleLefort.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ASICS\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ASICS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
