### ISSUE TITLE
Submitting New Package "TissueEnrich"

### ISSUE THREAD

**Issue by ashishjain1988** [Bioconductor/Contributions#697]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Tuteja-Lab/TissueEnrich

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please enable interoperability and robust code by using well-established Bioconductor data representations, especially  [SummarizedExperiment][1]; see also [these guidelines][2].

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by mtmorgan** [comment]
Use SummarizedExperiment for matrix-like inputs / outputs; lists of genes do not fit this description. The GSEABase class has some standard representations, but I would not recommend their use as strongly.

**Comment by ashishjain1988** [comment]
@mtmorgan As per your suggestions, I updated the input and output using the Bioconductor recommended data structures. The version is 0.99.4.

**Comment by mtmorgan** [comment]
# 3 April, 2018

Thank you for your contribution. Please revise your package in response to the following comments, posting a short description of your revisions when ready for a second review.

DESCRIPTION, NEWS

- great!
- remove man/.DS_Store and other files not related to this package from the git repository.

NAMESPACE

- see below

vignettes

- good!

R

- remove `library()` calls; required functions should be imported in the NAMESPACE. use the `@import` and `@importFrom` tags and `devtools::document()` to manage the NAMESPACE file, or edit by hand.

- adopt a coding style that allows for longer lines with more consistent indentation; aim for lines that are < 80 characters wide, so that they are easy to scan by a human e.g., tissueEnrich.R:53

    ```
        expressionData<-ensurer::ensure_that(
            expressionData, !is.null(.) && 
            class(.) == "SummarizedExperiment" && 
            !is.null(assay(.)) && 
            (nrow(assay(.)) > 0) && 
            (ncol(assay(.)) > 1) && 
            (ncol(rowData(.)) == 1) && (ncol(colData(.)) == 1),
            err_desc = "expressionData should be a non-empty SummarizedExperiment object with at least 1 gene and 2 tissues."
        )
    ```

- adopt a more readable coding style, e.g., spacing around assignment `minNumberOfTissues <- 2`, broken lines (tissueEnrich.R:73), etc; consider e.g., the [formatR][1] package for guidance.

    ```
    expressionData <- setNames(
        data.frame(
            assay(expressionData), 
            row.names = rowData(expressionData)[,1]
        ),
        colData(expressionData)[,1]
    )
    ```
    
[1]: https://cran.r-project.org/package=formatR

- carefully consider the need for each statement, e.g., tissueEnrich.R:76

    ```
        tpm<-data.frame(t(as.matrix(expressionData[gene,])))
        colnames(tpm)<-c(gene)
        tpm<-tpm[with(tpm, order(-tpm[gene])), ,drop = FALSE]
    ```
    
    does not require `data.frame()`, `c()`, `with()`. At the start of the function `expressionData` should not have been coerced to a matrix, so `as.matrix()` and `colnames()` are also not required.
- carefully consider how to replace iteration (e.g., `for`, `lapply()`, `apply()`; many calls to _R_ functions) with vectorization (one call to _R_ fucntions); the [matrixStats][2] package can be helpful for this, e.g., `highTPM` at tissueEnrich.R:79 can be calculated as a vector outside the `for` iteration with `highTPM <- matrixStats::rowMaxs(expressionData)` (or maybe that's `colMaxs()`, it's hard for me to keep straight).
- `rbind()` and `cbind()` in iterations, e.g., at tissueEnrich.R:109 are usually very inefficient; this loop would seem to be

    ```
    j <- seq_len(i)
    df <- data.frame(
        Gene = gene, Tissue = row.names(tpm)[j], Group = "Group-Enriched"
    )
    groupEnriched <- rbind(groupEnriched, df)
    ```
    
  The many `rbind()` implied by the iteration `for(i in 2:(nrow(groupTPM)))`  can likely be replaced by a pattern like `x <- lapply(2:(nrow(groupTPM)), .); do.call("rbind", x)`.
  
- in complex `if()` statements, factor out common expressions to reduce the amount of redundant computation in the conditional. e.g., tissueEnrich.R:578

    ```
    groups <- list(
        c("Tissue-Enriched", "Tissue-Enhanced", "Group-Enriched"),
        "Tissue-Enriched", "Tissue-Enhanced", "Group-Enriched"
    )
    if (tissueSpecificGeneType > length(groups))
        stop("...")
    group <- groups[[tissueSpecificGeneType]]
    ridx <- tissueSpecificGeneType$Group %in% group
    finalTissueSpecificGenes <- tissueSpecificGeneType[ridx, , drop=FALSE]
    ```
- consider breaking your code into separate logically coherent files, e.g., one file per each exported function.

**Comment by ashishjain1988** [comment]
@mtmorgan Thank you for the detailed code review and suggestions to optimize the code. Being new in R, these suggestions are very helpful. I have one question regarding the loops. Should I not use the `for` loops at all in my code (instead use `lapply` or other functions)?

**Comment by mtmorgan** [comment]
`for` and `apply` are really the same thing, iterations. The goal is to write code that can be vectorized

      sapply(letters, function(x) if (x > "c") TRUE else FALSE)  # iteration, 26 calls to function(), if, >, etc.
      letters > "c"                                                                         # vectorized, 1 call to >

There are three things about your code that need to be improved.

The first is that you've thought of operating on individual elements of vectors, instead of on the entire vector, like the `>` comparison above; usually one can start to 'hoist' parts of a complicated iteration outside the for loop into vectorized operations, and suddenly it becomes clear that all steps in the loop can be hoisted out, and what was previously an iteration is now a vectorization.

The second thing about your code is that it has been structured as basically lists-of-lists, instead of as vectors, along the lines of

    sets1 = list(a=letters[1:3], b = letters[4:5])                                                                       # list-oriented
    sets2 = data.frame(set = rep(c("a", "b"), c(3, 2)), member = c(letters[1:3], letters[4:5])) # vectors

`sets1` needs to be processed by an iteration `lapply(sets`, toupper)` whereas `sets2` can be processed in a vectorized fashion `toupper(sets2$member)`.

The third aspect of your code is that it has conditional statements inside the iteration, instead of outside (or simply being less ambitious about the situations that you will handle). 

    lapply(sets1, function(elt) {
        if (length(elt) %% 2 == 0)                                                  # condition inside iteration
            toupper(elt)
        else elt
    })
    doit = lengths(sets1) %% 2 == 0                                          # vectorized condition
    sets1[doit] = lapply(sets1[doit], toupper)                              # iteration without inside condition
    sets1[doit] = relist(toupper(unlist(sets1[doit])), sets1[doit])   # vectorized
    tbl = table(sets2$set)
    doit = sets2$set %in% names(tbl)[tbl %% 2 == 0]
    sets2$members[doit] = toupper(sets2$members[doit])        # vectorized

**Comment by ashishjain1988** [comment]
@mtmorgan Thank you so much for this explanation. It will really help me in optimizing my code. Thank you again!

**Comment by ashishjain1988** [comment]
@mtmorgan I updated the code following the comments made in the code review. The summary of the updates made in the revision (0.99.11) is as follows:

DESCRIPTION, NEWS
*  Removed the man/.DS_Store from the package.

R

* Removed the `library` calls from the R files and put it in the NAMESPACE file.
* Adopted the Bioconductor's coding style and broke down the lines greater than 80 characters in human readable format. Also followed the guidelines for the indentation using `formatR`.
* Removed redundant data format conversions in the code.
* Used the vectorization strategy to remove the loops wherever possible.
* Removed `rbind`, `cbind`, and `if` statements inside the iterations wherever possible.
* Broke the code into three files; one file per each exported function.

Again, I would like to thank you for your previous suggestions as it helped me a lot to improve the speed considerably.

**Comment by mtmorgan** [comment]
Thanks for your revisions

- please remove vignettes/TissueEnrich.html and vignettes/TissueEnrich.R ; these are created by the build process.

**Comment by ashishjain1988** [comment]
@mtmorgan These files are not there in my github repository.

**Comment by mtmorgan** [comment]
My mistake, sorry!

**Comment by ashishjain1988** [comment]
@mtmorgan Thank you for accepting my package!!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ashishjain1988.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TissueEnrich\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TissueEnrich

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
