### ISSUE TITLE
geneAttribution

### ISSUE THREAD

**Issue by awuster** [Bioconductor/Contributions#70]
- Repository: https://github.com/awuster/geneAttribution

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Marcel will review your package, but in moderating it I noticed that you read bed files using read.table, and then cast to GRanges. It is better to re-use existing software, in this case `rtracklayer::import.bed()`.

**Comment by LiNk-NY** [comment]
Hi @awuster, 
Thank you for submitting your package. I saw that you implemented the use of the `import.bed` function. Great! 
The review is as follows: 

---

#### Package size > 5Mb
Perhaps you can make the example data files (in `/inst/extdata/`) a bit smaller since they are 4.9Mb of your package. You just need the minimum to show how your code runs. 

#### Descriptive function names
You have some functions like `ga` that could use a better and more descriptive name. Perhaps you can consider naming it `geneAttribution` as this is likely the main function in your package and should be of the same name. 

#### Vignettes
* The `inst/doc/` folder does not have to be included as it will be generated at build time. 
* You have duplicate vignette files in the repository. 

#### Unit tests

We highly encourage the use of unit tests for your package. This not only ensures that your functions are working correctly, but also helps you prevent any bugs with further development. Please add some unit tests to your functions. 

#### Grammar
Please try to avoid `1:length(x)` and `rep(1, value)` syntax as this may present problems when x = 0. Please use seq_along(x) and seq_len(value). 

#### Minor considerations
* Shortening lines to less then 80 columns/characters

Your submission is looking good. 
Please make the appropriate changes and bump the version for the SPB. Looking forward to accepting your package.

Thank you again for submitting to Bioconductor!

Regards,
Marcel

**Comment by awuster** [comment]
Hi Marcel,

Thank you for your comments! I've resolved almost all the issues you raised, but before I submit the updated version, I was wondering if you could help me with the following:

- You suggest avoiding 1:length(x) and rep(1, value) and using seq_along() and seq_len() instead. I was able to do that for 1:length(x), but I couldn't figure out how to do that for rep()
- I shortened almost all lines to < 80 characters, but for some lines this isn't feasible. I assume that's not a problem?

Thanks again,

Art

**Comment by LiNk-NY** [comment]
Hi @awuster, 
* For `rep(1, value)` you would enter `seq_len(value)` instead. 
* That is okay if you can't do it for some. The reason we want to have lines shortened to less than <80 columns/characters is to improve readability. 

I will have a look at it an approve your submission. Thank you!

**Comment by LiNk-NY** [comment]
Hi @awuster, 
Thank you for your submission. Your package has been approved! 
You will get a notice in a few days regarding SVN credentials. 

Marcel

**Comment by awuster** [comment]
Hi @LiNk-NY,

That's great news!

Thanks again,

Art

**Comment by awuster** [comment]
Hi @LiNk-NY,

It has been a week, but I haven't received any SVN credentials yet. I was wondering what the status of this was?

Thanks,

Art

**Comment by LiNk-NY** [comment]
Hi Art, 
I will contact @mtmorgan and let him know. 
Thank you, 
Marcel
