### ISSUE TITLE
sevenC

### ISSUE THREAD

**Issue by ibn-salem** [Bioconductor/Contributions#700]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ibn-salem/sevenC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ibn-salem** [comment]
@vobencha Please note that this package was submitted before under the name "chromloop" #511. I renamed the package into "sevenC" and submitted it here again.

**Comment by ibn-salem** [comment]
Hi @LiNk-NY ,
the automatic check on windows results in warnings of this kind: 

Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/RtmpMBDhSF/R.INSTALL28c5080708d/sevenC/man/addCovToGR.Rd:5: file link 'GRanges' in package 'GenomicRanges' does not exist and so has been treated as a topic

This seems to be a common issue also in build reports of other packages, such as GenomicRanges or InteractionSet. Is there anything I can do about this?
Many thanks in advance for your help!

**Comment by ibn-salem** [comment]
Dear @LiNk-NY and @mtmorgan 
as mentioned above, my package gets only warnings on windows. They are all of this kind:

> Rd warning: C:/Users/pkgbuild/AppData/Local/Temp/RtmpMBDhSF/R.INSTALL28c5080708d/sevenC/man/addCovToGR.Rd:5: file link 'GRanges' in package 'GenomicRanges' does not exist and so has been treated as a topic

These warnings are also discussed on the Bioc-devel mailing list:
https://stat.ethz.ch/pipermail/bioc-devel/2018-April/013161.html

Is there anything I can do from my side to proceed with the package submission? I would be really happy to get a review of my package in time for the 3.7 release. 

Many thanks for your help!

**Comment by LiNk-NY** [comment]
Hi Jonas, @ibn-salem 

This is a known issue regarding the documentation on Windows.
We have been looking into and will decide what to do with the generated warnings.
For now, just ignore them. 

Thank you,
Marcel

**Comment by ibn-salem** [comment]
Hi Marcel @LiNk-NY

thanks a lot for the review! 

I'm happy that you like the package. Thanks for your suggestions. As you can see 
I made the respective changes. Two of your points are addressed below.

Please let me know if you have questions or further suggestions!

Best,
Jonas

---

> - Why not sort the inGR for the user by default instead of giving an error?

The reason was to have the same order of elements in `regions(gi)` and `inGR`
after calling `gi <- getCisPairs(inGR)`. The `GenomicInteractions` class has
several functions to access the anchor regions, such as `anchors(gi)`,
`anchorIds()` or `regions(gi)`. Changing `inGR` inside the function could lead
to confusion when order of anchors and indexes are different to the input
ranges, I think.

> - Can you provide examples that work for windows as well?

since bigWig file parsing is not supported on Windows, Windws users would need
to provide coverage counts for each motif as `NumericList` to run the loop
prediciton method.
I added the following to the vignette:
Please note, on Windows systems, reading of bigWig files is currently not
supported. See `help(rtracklayer::import.bw)` for more information. Users on
Windows need to get ChIP-seq signals around motif sites as a `NumierList`
object. A `NumericList` `l` with ChIP-signal counts around each motif list can
be added by `motifs$chip <- l`.

**Comment by LiNk-NY** [comment]
Hi Jonas, @ibn-salem 

Thanks for making those changes. 
One possibility is to abstract the internal representation a bit more. 
If many of your operations will require that you have a sorted `inGR` then
you could internally do the sorting and keep an index of the order that it was
received in. This would be akin to what some standard Bioconductor
classes do internally (such as `GRangesList`). 

You could consider this for future changes.
Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ibn-salem.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"sevenC\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sevenC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by nturaga** [comment]
Please use the following link to [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/). The link listed in the previous message is deprecated.
