### ISSUE TITLE
package TFutils submission

### ISSUE THREAD

**Issue by shwetagopaul92** [Bioconductor/Contributions#705]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shwetagopaul92/TFutils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Please see the following review comments

- [ ] There are .DS_Store files that need to be removed from the git tree with `git rm`   vignettes/ data/ R/ ... possibly elsewhere

- [ ] From the build report
```
 * NOTE: Avoid sapply(); use vapply() found in files:
    grabTab.R (line 31, column 12)
```
-[ ] also sapply in vignette

- [ ] From build report
```
* Checking for direct slot access...
    Found @ in vignettes/TFutils.Rmd
    * NOTE: Use accessors; don't access S4 class slots via '@' in
      examples/vignettes.
```
Is this something that the user would want frequently that an accessor method is
    appropriate? 

**man pages:**
- [ ] I feel like all of these could be expanded and add more detail. the data pages should describe where it came from and how it was generated, the class pages - please give more detail about structure and slots 

 - [ ] Why was it necessary to create your own class instead of using an existing Bioconductor infrastructure? 


After updates are made, please do a version bump to get a new build of the package and comment back here with what has been modified and any appropriate responses.  Thank you for your interest in Bioconductor.

**Comment by vjcitn** [comment]
Hi -- I wanted to comment on the "new class" introduced in TFutils.  We did not see an immediate map from existing classes to this one, where we are coordinating a resource name, ad hoc identifiers, a map from ad hoc to HGNC symbols, and general metadata.  It is conceivable that a "db-like" interface would be nice for this problem -- so that select() and keytype etc. would be usable for the translations and set mappings that are of interest.  But that seemed kind of heavy at this point.

**Comment by shwetagopaul92** [comment]
Hi @lshep 
Thank you for your feedback.
1. The .DS_Store files have been removed from the github repository.
2. sapply() has been replaced with vapply() in grabTab.R and in the vignette.
3. Accessors have been used in the vignette.
4. We have added more details to the man pages. 

Thank you!

**Comment by lshep** [comment]
Some other minor points:

**vignette:**
Classification of transcription factors section -  while you load the needed libraries at the top for the other sections you included the needed packages -  for this section you don't show where kable comes from, add the library(knitr) 

**Data/man**
Is there a plan for periodically updating the data in the package - the three main datasets have been Extracted March 2018 - do these get updated frequently? 
Again it would be nice for more detail about how the actual data was created for example, tftColl. How was this object created?  Are the other datasets just downloaded and saved as data.frame? 

**class/man**
TFCatalog-class.Rd
define a structure to hold information about TFs from diverse reference sources - What is the class structure? what are the slots? are they lists, data frames, characters? 

Thank you.

**Comment by vjcitn** [comment]
Hi -- I will comment but I hope Shweta can make the changes.

On Mon, Apr 9, 2018 at 10:54 AM, lshep <notifications@github.com> wrote:

> Some other minor points:
>
> *vignette:*
> Classification of transcription factors section - while you load the
> needed libraries at the top for the other sections you included the needed
> packages - for this section you don't show where kable comes from, add the
> library(knitr)
>
OK -- that's just a line in the vignette before call to kable

> *Data/man*
> Is there a plan for periodically updating the data in the package - the
> three main datasets have been Extracted March 2018 - do these get updated
> frequently?
>
"longer run" the tables can probably become AnnotationHub resources.  I
think the frequency of updates
is modest at best -- we really want to prove utility before pushing further.

> Again it would be nice for more detail about how the actual data was
> created for example, tftColl. How was this object created? Are the other
> datasets just downloaded and saved as data.frame?
>
tftColl is indeed a simple GSEABase::getGmt run on the downloaded c3/TFT
gene set collection from msigDb ... the man page should reflect that.

the cisbp and hocomoco man pages indicate the sources, and indeed they are
just tables that are serialized as
data.frame




> *class/man*
> TFCatalog-class.Rd
> define a structure to hold information about TFs from diverse reference
> sources - What is the class structure? what are the slots? are they lists,
> data frames, characters?
>
indeed this is a misunderstanding of how roxygen does class documentation.
i thought it would
generate slot info etc.  We may have to get the export directive right.
however you can add
the information that the slots are

Name:        name  nativeIds    HGNCmap   metadata

Class:  character  character data.frame        ANY


"nativeIds" are the tokens used by the provider to enumerate

TFs


HGNCmap is a data.frame with at least two columns, the first should

be the native id and the second is the HGNC symbol to which

native id maps.  There may be additional columns and we do

not force any particular choice of column names.


we should use the example code


> TFs_MSIG = TFCatalog(name="MsigDb.TFT", nativeIds=names(tftColl),

  HGNCmap=data.frame(tftCollMap,stringsAsFactors=FALSE))


the result is


> TFs_MSIG

TFutils TFCatalog instance MsigDb.TFT

 615 native Ids, including

AAANWWTGC_UNKNOWN ... GCCATNTTG_YY1_Q6

 196 unique HGNC tags, including

MYOD1 TCF3 ... USP7 YY1

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shwetagopaul92.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TFutils\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TFutils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
