### ISSUE TITLE
(inactive) modulaRmap

### ISSUE THREAD

**Issue by jrybarczyk** [Bioconductor/Contributions#706]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jrybarczyk/modulaRmap

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I'd like to review your package; please update the version to trigger a build.

**Comment by mtmorgan** [comment]
Thanks for your contribution. Your package requires extensive revision, in particular revinsing code so that it is 'vectorized' rather than using iterations (`for` loops). There are a number of additional problems with the vignette, man pages, etc; the review below is not meant to be comprehensive but instead to outline where you must expend effort. Because there are so many opportunities to improve the quality of the code, I am declining the package for consideration in Bioconductor.

DESCRIPTION, NAMESPACE

- ok

vignettes

- remove .html, .R files (these are generated by the build process
- remove .png files generated by the vignette
- modulaRmap.Rmd:60 generate the data with

    ```
    tab <- data.frame(
        keys = keys(GOTERM), 
        ontology = Ontology(keys(GOTERM)), 
        stringsAsFactors=FALSE, row.names=NULL
    )
    ```

- modulaRmap.Rmd:82 generally no need to use `as.list(GO*)`
- modulaRmap.Rmd:106: `sub()` (first occurence in each element) rather than `gsub()` (all occurrences in each element)
- iteration (`for` loops, `lapply()`) are rarerly needed and often highly inefficient in _R_. The iteration at modulaRmap.Rmd:111 is particularly expensive, involve web requests. Simply call `getBM(, values = tab_BP$keys)` once.
- unnecessary iteration is pervasive in your code, and must be avoided. The next example is at modulaRmap.Rmd:117 where the tests do not need to be iterated over

    ```
    absent <- !nzchar(gene.data$hgnc_symbol) | is.na(gene.data$hgnc_symbol)
    ```
- it's not clear why these apparently common operations are being required of the user, instead of being implemented in the vignette.
- the code formating is non-standard; use [formatR][1] to provide more standard code.
- use the [`select()` interface][2] to Bioconductor annotation resources, rather than out-of-date `getSYMBOL()` and friends

[1] https://cran.r-project.org/package=formatR
[2] https://bioconductor.org/packages/release/bioc/vignettes/AnnotationDbi/inst/doc/IntroToAnnotationPackages.pdf

R

- the code has many examples of unnecessary iteration, e.g., the loops at arrayGenes.R:29, c.f., e.g., `scale()`, `colMeans()`, etc.
- `message(paste(...))` usually can be written as `message(...)`.
- never change user directory via `setwd()`; simply use the file path including the directory, e.g,. `out <- file.path(outdir, out).
- things like `paste0("arrayXgenes.txt")` have no effect, remove.
- if using `message()` to provide progress updates, be sure to include a `verbose=FALSE` argument so that these can be silenced by the user.
- adopt `camelCase()` to name functions; do not mix this with other naming convetions especially those that can be confused with S3 methods such as `consistency.stats`.
- I don't see anything in the nested loops at consistency.stats.R:9 that require iteration; vectorize this. The calculations do not seem time intensive, so do not require a progress bar. Avoid 'copy-and-append' forms such as `final <- NULL; ... `final <- rbind(final, tab)`; see [here][3].
- start each user-facing function by validating inputs are correct. For instance, use `stopifnot()` to assert that the input is a data.frame with correct number of columns and correct type of data.
- THE REMAINING FILES IN YOUR PACKGE HAVE SIMILAR PROBLEMS AND REQUIRE EXTENSIVE AND CAREFUL REVISION.

[3]: http://bioconductor.org/developers/how-to/efficient-code/

man

- the example sections should have code that illustrates how the function fowrk. For instance, the exmaple on arrayGenes.Rd 

    ```
    \examples{
    ##See vignette for more informations
    print("arrayGenes(path, outdir, filename)")
    }
    ```
    
  is not acceptable. Remember that examples and vignettes should ALWAYS write to temporary files `tempfile()` or directories `dir <- tempdir(); dir.create(dir)`

- pay attention to the output from examples. For instance, The example for `consistency.stats()` prints many hundreds of rows. Instead, capture to a variable and print `head(result)`.
- I have not looked at other man pages.
