### ISSUE TITLE
submitting BiocOncoTK

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#709]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/BiocOncoTK

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vjcitn** [comment]
It introduces new tools, specifically for working with pancancer-atlas.
However it might be worth
holding off on review at the moment.  I will get back to you.

**Comment by vjcitn** [comment]
On Wed, Apr 11, 2018 at 10:20 AM, vobencha <notifications@github.com> wrote:

> Hi Vince,
> Was this package intended to be a workflow? It's educational at the 'big
> picture' level but doesn't AFAICT introduce new functionality.
>
> The vignette shows how to perform multiple independent tasks but the
> outputs aren't necessarily used together in an analysis, i.e., towards
> common goal. This would be the usual trademark of a workflow.
>
I don't understand this comment.  The trademark of a workflow is to use
independent tasks towards a common goal.

This package collects together various as yet unavailable interfaces to
permit exploration of several
cancer bioinformatics projects.  It is not a workflow.

I plan to mature the vignette and the code this weekend and hope you will
review it like any other package.
Of course if time is too short then it can wait for the next release.


>
>
Just not sure what you had in mind here.

**Comment by vobencha** [comment]
Hi Vince,
All I meant by this comment https://github.com/Bioconductor/Contributions/issues/709#issuecomment-381230995 was to ask if this was a workflow or software package. Thanks for clarifying that it is software and not workflow.

The deadline for approving packages for BioC 3.7 is tomorrow, the 16th. Here are my comments:

- Add biocViews from 'Software' category:

    BiocCheck tries to determine package type by looking at the biocViews in DESCRIPTION. You have a single term 'CancerData' that appears in biocViews hierarchy under 'ExperimentData' package.

https://www.bioconductor.org/packages/release/BiocViews.html#___CancerData

  In the SPB output you can see BiocCheck does not think this is a software package vignette checks were skipped:
```
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 17 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    object (function)
   ...
   This is not a software package, skipping vignette checks...
```

  Please add some biocViews terms that appear under the 'Software' category:
https://www.bioconductor.org/packages/release/BiocViews.html#___Software

- Remove .utils.R.swp:
https://github.com/vjcitn/BiocOncoTK/blob/master/R/.utils.R.swp

- Function names are a mixture of underscores and camelCase.
- Data set names are a mixture of underscores, camelCase and dots.

**Comment by vjcitn** [comment]
looks like i missed this email and thus the deadline.  if this can go into
devel, fine.  the
concerns have been addressed with the possible exception of the camelCase
issue.

**Comment by vobencha** [comment]
I think a few more packages will be accepted into 3.7 - this might still be included.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BiocOncoTK\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocOncoTK

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
