### ISSUE TITLE
BiocMetaWorkflow

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/Contributions#711]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/grimbough/BiocMetaWorkflow

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by grimbough** [comment]
This is a workflow package version of a paper that has been accepted to F1000Research pre-print describing how to write a single R Markdown document and submit to both BioC and F1000.

**Comment by Liubuntu** [comment]
Hi @grimbough , 

Please wait for a day or two to see if the today2 build could be successful. The not building platform might be on our end. Thanks. 

Best,
Qiaqn

**Comment by Liubuntu** [comment]
Thanks for the update. Since it still fails the Tokay2 platform, so please send the list and I will talk with Bioconductor Core Team for any possible solution.

**Comment by grimbough** [comment]
Here's the list of packages included to use the F1000 style:

```
\usepackage{authblk}
\usepackage{babel}
\usepackage{inputenc}
\usepackage{fontenc}
\usepackage{mathdesign}
\usepackage{colortbl}
\usepackage{xcolor}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{setspace}
\usepackage{caption}
\usepackage{lastpage}
\usepackage{xifthen}
\usepackage{todonotes}
\usepackage{geometry}
```

Hopefully Tokay is just missing one of those.  It's not easy to debug deeper without being able to see the Latex log file.

**Comment by Liubuntu** [comment]
Hi @grimbough , 

Thank you for your contribution to Bioconductor workflows. We are working on the workflow package building issue on Tokay2 (Windows), and the Latex package list you have provided is very helpful.  

This is a very well written vignette that I have been actually learning rather than reviewing. Only several minor issue to fix before we add it to the new release. 

## DESCRIPTION

- Duplicate DESCRIPTION fields: `VignetteBuilder`

## Vignette

- Can you replace `raison d'être` with English words? e.g., "the main purpose of ..."

Cheers!
Qian

**Comment by Liubuntu** [comment]
Hi @grimbough , 

Thank you for the quick fix. I have talked with the core team member Lori about the workflow packages. And here are some points I may have missed in the previous comment, and these are raised by the newly updated workflow package guideline. 

1. BiocView terms. check [here](http://bioconductor.org/packages/devel/BiocViews.html#___Workflow)
   for the newly updated biocView terms. Toggle the box on upper left hand to see all biocViews terms. In this case, the "BasicWorkflow" would fit. Please modify in `DESCRIPTION` file accordingly.
2. Check here for updated [Workflow package guidelines](http://bioconductor.org/developers/how-to/workflows/). Especially in the `Consistent formatting` section, to make sure your output is  `BiocStyle::html_document` and add the versioning information with updated: `BiocInstaller::biocVersion()` in the template somewhere.   
This is more related to the `BiocWorkflowTools` package, the template output was by default `BiocWorkflowTools::f1000_article` in the template, is there a way to let the user choose if they want this or just an html for workflow packages? If you could make any changes in `BiocWorkflowTools` and modify it in this workflow vignette, these good new features will both be included in the new release for users. 
3. Lori is developing on a template  of workflow packages, she might be able to make use of your
   existing `BiocWorkflowTools` in the guidelines. If you have any questions or suggestions, please feel free to contact her @lshep .

Thanks!
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/grimbough.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BiocMetaWorkflow\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocMetaWorkflow

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by nturaga** [comment]
Please use the following link to [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/). The link listed in the previous message is deprecated.
