### ISSUE TITLE
mdp

### ISSUE THREAD

**Issue by csbl-usp** [Bioconductor/Contributions#712]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/csbl-usp/mdp/

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Here is the review of your package.  Please address the issues below and message me back when you're finished.

DESCRIPTION
- [CONSIDER] Add more biocViews terms if applicable.

.gitignore
- [REQUIRED] Place `mdp.Rproj` in `.gitignore`.

R/mdp.R
- [CONSIDER] Be specific with what classes are being input and output.  For
example, L15 it seems that the `pathways` param is asking for a `character`
bit there are packages like `rtracklayer` that have specific classes for files.
In general, it is advisable to be as specific as possible for the user.

- [CONSIDER] L58: Use `match.arg()` to improve style of function declaration.
For example, the parameter `measure` can have two values `"mean"` and
`"median"`. The parameter in the function declaration can be written as
`measure=c('mean', 'median')`.  The value that the user uses can be obtained
with `measure <- match.arg(measure)`.  The first value (in this case `mean`) is
the default argument. Using this method makes it clear to users what the allowed
inputs to a function are and may also make error catching easier. There are many
places in this function that you could use this.

- [REQUIRED] L112,115,134,143,578: Use `message()` instead of `print()` for
diagnostic messages.

- [REQUIRED] L361-372: Use `lapply()` instead of iteratively creating
`sample_results`.  This is more efficient:
```
sample_results <- lapply(seq_along(genesets), function(idx) {
    sample_scores <- colMeans(zscore[zscore$Symbol %in% genesets[[idx]],
                              2:ncol(zscore)])
    data.frame(Sample = names(sample_scores),
               Score = sample_scores,
               Class = pdata[names(sample_scores),
                             "Class"])
})
```

- [CONSIDER] L460: This line is formatted strangely, please remove the extra
spaces.

- [REQUIRED] L616-629: Use `vapply()` instead of inefficient copy and append
pattern to create `signal_noise`.  Replace with:
```
signal_noise <- vapply(seq_along(sample_results), function(idx) {
        sample_sub <- sample_results[[idx]]
        control_scores <- sample_sub[sample_sub$Sample %in% control_samples,
                                     "Score"]
        test_scores <- sample_sub[!(sample_sub$Sample %in% control_samples),
                                  "Score"]
        signal_noise[idx] <- (mean(test_scores) - mean(control_scores))/
                             (sd(test_scores) + sd(control_scores))
    }, numeric(1)
)
```

tests
- [CONSIDER] Add tests using the `testthat` package.

**Comment by melissalever** [comment]
Hi Daniel,

Thanks for reviewing the function and making improvements

I have addressed your suggestions and so let me know if anything more needs
to be done.

Best,

Melissa


DESCRIPTION

   - [CONSIDER] Add more biocViews terms if applicable.
   - done

.gitignore

   - [REQUIRED] Place mdp.Rproj in .gitignore.
   - done

R/mdp.R

   -

   [CONSIDER] Be specific with what classes are being input and output.
   -

   I defined pathways more clearly in the description
   -

   [CONSIDER] L58: Use match.arg() to improve style of function declaration.
   -

   I did this with c(''mean","median") in the mdp and compute_zscore
   functions, and
   -

    c("gene_score","gene_freq") in the compute_gene_score function
   -

   [REQUIRED] L112,115,134,143,578: Use message() instead of print() for
   -

   diagnostic messages.
   -

   Changed except for line 578 (now L615 and L631) these ones aren't
   diagnostic messages,
   -

   grid is using print to plot
   -

   [REQUIRED] L361-372: Use lapply() instead of iteratively creating
   sample_results. This is more efficient:
   -

   done
   -

   [CONSIDER] L460: This line is formatted strangely,
   -

   done


   -

   [REQUIRED] L616-629: Use vapply() instead of inefficient copy and append
   -

   done


   - [CONSIDER] Add tests using the testthat package
   - done

**Comment by dvantwisk** [comment]
Please perform a version bump.

**Comment by dvantwisk** [comment]
The changes look fine.  I'm going to move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/csbl-usp.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"mdp\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mdp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
