### ISSUE TITLE
RandomWalkRestartMH

### ISSUE THREAD

**Issue by alberto-valdeolivas** [Bioconductor/Contributions#717]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/alberto-valdeolivas/RandomWalkRestartMH

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
This seems like a general statistical method without dependencies on or use of Bioconductor; why not submit to CRAN instead? If you'd like to target Bioconductor, then update the user-visible functions so that they accept or return, as appropriate, [standard Bioconductor objects][1]. Please let me know if you do make this change by adding a brief comment. I will then add your package to the review queue.

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by alberto-valdeolivas** [comment]
Hello. Thanks for your answer. This package is based on an algorithm we developed for an article submitted to the Bioinformatics journal. They proposed us to deposite our software in Bioconductor, since the algorithm is dealing with a graph theory method applied to Bioinformatics. Therefore, to enable a wider audience to apply our methods, we developed this package in order to be more user friendly and generally applicable. 

I would still like to target Bioconductor, since our method is applied to Bioinformatics.

**Comment by alberto-valdeolivas** [comment]
Dear Martin,

We carefully checked the Bioconductor objects, but all the 4 packages (igraph, Matrix, dnet, methods) and objects we are using are either new or from CRAN. So, even if our package is dedicated to the bioinformatics community, to navigate biological multiplex networks, we do not see any way of using Bioconductor objects for input or output. If this is mandatory for Bioconductor, we unfortunately have to dismiss our submission.

Sincerely,

Alberto

**Comment by mtmorgan** [comment]
Thanks for submitting your package. Please revise according to the following and post a comment briefly summarizing changes when you are ready for a second review.

- please remove the the build/ directory from git; this is generated during the R CMD build process.

DESCRIPTION

- provide a Description: field that does not force the user to find the publication

vignette

- good

R

- AllFunctions.R:33 etc test class membership with `is(x, "Multiplex")`
- Avoid function names that can be confused for S3 methods -- `isMultiplex` or `is_Multiplex`; this is more than just a style issue.
- AllFunctions.R:156 consider `vapply()` rather than explicit for loop to avoid need to pre-allocate and fill. Similar issues for many `for ()` loops that populate lists or vectors to be replaced by `lapply()` or `vapply()`.
- AllFunctions.R:325 (and elswhere) vectorize as

    ```
    Layers_Name <- paste0("Layer_", seq_len(Number_of_Layers), ":")
    ```
- AllFunctions.R:330 adopt a style that allows for longer lines, e.g., new-line after `{`, consistent indentation by 4 spaces

    ```
    if (!is.character(Layers_Name)) {
        stop("The name of the layer should be a vector of characters")
    }
    ...
        Transition_Multiplex_SecondNet <- get.transition.multiplex.secondNet(
            N, L, M, SupraBipartiteMatrix, lambda
        )
        ## alternatively...
        Transition_Multiplex_SecondNet <- 
            get.transition.multiplex.secondNet(N, L, M, SupraBipartiteMatrix, lambda)
    ```
- Please spell-check documentation and error messages; one example AllFunctions.R:630 "The lenght" -> "The length"
- AllFunctions.R:751 Avoid 'copy-and-append' (`x <- character(); for (...) x <- c(x, ...)` which scales quadratically w/ vector size; pre-allcoate and fill or use `lst <- lapply(); x <- do.call(c, lst)`. See also use of `rbind()` at AllFunctions.R:1545
- AllFunctions.R:753 hoist vectorizable calculations out of for loops, e.g.,

    ```
    i <- seq_len(Number_Layers)
    Position_ini_row <- 1 + (i - 1) * Number_Nodes_1
    Position_end_row <- Number_Nodes_1 + (i - 1) * Number_Nodes_1
    for (i in seq_len(Number_Layers)) {
        ...
        idx <- seq(Position_ini_row[i], Position_end_row[i])
        Supra_Bipartite_Matrix[idx,] <- Bipartite_matrix
    }
    ```
- AllFunctions.R:892 use `message()` instead of `print()` for diagnositic / verbose output
- AllFunctions.R:938 it seems like this form 
    ```
        for (j in seq_len(Number_Nodes_secondNet)){
        if (Col_Sum_Bipartite[j] != 0){
            Transition_Multiplex_SecondNet[,j] <-
                (lambda*SupraBipartiteMatrix[,j]) /Col_Sum_Bipartite[j]
        }
    ```
  can be vectorized
    ```
      m <- lambda * t(t(Supra_Bipartite_Matrix) / Col_Sum_Bipartite)
      idx <- Col_Sum_Bipartite != 0
      Transition_Multiplex_SecondNet[,idx] = m[,idx]
    ```
  and similar elsewhere in the code
- use (internal) functions to avoid code repetition, e.g., the above transformation appears repeatedly in the `get.transition.*` functions.
- consider structuring your code into (a few) separate files with common functionality in each; structure the man pages and unit tests in similar fashion so that the user has easy access to related documentation / the relationshp between code / test / man is less of a hunt-and-search exercise.

man

- documentation is generally great!

NEWS

- should be parse-able by `utils::news()` and contain meaningful NEWS, otherwise delete.

**Comment by alberto-valdeolivas** [comment]
Dear Martin,

We carefully checked your comments and we reviewed our code according to them. In fact, your comments were very useful to improve the computational efficiency of our algorithms. Thanks very much.

I briefly summarize the changes:

- We spell-check documentation, vignette and error messages. We removed unused files and directories.

- We provide a link to the related publication in the **DESCRIPTION FILE**.

**R code**

- We replaced `for ()` loops by `apply` or `do.call` functions. In addition, we applied vectorization in some cases following your recommendations. Just a couple of `for ()` loops remain in our code, since we think they can ease future modifications or user's understanding. 

- We replaced some potentially confusing names for S3 methods, and we tested class membership in the way you proposed.

- We replaced `print()` by `message()` for verbose output.

- We structured our code into different files with related functionality and according the unitary test files.

Therefore, we consider to be ready for a second review.

Sincerely,

Alberto

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alberto-valdeolivas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"RandomWalkRestartMH\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RandomWalkRestartMH

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
