### ISSUE TITLE
icetea

### ISSUE THREAD

**Issue by vivekbhr** [Bioconductor/Contributions#719]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vivekbhr/icetea

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vobencha** [comment]
Sorry for the delay on this. I'll get you a review tomorrow.
Valerie

**Comment by vivekbhr** [comment]
Thanks for the review Valerie. I would try to fix them soon

**Comment by vivekbhr** [comment]
@vobencha Thanks for the review. Here are some changes I made so far :

**package name**

I modified the description to add what icetea stands for. (**I**ntegrating **C**ap **E**nrichment with **T**ranscript **E**xpression **A**nalysis)

**Please remove LazyData = true. **


DONE

**non-exported functions**

I improved description of ResizeReads and other non-exported functions. I don't need the man pages but I would like to keep the roxygen style comments in the code so I end up generating them.

I want to keep the function `ResizeReads` since 1) I use this multiple times in the package. 2) we are thinking of using the package for iCLIP analysis in future, where the users would like to have the signal from the end or the middle of the reads.

**newCapSet class**

The purpose in my mind when creating the class was to use a container for all file paths (fastq and BAMs) along with mapping statistics, also to make it easy to check certain assumptions and fail early in the analysis.

I tried using `RangedSummarizedExperiment`, but I am not able to use any of its functionality. In principle, I could fit my sampleInfo `DataFrame` as `colData` and other information as `metadata` in the SE object. But the former throws an error (due to no `assay` column) and the latter requires me to skip the validity checks. Would appreciate any suggestions here.


**imports / exports**
I added atleast one import from each package into namespace (through roxygen directive `@importfrom` ), but I have still not listed all required functions there since that would mean removing all my  `package::function` syntax from the code. I want to keep the `package::function` syntax in my code to : 1. avoid a function masking another 2. it's easier for me to come back after years and find which function came from which package. I could still add all imports for each of my functions through roxygen if this is absolutely required.

**R file names**

DONE

**Comment by vivekbhr** [comment]
My build is passing on all platforms through [appveyor](https://ci.appveyor.com/project/vivekbhr/icetea/branch/master) and [travis](https://travis-ci.org/vivekbhr/icetea) . Can someone point out the issue here? (I already tried listing the .gitattributes file in .Rbuildignore)

**Comment by vivekbhr** [comment]
@vobencha I have fixed all issues with the build errors except the error with RSubread on windows. Please have a look at my replies above and let me know if additional changes are required.

Best,
Vivek

**Comment by vobencha** [comment]
Thanks for making the changes. 

If you want to keep RSubread in Suggests you'll need to add a .BBSoptions file as described by Herve in 
https://stat.ethz.ch/pipermail/bioc-devel/2018-May/013667.html
This file should go at the same level at R/ man/ etc.

Valerie

**Comment by vivekbhr** [comment]
@vobencha It's there already. It's just not being recognized by the build system at the moment.

**Comment by vobencha** [comment]
Yes, I know the SPB does not recognize this option and the error will persist until the package is built on the formal build system. I had missed the file in the github repo when I looked for it last time. Thanks for adding it.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vivekbhr.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"icetea\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/icetea

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
