### ISSUE TITLE
MetaGxPancreas

### ISSUE THREAD

**Issue by mzon7** [Bioconductor/Contributions#721]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/MetaGxPancreas

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
A few minor comments:


**General**
- [ ] Please update the BiocViews to be from the [ExperimentData section and subsections]( http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData)

**Man**
Can you include in the example how to get the details on the data object creation: 
i.e 
```
experimentData(esets$BADEA)
```

**Coding**
- [ ] You don't need paste inside message calls, message does a paste automatically with `sep = "" `
i.e  one example from code but should be applied to all: 
``` 
message(paste("excluding ",
                    "(minNumberEvents or minSampleSize)"))

#  and just be 
message("excluding ",
                "(minNumberEvents or minSampleSize)")
```
This is also true for object with character representation:
```
message(paste("including experiment hub dataset",pancreasData[i]$title))
# can be
message("including experiment hub dataset ", pancreasData[i]$title)
```
- [ ]   Check for loops for vectorization  - at the very least this last one can be vectorized more 
```
 for (i in ids.with.missing.data) {
     Biobase::exprs(esets[[i]]) = impute::impute.knn(Biobase::exprs(esets[[i]]))$data
 }

#  quick example

temp = list(matrix(rnorm(12), nrow=3), matrix(rnorm(12), nrow=3), matrix(rnorm(12), nrow=3))
funFunc <- function(i, m){  abs(m[[i]])}
idx = c(1,3)
temp[idx] = lapply(idx, FUN=funFunc, m=temp)
```

Cheers

**Comment by lshep** [comment]
Looking into this -  hopefully will kick off a build manually on our end - sorry for the trouble

**Comment by lshep** [comment]
Sorry for the noise - looking into it

**Comment by mzon7** [comment]
Hi Lori,

Thanks for fixing the naming issue with the data sets on the hub yesterday. I have updated all the man files to include how to get the experiment data and fixed the BiocViews. I decided not to vectorize the impute.knn code as I was having some trouble since the right side cannot be a list as is the case in the example you provided. I do think that any vectorized solution will be longer than the 1 line currently there as it will require replacing the esets with new esets, which sometimes raises problems as well based on the way the eSet class is setup with locked environments . However, I did vectorize the loading of the dataset from the hub with an lapply that saved about 5 lines. Hope this will suffice, if not let me know.

Best,
Michael

**Comment by lshep** [comment]
Looks like that change may have broken the function  - if you would like to revert it it isn't essential - all the other changes to the man files and the message calls look good.

**Comment by mzon7** [comment]
Looks like it was just a spelling mistake in one of the man files, should be resolved now.

**Comment by lshep** [comment]
That ERROR is on us.  Looks good.

**Comment by mzon7** [comment]
Seems that the addition of the example to the man files has caused an error due to the fact that on windows it takes more than 5 seconds to run (but not on Mac). Should I remove the examples?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mzon7.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MetaGxPancreas\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaGxPancreas

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
