### ISSUE TITLE
maser

### ISSUE THREAD

**Issue by DiogoVeiga** [Bioconductor/Contributions#722]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DiogoVeiga/maser

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by DiogoVeiga** [comment]
The error seems to be related to AnnotationHub. I use AnnotationHub to demonstrate the package in the vignettes. If it persists, I will change the examples in the vignettes.

failed to load resource
  name: AH51014
  title: Homo_sapiens.GRCh38.85.gtf
  reason: invalid class "GRanges" object: 'seqnames(x)' contains missing values

[https://support.bioconductor.org/p/101614/](https://support.bioconductor.org/p/101614/)

**Comment by dvantwisk** [comment]
Here's a review of the package.  Please address the following issues and message me back once you've finished.  I don't test code that I've written so I can't guarantee everything is completely correct.

LICENSE
- [REQUIRED] The license file isn't the MIT license. Get it here:
https://opensource.org/licenses/MIT

.gitignore
- [REQUIRED] Add `maser.Rproj` to your `.gitignore`.

GENERAL
- [REQUIRED] Your repository is 12MB and we want to see repositories smaller
than 5MB.  The `.git` file is 9.2MB which leads me to believe that in somepoint
of the development process, you commited some larger files, but later deleted
them. I would recommend using BFG cleaner to remove these large files from your
git history https://rtyley.github.io/bfg-repo-cleaner/.

R/GENERAL
- [REQUIRED] Explicitly import symbols from packages. For example,
`annotationTracks.R`L67: `dplyr::filter()` is being invoked here. Please include
the `Roxygen2` header `@importFrom` so that `importFrom(dplyr, filter)` is
included in the `NAMESPACE`.

R/annotationTracks.R
- [REQUIRED] There are multiple functions `createAnnotationTrack*_transcripts()`
that seem to be very similar. Create a function that invokes the repeated code
and call it in this functions instead of repeating code multiple times.
The `createPSITTrack*_event` class of functions seem to have the same issue; 
reuse code here too.

- [REQUIRED] L462, 481-504: Use `lapply()` to create `uniprotTrack` instead of
inefficiently creating it using an iterative method.
```
uniprotTracks <- lapply(seq_along(tables_uniprot), function(i) {
    ...
    (end function by returning "track")
}
```

- [REQUIRED] L512-541: Same as above; use `lapply()`.

R/filterEvents.R
- [REQUIRED] L109-115: Use lapply() to declare `grl_new`:
```
grl_new <- lapply(grl, function(exon) {
    exon[exon$ID %in% res_id,]
})
```

- [REQUIRED] L144-276: Code here is repeated from previious function. Create
function for repeated code and invoke from there.

- [REQUIRED] Avoid inefficient copy and append pattern to create `event_counts`:
```
event_counts <- vapply(as_types, function(type) {
        annot <- events[[paste0(type,"_","events")]]
        resAnnot <- dplyr::filter(annot, geneSymbol %in% geneS)
        length(resAnnot$ID)
    }, numeric(1)
)
```

R/mappingEvents.R
- [CONSIDER] L51: Use `match.arg()` to improve style of function declaration.
For example, the parameter `by` can have two values `"feature"` and
`"category"`. The parameter in the function declaration can be
written as `by=c("feature", "category")`. The value that
the user uses can be obtained with `by <- match.arg(by)`. The
first value (in this case `"feature"`) is the default argument. Using this
method makes it clear to users what the allowed inputs to a function are and may
also make error catching easier. There are many places in this package that you
could use this.

- [REQUIRED] L84-87: Replace inefficient iteration with:
```
features_Gr <- lapply(seq_along(features), createGRangesUniprotKBtrack)
features_Gr <- GRangesList(features_Gr)
```

- [REQUIRED] L149-156: Remove `unipKB_id`; delcare `enst_trans` with:
```
enst_trans <- vapply(seq_along(aus), function(i) tokens[[i]][[1]], character(1))
```

- [REQUIRED] L169-202: Use `lapply()` as stated previously.
- [REQUIRED] L181-194: Replace inefficient copy and append pattern with `vapply()`
as shown previously.

- [REQUIRED] L306-386: Use `lapply()` to create `events_with_txn`.
- [REQUIRED] L320-378: Use `vapply()` to create `list_txn_a` and `list_txn_b`.

- [REQUIRED] L394-708: All these functions seem to have a lot of repitition.
Correct this as described previously.

R/maser.R
- [REQUIRED] L1-184: There appears to be repeated code in these functions.
Correct this as described previously.

- [REQURIED] L243-250: Replace with:
```
reads.mat <- cbind(as.numeric(unlist(inc1), as.numeric(unlist(inc2)))
```

- [REQUIRED] L264-272: Same as above.

- [REQUIRED] L323-333: Remove `counts`, use `lapply()` to create `total` and
`line_events`.

- [REQUIRED] L382-383, L388-391: create `PSI_*` using `vapply()`.
- [REQUIRED] L393, L398-403: create `exon_df` using `lapply()` then `cbind()`.

R/plotEvents.R
- [REQUIRED] L80-81, 89-98: use `vapply()` to create `nevents_cond*`.

- [REQUIRED] L374-378: Create `geneList` using `lapply()` then `unlist()`.
- [REQUIRED] L381-385: Create `geneList_counts` using `lapply()` then `rbind()`.

R/plotGeneEvents.R
- [REQUIRED] L354-357: Use `lapply()` than `GRangesList()` to create `eventGr`.

R/queryUniprotKB.R
- [REQUIRED] L21-28: Declare `name` using vapply() as shown previously. 
- [REQUIRED] L54-71: Declare `track_df` using `lapply` as shown previously. Then
use `rbind()` on resulting list to create `data.frame`.

- [REQUIRED] L109-132: Use `lapply()` then `rbind()` to create `track_df`.

R/sysdata.rda
- [REQUIRED] Is this file necessary? If not, remove it.

tests
- [CONSIDER] Add `tests` using the `testthat` package.

vignettes
- [REQUIRED] Your vignettes contain multiple `eval=FALSE`'s. We don't allow
these on code that the user must have access to (we expect the code displayed in
vignettes to function for the user, so it should be ran on build). I am assuming
that maybe these were placed there to reduce build time to avoid timeout's. If
this is the case, we ask that either the examples in the vignette be scaled down
or code simplified to avoid these timeouts instead of using `eval=FALSE`.

**Comment by mtmorgan** [comment]
actually, R includes text for several license files so these do not need to be included, as per [Writing R Extensions][1]

[1]: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing

```
> dir(R.home("share/licenses"))
 [1] "AGPL-3"       "Artistic-2.0" "BSD_2_clause" "BSD_3_clause" "GPL-2"       
 [6] "GPL-3"        "LGPL-2"       "LGPL-2.1"     "LGPL-3"       "license.db"  
[11] "MIT"       
```

For MIT, one does require a LICENSE file with YEAR and COPYRIGHT HOLDER , but obviously "Your name here" (as in the current LICENSE file in maser) is not appropriate.

**Comment by DiogoVeiga** [comment]
Hi  @dvantwisk , @mtmorgan 

After I made the modifications asked in the review process, the check time in Windows machine is around 6min, while in the OSX and Linux are all okay (<=4min). Not sure why this is happening, since previous versions checked ok in Windows. 

Could you suggest how to decrease the check time on Windows?
Thank you

**Comment by dvantwisk** [comment]
We recently added this warning that is coming up to our build machines.  Since it is not running over-time on our other machines, we can ignore it.  I'll have a look at your changes soon.

**Comment by DiogoVeiga** [comment]
Hi @dvantwisk 
I have created a new version of the package which makes use the S4 class system. Please see details below. Thank you.

[Response to Reviewer Round 2.docx](https://github.com/Bioconductor/Contributions/files/1968064/Response.to.Reviewer.Round.2.docx)

**Comment by dvantwisk** [comment]
I've looked over the changes.  A lot of it looks great but the following still need to be done to the maser.R file:

- The coercion functions need to be written as follows (e.g. for `as.list`):
```
.maser_to_list <- function(x) {
  mapply(function(y) {
    #apply as.list if the slot is again an user-defined object
    #therefore, as.list gets applied recursively
    if (inherits(slot(x,y),"Maser")) {
      as.list(slot(x,y))
    } else {
      #otherwise just return the slot
      slot(x,y)
    }
  },
  slotNames(class(x)),
  SIMPLIFY=FALSE)
})

setAs("Maser", "list", .maser_to_list)
```
No generic is needed.  Coercion occurs when a `Maser` object, `m`, has `as()` called on it such that `li <- as(m, "list")`.  `li` is the converted list object.

- The "getter" methods should reuse existing s4 generic where possible and should be declared with `setMethod()`. 
  - `PSI` of something similar doesn't appear to be present in any other packages, so you should create your own generic for this one.
  - `counts` is a generic available from the `DESeq2` package, import the generic from there.
  - `annotation` can be used in place of `annot`, import the generic from the `BiocGenerics` package.
  - `stats` sounds like a very "generic" name for a generic and shouldn't be declared here, however, `stats` doesn't appear to be set anywhere.  Could you use the `summary` generic available from the `base` package?
  -  `granges` can be used in place of `gr`, import the generic from the `GenomicRanges` package.

**Comment by DiogoVeiga** [comment]
Hi @dvantwisk 
I've made the changes you requested, please see details below. Thank you.
[Response to Reviewer Round 3.docx](https://github.com/Bioconductor/Contributions/files/1978459/Response.to.Reviewer.Round.3.docx)

**Comment by DiogoVeiga** [comment]
Hi @dvantwisk 
I removed the check `is(object, "Maser)` in S4 methods, and changed to use `match.arg(type)` in all methods. Thanks.

**Comment by dvantwisk** [comment]
Great!  I have nothing more to suggest, so I am going to move to accept the package now.

**Comment by DiogoVeiga** [comment]
Hi @dvantwisk 
I appreciate very much your review that made the code much better! And I learnt a lot through the process as well. All the best. Thank you.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DiogoVeiga.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"maser\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/maser

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
