### ISSUE TITLE
(inactive) Hapi

### ISSUE THREAD

**Issue by Jialab-UCR** [Bioconductor/Contributions#725]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jialab-UCR/Hapi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package will be reviewed by a core team member. Note however that you must modify your package to interoperate with other Bioconductor packages, especially modifying input / outputs of your user-facing functions to work with [standard Bioconductor classes][1] especially from the [GenomicRanges][2] (_GRanges_, _GPos_) and [SummarizedExpermient][3] packages.

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/devel/GenomicRanges
[3]: https://bioconductor.org/packages/devel/SummarizedExperiment

**Comment by mtmorgan** [comment]
Sorry for the delay in reviewing your package. I think your package requires a lot of work. It should use the [GenomicRanges][] infrastructure, and the code needs to be 'vectorized' rather than using iteration (`for`, `lappy()`, `apply()`). I have started to provide some indication of the required revisions below, but the list is far from exhaustive.

DESCRIPTION

- Consider using Authors@R rather than Author: and Maintainer: to more accurately convey contributinos of each author.

- R is distributed with copies of licenses, so the LICENSE file is not required.

vignettes

- Please remove index.Rmd.

- Update the installation instructions assuming acceptance to Bioconductor, i.e., `source("https://bioconductor.org/biocLite.R"); biocLite("Hapi")`

- Vignette looks good!

R

- many of these calculations appear to be range-based, and should be using the [IRanges][] or [GenomicRanges][] infrastructure for efficient vectorized computation. `gmt` would seem to be a perfect candidate for representation as a GRanges object, with your software using `rtracklayer::import()` to read the gmt file. See [rtracklayer][].

[IRanges]: https://bioconductor.org/packages/devel/IRanges
[GenomicRanges]: https://bioconductor.org/packages/devel/GenomicRanges
[rtracklayer]: https://bioconductor.org/packages/devel/rtracklayer

- Carefully review all code for opportunities for vectorization, even if only partial. For instance

    ```
        filter <- c()
    for (i in 1:ncol(haps)) {
        iden <- haps[,1] == hap
        ratio.t <- sum(iden==TRUE, na.rm=TRUE)/sum(!is.na(iden))
        if (ratio.t < consistencyThresh) {
            filter <- c(filter, i)
        ...
    ```
    
  is (I think)

    ```
    ratio.t <- colSums(haps) / colSums(!is.na(hap))
    filter <- ratio.t[ ratio.t < consistencyThresh ]
    ```
    
  Vectorize all functions, then see if the functions called in outer loops, e.g., assembly.R:52 `hapInferFun()`, assembly.R:73 `alleleDetermineFun()` can be re-written to operate on vectors, so that the `apply()` iteration is not requried.

- For more robust code, start each function exposed to the user with assertions (e.g., via `stopifnot()`) to test that the inputs are consistent with the expectaions of the function, e.g., `hapiAssemble()` has `gmt` a data.frame, presumably with specific columns with specific type (these should be specified in the documentation), so

    ```
    stopifnot(
        is.data.frame(gmt),
        is.numeric(gmt$...),
        ...
    )
    ```
    
- e.g., assembly.R:54 avoid 'copy and append' in favor of '[pre-allocate and fill][1]'

[1]: http://bioconductor.org/developers/how-to/efficient-code/

- use robust `seq_len()` or `seq_along()` instead of `1:...`, e.g., assembly.R:213.

- `message()`, `warning()`, `stop()` all `paste0()` their arguments, so

    ```
    message (paste('Warning: bad consistence between draft haplotype 
        and', colnames(haps)[i], ': ', ratio.t, '\n', sep=''))
    ```
    
  is simply

    ```
    message ('Warning: bad consistence between draft haplotype and ', 
        colnames(haps)[i], ': ', ratio.t)
    ```
    
  It is not generally necessary to append `"\n"` to `message()` text, e.g., assembly.R:401.

- define and use variables and functions rather than repeating code, e.g., a trivial example is `idx <- seq(start, end); ... newHap[idx] <-  gmt[idx]` (assembly.R:221, but this code looks like it can be vectorized).

- avoid unused calcualteiosn, e.g., `naPos`, assembly.R:218

- The comments above apply to ALL files.

man

- describe return values more fully, e.g., "a dataframe containing phased haplotypes" (assembly.R:96) should indicate the columns and their values. This is especially important because it appears you make extensive use of crytpic abbrevations to indicate state. Be careful to use correct R terminology (e.g., "data.frame", not "dataframe").

tests

- it's nice that you have started to implement tests, but the test suite needs to be greatly expanded if it is to be effective.

NEWS

- format so that `utils::news()` parses this file. Make sure the NEWS contains, and continues to contain as you update your package, relevant information.

**Comment by mtmorgan** [comment]
@Jialab-UCR I hope you'll have a chance to work on this. Post a short comment if you will not be able to get to this within the next two weeks.

**Comment by Jialab-UCR** [comment]
@mtmorgan Hi Martin, really sorry for the late response. I have just completed the dissertation defense and will work on this as soon as possible. Thanks. Sorry again
