### ISSUE TITLE
CAMTHC

### ISSUE THREAD

**Issue by Lululuella** [Bioconductor/Contributions#726]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Lululuella/CAMTHC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your interest in Bioconductor.  Please see the following comments


**README:**
- [ ] typos in readme:  ie. comoputational
- [ ] update to have Bioconductor installation instructions
```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("CAMTHC")
```

**General:** 
- [ ] Please `git rm` CAMTHC.Rproj   If you would like to keep this file locally in the future please add to
.gitignore

 
**Vignette/R code:**
- [ ] Your main function should also work with standard [Bioconductor objects](http://bioconductor.org/developers/how-to/commonMethodsAndClasses/) for gene expression data, proteomics data and DNA methylation data. - Ideally take the Bioconductor object as input and coerace to needed format for you function - this could be in your main function or provide wrapper functions for the Bioconductor object

- [ ] You also define many S3 internal classes that become values in the object you return from your main function (MDLObj, CAMPrepObj, CAMASObj, CAMMGObj) .  These should be converted to S4 classes and provide accessor methods for getting and setting values.   The output of your main CAM function should also be converted into an S4 object with associated getter accessor methods rather than a generic list with obscure accessing through `$` and `[`.  Not only would this clean up and better define the output, but the accessor methods would get rid of messy and undescriptive code like 
```
Aest <- rCAM$ASestResult$'3'$Aest
Sest <- rCAM$ASestResult$'3'$Sest
# or 
m <- which(names(rCAM$ASestResult) == '3')
Aest <- rCAM$ASestResult[[m]]$Aest
Sest <- rCAM$ASestResult[[m]]$Sest
```
could have an accessor method  of `Aest` and `Sest` 

- [ ] In your vignette, In your lapply's  - 1:n should also use use seq_len()  
i.e  `1:3` should be `seq_len(3)`

- [ ] Case Study section is Excellent! We like showing it can be used with Bioconductor object - 
However - instead of having the user perform these can you create a wrapper around the object to be used with the main function. 


Please address these issue. When ready for a re-review please perform a version bump to kick off a new build and comment here with how the code has been updated.  

Cheers
Lori

**Comment by lshep** [comment]
Hello.  Just wanted to check it to see if you had any questions or when we might expect to see updates.  If there is no response within two weeks we will close the issue for inactivity and you can reopen the issue when you can work on updates.

**Comment by Lululuella** [comment]
Hello,

Sorry for being late. Do I still have time to update the software this
week? Thanks a lot!

Best,
Lulu

**Comment by lshep** [comment]
Of course!  We just want to make sure that there is forward moving progress.  When you are ready for a re-review please make sure there is a version bump in the DESCRIPTION file to kick off a new build and please comment back here with what has been updated.  
Cheers!

**Comment by Lululuella** [comment]
Hello, do I need to update my current R and bioconductor version?

**Comment by lshep** [comment]
I'm unsure what you mean by update -   Your R version in your description is R >= 3.5 which is the version of R we are currently using. 
If you want to test locally - the versions we are using to test your package are Bioc 3.8  and R 3.5.0

**Comment by Lululuella** [comment]
Hello, I update my package following your suggestion.  Objects returned from main functions are converted to S4 classes with some useful accessor methods. Input expression data could be SummarizedExperiment and ExpressionSet object. The second Case Study used ExpressionSet type as input. Please review it again. Thanks a lot!

**Comment by lshep** [comment]
Hi.  Looking much better thank you for making the switch to S4 -  some minor clean up:

**NEWS**
- [ ] NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
       If the NEWS file is in inst please remove the md extension (but can still
       be written in markdown)
- [ ] Formating.  Please change the title of the section from 
    # CAMTHC 0.99.0  to Changes in verison 0.99.0

**DESCRIPTION**
- [ ] Remove LazyData: true. This rarely proves to be a good thing. In our
experience it only slows down the loading of packages with large data

Please make the above changes and do another version bump for a new build.

**Comment by Lululuella** [comment]
Hi, I have a new warning: "Remove set.seed usage in R code".  I use the seed to reproduce the same result.  Now it is not encouraged? Do you have any suggestion?

**Comment by lshep** [comment]
It is encouraged but normally we encourage its use outside of R code - for example set.seed in the examples or vignette before running an R function -  I looked at your code at it seems you set the seed by argument, and if the seed is not specified than it is not used - is that correct?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Lululuella.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CAMTHC\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CAMTHC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Lululuella** [comment]
Hi, my package's "devel" builds failed in windows:  .onLoad failed in loadNamespace() for 'rJava'. This problem did not exist in previous check. Could anyone help me to fix this problem?

**Comment by lshep** [comment]
Please post to the bioc-devel@r-project.org  for questions on the daily builders and how to resolve ERRORs -  Cheers
