### ISSUE TITLE
onlineFDR

### ISSUE THREAD

**Issue by dsrobertson** [Bioconductor/Contributions#727]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dsrobertson/onlineFDR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
# 5 May, 2018

Thank you for your package. There seem to be a number of opportunities throughout the code to 'vectorize' (comment on LORD.R:134, below) and to more efficiently process groups of data.frame rows (bonfInfinite.R:122, below). Please apply the comments to your entire code base, and post a comment here when revisions are ready for a second review.

DESCRIPTION

- good

vignette

- Good
- Replace `date: ` with a static date representing the last revised (rather than last compiled) date.

R

- bonfInfinite.R:122. updating data.frame rows by group is generally more efficiently done with `ave()` (see the implementation for additional flexiblity), `aggregate()`, or generally the 'split, apply (e.g., `lst = lapply(split(...), ...)`), combine (e.g., `do.call(lst)`)' paradigm.

- e.g., LOND.R:134, vectorize where possible

    ```
    den <- cumsum(1 / seq_len(N))
    beta <- beta / den
    ```

- bonfInfinite.R:110 and elsewhere. Avoid `1:N` in favor of `seq_len(N)` (also `seq_along(v)`) for more robust code (e.g., when `N == 0`).

- watch for consistent formatting & indentation, e.g., LORDdep.R:142 should be indented.

- LORDdep.R:140 Do not use `set.seed()` internally; code should be robust to random number state.

man

- good!

NEWS

- please format for parsing by `utils::news()`.

- Only need 1 copy of NEWS (top-level or inst/).

tests

- it can be very valuable to test simple edge cases, e.g., zero-length inputs.

**Comment by dsrobertson** [comment]
Thank you for taking the time to review our package, and for your helpful suggestions. We have tried to address all of your points above, and the comments below give some further explanations of the changes:

R code

- The updating of data.frame rows by group now uses the ‘split-apply-combine’ paradigm instead of `for` loops. We have also implemented your suggested vectorisation of LOND.R:134. The remaining `for` loops in the R code are necessary given the fully sequential manner of the procedures, as well as to aid user’s understanding.

- Regarding using `set.seed()` internally, the rationale for doing so was to ensure that p-values within the same batch are randomised while still maintaining the reproducibility of the results within the workflow of a growing dataset. From the vignette: “For simplicity, as the dataset grows the new larger dataset should be passed to the wrapper function and the values recalculated … Note that the randomisation of the data within the previous batches will remain the same to allow for reproducibility of the results.”

- However, we have changed the implementation so that we save the current `.Random.seed` state from the global environment (if it exists) and restore it at the end of the function (which does involve a global reassignment of `.Random.seed` as a result). This should now make the code robust to the random number state in the sense that (for example)
`LORD(sample.df); rnorm(10)`
`set.seed(100); LORD(sample.df); rnorm(10)`
would both produce the expected behaviour for `rnorm(10)`. We are of course open to other suggestions on how to implement this feature.

tests

- We have added a number of additional tests for simple edge cases (i.e. zero-length inputs and inputs of length one).

**Comment by mtmorgan** [comment]
Thank you for your changes.

- With respect to the random number seed, I'm not sure that I follow. If I comment out your code setting the random number seed, then 

    ```
    > set.seed(100); x0 <- LORD(sample.df); rnorm(10)
     [1]  0.4372134 -0.3650827  0.4966740  0.5557346  0.6712590 -0.9485679
     [7]  1.1848094 -0.5896169  1.4647474  1.6865777
    > set.seed(100); x1 <- LORD(sample.df); rnorm(10)
     [1]  0.4372134 -0.3650827  0.4966740  0.5557346  0.6712590 -0.9485679
     [7]  1.1848094 -0.5896169  1.4647474  1.6865777
    > identical(x0, x1)
    [1] TRUE
    ```
    
  so all that is required for reproducibility is for the user to set the random number seed? This is the preferred approach, documented as appropriate.
  
- for what it's worth, it's usually more efficient to split only the essential information for a calculation, rather than the entire data frame, e.g., the row indexes

    ```
    f0 <- function(d) {
        lst <- lapply(split(d, d$date),
                function(x){x[sample.int(length(x$date)),]})
        ## set.seed(1)
    
        d <- do.call('rbind', lst)
        rownames(d) <- NULL
        d
    }
    
    f1 <- function(d) {
        lst <- lapply(split(seq_len(nrow(d)), d$date), function(x) {
            x[sample.int(length(x))]
        })
        d <- d[unlist(lst, use.names = FALSE),]
        rownames(d) <- NULL
        d
    }
    
    f2 <- function(d) {
        ## more idiomatic
        i <- ave(seq_len(nrow(d)), d$date, FUN = function(x) {
            x[sample.int(length(x))]
        })
        d <- d[i,]
        rownames(d) <- NULL
        d
    }
    ```
    
  leading to
  
    ```
    > identical({ set.seed(123); f0(sample.df) }, { set.seed(123); f1(sample.df) })
    [1] TRUE
    > identical({ set.seed(123); f0(sample.df) }, { set.seed(123); f2(sample.df) })
    [1] TRUE
    > microbenchmark(f0(sample.df), f1(sample.df), f2(sample.df), times=10)
    Unit: microseconds
              expr      min       lq      mean    median       uq      max neval
     f0(sample.df) 2318.877 2352.171 2439.8202 2391.9720 2435.573 2717.983    10
     f1(sample.df)  520.809  526.954  537.9477  528.4875  540.628  575.603    10
     f2(sample.df)  596.682  601.327  627.0121  616.6280  651.558  678.583    10
    ```
    
  Regardless of implementation, this should be a helper function used by LORD, LORDdep, LOND, and bonfInfinite rather than replicated in four different locations.

**Comment by dsrobertson** [comment]
Thank you for your comments. We have removed the code setting a random number seed, and updated the documentation. The randomisation is now implemented via a helper function `randBatch`, which is used by LORD, LORDdep, LOND and bonfInfinite. We have also implemented your suggested function `f1` as part of `randBatch`.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dsrobertson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"onlineFDR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/onlineFDR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
