### ISSUE TITLE
GeneAccord

### ISSUE THREAD

**Issue by arhofman** [Bioconductor/Contributions#730]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbg-ethz/GeneAccord

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
Hi @arhofman 

Please correct all the issues in your build report before we proceed and I take a look at your package and review it. 

[REQUIRED]
```
* Checking coding practice...
     * NOTE: Avoid sapply(); use vapply() found in files:
       data_handling_functions.R (line 116, column 19)
       data_handling_functions.R (line 608, column 21)
       data_handling_functions.R (line 689, column 17)
       data_handling_functions.R (line 693, column 27)
       data_handling_functions.R (line 777, column 26)
       databases_handling_functions.R (line 249, column 25)
       sim_functions.R (line 365, column 25)
       stats_functions.R (line 263, column 32)
     * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
       databases_handling_functions.R (line 113, column 17)
       plot_functions.R (line 461, column 29)
     * WARNING: Use TRUE/FALSE instead of T/F
       Found in files:
         inst/extdata/prepare_patient_data_all.R

 * Checking for bioc-devel mailing list subscription...
     * NOTE: Cannot determine whether maintainer is subscribed to the
       bioc-devel mailing list (requires admin credentials).  Subscribe
       here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

 * NOTE: Consider shorter lines; 1185 lines (23%) are > 80
      characters long.
    First 6 lines:
      R/data_handling_functions.R:1 #' Creates a tibble containing the inform...
      R/data_handling_functions.R:3 #' It expects a comma-separated table whe...
      R/data_handling_functions.R:4 #' or pathway. The other columns are for ...
      R/data_handling_functions.R:7 #' The table is expected to be comma-sepa...
      R/data_handling_functions.R:8 #' ..., 'cloneN', depending on how many c...
      R/data_handling_functions.R:9 #' in the first column the name of the mu...
    * NOTE: Consider multiples of 4 spaces for line indents, 1578
      lines(30%) are not.
    First 6 lines:
      R/data_handling_functions.R:28   stopifnot(is.character(path_to_file))
      R/data_handling_functions.R:29   stopifnot(is.numeric(max_num_clones))
      R/data_handling_functions.R:30   stopifnot(file.exists(path_to_file))
      R/data_handling_functions.R:32   message(paste("Found the file ", path_...
      R/data_handling_functions.R:34   # create tibble
      R/data_handling_functions.R:35   fn <- path_to_file
```

 See http://bioconductor.org/developers/how-to/coding-style/


Your summary says you have a lot of issues in your build report please fix them. There should be no warnings, and as few notes as possible.

```
Summary:
 ERROR count: 0
 WARNING count: 1
 NOTE count: 6
```

**Comment by arhofman** [comment]
Hi @nturaga 

Thank you for your message. I tried to address all notes and warnings. Specifically, I implemented the following changes:
- sapply to vapply or lapply
- 1:... to seq(1, ...)
- T/F to TRUE/FALSE
- shortened the lines and tried to be < 80 characters
- have indents of multiples of four spaces
- I am subscribed to the bioc-devel mailing list

Thanks a lot for reviewing my this package!
Best regards,
@arhofman

**Comment by nturaga** [comment]
## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION
ok

## NAMESPACE 

ok

## R

* There is no need to call `paste0` when you are trying to write a
  `message` or a `warning`. Both `message` and `warning` will
  automatically concatenate your string with a variable. This has been
  done in multiple places, and needs to be corrected.
  
  Using `paste0` or `paste` is only a good idea when the variable is a
  vector.
  
* Remove commented out code.

* use `seq_len` instead of `seq` in data_handling_functions.R, L56.

		for(i in seq_len(num_clones))
		
	instead of

	    for(i in seq(1, num_clones))


	Do this everywhere `seq` is being used. You can also take a look
    at `seq_along` wherever appropriate.
	
* The code chunk from L770 in data_handling_functions.R, which sets
  the variable, `merged_ents_clone_tbl_list` needs to be
  simplified. You use for loops within an `lapply` making it a nested
  for loop. There are operations in this set that can be vectorized.
  
  This nesting is done again in databases_handling_functions.R L319
  onwards.
  
  Pleae fix similar issues throughout your code.



## Vignette

* Please consider using the BiocStyle formatting for your vignette by
  checking out the package `BiocStyle` on Bioconductor. It adds
  formatting to make your vignette more easily readable.
  
* In the vignette you must also include installation instructions instead of
  pointing to README, as that won't be available via the Bioconductor
  website.
  
* The vignette takes a while to run (especially the code in `sim_functions.R`.)

* There is no need to include `GeneAccord.R` or `GeneAccord.html` in
  the vignettes folder. When the package is being built, the system
  will run `R CMD Stangle GeneAccord.Rmd` to generate the code from
  the vignette.

After your changes in the code, please let me know. I will review it again. As always, please bump the version number and make sure the build is as clean as possible.

**Comment by arhofman** [comment]
Hi @nturaga
Thank you for your comments. I addressed all of them and implemented the following changes:
- removed the paste0 from warnings, messages, and stops
- removed code that was commented out
- used seq_len or seq_along instead of seq where possible
- simplified code such that there are no for loops within an apply
- tried to use the BiocStyle formatting for the vignette
- included installation instructions in the vignette
- adjusted the vignette such that it runs faster
- removed the GeneAccord.R and GeneAccord.html files from the vignettes folder
- shortened the lines as good as possible and tried to be < 80 characters 
- tried to have indents of multiples of four spaces

Thanks a lot for reviewing this package!
Best regards,
@arhofman

**Comment by nturaga** [comment]
Hi @arhofman 

I'm giving you a 2 week notice to improve your package or reply with some information regarding your progress. We can always close the issue and reopen when needed and you are ready.

Best,

Nitesh

**Comment by arhofman** [comment]
Hi @nturaga 

Thanks for your comments and your notice. I was busy with another project where we had a deadline coming up, but will now have time within the next two weeks to work on your suggestions. I hope this is fine,

Bests,
Ariane

**Comment by nturaga** [comment]
That's great. It's good to know you'll be working on this again. 

The notice just serves as a reminder for a progress update or activity of some sort. Sometimes developers have other things on their plate, so we don't keep the issue open more than a certain number of days if there has been no progress.

**Comment by arhofman** [comment]
Hi @nturaga

Thanks for your comments to improve my package! I addressed all of them. Specifically I implemented the following changes:
-	I now use roxygen2 to create the Namespace file, and also import explicitly all functions from other packages that I need in my functions to avoid unnecessary use of “::”
-	Changed the News file such that it is hopefully parsable by utils::news()
-	Changed do.call(“rbind”,…) into bind_rows(…), and also changed cbind(data.frame(…)) into bind_cols(…) in a few places
-	Changed as.tbl(data.frame(…)) to just tibble(…)
-	Changed the way to extract a single column from a tibble from as.numeric(as.vector(as.data.frame(…))) to pull
-	Removed unnecessary variable fn -> path_to_file
Thanks a lot for reviewing this package!

Best regards,
@arhofman

**Comment by nturaga** [comment]
Thanks for making the changes. It looks good.

Could you please issue a version bump on this so that it builds on all three platforms? This might have been an issue on our end (maybe @lshep has an idea?)

Thanks,

Nitesh

**Comment by lshep** [comment]
We were running updates which is why the malbec1 is not displayed.  I'll kick off a manual build now to have all three platforms in the report.  Sorry about that.

**Comment by nturaga** [comment]
Hi @arhofman,

Your package seems fine after the new build report. You might want to consider using MultiAssayExperiment (https://bioconductor.org/packages/release/bioc/html/MultiAssayExperiment.html) as an input object to your functions. This will help users who are using Bioconductor objects to directly use your package instead of passing in a tibble. You may have to change the structure a little bit. 

But I will accept the package since it looks good otherwise. But you should really consider taking in a Bioconductor object as well as a tibble if your users need it. 

Best,

Nitesh

**Comment by LiNk-NY** [comment]
Hi @arhofman, 

I second Nitesh @nturaga and suggest that you use existing Bioconductor infrastructure
such as `MultiAssayExperiment` for your package.
The `MultiAssayExperiment` class uses an `ExperimentList`, which is a
`List`-derived structure that allows you to include several assays from different
flat rectangular data types.
It also allows you to subset to specific set of patients via the `colData` structure.
Refer to the MultiAssayExperiment [vignette](http://bioconductor.org/packages/release/bioc/vignettes/MultiAssayExperiment/inst/doc/MultiAssayExperiment.html) for more details. 


PS. Please update the `Installation` section in the package vignette.
Best regards,
Marcel

**Comment by arhofman** [comment]
Hi @nturaga and @LiNk-NY,

Thank you for your comments. That sounds very good. I am busy now finishing another deadline, but will address your suggestions in 2-3 weeks. 

Bests,
Ariane

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/arhofman.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"GeneAccord\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeneAccord

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
