### ISSUE TITLE
(inactive) GSminer: An R package for generating gold standard applied in gene functional network inference

### ISSUE THREAD

**Issue by ShadowFiendSF** [Bioconductor/Contributions#731]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ShadowFiendSF/GSminer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ShadowFiendSF** [comment]
Hi, *Bioconductor* team,

I have simplified the examples that in the R source code and thus can
reduce the building time. And, I have modified the vignette file.
Furthermore, I have run "R CMD check" and "R CMD BiocCheck" in my
workstation and the package has passed the check.

Thank you for review.

2018-04-23 1:19 GMT+08:00 bioc-issue-bot <notifications@github.com>:

**Comment by ShadowFiendSF** [comment]
Hi, @bioc-issue-bot 
I have modified the R source code and thus can pass the check and build.

**Comment by ShadowFiendSF** [comment]
Hi, @vobencha ,
I have modified my description file and vignettes . And I have test check and build on my workstation.

**Comment by ShadowFiendSF** [comment]
Hi, @vobencha ,
I have modified my description file and vignettes . And I have tested the check and build on my workstation.
Thank you for review.

**Comment by vobencha** [comment]
Hi @ShadowFiendSF ,
We are in the middle of preparing for the release of BioC 3.7 next Tuesday. I may not get to review this package until early next week.
Valerie

**Comment by ShadowFiendSF** [comment]
Hi @vobencha ,
I'll waiting for your review. I hope not to wait too long. Or this issue will be expired.
Thank you very much.

**Comment by vobencha** [comment]
What do you mean this issue will be expired? You submitted this package 5 days ago.

**Comment by ShadowFiendSF** [comment]
Yes,  if the package does not get passed in two week, the issue will expired.  If you got free until next Tuesday, I am a bit worried about this.

**Comment by vobencha** [comment]
That is not correct. Where are you getting this information?

When a package is submitted you can expect the first review within 2 weeks. Two weeks would be the end of next week. Once the review is in progress if you don't respond to comments within 2 weeks of the comment date, the issue will be closed.

**Comment by ShadowFiendSF** [comment]
Thank for you telling me the correct information about the process of the
review.
I will wait for you are free to review the package.

2018-04-26 22:11 GMT+08:00 vobencha <notifications@github.com>:

**Comment by ShadowFiendSF** [comment]
Hi @vobencha ,
I've modified the source code a week ago, I would like to know whether you are free to review the package.
Thank you!

**Comment by vobencha** [comment]
Hi,
I've done a first review. Let me know if you have questions.

1) DESCRIPTION

- I'm not sure what the 'gold standard' is in the Description. Please explain.
```
Description: GSminer, an R package that can automatically select gold standard including positive
            and negative genes pairs based on the Gene Ontology information of a specific species.
```
- Please remove this or set LazyData to false. In our experience 'true' has no advantages and some serious disadvantages when loading packages with large data.
```
LazyData: true
```
- As of R 3.5.0 the default is to byte-compile so you can remove this:
```
ByteCompile: true
```
2) Remove the figures/ directory from the man/ directory. man/ should contain only .Rd files.

3) man pages: running examples

All man pages need running examples. For example, in gene2BP-methods.Rd the single most important line, the one that tests gene2BP(), is commented out:
```
\examples{
inputFile <- paste0(system.file(package = "GSminer"), "/extdata/TAIR.GO")
#inputFile the name of input file which contain the mapping
#relationship between the gene and GO terms
#sep used in the input file by default is tab
#for an example how to use:
miner <- GSminer(inputFile = inputFile, sep = "\\t")
#gene2BP(miner@ggmapping)
}
```
This is not the only man page that has this problem. I am not going to list them all here but I do expect them all to be fixed. Please go through the man pages and remove the comments that silence code evaluations. If you feel the code cannot be evaluated, please explain why.

4) man pages: description section

Most man pages need more descriptive \description section. For example, this \description is from gene2BP:
```
\description{
Method gene2BP.
gene for GO Biological Process (BP) terms
}
```
This is from getThreshold-methods.Rd:
```
\description{
getThreshold method generics
select the GO term size
}
```

 Neither of these tell me what the function does. What is the input and output? What does 'select the GO term size' mean to a user that is not familiar with GO analysis?

Please revisit the \description sections of all man pages and add more detail about what the function does. Try to look at it from the perspective of someone new to the package and analysis.

5) man pages: filterNeg

The filterNeg-methods.Rd file has nothing in it ... ?
```
\name{filterNeg}
\alias{filterNeg}
\title{filterNeg method generics}
\description{
filterNeg method generics
}
```
6) C and C++ code

I'm curious why you chose to have both C and C++ code in your package. There isn't that much native code included and you are already LinkingTo Rcpp, why not make all code C++?

7) registration of native routines

Thanks for registering the native routines. It's also worth adding the useDynLib() to NAMESPACE so the registered routines can be referred to as R objects. I would recommend -
- Rename Rinit.c -> R_init_GSminer
- Add useDynLib("GSminer", .registration=TRUE) to NAMESPACE

See section 1.6.3 'Load hooks':
http://www.hep.by/gnu/r-patched/r-exts/R-exts_30.html#SEC30

And section 5.4 'Registering Native Routines':
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Registering-native-routines

Good examples are registration in the GenomicAlignments and Biostrings packages.

8) S4 classes

I think the structure of GeneGOMapping and GSminer is confusing. If you want reference class semantics you should use the existing R reference classes instead of creating a S4 class with a separate environment. Hadley has a good introduction to the reference classes:

http://adv-r.had.co.nz/R5.html

That said, the standard R user is not used to reference class semantics. Classes that are exported for manipulation by the user are better left at the usual "copy on change" behavior. The reference classes may be useful for low level methods or manipulations but I would not recommend exporting them for general use. If you feel strongly about exporting mutable classes, their behavior should be well documented complete with examples etc.

9) S4 methods

It makes sense to promote a function to S4 generic and method when you expect to use the method on more than one class. I don't see that situation with the methods in GSminer - each method is used on only one class. Why not make these regular functions? Are you planning to extend the methods to other classes in the future?
```
~/repos/github/packageReview/GSminer/R >grep setMethod *
...
buildMapping.R:setMethod("buildMapping", signature(object = "GeneGOMapping"),
buildMapping.R:setMethod("gene2BP", signature(object = "GeneGOMapping"),
buildMapping.R:setMethod("CC2gene", signature(object = "GeneGOMapping"),
getThreshold.R:setMethod("getThreshold", signature(object = "GSminer"),
getThreshold.R:setMethod("selectGO", signature(object = "GSminer"),
loadBPoffsprings.R:setMethod("loadBPoffsprings", signature(object = "GSminer"),
loadBPoffsprings.R:setMethod("loadCCoffsprings", signature(object = "GSminer"),
output.R:setMethod("outputPosNeg", signature(object = "GSminer"),
output.R:setMethod("filterNeg", signature(object = "GSminer"),
```
10) data sets

Why not save TAIR.GO in data/ instead of inst/extdata? TAIR.GO is a standard R object (data.frame) so there is no reason why it can't be saved as an .rda or .rds file.

11) SPB output

The purpose of the Single Package Builder (SPB) is to give you an idea of "how ready" your package is for review. You have both errors and warnings in the build output. Usually we wait until the package is 'clean', that is no errors or warnings before we do a first review. The SPB output should be clean before I do a second review.

**Comment by vobencha** [comment]
We've passed the 2 week period with no response from you. If we don't have a new version by Monday (June 4) I'll close this issue due to inactivity and we can re-open it when you are ready with a new version.
