### ISSUE TITLE
qPLEXanalyzer

### ISSUE THREAD

**Issue by AshKernow** [Bioconductor/Contributions#735]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/crukci-bioinformatics/qPLEXanalyzer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi @AshKernow ,

Thank you for your submission. I will be reviewing your package in the coming days. 
Please reach out to me here if you have any questions. Don't forget to use the @LiNk-NY tag
to notify me. Thanks!

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @AshKernow,

Please see the review below.
Don't hesitate to contact me via the issue here. 

Best regards,
Marcel

---

# qPLEXanalyzer #735

* Please format code so that it fits within 80 columns.
* Your repository is at ~40 Mb. Please reduce the repository size (.git) using
the BFG repo cleaner.

## DESCRIPTION

* Looks good.
* Please add a `BugReports` field to link to the issues page on GitHub
* Remove `LazyLoad` field, it's no longer supported and is ignored.
* Consider using `Authors@R` field instead of the `Author` and `Maintainer`
fields

## NAMESPACE

* Names look good. 
* You might want to consider renaming `convertToMSnset` to
something like `dataframeToMSnset`.
* Where possible, reduce function name length.

## R

* You might want to write a function that will perform all the checks to the
inputs of `convertToMSnset` and other functions.
* Avoid the copy and append method in `groupScaling`, use the allocate and fill
method.
* Avoid `1:ncol(x)` sequence generation, use the more robust `seq_len` and
`seq_along`
* There's no need to use `'%in%'(x, TRUE) & ...`, instead use `x & ...`
* Consider opening up the `corrPlot` interface to allow users to select colors

Minor:

* `length(x) == 0` is equivalent to `!length(x)`

## vignettes

* Again, format the vignette to max 80 column width. It is easier to read
and maintain.
* Consider using `gridExtra` for displaying the figures (p1, p2, etc.)
* Update or delete commented code if it is not running

**Comment by AshKernow** [comment]
Hi @LiNk-NY

Thanks very much for your helpful feedback. We will address the issues you've raised.

cheers

Ash

**Comment by LiNk-NY** [comment]
Please bump your package's version for another build in the BBS/SPB. 
Thanks,
Marcel

**Comment by AshKernow** [comment]
Hi Marcel
Will do, but we have a couple more fixes we want to do first. Hopefully in the next day or so.
cheers
Ash

**Comment by LiNk-NY** [comment]
Hi Ash, @AshKernow 

Thank you for following up on the comments. 
Please submit your changes as soon as possible so to avoid closing the issue due to inactivity.
Thank you. 

Marcel

**Comment by AshKernow** [comment]
Version bump to avoid inactivity. Still need to deal with:

- Your repository is at ~40 Mb. Please reduce the repository size (.git) using the BFG repo cleaner.
- You might want to write a function that will perform all the checks to the  inputs of convertToMSnset and other functions.

**Comment by LiNk-NY** [comment]
Hi Ashley, 

It looks like you'd like to submit an accompanying data package (although the link is broken).

Stripping the data out after submission does not look favorable because
it will result in a repository with a large `.git/` folder.

It would be better to resubmit both packages as a new issue.
In the meantime, I can close the issue. 

Best regards,
Marcel

**Comment by AshKernow** [comment]
Hi @LiNk-NY 

I've fixed the data package link - the repository was private, I've switched it to public now.

The problem is that the vignette for the data package describes 9 experiments, for which we include data, and their analysis. It is therefore dependent on the qPLEXanalyzer package and so cannot be submitted first, as recommended by the section on "Submitting related packages". Likewise the qPLEXanalyzer vignette requires the data, but we can't submit the pair with a circular dependency.

I will look at reducing the data size for the qPLEXanalyzer package to the minimum required for the examples in its vignette, and then clean the repository again. Would that be okay?

cheers

Ash

**Comment by LiNk-NY** [comment]
Hi Ashley, @AshKernow

Please add the data package to the `Suggests:` field of `qPLEXanalyzer`.
Then add `qPLEXanalyzer` to the `Depends:` field of the data package.
This will avoid a circular dependency. 

As far as the submission process goes, did you add an additional webhook for the data package? 
See here: https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages

The `qPLEXanalyzer` repository is just software and it should not be as big as it is currently.
Please remove any _extra_ data from the package and run the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to reduce
the size of the repository. 

Best regards,
Marcel

**Comment by AshKernow** [comment]
Hi Marcel, @LiNk-NY

I have trimmed the data in the qPLEXanalyzer package and cleaned the repo with the BFG. I can't add the qPLEXdata into the DESCRIPTION under Suggests as this results in a build error:

* checking package dependencies ... ERROR
Package suggested but not available: 'qPLEXdata'

The webhook for the qPLEXdata package is in place.

cheers

Ash

**Comment by LiNk-NY** [comment]
Hi Ashley, @AshKernow

My apologies if I didn't make myself clear but I wanted you to **keep** `qPLEXdata` in the
`Suggest` field of `qPLEXanalyzer`. Please do this first and include a version bump. 

Once the build has completed:

Our SPB expert, Lori @lshep, suggested that you re-add the `AdditionalPackage`
comment so that the SPB picks up and builds both packages.

Regards,
Marcel

**Comment by AshKernow** [comment]
AdditionalPackage: https://github.com/crukci-bioinformatics/qPLEXdata

**Comment by LiNk-NY** [comment]
Hi Ashley, @AshKernow 
I will review the data package. 
In the meantime, please response to each of the items in the review. 

Thank you for your attention. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Ashley, @AshKernow 
Thanks for the response! 

> We do not wish to give the impression that the only possible input is a dataframe, we also support other formats e.g. tibble.

Those familiar with `tibble`s know that `data.frame` methods work for that data class. 
You can also consider using coercion functions such as `as(object, "MSnset")`. 

I will have a final peek at the package before accepting it. 

Regards,
Marcel

**Comment by AshKernow** [comment]
Hi Marcel, @LiNk-NY

I rebuilt the package and we have no errors now.

cheers

Ash

**Comment by LiNk-NY** [comment]
Hi Ashley, @AshKernow 
Your package has been accepted. Thank you for contributing!
Regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/AshKernow.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"qPLEXanalyzer\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/qPLEXanalyzer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/AshKernow.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"qPLEXdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/qPLEXdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
