### ISSUE TITLE
gwasurvivr

### ISSUE THREAD

**Issue by aarizvi** [Bioconductor/Contributions#749]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/suchestoncampbelllab/gwasurvivr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by aarizvi** [comment]
I'm not sure what's going on with Windows installation. It seemed to have been working in my earlier commits. It seems like it has to do something with the `stringi` package that is being called from one of the packages in my `NAMESPACE`. I'm not sure how to narrow that down. And should I be more explicit with my `importFrom` calls from some of the packages I depend on? Thanks.

**Comment by aarizvi** [comment]
Hi Val, 

Any suggestions on whats going on with the Windows build and why the time elapses are so long for the build and the examples. It seems like the user functions are finishing quite quickly (as they are on my end too). Is something getting caught up on the Windows machine? The Linux/Mac ones seem to building and executing the examples much faster. 

I could make the example files smaller - just want to hear if you have any suggestions before I do that.

Thank you for your time!

Abbas

**Comment by vobencha** [comment]
Referring to question asked in https://github.com/Bioconductor/Contributions/issues/749#issuecomment-386436253. 

The Windows builders only have 32GB of RAM and the 32-bit arch can only allocate 2-3GB for an R process. So, yes, please do reduce the size of data used/processed in the man page examples and vignette to play nice with the Windows restrictions. We are planning to get more RAM for the Windows builders in the next couple of months.

**Comment by aarizvi** [comment]
Referring to your [last comment] (https://github.com/Bioconductor/Contributions/issues/749#issuecomment-387586127) --

I'm having some trouble understanding whats going on here. Originally when I started the submission process, the data I was using was "small" but considerably larger than my current data. In those earlier commits, it seemed like everything was building and installing properly (< 5 min, with the exception of Windows which was about 6 minutes). So I understood the warnings with Windows because the `R CMD CHECK` time was > 5 minutes.  And then yesterday I kept getting TIMEOUT, which didn't make much sense to me, because all I did was reduce the size of my data.

Now I've greatly reduced the data (all < 5 KB). The package after `R CMD BUILD` is ~ 70KB. On my personal laptop it seems to be getting through `R CMD CHECK` under 5 min with no errors.  As well as no errors with `R CMD BioCheck`. 

With this last commit, I'm not seeing the ERROR in the OS X build, besides "/Library/Frameworks/R.framework/Resources/bin/Rcmd: line 62: exec: BiocCheck: not found"

I suspect that this one is not on my end. 

I'm wondering how I can get the Windows to be <5 minutes, I certainly can evaluate less in the vignette (right now at 41% not being evaluated, and it seems like there is a 50% allowance), because reducing the size of the data doesn't seem to doing anything.

I also have a suspicion that because this package does parallel computing by default that maybe creating workers is slowing things down? I would prefer to keep this option, but I suppose that we can make an option that does not parallelize if you think this will be speed it up enough to make it past these checks. On my side I have always seen more efficient (faster) computation when running in parallel, but with these small datasets I'm not sure if it is somehow making things slower.

These computations should not be very RAM intensive, particularly with the size of the data, so I don't think that we are exceeding our memory allowances in these vignette and man examples.

Thank you very any advice/suggestions and of course for reviewing the package!

**Comment by vobencha** [comment]
Hi,
If you have reasonable examples that don't use much RAM then we should be ok. I can give you more input when I've had a chance to do a full review and look at the examples in detail.

As for parallel computations, man page examples and the vignette should use minimal cores (not max). Remember your package will be built and checked with 1500+ other packages nightly and it should not monopolize resources. Some parallel evaluation is not available on Windows - depending on how you're using 'parallel' this may or may not be the case. Again, I can comment more when I've had a chance to do a full review.

This package was submitted 8 days ago. We try to get comments back within 2 weeks of submission. If I can't get to this tomorrow I'll do it next week.

Valerie

**Comment by vobencha** [comment]
Hi,
1) Yes, that's fine.
2) Thank you.
3-4) OK
5) warnings
I'm no expert with knitr but the warning your seeing is coming from knitr:::process_file(). knitr::purl() calls down to knitr:::knit() which makes it's way down to process_file().

The bash script code chunk is the problem. knitr:::process_tangle() can't seem to parse that chunk as labeled (it produces a list of length > 1). If you change the label to 
     ```{r, eval = FALSE}```
it works fine. I'm sure there is a way to correctly specify shell scripts or 'asis' chunks - you could ask on the mailing list, someone may know.

I was testing with BiocStyle 2.9.2. You say this went away with BiocStyle 2.9.1? We currently have 2.9.2 on the devel build machine so that is the version the version the SPB will use. I did also cleaned up a few things in BiocCheck so if you're testing locally be sure to get the latest version. 

Why don't you investigate that bash code chunk and see if you can find a solution. Bump the version and see if we get a clean build. If the bash code label should work as advertised you could open an issue on the knitr github site.

Valerie

**Comment by vobencha** [comment]
We can ignore the warning from BiocCheck during the review process. You won't see this with `R CMD check` on the build machines.

**Comment by vobencha** [comment]
Thanks for making the changes. The package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aarizvi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"gwasurvivr\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gwasurvivr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
