### ISSUE TITLE
RaMWAS: Fast Methylome-Wide Association Study Pipeline for Enrichment Platforms

### ISSUE THREAD

**Issue by andreyshabalin** [Bioconductor/Contributions#75]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/andreyshabalin/ramwas

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lshep** [comment]
Thank you for you submission.  Your pipeline vignette is very descriptive but it doesn't have a runable example with executable R code.  Could you please include a vignette that depicts the function calls and have an executable example so that it is more clear how to utilize your package functions.

**Comment by andreyshabalin** [comment]
Thank you for the feedback.
I will update the vignette and manual to include examples with simulated
data.

Andrey

**Comment by andreyshabalin** [comment]
I've added a function creating an artificial data set and now use it to illustrate the pipeline steps with relevant code in vignette("RaMWAS_pipeline").

**Comment by lshep** [comment]
Thank you for your efforts. I appreciate being able to work through your vignette with the example.  

However, the data provided with the package is rather large (31M); package generally have to be <4M.  Can you provide a small subset to run with the vignette? Just enough to show functionality? Perhaps only providing a few chromosomes or a subset of each, etc. 

You might also considering looking at the [SystemPipeR vignette](http://bioconductor.org/packages/release/bioc/vignettes/systemPipeR/inst/doc/systemPipeR.html) as they are another pipeline that do a very nice job of explaining. 


**General**
- [ ] Please fix all warnings in the build report and address any notes as well. 

**vignette**
- [ ] Add a section at the top for downloading from bioconductor and loading the package 
```
source("https://bioconductor.org/biocLite.R")
biocLite("ramwas")
```

- [ ] Remove the extra brackets {   }  around the code chunks in the vignette and shorten the code chunks to under 80 characters per line to avoid running over a standard page width. 

- [ ] You mention that you can change the default directories(dirrqc, dirqc, etc): how?  are these additional param? They are not listed in the param vignette or when declaring param. 

- [ ] You can condense the cat/message calls in the codes chunks down to a single call and these should probably be hidden from the user - only the output should be displayed not the message code 

- [ ] It seems like you should have some helper functions to display some outputs of the files you generate. 
i.e.
```
show(head( read.table(paste0(dir,
         "/coverage_norm_20/PCA_00_cvrts/PC_vs_covariates_corr.txt"), 
          sep = "\t", header = TRUE)))
```
There could be a function that the user can call to retrieve this object since you know the paths to the output.  
The same is true for your plotting function. 
```
qqPlotFast(fm.load(paste0(dir,
        "/coverage_norm_20/PCA_00_cvrts/Testing_age_0_PCs/Stats_and_pvalues"))[,3])
```
Either have a helper function to retrieve the pvalues or wrap around reading the file that is generated. 

**general R code/man files**
- [ ] Please remove any lingering commented out code in the R code or man files that are not notes or comments on code functionality.  

I can provide additional feedback once the above issues are addressed.  We appreciate your time and effort.  I look forward to reviewing any updates.

**Comment by andreyshabalin** [comment]
Dear @lshep,

I've addressed all your comments in this update.

The warning the package builder signals is:
WARNING: y of x.y.z version should be even in release
I believe 'y' should be 99 for my initial submission.

There are no other warnings.

I appreciate your work reviewing my package.

**Comment by lshep** [comment]
Some questions: 

 - [ ] Do the raw files have to be created or are the result of a specific platform type, machine type, or experiment type? 
 - [ ] To run your pipeline from the start, it seems like you generate BAM files, a list of the BAM files, list of covariates, and file withe the locations of CpGs. Are the covariates and CpG files mandatory or can they be missing? 
 - [ ] Can people use your pipeline at an intermediate step?  Say they used some other package or method for scanning/reading BAM files and came in with coverage matrix, would they be able to utilize the remaining steps in your pipeline?

**Comment by andreyshabalin** [comment]
Dear @lshep,

It is the usual workflow of MBD-seq, MeDIP-seq, and other enrichment sequencing platforms begins with DNA fragments being enriched and then sequenced. The sequenced reads are then aligned (using any of many available aligners) to the reference genomes resulting in BAM files, which RaMWAS uses in Step 1.

The CpG set file is mandatory as it indicates the genomic positions at which read coverage is calculated. The "CpG sets" vignette provides a number of CpG sets for human and mouse genomes, as well as instructions for creating a CpG set for any other genome.

The covariate/phenotype file is required for association studies and cross validation (Step 5+) as the outcome variable is taken from it. Steps 3 (matrix creation) and 4 (PCA) restrict their attention to the set of samples present in the covariate file.

> Can people use your pipeline at an intermediate step?
Yes. Great question. I should make a separate vignette about it.
I actually did this just yesterday. I created a 'coverage matrix' containing imputed genotype data for 2700 samples and 7 million SNPs. Then with Steps 5 and 6, I could run PCA and GWAS (genome wise association study) on this data very easily and very quickly.
All one has to do is create the coverage filematrix and the location filematrix like those produced by step 3.

Can the package be accepted before I add such vignette? I'll add it within a week.

Thank you.

**Comment by lshep** [comment]
We would appreciate if this vignette gets added before acceptance to show that it can be utilized by other packages

**Comment by andreyshabalin** [comment]
Dear @lshep,

The newly added vignette (RW2_matrix) illustrates how to use RaMWAS on an external data set.
It also illustrates that the association testing results match those from standard linear regression function 'lm'.

The error indicated by the package builder above is "pdflatex is not available".
This error is a package builder issue out of my control.
There warnings appear to be unimportant as well.

Thank you for consideration.

**Comment by lshep** [comment]
Thank you I will review the new vignette. 
The ERROR is on our end and I will investigate. We do expect the WARNINGS that are in your control to be fix. The systems were updated to the latest versions of R and Biocondcutor which is why they are new.

**Comment by andreyshabalin** [comment]
The warnings I got are:
1. Update R version dependency from 3.3.0 to 3.4
2. inst/doc files ... ignored as vignettes have been rebuilt.

I find them very minor, but OK, I will address them.

It's just I've been using this github repository to distribute the package to my collaborators.
They can now easily install it via: devtools::install_github("andreyshabalin/ramwas").
And there is NO benefit in forcing them to update to the development version of R - the package works fine on R 3.3.0. And they were finding the compiled vignettes useful.

But OK, I will address the warnings.

**Comment by lshep** [comment]
Thank you for correcting the other WARNINGS.  Since this ERROR seems to be on our end I will mark your package as accepted.  If the problem persists on the daily build you will be expected to make changes in a timely matter.  Please leave the issue open; you will receive svn instructions within a few days for uploading to Bioconductor. Thank you for your effort and submitting to Bioconductor.

**Comment by andreyshabalin** [comment]
Dear @lshep,

Thank you for your time and effort
reviewing my submission.

Is there any timeframe on when I should receive the SVN instructions?

**Comment by lshep** [comment]
Probably within the next week
