### ISSUE TITLE
allenpvc

### ISSUE THREAD

**Issue by diogo-branco** [Bioconductor/Contributions#751]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/diogo-branco/allenpvc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@Liubuntu will review this package. I think it would be a useful convenience to have a single function `allenpvc()` that simply returns `eh[["EH..."]]`.

**Comment by diogo-branco** [comment]
@mtmorgan Thank you, I will create the `allenpvc()` function.

Regarding the error on the building: the Package Builder seems to be using BiocVersion 3.7 and not 3.8. This package will only work on version >= 3.8. Is there anything to be fixed on my side in that regard?

**Comment by mtmorgan** [comment]
the build system should heal itself; @lshep might post here when it is updated.

**Comment by lshep** [comment]
I apologize for the delay. We are working on the updates -  I will post back here when they are complete.

**Comment by Liubuntu** [comment]
Hi @diogo-branco , 

Thank you for your contribution to Bioconductor. Please refer to the following technical review and address any issue. This is my first time reviewing an experiment data package. I will talk to Bioconductor core team about any potential points to add possibly.  Please let me know for any questions or concerns. Thanks!

## DESCRIPTION
- look good.

## NAMESPACE
- looks good.

## R
- the `query()` on line 34 is not needed.

## Vignettes
- Please add a section called `Installation` after `Introduction`, and show to users how to download and library this package as it is already available in Bioconductor. E.g., to use `BiocInstaller` function for downloading. ``` BiocInstaller::biocLite("allenpvc")```
- please add a section in the end `sessionInfo()` to show users your working environment.

## inst/
- the `metadata.csv` is not consistent with `make-metadata.R`, in the `BiocVersion` filed (3.6 versus 3.8).

Cheers, 
Qian

**Comment by Liubuntu** [comment]
I would say `as if it is already available in Bioconductor`. Because when users are exposed to the vignette, the package should already be available on Bioconductor. Be sure to make the code trunk `eval=FALSE` for this `Installation` section.

**Comment by diogo-branco** [comment]
Thank you for clarifying, I will include the `Installation` section after `Introduction`. Is a version bump required for this push to be built by the SPB?

**Comment by Liubuntu** [comment]
Yes. Be sure to bump the version whenever you are ready for a new build.

**Comment by diogo-branco** [comment]
@Liubuntu I believe I have complied with all the review points in this latest build. Please let me know in case I have overlooked something.

**Comment by Liubuntu** [comment]
HI @diogo-branco , 

Sorry for the delay. I will look into the updates and get back to you very soon!

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/diogo-branco.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"allenpvc\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/allenpvc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
Since you have remained unresponsive to emails - this is our last attempt to contact you -  Your software package condcomp has been failing in Bioconductor since before the last release.  We have tried to contact you to fix the ERRORs but you have remained unresponsive and the repository has been unchanged.  If your package is not fixed in the next week we will be deprecating condcomp and allenpvc do to being an unresponsive maintainer.
