### ISSUE TITLE
(inactive) qckitfastq

### ISSUE THREAD

**Issue by winnie0521** [Bioconductor/Contributions#753]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/compbiocore/qckitfastq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment]
Hi @winnie0521 ,

Thanks for your submission. Note that the following line is all you need in your `Makevars` file:
```
PKG_LIBS = -lz
```
I notified the author of the zlibbioc vignette that the documentation is a little bit misleading. He will update it soon.

Regards,
H.

**Comment by hpages** [comment]
Hi @winnie0521 

I looked at qckitfastq and have some feedback for you:

## Value

1. First of all: R packages for doing quality control of sequencing data have been available for many years. A popular Bioconductor package for this is ShortRead. There is also fastqcr on CRAN that wraps FASTQC functionality in an R package. So my question is: what qckitfastq has to offer that is not already available via ShortRead or fastqcr?

## Vignette

2. Your vignette needs an introduction explaining what the package is for. Also please provide some context and the motivations e.g. what is the typical use case for the package, on what kind of data it can be used, coming from what kind of experiment etc... Put yourself in the shoes of your reader. Don't take for granted that things that are obvious for you are obvious for your reader.

3. Please capitalize the first letter in the first word of your titles (main title, sections and subsection titles).

4. Do not use `devtools::install_github` in your vignette to install the package. Once a package is part of Bioconductor, it should be installed with `biocLite()` i.e. with:
    ```
    source("https://bioconductor.org/biocLite.R")
    biocLite("qckitfastq")
    ```
    so please show this instead. See https://bioconductor.org/install/ for the detailed instructions.
It's ok to add a note showing how to install the development version of the package though but please make it clear that, unless the user knows what s/he's doing, this should be avoided as it can lead to package version mismatch hell.

5. Also use `eval=FALSE` for this code chunk otherwise the package will re-install itself everytime its vignette gets built (e.g. when someone or the build system runs `R CMD build` on it). More generally speaking, the code in the man pages, vignettes and unit tests should not effectively install packages.

6. The vignette says:

    _For some functions based on seqTools, we will first process the file through seqTools
    and then let qckitfastq functions proceed with the analysis._

    Please explain this. What `seqTools::fastqq` does exactly? Why do we need to do this? Couldn't the functions in qckitfastq do this for us?

7. Please briefly comment the result of each step of the analysis.

## Man pages

8. Man page for `dimensions` mentions `ncolumn` but there is no such function.

9. Overall man pages are too minimalist.

## Other

10. Please address the following notes from the Single Package Builder:
```
    * NOTE: Avoid sapply(); use vapply() found in files:
      over_rep_kmer.R (line 82, column 25)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      over_rep_kmer.R (line 37, column 13)
      plot_overep_seq.R (line 21, column 21)
      plot_overep_seq.R (line 25, column 23)
```

11. Many of your functions provide the `writefile` and `prefix` arguments let the user write the result to a file or not. Not only this is clumpsy design but also this feature is poorly documented (the man pages don't say a thing about the location and name of the file by default). So the feature is inconvenient to use and obscure. A better (and simpler) design would be to provide a single argument e.g. `output_file` that is NA by default and to write the result to a file when this argument is not NA (it must then be a single string specifying the path to the file). If you want a good file name to be used by default, another approach is to provide 2 arguments, `write_output` (similar to your `writefile` argument) and `output_file` with a default value for `output_file` e.g.
```
    plot_quality_score <- function(basic_statistics, write_output=FALSE, output_file="quality_score.pdf")
    {
        ...
    }
```

12. Why specify `writefile=FALSE` in your examples (man pages and vignette) when this is the default? The fact that you explicitely specify `writefile=FALSE` is distracting and potentially misleading because it suggests that a file is written by default.

13. C++ code: using 100 lines of code to initialize `ascii_map` when you could do this in 2 lines with a loop is very poor coding practice. Even worse: you do this twice! (Once in the `process_fastq()` function and once again in the `qual_score_per_read()` function.) Furthermore it seems that the only purpose of `ascii_map` is to map ascii characters to their ascii code minus 33. Please realize that you could just do `(int) c - 33` for this. So you don't need `ascii_map` at all.

    Keeping things as simple as possible is one of the first and most important pre-requisite for good programming!

**Comment by hpages** [comment]
Hi @winnie0521 -- Are you planning to followup on this submission? If not, we'll close the issue. Thanks!  H.

**Comment by aguang** [comment]
@hpages Hi, I will be following up on the submission, thank you. Will try to get in a response by the end of next week.

**Comment by aguang** [comment]
Hi, I would like to reopen this issue, what is the way to do so?

**Comment by aguang** [comment]
I pushed commits to `master` which got a 200 response from the webhook, but it doesn't seem like bioc-issue-bot is building the package. Does the tag need to be changed?

Also, I have addressed concerns in the previous review in the repo in [`response.md`](https://github.com/compbiocore/qckitfastq/blob/master/response.md).

**Comment by lshep** [comment]
Please ensure the [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)  is still initialized properly  and then try a version bump again.

**Comment by hpages** [comment]
@aguang 

Thanks for your work on qckitfastq. Please let me know when the package is ready for a 2nd review. 

Thanks again,
H.

**Comment by aguang** [comment]
@hpages The package is ready, thanks.

**Comment by hpages** [comment]
Hi @aguang,

Thanks for all the work you're putting on qckitfastq.

Please note that we don't support C++14 yet on our Windows build machines so we'll need to mark qckitfastq as not supported on this platform. We also need to do the same for RSeqAn which is currently failing to install on Windows in devel (see https://bioconductor.org/checkResults/3.9/bioc-LATEST/RSeqAn/). This dependency on C++14 is unfortunate and will likely hurt the deployment of your package on clusters with slow-moving enterprise Linux distributions.

Thanks for the much improved vignette. Here is some additional feedback about the vignette:

14. I was curious to take a look at the "qckit project page" but the link provided in the vignette does not work.

15. The top-level categorization of the various metrics ("Basic metrics", "C++ based metrics", "seqTools::fastqq based metrics") feels arbitrary and lacks relevance from an end-user point of view (e.g. the particular programming language used to implement the calculation of a metrics is really an implementation detail that is not relevant for the end-user). Maybe a more useful categorization would be paying attention to **what** the metrics are about.

16. "Basic metrics" is currently a subsubsection, directly inside the "Individual metrics" section, with no subsection in between. Shouldn't it be a subsection instead of a subsubsection? This would put it at the same level as the "C++ based metrics" and "seqTools::fastqq based metrics" sections.

17. More generally it feels like the overall structure of the document needs some attention, with a special attention to the nesting level of sections, subsections, and subsubsections. For example do you really want "Kmers count per base" and "Overrepresented kmers" to be subsections of the "Individual metrics" section at the same level as the "Basic metrics", "C++ based metrics", and "seqTools::fastqq based metrics" subsections?

18. The bibliography at the end of the vignette should be in its own section. Also in the body of the document references should be linked to their corresponding entry in the bibliography.

Thanks again,
H.

**Comment by aguang** [comment]
Hi @hpages,

Thanks for your review. There is only 1 main function that depends on C++14, which is `calc_adapter_content` to detect adapter contamination in reads. I can remove the function for Windows builds if there is a way to flag that as a possible solution. Should I ignore the current errors for the Windows build then?

To respond to the other points:
14. Sorry, someone else on my team is supposed to work on the qckit project page, but it is not up yet. I have removed the link for now.
15-18. Thanks for this, I have reorganized the vignette to just detail individual metrics rather than by what particular programming language they use. In general the vignette should be more organized with a description for each metric and plot and table styles. The bibliography also now has its own section.

**Comment by hpages** [comment]
Hi @aguang,

Feel free to use conditionals to disable the `calc_adapter_content` function on Windows. Then, at the R level, the `adapter_content()` function should fail graciously on this platform (with an error message saying something like "this function is not available on Windows, sorry"). Finally the man page for `adapter_content()` and the vignette would also need to use conditionals to disable calls to the function on Windows. If you decide to go that route, then you'll know that you've succeeded when qckitfastq installs, builds, and passes check on this platform.

Thanks for the improvements to the vignette. Please note that you're using commas improperly (and inconsistently) to separate the first and last names of the authors in the References section (e.g. "Andrews, Simon" or "Ewels, Philip"). Also, as mentioned earlier, it would be really nice if the references in the text were linked to their corresponding entry in the References section.

Thanks again,
H.

**Comment by aguang** [comment]
@hpages I will add the reference links and work on disabling `adapter_content()` for Windows. With regards to the commas usage in the References, it is [automatic from RMarkdown](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html) and follows the Chicago author-date format. I didn't see any inconsistencies in the references. Are you referring to the fact that the first author is shown as 'last name, first name' while subsequent authors are shown as 'first name last name'? If so that is consistent with [Chicago style](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html). I can change it to another style but didn't see anything in the Bioconductor documentation about it. Let me know if there is a specific style I should use instead.

**Comment by aguang** [comment]
@hpages I disabled `adapter_content` for qckitfastq Windows as well as disabled some functionality for RSeqAn for Windows as well. Let me know if this solution works for you.

**Comment by hpages** [comment]
Hi @aguang ,

Thanks for teaching me about the Chicago style. Everything looks good now. Thanks for all your hard work on qckitfastq.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/winnie0521.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("qckitfastq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/qckitfastq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
