### ISSUE TITLE
GREP2

### ISSUE THREAD

**Issue by naimmahi** [Bioconductor/Contributions#754]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/uc-bd2k/GREP2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@lshep will review this package. I recommend using the curl rather than RCurl package. Your vignette needs to be expanded, minimally to show how this might integrate with other Bioconductor packages.

I do not think the package name is very good, because of it's similarity to the `grep()` command.

The Description: doesn't really tell me what this package does, for instance does 'comprehensive' mean that you enable differential expression analysis?

The extensive dependency on non-R software (SRA toolkit, fastqc, trimmomatic, salmon) means that the build system will not be able to test the package comprehensively, and that  installation of the package results in a very incomplete piece of software. This makes me skeptical of the suitability of the package for Bioconductor.

**Comment by naimmahi** [comment]
@mtmorgan thanks for your comments.
I can definitely take care of some the issues you raised. 
1. I have used the primary function in the vignette to show the whole processing of a GEO RNA-seq data. Although, I could use the other functions as well, but this function mainly integrate all other functions of this package.
2. The package doesn't enable differential expression analysis. It provides RNA-seq read counts starting with a GEO series accession ID. 
3. Currently, no R package is available to download and process GEO RNA-seq data, which is the primary motivation of building this package. The package assumes that non-R software, such as  SRA toolkit, FastQC, Trimmomatic, Salmon are installed in the user end.

**Comment by naimmahi** [comment]
Hi @lshep, 
Any further update on my package? I can see the building status turned "OK". Please let me know.

Thanks.

**Comment by lshep** [comment]
I'm sorry for the delay I will try and have a review for you within the next day.

**Comment by naimmahi** [comment]
Thanks a lot.

**Comment by lshep** [comment]
Thank you for your contribution. After initial review, we do not feel that the domain of application and level of development is appropriate for Bioconductor, and are therefore declining the package.

The main reasoning is lack of executable code and dependency on outside third part applications and general lack of processing within R. 

**Executable code:** 
The majority of your pipeline functions are actually not evaluated in the vignette, man page examples, or tests (missing).  Bioconductor will not accept packages that do not have executable code to show the processing and workability of code.  

**Outside dependencies:** 
A large part of your package relies on non-R software (SRA toolkit, fastqc, trimmomatic, salmon). Which all of these dependencies should be listed as SystemDependencies in your DESCRIPTION and not left as an after thought in the man files. Also as @mtmorgan pointed out that the build system will not be able to test the package comprehensively, and that installation of the package results in a very incomplete piece of software. Many of your functions are merely wrappers around system calls and not actually processing in R. 


Some other tips but did not play a role in the decline: 
+ I agree with @mtmorgan - the name of the package because of it's similarity to the grep() command is not ideal - most programmers have a notion of something named 'grep'   even GREPP2 would be better (including the second P from Pipeline of your acronym GEO RNA-seq Experiments Processing Pipeline)
+ @mtmorgan already indicated we recommend using the curl rather than RCurl
+ We recommend system2 over system
+ We recommend BiocParallel. The mc.* functions from the parallel are not supported on Windows with more than one core. Please use the BiocParallel package instead of parallel. BiocParallel is supported across all platforms and builds on the snow and parallel packages; in other words, you aren't loosing functionality by using BiocParallel.



We wish you success in your work and look forward to your future contribution to Bioconductor.
