### ISSUE TITLE
slingshot

### ISSUE THREAD

**Issue by kstreet13** [Bioconductor/Contributions#755]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kstreet13/slingshot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
## Build report

```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: Biobase
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

- If your package Depends: on Biobase, then probably there your package code uses Biobase functions; these functions should be imported in the NAMESPACE. On the other hand if your package doesn't use Biobase functions, then Biobase shouldn't be listed in the DESCRIPTION file.

```
* checking foreign function calls ... NOTE
Foreign function call to a different package:
  .Fortran("getlam", ..., PACKAGE = "princurve")
```

- Generally, one should act on this note and access the functionality via public R-level functions. Is that practical in the current case?

```
* checking R code for possible problems ... [15s/15s] NOTE
slingshot,ClusterExperiment-ANY: no visible global function definition
  for colData<-
slingshot,SingleCellExperiment-ANY: no visible global function
  definition for colData<-
Undefined global functions or variables:
  colData<-
```

- This looks like a missing import, perhaps

    ```
    #' @importFrom SummarizedExperiment colData<-
    ```

## Other

DESCRIPTION

- Please write the Description: field more as a paper abstract, providing enough information to orient the potential user to your package and it's relative merits compared to alterntaives.

- When using Authors@R, it is not necessary to use Author: and Maintainer: fields; these are generated by R CMD build.

vignettes

- the *html and other artifacts of building the vignette should be removed.

R -- Comments reference specific lines but apply throughout

- AllGenerics.R:241 consider whether dispatch (versus argument validation) will occur on all arguments here; perhaps it is better to restrict `signature = "sds"` and validate the other arguments? Also this might motivate re-arranging the order of arguments in the signature. The underlying reasons for this recommendation are to avoid needing to reason about method selection under method dispatch, and the principle that code should be as simple as possible to satisfy current need.

- AllHelperFunctions.R:408 The 'copy-and-append' pattern here is inefficient (`out` is copied each time through the list); see [robust code][] 'pre-allocate and fill'. The `Recall()` function is generally 'too clever' for itself; simply use `.get_connections()` explicitly. 

- AllHelperFunctions.R:436 doubly-nested iterations like this necessarily have quadratic execution time. Can you generate this data in a way that is more tradition (matrix or multi-dimensional array) or a 'long' data frame where operations can be performed by group (e.g., via `aggregate()`)?

- AllHelperFunctions.R:452 consider `matrixStats::colWeightedMeans()` and similar functions in place of `apply()` on a matrix, here and elsewhere.

- getCurves.R:110 consider an indentation style that allows for longer lines and easier visual parsing (less white space at the start of each line), e.g.,

    ```
    setMethod(f = "getCurves",
          signature = signature(sds = "SlingshotDataSet"),
          definition = function(sds,
                                shrink = TRUE, 
                                extend = 'y', 
                                reweight = TRUE,
                                drop.multi = TRUE, 
                                thresh = 0.001, maxit = 15, stretch = 2, 
                                smoother = 'smooth.spline', 
                                shrink.method = 'cosine',
                                allow.breaks = TRUE, ...)
    {
        X <- reducedDim(sds)
        clusterLabels <- clusterLabels(sds)
        lineages <- slingLineages(sds)
        ...
    })
    ```

- getCurves.R:116 avoid direct slot access; use (internal) accessors instead

    ```
    .slingParams <- function(x)
        x@slingParams
        
    `.slingParams<-` <- function(x, value) {
        x@slingParams <- value
        x
    }
    
    ...
    .slingParams(sds)$shrink = shrink
    ## better -- one copy
    .slingParams(sds) <- list(
        shrink = shrink,
        extend = extend,
        ...
    )
    ```
    
- getCurves.R:362 this line looks like it could be vectorized (probably more cleanly than below); I suspect many other iterations are similar

    ```
    cidx <- colMaxs(Z, na.rm = TRUE) > .9 & 
        colMins(z, na.rm = TRUE) <= .5
    W0 <- W[, cidx]
    Z0 <- Z[, cidx]
    W0[!is.na(Z0) & Z0 > .9] <- 0
    W[, cidx] <- W0
    ```

- getLineages.R:395 `message(paste0(...))` (also `warning(), stop()`) is generally redundant, `message(...)` pastes the arguments together.

[robust code]: http://bioconductor.org/developers/how-to/efficient-code/

man

- Some man page do not render correctly, for instance SlingshotDataSet-class.Rd, I guess because of the 'double roxygen' comments like

    ```
    #' #' @describeIn SlingshotDataSet Updated object with new reduced dimensional
    ```
    
  perhaps the intention was to comment these lines, `# #' @describeIn ...`?

**Comment by mtmorgan** [comment]
Thanks for your updates

- Please use `seq_len()` / `seq_along()` instead of 1:... as indicated by BiocCheck; this avoids surprises with, e.g., 1:0, which can occur when dealing with user data.

- Please also consider `vapply()` rather than `sapply()`; `vapply()` is a more robust approach that 'fails early', a classic example being `sapply(integer(), sqrt)` which returns a `list(0)`, versus likely expectation `numeric(0)`.

**Comment by mtmorgan** [comment]
I see the warnings are from (minor) excess build / check times. I'll approve the package anyway.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kstreet13.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"slingshot\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/slingshot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
