### ISSUE TITLE
CancerInSilico

### ISSUE THREAD

**Issue by tsherma4** [Bioconductor/Contributions#76]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tsherma4/CancerInSilico

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
DESCRIPTION

- good
- add additional BiocViews terms?

NAMESPACE

- ok

vignettes

- looks good

man

- Generally, the documentation seems 'sparse'

- CellModel-class.Rd

  - worth documenting, for your own purposes, what the structure of
    this class is.
  - consider adding the aliases for each CellModel-method to this page
    (rather than on the page where the generic is documented), and
    enumerating the methods that are available to an individual who
    has one of these classes.
  - This can be tedious to establish with roxygen; tags like @rdname
    can help.

- runCancerSim() seems to be the main function, and should provide a
  richer resource for the user to understand what is going to happen
  -- in a \detail{} section, briefly indicate what 'the model' of the
  title is, and provide a greater description of what the user can get
  from the function.
    
R

- the CellModel class is sort of a faux class; it would be better to
  structure it with slots that explicitly enumerate the relevant
  parameter and 'cells' elements, rather than allowing these to be
  specified in named numeric vectors or lists. This (providing
  reproducible structure to data objects) is after all a main benefit
  of S4.

- implement a 'show' method that provides a succinct summary of the
  class and emphasizes how (what functions, if any) the user is
  supposed to use to access the object -- the user should not be
  exposed to 'Slot' information. The idea is again that the use of
  classes provides a way to separate the implementation details (which
  may change) from the interface experienced by the user (which can
  often be held relatively constant even as the representation
  changes).

- implement simple 'getters' for the class, and use these in your
  package code. Expose these or not to the user, as you see fit. For
  instance, define a function in cellModelClass.R (usually better to
  adopt a naming convention that is closer to the objects / functions
  defined in the file, e..g, CellModel-class.R)
  
      .n_generations <- function(model)
          model@parameters[8]
          
  and replace `nG <- model@parameters[8]` in
  (getCycleLengthDistribution) with `nG <- .n_generations(model)`
  (part of this is guess-work, I have no idea, and neither will you in
  6 months, what parameters[8] or nG are supposed to represent). When
  you have a more structured class, e.g., with slot n_generations,
  then one has only to change the definition of `.n_generations`
  rather than the references, direct or otherwise, to parameters[8] in
  the code.

- the tryCatch of runDrasdoHohme.R is unnecessary /
  inappropriate. You'd like any error message to be printed on the
  'error' stream, rather than on the standard I/0 stream, so that
  errors are easily detected when run in a script. But your
  formulation undermines this.

- avoid the excessively long `cellMat<-` line in runDrasdoHohme.R,
  instead, let the code breath with a space after ',' and wrapping at
  80 characters. This greatly improves readability.
  
src

- consider adopting a standard indentation style, e.g., in
  CellModel.cpp there are both tabs and 4 spaces. I prefer 4 spaces.
  
- I'm not sure about the details of your code, but please assess
  whether checking for user interrupt occurs at appropriate
  intervals, e.g., in CellPopulation::CellPopulation.

**Comment by mtmorgan** [comment]
For final review please address the remaining warning in your package, and provide a brief summary of your response to the original comments.

**Comment by tsherma4** [comment]
> DESCRIPTION

>* good
>* add additional BiocViews terms?

added SystemsBiology, CellBiology, BiomedicalInformatics

> NAMESPACE

>* ok

> vignettes

>* looks good

vignette has been updated to reflect changes in function names

> man

>* Generally, the documentation seems 'sparse'

>* CellModel-class.Rd

>>* worth documenting, for your own purposes, what the structure of this class is.

documented CellModel class

>>* consider adding the aliases for each CellModel-method to this page (rather than on the page where the generic is documented), and enumerating the methods that are available to an individual who has one of these classes.
>>* This can be tedious to establish with roxygen; tags like @rdname can help.

I wasn't able to combine the documentation without getting a warning from `R CMD check` due to multiple arguments having the same name. The major change to the structure was putting all of the functions related to a CellModel object in CellModel-class.R and implementing them just as functions (instead of having a generic and a method defined). I believe this makes the organization more clear, but I'm not sure if this is the kind of design you we're looking for. I could combine the documentation without a warning if I give every argument a unique name (time1, time2, etc) but it would be a hack. I wanted to get your input about this before I did something like that.

>* runCancerSim() seems to be the main function, and should provide a
richer resource for the user to understand what is going to happen
-- in a \detail{} section, briefly indicate what 'the model' of the
title is, and provide a greater description of what the user can get
from the function.

added a detail section for this function, as well as documentation for every function in the package

> R

>* the CellModel class is sort of a faux class; it would be better to
structure it with slots that explicitly enumerate the relevant
parameter and 'cells' elements, rather than allowing these to be
specified in named numeric vectors or lists. This (providing
reproducible structure to data objects) is after all a main benefit
of S4.

I added a slot for each parameter. There is still a slot for cells that contains the raw data from the output of the model. Ideally, this would be a list of cell objects, where each cell object contains the information about a particular cell, and the CellModel class has a list of cells for each time point. The problem with this approach is the size of the objects starts to become unmanageable even with reasonably small simulations. Storing the data in raw form provides a dramatic reduction in size, at the cost of a well organized object. To make up for this, all the information in the cell object is accesed through functions that account for the structure of the raw data. 

>* implement a 'show' method that provides a succinct summary of the
class and emphasizes how (what functions, if any) the user is
supposed to use to access the object -- the user should not be
exposed to 'Slot' information. The idea is again that the use of
classes provides a way to separate the implementation details (which
may change) from the interface experienced by the user (which can
often be held relatively constant even as the representation
changes).

This function has been implemented

>* implement simple 'getters' for the class, and use these in your
package code. Expose these or not to the user, as you see fit. For
instance, define a function in cellModelClass.R (usually better to
adopt a naming convention that is closer to the objects / functions
defined in the file, e..g, CellModel-class.R)

>* ```.n_generations <- function(model)
    model@parameters[8]```
and replace `nG <- model@parameters[8]` in
(getCycleLengthDistribution) with `nG <- .n_generations(model)`
(part of this is guess-work, I have no idea, and neither will you in
6 months, what parameters[8] or nG are supposed to represent). When
you have a more structured class, e.g., with slot n_generations,
then one has only to change the definition of `.n_generations`
rather than the references, direct or otherwise, to parameters[8] in
the code.

Getters have been implemented for each parameter and for all the cell data. `nG` and `epsilon` still have their obscure names since they refer to mathematical parameters in the Drasdo paper. All other parameters have explicit names that describe what their for.

>* the tryCatch of runDrasdoHohme.R is unnecessary /
inappropriate. You'd like any error message to be printed on the
'error' stream, rather than on the standard I/0 stream, so that
errors are easily detected when run in a script. But your
formulation undermines this.

this has been removed

>* avoid the excessively long cellMat<- line in runDrasdoHohme.R,
instead, let the code breath with a space after ',' and wrapping at
80 characters. This greatly improves readability.

this has been removed

> src

>* consider adopting a standard indentation style, e.g., in
CellModel.cpp there are both tabs and 4 spaces. I prefer 4 spaces.

all tabs have been removed

>* I'm not sure about the details of your code, but please assess
whether checking for user interrupt occurs at appropriate
intervals, e.g., in CellPopulation::CellPopulation.

the program checks for user interrupt at every time step

**Comment by tsherma4** [comment]
Thank you for taking the time to review this package. We greatly appreciate the feedback.

**Comment by mtmorgan** [comment]
The changes look good and I will mark this package as accepted. It will be added to the Bioconductor nightly builds and svn repository, with additional instructions in the next week.

Something like the following, where the param x is defined once but used across functions
```
#' Foo
#' 
#' @param x integer(1) blah
#' @export
foo <- function(x) {}

#' @rdname foo
#' @export
bar = function(x) {}
```
gets foo and bar documented on the same page without warnings.

**Comment by tsherma4** [comment]
Thank you for the feedback and acceptance of the package. I will update the documentation, thanks for the tip.
