### ISSUE TITLE
brainImageR

### ISSUE THREAD

**Issue by saralinker** [Bioconductor/Contributions#760]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saralinker/brainImageR

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by saralinker** [comment]
Thank you. I see this error...

ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .

...and have signed up using the link here. Has this fixed the error?

**Comment by trannhatanh89** [comment]
I think you can just bump a version to build the package again and see if the error go away or not.

**Comment by saralinker** [comment]
Thanks @trannhatanh89 The error persists on my end but with the message "requires\nadmin credentials." Since I have signed up (and can log in) I was hoping that the Bioconductor team would have any required admin credentials to see that I am indeed signed up for the support site. 

I have searched around for information on this issue and didn't come across anything useful. If you have any idea as to why this error persists even though I am signed up for the support site I would much appreciate the help. Please note that I sign in with the same email that is listed in the DESCRIPTION file under maintainer.

**Comment by saralinker** [comment]
Hey @trannhatanh89 . I think I may have misinterpreted your original comment. Did you mean that if I bump the version number in the DESCRIPTION file then the bot will automatically re-run the code to generate any errors? Sorry, this is my first time submitting to Bioconductor so I'm a complete newbie here.

**Comment by trannhatanh89** [comment]
@saralinker Yes, that's what I meant. I'm a newbie too, and it did take me a while to get the OK status. What I kept doing was fix error -> local checks -> bump version -> commit -> online build check -> repeat. Didn't pass the test until 0.99.9 or so. It's fun if you like troubleshooting. There are certain things like creating webhooks or sign up for the mailing list that you need to read the guidelines to know what to do.

**Comment by trannhatanh89** [comment]
Also, in my personal experience, BiocCheck on my local computer and the one here give different results, so I just base my troubleshooting on the online build checks.

I'm not sure if it's OK to keep bumping the version to check here or not. Maybe someone from the bioc team can help me out here, please? :-)

**Comment by saralinker** [comment]
Thanks @trannhatanh89 ! I gave the version bump a shot (and double-checked that the web hook was created correctly). Hopefully it just takes awhile to go through.

**Comment by saralinker** [comment]
great thanks @dvantwisk!

**Comment by saralinker** [comment]
My apologies @dvantwisk . I will keep it stable.

**Comment by dvantwisk** [comment]
That's fine.  If you have changes to make, you might consider putting them on another branch and merging later.

**Comment by saralinker** [comment]
Thanks for the advice. Will do.

**Comment by saralinker** [comment]
hi @dvantwisk is there anything further that you need me to do to move forward with this process?

**Comment by dvantwisk** [comment]
I apologize for the wait!  I'll have a review to you very soon.

**Comment by saralinker** [comment]
no worries, and thanks

**Comment by dvantwisk** [comment]
Here is the review.  The code looks great for the most part, although I do have some gripes with the documentation.  [REQUIRED] tags must be addressed.  [CONSIDER] tags describe changes that are not necessary but advisable.  Please make the change in the review and message me back when you are finished so I can have another look at the changes.

R/GENERAL
- [CONSIDER] Be specific about what is required as a paramete or given as output
to your user facing funcions and methods. For example, in `R/BrainMap.R:L54`,
`slice` is mentioned as a `@param`.  Is `slice` an `integer()` or `character()`
or something else?  It would be best to be explicit about the type here so that
the user knows what should be given as input.
- [CONSIDER] The documentation in the man pages seems sparse throughout. It may
be worth it to take a look through the documentation and see if anything can be
added for the sake of the user.

R/Comp.R
- [REQUIRED] Add a better title and a more detailed description to the
`Roxygen2` header of the class `Comp`.  Also add a description abut what the
slots are for.  This class is exported and as a user I would have no idea what
it does by this piece of documentation.

R/GeneLists.R
- [CONSIDER] Mention a source for where this information was aquired.

R/PValue.onetail.R
- [REQUIRED] L26: Import na.exclude from stats with an `Roxygen2` tag.

R/PlotEnrich.R
- [REQUIRED] Import the symbols that you are using from `ggplot2` using an
`Roxygen2` header.

R/Pred.R
- [REQUIRED] Same thing as `R/Comp.R`.

R/RandomTissueSummary.R
- [CONSIDER] L21: Use `match.arg()` to improve style of function declaration.
For example, the parameter `refset` can have two values `"developing"` and
`"adult"`. The parameter in the function declaration can be
written as `method=c("developing", "adult")`. The value that
the user uses can be obtained with `refset <- match.arg(refset)`. The
first value (in this case `"developing"`) is the default argument. Using this
method makes it clear to users what the allowed inputs to a function are and may
also make error catching easier. This can be used in other functions in the
package.

R/SpatialEnrichment.R
- [REQUIRED] L78-81, L83-86: Inefficient copy-and-append pattern used here.
Use `vapply()` as apposed to itertively building from an unallocated vector. Eg.:
```
tissueExp1b <- vapply(unique(names(tissueExp1)), function(i) {
    mean(tissueExp1[names(tissueExp1) == i])
}, numeric(1))
```

R/TissueSummary.R
- [CONSIDER] L31: `paste()` unnecessary here.

R/availiable_areanames.R
- [CONSIDER] L29: `paste()` unnecessary here.

R/brainrange.R
- [REQUIRED] Can you explain the `brainrange.R` function? What is the function
made to avoid in `BiocCheck`. Also, does this need to be visible to the user?

R/dat.R
- [REQUIRED] Please provide more information about what this data is. Where was
it obtained? What do the row and columns represent?

R/hipp.R
- [REQUIRED] Same as `R/dat.R`.

R/loadworkspace.R
- [REQUIRED] As a user, I don't understand what `loadworkspace()` does. Please
expand more on the eplanation of the function.

R/predict.time.R
- [REQUIRED] L31-32: It seems like removing `warning()` and putting the message
inside of `stop()` would be best.

R/reColor.R
- [CONSIDER] L48: `paste()` unnecessary here.

R/tis_in_region.R
- [CONSIDER] L31: `paste()` unnecessary here.

R/tis_set.R
- [CONSIDER] L35: `paste()` unnecessary here.

R/tissuemean.R
- [REQUIRED] @examples seems to be unfinished for this.

R/vth.R
- [REQUIRED] Same as `R/dat.R`.

R/whichtissues.R
- [CONSIDER] L23: `paste()` unnecessary here.

inst/unitTests
- [REQUIRED] This is the only test file and doesn't seem to have any tests (i.e.
calls to `Runit`'s `check_` functions).  Please either add tests or remove them.
It is preferrable to have tests.  The `testthat` package tends to be a more
intuitive way to create R unit tests and I would recommend it in place of
`Runit`.

**Comment by saralinker** [comment]
hi @dvantwisk in this case is the problem with the build system? When I look into the warning "Warning: replacing previous import stats::sd by BiocGenerics::sd when loading" it seems like the problem is that the Bioconductor version is out of date. I don't get these warnings on my machine.

**Comment by dvantwisk** [comment]
This appears to be an issue specific to our build machine, however, it can likely be solved by explicitly importing `sd` and `var` from `stats` in your `NAMESPACE`.

**Comment by dvantwisk** [comment]
It seems the actual reason for this may be that you've imported `sd` and `var` from `BiocGenerics`.
BiocGenerics should either just include the symbols that are being used instead of importing the entire package, or use an `except` clause to remove the unneeded ones:
```
import(BiocGenerics, except = c(sd, var))
```
To exclude these using an roxgyen2 tag, use:
```
#' @rawNamespace import(BiocGenerics, except = c(sd, var))
```

**Comment by dvantwisk** [comment]
Did these changes work?  I'm not entirely familiar with this warning, but I was told it may be the case that you aren't using the current devel version of R.  That may make it appear for you, if this issue hasn't already been resolved.

**Comment by saralinker** [comment]
Hi Daniel, yes I am working on it. Should be done soon. Thanks.

**Comment by saralinker** [comment]
hi @dvantwisk sorry for the delay. The code seems to be working properly now.

**Comment by dvantwisk** [comment]
Sorry for the delay.  The package looks fine now.  I'm going to move to accept it.

**Comment by saralinker** [comment]
Thanks that's great

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/saralinker.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"brainImageR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/brainImageR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
