### ISSUE TITLE
ERSSA

### ISSUE THREAD

**Issue by zshao1** [Bioconductor/Contributions#761]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zshao1/ERSSA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by zshao1** [comment]
The only error seems to be subscription at: https://stat.ethz.ch/mailman/listinfo/bioc-devel
I have previously tried subscribing to this mailing list, but have yet to receive a confirmation email or any daily digests from the mailing list. 
I just made any other attempt at subscribing, hopefully it works this time.

**Comment by zshao1** [comment]
HIC2
2.169211978
2.762179861
2.649800335
2.269920276
2.26052042
2.068973663
2.465933172
1.898681129
2.560403078
2.10283373
2.118614946
2.051746989
2.433689277
2.141364565
2.010360299
2.44619013
2.001073207
3.136162276
2.006828044
1.645079989
1.925750301
2.099569411
2.407327191
2.225499975
2.758385508

**Comment by hpages** [comment]
Hi @zshao1 ,

Thanks for your submission. One thing before I start the formal review: please do not use `devtools::install_github()` in your vignette to install the package. Once a package is part of Bioconductor, it should be installed with `biocLite()` i.e. with:
```
source("https://bioconductor.org/biocLite.R")
biocLite("ERSSA")
```
so please show this instead. See https://bioconductor.org/install/ for the detailed instructions. It's ok to add a note showing how to install the development version of the package though but please make it clear that, unless the user knows what s/he's doing, this should be avoided as it can lead to package version mismatch hell.

Thanks,
H.

**Comment by zshao1** [comment]
Hi @hpages,

Sure, I have made the necessary changes and created a new build 0.99.4. Thanks!

Best,
Zach

**Comment by zshao1** [comment]
Hi @hpages,

I made some edits to the vignette and plots to improve clarity.
The package has been bumped to version 0.99.5.
Please let me know if you have any questions!

Best,
Zach

**Comment by dvantwisk** [comment]
I apologize for the long wait for a review.  Herve was on vacation for some time, and sequentially after that, our core team had a conference to go to.  I've reviewed your package in Herve's stead to get it out to you faster.  Things look pretty good, there are just some issues that I have that occur repeatedly throughout the package that I'd like you to address.  Tags labeled [REQUIRED] must either be changed or you must offer an explanation regarding it.  Tags labeled [CONSIDER] are changed that are advisable but not required.  Please message me back when you are finished making changes or needs to ask more questions!

GENERAL:
- [REQUIRED] We generally like to see repos smaller than 5MB for software
packages.  This repo is 13MB.  The `.git` directory is 8.2MB large, indicating
that you may have committed some large files and removed them later down the line.
Please use BFG Repo cleaner to try to reduce the repo's size as much as possible.
https://rtyley.github.io/bfg-repo-cleaner/

R/NAMESPACE:
- [REQUIRED] It seems that you are not importing any packages in your NAMESPACE
despite indicating you are importing packages in your `DESCRIPTION`.  I am
seeing spots in your code where you are using symbols from other packages, e.g.
`DE_DESeq2.R:L146` uses `DESeq2::DESeq`.  Since you are using `roxygen2`, you
ought to import this symbol to your `NAMESPACE` with `@importFrom DESeq2 DESeq`.
Please also do this with the rest of your imported symbols.

R/GENERAL:
- [CONSIDER] Use `seq_along()` or `seq_len()` instead of `1:...` or seq.  Doing
this is slightly more efficient.
- [CONSIDER] Use `vapply()` over `sapply()`.  Doing this is slightly more
efficient.
- [REQUIRED] Use `message()` instead of `cat()` for diagnostic messages to the
user.  `message()` is preferable is it can be turned off with
`surpressMessages()`.

R/DE_DESeq2:
- [REQUIRED] L117-167: For both declaring `DE_genes` and `DE_genes_rl`, it
would be better to use an `lapply()` statement instead of using a for-loop to 
iteratively create the lists.
```
  DE_genes <- lapply(names(combinations), function(rep_level){

    comb_rl = combinations[rep_level][[1]]

    if (save_table==TRUE){
      #create dir to save results
      folder_path = file.path(path, 'ERSSA_DESeq2_table', rep_level)
      dir.create(folder_path, showWarnings = FALSE)
    }

    #loop through each combination at given replicate level
    DE_genes_rl <- lapply(seq_len(comb_rl), function(index){

      #combination string to vector
      comb_samples_i = strsplit(comb_rl[index], ';')[[1]]

      #parse out sample counts
      count_table.filtered_i = count_table.filtered[,colnames(
        count_table.filtered) %in% comb_samples_i]

      #DESeq2
      group = sapply(colnames(count_table.filtered_i), function(x)
        condition_table$condition[which(condition_table$sample_name==x)])
      group=as.data.frame(group)
      dds = DESeq2::DESeqDataSetFromMatrix(countData = count_table.filtered_i,
                                         colData = group,
                                         design = ~ group)
      dds$group = stats::relevel(dds$group, ref = control)
      dds = DESeq2::DESeq(dds, quiet=TRUE)
      resLFC = DESeq2::lfcShrink(dds, coef=2)

      res_cutoff = resLFC[which(resLFC$padj < cutoff_stat & abs(
        resLFC$log2FoldChange) > cutoff_Abs_logFC),]

      #save list of DE genes to list
      DE_genes_rl[[paste0('comb_',index)]] = rownames(res_cutoff)

      #save entire result table to drive
      if (save_table==TRUE){
        utils::write.csv(resLFC, file = file.path(folder_path,paste0(
          'ERSSA_DESeq2_',rep_level,'_comb',index,'.csv')))
      }

      cat(paste0(rep_level,'; combination_',index,' | done\n'))
    })

    DE_names_rl <- vapply(seq_len(comb_rl), function(index){
        paste0("comb_", index)
    }, character(1))

    names(DE_genes_rl) <- DE_names_rl

    #add DE gene lists to main list
    DE_genes_rl
  })

  names(DE_names) <- names(combinations)
```
- [REQUIRED] L301-361: You can do the same thing mentioned above here.
- [REQUIRED] L169,363: It doesn't make much sense to automatically save `DE_genes`
here.  If the object is being returned to the user, the user could just choose
to save it themselves if they so choose.  Please remove these lines.

DE_edgeR.R:
- [REQUIRED] L115-162, 303-364: It seems the same efficiency mechanisms can be
implemented here as mentioned in the `DE_DESeq2` section.
- [REQUIRED] L170, 366: It seems that the save statements can be removed as
mentioned in the `DE_DESeq2` section.

R/combination_gen.R
- [REQUIRED] L93-167: better to initiate replicate_combs with `lapply()` than
iterative for-loops.  Also, the empty vectors and while-loops within this 
for-loop are very inefficient.  Please use `vapply()` to initiate those vectors.
- [REQUIRED] 172-175: Either don't include these lines or make it optional for a
user to save the file here.  Since the saved object is being returned to the
here, the user can just save the object themselves.

R/count_filter.R
- [REQUIRED] L50-54: Same issue as previously mentioned.  Either remove these
lines or add an argument to the function to make it optional to save here.

R/erssa.R
- [REQUIRED] L176-178: Please add optional argument to generate the log file.
- [REQUIRED] 274-286: Same issues with writing these objects as mentioned before.

R/plot_TPR_FPR.R
- [REQUIRED] L80-109: `TPR, FPR, replicate, and combination` are being initiated
using a copy-and-append pattern.  This pattern is very inefficient in R.  Please
find a way to either vectorize or use a `vapply()` function to declare these
variables.  If doing so is too complicated, the time-efficiency of doing this would
be greatly increased by pre-declaring these vectors.  E.g. if we knew `TPR`
would ultimately have a length of `10` and that is would contain `character`
objects, we should use `TPR <- vector(mode="charcter", length=10)`.  The inner-loop
would then reference these elements as `TPR[i] <- value`.  Pre-allocating size and
types, as well as avoiding `c(TPR, TPR_i)` prevents the expensive operation
involving allocating an entirely new vector for the new `TPR and TPR_i` as well
as the amount of time needed to refill the new vector.
In addition to this, `lapply()` should be used to declare `list_TP_FP_genes`.
- [REQUIRED] L144-146: Saving the plot should be made optional or removed as
the plot is returned to the user at the end of the enclosing function.

R/plot_dot.R
- [REQUIRED] L51-67: Same concerns about inefficient copy-and-append patterns.
that was explained above.
- [REQUIRED] L95-102: Same concerns about saving graph as before.

R/plot_intersectPlot.R
- [REQUIRED] L68-75: Use `lapply()` to declare inters_genes.
- [RQEUIRED] L90-108: Same concerns about inefficient copy-and-append patterns.
- [REQUIRED] L142-149: Same concerns about saving graph as before.

R/plot_marginalPlot.R
- [REQUIRED] L49-71: Same concerns about inefficient copy-and-append patterns.
- [REQUIRED] L93-101: Same concerns about saving graph as before.

vignettes:
- [REQUIRED] L33-34: We are moving towards using the new BiocManager package for
package management of Bioconductor packages.  The new way to install the package
should be given as:
```
install.packages("BiocManager")
BiocManager::install("ERSSA")
```
- [REQUIRED] L65,202: We generally do not allow `eval=FALSE`'s in user-visible
parts of the vignette.  This is so the build machine can test whether this code
meant to demonstrate your package actually works for the user.  Please remove
the `eval=FALSE`.
It may be that you probably included this here because it takes the build
system too long to run this vignette without throwing a warning.  If that is
that case, I need to ask that you find a way to simplify the example code so
that it does build within the allotted time.

**Comment by dvantwisk** [comment]
Hello,

Have you made any progress on this package? We generally like to see packages not go more than two weeks without activity. If a package is inactive, we will close the issue until the developer is prepared to continue work on it.  Please respond within the next week, or we'll have to close this issue for the time being.

**Comment by dvantwisk** [comment]
Okay, thanks for the update. I'll wait for your changes.

**Comment by zshao1** [comment]
In the lastest build, BGF-repo-cleaner was used to remove old large files > 128K. Now the repo is 8.03 MB (8,425,472 bytes). Is this acceptable?

**Comment by zshao1** [comment]
•	BGF-repo-cleaner was used to remove old large files > 128K. Now the repo is 8.03 MB (8,425,472 bytes). Some of that is occupied by the vignette HTML file (~2.2MB).
•	Functions from other packages are now in the NAMESPACE with @import and @importFrom. Thanks!
•	Where appropriate, seq() has been replaced with seq_along()
•	Cat() replaced with message()
•	Lapply now replaces for loops in DE_DESeq2.R, DE_edgeR.R, plot_intersectPlot and plot_TPR_FPR.R scripts. 
•	Removed automatic saving of objects in DE_{DE Software}.R, combination_gen.R and count_filter.R, erssa.R.
•	Generate log file is now optional for erssa.R
•	In combination_gen.R, we think it will be hard to use vapply() in place of while loop to generate the random combinations. We want to employ a random sampling process so each run may generate unique combination of combinations (assume total number of unique combinations is smaller than n_repetition). Additionally, we want to remove any duplicates during this process. The two requirements make it hard to implement vapply(). Additionally, we performed some additional testing with a hypothetical 100 samples (50 samples per condition) dataset and use comb_gen() to generate 100 unique combinations at replicate levels 2-49. We found that it took 2 seconds to generate the required combinations on our system. On the other hand, running the differential expression analysis on all of these combinations may take hours. Here are the codes we tested:
```
> condition_table=data.frame(sample_name=paste0('sample_', seq_len(100)), condition=c(rep('condition_1', 50), rep('condition_2', 50)))
> Sys.time(); combs = comb_gen(condition_table, n_repetition = 100); Sys.time()
[1] "2018-08-29 14:26:02 PDT"
[1] "2018-08-29 14:26:04 PDT"
```
•	All plot functions now have save plot as an option.
•	Replace copy-and-append vector generation in plot functions with vapply()
•	Vignette now mention BiocManager in installation instruction. Codes are also now evaluated.

**Comment by dvantwisk** [comment]
In `comination_gen.R`, is it possible to preallocate the length of the vector beforehand? Also, is it possible to remove these duplicate elements outside of the loop?

**Comment by zshao1** [comment]
I went ahead with the change to combination generation script.
Running the same test previously used shows the script is indeed faster now:
```
> condition_table=data.frame(sample_name=paste0('sample_', seq_len(100)), condition=c(rep('condition_1', 50), rep('condition_2', 50)))
> time0=proc.time(); combs = comb_gen(condition_table, n_repetition = 100); proc.time() - time0
   user  system elapsed 
   0.88    0.00    0.88
```

**Comment by dvantwisk** [comment]
Great! I think that's all the changes i have for you. Would you like mo to accept the package now or do you want to make more changes?

**Comment by zshao1** [comment]
Hi, that's great! We don't have any updates at the moment, so I think we can go ahead with the release.
Can you walk me through the next steps? Thanks!

Zach

**Comment by zshao1** [comment]
Hi @dvantwisk, just want to check in on what we should do next now that the package is accepted. Thanks!

**Comment by dvantwisk** [comment]
Nothing more needs to be done on your end. That are a few manual things we need to do before your package is propagated to our devel server.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zshao1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ERSSA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ERSSA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
