### ISSUE TITLE
maEndToEnd workflow package submission

### ISSUE THREAD

**Issue by b-klaus** [Bioconductor/Contributions#765]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/b-klaus/maEndToEnd

**This package is a workflow**

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hi, 
Just a few minor comments

**DESCRIPTION:** 
- [ ] remove LazyData: true . This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data.

**DATA:**
- [ ] Please include an inst/scripts that describes how the inst/extdata palmieri_DE_res.xlsx  was created - it can be sudo code but should have some indication of the source and information provided


**VIGNETTE:**
- [ ] Please update instructions to include bioconductor installation.  You can keep the github if you would like to advertise as the development version. 

- [ ] The vignette should write to a temporary directory instead of the current working directory. Please update the code in sections 4 and 7 to use tempdir() or tempfile().  

Please make the above changes, do a version bump, and comment back here. Thank you.

**Comment by b-klaus** [comment]
Hello Lori,

we have now implemented the changes requested.

Best wishes,

Bernd

**Comment by lshep** [comment]
Could you please make sure the webhook is initialized on your repository https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook  and   do a version bump to kick off the new build?

**Comment by b-klaus** [comment]
I double-checked: it says " **We couldn’t deliver this payload: Service Timeout** I am now trying to manually re-deliver.

**Comment by lshep** [comment]
I'll can manually kick off a build on our end -  When you set up the webhook did you make sure to switch the content type to application/json ?

**Comment by b-klaus** [comment]
Yes, thanks, the initial webhook test "delivery" also worked (code 200).

**Comment by lshep** [comment]
hmm - I'll investigate more but for now will kick off a build manually on our end. Its running now and should be posted shortly.

**Comment by lshep** [comment]
Thank you the changes look good.  Provided that when the build report posts that it looks okay I would be ready to accept.

**Comment by b-klaus** [comment]
Thanks Lori! All looks good in the build report I think.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/b-klaus.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"maEndToEnd\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/maEndToEnd

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
@b-klaus The maEndToEnd repository already exists at Bioconductor, with version 1.0.3; I bumped the version to 1.99.0, so that at the next release this will become 2.0.0, which seems approximately correct if I'm understanding the history of this workflow. You'll need to sync the upstream changes (`upstream` remote in the example below) with your github repository (`origin` remote), e.g.,

```
cd maEndToEnd
git remote add upstream git@git.bioconductor.org:packages/maEndToEnd
git fetch --all
git merge upstream master
git push origin master
```

**Comment by truong128** [comment]
Dear Everyone,

I am working on data analysis for microarray data, but I could not install into my R studio,

Could anyone help me to install "maEndToEnd" for microarray analysis into R studio in Macbook?

Thank you very much

**Comment by lshep** [comment]
The Bioconductor contributions is for the package submission process only. -  Please post support questions to the bioconductor support site   https://support.bioconductor.org/  .  Also please include any commands you have tried with the ERROR output  and your `sessionInfo()`  when posting .  thank you.
