### ISSUE TITLE
MetNet submission

### ISSUE THREAD

**Issue by tnaake** [Bioconductor/Contributions#766]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tnaake/MetNet 

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
nturaga will review your package. Usually a vignettes/Makefile is not required or desired; it gets in the way of R's standard procedures for building vignettes during R CMD build.

**Comment by nturaga** [comment]
Hi @tnaake 

Please make sure you have a clean build report before I review your package. 

Follow the Bioconductor style guide as far as coding practices go, http://bioconductor.org/developers/how-to/coding-style/ and follow this guide on how to write robust code (http://bioconductor.org/developers/how-to/efficient-code/).

```
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      statistical.R (line 45, column 24)
      statistical.R (line 55, column 22)
      statistical.R (line 68, column 15)
      statistical.R (line 110, column 34)
      statistical.R (line 119, column 22)
      statistical.R (line 131, column 15)
      statistical.R (line 341, column 14)
      structural.R (line 100, column 15)
      structural.R (line 101, column 40)
```

**Comment by nturaga** [comment]
# MetNet Review

## R CMD buld

ok

## R CMD check

ok 

## NEWS

* Good job with the informative NEWS file.

## DESCRIPTION

* No need of Author + Maintainer if you are using `Authors@R`.

## NAMESPACE

* ok

## man

* ok

## vignette

* Consider using BiocStyle package for your vignette. 
https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html

* remove Makefile and all artifacts mentioned by `mtmorgan`.

## R 

* Use Bioconductor's parallel evaluation facilities `BiocParallel`
  instead of `parallel`. Instead of `mclapply` you'd be using
  `bplapply` which gives you a whole range of parallel facilities
  specifically for bioconductor.
  
  https://bioconductor.org/packages/3.7/bioc/html/BiocParallel.html
  
* Make sure all your functions need to be exported to the user, if
  these functions have value in a workflow. (eg: threeDotsCall, I
  think is useful only as an internal function)

**Comment by nturaga** [comment]
# BUScorrect Review

## R CMD buld

ok

## R CMD check

ok 

## NEWS

* Please include a NEWS file.

## DESCRIPTION

* Description not enough to give a full picture of what the package is
  doing. Please think of this section like the abstract of a paper.

## NAMESPACE

* ok

## man

* ok

## vignette

* Consider using BiocStyle for you vignette.

https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html

## R 

* [REQUIRED] Make sure your build report is clean. Address all the
  NOTEs before a further review. I'm only pasting one from your build
  report below, but please address all the NOTE sections in
  http://bioconductor.org/spb_reports/BUScorrect_buildreport_20180627000843.html.
  
* [REQUIRED] We are particular about coding standards, follow
  https://bioconductor.org/developers/how-to/coding-style/ . It also
  makes your code easier to read for the reviewer.

```
* Checking coding practice...
	* NOTE: Avoid sapply(); use vapply() found in files:
      BUS_Rfunctions.R (line 17, column 22)
      BUS_Rfunctions.R (line 44, column 25)
      BUS_Rfunctions.R (line 398, column 24)
      BUS_Rfunctions.R (line 484, column 25)
      BUS_Rfunctions.R (line 529, column 33)
      BUS_Rfunctions.R (line 566, column 25)
      BUS_Rfunctions.R (line 769, column 41)
      BUS_Rfunctions.R (line 811, column 42)
      BUS_Rfunctions.R (line 856, column 42)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      BUS_Rfunctions.R (line 17, column 29)
      BUS_Rfunctions.R (line 43, column 18)
      BUS_Rfunctions.R (line 44, column 32)
      BUS_Rfunctions.R (line 88, column 18)
      BUS_Rfunctions.R (line 89, column 26)
      BUS_Rfunctions.R (line 91, column 44)
      BUS_Rfunctions.R (line 209, column 10)
      BUS_Rfunctions.R (line 218, column 10)
      BUS_Rfunctions.R (line 223, column 10)
      BUS_Rfunctions.R (line 266, column 10)
      BUS_Rfunctions.R (line 268, column 36)
      BUS_Rfunctions.R (line 281, column 10)
      BUS_Rfunctions.R (line 282, column 18)
      BUS_Rfunctions.R (line 334, column 10)
      BUS_Rfunctions.R (line 350, column 10)
      BUS_Rfunctions.R (line 375, column 26)
      BUS_Rfunctions.R (line 397, column 10)
      BUS_Rfunctions.R (line 398, column 31)
      BUS_Rfunctions.R (line 422, column 10)
      BUS_Rfunctions.R (line 423, column 47)
      BUS_Rfunctions.R (line 424, column 53)
      BUS_Rfunctions.R (line 425, column 59)
      BUS_Rfunctions.R (line 429, column 10)
      BUS_Rfunctions.R (line 431, column 47)
      BUS_Rfunctions.R (line 483, column 18)
      BUS_Rfunctions.R (line 484, column 32)
      BUS_Rfunctions.R (line 528, column 26)
      BUS_Rfunctions.R (line 529, column 40)
      BUS_Rfunctions.R (line 565, column 18)
      BUS_Rfunctions.R (line 566, column 32)
      BUS_Rfunctions.R (line 599, column 18)
      BUS_Rfunctions.R (line 603, column 18)
      BUS_Rfunctions.R (line 612, column 26)
      BUS_Rfunctions.R (line 613, column 34)
      BUS_Rfunctions.R (line 635, column 18)
      BUS_Rfunctions.R (line 698, column 18)
      BUS_Rfunctions.R (line 704, column 18)
      BUS_Rfunctions.R (line 710, column 18)
      BUS_Rfunctions.R (line 768, column 34)
      BUS_Rfunctions.R (line 769, column 48)
      BUS_Rfunctions.R (line 770, column 80)
      BUS_Rfunctions.R (line 772, column 85)
      BUS_Rfunctions.R (line 810, column 34)
      BUS_Rfunctions.R (line 811, column 49)
      BUS_Rfunctions.R (line 812, column 81)
      BUS_Rfunctions.R (line 814, column 80)
      BUS_Rfunctions.R (line 854, column 26)
      BUS_Rfunctions.R (line 855, column 34)
      BUS_Rfunctions.R (line 856, column 49)
      BUS_Rfunctions.R (line 857, column 84)
      BUS_Rfunctions.R (line 859, column 83)
      BUS_Rfunctions.R (line 887, column 18)
      BUS_Rfunctions.R (line 897, column 18)
      BUS_Rfunctions.R (line 901, column 18)
```

Please let me know once your done fixing the issues, I will do a secondary review of your code.

**Comment by tnaake** [comment]
Dear @nturaga 

I uploaded a new version of the package to the package builder system implementing all suggestion that you made. Many thanks for these suggestions. 
After uploading, an error occured in CHECK on Windows Server 2012 R2 Standard/x64 (at the level of test_statistical.R unit tests). Since I do not have access to a Windows-operating computer, I wanted to ask if there is a possibility somehow, to dig more into why the package fails at this step. Do you have any suggestions how I could check for this error? 

Best wishes,
tnaake

**Comment by nturaga** [comment]
Hi @tnaake,

I tried running your tests after you made the changes,

```
RUNIT TEST PROTOCOL -- Mon Jul 16 09:18:49 2018
***********************************************
Number of test functions: 4
Number of errors: 1
Number of failures: 1


1 Test Suite :
MetNet RUnit Tests - 4 test functions, 1 error, 1 failure
ERROR in /MetNet/inst/unitTests/test_statistical.R: Error while sourcing  
/MetNet/inst/unitTests/test_statistical.R : Error in get(fun, mode = "function", envir = parent.frame()) :
  object 'stabsel.matrix' of mode 'function' was not found
FAILURE in test_rtCorrection: Error in checkException(rtCorrection(struct_adj, mat_test, cbind(transformations[,  :
  Error not generated as expected


Test files with failing tests

   test_statistical.R
  /MetNet/inst/unitTests/test_statistical.R

   test_structural.R
     test_rtCorrection


Error in BiocGenerics:::testPackage("MetNet") :
  unit tests failed for package MetNet
```

**Comment by tnaake** [comment]
Dear @nturaga ,

thanks for your message. I cannot somehow understand the message:
ERROR in /MetNet/inst/unitTests/test_statistical.R: Error while sourcing  
/MetNet/inst/unitTests/test_statistical.R : Error in get(fun, mode = "function", envir = parent.frame()) :
  object 'stabsel.matrix' of mode 'function' was not found

In my NAMESPACE, I am using `importFrom(stabs,stabsel.matrix)` which should load the `stabsel.matrix` function from `stabs`. Strangely, this seems not to be the case on Windows, however under Mac OS X and Linux the package builds nicely. 

Do you have any idea why this error is created? 

Best,
tnaake

**Comment by tnaake** [comment]
Dear @nturaga 
the package now builds nicely. Could you tell me, please, if there needs to be done anything else from my side or when the package will be accepted? 

Best
tnaake

**Comment by tnaake** [comment]
Dear @nturaga 

I issued a version bump and the package builds nicely. Seems there was some problem with the Windows server. 

Best,
tnaake

**Comment by tnaake** [comment]
Dear @nturaga 

I am wondering when the package will be accepted. We would like to submit a paper soon and would like to have the package accepted before submission. 

Could you please tell me what is delaying the acceptance?

Best,
tnaake

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tnaake.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MetNet\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetNet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
