### ISSUE TITLE
hierinf

### ISSUE THREAD

**Issue by crbasel** [Bioconductor/Contributions#773]
- Repository: https://github.com/crbasel/hierinf

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by crbasel** [comment]
Hi @hpages,

First of all, thanks a lot for reviewing our R package. 

Can you please give me a hint why we receive a warning under windows? I’m puzzled because running R CMD check using win-builder.r-project.org does not return any warning. 

Thanks a lot and best wishes,
Claude

**Comment by lshep** [comment]
@crbasel In the summary section it indicates that the check time is above 5 min. Since the other two platform pass, It will be okay to ignore for now.  @hpages will have a technical review of your package soon.

**Comment by crbasel** [comment]
Hi @lshep,

Thanks for your reply. I'll add testthat::skip_on_bioc() or testthat::skip_on_os("windows") in the next version such that the check time will be shorter. 

Best wishes,
Claude

**Comment by dvantwisk** [comment]
Hello,
I've reviewed your package due to Herve being on vacation.  The package looks very well written and I only have a few things to add.  The [REQUIRED] tags indicate that an issue must either be fixed or responded to.  The [CONSIDER] tags indicate issues where changes are advisable but not necessary.  Please message me back when you have finished making you changes.

GENERAL
- [REQUIRED] remove `bioc-comments.md`, it doesn't seem to be useful once the package
is accepted.

R/GENERAL
- [CONSIDER] Use `BiocParellel` instead of `parellel`. `BiocParellel`
  encapsulates a lot more functionality that just what the `parallel` package
  has, and it is also easier to use. For example, `BiocParallel` figures out the
  number of cores etc automatically behind the scenes.

R/comp-cluster-pval.R
- [REQUIRED] L131-135: Improve efficiency by delcaring `gamma.step` with `vapply`:
```
gamma.step <- vapply(gamma.seq, function(g) {
    min(1, stats::qunatile(pvals / g, g, na.rm = TRUE))
}, numeric(1))
```

R/test-only-hierarchy.R
- [REQUIRED] L185-189: Improve efficiency by declaring `colanmes.multisplit` using
`vapply` as show previosuly.

**Comment by dvantwisk** [comment]
Hello,
It's been a few week since we've last heard from you.  Have you made any progress on this package?  I do need to say that If you don't have any activity within the next two weeks, we'll have to close the issue for the time being.

**Comment by crbasel** [comment]
Hi @dvantwisk,

Thanks a lot for your very helpful review. I'll make the changes in the coming days and push the newest version. Sorry for my delay in replying. I was out-of-office. 

Best wishes,
Claude

**Comment by crbasel** [comment]
Hi @dvantwisk,

Thanks again for your helpful review. I've made the small changes to the R code. 

Best wishes,
Claude

**Comment by dvantwisk** [comment]
The changes look good!  I don't have anything else to add so I'm going to move to accept the package.

**Comment by crbasel** [comment]
Thanks a lot. That's great.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/crbasel.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"hierinf\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hierinf

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
