### ISSUE TITLE
NBSplice

### ISSUE THREAD

**Issue by gamerino** [Bioconductor/Contributions#775]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gamerino/NBSplice

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@lshep will review your package. Please update the vignette so that installation instructions assume the package has been accepted to Bioconductor -- `biocLite("NBSplice)`

**Comment by gamerino** [comment]
Hello!

I have updated the package vignette assuming that NBSplice has been accepted to Bioconductor.

**Comment by gamerino** [comment]
I have updated the fitModel function to solve a problem found when the contrast parameter is specified by the user.

**Comment by lshep** [comment]
**General**

- [ ] Please comment on some differences from existing packages:
[ballgown](http://bioconductor.org/packages/release/bioc/html/ballgown.html)
[EBseq](http://bioconductor.org/packages/release/bioc/html/EBSeq.html) / [EBseqHMM](http://bioconductor.org/packages/release/bioc/html/EBSeqHMM.html)
[IsoformSwitchAnalyzeR](http://bioconductor.org/packages/release/bioc/html/IsoformSwitchAnalyzeR.html)

- [ ] Why did you develop a new class? The data is rectangular and seems like SummarizedExperiment or MultiAssayExperiment should be used or extended. Justify why a new class is needed. There are additional comments about the classes in vignette feedback but again, if you think your new classes are justified it is ok to leave as is but please give explanation .  Best practices involve reusing existing Bioconductor infastructure or at least having wrappers that may incorporate common structures for data types. 


**Man Pages**

- [ ] For data objects: More information on how these were created? What is source? what code was run to construct? Where is the example data taken from? 

- [ ] (optional) It is recommended to document constructor and  method functions for particular classes on the same page. So the IsoDataSet and NBSplice indivudal pages could be combined. This way all the relavant documentation is on one help page rather than a user having to navigate through several to find which was needed. Achieved through @rdname, @describedIn


**Vignette**

- [ ] Input Data - are these geneIso and designMatrix generated from some instrumentation or are they user constructed?  There needs to be more information here. 
- [ ] If using expression counts, the functions can take in matrices but should also  minimally take in SummarizedExperiment objects? could it take in both? 
- [ ] Can the geneIso also be represented as a geneSetCollection object from GSEABase?
- [ ] It seems like relavant genoIso and designMatrix could be pData of a SummarizedExperiment object, so beside individual matrices could work with this object?

- [ ] Your functions aren't actually run in the vignette? You trick it by storing the results and then loading the data objects. These should be run interactively whenever possible.  Please remove the eval=FALSE. 

- [ ] Instead of own class object for IsoDataSet,  please investigate the use of SummarizedExperiment or MultiAssayExperiment. Justify why a new class is needed  

- Like the getter methods! Very nice
- The further exploration functions for your results are also nice! 
- Thank you for including the model information and implementation sections. 


**R code**
- [ ] You define getters for the class but then internal don't use them.  For example in NBTest, object@geneCounts - but you have defined a geneCount() getter method for the class.  Please use the getter methods whenever possible. 
- [ ] For loops like those found at NBTest line # 101, should probably be updated to a vapply for efficiency. See [Vectorize Section](http://bioconductor.org/developers/how-to/efficient-code/)
- [ ] Similarly NBtest for loop at #127 - you could preallocate the data.frame and fill by line rather than the efficient concatentate to the vectors. 
- [ ] Apply the above throughout R code where applicable. 


Please make the adjustments above.  When ready please do another version bump to kick off a new build and comment back here with updates and justifications. 

Cheers

**Comment by gamerino** [comment]
Hello Lori,

Thank you for all your comments about our package. I have pushed a new version of NBSplice fixing many of the issues you identified. I detailed below the changes and suggestions you made me and my responses, in bold text.

Please, let me know about any inconvenient or another change needed.

Cheers


**General**

- _Differences with existing packages: ballgown, EBSeq/EBSeqHMM and IsoformSwitchAnalzeR:_ 
**To our knowledge, the packages ballgown, EBSeq, and EBSeqHMM perform differential isoform expression. However, they don’t evaluate _differential isoform usage_ or _differential splicing_ which is the aim of NBSplice. The IsoformSwicthAnalyzeR package tests differential isoform usage by independent analysis of gene isoforms based on non-parametric tests. We consider that this approach could be useful when the number of replicates per condition is high, as in the IsoformSwicthAnalyzeR paper. However, when a low number of replicates are available, parametric approaches are more appropriated. Our package proposes the identification of differential spliced genes by linear hypothesis test and the Simes test performed on coefficients of a robust parametric model sharing information across gene isoforms. Our approach is also novel because it identifies low-expressed isoforms which are not modeled but their counts are considered on the model fitting avoiding overestimation of high-expressed isoforms.**

- _Why did you develop a new class?:_ **Although we identified that the isoCounts, geneIso and designMatrix objects could be easily represented as the assay, rowData and colData of SummarizedExperiment class, we decided to develop a new class because our assay data is composed of two expression matrices, at the isoform level and at the gene level. In addition, the identification instead of the elimination of low-expressed isoforms is a key on NBSplice. The index of low-expressed isoforms are stored as a class slot and is frequently used to discard or kept those isoforms from the analysis.** 

**Man Pages**

- _For data objects: More information on how these were created? What is source? what code was run to construct? Where is the example data taken from?_ **This information was added to the corresponding documentation files.**

- _(optional) It is recommended to document constructor and method functions for particular classes on the same page. So the IsoDataSet and NBSplice indivudal pages could be combined. This way all the relavant documentation is on one help page rather than a user having to navigate through several to find which was needed. Achieved through @rdname, @describedin_ **We decided to use different man pages to avoid so long documentation pages. To help the navigation we have used the @seealso field to link with another relevant methods** 

**Vignette**

- _Input Data - are these geneIso and designMatrix generated from some instrumentation or are they user constructed? There needs to be more information here._ **This information was added to the corresponding sections.**

- _Can the geneIso also be represented as a geneSetCollection object from GSEABase?_ **We considered that it is not needed because geneIso a single matrix or data.frame with two columns containing isoform and gene IDS. Please, let me known if you think that it is necessary**

- _Your functions aren't actually run in the vignette? You trick it by storing the results and then loading the data objects. These should be run interactively whenever possible. Please remove the eval=FALSE._ **This has been modified**

-_If using expression counts, the functions can take in matrices but should also minimally take in SummarizedExperiment objects? could it take in both?_ **I don't completely understand the question. Is about building an IsoDataSet from a summarizedExperiment object? NBsplice methods have been created based on kallisto and RSEM expression counts which are stored in tab files. For this reason, we have based the IsoDataSet constructor on matrixes or data.frames.**

- _It seems like relavant genoIso and designMatrix could be pData of a SummarizedExperiment object, so beside individual matrices could work with this object?_ **I have explained above why we decided to incorporate a new class instead of using the SummarizedExperiment class.** 

**R code**

- _You define getters for the class but then internal don't use them. For example in NBTest, object@geneCounts - but you have defined a geneCount() getter method for the class. Please use the getter methods whenever possible._ **We have used the getters when it was possible. In the case of the geneCounts slot of an IsoDataSet object it stores an ‘expanded expression matrix’ at the gene level. This matrix is ‘expanded’ because it has as many rows as the isoCount slot has, i.e.: each row represents an isoform. It is useful to avoid time consuming each time that we need to work with the expanded matrix. Whereas, the geneCount getter returns the reduced expression matrix at the gene level, i.e each row represents a gene. When we use the object@geneCounts we are working with the expanded expression matrix.** 

- _For loops like those found at NBTest line # 101, should probably be updated to a vapply for efficiency._ **We have incorporated the use of vapply instead of the loop for in this line.**

- _Similarly NBtest for loop at #127 - you could preallocate the data.frame and fill by line rather than the efficient concatentate to the vectors._ **Done**

**Comment by gamerino** [comment]
Hi Lori,

I have updated NBSplice including the changes you recommended. 

Should I push it again to avoid the warnings in the build report? I didn't see those on my laptop so I suppose they are a temporary warning.

Best

Gabriela

**Comment by lshep** [comment]
Yes please push it again to see if it resolves.  Even if it remains I will review the package again but it would be nice to have the clean report.

**Comment by lshep** [comment]
I'll ignore it for now and have a review for you soon.

**Comment by gamerino** [comment]
Thank you. I'm replicating the build, install and checks steps on my Mac, but I don't get those warnings.

**Comment by lshep** [comment]
Thank you.   While I still strongly encourage expanding or utilizing SummarizedExperiment or MultiAssayExperiment class structure it is your decision as a maintainer. 

Please update the installation instructions as we are currently in the process of updating this site wide. There is a new package on CRAN BiocManager that will install Bioconductor packages and avoid sourcing a script. 

```
if (!require("BiocManager"))
    install.packages("BiocManager")
BiocManager::install("NBSplice", version="devel")
```

**Comment by gamerino** [comment]
Hi Lori,

I have updated the installation instructions as you suggested before.

Best

Gabriela

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gamerino.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"NBSplice\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NBSplice

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
