### ISSUE TITLE
OUTRIDER - OUTlier in RNA-Seq fInDER

### ISSUE THREAD

**Issue by c-mertes** [Bioconductor/Contributions#782]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gagneurlab/OUTRIDER

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by c-mertes** [comment]
Dear @vobencha,

We fixed all errors and reduced the example runtime to be within 5 minutes as requested by Bioconductor. 

We still have 2 warnings in our code which could be addressed easily. 
1. compiled vignette within repo: we currently have it compiled in our repo so people can look at it without installing the software. If required we can remove it.
2. We still have the older R version as requirement so that people can install it also on the 3.4 R version. Here we do not know what the best practice is to keep the package compatible with as many version as possible.

Finally we do have one issue on windows where one test fails on the 32 bit windows version but the 64bit works fine. Is this an issue we have to address or is this fine, since it is also no error in the build report?

**Comment by vobencha** [comment]
Hi,
You need to remove the pdf from vignettes/. If you want the built vignette in the GitHub repo add it to a .gitignore file.

We have the R>=3.5 requirement for new packages because we can't guarantee this package works with older versions of R (i.e., we aren't testing that situation in the package review process). It isn't just the R version that's implied, it's other Bioconductor packages versions that are associated with that version of R. This is ultimately your call. We suggest R>=3.5 but don't require it.

If the Windows issue has never appeared on the SPB report then I can't help fix it. Are you using R 3.5. to develop the package? What is the error? Usually a 32-bit only failure is related to trying to allocate more than 3-4GB in memory.

Valerie

**Comment by c-mertes** [comment]
Hi @vobencha,
We addressed now all issues. We removed the vignette from the repo. We fixed the issue for the 32bit windows version.

We still have the only warning from the R version check (3.4). If Bioconductor does not mind this warning, we would leave it in. We know that Bioconductor cant take responsibility for it but we do test it with travis on GitHub. So we feel comfortable that this will be compatible with it and also continuously test.

Is this fine for now? Or do we still have to address something before you go through the technical review?

**Comment by vobencha** [comment]
Thanks, I think it's ready for review. I'm out for a few days so may not get to this until mid next week.

**Comment by c-mertes** [comment]
Thanks for the heads up. We will then wait for your review.

**Comment by vobencha** [comment]
Hi,
Nice job with the package. A few comments below.

1. Please address these notes from the SPB:
```
File 'C:/Users/pkgbuild/packagebuilder/workers/jobs/782/4f21422/OUTRIDER.buildbin-libdir/OUTRIDER/libs/i386/OUTRIDER.dll':
  Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
  Found 'exit', possibly from 'exit' (C), 'stop' (Fortran)
  Found 'printf', possibly from 'printf' (C)

* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.4 to 3.5.
```
2. Unfortunately we still need to support 32-bit Windows. The examples below with time >20 min need to be addressed. Some of the man pages call the same functions, e.g., 
OUTRIDER, results, aberrant. It looks like the call to OUTRIDER() takes the most time. Can you combine a few of these methods on the same man page so you're calling 
OUTRIDER() less?

tokay1:
```
CheckTime: 69 minutes 6.29 seconds

Examples with CPU or elapsed time > 5s
                                    user system elapsed
OUTRIDER                            1.89   0.23   27.06
results                             1.39   0.11   26.85
plotVolcano                         0.94   0.03   25.45
aberrant                            0.83   0.06   26.36
plotAberrantPerSample               0.79   0.03   25.78
plotQQ                              0.77   0.02   26.91
computePvalues                      0.24   0.01   25.17
fit                                 0.17   0.04   13.78
plotDispEsts-OutriderDataSet-method 0.19   0.00   12.72
plotPowerAnalysis                   0.19   0.00   12.14
```

3. The OutriderDataSet 

This class is identical to RangedSummarizedExperiment:
```
setClass("OutriderDataSet", contains="RangedSummarizedExperiment")
```
What functionality is missing from RangedSummarizedExperiment that motivated the creation of this class? Was it to control the validity?

4. LazyData: true

Please remove this. Setting LazyData to TRUE can slow down the loading of a package.

5. Please remove these \donttest statements or explain why you feel they're needed. I tested a few and they seem to evaluate quickly ...
```
~/repos/github/packageReview/OUTRIDER >grep -R donttest *
man/findEncodingDim.Rd:\donttest{
man/plotCountCorHeatmap.Rd:\donttest{
man/plotQQ.Rd:\donttest{
man/plotPowerAnalysis.Rd:\donttest{
man/computeGeneLength.Rd:\donttest{
man/plotExpressionRank.Rd:\donttest{
```

**Comment by vobencha** [comment]
Thanks for making the changes.
2. Yes, please work on this some more to reduce the time.
3. Why not add import(DESeq2, except="results") to the NAMESPACE to avoid the clash. The results() function doesn't need to be an S4 generic unless you plan to dispatch on different objects. I only see the one method for 'OutriderDataSet' obejcts. results() does much more than extract values from a class slot so technically it isn't an accessor/getter. I'd recommend leaving this as a regular function named compileResults().

**Comment by c-mertes** [comment]
hey @vobencha, 

2. I worked a bit on the R CMD check runtime, but still get the warning. Im now around 7min on windows the rest is ok on the SPB. I really do not know why it is so slow. On a virtual box with windows 32 bit it runs through in 5 mins. And I also think its not the problem of the tests or examples I get the following timing locally on windows:

```
> system.time(devtools::test())
Loading OUTRIDER
Testing OUTRIDER
√ | OK F W S | Context
...
    user  system  elapsed 
  23.50      1.36      28.45 
> system.time(devtools::run_examples(show=FALSE))
Updating OUTRIDER documentation
Loading OUTRIDER
Running 19 example files in OUTRIDER
...
    user  system elapsed 
  19.62      2.49     39.41 
```

Also when looking at the timings on the build server it looks like most of the time is spend in a waiting state since the user and the system runtime is very low compared to the elapsed one.

I would appreciate any help or directions. 

3. Thanks for the tip with import. Since the workflows will probably go hand in hand a bit my I idea is to dispatch on the `results` function with an DESeq2 and an OUTRIDER data set object. I thought of it like a default function most of the software package will have to extract the results.

Best,
Christian

**Comment by vobencha** [comment]
7 minutes is close enough for me. Thanks for working on it.
Package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/c-mertes.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"OUTRIDER\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OUTRIDER

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
