### ISSUE TITLE
ipdDb

### ISSUE THREAD

**Issue by sklas** [Bioconductor/Contributions#783]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DKMS-LSL/ipdDb

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
The package looks in great shape and close to acceptance.  A few minor comments below:

**data**
- [ ] Could you include a script in inst/script that describes how you created the data submitted to AnnotationHub (even if it is sudo code or text)

**man dir**
- [ ] Can .IpdDb.Rd.un~  be removed? (git remove)

**README/vignette**
- [ ] typo extra close parenthesis alleles <- hla$getAlleles(available_loci[1]))
- [ ] when I try to run
```
> sequences <- hla$getReferences(alleles)
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  'getReferences' is not a valid field or method name for reference class "IpdDb"
> sequences <- hla$getReferences(c("HLA-A*01:01:01:01", "HLA-A*01:01:01:03" ))
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  'getReferences' is not a valid field or method name for reference class "IpdDb"
```
- [ ] And when I try to run 
```
> structures <- hla$getStructure(ipd.Hsapiens.db, alleles)
Error in .f(.self, ...) : unused argument (alleles)
> structures <- hla$getStructure(ipd.Hsapiens.db, c("HLA-A*01:01:01:01", "HLA-A*01:01:01:03" ))
Error in .f(.self, ...) : 
  unused argument (c("HLA-A*01:01:01:01", "HLA-A*01:01:01:03"))
```

After these few points are cleaned up please do a version bump and comment back here that you are ready for a re-review. 
Cheers

**Comment by sklas** [comment]
Hi Lori,

thanks for your review and the help with uploading the data.

Everything should be fixed now. 
The make-data.R script contains some general explanations and a working condensed extract of an in-house package.
Hope this is ok.

Cheers,
Steffen

**Comment by lshep** [comment]
Sorry about that.  One last minor thing.  While your package deals and provides a wrapper to annotationData, the package itself really is a software package.  Could you change the views to be from the [Software category and subcategories](http://bioconductor.org/packages/release/BiocViews.html#___Software) . We think this will add users to finding the package.

**Comment by sklas** [comment]
Hi,

sure no Problem. The views are added and I made the Readme to a Vignette. BiocCheck() started to complain about missing vignettes before.

Cheers,
Steffen

**Comment by lshep** [comment]
Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sklas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ipdDb\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ipdDb

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
