### ISSUE TITLE
SIMD

### ISSUE THREAD

**Issue by FocusPaka** [Bioconductor/Contributions#788]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FocusPaka/SIMD

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# SIMD review

The title of the package SIMD is not informative to the user. Please
consider changing it to something more recognizable and indicative of
your package functionality.

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* The Description is not adequate. It needs to be like the abstract to a paper. 

## NAMESPACE

ok

## man

ok

## vignettes

* Vignette needs to be improved significantly. Please follow this
  guide
  http://bioconductor.org/developers/package-guidelines/#vignettes.

* Consider using `BiocStyle` for the markdown formatting. 

## data

ok

## NEWS

* NEWS file needs to be parsable by `utils::news()`

## R 

* Follow
  http://bioconductor.org/developers/how-to/coding-style/ as closely
  as possible.

* remove commented out code

* Looks like the only thing changing here is the `skip` and
  `nrows`. Write a function to minimze code repetition.
  
```
    tag_cpg1 <- read.table(cpgsitefile, header = FALSE,
                           skip = 0,nrows = floor(nrec/4),as.is = TRUE)
    tag_cpg2 <- read.table(cpgsitefile, header = FALSE,
                           skip = floor(nrec/4),nrows = floor(nrec/4), as.is = TRUE)
    tag_cpg3 <- read.table(cpgsitefile, header = FALSE,
                           skip = 2 *floor(nrec/4),nrows = floor(nrec/4), as.is = TRUE)
    tag_cpg4 <- read.table(cpgsitefile, header = FALSE,
                           skip = 3 *floor(nrec/4),nrows = nrec, as.is = TRUE)
```

vs

```
readcpgsite <- function(skip, nrows) {
	read.table(cpgsitefile, header = FALSE, skip = skip, 
               nrows=nrows, as.is = TRUE)
	}
	
tag_cpg1 <- readcpgsite(0, floor(nrec/4))
...
```

* In emalgth.R, used vectorized functions for `rowSums` and `colSums`
  instead of `apply` functions across a margin. Do this accross your
  package.

* I highly encourage that you follow the coding style and reformat
  your code. Also follow the Best practices guide,
  http://bioconductor.org/developers/package-guidelines/#rcode. Your
  code can be improved a lot.
  
  http://bioconductor.org/developers/how-to/efficient-code/
  

## src

Please follow the coding priniciples shown here
http://bioconductor.org/developers/package-guidelines/#ccode


Once you have made the initial changes, I will go through your code
once again and review it. Please leave a detailed response on all the
changes made.

**Comment by nturaga** [comment]
## Update

* EMalgorithm.R, in a function you should always try to put your
  return statement at the end

		if (is.null(writefile)) {
			return(cpg20)
		} else {
			write.table(cpg20, writefile, sep = "\t", quote = FALSE, row.names = FALSE)
		}
		
		
	vs
	
		if(!is.null(writefile))
			write.table(cpg20....)
		return(cpg20)
		
		
 You should use this same logic in all your functions through out your code.
		
		
* EMtest.R, instead of writing at each line, you can paste your output
  lines in a single `paste` call and then use a single `write` call.

		if (!is.null(reportfile)) {
		   write(paste("s1/s2:", fws1s2), reportfile, append = TRUE)
		   write(paste("s3/s4:", fws3s4), reportfile, append = TRUE)
		   if (length(cpg[kk[, 4] != 0, 1]) != 0) {
			   write(paste("N1(sum of MRE-CpG!=0 ):", N1), reportfile, append = TRUE)
			   write(paste("N2(sum of MRE-CpG!=0 ):", N2), reportfile, append = TRUE)
			   write(paste("N3(sum of MRE-CpG!=0 ):", N3), reportfile, append = TRUE)
			   write(paste("N4(sum of MRE-CpG!=0 ):", N4), reportfile, append = TRUE)
			   write(paste("c1:", rmd21), reportfile, append = TRUE)
			   write(paste("c2:", rmd43), reportfile, append = TRUE)
		   }
		   write(paste("Number of windows:", length(pall)), reportfile, append = TRUE)
		   write(paste("Number of p<1e-8:", sum(pall < 1e-08)), reportfile, append = TRUE)
		   write(paste("Number of p<1e-3:", sum(pall < 0.001)), reportfile, append = TRUE)
		   write(paste("Spend time:", spendtime), reportfile, append = TRUE)
	   }		
	
	
vs

	if(!is.null(reportfile)) {
		str <- paste("s1/s2:", fws1s2, 
		             "\n",
			         "s3/s4:", fw3s4
					 )
		write(str, reportfile)
		..... ## You can do this for the if else statements too
	}
		

* Please don't use `biocLite` anymore in the vignettes or in your
  package README etc. We have upgraded to a package called
  `BiocManager`.

	Example:
  
		BiocManager::install(c('edgeR', 'statmod','methylMnM'))
		
		
* There are also a few `eval=FALSE` sections in your vignette which
  should not be there. Your entire vignette needs to be evaluated. If
  not, please explain why?.

**Comment by nturaga** [comment]
@FocusPaka Are you ready for another review?

**Comment by FocusPaka** [comment]
Hi @nturaga, 
Thanks for your comments and suggestion! Below are responses to your reports.
1.Put return statement at the end of functions.
2.For function EMtest.R, paste output lines in a single paste call and use a single write call.
3.Use BiocManager instead of biocLite in the vignette.
4.Move eval=FALSE sections in my vignette to ensure vignette be evaluated.

Best regards with many thanks,
FocusPaka

**Comment by nturaga** [comment]
Hi @FocusPaka 

Your package ha

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/FocusPaka.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"SIMD\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SIMD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
