### ISSUE TITLE
appreci8R

### ISSUE THREAD

**Issue by sandmanns** [Bioconductor/Contributions#789]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sandmanns/appreci8R

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sandmanns** [comment]
The appreci8R imports quite some other R-packages. I think, this is why the installation takes a while and why the R CMD check exceeds the limit of 5 minutes in case of Windows (on Linux and OS X it seems to be faster).
I already minimized the examples. And actually, I do not know what to do in addition to speed up the "check". 
Do you have any ideas on what I could do to speed it up? Or would you maybe review the appreci8R despite this remaining Warning...? :-)
Thanks a lot in advance!

**Comment by lshep** [comment]
Since this check is clear on MAC and Linux I will review the package and ignore this WARNING.  I will have a technical review in a few days.

**Comment by sandmanns** [comment]
Cool! Thank you so much!
I am looking forward to it!

**Comment by lshep** [comment]
Hello, 
Very nice package.  Please see the following comments:

**Build Report**
- [ ] Unit tests are good practice. Highly recommend adding a few
- [ ] Clean up coding practice note about 1:...


**Data**
- [ ] Please include a inst/script/ file that describes how the data in extdata
was generated (can be sudo code or text).  It should have some details on the
instrumentation used and settings used for generation of files. 
- [ ] Is there a reason existing data sets of bam files (like from Rsamtools)
could not be used and you needed to include your own? 

**Vignette**
- [ ] Please remove intermediate files (toc/tex/etc) - should only need the Rnw
file as the vignette will be generated automatically. 
- [ ] We are updating our installation methods.  Please Update biocLite to
BiocManager::install("appreci8R")

**filterTarget function**
- [ ] it seems like it should also be able to take in a GenomeRanges object for
targetRegions
- [ ] Could this function be designed to work with a vcf object read in using
VariantAnnotation::readvcf() as that is the standard Bioconductor way for
importing a vcf file. 
- [ ] A more standard output for this representation rather than a list is a
GRangesList. 


**General**
Objects reporting genomic positioning should be converted to a GenomicRanges or
GRangesList from the GenomicRanges package. This is a very common and consistent
representation throughtout Bioconductor. This is true for all the input and
output of your functions (rather than data.frames or lists of data.frames). The
other option would be the VariantAnnotation representation for vcf like a
CollapsedVCF


Please address or comment on the above issue.  When ready please perform another version bump and comment back here for a re-review. 
Cheers
Lori

**Comment by sandmanns** [comment]
Dear Lori,

Thanks a lot for your very quick feedback!
These are my comments on the points you mentioned:

**Build Report**
- [ ] Unit tests are good practice. Highly recommend adding a few
-> Currently there are no unit tests. However, each functions contains internal
   checks to make sure files exist, input is not empty etc. so that the functions
   don't crash. Would that be okay?
- [x] Clean up coding practice note about 1:...
-> The only cases of 1:... that remain are lines like:
   temp2<-cbind(temp1[,1:3],etc...)
   As temp1 is an internal object, I know that it contains (more than) 3 columns.
   Would it be okay to keep it like this?

**Data**
- [x] Please include a inst/script/ file that describes how the data in extdata
was generated (can be sudo code or text). It should have some details on the
instrumentation used and settings used for generation of files.
-> included inst/script/information.txt; this is hopefully okay?
   file contains information on all files present in inst/extdata (how they were
   generated etc.)
- [ ] Is there a reason existing data sets of bam files (like from Rsamtools)
could not be used and you needed to include your own?
-> We hope that the appreci8R performs equally well on all data sets of bam files.
   However, for the exemplary data, we had the following idea: We developed the 
   appreci8R on the basis of our appreci8 pipeline. In our paper, we present the
   analyses of a wide set of samples (training and test samples). We invested a
   lot of work into validating the numerous mutations, polymorphisms and artifacts
   detected in these samples. So, after all we are quite confident considering
   biological truth for these samples.
   For the exemplary data, we included two samples from the original training
   data set. The BAM files files (containing more than just 2 exemplary regions) are 
   available via the NCBI SRA and information on all mutations and polymorphisms 
   (and artifacts that were detected by various tools) in these samples are available 
   as supplementary information.
   We liked to include these samples as exemplary data as we are confident about the
   categorization of their calls as mutations, polymorphisms and/or artifacts. 
   So, we know that the appreci8R performs correctly on these sampels. And in case
   a user is interested to extend the example, he or she can download the complete
   BAM from the SRA.

**Vignette**
- [x] Please remove intermediate files (toc/tex/etc) - should only need the Rnw
file as the vignette will be generated automatically.
- [x] We are updating our installation methods. Please Update biocLite to
BiocManager::install("appreci8R")

**filterTarget function**
- [x] it seems like it should also be able to take in a GenomeRanges object for
targetRegions
- [ ] Could this function be designed to work with a vcf object read in using
VariantAnnotation::readvcf() as that is the standard Bioconductor way for
importing a vcf file.
-> We opted against this solution when writing the package for the following reasons:
   Although vcf files should be the standardized output format of any variant
   calling tool, we experienced that several tools (e.g. VarScan or Vardict)
   report (differently structured) txt files. Thus, it would always be the necessary
   to convert one to the other, as the txt-files cannot be read in as vcf files.
   Or - even easier - to read in vcf files (and txt files) as data.frames. That's what
   we decided to do.
   Additionally, CollapsedVCF objects need more storage compared to data.frames. If 
   input from a very sensitive calling or WES results are analyzed, this aspect can
   be essential.
- [ ] A more standard output for this representation rather than a list is a
GRangesList.
-> We see your point that a GRangesList would be the more standard output. Unfortunately,
   it is a bit impractical to realize it for this function. The input of the different
   variant calling tools has not been normalized yet. As we just report chr and pos
   in our list of data.frames, coversion to chr, start and end has to be done via 
   information on ref and alt. In the non-normalized form this is can be quite challenging
   (e.g. C > T,A or G > -C). To define a proper IRanges for the GRanges objects, 
   normalization is inevitable.
   Well, it would be impractical to normalize everything twice, right? So, if possible,
   I would really like to keep the data.frame for this very first function.


**General**
- [x] Objects reporting genomic positioning should be converted to a GenomicRanges or
GRangesList from the GenomicRanges package. This is a very common and consistent
representation throughtout Bioconductor. This is true for all the input and
output of your functions (rather than data.frames or lists of data.frames). The
other option would be the VariantAnnotation representation for vcf like a
CollapsedVCF
-> Fixed for all functions except for filterTarget (see comment above)

The WARNING was again just on Windows, because it took 5 minutes and 8 seconds... :-)

Best,
Sarah

**Comment by lshep** [comment]
Thank you for providing justification for the above implementation and thank you for converting to GenomicRanges for the majority of the output.  The package looks good and I will allow the few exceptions to the build report.

**Comment by sandmanns** [comment]
Thank you so much for this great, quick review!
Just let me know in case there is anything left I can do.

Looking forward to seeing the appreci8R on Bioconductor :-)

Best,
Sarah

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sandmanns.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"appreci8R\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/appreci8R

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
