### ISSUE TITLE
LoomExperiment

### ISSUE THREAD

**Issue by dvantwisk** [Bioconductor/Contributions#791]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/LoomExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@hpages can you review this issue? for dumb technical reasons I'll only update the assigned reviewer once another package is in the review queue. Happy to take one or two of yours in exchange...

**Comment by hpages** [comment]
@mtmorgan Sure, please assign to me. My understanding is that @dvantwisk  already volunteered to pick up one of my assigned packages. Thanks Daniel!

**Comment by hpages** [comment]
Should I go ahead and assign it to myself?

**Comment by hpages** [comment]
Sorry @dvantwisk @mtmorgan for the long delay. Here is my initial review. I found the *LoomExperiment classes to be an interesting case from a class design point of view. The fact that you can represent something as complex as a loom experiment by just adding the rowGraphs and colGraphs components to the standard SummarizedExperiment derivative is really neat. Impressive work overall.

## R CMD check

Emits the following note that should not be ignored (true positive):
```
* checking R code for possible problems ... NOTE
.importLoom_GRangesList : <anonymous>: no visible binding for global
  variable ‘group_name’
Undefined global functions or variables:
  group_name
```

## The LoomExperiment class hierarchy and other design considerations

The LoomExperiment class hierarchy is flat (i.e. all the concrete subclasses are at the same level):
```
                               LoomExperiment
                                 (virtual)
                              ^      ^       ^
                             /       |        \
                            /        |         \
                           /         |          \
                          /          |           \
                         /           |            \
  SummarizedLoomExperiment  RangedLoomExperiment  SingleCellLoomExperiment
         (concrete)              (concrete)             (concrete)
```
This design is awkward because OTOH the 3 LoomExperiment concrete subclasses extend SummarizedExperiment, RangedSummarizedExperiment, and SingleCellExperiment, respectively, and these 3 classes form a *linear* class hierarchy:
```
                            SummarizedExperiment
                                 (concrete)
                                     ^
                                     |
                         RangedSummarizedExperiment
                                 (concrete)
                                     ^
                                     |
                            SingleCellExperiment
                                 (concrete)
```
So it would be more natural and cleaner design to have the 3 LoomExperiment concrete subclasses also organized in a linear hierarchy that goes along the SummarizedExperiment hierarchy:
```
           SummarizedExperiment    <----  SummarizedLoomExperiment
                    ^                               ^
                    |                               |
        RangedSummarizedExperiment <----    RangedLoomExperiment
                    ^                               ^
                    |                               |
           SingleCellExperiment    <----  SingleCellLoomExperiment
```
One immediate benefit of this new design is that you don't need the LoomExperiment virtual class anymore (and you should take advantage of this to rename SummarizedLoomExperiment -> LoomExperiment). Another potential benefit of the linear hierarchy is that you might run into more opportunities to take advantage of inheritance. In other words you might be able to reduce the number of methods you need to define and/or you might be able to simplify your methods by making more use of callNextMethod().

It would be somewhat convenient if one could plug one of the 3 SummarizedExperiment derivatives in a LoomExperiment() constructor, that is, plug a SummarizedExperiment or RangedSummarizedExperiment or SingleCellExperiment instance and get a LoomExperiment or RangedLoomExperiment or SingleCellLoomExperiment instance, respectively.

Shouldn't the "a" and "b" columns of a LoomGraph object be of type integer instead of numeric?

The semantic of LoomGraph objects is surprising: Their length is always 2 or 3. You can do `lg[1:1e6]` (and it's a no-op) or `lg[-2]` and it removes all its edges. I know I know it's all intended but I'm playing naive here (it's part of the game). `c()` does something not useful and is not an endomorphism:
```
    > c(lg, lg)
    DataFrame with 3 rows and 6 columns
              a         b         w         a         b         w
      <numeric> <numeric> <numeric> <numeric> <numeric> <numeric>
    1         1         3       100         1         3       100
    2         2         2        10         2         2        10
    3         3         1         1         3         1         1
```
Note that having [ deviate from the semantic of the parent class (`[`) is not a good idea. There is a lot of code around that deals with DataFrame objects and assumes that these objects support the DataFrame API and its semantic. More generally speaking an important principle is that when you extend a class your new class should respect the semantic of the class that you extend. Don't override methods with new methods that do something completely different (i.e. that change the semantic).

Conceptually a LoomGraph object is a vector of edges (so is not a 2D object) and its length is the number of edges. Have you considered using or extending SelftHits instead of DataFrame? A SelfHits object represents a vector of oriented edges between a set of nodes numbered from 1 to N. For example:
```
    > SelfHits(2:5, 6:3, 10)
    SelfHits object with 4 hits and 0 metadata columns:
               from        to
          <integer> <integer>
      [1]         2         6
      [2]         3         5
      [3]         4         4
      [4]         5         3
      -------
      nnode: 10
```
Unlike DataFrame, this is a 1-dimensional object and its length is the number of edges. You could use a metadata column or add a slot for the weigths (mark that slot as a parallel slot and that will give you `[` and `c()` for free).

Is it expected that rbind'ing or cbind'ing *LoomExperiment objects drops the `rowGraphs` and `colGraphs` components?

## Man pages

### Man page for LoomGraphs objects

The Description section says:
```
      A description of the LoomGraphs class for storing multiple LoomGraph objects.
```
Note that the sentence in the description field should provide a description so should not start itself with "A description".

In the Arguments section, the description of the ... argument of the `LoomGraphs()` constructor is:
```
      ...: Arguments to pass to the ‘SimpleList’ constructor.
```
I'm not sure why the SimpleList constructor is mentioned here. By looking at the code of the LoomGraphs() constructor it doesn't seem that it's passing its arguments to the SimpleList constructor.
 
Anyway, generally speaking it is not so relevant or interesting for the end user to know **how** arguments passed to a function are going to be handled or processed internally. A much more important thing the user needs to know is **what** those arguments should be. So for the `...` argument of the `LoomGraphs()` constructor, just say
```
      ...: LoomGraph objects.
```

Examples section: It's not always easy to show compelling/exciting examples (we all struggle with this) but if the purpose of the subsetting example is to show the user that a LoomGraphs object can actually be subsetted I would choose a subsetting operation that is not a no-op.

### Description of the LoomGraph class (from its man page)
```
     A description of the LoomGraph class for storing multiple LoomGraph objects.
```
The LoomGraph (singular) class cannot not store multiple LoomGraph objects (that's what the LoomGraphs (plural) class does). Looks like the description of LoomGraphs objects was copied here but not edited.

### Man page for LoomFile class

The Description field
```
     A ‘LoomFile’ object is the base class for classes representing files accessible
     with ‘rtracklayer’. It wraps a resource (either a path, URL or connection).
```
sounds very generic and doesn't really tell me anything about what a LoomFile object is. It actually seems to be a copy of the description of RTLFile objects from the rtracklayer package. Note that RTLFile is a virtual class with many subclasses and LoomFile is one of them. You can see this with `showClass("RTLFile")`. The fact that the description of RTLFile objects is generic is expected because it's a virtual class whose sole purpose is to regroup a big collection of concrete subclasses under the same banner. But the man page for a concrete subclass should provide details about what this concrete subclass really is. In the case of a LoomFile object, I guess this is an object that represents a loom file and the man page could give a quick explanation of what this kind of file is. Providing URLs to more information about loom files is fine and actually good practice (rather than repeating information that is already available somewhere on the internet).

I would suggest that you add the LoomFile alias to the man page of the LoomFile class. This will allow people to access the man page with just `?LoomFile` which is less typing that `class?LoomFile` (and many end-users don't know about the `class?<classname>` syntax anyway, let's keep in mind that most people get exposed to S4 for the first time when they start using Bioconductor).

### Description of the `import` method for LoomFile objects (from its man page):
```
    Imports a LoomExperiment to a LoomFile
```
Should be "from" instead of "to". (And same problem in the title.)

### Man page for L1_DRG_20_example.loom

"the total size of" repeated in the Description section

## Vignette

- I would advice against using the term "Experiment object" when what you really mean is "SummarizedExperiment object" or "SummarizedExperiment derivative". By using the term "Experiment object" you suggest that Bioconductor has an Experiment class which is not the case. Furthermore if one is added in the future it will make the use of "Experiment object" even more problematic.

- Instead of
    ```
    A LoomGraph object extends the S4Vectors::DataFrame object 
    ```
    it's slightly preferrable to say
    ```
    The LoomGraph class extends the DataFrame class defined in the S4Vectors
    package
    ```
  or
    ```
    A LoomGraph object is a DataFrame derivative
    ```

- Since a LoomGraph object is a DataFrame derivative there is no need to say that "All columns are of equal length" in the list of requirements. Only list the requirements that are not already enforced by the DataFrame class.

- Some minor typos/tweaks:

    - "One can also simply plug the the arguments" --> "the" repeated

    - "We will use the following SingleCellLoomExperiment for the remainder of the package." --> should be "of the vignette" instead of "of the package"

    - "The colGraphs and rowGraphs slots correspond to the col_graphs and row_graphs in the Loom File format" --> shouldn't it be something like "the col_graphs and row_graphs **fields** in the Loom File format"? or columns? or components? It feels like a word is missing between "the col_graphs and row_graphs" and "in the Loom File format"

## Code

- You use a mix of `"` and `'` for string literals in your code. Stick to one style (use of double-quote is preferred for consistency with what R uses by default to print strings).

- Why would you do
    ```
    nrow(df[grep('GRanges', df$name),]) > 0
    ```
    when you can just do
    ```
    length(grep('GRanges', df$name)) > 0
    ```
    or even just
    ```
    any(grepl('GRanges', df$name))
    ```
    The last form is the most readable.

    But the important bit is that you don't need to subset the data frame here (although not terribly pricey, this subsetting has a cost that is not neglectable).

**Comment by dvantwisk** [comment]
The changes to `LoomExperiment` in response to your review are complete. I've changed the class structure, made it so `LoomGraph` now extends `SelfHits`, and made all your suggested code and documentation changes. These changes were rather significant, so I would appreciate a thorough look through them.

A few issues I've experienced:
- Although I've implemented your class hierarchy system, there are some things that I don't think it can easily do.
  - First off, I don't think a single `LoomExperiment` constructor can be used for all `LoomExperiment` objects. My case in point being that there is nothing particularly distinguishable about the arguments to the `RangedLoomExperiment` class and `SingleCellLoomExperiment` class (that is a combined consturctor could not tell the difference between the two).
  - Secondly, I still needed to implement separate method for `show` and `[` on each object. This is because each class inherits from both the `LoomExperiment` class one step above it and their respective "Experiment" class. Both of these classes have separate methods for `[` and `show` and I don't know of a way to specify which signature to dispatch upon (e.g. `SingleCellLoomExperiment` objects were using `SingleCellExperiment`'s `show` method, though I wanted it to use `RangedLoomExperiment`'s `show` method (which that class inherited from `LoomExperiment`. For this reason, I had to declare separate show methods so `SingleCellLoomExperiment` objects would now have a show method that dispatched on the`SingleCellLoomExperiment` class.)
- I've implemented the `selectHits()` and `dropHits()` methods that dispatch on LoomGraph and LoomExperiment objects. These methods allow the user to select or drop entries from the LoomGraph objects based on the integer value. `dropHits()` also has a replacement method, `dropHits()<-` in which the select node will be replaced with new entries, i.e. `dropHits(lg, c(1, 2, 3) <- c(7, 8, 9)` will replace all edges named 1, 2, and 3 with 7, 8, and 9 respectively. I've added generics for these as well.
Do these names sound fine or would you recommend different names? Also, I've had some trouble with the `dropHits()`/`selectHits()` dispatch on `LoomExperiment` in that as it is now, it will only act on the `colGraphs` and `rowGraphs` slots of the `LoomExperiment` object. One would expect this object to also subset the rows and columns of the LoomExperiment object in the same way the `SummarizedExperiment` object would be subsetted. However, the machinery to do this is in `SummarizedExperiment`'s `[` method, but since `LoomExperiment` already has a `[` method, I can't call it. Is there a way to select which method's signature to dispatch on.

Thank you for all the help and insight on the package.

**Comment by hpages** [comment]
Hi Daniel,
Thanks for the update. All these changes sound good. I'll take a look next week.
H.

**Comment by hpages** [comment]
Hi Daniel,

Thanks for these changes and for all your work on the LoomExperiment package. Things look better but there are still some problems with subsetting and binding. Plus a few other minor things (mostly cosmetic). See details below.

H.

- Your `selectHits()` generic masks the `selectHits()` generic defined in S4Vectors. Please choose a different name. I would actually argue that there is not much value in exporting and documenting the helper functions (currently `selectHits()` and `dropHits()`) used internally by the subsetting methods for LoomExperiment derivatives. If you don't export and don't document them, then they won't be able to conflict so it doesn't matter anymore how you name them. But it might very well be that you don't need these helper functions at all. See below why...

- Since the `from` and `to` slots of a LoomGraph object are supposed to contain col/row numbers corresponding to entries in the LoomExperiment object, these col/row numbers need to be updated when subsetting the LoomExperiment object changes those numbers. Let's take for example the following object:
    ```
    le <- LoomExperiment(list(counts=matrix(runif(25), nrow=5)))
    rowGraphs(le) <- LoomGraphs(LoomGraph(2:4, 1:3))

    rowGraphs(le)[[1]]
    # LoomGraph object with 3 hits and 0 metadata columns:
    #            from        to
    #       <integer> <integer>
    #   [1]         2         1
    #   [2]         3         2
    #   [3]         4         3
    #   -------
    #   nnode: 4
    ```
    If I remove the 1st row (e.g. with `le[-1, ]`), this removes the 1st edge of the rowGraphs object, which makes sense, but it doesn't update the row numbers contained in the `from` and `to` slots:
    ```
    rowGraphs(le[-1, ])[[1]]
    # LoomGraph object with 2 hits and 0 metadata columns:
    #            from        to
    #       <integer> <integer>
    #   [1]         3         2
    #   [2]         4         3
    #   -------
    #   nnode: 4
    ```
    The 3->2 and 4->3 edges should now be 2->1 and 3->2 to reflect the fact that the LoomExperiment object has lost its 1st row. Furthermore, because row/col numbers are not updated, I will sometimes end up with an invalid object:
    ```
    broken_le <- le[-(1:2), ]

    rowGraphs(broken_le)[[1]]
    # LoomGraph object with 1 hit and 0 metadata columns:
    #            from        to
    #       <integer> <integer>
    #   [1]         4         3
    #   -------
    #   nnode: 4

    validObject(broken_le)
    # Error in validObject(broken_le) : 
    #   invalid class “LoomExperiment” object: All LoomGraph objects in LoomExperiment must reference a row in the LoomExperiment
    ```
    I think that the transformation that your LoomGraph objects need to go thru during subsetting of a LoomExperiment object is something along the line of what `S4Vectors::remapHits()` does. So you might not even need your `selectHits()` or `dropHits()` internal helpers.

- `rbind()` and `cbind()` don't drop the rowGraphs or colGraphs components anymore but they still drop information:
    ```
    rowGraphs(rbind(le, le))[[1]]
    # LoomGraph object with 3 hits and 0 metadata columns:
    #            from        to
    #       <integer> <integer>
    #   [1]         2         1
    #   [2]         3         2
    #   [3]         4         3
    #   -------
    #   nnode: 4
    ```
    Only the edges coming from the 1st object were propagated. Shouldn't the edges of the 2nd object also be propagated so we see 6 edges in the combined object? Note that the 3 edges coming from the 2nd object will need to be modified to reflect the fact that rows 1-5 in the original object have become rows 6-10 in the combined object.

- The number of nodes of the LoomGraph objects contained in a LoomExperiment object should always be the same as the number of rows or cols of the LoomExperiment object. The validity method for LoomExperiment objects should check that. Also subsetting, `rbind`'ing, `cbind`'ing, and more generally any endomorphic transformation, should make sure that the LoomGraph objects in the returned LoomExperiment object have an `nnode()` that is in sync with the number of rows or cols.

- My suggestion for the `LoomExperiment()` constructor was that one should be able to pass a SummarizedExperiment derivative to it and get the right thing e.g. if I pass a SingleCellExperiment instance to it I should get a SingleCellLoomExperiment instance, not a LoomExperiment instance as it is the case right now.

- Man page for LoomGraph class:
     ``` 
     Its purpose is to store multiple ‘col_graph’ or ‘row_graph’ as specified
     by the ‘loom’ file format.
    ```
    Note that you also use this sentence to describe the LoomGraphs class and it's appropriate there. However the LoomGraph class can only store a single graph so the use of "multiple" is not appropriate here.

- Rendering problem when I do `?LoomGraph` (probably due to a missing `\` in front of "code"):
    ```
    The LoomGraph class extends the codeSelfHits class.
    ```

- It's very likely that your reader has never heard about the SelfHits class so it is worth providing a little extra details:
    ```
    The LoomGraph class extends the SelfHits class defined in the S4Vectors package.
    ```

- Also the \seealso section in `?LoomGraph` should be updated to point to the SelfHits class instead of the DataFrame class.

- Subsetting example in `?LoomGraphs` is still a no-op (see my previous feedback about this).

- "The LoomGraph class" section of the vignette needs to be updated (it's still from the time when LoomGraph derived from DataFrame).

- You still use unnecessarily complicated code (e.g. `nrow(ls[grep('some_string', ls$name),]) > 0`) to detect whether `"some_string"` occurs in the column of a data frame (see my previous feedback about this).

- Title for LoomFile man page incorrect (see my previous feedback about this).

- Man page for LoomFile should probably reference some official doc about loom files (by providing a reference section with a link).

**Comment by dvantwisk** [comment]
Thanks for getting back to me. This is a very thorough examination and will be very helpful with refining the package. I will message you back once I make the changes.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dvantwisk.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("LoomExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/LoomExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
