### ISSUE TITLE
FoldGO

### ISSUE THREAD

**Issue by DanWiebe** [Bioconductor/Contributions#799]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DanWiebe/FoldGO

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vobencha** [comment]
Hi,
Please fix these issues flagged by the SPB:
```
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.

* checking dependencies in R code ... NOTE
package 'methods' is used but not declared

* checking R code for possible problems ... NOTE
FoldSpecTest: no visible global function definition for new
FuncAnnotGroupsTopGO: no visible global function definition for new
GAFReader: no visible global function definition for new
GeneGroups: no visible global function definition for new
runFuncAnnotTest,FuncAnnotGroupsTopGO: no visible global function
  definition for new
runFuncAnnotTest,FuncAnnotGroupsTopGO: no visible global function
  definition for p.adjust
Undefined global functions or variables:
  new p.adjust
Consider adding
  importFrom("methods", "new")
  importFrom("stats", "p.adjust")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').

WARNING: R CMD check exceeded 5 min requirement
```

**Comment by DanWiebe** [comment]
Dear Bioconductor reviewers,
I have fixed issues mentioned above. Now there is only one warning for Mac and Linux: 
Product from R CMD build exceeds 4 MB requirement: 4.0916 MB and 4.1382 MB. 
Do I have to fix it?
Sincerely yours, Daniil Wiebe

**Comment by vobencha** [comment]
Hi,

1) I'd recommend setting LazyData to FALSE in DESCRIPTION. When TRUE, the package takes longer to load and can create problems for others depending on your package.

2) S4 classes need getters and setters and should be documented on the man page.

3) You've got 58 man pages. It's hard to imagine a user will be able to find each of these individual functions. Please consider combining these by common use into 10 or less man pages. Also add /seealso sections with links to related functions.
```
~/FoldGO/man >ls | wc -l
58
```
4) Several man pages are incomplete, e.g., read.Rd is very sparse:
```
\name{read}
\alias{read}
\title{Read GAF file}
\usage{
read(object)
}
\arguments{
\item{object}{- Object of GAFReader class}
}
\value{
- object of GAFReader class
}
\description{
Read GAF file
}
```
5) read() was created as an S4 generic, a method was defined for GAFReader object but neither of these were exported. I would recommend renaming this to something more descriptive like readGAF() and make it a regular function instead of a generic.

When a function is not exported it's generally internal business. Most internal functions don't need to be generics with methods because you'll have your own internal checking. Maybe I've misunderstood what you're trying to accomplish.

I'm going to stop here. Please reorganize the man pages and make those that are exported more complete. Once that's done I'll finish the review.

Thanks.
Valerie

**Comment by DanWiebe** [comment]
Hi @vobencha !
1) Ok
2) I haven't added setters/getters for every slot in order to encapsulate them. If it is needed for submission I will add them.
3) Such a big amount of man pages is generated automatically by roxygen. If it is needed I can rewrite everything in a more compact way manually, but it may cause problems in future e.g. when rewriting functions/methods.
4) Ok, I'll correct it as soon as possible
5) I've implemented it in such way in order to leave extension point so that I can add parsers for other annotation files format and operate with them via superclass which I have not implemented yet, which probably caused this misunderstanding. 

Best regards, Daniil Wiebe

**Comment by vobencha** [comment]
2. You only need getters/setters for slots on classes the user will access. If you don't expect a user (or downstream developer, i.e., package that depends on your package) will access that slot then no need for a formal, exported accessor. 
3. You can group man pages generated by roxygen. See use of @describeIn or @rdname here:
http://r-pkgs.had.co.nz/man.html#dry2

Valerie

**Comment by DanWiebe** [comment]
Hi @vobencha 
I combined all documentation in 10 man pages and added meaningful sections to them. Thanks for Your valuable advice!
Daniil

**Comment by vobencha** [comment]
Thanks for making the changes.

As for #5, 
- The name `read` is too common to be an exported function. If you ever plan to export this the name should be changed to avoid NAMESPACE clashes. Base R (and other packages) define a 'read' function. For example, the Base R read()  is S3:
```
> read.
read.csv      read.dcf      read.delim2   read.fortran  read.fwf      read.table    
read.csv2     read.delim    read.DIF      read.ftable   read.socket  
```

I feel this package re-implements much of the infrastructure in the msga package:
https://www.bioconductor.org/packages/release/bioc/html/mgsa.html

Have you looked at this package? Why can't you re-use `readGAF()` and one of the classes `MsgaGOSets`, `MsgaResults` etc. If these classes don't exactly meet your needs you can extend them and add your own slots.

A primary goal of package review is to harmonize the infrastructure by encouraging re-use and compatibility. If every package that implements a GO analysis uses it's own (unrelated) classes and methods it's difficult for users to move between methods. They have to re-import their data, put it in a different class etc.

Please consider reusing data import functions and classes from mgsa.
Thanks.
Valerie

**Comment by DanWiebe** [comment]
Hi @vobencha 
I added support for objects of MgsaSets, MgsaGOSets classes, as suggested.
However, we noted that `readGAF` from `mgsa` produces errors while parsing some .gaf files, for instance, gene_association.tair file from FoldGO extdata. To make FoldGO package universal for all organisms, we left `GAFReader` class as an option. If it is confusing I can delete our own .gaf parser implementation, but then FoldGO would not work with custom annotation for a number of organisms. 
About read method, it is as an internal method for annotation parsers, which can't be used externally. 
Sincerely yours, Daniil

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DanWiebe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"FoldGO\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FoldGO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
