### ISSUE TITLE
multiHiCcompare

### ISSUE THREAD

**Issue by jstansfield0** [Bioconductor/Contributions#801]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jstansfield0/multiHiCcompare

Confirm the following by editing each check box to '[x]'

- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi John,
Thank you for your submission.
As you are aware, Bioconductor already has a package callled `HiCcompre`.

We do not recommend extensions of existing packages with version numbers in the title.

We would rather have you update the original `HiCcompare` package and provide additional functionality. 
This way you will maintain one package rather than two. 
If the functionality provided in HiCcompare is vastly different, please rename the package into
something more appropriate. 

Best regards,
Marcel

cc: @mtmorgan

**Comment by jstansfield0** [comment]
Hi Marcel,

We feel that the package is different enough from `HiCcompare` and would like to rename it, however finding a different name that conveys the function of the package is difficult. Can we rename it as `multiHiCcompare` ? This will indicate the expanded nature of the analyses on multiple datasets offered by our new package while still explaining its functionality.

Thanks,
John

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0

Yes, you can rename the package. This might be a better solution than adding functionality to 
`HiCcompare`. Please make sure that the functionality in `HiCcompare` does not overlap that in
`multiHiCcompare`.

It should be okay to rename the package and issue. Right Lori @lshep?

Best regards,
Marcel

**Comment by lshep** [comment]
Yes you can rename the repository.  Please update your Github repository and associated files in the package (DESCRIPTION, etc)  and update the Repository link in the first entry of this issue.  When that is complete please let me know by using a tag @lshep - We will have to make some changes to the database that keeps track of issues on our end for the automatic build/webhook to work properly.

**Comment by jstansfield0** [comment]
@lshep I have changed the repository name and the name in the code.

**Comment by lshep** [comment]
@jstansfield0 I think everything has been updated and should now be recognized by the system.  Please ensure your webhook is still initialized and then please perform a version bump to get a new build of the package.  Let me know if you are having any troubles.

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 

Thanks for your submission. 
Please see the review below. 

Feel free to post any comments, questions here in the issue.

Best regards,
Marcel

---

# multiHiCcompare #801

* Overall, the package code and vignettes need more formatting so that lines
don't go over 80 column width. This makes the package easier to maintain.
* It would be good to find an existing Bioconductor class to build `hicexp` from.

## DESCRIPTION

* Looks okay although it could use formatting.

## NAMESPACE

* The Bioconductor usual practice is to use `camelCase` for function names.
* Avoid using periods in function names unless creating an S3 method.

## R

* Create a set of accessor functions for your `hicexp` data class so to avoid
using `@` in the code.
* It is convention to denote class names with capital letters (i.e., `Hicexp`)
    * Avoid creating sequences with `1:n` expressions, use the more robust
`seq_len` or `seq_along`
* Avoid nesting `for` loops whenever possible
* Combine input checks into a couple of checks (`.loess.as`) with a consistent
message (e.g., `!ncol(x) %in% c(1, 2) || !is.numeric(x) || any(is.na(x))`, etc.)
* Separate `plot` functionality from computations (avoid `plot` arguments).
* Use helper functions to avoid repetitive code (argument checking in
`fastlo`, etc.)
* Typically, it is better to avoid `%>%` piping in package code. It's largely
convenient for end-user code.
* It would be better to create a general function that would change based on
the `parallel` argument rather than coding for both conditions
(e.g., `FUN <- if (parallel) BiocParallel::bplapply else lapply` in `glm.R`)
* Avoid referencing columns by index position and use names for robustness.
* Please avoid functions like `reset_par`. You can save user defaults first,
then restore them after modifying them.

Minor:
* It would be better to write conditionals such as `if (iterations != 3L)`
rather than `iterations < 2` and `iterations > 4`.

## data

* Use a more descriptive and informative names for the data objects

## vignettes

* Use `BiocManager` instead of `biocLite` in the vignette.
* Remove commented sections from the vignette or include them as runnable code.
* Include `sessionInfo` at the end
* Be mindful of the formatting. Clean formatting makes a package easier to
maintain.

## tests

* You don't need to call `library` inside tests.
* Looks good. More is always better.

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 
Thanks for making those changes. I've had another look at your package. 
There are still a few points to consider:

* Use `||` when a fail is desired if either condition was not met (e.g., `if (max.pool < 0 | max.pool > 1)`).
* Combine input check conditions (see `R/cyclic_loess.R:160`)
* Avoid using index positions to subset (e.g., `x[, c(1,2,5,7)]`)

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 
Thanks for making those changes. 
Your package has been accepted. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 
Thanks for bumping the version. 

Could you consider this `NOTE` from `BiocCheck`?
 
```
* NOTE: Consider clarifying how 35 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    function (object)
      .cloess (loess.control)
      .et_reformat (p.adjust)
      .fastlo (loess.control)
      .glm_reformat (p.adjust)
   [truncated ... ]
```

-M

**Comment by jstansfield0** [comment]
Marcel, @LiNk-NY 

I am not really sure how to address that note. Do you have a suggestion?

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 
You'd have to specify what package you are importing those functions / objects from.
See the output if `BiocCheck`:

```
Consider adding
  importFrom("graphics", "abline", "legend", "lines", "par", "persp",
             "points", "smoothScatter")
  importFrom("stats", "D", "aggregate", "loess", "loess.control",
             "model.matrix", "optimize", "p.adjust", "predict", "update")
  importFrom("utils", "combn", "read.table")
```
-M

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 

There are still some uninitialized objects in the package. Please see the report [here](http://bioconductor.org/spb_reports/multiHiCcompare_buildreport_20180821110350.html). 

Regards,
Marcel

**Comment by jstansfield0** [comment]
Marcel @LiNk-NY 

Those objects all look to be object that I create in the functions or are references to column names in the data.tables.

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 

Perhaps, some of these NOTES can be minimized by quoting the variable names.
You can continue to improve your package one it has been accepted into our repository.
Thank you for your contribution! 

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jstansfield0.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"multiHiCcompare\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/multiHiCcompare

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
