### ISSUE TITLE
REBET

### ISSUE THREAD

**Issue by wheelerb** [Bioconductor/Contributions#802]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wheelerb/REBET

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

Please read the building report and seek to fix all the warnings (about biocViews, coding styles...) and most of the NOTEs. (more about coding styles). 

Please comment back if you have any question or are ready for an official technical review here. Thanks!

Cheers,
Qian

**Comment by wheelerb** [comment]
Hi Qian,
Updated files that fix the warnings and notes have been pushed.
Sincerely,
Bill

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

Thanks for the quick update. A technical review will soon be given (within 2 weeks)!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

Sorry for the delay. The technical review and comments will be given this afternoon. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

Here is the technical review of your package. Please seek to address most of the issues. Comment back here when you are ready for a 2nd review or have any questions. 

## DESCRIPTION

- use `Authors@R` instead of `Author + Maintainer` to specify the role of authors in developing and maintaing the package. [Reference](https://github.com/Bioconductor/GDSArray/blob/master/DESCRIPTION) Currently it's a little confusing that the maintainer is not listed as author. 
- Add some more details for a more descriptive `Description` filed.

## NAMESPACE

- looks good. 

## data/

- use more descriptive names for the data sets.

## R/rebet.R

- Use more descriptive/meaningful argument names. Y/G/E/X/a/b... does not give any information.
- move the unexported / local functions out into a separate R script, e.g., "Utility.R". Add "." before each function name to indicate it's internal usage. [reference](https://bioconductor.org/developers/how-to/coding-style/)

## vignette/

1. After the Introduction, please add a section for "Installation" to show to users how to install the package as if it has been included in Bioconductor. Because new packages is going to be in Bioc devel (Bioc 3.8), they are required to use `BiocManager` instead of `BiocInstaller` for downing the package. You should include something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("REBET")

2. Load the package into R session.
{r Load, message=FALSE}
library(REBET)
```

You can also add a subsection for installing the developmental version
from github, e.g.,```devtools::install_github("kevinblighe/REBET") ```

2. add a table of contents for the vignette.

3. Organize your vignette in a more hierarchical structure.

for example, include :
- `Introduction/Abstract`
- `Installation`, as stated above.
- `Example`: Briefly introduce the file types that are needed and steps that are taken for the whole process. Use sub-headers for different steps. e.g., phenotype data, sub-region file, ..., calculation, result summary...
- `SessionInfo`.

Cheers!
Qian

**Comment by wheelerb** [comment]
Hi Qian,

Thanks for the review. I have made the changes that you suggested to version 0.99.4. However the new build is giving an ERROR:
* ERROR: System Files found that should not be git tracked:
        src/source.o
        src/REBET.so
However, these two files are not in my /src folder.

I also get the WARNING:
* WARNING: Import stats, utils in DESCRIPTION as well as NAMESPACE.
The DESCRIPTION and NAMESPACE files do import stats and utils.

Sincerely,

Bill

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

1. Please use `Imports` instead of `Import` in DESCRIPTION. 
2. I am not sure about the error message since you don't have the 2 files in your folder. But as a workaround, you can create a file in the top directory called `.gitignore`, and write these 2 files as 2 lines inside the file. 
```
src/source.o
src/REBET.so
```

Then bump the package version, and see how the new building report say. 

Best,
Qian

**Comment by wheelerb** [comment]
Hi Qian,

Thanks. The WARNING message is now gone, but the ERROR still occurs.

Sincerely,

Bill

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

The ERROR is fixed now. I'll look at your other updates and get back to you very soon. 

Cheers,
Qian

**Comment by wheelerb** [comment]
Hi Qian,

Thank you

Sincerely,

Bill

**Comment by Liubuntu** [comment]
HI @wheelerb , 

Thank you for your updates in the package. Here are some additional points mainly for a more organized vignette. Bump the version when you are ready for the updates. Thanks!

Best, 
Qian

## DESCRIPTION

- No need to change anything. Just a reminder that you can actually use vector for the "role". E.g., role=c("cre", "aut"). Usually the "cre" is equivalent to the "maintainer".

## vignette

- The section of `Installation` should be organized as 2 subsections, e.g.,
`1.1, Install from Bioconductor. ... 1.2 Install the development version`...

- The section of `Example` should have some sub-sections as I
  mentioned in the first review, to break the big chunk into several
  to be more organized and reable. Use subsections like `phenotype
  data`, ... `sub-region file`,... `result summary`... with descriptive explanations 
for each section.

**Comment by wheelerb** [comment]
Hi Qian,

I did not get an email, but I now see the comments on github. I will make the changes to the vignette.

Sincerely,

Bill

**Comment by wheelerb** [comment]
Hi Qian,

Sorry for the delay. The vignette has been updated for version 0.99.6.

Sincerely,

Bill

**Comment by Liubuntu** [comment]
Hi @wheelerb , 

Thank you for the updates. You package is accepted now. 

Cheers,
Qian

**Comment by wheelerb** [comment]
Hi Qian,

Thank you

Sincerely,

Bill

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wheelerb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"REBET\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/REBET

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
