### ISSUE TITLE
tximeta

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/Contributions#806]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mikelove/tximeta

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hi @mikelove  did you want me to do an initial review or are you still making updates?

**Comment by mikelove** [comment]
hi @lshep Good question! :-)

I was doing some rolling updates getting ready for BioC and then after feedback from other developers. 

Now is a good time to take a break from any updates for the initial review.

BTW there were two extra slides from BioC that I didn't get to, which might be useful for reviewing the package, and seeing how it's leveraging BiocFileCache. If you go to the last 2 slides here:

http://bit.ly/tximeta

Thanks for your time!

**Comment by lshep** [comment]
Looking good to me.  Some minor points and questions: 

**inst/**
[Optional]  I personally like to see an inst/script/ directory that includes information on what is in extdata/ ,why it is included, and code or sudo code of how it was generated. (I realize a lot of this is in the vignette now - I still like a quick view in inst too but this is optional as long as it is somewhere)

**VIGNETTE** (by sections)

What Happened? 
`See the linkedTxome vignette in this package for a demonstration.`  Should this be the a  section of the current vignette?  else there is no other vignette currently included in the package? 

Examining SummarizedExperiment output
```
Here we show the three matrices that were imported. (Note: this part would need updating for un-reduced inferential variance matrices.) (Second note: the downstream packages would need updating of their functions or workflows, e.g. DESeqDataSetFromTximport needs a little update to work with these
SummarizedExperiments instead of simple lists.) 
```
I guess I was confused by the clarification points -  was this a note to update in the future or this seemed unclear to me? 

Easy summarization to gene-level
If the user wanted to regenerate rather than use the stashed version is there an overwrite? 

Run a differential expression analysis
So is there a plan for a convenience function? 

Metadata galore
[Optional]  I particularly like the syntax of `str(metadata(se)[["quantInfo"]])` rather than `str(metadata(se)$quantInfo)` but this is obviously optional. 


**R code:**

addIds.R:
minor point:
`message(paste0("mapping to new IDs using '", orgpkg.name, "' data package"))` I don't think you need the paste0, message does a sep="" to arguments `message("mapping to new IDs using '", orgpkg.name, "' data package")`

bfcLocation.R
more of a note for me - if you think of it can you open an issue on BiocFileCache to possible expose this use of rapp with a default or tempdir - I think we talked at CSAMA about how BiocFileCache does this internally automatically already but a package specific cache will want to expose like you have done - I
probably should make some sort of template for this to provide

**Comment by mikelove** [comment]
Thanks for these notes @lshep! I'll work on these and open the BiocFileCache Issue.

**Comment by lshep** [comment]
Hey how is this looking?  Any updates?

**Comment by mikelove** [comment]
Sorry for the delay, everything seems straightforward, I just got caught up with the rnaseqDTU workflow revision, but plan to fix up tximeta next week.

**Comment by lshep** [comment]
sounds good thanks.

**Comment by mikelove** [comment]
@lshep, I've addressed all your points. Mostly removing pieces that were confusing.

For the *DESeq2* integration, I added some code to DESeq2 devel branch right now to deal with the hand off. There's one remaining line of code I will delete once the DESeq2 version propagates.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mikelove.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"tximeta\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tximeta

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
