### ISSUE TITLE
NormalyzerDE

### ISSUE THREAD

**Issue by Jakob37** [Bioconductor/Contributions#808]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ComputationalProteomics/NormalyzerDE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Jakob37** [comment]
Dear Bioconductor reviewers,

Some thoughts and questions about the four remaining notes:

* For testing - I have a global test in place which verifies that files with same MD5sums are received which failed here. Previously this has been due to subtle differences in either number roundings or updates in dependencies altering numbers in late digits. I will investigate this and come back, but if you have input on how to better do this kind of verification your input is very welcome.
* For functions reading directly from harddrive I have surrounded the documentation examples with \dontrun{} as I struggled to figure out how to best setup example data for them.
* Regarding line length and indentation in multiples of four. I think that in this case it would reduce readability to shorten the lengths by added linebreaks or shorter variable names. The same for the note about indentation of four - I have indented visually when breaking lines. Let me know if you disagree here.

Thank you for your time!

**Comment by Jakob37** [comment]
I have looked over the code and added unit tests to the core parts. That part seems to run fine now, and the Biooconductor-build succeeds on Windows and Mac. Installation seems to fail on Ubuntu 16 though, referring to a missing package 'nortest'. This is surprising to me as I develop on Ubuntu 16 myself (it works fine here) and as the 'nortest' package is not directly referred to from the NormalyzerDE code.

I didn't see this error before either when I did the first builds here last week, so I am a bit confused. Do you have any idea about whether this error is on my side, or in the build server?

**Comment by Jakob37** [comment]
Seems like the problem went away overnight. Celebrations!! Now the code should be ready for review.

**Comment by Jakob37** [comment]
I am currently performing updates to the documentation in response to reviewer comments. An updated version will be uploaded the coming days. There are no structural changes, only documentation and minor updates to syntax (breaking down very long lines to multiple lines). Sorry if this causes any inconvenience.

**Comment by Jakob37** [comment]
Now the updates are completed and no further urgent changes are planned, so the software is ready for review. I apologize if these additional changes caused any inconvenience. 

Please let me know if anything else is needed from me at this stage.

**Comment by mtmorgan** [comment]
Thanks for your submission. Can you please address the following, posting a comment indicating how you have responded to each concern when your revisions are complete? Note that comments on R code highlight a single example, but the problem usually occurs throughout the package.

Repository

- please make the master branch a 'clean' R package repository, without other files; it may be helpful to create a separate branch for non-package files (e.g., the 'tools/' directory).

DESCRIPTION / NAMESPACE

- good

vignette

- It is usually more appropriate to write code that accepts standard R objects rather than text files requiring specific formatting. This makes it easy for users to incorporate your package into their work flow. The data looks very much like a 'SummarizedExperiment'.

- to reference files in your vignette, place the files under NormalyzerDE/inst/extdata/data.tsv and refer to them as `system.file(package="NormalyzerDE", "extdata", "data.tsv")`, etc.

- consider using a formula to specify the design, e.g., `~ group`; note that using a SummarizedExperiment removes the need to coordinate 'sample' across files.

R (representative problems; please correct similar issues throughout)

- e.g., analyzeResults.R:21 -- avoid direct slot access nr@nds, nr@ner <- ... and use accessor functions (not necessarily exported) instead, `.nds <- function(x) x@nds`; this abstraction helps to isolate implementation details from usage.

- analyzeResults.R:67 -- maybe `length(unique(unlist(sampleReplicateGroups)))` ?

- analyzeResults.R:70 use `vapply()` instead of an explicit for loop, so that you don't have to worry about pre-allocating the ersult (`featureCondCVs`) ?

- analyzeResults.R:80 use `colMeans()` etc (perhaps from the matrixStats package) rather than less efficient `apply()`

- analyzeResults.R:183 `seq_along(indexList)` rather than `seq_len(length(names(indexList)))`.

- analyzeResults.R:188 vectorize (i.e., call R functions once, rather than once per element), e.g., `rowSums(!is.na(processedDataMatrix[, cols])) - 1`. Likewise `matrixStats::rowVars()` a few lines down.

- `stop(paste(...` is usually the same as `stop(...`; likewise with `warning()`, `message()`.

- normal for a single `.gitignore` file, in the top level of the package directory

- higherOrderNormMethods.R:55 use `min(., na.rm = TRUE)` rather than `min(stats::na.omit(.))` for efficiency

- inputVerification.R:167 Is the `tryCatch()` effort here actually helpful? It seems likely that the `warning=` handler could easily mislead the user about the nature of the problem.

- (e.g., NormalyzerDataset.R:200) Use `message()` rather than `print()` to display informational messages.

- inputVerification.R:288 this 'copy-and-append' pattern is inefficient; pre-allocate or use an `*apply()` function. See http://bioconductor.org/developers/how-to/efficient-code/

- inputVerification.R:305 `which(<logical>)` is seldom necessary; `dataMatrix[dataMatrix == 0] <- NA`.

- NormalyzerResults.R:122 updating individual components of a class can be expensive, as each update triggers a copy of the _entire_ object. Consider instead using `initialize()` to update all slots in one call.

tests, man

- look good!

**Comment by Jakob37** [comment]
Thank you for the review morgan, very appreciated - and useful! I will likely have time to work this through and come back with comments the coming weeks.

**Comment by Jakob37** [comment]
Thanks again for your comments, they have been very valuable - both for improving NormalyzerDE and my understanding of R. I have agree with your points, and have made edits accordingly in all except one point. If you have further requests, let me know and I will do my best to update accordingly.

```
please make the master branch a 'clean' R package repository, without other files; it may be helpful to create a separate branch for non-package files (e.g., the 'tools/' directory).
DESCRIPTION / NAMESPACE
```

I have separated out the tool directory (with the container recipe) to a separate branch called 'singularity'.

```
It is usually more appropriate to write code that accepts standard R objects rather than text files requiring specific formatting. This makes it easy for users to incorporate your package into their work flow. The data looks very much like a 'SummarizedExperiment'.
```

Didn't know about the SummarizedExperiment before, will definitely be useful to me in the future. I have updated the interfaces so that input can be provided either through a file path or as an instance of SummarizedExperiment.

```
to reference files in your vignette, place the files under NormalyzerDE/inst/extdata/data.tsv and refer to them as system.file(package="NormalyzerDE", "extdata", "data.tsv"), etc.
```

Fixed.

```
consider using a formula to specify the design, e.g., ~ group; note that using a SummarizedExperiment removes the need to coordinate 'sample' across files.
```

I agree that this point would be very useful, in particular for the statistics module. I don't want to abandon the current interface though as I think it is easy to understand for less experienced R users. I am considering adding the ability to pass the formula and related contrasts as an advanced option, but would like to leave that as a feature for the future as it would require significant restructuring of the statistical part of the software.

```
e.g., analyzeResults.R:21 -- avoid direct slot access nr@nds, nr@ner <- ... and use accessor functions (not necessarily exported) instead, .nds <- function(x) x@nds; this abstraction helps to isolate implementation details from usage.
```

Updated for all four S4 classes.

```
analyzeResults.R:67 -- maybe length(unique(unlist(sampleReplicateGroups))) ?
```

Updated.

```
analyzeResults.R:70 use vapply() instead of an explicit for loop, so that you don't have to worry about pre-allocating the ersult (featureCondCVs) ?
```

I have updated this in a number of places where preallocation was performed. I left the for-loops in some cases where I thought the apply statements didn't make things clearer.

```
analyzeResults.R:80 use colMeans() etc (perhaps from the matrixStats package) rather than less efficient apply()
```

Thanks a lot for this comment, awesome! I have used the matrix commands from matrixStats package and from base R and updated all row/column operations I could find.

```
analyzeResults.R:183 seq_along(indexList) rather than seq_len(length(names(indexList))).
```

Updated.

```
analyzeResults.R:188 vectorize (i.e., call R functions once, rather than once per element), e.g., rowSums(!is.na(processedDataMatrix[, cols])) - 1. Likewise matrixStats::rowVars() a few lines down.
```

Updated.

```
stop(paste(... is usually the same as stop(...; likewise with warning(), message().
```

Paste removed in all instances I could find.

```
normal for a single .gitignore file, in the top level of the package directory
```

I had missed the second .gitignore - removed.

```
higherOrderNormMethods.R:55 use min(., na.rm = TRUE) rather than min(stats::na.omit(.)) for efficiency
```

Updated.

```
inputVerification.R:167 Is the tryCatch() effort here actually helpful? It seems likely that the warning= handler could easily mislead the user about the nature of the problem.
```

I rewrote this statement so that it no longer accidentally could hide some warnings. Instead - if it receives a warning for the file input it displays it and stops processing.

```
(e.g., NormalyzerDataset.R:200) Use message() rather than print() to display informational messages.
```

Updated.

```
inputVerification.R:288 this 'copy-and-append' pattern is inefficient; pre-allocate or use an *apply() function. See http://bioconductor.org/developers/how-to/efficient-code/
```

Fully agree - updated.

```
inputVerification.R:305 which(<logical>) is seldom necessary; dataMatrix[dataMatrix == 0] <- NA.
```

Updated.

```
NormalyzerResults.R:122 updating individual components of a class can be expensive, as each update triggers a copy of the entire object. Consider instead using initialize() to update all slots in one call.
```

I have introduced constructors and removed the repeated value assignments. When doing this I also realized ways to significantly simplify the classes (in particular NormalyzerResults).

Thanks again for your comments. Please let me know how to proceed from here.

**Comment by mtmorgan** [comment]
Thanks the changes look good!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jakob37.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"NormalyzerDE\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NormalyzerDE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
