### ISSUE TITLE
primirTSS

### ISSUE THREAD

**Issue by ipumin** [Bioconductor/Contributions#817]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ipumin/primirTSS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ipumin** [comment]
Dear Bioconductor team member,

I have recently started the submission process of my R package “primirTSS”. In my most recent attempt, the results of check return good on Linux and OS X while the build report mentions WARNINGS on the Windows system check:

```
WARNING: check time exceeded 5 min. 
```

I’ve been trying many different method to utilize my package to get over with the WARNINGS from Window platform. But my attempt seems to be limited. So I was wondering if Windows check longer than the other two platforms and may I ask if there is anything else I can do to deal with this warning and go ahead with the package submission?

Look forward to your kind advice. 
Thanks a lot.

Best
Pumin Li

**Comment by ipumin** [comment]
Dear @Liubuntu ,

I have recently started the submission process of my R package “primirTSS”. In my most recent attempt, the results of check return good on Linux and OS X while the build report mentions WARNINGS on the Windows system check:

```
WARNING: check time exceeded 5 min. 
```

I’ve been trying many different method to utilize my package to get over with the WARNINGS from Window platform. But my attempt seems to be limited. So I was wondering if Windows check longer than the other two platforms and may I ask if there is anything else I can do to deal with this warning and go ahead with the package submission?

Look forward to your kind advice. 
Thanks a lot.

Best
Pumin Li

**Comment by Liubuntu** [comment]
Hi @ipumin , 

The timeout on Windows might be on our end. I will try to communicate with other core team members about this issue and let you updated. For the mean time, please work on the "NOTE" messages in the building report and try to fix as many as possible. A technical review will be given within 2 weeks. 

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Can you bump the version of you package in `DESCRIPTION`, without doing anything else? We'll see if the new build will be clean. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
@ipumin , 

After the version bump, could you work on the NOTE messages in the building report? For example, the following several. Also try to fix issues in NOTE that are under control, and let me know for any question.  

1. See if any of the suggested BiocViews terms would fit your package. 
> * Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews:
      GeneExpression, Transcription, ChipOnChip, SingleCell,
      GenePrediction, GeneRegulation, GeneSetEnrichment
See http://bioconductor.org/developers/how-to/biocViews/

2. We encourage (and kind of reinforce) a robust coding style. 
> * Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      eponine_score.R (line 79, column 17)

3. The initial file of `NEWS` could be blank, but any major updates (e.g., new functions implemented...) of your package after this submitted initial version should be included in the file. The file should be in the top directory, i.e., `primirTSS/NEWS`. 

> * Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.

Qian

**Comment by ipumin** [comment]
Hi @Liubuntu ,

Sorry for replying late. The following issue mentioned in NOTE have been fixed:

1. The suggested biocViews have been added.

2. The `eponine_score.R` has already been edited using `seq_len()` to match better coding style.

3. And I have added a `NEWS` file in the top directory for potention updates.

But in my recent attempt, the results of check return good on Linux while the build report mentions WARNINGS on the Windows and OS X system check:
```
WARNING: check time exceeded 5 min. 
```
I have not changed any code except that `1:3` is changed to `seq_len(3)` in `eponine_score.R`.
I’ve been trying many different method to utilize my package to get over with the WARNINGS. But my attempt seems to be limited. 

Look forward to your kind advice.
Thanks a lot. Thanks again for your time and kind suggestion.

Best
Pumin Li

**Comment by Liubuntu** [comment]
HI @ipumin , 

Thanks for your updating. Since there is only 1 warning for the timeout, I can start reviewing your package, and see what might be the factor affecting the building time. Usually it could be related to the  slow examples in functions and vignette, loading of public data resources, ... 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Here is part of the technical reviews. More will be coming...
## DESCRIPTION

- Description field: make it relatively short, but at the same time, as descriptive and informative as possible. Seems that your vignette introduction has some good summary of the unique feature/advantage of your tool, maybe you want to extract something useful to add into the Description field?
```
By integrating H3k4me4 and Pol II data, parting of false positive counts
after scoring can be filter out. Besides, DNase I hypersensitive sites(DHS) also
imply TSSs, where miRNAs will be accessible and functionally related to
transcription activities. And additionally, the expression profile of miRNA and
genes in certain cell-line will be considered as well for improve fidelity. By
```

- License: use a specific version. e.g., `GPL-2`.

...

**Comment by ipumin** [comment]
Hi @Liubuntu ,

Thanks so much for your very nice and considerate suggestions. We’ll figure it out and append additional necessary information into the description as soon as possible. 
Thanks again.

Best
Pumin Li

**Comment by Liubuntu** [comment]
## NAMESPACE
- Since you package depends on `dplyr` heavily for plotting, you might want to import the whole package instead of import specific functions. So that the NAMESPACE would also be cleaner.
- Similar to `BiocGenerics` and `GenomicRanges`. As these packages are very basic within Bioconductor ecosystem, we would recommend import the whole packages.



## R/

- `trans_cor.R`: Be cautious in querying web sources. see [here](https://bioconductor.org/developers/how-to/web-query/) for guidelines. The `timeout` warning might comes from here. Test the downloading time for the example. The whole check process requires less than 5 mins. If the examples runs slow, make it a `dontrun` example.

- Coding style:
1. Prefix non-exported functions with a ‘.’ to indicate internal usage. see [here](https://bioconductor.org/developers/how-to/coding-style/) for "Function names" section. For some general internal functions that could be used in multiple scripts, The best practice is to put them into one script, e.g., `AllUtilities.R`. However, these are not reinforced.
2. Use camel case in naming the **exported** functions (initial lower case, then alternate case between words). e.g., `peakJoin`, `peakMerge`, `findNearestPeak`... Use consistent names for the exported function and the script defining it and the documentation. E.g., in defining function `peakJoin()`, name the script as `peakJoin.R` and the documentation file as `peakJoin.Rd`. These are not reinforced.



## man/
- add documentation for the package itself. see [here](http://r-pkgs.had.co.nz/man.html#man-packages). Name the script as `R/primirTSS-package.R` and it will generate documentation file as `man/primirTSS-package.Rd`.

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Here is the technical review for the vignette. I had some problem downloading one of the imported package now, once that is successful, additional comments might be added. 

## vignette/

- for the installation, use the following code: (add backquotes around the code chunks)
```
{r, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package using the same command, but with github account name.

{r, eval=FALSE}
BiocManager::install("githubUserName/pkgName")  ## same as the input for devtools::install_github().


2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```
- put the last section about session info into runnable code using `{r} sessionInfo()` as you do for the other code chunks. It will return the working environment based on you package dependencies / imports.

- typos:
  L65: "one of these **two**"
  L65: use "before **executing**".
  Please also heck other lines and correct accordingly.


## OTHERS: 

- multiple typos in the vignette, and also the documentation files. Try to run a spell checker. e.g., ``spelling::spell_check_package("primirTSS")```.

**Comment by ipumin** [comment]
Hi @Liubuntu ,

I have just pushed a new version of my package. Thank you so much for all the helpful comments:

**DESCRIPTION**

* The primary and descriptive informaiton has already been added to the package according to your advice.

**NAMESPACE**

* There’re several functions, such as `intersect()` and `union()`, conflict with each other in `BiocGenerics`, `GenomicRanges`, `dply`, therefore we didn't import all the functions in the packages.


**R/**

* `trans_cor.R` has been modified.
* Coding style: I felt extremely grateful for your patient and careful review for my package. For this time, considering the limitted time for the following further submission, I haven't modified this part of the coding style, and I was wondering if we could skip it for this time and continue reviewing. I will pay more attention will be paid to the following projects, according to your nice suggestion.


**man/** 

* The documentation for the package itself has been added. Please refer `man/primirTSS.Rd`


**vignette/**  

* All the suggestions incorperated.


**OTHERS**

* Additionally, typos have been checked again carefully and corrected. 

Looking forward to your helpful feedback again. Thank you very much.

Best
Pumin Li

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Thank you for your updates. Here are some additional comments (mostly just cosmetic). Please address all of them ASAP (I'll travel from next week) so that it could be processed properly.   

## DESCRIPTION
- Please add `URL` field for the github repository. See [here](http://bioconductor.org/developers/package-guidelines/#description).
- Please add a `BugReports` field for the relevant links to Github for reporting Issues. (same link above)

## NAMESPACE
- Please use the following to import packages with exceptions. e.g., `@rawNamespace import(Utils, except=c(“head”, “tail”))`

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Can you put the example inside "trans_cor.R" as `dontrun`? bump the version and see if the `WARNING` from building report go away. Thanks!

Best,
Qian

**Comment by ipumin** [comment]
Hi @Liubuntu,

Thanks for your advice. I have modified my package according to your suggestions. But I am sorry that it still shows timeout after putting the example inside "trans_cor.R" as `dontrun`.

Looking forward to your helpful feedback again. Thank you very much.

Best
Pumin Li

**Comment by Liubuntu** [comment]
Hi @ipumin , 

For the example `trans_cor(peak, "hg19", "hg38")`, how big the data is? I couldn't actually open the link... 

If the specific downloading file is to be used in most user cases (not changing much in different situations), you should put the data as an `experimentHub` object and submit it as a experiment package. see [here](https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html).

**Comment by ipumin** [comment]
Hi @Liubuntu,

The size of "hg19ToHg38.over.chain.gz" is 223KB. And there are other files, such as "hg38ToHg19.over.chain.gz", "hg19ToHg17.over.chain.gz", "hg19ToHg18.over.chain.gz", "hg18ToHg19.over.chain.gz", "hg18ToHg38.over.chain.gz" and "hg18ToHg17.over.chain.gz". ALL of them are downloaded from UCSC. The link of "hg19ToHg38.over.chain.gz" is http://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz.

For convenience, I put the "hg19ToHg38.over.chain.gz" locally, and users can convert coordinates from "hg19" to "hg38" without connecting network. But I do not put all "hg*ToHg*.over.chain.gz" files due to package size limitations. Users can download additional files to convert coordinates between different genomes.

Besides, I have removed the `dontrun` tag from the example.

**Comment by ipumin** [comment]
Hi @Liubuntu,

In my opinion, the `eponine_score` function uses the `eponine-scan.jar` which is a java program and performs a lot of calculations. I think it is the main reason for the timeout warning.

**Comment by Liubuntu** [comment]
Seems that the `find_tss` function calls `find_candidate_tss`, and then calls `phast_score`, which is the actual time-consuming part? 

Does the whole process has any web source downloading automatically? If the web source are experiment / annotation package, you should put them all into `Imports` field. Otherwise, follow the instructions and example [here](https://bioconductor.org/developers/how-to/web-query/) for resource queries. 

One more thing, the function of `tss_filter2` does not seem to be used anywhere and not exported. If that is that case, it should not be included inside the package.

**Comment by ipumin** [comment]
Hi @Liubuntu,

I have found that `plot_primiRNA()` is the actual time-consuming part because it uses the `Gviz` package, which needs to connect to the network when imported. I have modified this function and now there is no warnings. Also, I have deleted `tss_filter2`. 

Thank you for your helpful suggestions. Looking forward to your feedback again. Thank you very much.

Best
Pumin Li

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Please remove the `dontrun` tag for "find_tss.R" example. 

You mentioned you have modified the function "Gviz" part, how does it work now? what's the difference by introducing the modification? 

Qian

**Comment by ipumin** [comment]
Hi @Liubuntu,

I used `Gviz::function` in `plot_primiRNA()` instead of using `importFrom(Gviz, function)` in NAMESPACE. So `Gviz` will not be imported until `plot_primiRNA()` is executed.

Best
Pumin Li

**Comment by ipumin** [comment]
Hi @Liubuntu,

I tried to remove the dontrun tag for `find_tss()` example but it showed "WARNING: R CMD check exceeded 5 min requirement" again. And I met a strange thing, the code showing [OK](https://bioconductor.org/spb_reports/primirTSS_buildreport_20180906093153.html) last night showed [WARNINGS](https://bioconductor.org/spb_reports/primirTSS_buildreport_20180906215948.html) this morning. One CheckTime is 4 minutes 45.83 seconds and the other is 6 minutes 30.58 seconds. I don't know what caused the difference between the two on windows platform. I was wondering if this WARNINGS is caused by random test error of windows platform when the `primirTSS` package needs some time to run?

Best
Pumin Li

**Comment by ipumin** [comment]
Hi @Liubuntu,

As [*R Packages*](http://r-pkgs.had.co.nz/namespace.html#imports) states
> R functions
If you are using just a few functions from another package, my recommendation is to note the package name in the Imports: field of the DESCRIPTION file and call the function(s) explicitly using ::, e.g., pkg::fun(). Operators can also be imported in a similar manner, e.g., @importFrom magrittr %>%.

I have noted `Gviz` in the `Imports:` field of the `DESCRIPTION` file and used `Gviz::function` because I think I am using just a few functions from `Gviz`. But I am sorry that I don't know why using `Gviz::function` will display OK([2018/9/8 GMT+8 5:08 am](http://bioconductor.org/spb_reports/primirTSS_buildreport_20180907170831.html), [2018/9/6 GMT+8 9:31 pm](http://bioconductor.org/spb_reports/primirTSS_buildreport_20180906093153.html), [2018/9/6 GMT+8 8:34 pm](http://bioconductor.org/spb_reports/primirTSS_buildreport_20180906083426.html)), when adding `importFrom(Gviz,function)` to the namespace will display WARNINGS([2018/9/8 GMT+8 5:00 am](http://bioconductor.org/spb_reports/primirTSS_buildreport_20180907170008.html)).

Best
Pumin Li

**Comment by Liubuntu** [comment]
Hi @ipumin , 

Thanks for adding the link for package `Import`. So as Hadley stated: 
> It’s common for packages to be listed in Imports in DESCRIPTION, but not in NAMESPACE. In fact, this is what I recommend: list the package in DESCRIPTION so that it’s installed, then always refer to it explicitly with pkg::fun(). 

So since you are using `Gviz` in only a few functions, that's more efficient not including it in NAMESPACE. But important to have it in DESCRIPTION. 

I am also confused about the `importFrom` of Gviz now, but as you are already using it correctly, we can skip this part and just have the package accepted now. I'll keep an eye on these kind of problems later until we find why. 

Thanks again for your contribution to Bioconductor. 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ipumin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"primirTSS\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/primirTSS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
