### ISSUE TITLE
miRSM

### ISSUE THREAD

**Issue by zhangjunpeng411** [Bioconductor/Contributions#825]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhangjunpeng411/miRSM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
please update the user-facing interface (argument and return values) to use a [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment) and other [standard objects](http://bioconductor.org/developers/how-to/commonMethodsAndClasses/) instead of ad-hoc data representations.

**Comment by zhangjunpeng411** [comment]
@mtmorgan 
Thanks for you advice.

Junpeng

**Comment by zhangjunpeng411** [comment]
Hi @lshep  ,

How can I resolve the ABNORMAL status of the repository? I don't see anything particularly wrong in the build report, only the operating system is not showed in the OS/Arch field. In addition, only one operating system is runned.

Thanks and Regards,
Junpeng

**Comment by lshep** [comment]
This was likely an issue on our end.  I am rerunning the package now to generate the complete build report.

**Comment by lshep** [comment]
Please let me know when you are finished updating user-facing interface (argument and return values)  as @mtmorgan suggested.   When you are finished with this update I will give a more formal review of the package.

**Comment by zhangjunpeng411** [comment]
Hi @Ishep,

I have updated all functions by using a SummarizedExperiment object for arguments. Now, you can review it. Thanks for your hard work.

Regards,
Junpeng

**Comment by lshep** [comment]
Sorry for the delayed response.  Please see the following comments:

**General:**
- [ ] Can you give a Comparison to existing ceRNAs, miRNA sponges or miRNA decoys packages. Like
miRsponge

**README**
- [ ] Update installation instructions to use BiocManager

**Description:**
- [ ] remove lazydata: true rarely proves a good thing in our experience. 

**NEWS:**
- [ ] not formatted quite right - please add delimiter for text under section - extend the below example to entire text

```
CHANGES IN VERSION 0.99.8-0.99.14
-------------------------
Update miRSM.Rmd

CHANGES IN VERSION 0.99.4-0.99.7
-------------------------
Update runnable examples
```
would become 
```
CHANGES IN VERSION 0.99.8-0.99.14
-------------------------
o Update miRSM.Rmd

CHANGES IN VERSION 0.99.4-0.99.7
-------------------------
o Update runnable examples

```


**Vignette:**
- [ ] you only need to load the data once instead of repeatedly 
```
data(ceRExp)
data(mRExp)
```

- [ ] So running your examples module_GFA is an empty list - is this intended? 

- [ ] All output are lists of character vectors? It seems as list of Genes - please look into formatting output to a GSEAbase::GeneSet or GeneSetCollection object 

- [ ] Are the lengths of the lists going to be consistent? What do the different elements of the list mean?  Some better explanation of the output would be helpful as well as maybe labelling the list elements. 

- [ ] It seems like there is extra whitespace in the coding sections of Identification of miRNA sponge modules and Functional analysis of miRNA sponge modules causing it to display weirdly

- [ ] Your last code section is eval=FALSE why? 

- [ ] So these modules are meant to be run separatly depending on which is
  appropriate or desired? 

**inst/script:**
- [ ] Please include a script in the above directory location that has the code used to generate your data objects and commented information like  How were the samples selected? was there any filtering or formatting? etc... 

**Man files:**
- [ ] Data man files - either here or in the inst/script above please provide more details on how the samples were selected from teh cancergenome site. 

**R Code:**
Internal ProNet functions -  
- [ ] So I see that ProNet is temporarily removed from CRAN which is why I assume you are inlcuding these functions here?  Have you reached out to the ProNet package maintainer to see if they plan on maintaining the package and having it back on CRAN?  

- [ ] It seems like this section of code outputs the resutls of each function. Maybe create a helper function for it instead so that if there are every updates it only needs to be updated in one instance 
```
    ceR_Num <- lapply(seq_along(Modulegenes), function(i) length(which(Modulegenes[[i]] %in%
        colnames(ceRExp))))
    mR_Num <- lapply(seq_along(Modulegenes), function(i) length(which(Modulegenes[[i]] %in%
        colnames(mRExp))))

    index <- which(ceR_Num >= num.ModuleceRs & mR_Num >= num.ModulemRs)
    CandidateModulegenes <- lapply(index, function(i) Modulegenes[[i]])

    return(CandidateModulegenes)
```

Please address the above issues and push changes.  When you are ready please comment back here and I will re-review. 
Thank you for you submission - I look forward to working with you to get your package accepted 

Cheers,

**Comment by zhangjunpeng411** [comment]
Hi @lshep ,

Thanks for your comments.

Regards,
Junpeng

**Comment by zhangjunpeng411** [comment]
Hi @lshep  

Thanks for your comments. Please find the below response.

**General:**
•	  Can you give a Comparison to existing ceRNAs, miRNA sponges or miRNA decoys packages. Like miRsponge, SPONGE
**Re: The existing packages (miRsponge and SPONGE) focus on identifying miRNA sponge interactions or networks using computational methods. For miRNA sponge modules, miRsponge identifies them based on miRNA sponge interaction networks. However, miRSM directly identifies miRNA sponge modules by integrating expression data and miRNA-target binding information instead of miRNA sponge interaction networks. We have explained it in the miRSM.Rmd file in this revision.**

**README:**
•	  Update installation instructions to use BiocManager
**Re: The installation instructions have been changed by using BiocManager.**

**Description:**
•	  remove lazydata: true rarely proves a good thing in our experience.
**Re: The lazydata: true has been removed.**

**NEWS:**
•	  not formatted quite right - please add delimiter for text under section - extend the below example to entire text

    CHANGES IN VERSION 0.99.8-0.99.14
    -------------------------
    Update miRSM.Rmd

    CHANGES IN VERSION 0.99.4-0.99.7
    -------------------------
    Update runnable examples

would become

    CHANGES IN VERSION 0.99.8-0.99.14
    -------------------------
    o Update miRSM.Rmd

    CHANGES IN VERSION 0.99.4-0.99.7
    -------------------------
    o Update runnable examples

**Re: Corrected.**

**Vignette:**
•	  you only need to load the data once instead of repeatedly
data(ceRExp)
data(mRExp)
**Re: I have combined four data files (ceRExp, mRExp, miRExp, miRTarget) into one data file called “BRCASampleData.rda”. The data file is loaded once when needed.** 

•	  So running your examples module_GFA is an empty list - is this intended?
**Re: Yes. module_GFA may not identify any modules when running examples.**

•	  All output are lists of character vectors? It seems as list of Genes - please look into formatting output to a GSEAbase::GeneSet or GeneSetCollection object
**Re: The output of character vectors (genes) in 6 functions (module_GFA, module_NMF, module_ProNet, module_WGCNA, module_biclust and module_igraph) have been changed into GeneSetCollection objects.**

•	  Are the lengths of the lists going to be consistent? What do the different elements of the list mean? Some better explanation of the output would be helpful as well as maybe labeling the list elements.
**Re: Thanks for your advice. We have labeled each list element in this revision.**

•	  It seems like there is extra whitespace in the coding sections of Identification of miRNA sponge modules and Functional analysis of miRNA sponge modules causing it to display weirdly
**Re: Corrected.**

•	  Your last code section is eval=FALSE why?
**Re: It takes much time for functional analysis of miRNA sponge modules. If eval = TRUE, it will cause “timeout” during checking.**

•	  So these modules are meant to be run separately depending on which is appropriate or desired?
**Re: These modules can all be run. Some modules take much time during checking, so I don’t run them.**

**inst/script:**
•	  Please include a script in the above directory location that has the code used to generate your data objects and commented information like How were the samples selected? was there any filtering or formatting? etc...
**Re: I have explained it in the Man data files.**

**Man files:**
•	  Data man files - either here or in the inst/script above please provide more details on how the samples were selected from the cancer genome site.
**Re: Provided.** 

**R Code:**
Internal ProNet functions -
•	  So I see that ProNet is temporarily removed from CRAN which is why I assume you are including these functions here? Have you reached out to the ProNet package maintainer to see if they plan on maintaining the package and having it back on CRAN?
**Re: ProNet has been removed from the CRAN repository for more than a month. So I include some internal functions of the package under GPL-2.0 license. I have sent an email to the maintainer of ProNet package (Xia-Yu Xia, xiaxiayu.thu@hotmail.com), but no reply. If they plan on maintaining the package and having it back on CRAN in the future, I will remove these internal functions and import the package.**

•	  It seems like this section of code outputs the results of each function. Maybe create a helper function for it instead so that if there are every updates it only needs to be updated in one instance

    ceR_Num <- lapply(seq_along(Modulegenes), function(i) length(which(Modulegenes[[i]] %in%
        colnames(ceRExp))))
    mR_Num <- lapply(seq_along(Modulegenes), function(i) length(which(Modulegenes[[i]] %in%
        colnames(mRExp))))
    index <- which(ceR_Num >= num.ModuleceRs & mR_Num >= num.ModulemRs)
    CandidateModulegenes <- lapply(index, function(i) Modulegenes[[i]])
    return(CandidateModulegenes)

**Re: The above scripts have been changed into an internal function called CandModgenes.** 

Regards,
Junpeng

**Comment by lshep** [comment]
You still don't need all the data(BRCASampleData)  in the vignettes -  onces its loaded its loaded so a single call at the top of the script would suffice but a minor point not hindering acceptance.  Cheers and Thank you for implemented all the suggested changes so quickly.

**Comment by zhangjunpeng411** [comment]
Hi @lshep,

Thanks for your help and advice. By generating a new section "Load BRCA sample data", I have further revised the data loaded in the vignettes. It's nice to be able to cooperate with you.

Regards,
Junpeng

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhangjunpeng411.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"miRSM\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/miRSM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
