### ISSUE TITLE
celaref

### ISSUE THREAD

**Issue by swbioinf** [Bioconductor/Contributions#827]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MonashBioinformaticsPlatform/celarefData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by swbioinf** [comment]
AdditionalPackage: https://github.com/MonashBioinformaticsPlatform/celarefData

**Comment by swbioinf** [comment]
AdditionalPackage: https://github.com/MonashBioinformaticsPlatform/celaref

**Comment by swbioinf** [comment]
Addressing BiocCheck notes: 

[1] "Consider adding these automatically suggested biocViews: GeneExpression, Microarray, DifferentialExpression, WorkflowStep, Clustering, RNASeq"             
 * Considered. Sticking with SingleCell.

[2] "Consider adding unit tests. We strongly encourage them. See\n  http://bioconductor.org/developers/how-to/unitTesting-guidelines/."                         
 * Right now everything is covered in the code examples. Considering for the next version.
                        
[3] " Avoid 1:...; use seq_len() or seq_along() found in files:"                                                                                              

 * There's a section where am working across a small ordered table. I'm fairly confident that I'm not introducing negatives, but will consider next time I'm working on that section. 

[4] "Consider shorter lines; 679 lines (14%) are > 80 characters long."                                                                                         

 * I use fairly verbose function names, parameter names. I've wrapped some but keep lines long in places for readability.
                       
[5] "Consider multiples of 4 spaces for line indents, 1050 lines(22%) are not." 

 * Using 3 spaces for indentation, consistantly throughout.
                                                                                                       
[6] "Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin\ncredentials).  Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel"

 * Done.

**Comment by mtmorgan** [comment]
For your responses, for 2 and especially 3 I'd ask "why wait?"

For 4 scanning just one file it seems appropriate to wrap `@param` lines (in RStudio, turn on Tools -> Global Options -> Code -> Display -> Show Margin and hit the carriage return as appropriate). For the merit of this approach, try reading the code in github, e.g., https://github.com/MonashBioinformaticsPlatform/celaref/blob/master/R/loading_helper_functions.r#L432 (also other text processors like emacs and vim commonly used by developers). For lines such as https://github.com/MonashBioinformaticsPlatform/celaref/blob/master/R/loading_helper_functions.r#L444 and in general I would suggest a rule of 'current indent + 4' (your use of 3 is idiosyncratic, but that's ok with me, so use 'current indent + 3') so that

```
trim_small_groups_and_low_expression_genes <- function(
    dataset_se, min_lib_size=1000, min_group_membership=5,
    min_reads_in_sample=1, min_detected_by_min_samples=5
) {
   ...
}
```
with the rationale again being general readability, not just on github but in general enabling the eye to track from one line to the next.

For lines like https://github.com/MonashBioinformaticsPlatform/celaref/blob/master/R/loading_helper_functions.r#L451 I think it's better (easier to follow the logic) to separate out the nested code into logically simple units

```
ridx <- Matrix::rowSums(assay(dataset_se) >= min_reads_in_sample) >=  min_detected_by_min_samples
dataset_se <- dataset_se[ridx, ]
```
The formatting in https://github.com/MonashBioinformaticsPlatform/celaref/blob/master/R/loading_helper_functions.r#L121 with `{ ... }` on one line doesn't capture the conditional nature of the expression, and I'd always write
```
if () {
    ...
}
```

**Comment by mtmorgan** [comment]
I'd like to move this package through the review process. This requires that the packages do not have errors / version bump required etc. On what timeline do you think it will be possible to get to this stage?

**Comment by mtmorgan** [comment]
These packages look to be in really good shape. Some minor comments... please address and post a short comment summarizing changes. 

With respect to `Matrix::rowSums()`, etc., yes it is not incorrect to do this; personally I would prefer to `@importFrom Matrix rowSums` and use simply `rowSums(.)` where as developer I can control importFrom statements and thus guarantee that the `rowSums()` seen by my package code is from the Matrix package. This is a preference so feel free to continue to fully specify the source of the function.

## celarefData

- nice!

## celaref

DESCRIPTION / NAMESPACE

- good

vignette

- `BiocManager::install("MonashBioinformaticsPlatform/celaref")` also installs the github version.

- package 'landing pages' have url like, e.g,. https://bioconductor.org/packages/limma, which is a more compact and robust way of referencing http://bioconductor.org/packages/release/bioc/html/limma.html

- good!

R (exemplar issues; please correct throughout)

- contrasting_functions.R:85 use `message()` rather than `print()` for informational messages (output goes to 'stderr' rather than 'stdout', which is appropriate for diagnositic messages). Usually `message(paste0(...` can be replaced by `message(...`; similarly for `warning()`, `stop()`.

man

- good

**Comment by swbioinf** [comment]
No worries, changes done. Thanks.
 * print statements replaced with message, and paste() removed from message/stop/warning
 * Vignette updated with bioconductor dev install and landing page url

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/swbioinf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"celarefData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/celarefData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/swbioinf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"celaref\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/celaref

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
