### ISSUE TITLE
MPRAnalyze

### ISSUE THREAD

**Issue by talashuach** [Bioconductor/Contributions#829]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YosefLab/MPRAnalyze

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by talashuach** [comment]
Hi Valerie,
Thanks for the comments!

Some questions:
1 - I'm trying to move the data to the main "/data" path but I'm having trouble creating the man file. I'm working off the instructions [here](http://r-pkgs.had.co.nz/data.html#documenting-data), but I'm getting an error when trying to document the package (using devtools::document), similar to what is described [here](https://stackoverflow.com/questions/46837428/r-data-is-not-an-exported-object-from-namespacemy-package). They suggest removing the .R file put the documentation in, which I'm not sure how I can get the .man file without.
Can you point me in the right direction of this?

2 - Will BiocManager::install() work for my package at this point? It is already being downloaded and used (not through bioconductor, directly through github), so I'd rather not have this instruction before it works.

Other changes were incorporated, I'll push everything soon. Thanks again!
Tal

**Comment by vobencha** [comment]
Hi,
1) I'm not sure I understand the problem. You need to move the data/ directory out of vignettes/ (up one level). Next, create a R/ChrEpi.R file that documents the object similar to Hadley's example. The man page is created automatically when you build the package. 

Is this what you've done? At what point are you seeing the error?

2) BiocManager::install will work once your package is accepted and added to the Bioconductor repo. You can also demonstrate loading from GitHub in the vignette but the point is once the package is added to the Bioconductor repo the canonical version of the package is in our git server, not the public git server. It will be your responsibility to keep your GitHub account in sync with the Bioconductor git server. Instructions for doing this are here: https://www.bioconductor.org/developers/how-to/git/

All this to say that instructing users to install from GitHub may mean they don't get the most current version in Bioconductor.

**Comment by vobencha** [comment]
Please respond to each item here https://github.com/Bioconductor/Contributions/issues/829#issuecomment-415110546. Let me know how you've addressed these and if you haven't, please explain why.

**Comment by talashuach** [comment]
- all man pages now have running examples
- I moved the vignette data to the general data folder. I did not use this for the examples for runtime reasons, simulated data is smaller than the data I used for the vignette, doesn't take as long to run.
- 'Date' was removed from the DESCRIPTION file
- Man pages that I thought warranted this are already combined this way (e.g getModelParameters)
- README now demonstrates package installation with BIOCManager::install

**Comment by vobencha** [comment]
Thanks for making the changes.

- You don't need man pages for functions that aren't exported, e.g., ``extractProp()`. You can leave them if you want I just wanted to clarify they aren't required.

- What is the `dnaCounts` man page for? I don't see where this function or dataset is defined ... maybe I missed it? If this was an error please check the other man pages to make sure this is cleaned up.

- Reuse existing infrastructure

Why can't the `MpraObject` class extend `SummarizedExperiment::SummarizedExperiment` or the `MultiAssayExperiment::MultiAssayExperiment` class vs being created from scratch? Reuse and compatibility is a priority in Bioconductor. Building on existing infrastructure allows the user to move from method to method more easily vs a completely new import of data, incompatible class etc.

- Name consistency

Your object is named `MpraObject` but the R code file is called `mpraObject`. I think it would make more sense to name these in a consistent way. Any reason whey they are different? 

- S4 accessors 

S4 classes should have accessors (getters / setters). Once these are defined, extraction from slots should be done with the accessor and not '@'. Modifying the object with '@' can lead to an invalid object because it does not pass through an accessor that triggers validity. 

Please create accessors for the S4 classes and use them in your base code. You only need accessors for slots that the user has access to. For example, one of your slots is called `dnaCounts`. The standard approach is to create a getter and setter of the same name that operates on the `MpraObject`. Document this on the class man page. Use the function in your base code so we don't see any instance of
```
if (length(unique(rownames(object@dnaCounts))) != 
```
Instead we should see
```
if (length(unique(rownames(dnaCounts(object)))) != 
```

- MpraObject man page

An S4 class man page should document all accessors and the constructor. Please re-work this page to be more comprehensive. The `GRanges` class is a good example of a complete man page -
```
library(GenomicRanges)
?GRanges
```

**Comment by talashuach** [comment]
Thanks for the comments!

> Thanks for making the changes.
> 
> * You don't need man pages for functions that aren't exported, e.g., ``extractProp()`. You can leave them if you want I just wanted to clarify they aren't required.

I tagged unnecessary man pages with @noRd, but kept the documentation so it'll remain available for anyone looking at the code itself.

> * What is the `dnaCounts` man page for? I don't see where this function or dataset is defined ... maybe I missed it? If this was an error please check the other man pages to make sure this is cleaned up.

It was the name of a matrix included in the ChrEpi.Rda file. I changed the names of the objects in it + combined the documentations of the objects to avoid confusion and organize the man pages.

> * Reuse existing infrastructure
> 
> Why can't the `MpraObject` class extend `SummarizedExperiment::SummarizedExperiment` or the `MultiAssayExperiment::MultiAssayExperiment` class vs being created from scratch? Reuse and compatibility is a priority in Bioconductor. Building on existing infrastructure allows the user to move from method to method more easily vs a completely new import of data, incompatible class etc.

I've considered this. The main problem is that MPRAs consist of two related but distinct data matrices (DNA and RNA) that don't necessarily share dimensionality. Specifically, they share the number of rows, but often the two matrices have a different number of columns. This poses some technical issues that can be handled (i.e both containers supporting a single set of column annotations, whereas this analysis requires two, etc), so it is possible for MpraObject to extend one of these, but I couldn't think of a way for that extension to be intuitive and not misuse the goal of these objects.
Having said that, I'm considering adding a constructor that will initialize an MpraObject from two input SummarizedExperiment objects. Is that a suitable compromise?

> 
> * Name consistency
> 
> Your object is named `MpraObject` but the R code file is called `mpraObject`. I think it would make more sense to name these in a consistent way. Any reason whey they are different?

No good reason, renamed.

> 
> * S4 accessors
> 
> S4 classes should have accessors (getters / setters). Once these are defined, extraction from slots should be done with the accessor and not '@'. Modifying the object with '@' can lead to an invalid object because it does not pass through an accessor that triggers validity.
> 
> Please create accessors for the S4 classes and use them in your base code. You only need accessors for slots that the user has access to. For example, one of your slots is called `dnaCounts`. The standard approach is to create a getter and setter of the same name that operates on the `MpraObject`. Document this on the class man page. Use the function in your base code so we don't see any instance of
> 
> ```
> if (length(unique(rownames(object@dnaCounts))) != 
> ```
> Instead we should see
> 
> ```
> if (length(unique(rownames(dnaCounts(object)))) != 
> ```

I added getters for fields that the user should have access too, and replaced direct access with these getters.

> * MpraObject man page
> 
> An S4 class man page should document all accessors and the constructor. Please re-work this page to be more comprehensive. The `GRanges` class is a good example of a complete man page -
> 
> ```
> library(GenomicRanges)
> ?GRanges
> ```

I added extensive documentation. Since the MpreObject itself is not exported, the object documentation (including detailed description of slots the user doesn't have access too) is included in the code but a man page is not generated, so the object properties (constructor, accessors, etc) are detailed in the constructor man page. They share the same name, so ?MpraObject will give that man page.

Thanks again for the comments,
Tal

**Comment by vobencha** [comment]
Are you planning to submit a new version?

**Comment by talashuach** [comment]
@vobencha 
Sorry, I somehow missed the previous comment. I'll get to work on the constructor right away, will submit a new version by tonight.

Thanks!
Tal

**Comment by talashuach** [comment]
@vobencha 
I added the constructor we discussed (two SummarizedExperiment objects).

Thanks for following up, sorry it took so long to implement.

Tal

**Comment by vobencha** [comment]
Thanks, package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/talashuach.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MPRAnalyze\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MPRAnalyze

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
