### ISSUE TITLE
mcsurvdata

### ISSUE THREAD

**Issue by adricaba** [Bioconductor/Contributions#831]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/adricaba/mcsurvdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Usually experiment data packages have vignettes that describe the data, its origin and any pre-processing steps.

Is there any reason why your methodology is limited to microarrays, or is it likely to be used with more modern technologies (i.e., RNA-seq)? If the latter then [SummarizedExperiment][1] is much preferred as a representation. Also, consider providing the data in simple text-based format, and helper functions to input and assemble it into final objects; this helps protect your data package from 'bit rot' as the format of the R objects changes.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by Liubuntu** [comment]
Hi @adricaba , 

If you already have the vignette available, please bump the version in `DESCRIPTION` so that it triggers an automatic building. When you get a new building report, try to fix all ERROR, or WARNING, and as much as the NOTE messages. 

If you haven't already done so, please follow [the instructions](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for setting up a push hook on your repository, or further changes to your repository will NOT trigger a new build.

Thanks for your contribution to Bioconductor, and let me know for any questions. 

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @adricaba , 

Are you still actively maintaining your package? Like I said in the above comment, please add the vignette in the github repo and bump version, so that the ERROR could hopefully go. 

We are having a general 2 week policy for processing the new package submission. We would expect the package maintain to be actively involved in the package review process (making modifications of your package according to the Bioconductor technical review, bumping versions, address other issues from building report), and we also expect the package maintainer to actively maintain their packages during each release (by fixing bugs, answering user's questions on support or mailing list) after the package is included into Bioconductor. 

If there is no response at all within 2 weeks, we will close the issue for now. Feel free to reopen it whenever you think you would be more available for the process. Thanks, and let me know for any question. 

Best,
Qian

**Comment by adricaba** [comment]
Hi Qian, 

If I am not wrong, I did that last week, but I am afraid I missed sending the confirmation email. 

I hope it is all OK now.

Thanks, 
Adria

**Comment by lshep** [comment]
Please do a version bump in the package DESCRIPTION to kick off a new build.  If the webhook was initialized correctly it will provide a new build report for review.

**Comment by Liubuntu** [comment]
The package is building successfully. A technical review will be given shortly. (within 2 weeks)

**Comment by Liubuntu** [comment]
Hi @adricaba , 

Thank you for the contribution to Bioconductor. Here is the technical review of your experiment data package. Please address the issues and comment back with any question or ready for a 2nd look. Thanks!

## DESCRIPTION

Seems that you have some info for other authors in the documentation. You may want to use `Authors@R` to specificy in DESCRIPTION. e.g.,
```
Authors@R: c(person("Valerie", "Obenchain", role=c("aut", "cre"),
        email="maintainer@bioconductor.org"),
                    person("Martin", "Morgan", role="aut"),
                        person("First", "Last", role="ctb")
```

## vignette

- Add `SessionInfo()` as the section 3 before Reference.
- Some typos, you may want to run a spell checker for the rest.
L29, change "1.072" to "1,072"?
L47, "samples processing" to "sample processing"?
L53: "No samples were excluded" to "No sample was excluded"?
...

Cheers, 
Qian

**Comment by Liubuntu** [comment]
Hi @adricaba , 

I am reminding now (Usually we have 2 weeks notice) only because I will travel from next week with limited internet connection. It would be great if you can make updates soon. Since most of them are really just cosmetic, it would not be hard to address and the acceptance would be fast. Thanks!

Best,
Qian

**Comment by lshep** [comment]
Could you please also update the BiocViews listed in the DESCRIPTION to be from the [ExperimentData](http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData) subset of terms as this is an ExperimentData package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adricaba.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"mcsurvdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mcsurvdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
