### ISSUE TITLE
sparsenetgls

### ISSUE THREAD

**Issue by superOmics** [Bioconductor/Contributions#834]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/superOmics/sparsenetgls

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Here is the review of your package.  The [REQUIRED] tags indicate issues that require a change or an explanation.  The [CONSIDER] tags indicate changes that are advisable but not required.  Please message me back once you are finished making changes.
DESCRIPTION:
- [REQUIRED] `URL` is emptry. Add github link or remove it.

NAMESPACE:
- [CONDSIDER] You seem to be importing the entire set of symbols from
multiple packages. It is advisible to only select symbols needed for
the functionality of your package instead of all of them, so I would
suggest you do this.

R/GENERAL:
- [CONSIDER] The formating of the package's code is a little hard to read.
You may consider using the package `formatR` to make the code easier to read.

R/assess_direct.R
- [REQUIRED] L34-57: Remove double for-loops and vectorize to greatly
improve efficiency.
```
## i's and j's corresponding values can be generated without for-loops
p_len <- seq_len(p)
i <- rep.int(p_len, rev(p_len)
j <- unlist(lapply(p_len, function(x) p_len[x:p]))

## booleans can now be found without for-loop
ij_not_equal <- i!=j
PREC_vals <- PREC_for_graph[i,j]
OMEGA_vals <- OMEGA_for_graph[i,j]

## add up TRUE's of various conditionals
truepos <- sum(ij_not_equal & (PREC_vals!=0))
testpos <- sum(ij_not_equal & (abs(OMEGA_vals)>0))
corrpos <- sum(ij_not_equal & (PREC_vals!=0) & (abs(OMEGA_vals)!=0))
trueneg <- sum(ij_not_equal & (PREC_vals==0))
testneg <- sum(ij_not_equal & (OMEGA_vals==0))
corrneg <- sum(ij_not_equal & (PREC_vals==0) & (OMEGA_vals==0))
```

R/banddata.R
- [REQUIRED] Add more information about this dataset. As a user, I wouldn't know
much about it from the information currently in the `roxygen2` tag. What is its
origins? What data does it contain? What are its dimensions?

R/internal_functions
- [REQUIRED] The `roxygen2` header creates an entry named `density.rd`. This
doesn't seem to be what is desired, so it may be useful to use the `@name` name
tag to rename it more appropriately. In fact, since these function are not user
facing, I don't think any documentation is necessary. You could keep your notes
as comments or just remove it entirely. Same goes for other `roxygen2` headers
in this file.
- [REQUIRED] L16-19, 27, 35, 42, 47-49, 57-62, 69-71, 146-147, 149-168: All of
locations have for-loops that may not be necessary. Since there are so many
instances, I ask that you look at my changes suggested in
`R/assess_direct.R:L34-57` and attempt to make similar changes. I am marking
this as required (although I am not sure all for-loops can be improved on) since
improving efficiency in your utility functions can increase the performance of
your package overall by magnitudes. Please try to improve these.
- [NOTE] L61, 152: The comments mention lower triangles. If it is applicable,
there is a very efficient function in `base` named `lower.tri()` that returns a
matrix represntation of a lower triangle of the inputted matrix.

R/plotsngls.R
- [CONSIDER] L79-98: You may be able to vectorize these for and while loops to
improve the efficiency of the code.

R/sparsenetgls.R
- [CONSIDER] L94-95: Consider using `match.arg()` to make the `method` argument
easier for the user to understand. This would involve declaring `method` as
`method=c("lasso", "glasso", "elastic", "mb")`. The first argument `lasso` will
be the default. The `method` variable can be obtained with
`method <- match.arg(method)`.
- [CONSIDER] L173-188: These double for-loops look like they can be vectorized.

vignettes
- [REQUIRED] L118-199: Bioconducotr will begin using the `BiocManager`
installation paradigm instead of the `BiocInstaller` one in future
releases. This should be documented as:
```
install.packages("BiocManager")
BiocManaged::install("sparsenetgls")
```

**Comment by superOmics** [comment]
@dvantwisk , Thank you for these useful suggestions. 
I have revised the program accordingly, for all required changes, and all considered changes except for one. 
R/sparsenetgls.R
[CONSIDER] L173-188: These double for-loops look like they can be vectorized. 
  
The loops involved list and 3 dimensional array , I found it difficult to vectorize this part. One looping parameter is not expected to be large for sparse matrix (i.e. <10) , the time saving will not be a lot for this part. 
Please check and advise. 

Thank you, 

Irene

**Comment by dvantwisk** [comment]
Sorry for the wait. The changes look good and as long as the triple for loop has a low ceiling, it should be fine. I'm going to move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/superOmics.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"sparsenetgls\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sparsenetgls

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
