### ISSUE TITLE
BDMMAcorrect

### ISSUE THREAD

**Issue by DAIZHENWEI** [Bioconductor/Contributions#839]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DAIZHENWEI/BDMMAcorrect

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Looks like you didn't pay attention to DESCRIPTION/Description field?

**Comment by DAIZHENWEI** [comment]
Thanks a lot for your report! I have updated the package name in the DESCRIPTION. The package name and the repository name are consistent now.

**Comment by DAIZHENWEI** [comment]
The error reports are about the inconsistent package name and repository name. I have updated the package name in the DESCRIPTION. So, the error reported should have been solved now.

**Comment by lshep** [comment]
Make sure you have added your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) as instructed earlier.   If the webhook is initialized, please bump the version in your package to kick off a new build.

**Comment by DAIZHENWEI** [comment]
The error reported by the windows system seems to be the problem of different R version. My package can be installed on the 64 bit R, while installing on 32 bit R may generate some errors. Could you just compile my package on 64 bit R?

**Comment by DAIZHENWEI** [comment]
I have updated the package, such that it can accommodate to the 32 bits R. I also removed the MCMC_algorithm.o, RcppExport.o and  BDMMA.dll in the ./src folder. Please check whether my packages can be compiled on different platforms.

**Comment by lshep** [comment]
Again - we do not do this manually for you -  When you make changes to the package please do a version bump in the DESCRIPTION file and a new build will be made -

**Comment by lshep** [comment]
We also will not review until the package builds without TIMEOUT or ERROR

**Comment by lshep** [comment]
Please update the package to build without ERROR or TIMEOUT.  If there are no updates in the next week we will close the issue for inactivity, where as it can be reopened when you have time to actively participate in the review process.

**Comment by DAIZHENWEI** [comment]
My package has been built without errors or warnings. Would you mind proceeding the review of my pacakge?

**Comment by hpages** [comment]
Hi @DAIZHENWEI ,

Thanks for your submission. I took a first look at BDMMAcorrect and have the following feedback for you:

1. Please address the various `R CMD check` NOTEs, in particular those about:
    - Empty importFrom directives
    - Malformed title
    - Non-standard license
    - Unneeded library(ggplot2) statements
    - Missing importFrom(ellipse, ellipse) and importFrom(vegan, vegdist)
      statements
    - Other missing imports from the stats package

2. `dat` is not a good name for a dataset, it's too generic. Please use a less generic and more meaningful name.

3. Use `names(dat)` instead of `attributes(dat)` in the vignette to display the names of the `dat` list.

4. Where is the `dat` dataset coming from? How was it generated? What are the two phenotype variables in `dat$X`? Why not use meaningful colnames for the `dat$X` data.frame instead of `V1` and `V2`?

5. `datr$Y` is a data.frame but read counts should preferably be stored in a matrix.

6. Also the Bioconductor convention for rectangular datasets like `dat$Y` is to use one column per sample so `dat$Y` would need to be transposed to adhere to this convention. It would then be a 40x80 matrix with 1 row per taxon and 1 column per sample. Don't call a sample an "observation" as this is kind of vague and is generally used to refer to the rows of the rectangular dataset (the taxa in your case).

7. Using `X` for the phenotype variables and `Y` for the read counts are not particularly helpful either. Please use meaningful names for these components (e.g. `pheno` and `counts`).

8. You probably have missed the existence of the SummarizedExperiment class defined in Bioconductor package SummarizedExperiment. The purpose of this class is to bundle together a rectangular dataset and its metadata. So the `dat` dataset could be stored in a SummarizedExperiment object with something like:
    ```
    library(SummarizedExperiment)
    col_data <- DataFrame(dat$X, batch=dat$batch)
    mcols(col_data)$continous <- c(0L, 1L, 0L)
    se <- SummarizedExperiment(list(counts=t(dat$Y)), colData=col_data)
    se
    # class: SummarizedExperiment 
    # dim: 40 80 
    # metadata(0):
    # assays(1): counts
    # rownames(40): V1 V2 ... V39 V40
    # rowData names(0):
    # colnames: NULL
    # colData names(3): V1 V2 batch
    ```
    Then access the read counts with `assay(se)`, the sample metadata with `colData(se)`, and the continous variable with `mcols(colData(se))$continous`.

    There are many advantages in reusing an existing container instead of coming up with an adhoc representation like the `dat` list. Please take the time to familiarize yourself with the SummarizedExperiment container and use it to store metagenomic sequencing data. Then my points 3 and 7 above will become moot.

9. Note that discrete variables should use a discrete type like `integer`, `factor`, `character` instead of a continous type like `numeric`.

10. Finally people will typically use your package on their own data. Please show them how they would typically prepare their data (i.e. bundle it in a SummarizedExperiment object) for use with the BDMMAcorrect package.

Thanks,
H.

**Comment by hpages** [comment]
Hi @DAIZHENWEI 

Have you been able to make any progress on this? Should I take a 2nd look at what you have? Monday would be the last day for adding the package to BioC 3.8.

Thanks,
H.

**Comment by DAIZHENWEI** [comment]
@hpages Thanks so much for your advice! Basically, I have addressed your comments. But there is still a minor issue. I used both the RcppArmadillo and RcppEigen in my package. If I use import() in the NAMESPACE to import the two packages, it will generate some warnings. While if I use importFrom(), it will give a note during R CMD Check. So, I choose to use importFrom(). It that acceptable?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DAIZHENWEI.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BDMMAcorrect")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BDMMAcorrect

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
