### ISSUE TITLE
meshes

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/Contributions#84]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GuangchuangYu/meshes

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by GuangchuangYu** [comment]
already set the push hook.

I made some change of `GOSemSim` to satisfy `meshes` and the new version is not yet build in the BioC build server.

The package should build successful when the new version of `GOSemSim` available in build server.

**Comment by GuangchuangYu** [comment]
@hpages I can't reproduce the warning msg:

```
* checking examples ... WARNING
checking a package with encoding  'UTF-8'  in an ASCII locale
```

I also check my files with `tools::showNonASCII()` and there is not non ascii character reported.

Do you have any idea?

**Comment by hpages** [comment]
Hi Guangchuang,

Thanks for this new contribution. meshes looks good and is almost ready to go. Only a couple of minor issues:

(1) Please use `<-` instead of `=` for assignment everywhere, in particular in the examples in the man pages.

(2) There is just not enough details in the man page of the `enrichResult` class about what the slots contain. But see (3) below before you engage in documenting the slots of the class.

(3) Note that if you were providing accessor functions to let the user access the data in an `enrichResult` you would be presenting an interface to the end user that would be separated from the internal representation of your objects. For example a `geneID(x)` getter would return `x@result$geneID`. Right now, `show(x)` and `head(x)` both display some information labeled geneID but it's not obvious where to find that information in the object. Providing the `geneID()` getter completely avoids that problem since now it doesn't matter anymore where this information is stored exactly. Furthermore, you can always change your mind in the future about the internal representation of your objects: that won't break anybody's code (e.g. users' scripts or other packages accessing your objects) as long as the code always uses the accessors in order to access the data instead of using direct slot access.
Finally note that if you provide a set of getters to let the user extract data from your objects, you don't need to document the internals of the class (i.e. the slots). What you need to document instead is the set of getters. In particular you need to describe the value returned by each getter with the same level of details as you would have done if you had documented the content of each slot.

(4) Why is the geneID information stored in 2 different places, in `x@result$geneID` and in `x@geneInCategory`?
```
    > identical(strsplit(x@result$geneID, "/", fixed=TRUE),
                unname(x@geneInCategory))
    [1] TRUE

```
A good practice in object design is to avoid storing redundant information. Another advantage of providing getters is that they can access "computed slots" i.e. slots that don't exist but are computed on the fly from data taken from other slots. For example, if you provide the `geneID()` getter to access `strsplit(x@result$geneID` then you can define the `geneInCategory()` on top of it like this:
```
    geneInCategory <- function(x)
        setNames(strsplit(geneID(x), "/", fixed=TRUE), rownames(x@result))
```
No need to store the same information in 2 different forms.

Thanks,
H.

**Comment by GuangchuangYu** [comment]
Hi Herve,

Thanks for your suggestions.

## 1.

corrected.

## 2.

The `enrichResult` class was defined in `DOSE` package and all the slots were documented.

```
##' @seealso \code{class?enrichResult}
```

was added in man page of `enrichMeSH` and user can use `class?enrichResult` to view the details of the class.

## 3.

`summary` method can convert the `enrichResult` object to `data.frame` which most of the R users are familar with. There should be no problem to access information like `geneID`. Of course I will add more accessor methods if they are needed.

Some of the slots are used internally for visualization only. If such information is also useful for users, I will define accessor methods to present interface to end users. 

## 4.

`geneInCategory` slot was removed from `enrichResult` class defined by `DOSE` (version >= 2.11.10) and `geneID` and `geneInCategory` methods were defined accordingly as your suggested.

**Comment by hpages** [comment]
Hi Guangchuang,

Thanks for the update. I didn't realize that the enrichResult class was defined in DOSE. Thanks for clarifying. The reason I landed in the man page of this class is because I was running the example in the man page for `enrichMeSH` and got the result in an enrichResult object. So I was curious about this object and did `class?enrichResult` to learn more about it. I didn't realize that this was opening a man page that belongs to the DOSE package. Anyway my advice about providing accessors and documenting them instead of documenting the gory details of the internal representation (a.k.a. slots) of these objects still stands. Except that I understand now that these improvements would need to happen in DOSE and not in meshes.

About this:

> summary method can convert the enrichResult object to data.frame which most of the R users are familar with.

2 problems with this:

- `summary(x)` doesn't return the expected data.frame for me after running the example in the `enrichMeSH` man page:
```
data(geneList, package="DOSE")
de <- names(geneList)[1:100]
x <- enrichMeSH(de, MeSHDb = "MeSH.Hsa.eg.db", database='gendoo', category = 'C')
summary(x)
#     Length        Class         Mode 
#          1 enrichResult           S4 

```
apparently because the `summary` method for enrichResult objects is defined in the DOSE package which is not attached to my session yet. If I load it, then it works:
```
library(DOSE)
dim(summary(x))
# [1] 126   9
```
Please move DOSE from Imports to Depends in your DESCRIPTION file in order to avoid this kind of problems.

- The other problem is that most R users would use `as.data.frame`, and not `summary`, in order to turn an object into a data frame. Providing a `summary` method that does what `as.data.frame` should do is actually a bad idea. `summary` should return, well, a summary of the object, that is, something typically short that can be displayed in a few lines whatever the size of the object is.

Thanks for adding the  `geneID` & `geneInCategory` accessors to the DOSE package. Their man pages are way too minimalist though. Any chance you can improve them? They would need to contain at least a \value and \examples sections.

Thanks,
H.

**Comment by GuangchuangYu** [comment]
Hi Herve, 

Thanks for your suggestion. I know `as.data.frame` is better. 

I did implement `as.data.frame` method in `DOSE` (version >= 2.11.12), and change the `summary` method to:
```
         function(object, ...) {
              warning("summary method to convert the object to data.frame is deprecated, please use as.data.frame instead.")
              return(as.data.frame(object, ...))
          }
```

As the `summary` method exists for quite a long time and `DOSE` was depended by [several Bioconductor packages](https://guangchuangyu.github.io/DOSE/#bioconductor-packages), I can't change the `summary` method at this time since I don't won't to break any existing code.

I have added  `\value` and `\examples` sections in both `geneID` and `geneInCategory`.

All the above changes were happened in `DOSE`.

For `meshes` package, the only change is move `DOSE` from `Imports` to `Depends`.

Thanks,
Guangchuang

**Comment by hpages** [comment]
Hi Guangchuang,

Thanks for all these changes. The package is now accepted. It will be added to our svn repository and to our nightly builds in the next days. You'll soon receive an email with details about this.

Thanks again for your contribution to the Bioconductor project,
H.
