### ISSUE TITLE
brainImageRdata

### ISSUE THREAD

**Issue by saralinker** [Bioconductor/Contributions#843]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saralinker/brainImageRdata

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Looks like the corresponding software package has capital I brainImageR; please change the name of this repository and the package name in the DESCRIPTION file accordingly. This might introduces problems requiring manual intervention on our side, so please post a comment here mentioning @lshep that you have made this change.

**Comment by saralinker** [comment]
Hi @mtmorgan ,

I've changed the name of the repo, the name in DESCRIPTION, and bumped the version number, but it doesn't seem to have registered here. I checked the webhook and it seems to be working. Do you have any suggestions as to what may be the issue?

Best,
Sara

**Comment by mtmorgan** [comment]
Hi Sara -- yes, likely our internal database is confused by the changed name; @lshep will look into this, probably on Monday morning.

**Comment by saralinker** [comment]
Thanks!

**Comment by mtmorgan** [comment]
Users rely on the vignette to provide them with confidence that the code in the package actually works. Your vignette has several code chunks that are evaluated, but these just create data.frames, so the user is only confident that R can create data frames. You need to update your vignette so it performs an actual analysis using the code in your package. This may mean developing a small example data set, or (re)using existing data from an experiment data package or ExperimentHub, or creating your own ExperimentHub resource for use with your package.

**Comment by mtmorgan** [comment]
(oops, deleting a comment posted to the wrong issue, sorry about that!)

**Comment by lshep** [comment]
The internal database has been updated.  The github issue would not automatically update you would have had to also edit those manually but I took care of it for you.  Everything should work properly now and if you try a version bump should see the new build report.

**Comment by saralinker** [comment]
thanks lshep

**Comment by lshep** [comment]
Hi Sara
@nturaga is out for a few weeks so I'll take over this review for him.  A few things:

**Description:** 
- [ ] we know its recommended in the writing cran extensions but remove lazydata true we rarely find it useful and actually can slow down building. Especially since there are actually no data files actually loaded
- [ ] Should be depending on ExperimentHub for retrieval of data and show example in vignette and/or man page

**Vignette:**
Currently missing? Even tho this is a data package we recommend some documentation.  Perhaps a minimum vignette that describes the data available via the hub and describing the hub interface for retrieving your specific data

**Man:** 
No man pages.  Again we recommend some documentation.  At the very least maybe a package man package again describing the available data

With a little documentation I think this will be accepted shortly.  Please make the above changes and respond back when you are ready for me to take another look. 

Cheers

**Comment by lshep** [comment]
Hi Sara -  Just wanted to check in with your progress and if you had any questions about the above comments?   May we expect updates soon?

**Comment by saralinker** [comment]
Hi Ishep, I apologize for the delays! It's been a little hectic over here. I'm going to try to have the updates finished today.

**Comment by saralinker** [comment]
Hi @lshep 

I've added in the vignette, changed the DESCRIPTION, and pushed. I didn't add a man page because I wasn't exactly sure how the syntax works when I don't have a particular script to reference. Will this be necessary to be accepted? If so, I can try to add a script that loads the data and make a man page for that?

**Comment by lshep** [comment]
To mock a package documenation page with roxygen you can create an R file that is above a NULL and use @docType package 
so a file called  R/brainImageRdata.R
```
#' brainImageRdata contains image masks for the developing human .... 
#' @section {data available}
#' @docType package
#' @aliases
NULL
```

Its not strictly required but I do strongly encourage it so users can do `?brainImageRdata`

Cheers

**Comment by lshep** [comment]
Also to get rid of the ERROR please add  Suggests: knitr to the DESCRIPTION  file.  

Once this is added and the proper version bump - your package should build cleanly and will be accepted.

**Comment by saralinker** [comment]
he @lshep I'm having trouble finding documentation on the error "Accessing git_info complete. get_dcf_info failed; could not open." My git account seems to be fine. Would you be able to advise?

**Comment by lshep** [comment]
This has to do with the formatting of the DESCRIPTION file.  Please try removing the lines breaks in the `Description:` entry.  
ie.
``` 
Description: brainImageRdata contains image masks for the developing human
and the adult human brain. These masks can be used in conjunction with the
gene expression data to generate spatial gene set enrichment plots. It also
contains the expression data for the 15 pcw human brain, the adult human
brain, and the developing human brain.
```
Should all be on one line 

Sorry that the ERROR message wasn't very helpful in determining this

**Comment by saralinker** [comment]
Thanks @ishep

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/saralinker.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"brainImageRdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/brainImageRdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
