### ISSUE TITLE
Supporting data for package OMICsPCA

### ISSUE THREAD

**Issue by subhadeep1024** [Bioconductor/Contributions#845]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/subhadeep1024/OMICsPCAdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Related packages are normally submitted in the same issue. The idea is to submit one package (this one) and to work through the automatic build process until it is 'clean'. Then add the second package using the AdditionalPackage tag as outlined in [the instructions][1].

I will close the software package issue. Before this package can be added to the review queue, you must add biocViews: terms [from the ExperimentData ontology][2]. Also, please carefully review the need for each of your data objects in terms of availability from ExperimentHub, AnnotationHub, or Bioconductor annotation / experiment data resources. Finally, we strongly recommend that new 'experiment data' resources be provided via ExperimentHub, with the experiment data package simply being a shell that retrieves the data. Please see [this vignette][3] for more information.

[1]: https://github.com/Bioconductor/Contributions#submitting-related-packages
[2]: http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData
[3]: http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

**Comment by subhadeep1024** [comment]
The following modifications are done:
1) updated description file and data folder
2) added man, vignettes, news.
3) added webhook.

**Comment by subhadeep1024** [comment]
Hi,

Should I upload the software package now?
One of the earlier messages said
"The idea is to submit one package (this one) and to work through the automatic build process until it is 'clean'."
I am not sure if the 'OK' and 'clean' tag is the same or not.

**Comment by mtmorgan** [comment]
yep, following the instructions linked above.

**Comment by subhadeep1024** [comment]
AdditionalPackage: https://github.com/subhadeep1024/OMICsPCA

**Comment by subhadeep1024** [comment]
changed the data package OMICsPCAdata and bumped to new version.

**Comment by subhadeep1024** [comment]
Reduced number of data sets in the data package.  Going to bump the version of software package to check if check time reduces or not.

**Comment by subhadeep1024** [comment]
Hi,
@vobencha 
I am not sure why it is getting an "ERROR" message while getting built on the linux system. I have added the dependency "pdftool" in "NAMESPACE" and in"DESCRIPTION" but still getting the messeage "dependency pdftools is not available for package OMICsPCA".

Another "ERROR" is received on the mac system at the R CMD BiocCheck : 
ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 8.971 MB
        Size Requirement: 4.0000 MB

In my local windows machine the source tarball is 1.96 mb. I am not sure why it is getting so large in the mac system.
Can you please help?

**Comment by vobencha** [comment]
I will look at these issues and the packages in general in the next couple days.

Valerie

**Comment by subhadeep1024** [comment]
Ok. Thanks a lot.

**Comment by vobencha** [comment]
@lshep do you know why we see such a difference in 'PackageFileSize' in the summary section in the SPB output?
tokay1: 1919.00 KiB
malbec1: -1.00 KiB
merida1: 8760.75 KiB

Does the check test the size of the output from `R CMD build` (and not `R CMD build --no-build-vignettes`) such that the size of the built vignette is included?

**Comment by lshep** [comment]
I would assume the size of the built vignette is included as the size is determined off the build product which does include the vignette. We use  `R CMD build --keep-empty-dirs --no-resave-data` to create the tar.gz that I then check size.

**Comment by vobencha** [comment]
Thanks @lshep.

@subhadeep1024 , I believe the size difference is due to how images are embedded in the html doc. I'm not sure which rmarkdown or knitr option might control this. You have quite a bit of specific formatting at the top of your vignette file. Can you simplify this?

Please change `LazyData` to FALSE in the data package. Marking this as TRUE greatly increases load time for the package.

I've taken care of the necessary dependencies for pdftools on the Linux builders. Please bump the versions of both packages so we get a new build. Once I see that output I'll do a full review.

**Comment by subhadeep1024** [comment]
@vobencha 
I changed the lazydata to FALSE in both the packages, as you have suggested. regarding the specific formatting, I am not sure how to simplify them. Although the CSS formatting is optional, they maintain the text/image/table ratio in good shape. However, If you specifically mention the formatting issues, I will try to improve those.
Regarding the size of the tarballs, I could not find any solution yet, but trying to solve it.

**Comment by subhadeep1024** [comment]
@vobencha 

Hi,
Is my package under "full review"?

**Comment by vobencha** [comment]
It is not. We have a limited number of reviewers and a large number of packages. This package was submitted 10 days ago. The standard is to expect a review in 14 days. I will get to this as soon as I can but there are other packages in front of yours.

Please be patient. When the review is done it will be posted here. Until then, there is nothing required from your end.

**Comment by subhadeep1024** [comment]
ok. thanks.

**Comment by vobencha** [comment]
Hi,
Here is the full review. When you've addressed these, please explain what was done for each point raised. Let me know if you have questions.

Data package:

- The man pages for the .rda files look good. Do you have a url for the data? Has any QC or processing been done to create the data.frames? Please add any detail you might have about that - just a heads up to the user.

- What are the data in extdata/ used for?
```
~/OMICsPCAdata >du -hs inst/extdata/*
30M    inst/extdata/annotation
24M    inst/extdata/factors
4.0M    inst/extdata/groupinfo
8.3M    inst/extdata/H2az
80M    inst/extdata/rawdata
```
- This \usage is incorrect on the H2az_Cell_wise man page:
```
\usage{data("H2az")}
```

Software package:

- Is OMICsPCA truly functional without the data package? If the software requires the data package to be functional it should 'Depend' and not 'Import' the data package in the DESCRIPTION.

- I now see where you are using the extdata/ from the data package. Again, I'd like some background on why you are using data in extdata/ and not data/ for the man pages examples, whether or not these are essential to the software package etc.

- If you 'Depend' on the data package please remove "library(OMICsPCAdata)" from all man pages. Regardless, it should not be in the man page if it's commented out.

- Why are so many of the man page examples commented out? You need running example of the documented function on each man page. Please fix or explain.

- The OMICS class is a collection of lists with no particular structure. I don't think there is any reason to create your own class - there are several containers in the infrastructure designed to hold 'omics' data. These classes come with validity methods, accessors and methods for managing metadata. Please use a class from MultiAssayExperiment::MultiAssayExperiment or SummarizedExperiment::SummarizedExperiment. If you want to look at other potentially compatible packages you can search the biocViews:

https://www.bioconductor.org/packages/release/BiocViews.html#___Software

- Please choose either camelCase or underscores for naming the functions you export. Right now you've got a mixture:
```
~/OMICsPCA >ls R
analyse_individuals.R             cluster_boxplot.R     descriptor.R       integrate_variables.R
analyse_integrated_individuals.R  cluster_parameters.R  extractAssays.R    plot_density_3D.R
analyse_integrated_variables.R    cluster.R             extract.R          plot_density.R
analyse_variables.R               create_group.R        inputOMICs.R       prepareDataset.R
chart_correlation.R               create_OMICs.R        integrateAssays.R  setclass.R
```

**Comment by subhadeep1024** [comment]
Hi,

Data package : 
1) The Histone modification are collected from : 
https://www.encodeproject.org/matrix/?type=Experiment&assay_title=ChIP-seq&target.investigated_as=broad+histone+mark

The DNaseI hypersensitivity (DHS) datasests are collected from :
http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/openchrom/jan2011/fdrPeaks/

The Histone fand DHS files are downloaded as bigbed(.bb) format and converted to bed(.bed) format

The CAGE datasets are collected from :
https://www.encodeproject.org/search/?type=Experiment&assay_slims=Transcription&replicates.library.biosample.donor.organism.scientific_name=Homo+sapiens&assay_title=CAGE

The CAGE datasets were downloaded as bam(.bam) files and comverted to sam by samtools. The sam files are processed through CAGEr package in R to obtain CTSSs.

2) As you have already figured it out, the datasets in extdata are used in the vignette and man page examples of the software package.

3) "This \usage is incorrect on the H2az_Cell_wise man page" : rectified


Software package:

1) "Is OMICsPCA truly functional without the data package?" : 

Yes. The data package is included to run the examples in vignette and man pages of the software package.
 
" If the software requires the data package to be functional it should 'Depend' and not 'Import' the data package in the DESCRIPTION." : 

The software package is independently functional if the datasets are provided in the specified format and the instructions are followed as mentioned. So the software package does not essentially "Depends" on the data package.


2) "Again, I'd like some background on why you are using data in extdata/ and not data/ for the man pages examples, whether or not these are essential to the software package etc." :

There are two ways to read the data in the OMICs object: from files and from object. The dataframes (rawdata) are kept to show how to read from files. 

Again, reading from files can be done in two ways: 

i) the assay data and annotation data are already overlapped --> dataframes in extdata/rawdata
ii) an overlap overation needs to be done (using prepareDataset) --> extdata/factors and extdata/annotation

Among the other two files in extdata/, groupinfo is used in the create_group() example to demonstrate how predefined groups can be read from files. The H2az file is currently not in use. we can remove it if required.

3) "If you 'Depend' on the data package please remove "library(OMICsPCAdata)" from all man pages. Regardless, it should not be in the man page if it's commented out" : 

As mentioned earlier, OMICsPCA is an independent package and does not require OMICsPCAdata to function. But the examples of vignette and man pages are dependent on the data package. So, please suggest whether I should use "imports" or "depends"

4) "Why are so many of the man page examples commented out? You need running example of the documented function on each man page. Please fix or explain" : 

The functions of OMICsPCA is desigend to work in a sequential way. Some functions populate the slots of the OMICs object and the rests access those slots. Therefore, all the other functions need to be run prior to the dependent functions and hence, mentioned in the man pages. But, it substantially increases the check and build time. Therefore, I commented them out in the man pages.

5)  "Please use a class from MultiAssayExperiment::MultiAssayExperiment or SummarizedExperiment::SummarizedExperiment." : 

I tried using SummarizedExperiment but it seems that it is designed to handle datasets with single columns (as the examples show) and/or datasets having equal number of columns. In contrast, the datasets used in this software package:

i) have multiple columns
ii) have unequal number of columns

Moreover, I designed 2 slots "PCA" and "IntegratedPCA" which hold the data generated by two PCA functions. I am not sure how to keep such data in "MultiAssayExperiment" slots.

In addition to that, the functiones here are designed to access data specifically from the OMICsobject. So, if this data structure is changed, all the functions needs to be reconstructed.

6) "Please choose either camelCase or underscores for naming the functions you export. Right now you've got a mixture"

Alright, I will change the cases.

Please let me know if you need more information or explanation. 

Thanks a lot for the in-depth review.

**Comment by vobencha** [comment]
Hi,
Thanks for the details.

- Extend existing class

Yes, having different number of columns excludes SummarizedExperiment. How about including the "PCA" and "IntegratedPCA" output as elements the ExperimentList class in the MultiAssayExperiment?

From the man page:
```
> example("ExperimentList")
> class(ExpList)
[1] "ExperimentList"
attr(,"package")
[1] "MultiAssayExperiment"
> ExpList
ExperimentList class object of length 4:
 [1] Affy: SummarizedExperiment with 5 rows and 4 columns
 [2] Methyl450k: matrix with 5 rows and 5 columns
 [3] RNASeqGene: matrix with 5 rows and 4 columns
 [4] GISTIC: RangedSummarizedExperiment with 5 rows and 3 columns 
```
- Software package man pages

It is not ok to have unevaluated man page examples - the package will not be accepted in this form. You need to find smaller sample data that can be saved as part of your pipeline to use in the examples. More discussion on the data package below.

NOTE: If you choose to go the route of reducing the size of the experimental data package, the description of where the data were downloaded and how they were processed needs to go in the man pages.

- Smaller data package

In general, experimental data packages contain data from an experiment, manuscript publication or course. Other data packages have example data that can be used by multiple people so not all package authors need to include sample data in their software package. The size of your data package is too big for use by a single software package.
```
~ >du -h OMICsPCAdata_0.99.5.tar.gz
50M    OMICsPCAdata_0.99.5.tar.gz
```
Additionally, the experiment data packages are kept under version control and we avoid storing large amounts of static data in that environment. You have a couple of options:

-- The preferred solution is to find other sample data in ExperimentHub, AnnotationHub or existing experimental data packages.

https://www.bioconductor.org/packages/release/BiocViews.html#___ExperimentData
https://www.bioconductor.org/packages/release/BiocViews.html#___AnnotationData
```
library(AnnotationHub)
ah = AnnotationHub()
query(hub, "BED") # query for available bed files
```
Same procedure for ExperimentHub ...

-- Reduce the amount of data needed for the man pages and vignette so the experiment data package is <10 MG

-- Put the data in an ExperimentHub package. The size limit here isn't as strict because the data are stored in AWS S3 and not under version control. See section on "Including Data" in https://www.bioconductor.org/developers/package-guidelines/.

**Comment by subhadeep1024** [comment]
@vobencha 

Hi,

The issues you had raised are solved:

1) data size reduced (< 10 mb)
2) data is packaged in a MultiAssayExperiment object
3) the commented out sections at man page examples are removed.

In order to resolve the issues, I had to change some code structure of the functions but the major outputs are same.

I also have changed the same of one function from "integrateAssays" to "integratePCA".

**Comment by subhadeep1024** [comment]
function names are changed from camel case to underscore format.

**Comment by subhadeep1024** [comment]
This time I set the lazydata of the data package to TRUE, because the examples in the .Rd files use the data of the data package.

**Comment by vobencha** [comment]
Hi,

* pdf error in vignette

If the vignette needs a graphic it should generally be gif, tiff or png (not pdf) and they should be in the vignettes/ directory (not inst/extdata).

* Consider consistent names for the data files (camelCase or underscores):

~/repos/github/packageReview >ls OMICsPCAdata/man/
clustered_data.Rd  groupinfo_ext.Rd  MultiAssay.Rd  transcript_details.Rd

* LazyData should still be FALSE, this has nothing to do with the data being used in the man page examples.

* Add a .gitignore file for both packages:

https://www.bioconductor.org/developers/package-guidelines/#gitignore

* The git history in the data package is huge. Can this be cleaned up? Better yet, why not make this an ExperimentHub package? Martin suggested this in https://github.com/Bioconductor/Contributions/issues/845#issuecomment-414361462
```
~/repos/github/packageReview >du -h OMICsPCAdata/
52K    OMICsPCAdata/.git/hooks
4.0K    OMICsPCAdata/.git/branches
88M    OMICsPCAdata/.git/objects/pack
4.0K    OMICsPCAdata/.git/objects/info
88M    OMICsPCAdata/.git/objects
8.0K    OMICsPCAdata/.git/info
8.0K    OMICsPCAdata/.git/logs/refs/heads
8.0K    OMICsPCAdata/.git/logs/refs/remotes/origin
12K    OMICsPCAdata/.git/logs/refs/remotes
24K    OMICsPCAdata/.git/logs/refs
32K    OMICsPCAdata/.git/logs
4.0K    OMICsPCAdata/.git/refs/tags
8.0K    OMICsPCAdata/.git/refs/heads
8.0K    OMICsPCAdata/.git/refs/remotes/origin
12K    OMICsPCAdata/.git/refs/remotes
28K    OMICsPCAdata/.git/refs
88M    OMICsPCAdata/.git
20K    OMICsPCAdata/man
28K    OMICsPCAdata/inst/extdata/rawdata
12K    OMICsPCAdata/inst/extdata/factors2/demofactor
16K    OMICsPCAdata/inst/extdata/factors2
12K    OMICsPCAdata/inst/extdata/annotation2
100K    OMICsPCAdata/inst/extdata
104K    OMICsPCAdata/inst
6.5M    OMICsPCAdata/data
8.0K    OMICsPCAdata/vignettes
95M    OMICsPCAdata/
```

**Comment by subhadeep1024** [comment]
@vobencha 

Hi,

I tried to solve the issues you raised in your last comment. But there are some confusions. Pardon me, there might be some very silly queries (which is too tough to a biologist).

1) "pdf error in vignette

If the vignette needs a graphic it should generally be gif, tiff or png (not pdf) and they should be in the vignettes/ directory (not inst/extdata)"

In my local machine, there is no "vignette" folder at the location where the package is installed. i.e. at C:/Users/.../R/3.5/win-library/OMICsPCAdata.
But, If the graphic file is kept at "inst/extdata", it is easily accessible by "system.file("extdata", package = "OMICsPCAdata)".  So, if I keep the graphic file in vignette directory (either of data or software package), what path should I provide to locate it?

The best solution I found is to delete the pdf and I did it.

2) "Consider consistent names for the data files (camelCase or underscores)"

Done.

3) "LazyData should still be FALSE, this has nothing to do with the data being used in the man page examples"

If lazy data is set to FALSE then the dataset multi_assay is not accessible from the examples of man pages. This issue can be solved by importing data to each man page (e.g. data(multi_assay), data(groupinfo_ext)), but it increases the check time (R CMD check) around 3 times. (from 5 minutes to 15 minutes).

4) "Add a .gitignore file for both packages:"

Added.

5) "The git history in the data package is huge. Can this be cleaned up?" 

Not clear. Will deleting some records from the ".git" folder of my local machine (which is synced with github) work? If so, then which ones should I delete? 

6) "Better yet, why not make this an ExperimentHub package? Martin suggested this in #845 (comment)"

Reasons:
i) you suggested 3 options:
 "Additionally, the experiment data packages are kept under version control and we avoid storing large amounts of static data in that environment. You have a couple of options: 

-- The preferred solution is to find other sample data in ExperimentHub, AnnotationHub or existing experimental data packages.

-- Reduce the amount of data needed for the man pages and vignette so the experiment data package is <10 MG,

-- Put the data in an ExperimentHub package. The size limit here isn't as strict because the data are stored in AWS S3 and not under version control." 

Now to me, The second option is better, because the datasets I have used is perfect to describe the proper functionality of the software package. Therefore I reduced it to <10 mb.

ii) I could not understand the structure of the ExperimentHub package. For example:

what to write in make-data.R and make-metadata.R? I am trying to find examples but could not find an appropriate one so far. It would be a great help if you can help me out in this regard.

**Comment by vobencha** [comment]
Hi,
Thanks for making the changes.

1. vignette files

In general, inst/extdata and data/ are reserved for data files. If you need a graphic for the vignette you can put it in the vignettes/ directory.

Look at the source code of the AnalysisPageServe package as an example:
https://www.bioconductor.org/packages/release/bioc/html/AnalysisPageServer.html

3. LazyData

Yes, it is true that by setting LazyData=TRUE you don't need to call the data() wrapper to load the data file. However, calling data() is not a big effort and IMO is more instructive to the user as to what is going on - e.g., a data set of this name is being loaded and then used. There is a disadvantage to setting LazyData=TRUE when the data files are large. The minor advantage of not using the data() wrapper does not outweigh the disadvantage of longer load times.

Lazy loading is part of the installation and when used, the R objects are created at installation time and stored in a db in the R directory of the installed package. The db consists of 2 binary files, one with `.rdb` extension (the objects) and one with `.rdx` (the index). Instead of loading the objects into the envir, the lazy load mechanism creates promises that load the object from the db when they are first accessed.

When a package has large data files we've seen LazyData=TRUE slow down package installation. I believe the 'slowness' comes from creating the index. 

In your case, the software package does not have data in data/ or inst/extdata; there is no need to include LazyData in DESCRIPTION. The data package currently has LazyData=FALSE so that looks fine.

If you want LazyData=TRUE in your data package, please save one object per file and try different compression options, e.g., tools::resaveRdaFiles(), saveRDS(), etc.

5. cleaning git history

@nturaga, the size of the .git directory in the data package looks large to me. Do you have any recommendations for cleaning this up?
```
~ >du -hs OMICsPCAdata/.git
127M	OMICsPCAdata/.git
```
6. ExperimentHub package

alpineData is an ExperimentHub package:
https://www.bioconductor.org/packages/release/data/experiment/html/alpineData.html

You can download the source tarball and unpack it to see an example of the package structure.
```
~/Downloads >tree alpineData
alpineData
├── build
│   └── vignette.rds
├── DESCRIPTION
├── external_data_store.txt
├── inst
│   ├── doc
│   │   ├── alpineData.html
│   │   ├── alpineData.R
│   │   └── alpineData.Rmd
│   ├── extdata
│   │   ├── metadata.csv
│   │   └── selected.genes.txt
│   └── scripts
│       ├── make-data.Rmd
│       └── make-metadata.R
├── man
│   └── alpineData-package.Rd
├── NAMESPACE
├── NEWS
├── R
│   └── zzz.R
└── vignettes
    └── alpineData.Rmd
```

**Comment by subhadeep1024** [comment]
@vobencha 

Hi,
Thanks a lot for your suggestions.  The reason I was concerned about the LazyData is that the runtime was exceeding 5 minutes. If that is not a problem from your end, I am totally ok with the present structure of the packages.

Regarding the ExperimentHub structure, all the preprocessing was done using shell scripts, perl and awk.
I understand that the scripts can be converted to R format or some wrapper functions may be used, but it will cost me a considerable amount of time and effort. So, I do not want any further modifications until they are mandatory. Moreover, in the vignette, I have shown the original format of the data and included functions in the package for necessary preprocessing. Therefore, I think it is sufficient for the user to understand the preprocessing steps and go to the analysis section without any trouble. 

I really appreciate your valuable suggestions. I will certainly use ExperimentHub packaging from my next packages to preprocess data from scratch.

**Comment by vobencha** [comment]
Yes, the check time is a problem. Looking at the SPB output, can you choose a few of the longer running examples to trim down?:
```
* checking examples ... OK
Examples with CPU or elapsed time > 5s
                                 user system elapsed
analyse_individuals            14.528  0.132  14.963
cluster_parameters             12.700  0.176  12.881
analyse_integrated_individuals 11.164  0.180  12.108
plot_integrated_density_3D     11.184  0.048  11.236
cluster                        11.100  0.080  11.232
analyse_integrated_variables   11.016  0.076  11.097
extract_assay                  10.752  0.284  11.040
cluster_boxplot                10.792  0.056  10.867
extract                        10.752  0.068  10.822
plot_integrated_density        10.632  0.036  10.673
create_group                   10.416  0.088  10.508
integrate_pca                  10.420  0.052  10.475
plot_density_3D                10.388  0.076  10.465
descriptor                     10.020  0.044  10.067
chart_correlation               9.884  0.056   9.942
analyse_variables               9.824  0.064   9.890
plot_density                    9.264  0.028   9.296
integrate_variables             9.132  0.028   9.164
```

These problems in the SPB output need to be fixed:
```
* checking installed package size ... NOTE
  installed size is  7.1Mb
  sub-directories of 1Mb or more:
    doc   6.9Mb

* checking dependencies in R code ... NOTE
Package in Depends field not imported from: OMICsPCAdata
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

**Comment by subhadeep1024** [comment]
I will start with the summary of the review done so far:

1) The size of data package exceeded 10 mb. I reduced it down, and the issue is resolved

2) You suggested to use MultiAssayExperiment instead of OMICs class (defined by me) and I did that. The issue is solved.

3) The examples were commented out in the man pages as they were increasing the check time. I resolved this issue by 
i) changing the structure of the package (used MultiAssayExperiment instead of"OMICs class)
ii) setting the LazyData = TRUE.
These changes solved the problem of check time and the problem of commented out sections in man pages.

4) But you suggested setting the Lazy data = FALSE. When I set the LazyData = FALSE, the check time increases at least three times more.

If I need to solve both the issues together, i.e. Lazydata=TRUE and check time < 5 min. I have 2 options,
i) use ExperimentHub structure
ii) reduce the data size even more.

The first option demands lots of effort and time (and I am not sure whether it will reduce the check time or not). The second option may not produce the appropriate results shown in the vignette. It does not mean that the package is data dependent, it means other data is not as perfect as is the present data.

Again, all these problems may be solved just by setting Lazydata = TRUE.

Now let's come to your opinion against setting Lazydata = TRUE:

1) "There is a disadvantage to setting LazyData=TRUE when the data files are large"

How large is considered as "large"? I reduced down the data size from >50 mb to <10 mb. Should it still be considered as large?

2) "The minor advantage of not using the data() wrapper does not outweigh the disadvantage of longer load times"

the check time goes up from 4 mins to 15 mins: should it be still considered as a "minor" advantage?

3) "When a package has large data files we've seen LazyData=TRUE slow down package installation"

Now, the data size is in the data package is <10 mb and the software package does not have any data. If this size is not "large" and the installation is not slowing down significantly, then what is the problem with Lazydata= TRUE? especially when the check time is reduced down substantially.

Now let's come to the issue of package size. Regarding the installed package size, I had drawn your attention long time back and here is the corresponding section of our conversation:

> @lshep do you know why we see such a difference in 'PackageFileSize' in the summary section in the SPB output?
> tokay1: 1919.00 KiB
> malbec1: -1.00 KiB
> merida1: 8760.75 KiB
> 
> Does the check test the size of the output from `R CMD build` (and not `R CMD build --no-build-vignettes`) such that the size of the built vignette is included?


reply of lshep
> I would assume the size of the built vignette is included as the size is determined off the build product which does include the vignette. We use `R CMD build --keep-empty-dirs --no-resave-data` to create the tar.gz that I then check size.


> Thanks @lshep.
> 
> @subhadeep1024 , I believe the size difference is due to how images are embedded in the html doc. I'm not sure which rmarkdown or knitr option might control this. You have quite a bit of specific formatting at the top of your vignette file. Can you simplify this?
> 
> Please change `LazyData` to FALSE in the data package. Marking this as TRUE greatly increases load time for the package.
> 
> I've taken care of the necessary dependencies for pdftools on the Linux builders. Please bump the versions of both packages so we get a new build. Once I see that output I'll do a full review.


In summary, the package size in windows is not exceeding 4 mb (it is 1.96 mb in my local machine), but why it is exceeding the limit in linux and mac is still unknown. 
Please note that, I have not embedded any pdf or image files in the vignette, except the ones being generated by the vignette codes.

So, can you specifically give me any suggestions on how to tackle this size issue (in linux and mac)?


Regarding the "depends" issue, you said:

"Is OMICsPCA truly functional without the data package? If the software requires the data package to be functional it should 'Depend' and not 'Import' the data package in the DESCRIPTION"

and I replied, 

"As mentioned earlier, OMICsPCA is an independent package and does not require OMICsPCAdata to function. But the examples of vignette and man pages are dependent on the data package. So, please suggest whether I should use "imports" or "depends".

But, there was not any further discussion on this issue. So, again I am asking for your help with this issue.

The total conversation so far may be summarized as a cycle:

1) You raise an issue
2) I solve it
3)  you move to other issues
4)  You again come back to issue 1 (for example, the package size issue)

In this way, I am really getting lost and confused. Can we attend one issue (or set of issues) at a time and not move to the next ones until it is/they are solved?

Thanks a lot for your time, patience and bearing with me for so long. I really appreciate it.

**Comment by vobencha** [comment]
Hi,

Starting at the top of https://github.com/Bioconductor/Contributions/issues/845#issuecomment-424735990

1,2,3 are solved.
4. Setting LazyData TRUE or FALSE is your decision (not a requirement). I was trying to provide background as to why we suggest this. If keeping this as TRUE reduces your check time than you can leave it as TRUE.

package size: I do not know why the vignette is larger on Linux and Mac than Windows. This would take some time to troubleshoot. My only guess at this point is that it's related to the graphics and how they are embedded in the final vignette product. The size on Windows is fine, Linux is only just above the size requirement. I am ok to let the size issue go if we tidy up the other things.

depends issue: The error I pasted above is saying you need to import the data package in the NAMESPACE.  (Note this is different from having the package in the 'Imports' field of the DESCRIPTION file and that's not what it is asking for.) You have the data package in the 'Depends' field of the DESCRIPTION file of the software package (fine) but you also need to import it in the NAMESPACE:
```
import(OMICsPCAdata)
```
ExperimentHub issue: ExperimentHub was an option not a requirement. I was providing background so you understood the procedure if you went that route. You chose to go with the experimental data package. This is fine.

Package review is not always a straightforward path. When one problem is fixed it often leads to the discovery of another. Thank you for making the changes you have made. I realize you have been at this for some time now and would like to wrap it up. The last two tings that need to be fixed are
- import the data package in the NAMESPACE of the software package
- set LazyData=TRUE to produce reduced check times

Once these two things are done those errors in the SPB report should go away and we can approve the package.

**Comment by subhadeep1024** [comment]
@vobencha 

Hi, 

I have done the modifications as suggested. I have a query: I have plans to add more functions to this package in future. What is the procedure to do that?

Thanks a lot in advance.

**Comment by vobencha** [comment]
Instructions for maintaining the package in git (i.e., adding new functions) are on the web site:
https://www.bioconductor.org/developers/how-to/git/

**Comment by subhadeep1024** [comment]
@vobencha 

Thanks a lot for your generous and continuous support.

**Comment by mtmorgan** [comment]
Is OMICsPCA meant to be  a software package, or a worklfow package? It has terms from both parts of the biocViews hierarchy, but should have terms from only one.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/subhadeep1024.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"OMICsPCAdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OMICsPCAdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/subhadeep1024.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"OMICsPCA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OMICsPCA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
