### ISSUE TITLE
XINA: a workflow for the integration of multiplexed proteomics kinetics data with network analysis

### ISSUE THREAD

**Issue by langholee** [Bioconductor/Contributions#847]
Hello,

I am Lang and want to submit XINA to Bioconductor. I checked XINA by using R CMD Check and Bioccheck and found no warnings and no errors. Of course, I know these are just minimum requirements. Please consider XINA to add to the Bioconductor repository. I attached the abstract part of XINA manuscript that I submitted to Journal of Proteome Research.

XINA ABSTRACT
Quantitative proteomics experiments, using for instance isobaric tandem mass tagging approaches, are conducive to measuring changes in protein abundance over multiple time points in response to one or more conditions or stimulations. The aim is often to determine which proteins exhibit similar patterns within and across experimental conditions, since proteins with co-abundance patterns may have common molecular functions related to a given stimulation. In order to facilitate identification and analyses of co-abundance patterns within and across conditions, we previously developed a software inspired by the isobaric mass tagging method itself. Specifically, multiple datasets are tagged in silico and combined for subsequent subgrouping into multiple clusters within a single output depicting the variation across all conditions; converting a typical inter-dataset comparison into an intra-dataset comparison. An updated version of our software, XINA, not only extracts co-abundance profiles within and across experiments, but also incorporates protein-protein interaction databases and integrative resources such as KEGG to infer interactors and molecular functions, respectively, and produces user-friendly graphical outputs. In this report we compare the kinetics profiles of >5,600 unique proteins derived from three macrophage cell culture experiments and demonstrate through intuitive visualizations that XINA identifies key regulators of macrophage activation via their co-abundance patterns.

Update the following URL to point to the GitHub repository of
the package you wish to submit to Bioconductor

Repository: https://github.com/langholee/XINA
Confirm the following by editing each check box to '[x]'

[O] I understand that by submitting my package to Bioconductor,
the package source and all review commentary are visible to the
general public.

[O] I have read the Bioconductor Package Submission
instructions. My package is consistent with the Bioconductor
Package Guidelines.

[O] I understand that a minimum requirement for package acceptance
is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS.
Passing these checks does not result in automatic acceptance. The
package will then undergo a formal review and recommendations for
acceptance regarding other Bioconductor standards will be addressed.

[O] My package addresses statistical or bioinformatic issues related
to the analysis and comprehension of high throughput genomic data.

[O] I am committed to the long-term maintenance of my package. This
includes monitoring the support site for issues that users may
have, subscribing to the bioc-devel mailing list to stay aware
of developments in the Bioconductor community, responding promptly
to requests for updates from the Core team in response to changes in
R or underlying software.

I am familiar with the essential aspects of Bioconductor software
management, including:

[O] The 'devel' branch for new packages and features.
[O] The stable 'release' branch, made available every six
months, for bug fixes.
[O] Bioconductor version control using Git
(optionally via GitHub).
For help with submitting your package, please subscribe and post questions
to the bioc-devel mailing list.

**Comment by langholee** [comment]
I modified example codes.  Please do check up process again.  Thanks.

**Comment by mtmorgan** [comment]
be sure that you have correctly installed the 'webhook' on your github repository, and remember to always 'bump your version' (to 0.99.1, then 0.99.2, ...) each time you wish the build system to rebuild your package.

**Comment by langholee** [comment]
@mtmorgan  v.0.99.1 is ready for get rid of TIMEOUT label!

**Comment by mtmorgan** [comment]
bump the version to 0.99.2 and it will automatically start a build.

**Comment by langholee** [comment]
Yeah! Go XINA!

**Comment by vobencha** [comment]
Hi @langholee 
I've done a first review. Let me know if you have questions.

1) What is the main contribution of the package?

It's not clear from the vignette if the contribution is a pipeline based on other's work or if you've developed an original method. For example, this sentence is confusing and doesn't give me a good idea of what the package does.
```
"Despite the growing need to integrate network approaches, however, few practical bioinformatics tools are available to do so.  To address this disconnect, we developed a high-dimensional data analysis strategy and accompanying software that multiplexes isobaric mass tagged-based kinetics data for network analysis (XINA) with the aim to identify coregulated protein networks."
```
Please re-work the vignette to explain these issues:
- Main contribution
- What type of data are expected, e.g., what is "isobaric mass tagged-based kinetics data" and is everyone in proteomics familiar with this?
- Where would you normally get these data? In the package you simulate data but where would someone get this in a practical experiment?

2) Change LazyData = FALSE in DESCRIPTION. Setting this to TRUE results in a longer load time for the package.

3) Break up the code in R/xina.R into multiple files with related functions. This file is 2190 lines long and is difficult to navigate and understand.

4) Use an existing data container as input and output instead of data.frames and lists.

    The advantage of reusing a formalized class is that you can perform checks, write methods and re-use class accessors for free. Depending on how you want to store the "high-dimensional proteomics/trascriptomics kinetics data" you could use a class from Biobase, SummarizedExperiment::SummarizedExperiment or even one of the proteomics packages if that is appropriate.

Go to the biocViews page and enter the term 'proteomics' in the search box:

https://www.bioconductor.org/packages/release/BiocViews.html#___Software

Once you've decided on an input class, the example data saved in data/ should also be saved as this class (or converted once imported).

5) Clean up vignettes/

This directory should only contain the main vignette file and graphics files. Please remove all others.

6) The vignette should show how to load the package with BiocManager::install().

**Comment by langholee** [comment]
Dear @vobencha
Thank you for reviewing our package. I have inserted the new contents you requested. Please see below.

1.	What is the main contribution of the package?

Response: we have modified the vignette (below) to address your concerns. Regarding your 3rd point, we have uploaded as supplemental information (to the Journal of Proteome Research) the primary proteomics data used in the XINA manuscript (currently in revision for publication). In short, since this software will be published in a bioinformatics special edition of the Journal of Proteome Research, potential users will presumably have access to their own data, and will have access to our up-loaded published data. Currently, we have provided a smaller simulated data for the BioConductor package.
Updated vignette

“Quantitative proteomics experiments, using for instance isobaric tandem mass tagging approaches, are conducive to measuring changes in protein abundance over multiple time points in response to one or more conditions or stimulations. The aim of XINA is to determine which proteins exhibit similar patterns within and across experimental conditions, since proteins with co-abundance patterns may have common molecular functions. XINA imports multiple datasets, tags dataset in silico, and combines the data for subsequent subgrouping into multiple clusters. The result is a single output depicting the variation across all conditions. XINA, not only extracts co-abundance profiles within and across experiments, but also incorporates protein-protein interaction databases and integrative resources such as KEGG to infer interactors and molecular functions, respectively, and produces intuitive graphical outputs. 
Main contribution: an easy-to-use software for non-expert users of clustering and network analyses.
Data inputs: any type of quantitative proteomics data, label or label-free”

2.	Change LazyData = FALSE in DESCRIPTION. Setting this to TRUE results in a longer load time for the package.

Response: Changed

3.	Break up the code in R/xina.R into multiple files with related functions. This file is 2190 lines long and is difficult to navigate and understand.

Response: Partitioned into six segments

4.	Use an existing data container as input and output instead of data.frames and lists.
	
Response: Our manuscript and codes have undergone the peer review process, with invited revisions. This package is marketed for non-expert users of R, but do require basic knowledge. In order to make these changes, we would have to redesign XINA which is beyond the scope of its target user, and will not be done in time for the deadline resubmission of two weeks. Moreover, XINA has already been implemented in several academic collaborations in its current form.  Nevertheless, I searched several proteomics R packages, but none of them was good fit to XINA.  SummarizedExperiment is based on genomics data and MSnbase is not for multiplexed kinetics proteomics data.  I think data.frame and list are big advantage of R and familiar to most of R users.  I will consider data containers for potential update if we can find any appropriate one in Bioconductor.



5.	Clean up vignettes/

Response: Cleaned it.

6.	The vignette should show how to load the package with BiocManager::install().

Response: Added it.

**Comment by vobencha** [comment]
Thanks for making the changes. The package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/langholee.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"XINA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/XINA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
