### ISSUE TITLE
artMS

### ISSUE THREAD

**Issue by biodavidjm** [Bioconductor/Contributions#848]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biodavidjm/artMS

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
looks like you forgot to write a vignette?

**Comment by mtmorgan** [comment]
Will you be able to update your package or should we move this issue to inactive?

**Comment by biodavidjm** [comment]
Yes! please, check it out. The vignette is ready. 
I have also been very actively working on other issues of the package to make sure is solid enough (please, check [stats](https://github.com/biodavidjm/artMS/graphs/contributors) and to the lastest [commits](https://github.com/biodavidjm/artMS/commits/master) to find out more).

**Comment by LiNk-NY** [comment]
Hi David, @biodavidjm 
It looks like you still have errors. Could you bump the version for another build? Thanks.

**Comment by biodavidjm** [comment]
@LiNk-NY  Done! package absolutely free of warnings and errors both locally and on travis. Please, check it out (and if it fails, please, send me the log)

**Comment by LiNk-NY** [comment]
David, @biodavidjm it looks like the build is not being triggered. Did you make any changes to the webhook?

**Comment by biodavidjm** [comment]
Sorry @LiNk-NY  I have just added bioconductor to web hooks following [this guideline](https://github.com/Bioconductor/Contributions#adding-a-web-hook). it looks like it is working now

**Comment by biodavidjm** [comment]
Hi @LiNk-NY 

I have fixed the issue regarding the undefined objects. However, I have a problem with the runnable examples. Let me explain it. 

Even though I have provided examples for all the functions, I added the label `\donttest`.  This is due to the following reasons: 

1. `artMS` relies on very large input datasets (the smallest example that I have found is not less than 40MB)
2. Some of the functions take some time due to the complexity of the analysis (and using these large files), and I am afraid that compiling the package would take way longer than the allowed time.
3. Many of the functions generate quite a lot of output files that, if run as an example, could end up unseen somewhere in the system of the (unexperienced) users.

We are addressing a broad audience, mainly users with basic R knowledge who are going to be able to run a sophisticated analysis of Mass Spectrometry data (mostly proteomics) thanks to this package in a very easy way. 
My proposed solution is to make the vignettes as good as possible and provide in the vignettes examples of these large files through Bioconductor ExperimentData resource. Would that work? 

Any advice would be greatly appreciated! Thanks so much!

**Comment by LiNk-NY** [comment]
Hi David, @biodavidjm 

We rather not have 'donttest' or 'dontrun' examples because that usually creates stale
code in the long run. We prefer runnable examples for most of the functions.

Perhaps you can add a small dataset to the package under `inst/extdata` (raw files) or `data` (processed, exported, and documented data) to use for the examples. You may even want to generate data in a script under the `R` folder. 

For larger datasets, `ExperimentHub` is the better option. 

Keep in mind that there are time restrictions when checking the package. This factors in when using large datasets in the vignette. 

Regards,
Marcel

**Comment by biodavidjm** [comment]
Hi @LiNk-NY 

I've been working extensively addressing every error, warning, and note. 
The main issue is the **error**, which is about the percentage of runnable examples in the documentation. As it is detailed in [this issue](biodavidjm/artMS#37), I am very close to the 80%. Unfortunately, in order to provide an example to the remaining functions, I would need to have more 'data' available and I am very close to the limit (if it is not passed already). What is your advice?

With respect to the few remaining notes and warnings, any comment? They don't seem to be important, but I might be wrong.

Thank you very much!

**Comment by biodavidjm** [comment]
@LiNk-NY would you mind to take a look? any comment? is there anything else I need to do? The warnings don't seem to be important. Thanks so much!

**Comment by LiNk-NY** [comment]
Hi David, @biodavidjm 

Thank you for submitting to Bioconductor. 
I have had a look at your package.
Please see the review below and respond to the individual items.

Feel free to respond directly in this issue tracker if you have any questions.

Best regards,
Marcel

----
# artMS #848

## DESCRIPTION

* Please put all `db` packages in the `Suggests` field. These are optional
and not required to run the code in the package.

## NAMESPACE

* Remove 'artMS_' before your exported functions. It makes them unnecessarily
long. Bioconductor convention for names is 'camelCase' rather than 'snake_case'.

## R

* Make sure you are using the right tests. For example, when checking empty
arguments, you want to use `is.missing` for `any` of the files rather than
are `all` the files 'NULL' (`is.null`). 
* The `output_dir` could be the current working directory by default
(i.e., `"."`).
* Use class function tests like `is.numeric`, `is.logical`, etc. rather than
grepping the class name. 
* Use `match.arg` to show all the options in the argument and use the first by
default: `match.arg(c("a", "b", "c"), c("a", "b", "c"))`
* The `analysisQuantifications` function does too much. Your functions should
be modular. Impute data separately from the analysis and use that data as
input to the analysis function.
* Avoid saving 'PDF' or other files for the user. Provide only plotting, data
processing functions.
* The plotting function should be separate from the analysis one. This means
returning an object from the analysis function that could be fed the plotting
one.
* Use internal error messages instead of "dude, check the source code"
* Use "species" rather than `specie` for argument names.
* Create internal helper functions for repetitive code such as `grepl("_H1N1
... ` etc. It makes your code easier to maintain and less prone to errors.
* Remove superfluous exclamation points, interjections, and language
(e.g., "Oh no!!" and "Abort mission!").
* You could have used a `data.frame` map for the 'mapUniprot2entrezGeneName'
function. Is the function necessary?
* Make installation of `db` packages optional by using
`if (!requireNamespace("dbpackage")) stop(...)`
* Remove emoji and whimsical messages (e.g., 'Have a nice day! :)').
* Provide a `verbose = FALSE` argument in your functions. 
* Avoid using `cat` for diagnositic messages, use `message` and `warning`
functions.
instead. See: http://bioconductor.org/developers/how-to/coding-style/
* Why do you need so many global variables? 
* Code can be reduced when only single values change given a condition (e.g.,
`pvals <- if (select_pvalues == "adjpvalue") "adj.pvalue" else "pvalue"` then
use `results_msstats[, c(..., pvals, ...)]`)
* Avoid using all caps for errors, warnings, and messages in general.
* Being that this package has a lot of functionality, have you considered
separating functions into a group of packages?
* Shiny functionality should be in another package. 

## vignettes/

* Ensure that your formatting does not exeed 80 column widths. This is good
for reability and maintenance.
* Avoid using `BiocInstaller` for installing Bioconductor packages. Use
`BiocManager` in your code. 
* Include a `sessionInfo` chunk
* Consider having a quick start vignette and a full functionality vignette
included in your package.

## tests/

* Please include more tests, at least for your main function.

Minor: 
* Avoid using function names as variables in your code (e.g., `c`)
* `if (length(x) > 0)` is equivalent to `if (length(x))`

**Comment by biodavidjm** [comment]
Thank you very much Marcel, @LiNk-NY 

I am planning to implement all your suggestions. However, are all the suggestions mandatory? For example, I am not considering to create more packages (I want all these functions to be part of the same package).

And would you mind to clarify the following?

> DESCRIPTION
> Please put all db packages in the Suggests field. These are optional
> and not required to run the code in the package.

But there are some functions that require those db packages for annotations. Is still ok to move them to suggestions? (Yes, I admit that I don't understand perfectly well what "suggested" would imply, so I apologize in advance)

> NAMESPACE
> Remove 'artMS_' before your exported functions. It makes them unnecessarily
> long. Bioconductor convention for names is 'camelCase' rather than 'snake_case'.

I didn't know that camelCase was the convention (sorry, I probably missed it when reading the documentation). No problem at all. But, I would like to keep at least `artCamelCase` or `artmsCamelCase`. And I can try to make the function names shorter. The reason is that it is something that I have always liked to see for any function in any package: it would be way easier to remember and find functions of any package by start typing the name of the package and autocomplete with the tab key... 

> R
> Make sure you are using the right tests. For example, when checking empty
> arguments, you want to use `is.missing` for any of the files rather than
> are all the files 'NULL' (is.null).

After googling, does this mean that I need to install the package `splus2R`? R in my system does not come with that package by default

Thanks!

**Comment by LiNk-NY** [comment]
Hi David, @biodavidjm 

We encourage packages to have a central focus, i.e. analysis, visualization, annotation,
infrastructure, etc.
Moving the shiny code into another package allows the current package to have a clearer focus.

> But there are some functions that require those db packages for annotations. Is still ok to move them to suggestions? (Yes, I admit that I don't understand perfectly well what "suggested" would imply, so I apologize in advance)

Yes, move them to `Suggests`. Otherwise, the user is required to install all of those packages
that they may not need.
Your `artms_mapUniprot2entrezGeneName` function should be using a `data.frame` map that has two columns: common name and the annotation abbreviation (e.g., "Anopheles", "Ag"). Then you can use this along with `if (!requireNamespace(<annotationPackage>))` then `stop("Install <annotationPackage> to map IDs")` to get the user to have the package already installed before using your function. It would
also reduce the repetitive code. 

> I didn't know that camelCase was the convention (sorry, I probably missed it when reading the documentation). No problem at all. But, I would like to keep at least artCamelCase or artmsCamelCase. And I can try to make the function names shorter. The reason is that it is something that I have always liked to see for any function in any package: it would be way easier to remember and find functions of any package by start typing the name of the package and autocomplete with the tab key...

This is not convention and any user wanting a list of functions available in your package
could just do `help(package = "artMS")` instead. 

> After googling, does this mean that I need to install the package splus2R? R in my system does not come with that package by default

Apologies if it wasn't clear. I meant that your `if` statement should be more like
`any(is.missing("datafilearg"), is.missing("textfilearg"))` instead of testing with `all(is.null(...), is.null(...))`.
The logic in these tests is slightly different and perhaps you don't want any of the file
arguments to be missing rather than the instance where all of them are missing.

**Comment by lshep** [comment]
Please ignore the above build report - there was an ERROR on our system - I am rerunning the package for you now

**Comment by lshep** [comment]
Please ignore the above build report - there was an ERROR on our system - I am rerunning the package for you now

**Comment by biodavidjm** [comment]
Hi Marcel @LiNk-NY 

it makes sense and I have modified the code to incorporate all your latest suggestions. Please, take a look. Is there anything else that I need to do?

Thanks a lot!
David

**Comment by biodavidjm** [comment]
Hi Marcel @LiNk-NY 

I have addressed your last two suggestions. It looks like this is ready to go!! 
Please let me know if there is anything else I can do.

> Hi David, @biodavidjm
> 
> Please remove packages that you don't need from the `Suggests` field such as
> the `org.*db` packages.
> 
> Also, make the default behavior to _not_ save PDF files in the user's directory.
> Otherwise, this would save a bunch of files in the build system when checking the package.
> 
> Almost there!
> Thanks,
> Marcel

**Comment by LiNk-NY** [comment]
Hi David, @biodavidjm 

Thank you for making those changes. 
I will accept your package on the condition that you will continue to improve the
plotting functions. 

As an example, please see this function as reference on how to write plotting functions
without saving a number of pdf files: 
https://github.com/markrobinsonuzh/treeAGG/blob/master/R/treePlot.R

Best regards,
Marcel

**Comment by biodavidjm** [comment]
Thanks Marcel @LiNk-NY 

absolutely! you have my full commitment to improve it, but also other issues, as adding way more tests and create more vignettes.

Thanks to your very constructive revisions, you have definitely made artMS a way better package. Thanks a lot!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/biodavidjm.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"artMS\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/artMS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
