### ISSUE TITLE
glmSparseNet

### ISSUE THREAD

**Issue by averissimo** [Bioconductor/Contributions#849]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sysbiomed/glmSparseNet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by averissimo** [comment]
Can you advise on the warnings I'm getting @LiNk-NY 

The warnings in the package are from two sources:

* Exceed 5 minute check
* Having to rebuild one of the files in inst/doc

**Exceed 5 minute check**

I believe the source of this are the vignette building, as it retrieves and processes data from another BioC package it can take some time.

I can either/both:

* reduce the number of vignettes being built
* use a data file to store a cache to speed up the vignette building

**Having to rebuild one of the files in inst/doc**

This is the warning and I have no idea on how to solve this, I could not find any solution when searching online.

```
* creating vignettes ... OK
Warning: inst/doc file
    example_brca_survival_ppi.R
  ignored as vignettes have been rebuilt.

```

**Comment by LiNk-NY** [comment]
Hi André, @averissimo 
Apologies for the delay. I will get to your package soon. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi André, @averissimo 
Thank you for your submission. The review can be seen below.
Please respond to individual bullet points of the review. 

If you have any questions, please feel free to reach out. 

Best regards,
Marcel

---

# glmSparseNet #849

## DESCRIPTION

* Looks good overall.
* Why do you need `devtools` and `roxygen` in the `Suggests` field?

## NAMESPACE

* Avoid using `.` dot delimiters in function names such as
`build.string.network` unless you're creating S3 methods. The Bioconductor
convention is to use `camelCase`

## vignettes/

* It looks like you incorrectly reference `TCGAbiolinks` rather than
`curatedTCGAData` in the vignettes
* Your code can use helper functions in `TCGAutils` that allow you to separate
assays by sample type code (referring to tumors, normals, etc.)
* "metastatic" samples (code 11) actually refer to 'Solid Tissue Normal', see
`data(sampleTypes)` in `TCGAutils`
* You should use functions like `TCGAbarcode`, `splitAssays`,
`intersectColumns`, `as(X, "MatchedAssayExperiment")` etc.
* Your vignette code could probably be reduced to a few lines for the first
part of the vignette (the 'data.show' chunk)

## R/

* Don't create methods for regular classes such as `matrix`. Please create a
regular function and have checks in place so that it only works for certain
classes (in this case `matrix`)
* You don't need to create a generic if you're only going to set a method for
a single class (see `degree.sparsebn`)
* See bullet under `NAMESPACE` with regards to the dots `.` in functions
* Ensure that your code is readable by limiting line widths to less than 80
columns
* Consider using the data structure as your first argument for functions like
`degree.generic` and similar. You may also want to have a default function for
the `fun` argument
* Consider using `BiocParallel` for parallel computations
* Avoid using `seq(1, X)` use `seq_len(X)` for robustness
* Remove any code that is commented out or provide a working version of it.
* Consider including a script that generated the dataset documented in `data.R`
* You shouldn't have to create so many methods for the different class
combinations, just create one regular function and have a filtering step
that will account for the different inputs.
* Look into a replacement for `biocmaRt`. I'm not sure what package is
recommended here.
* You should only create methods for classes that you create and not external
classes (e.g., `SummarizedExperiment` and `MultiAssayExperiment`)
* If you need a function to work for a particular class, check class membership
as part of the function
* Consider using `switch` for `calc.penalty` options rather than a series of
calls

## README.md

* Replace all `source` and `biocLite` calls with `BiocManager`. See the devel
landing pages of any package on the Bioconductor website for examples or
check the Bioc-devel mailing list.

**Comment by averissimo** [comment]
Thanks for the feedback Marcel, I'll work on these and reply as soon as possible.

**Comment by averissimo** [comment]
> Hi André, @averissimo
> Thank you for your submission. The review can be seen below.
> Please respond to individual bullet points of the review.
> 
> If you have any questions, please feel free to reach out.
> 
> Best regards,
> Marcel
> # glmSparseNet #849
> ## DESCRIPTION
> 
>     * Looks good overall.
> 
>     * Why do you need `devtools` and `roxygen` in the `Suggests` field?

**I don't and they have been removed**, at one point I might had some problem in travis CI

> 
> 
> ## NAMESPACE
> 
>     * Avoid using `.` dot delimiters in function names such as
>       `build.string.network` unless you're creating S3 methods. The Bioconductor
>       convention is to use `camelCase`

**Done! camelCase it is** I also renamed non-exported methods to have '.' prefix

> 
> 
> ## vignettes/
> 
>     * It looks like you incorrectly reference `TCGAbiolinks` rather than
>       `curatedTCGAData` in the vignettes

**Corrected, nice eye!**

> 
>     * Your code can use helper functions in `TCGAutils` that allow you to separate
>       assays by sample type code (referring to tumors, normals, etc.)

**Converted code to use TCGAutils**, very nice package that I did not know about

> 
>     * "metastatic" samples (code 11) actually refer to 'Solid Tissue Normal', see
>       `data(sampleTypes)` in `TCGAutils`

**Copy/paste mistake** thanks

> 
>     * You should use functions like `TCGAbarcode`, `splitAssays`,
>       `intersectColumns`, `as(X, "MatchedAssayExperiment")` etc.

**Done that**, I could not find an already implemented function that removed clinical cases that were not in a specific assay, so I kept my 'reduceByExperiment' function with slight improvements

> 
>     * Your vignette code could probably be reduced to a few lines for the first
>       part of the vignette (the 'data.show' chunk)

**Yes!!** although not for the survival case, that required additional processing

> 
> 
> ## R/
> 
>     * Don't create methods for regular classes such as `matrix`. Please create a
>       regular function and have checks in place so that it only works for certain
>       classes (in this case `matrix`)

**Removed all methods from package as per your advice**

> 
>     * You don't need to create a generic if you're only going to set a method for
>       a single class (see `degree.sparsebn`)

**Done**

> 
>     * See bullet under `NAMESPACE` with regards to the dots `.` in functions

**Done!!, see response in NAMESPACE**

> 
>     * Ensure that your code is readable by limiting line widths to less than 80
>       columns

**Done!** Not a single one! also converted to 4 space indentation, with some exceptions such as function arguments definition so they are indented with first argument

```
exampleFun <- function(arg1,
                                            arg2,
                                            ...) {
```

Could not find if this is good practice, or should I continue to use 4 space for `arg1` and `...`

> 
>     * Consider using the data structure as your first argument for functions like
>       `degree.generic` and similar. You may also want to have a default function for
>       the `fun` argument

**added default fun argument, but not a structure**

> 
>     * Consider using `BiocParallel` for parallel computations

**On my tests mclapply was faster than `BiocParallel` so I went with that one**. I'll consider switching on a future version, especially if iterating over Bioc data structures

> 
>     * Avoid using `seq(1, X)` use `seq_len(X)` for robustness

**I believe all seq(1, X) was already converted to seq_len(X)**

> 
>     * Remove any code that is commented out or provide a working version of it.
> 
>     * Consider including a script that generated the dataset documented in `data.R`

**Done!** data.R was moved to a publication-specific package that will not be submitted to Bioc

> 
>     * You shouldn't have to create so many methods for the different class
>       combinations, just create one regular function and have a filtering step
>       that will account for the different inputs.

**My basis for doing this was flawed and used the filtering step**, thanks!
> 
>     * Look into a replacement for `biocmaRt`. I'm not sure what package is
>       recommended here.

**Is there a problem for having `biomaRt`?** I depend on this to get conversions between geneIds and geneNames

> 
>     * You should only create methods for classes that you create and not external
>       classes (e.g., `SummarizedExperiment` and `MultiAssayExperiment`)

**Done!!** removed all methods as they did not make sense

> 
>     * If you need a function to work for a particular class, check class membership
>       as part of the function

**Done, see above**

> 
>     * Consider using `switch` for `calc.penalty` options rather than a series of
>       calls

**Done!**

> 
> 
> ## README.md
> 
>     * Replace all `source` and `biocLite` calls with `BiocManager`. See the devel
>       landing pages of any package on the Bioconductor website for examples or
>       check the Bioc-devel mailing list.

**Done!**

Again thanks for the feedback, I felt it greatly improved the package implementation.

**Comment by averissimo** [comment]
Note: I kept the 'cv.glmSparseNet`, `cv.glmHub`, etc.. to keep up with `glmnet` cross-validation functions name that has that prefix with '.'

**Comment by averissimo** [comment]
There was 3 functions that I missed with dot in their name. Response above now fully applies

**Comment by LiNk-NY** [comment]
Hi André, @averissimo 
Thank you for making those changes. I will check your package shortly.
-Marcel

**Comment by LiNk-NY** [comment]
Hi André, @averissimo 

A few points to consider:

* Only use `cat` for class show methods, otherwise use `message` or `warning` functions. See: http://bioconductor.org/developers/how-to/coding-style/
* Use the proper extractor functions for `MultiAssayExperiment` such as `sampleMap(multiassay)`
* Why not use `MatchedAssayExperiment` instead of `reduceByExperiment`? You can subset first and then convert to the class:  `as(multiassay[, , "experiment1"], "MatchedAssayExperiment")`

Thanks.

**Comment by averissimo** [comment]
Hi Marcel ( @LiNk-NY )

I've implemented those changes.

* `cat`, replaced with appropriate message/stop
* `sampleMap(..)` code was removed in next bullet actions, so no action here
* `as(..., 'MatchedExperimentAssay)` -- exactly what was necessary, sorry that you had to repeat yourself, I'm still familiarizing with Bioc data structures and auxiliary functions.

**Comment by LiNk-NY** [comment]
Hi André, @averissimo 
A couple of notes: 
* `biomaRt` has been unreliable in the past. If there are alternatives, I would certainly seek them out.
* Indentation for functions with many arguments varies by author. I tend to prefer something like this if it doesn't fit in one line:
```
exampleFun <- 
    function(arg1, arg2, ...)
{
}
```
but I will leave this up to you. 
Thanks.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/averissimo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"glmSparseNet\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/glmSparseNet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
