### ISSUE TITLE
IWTomics

### ISSUE THREAD

**Issue by marziacremona** [Bioconductor/Contributions#85]
- Repository: https://github.com/marziacremona/IWTomics
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

**Comment by marziacremona** [comment]
I checked the build report and the error was because I forgot to subscribe to the bioc-devel mailing list. 
Now I'm subscribed, so the error should disappear.

**Comment by lshep** [comment]
The ERROR for BUILD BIN is on our end.  I am working on fixing this now.  In the meantime please considering fixing the other WARNINGS, NOTES, and RECOMMENDED on the build report.

**Comment by marziacremona** [comment]
The WARNING
Warning: replacing previous import 'fda::matplot' by 'graphics::matplot' when loading 'IWTomics'
is due to the imported package fda, so I cannot do anything about it.

I don't understand the following NOTE, since subsetByOverlaps is a method from GenomicRanges package that is imported
getFeatures : <anonymous> : <anonymous>: no visible global function
  definition for 'subsetByOverlaps'
getFeatures : <anonymous>: no visible global function definition for
  'subsetByOverlaps'
Undefined global functions or variables:
  subsetByOverlaps

**Comment by lshep** [comment]
You could get rid of the WARNING by selectively importing functions from fda rather than the entire package.  

subsetByOverlaps is actually not in GenomicRanges but works on GenomicRanges.  I believe the function is in the IRanges package.  Please importMethodsFrom(IRanges, subsetByOverlaps) in the NAMESPACE

**Comment by marziacremona** [comment]
I found a small bug with parallel computation in one function, so I fixed it.

**Comment by lshep** [comment]
Thank you for you submission.  

Some general comments: 

It seems like your code could be organized a little better.  I suggest one of two options: 

1. Condense the code down and have getRegions.R and getFeatures.R be helper functions.  Your main function, IWTomics.test should take in as argument a GRanges or GRangesList.  (This also helps connect it to other Bioconductor functions). There really doesn't seem much of a need to create your own classes to use as arguments for your function, you could call them from within your main function to format the data as you need (adjusting the main function arguments as necessary); This takes the burden off the user to have to go through multiple steps to use your function

2. If you would like to keep your classes visible and accessible to the user then these really should be switched to S4 methods instead of S3 methods.  The would involve creating a class, constructor and getter/setter methods.  

Other general notes: 

1. Function calls should avoid using  "."  as part of the name and instead use camel case.  (ie.  IWTomics.test ,   IWTomicsTest) The dot "." is used for S3 method dispatch and can be confusing to novice users.    

2. regardless of the above reorganization options, it seems like there should be some accessor/getter methods created for the user so that some of the more common results of your function are easily accessible (ie.  a function to return the pvalues instead of having the user have to manual use something like result1$IWT[[1]]$ftr1$adjusted_pval ) 

3.  Thank you for including runnable examples.  To be consistent we prefer to have this data included in a directory inst/extdata instead of your inst/examples 

4.  You can remove from the NAMESPACE importMethodsFrom(S4Vectors,as.matrix) as you have already fully imported the package in the line above import(GenomicRanges, S4Vectors, parallel, gtable, grid, graphics)

5.  In your R code, if you properly set the imports in DESCRIPTION and NAMESPACE files, you should not need to specify "::"  in any R code as the libraries/functions will be available for use directly.    
(i.e      s = apply(x, 1, stats::sd, na.rm = TRUE)   can be   s = apply(x, 1, sd, na.rm = TRUE)  ) 


Thank you 

Lori

**Comment by marziacremona** [comment]
Dear Lori, 

thank you very much for your comments and suggestions that improved our package, and sorry for the delay in the answer. 
Here below you find your comments and the point-to-point responses. 

> It seems like your code could be organized a little better. I suggest one of two options: 
> 1.	Condense the code down and have getRegions.R and getFeatures.R be helper functions. Your main function, IWTomics.test should take in as argument a GRanges or GRangesList. (This also helps connect it to other Bioconductor functions). There really doesn't seem much of a need to create your own classes to use as arguments for your function, you could call them from within your main function to format the data as you need (adjusting the main function arguments as necessary); This takes the burden off the user to have to go through multiple steps to use your function
> 2.	If you would like to keep your classes visible and accessible to the user then these really should be switched to S4 methods instead of S3 methods. The would involve creating a class, constructor and getter/setter methods. 

We decided to switch to S4 classes and methods because we think it is important that the user can directly access them, and the organization of the data and of the test results is more clear. We also re-implemented the package so that it is simpler and better organized. 
In particular, we condensed the old S3 classes “IWTomicsRegions”, “IWTomicsRegionsFeatures” and “IWTomicsTest” in a single new S4 class called “IWTomicsData”, with an optional slot “test”. 
We created many accessors, a “show” method, a subset method “[” to extract specific region datasets and/or feature datasets, and different combine methods (“c”, “merge”, “cbind” and “rbind”) that substitute the old S3 method “merge”. 
The new S4 class “IWTomicsData” has two constructor methods. The first one substitutes the old S3 constructor method, while the second one combines the two old function getRegions and getFeatures (so that the user only need to specify the names of the files with the regions and features). 
The optional slot “test” is filled by the function IWTomicsTest that performs the test. 
We also added a small real data example to the package and to the vignette, in order to have a more user-friendly package. 

> Other general notes: 
> 1.	Function calls should avoid using "." as part of the name and instead use camel case. (ie. IWTomics.test , IWTomicsTest) The dot "." is used for S3 method dispatch and can be confusing to novice users. 

We fixed this problem.

> 2.	regardless of the above reorganization options, it seems like there should be some accessor/getter methods created for the user so that some of the more common results of your function are easily accessible (ie. a function to return the pvalues instead of having the user have to manual use something like result1$IWT[[1]]$ftr1$adjusted_pval ) 

We added multiple accessor methods for the new S4 class “IWTomicsData”, among which the function adjusted_pval that returns the pvalues for all the tests performed.

> 3.	Thank you for including runnable examples. To be consistent we prefer to have this data included in a directory inst/extdata instead of your inst/examples 

We modified the directory to inst/extdata.

> 4.	You can remove from the NAMESPACE importMethodsFrom(S4Vectors,as.matrix) as you have already fully imported the package in the line above import(GenomicRanges, S4Vectors, parallel, gtable, grid, graphics)

We removed import(S$Vectors), and we are now importing only the methods needed importMethodsFrom(S4Vectors,as.matrix,isEmpty).

> 5.	In your R code, if you properly set the imports in DESCRIPTION and NAMESPACE files, you should not need to specify "::" in any R code as the libraries/functions will be available for use directly.
> (i.e s = apply(x, 1, stats::sd, na.rm = TRUE) can be s = apply(x, 1, sd, na.rm = TRUE) ) 

Now the code does not specify “::” anymore.

**Comment by lshep** [comment]
Thank you for your work and your recent updates to your package. It is much
cleaner and better organized.  We are still slightly concerned with the lack of
integration with a standard bioconductor structure as we like to foster
interconnectiveity to other bioconductor packages rather than inventing new
classes. Have you looked at MultiAssayExperiment for use instead of/or that you
could build your classes as an extension of? We are trying to streamline
containers for omics data and there are substantial resources behind and support
available for MultiAssayExperiment. If this is not suitable please provide a
justification so we may better understand; also you mention the use of
GRanges/GRangesList as the main input, which may be useful as recommended,
but without any example is somewhat unclear. 

Also please fix the WARNINGS that are appearing in the recent build report.

**Comment by marziacremona** [comment]
We understand your concern, but we do not think that MultiAssayExperiment is suitable for our package. 
As far as we understand, the MultiAssayExperiment class can be used to manage diverse assays on a collection of samples related to different biological units (different patients, plants etc, possibly with a description of their phenotype). Each biological unit is associated to one or multiple assays. Our package does not deal with different biological units. Our class IWTomicsData stores information about different groups of genomic regions. Each of these groups is associated to one or multiple features, but each feature correspond to a single assay, i.e. the assay is the same for all the groups of regions. For example, we can have two groups of genomic regions: a group of 100 regions surrounding ERVs (call it “Elements”), and a group of 100 regions without ERVs (call it “Control”). In each of the 200 regions we have measurements of two different features: “Recombination hotspots” and “DNase I hypersensitive sites”. We have a single experiment for “Recombination hotspots” and the feature is measured on the whole genome at the same time, but we store only the information in the regions correspondent to the 100 “Elements” and the 100 “Controls”. Similarly, we have a single assay for “DNase I hypersensitive sites” (a single DNse-seq experiment) on the whole genome, and we store only the measurements in the 200 regions of interest. We think that the type of data collection used by our package is quite different from the one provided by MultiAssayExperiment class, both from a biological point of view and a bioinformatics point of view, and it could be confusing for the user try to fit our type of data collection inside the MultiAssayExperiment object. 

Moreover, an additional issue is that in our package each feature in each region correspond to a curve (a vector of measurements) and not to a single number. To the best of our knowledge, in Bioconductor there is no class made specifically for this type of data. The package MMDiff2 deals with a type of data similar to the one that we are using. In particular, it considers different regions on the genome defined by ChIP-seq peaks. Similarly to our package, MMDiff2 associates a curve (histogram) to each of these regions. Differently from our package, MMDiff2 considers groups of features instead that groups of regions, and it can deal only with ChIP-seq experiments. MMDiff2 uses a custom class (DBAmmd class) to store data. 

Our class IWTomicsData is an extension of GRangesList, meaning that a very important slot in our class (“regions” slot) is a GRangesList that contains the different groups of regions. Anyway, we do not think that GRangesList is flexible enough to store all the data that our main functions need. Indeed, IWTomicsData contains also to slot “features” with all the curves corresponding to each region and each feature. Importantly, these curves are aligned by the class constructor (and stored in lists of matrices). The alignment step can be time consuming, so we run it only once when we create the object. In addition, the class GRangesList has a slot “test” where we store the test results. We think it is very convenient to organize both the data and the results together in the same class, because in this way everything is more clear. 

All the WARNINGS are now fixed.

**Comment by lshep** [comment]
Thank you.  That was very helpful.  I do believe it is okay.   A few minor details to clean: 

- [ ] Please remove the pdf from the vignettes directory 
- [ ] Please use the metadata() generic from S4Vectors and not define your own. (also update the NAMESPACE accordingly.  

Once these are complete, I believe the package is ready for acceptance.

**Comment by lshep** [comment]
Please ignore the ERROR that the windows (tokay2) machine is generating.  The texipdf ERROR is a problem on our system.  Please let me know when you are finished with your updates.

**Comment by marziacremona** [comment]
I did all the updates you suggested!
Thank you!

**Comment by lshep** [comment]
Thank you for your efforts.  I will mark your package as accepted.  Please leave the issue open until you received svn instructions for upload to Bioconductor via email.  It may take a few days to receive your svn instructions.
