### ISSUE TITLE
plotGrouper

### ISSUE THREAD

**Issue by jdgagnon** [Bioconductor/Contributions#852]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jdgagnon/plotGrouper

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
The title doesn't provide any indication of what this package is for!

**Comment by jdgagnon** [comment]
Hi @Liubuntu I have *finally* gotten my package free of errors and warnings. Is there anything else I need to do or is this now the start of the review process?
Thanks!
John

**Comment by Liubuntu** [comment]
Hi @jdgagnon , 

Yes, I'll look at your package for a technical review. In the meantime, can you look at also the NOTE messages in the building report, from both Check and BiocCheck? Some will go to the technical review anyway, for example, we encourage adding NEWS file, unit test, runnable examples. Also replacing the `sapply` with `vapply` for a robust coding. Let me know for any question.  

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @jdgagnon , 

Seems that you have figured out a workaround to remove the note message about the `no visible binding...`. This is actually a false positive since people are using `dplyr` or `ggplot` in their own package development. And Currently Bioconductor does not have a clear guideline about using the piping languages (which is actually not encouraged for software development). So this could be ignored for now. 

A technical review is under process and will be posted soon. Thanks!

Qian

**Comment by Liubuntu** [comment]
Hi @jdgagnon , 

Here is the technical review for your package. Please seek to address all issues and comment back when you are ready for the 2nd look. Thanks!

## DESCRIPTION

- Use a specific license version. e.g., `License: GPL-3`.
- Seems that the FlowCytometry is not a proper biocViews for this package...
- In addition to the bug report, please add the relevant links to the GitHub repository.

## NAMESPACE
- Looks good.

## man
- Looks good.

## R

- Don't check logical values twice. use `if (angle.x)` instead of `if (angle.x == TRUE)`. Similarly, use `if (sci)` instead of `if (isTRUE(sci))`. Check your other scripts for similar instances.

- Remove commented lines from R scripts.

## vignette

1. For the first section of `Installation`, use the following code.
- The `BiocManager` is up to replace the `BiocInstaller` in the development version now, and after the next release in the end of Oct, `BiocInstaller` will be removed from Bioconductor. So all new packages are required to use `BiocManager` for the installation.
- Install the package as if it is already included in Bioconductor. Mention the installation from github for most recent version if you deem necessary.

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
   install.packages("BiocManager")
   BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```

2. Please add a table of contents for better organization. This could be easily specified in the header. check here: https://rmarkdown.rstudio.com/html_document_format.html.

3. Please add in the end of the vignette a section of `SessionInfo` for your vignette running environment.

4. The shiny app could also be opened through R session within terminal / emacs. So seems that the `Rstudio` is not necessarily a prerequisite here?

5. In explaning the `Unique identifier`, `Comparisons` and `Variables`, could you use the corresponding column name in `iris` data as an example?

6. Could you also add introduction about the `Statistics` and `Report`? For the `iris` examples, I couldn't see how to export the report, because it shows "Nothing added to report yet." Can you explain how to add results into report? And how to save the plot itself for publication?

7. What does `Lock` mean? Is it intended to fix all setting for exporting?

## OTHER
- Multiple typos in the function documentation. Please run a spell checker for those. 

Cheers,
Qian

**Comment by jdgagnon** [comment]
Hi @Liubuntu ,

I have made the changes you recommended. The only thing I have not done yet is remove commented lines from R scripts. Is this necessary? I find them helpful for organizing my code and making it easier to find sections that I want to work on.

Thanks!
John

**Comment by Liubuntu** [comment]
Hi @jdgagnon , 

That's fine for the commented note messages. I was talking about the unused code inside the scripts. Please remove them if you have any. I'll look at the updates soon and let you updated. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @jdgagnon , 

Thanks for the updates! There is a few additional. Thanks. 

## DESCRIPTION
- Your package is a "shiny app GUI wrapper for ggplot", so it does not
  aimed for data that are generated from a specific experiment /
  technology. So are you sure that the `flowCytometry` is a proper
  `biocViews` term here?

## vignette

- For the last section of `sessionInfo`, just include the code chunk
  using `{r} sessionInfo()`, it will print results in the vignette.

- Start the toc with 1 not 0.1 (move "##" into "#" for section names).

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @jdgagnon , 

The flowCytometry now sounds acceptable to me. So that people with this kind of data could see this package after searching Bioconductor, if that's your original intention? 

The other updates looks fine with me. Will accept the package now. 

Cheers,
Qian

**Comment by jdgagnon** [comment]
Thanks @Liubuntu ,

Yes, I think being able to find the package when searching for flow cytometry would be beneficial. 

So what are the next steps? Will changes made to the GitHub master continue to get pushed to the Bioconductor Git repository? How long does it generally take to become available for installation via Bioconductor?

Thanks for your help!
John

**Comment by Liubuntu** [comment]
Instructions for maintaining your package will be posted soon. 

Basically, once the package was accepted and included in Bioconductor (might take several days since it requires manual steps for addition and extra checking by Martin), it will be available to download from Bioconductor devel (Bioc 3.8 for now).

The github master branch is treated as the devel branch of your package. Make sure to have the git@git.bioconductor.org:packages/pkgname in the remote. And make changes in local master branch, then: 
$ git push origin master
$ git push upstream master
 
After the next release cycle (end of Oct.), you package will be available for both release and devel. [Here](http://bioconductor.org/developers/how-to/git/bug-fix-in-release-and-devel/) is some extra information for maintaining or fixing bugs.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jdgagnon.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"plotGrouper\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/plotGrouper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
