### ISSUE TITLE
HiCBricks

### ISSUE THREAD

**Issue by carmencita** [Bioconductor/Contributions#856]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/koustav-pal/HiCBricks

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by carmencita** [comment]
Hi all,
we were just wondering if you are waiting for some action from our side to continue with the review of the HiCLegos package? Thanks

**Comment by dvantwisk** [comment]
No more action is required on your end, we hope to have a review of your package in the coming days.

**Comment by dvantwisk** [comment]
Here is a review of your package. It looks very well written and I only have a few issues. [REQUIRED] tags indicate issues that must be changed or responded to. [CONSIDER] tags are changes that are advisable but not necessary. Please comment back when you are finished with your changes.

R/GENERAL:
- [REQUIRED] Use `message()` instead of `cat()` to display diagnostic messages
to users. The is preferable as messages can be toggled off.
- [CONSIDER] Use `match.arg()` in function statements. For example in
`Lego_functions.R:L163`, the argument `exec` can take three inputs. This can
be written as `exec=c('cat', 'bz2', 'bzcat')` in the function header. The
default value is the first value (`cat`). The value can then be extracted with
`exec <- match.arg(exec)`. Doing this is preferrable as it makes it more clear
to the user what the accepted arguments are. This can be done in multiple places
throughout the package.

DESCRIPTION
- [CONSIDER] The `lazyData: true` tag is rarely useful and tends to slow down
installation. Consider removing it.

R/Lego_functions.R
- [REQUIRED] `CreateLego()` creates HDF5 files in the current directory if no
path is given in the `Output.Filename` argument. This may clutter the working
directory and it would be better to have the files saved to a temporary file
(or directory) using `tempfile()` (or `tempdir()`).

man
- [CONSIDER] Have a man page for your package so that a user can do a ?HiCLegos
that gives an overview and directs to main functions of the package and/or
package vignette.

tests
- [CONSIDER] Adding unit tests to your package using the `testthat` package.

vignettes
- [REQUIRED] Change the name of the vignette to something useful not just
"vignette.R". We woudl recommend the package name.
- [REQUIRED] Remove `Stangle`'d `Vignette.R` file.
- [REQUIRED] The final examples in the vignettes are labeled `eval=FALSE`.
These sections seem to be plotting related. Is there a reason why they can't be
run? We generally don't allow packages to have `eval=FALSE`'s since users are
meant to be able to run the code and this should be checked at build time.

**Comment by dvantwisk** [comment]
It looks like you've been making commits. Could you perform a version bump so our that our build system will rebuild your package?

**Comment by koustav-pal** [comment]
Hi Daniel, 

R/GENERAL:
- cat() has been substituted with message()

DESCRIPTION
-"lazyData: true" has been removed

man
- a man page has been added for ?HiCLegos

tests
[CONSIDER] Adding unit tests to your package using the testthat package.

vignettes
- vignette name changed from "vignette.Rnw" to HiCLegos-Vignette.Rnw
- Stangle'd Vignette.R remvoed
- removed "eval= FALSE" where possible

Regarding this issue,

> [REQUIRED] CreateLego() creates HDF5 files in the current directory if no
> path is given in the Output.Filename argument. This may clutter the working
> directory and it would be better to have the files saved to a temporary file
> (or directory) using tempfile() (or tempdir()).

The idea behind this package is to create a HDF file for storing high-resolution Hi-C (can be as large as a user wants) data and keep it as a persistent copy which the user can access later without having to reload the file. Therefore, I am a bit averse towards creating a tempfile or tempdir. Using a temporary file would go against this idea and would probably result in the user not having access to the file later. I have incorporated a control statement which will issue a warning regarding file creation inside the current working directory. **Is that ok**? 

For the consider comments, we already have plans for future releases where we will follow up with most of them. Especially, this one

> [CONSIDER] Adding unit tests to your package using the testthat package.

Towards the other comment,

> - [CONSIDER] Use match.arg() in function statements. For example in
> Lego_functions.R:L163, the argument exec can take three inputs. This can
> be written as exec=c('cat', 'bz2', 'bzcat') in the function header. The
> default value is the first value (cat). The value can then be extracted with
> exec <- match.arg(exec). Doing this is preferrable as it makes it more clear
> to the user what the accepted arguments are. This can be done in multiple places
> throughout the package.

I will do so in a future release, but at least for this specific case I would not do so as exec is concatenated with the input file and passed on to `data.table::fread`. So, users are free to construct even `awk` one liners and pass these on such as awk \'{for(i = 4; i<= NF; i++){printf "% ", $i}print ""}\'. Using `match.arg` would force the users to use any one of the predefined commands. 

I will incorporate this change into other functions after reviewing all such cases. But I wish to keep this for a future release which will contain a lot of code cleanup and further modularization.

**Comment by dvantwisk** [comment]
The changes so far look good. I understand that `tempfile()` isn't a great solution for your package, so may I recommend that you store your data using the BiocFileCache package https://bioconductor.org/packages/release/bioc/html/BiocFileCache.html as opposed to automatically saving the file in a local directory. Once this change is made, I should be able to accept the package.

**Comment by koustav-pal** [comment]
Hi,

I have made the suggested change and integrated the Bioc File cache package. All files are now tracked through bfc. 

I ran into some trouble yesterday. 

- I pushed some changes to the package and committed a version bump. But the issue bot did not recognize it. I tried this three times. 
Later (today morning), I made some changes to documentation and pushed those. Now the issue bot recognised the change and started a build. 

It has been three hours and I still have not received a build report. 

Please advise on the steps that I should take or is there a problem with the build machine?

**Comment by dvantwisk** [comment]
It looks like the package is building fine and aside from that the BiocFileCache changes look very good. It seems there are a few errors on the windows builder to be solved.

**Comment by koustav-pal** [comment]
The Bioc File Cache integration has been successfully added. The package is now ready for acceptance. Although, we would like to change the package name before it is accepted.

**Comment by dvantwisk** [comment]
As long as no new build reports need to be made, you just need to update the name within the package, your github page, the name of this issue, and the link to your newly named package in this issue.

**Comment by koustav-pal** [comment]
We made the changes and additional changes to the codebase which involved renaming functions and updating the rd files. Later, in these steps, we, changed the name of the function on our side, changed the package name and updated the issue. Later, we updated the webhook and pushed a version bump.

This was not accepted. 

So we deleted the webhook, and created a new one. When we did this, another version bump sent back the following response

Sorry, you haven't told us about this repository, please


Please advise on what steps we should take to reactivate the webhook.

**Comment by dvantwisk** [comment]
Since you've changed the name of the package, it isn't no longer going to be able to build as it did before. As long as the extra change you made to your package was very minor, it shouldn't be an issue. We should be able to accept your package now if you are ready.

**Comment by koustav-pal** [comment]
Great. We are ready for release.

**Comment by dvantwisk** [comment]
Alright, I'm moving to accept the package now. Just be sure to keep an eye on the build reports for your package once it has propagated.

**Comment by dvantwisk** [comment]
It should be fine.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/koustav-pal.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"HiCBricks\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HiCBricks

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
