### ISSUE TITLE
AffiXcan

### ISSUE THREAD

**Issue by alussana** [Bioconductor/Contributions#860]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/alussana/AffiXcan

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
vobencha will review your package; please consider updating your DESCRIPTION Title: so that the user does not need to know what 'GReX' is an abbreviation for. Consider also using BiocParallel rather than doMC for  parallel evaluation, for greater interoperability with Bioconductor packages.

**Comment by alussana** [comment]
Right now it is not clear to me whether BiocParallel registered back-ends can be used along with plyr functions. In addition to other minor corrections, I replaced doMC with doParallel, as an at least temporarily solution.

**Comment by alussana** [comment]
Now AffiXcan uses BiocParallel instead of doParallel or doMC, as suggested by @mtmorgan

**Comment by vobencha** [comment]
Hi @alussana ,
@Kayla-Morrell and I will be reviewing your package and will have a first round of comments for you next week.
Valerie

**Comment by vobencha** [comment]
Hi,

The package looks good. A few comments and suggestions below. Let us know if
you have questions.

1) Imports / Depends in NAMESPACE

If you need functions from SummarizedExperiment to manipulate the data
objects, you should 'Depend' (not 'Import') SummarizedExperiment. It is
inconvenient for the user to have to load SummarizedExperiment in
order to use the package data.

2) man pages

i) dontrun
For the most part the man pages are very complete - thank you. There
are a couple of /dontrun statements which we discourage. Why were
these marked as /dontrun? 
```
~/repos/github/packageReview/AffiXcan/man >grep dontrun *
affiXcanGReX.Rd:\dontrun{
computeExpr.Rd:\dontrun{
```
ii) Please add detail to the existing man pages for data objects
explaining how they were generated. Were they downloaded and subset
or did you generate them, if yes, how etc.

3) LazyData

Setting LazyData to TRUE can result in much longer load times when other
packages load (depend on) AffiXcan. I would recommend changing this to FALSE.

4) example data

Any reason why 'testing.tba.toydata.rds' and 'training.tba.toydata.rds' are in
inst/extdata instead of data/? The *.rds files se are serialized R objects so
it would make sense to have them in data/ and documented in man.

5) preallocate list()

In affiXcanPcs() and similar functions you're growing the list (making copies) with each addition:
```
pcs <- append(pcs, newPcs)
```
If you know the length in advance it would be best to preallocate with
```
pcs <- vector("list", desired_length)
```
Filling the list with single bracket does not make a copy and would
be a better approach: 
```
pcs[index] <- value
```
Some useful references on avoiding copies:
https://bioconductor.org/developers/how-to/efficient-code/
https://www.bioconductor.org/help/course-materials/2017/Zurich/Inside-R.html

6) updateObject()

What is the purpose of the updateObject() call, i.e., why do these objects need an update?

7) README

The README should refer the user to the package vignette, not another
site on the web, e.g,
```
For usage, please see the package's
[vignette](https://mega.nz/#!uW4RRYjJ!loBNzR24ECan2LFLDBmXkekTNtHVbYoBy1iUHmNL1XA).
```
If this doc at mega.nz has critical useage information it should be
included in the vignette. Was there a reason why this wasn't included in the
vignette?

8) vignette 

I think it would be helpful to add a 'Background' section to explain what
AffiXcan is (stands for) and what type of analysis it performs. Also
give a little context of how this package fits into the big picture
of analysis in this field, e.g., are there other packages in Bioconductor
that do similar things and what AffiXcan adds that is unique.

9) gc() and rm()

R will automatically take care of deleting objects that are no longer used so there is no need to call `gc()`. I also think most of the rm() calls are also unnecessary. Have you tested with and without and found them essential for memory management?

This page has some details on garbage collection:
http://adv-r.had.co.nz/memory.html

10) BiocParellelParam

It would make sense to let the user construct the BiocParallelParam at the top level when affiXcanImpute() is called. The argument could be BPPARAM and the default
```
BPPARAM = BiocParallelParam()
```
The BiocParallelParam() constructor detects the OS and automatically
chooses the most appropriate back-end (Snow, Multicore etc.).

If you specifically want to use the SnowParam() this could be the default
```
BPPARAM = SnowParam()
```
but I don't think construction of the param should be buried in 
affiXcaPcs() but instead pushed higher up so the user has control over it.

The BiocParalleParam() constructor also picks a sensible number of default
cores so the user would not have to specify this unless they want to.

**Comment by vobencha** [comment]
@alussana 

I didn't provide much background for why I asked you to set LazyData=FALSE. This is not a big concern when the datasets are small and yours are fairly small:
```
~/repos/github/packageReview/AffiXcan >du -h data/
28K	data/
~/repos/github/packageReview/AffiXcan >du -h inst/extdata/
1.5M	inst/extdata/
```
There are 2 components to the lazy load database, one is the .rdb file which stores the objects and the other is the .rdx index file. When the data are large and LazyData=TRUE, installation of the package can be slow due to creating the index. 

LazyData=TRUE only applies to data in the data/ directory. If you move the test and train data sets to data/, good practice would be to save one object per file and/or investigate compression options with tools:::resaveRdaFiles(), saveRDS(), save() etc.

**Comment by alussana** [comment]
@vobencha and @Kayla-Morrell,
Thank you very much for your review!
I will try and address these points within the next few days

**Comment by alussana** [comment]
1. NAMESPACE

Done; 'Depend' on SummarizedExperiment (not 'Import')

2. man pages

i)
Togheter, the functions affiXcanTrain() and affiXcanImpute() call every other
function, so running these two means running all the package's functions. In
order to minimize the checking time I would have tagged with /dontrun every
function except affiXcanTrain() and affiXcanImpute(), but BiocCheck allows a
/dontrun statement on not more than 20% of functions.

WARNINGS
In this context, the build report for my latest push gave a warning
on Windows:
    
    WARNING: check time exceeded 5 min

The checking time on the other machines is around 2 min, while on Windows is
over 9 min
I already had to address this problem in a previous build and I managed to
solve it by reducing the time needed by the example code to be executed
lightening the example datasets, but now - if avoiding the redundancy of the
examples with the  \dontrun statement is not possible - I'm not sure what to do.
Could you help me?

ii)
Done; I added details on how the data objects were generated

3. LazyData

Done; LazyData set to false

4. example data

I tried to move *.rds files in data/, changing the example code accordingly.
Everything seemed to work, but devtools::check() throwed a warning:

    checking contents of ‘data’ directory ... WARNING
    Files not of a type allowed in a ‘data’ directory:
      ‘testing.tba.toydata.rds’ ‘training.tba.toydata.rds’
    Please use e.g. ‘inst/extdata’ for non-R data files

Maybe I'm missing something, but this was the reason why I located these files
in inst/extdata

5. preallocate list()

Done;
I'm aware of these growing lists. When using affiXcanTrain() or
affiXcanImpute(), if the user provides only one path to a MultiAssayExperiment
RDS object, the growing list issue should be irrelevant. However, TBA matrices
are typically very large object and it is likely that they are stored in
different files (e.g. one for each chromosome, but AffiXcan ultimately wants to
create only one GReX matrix in a single SummarizedExperiment object). In this
latter case, the growing list is copied a number of times equal to the number of
different MultiAssayExperiment objects provided by the user.
I added the function overlookRegions() to count the number of assays() contained
in all the MultyAssayExperiment objects together. This integer is now used to
preallocate the lists in affiXcanPca() and affiXcanPcs(), and also to check if
the number of genomic regions included in the training phase is equal to the
number of regions found in the MultiAssayExperiment objects by affiXcanImpute()
(the condition being false results in a warning)

6. updateObject()

Done;
When I was writing this package I experienced a couple of situations in which
devtools::check() threw an error (sorry, I can't remeber exactly what the error
said) and suggested to call updateObject(). I honestly don't know why calling
updateObject() used to solve the issue.
Since I too can not see the purpose of calling updateObject(), I removed it and
the package works fine.

7. README

Done; the doc at mega.nz is nothing more than the package's vignette in html
format. I thought it could be useful to download the html file without
downloading the package or installing it on the system. While rewriting the
README I removed the link to the external document.

8. vignette

Done; I added some background information, including in particular the role of
AffiXcan's features in studying/predicting how genetic variation influences gene
expression.

9. gc() and rm()

Done; thanks for the useful link! I removed rm() and gc() calls since they are
not needed.

10. BiocParellelParam

Done; BiocParallelParam construction at top level; BPPARAM = bpparam() as
default.

**Comment by vobencha** [comment]
Hi,
Thanks for the detailed response. 

2. man pages
If `affiXcanTrain()` and `affiXcanImpute()` are the higher level calls, you can rewrite the example to only be run if the session is interactive:
```
if (interactive()) {
   example here
   ...
}
```
The other man pages should test the functions "beneath" these 2 so in essence the functionality is being tested - that's the main point. No need to duplicate the run in multiple man pages.

4. My oversight. These are `.rds` files, not `.rda`. Yes, the `.rds` files must go in inst/extdata.

The package looks much cleaner - thanks for making all the changes. Once these last 2 issues are cleared up we can approve it.

Valerie

**Comment by alussana** [comment]
Thank you, Valerie

Sorry for the delay, I had some commitments these days.
I will edit the examples asap.

Alessandro

**Comment by alussana** [comment]
I added some if(interactive()) conditions:

In order to call every function once during the checking, only the examples in
man/AffiXcan-package.Rd are now tested in a non-interactive session. This should
be the most convenient way to test the whole workflow (training + testing),
calling every function, whitout executing the functions more than once.

affiXcanTrain() and affiXcanImpute() are the higher level calls, but excluding
their examples is not enough to avoid redundancy. In fact, for example:
affiXcanPcs() calls computePcs; affiXcanPca calls computePca; affiXcanBs()
calls computeBs() and needs the output of affiXcanPca() (so in the examples is
again executed affiXcanPca); and so on...

Please let me know if this is OK or I have to follow more literally your
previous suggestion when using if(interactive()). In this latter case I
think it is quite likely that there could be checking time issues on Windows

Alessandro

**Comment by vobencha** [comment]
Thanks for making the changes. I think you may have scaled back more than necessary but this is fine. If there are some man pages that don't take long to run I'd remove the `interactive()` statement.

It's a balance. You want to minimize the number of times a long running function is called but you also want to test it's critical behavior. Hopefully you feel you've tested the fundamental parts of the main functions. Feel free to play around with this as you develop the package. Unit tests (even for unexported functions) would be a good future addition.

Valerie

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alussana.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"AffiXcan\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AffiXcan

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
