### ISSUE TITLE
DelayedDataFrame

### ISSUE THREAD

**Issue by Liubuntu** [Bioconductor/Contributions#861]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/DelayedDataFrame

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Qian, @Liubuntu 
Thanks for submitting to Bioconductor. 
I have had a look at your package. 
It's looking good! 

Please see the review below.

Best regards,
Marcel 

---

# DelayedDataFrame #861

## DESCRIPTION

* Looks good. 
* You don't need the `LazyData` field in there
* Last sentence could be:
> The listData slot stays untouched until a realization call (e.g., DataFrame
constructor OR 'as.list') is invoked.

## NAMESPACE

* Does `extractROWS` need to be an exported method?

## vignettes/

* It looks good. It is brief and describes how to get started with
`DelayedDataFrame`

## R/

* Perhaps you can use something like a `cbind.DelayedDataFrame` in the
constructor function (L:68) so that you don't have to ensure that your output
will be `DelayedDataFrame` (L:74)
* `check.names` works when _not_ doing the `cbind` in the contructor. To make it
work with `DelayedDataFrame` inputs, use `make.names` after `cbind`ing.
* The `setAs,DataFrame,DelayedDataFrame` function can be reduced to one line by
using `length(from)`:
```
ldf <- length(from)
lazyIndex <- .LazyIndex(vector("list", as.numeric(as.logical(ldf))),
    index=rep(1L, ldf))
```
* You're using the copy-replace method in DelayedDataFrame-method.R-L:64. It
might not make much of a difference in newer version of R but you should use
the allocate-fill method.
* Can you use `replaceSlots` in `.cbind_DDF` rather than initialize? I think
this is preferred. Thoughts @hpages?


Minor:
* `if (length(listData) > 0)` is equivalent to `if (length(listData))` and
`if (!ncol(from))` is the same as `if (ncol(from) == 0)`

**Comment by Liubuntu** [comment]
Hi @LiNk-NY , 

Thank you so much for reviewing and the helpful suggestions. I'll make changes and update. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi Marcel, 

Thanks again for the review. Here I have made modifications according to your suggestion. Also I have made explanations for some of the points. Please take a look, thanks!

> Does extractROWS need to be an exported method?

This is a method that is defined and exported inside "S4Vectors", and "?extractROWS" shows a help page saying "...They are not intended to be used directly." So I guess although it's not intended for general use, I'll still need to export it? 

> Perhaps you can use something like a cbind.DelayedDataFrame in the
constructor function (L:68) so that you don't have to ensure that your output
will be DelayedDataFrame (L:74)

We do have the `.cbind_DDF` defined to keep all old lazyIndexes (this function is based on all arguments in DelayedDataFrame class), and `cbind,DelayedDataFrame` on top of it to do the coercion of non-DelayedDataFrame arguments into DelayedDataFrame first and then call `.cbind_DDF` to keep any old lazyIndexes. But one problem is that in order to invoke `cbind,DelayedDataFrame`, the first argument must be DelayedDataFrame class, otherwise, a warning message will be returned. 

For example, when the first argument is a DelayedDataframe, and 2nd a DataFrame, it gives a warning: 
```
ddf1 <- DelayedDataFrame(letters, da1 = DelayedArray(array(1:26)))
!> cbind(ddf1, DataFrame(letters))
 DelayedDataFrame with 26 rows and 3 columns
         letters            da1     letters
     <character> <DelayedArray> <character>
 1             a              1           a
 2             b              2           b
 3             c              3           c
 4             d              4           d
 5             e              5           e
 ...         ...            ...         ...
 22            v             22           v
 23            w             23           w
 24            x             24           x
 25            y             25           y
 26            z             26           z
 Warning message:
 In methods:::.selectDotsMethod(classes, .MTable, .AllMTable) :
   multiple direct matches: "DelayedDataFrame", "DataFrame"; using the first of these
```
Or when the 1st argument is a DelayedDataFrame but the 2nd argument a plain vector, it returns a DataFrame object: 
```
 > cbind(ddf1, letters)
 DataFrame with 26 rows and 3 columns
         letters            da1     letters
     <character> <DelayedArray> <character>
 1             a              1           a
 2             b              2           b
 3             c              3           c
 4             d              4           d
 5             e              5           e
 ...         ...            ...         ...
 22            v             22           v
 23            w             23           w
 24            x             24           x
 25            y             25           y
 26            z             26           z
```
 
That why we need to ensure the output of `DelayedDataFrame` class in L75 for the constructor. 
Talked with Herve before but haven't got any good solution for now... The S4Vectors for DataFrame was complicated, and hard to modify for DelayedDataFrame, would appreciate for any suggestion. 

> Can you use replaceSlots in .cbind_DDF rather than initialize? I think
this is preferred. 

I have changed this into `BiocGenerics:::replaceSlots` and it works equally fine as `initialize`. I checked the help page for initialize and now knew that  `new()` in turn calls `initialize()`. But doesn't really know the difference between replaceSlots and initialize, which one is more general / intuitive / generic in this kind of situation? So still keeping the old code commented inside the script. 

> check.names works when not doing the cbind in the contructor. To make it
work with DelayedDataFrame inputs, use make.names after cbinding.

Could you give more details on this? Thanks!

I believe I have addressed all other issues in the review. Please take another look. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @LiNk-NY , 

Do we have any updates on this package? I have made some updates based on your review, but also need some suggestions for a future incorporation. I plan to update this package in the next 6 months (together with the `VariantExperiment` package) to make it more powerful with more complete functionalities. Let me know if there is any immediate issues we need to address. Thanks a lot!

Best,
Qian

**Comment by LiNk-NY** [comment]
Hi Qian, @Liubuntu 
Sorry for the delay in getting back to you. 

> This is a method that is defined and exported inside "S4Vectors", and "?extractROWS" shows a help page saying "...They are not intended to be used directly." So I guess although it's not intended for general use, I'll still need to export it?

If it's an internal method, you don't need to export it. 

> We do have the .cbind_DDF defined to keep all old lazyIndexes (this function is based on all arguments in DelayedDataFrame class), and cbind,DelayedDataFrame on top of it to do the coercion of non-DelayedDataFrame arguments into DelayedDataFrame first and then call .cbind_DDF to keep any old lazyIndexes. But one problem is that in order to invoke cbind,DelayedDataFrame, the first argument must be DelayedDataFrame class, otherwise, a warning message will be returned.

If it works, I would just leave it. In terms of having a constructor function that does not depend
on coercion, I would use the `new` function in conjunction with a helper function to ensure that
you have the right data class, i.e. `DataFrame`, `DelayedArray`, etc. and then build with those
objects. Maybe you want to look at `S4Vectors:::new_DataFrame` and see how `DataFrame`
is constructed from `...`. 

> I have changed this into BiocGenerics:::replaceSlots and it works equally fine as initialize. I checked the help page for initialize and now knew that new() in turn calls initialize(). But doesn't really know the difference between replaceSlots and initialize, which one is more general / intuitive / generic in this kind of situation? So still keeping the old code commented inside the script.

`replaceSlots` is the way to go. I don't know the specifics. Perhaps @hpages can elaborate. But this
helps when other developers are expanding your class. 

* For `make.names`, use it after line 28 for the `ans` object.

**Comment by LiNk-NY** [comment]
You can use this diff to clean up the code a tiny bit :) 

```diff
diff --git a/R/DelayedDataFrame-class.R b/R/DelayedDataFrame-class.R
index d983a19..feaef90 100644
--- a/R/DelayedDataFrame-class.R
+++ b/R/DelayedDataFrame-class.R
@@ -64,14 +64,14 @@ DelayedDataFrame <- function(..., row.names=NULL, check.names=TRUE)
 {
     listData <- list(...)
     isDDF <- vapply(unname(listData), is, logical(1), "DelayedDataFrame")
-    if (length(listData) && any(isDDF)) {
+    if (length(listData) && any(isDDF))
         ans <- do.call(cbind, listData)
-    } else {
-        df <- DataFrame(..., row.names=row.names, check.names=check.names)
-        ans <- as(df, "DelayedDataFrame")
-    }
+    else
+        ans <- DataFrame(..., row.names=row.names, check.names=check.names)
+
     if (!is(ans, "DelayedDataFrame"))
         ans <- as(ans, "DelayedDataFrame")
+
     ans
 }
 ### FIXME: the "check.names" in constructor is not working here yet. 
```

**Comment by Liubuntu** [comment]
Thanks @LiNk-NY , I'll work on the issues.

**Comment by Liubuntu** [comment]
Hi Marcel @LiNk-NY , 

Thanks for the suggestions! I have made the following modifications based on your comments: 

1. I have unexported the `extractROWS` method, but keeping the aliases
   and rdname so that by `?extractROWS,DelayedDataFrame-method`, it
   could still open the help page and show the usage of this function
   if there is any need.

2. Cleaned up the `DelayedDataFrame` constructor. Thanks for the
   `make.name` suggestion, it works magic that I need!

The constructor function works fine now, but I'll look at your following comment and see if I can improve it. But I'm not sure if I'll make the changes for this cycle. I am pretty sure to work on the DelayedDataFrame package in the new release cycle and put effort in polishing the code. Thanks!

> In terms of having a constructor function that does not depend
on coercion, I would use the new function in conjunction with a helper function to ensure that
you have the right data class, i.e. DataFrame, DelayedArray, etc. and then build with those
objects. Maybe you want to look at S4Vectors:::new_DataFrame and see how DataFrame
is constructed from ....

Best,
Qian

**Comment by lawremi** [comment]
I'm confused by `cbind,DelayedDataFrame()`, because that should only dispatch when _all_ arguments in `...` are DelayedDataFrame objects. Yet, the code seems to expect that some won't be, and attempts to coerce them. Have you tested this yet? To achieve what you want, best practice is to define methods on `cbind2()` that perform the coercion.

Calling `cbind()` in the constructor is going to be a problem, because in general it is going to produce matrices and dissolve any abstractions. A simple approach would be to just explicitly coerce everything to a DelayedDataFrame and `cbind()` those together, but the column naming is not going to be consistent with `data.frame()` or `DataFrame()`, recycling is not going to work, etc. It might be possible to generalize `DataFrame()` to create any DataFrame derivative, without extracting columns (and thus materializing). Maybe the simple approach is good enough for submission. For simplicity, you could unconditionally take that approach and remove all the `DataFrame()` calls from the constructor.

Btw, you only want to do `make.names()` when `check.names` is `TRUE`, and just FYI you can pass `strict=FALSE` to `as()` to avoid coercing an object that is already derived from the target class.

**Comment by Liubuntu** [comment]
Hi @lawremi and @LiNk-NY , 

Thank you all for the good suggestions on the `DelayedDataFrame` constructor. There were some problems in writing the constructor. We want to keep the old lazyIndexes as much as possible from a DDF input, also we want the `cbind,DelayedDataFrame` to dispatch only when all arguments in ... are DelayedDataFrame objects. Also we want to remove the `DataFrame()` from `DelayedDataFrame()`... There are many flaws especially in the structure of having `cbind,DelayedDataFrame` and `DelayedDataFrame()`. (`cbind,DataFrame` calls `DataFrame()` actually...). But I'm hoping to have it available on devel for this stage, and will put more efforts in updating/polishing and add new features in next release cycle. 

I have also modified the package according to the following part. Thanks @lawremi 
> Btw, you only want to do make.names() when check.names is TRUE, and just FYI you can pass strict=FALSE to as() to avoid coercing an object that is already derived from the target class.

Best,
Qian

**Comment by LiNk-NY** [comment]
Hi Qian, @Liubuntu 

Sorry for the delay!

Thanks for making those changes. I agree with Michael's comments.
The constructor shouldn't be calling `cbind`. Please work on these points for the next release.

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Liubuntu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DelayedDataFrame")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DelayedDataFrame

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
