### ISSUE TITLE
VariantExperiment

### ISSUE THREAD

**Issue by Liubuntu** [Bioconductor/Contributions#862]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/VariantExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
I'm confused about how VariantExperiment compares to VCF. Seems like the basic API should be the same, as the underlying data is very similar. SeqArrray is pretty close to a direct embedding of VCF in GDS. Also, this fails to encapsulate the GDS implementation. There are literally function arguments named `gdsobj` when the operation itself is more general.

Why don't we come up with an API for working with variant data like that stored in VCF and SeqArray and define that somewhere, probably the VariantAnnotation package. Then have a SeqArrayExperiment or GDSExperiment or something that transparently pushes operations down to the GDS/SeqArray layer.

**Comment by Liubuntu** [comment]
Hi @lawremi , 

Currently the VariantExperiment is having GDS as the real backend. Assay data are saved as GDSArray, row/colData are saved as DelayedDataFrame which has 1D-GDSArray as columns. The `makeSummarizedExperimentFromVCF` actually converts VCF into GDS (using `SeqArray::seqVCF2GDS`) and then use the GDS as backend for the VariantExperiment object. So this is not the most efficient way of embedding of VCF. It's more essentially a `GDSExperiment/SeqArrayExperiment`, but with an easier interface than SeqArray, by using a `SummarizedExperiment` metaphor. 

For a better embedding of VCF, we have recently developed an API called `VCFArray`(check [here](https://github.com/Bioconductor/VCFArray)), it's designed as an extension of `DelayedArray` with VCF backend. The backend VCF file could either be saved on-disk locally or remote as online resources, it could also be a `RangedVcfStack` object with multiple of VCF files. It's designed to extract columns of VCF files (1D for fixed/info columns and >=2D for geno data) and eventually be encapsulated into `VariantExperiment` (as a 2nd phase) with a direct VCF backend. The underneath code are based on `VariantAnnotation`. The development is almost finished and close to submission. We would appreciate for any suggestions/comments at this point. For the next phase of `VariantExperiment`, we would also like to have the variant filtering functions work. 

The function arguments with `gdsobj` because the method generic are defined inside `SeqVarTools`, and we want them to work equivalently to `VariantExperiment` object with the corresponding GDS backend...  

Best,
Qian

**Comment by lawremi** [comment]
I'm just confused as to why this package does not import VariantAnnotation, e.g., why not implement a `geno()` method on this object? VariantExperiment sounds generic, but has a specific implementation, which is weird. Somehow there should be unification between the _VCF_ object and the _VariantExperiment_ object.

**Comment by mtmorgan** [comment]
The idea was to implement the 'SummarizedExperiment API', rather than SE + VCF; those wanting  the VCF API can use VariantAnnotation?

**Comment by lawremi** [comment]
How? Do I need to convert the VariantExperiment to a VCF? Why do I have to do that when they have the same data model? If I want to write code that generally interacts with variant data, should I use `geno()$GT` or `assay()$GT` to get the genotypes? I guess `assay()$GT` would always work, but an argument could be made for calling `geno()` for semantic reasons. Or, why does VariantAnnotation have a `geno()` if we could have just used `assay()` all along?

Doesn't it make sense to define a variant-specific API (taking inspiration from VariantAnnotation and VariantExperiment), and then have separate packages that implement that API? Or am I crazy?

```
SummarizedExperiment <- VariantExperiment
                                     ^-- GDSExperiment
                                     ^-- VDSExperiment
```

**Comment by mtmorgan** [comment]
Sorry for my delay! The package looks good and I have only a few minor comments.

DESCRIPTION

- good

vignettes

- use an abstract or the introductory paragraph to describe the material found in each vignette, so the user can easily navigate to the relevant vignette.

- VariantExperiment-classs.Rmd:65 use `"VariantExperiment"`

R

- VariantExperiment-methods.R:7 usually no need to `paste()` inside `stop()`, just `stop("foo ", "bar.")

- VariantExperiment-methods.R:21 `if()` is not needed, just return the result of `identical()`

man

- good

tests

- good

**Comment by Liubuntu** [comment]
Hi @mtmorgan , 

Just forgot to comment back here. The issues were all addressed and ready for the 2nd look. Thanks!

Best,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Liubuntu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VariantExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VariantExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
