### ISSUE TITLE
HIREewas

### ISSUE THREAD

**Issue by XiangyuLuo** [Bioconductor/Contributions#864]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/XiangyuLuo/HIREewas

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
I apologize for the wait. The package looks good, but I have a few issues that should be addressed. Tags labeled [REQUIRED] must involve making the described change or an explanation. Tags labeled [CONSIDER] are advisable changes but not required. Please message me back when you are done making changes. 

GENERAL
- [REQUIRED] Better to use `lapply()` or `vapply()` in place of `sapply()` to
constrain output and improve efficiency.
- [REQUIRED] Better to use `seq_along()` or `seq_len()` in place of `1:...`.
This is slightly more efficient and ignores the unexpected case `1:0 = c(1, 0)`.
- [REQUIRED] Better to use `message()` in place of `cat()` for diagnostic
messages. `message()` messages can be toggled off.

man/HIRE.Rd
- [CONSIDER] Be more specific about types that are returned or used as
parameters. For example, It's not immediately clear what type `num_celltype`
is. It may be a `numeric(1)`, but maybe it could be a `character(1)`. It is
advisable to be as clear as possible for the user.
- [REQUIRED] The examples seem to have a lot of the issues I've pointed out
before in your code, please be sure to modify them.

man/HIREewas-package.Rd
- This should just give a description of your package to the user, so an
`examples` section does not seem necessary. The only two function exported by
your package already have examples and the vignette should already show the
general use of the package to the user.

vignettes
- [REQUIRED] L49: The vignette demonstrates how the package normally acts, so
there isn't a reason to use `set.seed()`. Please remove it.

**Comment by XiangyuLuo** [comment]
Thank you so much for the great review comments! I will revise my package according to these points and let you know as soon as possible. Thank you again for the very great help!

**Comment by XiangyuLuo** [comment]
Hi @dvantwisk I have revised the package according to your very helpful comments. The revisions are as follows.

1. I replaced all ```sapply``` by ```vapply``` in my R code as well as the code in the example.
2. I used the ```seq_len()``` function in place of all ```1:...```.
3. All ```cat()``` were replaced by ```message()```.
4. I added the data type details for the input values in the HIRE.Rd file. For example, the ```num_celltype``` was annotated as an integer.
5. In the examples, all the issues you mentioned were corrected.
6. In man/HIREewas-package.Rd, the example was removed.
7. I have deleted the ```set.seed()```.

Please accept my deepest gratitude for your precious time on my package!

Best regards,

Xiangyu

**Comment by dvantwisk** [comment]
The changes look great! I'm going to move to accept your package now.

**Comment by XiangyuLuo** [comment]
@dvantwisk Thank you so much!

Very best regards,

Xiangyu

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/XiangyuLuo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"HIREewas\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HIREewas

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
