### ISSUE TITLE
IsoCorrectoRGUI: A Graphical User Interface for IsoCorrectoR

### ISSUE THREAD

**Issue by chkohler** [Bioconductor/Contributions#867]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/chkohler/IsoCorrectoRGUI

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by chkohler** [comment]
Dear Martin Morgan @mtmorgan,

thanks for considering our ***IsoCorrectoRGUI*** package for review.

Please let me add some information on this submission:
***IsoCorrectoRGUI*** is a graphical user interface for our IsoCorrectoR package, wich is also currently under review](https://github.com/Bioconductor/Contributions/issues/800) and reviewed by Marcel Ramos (@LiNk-NY). Mr Laurent Gatto (@lgatto) offered his assistance to take a look at ***IsoCorrectoR*** by this weekend as he is an expert in the proteomics / metabolomics field.
Hence, do you think it would be possible to assign Marcel Ramos and Laurent Gatto as additional reviewers for our ***IsoCorrectoRGUI*** package?

At the moment, the build process of ***IsoCorrectorRGUI*** fails as ***IsoCorrectoR*** package is not yet part of the Bioconductor repository. Is there nevertheless a way to build ***IsoCorrectoR*** successfully on your build systems?

Many thanks for your help.
Please let us (Paul Heinrich (@paulheinrich) and me) know if we can answer any further questions.

Regards
Paul and Christian

**Comment by mtmorgan** [comment]
We will wait on this review until IsoCorrector has been accepted and built by the main builder, and then proceed with the review of this package.

**Comment by mtmorgan** [comment]
Now that IsoCorrector has been added to Bioconductor, can you please bump the version of this package to trigger a build?

**Comment by mtmorgan** [comment]
DESCRIPTION

- Authors@R should be used instead of Authors:, Maintainer: (these fields are created when the package is built).
- Please provide more detail in Description: so that one does not have to chase down the IsoCorrectoR package to find relevance.

vignettes

- no need for the *R file
- Please update the text labelled '__THIS TEXT HAS TO BE UPDATED__'

R

- I recognize the challenges of testing GUI-based code, but it is a little disconcerting that most of the code is not evaluated at all, beyond being syntactically correct.

**Comment by chkohler** [comment]
Dear Martin Morgen @mtmorgan,

thank you for your comments, we will deal with the issues mentioned. 

> I recognize the challenges of testing GUI-based code, but it is a little disconcerting that most of the code is not evaluated at all, beyond being syntactically correct.”

Do you mean that the GUI code lacks sections to evaluate the validity of user inputs? Most of the code that checks user input for validity is in the ***IsoCorrectoR*** base package. The GUI mostly just takes parameters and then forwards them to a function call to `IsoCorrection()` from the base package. The GUI itself checks whether the input file paths provided exist, whether all required inputs have been made by the user and puts constraints on the number of options available to the user (checkboxes etc.). Once the parameters have been transferred from the GUI to `IsoCorrection()`, subfunctions of IsoCorrection() assess their validity. Aspects that are checked are: 

- Is the structure of the input files correct? 
- Are there logical issues in input files?
- Are the parameters supplied within the expected range of values?

If an error occurs/if any of the checks performed is negative in `IsoCorrection()`, the corresponding error message will be transferred to the GUI and pop up as an error window. Additionally, errors and warnings are written to the log-file.

Kind regards,

Christian @ckohler and Paul @paulheinrich

**Comment by chkohler** [comment]
Dear Martin Morgen @mtmorgan,

thank you for your comments, we will deal with the issues mentioned. 

> I recognize the challenges of testing GUI-based code, but it is a little disconcerting that most of the code is not evaluated at all, beyond being syntactically correct.”

Do you mean that the GUI code lacks sections to evaluate the validity of user inputs? Most of the code that checks user input for validity is in the ***IsoCorrectoR*** base package. The GUI mostly just takes parameters and then forwards them to a function call to `IsoCorrection()` from the base package. The GUI itself checks whether the input file paths provided exist, whether all required inputs have been made by the user and puts constraints on the number of options available to the user (checkboxes etc.). Once the parameters have been transferred from the GUI to `IsoCorrection()`, subfunctions of `IsoCorrection()` assess their validity. Aspects that are checked are: 

- Is the structure of the input files correct?
- Are there logical issues in input files?
- Are the parameters supplied within the expected range of values?

If an error occurs/if any of the checks performed is negative in `IsoCorrection()`, the corresponding error message will be transferred to the GUI and pop up as an error window. Additionally, errors and warnings are written to the log-file.

Kind regards,

Christian @chkohler and Paul @paulheinrich

**Comment by mtmorgan** [comment]
I meant more simply that there is a lot of GUI code -- the IsoCorrectoRGUI package itself -- that is not tested, e.g., for simple typos that fail to pass correct user input to the IsoCorrectoR.

**Comment by chkohler** [comment]
Dear Martin Morgen @mtmorgan,

yesterday, we recieved a decision letter on our IsoCorrectoR manuscript with only minor issues but a prompt deadline. Hence, we'd like to work on this issue first and then focus on the IsoCorrecturGUI issues afterwards.

Kind regards,
Christian @chkohler and Paul @paulheinrich

**Comment by paulheinrich** [comment]
Dear Martin Morgan @mtmorgan,

we have worked on the issues you raised. Please find a point-by-point discussion below.
 
> DESCRIPTION
> 
>     * Authors@R should be used instead of Authors:, Maintainer: (these fields are created when the package is built).
> 
>     * Please provide more detail in Description: so that one does not have to chase down the IsoCorrectoR package to find relevance.

We have removed the manually created fields Authors: and Maintainer:. 

We added information on what the IsoCorrectoR package does.

> vignettes
> 
>     * no need for the *R file
> 
>     * Please update the text labelled '**THIS TEXT HAS TO BE UPDATED**'

We have removed the R file and created a new vignette that also holds all the information from the IsoCorrectoR package. This way, users don’t have to search for the IsoCorrectoR vignette to find that information. The text labelled 'THIS TEXT HAS TO BE UPDATED' has been updated.

> R
> 
>     * I recognize the challenges of testing GUI-based code, but it is a little disconcerting that most of the code is not evaluated at all, beyond being syntactically correct.

We have added tests using the testthat package. Those tests check whether parameters are correctly transferred from the GUI to the call of the `IsoCorrection()` function of the IsoCorrectoR package. One type of test checks if the default parameters of the GUI are transferred correctly, without making any changes. The other type of test simulates user inputs by directly modifying the variables otherwise set by the functions associated with the GUI buttons or fields. It is then analyzed whether the parameters that would be transferred to `IsoCorrection()` are the expected ones.

Kind regards,

Christian (@chkohler) and Paul (@paulheinrich)

**Comment by chkohler** [comment]
Dear Martin Morgan @mtmorgan,

thank you very much for accepting our **IsoCorrectoRGUI** package.

Kind regards,

Christian (@chkohler) and Paul (@paulheinrich)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/chkohler.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("IsoCorrectoRGUI")`. The package 'landing page' will be created at

https://bioconductor.org/packages/IsoCorrectoRGUI

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
