### ISSUE TITLE
transite

### ISSUE THREAD

**Issue by kkrismer** [Bioconductor/Contributions#876]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kkrismer/transite

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kkrismer** [comment]
Hi @dvantwisk,

Thank you for your kind and helpful feedback!

I have changed all required points as suggested and followed your recommendation on all but two points labeled as _consider_. I am happy to elaborate on the exact changes, if necessary.

Cheers,
Konstantin

**Comment by dvantwisk** [comment]
I like the changes so far. It seems that the `Sys.sleep()` is indeed necessary, correct? My only remaining issue if the naming of some of your classes and methods.

The Bioconductor suite of packages involves a hierarchical system of packages that inherit classes and generics from each other. Problems may arise if the same names are used for the classes and generics that are used at a higher level of the hierarchy. For this reason, I ask that you differentiate your class and generic names a little more. `Motif` sounds like a very standard name for a class and it may have been declared elsewhere since many packages deal with motifs. It would be better to rename this class to something like `TransiteMotif`. The same goes for many of the s4 generic names that you are instantiating (e.g. `slope` and `degree` seem far to general and seem to be in use by other packages). Lastly, it is common to use "camel-case" instead of "dot-notation" for s4 methods. For example, instead of `motif.matrix` almost look like an s3 method meant to dispatch on matrix. It would be more proper to name this `motifMatrix` instead. As you can see, "camel-case" has the first word as under-case and every word after that in capitalized.

These changes will help your package play better with other packages currently present in Bioconductor. After these changes are made I should be able to accept the package.

**Comment by kkrismer** [comment]
About `Sys.sleep()`: Yes, it is used to periodically check whether the motif cache file is still in use by another process - I think `Sys.sleep()` is necessary in this case.

I've renamed the Motif class and made the method names from both classes more specific to avoid conflicts with other R/Bioconductor methods. Also, they are in camel case now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kkrismer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"transite\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/transite

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
