### ISSUE TITLE
SpatialCPie

### ISSUE THREAD

**Issue by jbergenstrahle** [Bioconductor/Contributions#880]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jbergenstrahle/SpatialCPie

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package so that main functions accept and / or return [SummarizedExperiment][1] / [SingleCellExperiment[[2] and other [standard Bioconductor objects][3] to improve interoperability with existing work flows.

[1]: https://bioconductor.org/packages/devel/SummarizedExperiment
[2]: https://bioconductor.org/packages/devel/SingleCellExperiment
[3]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by jbergenstrahle** [comment]
Thanks @nturaga for reviewing our package and for your helpful feedback!

We have reformatted the code according to the tidyverse style guide.

The package makes extensive use of data manipulations with dplyr/tidyr/et. al., which rely on NSE. However, we agree that NSE may worsen readability in some cases. Thus, wherever applicable, we're now using the `rlang::.data` pronoun to explicitly reference columns in the data being manipulated. Moreover, calls to `ggplot2::aes` have been replaced by non-NSE equivalents (either `ggplot2::aes_` or `ggplot2::aes_string`).

The error in the vignette was caused by a dependency update and should now be fixed.

We have checked that the NEWS file, although quite sparse at the moment, is parsable by utils::news()

Added text to Description and Vignette

Best,

**Comment by nturaga** [comment]
@jbergenstrahle If your local workstation is a Mac please make sure it works on that. There is an error with install `ggiraph`.

**Comment by jbergenstrahle** [comment]
Dear @nturaga , I tested the installation on a colleagues Mac and it completed without any errors. Do you have any idea what could be causing this? Not sure how to address this.

Also, about the warning "Update R version dependency from 3.5.1 to 3.6",
It's my impression that 3.6 is not officially released yet?

**Comment by nturaga** [comment]
It should be `3.6` since it's running on R-devel as the development version of R right now. This version of R will release along with your package in the next cycle. (Spring 2019)

**Comment by nturaga** [comment]
I'm also running your example given in the documentation of your app, It still doesn't work. I'm running your latest version.

```
Examples:

     if (interactive()) {
         options(device.ask.default = FALSE)

         ## Set up coordinate system
         coordinates <- as.matrix(expand.grid(1:10, 1:10))

         ## Generate data set with three distinct genes generated by three
         ## distinct cell types
         profiles <- diag(rep(1, 3)) + runif(9)
         centers <- cbind(c(5, 2), c(2, 8), c(8, 2))
         mixes <- apply(coordinates, 1, function(x) {
             x <- exp(-colSums((centers - x) ^ 2) / 50)
             x / sum(x)
         })
         means <- 100 * profiles %*% mixes
         counts <- matrix(rpois(prod(dim(means)), means), nrow = nrow(profiles))
         colnames(counts) <- apply(
             coordinates,
             1,
             function(x) do.call(paste, c(as.list(x), list(sep = "x")))
         )
         rownames(counts) <- paste("gene", 1:nrow(counts))

         ## Run SpatialCPie
         runCPie(counts)

}
```

<img width="1430" alt="screen shot 2018-11-21 at 10 27 06 am" src="https://user-images.githubusercontent.com/2746443/48851094-32dcf500-ed78-11e8-9d76-452ab3321219.png">

**Comment by jbergenstrahle** [comment]
@nturaga thanks again for taking the time to review the package. I understand it's a bit frustrating with the error you get.

Ok about R version.

I've now tested this on 4 different systems (including Linux, Windows, Mac), I've tested to perform completely clean installs with both R 3.5.1 and R 3.6. I've also asked other users to try it out. All have worked with no errors encountered. I don't really know how to address this, given that I'm unable to replicate your error. 
Any suggestions would be appreciated!

**Comment by nturaga** [comment]
It's especially hard to debug since your code is written using pipe operations. 

But the bug is in this bit, (SpatialCPie.R)

```
    browser()
    labels <-
        vertices %>%
        select(.data$resolution, .data$x, .data$y) %>%
        filter(.data$resolution != 1) %>%
        mutate(ymin = min(.data$y), ymax = max(.data$y)) %>%
        group_by(.data$resolution) %>%
        summarize(
            x = mean(.data$x),
            y = first(.data$ymax) +
                0.1 * (first(.data$ymax) - first(.data$ymin))
        ) %>%
        mutate(label = sprintf(
            "Resolution %s",
            levels(assignments$resolution)[.data$resolution]
        ))
```

This was my workflow,

```
Browse[1]>     labels <-
+         vertices %>%
+         select(.data$resolution, .data$x, .data$y) %>%
+         filter(.data$resolution != 1) %>%
+         mutate(ymin = min(.data$y), ymax = max(.data$y)) %>%
+         group_by(.data$resolution) %>%
+         summarize(
+             x = mean(.data$x),
+             y = first(.data$ymax) +
+                 0.1 * (first(.data$ymax) - first(.data$ymin))
+         )
Browse[1]> labels
# A tibble: 3 x 3
  resolution     x     y
       <dbl> <dbl> <dbl>
1          2     1  1.18
2          3     2  1.18
3          4     3  1.18
Browse[1]> levels(assignments$resolution)
NULL
Browse[1]> levels(assignments$resolution)[1:5]
NULL
Browse[1]> length(NULL)
[1] 0
```

This the where your bug is. I'm sure that if it's happening on my machine, it will happen on other users as well. Please see if you can debug this.

**Comment by jbergenstrahle** [comment]
@nturaga thanks for giving us the info. We think we have found the problem that resulted in your error. Could you give it a go and see if it works now? 

PS.  Not sure why I got a timeout on the Linux test after last update, nothing have been changed that could make a difference in the R CMD check time.

**Comment by nturaga** [comment]
I have checked your package and it looks good. Please issue another version to see how the build system responds.

**Comment by jbergenstrahle** [comment]
Thanks a lot for the review @nturaga , I've noted the ggiraph issue and also added a statement in the package vignette

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jbergenstrahle.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpatialCPie")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpatialCPie

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
