### ISSUE TITLE
countsimQC

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/Contributions#889]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/csoneson/countsimQC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hello and Thank you for your submission to Bioconductor. Please see the comments below:

**NEWS file**
- [ ] formatted incorrectly. we use the build in R functions for reading the
NEWS file and unfortunately they are strict on formatting.  It should be able to
be read in with `tools:::.news_reader_default(news)` and not indicate text:.  I
think the main issue is the headers that they should be changes in version x.y.z
rather than countsimQC v0.5.2 

**Description**
- [ ] We recommend not including lazyData: TRUE.  Please remove

**Vignette**
- [ ] Please write output to a tmpdir() rather than ".". 

**Man**
- [ ] It seems many of these functions are documented but not exported to the
user. If they are meant to be internal maybe they could be marked as such
`@keyword internal`

- [ ] countsimExample_dfmat.Rd/countsimExample.Rd Can you provide some
  additional information on source information and how the data was generated

**Data**
- [ ] It seems right now you don't utilize or reference
countsimExample_dfmat.rda anywhere. Should this be removed? 

Please comment back here describing any updates that have been made and when you are ready for re-review. 

Cheers

**Comment by csoneson** [comment]
Hi Lori, thanks for spotting these issues! I have made the following changes in v0.99.3:

- [x] reformatted the NEWS file, now it's readable with `tools:::.news_reader_default()`.
- [x] removed `LazyData: true`.
- [x] changed "." to a `tempdir()` in vignette and unit tests.
- [x] added `@keywords internal` to nonexported functions. These functions are called by the main `countsimQCReport()` function, and at this point I don't think they need to be exported. 
- [x] expanded the documentation of the data sets.
- [x] added an example involving `countsimExample_dfmat.rda` to the vignette. It was used previously in the unit tests that I trimmed to fit within the 5 min CHECK limit - I would like to keep the example data to illustrate the different ways of providing the input data sets.
- [x] updated the example data sets and added a script in `inst/scripts` to describe their generation. Since some of the packages that were used to generate the previous example data sets are no longer available, the new example data sets are different from the previous ones.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/csoneson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"countsimQC\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/countsimQC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
