### ISSUE TITLE
DEsubs

### ISSUE THREAD

**Issue by balomenos** [Bioconductor/Contributions#89]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/balomenos/DEsubs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
I noticed that your package imports DESeq, but that is a very old version; it should use DESeq2. A more complete review will be provided by @LiNk-NY in due course.

**Comment by balomenos** [comment]
Hi Martin,

Functions imported from package DESeq are used in 'DEsubs()' function to perform a differential expression analysis on the RNA-seq data imported by the user (options DEtool='DESeq' and DEtool='vst+limma'). Here, we selected a total of eight tools which were deemed appropriate for use in our approach and a synthetic analysis was performed assessing their performance. Since DESeq2 and DESeq have quite significant methodological differences and produce (more or less) different results, we would like to stay in tune with what was presented in the publication, if that is possible, and not replace DESeq with DESeq2. 

However, in version 0.99.2, the proposed changes have been included as two new options, namely DEtool='DESeq2' and DEtool='vst2+limma', by utilizing only DESeq2 functions. Understandably, the point of your comment is not to use DESeq at all. So, we await further comments on this. It would be preferable however just to include the original options. 

Notably, the user can skip the usage of a differential expression analysis tool altogether and just supply a ranked list of Q-values of the genes in the count matrix. This is a more straightforward approach and was adopted in the examples.

**Comment by LiNk-NY** [comment]
Hi @balomenos, 
Thank you for submitting to Bioconductor!
Please see your review below

---
## DEsubs

Overall, the package looks in good shape. However, there are a few things that could be improved. 

#### Function default values

Some functions in the package should have a default value at function specification rather than inside the function, e.g., `myFun <- function(arg1 = "default")`

#### Object accessors
Please try to use double bracket `[[` to access elements rather than using the dollar sign operator `$` in the code. It's good practice. 

#### 1:number
Specifying a set of numbers as `1:nrow(x)` is not considered robust coding as there is potential for a `1:0` set. It is recommended that you use `seq_len(nrow(x))` for such cases.

#### Descriptive function arguments
Some arguments in your exported functions have short and not very clear names, such as `L`. Please provide descriptive function arguments so that users know what input you intend. 

#### Using S4 methods
I noticed that your package does not contain any S4 structure but you do have a lot of `if`/`else` control structures. Could it be useful to use S4 method dispatch for those cases where you want to run code for a specific class? 

Feel free to contact me with any questions! 

Regards,
Marcel

**Comment by balomenos** [comment]
Hi Marcel,

Thanks for reviewing our package and for your useful comments, all of which have been addressed in version 0.99.5. 

### Details

**Function default values**
All functions now have default values at function specification rather than the body, except from few cases where the default value needs to be computed within the function.

**Object accessors**
Use of the `$` operator has been replaced by `[[` throughout the package.

**1:number**
The `1:nrow(x)` and `1:length(x)` specifications of sets have been replaced by `seq_len(nrow(x))` and `seq_len(length(x))` respectively.

**Descriptive function arguments**
The non-exported functions in `utilities.R` which were too vague now all have descriptive arguments. Notably, the `.` symbol in front of a function name (e.g. `.internalFunction()`) was not used in the conventional way throughout the package and was only reserved for housekeeping functions or any workhorse function called by the corresponding exported wrapper function. To avoid any confusion, all internal functions now start with the `.` symbol. 

**Using S4 methods**
It seems that there is only one place where such an approach would be advantageous, namely function `.matrixVisualization()` which handles most of the visualizations. The function has been rewritten in a modular fashion utilizing S4 method dispatch.


Best regards,
Panos

**Comment by LiNk-NY** [comment]
Hi Panos @balomenos, 
Thank you for your response. I will review the changes shortly. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Panos @balomenos, 
Thank you for your changes to the package. It's coming together nicely. 
I have some further suggestions, recommendations and one requirement. 

**Suggestion:**
Remove repetitive coding by using lookup tables with "method" and "functionNames" columns. You can then use "get()" to call the function that you need based on the method and reduce the amount of lines in your code.

**Recommendation:**
* Add a helper function for creating choices and cases so that it can be reused in both `pathwayAnalysis` and `subpathwayTypes`. 
* Try not to step on `base` function names such as `data` with your objects. 

**Required:**
* I don't see a need to create a copy of the data for the user via the `.buildDirectories` function. You don't need to put this in the `.onAttach` function. 

It would be better to create a convenience function so that if the user wishes to, he or she can copy the data files to a specified directory. Also, if you need an output folder, that can be provided in functions that save output. 

Feel free to contact me with any questions. 

Regards, 
Marcel

**Comment by balomenos** [comment]
Hello Marcel,

Thank you for your comments. All suggestions, recommendations and requirements have been addressed. In more detail:


## **Suggestions**

**Removal of repetitive coding**

- A lookup table has been created in `.getTopologicalHandlers()` providing the function needed for each topological measure for use in `.topologicalMeasures()` and `.measureToNodes()`. 
- A lookup table, has been created in `.subpathwayAnalysis()`, namely `communityHandlers`, providing functions needed in community-based subpathway extraction approaches.

## **Recommendations**

**Removal of repetitive coding**
- A helper function `.subpathwayTypes()` now provides subpathway choices and cases required in both `.subpathwayAnalysis()` and `subpathwayTypes()`.

**Removal of (argument) names replacing base functions**
- The argument name `data` was used in most exported functions. It has been replaced by the more descriptive name `DEsubs.out`. 
- The few uses of the name `data` as a variable have been removed.

## **Requirements**

- Copying of the data in `extdata//Data` via the `.buildDirectories()` function has been removed. The tool now searches for default gene-sets in `extdata/Data` and user-defined gene-sets in `DEsubs/Data`. This straightforward approach makes the existence of a helper function unnecessarily confusing, i.e. having two copies of the same data. 

**Other changes**

- The `.onAttach()` function does not call `.buildDirectories()`, which has been removed,  but merely sets up the default location for the user-directory structure. 

- No directories are created proactively. The `Output` directory required by all visualization functions is created on demand based on either the filepaths supplied by the user, or default ones. The `Data` directory can be supplied by the user,  as explained in the vignette, if any custom gene-set is to be included in the analysis or visualizations. The `User` directory, which was used for storing a ranked list of genes in `.txt` format is unnecessary and has been removed, since the full path of the file can now be supplied as an argument in `DEsubs()`.


Best Regards,
Panos

**Comment by LiNk-NY** [comment]
Hi @balomenos, 
Thank you for your changes. I will mark this package as accepted and you will be getting SVN credentials soon. 
Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by balomenos** [comment]
Hi Marcel,

Thank you for accepting the package, as well as for your useful comments.

Best regards,
Panos
