### ISSUE TITLE
RegParallel

### ISSUE THREAD

**Issue by kevinblighe** [Bioconductor/Contributions#890]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kevinblighe/RegParallel

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kevinblighe** [comment]
Dear Bioconductor, I have modified the vignette to fix what I believe threw the error; however, I have bumped the version to 0.99.1 but it has not been picked up by the bioc-issue-bot. The package had built AOK on my local system.

**Comment by mtmorgan** [comment]
Try to [diagnose the web hook][1].

[1] https://github.com/Bioconductor/Contributions#resources

**Comment by mtmorgan** [comment]
Don't worry about the error on Windows for the moment; the other `is(try(...) == "try-error")` should be `is(try(...), "try-error")`

**Comment by kevinblighe** [comment]
Thank you Martin for spotting that!

**Comment by kevinblighe** [comment]
It has now passed checks on all platforms.

**Comment by mtmorgan** [comment]
DESCRIPTION / NAMESPACE

- ok

vignette

- ok

R

- RegParallel.R:14 `message(paste0())` (also `stop()`, `warning()`) is usually unnecesary, `message` will paste multiple arguments.
- RegParallel.R:105 avoid `1:length(.)` in favor of `seq_len(.)` or `seq_along()`
- e.g., bayesglmParallel.R: there is substantial code duplication along the lines of

    ```
      if (nestedParallel == TRUE) {
        if (system == 'Windows') {
            models <- parLapply(cl, formula.list[1:(blocksize*l)],
              function(f) summary(FUN(formula = f, data = df))$coefficients)
        } else {
            models <- mclapply(formula.list[1:(blocksize*l)],
              function(f) summary(FUN(formula = f, data = df))$coefficients)
        }
      } else if (nestedParallel == FALSE) {
        models <- lapply(formula.list[1:(blocksize*l)],
          function(f) summary(FUN(formula = f, data = df))$coefficients)
      } else {
        stop('Invalid value for argument nestedParallel. Must be TRUE/FALSE')
      }
  ```
  
  What about a pattern like
  
  ```
      if (nestedParallel == TRUE) {
        if (system == 'Windows') {
            APPLYFUN = function(...) parLapply(cl, ...)
        else
            APPLYFUN = function(...) mclapply(...)
        }
      } else if (nestedParallel == FALSE)
          APPLYFUN = function(...) lapply(...)
  ```
  Each use would be 
  ```
  models <- APPLYFUN(formula.list[1:(blocksize*l)],
    function(f) summary(FUN(formula = f, data = df))$coefficients)
  ```
  with no need for tedious and error-prone repetition of the function arguments across different scenarios.

**Comment by kevinblighe** [comment]
Thank you for the helpful tips, particularly regarding the APPLYFUN - it has greatly helped to tidy up the code. I have followed up on the other suggested changes, too, and will bump the version shortly.

**Comment by kevinblighe** [comment]
Great! - thank you so much, mtmoragn!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinblighe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"RegParallel\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RegParallel

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
