### ISSUE TITLE
FCBF

### ISSUE THREAD

**Issue by lubianat** [Bioconductor/Contributions#892]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lubianat/FCBF

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
please revise your package to follow Bioconductor conventions (feature x sample matrix) and to interoperate with standard Bioconductor data representations relevant to your domain, especially the [SingleCellExperiment][1] class and / or SummarizedExperiment][2] (see [common Bioconductor classes][3]); this will improve robustness and interoperability.

Also, mark the code chunk that installs the package in the vignette as `eval = FALSE`.

[1]: https://bioconductor.org/packages/SingleCellExperiment
[2]: https://bioconductor.org/packages/SummarizedExperiment
[3]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by vobencha** [comment]
Hi,

Looks good. Just a few comments/suggestions.

1) extra files in vignettes/
Please remove myvignette.R and .build.timestamp

2) Rename the vignette to something more descriptive.

3) Why the /dontrun statements in the man pages? Are these especially long running examples? If you don't want to evaluate them here you could direct the user to the man pages for these functions for analysis examples.
```
~/FCBF/man >grep dontrun *
scDengue.Rd:\dontrun{discrete_expression <- as.data.frame(discretize_exprs(exprs))}
scDengue.Rd:\dontrun{fcbf_features <- fcbf(discrete_expression,
```

4) LazyLoad
Was there a reason you set this to TRUE in DESCRIPTION? Your man page examples don't make use of the auto-load feature.

5) Avoid use of '@'
Accessing slots with '@' is discouraged - instead you should use the class accessors.
```
~/FCBF/man >grep @ *
fcbf.Rd:target <- infection@listData$infection
scDengue.Rd:infection <- scDengue@colData
scDengue.Rd:target <- infection@listData$infection
scDengue.Rd:exprs <- scDengue@assays$data$logcounts
su_plot.Rd:target <- infection@listData$infection
```
The 'scDengue' object is a SingleCellExperiment and colData can be accessed with colData():
```
> colData(scDengue)
DataFrame with 120 rows and 1 column
               infection
                <factor>
1001700604_A13      ctrl
1001700604_A16      ctrl
1001700604_A20      ctrl
1001700604_C21      ctrl
1001700604_D6       ctrl
...                  ...
1001700605_O5     dengue
1001700605_O11    dengue
1001700605_O14    dengue
1001700605_O15    dengue
1001700605_O21    dengue
```

Use '$' on the DataFrame to pull out columns:
```
> head(infection$infection)
[1] ctrl ctrl ctrl ctrl ctrl ctrl
Levels: ctrl dengue
```

**Comment by lubianat** [comment]
Thank you for the review, @vobencha .

I think that the \dontrun statement and the LazyLoad = True were set at some time during the debugging phase and were left there. I have changed to class accessors instead of '@', and used $ to access information.

Once again, thank you for the comments/suggestions.

**Comment by vobencha** [comment]
Thanks for making the changes. It looks good and the package is approved.

FYI, you have a double `data(scDengue)` in the scDengue man page you'll want to remove at some point.

**Comment by vobencha** [comment]
@lubianat  Sorry, I didn't see the red on the SPB report before approving. I'm not sure why we're getting this - please bump the version so we can get another build.

**Comment by lubianat** [comment]
There was a typo during of the modifications, instead of getting a vector out of the object, it was returning a NULL. I have fixed the issue and bumped the version. It should work now... 
Thanks for the review and the comments.

**Comment by vobencha** [comment]
Package is approved. I am ok with the check time on Windows:

CheckTime: 5 minutes 50.88 seconds

The package takes less than 2 minutes on the other platforms.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lubianat.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"FCBF\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FCBF

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
