### ISSUE TITLE
EuPathDB

### ISSUE THREAD

**Issue by khughitt** [Bioconductor/Contributions#893]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/khughitt/EuPathDB

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hello -   I know we are talking off this space about getting the data back into the hubs but some general comments about the package so that once the data gets on it can be accepted fairly immediately

**Description**
- [ ] remove LazyData: true
- [ ] biocViews - make sure to add AnnotationHub and there will be a new biocView that should register shortly for EuPathDB
- [ ] Remove Maintainer - specified in Authors@R with cre designation

**Vignette**
- [ ] Debug once resources available through hub - a few code functions seem off

**Comment by khughitt** [comment]
- Fixed items 1-3 (Description)
- Vignette is definitely off in some places and needs to be expanded quite a bit; will prioritize that as soon as sources are available on AH for testing.

**Comment by lshep** [comment]
You don't have your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) set up but I pushed a manual build.  If you set up webhook additional version bumps will trigger a build automatically

**Comment by lshep** [comment]
I'll look this over shortly but I don't expect there to be any more recommended changes

**Comment by lshep** [comment]
@mtmorgan   Please note this is an Annotation Package -  I'm not sure what the process is with coordinating with Daniel for adding it or how that process might be different.

**Comment by lshep** [comment]
Ah yes - That would have required some changes in our internal database.  regardless glad it worked out and thank you for your opinions and working with us on improving the hub.

**Comment by khughitt** [comment]
Sounds good! And thank you as well for working with me to get this into AH -- I appreciate your patience and feedback.

**Comment by lshep** [comment]
Hello -  one last thing -  Newer Annotation Packages that use the hubs will be transitioned to github so that you would be able to push and update your package automatically -  However,  it isn't quite implemented yet.   We therefore need to manually upload the Annotation Package.  @dvantwisk   will handle this process.    Since the version bump will not happen automatically (yet) -  Could you please increase the version number to 1.0.0 and comment back here.  Then @dvantwisk  will uploaded it and it will be available shortly there after.   Cheers.

**Comment by khughitt** [comment]
Sure thing! Just bumped it. Cheers.
