### ISSUE TITLE
treeAGG

### ISSUE THREAD

**Issue by fionarhuang** [Bioconductor/Contributions#896]
- Repository: https://github.com/markrobinsonuzh/treeAGG

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Looks like the Title and Description fields of DESCRIPTION need to be updated! Please review each box that you 'checked' in the package submission form to ensure that your package is ready for review.

**Comment by fionarhuang** [comment]
Thanks! The description file was updated.

**Comment by fionarhuang** [comment]
Hi @LiNk-NY @mtmorgan,

Please excuse me for my impatience to ask about the review process of my package. As the deadline is getting closer and this issue page doesn't get new updates, I am wondering whether everything goes well about the review of my package. Would it be possible for you to kindly tell me what should I do in the next step?

Thanks!
Fiona

**Comment by fionarhuang** [comment]
Hi Marcel, 

Thanks for the help!

Fiona

**Comment by LiNk-NY** [comment]
Hi Fiona, @fionarhuang 
Thank you for your submission to Bioconductor.
Please see the review below. 
If you have any questions, please respond to the issue thread below. 

Best regards,
Marcel

--- 

# treeAGG #896

## DESCRIPTION

* Looks good.
* Please wrap the `Description` field text.
* If you're extending `SummarizedExperiment`, it would be much easier to put
`SummarizedExperiment` package in the `Depends` field. 

## NAMESPACE

* Looks good overall.

## vignettes

* It seems to me that `rowData(..., internal = TRUE)` is something that you
should provide in another function. It is better to keep the consistency of
what `rowData` does. Otherwise, you can throw your users off by returning
data or employing an argument that is not expected by the method.
* Looks good.

## R/

* For the bracket `[` method, it seems like you should have an accessor for the
`SummarizedExperiment` data object so that you don't have run the constructor
function.
* You may want to use `BiocGenerics:::replaceSlots` after subsetting rather
than reconstructing the object.
* Look into using `@inheritParams` where possible. It might be better to have
the same arguments that the `SummarizedExperiment` constructor function has so
that it is clear to the user.
* I'm not sure to what extent you need the different data sizes but I would
consider using just one medium sized dataset for examples.
* Some of the repetitive code can be reduced using conditional logic such as
`onlyTip <- level == "leaf"` and then use the same operations for both
conditions in `fdr0`, `tpr0`, etc.
* Functions like `findAncestor` are only working on `phylo` trees. I thought
you wanted to support functions / methods for your class,
`treeSummarizedExperiment`? 
* Use names instead of integer positions for subsetting where possible (e.g.,
`vec[, "varA"]` vs `vec[, 1]`)
* Avoid conditional return values as in `findAncestor`. Please provide functions
with a single and consistent output.
* Repeat may not be necessary, it can done via `lapply` or a `for` loop
(`R/findOS.R`:L60)
* Use helper functions to reduce repetitive code (see `matTree`)
* Avoid nested `for` loops, use vectorized operations
(see: http://bioconductor.org/developers/how-to/efficient-code/)
* Avoid creating methods for classes that are not your own. For methods
such as `nodeValue`, use an `ANY` class signature and filter using
`is.data.frame` etc.
* Combine files into groups of related functions. This makes it easier to find
related functions and easier to maintain.
* Use `seq_len` or `seq_along` to create sequences rather than `seq(1, n)`
* Avoid nesting `lapply` calls where possible.
* It seems like you're running the same checks over several functions, create
a helper functions to standardize those checks across the functions such
as `signalNode`
* Remove `set.seed` from the inside of function calls
* Remove commented code or provide a working version
* Explicitly set defaults when arguments are `NULL`, for example, in the
`addLegend` internal function, you can set `legend.theme = list(NULL)`
instead of checking it's `NULL` and then setting it.

Minor:
* You don't need to set the object into itself (see `findAncestor.R` line 50)
* Use `is.character` and other `is.*` type checking functions instead of
`inherits` (where possible; such as `is.data.frame`, `is.matrix`, etc.)
* `if (length(x) > 0)` is the same as `if (lenght(x))`
* Use `methods::is` instead of `inherits` to test S4 classes (`R/selNode.R`)
* Convention is to add a `.` period in front of a function name (e.g.,
`.infLoc`)

## tests/

* Looks like you have plenty of tests. :+1:

**Comment by fionarhuang** [comment]
Hi Marcel@LiNk-NY ,

Thank you very much for your help in review my package and the nice comments! 

As you suggested, I added the SummarizedExperiment in the Depends of description file. In this way, the package SummarizedExperiment is loaded automatically when users load my package. If I delete accessor functions, e.g. colData, from allGenerics.R files, users could still use colData.

- Does it mean that all the accessor functions created in allGenerics.R files using callNextMethod() are not necessary now?
- It seems there are deadlines on this Wednesday and Friday. Should I finish all the changes before this Wednesday to get accepted to the Bioconductor devel? Is it possible to allow me some extra days to fix all the issues?

Thanks!
Fiona

**Comment by LiNk-NY** [comment]
Hi Fiona, @fionarhuang 

> Does it mean that all the accessor functions created in allGenerics.R files using callNextMethod() are not necessary now?

Yes, you don't need to set those methods because your class contains `SummarizedExperiment`. They will just work on the internal `SummarizedExperiment` representation.

> It seems there are deadlines on this Wednesday and Friday. Should I finish all the changes before this Wednesday to get accepted to the Bioconductor devel? Is it possible to allow me some extra days to fix all the issues?

If you want your package to be included in the *3.8* version of Bioconductor, you should have all the changes in by the deadline. _Otherwise_, your package will only be included in the *devel* version of Bioconductor. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Also, please remove all the:

```
else {
    p <- p
}
```
`p` will be `p` even if you don't modify it. Therefore, you only need the `if (condition) { p <- ... }` 

Thanks

**Comment by fionarhuang** [comment]
Hi Marcel,

I am doing updates on my package. Thank you for all your comments. They are very helpful!
Sorry, I didn't ask my question clearly.  We would like to have our package included in the 3.8 version of Bioconductor. Would it be possible to allow me some extra days to do the updates based on your comments? I will finish it as soon as possible, hopefully before next Monday.

> You may want to use BiocGenerics:::replaceSlots after subsetting rather than reconstructing the object.

When I tried replaceSlots, R complains that replaceSlots isn't exported in creating namespace file.

> Avoid conditional return values as in findAncestor. Please provide functions
with a single and consistent output.

I am not very clearly about this comments. Does it mean that I should separate it into two functions, one return "label" and one return "number"? 

> Repeat may not be necessary, it can done via lapply or a for loop
(R/findOS.R:L60)

If I understand it correctly, to use lapply or loop, I need to know about the length of the output (e.g. the number of columns for matN)? Repeat is used because this value can't be decide. Each path connects a root and a leaf of the tree. Different path might pass different number of nodes, and the number of columns is determined by the longest of the path.

Thanks!
Fiona

**Comment by LiNk-NY** [comment]
Hi Fiona, @fionarhuang 

> I am doing updates on my package. Thank you for all your comments. They are very helpful!
Sorry, I didn't ask my question clearly. We would like to have our package included in the 3.8 version of Bioconductor. Would it be possible to allow me some extra days to do the updates based on your comments? I will finish it as soon as possible, hopefully before next Monday.

Unfortunately, it's a little too late to add your package to the release manifest. It will have to go into the devel version of Bioconductor. Special considerations may be taken after the release goes live. But this is not up to me. Please keep in mind that this creates more work for the core team to add your package after the release. 

> R complains that replaceSlots isn't exported by BiocGenerics when creating namespace file.

That's okay. You just have use the triple colons `:::` to get the function. It should really be exported though...

> I am not very clearly about this comment. Does it mean that I should separate it into two functions, one return "label" and one return "number"? Or, I should avoid using switch?

It means you should avoid using "impure" functions. A pure function will return a consistent output.
Avoid using `switch` to change what a function will return. It is better to create two different functions for two different types of outputs. 

> If I understand it correctly, to use lapply or loop, I need to know about the length of the output (e.g. the number of columns for matN)? Repeat is used here because the number of columns can't be determined. Each path connects a root and a leaf of the tree. Different path might pass different number of nodes, and the number of columns is determined by the longest of the path that I can not know in advance.

Can't you use `apply(..., margin = 2)` ? Perhaps Martin @mtmorgan has more insight on the efficiency / downsides of using repeat over a `for` loop or an *apply family function. 

Regards,
Marcel

**Comment by mtmorgan** [comment]
I think we can make an exception to get this package into the release, provided the changes are completed in a timely fashion.

**Comment by fionarhuang** [comment]
Hi Marcel @LiNk-NY,

Thanks a lot for the nice and detailed comments! Now, the package works better than before!
The updates are summarized as below.

> * Please wrap the `Description` field text.
> * If you're extending `SummarizedExperiment`, it would be much easier to put
>   `SummarizedExperiment` package in the `Depends` field.
The description file has been updated as suggested.

> ## vignettes
> * It seems to me that `rowData(..., internal = TRUE)` is something that you
>   should provide in another function. It is better to keep the consistency of
>   what `rowData` does. Otherwise, you can throw your users off by returning
>   data or employing an argument that is not expected by the method.
Now, the `internal` argument is removed from the `rowData` function. The internal part of the row data could be viewed via `topNodes`. The related texts in vignettes are also updated.

> ## R/
> * For the bracket `[` method, it seems like you should have an accessor for the
>   `SummarizedExperiment` data object so that you don't have run the constructor
>   function.
> * You may want to use `BiocGenerics:::replaceSlots` after subsetting rather
>   than reconstructing the object.
The function `[' has been rewritten. Unfortunately, I still have not managed to use `BiocGenerics:::replaceSlots`. (I comment out the code using `BiocGenerics:::replaceSlots` in the file allGenerics.R). Would it be possible for you to kindly help me out about it? Currently, the function `[` works correctly, but I use the constructor to create the object.

> * Look into using `@inheritParams` where possible. It might be better to have
>   the same arguments that the `SummarizedExperiment` constructor function has so
>   that it is clear to the user.
Now, `@inheritParams` is used for the constructors of `leafSummarizedExperiment` and `treeSummarizedExperiment`.

> * I'm not sure to what extent you need the different data sizes but I would
>   consider using just one medium sized dataset for examples.
The semi-simulated AML data sets are removed. As you could see, now there are only three small tree data.

> * Some of the repetitive code can be reduced using conditional logic such as
>   `onlyTip <- level == "leaf"` and then use the same operations for both
>   conditions in `fdr0`, `tpr0`, etc.
The corresponding updates have been made. Now, the argument `level` is changed to `only.Tip`
 as used in other functions.

> * Functions like `findAncestor` are only working on `phylo` trees. I thought
>   you wanted to support functions / methods for your class,
>   `treeSummarizedExperiment`?
This part I am not sure whether I should update it, because currently we plan to have functions, such as findAncestor, findOS, used after the tree aggregation. In other words, users might need them when they want to plot the signal nodes on the tree or get more information about the signal nodes they find. I will think about it and probably discuss it with my supervisors. Thanks for the suggestion!

> * Use names instead of integer positions for subsetting where possible (e.g.,
>   `vec[, "varA"]` vs `vec[, 1]`)
This part is fixed. Now, you might see there are some codes still have something like, mat[, 1]. This is the edge matrix extracted from the phylo object, and there are no column names. 

> * Avoid conditional return values as in `findAncestor`. Please provide functions
>   with a single and consistent output.
Thank you for pointing this out! I have fixed the output so that it would be a numeric vector (the previous output under `return = number`) with names (the previous output under `return = Label`). The same change has been applied to functions, findOS, findSibling, rmDesc, shareNode, signalNode.

> * Repeat may not be necessary, it can done via `lapply` or a `for` loop
>   (`R/findOS.R`:L60)
> * Use helper functions to reduce repetitive code (see `matTree`)
The function findOS has been rewritten and the repetitive code is removed

> * Avoid nested `for` loops, use vectorized operations
I didn't find the nested `for` loops. Probably, they are in the codes that were commented out. Now these codes are removed.

> * Avoid creating methods for classes that are not your own. For methods
>   such as `nodeValue`, use an `ANY` class signature and filter using
>   `is.data.frame` etc.
This is fixed. `ANY` is using now.

> * Combine files into groups of related functions. This makes it easier to find
>   related functions and easier to maintain.
Does this means that I should add a same prefix the file names of functions that are related?
For example, add a prefix such as `tree_` to functions, such as findAncestor and findSibling?

> * Use `seq_len` or `seq_along` to create sequences rather than `seq(1, n)`
This is fixed.

> * Avoid nesting `lapply` calls where possible.
This is fixed.

> * It seems like you're running the same checks over several functions, create
>   a helper functions to standardize those checks across the functions such
>   as `signalNode`
Do this mean the tree data and the nodes I used to test the functions, e.g. findOS, findSibling, 
findAncestor, etc.? For these, the structure of the data or code are manually collected via plot the tree.  I thought about using different functions to do cross check, but not sure whether it's safe. I might make the same mistake in programs to find the nodes.

> * Remove `set.seed` from the inside of function calls
This is done.

> * Remove commented code or provide a working version
This is done.

> * Explicitly set defaults when arguments are `NULL`, for example, in the
>   `addLegend` internal function, you can set `legend.theme = list(NULL)`
>   instead of checking it's `NULL` and then setting it.
This is done.

> Minor:
> 
> * You don't need to set the object into itself (see `findAncestor.R` line 50)
> * Use `is.character` and other `is.*` type checking functions instead of
>   `inherits` (where possible; such as `is.data.frame`, `is.matrix`, etc.)
> * `if (length(x) > 0)` is the same as `if (lenght(x))`
> * Use `methods::is` instead of `inherits` to test S4 classes (`R/selNode.R`)
> * Convention is to add a `.` period in front of a function name (e.g.,
>   `.infLoc`)
All minor are fixed!

Thank you so much for your help and patience!

Regards,
Fiona

**Comment by fionarhuang** [comment]
Hi Martin @mtmorgan,

Thank you very much for allowing me more time! I really appreciate the help!

> I think we can make an exception to get this package into the release, provided the changes are completed in a timely fashion.

Regards,
Fiona

**Comment by fionarhuang** [comment]
Hi Marcel,

Thank you for the help, and nice to meet you in today's meeting! I will come back to do update after we finally decide which part of the codes should go to treeSE.

Ruizhu (Fiona)

**Comment by LiNk-NY** [comment]
Hi Fiona, @fionarhuang 
Nice to meet you as well! 
Please provide updates on the status of the package. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Fiona, @fionarhuang 
Is the package ready? 
I can accept if so. Thanks!
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Fiona, 
Okay, no problem. 
Best regards,
Marcel

**Comment by fionarhuang** [comment]
Hi Marcel @LiNk-NY , 

I discussed with Mark (my supervisor) today. We think it's probably better to put this package in the R devel branch later so that it could be updated based on the package of TreeSummarizedExperiment. I will ask people about the progress of the TreeSummarizedExperiment in the slack.

Fiona

**Comment by fionarhuang** [comment]
Hi Marcel,

Sorry for the delay. At this moment, it is difficult to tell when it will be completed. Probably, it's easier to close this issue. 

Thank you.
Fiona

**Comment by LiNk-NY** [comment]
Hi Fiona, 
Thanks for getting back to me. 
Best regards,
Marcel
