### ISSUE TITLE
Pi

### ISSUE THREAD

**Issue by hfang-bristol** [Bioconductor/Contributions#90]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hfang-bristol/Pi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hfang-bristol** [comment]
This is the submission of a new software package called 'Pi' which is developed as a genomic-led target prioritisation system, with the focus on leveraging genetic data to prioritise targets at the gene, pathway and network level.

**Comment by hfang-bristol** [comment]
Hi @bioc-issue-bot, it seems that 'single package builder' is not triggered automatically?

**Comment by hfang-bristol** [comment]
Thanks. The version incremented.

**Comment by hpages** [comment]
Hi Hai,

Thanks for your submission. The package looks fine. Only 2 minor things concerning the vignette:

1. We strongly advice against documenting how to install R in your vignette. The installation process how you describe it might work out-of-the-box for some users but will fail for many other users. When it fails, the user will be left with no clue of what to do. Also you're providing the instructions for how to install a specific version of R but this will become out-of-sync in a few months unless you remember to update your document on a regular basis. So instead of providing this information, we strongly suggest that you provide the following link instead:

    `http://bioconductor.org/install/#install-R`

2. Also we strongly recommend that BioC users install packages using the standard installation method:
```
    source("http://bioconductor.org/biocLite.R")
    biocLite("Pi")
```
That will take care of installing your package as well as its dependencies once the package is part of Bioconductor. Any other installation method is not supported and can lead to installation problems (we see a lot of those problems on the support site, most of them reported by users that didn't follow the standard method).

Thanks in advance for addressing these points.

Cheers,
H.

**Comment by hfang-bristol** [comment]
Thanks Hpages. Points addressed (see version 0.99.4). Best, Hai

**Comment by hpages** [comment]
Hi Hai,

Thanks for making the changes. The package satisfies our guidelines and will be added to our Subversion repository and build system in the next days. You'll also receive an email with further details about this.

Thanks for contributing to the Bioconductor project.

Regards,
H.

**Comment by hfang-bristol** [comment]
Hi Hpages

Just wonder when SVN will be available for the Pi package.

Thanks,

Hai
