### ISSUE TITLE
mixOmics

### ISSUE THREAD

**Issue by mixOmicsTeam** [Bioconductor/Contributions#900]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mixOmicsTeam/mixOmics

> mixOmics has been on CRAN since 2009 and we finally decided to convert to bioC. It is a big move for us and we are aware that our current submission needs further improvements. We hope to be able to stage some of our developments gradually. The future improvements we envisage in particular are to set up setGeneric and setMethods functions to fit in MultiAssayExperiments. We have not been successful so far and we need more time.
> We hope that mixOmics will benefit the bioC community and attract more users! You can see our engagement and commitment with the computational biology community at www.mixOmics.org

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [see below] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

> Please note the following:
> - R CMD check --as-cran gives 3 NOTES, all OK for bioconductor 
> - R CMD BiocCheck gives:
>   - 1 ERROR (remove package from CRAN as our package still needs to be live on CRAN
>   - 1 WARNING: that we cannot address because it's relative to when we use the `cpus` argument in some of our functions, let me know if there is a work around this
>  - 4 NOTES: those include unit tests and aesthetics of the code. Our package includes > 100 R functions and we are unsure how to implement the unit tests at this stage. We welcome any feedback from you.

             
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
This package is on CRAN; when accepted in Bioconductor it must be removed from CRAN.

**Comment by klecao** [comment]
The biocheck we ran (v1.12) was ok but for some reason the V1.17 breaks down. We dont understand where the error is coming from, we suspect it is something with the vignette but not too sure what it is. Could you please advise as we are in the dark.

```
Error in vapply(vigdircontents, vigHelper, logical(1), builder = desc) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 2
Calls: <Anonymous> ... BiocCheck -> checkVignetteDir -> checkVigBuilder -> vapply
```

Thank you

**Comment by llrs** [comment]
There is an error with the BiocCheck package. But also on your vignette, I copied a fragment from the begining:

```
  %\VignetteIndexEntry{mixOmics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  
bibliography: ["mybib.bib"]
biblio-style: apalike
link-citations: true
  
header-includes:
  - \usepackage{color}
---

<!--
  %% \VignetteEngine{knitr::knitr}
-->

```

It has two `\VignetteEngine` which are different, one is knitr::knitr and the other knitr::rmarkdown, there should be only one.

**Comment by mixOmicsTeam** [comment]
Hi bioC team, we would need advice on the following:
```
     * ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 6.5165 MB
        Size Requirement: 4.0000 MB
```
Our package includes many case studies as we try to give real examples for each method in our toolkit. Could you please advise how we could work around this?

The warnings from the check have been fixed and pushed.

**Comment by llrs** [comment]
To trigger another build you need to increment de version number.

To reduce the size of the package the usual route is to remove the vignette.html and to move the data to a specific data package linked to the software package.

**Comment by mixOmicsTeam** [comment]
We have incremented the version number.

We had already removed the vignette.html
We would prefer at this stage not to create a specific software package for the data, and discuss with our reviewer directly @Liubuntu

**Comment by Liubuntu** [comment]
Hi @mixOmicsTeam , 

Thank you for your submission. But please remember to remove it from CRAN before we can accept it to Bioc. Also follow this link to [add a web hook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that it could trigger a new build. A technical review will be give shortly. Thanks!

Cheers,
Qian

**Comment by llrs** [comment]
Sorry if my comments weren't helpful. As a user of mixOmics I am excited to see the package coming to Bioconductor. I was only trying to help you with the process. 

I want to offer my help regarding the unit tests. One good point to start with is conerting the examples into tests. I would recommend to add tests using testthat. If you want I could submit a pull request.

**Comment by mixOmicsTeam** [comment]
Hi Lluis,

Thanks for your support/help :)
We already have all our examples as tests (and some more, https://github.com/mixOmicsTeam/mixOmics-CRAN/tree/master/running_scripts); we run them everytime to make sure the package is not broken, but it does not check for consistency between version, just that the code runs without errors.
I'm not sure how to make tests using testthat (from what I saw the examples are quite simple) without saving a lot of mixOmics objects of the previous version and checking that the new versions give the same objects/outputs..

Best,
--
Dr. Florian Rohart
Research Fellow - Applied Statistician
Course coordinator

Institute for Molecular Bioscience
The University of Queensland
St Lucia, Brisbane, QLD 4072
http://florian.rohart.free.fr/
http://www.flickr.com/frohart/<https://www.flickr.com/photos/119717703@N02/>

On 10 Oct 2018, at 3:06 am, Lluís <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry if my comments weren't helpful. As a user of mixOmics I am excited to see the package coming to Bioconductor. I was only trying to help you with the process.

I want to offer my help regarding the unit tests. One good point to start with is conerting the examples into tests. I would recommend to add tests using testthat. If you want I could submit a pull request.

**Comment by Liubuntu** [comment]
Hi @mixOmicsTeam , 

I am looking at the package already and will talk with the other team members about the situation. For now, the ERROR would not prevent the review process. 

Best,
Qian

**Comment by Liubuntu** [comment]
For the unzipped tarball, vignette.html is 6.3 MB and the data/ repo is 3.0MB. 

Will talk with the core team about the possibility to size down the vignette without reducing the figures... 

The other way to size down is to write a data package for all the data, and have the current software package "Depends" on the data package. [Here](https://bioconductor.org/packages/3.7/data/experiment/) is the link to the current "ExperimentData package", follow the general [rules](http://bioconductor.org/developers/package-guidelines/) of package developing. could leave empty. Need to have DESCRIPTION, vignette, man/ with runnable examples and help page documentation. 

Will see which is easier and let you updated!

Also Please fix this ERROR: 

> * Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

## vignette. a quick glance of the vignette suggest the following issue: 

- "Installation" section should not use the biocLite any more since it has been updated to be "BiocManager". Write the following:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
 BiocManager::install("pkgName")

 Or install the development version of the package from Github.

 {r, eval = FALSE}
  BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.

{r Load, message=FALSE}
 library(pkgName)
```

Best,
Qian

**Comment by Liubuntu** [comment]
Continued: 

## NAMESPACE

- Looks good!

## R

- There should be no installing or loading of any packages inside the package. See the following WARNING message on build report.

> * Checking for library/require of mixOmics...
        * WARNING: The following files call library or require on mixOmics.
              This is not necessary. R/MCV.block.splsda.R, R/perf.R,
                        R/tune.block.splsda.R, R/tune.spls.R, R/tune.splsda.R

[Formatting](http://bioconductor.org/developers/package-guidelines/):
- Please avoid using "1:...", and use `seq_len()` or `seq_along()`.
- Avoid `sapply()`, use `vapply()` instead to be more robust.
- use "<- " for assignment instead of "=".
- avoid long lines, and multiples of 4 spaces for line indents. (See building report)

## man

- Looks good!

**Comment by mixOmicsTeam** [comment]
Hi Qian,

Regarding this warning: it comes from the fact that we're using `parallel' to set up some parallel computing, and we send the mixOmics package to the remote clusters so that the code runs; hence some
>        clusterEvalQ(cl, library(mixOmics))

I'm not too sure how we can avoid that properly.
Do you have any suggestions?

Thanks

Best,
--
Dr. Florian Rohart
Research Fellow - Applied Statistician
Course coordinator

Institute for Molecular Bioscience
The University of Queensland
St Lucia, Brisbane, QLD 4072
http://florian.rohart.free.fr/
http://www.flickr.com/frohart/<https://www.flickr.com/photos/119717703@N02/>

On 12 Oct 2018, at 5:57 am, Qian Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


Continued:

NAMESPACE

  *   Looks good!

R

  *   There should be no installing or loading of any packages inside the package. See the following WARNING message on build report.

  *   Checking for library/require of mixOmics...
* WARNING: The following files call library or require on mixOmics.
This is not necessary. R/MCV.block.splsda.R, R/perf.R,
R/tune.block.splsda.R, R/tune.spls.R, R/tune.splsda.R

Formatting<http://bioconductor.org/developers/package-guidelines/>:

  *   Please avoid using "1:...", and use seq_len() or seq_along().
  *   Avoid sapply(), use vapply() instead to be more robust.
  *   use "<- " for assignment instead of "=".
  *   avoid long lines, and multiples of 4 spaces for line indents. (See building report)

man

  *   Looks good!

**Comment by Liubuntu** [comment]
Hi @mixOmicsTeam , 

I'm not expert in using `clusterEvalQ`... and didn't get any input until now. I understand that you are using parallel when passing the "ncpu" argument, But is it necessary to run the "library(mixOmics) for each of the cluster? In other words, do you want to try to remove this line```clusterEvalQ(cl, library(mixOmics))``` from your scripts and see will the package work fine still? Thanks!

Best,
Qian

**Comment by frohart** [comment]
Hi @Liubuntu ,
`clusterEvalQ(cl, library(mixOmics))` is actually needed when using the package on HPC (it would work without it on a single machine, but not on a HPC).
I guess we could try to replace `clusterEvalQ(cl, library(mixOmics))` by passing every single functions of mixOmics used on the clusters, but that would make a mess compared to the simple `library(mixOmics)`. Any good reasons why it's not good practice to do `clusterEvalQ(cl, library(mixOmics))` ?
Thanks

**Comment by Liubuntu** [comment]
Hi, 

Thank you for your explaining on the difference in using HPC and single machine. If that is the case, we'll just pass it. The WARNING comes from BiocCheck, which checks for the keyword `library()/require()`... because in normal case, the package loading is not allowed and they should go to `Depends/Imports/Suggests...` in DESCRIPTION. As long as it's needed for functioning of this package, an exception could be made here.

Best,
Qian

**Comment by Liubuntu** [comment]
Also please let me know if you have questions about the above review. Basically they are about coding styles for the `R/` section. Those are based on the [Bioconductor guidelines](https://bioconductor.org/developers/how-to/coding-style/). While they would not directly affect the package acceptance, but are preferences that we would strongly encourage. 

The issue about the `vignette` is important and must be addressed! 

Thanks,
Qian

**Comment by Liubuntu** [comment]
Hi, 

Thank you for making those changes and adding unit tests. Please correct the following: 

## vignette
- Please replace "pkgName" with "mixOmics" for the "Installation" section. (L216, L221)

The other looks good, and a progressive changes for the coding style sounds ok. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @mixOmicsTeam , 

Seems that you have made the changes to vignette. But please make a version bump so that the daily build could catch that. As soon as you bump the version, we are good to go. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @mixOmicsTeam , 

Sorry, one last thing to do. You need to remove `mixOmics` from CRAN before we could accept it to Bioconductor. Thanks!

Best,
Qian

**Comment by mixOmicsTeam** [comment]
@Liubuntu we have requested the archival of the R CRAN package and awaiting confirmation. We'll let you know when this is done. Thanks!

**Comment by mixOmicsTeam** [comment]
@Liubuntu see the following answer from the R CRAN team, could you please advise?

>  mixOmics does not seem to be established in BioC release yet.
> As long as that is not the case, it is advisable to double host it, e.g. with some version number on CRAN and a higher version number on BioC. Note that otherwise your reverse dependencies on CRAN
> 
> Reverse depends: 	bootsPLS, mixKernel, sgPLS, YuGene
> Reverse imports: 	MetabolomicsBasics, PCA4you, plsRcox, polyPK, RVAideMemoire
> Reverse suggests: 	PLSbiplot1
> 
> will break if mixOmics is no longer available from any repository for R release and older evrsions of R

.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mixOmicsTeam.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"mixOmics\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mixOmics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mixOmicsTeam** [comment]
Hi there,
Just a quick follow up question: when we do modifications to the package, which branch of bioconductor should we push them on? master? RELEASE_3_8? If we do modifications on our own github, are they taking into account somehow or only the ones we push to the bioconductor github repo?
Thanks!

**Comment by llrs** [comment]
See section "Where to commit changes" on this [help page](https://bioconductor.org/developers/how-to/git/) linked above. Usually the new developments go the development branch and bug fixes to the development branch (and to the RELEASE branch). 

The modifications on the github repository aren't pulled into Bioconductor repository. See this [help file ](https://bioconductor.org/developers/how-to/git/new-package-workflow/) about how to set them. Basically you'll need to set a remote repository to bioconductor.org and pull from there (to get the version bump performed by the Bioconductor team) and push to add the new changes to Bioconductor.
