### ISSUE TITLE
levi 

### ISSUE THREAD

**Issue by jrybarczyk** [Bioconductor/Contributions#901]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jrybarczyk/levi

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Here is a review of your package. It looks very interesting and I have a few issues that need to be addressed. [REQUIRED] tags must involve making the change or a response. [CONSIDER] tags are changes that are advisable but not required. Please message me back when you are finished making changes.

GENERAL
- [CONSIDER] Be specific with `param` and `return` values in the `roxygen2`
headers. For example, in `levi.R`:L37 I have no idea what `networkNodesInput`
means, and a user probably wouldn't either. Maybe the arugment requires a
`character(1)` of `numeric(1)` as input but it isn't clear. It is best to be
as clear as possible to the user with your documentation.

R/LEVIui.R
- [REQUIRED] L22-30: This try-catch statement seems odd. The error message
suggests that it is justs check whether `browser` is `logical`. Try-catch loops
are normally used to catch problems that occur within the funciton functions
being called within the statment. It would make more sense to just rewrite this
as:
```
if (!is(browser, "logical"))
    stop("'browser' must be a TRUE or FALSE')
if (browser) {
    shiny::runApp(system.file("shiny",package="levi"),
    launch.browser = TRUE)
} else {
    shiny::runApp(system.file("shiny",package="levi"))
}
```

R/levi.R
- [REQUIRED] Use `match.arg()` to verify user input to "multiple-choice" inputs.
For example, on L59 `setColor` can have inputs as default, terrain, rainbow,
heat, topo or cm. You can write in the function declaration
`setColor = c("default", "terrain", "rainbow", "heat", "topo", "cm")`. `default`
will still be the default argument. In the function you can then call
`setColor <- match.arg(setColor)` to obtain the user's input. It will throw an
error if the user uses a choice that isn't availiable. This is the prefered way
of doing this and it seems it can be used in multiple places in your package.

R/levi_funcion.R
- [REQUIRED] L1-27: This block looks awkward and it's if-else statements are
overly complex. Just do:
```
defaultColors <- function(n) {
    c("#180052", "#0c0083","#0000b4",
    "#0000e4","#0010ff", "#0041ff", "#0072ff", "#00A3FF", "#00D4FF",
    "#00FF49","#5AFF00", "#FFE400", "#FFC400", "#FFA300", "#FF8300",
    "#FF6200", "#FF4100", "#FF2100", "#FF0000", "#E40000")
}

color_list <- list(
    default = defaultColors,
    terrain = terrain.colors,
    rainbow = rainbow,
    heat = heat.colors,
    topo = topo.colors,
    cm = cm.colors
)

colorSet <- color_list[[setColor]](20)
```
The code at L7,26-27 can be removed since the `match.arg()` call already will
verify the user's input from `levi()`.
- [REQUIRED] A lot of this function seems dedicated to checking for bad input.
From what I can see, `levi_function()` can only be invokded by the user through
`levi()`. First off you can avoid a lot of `missing(value)` error check by
providing a default value in the `levi()` function statement, e.g.
`levi(..., expressionLog = FALSE, ...)` will always make it so `expressionLog`
has a default value, in this case `FALSE`. This seems appropriate for a lot of
these arguments.
- [REQUIRED] L91-354: This contains a lot of misused try-catch statments.
I'm actually not clear what any of these statements are actually trying to
"catch". Maybe they are just there to check whether the file format corresponds
to the file type. However, to do this, it would be better to only encapsulate
the `read.delim` in the try-catch statement. Encapsulating so much means that
*anything* that goes wrong will be attributed to "Incorrect file format (dyn)"
when it may not be. But this could still be incorrect since other errors may go
wrong with the `read.delim` function that may be better to just have
`read.delim` throw the error. So it might be better to just remove the try-catch
statements and assume that the user knows the file is in the correct format.
Also, if `match.arg()` is used in `levi()` to verify `fileType`, error checking
may not be necessary here.
- [REQUIRED] L546-551: Replace inefficient double for-loop with:
```
i <- seq_len(n)
b <- max(matrixOutExp[i, i+1])
c <- max(matrixOutCtrl[i, i+1])
```
- [REQUIRED] L553-564: Replace inefficient double for-loop with:
```
matrixOutExp[i, i+1] <- matrixOutExp[i, i+1]/b
matrixOutCtrl[i, i+1] <- matrixOutCtrl[i, i+1]/c

ExpCtrl <- MatrixOut[i, rev(i)]
exp <- matrixOutExp[i, rev(i)]
ctrl <- matrixOutCtrl[i, rev(i)]
```
L539-541 can be removed after this is done.
- [REQUIRED] L643: Would it be better to return the `ggplot` object instead of
just a printed out image that the user cannot manipulate? Or does the package
require the output to just be an image?

**Comment by jrybarczyk** [comment]
@dvantwisk , thanks for the review. We made the changes that  you requested.

>     * [REQUIRED] L643: Would it be better to return the `ggplot` object instead of
>       just a printed out image that the user cannot manipulate? Or does the package
>       require the output to just be an image?

We believe the best output is an image instead of an object.
The user can produce this image in two ways: via script or shiny app. 
We can implement the output as ggplot object in future versions if the users demonstrate interest.

Thank you
José Luiz

**Comment by jrybarczyk** [comment]
@dvantwisk , thanks again,  We made the changes that you requested.
> The changes look pretty good so far. Just a few more things:
> 
> * R/levi_function.R:L261-302 I don't understand the purpose of this try-catch statement. It encapsulates sections of code that may not throw an error relevant to "Incorrect Expression file of Gene Symbol". I'm not sure where this warning/error message is actually applicable, maybe around the `read.delim()` method call at L264, but there are other reasons why that call to `read.delim()` may fail that you message doesn't describe. And if there is  a failure here, it seems that the program will continue running. This doesn't seem like the functionality you want here. It may be best to use an if-statement test in conjunction with `stop()` to check if there are any issues with Gene Symbols. You could probably assume that the user is using a correct Expression file and allow `read.delim()` to throw and error if there is an issue reading it.
We forgot one try-cath statement, sorry. Now I'm assuming that the user is using a correct file. 

> * GENERAL: For diagnostic messages, its best to use `message()` instead of `print()` since `message()` can be toggled off. `warning()` may be appropriate in other locations. One odd place is R/levi_function.R:L381. The `print()` statement here seems to make more sense as a `warning()`. It may be worth it to look through the package to make sure messages to users are `message()`, `warning()`, or `error()`.

I replaced the print() by message(),warning() and error()

thanks 
José Luiz

**Comment by dvantwisk** [comment]
Alright, things look good now. I'm going to move to accept the package.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jrybarczyk.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"levi\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/levi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
