### ISSUE TITLE
universalmotif

### ISSUE THREAD

**Issue by bjmt** [Bioconductor/Contributions#903]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bjmt/universalmotif

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by bjmt** [comment]
Dear reviewer (@lshep),

I would like to ask for guidance regarding my build results.

For the build warning:
```
* creating vignettes ... OK
Warning: 'inst/doc' file
    'IntroductionToSequenceMotifs.R'
  ignored as vignettes have been rebuilt.
  Run R CMD build with --no-build-vignettes to prevent rebuilding.
```

There is no 'IntroductionToSequenceMotifs.R' file in the github repository. Just as for all the other vignettes, this file is created during vignette building, and ends up in 'inst/doc'; so I have no idea why this is triggering a warning. Regardless, the final built .tar.gz file doesn't have any incorrect files in 'inst/doc', so would it be okay to assume this warning is harmless?

For the windows error:
The windows build system seems very unhappy with a lot my C++ code. However, I am unsure whether this is truly due to bad code (which I don't doubt is possible) or specific to the build system itself; indeed, everything seems fine when the package is built and checked on appveyor.

On a final note, building the binary is skipped on linux but there is no feedback as to why.

Thank you for taking the time to review my package. I would appreciate any guidance you would be willing to offer.

**Comment by lshep** [comment]
@bjmt I'm switching review to @hpages -  He has more C expertise and could better assist with your package.  Cheers

**Comment by dvantwisk** [comment]
I apologize for the delay with reviewing your package. I took the review from Herve since many members of our group are very busy preparing for the Bioconductor 3.8 release. Here is my review. Your package looks expertly written and I have only a few issues. [REQUIRED] tags are changes that must be made or addressed. [CONSIDER] tags are changes that are advisable but not necessary.

I've found many of my recommended changes involve using `lapply()` or `vapply()` in place of instantiating a variable using a for-loop. The method you tended to use was declaring the length of a list or vector and then filling it with the for-loop. This is slightly less efficient than using `lapply()` or `vapply()`.  However, you do make liberal use of these two functions thoughout your package, so perhaps there are reasons you opted for the for-loop method.

Please message me back when you are done making changes. We will still be able to include your package in the 3.8 release as long as you quickly address this review.

R/GENERAL:
- [CONSIDER] Use `match.arg()`. For example in `add_multifreq.R`L67: The
`threshold.type` argument can be given as
`threshold.type = c('logodds', 'pvalue')`. The default argument is the first
element of the vector. The value that the user selects can be obtained using
`threshold.type <- match.arg(threshold.type)` in the function call. Doing
this explicitly tells the user what arguments are accepted when displaying the
function using `add_multifreq`. It also throws an error if the user gives an
input other than the two specified arguments. This could be implmeneted in
multiple other places throughout the package.

R/add_multifreq.R
- [CONSIDER] L120-133: Use `lapply()` to declare `multifreq`. This is more
efficient than declaring `multifreq` and then iterately adding to it with a
for-loop.

R/compare_motifs.R
- [CONSIDER] L231-251: Use `lapply()` to declare `comparisons` and `pvals`.
- [REQUIRED] L337-339: Use `diag()` to get and set matrix diagonals:
```
diag(comparions) <- mot.lens^2
```
- [CONSIDER] L354-357: Use `vapply()` to declare `comparisons.sorted`.

R/data.R
- [CONSIDER] It's not entirely clear what the source and structure of this data
is. Please add more documentation to make this clear to the user.

R/enrich_motifs.R
- [CONSIDER] L327-331: Use `lapply()` to declare `results.sep`.

R/scan_sequences.R
- [CONSIDER] L305-313: Use `lapply()` to declare `res`.
- [CONSIDER] L322-330: Use `lapply()` to declare `res.rc`.

R/shuffle_motifs.R
- [CONSIDER] L77-80: Use `lapply()` to declare `new.mats`.

**Comment by dvantwisk** [comment]
Also with regards to the issues that the package still has on the build report, I think all of them come from our system. Tying to build them independently on our platforms yielded no errors, so those can be ignored.

**Comment by bjmt** [comment]
Dear @dvantwisk,

Thank you for taking the time to review my package and provide feedback. Glad to know I can ignore the windows errors.

Regarding the use of for loops vs `lapply`/`vapply`:

Frankly my reason using for loops is simply code legibility (for myself), and I acknowledge that `vapply`/`lapply` are generally preferred. To this end I have converted some of the simpler loops you mention to use these. That being said, I've left some of these for loops intact; reason being that these are a bit more complex, and as result i) I would prefer to keep these for code legibility (for myself) and ii) I don't believe it would be worth the time investment. I've made an effort to use C++ code for the slowest parts, and I don't think that overall the current for loops contribute much in terms of function (in)efficiency.

> R/GENERAL:
> [CONSIDER] Use match.arg(). For example in add_multifreq.RL67: The
> threshold.type argument can be given as
> threshold.type = c('logodds', 'pvalue'). The default argument is the first
> element of the vector. The value that the user selects can be obtained using
> threshold.type <- match.arg(threshold.type) in the function call. Doing
> this explicitly tells the user what arguments are accepted when displaying the
> function using add_multifreq. It also throws an error if the user gives an
> input other than the two specified arguments. This could be implmeneted in
> multiple other places throughout the package.

I must admit I didn't know about this, but it certainly seems like it would be a straightforward improvement. I wish I had known this before I implemented my own parameter checks. However this would take a bit more time than the other recommended changes, and out of a desire to get in the 3.8 release I will leave it as is for now (I am assuming taking the weekend to make these changes would take me past the deadline). I certainly do plan on performing this change, but with my current schedule I would rather not risk losing out on the 3.8 release.

> R/add_multifreq.R
> [CONSIDER] L120-133: Use lapply() to declare multifreq. This is more
> efficient than declaring multifreq and then iterately adding to it with a
> for-loop.

Done.

> R/compare_motifs.R
> [CONSIDER] L231-251: Use lapply() to declare comparisons and pvals.

I will be keeping the loop here, for reasons discussed previously.

> [REQUIRED] L337-339: Use diag() to get and set matrix diagonals:
> diag(comparions) <- mot.lens^2

Done.

> [CONSIDER] L354-357: Use vapply() to declare comparisons.sorted.

Done.

> R/data.R
> [CONSIDER] It's not entirely clear what the source and structure of this data
> is. Please add more documentation to make this clear to the user.

Done.

> R/enrich_motifs.R
> [CONSIDER] L327-331: Use lapply() to declare results.sep.

Done.

> R/scan_sequences.R
> [CONSIDER] L305-313: Use lapply() to declare res.

I will be keeping the loop here, for reasons discussed previously.

> [CONSIDER] L322-330: Use lapply() to declare res.rc.

I will be keeping the loop here, for reasons discussed previously.

> R/shuffle_motifs.R
> [CONSIDER] L77-80: Use lapply() to declare new.mats.

Done.

**Comment by bjmt** [comment]
The windows error is quite a bit different this time around, is it still safe to ignore? I don't think I've done anything to change the way the vignettes are built.

**Comment by dvantwisk** [comment]
All the changes that you've made have been good. With regards to the windows error, I've looked at the issue over the weekend and can still find no reason to believe why it would be your code that is causing this issue. I'm going to accept your package now. Please keep in contact via email in case we find a reason why it is failing and we need you to correct something.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bjmt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"universalmotif\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/universalmotif

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by bjmt** [comment]
@dvantwisk 

You are likely the wrong person to be asking this to, but when I try to activate my account on https://git.bioconductor.org/BiocCredentials/account_activation/ I always run into 'Server Error (500)'. Do you know how I can get around this? Or if not, who may I ask to help me with this? I'm sorry for the trouble.

Thank you.

**Comment by vobencha** [comment]
@bjmt these questions should be asked on the bioc-devel mailing list.

**Comment by vobencha** [comment]
I think I see your account creation in the logs. I believe your email is b2tremblay@uwaterloo.ca. We hit a bug in the app during account creation which left it in a broken state. This has been fixed and you should have access now. 

Sorry for the inconvenience - let me know if you still have problems.
Valerie

**Comment by bjmt** [comment]
Sorry for not asking the bioc-devel mailing list, I'll remember to do that from now on.

Thanks for looking into it, everything works correctly now.
