### ISSUE TITLE
abseqR

### ISSUE THREAD

**Issue by jiahfong** [Bioconductor/Contributions#905]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/malhamdoosh/abseqR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jiahfong** [comment]
It seems like the error from macOS is similar to [this](https://github.com/Bioconductor/BiocParallel/issues/61).
I tried setting `options(bphost="localhost")` in both vignette and R source (before calling `bplapply`) but it gave the same error.

By default, `abseqR` uses ` BPPARAM <- BiocParallel::bpparam()` if the user doesn't specify one. If I use `SerialParam` on macOS, the error goes away. I can mitigate this error by checking if the OS is mac and use Serial instead of bpparam but I was wondering if there's a better solution?

Your thoughts are much appreciated.

Regards,
Harry.

**Comment by nturaga** [comment]
Hi @jiahfong ,

Without passing the build report, I cannot review your package. Please make sure the build report is as clean as possible with no ERRORs, WARNINGs and NOTE messages (i'm particular about the efficient coding style NOTE messages).

Once you have made changes, bump the `z` in your version number (`x.y.z`). This will trigger a new build. 

Best,

Nitesh

**Comment by jiahfong** [comment]
Hi @nturaga,

The build passes on all OSes except for macOS.
It seems like the error from macOS is similar to [this](https://github.com/Bioconductor/BiocParallel/issues/61).
I tried setting `options(bphost="localhost")` in both vignette (in the setup chunk) and R source (before calling bplapply) but it gave the same error.

By default, abseqR uses `BiocParallel::bpparam()` if the user doesn't specify one. If I use `SerialParam` or `BiocParallel::MulticoreParam(1)` on macOS, the error goes away. I can mitigate this error by checking if the OS is mac and use `Serial` instead of `BiocParallel::bpparam()` but I was wondering if there's a better solution?

Your thoughts are much appreciated.

Regards,
Harry.

**Comment by nturaga** [comment]
Thats fine @jiahfong. I'll take a closer look at it, but that appears a decent solution.

**Comment by nturaga** [comment]
# abseqR review

## DESCRIPTION

ok

## NAMESPACE

ok

## data

You can host the `images` folder in the `man/figures` folder
instead. Check
https://cran.r-project.org/web/packages/Rdpack/vignettes/Inserting_figures_and_evaluated_examples.pdf

## inst

* ok

## man

* ok

## vignette

* Good and informative vignette! 

## R

* Accessors (simple functions that return components of your object)
  rather than direct slot access (using @) help to isolate the
  implementation of your class from its interface. Generally @ should
  only be used in an accessor, all other code should use the
  accessor. The accessor does not need to be exported from the class
  if the user has no need or business accessing parts of your data
  object. Plain-old-functions (rather than generic + method) are often
  sufficient for accessors; it’s often useful to employ (consistently)
  a lightweight name mangling scheme (e.g., starting the accessor
  method name with a 2 or 3 letter acronym for your package) to avoid
  name collisions between similarly named functions in other packages.
  
  
  There is the use of `@` in multiple locations in your
  codebase. Please fix them all.


* Make sure all your `paste` functions are required within the
  `message`, `stop` and `warning` calls. Some of them don't require
  `paste` as the values being passed are not vectors, i.e there is no
  recycling of the operation.
  

# General 

The package is well written and documented. 

One way to further improve this package is the author considers writing some unit tests, since it's such an extensive code base. This will make the package more robust.

**Comment by jiahfong** [comment]
Hi @nturaga 

Thank you very much for your suggestions, here are the fixes:

# data
> You can host the images folder in the man/figures folder instead

The images in this folder were removed as they're already generated within the vignette. Instead, we've opted to display a GIF that better illustrates the reporting capability of `abseqR` in the README.

# R

## Accessors
> Accessors (simple functions that return components of your object)
rather than direct slot access (using @) help to isolate the
implementation of your class from its interface. Generally @ should
only be used in an accessor, all other code should use the
accessor. The accessor does not need to be exported from the class
if the user has no need or business accessing parts of your data
object. Plain-old-functions (rather than generic + method) are often
sufficient for accessors; it’s often useful to employ (consistently)
a lightweight name mangling scheme (e.g., starting the accessor
method name with a 2 or 3 letter acronym for your package) to avoid
name collisions between similarly named functions in other packages.

All instances of `@` were removed throughout the codebase and replaced with accessors that are _not_ exported (they are `.` prefixed and has name mangling as suggested).

## Redundant `paste`

> Make sure all your paste functions are required within the
message, stop and warning calls. Some of them don't require
paste as the values being passed are not vectors, i.e there is no
recycling of the operation.

Redundant `paste`s were removed in all `message`, `warning`, and `stop` function calls.

## Unit tests

> One way to further improve this package is the author considers writing some unit tests, since it's such an extensive code base. This will make the package more robust.

We have added unit tests in `abseqR`, starting with all the publicly exported functions.

**Comment by jiahfong** [comment]
Hi @nturaga 

Thank you very much for your suggestions, here are the fixes:

# data
> You can host the images folder in the man/figures folder instead

Done.

# R

## Accessors
> Accessors (simple functions that return components of your object)
rather than direct slot access (using @) help to isolate the
implementation of your class from its interface. Generally @ should
only be used in an accessor, all other code should use the
accessor. The accessor does not need to be exported from the class
if the user has no need or business accessing parts of your data
object. Plain-old-functions (rather than generic + method) are often
sufficient for accessors; it’s often useful to employ (consistently)
a lightweight name mangling scheme (e.g., starting the accessor
method name with a 2 or 3 letter acronym for your package) to avoid
name collisions between similarly named functions in other packages.

All instances of `@` were removed throughout the codebase and replaced with accessors.

## Redundant `paste`

> Make sure all your paste functions are required within the
message, stop and warning calls. Some of them don't require
paste as the values being passed are not vectors, i.e there is no
recycling of the operation.

Redundant `paste`s were removed in all `message`, `warning`, and `stop` function calls.

## Unit tests

> One way to further improve this package is the author considers writing some unit tests, since it's such an extensive code base. This will make the package more robust.

We have added unit tests in `abseqR`, starting with all the publicly exported functions.

Best regards,
Harry

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jiahfong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"abseqR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/abseqR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
