### ISSUE TITLE
ADAM

### ISSUE THREAD

**Issue by jrybarczyk** [Bioconductor/Contributions#908]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jrybarczyk/ADAM

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi @jrybarczyk 
Thank you for submitting to Bioconductor.
Please see your review below.
If you have any questions, please post them as comments in the 
issue thread. 

Regards,
Marcel

---

# ADAM #908

* ADAM seems to have two aims, analysis and shiny representation. Please
separate functionality into two different packages.

## DESCRIPTION

* Future note: If you have many dependencies for one package, list the package
in the `Depends` field

## NAMESPACE

* You have two groups of functions that are exported. Separate these into two
packages.

## vignettes/

* Avoid using `eval=FALSE` chunk options. Provide a small dataset to demonstrate
your package functionality
* Include a `sessionInfo` at the end of the vignette

## R/

* Avoid using numeric indices for data extraction, use names for robustness.
* Provide support for Bioconductor classes such as `SummarizedExperiment`
for the `ExpressionData` argument.
* Use argument defaults for exported functions, this makes it easier for the
user to use your functions.
* Use `rbind.data.frame` method to get a `data.frame` back when binding
from samples rather than coercing to `data.frame` after binding.
* The series of checks could be part of the validity checks for a class in
the package (`checkComparisonID`, `checkExpressionData`, etc.)
* Please correct spelling errors `datra.frame`, `at list 3 columns`, etc.
* Avoid using `1:ncol(x)` sequence generation, use the more robust `seq_len(x)`
* Avoid `ifelse` statements when you can just take the sum of the conditional
statement. For example,
`if(sum(ifelse(ExpressionColumns==TRUE,1,0))!=(ncol(DataFile)-1))` can be
`if (sum(ExpressionColumns) != (ncol(DataFile)-1))`
* Use `vapply` when reducing a list to a logical vector (R/checks.R:Line41)
* Consider using a table (`data.frame`) to map `db` packages to `genus
species` names. You may also want to consider using `BiocManager::available`
for package lookup instead of said `data.frame` map.
* Avoid the use of short and undescriptive variable names in all functions,
for example, use `SpeciesID` instead of `y` and `ExpressionData` instead of `k`.
* There should be no need to hard-code 'org.*.db' packages as these can be
looked up and loaded.
* Again, the sum of a logical vector is equal to the number of `TRUE` values in
the logical vector, avoid `ifelse` for this purpose.
* The `gc()` in R will take care of any stray datasets left behind, you don't
need to run `rm(objectNAME)` AFAIK
* Avoid installing packages for the user. Remove `BiocManager::install` in
line `R/checks.R:Line-304`. If the package is not available for the user
(checked with `requireNamespace`) then produce an error and inform the user to
install the package.
* Avoid using `sapply`, see Bioconductor package guidelines:
http://www.bioconductor.org/developers/package-guidelines/
* Use `ECGPreprocess` as your constructor function. Rename it to `ECGMainData`,
run your checks on the arguments and then call `new` at the end.
* Unexported functions have the convention of a `.` (dot) in front of the name.
* Create accessor and setter functions for your class, for example,
`expressionData(ECGMainData)` `expressionData(ECGMainData) <- newData`

Minor
* `c(1)` is the same as `1`

## tests/

* Add more tests to increase package robustness

## data/

* I don't think `AvailableDBSpecies` is required as we have a lookup function
in `BiocManager::available`.
* Consider using one set of datasets for either humans or 'Aedes aegypti' for
your examples, not both. This will reduce the storage required for your package.

## R CMD check results

```
Undefined global functions or variables:
  GOID Ontology Term mappedkeys
```

**Comment by jrybarczyk** [comment]
@LiNk-NY thanks for the review of the package. Your requirements and suggestions really improved our package.

>  ADAM #908
> ADAM seems to have two aims, analysis and shiny representation. Please
>   separate functionality into two different packages.

We separated the ADAM in two different packages. Now, we are submitting only the statistical module (without shiny app) 

> ## DESCRIPTION
> * Future note: If you have many dependencies for one package, list the package
>   in the `Depends` field

Done.

> ## NAMESPACE
> * You have two groups of functions that are exported. Separate these into two
>   packages.

Done.

> ## vignettes/
> * Avoid using `eval=FALSE` chunk options. Provide a small dataset to demonstrate
>   your package functionality

Done.

> * Include a `sessionInfo` at the end of the vignette

Done.
 
> ## R/
> * Avoid using numeric indices for data extraction, use names for robustness.

Now, we are using the column names.

> * Provide support for Bioconductor classes such as `SummarizedExperiment`
>   for the `ExpressionData` argument.

We implemented support for "SummarizedExperiment" class

> * Use argument defaults for exported functions, this makes it easier for the
>   user to use your functions.

We have setted default values when it was possible.

> * Use `rbind.data.frame` method to get a `data.frame` back when binding
>   from samples rather than coercing to `data.frame` after binding.

In two cases weren't possible to implement the modifications (lines 47, 112-116) in PackageFunctions.R file. 

> * The series of checks could be part of the validity checks for a class in
>   the package (`checkComparisonID`, `checkExpressionData`, etc.)

We could not implement the suggested modifications because many of our check functions perform data filtering, extraction and transformantion steps and the validity checks you suggested does not allow to do these steps.

> * Please correct spelling errors `datra.frame`, `at list 3 columns`, etc.

Done.

> * Avoid using `1:ncol(x)` sequence generation, use the more robust `seq_len(x)`

Done.

> * Avoid `ifelse` statements when you can just take the sum of the conditional
>   statement. For example,
>   `if(sum(ifelse(ExpressionColumns==TRUE,1,0))!=(ncol(DataFile)-1))` can be
>   `if (sum(ExpressionColumns) != (ncol(DataFile)-1))`

Done.

> * Use `vapply` when reducing a list to a logical vector (R/checks.R:Line41)

Done.

> * Consider using a table (`data.frame`) to map `db` packages to `genus species` names. You may also want to consider using `BiocManager::available`
>   for package lookup instead of said `data.frame` map.

Done. However, I didn't use BiocManager::available.

> * Avoid the use of short and undescriptive variable names in all functions,
>   for example, use `SpeciesID` instead of `y` and `ExpressionData` instead of `k`.

Done.

> * There should be no need to hard-code 'org.*.db' packages as these can be
>   looked up and loaded.

Done.

> * Again, the sum of a logical vector is equal to the number of `TRUE` values in
>   the logical vector, avoid `ifelse` for this purpose.

Done.

> * The `gc()` in R will take care of any stray datasets left behind, you don't
>   need to run `rm(objectNAME)` AFAIK

Done.

> * Avoid installing packages for the user. Remove `BiocManager::install` in
>   line `R/checks.R:Line-304`. If the package is not available for the user
>   (checked with `requireNamespace`) then produce an error and inform the user to
>   install the package.

Done.

> * Avoid using `sapply`, see Bioconductor package guidelines:
>   http://www.bioconductor.org/developers/package-guidelines/

Done, exept line 42 from cheks.R file

> * Use `ECGPreprocess` as your constructor function. Rename it to `ECGMainData`,
>   run your checks on the arguments and then call `new` at the end.

Done.

> * Unexported functions have the convention of a `.` (dot) in front of the name.

Done.

> * Create accessor and setter functions for your class, for example,
>   `expressionData(ECGMainData)` `expressionData(ECGMainData) <- newData`

We have not implemented this change because the user will never have access to the object. It is made only for internal use.

> 
> Minor
> 
> * `c(1)` is the same as `1`
> 

Done.

> ## tests/
> * Add more tests to increase package robustness
> 

Done. We included two tests. One for ADAnalysis function and other for GFAGAnalysis function.

> ## data/
> * I don't think `AvailableDBSpecies` is required as we have a lookup function
>   in `BiocManager::available`.

We have removed this data file.

> * Consider using one set of datasets for either humans or 'Aedes aegypti' for
>   your examples, not both. This will reduce the storage required for your package.
> 

We excluded the humans data sets. Now there is only Aedes aegypti data files.

> ## R CMD check results
> ```
> Undefined global functions or variables:
>   GOID Ontology Term mappedkeys
> ```

Done.

Best Regards,
José Luiz

**Comment by jrybarczyk** [comment]
Hi Marcel @LiNk-NY 

Your suggestions and considerations for improving our package, ADAM, were
extremely valuable and really contributed to the development of a more efficient
and professional code.
We made most of the changes, justifying why some of them could not be made.
We submit the new version, duly corrected, 6 days ago.
Is there anything we can do to improve the package in time for it to be accepted in
this release?

Thank you in advance.
Best regards,

José Luiz

**Comment by LiNk-NY** [comment]
Hi José Luiz, @jrybarczyk 
I will have a second look at your package today. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi José Luiz, @jrybarczyk 
I've looked at the changes and it doesn't seem like you properly imported the
`SummarizedExperiment` package and related functions. Include `@importFrom SummarizedExperiment assay`.

Please tidy up the `DESCRIPTION` file and remove `org*db` packages from `Imports` these
are not needed there.

You likely don't need to import `BiocManager` now that you have cleaned the function in
the `R/checks.R` file. 

Regards,
Marcel

**Comment by jrybarczyk** [comment]
Hi Marcel @LiNk-NY,

Thanks for your review. All the required corrections have been done.

Best regards,

José Luiz

**Comment by LiNk-NY** [comment]
Hi José Luiz, @jrybarczyk 
Thanks for making those changes. Your package has been accepted.
Best regards,
Marcel

**Comment by jrybarczyk** [comment]
Hi Marcel @LiNk-NY 

I would like to thank you for all suggestions to improve the package.

Best regards,

José Luiz

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jrybarczyk.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ADAM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ADAM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
