### ISSUE TITLE
Wrench

### ISSUE THREAD

**Issue by hcorrada** [Bioconductor/Contributions#909]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HCBravoLab/Wrench

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi @hcorrada , 

Thank you for your submission to Bioconductor. Please follow the build report to fix all WARNING message and as best as you can of the NOTE message. 

After the WARNINGS are fixed, a technical review will be given (most of the NOTE messages will appear here again to require a fix). Comment back here with any question or when you are ready for a new look. Thanks!

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @jkanche , 

Here is the technical review. Please address all issues and comment back with any question or when you are ready for a 2nd look!

## DESCRIPTION

Refer [here](http://bioconductor.org/developers/package-guidelines/) for more details.
- Be sure to "Depends: R (>= 3.5.0)"
- Remove the "Collate" field since you only have one script. This is intended to be used to order class and method definitions appropriately during package installation.
- Add "URL" field to direct users to source code repositories, additional help resources, usually the github page.
- Also add "Bugeports" field for the relevant link to github for report issues.

## NAMESPACE

- Looks good.

## vignette

- Add author affiliations.

- setup options: be sure to use "include=FALSE" to evaluate the chunk, but neither the code nor it's output displayed for the following code.
```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- loading other R packages: use "message=FALSE" to avoid loading messages in vignette. Put this code chunk in the main sections (other than "introduction" and "installation")
```
{r packages, message=FALSE}
require(metagenomeSeq)
require(edgeR)
require(Wrench)
require(DESeq2)

```

- Enable Table of contents to show the structures. Refer [here](https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents).

- Reorganize your vignette to include these sections: "Introduction/Abstract", "Installation", ... main sections, ... "sessionInfo". For the main sections in between, use hierarchical structures to organize them and show in Table of Contents.

- Use the following for "Installation":

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```
- For the last section of "sessionInfo", Include the following code and let it run and print the output.

```
{r sessionInfo}
sessionInfo()
```

- L26: "The manuscript can be accessed here: [REF]": no link is included here.

- L31: If only specific figures(Fig.1) or tables (table 1) are needed in the vignette, you should print them in the vignette as examples, instead of refering into other website.

- You need to print out some of the intermediate data in your code to help the users follow your vignette. E.g.,
```
data(mouseData)
mouseData
...
counts[1:10, 1:5]
...
table(group)
```

And,
```
...
head(compositionalFactors)
...
head(normalizationFactors)
...
deseq.obj

```

## R/

- There are unefficient repeated code chunks like this, please write some utility functions and use it inside "estimSummary()".
```
}else if( estim.type=="w.cond.mean"){
    W <- getCondWeights( res )
    with(res$others, {
        sapply( seq(ncol(radj)), function(j){
            y <- radj[,j]
            w <- W[,j]
            y <- y[!is.na(w)]
            w <- w[!is.na(w)]
            weighted.mean( y, w )
        } )
    }
    }
```

- A better coding style for unexported functions is to prefix them with ‘.’. E.g., ".estimSummary <- function(...)". Refer [here](https://bioconductor.org/developers/how-to/coding-style/).

- Avoid use of "sapply", use "vapply" instead.

- Remove the unneeded commented code.

## man/

- Looks good!

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @hcorrada 

Just a reminder that the last day of new package inclusion to the new release would be Oct 24th (next wednesday). Please address the above issues ASAP so that we can make the deadline for the release. But anyway, it will be in the new devel if we miss that. 

Qian

**Comment by Liubuntu** [comment]
Hi @mskb01 , 

Thank you for addressing the review issues. Please fix the following issue and bump version. As soon as it clears, we could have the package accepted by today. Thanks!

## DESCRIPTION

- rename `Bufreports` as `BugReports`.

Cheers,
Qian

**Comment by mskb01** [comment]
Hi @Liubuntu , the package now reflects the change you recommended. 

Cheers,
Kumar

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hcorrada.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"Wrench\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Wrench

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
