### ISSUE TITLE
compartmap

### ISSUE THREAD

**Issue by biobenkj** [Bioconductor/Contributions#914]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/trichelab/compartmap

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by biobenkj** [comment]
It looks like the build failed at the vignette building step. I'll swap out for a shorter running example for the vignette and push. The arrays are quite slow in terms of processing.

**Comment by biobenkj** [comment]
Even though the TIMEOUT label was removed with the most recent build, it looks like one of the warnings is from the Windows build taking 6 min and 55 sec - thus exceeding the 5 min build time. I'm not sure I can speed up the examples much faster beyond trying a smaller chromosome (e.g. chr22) for the data. What would you suggest @mtmorgan?

**Comment by mtmorgan** [comment]
I'll review the package as-is.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Authors@R is a replacement for separate Author: and Maintainer: fields (these are generate when the package is built).
- Please make the 'master' branch a clean package repository, e.g., no top-level `Makefile` (this might be on a separate branch)

vignettes

- ok

R

- `message(paste())` (also `stop()`, `warning()`) is usually not necessary (`message()` pastes its arguments internally)
- avoid `1:n` style iteration, which goes wrong when, e.g., n == 0; use `seq_len()`, `seq_along()` instead
- using BiocParallel instead of parallel (e.g., getATACABsignal.R:42) would provide greater flexibility for users.
- no need for `which()` around logical indices...
- Do the TODO at getArrayABsignal.R:99?
- For what it's worth each test in `stopifnot()` is usually evaluated separately, rather than concatenated with `&&`.

tests

- looks like there are no tests implemented, remove this part of the infrastructure

inst/doc

- is this folder used?

**Comment by biobenkj** [comment]
Hi @mtmorgan,

Thanks for all your feedback! This has been a lot of fun (first R package for me).

> DESCRIPTION
>     * Authors@R is a replacement for separate Author: and Maintainer: fields (these are generate when the package is built).

Got it. Fixed this by removing redundant Author: and Maintainer: fields.

>     * Please make the 'master' branch a clean package repository, e.g., no top-level `Makefile` (this might be on a separate branch)

Done.

> vignettes
> 
>     * ok
> 
> 
> R
> 
>     * `message(paste())` (also `stop()`, `warning()`) is usually not necessary (`message()` pastes its arguments internally)

Done.

>     * avoid `1:n` style iteration, which goes wrong when, e.g., n == 0; use `seq_len()`, `seq_along()` instead

I've added a couple of additional checks to assert that in (specifically in the meanSmoother function) that the variable(s) used for this function won't be 0. Since these are internal variables not necessarily exposed to the user, I hope these checks will suffice?

> 
>     * using BiocParallel instead of parallel (e.g., getATACABsignal.R:42) would provide greater flexibility for users.

Could this be a part of devel where we can really flesh out how the user could interact with the various parallel backegnds?

>     * no need for `which()` around logical indices...

Done.

>     * Do the TODO at getArrayABsignal.R:99?

Done.

>     * For what it's worth each test in `stopifnot()` is usually evaluated separately, rather than concatenated with `&&`.

Have split each of these out into individual checks and stop() with, hopefully, a more informative message than would necessarily result from stopifnot()

> 
> tests
> 
>     * looks like there are no tests implemented, remove this part of the infrastructure

Done.
> 
> 
> inst/doc
> 
>     * is this folder used?

Yes, this folder is used to house a couple images for the README.md on the GitHub homepage

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/biobenkj.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("compartmap")`. The package 'landing page' will be created at

https://bioconductor.org/packages/compartmap

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
