### ISSUE TITLE
DNABarcodeCompatibility

### ISSUE THREAD

**Issue by etournay** [Bioconductor/Contributions#917]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/comoto-pasteur-fr/DNABarcodeCompatibility

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vobencha** [comment]
Hi @etournay 
Sorry for the delay. I'll take a look at this and get comments back to you tomorrow.
Valerie

**Comment by etournay** [comment]
Hi @vobencha,
Thank you for your message, this is very kind of you.
Raphael

**Comment by etournay** [comment]
Dear @vobencha,

I thank you for your comments. We are going to fix these issues within the next few days.

Best wishes,
Raphael

**Comment by etournay** [comment]
Dear @vobencha,

We have started to address "error handling" in general.
For example we handle cases where the multiplex level is higher than the number of available different barcodes. We did other changes in this spirit to ensure a proper error handling within the graphical user interface that we provide in a different repository.
We will soon move to the suggestions you made. 

BiocCheck now imposes an R version >= 3.6. However the latest R version is 3.5.
I will have to change it back to 3.5 in the DESCRIPTION file otherwise nobody can install our package from the master branch, unless you have a hint?
 
Best wishes,
Raphael

**Comment by vobencha** [comment]
Hi,
The latest 'devel' version of R is 3.6 and can be downloaded here
https://stat.ethz.ch/R/daily/

Valerie

**Comment by etournay** [comment]
Ok, I see, we need to install the development version.
All right, thank you for the tip.
Raphael

**Comment by etournay** [comment]
Dear Valerie,
We have improved the documentation and code according to your suggestions.

Regarding issue#1, we have kept the arguments' names `file1` and `file2` for simplicity and we have added more explanation about those inputs in the documentation with respect to the 'single' and 'dual' indexing precodures.

Regarding issue#2, we now check the class and content of the input data in the functions `distance_filter()`, `experiment_design()`, `get_all_combinations()`, `get_random_combinations()`, and `optimize_combinations()`.

Regarding issue#3, we now mention in the documentation that, according to Illumina, a multiplex value below 96 is reasonable. And we fixed the error generated when the multiplex level is higher than the number of available barcodes. The error messages that we output are now devoid of `\n`.

We believe that the changes we made are in agreement with your suggestions. Shouldn't it be the case, please let me know. 
Kind regards, 
Raphaël

**Comment by vobencha** [comment]
Thanks for making the changes. Package is approved.
Valerie

**Comment by etournay** [comment]
Dear Valerie,

On behalf of my team, I thank you for your time and suggestions.
Kind regards,
Raphael

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/etournay.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DNABarcodeCompatibility")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DNABarcodeCompatibility

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
