### ISSUE TITLE
VCFArray

### ISSUE THREAD

**Issue by Liubuntu** [Bioconductor/Contributions#918]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/VCFArray

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
Looks useful. I think the `pos` meta column in `@gr` could be formalized better, perhaps as its own slot, or via a validation rule.

**Comment by Liubuntu** [comment]
Thank you @lawremi for your input. I have made `pos` as its own slot now. Will come in next version after I fix the current error, (which should come from the dependency). Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @Kayla-Morrell, 

I have modified the package to pass building and checks on all platforms. One example for `RangedVcfStack` was deactivated in `man/VCFArray-class.Rd`, because it takes longer time to give the "TIMEOUT" warning on windows system. However the same examples has been included in vignette with `eval = TRUE`, and also been tested in `test/testthat/test_VCFArray.R`. So there won't be any problem in evaluating. 

So I think it's ready for a review. Please let me know if there any further issues I need to address. Thank you very much!

Best,
Qian

**Comment by Kayla-Morrell** [comment]
Hi @Liubuntu 

Your package looks good to me, I just had a few minor things to bring to your attention. Please see the initial review below:

**Vignette**
- [ ] REQUIRED: under 3.1, I try to run code for the remote VCF file, but I come up with an error when I try to define `va`. Double check that this code is able to be executed even if it isn't evaluated in the vignette. See the error below:

`Error in vcfFields(file) : all(file.exists(x)) is not TRUE`

- [ ] SUGGESTION: under 3.2.1, there doesn't need to be a period after "slot accessors" since none of the other headers have a period after them. 

**R files**
- [ ] SUGGESTION: `AllUtilities.R`, for `.header()` you might consider taking out the `FIXME` comment.
- [ ] SUGGESTION: `AllUtilities.R`, for `.get_VCFArraySeed_type()` you might consider a closing edge case of some kind. Either closing with a final else statement or using `stopifnot()`.
- [ ] SUGGESTION: `AllUtilites.R` for `.get_VCFArrarySeed_basic_param()` the same as the previous suggestion with a closing edge case.
- [ ] REQUIRED: `VCFArray-classes.R` for the VCFArray constructor `setMethod()` the comment about extract_array should be removed.

**man files**
- [ ] REQUIRED: `VCFArray-classes.Rd` I tried running the `\dontrun{}` section of examples and I get an error when trying to assign `stack` and the rest of the example can't be evaluated. The error is below:

`Error in validObject(.Object): invalid class "VcfStack" object: all rownames(object) must be in seqlevels(object)`

**inst files**
- [ ] REQUIRED: `todo.Rmd` should be removed.

**tests**
- [ ] SUGGESTION: for `XStringSetList, IntegerList...` there is a comment that could be potentially good tests. You might consider developing these.
- [ ] REQUIRED: for `RangedVcfStack geno()` get rid of the "success" comment.

Comment back with updates that have been made and when the package is ready for a re-review.

Best,
Kayla

**Comment by Liubuntu** [comment]
Hi @Kayla-Morrell , 

Thanks for the thorough review. I'll address the review issues very soon! 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @Kayla-Morrell , 

Thanks again for the review. I have addressed most of the issues. Here are 
some explanations / plan for the ones that are not addressed. 
 
> SUGGESTION: for XStringSetList, IntegerList... there is a comment
> that could be potentially good tests. You might consider developing
> these.

This is a feature request for `DelayedArray` and here is the related
issue report: https://github.com/Bioconductor/DelayedArray/issues/27.
Herve said feasible but requires major development. When this feature
is added, the `VCFArray` package itself would need some more
modifications (e.g.,the `.readVcf_for_class` function need to remove
the "array()" before returning the result). So I'm keeping this
potential test in test file and for now commented.

> REQUIRED: VCFArray-classes.R for the VCFArray constructor
> setMethod() the comment about extract_array should be removed.

Can you point out which specific line is it? sorry that I couldn't be
able to locate...

> man files

> REQUIRED: VCFArray-classes.Rd I tried running the \dontrun{} section
> of examples and I get an error when trying to assign stack and the
> rest of the example can't be evaluated. The error is below:   
> Error in validObject(.Object): invalid class "VcfStack" object: all
> rownames(object) must be in seqlevels(object)

I could not reproduce this error, I wonder if you are using a version
of `GenomicFiles` >= 1.17.3? because the example of generating `stack`
and `rgstack` is mostly copied from the example in `?VcfStack`, which
should works since the packages are building without error.

> REQUIRED: under 3.1, I try to run code for the remote VCF file, but
> I come up with an error when I try to define va. Double check that
> this code is able to be executed even if it isn't evaluated in the
> vignette. See the error below:   
> Error in vcfFields(file) : > all(file.exists(x)) is not TRUE

Thank you pointing this out. I will work on another pull request to
`VariantAnnotation` to make the `vcfField` method work on remote
path. When it's done I will then comment back here.

Best,
Qian

**Comment by Liubuntu** [comment]
HI @Kayla-Morrell , 

I have just created a pull request to `VariantAnnotation`. https://github.com/Bioconductor/VariantAnnotation/pull/18  As soon as this is merged, I would bump version of `VCFArray` so that it could build. This should fix the not-runnable vignette example problem. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @Kayla-Morrell ,

In your initial review (https://github.com/Bioconductor/Contributions/issues/918#issuecomment-440370274), I have checked boxes for those I made changes. For those not check, I have given explanation / further question here (https://github.com/Bioconductor/Contributions/issues/918#issuecomment-442611748). 

The pull request I mentioned in VariantAnnotation https://github.com/Bioconductor/VariantAnnotation/pull/18 has been merged so that the previous unsuccessful vignette code for remote vcf filepath is now fixed. 

The WARNING in building report comes from longer check time on windows machine, which should be fine according to Lori, since more checks have been added and windows always takes longer checking time than the other 2 platforms. 

Please let me know for further issues. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @Kayla-Morrell , 

The "WARNING" for windows checking has been cleared! So finally ready for the 2nd review. :)

Best,
Qian

**Comment by Kayla-Morrell** [comment]
Hi @Liubuntu,

All the updates look great. I'm working through my 2nd review and should have some comments for you soon. 

Thanks, 
Kayla

**Comment by Kayla-Morrell** [comment]
Thank you @Liubuntu for making the necessary changes. Below are my comments:

>> REQUIRED: VCFArray-classes.R for the VCFArray constructor
setMethod() the comment about extract_array should be removed.

> Can you point out which specific line is it? sorry that I couldn't be
able to locate...

It would be line 244 in VCFArray-classes.R.

>> man files
REQUIRED: VCFArray-classes.Rd I tried running the \dontrun{} section
of examples and I get an error when trying to assign stack and the
rest of the example can't be evaluated. The error is below:
Error in validObject(.Object): invalid class "VcfStack" object: all
rownames(object) must be in seqlevels(object)

> I could not reproduce this error, I wonder if you are using a version
of GenomicFiles >= 1.17.3? because the example of generating stack
and rgstack is mostly copied from the example in ?VcfStack, which
should works since the packages are building without error.

This was my mistake. I was trying to perform the example directly from the .Rd file instead of looking at the formatted man page. When doing it from the .Rd file I was getting an error due to the definition of the names of files (`"\\\\1"`). This formats correctly and when going through the example on the proper man page I don't get the the error. So this requirement can be ignored.

Once the first comment is addressed I'll be ready to accept your package.

Thank you,
Kayla

**Comment by Liubuntu** [comment]
Hi @Kayla-Morrell , 

The comment was removed for the first issue and the building report is cleared. Thanks!

Best,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Liubuntu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VCFArray")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VCFArray

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
