### ISSUE TITLE
cytofast

### ISSUE THREAD

**Issue by KoenAStam** [Bioconductor/Contributions#922]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/KoenAStam/cytofast

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Here is the review of your package. It looks good and I have a few general concerns. [REQUIRED] tags indicate change that must be made of require responses. [CONSIDER] tags indicate changes that are advisable but not required. Please message me back when you are finished so I can have another look at your package.

DESCRIPTION:
- [CONSIDER] The `description` section seems a little sparse. Consider giving a
little more explanation about what the pacakge does.

R/GENERAL:
- [REQUIRED] The Bioconductor project requires that its packages use the S4
class system instead of the S3 class system like this package is. Please convert
S3 classes and function with dispatch to the S4 class system:
http://adv-r.had.co.nz/S4.html
https://www.bioconductor.org/packages/release/bioc/vignettes/S4Vectors/inst/doc/S4QuickOverview.pdf
- [CONSIDER] Use `match.arg()`. For example, in `cytottest.R`:L40, the function
`cytottest()` can declare the `adjustMethod` argument as
`adjustMethod=c("holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none")`.
In the function, the user's choice can be acquired with
`adjustMethod <- match.arg(adjustMethod)`. The first argument will be the
default argument (in this case "holm"). Using `match.arg()` is prefered as it
will throw an error if the user selects an invaild argument. Also, it will
easily show the user the acceptable values of `adjustMethod` when showing the
function by typing `cytottest`. This can be done in other locations in the
package.
- [REQUIRED] Use `message()` for all diagnositic messages to users, not `cat()`.
This is better because `message()`s can be toggled off.

tests
- [CONSIDER] Add tests to the package using the `testthat` package.

**Comment by KoenAStam** [comment]
Thanks for the review! 

I actually considered the S4 class when starting writing, but I generally just liked the S3 more because of its flexibility (and its simplicity). Nonetheless, I'll start with making the transition to S4.   

As for the testthat, I want to add it to the package, but I was a bit confused on how to apply it. Could you point me to the right direction, like some useful documentation?

Lastly, I assume I can just keep making commits and push to check if everything is still OK?

**Comment by dvantwisk** [comment]
With regards to `testthat`, here are some resources:
https://journal.r-project.org/archive/2011/RJ-2011-002/RJ-2011-002.pdf
https://www.johndcook.com/blog/2013/06/12/example-of-unit-testing-r-code-with-testthat/

It helps to look at packages that have already implemented `testthat` tests:
https://github.com/drisso/SingleCellExperiment/tree/master/tests/testthat

Yes, you can keep building your package on our build machines by bumping the z coordinate of your version (e.g. 0.99.0 to 0.99.1).

**Comment by dvantwisk** [comment]
I've been looking over the changes made to this package and they look great! I'm ready to accept the package as-is but I'm not sure if you'd like to make any of the other optional changes. Message me back when you'd like me to accept it.

**Comment by dvantwisk** [comment]
Hello, can you perform a version bump?

**Comment by dvantwisk** [comment]
Are you still working on this package? It's been over two weeks since your last push. We close packages for inactivity if we see they haven't been worked on for a two-week period. Issues that are closed can be reopened once the maintainer is ready to work on them again. Please message me back if you plan on making any changes soon.

**Comment by KoenAStam** [comment]
Thanks for reaching out, I had to address a few other things, but I'm fully focused on the package again. I made the final changes and as far that I can see I only have to update my R dependency in the description file to 3.6. I have some users who are still on 3.5, hence I didn't change it yet, do you want me to update it now?

**Comment by dvantwisk** [comment]
Yes, you can update the version of R now.

**Comment by dvantwisk** [comment]
I've looked over your package and everything looks good now. I'm going to move to accept it.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/KoenAStam.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cytofast")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cytofast

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
