### ISSUE TITLE
(inactive) ComStat

### ISSUE THREAD

**Issue by gzrrobert** [Bioconductor/Contributions#923]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gzrrobert/ComStat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please review the Bioconductor package guidelines. Your package does not have a vignette and does not interoperate with robust, established packages relevant to the domain of analysis. Is it more appropriate as a CRAN package?

**Comment by mtmorgan** [comment]
A vignette is a document that describes how the package is used, typically with a working example and emphasizing integration with other Bioconductor packages.

An excellent vignette is from [DESeq2][1] (from the source in the package /vignettes directory -- `git clone https://git.bioconductor.org/packages/DESeq2`)

Some basic instructions for producing a vignette are [here][2]

[1]: http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html
[2]: http://r-pkgs.had.co.nz/vignettes.html

**Comment by gzrrobert** [comment]
Okay, thank you so much about the instruction, but I am still confused
about the  infrastructure packages
<http://bioconductor.org/developers/how-to/efficient-code/> instruction.

Best regards,
*Zhangrong Gu, MS in Biostatistics*
*Research Assistant *
*Department of Biostatistics, Bioinformatics & Biomathematics*
*Georgetown University Medical Center*
*+1-(202) 294-2414*


Martin Morgan <notifications@github.com> 于2018年10月30日周二 下午11:30写道：

**Comment by mtmorgan** [comment]
Several problems immediately appear to me in your code.

The first is that examples cannot refer to locations on your disk, since our build system (that runs the examples) does not have access to your disk. Instead, put example data sets in `inst/extdata/<your-data-here>` and use the `system.file()` function in examples / vignettes to locate these -- `system.file(package="ComSat", "extdata", "<your-data-here")`

The second is that users will often have read their data into R's memory and manipulated the objects themselves, so they should be able to pass a data.frame or similar object rather than file paths.

The third is that R operates on vectors, so loops such as the one at https://github.com/gzrrobert/ComStat/blob/b949bd076659a983662c8997c27cd0b37b8bb5d2/R/TwoDrug1.R#L163
```
  for (i in 1:length(linear_hat)) {
    diff_linear_hill[i]<-(linear_hat[i]-hill_hat[i])**2
  }
```
are much more efficiently written as simply
```
 diff_linear_hill <- (linear_hat - hill_hat) ** 2
```
This applies at many places in your code, in this 'obvious' way and in more subtle ways.

Using `<<-` at https://github.com/gzrrobert/ComStat/blob/b949bd076659a983662c8997c27cd0b37b8bb5d2/R/TwoDrug1.R#L49 will over-write any variable on the left-hand side that the user has in their global environment; this is very bad practice and should be avoided -- your code should not rely on a variable "location1" that is present in the user's global environment, but should instead rely on arguments passed to the function.

**Comment by gzrrobert** [comment]
Okay, I see the problems, thank you so much for your help, and I have uploaded the data used in the example. I will also change the location in the example so that the users could download the example data from Github and put their own path on their disk to run the example.

**Comment by mtmorgan** [comment]
the data is small and should be included in the package (in the inst/extdata folder mentioned previously) and not downloaded from github.

**Comment by gzrrobert** [comment]
Okay, sure!

**Comment by mtmorgan** [comment]
Can you update me on the status of your package, have you addressed the data and other issues so that your package is ready for moderation and addition to the review queue?

**Comment by gzrrobert** [comment]
Hi Martin,
I have included the data in the package.

Best regards,
*Zhangrong Gu, MS in Biostatistics*
*Research Assistant *
*Department of Biostatistics, Bioinformatics & Biomathematics*
*Georgetown University Medical Center*
*+1-(202) 294-2414*


Martin Morgan <notifications@github.com> 于2018年11月21日周三 上午12:37写道：

**Comment by mtmorgan** [comment]
your code still contains loops that can be easily vectorized. There is no vignette in your package. I think the effort required to bring this to Bioconductor standards is substantial, and I am therefore declining the package.
