### ISSUE TITLE
(inactive) mms2plot

### ISSUE THREAD

**Issue by lileir** [Bioconductor/Contributions#928]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lileir/mms2plot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lileir** [comment]
Hi, I have subscribed  bioc-devel and my email address (leili at qdu.edu.cn) is listed in https://stat.ethz.ch/mailman/roster/bioc-devel). However, I do not know why it is reported that "ERROR: Maintainer must subscribe to the bioc-devel mailing list.". Please give me a hand. Thanks!

**Comment by lshep** [comment]
Because that is not the email listed as the maintainer in the package.

**Comment by lileir** [comment]
Hi, lshep, 

Could you please estimate when you finish reviewing this package?  

Thanks!
Lei

**Comment by lshep** [comment]
Thank you for your interest in Bioconductor. Please see comments below: 

**General**
- [ ] show example code writing to a temporary directory for all output files created. `tempdir`
- [ ] it seems like the output is always written to a file, it might be nice to allow for an interactive view rather than always writing to a file. 
- [ ] This seems like visualization of Mass Spec data but there currently is no interoperability with current Bioconductor structure - Please look into current data elements that hold proteomics data and explain what data would be missing that is provided in raw files to make it unable to be adapted to your visualization functions. https://bioconductor.org/packages/release/bioc/html/MSnbase.html

**DESCRIPTION**
- [ ] Please use either Author/Maintainer  or Authors@R  not both 
- [ ] Please remove lazyData: true.  We have found this rarely proves useful and can actually slow down installation

**NEWS**
- [ ] Please add in list indication element for Welcome to report bugs! else it will not parse correctly. Ex:

```
VERSION 0.99.6
-----------------------

+ Welcome to report bugs!
```

**Man**
atom_mw_table
- [ ] Please provide source information or how/where this data was generated. 

mms2plot
- [ ] Instead of commenting out the plotting function, put just that line in dontrun{}  this will distiguish the comments from the code 
- [ ] So do these indicate different values obtained from the instrumentation or analysis?  I guess I'm confusted at why you would show the same general commands 3 different times when nothing is different excepte the paths?
- [ ] I can't currently execute your example code. When I try to run what isn't run it errors.  Even if it is in dontrun it should be able to be run without ERROR
```
> general_path = system.file( package = "mms2plot",dir = "extdata" )
> TMT_path = system.file( package = "mms2plot",dir = "extdata/TMT" )
> id_table_path = dir( TMT_path, "msms_TMT.txt", full.names = TRUE )
> par_xml_path = dir( general_path, "modifications.xml", full.names = TRUE )
> par_xml_path 
[1] "/home/lori/R/x86_64-pc-linux-gnu-library/3.6-BioC-3.9/mms2plot/extdata/modifications.xml"
> mqpar_filepath = dir( general_path, "mqpar_batch.txt", full.names = TRUE )
> output_path = general_path
> output_path
[1] "/home/lori/R/x86_64-pc-linux-gnu-library/3.6-BioC-3.9/mms2plot/extdata"
> mms2plot(id_table_path, par_xml_path, mqpar_filepath, output_path) # not run
Error: 'silac/mqpar.xml' does not exist in current working directory ('/home/lori').
```

**Vignette**
- [ ] Please remove the mms2plot.R file it is not needed. 
- [ ] Consider updating to use BiocStyle vignette format (but not required)
- [ ] For consistency please use system.file( package = "mms2plot",dir =  ) to find your files instead of hard coding inst/extdata as that location will not be found on a users system. For example when I try to run your code in your vignette
```
> id_table_path = "../inst/extdata/silac/msms_SILAC.txt"
> input_table <- data.table::fread(id_table_path, na.strings = "NA",
+         sep = "\t", fill = TRUE, header = TRUE)
Error in data.table::fread(id_table_path, na.strings = "NA", sep = "\t",  : 
  File '../inst/extdata/silac/msms_SILAC.txt' does not exist or is non-readable. getwd()=='/home/lori/pkgReview'
```
- [ ] par_xml_path is not very informative at what this file is or what the format should be if not using Maxquant input - please provide more detail like you did for id_table_path. 

- [ ] mqpar_filepath  same as before - you cannot hard code paths as they will not be the same  on the users system. Use system.file to find your example file. 

- [ ] Input parameters.  While this plot is nice and still should be included a  list of available options would also be nice as it may be hard to find or underdstand everything from the graph representation. 

- [ ] It would be nice to show the actually call you make to get a plot. Simply including the code in the man page would suffice but currently the vignette does not actaully show how you would run any function.

**inst**
- [ ] Please include an inst/scripts directory that includes how the data in inst/extdata was generated.  In can be code, sudo code or text but should indicate the source and any instrument settings. 

**Data check**
- [ ] where are all these data and inst/extdata files being used? Are all necessary for inclusion? No need to include in the package but please comment back here on where these are being used and why. 

**R**
- [ ] Use system.file( package = "mms2plot",dir =  ) to find your files instead of hard coding inst/extdata as that location will not be found on a users system. 
- [ ] Use message instead of print to display output to users
- [ ] Try to minimize code and repeated code as much as possible to have wrappers

mms2plot.R
- [ ] Remove commented out code - if you would like to save this for your own use please put it somewhere else than in the code/documentation perhaps in inst/scripts or elsewhere saved file (mayb .gitignored so not provided to user)
- [ ] Remove comment out browser calls in code 
- [ ] The double check for output_path seems excessive, Require that it is an expanded path rather than character vector. Simplifed code is always better so something like this 
```
  if(! file.exists(output_path)) {
        output_path = paste(output_path, "/", sep="")
        if(! file.exists(output_path)){
            stop(paste("The output dictionary [", output_path, "] does NOT \
                exist!"))
        }
    }`
```
could be 
```
stopifnot(file.exists(output_path))

```
if you would like the if to customize the message that is understandable. 

- [ ] I might have more comments once I'm able to trace a working example through your code so please update the example in the man page to run 


plot_mirror_or_group.R

readMQPar_ppm 
- [ ] Simplify this code, it is messy and a lot of repeated code. You create variables that then you do something else to and override the name, combined these lines. There is also no need to try and parse anything `if (all(nchar(filePaths) > 0)) `  so these should be moved inside this check. 

drawms2plot_samerawfile
- [ ] You hard code the use of your data table.  Is there a use case where a user would provide this table instead of using your own?  There are a lot of NA's columns in this provided table, are these columns that are utilized in your function? else whats the point? 
- [ ] Use message instead of print to display output to users. 

I'm going to halt looking at the rest of the R code until the above is fixed and I am able to run an example to trace it through the code.  Having a runnable example provided is a necessity and it will not be accepted otherwise.  Please address the above issues - when ready ensure there was a version bump to trigger a new build and comment back here requesting a re-review and addressing the comments above.  Thank you.

**Comment by lshep** [comment]
Just wanted to check it to see how updates were going and if you had any questions regarding any of the comments?

**Comment by lshep** [comment]
We normally like to see changes to a package within a few weeks to know they are being actively worked on -  do you have an estimate of when we might see updates to the package?
