### ISSUE TITLE
deco

### ISSUE THREAD

**Issue by fjcamlab** [Bioconductor/Contributions#929]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fjcamlab/deco

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by fjcamlab** [comment]
Hi,

I must be missing something because I do not understand why only the **CHECK** process in OS X 10.11.6 El Capitan/x86_64 is failing due to the package size. Since previous version v.0.99.16, any change has incremented the number or the size of files. That version did not reply about this matter, but now it does.

OS X 10.11.6 El Capitan/x86_64:
```
ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 5.3193 MB
        Size Requirement: 4.0000 MB
```

Windows Server 2012 R2 Standard/x64 and Linux (Ubuntu 16.04.1 LTS)/x86_64:
`* checking installed package size ... OK`

Thanks

**Comment by mtmorgan** [comment]
I think it's the size of the built vignettes, due to the way images are generated / resolution that they are stored at. I'll review the package as-is.

**Comment by fjcamlab** [comment]
Hi,

I removed some of the issues (NOTES) related to the R code like replacing sapply() by vapply() and removing some unnecessary parts of the code. I have also re-designed the R vignette to save space for the total R package size, as you hinted before. However, sometimes, the same BioCheck error related to OS X compiled size still appears when I push a new version. 

Please, let me know which changes I should do now. 

Thanks

**Comment by mtmorgan** [comment]
# 20 November, 2018

DESCRIPTION

- It is not necessary to include the GPL LICENSE file with your package, it is distributed with R.

- Are the packages in the Depends: field needed by the end user, or used internally to your package? If just internal to the package then they should be in the Imports: field (and import()'ed in the NAMESPACE file).

vignette

- the vignette looks like a very valuable resource, thanks for the effort creating it!

- please carefully review your LaTeX dependencies and include only those that are essential for your vignette; a common problem is that these dependencies change, and the package must be updated even when the dependency is not used or used for marginal benefit.

- It is not best practice to disable warnings globally in knitr, this hides rather than addresses problems.

- I do not recommend including installation instructions from your lab web site; instead, use standard Bioconductor installation instructions as though the package were accepted

```
if (!requireNamespace('BiocManager', quietly = TRUE))
    install.packages("BiocManager"
BiocManager::install('deco')
```

  Optionally, include a 'devel' installation instruction that points to a public source code repository and uses standard R tools, e.g., `BiocManager("fjcamlab/deco")`.

- 'ExpressionSet' has been replaced by [SummarizedExperiment][https://bioconductor.org/pacakges/SummarizedExperiment], which should be used whereever possible.

- Try where possible to use data sets and packages that are available within R. For instance TCGA data is readily available using the [curatedTCGAData][https://bioconductor.org/packages/curatedTCGAData] package. Since the curatedTCGAData package uses ExperimentHub, the data is downloaded only once on the build or user machines, so the vignette chunks do not need to be marked with `eval = FALSE`.

- Using direct slot access, `slot(deco_results, "featureTable")` is strongly discouraged -- write and use throughout the vignette and your own R code a simple 'accessor' function to separate the interface experienced by the user from the implementation useful to the developer.

R (comments are on specific code lines, but apply throughout)

- deco.R:16: use a named vector `c(featureTable = "data.frame", ...)` rather than constructing the vector in two steps. Consider adopting a convention, e.g., `.slots <- ...` to name variables that are not going to be visible to the user. Does this style of defining the slots outside the `setClass()` statement provide much additional value over defining the slots inside the `setClass()` tatement?. Use of data structures like `data.frame()` or `list()` as slots to some extent undermines the value of a formal class, since the content of a data.frame or list is not well-defined.

- deco.R:33 Never change global options inside a function; it looks like your code generates warning that you are trying to suppress. Instead, write code that does not generate warnings, or if absolutely necessary use `suppressWarnings()` around the specific problematic code.

- deco.R:33 Please format your code to enable readability, rather than to fit code on one line. For instance, aim for individual lines that accomplish one task, and that are not higly nested; change

    ```
    if(temp.path == tempdir() || !(temp.path %in% names(dir()))){
      temp.path <- tempdir(); message("'temp' folder will be created in current work directory to store internal loop data.")}
    ```
    
  to
  
    ```
    if(temp.path == tempdir() || !(temp.path %in% names(dir()))){
      temp.path <- tempdir()
      message("'temp' folder will be created in current work directory to store internal loop data.")
    }
    ```
    
  Note here that the message is incorrect, `tempdir()` points to a temporary directory somewhere on the file system, usually not in the current working directory.
  
- deco.R:40 As noted, new packages should use SummarizedExperiment rather than ExpressionSet.

- deco.R:49 and throughout: `paste()` inside `stop()` is usually not necessary, `stop("foo ", 123, " bar")` is rendered with `foo 123 bar`. This is true for `message()` and `warning()`, as well. The formatting here is also difficult to read; consider a more traditional

    ```
    if (test) {
        ## true
    } else {
        ## false
    }
    ```

- deco.R:56 avoid nesting complicated expressions, and reuse rather than re-calculate where possible (there are many places in your code where expressions are re-calculated rather than stored once in a variable and reused, e.g, in the test at deco.R:205 where `all(!is.na(classes))` is invariant across the loop), e.g.,

    ```
    test <- infogenes[,"CHR"] %in% c("X","Y")
    if (sum(test) > 1) {
        data <- data[rownames(infogenes)[!test],]
    ...
    ```
- deco.R:58 Write simple functions for commonly used expressions, e.g., 

    ```
    .timestamp <- function()
       format(Sys.time(), " %H:%M:%S")
    message(.timestamp(), "-- Features...)
    ```

  Consider revising code in this vicinity to reduce the number of calls to functions with similar function, e.g., capturing the variant part of the message in a variable and invoking a single call to `message()`
  
    ```
        ...
        if (...) {
           msg <- "Features ..."
        } else {
          msg <- "..."
    } else {
        msg <- "...
    }
    message(.timestamp(), " -- ", msg)
    ```

- deco.R:78 vectorize where possible; `apply(combMulti, 1, function(x) x[1] == x[2])` looks like

    ```
    combMulti[,1] == combMulti[,2]
    ```
    
  and is vectorized because there is 1 call to the R function `==`, rathern than `nrow(combMulti)` calls. Examine all uses of iterative functions `for()`, `sapply()`, `lapply()`, `mapply()`, `apply()`, etc., for similar opportunities for vectorization.
    
- consider using the Bioconductor standard [BiocParallel][https://bioconductor.org/packages/BiocParallel] rather than snowfall for parallel computation. This will make your package more interoperable with other Bioconductor packages.

- deco.R:221 rather than using `tempdir()`, probably it makes more sense to use `tempfile()` and `dir.create()` to create a temporary, uniquely named directory; the file used here `dir.create(file.apth(temp.path, "temp"))` will not be unique within an R session.
    
- deco.R:366 use base `rowSums()` (and similar; also the CRAN matrixStats package) for vectorized row- and column-wise operations on matricies.

- deco.R:494 Looks like I'm at the end of the first function in this file! That is too long, making the parts of the function impossible to test or debug. Consider breaking this function into individual functions that perform a single step in the analysis, and that are no longer than 20 to 30 lines each.

- additionalFunctions.R:39 S4 classes should have S4 `show` methods defined, rather than S3 `print.deco` methods.

- additionalFunctions.R:121 adopt a formatting style that provides more consistent indentation and allows for lines that do not extend too far to the right, e.g., starting idented lines at a fixed indentation rather than aligned with the opening bracket

    ```
    infogenes <- suppressMessages(AnnotationDbi::select(
        x = get(pack.db), obj = names(xx),
        columns = c(attributes,id.type),
        keys = keys(get(pack.db)
        ...
    ))
    ```

man

- ok

other

- make sure that NEWS is formatted so that it can be parsed by `utils::news()`

**Comment by fjcamlab** [comment]
Hi @mtmorgan 

Thank you so much for the extended review on **20 November, 2018**, I appreciate all the comments and suggestions. I am still working on writing new simple functions for simplicity of the code, but below I will reply to each comment, clarifying what have been the principal changes from version 0.99.30 to version 0.99.40 (after revision changes):

> DESCRIPTION
> 
> - It is not necessary to include the GPL LICENSE file with your package, it is distributed with R.
> 
> - Are the packages in the Depends: field needed by the end user, or used internally to your package? If just internal to the package then they should be in the Imports: field (and import()'ed in the NAMESPACE file).

I removed the LICENSE file and re-distributed packages for Depends or Imports field accordingly in the DESCRIPTION.

> vignette
> 
> - the vignette looks like a very valuable resource, thanks for the effort creating it!
> 
> - please carefully review your LaTeX dependencies and include only those that are essential for your vignette; a common problem is that these dependencies change, and the package must be updated even when the dependency is not used or used for marginal benefit.
> 
> - It is not best practice to disable warnings globally in knitr, this hides rather than addresses problems.
> 
> - I do not recommend including installation instructions from your lab web site; instead, use standard Bioconductor installation instructions as though the package were accepted
> 
> ```
> if (!requireNamespace('BiocManager', quietly = TRUE))
>     install.packages("BiocManager"
> BiocManager::install('deco')
> ```
> Optionally, include a 'devel' installation instruction that points to a public source code repository and > uses standard R tools, e.g., BiocManager("fjcamlab/deco").
> 

Thanks for the positive comments. I disabled the `knitr` warnings modified the vignette to include installation instructions as mentioned, also offering the option of using `devtools` and GitHub repository. To avoid LaTeX dependencies' problem, we have finally chosen HTML as final file format for the vignette so I removed them.

> - 'ExpressionSet' has been replaced by [SummarizedExperiment][https://bioconductor.org/pacakges/SummarizedExperiment], which should be used whereever possible.

I replaced the example dataset structure (data/ALCLdata.rda), which used `ExpressionSet`, by a `SummarizedExperiment` structure. The vignette and examples were also re-written accordingly.
 
> - Try where possible to use data sets and packages that are available within R. For instance TCGA data is readily available using the [curatedTCGAData][https://bioconductor.org/packages/curatedTCGAData] package. Since the `curatedTCGAData` package uses `ExperimentHub`, the data is downloaded only once on the build or user machines, so the vignette chunks do not need to be marked with `eval = FALSE`.

Thanks, I modified the vignette to now download and use TCGA datasets included in `curatedTCGAData` library instead `TCGA2STAT`.

> - Using direct slot access, slot(deco_results, "featureTable") is strongly discouraged -- write and use throughout the vignette and your own R code a simple 'accessor' function to separate the interface experienced by the user from the implementation useful to the developer.

Now, the `deco-class` includes two accessors functions to extract main information: `featureTable()` and `NSCAcluster()`.

> - deco.R:16: use a named vector c(featureTable = "data.frame", ...) rather than constructing the vector in two steps. Consider adopting a convention, e.g., .slots <- ... to name variables that are not going to be visible to the user. Does this style of defining the slots outside the setClass() statement provide much additional value over defining the slots inside the setClass() tatement?. Use of data structures like data.frame() or list() as slots to some extent undermines the value of a formal class, since the content of a data.frame or list is not well-defined.

Agreed. The new definition of `deco-class` is now within `classAccessors.R` script. I chose this definition of formal class for a better final understanding of objects by a future developer, because there would be a lot of information within a typical  `deco-class` R object.

> - deco.R:33 Never change global options inside a function; it looks like your code generates warning that you are trying to suppress. Instead, write code that does not generate warnings, or if absolutely necessary use suppressWarnings() around the specific problematic code.

I removed all `options()` calls and included 'suppressWarnings' on 'bplapply' functions, since they provided always a warning "In serialize(data..." in my local machine.

> - deco.R:33 Please format your code to enable readability, rather than to fit code on one line. For instance, aim for individual lines that accomplish one task, and that are not higly nested; change
> 
> ```
> if(temp.path == tempdir() || !(temp.path %in% names(dir()))){
>   temp.path <- tempdir(); message("'temp' folder will be created in current work directory to store internal loop data.")}
> ```
> to
> 
> ```
> if(temp.path == tempdir() || !(temp.path %in% names(dir()))){
>   temp.path <- tempdir()
>   message("'temp' folder will be created in current work directory to store internal loop data.")
> }
> ```
> Note here that the message is incorrect, tempdir() points to a temporary directory somewhere on the file system, usually not in the current working directory.

> - deco.R:221 rather than using tempdir(), probably it makes more sense to use tempfile() and dir.create() to create a temporary, uniquely named directory; the file used here dir.create(file.apth(temp.path, "temp")) will not be unique within an R session.

Agreed. I made all these changes along the code to facilitate the reading, and specifically changed this message. However, I found a problem related with the temporary files and the vignette output. 

> - deco.R:40 As noted, new packages should use SummarizedExperiment rather than ExpressionSet.
> 
> - deco.R:49 and throughout: paste() inside stop() is usually not necessary, stop("foo ", 123, " bar") is rendered with foo 123 bar. This is true for message() and warning(), as well. The formatting here is also difficult to read; consider a more traditional
> 
> ```
> if (test) {
>     ## true
> } else {
>     ## false
> }
> ```

`ExpressionSet` issue is solved. I removed all paste() inside stop() or message(), and re-formatting these parts.  

> deco.R:56 avoid nesting complicated expressions, and reuse rather than re-calculate where possible (there are many places in your code where expressions are re-calculated rather than stored once in a variable and reused, e.g, in the test at deco.R:205 where all(!is.na(classes)) is invariant across the loop), e.g.,
> 
> ```
> test <- infogenes[,"CHR"] %in% c("X","Y")
> if (sum(test) > 1) {
>     data <- data[rownames(infogenes)[!test],]
> ...
> ```

Agreed, I dealt with major repetitions of code like you mentioned, and I am still working on this issue along all the code. 

> - deco.R:58 Write simple functions for commonly used expressions, e.g.,
> 
> ```
> .timestamp <- function()
>    format(Sys.time(), " %H:%M:%S")
> message(.timestamp(), "-- Features...)
> ```
> Consider revising code in this vicinity to reduce the number of calls to functions with similar function, e.g., capturing the variant part of the message in a variable and invoking a single call to message()
> ```
>     ...
>     if (...) {
>        msg <- "Features ..."
>     } else {
>       msg <- "..."
> } else {
>     msg <- "...
> }
> message(.timestamp(), " -- ", msg)
> ```

Agreed. I changed the R code accordingly for avoiding these repetitions and only calling these functions once.

> - deco.R:78 vectorize where possible; apply(combMulti, 1, function(x) x[1] == x[2]) looks like `combMulti[,1] == combMulti[,2]` and is vectorized because there is 1 call to the R function ==, rathern than nrow(combMulti) calls. Examine all uses of iterative functions for(), sapply(), lapply(), mapply(), apply(), etc., for similar opportunities for vectorization.

> deco.R:366 use base `rowSums()` (and similar; also the CRAN matrixStats package) for vectorized row- and column-wise operations on matricies.

Thanks, I reviewed iterative functions and replaced them by vectorized calculations or basic functions like `rowSums()` if possible.

> - consider using the Bioconductor standard [BiocParallel [https://bioconductor.org/packages/BiocParallel] rather than snowfall for parallel computation. This will make your package more interoperable with other Bioconductor packages.

I replaced all `snowfall` dependencies and functions by `BiocParallel`. Now, the package uses `bplapply()` function and the R code has been adapted accordingly.

> - deco.R:494 Looks like I'm at the end of the first function in this file! That is too long, making the parts of the function impossible to test or debug. Consider breaking this function into individual functions that perform a single step in the analysis, and that are no longer than 20 to 30 lines each.

Agreed. I have notably reduced the length of the three main functions of the pipeline `decoRDA()`, `decoNSCA()` and `decoReport()`, through the re-writing of separate intern functions to facilitate debug and future tests. However, I am still working on this issue trying to reduce them to minimum expression.

> - additionalFunctions.R:39 S4 classes should have S4 show methods defined, rather than S3 print.deco methods.

Thanks. I removed `print.deco()` function and now it uses 'show()' and/or 'summary()'.

> - additionalFunctions.R:121 adopt a formatting style that provides more consistent indentation and allows for lines that do not extend too far to the right, e.g., starting idented lines at a fixed indentation rather than aligned with the opening bracket
> 
> ```
> infogenes <- suppressMessages(AnnotationDbi::select(
>     x = get(pack.db), obj = names(xx),
>     columns = c(attributes,id.type),
>     keys = keys(get(pack.db)
>     ...
> ))
> ```

Thanks. I adopted the tidyverse R style for all the code, including indentation by 4.

> man
> - ok
> 
> other
> - make sure that NEWS is formatted so that it can be parsed by utils::news()
> 

I followed the instructions for plain text ‘NEWS’ files in add-on packages described in `utils::news()` man page but let me know if any change needs to be included.

However, the system still gives me the following ERROR only for OS X 10.11.6 El Capitan/x86_64. Before this last version, sometimes OS X also gave me an ERROR of size but with different estimation.
```
* Checking package size...
    * ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 507.4447 MB
        Size Requirement: 5.0000 MB
* Checking individual file sizes...
    * WARNING: The following files are over 5MB in size:
      'vignettes/DECO_cache/html/unnamed-chunk-4_17cdebb625a2e17a0cdc77246fe6ca3b.rdb
      vignettes/DECO_cache/html/unnamed-chunk-5_410ac7c8b3b24a4172650dfa9ff42f6d.rdb'
```
I have no idea why this error still persists but my vignette folder does not contain any cache from previous compilations. What do you think I should change to solve it?

Thanks for your time.

**Comment by mtmorgan** [comment]
Please adjust your vignette not to use a cache (or to use one conditional on the presence of an environment variable present on your own system) -- the build system always builds from a fresh check-out of the git repository so a cache does no good in terms of build time, but also creates the artifacts that are then included in the tar ball, making the tar balls large. Alternatively, add the cache path to the ~/.Rbuildignore file.

I'm unsure of the large tarball size reported on Mac, ignore this for now.

**Comment by fjcamlab** [comment]
> Please adjust your vignette not to use a cache (or to use one conditional on the presence of an environment variable present on your own system) -- the build system always builds from a fresh check-out of the git repository so a cache does no good in terms of build time, but also creates the artifacts that are then included in the tar ball, making the tar balls large. Alternatively, add the cache path to the ~/.Rbuildignore file.
> 
> I'm unsure of the large tarball size reported on Mac, ignore this for now.

Thanks for the comment @mtmorgan. The error disappeared and the package is well-built now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fjcamlab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("deco")`. The package 'landing page' will be created at

https://bioconductor.org/packages/deco

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
