### ISSUE TITLE
graper

### ISSUE THREAD

**Issue by bv2** [Bioconductor/Contributions#930]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bv2/graper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# graper Review

We are particular about the build report, if there are any NOTE, WARNING, ERROR, please make sure to correct them.

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## man

ok

## vignette

ok

## R

* Reformat code according to http://bioconductor.org/developers/how-to/coding-style/

	eg:
	
```
#' @importClassesFrom Matrix dgTMatrix
graperCpp_sparse_ff <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init) {
    .Call('_graper_graperCpp_sparse_ff', PACKAGE = 'graper', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init)
}
```
	
should look like,
	
```
#' @importClassesFrom Matrix dgTMatrix
graperCpp_sparse_ff <-
function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma,
	     r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose,
         freqELB, mu_init, psi_init)
{
    .Call('_graper_graperCpp_sparse_ff', PACKAGE = 'graper', X, y,
          annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi,
          d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init,
          psi_init)
}
```

The reformatted function obeys all the coding style requirements,
making your code easier to read. Use proper indentation in "if - else"
statements.


* You don't need the `else` case here, (coef.graper.R)

```
	if(include_intercept) {
		return(coefs)
	} else
		return(coefs[-1,,drop=FALSE])
```

vs (you also don't need the explicit `return` statements)


```		   
  if(include_intercept) {
      coefs
  }
  coefs[-1,,drop=FALSE])
```


* (In graper.R ) You don't need `message(paste(` unless you are
  recycling a vector. If the length of the vector is just 1, then you
  can just use `message`, there is no need of a `paste` call.
  
		message(paste("Fitting a model with", g, "groups,", n, "samples and", p , "features."))

  Do the same check for `cat` statements used in print.graper.R as
  well. You don't need `cat(paste(` unless you are recycling a vector.

* Use the package `matrixStats`, where you have functions like
  `colSds` which are highly optimized instead of `apply` statements.
  
          sf <- apply(X, 2, stats::sd)
		  
	vs
	
		  matrixStats::colSds(X)
		  
* (plotting_functions.R) not sure why you need to use
  `dplyr::bind_rows` and `dplyr::mutate` when you don't use dplyr
  anywhere else in your package. I suggest you just use native R
  functions for this, `rbind` or `rbind2`, and just add a column using
  `df$new_col = x^y`.
  
  It is not worth using these two functions and introducing a
  dependency. 
  
* Consider adding unit tests as well to your package. It will make it more robust.

**Comment by bv2** [comment]
Hi @nturaga,

thanks a lot for your comments on the package!
Following your suggestions I made the following changes to the package:
- Removed the dependency on `dplyr` (in `plotting_functions.R`)
- used the `matrixStats` package for column-wise matrix operations in `graper.R`
- removed unnecessary `paste` calls in `message` and `cat` in `graper.R` and `print.graper.R`
- removed the unnecessary return statement in `coef.graper.R` (However, I kept the else statement in your example as otherwise the second argument is returned in any case.)
- reformatted the code according to the coding style guidelines. (However, I did not change the formatting of the code in `RcppExports.R` as this is automatically (re)generated by `Rcpp::compileAttributes()` and says ` do not edit by hand`. Would you still reformat this part?)
- added some basic unit tests

The automated package build report has one WARNING now due to not requiring R version 3.6 in the DESCRIPTION, but this version seems not to be available yet.

**Comment by nturaga** [comment]
Please check the build report, update the R version from 3.5 to 3.6 to get rid of the WARNINGs. There are also quite a few NOTEs in your build report which are very easy to clean up.

We prefer having a clean build report. 

Bump the version once this is done, for a new build report. You may check locally with `BiocCheck` and `R CMD check` before pushing changes to make sure you've resolved all the issues in your build report.

**Comment by bv2** [comment]
hi @nturaga,
thanks, I got rid of the warning concerning the R version and the notes (running under Mac OS).

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bv2.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("graper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/graper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
