### ISSUE TITLE
NestLink (package type - Experiment Data )

### ISSUE THREAD

**Issue by cpanse** [Bioconductor/Contributions#931]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cpanse/NestLink

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic **and mass spectromety** data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by vobencha** [comment]
@cpanse these data look like a good candidate for ExperimentHub: https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

The Hub is an alternative to the old style data-experiment (or annotation) package. The data would be stored in AWS S3 and a lightweight software "shell" is stored in git. If you are interested in this route @lshep can help you reorganize the package.

Valerie

**Comment by cpanse** [comment]
@vobencha  excellent idea. 
@lshep can you please provide me the credentials to upload to AWS S3.

Christian

**Comment by lshep** [comment]
@cpanse Could you please email me at lori.shepherd@roswellpark.org -   I cannot post credentials on a github issue.

**Comment by vobencha** [comment]
Changing reviewer to @lshep .

**Comment by lshep** [comment]
So is there a reason for using the fig.retina=3  in the code that produces the large image sizes?  Is it possible to remove this  or is it really necessary for resolution?   
Also keep in mind when doing the git cleaning code http://bioconductor.org/developers/how-to/git/remove-large-data/   you will need to change the argument to the java command to be the file size appropriate for cleaning (the default is 100Mb  but I don't know the sizes of the files you had generated maybe 3Mb or 10Mb is more appropriate)

**Comment by lshep** [comment]
Thank you for your submission.  A few initial comments below: 

**README**
- [ ] eventually update to have Bioconductor installation instructions for your package.  
For What its worth: 
BiocManager::install also can install package from github so it can't hurt to update this either if you wanted to keep the call to install from github as the development version of your package vs the bioconductor release version of your package 


**DESCRIPTION:**
- [ ] Use Authors@R  or Author/Maintainer fields but not both
- [ ] Remove LazyData=TRUE we find it actaully slows building and installation


**INST/Scripts**
- [ ] make-data.R  can you describe in text/sudo code/or code how the data list in metadat.csv was created.  It can be text indicating download from website with specific settings or parameters etc... or accepted is what you have for the RData showing the code run to save the object ...  There is currently no real indication how these files were made neither here nor in the man files 

**Vignettes:**
I reran all displayed code manually: 

_**In simulateFlycodes.Rmd:**_

- [ ] Compute Hydrophobicity value using SSRC
```
ssrc <- sapply(peptideStd, function(x){ssrc(x$peptideSequence)})
rt <- unlist(lapply(peptideStd, function(x){x$rt}))
plot(ssrc, rt); abline(ssrc.lm <- lm(rt ~ ssrc), col='red'); 
legend("topleft", paste("spearman", round(cor(ssrc, rt, method='spearman'),2)))

```
Doesn't run. I get
```
> ssrc <- sapply(peptideStd, function(x){ssrc(x$peptideSequence)})
Error in sapply(peptideStd, function(x) { : object 'peptideStd' not found
```

- [ ] At the end 
```
the plots graph a LC-MS map.
```
What makes these plots?  I don't see plotting code? 

_**In  summaryFASTA.Rmd**_

- [ ]  Import Data into R
I believe you moved the WU160118.RData to EH and removed from extdata so this is no longer valid `system.file("extdata/WU160118.RData", package = "NestLink").`


_**In SupplementaryNote1.Rmd**_

- [ ] Camera ready summary table
When I try to run the plotting
```
rv <-lapply(unique(P$ConcGr), function(q){
pairs((P[P$ConcGr == q ,c('coli1', 'coli2', 'smeg1', 'smeg2')]),
      pch=16, col=rgb(0.5,0.5,0.5,alpha = 0.3),
      lower.panel = panel.cor,
      asp=1,
      main=q)
})
Error in pairs.default((P[P$ConcGr == q, c("coli1", "coli2", "smeg1",  : 
  object 'panel.cor' not found
```

There is also a call later on in the code that also fails with panel.cor not
found. 


**Man pages:**
- [ ] In general the documentation could be expanded on to provide more detail for all
pages but in particular: 
- [ ] You have three compose functions for creating an AA sequence but there is no
indication of how these 3 functions are different. 
- [ ] It seems like getNB and getFC are wrappers around getting predefined data - this
should be better explained. 


When finished with these updates please make sure there is a valid version bump and new build and comment back here when you are ready for re-review.  
Cheers and I look forward to working with you to get your package accepted.

**Comment by cpanse** [comment]
@lshep  We address all the [x] items. Thanks.

> Thank you for your submission. A few initial comments below:
> 
> **README**
> 
>     * [x]  eventually update to have Bioconductor installation instructions for your package.
>       For What its worth:
>       BiocManager::install also can install package from github so it can't hurt to update this either if you wanted to keep the call to install from github as the development version of your package vs the bioconductor release version of your package
> 
> 
> **DESCRIPTION:**
> 
>     * [x]  Use Authors@R  or Author/Maintainer fields but not both
> 
>     * [x]  Remove LazyData=TRUE we find it actaully slows building and installation
> 
> 
> **INST/Scripts**
> 
replaced by a make-data.Rmd vignette
>     * [x]  make-data.R  can you describe in text/sudo code/or code how the data list in metadat.csv was created.  It can be text indicating download from website with specific settings or parameters etc... or accepted is what you have for the RData showing the code run to save the object ...  There is currently no real indication how these files were made neither here nor in the man files
> 
> 
> **Vignettes:**
> I reran all displayed code manually:
> 
> _**In simulateFlycodes.Rmd:**_
> 
>     * [x]  Compute Hydrophobicity value using SSRC
> 
> 
> ```
> ssrc <- sapply(peptideStd, function(x){ssrc(x$peptideSequence)})
> rt <- unlist(lapply(peptideStd, function(x){x$rt}))
> plot(ssrc, rt); abline(ssrc.lm <- lm(rt ~ ssrc), col='red'); 
> legend("topleft", paste("spearman", round(cor(ssrc, rt, method='spearman'),2)))
> ```
> 
> Doesn't run. I get
> 
> ```
> > ssrc <- sapply(peptideStd, function(x){ssrc(x$peptideSequence)})
> Error in sapply(peptideStd, function(x) { : object 'peptideStd' not found
> ```
the corresbonding R code ist now visible
> 
>     * [x]  At the end
> 
> 
> ```
> the plots graph a LC-MS map.
> ```
> 
> What makes these plots? I don't see plotting code?
> 
> _**In summaryFASTA.Rmd**_
> 
>     * [x]   Import Data into R
>       I believe you moved the WU160118.RData to EH and removed from extdata so this is no longer valid `system.file("extdata/WU160118.RData", package = "NestLink").`
> 
> 
> _**In SupplementaryNote1.Rmd**_
> 
>     * [x]  Camera ready summary table
>       When I try to run the plotting
> 
> 
> ```
> rv <-lapply(unique(P$ConcGr), function(q){
> pairs((P[P$ConcGr == q ,c('coli1', 'coli2', 'smeg1', 'smeg2')]),
>       pch=16, col=rgb(0.5,0.5,0.5,alpha = 0.3),
>       lower.panel = panel.cor,
>       asp=1,
>       main=q)
> })
> Error in pairs.default((P[P$ConcGr == q, c("coli1", "coli2", "smeg1",  : 
>   object 'panel.cor' not found
> ```
> 
> There is also a call later on in the code that also fails with panel.cor not
> found.
> 
> **Man pages:**
> 
>     * [x]  In general the documentation could be expanded on to provide more detail for all
>       pages but in particular:
> 
>     * [x]  You have three compose functions for creating an AA sequence but there is no
>       indication of how these 3 functions are different.
> 
>     * [x]  It seems like getNB and getFC are wrappers around getting predefined data - this
>       should be better explained.
> 
> 
> When finished with these updates please make sure there is a valid version bump and new build and comment back here when you are ready for re-review.
> Cheers and I look forward to working with you to get your package accepted.

**Comment by lshep** [comment]
I apologize for the delay - I was out on holiday. 

A few last things to clean up or respond to:

**Description:**

- [ ] Please remove Maintainer field and use the designation 'cre' in the Authors@R to designate maintainer

**Vignettes:** 

_summaryFASTA_

- [ ]  Import Data into R -  I'm confused why you included the code snippet   concerning the extracting data - users wouldn't know what   `~/Download/444589.Rdata` is or contains so the clip iteself does not seem   useful, only confusing.  I would either expand more details on the background or remove this snippet and only include the shipped data component.  

_cmpPredictedMeasuredFlyCodees-

- [ ] Why not include this as a function with the package rather than showing the code? Its fine as is but just curious. 

**R/man**

_runNGSAnalysis_

- [ ] Would a user know what valid input param are? Should there be a list or helper of some sort describing the acceptable values for this param list and what the values mean? Can a param list be missing one of those input params (i.e is there a default?)

_compose.R_

- [ ] Would there be a case to use the getFC or getNB with a user provided file rather than the provided experimentHub file?  Are the files in ExperimentHub processed and unique that these function only provide a wrapper to retrieving the data or does these function provide utility for converting files of a particular format to a usable format for your functions? 


Again, I apologize for the delay.  As before please make changes and when ready do a version bump to kick off a new build and respond here addressing the above concerns. 

Cheers, 
~L

**Comment by mtmorgan** [comment]
I'm a little confused about this package. The 'Maintainer' (`cre` in `Authors@R`) is different from the owner of the repository contributing the package. Who's in charge?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cpanse.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NestLink")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NestLink

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
