### ISSUE TITLE
CluMSIDdata

### ISSUE THREAD

**Issue by tdepke** [Bioconductor/Contributions#933]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tdepke/CluMSIDdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by tdepke** [comment]
AdditionalPackage: https://github.com/tdepke/CluMSID

**Comment by LiNk-NY** [comment]
Hi Tobias, @tdepke 

Thank you for your submission. 
Please see the review below. 
If you have any questions, feel free to post them here. 

Best regards,
Marcel

---

# CluMSID #933

## DESCRIPTION

* Please add `BugReports` and `URL` fields (if available)

## NAMESPACE

* Stick to either `camelCase` or `snake_case`. Try to avoid mixing both
types.
* Avoid using a `CluMSID_` prefix. It is not necessary and can be confusing.
* Ordinary functions should start with lower case letters for instance,
`Featurelist` becomes `featureList` unless it is a class.
* You have more packages under the `Imports` field than documented in the
`NAMESPACE`. They should have some level of concordance.

## R

* Why save an `Rdata` file in `extdata` than create it in the examples
(for `access_id`)? The `extdata` should be raw data for a `read*` type of
function.
* Use `is()` to test for class memberships rather than `class(x) %in% ...`
* It would be better to use `generics` that are already established in other
packages or create your own generic and method functions for slot accession.
* Provide all the options in the `type` argument as a vector, i.e.,
`c("spectrum", "neutral_losses")` so that it is visible to the user and then use
`match.arg` to take the first one within the function.
* It is better to not assume that the user will input a `MS2spectrum` class and
check for class membership within the `getSimilarities` function.
* Avoid using `cat` and use `message` instead. Use `cat` for show methods only.
* Although R has improved copy and append methods, these should be avoided when
possible. It would be simpler to use `vapply` for looping along `featlist` in
`findFragment` and other functions. You can even make this `subsetter` check
into a helper function for reuse in other functions incl. `findNL` and
`findFragment`. 
* Replace `if else` logic in `getSpectrum` using a `switch()` call that returns
*just the unevaluated condition* i.e., `what %in% m`, `abs(what - m) <= mz.tol`,
`abs(what - m) <= rt.tol`. You would have to quote the expression and evaluate
later.
* Avoid use of `;`. You can just do `id <- mz <- rt <- c()` but this shouldn't
be necessary if you're using `lapply` (in `Featurelist`).
* Use `as(...)` coercion instead of the `convertSpectrum` function.
* Some code can be reduced in `extractMS2spectra` by using a variable when
`recalibrate_precursor` is `TRUE`
* Avoid nested `for` loops where possible.
* Why not let the user specify the column name for `mz` and `rt` in
`extractPseudospectra`? This way you don't have to check whether it is in the
`data.frame`.

Minor:
* `FUN.VALUE` in `splitPolarities` should just be `logical(1L)` it doesn't
have to be a conditional expression.
* Open up `specplot` (with `...`) for users to access additional arguments in
`plot`. This makes plotting more customizable.
* No need to test for `TRUE` within an `if` function:
`if (recalibrate_precursor)`, if you're unsure if the result will be logical,
you can use `isTRUE(recal...)`
* Avoid `2:x` sequence generation in the event that `x = 0`.
Use `seq_along(x)[-1]`

## vignettes

* Looks good.
* Consider using `BiocStyle`.
* Remember to change your download instructions to `BiocManager::install()`
once it is accepted.

**Comment by tdepke** [comment]
Hi Marcel, @LiNk-NY 
thank you for your review! I'm sorry for being so slow, I will revise the package and respond to your review in the next days.
Best regards,
Tobias

**Comment by tdepke** [comment]
Hi Marcel, @LiNk-NY 
thanks again for the review! Please find my point-by-point response below.
I look forward to receiving your feedback.
Best regards,
Tobias

> # CluMSID #933
> ## DESCRIPTION
> * Please add `BugReports` and `URL` fields (if available)

Done.
> 
> ## NAMESPACE
> * Stick to either `camelCase` or `snake_case`. Try to avoid mixing both
>   types.

I changed all names to `camelCase`.
> * Avoid using a `CluMSID_` prefix. It is not necessary and can be confusing.

All `CluMSID_` prefixes have been removed.
> * Ordinary functions should start with lower case letters for instance,
>   `Featurelist` becomes `featureList` unless it is a class.

Done.
> * You have more packages under the `Imports` field than documented in the
>   `NAMESPACE`. They should have some level of concordance.

I changed that.
> 
> ## R
> * Why save an `Rdata` file in `extdata` than create it in the examples
>   (for `access_id`)? The `extdata` should be raw data for a `read*` type of
>   function.

I did that because it would take too long to generate the respective objects
from raw data for each example. I agree that it is not ideal to save the 
`Rdata` files in `extdata`. Would it be okay to move these files to `\data`?
That would make them accessible to the user which is neither necessary
nor intended. Do you have a suggestion how to handle these files?
> * Use `is()` to test for class memberships rather than `class(x) %in% ...`

Done.
> * It would be better to use `generics` that are already established in other
>   packages or create your own generic and method functions for slot accession.

I generally agree which is why I added methods for `precursorMz`, `rtime`, `intensity`, 
`mz` and `peaksCount` from `MSnbase` that can be used to access information from 
`MS2spectrum` objects but I need additional accessor functions for `neutral_losses`,
`annotation`, `id` and `spectrum` (as a whole, not _m/z_ and intensities separately).
For the sake of consisteny, I also kept the `accessPrecursor` and `accessRT` functions.
> * Provide all the options in the `type` argument as a vector, i.e.,
>   `c("spectrum", "neutral_losses")` so that it is visible to the user and then use
>   `match.arg` to take the first one within the function.

Done.
> * It is better to not assume that the user will input a `MS2spectrum` class and
>   check for class membership within the `getSimilarities` function.

Done.
> * Avoid using `cat` and use `message` instead. Use `cat` for show methods only.

Done.
> * Although R has improved copy and append methods, these should be avoided when
>   possible. It would be simpler to use `vapply` for looping along `featlist` in
>   `findFragment` and other functions. You can even make this `subsetter` check
>   into a helper function for reuse in other functions incl. `findNL` and
>   `findFragment`.

Done.
> * Replace `if else` logic in `getSpectrum` using a `switch()` call that returns
>   _just the unevaluated condition_ i.e., `what %in% m`, `abs(what - m) <= mz.tol`,
>   `abs(what - m) <= rt.tol`. You would have to quote the expression and evaluate
>   later.

Done.
> * Avoid use of `;`. You can just do `id <- mz <- rt <- c()` but this shouldn't
>   be necessary if you're using `lapply` (in `Featurelist`).

I changed the respective line to `id <- mz <- rt <- c()` as you suggested.
> * Use `as(...)` coercion instead of the `convertSpectrum` function.

Conversion can now be done using either `as(object, "MS2spectrum")` or
`as.MS2spectrum(object)`.
> * Some code can be reduced in `extractMS2spectra` by using a variable when
>   `recalibrate_precursor` is `TRUE`

I am not quite sure if that is what you meant but I reduced the respective code from
39 to 16 lines by using a function for the precursor checking.
> * Avoid nested `for` loops where possible.

I replaced the nested for-loop in `distanceMatrix` with a combination of
`utils::combn` and `vapply`. This did not increase speed, though.
> * Why not let the user specify the column name for `mz` and `rt` in
>   `extractPseudospectra`? This way you don't have to check whether it is in the
>   `data.frame`.

The idea was to enable direct and easy input of files/objects generated with
`xcms`/`CAMERA` but they have this naming inconsistency. Therefore, I decided
to check for both possibilities rather than letting the user specify and setting
one of the possibilities as default.
> 
> Minor:
> 
> * `FUN.VALUE` in `splitPolarities` should just be `logical(1L)` it doesn't
>   have to be a conditional expression.

I changed that.
> * Open up `specplot` (with `...`) for users to access additional arguments in
>   `plot`. This makes plotting more customizable.

Done.
> * No need to test for `TRUE` within an `if` function:
>   `if (recalibrate_precursor)`, if you're unsure if the result will be logical,
>   you can use `isTRUE(recal...)`

This has been changed in all respective functions.
> * Avoid `2:x` sequence generation in the event that `x = 0`.
>   Use `seq_along(x)[-1]`

Done.
> 
> ## vignettes
> * Looks good.
> * Consider using `BiocStyle`.

I would like to use `BiocStyle` but the problem is that `BiocStyle::html_document`
leads to rather large file sizes, comparable to `rmarkdown::html_document`, whereas
`rmarkdown::html_vignette` produces much smaller files. As `CluMSID` is already
quite big, I had to reduce the file sizes of the vignettes and thus decided to use
`rmarkdown::html_vignette`. I am open to suggestions regarding this issue.
> * Remember to change your download instructions to `BiocManager::install()`
>   once it is accepted.

I will.

**Comment by LiNk-NY** [comment]
Hi Tobias, @tdepke 
Thanks for making those changes. It's looking good! 
Thank you for submitting to Bioconductor!
Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tdepke.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CluMSIDdata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CluMSIDdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tdepke.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CluMSID")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CluMSID

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
