### ISSUE TITLE
rScudo

### ISSUE THREAD

**Issue by Matteo-Ciciani** [Bioconductor/Contributions#936]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Matteo-Ciciani/rScudo

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Matteo, @Matteo-Ciciani 
Thank you for your submission. 
Please see your review below. 
If you have any questions, please post them here on the issue tracker. 

Best regards,
Marcel

---

# rScudo #

* Good work on putting this together. The package looks clean and follows
the Bioconductor guidelines. There are a few things to consider before
accepting this package.

## DESCRIPTION

* Please support `SummarizedExperiment` as a possible input in your package

## NAMESPACE

* It might not be necessary to include the `scudo*` prefix in your function
names, these could possibly be methods for your class.
* It may be better to export a `Scudo` class and have a more expansive API
that would include the `results` function (as in `results(Scudo)`)

## R

* It seems like you could extend `SummarizedExperiment` to accomodate the
specifications of the `ScudoResults` class.
* You can also shorten the validity checks by implementing a helper function
for some of the slots in the class that use the same checks (e.g.,
`*Signatures`)
* Add support for `SummarizedExperiment` inputs
* (optional) Look into using `S4Vectors::isSingle*` helper functions to check
vectors of length 1.
* Create a mini-converter function to check `scudo*()` expression data inputs
and return an object you can work with. Many of your functions would use this
helper check function.
* Use your own API wherever possible, including inside your validity checks.
* Since you have so many objects to check, you can create an `are.logical`
helper function to check `is.logical` on a number of objects, for example:
`are.logical(featureSel, groupedFoldChange, parametric)`

Minor:
* Why not use the same defaults from RCy3 in `scudoCytoscape`? You wouldn't
have to worry about `base.url` being `NULL`. 
* Rename `fit`/`predict`/`prob` functions to not clash with other model
functions.

## vignettes/

* Nicely put together.

**Comment by Matteo-Ciciani** [comment]
Hi Marcel, @LiNk-NY

Thank you for the nice review, I will start implementing the suggested changes in the next few days.

I would like to ask you a couple of clarifications:
 
> ## NAMESPACE
> 
>     * It might not be necessary to include the `scudo*` prefix in your function
>       names, these could possibly be methods for your class.
> 
>     * It may be better to export a `Scudo` class and have a more expansive API
>       that would include the `results` function (as in `results(Scudo)`)
> 
> 
> ## R
> 
>     * It seems like you could extend `SummarizedExperiment` to accomodate the
>       specifications of the `ScudoResults` class.

If I got it correctly, here you are suggesting to define a class `Scudo` that replaces my class `ScudoResults` and that extends `SummarizedExperiment`. The functions that currently take as input a `ScudoResults` object (which are only `scudoTest` and `scudoNetwork`) should become methods of `Scudo`. However, it's not clear to me what the `results` function should do, since the user would already have getters to access the slots of `Scudo`. Are you suggesting that the class `Scudo` should contain not only the results of the analysis, but also the input data represented as a `SummarizedExperiment`?

>     * Rename `fit`/`predict`/`prob` functions to not clash with other model
>       functions.

I can't do this without causing an error in `caret::train`. In order to define a customized model in `caret`, one has to define a named list containing functions named  `fit`/`predict`/`prob`, as specified in the `caret` [manual](https://topepo.github.io/caret/using-your-own-model-in-train.html). However, I don't see how the functions `fit`/`predict`/`prob` could clash with other model functions: their binding and enclosing environments are the execution environment of `scudoModel`, so they are not visible from the global environment. Am I missing something?

Best regards,
Matteo

**Comment by Matteo-Ciciani** [comment]
Hi Marcel, @LiNk-NY 

We have implemented some of the changes suggested in your review. You will find a description below. I'm still waiting for an answer to my previous post before making any modification to the class.

Best regards,
Matteo

> ## DESCRIPTION
> 
>     * Please support `SummarizedExperiment` as a possible input in your package

`SummarizedExperiment` objects are now a supported input for my functions

> ## R
>     * Add support for `SummarizedExperiment` inputs

Support for `SummarizedExperiment` inputs has been added

>     * (optional) Look into using `S4Vectors::isSingle*` helper functions to check
>       vectors of length 1

I defined some helper functions that perform more stringent checks than `S4Vectors::isSingle*` functions, like `.isSinglePositiveNumber`. This greatly simplifies the code needed to check the input of my functions.

>     * Create a mini-converter function to check `scudo*()` expression data inputs
>       and return an object you can work with. Many of your functions would use this
>       helper check function.

We implemented a `.inputConverter` function that converts the expression data inputs into `data.frame`s.

>     * Since you have so many objects to check, you can create an `are.logical`
>       helper function to check `is.logical` on a number of objects, for example:
>       `are.logical(featureSel, groupedFoldChange, parametric)`

I preferred to define the function `.isSingleLogical`, similar to the `S4Vectors::isSingle*` helper functions. This made the code much shorter, since it removed the need to run `is.logical(x)`, `length(x) == 1L`, `!is.na(x)` and `is.vector(x)` on every logical parameter.

> Minor:
> 
>     * Why not use the same defaults from RCy3 in `scudoCytoscape`? You wouldn't
>       have to worry about `base.url` being `NULL`.

`scudoCytoscape` now uses the default `base.url`.

**Comment by LiNk-NY** [comment]
Ciao Matteo, @Matteo-Ciciani 

> If I got it correctly, here you are suggesting to define a class Scudo that replaces my class ScudoResults and that extends SummarizedExperiment. The functions that currently take as input a ScudoResults object (which are only scudoTest and scudoNetwork) should become methods of Scudo. However, it's not clear to me what the results function should do, since the user would already have getters to access the slots of Scudo. Are you suggesting that the class Scudo should contain not only the results of the analysis, but also the input data represented as a SummarizedExperiment?

After looking it over, I think it is better to just have a `ScudoResults` class. 

> I can't do this without causing an error in caret::train. In order to define a customized model in caret, one has to define a named list containing functions named fit/predict/prob, as specified in the caret manual. However, I don't see how the functions fit/predict/prob could clash with other model functions: their binding and enclosing environments are the execution environment of scudoModel, so they are not visible from the global environment. Am I missing something?

If this is the case, you can leave them as-is as long as they're not exported. 

Thanks, 
Marcel

**Comment by Matteo-Ciciani** [comment]
Hi Marcel, @LiNk-NY 
thank you for the good news and for your suggestions to improve our package.
Kind regards,
Matteo

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Matteo-Ciciani.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rScudo")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rScudo

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
