### ISSUE TITLE
bigPint

### ISSUE THREAD

**Issue by lrutter** [Bioconductor/Contributions#939]
- Repository: https://github.com/lrutter/bigPint

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

**Comment by lrutter** [comment]
I do have one NOTE for R CMD BiocCheck: Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin credentials).  Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel.

However, I believe I joined bioc-devel mailing list one week ago. Thank you.

**Comment by lrutter** [comment]
I have one remaining ERROR and WARNING that I am trying to resolve:

1) Is it possible the remaining ERROR is something I cannot resolve on my end? It seems it could be more related to the merida2 operating system.

2) I am unsure how to resolve the remaining WARNING. I did run R CMD build --resave-data bigPint, which created the tar ball. I copied the compressed data from the tar ball into the package data, but this warning remains. The data sizes on my GitHub appear to be the recommended compressed sizes given by this warning as well. Any ideas on why this WARNING may not resolve despite my data files on GitHub having the recommended compressed sizes? 

Thank you!

**Comment by dvantwisk** [comment]
Here is my review of your package. It looks very well written but there a few reoccurring issues that I need to address. [REQUIRED] tags indicate changes that must be made or addressed while [CONSIDER] tags indicate changes that are optional but advisable. Please message me back if you have questions or when you are finished making changes so that I can have another look.

GENERAL:
- [REQUIRED] The package is 103MB in size. We generally like to see packages
that are no larger than 5MB in size. It looks like your data directory is too
large. To correct this, you'll either need to make an Experimental Data package
or an Annotation Data package (see https://www.bioconductor.org/developers/package-submission/#experPackage and https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages).
It also seems like a lot of the size if due to images. Are all images necessary
or is it possible for the package to generate them? We may be able to show some
leniency, but it would be helpful to reduce the size of the package as much as
possible before then.
- [REQUIRED] This package produces a number of files that are saved by default
to the user's working directory. Are these files necessary to save within the
function, that is, can the functions just return the object so that the user can
save the themselves. If these files must be saved, it would be better to save
them to a `tempdir()` by default so that they don't clutter the users working
directory.
- [CONSIDER] Use `seq_along()` in place of `seq(1, length(var))`. `seq_along()`
is slightly faster. This can be done in multiple files throughout your package.

DESCRIPTION:
- [CONSIDER] specify a version of the GPL Licence to use.

R/helperMakeHex.R
- [REQUIRED] L7-16: This double for-loop seems inefficient. Also an
inefficient copy-and-append pattern is used here be iteratively creating
`x` and `y`. This is inefficient because for each time elements are added
to `x` or `y`, `x` or `y` must first be resized to allocate more room for
the extra elements and then the existing elements must be moved to this
new array. Please change to code to:
```
seqVec1 <- seq_along(sampleIndex1)
seqVec2 <- seq_along(sampleIndex2)
index1 <- sampleIndex1[seqVec1]
index2 <- sampleIndex2[seqVec2]
x <- unlist(datSel[,index1])
y <- unlist(datSel[,index2])
```

R/helperMakePairs.R
- [REQUIRED]L3-7: Similar issue as in `R/helperMakeHex.R`:
```
seqVec <- seq_along(colNames)
colGroups <- vapply(seqVec, function(i){
    strsplit(colNames[i],"[.]")[[1]][1]
}, character(1))
```

R/helperSMFC.R
- [REQUIRED]L18-31,38-47: Similar issue as in `R/helperMakeHex.R` but this time
with lists. Use lapply to declare `names_list` and `data_list`. Also modify
the creation of `indexPoints` accordingly.

R/helperSMHex.R
- [REQUIRED]L16-29: Similar issue as in `R/helperSMFC.R`

R/helperSMOrth.R
- [REQUIRED]L19-32,40-46: Similar issue as in `R/helperSMFHex.R`

R/helperSMPoints.R
- [REQUIRED]L54-68: Similar issue as in `R/helperSMFHex.R`

R/helperTestData.R
- [REQUIRED]L25-30: Declare `colGroups` and `colReps` without copy-and-append
pattern.

R/helperTestDataMetrices.R
- [REQUIRED]L21-36: Declare `colGroups` and `colReps` without copy-and-append
pattern.

R/helperTestDataMetricLitreApp.R
- [REQUIRED]L16-21,53-61: Declare `colGroups` and `colReps` without
copy-and-append pattern.

R/helperTestDataMetricsVolcano.R
- [REQUIRED]L24-29,60-74,78-86: Declare variables without using copy-and-append
pattern.

R/helperTestDataMetricsVolcanoApp.R
- [REQUIRED]L24-29,58-58,72-80: Declare variables without using copy-and-append
pattern.

R/plotClusters.R
- [CONSIDER]L141: Use `match.arg()`. For example in the function plotClusters,
the parameter `aggMethod` can be delcared as
`aggMethod = c("ward.D", "ward.D2", <the rest of the possible value as a character list>)`
within the function declaration. The user's selected value can then be obtained
using `aggMethod <- match.arg(aggMethod)` within the function. The default value
is the first element in the vector (in this case `ward.D`). This way of doing
things is preffered because `match.arg()` will throw an error if the user gives
on unacceptable argument as input. It also allows the user to see possible
inputs by simply typing the function name `plotClusters`. This can be used in
other functions in this package.

- [REQUIRED]L157: Declare `ret` using `lapply()`.

R/plotLitres.R
- [REQUIRED]L97: Declare `ret` using `lapply()`.

R/plotPCP.R
- [REQUIRED]L103: Declare `ret` using `lapply()`.

R/plotVolcano.R
- [REQUIRED]L111: Declare `ret` using `lapply()`.
- [REQUIRED]L149-153: Other variables that need to be declared without
copy-and-append pattern.

vignettes
- [REQUIRED] I am seeing `eval=FALSE` used liberally within the vignettes. Since
the vignette code is meant to be functional to the user, it ought to be run on
build in order to verify that it is functional. Is there a reason why
`eval=FALSE`'s are being used here?

**Comment by lrutter** [comment]
Thank you for a thorough review. The match.arg() method is very helpful. I believe I took into account all the [REQUIRED] and [CONSIDER] fields, except for the first and last one (which I will discuss below). I updated the vignette to reflect that the default directory for locally saving images is tempdir(), instead of the current working directory.

Regarding the last [REQUIRED] field, I used eval=FALSE in the vignettes for two types of examples:

1) When shiny applications are deployed (examples of this are L43, L63, L85, L114 in interactive.Rmd). Shiny applications cannot be deployed in pkgdown, which I used to generate the vignette. Instead, embedding shinyapps.io examples in an iframe is recommended for didactic purposes (https://github.com/r-lib/pkgdown/issues/838).

2) When showing an example where the user chooses not to return their static graphics in a list object in the R console and instead saves them in tempdir(). In these examples, I did not evaluate the command as it was not needed to generate any object in particular, but was only needed to simply explain that running the command would save images in tempdir(). An example of this is L139 of static.Rmd.

Regarding the first [REQUIRED] field, I may need some help/advice. I did not receive any ERRORS or NOTES about package size when running Bioconductor checks. Specifically, I used the following three commands: R CMD build --resave-data bigPint; R CMD check bigPint_0.99.5.tar.gz; R CMD BiocCheck bigPint_0.99.5.tar.gz. For me, the bigPint_0.99.5.tar.gz file was about 3.8MB.

There are a few items that are in my GitHub repository (https://github.com/lrutter/bigPint) but are in .Rbuildignore (and are therefore not built or included in the .tar.gz file). Some of the largest of these non-built files are in the data/ directory. There are 8 data files on my GitHub repository, but I am only building four of them (soybean_cn_sub.rda, soybean_cn_sub_metrics.rda, soybean_ir_sub.rda, soybean_ir_sub_metrics.rds). These files contain the term “sub” because they are small subsets of their corresponding larger four data files (soybean_cn.rda, soybean_cn_metrics.rda, soybean_ir.rda, soybean_ir_metrics.rda). I created the four “sub” datasets to save space in the package. Another item that is in the GitHub repository but not in the build process is the inst/shiny-dashboards folder. I wonder if any of these files are counting toward the 103MB that you are observing? What factors might cause us to see such discrepancies in package size?

There are some images, mostly located in the inst/shiny-dashboards/*/www directories. These are pre-made screenshots that are included in the interactive graphic functions in the package (plotLitreApp.R, plotPCPApp.R, plotSMApp.R, and plotVolcanoApp.R). These images are displayed in the interactive applications in an “About” tab that instructs users how to use the interactive applications. I think they can be helpful for users and may be difficult/impossible to directly generate by the package. Other images (in the vignette) are all generated by the package.

Thank you again for your feedback. I am happy to make additional changes to meet the expected criteria and improve the package.

**Comment by dvantwisk** [comment]
It seems that the repo size actually isn't an issue. I didn't notice that `.Rbuildignore` trimmed down the `.tar.gz` size so much.

The use of `eval=FALSE` seems to be acceptable as well since the shiny app would need to be run interactively and simply saving the file doesn't seem to be essential functionality (although `tempdirs` will be removed after the build process). Just to be certain, though, does the process in (2) essentially only save data or run something interactively? If it performs any other user functionality it would be useful to remove the `eval=FALSE`s.

Aside from that, can you perform a version bump?

**Comment by lrutter** [comment]
Thank you for confirming about the repo size. The eval=FALSE process in (2) only saves static images to tempdir(); it does not run anything interactively or perform other user functionality. Yes, I just performed a version bump as well.

**Comment by dvantwisk** [comment]
Hello,
I apologize for the wait. I've reviewed all the changes you made and they look great! I am ready to accept this package as long as you are no longer making changes. Please respond if you intend to make more change or want me to accept the package now.

**Comment by lrutter** [comment]
Hello:

Thank you for the update and I am glad to hear the changes look good. I can confirm I am not making changes to the packages at this time. Thanks again for your support in making this package available on Bioconductor!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lrutter.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bigPint")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bigPint

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
