### ISSUE TITLE
cola

### ISSUE THREAD

**Issue by jokergoo** [Bioconductor/Contributions#941]
- Repository: https://github.com/jokergoo/cola

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment]
Hi @jokergoo ,

Thanks for this new contribution.

@mtmorgan will provide a full review but since I already started to look at cola before the change of assignee, I'll share the notes I had to far:

1. Some of your functions use the venneuler package internally so venneuler needs to be added to the Suggests field.

2. Same thing for packages GetoptLong, kohonen, and NNLM, which are used in the vignette.

3. cola depends (directly and indirectly) on 114 packages (that's the number of packages loaded via a namespace as reported by `sessionInfo()` after doing `library(cola)`). Packages with so many dependencies tend to be fragile and hard to maintain. Please try to reduce the number of dependencies.

4. The vignette should explain what the input matrix should typically be, what kind of data it should contain, how the data should be organized. Given that many clustering algorithms take a distance matrix as input, it would not hurt to clarify that the input matrix for cola is not expected to be a distance matrix but a matrix of counts or other measurements, where the rows represent the features being measured and the columns the various observations or samples. Also please clarify what is being clustered, the rows or the columns.

5. Why isn't the flowchart listing the general steps not reflecting the 8 steps described below it. Maybe it does, but the steps are named differently so it's hard to tell (i.e. it makes it hard to see which step on the flowchart corresponds to which step in the text below). Also the layout and arrows of the flowchart is confusing. For example why is the top-right red box (which seems to correspond to step 1 i.e. to the "clean the input matrix" step) placed on the side of the "input matrix" box and with an arrow pointing at it? If the arrows reflect the flow of operations, this step should be placed after the input matrix and not before. Finally what's the meaning of the color of the boxes (dark blue, light blue, orange, red)?

6. Your readers should be able to execute the code you show in your vignette. When I copy/paste the 1st line of code shown in your vignette, I get an error:
    ```
    data = adjust_matrix(data)
    # Error in apply(m, 1, function(x) sum(is.na(x))/length(x)) : 
    #   dim(X) must have a positive length
    ```

7. Also lines of code (like `library(cola)`) that are necessary for the visible code to work should not be hidden. Keep in mind that your readers typically look at the HTML version of the vignette, not at its source.

8. Please use `<-` instead of `=` for assignments.

9. Please set rownames on the input matrix used in the examples of `adjust_matrix()` so the user can see which rows were removed.

10. It is really not expected and not a good property that multiplying or dividing a matrix by a constant has an impact on the rows removed by `adjust_matrix()`:
    ```
    set.seed(123)
    m <- matrix(rnorm(40), 8, dimnames=list(letters[1:8], LETTERS[1:5]))
    m[1, 1] <- 1000
    rownames(adjust_matrix(m))
    # 1 rows have been removed with too low variance (sd < 0.05 quantile)
    # [1] "a" "b" "d" "e" "f" "g" "h"
    rownames(adjust_matrix(m/1e6))
    # 6 rows have been removed with zero variance (sd < 1e-6).
    # 1 rows have been removed with too low variance (sd < 0.05 quantile)
    # [1] "a"
    ```
    In the absence of some kind of normalization process, treating variance < 1e-6 like zero variance is not a good idea.

11. Improve your coding practice. In particular you should fully embrace the DRY principle (Don't Repeat Yourself principle) as best practice in software engineering. For example defining 2 almost identical functions, like `compare_to_highest_subgroup()` and `compare_to_lowest_subgroup()`, which are 42 lines each, where only 1 line differs between the 2 functions, should be avoided. Code with so much repetition (generally obtained by copy/paste) is known to be hard to maintain and prone to bugs.

Best,
H.

**Comment by mtmorgan** [comment]
I do not have substantial additional comments. I agree strongly with Hervé's concern about number of package dependencies. Consider also adopting the use of `seq_along()` and `seq_len()` for more robust definition of iterations.

**Comment by jokergoo** [comment]
Hi @hpages and @mtmorgan , I am sorry for being absent! First I would like to thank you both for your comments on my package! I have been working on it slowly because I have to work on my main projects after the new year's holiday... Anyway, I will try to spend more time on this package and improve my package according to your comments as much as possible.

**Comment by jokergoo** [comment]
Dear @mtmorgan and @hpages ,

I have made following changes according to your comments:

1. The venneuler package is added to Suggests field.

2. Since GetoptLong is already in Imports fields, I added kohonen and NNLM to Suggests.

3. I didn't know it loads that many packages. It is basically because the data.tree,
dendextend and samr packages load many other packages. Fortunately, they are only used
in a small part of the analysis in the cola package and I have moved them to Suggests field.
Now the number packages loaded has been reduced to 42 after `library(cola)`.

4. Now I have explained clearly on the type and format of the matrices for cola analysis in the vignette, in the section "The input matrix". Also I have clarified the subgrouping are only applied
on samples, which are on columns.

5. I have remade the flowchart to make it easier to read and correspond to the steps listed
in the vignette. There is also legend to explain different elements in the flowchart.

6. There are some chunks of code that do not run when building the vignette because they are
time-consuming, and these code are mainly for demonstration purpose. Now for the chunks
that are not runnable, I added a comment line in each chunk to explictly clarify to the readers
that they are only for demonstration.

7. Yes, I have added this in the vignette.

8. I know this is recommended in Bioc, but is it mandatory? I am more used to "=" for assignments.

9. The row names are added to the matrix in the example.

10. The aim of this adjustment is to remove rows with zero variance. Now I have change to code
by using `x == 0` to test whether x is zero.

11. This function has been improved.

12. I have adjusted to use `seq_len()` and `seq_along()` for looping. You might still see many Notes for using `seq_len()`/`seq_along()` in `R CMD BiocCheck`. These places basically construct vectors and I can make sure in `1:x`, `x` is larger than 1.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jokergoo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cola")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cola

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
