### ISSUE TITLE
(inactive) NPA

### ISSUE THREAD

**Issue by sgubianpm** [Bioconductor/Contributions#943]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pmpsa-hpc/NPAModels

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sgubianpm** [comment]
AdditionalPackage: https://github.com/pmpsa-hpc/NPA

**Comment by lshep** [comment]
Please correct the WARNINGS and NOTES before a more thorough review takes place.  Also the AdditionalPackage did not get built as it was added before the package was out of the "awaiting moderation" step.  Please repeat the call to have that package also built.   Please also ensure both packages have set up the [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) so that version bumps produce new builds

**Comment by lshep** [comment]
Do you plan on updating your package soon?

**Comment by sgubianpm** [comment]
@lshep , thanks for your note. Yes. I pushed yesterday an update to fix the warnings, but I may have done a mistake with the webhook, it has not triggered a new build...

**Comment by lshep** [comment]
From the look of your commit history at  https://github.com/pmpsa-hpc/NPAModels  the last commit was 4 days ago and no commit introduced a version bump -  The webhook requires a valid version bump (in this case 0.99.0  would become 0.99.1 in DESCRIPTION file)  in order to trigger a new build -  But yes please also check your webhook -  
  
Also again please redo AdditionalPackage: https://github.com/pmpsa-hpc/NPA   as it didn't register because the package was not under review yet as indicated in the message thread -

**Comment by sgubianpm** [comment]
AdditionalPackage: https://github.com/pmpsa-hpc/NPA

**Comment by lshep** [comment]
Please fix the [build errors for NPA](http://bioconductor.org/spb_reports/NPA_buildreport_20181210123238.html)

Please also clean the [NOTES/WARNINGS in NPAModles](http://bioconductor.org/spb_reports/NPAModels_buildreport_20181210123414.html)

**Comment by lshep** [comment]
There have been no further updates -  

NPA continues to ERROR 
NPAModels continues to have significant WARNINGS/NOTES

We expect maintains to be actively engaged during the submission process. If your packages are not updated within the next week we will close this issue for inactivity.  The package can be reopened when you have more time to work through the submission process.

**Comment by sgubianpm** [comment]
@lshep, Thanks a lot. Bumped. I am now working the NPA build error...

**Comment by lshep** [comment]
Sounds good!  Thanks for the update!

**Comment by lshep** [comment]
You can ignore this ERROR for NPAmodels it is on our end as the builders were being updated and rebooted -

**Comment by sgubianpm** [comment]
Thanks, yes I was thinking so as I saw that the error was coming from the bioc/VIEWS url not reachable during the build... Thanks a lot!

**Comment by mtmorgan** [comment]
```
zzz.R:    if (!exists(x = '.npa_models')) {
zzz.R:        assign(".npa_models", new.env(hash = TRUE), envir = .GlobalEnv)
```
It's generally considered bad practice to assign symbols into the global environment; that is for users. The usual practice when creating package-specific space is to create an environment in the package name space, for instance just add the line

    .npa_models <- new.env(hash = TRUE)

to any of your source files

    NPAModel.R:    get_data = function() get(x = private$data_name, envir = .npa_models)

Probably it is more straight-forward to assign a function in the `.npa_models` environment, and use it

    .npa_models$get_data <- function() .npa_models$private$data_name
    .npa_models$get_data()

Instead of retrieving the environment and then populating it using `data()`

    load_model.R:    envir <- get('.npa_models', envir = globalenv())
    load_model.R:    do.call("data", list(data_name, envir=envir))

use `saveRDS()` / `readRDS()` to save and retrieve single objects that are assigned directly to symbols, maybe `.npa_models[[data_name]] <- readRDS(...)`. Or perhaps using the functions makes the need for `.npa_models` unnecessary?

**Comment by lshep** [comment]
Still waiting on the revisions to NPA -  But here is a review awhile for NPAmodels based on the last build report -  

**General**
- [ ] can a user use/create their own data for use or is this strictly limited to the data you have provided? 
 
**Build Report**
- [ ] See comment above from @mtmorgan about global environment.  This should be corrected.
- [ ] Please fix the notes about Avoiding 1:... use seq_len or seq_along instead
- [ ] getLQ.R may be reduced in line length if you move the internal helper functions to outside the function call.

**Description**
- [ ] As NPAmodels is an experiment data package the biocViews terms should come from the experiment data section of terms not the software terms.  http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData

**Vignette**
- [ ] Completely optional but I would recommend just NPAModels rather than NPAModels-package for the file name as this command in R is more intuitive to just use the package name `> vignette("NPAModels-package")`

**Man Pages**
- [ ] load_models/load_model/getLQ
don't comment out the code in the example portion.  The code should be run at least once in either the man/test/vignette.  As this is the only place the code occurs out of those possibilities it should be run.  This allows for the capture of ERRORs.  
Case in point the getLQ exxample does not run 
```
> data(Hs__CFA__Apoptosis__0__0__1) 
> Hs__CFA__Apoptosis__0__0__1 <- getLQ( Hs__CFA__Apoptosis__0__0__1, verbose = TRUE)
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
```

- [ ] NPAModel
This is confusing without an example to understand how this object is created. include an example. 

- [ ]  All dataset man page documentation
 need a description about how the data was collected/generated, any sort of filtering or standards used, etc ... where did this data come from and how was it generated. If you feel it is overkill in the man pages directly this information can be provided with an inst/scripts/ directory that contains a text file with code/sudo code/ or just descriptive text describing the above information. 

**R code/coding**
- [ ] load_model/load_models
when a file match isn't found perhaps suggest list_data() as that seems to be the definitive matches of species/family/name available 
i.e
```
> load_model(family = "CFA", name = "Cell_Cycle") 
Model: Hs__CFA__Cell_Cycle__0__0__1 not found
NULL
```
- [ ] getLQ
* We generally recommend pulling out nested functions (perhaps putting in a separate R script like utils.R or helpers.R) This allows for better readability of the main function rather than it getting sections based on additional helper functions (optional request - fine to leave as is) 
* Model argument - Are these data object lists standard output from some instrumentation? How would one construct this "model" argument themselves?
* Is there information on the algorithms used to calculate the extra metrics? what are they? where do these come from and why are they important? This information is missing and should be expanded on either in the man page and/or vignette
- [ ] minimizeNetwork
*  typo in man page "cleanded".   
* why is this important or necessary? Seems unclear to why this exists


Please address the above issues and when ready perform a version bump on NPAmodels for a new build report.  Please also comment back here addressing the above concerns and how they have been addressed. 

Please also comment when you have pushed changes and are ready for a review of NPA. 

Thank you.

**Comment by sgubianpm** [comment]
@mtmorgan , @lshep 
Thanks a lot for your comments. I will adress them and get back to you.

**Comment by lshep** [comment]
Just checking in, is there any progress on this?

**Comment by sgubianpm** [comment]
Hi @lshep,
Thanks a lot for your message.
I am working on addressing the comments. Bumped version will come early next week.

**Comment by lshep** [comment]
We are closing this issue for now for inactivity.  when you are ready for a re-review - please request the issue be reopened _before_ the version bump for a new build report.
