### ISSUE TITLE
PCAtools

### ISSUE THREAD

**Issue by kevinblighe** [Bioconductor/Contributions#951]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kevinblighe/PCAtools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kevinblighe** [comment]
I am somewhat confused by the error. When I build it on my computer, the tarball is just 3.4MB.

**Comment by Kayla-Morrell** [comment]
I built your package locally on my computer and got a tarball size of 8.1MB. Please look at the link below, perhaps you have some legacy products in the directory that my have to be removed. 

http://bioconductor.org/developers/how-to/git/remove-large-data/

**Comment by kevinblighe** [comment]
Hello Kayla, the package has now built successfully on all systems.

**Comment by Kayla-Morrell** [comment]
Hello Kevin, 
I am finishing up your review this week (I was out of the office for the holidays) and I should have comments for you early next week. Thanks for checking in.

**Comment by Kayla-Morrell** [comment]
Hi @kevinblighe,

Thank you for submitting to Bioconductor. Please see the initial review of your package below:

**DESCRIPTION**

Good description of package

- [ ] SUGGESTION: Add additional author (Myles Lewis) from the vignette to the DESCRIPTION file.

Everything else looks good

**NAMESPACE**

Looks good

**vignette**

- [ ] REQUIRED: Under Section 3 Quick start, when checking that sample names match exactly between pdata and expression data your code seems a bit redundant. I would simplify it to just `all(colnames(x) == rownames(metadata))`.

- [ ] SUGGESTION:  The subsection headings seem more descriptive than the figure captions. I would shorten the heading and use the wording for the caption. For example, section 3.1 could be "A SCREE plot" and the caption could be "Figure 1: A basic SCREE plot to show the proportion of explained variance by PC".

- [ ] REQUIRED:  Section 4.3, there are some typos in the first sentence (lines 340 & 341). The word squeezing is misspelled and I believe you were trying to say 'squeezing every last ounce of information out of data,...', please make the necessary changes.

- [ ] REQUIRED: Section 4.5, the beginning of the second sentence (line 499) doesn't read right to me ("This is also and mostly untapped resource in the era..."). Please edit or let me know if I am mistaken.

- [ ]  REQUIRED: Section 4.5, the last sentence talking about `eigencorplot` (line 506) does not show the function name as being different from the other text. Please format this accordingly.

- [ ] REQUIRED: Section 4.5, below the two chunks of code for `eigencorplot`, the section of text has a misspelling of 'statistically' (line 583). Please edit this.

- [ ] SUGGESTION: Section 4.6, I would have a title above each panel, and decide if all should be bold or not (E is the only one that isn't bold).

- [ ]  SUGGETION: When building the vignette using `devtools::build_vignettes()` there are errors for any of the chunks of code with extra line spaces (ex6 - ex18). I assume this is because you didn't want the code being on a single line in the vignette. To eliminate these errors you can add `tidy = FALSE` when defining the R code chunks. Then you can get rid of the extra space (if you want), the R code will not be on a single line, and `devtools` will be happy.

** R files** 

- [ ] REQUIRED: Make sure your R files use either `seq_len()` or `seq_along()` and keep it consistent throughout your code.

- [ ] SUGGESTION: `pca.R` Looking at the if statements enforcing the rule that `rownames(metadata)` is the same as `colnames(mat)` when metadata is specified (starting at line 12), the second if loop could be simplified by using just `if(!all(colnames(mat) == rownames(metadata)))`.

- [ ] SUGGESTION: `plotloadings.R` Where you build a consensus list of variables that will be included (starting at line 67), remove the `TRUE` for the two`which` statements. This is redundant.

- [ ] REQUIRED: `screeplot.R` Your second `if` statement needs to be corrected (starting at line 85). I think you were looking for `if (drawCumulativeSumPoints == TRUE)` but you have `drawCumulativeSumLine`.

** man pages**

- [ ] REQUIRED: For all man pages, the title should not be the name of the overall package. It should be a title pertaining to the man page.

- [ ] REQUIRED: For all man pages, `Description` and `Detail` should be different. The details should provide any other important details of how the function operates. Details are optional so if you have nothing else to add I would remove this.

- [ ] SUGGESTION: For all man pages, dealing with the wording of argument descriptions. It seems that when the argument is logical, you use a question for the description. This doesn't seem like the best practice. I would just explain that it is `logical, indicating where or not...`.

Everything else looks good. Comment back here with updates that have been made and when the package is ready for a re-review.

Best,
Kayla

**Comment by kevinblighe** [comment]
Hey Kayla, thanks very much! I have implemented the changes where possible. I also added a new simple `getLoadings` function, and modified the `pairsplot` function in order to add a general plot title (previous functionality resulted in a title being added for each individual plot in the `pairsplot` plot space).

The only point from your list about which I was not sure was this:
`REQUIRED: Section 4.5, the last sentence talking about eigencorplot (line 506) does not show the function name as being different from the other text. Please format this accordingly.`

Kind regards,
Kevin

**Comment by Kayla-Morrell** [comment]
Hey Kevin, in previous sections (like section 4.4) you distinguish functions or variables with single quotes. So if you do something like "'eigencorplot' is build upon..." it will help distinguish it from the rest of the text. Just a minor formatting thing. 

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinblighe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PCAtools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PCAtools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
