### ISSUE TITLE
PrInCE (predicting interactomes from co-elution data)

### ISSUE THREAD

**Issue by skinnider** [Bioconductor/Contributions#957]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fosterlab/PrInCE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Michael, @skinnider 

It doesn't appear that you are using Bioconductor dependencies in your package. 
Please make sure that you are importing and providing support for Bioconductor
classes in the same area of interest as your package. Please browse the BiocViews
section on the Bioconductor website. 

Best regards,
Marcel

**Comment by skinnider** [comment]
Hi Marcel @LiNk-NY,

I took a look at the Proteomics and NetworkInference BiocViews, but couldn’t find any existing Bioconductor classes that would be appropriate for this package. In fact I don’t believe there are currently any packages on Bioconductor for the analysis of the type of experiments that PrInCE is designed for. The input to PrInCE is a matrix of protein quantifications across fractions, output by proteomic software such as [MaxQuant](https://maxquant.org/), and the goal is to infer a physical protein-protein interaction network. The only class I can think might be appropriate is SummarizedExperiment, but I am not aware of a proteomic analysis package that provides the genomic ranges of each protein as output to the user, so requiring a SummarizedExperiment as input would entail a significant amount of extra work for the user to wrangle their data into this format. 

The closest packages I can find to PrInCE would be [apComplex](https://www.bioconductor.org/packages/devel/bioc/html/apComplex.html), [minet](https://www.bioconductor.org/packages/devel/bioc/html/minet.html) or [GENIE3](https://www.bioconductor.org/packages/devel/bioc/html/GENIE3.html) which aim to reconstruct networks from a different kind of proteomic data or gene expression (RNA-seq/microarray) data. These all take base R matrices as input - the latter two do not have Bioconductor imports and apComplex imports Bioconductor packages for visualization or identifier mapping, rather than for Bioconductor classes. 

Is there a particular class you think that PrInCE should be supporting?

Thanks

Michael

**Comment by skinnider** [comment]
Hi Marcel @LiNk-NY, just wanted to follow up on your comment. Is there a particular class that you think that PrInCE should support in order to be contributed to Bioconductor?

**Comment by LiNk-NY** [comment]
Hi Michael, @skinnider 

It would be really good to have Laurent's @lgatto input on this matter. 
He certainly would know if `SummarizedExperiment` or other classes
(`MSnbase`) are appropriate.

IMO, supporting and/or extending classes such as `SummarizedExperiment` 
is not an extensive amount of work when setup properly.

We prioritize inter-operability by ensuring that incoming packages are using
available classes and methods from other Bioconductor packages. 

Please see: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

Best regards,
Marcel

**Comment by skinnider** [comment]
Hi Marcel @LiNk-NY,

Thanks for referring me to `MSnbase`—I wasn’t familiar with this package, but the `MSnSet` class seems to be appropriate for this type of data. I have modified the `PrInCE` functions that take numeric matrices as input to also take `MSnSet` objects as input, and return them as output where appropriate. Please let me know if this satisfies the requirement for interoperability.

Best,

Michael

**Comment by LiNk-NY** [comment]
Hi Michael, @skinnider 
Thank you for your submission to Bioconductor.
Please see the review below. 

Feel free to respond in this thread if you have any
questions. 
Best regards,
Marcel

---
# PrInCE #957

## DESCRIPTION

* Update the `BugReports` field to 'https://github.com/fosterlab/PrInCE/issues'
* Please wrap text to fit 80 column widths.
* Minor: Depends field should read R (>= 3.6.0)
* It's not entirely necessary to inclue the package version of every package.
You can leave it as is for now.

## NAMESPACE

* Looks okay. Try to keep function names short.
* Some functions could possibly be methods on a class (e.g.,
`predict_NB_ensemble`, `predict_RF_ensemble`, etc.)
* Some can be combined such as `make_feature_*` into `make_feature`.

## R/

* Use character names rather than indices to subset `data.frame`s (more robust).
These can be arguments to a function if the name is not specified.
* Check for `is.missing` rather than `is.null` when no default value is used
in `check_gaussians`.
* Vectorize or loop where possible to avoid long `if` `else` statements
(e.g., in `check_gaussians` you can use an lapply or vapply to check if any of
those fields are missing).
* Perhaps you should keep `clean_profiles` and related operations endomorphic,
meaning they accept and return `MSnSet`.
* Consider grouping functions into one file rather than having 1 file for each
function (for example, AIC related functions; data docs).
* Avoid using vague argument names such as 'input'
* Use switch to avoid a series of `if` `else` statements in
`predict_interactions`

```
interactFUN <- switch(classfier,
    NB = predict_NB_ensemble,
    RF = predict_RF_ensemble,
    ... etc.)
```

* It is possible to combine predict_*_ensemble functions into one and have an
argument for each algorithm (`c("NB", "RF", "SVM")`)


Minor:
* `if (length(best) == 0)` is equivalent to `if (!length(best))`
* Use `<-` for assignment rather than `=`
* Use `seq_along(x)` instead of `seq_len(length(x))`

## vignettes/

* Please wrap text to 80 column width
* It looks thorough in terms of describing functionality but perhaps some
additional examples would help users.

**Comment by skinnider** [comment]
Hi Marcel @LiNk-NY,

Thanks for your thorough review. I have made most of the changes you requested, but I had a few additional questions or comments on some of the points you raised. I responded to each point below. 

> ## DESCRIPTION
> * Update the `BugReports` field to 'https://github.com/fosterlab/PrInCE/issues'

Done. 

> * Please wrap text to fit 80 column widths.

Done. 

> * Minor: Depends field should read R (>= 3.6.0)

Done. 

> * It's not entirely necessary to inclue the package version of every package.
>   You can leave it as is for now.
> 
> ## NAMESPACE
> * Looks okay. Try to keep function names short.
> * Some functions could possibly be methods on a class (e.g.,
>   `predict_NB_ensemble`, `predict_RF_ensemble`, etc.)

I combined these into a single function. 

> * Some can be combined such as `make_feature_*` into `make_feature`.

These functions take very different arguments so I am not sure it makes sense to combine them.

> ## R/
> * Use character names rather than indices to subset `data.frame`s (more robust).
>   These can be arguments to a function if the name is not specified.

I am a bit confused about why this would be the case. The opposite is true in my experience. Can you elaborate a bit on this point? 

> * Check for `is.missing` rather than `is.null` when no default value is used
>   in `check_gaussians`.

I rewrote this to check for both using the non-vectorized operator (`&&`), i.e., 

```
if (!missing(gaussians) && !is.null(gaussians)) {
    ...
}
```

> * Vectorize or loop where possible to avoid long `if` `else` statements
>   (e.g., in `check_gaussians` you can use an lapply or vapply to check if any of
>   those fields are missing).

I rewrote this error message. 

> * Perhaps you should keep `clean_profiles` and related operations endomorphic,
>   meaning they accept and return `MSnSet`.

I am not totally sure what you mean by this. After the last round of edits to the source code, many functions in PrInCE can take either a matrix or a `MSnSet` as input; however, most return something else entirely (e.g. a data frame). `clean_profiles` and `filter_profiles` are the only two functions that return essentially the same object as input. I am reluctant to _require_ that the user provide a `MSnSet` as input instead of a base R matrix so `clean_profiles` and `filter_profiles` return the same object that was provided, i.e., if a matrix was provided as input they return a matrix; if a `MSnSet` was provided as input they return an `MSnSet`. 

> * Consider grouping functions into one file rather than having 1 file for each
>   function (for example, AIC related functions; data docs).

Done.

> * Avoid using vague argument names such as 'input'

I renamed all arguments named `input`. 

> * Use switch to avoid a series of `if` `else` statements in
>   `predict_interactions`
> 
> ```
> interactFUN <- switch(classfier,
>     NB = predict_NB_ensemble,
>     RF = predict_RF_ensemble,
>     ... etc.)
> ```

Done.

> * It is possible to combine predict_*_ensemble functions into one and have an
>   argument for each algorithm (`c("NB", "RF", "SVM")`)

I have consolidated the four `predict_*_ensemble` functions into a single function, `predict_ensemble`.

> Minor:
> 
> * `if (length(best) == 0)` is equivalent to `if (!length(best))`

Although the two statements are equivalent, I think the former is much easier to read. Is it an issue if I leave it as is?

> * Use `<-` for assignment rather than `=`

I have replaced all instances of `=` assignment. But, for future reference, I wanted to know if this is an official policy required for a package to be accepted to Bioconductor? It seems to me that this is a difference of opinion with no impact on performance, and there are advocates on both sides of the fence (e.g., see https://github.com/Robinlovelace/geocompr/issues/319). 

> * Use `seq_along(x)` instead of `seq_len(length(x))`

I replaced this.

> ## vignettes/
> * Please wrap text to 80 column width

Done.

> * It looks thorough in terms of describing functionality but perhaps some
>   additional examples would help users.

I would be happy to add more examples, but the difficulty in this respect is fitting everything within the `R CMD check` 5-minute window. At present on the Windows machine, the entire check is right around ~5 min, which is causing the warning above, and would not admit the addition of another example.

**Comment by LiNk-NY** [comment]
Hi Michael, @skinnider 
> > * Use character names rather than indices to subset `data.frame`s (more robust).
These can be arguments to a function if the name is not specified.

> I am a bit confused about why this would be the case. The opposite is true in my experience. Can you elaborate a bit on this point?

When you subset an input using numeric indices, there is room for error when the input changes.
If for some reason, the user decides to change what you would expect to be in the first column of the
`data.frame`, your operations would be working on the wrong column.
The more robust way to handle subsetting of input would be to use dedicated and/or default column
names so that you can always get the right column no matter the position in the `data.frame`. 

Here using column names is more robust when the input changes:
```
data(mtcars)
mtcars <- mtcars[, c(3:1)]

## _intend_ to get 'mpg' with numeric index
mtcars[, 1]

## robust way to get 'mpg'
mtcars[, "mpg"]
```

> > * Perhaps you should keep `clean_profiles` and related operations endomorphic,
> >  meaning they accept and return `MSnSet`.

> [truncated...] if a matrix was provided as input they return a matrix; if a `MSnSet` was provided as input they return an `MSnSet`.

It sounds like these could be a method for each input. The `MSnSet` method can return `MSnSet` and likewise for `matrix` inputs, improving interoperability. 

> > * Use `<-` for assignment rather than `=`

> I have replaced all instances of `=` assignment. But, for future reference, I wanted to know if this is an official policy required for a package to be accepted to Bioconductor? [truncated...]

It is not an official policy, it is just a minor point in the review. The `<-` operator is expressly for object assignment and its use improves readability. 

> > * It looks thorough in terms of describing functionality but perhaps some
> >  additional examples would help users.

> I would be happy to add more examples, but the difficulty in this respect is fitting everything within the `R CMD check` 5-minute window. At present on the Windows machine, the entire check is right around ~5 min, which is causing the warning above, and would not admit the addition of another example.

Could you use data that is smaller for demonstration purposes?

**Comment by LiNk-NY** [comment]
Hi Michael, @skinnider 
Please provide an update. 
Thank you. 
-MR

**Comment by skinnider** [comment]
Hi Marcel, @LiNk-NY -
Sorry for the inactivity. I have had a few major deadlines looming this Friday, but I will try to make the remaining changes early next week.

**Comment by LiNk-NY** [comment]
No worries. Thanks for the update.

**Comment by skinnider** [comment]
Hi Marcel - thanks again for your review and for your patience as I’ve addressed these last few points. 

I have replaced the indexing operations in the package that assume protein identifiers are in the first two columns with either an integer or character vector of column positions or names, and provided an argument for the user to optionally change these. I have also modified `clean_profiles` to take either a matrix or `MSnSet` as input, and return a matrix. 

In terms of the examples, the issue is just that protein interaction networks are very sparse—less than 1% of possible pairs are interacting. So, in order to give the classifier enough points to train on and produce a realistic precision curve, one has to provide something relatively close to a complete dataset. This is the origin of the problems I’m running into with respect to the 5-minute compilation time warning. I suppose it would be possible to simulate some data but I would strongly prefer to provide real data in a worked example. However, to extend the vignette, I have added a demo of the `detect_complexes` function. I hope that provides a bit more information to users.

I think that should be it, but let me know if any further changes are required. 

Mike

**Comment by LiNk-NY** [comment]
Hi Mike, @skinnider 

Thanks for making those changes. 
In this instance you can create an artificially enhanced interaction network where
more than 1% of possible pairs are interacting and make the data smaller
so that it doesn't take a long time on the build machines. 

The examples provided do not have to present real-world scenarios. If you so
wish to do so, we have workflow packages for that. 

Best regards,
Marcel

**Comment by skinnider** [comment]
Hi Marcel @LiNk-NY - it is not immediately obvious to me how to simulate the underlying proteomics data such that some large percentage of possible pairs would be interacting, and I also think this would most likely be more confusing to potential users than providing a single worked example. Although I appreciate your points that the examples do not strictly have to provide real-world scenarios, it seems to me that this is what is likely to be most useful to potential users in a field without a culture or norms surrounding simulation studies (i.e. I am not aware of a paper that benchmarks a method on simulated co-elution data). 

If you want, I can provide a second example that does not get run in the vignette - this would have to be concise though to avoid the BiocCheck warning when more than 50% of chunks are `eval=FALSE`. 

Mike

**Comment by LiNk-NY** [comment]
Hi Mike, @skinnider 

I would image that removing a large number of pairs that don't interact
is the easiest approach. The inputs will still be the same, only the
runtime will be shortened. 

Keep in mind that the examples are meant to elucidate the use of your
functions rather than the contents / structure of the data. A user shouldn't
expect to get biologically meaningful results from the function examples
but rather be guided as to how to run the group of functions for analysis
 / discovery in your package.

As I mentioned earlier, real-world examples are best reserved for Bioconductor
workflow packages.  

Regards,
Marcel

**Comment by skinnider** [comment]
Hi Marcel @LiNK-NY - I have added a second dataset to the package, and added it as a new section to the vignette.
Mike

**Comment by LiNk-NY** [comment]
Hi Mike, @skinnider 
Sorry for the delay. I will review the changes you've made today. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
It's looking good. I will accept your package. 
Also, resolve the warnings about `insertRef`: 
```
R/PrInCE.R:163:#' \insertRef{stacey2017}{PrInCE}
R/PrInCE.R:165:#' \insertRef{scott2015}{PrInCE}
R/PrInCE.R:167:#' \insertRef{kristensen2012}{PrInCE}
R/PrInCE.R:169:#' \insertRef{skinnider2018}{PrInCE}
```

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/skinnider.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PrInCE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PrInCE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
