### ISSUE TITLE
Submission of "topconfects" package to Bioconductor

### ISSUE THREAD

**Issue by pfh** [Bioconductor/Contributions#959]
Hello Bioconductor developers,

I would like to submit my "topconfects" R package to Bioconductor. It implements a method described in this preprint on BioRXiv: https://www.biorxiv.org/content/early/2018/06/11/343145

One difficulty I've run into is that I was unable to install the development version of R 3.6 from http://r.research.att.com/, the web page says something about "make check FAILED", and therefore I couldn't install the bioconductor devel version. However I don't think this package depends on anything likely to be updated in the latest version.

- Repository: https://github.com/pfh/topconfects

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by pfh** [comment]
R devel nightly build for Mac OS seems to have recovered, and I've now managed to install R 3.6 and Bioconductor devel.

I have attempted to fix the problems found by build-bot:
* Changed version to 0.99.1
* Changed email address to the one I susbscribed to bioc-devel with
* Changed R dependency to >= 3.6.0
* Removed file check.Renviron

The github repository has the webhook installed and it seems to have triggered. I got the response "version bump required". Should the build-bot have tried to build the package again, or have I missed a trick?

**Comment by lshep** [comment]
It may be the downward switch in version number -  for now I'll kick off a manual build, hopefully that will get things back on track.

**Comment by dvantwisk** [comment]
Things seem to be building okay now, but can you perform a version bump?

**Comment by pfh** [comment]
Ok, the build manager seemed to like that version bump. Anything else I can do for you, or should I sit tight?

**Comment by dvantwisk** [comment]
Everything looks fine. I will have a review to you soon.

**Comment by dvantwisk** [comment]
Here's the review for your package. I think it looks very good, most of my issues just revolve around properly importing symbols. [REQUIRED] tags must be implemented or addressed. [CONSIDER] tags are advisable but not required. Please message me back when you are finished making changes.

R/deseq2.R
- [REQUIRED] L64: Import `Deseq2` symbols used here.

R/edger.R
- [CONSIDER] L61: Use `match.arg()`. For example in the function `edger_confects`,
the parameter `null` can be delcared as `null= c("worst.case", "interval")`
within the function declaration. The user's selected value can then be obtained
using `null <- match.arg(null)` within the function. The default value
is the first element in the vector (in this case `worst.case`). This way of doing
things is preffered because `match.arg()` will throw an error if the user gives
on unacceptable argument as input. It also allows the user to see possible
inputs by simply typing the function name `edger_confects`. This can be used in
other functions in this package.
- [REQUIRED] L67-68: Import `edgeR` symbols used here.

R/limma.R
- [REQUIRED] Import `limma` symbols used here.

tests
- [CONSIDER] testthat/test_edger.R: This file doesn't seem to contain any
`expect_` tests.

**Comment by dvantwisk** [comment]
Is there a reason to avoid installing these packages?

**Comment by dvantwisk** [comment]
Your suggestion about using `requireNamespace()` seems to be a good solution for this.

**Comment by pfh** [comment]
Ok, as requested I have:

* Added checks with `requireNamespace` to give an informative error message before using `::`.
* Used `match.args` in `edger_confects`.
* Added an actual test to `test/testthat/test_edger.R` (and a similar test to `test_limma_identical.R`).

I also tweaked the vignette to reduce the build time slightly.

I'm not sure what has happened in the latest Linux build. I don't think it was anything I did -- something about a missing shared library for BiocCheck.

**Comment by dvantwisk** [comment]
Yeah, it looks like the machine is missing a shared object library so this is not your issue. We'll look into it. Aside from that, the changes you made look good so I will likely move to accept the package soon.

**Comment by dvantwisk** [comment]
This seems to just be an unrelated intermittent issue that we our still addressing in our build system, but is unrelated to your package. I'm going to move to accept the package now.

**Comment by pfh** [comment]
This is great news, thank you. I definitely feel my package writing skills have been improved by this process.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pfh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("topconfects")`. The package 'landing page' will be created at

https://bioconductor.org/packages/topconfects

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
