### ISSUE TITLE
atSNP package submission

### ISSUE THREAD

**Issue by sunyoungshin** [Bioconductor/Contributions#960]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sunyoungshin/atSNP

Confirm the following by editing each check box to '[x]'

- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sunyoungshin** [comment]
Hello @hpages,

Thank you for reviewing my submission. I have fixed all but 1 warning:
                        R CMD check exceeded 5 min requirement
Can you please give me an idea on the fix? R CMD check is especially slower on Windows, taking ~10 minutes.

Sunyoung

**Comment by mtmorgan** [comment]
Thank you for your contribution.

- address overall compute time by reducing the example size or vignette extent, or by identifying and addressing inefficient R code.

DESCRIPTION

- DESCRIPTION: Provide only Authors@R field. Author: and Maintainer: are generated automatically. Provide email address without `[]`.

- remove unnecessary files, e.g., Read-and-delete-me

vignettes

- remove atsnp-vignette.R and atsnp-vignette.html, these are generated when the package is built.

- The markdown `r Biocpkg()` generates a hyperlink to Bioconductor package landing pages, and should not be used for CRAN packages (e.g., data.table, Rcpp; use `CRANpkg()` instead.

- do not specify `version = 3.8` in `BiocManager::install()` as the version depends on the user's installation.

- Use [BiocFileCache][1] to manage downloads; this will make your package more robust to internet availability and will decrease time required to build the vignette

R

- graphic.R:48 consider simple helper functions to reduce code duplication, e.g., replacing 

    ```
    if (all(any(!is(snpids, "character"),  length(snpids)==0), is.null(snpids)==FALSE)
    ```

  with a function performing the same operations and returning TRUE or FALSE; use it in the next line.

- data.table has very unusual semantics and we strongly discourage its use outside of the package namespace. Consider revising your functions to accept and return 'data.frame' objects that are coerced, if necessary, to data.table inside the function.

- motif_analysis.R:233 and throughout. Examine each 'iteration' (for, sapply, lapply, apply, ...; invoking an R function n times) for opportunities to vectorize invoing an R function once. For instance

    ```
    keep.id <- which(apply(sequences, 2, function(x) sum(is.na(x))) == 0)
    ```

  is more more efficiently

    ```
   colSums(is.na(sequences)) == 0
   ```

 later,

   ```
   prior <- apply(transition, 1, sum)
   ```
    
  is simply `rowSums(transition)`. there are many such examples.
  
- it does not make sense to start error messages with "Error:"

    ```
    > stop("Error: oops")
    Error: Error: oops
    ```
    
- use `seq_along(results)` instead of `seq(length(results))` and similar.

man

- format output so that lines fit within 80-character width screens; some help pages are not readable (e.g., ComputeMotifScore.Rd) at the moment

tests

- revisit your unit tests. Many are too complicated for this purpose. It does not make sense to include calculations whose output is not tested, e.g., plotting figures. Tests should all include `expect_*()` statements resulting from simple and fast computations -- test the components that your software puts together, rather than the integrated whole.

**Comment by sunyoungshin** [comment]
@mtmorgan Morgan,

Thank you very much for your careful review. I am currently working on all points that you have raised in the report. I have questions about BiocFileCache and data.table.

1. Can you please give me an example on the use of BiocFileCache? Although I have looked through its vignette and etc, the appropriate use of BioFileCache for my package is not clear.

2. Do you encourage to convert all 'data.table' objects to 'data.frame' objects? My namespace contains import(data.table), so I thought 'data.table' can be used under my package without any restriction.

**Comment by mtmorgan** [comment]
With respect to data.table, please feel free to use it internally in your package as you see fit. But please also ensure that the use of data.table is NOT required as inputs to your function, and NOT returned by your functions.

For BiocFileCache, whenever you retrieve an internet resource, use BiocFileCache to cache it locally. For instance in `LoadMotifLibrary()` (I am just scanning your code; perhaps I am parsing it incorrectly) use

```
url = "http://pages.stat.wisc.edu/~keles/atSNP-Data/motifs.txt"
rid <-  bfcrid(bfcquery(query=url, exact=TRUE, field="rname"))
if (!length(rid))
    rid <- names(bfcadd(rpath = url))
readLines(bfcrpath(rids=rid))
```

**Comment by sunyoungshin** [comment]
> Received a valid push; starting a build. Commits are:
> 
> [efb12fb](https://github.com/sunyoungshin/atSNP/commit/efb12fb4b50115fc3ea6a23d5104d2c8015270a1) separated three separate internal functions: motif...
> [c4de8cd](https://github.com/sunyoungshin/atSNP/commit/c4de8cdad39d1bd9011a63ce1a0d29b9097fde7e) Merge pull request #35 from sunyoungshin/devtools-...

**Comment by sunyoungshin** [comment]
> Received a valid push; starting a build. Commits are:
> 
> [efb12fb](https://github.com/sunyoungshin/atSNP/commit/efb12fb4b50115fc3ea6a23d5104d2c8015270a1) separated three separate internal functions: motif...
> [c4de8cd](https://github.com/sunyoungshin/atSNP/commit/c4de8cdad39d1bd9011a63ce1a0d29b9097fde7e) Merge pull request #35 from sunyoungshin/devtools-...

**Comment by sunyoungshin** [comment]
> Received a valid push; starting a build. Commits are:
> 
> [f7ad76f](https://github.com/sunyoungshin/atSNP/commit/f7ad76f9ea6337ed028a6df5bd822ef0f7cae5de) Moved three internal files from motif_analysis to ...
> [8d92b3b](https://github.com/sunyoungshin/atSNP/commit/8d92b3bfd6e6f739a095582f7fde8ba6654b5c31) vignettes update
> [c423736](https://github.com/sunyoungshin/atSNP/commit/c42373631d9f7f2b544118cf625bab6c30555f8a) Merge pull request #37 from sunyoungshin/devtools-...

**Comment by sunyoungshin** [comment]
Reopen on Feb 16, 2019

**Comment by sunyoungshin** [comment]
> > Received a valid push; starting a build. Commits are:
> > [f7ad76f](https://github.com/sunyoungshin/atSNP/commit/f7ad76f9ea6337ed028a6df5bd822ef0f7cae5de) Moved three internal files from motif_analysis to ...
> > [8d92b3b](https://github.com/sunyoungshin/atSNP/commit/8d92b3bfd6e6f739a095582f7fde8ba6654b5c31) vignettes update
> > [c423736](https://github.com/sunyoungshin/atSNP/commit/c42373631d9f7f2b544118cf625bab6c30555f8a) Merge pull request #37 from sunyoungshin/devtools-...



> > Received a valid push; starting a build. Commits are:
> > [efb12fb](https://github.com/sunyoungshin/atSNP/commit/efb12fb4b50115fc3ea6a23d5104d2c8015270a1) separated three separate internal functions: motif...
> > [c4de8cd](https://github.com/sunyoungshin/atSNP/commit/c4de8cdad39d1bd9011a63ce1a0d29b9097fde7e) Merge pull request #35 from sunyoungshin/devtools-...

**Comment by sunyoungshin** [comment]
> > > Received a valid push; starting a build. Commits are:
> > > [f7ad76f](https://github.com/sunyoungshin/atSNP/commit/f7ad76f9ea6337ed028a6df5bd822ef0f7cae5de) Moved three internal files from motif_analysis to ...
> > > [8d92b3b](https://github.com/sunyoungshin/atSNP/commit/8d92b3bfd6e6f739a095582f7fde8ba6654b5c31) vignettes update
> > > [c423736](https://github.com/sunyoungshin/atSNP/commit/c42373631d9f7f2b544118cf625bab6c30555f8a) Merge pull request #37 from sunyoungshin/devtools-...
> 
> > > Received a valid push; starting a build. Commits are:
> > > [efb12fb](https://github.com/sunyoungshin/atSNP/commit/efb12fb4b50115fc3ea6a23d5104d2c8015270a1) separated three separate internal functions: motif...
> > > [c4de8cd](https://github.com/sunyoungshin/atSNP/commit/c4de8cdad39d1bd9011a63ce1a0d29b9097fde7e) Merge pull request #35 from sunyoungshin/devtools-...

**Comment by sunyoungshin** [comment]
@mtmorgan Martin,

Thank you for your comments on data.table and BiocFileCache. atSNP package now uses the both in a proper way. 

Build reports are not generated since yesterday. Can you please let me know what I can do to fix the issue?

**Comment by sunyoungshin** [comment]
@mtmorgan Hello Martin,

I addressed all issues you pointed out but one warning: "WARNING: check time exceeded 5 min". On my Macbook pro, the check time is just 3m 18.4s and it took 23.5s for checking whether package ‘atSNP’ can be installed. I am not sure about the discrepancy in check time between the local run and the server run. Should I make further changes in my R codes?

On top of that, there are three issues I would like to let you know. First, I observed that malbec2 (LInux server) does an incorrect job from time to time. atSNP does not come with Rsamtools, but the build report showed an error message about Rsamtools. You can find this in http://bioconductor.org/spb_reports/atSNP_buildreport_20190223184257.html. Also, the performance of tokay2 (Windows server) does not seem stable. I did submit two atSNP versions which have only a few minor differences, but  tokay2 used significantly different amount of time on R CMD check. One of the runs issued a Timeout label. You can find them at atSNP_buildreport_20190223184257.html and atSNP_buildreport_20190223200828.html.
Last, my last push does not still return a build report. Does this happen from time to time? I have experienced this several times since mid February.

I look forward to hearing from you.

**Comment by mtmorgan** [comment]
Although atSNP does not use Rsamtools directly, it depends on imports packages that use it; I'm not sure why the build system sometimes has difficulty finding the .so file. All servers build multiple packages, and windows builds / checks under two architectures, so there are explanations for differences in build times. I will accept the package in its current condition but encourage you to develop a vignette or examples that make more modest use of time.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sunyoungshin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("atSNP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/atSNP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
