### ISSUE TITLE
(inactive) rMVP

### ISSUE THREAD

**Issue by hyacz** [Bioconductor/Contributions#965]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/XiaoleiLiuBio/rMVP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
It looks like the vignette code chunks are static, not evaluated as required by the Bioconductor package guidelines. Also there are no Bioconductor packages in the Depends: or Imports: field; if your package inputs or returns standard data formats, e.g., VCF, genomic coordinates, experimental summaries, then your package should include as part of its interface [standard Bioconductor packages][1].

Please update your vignette to include fully evaluated code chunks and to respond to the concern about interoperability with standard Bioconductor data representations. Your package will then be added to the review queue.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by hyacz** [comment]
Thank you for pointing out these issues, I will update the vignette code to follow the guidelines, rMVP uses bigmemory::big.matrix() as the data structure for the genotype matrix for computational efficiency, so we used Rcpp to write the data reading code. I didn't know much about standard Bioconductor packages before, rMVP used VCF and genomic coordinates. If standard Bioconductor packages are helpful, we would be happy to use more robust standard Bioconductor packages in subsequent versions.
This is my first time to submit the R package, thank you again for your advice and understanding. :smiley:

**Comment by mtmorgan** [comment]
I think the important part is that the user-facing part of the interface is as compatible as possible with Bioconductor objects; internally, I think it is OK that you use Rcpp to read data directly into your internal representation. I don't really know enough about what the inputs and outputs of your functions are to provide more detailed advice.

**Comment by mtmorgan** [comment]
Please update your package to address the errors in the automatic build report. After addressing the errors, be sure to include a 'version bump' to 0.99.1 (then 0.99.2, 0.99.3, etc) to trigger an automatic build and check.

**Comment by hyacz** [comment]
> WARNING: Update R version dependency from 3.5 to 3.6.

I noticed a warning that the package must depend on the R 3.6. Can I keep the 3.5 dependency? This is important because the latest version of Microsoft R Open is 3.5.1 and we have made some special optimizations.

**Comment by mtmorgan** [comment]
See the recent discussion in the mailing list thread at https://stat.ethz.ch/pipermail/bioc-devel/2019-January/014552.html . At the end of the day it is ok to ignore the warning.

**Comment by hyacz** [comment]
:smiley:Thanks for the information you provided! I will try to create a separate branch for the earlier Bioconductor to be compatible with R 3.5, which seems like a good idea.
I have already run BioCheck on my computer without Error and Warning, but some errors only appear on the autobuild system, I will check and fix them.

**Comment by hyacz** [comment]
```
> MVP.Data.Hapmap2MVP(hapmapPath)
Warning in file.remove(backingfile) :
  cannot remove file 'mvp.geno.bin', reason 'Permission denied'
Reading file...
inds: 281	markers:3092
Error in filebacked.big.matrix(nrow = m, ncol = n, type = type.geno, backingfile = backingfile,  : 
  Backing file already exists! Either remove or specify
           different backing file
Calls: MVP.Data.Hapmap2MVP -> filebacked.big.matrix
Execution halted
```
This file looks like it was generated in the previous round of builds. Why don't I have permission to delete it? Should I clean up my generated files during each automatic build? Or set a temporary directory as a working directory? Or use a random file name? I need some advice.

**Comment by mtmorgan** [comment]
Although all three builds fail, this error only occurs on Windows. I would guess that this is because Windows is more careful about file removal, and from the operating system perspective the file is 'in use' by this or another process, e.g., because the file was used in another example but not properly cleaned up (e.g., closed) in that example.

In general the default behavior should be for example code to write to temporary files or directories e.g., `fl <- tempfile()` or `dir.create(dir <- tempfile())`.

**Comment by hyacz** [comment]
Sorry for the frequent upgrades that triggered automatic builds. I tried to build a clean R 3.6 environment and perform automated tests, but I can't reproduce the errors on Bioconductor automatic build system.

But I think it should be OK now. 😃

**Comment by hyacz** [comment]
We want to keep `devtools::install_github("xiaoleiLiubio/rMVP")` available, so we need R >= 3.4 instead of 3.6, there will be a warning.

**Comment by mtmorgan** [comment]
Can you please update your package to remove the remaining warnings, so that a review can be performed?

**Comment by mtmorgan** [comment]
Is your package now ready for review?

**Comment by hyacz** [comment]
Yes, our package is ready for review. The current version is 0.99.14.

**Comment by hyacz** [comment]
Hi, Morgan

Is the review in progress? Is there anything I can do?

Haohao

**Comment by mtmorgan** [comment]
# 19 February, 2019

There are notes in the build report that seem like true positives, and that should be addressed:

- seem like straight-forward corrections
    ```
    * checking R code for possible problems ... [16s/16s] NOTE
    MVP.Data.Kin: warning in read.big.matrix(fileKin, head = FALSE, type =
      "double", sep = sep): partial argument match of 'head' to 'header'
    MVP.Data.Numeric2MVP: warning in read.big.matrix(num_file, head =
      FALSE, sep = sep): partial argument match of 'head' to 'header'
    MVP.Data.PC: warning in read.big.matrix(filePC, head = FALSE, type =
      "double", sep = sep): partial argument match of 'head' to 'header'
    MVP.FarmCPU: warning in FarmCPU.BIN(Y = phe[, c(1, 2)], GD = geno, GM =
      map, CV = CV, P = myPrior, method = method.bin, b = bin.size, s =
      bin.selection, theLoop = theLoop, bound = bound, ncpus = ncpus):
      partial argument match of 'GD' to 'GDP'
    MVP.FarmCPU: warning in FarmCPU.BIN(Y = phe[, c(1, 2)], GD = geno, GM =
      map, CV = theCV, P = myPrior, method = method.bin, b = bin.size, s =
      bin.selection, theLoop = theLoop, ncpus = ncpus): partial argument
      match of 'GD' to 'GDP'
    MVP.FarmCPU: warning in FarmCPU.Remove(GD = geno, GM = map, seqQTN =
      seqQTN, seqQTN.p = seqQTN.p, threshold = 0.7): partial argument match
      of 'GD' to 'GDP'
    print_info: warning in make_line(welcome, line = linechar, width =
      width): partial argument match of 'line' to 'linechar'
    ```
    
- `Undefined global functions or variables: Revo.version getMKLthreads setMKLthreads` looks like missing imports

- seems like mis-use of compiler flags

    ```
    * checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... NOTE
      src/Makevars: SHLIB_OPENMP_CXXFLAGS is included in PKG_CXXFLAGS but not in PKG_LIBS
      src/Makevars: SHLIB_OPENMP_CFLAGS is included in PKG_LIBS but linking is by C++
      src/Makevars.win: SHLIB_OPENMP_CXXFLAGS is included in PKG_CXXFLAGS but not in PKG_LIBS
      src/Makevars.win: SHLIB_OPENMP_CFLAGS is included in PKG_LIBS but linking is by C++
    Use of these macros is discussed in sect 1.2.1.1 of Writing R
    Extensions. The macros for different languages may differ so the
    matching macro must be used in PKG_CXXFLAGS (etc) and match that used
    in PKG_LIBS (except for Fortran: see the manual).
    ```
    
DESCRIPTION

- Please provide a Description: field that reads more like a paper abstract, providing the user with an informative summary of the functionality of your package and how it advances current 'state of the art'. Remember that the field can be wrapped to multiple lines, with continuation lines indented, e.g., by 4 spaces.

- It seems likely that BH, RccpPrgoess, Rcpp, parallel and perahps other packages are not 'seen' by the end user, and should be in Imports: rather than Depends:.

NAMESPACE

- BH does not have any R functions, so importing it's NAMESPACE does not make sense

vignettes

- Please arrange for more of your vignette code chunks to be actually evaluated. The problem is that these 'pictures of code' quickly break, and the user is left with the impression that the package functions as advertised when it does not.

R -- the following are specific comments, but issues should be addressed throughout the package

- MVP.Data.r:77 `message("WARNING...")` if this is a warning, then use `warning()` rather than than `message()`.

- MVP.Data.r:77 please avoid long lines that combine programming idioms, they are difficult to read and comprehend

    ```
    if ("sep.vcf" %in% names(parames))
        warning("'sep.vcf' has be DEPRECATED")
    ```
    
- MVP.Data.r:90 use `vapply()` rather than `sapply()` to avoid surprises when the length of the first argument is 0.

- MVP.Data.r:223 use `message()` rather than `cat()` to communicate informative messages to users; note that `message()` does not usually require `paste()`.

- MVP.Data.r:550 use `seq_len()` or `seq_along()` rather than `1:n` to avoid surprises when n < 1.

- MVP.Data.r:555 `stop("ERRROR: ...")` and similar seems redundant, simply `stop("...")` would seem sufficient.

- MVP.Data.r:857 setting `options(...)` without restoring values to their default is bad style. use

    ```
    opts <- options(...)
    on.exit(options(opts))
    ```
    
- MVP.EMMA.Vg.Ve.r:113 another example of using `seq_len()` rather than `1:(m - 1)`

- MVP.EMMA.Vg.Ve.r: 115 'hoist' loop invariant code like this function definition outside the `for` loop to avoid redundant computation.

- MVP.FarmCPU.r:95 another example where use of `message()` is appropriate

- MVP.FarmCPU.r:188 reconsider the need for verbose output like this.

- MVP.FarmCPU.r:300 this code is highly similar (identical?) to other code; write simple functions and reuse rather than copy / paste.

- MVP.GLM.r:93 please use consistent indentation for readability

- MVP.PCA.r:230 remove dead code.

- MVP.Utility.r:59 re-think the value of re-implementing a progress bar; this represents additional code that you must maintain, providing limited incremental value.

General

- are the files on the master branch of this repository necessary for the package? For instance, are the files in the `results` folder used?

**Comment by mtmorgan** [comment]
Please let me know when you expect to have revisions complete.

**Comment by hyacz** [comment]
The revision is still in progress and we plan to complete it by April. Detailed progress is available at https://github.com/XiaoleiLiuBio/rMVP/issues/33
