### ISSUE TITLE
CNVRanger: summarization and quantitative trait analysis of CNV ranges

### ISSUE THREAD

**Issue by lgeistlinger** [Bioconductor/Contributions#966]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/CNVRanger

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Ludwig, @lgeistlinger 
Thanks for the heads up. 
I can provide an initial review. 

Please see below. 

Best regards,
Marcel 

---

# CNVRanger #966

## DESCRIPTION

* Minor: Consider using an `Authors@R` field instead of Author and Maintainer
fields
* Add a `BugReports` field pointing to the GitHub issues page
* `BiocCheck` will say to update your R dependency to `3.6.0`

## NAMESPACE

* Looks good. You might want to rename `importLRR_BAF` to use 'camelCase' so
that it is consistent with other functions. 

## R/

* Consider providing support for MultiAssayExperiment inputs that contain
appropriate data for running `cnvExprAssoc`. 

* `.largest` can be simplified to: 

```
.largest <- function(scores, ranges, qranges) {
    ind <- IRanges::which.max(GenomicRanges::width(ranges))
    vapply(seq_along(scores), function(i) scores[[i]][ind[i]], scores[[1]]) 
}
```

* Update the `@param` entry for `all.paths`
* Check inputs to avoid errors (`plotManhattan`)
* Consider using `GRanges` structures instead of `data.frame` in `plotManhattan`
* Avoid saving PDF files for the user by default, make the `plot.pdf`
argument `FALSE`
* No need to use `gc()` explicitly
* Functions like `setupCnvGWAS` should make use of structures such as
`RaggedExperiment` rather than a collection of files.
* Use names rather than integers to subset vectors and lists
(ex. all.paths in `prodGdsCnv`Line:395)
* It is more efficient to make a call to `rappdirs:::get_os()` once than
every time you need to check the OS, therefore, assign the result to an object
and use the object for checking (`prodGdsCnv`).
* FWIW Perhaps `GDSArray` may help import GDS files (for `importLRR_BAF`)?
* Vectorize where possible and use maps for matching and replacing (e.g., in 
replace gain / loss sections of `.recodeCNVgenotype`)
* Try to avoid reading in the data from a file and accept the dataset as an
argument so that users can read as they choose. 
* Use `TRUE` and `FALSE` and not character versions of `TRUE` and `FALSE`

## vignettes/

* Looks good and thorough

**Comment by LiNk-NY** [comment]
Hi Ludwig @lgeistlinger and Vinicius,

I've had a second look at the package and it's looking good. 
Thank you for incorporating the feedback on `TCGAutils`, it's
working quite nicely. 

Thanks for submitting to Bioconductor. 
I will accept your package. 

Best,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgeistlinger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CNVRanger")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CNVRanger

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
