### ISSUE TITLE
rmelting

### ISSUE THREAD

**Issue by aravind-j** [Bioconductor/Contributions#973]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aravind-j/rmelting

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by aravind-j** [comment]
I have one remaining **ERROR**, which seems to be due to a build system issue in _merida2_ due to non availability of the dependent package `rjava`.

**Comment by mtmorgan** [comment]
Sorry for my extended delay.

vignettes

- Please remove vignette build products (Tutorial.pdf) from the git repository, these are rebuilt by `R CMD build`.

- (suggest) update installation instructions to reflect Bioconductor best practices

    ```
    if (!"BiocManager" %in% rownames(installed.packages()))
        install.packages("BiocManager")
    BiocManager::install("rmelting")
    ```
    
R

- (minor) `stop(paste(...))` is usually unnecessary (`stop()` `paste()`'s its arguments internally).

- melting.R:1016 Use `stringsAsFactors = FALSE` ?

- melting.R:1038 `paste0(eopt$ion_agent, "=", eopt$eval, collapse = ":")` ?

- melting.R:1196 error / warning handling seems somewhat _ad hoc_, would it make sense to use `futile.logger`, e.g.,
    ```
    tryCatch({
        stop("oops", call.=FALSE)
    }, error = flog.error)
    ```
- usually, `tryCatch()` is not appropropriate for warnings, because one wishes to continue after a warning; compare
    ```
    tryCatch({ warning("oops"); 1 }, warning = flog.warn)
    ```
  with
    ```
    withCallingHandlers({
        warning("oops", call.=FALSE)
        1
    }, warning = function(w) {
        flog.warn(conditionMessage(w))
        invokeRestart("muffleWarning")
    })
    ```
    
- meltingBatch.R:81 highly nested functions are dificult to parse; consider a more straght-forward iterative representation
    ```
    melted <- mapply(melting, sequence = sequence,
        comp.sequence = comp.sequence,
        MoreArgs = ..., SIMPLIFY = FALSE)
    unlisted <- lapply(melted, function(x) unlist(x[subs]))
    out <- t(data.frame(unlisted))
    ```

**Comment by aravind-j** [comment]
@mtmorgan Thank you for the comments. I have made the required changes as suggested. Here are the comment wise changes made and clarifications.

> Please remove vignette build products (Tutorial.pdf) from the git repository, these are rebuilt by `R CMD build`.

Removed vignette build products from git repository.

> (suggest) update installation instructions to reflect Bioconductor best practices.

Updated installation instructions as suggested.

> (minor) `stop(paste(...))` is usually unnecessary (`stop()` `paste()`'s its arguments internally).

Fixed all instances of `stop(paste(...))`.

> melting.R:1016 Use `stringsAsFactors = FALSE` ?

Added `stringsAsFactors = FALSE` to the `eopts` data frame.

> melting.R:1038 `paste0(eopt$ion_agent, "=", eopt$eval, collapse = ":")` ?
This is to create the input to be passed on to the java melting program, which requires the following syntax.

`ion1_name=x.xxe-xx:ion2_name=x.xxe-xx:agent1_name=x.xxe-xx....`

> meltingBatch.R:81 highly nested functions are dificult to parse; consider a more straght-forward iterative representation.

Expanded the specified nested function as suggested to multiple steps.

> melting.R:1196 error / warning handling seems somewhat _ad hoc_, would it make sense to use `futile.logger`, e.g.,

&

> usually, `tryCatch()` is not appropropriate for warnings, because one wishes to continue after a warning; compare

Implemented a custom internal function withWE for better error and warning handling. It is used to capture the errors and/or warning(s) from only the java program in the output returned. All non java errors and warnings will show normal behaviour.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aravind-j.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rmelting")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rmelting

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
