### ISSUE TITLE
(inactive) mfBiclust

### ISSUE THREAD

**Issue by jonalim** [Bioconductor/Contributions#976]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jonalim/mfBiclust

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jonalim** [comment]
@LiNk-NY Hello, I was wondering if you could help me advance the review process. I'm currently trying to resolve the Rd warnings, but I think the other warnings are unavoidable. Set.seed() used in our internal duplicable() function enables users to make results repeatable, and the duplicable() is always followed by appropriate code to ensure the global environment is not modified.

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonalim 
After a brief look at the package, it looks like there are a few issues:

1) Please extend `SummarizedExperiment` instead of `Biobase::eSet`. The `eSet` class
was superseded by the `SummarizedExperiment` class.
2) Your GitHub repository is huge. It seems like you have a large `.git` history file in the repo.
Use BF Repo Cleaner to reduce the size. 
3) Functions shouldn't work with the random seed or try to set it. This should be left up
to the user. I would also avoid 'restoring' of the old seed.
4) The second warning shown above means that you used those arguments in the 
documentation of `BiclusterExperiment-class` but did not describe them. You may have
described them in other documentation pages. 

Best, 
Marcel

**Comment by jonalim** [comment]
Hi Marcel, @LiNk-NY 
Thank you for your evaluation. I will work on resolving those issues.

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonalim
Thanks for making changes. 
Can you provide an update? 
Best,
MR

**Comment by jonalim** [comment]
Hi Marcel, @LiNk-NY 

Thank you for checking in. I resolved the warnings about set.seed and undocumented arguments. 

I also ran BFG repo-cleaner. In [https://github.com/settings/repositories](https://github.com/settings/repositories), I see the size as 38.4 MB. If that is still unworkable, I can ask GitHub support to remove past pull requests, which may retain references large blobs.

I am working today to change the BiclusterExperiment to a subclass of SummarizedExperiment.

Best,
Jonathan

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonalim 
It sounds like you're making good progress.
Thanks for providing the update. 

The repo size is looking good as well. Just remember to tell your colleagues to _re-clone_ the repository rather than update their existing repositories so that the repository size does not grow again. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonalim 
Thank you for your submission. 

Please see your review below. 

Respond here if you have any questions. 

Best regards,
Marcel 

---

# mfBiclust #976

* Overall, the package is in good shape. I would strongly consider separating
the two main objectives in the package and make them separate packages.
Create a shiny package that depends on the analysis package. It's easier to
maintain this way and the available functionality is split into two.

## DESCRIPTION

* Expand a bit on the meaning of 'pipelines'. Do you just mean methods? It
would be good to know from the `Description` field.
* It appears that you are submitting analysis tools and a shiny package.
Consider separating the two. 

## NAMESPACE

* Use either 'snake_case' or 'camelCase' consistently.
* Class names should start with capital letters.

## vignette

* Please stick to the 80 column width recommendations. It not only makes it
easier to review but also easier to maintain.
* Be sure to include a `sessionInfo` section at the very end.

## R

* Your `setGeneric` should wrap `standardGeneric` with the name of the generic
function. Consider creating a regular function instead since there is only one
method registered for it.
* `auto_bcv` doesn't have to be a generic, it can just work on matrix and
`BiclusterExperiment` objects. Also, it's best not to create methods for
classes that you don't own such as 'matrix'
* Create helper functions out of checks and re-use them in functions like
`auto_bcv` and `bcv`
* `validObject` is run whenever you create an instance of
`BiclusterExperiment` using `new` so you don't need to run it explicitly
(in `setAs`)
* You shouldn't need a generic `BiclusterExperiment` function to create your
class. Please use a regular function as a constructor function and check for
matrix input.
* _Do not_ create methods for external classes in your package ('matrix')
* You don't need to use `setMethod` to create an `as.matrix` function. You
can create a regular S3 method. I suggest having an extractor function
comparable to `assay` in `SummarizedExperiment` to obtain matrix data.
* Avoid using indices to obtain data. Use more robust names for example,
`results[["table"]]` instead of `results[[1L]]`.
* Avoid creating generics for single methods `getStrat`. If possible re-use
already established generics. It may be easier to just use `strategies` to
obtain the data and remove `getStart`. It seems like a confusing interface.
* Use `BiocGenerics:::replaceSlots` in the `setReplaceMethod` function.
* Use `cat` only for show methods, otherwise use `message`

Minor: 
* Create a single `args` object from inputs `list(...)` and use that to 
carry out the rest of the operations.
* Use descriptive argument names where possible
* Use `identical` to test scalar rather than vector conditions, i.e.,
`if (identical(length(clusterHeight), 1L))`

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonalim 
Please provide an update about the status of your packages.
Much appreciated. 

- Marcel

**Comment by jonalim** [comment]
Hi Marcel, @LiNk-NY 

Thank you for your guidance. I would like to work towards implementing your points (many of them would break the interface, so of course I'd like to implement them now rather than later). I don't have as much time for this project as I've had previously though. Will this issue stay open so I can ask any questions that arise?

Thanks,
Jonathan

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonalim 

It sounds like the review process timeline will be extended significantly.
I suggest we close the issue and you re-open it once the package is more ready.

Best regards,
Marcel

**Comment by jonalim** [comment]
Hi Marcel, @LiNk-NY ,

Okay, I can provide revisions in a couple weeks. 

I would like to keep the tools and Shiny app in a single package if possible. Since the analysis involves large matrices, I think users will appreciate having a visual interface in the same package, and I myself have found such packages easy to use.

Thanks,
Jonathan

**Comment by lshep** [comment]
Making the issue inactive - but feel free to comment with questions along the way and comment here when you wish it reopened for review.
