### ISSUE TITLE
Rhisat2

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/Contributions#977]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fmicompbio/Rhisat2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by csoneson** [comment]
Tagging @mbstadler as well

**Comment by csoneson** [comment]
Hi @Liubuntu,
I just wanted to give a couple of additional notes on this package. The main motivation for developing it is to provide HISAT2 as an alternative to bowtie/SpliceMap for spliced alignment in [QuasR](https://bioconductor.org/packages/QuasR/). Thus, we have followed the same implementation approach as for the [Rbowtie](https://bioconductor.org/packages/Rbowtie/) package, which provides the bowtie/SpliceMap interface to QuasR. 
The remaining Warnings and Errors are due to the package (as well as a few of the HISAT2 executables) exceeding the size limits, and the CHECK taking too long on malbec2 and merida2 (but not on tokay2). I'm not sure what we can do to decrease the size, since it's driven by the generated HISAT2 files. If you have any ideas or spot something clearly suboptimal please let us know, it would be super helpful.
Thanks!

**Comment by Liubuntu** [comment]
Hi @csoneson , 

Since these file (that are generated from building): 'inst/hisat2-build.exe" and "inst/hisat2.exe" have exceeds 5 MB in size and there is no way to reduce the "src/" folder. So we can ignore the size warning/error. The warnings about the src/ files could also be ignored because there is nothing we can do to modify them. 

About the warnings for long checking time on linux and mac machine, I would suggest to check your example data to see if we can use a moderate size data for all examples / tests. 

But anyway, I'll go ahead with the review process. 
 
Best,
Qian

**Comment by csoneson** [comment]
Thanks Qian,
I'll see what I can do for the example data - the fastq files contain only four reads each. Locally, the tests run in ~4s, and the main part of the CHECK seems to be the step checking whether the package can be installed.
Cheers,
Charlotte

**Comment by Liubuntu** [comment]
Hi Charlotte @csoneson , 

It was really joyful reviewing your package. Very well-written and organized, with clear vignette and solid tests. Only some minor things to address, and it will be ready to go. 

## DESCRIPTION

- Add a `Depends` field to have `R (>= 3.6.0)` included. 
- Add a `URL` field to directs users to source code repositories, additional help resources, etc;

## vignette

- After the Introduction, please add a section of `Installation` to show to users how to install the package as if it has been included in Bioconductor. Because new packages is going to be in Bioc devel (Bioc 3.9), they are required to use `BiocManager` instead of `BiocInstaller` for downloading the package. You should include contents like the following:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
        BiocManager::install("pkgName")
        
Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)
        
2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```
        
- The `References` section is empty now, maybe you want to add something here or remove the whole part? 

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi Charlotte, 

I have tried `devtools::build_vignette()` and still get nothing in the `Reference` section. Would you like to look again? I'll also try to debug to see if there is anything wrong on my end. All the other updates look good!

Best,
Qian

**Comment by mtmorgan** [comment]
I suggest following standard R practices, rather than devtools
```
R CMD build <repo>
R CMD INSTALL <repo>.x.y.z.tar.gz
```
I haven't been following this conversation so am maybe missing something.

**Comment by csoneson** [comment]
Just to say that also after (RStudio-independent) `R CMD build`/`R CMD INSTALL`, I get a non-empty Reference section in the vignette. 
<img width="538" alt="screen shot 2019-02-01 at 20 55 19" src="https://user-images.githubusercontent.com/5628952/52146568-62578a00-2664-11e9-9d28-0698e927454a.png">
Could it be a `pandoc-citeproc` issue?

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/csoneson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rhisat2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rhisat2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
