### ISSUE TITLE
sitePath

### ISSUE THREAD

**Issue by Takkoona** [Bioconductor/Contributions#979]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wuaipinglab/sitePath

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment]
Hi @Takkoona 

Thanks for your submission and sorry for the delay in getting back to you.

sitePath is in good shape. Before we accept it though, some minor issues need to be addressed. See below for the details.

Let me know if you have any questions.

Regards,
H.

### Vignette

1. Any reason you use `ape::` when calling `ape::root()` but not when calling `read.tree()`?

2. The vignette says that "Tree must be rooted before further analysis" but the tree seems to be already rooted. Furthermore calling `ape::root()` on it seems to have the opposite effect i.e. it turns it into an unrooted tree:
    ```
    zikv_tree <- system.file("ZIKV.newick", package = "sitePath")
    tree <- read.tree(zikv_tree)
    is.rooted(tree)  # TRUE
    tree <- ape::root(tree, "ANK57896")
    is.rooted(tree)  # FALSE
    ```

3. This is quite vague:

    _Occasionally you may get S4 phylo4 class from ggtree or other packages, use the @ symbol to get the S3 phylo object from it_

    Providing a real example would be more useful. Also it is highly recommended to use an accessor function instead of direct slot access with `@`.

4. It says: "The names in tree and aligment must be matched". Is there an easy way to check that?

### Datasets

5. The Usage sections of the various datasets suggest that the data set can be accessed directly without the need to load them first with `data()`. However that doesn't seem to be the case:
    ```
    > zikv_tree
    Error: object 'zikv_tree' not found
    > data(zikv_tree)
    > zikv_tree

    Phylogenetic tree with 362 tips and 360 internal nodes.

    Tip labels:
	APO39243, APO39229, ARU07183, AQZ41956, ATG29276, ANG09399, ...

    Unrooted; includes branch lengths.
    ```
    Therefore the Usage section for `zikv_tree` should contain `data(zikv_tree)`. The same applies for all the other datasets.

6. It could lead to some confusion that the vignette defines a variable with the same name as the `zikv_tree` dataset, especially since the former is a character string and the later a `'phylo'` object.

### Package source tree

7. Data files like `ZIKV.newick` and `ZIKV.fasta` should be placed in `inst/extdata/` instead of `inst/`.

8. What's the purpose of the `docs/` folder? This doesn't seem needed and should probably be removed.

9. What is the `inst/beast_mcc.tree` file? Is it needed?

10. The `sitePathTutorial.html` and `sitePathTutorial.R` files don't belong to the `vignettes/` folder and should be removed.

**Comment by Takkoona** [comment]
Hi @hpages ,

So I made some changes accordingly and hope to solve the issues.

[Here](https://github.com/wuaipinglab/sitePath/pull/2) list the reasons for the changes.

Regards,
Takkoona

**Comment by Takkoona** [comment]
Hi,

I'm adding some major functionalities to the package. May take a while to finish. Please don't close the submission.

**Comment by lshep** [comment]
If it is going to take awhile to finish,  we can mark the package as inactive.  When you are ready with the changes and to continue forth we the review process, simply comment on this issue to reopen it.

**Comment by Takkoona** [comment]
Ready to roll.

**Comment by Takkoona** [comment]
Hi,

I've finished adding the new features. Please reopen the issue and resume the review process. And I know this one should be asked through the mailing list but when is my package gonna come out if it's accepted.

Regards

**Comment by lshep** [comment]
Please perform a version bump to trigger a new build for your reviewer.  Your package will be added to the devel branch of bioconductor immediately.   If you can pass and get the package accepted before April 24th it will be released with the April 30 Spring release,  else it will remain in devel until the Sept/Oct release.

**Comment by Takkoona** [comment]
Hi @hpages 
 
I managed to pass the checks. Ready for any feedbacks now.

Regards

**Comment by Takkoona** [comment]
Notice me! @hpages senpai!

Waiting for the feedback. I really want my package to be accepted before the April release.

**Comment by hpages** [comment]
Hi @Takkoona ,

Thanks for all the changes you made to sitePath. Package looks good and meets our guidelines.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Takkoona.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sitePath")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sitePath

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
