### ISSUE TITLE
Rcwl

### ISSUE THREAD

**Issue by hubentu** [Bioconductor/Contributions#980]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hubentu/Rcwl

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@hpages @lshep This package requires the python module(s) `cwltool`.

**Comment by lshep** [comment]
So as a general comment -   We feel like you shouldn't be changing or writing to a users system in the vignette or examples/tests.  You should include instructions of what the user needs to do to set up to use the package and run the code assuming that this set up has been done (ie.  there should be no system install or upgrades for the user )

**Comment by hubentu** [comment]
Hi @lshep ,
I have removed the scripts to install the cwltool and give an installation URL instead. Thanks!

**Comment by lshep** [comment]
Thank you. Please see initial review below.  

<br>
<br>
<br>

# General
- [ ] Please continue trying to fix all WARNING/NOTES in the build report

# Readme
- [ ] include Bioconductor installation instructions

# vignette

- [ ] (optional) I recommend the vignette be Rcwl.Rmd rather than user guide as it is more intuitive for an R users to do vignette("Rcwl") rather than vignette("user_guide") to open the vignette. 

- [ ] All output in vignette should be shown and written to tempdir() or tempfiles() and not on a users system. When I'm running the commands all output is saved to current directory. You hid the global option for this in the vignette so while its true the builder should respect this, if a user is working through the code blindly it will be to their working directory - as happened with me and I polluted your package directory with output.txt and random file names like b87c26e2605a9b297621cf046edb678d7dcb9a8 which seems to be writing the output of runCWL. 
```
 cat 9b87c26e2605a9b297621cf046edb678d7dcb9a8 
-A a b c -B=d -B=e -B=f -C=g,h,i
```
  And I end up with many more as I run through all your examples manually. 

- [ ] Where is the WARNING coming from? Why are these different when I run interactively? Is this expected?

```
> readLines(tres$output)
[1] "WARNING: ignoring environment value of R_HOME"
[2] "[1] 4 2 1 9 5"                                

> readLines(r7$output)
[1] "WARNING: ignoring environment value of R_HOME"
[2] "[1]  6  9 10  1  3"                           
```

- [ ] This links displays the link correctly  but links back the the user_guide. I think because of the empty parenthesis
```
[http://www.commonwl.org]().
```
The same with this:

```
[https://www.commonwl.org/v1.0/CommandLineTool.html#CWLType]()
```

- [ ] I'm having trouble understanding the overall concept and how this would be applicable to a Bioconductor workflow -  Do you have a more specialized case that you could show in a separate vignette for a real life proof of principle. I would allow the use of eval=FALSE throughout in this case  (and you would be able to ignore the   warning about this in the checks) but to really show its utility and how it is executed in a more advance/real use case. 


# R 

- generally looks pretty good. The following are general statements that I saw throughout multiple .R files: 

- [ ] I would shorten the `cat` statements in the `show` methods where applicable 
i.e
```
    cat("class:", class(object), "\n")
    cat("cwlClass:", cwlClass(object), "\n")
    cat("cwlVersion:", cwlVersion(object), "\n")

```
doesn't need separate statements
```
    cat("class:", class(object), "\n",
        "cwlClass:", cwlClass(object), "\n",
        "cwlVersion:", cwlVersion(object), "\n")
```

- [ ] There is WARNING in the build report about library/require call
- [ ] There is a NOTE about sapply vs vapply that should be updated
- [ ] For what its worth there is an ifelse function that could be a cleaner syntax for single input 
 It takes the for ifelse(test_expression, x, y) 
i.e 
```
       if(cwlClass(cwl) == "Workflow"){
            ilist <- c(id = names(inputList)[i], inputList[[i]])
        }else{
            ilist <- inputList[[i]]
        }
```
Could be written as 
```
ilist <- ifelse((cwlClass(cwl) == "Workflow"), c(id = names(inputList)[i], inputList[[i]]), inputList[[i]])
```
Totally optional but I'm generally in favor of concise code. 

- [ ] There are occassionally comment out code chunks that should be removed. 

# Man 
- [ ] I would expand the package documentation maybe have a seealso link to main
package function


<br>
<br>
<br>

When the above have been addressed please kick off a new build with a version bump and comment back here with response/how the code has been updated.  

Thank you and I look forward to getting your package accepted into Bioconductor
~Lori

**Comment by hubentu** [comment]
Hi @lshep ,

# Readme
￼ Installation instructions added.

# vignette
1. user_guide.Rmd has been renamed to Rcwl.Rmd.
2. All outputs have been defined to tempdir() by `outdir` option.
3. I could not repeat your warning from `readLines` outputs. The warning was not shown when I run check in the bioconductor/devel_core2 container. It might be caused by the R environment set in Renviron via google.
4. The links were fixed.
5. Real Bioinformatics pipelines and examples are packaged in another package `RcwlPipelines`. A new section of Resources was added to give more details about how this package could be used in practice.

# R
1. The show methods updated with shorter cat statements.
2. The internal function `runFun` is used to assign `Rcwl` functions and inputs to each computing nodes in cluster server via the `BiocParallel`, so `library(Rcwl)` is used in this function.
3. sapply was changed to vapply.
4. I prefer shorter if and else. Thanks..
5. Commented codes were cleaned.

# Man
seealso links added to main package man.

Thanks,
Qiang

**Comment by lshep** [comment]
Sorry for the delay - I'm looking at the package and should have a review within the next day or two.

**Comment by lshep** [comment]
I still would also add the Bioconductor installation instructions to the README.md
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Rcwl")
```
But otherwise looks good.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hubentu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rcwl")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rcwl

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
