### ISSUE TITLE
divergence

### ISSUE THREAD

**Issue by wikum** [Bioconductor/Contributions#981]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wikum/divergence

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
While working through the errors, please consider that your package is being contributed to Bioconductor, where re-use of standard packages results in more robust code and greater interoperability with other packages. Parallel evaluation might use [BiocParallel][1], for instance by default it performs appropriately for Windows and non-windows platforms. Your inputs sound like [SummarizedExperiment][2] and it would be good to modify your user-facing functions to accept this type of object.

[1]: https://bioconductor.org/packages/devel/BiocParallel
[2]: https://bioconductor.org/packages/devel/SummarizedExperiment

**Comment by mtmorgan** [comment]
DESCRIPTION

- (required) please provide more descriptive Title: and Description: fields, like a paper title and abstract that help orient the user.

vignette

- (required) Your package seems to work with feature x sample (e.g., RNA-seq expression) data. It should therefore be interoperable with existing Bioconductor data representations of the same data, in particular the [SummarizedExperiment][1] class. Implement your functions so they accept as inputs SummarizedExperiment objects. Update your vignette so that it illustrates work flows using this data structure. For instance at divergence.Rmd:75 one might expect, where `se` is a SummarizedExperiment object,

    ```
    assays(se)$quantile <- computeQuantileMatrix(se)
    ```
    
- (Consider) using GeneSetCollection representations in the [GSEABase][2] package

R

- chisq.R:11 avoid highly nested code `apply(..., if(..., sapply(..., sapply(...`. I believe this is more clearly written as

    ```
    rowChiSq <- function(obs, exp) {
        if(length(unique(obs)) > 1) {
            chisq.test(xtabs(~obs + exp))
        } else {
          list(statistic=NA, p.value=NA)
        }
    }
    
    chiSquaredTest <- function(Mat, Groups, classes) {
        ...
        ch <- apply(Mat, 1, rowChiSq, Groups)
        ...
    }
    ```

- use `NA` rather than `""` for missing values in the data set `breastTCGA_ER`. use `na.action=` and similar to control handling of NAs in computations like `xtabs()`, above.

- use `message()` rather than `cat()` to communicate information messages to the user. `messages()` automatically pastes arguments together, so formulations like `message(print(...))` are rarely necesssary.

- use vectorization (one R-level fucntion call) rather than iteration (n R-level function calls, e.g., `apply()`, `lapply()`, etc) when possible. For instance divergence.R:10

    ```
    quantileTransform = function(x){
        x = x - min(x)
        y = x
        z = rank(x[x > 0], ties.method="min")
        y[x > 0] = (z - min(z))/sum(x > 0)
        y
    }
    ...
    newMat = apply(Mat, 2, function(x) quantileTransform(x))
    ```

  might be written (using efficient implementations in the matrixStats package) as

    ```
    colSweep <- function(X, v)
        t( op(t(X), v) )
    X <- colSweep(Mat, colMins(Mat), `-`)
    Z <- colRanks(X, ties.method="min")
    Z1 <- colSweep(Z, colMins(Z), `-`)
    colSweep(Z1, colSums(Z1), `/`)
    ```
    
  Investigate similar approaches throughout computationally intensive portions of your code.
    
- divergence.R:61 avoid `1:length(x)`, which produces unexpected results when `length(x) == 0`. Use `seq_along(x)` instead. 

- divergence.R:65 it is not usually necessary to use `which()`; the logical vector `sel <- xjn <= quanitle(xjn, beta)` can be used directly

- please use consistent indentation style, e.g., tabs are used on some lines, but spaces for `tryCatch()` at divergence.R:102

- the `tryCatch()` at divergence.R:102 (parallel computation) is different from the `tryCatch()` at divergence.R:126. Also, the decision to re-run failed parallel evaluation but not failed serial evaluation seems to be inconsistent. I believe you would like to define an `LAPPLY` that can be either parallel or serial but always uses the same `FUN`.

    ```
    LAPPLY <- if (par) function(...) {
        parallel::mclapply(..., mc.cores = parallel::detectCores() - 1L)
    } else lapply
    FUN <- function(i, M, gamma, beta, j) {
        tryCatch({
            computeSingleRange(M[i,], gamma, beta, j)
        }, error = function(e) {
            warning(e)
            NULL
        })
    }
    L = LAPPLY(seq_len(nrow(MAT)), FUN, Mat, gamma, beta, j)
    ```

- divergence.R:142 avoid iteration with

    ```
    paste(sample(0:9, 5, replace=TRUE), collapse="")
    ```
    
  or use `tempfile()` to generate a unique temporary file name.
  
- divergence.R:156 use of `system("rm")` is not portable; use `unlink()` instead.

- divergence.R:237 as noted above, use `message()` rather than `cat()` to commuincate status or progress to users; generally, `paste()`-style is more compact and legible than `sprintf()`, e.g.,
    ```
    message(
        "Computing ranges from ", ncol(Mat),
        " reference samples for ", nrow(Mat), " features"
    )
    ```

- util.R:83 this check is not correct. If the user does not have the `parallel` package, then `parallel` remains unchanged from it's original TRUE value. However, `requireNamespace("parallel")` fails if "parallel" is not installed, so the test for `"parallel" %in% rownames(installed.packages())` is redundant; in addition, the "parallel" package is a 'base' package, so is always available and `requireNamespace("parallel")` always succeeds. `mclapply()` always exists in the parallel name space, but `exists("mclapply")` fails when the package is loaded (e.g., via `requireNamespace()`) but not attached to the search path (e.g., by `library("parallel")`). `mclapply` is defined on windows, but fails when `mc.cores != 1L`. The only test required is whether the user is on Windows or not
    ```
    if (parallel && identical(.Platform$OS.type, "windows"))
        stop("parallel support not available on windows")
    ```
  or maybe
    ```
    parallel <- parallel && !identical(.Platform$OS.type, "windows")
    ```

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/packages/GSEABase

**Comment by wikum** [comment]
Hi Martin, thanks for the review. The following changes have been incorporated into the package now:

- SummarizedExperiment has been incorporated throughout the package.
- Title and Description have been updated.
- [chisq.R] chiSquaredTest updated as suggested.
- [divergence.R, setDivergence.R] cat() has been replaced with message() for providing information to the user.
- [divergence.R, setDivergence.R] 1:length(x) type iterations have been replaced by seq_along()
- [divergence.R] temporary file names generated with tempfile() instead of ad-hoc method.
- [divergence.R] system("rm") replaced by unlink().
- [util.R] Parallelization check replaced with simpler check for windows platform.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wikum.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("divergence")`. The package 'landing page' will be created at

https://bioconductor.org/packages/divergence

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
