### ISSUE TITLE
macrophage

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/Contributions#984]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mikelove/macrophage

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mikelove** [comment]
Question for @Kayla-Morrell 

I have a software package which builds on this one as a data package. Should I add the software to this thread or would you prefer I wait and post as a new issue?

**Comment by Kayla-Morrell** [comment]
Hey @mikelove,

Ultimately it's up to you which way you prefer. I was about to accept the data package because everything looked good but then you would have to wait for it to be officially accepted and then go through a build cycle (without any issues) before the data would be available for the software package.

If it is directly related (depends/imports/etc.) feel free to submit on this thread using `AdditionalPackage:` with the github repo url. This way the single package builder can find the data package (in it's current state) for the software package. I'll be able to start the review for the software package as soon as there is a clean build.

Best,
Kayla

**Comment by mikelove** [comment]
Thanks for the details. That makes sense (i hadn't thought about the build cycle part)

We're still getting the package in order, so I'll post it as a new issue next week probably. Thanks for clarifying, and thanks for your time during review.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mikelove.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("macrophage")`. The package 'landing page' will be created at

https://bioconductor.org/packages/macrophage

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mikelove** [comment]
Hi, 

I checked out the Bioc git package and then tried to push a change but i get the following:

```
> git push origin master
fatal: remote error: FATAL: W any packages/macrophage nobody DENIED by fallthru
(or you mis-spelled the reponame)
> git remote -v
origin	https://git.bioconductor.org/packages/macrophage (fetch)
origin	https://git.bioconductor.org/packages/macrophage (push)
```

This is on a machine where I have other Bioc repositories and no problem pushing. Any ideas why I can't push to Bioc git repo?

Here's the landing page:

http://master.bioconductor.org/packages/3.9/data/experiment/html/macrophage.html

**Comment by mtmorgan** [comment]
It needs to be checked out with ssh, using `git clone git@git.bioconductor.org:packages/macrophage` (note `:packages` versus `/packages`).

**Comment by mikelove** [comment]
Doh, thanks, i was copy pasting without looking.
