### ISSUE TITLE
hypeR

### ISSUE THREAD

**Issue by anfederico** [Bioconductor/Contributions#986]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/montilab/hypeR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment]
Hi, 

Thank you for submitting your package to Bioconductor. You can expect an official review within 2 weeks from the last successful build. 

Cheers,
Qian

**Comment by anfederico** [comment]
Any update on the status of the review?

**Comment by Liubuntu** [comment]
Hi @anfederico , 

For some reason, this package has not been showing on my github package issue list. Sorry for the delay. I'll work on it right now and get back to you shortly. 

Best,
Qian

**Comment by anfederico** [comment]
No worries, just wanted to make sure it didn't get buried!

**Comment by Liubuntu** [comment]
Hi @anfederico , 

Sorry again for the delay. Here are some issues in your package. Please seek to address all / most of them and comment back with any questions or argument why you cannot implement modifications on specific issues. Thanks for your contribution to Bioconductor. 

Cheers, 
Qian

## DESCRIPTION
- looks good. 

## NAMESPACE
- Exported functions should use camel case or underscoring and not
  include “.” indicate S3 dispatch. See [here](https://bioconductor.org/developers/package-guidelines/#namespace). 

## README.*
- Seems that `README.Rmd` is section from `vignette/hypeR` and could
  be removed.

## R/
- add default values for arguments in "download.gsets" and
  "db.get()". If all possible values are from a fixed set, provide all
  values in the argument or parameter documentation.
- "download.msigdb": provide an argument for output filepath instead
  of writing directly to the package folder / working directory /
  arbitrary folders, which are highly discouraged. Leave the choice to
  users. Add documentations for new arguments.
- "hyper.enrichment" is well documented, do you want to export it?
  otherwise, if it's mainly intended as internal use, Prefix
  non-exported functions with a ‘.’. See
  [here](https://www.bioconductor.org/developers/how-to/coding-style/)
  for coding style suggestions.

## man/
- "download.msigdb": Does this `species` argument only support "Homo
  Sapiens" or also support other species? Put all possible values in
  the documentation or directly in the argument. e.g.,
  `function(species = c("Homo sapiens", "some other species", ...))`
  and then use `match.args()` in the body of the function to check for
  partial match. In this way, the default value of `species` would
  still be "Homo sapiens". 
- "db.info". `@return` actually returns a table of ... instead of "None". 
- "db.get". Since the `inst/extdata/...` is not directly visible to
  users, so put all 3 possible values in the documentation. 

## tests
- looks good. 

## vignette

- Start first level header using `# Introduction`, `# Installation`,
  `# Workflows`, `# Session info`. And use 2nd level header using `##
  Print Available Gene Sets`... Then you TOC would print much
  organized as `1... 1.1 ... ` instead of `0.001... 0.002 ...`.

- Add an `Introduction` section in the beginning which serves as an
  abstract of a research paper. e.g., to introduce the objective,
  models, unique functions, key points that distinguish it from other
  similar packages of your package.

- After the Introduction, please add a section for `Installation` to
  show to users how to install the package as if it has been included
  in Bioconductor. Because new packages is going to be in Bioc devel
  (Bioc 3.8), they are required to use `BiocManager` instead of
  `BiocInstaller` for downloading the package. You should include
  something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")
        
Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)
        
2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```
        
- Please add in the end of the vignette a section of `SessionInfo` for your 
vignette running environment. E.g.,
```
{r}
sessionInfo()
```

- Add more explanatory contents in each section, instead only printing
  the code chunk and the output.

**Comment by anfederico** [comment]
Hi Qian,

Thanks for the review. I followed your recommendation on all issues except a coupe:

1. Functions download_msigdb() and download_gsets() are utilizing the R package msigdbr to download genesets. There are many options for species, categories, and subcategories, therefore in the documentation I tell users to refer to their documentation to view available options. I hope this is sufficient.

2. By default, download_msigdb() downloads all human genesets from msigdb. Because I expect the vast majority of users will use these genesets, the easiest workflow for them will be to install hypeR and immediately download all these genesets to the package. They can then seamlessly use them with the db_get() and db_info() functions. I would include all these genesets pre-installed however it pushes the package over the 5 MB size limit. I added a section after the installation instructions in the vignette to direct users.

I have also provided an optional argument for users to download these genesets to a specified directory, however I doubt many will. To avoid confusion, I explicitly state where genesets are downloaded.

Best,
Anthony

**Comment by Liubuntu** [comment]
Hi @anfederico , 

Thanks for the quick fixes. Here are some additional comments: 

## R/
> "download.msigdb": provide an argument for output filepath instead
> of writing directly to the package folder / working directory
> arbitrary folders, which are highly discouraged. Leave the choice to
> users. Add documentations for new arguments.

It's better to use `output_dir = tempfile()` or `tempdir()` instead of
`system.file("extdata", package = "hypeR")` as default value. Think
about the case that users run your package on cluster where they don't
have write permission to the package installation path. It's good
that you are printing out the `output_dir` explicitly.

## man/

> (refer to the msigdbr R package for available species)

Direct users to `?msigdbr::msigdbr`, which is more specific. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @anfederico , 

Your changes look good. I am accepting the package now. 

Cheers,
Qian

**Comment by anfederico** [comment]
Great, thank you for all the feedback and help!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anfederico.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("hypeR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hypeR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
