### ISSUE TITLE
SMAD

### ISSUE THREAD

**Issue by zqzneptune** [Bioconductor/Contributions#993]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zqzneptune/SMAD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by zqzneptune** [comment]
Hello, Reviewer,
Just a quick check-in on the review progress, is there anything I have missed to push?

Kind regards,

**Comment by mtmorgan** [comment]
DESCRIPTON

- no need for `Maintainer:` field when `Authors@R` specified.

- Provide more detail in `Description:`, like a paper abstract so someone understands what methods are available and how these differ from other pacakges.

vignettes

- it would be very helpful to provide additional information in the vignette, e.g., simple data exploration, visualization and interpretation of the outputs of each function.

R

- e.g., CompPASS.R:36 start each user-facing function by validating the user input, e.g., 
    ```
    stopifnot(
        is.data.frame(datInput),
        all(c("idRun", "idBait", "idPrey", "countPrey") %in% rownaems(datInput),
        ...
    )
    ```

- CompPASS.R:70 use efficient 'vectorized' (one R-level function call) computation rather than iteration, e.g., `rowMenas(statsTable)`; see also functions in the `matrixStats` package. Also elsewhere in the code, e.g., CompPASSplus.R:124 `rowSums(m) / k`.

- Is the C++ code really necessary? I think it is relatively efficiently implemented as

    ```
    getPPN <- function(M) {
        res <- matrix(0, ncol(M), ncol(M))
        for (i in seq_len(ncol(M)))
            for(j in seq_len(i - 1))
                res[i, j] <- sum(pmin(M[,i], M[,j]))
        res
    }
    ```

**Comment by zqzneptune** [comment]
Hello, Reviewer,

Thank you very much for your inputs. I have addressed your comments accordingly.

However, for the last point, it is necessary to implement C++ code, which could decrease the computing time by several orders of magnitude:

```{r}
dim(g)
[1] 1990  568
> system.time(smadPPN <- SMAD::GetPPN(t(g)))
   user  system elapsed 
  1.603   0.018   1.620 
> system.time(ppn <- getPPN(t(g)))
   user  system elapsed 
 98.642   0.082  98.718 
> identical(smadPPN, ppn)
[1] TRUE
```

**Comment by mtmorgan** [comment]
Thanks; note that
```
stop(paste0("Input data missing: ", paste(missingCol, collapse = ", ")))
```
can be simply
```
stop("Input data missing: ", paste(missingCol, collapse = ", "))
```
and similar

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zqzneptune.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SMAD")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SMAD

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
