### ISSUE TITLE
BiocSingular

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#996]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/BiocSingular

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment]
Looks like a bug with _BiocParallel_ when attempting to construct a `MulticoreParam()` on Windows. Previously this would just default to `SerialParam()` and just keep going. Any thoughts @mtmorgan? I notice _BiocParallel_ is failing on Windows in devel but this seems to be for an unrelated reason.

**Comment by mtmorgan** [comment]
Looks like it's from 
```
BiocSingular master$ grep -r MulticoreP vignettes/BiocSingular.Rmd
vignettes/BiocSingular.Rmd:i.out2 <- runSVD(dummy, k=10, BSPARAM=ipam, BPPARAM=MulticoreParam(2))
```
Explicitly calling `MulticoreParam(2)` has always (tried to) create a MulticoreParam instance; calling without arguments `MulticoreParam()` will default to 1 core (serial evaluation) on Windows, and will throttle (to 4 cores) on the build system. I just updated (1.17.11) the code so that `MulticoreParam(n)` will warn and create `MulticoreParam(1)` and perform serial evaluation on Windows.

**Comment by LTLA** [comment]
I'm going to convert the `DeferredMatrix` class to a `DelayedArray` backend over the weekend, so if anyone's doing some reviewing in the next few days, you might want to hold off on the `DeferredMatrix.R` file.

**Comment by LTLA** [comment]
Windows is its usual grumpy self. Funnily enough, I tested the code on my colleague's Windows computer (running the latest _BiocParallel_) and it worked fine. I guess the SPB doesn't get updated so frequently?

**Comment by LTLA** [comment]
`a487158` above uses an unusual way of defining S4 methods, I'd like some opinions on that. The aim is to avoid manually retyping the signature for each method when many of the arguments can be passed as-is.

**Comment by mtmorgan** [comment]
The trade-offs are between DRY and maintainability. In this case the 'factory' seems ok to me, reducing repetition in a way that is relatively transparent. GSEABase uses a similar approach but in a more complicated way, such that it's actually difficult for an 'outsider' to figure out what's going on.

**Comment by LTLA** [comment]
Thanks @mtmorgan. This was actually a test case for a much more extreme situation in the _BiocNeighbors_ package, where I would have had to copy-and-paste an even longer signature over 40 times. I was a bit worried about using a function to generate functions to pass to `setMethod()`, but your comments are reassuring.

**Comment by LTLA** [comment]
Gee, the SPB's taking a long time. 

In any case, I've made all the changes I've wanted to make, so it's all yours @LiNk-NY.

**Comment by LiNk-NY** [comment]
Hi Aaron, @LTLA 
I'm a bit backed up on package reviews.
It will take a couple days before I can get to yours.
Thanks for your patience. 
Best, 
Marcel

**Comment by LTLA** [comment]
No probs. BTW, I don't know what's up with the Windows failures; _BiocParallel_ updates should have fixed them.

**Comment by LiNk-NY** [comment]
Hi Aaron, @LTLA 

Thanks for submitting to Bioconductor. 
Overall, the package is in good standing and can be 
accepted rather quickly. 

Please see a few points below.

Best, 
Marcel 

---

# BiocSingular

## DESCRIPTION

* Looks good. 
* Add `BugReports` and `URL` fields.

## NAMESPACE

* Looks good.

## vignettes

* Respect the 80 column width limits in the vignettes. It makes them
easier to read as a reviewer and easier to maintain.
* Good job at making them not too dense. They're easy to read. 

## R

* Class definitions look good.
* See first bullet in vignettes.
* Should default `center` and `scale` values be `FALSE` instead of `NULL`
or is it convention to use `NULL`?
* As with other Bioconductor classes, `LowRankMatrixSeed` should work
with no arguments. For example, have resonable type defaults such as `matrix()`. 
* Consider having a constructor function for `LowRankMatrixSeed` that does
nothing with a `LowRankMatrixSeed` input (other than returning it) so
that when you create a `LowRankMatrix` you don't need test for the class in [L:121](https://github.com/LTLA/BiocSingular/blob/master/R/LowRankMatrix.R#L121)
and just run something like
`DelayedArray(LowRankMatrixSeed(rotation, components))`
* Consider combining preliminary checks for `runExactSVD`, `runRandomSVD`,
and `runIrlbaSVD` into a single helper function.

**Comment by LTLA** [comment]
Thanks @LiNk-NY. 

## Things that are done

> Add `BugReports` and `URL` fields.

Done.

> Should default `center` and `scale` values be `FALSE` instead of `NULL` or is it convention to use `NULL`?

Agreed, I've switched it to `FALSE` for all functions, which conveys a clearer intent. The exceptions are the `DeferredMatrix` constructors, which use `NULL` because it doesn't make sense to have a logical here.

> As with other Bioconductor classes, `LowRankMatrixSeed` should work with no arguments. For example, have resonable type defaults such as `matrix()`.

Done, and for `DeferredMatrixSeed` as well.

> Consider having a constructor function for `LowRankMatrixSeed` that does nothing with a `LowRankMatrixSeed` input (other than returning it) so that when you create a `LowRankMatrix` you don't need test for the class in [L:121](https://github.com/LTLA/BiocSingular/blob/master /R/LowRankMatrix.R#L121) and just run something like `DelayedArray(LowRankMatrixSeed(rotation, components))`

Done, and also for the `DeferredMatrix`.

## Things that are not

> Consider combining preliminary checks for `runExactSVD`, `runRandomSVD`, and `runIrlbaSVD` into a single helper function.

Not sure what you're referred to here. I've already centralized some checking code in `check_numbers`. There is a common block of code that I would like to centralize:

```r
    # Setting up the parallelization environment.
    old <- bpparam()
    register(BPPARAM)
    on.exit(register(old))

    if (!bpisup(BPPARAM)) {
        bpstart(BPPARAM)
        on.exit(bpstop(BPPARAM), add=TRUE)
    }
```

... but this involves setting `on.exit` expressions, and I don't see an easy way of doing this inside a helper function. Well, I guess I could (e.g., by passing an expression out), but it would be pretty hard to read.

> Respect the 80 column width limits in the vignettes. It makes them easier to read as a reviewer and easier to maintain.

I'll be honest here. Ever since the 80 character column width check came up on _BiocCheck_, I've tried and failed - multiple times - to code to that limit. I just don't understand the motivation for this. My text is restricted to half of my screen! Are people reading code on their phones or something? 

I can understand the motivation to break up very long lines, but 80 characters barely gets me anywhere, especially once I start indenting within functions. In projects like _iSEE_ where deep indenting was unavoidable, we would have been working with <40 characters per line if we tried to stick to the limit. (And we did try, but that stopped pretty quickly once we had to start a new line for every argument to a function call.)

For vignettes, I would also dispute that the 80 character limit simplifies maintenance. I'd have to redo the line wrap every time I modified a sentence. This is a pain to remember and it also adds a lot of noise to `git diff` when I want to figure out which lines have changed. I generally try to keep a 1:1 mapping between lines and sentences in my vignettes, which is easy to read (I read each line, I think about the message, and I move onto the next line) and maintain (one sentence change results in a one line change in the `git diff` output). If I do have a long sentence, I break it up by its structure (e.g., clauses, phrases, parentheses). This provides greater modularity for easier reading - one idea is one line - and more modular changes for easier `diff`ing.

**Comment by LiNk-NY** [comment]
Hi Aaron, @LTLA 
Thanks for making those changes.
For the first item not done, leave it as is. It is easier to read.

For the second item, it suppose it depends on the tools that you're
using to edit text in the vignette and if you're using panes.
Viewing it in vim, the text runs off the screen and it's harder to not only
read but to access parts of a long sentence quickly. 
If it works for you, keep it as is. 

Best, 
Marcel

**Comment by LTLA** [comment]
Okay, thanks @LiNk-NY.

**Comment by LTLA** [comment]
I don't think the Windows error is my fault, so is everything otherwise fine? There's a bunch of updates to other packages that are pending on the availability of _BiocSingular_, so I'd like to get this in.

**Comment by LiNk-NY** [comment]
Hi Aaron, @LTLA

Thanks for your submission your package has been accepted.
We will add it to the repository as soon as possible. 

Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BiocSingular")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BiocSingular

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by LTLA** [comment]
Thanks @LiNk-NY, @mtmorgan for handling the submission. Also a shout-out to @bwlewis and @erichson for incorporating changes to their packages to make this entire thing work.
