### ISSUE TITLE
ADAMgui

### ISSUE THREAD

**Issue by bads752** [Bioconductor/Contributions#997]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jrybarczyk/ADAMgui

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by bads752** [comment]
As requested in issue #908 by @LiNk-NY, we have separated the ADAM package into a statistical module and a graphical module. The statistical module has been already accepted in bioconductor (see issue #908). Now we are submitting the graphical module by the name ADAMgui.

**Comment by Liubuntu** [comment]
Hi,

Thank you for submitting your package to Bioconductor. You can expect an official review within 2 weeks from the last successful build.

Cheers,
Qian

**Comment by Liubuntu** [comment]
Hi @bads752 

Sorry for the delay in the review process. I'll start reviewing and get back to you very soon!

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Here is the comments for the first review of your package. Please try to address all / most of these issues, and comment back with any questions, or explanation for why some were not addressed. 

The comments for vignette will be added shortly. 

Best,
Qian

## DESCRIPTION
- add "BugReports:” field: It is encouraged to include the relevant links
  to Github for reporting Issues.
- add “URL:” field: This field directs users to source code
repositories, additional help resources, etc; details are provided in
“Writing R Extensions”, RShowDoc("R-exts").  For more package
guidelines, check
[here](http://bioconductor.org/developers/package-guidelines/#description).

## NAMESPACE
- As you are using a lot functions from `shiny`, so better to import
  the whole package and make the NAMESPACE tidier.

## R/`GFAGpathUi.R`
- add default value for `browser` argument.
- avoid duplicate code in calling `shiny::runApp`, pass `browser` directly into `launch.browser`.
- `error = function(e) print(...)` could be `error = print(...)`
- In summary, code could be simplified in multiple places:
```                                                                                                                                                                                                                                                          
GFAGpathUi <-function(browser = TRUE){                                                                                                                                                                                                                       
    tryCatch(                                                                                                                                                                                                                                                
        shiny::runApp(paste0(system.file("shiny", package="ADAMgui"), "/app.R"), launch.browser = browser), 
        error = print("Parameter must be TRUE or FALSE") 
 )}                                                                                                                                                                                                                                                       
```                                                                                                                                                                                                                                                          
All above comments apply to `GFAGtargetUi.R`.

## man/`GFAGpathUi.Rd`
- examples `data(ExpressionAedes)` exists in `ADAM` but not in this
  package.
- Is it required to do `write.table()` for the example data before
  `GFAGpathUi()`?
- above also applies to `GFAGtargetUi.Rd`.

## inst/shiny: `app.R` and `app2.R`
- Please remove `suppressMessage(require(...))`. Since these packages
  have already been included in `DESCRIPTION, Imports`, when calling
  functions from these pkgs, error message will be automatically
  returned, showing users that they need to install before using
  relative functions.

## tests/tests_ADAMgui.R
- if you add default values e.g., `GFAGpathUi(browser = TRUE)`, these
  test functions could be removed.

**Comment by Liubuntu** [comment]
## vignette
- for some reason, the vignette html file I generated does not have
  the header section. I didn't get any error from building, could you
  check if there is any problem or let me know if you can get the
  header? Thanks!
- please add a section for "Installation" to show to users how to
  install the package as if it has been included in
  Bioconductor. Because new packages is going to be in Bioc devel
  (Bioc 3.8), they are required to use `BiocManager` instead of
  `BiocInstaller` for downloading the package. You should include
  something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")
        
Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```
- Add a table of contents for better organization. This could be
  easily specified in the header. check here:
  https://rmarkdown.rstudio.com/html_document_format.html.

- Please add in the end of the vignette a section of `SessionInfo` for
  your vignette running environment. E.g.,
```
{r}
sessionInfo()
```
- L24: `...activity (@Castro2009)` the link is not set correctly and
  shows `???` in the html file. Same issue as L38: `(@molan2018)` and
  L41:`@fontoura2016`.
- Typos: L53: `allways`. L55: `bellow` (all over ...). Run a spell
  checker if possible.

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Just a reminder that you need to respond to the previous review within 2 weeks, by replying questions, making modifications with new pushes, or ask questions. Thanks!

Best,
Qian

**Comment by bads752** [comment]
Hi @Liubuntu, I sorry for the late reply. Below are the coments in regards
to your suggestions. I took the freedom to enumerate them from 1 to 20 
so it is easier  for us to talk about them. I want to make it clear that most 
problems have been corrected, save a couple of issues. Particularly 
suggestions number 3, 5, 11, 15, 17 and 19.

Best regards,
bads752.

**DESCRIPTION**


    1 - Please remove “LazyData = true”. This rarely proves to be a good thing.
    In our experience it only slows down the loading of packages with large data.
    
Answer: Done!
    
    2 - add "BugReports:” field: It is encouraged to include the relevant links
    to Github for reporting Issues.
    
Answer: Done!

    3 - add “URL:” field: This field directs users to source code
    repositories, additional help resources, etc; details are provided in
    “Writing R Extensions”, RShowDoc("R-exts"). For more package
    guidelines, check here.
    
Answer: The web page refering to ADAMgui is still under development. So we added 
the "URL:" field as TBA (To be Announced)
    
    4 - Please add Suggests: BiocStyle since the vignette is using functions from 
    this package. doc_date and pkg_ver.
    
Answer: Done!


**NAMESPACE**

    5 - As you are using a lot functions from shiny, so better to import
    the whole package and make the NAMESPACE tidier.
    
Answer: We choose to import functions individually to avoid name conflicts with functions from other packages. if possible we would like to let this approach unaltered.

**R/GFAGpathUi.R & R/GFAGtargetUi.R**

    6 - add default value for browser argument.
    
Answer: Done! Now 'browser = TRUE'

    7 - avoid duplicate code in calling shiny::runApp, pass browser directly into launch.browser.
    
Answer: Done! By setting the default value of 'browser = TRUE' we avoided the code duplication. 

    8 - error = function(e) print(...) could be error = print(...)
    
Answer: Done!

    9 - In summary, code could be simplified in multiple places:
    GFAGpathUi <-function(browser = TRUE                {                                                                                                                                                                                                                        tryCatch(                                                                                                                                                                                                                                                
        shiny::runApp(paste0(system.file("shiny", package="ADAMgui"), "/app.R"), launch.browser = browser), 
        error = print("Parameter must be TRUE or FALSE") )}                                                                                                                                                                                                                                                       


Answer: We simplified the code for both the GFAGpathUi.R and GFAGtargetUi.R functions

**man/GFAGpathUi.Rd & man/GFAGtargetUi.Rd**

    10 - Seems you don't have '*Hs' data available in both ADAM and ADAMgui.
    Please update your examples. Or comment before the code chunk saying 
    that these files are required as inputs for the api.
    
Answer: We removed the '*Hs' examples. Now we only use the 'Aedes' data for the examples.

    11 - Is it required to do write.table() for the example data before GFAGpathUi()?
    
Answer: No it is not, but the apps are useless without correctly formatted input files.
 We use the write.table()  function in the examples so the user can see the 
format of the input data files for each app.    

    12 - above also applies to GFAGtargetUi.Rd.
    
Answer: Done! Refer to 9.

**inst/shiny: app.R and app2.R**

    13 - Please remove suppressMessage(require(...)). Since these packages
    have already been included in DESCRIPTION, Imports, when calling
    functions from these pkgs, error message will be automatically
    returned, showing users that they need to install before using
    relative functions.
    
Answer: Done!

**tests/tests_ADAMgui.R**

    14 - if you add default values e.g., GFAGpathUi(browser = TRUE), these
    test functions could be removed.
    
Answer: Done! The 'tests' folder and it's contents have been removed!

**vignette**

    15 - for some reason, the vignette html file I generated does not have
    the header section. I didn't get any error from building, could you
    check if there is any problem or let me know if you can get the
    header? Thanks!
    
Answer: We are not having any issues with the genereted vignette here. The vignette also 
does not have any problems with the header, table of contents (ToC) and the references. We though that your problem could be caused by missing or non-updated packages and ubuntu libraries. 
So we builded the ADAMgui package in other PCs, some of them had fresh installed ubuntu 18.04.
As expected the package and it's vignette could not be build without all of the necessary
dependencies. We installed the necessary dependencies one by one as prompted by R console. 
In the end we were able to correctly build the package and it's vignette without problems...
We are sending a new bump of the ADAMgui package with many of the suggested corrections,
should the problem with the vignette persist could you send us a print of the vignette?
    
    
    
    16 - please add a section for "Installation" to show to users how to
    install the package as if it has been included in
    Bioconductor. Because new packages is going to be in Bioc devel
    (Bioc 3.8), they are required to use BiocManager instead of
    BiocInstaller for downloading the package. You should include
    something like this:


    1. Download the package from Bioconductor.

    {r getPackage, eval=FALSE}
    if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
    BiocManager::install("pkgName")
        
    Or install the development version of the package from Github.
    {r, eval = FALSE}
    BiocManager::install(“githubUserName/pkgname”)

    2. Load the package into R session.
    {r Load, message=FALSE}
    library(pkgName)
    
Answer: Done! Added the "Package Download and Installation" section to cover the issue.
    
    17 - Add a table of contents for better organization. This could be
    easily specified in the header. check here:
    https://rmarkdown.rstudio.com/html_document_format.html.
    
Answer: Please refer to 15!

    18 - Please add in the end of the vignette a section of SessionInfo for
    your vignette running environment. E.g.,

    {r}
    sessionInfo()

Answer: Done!

    19 - L24: ...activity (@Castro2009) the link is not set correctly and
    shows ??? in the html file. Same issue as L38: (@molan2018) and
    L41:@fontoura2016.
    
Answer: Please refer to 15.
    
    20 - Typos: L53: allways. L55: bellow (all over ...). Run a spell
    checker if possible.
    
Answer: Done! Other typos have been found and corrected!

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Thanks for making those changes. I'll go through your changes and my own setting (ubuntu 18.04) for the vignette issue. Thanks for your suggestions. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Please see the following and let me know for any question. Thanks!

## NAMESPACE
- For conflicting function names, use `@rawNamespace import(shiny,
  except=c("funName1", "funName2", ...))`.

## unit test
- I see you have removed unnecessary tests, It's strongly recommended
  to add unit tests for your major functions to make the package more
  robust.

## vignette
> 16 - Added the "Package Download and Installation" section to cover the issue.
> 18 - Please add in the end of the vignette a section of SessionInfo for your vignette running environment. E.g.,

I don't see either of these two sections in your vignette...

Best,
Qian

**Comment by Liubuntu** [comment]
Reminder that if you made any commits or changes, bump the version in DESCRIPTION to trigger a new build. Thanks!

**Comment by bads752** [comment]
Hi @Liubuntu, 

The issues with NAMESPACE and Vignette are straightforward and simple to solve. However I having trouble trying to understand the issue with the test. Since the package is, essentially, a Shiny App, most functions are dependent of arbitrary user inputs. That said, i though that the only viable test that could be done would be to see if the functions that calls the apps were working correctly.  The "thestthat" tests that I made previously, and that you asked to remove, had this purpose. So my question is: how could I implement the unit test that you suggest? What kind of functions could I test that does not include the app calling functions? 

"Reminder that if you made any commits or changes, bump the version in DESCRIPTION to trigger a new build. Thanks!"

Thanks for the reminder, I aware of the version bump requirement, but I choose to not do so because I still have not solved the test issue. In fact I will be waiting your reply to the question above so I can do the version bump and trigger the new build.

Best regards,
Bads752

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Please see following: 
  
## inst/shiny/*.R

- Please try to move all these shiny app scripts into `R/` folder.
- remove those `require()` in the beginning of the scripts.

## Unit tests

- Basically you have to decompose the functionality of the RShiny app
  until your can simply use `testthat`, so the functions can be tested
  without actually running the app.

A useful links to refer:
https://stackoverflow.com/questions/36338779/unit-testing-shiny-apps
. Look at the second answer by Stephen Kirk, and focus on "testing the
underlying functionality".

Best,
Qian

**Comment by bads752** [comment]
Hi @Liubuntu ,

I was unable to complete all the necessary alterations in the 2-week deadline. So i writing this message to inform you that I am still working on the unit test.

Best regards, 
Bads752

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Those unit tests are strongly recommended but not strictly required. I was talking with the Bioconductor core team for correct unit tests for the GUI packages, and the above comment was the solutions we had for now. These shiny apps are emerging recently also in Bioconductor, we are still working on a standardized review strategies. 

So  don't worry too much about the unit test, but bear in mind that in further development, R functions should be break down into testable units, and put in the R/ directory. I have had another good example [here](https://github.com/csoneson/iSEE). 

Given that your software package was already included in Bioconductor, and this one doesn't have major issues, I'm accepting it now. You can always work on improvement later. 

Cheers, 
Qian

**Comment by Liubuntu** [comment]
Hi @bads752 , 

Reminder that you should bump version in DESCRIPTION for your commits made on March 27th and 28th. So that I can review those most recent updates and proceed to acceptance. 

Best,
Qian

**Comment by bads752** [comment]
Hi @Liubuntu,

I just did a version bump of the package. It is mostly unaltered since the last bump, the only notable changes in this bump are related to the app calling functions (GFAGpathUi and GFAGtargetUi). Since the shinyapp() function does not automatically launches the app in local machine when launch.browser parameter is FALSE (it simply does not launch anything at all), conditional loops (if else) are required along with code repetition. Since the unit tests are not a MUST for now, this version of the package will have no tests at all.

I am really thankful for the support and tips that you gave me in order to improve the package. I will follow your instructions and I will try to make unit tests for the shiny applications in future updates.

Best regards,
@bads752

**Comment by Liubuntu** [comment]
Hi @bads752 , 

I reviewed your changes with the commit, and here are couple minor issues to fix. Let me know for any questions. 

Best,
Qian

## R
- R/GFAGpathUi.R: L36,42: Avoid double checking for `if(browser=TRUE)`, use
  `if(browser)` or `if(!browser)` instead.
- R/GFAGpathUi.R: L37,43: Instead of `paste0("a", "/b")` use
  `file.path("a", "b")` and you can get directly the file path of
  "a/b".
- Same above issues for "R/GFAGtargetUi.R".

## inst/shiny: `app.R` and `app2.R`
- Please remove `library(...)`. Since these packages
  have already been included in `DESCRIPTION, Imports`, when calling
  functions from these pkgs, error message will be automatically
  returned, showing users that they need to install before using
  relative functions.
  I have tried to comment all lines of your `library()` commands in
  `app.R` and `app2.R`, and seems that the `GFAGpathUi(browser=TRUE)`
  still works. Please try to remove and test in your end and let me
  know if this is correct!

## vignette

- ADAMgui.Rmd: L65. When installing github repo by BiocManager, you
should do `BiocManager::install("jrybarczyk/ADAMgui")` instead of
`BiocManager::install('https://github.com/jrybarczyk/ADAMgui')`. Only
keep the `folderName/pkgName`. Here is the documentation for
`BiocManager::install(pkgs = )` argument:
```
    pkgs: ‘character()’ vector of package names to install or update.
          A missing value updates installed packages according to
          ‘update =’ and ‘ask =’. Package names containing a '/' are
          treated as GitHub repositories and installed using
          ‘remotes::install_github()’.
```
See `?BiocManager::install` for more details.

**Comment by bads752** [comment]
Hi @Liubuntu ,

I made all the required corrections, a new version bump has also been done already.
I await your evaluation.

Best regards,
bads752

**Comment by Liubuntu** [comment]
HI @bads752  

The new update looks great! I'm accepting the package now. 

Cheers,
Qian

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bads752.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ADAMgui")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ADAMgui

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
