### ISSUE TITLE
CellBench

### ISSUE THREAD

**Issue by Shians** [Bioconductor/Contributions#998]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Shians/CellBench

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update the Description: field to contain an abstract of the package functionality.

**Comment by Shians** [comment]
Added package description and fixed some other BiocCheck issues. Currently just getting warnings about checks taking >5min to run.

**Comment by dvantwisk** [comment]
I apologize for the silence on my end. At this point, I think your current check times are acceptable and we go forgo the final warning. I will have a review of your package soon.

**Comment by dvantwisk** [comment]
Hello,
I've completed and initial review of your package. The package as a whole looks very well written but there are two large issues that I need to see addressed before moving forward with a more thorough review. Please message me back with any questions or comments you may have.

R/
- [REQUIRED] It appears that you are using the s3 class system to initiate
methods and create classes. The Bioconductor project requires the s4 class
system to be used. Please convert all methods and classes to the s4 system:
http://adv-r.had.co.nz/S4.html
https://kasperdanielhansen.github.io/genbioconductor/html/R_S4.html
https://www.bioconductor.org/help/course-materials/2017/Zurich/S4-classes-and-methods.html

vignettes/
- [REQUIRED] In both `DataManipulation.Rmd` and `Introduction.Rmd` there are a
lot of `eval=FALSE`s being used. We generally want to see user facing code run
in the vignettes for testing purposes since it is expected for the code to work
for the user. Is there a reason why you are using `eval=FALSE`s throughout your
vignette?

**Comment by Shians** [comment]
Hi Daniel,
Thanks for reviewing my package.

My use of S3 classes is for interoperability with tidyverse features, in particular almost all my data objects are inheriting from tibbles for dplyr compatibility. I don't want to take them S4 because they would become S3 upon first contact with tidyverse anyway.

The `eval=FALSE` code in my vignettes are all cases of code that affect the filesystem (creates new folders), code that is intentionally slow (calling `sleep()`), code that is expected to fail, trivial code (I demonstrate `x <- 1` for example) or code that is run earlier in the vignette that I've isolated for explanatory purposes. Of these I could change the trivial and repeated code to `eval = TRUE, result = 'hide'`, but the rest shouldn't be run while installing or checking.

**Comment by dvantwisk** [comment]
S4 classes are largely interoperable with S3 functionality and can extend s3 classes. For example, we want to create a class `A` that inherits the functionality of `tibble`'s `tibble`. We can do that like:
```
#' @importFrom tibble tibble

## setOldClass() allows us to treat s3 classes as s4 classes
setOldClass('tibble')
A <- setClass('A', contains='tibble')

## check if an object of class A is a tibble
a <- A()
is(a, 'tibble')
## TRUE
``` 

If we want to write a method for `A` to dispatch on the `dplyr` method `filter()`, you can still write:
```
#' @importFrom dplyr filter
filter.A <- function(object, ...)
{
<code>
}
```
The remaining s3 classes and methods that you create can be rewritten as s4 classes and  methods.

I don't think there would be any cases in your code where this couldn't be done. The Bioconductor project requires s4 for all user facing-functionality. This document gives some of the reasons why we require this: https://www.bioconductor.org/help/course-materials/2017/Zurich/S4-classes-and-methods.html#strengths-of-s4-compared-to-s3

For the `eval=FALSE`s in the vignette, the code that is expected to fail seems fine. For file system related code, you could use the `tempfile()` and `tempdir()` functions to create temporary files and directories that will be removed upon termination of the session instead of saving files the user's directory. For `sleep()` related code, is it possible to give a less-time consuming example in the vignette? For trivial code, even if it's very simple, I don't see why it shouldn't be run.

Thank you for reading my explanations and I hope it won't be too much trouble to make these changes in order to conform to Bioconductor's standards. I really like how well written this package is and I think it looks to provide very useful functionality. I am happy to help wherever I can with getting it onto Bioconductor.

**Comment by dvantwisk** [comment]
Another little note with regards to s3 dispatch. When a object is created with `as_tibble()` it has classes `"tbl_df"     "tbl"        "data.frame"`, so it may make more sense to use `tbl_df` or `tbl` when creating a class.

**Comment by Shians** [comment]
I have removed as many `eval = FALSE` as I think is sensible. I'm keeping the `sleep(2)` code on because it's there to demonstrate cached function calls, where the first run triggers a noticeable wait but subsequent runs immediate return.

I had an attempt to covert to S4 classes, but it results in some undesirable behaviour upon naive implementation.

``` r
library(methods)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tibble)
data(iris)

BenchmarkTbl <- setClass("BenchmarkTbl", contains = "tbl")

iris_tbl <- as_tibble(iris)
iris_s4 <- BenchmarkTbl(iris_tbl)

res_tbl <- iris_tbl %>%
    filter(Sepal.Length <= 5)

res_s4 <- iris_s4 %>%
    filter(Sepal.Length <= 5)
#> Warning in class(x) <- c(subclass, tibble_class): Setting class(x) to
#> multiple strings ("tbl_df", "tbl", ...); result will no longer be an S4
#> object

class(res_tbl)
#> [1] "tbl_df"     "tbl"        "data.frame"
class(res_s4)
#> [1] "data.frame"
```

Based on this, if Bioconductor is strict on the use of S4 for user-facing classes then I'd rather fall back to using naked `tbl` with `switch()` to simulate polymorphism than reimplement in S4.

**Comment by dvantwisk** [comment]
I apologize for the delay with responding. You are right that s4 classes can't do what you need it to do in this instance. I've found this issue on tidyverse's github that is very similar to yours and the developers state they have no plans to support the s4 class class system. I've consulted with other members of our group and we think in this rare instance we can allow you to use the s3 class system for using facing functions and classes, so you can ignore my comment about that.

I'll have another quick look-through of your package to see if I can find any issues and after all goes well with that, I can accept it.

**Comment by dvantwisk** [comment]
I've had another look through your package and after the changes you've already made, I really don't have anything more of consequence to mention. That package is expertly written. I'll move to accept the package once you've cleared up the remaining timeout.

**Comment by dvantwisk** [comment]
Great! I'll accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Shians.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CellBench")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CellBench

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
