### ISSUE TITLE
VennDetail

### ISSUE THREAD

**Issue by guokai8** [Bioconductor/Contributions#999]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/guokai8/VennDetail

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
This package looks like it is useful to R users in general; I recommend that you submit it to CRAN instead.

**Comment by guokai8** [comment]
Dear Reviewer,
Thanks for your suggestion. Can I still try to submit my package to biocondutor? I am a bioinformatics PhD. I more prefer biocondcutor.
 Kai

**Comment by guokai8** [comment]
Already remove the  VennDetail.Rproj file

**Comment by mtmorgan** [comment]
Remember to increment the version number (0.99.1, 0.99.2, 0.99.3...) whenever you want to have your package checked again.

Yes you can still submit this to Bioconductor.

**Comment by guokai8** [comment]
Update the test folder. And version changed to 0.99.1. Fixed the test error.

**Comment by guokai8** [comment]
This is my first package submission to Bioconductor. I apologize in advance for my lack of experience.

**Comment by guokai8** [comment]
Hi,
I just add new function in VennDetail. Now it supports to extract wide format to see the unique or shared results. 
Kai

**Comment by hpages** [comment]
Hi @guokai8 ,

Here is some initial feedback for the VennDetail package. Overall the package needs more work.

## Code quality

1. `show()` is an S4 generic defined in the methods package. Don't redefine this generic. More generally speaking, you should **never** override an existing generic function. Instead, all you need to do is define a `show()` method for your venn objects. Note that even though you are currently defining such method, the method gets attached to your `show()` generic instead of to the original `show()` generic defined in the methods package. This breaks many things downstream, starting with your `show()` method not being called when entering the name of a venn object at the command line (followed by \<ENTER\>):
    ```
    library(VennDetail)
    set.seed(123)
    A <- sample(1:5, 2, replace=FALSE)
    B <- sample(1:5, 4, replace=FALSE)
    res <- venndetail(list(A=A, B=B))
    res  # this doesn't call show(res) as it should
    ```
    BTW, calling `show(res)` explicitly shows some strange output for this object:
    ```
    show(res)
    # === Here is the detail of Venndiagram===
    # Total results:  5 x 2 
    # Total sets is: 3 
    #    Group Detail
    # 1 Shared      4
    # 2      A      2
    # 3      B      3
    # 4      B      5
    # 5      B      1
    # ... with -1 more rows
    ```
    See last line: "with -1 more rows" !?

2. Similar situation with `merge()`. This function is already defined (as an S3 generic) in the base package. Do NOT override it with your own S4 generic. Again this will break many things when people use your package in conjunction with other Bioconductor or CRAN package. You are only allowed to define methods for it, not to override the existing generic function. Note that even though `base::merge()` is an S3 method, you can define an S4 or method for it.

3. Why mix S3 generics (e.g. `result()`, `detail()`) with S4 generics (e.g. `dplot()`, `rowjoin()`, `Get()`, etc...) when introducing new generic functions? Bioconductor recommends that packages implement S4 classes instead of S3 classes. Also new generics introduced to manipulate S4 objects should preferably be defined as S4 generics instead of S3 generics.

4. Don't put curly brackets (`{ .. }`) around the call to `standardGeneric()` in your `setGeneric()` statements.

5. Plotting a venn object with 6 or more sets doesn't seem to work:
    ```
    library(VennDetail)
    A <- sample(1:1000, 400, replace=FALSE)
    B <- sample(1:1000, 600, replace=FALSE)
    C <- sample(1:1000, 350, replace=FALSE)
    D <- sample(1:1000, 550, replace=FALSE)
    E <- sample(1:1000, 450, replace=FALSE)
    F <- sample(1:1000, 750, replace=FALSE)
    res <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F), plot=TRUE)  # no plot produced
    plot(res)  # no plot produced
    ```

6. All the logic for plotting a venn object is implemented in S3 method `plot.venn()`. Why repeat that logic at the end of the `venndetail()` constructor when you could just call `plot()` on the newly created venn object? Avoiding code duplication is part of the DRY (Don't Repeat Yourself) principle, an important principle in good software engineering practices.

## Vignette

7. Always put a space after commas (`,`) and periods (`.`).

8. "offering" instead of "offerings" in "no R package offerings functions to extract"

9. The dependencies listed in the vignette don't match those listed in the DESCRIPTION file. It's actually not useful to list them in the vignette since they get automatically installed when installing the package.

10. Never install a Bioconductor package from GitHub. The proper way to install a Bioconductor package is explained here: https://bioconductor.org/install/ Either provide that link, or show the following code in your vignette:
    ```
    if (!requireNamespace("BiocManager"))
        install.packages("BiocManager")
    BiocManager::install("VennDetail")
    ```
    Or both. Note that the above code should not get evaluated when the vignette gets built (e.g. with `R CMD build`) which means that `eval=FALSE` should be used in the opening line of the code chunk.

11. Please hide the output of `library(VennDetail)` by using `results="hide"` in the opening line of the corresponding code chunk.

12. No need to call `library(VennDetail)` twice.

13. What about the empty "Support shiny now" section?

14. Overall the vignette is too minimalist. It should show how to use VennDetail on **real** data.

## Coding style

15. S4 class names capitalized i.e. _Venn_ instead of _venn_.

16. Put spaces around `<-`.

17. Put a space after commas (`,`).

18. Please remove the trailing semicolons in your code. They are not needed and hurt readability. This applies to the code chunks in the vignette and to the examples in the man pages.

Please address at your earliest convenience. Thanks!

Regards,
H.

**Comment by guokai8** [comment]
Hi, 
Thanks for you kindly suggestions. Below is the point by point revised.
## Code quality
1. show() is an S4 generic defined in the methods package. Don't redefine this generic. More generally speaking, you should never override an existing generic function. Instead, all you need to do is define a show() method for your venn objects. Note that even though you are currently defining such method, the method gets attached to your show() generic instead of to the original show() generic defined in the methods package. This breaks many things downstream, starting with your show() method not being called when entering the name of a venn object at the command line (followed by <ENTER>):  

__Response: show function was re-designed as a S3 function.__
```
library(VennDetail)
set.seed(123)
A <- sample(1:5, 2, replace=FALSE)
B <- sample(1:5, 4, replace=FALSE)
res <- venndetail(list(A=A, B=B))
res  # this doesn't call show(res) as it should
```
  __Response: The problem have been fixed.__

BTW, calling show(res) explicitly shows some strange output for this object:

__Response: The problem have been fixed as show function was not directly export now__

2. Similar situation with merge(). This function is already defined (as an S3 generic) in the base package. Do NOT override it with your own S4 generic. Again this will break many things when people use your package in conjunction with other Bioconductor or CRAN package. You are only allowed to define methods for it, not to override the existing generic function. Note that even though base::merge() is an S3 method, you can define an S4 or method for it.

__Response: merge function was re-designed as a S3 function.__

3. Why mix S3 generics (e.g. result(), detail()) with S4 generics (e.g. dplot(), rowjoin(), Get(), etc...) when introducing new generic functions? Bioconductor recommends that packages implement S4 classes instead of S3 classes. Also new generics introduced to manipulate S4 objects should preferably be defined as S4 generics instead of S3 generics.

__Response:  The result() ,detail() function were re-designed as S4 function__

4. Don't put curly brackets ({ .. }) around the call to standardGeneric() in your setGeneric() statements.

__Response: The curly brackets have been removed in  setGeneric() statements.__

5. Plotting a venn object with 6 or more sets doesn't seem to work:

__Response: The issue have been fixed.__

6. All the logic for plotting a venn object is implemented in S3 method plot.venn(). Why repeat that logic at the end of the venndetail() constructor when you could just call plot() on the newly created venn object? Avoiding code duplication is part of the DRY (Don't Repeat Yourself) principle, an important principle in good software engineering practices.

__Response: The plot parameter in the _venndetail_ have been removed__

## Vignette

7. Always put a space after commas (,) and periods (.).

__Response: spaces were add after commas and periods.__

8. "offering" instead of "offerings" in "no R package offerings functions to extract"

__Response: "offerings" have been changed to "offering" 

9. The dependencies listed in the vignette don't match those listed in the DESCRIPTION file. It's actually not useful to list them in the vignette since they get automatically installed when installing the package.
__Response: We rewrite the vignette so the dependencies part was removed__

10.Never install a Bioconductor package from GitHub. The proper way to install a Bioconductor package is explained here: https://bioconductor.org/install/ Either provide that link, or show the following code in your vignette:

if (!requireNamespace("BiocManager"))
    install.packages("BiocManager")
BiocManager::install("VennDetail")
Or both. Note that the above code should not get evaluated when the vignette gets built (e.g. with R CMD build) which means that eval=FALSE should be used in the opening line of the code chunk.

__Response: We rewrite the vignette. This part have been added.__
11. Please hide the output of library(VennDetail) by using results="hide" in the opening line of the corresponding code chunk.

__Response: The results="hide" have been added.__

12. No need to call library(VennDetail) twice.

__Response: Now library(VennDetail) at the beginning.__

13. What about the empty "Support shiny now" section?

__Response: This part have been extended.__

14. Overall the vignette is too minimalist. It should show how to use VennDetail on real data.
__Response:The vignette was rewrited.__

## Coding style

15. S4 class names capitalized i.e. Venn instead of venn.

__Response: "venn" was changed to "Venn".__

16. Put spaces around <-.

__Response: spaces were added.__

17. Put a space after commas (,).

__Response: spaces were added.__

18. Please remove the trailing semicolons in your code. They are not needed and hurt readability. This applies to the code chunks in the vignette and to the examples in the man pages.

__Response: semicolons were removed.__

Thanks again.
Kai

**Comment by guokai8** [comment]
Hi @hpages ,
I just wonder if you receive the revised information I upload. 
Best,
Kai

**Comment by hpages** [comment]
Hi @guokai8 ,

Thanks for these improvements. Some of the items listed in my initial feedback still need your attention. Also there are still some important usability issues with the package. See below.

Regards,
H.

### Previous items that still need your attention

- About item 11: The undesired output of `library(VennDetail)` is still displayed. Looks like you might need to also use code chunk option `message=FALSE` in addition to `results="hide"`.

- About item 16: You still have a few places in your code with no spaces around the assignment operator e.g. in the `README.md` file etc... Also make sure to always use the left arrow (`<-`) for assignment (I see that you sometimes use `=`).

- About item 17: You now have 2 spaces after the comma in many places e.g. in the examples for `dplot` etc... It should be 1 space only.

- About item 18: Your code still has trailing semicolons in many places e.g. in the `README.md` file, in the examples for `dplot` etc... Make sure to remove them all.

### Vignette

Thanks for the improved vignette. Here are a few more things about the vignette:

19. The "Software Implementation" section is more about software usage than software implementation so its title is misleading.

20. The title of the "Support Shiny Now" subsection should probably be modified now that the shiny web app is available.

21. This sentence needs a verb and a period:
    ```
    A shiny web application VennDetail for those who are not familiar
    with the R analysis platform 
    ```

### Other issues

22. It doesn't seem right that the number of total sets for `res7` is less than for `res6` in the following example:
    ```
    library(VennDetail)
    set.seed(123)
    A <- sample(1:1000, 400, replace=FALSE)
    B <- sample(1:1000, 600, replace=FALSE)
    C <- sample(1:1000, 350, replace=FALSE)
    D <- sample(1:1000, 550, replace=FALSE)
    E <- sample(1:1000, 450, replace=FALSE)
    F <- sample(1:1000, 750, replace=FALSE)
    G <- sample(1:1000, 425, replace=FALSE)
    res6 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F))
    res7 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G))
    res6
    # === Here is the detail of Venndiagram ===
    # Total results:  970 x 2 
    # Total sets is: 62 
    #    Group Detail
    # 1 Shared    217
    # 2 Shared     72
    # 3 Shared    456
    # 4 Shared    291
    # 5 Shared    424
    # 6 Shared      5
    # ... with 964 more rows ...
    res7
    # === Here is the detail of Venndiagram ===
    # Total results:  113 x 2 
    # Total sets is: 15 
    #    Group Detail
    # 1 Shared    217
    # 2 Shared    291
    # 3 Shared    424
    # 4 Shared      5
    # 5 Shared     20
    # 6 Shared    712
    # ... with 107 more rows ...
    ```
    Note that these `Total sets` numbers (62 and 15) are in disagreement with `VennDiagram::get.venn.partitions()`:
    ```
    library(VennDiagram)
    nrow(get.venn.partitions(list(A=A, B=B, C=C, D=D, E=E, F=F)))
    [1] 63
    nrow(get.venn.partitions(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G)))
    [1] 127
    ```

23. `venndetail()` gives me an error when the number of input sets is > 8:
    ```
    H <- sample(1:1000, 750, replace=FALSE)
    I <- sample(1:1000, 425, replace=FALSE)
    res9 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G, H=H, I=I))
    # Error in new("Venn", input = x, raw = raw, sep = sep, GroupNames = GroupNames,  : 
    #   object 'res' not found
    ```
    If 8 is the maximum number of input sets supported by `venndetail()` then the function should fail gracefully with an informative error message. Also in addition to mentioning that "graphical visualization is usually limited to six or less gene sets" for the existing packages and web applications, the vignette could also mention what the limit is for VennDetail.

24. Even though most of the time you use the term "groups" to design the _input sets_ of the `venndetail()` function, sometimes you also use "set" for this. Note that you also use "sets" to design the Venn regions in the resulting diagram. This results in an overall documentation that lacks precision and clarity. Also this terminolgy is not following the usual convention which is to use "sets" for the input sets and "partitions" for the Venn regions. Please use this terminology instead of "groups" and "sets". Make sure to use it consitently everywhere (e.g. vignette, man pages, show method, etc...)

**Comment by guokai8** [comment]
Hi @hpages,
I am still working on it. I will revise it ASAP. 
Thanks!
Kai

**Comment by guokai8** [comment]
Hi @hpages 
## Previous items that still need your attention
•	About item 11: The undesired output of library(VennDetail) is still displayed. Looks like you might need to also use code chunk option message=FALSE in addition to results="hide".

### Response: “message=FALSE” was added in the chunk
•	About item 16: You still have a few places in your code with no spaces around the assignment operator e.g. in the README.md file etc... Also make sure to always use the left arrow (<-) for assignment (I see that you sometimes use =).
### Response:  all assignment operators with “= ” have been replaced with “<-”
•	About item 17: You now have 2 spaces after the comma in many places e.g. in the examples for dplot etc... It should be 1 space only.
### Response: extras spaces have been removed
•	About item 18: Your code still has trailing semicolons in many places e.g. in the README.md file, in the examples for dplot etc... Make sure to remove them all.
### Response: semicolons have been removed in all examples
## Vignette
Thanks for the improved vignette. Here are a few more things about the vignette:
19.	The "Software Implementation" section is more about software usage than software implementation so its title is misleading.
### Response: “Software Implementation” was renamed as “Software Usage”
20.	The title of the "Support Shiny Now" subsection should probably be modified now that the shiny web app is available.
### Response: “Support Shiny Now” change to “Shiny web app”
21.	This sentence needs a verb and a period:
```
A shiny web application VennDetail for those who are not familiar	
with the R analysis platform 
```
### Response: The sentence was changed to “Shiny web application”
Other issues
22.	It doesn't seem right that the number of total sets for res7 is less than for res6 in the following example:
```
library(VennDetail)
set.seed(123)
A <- sample(1:1000, 400, replace=FALSE)
B <- sample(1:1000, 600, replace=FALSE)
C <- sample(1:1000, 350, replace=FALSE)
D <- sample(1:1000, 550, replace=FALSE)
E <- sample(1:1000, 450, replace=FALSE)
F <- sample(1:1000, 750, replace=FALSE)
G <- sample(1:1000, 425, replace=FALSE)
res6 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F))
res7 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G))
res6
# === Here is the detail of Venndiagram ===
# Total results:  970 x 2 
# Total sets is: 62 
#    Group Detail
# 1 Shared    217
# 2 Shared     72
# 3 Shared    456
# 4 Shared    291
# 5 Shared    424
# 6 Shared      5
# ... with 964 more rows ...
res7
# === Here is the detail of Venndiagram ===
# Total results:  113 x 2 
# Total sets is: 15 
#    Group Detail
# 1 Shared    217
# 2 Shared    291
# 3 Shared    424
# 4 Shared      5
# 5 Shared     20
# 6 Shared    712
# ... with 107 more rows ...
``` 
Note that these Total sets numbers (62 and 15) are in disagreement with 
VennDiagram::get.venn.partitions():
``` 
library(VennDiagram)
nrow(get.venn.partitions(list(A=A, B=B, C=C, D=D, E=E, F=F)))
[1] 63
nrow(get.venn.partitions(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G)))
[1] 127
``` 
### Response: The issus was fixed.
```
library(VennDetail)
set.seed(123)
A <- sample(1:1000, 400, replace=FALSE)
B <- sample(1:1000, 600, replace=FALSE)
C <- sample(1:1000, 350, replace=FALSE)
D <- sample(1:1000, 550, replace=FALSE)
E <- sample(1:1000, 450, replace=FALSE)
F <- sample(1:1000, 750, replace=FALSE)
G <- sample(1:1000, 425, replace=FALSE)
res6 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F))
res7 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G))
res6
=== Here is the detail of Venndiagram ===
Total results:  988 x 2 
Total sets is: 63 
   Group Detail
1 Shared    453
2 Shared    993
3 Shared    961
4 Shared    758
5 Shared    626
6 Shared    361
... with 982 more rows ...
res7
=== Here is the detail of Venndiagram ===
Total results:  993 x 2 
Total sets is: 126 
   Group Detail
1 Shared    993
2 Shared    758
3 Shared    626
4 Shared    614
5 Shared    540
6 Shared    411
... with 987 more rows ...
```
The reason we got 126 compare with ```nrow(get.venn.partitions(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G)))``` got 127 is that we remove the set with 0 element.
23. venndetail() gives me an error when the number of input sets is > 8:
```
	H <- sample(1:1000, 750, replace=FALSE)
	I <- sample(1:1000, 425, replace=FALSE)
	res9 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G, H=H, I=I))
	# Error in new("Venn", input = x, raw = raw, sep = sep, GroupNames = GroupNames,  : 
	#   object 'res' not found
```
If 8 is the maximum number of input sets supported by venndetail() then the function should fail gracefully with an informative error message. Also in addition to mentioning that "graphical visualization is usually limited to six or less gene sets" for the existing packages and web applications, the vignette could also mention what the limit is for VennDetail.
### Response: We support unlimited groups after revised the code and the issue have been fixed. We also add explanation in the vignette.
```
H <- sample(1:1000, 750, replace=FALSE)
I <- sample(1:1000, 425, replace=FALSE)
res9 <- venndetail(list(A=A, B=B, C=C, D=D, E=E, F=F, G=G, H=H, I=I))
res9
=== Here is the detail of Venndiagram ===
Total results:  1000 x 2 
Total sets is: 357 
            Group Detail
1          Shared    993
2          Shared    758
3          Shared    614
4          Shared    636
5          Shared    674
6 B_C_D_E_F_G_H_I    118
... with 994 more rows ...
```
24.	Even though most of the time you use the term "groups" to design the input sets of the venndetail() function, sometimes you also use "set" for this. Note that you also use "sets" to design the Venn regions in the resulting diagram. This results in an overall documentation that lacks precision and clarity. Also this terminology is not following the usual convention which is to use "sets" for the input sets and "partitions" for the Venn regions. Please use this terminology instead of "groups" and "sets". Make sure to use it consistently everywhere (e.g. vignette, man pages, show method, etc...)
### Response: We try to use “group” to define the input datasets and “set” or “subset” to define the shared or unique partitions since we think biologist are more familiar with these terminology. We revised the vignette and man pages to make it consistently.

**Comment by hpages** [comment]
Hi @guokai8 

Thanks for making these changes.

The most important thing in software engineering is _correctness_ i.e. to make sure that the software produces correct results. This is what I mostly focused on so far when looking at the VennDetail package. Note that the incorrect results could have probably been avoided if you had a more comprehensive set of unit tests, which is something that you should definitely consider adding to the package at some point.

Now that we have reached correctness (to my knowledge), I was able to focus on other aspects. See below.

Note that some items reported previously are still not addressed properly.

Regards,
H.

## Previous items that still need your attention

- Items 16 and 17 are still not fully addressed.

- About item 24: You're still using "group", "set" and "subset" inconsistently in many places. For example the vignette says:
    ```
    Get function provides a way to extract subsets etc..
    ```
    but the man page says:
    ```
    Get the contents of a specific set from venndetail object
    ```
    I will reiterate my concern that the use of "set" is ambiguous in this context as it's not clear whether it refers to the input sets (what you call "groups") or to the subsets defined by the Venn regions. Using "subset" would help disambiguate.
    Also:
    ```
    library(VennDetail)
    set.seed(123)
    A <- sample(20, 12)
    B <- sample(20, 15)
    C <- sample(20, 9)
    venn <- venndetail(list(A=A, B=B, C=C))
    Get(venn, set=c("A_B", "Shared"))
    #     Group Detail
    # 1  Shared     15
    # 2  Shared     19
    # 3  Shared     10
    # 4  Shared     18
    # 5  Shared      9
    # 6     A_B     14
    # 7     A_B      3
    # 8     A_B     11
    # 9     A_B      5
    # 10    A_B      4
    ```
    The `Group` column contains **subset** names (e.g. `Shared`, `A_B`) not **group** names so this column should be called "subset". Also the `set` argument of the `Get()` accessor should be renamed `subset` (or `subsets` since more than one subset name can be supplied). The man page would need to be updated to reflect these changes. Note that the description of the `min` argument ("Minimal number of shared sets") lacks precision and is also using "set" ambiguously. A more accurate description of this argument could be something like "The minimum number of input groups that a subset must belong too". Finally to add to the confusion, the vignette says "The parameter `group` asks the users to give the subset names to extract." This also needs to be corrected.

25. The `vennpie()` function and its documentation (in the man page and in the vignette) have the same kind of issues as `Get()`.

26. The `getFeature()` function and its documentation also need to be made consistent with `Get()`.

27. `Get()` is actually a bad name for a Venn object accessor returning subsets. It's way too generic! Also why would you use such a generic name for this accessor and a specific name for the `getFeature()` accessor. Both accessors should have a specific name that indicates what they access. Also please use a consistent naming style for both. In particular don't start your function names with a capital letter.

28. The name of the `make.table()` function is also too generic. The name of the original `make.truth.table()` function from the VennDiagram package is a better one. You could actually use this name since VennDiagram doesn't export `make.truth.table` (so there will be no name clash).

29. Please implement a `summary()` method for Venn objects that does what `detail()` does and get rid of `detail()`. `summary()` is an S3 generic defined in the base package. There is no need to introduce a new generic function for that.

30. Note that your name is repeated in the Author section of the man page for `Get()`.

31. Some minor issues in the man page for `make.table()`:
    - The name of the VennDiagram package is misspelled (VennDaigram).
    - The data frame returned by `make.table()` has `2^length(x) - 1` rows, not `2^length(x)`.
    - About this function call: `make.table(x = list(A = A, B = B, C = C))`. It is not considered good style to name the argument when the function being called has a single argument. Note that the man page for `get.set()` contains the same call to `make.table()`.

32. Many problems with the `get.set()` function and its man page:
    - The name of the function: why not be consistent with `make.table()` and use `make` instead of `get` in the name?
    -  It returns the Venn **subsets** so `set` needs to be replaced with `subsets` in the name (note the plural form).
    - The subset named `Shared` in the output of other functions is now named `A_B_C` (if the input groups were `A`, `B`, and `C`). Striving for consistency is an important part of good software design.
    - These lines from the example in the man page:
        ```
        x = list(A = A, B = B, C = C)
        tab <- make.table(x = list(A = A, B = B, C = C))
        out <- get.set(x = x, tab = tab)
        ```
        should be:
        ```
        x <- list(A = A, B = B, C = C)
        tab <- make.table(x)
        out <- get.set(x, tab)
        ```
        or:
        ```
        x <- list(A = A, B = B, C = C)
        out <- get.set(x, make.table(x))
        ```
        Striving for code simplicity and clarity is considered good practice.
    - The `tab` argument should be optional (e.g. with `NULL` as default value). When the argument is omitted (or set to `NULL`), the function should call `make.table()` internally. The above example would then become:
        ```
        x <- list(A = A, B = B, C = C)
        out <- get.set(x)
        ```
    - The Description section in the man page is insufficient:
        ```
        Description:

             get set
        ```
    - The Value section could be more precise e.g.
        ```
        A list of subsets. The names on the list are the subset names and the
        list elements are the subset details.
        ```
    - Not clear what colnames you are referring to in the description of the `sep` argument. Would be much clearer to say something like "when concatenating group names into subset names". It will also be consistent with the terminology used everywhere else in the package.

**Comment by guokai8** [comment]
Hi @hpages,
Thank you so much for your kindly suggestion which help me a lot. I try to address all the issues. Maybe there are still some issues left since this is the first time I submit package to bioconductor. Please help me to point out any bug you find.
Below are the response:
## Previous items that still need your attention
•	Items 16 and 17 are still not fully addressed.
### Response:  I remove two space and replace the “=” to “<-” .
•	About item 24: You're still using "group", "set" and "subset" inconsistently in many places. For example the vignette says:
•	Get function provides a way to extract subsets etc..
but the man page says:
Get the contents of a specific set from venndetail object
I will reiterate my concern that the use of "set" is ambiguous in this context as it's not clear whether it refers to the input sets (what you call "groups") or to the subsets defined by the Venn regions. Using "subset" would help disambiguate.
Also:
```
library(VennDetail)
set.seed(123)
A <- sample(20, 12)
B <- sample(20, 15)
C <- sample(20, 9)
venn <- venndetail(list(A=A, B=B, C=C))
Get(venn, set=c("A_B", "Shared"))
#     Group Detail
# 1  Shared     15
# 2  Shared     19
# 3  Shared     10
# 4  Shared     18
# 5  Shared      9
# 6     A_B     14
# 7     A_B      3
# 8     A_B     11
# 9     A_B      5
# 10    A_B      4
```
The Group column contains subset names (e.g. Shared, A_B) not group names so this column should be called "subset". Also the set argument of the Get() accessor should be renamed subset (or subsets since more than one subset name can be supplied). The man page would need to be updated to reflect these changes. Note that the description of the minargument ("Minimal number of shared sets") lacks precision and is also using "set" ambiguously. A more accurate description of this argument could be something like "The minimum number of input groups that a subset must belong too". Finally to add to the confusion, the vignette says "The parameter group asks the users to give the subset names to extract." This also needs to be corrected.
### Response: _Get_ function now change to _getSet_. I change all “set” to “subset” and also change the “Group” column to “Subset”. The parameter “group” now change to “subset”.  The description of “min” argument is changed to “The minimum number of input groups that a subset must belong to. e.g. min = 2 will only report those subsets with elements shared by 2 or more input groups.” The parameter “group” in the vignette now change to “subset”
```
library(VennDetail)
set.seed(123)
A <- sample(20, 12)
B <- sample(20, 15)
C <- sample(20, 9)
venn <- venndetail(list(A=A, B=B, C=C))
getSet(venn, subset=c("A_B", "Shared"))
  Subset Detail
1 Shared      6
2 Shared     17
3 Shared      1
4 Shared     20
5    A_B      8
6    A_B     16
7    A_B      7
8    A_B      5
```
25.	The vennpie() function and its documentation (in the man page and in the vignette) have the same kind of issues as Get().
### Response: “group” change to “subset”. The description of parameter “min” was changed to same description with _getSet_ function

26.	The getFeature() function and its documentation also need to be made consistent with Get().
### Response: “group” change to “subset”.
27.	_Get_ is actually a bad name for a Venn object accessor returning subsets. It's way too generic! Also why would you use such a generic name for this accessor and a specific name for the _getFeature()_ accessor. Both accessors should have a specific name that indicates what they access. Also please use a consistent naming style for both. In particular don't start your function names with a capital letter.
### Response: _Get_ function now change to _getSet_
28.	The name of the make.table() function is also too generic. The name of the original make.truth.table() function from the VennDiagram package is a better one. You could actually use this name since VennDiagram doesn't export make.truth.table (so there will be no name clash).
### Response: I redefine the _make.table_ function to _.make.table_
29.	Please implement a _summary()_ method for Venn objects that does what _detail()_ does and get rid of _detail()_. summary() is an S3 generic defined in the base package. There is no need to introduce a new generic function for that.
### Response: _summary_ function was created. I want first keep _detail_ function and will add new method in it.
30.	Note that your name is repeated in the Author section of the man page for Get().
### Response: This issue was fixed
31.	Some minor issues in the man page for make.table():
o	The name of the VennDiagram package is misspelled (VennDaigram).
### Response: Fixed
o	The data frame returned by make.table() has 2^length(x) - 1 rows, not 2^length(x).
### Response: The function I defined include the step remove the rows with all FALSE value. I change the return part.
o	About this function call: make.table(x = list(A = A, B = B, C = C)). It is not considered good style to name the argument when the function being called has a single argument. Note that the man page for _get.set()_ contains the same call to make.table().
### Response:  make.table now change to .make.table without example.
32.	Many problems with the _get.set()_ function and its man page:
o	The name of the function: why not be consistent with make.table() and use make instead of get in the name?
### Response: _get.set_ function was renamed as _make.subset_
o	It returns the Venn subsets so set needs to be replaced with subsets in the name (note the plural form).
### Response: _set_ was changed to _subset_
o	The subset named Shared in the output of other functions is now named A_B_C (if the input groups were A, B, and C). Striving for consistency is an important part of good software design.
### Response: Fixed
o	These lines from the example in the man page:
```
o	x = list(A = A, B = B, C = C)
o	tab <- make.table(x = list(A = A, B = B, C = C))
o	out <- get.set(x = x, tab = tab)
```
should be:
```
x <- list(A = A, B = B, C = C)
tab <- make.table(x)
out <- get.set(x, tab)
```
or:
```
x <- list(A = A, B = B, C = C)
out <- get.set(x, make.table(x))
```
Striving for code simplicity and clarity is considered good practice.
### Response: the example code have been changed
```
x <- list(A = A, B = B, C = C)
out <-  make.subset(x)
```
o	The tab argument should be optional (e.g. with NULL as default value). When the argument is omitted (or set to NULL), the function should call make.table() internally. The above example would then become:
```
o	x <- list(A = A, B = B, C = C)
o	out <- get.set(x)
```
### Response: tab argument have been removed
o	The Description section in the man page is insufficient:
o	Description:
o	
o	     get set
o	The Value section could be more precise e.g.
o	A list of subsets. The names on the list are the subset names and the
o	list elements are the subset details.
###  Response: The Value was changed to “A list of subsets. The names on the list are the subset names and the” 
o	Not clear what colnames you are referring to in the description of the sep argument. Would be much clearer to say something like "when concatenating group names into subset names". It will also be consistent with the terminology used everywhere else in the package.
### Response: change to the way you suggestion.

Thanks again!
Kai

**Comment by hpages** [comment]
Hi @guokai8 ,

Thanks for all these changes and improvements. Overall, things look much better now.

Cheers,
H.

**Comment by guokai8** [comment]
Hi @hpages,
Thank you so much for all your suggestions.
Cheers,
Kai

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/guokai8.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VennDetail")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VennDetail

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
